### ISSUE TITLE
Kubernetes how to limit the pods restart count

### ISSUE THREAD

**Issue by killy001** [kubernetes/kubernetes#49466]
**In kubernetes, how can I limit the pods restart count ?** 

Now, when the pods exit with none zero or other reasons ,then it will be restarted according to restartPolicy (Always、OnFailure、Never).

From the source code, there is a property (restart) to add the restart count. I think that when the property equals to the number I expect to restart count, then the pod will be deleted. Weather it will work? Or there are other solutions to work this problem? Thank you !!!

**Comment by dixudx** [comment]
@killy001 Currently there is no way to limit the pod restart counts.

That [restart count](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1766-L1782) you mentioned is used for GC, which is calculated from dead containers.

**Comment by asarkar** [comment]
This would be a good feature to have, any thoughts?

**Comment by chinglinwen** [comment]
I have pod restart over 1000, and it seems cause cidr not available.

**Comment by OndraZizka** [comment]
Hi, I google this up. How should I stop an infinite restart loop? It's wasting the resources, and `kubectl rollout status ...` waits infinitely.

**Comment by efirdman** [comment]
Can someone explain why this was closed? Sims like a very reasonable request. Our test system keeps restarting the Pods over and over and over.
I think it should be a setting to set a maximum number of restarts or maximum number of restarts in a selected time period (hour/ day/ month)

**Comment by m-no-2017** [comment]
I would also say that this is a reasonable feature request.

Our current usage of Kubernetes is heavily geared to development, so it would be nice to limit restarts in specific namespaces. To this day I have to write scripts as workaround, which works but everyone could have a benfit from an implemented feature.

**Comment by gturetsky** [comment]
Agreed - I think this would be a great/useful feature.

**Comment by Xyrion** [comment]
Any updates on if this feature will be created?

**Comment by dixudx** [comment]
@Xyrion PR #68745 is addressing this feature. But we need to have a proposal for further discussions on  how to better implement this feature. I am working on it and will send it out in a few days.

**Comment by m-no-2017** [comment]
The event loop of a pod already counts (re-)starts (Type: Normal, Reason: Started) and the JSON structure holds the value (Count-1) in [.status.containerstatuses.restartCount].

An example would be another field in the deployment field named something like "restartLimit: (int)", with reference to the mentioned information.

Instead of a event like "CrashLoopBackoff" it could be something like "RestartLimitExceeded" and the behaviour would be identical to a "Completed" state of a job. Therefore we would not lose the information of the faulty deployment/pod and could keep away pressure on the kubelet and scheduler + controller-manager.

**Comment by alena1108** [comment]
Very interested to see this feature in. Similar to kubelet and scheduler, for the systems integrating with k8s apis, constantly crashing pods cause increased load for the controllers subscribing to the pod events. Any updates on the proposal/pr? @dixudx

**Comment by bahho** [comment]
We've even seen restart counts >6k.
Definitely a must feature imho.

**Comment by azerbe** [comment]
This would be very helpful.

**Comment by killy001** [comment]
@dixudx  Very glad to see this feature adopted and implemented. It's my honor to contribute my suggestion for kubernetes organization. Thank you very much.

**Comment by luarx** [comment]
I would appreciate that feature also. As @bahho said, a pod can be restarted a lot of times!

**Comment by yivo** [comment]
I am also interested in that feature. Would be good for me to use along with `RestartPolicy: OnFailure`.

**Comment by mr-karan** [comment]
+1 handy feature to have.

**Comment by AbdulR3hman** [comment]
we have the same issue. A pod with buggy code had been trying to restart for over 15000 without noticing it causing issue with none-faulty deployment due to capacity limitation. We have a small cluster with roughly 400 nodes capacity. 

+1

**Comment by gugahoi** [comment]
Not sure if this has a different solution but an example here:

- Pod has an init container that does DB migrations
- After init is successful app container starts and connects to DB
- Somehow db gets out of wack (rolled back by an external process for example)
- App container starts restarting as it is not able to run on older DB schema
- Stuck in forever restarting loop as init container is not invoked and DB migrations never take place again.

A `restart limit` would solve this as deleting the pod means the init container would run again.

**Comment by thdrnsdk** [comment]
it looks like almost done 

https://github.com/kubernetes/kubernetes/pull/79334

I really hope this feature will be included in the next release.

**Comment by McCoyAle** [comment]
/remove-lifecycle stale

Due to PR #79334

**Comment by ajay1206** [comment]
+1

**Comment by gogineni99** [comment]
+1

**Comment by vivekpd15** [comment]
+1

**Comment by ThaSami** [comment]
+1

**Comment by yangqiang** [comment]
`Job` provide a restart policy with a `.spec.backoffLimit` parameter to limit the restart times. Maybe you can use `Job` instead of bare `Pod`.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
