### ISSUE TITLE
kubelet try pull new version api-server image,when i destroy cluster and rebuild it

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#49462]
Environment:

Kubernetes version (use kubectl version): v1.7.0
Cloud provider or hardware configuration**:
OS (e.g. from /etc/os-release): CentOS 7
Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
Install tools: Kubeadm
Others:
docker version : Docker version 1.12.6,
My RPM version :
docker-1.12.6-16.el7.centos.x86_64.rpm
kubectl-1.7.0-0.x86_64.rpm
kubernetes-cni-0.5.1-0.x86_64.rpm
kubeadm-1.7.0-0.x86_64.rpm
kubelet-1.7.0-0.x86_64.rpm

local images
[root@k8s-master ~]# docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/heapster-grafana-amd64          v4.4.1              0467cb9967dd        3 days ago          151.5 MB
gcr.io/google_containers/heapster-influxdb-amd64         v1.1.1              dbb7a2fb4736        3 days ago          11.59 MB
gcr.io/google_containers/heapster-amd64                  v1.3.0              78ae41d7ba79        3 days ago          68.11 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.4              db8241b72199        10 days ago         41.81 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.4              3e08c89ee425        10 days ago         49.38 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.4              1813641c1a74        10 days ago         41.41 MB
gcr.io/google_containers/flannel                         0.5.5               6e1cb07df40c        11 days ago         26.29 MB
gcr.io/google_containers/kubernetes-dashboard-amd64      v1.6.1              2769cef613d2        11 days ago         134.4 MB
gcr.io/google_containers/kube-discovery-amd64            1.0                 e210dbc7bd64        11 days ago         134.2 MB
gcr.io/google_containers/etcd-amd64                      3.0.17              8acba0dd4211        11 days ago         168.9 MB
gcr.io/google_containers/kube-proxy-amd64                v1.7.0              0f6b58eda451        11 days ago         114.7 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.7.0              fbfc3889420e        11 days ago         77.16 MB
gcr.io/google_containers/hyperkube-amd64                 v1.7.0              31c3a3021de8        11 days ago         614.5 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.7.0              ddccb9a6d095        11 days ago         137 MB
gcr.io/google_containers/pause-amd64                     3.0                 7611b1b0ae92        11 days ago         746.9 kB
gcr.io/google_containers/kube-apiserver-amd64            v1.7.0              b1984f7f569a        11 days ago         185.2 MB
kubelet-rpm-builder                                      latest              f0bb05c41a21        11 days ago         449.1 MB
quay.io/coreos/flannel                                   v0.8.0-amd64        9db3bab8c19e        12 days ago         50.73 MB
docker.io/fedora                                         24                  f623aaef07f0        8 months ago        204.4 MB

i build the cluster successful ,i want to change the pod-network-cidr ,i do the following step to destroy my cluster

1. uninstall app pods (include flannel ,dashboard )
kubectl delete -f file.yml
2. reset nodes (on every node)
kubeadm reset
3. reset master node

--------------------------

and i do this build new cluster

kubeadm init --pod-network-cidr=172.16.0.0/16 --apiserver-advertise-address 10.132.41.234

it seems api-server can not start ,and i checked logs ,find the kubelet try pull the api-server:v1.7.2 instead of using the local v1.7.0 image ,why?

Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.882703   18380 status_manager.go:325] Ignoring same status for pod "kube-apiserver-k8s-master_kube
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883030   18380 kubelet.go:1605] Creating a mirror pod for static pod "kube-apiserver-k8s-master_ku
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883454   18380 server.go:351] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-master
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883494   18380 server.go:351] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-master
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883530   18380 server.go:351] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-master
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883642   18380 round_trippers.go:405] POST https://10.132.41.234:6443/api/v1/namespaces/kube-syste
Jul 24 09:59:37 k8s-master kubelet[18380]: E0724 09:59:37.883694   18380 kubelet.go:1607] Failed creating a mirror pod for "kube-apiserver-k8s-master_kube-s
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.883773   18380 volume_manager.go:340] Waiting for volumes to attach and mount for pod "kube-apiser
Jul 24 09:59:37 k8s-master kubelet[18380]: I0724 09:59:37.930803   18380 config.go:101] Looking for [api file], have seen map[file:{}]
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.030841   18380 config.go:101] Looking for [api file], have seen map[file:{}]
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.130890   18380 config.go:101] Looking for [api file], have seen map[file:{}]
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.184078   18380 volume_manager.go:369] All volumes are attached and mounted for pod "kube-apiserver
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.184120   18380 kuberuntime_manager.go:428] Syncing Pod "kube-apiserver-k8s-master_kube-system(0737
Jul 24 09:59:38 k8s-master kubelet[18380]: mote-Extra- --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --service-cluster-ip-range=10.96.0.0
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.184480   18380 kuberuntime_manager.go:457] Container {Name:kube-apiserver Image:gcr.io/google_cont
Jul 24 09:59:38 k8s-master kubelet[18380]: onMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.184495   18380 kuberuntime_manager.go:548] computePodContainerChanges got {CreateSandbox:false San
Jul 24 09:59:38 k8s-master kubelet[18380]: [],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshol
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.184617   18380 kuberuntime_manager.go:715] Creating container &Container{Name:kube-apiserver,Image
Jul 24 09:59:38 k8s-master kubelet[18380]: ext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[],TerminationMessagePolicy:File,} in pod kube-apiserver-k8
Jul 24 09:59:38 k8s-master kubelet[18380]: E0724 09:59:38.186266   18380 kuberuntime_manager.go:718] container start failed: ImagePullBackOff: Back-off pull
Jul 24 09:59:38 k8s-master kubelet[18380]: E0724 09:59:38.186304   18380 pod_workers.go:182] Error syncing pod 0737e0c4303d088d5c7fb0e19f98b247 ("kube-apise
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.186351   18380 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.186377   18380 server.go:351] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.230838   18380 config.go:101] Looking for [api file], have seen map[file:{}]
Jul 24 09:59:38 k8s-master kubelet[18380]: W0724 09:59:38.265283   18380 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.265563   18380 kubelet.go:2133] Container runtime status: Runtime Conditions: RuntimeReady=true re
Jul 24 09:59:38 k8s-master kubelet[18380]: E0724 09:59:38.265605   18380 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:Net
Jul 24 09:59:38 k8s-master kubelet[18380]: I0724 09:59:38.330846   18380 config.go:101] Looking for [api file], have seen map[file:{}]
lines 966-1001/1001 (END)

**Comment by harryge00** [comment]
@justlooks  How did you solve this?
