### ISSUE TITLE
No Authn/z in CoreOS.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#4947]
CoreOS distro does: 
  - `kube-apiserver --address=0.0.0.0 --port=8080` 
  - `kubelet --api_servers=$APISERVER_IP:8080`
 Therefore, anything on the cluster's network can talk to apiserver with no authn/z.

By contrast, other distros do:
  -  `kube-apiserver --address=127.0.0.1 --port=8080 --authed_port=7080`
  - `kubelet --api_servers=$APISERVER_IP:7080`
  - distribute a token to kubelet to use with the authed port
 
This can be solved by either making CoreOS like the other distros, or by making the `--port` port be authenticated by default.

**Comment by pires** [comment]
Whenever you do this, please update CoreOS docs. Thanks.
