### ISSUE TITLE
(*IntOrString) IntValue() always returns zero when IntOrString is a percentage

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#49487]
https://github.com/kubernetes/apimachinery/blob/21807b270ec15d19215659a5caa08b17f66d6f44/pkg/util/intstr/intstr.go#L104-L107
https://play.golang.org/p/YQMgFOpopM

There is no added value by that conversion, even worse it can be misused.

@kubernetes/sig-api-machinery-bugs

**Comment by k82cn** [comment]
should we use `GetValueFromIntOrPercent ` in such case?

https://github.com/kubernetes/apimachinery/blob/21807b270ec15d19215659a5caa08b17f66d6f44/pkg/util/intstr/intstr.go#L149

**Comment by lavalamp** [comment]
@kargakis I do not think this is a bug. 25% == .25 and int(.25) == 0. ;)

Even in the case where the user puts in something like 100% I do not think it's a bug. Users should not put strings like "25%" into intOrString and expect to get the integer 25 out. Likely a user doing that is confused about what format the field takes in.

@k82cn I am not sure why the function GetValueFromIntOrPercent exists, and I bet I am not going to like the answer :)

**Comment by kargakis** [comment]
> @kargakis I do not think this is a bug. 25% == .25 and int(.25) == 0. ;)

No. First, this depends on how you do the rounding. If you are rounding up (MaxSurge in Deployments), this is 1. Then, the replica size of the deployment also plays a part. 25% of a controller with 1 replica, is different from a controller with 4 replicas, etc.

**Comment by kargakis** [comment]
Also, the fact that IntValue returns 0 for every percentage has nothing to do with any logic. It's purely because the conversion errors out: https://play.golang.org/p/j6Q4m1krDv

**Comment by lavalamp** [comment]
@kargakis the first line there was supposed to be a joke, sorry. :) I know that the actual reason for returning 0 is the % sign means it is not an int.

More seriously: I actually agree with the parsing function that percentages are not ints. Users who want to do this should not use IntOrString. Is there a place in the API that wants to do this?

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/86172 to ensure all in-tree callers only call this when the type is Int (or verify it is a parseable number first), and to update the method documentation
