### ISSUE TITLE
Update to Go 1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#49484]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

This is a followup on https://github.com/kubernetes/kubernetes/issues/38228, but for Go 1.9

We should do the same kind of testing now to possibly catch bugs in either Go or Kubernetes when doing this kind of dependency version bump.

Ideally we'd have automated tests against Go tip (https://github.com/kubernetes/test-infra/issues/1399), but we don't have that at the moment, so we have to do it kind of manually.

We should also decide which k8s version we should target. k8s v1.8 or v1.9?

What Go versions have been used so far?
 - Kubernetes v1.7.0 - go1.8.3 [ref](https://github.com/kubernetes/kubernetes/blob/v1.7.0/build/build-image/cross/Dockerfile)
 - Kubernetes v1.6.0 - go1.7.5 [ref](https://github.com/kubernetes/kubernetes/blob/v1.6.0/build/build-image/cross/Dockerfile)
 - Kubernetes v1.5.0 - go1.7.4 [ref](https://github.com/kubernetes/kubernetes/blob/v1.5.0/build-tools/build-image/cross/Dockerfile)
 - Kubernetes v1.4.0 - go1.6.3 [ref](https://github.com/kubernetes/kubernetes/blob/v1.4.0/build/build-image/cross/Dockerfile)
 - Kubernetes v1.3.0 - go1.6.2 [ref](https://github.com/kubernetes/kubernetes/blob/v1.3.0/build/build-image/cross/Dockerfile)
 - Kubernetes v1.2.0 - go1.4.2 [ref](https://github.com/kubernetes/kubernetes/blob/v1.2.0/build/build-image/cross/Dockerfile)

Seems like the trend has been to stay on the same Go version for two releases and then bump.
That'd mean we'd switch to Go1.9 in k8s v1.9

Everyone happy with that? Or is there any reason for us to go start using go1.9 in k8s v1.8?

In any case, we should indeed start testing go1.9 out now...

cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-testing-feature-requests @kubernetes/sig-release-feature-requests @bradfitz @jessfraz @kubernetes/sig-scalability-feature-requests

**Comment by jessfraz** [comment]
Let me know if you find any bugs

**Comment by timothysc** [comment]
FWIW pretty tight to code-freeze I would prefer punting out a cycle fwiw.

**Comment by luxas** [comment]
I don't think we're that close to code freeze given that we have 5 (of 8) weeks left in this coding cycle
But I'm happy to defer this to v1.9 if others think that.

I guess the main reason for a bump would be scalability goals, but I'm not sure we have the need to expand above 5000 (and that Go would be the bottleneck in that case) for v1.8

**Comment by rmmh** [comment]
[Mid-stack inlining](https://docs.google.com/presentation/d/1Wcblp3jpfeKwA0Y4FOmj63PW52M_qmNqlQkNaLj0P5o/edit#slide=id.g1b2157b5d1_3_246) made the Go benchmarks 9% faster with 15% larger binaries. I'm interested to see how that affects our numbers.

**Comment by bradfitz** [comment]
@rmmh, mid-stack inlining was not included in Go 1.9. It made the compiler too slow.

It's being targeted to GO 1.10 now instead, after some compiler optimization work.

**Comment by rmmh** [comment]
Oh, thanks for the correction!

Regardless, we need to run the scalability tests against the RC so we can report issues earlier-- the last upgrade was particularly painful because of an HTTP regression that we caught *way* too late.

**Comment by luxas** [comment]
@rmmh yeah. I filed #49506 for that now

**Comment by ixdy** [comment]
yeah, my recollection is that the Go releases usually occur too late in our release cadence and end up getting bumped to the next Kubernetes release. (Also we inevitably find something wrong, though testing RCs would help with that. Though I'm not sure anyone has cycles to test RCs and fix all of the issues that do come up.)

**Comment by cblecker** [comment]
Based on our current time frame, it looks like go1.9 support will have to slip to k8s 1.9. https://github.com/kubernetes/kubernetes/pull/51375 is open to dig into and start things testing, but there's a number of things that have to move.. I'll try to document those this time around to help with future go version bumps.

So far:
- bazel build rules needed to be updated to support go1.9 (https://github.com/bazelbuild/rules_go/pull/753)
- bazel version possibly needs to be updated?
- some of our custom bazel rules broke

**Comment by cblecker** [comment]
When done, we should update this: https://git.k8s.io/community/contributors/devel/development.md#go

**Comment by ixdy** [comment]
Updating the `rules_go` dependency is blocked pending bazel 0.6.0 - #52677.

**Comment by luxas** [comment]
@ixdy Can we upgrade to 0.6.0 now?
Does bazel 0.6.0 have multiarch support btw?

**Comment by ixdy** [comment]
We can't update to depend on bazel 0.6.0+ until we can figure out how to support different versions of the bazelbuild and kubekins-e2e images in PR jobs in prow based on what branch is being tested. cc @kubernetes/sig-testing-feature-requests

**Comment by BenTheElder** [comment]
Noting that we're working on branching jobs, @krzyzacy is testing one option here: https://github.com/kubernetes/test-infra/pull/4855

**Comment by luxas** [comment]
@ixdy @cblecker I approved this for v1.9, this is something we definitely want in order to keep up with Go (and for improved performance)

**Comment by BenTheElder** [comment]
we're starting to use the forked images now /cc @krzyzacy, this should be more feasible very soon

**Comment by cblecker** [comment]
We've identified a failing test as a result of the WIP PR to upgrade the codebase to go1.9:
https://github.com/kubernetes/kubernetes/issues/54020

The admission webhook test fails with certificate errors under go1.9.1, but runs successfully under go1.8.3.

cc: @jessfraz who wanted to be alerted to potential bugs

**Comment by dims** [comment]
@jessfraz @cblecker - please see https://github.com/kubernetes/kubernetes/pull/54030 for a possible fix
