### ISSUE TITLE
Use CNI v0.6.x in Kubernetes v1.9.0

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#49480]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

It's time to decide which CNI version to use for v1.8.
We should do early in the cycle to catch regressions in the CNI <-> k8s integration.
We don't want the thing that happened in v1.6 to occur again, so we need to be very careful.

Currently, we're using v0.5.1 and consuming tarballs via a sha pushed by this `Makefile`: https://github.com/kubernetes/kubernetes/blob/master/build/cni/Makefile

We did this earlier because CNI didn't provide binary artifacts for all platform that kubernetes supports.
Since v0.5.2, they do, so we can get rid of `build/cni/Makefile` :tada:

Also, we don't want to consume a strange SHA as the version indicator, instead we want to use a version number _and_ possibly a SHA for verification.

I guess it would make sense to bump CNI to v0.5.2 for the v1.8 cycle.
Agree/disagree? It's not clear to me when v0.6.0 will be released, but the rc has been out for some time already...

cc @kubernetes/sig-network-feature-requests @ixdy @freehan @kubernetes/sig-cluster-lifecycle-feature-requests @dcbw

**Comment by luxas** [comment]
cc @bboreham

**Comment by bboreham** [comment]
CNI v0.6 should be out this week

There are a bunch of small fixes; also this is the first version that includes the portmap plugin.

**Comment by luxas** [comment]
@bboreham So you're advocating for using v0.6?
Well, that's fine by me.

I just want to be sure we track all the action items correctly and make sure we test everything properly in time.

What we (at least) need to do:
 - [ ] Bump the CNI vendored libraries
 - [ ] Remove `build/cni`
 - [ ] Update all binary download references to v0.5.1 to v0.6.0
 - [ ] Update debs/rpm packages to use v0.6.0 
 - [ ] Make sure all CNI network providers are compatible with the CNI v0.3.1 spec
 - [ ] Make sure CRI properly integrates with CNI v0.6.0

More action items?

**Comment by timothysc** [comment]
Is there a changelog we should be following? 
I'd like to properly build the rpms now as well.

**Comment by bboreham** [comment]
No changelog file but releases are visible in https://github.com/containernetworking/cni/releases and https://github.com/containernetworking/plugins/releases and announced on the CNI mailing list and Kubernetes sig-network mailing list.

**Comment by luxas** [comment]
CNI v0.6.0 is out https://github.com/containernetworking/cni/releases/tag/v0.6.0 :tada:, but it's too late in the cycle for us to update.
I think we should target k8s to use v0.6.x in v1.9 (and then include portmap, etc. etc.)

@dixudx is this something you'd want to work on?

**Comment by dixudx** [comment]
@luxas I would like to work on this. Thanks. Will send out a PR later.

**Comment by roberthbailey** [comment]
Shouldn't we ask @kubernetes/sig-network-misc which CNI version we should be supporting with 1.8? And try to make the CNI version consistent across all of the install tools?

**Comment by dixudx** [comment]
> Shouldn't we ask @kubernetes/sig-network-misc which CNI version we should be supporting with 1.8? And try to make the CNI version consistent across all of the install tools?

@roberthbailey +1. Waiting for the reply.

**Comment by luxas** [comment]
@roberthbailey I'm not dictating, here I'm asking what version is targeted :smile:.
Seems like folks are happy with this; no objections so far.
Think it's definitely too late to upgrade CNI at this point, so upgrading as @bboreham mentioned makes sense to me in v1.9

**Comment by feiskyer** [comment]
> Think it's definitely too late to upgrade CNI at this point, so upgrading as @bboreham mentioned makes sense to me in v1.9

Agreed, time too late now. v1.9 is preferred.

**Comment by danehans** [comment]
@feiskyer I am part of a team adding IPv6 support to k8s. CNI 0.6.0 is needed for assigning IPv6 addresses to pods. Several users are interested in k8s IPv6 support. It would be very helpful to get the cni bump into 1.8. However, I respect your decision if you choose to wait until 1.9.

**Comment by feiskyer** [comment]
@danehans Is IPv6 feature a blocker of 1.8? 

/cc @kubernetes/sig-network-misc

**Comment by danehans** [comment]
@feiskyer I'm a relatively new contributor. Can you help me understand or point me to documentation that explains what qualifies a feature as a blocker for a release? IPv6 is a feature several users are waiting for us to release.

**Comment by luxas** [comment]
@danehans So technically we can still do this in time for v1.8
I didn't just get an overwhelming "YES! WE WANT THIS!" response from @kubernetes/sig-network-misc when I brought up the matter in this issue, so my obvious interpretation is that this wasn't useful enough to be prioritized.

Worth keeping in mind that CNI bumps tend to break things and has done so some times in the past, which of course has been really annoying, so if we do this we have to be super-careful and start testing everything _today_, send various PSAs, make sure all CNI 3rd party providers support v0.6.0, that CRI is ready for such a change, that sig-cluster-lifecycle are looped in on packaging, sig-pm has visibility into it, etc etc

That said, I'm very happy to discuss this (that's why I opened this issue :smile:) and @dixudx already opened the PR (thanks!)
An absolute requirement for approving this is having an Owner with a big O for this transition.
Do we have such a person?

However, I don't see a features issue for IPv6: https://github.com/kubernetes/features/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ipv6
Which in my mind suggests that it's not tracked as a "valid" feature for v1.8 by SIG PM
cc @idvoretskyi @jdumars @apsinha

cc @kubernetes/sig-node-feature-requests

**Comment by danehans** [comment]
@luxas I apologize for not seeing this earlier. Thanks for helping me understand the potential impact of the change.

@dcbw does it make sense for some like yourself to be the "Owner" that @luxas references?

**Comment by thockin** [comment]
We really do want this, the question is whether we can do it safely in the time remaining.  Is there a PR ready with e2e results?

**Comment by dixudx** [comment]
@thockin PTAL PR #51250.

**Comment by tobad357** [comment]
@luxas I would like to put up a "YES WE WANT THIS"
The reason being when K8S moved to the CNI plugin the fix for 
"#20096 Mitigate impact of unregister_netdevice kernel race" got rolled back as the responsibility of setting a bridge to promiscuous mode was moved from the kubelet to the CNI layer.
CNI didn't received support for promiscuous until 0.6 which means currently we hit the issue frequently and can't deploy K8S 1.7 to production until there is a workaround

**Comment by klausenbusk** [comment]
> can't deploy K8S 1.7 to production until there is a workaround

You can just bump the CNI binaries manually, that what I did and it is working fine.

I'm using bootkube btw.

**Comment by tobad357** [comment]
@klausenbusk thanks for the tip.
We would of course prefer to run on a supported setup, but if it doesn't get merged into 1.8 then we will probably do as you suggest

**Comment by timothysc** [comment]
It's too late in the cycle imo, and we haven't even bumped our .rpm and .deb deliverables.  There is still no owners for the build products.

**Comment by dims** [comment]
Here's a note from @justinsb on another issue - https://github.com/kubernetes/kubernetes/issues/52331#issuecomment-331642854

**Comment by justinsb** [comment]
As it seems we probably wanted this in 1.8 but ran out of time, shall we get this into 1.9 now?

**Comment by luxas** [comment]
YES! :smile:

**Comment by luxas** [comment]
@thockin Can you take a look at https://github.com/kubernetes/kubernetes/pull/51250 and shepherd it (and other required changes) in time for v1.9?

I approved this for v1.9 now

**Comment by luxas** [comment]
We need to send an email to kubernetes-dev about this @dixudx can you please do that?

Also, the debs/rpms in kubernetes/release needs to be updated. cc me on that PR

**Comment by luxas** [comment]
Pinging CNI & CRI plugin maintainers
[ ] Weave (@bboreham)
[ ] Calico (@caseydavenport)
[ ] Canal (@tomdee)
[ ] Flannel (@aaronlevy)
[ ] Romana (@chrismarino)
[ ] cri-containerd (@Random-Liu)
[ ] cri-o (@runcom)
[ ] frakti (@resouer)
[ ] rktlet (@iaguis)

I saw kops filed an issue for this (thanks @chrislovecnm)
cc @mattymo for kubespray

**Comment by dixudx** [comment]
@luxas Ok. I will do that later.

**Comment by runcom** [comment]
@luxas is this just a matter of bumping the CNI library in the container runtimes? (just want to double check I understood this correctly)

**Comment by yujuhong** [comment]
> Pinging CNI & CRI plugin maintainers

As far as CRI is concerned, CNI is an implementation detail. Is there a need to enforce a newer version of CNI across all CRI-compatible runtimes? Are there any new requirement we need to explicitly define in CRI?

@luxas @freehan

**Comment by luxas** [comment]
@yujuhong The last time we did this upgrade, there were some incompability that made things start failing on the wrong CNI / CRI skew. Not sure if that's gonna happen again / if that's the case this time, but pinging for visibility. I think it would be good if we had one version as the officially recommended and validated, and upgraded our projects living in the k8s repo as part of the effort.

**Comment by enisoc** [comment]
@luxas Is your main concern that this may cause our CI jobs to break? Or is it that we will unknowingly break users who set up components with different versions than the exact combination we test?

**Comment by yujuhong** [comment]
> @yujuhong The last time we did this upgrade, there were some incompability that made things start failing on the wrong CNI / CRI skew

CRI made some assumptions that older CNI plugins do no comply. Hopefully this should not be the case anymore.

> Not sure if that's gonna happen again / if that's the case this time, but pinging for visibility. I think it would be good if we had one version as the officially recommended and validated, and upgraded our projects living in the k8s repo as part of the effort.

Thanks for bringing this to everyone's awareness! 

I am not sure if we should have an "officially recommended" CNI version since we delegate networking to the container runtime. The runtimes may use different plugins if they want, theoretically, as long as they validate their integration properly.

That said, if there is any feature that relies on newer CNI specs, and that requirement is not expressed through CRI, we should fix them.

**Comment by dchen1107** [comment]
Bumping CNI to v0.6.0 (#51250) has introduced a huge pod creation latency regression. Please see https://github.com/kubernetes/kubernetes/issues/54651 for details.

**Comment by rpothier** [comment]
xref https://github.com/kubernetes/kubernetes/issues/52179

**Comment by dims** [comment]
@luxas what do we need to do for this issue in 1.9? (or do we move this to 1.10)?

**Comment by luxas** [comment]
@dims I think most things are done here, but need to verify once more with some people.

**Comment by danehans** [comment]
IPv6 alpha support in 1.9 is dependent on CNI getting bumped to 0.6.0.

**Comment by caseydavenport** [comment]
I think this is done. Unless someone shouts otherwise, I'll close this later today.

**Comment by enisoc** [comment]
We still haven't ensured that people using debs/rpms will get CNI 0.6.0:

https://github.com/kubernetes/release/pull/446

**Comment by luxas** [comment]
Yes @enisoc we'll handle that as we get closer to the release date and actually can publish the new packages

**Comment by resouer** [comment]
I think the bot is asking for status update (and so do I).  😆 

Can CRI runtimes begin to upgrade to CNI 0.6 now?

**Comment by danehans** [comment]
CRI-O has been updated to CNI 0.6.0: https://github.com/cri-o/ocicni/pull/1
Containerd already [supports](https://github.com/kubernetes-incubator/cri-containerd/blob/master/hack/versions#L2) CNI 0.6.0

**Comment by luxas** [comment]
> Can CRI runtimes begin to upgrade to CNI 0.6 now?

@resouer yes you should :)

**Comment by caseydavenport** [comment]
@enisoc @luxas how does the rpm/deb packaging fall into the release timeline? Is there an ETA for those, or is it just "when the release happens"?

AFAIK that's the last thing blocking this issue from being closed.

**Comment by luxas** [comment]
@caseydavenport it's enqueued to be done right before the release yes

**Comment by enisoc** [comment]
The rpm/deb packaging happens after we build and push the final release artifacts to GCS. To clarify, I didn't intend to hold this issue open until the packaging occurs, but I would like to hold this open until we know how it's going to work.

In particular, we need a plan to make sure k8s 1.9 uses CNI 0.6.0, while keeping k8s 1.8 and below on CNI 0.5.x.

**Comment by caseydavenport** [comment]
> but I would like to hold this open until we know how it's going to work.

@enisoc Sounds fine to me - who is making that decision?

**Comment by chrislovecnm** [comment]
@caseydavenport which decision?

**Comment by caseydavenport** [comment]
> In particular, we need a plan to make sure k8s 1.9 uses CNI 0.6.0, while keeping k8s 1.8 and below on CNI 0.5.x.

@chrislovecnm this one ^

**Comment by danehans** [comment]
@luxas @caseydavenport now that a 1.9 branch has been cut, can CNI get bumped?

**Comment by dixudx** [comment]
> now that a 1.9 branch has been cut, can CNI get bumped?

@danehans Already bumped in #51250 (merged). Only get kubernetes/release#446 left, should be shipped ASAP, since v1.9 is coming out.

**Comment by danehans** [comment]
@dixudx I have added IPv6 support details to the 1.9 release notes.

**Comment by danehans** [comment]
@dixudx what needs to be done to close this issue? The 1.9 burndown https://github.com/kubernetes/sig-release/issues/38#issuecomment-351132900 is highlighting this issue:

> CNI 0.6.0: (kubernetes/kubernetes#49480): issue still lacks
an "owner" who is going to make sure that the deploy & packaging changes happen. There have been
some updates on this, but a critical outstanding issue is making sure that people can still install version 1.8 with the correct CNI.

**Comment by dixudx** [comment]
> what needs to be done to close this issue?

@danehans Can be closed when kubernetes/release#486 get merged. PTAL.

**Comment by resouer** [comment]
I think all CRI runtimes has been upgraded, ref: https://github.com/kubernetes/frakti/pull/270

**Comment by danehans** [comment]
@dixudx https://github.com/kubernetes/release/pull/486 has ben merged. Can we close this issue?

**Comment by caseydavenport** [comment]
I think so - @enisoc do you agree?

**Comment by luxas** [comment]
Can we close this now with https://github.com/kubernetes/release/pull/486 merged? I think so

**Comment by enisoc** [comment]
@pipejakob is still working on back-filling packages for old k8s versions to prevent them from picking up kubernetes-cni 0.6.0. I think we can close this once that's done.

**Comment by enisoc** [comment]
@pipejakob reported last night that the back-fill is done and staged in `unstable`. He's tested the updated packages, so we just need to re-tag that package set as `stable` this morning before pushing v1.9.0 in the afternoon.

**Comment by pipejakob** [comment]
Thanks for remembering to update here, @enisoc. All of the backfill builds are now promoted to stable (with easy rollback instructions in case anything goes wrong). Should be good to go today with the 1.9 debs/rpms after the release is cut.

**Comment by luxas** [comment]
Thanks @pipejakob for helping with thiis!
