### ISSUE TITLE
API Export Parameter Ignored for List

### ISSUE THREAD

**Issue by dgoodwin** [kubernetes/kubernetes#49497]
/kind bug

**What happened**:

When running kubectl get secrets --export -o yaml, no metadata is stripped and no export logic is applied. The same is true for all API types.

**What you expected to happen**:

Behavior should match getting individual secrets, (kubectl get secret foo --export -o yaml) and export logic should be applied even when listing resources.

**How to reproduce it (as minimally and precisely as possible)**:

Using a hack/local-up-cluster.sh cluster:

```
echo -n "admin" > ./username.txt
echo -n "1f2d1e2e67df" > ./password.txt
kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt
kubectl get secrets -o yaml
```

You will see various fields in the output such as creationTimestamp, namespace, UID, all of which should be filtered out when exporting an object. (which they are when doing an individual GET)

**Anything else we need to know?**:

Via @deads2k the export option may have been missed on ListOptions, or we should be passing ExportOptions everywhere we're passing ListOptions.

Working on a PR to fix this issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.709+6fdf0e4157c76e-dirty", GitCommit:"6fdf0e4157c76eeaf7619e8411ee7231305f7d87", GitTreeState:"dirty", BuildDate:"2017-07-24T13:51:15Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.709+6fdf0e4157c76e-dirty", GitCommit:"6fdf0e4157c76eeaf7619e8411ee7231305f7d87", GitTreeState:"dirty", BuildDate:"2017-07-24T13:51:15Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration**: N/A
- OS (e.g. from /etc/os-release):  Fedora 26
- Kernel (e.g. `uname -a`): Linux wrx 4.11.9-300.fc26.x86_64 #1 SMP Wed Jul 5 16:21:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by deads2k** [comment]
@dgoodwin sounds like you're looking at this.

**Comment by dgoodwin** [comment]
Yeah mentioned in issue but I am trying to get a fix together.

**Comment by dgoodwin** [comment]
I have added Export to ListOptions and a unit test at the apiserver level is passing.

Now for ensuring it's respected. The Export interface today is one method:

```
Export(ctx genericapirequest.Context, name string, opts metav1.ExportOptions) (runtime.Object, error)
```

We're operating here on an object name, so logically the implementation has to do a Get first, then apply Export logic. (these two are tied together)

This isn't great when it comes to Listing because we already have the objects, we don't want to do another Get on each, so it's not easy to re-use the logic within Export.

Propose we make Exporter.Export operate on a pre-existing runtime.Object. It is then no longer responsible for lookup, it just has to strip information, and thus can be reused on the result of a Get or List. (this should also improve testability)

Choosing whether or not to apply it moves one layer above:

https://github.com/dgoodwin/kubernetes/blob/d879780af2fcc2317f5bb09544a510c028177af2/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L150-L150
- will no longer fork to getter.Get or exporter.Export, instead just getter.Get and then optionally apply exporter.Export.

https://github.com/dgoodwin/kubernetes/blob/d879780af2fcc2317f5bb09544a510c028177af2/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L276-L276
- if ListOptions.Export is true will similarly call exporter.Export on each entry in the result we return.

@deads2k does this seem safe and worth doing to you?

**Comment by deads2k** [comment]
It seems like a good idea (recall that you're going to have to filter watches too), but this is of general interest to @kubernetes/sig-api-machinery-misc .

**Comment by caesarxuchao** [comment]
cc @cheftako

**Comment by lavalamp** [comment]
I am not sure if adding an export boolean to list options is great-- it might not play well with the content type negotiation (alternative get formats) @smarterclayton is working on.

In regards to the permissions-- LIST is very powerful, don't give it to people and expect them not to be able to see every secret.

**Comment by smarterclayton** [comment]
We should at minimum talk about export parameter plus list before we add
the flag.  Export has some gaps today

**Comment by dgoodwin** [comment]
@lavalamp @smarterclayton in the current state of the PR I actually reverted the addition of export to ListOptions. The handler layer was already parsing ExportOptions and deciding if it should do a store.Get or an exporter.Export (which implied a store.Get). I split that up, handler now does store.Get or store.List, then if appropriate calls Export on the objects we got back.

**Comment by deads2k** [comment]
> I am not sure if adding an export boolean to list options is great-- it might not play well with the content type negotiation (alternative get formats) @smarterclayton is working on.

So are you proposing we use the content type negotiation instead of the existing query parameter?



> We should at minimum talk about export parameter plus list before we add
> the flag.  Export has some gaps today

The export parameter already exists.  I could see switching it to an enumerated type and having "true" map to something.  It seems very reasonable to extend it from get to list since "export my deployments" is a natural step from "export my deployment named foo".  Probably more likely even.

**Comment by deads2k** [comment]
I spoke with @lavalamp on Friday.  Since the existing feature was broken for some time, we get a free-er hand for changes.  We'll try to see if we can use the content-type negotiation from @smarterclayton first.  If we can't, then we can use parameter options, but they can't be a bool, it will need to be an enumerated string.

**Comment by sttts** [comment]
> We'll try to see if we can use the content-type negotiation from @smarterclayton first

To see whether we are on the same page: 

Content-type negotiation means to introduce something like `Accept: application/json;export=true` or `Accept: application/json;format=export`. A client then can request just the export version passing `Accept: application/json;export=true` or `Accept: application/json;export=true, application/json` if it has a fallback for endpoints without the export implementation.

**Comment by smarterclayton** [comment]
Export is already represented in the content type negotiation options in
`MediaTypeOptions`.  Right now that is done late - but fortunately, the
structure for the handling is already there in transformResponseObject in
response.go.  Export is a post transformation, so it belongs with that
method (some generalization of this method will be useful in the future,
but for now is kept deliberately simple and stupid)

**Comment by dgoodwin** [comment]
Extremely helpful pointers thanks, I can start looking into this in ~2 weeks after vacation if it's still up for grabs.

Do we want to try to move away from just a boolean export=true and towards a configurable strategy or strategies as David suggested above? (optionally for a different cluster, different namespace, etc)

**Comment by dgoodwin** [comment]
I have something in progress for this. A couple questions:

- Where do we want to go with regards to the old export query param? Right now I'm leaving it and just making sure they're both processed in the same place wherever possible.

- Do we want "exact" export option supported in the content type params? It doesn't feel like it's particularly ready for prime time, I would propose we omit it for now and work on a more configurable strategy over time that might encompass it. (keep respecting it if provided as a query parameter for now however)

- Do we want to keep export=1, or go to export=strategy so we can support different paths for export logic.

- Watch requests do not go through transformRequestObject. Do we want to support export with watch requests at all? Right now I'm aiming to keep it working, it just means a little duplicated logic to call exporters.



WIP can be viewed in: https://github.com/kubernetes/kubernetes/pull/49715

**Comment by smarterclayton** [comment]
Old parameter takes priority.  I don't think exact is ready, and it's
always good to err on the side of "don't expose it yet".

I think export=strategy requires more work, so we need a proposal.

Watch should be going through transform, but it looks like it hasn't been
implemented yet.  It would be better to invoke transform on watch.

**Comment by liggitt** [comment]
/close

this issue is noted in the original "implement export" issue in https://github.com/kubernetes/kubernetes/issues/24855#issuecomment-329889844 which is still open... this very much seems like a partially designed feature that we need to finish designing before changing behavior further
