### ISSUE TITLE
Ensure all e2e gcloud calls use a helper methods and follow the test_context

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#49508]
@kubernetes/sig-testing-feature-requests 

The e2e tests define things like `--gcp-project` https://github.com/kubernetes/kubernetes/blob/ce6d92546c9f5203bb1c7808c57d0b344b63593d/test/e2e/framework/test_context.go#L206

It is not always the case that tests follow the test_context configuration, an example from storage that does not use --project or --zone flags:
https://github.com/kubernetes/kubernetes/blob/ce6d92546c9f5203bb1c7808c57d0b344b63593d/test/e2e/storage/pd.go#L452

This gives our e2e tests implicit dependencies on global state (ZONE env vars and/or gcloud config commands), which makes our tests brittle and hard to repro.

We should a) create helper methods for gcloud commands that pass all the right test_context flags to gcloud b) identify and migrate all gcloud commands to these methods and c) write a unit test that validate that gcloud is never used directly.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/area test
/sig gcp
ref: #13535

**Comment by spiffxp** [comment]
/close
In favor of #13535 which I've frozen
