### ISSUE TITLE
VolumeStatus in PodStatus

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#4950]
We need a way to report volume status in podStatus.  The motivating case is to show what the uid and resourceVersion is for a Secret volume (see #4949).

Other uses might include:
- show version at which a git volume was pulled.
- show disk space usage of a volume (though we have talked about not putting usage in podStatus)
- show state of volume as installing/ready/deleting, for debugging slow startup, etc.

We need to pick a place in PodStatus for this per-volume data.

**Comment by erictune** [comment]
@bgrant0607 @thockin @markturansky

**Comment by erictune** [comment]
Config Data volumes would need this too, since they will be much like Secrets.

**Comment by pmorie** [comment]
@erictune I think we're probably on the same page about this but making it explicit:

If you specify a name and namespace for a secret in your pod spec, the status should show the bound resourceVersion and uid; the spec should never have these fields populated except by the user.

**Comment by erictune** [comment]
@pmorie I think that too.  waiting to see what other folks say.

**Comment by markturansky** [comment]
> ...specify a name and namespace for a secret in your pod spec

You can get by with just a name.  I used a defaulting func to add the current namespace of the pod to the object reference. 

See https://github.com/GoogleCloudPlatform/kubernetes/issues/4949#issuecomment-76883407

**Comment by thockin** [comment]
Where will kubelet stash all this info?  It's not carried in the
in-filesystem state, so you'll have to hold on to it somewhere..

**Comment by bgrant0607** [comment]
See #489. (Yes 3 digits.)

**Comment by bgrant0607** [comment]
Half-baked idea: embed identifying information in the file name.

**Comment by thockin** [comment]
It's possible to start checkpointing (in fact some volume plugins already
do it a bit) but I'd rather not do it entirely ad hoc...

**Comment by pmorie** [comment]
@bgrant0607 i had thought about a metadata file in the volume

**Comment by erictune** [comment]
You can work around this by treating volumes as immutable and giving them unique names every time.  Lowering priority.
