### ISSUE TITLE
kubernetes 1.7.2 RPM for CentOS are missing at the repository

### ISSUE THREAD

**Issue by andrey01** [kubernetes/kubernetes#49500]
Dear Kubernetes devs,

it looks like kubernetes 1.7.2 RPM for CentOS are missing at the repository https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata

any ETA for them to be there?

Thank you,

Kind Regards,
Andrey Arapov

**Comment by VFT** [comment]
Same as ubuntu16.04

**Comment by andrey01** [comment]
@luxas @liggitt any insights on ^^ ?  Thanks.

**Comment by githubvick** [comment]
I'm also looking to upgrade my cluster in Centos from 1.5.2 which is the current one available to 1.7, but stuck.

Current repo used 

```
vi /etc/yum.repos.d/
CentOS-Base.repo       CentOS-Debuginfo.repo  CentOS-Media.repo      CentOS-Vault.repo      epel-testing.repo
CentOS-CR.repo         CentOS-fasttrack.repo  CentOS-Sources.repo    epel.repo
[root@kubemaster ~]# vi /etc/yum.repos.d/epel^C
[root@kubemaster ~]# ^C
[root@kubemaster ~]# yil list | grep kube
-bash: yil: command not found
[root@kubemaster ~]# yum list | grep kube
kubernetes-client.x86_64                  1.5.2-0.6.gitd33fd89.el7     @extras
kubernetes-master.x86_64                  1.5.2-0.6.gitd33fd89.el7     @extras
cockpit-kubernetes.x86_64                 141-3.el7.centos             extras
kubernetes.x86_64                         1.5.2-0.7.git269f928.el7     extras
kubernetes-client.x86_64                  1.5.2-0.7.git269f928.el7     extras
kubernetes-master.x86_64                  1.5.2-0.7.git269f928.el7     extras
kubernetes-node.x86_64                    1.5.2-0.7.git269f928.el7     extras
kubernetes-unit-test.x86_64               1.5.2-0.7.git269f928.el7     extras
```
I want to upgrade. Thanks,

**Comment by luxas** [comment]
There are v1.7.2 RPMs now: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml
Sorry for the delay, but the process is unfortunately manual and has to be performed by Googlers in the meantime https://github.com/kubernetes/sig-release/issues/10

**Comment by githubvick** [comment]
@luxas one more question, I would like to upgrade on Cent OS 7 from 1.5 to 1.7. My machine had the repo installed from baseurl=http://mirror.centos.org/centos/7/extras/$basearch/ and it lists only the above. when I tried with the above url, I only get kubeadm, kubectl not master, client and node.

```
 yum list | grep kube
kubeadm.x86_64                         1.7.2-0                     kubernetes
kubectl.x86_64                         1.7.2-0                     kubernetes
kubelet.x86_64                         1.7.2-0                     kubernetes
kubernetes-cni.x86_64                  0.5.1-0                     kubernetes
rkt.x86_64                             1.27.0-1                    kubernetes


```
 Could you please let me know how to upgrade? Thx

**Comment by azalio** [comment]
I build rpm for myself: https://gitlab.com/azalio/kubernetes-binary
