### ISSUE TITLE
Kubelet should enable hierarchical memory on host

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#4951]
Today hierarchical memcg may not be enabled on the host we run. As we move towards "cgroup under" we need to enable hierarchical memcg to get proper accounting and behavior.

**Comment by vmarmol** [comment]
Adding some more information about this bug.

To enable hierarchical memory accounting/limiting we have to write "1" to "memory.use_hierarchy" in that cgroup. However, this can't be done for containers that already have subcontainers. We should try to ensure this is on for the distros we run on (e.g.: container-vm).

If a distro does not do this hierarchical accounting will be broken so that use at root != use at the machine. We can hack around this for the pod usecase, but the breakage at the host level may be a deal-breaker for us once we rely on the machine-wide usage for scheduling.

We are probably okay for v1, but may start hurting after that.

Assigning to myself and I'll continue examining.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/76

**Comment by jdef** [comment]
There needs to be a way to stop the kubelet from making changes at the host level. In certain deployments, kubernetes will be sharing the host machine with other services and should not assume ownership of the entire node (or the settings at the root level of that node). While I can appreciate the need for configuring this setting at the host level, I'm not sure that the kubelet is right place do it.
