### ISSUE TITLE
Where is your kube swag.... Dress Socks

### ISSUE THREAD

**Issue by tmedford** [kubernetes/kubernetes#49518]
/kind feature

The path to successful open source software is not only filled with impressive features, late coding and drinking nights, but most importantly SWAG. I have my glorious Deis socks, 
![image](https://user-images.githubusercontent.com/4482381/28546112-8908b356-7097-11e7-8104-957eb3ad6b10.png),  but no kube socks to match. Help me! 
```
kubectl get socks
```

**Comment by Cryptophobia** [comment]
This issue is related to https://github.com/Codaisseur/alea/issues/17 and https://github.com/deis/workflow/issues/831

**Comment by xiangpengzhao** [comment]
AFAIK, `kubectl get socks` will respond an error `the server doesn't have a resource type "socks"`. Try `kubectl get t-shirts`. Wish you luck!

@kubernetes/sig-contributor-experience-feature-requests ha!

**Comment by cblecker** [comment]
@sarahnovotny might be able to comment on this heh

**Comment by sarahnovotny** [comment]
all things k8s swag are available at http://store.cncf.io . sadly, there are only athletic socks.

**Comment by Cryptophobia** [comment]
Never had "no show" swag before.

Athletic no-show socks for kubernetes geeks?!?!... Is there a hint in there somewhere?

Is this the look we are going for?

![image](https://user-images.githubusercontent.com/15237494/28801034-a7a17740-761d-11e7-8d0e-e58605e60137.png)

**Comment by sarahnovotny** [comment]
think of your fashion opportunities going through the TSA lines.

**Comment by Cryptophobia** [comment]
Oh, the opportunities in fashion are endless for software engineers these days... 

When is Google going to open source Giorgio Armani then? Or should I say "Googlio Armani"?

**Comment by sarahnovotny** [comment]
give us some time.... and these will be an option.

![kubernetesbusiness_biz_10 1 1](https://user-images.githubusercontent.com/127370/29047271-dc139758-7b7f-11e7-9a91-e92bef612fa7.jpg)

**Comment by kingdonb** [comment]
I see the socks in the store now, as well as decals, concert T-shirts, and hoodies!  Thanks for taking this one on, it was a blocker for us.

**Comment by cblecker** [comment]
Glad to see this one resolved!
/close
