### ISSUE TITLE
Make it easier to understand versioning of repositories pushed from staging

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#49536]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
In attempts to rebase kubernetes incubator projects (i.e. service catalog and cluster-capacity), it was unclear what commits from the various repositories would all work well together.  These repositories include the following:

- kubernetes/kubernetes
- kubernetes/apimachinery
- kubernetes/apiserver
- kubernetes/client-go

After further investigation, the behavior for kubernetes/client-go was clear in that we bump the semantic version with each minor kubernetes version at this time.  The behavior for the other repositories was less clear.  Evidence shows that these repositories attempt to choose a commit around the time that kubernetes shipped, and its a bit of a guessing game to try and find a commit around the time kubernetes releases were cut.

See comments here for an example:
https://github.com/kubernetes-incubator/service-catalog/blob/master/glide.yaml

Ideally, for the kubernetes/apimachinery and kubernetes/apiserver repositories we could have a release branch that tracks kubernetes/kubernetes until such time those libraries stabilize and are themselves vendored back into kubernetes/kubernetes rather than vendored out.  I think that would make repositories that vendor them in have a less confusing experience.

In addition, it is not clear to the reporter of this issue how a project that depends on those repositories can pick up security changes or fixes that may be found at a later time.  For example, if a fix (security or otherwise) goes into kubernetes/kubernetes release-1.7 via a cherry-pick for a file in the staging directories, how can a dependent project know that they can get those fixes in the current model?  Ideally, any fixes made in a cherry-pick to past releases would also get pushed out the kubernetes/apimachinery release-1.7 branch, and dependent repositories could just pull an updated commit from that branch.

**What you expected to happen**:
It should be less confusing on what things work well together.  There should be a mechanism for getting cherry-picks made in kubernetes/kubernetes staging areas to be easily pulled by dependent projects until such time kubernetes/kubernetes vendors those libraries directly.  I recognize that these projects are on the cutting edge, but it seems like we could make small improvements to help those consumers.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:
nope

**Environment**:
n/a

**Comment by derekwaynecarr** [comment]
cc @kubernetes/sig-api-machinery-feature-requests 

@eparis @jaboyd01 @aveshagarwal @pmorie @jpeeler @sttts -- this is based on our discussion today.  let me know if i did not clearly capture the issues we have encountered.

**Comment by derekwaynecarr** [comment]
It looks like we have a release-1.7 branch for apimachinery
see: https://github.com/kubernetes/apimachinery/tree/release-1.7

We do not have a release-1.7 branch for apiserver (but it does have a release-1.6 branch).

**Comment by liggitt** [comment]
@sttts @caesarxuchao as fixed are made to release branches, we need to ensure those are propagated. is there a plan to get branches for the child repos that track maintenance branches in the main repo?

**Comment by sttts** [comment]
@liggitt we always have tracked release branches in the published repos. Though we forgot to keep the branch list up to date for some repos. release-1.8 will come with the next manual push (before we enable the nightly run again).

**Comment by munnerz** [comment]
Will github.com/kubernetes/code-generator also be tagged as part of this? That'd make it a lot easier to generate client libs etc. that are compatible with released versions of client-go/apimachinery/apiserver. & will there be a release-1.7 of code-generator if so? It'd be great to stop depending on master! 😄

**Comment by sttts** [comment]
@munnerz k8s.io/code-generator is a staging repo like the others, i.e. it will be tagged as well.

There won't be a code-generator repo for 1.7.

**Comment by sttts** [comment]
With https://github.com/kubernetes/client-go#kubernetes-tags and the bot running again, I will close this issue. Reopen if you think otherwise.
