### ISSUE TITLE
Use the core client with version

### ISSUE THREAD

**Issue by supereagle** [kubernetes/kubernetes#49535]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
When rebase #48976 to fix the conflict with #48847, find that some codes use `clientSet.CoreV1()`, while some codes still use the **Deprecated** `clientSet.Core()`.

**What you expected to happen**:
Replace the **Deprecated** `clientSet.Core()` with `clientSet.CoreV1()`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by kevin-wangzefeng** [comment]
Found that there are still a lot of places currently using `clientSet.Core()`. Reopening this issue.
