### ISSUE TITLE
Pod suffix is b0110ck5

### ISSUE THREAD

**Issue by jamesawebb1** [kubernetes/kubernetes#49543]
/kind feature

**What happened**:

In playing with the nginx ingress controller deployment, I noticed the following pod name:
nginx-ingress-controller-1449474453-c0ck5
I figure we should possibly put something in place to prevent accidental l33t profanity ;-).

**What you expected to happen**:

The following pod name:
nginx-ingress-controller-1449474453-r0ck5

**Comment by jamesawebb1** [comment]
My first github (k8s) issue.  I've no idea which SIG would cover this topic.

/sig product-management

**Comment by mml** [comment]
Previously we removed vowels in #37225.  We can 3xt3nd the idea with 0, 1 (can stand for `I`) and 3.  @jamesawebb1 would you like to send a PR?  If not, I can work on this.

**Comment by mml** [comment]
@jamesawebb1 Reassign to me if you do not want to contribute a PR.
