### ISSUE TITLE
Working config for GKE ingress with SSL termination. 

### ISSUE THREAD

**Issue by Blasterdick** [kubernetes/kubernetes#49546]
How can I create a load balancer with SSL termination within GKE (examples from [here](https://github.com/kubernetes/ingress/blob/master/controllers/gce/README.md#tls) seem doesn't work)? 

When I created a load balancer from the [ingress](https://pastebin.com/MBQpaeYQ) with `NodePort` [service](https://pastebin.com/gpn2L68C), the backend group for ingress load balancer uses all the nodes in the cluster for a `GCE instance group` and marks them as unhealthy. 

As a result, all the requests to a load balancers IP address are getting `502` code with the following error message:

```
Error: Server Error

The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

Thanks in advance for any kind of help.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at present

/sig network
because ingress

**Comment by mikesparr** [comment]
I had the "unhealthy" warnings and kept trying different configs, only to learn that this appears for 10-20 minutes after a deployment, and then resolves to `OK`.

 * https://www.linkedin.com/pulse/automating-tls-name-based-hosting-kubernetes-google-cloud-mike-sparr/

I shared findings in blog post. I used `kube-lego` for SSL provisioning and settled on `gce` class but I'm sure `nginx` would work same.

**Comment by mikesparr** [comment]
I too see these errors however, and not related to SSL (I think). I'm tracing code in a container running Apache/PHP5.6 and trying to make `nusoap` calls to a 3rd-party web service. When it hits that code, the app crashes and I see this:

![screenshot_2017-10-19_21_04_05](https://user-images.githubusercontent.com/5553105/31803489-4621eb48-b511-11e7-94e0-6b6b054cbcc0.png)

Unfortunately even after adding error logging and move to stdout in `php.ini` I don't receive or see any PHP errors in kubectl logs -f {pod} -c {container} just the Apache HTTP logs.

**Comment by puppychen** [comment]
Same kind here. Ingress with NodePort.
Try to run nginx and Php5.6. Nginx is worked but Apache/php5.6 got the same error message.

**Comment by dfang** [comment]
same here. Ingress with service Type NodePort

**Comment by dennypenta** [comment]
It probably happened because of healthchekers had was directed to wrong endpoint.
You have to check it and change if a backend service have error.

**Comment by abraithwaite** [comment]
/remove-lifecycle stale

I still care about this.

**Comment by abraithwaite** [comment]
/remove-lifecycle stale

GCP just introduced managed certificates which should make this easier.

https://cloud.google.com/load-balancing/docs/ssl-certificates#managed-certs

**Comment by freehan** [comment]
reopen if needed
