### ISSUE TITLE
k8s.io/kubernetes/pkg/registry/core/service TestInitNodePorts flake

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#49548]
```
rest_test.go:1551: "Service has two same ports with different protocols and specifies same NodePorts": unexpected error: Service "foo" is invalid: spec.ports[0].nodePort: Invalid value: 30054: provided port is already allocated
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49286/pull-kubernetes-unit/42616/

@kubernetes/sig-network-test-failures

**Comment by xiangpengzhao** [comment]
/assign

This was introduced in #48418. I will rebase #49361 and fix it in that PR.

**Comment by xiangpengzhao** [comment]
Added in #49361. Thanks @kargakis for reporting this!

**Comment by liggitt** [comment]
seen again in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49574/pull-kubernetes-unit/45907/

**Comment by xiangpengzhao** [comment]
@liggitt This is because #49361 is not merged yet. I will address your comments. Thanks!
