### ISSUE TITLE
Containers reconfiguration in real-time

### ISSUE THREAD

**Issue by maxkondr** [kubernetes/kubernetes#49545]
Hello,

I have faced with following case and haven't found clear answer for me.

Preconditions:
- I have kubernetes cluster
- there are some options related to my application (for example debug_level=Error)
- there are pods running and each of them uses configuration (ENV, mount path or cli args)
- later I need to change value of some option (the same 'debug_level' Error -> Debug)
The Q is:
how should I notify my Pods that configuration has changed? 
Earlier we could just send HUP signal to the exact process directly or call `systemctl reload app.service`

What are the best practices for this use-case?

Thanks.

**Comment by abdasgupta** [comment]
Hi @maxkondr 
You can modify the Pod using https://kubernetes.io/docs/api-reference/v1.6/#-strong-write-operations-strong--54
Does it help?

**Comment by maxkondr** [comment]
@abdasgupta 

Hm, could you please point me to some real examples? For the time being I do not see how it could help me

**Comment by maxkondr** [comment]
in fact (I mean by functionality) my Q is very similar to case when service updates the list of endpoints (pods) when the list of them is changed. How is it achieved?
