### ISSUE TITLE
Failed to register node

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#49544]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If instance comes from the zone which has Chinese name，it can not be used as a kubernetes node.
\-----------
\# nova show ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka | grep availability_zone
| OS-EXT-AZ:availability_zone                                           | 中文                                                          |
\-----------
Kubelet's log as following:
\-----------
Jul 20 07:35:56 ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka.novalocal kubelet[10092]: I0720 07:35:56.762145 10092 kubelet_node_status.go:283] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=中文 
Jul 20 07:35:56 ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka.novalocal kubelet[10092]: I0720 07:35:56.762202 10092 kubelet_node_status.go:287] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=RegionOne
Jul 20 07:35:57 ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka.novalocal kubelet[10092]: I0720 07:35:57.527723 10092 kubelet_node_status.go:77] Attempting to register node ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka
Jul 20 07:35:57 ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka.novalocal kubelet[10092]: E0720 07:35:57.530644 10092 kubelet_node_status.go:101]  Unable to register node "ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka" with API server: Node "ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka" is invalid: metadata.labels: Invalid value: "中文": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') 
Jul 20 07:35:58 ne-cdlqmo7wgw-0-7yzmth4qkivz-kube-minion-btgwnwp3utka.novalocal
\-----------
**What you expected to happen**:
Kubernetes node also can comes from Chinese name zone.

**How to reproduce it (as minimally and precisely as possible)**:
Create a instance in Chinese-name-zone, then start kubelet and register to kube-apiserver.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):   v1.6.4
- Cloud provider or hardware configuration**:   OpenStack cloud provider
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@FengyunPan Because chinese character is not valid label name, which must match `([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]`.

**Comment by FengyunPan** [comment]
@dixudx Can we support chinese character?
What you expected to happen:
Kubernetes node also can comes from Chinese name zone.

**Comment by dixudx** [comment]
@FengyunPan These names are qualified names. I don't think we can use Chinese character as qualified names.

**Comment by dims** [comment]
@FengyunPan - Can you try removing openstack from the equation? Like @dixudx says, you will most probably see the problem even without OpenStack

**Comment by dims** [comment]
On the OpenStack side, this should be working since kilo already. https://specs.openstack.org/openstack/nova-specs/specs/kilo/implemented/relax-resource-name-restrictions.html

**Comment by FengyunPan** [comment]
@dims I know the reason of this issuse(kubernetes can't support Chinese character), but I can't fix it and I don't know if the *resource name\label\other name* of kubernetes can be expanded to all printable unicode characters and horizontal spaces like openstack. I want to get others' opinions about this issue.

**Comment by FengyunPan** [comment]
Currently if the region name\zone name\instance name\volume name of OpenStack contains Chinese character(or other invalid  character), kubernetes can't use them. Do you have any ideas to fix it? @dims

**Comment by dims** [comment]
@FengyunPan Nice test using "中文" which seems to mean chinese :) This is probably a question for SIG API Machinery (and of course SIG Node). I don't think there is an easy answer other than try to fix scenarios one by one (starting with that regexp) and seeing how difficult it is going to be. Also we might want to check if things work with Docker first (how kubernetes uses docker API for names labels etc).

/sig api-machinery

**Comment by MatMaul** [comment]
I hit a similar problem a while ago because the availability zone of a VM was "-". It would be very nice to extend the possible values for label values.
https://github.com/kubernetes/kubernetes/issues/44045

**Comment by FengyunPan** [comment]
Yes, I agree.

**Comment by mml** [comment]
/sig node I think this is a kubelet issue.  Is it doing something sensible when the hostname does not match the label regex.
/sig architecture Should consider whether or not this list is correct.

**Comment by dims** [comment]
@kubernetes/sig-architecture-bugs

**Comment by dims** [comment]
@kubernetes/sig-node-bugs

**Comment by ning0011** [comment]
(name must consist of lower case alphanumeric characters, '-' or '.' (regex: [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*))
