### ISSUE TITLE
Requests and limits of memory, CPU unit conversion has bugs to Requests and limits of memory, CPU unit conversion has bugs

### ISSUE THREAD

**Issue by zzy0707zzy** [kubernetes/kubernetes#49559]
When
requests:
        memory: 0.001Mi
        cpu: 1
      limits:
        memory: 0.001Mi
        cpu: 1
kubectl describe pod_id
Results :   memory=1048576m

**Comment by zzy0707zzy** [comment]
200 m memory is equal to how many Mi?

**Comment by xiangpengzhao** [comment]
IIUC, for memory, the unit `m` means milli-bytes, i.e. `1/1000 byte` (Though it may be meaningless...)

So for your example: 
```
0.001Mi == (1/1000)Mi == 1024*1024*(1/1000)bytes = 1024*1024 milli-bytes == 1048576m
```

/cc @smarterclayton @vishh I remember there was a discussion about if allowing `m` unit for memory?

**Comment by xiangpengzhao** [comment]
A recent issue: #49442

**Comment by supereagle** [comment]
I have verified that `m` is allowed for memory unit, which is milli-bytes as @xiangpengzhao said.

According the definition of  [Quantity](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L61-L70):
```
// When a Quantity is parsed from a string, it will remember the type of suffix
// it had, and will use the same type again when it is serialized.
//
// Before serializing, Quantity will be put in "canonical form".
// This means that Exponent/suffix will be adjusted up or down (with a
// corresponding increase or decrease in Mantissa) such that:
//   a. No precision is lost
//   b. No fractional digits will be emitted
//   c. The exponent (or suffix) is as large as possible.
// The sign will be omitted unless the number is negative.
```
To ensure that on precision is lost when serialized, the `0.001Mi` is adjusted down to `m` unit.
This works as expected, maybe it is not a bug.

**Comment by vishh** [comment]
https://github.com/kubernetes/kubernetes/issues/49442#issuecomment-320847044

**Comment by zhangxiaoyu-zidif** [comment]
1 milli-bytes equals 1/1000 byte
but it is not really exist. The mininum of memory or disk should be bit. All right?
mili-bytes seems to be non-meanning or non-value.
@vishh

**Comment by zhangxiaoyu-zidif** [comment]
And if user use 0.1Gi, this value  can not be converted into a integer value bytes...
