### ISSUE TITLE
keep Pod Running when upgrading kubelet binary within given timeout duration

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/kubernetes#49563]
/kind feature
/sig controller-manager

**What you expected to happen**:

- give a node obj an upgrading annotation pairs

- in function func (nc *NodeController) monitorNodeStatus() error ; 
  add another logic to handle the upgrading senario of kubelet binary to avoid evictPods on the upgrading   node, so the status of the pods are still running within the given nodeUpgradeTimeout,when the timeout reached , add the node to the queue of evictPods(node *v1.Node)  to evict pods of the node.

**Comment by jiaxuanzhou** [comment]
@spiffxp would agree with me about the solution? if so , i will submit one PR to implement the feature, thx.

**Comment by spiffxp** [comment]
@jiaxuanzhou sorry I missed your comment, if you still want to work on this please feel free to `/reopen`.  I don't know enough about this code to say whether your solution is correct or not, I was just categorizing the issue.

**Comment by jiaxuanzhou** [comment]
@spiffxp i will work on it 
/reopen
