### ISSUE TITLE
servicecontroller doesn't record some events

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#49564]
we still have some un-recorded events on the servicecontroller : https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L499 

these events might be warnings that we miss recording, are we still doing these convertions ? @bowei @thockin

**Comment by bowei** [comment]
@yastij send a PR, happy to review

**Comment by yastij** [comment]
@bowei - started working on this, do we want to add recording only on errors ? or everywhere by recording errors and replacing error logging `glog#Errorf` by eventRecording (the eventRecorder will send events to watch or log or other) ? I think the latter.

**Comment by yastij** [comment]
This will be waiting for event v2

/remove-lifecycle stale
