### ISSUE TITLE
How can I get the information about which GPUs are already allocated for each node, using k8s API

### ISSUE THREAD

**Issue by hongshibao** [kubernetes/kubernetes#49561]

**Comment by pineking** [comment]
@hongshibao AFAIK, there are no k8s APIs can do such things.
this information is in the variable `nvidiaGPUManager`
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L60

**Comment by hongshibao** [comment]
Thanks @pineking . I think I know how to expose this information now.

**Comment by RenaudWasTaken** [comment]
You could always `kubectl exec 'nvidia-smi -L'` on the containers requesting a GPU
