### ISSUE TITLE
K8s Service fails to create Azure internal load balancer

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#49577]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

@kubernetes/sig-azure
@kubernetes/sig-network

**What happened**: 

I've created a Kubernetes CLuster on Azure using acs-engine.

In order to be able to communicate within a private network (Azure Vnet) between k8s resources and other Azure resources I have used a custom VNet configuration which allows to specify the Azure VNet resource you want k8s to be deployed into (which was already existing and had already some resources).

When I tried to create an **internal** load balancer service (see following yaml) Kubernetes tells me it fails to get the subnet he wants to use for the Azure internal load balancer resource (it's the same subnet that is used by k8s masters nodes, so it does exist).

```kind: Service
apiVersion: v1
metadata:
  name: prometheus-internal-load-balancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: prometheus
    component: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
```

**What you expected to happen**: Azure **internal** load balancer resource created

**How to reproduce it (as minimally and precisely as possible)**:

```
sylvain@wsrabot:~/helm$ kubectl create -f service-internal-load-balancer.yml --context=k8s3-euw-dev --namespace=monitoring
service "prometheus-internal-load-balancer" created

sylvain@wsrabot:~/helm$ kubectl describe service --context=k8s3-euw-dev --namespace=monitoring prometheus-internal-load-balancer
Name:                   prometheus-internal-load-balancer
Namespace:              monitoring
Labels:                 <none>
Annotations:            service.beta.kubernetes.io/azure-load-balancer-internal=true
Selector:               app=prometheus,component=server
Type:                   LoadBalancer
IP:                     10.0.200.138
Port:                   <unset> 80/TCP
NodePort:               <unset> 32552/TCP
Endpoints:              10.100.242.24:9090
Session Affinity:       None
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                          Message
  ---------     --------        -----   ----                    -------------   --------        ------                          -------
  8m            2m              7       service-controller                      Normal          CreatingLoadBalancer            Creating load balancer
  8m            2m              7       service-controller                      Warning         CreatingLoadBalancerFailed      Error creating load balancer (will retry): Failed to create load balancer for service monitoring/prometheus-internal-load-balancer: ensure(monitoring/prometheus-internal-load-balancer): lb(k8s3-euw-dev-internal) - failed to get subnet: Network-EUW-dev-VNet/k8s3-master-EUW-dev-subnet
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): 16.04.2 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux k8s-master-83339970-0 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sylr** [comment]
All right, I think I found the issue.

K8s fails to find the subnet because in my case the VNet is not in the same resource group as the kubernetes.

I'll try to make a patch to be able to configure the resource group of the VNet.

**Comment by dcieslak19973** [comment]
I still seem to be experiencing this problem using version 1.7.4; was it merged into the 1.7.x branch?

**Comment by sylr** [comment]
@dcieslak19973 It has been, have you added the vnetResourceGroup properties your the azure.json ?

**Comment by dcieslak19973** [comment]
I don't think so. I've provisioned the cluster using acs-engine. Is the azure.json file just on the master node(s)?

**Comment by zerogjoe** [comment]
azure.json definitely exists on both masters and agents, in /etc/kubernetes. Presumably both are used as masters and agents have different subnet configurations. I updated both to be safe.

I've just experienced this issue myself on a fresh deployment to Azure using [acs-engine](https://github.com/Azure/acs-engine). Presumably acs-engine needs to be updated to populate the `vnetResourceGroup` attribute from the `vnetSubnetId` attributes in the apimodel specification JSON.

Specifically they can be found here:

```
{
  "apiVersion": "vlabs",
  "properties": 
    ...
    "masterProfile": {
      ...
      "vnetSubnetId": "/subscriptions/(**REDACTED**)/resourceGroups/(**HERE**)/...",
      ...
    },
    "agentPoolProfiles": [
      {
        ...
        "vnetSubnetId": "/subscriptions/(**REDACTED**)/resourceGroups/(**HERE**)/...",
        ...
      }
    ],
    ...
  }
}
```

Does anyone know if this has been documented as an issue in acs-engine already?

**Comment by markya0616** [comment]
We also encountered the similar issue. @sylr Can you provide an example about how to add `vnetResourceGroup` into `azure.json`?

**Comment by sylr** [comment]
```s.rabot@k8s-agent-yyyyyyyyyy-1:~$ sudo cat /etc/kubernetes/azure.json
{
    "cloud":"AzurePublicCloud",
    "tenantId": "xxxxxxxxxxxxxxxxx",
    "subscriptionId": "xxxxxxxxxxxxxxxxx",
    "aadClientId": "xxxxxxxxxxxxxxxxx",
    "aadClientSecret": "xxxxxxxxxxxxxxxxx",
    "resourceGroup": "xxxxxxxxxxxxxxxxx",
    "location": "westeurope",
    "subnetName": "k8s1-xxxxxxxxxxxx-EUW-test-subnet",
    "securityGroupName": "k8s-xxxxxxxxxxxxxxxxx-yyyyyyyyyy-nsg",
    "vnetName": "VNet",
    "vnetResourceGroup": "common-RG",
    "routeTableName": "k8s-xxxxxxxxxxxxxxxxx-yyyyyyyyyy-routetable",
    "primaryAvailabilitySetName": "agent-availabilitySet-yyyyyyyyyy",
    "cloudProviderBackoff": false,
    "cloudProviderBackoffRetries": 0,
    "cloudProviderBackoffExponent": 0,
    "cloudProviderBackoffDuration": 0,
    "cloudProviderBackoffJitter": 0,
    "cloudProviderRatelimit": false,
    "cloudProviderRateLimitQPS": 0,
    "cloudProviderRateLimitBucket": 0,
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": false
}
```

**Comment by markya0616** [comment]
@sylr Thanks for the reply. Can you provide more details? In our case, we use a json file like below to generate `azuredeploy.json` and `azuredeploy.parameters.json` by `acs-engine`.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": ${master_vm_count},
      "dnsPrefix": "${dns_prefix}",
      "vmSize": "${vm_size}",
      "firstConsecutiveStaticIP": "${first_master_ip}"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": ${worker_vm_count},
        "vmSize": "${vm_size}",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "${admin_user}",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "${ssh_key}"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientID": "${service_principle_client_id}",
      "secret": "${service_principle_client_secret}"
    }
  }
}
```

After that, we can deploy the cluster by `az group deployment create`. Do you have any idea about this?

**Comment by zerogjoe** [comment]
It looks like this was fixed in a PR to acs-engine last week: https://github.com/Azure/acs-engine/pull/1150

There hasn't been a binary release since then, so you'd have to clone the acs-engine repo and build from source to benefit from the fix.

@markya0616 - as a workaround for a cluster that's already been deployed, you need to SSH to each master and worker and edit /etc/kubenetes/azure.json as @sylr suggested. Specifically:

```
    "vnetName": "<YOUR_VNET_NAME>",
    "vnetResourceGroup": "<YOUR_VNET_RESOURCE_GROUP>", # add this line
    "routeTableName": "k8s-xxxxxxxxxxxxxxxxx-yyyyyyyyyy-routetable",
```
