### ISSUE TITLE
PodExecOptions has odd behavior

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#49586]
Based on my testing, in 1.6, if I passed 
 1. stdout empty - `true`
 1. stdout `false` - `true`
 1. stdout `true` - `true`

In 1.7, if I passed
 1. stdout empty - `false`
 1. stdout `false` - `false`
 1. stdout `true` - `true`

The 1.6 defaulting doesn't work because you can't default a `bool` field.  The parameter decoder doesn't handle `*bool` and even if it did, you'd end up facing more conversions to get to a useable internal version.

The 1.7 handle is sane (if I pass false, I get false), but it drops the empty -> true aspect.  The kubernetes-ui library always passes a value and kubectl always passes a value.

I think we should probably stick with the 1.7 behavior and add a note somewhere about it.  If the world explodes in 1.7 (doubtful, I think), we could reassess.

@kubernetes/sig-api-machinery-bugs @lavalamp @smarterclayton @liggitt

**Comment by deads2k** [comment]
@ncdc

**Comment by ncdc** [comment]
@deads2k this is exactly what I was hoping to see (the 1.7 behavior). You may want to test things like `oc rsync`,`oc debug`, and the openshift web console to make sure they're still good.

**Comment by ncdc** [comment]
This affects stderr too, and both fields in PodAttachOptions, doesn't it?

**Comment by deads2k** [comment]
> This affects stderr too, and both fields in PodAttachOptions, doesn't it?

Yes it does.

**Comment by lavalamp** [comment]
The desired behavior for this is
* If the user passes nothing, it defaults to `true`
* if the user passes something, it uses what the user passed.

The current state (as I understand it) is defaulting to `false`. This is a bug! We don't have someone to work on this right now though.

**Comment by shiywang** [comment]
hi @deads2k , I checked the code, seems defaulting is correct here: https://github.com/kubernetes/kubernetes/blob/1faa6f56b9c026b58d17e9163bf0b26a8b4086b4/pkg/api/v1/defaults.go#L43, I'm not sure when those two values turn into `false` when stdout is unset, BTW how do you check those values here ? through etcd ? Thanks
