### ISSUE TITLE
Dynamic client does not support subresources

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#49588]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind feature

**What happened**: Existing dynamic client library does not support subresources.

**What you expected to happen**: The library should support the subresources to facilitate e2e testing.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**: N/A
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig api-machinery
/cc @lavalamp

**Comment by crimsonfaith91** [comment]
@enisoc

**Comment by mml** [comment]
@mbohlool can you take a look?

**Comment by mbohlool** [comment]
@caesarxuchao I guess this is client-go. Can you take care of this? I can also look if you want me to.

**Comment by caesarxuchao** [comment]
@roycaihw feel free to have a try.

**Comment by enisoc** [comment]
Woohoo! Thanks @roycaihw!
