### ISSUE TITLE
Failed to start service controller without cloud provider

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#49612]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After starting kubernetes controller manager, I get the following error:
\-----------------
**E0726** 11:55:39.362927       1 controllermanager.go:494] **Failed to start service controller**: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
\-----------------

**What you expected to happen**:
Get a warning message rather than a Error.

**How to reproduce it (as minimally and precisely as possible)**:
start service controller without cloud provider
    --cloud-config=
    - --cloud-provider=

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.6.4
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FengyunPan** [comment]
\assign

**Comment by xiangpengzhao** [comment]
/sig network

This is not a bug. This is an expected warning when there is no cloud provider.

**Comment by FengyunPan** [comment]
We can support starting controller manager without cloud provider when I don't create the LoadBaancer service. I will create pr to fix it.

**Comment by FengyunPan** [comment]
@xiangpengzhao "Failed to start service controller" means failure. It is better to make a expected warning when there is no cloud provider rather than getting a error.

**Comment by FengyunPan** [comment]
@xiangpengzhao And I think it is easy to fix it.

**Comment by xiangpengzhao** [comment]
Yeah, this is an enhancement rather than a bug:)

**Comment by uiansol** [comment]
Today I got the same error but my case is just a little different: My case is run a service in a on-premises cluster exposing it as load balancer. It's requires a cloud provider that doesn't exist in on-premises.

I found the ServiceController.go where it's managed and it's seen to be a easy solution. But is it require a proposal as it's a enhancement?

@FengyunPan I would like to help in a proposal for this if needed. Also it can help in deploy Ingress resource in on-prem.

**Comment by FengyunPan** [comment]
Yeah, you can file a pr@uiansol

**Comment by jiaozg22** [comment]
I use version 1.18，it happened the same error.   

 `Log file created at: 2020/08/25 15:01:06
Running on machine: k8s-master
Binary: Built with gc go1.13.4 for linux/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0825 15:01:06.293363    4348 core.go:89] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
E0825 15:01:06.533094    4348 core.go:229] failed to start cloud node lifecycle controller: no cloud provider provided
`
I with Binary installation k8s .kube-ctroller-manager started,But  when kubelet get nodes ,the result is No resources found in default namespace.
How to do solve this problem? I doubt this is a bug
-------------------------------------------
KUBE_CONTROLLER_MANAGER_ARGS="--master=https://192.168.0.200:6443 --service-account-private-key-file=/etc/k8s/ssl/server.key --root-ca-file=/etc/k8s/ssl/ca.crt --kubeconfig=/etc/k8s/kubeconfig --cluster-name=kubernetes --logtostderr=false --log-dir=/var/log/k8s --v=2"

-------------------kubeconfig file----------------------------------------
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ssl/ca.crt
    server: https://192.168.0.200:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: controllermanager
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: controllermanager
  user:
    client-certificate: /etc/k8s/ssl/cs_client.crt
    client-key: /etc/k8s/ssl/cs_client.key
~
