### ISSUE TITLE
factor out aws's volumes interface and extend its usage to other CP

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#49625]
I think that we should allow now other CP to implement this [interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L321)  and make volumes mgmt cloud agnostic. To do so, we should also extract the volumeOptions

/area cloudprovider
/sig storage
/kind enhancement

**Comment by yastij** [comment]
also ping @justinsb and @bowei

**Comment by bowei** [comment]
@saad-ali -- this is storage related

**Comment by yastij** [comment]
@saad-ali @justinsb WDYT ?

**Comment by yastij** [comment]
ping @saad-ali

**Comment by yastij** [comment]
Also ping @rootfs

**Comment by rootfs** [comment]
@yastij see https://github.com/kubernetes/features/issues/88

**Comment by yastij** [comment]
@rootfs - from what i read, work on volumes will be the very last one implemented.

I think that the following extraction and refactoring will ease hugely the work when we'll get there, don't you think ?

**Comment by yastij** [comment]
ping @rootfs

**Comment by yastij** [comment]
@rootfs - do we still need to work on this one ?

**Comment by yastij** [comment]
@wlan0 @luxas - do we still have to work on this one ?

**Comment by andrewsykim** [comment]
I think in general there should be a volume interface that cloud providers use, though I would be interested to hear what sig-storage has to say about the interface with respect to CSI.

**Comment by yastij** [comment]
@andrewsykim - I'm usually busy during sig storage meetings to discuss the matter, might be interesting to see what we can do about this one @rootfs @saad-ali

**Comment by yastij** [comment]
@andrewsykim - just came back, I was off the whole month. @jsafrane any thoughts on this one as now CSI is merged.

**Comment by jsafrane** [comment]
Every cloud provider has different features that cannot be easily abstracted by a generic interface. The closest abstraction we have are volume plugins. Anything behind volume plugin interface is heavily cloud dependent.

Current sig-storage plan is to move every volume plugin out of Kubernetes and use CSI for everything. So CSI should be the abstraction interface here.

**Comment by yastij** [comment]
I see. Does any issue exists to track such work ?

**Comment by andyzhangx** [comment]
@jsafrane does `every volume plugin` also include NFS, rbd, etc. not only related to cloud provider, right? So all the common plugins need to be refactored, that's a quite huge project.

**Comment by jsafrane** [comment]
@andyzhangx, yes, it's going to be interesting. Nothing is set to stone yet, it's just an idea. No final decision, no concrete plan, no tracking issue yet. We need to do CSI right first.

**Comment by yastij** [comment]
@jsafrane - let's use this one, to track work, i'll update the title and list plugins that'll need adapters.

cc @wlan0 @jhorwit2  and @ublubu  for the wg-cloud-provider side

**Comment by yastij** [comment]
created #57715 as fresh start to track work.
