### ISSUE TITLE
kubectl --as doesn't work inside pod

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#49622]
**Is this a BUG REPORT or FEATURE REQUEST?**
/kind bug

**What happened**:
kubectl --as=foo doesn't work inside pod

**How to reproduce it (as minimally and precisely as possible)**:
1. [configure service accounts for pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/)
2. run following commands
```shell
fujitsu@kubenet-01:~$ kubectl exec -it counter sh
/ # kubectl get pods
Error from server (Forbidden): pods "" is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "default".
/ # kubectl get pods --as=jane
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
@deads2k @liggitt 

I will research and fix this issue myself.

**Comment by deads2k** [comment]
> I will research and fix this issue myself.

Great! assigned.

**Comment by sajattack** [comment]
@kubernetes/sig-auth-bugs

**Comment by supereagle** [comment]
Same error with #49343

**Comment by wanghaoran1988** [comment]
Workaround for this is not automatically mount the service account to the pod.

**Comment by CaoShuFeng** [comment]
> Workaround for this is not automatically mount the service account to the pod.

Yes. This needs serviceaccount feature turned on.
I will update the issue description.

**Comment by zhangxiaoyu-zidif** [comment]
Is that a env. that's Kubernetes on kubernetes?

**Comment by CaoShuFeng** [comment]
No.
Only "kubectl" runs inside a pod, no other services like kube-apiserver, kube-scheduler.

**Comment by liggitt** [comment]
@kubernetes/sig-cli-bugs
