### ISSUE TITLE
Indeterministic kubectl behavior for DaemonSet

### ISSUE THREAD

**Issue by x13n** [kubernetes/kubernetes#49627]
/kind bug

**What happened**:
I was running kubectl command during master startup. This failed during pull-kubernetes-e2e-gce-etcd3 test, so I SSHed into the master and ran the following:

$ kubectl --v=9999 set resources --dry-run --local -f /etc/kubernetes/addons/fluentd-gcp/fluentd-gcp-ds.yaml --limits=memory=333Mi -o yaml

This failed about every second run and succeeded every other, but replacing apiVersion: extensions/v1beta1 with apps/v1beta2

**What you expected to happen**:

Outputted yaml with updated limits only, apiVersion untouched.

**How to reproduce it (as minimally and precisely as possible)**:

SSH into running master instance for pull-kubernetes-e2e-gce-etcd3 test and run the command I provided.

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/commit/c168a3faebfa40fdffd1cac1f307f524786bf11b seems to have added DaemonSet to apps/v1beta2

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.876+35b16deed7c835", GitCommit:"35b16deed7c83566955daa710d95f816e0a7e7e4", GitTreeState:"clean", BuildDate:"2017-07-26T11:26:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.876+35b16deed7c835", GitCommit:"35b16deed7c83566955daa710d95f816e0a7e7e4", GitTreeState:"clean", BuildDate:"2017-07-26T11:21:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release): Container-Optimized OS
- Kernel (e.g. `uname -a`): Linux e2e-43060-master 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
- Install tools: e2e jenkins test

@kubernetes/sig-api-machinery-bugs @wojtek-t

**Comment by crassirostris** [comment]
@x13n version changing is probably OK, since kubectl on the master use the same api as the apiserver

Btw, could you please add the error you're seeing? I can't reproduce it

**Comment by x13n** [comment]
Unfortunately after changing code in my PR I'm also no longer able to reproduce this, so closing for now. Will reopen if it happens again.

/close
