### ISSUE TITLE
Kubelet ignoring --register-schedulable=false

### ISSUE THREAD

**Issue by roffe** [kubernetes/kubernetes#49628]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
Kubelet gets registered as schedulable even though `--register-schedulable=false` is set

**What you expected to happen**:
Node to show up as Unschedulable in "kubectl get nodes"

**How to reproduce it (as minimally and precisely as possible)**:
Set up kubernetes 1.7.2, start kubelet with `--register-schedulable=false` as a param

see the deprecation warning:

`Jul 26 11:25:39 agi-cph-kubemaster03 kubelet-wrapper[4549]: Flag --register-schedulable has been deprecated, will be removed in a future version`

Note the node gets registered as schedulable in the cluster.

**Anything else we need to know?**:
I know this is scheduled for deprecation. but what have you planned to replace it with? The references to the function is gone from documentation but is still present in code.

Taints might work but the visual "SchedulingDisabled" on the node statuses is something i wish to preserve

Is the idea to use taints on nodes now and how do i get the node to show up as "Unschedulable"

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: `On-prem, bare metall`
- OS (e.g. from /etc/os-release): `CoreOS 1409.7`
- Kernel (e.g. `uname -a`): `4.11.11-coreos`
- Install tools: `Bare-metall deploy`
- Others:

**Comment by roffe** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by wanghaoran1988** [comment]
@xiangpengzhao When you run kubelet --register-schedulable=false, you should make sure the node is not exits, if it's first time you register the node with that flag, the node is indeed unSchedulable, and if it's exits before and is schedulable, the 2nd time you run with the flag will not update the Node info with unSchedulable.
Replace with this is : use registerWithTaints instead

**Comment by roffe** [comment]
@wanghaoran1988 Thank you for clarification of logic.

Is cordoning the only way to mark a node as unSchedulable now in the node status?

**Comment by wanghaoran1988** [comment]
You can also delete the node before you register the node again

**Comment by roffe** [comment]
Thanks for the suggestion. 

I will start updating my deployment repo and clusters to not rely on register-schedulable and introduce taints instead.

Thanks team for quick replys!

**Comment by Bhuvanesh1208** [comment]
can anyone tell me what is the exact replacement for register-schedulable=true in kubernates 1.9

**Comment by juliantaylor** [comment]
Unfortunately `--register-with-taints=node.kubernetes.io/unschedulable=:NoSchedule` does not work either without the deprecated `--register-schedulable=false` the taint just does not get added to the node.

Is there really no replacement to get a node registered as cordoned so one does not have to introduce duplicate taints that have the same effect as `node.kubernetes.io/unschedulable`?
