### ISSUE TITLE
Incorrect Status: 'deployment "testapp" exceeded its progress deadline'

### ISSUE THREAD

**Issue by jtslear** [kubernetes/kubernetes#49637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When setting an image using the example command and following it up with a status check, the command incorrectly indicated that the deployment exceeded it's progress deadline.

I'm using a shell script for deploys, those commands look similar to this:

```bash
kubectl set image deployments/${deployment_name} ${container_name}=${image_name}:${tag} --record
kubectl rollout status deployments/${deployment_name} --namespace ${environment}
if [[ $? != 0 ]]
then
  echo "The deploy has failed"
fi
```

During a deploy, sometimes the output looks like this:
```
deployment "testapp" image updated
error: deployment "testapp" exceeded its progress deadline
The deploy has failed
```

When in fact the deployment continued to work just fine.  We never hit the limit of our `progressDeadlineSeconds` at all.

The problem comes in that my deploy script is larger then the above.  I rely on the exit code of the `status` command to determine if if should perform a rollback.  When the `status` command runs it sometimes receives the wrong information and exits with status `1`.

**What you expected to happen**:
I expected the status to report to me the legit status of the on-going deployment.  Example successful output:

```
deployment "testapp" image updated
Waiting for rollout to finish: 1 old replicas are pending termination...
Waiting for rollout to finish: 1 old replicas are pending termination...
deployment "testapp" successfully rolled out
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a deployment with `.spec.progressDeadlineSeconds` set to something reasonable, in my case it's set to `100`.  [I'm using this gist for testing.](https://gist.github.com/jtslear/aecb16e73254a6e864cde274c6b0332b)
1. In one terminal execute: `while true; do kubectl rollout status deploy/testapp; done`
1. In another terminal update the deployment, example in my case: `kubectl set image deploy/testapp testapp=jtslear/testapp:0.0.15`

**Anything else we need to know?**:
This is flakey.  I've seen this in our production clusters only a few times, and even recreating it is rather tricky.  I've had to repeat the steps above a couple of times before I ran into it.

To work around this, I've added a 3 second sleep between the `set` and `status` commands.

**Environment**:
- Kubernetes version (use `kubectl version`): seen on versions 1.7.0 and 1.7.1
- Cloud provider or hardware configuration**: minikube/GKE
- OS (e.g. from /etc/os-release): 
  - GKE: COS, build: 9460.64.0 version: 59
  - minikube: Buildroot, version 2017.02
- Kernel (e.g. `uname -a`):
  - GKE: `Linux gke-production-pool-1-7-1-2a195619-19nh 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux`
  - minikube: `Linux minikube 4.9.13 #1 SMP Tue Jul 18 22:17:02 UTC 2017 x86_64 GNU/Linux`
- Install tools: minikube/GKE
- Others:

**Comment by jtslear** [comment]
@kubernetes/sig-cli-bug

**Comment by spiffxp** [comment]
@kubernetes/sig-cli-bugs 

@kubernetes/sig-apps-bugs 
because this may be behavior of the deployment itself, not the CLI interaction

**Comment by kargakis** [comment]
I was testing this today w/o being able to reproduce :( `kubectl rollout status` uses the status of the Deployment to determine if a Deployment has succeeded rolling out so this must be an issue in the Deployment controller where the ProgressDeadlineExceeded Condition is set prematurely. Do you have access in controller manager logs?

**Comment by kargakis** [comment]
> When in fact the deployment continued to work just fine. We never hit the limit of our progressDeadlineSeconds at all.

Can you post the output of the Deployment next time you hit this?
```
kubectl get deploy/testapp -o yaml
```

**Comment by kargakis** [comment]
> Do you have access in controller manager logs?

Ideally with --v=4 (loglevel).

**Comment by jtslear** [comment]
@kargakis Thanks for taking a gander.  As stated I do run into this tremendously randomly.  

I'll see if I can get the logs.  I'm running this in GKE, so I'll need to figure out where those may live.

In the meantime, I've modified my deploy script to see if it can help with troubleshooting.  The relevant bits:
```bash
  echo "Deploying to ${environment}"
  kubectl rollout history --namespace ${environment} deployments/${deployment_name} | tail
  kubectl set --namespace ${environment} image deployments/${deployment_name} ${container_name}=${image_name}:${CIRCLE_SHA1} --record
  kubectl rollout history --namespace ${environment} deployments/${deployment_name} | tail
  kubectl get pods -l app=app --namespace ${environment}
  for sleep_time in {1..10}
  do
    echo "Take ${sleep_time}"
    kubectl rollout status deployments/${deployment_name} --namespace ${environment}
    if [[ $? == 0 ]]
    then
      break
    fi
    kubectl get pods -l app=app --namespace ${environment}
    sleep ${sleep_time}
  done
  kubectl rollout status deployments/${deployment_name} --namespace ${environment}
  if [[ $? != 0 ]]
  then
    echo "The deploy has failed, I'm going to attempt to roll back..."
    kubectl rollout undo deployments/${deployment_name} --namespace ${environment}
    kubectl rollout status deployments/${deployment_name} --namespace ${environment}
    kubectl rollout history --namespace ${environment} deployments/${deployment_name} | tail

    if [[ $? != 0 ]]
    then
      echo "Rollback was unsuccessful."
    else
      echo "Rollback was successful."
    fi
    exit 1
  else
    echo "Deployment has succeeded."
```

And another example failure.  In this case, we see it take 9 seconds before the next try outputs what I expect the first time around. (things were redacted for readability)

```
Deploying to staging3
19		kubectl set image deployments/app app=app:19 --namespace=staging3 --record=true
20		kubectl set image deployments/app app=app:20 --namespace=staging3 --record=true
21		kubectl set image deployments/app app=app:21 --namespace=staging3 --record=true
23		kubectl set image deployments/app app=app:23 --namespace=staging3 --record=true
25		kubectl set image deployments/app app=app:25 --namespace=staging3 --record=true
26		kubectl set image deployments/app app=app:26 --namespace=staging3 --record=true
27		kubectl set image deployments/app app=app:27 --namespace=staging3 --record=true
28		kubectl set image deployments/app app=app:28 --namespace=staging3 --record=true
29		kubectl scale deploy/app --replicas=1 --namespace=staging3

deployment "app" image updated
20		kubectl set image deployments/app app=app:20 --namespace=staging3 --record=true
21		kubectl set image deployments/app app=app:21 --namespace=staging3 --record=true
23		kubectl set image deployments/app app=app:23 --namespace=staging3 --record=true
25		kubectl set image deployments/app app=app:25 --namespace=staging3 --record=true
26		kubectl set image deployments/app app=app:26 --namespace=staging3 --record=true
27		kubectl set image deployments/app app=app:27 --namespace=staging3 --record=true
28		kubectl set image deployments/app app=app:28 --namespace=staging3 --record=true
29		kubectl scale deploy/app --replicas=1 --namespace=staging3
30		kubectl set image deployments/app app=app:30 --namespace=staging3 --record=true

NAME                   READY     STATUS              RESTARTS   AGE
app-1070618494-m0glv   1/1       Running             0          33m
app-1761012463-bclcv   0/1       ContainerCreating   0          0s
Take 1
error: deployment "app" exceeded its progress deadline
NAME                   READY     STATUS              RESTARTS   AGE
app-1070618494-m0glv   1/1       Running             0          33m
app-1761012463-bclcv   0/1       ContainerCreating   0          0s
Take 2
error: deployment "app" exceeded its progress deadline
NAME                   READY     STATUS    RESTARTS   AGE
app-1070618494-m0glv   1/1       Running   0          33m
app-1761012463-bclcv   0/1       Running   0          2s
Take 3
error: deployment "app" exceeded its progress deadline
NAME                   READY     STATUS    RESTARTS   AGE
app-1070618494-m0glv   1/1       Running   0          33m
app-1761012463-bclcv   0/1       Running   0          4s
Take 4
deployment "app" successfully rolled out
deployment "app" successfully rolled out
Deployment has succeeded.
```

The above output is just one example.  I haven't been able to determine if the status of the pod it's spinning up affects the outcome of the `status` command yet.

**Comment by jtslear** [comment]
Unfortunately it looks I won't have access to the controller manager logs.  GKE only exposes the api server logs.

**Comment by kargakis** [comment]
It may or may not help but please post the output of `kubectl get deploy/testapp -o yaml` next time you reproduce this. `Reason: ProgressDeadlineExceeded` should be in the status.

**Comment by innovia** [comment]
this happens to me too 
```
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-03T20:41:52Z
    lastUpdateTime: 2017-08-03T20:41:52Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2017-08-04T06:49:55Z
    lastUpdateTime: 2017-08-04T06:49:55Z
    message: ReplicaSet "app-stg-2565272565" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 195
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
```

**Comment by kargakis** [comment]
Yeah, flipping from False to True is ok since the actual state of the Deployment is True. Are you also running on GKE?

**Comment by innovia** [comment]
Im on AWS

**Comment by kargakis** [comment]
Can you post controller manager logs on log level 4 when you reproduce this?
I am interested in logs that conform to the following format:

Deployment %q timed out (%t) [last progress check: %v - now: %v]

**Comment by innovia** [comment]
@kargakis 

When you say controller manager logs what exactly do you mean? kubelet logs?

can you direct me exactly how to fecth this info?

**Comment by kargakis** [comment]
How did you deploy the cluster?

**Comment by innovia** [comment]
KOPS

**Comment by kargakis** [comment]
@justinsb how can you get the logs from the controller manager in a cluster installed by kops?

**Comment by jinlee** [comment]
I think we're seeing similar issues. We're also using `set image` to deploy and randomly see `rollout status` return with a progress deadline error. Is there anything I can provide to help track this down?

**Comment by kargakis** [comment]
controller manager logs on log level 4 when you reproduce, ideally

**Comment by jinlee** [comment]
Also running on GKE and it looks like controller manager logs aren't exposed

**Comment by kargakis** [comment]
I think I have figured out why this is happening - opened https://github.com/kubernetes/kubernetes/issues/49637 and once it merges I will backport it in 1.7.

**Comment by prudhvigodithi** [comment]
Hey so automated rollbacks through kubernetes is done currently with only "undo" command with kubectl.

Is there is way kubernetes identifies the failed deployment and rollbacks automatically to previous running deployment by itself rather than passing the command kubectl rollout undo deploy/

Also with the command "kubectl patch deployment/nginx-deployment -p '{"spec":{"progressDeadlineSeconds":100}}" kubernetes does not by default rolls back to previous success deployment after the new deployment fails and completes the progressDeadlineSeconds to 100s

can we make make kubernetes know to rollback by itself depending upon progressDeadlineSeconds ?

I have tried " kubectl patch deployment/nginx-deployment -p '{"spec":{"spec.autoRollback":true}}'" which dint seem to work

Please provide me with solution if there is a way kubernetes can automatically rollback to previous successful deployment by itself.
Thank you

**Comment by fandu139** [comment]
if you have a problem like this on deployment action github 
```
error: deployment "gke-apiadministrasi" exceeded its progress deadline
```
you can check your flow and your code,  here I assume you using program language `golang` :
1. make sure your project run success in your local. example (go run main.go)
2. after your project is run, you can `build` and `push` your image docker. here i'm use command ( `gcloud builds submit --tag gcr.io/[PROJECT_ID]/[IMAGE_NAME] .` or `gcloud builds submit --config cloudbuild.yaml .` if you use cloud build)
3. check your `google container registry` and make sure build image success
4. change your `image: gcr.io/<prject-id>/web-app-administrasi:<latest or result build image on `google container registry`> #inject docker image tag latest` on deployment.yaml
5. and then push your project to github

**Comment by dwakel** [comment]
I think what is likely to cause this issue is if your cluster runs a health check or a liveness check on your containers before deploying.
Your cluster identifies that your application isnt running and enters a waiting state due to CrashLoopBackOff 
This can be fixed by just creating a default get route on your API application on "/" that returns a 200.
