### ISSUE TITLE
Support percentage of resource in ResourceQuota

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#49630]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**:

Currently, the resource restriction in ResourceQuota are hard code for 'Object Count Quota', 'Storage Resource Quota' and 'Compute Resource Quota'. It's inconvenient if the cluster size is changed, e.g. admins have to adjust quota for each namespace.

This proposal is to support percentage of resource in ResourceQuota, e.g. 50% cpu of cluster. 'Compute Resource Quota' is easy to support as ResourceQuotaController can get total resource of cluster by Nodes' allocatable resources. For 'Object Count Quota' and 'Storage Resource Quota', admins has to define the total object count of cluster.

/cc @deads2k @derekwaynecarr

**Comment by deads2k** [comment]
> This proposal is to support percentage of resource in ResourceQuota, e.g. 50% cpu of cluster. '

I think I would consider other solutions like having a controller maintain the values in the quota.  Right now, the RQ object is self-contained and we can compute against it without any external dependencies.  If we had it based on the size of the cluster, suddenly there is an external factor at play, not reflected in the object itself.

In addition, aggregated API servers have to compute quota on their objects (they own local admission), so if we did this, the metrics about available resources in the cluster would be distributed more widely.

@derekwaynecarr

**Comment by derekwaynecarr** [comment]
@k82cn - i commented on the google doc you shared with a similar proposal.  i agree with @deads2k that dynamic allocation of quota can happen in a layer above quota.  For example, a CRD called ResourceQuotaAllocator that operates with a target of cluster size, and it programs the ResourceQuota directly with literal hard values.  ResourceQuota itself can continue to work as it does today.  From a priority standpoint as I noted in the other document, I would like to finish the use case for ResourceQuota to support simple object count quota on all existing namespaced resources now that the underlying machinery supports the discovery mechanics needed before adding more API complexity to ResourceQuota.

**Comment by k82cn** [comment]
@deads2k, @derekwaynecarr , thanks for your suggestion :). slack with derekwaynecarr@, I think 'a layer above quota' is OK for this case; but I'm not sure whether it's OK for hierarchical RQ+NS, please give me some time to think about it.

/cc @timothysc 

> From a priority standpoint as I noted in the other document, I would like to finish the use case for ResourceQuota to support simple object count quota on all existing namespaced resources now that the underlying machinery supports the discovery mechanics needed before adding more API complexity to ResourceQuota. 

I may contribute after 1.8, or do some investigation at early stage; any suggestion?

**Comment by timothysc** [comment]
You can/should be able to implement DHQ using aggregated api-servers, but priority and preemption are a requirement in order for it to work properly.  

xref: https://docs.google.com/document/d/1UEw4NASc3bIFV9q9E628ORlOiATA6HxTcBjkPKyND0I/edit#heading=h.nxatj7rbrmbp

**Comment by k82cn** [comment]
@timothysc , I'm trying to use CRD for DHQ; and an updated doc with sub-projects.

xref: https://docs.google.com/document/d/1X_-46p7mLsnflAPnLR4kMAwr-E1NoJEZVMlmo7M7uX0/edit?usp=sharing

**Comment by k82cn** [comment]
A really simple demo here: https://youtu.be/h1HfdqW2J6E , just first step :).

**Comment by derekwaynecarr** [comment]
@k82cn -- cool demo.  since this will be pursued as a layer above quota, any objecting to close of issue?

**Comment by k82cn** [comment]
I'd like to close this one, and refer it to [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator); that'll be a part of that incubator project.
