### ISSUE TITLE
Two masters using one etcd(High Availability of Masters)

### ISSUE THREAD

**Issue by akanshajain1** [kubernetes/kubernetes#49634]
I have Etcd in one AWS EC2 instance and other kubernetes master in another EC2 instance everything is working fine. Now i created AMI of my existing Master so that i can create new Master using that AMI but when i am creating new master with this AMI and my existing master goes down. It is giving error:

"error retrieving resource lock kube-system/kube-controller-manager:Get http://10.31.106.127:8080/api/v1/namespaces/kube-system/endpoints/kube-controller--manager: dial tcp 10.31.106.127:8080: getsockopt: connection refused"

I also tried **--leader-elect** also but for two masters its not working.

Please give me some suggestion how to achieve High-Availability of Kubernetes Masters with 2 Masters.

**Comment by sajattack** [comment]
@kubernetes/sig-aws-bugs

**Comment by justinsb** [comment]
If you use kops, it can create HA configurations for you:  e.g. `kops create cluster ha.example.com --zones us-east-1b,us-east-1c,us-east-1d --master-count 3`.

But we only really an odd number of masters (1 , 3 or 5), because the tested e2e configuration is a local etcd, and a 2 node etcd cluster has lower expected uptime than a 1 node etcd cluster.

**Comment by m-no-2017** [comment]
Basically there are three things to take care of if you want to get a HA setup:
- (API server flag) "--apiserver-count=[integer amount of your api servers]"
- (API server flag) "--etcd-servers=[IPs of your etcd cluster]"
- kubelet connection through a loadbalancer to your api servers as endpoints

E.g. for the API server flags:
- "--apiserver=count=2"
- "--etcd-servers=https://192.168.1.10:2379,https://192.168.1.11:2379,https://192.168.1.12:2379"

Please note that you need to have at least 3x machines with a running etcd instance regarding its [fault tolerance](https://coreos.com/etcd/docs/latest/v2/admin_guide.html#optimal-cluster-size).
