### ISSUE TITLE
Support for CloudFlare DNS provider for Federated clusters

### ISSUE THREAD

**Issue by thecodeassassin** [kubernetes/kubernetes#49639]
/kind feature

Currently federation only supports Google CloudDNS, Route53 and CoreDNS. I would love if if CloudFlare could also be supported since we use them for our DNS zones. I'm sure this will be a popular addition as well. It's already supported for ExternalDNS. I'm sure most of the work can be driven from existing providers and ExternalDNS:

https://github.com/kubernetes-incubator/external-dns/blob/master/provider/cloudflare.go

Maybe it would be nice to merge them at some point. Is there anybody already working on this or will it be my summer project?

**Comment by Krymonota** [comment]
I, too, would love to see this feature being implemented.

**Comment by quinton-hoole** [comment]
@thecodeassassin @Krymonota a PR from you would be most welcome.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#24.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
