### ISSUE TITLE
Windows Kernelspace proxier support

### ISSUE THREAD

**Issue by madhanrm** [kubernetes/kubernetes#49647]
**FEATURE REQUEST**:

**What happened**:
To provide Kernel space proxier support.
A PR is on its way.
With the new platform features being opened up in Windows, a new Kernelspace proxier of programming the VFP of the Virtual Switch has to be written to provide the equivalent iptables support.

More documentation to follow

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sajattack** [comment]
@kubernetes/sig-windows-feature-requests

**Comment by madhanrm** [comment]
Will be tracked using #49666
