### ISSUE TITLE
CNI doesnt work on Windows

### ISSUE THREAD

**Issue by madhanrm** [kubernetes/kubernetes#49646]
**What happened**:
Kubelet on windows doesn't work with Windows CNI plugins & the current code uses Linux specifc tools.
A PR is on the way, which would take care of adding Windows specific code and let Kubelet work seamlessly across windows and Linux with same user experience

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sajattack** [comment]
@kubernetes/sig-windows-feature-requests

**Comment by madhanrm** [comment]
Tagging @dineshgovindasamy
