### ISSUE TITLE
Make it possible to tune projection volume refresh period

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#49650]
It's currently not possible to tune the refresh period of volume plugins that are dynamically updated by the kubelet (secret, configmap, downward api, projected).  Currently these volume types are updated once per kubelet sync interval, and it can add up to be quite expensive with large numbers of pods and volumes, and the only control surface we have to tune is the resync interval itself.  It would be very useful to have a way to tune the refresh interval for these volumes separately from the main kubelet resync interval

/kind feature
/sig node

**Comment by derekwaynecarr** [comment]
I am trying to determine a budget for the amount of traffic I would expect from nodes to my cluster, and this was an area where having a separate tunable would be helpful.  Right now, I can set the `sync-frequency`, higher, but it doesn't let me separately tweak the volume projection pieces.

Assume:
n = number of nodes
p = number of pods per node
s = number of secrets per pod

Traffic to master right now per minute is the following:

T = (n * 12) + (n * p * s) + (events and pod status updates)

With a large cluster, the middle clause above is something I would like to tune with more granularity.  With https://github.com/kubernetes/kubernetes/pull/47367 I can establish in the steady worst case, that event traffic per pod on a node would have a long tail of .2 (right now its way worse).

@sjenning -- per our discussion today. 

/cc @gmarek

**Comment by derekwaynecarr** [comment]
hmm, so there is the `NewCachingSecretManager` which would help here, was not on my nodes when investigating this.

**Comment by derekwaynecarr** [comment]
i think `node.alpha.kubernetes.io/ttl` is what i was missing here.  closing.
