### ISSUE TITLE
Audit Logging E2E improvements

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#49653]
The [current audit logging e2e](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/audit.go) is pretty limited. It makes a small number of calls, and verifies a small number of fields by parsing out the legacy format log file.

We should make a few improvements to make this test more thorough:

- [x] Switch the test log format to JSON, so that all audit event data is included (use the structured object in the test)
- [ ] Increase the range of calls we're verifying. I don't know if we need to cover every method in Kubernetes (~250), but we should cover a broad range of resources, subresources, and verbs.
- [ ] Verify more audit event fields. Minimally we should check for presence, and expand from there (consider using the [gomega gstruct](https://github.com/onsi/gomega/tree/master/gstruct) library)

Improving the test should be a requirement for [advanced auditing beta](https://github.com/kubernetes/kubernetes/issues/48561).

/cc @ericchiang @ihmccreery @sttts

**Comment by crassirostris** [comment]
@loburm will help with this, thanks!

**Comment by tallclair** [comment]
I'm moving this to v1.9 because, while important, it shouldn't block the 1.8 release, and doesn't need to be match the release schedule. It still might be worth backporting the improvements to the 1.8 branch though.

**Comment by crassirostris** [comment]
@tallclair OK, though I hope it will mostly be addressed this week

**Comment by soltysh** [comment]
I agree with Tim, Vik if you make it, it'll merge and you rock :) But it should not block the release on it.

**Comment by soltysh** [comment]
I agree with Tim, Mik if you make it, it'll merge and you rock :) But it should not block the release on it.

**Comment by crassirostris** [comment]
Yeah, sure, I agree with that
