### ISSUE TITLE
Multi-object atomic updates

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#49658]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

/sig api-machinery
/sig storage

PVCs and PVs are first class K8s objects that are bound together.  The PV controller has a complex state machine that binds these two objects together as an atomic operation using two-way pointers.  This state machine could be simplified if the K8s API could support atomic multi-object updates.

In addition to this current behavior, we are also looking into extending the PV binding workflow to be able to bind multiple PVCs (specified by a single pod) as a single transaction.  Multi-object updates could also greatly simplify the implementation.

**Comment by liggitt** [comment]
Given that different resources can be backed by different storage, or even by different servers, cross resource transaction support seems unlikely

**Comment by mml** [comment]
I'm pretty sure we have no plans to do this.  We may have a bug where we documented why.

/sig architecture probably knows more.

**Comment by msau42** [comment]
Please link me to the bug discussing why not, since etcd supports it.
