### ISSUE TITLE
GCE: gce.conf file cannot contain key-value pairs not defined in config struct

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#49660]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The ingress controller stopped working in 1.7.0 because the ingress repository's vendored version Kubernetes was not updated to read a new key: subnetwork name.  When the ingress controller attempted to read the configuration, the ini-style parser `gcfg` returned an error saying the key is unknown and the rest of the config was ignored.

**What you expected to happen**:
`gcfg` to ignore the unknown key/value. 

/sig network
/area platform/gce

**Comment by sajattack** [comment]
@kubernetes/sig-network-bugs
