### ISSUE TITLE
client-go: discovery client should fail more gracefully

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#49664]
Instead of returning an error "unable to retrieve the complete list of server APIs" if a single endpoint can't be loaded, the discovery client should return the list of everything that it *was* able to load.

Due to this, users can currently break their clusters by making a TPR with multiple versions: https://github.com/kubernetes/kubernetes/issues/22768#issuecomment-220522337

**Comment by caesarxuchao** [comment]
I think #49495 is the correct fix. If the enpoints of some groupversions fail to load, the discovery client will return a partial list and an error. The caller can choose to ignore the error. #49495 lets the controller-manager log the error instead of crashing.
