### ISSUE TITLE
kube-proxy on Windows doesn't support kernel-mode proxying.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#49666]
The current implementation of the `kube-proxy` on Windows uses user-mode proxying.

As we have seen with the Linux implementation of user mode proxying this introduces higher tail latency and uses lots of CPU on the container host machine.

Windows has packet filtering support in the kernel similar to iptables, we should support using it from the `kube-proxy`.

/kind bug

**Comment by rjmorse** [comment]
This was initially addressed with https://github.com/kubernetes/kubernetes/pull/51064 and later fixed with work in https://github.com/kubernetes/kubernetes/pull/56529 and manually tested to be functional. This looks good to close as fixed.

**Comment by brendandburns** [comment]
Fixed now.
