### ISSUE TITLE
update gcloud compute calls to remove --zones and --regexp

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#49673]
As of `gcloud` 164.0.0 (2017-07-26), the `--zones` and `--regexp` flags are deprecated from a number of `gcloud compute` calls:
* `gcloud compute disks list`
* `gcloud compute disk-types list`
* `gcloud compute instance-groups unmanaged list`
* `gcloud compute instances list`
* `gcloud compute machine-types list`
* `gcloud compute target-instances list`

We use these pretty extensively in our cluster scripts, and we need to update them to use `--filter` so they don't mysteriously break in the future.

**Comment by pci** [comment]
I'd like to take a look at this. It is my first kubernetes bug, so please let me know if there's anything I need to do apart from opening a PR referencing this issue number.

**Comment by ixdy** [comment]
Welcome! That should be all you need to do. I'd assign this issue to you, but GitHub doesn't allow assigning to non-org members, so your comment will have to suffice.

**Comment by pci** [comment]
Also leaving as a note: it looks like `gcloud` [165.0.0 (2017-08-02)](https://cloud.google.com/sdk/docs/release-notes#16500_2017-08-02) deprecates `--regex` and `--regions` for:
* `gcloud compute target-vpn-gateways list`
* `gcloud compute target-pools list`
* `gcloud compute vpn-tunnels list`
* `gcloud compute commitments list`

These don't appear to be used in the codebase, but worth noting for future reference.

**Comment by shyamjvs** [comment]
Please note that any of the changes need to be cherry-picked to earlier release branches also. Otherwise presubmit tests will fail for PRs on those branches (unless you skip e2e tests for those branches which I don't think we want).

**Comment by shyamjvs** [comment]
I think this issue is becoming increasingly important, as I've been asked by at least 3 people by now why the kube-up/kube-down scripts are failing.
Could someone make sure it's fixed asap?

**Comment by ixdy** [comment]
gcloud 168.0.0 seems to have broken things further. I'm now consistently getting stuff like
```
ERROR: (gcloud.compute.instance-groups.managed.list-instances) wrong collection: expected [compute.regionInstanceGroupManagers,compute.instanceGroupManagers], got [compute.instanceGroups], for path [...]
```

**Comment by shyamjvs** [comment]
Yes.. Heard the same issue from @jcbsmpsn too very recently. The fix needs to go in asap.

**Comment by ixdy** [comment]
this latest breakage seems different. `gcloud compute instance-groups managed list` is now returning a URL, and `gcloud compute instance-groups managed list-instances` isn't parsing that URL correctly.

**Comment by shyamjvs** [comment]
fyi - @wojtek-t @mwielgus

**Comment by roberthbailey** [comment]
This is being worked on by @pci in https://github.com/kubernetes/kubernetes/pull/50398

**Comment by pci** [comment]
Cherry pick PRs are https://github.com/kubernetes/kubernetes/pull/51651, https://github.com/kubernetes/kubernetes/pull/51652 and https://github.com/kubernetes/kubernetes/pull/51654

**Comment by pci** [comment]
> Also it's great how gcloud crashes, rather than handling the deprecation gracefully.

Wonderful. Sorry we missed that one.

**Comment by ixdy** [comment]
Everything is terrible.

Now we're getting warning messages like
```console
$ nodes=$(gcloud compute instances list --project k8s-scale-testing '--filter=(metadata.created-by:*zones/us-east1-a/instanceGroupManagers/gke-cluster-1-default-pool-c9471aa4-grp)' '--format=get(name)')
WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  metadata."created-by":*zones/us-east1-a/instanceGroupManagers/gke-cluster-1-default-pool-c9471aa4-grp currently matches but will not match in the near future.  Run `gcloud topics filters` for details.
```

**Comment by pci** [comment]
Had a quick look, the change was introduced in 168.0.0.0 (although there's nothing in the release notes!). [Here are the new docs](https://cloud.google.com/sdk/gcloud/reference/topic/filters) and `:` is now only allowed an optional _trailing_ `*`. Switching to `--filter=(metadata.created-by~'.*zones(..)'` should fix it, but I won't get a chance to test until the weekend.

**Comment by roberthbailey** [comment]
@ixdy says that this issue is not a release blocker for 1.8, but that we will need to backport the fix into the 1.8 release branch.

**Comment by roberthbailey** [comment]
@ixdy - I'm going to bump this out of the 1.8 milestone as it isn't a release blocking issue, but we shouldn't lose track of fixing it.

**Comment by dims** [comment]
Thanks @roberthbailey

**Comment by pci** [comment]
A new arrival in my family has meant I've not had time to get make a PR for this, if it's still here when I have some time I'll take it. But if anyone else has the capacity, or if you're reading this and looking for a good first issue to take, please comment below!

**Comment by cblecker** [comment]
@ixdy is this still relevant?

**Comment by ixdy** [comment]
I don't see any gcloud warnings (of this form) in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/21952?log#log, so I think we're good for now.

/close
