### ISSUE TITLE
Bulk of CI jobs are leaking a master node

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#49679]
Observations:
Seems it fails to tear down the master nodes?

We bumped gcloud in e2e image, but https://github.com/kubernetes/kubernetes/issues/49673 seems not relevant - tried locally with 162.0.0 and still see the error.

And also saw a lot of `Found 4 nodes, but expected 3. Your cluster may not behave correctly.`

sample log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-gci-kubectl-skew-serial/1028?log#log

cc @rmmh @MrHohn

**Comment by MrHohn** [comment]
Confirmed locally, gcloud upgrade introduced this:
```
# Using 163.0.0.
$ gcloud compute instances list --project=zihongz-k8s-dev --regexp "e2e-test-zihongz-master(-...)?"
NAME                     ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
e2e-test-zihongz-master  us-central1-b  n1-standard-1               10.128.0.2   35.192.160.247  RUNNING

# Using 164.0.0.
$ gcloud compute instances list --project=zihongz-k8s-dev --regexp "e2e-test-zihongz-master(-...)?"                                                              
WARNING: This flag is deprecated. Use `--filter="name ~ REGEXP"` instead.
WARNING: This argument is deprecated. Use `--filter="name =( NAME ... )"` instead.
Listed 0 items.
```

Above is basically the same gcloud command as https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1759-L1766. Hence `get-master-replicas-count()` return 0, then we are counting one less node [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/validate-cluster.sh#L65-L72).

**Comment by krzyzacy** [comment]
hummmmmmm ahhhhhh thank!

**Comment by fejta** [comment]
If we use the non-deprecated flag does it fix things?

**Comment by krzyzacy** [comment]
didn't understand the other warning..

```
senlu-macbookpro:test-infra senlu$ gcloud compute instances list --project=zihongz-k8s-dev --filter="name =( e2e-test-zihongz-master ... )"
WARNING: This argument is deprecated. Use `--filter="name =( NAME ... )"` instead.
NAME                     ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
e2e-test-zihongz-master  us-central1-b  n1-standard-1               10.128.0.2   35.192.160.247  RUNNING
```

**Comment by fejta** [comment]
@kubernetes/sig-cluster-lifecycle-test-failures

**Comment by MrHohn** [comment]
Probably use
```
gcloud compute instances list --project=zihongz-k8s-dev --filter "name~e2e-test-zihongz-master"
```
if we are still sticking with regex?

**Comment by MrHohn** [comment]
`--filter="name =( NAME ... )"` may not fit our case?
```
key =( value ... )
            True if key is equal to any value in the (space, tab, newline, ,)
            separated list.
```

**Comment by krzyzacy** [comment]
same warning :-) I'm trying different things

from the latest doc:
```
Sets a filter expression for filtering listed resources, in the form filter={expression}. Your {expression} must be in the format: field_name comparison_string literal_string. 
```

**Comment by krzyzacy** [comment]
@fejta shall we pin our gcloud to 163.0.0 for now?

**Comment by krzyzacy** [comment]
I think that warning is a gcloud bug which is not suppose to show up :-)

**Comment by MrHohn** [comment]
> I think that warning is a gcloud bug which is not suppose to show up :-)

I believe so, can't imagine gcloud deprecates all other [supported Operator Terms](https://cloud.google.com/sdk/gcloud/reference/topic/filters) :)

**Comment by krzyzacy** [comment]
I feel like we'll need to manually clean stuff up since e2e-down will not deal with leaked master nodes..

**Comment by krzyzacy** [comment]
(Good news is all boskos jobs is still healthy and being cleaned up properly, we'd move the rest jobs over soon)

**Comment by krzyzacy** [comment]
Update: rolled gcloud back to 163.0.0, I'm running a janitor pass now to clean up leaked master nodes, however jobs with `--gcp-cloud-sdk=` set will still grab gcloud from their designated bucket which might still fail.

Filed bug against gcloud sdk, once they have a fix we will push a new image.

cc @shyamjvs if you still see projects have leaked e2e-master, you can run something like `./test-infra/boskos/janitor/janitor.py --project=project-name --hour=0` to wipe it, or do it manually.
