### ISSUE TITLE
Failed tests: pull-kubernetes-e2e-gce-etcd3 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#49672]
Found it in #49238
An example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49238/pull-kubernetes-e2e-gce-etcd3/43197/

All recent tests failed:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-etcd3?before=43287

@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
yeah all the ci jobs are seems leaking the master node, looking, assign to oncall

/assign @rmmh

**Comment by krzyzacy** [comment]
cc @MrHohn

**Comment by krzyzacy** [comment]
eh, wrong thread..
/unassign @rmmh

**Comment by fejta** [comment]
@kubernetes/sig-cluster-lifecycle-test-failures

**Comment by fejta** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce-etcd3/43288/ uses the latest test-infra commit that downgraded the gcloud version but it doesn't seem to have done anything?

https://github.com/kubernetes/test-infra/commits/master

**Comment by fejta** [comment]
On the other hand it seems to have made CI happy? https://k8s-testgrid.appspot.com/google-gce

**Comment by crimsonfaith91** [comment]
PR #49168 and #49674 are also affected.

**Comment by janetkuo** [comment]
cc current buildcop @pwittroc

**Comment by jpbetz** [comment]
I'll look into this now.

Unfortunately, I'm not a project member yet, so I can't assign this to myself.

**Comment by MrHohn** [comment]
Checked the pr job project. All the pr clusters are running in the same network (e2e) with overlapping CIDR  for pods network, which essentially broke all pods network functionality.

Before it was broken, we would create a separate network (e2e-PR_NUMBER) for each pr job. Possibly something mistakenly overwrote this network config.

**Comment by krzyzacy** [comment]
I think it's broken by https://github.com/kubernetes/test-infra/pull/3713 and need https://github.com/kubernetes/test-infra/pull/3729, I guess I'll put up something

**Comment by krzyzacy** [comment]
Jenkins is unhappy now which gives us some time

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48905/pull-kubernetes-e2e-gce-etcd3/43357 latest run looks good, but there's a giant queue in now.

**Comment by janetkuo** [comment]
@krzyzacy is this fixed? Can we close this issue?

**Comment by krzyzacy** [comment]
Yeah I think so, I'll close this and keep monitoring sq. 

/close
