### ISSUE TITLE
should reject headless service without port definition

### ISSUE THREAD

**Issue by wzhliang** [kubernetes/kubernetes#49686]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When deploying a headless service without port definition, k8s allows it but the service gets no endpoint. 

**What you expected to happen**:
Like a normal clusterIP service, if there is no port definition, it should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:
create a headless service with no port definition

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6, 1.7.0
- Cloud provider or hardware configuration**: bare metal
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): Linux master 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by sajattack** [comment]
/area/apiserver
@kubernetes/sig-network-bug

**Comment by sajattack** [comment]
@kubernetes/sig-network-bugs

**Comment by m1093782566** [comment]
@wzhliang Could you please provide more reasons why you think kubernetes should reject headless service without port definition?

**Comment by wzhliang** [comment]
@m1093782566  without port definition, `kubectl describe svc foo` shows no endpoint. `nslookup` cannot find the pod either. so from all I can see, it's not working. Either it should be rejected, or it's a bug somewhere else - I actually thought headless is only related with DNS entries.

**Comment by m1093782566** [comment]
@wzhliang 

AFAIK, ports field is not required in headless service or ExternalName type service, see https://kubernetes.io/docs/concepts/services-networking/service/

>Accessing a Service without a selector works the same as if it had selector. The traffic will be routed to endpoints defined by the user (1.2.3.4:9376 in this example).
An ExternalName service is a special case of service that does not have selectors. It does not define any ports or endpoints. Rather, it serves as a way to return an alias to an external service residing outside the cluster.
kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com

For headless service, it is not intended for client accessing, it is used to create a DNS entry. So, I assume the port is not necessary for headless service?

**Comment by wzhliang** [comment]
https://github.com/kubernetes/kubernetes/issues/49722 raised

**Comment by dcbw** [comment]
https://github.com/kubernetes/kubernetes/pull/47250 was already merged to fix #49722, so can this issue be closed as well?

**Comment by wzhliang** [comment]
Yes please close this one.
