### ISSUE TITLE
Allow discovering if basic auth is enabled

### ISSUE THREAD

**Issue by floreks** [kubernetes/kubernetes#49709]
I'm not sure if we can classify it as a bug so let's discuss. 

```
Kubernetes version: 1.7.2
Client-go: 3.0.0 (compatible with k8s 1.6+)
```

Currently I'm trying to implement log in mechanism for kubernetes dashboard. I have noticed that when [AuthInfo](https://github.com/kubernetes/kubernetes/blob/ebf24c14a916adebc37023be69f112d2c97759a9/staging/src/k8s.io/client-go/tools/clientcmd/api/v1/types.go#L79) is filled with username/password there are 2 cases where there is no check if credentials are valid and it falls back to anonymous user.

1. `--authorization-mode=ABAC` is not set
2. `--authorization-mode=ABAC` and `--authorization-policy-file=...` are set but `--basic-auth-file=...` is not set

Only in case I set all 3 parameters username/password combination is actually checked.

I'm aware that in these cases code responsible for basic authorization is disabled but due to that it is hard to implement good log in mechanism. From dashboard point of view I'd expect to:

1. Get response `Unauthorized` if user tries to log in with username/password and basic auth is disabled or user/password is not correct.
2. Be able to check which authorization modes are enabled and show only the ones supported by apiserver.

Is second option something that is possible to check using existing api? `kubectl api-versions` does not even list `abac...` api version. Is it maybe possible to check 'name' of user? We could also reject login prompt if health check falls back to using anonymous user.

@kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
There's really just one case, when `--basic-auth-file=...` is not set. When basic auth is not enabled, basic auth headers are ignored. 

> Be able to check which authorization modes are enabled and show only the ones supported by apiserver.
> Is second option something that is possible to check using existing api? kubectl api-versions does not even list abac... api version. Is it maybe possible to check 'name' of user? We could also reject login prompt if health check falls back to using anonymous user.

Configured authentication methods are not exposed via API today. Authentication methods are not the same as enabled APIs (also, ABAC doesn't have anything to do with basic auth… it is authorization, not authentication)

There's been discussion of a way to discover configured authentication as part of a `kubectl login` command, but other development has taken priority

**Comment by floreks** [comment]
Are basic auth headers also ignored when `--token-auth-file` is set instead of `--basic-auth-file`? For me only option to get 401 response when using basic auth was to set all 3 flags.

> Configured authentication methods are not exposed via API today. Authentication methods are not the same as enabled APIs (also, ABAC doesn't have anything to do with basic auth… it is authorization, not authentication)
>
> There's been discussion of a way to discover configured authentication as part of a kubectl login command, but other development has taken priority

Is there any workaround working now that you could suggest other than just disabling option to log in using username/password?

Can we maybe check name of user that makes the request (`system:anonymous`) ?

**Comment by liggitt** [comment]
> Are basic auth headers also ignored when --token-auth-file is set instead of --basic-auth-file? 

Yes. If the server is not configured to accept a specific type of authentication credential, it doesn't even look for it on the request. For example, one of the possible authentication methods is to accept user info in headers from an auth proxy. If that authentication method is not enabled, the server does not even look for user info headers.

> Is there any workaround working now that you could suggest other than just disabling option to log in using username/password?

Until authentication methods are discoverable, I'd expect an option to the dashboard to select which methods to enable.

> Can we maybe check name of user that makes the request (system:anonymous) ?

`system:anonymous` is assigned to requests that do not present any credentials for the authentication methods enabled on the server. There was a [proposed PR](https://github.com/kubernetes/kubernetes/pull/30829) at one point to echo the effective user in a header in API responses, but that is not available today.

**Comment by floreks** [comment]
> Until authentication methods are discoverable, I'd expect an option to the dashboard to select which methods to enable.

I guess we'll have to do it this way for now. Similar to apiserver dashboard will accept some arguments that will be responsible for enabling specific login methods. It will be great though if we'll be able to automate that

**Comment by lxlxok** [comment]
Hey @floreks  Thanks for developing this great log in feature. I am working on enhancing this feature. Is it possible to debug login feature by using "gulp sever"? Currently,  every time when I debug I need to rebuild the docker image and deploy it on cluster so that I can test my code by visiting https endpoint.
