### ISSUE TITLE
Loadbalancing: L7 [k8s.io] [Slow] Nginx should conform to Ingress spec is consistently failing in 1.7 branch on GKE

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49704]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gke-slow-release-1-7

@bowei - can you please triage?

This will be blocking 1.7.3 release cut.

**Comment by wojtek-t** [comment]
Same here:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-ingress-release-1-7

**Comment by bowei** [comment]
cc: @nicksardo triage?

**Comment by nicksardo** [comment]
The `BeforeEach` condition of this test is failing when attempting to create a firewall rule:

```log
I0727 10:38:42.280] Jul 27 10:38:27.272: INFO: Error creating firewall-rules, output: Creating firewall...
I0727 10:38:42.281] failed.
I0727 10:38:42.281] ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
I0727 10:38:42.281]  - The resource 'projects/k8s-jkns-gke-slow-1-3/global/networks/bootstrap-e2e' was not found
```

At the top of the log file, I checked that the desired network is `bootstrap-e2e`
```
W0727 10:29:33.180] KUBE_GKE_NETWORK=bootstrap-e2e
W0727 10:29:33.181] E2E_UP=true
W0727 10:29:33.181] KUBERNETES_SERVICE_PORT_HTTPS=443
W0727 10:29:33.181] KUBE_GCE_NETWORK=bootstrap-e2e
```

There's currently no test running, so I don't know what network name is being used. This may be related to https://github.com/kubernetes/kubernetes/issues/49672#issuecomment-318436864...

**Comment by krzyzacy** [comment]
So this should be back to normal for the next run. However Prow is affected by the Jenkins outage so next ci job might take a while to run. I'll watch this.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-ingress-release-1-7 - ingress is green now, I'll close this. Other jobs are still soaking.

/close

**Comment by ericchiang** [comment]
This has cropped up again:

https://k8s-testgrid.appspot.com/release-master-blocking#gke-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke-ingress

Example failure

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-slow/8588#sig-network-loadbalancing-l7-sig-network-slow-nginx-should-conform-to-ingress-spec

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:201
Expected error:
    <*errors.errorString | 0xc420305220>: {
        s: "Failed to execute a successful GET within 15m0s, Last response body for http://104.154.182.17/foo, host foo.bar.com:\n<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.11.9</center>\r\n</body>\r\n</html>\r\n\n\ntimed out waiting for the condition\n",
    }
    Failed to execute a successful GET within 15m0s, Last response body for http://104.154.182.17/foo, host foo.bar.com:
    <html>
    <head><title>503 Service Temporarily Unavailable</title></head>
    <body bgcolor="white">
    <center><h1>503 Service Temporarily Unavailable</h1></center>
    <hr><center>nginx/1.11.9</center>
    </body>
    </html>
    
    
    timed out waiting for the condition
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/ingress_utils.go:930
```

Re-opening for 1.8

**Comment by ericchiang** [comment]
cc @kubernetes/sig-network-bugs

**Comment by ericchiang** [comment]
(this appears to be working again)
