### ISSUE TITLE
Use a PartialObjectMetadata based CodecFactory for GC client

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#49718]
The [metaonly](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/garbagecollector/metaonly) garbage collector package intends to provide a `serializer.CodecFactory` which works only with object metadata (as the GC only cares about object relationships, not object contents). This is important as an optimization (as object contents can vary wildly in size) and as a matter of generic semantics (the GC should work with any object regardless of its non-metadata structure).

The current package is only capable of working with built-in types, and does not support instances of custom resource definition types. When the [GC supports custom resources](https://github.com/kubernetes/kubernetes/issues/44507), the metaonly package should also support custom resources.

/kind feature
/cc @kubernetes/sig-api-machinery-feature-requests

**Comment by ironcladlou** [comment]
@smarterclayton directed me to https://github.com/kubernetes/community/pull/123 as a possible way forward here without doing a bunch of custom client codec work.

**Comment by ironcladlou** [comment]
My vote is to refactor to a single kube client within the GC using alternate representations via Content-Type parameters once PartialObjectMetadata hits beta. In addition to being even more optimizing that we had hoped (given the server transform, serialization benefits, etc), the overall GC code will be simplified where clients are involved.

**Comment by ironcladlou** [comment]
Via Accept header parameters, rather

**Comment by caesarxuchao** [comment]
I agree we should use a client that utilize the Accept header parameters to only acquire the PartialObjectMetadata. We can use a restclient or a dynamic client, not sure which one will be more elegant.

**Comment by nikhita** [comment]
Can we close this? GC uses the dynamic client now: https://github.com/kubernetes/kubernetes/pull/63444
