### ISSUE TITLE
How to use Watch APIs

### ISSUE THREAD

**Issue by vaibhavswarnkar** [kubernetes/kubernetes#49716]
How to implement watch API using OkHttp and Retrofit in Java. Do I have to use WebSockets for this to implement?

**Comment by vaibhavswarnkar** [comment]
@jianzhangbjz @yastij Do we have a way to use this watch API?

**Comment by vaibhavswarnkar** [comment]
Is there anyone who knows how to do this?

**Comment by ravilr** [comment]
@vaibhavswarnkar you may want to look at https://github.com/fabric8io/kubernetes-client#following-events
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java

**Comment by liggitt** [comment]
take a look at https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java
