### ISSUE TITLE
Make scheduler perf read config from file

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#49723]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
As of now, we are reading scheduler_perf input data(predicates and priorites that need to be evaluated) from hardcoded values. 

**What you expected to happen**:
We need to read from a yaml file to switch on and off various predicates and priorities.

/sig scheduling

**Comment by jayunit100** [comment]
+1

**Comment by resouer** [comment]
I work out a patch to implemented this. Please take a look @jayunit100 

- [X] Make scheduler configurable in scheduler_perf #51776
- [ ] Respect more predicates & priorities in scheduler_perf
