### ISSUE TITLE
headless service with no port definition finds no endpoint

### ISSUE THREAD

**Issue by wzhliang** [kubernetes/kubernetes#49722]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When deploying a headless service without port definition, the service finds no endpoint and service name couldn't be resolved.

**What you expected to happen**:
The headless service finds endpoint matching the selector and the service name resolves to the endpoints.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a headless service with no port definition

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.6.6, 1.7.0
- Cloud provider or hardware configuration**: bare metal
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): Linux master 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by wzhliang** [comment]
@kubernetes/sig-network-bugs

**Comment by xiangpengzhao** [comment]
Thanks @wzhliang for reporting this! This was fixed by #47250. Would you please try with the master branch?

**Comment by xiangpengzhao** [comment]
@wzhliang can this issue be closed?

**Comment by wzhliang** [comment]
OK. Please close this. If I see it again I'll re-open.

**Comment by xiangpengzhao** [comment]
I don't have the right to close issue. As you're the author, you can close it :)

**Comment by wzhliang** [comment]
Forgot who opened it.
