### ISSUE TITLE
kubelet send volumesInUse sorted in status updates

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#49731]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`volumesInUse` is not sent in a stable sort order.  this makes node status patch requests larger than needed, and makes debugging nodes harder than necessary.

**What you expected to happen**:
stable sort of volumesInUse

**How to reproduce it (as minimally and precisely as possible)**:
always

**Anything else we need to know?**:
nope

**Environment**:
n/a

**Comment by derekwaynecarr** [comment]
@jboyd01 - this is a good getting started item.

**Comment by dixudx** [comment]
@derekwaynecarr @jboyd01 I've already submitted a PR in #49849. PTAL. Thanks.
