### ISSUE TITLE
Update client-gen doc

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#49737]
https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md is out dated, especially after https://github.com/kubernetes/kubernetes/pull/49192 unified the tags used by client-gen.

**Comment by caesarxuchao** [comment]
@mfojtik could you help?

**Comment by mfojtik** [comment]
/assign 

@caesarxuchao i'll try write something up later today

**Comment by caesarxuchao** [comment]
closed by https://github.com/kubernetes/community/pull/1008/files
