### ISSUE TITLE
Cross-group conversions should be tested in roundtrip test 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#49734]
From https://github.com/kubernetes/kubernetes/pull/49454#discussion_r129645760:
> Our roundtrip test doesn't exercise these conversions, because the internal Kind and the external Kind are of different group (see [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/testing/roundtrip/roundtrip.go#L210-L212)). We need to update `roundTripToAllExternalVersions` to test cross-group conversions. 

@kubernetes/sig-api-machinery-bugs @caesarxuchao @sttts @deads2k @lavalamp

**Comment by janetkuo** [comment]
Can we fix this by changing

```go
if externalGVK.GroupKind() != internalGVK.GroupKind() {
	continue
}
```

to 

```go
if externalGVK.GroupKind().Kind != internalGVK.GroupKind().Kind {
	continue
}
```
?

**Comment by janetkuo** [comment]
The above change works locally. 
```console
$ go test -v k8s.io/kubernetes/pkg/api -run TestRoundTripTypes$ 
        roundtrip.go:155: round tripping apps/__internal, Kind=DeploymentList
        roundtrip.go:220:       round tripping to apps/v1beta2, Kind=DeploymentList v1beta2.DeploymentList
        roundtrip.go:220:       round tripping to extensions/v1beta1, Kind=DeploymentList v1beta1.DeploymentList
        roundtrip.go:220:       round tripping to apps/v1beta1, Kind=DeploymentList v1beta1.DeploymentList
        roundtrip.go:220:       round tripping to apps/v1beta2, Kind=DeploymentList v1beta2.DeploymentList
        roundtrip.go:220:       round tripping to extensions/v1beta1, Kind=DeploymentList v1beta1.DeploymentList
...
PASS
ok      k8s.io/kubernetes/pkg/api       2.800s
```

**Comment by sttts** [comment]
@janetkuo Only works if we don't reuse kind names. It's hard to believe that we don't. But maybe my assumption was too pessimistic and it really works.

I have started to use the registered conversion funcs for this test https://github.com/kubernetes/kubernetes/pull/49748, but this lead me to very strange issues with our global schema. So I am still investigating this.

**Comment by caesarxuchao** [comment]
> But maybe my assumption was too pessimistic and it really works.

Can we blacklist such kinds if there is any? I expect reuses to be rare.

**Comment by sttts** [comment]
> Can we blacklist such kinds

Sure, and it seems we have no such conflicts (for top-level objects) right now. So the blacklist is empty anyway. Wondering about @gmarek's new events API. That might be a first example.

**Comment by gmarek** [comment]
@sttts - after discussions with @bgrant0607 I'm dropping new api group and make changes to existing Events, as stopping to send 'old' Events would be a breaking change. So no need to worry about me any more:)
