### ISSUE TITLE
TLD compromised

### ISSUE THREAD

**Issue by lypht** [kubernetes/kubernetes#49730]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: https://*.kubernetes.io resolves to a self-signed under construction credit card spam page.  I tried api.kubernetes.io and apis.kubernetes.io

**What you expected to happen**: A 404 or home page redirect.

**How to reproduce it (as minimally and precisely as possible)**: Browse to one of the two aforementioned sites.

**Anything else we need to know?**: Not imperative to resolve; I'm just informing the community that this is occurring.

**Environment**:
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration**: n/a
- OS (e.g. from /etc/os-release): Darwin
- Kernel (e.g. `uname -a`): n/a
- Install tools: google-chrome
- Others:

**Comment by thockin** [comment]
I get a google 404 for those URLs.  Are you sure it's not your provider DNS hijacking.

**Comment by thockin** [comment]
We had a wildcard DNS record, for some reason.  I will see if we can delete that - I don't think of anything we're doing with it - it must be a leftover.

**Comment by thockin** [comment]
I removed the wildcard record.  Such name lookups should now give you NXDOMAIN responses.

**Comment by lypht** [comment]
Thanks, Tim.  It potentially could have been DNS hijacking (noticed it in the United Club lounge in Newark, on their private WIFI).  Granted, that would be a fantastic location for a pineapple.  Glad the wildcard was purged.
