### ISSUE TITLE
etcd3 storage has no instrumentation, grpc client metrics aren't any good either

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#49746]
In etcd2 we tracked latency, count per resource, and a few other options.  etcd3 storage has none of this instrumentation.  We could use the gRPC metrics, but they don't provide useful info (this is from adding the default indicators, and as you can see tell us nothing):

```
$ kubectl get --raw /metrics | grep grpc
# HELP etcd_network_client_grpc_received_bytes_total The total number of bytes received from grpc clients.
# TYPE etcd_network_client_grpc_received_bytes_total counter
etcd_network_client_grpc_received_bytes_total 57586
# HELP etcd_network_client_grpc_sent_bytes_total The total number of bytes sent to grpc clients.
# TYPE etcd_network_client_grpc_sent_bytes_total counter
etcd_network_client_grpc_sent_bytes_total 1.7420058e+07
# HELP grpc_client_handled_total Total number of RPCs completed by the client, regardless of success or failure.
# TYPE grpc_client_handled_total counter
grpc_client_handled_total{grpc_code="OK",grpc_method="LeaseGrant",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 2
grpc_client_handled_total{grpc_code="OK",grpc_method="Range",grpc_service="etcdserverpb.KV",grpc_type="unary"} 642
grpc_client_handled_total{grpc_code="OK",grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 16
grpc_client_handled_total{grpc_code="Unavailable",grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
# HELP grpc_client_msg_received_total Total number of RPC stream messages received by the client.
# TYPE grpc_client_msg_received_total counter
grpc_client_msg_received_total{grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
grpc_client_msg_received_total{grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 72
# HELP grpc_client_msg_sent_total Total number of gRPC stream messages sent by the client.
# TYPE grpc_client_msg_sent_total counter
grpc_client_msg_sent_total{grpc_method="LeaseGrant",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 2
grpc_client_msg_sent_total{grpc_method="Range",grpc_service="etcdserverpb.KV",grpc_type="unary"} 642
grpc_client_msg_sent_total{grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 17
grpc_client_msg_sent_total{grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 72
# HELP grpc_client_started_total Total number of RPCs started on the client.
# TYPE grpc_client_started_total counter
grpc_client_started_total{grpc_method="LeaseGrant",grpc_service="etcdserverpb.Lease",grpc_type="unary"} 2
grpc_client_started_total{grpc_method="Range",grpc_service="etcdserverpb.KV",grpc_type="unary"} 642
grpc_client_started_total{grpc_method="Txn",grpc_service="etcdserverpb.KV",grpc_type="unary"} 17
grpc_client_started_total{grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 72
```

We can't add key level logging to the client, because we'd blow up on high cardinality metrics.  Instead, I think we should instrument etcd3 like etcd2 - metrics per rest storage, not per key or client.

@kubernetes/sig-scalability-misc @kubernetes/sig-instrumentation-feature-requests

**Comment by smarterclayton** [comment]
I think this is required for any serious cluster debugging.

**Comment by brancz** [comment]
Latency metrics actually just have to be enabled for the grpc metrics: https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/master/client_metrics.go#L64-L66

They are only disabled by default as they can potentially produce a lot of metrics, but this seems like a perfect use case to enable them. Now it's just a question of how to do that with the etcdv3 client.

**Comment by xiang90** [comment]
@brancz 

see https://godoc.org/github.com/coreos/etcd/clientv3#example-Client--Metrics

**Comment by brancz** [comment]
@xiang90 thanks for the hint! That's great! I actually recently contributed to the grpc metrics package that we can pass it a metrics registry instead of it using the global one. For now we can pass in the global one into those functions, but we should step by step move towards not registering metrics via globals and init functions.

**Comment by xiang90** [comment]
/cc @jpbetz @rphillips 

after we bump the etcd client version, the client side metrics should be enabled easily.

/remove-lifecycle stale

**Comment by xiang90** [comment]
@smarterclayton 

as we are going to bump etcd client in 1.10, shall we also make this issue part of 1.10? it should be fairly easy to enable.

**Comment by redbaron** [comment]
Version bump happened in 1.10 cycle, right?

/remove-lifecycle stale

**Comment by wenjiaswe** [comment]
I think this is fixed via https://github.com/kubernetes/kubernetes/pull/75953

**Comment by brancz** [comment]
Nice! I missed that one, thanks for linking it! I agree #75953 is a good start!
