### ISSUE TITLE
Kubernetes watch events are out of order

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#49745]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

/kind bug

**What happened**:

I create CRD and two custom resources. Then watch it from "0". The two events are out of order:

```
event: ADDED name: test2 version: 950362
event: ADDED name: test  version: 950361
```
The object with larger resource version is delivered before the one with smaller version.
For more context, I create "test" object before "test2".

**What you expected to happen**:
Events should be delivered in order of object's resource versions, from smallest.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.1-gke.0", GitCommit:"841411e511bfb1ccd78e76bf8633d4515061e18b", GitTreeState:"clean", BuildDate:"2017-07-14T17:52:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
The watch events when watching from 0 are synthetic. Sorting the list of objects from the store could be significant… I'm not sure we want to add server side sorting on potentially very large lists

**Comment by hongchaodeng** [comment]
@liggitt 
This is just one example. Even watching from >0 also produce out of order delivery. I guess this is not how watch stream should work, right?
Any suggestion how to fix it or work around it?

**Comment by liggitt** [comment]
> Even watching from >0 also produce out of order delivery

*that* is unexpected

**Comment by hongchaodeng** [comment]
This doesn't make any sense.
Let's take this problem as an example:
- object A with version 1, B with version 2
- if out of order, B comes first
- then connection is closed (by apiserver)
- how to re-watch at this moment? Usually it watch at version 2, if so A will never be observed, and it is missing events. So I guess you are also trying to say missing events is _expected_?

**Comment by mml** [comment]
cc @jpbetz 
cc @caesarxuchao

**Comment by jnicholls** [comment]
I suggest reopening this, due to a few client projects having ran into this issue. I will be addressing this issue in the Rust client's Reflector implementation.

**Comment by jnicholls** [comment]
We decided to leave it to upstream Kubernetes since resourceVersions are technically an opaque value, and any perceived order of the values should not be assumed by the clients. So I would strongly suggest if there is no means for clients to order events on their own, and the apiserver's expectations is to deliver events in the order in which they occurred, that this issue be reopened, confirmed, and then if necessary, resolved.
