### ISSUE TITLE
GPU consistently failing in 1.7 branch

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49757]
GPU tests in 1.7 branch started consistently failing:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gke-gpu-1-7

The other ones became flakey recently:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-gpu-1-7

@vishh - can you please take a look - this will be blocking 1.7.3 patch release?

**Comment by feiskyer** [comment]
The Container Engine API is not enabled for project. Maybe there are some settings wrong on the project?

**Comment by mindprince** [comment]
This is passing now. I don't know how the project got into the state of not having it's container engine API enabled.
