### ISSUE TITLE
Method names are not correct in comments generated by deepcopy-gen

### ISSUE THREAD

**Issue by supereagle** [kubernetes/kubernetes#49755]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
[pkg/apis/apps/zz_generated.deepcopy.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/zz_generated.deepcopy.go#L88-L96):
```go
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevision.
func (x *ControllerRevision) DeepCopy() *ControllerRevision {
	if x == nil {
		return nil
	}
	out := new(ControllerRevision)
	x.DeepCopyInto(out)
	return out
}
```

The method name in comment does not match the real method name.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Regenerate these codes and update the dependency in vendor after kubernetes/gengo#69 merged.

**Comment by supereagle** [comment]
@caesarxuchao  Do you know how to generate the `zz_generated.deepcopy.go` files? I'm not sure where is the script for that.

**Comment by caesarxuchao** [comment]
cc @sttts

**Comment by caesarxuchao** [comment]
> Do you know how to generate the zz_generated.deepcopy.go files?

make generated_files

**Comment by sttts** [comment]
Can we also merge https://github.com/kubernetes/gengo/pull/66 when we are at it? @thockin ptal. It's rebased.

**Comment by k82cn** [comment]
i think we need to update gengo in vendor.

**Comment by supereagle** [comment]
@k82cn Sure, will update it in the PR #49782.
