### ISSUE TITLE
Add support for IPv6 to AWS ELBs

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kubernetes#49753]
/kind feature

The Kubernetes does a nice job of providing support for AWS ELBs using IPv4 to back `type=LoadBalancer` Services. Amazon also provides support for IPv6 and both IPv4 & IPv6 by prepending the FQDN for the ELB with `ipv6.` or `dualstack.` respectively. Reference this [aws doc](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-internet-facing-load-balancers.html).

This is a feature request to add a new annotation that could be applied to any Service to enable IPv6 or IPv4 & IPv6 support in AWS. So when Kubernetes creates that Service, it would assign the ELB FQDN that supported IPv4, IPv6 or a combination.

**Comment by sajattack** [comment]
@kubernetes/sig-aws-feature-requests

**Comment by yastij** [comment]
@pluttrell will submit a PR next week

/assign

**Comment by aanm** [comment]
@yastij How's the PR going?

/area ipv6

**Comment by yastij** [comment]
@aanm - got stuck in other work, I will take a look as soon as I can.

**Comment by chrissound** [comment]
Would this apply to Google GCP as well?

**Comment by craneworks** [comment]
@yastij  What is the state about this PR with the release of 1.9?

**Comment by yastij** [comment]
I'm not following this one anymore, but don't think it made it to 1.9

**Comment by KIVagant** [comment]
Looks like the new related PR is here https://github.com/coreos/alb-ingress-controller/pull/317

**Comment by lareeth** [comment]
That's correct, this will be merged into https://github.com/coreos/alb-ingress-controller but this is a custom ingress controller and not the Kubernetes provided one. If you want to use it, it still requires some work with https://github.com/kubernetes-incubator/external-dns. I will be raising a ticket there to add AAAA support.

**Comment by tambry** [comment]
@pinepain In [this talk](https://youtu.be/qy7zNaDTYGQ?t=24m30s) it's more or less said that you need to ask Amazon support to enable IPv6 on VPC ELBs.
