### ISSUE TITLE
Zero-downtime upgrades of stateful deployments/statefulsets should be possible

### ISSUE THREAD

**Issue by philipn** [kubernetes/kubernetes#49756]
Currently, does not appear possible to provide zero-downtime updates to stateful Deployments or StatefulSets.

For **StatefulSets**, it looks like most users are deploying third-party stateful applications rather than frequently-updated internal applications.  This could explain the lack of functionality here.  How I imagine this could work is:
   * Something akin to `maxUnavailable: 0` could be provided for the StatefulSet.  During a StatefulSet update, new pods would start up and wait until health checks have passed until old pods were terminated.  Additionally, all new pods (e.g. `web-0_new`, `web-1_new`, `web-2_new`) for a given StatefulSet would schedule to the nodes where existing pods are running, so that the underlying volumes wouldn't have to be detached (leading to downtime).

For **Deployments**, some mechanism for allowing pod updates to always schedule to the same nodes, and attach to the same volumes, should be provided.  Currently, a deployment update will schedule pod updates pretty much anywhere, meaning that the deployment will either hang indefinitely with no update (if `maxUnavailable: 0`), or require downtime as volumes must be reattached between nodes.

---
Note that pod label affinity-based scheduling does *not* really work for this use case right now.  If `preferred` scheduling for a label (e.g. `db1`) is specified, then the scheduler may throw the replacement pod elsewhere if it feels like it.  If `required` scheduling is specified, then it is impossible to do the initial deployment of the pods, as they aren't present on any nodes.  So the only available option is to hardcode e.g. the node hostname, which is the same option provided by e.g. local persistent volumes.  Static node specification creates a number of maintenance problems as the cluster changes.

Current workarounds include:

   * Writing (or likely, rewriting) the stateful bits of your application in a multi-master manner.

   * For Deployments, one can take advantage of the multiple-pods-can-RWO-to-PVC behavior of the "bug" described in #26567, set `strategy.rollingUpdate.maxUnavailable: 0` in the Deployment, and then use a custom scheduler, e.g. https://github.com/philipn/kubernetes-sticky-node-scheduler to ensure that all variants of a given pod land on the same node.

   * There appears to be no workaround for StatefulSets.

See also #26567.

---

If other folks are doing zero-downtime updates of stateful applications, I'd love to hear your workarounds / approaches!

----
/kind feature

**Comment by smarterclayton** [comment]
Please describe what you mean by "zero-downtime".  If you have a statefulset of size 2, and do an update, only one stateful set pod should be down at any one time.

**Comment by philipn** [comment]
> On Aug 15, 2017, at 10:29 AM, Clayton Coleman <notifications@github.com> wrote:
> 
> Please describe what you mean by "zero-downtime". If you have a statefulset of size 2, and do an update, only one stateful set pod should be down at any one time.
> 

That statefulset update will result in downtime, unless the application being run does its own replication (e.g. MySQL). This is because each stateful pod is taken down before a replacement stateful pod (attached to the same volume) is brought up.

**Comment by kargakis** [comment]
cc @kow3ns

**Comment by smarterclayton** [comment]
> That statefulset update will result in downtime, unless the application being run does its own replication (e.g. MySQL)

Yes, the design of stateful sets today does not cover "applications that cannot lose any instance".  The design discussions occurring around daemonsets may result in some precedent for that sort of feature in the future (as well as highlighting how that might be achieved while preserving other system guarantees).

**Comment by henriksp** [comment]
Has there been any development on this topic, looking at how to achieve zero-downtime upgrade for stateful services with a RWO PVC?

**Comment by imdmahajankanika** [comment]
Is there any news about how to achieve zero-downtime upgrade for stateful services with a RWO PVC?

**Comment by bryceeller-qz** [comment]
The best way to do this is to run twin stateful-sets, ex: StatefulSetBlue and StatefulSetGreen. When you want to deploy a new version, publish that deployment to the idle color, scale it up, switch over from the active color to the idle one, then scale down the newly idle color
