### ISSUE TITLE
DaemonSet should respect  node status like mem and disk pressure

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#49784]
when we decide if node shoud run daemon pod the ds should respect other node status as stated here in [#L1103](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L1103). @lukaszo @kargakis 

/assign
/sig apps
/area workload-api/daemonset

**Comment by lukaszo** [comment]
cc @davidopp

**Comment by yastij** [comment]
@davidopp @lukaszo also as stated we should move it to the predicates, are you okay with it ?

**Comment by k82cn** [comment]
we are working on tainting node by condition, target is 1.8; so mem and disk presure are covered.

**Comment by yastij** [comment]
@k82cn handing this one to you then

**Comment by k82cn** [comment]
@yastij , the tasks are traced at https://github.com/kubernetes/kubernetes/issues/42001#issuecomment-315987635 ; that'll be great if you can you help to review current PRs :). And then you can other tasks, e.g. Add toleration to DaemonSet.

**Comment by yastij** [comment]
Thanks !

**Comment by yastij** [comment]
@k82cn @gmarek - Since we still support both approaches (tainting by nodeConditions and nodeConditions check) do you think that we have to work on this one ? Or just close it right after #50186 is merged ?

**Comment by yastij** [comment]
ping @k82cn @gmarek

**Comment by gmarek** [comment]
I think in general it shouldn't. Operator can always add those tolerations for daemons for which this is safe, but in principle Daemons might actually require healthy disk.

**Comment by yastij** [comment]
Closed since #50186 is merged
