### ISSUE TITLE
Make it possible to see which items are currently awaiting insert into a rate-limited workqueue

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#49783]
It would be really useful to be able to make an assertion in a test that a particular item was waiting for requeue in a rate-limited workqueue.  This would allow a unit test for a controller method to ensure that the controller had correctly requeued a workitem.

/kind feature
/sig api-machinery

**Comment by mml** [comment]
cc @caesarxuchao 

@pmorie are you planning to do this yourself?

**Comment by pmorie** [comment]
@mml I am definitely not planning on doing it myself, as my attention is on other matters.  I'm happy to review the code someone else writes.
