### ISSUE TITLE
Update pd.go tests to use gce api instead of gcloud commands

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#49796]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig storage

**What happened**:
Offshoot of #49334.  Let's change the tests to use the programmatic API instead of gcloud CLI.

**Comment by davidz627** [comment]
Just confirming that this issue is referring only to the 3 gcloud CLI calls in pd.go?

**Comment by msau42** [comment]
yup

**Comment by davidz627** [comment]
PR: #51809
