### ISSUE TITLE
kubectl: No resources found

### ISSUE THREAD

**Issue by Shashwatsh** [kubernetes/kubernetes#49804]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
i started a simple nginx pod and it doesn't show on kubectl get pods
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```[root@fedora-1gb-blr1-01 ~]# kubectl run my-nginx --image=nginx --replicas=2 --port=80
deployment "my-nginx" created
[root@fedora-1gb-blr1-01 ~]# kubectl get pods
No resources found.
[root@fedora-1gb-blr1-01 ~]# kubectl get deployment
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   2         0         0            0           22s
```

**Anything else we need to know?**:
```
[root@fedora-1gb-blr1-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-08T18:30:56Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-08T18:30:56Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
[root@fedora-1gb-blr1-01 ~]# 
```

```NAME=Fedora
VERSION="26 (Cloud Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Cloud Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Cloud Edition"
VARIANT_ID=cloud
```
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
/sig apps

Note that your deployment desires 2 pods but curent is 0. You should check this. What's the `kubectl describe your deployment`?
```
[root@fedora-1gb-blr1-01 ~]# kubectl get deployment
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   2         0         0            0           22s
```

**Comment by Shashwatsh** [comment]
it shows 
```
[root@fedora-1gb-blr1-01 ~]# kubectl describe deployments my-nginx
Name:			my-nginx
Namespace:		default
CreationTimestamp:	Fri, 28 Jul 2017 17:58:44 +0000
Labels:			run=my-nginx
Annotations:		<none>
Selector:		run=my-nginx
Replicas:		2 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Pod Template:
  Labels:	run=my-nginx
  Containers:
   my-nginx:
    Image:		nginx
    Port:		80/TCP
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
OldReplicaSets:		<none>
NewReplicaSet:		<none>
Events:			<none>
```

**Comment by xiangpengzhao** [comment]
also your deployment yaml/json please

**Comment by Shashwatsh** [comment]
```

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2017-07-28T17:58:44Z
  generation: 1
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "201"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/my-nginx
  uid: 65a5ca68-73be-11e7-b0c8-0e483bf31006
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

**Comment by Shashwatsh** [comment]
Any idea why it's happening?

**Comment by xiangpengzhao** [comment]
seems like ReplicaSet was not created. Can you get anything by `kubectl get rs`?

**Comment by Shashwatsh** [comment]
```
[root@fedora-1gb-blr1-01 ~]# kubectl get rs
NAME                   DESIRED   CURRENT   READY     AGE
my-nginx-858393261     2         0         0         1h
my-nginx2-769133329    2         0         0         1h
nginx-2371676037       1         0         0         1h
nginx-test-659417951   1         0         0         1h
[root@fedora-1gb-blr1-01 ~]# 
```

**Comment by xiangpengzhao** [comment]
`my-nginx-858393261` should be your the associated rs. But note that all other rs don't have pods, either. Can you get pods by other creating ways, e.g. rc?

**Comment by Shashwatsh** [comment]
sorry, i don't get you.

**Comment by Shashwatsh** [comment]
```
[root@fedora-1gb-blr1-01 ~]# nano rep.yaml
[root@fedora-1gb-blr1-01 ~]# kubectl create -f ./rep.yaml
replicationcontroller "nginx" created
[root@fedora-1gb-blr1-01 ~]# kubectl get pods
No resources found.
[root@fedora-1gb-blr1-01 ~]# 
```

**Comment by xiangpengzhao** [comment]
Are there any events in `kubectl describe rc nginx`? I doubt if all of your kube componets are running. Can you check it?

**Comment by Shashwatsh** [comment]
```systemctl status  etcd kube-apiserver kube-controller-manager kube-scheduler kubelet docker kube-proxy``` these ones ^^ are running

**Comment by xiangpengzhao** [comment]
I once encountered the similar issue when my kube-controller-manager was down.

**Comment by Shashwatsh** [comment]
systemctl status kube-controller-manager
● kube-controller-manager.service - Kubernetes Controller Manager
   Loaded: loaded (/usr/lib/systemd/system/kube-controller-manager.service; enabled; vendo
   Active: active (running) since Fri 2017-07-28 23:18:02 UTC; 3h 7min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 14867 (kube-controller)
    Tasks: 6 (limit: 4915)
   Memory: 29.4M
      CPU: 1min 37.097s
   CGroup: /system.slice/kube-controller-manager.service
           └─14867 /usr/bin/kube-controller-manager --logtostderr=true --v=0 --master=http

**Comment by xiangpengzhao** [comment]
Are there any events in `kubectl describe rc nginx`?

**Comment by Shashwatsh** [comment]
Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account

**Comment by Shashwatsh** [comment]
```
[root@fedora-1gb-blr1-01 ~]# kubectl describe rc nginx
Name:		nginx
Namespace:	default
Selector:	app=nginx
Labels:		app=nginx
Annotations:	<none>
Replicas:	0 current / 3 desired
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	app=nginx
  Containers:
   nginx:
    Image:		nginx
    Port:		80/TCP
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  48m		7m		60	replication-controller			Warning		FailedCreate	Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account
[root@fedora-1gb-blr1-01 ~]# 
```

**Comment by Shashwatsh** [comment]
@xiangpengzhao Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account

**Comment by Shashwatsh** [comment]
How do I solve it??

**Comment by xiangpengzhao** [comment]
no idea yet.

/cc @liggitt 

/sig auth

**Comment by Shashwatsh** [comment]
i know how to solve this issue on k8s 1.5 but it doesn't work on 1.6.

**Comment by m-no-2017** [comment]
Did you take into account that from 1.5 > 1.6 there may be RBAC enabled ?  
All the controller functions may rely on roles which need to have the right permissions to set up the pods correctly.  
Could you post your API server file (or startup args)?

**Comment by Shashwatsh** [comment]
[root@fedora-1gb-blr1-01 ~]# cat /etc/kubernetes/apiserver
###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The address on the local server to listen to.
KUBE_API_ADDRESS="--insecure-bind-address=127.0.0.1"

# The port on the local server to listen on.
# KUBE_API_PORT="--port=8080"

# Port minions listen on
# KUBELET_PORT="--kubelet-port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://127.0.0.1:2379,http://127.0.0.1:4001"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"

# Add your own!
KUBE_API_ARGS="--secure-port=0 --service-account-key-file=/etc/kubernetes/service_account.key"

**Comment by m-no-2017** [comment]
So i assume that you just have 1x API server and 1x ETCD node on the same machine.  
Maybe a kubeadm setup?

Just to eliminate the RBAC issues you could enter these commands and restart the deployments:
<pre><code>kubectl create clusterrolebinding free-for-all-serviceaccounts --clusterrole=cluster-admin --group=system:serviceaccounts</code></pre>
<pre><code>kubectl create clusterrolebinding free-for-all-controllers --clusterrole=cluster-admin --group=system:controllers</code></pre>

This is only for testing, since these allow all serviceaccounts and controllers everything in the cluster!

**Comment by Shashwatsh** [comment]
Hi, I ran the commands, but ```kubectl get pods``` still shows ```No resources found```. any ideas?

**Comment by Shashwatsh** [comment]
However, doing a ```kubectl describe rc nginx``` doesn't show any events or errors now

**Comment by Shashwatsh** [comment]
```
[root@fedora-1gb-blr1-01 ~]# kubectl run example --image=nginx
deployment "example" created
[root@fedora-1gb-blr1-01 ~]# kubectl get pods -l run=example
No resources found.
```

**Comment by m-no-2017** [comment]
Something like:
<pre><code>kubectl get pods -o wide --all-namespaces</code></pre>

Doesn't show anything ?

**Comment by tao-zhang** [comment]
I ran into the same issue:
`kubectl get pods` - No resources found.
`kubectl get pods --all-namespaces` that works.

Any idea on this?

**Comment by m-no-2017** [comment]
<pre><code>kubectl get pods</code></pre>
Shows the "default" namespace. If you don't have any workloads running in the default namespace you don't see anything.

Specify a namespace and try it again.  
The standard namespaces are kube-system and default, so try
<pre><code>kubectl -n kube-system get pods
kubectl -n default get pods</code></pre>

PS: the flag "-n" is also shown as "--namespace" in some docs, but it's the same.

**Comment by liggitt** [comment]
you do need to add `--service-account-key-file=/etc/kubernetes/service_account.key` to the API server startup args, but you do not need to set `--secure-port=0`

the rest of the setup for running the token controller looks right to me

**Comment by ucookie** [comment]
i meet the same.
you can try this.
$ cat /etc/kubernetes/apiserver
find the “KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
”
second: delete "ServiceAccount"
finnaly: restart kube-apiserver service

you try "kubectl get pods"

**Comment by latouchek** [comment]
Thx a lot for that @ucookie 
You made my day :)

**Comment by Tushar120120** [comment]
> NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
Do you mean we should change this in /etc/kubernetes/manifests/kube-apiserver.yaml
enable-admission-plugins=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,Resourc
eQuota

**Comment by git006** [comment]
> i meet the same.
> you can try this.
> $ cat /etc/kubernetes/apiserver
> find the “KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
> ”
> second: delete "ServiceAccount"
> finnaly: restart kube-apiserver service
> 
> you try "kubectl get pods"

用kubectl -n kube-system get pods可以看到pods. 但是没有这个文件/etc/kubernetes/apiserver

**Comment by Vaishalinicky** [comment]
apiserver is not there 

[root@k8snode2 kubernetes]# ls
admin.conf  controller-manager.conf  kubelet.conf  manifests  pki  scheduler.conf
[root@k8snode2 kubernetes]#

under manifest i have below details

[root@k8snode2 manifests]# ls -ltr
total 16
-rw-------. 1 root root 1384 Jan 10 10:59 kube-scheduler.yaml
-rw-------. 1 root root 2798 Jan 10 10:59 kube-controller-manager.yaml
-rw-------. 1 root root 3276 Jan 10 10:59 kube-apiserver.yaml
-rw-------. 1 root root 2181 Jan 10 10:59 etcd.yaml
[root@k8snode2 manifests]#

under file kube-apiserver.yaml

[root@k8snode2 manifests]# more kube-apiserver.yaml | grep -i "admission"
    - --enable-admission-plugins=NodeRestriction
[root@k8snode2 manifests]#

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.0xx.x:xxxx
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.0.x.x
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.x.x.x:2333
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-




can someone guide me what i can change to resolve issue ?

[root@k8snode2 manifests]# kubectl get pod
No resources found in default namespace.

**Comment by Vaishalinicky** [comment]
> > NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
> > Do you mean we should change this in /etc/kubernetes/manifests/kube-apiserver.yaml
> > enable-admission-plugins=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,Resourc
> > eQuota

@Tushar120120 

Is that solution worked for you??

**Comment by fdiasmor** [comment]
@Vaishalinicky Have you found a solution for that? 
I am running into exactly the same issue.

**Comment by yuangu** [comment]
I also encountered this problem，But I restarted the operating system and all is ok.

**Comment by LEENAK10** [comment]
> apiserver is not there
> 
> [root@k8snode2 kubernetes]# ls admin.conf controller-manager.conf kubelet.conf manifests pki scheduler.conf [root@k8snode2 kubernetes]#
> 
> under manifest i have below details
> 
> [root@k8snode2 manifests]# ls -ltr total 16 -rw-------. 1 root root 1384 Jan 10 10:59 kube-scheduler.yaml -rw-------. 1 root root 2798 Jan 10 10:59 kube-controller-manager.yaml -rw-------. 1 root root 3276 Jan 10 10:59 kube-apiserver.yaml -rw-------. 1 root root 2181 Jan 10 10:59 etcd.yaml [root@k8snode2 manifests]#
> 
> under file kube-apiserver.yaml
> 
> [root@k8snode2 manifests]# more kube-apiserver.yaml | grep -i "admission" - --enable-admission-plugins=NodeRestriction [root@k8snode2 manifests]#
> 
> apiVersion: v1 kind: Pod metadata: annotations: kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.0xx.x:xxxx creationTimestamp: null labels: component: kube-apiserver tier: control-plane name: kube-apiserver namespace: kube-system spec: containers:
> 
> * command:
>   
>   * kube-apiserver
>   * --advertise-address=10.0.x.x
>   * --allow-privileged=true
>   * --authorization-mode=Node,RBAC
>   * --client-ca-file=/etc/kubernetes/pki/ca.crt
>   * --enable-admission-plugins=NodeRestriction
>   * --enable-bootstrap-token-auth=true
>   * --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
>   * --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
>   * --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
>   * --etcd-servers=https://127.x.x.x:2333
>   * --insecure-port=0
>   * --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
>   * --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
>   * --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
>   * --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
>   * --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
>   * --requestheader-allowed-names=front-proxy-client
>   * --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
>   * --requestheader-extra-headers-prefix=X-
> 
> can someone guide me what i can change to resolve issue ?
> 
> [root@k8snode2 manifests]# kubectl get pod No resources found in default namespace.

Hi Vaishali, i encountered same error and unable to locate api server file, have u succeded with it, how you resolved it
