### ISSUE TITLE
Support Local Storage as one Quota Resource

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#49818]
We plan to add local storage in the quota resource management.

For quota resource like CPU and memory, the quota resource and request/limit is one to one mapping. But local storage is different. The scratch space is node-level resource that could be used by both pod level emptyDir volume and/or container's overlay (depending whether there is one root partition or a separate imagefs partition). So it might cause confusion when we set quota on local storage scratch space. Should it  include emptyDir volume or also container's overlay? Do admins want fine grain control over emptyDir and container overlay on Quota or they only care about total local storage usage and set one quota for it? Based on the questions, here are two options.

1. Give admin fine-grain control with separate quota resource for emptyDir and container overlay
There will be two types of resources
ResourceRequestsStorageOverlay  ResourceLimitsStorageOverlay
ResourceRequestsEmptyDir           ResourcelimitsEmptyDir (since EmptyDir only allows to set LimitSize, these two values are equal) 

Admin can set one or both of the quota resources. Quota evaluator will validate whether resource limit/request is set for the quota resource and whether the value satisfies the requirement.

- Pros: EmptyDir volume and container overlay have a separate quota resource, it is easier to understand and set up for two shared partition case because emptyDir and container overlay will consume storage from different partitions. 
- Cons: Admin has more (sometimes unnecessary) configuration parameters to adjust. For the case of only one partition, admin has to figure out how much quota assigned for EmptyDir and how much quota for container overlay which might be difficult to decide.

2. Give admin only one quota resource for local storage
ResourceRequestsStorageScratch ResourceLimitsStorageScratch
Quota evaluator will validate whether resource limit/request is set for either emptyDir and (or) container’s overlay (Should we require both of them to be set or only one of them is fine?). 

- Pros: It is easier to set up for one root  partition case. Admin just sets the quota for total local storage use, and evaluator will add emptyDir and container’s overlay together for quota validation  
- Cons: It is not very clear for admin how to set up for two partitions case. Use the following as an example. 
- There are two partitions, root partition has 10GB and second partition has also 10GB. EmptyDir volume size limit is 12, and container’s overlay request 3. This case, quota evaluation could pass however, emptyDir actually requests more than the quota capacity.

Please share your feedback and comments. Thanks!

**Comment by jingxu97** [comment]
cc @k8s-mirror-storage-feature-requests @k8s-mirror-storage-misc @k8s-mirror-storage-proposals

**Comment by NickrenREN** [comment]
In favor of option 1, two separate quota resources(scratch,overlay) may be easier to undertand and will not cause the problem mentioned in option2

> There are two partitions, root partition has 10GB and second partition has also 10GB. EmptyDir volume size limit is 12, and container’s overlay request 3. This case, quota evaluation could pass however, emptyDir actually requests more than the quota capacity.

**Comment by ddysher** [comment]
This is a problem we can't solve unless we have different types of resource quota, or unless we do differently for different partition setup.  Admin can always change resource quota if needed, so option1 sounds like the way to go.
> There are two partitions, root partition has 10GB and second partition has also 10GB. EmptyDir volume size limit is 12, and container’s overlay request 3. This case, quota evaluation could pass however, emptyDir actually requests more than the quota capacity.

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage-misc

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling-feature-requests 
@derekwaynecarr

**Comment by jingxu97** [comment]
To reduce the confusion and complexity caused by multiple storage APIs design, we plan to only have one storage API to represent scratch space and only manage root partition ephemeral storage isolation. The main reasons include
- We want to support both overlay and scratch storage API and isolation mainly because the use case of devicemapper. However, it is not a common use case and it is hard to  expose per container overlay storage requests
- From the discussion in the above sections, we can see the hard design issues and confusion caused by the multiple storage APIs. By supporting only one time, the design of storage isolation can be more consistent with the memory management.

After changing to only support one type of ephemeral storage API, we will need to modify the following design
- Each container can only specify its scratch space request and limit. The total request/limit across all containers create a pod-level boundary of local ephemeral storage isolation
- EmptyDir sizeLimit: if this value is not set, emptyDir volume storage usage is also limited by the total limit across all containers (pod-level boundary). If sizeLimit is set, the emptyDir storage usage is also bounded by its own limit.
- Only need to support one storage quota and limitRange for containers’ storage request/limits.

**Comment by jingxu97** [comment]
As explained above, we now only support on ephemeral storage type. So close this issue
