### ISSUE TITLE
fluentd-elasticsearch addon broken with latest commit

### ISSUE THREAD

**Issue by mkjpryor-stfc** [kubernetes/kubernetes#49816]
/kind bug

**What happened**:

After updating the elasticsearch container in the fluentd-elasticsearch addon to use version 5.4.0-1, the following error occurs:

```
kubectl -n monitoring logs elasticsearch-logging-713280597-2l0ct
sysctl: error setting key 'vm.max_map_count': Read-only file system
```

I believe this is caused by [this line](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-image/run.sh#L17), which was introduced in the latest commit. It appears that this happens because /sys is mounted read-only in containers. However, it does seem to be important to running elasticsearch (see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html).

**What you expected to happen**:

Elasticsearch to start normally.

**How to reproduce it (as minimally and precisely as possible)**:

Modify the container version in https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-controller.yaml to be 5.4.0-1 and install the addon.

**Environment**:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Issue occurs on Kubernetes running on Ubuntu Xenial VirtualBox VMs.

**Comment by crassirostris** [comment]
@mkjpryor-stfc Thanks! It's a known problem, we're trying to mitigate it in https://github.com/kubernetes/kubernetes/pull/48722

It's going to be fixed soon

**Comment by mkjpryor-stfc** [comment]
@crassirostris Thanks for the info. The PR looks like a decent approach. I'm pleased to see the addon being modified to use upstream base images, as I was thinking of doing that!
