### ISSUE TITLE
api-reference docs don't contain types from staging repos

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#49811]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**: 

The 1.7 api reference docs at https://kubernetes.io/docs/api-reference/v1.7/ don't contain types from groups present in staging (like `apiextensions` - https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiextensions-apiserver).

**What you expected to happen**:

Types from groups in staging repos should be present in the api reference docs.

**How to reproduce it (as minimally and precisely as possible)**:

Visit https://kubernetes.io/docs/api-reference/v1.7/.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @sttts

**Comment by nikhita** [comment]
Update: They are not present in the 1.8 api reference docs too.

**Comment by sttts** [comment]
Is this fixed in 1.8? https://kubernetes.io/docs/api-reference/v1.8/#customresourcedefinition-v1beta1-apiextensions looks good, doesn't it?

**Comment by nikhita** [comment]
> Is this fixed in 1.8? https://kubernetes.io/docs/api-reference/v1.8/#customresourcedefinition-v1beta1-apiextensions looks good, doesn't it?

Yes! Closing.
