### ISSUE TITLE
Support a Vault based KMS provider for envelope encryption of resources in a cluster

### ISSUE THREAD

**Issue by kksriram** [kubernetes/kubernetes#49817]
Resources (not just secrets) in a Kubernetes cluster can be encrypted using an envelope encryption scheme with the DEK being encrypted with a KEK that is managed in Vault. 

Add support for using Hashicorp Vault as a KMS provider to manage KEKs. 

Would address several concerns discussed in the issues referenced: 

*  Reuse Vault already in use in an enterprise to additionall manage KEKs for K8S clusters. 
*  KEK is externalized and managed in the KMS provider, adding to the security of the overall deployment. 
*  Separate cluster mangement responsibilities from key management/administration, better reflecting Ops, SecOps separations.  

[Design Proposal](https://docs.google.com/document/d/15-baW4i7qws1yxxIYjHXqKpk259ebauQbECQCpPD308/edit#). Discussed at [sig-auth July 26](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#heading=h.ucn6b5acqauf).  

Alpha release Target 1.8 ?  

Relies on support added via PRs

* https://github.com/kubernetes/kubernetes/pull/41939 for transformers
* https://github.com/kubernetes/kubernetes/pull/49350 for envelope encryption transformers
* Config support added in https://github.com/kubernetes/kubernetes/pull/46460 and https://github.com/kubernetes/kubernetes/pull/48574

## Roadmap
* [A Plan for Kubernetes Secrets](https://docs.google.com/document/d/1JAwPuZg47UhfRVlof-lMw08OJztunW8pvTNxDK3rCF8/edit#heading=h.vw9xyk1ib8nn)
* https://github.com/kubernetes/community/pull/607

## Related Issues  
* https://github.com/kubernetes/features/issues/92 
* https://github.com/kubernetes/kubernetes/issues/12742
* https://github.com/kubernetes/kubernetes/issues/28538
* https://github.com/kubernetes/kubernetes/issues/10439
* https://github.com/kubernetes/kubernetes/issues/48522

/kind feature

@kubernetes/sig-auth

/sig auth

/assign @vineet-garg

**Comment by kksriram** [comment]
@kubernetes/sig-auth

**Comment by sakshamsharma** [comment]
Closely related changes, how to integrate KMS: #49742

**Comment by kksriram** [comment]
Proposal PR : https://github.com/kubernetes/community/pull/888

**Comment by ericchiang** [comment]
@kubernetes/sig-auth-feature-requests going to move this to the 1.9 milestone per our SIG auth meeting.

**Comment by luxas** [comment]
This is part of beta graduation requirements in that case #51965
I'd be a bit hesitant to add many more providers... See the discussion in #48574

**Comment by deads2k** [comment]
> This is part of beta graduation requirements in that case #51965
> I'd be a bit hesitant to add many more providers... See the discussion in #48574

We spoke in sig-auth and sig-apimachinery.  We'll be adding this as another example of building a KMS plugin to gain more experience with the API.  After we have those two examples, we'll be more competent to shape an external API that is likely to work.

**Comment by kksriram** [comment]
@deads2k @ericchiang @liggitt Need your help setting the milestones label, please. I don't have privileges.

**Comment by dims** [comment]
@kksriram will this make 1.9? (am usually help with bug triage etc before releases in case you are wondering why :)

**Comment by kksriram** [comment]
@dims considering the change in direction to out of tree in https://github.com/kubernetes/kubernetes/pull/55684 I don't expect this will make 1.9.

**Comment by mfilotto** [comment]
@kksriram do you think it will be ready for 1.10 ?

**Comment by kksriram** [comment]
@mfilotto Not sure. The approach proposed for this issue assumed an in-tree provider. The agreement at sig-auth and sig-api-machinery at the end of 1.9 was to have all future KMS providers be out-of-tree. We're working on implementing that for 1.10 via #51965 and the corresponding implementation in #55684 . With that direction, we are discussing a couple of ways forward for this issue

- Revise this proposal so it becomes an out-of-tree provider for Vault. 
- separately build a Vault provider implementation for #55684. That likely, will live in some other Git repo and will definitely not be in kubernetes/kubernetes. 

Will keep this updated as we discuss and decide. I'll update next week if this will not make 1.10.

**Comment by jberkus** [comment]
@kksriram will this make 1.10?  if so, please approve-for-milestone, otherwise please bump it to 1.11.  Thanks!

**Comment by deads2k** [comment]
Since we merged the grpc kms provider, I think this can be closed.

**Comment by kksriram** [comment]
@deads2k beat me to it. I meant to close this because I don't think this will ship as part of Kubernetes. Given the support added via #51965 and the corresponding PR #55684, we will work offline to figure out how best to release the Vault KMS provider that implements the gRPC interface in #55684.

**Comment by alonbl** [comment]
Hi,
Anyone knows if there is a standalone KMS plugin for HashiCorp Vault?
I see there is for GCP and Azure, but I cannot find vault.
Thanks!

**Comment by dims** [comment]
@alonbl looks like @kksriram has an implementation here - https://github.com/oracle/kubernetes/pull/4

**Comment by alonbl** [comment]
@dims it looks like this is not a standalone module, but the old implementation of merging into k8s codebase.

**Comment by kksriram** [comment]
@alonbi
We expect to release a standalone version in a couple of weeks

**Comment by alonbl** [comment]
@kksriram thanks! if possible please paste here the URL of the repo :)

**Comment by mfilotto** [comment]
Awesome @kksriram, looking forward to see this coming.

**Comment by ssboisen** [comment]
Hi @kksriram any progress on making the vault KMS plugin standalone? Thanks for working on this!

**Comment by kksriram** [comment]
We should have something next week. Will update here with a link

**Comment by kksriram** [comment]
Kubernetes KMS plugin for HashiCorp Vault : https://github.com/oracle/kubernetes-vault-kms-plugin
