### ISSUE TITLE
Migrate scalability jobs to prow and off centralized jenkins before end of 1.9 timeframe

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#49820]
The GKE engprod team will stop supporting sigs running their testing on shared jenkins infrastructure after 1.8

Please migrate your jobs to prow. If this is infeasible for some reason please let sig-testing know what we need to add to prow and/or plan to create and maintain your own jenkins instance if we cannot come up with a solution kubernetes/test-infra#3778

This impacts the following jobs:
```
  "ci-kubernetes-e2e-gce-large-correctness": {
  "ci-kubernetes-e2e-gce-large-performance": {
  "ci-kubernetes-e2e-gce-scalability": {
  "ci-kubernetes-e2e-gce-scalability-release-1-6": {
  "ci-kubernetes-e2e-gce-scalability-release-1-7": {
  "ci-kubernetes-e2e-gce-scale-correctness": {
  "ci-kubernetes-e2e-gce-scale-performance": {
  "ci-kubernetes-e2e-gci-gce-scalability": {
  "ci-kubernetes-e2e-gci-gce-scalability-release-1-6": {
  "ci-kubernetes-e2e-gci-gce-scalability-release-1-7": {
  "ci-kubernetes-e2e-gke-large-correctness": {
  "ci-kubernetes-e2e-gke-large-deploy": {
  "ci-kubernetes-e2e-gke-large-performance": {
  "ci-kubernetes-e2e-gke-large-teardown": {
  "ci-kubernetes-e2e-gke-scale-correctness": {
  "ci-kubernetes-kubemark-100-gce": {
  "ci-kubernetes-kubemark-5-gce": {
  "ci-kubernetes-kubemark-5-gce-1.5": {
  "ci-kubernetes-kubemark-500-gce": {
  "ci-kubernetes-kubemark-gce-scale": {
  "ci-kubernetes-kubemark-high-density-100-gce": {
  "ci-perf-tests-kubemark-100-benchmark": {
  "pull-kubernetes-kubemark-e2e-gce": {
  "pull-kubernetes-kubemark-e2e-gce-gci": {
```

https://github.com/kubernetes/test-infra/issues/3774
@kubernetes/sig-scalability-bugs

**Comment by spiffxp** [comment]
/assign @shyamjvs @gmarek 
Ping.  I'm assigning you two based on activity related to the scale tests last release cycle.  Please re-assign to someone who has bandwidth to work on this if not you.

**Comment by shyamjvs** [comment]
@krzyzacy Is working towards this at lightening speed. We'll co-own this issue.

**Comment by krzyzacy** [comment]
update:
- cron trigger is working in prow
- start to migrate over scalability jobs, and gonna grant necessary permission for manual trigger jobs in prow
- still need to sort out kubemark jobs, but worst case we can shovel that into prow dind, and looking at the bazel image later

**Comment by shyamjvs** [comment]
Here's a check-list of our scalability jobs (let's mark them as we go):

[ ]  ci-kubernetes-e2e-gce-large-correctness
[ ] ci-kubernetes-e2e-gce-large-manual-down
[ ] ci-kubernetes-e2e-gce-large-manual-up
[ ]  ci-kubernetes-e2e-gce-large-performance
[ ] ci-kubernetes-e2e-gce-scalability-release-1-7
[ ] ci-kubernetes-e2e-gce-scale-correctness
[ ] ci-kubernetes-e2e-gce-scale-performance
[ ] ci-kubernetes-e2e-gci-gce-scalability
[ ] ci-kubernetes-e2e-gci-gce-scalability-release-1-7
[ ] ci-kubernetes-e2e-gci-gce-scalability-stable1
[ ] ci-kubernetes-e2e-gke-large-correctness
[ ] ci-kubernetes-e2e-gke-large-deploy
[ ] ci-kubernetes-e2e-gke-large-performance
[ ] ci-kubernetes-e2e-gke-large-teardown
[ ] ci-kubernetes-e2e-gke-scale-correctness
[ ] ci-kubernetes-kubemark-100-gce
[ ] ci-kubernetes-kubemark-5-gce
[ ] ci-kubernetes-kubemark-5-gce-last-release
[x] ci-kubernetes-kubemark-5-prow-canary
[ ] ci-kubernetes-kubemark-500-gce
[ ] ci-kubernetes-kubemark-gce-scale
[ ] ci-kubernetes-kubemark-high-density-100-gce
[ ] pull-kubernetes-kubemark-e2e-gce
[ ] pull-kubernetes-kubemark-e2e-gce-big

**Comment by shyamjvs** [comment]
Seems like the initial move (https://github.com/kubernetes/test-infra/pull/5515) worked fine. However, note that the timezone has been shifted probably because prow cluster and jenkins are in different ones. For 100-node jobs it's probably fine, but for large scale jobs we need to shift the cron string to ensure original times continue to be followed.

**Comment by shyamjvs** [comment]
Next I think we can move all our large-scale manual jobs (gce-large-manual-up/down, gke-large-deploy/teardown). However, for that we need to support manual jobs on prow.
Since I don't think cron supports such a thing, what we can instead do is not use cron, but instead specify a very very long 'interval' for the job.

@krzyzacy WDYT about it? Could it lead to the job running once initially though?

**Comment by krzyzacy** [comment]
@shyamjvs Interval will not work, as we clean up pods older than 2days, which means after 2 days prow will think that the pod never runs thus will trigger another run.

Instead we probably should use some very long cron, people have suggested use cron in the past, but seems our cron version cannot specify years? I'll play around with it locally.

**Comment by shyamjvs** [comment]
> people have suggested use cron in the past, but seems our cron version cannot specify years?

Yes, I don't see how the cron syntax we're using can represent anything that's not periodic. The maximum time period I could come up with using a crontab was 1 year - using `0 0 1 1 *` (ref - http://cron.schlitt.info/index.php?cron=0+0+1+1+*&iterations=10&test=Test). I tried to make it 7 years (on avg) by even setting the day of the week, i.e sth like `0 0 1 1 7`, but that seems to increase the count (as 'day of the week' and 'day of the month & month of the year' seem to be used with an OR condition instead of an AND).

Can't you just allow a special string in your cron implementation to neglect such jobs?

**Comment by krzyzacy** [comment]
aha, we can use something like `0 0 31 2 0` to schedule the job on Feb. 31st!

**Comment by shyamjvs** [comment]
I guess you mean `0 0 31 2 *` (because otherwise the OR condition I mentioned above kicks in).
That sounds like a cool solution, just found it here - https://stackoverflow.com/a/13938155

**Comment by krzyzacy** [comment]
yep, sgtm, gonna PR it out :-)

**Comment by shyamjvs** [comment]
Ok.. So we've moved all the non-kubemark jobs to prow successfully!
Let's move the kubemark ones now. Guess we chose the D-in-D approach for those.

cc @krzyzacy @BenTheElder

**Comment by krzyzacy** [comment]
on the side note, I'm pretty sure the bazel built image should be fine since the real flake comes from https://github.com/kubernetes/test-infra/pull/5821#issue-279485550. I'll canary bazel image again after the Jenkins migration.

**Comment by krzyzacy** [comment]
/close
all kubemark & scalability jobs are in prow now :-)

**Comment by shyamjvs** [comment]
Ok.. seems like we've migrated all our kubemark jobs with the above PRs. With that, all scale jobs are on prow now. Thanks for the effort Seen.

**Comment by shyamjvs** [comment]
*Sen
Seems like a race.
Also, let's keep a watch on how these jobs go (especially the kubemark-5000 one which is more sensitive for failures).

**Comment by shyamjvs** [comment]
cc @wasylkowski @porridge
