### ISSUE TITLE
Cannot restart kube-apiserver

### ISSUE THREAD

**Issue by Shashwatsh** [kubernetes/kubernetes#49838]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

**What happened**:
```
[root@fedora-1gb-blr1-01 ~]# cat /etc/kubernetes/apiserver
###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The address on the local server to listen to.
KUBE_API_ADDRESS="--insecure-bind-address=127.0.0.1"

# The port on the local server to listen on.
# KUBE_API_PORT="--port=8080"

# Port minions listen on
# KUBELET_PORT="--kubelet-port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://127.0.0.1:2379,http://127.0.0.1:4001"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"

# Add your own!
KUBE_API_ARGS="--secure-port=0 --service-account-key-file=/etc/kubernetes/service_account.key"

[root@fedora-1gb-blr1-01 ~]# service kube-apiserver restart
Redirecting to /bin/systemctl restart kube-apiserver.service
Job for kube-apiserver.service failed because the control process exited with error code.
See "systemctl  status kube-apiserver.service" and "journalctl  -xe" for details.
```
**What you expected to happen**:
goal is to start kube-apiserver with service account API token
**How to reproduce it (as minimally and precisely as possible)**:
mentioned above

**Anything else we need to know?**:
kubernetes version is 1.6
OS is fedora 26

Linux fedora-1gb-blr1-01.localdomain 4.11.8-300.fc26.x86_64 #1 SMP Thu Jun 29 20:09:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mkumatag** [comment]
can you paste the out of those suggested commands : `systemctl  status kube-apiserver.service` and `journalctl  -xe`

**Comment by Shashwatsh** [comment]
systemctl status kube-apiserver.service 
```
[root@fedora-1gb-blr1-01 ~]# systemctl status kube-apiserver.service
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: failed (Result: protocol) since Sat 2017-07-29 15:59:35 UTC; 3h 39min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 18738 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_AP
 Main PID: 18738 (code=exited, status=1/FAILURE)
      CPU: 165ms

Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=1/FAIL
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Unit entered failed state.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Failed with result 'protocol'.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Service hold-off time over, scheduling restart.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: Stopped Kubernetes API Server.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Start request repeated too quickly.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Unit entered failed state.
Jul 29 15:59:35 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Failed with result 'protocol'.
lines 1-18/18 (END)
```
journalctl -xe
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.104841   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain audit: NETFILTER_CFG table=nat family=2 entries=40
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain audit: NETFILTER_CFG table=nat family=2 entries=40
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain audit: NETFILTER_CFG table=nat family=2 entries=40
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.444255   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:12.554330    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.555380   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.556178   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:12.556877    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.557474   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:12.676242   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:12 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:12.973621    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:13.045077    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:13.045988    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.056895   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.103721   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.105418   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.106502   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.445408   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:13.555325    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.556453   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:13.557313    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.557967   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.559062   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.677032   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:13.955312   18743 leaderelection.go:229] error r
Jul 29 19:40:13 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:13.974960    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:14.046461    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kubelet[2986]: E0729 19:40:14.047274    2986 reflector.go:190] k8s.io/kubernetes/pk
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.057629   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.104425   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.105935   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.106934   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.447063   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:14.556409    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.557625   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-proxy[2825]: E0729 19:40:14.558401    2825 reflector.go:201] k8s.io/kubernetes
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.559127   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.559408   18743 reflector.go:201] k8s.io/kuber
Jul 29 19:40:14 fedora-1gb-blr1-01.localdomain kube-scheduler[18743]: E0729 19:40:14.678096   18743 reflector.go:201] k8s.io/kuber

**Comment by Shashwatsh** [comment]
Any idea?

**Comment by mkumatag** [comment]
I see `journalctl -xe` output is truncated. Can you please redirect the output to some file like `journalctl -xe > failures.txt` and upload to gist and paste the link here!

**Comment by Shashwatsh** [comment]
@mkumatag https://gist.github.com/Shashwatsh/18d8bede16327f7e8717ff6f1d9ea08a

**Comment by clenimar** [comment]
most of the logs are other components complaining because API server is off. try `journalctl -fu kube-apiserver > failures.txt` for a better output.

**Comment by Shashwatsh** [comment]
```
-- Logs begin at Sun 2017-07-30 15:40:23 UTC. --
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=1/FAILURE
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Unit entered failed state.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Failed with result 'protocol'.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Service hold-off time over, scheduling restart.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: Stopped Kubernetes API Server.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Start request repeated too quickly.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: Failed to start Kubernetes API Server.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Unit entered failed state.
Jul 30 22:27:34 fedora-1gb-blr1-01.localdomain systemd[1]: kube-apiserver.service: Failed with result 'protocol'.
```

**Comment by Shashwatsh** [comment]
it works perfectly without service account in apiserver config but i need service accounts

**Comment by mkumatag** [comment]
No activities since 5months
/close
