### ISSUE TITLE
kubectl: must warn about the --labels option overwriting other --labels options

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#49854]
If you run a command like:

    $ kubectl run --image=nginx --labels app=web --labels env=prod web

It only uses the latest declaration of `--labels` and drops the earlier `--labels` options specified. Especially because the --help documentation on `--labels` does not specify the format, this is impairing the user experience.

I looked around a few other CLIs to see how they handle this.

- curl, for example, uses `-H` to additively collect headers (instead of a comma-separated list), therefore each value specified is used.
- "docker run" command ignores the earlier --name argument when you specify another one.

I am wondering if we can easily detect non-additive/overwriting args specified multiple times in an invocation.

/kind bug
/sig cli

**Comment by xingzhou** [comment]
I think this is reasonable for improving cli tool user experience. For different commands, it may different in the options, but for each of them we can add warning messages at least for the end user to realize what had happened in the backend, especially for the ignored staff

**Comment by zjj2wry** [comment]
why use `string` for `label` flag instead of `slice`?
