### ISSUE TITLE
kube-proxy conntrack hash resize kernel panic with PREEMPT kernel.

### ISSUE THREAD

**Issue by danisla** [kubernetes/kubernetes#49852]
Running a kernel with `CONFIG_PREEMPT=y` causes kernel panic when running `kube-proxy` unless `--conntrack-max-per-core=0` is passed. [Kernel stack trace here](https://gist.github.com/danisla/b002610edf9b9687a492b8d99a6edaf4#file-dump-txt-L17).

** Background ** 

Preemptive and real-time kernels do not support spinlocks and the current implementation of the kernel conntrack_hash_resize function [uses a spinlock](https://github.com/torvalds/linux/blob/v4.10/net/netfilter/nf_conntrack_core.c#L1755) to perform the resize. When [kube-proxy attempts to set the hashsize](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/conntrack.go#L84) on a system with a preemptive kernel, the kernel panics and entire node crashes. 

** Possible workarounds/solutions **

1. Pass `--conntrack-max-per-core=0` to kube-proxy so that it doesn't modify the hashsize. This can be problematic when running on environments like GKE where I just want to swap the instance template with an image containing the PREEMPT kernel.

2.  [Patch the kernel](https://gist.github.com/danisla/be3c3ebb1d939139cdf426ee88d78f56) to prevent resizing when using `CONFIG_PREEMPT`. Hack.

3. Add some logic to kube-proxy to detect PREEMPT kernel and skip modification of the hashsize.

I'm mostly in favor of option 3 since it doesn't involve hacking the kernel and it would be a drop-in fix for existing K8S deployments.

I am also curious what the scaling consequences may be when the hashsize cannot be set appropriately. It's worth noting that the default hashsize with the preemptive kernel is only 16384 and I'm not sure how far I can scale with that value.

/kind bug
/sig network

**Comment by feiskyer** [comment]
cc/ @kubernetes/sig-network-bugs

**Comment by thockin** [comment]
Not setting conntrack size is going to result in very bad failure modes unless all the nodes are very small.  The default simply is not sufficient in practice.

The kernel needs to be fixed.

**Comment by cmluciano** [comment]
So should the fix be similar to our ```iptables -w``` skip, or do we want to set this value statically from kube-proxy?

**Comment by danisla** [comment]
Fixing this in the kernel is probably the best way to go since modifying the conntrack size is crucial to cluster operation. 

I was able to successfully patch the kernel with the patch below to run with CONFIG_PREEMPT=y without kube-proxy crashing the node.

https://patchwork.kernel.org/patch/8034121/raw/

**Comment by guanyuding** [comment]
https://patchwork.kernel.org/patch/8034121/raw/ has not found. could you please apply for another one?  @danisla
