### ISSUE TITLE
Unable to get node info in Kubelet: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#49864]
Hi,
   I am trying to set up k8s cluster on azure stack and I found k8s master could not start up because kubelet could not connect to azure stack management portal successfully. The certificate of https://management.local.azurestack.external is self signed and kubelet could not recognize that cert.
Question is how could I workaround this? I tried to import azure stack cert to the master Ubuntu VM and restart kubelet, it does not work. Any help is appreciated, thanks.

Below are the logs:
E0731 07:42:27.441625   10740 kubelet.go:1318] Kubelet failed to get node info: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.local.azurestack.external/subscriptions/a3368291-e427-41b0-b790-66b7be21017b/resourceGroups/andyazurestack/providers/Microsoft.Compute/virtualMachines/k8s-master-13534591-0?api-version=2016-03-30: x509: certificate signed by unknown authority
I0731 07:42:27.441718   10740 status_manager.go:140] Starting to sync pod status with apiserver
I0731 07:42:27.441737   10740 kubelet.go:1809] Starting kubelet main sync loop.
I0731 07:42:27.441763   10740 kubelet.go:1820] skipping pod synchronization - [Kubelet failed to get node info: failed to get external ID from cloud provider: compute.VirtualMachinesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.local.azurestack.external/subscriptions/a3368291-e427-41b0-b790-66b7be21017b/resourceGroups/andyazurestack/providers/Microsoft.Compute/virtualMachines/k8s-master-13534591-0?api-version=2016-03-30: x509: certificate signed by unknown authority container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]

**Comment by dixudx** [comment]
/sig azure

@andyzhangx What's in your kubelet `--cloud-config`.

In the config file, there is a `aadClientCertPath`, which is the path of a client certificate for an AAD application with RBAC access to talk to Azure RM APIs.

**Comment by andyzhangx** [comment]
@dixudx Current issue is cert of https://management.local.azurestack.external is not recognized.
Below are all the parameters:
/hyperkube apiserver --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --address=0.0.0.0 --allow-privileged --insecure-port=8080 --secure-port=443 --cloud-provider=azure --cloud-config=/etc/kubernetes/azure.json --service-cluster-ip-range=10.0.0.0/16 --etcd-servers=http://127.0.0.1:2379 --etcd-quorum-read=true --advertise-address=10.240.255.15 --tls-cert-file=/etc/kubernetes/certs/apiserver.crt --tls-private-key-file=/etc/kubernetes/certs/apiserver.key --client-ca-file=/etc/kubernetes/certs/ca.crt --service-account-key-file=/etc/kubernetes/certs/apiserver.key --storage-backend=etcd2

**Comment by dixudx** [comment]
@andyzhangx What's in your `/etc/kubernetes/azure.json`? Have you tried to add `aadClientCertPath`?

**Comment by andyzhangx** [comment]
@dixudx From the azure.json, it's using aadClientId and aadClientSecret to create ServicePrincipalToken, so shall I switch to use AADClientCertPath and AADClientCertPassword ? I only got a azure stack cert file, what value should I set for AADClientCertPassword?

{
    "cloud":"AzureStack",
    "tenantId": "5454420b-2e38-4b9e-8b56-1712d321cf33",
    "subscriptionId": "***",
    "aadClientId": "cec6fd33-bbcc-45e6-ba12-33af06fa73de",
    "aadClientSecret": "***“”
    "resourceGroup": "andyazurestack",
    "location": "local",
    "subnetName": "k8s-subnet",
    "securityGroupName": "k8s-master-13534591-nsg",
    "vnetName": "k8s-vnet-13534591",
    "routeTableName": "k8s-master-13534591-routetable",
    "primaryAvailabilitySetName": "agentpool1-availabilitySet-13534591"
}

And I have used azure-cli for azure stack, if I export the azure stack cert file to python cert store, azure-cli works well for azure stack. So my question is where could I put the cert file to k8s, so that kubelet could recognize https://management.local.azurestack.external? Thanks for the help.

**Comment by seanknox** [comment]
@andyzhangx how did you provision the cluster on azure stack?

**Comment by andyzhangx** [comment]
Hi @seanknox , I am using a modified acs-engine (https://github.com/andyzhangx/acs-engine/tree/andy-azurestack), trying to run k8s on azure stack, it's now stuck on cert issue.

**Comment by seanknox** [comment]
I'm pretty sure this is acs-engine issue, not a Kubernetes issue, and should probably be dealt with on the [acs-engine issues page](https://github.com/Azure/acs-engine/issues). We've worked a bit with Azure Stack folks to provision Kubernetes via acs-engine but last I recall we're blocked on the network configuration needed on AS.

**Comment by andyzhangx** [comment]
Hi @seanknox,  I have tried that if I add the self signed azure stack cert into the hyperkube container, there is no this error. So my question is, is there any way to add the cert into Ubuntu OS of hyperkube image in advance? k8s should have such exception way to add self signed cert, thanks.

**Comment by feiskyer** [comment]
@andyzhangx the certs could be attached when running containers with hostPath mounts.

**Comment by jdumars** [comment]
Closing as stale.  Please feel free to re-open if this issue is still valid.
