### ISSUE TITLE
Initializer: Consider a build-in "patcher" for initializer to use

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#49877]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

When creating a initializer, we have to write a controller code to patch the resource object. e.g. https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/envoy-initializer/main.go

**What you expected to happen**:

Could we have a build-in "patcher" (as a addon Pod) so users can avoid this step?

I can see there's fixed pattern in this controller, and we can provide a default one in this case.

**Comment by resouer** [comment]
cc @kelseyhightower

**Comment by ncdc** [comment]
@resouer what would you have a "default" patcher pod do exactly? Isn't the initializer logic specific to each individual initializer in terms of what it mutates?

**Comment by resouer** [comment]
@ncdc, patch containers spec, more specifically, for side-car.  Do you think its stand?

**Comment by ncdc** [comment]
@resouer maybe something like that could work, if all you wanted to do was apply something like a json or strategic merge patch to a resource.
