### ISSUE TITLE
use rolling-update error

### ISSUE THREAD

**Issue by whc9527** [kubernetes/kubernetes#49873]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When I was trying to upgrade when using rolling-update for a long time, there is no complete (just a simple nginx), this time I will use the Control+C to terminate, then makes me unable to delete pod

**What you expected to happen**:
how to use rolling-update to upgrade pods

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.6.2
- Cloud provider or hardware configuration**:
Dell R620
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux A03-R07-I9-73.JD.LOCAL 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

The old pod was deleted, but a new one came out again
![image](https://user-images.githubusercontent.com/17898805/28779463-d27eaeac-7635-11e7-9fa6-20603ad6da28.png)

Here is the pod for this JSON
#kubectl get pods my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w  -o=json > my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w.json
`{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"my-nginx-91c06554c6a15b632a933ab2f6abacbf\",\"uid\":\"395beae3-75eb-11e7-b80d-6c92bf4da32c\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1159891\"}}\n"
        },
        "creationTimestamp": "2017-07-31T13:14:08Z",
        "generateName": "my-nginx-91c06554c6a15b632a933ab2f6abacbf-",
        "labels": {
            "deployment": "91c06554c6a15b632a933ab2f6abacbf",
            "run": "my-nginx"
        },
        "name": "my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "ReplicationController",
                "name": "my-nginx-91c06554c6a15b632a933ab2f6abacbf",
                "uid": "395beae3-75eb-11e7-b80d-6c92bf4da32c"
            }
        ],
        "resourceVersion": "1160663",
        "selfLink": "/api/v1/namespaces/default/pods/my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w",
        "uid": "2297e8df-75f2-11e7-b80d-6c92bf4da32c"
    },
    "spec": {
        "containers": [
            {
                "image": "bj01rg.jcloud.com:5000/tengine-2.2.0:v2",
                "imagePullPolicy": "Always",
                "name": "my-nginx",
                "ports": [
                    {
                        "containerPort": 80,
                        "protocol": "TCP"
                    }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "default-token-6h5b9",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "nodeName": "172.27.9.79",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "volumes": [
            {
                "name": "default-token-6h5b9",
                "secret": {
                    "defaultMode": 420,
                    "secretName": "default-token-6h5b9"
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-07-31T13:13:14Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-07-31T13:13:14Z",
                "message": "containers with unready status: [my-nginx]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2017-07-31T13:14:08Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://0216e65fed107b57c77e459e3366743addb272dd14cf5a2579c5cccd92f0e92c",
                "image": "bj01rg.jcloud.com:5000/tengine-2.2.0:v2",
                "imageID": "docker-pullable://bj01rg.jcloud.com:5000/tengine-2.2.0@sha256:f0b1bf5909ca06c3b77fa6c7fe43f0ed6c8d014d57ad533fc3e284fda4efd3b9",
                "lastState": {
                    "terminated": {
                        "containerID": "docker://0216e65fed107b57c77e459e3366743addb272dd14cf5a2579c5cccd92f0e92c",
                        "exitCode": 0,
                        "finishedAt": "2017-07-31T13:14:03Z",
                        "reason": "Completed",
                        "startedAt": null
                    }
                },
                "name": "my-nginx",
                "ready": false,
                "restartCount": 3,
                "state": {
                    "waiting": {
                        "message": "Back-off 40s restarting failed container=my-nginx pod=my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w_default(2297e8df-75f2-11e7-b80d-6c92bf4da32c)",
                        "reason": "CrashLoopBackOff"
                    }
                }
            }
        ],
        "hostIP": "172.27.9.79",
        "phase": "Running",
        "podIP": "172.30.32.2",
        "qosClass": "BestEffort",
        "startTime": "2017-07-31T13:13:14Z"
    }
}`

`[@@@ ~]# kubectl describe pod my-tengine-v2-2dfbf  
Name:           my-tengine-v2-2dfbf
Namespace:      default
Node:           172.27.9.73/172.27.9.73
Start Time:     Mon, 31 Jul 2017 21:24:16 +0800
Labels:         run=my-tengine-v2
                version=v2
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"my-tengine-v2","uid":"8cf90c68-75f3-11e7-b80d-6c92bf4...
Status:         Running
IP:             172.30.60.3
Controllers:    ReplicationController/my-tengine-v2
Containers:
  my-tengine:
    Container ID:       docker://4a00fbf3fe812a0473a9c90e583b613eb1c2c2cf89203925ab7e5f2b0deea722
    Image:              bj01rg.jcloud.com:5000/tengine-2.2.0:v2
    Image ID:           docker-pullable://bj01rg.jcloud.com:5000/tengine-2.2.0@sha256:f0b1bf5909ca06c3b77fa6c7fe43f0ed6c8d014d57ad533fc3e284fda4efd3b9
    Port:               80/TCP
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Completed
      Exit Code:        0
      Started:          Mon, 01 Jan 0001 00:00:00 +0000
      Finished:         Mon, 31 Jul 2017 21:27:09 +0800
    Ready:              False
    Restart Count:      5
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6h5b9 (ro)
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  default-token-6h5b9:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-6h5b9
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type Reason           Message
  ---------     --------        -----   ----                    -------------                   --------      ------          -------
  4m            4m              1       default-scheduler                                       NormaScheduled        Successfully assigned my-tengine-v2-2dfbf to 172.27.9.73
  4m            4m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     NormaCreated          Created container with id 45562f120d521358076da5bd9aa10359775d167a2dd6e2159646d49a90315e5f
  4m            4m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     NormaStarted          Started container with id 45562f120d521358076da5bd9aa10359775d167a2dd6e2159646d49a90315e5f
  4m            4m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     NormaCreated          Created container with id a2c2c554428da27a41cd3449f188937ed1ce085083b9ca14a996fc66191de803
  4m            4m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     NormaStarted          Started container with id a2c2c554428da27a41cd3449f188937ed1ce085083b9ca14a996fc66191de803
  4m            4m              2       kubelet, 172.27.9.73                                    Warning               FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "my-tengine" with CrashLoopBackOff: "Back-off 10s restarting failed container=my-tengine pod=my-tengine-v2-2dfbf_default(8d068c33-75f3-11e7-b80d-6c92bf4da32c)"

  4m    4m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Created      Created container with id d24853a6b72c780e341d798377470a6ed823d1bc7bff5b5f7c73b870116a2119
  4m    4m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Started      Started container with id d24853a6b72c780e341d798377470a6ed823d1bc7bff5b5f7c73b870116a2119
  3m    3m      2       kubelet, 172.27.9.73                                    Warning FailedSync   Error syncing pod, skipping: failed to "StartContainer" for "my-tengine" with CrashLoopBackOff: "Back-off 20s restarting failed container=my-tengine pod=my-tengine-v2-2dfbf_default(8d068c33-75f3-11e7-b80d-6c92bf4da32c)"

  3m    3m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Created      Created container with id 7b8bf21fd3a8ce5c507036d67417ee04bcec3e117e8d797b2be5554b8ae617cb
  3m    3m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Started      Started container with id 7b8bf21fd3a8ce5c507036d67417ee04bcec3e117e8d797b2be5554b8ae617cb
  3m    3m      3       kubelet, 172.27.9.73                                    Warning FailedSync   Error syncing pod, skipping: failed to "StartContainer" for "my-tengine" with CrashLoopBackOff: "Back-off 40s restarting failed container=my-tengine pod=my-tengine-v2-2dfbf_default(8d068c33-75f3-11e7-b80d-6c92bf4da32c)"

  2m    2m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Started      Started container with id a5e29cc2cb3b725a013a41ce9cbd9522ed9250179668cc37a20966356b5a6035
  2m    2m      1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Created      Created container with id a5e29cc2cb3b725a013a41ce9cbd9522ed9250179668cc37a20966356b5a6035
  2m    1m      6       kubelet, 172.27.9.73                                    Warning FailedSync   Error syncing pod, skipping: failed to "StartContainer" for "my-tengine" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=my-tengine pod=my-tengine-v2-2dfbf_default(8d068c33-75f3-11e7-b80d-6c92bf4da32c)"

  4m    1m              6       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  PulleContainer image "bj01rg.jcloud.com:5000/tengine-2.2.0:v2" already present on machine
  1m    1m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Created               Created container with id 4a00fbf3fe812a0473a9c90e583b613eb1c2c2cf89203925ab7e5f2b0deea722
  1m    1m              1       kubelet, 172.27.9.73    spec.containers{my-tengine}     Normal  Started               Started container with id 4a00fbf3fe812a0473a9c90e583b613eb1c2c2cf89203925ab7e5f2b0deea722
  4m    <invalid>       24      kubelet, 172.27.9.73    spec.containers{my-tengine}     Warning BackOff               Back-off restarting failed container
  1m    <invalid>       11      kubelet, 172.27.9.73                                    Warning FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "my-tengine" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=my-tengine pod=my-tengine-v2-2dfbf_default(8d068c33-75f3-11e7-b80d-6c92bf4da32c)"
`

`[@@@ kube]# kubectl rolling-update my-tengine -f my-tengine-v2.yaml 
Created my-tengine-v2
Scaling up my-tengine-v2 from 0 to 2, scaling down my-tengine from 2 to 0 (keep 2 pods available, don't exceed 3 pods)
Scaling my-tengine-v2 up to 1
error: timed out waiting for any update progress to be made
[@@@ kube]# kubectl get pods                                            
NAME                                              READY     STATUS             RESTARTS   AGE
my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w   0/1       CrashLoopBackOff   8          16m
my-tengine-clzjw                                  1/1       Running            0          10m
my-tengine-ds19j                                  1/1       Running            0          10m
my-tengine-v2-2dfbf                               0/1       CrashLoopBackOff   6          6m
[@@@ kube]# cat my-tengine.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-tengine
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-tengine
    spec:
      containers:
      - name: my-tengine
        image: bj01rg.jcloud.com:5000/tengine-2.2.0
        ports:
        - containerPort: 80
[@@@ kube]# cat my-tengine-v2.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-tengine-v2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-tengine-v2
        version: v2
    spec:
      containers:
      - name: my-tengine
        image: bj01rg.jcloud.com:5000/tengine-2.2.0:v2
        ports:
        - containerPort: 80
[@@@kube]#
[@@@ kube]# kubectl get pods
NAME                                              READY     STATUS             RESTARTS   AGE
my-nginx-91c06554c6a15b632a933ab2f6abacbf-9g72w   0/1       CrashLoopBackOff   8          18m
my-tengine-clzjw                                  1/1       Running            0          12m
my-tengine-ds19j                                  1/1       Running            0          12m
my-tengine-v2-2dfbf                               0/1       CrashLoopBackOff   6          8m
 `
Thank you for your help, thank you!

**Comment by xiangpengzhao** [comment]
Could you please edit the issue body with more readable markdown format?

/sig scalability
