### ISSUE TITLE
CRDs should be registered with Aggregation Server

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#49878]
Right now CRDs is being registered with the local API server (not sure what we call that server, is the one that has most of the API Services). That will creates some issues. For example, OpenAPI aggregator needs a signal back from that server to update aggregation when a CRD is registered/removed. If we support that signal, to be consistent, we should support that for User API servers too. I believe it is a much better design to register CRDs with aggregation API server. That way the OpenAPI spec is getting aggregated automatically as well as we won't have to deal with any dynamic changes to API Services on local API server or user API servers.

cc: @deads2k @sttts

**Comment by deads2k** [comment]
> I believe it is a much better design to register CRDs with aggregation API server.

When a CRD creates a new GroupVersion, a controller automatically registers that GroupVersion with the aggregator.    This happens today.

**Comment by mbohlool** [comment]
@deads2k Are you talking about `AutoRegister...` controller? I believe that may not work. I will confirm that, but if that is the case and it is actually registered with aggregation API server, then we should be good regarding aggregation of CRD specs (when they are available).

**Comment by deads2k** [comment]
> @deads2k Are you talking about AutoRegister... controller? I believe that may not work. I will confirm that, but if that is the case and it is actually registers with aggregation API server, then we should be good regarding aggregation of CRD specs (when they are available).

It puts them in the same position as other aggregated API servers.  The constituent servers could be restarted with new resources (see the way `extensions` can turn them on and off) and the openapi aggregation doesn't appear to take that into account.

**Comment by sttts** [comment]
The only missing trigger is if apigroups do not change, but resources do. In other words, we don't have proper watchable resources in a generic CRD independent way. For OpenAPI we would like to have that obviously, at least if we continue to serve an aggregated OpenAPI spec over apigroups (wondering, what the reason was for that original. group-wise would fit much better here).

**Comment by mbohlool** [comment]
We can find a way to update local api server when it is restarted, but if CRDs get registered with aggregation server properly (if they already don't), then a re-register of their APIService triggers an update to aggregated API server.

**Comment by sttts** [comment]
I don't like the idea of an APIServer updating its APIService spec. But I could imagine that an APIServer updates its APIService /status subresource.

**Comment by mbohlool** [comment]
> When a CRD creates a new GroupVersion, a controller automatically registers that GroupVersion with the aggregator. This happens today.

My understanding is the chain goes like this

`apiExtensionsServer` -> `kubeAPIServer` (has v1, etc.) -> `aggregatorServer`

A controller looks into kubeAPIServer and register its API Groups to Aggregator API server, but the Aggregator API Server does not have access to apiExtensionsServer. What is the benefit of having this change, my proposal in this issue is to have them both register with aggregatorServer.

"""bash
`apiExtensionsServer` \\
 ------------------------- > `aggregatorServer`
 `kubeAPIServer`     / 
"""

This way we have access to both of them and we can aggregate their Spec. Then we can periodically look into their changes (as a starter solution in lack of any watchable resource) and aggregate them again.

**Comment by sttts** [comment]
What do you mean with `have access to apiExtensionsServer`? We can change the apiserver api surface in such a way that we get what we need. I don't see that we change the delegation chain design for this. It's merely just an implementation detail of "an ordered list of apiservers". Have to look another look at the current blocker for getting the aggregation right.

**Comment by mbohlool** [comment]
I did not suggest this new design just for this feature. I think it is a slightly better design. 

For the right design, I don't think we should have these layers at all. Aggregation should be just a handler in chan of kubeAPIServer handlers and do aggregation if APIService group is enabled. That would have been much easier design. @cheftako have some thoughts on this.

This issue is not a blocker for OpenAPI aggregation of CRDs. I will find a workaround for that for now.

**Comment by liggitt** [comment]
APIService objects are registered with the aggregation server for every CRD-backed API group, just like every aggregated API group

/close
