### ISSUE TITLE
kubectl create namespace: does not support -l/--labels

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#49887]
/kind feature
/kind friction
/sig cli

**What happened**:

```
$ kubectl create namespace dev --labels=purpose=test
Error: unknown flag: --labels
```

**What you expected to happen**:

I expect `--labels`/`-l` to work on pretty much all resources that can be created with `kubectl create`. Missing labels flag for namespace is creating asymmetry and friction.

I had to write a YAML file to create a namespace with a label.

kubectl: 1.7.2.

**Comment by liggitt** [comment]
see https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#create-commands for the philosophy behind the `kubectl create` commands. create commands are not designed to support every option on every object they can produce. the preferred approach is to create, then label with `kubectl label`

**Comment by manast** [comment]
@liggitt is there any real reason for not supporting creating the label when creating the namespace resource?
I understand the philosophy, but that should only apply to options that are not compatible with a given resource, adding a label is compatible so why not?
