### ISSUE TITLE
User "system:node:127.0.0.1" cannot get configmaps in the namespace "kube-system".: "no path found to object"

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/kubernetes#49880]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Ran hack/local-up-cluster.sh using the latest code from the master. After the local cluster is up, check /tmp/kubelet.log.  It has the following errors:

I0731 16:28:41.786486   12184 empty_dir.go:256] pod 4d7ce016-760d-11e7-9ab2-fa163e060fcc: mounting tmpfs for volume wrapped_kube-dns-token-j73mf
I0731 16:28:41.786503   12184 mount_linux.go:118] Mounting cmd (mount) with arguments ([-t tmpfs tmpfs /var/lib/kubelet/pods/4d7ce016-760d-11e7-9ab2-fa163e060fcc/volumes/kubernetes.io~secret/kube-dns-token-j73mf])
E0731 16:28:41.789256   12184 configmap.go:202] Couldn't get configMap kube-system/kube-dns: configmaps "kube-dns" is forbidden: User "system:node:127.0.0.1" cannot get configmaps in the namespace "kube-system".: "no path found to object"
E0731 16:28:41.789399   12184 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/configmap/4d7ce016-760d-11e7-9ab2-fa163e060fcc-kube-dns-config\" (\"4d7ce016-760d-11e7-9ab2-fa163e060fcc\")" failed. No retries permitted until 2017-07-31 16:28:42.289363623 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "kube-dns-config" (UniqueName: "kubernetes.io/configmap/4d7ce016-760d-11e7-9ab2-fa163e060fcc-kube-dns-config") pod "kube-dns-4124969034-6jgbh" (UID: "4d7ce016-760d-11e7-9ab2-fa163e060fcc") : configmaps "kube-dns" is forbidden: User "system:node:127.0.0.1" cannot get configmaps in the namespace "kube-system".: "no path found to object"
I0731 16:28:41.789500   12184 server.go:347] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-4124969034-6jgbh", UID:"4d7ce016-760d-11e7-9ab2-fa163e060fcc", APIVersion:"v1", ResourceVersion:"238", FieldPath:""}): type: 'Warning' reason: 'FailedMount' MountVolume.SetUp failed for volume "kube-dns-config" : configmaps "kube-dns" is forbidden: User "system:node:127.0.0.1" cannot get configmaps in the namespace "kube-system".: "no path found to object"
E0731 16:28:41.794305   12184 secret.go:201] Couldn't get secret kube-system/kube-dns-token-j73mf: secrets "kube-dns-token-j73mf" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "kube-system".: "no path found to object"
E0731 16:28:41.794511   12184 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/4d7ce016-760d-11e7-9ab2-fa163e060fcc-kube-dns-token-j73mf\" (\"4d7ce016-760d-11e7-9ab2-fa163e060fcc\")" failed. No retries permitted until 2017-07-31 16:28:42.294451161 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "kube-dns-token-j73mf" (UniqueName: "kubernetes.io/secret/4d7ce016-760d-11e7-9ab2-fa163e060fcc-kube-dns-token-j73mf") pod "kube-dns-4124969034-6jgbh" (UID: "4d7ce016-760d-11e7-9ab2-fa163e060fcc") : secrets "kube-dns-token-j73mf" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "kube-system".: "no path found to object"
I0731 16:28:41.794538   12184 server.go:347] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-4124969034-6jgbh", UID:"4d7ce016-760d-11e7-9ab2-fa163e060fcc", APIVersion:"v1", ResourceVersion:"238", FieldPath:""}): type: 'Warning' reason: 'FailedMount' MountVolume.SetUp failed for volume "kube-dns-token-j73mf" : secrets "kube-dns-token-j73mf" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "kube-system".: "no path found to object"

Trying to create a pod using "kubectl.sh create -f <pod yaml file>" resulted in pod in ContainerCreating status.

**What you expected to happen**:
There should not be "forbidden" errors in kubelet.log.
Should be able to create a pod successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. hack/local-up-cluster.sh
2. Check /tmp/kubelet.log
3. kubectl.sh create -f task-pv-volume.yaml
4. kubectl.sh create -f task-pv-claim.yaml
5. kubectl.sh create -f task-pv-pod.yaml

Yaml files used in my testing:

PV task-pv-volume.yaml:

kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

PVC task-pc-claim.yaml:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

Pod task-pv-pod.yaml:

apiVersion: v1
metadata:
  name: task-pv-pod
spec:

  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim

  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pc-storage

**Anything else we need to know?**:
This is related to "https://github.com/kubernetes/kubernetes/issues/49822".
The commit "Enable node authorizer in local-up-cluster #49812" fixed "kubectl get node", but there are still remaining issues as described here.

**Environment**:
- Kubernetes version (use `kubectl version`): latest master
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:  local-up-cluster.sh
- Others:

**Comment by liggitt** [comment]
creating those objects with a `hack/local-up-cluster.sh` on master is working for me:

```
$ kubectl get pod/task-pv-pod pv/task-pv-volume pvc/task-pv-claim 
NAME             READY     STATUS    RESTARTS   AGE
po/task-pv-pod   1/1       Running   0          1m

NAME                CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                   STORAGECLASS   REASON    AGE
pv/task-pv-volume   1Gi        RWO           Retain          Bound     default/task-pv-claim   manual                   4m

NAME                STATUS    VOLUME           CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/task-pv-claim   Bound     task-pv-volume   1Gi        RWO           manual         3m
```

**Comment by liggitt** [comment]
the denials in the kubelet log are expected until the graph the node authorizer uses observes the creation of the pv/pvc/pod, but do not persist for more than a second or two.

> Trying to create a pod using "kubectl.sh create -f " resulted in pod in ContainerCreating status.

that is expected momentarily... a persistent error in setting up the pod would fail the pod.

what do you see after a few seconds when the kubelet is trying to run the pod?

**Comment by xing-yang** [comment]
On my setup, the errors don't go away.  I got the following errors when trying to create the pod:

E0731 16:48:43.922125   12184 secret.go:201] Couldn't get secret default/default-token-96xkh: secrets "default-token-96xkh" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "default".: "no path found to object"
E0731 16:48:43.922226   12184 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/f5b4c2d9-760e-11e7-9ab2-fa163e060fcc-default-token-96xkh\" (\"f5b4c2d9-760e-11e7-9ab2-fa163e060fcc\")" failed. No retries permitted until 2017-07-31 16:50:45.922199905 +0000 UTC (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "default-token-96xkh" (UniqueName: "kubernetes.io/secret/f5b4c2d9-760e-11e7-9ab2-fa163e060fcc-default-token-96xkh") pod "task-pv-pod" (UID: "f5b4c2d9-760e-11e7-9ab2-fa163e060fcc") : secrets "default-token-96xkh" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "default".: "no path found to object"

I0731 16:48:43.922343   12184 server.go:347] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"task-pv-pod", UID:"f5b4c2d9-760e-11e7-9ab2-fa163e060fcc", APIVersion:"v1", ResourceVersion:"1061", FieldPath:""}): type: 'Warning' reason: 'FailedMount' MountVolume.SetUp failed for volume "default-token-96xkh" : secrets "default-token-96xkh" is forbidden: User "system:node:127.0.0.1" cannot get secrets in the namespace "default".: "no path found to object"

I0731 16:48:44.106761   12184 request.go:458] Throttling request took 298.318575ms, request: GET:https://localhost:6443/api/v1/namespaces/default/persistentvolumeclaims/task-pv-claim
E0731 16:48:44.108069   12184 desired_state_of_world_populator.go:274] Error processing volume "task-pv-storage" for pod "task-pv-pod_default(f5b4c2d9-760e-11e7-9ab2-fa163e060fcc)": error processing PVC "default"/"task-pv-claim": failed to fetch PVC default/task-pv-claim from API server. err=persistentvolumeclaims "task-pv-claim" is forbidden: User "system:node:127.0.0.1" cannot get persistentvolumeclaims in the namespace "default".: "no path found to object"

**Comment by liggitt** [comment]
what does `kubectl get node -o yaml` show?

**Comment by xing-yang** [comment]
I tried this again.  Looks like this issue only happens if I set cloud_provider=openstack.

PATH=$PATH KUBERNETES_PROVIDER=local LOG_LEVEL=5 ALLOW_SECURITY_CONTEXT=true ALLOW_PRIVILEGED=true CLOUD_CONFIG="/home/ubuntu/cloudprovider/cloud_config.conf" CLOUD_PROVIDER=openstack hack/local-up-cluster.sh

[get_node_yaml_openstack.txt](https://github.com/kubernetes/kubernetes/files/1188925/get_node_yaml_openstack.txt)

If I don't set cloud_provider and cloud_config, it works.  No "forbidden" errors in kubelet.log and pod is created successfully.

PATH=$PATH KUBERNETES_PROVIDER=local LOG_LEVEL=5 ALLOW_SECURITY_CONTEXT=true ALLOW_PRIVILEGED=true hack/local-up-cluster.sh

[get_node_yaml.txt]
(https://github.com/kubernetes/kubernetes/files/1188927/get_node_yaml.txt)

**Comment by liggitt** [comment]
Setting HOSTNAME_OVERRIDE=kubevm3 to match the name seen by your cloud provider should result in a correct credential for your kubelet

**Comment by xing-yang** [comment]
I tried HOSTNAME_OVERRIDE=kubevm3 and it worked.  Thanks @liggitt !

**Comment by xing-yang** [comment]
I think this issue can be closed now?
