### ISSUE TITLE
kube-proxy clears conntrack for all IPs when it cleans up a nodePort

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#49881]
When we clean up a node port, we run `ExecConntrackTool(execer, "-D", "-p", "udp", "--dport", strconv.Itoa(port))`.  This will clear ALL addresses, but what we really want is just NodePort addresses.

I'm not sure what the right way to express this is.  Consider that we use NodePort 30123 for service A and service port 30123 for service B.  When service A goes away, service B will have its state cleared.

This is very low impact.  The NodePort range is intentionally obscure, and unlikely to actually collide with real Services.  This only affects UDP connections, which are not common.  UDP is typically truly connectionless, so it shouldn't matter if the client gets a new backend.

This would have to have a UDP service be deleted while another UDP service uses the same port and has active "connections" that it needs to stay with the same backend.

Maybe a comment in the code would be sufficient, with a TODO to re-explore this if it ever becomes an issue?

@m1093782566

**Comment by m1093782566** [comment]
Yes, @thockin 

I can help fix it.

**Comment by thockin** [comment]
This is pretty low priority.  Unless the fix is pretty easy (not sure it
is) it may not be worth fixing at all..

**Comment by m1093782566** [comment]
I agree this issue has low priority. I mean should we add a TODO in code now?

**Comment by Stelminator** [comment]
/remove-lifecycle stale

I just ran into a problem using a hostPort service that got replaced, while still on the same machine; maybe I need to install `conntrack` to get the clearing to work, but that's an unexpected step.

**Comment by Stelminator** [comment]
actually, I think I ran into what gets fixed by https://github.com/kubernetes/kubernetes/pull/59286
