### ISSUE TITLE
kubectl does not support rollout commands for StatefulSet

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#49890]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**: There are rollout commands for Deployment and DaemonSet, but not StatefulSet. As part of greater core controller GA plan, implementing kubectl rollout command for StatefulSet will contribute to standardization of existing kubectl commands across all core controllers.

**What you expected to happen**: As `pause` and `resume` are not applicable for current StatefulSet operations, kubectl should support rollout `history`, `status`, and `undo` commands for StatefulSet.

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: I have started working on this.

**Environment**: N/A
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huangjiasingle** [comment]
@crimsonfaith91  1.7 seem to support this command.   https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v170
