### ISSUE TITLE
Enable the BootstrapSigner and TokenCleaner controllers by default

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#49900]
Needed for getting https://github.com/kubernetes/features/issues/130 to beta
cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-auth-feature-requests

**Comment by timothysc** [comment]
@mattmoyer

**Comment by luxas** [comment]
Closing this as we decided to not do this for beta.
