### ISSUE TITLE
Increase default value of DeploymentSpec.RevisionHistoryLimit to 10 in apps/v1beta2

### ISSUE THREAD

**Issue by liyinan926** [kubernetes/kubernetes#49913]
All controllers that use the `RevisionHistoryLimit` field have a default value of 10 for the field, except for `Deployment`, which has a default of 2. We should increase it to 10 for consistency on its default value across controllers. 

/sig apps

**Comment by wanghaoran1988** [comment]
@kubernetes/sig-apps-misc
