### ISSUE TITLE
replication controller send delete Signal but delete fail then the pod always exist

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#49917]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
After the pod is scheduled to a node and no memory is found, after manual cleanup of the node's disk space, the RC is re-scheduled to another node, and the pod of RC scheduled to the first node has sent the deletion signal but the deletion failed and Always exist！
**What you expected to happen**:
not always existed !

the pod Information：
![image](https://user-images.githubusercontent.com/25783555/28805177-bc24708c-769a-11e7-9ccf-736c6552fc62.png)

describe the pod
![image](https://user-images.githubusercontent.com/25783555/28805194-dc87d6d4-769a-11e7-9153-5e74aadac6b7.png)

container information
![image](https://user-images.githubusercontent.com/25783555/28805315-b6a0bf84-769b-11e7-8e22-043022730ee9.png)

docker logs 
![image](https://user-images.githubusercontent.com/25783555/28805366-18980760-769c-11e7-8561-dbac62820611.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.5.1
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):NewStart Carrier Grade Server Linux
- Kernel (e.g. `uname -a`):Linux paas-controller-200-0-0-154 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu Jun 29 01:10:55 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jianzhangbjz** [comment]
The `kubelet` of the first node is running well? logs of `kubelet`?

**Comment by jianglingxia** [comment]
thanks for your review,but now the Environment has been redeployed by other People，so I can not take the log，but in that time the  kubelet of the first node is running！so I guess that the RC delete the pod once Whether or not to delete？or you Encountered the Problem？thanks！

**Comment by jianzhangbjz** [comment]
No, never encountered. I doubt it maybe caused by `Kubelet` or `ControllerManager`.
Have you test the latest version for this?

**Comment by jianglingxia** [comment]
now our project used V1.5.1，haven't used the latest version，will update to 1.6.4 recently，one problem i want to know that the rc delete the pod once whether or not delete？

**Comment by jianzhangbjz** [comment]
No, the rc(`ControllerManager`) doesn't execute delete pod action, it just make sure the number of replies with my understanding. What's the output of `kubectl describe rc`? Or can you reproduce this issue?

**Comment by zhangxiaoyu-zidif** [comment]
If no memory, how could Pod be assigned to that node. I feel confused. =(

**Comment by jianzhangbjz** [comment]
I think the memory he said, means the disk. Maybe this problem was caused by the container itself.
