### ISSUE TITLE
hack/local-up-cluster.sh does not create a node by default

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#49920]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Running `hack/local-up-cluster.sh` does not trigger creation of a node. When running `kubectl get nodes`, it return no resource.

**What you expected to happen**: There will be a default node created.

**How to reproduce it (as minimally and precisely as possible)**:
(1) hack/local-up-cluster.sh
(2) kubectl get nodes

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.991+3e77df06dec76a-dirty", GitCommit:"3e77df06dec76a97415ad55675a48cd68303e641", GitTreeState:"dirty", BuildDate:"2017-07-28T23:34:42Z", GoVersion:"go1.9rc1_cl163367517", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
how are you invoking local-up-cluster? are you setting a cloud provider?

**Comment by liggitt** [comment]
it looks like you're building from a local branch 3e77df06dec76a97415ad55675a48cd68303e641 based on https://github.com/kubernetes/kubernetes/commit/4a73f19aed1f95b3fde1177074aee2a8bec1196e

this is a dupe of https://github.com/kubernetes/kubernetes/issues/49822, fixed in https://github.com/kubernetes/kubernetes/pull/49812. rebasing your branch on master will pick up the fix.

**Comment by crimsonfaith91** [comment]
@liggitt Thanks! Appreciate the clarification.
