### ISSUE TITLE
gci-gke tests in 1.7 branch are consistently failing

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#49939]
As an example those jobs:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-reboot-release-1-7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-slow-release-1-7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gci-gke-serial-release-1-7

@abgworrall @dchen1107 @mtaufen - can you please triage? This will block the 1.7.3 cut.

**Comment by abgworrall** [comment]
Very consistent failures across all three jobs, from ~4pm yesterday onwrds.

I'd guess something changed WRT GCP networking, maybe even a change to GKE test endpoint ?

@Kashomon , @bowei , @fejta  - in case you've seen something like this before ...

It doesn't seem obviously related to a commit - the final passing job and first failing job are both on the same k8s commit hash.

I'm not hugely sure which errors are fatal and which should be warnings, but I'm seeing:

```
ERROR: (gcloud.compute.networks.describe) Could not fetch resource:
  - The resource 'projects/k8s-e2e-gke-alpha-1-5/global/networks/e2e-1314' was not found

ERROR: (gcloud.compute.firewall-rules.describe) Could not fetch resource:
  - The resource 'projects/k8s-e2e-gke-alpha-1-5/global/firewalls/e2e-ports-88c85ac5' was not found

./hack/ginkgo-e2e.sh: line 97: detect-node-instance-groups: command not found
!!! Error in ./hack/ginkgo-e2e.sh:97
   Error in ./hack/ginkgo-e2e.sh:97. 'detect-node-instance-groups' exited with status 127
```

**Comment by yujuhong** [comment]
Looks like KUBERNETES_CONFORMANCE_TEST is set properly, so hack/ginkgo-e2e.sh skips the GKE setup. 
```
W0801 14:51:34.476] 2017/08/01 14:51:34 util.go:129: Running: ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts
I0801 14:51:34.636] Conformance test: not doing test setup.
W0801 14:51:35.059] ./hack/ginkgo-e2e.sh: line 97: detect-node-instance-groups: command not found
W0801 14:51:35.062] !!! Error in ./hack/ginkgo-e2e.sh:97
W0801 14:51:35.062]   Error in ./hack/ginkgo-e2e.sh:97. 'detect-node-instance-groups' exited with status 127
```
I saw a couple of test-infra PRs from @zmerlynn that touched the gke setup logic. Not sure if they are related.

**Comment by zmerlynn** [comment]
/assign

This is me, I'll have a cherry pick out shortly.

**Comment by zmerlynn** [comment]
c.f. #49960. This is totally my bad, I meant to get the c-ps in before migrating the release branches. (Honestly, I was hoping the work to complete the wrapper was finished before then and forgot about it.)
