### ISSUE TITLE
K8s auto reset ConfigMap 

### ISSUE THREAD

**Issue by akaipham** [kubernetes/kubernetes#49934]
**What happened**:
Whenever I updated ConfigMap, it triggers config-reloader to reload new ConfigMap as expected. But then, after a while, it reset ConfigMap to default configuration

**What you expected to happen**:
Remain new ConfigMap and DON'T reset ConfigMap

**Environment**:
- Kubernetes version (use `kubectl version`):
>Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", @gnufied GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.6-rancher1", GitCommit:"973d2fa162b887a6f696f4574b85e949d480a071", GitTreeState:"clean", BuildDate:"2017-06-17T03:54:44Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

@kubernetes/sig-contributor-experience-bugs /kind bug

**Comment by dixudx** [comment]
@akaipham Any ways to reproduce this? And related logs.

**Comment by akaipham** [comment]
@dixudx I just update manually ConfigMap on k8s Dashboard. As you can see, I updated once at 9:27, it worked well, then it trigger another reload and reset ConfigMap to default
![image](https://user-images.githubusercontent.com/25759643/28819186-90ae8d7e-76d7-11e7-9fc6-dafa2855669b.png)
Here default configuration after 'weird' reloading at 9:32
![image](https://user-images.githubusercontent.com/25759643/28819206-ab3d892e-76d7-11e7-9aab-febc65cbbd88.png)

**Comment by akaipham** [comment]
Another thing is Secret remain same after both two reloading

**Comment by liggitt** [comment]
what config-reloader are you referring to?

**Comment by akaipham** [comment]
@liggitt I'm using this `jimmidyson/configmap-reload` as config-reloader

**Comment by akaipham** [comment]
ATM, I found out that `quay.io/coreos/configmap-reload` does not trigger reloading by itself, and it uses `prometheus.yaml` as key to reference in `Secret`. In contrast, `jimmidyson/configmap-reload` triggers reloading automatically when detecting changes in config files, but it uses `ConfigMap` to load configuration and yields above error that reseting configuration to default.

Is there any recommendation for `standard` config-reloader? @liggitt
