### ISSUE TITLE
Enabling insecure port for API Server

### ISSUE THREAD

**Issue by mohitpatiyala** [kubernetes/kubernetes#49933]
Hi All

We installed kubernetes using kubeadm and want to enable the "insecure-port" for the apiserver , we tried updating the "kube-apiserver.yaml" and restarted the Kubelet but it is taking the original YAML file for the pod and not taking our changes .

We even tried updating the YAML file for the pod from the Dashboard but it says acess denied 

Any suggestions on how to achieve this

Thanks & Regards
Mohit Patiyala

**Comment by dixudx** [comment]
@mohitpatiyala Where is your `--pod-manifest-path`? All the static pod manifests are stored default to `/etc/kubernetes/manifests`. `kubelet` will watch the changes of this directory. You can update `apiserver` configurations there by adding `--insecure-bind-address=0.0.0.0`.

**Comment by huangjiasingle** [comment]
@dixudx @mohitpatiyala  you can't only add --insecure-bind-address=0.0.0.0, you also should update the --insecure-port=8080. it's will be ok.

**Comment by huangjiasingle** [comment]
@mohitpatiyala  if you use the dashboard to deploy a pod or deployment . and you also want to  use insecure  api of apiserver, you should deploy the dashboard without rbac or abac authorizion.

**Comment by dixudx** [comment]
@huangjiasingle The default value of `--insecure-port` is `8080`, which can be omitted. Also for insecure requests, no authentications and authorizions will be performed.

**Comment by mohitpatiyala** [comment]
@huangjiasingle  i tried updating the yaml file and restarted the kubelet but it is still refeerring to the orignal yaml file

**Comment by huangjiasingle** [comment]
@dixudx  my kubernetes's version is 1.6.x or 1.7.x, The default value of --insecure-port is 0, it's mean's that doesn't support insecure api handler. the old version. l didn't use. you can see the /etc/kubernetes/manifest/kube-apiserver.yaml to cosume it

**Comment by huangjiasingle** [comment]
@mohitpatiyala  you can show your kubelet's config file ?  maybe the  config file's manifest dir is not you modified yaml's dir.  so please show your kubelet's config file and  the absolute path of you modified kube-apiserver.yaml.  maybe l can find the reason of your bug

**Comment by dixudx** [comment]
@huangjiasingle Just an excerpt from [kube-apiserver official doc](https://kubernetes.io/docs/admin/kube-apiserver/).

> --insecure-port int                                       The port on which to serve unsecured, unauthenticated access. It is assumed that firewall rules are set up such that this port is not reachable from outside of the cluster and that port 443 on the cluster's public address is proxied to this port. This is performed by nginx in the default setup. (default 8080).

`--insecure-port=0` means to disable insecure access, which is not the default value.

**Comment by mohitpatiyala** [comment]
@huangjiasingle
Below is the apiserver YAML and kubelet conf file (renamed to text) 
[kube-apiserver.txt](https://github.com/kubernetes/kubernetes/files/1196707/kube-apiserver.txt)  
[kubelet.txt](https://github.com/kubernetes/kubernetes/files/1196711/kubelet.txt)

Also the absolute path of the API server YAML file is (/etc/kubernetes/manifests)

We notice that as soon as we change the YAML file(adding the insecure port) the API Server pod crashes , we tried restarting the Docker Daemon as well as the Kubelet but it doesnt help 

The only option is to revert the changes ,

**Comment by mohitpatiyala** [comment]
@dixudx  when installing through Kubeadm the default value of the default  --insecure-port=0 and not 8080

**Comment by dixudx** [comment]
@mohitpatiyala That means kubeadm disable insecure requests by setting `--insecure-port=0`.
