### ISSUE TITLE
Make log-rotation maxSize and/or #Files on VM configurable through salt

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#49941]
We are losing some older apiserver logs on our long-running scale-tests due to logrotate set by default to 5 files of maxsize 100M.
This should be made configurable.

cc @k8s-mirror-cluster-lifecycle-misc @kubernetes/sig-scalability-misc @crassirostris

**Comment by crassirostris** [comment]
Note, that by changing the logrotate script in the `configure-helper.sh`, you change the setting for all components that write to `/var/log` directly, not only for apiserver

**Comment by gmarek** [comment]
Which is fine for our purposes:)

**Comment by crassirostris** [comment]
SGTM
