### ISSUE TITLE
DefaultRESTMapper does not work for custom resources CRD

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#49948]
**What happened**:
`DefaultRESTMapper.Add()` uses `UnsafeGuessKindToResource()` instead of using `plural` field returned by discovery.

**What you expected to happen**:
Rest mapper should return correct plural form in the "resource" field of `RESTMapping`.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CRD where plural != lowercase kind+"s" e.g. plural is "bla1" and kind is "Blax".
On a discovery rest mapper try to call `RESTMapping()` with the group/kind of the CR.
It will return something like "blaxs".

I wonder how GC works in #47665. Isn't it affected by this issue? @ironcladlou 

**Environment**:
I use 1.7 branch of client-go but looks like k8s master does not have any changes to `DefaultRESTMapper` so the bug is there too.

/kind bug
/sig api-machinery
/area third-party-resource

**Comment by enisoc** [comment]
cc @kubernetes/sig-api-machinery-bugs @deads2k

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/kubernetes/pull/50012

**Comment by ironcladlou** [comment]
I somehow missed this issue and independently re-discovered it while root causing https://github.com/kubernetes/kubernetes/issues/50022. Oops! Thanks!
