### ISSUE TITLE
TestClientGoCustomResourceExample flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#49956]
flaking on HEAD:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=ci-kubernetes-test-go&test=TestClientGoCustomResourceExample

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/8135#k8siokubernetesvendork8sioapiextensions-apiservertestintegration-testclientgocustomresourceexample

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/8118#k8siokubernetesvendork8sioapiextensions-apiservertestintegration-testclientgocustomresourceexample

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/8105#k8siokubernetesvendork8sioapiextensions-apiservertestintegration-testclientgocustomresourceexample

@kubernetes/sig-api-machinery-test-failures

**Comment by liggitt** [comment]
these errors started occurring right after 74b9ba3b4d7c6f0a116464ac01a5f98b915d4586 was merged

cc @deads2k @wojtek-t for oddities with watch, custom resources, and the watch cache

**Comment by wojtek-t** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
Could this be interactions with the aggregator cache?

**Comment by smarterclayton** [comment]
```
E0728 21:35:49.536152   31354 customresource_discovery_controller.go:155] timed out waiting for caches to sync
```

Is that bad?

**Comment by liggitt** [comment]
> Could this be interactions with the aggregator cache?

no, `TestClientGoCustomResourceExample` tests a CRD server all alone, no aggregator involved

**Comment by liggitt** [comment]
with lots of tracing added, I can reproduce:

controller lister/watcher:
1. lists before watch cache is ready, goes to etcd, gets empty list at resourceVersion=386
2. watches from resourceVersion=386 before watch is ready

client creates an object with resourceVersion 387

cacher lister/watcher:
1. lists, gets list with a single item at resourceVersion=387
2. watches etcd from resourceVersion=387

processEvent is never called with the 387 watch event. the next event it sees is the delete event at 388 when the test times out and is tearing itself down.
