### ISSUE TITLE
 [Flaky e2e test] Garbage collector should not delete dependents that have both valid owner and owner that's waiting for dependents to be deleted

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#49966]
Failure rate is [high](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=%20Garbage%20collector%20should%20not%20delete%20dependents%20that%20have%20both%20valid%20owner%20and%20owner%20that%27s%20waiting%20for%20dependents%20to%20be%20deleted).

We have an integration test that validates the same functionality, so i probably will investigate the cause of the e2e failures and then delete the e2e test.

**Comment by liggitt** [comment]
be careful to verify the root cause before... the e2e tests often reveal more about real-life interactions between controllers

**Comment by caesarxuchao** [comment]
case 1: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49370/pull-kubernetes-e2e-gce-etcd3/44357?log#log

error message: failed to delete rc simpletest-rc-to-be-deleted, err: timed out waiting for the condition

The RC deletion was initiated at:
```
I0801 16:26:18.165300       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-gc-xb9vb/replicationcontrollers/simpletest-rc-to-be-deleted: (16.092908ms) 200 [[e2e.test/v1.8.0 (linux/amd64) kubernetes/749e032] 104.197.26.237:51122]
```

The rc is deleted after 61s, exceeding the 30s timeout, according to apiserver log,
```
I0801 16:27:19.477118       5 wrap.go:42] PUT /api/v1/namespaces/e2e-tests-gc-xb9vb/replicationcontrollers/simpletest-rc-to-be-deleted: (378.903338ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/749e032/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:60024]
...

I0801 16:27:19.884942       5 wrap.go:42] GET /api/v1/namespaces/e2e-tests-gc-xb9vb/replicationcontrollers/simpletest-rc-to-be-deleted: (146.856642ms) 404 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/749e032/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:60024]
```

and garbage collector starts a resync of API at 16:26:46
```
I0801 16:26:46.817518       5 wrap.go:42] GET /api: (285.843042ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/749e032/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:60024]
```
it's finished at 16:27:18
```
I0801 16:27:18.386885       5 controller_utils.go:1001] Caches are synced for garbage collector controller
```

The resync costs 32s.

**Comment by caesarxuchao** [comment]
@ironcladlou the rediscovery is quite expensive (32s). After https://github.com/kubernetes/kubernetes/pull/47353 is in, we can optimize the gc.Sync() by returning early if server replies there is no API changes.

**Comment by caesarxuchao** [comment]
Case 2:  The timeout was caused by an untimely API rediscovery.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49891/pull-kubernetes-e2e-gce-etcd3/44351?log#log

Same error: I0801 16:07:47.248] Aug  1 16:07:15.495: INFO: failed to delete rc simpletest-rc-to-be-deleted, err: timed out waiting for the condition

Delete started at:
```
I0801 16:06:45.348896       5 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-gc-wxzl6/replicationcontrollers/simpletest-rc-to-be-deleted: (9.546583ms) 200 [[e2e.test/v1.8.0 (linux/amd64) kubernetes/55f0a06] 130.211.120.23:50632]

```

finished at 16:06:17, 32s in total, slightly exceeded the 30s timeout
```
I0801 16:07:17.993865       5 garbagecollector.go:455] remove DeleteDependents finalizer for item [v1/ReplicationController, namespace: e2e-tests-gc-wxzl6, name: simpletest-rc-to-be-deleted, uid: 6357ce39-76d3-11e7-8b17-42010a800002]
...
I0801 16:07:18.241963       5 wrap.go:42] PUT /api/v1/namespaces/e2e-tests-gc-wxzl6/replicationcontrollers/simpletest-rc-to-be-deleted: (42.6588ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/55f0a06/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:37510]
```

In the meantime, GC had a API rediscovery starting at
```
I0801 16:06:48.434979       5 wrap.go:42] GET /api: (17.01229ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/55f0a06/system:serviceaccount:kube-system:generic-garbage-collector] [::1]:37510]
```

Finished at 
```
I0801 16:06:57.481190       5 controller_utils.go:1001] Caches are synced for garbage collector controller
```

The rediscovery took 9 seconds.

**Comment by caesarxuchao** [comment]
The API rediscovery periods is set to [30s](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/core.go#L342). Before we can optimize the API rediscovery for GC, we need to increase the timeout in the tests.

**Comment by ironcladlou** [comment]
Thanks for the great research. I think this is more important to solve in the short term than https://github.com/kubernetes/kubernetes/issues/49718 in the short term and will see if I reduce the sync time.

**Comment by ironcladlou** [comment]
@caesarxuchao 

Looking over the new sync code again, one thing that stood out immediately is that we're unconditionallly [pausing workers](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L174) during the discovery resync. Seems like it'd be an improvement if we re-discovered asynchronously and then paused workers only if new discovery results were observed requiring a monitor resync.

One problem there is that we're calling `Reset` on a shared RESTMapper, so we can't re-discover without impacting the running informers and workers. Will think more about this.

**Comment by ironcladlou** [comment]
@caesarxuchao One option would be to periodically build a new RESTMapper (rather than calling Reset on the existing one), diffing the resource list against current, and if there's an update, atomically swapping in the new mapper to the graph builder. This would ensure:

1. We only stop processing if there's a reason to do so
2. Pause time is minimized because the mapper is already initialized via the async request to get the current resource list

**Comment by dims** [comment]
is this set of failures related to the original problem in the issue too? `Garbage collector should not be blocked by dependency circle` [Failure rate](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&test=Garbage%20collector%20should%20not%20be%20blocked%20by%20dependency%20circle)

**Comment by ironcladlou** [comment]
@dims 
>@caesarxuchao @ironcladlou is this set of failures related to the original problem in the issue too? Garbage collector should not be blocked by dependency circle Failure rate

I believe so (and @caesarxuchao can probably confirm). I'm also triaging https://github.com/kubernetes/kubernetes/issues/50022#event-1189821662 which are likely the same root cause.

**Comment by caesarxuchao** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/50046 to track the optimization of API discovery behavior of GC.

**Comment by caesarxuchao** [comment]
@dims tracked "Garbage collector should not be blocked by dependency circle" in https://github.com/kubernetes/kubernetes/issues/50047.

**Comment by ironcladlou** [comment]
https://github.com/kubernetes/kubernetes/pull/50335 is an attempt at improving the situation.

**Comment by Raffo** [comment]
This is probably only an improvement, but not a fix as I see the same test failing again: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48963/pull-kubernetes-e2e-gce-etcd3/47829/#sig-api-machinery-garbage-collector-should-not-delete-dependents-that-have-both-valid-owner-and-owner-thats-waiting-for-dependents-to-be-deleted

**Comment by ironcladlou** [comment]
@Raffo 
>This is probably only an improvement, but not a fix as I see the same test failing again: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48963/pull-kubernetes-e2e-gce-etcd3/47829/#sig-api-machinery-garbage-collector-should-not-delete-dependents-that-have-both-valid-owner-and-owner-thats-waiting-for-dependents-to-be-deleted

The flake you linked is https://github.com/kubernetes/kubernetes/issues/42086. 

#50335 is intended to (and seems to have) have resolved the flake covered by this issue.
