### ISSUE TITLE
Hardware topology awareness at node level (including NUMA)

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#49964]
/kind feature

**Problem description:**

Multiple components in the Kubelet make decisions about NUMA-related assignments:

- Hugetlb cgroup controller and hugetlbfs volume plugin ([proposal](https://github.com/kubernetes/community/pull/837)). Limits and volumes are managed per-memory-node on NUMA systems. 
- Container network interface. Network interfaces including SR-IOV virtual functions have affinity to one NUMA node, with measurable performance ramifications.
- CPU manager ([proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cpu-manager.md)). The CPU manager makes decisions about the set of CPUs a container is allowed to run on.
- Device manager ([proposal](https://github.com/kubernetes/community/pull/695)). The device manager makes concrete device assignments to satisfy container resource requirements. Generally devices are attached to e.g. one PCIe switch. In case there is a misalignment between the device manager and the CPU manager, all communication between the CPU and the device can incur an additional hop over the interconnect fabric.

Each of these components will need to coordinate about the resource assignment in order to avoid cross NUMA assignments. The problems related to this coordination are tricky; reasonable cross domain assignments such as “one exclusive core on the same NUMA node as my assigned network interface” will involve both CNI and the CPU manager.

@kubernetes/sig-node-feature-requests

**Comment by ConnorDoyle** [comment]
This is a placeholder, the intent of wg-resource-management is to begin discussing this more seriously during the v1.9 development cycle at the earliest.

**Comment by msau42** [comment]
This will have impact on local persistent storage too. I am currently working on changes to make the scheduler aware of storage topology, but the smallest granularity is at the node level, and not within a node.

**Comment by davidopp** [comment]
@msau42 My understanding is that the kind of detailed scheduling @ConnorDoyle is talking about is done locally on the kubelet and not in the cluster scheduler (except very coarse-grained things like number of NUMA nodes you are requesting).

**Comment by msau42** [comment]
Yeah, so it can have impact on the volume binding flow since the decision to bind to a particular pci-e ssd could impact the numa-aware scheduling of the pod.

**Comment by vishh** [comment]
@msau42 We have discussed this in detail already. To give some context, high performance hardware like GPUs may want direct access to SSDs to lower latency. See [GPU Direct](https://developer.nvidia.com/gpudirect) for example. To me, moving volume binding out of the current controller is the first main leap. Moving it to the kubelet can happen in the future. We can also explore the possibility of using extensions to tackle the performance scenario, until upstream can solve it. Let's not re-design volume binding in this issue though.

**Comment by msau42** [comment]
That's fine.  I just wanted to make sure that the dependency is known, and that I am kept in the loop.

**Comment by davidopp** [comment]
Thanks for the clarification @msau42. I hadn't thought about that.

**Comment by rkamudhan** [comment]
+1 for this feature, we are investigating numa awareness feature though SRIOV CNI

**Comment by ConnorDoyle** [comment]
cc @resouer

**Comment by resouer** [comment]
Thanks Connor for redirecting!

We would like to propose some ideas (see the doc below) about GPU topology (once discussed with @RenaudWasTaken, here is more details). This came from real use cases.

https://docs.google.com/document/d/1NprGyCflZOC3Dkb1ndinvmXaawqOmlBCt_ktlXk22yE/edit#

As a summary, the use case includes:
1. How can we represent topology information in Pod spec and scheduler?
2. How scheduler use these non-numerical topology info to do predicate/priority?
    1. [ResouceClass design](https://github.com/kubernetes/community/pull/782) should help here while the current design need change I think.
3. What structure should be passed to Device Plugin and how to use it do `Allocate()`?

Other random thoughts:
1. We may need umbrella issue and sub-issues as it looks like this one is mainly about NUMA? GPU topology can be a little bit different. 
2. We may also need to narrow down what kind of topology we want to support in the first stage. @RenaudWasTaken may help here.
3. The goal would be a general proposal which can handle the whole process (data structure, scheduling, allocate) of our target topology cases.

**Comment by ConnorDoyle** [comment]
Discussion doc: [Use cases and requirements for Kubernetes hardware topology](https://docs.google.com/document/d/1dv3-se21ivEZhyRCr9qixvjyB_VRO2yIlotWb2kOdiw) (join `kubernetes-sig-node`, `kubernetes-dev`, or `kubernetes-wg-resource-management` mailing lists to view/comment)

**Comment by ConnorDoyle** [comment]
Here is a design doc to address only part of the problem: making CPU manager and device manager agree on numa alignment. https://github.com/kubernetes/community/pull/1680

**Comment by eloyekunle** [comment]
@ConnorDoyle 

I'm working on my GSoC proposal for _[Kubernetes with hardware devices topology awareness at node level](https://github.com/cncf/soc#kubernetes-with-hardware-devices-topology-awareness-at-node-level)_ and I have some questions:
- What exactly do we mean by `Hardware topology awareness at node level`?
For example, the CPU manager is able to detect the `CPUTopology` and act on it. If the CPU topology detection is done at Node level, then I guess we already have CPU topology awareness at node level and only need to start implementing topology awareness for other components (e.g. GPUs, NICs etc).
Is this what we're trying to do?

- I've read the [topology manager proposal](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0035-20190130-topology-manager.md), and one of the Goals is to provide interface and pattern to integrate additional topology-aware components (e.g. GPUs, NICs etc). Eventually, this would be used to arbitrate affinity for containers based on these components.
Question: Isn't this achieved by the current device plugins? Or is this supposed to provide additional interfaces for device plugins to be able to integrate topology-awareness?

- Where does NUMA fit into all this? Is NUMA another component that we want to implement topology awareness for?

- How generic is the device topology awareness supposed to be? Will we be implementing for some devices and make it possible for users to extend?

(Sorry if there's any of these questions that's been asked and answered before, I got confused reviewing some past material)

@resouer 
It seems a major consideration for [this project idea](https://github.com/cncf/soc#kubernetes-with-hardware-devices-topology-awareness-at-node-level) is GPU-related. To what extent is the implementation supposed to be generic, or GPU-focused?

**References**
- [K8s GPUs In Action - Google Docs](https://docs.google.com/document/d/1lSwVh2ZfJ2FeLXIeyyiNqN_hKPYpahJiwN5X5cszjOk/edit#)
- [A Primitive GPU Topology Use Case From Research Users - Google Docs](https://docs.google.com/document/d/1NprGyCflZOC3Dkb1ndinvmXaawqOmlBCt_ktlXk22yE/edit#)
- [Topology-Aware GPU Scheduling for Learning Workloadsin Cloud Environments](https://upcommons.upc.edu/bitstream/handle/2117/114851/Topology-Aware%20GPU%20Scheduling%20for%20Learning%20Workloads.pdf)
- [kubernetes/enhancements/0035-20190130-topology-manager.md at master](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0035-20190130-topology-manager.md)

**Comment by ConnorDoyle** [comment]
@eloyekunle

> What exactly do we mean by Hardware topology awareness at node level?

You’re right the CPU manager takes topology into account when allocating exclusive cores. In the topology manager proposal it’s stated that the scope is “just” to make CPU manager and device manager try to cooperate regarding the closest CPU socket. In general, this ticket is about making sure the various components inside Kubelet can coordinate this way to avoid leaving a lot of performance on the floor.

> Question: Can't this be achieved by the current device plugins architecture? 

Not reliably. Before topology manager is added, Kubelet knows nothing about socket affinity or any other locality among devices from any single device plugin. That problem is even harder to solve without support from the Kubelet when there are multiple device plugins involved, or exclusive cpu cores as mentioned above.

> Where does NUMA fit into all this? Is NUMA another component that we want to implement topology awareness for?

This is TBD and part of the design space. So far we’ve deferred dealing with memory affinity since many applications that benefit from locality tend to use libnuma or similar to allocate buffers. In some of those cases, aligning devices is enough for the application to do the right thing.

> How generic is the device topology awareness supposed to be? 

Ideally we can come up with some further extensions to the TopologyHints struct from the Topology manager that benefit multiple device families and vendors. Top of mind now are point-to-point or switched inter-device links.

**Comment by eloyekunle** [comment]
@ConnorDoyle Thanks for your explanations. I understand the problem much better now.

**Comment by vivpm6ue** [comment]
@ConnorDoyle is there any way to try out the Topology Manager or the following module?

https://github.com/kubernetes/community/pull/1680

Are there instructions or Is there a daemonset/yaml/config of the ongoing work on this that I can install on my multi-NUMA SRIOV bare metal K8s setup to give it a try?

**Comment by everpeace** [comment]
> one of the Goals is to provide interface and pattern to integrate additional topology-aware components (e.g. GPUs, NICs etc)

I would really love kubernetes to support this and am interested in this topic.  In our use case,  we would like to allocate multiple GPUs and multiple NICs with socket(PCI level) affinity to containers for high performance distributed deep learning workloads.
