### ISSUE TITLE
Bug in hack/verify-no-vendor-cycles.sh

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#49977]
The script tries to find cycles in the staging folder with a short name of repos. This will create problems as "k8s.io/api"'s short name is "api" and the grep commands will match that to "kube-openapi" and thinks kubeopenapi has a cyclic dependency. e.g.:

```
echo "k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/util" | grep -E "api|apiextensions-apiserver|apimachinery|apiserver|client-go|kube-aggregator|kube-gen|metrics|sample-apiserver"```

returns `util` package while its intend was to grep "k8s.io/api/" instead of "api". I suggest we change pattern to "k8s.io/$$$/" where $$$ is the old pattern values.

**Comment by cblecker** [comment]
/sig api-machinery
cc: @caesarxuchao

**Comment by dims** [comment]
@caesarxuchao @mbohlool something like this?

```
grep -E "k8s.io\/(api|apiextensions-apiserver|apimachinery|apiserver|client-go|kube-aggregator|kube-gen|metrics|sample-apiserver)\/"
```

**Comment by caesarxuchao** [comment]
I'd replace the second "\/" with a word boundary (perhaps `\>`? now sure about the syntax). It's just in case these repos have top-level packages.

**Comment by mbohlool** [comment]
I sent a fix for this in #48861

**Comment by dims** [comment]
@mbohlool Since #48861 has merged, this issue can be closed right?

**Comment by mbohlool** [comment]
Yes. Thanks for the solution @dims and @caesarxuchao
