### ISSUE TITLE
SQ Blocked on PVC bind failures for AWS kops

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#49981]
**BUG REPORT**:
 /kind bug

aws-kops is [consistently](https://prow.k8s.io/?type=batch) failing to delete pvs and bind pvcs to new pvs as seen [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-kops-aws/38636/). We haven't been able to get a batch through for most of the day.

**Comment by wongma7** [comment]
W0801 17:17:11.376921       5 shared_informer.go:301] resyncPeriod 15000000000 is smaller than resyncCheckPeriod 49961631804456 and the informer has already started. Changing it to 49961631804456

https://github.com/kubernetes/kubernetes/issues/49905#issuecomment-319367328

so https://github.com/kubernetes/kubernetes/pull/49016 will probably fix it
