### ISSUE TITLE
Allocate healthcheck nodeport the same way as common nodeports

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#49999]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
healthcheck nodeport allocation doesn't have roll-back, this may lead to nodeport leak.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig network
/assign

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MrHohn** [comment]
> healthcheck nodeport allocation doesn't have roll-back, this may lead to nodeport leak.

Could you clarity "roll-back"? It seems that we [release nodePort and healthCheckNodePort](https://github.com/kubernetes/kubernetes/blob/v1.7.2/pkg/registry/core/service/rest.go#L218-L236) basically in the same way.

**Comment by xiangpengzhao** [comment]
@MrHohn I didn't mean the HealthCheck NodePort release process in `Delete()`. I meant the allocation process in `Create()` and `Update()`.

Take `Create()` for example, please see:
https://github.com/kubernetes/kubernetes/blob/v1.7.2/pkg/registry/core/service/rest.go#L119-L191

There is a defer for common NodePorts in [L120](https://github.com/kubernetes/kubernetes/blob/v1.7.2/pkg/registry/core/service/rest.go#L120):
```go
defer nodePortOp.Finish()
```

Once [CreateService at L178](https://github.com/kubernetes/kubernetes/blob/v1.7.2/pkg/registry/core/service/rest.go#L178) fails, the above defer will finally exec. Then the allocated NodePorts will _**roll-back**_, i.e. these NodePorts will be released.

But the HealthCheck NodePort allocation process doesn't use this roll-back. This will lead to leak.

I run a simple test and see the HealthCheck NodePort leak. Will paste the result later.

**Comment by xiangpengzhao** [comment]
Testing service manifest, `lb.yaml`.
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: LoadBalancer
  ports:
  - port: 53
    name: port-tcp
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  externalTrafficPolicy: Local
  healthCheckNodePort: 32222
  selector:
    bar: baz
```

1. Add some simple testing code. See: [compare](https://github.com/kubernetes/kubernetes/compare/master...xiangpengzhao:fix-hcnp). Note that I add this error intentionally:
```go
err = fmt.Errorf("Testing HealthCheck NodePort leak")
```

2. Run kube-apiserver with flag `--feature-gates=AllowExtTrafficLocalEndpoints=true`.

3. `kubectl create -f lb.yaml`. We will get below output. This is expected.
```
I0803 11:56:02.383466   13073 rest.go:501] Reserved user requested nodePort: 32222
E0803 11:56:02.385599   13073 rest.go:148] Testing HealthCheck NodePort leak
E0803 11:56:02.388186   13073 status.go:62] apiserver received an error that is not an metav1.Status: Testing HealthCheck NodePort leak
Error from server: error when creating "lb.yaml": Testing HealthCheck NodePort leak
```

4. `kubectl create -f lb.yaml` again. We will get below output. Note the error `Internal error occurred: failed to allocate requested HealthCheck NodePort 32222: provided port is already allocated`. That means that when creating service fails at step 3, the NodePort and HealthCheck NodePort should be both released, but the `HealthCheck NodePort` was NOT.

```
E0803 11:56:18.668867   13073 rest.go:98] service.Spec.HealthCheckNodePort: 32222 has been allocated
Error from server (InternalError): error when creating "lb.yaml": Internal error occurred: failed to allocate requested HealthCheck NodePort 32222: provided port is already allocated
```

**Comment by xiangpengzhao** [comment]
Fortunately, several minute later, the leak was repaired and cleaned up.

```
E0803 11:58:51.982984   13073 repair.go:133] the node port 31111 for service foo/default is not allocated; repairing
E0803 11:58:51.983081   13073 repair.go:160] the node port 32222 may have leaked: flagging for later clean up
E0803 11:58:51.983807   13073 repair.go:150] the cluster IP 192.168.3.251 for service foo/default is not allocated; repairing
E0803 12:04:51.997857   13073 repair.go:171] the node port 32222 appears to have leaked: cleaning up
```

But anyway, we should release the HealthCheck NodePort when `CreateService` fails. We shouldn't depend on the later repair.

**Comment by MrHohn** [comment]
@xiangpengzhao Thanks for tracing down, sent #50116 for fixing.

**Comment by cihangirbesiktas** [comment]
We're having this issue on service deletion. It looks like healthcheck nodeport is not deallocated immediately when deleting the service.

This is causing issues for backup and restore of services with heathcheck node port.
