### ISSUE TITLE
cinder volumes not being detached

### ISSUE THREAD

**Issue by ralberto** [kubernetes/kubernetes#50004]
/kind bug

**What happened**:
I've been using kubernetes 1.5.2 and docker 1.12.6 without any major problems. However, after upgrading to kubernetes version 1.7.2 volumes remain attached to nodes when they became unavailable (powered off), preventing the volume from being attached to another node.

According to the logs on master nodes, kubernetes is trying to detach the volume, but an error occurs (Error: Volume not attached according to node status for volume ...). Relevant log message follows:

`Operation for "\"kubernetes.io/cinder/5cfe60d7-0b82-4933-9e69-aeb2cbd2521d\"" failed. No retries permitted until 2017-08-01 17:53:01.154312563 +0100 WEST (durationBeforeRetry 32s). Error: Volume not attached according to node status for volume "pvc-21b92fac-76d5-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/5cfe60d7-0b82-4933-9e69-aeb2cbd2521d") pod "smartiot-kafka-0" (UID: "bac7a5a8-76d9-11e7-90b6-fa163e4b4ca8")
Aug 01 17:52:35 smartiot-node1.c.ptin.corppt.com kubelet[1146]: W0801 `

The volume remains attached to the unavaiable node, because kubernetes fails to mount the volume in another node, with the error: (Multi-Attach error for volume <volume-id>....). Accesing openstack console I can also confirm the the given volume remains attached to the unavailable node.

**What you expected to happen**:
Volumes attached to unavailable nodes being detached, so they can be attached to available nodes.  

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod that claims a persistent volume using the cinder volume plugin.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
Openstack Mitaka
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
- Kernel (e.g. `uname -a`):
Linux node1 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jingxu97** [comment]
@ralberto  Thanks for reporting the issue. Could you share us your full controller-manager log so that we could check the issue?
Also did it happen during upgrading to 1.7?

**Comment by ralberto** [comment]
Hi @jingxu97,
I've removed version 1.5.2 and installed 1.7.2 from scratch. (no migrations whatsoever)

Here's the controller-manager logs after shutting down the node with the attached volume.

<pre>
I0803 09:42:18.099080       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"smartiot-worker3", UID:"7514afae-782b-11e7-a33d-fa163e9971f4", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node smartiot-worker3 status is now: NodeNotReady
I0803 09:42:18.250736       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"smartiot-worker3", UID:"7514afae-782b-11e7-a33d-fa163e9971f4", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node smartiot-worker3 event: Deleting Node smartiot-worker3 because it's not present according to cloud provider
I0803 09:42:18.339373       1 attach_detach_controller.go:465] error removing node "smartiot-worker3" from desired-state-of-world: failed to delete node "smartiot-worker3" from list of nodes managed by attach/detach controller--the node still contains 1 volumes in its list of volumes to attach
E0803 09:42:18.587552       1 operation_generator.go:161] VolumesAreAttached failed for checking on node "smartiot-worker3" with: Failed to find object
I0803 09:42:23.250201       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"smartiot-worker3", UID:"7514afae-782b-11e7-a33d-fa163e9971f4", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node smartiot-worker3 event: Removing Node smartiot-worker3 from NodeController
I0803 09:42:23.473512       1 gc_controller.go:62] PodGC is force deleting Pod: default:test-3642784874-cxgqw
I0803 09:42:23.528677       1 gc_controller.go:166] Forced deletion of orphaned Pod test-3642784874-cxgqw succeeded
I0803 09:42:23.528718       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-proxy-amd64-0wb9p
I0803 09:42:23.543907       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"test-3642784874", UID:"45bccae7-782f-11e7-90b6-fa163e4b4ca8", APIVersion:"extensions", ResourceVersion:"424256", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: test-3642784874-lzxs4
I0803 09:42:23.596275       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-proxy-amd64-0wb9p succeeded
W0803 09:42:23.629743       1 reconciler.go:262] Multi-Attach error for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae") from node "smartiot-worker2" Volume is already exclusively attached to one node and can't be attached to another
I0803 09:42:23.632897       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"test-3642784874-lzxs4", UID:"0d51a2ea-7830-11e7-90b6-fa163e4b4ca8", APIVersion:"v1", ResourceVersion:"424273", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" Volume is already exclusively attached to one node and can't be attached to another
W0803 09:42:23.733146       1 reconciler.go:262] Multi-Attach error for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae") from node "smartiot-worker2" Volume is already exclusively attached to one node and can't be attached to another
I0803 09:42:23.733930       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"test-3642784874-lzxs4", UID:"0d51a2ea-7830-11e7-90b6-fa163e4b4ca8", APIVersion:"v1", ResourceVersion:"424273", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" Volume is already exclusively attached to one node and can't be attached to another
</pre>

After detaching the volume using openstack API, eventually the volume is attached to another node. Here's the controller-manager logs after detaching the volume.
<pre>
...
I0803 10:13:15.483366       1 attacher.go:157] Attach volume "6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae" to instance "5c9d8736-7337-403f-bc36-cba9a9de6095" failed with: volume kubernetes-dynamic-pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8 status is in-use, not available, can not be attached to instance 5c9d8736-7337-403f-bc36-cba9a9de6095.
E0803 10:13:15.485148       1 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae\"" failed. No retries permitted until 2017-08-03 10:15:17.485066456 +0000 UTC (durationBeforeRetry 2m2s). Error: AttachVolume.Attach failed for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae") from node "smartiot-worker2" : volume kubernetes-dynamic-pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8 status is in-use, not available, can not be attached to instance 5c9d8736-7337-403f-bc36-cba9a9de6095.
I0803 10:13:15.489311       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"test-3642784874-lzxs4", UID:"0d51a2ea-7830-11e7-90b6-fa163e4b4ca8", APIVersion:"v1", ResourceVersion:"424273", FieldPath:""}): type: 'Warning' reason: 'FailedMount' AttachVolume.Attach failed for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" : volume kubernetes-dynamic-pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8 status is in-use, not available, can not be attached to instance 5c9d8736-7337-403f-bc36-cba9a9de6095.
W0803 10:14:47.161253       1 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1beta1.ThirdPartyResource ended with: etcdserver: mvcc: required revision has been compacted
I0803 10:15:17.570260       1 reconciler.go:272] attacherDetacher.AttachVolume started for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae") from node "smartiot-worker2" 
I0803 10:15:22.124153       1 attacher.go:155] Attach operation successful: volume "6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae" attached to instance "5c9d8736-7337-403f-bc36-cba9a9de6095".
I0803 10:15:22.330735       1 operation_generator.go:271] AttachVolume.Attach succeeded for volume "pvc-8f03879b-782e-11e7-90b6-fa163e4b4ca8" (UniqueName: "kubernetes.io/cinder/6ea2a8c7-08cf-4996-a2e2-31d5bc98a3ae") from node "smartiot-worker2"
</pre>

**Comment by ralberto** [comment]
Here's the logs of the other two controller-managers.
<pre>
I0803 08:50:31.368864       1 controllermanager.go:107] Version: v1.7.2
I0803 08:50:31.375120       1 leaderelection.go:179] attempting to acquire leader lease...
</pre>

They remain blocked infinitely. I don't see the symptoms described in this issue #49000, i.e. kubectl responses are fast and resource creation is also usually fast.

**Comment by jingxu97** [comment]
@ralberto thanks for the information. Is that ok you could share with us the full controller log? You could email me jinxu at google.com if you prefer. Are you using deployment or something else for creating the pod?

**Comment by ralberto** [comment]
Hi @jingxu97,
I've recorded a session in a text file reproducing the problem. In [this file](https://github.com/kubernetes/kubernetes/files/1200204/session.log.gz) you can find the requested logs, how the pod was created, etc... 
If you need more details, please let me know.
Thanks.

**Comment by jingxu97** [comment]
@ralberto sorry for the late reply. I think this issue is related to #50266, and we have PR to fix it

**Comment by ralberto** [comment]
Hi.
Any progress on this issue? Release 1.7.5 resolved issues #50266 and  #50200, however I've validated that this problem remains in version 1.7.5.

Thanks.

**Comment by jingxu97** [comment]
@ralberto do you have the master log during the issue happened so I can take a look? Thank you! 

Normally when nodes powered off, node will be marked as NotReady. Pods are deleted from the node. Detach should happen after 6 minutes timeout so that volume could be attached to new node after that. 
I also wondered you mentioned that older version of kubernetes works fine. But do you notice whether the detach and attach happen quickly or after some minutes?

**Comment by ralberto** [comment]
@jingxu97 thanks for your answer.
After shutting down the node, the volume remains attached to the unavailable node indefinitely, it's not detached even after a long period... 
You can find the logs that I've recorded in the past in this URL: https://github.com/kubernetes/kubernetes/files/1200204/session.log.gz

Anyway, I'm going to reinstall the cluster from scratch using kubernetes latest version and try to reproduce the problem again.  I'll give you feedback. 

Thanks.

**Comment by ralberto** [comment]
I've deployed a kubernetes cluster using version 1.8.0 and verified that the problem remains. Here's the 
[controll-manager logs](https://github.com/kubernetes/kubernetes/files/1372614/cmanager.zip).

Here's what I've done.
- Created a cluster with 3 masters (smartiot-node1; smartiot-node2; smartiot-node3) and 3 worker nodes (smartiot-worker1; smartiot-worker2; smartiot-worker3).
- Deployed a pod, with a persistent volume claim. The pod was started at smartiot-worker1, and  consequently the volume was attached to smartiot-worker1.
- Shutdown smartiot-worker1
- Kubernetes moved the pod to smartiot-worker2, but fails to attach the volume to instance smartiot-worker2 because it remains attached to smartiot-worker1 indefinitely.

Looking in the logs, there's a line at timestamp  14:53:42.155253, saying that the volume is no longer attached to smartiot-worker1. However the volume remains attached to smartiot-worker1.

**Comment by stamak** [comment]
the same with k8s 1.8.2
Very easy to reproduce

Logs

```
  Warning  FailedMount            2m (x11 over 8m)  attachdetach                                        AttachVolume.Attach failed for volume "pvc-6fba6aa6-c470-11e7-9fa8-fa163ec1e2e4" : Disk c51375f7-0321-4db1-8795-080571ed0654 is attached to a different instance (846acb96-d6f2-4fe6-a197-c4c1d923e5f2)
```

**Comment by edisonxiang** [comment]
Hey @jingxu97 @ralberto @stamak, I have an idea about this issue. When the problem happens, the volume is actually in used and is attached to the unavailable node in OpenStack Cinder's database . So we can execute `Volume Detach ` when `cloudprovider.InstanceNotFound` is hit in the `VolumesAreAttached ` function. I am not sure it works. So what's your opinion?

**Comment by dims** [comment]
cc @FengyunPan

**Comment by FengyunPan** [comment]
Sorry for the delay.
IMO, I have fixed this issue in cloud provider, the logic of attach_detach_controller attachs volume and detachs volume regularly. When attach_detach_controller attachs volume before detach volume, we will get "Warning  FailedMount". And when attach_detach_controller have do a detach, but the status of volume is detaching, we also get "Warning  FailedMount".

OTH, we should do same improves for attach_detach_controller, we should wait for the volume to be detached. I will check it later.

**Comment by zetaab** [comment]
@FengyunPan imo this integration with openstack was better before you "fixed" it.

**Comment by h4ckroot** [comment]
Hello, Do we have any update on this please ?
