### ISSUE TITLE
k8s-oidc-helper does not work

### ISSUE THREAD

**Issue by spnzig** [kubernetes/kubernetes#50002]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: 
I have installed kubernetes with kubeadm on 2 VMs running ubuntu 16.04. NOw i am trying to configure OIDC with it. So i tried installing the k8s-oidc-helper package using go. But unfortunately there seems to be some issue and i cant run any commands with it. 

**What you expected to happen**:
k8s-oidc-helper package should work and give the required parameters

**How to reproduce it (as minimally and precisely as possible)**:
```
sudo apt install golang-go
go get github.com/micahhausler/k8s-oidc-helper
k8s-oidc-helper --version
k8s-oidc-helper: command not found


```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.2
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): UBUNTU 16.04lts
- Install tools: KUBEADM

**Comment by xiangpengzhao** [comment]
/sig auth

@spnzig This is not an issue of kubernetes. I suggest to check your $PATH. If the problem still exists, please check [k8s-oidc-helper README.md](https://github.com/micahhausler/k8s-oidc-helper/blob/master/README.md) for more info or create an issue in that repo.

:)

**Comment by spnzig** [comment]
@xiangpengzhao thanks for the link. I tried the same command but it gives command not found. I am new here. So could you suggest a right group where i can ask this question and get help? That would be really helpful

**Comment by xiangpengzhao** [comment]
I think @micahhausler the author of k8s-oidc-helper would be glad to help :)

**Comment by spnzig** [comment]
@xiangpengzhao thanks :)

**Comment by ericchiang** [comment]
k8s-oidc-helper is an external tool not maintained by the Kubernetes project.

It looks like you've opened an issue on that repo (https://github.com/micahhausler/k8s-oidc-helper/issues/3) so I'm going to close this one.
