### ISSUE TITLE
local volume Gid does not get reset after pod termination

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#50024]
k8s version v1.8.0-alpha.2.1149+8dc7cf1ebd4515-dirty

When POD which was using a local volume terminates and this POD was using a non-default Gid, after POD termination Gid of volume does not reset to default. It causes a problem when another POD tries to mount this local volume as volume still has stale Gid.
I would like to propose to reset Gid to 0 on unmount operation of a local volume.

/sig storage

**Comment by zhangxiaoyu-zidif** [comment]
The version is you build from master branch?
More details about env., config files are needed.
That would help reproduce it.=)
