### ISSUE TITLE
Allow spec.terminationGracePeriodSeconds to be used in downward API

### ISSUE THREAD

**Issue by rolftimmermans** [kubernetes/kubernetes#50032]
**Is this a BUG REPORT or FEATURE REQUEST?:**

/kind feature

**What happened**:
I was attempting to use `spec.terminationGracePeriodSeconds` with the downward API, but received an error message:

```Invalid value: "spec.terminationGracePeriodSeconds": error converting fieldPath: field label not supported: spec.terminationGracePeriodSeconds```

**What you expected to happen**:
I expect most/all of the attributes of the pod to be available via the downward API. 

**How to reproduce it (as minimally and precisely as possible)**:
Use the following in the pod spec.

```
env:
- name: TERMINATION_GRACE_PERIOD_SECONDS
  valueFrom:
    fieldRef:
      fieldPath: spec.terminationGracePeriodSeconds
```

**Anything else we need to know?**:
I realise this is currently not supported, but it would be nice if it was. It would be even nicer if every field could be used in the downward API, because I'm sure there are a lot of other scenarios that aren't possible.

**Environment**:
- Kubernetes version (use `kubectl version`):
client version 1.6.1
server version 1.7.2

- Cloud provider or hardware configuration**:
GCP

- OS (e.g. from /etc/os-release):
macOS

- Kernel (e.g. `uname -a`):
Darwin 16.7.0

**Comment by kanor1306** [comment]
That would be a really nice to have

**Comment by integrii** [comment]
Please reopen! /reopen

**Comment by Stono** [comment]
I would also love this.

**Comment by RochesterinNYC** [comment]
We (Spotify) would also like this/have a use case for it. We have some logic in our nginx Docker base images used here to enable graceful shutdowns for apps on K8s using this image. Some of the timing in the logic could be improved by having it take or calculate values based on the container/Pod's `terminationGracePeriodSeconds` (which we'd like to access as an env var in the container).

**Comment by stevesloka** [comment]
I had a need for this as well and almost have a PR together. Would folks be interested in that PR?
