### ISSUE TITLE
Strategic merge patch fails for custom resources with cryptic error

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#50037]
If you try to do a strategic merge patch on a custom resource, it fails with an error like:

```
Object 'Kind' is missing in '{"metadata":{"labels":{"even-odd":"even"}},"object":{"apiVersion":"myapp.ncdc.io/v1","color":"blue","kind":"Widget","metadata":{"clusterName":"","creationTimestamp":"2017-08-02T19:13:18Z","deletionGracePeriodSeconds":null,"deletionTimestamp":null,"name":"widget1","namespace":"myapp","resourceVersion":"316","selfLink":"/apis/myapp.ncdc.io/v1/namespaces/myapp/widgets/widget1","uid":"a468af6d-77b6-11e7-b287-001c4236e660"},"sides":2}}'
```

Because custom resources are decoded as `*unstructured.Unstructured`, and because we're missing the metadata about how to handle each field in a strategic merge patch, we can't easily do a strategic merge here. We should fail fast and return an error saying that we can't yet do strategic merge patches for custom resources / unstructured data.

/kind bug

@kubernetes/sig-api-machinery-bugs @deads2k

**Comment by ncdc** [comment]
@mml I think this is api machinery and not cli. The apiserver needs to see that it's getting unstructured data and return an error to the client. Right?

**Comment by ncdc** [comment]
Where the client is any http client, not just kubectl

**Comment by nikhita** [comment]
Created PR https://github.com/kubernetes/kubernetes/pull/53558.

**Comment by tamalsaha** [comment]
Hi,
I think there is still an issue left here, which is supporting StrategicPatch for CRDs. We are interested in using PATCH for parameter substitution as mentioned in @bgrant0607 's big doc https://docs.google.com/document/d/1cLPGweVEYrVqQvBLJg6sxV-TrE5Rm2MNOBA_cxZP2WU/edit#  .

I understand that there are technical challenges in supporting this. Given how popular CRDs are, it will be very weird if it does not support Strategic Patch.

cc: @bgrant0607

**Comment by nikhita** [comment]
@tamalsaha Just to clarify, you mean strategic merge patch for custom resources, right? i.e. the types defined by the CRD.
