### ISSUE TITLE
Local pv tests panicking

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#50043]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
[testgrid](https://k8s-testgrid.appspot.com/google-gce#gce-alpha-features)
[logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-alpha-features/13933)

```
I0802 21:12:24.694]     [91m[1mTest Panicked[0m
I0802 21:12:24.694]     [91mruntime error: invalid memory address or nil pointer dereference[0m
I0802 21:12:24.695]     /usr/local/go/src/runtime/panic.go:489
I0802 21:12:24.695] 
I0802 21:12:24.695]     [91mFull Stack Trace[0m
I0802 21:12:24.695]     	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0802 21:12:24.696]     k8s.io/kubernetes/test/e2e/storage.glob..func5.1()
I0802 21:12:24.696]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go:112 +0x2df
I0802 21:12:24.696]     k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4203bb080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0802 21:12:24.696]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:344 +0x219
I0802 21:12:24.696]     k8s.io/kubernetes/test/e2e.TestE2E(0xc4206b9ba0)
I0802 21:12:24.696]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:41 +0x2b
I0802 21:12:24.696]     testing.tRunner(0xc4206b9ba0, 0x35cadf0)
I0802 21:12:24.696]     	/usr/local/go/src/testing/testing.go:657 +0x96
I0802 21:12:24.697]     created by testing.(*T).Run
I0802 21:12:24.697]     	/usr/local/go/src/testing/testing.go:697 +0x2ca
```

**What you expected to happen**:
Test should pass

**Comment by msau42** [comment]
@ddysher can you take a look?

**Comment by msau42** [comment]
cc @sbezverk

**Comment by sbezverk** [comment]
This part looks a bit suspicious,  config var at this moment initialized properly, it is just a pointer to nil.
        var (
                config *localTestConfig
                node0  *v1.Node
                scName string
        )
Panic here is because I think points nowhere
                node0 = &config.nodes.Items[0]

Here is only where config gets instantiated.
                config = &localTestConfig{
                        ns:     f.Namespace.Name,
                        client: f.ClientSet,
                        nodes:  nodes,
                        node0:  node0,
                        scName: scName,
                }
@msau42 Am I on the right track here?

**Comment by msau42** [comment]
Yeah, looks like `node0` should not use `config`

**Comment by ddysher** [comment]
+1 we should just use nodes.Items[0]

wondering how this passed ci ...

**Comment by msau42** [comment]
It didn't :-)  See [testgrid](https://k8s-testgrid.appspot.com/google-gce#gce-alpha-features)

**Comment by ddysher** [comment]
hmm, ok

@sbezverk since u spotted the bug, do you want to put a PR for it?

**Comment by sbezverk** [comment]
if you can do it now, then please go ahead. otherwise I will do it tomorrow morning since it is already late on East Coast.

**Comment by ddysher** [comment]
I've created #50059, PTAL @sbezverk @msau42
