### ISSUE TITLE
Optimize the periodic API discovery of the garbage collector

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#50046]
Currently every 30s, the garbage collector pauses all its workers, invalidates its discovery cache,  re-discover the API, waits for all the informers to be synced (i.e., waits for informers finish initial LIST), then resumes working. The process is expensive, costs 10~30 seconds according to the logs of presubmit tests (https://github.com/kubernetes/kubernetes/issues/49966#issuecomment-319505816). 

Ideal mechanisms that won't make 1.8:
* One way to optimize it is to only redo the discovery if the API actually changes. After the ETag supports in https://github.com/kubernetes/kubernetes/pull/47353 gets accepted, every 30s, the garbage collector could query if the swagger spec has changed, and only continues the rediscovery if the apiserver indicates the client cache is stale.
  * Blocking issue: custom resource is not in the openapi https://github.com/kubernetes/kubernetes/issues/47426
* Or we can use the watchable discovery API (https://github.com/kubernetes/kubernetes/pull/45659, https://github.com/kubernetes/community/pull/617), but they are not going to be ready for 1.8

Temporary solution:
* similar to https://github.com/kubernetes/kubernetes/issues/49966#issuecomment-319681399, use another goroutine to periodically re-discover, and resets the garbage collector if there are changes.

**Comment by caesarxuchao** [comment]
The garbage collector don't care about the content of the openAPI spec, which is very large, it just needs to know if the openAPI spec has changed. Ideally, GC should send a HEAD request to the openAPI endpoint, and the server should just send back a header including the ETag.

As @apelisse pointed out, the openAPI [endpoint](https://github.com/kubernetes/kube-openapi/blob/master/pkg/handler/handler.go) doesn't support HEAD verb, we need to build that functionality. @mbohlool do you have suggestions?

**Comment by caesarxuchao** [comment]
Alternatively, we can use the watchable discovery API (https://github.com/kubernetes/kubernetes/pull/45659) if that gets in.

**Comment by caesarxuchao** [comment]
@ironcladlou it looks like we have to go with https://github.com/kubernetes/kubernetes/issues/49966#issuecomment-319681399. I updated the first comment to summarize why other methods don't work currently.

**Comment by ironcladlou** [comment]
https://github.com/kubernetes/kubernetes/issues/50046 should hopefully provide some improvement in the immediate future.

**Comment by mbohlool** [comment]
Looking at the code, OpenAPI endpoint should support `HEAD`. Have you guys tried it? I will give it a try.

**Comment by apelisse** [comment]
I haven't tried, but I agree with you after looking at the code. The documentation for `http.ServeContent` is not very explicit with that regard ...
