### ISSUE TITLE
PSP: User group with rolebinding to clusterrole cluster-admin can use any PSP

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#50057]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
User group/service account with rolebinding to clusterrole `cluster-admin` in a namespace can use any PSP.

**What you expected to happen**:

User group/service account with rolebinding to clusterrole `cluster-admin` in a namespace shall not use any PSP if there is no explicit clusterrolebinding/rolebinding that refer to clusterrole which defines to use the privileged PSP.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a PSP with `privileged` field set to `true`. And create a clusterrole to use that PSP.
2. Create namespace `demo`.
3. Create rolebinding which refers to clusterrole `cluster-admin` in namespace `demo`.
4. Create a pod with `default` service account in namespace `demo`. Enable `privileged` securityContext. There is no explicit clusterrolebinding/rolebinding that refer to clusterrole which defines to use the privileged PSP.

The pod still can be launched.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.2
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by php-coder** [comment]
Unfortunately, I don't fully understand your case but if you're creating a pod under user with `cluster-admin` role I'd expect that this user will be super privileged because this role "gives full control over every resource" (quote from doc: https://kubernetes.io/docs/admin/authorization/rbac/)

CC @pweil- @liggitt

**Comment by liggitt** [comment]
this is working as designed. the `cluster-admin` clusterrole is a superuser role that grants any verb (including `use`) on any resource (including `podsecuritypolicies`) at the scope where it is bound. The ability to use a PSP is checked within the namespace where the pod is being created (the query to the authorization layer is of the form "can user X `use` the resource `podsecuritypolicies` with name `policy-x` in namespace `somenamespace`") that means that user can make use of any PSP policy.

If you want a user to have broad but enumerated permissions within a namespace, the `admin` role would be a better selection.

**Comment by php-coder** [comment]
@liggitt Do we need to mention this in PSP documentation or we don't?

**Comment by liggitt** [comment]
sure, I will open a doc update PR to clarify

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/examples/pull/49/files
