### ISSUE TITLE
fluentd-elasticsearch deploy error

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#50056]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When deploying [https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch) addon, the fluentd pods start error because of image `gcr.io/google_containers/fluentd-elasticsearch:1.24` is missing.

**What you expected to happen**:

Start fluentd-elasticsearch pods normally.

**How to reproduce it (as minimally and precisely as possible)**:

```
cd cluster/addons/


**Suggestion to fix the problem**:

1. Build and push the 1.24 tag for the image `gcr.io/google_containers/fluentd-elasticsearch:1.24`
2. Or, use an old version of fluentd-elasticsearch image.

**Comment by feiskyer** [comment]
cc/ @coffeepac @crassirostris

**Comment by sebglon** [comment]
cc/ @aknuds1

**Comment by crassirostris** [comment]
Pushed it, my mistake, sorry!

**Comment by supereagle** [comment]
@feiskyer  I can pull the image `gcr.io/google_containers/fluentd-elasticsearch:1.24`. Is your network limited to access GCR? What about pulling this image through `docker pull`?

**Comment by supereagle** [comment]
@crassirostris  Have just pulled, it works. Thanks.

**Comment by feiskyer** [comment]
@crassirostris @supereagle It works now. Thanks.
