### ISSUE TITLE
Azure: configure the properties of load balancer endpoint through annotations

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#50062]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:
Right now, it's a manual process to update the exposed load balancer endpoint with DNS, NSG, and etc. It could be automated by cloud provider through annotations on service resource, for instance:
`azure.io.domainHost: foo` which will assign dns `foo.westus.cloudapp.azure.com`
likewise, if we have
<pre>
azure.io.nsg:
   name: foo
   access: allow
   sourceAddressPrefix: *
   targetPortRange: 80
</pre>
Then the nsg of the exposed IP will be configured properly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by weinong** [comment]
@jdumars @anhowe @brendandburns

**Comment by jdumars** [comment]
@weinong does this need to go into the SIG-Azure 1.10 backlog?

**Comment by khenidak** [comment]
So if the use case to have one service exposed with LB then 
1. add ```type: Load Balancer`` to the service annotation
2. add ```service.beta.kubernetes.io/azure-dns-label-name``` with your dns label to the service

if the use case is to have ingress controller with a DNS label, then the service that exposes the ingress controller to the LB should have the above.

if the use case is to have multiple ingress resources each have a DNS label then use [external DNS](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/azure.md)  project. The idea is each ingress resources carries an annotation for DNS label ```external-dns.alpha.kubernetes.io/hostname``` which a sub domain on your Azure DNS service.

Can you confirm that this covers the use cases you are looking for? @weinong

**Comment by dtzar** [comment]
@khenidak - Scenario 1 worked for me on a 1.9.1 K8s cluster.  Thanks!

**Comment by khenidak** [comment]
Please close the issue the. :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jdumars** [comment]
Closing, please feel free to re-open if this occurs again.

**Comment by dtzar** [comment]
For reference, I created this post which walks people through the scenario: http://ow.ly/Fqge30i1O0U
