### ISSUE TITLE
Can't delete pod

### ISSUE THREAD

**Issue by insoz** [kubernetes/kubernetes#50077]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When I delete the pod with yaml file

```
[root@localhost influxdb]# kubectl delete -f .
service "monitoring-grafana" deleted
serviceaccount "heapster" deleted
service "heapster" deleted
service "monitoring-influxdb" deleted
error when stopping "grafana.yaml": timed out waiting for the condition
error when stopping "heapster.yaml": timed out waiting for the condition
error when stopping "influxdb.yaml": timed out waiting for the condition
```

Aug  3 05:20:38 localhost journal: W0803 09:20:38.272696       1 cache.go:367] Couldn't expire cache for pod kube-system/monitoring-grafana-2495521324-r0gq3. Binding is still in progress.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

execute `kubectl delete -f .`, `kubectl create -f .` maybe 4 times

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
`24core, 64G MEM`
- OS (e.g. from /etc/os-release):
`CentOS7.3`
- Kernel (e.g. `uname -a`):
`Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`kubeadm`
- Others:

**Comment by insoz** [comment]
@yastij What shoud i do now ? I can't create or delete the pod. and execute `kubectl create/delete` is so slow...

**Comment by jianzhangbjz** [comment]
These pods running normal before deleting?

**Comment by insoz** [comment]
When I create the pods,  The result was syntax error. but look like the pods is still created.  
Then I repeat the create/delete about 4 times.

**Comment by insoz** [comment]
Before I modify the yaml file.  These pods running normal.

**Comment by jianzhangbjz** [comment]
> When I create the pods, The result was syntax error. but look like the pods is still created.

Can you post the error info and the yaml? Maybe this problem is here: "still created".

**Comment by k82cn** [comment]
Should be handled by https://github.com/kubernetes/kubernetes/pull/50106 .

**Comment by k82cn** [comment]
any feedback after apply  #50106 ?

**Comment by yastij** [comment]
@insoz - Is this still happening ?
