### ISSUE TITLE
Unable to get pod by filtering by its IP

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kubernetes#50075]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug
> /kind feature

**What happened**:
I was attempting to filter pods with a `fieldSelector` using client-go selecting by its `podIP`. I tried multiple variations until I ended up with `"status.podIP=<pod-ip>"`.
When filtering by `status.podIP=172.17.0.4`, list of pod(s) came back empty even if pod with the IP we are filtering by was running. Then I tried reproducing it by calling the Kubernetes API directly which had the same result, list of pods `items` came back empty:

```
$ curl http://localhost:8001/api/v1/namespaces/default/pods\?fieldSelector\=status.podIP\=172.17.0.4
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "21678"
  },
  "items": []
}%
```

**What you expected to happen**:
When passing the IP of the previously retrieved running Pod, I expected to get that Pod returned in the result.

**How to reproduce it (as minimally and precisely as possible)**:
- create a simple [pod](https://gist.github.com/LiliC/7f28482341e07fbf78673db2406db002), 
- get its IP (For example using `kubectl describe pods`
- `kubectl proxy`
- query Kubernetes: 
`curl http://localhost:8001/api/v1/namespaces/default/pods\?fieldSelector\=status.podIP\=<POD_IP>` 

**Anything else we need to know?**:
If I leave out the pod IP, I get all the pods back. I also tried using different formats when doing the curl, not one of them return anything. Also it seems like `status.podIP` field is [supported](https://github.com/kubernetes/kubernetes/issues/24657#issuecomment-282797258).
As a side note I retrieved the URL which I used from debugging which calls client-go made.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T05:21:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T10:17:58Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: minikube version: v0.20.0
- OS (e.g. from /etc/os-release):
minikube OS
```
NAME=Buildroot
VERSION=2017.02
ID=buildroot
VERSION_ID=2017.02
PRETTY_NAME="Buildroot 2017.02"
```
- Kernel (e.g. `uname -a`):
minikube kernel:
`Linux minikube 4.9.13 #1 SMP Fri Jun 16 20:55:02 UTC 2017 x86_64 GNU/Linux`
- Install tools: minikube
- Others:

**Comment by LiliC** [comment]
@kubernetes/sig-api-machinery

**Comment by LiliC** [comment]
@kubernetes/sig-api-machinery-bugs

/sig api-machinery

**Comment by dixudx** [comment]
@LiliC Currently the `fieldSelector` for `Pod` only support `metadata.name`, `metadata.namespace`, `spec.nodeName`, `spec.restartPolicy` and `status.phase`. I've already submitted a PR in #50091. PTAL.

**Comment by mml** [comment]
cc @caesarxuchao
