### ISSUE TITLE
Updates of running deployments fail with rpc error code = 2 (repository not found: does not exist or no pull access)

### ISSUE THREAD

**Issue by binaryreverse** [kubernetes/kubernetes#50086]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Hi. I am running a small Kubernetes cluster with a master and three nodes. We are developing a software which consists of many different services that communicate with each other. Those are built on a Jenkins CI server and deployed into a Docker image. 

I have set up a Kubernetes cluster to proceed further deployment, away from running the Docker images on the same VM as Jenkins. The Docker images are pushed from Jenkins to our private repository, a Nexus repository manager and from there pulled into the new Kubernetes cluster.

Now,  setting up a new deployment which pulls the initial image, works great. We do this like that:

`kubectl run <deployment-name> --image=<repo-name>/<image-name>:v1 --port=8080`

Right after this, I can see the successfully running deployment on our cluster:

```
kubectl get deployment 

NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment-name                 1         1         1            1           3h
```

The initial pull, with the specific Tag version (here v1) works. Now, when I am trying to "update" a deployment with a new version, this fails. The update command looks like this:

`kubectl set image deployments/<deployment-name> <deployment-name>=<repo-name>/<image-name>:v2`

This always fails with this error message:

`Failed to pull image "<image-name>": rpc error: code = 2 desc = Error response from daemon: {"message":"repository <repo-name> not found: does not exist or no pull access"}`

Well, what's strange here is that the repository name actually **is** valid, as we are able to pull successfully images from the Nexus repo in the initial step. Also, we ensured that the version, we want to update to, is available in the repository. It definitely is.  

We tried different approaches, including:

- Restarting the Docker service daemon
- Altering the repository path in many different variations
- Checking that our secret for the repo is valid

Nothing worked here. Obviously, there has to be a working connection with working secret credentials as we can pull the images and create deployments in the first step. 

**What you expected to happen**:
An update of the deployment based on a new image version from our Nexus repository.

**How to reproduce it (as minimally and precisely as possible)**:
1. Pulling an image from a repository, e.g.:
`kubectl run <deployment-name> --image=<repo>/<image>:v1 --port=8080`

2. Updating an deployment with a new image version:
`kubectl set image deployments/<deployment-name> <deployment-name>=<image-name>:v2`

**Environment**:
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration**:
Virtual machines on a high availability cluster (bare metal), running VMware

- OS (e.g. from /etc/os-release):
CentOS 7

- Kernel (e.g. `uname -a`):
`3.10.0-514.26.2.el7.x86_64 x86_64 GNU/Linux`

- Install tools:
Kubernetes repository from official documentation

- Others:

**Comment by binaryreverse** [comment]
This is resolved. Sorry for the unnecessary issue report. It was a classic typo, I missed the "v" for version in the version tag at the end of the image path, seems I accidentally deleted it when changing version numbers. 

Updates now work as expected.

**Comment by ramaswin121994** [comment]
I got same error. Can you please give me the step to resolve

**Comment by kojiDev** [comment]
I got this error. I was using private registry. I added secret as [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) says, and referenced it in `imagePullSecrets`.

I solved it by specifying server address as a prefix to an image:

from: 
```
containers:
      - name: "foo"
        image: "foo/bar:1.0.0"
```
to:
```
containers:
      - name: "foo"
        image: "myregistry.com/foo/bar:1.0.0"
```
