### ISSUE TITLE
Split the fuzzers by apigroup and move into their pkg/apis/<apigroup>/fuzzer package

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#50081]
In `pkg/api/testing/fuzzer.go` there is a `overrideGenericFuncs` function. We switched some of the apigroups (most are in `pkg/apis`) to have their own fuzzer/ package (e.g. `vendor/k8s.io/apiserver/pkg/apis/example/fuzzer/fuzzer.go`). The task would be to split the `pkg/api/testing/fuzzer.go` file up and create those fuzzer dirs in the `pkg/apis/<apigroup>/fuzzer`.

**Comment by mml** [comment]
cc @caesarxuchao
