### ISSUE TITLE
Need a general design for varying storage media and volumes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#5009]
From #4602 

I do want to offer a tmpfs EmptyDir.  The obvious thing to do is to add a
tmpfs plugin.  But WAIT.  It's identical to EmptyDir in pretty much every
way except a call to mount() instead of mkdir().  I expect that eventually
I will want a local SSD EmptyDir too - do I again fork it and just hardcode
the concept?  What about when phase change and NVM and whatever new space
age storage tech emerges?

And what about things like the GitRepo?  I want to make that go away, but
the replacement will need similar concepts.  Do I make N copies of that for
disk, SSD, NVM, PCM, quantum, etc?

Stick with me, I am going somewhere, I think.

In a sense, WHAT you store and WHERE you store it are orthogonal.  But not
REALLY because the full matrix doesn't make sense - we don't want to offer
secrets on disk, and what does it even mean to map PD or NFS or iscsi onto
tmpfs?  That's a nonsensical question.

In a sense, what you want to ask for is a QoS of storage or a set of
attributes that must be met.  For example secrets requires a volatile
storage medium, but it doesn't care much about perf.  Someone who cares
about perf might ask for IOPS > x or throughput > y MB/s.  It seems that an
API like:

``` json
    source: emptyDir{ requirements: [ "IOPS >= 1000" ]}
```

...is a better way to express performance.  This happens to be similar to
what @markturansky is pushing with pet storage, but I can't help but thing
that is TOO exact, and not good UX.  But if we HAD such an API, I would
argue that secret volumes are essentially hardcoded to "Volatile"
requirements.

So the question I offer is this: Is it worthwhile to take a swing at this
now, and implement secrets in terms of it?  Or should we punt on this and
just make a kubelet-global tmpfs (which we might want for other things
eventually) and then carve slices off of that for secrets?

I think the latter is probably more expedient but messier.  The former is
going to take longer, but has a better chance of lasting, IMO.

And then a second question: Is secrets really just a special case of
GitRepo, which is just a special case of "run this side-car container" ?
In other words, could we get rid of the secrets volume plugin and instead
just run a container which syncs some Secrets objects into files?  The
ServiceAccount tie-in makes me think maybe not, but i wanted to put it on
the table.

This is not a critical issue for Secrets - I am fine offering a tmpfs-centric solution for now and migrating to this once we have it.

There's also some overlap with the of plugin-wrapper plugins (e.g. secrets is literally a wrapper around an emptydir(medium=tmpfs) plugin instance).

Filing this issue so we can consider it independently.

**Comment by bgrant0607** [comment]
GitRepo should go away.

That leaves only EmptyDir. 

Other VolumeSources should be just that -- other sources.

**Comment by chrislovecnm** [comment]
@thockin @bgrant0607 with PetSet coming shortly this is going to become more of a challenge.  For instance gce persistent storage only does pd-standard ... and I need pd-ssd for C*

See https://github.com/kubernetes/kubernetes/issues/23525

**Comment by thockin** [comment]
petset leans on PersistentVolumes.  PV with paramaters is covered by the storage classes proposal (sorry, don't have a link on hand, look for PRs by one @pmorie)

**Comment by pmorie** [comment]
@chrislovecnm we recently added label selectors to PV claims.  there's also a porposal for storage classes and dynamic provisioning you might be interested in #26908

**Comment by endocrimes** [comment]
I think this issue is mostly solved by newer additions to kubernetes like storage classes, CSI, and dynamic provisioning - at least when it comes to classes of storage from within a source and not needing to maintain in-tree copies of volume management as storage technologies evolve.

I think because of that it makes sense to close this issue as a lot of the underlying need was solved in other ways.

/close
