### ISSUE TITLE
When using elbSecurityGroup cloudConfig with AWS, the sg's rules flap

### ISSUE THREAD

**Issue by rmt** [kubernetes/kubernetes#50105]
/kind bug

**What happened**:

When setting an elbSecurityGroup in cloud.config for AWS, and deploying multiple services with differing ports, then the security group rules flap in AWS, causing services to become inaccessible (only one will be correctly configured at a time).

**What you expected to happen**:

I expect that the configured elbSecurityGroup's rules will not be touched at all.  It must be pre-configured to permit access.  Alternatively, all ports for all services are queried and managed together.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

Most people are not running large clusters which may hit the AWS limits, so they won't use this option, nor see this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.1
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 4.10.13-1-ARCH
- Install tools: Custom
- Others:

**Comment by rmt** [comment]
/sig aws
@kubernetes/sig-aws

**Comment by nbutton23** [comment]
This is fixed by 
https://github.com/kubernetes/kubernetes/pull/49805
