### ISSUE TITLE
TaintExternalCloudProvider is removed before external cloud provider acts on it

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#50107]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We run KCM (Kubernetes Controller Manager) and kubelet with cloud-provider=external flag; CCM (Cloud Controller Manager) runs as a separate service. First it was noticed that this [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L275)  sometimes doesn't exercise. Happens because TaintExternalCloudProvider thats gets set when cloud-provider=external specified, gets reset before init is called on CCM.

@wlan0 
Here are the logs from KCM/APIServer/Kubelet/Scheduler
[logs.tar.gz](https://github.com/kubernetes/kubernetes/files/1198466/logs.tar.gz)

**What you expected to happen**:
TaintExternalCloudProvider should remain on the node till CCM resets it.

**How to reproduce it (as minimally and precisely as possible)**:
1) Start kubelet and KCM with cloud-provider=external. Do NOT start CCM. 
2) As no CCM is in the picture, TaintExternalCloudProvider should never be removed. Yet it happens.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.2
- Cloud provider or hardware configuration**: Rancher as an external Cloud Controller Manager
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wlan0** [comment]
/sig cluster-lifecycle

Thanks @alena1108 

cc @thockin @luxas
