### ISSUE TITLE
expose "KernelTunableWarn" in kublet config

### ISSUE THREAD

**Issue by jlzhao27** [kubernetes/kubernetes#50110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
We wanted to run kublets as part of our Circle CI integration tests, however, since circle VMs are lxc containers, `KernelTunableModify` or `KernelTunableError` will cause the kubelet to never be ready because the system settings do not match.

**What you expected to happen**:
If you manually compile the kubelet with `KernelTunableWarn` in `container_manager_linux.go`, then everything works correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Run a kubelet in a CI environment where root cannot modify `/proc/sys/*`

**Anything else we need to know?**:

**Environment**:
- CircleCI build node (Linux box299 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

my exact test environment used `minikube` with `vm-driver=none`, but I think running vanilla kubelets have the same issue (https://github.com/kubernetes/minikube#linux-ci-installation-which-supports-running-in-a-vm-example-w-kubectl-installation).

**Comment by jlz27** [comment]
@kubernetes/sig-node

**Comment by dims** [comment]
Here's the background https://github.com/kubernetes/kubernetes/pull/27874#r71256066

@vishh Here's the use case for kernel-tunable-behaviour to honor a "warn" option

**Comment by vishh** [comment]
`warn` sounds like `disable` to me. If kubelet cannot get the desired environment, it's functionalities/behavior is not guaranteed.

**Comment by ash211** [comment]
@vishh the goal here is to support running minikube with `--vm-driver=none` in integration tests in e.g. TravisCI and CircleCI, where in those environments root can't modify `/proc/sys/*`.  Exposing a flag on `kubelet` was mentioned as a followup TODO in the original PR introducing the config options at https://github.com/kubernetes/kubernetes/commit/0ec36ae2104c342ec3a68d7f138f069911227e20#diff-bb0391fb539757911b4d4b193cbf323aR145

Running anything other than `KernelTunableModify` would clearly not be recommended for production, but if it enables CI against kubernetes in TravisCI/CircleCI that would be very valuable for me in running Apache Spark's integration tests against minikube.

**Comment by vishh** [comment]
Ok. If it's test only, then I'm fine with exposing a config knob and
prefixing that with `test` string to make that clear.

**Comment by ryanmcnamara** [comment]
Any update?

**Comment by ryanmcnamara** [comment]
@vishh do you know if there is any workaround available for this?

**Comment by ryanmcnamara** [comment]
/remove-lifecycle stale

I do still care about this
@vishh do you know if there is any workaround available for this?

**Comment by vishh** [comment]
@ryanmcnamara I do not have cycles to post a patch for it, although I'm happy to review one.
