### ISSUE TITLE
Pods stuck with "Terminating" in an absent node

### ISSUE THREAD

**Issue by nutchalum** [kubernetes/kubernetes#50122]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Pods stuck with "Terminating" in an absent node.

**Systoms:**
Pods stuck with "Terminating" in an absent node after update cluster.

**Causes:**
I have a deployment with 3 pods (scaling).
Then I try to update an entire cluster from 1.6.3 to 1.6.7.

**Effects:**
One of them is fine, the rest is "Terminating" (from kubectl)
All of them are "Running" in dashboard with a label from an absent nodes.

**Diagnose:**
List my promblem pods (deployment)
```
kubectl get pods -n mynamespace

NAME                                READY     STATUS        RESTARTS   AGE
xxxxxxxxxxxxx-app-393156728-l0l0f   1/1       Terminating   0          18h
xxxxxxxxxxxxx-app-393156728-l17xt   1/1       Terminating   0          18h
xxxxxxxxxxxxx-app-393156728-nl1pr   1/1       Running       0          16h
```

Then I try to get log from one of "Terminating"
```
kubectl logs -n mynamespace xxxxxxxxxxxxx-app-393156728-l0l0f

Error from server (NotFound): nodes "ip-172-20-92-136.ap-southeast-1.compute.internal" not found
```

**First aid**
I try to scale down (from 3 to 0), the result were 2 Terminating pods.
I try to scale up (from 0 to 5), the result were 5 (3 fine, 2 broken) pods.
I try to exec sh into the pods, can't.
I try to force delete, nothing works
```
kubectl delete pod -n mynamespace xxxxxxxxxxxxx-app-393156728-l17xt --grace-period=0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "xxxxxxxxxxxxx-app-393156728-l17xt" deleted
```
The status is "deleted.", However it's still there.

I deleted a deployment, the fine pod's gone, the broken pods alive.

**What you expected to happen**:
The pods are healthy

**How to reproduce it (as minimally and precisely as possible)**:
No ideas, sorry.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.7
- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): GNU/Linux
- Install tools: kops
- Others: my kubectl version is 1.6.4 (in cluster kubectl is 1.6.7 if I ssh in to them).

**Comment by simsimon** [comment]
We got the exact same issue. 
We have pods which are not removed and stay in terminating status:
```
$ kubectl get pods

NAME                   READY     STATUS        RESTARTS   AGE
nginx-8586cf59-469jk   0/1       Terminating   0          1d
nginx-8586cf59-xggks   0/1       Terminating   0          1d
nginx-8586cf59-znblf   0/1       Terminating   0          1d
```

When we describe them we see following output:
```
$ kubectl describe pod nginx-8586cf59-469jk  

Name:                      nginx-8586cf59-469jk
Namespace:                 default
Node:                      codepipes-hafenkneipte-h9qrf/10.180.1.30
Start Time:                Tue, 23 Jan 2018 13:49:31 +0100
Labels:                    pod-template-hash=41427915
                           run=nginx
Annotations:               <none>
Status:                    Terminating (expires Thu, 25 Jan 2018 10:32:20 +0100)
Termination Grace Period:  0s
IP:                        198.19.11.3
Controlled By:             ReplicaSet/nginx-8586cf59
Containers:
  nginx:
    Container ID:   docker://ba2fe0b04ccbe3ee3ce07db0e07d6d652bfcf3202ea63f100db17e9e86f4ec61
    Image:          nginx
    Image ID:       docker-pullable://nginx@sha256:285b49d42c703fdf257d1e2422765c4ba9d3e37768d6ea83d7fe2043dad6e63d
    Port:           <none>
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-994h6 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-994h6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-994h6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>
```
We can try to delete it, no error message, but the pod will still be there:
```
$ kubectl delete pod nginx-8586cf59-469jk --grace-period=0 --force

warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "nginx-8586cf59-469jk" deleted
```
When we try to attach to it, like logging:
```
$ kubectl logs nginx-8586cf59-469jk

Error from server (NotFound): nodes "codepipes-hafenkneipte-h9qrf" not found
```

**Comment by mharrys** [comment]
Same problem on AKS 1.23.5. Pod stuck in Terminating on a node that no longer exist (node scale down) and cant be deleted with or without "--grace-period=0 --force". Historic pod logs collected indicate that pod shutdown successfully. Pod was started by CronJob.
