### ISSUE TITLE
all functions in cluster/common.sh could not work

### ISSUE THREAD

**Issue by rainmor** [kubernetes/kubernetes#50125]
### the pattern of all function names in the shell file cluster/common.sh is wrong

- when run any function , something wrong while be thrown like this
```
./../../cluster/centos/config-default.sh: line 37: `length-of': not a valid identifier
```
- these shell files has this problem:
```
cluster/common.sh
cluster/centos/config-default.sh
cluster/centos/util.sh
```

###  no one come to fix this?  so obvious problems?
@kubernetes/sig-cluster-ops-test-failures

**Comment by rainmor** [comment]
/sig cluster-ops
@kubernetes/sig-cluster-ops-test-failures

**Comment by waterings** [comment]
I got the same problem, and I think you are in the same situation with me .
use bash instead of sh to execute this shell.

/bin/bash  cluster/common.sh

**Comment by dims** [comment]
both cluster/centos/config-default.sh and cluster/common.sh specify `#!/bin/bash` . Anything else we can do to advertise this better?
