### ISSUE TITLE
SizeLimit violates k8s API convention

### ISSUE THREAD

**Issue by kyessenov** [kubernetes/kubernetes#50121]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: 
https://github.com/kubernetes/community/pull/306 added field `SizeLimit` in PR https://github.com/kubernetes/kubernetes/commit/85f030c2aad00c54d498646e4151e7fad930c7c3. The field is marked as _optional_ yet has the non-pointer type `resource.Quantity`. This is against the API convention that requires optional fields to be pointers. 

As a consequence, k8s client-go library does not omit this field in serialization, breaking k8s 1.6 compatibility for this API.

**What you expected to happen**:
client-go 1.7 works with k8s 1.6 in pass-through object processing pipeline.

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/kubernetes/client-go/issues/257#issuecomment-319552550

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @caesarxuchao

**Comment by kyessenov** [comment]
cc @andraxylia @jasonyoung

**Comment by kyessenov** [comment]
Please cherry-pick this into 1.7 since this might affect everyone who uses client-go 1.7 for this API.

**Comment by screeley44** [comment]
@kyessenov  @liggitt - does this apply to ALL optional api fields or just non-strings?  I'm not seeing many types holding this convention?  I'm asking in regards to another PR I'm about to do so wanting some clarification.  Thanks!

cc @msau42

**Comment by caesarxuchao** [comment]
IMO we don't have to fix every violations unless they break a use case. We need to strictly enforce the convention during our API reviews to prevent more violations.

**Comment by liggitt** [comment]
it's about go's ability to honor the `omitempty` directive on structs. we need to ensure that an unset (zero-value) field does not get included in the serialized API content

see https://play.golang.org/p/gEZoDu7LdG for the way go behaves with zero values

**Comment by kyessenov** [comment]
Sounds like it could be possible to detect this statically: if the field is marked as optional and omitempty, it should not serialize to a JSON field.

I can't tell if there are more violations like this one, I happened to discover this while using client-go 1.7 on 1.6 cluster.

**Comment by liggitt** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/51763

**Comment by mml** [comment]
FYI #44005 is a bug for a future API linting tool that would have caught this.
