### ISSUE TITLE
SQ blocked on verify-codgen

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#50154]
**BUG REPORT**: The submit queue is [broken on head](https://prow.k8s.io/?type=batch) do to [errors with hack/verfiy-codegen](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-verify/43356/). It fails after detecting the dif in versioned/clientset with the error message `vendor/k8s.io/kube-gen/hack/../test is out of date. Please run hack/update-codegen.sh`. Suspect that  #49370 may be the trigger if not the cause.

/kind bug

**Comment by kow3ns** [comment]
@sttts PTAL
/cc

**Comment by BenTheElder** [comment]
`pull-kubernetes-verify` seems to have been passing for a while now for batch jobs at least:
https://prow.k8s.io/?type=batch&job=pull-kubernetes-verify

**Comment by kow3ns** [comment]
@BenTheElder yeah because other PRs passed through the build queue and #49370 has merge conflict keeping it at bay.

**Comment by sttts** [comment]
Is this still the case? I just rebased one of my PRs to master and at least unit and verify are green.
