### ISSUE TITLE
azure disk client does not override polling duration

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#50152]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug Report
/kind bug

**What happened**: I created a PVC for a Managed Disk. It created very quickly. It took longer for the PV to show up. I suspect this is because we didn't override the poll duration like we do for some of the other clients: https://github.com/kubernetes/kubernetes/blob/8b30aaec39800616e8a8578d54222853689211c5/pkg/cloudprovider/providers/azure/azure.go#L271

Maybe consider changing the poll duration?

**What you expected to happen**: The PV to show up faster after the Disk was provisioned and visible in the Portal.

**How to reproduce it (as minimally and precisely as possible)**: Boot a 1.7.2 or higher, apply this Gist: https://gist.github.com/colemickens/0cd6a12fdbf5a8b5040724a0b8e900fd

**Anything else we need to know?**: N/a

**Environment**: Azure
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```
- Kernel (e.g. `uname -a`): `Linux colemick172-master-0 4.9.24-coreos #1 SMP Tue May 30 23:12:01 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux`
- Install tools: `tectonic-installer`

**Comment by colemickens** [comment]
/sig azure

cc: @brendanburns @anhowe @jdumars @khenidak @jackfrancis

**Comment by jdumars** [comment]
Adding to SIG Azure agenda for visibility

**Comment by khenidak** [comment]
@colemickens - Can you expand on " It took longer for the PV to show up." ? is it showing up on VM?

**Comment by khenidak** [comment]
Just to clarify why i asked, the "DiskClient" is used to create/delete disks. "VirtualMachineClient" is the one used for Attach/Detach (and that is where our time-to-complete-operation budget is mostly spent) and is currently configured with [poll](https://github.com/kubernetes/kubernetes/blob/8b30aaec39800616e8a8578d54222853689211c5/pkg/cloudprovider/providers/azure/azure.go#L251) every 5 sec

**Comment by jdumars** [comment]
Closing due to staleness.  If we need to re-open, please feel free to do so.
