### ISSUE TITLE
Aggregation fails to proxy API group if aggregated server is missing an OpenAPI spec

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#50165]
PR #48861 added in aggregation of the OpenAPI specifications for aggregated API servers.
Unfortunately, it assumes two things:

1. All aggregated API servers will have OpenAPI specifications
2. All OpenAPI specifications are static.

Neither of these assumptions hold for the custom metrics API.

Currently, the aggregator code will actually fail to register the proxy provider for the entire API group-version if it fails to fetch the OpenAPI spec.  Not having an OpenAPI spec doesn't prevent aggregation or discovery from working properly, so it shouldn't block the aggregator from working.

/kind bug
@kubernetes/sig-api-machinery-bugs 

/cc @mbohlool @deads2k @sttts

**Comment by DirectXMan12** [comment]
I've got a PR up, but it most likely breaks retries on fetching the OpenAPI spec, since it simply logs an error and continues on.  I'm not sure how we want to handle this.

**Comment by mbohlool** [comment]
not having an OpenAPI spec should not fail the aggregation, have you tried it?

**Comment by DirectXMan12** [comment]
yes, hence the PR ;-).  It returns an error fetching the OpenAPI spec, which causes the whole method which sets up the proxying for that group to fail, giving 404s when you actually try to hit, for example, `/apis/custom-metrics.metrics.k8s.io/v1alpha1/` and `/apis/custom-metrics.metrics.k8s.io/v1alpha1/namespaces/...`
