### ISSUE TITLE
TODO: remove deprecated ESIPP beta annotations in 1.8

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#50187]
[TODO: The beta annotations have been deprecated, remove them when we release k8s 1.8.](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/annotation_key_constants.go#L98)

As we are on the 1.8 train now, is it time to remove these deprecated annotations? I have already made the cleanup on my local branch. I can send a PR once I get the ticket :)

/kind cleanup
/sig network
/assign
/cc @MrHohn

**Comment by MrHohn** [comment]
@xiangpengzhao Thanks, I'd happy to review it :)

**Comment by xiangpengzhao** [comment]
@MrHohn PR #50224 sent :)
