### ISSUE TITLE
GPU resource validation incorrectly allows zero limits

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#50182]
The [validation logic](https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/api/v1/validation/validation.go#L49) for GPUs is not run if limits is not set for GPUs. 
We need to check limits equals requests even if just request is set for GPUs.

@jiayingz can you fix this bug? This may be a good starter bug in k8s.

**Comment by vishh** [comment]
@jiayingz it may be helpful to request a cherry pick for the bug fix into v1.7

**Comment by dixudx** [comment]
I'm working on this. See PR #50218.
