### ISSUE TITLE
set-image does not work when using a private repository with a newly pushed image

### ISSUE THREAD

**Issue by dmasters19** [kubernetes/kubernetes#50199]
@kubernetes/sig-AWS-bugs
> /bug

**What happened**:

When creating a deployment with a docker image that is hosted on a private repository, with an `imagePullSecret` that allows access to the private server, you are unable to update the image using the `set-image` command with a newly push docker image.

**What you expected to happen**:

You should be able to execute the command and have it update with a new docker image.

**How to reproduce it (as minimally and precisely as possible)**:

Push 2 versions of a docker image hosted on a private repository (dockerhub works) with the tags v1 and v2.  Create a kubectl secret which allows access to your dockerhub private repos.  Add this to the imagePullSecrets field.  Create a kubernetes deployment using the image with the v1 tag.  Now use the `kubectl set-image` command to update the image to the v2 tag.  This should also work.  Now build and push a *3rd* version to dockerhub with tag v3.  Attempt to update the image with the `set-image` command.  You will get an `ErrImgPull` and it won't work.

**Anything else we need to know?**:

- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration: AWS

**Comment by dmasters19** [comment]
I found a workaround from [#45487](https://github.com/kubernetes/kubernetes/issues/45487).  In your worker nodes, add a `.docker` directory to the `/root` directory.  Inside of it place a `config.json` file which will have the same contents as your `~/.docker/config.json` on your main machine (it will exist as long as you've run the `docker login` command at some point`.  Then edit the `kubelet.service` daemon file in `/lib/systemd/system` by adding `User=root`.  Then restart the `kubelet` service with `systemctl daemon-reload` and `systemctl restart kubelet`.

**Comment by redbaron** [comment]
what does error message say?

**Comment by eduardobcastro** [comment]
I'm having the same issue with version 1.15.0
This is the message:
`Failed to pull image "my_docker_hub_user/my_image:some_tag": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/my_docker_hub_user/my_image/manifests/some_tag: unauthorized: incorrect username or password`
