### ISSUE TITLE
k8s-ci-robot not allowing retest/test the failed CI jobs

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#50209]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind flake
/priority failing-test

**What happened**:

The k8s-ci-robot does not allow me to `/retest` or `/test pull-kubernetes-xxx`.

**What you expected to happen**:

Should works well as before

**How to reproduce it (as minimally and precisely as possible)**:
Affected PR:  #49454

**Comment by xiangpengzhao** [comment]
Seems like your PR needs a `/ok-to-test` from a member. See: https://github.com/kubernetes/test-infra/issues/3862

/cc @crimsonfaith91
