### ISSUE TITLE
DetachDisk should not fail if status is available in OpenStach volume

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#50207]
When detaching disk, if the volume status is already available, detach should return true instead of error. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L261

**Comment by FengyunPan** [comment]
Related to #50200

**Comment by FengyunPan** [comment]
Oops, sorry it is my mistake, I will file a PR to fix it soon.
