### ISSUE TITLE
the fluentd-elasticsearch:v2.0.0 and elasticsearch:v5.5.1-1 can't pull 

### ISSUE THREAD

**Issue by Bobi-zhou** [kubernetes/kubernetes#50221]
the image can't pull

gcr.io/google-containers/elasticsearch:v5.5.1-1
gcr.io/google-containers/fluentd-elasticsearch:v2.0.0

**Comment by crassirostris** [comment]
/sig instrumentation

@Bobi-zhou Thanks for reporting that! We don't have a mechanism currently to build those images automatically and I'm hesitant to build them not from master. Therefore, some delay will be present for now, especially when the merge happens on a weekend, sorry about that

Meanwhile, built and pushed
