### ISSUE TITLE
Token authentication inside a pod failed (unauthorized)

### ISSUE THREAD

**Issue by dmnord** [kubernetes/kubernetes#50226]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT (may be)

/kind bug
/sig auth

**What happened**:
I try to get access to kubernetes api to take a configuration inside a pod.
When I curl this query:
```
curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"  \
  https://kubernetes.default:443/api/v1/namespaces/rabbitmq/endpoints/rabbitmq
```
I receive an **Unauthorized** message:

This time I trying to rise an autocluster rabbitmq plugin in kubernetes environment.
This [post](https://github.com/rabbitmq/rabbitmq-autocluster/issues/41) may help you to understand the problem.

Also I use the next set of [receipts](https://github.com/rabbitmq/rabbitmq-autocluster/tree/master/examples/k8s_statefulsets) to rise a cluster

**What you expected to happen**:
I have to successfully get information from api-server via token and self-signed CA-certificate of my working k8s-cluster!

**How to reproduce it (as minimally and precisely as possible)**:
```
bash-4.4$ curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default:443/api/v1/namespaces/rabbitmq/endpoints/rabbitmq

*   Trying 10.100.0.1...
* TCP_NODELAY set
* Connected to kubernetes.default (10.100.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* ALPN, server accepted to use h2
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: E=root@infra.local,CN=kube-node02.infra.local,OU=System Service,O=A,L=B,ST=C,C=RU
* 	start date: Aug 03 12:57:28 2017 GMT
* 	expire date: Aug 03 12:57:28 2018 GMT
* 	common name: kube-node02.infra.local
* 	issuer: E=root@infra.local,CN=PrivateCA,OU=Root Service,O=A,L=B,ST=C,C=RU
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0xc083d05ff0)
> GET /api/v1/namespaces/rabbitmq/endpoints/rabbitmq HTTP/2
> Host: kubernetes.default
> User-Agent: curl/7.53.1
> Accept: */*
> Authorization: Bearer **TOKEN OMITTED** > 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 401 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 13
< date: Fri, 04 Aug 2017 13:05:18 GMT
< 
Unauthorized
* Connection #0 to host kubernetes.default left intact
bash-4.4$
```

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.7.2**
- Cloud provider or hardware configuration**: **none**
- OS (e.g. from /etc/os-release): Fedora release 25
- Kernel (e.g. `uname -a`): 4.11.12-200.fc25.x86_64

**Comment by dmnord** [comment]
How to generate a service account key file, which used to authenticate tokens? What parameters have to be in it for successfull work with tokens?

As I guess, It have to be a single unique file different from node key files.
Is it right?

I spoted, everytime when the query requests from api server using certificate from primary api server, i'm getting successfull result without Unauthorized!

**Comment by jordanwilson230** [comment]
@dmnord How did you resolve this?
