### ISSUE TITLE
fieldSelector does not return error for unsupported selector

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#50234]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I want to query all the pods with `status.qosClass=BestEffort` using `fieldSelector`.

```shell
$ curl http://172.17.8.101:8080/api/v1/namespaces/kube-system/pods?fieldSelector=status.qosClass=BestEffort
```
It returned,
```json
{
    "kind": "PodList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/api/v1/namespaces/kube-system/pods",
        "resourceVersion": "92474"
    },
    "items": []
}
```

It seems no pods matching `status.qosClass=BestEffort`. However, lots of pods are scheduled with `QoSClass=BestEffort`. The result is quite confusing and misleading.

**What you expected to happen**:
For such unsupported `fieldSelector`, should return something like this,
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "fieldSelector not supported: [xxx.xxx, xx.xx]",
    "reason": "BadRequest",
    "code": 400
}
```

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration**: Local
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mml** [comment]
cc @mml

We need to make sure we announce this in the release notes, because some people may have been depending on the old behavior, perhaps without knowing it.

**Comment by liggitt** [comment]
when I run that query, I get an error:
```
$ curl http://localhost:8080/api/v1/namespaces/kube-system/pods?fieldSelector=status.qosClass=BestEfort
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "field label not supported: status.qosClass",
  "reason": "BadRequest",
  "code": 400
}
```

**Comment by dixudx** [comment]
@liggitt Seems I gave a bad example.

Here is a new example.

```shell
# get the hostIP of pod "kube-apiserver-172.17.8.101"
$ kubectl get pods kube-apiserver-172.17.8.101 --namespace=kube-system -o go-template='{{ .status.hostIP }}'
172.17.8.101$ 

# use fieldSelector to query the pods whose hostIP is 172.17.8.101
$ curl http://172.17.8.101:8080/api/v1/namespaces/kube-system/pods?fieldSelector=status.hostIP=172.17.8.101
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/kube-system/pods",
    "resourceVersion": "269800"
  },
  "items": []
}$ 
```

**What we expect is to get the pods list or explicit bad request message like `field label not supported: status.hostIP`**, right?

***Current there is an inconsistent strategy on `fieldSelector`.***

https://github.com/kubernetes/kubernetes/blob/c16ff84e925ea56a8753bb0cd2650c8e9a71ff1c/pkg/api/v1/conversion.go#L156-L180

https://github.com/kubernetes/kubernetes/blob/c16ff84e925ea56a8753bb0cd2650c8e9a71ff1c/pkg/registry/core/pod/strategy.go#L232-L246

`AddFieldLabelConversionFunc` has a more wider scope than `PodToSelectableFields`. This inconsistency just result in such error.

**Comment by liggitt** [comment]
this was fixed in https://github.com/kubernetes/kubernetes/pull/55902/commits/34a7b3dea8739abfc113c4e42935289ac1e89d64 which moved the selectors for downwardAPI out of the field selector conversion function
