### ISSUE TITLE
[Flexvolume] consider add json option as parameter for init()

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#50232]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
According to [flexvolume doc](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md#init), the `init` phase dose not accept any parameter.

**What you expected to happen**:

In many cases, we want to do initialization work (for example, create a NFS mounter with given server URL) in this step based on given json options in volume spec. We hope to have a json option as parameter here.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by resouer** [comment]
Also, cc @saad-ali @jingxu97

**Comment by dixudx** [comment]
@resouer If no one is working on this, I would like to take it.

**Comment by resouer** [comment]
@dixudx The suggestions from sig-storage maintainers is expected here, before that, I'm afraid nothing we can do to help. It can even be by design.

**Comment by resouer** [comment]
After looking it deeper, it seems that every call of flexvolume binary is a fresh new call, so initialization in init() actually make no sense here. Will close this issue if my guess is right.
