### ISSUE TITLE
Add Cinder e2e tests

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#50246]
Right now we do not have any e2e tests for OpenStack, meaning that we can't be 100% sure that a PR doesn't introduce a regression (e.g. https://github.com/kubernetes/kubernetes/issues/47651). Ideally we would have access to a test OpenStack cluster, allowing us to test various external components such as Cinder.

This PR is just to collect feedback and possibly figure out what would be needed for this to be implemented. I remember hearing in a sig-storage meeting a few weeks ago about a CNCF cluster that might enable this, but wasn't too sure on the details.

/cc @NickrenREN @k8s-sig-openstack-proposals @k8s-mirror-storage-proposals

**Comment by NickrenREN** [comment]
Yeah, we really need this to test openstack related functions.
/cc @anguslees  @dims

**Comment by FengyunPan** [comment]
+1
/cc

**Comment by FengyunPan** [comment]
@dims I remember that @hogepodge have raised this issuse on slack.

**Comment by NickrenREN** [comment]
cc @zjj2wry

**Comment by jamiehannaford** [comment]
@dims @idvoretskyi @anguslees Does anybody know of any efforts that might enable this? I heard rumblings of some kind of OpenStack cluster for testing but don't know any details.

**Comment by dims** [comment]
cc @hogepodge

**Comment by hogepodge** [comment]
@jamiehannaford we're bringing a stable OpenStack cluster online that will be devoted to CICD to test OpenStack providers on. I'm expecting to have credentials for it in the next few weeks.

**Comment by jamiehannaford** [comment]
@hogepodge Awesome! Is there a tracking issue which covers that CI integration? (Just so I can subscribe.)

**Comment by dims** [comment]
cc @bugosiphionah
