### ISSUE TITLE
the fluentd-es cannot start

### ISSUE THREAD

**Issue by Bobi-zhou** [kubernetes/kubernetes#50242]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:

[root@node-21 EFK]# kubectl logs -f fluentd-es-jrsf7 -n kube-system
/var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsystemd.so.0': libgcrypt.so.11: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libsystemd.so': libsystemd.so: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so.0': libdw.so.1: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so': libsystemd-id128.so: cannot open shared object file: No such file or directory
	from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:48:in `<module:Native>'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:45:in `<module:Id128>'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:6:in `<module:Systemd>'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal/native.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:170:in `each'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:170:in `try_load_plugin'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:130:in `new_impl'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:55:in `new_input'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:154:in `add_source'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:95:in `block in configure'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:92:in `each'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:92:in `configure'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:129:in `configure'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:103:in `run_configure'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:489:in `run_configure'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:174:in `block in start'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `call'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `main_process'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:170:in `start'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'

**What you expected to happen**:
fluentd-es run success
**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f fluentd-es-ds.yaml

the image is google-containers/fluentd-elasticsearch:v2.0.0

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):centos 7.3
- Kernel (e.g. `uname -a`):Linux node-21.46 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
@crassirostris

**Comment by crassirostris** [comment]
@Bobi-zhou Yup, the situation with fluentd on the system with systemd is very sloppy. There's a hack to make it works sometimes, but it seems that it doesn't work. I'll look into it

**Comment by pranshuverma** [comment]
Facing same issue.

**Environment Details:**

`kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
`
OS (e.g. from /etc/os-release):Centos 7 (Core)

Kernel (e.g. uname -a): Linux xxxx 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Error for reference**
`
/var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsystemd.so.0': libgcrypt.so.11: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libsystemd.so': libsystemd.so: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so.0': libdw.so.1: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so': libsystemd-id128.so: cannot open shared object file: No such file or directory
        from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
        from /var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:48:in `<module:Native>'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:45:in `<module:Id128>'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:6:in `<module:Systemd>'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:3:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal/native.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:170:in `each'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:170:in `try_load_plugin'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:130:in `new_impl'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/plugin.rb:55:in `new_input'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:154:in `add_source'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:95:in `block in configure'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:92:in `each'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:92:in `configure'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:129:in `configure'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:103:in `run_configure'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:489:in `run_configure'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:174:in `block in start'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `call'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `main_process'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:170:in `start'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /var/lib/gems/2.1.0/gems/fluentd-0.12.39/bin/fluentd:5:in `<top (required)>'
        from /usr/local/bin/fluentd:23:in `load'
        from /usr/local/bin/fluentd:23:in `<main>'
`

**Comment by crassirostris** [comment]
@freeformz @Bobi-zhou You can solve it temporary by removing [`systemd` parts from the ConfigMap](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L272)

I'm working on the solution

**Comment by aknuds1** [comment]
A solution here might be to base fluentd-es off an image with journald supporting XZ and LZ4 compression. I'm looking :)

**Comment by crassirostris** [comment]
Thanks @aknuds1!
