### ISSUE TITLE
`kubectl explain <resource>` returns error for valid resource

### ISSUE THREAD

**Issue by tcharding** [kubernetes/kubernetes#50248]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
 
**What happened**:

Running `kubectl explain` (missing resource) outputs a list of valid resources for the command. However a number of these resources cause `kubectl explain` to throw an error.

**What you expected to happen**:

It would be nicer if the suggested list of valid resources all had documentation i.e no error returned when passing any resource from the list of valid resources to `kubectl explain`.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl explain clusters
error: API version: federation/v1beta1 is not supported by the server. Use one of: [authentication.k8s.io/v1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2alpha1 batch/v1 batch/v2alpha1 certificates.k8s.io/v1beta1 extensions/v1beta1 policy/v1beta1 rbac.authorization.k8s.io/v1beta1 rbac.authorization.k8s.io/v1alpha1 settings.k8s.io/v1alpha1 storage.k8s.io/v1beta1 storage.k8s.io/v1 apps/v1beta1 v1]
```
and also
```
kubectl explain all
the server doesn't have a resource type "all"
```
**Anything else we need to know?**:

I have implemented a test to catch the failing calls. Will submit PR once issue is raised.

**Environment**:
Bug present in master branch as well as in v1.6.4
```
$ kubectl version --short --client
Client Version: v1.6.4

$ _output/bin/kubectl version --short --client
Client Version: v1.8.0-alpha.2.1430+ae4fac416d60b3-dirty
```
Run against minikube instance
```
$ minikube version 
minikube version: v0.20.0
```

Os and kernel
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Linux eros 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zjj2wry** [comment]
```gvk, err = mapper.KindFor(groupResource.WithVersion(""))``` return ```no matches for {  all}```. how fix this?

**Comment by dharmeshkakadia** [comment]
How can we fix `kubectl explain all` ? It currently throws `the server doesn't have a resource type "all"`.
