### ISSUE TITLE
Mark volume as detached if instance is deleted from cloud provider.

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#50266]
Cloud provider volume has a function DiskIsAttached to check whether the volume is still attached to the instance. If the instance is no longer exist (deleted by cloud provider), we can safely assume that the volume is no longer attached to the instance and return false without error for DiskIsAttached(). Currently GCE PD and AWS has the correct behavior, but all other volume plugins do not.

**Comment by FengyunPan** [comment]
In order to be easier to review, I split it for every cloud provider.

**Comment by FengyunPan** [comment]
cinder plugin (openstack, rackspace): #50239

**Comment by FengyunPan** [comment]
Anyone can merge this PR:#50280?
