### ISSUE TITLE
[upgrade test failure] DNS should provide DNS for ExternalName services - IP not in range

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#50274]
This e2e test is failing on several of the upgrade tests.

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-master
https://k8s-testgrid.appspot.com/master-upgrade#gke-cvm-1.6-cvm-master-upgrade-master

/cc @kubernetes/sig-network-bugs 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:488
Expected error:
    <*errors.StatusError | 0xc4240b2c80>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "Service \"dns-test-service-3\" is invalid: spec.clusterIP: Invalid value: \"127.1.2.3\": provided IP is not in the valid range",
            Reason: "Invalid",
            Details: {
                Name: "dns-test-service-3",
                Group: "",
                Kind: "Service",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"127.1.2.3\": provided IP is not in the valid range",
                        Field: "spec.clusterIP",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    Service "dns-test-service-3" is invalid: spec.clusterIP: Invalid value: "127.1.2.3": provided IP is not in the valid range
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:477
```

**Comment by xiangpengzhao** [comment]
The upgrade tests you listed mean running 1.6/1.7 tests against master clusters, right?

#46197 was merged after 1.7. Before that PR, clusterIP is not respected when updating from service type ExternalName to type ClusterIP. After that PR, specified clusterIP will be allocated. The IP will be validated when allocating. In the failed tests, `127.1.2.3` is not in the valid clusterIP range of the testing clusters.

Maybe we should disable this test case in such upgrade tests?

/cc @thockin @freehan

**Comment by xiangpengzhao** [comment]
@ericchiang how to disable a test in upgrade tests?

**Comment by ericchiang** [comment]
@xiangpengzhao tried to check with #sig-release @pwittrock or @mbohlool any advice on this?

**Comment by ericchiang** [comment]
@xiangpengzhao would it be possible to modify the test to make it pick a valid clusterIP range?

**Comment by xiangpengzhao** [comment]
On HEAD, it already picks a valid clusterIP, but I don't how to modify in 1.7/1.6. Maybe by a cherry-pick but I don't know if we want to cherry-pick #46197.

**Comment by thockin** [comment]
If you can identify the patch that fixes the bug, we could backport.  Or we should disable that case.

**Comment by xiangpengzhao** [comment]
#46197. But it's somewhat large, I don't think we want to backport it.

One alternative is to send a small patch to change below IP to be another valid IP (although it's already a valid IP on HEAD). So we can have a small patch to backport and then we can cherry-pick it to 1.6/1.7. Tim, WDYT?

https://github.com/xiangpengzhao/kubernetes/blob/a58232ab418b303fc53a25651ac900da888d0e6c/test/e2e/dns.go#L474

**Comment by ericchiang** [comment]
This test started passing again on the upgrade tests. hmmm.

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster

**Comment by xiangpengzhao** [comment]
Hmmm, weird...

**Comment by mbohlool** [comment]
Can't find anything in the log explaining why it is not failing anymore. Only thing I can see from comparing two logs artifacts ([success](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/102/artifacts/), [failure](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/101/artifacts/)) is the name of sub directories (that I guess is related to notes running the test) is different (and less in success case). Maybe it has something to do with some config changes in running e2e tests.

**Comment by mbohlool** [comment]
also comparing image list of nodes.yaml files of those two [success](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/102/artifacts/nodes.yaml), [failure](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/101/artifacts/nodes.yaml) cases, the success case has way less images (only one actually). I wonder if some change disabled this (or many more) tests?

**Comment by mbohlool** [comment]
Any update on this? The test is still failing for at least gce-1.7-master-upgrade-master. Should the test being disabled for 1.7 and re-enabled in 1.8? @ericchiang @xiangpengzhao

**Comment by xiangpengzhao** [comment]
@mbohlool I take a look at the test failure of `gce-1.7-master-upgrade-master`. There is only one failure of `DNS should provide DNS for ExternalName services` (the test case associated with this issue) on 08.29 since 08.17.

The [failure ](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/167) is as below.  It's not the failure in this issue.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:488
Expected error:
    <*errors.errorString | 0xc4202458d0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:223
```

**Comment by xiangpengzhao** [comment]
As is mentioned in https://github.com/kubernetes/kubernetes/issues/51695#issuecomment-326430304 by @MrHohn , the original issue here might be caused by upgrade framework.

**Comment by dcbw** [comment]
@xiangpengzhao is this still regularly failing?  And is the actual issue the upgrade framework, or something actually DNS related?

**Comment by ericchiang** [comment]
Going to close since the test is back to green. Will re-open if we see more failures.

**Comment by xiangpengzhao** [comment]
>And is the actual issue the upgrade framework, or something actually DNS related?

Per discussion in #51695, I think it's the issue of upgrade framework.

**Comment by ericchiang** [comment]
This is popping up again in some of our other upgrade tests https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-parallel

Going to re-open for tracking. It sounds like this is still non-blocking though, so lowering the priority.

**Comment by xiangpengzhao** [comment]
/sig testing
/area test-infra

/assign @zmerlynn
as per #51695

**Comment by xiangpengzhao** [comment]
Found this in : https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/595?log#log

```
W0918 06:56:09.324] !!! Error in ./hack/ginkgo-e2e.sh:138
W0918 06:56:09.325]   Error in ./hack/ginkgo-e2e.sh:138. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gce-multizone="${MULTIZONE:-false}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --cloud-config-file="${CLOUD_CONFIG:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --federated-kube-context="${FEDERATION_KUBE_CONTEXT:-e2e-federation}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_CLEAN_START:+"--clean-start=true"} ${E2E_MIN_STARTUP_PODS:+"--minStartupPods=${E2E_MIN_STARTUP_PODS}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
W0918 06:56:09.325] Call stack:
W0918 06:56:09.325]   1: ./hack/ginkgo-e2e.sh:138 main(...)
W0918 06:56:09.325] Exiting with status 1
```

Not sure if this has something to do with the failure.

BTW, the below tests have exactly the same failure status when `[k8s.io] DNS should provide DNS for ExternalName services` fails.
* [k8s.io] CronJob should adopt Jobs it owns that don't have ControllerRef yet
* [k8s.io] Initializers should be invisible to controllers by default
* [k8s.io] PodPreset should create a pod preset
* [k8s.io] PodPreset should not modify the pod on conflict

So I think it's most likely an issue of the upgrade framework.

**Comment by zmerlynn** [comment]
/unassign

That's the normal error message from a Ginkgo test failure and has nothing to do with #51695, which has the failure signature of `detect-node-instance-groups: command not found`.

**Comment by apelisse** [comment]
@thockin @xiangpengzhao I'll track you guys as owners for this failure. Let's try to get it merged quickly. And let me know if you don't have time/power to fix that. Thanks

**Comment by MrHohn** [comment]
Upgrade framework is likely broke by https://github.com/kubernetes/kubernetes/pull/52582. Ref: https://github.com/kubernetes/kubernetes/pull/52582#issuecomment-330614277.

It is being fixed by https://github.com/kubernetes/kubernetes/pull/52743.

**Comment by xiangpengzhao** [comment]
ref: #52759

**Comment by dims** [comment]
@xiangpengzhao @ericchiang - #52759 does not seem to have v1.8 and this Issue seems to have v1.8, is there a disconnect? 

( cc @jdumars @kubernetes/sig-release-members )

**Comment by xiangpengzhao** [comment]
@dims I want #52759 to be in 1.8 milestone and be cherry-picked to 1.6/1.7.

**Comment by jdumars** [comment]
I added it to the 1.8 milestone, but it still needs approvals.  Contact @abgworrall about the 1.7.x cherry pick and @enisoc about 1.6.x

**Comment by xiangpengzhao** [comment]
Thanks @jdumars !

**Comment by xiangpengzhao** [comment]
https://github.com/kubernetes/kubernetes/pull/52804 merged, let's wait and see :)

**Comment by xiangpengzhao** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/630 is green!

**Comment by xiangpengzhao** [comment]
Unfortunately, gke-gci-1.7-gci-master-upgrade-cluster-parallel still fails after #52804 merged.

This test has a different clusterIP range `10.55.240.0/20`. cc @thockin @MrHohn 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/2071

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:488
Expected error:
    <*errors.StatusError | 0xc420a2c480>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "Service \"dns-test-service-3\" is invalid: spec.clusterIP: Invalid value: \"10.0.0.123\": provided IP is not in the valid range. The range of valid IPs is 10.55.240.0/20",
            Reason: "Invalid",
            Details: {
                Name: "dns-test-service-3",
                Group: "",
                Kind: "Service",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"10.0.0.123\": provided IP is not in the valid range. The range of valid IPs is 10.55.240.0/20",
                        Field: "spec.clusterIP",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    Service "dns-test-service-3" is invalid: spec.clusterIP: Invalid value: "10.0.0.123": provided IP is not in the valid range. The range of valid IPs is 10.55.240.0/20
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:477				
```

PS: #52693 helps provide the range info, it's really useful :)

**Comment by xiangpengzhao** [comment]
@thockin @MrHohn I send PR #52840 trying to fix this. PTAL. Thanks!

**Comment by ericchiang** [comment]
This is still failing on some 1.8 upgrade tests https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-gci-1.7-gci-1.8-upgrade-master

**Comment by krzyzacy** [comment]
do we need to cherrypick the fix into previous branches?

**Comment by MrHohn** [comment]
Sorry I forgot to update here.

https://github.com/kubernetes/kubernetes/pull/52875 is fixing the gke 1.7->1.8 upgrade cases.

I will send a similar fix to 1.6 branch to fix the 1.6->1.8 upgrade cases soon.

**Comment by MrHohn** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/53015 for 1.6 branch.

**Comment by MrHohn** [comment]
Both fixes are merged, I will observe the upgrade suites a bit longer before closing.

**Comment by MrHohn** [comment]
Test is passing now (on both 1.7->1.8 and 1.6->1.8, gce and gke). Closing this issue.

/close

**Comment by xiangpengzhao** [comment]
Awesome!
