### ISSUE TITLE
minor HPA documentation fix

### ISSUE THREAD

**Issue by vinayagg** [kubernetes/kubernetes#50270]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-autoscaling

**What happened**:
Documented commend does not work.

**What you expected to happen**:
Change to documentation required

**How to reproduce it (as minimally and precisely as possible)**:
on following page
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
the command 
`kubectl get hpa.autoscaling.v2alpha1 -o yaml > /tmp/hpa-v2.yaml`
should instead be
`kubectl get hpa.v2alpha1.autoscaling -o yaml > /tmp/hpa-v2.yaml`

**Anything else we need to know?**:
tagging @DirectXMan12 as discussed on slack

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vinayagg** [comment]
@kubernetes/sig-autoscaling

**Comment by xiangpengzhao** [comment]
/sig autoscaling
/kind documentation

@vinayagg could you please send a PR to fix it? Note: in the docs repo https://github.com/kubernetes/kubernetes.github.io

**Comment by Kenblair1226** [comment]
Fixed and merged.
/close

**Comment by xiangpengzhao** [comment]
@Kenblair1226 thanks for the fix!

/assign
/close
