### ISSUE TITLE
build/run.sh rsyncs .git directory, causing massive transfers

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#50272]
/kind bug

**What happened**:
After #46193 k8s master started rsyncing `.git` directory, causing hundreds of megabytes to be transferred, making some workflows that utilize remote docker engines impractical. E.g. I use [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) which can start docker-in-docker test cluster on the same remote docker where k8s is built, and currently my Internet connection can only give me about 1 Mb/s, so ~430Mb transfer caused by .git is impractical.

**What you expected to happen**:
`.git` is ignored as before, unless it's needed by the current script. In case `.git` is about to be `rsync`ed, a warning needs to be printed.

**How to reproduce it (as minimally and precisely as possible)**:
Just run `build/run.sh`. Doing so against a remote docker over slow(ish) Internet connection will make the behavior apparent.

**Anything else we need to know?**:
For now perhaps only `update-staging-godeps` script needs to rsync `.git` IIUC (see #46193).

**Environment**:
- Kubernetes version (use `kubectl version`):
654de23cbf821cd8b47387308de9a62aebb6df0d

I'll work on this issue.

**Comment by cblecker** [comment]
/assign @ivan4th
Feel free to ping for review when you have a PR :)
