### ISSUE TITLE
Should cadvisor API be protected

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#5028]
IRC user dagon_ was concerned that the cadvisor API is exposed and unprotected on his minions.  Should this API be protected?
- it appears to only be readonly and only have resource usage information
- however, exposing an unnecessary API without auth could still go against principle
- could it run on localhost?  It is in a pod, and there doesn't appear to be a way to have a pod use a port only on localhost.
- the pod config does not appear to setup basic auth for cadvisor.

**Comment by erictune** [comment]
@vmarmol

**Comment by erictune** [comment]
@vishh

**Comment by vmarmol** [comment]
cAdvisor does support basic auth although we don't set it up by default on cluster startup today. I'm working on running cAdvisor inside of Kubelet #4798 . We can secure it alongside the Kubelet in that case. Do we protect the Kubelet API today?

**Comment by erictune** [comment]
No, but we should.

**Comment by liggitt** [comment]
Cadvisor runs inside kubelet and does not need to expose its own API port.

**Comment by liggitt** [comment]
standalone cadvisor can be disabled, and access via the kubelet is protected
