### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by AliYmn** [kubernetes/kubernetes#50295]
Hi,

	>> kubectl get pods --all-namespaces | grep dashboard
	Result ;
	The connection to the server localhost:8080 was refused - did you specify the right host or port?

----

	>> kubectl create -f https://git.io/kube-dashboard

	Result ; 

	The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by xiangpengzhao** [comment]
Can you check if your kube-apiserver is running and insecure-port 8080 is enabled?

**Comment by AliYmn** [comment]
@xiangpengzhao No, no employee.

**Comment by xiangpengzhao** [comment]
It should be running. How do you setup your cluster?

**Comment by AliYmn** [comment]
root@ubuntu-512mb-nyc3-01:~$ lsof -i
	COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
	sshd       1527 root    3u  IPv4  15779      0t0  TCP *:ssh (LISTEN)
	sshd       1527 root    4u  IPv6  15788      0t0  TCP *:ssh (LISTEN)
	VBoxHeadl 15644 root   22u  IPv4  37266      0t0  TCP localhost:2222 (LISTEN)
	sshd      18809 root    3u  IPv4  42637      0t0  TCP 104.131.172.65:ssh->78.187.60.13.dynamic.ttnet.com.tr:63690 (ESTABLISHED)
	redis-ser 25193 root    4u  IPv6  56627      0t0  TCP *:6380 (LISTEN)
	redis-ser 25193 root    5u  IPv4  56628      0t0  TCP *:6380 (LISTEN)
	kubectl   31904 root    3u  IPv4  89722      0t0  TCP localhost:8001 (LISTEN)

**Comment by xiangpengzhao** [comment]
FYI: https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by joshualevy2** [comment]
I had this problem because there was no admin.conf file and I did not have KUBECONFIG=/root/admin.conf set.  the admin.conf file is created in /etc/kubernetes by the "kubeadmin init" command and you need to copy it to all your minion nodes.  kubeadmin does not do this for you.

**Comment by gkatsanos** [comment]
```~/D/p/i/server (master|✔) $ kubectl create -f wtf.yml                                                 16:34:07
W1128 16:34:09.944864   27487 factory_object_mapping.go:423] Failed to download OpenAPI (Get http://localhost:8080/swagger-2.0.0.pb-v1: dial tcp [::1]:8080: getsockopt: connection refused), falling back to swagger
The connection to the server localhost:8080 was refused - did you specify the right host or port?```

**Comment by Didd** [comment]
On my case this is happening due to a failing kubelet service('service kubelet status') and I had to do 'swapoff -a' to disable paging and swapping which fixed the problem. You can read about the "why" [here](https://askubuntu.com/questions/214805/how-do-i-disable-swap).

**Comment by MulticsYin** [comment]
Maybe you not set environment variables, try this:  
`export KUBERNETES_MASTER=http://MasterIP:8080`  
MasterIP was you kubernetes master IP

**Comment by clenk** [comment]
I had this problem because I was running kubectl as the wrong user. I had copied `/etc/kubernetes/admin.conf` to `.kube/config` in one user's home directory and needed to run kubectl as that user.

**Comment by moqichenle** [comment]
Run these commands solved this issue:
`mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config`

After running them, kubectl is working.

**Comment by fengerzh** [comment]
I don't understand, why this command must be run by normal user but not root user?

**Comment by Sam-Fireman** [comment]
Run these commands solved this issue:
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

After running them, kubectl is working.

**Comment by helloworlde** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

I tried by this solution on Ubuntu 18.04, but it still not work. At last I found it caused by Swap! So I fixed by disable swap like this:
```bash
sudo swapoff -a
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

**Comment by neolit123** [comment]
please try tools like kops or kubeadm that will handle all the setup for you.
they also print instructions in the terminal on how to setup admin.conf or pod-network-plugins.

closing this issue.
for similar questions try stackoverflow:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close

**Comment by jvleminc** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

I fixed it through sinilar commands:
https://github.com/kubernetes-sigs/kubespray/issues/1615#issuecomment-453118963

**Comment by HiMyFriend** [comment]
mkdir -p $HOME/.kube 
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
sudo chown $(id -u):$(id -g) $HOME/.kube/config

Mission complete!

**Comment by azoaib** [comment]
I am using docker-for-mac, got the same issue but restarting docker daemon solved the issue.

**Comment by soromamadou** [comment]
hello,
be sure to not run your command as root. You need to use user account

**Comment by avaslev** [comment]
If after running `sudo cp /etc/kubernetes/admin.conf $HOME/ && sudo chown $(id -u):$(id -g) $HOME/admin.conf` 
Command `kubectl config view` display like this:
```
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```
Running this command `unset KUBECONFIG` solved it.

**Comment by Tarvinder91** [comment]
> Maybe you not set environment variables, try this:
> `export KUBERNETES_MASTER=http://MasterIP:8080`
> MasterIP was you kubernetes master IP

Or in case your master is running on different port. Specify that port instead of 8080. 6433 in my case

**Comment by subeeshvasu** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

For me kubectl didn't work with the above commands, but, it worked after running the following export command on top the above ones.
export KUBECONFIG=$HOME/.kube/config

**Comment by bogere** [comment]
sometimes especially if you on Mac OS, just enable kubernetes on your Docker desktop for Mac.
Ensure that it is running , that is what i did to resolve the above error.
![Screenshot 2019-09-04 at 9 55 13 AM](https://user-images.githubusercontent.com/7900382/64236120-6bfae600-cf02-11e9-9213-75f9c1215711.png)

**Comment by Anuradha677** [comment]
I have found same issue.
gcloud container clusters get-credentials micro-cluster --zone us-central1-a
The issue is resolved.

**Comment by p8ul** [comment]
I experience this error after switching between projects & login. I solved the issue by running this command

```gcloud container clusters get-credentials --region your-region gke-us-east1-01```

**Comment by aescobar-icc** [comment]
thanks @p8ul, That solved my issue.

**Comment by zhangdavids** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

solved  :clap:

**Comment by nightswimmings** [comment]
This happened to me because of my .kube/config file having wrong indentations

**Comment by tnduy27** [comment]
I have the same problem and resolved completely. If you are using Ubuntu OS, please follow steps:
1. remove kubernetes if any: https://stackoverflow.com/questions/44884322/how-to-remove-kubectl-from-ubuntu-16-04-lts
2. Follow those steps in this: https://ubuntu.com/kubernetes/install

Thanks

**Comment by manishalankala** [comment]
> I had this problem because there was no admin.conf file and I did not have KUBECONFIG=/root/admin.conf set. the admin.conf file is created in /etc/kubernetes by the "kubeadmin init" command and you need to copy it to all your minion nodes. kubeadmin does not do this for you.

**Comment by seyfbarhoumi** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

Worked for me thanks

**Comment by saikrishna7586** [comment]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
This command I have to use in Master or Node because I'm getting error in Node 
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

**Comment by jecacs** [comment]
`cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
`

**Comment by codebyalokgupta** [comment]
If anyone using Docker Desktop on Mac then go to docker desktop preferences and enable Kubernetes. It is not enabled by default. It should show Kubernetes running, after that this should be resolved.

![Screenshot 2020-05-07 at 10 52 03 pm](https://user-images.githubusercontent.com/20811935/81348052-43d90d80-90b5-11ea-8d83-10b208ef9d34.png)

**Comment by hashimyousaf** [comment]
> If anyone using Docker Desktop on Mac then go to docker desktop preferences and enable Kubernetes. It is not enabled by default. It should show Kubernetes running, after that this should be resolved.
> 
> ![Screenshot 2020-05-07 at 10 52 03 pm](https://user-images.githubusercontent.com/20811935/81348052-43d90d80-90b5-11ea-8d83-10b208ef9d34.png)

Thanks, it solved my problem. :)

**Comment by bng-github** [comment]
1) **systemctl status kubelet** -> it should be runnning

2) **kubeadm reset** -> reset the kubeadm using this command
Your Kubernetes control-plane has initialized successfully!

3) Now try to RUN “**kubectl get pods**”

**Comment by moshinde** [comment]
I faced this issue when I installed kubectl with root and initialized kubernetes cluster with different user.
Using the same user resolved this issue

**Comment by ica10888** [comment]
Maybe there is a reason what caused this:
such like in some container, missing environment variable.
could excute follows command to set the environment variable
``` shell
export KUBECONFIG=/etc/kubernetes/admin.conf
```
`/etc/kubernetes/admin.conf` is volumes on the node master's same path.

**Comment by felipeschossler** [comment]
> I had this problem because there was no admin.conf file and I did not have KUBECONFIG=/root/admin.conf set. the admin.conf file is created in /etc/kubernetes by the "kubeadmin init" command and you need to copy it to all your minion nodes. kubeadmin does not do this for you.

I love you, so simple as that! :heart:

**Comment by ibrahiminui** [comment]
If you're using EKS, the error is due to the fact that kubectl isn't working yet. To do this, you need to use the command below

aws eks --region {region} update-kubeconfig --name {}cluster name}

**Comment by testbsstest** [comment]
> Run these commands solved this issue:
> `mkdir -p $HOME/.kube`
> `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`
> `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

Thank you. it works well 💯

**Comment by tyluRp** [comment]
For anyone who had this working but then it randomly stopped, I noticed that my environment variable was no longer set, below is how I resolved:

```bash
# check if env is set
echo $KUBECONFIG

# if it returns nothing, set env
export KUBECONFIG=~/.kube/<name of your config file>

# if you don't have that file to begin with, you might try copying it from master node
scp <user>@<master ip>:~/.kube/config ~/.kube/<name you want to give to config file>
```

**Comment by jamesfranklinnetsec** [comment]
> I had this problem because there was no admin.conf file and I did not have KUBECONFIG=/root/admin.conf set. the admin.conf file is created in /etc/kubernetes by the "kubeadmin init" command and you need to copy it to all your minion nodes. kubeadmin does not do this for you.

thanks this was my problem cheerio

**Comment by Hawaiideveloper** [comment]
Resolved:
---

"The connection to the server localhost:8080 was refused - did you specify the right host or port?"

I suggest clicking the link [here](https://github.com/Hawaiideveloper/Infastructure-as-Code-Sample_Env/issues/15#issuecomment-811377749)

**Comment by Yavdhesh** [comment]
For me I accidently installed kubectl and microk8s both. So, I uninstalled kubectl.
`microk8s.kubectl version ` <---- works fine now

**Comment by xyzkpz** [comment]
if you are getting like this goto this url [](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)
it will fix your errors... 
enjoy everyone

**Comment by kevinadhiguna** [comment]
> Run these commands solved this issue: `mkdir -p $HOME/.kube` `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config` `sudo chown $(id -u):$(id -g) $HOME/.kube/config`
> 
> After running them, kubectl is working.

Sadly I did not get it worked...
The second command gave me output :
`cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory`

Any help is appreciated

**Comment by preciousonyekwere** [comment]
> Run these commands solved this issue: mkdir -p $HOME/.kube sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config sudo chown $(id -u):$(id -g) $HOME/.kube/config
> 
> After running them, kubectl is working.

run this command as ubuntu user NOT root user if you have issues deploying on k8S

**Comment by Tebeye** [comment]
Hello, I am getting same error even I copied the configuration file from **/etc/kubernetes/admin.conf** 
Even I tried `export KUBERNETES_MASTER=http://MasterIP:8080`
Does anyone know another alternative to solve this problem?

**Comment by KalinIvanov-l** [comment]
> If anyone using Docker Desktop on Mac then go to docker desktop preferences and enable Kubernetes. It is not enabled by default. It should show Kubernetes running, after that this should be resolved.
> 
> ![Screenshot 2020-05-07 at 10 52 03 pm](https://user-images.githubusercontent.com/20811935/81348052-43d90d80-90b5-11ea-8d83-10b208ef9d34.png)

thanks, solved!
