### ISSUE TITLE
service controller should check loadbalancer before create

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#50299]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
pkg/controller/service/service_controller.go  func createLoadBalancerIfNeeded does not check existence of loadbalance before createLoadBalancer. 
**What you expected to happen**:
It is graceful to check existence of lb, only call createLoadBalancer when no lb found
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yastij** [comment]
cc @bowei

**Comment by yastij** [comment]
@hzxuzhonghu it does check LB existence, see: 

```go
	if !wantsLoadBalancer(service) {
		needDelete := true
		_, exists, err := s.balancer.GetLoadBalancer(s.clusterName, service)
		if err != nil {
			return fmt.Errorf("Error getting LB for service %s: %v", key, err), retryable
		}
		if !exists {
			needDelete = false
		}

		if needDelete {
			glog.Infof("Deleting existing load balancer for service %s that no longer needs a load balancer.", key)
			s.eventRecorder.Event(service, v1.EventTypeNormal, "DeletingLoadBalancer", "Deleting load balancer")
			if err := s.balancer.EnsureLoadBalancerDeleted(s.clusterName, service); err != nil {
				return err, retryable
			}
			s.eventRecorder.Event(service, v1.EventTypeNormal, "DeletedLoadBalancer", "Deleted load balancer")
		}

		newState = &v1.LoadBalancerStatus{}
	} 
```

**Comment by hzxuzhonghu** [comment]
@yastij  I mean in the else branch， 
before s.createLoadBalancer(service) should check LB ， if LB exist， no use to create, otherwise call create

**Comment by yastij** [comment]
@hzxuzhonghu - read it too fast, yup indeed I think it misses some check, waiting for @bowei confirmation

I'll also submit some simplification for the code above

**Comment by FengyunPan** [comment]
@hzxuzhonghu It has checked LB:https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L265

**Comment by yastij** [comment]
@hzxuzhonghu -  after closer look:
```go
func (s *ServiceController) createLoadBalancer(service *v1.Service) (*v1.LoadBalancerStatus, error) {
	nodes, err := s.nodeLister.ListWithPredicate(getNodeConditionPredicate())
	if err != nil {
		return nil, err
	}

	// - Only one protocol supported per service
	// - Not all cloud providers support all protocols and the next step is expected to return
	//   an error for unsupported protocols
	return s.balancer.EnsureLoadBalancer(s.clusterName, service, nodes)
}
```
from what i recall `#EnsureLoadBalancer()` still updates LB if one exists, so i think that it's okay, @bowei to you for confirmation

**Comment by hzxuzhonghu** [comment]
@yastij I think this may work more gracefully.
`else {
		glog.V(2).Infof("Ensuring LB for service %s", key)

		// Should check exist of LoadBalancer
		newState, exists, err = s.balancer.GetLoadBalancer(s.clusterName, service)
		if err != nil {
			return fmt.Errorf("Error getting LB for service %s: %v", key, err), retryable
		}
		if !exists {
			// The load balancer doesn't exist yet, so create it.
			s.eventRecorder.Event(service, v1.EventTypeNormal, "CreatingLoadBalancer", "Creating load balancer")
			newState, err = s.createLoadBalancer(service)
			if err != nil {
				return fmt.Errorf("Failed to create load balancer for service %s: %v", key, err), retryable
			}
			s.eventRecorder.Event(service, v1.EventTypeNormal, "CreatedLoadBalancer", "Created load balancer")
		}
	}`

**Comment by yastij** [comment]
@hzxuzhonghu - this might be called to process services updates. with this check we can't update LB if needed.

**Comment by hzxuzhonghu** [comment]
I know what you mean, I miss it .   This requires cloud provider  realize of EnsureLoadBalancer to do some more check.

**Comment by MrHohn** [comment]
+1 to what @yastij explained, codes seems correct to me.

@hzxuzhonghu Do you mind closing this issue?

**Comment by hzxuzhonghu** [comment]
@MrHohn Of course not, now all loadblancer cloud provider should do some logic in EnsureLoadBalancer

**Comment by MrHohn** [comment]
@hzxuzhonghu AFAIK that is the expected behavior defined on LoadBalancer interface, see https://github.com/kubernetes/kubernetes/blob/v1.7.3/pkg/cloudprovider/cloud.go#L92-L96.

**Comment by hzxuzhonghu** [comment]
I overlooked it

**Comment by yastij** [comment]
I think we should close this one.
