### ISSUE TITLE
Spurious whitespace in kubectl help output

### ISSUE THREAD

**Issue by tcharding** [kubernetes/kubernetes#50292]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Within the long description for `kubectl help <command>` environment variables are incorrectly rendered. Output for `kubectl help edit` contains `KUBE _EDITOR`. It should be rendered `KUBE_EDITOR` (without the spurious space).

**What you expected to happen**:

There should not be a space in between `KUBE` and `_EDITOR`.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl help edit`

**Anything else we need to know?**:

Relevant files:
 `k8s.io/kubernetes/pkg/kubectl/cmd/edit.go`
 `k8s.io/kubernetes/pkg/kubectl/cmd/templates/normalizers.go`

The long description is created using `LongDesc()` which calls `markdown()` which calls the blackfriday library like this

`formatted := blackfriday.Markdown(bytes, &ASCIIRenderer{Indentation: Indentation}, 0)`

The last parameter is for extensions. Passing `blackfriday.EXTENSION_NO_INTRA_EMPHASIS` should fix this issue however it does not. 

I have verified that this functionality works currently upstream. By verified I mean I verified that `EXTENSION_NO_INTRA_EMPHASIS` works as expected by testing the upstream `blackfriday` code, not that the upstream library fixes this issue.

**Going forward**:

I am opening this issue because I am not sure how to go forward from here. Two ideas are;

1. Check whether upgrading the `blackfriday` library fixes this issue. I have no idea how to do that, that is why I am raising the issue now. I am also not entirely sure on the implications of updating vendor libraries.

2. Isolate the bug in the `blackfriday` version we have and patch it.

Option one seems like less work but I do not entirely know the risks involved. I'm happy to keep working on this if someone please has some suggestions.

**Comment by tcharding** [comment]
My bad. Cheers @xiangpengzhao

**Comment by xiangpengzhao** [comment]
np. :smile:

**Comment by zjj2wry** [comment]
@tcharding i can normal work with ```KUBE_EDITOR="nano" kubectl edit svc/docker-registry```. how reappear？thanks

**Comment by tcharding** [comment]
@zjj2wry I don't completely understand your question. This is not a bug in program behavior it is a bug in documentation output.

**Comment by zjj2wry** [comment]
@tcharding got! 
```
The edit command allows you to directly edit any API resource you can retrieve via the command line tools. It will open
the editor defined by your KUBE _EDITOR, or EDITOR environment variables, or fall back to 'vi' for Linux or 'notepad'
for Windows. You can edit multiple objects, although changes are applied one at a time. The command accepts filena
```
this looks markdown apply ```_``` syntax. maybe we should not support ```_``` grammar for markdown.  i will create a PR to fix this, thank you very much : )

**Comment by tcharding** [comment]
There is an option in the current upstream version to not render `_` when within a string. I think the path forward is to verify that the upstream version functions correctly and doesn't break anything then update `vendor/`

**Comment by zjj2wry** [comment]
@tcharding not notice i updated the vendor file. after investigation，```_``` and ```*``` will
trigger emphasis marker. can you create PR disable ```_```. and update kubectl code ```_``` to ```*``` if exists.

**Comment by tcharding** [comment]
I've tracked this down to the `NormalText` function within the `ASCIIRenderer` type (our custom blackfriday markdown renderer).
```
// NormalText gets a text chunk *after* the markdown syntax was already
// processed and does a final cleanup on things we don't expect here, like
// removing linebreaks on things that are not a paragraph break (auto unwrap).
func (r *ASCIIRenderer) NormalText(out *bytes.Buffer, text []byte) {
	raw := string(text)
	lines := strings.Split(raw, linebreak)
	for _, line := range lines {
		trimmed := strings.Trim(line, " \n\t")
		out.WriteString(trimmed)
		out.WriteString(" ")
	}
}
```
Modifying `normalizers.go` to pass the extension `blackfriday.EXTENSION_NO_INTRA_EMPHASIS` into the call to `blackfriday.Markdown` still results in `KUBE_EDITOR` being passed to `NormalText` with a line break in the middle. This means, AFAICT, that we cannot implement `NormalText` as we would like.
```
func (s normalizer) markdown() normalizer {
	bytes := []byte(s.string)
	extenstion := blackfriday.EXTENSION_NO_INTRA_EMPHASIS
	formatted := blackfriday.Markdown(bytes, &ASCIIRenderer{Indentation: Indentation}, extension)
	s.string = string(formatted)
	return s
}
```

I have raised an issue upstream to investigate further.

https://github.com/spf13/cobra/issues/518

thanks

**Comment by tcharding** [comment]
Woops, the issue is with `blackfriday` not `cobra`. Original issue closed, new [issue](https://github.com/russross/blackfriday/issues/395) opened.

**Comment by tcharding** [comment]
[Response](https://github.com/russross/blackfriday/issues/395) from a dev at `blackfriday` says upgrading to `v2` may resolve this. Our current vendor-ed version of `blackfriday` is **very** out of date.  The upgrade is non-trivial, `Renderer` type has totally changed so the custom `ASCIIRenderer` will have to be totally re-written to move to `v2` of `blackfriday`. There are other vendor-ed libraries that rely on the current version of `blackfriday`, e.g `md2man`.

**Comment by tcharding** [comment]
Accidental close of issue, re-opened.

**Comment by CaoShuFeng** [comment]
@tcharding 
What's the situation of this issue?
