### ISSUE TITLE
Higher level image and deployment concepts in Kubernetes

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#503]
In Kubernetes, the reference from a container manifest to an image is a "name" - that name is arbitrary and it is up to the user to specific how that name interacts with their docker build and docker registry scenarios.  That includes ensuring that the name and label the user uses to refer to their image is not changed accidentally (so that new images aren't introduced outside of a controlled deployment process) and that the registry DNS that hosts the images is continuously available as long as that image may be needed (see [docker image discussions for how this might change](https://github.com/dotcloud/docker/issues/6805)).

That loose coupling is valuable for flexibility, but the lack of a concrete process leaves room for error and requires thought and control.  In addition, the resolution of those names is tightly bound to the execution of the container in the Kubelet.

We think there is value in Kubernetes providing a set of higher level concepts above pods/replication controllers that can be used to create deployable units of containers.  Two concepts we see as valuable are "builds" and "deployments" - the former can be used to compose new images (by leveraging the Kubernetes cluster for build slaves with resource control) and the latter can manage the process of transitioning between one set of podTemplates to another (and can be triggered by builds).

First, is this something that should be in Kubernetes?  Should it be on top of Kubernetes as a separate server?  Or is it something that could be optionally enabled by those who wish to work on it?  We've got some ideas of how we could make this flow work really cleanly with Docker and images, but we'd want to get feedback on those ideas.

**Comment by bgrant0607** [comment]
Not urgent, but how hard would it be to package most of this functionality as independent plugins (once we have a plugin mechanism)?

**Comment by smarterclayton** [comment]
Very little.  Builds are decoupled except for the ability to watch for upstream images that change, and the same applies to deployments.

**Comment by davidopp** [comment]
@davidopp

**Comment by ghodss** [comment]
Is this now a dupe to #1743? Or do we still want to keep this open for the idea of builds? In which case it may help to close and fork given this issue as-is covers a lot.

**Comment by ghodss** [comment]
The issue for a job controller is #1624, with the proposal for it at #11746.

**Comment by bgrant0607** [comment]
I'm closing this now. Jobs and Deployments are underway. If builds appear in Kubernetes, it will be as some kind of extension. We might need image metadata at some point, but that's not really discussed here in any detail.
