### ISSUE TITLE
Can't update cluster-cidr for controller manager

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#50305]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

1. start controller manager with --cluster-cidr=10.0.0.0/16
\--------------------------
\#  kubectl get pod -n kube-system | grep controller-manager
kube-controller-manager-hz-ugnx7gsqul-0-i5qtlkkffqkf-kube-master-2cn6c3wo57qx   1/1       Running   0          1m
\# kubectl logs kube-controller-manager-hz-ugnx7gsqul-0-i5qtlkkffqkf-kube-master-2cn6c3wo57qx -n kube-system 
…
I0808 08:56:46.584672       1 cidr_allocator.go:111] Node hz-uaaasmcpnd-0-jlx5pevc5una-kube-minion-aydmdqfdo7xe has CIDR 10.0.0.0/24, occupying it in CIDR map
I0808 08:56:46.584710       1 cidr_allocator.go:111] Node hz-ugnx7gsqul-0-i5qtlkkffqkf-kube-master-2cn6c3wo57qx has CIDR 10.0.1.0/24, occupying it in CIDR map
\--------------------------

2. update cluster-cidr of controller manager service to '--cluster-cidr=10.10.0.0/16', then restart controller manager:
\--------------------------
\# kubectl get pod -n kube-system | grep controller-manager
kube-controller-manager-hz-ugnx7gsqul-0-i5qtlkkffqkf-kube-master-2cn6c3wo57qx   0/1       CrashLoopBackOff   5          4m
\# kubectl logs kube-controller-manager-hz-ugnx7gsqul-0-i5qtlkkffqkf-kube-master-2cn6c3wo57qx -n kube-system 
…
**I0808 08:51:53.942134       1 cidr_allocator.go:111] Node hz-uaaasmcpnd-0-jlx5pevc5una-kube-minion-aydmdqfdo7xe has CIDR 10.0.0.0/24, occupying it in CIDR map
F0808 08:51:53.942182       1 controllermanager.go:181] error running controllers: failed to initialize nodecontroller: failed to mark cidr as occupied: cidr 10.0.0.0/24 is out the range of cluster cidr 10.10.0.0/16**
\--------------------------

**What you expected to happen**:
succeed to update cluster-cidr for controller manager

**Anything else we need to know?**:
Currently node controller get node cidr from apiserver(etcd), then check the cidr and cluster-cidr. Id cluster-cidr can't contains node cidr, controller manager will failed.
_**So can we update original node cidr if cluster-cidr has been changed?**_

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by drinktee** [comment]
Maybe we should not change the cluster-cidr. Because if every node changes cidr, the ips of pods need to change too which means all pods will be killed.

**Comment by thockin** [comment]
In general, you can't change this at run time today.  You'd have to fully drain the cluster.  Is this really something you need to do?

**Comment by XericZephyr** [comment]
Hi, @thockin @drinktee, if I have to update the cluster CIDR anyway, is there an instruction?

**Comment by sadlar** [comment]
@XericZephyr https://github.com/kubernetes-incubator/kube-aws/issues/1307  i find someway to change it .
