### ISSUE TITLE
Add validations for kube-apiserver run options

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#50301]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

Create Validate() or add more checks in existing Validate() for the following files:

-  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/start.go:80
-  vendor/k8s.io/kube-aggregator/pkg/cmd/server/start.go:104
-  vendor/k8s.io/sample-apiserver/pkg/cmd/server/start.go:82
-  cmd/kube-apiserver/app/options/validation.go:49

I am working on it.

**Comment by m1093782566** [comment]
@sttts

**Comment by sttts** [comment]
:+1:

**Comment by mbohlool** [comment]
cc @cheftako
