### ISSUE TITLE
Failed to run godep-save.sh

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#50318]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:

\$ rm -rf Godeps
\$ rm -rf vendor
\$ ./hack/godep-save.sh
Running godep save. This will take around 15 minutes.
godep: Package (k8s.io/apimachinery/pkg/openapi) not found
!!! Error in ./hack/godep-save.sh:45
  Error in ./hack/godep-save.sh:45. 'GOPATH=${GOPATH}:${KUBE_ROOT}/staging godep save "${REQUIRED_BINS[@]}"' exited with status 1
Call stack:
  1: ./hack/godep-save.sh:45 main(...)
Exiting with status 1

**What you expected to happen**:
succeed to run godep-save.sh.

**How to reproduce it (as minimally and precisely as possible)**:
\$ rm -rf Godeps
\$ rm -rf vendor
\$ ./hack/godep-save.sh

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):   latest
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FengyunPan** [comment]
@sttts Can you give me some ideas?

**Comment by dims** [comment]
@FengyunPan - Did you try the "separate directory" tip? https://github.com/mironov/kubernetes/blob/master/docs/devel/development.md#using-godep

**Comment by sttts** [comment]
have you called `./hack/godep-restore.sh` before?

**Comment by sttts** [comment]
`godep: Package (k8s.io/apimachinery/pkg/openapi) not found` is strange. I think we had that before. It was gone after a clean checkout.

**Comment by FengyunPan** [comment]
@dims Yes, I try to update gophercloud by (https://github.com/mironov/kubernetes/blob/master/docs/devel/development.md#using-godep).

**Comment by FengyunPan** [comment]
@sttts @dims Sorry, my code is older and pkg/generated/openapi/zz_generated.openapi.go need '(k8s.io/apimachinery/pkg/openapi)'.
I close this issue.
