### ISSUE TITLE
hack/cherry_pick_pull.sh failing

### ISSUE THREAD

**Issue by x13n** [kubernetes/kubernetes#50314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Cannot create cherrypick PR with hack/cherry_pick_pull.sh:

$ GITHUB_USER=x13n hack/cherry_pick_pull.sh release-1.7 49009
+++ Updating remotes...
Fetching upstream
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
error: Could not fetch upstream
Fetching origin

**What you expected to happen**:

Continue executing script and create cherrypick PR.

**How to reproduce it (as minimally and precisely as possible)**:

Run:

GITHUB_USER=x13n hack/cherry_pick_pull.sh release-1.7 49009

**Anything else we need to know?**:

$ git remote -v
origin	git@github.com:x13n/kubernetes.git (fetch)
origin	git@github.com:x13n/kubernetes.git (push)
upstream	https://github.com/kubernetes/kubernetes.git (fetch)
upstream	nope (push)

/cc wojtekt@

**Comment by wojtek-t** [comment]
This is misconfiguration because the script works for me. It's not a bug, maybe it's missing some hints what do you have misconfigured.

**Comment by x13n** [comment]
Indeed. Narrowed this down to:

$ git fetch upstream
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository

This was working before; digging further.

**Comment by x13n** [comment]
I still have no idea what failed, but recreating the repo helped. Keeping this open to improve error messages in the script.

**Comment by xiangpengzhao** [comment]
Seems like here misconfigured, not sure why though.

```
upstream	nope (push)
```

/sig contributor-experience

**Comment by x13n** [comment]
Nope, that's something else:

$ git remote set-url --push upstream https://github.com/kubernetes/kubernetes.git
$ git remote -v
origin	git@github.com:x13n/kubernetes.git (fetch)
origin	git@github.com:x13n/kubernetes.git (push)
upstream	https://github.com/kubernetes/kubernetes.git (fetch)
upstream	https://github.com/kubernetes/kubernetes.git (push)
$ git fetch upstream
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
