### ISSUE TITLE
There should be constants for well-known RBAC ClusterRole(Bindings)

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#50315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

Right now, there are no constants defined for well-known ClusterRoles and ClusterRoleBindings like `system:node-proxier`, `system:node-bootstrapper`, etc.

It would be really helpful for consumers like kubeadm etc. to be able to source these consts from a pkg with no other deps.

cc @kubernetes/sig-auth-feature-requests @kubernetes/sig-cluster-lifecycle-feature-requests @timothysc

**Comment by vbmade2000** [comment]
I think this can be closed.

**Comment by luxas** [comment]
This is not fixed yet.

**Comment by vbmade2000** [comment]
Ah correct.

**Comment by liggitt** [comment]
Where would you expect the constants to live? The bootstrap roles and bindings are in the kube apiserver, which we don't want people vendoring

**Comment by luxas** [comment]
> which we don't want people vendoring

Why not? In a constants package with no other deps...?

**Comment by liggitt** [comment]
Repos are the unit of vendoring, not packages.

**Comment by luxas** [comment]
But why should no-one be vendoring the kube-apiserver repo then? I don't understand that.
