### ISSUE TITLE
kubelet-v1.7.0: storage capacity is 0

### ISSUE THREAD

**Issue by flyer103** [kubernetes/kubernetes#50322]
**Is this a BUG REPORT or FEATURE REQUEST?**:

bug

**What happened**:
When I described a node, I found that the value of `storage.kubernetes.io/scratch` is `0`.

**What you expected to happen**:
The value of `storage.kubernetes.io/scratch` should be the storage size that the node could offer, like `cpu` or `memory` resource.

**How to reproduce it (as minimally and precisely as possible)**:
In kubernetes-v1.7.0, do the following:

```shell
$ kubectl describe node SOME_NODE | grep "storage.kubernetes.io/scratch"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: Vultr
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`): 4.4.0-83-generic
- Install tools: [kismatic](https://github.com/apprenda/kismatic/)
- Others:

**Comment by xiangpengzhao** [comment]
This should have been fixed by #48567.
xref: #48452

/cc @jingxu97 @feiskyer

**Comment by flyer103** [comment]
Thanks.
I'll try kubernetes-v1.7.3 tomorrow and check the node storage capacity reported by kubelet.

**Comment by jingxu97** [comment]
@flyer103 Since the storage capacity storage.kubernetes.io/scratch is a new API type, it is till in alpha feature. So you have to enable alpha cluster to get the capacity reported by kubelet.

**Comment by flyer103** [comment]
Thank you.

I have tried to install kubernetes-v1.7.3 and set `--feature-gates=AllAlpha=true` to `apiserver` `controller-manager` `scheduler` and `kubelet`. Then I could see the  expected value of `storage.kubernetes.io/scratch`.

In addition, I have another doubt. 
[sizeLimit](https://kubernetes.io/docs/api-reference/v1.7/#emptydirvolumesource-v1-core) for `EmptyDir` is supported since kubernetes-v1.7.0 and [client-go v4.0.0.beta.0](https://github.com/kubernetes/client-go/blob/v4.0.0-beta.0/pkg/api/types.go#L618) has supported the argument too.
But if not setting the flag `--feature-gates=AllAlpha=true`, I would get the error `Forbidden: SizeLimit field disabled by feature-gate for EmptyDir volumes`.
So is `sizeLimit` for `EmptyDir` an alpha feature?

**Comment by xiangpengzhao** [comment]
@flyer103 yes this is an alpha feature in 1.7. See: https://github.com/kubernetes/kubernetes/pull/45686

**Comment by flyer103** [comment]
Got.
