### ISSUE TITLE
Support the env flag from docker exec in kubectl exec (and API)

### ISSUE THREAD

**Issue by marvinthepa** [kubernetes/kubernetes#50321]
This is similar to #30656.

If `docker exec` is used for the `exec` endpoint, then it would be better to have an `env` parameter working like the one of `docker exec`. At least better than pasting the environment variables into the command and having to deal with escaping issues..

/kind feature
/sig cli

**Comment by marvinthepa** [comment]
I feel this needs an additional label as it is not only about the CLI, but the corresponding API as well - but I can't find the corresponding label. Maybe someone can help me out here,?

**Comment by steinnes** [comment]
I'd really appreciate this feature :-)

**Comment by f3flight** [comment]
/reopen
run into this lack of a feature today, had to revert to dokcer exec to run etcdctl with ETCDCTL_API=3 variable inside default etcd container deployed by kubeadm

**Comment by steerben** [comment]
+1 for reopening

**Comment by marvinthepa** [comment]
I will try:

/reopen
