### ISSUE TITLE
Proposal to simplify kubectl reapers

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#50340]
# Summary of proposed code change

  1. remove selector-overlap detection code from reapers that have it because ownerRef changes in 1.5 effectively prevent selector-overlap.
  1. remove scale down code from reapers since foreground GC can do it for you
  1. change default timeout to either num pods time pod grace period, or infinity.

# Changes in kubectl behavior

A Relnote will call out this change in behavior as seen by users:

In 1.7 and before, when you use kubectl delete to delete a replicaSet, replicationController, daemonSet, deployment, statefulSet or job, it would return after all the pods had begun deleting, but before they completed deleting.  In 1.8, it will wait for all the pods to complete deleting.   With this new behavior, the involved pod names (which are reused by statefulSet) and the pod's resources are guaranteed to be freed when the command returns.   The default timeout is increased to `blah`.  Use a shorter timeout if you do not want to wait, using the `--blah` flag.

# After the Change:

Ideally each reaper code is just:

```
c := Blah client
c.Delete(name, foregroundGCOption, veryLargeTimeout)
```

# Summary of current reapers
All code in pkg/kubectl/delete.go in functions called `Stop`.

##  ReplicaSet Reaper
- Make a replicaSet client.  
- Set timeout based on number of replicas
- detect overlap and error out if found.
- scale while waiting for scale to zero with timeout
- delete the RS

## ReplicationController Reaper
Same as RS

## DaemonSet Reaper
- make DS client
- hacky scale to zero
- wait for zero scheduled
- delete DS

## StatefulSet Reaper
- make SS client
- scale to zero
- delete SS

*TODO*: check that PVCs are not owned, so that they are orphaned when you GC them.

## Job reaper
- make job and pods clients
- set timeout based on number of pods 
- scale down
- delete dead pods
- delete job

*TODO*: check that dead pods still have ownerRef to job so GC gets them.

## Deployment Reaper

- make Deployment and RS clients
- pause it, set replicas to zero, and revision history to zero
- wait for it to observe the pause
- stop all RSes using RS reaper
- delete Deployment

*TODO*: will Deployment controller consider itself paused when it gets a deletion timestamp?  If so, don't need "paused".

*TODO*: will revision history get GC'ed?

## Pod Reaper

- Get pod's grace period
- delete pod with grace period.

# Version considerations

Kubectl supports 1 version of skew.
Foreground GC and all needed GC features are supported in 1.6, according to @caesarxuchao so we could just entirely replace the reaper code with the new simpler code.  

*TODO*: Need to verify that in 1.6 the controllers-loops all know to stop reconciling when a controller-object has a deletion timestamp (this gets delivered as an update, not a delete, via watch, so need to make sure it is handling the right way.

# Client Failure or Timeout

If kubectl fails or times out before Foreground GC is done, the GC proceeds anyways (according to the expert, @caesarxuchao).  If the user wants rerun kubectl, kubectl will try the delete again, and the second foreground delete should again wait on the deletion of that same object (again according to the expert). 

TODO: make sure the delete command will allow re-deleting an object that is in a deleting state.

**Comment by erictune** [comment]
@kubernetes/sig-apps-misc

**Comment by erictune** [comment]
For statefulSet, when we stop doing scale down, you lose ordered delete.
However, there are no known use cases where ordered delete is important.  Ordered scale up and down is mostly about maintaining sync between actual scale and individual members knowledge of what peers they have / quorum expectations.  You don't need that if you are just deleting without scaling.  @kow3ns agreed with this.   So, if we do this, and I think we should, then we can close https://github.com/kubernetes/dashboard/issues/2176, or rather tell Dashboard to use plain delete too.  TBD how dashboard should handle timeouts.

**Comment by erictune** [comment]
It turns out just a Delete returns immediately.  If you want to wait for the synchronous GC to complete, you have to watch for it to be deleted.

**Comment by kargakis** [comment]
> TODO: will Deployment controller consider itself paused when it gets a deletion timestamp? If so, don't need "paused".
> TODO: will revision history get GC'ed?

The reason we are pausing first is to use the controller's GC policy wrt the old ReplicaSets. RevisionHistoryLimit=0 means that all old RSs will be GC'ed

**Comment by kargakis** [comment]
related: https://github.com/kubernetes/kubernetes/issues/49504

**Comment by kow3ns** [comment]
@kargakis why not let GC happen in the background after deletion?

**Comment by kargakis** [comment]
@kow3ns you mean, delete the Deployment and let the ReplicaSets be deleted by the garbage collector as opposed to the revisionHistoryLimit mechanism?

**Comment by kow3ns** [comment]
@kargakis Yes. Maybe I'm missing something, but if you delete the Deployment and leave the ControllerRef on the RS it should get collected anyway no?

**Comment by kargakis** [comment]
Yes. IIRC, the reason behind deleting RSs first and then collecting the Deployment was that a Deployment may run a bunch of ReplicaSets in parallel. Essentially, people/processes should be able to monitor the Deployment and determine that things are getting cleaned up. Now, the kubectl reaper predates the work that has been done on server-side GC and I think that it's possible today to do this via the GC or at least it's been worked on. cc: @caesarxuchao

**Comment by caesarxuchao** [comment]
> Essentially, people/processes should be able to monitor the Deployment and determine that things are getting cleaned up

This is possible with the server-side GC. You need to set [DeleteOptions.PropagationPolicy](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L449) to "Foreground" when you delete a deployment, then the deployment object won't be deleted until all the dependent replicasets and pods are garbage collected. 
[Doc](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion) on foreground GC.

**Comment by kargakis** [comment]
Yeah, that's what I was thinking! Thanks @caesarxuchao! So we should be able to switch the kubectl reaper to use foreground policy but we need to make sure that it works with two versions older servers? Or is it one?
@caesarxuchao what's the version foreground policy was added?

**Comment by caesarxuchao** [comment]
1.6

**Comment by kow3ns** [comment]
I think we should do this for 1.9.

**Comment by kargakis** [comment]
sgtm

**Comment by kow3ns** [comment]
@pwittrock between sig-apps and sig-cli can we get rid of the reapers in 1.11 if we haven't done so in 1.10?

**Comment by liggitt** [comment]
reapers were removed from kubectl in 1.11, deletion now depends on server side GC, and client-side wait is skippable with `--wait=false`

/close
