### ISSUE TITLE
Cannot start the pods 

### ISSUE THREAD

**Issue by barathjoeee** [kubernetes/kubernetes#50357]
kubectl get pods

nginx-cb40j                  0/1       rpc error: code = 2 desc = failed to start container "fc9a052c5767e76d17930678dd569f35f3c91e23266b165786c6e20347ab1742": Error response from daemon: {"message":"cannot join network of a non running container: 56db0de585403b05922f3ffd0db1cc35c98c6be8d8d64975d4bd1c127809366e"}   73         4d
nginx-sgp02                  0/1       rpc error: code = 2 desc = failed to start container "f9e4333a6ef4b518f5ca5e611ad1ee6a36d3f72b52c5685a796b55c5024b842a": Error response from daemon: {"message":"cannot join network of a non running container: f2ada2e19c0df732ef7e0a5358b66d1f427752b1cc997a45199d89d5a369b94d"}   87         4d
wordpress-3878056801-tpmdc   0/1       rpc error: code = 2 desc = failed to start container "7088de7ce5db3b6d49ea7237135eb3512e5172013f2cc9462f43548f1ddace52": Error response from daemon: {"message":"cannot join network of a non running container: 7431fcadbbf0b37faf5663bdc7407d6c0e5837f70d704a3b4506f11582055a0b"}   223        5d
root@ip-172-31-31-202:~# dokcer run 7431fcadbbf0b37faf5663bdc7407d6c0e5837f70d704a3b4506f11582055a0b

**Comment by idvoretskyi** [comment]
@barathjoeee there's no exact information at the issue body (together with empty issue description).

Please, update the issue description by filling the template before someone may assist you.

**Comment by post707** [comment]
@xiangpengzhao Have you solved your problem?I've had this problem, too

Aug 28 20:37:29 k8snode2 kubelet: I0828 20:37:29.456214    2441 kuberuntime_manager.go:458] Container {Name:operate Image:docker.gaia/docker/operate/image Command:[] Args:[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:8080 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:CONFIG_SERVER_URL Value:http://192.168.1.15:8888 ValueFrom:nil} {Name:spring_profiles_active Value:k8s ValueFrom:nil} {Name:server_port Value:8080 ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-z0tjg ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Aug 28 20:38:28 k8snode2 kubelet: E0828 20:38:28.284501    2441 pod_workers.go:182] Error syncing pod 81b94a42-8bb5-11e7-8c41-5254008783ac ("operate-939293338-sg1tw_default(81b94a42-8bb5-11e7-8c41-5254008783ac)"), skipping: failed to "StartContainer" for "operate" with rpc error: code = 2 desc = failed to start container "17143dd69a72044579514536c664a06887626d45c9b0a36e128ec70ca949ea60": Error response from daemon: {"message":"shim error: context deadline exceeded"}: "Start Container Failed"

**Comment by kenden** [comment]
Can you add information about this issue? See the issue template has:

Is this a BUG REPORT or FEATURE REQUEST?:

Uncomment only one, leave it on its own line:

/kind bug
/kind feature
What happened:

What you expected to happen:

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:
