### ISSUE TITLE
Additional probe for rolling updates to StatefulSet

### ISSUE THREAD

**Issue by bsander** [kubernetes/kubernetes#50363]
/kind feature

We have an elasticsearch cluster running as a `StatefulSet`, on which we would like to perform a rolling update. When one pod gets updated and comes online, Kubernetes sees that as a signal that the update is complete and proceeds to updating the next pod. However, at this point elasticsearch is still recovering and balancing its shards and the update should wait until this process is finished. Elasticsearch has support for probing its cluster state for this purpose.

I could implement this as a readiness probe of course, however the cluster state is shared across all pods so that would make them all fail the probe and cut them off from traffic at the same time. This rebalancing process does not actually affect the cluster availability, so I do not want to do that. Currently I'm trying to work around this by adding an extremely large `failureThreshold` to the readiness probe, but this is far from ideal and still has edge cases which may render the entire cluster unavailable.

I could really use a separate probe in this scenario to signal that a pod's update is complete and that the rolling update may continue, without affecting the pod's availability.

**Comment by kargakis** [comment]
cc @kow3ns

**Comment by kow3ns** [comment]
@bsander are you implementing [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) workflow? If so, what mechanisms are you using to do it?

**Comment by bsander** [comment]
@kow3ns Well, basically, but without the shard allocation in advance. For now we "just" have Kubernetes perform a rolling upgrade (thus, deleting pods one by one and starting up new ones based on an updated image). But even if we did do the shard allocation steps, there still would be some time between the **node** being up and ready for traffic, and the **cluster** being ready for the next pod to be updated.
