### ISSUE TITLE
kubemark-500 continuously failing since 3 days while starting hollow-nodes

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#50366]
I'm consistently seeing the following failure in those runs:

```
I0806 06:39:32.654] [0;31m Timeout waiting for all hollow-nodes to become Running. [0m
I0806 06:39:33.270] Found only 494 ready hollow-nodes while waiting for 500.
I0806 06:39:35.032] 495 hollow-nodes are reported as 'Running'
I0806 06:39:35.034] 6 hollow-nodes are reported as NOT 'Running'
I0806 06:39:35.036] NAME READY STATUS RESTARTS AGE hollow-node-4gt6q 0/3 Pending 0 29m hollow-node-b2lqz 0/3 Pending 0 29m hollow-node-fzjbb 0/3 Pending 0 29m hollow-node-jp5qf 0/3 Pending 0 29m hollow-node-rdvfr 0/3 Pending 0 29m hollow-node-t299r 0/3 Pending 0 29m
```

Seems like they're failing scheduling. Will look into it.

cc @k8s-mirror-scalability-bugs @gmarek

**Comment by shyamjvs** [comment]
Ok.. So it's consistently failing to create 6 pods and almost surely it's an issue with requests. Most probably some node-daemon is requesting more than before.

**Comment by shyamjvs** [comment]
From the [diff](https://github.com/kubernetes/kubernetes/compare/fc89743dc...94abce7c2) I'm almost 100% sure that it's failing due to this PR - https://github.com/kubernetes/kubernetes/pull/49009
It seems to have increased the fluentd memory request.

@x13n @crassirostris Could one of you confirm this?

**Comment by crassirostris** [comment]
@shyamjvs It hasn't (shouldn't have) changed the resource requirement, defaults for the env variable are the same as in the yaml

**Comment by shyamjvs** [comment]
Cool, thanks. I'll check what else it could've been.

**Comment by shyamjvs** [comment]
So it's due to insufficient cpu:

```
I0805 07:47:07.923870       9 scheduler.go:255] Attempting to schedule pod: kubemark/hollow-node-87jtw
I0805 07:47:07.924151       9 factory.go:932] Unable to schedule kubemark hollow-node-87jtw: no fit: No nodes are available that match all of the following predicates: Insufficient cpu (6).; waiting
I0805 07:47:07.924218       9 factory.go:1009] Updating pod condition for kubemark/hollow-node-87jtw to (PodScheduled==False)
I0805 07:47:07.924525       9 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kubemark", Name:"hollow-node-87jtw", UID:"1faea013-79af-11e7-961c-42010a800002", APIVersion:"v1", ResourceVersion:"2022", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' No nodes are available that match all of the following predicates: Insufficient cpu (6).
```

**Comment by x13n** [comment]
Unless kubemark was using another value than set in that yaml? At some point in time the cpu request was lower (https://github.com/kubernetes/kubernetes/pull/47906).

**Comment by crassirostris** [comment]
It was almost immediately reverted: https://github.com/kubernetes/kubernetes/pull/48066

**Comment by shyamjvs** [comment]
We need 50m (kubelet) + 20m (proxy) + 20m (npd) for each hollow-node. And all nodes seem very close to being exhausted:

```
kubemark-500-master
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  1050m (26%)	0 (0%)		600Mi (4%)	600Mi (4%)

kubemark-500-minion-group-44qj
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  8 (100%)	0 (0%)		23170256640 (73%)	770Mi (2%)

kubemark-500-minion-group-4rhn
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  7950m (99%)	100m (1%)	21005390080 (66%)	1070Mi (3%)

kubemark-500-minion-group-d0hg
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  7970m (99%)	200m (2%)	21917192960 (69%)	1200Mi (4%)

kubemark-500-minion-group-dnbr
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  7963m (99%)	283m (3%)	21602497024 (68%)	1167016Ki (3%)

kubemark-500-minion-group-ndsd
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  7950m (99%)	0 (0%)		21790905600 (69%)	600Mi (2%)

kubemark-500-minion-group-x6l3
  CPU Requests	CPU Limits	Memory Requests		Memory Limits
  7980m (99%)	10m (0%)	21822362880 (69%)	620Mi (2%)
```

@gmarek Do you by any chance remember how much was used before?

**Comment by shyamjvs** [comment]
The above pr should fix this

**Comment by shyamjvs** [comment]
So the problem is indeed with fluentd. It's requesting 200m of CPU instead of 100m (as is expected).
- The fluentd container requests 100m as it should be - https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L38
- But the prometheus-to-sd-exporter sidecar container has also requested 100m : 

```
  prometheus-to-sd-exporter:
    Container ID:	docker://da54cff1d898f625349376c8f3878121c925dc4c89d16913832ddb454b882427
    Image:		gcr.io/google-containers/prometheus-to-sd:v0.1.3
 ..... bla bla ......
    Restart Count:	0
    Limits:
      memory:	300Mi
    Requests:
      cpu:		100m
      memory:		200Mi
    Environment:	<none>
```

We don't have any requests for the exporter set in the yaml template - https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L84
But it's being set.

**Comment by shyamjvs** [comment]
There is a limitranger that sets default request to 100m but that's in default namespace which shouldn't affect fluentd.
So it's indeed a bug with your PR @x13n. Could you fix it?

**Comment by crassirostris** [comment]
Now these numbers seems awfully similar to the fluentd numbers. Now I see the link with https://github.com/kubernetes/kubernetes/pull/49009

@x13n Please investigate, it's a huge bug and has to be rolled back!

**Comment by x13n** [comment]
Testing a fix, I will send a PR soon.

**Comment by shyamjvs** [comment]
Seems fixed - https://k8s-testgrid.appspot.com/sig-scalability#kubemark-500
