### ISSUE TITLE
Can kubernetes node limit the cpu and memory resource ?

### ISSUE THREAD

**Issue by killy001** [kubernetes/kubernetes#50369]
I found a yaml file about resource node, like this:

```
apiVersion: v1beta3
kind: Node
metadata:
  name: 10.5.39.42
  resource:
    capacity:
      cpu: 1000
      memory: 1021888
  labels:
    environment: production
    name: node1
    role: web
```

In this file, it limits the cpu and memory number. When I created a node.yaml file like this, it failed. the api version v1beta3 have not the field resource. 

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-08-08T09:58:51Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: 10.77.9.65
  name: 10.77.9.65
  namespace: ""
  resourceVersion: "976790"
  selfLink: /api/v1/nodes/10.77.9.65
  uid: 2e7f5f82-7c20-11e7-bdf3-1c98ec1a80c0
spec:
  externalID: 10.77.9.65
status:
  addresses:
  - address: 10.77.9.65
    type: InternalIP
  - address: 10.77.9.65
    type: Hostname
  allocatable:
    cpu: "32"
    memory: 31602936Ki
    pods: "3"
  capacity:
    cpu: "32"
    memory: 32651512Ki
    pods: "3"
  conditions:
  - lastHeartbeatTime: 2017-08-09T12:34:34Z
    lastTransitionTime: 2017-08-09T10:18:10Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"

```
Above is my node info, how can I modify the default cpu and memory . The default number of pods is 110, when I start the kubelet service , add the param --max-pods=3 . Now the max number of pods have been 3. How can I modify the default cpu and memory? Thanks you.

**Comment by NickrenREN** [comment]
You maybe create a LimitRange to set default CPU and Memory for a namespace

> Above is my node info, how can I modify the default cpu and memory . The default number of pods is 110, when I start the kubelet service , add the param --max-pods=3 . Now the max number of pods have been 3. How can I modify the default cpu and memory?

**Comment by jianzhangbjz** [comment]
@killy001 Agree with @NickrenREN . You can set the apiserver `--admission-control=` flag has `ResourceQuota` as one of its arguments.
Note that resource quota divides up aggregate cluster resources, **but it creates no restrictions around nodes**. Details in [Resource Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/)

**Comment by killy001** [comment]
@NickrenREN  It is useful for me. Thank you for reply.

**Comment by killy001** [comment]
@jianzhangbjz  Thanks.
