### ISSUE TITLE
External load balancer is not removed after the service is deleted on OpenStack cloud provider

### ISSUE THREAD

**Issue by yuyangbj** [kubernetes/kubernetes#50364]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /sig network

**What happened**:

When I deployed a service with type load balancer, the service controller will create an external load balancer on OpenStack, but when I delete this service, the load balancer will still exist on OpenStack cloud provider.

#kubectl get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.248.0.1   <none>        443/TCP   5d

#neutron lbaas-loadbalancer-list
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+
| id                                   | name                                               | vip_address | provisioning_status | provider   |
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+
| 021e6a63-1643-4557-aaca-37c9fb3b3ad1 | k8s-master-lb-4378c909-26fd-4254-9f34-17976b292014 | 192.168.0.3 | ERROR               | vmwareedge |
| 1392daee-40fd-48d8-91e8-37ffef4eb41c | a3a9866527ce211e79504fa163e95de4                   | 192.168.0.8 | ACTIVE              | vmwareedge |
| e7864372-3ed4-4ae9-849d-db71f5a2c041 | k8s-master-lb-4378c909-26fd-4254-9f34-17976b292014 | 192.168.0.7 | ACTIVE              | vmwareedge |
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+

**What you expected to happen**:

The load balancer created for the kubernetes service should be deleted automatically.

**How to reproduce it (as minimally and precisely as possible)**:

1> Create a service with load balancer type
2> Check the OpenStack load balancer using command: neutron lbaas-loadbalancer-list
3> Delete the service defined in step 1
4> do same as step 2

**Anything else we need to know?**:

1. The kubernetes controller manager does not restart during these ops. I checked the process number, it keeps same.
2. The floating ip related to the load balancer vip is deleted.

**Environment**:
- Kubernetes version (use `kubectl version`):

#kubectl version
2017-08-09 02:37:01.607289 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-09 02:37:01.607883 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-09 02:37:01.608000 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"50ce6464749d05317882f2a4e5e06b3709d59737", GitTreeState:"clean", BuildDate:"2017-07-26T04:38:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"50ce6464749d05317882f2a4e5e06b3709d59737", GitTreeState:"clean", BuildDate:"2017-07-26T04:38:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
OpenStack provider
- OS (e.g. from /etc/os-release):
Ubuntu
- Kernel (e.g. `uname -a`):
#cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

- Install tools:
Kubespray

- Others:

**Comment by FengyunPan** [comment]
@yuyangbj Can you give me some detail logs of kube-controller-manager? Is there error about deletion of LB?

**Comment by yuyangbj** [comment]
I only see the log 


{"log":"I0809 09:11:00.628130      22 servicecontroller.go:740] Service has been deleted default/frontend\n","stream":"stderr","time":"2017-08-09T09:11:00.628497774Z"}
{"log":"E0809 09:11:01.440261      22 servicecontroller.go:753] Failed to process service. Retrying in 40s: Resource not found\n","stream":"stderr","time":"2017-08-09T09:11:01.440499757Z"}
{"log":"I0809 09:11:41.440554      22 servicecontroller.go:740] Service has been deleted default/frontend\n","stream":"stderr","time":"2017-08-09T09:11:41.442214976Z"}
{"log":"E0809 09:11:42.300877      22 servicecontroller.go:753] Failed to process service. Retrying in 1m20s: Resource not found\n","stream":"stderr","time":"2017-08-09T09:11:42.301028896Z"}
{"log":"I0809 09:13:02.304065      22 servicecontroller.go:740] Service has been deleted default/frontend\n","stream":"stderr","time":"2017-08-09T09:13:02.304604367Z"}
{"log":"E0809 09:13:03.799052      22 servicecontroller.go:753] Failed to process service. Retrying in 2m40s: Resource not found\n","stream":"stderr","time":"2017-08-09T09:13:03.800162235Z"}
{"log":"I0809 09:15:43.801200      22 servicecontroller.go:740] Service has been deleted default/frontend\n","stream":"stderr","time":"2017-08-09T09:15:43.801495459Z"}
{"log":"E0809 09:15:44.989576      22 servicecontroller.go:753] Failed to process service. Retrying in 5m0s: Resource not found\n","stream":"stderr","time":"2017-08-09T09:15:44.989939253Z"}

I guess it is related to the code below 

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L780

I am still debugging, that is great if you can help.

**Comment by FengyunPan** [comment]
Can you try 'kubectl get events' to get message of 'DeletingLoadBalancerFailed'?

**Comment by FengyunPan** [comment]
'Resource not found' seems that some resources of the LB have been deleted.

**Comment by yuyangbj** [comment]
but no, I can see the load balancer resources in OpenStack.

**Comment by yuyangbj** [comment]
root@k8s-master-0-4378c909-26fd-4254-9f34-17976b292014:/var/log/containers# grep -r 'Error deleting load balancer' .
root@k8s-master-0-4378c909-26fd-4254-9f34-17976b292014:/var/log/containers# kubectl get events
2017-08-09 03:55:02.484424 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-09 03:55:02.485104 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-09 03:55:02.485349 I | proto: duplicate proto type registered: google.protobuf.Timestamp
LASTSEEN   FIRSTSEEN   COUNT     NAME                                                KIND      SUBOBJECT   TYPE      REASON                             SOURCE                                                       MESSAGE
3m         1h          26        frontend                                            Service               Normal    DeletingLoadBalancer               service-controller                                           Deleting load balancer
3m         1h          26        frontend                                            Service               Warning   DeletingLoadBalancerFailed         service-controller                                           Error deleting load balancer (will retry): Resource not found
0s         1h          110       k8s-master-0-4378c909-26fd-4254-9f34-17976b292014   Node                  Warning   FailedNodeAllocatableEnforcement   kubelet, k8s-master-0-4378c909-26fd-4254-9f34-17976b292014   Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 4143697920 to memory.limit_in_bytes: write /var/lib/docker/aufs/mnt/ed82dac1e4d0b7f94623b88201e6dea8398e19d2886924715a2ea0d8dc8f5015/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument
30s        5d          7448      k8s-node-0-4378c909-26fd-4254-9f34-17976b292014     Node                  Warning   FailedNodeAllocatableEnforcement   kubelet, k8s-node-0-4378c909-26fd-4254-9f34-17976b292014     Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 4143697920 to memory.limit_in_bytes: write /var/lib/docker/aufs/mnt/8b74d7f35136ecfd46ff16f41aa909f19dba3c84d538bab22118d7dc65c73d99/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument
30s        5d          7448      k8s-node-1-4378c909-26fd-4254-9f34-17976b292014     Node                  Warning   FailedNodeAllocatableEnforcement   kubelet, k8s-node-1-4378c909-26fd-4254-9f34-17976b292014     Failed to update Node Allocatable Limits "": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 4143697920 to memory.limit_in_bytes: write /var/lib/docker/aufs/mnt/7957845159c8a7f6a3fbb0cd97e2550d736ec8214eb63244a80a706964827485/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument

**Comment by FengyunPan** [comment]
Are LB's listener  pool  monitor and member exist?

**Comment by yuyangbj** [comment]
@FengyunPan yes, it is there.

# neutron lbaas-loadbalancer-list
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+
| id                                   | name                                               | vip_address | provisioning_status | provider   |
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+
| 021e6a63-1643-4557-aaca-37c9fb3b3ad1 | k8s-master-lb-4378c909-26fd-4254-9f34-17976b292014 | 192.168.0.3 | ERROR               | vmwareedge |
| 1392daee-40fd-48d8-91e8-37ffef4eb41c | a3a9866527ce211e79504fa163e95de4                   | 192.168.0.8 | ACTIVE              | vmwareedge |
| e7864372-3ed4-4ae9-849d-db71f5a2c041 | k8s-master-lb-4378c909-26fd-4254-9f34-17976b292014 | 192.168.0.7 | ACTIVE              | vmwareedge |
+--------------------------------------+----------------------------------------------------+-------------+---------------------+------------+

# neutron lbaas-listener-show 004df606-1efe-450a-b4d2-201e528eb695
+---------------------------+------------------------------------------------+
| Field                     | Value                                          |
+---------------------------+------------------------------------------------+
| admin_state_up            | True                                           |
| connection_limit          | -1                                             |
| default_pool_id           | 29d67489-90c5-4acc-8ad7-d4895454ccdf           |
| default_tls_container_ref |                                                |
| description               |                                                |
| id                        | 004df606-1efe-450a-b4d2-201e528eb695           |
| loadbalancers             | {"id": "1392daee-40fd-48d8-91e8-37ffef4eb41c"} |
| name                      | listener_a3a9866527ce211e79504fa163e95de4_0    |
| protocol                  | TCP                                            |
| protocol_port             | 80                                             |
| sni_container_refs        |                                                |
| tenant_id                 | 3c37ddb0a64b416fa66f3251dabb2fcb               |
+---------------------------+------------------------------------------------+

**Comment by FengyunPan** [comment]
I think you can get some useful message from Neutron, kubernetes just tell you resources have been deleted and can not do a deletion for the LB.

**Comment by yuyangbj** [comment]
I figured out the root cause.

That was because the kubernetes v1.7 openstack load balancer code assume we enable the health monitor by default.

https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L1109

It does not address the scenario we do not enable the healthmonitor. I see master branch has enhance it.

**Comment by FengyunPan** [comment]
Yes, this PR fix it: https://github.com/kubernetes/kubernetes/pull/48336
