### ISSUE TITLE
local cluster fails to start Error: failed to run Kubelet: Running with swap on is not supported

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#50373]
With latest master:
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.1564+3655685d647eb0", GitCommit:"3655685d647eb05006632763987f206e27e173c8", GitTreeState:"clean", BuildDate:"2017-08-09T13:59:53Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

local cluster's kubelet fails to start with the following error:

I0809 10:01:57.021623   25297 server.go:348] Sending events to api server.
I0809 10:01:57.021681   25297 server.go:541] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename                         Type            Size       Used    Priority /dev/dm-1                               partition      4001788 0       -1]

Here is the command used to bring it up, the same command worked yesterday.
ALLOW_PRIVILEGED=true ALLOW_SECURITY_CONTEXT=true LOG_LEVEL=6 FEATURE_GATES=PersistentLocalVolumes=true hack/local-up-cluster.sh

/sig node
/kind bug

**Comment by sbezverk** [comment]
Adding KUBELET_FLAGS=${KUBELET_FLAGS:-"--fail-swap-on=false"}
to hack/local-up-cluster.sh
resolves the issue:
 kubectl get nodes            
NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     2m        v1.8.0-alpha.2.1564+3655685d647eb0

but still it is not clear why it was working before without it.

**Comment by dims** [comment]
@sbezverk please the the following PR and referenced issue - https://github.com/kubernetes/kubernetes/pull/47181

**Comment by cblecker** [comment]
Fixed in #51054
/close
