### ISSUE TITLE
[PROPOSAL] Refactor printer funcs to be mainly exposed / consumed through the factory

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#50388]
https://docs.google.com/a/redhat.com/document/d/15uieHE_QnfF9eEj-AAbAvo3xBqfyu5x1v5Cghzy4ZDI/edit?usp=sharing

#### Case

Right now, there are multiple ways to consume printers in the cli. There are also multiple factory methods that expose different ways of consuming printers (`PrinterForMapping`, `PrinterForCommand`, `PrintObj`, `Printer`, etc).

This proposal calls for consolidating all printer consumption through the [cmd/util factory](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go), making printer consumption simpler by having a single way to set printer options, and making the existing factory methods for accessing printers have less overlap.

#### Sanitize printing options

In order to make it easier to consume printers, there should be a single interface for accessing printers (cmd/util factory), and a single way of passing / setting printing options. 

Ideally, there should only be one `options` struct that binds directly to flags at the cmd level, instead of multiple sets of printer options (`PrintOptions`, `OutputOptions`).

This proposal would merge `OutputOptions` with `PrintOptions`. Leaving a single struct to be passed to printer methods and functions in order to set print opts.

#### Consolidate consumption of printers

For reduced complexity, and ease of customization of printer usage in downstream projects, there should be a single interface for consumers of printers. As suggested in the [linked document](https://docs.google.com/a/redhat.com/document/d/15uieHE_QnfF9eEj-AAbAvo3xBqfyu5x1v5Cghzy4ZDI/edit?usp=sharing), the `pkg/kubectl/cmd/util/factory` should be the single interface for providing access to printers. This would mean unexposing as many helper functions as possible in [pkg/kubectl/cmd/util/printing.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go), and moving others such as [PrintResourceInfoForCommand](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L136), [PrinterForCommand](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L112), and [PrintSuccess](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L76) to the cmd/util factory.

#### Move printer handler registration to the factory

Exposing printer handler registration ([AddHandlers](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L67)) through the cmd factory would provide a simplified way for consumers of `HumanReadablePrinters` to add client-default handlers to the printer. It would additionally allow downstream projects to use kubectl-default printer handlers, while adding new custom handlers all through the same interface.

A way to achieve this could be to expose the [handlerEntry struct](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/humanreadable.go#L48) and update [internalversion/printers.go#AddHandlers](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L67) to instead return a slice of `*handlerEntry`. A new cmd factory method could then be added to call the updated `AddHandlers` function, and iterate over the list of returned `handlerEntries`, registering each one with a given printer. This would also allow the factory to have a new method that returns a list of client-registered print handlers, as suggested in the [linked document](https://docs.google.com/document/d/15uieHE_QnfF9eEj-AAbAvo3xBqfyu5x1v5Cghzy4ZDI/edit?ts=5978e6a6#heading=h.c0r58jdubym8).

#### Update cmdutil.Factory#PrinterForCommand and cmdutil.Factory#PrinterForMapping

Right now, both of these factory methods depend on a `*cobra.Command` and are not very clear on their overall intent. `PrinterForMapping` receives a `*cobra.Command`, a mapping and wraps a call to `PrinterForCommand` while decorating the output from `PrinterForCommand` with either print handlers (if the printer implements `pkg/printers.PrintHandler`) or a versioned printer (if the printer is "generic").

A way to make the intent of these two methods more clear, while improving code re-use, would be to add a new method `PrinterWithOptions` which does not depend on `*cobra.Command` and receives a single set of `printers.PrintOptions`, as well as a mapper (or nil). This new method would then re-use the helper [pkg/kubectl/cmd/util/printing.go#PrinterForCommand](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/printing.go#L113).

`PrinterForCommand` would then be updated to only extract options from a given *cobra.Command, and pass these options to the new `PrinterWithOptions` method.

`PrinterForMapping` would be renamed `DecoratedPrinterWithOptions`. It would no longer receive a `*cobra.Command` but rather a set of `PrintOptions` and a resource mapping. It would then retrieve a "standard" cli printer based on the options given by calling the new method `PrinterWithOptions`, and decorate it by either registering print handlers (if the printer implements `printers.PrintHandler`), or compose it in a versioned printer (if generic).

The above solution would ensure code re-usability where possible among `PrinterWithOptions`, `PrinterForCommand`, and `DecoratedPrinterWithOptions (previously PrinterForMapping)`, while simplifying each method's intent.

@fabianofranz @kubernetes/sig-cli-misc @deads2k @liggitt

**Comment by fabianofranz** [comment]
@kubernetes/sig-cli-proposals

**Comment by deads2k** [comment]
> , as well as a mapper (or nil).

Given a method on the factory, why would the printer need to be passed in?  Seems like you could get a mapper from the factory.



> PrinterForCommand would then be updated to only extract options from a given *cobra.Command, and pass these options to the new PrinterWithOptions method.

Instead of doing this, couldn't you bind the options struct to the command directly and then each command options struct could contain the already built up options from the cli and deal only in objects?
