### ISSUE TITLE
Swagger.json missing in: "path" parameters for multiple endpoints

### ISSUE THREAD

**Issue by jason-kane** [kubernetes/kubernetes#50383]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
inconsistency in generated swagger.json causes coreapi tools to fail.  specifically 

(good)
/api/v1/namespaces/{namespace}/bindings
and many others include in: "path" parameters for namespace, name, etc..

(bad)
/api/v1/namespaces/{namespace}/pods/{name}
includes only query and body parameters.

**What you expected to happen**:
All url endpoints should include descriptions of all required parameters

**How to reproduce it (as minimally and precisely as possible)**:
open https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json and search for /api/v1/namespaces/{namespace}/pods/{name}, compare to /api/v1/namespaces/{namespace}/bindings

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mbohlool** [comment]
There are two places to put parameters. One in the operation itself and one it the Path section. The later one is a common set of parameters that applies to all operations. I checked "/api/v1/namespaces/{namespace}/pods/{name}" and it has name and namespace path parameters as common parameters. I am going to close this. Please reopen if you see any other missing parameters.

**Comment by jason-kane** [comment]
you're right, the problem appears to be elsewhere:
https://github.com/core-api/python-openapi-codec/blob/master/openapi_codec/decode.py#L22

Anything in 'parameters' is ignored, it's unambiguously defined in the current spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#pathItemObject so the fault is pretty clearly on the python-openapi-codec side.  Sorry for the noise.
