### ISSUE TITLE
Kubectl should use protobuf to talk to API server

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#50403]
I have observe that there is a lot of overhead when kubectl tries to GET some large data from apiserver.
e.g. LIST configmaps that could be 100 MB+, in json will cause the etcd overloaded and not responding. It works when list in protobuf.
Steps to reproduce:
1. create configmaps that are larger than 100MB
2. run `kubectl proxy`
3. `curl localhost:8001/api/v1/namespaces/default/configmaps/ --header "Accept: application/vnd.kubernetes.protobuf" > curloutput` This works.
4. `curl localhost:8001/api/v1/namespaces/default/configmaps/ --header "Accept: application/json" > curloutput` This errors and will lose connection to APIserver.

Proposed change:
Change kubectl to use protobuf by default when communicating with API server.

@kubernetes/sig-cli-maintainers 
cc: @mml

**Comment by liggitt** [comment]
including both protobuf and JSON as accepted content types would make sense to me. Not all API servers (or all resources) necessarily support protobuf

**Comment by thedrow** [comment]
You can proxy the API server with something that can GZip/Brotli the response like nginx.
Assuming the kubectl uses a good HTTP client that can decompress GZip (which I assume it does) it will help as a workaround in the meantime.
Worth testing imo
