### ISSUE TITLE
AWS internal ELB subnets are chosen randomly

### ISSUE THREAD

**Issue by tommyvn** [kubernetes/kubernetes#50400]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Using a kops deployed Kubernetes cluster with a private topology on AWS, when creating a Service resource with spec.type == Loadbalancer _and_ metadata.annotations['service.beta.kubernetes.io/aws-load-balancer-internal'] == 0.0.0.0/0 the subnet is chosen randomly per AZ between a public and private subnet yielding inconsistent networking around the ELB.

**What you expected to happen**:
I have my k8s VPC peered with another VPC from which I'd like to access the internal Service ELB, but to say if that access is expected is tricky because at this point both public and private subnets are usually added in a multi-AZ setup resulting in me sometimes achieving my use case and sometimes not, depending on which AZ my browser request hits. I guess I'd expect either all private or all public networks attached, altho I think selfishly I'd like all public because that achieves my use case.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a private topology cluster with kops, edit the cluster to make the network sizes for public and private the same (this is very important, I think aws orders subnets in the api by size and so introducing a ghetto way to work around this), deploy out an internal ELB Service resource and check which subnets are assigned to it. The more AZs the more likely to see the issue.

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/aws/aws.go#L2412 shows exactly how this very bug is avoided on external ELBs but without an equivalent check on internal ELBs the subnet that gets assigned per AZ is based on potentially random ordering.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): debian
- Kernel (e.g. `uname -a`): 4.4.65-k8s
- Install tools: kops
- Others:

**Comment by yastij** [comment]
cc @justinsb

**Comment by adamnoll** [comment]
We have the same issue. We created a kubernetes cluster with kops with a private topology. We then created an ingress service with an internal ELB. That ELB was connected to all of our nodes but only one AZ. We had to manually add the other Availability Zone.

**Comment by tommyvn** [comment]
The documentation around this isn't great, I can't even remember where I saw this, if you set an AWS tag of kubernetes.io/role/internal-elb=true on _either_ the private _or_ utility subnets the kubernetes AWS cloud provider will use those networks for your internal ELBs rather then cobbling together random subnets like we're both currently seeing.
I hope this solves your issue @adamnoll like it did mine. I'm closing this issue as the tagging fixed this for me.

**Comment by adys** [comment]
Correct, the documentation isn't great. I found the [PR](https://github.com/kubernetes/kubernetes/pull/22064) that [introduces](https://github.com/kubernetes/kubernetes/pull/22064/files#diff-07ba008af9c76b0539556ff7fde3105eR62) **kubernetes.io/role/internal-elb tag**.

**Comment by infa-ddeore** [comment]
AWS has the documentation on the same, https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html#vpc-tag-private-subnets

But there shouldn't be a need to explicitly tag the private subnets, rather k8 should identify internal subnets and choose randomly from them. If someone wants to restrict internal ELBs in specific subnets then the tags should be used.
