### ISSUE TITLE
 kube-apiserver.service running error ：code=exited, status=203/EXEC

### ISSUE THREAD

**Issue by beyondli** [kubernetes/kubernetes#50415]
I install kube-apiserver 1.7.3， and when running it . the error show bleow:
the error code is status=203/EXEC, what does 203 it mean? anyone help me? thank in andvance!

  Active: failed (Result: start-limit) since Thu 2017-08-10 09:20:02 CST; 1min 10s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 4086 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=203/EXEC)
 Main PID: 4086 (code=exited, status=203/EXEC)

Aug 10 09:20:02 k8server systemd[1]: kube-apiserver.service: main process exited, code=exi...XEC
Aug 10 09:20:02 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 10 09:20:02 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 09:20:02 k8server systemd[1]: kube-apiserver.service failed.
Aug 10 09:20:02 k8server systemd[1]: kube-apiserver.service holdoff time over, scheduling ...rt.
Aug 10 09:20:02 k8server systemd[1]: start request repeated too quickly for kube-apiserver...ice
Aug 10 09:20:02 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 10 09:20:02 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 09:20:02 k8server systemd[1]: kube-apiserver.service failed.

**Comment by xiangpengzhao** [comment]
Any clue in the log of kube-apiserver?

/sig cluster-lifecycle

**Comment by beyondli** [comment]
yes, with <**systemctl start kube-apiserver**>
info is
ob for kube-apiserver.service failed because the control process exited with error code. See "systemctl status kube-apiserver.service" and "journalctl -xe" for details.

with <**systemctl status kube-apiserver.service**>
Aug 10 09:26:05 k8server systemd[1]: kube-apiserver.service: main process exited, code=exi...XEC
Aug 10 09:26:05 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 10 09:26:05 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 09:26:05 k8server systemd[1]: kube-apiserver.service failed.
Aug 10 09:26:06 k8server systemd[1]: kube-apiserver.service holdoff time over, scheduling ...rt.
Aug 10 09:26:06 k8server systemd[1]: start request repeated too quickly for kube-apiserver...ice
Aug 10 09:26:06 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 10 09:26:06 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 09:26:06 k8server systemd[1]: kube-apiserver.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

with **journalctl -xe**
-- The error number returned by this process is 2.
Aug 10 14:45:04 k8server systemd[1]: kube-apiserver.service: main process exited, code=exited, statu
Aug 10 14:45:04 k8server systemd[1]: Failed to start Kubernetes API Service.
-- Subject: Unit kube-apiserver.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kube-apiserver.service has failed.
-- 
-- The result is failed.
Aug 10 14:45:04 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 14:45:04 k8server systemd[1]: kube-apiserver.service failed.
Aug 10 14:45:05 k8server systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Aug 10 14:45:05 k8server systemd[1]: start request repeated too quickly for kube-apiserver.service
Aug 10 14:45:05 k8server systemd[1]: Failed to start Kubernetes API Service.
-- Subject: Unit kube-apiserver.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kube-apiserver.service has failed.
-- 
-- The result is failed.
Aug 10 14:45:05 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 10 14:45:05 k8server systemd[1]: kube-apiserver.service failed.
Aug 10 14:45:19 k8server chronyd[918]: Source 173.255.246.13 replaced with 61.216.153.107


---------------------------------
configure is error?  I really donot know this ....

**Comment by beyondli** [comment]
I code run apiserver.service like this

[Service]
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/apiserver
ExecStart=/usr/bin/kube-apiserver \
$KUBE_LOGTOSTDERR \
$KUBE_LOG_LEVEL \
$KUBE_ETCD_SERVERS \
$KUBE_API_ADDRESS \
$KUBE_API_PORT \
$KUBELET_PORT \
$KUBE_ALLOW_PRIV \
$KUBE_SERVICE_ADDRESSES \
$KUBE_ADMISSION_CONTROL \
$KUBE_API_ARGS
Restart=on-failure
Type=notify
LimitNOFILE=65536

-----------------------
so the error info : 4534 (code=exited, status=203/EXEC) is most improtant hint ,what meaning of 203? it seems harly to find the defination

**Comment by beyondli** [comment]
is there some places can find all the error code meanings? if possible ,I  think  it will be more easier to locate many problems

**Comment by dixudx** [comment]
@beyondli Dup of #50493?

Actually such error msg/code `code=exited, status=203/EXEC` is not brought by `apiserver`. It is `Systemd` that finds the unit file of `apiserver` will not function well.

Please check that `/usr/bin/kube-apiserver` does exist and is executable. Also the `KUBE_*` args are well formated.
