### ISSUE TITLE
Fitler out nodes in batch when scheduling pods

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#50419]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:
During the discussion at https://github.com/kubernetes/kubernetes/pull/50185 , we found there's some way to improve the performance of scheduling; for example, 1.) reordering the predicates to check simpler predicate firstly, 2.) group nodes by label/taints to filter nodes in batch (similar to equal cache).

I'd like to continue this discussion here if any more proposal/suggestion.

cc/ @gmarek @yastij @kubernetes/sig-scheduling-misc @kubernetes/sig-scalability-misc

**Comment by k82cn** [comment]
/assign

Assign to my self; I'll take a look after 1.8.

**Comment by k82cn** [comment]
cc/ @jinzhejz

**Comment by yastij** [comment]
@k82cn - For 1) :

>  I imagine that we can somehow estimate what percentage of Nodes pass through given predicate check and put those with smallest number in front. 

From what i understood of @gmarek, the idea is to put most restrictive predicates (ones with lowest percentage of nodes that passes through) in front, this doesn't imply that they are the simplest one ?

**Comment by k82cn** [comment]
great , "simpler" one first can be option 3.

**Comment by gmarek** [comment]
Yeah, that was my idea, but as I said, it's just something that popped up in my mind, so I have no idea how possible it is, and is it possible to dynamically change the order of predicates on a running scheduler, and so on. But generally if someone is interested in improving scheduler performance figuring out how to compute predicates most efficiently sounds like a very interesting project (make me wish I had time...)

**Comment by yastij** [comment]
@gmarek - well in November I plan to have a 2 months break to work on k8s, so i'll also follow this one closely 😄

**Comment by yastij** [comment]
@gmarek @k82cn - started thinking about this one, estimating percentage of nodes passing through each predicates is tied to the cluster. 

I think we should have number of scheduling actions before estimating this. The first question is when do we start estimating ?  (i.e when will we have enough data to make a decision)

**Comment by bsalamat** [comment]
Reordering predicates is certainly useful, but I am not sure if we really need to be able to change the order dynamically. At least for the first version, having a static order of predicates should be enough and is easy to implement.
I also like the idea of grouping nodes by label and taints. Grouping by label can particularly help improve performance.

**Comment by gmarek** [comment]
I agree with @bsalamat - initial version should just define some sane static order. Next step would be to allow changes to this order, probably by exposing the order to user. Dynamic reordering depending on the Pod being scheduled/state of the cluster has lower priority.

**Comment by yastij** [comment]
@gmarek @bsalamat - I'll work on the proposal, including these steps. I'll ping you for review and for defining a timeline.

**Comment by resouer** [comment]
@yastij Any progress may I ask? You can always ping me to review you know that :)

**Comment by yastij** [comment]
@resouer - this should be closed as predicates ordering was merged

**Comment by resouer** [comment]
close in favor of #57168
