### ISSUE TITLE
cinder volumes with statefulset Unable to mount 

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#50421]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind bug

**What happened**:
the pv info:
![image](https://user-images.githubusercontent.com/25783555/29152382-bf7fe3f8-7db9-11e7-8f97-3ac4baafb8c3.png)

the pvc info:
![image](https://user-images.githubusercontent.com/25783555/29152400-d88aa162-7db9-11e7-9969-ad7e675ceeca.png)

``-bash-4.2#` cat cinderpv1.yaml
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - "ReadWriteMany"
  cinder:
    fsType: "ext4"
    volumeID: "421806a2-db1e-460a-b65b-b1ae38b46317"

``-bash-4.2# cat cinderpvc1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cinder-jlx-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: "pv0001"

``-bash-4.2# cat cinderpv2.yaml
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0002"
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - "ReadWriteMany"
  cinder:
    fsType: "ext4"
    volumeID: "421806a2-db1e-460a-b65b-b1ae38b46317"

``-bash-4.2#` cat cinderpvc2.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cinder-jlx-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: "pv0002"

the statefulset info:
`-bash-4.2# cat statefulset-cinder.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jlx
spec:
  serviceName: "cinder"
  replicas: 2
  template:
    metadata:
      labels:
        app: cinder
    spec:
      containers:
      - name: cinder
        image: index.tenxcloud.com/docker_library/nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: cinder
          mountPath: /usr/cinder
  volumeClaimTemplates:
  - metadata:
      name: cinder
      annotations:
        volume.alpha.kubernetes.io/storage-class:
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 2Gi
`
but the pod info
![image](https://user-images.githubusercontent.com/25783555/29152519-699a80aa-7dba-11e7-9895-a190c195545d.png)
![image](https://user-images.githubusercontent.com/25783555/29152532-7daf7fe6-7dba-11e7-9e73-5989c396cbb0.png)
the kubelet info
![image](https://user-images.githubusercontent.com/25783555/29152598-d7c9f11e-7dba-11e7-8008-dbec00727dd7.png)
![image](https://user-images.githubusercontent.com/25783555/29152611-e1a39f50-7dba-11e7-9488-a5e6348e0b03.png)

cinder show
![image](https://user-images.githubusercontent.com/25783555/29152670-23f33b36-7dbb-11e7-9daf-5981c80123ba.png)
![image](https://user-images.githubusercontent.com/25783555/29152681-307c7dd6-7dbb-11e7-8449-a09080f4b6a0.png)

**What you expected to happen**:
pod running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):GitVersion:"v1.6.4+d6f433224538d"
- Cloud provider or hardware configuration**:openstack
- OS (e.g. from /etc/os-release):NAME="NewStart Carrier Grade Server Linux"
- Kernel (e.g. `uname -a`):Linux master-jlx-k8s.novalocal 3.10.0-514.6.1.el7.x86_64 #1 SMP Thu Feb 16 19:50:09 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/sig openstack
/sig storage 
@FengyunPan @dimthe 
thanks

**Comment by FengyunPan** [comment]
@jianglingxia Can you give me some logs about it from kube-controller-manager?

**Comment by jianglingxia** [comment]
![image](https://user-images.githubusercontent.com/25783555/29155976-ed42c3ec-7dd1-11e7-8f8a-c6dcbf1a6c94.png)
@FengyunPan 
thanks

**Comment by FengyunPan** [comment]
@jianglingxia Please check your config file of kube-controller-manager, '--cloud-config= --cloud-provider=openstack'.

**Comment by jianglingxia** [comment]
the configuration of kubelet is 
![image](https://user-images.githubusercontent.com/25783555/29156288-9f05422a-7dd3-11e7-9140-d819f62654a6.png)
and the kube_openstack_config file in node path of /etc/kubernetes
-bash-4.2# cat kube_openstack_config
[Global]
auth-url=http:/ip:5000/v2.0/
username=k8s
password=k8s
region=RegionOne
tenant-id=d0b676089a19434ab07b06c834c1ddc3

the '--cloud-config= --cloud-provider=openstack' configuration need add in master controller-manager file ?
I see the paper of http://www.sohu.com/a/111190250_468741  so  config the node kubelet file.

**Comment by jianglingxia** [comment]
sorry, @FengyunPan   need your help ,thanks very much!
I added the --cloud-config= --cloud-provider=openstack' configuration to master controller-manager,then restart kube-controller-manager ,and then 
-bash-4.2# kubectl get nodes
NAME             STATUS    AGE       VERSION
node-k8s-jlx-1   Ready     21h       v1.6.4+d6f433224538d
node-k8s-jlx-2   Ready     21h       v1.6.4+d6f433224538d
create a pod 
![image](https://user-images.githubusercontent.com/25783555/29156922-e76b29fa-7dd6-11e7-921f-41579e5dc033.png)
![image](https://user-images.githubusercontent.com/25783555/29156934-f84ccc06-7dd6-11e7-98a3-0432d8ab4f87.png)
the controller-manager log
![image](https://user-images.githubusercontent.com/25783555/29156967-207d3d14-7dd7-11e7-8123-8dd9d5633a51.png)
please

**Comment by FengyunPan** [comment]
As far as I know， you deploy the cluster by magnum, but the controller manager service can't work, I suspect your bay is wrong. 
Please show me the following log:
1. /etc/kubernetes/manifests/kube-controller-manager.yaml
2.more logs of controller manager

**Comment by jianglingxia** [comment]
in my enviroment no the path file /etc/kubernetes/manifests
-bash-4.2# cd /etc/kubernetes/
-bash-4.2# ls
apiserver   certs   controller-manager             kubectl.kubeconfig  kube_openstack_config  scheduler.kubeconfig          tokens
basic_auth  config  controller-manager.kubeconfig  kubelet             scheduler              scheduler-policy-config.json
but  why not use cinder volume ,create a pod  can running
![image](https://user-images.githubusercontent.com/25783555/29159945-f79c4c4e-7de2-11e7-911e-d4fed8d4f08d.png)
I just created the cloud hard disk on the OpenStack, and test the local Mount experiment, other cloud hosts can be mounted, but my two  nodes and master both cannot be mounted locally
![image](https://user-images.githubusercontent.com/25783555/29160095-8beeb5a8-7de3-11e7-903f-b7c53228ab91.png)
Is my node missing MULTIPATHD service or Iscis service？

[kube-controller-manager.txt](https://github.com/kubernetes/kubernetes/files/1214020/kube-controller-manager.txt)

@FengyunPan  thanks very much

**Comment by FengyunPan** [comment]
Sorry, I can't get helpful message.
You should check the error message from log or event.

**Comment by jianglingxia** [comment]
can  I  ask  you a question?thanks
config the kubelet file,the KUBELET_HOSTNAME="--hostname-override=192.165.1.151" must change the openstack Virtual machine name？is necessary ？Now there's a problem, our virtual machine name does not conform to the k8s regular expression，have [] in the name，so cannot do after! @FengyunPan 
thanks for your reply

**Comment by FengyunPan** [comment]
HostnameOverride is the hostname used to identify the kubelet instead of the actual hostname.
Your virtual machine name which does not conform to the k8s regular expression can not be used by kubernetes.

**Comment by jianglingxia** [comment]
now I need use the cinder in kubernetes ,so need config the hostname-override in the kubelet file ,
http://www.sohu.com/a/111190250_468741
in the paper note that 
![image](https://user-images.githubusercontent.com/25783555/29653688-57f02eda-88dd-11e7-8cd1-7b7a48fc303b.png)
so I want to know that is necessary to change the ip to the virtual machine name ?or you have some idea 
to resolve the problem of not conform the k8s regular expression?thanks very much!

**Comment by FengyunPan** [comment]
No idea. 
Related to #49544

**Comment by jianglingxia** [comment]
can you help me?
1、What is the cloud host name specifically used for?why must change the ip to virtual machine name?
2、in k8s cinder plugin only Interaction to openstack cinder ? not to interact other plugin?
thanks for your reply!

**Comment by jianglingxia** [comment]
I have done it,and I will close the issue,thanks for you all!

**Comment by avoidik** [comment]
@jianglingxia what was the problem?

**Comment by jianglingxia** [comment]
the first problem:I can not config the controller manager to --cloud-config= --cloud-provider=openstack;
yeah,you correct that the doc https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes-1 write cinder supports only ReadWriteOnce access mode,but if two pod in one minion use the same volumeid you can try it!maybe the way not often use,thanks very much!

**Comment by avoidik** [comment]
@jianglingxia in a case with multiple pods in one node, how did you managed scheduling to single node only?
