### ISSUE TITLE
PSP: export failOnNoPolicies in podSecurityPolicyPlugin to make it configurable

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#50424]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Currently in `podSecurityPolicyPlugin`, there is  a flag `failOnNoPolicies` to define the default behavior of PSP. Can we export this flag to make it configuration at external?

**What you expected to happen**:
Can we export this flag `failOnNoPolicies` in `podSecurityPolicyPlugin`  to make it configuration at external?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Currently PSP admission plugin will deny any pod creation if there is no matching PSP. In some of user cases, namespace and service account were dynamically created, and it's difficult create related PSP for these service account.

Can we just allow any pod creation if there is no matching PSP? Just like quota, without quota configuration, the resource usage will be not limited.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by php-coder** [comment]
/sig auth
CC @liggitt 

> Can we just allow any pod creation if there is no matching PSP?

How it differs from the case where you're disabling PSP admission controller?

**Comment by liggitt** [comment]
> How it differs from the case where you're disabling PSP admission controller?

I agree, I don't think the admission plugin should fail open.

> it's difficult create related PSP for these service account

I would recommend creating a restricted PSP that you want to be available to any user, and grant that to all users

**Comment by liqlin2015** [comment]
Thanks for your advice.
