### ISSUE TITLE
Is it reasonable putting all node as members for service with type load balancer

### ISSUE THREAD

**Issue by yuyangbj** [kubernetes/kubernetes#50437]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When I deployed a service with type load balancer, in the large scale, for example, I have 1000 worker nodes, every node will be put into load balancer pool member list.  Is it reasonable? You know in the LB's performance should be larger than number of pool member * single pool member performance.

**What you expected to happen**:

Can we define a method to pick up some of worker nodes as pool members?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Kubernetes version (use kubectl version):
#kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"50ce6464749d05317882f2a4e5e06b3709d59737", GitTreeState:"clean", BuildDate:"2017-07-26T04:38:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"50ce6464749d05317882f2a4e5e06b3709d59737", GitTreeState:"clean", BuildDate:"2017-07-26T04:38:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider or hardware configuration**:
OpenStack provider

OS (e.g. from /etc/os-release):
Ubuntu

Kernel (e.g. uname -a):
#cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Install tools:
Kubespray

**Comment by yuyangbj** [comment]
@FengyunPan any opinion?

**Comment by FengyunPan** [comment]
>You know in the LB's performance should be larger than number of pool member * single pool member performance.

Sorry, I don't understand what you say.
IMO, If some nodes(node-A) is not load balancer pool member and there are some pods(pod-B) run in them(node-A), LB service will can't access pod-B. So all the nodes should be LB member.
Please let me know if my understand is wrong.@yuyangbj

**Comment by yuyangbj** [comment]
There is something wrong in your understanding. 

Take flannel as am example. When you create a POD, actually there will be a port created on every worker nodes, and the corresponding iptables will be created on every worker nodes, the destination should be the POD IP. So there is no scenario that the service can not access to POD-B if its hosting node is not added as member.

My concern is should we put the 1000 nodes into the member list within one pool. In some cases, we cannot support 1000 members within one load balancer pool.

**Comment by FengyunPan** [comment]
Yeah, I see. Thank for your comment.
But the number of member is unlimited.
\-------
      --connection-limit CONNECTION_LIMIT
                        The maximum number of connections per second allowed
                        for the vip. Positive integer or -1 for unlimited
                        (default).
\-------

**Comment by thockin** [comment]
What is the problem this aims to solve?  With the `externalTrafficPolicy` field, you might actually lose backends if you don't have all VMs.  Nothing stops a particular cloud provider from selecting a subset, though, I think?

**Comment by yuyangbj** [comment]
@FengyunPan @thockin 

Thanks for your response. Can you guys explain more for these parameters?

I am looking for a configuration that we can create a load balancer with multiple pools or a load balancer with limited members. i am not sure if the Kubernetes can do it till now.

Basing on my test, every node will be put into the load balancer member list, for some neutron drivers, for example VMware NSX, it can only support 32 members within one load balancer pool. So @thockin is it configurable?
