### ISSUE TITLE
cannot join network of a non running container

### ISSUE THREAD

**Issue by barathjoeee** [kubernetes/kubernetes#50433]
unable to run the pods in kubernetes it throws the following error:
cannot join network of a non running container

Please help out

**Comment by vikaschoudhary16** [comment]
you should look for help at slack channels #kubernetes-user #sig-network.

**Comment by xiangpengzhao** [comment]
/sig node
probably

**Comment by fabiand** [comment]
I'm also seeing this issue now and then.

**Comment by kenden** [comment]
Could you add more information about this issue? See the issue template has:


**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature


**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:


**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
