### ISSUE TITLE
cinder calls detach disk even if nothing was mounted

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#50441]
@dims @anguslees - while reading some cinder code, i came accross [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder.go#L332), we try to detach disk even if we didn't try to mount. Is this call mandatory ? (from what i recall AWS EBS do not have such mecanism) 

Also ping @saad-ali

**Comment by yastij** [comment]
also cc @rootfs

**Comment by rootfs** [comment]
that's was before attach/detach controller, a revisit is necessary

**Comment by yastij** [comment]
Sure i'll take care of it
/assign
