### ISSUE TITLE
NetworkPolicy across Namespaces

### ISSUE THREAD

**Issue by mccormd** [kubernetes/kubernetes#50451]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
I can't find a way of matching a pod label AND a namespace label.

**What you expected to happen**:
I want to be able to define network policy such that certain pods in a frontend namespace can be allowed to access specific pods/services in a backend namespace.
i.e. I want to define NetworkPolicies which allow ingress across Namespaces by PodLabel.

When creating a policy with a namespaceSelector and a podSelector it seems to allow access from everything in the namespace.

**How to reproduce it (as minimally and precisely as possible)**:

Create backend and frontend namespaces and label each with network-zone: frontend|backend
Create a backend nginx service:
```
kubectl run nginxback --image=nginx --replicas=2 -n backend
kubectl expose deployment nginxback --port=80 -n backend
```
Now create two busybox clients in the frontend namespace for testing access to the nginxback backend service:
```
kubectl run busy1 -ti --image=busybox /bin/sh -n frontend
kubectl run busy2 -ti --image=busybox /bin/sh -n frontend
```
Catch all backend pods with a default deny policy...

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-backend
  namespace: backend
spec:
  podSelector: {}
```

Now create the following NetworkPolicy to allow access from busy2: -  
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-busy2-to-backend-nginx
  namespace: backend
spec:
  podSelector:
    matchLabels:
      run: nginxback
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network-zone: frontend
    - podSelector:
        matchLabels:
          run: busy2
    ports:
    - port: 80
```
Test access from busy1 and busy2 pods in the frontend:
busy2:
```
# wget -q -S --timeout=5 --spider http://nginxback.backend
  HTTP/1.1 200 OK
  Server: nginx/1.13.3
  Date: Thu, 10 Aug 2017 11:38:01 GMT
  Content-Type: text/html
  Content-Length: 612
  Last-Modified: Tue, 11 Jul 2017 13:06:07 GMT
  Connection: close
  ETag: "5964cd3f-264"
  Accept-Ranges: bytes
```
busy1:
```
# wget -q -S --timeout=5 --spider http://nginxback.backend
  HTTP/1.1 200 OK
  Server: nginx/1.13.3
  Date: Thu, 10 Aug 2017 11:39:30 GMT
  Content-Type: text/html
  Content-Length: 612
  Last-Modified: Tue, 11 Jul 2017 13:06:07 GMT
  Connection: close
  ETag: "5964cd3f-264"
  Accept-Ranges: bytes
```
Hmm, looks like I've opened a rule that allows ANYTHING in my frontend namespace where I want to pick out a specific pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
2017-08-10 12:08:38.168742 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-10 12:08:38.168836 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-10 12:08:38.168855 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release): 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux ip-10-20-14-134.eu-west-1.compute.internal 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

- Install tools:
- Others:

**Comment by mccormd** [comment]
@kubernetes/sig-network

**Comment by cmluciano** [comment]
Which CNI plugin are you using?

cc @kubernetes/sig-network-bugs

**Comment by caseydavenport** [comment]
> I can't find a way of matching a pod label AND a namespace label.

This isn't supported in the NetworkPolicy API at the moment, but has been considered.  I don't think this is a bug since this is how the API is currently designed. 

Right now, specifying a podSelector and a namespaceSelector gives you the logical OR of the two selectors.

**Comment by thockin** [comment]
This is a feature request.  I'm not against it, but we need to think through the implications and precedents.

**Comment by mccormd** [comment]
Hi, I'm using Calico (Canal) as my CNI plugin.  Should kubernetes be flexible around the namespace model or should we be deploying each application into its own namespace as a shared pattern?

**Comment by mccormd** [comment]
`Right now, specifying a podSelector and a namespaceSelector gives you the logical OR of the two selectors.`

@caseydavenport Why not make it a logical AND instead?  In most cases where you could need to use an OR you could achieve by splitting into two separate rules...

**Comment by caseydavenport** [comment]
@mccormd sorry, I wasn't particularly clear.  I meant that there's no way today to specify both namespaceSelector and podSelector except by putting them in two separate rules, which gives you the logical OR.

The API validates against having both present in a single rule - if this was allowed I agree it would indicate AND. 

I don't have a strong opinion yet on whether or not the AND combination should be supported - like @thockin said we need to figure out what the implications of doing that would be.

**Comment by Calpicow** [comment]
I think this would be a useful feature to have. What implications come to mind for this?

**Comment by Morriz** [comment]
Any updates on this? I assume more people would like to tighten their net, and only allow certain pods access to certain pods in another namespace. To do cross namespace policing we have to resort a combination of `namespaceSelector: {}` AND `ports:` which is kinda rough. Or am I missing something?

**Comment by redbaron** [comment]
Very surprised that there is no way to pick pods from another namespace in NetworkPolicy. Essentially what kubernetes offers is to trust another namespace as a whole.

**Comment by caseydavenport** [comment]
@redbaron in many cases if you'd want to select pods in another namespace you would need to essentially trust that namespace as a whole _anyway_.

Selecting pods within a foreign namespace would in many cases provide a false sense of security, because the owner of that namespace is free to put whatever labels they want on those pods anyway.

**Comment by redbaron** [comment]
Choosing pods in a namespace is quite useful for Egress control, more specifically allowing things like kube-dns to be accessible, without enabling access to other pods. Of course, locking ports helps, so even trusting whole kube-system doesn't open access to an apiserver, but locking ports AND pod would be even better :)

**Comment by danwinship** [comment]
> Choosing pods in a namespace is quite useful for Egress control, more specifically allowing things like kube-dns to be accessible, without enabling access to other pods.

Hmm. That can only work if the owner of that service agrees to treat the specific pod labels they're using as "stable API". (Eg, in the case of kube-dns, agreeing that the service will *always* be identified by the label `k8s-app: kube-dns`.) And if they forget, and change the labels, then the service would still work fine for them, and for anyone not using egress policies, but anyone with a NetworkPolicy in another namespace referencing the old pod labels would no longer be able to access it. (And in a multitenant/RBAC cluster, where people can't see objects in other namespaces, the service owner wouldn't even be able to check if other namespaces had NetworkPolicies referring to the old labels, and the users with broken NetworkPolicies wouldn't be able to check the Service to find out what the new labels were.)

"Allow egress to the Service 'kube-dns' in the Namespace 'kube-system'" or something like that would make more sense.

**Comment by caseydavenport** [comment]
> "Allow egress to the Service 'kube-dns' in the Namespace 'kube-system'" or something like that would make more sense.

It might, though isn't that just pushing the "stable API" from the labels to the name? Not sure if either can really be considered a contract. 

If anything, labels are more meaningful than a name, but the question in my mind is "are labels on namespaced resources meaningful outside of that namespace?"

**Comment by redbaron** [comment]
> If anything, labels are more meaningful than a name, but the question in my mind is "are labels on namespaced resources meaningful outside of that namespace?

I believe they are. Although I agree with points above, simple fact that I am forced to move kube-dns to a dedicated namespace to be able to reference it, shows something is wrong.  "Existence of the pod" is a contract, "existence of the pod with right labels" is a contract, "existence of the pod with right labels in the right namespace" is a contract. IMHO it is not much different from current "existence of the pod in the right namespace" situation.

**Comment by danwinship** [comment]
> isn't that just pushing the "stable API" from the labels to the name?

If you are intentionally exposing the service for pods in other namespaces to consume, then they are presumably finding it via kube-dns, so the name is already the "stable API". (OK, obviously that doesn't work for the kube-dns service itself, but for any *other* service, that's how you'd find it.)

**Comment by caseydavenport** [comment]
> If you are intentionally exposing the service for pods in other namespaces to consume, then they are presumably finding it via kube-dns, so the name is already the "stable API".

Yeah, that makes sense and I think I mostly agree. Obviously there are exceptions to that rule but it's definitely the majority use case.

**Comment by caseydavenport** [comment]
Closing the loop:

- There's a proposal for this here: https://github.com/kubernetes/kubernetes/issues/58637
- And an API change here! https://github.com/kubernetes/kubernetes/pull/60452

We're expecting this to go into k8s v1.11 in order to give implementations a chance to catch up.

/remove-lifecycle stale

**Comment by caseydavenport** [comment]
This will be in v1.11.

I know at least Calico [(as of release v3.1.3)](https://github.com/projectcalico/libcalico-go/pull/872) will have support for this once it ships. 

/close

**Comment by xoen** [comment]
@mccormd Hello don't know if anyone else already pointed out but as far as I know (with my limited knowledge of `NetworkPolicy`) the policy is slightly (but dangerously) wrong because it has two separate [NetworkPolicyPeer](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#networkpolicypeer-v1-networking-k8s-io) so it reads like

allow ingress traffic from:
 - pods in namespaces with label `network-zone=frontend` or
 - pods with label `run=busy2`

That is VERY SNEAKY. What you want (according to the documentation) should be achievable by having both `namespaceSelector` AND `podSelector`:

```yaml
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network-zone: frontend
      podSelector:
        matchLabels:
          run: busy2
```

>  `namespaceSelector`: Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces. If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.

UNFORTUNATELY I've found out that even with the right YAML syntax the old version of calico doesn't do what the documentation says. I'm glad this will work in a new version of calico thanks to this [PR #872](https://github.com/projectcalico/libcalico-go/pull/872) :)
