### ISSUE TITLE
[e2e test failure] Simple pod should support exec through kubectl proxy

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#50466]
/cc @kubernetes/sig-cli-bugs 

This test has started failing on GKE and GCI-GKI e2e tests:

https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke
https://k8s-testgrid.appspot.com/release-master-blocking#gke

Example failure

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke/12920

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:457
Expected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://35.188.213.188 --kubeconfig=/tmp/gke-kubecfg386178168 --server=http://127.0.0.1:45529 --namespace=e2e-tests-kubectl-nlzj2 exec nginx echo running in container] []  <nil>  W0810 18:25:44.244920    4112 http.go:342] Error reading backend response: unexpected EOF\nerror: error sending request: Post http://127.0.0.1:45529/api/v1/namespaces/e2e-tests-kubectl-nlzj2/pods/nginx/exec?command=echo&command=running&command=in&command=container&container=nginx&container=nginx&stderr=true&stdout=true: unexpected EOF\n [] <nil> 0xc4211d3830 exit status 1 <nil> <nil> true [0xc4203e6828 0xc4203e6840 0xc4203e6858] [0xc4203e6828 0xc4203e6840 0xc4203e6858] [0xc4203e6838 0xc4203e6850] [0x11bf750 0x11bf750] 0xc420f2db60 <nil>}:\nCommand stdout:\n\nstderr:\nW0810 18:25:44.244920    4112 http.go:342] Error reading backend response: unexpected EOF\nerror: error sending request: Post http://127.0.0.1:45529/api/v1/namespaces/e2e-tests-kubectl-nlzj2/pods/nginx/exec?command=echo&command=running&command=in&command=container&container=nginx&container=nginx&stderr=true&stdout=true: unexpected EOF\n\nerror:\nexit status 1\n",
        },
        Code: 1,
    }
    error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://35.188.213.188 --kubeconfig=/tmp/gke-kubecfg386178168 --server=http://127.0.0.1:45529 --namespace=e2e-tests-kubectl-nlzj2 exec nginx echo running in container] []  <nil>  W0810 18:25:44.244920    4112 http.go:342] Error reading backend response: unexpected EOF
    error: error sending request: Post http://127.0.0.1:45529/api/v1/namespaces/e2e-tests-kubectl-nlzj2/pods/nginx/exec?command=echo&command=running&command=in&command=container&container=nginx&container=nginx&stderr=true&stdout=true: unexpected EOF
     [] <nil> 0xc4211d3830 exit status 1 <nil> <nil> true [0xc4203e6828 0xc4203e6840 0xc4203e6858] [0xc4203e6828 0xc4203e6840 0xc4203e6858] [0xc4203e6838 0xc4203e6850] [0x11bf750 0x11bf750] 0xc420f2db60 <nil>}:
    Command stdout:
    
    stderr:
    W0810 18:25:44.244920    4112 http.go:342] Error reading backend response: unexpected EOF
    error: error sending request: Post http://127.0.0.1:45529/api/v1/namespaces/e2e-tests-kubectl-nlzj2/pods/nginx/exec?command=echo&command=running&command=in&command=container&container=nginx&container=nginx&stderr=true&stdout=true: unexpected EOF
    
    error:
    exit status 1
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2066```

**Comment by mengqiy** [comment]
Not sure if it is related to recent change in https://github.com/kubernetes/kubernetes/pull/49534.

**Comment by pwittrock** [comment]
@bowei Looks like this is only failing on GKE.  @liggitt suggested this might be due to the way the master / node network is setup on GKE.

**Comment by pwittrock** [comment]
cc
@kubernetes/sig-network-bugs 
@kubernetes/sig-cli-bugs

**Comment by jagosan** [comment]
@bowei can you please take a look at @pwittrock's comment and update / reassign if appropriate? Thanks!

**Comment by bowei** [comment]
I'll take a look

**Comment by bowei** [comment]
If networking is at fault, it would result in all of the tests that traverse the SSH tunnel path to fail with a timeout, which I'm not seeing here.

**Comment by bowei** [comment]
This test does not seem to have ever passed, at least not in the testgrid history.

**Comment by liggitt** [comment]
> Should I expect to see other test failures if the failure is not related to the request sent by kubectl, but instead how it is processed by the apiserver?

I'm not sure we test any other websocket requests in e2e, so maybe not?

**Comment by jagosan** [comment]
/unassign @bowei 
/assign @mengqiy 
/remove-sig network

Thanks for looking @bowei. @mengqiy - any more insight to add here?

**Comment by pwittrock** [comment]
@liggitt 

Should we be adding those tests?

**Comment by mengqiy** [comment]
/assign @apelisse 
/unassign
@apelisse is taking over this issue and have potential fix.

**Comment by smarterclayton** [comment]
The core bug here is that gke uses a different transport wrapper than normal gce installs and unwrapping the transport is required to upgrade passthrough proxies.

**Comment by apelisse** [comment]
And I think that's what I've addressed that in #50775 (making the GKE transport unwrappable), but as we can see, it fails for another reason. Any idea?

**Comment by liggitt** [comment]
#50775 is necessary but not sufficient.

copied from https://github.com/kubernetes/kubernetes/pull/50775#issuecomment-322963183

the issue is with https://github.com/kubernetes/kubernetes/blob/4bfe9b1a568be137f72cf5dfc8bc2c1f13874548/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L269-L282 that does not actually use the transport to handle the request, only to dial. That means that TLS-authentication methods like client certs work, and header authentication methods like bearer tokens do not.

can recreate this by running `kubectl proxy` using bearer token authentication and not cert auth, then try `kubectl exec ... --server=http://localhost:8001`

**Comment by smarterclayton** [comment]
The transport that is used for upgrade needs to be invoked on the request
we use to dial the backend.  In theory we can use a capturing RoundTripper
to see the mutation (we use that in a few other places, and I needed it for
the websocket code).
