### ISSUE TITLE
vSphere cloud provider - k8s cluster stopping see nodes if  vCentrer is unavailable  

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes#50465]
Such behavior of cluster is not good especially if it running in production .

Is it  malfunction of k8s or bug?
How do you recommend to handle this issue?

Thanks in advance
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug 
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
@g1001p Can you describe this issue? we can help.

@luomiao @BaluDontu @tusharnt @rohitjogvmw

**Comment by g1001p** [comment]
The issue is that kubernetes cluster stopped working  and pods switched  from running state to pending state due to vCenter applience IP is not responding. 

BTW once vCenter appliance  started be available  and it IP is responding than kubernetes cluster back working and pods switched back to running state.

⁣Sent from TypeApp ​

**Comment by divyenpatel** [comment]
@g1001p 
We recently analyzed similar issue - https://github.com/vmware/kubernetes/issues/204
but could not reproduce it.

Can you provide kubernetes cluster version?

**Comment by g1001p** [comment]
Sure , the version is 1.4 04

⁣Sent from TypeApp ​

**Comment by divyenpatel** [comment]
@g1001p We will try to re-produce the issue locally.

meanwhile as mentioned in https://github.com/vmware/kubernetes/issues/204#issuecomment-319127357 on release 1.6, we do not see any issue  with cluster when VC is down. 

you mentioned vCenter Appliance IP is not responding, Are you powering off VC or any specific step i.e bring down appliance network?

**Comment by g1001p** [comment]
Probably just reboot is not enough to reproduce this problem.  In my case the first minute that  vCenter became unavailable the k8s was function ok. I observed that k8s started reported about not ready workers when vCenter was  not available  approximately two minutes and more . 

⁣Sent from TypeApp ​

**Comment by g1001p** [comment]
Another moment I did not mention we power off vCenter to see how long kubernetes cluster could tolerate the disapirance of vCenter and I see that first two minutes after power off kubernetes has no issues . After two minutes passed the workers nodes becoming not ready one by one. 
If exists such deep dependency from vCenter high availability then  we need   k8s toleration parameter to manage the down time of vCenter.  What do you rhink?

⁣Sent from TypeApp ​

**Comment by g1001p** [comment]
I also checked this issue in k8s 1.6.6. Indeed it is not reproducible.
Thank you very much for help.
