### ISSUE TITLE
Taint/Toleration Not Enforced After Pod Delete

### ISSUE THREAD

**Issue by laverite** [kubernetes/kubernetes#50464]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I tained a node and created a deployment with a matching toleration and deployed.  My pod got scheduled on the expected tainted node.  However when I manually deleted the pod, k8s rescheduled a new pod on a node that had no taint.  

**What you expected to happen**:
I would expect k8s to enforce the same taint/toleration when rescheduling pods that are manually deleted. 
**How to reproduce it (as minimally and precisely as possible)**:
1. taint a node
2. created a deployment with a toleration matching taint
3. watch for pod to get scheduled on tainted node
4. manually delete pod and watch for pod to be rescheduled on a un-tainted node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:51:56Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
baremetal
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`):
Linux 4.9.13-1 #1 SMP Mon Feb 27 18:52:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by liggitt** [comment]
a pod's nodeSelector targets nodes with those labels

a pod's tolerations allow (but do not require) scheduling to nodes with corresponding taints

a toleration does not mean you *will* get scheduled on a node with a corresponding taint. it means you *can* get scheduled on a node with a corresponding taint.

if you want to target a specific node or set of nodes, you should label those nodes, and specify a matching nodeSelector in your deployment spec

**Comment by laverite** [comment]
thanks @liggitt.  that makes sense.
