### ISSUE TITLE
Kube-proxy uses incorrect iptables save and restore commands for IPv6 

### ISSUE THREAD

**Issue by leblancd** [kubernetes/kubernetes#50474]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When bringing up kube-proxy in IPv6 mode (i.e. with a BindAddress of ::0), several error messages were seen in the kube-proxy logs indicating that 'iptables-save' and 'iptables-restore' utilities were being called instead of 'ip6tables-save' and 'ip6tables-restore'. 

**What you expected to happen**:
kube-proxy should be using 'ip6tables-save' and 'ip6tables

**How to reproduce it (as minimally and precisely as possible)**:
Merge in changes from PR #48551, and then run kube-proxy with '--bind-address ::0'.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Latest master plus PR #48551
- Cloud provider or hardware configuration**: CentOS 7 VirtualBox VMs on a Ubuntu 16.04.1 host
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1 host, CentOS 6 guests
- Kernel (e.g. `uname -a`): 4.4.0-78-generic #99-Ubuntu x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by danielmorlock** [comment]
Is this in 1.7.9 ?
