### ISSUE TITLE
Find home for shared k8s-specific libraries

### ISSUE THREAD

**Issue by monopole** [kubernetes/kubernetes#50475]
As the [core] repo splits into multiple repos, shared packages need a home, as the core isn't intended for vendoring.

Proposal #48209 established the [utils] repository, specifically defining it as a repository with _no k8s dependence_.  The [utils] repo may be viewed as supplementing https://golang.org/pkg, and be of interest to non-k8s projects.

The discussion left open the question of where to put shared packages _specific to k8s_ .  E.g.

* k8s.io/kubernetes/pkg/api/v1/helper
* k8s.io/kubernetes/pkg/controller/deployment/util
* k8s.io/kubernetes/pkg/client/retry
* k8s.io/kubernetes/pkg/printers

Even if these particular examples don’t end up in a common repo, some shared k8s code will exist.  Some options to deal with it are:

 * Copy the code to multiple repos rather than link to one library. The copies then evolve independently.
 * Stop linking the code; access it via RPC to live service.  The code goes into the repo for that service.
 * Relax the no-k8s constraint on [utils] and throw all shared packages in there.
 * Per @smarterclayton 's [idea](https://github.com/kubernetes/kubernetes/issues/48209#issuecomment-313870481), make a new repo https://github.com/kubernetes/common.

This proposal opens the road for the last option.  

Proposed `README` for the new repo:
----------

# Common

Go libraries shared by various Kubernetes repositories.  See also [utils], which has the same purpose but different commit criteria.

## Purpose

As Kubernetes grows and spins functionality out of its [core] and into cooperating repositories ([apiserver], [kubectl], [kubeadm], etc.) that communicate with each other via known API types, the need arises for leaf repositories to house shared code.

This repository is intended to hold shared utilities specific to Kubernetes, e.g. code that depends on Kubernetes API types.  The [utils] repository, a sibling to this repository, holds shared utilities that have _no_ Kubernetes dependence.

## Criteria for committing code here

- Used by multiple Kubernetes repositories.

- Full unit test coverage.

- Go tools compliant (`go get`, `go test`, etc.).

- Complex enough to be worth vendoring, rather than copying.

- Stable, or backward compatible, API.

- With respect to Kubernetes repositories, this [common] repository may only depend on repositories intended for external use, e.g. [api] and [utils] are OK, [core] is not OK.  

[utils]: https://github.com/kubernetes/utils
[common]: https://github.com/kubernetes/common
[api]: https://github.com/kubernetes/api
[apiserver]: https://github.com/kubernetes/apiserver
[core]: https://github.com/kubernetes/kubernetes
[kubeadm]: https://github.com/kubernetes/kubeadm
[kubectl]: https://github.com/kubernetes/kubectl

**Comment by monopole** [comment]
@kubernetes/sig-architecture-proposals

**Comment by boris-42** [comment]
This is how OpenStack start dying, welcome to hell...

**Comment by bgrant0607** [comment]
@monopole Thanks for working through these details.

Why shouldn't k8s.io/kubernetes/pkg/client/retry move to client-go or another repo in kubernetes-client?

I'd like other functionality that's applicable to arbitrary K8s-compatible resources to go into kubernetes-client repos/libraries, also. (Ref #7311)

The functionality corresponding to specific Kubernetes APIs, such as k8s.io/kubernetes/pkg/controller/deployment/util, will eventually need to be separated into layers along with other functionality, but starting with kubernetes/common is fine by me. Any time we're ready to do this, email kubernetes-dev according to the incubator process, under the moving-code-out-of-k/k clause.

**Comment by bgrant0607** [comment]
@monopole 

https://github.com/kubernetes/common now exists

common-admins has admin privilege.

Please also create common-maintainers (write) and common-reviewers (read).

**Comment by bgrant0607** [comment]
The client code should live somewhere in API machinery though.
