### ISSUE TITLE
DaemonSet controller start new pod when the old pod is still in Terminating state

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#50477]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The DaemonSet controller will schedule a pod on a node when the old pod is still in Terminating state. This breaks the expectation that only one pod will be running at a time per node.

**What you expected to happen**:
The DaemonSet controller should not let two pods running at the same time on the same node.

**How to reproduce it (as minimally and precisely as possible)**:
Create a DaemonSet. Set terminationGracePeriodSeconds to be relatively long. Kill a pod. Watch a new pod start on the same node when the old pod is still terminating.

**Anything else we need to know?**:
Seems this behavior was introduced in https://github.com/kubernetes/kubernetes/pull/43077

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
cc @kargakis @janetkuo @lukaszo

**Comment by dhilipkumars** [comment]
cc: @kubernetes/sig-apps-bugs 
I think the expected behavior is correct, the terminating pod could be performing an important step such as 'removing a lock` or 'cleanup` etc., we should allow that to gracefully die before creating a new one.  

IMHO we should revoke to old behavior, but why did we need this new behavior in the first place? That is not clear to me from the PR and Issue.

**Comment by kow3ns** [comment]
We don't currently guarantee at least or at most one scheduling for DaemonSet. Both behaviors are under consideration via issue #48841 and in the future work section of the [design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/daemonset-update.md#future-plans). 

@dhilipkumars The reason for #43077 is to "Make sure that controllers are not adopting children that are marked for deletion" (#44144). This is necessary for GC to work properly.

**Comment by guoshimin** [comment]
Well the behavior may be technically undefined, but can I request that in the future changes like this be mentioned in the release notes?

**Comment by kow3ns** [comment]
Yes, certainly. Also "The DaemonSet controller should not let two pods running at the same time on the same node." is not necessarily the same thing as respecting termination prior to launching a new Pod. The former implies a more strict requirement than the latter. I think we should consider at least attempting to wait for a terminating Pod to be deleted prior to creating another Pod on the Node for same DaemonSet as default behavior.

**Comment by dhilipkumars** [comment]
@kow3ns will something like [this](https://github.com/kubernetes/kubernetes/pull/50533) work then?
