### ISSUE TITLE
"failed to open log file" on privileged daemon set

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#50499]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The pods are stuck in `CrashLoopBackOff` with this error:

```
failed to open log file "/var/log/pods/3f68b784-7e57-11e7-979c-42010af000e6/hivemp-elasticsearch-nodeconfig_15.log": open /var/log/pods/3f68b784-7e57-11e7-979c-42010af000e6/hivemp-elasticsearch-nodeconfig_15.log: no such file or directory
```

**What you expected to happen**:
I expect the pods to start.

**How to reproduce it (as minimally and precisely as possible)**:
Running this daemon set on a GCE cluster on `1.7.3` (both master and nodes):
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"component":"hivemp-elasticsearch","role":"nodeconfig"},"name":"hivemp-elasticsearch-nodeconfig","namespace":"default"},"spec":{"template":{"metadata":{"labels":{"name":"hivemp-elasticsearch-nodeconfig"}},"spec":{"containers":[{"command":["bash","-c","sysctl -w vm.max_map_count=262144 \u0026\u0026 (while [ 0 -eq 0 ]; do sleep 10; done)"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"hivemp-elasticsearch-nodeconfig","resources":{"requests":{"cpu":"0m"}},"securityContext":{"privileged":true}}]}}}}
  creationTimestamp: 2017-08-11T05:38:04Z
  generation: 1
  labels:
    component: hivemp-elasticsearch
    role: nodeconfig
  name: hivemp-elasticsearch-nodeconfig
  namespace: default
  resourceVersion: "26048395"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/hivemp-elasticsearch-nodeconfig
  uid: 3f65f984-7e57-11e7-979c-42010af000e6
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: hivemp-elasticsearch-nodeconfig
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: hivemp-elasticsearch-nodeconfig
    spec:
      containers:
      - command:
        - bash
        - -c
        - sysctl -w vm.max_map_count=262144 && (while [ 0 -eq 0 ]; do sleep 10; done)
        image: busybox
        imagePullPolicy: IfNotPresent
        name: hivemp-elasticsearch-nodeconfig
        resources:
          requests:
            cpu: "0"
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 3
  observedGeneration: 1
  updatedNumberScheduled: 3
```

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: Google Container Engine
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by feiskyer** [comment]
Confirmed the bug in dockershim, filed #50509 to fix this.

**Comment by feiskyer** [comment]
@hach-que @Random-Liu Changed a environment and didn't make to reproduce the log problem.

With provided manifests, the pod did fail in CrashLoopBackOff, but it is because `bash` not found in busybox image:

```
:~# kubectl get pod
NAME                                    READY     STATUS                                                                                                                                                   RESTARTS   AGE
hivemp-elasticsearch-nodeconfig-ftfxt   0/1       rpc error: code = 2 desc = failed to start container "a12cc35dfa6fc22482c666b53f5d7c1ff6562829437b2a72a7846d509c62562e": executable not found in $PATH   0          9s
```

And in container status, there is indeed errors of reading container logs:

![image](https://user-images.githubusercontent.com/676637/29705991-df5e7450-89b2-11e7-8df6-ed8b06d618cf.png)

After changing the `bash` to `sh`, it should run properly.

@Random-Liu Although #50509 didn't fix the crash problem, it still helps on termination messages.

**Comment by Random-Liu** [comment]
@feiskyer Yeah, that's what I thought. The log stuff is not the cause of the crashloop.

Even you create symlink after fail to start container, it still doesn't fix the problem completely. After create the container, there is not log, and if `GetPodStatus` is called at that time, you will still have this error.

So the problem is not that we should create symlink after start failure, we should let `GetPodStatus` tolerant log file not exist.

Another problem with this issue is that I saw the termination message policy is `File`. Why does kubelet still try to read message from the log?

**Comment by feiskyer** [comment]
> After create the container, there is not log, and if GetPodStatus is called at that time, you will still have this error.

Maybe we should return empty if the log file doesn't exist?

> Another problem with this issue is that I saw the termination message policy is File. Why does kubelet still try to read message from the log?

This is because kubelet always fallback to logs if it fails to get from terminationMessagePath.

**Comment by smarterclayton** [comment]
That if block definitely doesn't belong there...

**Comment by smarterclayton** [comment]
Or rather, I'm wondering if we should not be reporting the error at all when it's File.

**Comment by smarterclayton** [comment]
We should never fall back to logs if it is File.  Which code would do that (fallbackToLogs or false is always returned)

**Comment by smarterclayton** [comment]
Opened a change to correctly fall back to logs if the termination message path file does not exist (as we do if the file is empty).

While this may actually hide other errors (like #52502) it matches the intent of FallbackToLogsOnError.

**Comment by giacomolicari** [comment]
@hach-que did this work for you? I'm experiencing the same problem and opened an issue here: https://github.com/kubernetes/kubernetes/issues/54474

**Comment by vamsi248** [comment]
these are my logs i am getting in kubernetes.. i am running from jenkins by using kubernetes-plugin  
making base image as jenkins/jnlp-slave  whats this means exactly .. this error?
failed to open log file "/var/log/pods/70d9def9-ebf7-11e7-867e-005056bf5570/jnlp_0.log": open /var/log/pods/70d9def9-ebf7-11e7-867e-005056bf5570/jnlp_0.log: no such file or directory

**Comment by lrepolho** [comment]
Maybe you're here because you made the same mistake as I did: My image was trying to execute an ENTRYPOINT in a file that didn't exist. I discovered that by executing: ```kubectl inspect pod <podname>```
