### ISSUE TITLE
Content negotiation incorrect when Accept header uses type parameters

### ISSUE THREAD

**Issue by spadgett** [kubernetes/kubernetes#50519]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

I'm trying to use `PartialObjectMetadataList`, but fallback to JSON if the server doesn't support `PartialObjectMetadataList`.

Requests with the following Accept headers fail against 1.6, which doesn't support `PartialObjectMetadataList`. They should fall back to JSON.

```
Accept: application/json;as=PartialObjectMetadataList;v=v1alpha1;g=meta.k8s.io, application/json
```

```
{
  "metadata": {},
  "status": "Failure",
  "message": "only the following media types are accepted: application/json, application/yaml, application/vnd.kubernetes.protobuf",
  "reason": "NotAcceptable",
  "code": 406
}
```

Requests with the following Accept header in 1.7 return JSON, but they should return the more specific type per RFC 7231.

```
Accept: application/json, application/json;as=PartialObjectMetadataList;v=v1alpha1;g=meta.k8s.io
```

https://tools.ietf.org/html/rfc7231#section-5.3.2

```
   Media ranges can be overridden by more specific media ranges or
   specific media types.  If more than one media range applies to a
   given type, the most specific reference has precedence.  For example,

     Accept: text/*, text/plain, text/plain;format=flowed, */*

   have the following precedence:

   1.  text/plain;format=flowed

   2.  text/plain

   3.  text/*

   4.  */*
```

**How to reproduce it (as minimally and precisely as possible)**:

The following command returns an error rather than JSON:

```
$ curl -k -H 'Accept: application/json;as=BOGUS;v=v1alpha1;g=meta.k8s.io, application/json' https://127.0.0.1:8443/api/v1/namespaces/node/pods
{
  "metadata": {},
  "status": "Failure",
  "message": "only the following media types are accepted: application/json, application/yaml, application/vnd.kubernetes.protobuf",
  "reason": "NotAcceptable",
  "code": 406
}
```

The following command returns the full JSON when it should return only object metadata:

```
$ curl -k -H 'Accept: application/json, application/json;as=PartialObjectMetadataList;v=v1alpha1;g=meta.k8s.io' https://127.0.0.1:8443/api/v1/namespaces/node/pods
```

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v1.7.0+695f48a16f

@liggitt

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery-bugs @smarterclayton

**Comment by smarterclayton** [comment]
Yeah, negotiation has an early loop for valid parameters, and then a later loop for actual content type resolution for conversion.  I think this can be solved correctly by having the delegation in the loop (there's a todo there i think)

**Comment by shiywang** [comment]
@smarterclayton @liggitt  not sure if i fully understand this issue, but according your comments, I guess the fix is like this, ptal, thanks

**Comment by shiywang** [comment]
@smarterclayton after test, seems this may not fix the problem, I would like to continue take a look if you think is ok.

**Comment by mml** [comment]
cc @caesarxuchao
