### ISSUE TITLE
dependency broken: <cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util">

### ISSUE THREAD

**Issue by yiakwy** [kubernetes/kubernetes#50526]
/kind bug
@kubernetes/sig-auth-bugs
@kubernetes/sig-cli-bugs
the cmdutil package cannot be found in the path "k8s.io/kubernetes/pkg/kubectl/cmd/util".

After diving into Kubernetes auth source code, I want to identify from kubectl to kube-proxy at which part, authentication happens in the traffic flow.

According to the documentation, user first send request to Identity provider, for example GCE using gcloud SDK through oauth2. Then users or accounts visit authentication and authorisation server using "id_token", "access_token", "refresh_token" for subsequent requests.

## QUESTION
**Hence I need track the visiting traffic to find out where (in which package) and when (some part of the codes handles authentication when request coming, http server should be used here).**

It took a few days to go through the relevant codes in following structure
``` bash
k8s.io
├── api/
│       ...
├── kubernetes/
│   │   ...
│   ├──	pkg
│   │	│   ...
│   │   └── apis
│   │	    ├── abac
│   │	    ├── admission
│   │	    │   ..
│   │	    ├── authentication
│   │	    ├── authorization
│   │	    │   ..
│   │	    ├── certificates
│   │	    │   ...
│   │	    └── policy
│   ├── auth(empty)
│   ├── controller
│   │	│   ...
│   │	└── certificates
│   │       ├── approver
│   │       └── signer
│   ├── plugin
│   │		
│   └── cmd
│   	...
├── apiserver/
│   │   ...
│   └── pkg
│       │   ...
│       ├── authentiation
│       │   └── authenticator 
│       │       └── interfaces.go (token, password, )
│       │       ...
│       └── autherization
│           └── authorizaer
│               └── interfaces.go (attributes)
│               ...
└── client-go/
		...
```

But I still have troubles to identify those issues. SOS!

**Comment by liggitt** [comment]
I'm not sure exactly what the question is... 

the referenced package is at https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/util

the different providers that kubectl uses to fetch dynamic credentials are at https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth

the transport that is built from a kubeconfig file (including a static bearer token or dynamic auth provider) is at https://github.com/kubernetes/client-go/blob/master/rest/transport.go

**Comment by yiakwy** [comment]
Hi @liggitt , I have finished a article introducing authentication in k8s. I wish that you could kindly figure out what's the problem with it.
