### ISSUE TITLE
Federated service DNS should be created for all zones

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/kubernetes#50529]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

If a federated cluster is a multi-zone cluster, then when a federated `LoadBalancer` type service is created, there is only one zone DNS record created. For example:

```
# This cluster spans three zones
➜  kubernetes git:(master) kubectl --context=hurley-beta-federation get cluster beta-us-west-2 -o json | jq '.status'
{
  "conditions": [
    {
      "lastProbeTime": "2017-08-11T17:36:25Z",
      "lastTransitionTime": "2017-08-08T15:15:40Z",
      "message": "/healthz responded with ok",
      "reason": "ClusterReady",
      "status": "True",
      "type": "Ready"
    }
  ],
  "region": "us-west-2",
  "zones": [
    "us-west-2a",
    "us-west-2b",
    "us-west-2c"
  ]
}

```

In Route53 console, I only see DNS records for one of the zones (`us-west-2a`). Same thing for `us-east-1` federated cluster too.

![route53](https://user-images.githubusercontent.com/464299/29223594-23ce6f38-7e95-11e7-96ee-464969e84e9c.png)

I also see the following in `kube-dns` logs when I tried to resolve `nginx.default.k8s-beta-federation` locally:

```
I0810 20:31:17.072874       1 dns.go:636] Federation: skipping record since service has no endpoint: {10.5.35.160 0 10 10  false 30 0  /skydns/local/cluster/svc/default/nginx/6466336132663632}
I0810 20:31:17.147368       1 logs.go:41] skydns: incomplete CNAME chain from "nginx.default.my-federation.svc.us-west-2b.us-west-2.mycompany.com.": rcode 3 is not equal to success
```

**What you expected to happen**:

DNS records should be created for each zone of the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1. Launch a multi-zone cluster.
2. Join this cluster to a federation.
3. Create a federated service with `LoadBalancer` type.

**Anything else we need to know?**:

It looks like, as of v1.7.3, this behavior is [by design](https://github.com/kubernetes/kubernetes/blob/v1.7.3/federation/pkg/federation-controller/service/dns/dns.go#L510). I think we should address that `TODO` and add support for multi-zone clusters.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): `Container Linux by CoreOS 1353.7.0 (Ladybug)`
- Kernel (e.g. `uname -a`): `Linux ip-10-72-230-146.ec2.internal 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz GenuineIntel GNU/Linux`
- Install tools: `Custom tool`
- Others:

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#26.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
