### ISSUE TITLE
PV status is set to "Released" automatically even if its bound to a PVC

### ISSUE THREAD

**Issue by akgunjal** [kubernetes/kubernetes#50521]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: 
There were a bunch of PVCs which were in bound state. The PVs associated with the PVCs got their status changed to "Released" without me triggering PVC delete. This resulted in PV deletion due to my reclaim policy set to "Delete". The PVC went into Lost state as a result. Why this PV state is changed automatically ?

**What you expected to happen**:
The PV status should not be updated when its bound to a PVC without manual trigger

**How to reproduce it (as minimally and precisely as possible)**:
Not known as this is auto change of status in PV

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.5.6

**Comment by zhangxiaoyu-zidif** [comment]
PV's status change to "released" automatically without any operations?
Could you list more details about your problem, such as env. , PV config file, PVC config file, etc.

**Comment by akgunjal** [comment]
@zhangxiaoyu-zidif : Please find the details requested.
(1) ENV: Kubernetes 1.5.6
(2) We are using dynamic provisioner where the deletion of PVC will call our provisioner which will check if the state of PV is "Released" and then proceed with delete of the backend storage.
Sample PVC yaml:

_**kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcname # user can choose any name as per kubernetes
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-custom"
spec:
  accessModes:
    - ReadWriteMany # access mode
  resources:
    requests:
      storage: 20Gi
iops: "100"**_


Another data point I would like to provide is we have etcd snapshots enabled in our cluster. And when we saw this issue, there was etcd restart triggered around the same time. Could the etcd restart cause the PV records to be updated? There was no manual intervention and the state of PV was changed so I want to know if etcd restart can impact this behavior.

**Comment by zhangxiaoyu-zidif** [comment]
etcd is very important to Kubernetes. Actually, almost all data store in etcd. Maybe etcd restart result in PV's released. How much time does your etcd restart. If very transient, It should not. But I like to reproduce it in my env. =)
btw, how many PVs and PVCs you config?

**Comment by akgunjal** [comment]
The etcd restart is not very frequent and this issue we have got on some occasions. But we are not able to reproduce the problem yet. Can you provide a pointer if there is a way to reproduce this issue with snapshots enabled?

In what scenario etcd restart can change the PV to released as the PV was in bound state before restart?

We had around 80 PVs bound to PVCs when the issue happened. All PVs got deleted and we lost the backend storage volumes with data. This is an important issue without which we cannot roll-out our solution to production since data loss can occur here if it happens in production.

**Comment by zhangxiaoyu-zidif** [comment]
Seems to be a very serious problem.
/cc @xiang90 @spiffxp @jingxu97

**Comment by zhangxiaoyu-zidif** [comment]
@akgunjal 
In order to avoid this problem, I suggest that you can setup a HA cluster, which has three masters and etcds.

**Comment by akgunjal** [comment]
@zhangxiaoyu-zidif : As we dont know the cause of the issue, having changes in cluster is not sure will resolve the issue. Is there a known issue here with etcd?

**Comment by jingxu97** [comment]
@akgunjal could you provide some logs (controller-manager log) around that time?  Thanks!

**Comment by jingxu97** [comment]
cc @jsafrane

**Comment by jingxu97** [comment]
@akgunjal Talk with @jsafrane offline about this issue. We believe etcd restart should not change the status of PV/PVC. Do you have any operations performed around that time?

**Comment by zhangxiaoyu-zidif** [comment]
@jingxu97  If the etcd stay in-acive for a long time, and then restart. Is that possible?

**Comment by akgunjal** [comment]
@jingxu97 : I am checking with @jsafrane offline. I have also seen etcd timeouts for during the time when issue occurred. Can that be one of the possible causes?

**Comment by akgunjal** [comment]
@jingxu97 @jsafrane : As we are not able to reproduce the issue and there is no update to this ticket yet about the cause of such an issue we have done a handling in our delete flow in the dynamic provisioner.

In delete call:
1. We check the claim ID from PV object and verify if the PVC exists.
2. If we get any error in fetching the PVC object then we do not delete the PV object.
3. We also fetch all PVCs from all namespaces and check if any PVC has a reference to this PV being deleted.

We are doing this to avoid any accidental deletes due to the kind of issue we faced earlier. Let me know your feedback on this handling.

**Comment by jingxu97** [comment]
@akgunjal Are you plan to add these checking code in pv_controller directly or some other way?

**Comment by jsafrane** [comment]
@akgunjal, it should help to prevent this bug, but it would be nice to find the root cause.

**Comment by akgunjal** [comment]
@jingxu97 : The change we plan to do in our dynamic provisioner.

@jsafrane : Since we are not able to root cause or reproduce this issue and also there is no possible causes from community we are trying to prevent it as much possible.

**Comment by jsafrane** [comment]
@akgunjal, today I discovered https://github.com/kubernetes/kubernetes/issues/48081 that has similar symptoms. It is related to controller-manager startup though - do you remember restarting the controller-manager process before the bug appeared?

In case you still have the controller logs from time where the bug appeared, can you check if you see `PersistentVolumeController can't initialize caches` there?

**Comment by akgunjal** [comment]
@jsafrane : I will check if the logs are still present and search for the above log message. I will also be watching the other GHE issue for updates on this.

**Comment by msau42** [comment]
@akgunjal do you still see this issue?

**Comment by akgunjal** [comment]
@msau42 : This issue is not reproducible as we do not know what causes this issue. It had happened few times for us in our clusters. So the issue is actually not resolved as the cause of this issue is not known yet.

**Comment by akgunjal** [comment]
Closing this issue for now as its not reproducible and not found so far in later versions of kubernetes.
