### ISSUE TITLE
Federation presubmit test failing on release-1.7, blocking merges

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#50534]
It's continuously failing during the federation-up step, due to the following (seems like mismatch in the registered rbac group version):

```
W0810 21:38:15.817] I0810 21:38:15.642420    3922 request.go:782] Error in request: no kind "Role" is registered for version "rbac.authorization.k8s.io/v1"
W0810 21:38:15.817] F0810 21:38:15.642497    3922 helpers.go:120] error: no kind "Role" is registered for version "rbac.authorization.k8s.io/v1"
```

Recently opened PRs are affected due to this:
https://github.com/kubernetes/kubernetes/pull/50458
https://github.com/kubernetes/kubernetes/pull/50459
https://github.com/kubernetes/kubernetes/pull/50513
https://github.com/kubernetes/kubernetes/pull/50517

Strangely, this one went through:
https://github.com/kubernetes/kubernetes/pull/50514

cc @kubernetes/sig-federation-bugs @kubernetes/test-infra-maintainers @madhusudancs

**Comment by shyamjvs** [comment]
cc @fejta @krzyzacy

**Comment by nikhiljindal** [comment]
Am looking into this.

https://github.com/kubernetes/kubernetes/pull/50514 went through because its for master and not release-1.7

I know we had fixed the `Role` issue once before. (That was kubectl caching). Not sure if the same issue has resurfaced or this is different.

**Comment by shyamjvs** [comment]
Coo!. Misread it because of 1.7 milestone on it.
Thanks for looking into it :)

**Comment by nikhiljindal** [comment]
@shyamjvs Can you point me to where you saw the `no Kind Role` error?

Looking at the build logs, I just see the following which doesnt provide any information:
```
I0811 13:11:59.877] Starting pull-kubernetes-federation-e2e-gce-20216...
E0811 13:11:59.878] Command failed
I0811 13:11:59.878] process 19895 exited with code 1 after 23.5m
E0811 13:11:59.878] FAIL: pull-kubernetes-federation-e2e-gce
I0811 13:11:59.879] Upload result and artifacts...
```

Example build logs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50458/pull-kubernetes-federation-e2e-gce/20329/?log#log

**Comment by shyamjvs** [comment]
It's in the full log - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50458/pull-kubernetes-federation-e2e-gce/20329/build-log.txt

**Comment by nikhiljindal** [comment]
Thanks!
@madhusudancs pointed out that we are using clusters from HEAD in all release branch testing.
I see rbac.authorization.k8s.io was recently promoted to v1 in https://github.com/kubernetes/kubernetes/pull/49642, but I dont see any obvious reason why that would break.
cc @liggitt as FYI.

**Comment by liggitt** [comment]
looks like kubefed tries to speak whatever version of RBAC the server has, regardless of whether it knows about that version or not. the version discovery it does has to select a version both it and the server speak.

**Comment by nikhiljindal** [comment]
Thanks for sending https://github.com/kubernetes/kubernetes/pull/50538 to fix this @liggitt 
I have filed https://github.com/kubernetes/kubernetes/issues/50540 to fix the generic issue.

**Comment by shyamjvs** [comment]
Closing this issue as it's solved now.
Thanks for fixing @nikhiljindal @liggitt.
