### ISSUE TITLE
Do not leak GCE PD in federation tests

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#50543]
Our ci tests started failing sometime yesterday (https://k8s-testgrid.appspot.com/sig-federation) with errors such as:
```
Error: 1 leaked resources
[ disks ]
+prow-us-central1-f-dyn-pvc-d11b7df7-7eed-11e7-a35f-42010a80000a  us-central1-f  10       pd-standard  READY
```

@madhusudancs pointed out that we have always been leaking the GCE PD provisioned using Dynamic provisioning, we probably updated our tests now to catch it.

ci tests on HEAD and all release branches are now failing.

cc @kubernetes/sig-federation-bugs

**Comment by madhusudancs** [comment]
@quinton-hoole this is the PV/PD quota issue. I don't know whom to assign this. Would you be able to find someone?

@shashidharatd you have the most context here. Would you mind taking this up?

**Comment by madhusudancs** [comment]
Some pointers:

1. Before deleting the PV, get the associated PD name from the PV object here: https://github.com/kubernetes/kubernetes/blob/0d17e9deb7188bc79d905cb4ef6911c0a27adc59/federation/cluster/common.sh#L81
2. Run gcloud command to delete that PD.
3. Wait until the PD is gone before proceeding.

**Comment by madhusudancs** [comment]
/assign @quinton-hoole to find an owner.

@shashidharatd feel free to self-assign if you like to own this.

**Comment by shashidharatd** [comment]
/assign
Thanks @madhusudancs, i will work on this.

**Comment by shashidharatd** [comment]
linking the associated issue https://github.com/kubernetes/kubernetes/issues/23032
Deleting the dynamically provisioned PV is not deleting the PD in GCE because of may be 2 reasons:
1. The cluster is brought down soon after deleting the PV giving no room for controller to act on it, so PD is leaked.
2. There could be a bug due to which delete PD is not called by controller for dynamically provisioned PV.

either way as suggested by @madhusudancs, we should clean up resources by identifying the PD and delete it in cleanup script (federation-down.sh).

**Comment by shashidharatd** [comment]
cc @saad-ali

**Comment by madhusudancs** [comment]
@shashidharatd +1

**Comment by ericchiang** [comment]
Was there a reason this was moved to 1.9? This is a constant red that's messing with our e2e test signal https://k8s-testgrid.appspot.com/release-master-blocking#gce-federation

**Comment by madhusudancs** [comment]
It's has been a known issue since 1.4. We would ideally get it fixed in 1.8 timeframe, there is no reason to block 1.8 for this.

**Comment by shashidharatd** [comment]
GCE PD leaking issue seems to be resolved now by PR #51768. Hence closing this issue.
/close

**Comment by csbell** [comment]
Assigning to @wojtek-t to merge #51768 back into 1.7 to go green over there.

**Comment by wojtek-t** [comment]
I added appropriate labels - will handle cherrypicking the PR.
