### ISSUE TITLE
kubefed should use an API version that both it and server uses

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#50540]
Forked from https://github.com/kubernetes/kubernetes/issues/50534#issuecomment-321940562.

kubefed does API version discovery and then uses the preferred API group version that server supports. This breaks when server supports a newer version that the generated clientset that kubefed uses does not know about.
kubefed should choose the version that both server and it knows about.

https://github.com/kubernetes/kubernetes/pull/50537 fixes this for RBAC. We need the same for all API resources that kubefed creates.

cc @kubernetes/sig-federation-bugs @liggitt

**Comment by nikhiljindal** [comment]
As per discussion in https://github.com/kubernetes/kubernetes/pull/50537#discussion_r132804742, we do this only for RBAC. We should change that to match with what we do at other places (require the server to support a specific version, no discovery and preference required)

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#27.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
