### ISSUE TITLE
Sign error in comment on resource.ScaledValue

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#50564]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I invoked `ScaledValue(-9)` on a resource.Quantity, and got a result that was multiplied by a factor of 10^9.

**What you expected to happen**:
I expected to get a value that was multiplied by a factor of 10^-9, because the comment says "ScaledValue returns the value of ceil(q * 10^scale)".

**How to reproduce it (as minimally and precisely as possible)**:
```
q, _ := resource.ParseQuantity("10")
i := q.ScaledValue(-1)
```
print `i`.  You will find it is 100, not 1.

**Anything else we need to know?**:
Look at the meaning of the `AsScaledInt64` method invoked in the integer case.  This method returns the quantity expressed as a multiple of 10^scale.  10 is 100 tenths.

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by MikeSpreitzer** [comment]
@kubernetes/@sig-apimachinery-bugs

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-apimachinery-bugs

**Comment by dixudx** [comment]
@MikeSpreitzer I looked through all the testcases and found that it actually should means `ceil(q / 10^scale)`. Already fixed this in PR #50571. PTAL.

**Comment by MikeSpreitzer** [comment]
I see your PR and have given it LGTM.  It has not merged yet.  Thanks.

**Comment by mml** [comment]
cc @cheftako

**Comment by MikeSpreitzer** [comment]
@wojtek-t: I do not understand your remark at https://github.com/kubernetes/kubernetes/pull/50571#pullrequestreview-57017061 .  When I look at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L708 right now, I see
```
// ScaledValue returns the value of ceil(q * 10^scale); this could overflow an int64.
```

But that is backwards.  It returns the value of `ceil(q / 10^scale)`.

**Comment by MorrisLaw** [comment]
Should this issue be closed because of merged PR [#50571](https://github.com/kubernetes/kubernetes/pull/50571)? Or is there more work to be done for this issue?

**Comment by MikeSpreitzer** [comment]
I am sorry, but the comment was and remains wrong.  I updated that PR with some support.

**Comment by nikhita** [comment]
/remove-lifecycle stale

I am going to label this as a good-first-issue because this involves a comment update.

If you are interested in picking up this issue, create the changes as that of https://github.com/kubernetes/kubernetes/pull/50571 (add additional details if necessary). https://github.com/kubernetes/kubernetes/pull/50571 was closed down but looks like the comment is still incorrect. Would be good to clean it up or at least revive the discussion to make sure that the comment is correct.

/good-first-issue

**Comment by MikeSpreitzer** [comment]
/remove-lifecycle stale
The comment is still wrong.  Maybe this should be assigned to someone other than @jpbetz ?

**Comment by josiahbjorgaard** [comment]
I'm looking for a good first issue, will happily take this

**Comment by MikeSpreitzer** [comment]
@josiahbjorgaard : thanks.  I can not assign this to you.  Can you submit a PR?

**Comment by josiahbjorgaard** [comment]
I can submit a PR.

**Comment by MikeSpreitzer** [comment]
@josiahbjorgaard please feel invited to do so.

**Comment by josiahbjorgaard** [comment]
@MikeSpreitzer I've tested the behavior of ScaledValue and created PR #79738 with the changed comment.

**Comment by MikeSpreitzer** [comment]
There are existing test cases in the `TestScaledValue` function in `quantity_test.go` that also show that the comment is wrong.  For example, the test case `{Micro, Nano, 1000}` shows that NewScaledQuantity(1, -6).ScaledValue(-9) produces 10 to the power of 3 (that's (-6)-(-9)) rather than -15 (that would be (-6)+(-9)).
