### ISSUE TITLE
Addon resizer v2.0 significantly decreases resources for Heapster

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#50599]
Resources assigned to Heapster on 1000 nodes cluster:

with version 1.7
765m
5.6G

with version 2.0
540m
4.6GB

Heapster tends to OOM from time to time with the latter parameters.

**Comment by piosz** [comment]
cc @mwielgus @fgrzadkowski

**Comment by x13n** [comment]
@piosz Version 1.7 had bigger buckets, so some difference is expected. What parameters are you invoking pod_nanny with? With the default ones (80mCPU + 0.5mCPU per node, 140Mi + 4Mi per node, acceptance offset 20%), current requirements are within bounds for 1k cluster:

80+(0.5*1000 - 20%) = 480 < 540mCPU
140+(4*1000 - 20%) = 3340 < 4.6GB

I can bump memory per node from 4Mi to 6Mi, in which case 4.6GB would fall below expectations (4.94GB) so more memory would be requested (5.54GB with immediate resize to 1000 nodes, but may be less with gradual cluster size increase).

Actually, how were current base & per node memory requests determined?

**Comment by fgrzadkowski** [comment]
@x13n I believe the fact that it's expected doesn't mean it's correct. Basically you're saying "working as implemented" ;) Let's make sure that heapster configuration is correct.

**Comment by piosz** [comment]
@x13n in the previous version the approach was: we assign **at least** 80+n*0.5 mCPU and 140 + n*4 MB.

**Comment by x13n** [comment]
Right, with acceptance offset of 20% it should be 100+n*0.625 and 175+n*5 MB. I'll prepare a PR today.

**Comment by piosz** [comment]
As this is not fixed we decided to revert #46850.

**Comment by spiffxp** [comment]
Is this still a release-blocker for 1.8? Seems like since the offending change has been reverted we can kick this out of v1.8 milestone

**Comment by piosz** [comment]
@spiffxp correct, removing 1.8 milestone

**Comment by x13n** [comment]
Tested on 1000 node cluster. Coefficients above don't seem to be enough. Works with the following though:
      --cpu=100m
      --extra-cpu=0.7m
      --memory=175Mi
      --extra-memory=6Mi

With default recommendation offset of 10% this results in:

730m
5575Mi

for 1k nodes, which both works & is pretty close to the previous values. I will update this PR with those values.

**Comment by x13n** [comment]
We're not using nanny 2.0, so closing.
/close

**Comment by liggitt** [comment]
heapster removed in 1.13
