### ISSUE TITLE
Switch storage version for networking.k8s.io/v1 and extensions/v1beta1's networking types to networking.k8s.io/v1

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#50604]
This includes updating `hack/test-update-storage-objects.sh` with a test to switch off `extensions/v1beta1` in order to verify that `networking.k8s.io/v1` keeps working, compare https://github.com/kubernetes/kubernetes/pull/50327#discussion_r132570895.

**Comment by cmluciano** [comment]
Do we still want this for 1.8?

**Comment by danwinship** [comment]
Yes, I think so...

I started looking at this the other day, but I have no idea what actually needs to be done

**Comment by sttts** [comment]
We use cohabitation to store the networking objects in extensions. It's defined here: https://github.com/kubernetes/kubernetes/blob/55cb667b9ec975664609e736f49713ee24419b81/cmd/kube-apiserver/app/server.go#L569

Moreover, test/integration/etcd/etcd_storage_path_test.go must be adapted to test the new storage version, but old storage path.

**Comment by danwinship** [comment]
/kind cleanup
/priority important-soon

(I'm guessing on those, feel free to override)

**Comment by cmluciano** [comment]
xref: #51673

**Comment by caesarxuchao** [comment]
Also please add the networking group to the hack/test-update-storage-objects.sh (https://github.com/kubernetes/kubernetes/pull/50327#discussion_r133102601).

@danwinship could you please ping me when you have the PR? I'm curious to learn where to change the storage versions today.

**Comment by cmluciano** [comment]
Is this safe to make post freeze?

cc @thockin @caesarxuchao

**Comment by thockin** [comment]
probably.  @jdumars

**Comment by jdumars** [comment]
Could you help me understand the risks associated with this going in after freeze?  I assume this is technical debt reconciliation, but would love to know more context.

**Comment by sttts** [comment]
Is this done meanwhile?

**Comment by danwinship** [comment]
No, see #51955. No one seems to know exactly what needs to be done.
