### ISSUE TITLE
Kubernetes fails to configure AWS ELB properly

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#50608]
I am running a Kubernetes 1.7.0 cluster on aws managed by kops. I have seen at least 2 scenarios where listeners of an ELB created for a `LoadBalancer` type service is not configured properly.

case 1:
I have a LoadBalancer type service without any aws specific annotations. Then I apply the following annotations:
- "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443",
- "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:...",
- "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"

I see that ELB does not have certificate configured properly on listener for 443.

case 2:
I have a LoadBalancer type service without any aws specific annotations. Then I apply the following annotations:
- "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:...",

Then I updated it to have the above 3 annotations and also added port 443 -> 80 on the service. I see that listener for port 80 is not configured as HTTP protocol and correct NodePort.

/sig aws

**Comment by tamalsaha** [comment]
@kubernetes/sig-aws

**Comment by nbutton23** [comment]
@tamalsaha when you make the changes do you see errors in the logs for kube-controller-manager or anything in the events for the service?  I have seen ELBs not get updated if there was an error.

**Comment by tamalsaha** [comment]
I checked the logs for controller manager . I did not see any errors.

**Comment by lpabon** [comment]
I _think_ that some of these annotations are only viewed and used during creation.

**Comment by josephtyler** [comment]
I'm also having issues with this. I'm on version 1.7.6. Even when the cluster is created I'm not seeing the ELB configured properly. It appears that it's not respecting the annotations at all.

**Comment by williamlord** [comment]
Same, although gradually adding the annotations one by one does work.

**Comment by kiich** [comment]
I'm also seeing 1 specific annotation not taking effect even at creation time/update time
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: foo.bar
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
```
Using kube 1.9.3 though so wasn't sure if that annotation is supported (which I assumed it was).

Have also tried adding it 1 by 1, so first only have the external dns one and then the backend-protocol one, which does not work for me.
