### ISSUE TITLE
kubectl --dry-run does not check spec.template.spec.containers.ports.name

### ISSUE THREAD

**Issue by k4k** [kubernetes/kubernetes#50619]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
`kubectl apply --dry-run` does not catch port names longer than 15 characters but `kubectl apply` without `--dry-run` will fail to deploy citing `spec.containers

```
The Deployment <deployment-name> is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: "<long-port-name>": must be no more than 15 characters
```

**What you expected to happen**:
`kubectl apply --dry-run` should run all of the same checks as `kubectl apply` without `--dry-run`

**How to reproduce it (as minimally and precisely as possible)**:
* Create resource file (deployment used in this example) with `spec.template.spec.containers.ports.name` set to a value > 15 characters.
* Run `kubectl apply -f <resource-file> --dry-run`
* Verify all checks passed
* Run `kubectl apply -f <resource-file>`
* Apply will fail citing the that `spec.template.spec.containers[0].ports[0].name: Invalid value`

**Anything else we need to know?**:
Full command output:
```
$ kubectl apply -f deployment-prometheus-pushgateway.yaml --dry-run
deployment "prometheus-pushgateway" created (dry run)
$ kubectl apply -f deployment-prometheus-pushgateway.yaml
The Deployment "prometheus-pushgateway" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: "pushgateway-endpoint": must be no more than 15 characters
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: bare metal v.1.7.3
- OS (e.g. from /etc/os-release): `PRETTY_NAME="CentOS Linux 7 (Core)"`
- Kernel (e.g. `uname -a`): `Linux <hostname> 4.4.69-1.el7.elrepo.x86_64 #1 SMP Sun May 21 18:00:33 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by k4k** [comment]
@kuberentes/sig-CLI

**Comment by xiangpengzhao** [comment]
Similar with #42057

/cc @smarterclayton @adohe

**Comment by Vickey-Wu** [comment]
hello , i got the same error, RELEASENAME include 18 chars, how can i solve this, any help would be appreciated.
```
Error: release RELEASENAME failed: Deployment.apps "RELEASENAME-chart" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: "RELEASENAME-service": must be no more than 15 characters
```

**Comment by Vickey-Wu** [comment]
forgot to close it, cut RELEASENAME no more than 15 characters is work for me

**Comment by vigu16** [comment]
Hi, I got the same issue  "spec.template.spec.containers[0].ports[0].name: Invalid Value: "xxxxxxx" must be no more than 15 characters. 

Is there a fix for this ? Can anyone help ?

**Comment by viniciusd** [comment]
Same here, `--dry-run` runs just fine while a kubectl straight doesn't. Isn't that `--dry-run` purpose as well?

**Comment by viniciusd** [comment]
Just saying that comes from `pkg/apis/core/validation/validation.go:260`
```
// IsValidPortName check that the argument is valid syntax. It must be
// non-empty and no more than 15 characters long. It may contain only [-a-z0-9]
// and must contain at least one letter [a-z]. It must not start or end with a
// hyphen, nor contain adjacent hyphens.
//
// Note: We only allow lower-case characters, even though RFC 6335 is case
// insensitive.
func IsValidPortName(port string) []string {
	var errs []string
	if len(port) > 15 {
		errs = append(errs, MaxLenError(15))
	}
```
Couldn't find about that 15 limit on the documentation though. Neither at the RFC 6335.

Also, `isValidPortName` gets called by `validateContainerPorts`

**Comment by viniciusd** [comment]
Just double-checked the RFC and found its syntax constraints:
```
5.1.  Service Name Syntax
   Valid service names are hereby normatively defined as follows:
   o  MUST be at least 1 character and no more than 15 characters long
   o  MUST contain only US-ASCII [ANSI.X3.4-1986] letters 'A' - 'Z' and
      'a' - 'z', digits '0' - '9', and hyphens ('-', ASCII 0x2D or
      decimal 45)
   o  MUST contain at least one letter ('A' - 'Z' or 'a' - 'z')
   o  MUST NOT begin or end with a hyphen
   o  hyphens MUST NOT be adjacent to other hyphens
```

**Comment by liggitt** [comment]
`--dry-run` does a client-side dry run. `--server-dry-run` actually submits the request to the server, so server-side validation (like unique port name and port name format validation) is performed. If you want full validation, use `--server-dry-run`.

/close
