### ISSUE TITLE
Rename --experimental-bootstrap-token-auth to --enable-bootstrap-token-auth

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#50613]
/kind feature

As part of https://github.com/kubernetes/features/issues/130, the `--experimental-bootstrap-token-auth` flag on the API server should be renamed to something like `--enable-bootstrap-token-auth`. We'll leave `experimental-bootstrap-token-auth` deprecated (should it be a no-op or not?) for v1.8.

Or we should consider adding an explicit `--authenticators` flag to the API server in the same way we have [`--controllers`](https://github.com/kubernetes/kubernetes/pull/39740) flag on controller-manager.
Right now, it enables/disables most authn plugins implicitely based on other flags (often pointing to various files on disk; if you specified a path to that file, you also want to enable this authn module)

What way do you prefer?
@kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-auth-feature-requests

**Comment by mattmoyer** [comment]
Rough plan:
1. (1.8) Add `--enable-bootstrap-token-auth`
1. (1.8) Make it an error to specify both `--experimental-bootstrap-token-auth` and `--enable-bootstrap-token-auth` (so we don't have to decide on precedence)
1. (1.8) Add a warning if `--experimental-bootstrap-token-auth` is used.
1. (1.9) Drop `--experimental-bootstrap-token-auth`

**Comment by luxas** [comment]
3. That is: Mark `--experimental-bootstrap-token-auth` deprecated.

cc @ericchiang @jbeda @liggitt @mikedanese Approve?

**Comment by mattmoyer** [comment]
/reopen

Re-opening because there's a little bit left to do in 1.9 (ready to go in https://github.com/kubernetes/kubernetes/pull/52551).
