### ISSUE TITLE
Change the places of the files under ~/.kube easily

### ISSUE THREAD

**Issue by acomagu** [kubernetes/kubernetes#50612]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
/kind feature
/sig cli

**What happened**:
I want to move `$HOME/.kube` dir to another place, but I feel it's little troublesome because several configs must be set up.

**What you expected to happen**:
Something like `--home-dir` option or `KUBE_HOME` environment path can change the default places of schema, cache and config.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu GNOME 17.04
- Kernel (e.g. `uname -a`): Linux 4.10.0-30-generic
- Install tools: Linuxbrew
- Others:

Thanks!

**Comment by razor-x** [comment]
Is there any current to do this via env vars or otherwise?

**Comment by vbmade2000** [comment]
Anyone working on this issue ? I want to work.
