### ISSUE TITLE
All release-1.5 jobs failing due to leaked resources (mainly master VM and network)

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#50624]
More details in issue https://github.com/kubernetes/test-infra/issues/4059

In short, all jobs against 1.5 branch are failing to delete the master VM (and hence also the master-pd) and route for the master (and hence also the network). For e.g:

```
W0814 10:39:48.504] ERROR: (gcloud.compute.disks.delete) Could not fetch resource:
W0814 10:39:48.504]  - The disk resource 'projects/k8s-gce-cvm-1-6-1-5-ctl-skew/zones/us-central1-f/disks/bootstrap-e2e-master-pd' is already being used by 'projects/k8s-gce-cvm-1-6-1-5-ctl-skew/zones/us-central1-f/instances/bootstrap-e2e-master'
```

```
W0814 10:40:52.170] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W0814 10:40:52.170]  - The network resource 'projects/k8s-gce-cvm-1-6-1-5-ctl-skew/global/networks/bootstrap-e2e' is already being used by 'projects/k8s-gce-cvm-1-6-1-5-ctl-skew/global/routes/bootstrap-e2e-8d2a127e-80c8-11e7-8d23-42010af00002'
```

For ref - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-release-1-5/296

cc @kubernetes/test-infra-maintainers @krzyzacy

**Comment by shyamjvs** [comment]
Furthermore, it says that the route is deleted:

```
I0814 15:58:06.922] Deleting routes bootstrap-e2e-a7268d24-8106-11e7-9770-42010af00002
W0814 15:58:23.712] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-e2e-gce-f8n-1-5/global/routes/bootstrap-e2e-a7268d24-8106-11e7-9770-42010af00002].
```

but later complaints with:

```
W0814 15:58:53.258] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W0814 15:58:53.258]  - The network resource 'projects/k8s-e2e-gce-f8n-1-5/global/networks/bootstrap-e2e' is already being used by 'projects/k8s-e2e-gce-f8n-1-5/global/routes/bootstrap-e2e-a7268d24-8106-11e7-9770-42010af00002'
```

**Comment by shyamjvs** [comment]
cc @k8s-mirror-cluster-lifecycle-bugs - Could someone PTAL?

**Comment by krzyzacy** [comment]
I think it is: gcloud has an issue that leaks entire master node, so we reverted gcloud back to 163.0.0 until very recent, but all 1.5 jobs still update gcloud to latest.

e2e jobs are using a different project each run and will be cleaned up right after a run finishes, so they are all fine. Kubemark job pins to a specific project so it's not going to recover.

**Comment by krzyzacy** [comment]
i.e. https://github.com/kubernetes/kubernetes/pull/36292 is not in 1.5

**Comment by shyamjvs** [comment]
> e2e jobs are using a different project each run and will be cleaned up right after a run finishes, so they are all fine.

This still doesn't seem so clean as we're relying on something else for clean-up iiuc. Ideally, our cluster kube-down script should delete everything (as one would expect).

> Kubemark job pins to a specific project so it's not going to recover.

Can we do something to solve this? Unpin the kubemark-1.5 job or sth?

**Comment by shyamjvs** [comment]
> I think it is: gcloud has an issue that leaks entire master node, so we reverted gcloud back to 163.0.0 until very recent, but all 1.5 jobs still update gcloud to latest.

Btw - I just checked from within the container for kubemark-1.5 job and it seems like it's also using 163.0.0 :

```
root@05c023e7550e:~# gcloud version
Google Cloud SDK 163.0.0
alpha 2017.03.24
beta 2017.03.24
```

**Comment by krzyzacy** [comment]
Yes, before https://github.com/kubernetes/kubernetes/pull/36292, in the run it will upgrade gcloud to latest, that's the real issue :-)

**Comment by krzyzacy** [comment]
(Probably someone need to fix https://github.com/kubernetes/kubernetes/issues/49673)

**Comment by shyamjvs** [comment]
I see. Can we disable the upgrade somehow?

**Comment by krzyzacy** [comment]
Do you want to cherrypick #36292 to 1.5?

**Comment by shyamjvs** [comment]
Sent out the cherrypick PR. Hopefully fixes the issue.

**Comment by krzyzacy** [comment]
On a side note, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/2315?log#log which uses cloud sdk staging bucket and is now passing, I would expect the issue to be fixed from gcloud side very soon. (when they push their next release?)

**Comment by pci** [comment]
If it's helpful, I have a PR open for #49673: https://github.com/kubernetes/kubernetes/pull/50398

**Comment by shyamjvs** [comment]
@pci Thanks for the PR, that should definitely be helpful. Also it should be cherry-picked to 1.6 and 1.7 later.

**Comment by shyamjvs** [comment]
This issue has been fixed after merging my cherry-pick above:
https://k8s-testgrid.appspot.com/release-1.5-all#gci-1.5
https://k8s-testgrid.appspot.com/sig-scalability#kubemark-small-1.5
