### ISSUE TITLE
SAR approver for node server certs should verify SANs

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#50635]
The current mechanism of trusting self reported IPs and hostnames is broken.

**Comment by mikedanese** [comment]
depends on https://github.com/kubernetes/community/pull/911

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by nckturner** [comment]
@mikedanese If this is being closed in favor of other issues, can you reference them here?

**Comment by mikedanese** [comment]
I'm closing because the a SAR doesn't trust self reported ips anymore. https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/approver/sarapprove.go#L215

**Comment by mikedanese** [comment]
also related https://github.com/kubernetes/community/pull/1982

**Comment by mikedanese** [comment]
See https://github.com/kubernetes/community/pull/1982. I'm closing because I'm not sure if adding this to the SAR approver is a good approach and I'd rather design a solution first.
