### ISSUE TITLE
Guideline for Checking Volume attached/detached Status through Cloudprovider

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#50645]
In Kuberenetes volume attach/detach controller design, there is an in-memory cache of current actual state (which volume is attached to which instance). In order to make sure the cached state is in sync with the real world, there is a control loop to periodically check the volume attached/detached status through cloudprovider. However, there been some confusion about this checking and what results should return. This doc is intended to clarify the confusion. 

In each volume attacher, function VolumesAreAttached is used to check whether a list of volumes are still attached to the node specified in the function. This function internally calls the cloud provider’s DisksAreAttached() function to get the results including a map of volume name to boolean value (attached-> true, detached-false), and an error. The logic is very simple,
```
If err != nil {
         // check failed due to some reason, do nothing 
} else {
	for volume, attached := range attachedResult {
		if !attached {
			//update volumesAttachedCheck result accordingly
		}
	}
}
```

For cloud provider’s DisksAreAttached function, there are different ways of checking volume status. But there is some confusion around the returned result for node (instance) failure cases. The following summarizes some of the implementations of different cloud providers.

- Check volume status through node instance object. Example, GCE PD, AWS EBS, Azure, 
In this type of cloud provider, it first get the instance object through cloud provider API call, and then check whether the volume is still attached on that node. 
** If the node instance is no longer exist (return cloudprovider.InstanceNotFound error), we can safely assume that volume is no longer attached to the node. So the function return disk is not attached without error
(Note: AWS also checks that if the instance status is “terminated”, assume volume is detached already)

- Check volume status by getting the volume object directly. Example, openstack_volume (Cinder), rackspace
In this type of cloud provider, it directly get the disk object, and check whether the attachedServer field to see whether the volume is still attached to the given node. It does not check the node exist or not.

- Check node instance object, but returns error if node object is not found. Example, Photon, Vsphere
If node no longer exist, returns an error. In this case, the volume is still considered as attached in local cache.

The key for the checking here is to understand the underlying node and disk behavior especially when node object is no longer exist, what result should return.

**Comment by jingxu97** [comment]
cc @kubernetes/sig-storage-misc

**Comment by BaluDontu** [comment]
A small correction on vsphere side. If node no longer exists (NotFound in the VC inventory) we will return the disks are not attached to the node without any error. On any other error case for example network connectivity etc. where its not able to get the node instance object, we would just return an error. In this case, the volume is still considered as attached in local cache.

There is a PR which addresses this - https://github.com/kubernetes/kubernetes/pull/50281

**Comment by FengyunPan** [comment]
@jingxu97 If you agree my method(https://github.com/kubernetes/kubernetes/pull/50239), I will do it for RackSpace.

**Comment by jingxu97** [comment]
@BaluDontu my description is based on current implementation. After you make the change, I will change that too. btw I thought node not exist in vsphere means power off and volume is still attached? Or node not exist means that node is deleted and volume is already detached automatically?

**Comment by jingxu97** [comment]
@FengyunPan I think there is still some misunderstanding. I added a comment there.

**Comment by BaluDontu** [comment]
@jingxu97 we used a wrong name for the isExists() in current vSphere code. In current vsphere code, we use isExists() to check whether the node is powered on or off. Essentially the function name should be isActive().

@FengyunPan latest PR addresses that. Is node is NotFound it assumes that disks are already detached and for any other errors for node retrieval it will throw error.

**Comment by jingxu97** [comment]
kind/bug
priority/critical-urgent

**Comment by dims** [comment]
@jingxu97 @BaluDontu @FengyunPan - This is marked urgent, are there PR(s) ready to merge?

**Comment by jingxu97** [comment]
@dims, I think all the PRs are merged for this issue.

**Comment by dims** [comment]
great thanks!

(assigning to myself to close the issue)

/assign
