### ISSUE TITLE
kubectl create return 0 when error

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#50644]
Run `kubectl create` with no other argument should return non-zero exit code.
 Steps to reproduce:
```
$ kubectl create
...
A lot of help text
...
$ echo $?
0
```

Similar issue before: https://github.com/kubernetes/kubernetes/issues/42852

/assign @shiywang 
Assign to you per https://github.com/kubernetes/kubernetes/pull/42999#issuecomment-286649323

**Comment by mengqiy** [comment]
cc: @apelisse

**Comment by apelisse** [comment]
I'm even more interested in knowing why the test didn't fail.

**Comment by shiywang** [comment]
working on it
