### ISSUE TITLE
Flake: not enough arguments in call to ds.getSecurityOpts

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#50659]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind flake
/priority failing-test
/area test-infra

**What happened**:
[pull-kubernetes-cross](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-cross/) job is failing

See
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46317/pull-kubernetes-cross/3696/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50302/pull-kubernetes-cross/3697/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50587/pull-kubernetes-cross/3698/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50616/pull-kubernetes-cross/3699/

**What you expected to happen**:
test should pass

**Comment by dixudx** [comment]
@kubernetes/sig-testing-test-failures

/assign @ixdy @fejta

**Comment by xiangpengzhao** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/50675 and will be fixed by #50694.

/cc @dims

**Comment by cblecker** [comment]
Duplicate of #50675
/close
