### ISSUE TITLE
Remove redundant util helpers.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#50653]
We have many util helpers which exist in two places. It's hard to maintain these helpers. It may also make developers confused by which one to use.

Most of the below helpers are almost the same in their two places. We should only keep one copy of them.

- [ ] [api/v1/endpoints](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/endpoints) **vs** [api/endpoints](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/endpoints)
- [ ] [api/v1/helper](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/helper) **vs** [api/helper](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/helper)
- [ ] [api/v1/pod](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/pod) **vs** [api/pod](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/pod)
- [ ] [api/v1/resource](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/resource) **vs** [api/resource](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/resource)
- [ ] [api/v1/service](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/service) **vs** [api/service](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/service)
- [ ] [api/v1/validation](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/v1/validation) **vs** [api/validation](https://github.com/kubernetes/kubernetes/tree/master/pkg/api/validation)

ref: https://github.com/kubernetes/kubernetes/pull/50218/files#r133046187
/cc @thockin 

/assign @caesarxuchao @xiangpengzhao

I prefer to remove the v1 ones. WDYT? @kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
> I prefer to remove the v1 ones. WDYT

Unfortunately, the apiserver deals with internal types, and controllers deal with external types. That means for many utilities, both a versioned and unversioned implementation are required.

**Comment by dixudx** [comment]
> Unfortunately, the apiserver deals with internal types, and controllers deal with external types. That means for many utilities, both a versioned and unversioned implementation are required.

Agreed. GVK will convert between versioned and unversioned schema.

**Comment by xiangpengzhao** [comment]
>Unfortunately, the apiserver deals with internal types, and controllers deal with external types. That means for many utilities, both a versioned and unversioned implementation are required.

@liggitt Thanks for clarity! I didn't notice the signature of the helpers. Yes they should be kept as-is...

**Comment by thockin** [comment]
ugg, we need to get past this.  It's a ticking bomb.
