### ISSUE TITLE
Scheduler ignores requests for unknown fully-qualified resources.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#50658]
/kind bug
/sig scheduling

**What happened**:

_Scenario A:_
* Create a pod that requires one `example.com/foo` resource.
* Observe that the pod is scheduled, despite there being no matching resources available in the cluster.

_Scenario B:_
* Create a pod that requires one `kubernetes.io/foo` resource.
* Observe that the pod is scheduled, despite there being no matching resources available in the cluster.

**What you expected to happen**:

I did not expect the pod to be scheduled and run. In both cases, I expected the pod to do one of the following:
* Remain in pending state, having failed a scheduler predicate for all available nodes.
* Fail validation. Since there is no facility in the scheduler or kubelet for checking feasibility of these resources, you could argue that they should have failed admission.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

There is a pull request in progress that attempts to fix this problem for all resources outside of the default namespace: [PR 48922: ](https://github.com/kubernetes/kubernetes/pull/48922). Another patch will be needed to handle fully-qualified resources in the `kubernetes.io` domain.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7, recent master
- Cloud provider or hardware configuration**: Local cluster
- OS (e.g. from /etc/os-release): Linux Mint 18.1, CentOS 7
- Kernel (e.g. `uname -a`): 4.4, 3.10
- Install tools: ./hack/local-up-cluster.sh

**Comment by xiangpengzhao** [comment]
@ConnorDoyle FYI:

I had an issue tracking this: https://github.com/kubernetes/kubernetes/issues/44331
There was also a PR waiting for your review: https://github.com/kubernetes/kubernetes/pull/44332

:)

**Comment by bgrant0607** [comment]
I would not expect the pod to fail validation until we have an API that specifies valid computational resources. There's no way to know whether a node will be provisioned that satisfies the request or whether a custom scheduler will recognize the resource or not.

Additionally, the general behavior for unknown fields is that they are silently ignored (and, ideally, dropped and not persisted, as we are doing for disabled alpha fields).

**Comment by bgrant0607** [comment]
I would expect such pods to remain pending.

**Comment by ConnorDoyle** [comment]
@bgrant0607 that makes sense to me and also mitigates the upgrade concerns raised in #50838 :+1:

**Comment by bgrant0607** [comment]
Related: https://github.com/kubernetes/community/pull/782

**Comment by ConnorDoyle** [comment]
/remove-lifecycle stale
"Scenario B" from the PR description is not fixed yet AFAIK.

**Comment by mindprince** [comment]
Do we have any resolution for Scenario B?
@bsalamat @vishh @davidopp @bgrant0607 Should I add scheduler predicates that keep such pods as pending till the resource shows up on the node?

**Comment by ConnorDoyle** [comment]
@mindprince could it be rolled into the existing PodFitsResources predicate?

A related, but possibly separate issue is that although the first class resources like “memory” are explained in the docs as implicitly in the kubernetes.io domain, asking for “kubernetes.io/memory” doesn’t work.

**Comment by mindprince** [comment]
Oh yeah, it would definitely be in `PodFitsResources` predicate.

**Comment by k82cn** [comment]
Just have a quick check: `Scenario A:` is handled by the recent master; for the `Scenario B:`, the resource begin with `kubernetes.io/` is ignored by `IsScalarResourceName()` -> `IsExtendedResourceName()` when getting pod request. @ConnorDoyle , any background for that?

**Comment by jiayingz** [comment]
@k82cn Extended resource is defined as resources not in the default kubernetes.io domain.

I think the question @mindprince was asking is if we implement the change on PodFitsResources to cover Scenario B, i.e., if a pod requests a non-existing resource in the kubernetes.io domain we will keep it pending, do people see any problems on this change? Also, if we implement this change, do we need to do anything extra to roll it out other than adding a release note?

**Comment by bsalamat** [comment]
I also think that we should add the check for kubernetes.io resources to the scheduler's PodFitsResources predicate. We should probably make cpu and memory aliases for kubernetes.io/cpu and kubernetes.io/memory as well.
AFAIK, this change should not cause any backward compatibility.

**Comment by mindprince** [comment]
Cool. I will send a PR to do that.

**Comment by ConnorDoyle** [comment]
My main concern with that is vetting all the code that inspects container resource requests and limits, both in core and in the larger ecosystem.

I think it would help to enforce a canonical representation and always store that. Since to date it hasn’t been possible to use fully-qualified first class resources maybe it’s best to say, the domain is always implicit for kubernetes.io? On the other hand we have things like “alpha.kubernetes.io/nvidia-gpu” (although that one is going away in 1.11)

**Comment by jiayingz** [comment]
cc @liggitt

**Comment by mindprince** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/61860 which will make sure that `*kubernetes.io/` resrouces will remain unscheduled if not exposed on any nodes.

> We should probably make cpu and memory aliases for kubernetes.io/cpu and kubernetes.io/memory as well.

My PR doesn't cover that. We can do that later if we really want to.

**Comment by k82cn** [comment]
@jiayingz , I mean why we skip `*kuberentes.io/` :), my understanding is that we expect those resource are handled before, e.g. by `cpu()`.

In such case, prefer to valid resource for `*kubernetes.io/` as we know the resource name list that we supported: if not in the supported list, reject it, as those resource name are reserved by core.

And I agree with Bobby to give alias for default/system resource, e.g. cpu, memory.

**Comment by mindprince** [comment]
> if not in the supported list, reject it, as those resource name are reserved by core.

While it is true that they are reserved by core and should not be used, we have historically not enforced that. Adding that validation now may break certain users.

See https://github.com/kubernetes/kubernetes/pull/50838#discussion_r133773654 and Brian's comment above.

**Comment by k82cn** [comment]
I think [Brian's comments](https://github.com/kubernetes/kubernetes/issues/50658#issuecomment-326174398) is for customized/extended resources; for reserved label/resources, we already know which resource we supported (except that's also not true) :)

/cc @bgrant0607
