### ISSUE TITLE
panic in e2e test 

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kubernetes#50660]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
e2e test panic in test
**What you expected to happen**:
no panic 
**How to reproduce it (as minimally and precisely as possible)**:

start " [Feature:ManualPerformance] should be able to handle 3 pods per node" e2e test 
on a 3-node cluster
**Anything else we need to know?**:
panic info :
![2017-08-15 11 18 07](https://user-images.githubusercontent.com/2142864/29303051-287b4ca2-81bc-11e7-9379-540259086595.png)

After some digging find why. Because the cluster size is 3 that d is 0 in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scalability/load.go#L520
sleepUpTo func which causes rand.Int63n panic
happy to fix this.
**Environment**:
- Kubernetes version (use `kubectl version`):1.7.3 
- Cloud provider or hardware configuration**:  bare-metal
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 16.04 
- Install tools: kubeadm
- Others:

**Comment by WIZARD-CXY** [comment]
just add a sanity check is fine I think

**Comment by FengyunPan** [comment]
It seems that the count of pods is 0.

**Comment by FengyunPan** [comment]
we should add codes to check 0 in rand.Int63n().

**Comment by WIZARD-CXY** [comment]
pod count is not 0, is 9(3*3)

**Comment by WIZARD-CXY** [comment]
@FengyunPan 
```
creatingTime := time.Duration(totalPods/throughput) * time.Second
createAllResources(configs, creatingTime)
``` 
If totalPods less than throughput, in our case, totalPods is 9, throughput is 10, the creatingTime will be 0, which makes rand.Int63n panic

**Comment by WIZARD-CXY** [comment]
or throughput is getting from env LOAD_TEST_THROUGHPUT, safe to add a sanity check

**Comment by FengyunPan** [comment]
>If totalPods less than throughput, in our case, totalPods is 9, throughput is 10, the creatingTime will be 0, which makes rand.Int63n panic
agree.
