### ISSUE TITLE
PersistentVolumeLabel admission controller is undocumented

### ISSUE THREAD

**Issue by cjyar** [kubernetes/kubernetes#50699]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: https://kubernetes.io/docs/admin/admission-controllershttps://kubernetes.io/docs/admin/admission-controllers lists PersistentVolumeLabel as a recommended admission controller, but it doesn't describe what it does.

**What you expected to happen**: At least the recommended admission controllers should be documented.

**How to reproduce it (as minimally and precisely as possible)**: See https://kubernetes.io/docs/admin/admission-controllers/.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@cjyar note it is moving to another location https://github.com/kubernetes/kubernetes/pull/44680 as part of this effort https://github.com/kubernetes/kubernetes/issues/48690

**Comment by tengqm** [comment]
Though not sure how far we are getting the plug-in migrated, I'm proposing a PR to the docs along with other plugins which were not documented:
https://github.com/kubernetes/kubernetes.github.io/pull/4751

**Comment by jhorwit2** [comment]
@cjyar This seems resolved now. Can we close this issue or is there still something you'd like to see? https://kubernetes.io/docs/admin/admission-controllers/#persistentvolumelabel
