### ISSUE TITLE
kubelet regression: non-existent root directory causes error instead of autocreation

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes#50709]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
When running `kubelet` on a new VM, I get the following error:

    error: failed to run Kubelet: rootDirectory "/var/lib/kubelet" does not exist

**What you expected to happen**:
Previously, if this root directory did not exist, kubelet would automatically create it with the appropriate permissions.

**How to reproduce it (as minimally and precisely as possible)**:

    $ git clone https://github.com/kubernetes/kubernetes.git
    $ cd kubernetes
    $ git checkout 039f898c07a643d6ef244fcb65daff5a53de41c8
    $ ./build/run.sh make WHAT=cmd/kubelet
    $ sudo ./_output/dockerized/bin/linux/amd64/kubelet --fail-swap-on=false

This invocation exits immediately with the above error about `/var/lib/kubelet` not existing.

**Anything else we need to know?**:
I believe this recently-merged PR is the cause: https://github.com/kubernetes/kubernetes/pull/48487

If I revert this PR's commit locally, and repeat the above steps, then `/var/lib/kubelet` gets automatically created when I start up kubelet:

    $ git revert 6c7245d464250278882b59d68a97b0170201d35d
    $ ./build/run.sh make WHAT=cmd/kubelet
    $ sudo ./_output/dockerized/bin/linux/amd64/kubelet --fail-swap-on=false

This invocation stays running, and if I check in another window, `/var/lib/kubelet` has automatically been created.

This discrepancy is currently breaking our [kubeadm e2e tests](https://github.com/kubernetes/kubeadm/issues/392). If the correct answer is that autocreation of the root directory was never supposed to be a supported feature and just happened to work, then we can update that expectation elsewhere to explicitly create the root directory first, but this does seem like a regression.

**Environment**:
- Kubernetes version (use `kubectl version`): upstream/master HEAD (at 039f898c07a643d6ef244fcb65daff5a53de41c8)
- Cloud provider or hardware configuration**: The same happens on my local desktop and a GCE VM with Ubuntu
- OS (e.g. from /etc/os-release): Ubuntu 14.04 on my desktop, 16.04 on GCE
- Kernel (e.g. `uname -a`): 4.4.0-83-generic on my desktop, 4.4.0-21-generic on GCE
- Install tools: building/running directly from the source code using the above steps
- Others:

@kubernetes/sig-node-bugs

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by jingxu97** [comment]
I am sure about the sequence of this? When cadvisor checks the directory, should this directory already exist?

**Comment by dims** [comment]
@jingxu97 figured out where exactly we create the directories. please see the PR

**Comment by dixudx** [comment]
For default `/var/lib/kubelet`, we may create it if needed. But what if a customized value?

**Comment by dixudx** [comment]
@pipejakob Thanks for the clarification.

Actually [`cadvisor.New`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L100-L128) is called before [`setupDataDirs`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L380). So @dims we may remove the duplicated `os.MkdirAll(kl.getRootDir(), 0750)` in `setupDataDirs`. WDYT?

**Comment by dims** [comment]
@dixudx i am not comfortable with the duplicate from setupDataDirs as someone can use Kubelet directly without using the code under cmd/kubelet/app/server.go (and without using cadvisor). So we should let it be

**Comment by dixudx** [comment]
@dims SGTM. Thanks.
