### ISSUE TITLE
 Could not open library 'libsystemd.so.0': libgcrypt.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rainard** [kubernetes/kubernetes#50725]
### Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

### What happened:

when I run kubectl  create -f fluentd-es-ds.yaml ,my pods  CrashLoopBackOff  .and I checked to get follow ,how can I fix it?

## [root@10 efk]#  kubectl    logs --namespace=kube-system   fluentd-es-7mpfd
```bash
/var/lib/gems/2.1.0/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsystemd.so.0': libgcrypt.so.11: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libsystemd.so': libsystemd.so: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so.0': libdw.so.1: cannot open shared object file: No such file or directory.
Could not open library 'libsystemd-id128.so': libsystemd-id128.so: cannot open shared object file: No such file or directory
        
```
## [root@10 efk]# find / -name "libsystemd.so.0"
```bash
/var/lib/docker/overlay/00c21f393f755c1f5f2475f1e7fa4743d0672c2ce3495f3024070e3960504381/root/lib/x86_64-linux-gnu/libsystemd.so.0
/var/lib/docker/overlay/e6224785984dc6c002bd2c85fedd0fcfc5478e5f8af935b97da95d11f29b9c7a/root/lib/x86_64-linux-gnu/libsystemd.so.0
.............
/usr/lib64/libsystemd.so.0
```
### How to reproduce it (as minimally and precisely as possible):
```bash
 kubectl  create -f fluentd-es-ds.yaml 

```

### Environment:
Kubernetes v1.7.3
yaml files from  : https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**Comment by rainard** [comment]
I modify  fluentd-es-ds.yaml  image:gcr.io/google-containers/fluentd-elasticsearch:v2.0.0  to  image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1 , it work

**Comment by crassirostris** [comment]
> I modify fluentd-es-ds.yaml image:gcr.io/google-containers/fluentd-elasticsearch:v2.0.0 to image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1 , it work

Cool! :)
