### ISSUE TITLE
Remove CreatedByAnnotation in v1.9, in favor of ControllerRef

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#50720]
`CreatedByAnnotation` will be [deprecated](https://github.com/kubernetes/kubernetes/issues/44407) in v1.8 and be removed in v1.9, in favor of `ControllerRef`.

**Comment by enisoc** [comment]
ref #50536

**Comment by crimsonfaith91** [comment]
@enisoc Thanks for the quick fix! I didn't have the right to add label...
