### ISSUE TITLE
Get network id for openstack cloud provider automatically

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#50726]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
If user don't specify subnet-id in openstack cloud provider config file, service controller can't create LoadBalancer service. 
If user specify wrong subnet-id in openstack cloud provider config file, service controller will create a unsafe LoadBalancer service.
And subnet-id is unique for kubernetes cluster, we can get it from Neutron.
The same to "floating-network-id" and "node-security-group".

**What you expected to happen**:
We can get "subnet-id" "floating-network-id" and "node-security-group" automatically, like "lb-version", "bs-version". **Automatic is more safe and more convenience.**

**Anything else we need to know?**:
1. get subnet-id by server attachInterfaces
2. get "floating-network-id" by 'neutron  net-list --router:external=True'(we should support it in gophercloud)
3. get "node-security-group" by server SecurityGroups

@dims @anguslees

**Comment by anguslees** [comment]
I just want to say, this is my favourite bug report / suggestion for 2017.  :+1:

**Comment by FengyunPan** [comment]
Thank you.

**Comment by FengyunPan** [comment]
After reading the codes of (https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L606), I find another issuse.
if user enables  manage-security-groups, openstack cloud provider will recreate security group for service. We should check whether security group exist before creating it.
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L879
