### ISSUE TITLE
Enable federation apiserver connect to external etcd

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#50737]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
If I want to enable the federation control panel, then I need to use `kubefed init` to install etcd and control panel. For etcd, as the kubernetes already have etcd running, so I want to re-use the existing etcd in my kubernetes cluster and do not want to install a new etcd for federation only.

**What you expected to happen**:
I can specify external etcd when using `kubefed init`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig federation

/cc @kubernetes/sig-federation-feature-requests

**Comment by lukaszo** [comment]
As the workaround, after init, you can edit deployment `federation-apiserver` change `- --etcd-servers` line  and delete etcd container.

Other projects, like kubeadm, are using `--config` option to pass the whole configuration. @madhusudancs  are there any plans to move to config based configuration?

Another option is to add `--etcd-servers` to `kubefed join` but such option was removed from kubeadm and only --config is accepted.

**Comment by gyliu513** [comment]
How about enabling connect to external etcd when `kubefed init`? @lukaszo

**Comment by quinton-hoole** [comment]
#50815

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#30.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
