### ISSUE TITLE
Update e2e_federation with specific sig prefix

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/kubernetes#50735]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Ref to https://github.com/kubernetes/kubernetes/issues/49161, e2e_federation still test use `k8s.io` prefix. Not sure if we could use `sig-federation` instead of `k8s.io`  just as https://github.com/kubernetes/kubernetes/issues/49161 described.

 i would be happy to send a PR to update it if we indeed need.

/cc @quinton-hoole @csbell

**Comment by quinton-hoole** [comment]
@guangxuli Yes, it would be great if you could send a PR.  Please use sig-multicluster, our new sig name.

**Comment by guangxuli** [comment]
@quinton-hoole ok, i will do that.

**Comment by guangxuli** [comment]
@quinton-hoole I had send a PR to fix this issue, In this PR i just move the ubernetes_lite.go to the new created directory named multicluster, I created it under e2e directory. I found that there is a another specific directory named **e2e_federation**. A little confusing,  there are three cases:
- move ubernetes_lite.go to e2e, just like PR #51898 
- move ubernetes_lite.go to e2e_federation 
- move all e2e_federation to e2e

I am not sure which case is fit to sig-multicluster, what do you think? ;)

**Comment by guangxuli** [comment]
@nikhiljindal Could you see this issue and the relevant PR. Thanks.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#29.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
