### ISSUE TITLE
Kubefed init should not fail if resource are already existed

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#50746]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When I run `kubefed init` to deploy federation control plane in host cluster, some error happened. After I fixed the error and run `kubefed init` again, it throws error like "Service account already exist" or "federation-system namespace already exist".

**What you expected to happen**:
`kubefed init` should continue if related resource is already existed in host cluster. Or we expect a `--force` flag to force overwrite previous setting of federation.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create federation-system namespace in host cluster.
2. Run `kubefed init`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#31.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
