### ISSUE TITLE
kubelet 1.7.3 not reading config file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

### ISSUE THREAD

**Issue by ybbaigo** [kubernetes/kubernetes#50748]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind bug

**What happened**:  failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

**What you expected to happen**: starting kubelet

**How to reproduce it (as minimally and precisely as possible)**:

* yum install -y docker-1.12.6
* systemctl enable docker && systemctl start docker
* setenforce 0
* yum install -y kubelet kubeadm
* systemctl enable kubelet && systemctl start kubelet
* systemctl daemon-reload
* systemctl restart kubelet
* kubelet log

**Anything else we need to know?**:

Configuration for `cgroup drive` is right in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

> Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"

I also checked the `Environment` with cli

> $ systemctl show --property=Environment kubelet | cat
> Environment=KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf\x20--require-kubeconfig=true KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests\x20--allow-privileged=true KUBELET_NETWORK_ARGS=--network-plugin=cni\x20--cni-conf-dir=/etc/cni/net.d\x20--cni-bin-dir=/opt/cni/bin KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10\x20--cluster-domain=cluster.local KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook\x20--client-ca-file=/etc/kubernetes/pki/ca.crt KUBELET_CADVISOR_ARGS=--cadvisor-port=0 **KUBELET_CGROUP_ARGS=--cgroup-driver=systemd**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**:   4 core 16G RAM 
- OS (e.g. from /etc/os-release):  CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux 10-8-108-92 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by dixudx** [comment]
@ybbaigo Please help check all the `drop-ins` of `kubelet.service` to see whether `KUBELET_CGROUP_ARGS` has been override. Also check cgroup driver settings in Docker.

**Comment by iamzhout** [comment]
Does [this way by dsever](https://github.com/kubernetes/kubernetes/issues/43805#issuecomment-290403262) helps to resolve your problem?

**Comment by dixudx** [comment]
@ybbaigo run `systemctl status docker`, you will find something like this,

```
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─40-flannel.conf, 50-docker-options.conf
   Active: active (running) since Wed 2017-08-16 06:02:31 GMT+6; 10min ago
```

Found all your override settings in listed Drop-in.

**Comment by iamzhout** [comment]
@ybbaigo Have you tried `kubeadm init` to setup the cluster? I didn't see related steps in your description. Or if you can reproduce it exactly on another CentOS vm with the same steps you described?

**Comment by paddy235** [comment]
me too, not found /etc/systemd/system/kubelet.service.d

**Comment by paddy235** [comment]
```
[root@k8sMaster kubeadm]# ll /etc/systemd/system/kube*
-rwxr-xr-x 1 root root 221 8月   4 04:49 /etc/systemd/system/kubelet.service
[root@k8sMaster kubeadm]# cat /etc/systemd/system/kubelet.service
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
ExecStart=/usr/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
[root@k8sMaster kubeadm]# 

```

**Comment by paddy235** [comment]
use version 1.7.3-1

**Comment by jwcesign** [comment]
I got the same problem.... /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki --v=2 --log-dir=/var/log/kubelet.......... I add log dir, but I  haven't got log output,
