### ISSUE TITLE
Supports monitoring metrics for network/instance operations in openstack cloud provider

### ISSUE THREAD

**Issue by huzhengchuan** [kubernetes/kubernetes#50751]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
now I use openstack as a cloud provide to run kubernetes, through the monitoring metrics have optimized the stability of the kubernetes cluster and scalability. the volume operation metrics help mea lot, let me know the time to call openstack interface, why not add loadbalance and node operation metrics in openstack cloud provider, I think it is very meaningful.

**What you expected to happen**: Add loadbalance and node operation metrics in openstack cloud provider, likes the volume operation metrics.

**How to reproduce it (as minimally and precisely as possible)**:
Use the openstack cloud provider run kubernetes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@dims @anguslees

**Comment by xsgordon** [comment]
Do you have a milestone in mind for this work @huzhengchuan?

**Comment by huzhengchuan** [comment]
the rest request in openstack is asynchronous, It is better like 
https://github.com/kubernetes/kubernetes/pull/44510
I am not sure that the issue is valuable now, so put the issue to talk.  @xsgordon

**Comment by huzhengchuan** [comment]
close it, If some one thinks its needed, other open it.
