### ISSUE TITLE
RBAC: Application owners should be allowed to create PodDisruptionBudgets

### ISSUE THREAD

**Issue by seh** [kubernetes/kubernetes#50767]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
For a fresh cluster using the RBAC authorization plugin, with its "bootstrap" _ClusterRoles_ loaded, neither a user granted the ["admin"](https://github.com/kubernetes/kubernetes/blob/0cb8bae6ac6cc1d331052194e3e290d001e45dab/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml#L3-L163) nor the ["edit"](https://github.com/kubernetes/kubernetes/blob/0cb8bae6ac6cc1d331052194e3e290d001e45dab/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml#L184-L324) _ClusterRole_ via a _RoleBinding_ can create a _PodDisruptionBudget_ object within the namespace where that user can otherwise create the "applications" meant to be protected by a _PodDisruptionBudget_.

**What you expected to happen**:
[The documentation for _PodDisruptionBudget_](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work) reads as follows:
> An Application Owner can create a `PodDisruptionBudget` object (PDB) for each application. A PDB limits the number pods of a replicated application that are down simultaneously from voluntary disruptions.

The "application owner" role in that document is distinct from the "cluster manager" and "hosting provider" role. The 'application owner" is the one who creates the _Deployment_ or any other pod-managing object, not the cluster administrator presumed to have the permissions in the "cluster-admin" _ClusterRole_.

I expect that users who can create _Deployments_ and kind should be able to create _PodDisruptionBudgets_ as well. Hence, one solution is to allow the bootstrap "admin" and "edit" roles to create, mutate, and delete _PodDisruptionBudgets_.

**How to reproduce it (as minimally and precisely as possible)**:
Grant a user the "edit" _ClusterRole_ within a namespace via a _RoleBinding_. Authenticate as that user, and attempt to create a _PodDisruptionBudget_. Observe that the API Server rejects the request as forbidden.

**Anything else we need to know?**:
I [asked in the "sig-auth" channel of the "Kubernetes" Slack team](https://kubernetes.slack.com/archives/C0EN96KUY/p1502826416000083) whether this lack of permission is intentional, or whether it's a mistaken omission, but I didn't receive a reply.

This omission is similar in nature to #40881.

@kubernetes/sig-auth-bugs

**Environment**:
- Kubernetes version:  
  > Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T15:13:53Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
  > 
  > Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.6-21+464b547b816b32", GitCommit:"464b547b816b32a76944088268b69232ef3571c7", GitTreeState:"clean", BuildDate:"2017-07-28T20:20:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  
  (None pertinent)

- OS (e.g. from /etc/os-release):  
  Client: macOS Sierra 10.12.6
  Server: Ubuntu 16.04.1 LTS

- Kernel (e.g. `uname -a`):  
  4.4.0-78-generic

**Comment by ericchiang** [comment]
I don't think "application owner" in the document is referring to a specific RBAC role, so I don't know if this is strictly a bug.

Naively, this seems more in line with an "admin" than the "edit" role since lets users set custom scheduling policies that might conflict with other namespaces or actively impact an admins action, like draining a node.

**Comment by seh** [comment]
I agree that it's not so much a defect as an omission, even if only an omission of guidance. I didn't mean to imply that that document was describing specific parts of RBAC; rather this is me trying to _implement_ that document's imagined world via RBAC.

In my multi-tenant clusters, the tenants in each namespace have the "edit" _ClusterRole_ bound, and that's how they manage their _Deployments_ and such. I don't want to allow them the "admin" _ClusterRole_, because then they can grant other parties "admin" as well, if I understand those rules correctly.

The documentation for _PodDisruptionBudget_ doesn't make it clear whether or not it is namespace-scoped, but given that it selects pods, it seems strange to allow selecting on labels of pods that you don't own, and wouldn't even be able to see. Hence, I conclude that its scope is intended to be at the namespace level.

The intention here is to slow down the draining of a node to protect an application's SLO. An administrator can still force the drain—overriding this budget—if need be.

**Comment by ericchiang** [comment]
> In my multi-tenant clusters, the tenants in each namespace have the "edit" ClusterRole bound, and that's how they manage their Deployments and such. I don't want to allow them the "admin" ClusterRole, because then they can grant other parties "admin" as well, if I understand those rules correctly.

You can already add this power to your cluster's "edit" ClusterRole. The default ones are for _every_ kubernetes cluster, so it's probably best to be conservative when changing them.

Currently the only description for "admin" is:

> a role for a namespace level admin.  It is `edit` plus the power to grant permissions to other users.

The description for "edit" is:

> a role for a namespace level editor.  It grants access to all user level actions in a namespace.
It does not grant powers for "privileged" resources which are domain of the system: `/status`
subresources or `quota`/`limits` which are used to control namespaces

Probably best to determine if we feel that `PodDisruptionBudget` can impact things outside of its own namespace (again, I'm not very experienced with that resource). If it can, we should continue to leave it up to cluster operators to control the policy.

**Comment by seh** [comment]
> You can already add this power to your cluster's "edit" ClusterRole. The default ones are for every kubernetes cluster, so it's probably best to be conservative when changing them.

Yes, I understand and appreciate that freedom, but I figure that others will run into this omission and puzzle over it just as we have in my organization, so I'm trying to help everyone. It would take less effort to patch it locally than fixing it upstream. Doing so feels selfish, however expedient. I'm willing to create a PR, but I don't want to do so until we agree that it's a good idea.

> Probably best to determine if we feel that PodDisruptionBudget can impact things outside of its own namespace

Here's [a code pointer into `(*disruption.DisruptionController).getPodsForPdb`](https://github.com/kubernetes/kubernetes/blob/3e8a25e81804051ab47882843795254e268ae7e7/pkg/controller/disruption/disruption.go#L423-L438), where we see it listing the pods within the same namespace as the _PodDisruptionBudget_ that match the budget's selector.

**Comment by davidopp** [comment]
This is a tricky one.

My feeling is that you should be able to create a PDB if you can create a Deployment/ReplicaSet/whatever. Because really it's the app deployer who knows the data integrity semantics of their application. However, we probably need some kind of quota on PDB (which would only be configurable by a cluster admin) to prevent people from abusing PDB.

The PDB documentation [implies](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#separating-cluster-owner-and-application-owner-roles) that cluster admin should be the one who sets up PDBs but I don't agree with this (see previous paragraph).

I'm pretty sure PDB is namespaced.

@kubernetes/sig-apps-misc 

Also ref/ #35318

**Comment by seh** [comment]
I read that same paragraph several times this morning, @davidopp, before submitting this issue, and concluded that the separation of responsibilities it's trying to describe is as follows:
- Administrators impose _voluntary disruptions_ upon the cluster.
- Application owners express constraints on and tolerance for such disruptions.

It's the _PodDisruptionBudget_ by which the latter mediates the former, without the two parties needing to negotiate explicitly.

**Comment by davidopp** [comment]
@seh I think you're right. The paragraph could be written more clearly, but that interpretation makes more sense.

**Comment by liggitt** [comment]
What cluster administrator actions would a PDB block (e.g. would it prevent a node drain from succeeding)? For the operations it would block, is there an ability for a cluster admin to override PDB if needed?

**Comment by seh** [comment]
It can block a node drain from proceeding, yes, per the documentation on [how PDBs work](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work) and [the example](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pdb-example).
> When a cluster administrator wants to drain a node they use the _kubectl drain_ command. That tool tries to evict all the pods on the machine. The eviction request may be temporarily rejected, and the tool periodically retries all failed requests until all pods are terminated, or until a configurable timeout is reached.

[The eviction API returns HTTP status code 429](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api) to tell a client to try again soon to see whether the budget-induced contention has abated.

Though [_kubectl drain_ has a "force" flag](https://kubernetes.io/docs/user-guide/kubectl/v1.7/#drain), it doesn't circumvent respecting applicable _PodDisruptionBudgets_. As I understand it, _kubectl drain_ is intentionally graceful, and if you want to forgo that grace, you can delete pods manually, which sidesteps the Eviction API and _PodDisruptionBudgets_ entirely.

**Comment by davidopp** [comment]
> For the operations it would block, is there an ability for a cluster admin to override PDB if needed?

In practice I think yes. No admin is going to let a node run a one-year-old version of k8s after the rest of the cluster has been upgraded, just because it would violate a PDB. Of course k8s should not enforce a specific policy, I'm just saying that systems built on top will probably force-delete at some point. This is what GKE does (see paragraph beginning "Container Engine imposes" [here](https://cloud.google.com/container-engine/docs/clusters/upgrade)).

**Comment by davidopp** [comment]
> For the operations it would block, is there an ability for a cluster admin to override PDB if needed?

Sorry, I just realized you were asking a technical question, not a philosophical one. :-) My answer to the philosophical question stands, but the answer to the technical question is that yes, a client can bypass PDB by just doing a regular DELETE rather than using the evict subresource.

**Comment by seh** [comment]
Given @davidopp's take, @liggitt, shall I proceed with a patch? My intended approach is to allow both the existing "admin" and "edit" _ClusterRoles_ the following verbs against _PodDisruptionBudgets_:
- create
- delete
- deletecollection
- get
- list
- patch
- update
- watch

**Comment by dhawal55** [comment]
Just to add to this, is there any reason "admin" role is not allowed to view status on following resources:

- horizontalpodautoscalers/status
- persistentvolumeclaims/status
- services/status
- statefulsets/status
- scheduledjobs/status
- jobs/status
- cronjobs/status
- daemonsets/status
- deployments/status
- horizontalpodautoscalers/status
- ingresses/status
- jobs/status
- replicasets/status
- poddisruptionbudgets/status

Also missing are permissions for:
- networkpolicies
- replicationcontrollers

**Comment by seh** [comment]
One the subject of _NetworkPolicy_, see [this recent discussion in the "sig-auth" channel of the "Kubernetes" Slack team](https://kubernetes.slack.com/archives/C0EN96KUY/p1504021636000705).

**Comment by liggitt** [comment]
> is there any reason "admin" role is not allowed to view status on following resources?:

`get` access to status subresources is not a useful permission if you already have the ability to get the resource, since that returns the same thing as simply getting the resource.

**Comment by dhawal55** [comment]
@liggitt Thank you. We had used the status subresource permissions in earlier versions of k8s and thought it was required. I will try without it and let you know.

**Comment by dhawal55** [comment]
ok, I tested and confirm that I don't need access to `/status` subresources.

Any update on the `poddisruptionbudgets` permission? Are we adding it to built-in roles? If so, I will update the built-in roles on my cluster for now.

**Comment by seh** [comment]
I have not yet posted a patch that would do so. My intention with filing this issue first was to judge the likelihood of such a patch being accepted. @liggitt, can you share your opinion on the goal? Obviously it's possible to implement it poorly, but we can work through that in code review.

**Comment by liggitt** [comment]
@seh sorry for the delay... talked through this with some of the sig node folks as well. Adding write permissions to the `admin` and `edit` roles and read permissions to the `view` role makes sense to me.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/52654 with updates
