### ISSUE TITLE
Don't run CI on PRs that don't need them

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#5078]
Travis runs our PRs serially which is part of the reason it takes so long to run them during the day. There are many PRs that don't need to run the full suite of integration changes. We should quit early when those occur. In the Travis hooks we'll need to detect the no-op change and short-circuit the rest of the execution.

We need to figure out the cases where the tests don't need to be run. One very possible candidate is `docs/`

**Comment by alex-mohr** [comment]
... or we buy more Travis capacity.  I think @craigmcl is driving that.
