### ISSUE TITLE
kube-dns failed to list *v1.Endpoints: User "system:serviceaccount:kube-system:default" cannot list services

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#50799]
/kind bug
/sig auth

**What happened**:
I've set up k8s with RBAC and it seems kube-dns is trying to list the endpoint and services at cluster scope under namespace default.

Accordingly with https://kubernetes.io/docs/admin/authorization/rbac/ it seems there should only be 
a kube-dns account in the kube-system namespace. However there are some missing or mis-configured kube-dns options because I'm getting these error messages in kube-dns:
```
E0816 15:32:32.456507       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: User "system:serviceaccount:kube-system:default" cannot list endpoints at the cluster scope. (get endpoints)
E0816 15:32:32.456507       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: User "system:serviceaccount:kube-system:default" cannot list services at the cluster scope. (get services)
```

I'm not entirely sure if I should have open this here or under github.com/kubernetes/dns

I'm using the controller and service available here https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns

**Comment by liggitt** [comment]
cc @bowei @MrHohn

**Comment by bowei** [comment]
Version of software?

**Comment by MrHohn** [comment]
@aanm kube-dns should use `system:serviceaccount:kube-system:kube-dns` instead of `system:serviceaccount:kube-system:default`.

Did you set `serviceAccount` on the kube-dns deployment:
https://github.com/kubernetes/kubernetes/blob/85025ef7dc693c116efc5fbf199a4f7119c69186/cluster/addons/dns/kubedns-controller.yaml.base#L171

and create `kube-dns` service account using https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kubedns-sa.yaml?

**Comment by aanm** [comment]
@MrHohn I missed that last line when I copied the `kubedns-controller.yaml.base`

It's working fine now. Thanks for the help!

**Comment by bamb00** [comment]
@MrHohn I deploy the example-app (prometheus-frontend) to monitor my app in the namespace monitoring

Can you tell me what I am doing wrong? 

       #  **kubectl get po -n monitoring**
       **prometheus-frontend-0**                  2/2       Running   0          5m


prometheus-frontend logs:

       level=error ts=2018-03-15T05:01:22.217971764Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:177: Failed to list *v1.Endpoints: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list endpoints at the cluster scope. (get endpoints)"
       level=error ts=2018-03-15T05:01:22.220082098Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:178: Failed to list *v1.Service: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list services at the cluster scope. (get services)"
       level=error ts=2018-03-15T05:01:22.22024442Z caller=main.go:212 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:179: Failed to list *v1.Pod: User \"system:serviceaccount:monitoring:prometheus-frontend\" cannot list pods at the cluster scope. (get pods)"

**Comment by MrHohn** [comment]
@bamb00 It is likely the RBAC for your app wasn't properly setup. Have you checked out [this doc page](https://kubernetes.io/docs/admin/authorization/rbac/)?

**Comment by thomastvedt** [comment]
Just as a reference for the future me;
In my case it helped to just delete the two dns pods. When Kubernetes re-created them, dns was working again.

The error occurred when removing an app from "namespaceA", and then reinstalling it in "namespaceB".
