### ISSUE TITLE
[upgrade test failure] Basic StatefulSet functionality [StatefulSetBasic] should have a working scale subresource

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#50795]
/cc @kubernetes/sig-apps-bugs 

This test is failing on several of the 1.7 to master upgrade tests

https://k8s-testgrid.appspot.com/master-upgrade#gke-cvm-1.7-cvm-master-upgrade-cluster-new
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-cvm-master-upgrade-cluster-new

Example failure

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-new-cvm-master-upgrade-cluster-new/133#sig-apps-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-should-have-a-working-scale-subresource

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:881
Aug 16 08:04:23.109: Failed to get scale subresource: the server could not find the requested resource
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/statefulset.go:861
```

Maybe just an issue with the resource being enabled?

cc @kubernetes/release-maintainers @mbohlool

**Comment by crimsonfaith91** [comment]
@ericchiang It may be due to the test is based on `apps/v1beta1`.
I think this failure will be resolved when `apps/v1beta2` is enabled, and i change the e2e test to depend on `apps/v1beta2`.

**Comment by crimsonfaith91** [comment]
I have sent out a PR that changes API version of statefulset scale subresource e2e test to `v1beta2`: https://github.com/kubernetes/kubernetes/pull/50861

**Comment by crimsonfaith91** [comment]
@ericchiang Do the affected clusters have `apps/v1beta2` version enabled? I encountered the same error for a release-blocking GKE cluster, and the error is resolved by enabling the `apps/v1beta2` version.

**Comment by ericchiang** [comment]
@crimsonfaith91 I actually don't know. Will take a look.

**Comment by crimsonfaith91** [comment]
@ericchiang Thank you!

**Comment by crimsonfaith91** [comment]
@ericchiang I believe this has been fixed. Do you mind to verify it?

**Comment by ericchiang** [comment]
@crimsonfaith91 yep the current upgrade tests mark this as passing

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new

/close

Thanks!
