### ISSUE TITLE
vSphere Cloud Provider : Unable to format and mount vsphere volumes on nodes when a pod is created.

### ISSUE THREAD

**Issue by BaluDontu** [kubernetes/kubernetes#50802]
Is this a BUG REPORT or FEATURE REQUEST?:

Bug Report
/kind bug

What happened: I created a PVC using storageclass. The Pod which used the PVC fails to start. I see the disk was attached successfully to the node but the mount operation has failed.

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		1m		1	{default-scheduler }			Normal		Scheduled		Successfully assigned thindiskpod to node3
  1m		1m		1	{kubelet node3}				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-5h5x6" 
  1m		1m		5	{kubelet node3}				Warning		FailedMount		MountVolume.MountDevice failed for volume "pvc-4dc51e93-82c5-11e7-a497-0050569c48bf" : executable file not found in $PATH
```

What you expected to happen: The PV to mount, format and the Pod to start

How to reproduce it (as minimally and precisely as possible): Use the latest master builds for kubernetes deployments.

Anything else we need to know?: N/a

Environment: vSphere

I see the following errors on the kubelet where the node failed to format the disk and eventually mount was failed.

> {"log":"I0816 20:56:15.900236     659 operation_generator.go:417] MountVolume.WaitForAttach succeeded for volume \"pvc-4dc51e93-82c5-11e7-a497-0050569c48bf\" (UniqueName: \"kubernetes.io/vsphere-volume/[vsanDatastore] kubevols/kubernetes-dynamic-pvc-4dc51e93-82c5-11e7-a497-0050569c48bf.vmdk\") pod \"thindiskpod\" (UID: \"52fbf7a2-82c5-11e7-a497-0050569c48bf\") \n","stream":"stderr","time":"2017-08-16T20:56:15.901072134Z"}

> {"log":"I0816 20:56:15.902508     659 mount_linux.go:413] Checking for issues with fsck on disk: /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5\n","stream":"stderr","time":"2017-08-16T20:56:15.902695897Z"}

> {"log":"I0816 20:56:15.921616     659 mount_linux.go:427] `fsck` error fsck from util-linux 2.25.2\n","stream":"stderr","time":"2017-08-16T20:56:15.921725608Z"}

> {"log":"fsck: error 2 (No such file or directory) while executing fsck.ext2 for /dev/sdb\n","stream":"stderr","time":"2017-08-16T20:56:15.921752327Z"}

> {"log":"I0816 20:56:15.921652     659 mount_linux.go:432] Attempting to mount disk: ext4 /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5 /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] kubevols/kubernetes-dynamic-pvc-4dc51e93-82c5-11e7-a497-0050569c48bf.vmdk\n","stream":"stderr","time":"2017-08-16T20:56:15.921774238Z"}

> {"log":"I0816 20:56:15.921686     659 mount_linux.go:160] Mounting cmd (mount) with arguments ([-t ext4 -o defaults /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5 /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] kubevols/kubernetes-dynamic-pvc-4dc51e93-82c5-11e7-a497-0050569c48bf.vmdk])\n","stream":"stderr","time":"2017-08-16T20:56:15.921948786Z"}

> {"log":"E0816 20:56:15.929506     659 mount_linux.go:165] Mount failed: exit status 32\n","stream":"stderr","time":"2017-08-16T20:56:15.929619467Z"}

> {"log":"Mounting command: mount\n","stream":"stderr","time":"2017-08-16T20:56:15.92963496Z"}

> {"log":"Mounting arguments: -t ext4 -o defaults /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5 /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] kubevols/kubernetes-dynamic-pvc-4dc51e93-82c5-11e7-a497-0050569c48bf.vmdk\n","stream":"stderr","time":"2017-08-16T20:56:15.929639337Z"}

> {"log":"Output: mount: wrong fs type, bad option, bad superblock on /dev/sdb,\n","stream":"stderr","time":"2017-08-16T20:56:15.929642498Z"}

> {"log":"       missing codepage or helper program, or other error\n","stream":"stderr","time":"2017-08-16T20:56:15.929645312Z"}

> {"log":"\n","stream":"stderr","time":"2017-08-16T20:56:15.929647822Z"}

> {"log":"       In some cases useful info is found in syslog - try\n","stream":"stderr","time":"2017-08-16T20:56:15.929650562Z"}

> {"log":"       dmesg | tail or so.\n","stream":"stderr","time":"2017-08-16T20:56:15.929653095Z"}

> {"log":"\n","stream":"stderr","time":"2017-08-16T20:56:15.929655488Z"}

> {"log":"I0816 20:56:15.931335     659 mount_linux.go:480] Attempting to determine if disk \"/dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5\" is formatted using lsblk with args: ([-n -o FSTYPE /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5])\n","stream":"stderr","time":"2017-08-16T20:56:15.931446377Z"}

> {"log":"I0816 20:56:15.938198     659 mount_linux.go:483] Output: \"\\n\"\n","stream":"stderr","time":"2017-08-16T20:56:15.938284852Z"}

> {"log":"I0816 20:56:15.938236     659 mount_linux.go:452] Disk \"/dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5\" appears to be unformatted, attempting to format as type: \"ext4\" with options: [-F /dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5]\n","stream":"stderr","time":"2017-08-16T20:56:15.938393307Z"}

> {"log":"E0816 20:56:15.939026     659 mount_linux.go:460] format of disk \"/dev/disk/by-id/wwn-0x6000c29d3c96f77096950581483fe3a5\" failed: type:(\"ext4\") target:(\"/var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vsanDatastore] kubevols/kubernetes-dynamic-pvc-4dc51e93-82c5-11e7-a497-0050569c48bf.vmdk\") options:([\"defaults\"])error:(executable file not found in $PATH)\n","stream":"stderr","time":"2017-08-16T20:56:15.939126395Z"}

> {"log":"I0816 20:56:15.939915     659 server.go:214] Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"thindiskpod\", UID:\"52fbf7a2-82c5-11e7-a497-0050569c48bf\", APIVersion:\"v1\", ResourceVersion:\"5203\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedMount' MountVolume.MountDevice failed for volume \"pvc-4dc51e93-82c5-11e7-a497-0050569c48bf\" : executable file not found in $PATH\n","stream":"stderr","time":"2017-08-16T20:56:15.94001794Z"}

@tusharnt @divyenpatel @luomiao @rohitjogvmw

**Comment by BaluDontu** [comment]
I see a similar sort of issue on azure - https://github.com/kubernetes/kubernetes/issues/50150.

**Comment by BaluDontu** [comment]
It failed at line -
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L460 when it tried to execute the mkfs.ext4 command to format the file system. 

I tried to exec into the kubelet binary and I don't see the mkfs.ext4/mkfs.ext2 formatting tools available in kubelet binary.

```
root@node3 [ ~ ]# docker exec -it d2b63c97de99 /bin/bash
# mkfs.ext4
/bin/bash: 1: mkfs.ext4: not found
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

But i tried to verify it against the hyperkube image which i got from the https://storage.googleapis.com/kubernetes-release-dev/ci/latest-green.txt and deployed a kubernetes cluster using this image. I see this kubernetes cluster working perfectly fine and don't see any issues mentioned above when deploying a pod. Verified the kubelet binary to check if the mkfs.ext4 tools are available and I see they are available.

```
root@node3:/# which mkfs.ext4
/sbin/mkfs.ext4
root@node3:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

So the problem seems to be present on the kubelet binary in latest master builds.

**Comment by BaluDontu** [comment]
@jingxu97 @saad-ali

**Comment by saad-ali** [comment]
```
mkfs.ext4: not found
```

`mkfs` is an external dependency and apparently not present on your host. Make sure your image contains it and that it's accessible to kubelet. Moving forward @jsafrane is working on a making the mount operation for in-tree volume plugins containerized, so that dependencies like this can automatically be downloaded.

**Comment by divyenpatel** [comment]
On the Node VM (Docker Host), we have mkfs.ext4 available at /usr/sbin/.
We mounted /usr/sbin/ and /usr/lib/ from the docker host to the kubelet container and we are able to mount and format volume successfully.

```
 -v /usr/sbin/:/usr/sbin/:ro \
 -v /usr/lib/:/usr/lib/:rw \
```

This is only happening if we build kubernetes from the master branch.

if we we use following builds on the node VM created from the same docker host, without requiring to mount /usr/sbin/, we are able to find mkfs.ext4 in the hyperkube kubelet container image.

https://storage.googleapis.com/kubernetes-release-dev/ci/latest-green.txt and 
https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.7.txt and
https://storage.googleapis.com/kubernetes-release-dev/ci/latest-1.6.txt

@saad-ali  
So on the master branch,  mkfs command and library dependency is no longer embed in the image?

**Comment by jamiehannaford** [comment]
I'm also running into this issue but with Cinder mounts, which relies on `mkfs.ext4`. That binary no longer seems installed in v1.8 containers:

gcr.io/google-containers/hyperkube-amd64:v1.8.0-beta.0
gcr.io/google-containers/hyperkube-amd64:v1.8.1-beta.0

but it's available in v1.7.5. 

@saad-ali @jsafrane Is this intended, or is this a bug? Do you require people mounting `/usr/sbin` into the kubelet container?

**Comment by BaluDontu** [comment]
@jamiehannaford: We have solved this problem by mounting /usr/sbin into kubelet container when deploying kubernetes clusters with release 1.8.
With 1.7 and below we don't require the /usr/sbin/ mounting in kubelet and still the mount succeeds. So I am still unsure what specific changes in 1.8 release caused this behaviour.

**Comment by jamiehannaford** [comment]
@BaluDontu see https://github.com/kubernetes/kubernetes/pull/52798 for the fix. The base hyperkube image changed in v1.8, removing the necessary mount utils. Mounting this from the host is not recommended.
