### ISSUE TITLE
Pod stays pending after node dies

### ISSUE THREAD

**Issue by borgesgabriel** [kubernetes/kubernetes#50813]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Some pods stay `Pending` after the nodes in which they were previously running dies.

**What you expected to happen**:
Pods to be assigned to another node and transition to `Running`.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a replication controller with a replica of 1;
* Wait until the pod it creates is `Running`;
* Take the node where the pod is running offline;
* Observe that the newly-created pod by the replication controller stays `Pending`.

That said, I wasn't able to repro this on another cluster with the same `kubectl version` and replication controller template. This is not the first time I observe this issue, though.

**Anything else we need to know?**:
The pod uses node selectors and `podAntiAffinity`. Not sure if either is related though.
For the node selectors, I made sure that there are available nodes with the required label. I also made sure the `podAntiAffinity` conditions are able to be met on the cluster.
Deleting the pod does not help. We create a new pod, but see the same events on `describe pod` or `events`: `node '<node that doesn't exist any more>' not found`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0-4+642b8e765cab78", GitCommit:"642b8e765cab789da74297cc294f910e37b402a3", GitTreeState:"clean", BuildDate:"2017-07-11T02:43:48Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Kernel (e.g. `uname -a`):
```
Linux prod-kube-master000.ec2 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kube-aws
- Others:
Output of `kubectl get rc <rc-name> -o json`: https://gist.github.com/borgesgabriel/562feb13235f2c085088b03f2d7636e1
Output of `kubectl describe pod <pod-name>`: https://gist.github.com/borgesgabriel/694e2c9e79b192b966d455366411d362
Output of `kubectl get event -w`:
```
LASTSEEN                        FIRSTSEEN                       COUNT     NAME        KIND      SUBOBJECT   TYPE      REASON             SOURCE              MESSAGE
2017-08-17 00:35:48 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   413       zk1-l3f47   Pod                   Warning   FailedScheduling   default-scheduler   node 'ip-10-0-22-60.us-west-2.compute.internal' not found
2017-08-17 00:36:16 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   694       zk1-l3f47   Pod                 Warning   FailedScheduling   default-scheduler   node 'ip-10-0-23-27.us-west-2.compute.internal' not found
2017-08-17 00:36:48 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   414       zk1-l3f47   Pod                 Warning   FailedScheduling   default-scheduler   node 'ip-10-0-22-60.us-west-2.compute.internal' not found
2017-08-17 00:36:49 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   695       zk1-l3f47   Pod                 Warning   FailedScheduling   default-scheduler   node 'ip-10-0-23-27.us-west-2.compute.internal' not found
2017-08-17 00:36:49 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   415       zk1-l3f47   Pod                 Warning   FailedScheduling   default-scheduler   node 'ip-10-0-22-60.us-west-2.compute.internal' not found
2017-08-17 00:36:49 +0000 UTC   2017-08-16 21:07:20 +0000 UTC   416       zk1-l3f47   Pod                 Warning   FailedScheduling   default-scheduler   node 'ip-10-0-22-60.us-west-2.compute.internal' not found
```
The output of `kubectl get node` does not include either of the nodes whose hostname is "not found".

**Comment by resouer** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by timothysc** [comment]
It's most likely a permutation of your node-selector and anti-affinity rules.  

What happens when you describe the pod that is pending?

**Comment by borgesgabriel** [comment]
Linking the output of `kubectl describe pod <pod-name>` again: https://gist.github.com/borgesgabriel/694e2c9e79b192b966d455366411d362

I'm pretty confident in my assessment at the time that node-selector and anti-affinity requirements were met when the pod was pending. Besides, wouldn't a "couldn't schedule pod because no nodes match requirements" event show up in `describe pod`?

**Comment by timothysc** [comment]
I'll double check the node-controllers timeout interval to bounce the workload.  In the mean time you may want to reconsider how your are deploying ZK: https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/

**Comment by jayunit100** [comment]
I've seen this as well in 1.6.6 on gce recently when a node went unhealthy .  Waited a very long time... 10
Minutes ....and the pod was just in a hung state.   

- Is there something  that times out a pending pod after some period that would prevent this from being an issue ? Should there be ?

- Or maybe there's some logic  missing in the controllers for this corner case depending on the timing of the node.

- Or maybe the scheduler should check right before assignment that the node is healthy / has been healthy for the last 30 seconds.

**Comment by wenlxie** [comment]
This may related with following condition:

1.  The node had been removed from the cluster,
2.  There are pod that  used to running on there node still exists

If you deleted these pods, then the new pod will get normally scheduled.

I think this is related with function:
```go
func (cache *schedulerCache) RemoveNode(node *api.Node) error {
	cache.mu.Lock()
	defer cache.mu.Unlock()

	n := cache.nodes[node.Name]
	if err := n.RemoveNode(node); err != nil {
		return err
	}
	// We remove NodeInfo for this node only if there aren't any pods on this node.
	// We can't do it unconditionally, because notifications about pods are delivered
	// in a different watch, and thus can potentially be observed later, even though
	// they happened before node removal.
	if len(n.pods) == 0 && n.node == nil {
		delete(cache.nodes, node.Name)
	}
	return nil
}
```
Here we can see if there are pod not cleaned, the node will not be deleted from cache.nodes
And at the function ：

CalculateInterPodAffinityPriority()， it calls GetNodeInfo(),
```go
// GetNodeInfo returns cached data for the node 'id'.
func (c *CachedNodeInfo) GetNodeInfo(id string) (*api.Node, error) {
	node, exists, err := c.Get(&api.Node{ObjectMeta: api.ObjectMeta{Name: id}})

	if err != nil {
		return nil, fmt.Errorf("error retrieving node '%v' from cache: %v", id, err)
	}

	if !exists {
		return nil, fmt.Errorf("node '%v' not found", id)
	}

	return node.(*api.Node), nil
}
```
I think here it will get the nodes from somewhere that node had been removed, 
and then this issue happens.
