### ISSUE TITLE
Enable `kubefed init` accept a file to set up the control panel

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#50817]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Now I need to use a complex command to for `kubefed init` to set up the federation control panel as following:

```
kubefed init federation-cluster \
     --host-cluster-context=host-context \
     --dns-provider="coredns" \
     --dns-zone-name="example.com." \
     --dns-provider-config="/root/federation/coredns-provider.conf" \
     --api-server-service-type="NodePort" \
     --api-server-advertise-address="x.x.x.x" \
     --etcd-image="library/etcd:v3.1.5" \
     --etcd-persistent-storage=false \
     --etcd-pv-capacity="10Gi" \
     --etcd-pv-storage-class="" \
     --federation-system-namespace="federation-system" \
     --image="kubernetes:v1.7.3" \
     --apiserver-arg-overrides="" \
     --controllermanager-arg-overrides=""
```

It would be great to enable `kubefed init` can accept a file just like what we do for `kubectl apply -f <filename>`, so that I can put all parameters in a file which is easy to maintain.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig federation

/cc @kubernetes/sig-federation-feature-requests

**Comment by tengqm** [comment]
Alright, you are talking about a special "kind: FederationInitialization" struct. I am not voting against this as an alpha feature.
The thing I'm challenging is the fact that all these are hardcoded into the kubefed binary. In real life, the deployment of the federation control plan may have a lot knobs for tuning. I'd prefer a collection of well structured Shell scripts for this. After all, the stability of a software doesn't get improved by the fact it has been compiled into a binary.

**Comment by quinton-hoole** [comment]
#50815

**Comment by tengqm** [comment]
#12245

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#34.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
