### ISSUE TITLE
The rescheduler can not be started up due to the stdout point to a directory

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#50820]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
when create rescheduler resources with https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest, find the pod started failed due to the rescheduler.log was a directory.

**What you expected to happen**:
The pod should be started and should use -logtostderr to output the log to a file.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/rescheduler.manifest

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by crassirostris** [comment]
All system components currently write logs in this fashion, see for example https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L270

/cc @kubernetes/sig-storage-bugs @saad-ali

**Comment by wongma7** [comment]
Unless rescheduler.log is a file and already exists, docker will always create a directory at the path rescheduler.log. It can't know/infer whether you intend to mount a given path as a file or directory so defaults to directory. kube-apiserver.log and such are created beforehand to avoid this issue https://github.com/kubernetes/kubernetes/blob/eab039d7462cd87f395e628ee7cc852e011f153a/cluster/saltbase/salt/kube-apiserver/init.sls#L28

**Comment by crassirostris** [comment]
@wongma7 Thanks!

There's a file for rescheduler: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/rescheduler/init.sls#L11

@hchenxa Maybe you're not using salt properly?

**Comment by hchenxa** [comment]
Thanks @crassirostris @wongma7, it's yes that I am not using salt properly, and it the rescheduler.log was created by salt, the container can be started successful.

and as rescheduler support logrotate in fix https://github.com/kubernetes/contrib/commit/07514af5130851992cedff5b60a4aeb64970ab88 and included in rescheduler:v0.3.1 so I prefer to enable logrotate in this issue and also the have PR https://github.com/kubernetes/kubernetes/pull/50822.

**Comment by crassirostris** [comment]
@hchenxa Rescheduler has to write to stderr, that's the common patter for system containers. What you can do instead is add rescheduler in the [logrotate salt config](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/logrotate/init.sls#L5) or switch to GCP, where this problem [is solved](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L165).
