### ISSUE TITLE
k8s 1.7.3 secret mount but can not find in container

### ISSUE THREAD

**Issue by denkensk** [kubernetes/kubernetes#50847]
Is this a BUG REPORT or FEATURE REQUEST?:
/kind bug

**What happened**:
secret mount but can not find in container

-kubectl describe pods nginx-dm-81026071-drq05
![image](https://user-images.githubusercontent.com/8958057/29415333-4d022426-8395-11e7-9719-3c42524e6481.png)

-in vm, I can find secret in /var/lib/kubelet/pods/fdcbe17e-8351-11e7-9c67-fa163ea2f8ed/volumes/kubernetes.io~secret/default-token-55hck
![image](https://user-images.githubusercontent.com/8958057/29415406-8d0b6be0-8395-11e7-8285-422209ffb6a2.png)
![image](https://user-images.githubusercontent.com/8958057/29415535-f0f19f76-8395-11e7-8002-72c3cb5b844f.png)

-but when i exec into container, I can find nothing in /var/run/secrets/kubernetes.io/serviceaccount
![image](https://user-images.githubusercontent.com/8958057/29415519-e6081284-8395-11e7-9d83-aa7ff4ac6bf0.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.7.3
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
ubuntu 14.04.3 LTS
- Kernel (e.g. `uname -a`):
3.11.0
- Install tools:
- Others:

**Comment by denkensk** [comment]
![image](https://user-images.githubusercontent.com/8958057/29415595-1d7dc524-8396-11e7-98ed-0969b51a37b7.png)

**Comment by denkensk** [comment]
![image](https://user-images.githubusercontent.com/8958057/29415780-af197cda-8396-11e7-82d3-53463f27f000.png)

**Comment by denkensk** [comment]
![image](https://user-images.githubusercontent.com/8958057/29415796-bdc0a8bc-8396-11e7-8606-f1a3eaace555.png)

**Comment by liggitt** [comment]
issues with seeing contents of a secret or configmap mounted inside a container are more @kubernetes/sig-storage-bugs or @kubernetes/sig-node-bugs

**Comment by rootfs** [comment]
@denkensk can you post container's mount output and kubelet log?
