### ISSUE TITLE
fluentd gcp addon seems to have wrong max values

### ISSUE THREAD

**Issue by tlbdk** [kubernetes/kubernetes#50845]
**What happened**:

```
kubectl logs fluentd-gcp-v2.0-l9j3s fluentd-gcp --namespace=kube-system -f
2017-08-17 12:24:55 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-17 12:25:25 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3f9603437adc"
  2017-08-17 12:24:55 +0000 [warn]: suppressed same stacktrace
2017-08-17 12:25:25 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-17 12:25:55 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3f9603437adc"
  2017-08-17 12:25:25 +0000 [warn]: suppressed same stacktrace
```

**What you expected to happen**:
My logs should show up in slackdriver

**How to reproduce it (as minimally and precisely as possible)**:
We are seeing this in a production system where we trigger this issue, but can't see why.

**Anything else we need to know?**:

Could it be that the default limits in the fluentd gcp image is wrong?

https://cloud.google.com/logging/quota-policy

Size of a log entry	100 KB*
Size of an entries.write request	5 MB*

From the fluentd gcp addon configuration:

```
 <match kubernetes.**>
      @type google_cloud
     ....
      # Set the chunk limit conservatively to avoid exceeding the GCL limit
      # of 10MiB per write request.
      buffer_chunk_limit 2M
      # Cap the combined memory usage of this buffer and the one below to
      # 2MiB/chunk * (6 + 2) chunks = 16 MiB
      buffer_queue_limit 6
       ...
    </match>
    # Keep a smaller buffer here since these logs are less important than the user's
    # container logs.
    <match **>
      @type google_cloud
      ...
      buffer_chunk_limit 2M
      buffer_queue_limit 2
      ...
    </match>
```

**Environment**:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Standard Google Cloud Engine Cluster

**Comment by crassirostris** [comment]
@tlbdk From the message I see that fluentd fails to talk to Stackdriver. Do you see the failed requests in the API manger? Is there more information in the logs regarding e.g. the http status code?

**Comment by tlbdk** [comment]
@crassirostris yes, I'm seeing 8081 http status 500 errors in the last day, is there a way to see that request or response that failed?

**Comment by crassirostris** [comment]
@igorpeshansky Could you please reference some docs for debugging this issue?

**Comment by igorpeshansky** [comment]
This is happening on the server side. You'll want to ask the backend team to find those 500s. I'm on vacation, so @qingling128 can point you at the right people to mention.
The only known (to me) 500 happens when the total request size is too big, but with gRPC, a 2M chunk should not produce anything close to the 10M limit when encoded.

**Comment by qingling128** [comment]
@tlbdk Can you share the project id? Through email if needed.

**Comment by tlbdk** [comment]
Our project id is connectedcars-147810

**Comment by qingling128** [comment]
Summit helped check the server side logs. Seems the issue is similar to a known issue in the GRPC layer when server could not parse request sent by client. We are still investigating (haven't found a way to reliably reproduce the issue).

@tlbdk How frequent are you seeing this error? For `Google::Apis::ServerError`, the agent should always retry sending the logs. Just FYI, if there are not recurring `Google::Apis::ServerError` in the log, the logs should arrive eventually. If it's frequent enough, maybe we could work together to add more logging in the agent (right now we are not logging anything for server errors) and try to reproduce the issue. Knowing what requests are triggering this kind of issue can help speed up the investigation.

**Comment by tlbdk** [comment]
It's in a retry loop sending the same error over and over again, I would be happy to update the agent with one that shows better debug output.

**Comment by tlbdk** [comment]
fx. from this morning:

```
kubectl --namespace=kube-system get pods|grep fluentd|cut -d ' ' -f 1|xargs -I POD kubectl --namespace=kube-system logs --tail 5 POD fluentd-gcp
```
```
  2017-08-18 08:12:01 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:12:31 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:01 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fccdc026208"
  2017-08-18 08:12:31 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:13:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:31 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fccdc026208"
  2017-08-18 08:13:01 +0000 [warn]: suppressed same stacktrace
  2017-08-18 08:12:13 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:12:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:13 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fcd18e401f4"
  2017-08-18 08:12:43 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:13:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:43 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fcd18e401f4"
  2017-08-18 08:13:14 +0000 [warn]: suppressed same stacktrace
  2017-08-18 08:12:14 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:12:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:13 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fb4e9626208"
  2017-08-18 08:12:44 +0000 [warn]: suppressed same stacktrace
2017-08-18 08:13:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-18 08:13:43 +0000 error_class="Google::Apis::ServerError" error="Server error" plugin_id="object:3fb4e9626208"
  2017-08-18 08:13:14 +0000 [warn]: suppressed same stacktrace
```

**Comment by tlbdk** [comment]
Tried creating a custom image for debugging the issue where I dump the response body when I get the error, here is what I got back so far:

```
W, [2017-08-18T08:17:27.064248 #10]  WARN -- : Response body: {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "errors": [
      {
        "message": "Internal error encountered.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "INTERNAL"
  }
}
```

I could use some hints on how to replace the current running image as it gets rolled back to the old version as soon as I apply the custom debug image, so far I have renamed it and I'm running it on the side.

**Comment by tlbdk** [comment]
I did a bit more work and managed to capture the body of a failing request, it's from our production system so how can i share this in secure way?

**Comment by igorpeshansky** [comment]
@qingling128 will send you an email with her and my Google email address that you can share a Google doc with. If you give us edit access, we'll share it with others on the backend team who need to see it.

**Comment by tlbdk** [comment]
@igorpeshansky I already sent an e-mail with the debug info to @qingling128 so you should have something to look at if I don't response back right away

**Comment by tlbdk** [comment]
Did a bit of testing with the API explorer trying to send the payload and find out what part of the logging fails, we are sending some very large JSON structures in the jsonPayload, 20K lines and that seems to cause the problem.

Response headers:

```
alt-svc:quic=":443"; ma=2592000; v="39,38,37,35"
cache-control:private
content-encoding:gzip
content-length:104
content-type:application/json; charset=UTF-8
date:Fri, 18 Aug 2017 12:39:42 GMT
server:ESF
status:500
vary:Origin
vary:X-Origin
vary:Referer
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-xss-protection:1; mode=block
```

Response body:

``` json
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

**Comment by tlbdk** [comment]
Did a bit more testing and it seems i get internal when either the size or the nesting reaches a certain limit, under that I get a message too large

**Comment by jdumars** [comment]
this will eventually be SIG GCP but per current policy, it's being assigned to
/sig cluster-lifecycle

**Comment by tlbdk** [comment]
Got time to cook up an example of where it fails:

``` json
{
  "labels": {
    "compute.googleapis.com/resource_name": "gke-connectedcars-produc-default-pool-e9ca3824-0840",
    "container.googleapis.com/namespace_name": "default",
    "container.googleapis.com/pod_name": "web-1089063163-fd4kj"
  },
  "resource": {
    "type": "container",
    "labels": {
      "cluster_name": "connectedcars-production",
      "instance_id": "1010055681835557431",
      "zone": "europe-west1-d",
      "container_name": "web",
      "namespace_id": "default",
      "pod_id": "web-1089063163-fd4kj"
    }
  },
  "logName": "projects/connectedcars-147810/logs/web",
  "entries": [
    {
      "timestamp": {
        "seconds": 1503031572,
        "nanos": 0
      },
      "resource": {
        "type": "container",
        "labels": {
          "cluster_name": "connectedcars-production",
          "instance_id": "1010055681835557431",
          "zone": "europe-west1-d",
          "container_name": "web",
          "namespace_id": "default",
          "pod_id": "web-1089063163-fd4kj"
        }
      },
      "jsonPayload": {
        "nested": {
            "nested": {
                "nested": {
                    "nested": {
                        "nested": {
                            "nested": {
                                "nested": {
                                    "nested": {
                                        "nested": {
                                            "nested": {
                                                "nested": {
                                                    "nested": {
                                                        "nested": {
                                                            "nested": {
                                                                "nested": {
                                                                    "nested": {
                                                                        "nested": {
                                                                            "nested": {
                                                                                "nested": {
                                                                                    "nested": {
                                                                                        "nested": {
                                                                                            "nested": {
                                                                                                "nested": {
                                                                                                    "nested": {
                                                                                                        "validate": {
                                                                                                            "nested": {
                                                                                                                "nested": {
                                                                                                                    "nested": {
                                                                                                                        "nested": {
                                                                                                                            "nested": {
                                                                                                                                "nested": {
                                                                                                                                    "nested": {
                                                                                                                                        "nested": {
                                                                                                                                            "nested": {
                                                                                                                                                "nested": {
                                                                                                                                                    "nested": {
                                                                                                                                                        "validate": {
                                                                                                                                                            "nested": "stuff"
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "level": "info"
      },
      "labels": {
        "compute.googleapis.com/resource_name": "gke-connectedcars-produc-default-pool-e9ca3824-0840",
        "container.googleapis.com/namespace_name": "default",
        "container.googleapis.com/pod_name": "web-1089063163-fd4kj",
        "container.googleapis.com/stream": "stdout"
      },
      "severity": "INFO"
    }
  ]
}
```

**Comment by qingling128** [comment]
That's very helpful! Thanks @tlbdk. I'll let the other framework team know. Will update the tickets with any findings.

**Comment by tlbdk** [comment]
Hi @qingling128, any update on this?

I think the error subject is a bit misleading as this issue is related to an error with deeply nested jsonPayload as we found out after the debugging, should we create a new issue?

Also after we started to sanitise our logs for the deep nesting we started to get another type of errors:

2017-08-23 06:10:21 +0000 [warn]: Dropping 102 log message(s) error_class="Google::Apis::ClientError" error="badRequest: Log entry with size 810078 bytes exceeds maximum size of 112640 bytes"

As far as I can read this means that if one of the log message in a batch is larger than the allowed size all the messages are dropped even if they are completely unrelated.

Both of these issues are related to limits in stackdriver that really should be handled in the fluentd  out_google_cloud plugin, fx. by truncating the log message if it exceeds the supported size or JSON nesting depth. I think it would be a fair assumption that the log shipper never throws logs away or stops working no mater what is logged.

**Comment by igorpeshansky** [comment]
@tlbdk The fact that deep nesting produces an internal error is a bug in the underlying transport layer that's being investigated independently. Such entries should have been rejected as invalid.
As for the individual entries being too large, we've been discussing this for some time now, and there's no good automatic way to make those entries valid — truncation isn't safe in general. Such entries are likely to keep getting rejected. We are working on an alternate approach that will avoid losing the whole batch when encountering a bad entry.

**Comment by tlbdk** [comment]
@igorpeshansky It would be nice with some sanitation options for the depth until it was solved if fixing the underlying transport is a larger project.

In our logging framework we have started doing this by converting the message to textPayload and prepending "Depth limited " 

As for the too large issue, I still think the current implementation is the absolutely worst outcome: throw away a random bunch of log message along with the one that was too large. 

In our logging framework we have started doing by truncating the message to 100KB and prepend "Truncated " to it. At least this provides some information on where to find the location the large message was logged so it can be fixed in the application.

Implementation for both in node is here:
https://github.com/connectedcars/node-logutil/blob/master/src/format.js#L62

If you find a good way to retry on failed batches, fx by sending them individually then it would be nice if the same was done for 500 errors so small bugs in slackdriver does not bring down logging for a complete cluster.

**Comment by igorpeshansky** [comment]
The solution you're describing is perfectly sensible as a user-defined policy, but would be terrible as default agent behavior, since not everyone is willing to live with such a lossy approach. It's possible to implement effectively the same policy by configuring the logging agent, but not on GKE, where that configuration is not accessible.
Finally, 500 errors are already retried. Most 400 errors cause logs to be dropped.

**Comment by tlbdk** [comment]
I agree that loosing logs is not acceptable behavior, but this is what is happening right now, even unrelated logs get lost with the current setup. So truncating in my world is way less terrible. Alternatively could be to split the log message in multiple parts, get stackdriver to up the limit, leave the message on the node, etc. Anything is better than just dropping a bunch of unrelated logs messages in the process as is the current behavior.

Yes 500 are retried but effectively blocks all logging from cluster, so again the worst possible default behavior.

I do understand that it's hard to build a system for everyone, but a small mistake like the one that got us started on this debug session should not effectively kill logging for a complete cluster, what we did was dump a large ORM entity structure to the log by mistake. I don't think we will be the last ones to do so and it would be nice if the next person could actually debug this a bit easier fx by seeing an error in the stackdriver logging that the message was the problem. We had to modify the image to get fluentd to dump the message and get it running in the cluster without GKE killing it, not really what we where expect to be doing on a hosted service.

**Comment by igorpeshansky** [comment]
As I said above, we are already working on a solution that would not lose unrelated log entries. Also, as said above, the 500 returned for a deeply nested entry structure is a bug in the underlying infrastructure -- once that's fixed, the agent will do the right thing.

**Comment by igorpeshansky** [comment]
@tlbdk Unfortunately, we don't have an ETA on the fixes. As a workaround, you could add a custom logging agent config in your cluster that truncates long log lines. This will lose automatic updates of the logging agent DaemonSet in the cluster.
The configuration will need the following additional snippet (untested):
```
<filter kubernetes.*>
  @type record_transformer
  enable_ruby
  <record>
    log ${record['log'][0:100000]}
  </record>
</filter>
```
This will indiscriminately truncate long lines, likely resulting in malformed JSON. I'm sure we could concoct something that would also produce valid JSON, but this should at least prevent erroneous log lines from poisoning the whole batch.

**Comment by qingling128** [comment]
b/65481001 has been created to track the internal work for the underlying transport layer change ("Deeply nested JSON messages should raise a 400 error instead of 500").

**Comment by tlbdk** [comment]
All issues seems to have been fixed now, so closing
