### ISSUE TITLE
connection between services are failing in the first attempt

### ISSUE THREAD

**Issue by bilalyasar** [kubernetes/kubernetes#50844]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

```
W0817 12:34:57.200644       1 backup_handler.go:65] backup-worker-155201422-5n299 | Failed to 
get environment detail:Get http://environment-worker:503/v3/environments/11AEC97A1C6D555F: dial 
tcp: lookup environment-worker on 100.64.0.10:53: server misbehaving
```
inside my cluster, one of the micro service calls the another one.. but always the first request is failing.. the others are success, I'm using golang http client.
I found that, if there is some time gap from the last request this error happens.
I suspect this might be kube-dns issue

**Environment**:
- Kubernetes version (use `kubectl version`): v1.5.2
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): default KOPS configuration

/sig network

**Comment by bilalyasar** [comment]
@kubernetes/sig-network

**Comment by bilalyasar** [comment]
@kubernetes/sig-network-bugs

**Comment by cmluciano** [comment]
cc @bowei

**Comment by canhnt** [comment]
It relates to #39980

**Comment by wknapik** [comment]
Any news on this ? @justinb - I think this might be an issue you're familiar with ?
