### ISSUE TITLE
Kubemark-5000 flaking during hollow-node creation

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#50854]
Some e.g runs that failed:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/563
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/567
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/576

They all failed with the following error:

```
I0816 15:27:40.799]  Timeout waiting for all hollow-nodes to become Running. 
I0816 15:27:40.992] Found only 0 ready hollow-nodes while waiting for 5000.
```

cc @kubernetes/sig-scalability-bugs @wojtek-t @gmarek

**Comment by shyamjvs** [comment]
The reason is that none of the kubelets even received the hollow-node pods, which in turn was due to scheduler not able to schedule them because of:

```
I0816 14:57:40.080027       6 scheduler.go:166] Failed to schedule pod: kubemark/hollow-node-slm5q
I0816 14:57:40.080067       6 factory.go:903] Unable to schedule kubemark hollow-node-slm5q: no fit: No nodes are available that match all of the following predicates: NodeNetworkUnavailable (81), NodeUnschedulable (1).; waiting
```

**Comment by shyamjvs** [comment]
And the reason why all the nodes had NodeNetworkUnavailable condition is because the route-controller failed to create routes for the nodes. And that was due to failing list routes call to GCE:

```
E0816 15:28:42.958478       6 gce_routes.go:56] Error getting routes from GCE: googleapi: got HTTP response code 502 with body: <!DOCTYPE html>
...
...
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
E0816 15:28:42.958511       6 route_controller.go:115] Couldn't reconcile node routes: error listing routes: googleapi: got HTTP response code 502 with body: <!DOCTYPE html>
```

**Comment by wojtek-t** [comment]
I would say to quickest fix for that is (and I think we should do that anyway):
```
create a separate dedicated project for kubemark-scale
```

This obviously is not fixing the problem itself, but it will mitigate the consequences (and I think that it should be running in a separate project anyway).

**Comment by shyamjvs** [comment]
Discussed offline with @ignacyk to unblock other tests.

**Comment by shyamjvs** [comment]
fyi @piosz - I guess you faced this issue earlier too.

**Comment by shyamjvs** [comment]
This issue is now resolved after moving to separate project.
https://k8s-testgrid.appspot.com/sig-scalability#kubemark-5000
