### ISSUE TITLE
To global Scheme, or not to global Scheme

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#50855]
This issue is for continuing the discussion here https://github.com/kubernetes/kubernetes/pull/50789#discussion_r133549650

on whether to have global schemes per API group, or to construct schemes as needed and plumb to usage sites.

**Comment by mtaufen** [comment]
And of course, if you can live with multiple copies of a Scheme floating around, then local is the clear-winner.

**Comment by deads2k** [comment]
@sttts and I had considered one scheme per process, but having used it a little more, I think I prefer plumbing a scheme to the places that need it.  The clients do this for you automatically, leaving mostly just the server-side of things to maintain and plumb into their storage methods.
