### ISSUE TITLE
Documentation about required ports is lacking

### ISSUE THREAD

**Issue by tessiof** [kubernetes/kubernetes#50868]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
The [documentation](https://kubernetes.io/docs/setup/independent/install-kubeadm/) says I need to "check required ports", which is vague and don't convey much meaning.

**What you expected to happen**:
Specify the transport protocol (TCP or UDP) of each port, if I need to accept outgoing or incoming traffic, and to/from where the traffic if going/coming.  

**How to reproduce it (as minimally and precisely as possible)**:
Read the documentation.

**Anything else we need to know?**:
No.

Ps. CoreOS [documentation](https://coreos.com/kubernetes/docs/latest/kubernetes-networking.html) has all the necessary information.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
fixed in #6319
