### ISSUE TITLE
OpenAPI aggregation refresh

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#50863]
Current implementation of OpenAPI aggregation assumes the specs are static. We need a way to update the aggregated spec when the specs changed. One simple solution could be refreshing specs periodically.

@sttts @deads2k

**Comment by deads2k** [comment]
> Current implementation of OpenAPI aggregation assumes the specs are static. We need a way to update the aggregated spec when the specs changed. One simple solution could be refreshing specs periodically.

Given the low cardinality of APIServices, I think that could work out naturally as a controller driven flow on a fairly tight resync.  Adding a status condition for openapi aggregation could provide additional triggers from within the same controller
