### ISSUE TITLE
accessing service using nodeport from outside host(flannel environment)

### ISSUE THREAD

**Issue by pnuzyf** [kubernetes/kubernetes#50881]
Dear guys:

        I am confused when I tested the k8s network. My scenario is listed as follows:
        Host A access a service using nodeport.  Due to the iptables entry "KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE", the source ip address in the orignial ip packet sent by A is changed with the ip of docker0. Then one of the service pod would receive the new ip packet. In this case, the pod does not know the real destination. How could the response be routed to host A?
       I caputered the packet flow using wireshark.  I found that the  following cases:
       A------>pod:  the source ip is changed to the ip of docker0
      pod--->A: the destination ip is host A, the source ip is changed to the ip of the node where the pod resides. 

       I can not connect my analysis with the wireshark. Anyone can explain?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.3
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): centos7.1
- Kernel (e.g. `uname -a`): Linux kube2 3.10.0-229.el7.x86_64
- Install tools: 
- Others:

**Comment by chestack** [comment]
I think what you confused is how DNAT/SNAT works which uses Conntrack module to  maintain state information about a connection in memory tables. 
ref: http://www.rigacci.org/wiki/lib/exe/fetch.php/doc/appunti/linux/sa/iptables/conntrack.html

**Comment by cmluciano** [comment]
@pnuzyf Does what @chestack mentioned make sense?
