### ISSUE TITLE
[Flaky] GPU test failed

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#50884]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
One of the GPU tests started failing after this PR:
https://k8s-testgrid.appspot.com/wg-resource-management#gke-gpu&show-stale-tests=

First failed run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gpu/647?log#log
Last successful run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gpu/646?log#log

/assign
/sig scheduling

**Comment by k82cn** [comment]
One interesting thing is that: seems calico is deployed by deployment; the network is unavailable before it's deployed. By default, we'll use DaemonSet for calico; the DaemonSet will tolerate network unavailable to start calico daemons :). Let me check what happened for this case.

```
I0812 22:53:52.595] Aug 12 22:53:52.595: INFO: At 2017-08-12 22:42:51 +0000 UTC - event for calico-typha: {deployment-controller } ScalingReplicaSet: Scaled up replica set calico-typha-224432132 to 1
```

```
calico-typha-224432132-4smcp               Pending       [{Type:PodScheduled Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-08-12 22:42:51 +0000 UTC Reason:Unschedulable Message:No nodes are available that match all of the following predicates: NodeNetworkUnavailable (3), NodeNotReady (3).}]
```

**Comment by k82cn** [comment]
And we found this flaky test after https://github.com/kubernetes/kubernetes/pull/50362 merged. I'm checking it.

/cc @bsalamat , @mindprince

**Comment by k82cn** [comment]
@kubernetes/sig-testing-bugs 

It's not a test bug, but there's some question for the investigation:

1. why we deploy calico by Deployment? is there any DaemonSet for it? how to check it?
2. what means for the white box for `BeforeSuite`, passed or not run?

![e2e-gpu](https://user-images.githubusercontent.com/18107181/29444908-dd47c2ea-8415-11e7-81f9-091a7111ac08.jpg)

**Comment by mindprince** [comment]
https://github.com/kubernetes/kubernetes/issues/50723 has more tests which started seeing the same problem after #50362 
/cc @yujuhong 
Can we revert #50362 until we find what's wrong with it?

**Comment by bsalamat** [comment]
+1 to reverting #50362 until we find the root cause of the change of behavior caused by the PR.

**Comment by k82cn** [comment]
sure, let me revert it firstly :).

**Comment by k82cn** [comment]
reverted, let see what happened next :).

**Comment by mindprince** [comment]
The tests are passing again now.
