### ISSUE TITLE
tokens controller shouldn't create secret when namespace is terminating

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#50886]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug
 

---

**What happened**:    

**Operation**
1. create namespace
2. wait until all related secrets are created successfully
3. delete namespace

**Result**
1. apiserver has error log

```
Admit error: secrets "default-token-9shcg" is forbidden: Unable to create new content in namespace perftest-c-1502963261-0-0 because it is being terminated.

```

2. tokens controller has error log

```
tokens_controller.go:174] secrets "default-token-9shcg" is forbidden: Unable to create new content in namespace perftest-c-1502963261-0-0 because it is being terminated.

```

**Reason**
- delete namespace, apiserver will set deletionTimeStamp and terminating.
- namespace controller watch this event, starting delete all contents under this namespace, including secrets.
- tokens controller watch secret delete event, and will update correspongding ServiceAccount by removing reference of this secret.
- tokens controller watch ServiceAccount update event, and will create service-account-token if needed.
- apiserver get this POST request, reject it because namespace is terminating.

---

**What you expected to happen**:

There should not be error log.

When namespace is terminating, tokens controller should not create secret under it.

That is to say, tokens controller should add namespace cache. When create secret, check namespace firtly.

---

**How to reproduce it (as minimally and precisely as possible)**:

1. create namespace
2. wait until all related secrets are created successfully
3. delete namespace

---

**Anything else we need to know?**:

Not critical and not has great bad effect. But it is not the reason we ignore this problem.

---

**Environment**:
- Kubernetes version (use `kubectl version`):  1.3.5

**Comment by mml** [comment]
@shenlanse Is this causing you any problems in production?

**Comment by shenlanse** [comment]
@mml  Not cause bad effects. But I think error log shouldn't exist in normal state.

**Comment by liggitt** [comment]
It is normal for creations to be rejected while a namespace is terminating. In this case, the error is harmless, but we still want it logged for cases where the create failed and the namespace was not terminating

/close
