### ISSUE TITLE
how does scheduler determine node info?

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#50892]
kubelet collect node info (by advisor) and sent to apiserver every 10s. Scheduler will watch this nodes and cache it for scheduling.After scheduling,scheduler will assumePod which lead to cached nodes info inconsistent with data in apiserver.Which one will be used in next scheduling?

**Comment by bsalamat** [comment]
@mjaow It is not clear what you exactly mean by "cached nodes info inconsistent with data in apiserver". Scheduler has watches on certain objects, particularly nodes and pods, and when they change scheduler is notified and acts on them.
One piece of information that scheduler does not use is the actual amount of resource usage on nodes. Scheduler works with pods' resource requests (not by resource usage).
Please send your questions to: kubernetes-sig-scheduling@googlegroups.com

**Comment by k82cn** [comment]
In next cycle, scheduler will use nodeInfo from cache; the assumePod is also considered using the resources because delay of bind call. If any exception, the scheduler will clear it up.

**Comment by mjaow** [comment]
@k82cn ,@bsalamat ,I see... 
scheduler don't need to know the actual amount of resource usage on nodes.It just collect node info like disk,mem,cpu capacity and the request resource of pods binding on this node from apiserver.So the actual usage is not considered.This in turn update cache of scheduler,which then used for scheduling.
