### ISSUE TITLE
Local PV does not cleanly unmount in some cases

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#50894]
/kind bug

During an update of a statefulset (OnDelete, manually deleteting instances) twice (out of 125) happened this, kept repeating in the log for some time until I restarted the kubelet:
```
I0818 10:57:02.332181    2235 reconciler.go:186] operationExecutor.UnmountVolume started for volume "barrels" (UniqueName: "kubernetes.io/local-volume/1d8e3815-8272-11e7-a205-1402ec40deb8-finder-barrels-111") pod "1d8e3815-8272-11e7-a205-1402ec40deb8" (UID: "1d8e3815-8272-11e7-a205-1402ec40deb8") 
I0818 10:57:02.332264    2235 reconciler.go:186] operationExecutor.UnmountVolume started for volume "default-token-nftzh" (UniqueName: "kubernetes.io/secret/1d8e3815-8272-11e7-a205-1402ec40deb8-default-token-nftzh") pod "1d8e3815-8272-11e7-a205-1402ec40deb8" (UID: "1d8e3815-8272-11e7-a205-1402ec40deb8") 
E0818 10:57:02.332459    2235 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/1d8e3815-8272-11e7-a205-1402ec40deb8-default-token-nftzh\" (\"1d8e3815-8272-11e7-a205-1402ec40deb8\")" failed. No retries permitted until 2017-08-18 10:59:04.332431424 +0200 CEST (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "default-token-nftzh" (UniqueName: "kubernetes.io/secret/1d8e3815-8272-11e7-a205-1402ec40deb8-default-token-nftzh") pod "1d8e3815-8272-11e7-a205-1402ec40deb8" (UID: "1d8e3815-8272-11e7-a205-1402ec40deb8") : remove /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~secret/default-token-nftzh: device or resource busy
W0818 10:57:02.333396    2235 util.go:105] Warning: "/kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~local-volume/finder-barrels-111" is not a mountpoint, deleting
E0818 10:57:02.333444    2235 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/local-volume/1d8e3815-8272-11e7-a205-1402ec40deb8-finder-barrels-111\" (\"1d8e3815-8272-11e7-a205-1402ec40deb8\")" failed. No retries permitted until 2017-08-18 10:59:04.333427682 +0200 CEST (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "barrels" (UniqueName: "kubernetes.io/local-volume/1d8e3815-8272-11e7-a205-1402ec40deb8-finder-barrels-111") pod "1d8e3815-8272-11e7-a205-1402ec40deb8" (UID: "1d8e3815-8272-11e7-a205-1402ec40deb8") : remove /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~local-volume/finder-barrels-111: device or resource busy
```
actual state: folders were first unmounted and then even deleted, yet kubelet kept spamming ^
```
# ll /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~local-volume/finder-barrels-111:
ls: cannot access /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~local-volume/finder-barrels-111:: No such file or directory
# ll /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~secret/default-token-nftzh:
ls: cannot access /kubernetes/root/pods/1d8e3815-8272-11e7-a205-1402ec40deb8/volumes/kubernetes.io~secret/default-token-nftzh:: No such file or directory
```

Restarting kubelet fixed it. Sadly I will be gone for a week and cannot help track it down in the source code as of right now so if somebody wants to help, feel free to, please.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3 kubelet
- Cloud provider or hardware configuration**: custom
- Kernel (e.g. `uname -a`): rhel7.3

**Comment by msau42** [comment]
@CallMeFoxie have you seen the issue again?  Sometimes this can happen if you still have another shell open in that directory.

**Comment by CallMeFoxie** [comment]
I've had that happen on the forementioned kubernetes version a few times, since then we did a rolling upgrade to 1.7.9 but was not at work during the last update of this service where it has the highest chance of happening (422 pods in two statefulsets).

I think this was more of "it is unmounted and deleted but Kubelet thinks it is still mounted". The pods were stopped and I sure was not SSHed to the target machine.

**Comment by msau42** [comment]
Not just ssh to the node, but also to the pod that is mounting the volume.  How many pods with local volumes do you have per node?  Also, what type of local volume are you using?  A shared directory, or a separate mount point?  I can write some stress tests.

**Comment by CallMeFoxie** [comment]
the pods were long time stopped, there was no opened file to that mount point when I got to it - there may have been at the first attempt at unmounting though, unsure - I noticed the problem when the statefulset's pod was not coming up after a few minutes.
It is just a directory on the main HDD, not a dedicated mount point.
