### ISSUE TITLE
Makefile errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#50909]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

i followed the instructions here:
https://github.com/kubernetes/kubernetes/blob/master/README.md

> You have a working Docker environment.
> $ git clone https://github.com/kubernetes/kubernetes
> $ cd kubernetes
> $ make quick-release

first, i installed Docker, started `dockerd` and that worked.

cloned the Kubernetes github tree in `~/kubernetes`.

by running `make quick-release` i'm getting:
`Makefile:1: *** missing separator`
and nothing else.

so instead i did this:
`make -f ./build/root/Makefile quick-release`

this succeeds until the following is shown:
````
+++ [0818 15:05:29] Verifying Prerequisites....
+++ [0818 15:05:29] Building Docker image kube-build:build-a0984f1cd6-5-v1.8.3-2
+++ [0818 15:05:31] Syncing sources to container
+++ [0818 15:05:32] Running build command...
Makefile:1: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
!!! [0818 15:05:32] Call tree:
!!! [0818 15:05:32]  1: build/../build/common.sh:520 kube::build::run_build_command_ex(...)
!!! [0818 15:05:32]  2: build/release.sh:36 kube::build::run_build_command(...)
build/root/Makefile:404: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1

````

`the run_build_command_ex()` function receives the following args:

```
kube-build-a0984f1cd6-5-v1.8.3-2 -- make cross
```

**What you expected to happen**:

not getting GNU make errors when building Kubernetes!

**How to reproduce it (as minimally and precisely as possible)**:

explanation above in the `What happened` section.

**Anything else we need to know?**:

this is on a clean VM with no special modifications.
it only has docker, git and a few other unrelated tools installed.
only Kubernetes has failed to build thus far.

**Environment**:

- Kubernetes version (use `kubectl version`):
cloned the master branch (as instructed) -> at `9aa04c755`
````
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
````

````
$ git log -1
commit 9aa04c755fc8091ce5a59d0087fe6a4bc0119195
Merge: b67b0ad 05d3e9c
Author: Kubernetes Submit Queue <k8s-merge-robot@users.noreply.github.com>
Date:   Thu Aug 17 04:45:56 2017 -0700
`````

- Cloud provider or hardware configuration**:
?
i'm running a Ubuntu VirtualBox VM on a Windows 7 64bit host on a decent machine

- OS (e.g. from /etc/os-release):
`UBUNTU 16.04.1 LTS (Xenial Xerus)`

- Kernel (e.g. `uname -a`):
`Linux lubo-VirtualBox 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
`apt 1.2.15 (amd64)` ?

- Others:

`GNU Make 4.1`
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) `

--
lubomirivanov @ vmware

**Comment by neolit123** [comment]
@kubernetes/sig-release-bugs

**Comment by neolit123** [comment]
thanks for the reply,

i've re-created both the Makefile and Makfile.generated_files symlinks manually in the root folder with `ln -s` and the build got past that error. deleting them and checking them out from git does not fix the issue for me, which means that the symbolic links stored as-is in the git repository might not work for some folks...odd.

the build now fails with another error, which i first need to investigate a little before closing this ticket.

**Comment by neolit123** [comment]
i'm now experiencing https://github.com/kubernetes/kubernetes/issues/10662
with 4GB of ram available and also by using `taskset 3 make`, so not sure how i'm going to solve that...

closing this ticket as the underlying error was fixed.

**Comment by dabaooline** [comment]
> The Makefile in the root of the repo is a symlink to `build/root/Makefile`. What this tells me is that something in your local environment is breaking that symlink. You'll need to investigate and fix that, as many parts of the build scripts rely on this working correctly.

Thanks, your answer inspired me . I meet the same question at Ubuntu. Finally, I find the git config cause this symlink error.  
symlinks = true
