### ISSUE TITLE
Enable a mechanism SIGs can easily use for manual scalability testing while development

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#50907]
We're currently having automated scale jobs running for CI scalability validation. But multiple other SIGs/teams (e.g instrumentation, security, storage, autoscaler, scheduler etc) have recently started showing interest in scalability testing of features they're developing. The following are main requirements here IMO:
- Be able to run scale testing from their local dev environments (without having to wait to push their changes to the repo and then waiting for them to be tested by our CI jobs)
- Be able to do the above easily (ideally by just running a few commands)
- Not worry about setting up correctly some special config specific to scale-testing (we should do most of this work for them already)
- Ensure that they don't conflict with other jobs running alongside (wrt resource-naming and quotas)

I've started working on making infrastructural changes to solve the above problems.
Personally I love the fact that scalability validation is increasingly gaining traction (which it rightfully should) across the community :)

cc @kubernetes/sig-scalability-feature-requests @kubernetes/sig-testing-misc @wojtek-t @gmarek

**Comment by shyamjvs** [comment]
cc @ignacyk @wasylkowski

**Comment by shyamjvs** [comment]
As an initial step I created a new jenkins project on gcp named 'k8s-scale-testing' which is dedicated purely for this purpose. Requested for an increased quota in the project.
It would help isolate dev-testing from our CI 5k-node jobs, which is a win-win for both sides as we no longer need to block one on the other (which we saw happening recently).

**Comment by kargakis** [comment]
+1 on this, needed by sig-apps for things like https://github.com/kubernetes/kubernetes/pull/49429

**Comment by shyamjvs** [comment]
With scalability presubmits setup (for different scales) both blocking and optional ones that can be triggered using a bot command on a PR, I think this issue can now be closed.
More details here - https://github.com/kubernetes/community/blob/master/sig-scalability/processes/formal-scalability-processes.md#implementation--pre-submit-phase
