### ISSUE TITLE
 AWS provider excludes untagged nodes, causing node deletion on 1.5->1.6 upgrade

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#50915]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug
> /kind feature

**What happened**:
Upgrade 1.5->1.6. Untagged nodes get deleted on kubelet restart. Fortunately, most of my cluster was still tagged with KubernetesCluster (now deprecated).

**What you expected to happen**:
Didn't expect this - it's not mentioned in the CHANGELOG.md as a breaking change. In 1.5, untagged nodes were okay.

**How to reproduce it (as minimally and precisely as possible)**:
Try to start kubelet on a node that doesn't have `KubernetesCluster` or `kubernetes.io/cluster` tag. kubelet will register itself, followed by node-controller deleting it a few seconds later since ExternalID method from aws.go returns nil due to lack of a tag. kubelet gets very confused since it thinks it's registered, but all subsequent apiserver calls on itself return 404.

**Anything else we need to know?**:
I don't think this is broken per se, we just need to document it and mention it as a breaking change. I think tagged nodes were always expected/required.

Although, node-controller should probably NOT delete a node shortly after startup before it can go ready. It should respect grace period when checking the cloudprovider node status.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.8
- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lpabon** [comment]
So should the fix be to update the Changelog?

**Comment by jsravn** [comment]
@lpabon Probably. In addition, I think nodecontroller should be using `node-startup-grace-period` here, which it isn't. The behaviour is inconsistent and confusing. It should give new nodes a chance to go ready before considering them for deletion, even if the cloudprovider says they don't exist. It's pretty edge case, but it took a while to figure out what was causing this problem.

**Comment by jsravn** [comment]
I'm not sure this behavior is desirable at all, actually. If there is some issue in the cloud provider, the controller manager will indiscriminately delete nodes (and their pods), even if the node itself is up and happy and reporting okay status.

**Comment by jsravn** [comment]
Made https://github.com/kubernetes/kubernetes/issues/58334 in favor of this.
