### ISSUE TITLE
Is there a way to specify api server ip for cluster-proportional-autoscaler-amd64 image

### ISSUE THREAD

**Issue by ivankennethwang** [kubernetes/kubernetes#50921]
Is there a way to specify api server ip for cluster-proportional-autoscaler-amd64 image?

**Comment by mattjmcnaughton** [comment]
Would you mind explaining more about the error you're experiencing/use case you're hoping to accomplish?

In the cluster-proportional-autoscaler [README](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/blob/master/README.md), I see the following:
```
The code in this module is a Kubernetes Golang API client that, using the default service account credentials available to Golang clients running inside pods, it connects to the API server and polls for the number of nodes and cores in the cluster.
```

From this statement, it looks like the `cluster-proportional-autoscaler` will connect to the api server by default from within the pod.

Is that currently not working? Perhaps it could be something to do with [HBAC rules](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler/tree/master/examples).

**Comment by mattjmcnaughton** [comment]
One other note - you could also try asking this question on the cluster-proportional-autoscaler [issues](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler) page. They might be able to provide additional help and insight :)

**Comment by ivankennethwang** [comment]
Got it thanks @mattjmcnaughton
