### ISSUE TITLE
Implement GetZoneByProviderID and GetZoneByNodeName for all cloud providers

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#50926]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

As part of the initiative for external cloud providers (https://github.com/kubernetes/kubernetes/issues/48690), we added GetZoneByProviderID and GetZoneByNodeName. See https://github.com/kubernetes/kubernetes/pull/50858 for more details. The previous PR did not actually implement those methods for existing cloud providers in `pkg/cloudprovider/providers`. These methods should be implemented by all cloud providers in the future. 

cc @wlan0

**Comment by andrewsykim** [comment]
Could someone add the help-wanted label for this issue please?

**Comment by wlan0** [comment]
cc @thockin @luxas 

We need the following label -

help-wanted

and add it to the 1.8(?) milestone

cc @luomiao @FengyunPan @fgimenez @realfake @cheftako to implement it for their respective clouds.

**Comment by yastij** [comment]
I'll try to have a look by the end of the week.

**Comment by FengyunPan** [comment]
@wlan0 Ok, I will take care of the Rackspace and OpenStack.

**Comment by luxas** [comment]
Thank you @FengyunPan !

**Comment by yastij** [comment]
@luxas - Is there any listing, to see the already implemented cloud provider ?

**Comment by luxas** [comment]
@yastij No providers have this yet.
Current PRs:
 - Openstack: https://github.com/kubernetes/kubernetes/pull/51317
 - Rackspace: https://github.com/kubernetes/kubernetes/pull/51318

Please contribute if you have something ready @yastij :)

**Comment by yastij** [comment]
Sorry for the delay guys :)

**Comment by FengyunPan** [comment]
@yastij Have you implemented them for gce?

**Comment by yastij** [comment]
Intending to work on it tonight, but if you have something I can work on azure

**Comment by FengyunPan** [comment]
Yes, I have prepared for GCE.

**Comment by yastij** [comment]
Azure added.

**Comment by luxas** [comment]
Cool, than you all!
Any other providers we should implement this for in time for v1.8?

**Comment by yastij** [comment]
I'll take a look tomorrow to see if there's something left

**Comment by luxas** [comment]
Let's see which providers are left before closing this...

**Comment by yastij** [comment]
@luxas - I guess this one should be closed ?

**Comment by luxas** [comment]
@yastij If you say that all providers have this now, thanks, great!
