### ISSUE TITLE
Decide if we should write a proposal for sharing / exporting of configmaps between namespaces.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#50922]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened ?**

It would be nice to share configmaps between namespaces, 

- this is a good workaround to a recent  conversation on the kubernetes mailing list around "how many apps per cluster", as its another tool in the toolbox.
- example 1: a way to implement a 'poor man's multitenancy'.
- example 2: sharing paves the way for automated inheritance of configs, which again is valuable, for example when you want a user to have a bootstrapped version of an app so they can quickly use it, but you want to allow them to plug in new container implementations .
- example 3: standardize the way external services or data-center specific attributes are set up in a cluster where shared, highly dynamic config is required for security or reasons.

**Comment by jayunit100** [comment]
Not sure where this is most relevant, couldn't find sig-ux group, so ... cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/kubectl-maintainers

**Comment by jvanbruegge** [comment]
/reopen
I just came across the need for this: an easy way to share custom TLS certificates with the whole cluster. The configmap is created once on cluster initialization and new namespaces could directly access them. At the moment I have to invoke a bash script for every new namespace that copies the config map. I would prefer to be able to have all configuration in YAML.

The easiest way to do this would be to add a new field in the metadata of configmaps, `shareWithAll`, that can either be `false` (default; current behavior) or `true` (allows other namespaces to refer to this configmap)

**Comment by TomaszKlosinski** [comment]
Any news on this? Copying over configmaps from namespace to namespace seems, to say the least, impractical solution.
