### ISSUE TITLE
'kubectl get pvc' missing PV name label.

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#50937]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug

/kind bug

**What happened**: `kubectl get pvc` returns the following:
```
NAME       STATUS    CAPACITY    ACCESS MODES   STORAGECLASS   AGE
myclaim    Bound     pv-gcepd2   5Gi            ROX            slow      35m
myclaim2   Bound     pv-gcepd    5Gi            ROX            slow      25m
```
VOLUME label is missing.

**What you expected to happen**:
```
NAME       STATUS    VOLUME      CAPACITY       ACCESS MODES   STORAGECLASS   AGE
myclaim    Bound     pv-gcepd2   5Gi            ROX            slow           35m
myclaim2   Bound     pv-gcepd    5Gi            ROX            slow           25m
```
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.3928+7116f522eeee5c-dirty", GitCommit:"7116f522eeee5cf866c9b60de32bcecc6e74763b", GitTreeState:"dirty", BuildDate:"2017-08-18T01:09:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

/sig cli

**Comment by zjj2wry** [comment]
@verult thank for you report this
