### ISSUE TITLE
No-op endpoint updates clog up endpoint controller's queue

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#50936]
/kind bug

**What happened**:

On a large cluster with enough pods, endpoints take as long as 10 minutes to show up after their associated pods and service are created. We believe that this is because every pod change results in an update of the addresses within the endpoint since they refer to a pod via a `TargetRef` whose `ResourceVersion` changes every time a pod change is observed. All these non-update updates eventually overwhelm the endpoint controller's queue rate limit and the queue starts to grow.  While an increase in the queue's rate limit can alleviate the problem, an admin can keep a much lower limit if the non-update updates are dropped rather than processed.

**What you expected to happen**:

When a pod related to an endpoint is updated, I would expect the endpoint to update only if there is a change in the pod that relates to the endpoint, such as a change in the pod's IP address.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod and associated service:
```
kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/networking/list_for_pods.json
```
2. Watch the endpoint for changes:
```
kubectl get endpoint -o yaml --watch test-service
```
3. Leave the watch running, and in another session, edit a pod to add a label:
```
kubectl get pods
kubectl edit pod <podname>
```
Then add another label on the line after the `name:` label, such as `foo: bar`
4. Notice that the watched endpoint changed despite there not being any meaningful change to the fields the endpoint cares about.

**Anything else we need to know?**:

The PR #50934 addresses this issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2169+683f09c65e5a79", GitCommit:"683f09c65e5a7954a272e6640876b357bbdaf2e4", GitTreeState:"clean", BuildDate:"2017-08-18T21:54:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.2167+683f09c65e5a79", GitCommit:"683f09c65e5a7954a272e6640876b357bbdaf2e4", GitTreeState:"clean", BuildDate:"2017-08-18T22:57:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thockin** [comment]
@mikedanese what ever happened with the effort to move leases off of Endpoints?
