### ISSUE TITLE
Use util function to replace self-contained function

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#50952]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind feature

**What happened**:
In some files, i found that there are many self-contained function, whose feature is as same as some util function. Obviously, they are redundant. 

**What you expected to happen**:
Use util function to replace self-contained function

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
@zhangxiaoyu-zidif similar comment to https://github.com/kubernetes/kubernetes/issues/50951#issuecomment-323523437. Can you edit the description in #47506 to say `fixes #50952` instead of `fixes ##50952`? Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
Thanks. Done.
