### ISSUE TITLE
Reduce redundant commet of code and Fix go style comment

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#50951]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
 /kind feature

**What happened**:
There are some unused commet, these are meaningless.
And some function‘s comment does not follow go style.

**What you expected to happen**:
We should delete them all.
and fix comment following golang style  
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
@zhangxiaoyu-zidif can you edit the PR description in #50213 to say `fixes #50951` instead of `fixes ##50951`? That would automatically close this issue once the PR is merged. :)

**Comment by zhangxiaoyu-zidif** [comment]
@nikhita  OK, no problem~:)
