### ISSUE TITLE
Add test for kubeadm config defaults

### ISSUE THREAD

**Issue by leblancd** [kubernetes/kubernetes#50959]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
Upon code review, I don't see any unit test for checking kubeadm MasterConfiguration defaults.

**What you expected to happen**:
There should be a unit test for checking kubeadm MasterConfiguration defaults.

**How to reproduce it (as minimally and precisely as possible)**:
Code inspection.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Latest master
- Cloud provider or hardware configuration**: CentOS 7 VirtualBox VMs on a Ubuntu 16.04.1 host
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1 host, CentOS 6 guests
- Kernel (e.g. `uname -a`): 4.4.0-78-generic #99-Ubuntu x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by luxas** [comment]
@leblancd Thanks for this issue.
Do you mind reopening this in https://github.com/kubernetes/kubeadm/issues instead?
We're trying to consolidate all issues there...
Thanks!
