### ISSUE TITLE
Fix url redirection

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#50954]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind bug

**What happened**:
Some url in markdown file is invalid
or need to be redirected to dest. url one time or more.

**What you expected to happen**:
So cleaning them up is necessary. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
This can be closed now. It is fixed in https://github.com/kubernetes/kubernetes/pull/50882.
