### ISSUE TITLE
Allow setting some "safe" per-container sysctls

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#5095]
A GCE ContainerVM used on IRC asked how to set SOMAXCONN within his container.
That is not possible in an unprivileged container because `/proc/sys` is not writeable.

If the user tries to set `containerManifest.containers[i].privileged=true` then a validation error occurs.
I can't tell if that validation error is occuring only at the kubelet or also at some layer of the containerVM system.  At any rate, the user would at least need to set `--allow_privileged=true` on the kubelet.  Not sure if that is possible with ContainerVM.

For kubernetes, we would not want the user to have to set a blanket allow_privileged on kubelet and apiserver just to tune this parameter.

**Comment by bgrant0607** [comment]
This (and similar) is a system-wide setting, no? A quick search shows that several applications (e.g., riak, php, mysql) advise tuning /proc/sys parameters. We'll likely need a model for setting these parameters based on pod/container requirements (e.g., black-box configuration vs. semantic awareness of the knobs), and will need to decide what to do when different applications request different values (e.g., scheduling exclusion vs. max. of all requirements).

**Comment by thockin** [comment]
It's not clear whether this one in particular is inherited from the system
or re-initialized for each netns

**Comment by erictune** [comment]
The reporter made it sound like it was a per-interface setting.

**Comment by erictune** [comment]
I have it on good authority that the sysctls in `netns_core_table` in [`net/core/sysctl_net_core.c`](http://lxr.free-electrons.com/source/net/core/sysctl_net_core.c?v=3.10) are namespaced, and the others, which are in `net_core_table`, are not.  As of 3.10, only `somaxconn` is per-netns.

**Comment by edevil** [comment]
Any progress on this?

**Comment by janosi** [comment]
Docker 1.12 seems to receive support for per-container sysctls. 
https://github.com/docker/docker/pull/19265
Could it be the way for Kubernetes, i.e.managing sysctls in containers through the Docker API?

**Comment by thockin** [comment]
@dchen1107 @vishh would be nice to queue this up, even though we'll
probably NOT get 1.12 qualified for our 1.3

**Comment by vishh** [comment]
@thockin @erictune Given that https://github.com/docker/docker/pull/192 is done, how do you think sysctl options will be represented in our API?

**Comment by thockin** [comment]
I expect it would be similar in structure.  Either a per-pod or
per-container (or both) map of string-string ?  Can you think of any reason
not to make it simple?  I don't think we can/should abstract it much
further.  Maybe we don't want to spell it "sysctl" - maybe "osParams" or
something plausibly generic?  I didn't look at Docker's API, but presumably
Windows and Mac will have to handle this...

**Comment by janosi** [comment]
@vishh I do not know whether it matters or not, but you referenced wrong Docker github issue.

On pod vs. container level: one would think, it depends on whether a given parameter is in a pod level namespace or not, and consequently maybe both is needed (pod and container). According to the Docker issue above, the following sysctls are supported currently:
IPC namespace: kernel.msgmax, kernel.msgmnb, kernel.msgmni, kernel.sem, kernel.shmall, kernel.shmmax, kernel.shmmni, kernel.shm_rmid_forced, fs.mqueue.*
Network namespace : net.*

As I understand, both IPC and Network namespaces are on pod level. So, for the time being, if one considers only the current set of sysctls, a pod level option would be fine. But of course, it is your decision if you want to prepare for a future option in a per-container namespace.

One more thing: Docker does not allow the definition of these sysctls if the host namespace is used for the relevant parameter. I wonder if you would like to implement similar logic based on the other parameters of the pod, or you just let Docker to do its job.

**Comment by est** [comment]
looks like it's already in safe list? 

https://github.com/kubernetes/kubernetes/issues/54132
