### ISSUE TITLE
container that is supposed to restart every 60s ends up in CrashLoopBackOff

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#50962]
/kind bug

we have an app that is a simple shell script, executes a command, sleeps for 60 seconds, and then exit 0's, the idea is that Kubernetes restarts the container, and the cycle starts over again, giving us a task that runs continuously every 60 seconds.

This works, and the first couple of restarts (I haven't counted them yet) it works as expected, but eventually, the pod ends up in a weird `CrashLoopBackOff` state that I can't explain.

Here are the latest events of the pod in question:

```
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----							-------------		--------	------		-------
  6h		3m		72	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Created		Created container
  6h		3m		72	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Started		Started container
  6h		3m		71	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Pulled		Container image "eu.gcr.io/bnl-blendle/kubernetes-node-tainter:6abaa0a" already present on machine
  6h		7s		1542	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Warning		BackOff		Back-off restarting failed container
  6h		7s		1542	kubelet, gke-blendle-2-preemptible-762d699b-pfk1				Warning		FailedSync	Error syncing pod
```

And some details on the pod:

```
Containers:
  kubernetes-node-tainter-app:
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Sat, 19 Aug 2017 17:11:27 +0200
      Finished:		Sat, 19 Aug 2017 17:12:31 +0200
    Ready:		False
    Restart Count:	71
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
```

I went into the machine and used `journalctl -u docker` to see if anything weird was going on there, but I saw nothing of consequence (besides some repeating message about swap being disabled on the OS, which I guess is as expected).

Then, I restarted the Docker daemon using `systemctl restart docker`, this made the pod work again, here are the events after this command:

```
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath		Type		Reason		Message
  ---------	--------	-----	----							-------------		--------	------		-------
  1m		1m		1	kubelet, gke-blendle-2-preemptible-762d699b-pfk1				Normal		SandboxChanged	Pod sandbox changed, it will be killed and re-created.
  7h		35s		1602	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Warning		BackOff		Back-off restarting failed container
  7h		35s		1602	kubelet, gke-blendle-2-preemptible-762d699b-pfk1				Warning		FailedSync	Error syncing pod
  7h		20s		75	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Created		Created container
  7h		20s		75	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Started		Started container
  7h		20s		74	kubelet, gke-blendle-2-preemptible-762d699b-pfk1	spec.containers{kubernetes-node-tainter-app}	Normal		Pulled		Container image "eu.gcr.io/bnl-blendle/kubernetes-node-tainter:6abaa0a" already present on machine
```

Unfortunately, after a short while, the error starts again.

However, as I'm writing this, I'm wondering, is this maybe as-intended, and the 60 seconds the script runs is too short and thus Kubernetes marks it as a failing container, because it keeps restarting every 60 seconds (even though it has a clean exit)?

If that's the case, then please close this, as it's not a bug, but I'm still curious what the minimum time is a container needs to run for it not to be considered a "crash". (also, the event message itself isn't really clear if this is the case)

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-01T05:44:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Container-Optimized OS
- Kernel (e.g. `uname -a`): Linux 4.4.52+ #1 SMP Thu Jul 13 11:47:20 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux

**Comment by jianzhangbjz** [comment]
/area/docker

**Comment by jianzhangbjz** [comment]
@JeanMertz No, the error was `Container Terminated and Kubelet is backing off the restart`. I think the container terminated after sleep 60s, but the time of restarting is more than 60s. Because the Kubelet restart the container with an exponential back-off delay (10s, 20s, 40s …). Details as [Restart policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) .

**Comment by cblecker** [comment]
This is intentional, as @jianzhangbjz noted. I think a [cron job](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) may be better suited for you.

---
/kind support
/close

**Comment by JeanMertz** [comment]
Thank you two for your response. We solved it by putting the whole script in a simple loop, so the container never stops. CronJobs would be wonderful, but are not available to us on GKE, unfortunately.
