### ISSUE TITLE
Bazel fails to build a project that imports apimachinery 1.7

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#50975]
**What happened**:
I'm trying to use Bazel to build a project that depends on client-go 4.0 (k8s 1.7) which transitively depends on apimachinery of a corresponding version. This is what I'm getting:

```console
ERROR: /gopath/src/github.com/atlassian/smith/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:25:1: no such package 'hack/boilerplate': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
ERROR: /gopath/src/github.com/atlassian/smith/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:25:1: no such package 'cmd/libs/go2idl/set-gen': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
```
Offending rule is `go_genrule` (was introduced in #38990): https://github.com/kubernetes/apimachinery/blob/abe34e4f5b4413c282a83011892cbeea5b32223b/pkg/util/sets/BUILD#L25 (version that I use).

If I take this BUILD file from master ([there are some changes](https://github.com/kubernetes/kubernetes/blob/e633a1604f00908a1dcc898b206c3404db4d82ed/staging/src/k8s.io/apimachinery/pkg/util/sets/BUILD#L22)) then I'm getting this:
```console
ERROR: /gopath/src/github.com/atlassian/smith/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:22:1: no such package 'hack/boilerplate': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
```
Also I suspect it will not find [`//vendor/k8s.io/code-generator/cmd/set-gen`](https://github.com/kubernetes/kubernetes/blob/e633a1604f00908a1dcc898b206c3404db4d82ed/staging/src/k8s.io/apimachinery/pkg/util/sets/BUILD#L46) which is referenced there too. 

**Anything else we need to know?**:
Looks like apimachinery repository is not being synced with k8s/kubernetes - it is 22 days old while there is a 3 days old commit to the BUILD file mentioned above. /cc @caesarxuchao 

Perhaps there should be a testing project that exercises client-go/apimachinery/etc as dependencies if used via Bazel. It all works fine if used directly.

Similar to #42134.

```
Build label: 0.5.3-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Aug 6 12:54:10 2017 (1502024050)
Build timestamp: 1502024050
Build timestamp as int: 1502024050
```
rules_go: 0.5.3

Also Bazel also couldn't find `@io_kubernetes_build` (but at least this is fixable):
```console
error loading package 'vendor/k8s.io/apimachinery/pkg/util/sets': Extension file not found. Unable to load package for '@io_kubernetes_build//defs:go.bzl': The repository could not be resolved and referenced by '//vendor/k8s.io/client-go/rest:go_default_library'.
```

Once I comment out `load("@io_kubernetes_build//defs:go.bzl", "go_genrule")` and `go_genrule` in this BUILD file my build works fine. And it looks like there are no other places in whole apimachinery, and client-go where this module is required and this rule is used.

/kind bug
/area build-release
/sig release

**Comment by ash2k** [comment]
```
Build label: 0.5.3-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Aug 6 12:54:10 2017 (1502024050)
Build timestamp: 1502024050
Build timestamp as int: 1502024050
```
rules_go: 0.5.3

**Comment by ash2k** [comment]
Bazel also couldn't find `@io_kubernetes_build` (but at least this is fixable):
```console
error loading package 'vendor/k8s.io/apimachinery/pkg/util/sets': Extension file not found. Unable to load package for '@io_kubernetes_build//defs:go.bzl': The repository could not be resolved and referenced by '//vendor/k8s.io/client-go/rest:go_default_library'.
```

**Comment by spxtr** [comment]
cc @ixdy

**Comment by ixdy** [comment]
`@io_kubernetes_build` is provided by https://github.com/kubernetes/repo-infra (and is possibly poorly named). Bazel doesn't do recursive imports right now, so you'd need to explicitly add it to your `WORKSPACE`, though we might be able to write a rule that does that or something equivalent.

I'm not really familiar with how the apimachinery staging stuff works, so I'm not entirely sure what needs to be fixed here.

It is a bit weird that `staging/src/k8s.io/apimachinery/pkg/util/sets/BUILD` depends on `//hack/boilerplate`.  We should probably not allow that.

**Comment by ixdy** [comment]
nothing depends on the `go_genrule` right now because all of the generated files are also checked in. we'd like to eventually remove those generated files from the repo, which would make the genrule necessary, but currently the genrule only works in the main kubernetes repo, since otherwise `hack/boilerplate` doesn't exist.

**Comment by ash2k** [comment]
I've tried adding `@io_kubernetes_build` to my `WORKSPACE` file. It gets me further (it can resolve the rule) but the rule, as you can see, references a missing thing. So adding `@io_kubernetes_build` doesn't resolve this issue.

`staging/src/k8s.io/apimachinery` is published into a separate repo for external consumption https://github.com/kubernetes/apimachinery and in fact kubernetes consumes it via vendor directory (which contains a symlink to `staging/...`) as if it is an external dependency. So I guess the  script that publishes updates to the external repo should be also copying `hack` directory? I don't know what is the best way to resolve this.

@caesarxuchao

**Comment by ixdy** [comment]
we need to break the dependency from `//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen` to `//hack/boilerplate` - vendored code shouldn't be depending on the kubernetes repo.

**Comment by rickypai** [comment]
this ends up being quite a rabbit hole, even after my hacky attempt to copy https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate into https://github.com/kubernetes/apimachinery to at least resolve the missing `//hack/boilerplate` problem.

1. many of the dependencies referenced in the `go_genrule` aren't present

2. the build rule specifies apimachinery itself as a vendored dependency: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/sets/BUILD#L37

at this point, I'm limited by my limited understanding of the bazel build tooling in k8s :/

**Comment by AmandaCameron** [comment]
I'm not that clear on the repo model of the project overall, but does it make really sense to be including the BUILD files from the repo in the mirror at all? This is blocking us from being able to update to kube 1.8 because we can't update the client-go fr some of our services, which we build using bazel ourselves..

**Comment by diegs** [comment]
I've had pretty good success with just deleting all the BUILD{.bazel} files and regenerating them using gazelle. We're using a `vendor/` directory though (vendor = external for gazelle), not sure if it would work if you're using external deps in your WORKSPACE file.

**Comment by kadamvandita** [comment]
any solution to  error loading package 'vendor/k8s.io/apimachinery/pkg/util/sets': Extension file not found. Unable to load package for '@io_kubernetes_build//defs:go.bzl': The repository could not be resolved. error?

**Comment by scele** [comment]
FWIW, I ended up [forking](https://github.com/scele/apimachinery/commit/dde19de1310a58d5fe27e0a24c804ffbe1502ca1) the apimachinery repo to work around this issue in order to use client-go in my project that uses Bazel.

@mikedanese , @ixdy , it seems that the outputs of the problematic pkg/util/sets:set-gen rule go to bazel-genfiles and are not referenced by any other bazel rule. Am I right? Instead, the generated files are checked into the repository. Is the intended bazel workflow to invoke "bazel build //apimachinery/pkg/util/sets:set-gen" explicitly, and then manually copy the generated files from bazel-genfiles to apimachinery/pkg/util/sets? If so, could we just remove the bazel rule and require that users use "go generate" instead when the files need to be regenerated?

**Comment by kadamvandita** [comment]
hi 

which branch u cloned of apimachinery and which folder?

**Comment by ash2k** [comment]
This is a dupe of #37598.
