### ISSUE TITLE
Timeouts when draining a node while using external-traffic: OnlyLocal annotation on loadbalancer

### ISSUE THREAD

**Issue by simonklb** [kubernetes/kubernetes#50977]
/kind bug

**What happened**:

While trying to achieve zero downtime the current practice seem to be adding a preStop sleep hook (see https://github.com/kubernetes/ingress/issues/322 & https://github.com/kubernetes/kubernetes/issues/43576) to prevent pods being terminated before their endpoints have been removed. This works well except for when it's combined with a loadbalancer with the `service.beta.kubernetes.io/external-traffic: OnlyLocal` annotation.

**What you expected to happen**:

Doing a rolling update of the ingress or draining a node should not cause timeouts.

**How to reproduce it (as minimally and precisely as possible)**:

A minimal setup would be something like an ingress-controller and a backend deployment, both on at least 2 replicas and a preStop hook executing a small sleep. PodDisruptionBudgets with `minAvailable: 1`. And finally a loadbalancer service.

Execute some form of stress test while you drain a node which hosts an ingress-controller and there shouldn't be any disruptions.

Now add the `OnlyLocal` annotation and repeat the test. Timeouts occur.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.4
- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release): CoreOS 1465.6.0
- Kernel (e.g. `uname -a`): 4.12.7-coreos

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by kdima** [comment]
We are seeing the same issue. Based on our debugging it looks like:
1) old pod gets Delete request
2) goes into Terminating state and process receives Term signal. We catch TERM in our application and start reporting Not Healthy on the configured healthcheck endpoint but the application is still capable of serving traffic.
3) Happens around the same time as 2 kube-proxy removes all the routing from the node. Now if the external load balancer sends traffic to this node it will be silently dropped.
4) Some time later external load balancer realises that node is no longer healthy and removes it from circulation.

A nice fix for us would be an ability to configure the time between TERM and kube-proxy removing routing rules. Then after TERM LB will have enough time to realise that node is not healthy before kube-proxy starts blackholing traffic.
@thockin I saw you were on a number of discussions around non disruptive rollouts. I was wondering what's your opinion about this.

**Comment by edevil** [comment]
Any news on this?

**Comment by MrHohn** [comment]
Still a valid issue.
/remove-lifecycle rotten

**Comment by mattes** [comment]
This behavior is also affecting NodePort Services. 

> As a short term fix, I have another proposal: For the OnlyLocal feature, on the node that has no backend pod running on, instead of dropping service traffic, we could fall back to cluster-wide routing so that during rolling update or pod rescheduling, traffic forwarded to nodes that has no backend can still reach available backend on another node. One tradeoff is these traffic will not have source IP preserved, which I think is better than timeouts. WDYT?

@MrHohn, it's not perfect but sounds like a good short term fix to me. We don't have use cases where we look at the source IP, but I can't speak for others.

**Comment by zackb** [comment]
I am facing this same issue. Has anyone had any luck?

I've tried failing health checks and preStop lifecycle hooks, but traffic is still routed to the terminated pods briefly (by cloud LB) during scale-in or rolling updates.

**Comment by dpratt** [comment]
I suspect this is an *extremely* common usecase - we can't switch to using a local externalTrafficPolicy until this gets addressed. Without a fix or workaround for this issue, any recreation of a backend pod causes between 1-5 minutes of timeouts and outages for our external facing applications and APIs, which is unacceptable.

I like the option of having a mode in which kube-proxy doesn't blackhole traffic on nodes that aren't running a pod for the service, but rather routes them with the default logic while also failing the nodePortHealthCheck. Of course, nodes that do have pods running on them would then transparently send traffic directly to the pod. This does imply that there's a small window of time in which the source IP will be incorrect, but in my perspective that's a step up from having a full-on outage for the service.
