### ISSUE TITLE
Remove --cloud-provider=auto-detect

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#50986]
/kind feature

**What happened**:
Continuing the discussion from https://github.com/kubernetes/kubernetes/pull/50730, we should deprecate (or remove since its alpha) the option to set `--cloud-provider=auto-detect`. See comment https://github.com/kubernetes/kubernetes/pull/50730#issuecomment-323531048 and https://github.com/kubernetes/kubernetes/pull/50730#issuecomment-323531248 for more details. 

related issues: https://github.com/kubernetes/kubernetes/issues/48690
related kubernetes-dev thread: https://groups.google.com/forum/#!topic/kubernetes-dev/UAxwa2inbTA

EDIT:

Deprecation plan:
- [x] v1.8 - deprecate auto-detect cloud provider feature in kubelet
- [ ] v1.9 - set no cloud provider as the default in kubelet but still allow opt in for auto-detect
- [ ] v1.10 - completely remove the option to use `auto-detect`

**Comment by wlan0** [comment]
cc @thockin @luxas  - Wanted to ask you if you had any thoughts for/against this issue?

**Comment by andrewsykim** [comment]
/assign andrewsykim 

As discussed in our meeting I'll be following up with sig-node to see if we can deprecate this as it's going against what we want for external cloud providers

**Comment by luxas** [comment]
FYI @kubernetes/sig-node-feature-requests @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by andrewsykim** [comment]
Would have been nice to keep this issue open to track progress in the next releases

**Comment by luxas** [comment]
Indeed, should be kept open.
Next task is now targeting v1.9

**Comment by andrewsykim** [comment]
Thanks @luxas I edited the issue description to include the deprecation plan going forward. Open to changes on the deprecation plan if we think it's too aggressive.

**Comment by luxas** [comment]
Great, I think this is a good timeline. We need to make sure we communicate it very well though
@andrewsykim can you add this to the draft release notes in kubernetes/features please?

**Comment by andrewsykim** [comment]
Looks like you beat me to it 😛, gave it a review.

**Comment by luxas** [comment]
hehe, yes, added it at the same time as everything else ;)

**Comment by luxas** [comment]
@andrewsykim Can you create a PR for this soon to get this early into v1.9 please?

**Comment by dims** [comment]
@andrewsykim i took the liberty to move this along (filed 53573). Hope that's ok.

**Comment by andrewsykim** [comment]
Thanks @dims, appreciate it. I think there were some discussions in the mailing list thread about v1.9 being too soon. I think it largely depends on how many users actually take advantage of the auto-detect feature. It's not many from what I've seen but we should follow up and be sure.

**Comment by luxas** [comment]
@andrewsykim Any recent discussion about that? I haven't seen any activity recently but I might just be subject to email overflow. I hope we can get this into v1.9
cc @thockin

**Comment by dchen1107** [comment]
I didn't follow any discussion related to this topic, but thought this is right move to decouple cloud_provider components from the core system. If I remembered correctly, only cloud_providers for GCE, AWS and Azura depend on the feature, which can be easily override. 

Any concerns for v1.9?

**Comment by dims** [comment]
@dchen1107 yep, GCE/AWS/Azure - https://github.com/google/cadvisor/blob/a9b1ab1dd8d811d419487a631c3361df582346d2/utils/cloudinfo/cloudinfo.go#L58

**Comment by luxas** [comment]
@dchen1107 Please look at https://github.com/kubernetes/kubernetes/pull/53573 and give your LGTM

**Comment by dchen1107** [comment]
Done. Just better document in 1.9 release notes. LGTM

**Comment by luxas** [comment]
Thank you!

**Comment by luxas** [comment]
Reopening for the removal of the option in v1.10

**Comment by dims** [comment]
@enisoc please move this to 1.10 milestone
