### ISSUE TITLE
kubelet panic: err from UnsecuredDependencies not checked

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/kubernetes#50981]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Testing bringing up k8s cluster using kubeadm from latest k8s code from master branch.
kubelet is not coming up and below is the errors from syslog:
```
Aug 20 17:32:32 ubuntu startupscript: + systemctl start kubelet
Aug 20 17:32:32 ubuntu systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 20 17:32:33 ubuntu kubelet[5522]: 2017/08/20 17:32:33 proto: duplicate proto type registered: google.protobuf.Any
Aug 20 17:32:33 ubuntu kubelet[5522]: 2017/08/20 17:32:33 proto: duplicate proto type registered: google.protobuf.Duration
Aug 20 17:32:33 ubuntu kubelet[5522]: 2017/08/20 17:32:33 proto: duplicate proto type registered: google.protobuf.Timestamp
Aug 20 17:32:33 ubuntu kubelet[5522]: I0820 17:32:33.336515    5522 feature_gate.go:150] feature gates: map[]
Aug 20 17:32:34 ubuntu kubelet[5522]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 20 17:32:34 ubuntu kubelet[5522]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b9a0e5]
Aug 20 17:32:34 ubuntu kubelet[5522]: goroutine 1 [running]:
Aug 20 17:32:34 ubuntu kubelet[5522]: main.main()
Aug 20 17:32:34 ubuntu kubelet[5522]: #011cmd/kubelet/kubelet.go:101 +0x3e5
Aug 20 17:32:34 ubuntu systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 20 17:32:34 ubuntu systemd[1]: kubelet.service: Unit entered failed state.
Aug 20 17:32:34 ubuntu systemd[1]: kubelet.service: Failed with result 'exit-code'.
```
upon looking at the code from where the error is happening, it is evident that the err checking is missing.
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/kubelet.go#L98

**What you expected to happen**: deployment to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Use the latest code from k8s and build a k8s release and bring up cluster using kubeadm

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release): 16.04 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux e2e-21cc215cd6-master 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

/sig node
/cc @pipejakob @luxas

**Comment by luxas** [comment]
@kubernetes/sig-node-bugs PTAL
