### ISSUE TITLE
[CCM] Cloud node controller will not remove nodes that no longer exists for cloud providers that require ProviderID

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#50985]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/kind bug

**What happened**: 

@wlan0 mentioned [here](https://github.com/kubernetes/kubernetes/pull/50730#issuecomment-323485938) that:
> Secondly, there are some clouds whose providerID cannot be inferred from a remote location even within the cloud (e.g. openstack). This is why we wanted to have the ability to set a unique id while starting the kubelet.

Currently, [`MonitorNode()`](https://github.com/kubernetes/kubernetes/blob/02b520f0a40be2056d91fc0661c2b4fdb2694c30/pkg/controller/cloud/nodecontroller.go#L240) in the node controller only checks with the CCM if a node still exists by calling `ExternalID(nodeName)`. `ExternalID` is supposed to return the provider id of a node by its node name which is not supported on every cloud. This means that any clouds who cannot infer the provider id by the node name from a remote location will never remove nodes that no longer exist. 

**What you expected to happen**:

I'd expect the cloud node controller to ask the CCM if the instance still exists by node name and provider id just like the other methods in the cloud provider interface. 

**Other**

It seems weird to me that we check if a node exists by calling `ExternalID(nodeName)`. I feel we should add two more methods to the [`Instances`](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L116) interface for this purpose like:
* `Exists(nodeName types.NodeName) (bool, error)`
* `ExistsByProviderID(providerID string) (bool, error)`

I see in some places that `ExternalID` has deprecated; however, I can't find anywhere that says what it was deprecated in favor of. Sorry if this is a duplicate of an existing issue/proposal. 

cc @wlan0 @andrewsykim @luxas 

related: #48690

**Comment by FengyunPan** [comment]
>add two more methods to the Instances interface for this purpose like:
    Exists(nodeName types.NodeName) (bool, error)
    ExistsByProviderID(providerID string) (bool, error)

@jhorwit2 I agree, Currently VSphere calls Exists() to check whether node exists. But other cloud providers call ExternalID(nodeName) which is deprecated.

**Comment by wlan0** [comment]
@jhorwit2  Thanks for finding this bug and filing this issue :) I'll be happy to review it if you make a PR

**Comment by jhorwit2** [comment]
@wlan0 i'll start work on the PR. 👍

**Comment by luxas** [comment]
cc @thockin ^
