### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce check always failed

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#50999]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind flake

**What happened**:
check failed

**What you expected to happen**:
check passed

**Anything else we need to know?**:
check failed in many PRs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50005/pull-kubernetes-kubemark-e2e-gce/46742/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47896/pull-kubernetes-kubemark-e2e-gce/46705/

/cc @k8s-mirror-testing-bugs

**Comment by adelton** [comment]
I seem to be hitting this issue in https://github.com/kubernetes/kubernetes/pull/50596 as well.

**Comment by NickrenREN** [comment]
Seem [this](https://github.com/kubernetes/kubernetes/pull/51008) can resolve it
