### ISSUE TITLE
Controller manager fails to acquire lock in HA environment

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#51000]
/kind bug

**What happened**:
We are running an HA environment with 3 nodes (3 apiserver + 3 controller manager + 3 scheduler). We attach the Virtual  IP on one of the nodes using ucarp. After restart node with vip several times. All the controllers in the 3 nodes cannot get the lock and perform as the leader. All controller shows the same log as below

```
I0821 05:35:03.122765       1 leaderelection.go:179] attempting to acquire leader lease...
E0821 05:35:19.513926       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
E0821 05:35:23.467645       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
```

**What you expected to happen**:
One of the controller should be elected as leader.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start a three-master cluster
2. restart one node and wait until apiserver, controller and scheduler are up.
3. go back to step 2 on another node 

after performing step2-3 several time, we found all controllers fail to get lock.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-45-generic
- Install tools:
- Others:

**Comment by hchenxa** [comment]
seems the AcquireTime was too old than RenewTime in leaderElectionRecord:
```
I0821 09:12:53.340913       6 leaderelection.go:180] failed to acquire lease kube-system/kube-controller-manager
E0821 09:12:56.568254       6 leaderelection.go:255]leaderElectionRecord was: {hchenk8s2.eng.platformlab.ibm.com 15 2017-08-21 06:08:55 +0000 UTC 2017-08-21 09:12:56.565619676 +0000 UTC 1}
E0821 09:12:56.569565       6 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
I0821 09:12:56.569582       6 leaderelection.go:180] failed to acquire lease kube-system/kube-controller-manager
```

**Comment by tatsuhiro-t** [comment]
I get the same error "E0908 04:47:47.692141       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again".

But my cluster has a single master.  In some point in the past, I created new master, and stopped old master if that matters.  I'm using k8s v1.7.4.

**Comment by tatsuhiro-t** [comment]
The log says that controller manager of new master node emitted this log from the beginning, and never recover.

```
2017-09-05 07:52:53.558357 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-05 07:52:53.558719 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-05 07:52:53.558786 I | proto: duplicate proto type registered: google.protobuf.Timestamp
I0905 07:52:53.623426       1 controllermanager.go:107] Version: v1.7.4
I0905 07:52:53.624280       1 leaderelection.go:179] attempting to acquire leader lease...
E0905 07:53:53.626016       1 leaderelection.go:229] error retrieving resource lock kube-system/kube-controller-manager: the server cannot complete the requested operation at this time, try again later (get endpoints kube-controller-manager)
E0905 07:54:01.015818       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
E0905 07:54:03.943472       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
E0905 07:54:06.434533       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
E0905 07:54:10.373613       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
E0905 07:54:13.448215       1 leaderelection.go:263] Failed to update lock: Operation cannot be fulfilled on endpoints "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
...
```

As I write in the previous comment, at this point, I had another old master active, so temporarily my cluster was HA enabled.   I'm not sure why kube controller manager has not recovered from this state after old master stopped.  Does it forget to get a fresh Endpoints from apiserver?  Or, watch does not work, and controller local cache is left stale?

**Comment by tatsuhiro-t** [comment]
From the apiserver log, controller manager gets Endpoint from apiserver successfully, but its PUT operation fails:

```
Sep 08 05:42:24 master docker[6661]: I0908 05:42:24.550229       1 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (2.149749ms) 200 [[hyperkube/v1.7.4 (linux/amd64) kubernetes/793658f/leader-election] 127.0.0.1:42258]
Sep 08 05:42:24 master docker[6661]: I0908 05:42:24.552248       1 wrap.go:42] PUT /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (1.528709ms) 409 [[hyperkube/v1.7.4 (linux/amd64) kubernetes/793658f/leader-election] 127.0.0.1:42258]
```

Interestingly, the Endpoints annotation suggests that the current master successfully acquired lock.
Digging deeper, controller manager pod restarted once.  The log of initial run is lost, but from the timestamp, it looks like the controller manager acquired the log in its initial run, and then restarted for some reason.

Kube scheduler also shows the same error message: "Failed to update lock".

**Comment by catlittlechen** [comment]
I am a newer. I have the same question. All my master nodes have the same hostname, and the server use this hostname to choose leader. As a result, all my master nodes has become a leader when they up.
So I changed the hostname of them, and fix it.....
