### ISSUE TITLE
Confused code and comment in serviceController

### ISSUE THREAD

**Issue by dunjut** [kubernetes/kubernetes#51009]
According to code snippet https://github.com/kubernetes/kubernetes/blob/e633a1604f00908a1dcc898b206c3404db4d82ed/pkg/controller/service/service_controller.go#L263-L290

The `createLoadBalancerIfNeeded` handles the **ServiceUpdate** events, it first check out whether or not current service need a LoadBalancer, and if not, it ensures corresponding LoadBalacner deleted.  

However, another branch of the `if` statement is a little bit confusing. It says _The load balancer doesn't exist yet, so create it_, and then it calls `s.createLoadBalancer`. I think at this time, we're not sure whether or not the load balancer already exists (since we didn't call `GetLoadBalancer`), so the proper behavior would be *ensure load balancer exists* (actually `s.createLoadBalancer` just calls `EnsureLoadBalancer` indeed), so the comment (L-283) and the function name (L-285 `createLoadBalancer`) isn't very appropriate, it's confusing right?

**Comment by yastij** [comment]
Please see #50299

**Comment by dunjut** [comment]
@yastij I just follow #50299 and I think these are two different issues because

1) #50299 focus on the potential logical error in code (should check existence before calling create..) which I don't agree. I think the code logic is fine. But,

2) This issue focus on the code/comment expression, which means the code logic is okay but the comment and function name is NOT appropriate.

**Comment by yastij** [comment]
The only comment I think should be changed is L283.

**Comment by dunjut** [comment]
@yastij Yes, I mean L283 too, however, I think the function name s.`createLoadBalancer` should also be changed.

**Comment by yastij** [comment]
@dunjut -  it may be called `createOrUpdateLoadBalancer`, i agree that if you do not have prior knowledge of the servicecontroller it may be confusing. can you open a PR ?

**Comment by dunjut** [comment]
@yastij Takes me a lot of time for the first PR preparation...

Now I've opened the PR, please check it out.
