### ISSUE TITLE
[SQ-blocking] All kubemark jobs started failing due to kubelet changes

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51007]
Ref: https://k8s-testgrid.appspot.com/sig-scalability

@mtaufen - Your PR https://k8s-testgrid.appspot.com/sig-scalability was the only one in the diff, and it seems like it broke hollow-kubelet. I'll try to take a further look into it, but for now I think we should revert it as it is blocking the SQ.

@kubernetes/sig-scalability-misc @wojtek-t

**Comment by mtaufen** [comment]
I suspect the problem was that Kubemark was still using the old api scheme to manipulate the configuration. Do we gather logs from the hollow kubelet containers anywhere so I can confirm? @wojtek-t
