### ISSUE TITLE
container statuses contain wrong/misleading image tag

### ISSUE THREAD

**Issue by cpointner** [kubernetes/kubernetes#51017]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When multiple tags of an image share the same SHA256 digest the value status.containerStatuses[].image might return the wrong image tag. Unfortunately `docker inspect` doesn't include the tag that was used to create the container either so this might actually be a bug in docker?

**What you expected to happen**:

status.containerStatuses[].image contains the same tag as specified in spec.containers[].image

**How to reproduce it (as minimally and precisely as possible)**:

 - Create an image named `test:staging` and re-tag it as `test:production`.
 - You now have 2 images with the same name and digest but different tags.
 - Start 2 pods: one using `test:staging` and the other `test:production` as image.
 - The container status for both pods will state that the same image tag was used to create the container which is at least misleading. Although it doesn't really make a difference as both image tags share the same digest it is technically wrong.

**Anything else we need to know?**:

This should imho be considered for #46255.

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: self-hosted cluster
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.3 LTS (Xenial Xerus)`
- Kernel (e.g. `uname -a`): `Linux atgrzsl1751 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: custom ansible playbook
- Others: Docker version: `docker.io (1.12.6-0ubuntu1~16.04.1)`

**Comment by warmchang** [comment]
We have the same problem in our environment.

@yujuhong https://github.com/kubernetes/kubernetes/issues/46255, what advice or plans does the community have? Thank you!

**Comment by zuzzas** [comment]
Just figured out that our internal Controller have been a victim of this issue as well for god knows how log.
We've been relying on this field to determine current image version. Alas, it cannot be relied for more that a year.

**Comment by cinooo** [comment]
Any updates on this? :)

**Comment by tux21b** [comment]
any updates on this?

**Comment by taleodor** [comment]
we observe same issue

**Comment by mshivanna** [comment]
we have been hit by this bug too :(

**Comment by kell18** [comment]
Any news on that?? It's such an annoying bug

**Comment by haircommander** [comment]
This is up to the runtimes to report the correct values. There is the notion of `userRequestedImage` which I believe is shown in the pod status now. That said, the fundamental problem is OCI image specification (and specifically the handling of tags) creates these ambiguities. FWIW: it's generally better to reference images by sha as you know the content is correct and know where the image came from :slightly_smiling_face: 

I think we can close this, please reopen if you disagree

/close
