### ISSUE TITLE
How to change PV's permission?

### ISSUE THREAD

**Issue by dearboll** [kubernetes/kubernetes#51010]
i want to run a non-root user in my container and using the PersistentVolume via Ceph RBD. What troubles me is the PV's permission. I have tried to change the PV's GID but it still does not work.
The pod.yaml is as below:
volumeMounts:
        - name: ceph-vol1
          mountPath: /home/work/clouddisk
          readOnly: false
Although I have chown /home/work/clouddisk to my non-root user in Dockerfile, but when the pod is running I saw /home/work/clouddisk is root again. How can I change PV's permission?

**Comment by wenlxie** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod May solve  your issue.

**Comment by msau42** [comment]
@dearboll, did setting a security context work?

**Comment by dearboll** [comment]
@msau42  It works. Thank you all very much.
