### ISSUE TITLE
kube-controller-manager stuck on updating node status

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#51012]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:
During controller-manager startup it spends ~13 minutes trying to updating the node status (On a 5 node cluster)

During this time it's not processing DaemonSets etc.

**What you expected to happen**:
To complete this phase quickly

**How to reproduce it (as minimally and precisely as possible)**:
Unknown

This is happening during a self-hosted cluster update (i.e. all of the VMs being destroyed/created in sequence)

**Anything else we need to know?**:

It starts going wrong here:
```
E0821 09:32:05.334769       1 nodecontroller.go:978] Error updating node kubernetes-kubernetes-zone2-0-1503077970: Operation cannot be fulfilled on nodes "kubernetes-kubernetes-zone2-0-1503077970": the object has been modified; please apply your changes to the latest version and try again
E0821 09:32:05.362009       1 nodecontroller.go:978] Error updating node kubernetes-kubernetes-zone2-1-1503077970: Operation cannot be fulfilled on nodes "kubernetes-kubernetes-zone2-1-1503077970": the object has been modified; please apply your changes to the latest version and try again
# ... repeated a lot...
# And then starts working here
I0821 09:45:56.611225       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-sy
stem", Name:"checkpoint-installer", UID:"32e2b4a5-7c32-11e7-b064-fa163e294750", APIVersion:"extensions", 
ResourceVersion:"2017896", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: checkpo
int-installer-mzzx2

```

[controller-manager.txt](https://github.com/kubernetes/kubernetes/files/1238493/controller-manager.txt)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: Openstack
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```
- Kernel (e.g. `uname -a`):`Linux kubernetes-kubernetes-zone2-0-1503077970 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel Xeon E3-12xx v2 (Ivy Bridge) GenuineIntel GNU/Linux`
- Install tools: custom
- Others:

**Comment by mikebryant** [comment]
@kubernetes/sig-node-bugs

**Comment by Quentin-M** [comment]
I am facing a similar issue with the controller not being able to update any endpoints or other resources (e.g. StatefulSet) after a full etcd kill+recovery from a snapshot.
