### ISSUE TITLE
"kubect logs --selector" ignoring "--tail=-1"

### ISSUE THREAD

**Issue by Miouge1** [kubernetes/kubernetes#51027]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`kubectl logs --selector='app=myapp' --tail=-1` returns 10 lines.

**What you expected to happen**:

`kubectl logs --selector='app=myapp' --tail=-1` should return all

**How to reproduce it (as minimally and precisely as possible)**:

Use a selector that would output more than 10 lines of logs and do:
`kubectl logs --selector='app=myapp'`
`kubectl logs --selector='app=myapp' --tail=-1`
`kubectl logs --selector='app=myapp' --tail=0`

**Anything else we need to know?**:

Somewhat related to #35335

**Environment**:
- Kubernetes version (use `kubectl version`): server 1.5.2, client 1.6.3

**Comment by CaoShuFeng** [comment]
This is addressed by #51077 ,and can we close it?

**Comment by zjj2wry** [comment]
of course

**Comment by Miouge1** [comment]
Sounds good, thanks everyone!
