### ISSUE TITLE
Fix hardcoded validResources, change to fetch from DiscoveryClient

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#51023]
This problem is a TODO in [here](https://github.com/kubernetes/kubernetes/blob/b776df8a20444568614804791d24e64cc3fee0be/pkg/kubectl/cmd/cmd.go#L201), currently the [validResources](https://github.com/kubernetes/kubernetes/blob/b776df8a20444568614804791d24e64cc3fee0be/pkg/kubectl/cmd/cmd.go#L202) string used in our command help message, and some error messages, but it's hardcoded.

I'm not sure if there' any pitfall or blocker for this TODO haven't been picked yet, if not, I would like to fix that.

I will add an interface `ValidResourcesFromDiscoveryClient` in ring1Factory, and fetch those information from DiscoveryClient(), sort and return a string.

@sttts @deads2k @fabianofranz @kubernetes/sig-cli-misc wdyt ?

**Comment by shiywang** [comment]
@deads2k @sttts also if there's any other shortcut_mapper, discoveryClient releated issue you guys come up with, I can also fix that by the way : )

**Comment by deads2k** [comment]
> I will add an interface ValidResourcesFromDiscoveryClient in ring1Factory, and fetch those information from DiscoveryClient(), sort and return a string.

I think that's a good idea, but you'll need to have a fallback for when the server is unavailable, shouldn't be accessed (--local), or is slow to build the list. I think that fallback should include *only* resources from the core/legacy api group.
