### ISSUE TITLE
informer-gen should not require an internal informer to be generated

### ISSUE THREAD

**Issue by munnerz** [kubernetes/kubernetes#51029]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

`informer-gen` currently defaults `InternalClientSetPackage` to `k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset` (https://github.com/kubernetes/kubernetes/blob/e472a758c77e686e0849587b2b4eba0807e1f312/staging/src/k8s.io/code-generator/cmd/informer-gen/main.go), and as such requires that an internal clientset is provided when using `informer-gen` to create informers.

**What you expected to happen**:

When using CRDs, versioning is not currently supported and if it were, it'd likely not be done through code generation and submission to the apiserver. It

I'd expect to be able to skip generating an internal informer for my API. Looking at the code path, it seems we don't even need to differentiate between internal and external API versions in the generate. If I'm correct in this assumption, we could remove `VersionedClientSetPackage` and `InternalClientSetPackage` and replace it with a simple `ClientSetPackage`.

I think I've seen that there's an omit to get rid of the 'special' status of the internal API version, and it seems this would help push us toward this goal!

/cc @sttts @ncdc

**Comment by ncdc** [comment]
When I first wrote informer-gen, we didn't have shared informers in client-go, and it made sense to be able to generate all the informers (internal & external) in one pass. Now that client-go does have the informers, I think it makes sense to modify informer-gen so that a single invocation generates one set of informers (either internal or versioned).

**Comment by ncdc** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by munnerz** [comment]
@ncdc do you know if the internal clientset requires 'special treatment'? Or can we potentially remove the distinction between the two types altogether?

**Comment by ncdc** [comment]
@munnerz there isn't anything special about it, no. The reason for having it as a flag was to be able to get the import statement right. You can't use the internal clientset with versioned APIs and vice versa.

**Comment by mml** [comment]
cc @enisoc 
cc @caesarxuchao

**Comment by munnerz** [comment]
It appears it is possible to generate *just* versioned Informers -

Whilst the clientset package argument is required/defaults to a value, it will only actually be used if an API package that's determined to be internal (i.e. has no `json` struct tags) is passed as part of `--input-dirs`. Therefore, if you don't want to use an internal version you can simply leave the `--internal-clientset-package` as the default and make sure to not pass an internal version into the generator.

I'm going to close this issue now as I don't think there's anything more to do, unless it's still desired that it takes 2 invocations of informer-gen to generate internal & external informers.
