### ISSUE TITLE
Unable to use a fieldSelector with custom resources

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#51046]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: got an error when trying to use a fieldSelector when watching a custom resource

**What you expected to happen**: no error

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a CRD and then a CR for it.
1. Try to watch with a fieldSelector, such as `metadata.name=b1`

```
I0821 16:05:00.053529    2067 round_trippers.go:383] GET https://172.17.0.1:6443/apis/ark.heptio.com/v1/namespaces/heptio-ark/downloadrequests?fieldSelector=metadata.name%3Db1&resourceVersion=174842&watch=true
I0821 16:05:00.053540    2067 round_trippers.go:390] Request Headers:
I0821 16:05:00.053547    2067 round_trippers.go:393]     Accept: application/json, */*
I0821 16:05:00.053553    2067 round_trippers.go:393]     User-Agent: main/v1.7.3 (linux/amd64) kubernetes/$Format
I0821 16:05:00.056961    2067 round_trippers.go:408] Response Status: 400 Bad Request in 3 milliseconds
I0821 16:05:00.057028    2067 round_trippers.go:411] Response Headers:
I0821 16:05:00.057036    2067 round_trippers.go:414]     Content-Type: application/json
I0821 16:05:00.057040    2067 round_trippers.go:414]     Content-Length: 155
I0821 16:05:00.057043    2067 round_trippers.go:414]     Date: Mon, 21 Aug 2017 20:05:00 GMT
I0821 16:05:00.057058    2067 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unstructured cannot convert field labels","reason":"BadRequest","code":400}
```

**Anything else we need to know?**:

The customresource `REST` implementation has a `PredicateFunc` defined, and it looks like it should support at least a field selector for `metadata.namespace` and `metadata.name`, but I'm guessing we need a bit more in place to make this work for `meta/v1/unstructured`.

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD (commit baf2f85e738d83e8be6d1d75fed3a203b529a887)

/sig api-machinery
@deads2k @enisoc @sttts @nikhita 

I can try to submit a PR to fix once I finish my current work item, if nobody picks this up sooner.

**Comment by mml** [comment]
cc @enisoc

**Comment by enisoc** [comment]
This is a more general form of #49424. I don't have immediate plans to work on either of them, so you're welcome to take it.

**Comment by ncdc** [comment]
@enisoc sounds good. Do you want me to close this as a dupe?

**Comment by enisoc** [comment]
I think there's a useful distinction between the two issues. If we support only `metadata.name`, that would be enough to close #49424, but this one tracks the idea of supporting arbitrary field selectors.

By the way, if I recall correctly, when I applied the hack mentioned in the other thread to skip the `ConvertFieldLabel` step for CRDs, I think I saw that actually arbitrary field selectors worked too (not just `metadata.name`). That would mean enabling this might be easy on a technical level, although we may need to think through whether this could tie our hands if we ever wanted to add versioning support for CRD in the future. This issue is a better home for that discussion than the other one.

**Comment by kargakis** [comment]
This would help a lot with debugging in prow. Today, the only thing we can do is bubble up information from the spec of a prowjob as labels and use a label selector.

**Comment by ncdc** [comment]
What about just having `UnstructuredObjectConverter`'s `ConvertFieldLabel` just return the passed in label and value without any "conversion" for now?

**Comment by enisoc** [comment]
I don't think we'd want to do it for all Unstructured, since there's no guarantee all Unstructured objects are CRD objects. However, it should be pretty easy to arrange for ConvertFieldLabel to be a no-op for CRD objects, which makes sense currently because CRD only allows one version for a given resource. 

We just need to make sure this will not prevent us from doing more with CRD versioning in the future. My suspicion is that it should be fine, but I haven't investigated properly.

**Comment by ncdc** [comment]
@enisoc ok, I can put together a PR to make this change.

> We just need to make sure this will not prevent us from doing more with CRD versioning in the future. My suspicion is that it should be fine, but I haven't investigated properly.

@deads2k @liggitt @sttts @nikhita any gut reactions?

**Comment by ncdc** [comment]
PR: #53345

**Comment by jinghzhu** [comment]
@ncdc 

I am sorry to comment on this closed thread.

Currently, I am working on a CRD and needs to support arbitrary field selectors. I've tried to do it by learning from what you do for [pods](https://github.com/kubernetes/kubernetes/blob/c16ff84e925ea56a8753bb0cd2650c8e9a71ff1c/pkg/api/v1/conversion.go#L156-L180). But it always throws error: `field label not supported: status.state`.

So, I am wondering if I am doing something wrong or it only supports limited field selectors for CRD, which is stated [here](https://github.com/kubernetes/kubernetes/pull/53345/files#diff-2f720a7e61a4ddfcfe9a9e353be8784bR404-R414).  

Here is my code snippet:
```go
var (
	SchemeGroupVersion = schema.GroupVersion{
		Group:   mycrd.GroupName,
		Version: Version,
	}
	schemeBuilder = runtime.NewSchemeBuilder(addKnownTypes, addConversionFuncs)
	AddToScheme = schemeBuilder.AddToScheme
)

func addConversionFuncs(scheme *runtime.Scheme) error {
	return scheme.AddFieldLabelConversionFunc(
		Version,
		Kind,
		func(label, value string) (string, string, error) {
			switch label {
			case "status.state":
				return label, value, nil
			default:
				return "", "", fmt.Errorf("CRD field label not supported: %s", label)
			}
		},
	)
}

func test() {
        ......
        opts := metav1.ListOptions{
		FieldSelector: "status.state=Pending",
	}
	launches, err := client.List(opts)
	if err != nil {
		panic(err)
	}
}
```

**Comment by ncdc** [comment]
CRDs still only support namespace and name for field selectors

**Comment by filippomc** [comment]
Hi, isn't there any plan to support other fields for CRDs? In my use case (create argo workflows) not being able to filter by status is quite a big limitation

**Comment by zhujl1991** [comment]
> CRDs still only support namespace and name for field selectors

Any plan to support arbitrary field selector for CRDs?

**Comment by liggitt** [comment]
Not currently
