### ISSUE TITLE
Namespace arg ignored when using `kubectl create secret --dry-run`

### ISSUE THREAD

**Issue by absoludity** [kubernetes/kubernetes#51068]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When creating a secret using `--namespace` and `--dry-run`, the namespace is not included in the secret metadata.

**What you expected to happen**:
The metadata includes the specified namespace.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl create secret generic mysecret --dry-run --from-literal=foo=bar -o json --namespace foo
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "mysecret",
        "creationTimestamp": null
    },
    "data": {
        "foo": "YmFy"
    }
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: na (--dry-run)
- OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="16.04.3 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`): 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by zjj2wry** [comment]
@deads2k don't  RunCreateSubcommand() is need support namespace for try-run? if yes, maybe we should check namespaces is exist in api-server and write namespace to object.

**Comment by deads2k** [comment]
> @deads2k don't know RunCreateSubcommand() is need support namespace for try-run? if yes, maybe we should check namespaces is exist in api-server and write namespace to object.

Pretty sure the namespace gets defaulted, so we don't create the object with a namespace backed in.  @fabianofranz  for confirmation.

**Comment by WanLinghao** [comment]
@zjj2wry @deads2k  so it's not a bug at all?
