### ISSUE TITLE
Disable the kube-apiserver insecure port, and lead to health-check can't work

### ISSUE THREAD

**Issue by fisherxu** [kubernetes/kubernetes#51076]
In my environment, because the insecure port 8080 of kube-apiserver **expose all the API**. For security reasons, the port is Disabled. But lead to **health-check and pprof  can't work**. Can we consider **opening a separate port**  like other component only for health-check and pprof， metrics？

/sig cluster-lifecycle
/cc @caesarxuchao @deads2k @lavalamp @liggitt @mml

**Comment by deads2k** [comment]
> But lead to health-check and pprof can't work. Can we consider opening a separate port like other component only for health-check and pprof， metrics？

Why not update your  health check to use the secure port?   The kubelet supports it and the default authorization rules allow it.

**Comment by fisherxu** [comment]
@deads2k Thanks for quick reply, since other components like kubelet all have the insecure port to do health-check and pprof, so we want to be consistent.Why can't consider open an separate port like other components to do health and metric，8080 only for insecure api for k8s itself. I think this make the architecture more clearer :)

**Comment by deads2k** [comment]
> @deads2k Thanks for quick reply, since other components like kubelet all have the insecure port to do health-check and pprof, so we want to be consistent.Why can't consider open an separate port like other components to do health and metric，8080 only for insecure api for k8s itself. I think this make the architecture more clearer :)

Nothing should use an unsecured port.  All the others should be fixed to remove that port.  Movement on the kube-apiserver is towards securing all ports, not opening specific holes.  Default authorization (rbac) will allow access to healthz, but not to metrics.  Other authorizers should behave likewise.  Anything accessing metrics should be authenticatable.

**Comment by fisherxu** [comment]
> Default authorization (rbac) will allow access to healthz, but not to metrics. Other authorizers should behave likewise. Anything accessing metrics should be authenticatable.

I really agree with you, accessing metrics should be authenticatable. BTW, when this plan will be implemented?

**Comment by fisherxu** [comment]
Still another question, now I deploy kube-apiserver as container, and also through http probe to check for it, seems like probe only support insecure port?

**Comment by fisherxu** [comment]
Still another question, I deploy kube-apiserver as a container, if disabled insecure port, kubelet probe will can't work, have any idea how to deal with it and in your cluster how to do this?

**Comment by idouba** [comment]
@deads2k  Yes, HTTPProber can specify HTTPS schema, but disable security check by this:
 `func New() HTTPProber {
	tlsConfig := &tls.Config{InsecureSkipVerify: true}
	...
	return httpProber{transport}
}`

**Comment by dims** [comment]
@idouba `InsecureSkipVerify` seems ok for a health check. can you please explain what you mean a bit more?

**Comment by fisherxu** [comment]
@deads2k  @idouba   @dims Thanks very much for reploy. 

> Readiness probes allow the specification of a scheme, which can be https.

Our kube-apiserver securePort will  verify the client's certificate. InsecureSkipVerify ok for a health check？

**Comment by dims** [comment]
@fisherxu i don't believe `/healthz` needs the client cert. Can you please try and see if it works? yes on the client side `InsecureSkipVerify` should be enough

**Comment by fisherxu** [comment]
@dims I try _curl -k https://masterip:6443/healthz_  and it return **Unauthorized**. Maybe we can make probe support the certificate？

**Comment by deads2k** [comment]
> @dims I try curl -k https://masterip:6443/healthz and it return Unauthorized. Maybe we can make probe support the certificate？

Can you show the complete `-v` output from curl?  It can return 403's until the bootstrap roles and bindings are created, but we bind `system:discovery` to `system:unauthenticated`.  If you're using a webhook or some other authorization scheme, you'll want to do the same.  `/healthz` doesn't reveal sensitive data; the reasons are redacted.

**Comment by fisherxu** [comment]
root@SZV1000272344:~# curl -k -v  https://masterip:6443/healthz
*   Trying masterip...
* Connected to masterip(masterip) port 6443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: kube-apiserver (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=kube-apiserver
* 	 start date: Wed, 26 Apr 2017 03:05:08 GMT
* 	 expire date: Thu, 26 Apr 2018 03:05:08 GMT
* 	 issuer: CN=kubernetes
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /healthz HTTP/1.1
> Host: masterip:6443
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 24 Aug 2017 13:40:56 GMT
< Content-Length: 13
< 
Unauthorized
* Connection #0 to host 100.109.161.75 left intact

**it return 401** @deads2k @dims  @idouba

**Comment by deads2k** [comment]
> it return 401 @deads2k @dims @idouba

It appears that you have anonymous authentication disabled.  Anonymous auth is on by default in installations now and would allow this to succeed in our recommended installation.

**Comment by dims** [comment]
@deads2k you mean `AlwaysAllow` in the `--authorization-mode` command line flag right? or was it the `--anonymous-auth` command line option?

**Comment by deads2k** [comment]
> or was it the --anonymous-auth

` --anonymous-auth`.  I'd recommend using RBAC as the authorization mode to anyone trying to build out a cluster.

**Comment by dims** [comment]
@deads2k thanks. checking since i saw `AUTHORIZATION_MODE="RBAC,AlwaysAllow"` in test-cmd.sh

**Comment by xingangwang** [comment]
@deads2k Must anonymous authentication be enabled to make the secure health checking works? But the CIS benchmark recommends to disable it.

**Comment by deads2k** [comment]
> @deads2k Must anonymous authentication be enabled to make the secure health checking works? But the CIS benchmark recommends to disable it, the kube-bench report told me 1.1.2 Ensure that the --anonymous-auth argument is set to false (Scored),I also got 401 when kubelet probes kube-apiserver via https://127.0.0.1:443.

As long as you aren't using the `AlwaysAllow` authorizer, it's fine to have the anonymous-auth argument set to true.

@kubernetes/sig-auth-api-reviews @liggitt who works on the benchmark.  Looks like it needs some updating to understand the authenticator/authorizer interaction.

**Comment by liggitt** [comment]
> @kubernetes/sig-auth-api-reviews @liggitt who works on the benchmark. Looks like it needs some updating to understand the authenticator/authorizer interaction

I gave the same feedback already when the benchmark was being put together.

**Comment by xingangwang** [comment]
@liggitt Could you please give me a feedback here if getting any conclusions?

**Comment by liggitt** [comment]
allowing anonymous requests access to /healthz and discovery information is a reasonable thing to do. if you want to lock it down, your load balancers would need to be able to provide credentials to access /healthz

**Comment by lavalamp** [comment]
Honestly I think we should allocate a separate port specifically for liveness and readiness checking. It's a little embarrassing that apiserver doesn't support both, since we tell everyone else they should do so.

**Comment by liggitt** [comment]
A healthz-only port would be consistent with some of the other components and I could see it being an optional useful addition (and certainly greatly preferred to an insecure port with full api access)

**Comment by thyarles** [comment]
> @deads2k Must anonymous authentication be enabled to make the secure health checking works? But the CIS benchmark recommends to disable it, the kube-bench report told me `1.1.2 Ensure that the --anonymous-auth argument is set to false (Scored)`,I also got 401 when kubelet probes kube-apiserver via `https://127.0.0.1:443`.

Awesome! I tried both commands bellow and I got a PASS on both:
```
curl -L https://raw.github.com/aquasecurity/kube-bench/main/job-master.yaml | kubectl create -f -
curl -L https://raw.github.com/aquasecurity/kube-bench/main/job-node.yaml | kubectl create -f -
```
