### ISSUE TITLE
kube-proxy manifest should use `--oom-score-adj` flag (?)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#51083]
In cluster/saltbase/salt/kube-proxy/kube-proxy.manifest, we have this:

```
    command:
    - /bin/sh
    - -c
    - echo -998 > /proc/$$$/oom_score_adj && kube-proxy {{api_servers_with_port}} {{kubeconfig}} {{cluster_cidr}} --resource-container="" {{params}} 1>>/var/log/kube-proxy.log 2>&1
```

But kube-proxy also has a `--oom-score-adj` flag.  Is there a reason to use the `echo` approach instead of using the flag?

cc @vishh as you wrote the code, in https://github.com/kubernetes/kubernetes/pull/41700

**Comment by vishh** [comment]
In general, oom_score_adj is not expected to be directly updated by pods and kubelet is expected to manage it. 
If kube-proxy runs in the Guaranteed QoS class, then it's OOM score adj will be set to a low number.
Until that happens, kube-proxy process may want to be shielded from OOM kills to an extent (this matters only when kube-proxy's memory usage >> memory request)
Meanwhile, it does not make sense to have two means to configure the same thing. 
I'll let @MrHohn decide which option he prefers and sunset the other option.

**Comment by MrHohn** [comment]
@vishh Thanks for clarifying. At this point, I prefer to use the built-in flag instead of relying on composing bash commands. Sent #51221 for this.
