### ISSUE TITLE
autoscaler scales down below minReplicas when "All metrics below target"

### ISSUE THREAD

**Issue by dmitrievav** [kubernetes/kubernetes#51111]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
autoscaler scales down below minReplicas

**What you expected to happen**:
autoscaler should not scale down below minReplicas

**How to reproduce it (as minimally and precisely as possible)**:
create a deployment with a fake pod which does not really use CPU
create a hpa whit following parameters:
- Metrics:						( current / target )
  resource cpu on pods  (as a percentage of request):	0% (0) / 80%
- Min replicas:						2
- Max replicas:						5

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/controller/podautoscaler/horizontal.go
Does not have a check to prevent downscaling below minReplicas.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian jessie
- Kernel (e.g. `uname -a`): Linux ip-10-1-41-75 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux
- Install tools: kops
- Others:

**Comment by MaciekPytel** [comment]
This has been fixed in 1.7.2.

Ref: https://github.com/kubernetes/kubernetes/pull/48997, https://github.com/kubernetes/kubernetes/pull/49047
