### ISSUE TITLE
FeatureGate still has DynamicVolumeProvisioning though it is gone since 1.6

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#51120]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

kube-apiserver --help still shows this:
```
 DynamicVolumeProvisioning=true|false (ALPHA - default=true)
```

It looks like the related feature can be turned off. However, dynamic volume provisioning Alpha has retried in 1.6.

**What you expected to happen**:

Remove `DynamicVolumeProvisioning` from feature gate to avoid confusion.

**How to reproduce it (as minimally and precisely as possible)**:

Run `kube-apiserver --help`

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7+
- Cloud provider or hardware configuration**: Any
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Any
- Install tools:
- Others:

**Comment by lavalamp** [comment]
@xiangpengzhao @tengqm: SIG API Machinery doesn't own the *contents* of the API.

/sig storage
