### ISSUE TITLE
Flexvolumes ci-kubernetes-e2e-gci-gce-alpha-features failing

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#51123]
tests are failing atm on GCI https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/14884 because VOLUME_PLUGIN_DIR=/home/kubernetes/flexvolume set in cluster/common.sh takes precedence over KUBELET_TEST_VOLUME_PLUGIN_DIR="/etc/srv/kubernetes/kubelet-plugins/volume/exec". As far as I can tell /home/kubernetes/flexvolume is not readable yet by containerized kubelet so the test needs to keep using "/etc/srv/kubernetes/kubelet-plugins/volume/exec" and the bash needs to be shuffled around to solve this.

cc @verult

**Comment by wongma7** [comment]
This is more an acknowledgment of the issue than anything, can't write a PR until later

**Comment by ericchiang** [comment]
cc @kubernetes/sig-storage-bugs 
/kind e2e-test-failure

**Comment by jdumars** [comment]
@kubernetes/sig-storage-bugs this is currently blocking alpha.3 release

**Comment by wongma7** [comment]
@jdumars we are just waiting for https://github.com/kubernetes/kubernetes/pull/51166 approval

**Comment by wongma7** [comment]
@jdumars I think they’re still failing, not sure what the release process is, but these tests started running only yesterday and so failure indicates something wrong with the test themselves, they shouldn’t block release. (They succeed on gce cluster with Debian nodes but fail on gci)

**Comment by jdumars** [comment]
@wongma7 well, let's see if we can get the kinks worked out before the beta release on 9/27 or we will need to disable it from release-blocking

**Comment by wongma7** [comment]
# non-attachable:

I0824 17:49:28.426001    8562 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "flex-volume-0" (UniqueName: "flexvolume-k8s/dummy-e2e-tests-flexvolume-wf48v/934e3eba-88f4-11e7-a3f9-42010a800002-flex-volume-0") pod "flex-client" (UID: "934e3eba-88f4-11e7-a3f9-42010a800002")

# attachable:

## controller-manager.log:
I0824 17:44:06.955342       4 operation_generator.go:275] AttachVolume.Attach succeeded for volume "flex-volume-0" (UniqueName: "flexvolume-k8s/dummy-attachable-e2e-tests-flexvolume-j8962/flex-volume-0") from node "bootstrap-e2e-minion-group-9913" 
W0824 17:44:06.955385       4 plugin-defaults.go:32] flexVolume driver k8s/dummy-attachable-e2e-tests-flexvolume-j8962: using default GetVolumeName for volume 0x1c5df60
## kubelet.log:
I0824 17:43:59.619109    3728 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "flex-volume-0" (UniqueName: "flexvolume-k8s/dummy-attachable-e2e-tests-flexvolume-j8962/flex-volume-0") pod "flex-client" (UID: "cf5d743d-88f3-11e7-a3f9-42010a800002")
E0824 17:43:59.619238    3728 nestedpendingoperations.go:262] Operation for "\"flexvolume-k8s/dummy-attachable-e2e-tests-flexvolume-j8962/flex-volume-0\"" failed. No retries permitted until 2017-08-24 17:44:00.119202945 +0000 UTC (durationBeforeRetry 500ms). Error: Volume has not been added to the list of VolumesInUse in the node's volume status for volume "flex-volume-0" (UniqueName: "flexvolume-k8s/dummy-attachable-e2e-tests-flexvolume-j8962/flex-volume-0") pod "flex-client" (UID: "cf5d743d-88f3-11e7-a3f9-42010a800002")

Seems there is something wrong with VerifyControllerAttachedVolume, still at a loss as to why it's showing up in GCI but not Debian

**Comment by wongma7** [comment]
Never mind the GCI vs Debian issue, our test fix would have worked but in between https://github.com/kubernetes/kubernetes/commit/6bb928a3dff60c and https://github.com/kubernetes/kubernetes/commit/2b08d1e5a18ce3, something else changed and is causing both GCI and Debian tests to fail.

**Comment by wongma7** [comment]
https://github.com/kubernetes/kubernetes/pull/50843 might be the cause, so we might be looking at legitimate failures caught by the test at this point (yay?) and not faulty tests. investigating...
