### ISSUE TITLE
Potential bug related to pointer in strategic merge patch

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#51155]
Pointer usage in strategic merge patch test looks like a bug.

The type defined in [patch_test.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go#L96) is a pointer that has patch metadata.

It has some usage. e.g. in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go#L237-L270
More tests using it can be found by searching `mergeItemPtr` in [patch_test.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go)

This change is initially introduced in https://github.com/kubernetes/kubernetes/pull/9806/files.

I want to understand if this a bug or some magic.

cc: @liggitt @apelisse 

also cc: original PR reviewer and author: @ghodss @mikedanese @manansaraf

/sig cli

**Comment by mengqiy** [comment]
If this is not a bug, my guess is that point and slice are identical in golang like pointer and array in C.

**Comment by liggitt** [comment]
it looks like it is just resolving the underlying type in order to read fields and their tags. what bug do you think you are seeing?

**Comment by mengqiy** [comment]
Not sure if it's a bug.
```
MergeItemPtr *MergeItem `patchStrategy:"merge" patchMergeKey:"name"`
```
`MergeItemPtr` is a pointer of `MergeItem`. But it can be used like a slice of `MergeItem`.
E.g. in this test case: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go#L260-L270.
```
mergeItemPtr:
  - name: 1  # <--- Why mergeItemPtr can have a list of items?
  - name: 3
  - name: 2
```
