### ISSUE TITLE
AppArmor validation is docker specific.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#51156]
AppArmor validator returns error if the runtime is not `docker`.

For other runtime integrated via CRI, the runtime will be `remote`, and will not be able to provide AppArmor support because of this.

Currently, we decided to always pass validation for remote runtime, but we need a better solution in the future.

This is similar with https://github.com/kubernetes/kubernetes/issues/50343, and also related to #32803.

/cc @yujuhong @timstclair @feiskyer @mrunalp @mikebrow

**Comment by feiskyer** [comment]
I think we should pass validation for all container runtimes in validateHost, since it is host-wide.

**Comment by feiskyer** [comment]
Let me remove this requirement.

/assign
