### ISSUE TITLE
Support OpenAPI v3

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#51163]
Now that OpenAPI released version 3.0 we should support it. We should keep the support for v2 until we have full tooling support for v3.

[OpenAPI v3 Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)

[Differences between v2 and v3](https://www.openapis.org/news/blogs/2016/07/you-can-get-involved-creating-openapi-specification-and-heres-how)

**Comment by munnerz** [comment]
Now that #47263 has merged, it'd be great to be able to auto-generate schemas for our custom resource types.

@mbohlool have you had a chance to look at this yet? I'd be happy to take a look, although I'm not too sure where to start.

/cc @nikhita

**Comment by sttts** [comment]
@munnerz a good start is @mbohlool's PR from 1.8 adding OpenAPI aggregation in kube-apiserver: https://github.com/kubernetes/kubernetes/pull/50864. Probably apiextensions-apiserver "just" has to serve an OpenAPI spec built from the registered CRDs.

**Comment by mbohlool** [comment]
@munnerz @sttts correct. Just serving an OpenAPI spec at /swagger.json should solve this. Your spec would have a constant part that is defining CRUD operations on CRD and then plugin the model there. I may not get to this in 1.9 so your help is appreciated here.

**Comment by mbohlool** [comment]
Also I think this is the wrong issue to discuss CRD's OpenAPI support. For now we are supporting CRDs with OpenAPI v2. The spec generation in apiextensions-apiserver should somehow downgrade the model from v3 to v2. We need a new issue for this.

**Comment by roycaihw** [comment]
v3 spec requirement: https://github.com/kubernetes/kubernetes/issues/79472
v3 support KEP: https://github.com/kubernetes/enhancements/pull/1263

/close
