### ISSUE TITLE
kubectl create with no args shouldn't display all help options

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#51175]
The most important part of `kubectl create` is the subcommands.  For this top level command, and maybe a few others (set), the options should only be shown if we do `kubectl create -h` or `kubectl help create`, but not if a user simply runs `kubectl create`.  That would make it much more readable for end users.

**Comment by smarterclayton** [comment]
Also, `kubectl create` needs a description paragraph - a few sentences describing what the purpose of the command is.

**Comment by k82cn** [comment]
@jinzhejz , please help on this; it's good for newbee :).

**Comment by zjj2wry** [comment]
@jinzhejz you can use custom-defined-template

**Comment by jinzhejz** [comment]
@zjj2wry thanks for the advice, let me check it.

**Comment by jinzhejz** [comment]
I think we can add an new usage template like `MainUsageTemplate()` in `pkg/kubectl/cmd/templates/templates.go` without `SectionFlags`, and use the new template to show command usage when run `kubectl create` simply
