### ISSUE TITLE
kubectl logs with EOF error when the pod are not in the master node.

### ISSUE THREAD

**Issue by yison** [kubernetes/kubernetes#51179]
/kind bug
/area kubectl

**What happened**:
kubectl -n sock-shop logs carts-2469883122-hdqwt -c carts
Error from server: Get https://10.239.131.212:10250/containerLogs/sock-shop/carts-2469883122-hdqwt/carts: EOF

**What you expected to happen**:
How can I debug and solve this issue?

**How to reproduce it (as minimally and precisely as possible)**:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
I created a kubenetes cluster by the guide above. It worked well. And I can run "kubectl logs pod" correctly when the pod are in the master node.  But when the pod is in other nodes, it will return  EOF error.
cloud001-precision-tower-5810 is the master node.

NAMESPACE     NAME                                                    READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   etcd-cloud001-precision-tower-5810                      1/1       Running   7          6d           cloud001-precision-tower-5810
kube-system   kube-apiserver-cloud001-precision-tower-5810            1/1       Running   7          6d           cloud001-precision-tower-5810
kube-system   kube-controller-manager-cloud001-precision-tower-5810   1/1       Running   7          6d           cloud001-precision-tower-5810
kube-system   kube-dns-2425271678-wsr9m                               3/3       Running   14         7d               cloud003-precision-tower-5810
kube-system   kube-proxy-0mfg9                                        1/1       Running   1          7d           cloud003-precision-tower-5810
kube-system   kube-proxy-362tq                                        1/1       Running   7          7d          cloud001-precision-tower-5810
kube-system   kube-proxy-bcvg1                                        1/1       Running   1          6d           cloud002-precision-tower-5810
kube-system   kube-scheduler-cloud001-precision-tower-5810            1/1       Running   7          6d           cloud001-precision-tower-5810
kube-system   weave-net-6hkjl                                         2/2       Running   2          6d           cloud002-precision-tower-5810
kube-system   weave-net-pg282                                         2/2       Running   2          6d        10.239.131.212   cloud003-precision-tower-5810
kube-system   weave-net-z85q3                                         2/2       Running   11         6d        10.239.131.215   cloud001-precision-tower-5810
sock-shop     carts-2469883122-hdqwt                                  1/1       Running   1          6d        10.40.0.4        cloud003-precision-tower-5810
sock-shop     carts-db-1721187500-bbwdd                               1/1       Running   1          6d        10.40.0.5        cloud003-precision-tower-5810
sock-shop     catalogue-4293036822-s81vl                              1/1       Running   1          6d        10.40.0.3        cloud003-precision-tower-5810
sock-shop     catalogue-db-1846494424-wq504                           1/1       Running   1          6d        10.40.0.11       cloud003-precision-tower-5810
sock-shop     front-end-2337481689-939jv                              1/1       Running   1          6d        10.40.0.12       cloud003-precision-tower-5810
sock-shop     orders-733484335-hdd8k                                  1/1       Running   1          6d        10.40.0.19       cloud003-precision-tower-5810
sock-shop     orders-db-3728196820-28kh8                              1/1       Running   1          6d        10.40.0.17       cloud003-precision-tower-5810
sock-shop     payment-3050936124-9qbsn                                1/1       Running   1          6d        10.40.0.18       cloud003-precision-tower-5810
sock-shop     queue-master-2067646375-5nlvk                           1/1       Running   1          6d        10.40.0.14       cloud003-precision-tower-5810
sock-shop     rabbitmq-241640118-9z713                                1/1       Running   1          6d        10.40.0.20       cloud003-precision-tower-5810
sock-shop     shipping-2463450563-vc0gl                               1/1       Running   1          6d        10.40.0.16       cloud003-precision-tower-5810
sock-shop     user-1574605338-t7kd2                                   1/1       Running   1          6d        10.40.0.2        cloud003-precision-tower-5810
sock-shop     user-db-3152184577-zgvs6                                1/1       Running   1          6d        10.40.0.13       cloud003-precision-tower-5810

kubectl -n kube-system logs kube-proxy-0mfg9
Error from server: Get https://xxxxx:10250/containerLogs/kube-system/kube-proxy-0mfg9/kube-proxy: EOF

**Anything else we need to know?**:
used proxy and added all the cluster nodes into no_proxy.
**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
physical server: CPU Intel(R) Xeon(R) CPU E5-1650 6 cores, RAM 128G
- OS (e.g. from /etc/os-release):
ubuntu 16.04
- Kernel (e.g. `uname -a`):
4.10.0-32-generic #36~16.04.1-Ubuntu
- Install tools:
kubeadm
- Others:

**Comment by ErikOShaughnessy** [comment]
I have run into the same problem:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

# kubectl get pods -o wide
NAME                              READY     STATUS    RESTARTS   AGE       IP             NODE
cassandra-0                       1/1       Running   0          18h       10.244.1.196   wb1
consumer-dev-0                    1/1       Running   0          5h        10.244.5.179   wb5
generators-0                      2/2       Running   0          1h        10.244.5.181   wb5
jupyter-0                         1/1       Running   0          6h        10.244.5.175   wb5
kafka-0                           1/1       Running   6          18h       10.244.2.41    wb2
spark-master-0                    1/1       Running   0          18h       10.244.3.151   wb3
spark-ui-proxy-controller-7m9pt   1/1       Running   1          18h       10.244.0.157   wb6
spark-worker-0                    1/1       Running   0          18h       10.244.4.170   wb4
zookeeper-0                       1/1       Running   0          18h       10.244.2.40    wb2

# kubectl get pods -n kube-system -o wide
NAME                          READY     STATUS    RESTARTS   AGE       IP             NODE
etcd-wb6                      1/1       Running   0          19h       1.1.1.205      wb6
kube-apiserver-wb6            1/1       Running   0          19h       1.1.1.205      wb6
kube-controller-manager-wb6   1/1       Running   0          19h       1.1.1.205      wb6
kube-dns-545bc4bfd4-96nl2     3/3       Running   0          19h       10.244.0.156   wb6
kube-flannel-ds-55qfq         2/2       Running   2          18h       1.1.1.200      wb1
kube-flannel-ds-5ql9p         2/2       Running   0          18h       1.1.1.202      wb3
kube-flannel-ds-6dkj2         2/2       Running   0          18h       1.1.1.201      wb2
kube-flannel-ds-7tbgj         2/2       Running   0          18h       1.1.1.205      wb6
kube-flannel-ds-lzmrg         2/2       Running   0          18h       1.1.1.203      wb4
kube-flannel-ds-sk9kp         2/2       Running   0          18h       1.1.1.204      wb5
kube-proxy-274mr              1/1       Running   0          18h       1.1.1.203      wb4
kube-proxy-cqstn              1/1       Running   0          18h       1.1.1.202      wb3
kube-proxy-fx5wk              1/1       Running   0          18h       1.1.1.204      wb5
kube-proxy-m4ssm              1/1       Running   0          19h       1.1.1.200      wb1
kube-proxy-vmrq8              1/1       Running   0          18h       1.1.1.201      wb2
kube-proxy-x7qzw              1/1       Running   0          19h       1.1.1.205      wb6
kube-scheduler-wb6            1/1       Running   0          19h       1.1.1.205      wb6
```

Node wb6 is the master and ```kubectl logs``` on any pod scheduled on wb6 works as expected.

If the target pod is on any other node, a cryptic error results:
```
# kubectl logs zookeeper-0 
Error from server: Get https://1.1.1.201:10250/containerLogs/default/zookeeper-0/zookeeper: EOF
```

It appears that the http GET for 1.1.1.201:10250 is aimed at kube-proxy-vmrq8 given the IP and port, and kube-proxy isn't responding.

All nodes are running a relatively up-to-date install of Centos 7 and the cluster was installed with kubeadm with flannel as the fabric.
