### ISSUE TITLE
Insufficient documentation for HPA Custom metrics based scaling - GKE(Google container engine)

### ISSUE THREAD

**Issue by sureshdsk** [kubernetes/kubernetes#51188]
**Insufficient Documentation**:

Clear documentation for HPA Custom metrics based scaling is not available.

Documentation required for both  
* Minikube
* Google container engine

**Comment by Glennvd** [comment]
Any update on this in the past 4 months?

**Comment by ocervell** [comment]
@Glennvd not sure if you're still looking, but there is now a solution for [hpa autoscaling on GKE](https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling)

**Comment by Glennvd** [comment]
Thanks for the heads up @ocervell, I had already found the documentation but unfortunately ran into some other issues (https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/113#issuecomment-372350817)

**Comment by mwielgus** [comment]
Docs are available here:

https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling
