### ISSUE TITLE
The status of Persistent Volumes always is pending when i create a new PV.

### ISSUE THREAD

**Issue by wzdnzd** [kubernetes/kubernetes#51190]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

> /kind feature

**What happened**:
![image](https://user-images.githubusercontent.com/8565764/29612872-01623b64-8836-11e7-911e-3be1436aba13.png)

Today i found many PVs  in my k8s cluster are pending and i cann't know what's hapened.It cannot work well when i create a new PV.I'm using Network File System and it work well.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
![version](https://user-images.githubusercontent.com/8565764/29613215-9aaa655c-8837-11e7-8672-00d93d124237.png)

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): Linux  3.10.0-514.10.2.el7.x86_64
- Install tools: kubeadm
- Others:

**Comment by gnufied** [comment]
Can you paste your pv's YAML?

**Comment by wzdnzd** [comment]
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
      volume.beta.kubernetes.io/storage-class: slow
  labels:
     release: prometheus-test
  name: prometheus-test
spec:
   accessModes:
   - ReadWriteMany
  capacity:
     storage: 10Gi
  nfs:
     path: /data/nfs/prometheus-test
     server: xxx.xxx.xxx.xxx
  persistentVolumeReclaimPolicy: Recycle

**Comment by wzdnzd** [comment]
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
  labels:
    release: prometheus-test
  name: prometheus-test
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /data/nfs/prometheus-test
    server: xxx.xxx.xxx.xxx
  persistentVolumeReclaimPolicy: Recycle

**Comment by wzdnzd** [comment]
@gnufied Hi,gnufied,my pv's yaml file as show in the screenshot below.Thx.
![default](https://user-images.githubusercontent.com/8565764/29644897-9723479e-88ac-11e7-988f-e07e5e397cb6.png)

**Comment by gnufied** [comment]
Did you use dynamic provisioning via storageclass for provisioning the PV? I am saying that because - your PV has annotation `volume.beta.kubernetes.io/storage-class: slow` . That seems like a suspect.

Unless you are using external nfs provisioner - a default kube deploy doesn't support dynamic provisoning of nfs volumes.

**Comment by wzdnzd** [comment]
Yes,I'm using nfs provisioner,but now it cannot work well though i use the DefaultStorageClass.
![default](https://user-images.githubusercontent.com/8565764/29645556-e14d3cd6-88b0-11e7-84f5-cf6cffa1d121.png)

**Comment by gnufied** [comment]
If you are using nfs external provisioner, then it may be possible that your external provisioner is misconfigured. Any such issue should be opened in that project's repository, not here.

**Comment by wzdnzd** [comment]
It can not work when i use hostPath or nfs but storageclass also.It has no relation with external provisioner.
