### ISSUE TITLE
Validate Docker 17.03

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#51205]
/sig node

**Comment by dims** [comment]
@yguo0905 duplicate of https://github.com/kubernetes/kubernetes/issues/42926 ?

**Comment by yguo0905** [comment]
Sort of. I was going to post the e2e test results for 17.03 here but since this is essentially a patch release for 1.13, maybe I should just update the results in https://github.com/kubernetes/kubernetes/issues/42926.

**Comment by luxas** [comment]
Closing as a dupe then and updating the https://github.com/kubernetes/kubernetes/issues/42926 title
