### ISSUE TITLE
Enable scheduler to handle PD that belongs to multiple zones

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#51232]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
The Kubernetes scheduler has a `VolumeZonePredicate` that is run when evaluating if a particular pod is ok to schedule to a particular node. It looks for a label with the key `failure-domain.beta.kubernetes.io/zone` on the `PersistentVolume` object referenced in the pod. If present, it looks for the same label on the node object. If the node specifies no `failure-domain.beta.kubernetes.io/zone` labels, it is assumed to be regional and compatible. If the node specifies a different zone, then the it is assumed to be incompatible, and the pairing fails with `NoVolumeZoneConflict`. If the node specifies the same zone, it is assumed to be compatible and the paring is approved.

**What you expected to happen**:
In addition to the above, modify the Kubernetes scheduler’s `VolumeZonePredicate` to look for a label with the key `failure-domain.beta.kubernetes.io/zones` in addition to `failure-domain.beta.kubernetes.io/zone` on the `PersistentVolume` object referenced in the pod. If present, it looks for the label on the node object. If the node specifies no `failure-domain.beta.kubernetes.io/zone` labels, it is assumed to be regional and compatible. If the node specifies a zone, and the zone is not one of the zones specified on the `PersistentVolume` then the it is assumed to be incompatible, and the pairing fails with `NoVolumeZoneConflict`. If the node specifies a zone that is specified on the `PersistentVolume` then it is assumed to be compatible and the paring is approved.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Nope

CC @kubernetes/sig-storage-feature-requests

**Comment by resouer** [comment]
One note is equivalence class cache's behavior may be affected a bit by this design change

**Comment by resouer** [comment]
@saad-ali One question is: why should we have another `failure-domain.beta.kubernetes.io/zones` label instead of having multiple `failure-domain.beta.kubernetes.io/zone` in PV? Is it by design of current multi-zone PV object?

**Comment by bsalamat** [comment]
> why should we have another failure-domain.beta.kubernetes.io/zones label instead of multiple failure-domain.beta.kubernetes.io/zone labels in PV?
@resouer Labels are maps. We cannot have multiple items with the same key in a map.

**Comment by resouer** [comment]
@bsalamat Oh I see, it's `map[string]string`, so the format will be like: `failure-domain.beta.kubernetes.io/zones=zone1,zone2,zone3`.

**Comment by resouer** [comment]
If no one is working on this, mind if I take it up? And will also update equivalence class cache part if necessary.

**Comment by justinsb** [comment]
What is the use case for this?  For regional volumes, I was expecting we would set the region but not the zone label on the PV.  Are there clouds where volumes are in a subset of zones in a region?

**Comment by saad-ali** [comment]
> @bsalamat Oh yes, it's map[string]string, so the format will be like: failure-domain.beta.kubernetes.io/zones=zone1,zone2,zone3?
> 
> But it seems illegal ... I mean, how can we map multiple values to one key?

@resouer The reason I suggested a new label `failure-domain.beta.kubernetes.io/zones` was so that the meaning remains very explicit. When it sees `zones` Kubernetes knows and expects more than one zone. When it sees `zone` it knows and expects a single zone. But I don't feel very strongly about it, and am perfectly ok with reusing the existing `failure-domain.beta.kubernetes.io/zone` field and making the value a comma delimited list.

> Maybe new API filed is needed in PV?

For now I want to expand the beta functionality to support this case (resources that can exist in multiple, but not necessarily all, topological segments). I'm working on coming up with an end to end story for how to handle arbitrary topology across Kubernetes objects including PV, PVC, Node, etc. Will share that once it's more flushed out.

> What is the use case for this? For regional volumes, I was expecting we would set the region but not the zone label on the PV. Are there clouds where volumes are in a subset of zones in a region?

In GCE/GKE we are experimenting with volumes that are accessible from multiple zones but not necessarily all zones in a region.

Sending out PR shortly. Keep an eye out.

**Comment by saad-ali** [comment]
Closed with https://github.com/kubernetes/kubernetes/pull/51667.

Ended up going with a underscore delimited list, which is ugly but works for now. See https://github.com/kubernetes/kubernetes/pull/51667#discussion_r136513111 for details.
