### ISSUE TITLE
"notReady" toleration should be "not-ready"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#51246]
Almost all `foo.com/something` style strings use dashes, rather than javascript names.  `not-ready` vs `notReady`.

@davidopp @bsalamat

**Comment by luxas** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by resouer** [comment]
Thanks @luxas for notification, a quick fix is submitted.

**Comment by luxas** [comment]
The PR here isn't merged yet. Can we make that happen please?
We're still in alpha, so should be ok

**Comment by luxas** [comment]
Should I add the v1.8 milestone to this issue?

**Comment by resouer** [comment]
@luxas Hope so. We are pending in #51266, need approve from @lavalamp

**Comment by gmarek** [comment]
I opened #52264 with safe changes. 

"not-ready" change needs to be discussed more, as it's a breaking change. I believe it's best with fixing that to the time we'll be moving to beta, as we'll need to do another breaking change, i.e. remove 'alpha' from the key.

**Comment by timothysc** [comment]
Aren't we doing this at the 11th hour?  Is this going to hit 1.8?

**Comment by jbeda** [comment]
Strings like this that are part of the core API should be part of a design doc that is formally reviewed by an API group.  We need to find ways to catch this stuff earlier.  

We should also have an evolving API style guide that lists stuff like this.

/cc @kubernetes/api-approvers

**Comment by resouer** [comment]
Thanks @jbeda , let me make some summary:

1. A quick fix for 1.8 is #52264, will be merged soon.

2. The final fix is  #51266, we are collaborating to reach a final solution and it's not target 1.8

**Comment by smarterclayton** [comment]
Agree with Joe, can someone open a PR to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#label-selector-and-annotation-conventions that documents that taint names should follow the naming conventions for annotations?
