### ISSUE TITLE
Available fieldRefs inconsistent in Downward API

### ISSUE THREAD

**Issue by jamesawebb** [kubernetes/kubernetes#51241]
/kind bug
/sig api-machinery

**What happened**:
The availability of Pod and Container fields in the downward API depends on the method used to expose these.  For example, using `DownwardAPIVolumeFile`, `status.hostIP`, `spec.nodeName` and other similar fields are not available, however these fields are available using `EnvVarSource`.

**What you expected to happen**:
I would expect the availability of fields would be consistent regardless of the method used to expose them.

**How to reproduce it (as minimally and precisely as possible)**:
From the [documented example](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#store-pod-fields), try to expose a `fieldPath` value of `status.hostIP` or `spec.nodeName`.

**Anything else we need to know?**:
Relevant API documentation:
- https://kubernetes.io/docs/resources-reference/v1.7/#downwardapivolumefile-v1-core
- https://kubernetes.io/docs/resources-reference/v1.7/#envvarsource-v1-core

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: `GCP`

- OS (e.g. from /etc/os-release):
```
BUILD_ID=9460.64.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=efee0d7cfca9bf17817d7b5d796b56fa75c3b217
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=59
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=59
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
Linux gke-my-cluster-default-pool-759fcf29-97lh 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```

**Comment by resouer** [comment]
I will take a look at this, seems to be a bug.

**Comment by resouer** [comment]
This is not bug, this is a know issue and has TODO in https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/volume/downwardapi/downwardapi.go#L237

**Comment by resouer** [comment]
The main blocker I can think of is that we have no sync between volume reconciliation (in volume controller) and kubelet `syncPod`. So during downwardAPI setup, we have no easy way to get info  about the pod status (e.g. pod IP). 

But I doubt if that worth fix since ENV has already exported enough information. I even doubt if we should keep downwardAPI volume in the future.

@saad-ali  WDYT?

@jamesawebb1 Is your use case prefer volume than env for some reason?

**Comment by jamesawebb1** [comment]
Not at all.  I don't have any pressing need for this - I merely noticed the inconsistency.

**Comment by andyleap** [comment]
If this isn't going to be fixed, then you should really fix the documentation that clearly states it is possible: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api
