### ISSUE TITLE
DeploymentRollback: Lack of validation to name of deployment in url and that in request body 

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#51259]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
when making a regular rollback action to a deployment, I happend to make the deployment name in URL a wrong one, that is, the deployment in request url is different from that in request body, however, I still get a response of success:

_curl http ://127.0.0.1:8080/apis/extensions/v1beta1/namespaces/default/deployments/**compare-deployment**/rollback -X POST -d '{"kind": "DeploymentRollback", "apiVersion": "extensions/v1beta1", "name": "**nginx-deployment**", "rollbackTo": {"revision": 1}}' -H "Accept: application/json, */*" -H "Content-Type: application/json"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Success",
  "message": "rollback request for deployment \"nginx-deployment\" succeeded",
  "code": 200
}_

**What you expected to happen**:
get a failure response that remind me the error

**Anything else we need to know?**:
I tried to fix the issue by adding corresponding judgement in validation, but found that I could not get data in request url when it goes to validation logic.

Adding the judgement to addmision-controller might be a possible way, but I did not find proper position to place it in existing addminsions.

Adding a new addmision just for the judgement seems improper either.

So, any ideas about the issue?

**Comment by lichuqiang** [comment]
cc/ @kubernetes/sig-apps-misc

**Comment by enisoc** [comment]
cc @janetkuo

**Comment by janetkuo** [comment]
One way to achieve this is to add a create strategy for rollback subresource. However, we're deprecating `deployment/rollback` in 1.8. 

@kargakis

**Comment by kargakis** [comment]
Yeah, not worth fixing if we are removing the endpoint.

**Comment by renerchen** [comment]
Does it fix, I have the same problem! And there is another unexpected response. When I rollback a deployment with an non-existent revision, it  responses following:
{
"kind":"Status",
"apiVersion":"v1",
"metadata":{},
"status":"Failure",
"message":"rollback request for deployment "dzion-decompose-new" succeeded\",
"code":200
}

**Comment by lichuqiang** [comment]
Not sure, as @janetkuo said, `deployment/rollback` would be removed, I think the change should have been merged in since it's for v1.8, maybe you can compile it from master branch and have a try
