### ISSUE TITLE
Errors returned by some validation functions may be wrong

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#51256]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In some validation functions, such as `validateContainerResourceName(...)`, `ValidateResourceQuotaResourceName(...)`,  value returned may be wrong.
When `validateResourceName(...)` return some errors and `len(strings.Split(value, "/")) != 1`, we may just return `field.ErrorList{}`, that is not expected

**What you expected to happen**:
return correctly

**Comment by lavalamp** [comment]
Can you clarify "wrong"?
