### ISSUE TITLE
ImageGC:  capability to switch off the function of ImageGC

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/kubernetes#51268]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature
> /sig kubelet

**What happened**:
The kubelet will GC the images on the node to free space when the used space reaching the percent ot the high-threhold(90% as default), but when the containers are not just managed by kubernetes(such as managed by swarm together) and not wished to be GCed by kubelet, I found we can not close the GC function by the flag of image-gc-high-threshold.
**What you expected to happen**:
add one switch to close the function of imageGC in specific senario:
when the flag  image-gc-high-threshold is set as 0, we should not GC the images on the node, just record one warning event to kube-apiserver
Or add another switch flag to close the whole function of imageGC
**How to reproduce it (as minimally and precisely as possible)**:
run kubernetes with several nodes, and test with making the  inode all consumed of the nodes then the kubelet can triggle the GC to delete the oldest images on the node regardless the kind of them.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by CaoShuFeng** [comment]
What happens when --image-gc-low-threshold and --image-gc-high-threshold are both set to 100 ?

**Comment by jiaxuanzhou** [comment]
@CaoShuFeng 
when both set to 100, image GC will still delete one image to release space
as it always runs into the logic `freed, err := im.freeSpace(amountToFree, time.Now())` and delete image in logic  of func ` freeSpace(bytesToFree int64, freeTime time.Time) (int64, error)`
