### ISSUE TITLE
Why "pull-kubernetes-e2e-gce-etcd3" reports SUCCESS even with multiple test failures

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#51269]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/sig testing
/priority failing-test
/kind bug

**What happened**:
Noticed that [fpull-kubernetes-e2e-gce-etcd3](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-etcd3) reports SUCCESS for some PRs with failing testcases.

* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51258/pull-kubernetes-e2e-gce-etcd3/49636;
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50559/pull-kubernetes-e2e-gce-etcd3/49628/;
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51266/pull-kubernetes-e2e-gce-etcd3/49626/

**What you expected to happen**:
Reports **FAILURE** when testcases failed.

**Comment by dims** [comment]
See `FLAKE_ATTEMPTS`, if we fail a test we try again

https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=FLAKE_ATTEMPTS&type=

More info, look for `--flakeAttempts` in http://onsi.github.io/ginkgo/
