### ISSUE TITLE
HostPath volume should not call nsenter directly

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#51273]
https://github.com/kubernetes/kubernetes/pull/46597 brought us HostPath volume plugin that scans the host filesystem using direct calls or wrapped with nsenter when kubelet runs in a container.

IMO, volume plugins should not care much if they run in a container or not, access to files / directories should be handler either by `VolumeHost` or `mount.Interface`. Especially `mount.Interface` has an implementation that knows if it runs in a container and calls nsenter when necessary.

`mount.Interface` already has [method](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L66) to probe if a file is a device or not, so it could be extended to check for other types of special files and `mkdir` that HostPath needs. `mount.Interface` is not a public interface so we can refactor it as we want.

/kind bug
/sig storage
cc @dixudx

**Comment by dixudx** [comment]
@jsafrane As we discussed, I would cover this part.

**Comment by jsafrane** [comment]
thanks a lot!

**Comment by dixudx** [comment]
> `mount.Interface` already has [method](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L66) to probe if a file is a device or not

@jsafrane For [PathIsDevice in nsenter_mount.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/nsenter_mount.go#L275-L279), I don't think the implementation is right. We should check this in mount namespace using `nsenter`, directly calling `os.Stat` to get the file info is wrong. WDYT? Also the same issue of [`DeviceOpened`](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/nsenter_mount.go#L267-L273).

**Comment by jsafrane** [comment]
We in OpenShift run kubelet in a container that has host's `/dev` mapped to the container's `/dev`. How do other people run it?

Maybe we could add this requirement to description of NsMounter. Or fix `PathIsDevice` to check `/rootfs/<path to device>`, because mounting host's root to `/rootfs` is already mandatory. IMO we should avoid unnecessary `exec`.

**Comment by dixudx** [comment]
> Maybe we could add this requirement to description of NsMounter. Or fix PathIsDevice to check /rootfs/<path to device>, because mounting host's root to /rootfs is already mandatory. IMO we should avoid unnecessary exec.

Leave it open here.

Will resolve this after finishing the main part of refactoring.
