### ISSUE TITLE
kubelet is ignoring flags set (--runtime-request-timeout and --volume-stats-agg-period)

### ISSUE THREAD

**Issue by lindsaylandry** [kubernetes/kubernetes#51275]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
It seems that kubelet is ignoring flags that I have set.

I have set kubelet flags `--runtime-request-timeout=10h` and `volume-stats-agg-period=10h`. Defaults are `--runtime-request-timeout=2m` and `volume-stats-agg-period=1m`
**What you expected to happen**:
I expect `du -s` to be running every 10h and not getting killed if taking longer than 2m

**How to reproduce it (as minimally and precisely as possible)**:
Full command:
```/usr/local/bin/kubelet --allow-privileged=true --cgroup-root=/ --cloud-provider=aws --cluster-dns=100.64.0.10 --cluster-domain=cluster.local --enable-debugging-handlers=true --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5% --hostname-override=ip-172-29-41-36.ec2.internal --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin-mtu=9001 --network-plugin=kubenet --node-labels=kubernetes.io/role=node,node-role.kubernetes.io/node= --non-masquerade-cidr=100.64.0.0/10 --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --pod-manifest-path=/etc/kubernetes/manifests --require-kubeconfig=true --runtime-request-timeout=10h --v=2 --volume-stats-agg-period=10h```

**Anything else we need to know?**:

I have set kubelet flags `--runtime-request-timeout=10h` and `volume-stats-agg-period=10h`. This is due to the fact that we have large containers (about 2GB in size) and running `du` on all of them takes up a lot of cpu and memory. I was trying to see if we could run volume stats less often and not have them time out after 2m (default for runtime-request-timeout)

When I look in `journalctl -ru kubelet.service` I see the following:

`Aug 15 19:56:18 ip-172-29-41-36 kubelet[1654]: I0815 19:56:18.611572    1654 fs.go:481] killing cmd [nice -n 19 du -s /var/lib/docker/overlay/9e583fdcb333aa38cc23798700e519b3c99b8eb4af21e5aa0b3aa5e7e6fddd85] due to timeout(2m0s)`

I also see that `du -s` is still running about every minute when running `top` and `ps`

**Environment**:
- Kubernetes version (use `kubectl version`): `kubelet --version = Kubernetes v1.7.0`
- Cloud provider or hardware configuration**: AWS t2.medium boxes
- OS (e.g. from /etc/os-release):
```PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`): `Linux ip-172-29-41-36 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux`
- Install tools: kops
- Others:

**Comment by lindsaylandry** [comment]
Correction: 2m is the default timeout, not 2s

**Comment by zjj2wry** [comment]
@lindsaylandry maybe this is kubelet issue not cli? :)

**Comment by lindsaylandry** [comment]
could be, should I reassign?
/sig kubelet

**Comment by sjenning** [comment]
```
kubelet[1654]: I0815 19:56:18.611572 1654 fs.go:481] killing cmd [nice -n 19 du -s /var/lib/docker/overlay/9e583fdcb333aa38cc23798700e519b3c99b8eb4af21e5aa0b3aa5e7e6fddd85] due to timeout(2m0s)
```

This message comes from cadvisor.  Stats are not currently collected via the CRI and, therefore, are not subject to `runtime-request-timeout`.

The 2m timeout on disk stat collection is hard-coded in cadvisor:
https://github.com/google/cadvisor/blob/master/container/common/fsHandler.go#L55

**Comment by yujuhong** [comment]
> This message comes from cadvisor. Stats are not currently collected via the CRI and, therefore, are not subject to runtime-request-timeout.

That's correct. These flags do not apply to stats collection.

**Comment by lindsaylandry** [comment]
is there a way to turn this off for large images? Also is cadvisor subject to running as often as `--volume-stats-agg-period` is set?

**Comment by Eyjafjallajokull** [comment]
Please confirm if `--volume-stats-agg-period` kubelet option is related to log message `fsHandler.go:131] du and find on following dirs took`.

I have similar issue. I'm running 10-20 pods with 2gb containers (a lot of files) and `du -s` is eating all available iops. Was trying to limit `du` calls by setting `--volume-stats-agg-period`, but seems it has no effect. 

- kubernetes 1.8.1
- aws cloud
- ebs gp2 volume 400gb, 1200iops
