### ISSUE TITLE
Sandbox image lookup uses creds from docker config only; other credential providers are ignored

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#51293]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

We have a private registry configured (where all images including the sandbox one), are hosted. The registry credentials are being pulled by one of k8s credentials providers ([rancher](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/rancher/rancher_registry_credentials.go))

 With Kubernetes 1.7 sandbox image failed to be pulled with the following error message:

```
 unable to pull sandbox image \"<registry name>/google_containers/pause-amd64:3.0\": Error response from daemon: {\"message\":\"Get https://docker.fmr.com/v2/google_containers/pause-amd64/manifests/3.0: unknown: Authentication is required\"}"
```

Looks like with this [commit](https://github.com/kubernetes/kubernetes/pull/46236/files) only creds from docker config are being evaluated on the sandbox image pull 

**What you expected to happen**:

Sandbox image pull should be attempted using credentials returned by not just the basic docker credential provider, but other credentials providers registered in the system.

**How to reproduce it (as minimally and precisely as possible)**:

1) Register private repo credentials with one of the k8s credential providers (we've tried with rancher). Configure the `pod-infra-container-image` to use the image from the the private repo.
2) Make sure you are not logged in to this private repo on the kubelet host
3) Try to create a pod. Sandbox image pull will fail with an error mentioned above.

**Anything else we need to know?**:

Non-sandbox images from the same private repo were able to download correctly using private repo credentials provider.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by resouer** [comment]
@kubernetes/sig-node-bugs

**Comment by feiskyer** [comment]
Confirmed a bug introduced in dockershim. Will file a PR to fix this.

**Comment by feiskyer** [comment]
@alena1108 Could you also verify whether #51870 fixed your problem?

**Comment by alena1108** [comment]
@feiskyer tested against your commits cherry-picked on top of 1.8 beta, the fix seems to work

**Comment by feiskyer** [comment]
@alena1108 thanks.
