### ISSUE TITLE
[GCE kube-up] Remove kube-proxy static pods config

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#51292]
Ref: https://github.com/kubernetes/kubernetes/pull/51227#discussion_r135125827

We should remove kube-proxy static pods configuration in GCE startup scripts in v1.9 and make kube-proxy as DaemonSet the only way to deploy kube-proxy.

/assign
/sig network
/sig cluster-lifecycle
cc @mikedanese

**Comment by MrHohn** [comment]
This is still needed but is blocked by #23225.

/remove-triage unresolved

**Comment by cpanato** [comment]
I think I can try this, does someone can provide some initial direction? like where those configs/manifests are located.
@aojea @jayunit100 @rikatz 

/assign

**Comment by aojea** [comment]
@cpanato I'm not familiar with the problem but seems that there is an option already
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/cluster/gce/config-default.sh#L490-L492

@MrHohn may be more familiar with the issue, or maybe @amwat ??

**Comment by MrHohn** [comment]
@aojea @cpanato Thanks for following up on this! So this issue is mostly related to the GCE startup scripts, where we have two options to install kube-proxy, either via a per-node static pod or a daemonset. Unfortunately we haven't been able to enable kube-proxy daemonset mode by default for gce (I believe there are a few outstanding concerns that block this), that said we shouldn't remove the static pod option just yet.

(Keeping @robscott in the loop.)

**Comment by cpanato** [comment]
thanks @MrHohn for the input, so should we close this issue and open a new open when the removal can be done?

**Comment by robscott** [comment]
Yeah I think this is far enough out that it's probably best to close this for now. Thanks for following up on this!

/close
