### ISSUE TITLE
"NoNewPrivs" is admitted only if the runtime is docker or rkt in kubelet

### ISSUE THREAD

**Issue by miaoyq** [kubernetes/kubernetes#51319]
I tried to add the `NoNewPrivs` support for `cri-containerd`, but the `test-e2e-node` always failed with the error print:
```
E0825 13:03:23.824134     814 pod_workers.go:182] Error syncing pod 29b8ba92-8952-11e7-93c7-5254003d4460 ("alpine-nnp-false-29ab6dfa-8952-11e7-958f-5254003d4460_e2e-tests-security-context-test-4jdbq(29b8ba92-8952-11e7-93c7-5254003d4460)"), skipping: pod cannot be run: Cannot enforce NoNewPrivs: containerd runtime not supported
```

I checked the code of k8s, and found that "NoNewPrivs" is admitted only if the runtime is docker or rkt in kubelet. Related code is as follows:
https://github.com/kubernetes/kubernetes/blob/0cf928f6813741d9699786ee61ec014c90119e2c/pkg/kubelet/lifecycle/handlers.go#L190-L225

Maybe we should define a interface to get the capability of "NoNewPrivs" form runtime-shim.

@Random-Liu @mikebrow

**Comment by Random-Liu** [comment]
@miaoyq Sent #51347 to fix this. Thanks for finding this out!
