### ISSUE TITLE
DeploymentRollback: controller could't find origin revision in rs if it has been Rollbacked once

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#51315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The story is:
I created a deployment and edit it to have a update, then I made a rollback action to revision "1", 
This moment the related RS has a revision of "3" and a history revison "1"

    _deployment.kubernetes.io/revision: "3"
    deployment.kubernetes.io/revision-history: "1"_
Then I repeated the update and rollback step, expecting the deployment to rollback to the origin revision(revison "1")，however， the rollback did not take effect. And I got information as below in controller log:

_"Unable to find the revision to rollback to."_

By tracking the code, I found that when looking for RS to Rollback, controller just consider the revision in revisionAnnotation in RS ，So it did not find target revision in RS , which is in historyRevisionAnnotation in fact.

**What you expected to happen**:
history revision in RS should be taken into consideration when looking for rs to RollBack

**Anything else we need to know?**:
I‘ll have a fix for the issue

**Comment by lichuqiang** [comment]
cc/ @kubernetes/sig-apps-misc

**Comment by janetkuo** [comment]
Deployment rollback is done by passing current revision number of the history (ReplicaSet). In this case, `3` should be passed. `revision-history` just tells you the previous revision number used by this ReplicaSet. 

If you view Deployment history via `kubectl rollout history deployment`, you'll see that replicaset listed as revision 3, instead of 1. 

@kargakis check this user confusion

**Comment by lichuqiang** [comment]
@janetkuo Yes, it's a issue of design specification. Controller would not recognize the origin revisions of RS when it has been rollbacked to before.
While, I think it a little unfriendly that  origin revisions seem to disappear when repeating rollback to same RS.
Besides, I haven't noticed any adverse impact if we support origin revisions of RS in Deployment rollback

**Comment by kargakis** [comment]
We could possibly use the revision history annotation to determine to what RS to rollback to but I don't feel really strong about it.

**Comment by kow3ns** [comment]
@janetkuo @kargakis All of the controllers currently work in the same way with respect to rollback. The behavior is documented. I don't see a strong reason to redesign how rollback works from a UI perspective.

**Comment by kargakis** [comment]
> The behavior is documented

Let's add a link in this issue and close it, then.

**Comment by kow3ns** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment documents the correct behavior
