### ISSUE TITLE
[scheduler] node may lose a few resources when pod delete event is lost

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#51313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Newly registered node, but scheduler thinks this node doesn't have enough resources when schedules pod.

But actually, this node have enough resource for this pod.

**What you expected to happen**:

Schedule pod to this newly registered node successfully when this node have enough resources actually.

**How to reproduce it (as minimally and precisely as possible)**:

In our production env, node doesn't have many resources for many pods, it can only support a few pods, even only one pod.
So this problem happens with higher probability in our environment. 

Node with lots of resources, lose a few resource is not easily to find. 

Suppose there is one pod pod-a, one node node-a and newly registered node node-b. And pod-a is already scheduled to node-a. node-a and node-b have same name.

Reproduce steps:
1. pod-a is deleted, but scheduler lose this delete event.
2. node-a is deleted from etcd for operation reasons or other reasons.
3. node-b register with same name.
4. schedule a new pod and node-b have enough resources for this pod in fact.

**Anything else we need to know?**:

The reason is that :
- pod delete event is lost 
- so scheduleCache is not consistent with real state
- node name may be reused

Restart scheduler will deal this problem.

**Environment**:
- Kubernetes version : k8s 1.3.5

**Comment by jianzhangbjz** [comment]
Whether the lost resource is just equal the resource of the pod on the old node? Have you try it with higher version?

**Comment by shenlanse** [comment]
Yes, this problem still  exists in k8s1.6.

**Comment by ravisantoshgudimetla** [comment]
> pod delete event is lost

@shenlanse Can you please elaborate what you mean by pod delete event is lost?

If the node is deleted manually pod would be deleted as well(In 1.3 nodecontroller would have done reconciliation from node status in 1.5 the behaviour has changed). SchedulerCache gets the data from kubelet. If the kubelet is down(as the node is down), schedulercache's entry should be reconciled almost immediately. Can you provide some logs for 

- kube-scheduler when these events happen.
- kubectl describe podA, podB and node would be helpful too.

**Comment by shenlanse** [comment]
> pod delete event is lost

1. delete pod by kube-apiserver
2. kube-apiserver is down before delete event is sent to watcher.

scheduleCache is not like threadSafeStore, if watch connection is reset, will relist and replace all content of it.  scheduleCache don't. 

> SchedulerCache gets the data from kubelet.

kube-scheduler only communicate with kube-apiserver directly.

**Comment by jianzhangbjz** [comment]
schedulerCache does updates based on Pod events. I think the root issue is the why the kube-apiserver is down.

**Comment by shenlanse** [comment]
@jianzhangbjz we can't be sure any service is never down. What we can do is to try our best to lower the probability. Yeah, it is the root cause, but we must task necessay action to deal with side effects instead of ignoring it.

**Comment by shenlanse** [comment]
@jianzhangbjz In our production environment, this bug happens again. I don't know why the community don't think this is a problem, maybe i don't describe clearly.

Firstly, we have to admit that **delete event can be lost in some terrible circumstance.** I will never say add and update event can be lost, because when Reflector framework relist from apiserver, we can get the final data state and add/update event always have same handler . But delete event is different, lost is lost, even though relist from apiserver, we still can't get the lost delete event. So in k8s, we don't implement our important logic based on delete event.

So the question is why delete event is lost? I think there are many possibilities. In our production environment, it really happens.
(1) network problem: tcp connection err.
(2) kube-apserver restart
(3) etcd lost the event.(etcd2: 1000 history limit; etcd3: compact.)
(4) other reasons.

Also, when reflector relist and watch, scheduler **don't completely reconstruct scheduleCache.**

**Comment by shenlanse** [comment]
This bug has nothing to do with Node name reuse. In short word,

1. pod delete event is lost
2. kube-scheduler don't completely reconstruct scheduleCache when reflector relist and watch

**Comment by shenlanse** [comment]
I am wrong. When relist and watch, DeltaFifo will exec replace func and it will create delete event for ‘delete event lost circumstance’. So from client view, delete event will never be lost.
