### ISSUE TITLE
why need global mount in volume manager

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#51329]
i find it's confused to add global mount to volume manager.The code says it mount device to global mount path then mount the volume to pod specific path.Does it really need global mount?Why not just mount device to pod specific path?I think it also works fine

**Comment by mjaow** [comment]
/sig storage
@saad-ali 
@childsb

**Comment by wongma7** [comment]
because the device can be mounted only once and so if >1 pods want to use it, we then bind-mount it to the pod-specific paths

**Comment by mjaow** [comment]
@wongma7 ,thx i get it
