### ISSUE TITLE
kubectl should detect when it did not receive the entire HTTP response

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#51353]
While this issue happens without this complicated reproduction, here is a sure-fire way to get it.

1. Start a long-running kubectl get.  In this example, I have a cluster with about 2,000 configmaps each around 100KiB.

`kubectl --v=8 get cm -n kube-system`

Once you see these lines

```
I0825 12:02:40.297188    7736 round_trippers.go:383] GET http://127.0.0.1:8080/api/v1/namespaces/kube-system/configmaps
I0825 12:02:40.297197    7736 round_trippers.go:390] Request Headers:
I0825 12:02:40.297203    7736 round_trippers.go:393]     Accept: application/json
I0825 12:02:40.297209    7736 round_trippers.go:393]     User-Agent: kubectl/v1.8.0 (linux/amd64) kubernetes/04b2c29
```

Press `^Z`, then type `sleep 60; fg`, and then you'll see...

```
I0825 12:03:44.637250    7736 round_trippers.go:408] Response Status: 200 OK in 64340 milliseconds
I0825 12:03:44.637289    7736 round_trippers.go:411] Response Headers:
I0825 12:03:44.637306    7736 round_trippers.go:414]     Content-Type: application/json
I0825 12:03:44.637319    7736 round_trippers.go:414]     Date: Fri, 25 Aug 2017 19:02:49 GMT
I0825 12:03:52.719783    7736 request.go:816] transformResponse Response Body: 
F0825 12:03:52.719885    7736 helpers.go:119] unexpected end of JSON input
```

What's happening is that the apiserver is hitting [this timeout](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L34), and then it [panics](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L221).  As the code says, this should make it obvious to the client (kubectl) that it didn't get the entire body, because no 0-length EOF chunk gets sent.  I can confirm from using tcpdump that no such chunk gets sent.

However, kubectl doesn't notice this, and instead tries to decode a 0-length Response body, giving the cryptic message.

*What I expected to happen*

1. At the very least, a less cryptic error message like "connected closed".
2. Ideally, this gets detected by the code and we can internally retry, just as if we got, e.g., [408 Request Timeout](https://http.cat/408)

**Comment by mml** [comment]
cc @mengqiy 

Possibly seen here, too: openshift/origin#14396

**Comment by mengqiy** [comment]
Created a PR https://github.com/kubernetes/kubernetes/pull/51381 to detect it.
Further improvement may be retrying when detect connection closure

**Comment by pwittrock** [comment]
@mengqiy closing this since you filed a PR for it
