### ISSUE TITLE
HostPort does not work correctly on Windows nodes

### ISSUE THREAD

**Issue by Techwolfy** [kubernetes/kubernetes#51354]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig windows

**What happened**: I deployed a `microsoft/iis:nanoserver` pod to a Windows host, and configured it to use `hostPort: 80`. However, the host port was assigned to the infrastructure container instead of the application container, and I was unable to access the application through it. NodePort and the container's IP address continued to work when accessed from the node, but were unreachable from other nodes despite a working network configuration.

**What you expected to happen**: Port 80 on the container is exposed to port 80 on the host.

**How to reproduce it (as minimally and precisely as possible)**: Deploy a pod exposing a host port to a Windows node and attempt to access the service via the host port.

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: [Windows](https://kubernetes.io/docs/getting-started-guides/windows/) with manual network configuration.
- OS (e.g. from /etc/os-release): Windows Insider Preview
- Install tools: kubeadm

**Comment by jhorwit2** [comment]
Are you using the CRI? If so are you including the portmap plugin?

**Comment by Techwolfy** [comment]
I'm not using any CNI plugins. The master (Linux) node has `--network-plugin=kubenet`, and the Windows node with the issue has `--network-plugin` unset. The network is configured manually (outside of Kubernetes) on each node.
