### ISSUE TITLE
apiserver should export global timeout as a flag

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#51355]
#51353 explains a problem with kubectl, where it reacts poorly when the apiserver closes the connection due to [timeout](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L34).

That timeout is hard-coded to 60s.  That's probably a fine default, but we have found cases where ordinary requests won't complete in that time.  We should export this as a flag so that cluster admins can crank it up if they find this happening to them.

/sig api-machinery

cc @jpbetz @lavalamp

**Comment by liggitt** [comment]
There should possibly also be separate timeouts for namespaced and unnamespaced operations. cc @smarterclayton

**Comment by jpbetz** [comment]
@sttts, @deads2k I'm reviewing the code now. What's the distinction between `server.Config:MinRequestTimeout` and `timeout.go:globalTimeout` (if any)?

**Comment by jpbetz** [comment]
Current plan:

Introduce a `NonLongRunningRequestTimeout` to `server.Config`, next to `LongRunningFunc`. This will default to 60s and replace timeout.go:globalTimeout

Introduce a `--request-timeout` option to `kube-apiserver`.  Deprecate `--min-request-timeout` and replace it with `--longpoll-request-timeout-min`.

Not totally happy with the naming and a bit worried that if we make the timeouts too complicated it will be a mess. Suggestions welcome.

**Comment by mml** [comment]
I don't have an opinion on  "Deprecate --min-request-timeout and replace it with --longpoll-request-timeout-min.".  I haven't read the code and don't understand the motivation totally.

But, do the two changes have to be bundled together?  Maybe I don't understand how they interact.

**Comment by jpbetz** [comment]
https://github.com/kubernetes/kubernetes/pull/51415 adds the `--request-timeout` flag. I'll follow that PR up with a separate one to rename `--min-request-timeout` to `--long-running-request-timeout-min` so that we have sane names for all our flags.  We will only backport the PR to add `--request-timeout`  to 1.6 and 1.7.

**Comment by mml** [comment]
@jpbetz awesome.  Thanks for separating the changes.

**Comment by mml** [comment]
@jpbetz can we mark this fixed?

/assign

**Comment by dims** [comment]
@jpbetz ping, we need to close this out or move it out of 1.8 milestone. Please let us know

**Comment by mbohlool** [comment]
@jpbetz @mml daily greeting and ping from release team. Can we close this issue? If no, is it still planned for 1.8?

**Comment by lavalamp** [comment]
This appears to have been fixed by @jpbetz.
