### ISSUE TITLE
Add e2e test coverage of kubectl proxy

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#5136]
After converting the update demo tests to Go and making them mimic the README as closely as possible, we found that [running the kubectl proxy was unreliable](https://github.com/GoogleCloudPlatform/kubernetes/issues/5084) and switched to making calls directly to the kubernetes apiserver instead. This significantly increased the reliability of the e2e tests but we lost test coverage of the kubectl proxy functionality (which appeared to be flaky). 

We need to reinstate e2e test coverage for kubectl proxy (either back in the kubectl test or in a separate test) as well as investigate and fix any reliability problems running the proxy itself.

**Comment by lavalamp** [comment]
In what way exactly would the e2e test use `kubectl proxy`?

`kubectl proxy` should be tested in the hack/test-cmd.sh test suite (or replacement thereof).

**Comment by roberthbailey** [comment]
The e2e test would ensure that kubectl proxy actually works on a real cluster. kubectl proxy should certainly be unit/integration tested as well and the intent wasn't to have the proposed e2e test provide full coverage of the proxy functionality, but rather to make sure that the proxy worked end-to-end instead of just working against a mocked out apiserver.

**Comment by smarterclayton** [comment]
This was fixed a while ago, we have e2e tests for it now.
