### ISSUE TITLE
fix user documentation for `extensions/v1beta1` to not include golang type names

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#51362]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/kind bug

the documentation in `staging/src/k8s.io/api/extensions/v1beta1/types.go` does not follow the guidelines for user facing documentation outlined [here](https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#edit-typesgo). Specifically,
> Comments for types should not contain the type name; API documentation is generated from these comments and end-users should not be exposed to golang type names.

An example in extentions/v1beta1 would be the [PodSecurityPolicySpec](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/extensions/v1beta1/types.go#L911)

cc @bgrant0607

**Comment by mattjmcnaughton** [comment]
I'd love to work on this if its still open.

**Comment by jhorwit2** [comment]
It is definitely still open! All yours :D

**Comment by mattjmcnaughton** [comment]
Sweet, I'm on it :)

Just to conform - something like

```go
// DeploymentSpec is the specification of the desired behavior of the Deployment.
type DeploymentSpec struct {
...
}
```

should become

```go
// The specification of the desired behavior of the Deployment.
type DeploymentSpec struct {
...
}
```

**Comment by mattjmcnaughton** [comment]
@jhorwit2, just wanted to ping you re the above comment before I get a start on this. If I don't hear back in the next couple of days, I'll go forward with my best guess and we can chat about it in the pr.

**Comment by jhorwit2** [comment]
@mattjmcnaughton sorry, yeah that looks good.
