### ISSUE TITLE
"Firewall rule should have correct firewall rules for e2e cluster" flakes

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#51379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind flake

**What happened**:
```
test/e2e/network/firewall.go:183
Expected error:
    <*errors.errorString | 0xc420e06260>: {
        s: "incorrect source ranges [10.160.0.0/14], expected [10.100.0.0/14]: found differences: map[10.160.0.0/14:{}]",
    }
    incorrect source ranges [10.160.0.0/14], expected [10.100.0.0/14]: found differences: map[10.160.0.0/14:{}]
not to have occurred
test/e2e/network/firewall.go:166
```

**Anything else we need to know?**:
happened in many PRs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50889/pull-kubernetes-e2e-gce-bazel/12328/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49850/pull-kubernetes-e2e-gce-bazel/12341/#sig-network-firewall-rule-should-have-correct-firewall-rules-for-e2e-cluster
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45294/pull-kubernetes-e2e-gce-bazel/12291/#sig-network-firewall-rule-should-have-correct-firewall-rules-for-e2e-cluster

**Comment by MrHohn** [comment]
@NickrenREN  It seems this specific error (`incorrect source ranges`) is not occurring after 8/26/2017, do you mind closing this issue?

Ref: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=should%20have%20correct%20firewall%20rules

**Comment by NickrenREN** [comment]
@MrHohn  sure, thanks

**Comment by MrHohn** [comment]
Thanks!

**Comment by MrHohn** [comment]
Sorry, just hit this flake again. Reopening.

Ref: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51221/pull-kubernetes-e2e-gce-bazel/13170/

/assign
/reopen

**Comment by MrHohn** [comment]
pull-kubernetes-e2e-gce-bazel is failing consistently on this firewall test: https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-gce-bazel&width=5&sort-by-flakiness=

cc @kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
ah @shyamjvs I think the IP range is changed for the test right?

**Comment by krzyzacy** [comment]
It's affecting gce-etcd3 job as well, hummm - is the k/k pr not get in yet?

**Comment by mml** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51480/pull-kubernetes-e2e-gce-etcd3/51010/

**Comment by mml** [comment]
@kubernetes/sig-network-misc @kubernetes/sig-network-bugs please assign someone to this.

**Comment by shyamjvs** [comment]
I'm working on it - https://github.com/kubernetes/kubernetes/pull/51343

**Comment by mml** [comment]
Thanks @shyamjvs 

/assign shyamjvs

**Comment by ixdy** [comment]
It seems like release-1.6 is busted now. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51551/pull-kubernetes-e2e-gce-etcd3/51177/

**Comment by shyamjvs** [comment]
Also affecting release-1.7 - https://github.com/kubernetes/kubernetes/pull/51177

**Comment by shyamjvs** [comment]
Instead of cherry-picking my change to multiple releases, I have an alternative solution. Let's explicitly set the cluster-ip-range flag for gce-bazel and gce-etcd3 jobs to 10.100.0.0/14.

**Comment by shyamjvs** [comment]
Seems like it won't work - because there's no --cluster-ip-range flag in e2e framework in earlier releases. It's a hard-coded value inside the startup scripts and e2e test.
I'll send PRs for 1.6 and 1.7 changing those values to the new ones.

**Comment by shyamjvs** [comment]
Closing this issue as it's now fixed after merging the last PR in the series (https://github.com/kubernetes/kubernetes/pull/51343).
