### ISSUE TITLE
flexVolume: LVM example broken per #47400

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kubernetes#51407]
cc @chakri-nelluri 

**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
Before #47400 `mount path` was passed to the `detach` call, now the `volumeName` is passed.
The `volumeName` in the [LVM example POD](https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/nginx.yaml) is `test`, but the [LVM flexvolume plugin](https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/lvm#L118) expect the `mount path` or at least we need a way to pass the `volumeID` to the `detach` function.

After #47400 `volumeName` now needs to be unique (change of behavior, that wasn't the case before).

**What you expected to happen**:
It should pass the `mount path` or the `mount dev` (as the [doc says](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md#detach)).

**How to reproduce it (as minimally and precisely as possible)**:

Try deploying the LVM flexvolume example: https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/nginx.yaml https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/lvm

Also see: https://github.com/kubernetes/kubernetes/issues/44737#issuecomment-319982256

**Comment by klausenbusk** [comment]
@kubernetes/sig-storage-bugs
/sig sig-storage

**Comment by chakri-nelluri** [comment]
Thanks @klausenbusk. I will fix the example.

**Comment by chakri-nelluri** [comment]
@klausenbusk I reviewed it. This is not broken. The doc is wrong. Thanks for bringing it to the notice. I will fix the documentation.

Detach call had always been with PV or Volume Name. The commit just changed the variable name to reflect it.

**Comment by klausenbusk** [comment]
> @klausenbusk I reviewed it. This is not broken. The doc is wrong.

You correct, the LVM example does not seems to be broken, I was a little too fast, but the doc is definitely wrong.

> Detach call had always been with PV or Volume Name.

Hmm, I remember a different behavior, but maybe that is before: https://github.com/kubernetes/kubernetes/pull/41804 .

**Comment by leonj1** [comment]
Is flexvolume working in Kubernetes 1.7.1 and 1.7.4 ?
Several team mates have not been able to get the lvm example working.
After some debugging I have verified the driver is called with `init` during kubelet startup and 'getvolumename' when the example POD gets created. Its never called again.
Kubelet startup arguments included `--feature-gates="AllAlpha=true" -v=6 --enable-controller-attach-detach=false`

**Comment by chakri-nelluri** [comment]
No known issues as of yet.
Do you see any failure events in "kubectl get events"? Please feel free to
slack me @chakri-nelluri I can help debug.

**Comment by chakri-nelluri** [comment]
Fix the issue for @leonj1. It was a configuration issue.

**Comment by mingfang** [comment]
@chakri-nelluri The detach doc is still wrong
