### ISSUE TITLE
Implement InstanceExistsByProviderID() for all the cloud providers

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#51406]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What you expected to happen**:
Related to #50985
Since #51087 merged, we should implement this method for all the cloud providers.

**Anything else we need to know?**:
Many cloud providers(like aws, gce etc...) implement ExternalID(), they also implement InstanceExistsByProviderID(), I can fill it soon.
/cc @wlan0 @thockin  @luxas @jhorwit2

/area cloudprovider
/sig cluster-lifecycle

**Comment by jhorwit2** [comment]
Thanks @FengyunPan you beat me to it :)

**Comment by FengyunPan** [comment]
@jhorwit2 Do you means you want to implement them?

**Comment by jhorwit2** [comment]
No, I was just saying thanks for creating the ticket to track it! I was about to do the same after I saw the PR merged.

**Comment by FengyunPan** [comment]
Yeah, I will implement them soon.
