### ISSUE TITLE
[1.7.x] kubenet CIDR update isn't configurable through CRI

### ISSUE THREAD

**Issue by runcom** [kubernetes/kubernetes#51427]
CRI has `UpdateRuntimeConfig` API to update network CIDR. The pod CIDR is the only value received from kube. `dockershim` is the only CRI impl that can actually update the CIDR of `kubenet` via https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_service.go#L302-L313

When using the CRI is impossible to update CIDR in kubenet because we're missing some information which kube should provide us (thus, we won't be able to correctly update the CIDR for kubenet).

This is the relevant code in kube (only dockershim can actually use this) which updates the CIDR: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/kubenet/kubenet_linux.go#L238-L281

We need, at least:

- mtu
- hairpin mode

@feiskyer @kelseyhightower @Random-Liu PTAL, I would hope we could fix this for 1.7.x or having a workaround soon(ish).

**Comment by feiskyer** [comment]
@runcom Does cri-o support kubenet plugin? mtu and hairpin mode params are only for kubenet, not for all CNI plugins.

**Comment by yujuhong** [comment]
> @runcom Does cri-o support kubenet plugin? mtu and hairpin mode params are only for kubenet, not for all CNI plugins.

That's my question too. Why does cri-o use kubenet directly? /cc @freehan

**Comment by cmluciano** [comment]
Should also note that kubenet is slowly being deprecated

xref: https://github.com/kubernetes/kubernetes/issues/38890
