### ISSUE TITLE
Check automatically for standard API convention for JSON field names in godoc

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#51422]
The API conventions require that godoc on external API fields should use the `camelCase` form of the field when referring to it.  We should automate the checking.

Also consider automating the checking of JSON field name -> canonical form of the external name (i.e. field `PathPrefix` should always be `pathPrefix`).  I don't think we have any case where `camelCase(GoName) != jsonFieldName`, but we might need an exclusion

@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
@mbohlool was thinking along the lines of an API style linter, this could be one thing it checks.

**Comment by mml** [comment]
Yes.  That bug is #44005.

**Comment by mbohlool** [comment]
@roycaihw is this the linter you've added?

**Comment by ericchiang** [comment]
Ensuring the proto name is identical to the json name is another check that'd be good to include https://github.com/kubernetes/kubernetes/issues/45183

**Comment by roycaihw** [comment]
@mbohlool The linter in #54887 checks that the JSON field name matches canonical form of the external name. The checking of godoc on external API fields using the camelCase form of the field is also on the plan to be added once we get the API linter framework merged.
