### ISSUE TITLE
[upgrade test failure][sig-api-machinery] Initializers will be set to nil if a patch removes the last pending initializer

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#51429]
Seeing this test failure pretty consistently with kops, to the extent that we can't merge e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kops/3288/pull-kops-e2e-kubernetes-aws/2743/

Based on timing, seems likely to be #51082, although something odd happened in that this failure occurred on that PR but it still merged: https://github.com/kubernetes/kubernetes/pull/51082#issuecomment-325180686

cc @kubernetes/sig-api-machinery-bugs

**Comment by chrislovecnm** [comment]
@justinsb are you looking at this?

**Comment by liggitt** [comment]
Does kops enable the initializer admission plugin?

**Comment by chrislovecnm** [comment]
@liggitt more detail please

**Comment by justinsb** [comment]
@liggitt not yet, but thanks for the nudge ... hopefully this will fix it:                                                                                                                                                                                                              
https://github.com/kubernetes/kops/pull/3289

**Comment by liggitt** [comment]
the field, feature, and e2e tests should be feature gated since they are still alpha... kops e2e should have had to opt into the e2e test. it's ok to add the admission plugin if you want, but I'm also opening a PR to add the gates so it wouldn't have affected kops e2e unless you wanted it to.

**Comment by liggitt** [comment]
> something odd happened in that this failure occurred on that PR but it still merged

@justinsb it appears kops is not running the e2e tests built from the PR branch - I added a feature tag to the e2e tests, and they got omitted from the GCE e2e as I expected, but kops still tried to run them and didn't show the e2e test title change - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51436/pull-kubernetes-e2e-kops-aws/44314/

Where does the kops CI job get the e2es it runs? from the base master branch?

**Comment by liggitt** [comment]
fwiw, the same issue appears to have happened on the PR that added the test that is now failing in kops... kops had a green run on that PR which did not run the tests added in that PR - https://github.com/kubernetes/kubernetes/pull/51082#issuecomment-325245730

**Comment by mbohlool** [comment]
@caesarxuchao friendly ping. this test failure is a release blocker.

**Comment by liggitt** [comment]
this got straightened out... kops added the Initializers admission plugin, and the tests got a feature tag
