### ISSUE TITLE
glbc addon consuming too much memory in large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51433]
The latest run of density test on 5k-node cluster failed due to over-usage of memory by l7-lb-controller (everything else with the test was fine):

```
Expected error:
    <*errors.errorString | 0xc49fbac160>: {
        s: "Container l7-lb-controller-v0.9.6-gce-scale-cluster-master/l7-lb-controller is using 0.626918514/0.15 CPU\nContainer l7-lb-controller-v0.9.6-gce-scale-cluster-master/l7-lb-controller is using 2714.55078125/75 MB of memory",
    }
    Container l7-lb-controller-v0.9.6-gce-scale-cluster-master/l7-lb-controller is using 0.626918514/0.15 CPU
    Container l7-lb-controller-v0.9.6-gce-scale-cluster-master/l7-lb-controller is using 2714.55078125/75 MB of memory
not to have occurred
```

Ref https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/23

cc @kubernetes/sig-network-bugs @kubernetes/sig-scalability-misc @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
We're seeing this error even in 2k-node clusters (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/3):

```
        s: "Container l7-lb-controller-v0.9.6-gce-large-cluster-master/l7-lb-controller is using 0.430255767/0.15 CPU\nContainer l7-lb-controller-v0.9.6-gce-large-cluster-master/l7-lb-controller is using 1147.890625/75 MB of memory",
```

**Comment by shyamjvs** [comment]
From the values above it seems like the memory usage is scaling linearly with the no. of nodes.
@kubernetes/sig-network-misc I'm not too familiar with it's working - could someone confirm if this is as expected?
If yes, I can change the constraints of our density test to scale with the no. of nodes.

**Comment by shyamjvs** [comment]
cc @bowei

**Comment by smarterclayton** [comment]
It watches ingress, node, service, and pods and so memory usage will be
proportional to the decoded in memory size of those objects (pods are
usually 1.5-2x their protobuf serialized size in memory, but can be much
larger).

**Comment by wojtek-t** [comment]
As @smarterclayton wrote, this is expected. We should tweak the test.

**Comment by shyamjvs** [comment]
Sent out the above PR fixing it. Thanks for the info.

**Comment by gmarek** [comment]
A thought - we should have documented "normal" in memory sizes of objects for each type. It'd make easier to estimate supposed memory usage (here .6MB per Node sounds quite a lot for me if we assume 30 Pods/Node). Also we don't create any ingresses in the test...

**Comment by shyamjvs** [comment]
@smarterclayton @wojtek-t Maybe we should consider moving the l7-lb controller to controller-manager given that it is doing such heavy watches (i.e underlying stores of nodes and pods can be quite big). We'll save with shared informers. WDYT?

**Comment by wojtek-t** [comment]
This is google-specific, so definitely not now.
Once we will get to the world where every cloud-spefic providers are extracted to cloud-controller-manager and we will have the one that is specific to Google, the probably yes.

**Comment by shyamjvs** [comment]
> This is google-specific, so definitely not now.

Makes perfect sense.

> Once we will get to the world where every cloud-spefic providers are extracted to cloud-controller-manager and we will have the one that is specific to Google, the probably yes.

Curious if the plan is to have separate controller-manager for cloudprovider or adding it as a part of current one (by some registration or sth)? 2nd one seems more tempting wrt resource usage.

**Comment by wojtek-t** [comment]
There will be two separate binaries.
