### ISSUE TITLE
Local volume mixup when new node created with same name

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#51431]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig storage

**What happened**:
In GCE/GKE, the nodes are managed by instance groups, which causes nodes to get recreated with the same name, but different UID.

This causes inconsistency with local PVs.  The local static provisioner marks PVs with the node UID, so on the new node, it will not create/delete any PVs for the old node.  However, pod scheduling + volume mount only looks at the node name, so your pod will get scheduled on the new node with the old PV, but all the data will be gone (since it's a new node with new disks).  In addition, the provisioner will create new PVs for the new disks, so other applications are free to bind and use those new PVs.  Then you could end up having 2 pods use the same disk, which is very bad.

I think this could be solved in one of these ways:
1. Make node UID part of the node affinity.  That means we also need to add node UID as a label on the Node object (and I think node team doesn't want to add more labels).  This means that if a node is recreated, the pod cannot be scheduled because the node UID no longer exists.  And we would need to rely on PV tolerations to unbind the PVC and find a new one.

2. Don't use node UID and just use node name.  If you use local PVs on an environment where the local disks are ephemeral, like GCE, then you need to be prepared to lose your data at any time.  On an environment where the local disks are persistent, then it's up to the administrator to make sure they don't accidentally create two nodes with the same name.

**Comment by jsafrane** [comment]
Could we make the daemonset that creates PVs smarter? Now it creates PVs for local disks / directories. Should it sync PVs the other way around and either delete local PVs that don't have corresponding local disk / directory or mark them somehow as "unschedulable"?

**Comment by ianchakeres** [comment]
@jsafrane - I like the idea of the local PV provisioner keeping Kubernetes informed of the actual state of local storage.

@msau42 - There are non-ephemeral situations that will likely run into this issue. For example, on bare-metal a disk or server may be replaced. This replacement is likely to result in a disk mounted at the same location and a host with the same node name.

**Comment by jsafrane** [comment]
@ianchakeres - I think if it's a different disk it should have a different PV. You should include serial number of the disk or something similar in its name.

**Comment by msau42** [comment]
I'm weary of the provisioner deleting local PVs without knowledge of how the user wants to handle this situation.  I prefer the idea of tainting the PVs, and giving the user the ability to specify policies on how to handle those taints.  But we'll need to implement the PV taint/tolerations feature first before we can include any sort of health monitoring here.

Monitoring is also subject to race conditions due to the polling period, so I think some runtime enforcement is needed.  If the disk is formatted with a filesystem or has partitions, then we could include the UUID in the local volume source spec, and at mount time, we can enforce that the UUID matches.  I think for raw block devices, then the ID/serial should be sufficient.  This is something I think we can add in the short term.

@ianchakeres I'm not sure about the scenario about replacing a disk and it would get mounted at the same path.  One of the requirements for local volumes is that your paths need to be stable, even if the ordering of the disks changes.  One of the ways to accomplish that is to have a fstab entry using UUID.  For raw block devices, you can use udev with the serial number.

So say you created a fstab entry using UUID for the mount point.  If you replace that disk, the new one is going to have a new UUID (and no filesystem), so it will not get mounted to the same place.  You would have to explicitly create a new fstab entry with the new UUID and use the same mount point as the old disk.  Instead, I would recommend never reusing the same mount point when adding new fstab entries.

**Comment by ianchakeres** [comment]
@msau42 If local-PVs (or non-local PVs) no longer exist or are inaccessible and we know it, we should reflect this state in kubernetes. I think that deleting unbouncd PV should be an option, and I agree taints are likely a nicer way to indicate that a PV shouldn't be used or bound with new PVCs.

I agree with your statements about race conditions. If in reality a PV is not available then anything attempting to access it will encounter a problem.

Your comments about replacing a disk are valid, and using the UUID is a good practice. Do we have these type of operational recommendations and considerations documented somewhere? 

Similarly, we should encode and automate the correct behaviors into the local-volume provisioner in kubernetes-incubator/external-storage.

**Comment by msau42** [comment]
I'm primarily worried about the race condition between the provisioner deleting the PV, and a PVC binding to it, which is why I think taints is a safer mechanism.  Especially today because there is nothing preventing a PV from being deleted even when it's bound.  Taints could also provide more history since the object still exists.

Can you add the recommendations to the user guide?  There's a best practices section at the bottom.

**Comment by ianchakeres** [comment]
@msau42 - yes I'll add something to the local-volumes user guide.

**Comment by ianchakeres** [comment]
@msau42 - pulling out one of your comments from earlier in the thread.

"""
If the disk is formatted with a filesystem or has partitions, then we could include the UUID in the local volume source spec, and at mount time, we can enforce that the UUID matches. I think for raw block devices, then the ID/serial should be sufficient. This is something I think we can add in the short term.
"""

Did you mean node UID or disk UUID?

**Comment by msau42** [comment]
disk uuid

**Comment by ianchakeres** [comment]
@msau42 - Here is the relate PR for documenting the best practices discussed above.. https://github.com/kubernetes-incubator/external-storage/pull/387

**Comment by msau42** [comment]
Here's an idea I have to solve this.  The end goals are:
* Every new disk should be a new PV, even if the path and the node name are the same.
* Old/stale PVs cannot be mounted and should be marked with an unhealthy state.
* Users can specify how they want to handle that unhealthy state.

In the plugin:
1.  Add a new UID field to the LocalVolumeSpec. 
    1. For filesystem volumes, it's going to be the UUID of the partition.
    2. For block volumes, it's going to be the ID of the device.
2. At mount time, enforce that the UID in the spec matches the hardware

In the provisioner:
1. PV name is currently generated by hashing file name, node name and storage class name.  I think the node name needs to be node ID so that new PVs can be created even if the old PVs still exist.
2. Discovery needs to detect the UID and fill it in the volume spec.
3. Assuming the new master/workers design, if worker for the old node ID stops responding, then taint the old PVs.

**Comment by msau42** [comment]
For the immediate term, we'll fix this GCE issue by making the filesystem mount pts and block devices for local SSDs have a UID in their file name.

Then if a pod tries to mount an old volume, it will get a "path does not exist" error.
