### ISSUE TITLE
Pod with the critical annotation (kube-proxy) was evicted

### ISSUE THREAD

**Issue by andreychernih** [kubernetes/kubernetes#51432]
/kind bug

**What happened**:

kube-proxy pod which has been explicitly marked as critical (with `scheduler.alpha.kubernetes.io/critical-pod` annotation) has been evicted from the node because it was short on disk space. Kubernetes did not make any attempts to re-schedule it after which resulted in cluster outage.

Related: https://github.com/kubernetes/kubernetes/issues/23225

```
$ kubectl describe pod --namespace=kube-system kube-proxy-ip-10-51-40-185.us-west-2.compute.internal
Name:           kube-proxy-ip-10-51-40-185.us-west-2.compute.internal
Namespace:      kube-system
Node:           ip-10-51-40-185.us-west-2.compute.internal/
Start Time:     Thu, 03 Aug 2017 16:19:17 +0000
Labels:         k8s-app=kube-proxy
                tier=node
Annotations:    kubernetes.io/config.hash=7ec3e6c648c18e6348c2b7839744f402
                kubernetes.io/config.mirror=7ec3e6c648c18e6348c2b7839744f402
                kubernetes.io/config.seen=2017-08-03T16:19:12.592302299Z
                kubernetes.io/config.source=file
                scheduler.alpha.kubernetes.io/critical-pod=
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: nodefs.
IP:
Controllers:    <none>
Containers:
  kube-proxy:
    Image:      gcr.io/google_containers/kube-proxy:v1.6.2
    Port:
    Command:
      /bin/sh
      -c
      echo -998 > /proc/$$$/oom_score_adj && kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig --conntrack-max-per-core=131072 --resource-container="" --cluster-cidr=100.96.0.0/11 --master=https://api.internal.dev.jiff.kube --v=2 2>&1 | /usr/bin/tee /var/log/kube-proxy.log
    Requests:
      cpu:              100m
    Environment:        <none>
    Mounts:
      /etc/ssl/certs from ssl-certs-hosts (ro)
      /var/lib/kube-proxy/kubeconfig from kubeconfig (ro)
      /var/log from varlog (rw)
Volumes:
  varlog:
    Type:       HostPath (bare host directory volume)
    Path:       /var/log
  kubeconfig:
    Type:       HostPath (bare host directory volume)
    Path:       /var/lib/kube-proxy/kubeconfig
  ssl-certs-hosts:
    Type:       HostPath (bare host directory volume)
    Path:       /usr/share/ca-certificates
QoS Class:      Burstable
Node-Selectors: <none>
Tolerations:    =:Exists:NoExecute
Events:         <none>
```

**What you expected to happen**:

kubelet should've kept kube-proxy running because it's critical.

**Environment**:

```
# kubelet --version
Kubernetes v1.6.2
# uname -a
Linux ip-10-51-40-185 4.4.79-k8s #1 SMP Fri Jul 28 02:29:53 UTC 2017 x86_64 GNU/Linux
```

**Comment by andreychernih** [comment]
It looks like I don't have a toleration which is required according to https://v1-6.docs.kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

```
[{"key":"CriticalAddonsOnly", "operator":"Exists"}]
```

Could that be the reason?

**Comment by k82cn** [comment]
/sig node

It should be related to kubelet. BTW, how did you deploy kube-proxy? Static pod or DaemonSet?

**Comment by andreychernih** [comment]
I am using kops, it deploys kube-proxy as a static Pod.

**Comment by andreychernih** [comment]
I found that the only way to bring kube-proxy back is to restart kubelet. We will be running the following command periodically on all instances as a workaround:

```
(docker ps|grep kube-proxy > /dev/null) || kill $(pidof kubelet)
```

But I was really surprised to see critical pod has been evicted by Kubernetes.

**Comment by resouer** [comment]
cc @kubernetes/sig-node-bugs

**Comment by dchen1107** [comment]
@dashpole Is this the same issue we fixed before: disk eviction manager evicted the pods too aggressively upon the disk starvation? Shouldn't we already introduce a fix to Kubelet to always admit the static pods since v1.5?

**Comment by dashpole** [comment]
Is the critical pod feature gate enabled on the kubelet?

**Comment by dashpole** [comment]
I checked, and [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L379) was added prior to 1.6

**Comment by andreychernih** [comment]
It turns out kops does not enable this feature gate by default. https://github.com/kubernetes/kops/pull/3345 is pending review. Thanks @dashpole
