### ISSUE TITLE
Deprecate `volume.beta.kubernetes.io/storage-class`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#51434]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
In the Kubernetes 1.6 release, dynamic provisioning has been promoted to stable (having entered beta in 1.4). In 1.6, `StorageClassName` attribute has been added to `PersistentVolume` and `PersistentVolumeClaim` objects and should be used instead of annotation `volume.beta.kubernetes.io/storage-class`. Suggest remove the annotation in 1.8 release . 

/cc @kubernetes/sig-storage-feature-requests 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
/assign @xiangpengzhao 

There is already a PR for it https://github.com/kubernetes/kubernetes/pull/51440

**Comment by xiangpengzhao** [comment]
/close
as per https://github.com/kubernetes/kubernetes/pull/51440#issuecomment-396640304
