### ISSUE TITLE
kube-proxy does not update iptables for default/kubernetes Endpoints

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#51445]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

kube-proxy does not update iptables entry even if default/kubernetes Endpoints object is updated.
Because of that, iptables still routes API request to the non-existing host, which ends up with "no route to host" error.

**What you expected to happen**:

kube-proxy updates iptables entry when default/kubernetes Endpoints is updated.
If I understand correctly, kube-proxy maintains iptables so that it reflects default/kubernetes Endpoints, but sometimes it does not happen.

**How to reproduce it (as minimally and precisely as possible)**:

Initially, my cluster is 1 master and 1 worker nodes.  The IP address of (old) master node is 182.22.22.251.
Then I added a new master node whose IP address is 182.22.22.158.
When new master is fully up (which means it can process API request), I stopped old master.

The default/kubernetes Endpoint is like so:
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2017-07-18T07:36:21Z
  name: kubernetes
  namespace: default
  resourceVersion: "8585463"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: cb1b566b-6b8b-11e7-9243-fa163ec082b5
subsets:
- addresses:
  - ip: 182.22.22.158
  ports:
  - name: https
    port: 443
    protocol: TCP
```

IP address in .subsets.addresses is the address of new master, which is good.
However, after more than 2 days, the iptables of worker process still points to the old master:

```
-A KUBE-SEP-... -p tcp -m comment --comment "default/kubernetes:https" -m recent
  --set --name KUBE-SEP-... --mask 255.255.255.255 --rsource -m tcp -j DNAT
  --to-destination 182.22.22.251:443
```

The iptables of new master node is OK.

https://stackoverflow.com/questions/36337431/kubernetes-newer-api-server-shows-errors-resetting-endpoints-for-master-service suggests similar issues, but if I understand correctly, after deleting old master, default/kubernetes Endpoints becomes stable, and kube-proxy can setup iptables correctly.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: openstack
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1353.8.0 (Ladybug)
- Kernel (e.g. `uname -a`): `Linux worker 4.9.24-coreos #1 SMP Tue May 30 23:12:01 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz GenuineIntel GNU/Linux`
- Install tools:
- Others:

**Comment by tatsuhiro-t** [comment]
@kubernetes/sig-network-bug

**Comment by tatsuhiro-t** [comment]
@kubernetes/sig-network-bugs

**Comment by ncdc** [comment]
This is likely going to be covered by the fix for #22609 / proposal https://github.com/kubernetes/community/pull/939.

**Comment by ncdc** [comment]
Or maybe this is a slightly different issue?

**Comment by tatsuhiro-t** [comment]
I'm not sure, but I think that even if there are some periods that multiple apiservers are fighting to update Endpoints each other, when only one apiserver remains, and the others are stopped, kube-ctl should update iptables according to the latest Endpoints.

**Comment by tatsuhiro-t** [comment]
We ran kube-proxy without --v option, so the log is very quiet.  The only error I saw is it could not report Event to apiserver.

The occurrence of this issue seems to be a bit rare.  But at least we encountered this 2 times.  If they happen, it is quite cumbersome because we have to restart kube-proxy (we run it with systemd) on every machine affected.

I'm wondering that updating annotations of Endpoint object might trigger kube-proxy's processing, but it looks like kube-proxy does the tremendous effort not to update iptables if possible by checking Endpoints change.   If it caches the current Endpoints, then just changing just annotation probably does not work.  Are there any possibility that there is a bug in the detection of changes in endpoints, and caching of them in kube-proxy side?

**Comment by tatsuhiro-t** [comment]
We hit this issue today again.  default/kubernetes Endpoints resource has been updated, but kube-proxy on worker did not update iptables entry, and the pods on that node still point to the unavailable apiserver.  Any chance to look into this?

**Comment by cmluciano** [comment]
@ncdc Should this still be a problem now that https://github.com/kubernetes/kubernetes/issues/22609 is closed and code is merged

**Comment by ncdc** [comment]
@tatsuhiro-t @cmluciano the PR that closed 22609 had a bug, and https://github.com/kubernetes/kubernetes/pull/53809 is open right now to fix it.

However, if the endpoints are getting updated and kube-proxy is failing to update iptables, that is a different issue.

**Comment by cmluciano** [comment]
@tatsuhiro-t can you try this out with the master branch of k8s?

**Comment by tatsuhiro-t** [comment]
Will try.   Do you have any idea that a fix has been landed in master branch?

**Comment by cmluciano** [comment]
I'd like to see if this changes with the fix from https://github.com/kubernetes/kubernetes/pull/53809

**Comment by tatsuhiro-t** [comment]
Does it fix kube-proxy?  What we have observed is that default/kubernetes Endpoint is updated, but kube-proxy does not react to it, leaving iptables stale.

**Comment by cmluciano** [comment]
@tatsuhiro-t Any luck with this?

**Comment by tatsuhiro-t** [comment]
I don't see this issue these days, we use various versions of kubernetes 1.8.x to 1.9.x.
