### ISSUE TITLE
Unify priority functions pattern

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/kubernetes#51455]
**What happened**:
Unify priority functions pattern by using map/reduce pattern. In current priority function implementation, there are two patterns:
- map/reduce
- one whole function

There are still three priority funcions(the whole one) named `CalculateSpreadPriority`  `CalculateInterPodAffinityPriority` `CalculateAntiAffinityPriority` hadn't use map/reduce pattern.

I have completed one refactoring named `CalculateSpreadPriority`  insteaded by `CalculateSpreadPriorityMap/CalculateSpreadPriorityReduce`, and had send a pr(https://github.com/kubernetes/kubernetes/pull/51192) for this.

If all priority functions refactoring done by using map/reduce pattern, we will benifit from:
- simply  `PrioritizeNodes`  process 
- simply priority functions registered process, etc.
- remove all deprecated stuff, e.g `PriorityFunctionFactory`
- unify `RegisterPriorityFunction` and `RegisterPriorityFunction2` 

I am not list all things, just hopes to initiate analyzing.
**What you expected to happen**:

Unify the priority functions pattern if we can.
not sure all priority functions fit to map/reduce pattern in current definition.  but at least `CalculateSpreadPriority`  is definitely the one need to refactor.

/cc @k82cn @resouer @davidopp

**Comment by resouer** [comment]
I prefer to have inputs from @wojtek-t for further discussion

**Comment by wojtek-t** [comment]
Yes - I've always wanted to do that but never really had time for it.

I'm happy to review your PR for spreading, but will not have time before code freeze (and I think we shouldn't rush for 1.8 with that).

The Pod affinity/anti-affinity might be more tricky to do, because they really depend on the whole state of the cluster. But maybe it's actually time to thing and solve pod affinity/anti-affinity more properly.
If someone has time to optimize this (I mean pod affinity/anti-affinity), I will very strongly support this effort (and I'm pretty sure @davidopp will agree with that) and am happy to provide feedback and/or reviews on that.

**Comment by k82cn** [comment]
@wojtek-t , one more input for this is to add an interface for those algorithm to include `Name`, `ConditionChanged`, `Mandatory`, e.g. for kubelet and scheduler, both of them should enforce mandatory predicates; for equal cache, we can ask algorithm whether the condition it care where changed.

**Comment by guangxuli** [comment]
thanks @wojtek-t 
Yes,  the Pod affinity/anti-affinity seems not fit to use map/reduce pattern directly. It will traverse all relevant nodes in the cluster for computing count for one node. I had try to add the nodes list item to matadata or add a new nodes list parameter to current Map function prototype for getting the all nodes info, but all these attempt seems so ugly.

**Comment by wojtek-t** [comment]
> @wojtek-t , one more input for this is to add an interface for those algorithm to include Name, ConditionChanged, Mandatory, e.g. for kubelet and scheduler, both of them should enforce mandatory predicates; for equal cache, we can ask algorithm whether the condition it care where changed.

Sorry, I think I'm not really following. Can you clarify?

> Yes, the Pod affinity/anti-affinity seems not fit to use map/reduce pattern directly. It will traverse all relevant nodes in the cluster to compute count for one pod. I had try to add the nodes list item to matadata or add a new nodes list parameter to current Map function prototype for getting the all nodes info, but all these attempt seems so ugly.

Yes - this one is tricky. I  think no matter how hard we try, if we wan to solve if efficiently, we need to consider all nodes at once. It seems that the workaround here might be to actually precompute results in the precomputation phase, and in real map/reduce functions just grab the results from the metadata that is passed there. I can't see any better option for doing this.

Anyway - if you have any better idea, let me know - I'm open to any suggestions.

**Comment by wojtek-t** [comment]
BTW - this issue is actually a duplicate of long stanging one: https://github.com/kubernetes/kubernetes/issues/24246

We should probably close this and move this discussion there.

**Comment by guangxuli** [comment]
will close this issue, per #24246.
