### ISSUE TITLE
ResourceQuota got something wrong when stop kube-controller-manager for a while

### ISSUE THREAD

**Issue by fankangbest** [kubernetes/kubernetes#51454]
**ResourceQuota got something wrong when stop kube-controller-manager for a while**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I create a resourcequota in default namespace with restriction of 2 pods. Then I create an replicationcontroller with 1 pod and I stop kube-controller-manager  service. I create another two replicationcontrollers,  and then start kube-controller-manager  service。Now I can get three running pods in default namespace。

**What you expected to happen**:
The pod  belong to the third replicationcontroller cannot be created since the quota restriction.

**How to reproduce it (as minimally and precisely as possible)**:
1 Create a resource quota:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: default
spec:
  hard:
    pods: 2
```
2 Create the first replicationcontroller with one pod:

3 Stop kube-controller-manager service

4 Create the second replicationcontroller with one pod

5 Create the third replicationcontroller with one pod

6 Start kube-controller-manager service

7 "kubectl get pods" can get three running pods.
```
NAME            READY     STATUS    RESTARTS   AGE
ubuntu1-dnkfr   1/1       Running   0          41s
ubuntu2-pdwht   1/1       Running   0          3s
ubuntu3-2fjt5   1/1       Running   0          3s
```

**Anything else we need to know?**:
I think the main reason is the ListFuncByNamespace func in /pkg/quota/generic/evaluator.go return empty when kube-controller-manager starts. But I don't know how to fix it.
```
// ListResourceUsingInformerFunc returns a listing function based on the shared informer factory for the specified resource.
func ListResourceUsingInformerFunc(f informers.SharedInformerFactory, groupResource unversioned.GroupResource) ListFuncByNamespace {
	return func(namespace string, options api.ListOptions) ([]runtime.Object, error) {
		informer, err := f.ForResource(groupResource)
		if err != nil {
			return nil, err
		}
		return informer.Lister().ByNamespace(namespace).List(options.LabelSelector)
	}
}
```
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+08e0995", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"not a git tree", BuildDate:"2017-08-16T11:35:23Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+08e0995", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"not a git tree", BuildDate:"2017-08-16T11:35:23Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
VirtualMachine in VirtualBox
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
Linux fankang 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
```
(dockerd -H 0.0.0.0:4243 -H unix:///var/run/docker.sock &>> /var/log/docker.log &)
(etcd --data-dir=/home/fankang/data/etcd150/ --listen-client-urls http://0.0.0.0:4001 --advertise-client-urls http://0.0.0.0:4001 &>> /var/log/etcd.log &)
(kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://localhost:4001 --insecure-bind-address=0.0.0.0 --allow-privileged=false --service-cluster-ip-range=10.100.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,ResourceQuota --client-ca-file=/etc/kubernetes/security/serverkey/ca.crt --tls-private-key-file=/etc/kubernetes/security/serverkey/server.key --tls-cert-file=/etc/kubernetes/security/serverkey/server.crt &>> /var/log/kube-apiserver.log &)
(kube-controller-manager --logtostderr=true --v=0 --kubeconfig=/root/.kube/config &>> /var/log/kube-controller-manager.log &)
(kube-scheduler --logtostderr=true --v=0 --kubeconfig=/root/.kube/config &>> /var/log/kube-scheduler.log &)
(kube-proxy --logtostderr=true --v=0 --kubeconfig=/root/.kube/config &>> /var/log/kube-proxy.log &)
(kubelet --logtostderr=true --v=0 --address=0.0.0.0 --allow-privileged=false --pod-infra-container-image=pause:0.8.0 --cpu-cfs-quota=true --kubeconfig=/root/.kube/config --require-kubeconfig=True &>> /var/log/kubelet.log &)
```
- Others:

**Comment by k82cn** [comment]
/assign

Let me check what happened.

**Comment by k82cn** [comment]
Did not get time to try the steps, but found that the QuotaMonitor should be started after cache sync. Opened #55926 for this, I'll test it :).
