### ISSUE TITLE
Kubernetes won't create service

### ISSUE THREAD

**Issue by startopscollab** [kubernetes/kubernetes#51451]
/kind bug

**What happened**: 

**What you expected to happen**:

kubectl create -f stats-svc.yaml 
Error from server (BadRequest): error when creating "stats-svc.yaml": Service in version "v1" cannot be handled as a Service: [pos 214]: json: expect char '"' but got char '1'

**How to reproduce it (as minimally and precisely as possible)**: I edited existed replication controller file made by Terraform and modified to be service definition. And got above message. Whatever I do, it won't apply the service. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: AWS

- OS (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core) 

- Kernel (e.g. `uname -a`): 3.10.0-514.26.1.el7.x86_64
- Install tools: kops
- Others: I think this is famous yaml to json conversion bug. I still don't know either workaround or fix for this

**Comment by xiangpengzhao** [comment]
Could you please provide `stats-svc.yaml`?

/sig network

**Comment by startopscollab** [comment]
I wanted to provide it but I realized I deleted it. Will write new one and if this occurs again I will post it here.

**Comment by cmluciano** [comment]
/close

stale
