### ISSUE TITLE
daemonset exists 2 pods on one node

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#51464]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
when use kubectl delete one pod pod1 on node, then another pod2 running, pod1 in terminating status. 

**What you expected to happen**:

two pods belong to one daemonset should not exist simutaneously.
**How to reproduce it (as minimally and precisely as possible)**:

kubectl delete pod1
kubectl get pod
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
in many case, this may cause conflict if they use same resource or something else. Why not start a new pod, when the old one is totally deleted? any other considerations?

**Comment by jiaxuanzhou** [comment]
@hzxuzhonghu 
please try kubectl delete pod {podName} --grace-period=0 --force

**Comment by hzxuzhonghu** [comment]
i donot want force delete

**Comment by hzxuzhonghu** [comment]
i donot want force delete

**Comment by hzxuzhonghu** [comment]
link [Ensure that DaemonSet respects termination #51279](https://github.com/kubernetes/kubernetes/pull/51279)
