### ISSUE TITLE
Invalid pod spec can exhaust compute quota

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#51476]
/kind bug

**What happened**:
user submitted a pod with an invalid pod spec via a custom controller.

quota was exhausted as object validation happens after admission.

**What you expected to happen**:
this is a known limitation of the design today, what i would like to do is validate the pod spec in the interim to cover a broader set of invalid pod scenarios to mitigate the impact to users today until such time we can move validation before quota evaluation.

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:
no

**Environment**:
all versions of kube

**Comment by lavalamp** [comment]
I agree this sounds like a bug!

cc @caesarxuchao

**Comment by derekwaynecarr** [comment]
I have a pr in flight to mitigate the issue, but I would like kube 1.9 to
see if we can call validate before and after invocation of admission chain.

**Comment by liggitt** [comment]
Validation now occurs prior to quota admission

/close
