### ISSUE TITLE
pull-kubernetes-e2e-gce-gpu flaking

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#51481]
/kind bug

Got two different failure scenarios:
1. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51281/pull-kubernetes-e2e-gce-gpu/1976/
2. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51281/pull-kubernetes-e2e-gce-gpu/1981/

/cc @jiayingz @mindprince @vishh
Please reassign if the above is wrong. Thanks!

**Comment by vishh** [comment]
Both these failures seems to be test infra issues IIUC. There are no failures in the GPU related logic.

**Comment by mindprince** [comment]
/cc @BenTheElder 

```
W0828 22:05:49.339]     raise RuntimeError('Failed to get shared build location: %s' % err.reason)
```

**Comment by mindprince** [comment]
Seems like it's fixed in https://github.com/kubernetes/test-infra/pull/4223

**Comment by BenTheElder** [comment]
Yes, the PR GPU job had a flake with reusing a build which is a new feature that all e2e jobs will use soon. Hopefully it should be fixed now.

**Comment by BenTheElder** [comment]
Once https://github.com/kubernetes/test-infra/pull/4227 gets picked up things should be fixed. I'm still monitoring this.
/assign

**Comment by BenTheElder** [comment]
I have a PR out to revert using shared builds since rolling out an updated CI image will take a bit longer and the patch to kubetest needs to be rolled out.

**Comment by BenTheElder** [comment]
This is fixed.
/close
