### ISSUE TITLE
replicaset integration tests have to be revamped

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#51484]
**Background**
As part of GA goal of core controllers, unit, integration, e2e, cmd, and upgrade tests of replicaset have to be revamped based on test plan guidelines suggested by @enisoc. This issue lists all necessary tasks for integration tests, including conversion of some unit and e2e tests to the integration tests. Tasks for other types of tests are covered by #52118.

**Integration Test**
- [x] Shorten poll interval (currently 10s - can be 100ms) and use `PollImmediate()` instead of `Poll()`. Check if other integration tests have the same problem.
- [x] Add `TestReplicaSetBasic` with subtests that replace basic behavior unit tests like creating Pods, reacting to events, orphan/adopt, etc.

**End-to-end Test**
- [ ] Convert `testReplicaSetConditionCheck` to an integration test (have to be changed after adding RS conditions).

**Comment by enisoc** [comment]
There are still some items on this, right?

**Comment by crimsonfaith91** [comment]
@enisoc Yes, it is closed when the PR merged as i didn't specify `xref` when referring to this issue. Thanks!
