### ISSUE TITLE
Summary API: [Container|Pod]Stats.StartTime does not contain the expected data

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#51486]
The comments of both [PodStats.StartTime](https://github.com/kubernetes/kubernetes/blob/a64eeb47f6ed4aa2587113793a76878b876809f9/pkg/kubelet/apis/stats/v1alpha1/types.go#L83-L84) and [ContainerStats.StartTime](https://github.com/kubernetes/kubernetes/blob/a64eeb47f6ed4aa2587113793a76878b876809f9/pkg/kubelet/apis/stats/v1alpha1/types.go#L104-L105) indicate that the `StartTime` is timestamp at which the stats were collected.

However, we populate the fields ([here](https://github.com/kubernetes/kubernetes/blob/a64eeb47f6ed4aa2587113793a76878b876809f9/pkg/kubelet/server/stats/summary.go#L365) and [here](https://github.com/kubernetes/kubernetes/blob/a64eeb47f6ed4aa2587113793a76878b876809f9/pkg/kubelet/server/stats/summary.go#L409)) with the [container creation time](https://github.com/google/cadvisor/blob/c2f8191ba9550e302379473faf41d98759d1eff1/info/v2/container.go#L69), which is when the container created.

1. I haven't checked how the `StartTime` is calculated in cadvisor, but this does not seem to incorrect - we are populating the fields with the wrong data.
2. If so, we should probably not populate this data at all since it's been wrong for a long time and nobody cares.
3. Would it cause any issues if we just not set the `StartTime` for both pods and containers in the summary API?

/kind bug
/cc @yujuhong @Random-Liu @dashpole @loburm @piosz

**Comment by yujuhong** [comment]
@piosz do you know which definition of `StartTime` heapster assumes, or does this even concern heapster at all?

**Comment by piosz** [comment]
Heapster use `StartTime` to export cumulative metrics to external sinks and to detect duplicated containers (see https://github.com/kubernetes/heapster/pull/1708). Heapster expects it to be set to container creation time, so IIUC the implementation is correct and we need to fix the comment in the API.

**Comment by yguo0905** [comment]
OK, the comment can be updated. But I guess it's too late to change name to `CreationTime`.

**Comment by piosz** [comment]
@yguo0905 the api is in alpha, we can rename it as a part of graduating the api to beta effort.

**Comment by yguo0905** [comment]
Cool! I can do that after 1.8.
