### ISSUE TITLE
Deprecate debian-based CVM for GCE

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#51487]
The debian-based CVM image is going to be deprecated in September.

We should:
 1. Change the default OS image for GCE cluster setup script. This means that all the GCE CI builds will use the new default OS image.
 2. Add deprecation warning to the cluster setup script if CVM is specified.
 3. Maintain the node e2e test coverage for CVM for 1.8.

/cc @abgworrall @dchen1107 @mtaufen

**Comment by mtaufen** [comment]
The CVM tests were turned off a while ago.
