### ISSUE TITLE
kube-proxy panic because of service sessionAffinityConfig is nil

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#51499]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

upgrading k8s to latest version, but keep the data in etcd, especially the services which session affinity type is ClientIP. Then kube-proxy panic because of service sessionAffinityConfig is nil.

**What you expected to happen**:

backward compatible with latency services.

**How to reproduce it (as minimally and precisely as possible)**:

For example,

```
╰─k8s.io/kubernetes> k get service kubernetes -o json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": "2017-06-28T16:05:11Z",
        "labels": {
            "component": "apiserver",
            "provider": "kubernetes"
        },
        "name": "kubernetes",
        "namespace": "default",
        "resourceVersion": "6",
        "selfLink": "/api/v1/namespaces/default/services/kubernetes",
        "uid": "909a1c62-5c1b-11e7-8a60-4ccc6ab9973d"
    },
    "spec": {
        "clusterIP": "10.254.0.1",
        "ports": [
            {
                "name": "https",
                "port": 443,
                "protocol": "TCP",
                "targetPort": 6443
            }
        ],
        "sessionAffinity": "ClientIP",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

See error logs:

/data/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1616744]

goroutine 48 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x18b5200, 0x2610290)
        /data/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/proxy/iptables.newServiceInfo(0xc4203bc7f0, 0x7, 0xc4203bc7e0, 0xa, 0xc4203bc82a, 0x5, 0xc42075c730, 0xc4203805a0, 0x9eb318c987fc4ed7)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:199 +0x9d4
k8s.io/kubernetes/pkg/proxy/iptables.serviceToServiceMap(0xc4203805a0, 0xc4206e2060)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:875 +0x1c8
k8s.io/kubernetes/pkg/proxy/iptables.(*serviceChangeMap).update(0xc420385620, 0xc420489df8, 0x0, 0xc4203805a0, 0x1ad7000)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:312 +0xb4
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).OnServiceAdd(0xc420385600, 0xc4203805a0)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:645 +0x9a
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0xc420295ad0, 0x1a807c0, 0xc4203805a0)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:225 +0xe8
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).(k8s.io/kubernetes/pkg/proxy/config.handleAddService)-fm(0x1a807c0, 0xc4203805a0)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:182 +0x3e
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc42042ae90, 0xc42042aea0, 0xc42042aec0, 0x1a807c0, 0xc4203805a0)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc4204e2420, 0x1a807c0, 0xc4203805a0)
        <autogenerated>:57 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc4202fd130)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc42000fa98, 0xc420202160)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @gnufied, thanks for reporting this.

**Comment by pineking** [comment]
@m1093782566 I meet the same bug, waiting for your PR #51500 merged ASAP.

**Comment by m1093782566** [comment]
@pineking Sorry...

Currently, I think you can delete service `kubernetes` to work around it.
