### ISSUE TITLE
Unstructured codec's Encode() method mutates object (potential data race)

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#51521]
**What happened**:
Lines 705-706 mutate the object but encode method should probably be only reading the source object. Otherwise it can lead to data corruption in concurrent environment because it is a data race. Users of this method probably do not expect such behaviour and it is not documented.

https://github.com/kubernetes/kubernetes/blob/1b3836d5df302281a9db4b03bdc8fd5079142431/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L696-L715

**What you expected to happen**:
It should not mutate the object but use a temporary one instead.

/kind bug
/sig api-machinery

**Comment by smarterclayton** [comment]
Where did this happen?

**Comment by ash2k** [comment]
It did not happen, I stumbled upon this accidentally when was looking for something else.
