### ISSUE TITLE
There is no kubernetes CI unit test machine for Windows 

### ISSUE THREAD

**Issue by JiangtianLi** [kubernetes/kubernetes#51540]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Currently there is no kubernetes CI unit test machine for Windows. Since the Windows features in kubernetes are growing fast, it is important to set up the Windows CI jenkins test on kubernetes, to prevent build failure and unit test failure for Windows.

**What you expected to happen**:
kubernetes CI unit test machine is set up for Windows.

**Comment by andyzhangx** [comment]
actually there is `/test pull-kubernetes-cross` which will do build test for linux/windows/darwin, but by default it's not open

**Comment by yujuhong** [comment]
Does kubernetes even build natively on windows?

**Comment by JiangtianLi** [comment]
@yujuhong  We build kubernetes windows binary on linux. This issue is about be able to run unit test that requires windows. @andyzhangx  is working on Azure file/Azure disk and the ask here is to have unit test pass besides build pass.

**Comment by kargakis** [comment]
> actually there is /test pull-kubernetes-cross which will do build test for linux/windows/darwin, but by default it's not open

This job will run for every PR that touches any file with a name that satisfies [this regexp](https://github.com/kubernetes/test-infra/blob/0fd217c911778a681f2217b6119415bbc33766a3/prow/config.yaml#L236).

**Comment by yujuhong** [comment]
@JiangtianLi I asked because then you need one job to cross compile the binary, and another job to run tests on Windows. I don't know if this is currently supported by our test framework.

**Comment by jdumars** [comment]
@JiangtianLi do we need to pull this work forward into 1.10 / SIG-Azure?

**Comment by yujuhong** [comment]
> @JiangtianLi do we need to pull this work forward into 1.10 / SIG-Azure?

+1 
Would really like to see some CI tests for windows

**Comment by JiangtianLi** [comment]
@jdumars Please add this to 1.10 sig azure and drive forward. This would definitely benefit development on Windows platform.

**Comment by jdumars** [comment]
Acknowledged.

**Comment by feiskyer** [comment]
@JiangtianLi @jdumars Added to v1.10 milestone.

**Comment by krzyzacy** [comment]
this probably should be sig-azure implementing some provider interface within kubetest, similar with sig-aws did?

https://github.com/kubernetes/test-infra/blob/master/kubetest/kops.go
and 
https://github.com/kubernetes/test-infra/blob/master/kubetest/gke.go
are good references.

**Comment by jberkus** [comment]
adding priority so that we can keep tracking this for 1.10, please update.

/priority important-soon

**Comment by jdumars** [comment]
I am bumping this from 1.10. Let's get this sorted in 1.11 and get SIG Azure on the case.  cc: @khenidak

**Comment by BenTheElder** [comment]
> actually there is /test pull-kubernetes-cross which will do build test for linux/windows/darwin, but by default it's not open

As an aside we've improved this now with `pull-kubernetes-typecheck` which will ensure the code type checks for all the platforms / arches the cross build would do (but is cheap enough to be blocking on all 1.10+ / master PRs), this is a blocking presubmit. 
It should catch windows build failures, which leaves integration / e2e tests.

**Comment by BenTheElder** [comment]
There's now a prototype Prow presubmit on Azure.
https://github.com/kubernetes/test-infra/pull/8024

**Comment by feiskyer** [comment]
@PatrickLang Could you update the current status?

**Comment by PatrickLang** [comment]
/milestone 1.12


I don't think anyone is working on this for 1.11, moving to 1.12.

**Comment by dims** [comment]
@feiskyer is this targeted for 1.12? I don't see any activity

/milestone clear

**Comment by feiskyer** [comment]
@PatrickLang @ritazh Could you update current status for this?

**Comment by PatrickLang** [comment]
Still in the works, we have some PRs open

**Comment by PatrickLang** [comment]
I do see 
https://k8s-testgrid.appspot.com/sig-release-misc has cross-build results published: https://github.com/kubernetes/test-infra/blob/27957efc6e3859d58dceaac9e7cb7ada63410e2f/testgrid/config.yaml#L687

But nothing blocking

**Comment by PatrickLang** [comment]
I just went through this with @spiffxp, @BenTheElder and others in the SIG-Testing meeting today, and we agree we can move this to v1.14. Today, these tests are run in pods within a GKE cluster, which has no Windows capability. We would need to either bring up another cluster and prow deployment to handle non-Linux tests (Mac & Windows). Unit testing is currently a **should** not a **must**. SIG-Windows is continuing to move forward on E2E + Conformance testing for v1.13.

**Comment by BenTheElder** [comment]
We should be able to use a single prow deployment with a seperate build cluster (with not much special in the build cluster), and mark windows jobs as running in that cluster fwiw, we have some things leveraging this today (though with other linux clusters). 

We would need to figure out exactly what jobs need to run and the who and where of the cluster and jobs. 

ref: @kubernetes/k8s-infra-team would possibly be a place to discuss these.

**Comment by BenTheElder** [comment]
There is something for e2e running in CI currently FYI, but it does not work correctly, yet:
https://testgrid.k8s.io/sig-windows#Conformance%20acs-engine%20on%20Azure

Google (sig-node I think?) also has a prototype for e2e here:
https://testgrid.k8s.io/google-windows#windows-prototype

**Comment by yujuhong** [comment]
> Google (sig-node I think?) also has a prototype for e2e here:
> https://testgrid.k8s.io/google-windows#windows-prototype

This is running against a fork to test Windows nodes/containers in GCE. We are working on stabilizing and upstreaming the cluster bring-up changes (`cluster/gce`) so that we can get rid of the fork.

**Comment by yujuhong** [comment]
/remove-lifecycle stale

Unfortunately, this is still true.

**Comment by feiskyer** [comment]
Oh, right. Unit tests are still broken in most packages. @PatrickLang

**Comment by nikopen** [comment]
moving this as it's in the Backlog of the kanban board, feel free to move it back if needed

/milestone v1.15

**Comment by justaugustus** [comment]
@PatrickLang -- can you provide an update on this?

/remove-sig azure
/remove-lifecycle stale
/milestone clear

**Comment by BenTheElder** [comment]
/assign
I'll be sharing a prototype I hacked on in some of my spare time (lol!) soon :-)

**Comment by BenTheElder** [comment]
/unassign
I've got too much going on to get back to this in a reasonable time frame.

**Comment by jsturtevant** [comment]
looks like this got lost but should still be on sig-windows backlog

/reopen

**Comment by andyzhangx** [comment]
I think easiest way to add windows UT is add a github action in k/k, it supports Windows

**Comment by BenTheElder** [comment]
K/K does not currently use actions, and doesn't currently plan to for various reasons. There might be traction in using actions cron (not presubmit) but the release team won't monitor that (see release-blocking-jobs in sig-release).

**Comment by jsturtevant** [comment]
The windows tests are not running anywhere and I found that #99409 was failing. Since the tests are not run regularly many of them may not pass as was the case with `fs_windows_test.go`.

AFAIK the current way to [build the unit tests for Windows is on a Linux ](https://github.com/kubernetes/kubernetes/issues/51540#issuecomment-328245215) machine then run them on a Windows Machine.  

I wasn't able to build k/k on Windows machine using any of the standard ways: `make` fails, and the build scripts in `/build/` don't support Windows.

I did get them to run locally by doing the following, but not sure if there might be issues with this approach?

```
PS C:\projects\go\src\k8s.io\kubernetes> go mod vendor  
PS C:\projects\go\src\k8s.io\kubernetes> cd \pkg\volume\fs\util
PS C:\projects\go\src\k8s.io\kubernetes\pkg\volume\fs\util>go test . -mod=mod       
--- FAIL: TestDiskUsage (0.00s)
fs_windows_test.go:61: TestDiskUsage failed: CreateFile C:\Users\jstur\AppData\Loca\Temp\dir_1850396619/test: The system cannot find the file specified.                                                                                                                                                           FAIL                                                                                                                                                       
FAIL    k8s.io/kubernetes/pkg/volume/util/fs    0.384
FAIL                                                           
```

If we did that in actions (maybe in https://github.com/kubernetes-sigs/windows-testing) and published to a testgrid dashboard would that be a possibility?

**Comment by BenTheElder** [comment]
> AFAIK the current way to build the unit tests for Windows is on a Linux machine then run them on a Windows Machine.

If we're running in CI, we already upload full cross builds, so we can just download and run those. However I don't think go has a good way to pre-build unit tests (IIRC it has to be done binary-per-package?)

@liggitt runs the tests directly with `go test` on linux I think? but officially the `make` tools are doing various things we may want (e.g. supplying non-standard build tags).

> If we did that in actions (maybe in https://github.com/kubernetes-sigs/windows-testing) and published to a testgrid dashboard would that be a possibility?

IMHO that makes sense.

**Comment by jsturtevant** [comment]
/reopen
cc: @claudiubelu @adelina-t 

sig-windows is working to get unit tests working with CI running. A few PR's tracking this work:

https://github.com/kubernetes/kubernetes/pull/110263
https://github.com/kubernetes/kubernetes/pull/110399
https://github.com/kubernetes/kubernetes/pull/110403
https://github.com/kubernetes/kubernetes/pull/110453
https://github.com/kubernetes/kubernetes/pull/110566

**Comment by BenTheElder** [comment]
We had some discussion of possible approaches and tradeoffs at the SIG testing meeting earlier this week (June 14th 2022). 

For anyone following along and interested these get recorded and uploaded to YouTube and the running meeting notes are linked from the community repo in the SIG document.

**Comment by adelina-t** [comment]
@BenTheElder I followed the recording of the community meeting. The options I was considering are at the beginning of this work are:

1. Github actions. The downside of not having testgrid integration is easily mitigated , we have precedent for this in containers that also pushes to testgrid: https://github.com/containerd/containerd/blob/main/.github/workflows/windows-periodic.yml . Basically we format the logs in the appropriate file structure, push to google bucket and testgrid does the rest.

2. Prow. We would be using the kubekins_e2e image with runner.sh and a custom script( in sig-windows-testing repo or wherever appropriate ) to build the appropriate windows vm  and run the tests. This would allow prow to take care of log uploading + testgrid integration. This is how the clusters for e2e windows tests are built with cluster api and works quite well. We already have all the bits and pieces ( az secrets ) in place from the e2e tests runs for windows. This is the approach I am working on for the moment, though I am not completely happy with it.

As for how the test should run, ideally a periodic job until we gain confidence in the windows unit tests. After we can have confidence in it, it can easily get promoted to a presubmit.

**Comment by BenTheElder** [comment]
That sounds right, couple additions / notes:

In addition to 1 & 2 in the call we talked a little about a third option:

3. We could try to extend Prow to schedule to Windows Containers and run unit tests there as prowjob pods. I think this would mostly involve porting the "pod utilities" and setting up a Kubernetes cluster with windows nodes for prow.k8s.io to schedule to. For the latter in github.com/kubernetes/k8s.io we could request a windows node pool in an existing GKE cluster perhaps.

For 1) we can talk to sig-k8s-infra / github.com/kubernetes/k8s.io about how we'd manage the GCS <-> Github actions bit.

Personally I'd +1 any of these approaches. 

I think Prow has deeper integration with the community infra, particularly the merge automation if we're looking to do PR-blocking testing, but I don't want to make this harder than it needs to be.

> After we can have confidence in it, it can easily get promoted to a presubmit.

I would add the caveat that, we're trying to only push things down into running in presubmit / on every push if we've shown that the results are reliable *and* that we're frequently encountering bugs that should've been caught in presubmit.

For example if GPU plugin code is rarely changing then it may not make sense to always test GPU clusters in presubmit vs testing after merge at much less cost and hassle to the project at large, and just ensure that we don't *release* before any occasional bugs are patched. I.E. with a [release blocking job](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md). 

We want to start with getting something to release blocking, and then evaluate if PR-blocking is necessary in addition to release blocking. We're also periodically attempting to re-evaluate if existing PR blocking jobs should be, as Kubernetes PRs receive a lot of heavy, flaky, expensive testing today 😅 

That said, I would not be surprised to learn that windows unit tests were the sort of thing that need to be PR-blocking due to high rate of missing bugs that otherwise would have been prevented, but we should gather evidence first..

**Comment by adelina-t** [comment]
>We want to start with getting something to release blocking, and then evaluate if PR-blocking is necessary in addition to release blocking. We're also periodically attempting to re-evaluate if existing PR blocking jobs should be, as Kubernetes PRs receive a lot of heavy, flaky, expensive testing today 

Yes, that's what I sort of meant, but I got lost in the terminology of stuff :) but yes, totally agree here

**Comment by adelina-t** [comment]
Some PRs concerning this:
* https://github.com/kubernetes/test-infra/pull/26695
* https://github.com/kubernetes-sigs/windows-testing/pull/325

**Comment by jsturtevant** [comment]
The job dashboard is https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

With the other PR's hope seet those turn green. 🚀 

Thanks for all the work! It looks like some of the PR's to fix/add like https://github.com/kubernetes/kubernetes/pull/110864 have found actual issues.

**Comment by BenTheElder** [comment]
Thank you @adelina-t!

Sorry I'm going on vacation for a few weeks and have been working to ensure I'm not leaving anyone blocked but didn't get this one yet.

It looks like we're finally making smooth progress here 🎉

**Comment by jsturtevant** [comment]
I think we can close this. We have the ability to run the tests and have a job now. We are tracking the improvements to make all the unit tests pass in separate PRs.  You can find them searching for `unittest` on our sig-windows dashboard https://github.com/orgs/kubernetes/projects/99/views/1

/close
