### ISSUE TITLE
Remove status.conditions from apps/v1beta2 ReplicaSet

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#51549]
We plan to eliminate conditions from the API, see #7856

ReplicaSet only has one condition: "ReplicaFailure":
* condition status is only set to `True` in the controller code
* condition reason is either "FailedCreate" or "FailedDelete". 
* condition message contains the error returned from `manageReplicas()`

Plan to remove replicaset `.status.conditions` field, use a new status field `replicaFailure bool` to represent the ReplicaFailure condition, and use events to capture last transition time, reason and message. 

@kubernetes/sig-apps-api-reviews

**Comment by kargakis** [comment]
IIRC we already emit events on pod failures. Not sure how useful a single boolean is going to be. The point of having the error message included in the status was that it could be used by clients w/o the need to filter through events.

cc: @smarterclayton @tnozicka

**Comment by kow3ns** [comment]
Also #50798 is relevant.

**Comment by janetkuo** [comment]
I'll just drop conditions altogether as we can add status field later if we need to.

**Comment by smarterclayton** [comment]
Where is the discussion captured that agrees to the conclusions referenced in the linked PR?  Not discussed in sig-api-machinery (that I know of)?

**Comment by smarterclayton** [comment]
#7856 is not a plan, it's a description of a survey.  If it's a plan, it needs to be a plan.

**Comment by janetkuo** [comment]
Closing, as eliminating/deprecating conditions is not a priority anymore https://github.com/kubernetes/kubernetes/issues/7856#issuecomment-335687733
