### ISSUE TITLE
Failing test on alpha CIs: "[sig-auth] Advanced Audit [Feature:Audit] should audit API calls"

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#51556]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/priority failing-test

**What happened**:
`[sig-auth] Advanced Audit [Feature:Audit] should audit API calls` is consistently failing in alpha CIs since 8/25.

Checked [the commit diff](https://github.com/kubernetes/kubernetes/compare/acdf625e4...a235ba4e4), seems likely to be caused by https://github.com/kubernetes/kubernetes/pull/50971.

cc @CaoShuFeng @kubernetes/sig-auth-test-failures 

**How to reproduce it (as minimally and precisely as possible)**:
See https://k8s-testgrid.appspot.com/google-gce#gce-alpha-features&width=5&sort-by-flakiness=

**Comment by ericchiang** [comment]
I can update the test.
