### ISSUE TITLE
bazel build fails on release-1.6 branch

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes#51571]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`make bazel-build` fails on the `release-1.6` branch, and the [bazel-build-1.6](https://k8s-testgrid.appspot.com/google-unit#bazel-build-1.6) job is red.

**What you expected to happen**:

I would expect the bazel-build-1.6 job to be green, and that `make bazel-build` would succeed on the `release-1.6` branch (if using the correct version of bazel).

**How to reproduce it (as minimally and precisely as possible)**:

    $ git clone https://github.com/kubernetes/kubernetes.git
    $ cd kubernetes
    $ git checkout origin/release-1.6
    $ make bazel-build

This is failing as of commit 79cf9963f7a70f40dc29bc3bb880a57d9e3b3ce8 with the messages:

    vendor/github.com/aws/aws-sdk-go/aws/request/request.go:270: undefined: noBodyReader
    vendor/github.com/aws/aws-sdk-go/aws/request/request.go:284: undefined: noBodyReader
    2017/08/29 16:56:25 error running compiler: exit status 1

**Anything else we need to know?**:

All of our kubeadm e2e tests depend on the successful completion of bazel builds, since they use the `.deb` artifacts created during the bazel build. Since the 1.6 bazel build has been broken, the corresponding kubeadm e2e tests haven't even been triggered since [2017-07-26](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6/138). This likely means that the recent 1.6.9 release didn't have any signal for kubeadm's health.

CC @ixdy @kubernetes/sig-cluster-lifecycle-misc

**Comment by ixdy** [comment]
When I updated the rules_go ref in https://github.com/kubernetes/kubernetes/pull/50414, I inadvertently also updated release-1.6 to go1.8.3, which caused the build to fail since the version of `gazel` used on release-1.6 generates BUILD files only for go1.7.

I tried updating the `WORKSPACE` to use go1.7.6, but now I'm running into a weird internal go compiler error (https://github.com/bazelbuild/rules_go/issues/769).

If we build release-1.6 with go1.8.3 this may resolve the issue, though it would not match the non-dockerized build, which uses go1.7.6.

**Comment by ixdy** [comment]
There's a fix in the upstream `rules_go` repo now, but there are a few gotchas:
* `rules_go` at HEAD requires bazel 0.5.4+
* `rules_go` at HEAD requires fixes in our `repo-infra` rules

**Comment by pipejakob** [comment]
@ixdy, as a heads-up, @enisoc is targeting releasing 1.6.10 on September 13th. To make sure we take the appropriate measures, is there any chance that the `release-1.6` bazel build will be fixed by then so we can use the normal kubeadm e2e tests as our health signal? Or should we be preparing for manually QAing kubeadm for that release? Thanks!

**Comment by ixdy** [comment]
@pipejakob I think if we merge https://github.com/kubernetes/kubernetes/pull/52432 + https://github.com/kubernetes/test-infra/pull/4547 this should fix.

**Comment by luxas** [comment]
Did this get fixed?

**Comment by ixdy** [comment]
@luxas no, #52432 is waiting for lgtm/approval.

**Comment by luxas** [comment]
Closing this as last two runs were green. Reopen if you disagree ;)
