### ISSUE TITLE
How to deal with `Unknown` pod's volume？

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#51597]
Now the attach_detach_controller have a feature that can decide to detach the volume for `Terminating` Pod. 
Here is the function used to check the pod is `terminated` or not 
```go
func IsPodTerminated(pod *v1.Pod, podStatus v1.PodStatus) bool {
	return podStatus.Phase == v1.PodFailed || podStatus.Phase == v1.PodSucceeded || (pod.DeletionTimestamp != nil && notRunning(podStatus.ContainerStatuses)
}

func notRunning(statuses []v1.ContainerStatus) bool {
	for _, status := range statuses {
		if status.State.Terminated == nil && status.State.Waiting == nil {
			return false
		}
	}
	return true
}
```
But we can met the issue in the following scenario:
1. Node become `NotReady`
2. Node controller wait for minutes and then do pod eviction
3. The pod maybe not get deleted(Our pod has finalizer and can't be removed in this scenario), then pod will become `Unknown` status.
4. In this status, the pod have "deletionTimestamp" field, but pod's `phase` is `running`  and every container  state is `running` , the pod will hold this volume, as we can see from the code that the function `IsPodTerminated` will return false for this pod.

I think there should be a better way to handle this situation.

**Comment by wenlxie** [comment]
@jingxu97 @dims @gnufied Can you help to have a check?

**Comment by dims** [comment]
@wenlxie : Can you create a PR with the suggestion?

**Comment by jingxu97** [comment]
@wenlxie If the pod is unkown status, how could controller determine what is the correct action for this pod? 
In you scenario, can I ask what is the reason you have finalizer causing pods cannot be removed? Will new pods be created to replace the old one in this case?

**Comment by wenlxie** [comment]
@jingxu97  

1. Sorry for mention about the finalizer, it makes  some  confusion. Actually, if there is no finalizer, the pod will stuck at `Unknown` status too, Because  Kubelet  not report the container status and not do `delete` action.

2. If the pod belongs to an RC, controller  will create another pod , but the old pod holds the volume and then the new pod will not get the volume. 
It  will block the controller to create another pod.
