### ISSUE TITLE
Evaluate how to allocate resources on kubelet to fail fast during pod creation

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#51592]
During the review of PR https://github.com/kubernetes/kubernetes/pull/51209, @vishh mentioned that "Ideally, allocation of resources would happen as part of pod creation so as to fail pods during admission whose extended resource request cannot be satisfied by the kubelet due to any reason.
For example, a device may have just turned unhealthy and the scheduler may not have noticed it. Note there can be multiple entities scheduling pods on to nodes.
Node level admission control is the last line of defence against state propagation issues in k8s.
If not for allocation during pod admission, I'd at-least like to see an admission handler (we have quite a few of them), that validates that devices are available to satisfy a pod's request. Essentially a dry run of the logic here."

Filing this issue to follow up on this.

**Comment by lichuqiang** [comment]
@jiayingz @vishh 
I would like to help add  a node level admission handler for resource allocation if ok.
But here I have a doubt, that if we need to move the logic of updateAllocatedDevices in device_plugin_handle(that is: recalculate allocated resources with activepods retrieved everytime new pod comes in) here, or it's ok to process with current data?
