### ISSUE TITLE
Cloud Controller Manager updating ProviderID blocked by validation rule

### ISSUE THREAD

**Issue by karataliu** [kubernetes/kubernetes#51596]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Follow up for #49836 , #50730 

With the change for cloud-controller-manager updating providerID, the node.spec.ProviderID is to be updated. But it will fail later in node update call:
```
E0830 05:54:08.576076   21643 node_controller.go:374] Node "k8s-agentpool1" is invalid: []: Forbidden: node updates may only change labels, taints, or capacity (or configSource, if the DynamicKubeletConfig feature gate is enabled)
```

Should also check validation rule:
https://github.com/kubernetes/kubernetes/blob/12d73c31a97188286e7f4c8a3aec7fcd38a76a83/pkg/api/validation/validation.go#L3432

By adding following line will do the trick.
```
oldNode.Spec.ProviderID = node.Spec.ProviderID
```

But this will also allow users to manually edit node's providerID

Shall we enforce that only cloud-controller-manager can update the providerID?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by karataliu** [comment]
cc @andrewsykim @luxas

**Comment by andrewsykim** [comment]
@karataliu being able to update `node.Spec.ProviderID` seems pretty reasonable to me. Can you get a PR in for that since we're close to code freeze?

**Comment by andrewsykim** [comment]
cc @jhorwit2 @prydie @wlan0

**Comment by karataliu** [comment]
@andrewsykim I found this issue when validating against a cluster running azure cloud provider, could you please also check whether it is the same case from you side?

`providerID` serves somewhat like an identity for nodes, thus it wouldn't expect arbitrarily updating. A compromise proposal is to allow updates when the value is not set. This gives controller manager a chance to set it during node register.

Created #51761 as a fix proposal.

**Comment by andrewsykim** [comment]
@karataliu thanks for the patch, I think I'll have some time this weekend to verify this fix!
