### ISSUE TITLE
remove path exists check when unmount flexvolume

### ISSUE THREAD

**Issue by x1957** [kubernetes/kubernetes#51612]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I'm using flexvolume for s3 volume [(s3fs-fuse https://github.com/s3fs-fuse/s3fs-fuse)](https://github.com/s3fs-fuse/s3fs-fuse)
but when s3fs-fuse crash,  and then unmount the volume,  the path exists check will return an error. https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/unmounter.go#L47
```
ls: cannot access /var/lib/kubelet/pods/e523f96c-83f0-11e7-9d8b-fa163e03ab61/volumes/xxxx~xxx/test: Transport endpoint is not connected
```
When we delete the pod, we can not unmount the volume.

**What you expected to happen**:
remove the check, let user do something in flexvolume driver, like umount the dir.

/sig storage
/assign

**Comment by verult** [comment]
@chakri-nelluri

**Comment by linyouchong** [comment]
may be this PR will fix it:
https://github.com/kubernetes/kubernetes/pull/52324

**Comment by x1957** [comment]
@linyouchong I think this pr works, but **UnmountMountPoint** not used in flexvolume
