### ISSUE TITLE
pull-kubernetes-e2e-gce-gpu failing: Quota 'SUBNETWORKS' exceeded

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#51646]
```
I0830 18:41:03.170] Creating new network: e2e-2549
W0830 18:41:45.592] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0830 18:41:45.592]  - Quota 'SUBNETWORKS' exceeded.  Limit: 160.0
W0830 18:41:45.593] 
W0830 18:41:45.675] 2017/08/30 18:41:45 util.go:134: Step './hack/e2e-internal/e2e-up.sh' finished in 1m26.446604891s
```

---
/kind flake
@kubernetes/sig-network-bugs @kubernetes/sig-testing-bugs @krzyzacy @MrHohn 
Related issues:
https://github.com/kubernetes/kubernetes/issues/51136

**Comment by nicksardo** [comment]
Instead of creating an automatic network, can we create manual networks with a single subnet?

**Comment by MrHohn** [comment]
> Instead of creating an automatic network, can we create manual networks with a single subnet?

+1

**Comment by ixdy** [comment]
It seems like the `k8s-jkns-pr-gce-gpus` project isn't being cleaned by the janitor. Was this an explicit decision?

**Comment by krzyzacy** [comment]
ah I'll add to the list - but why did gpu test can leak a subnetwork?

**Comment by cblecker** [comment]
@krzyzacy did this get resolved? I'm guessing so with https://github.com/kubernetes/test-infra/pull/4260

**Comment by krzyzacy** [comment]
For now, yes, for future, we'll need to have https://github.com/kubernetes/test-infra/issues/4472

/assign
/close
