### ISSUE TITLE
Simple shell tests could save a lot of contributor time

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#51642]
Yesterday I created a PR with a bunch of shell changes.  In one of these files, I misspelled `then` as `the`.  No test noticed this, and it broke node startup in such a deeply buried way that I could only debug it by logging in to the node and looking at startupscript.log, and then making some educated guesses.

However, it is very easy to detect.

```console
% bash cluster/common.sh
cluster/common.sh: line 685: syntax error near unexpected token `fi'
# fix it in the editor
% bash cluster/common.sh
% 
```

**Comment by mml** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by bgrant0607** [comment]
@mml This looks like cluster lifecycle? Also, please avoid using the -misc teams.

**Comment by mml** [comment]
@bgrant0607 Will do.  What are the -misc aliases for?

I labeled it contribex because the shell scripts are not just in cluster, although you're right that the hardest ones to debug are in cluster (like my example).

@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
now fixed with https://github.com/kubernetes/kubernetes/pull/51649?

**Comment by mml** [comment]
@luxas I might add some test coverage for other files, but sure.  Let's mark this fixed.
