### ISSUE TITLE
Broken links in Sig WIki page

### ISSUE THREAD

**Issue by ejc3** [kubernetes/kubernetes#51647]
The following page has broken links:
  https://github.com/kubernetes/kubernetes/wiki/Special-Interest-Groups-(SIGs)

E.g. this one:
  https://github.com/kubernetes/community/blob/master/README.md#how-to-start-a-sig

That should go here:
  https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procedure

/kind bug

**Comment by ejc3** [comment]
It'd be nice if all wiki's were moved to the community page so that pull request editing is supported.

**Comment by ejc3** [comment]
@kubernetes/sig-docs

**Comment by bgrant0607** [comment]
@xiangpengzhao See #116

**Comment by xiangpengzhao** [comment]
@bgrant0607 I don't find #116(`Added a -verbose flag, and made a message verbose only.`) has anything to do this issue. I think you meant https://github.com/kubernetes/community/issues/116 (`deprecating wiki pages`) :smile:

**Comment by bgrant0607** [comment]
wiki is gone
