### ISSUE TITLE
Use RW mutex in persistent volume label controller

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#51640]
/kind bug

From #44680 look at using a RW mutex around the volume retrieval

**Comment by kargakis** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
@rrati, would you mind fixing it since you wrote the controller?
/assign @rrati

**Comment by dims** [comment]
Agree @rrati

**Comment by rrati** [comment]
This has become a non-issue since #52169 has merged.  Closing.
