### ISSUE TITLE
Scheduler extender interface should be extended to support preemption

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#51656]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

Scheduler extenders do not have any interface for preemption. As a result, scheduler has to send preemption candidate node and its set of victim pods to the extender one at a time. This is inefficient.
Scheduler extenders interface should be extended to support preemption. The workflow should be as follows:
1. Internal scheduler finds a set of nodes and a set of victim on each of these nodes.
2. All of these nodes and victims are sent to the extenders via the new verb in one batch. Extenders return a subset of the given nodes and any additional victims on the nodes.
3. Internal scheduler scores the nodes and picks the best one for preemption.

@kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment]
I think a primitive interface design can be:

```go
// ProcessPreemptionNodesByExtender returns nodes with their victim pods processed by extender
// based on given candidate nodes and victim pods.
// The possible changes made by extender may include:
// 1. Subset of candidate nodes after predicate phase of extender.
// 2. More victim pods of give candidate node after preemption selection phase of extender.
ProcessPreemptionNodesByExtender(nodeToPods map[*v1.Node][]*v1.Pod) map[*v1.Node][]*v1.Pod
```

Workflow change will be like:

```go
genericScheduler.Preempt(...) {

  nodeToPods, err := selectNodesForPreemption(pod, g.cachedNodeInfoMap, potentialNodes, g.predicates, g.predicateMetaProducer)

  // Loop all extenders
  newNodeToPods = extender.ProcessPreemptionNodesByExtender(nodeToPods)

  node := pickOneNodeForPreemption(newNodeToPods)
}
```

@bsalamat Is this design meet your expectation?

**Comment by bsalamat** [comment]
@resouer Yes, this is what we need. We should also find a "verb" to communicate this with an extender:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/core/extender.go#L40
