### ISSUE TITLE
Scheduler should return specific errors for affinity predicates

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#51655]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

Today predicate functions return `ErrPodAffinityNotMatch` for these three cases: 1) pod affinity rules failed, 2) pod anti-affinity rules failed, 3) pod violated other pods anti-affinity rules. We should return a specific error in each one of these three cases. Separate error codes help when processing these failures in other parts of the code. For example, preemption logic does not need to attempt preempting any pods when a pending pod cannot be scheduled because of its own affinity rules.

In order to keep backward compatibility, it would be better to keep the existing error (`ErrPodAffinityNotMatch`) and add three new ones which are returned in addition to  `ErrPodAffinityNotMatch`.

@kubernetes/sig-scheduling-feature-requests

**Comment by guangxuli** [comment]
Hi, if no none work for this，i will pick it up.

**Comment by bsalamat** [comment]
@guangxuli Sure. Thank you!

/assign @guangxuli
