### ISSUE TITLE
New added CI tests can not start.

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#51681]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
New added CI tests: pull-kubernetes-bazel-build  and pull-kubernetes-bazel-test 
can not start.

**What you expected to happen**:
those should start automatically.

**How to reproduce it (as minimally and precisely as possible)**:
ref: https://github.com/kubernetes/kubernetes/pull/46341
it has ok-to-test label
![image](https://user-images.githubusercontent.com/5154334/29909278-c271d4aa-8e57-11e7-95ce-4ab2337100f7.png)

but
![image](https://user-images.githubusercontent.com/5154334/29909335-f8c276c2-8e57-11e7-818d-0a08fdaf3f79.png)

**Comment by xiangpengzhao** [comment]
See also in #46079.

@cblecker I see you triggered the two tests manually in some PRs, e.g. https://github.com/kubernetes/kubernetes/pull/50846#issuecomment-326193577. Any thoughts on this?

**Comment by cblecker** [comment]
Yeah, I triggered them because they didn't start on their own.. but it's good to raise this issue. I'm not sure who added those contexts, but they didn't start but were still marked as required by SQ.

cc: @kubernetes/test-infra-maintainers

**Comment by kargakis** [comment]
Yes, today there is no way other than manually triggering newly added CI tests on pre-existing PRs.

@soltysh this was what you also hit.

**Comment by kargakis** [comment]
Mind moving this isssue in the test-infra repository?

**Comment by zhangxiaoyu-zidif** [comment]
@kargakis 
OK, I will do it.
