### ISSUE TITLE
when kube-controller-manager stopped, delete service but endpoint is also deleted

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#51688]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
when kube-controller-manager stopped, I use kubectl delete svc but found endpoint also deleted.
**What you expected to happen**:
endpoint still exists
**How to reproduce it (as minimally and precisely as possible)**:

1. stop kube-controller-manager

2. delete svc kube-dns
```
root@SZX1000353068:/mnt/go/src/k8s.io/kubernetes/_output/bin# kubectl delete svc kube-dns   -n kube-system
service "kube-dns" deleted

```

3. get endpoint
```
root@SZX1000353068:/mnt/go/src/k8s.io/kubernetes/_output/bin# kubectl get ep -n kube-system
NAME                      ENDPOINTS   AGE
kube-controller-manager   <none>      17m
kube-scheduler            <none>      17m

``` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FengyunPan** [comment]
That' ok, after deleting service, kube-controller-manager deletes endpoint for this service.
If you stop kube-controller-manager, kube-controller-manager can't delete endpoint.

**Comment by hzxuzhonghu** [comment]
I mean when stop kube-controller-manager , endpoint still deleted.  So I doubt who delete endpoint

**Comment by hzxuzhonghu** [comment]
Because in service restStorage, endpoint is deleted when delete service. See https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/rest.go#L170~L180

So close this issue.
