### ISSUE TITLE
Refactor OpenStack cloud provider

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#51687]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently the codes of openstack cloud provider are confusion:
1.openstack loadbalancer support v1 and v2, they are  in the same file
2.openstack volume support v1 and v2, they are also in the same file. 
3.some name codes which is not related to cloud provider interface in openstack.go file: 
    the codes of zone, the codes of parsing cloud provider config, the codes of getting server,
    the codes of getting server's ips, the codes of getting server's interfaces and so on.
4.there are many common function, but there is no common util file.

**What you expected to happen**:
For the above, do the following improvements:
1.split openstack loadbalancer and openstack volume by version, in the future we will also support V3, it is better to split them into different files.
2.simple openstack.go by cloud.go
3.extract common functions into common util file, 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Nope

/assign

**Comment by xsgordon** [comment]
@FengyunPan did you have a milestone in mind for this feature?

**Comment by dims** [comment]
Let's do this early in 1.10 @FengyunPan ?
