### ISSUE TITLE
[SQ-blocking] kops-aws presubmit failing continuously due to cronjob e2e test

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51692]
Ref: https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-kops-aws

The test "Garbage collector should delete jobs and pods created by cronjob" is failing continuously with:

```
I0831 02:54:25.154] Aug 31 02:54:10.012: INFO: Failed to delete the CronJob: the server could not find the requested resource
```

cc @k8s-oncall @kubernetes/sig-aws-misc @kubernetes/test-infra-maintainers

**Comment by shyamjvs** [comment]
It seems to be running fine on gce - https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-gce-bazel.

**Comment by shyamjvs** [comment]
And starting from run 45192 of kops-aws, I'm seeing a bunch of additional e2e tests around cronjobs.
https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-kops-aws&width=80

**Comment by shyamjvs** [comment]
Ok, I guess this PR which advanced cronJobs to v1beta1 caused the trouble - https://github.com/kubernetes/kubernetes/pull/51465
I'm seeing a bunch of places where the group version hasn't been updated.
For e.g - https://github.com/soltysh/kubernetes/blob/2de214b044832e4149ca5a7f6a3d59e67e82af4e/test/e2e/apimachinery/garbage_collector.go#L959

I'll send a PR fixing it.

cc @soltysh

**Comment by shyamjvs** [comment]
Not sure how it went through presubmit.
@kubernetes/test-infra-maintainers Was sth around the presubmit changed around that time? I can't find anything obvious except a huge time gap between the last succeeding and first failing run (~2hrs).

**Comment by justinsb** [comment]
But on the other hand, how is GCE passing.  @liggit was able to observe that kops was testing a different version of k8s from what we thought (which is why I'm trying to get a simpler approach going in https://github.com/kubernetes/test-infra/pull/3883 ) , so perhaps that's the problem here

**Comment by justinsb** [comment]
@errordeveloper confirmed that we are running an old k8s: https://github.com/kubernetes/kubernetes/pull/51697#issuecomment-326313831  Trying to figure out why...

**Comment by shyamjvs** [comment]
Thanks @justinsb

**Comment by shyamjvs** [comment]
Btw - since the presubmit is not running against the PR, why not just disable it for now (until it's fixed)?

**Comment by mml** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51649/pull-kubernetes-e2e-kops-aws/45455/

I also vote for disable test until we fix it.

**Comment by justinsb** [comment]
@mml I agree we should turn off all tests, not just kops.

**Comment by wongma7** [comment]
could it be related to the "shared builds" issue the gpu tests had? https://github.com/kubernetes/kubernetes/issues/51481

**Comment by shyamjvs** [comment]
Closing this - kops presubmit is fine now.

**Comment by yastij** [comment]
reopened #51709 since this is happening again

**Comment by liggitt** [comment]
it appears to be a bringup error, not related to the cronjob tests that I can see

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/issues/4315#issuecomment-326712225
