### ISSUE TITLE
[upgrade test failure] Services should be able to change the type from ExternalName to [ClusterIP| NodePort]

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#51695]
The upgrade test fails for these two test. Most recent job:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/179

Dashboard: https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new&sort-by-failures=

@kubernetes/sig-network-bugs

**Comment by xiangpengzhao** [comment]
@mbohlool does this upgrade test run master test cases against a 1.7 cluster? If so, we should disable `[sig-network] Services should be able to change the type from ExternalName to ClusterIP` and `[sig-network] Services should be able to change the type from ExternalName to NodePort`.

https://github.com/kubernetes/kubernetes/pull/46197 introduced allocating cluster IP when updating service from ExternalName to non-ExternalName. It was merged from `v1.8.0-alpha.2`. When running the upgrade test, the test cases expect the service updating to allocate cluster IP, but the 1.7 cluster will not. Then the SanityCheckService fails.

/cc @thockin @freehan

**Comment by xiangpengzhao** [comment]
How to disable test cases in upgrade test?

**Comment by MrHohn** [comment]
> does this upgrade test run master test cases against a 1.7 cluster?

@xiangpengzhao  The expected sequence for this specific cluster upgrade job is:
1. Create a 1.7 cluster.
2. Start a bunch of [upgrade tests](https://github.com/kubernetes/kubernetes/blob/5dc0845e3625a99028bef39d6dcd648d48e2e61e/test/e2e/lifecycle/cluster_upgrade.go#L42-L54) (initiation phase).
3. Upgrade the master.
4. Upgrade the nodes.
5. Finish those upgrade tests (evaluation phase).
6. Run skew tests (a set of tests on latest branch) against the upgraded cluster.

From the logs posted on top, it seems steps 2~5 were missing. Likely something is wrong with the upgrade framework itself.

**Comment by MrHohn** [comment]
Found the issue (from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/180?log#log):
```
W0831 07:22:08.052] 2017/08/31 07:22:07 util.go:132: Running: ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=upgrade
W0831 07:22:08.425] ./hack/ginkgo-e2e.sh: line 92: detect-node-instance-groups: command not found
W0831 07:22:08.428] !!! Error in ./hack/ginkgo-e2e.sh:92
W0831 07:22:08.428]   Error in ./hack/ginkgo-e2e.sh:92. 'detect-node-instance-groups' exited with status 127
W0831 07:22:08.429] Call stack:
W0831 07:22:08.429]   1: ./hack/ginkgo-e2e.sh:92 main(...)
W0831 07:22:08.429] Exiting with status 1
```

**Comment by MrHohn** [comment]
Function `detect-node-instance-groups` used to locate at [cluster/gke/util.sh](https://github.com/kubernetes/kubernetes/blob/release-1.7/cluster/gke/util.sh#L313-L342), but was removed from kubernetes repo by https://github.com/kubernetes/kubernetes/pull/50338.

@zmerlynn @roberthbailey

**Comment by xiangpengzhao** [comment]
@MrHohn thanks! I misunderstood how the upgrade tests work. BTW, is the workflow documented anywhere?

/unassign

**Comment by MrHohn** [comment]
@xiangpengzhao The only doc I could find is: [Automating an Upgrade Test](https://docs.google.com/document/d/1nj_cQ8RTuGPnpoHNOAROFNmgSaNytPdE1bgrNt8Hfjo/edit?ts=58911538#). It illustrates how the upgrade test is automated but doesn't explain the upgrade job procedure though.

**Comment by xiangpengzhao** [comment]
@MrHohn thanks!

**Comment by zmerlynn** [comment]
http://prow.k8s.io/log?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new&id=201 has an example upgrade job that should be getting past this issue. (Still not complete, but it's getting farther.)
