### ISSUE TITLE
Use netlink instead of ip command to bind IP address in ipvs pkg

### ISSUE THREAD

**Issue by choury** [kubernetes/kubernetes#51694]
When fixing a problem  in #51686 ,I notice that it is treated as already bound if `ip` returned 2 in `EnsureVirtualServerAddressBind`, but ref to the   [manual](http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS) and [source code](https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/tree/ip/ipaddress.c#n2080) of ip , it just means an error was reported by the kernel, such as "Operation not permitted". 

I prefer to use [netlink](https://github.com/vishvananda/netlink) instead of `ip` command to manage ip address. If so,  we will know whether the IP are bound or unbound from the interface in a more accurate way.

**Comment by choury** [comment]
I've tried  netlink, and if I want to bind an ip which is already exist, I will get an error of "file exists", I think this can distinguish  whether the ip are bound. But if unbind an ip which is not exist, I just get an error of "cannot assign requested address" which is not specific enough to distinguish with other situation.
@m1093782566

**Comment by m1093782566** [comment]
Thanks for your informatin, @choury 

Personally, I don't think checking the "output message" is safe enough. For example, the English output message may don't work in Chinese, Russian, Latin etc. environment.

**Comment by choury** [comment]
@m1093782566 the error of netlink is not "output message", but  syscall.Errno
