### ISSUE TITLE
Provide options for passing on native container manager flags

### ISSUE THREAD

**Issue by abhilashkk** [kubernetes/kubernetes#51691]
/kind feature
/sig windows

**What happened**:  For windows based containers, there is a need to access shared objects using domain user contexts. Currently there is no way to do it in Kubernetes albeit docker supports this using the flag `--security-opt credentialspec=file://myuser.json` during container creation

**What you expected to happen**: Since currently there is no out-of-box solution in kubernetes, it would be great if we can pass these to docker/rkt while creating the container

**How to reproduce it (as minimally and precisely as possible)**: NA

**Anything else we need to know?**: None

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`): Windows 2016
- Install tools: kubectl
- Others:

**Comment by xforze** [comment]
Are there any News on this issue ?
I'm running into the same problem that I cannot apply gmsa credentials via Kubernetes.
Starting the Application directly with docker and "--security-opt=........." works fine.

**Comment by abhilashkk** [comment]
Looks like this feature is in backlog https://trello.com/b/rjTqrwjl/windows-k8s-roadmap with priority 1, but not sure about the target release version.

**Comment by xforze** [comment]
Oh, this looks great :-)

**Comment by rofr** [comment]
This issue isn't really specific to windows. Of course the --security-opt flag is but wouldn't it be smart in general to have a "docker-args" property in the pod.yaml analogous to args property for container args?

**Comment by marosset** [comment]
/close
This was fixed with the Windows GMSA KEP a while ago.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/ for more details.
