### ISSUE TITLE
Panic in TestCancelAndReadd (again)

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#51704]
I have started to see #45375 again:

https://github.com/openshift/origin/pull/16071 -> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16071/test_pull_request_origin_unit/1869

The longer wait just pushes the race condition forward.

/assign @gmarek

cc @davidopp @timothysc

```
=== RUN   TestCancelAndReadd
panic: sync: negative WaitGroup counter

goroutine 419 [running]:
sync.(*WaitGroup).Add(0xc4201d2420, 0xffffffffffffffff)
	/usr/lib/golang/src/sync/waitgroup.go:75 +0x255
sync.(*WaitGroup).Done(0xc4201d2420)
	/usr/lib/golang/src/sync/waitgroup.go:100 +0x42
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.TestCancelAndReadd.func1(0xc4201c1380, 0x1, 0x20)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go:118 +0x61
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.(*TimedWorkerQueue).getWrappedWorkerFunc.func1(0xc4201c1380, 0x0, 0x0)
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:81 +0xb6
github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node.CreateWorker.func1()
	github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/node/_test/_obj_test/timed_workers.go:44 +0x72
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:170 +0x52
```

**Comment by lavalamp** [comment]
Who owns the node controller? It is not api machinery. Scheduling?

**Comment by gmarek** [comment]
This is a known issue with tests. It will go away once we migrate to taint based evictions, but the move is not high enough priority for anyone to work on it.

**Comment by kargakis** [comment]
We have been seeing this fairly often downstream. What's the effort required to fix the test w/o the move?

**Comment by enj** [comment]
@kargakis perhaps we should just disable it downstream?

**Comment by enj** [comment]
https://github.com/openshift/origin/pull/16077 already changed the tests with the longer sleep and it is still flaking.

**Comment by gmarek** [comment]
It's probably ~week of work to rewrite NC tests.
