### ISSUE TITLE
pull-kubernetes-e2e-kops-aws failing

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#51709]
currently it is always failing across PRs see [here](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws)

**Comment by yastij** [comment]
closing, duplicate of #51692

**Comment by yastij** [comment]
reopening this one, ping  @justinsb @shyamjvs

**Comment by liggitt** [comment]
symptom appears different now:
```
W0904 13:48:56.892] 2017/09/04 13:48:56 e2e.go:315: kubectl get nodes failed: error during kubectl get nodes --no-headers: exit status 1
W0904 13:48:56.893] 2017/09/04 13:48:56 e2e.go:367: Can't get cluster size, sleeping: error during kubectl get nodes --no-headers: exit status 1
W0904 13:49:26.892] 2017/09/04 13:49:26 util.go:172: Running: kubectl get nodes --no-headers
W0904 13:49:57.011] Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout
```

possibly https://github.com/kubernetes/test-infra/issues/4361

**Comment by justinsb** [comment]
The good news is that this appears to be test-infra, not real.  Tests I have run myself are passing apart from the 3 known failures (nodeports, dashboard, HPA not configured the same way) https://k8s-testgrid.appspot.com/kopeio#kopeio-aws

**Comment by mml** [comment]
@justinsb or @liggit, can we tell if the problem is kubernetes/test-infra#4361 for sure?  If it's not, is it some other problem with test-infra?

**Comment by ixdy** [comment]
The issue is https://github.com/kubernetes/test-infra/issues/4315#issuecomment-326712225. We're running a 1.7 cluster with 1.8+ tests.

**Comment by mml** [comment]
/assign @justinsb 

Justin, can you please find someone from SIG-AWS to work on this?

**Comment by mml** [comment]
@ixdy Does kubernetes/test-infra#4400 fix this?

**Comment by ixdy** [comment]
that + cleanup finally fixed this, yes.
