### ISSUE TITLE
Loadbalancer creation for service failing in case of custom network

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51714]
The "Services should be able to create an internal type load balancer [Slow]" e2e test is failing on our 2k-node gce clusters - https://k8s-testgrid.appspot.com/google-gce-scale#gce-large-correctness
with the following error:

```
Aug 26 10:40:25.476: INFO: At 2017-08-26 10:25:41 +0000 UTC - event for lb-internal: {service-controller } CreatingLoadBalancerFailed: Error creating load balancer (will retry): Failed to ensure load balancer for service e2e-tests-services-bqlcw/lb-internal: googleapi: Error 400: Invalid value for field 'resource.subnetwork': ''. Network interface must specify a subnet if the network resource is in custom subnet mode., invalid
```

We're using custom subnets for our large cluster tests, and seems like the glbc controller is not able to handle them.

cc @kubernetes/sig-network-bugs @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
Seems similar to https://github.com/kubernetes/kubernetes/issues/50034
@nicksardo Assigning to you as you seem to have the context already :) Also, is this expected to be fixed in 1.8 timeframe?

**Comment by nicksardo** [comment]
gce.util doesn't set the necessary variables for the GCE cloud provider. Will throw you a PR.

**Comment by shyamjvs** [comment]
Cool - thanks a lot!

**Comment by nicksardo** [comment]
I see the last test on 09/09 failed, but I can't see the build log due to exceeding memory. Any other way I can see the log, @shyamjvs?

/reopen

**Comment by nicksardo** [comment]
nevermind - went directly to raw log.

**Comment by shyamjvs** [comment]
@nicksardo Friendly ping. This e2e is still failing (https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness) and it's part of release-blocking suite.
