### ISSUE TITLE
Failing e2e tests on scalability jobs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51718]
This is an umbrella issue for tracking currently failing e2e tests on large clusters:

- [sig-instrumentation] Cluster level logging implemented by Stackdriver should ingest system logs from all nodes (https://github.com/kubernetes/kubernetes/issues/51700)
- [sig-instrumentation] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster (https://github.com/kubernetes/kubernetes/issues/51702)
- [sig-network] Firewall rule should have correct firewall rules for e2e cluster (should be fixed by https://github.com/kubernetes/kubernetes/pull/51343)
- [sig-network] Services should be able to create an internal type load balancer [Slow] (https://github.com/kubernetes/kubernetes/issues/51714)
- [sig-storage] Volume plugin streaming [Slow] NFS should write files of various sizes, verify size, validate content (https://github.com/kubernetes/kubernetes/issues/51717)

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek @spiffxp

**Comment by shyamjvs** [comment]
Some additional failures seen on 5k-node tests:

- [sig-node] AppArmor load AppArmor profiles should enforce an AppArmor profile (https://github.com/kubernetes/kubernetes/issues/51791)
- [sig-scalability] API call latencies shot up on large cluster tests (https://github.com/kubernetes/kubernetes/issues/51899)

**Comment by dims** [comment]
@shyamjvs are we almost done with the issues for this umbrella issue? if so can we close this out and leave the individual issues with correct milestone?

**Comment by shyamjvs** [comment]
Yes, most of the fixes have been done here - thanks to the concerned SIGs for acting promptly. There are a few ones which are failing even on smaller clusters (like #52496) and are not scalability related. The only one which is failing currently and is actually scalability-related is:

ESIPP [Slow] e2e tests failing on large cluster release-blocking job #52495 

There's some discussion going on there about a potential fix but we more or less know why it's failing and don't have to block release on it.
And for failures related to performance tests (which are different from correctness tests), we have separate issues.

**Comment by shyamjvs** [comment]
Closing the issue. We can reopen it later if needed.

**Comment by shyamjvs** [comment]
fyi - I've unmarked some of those issues from release-blocker based on the causes identified.
