### ISSUE TITLE
Volume plugin streaming e2e test failing on large cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51717]
The "Volume plugin streaming [Slow] NFS should write files of various sizes, verify size, validate content" e2e test is failing on our 2k-node gce clusters (https://k8s-testgrid.appspot.com/google-gce-scale#gce-large-correctness) with the following error:

```
    unable to test file content via `grep /opt/nfs/e2e-tests-volume-io-fwm9d/nfs_io_test-1048576`: error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.196.132.168 --kubeconfig=/workspace/.kube/config exec --namespace=e2e-tests-volume-io-fwm9d nfs-io-client -- /bin/sh -c grep -c -m1 -f /opt/nfs/e2e-tests-volume-io-fwm9d/dd_if /opt/nfs/e2e-tests-volume-io-fwm9d/nfs_io_test-1048576] []  <nil>  Killed
    Command stdout:
    
    stderr:
    Killed
    command terminated with exit code 137
```

cc @kubernetes/sig-storage-bugs @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
@saad-ali Could you take a look into it or reassign as apt?
This is part of the correctness suite and large cluster tests are release-blocking.

**Comment by msau42** [comment]
@shyamjvs is this run using the kubemark environment? 

I'll also take a look.  It could be that the commands this test needs to execute may not work with kubemark.
/assign

**Comment by rootfs** [comment]
cc @jeffvance

**Comment by shyamjvs** [comment]
No, this is not kubemark. This is on a real 2000-node cluster.

**Comment by shyamjvs** [comment]
Also all other volume-related e2e tests are passing, except this one.

**Comment by jeffvance** [comment]
Looking at the log I see that the nfs test fails trying to verify the test file's content. The test exec's into the nfs client pod and executes:
```
grep -c -m1 -f /opt/nfs/e2e-tests-volume-io-fwm9d/dd_if /opt/nfs/e2e-tests-volume-io-fwm9d/nfs_io_test-1048576
```
The return code from above is 127.
The test then deletes the nfs client pod calling `framework.DeletePodWithWait` which works. 
The nfs-server pod is deleted in the AfterEach which works.
The namespace is successfully destroyed.
For some reason the reported error is 137 but the `kubectl exec` returned err 127.
The same `grep` command is exec'd for all of the tested storage plugins so not sure why it's failing just for nfs.

**Comment by msau42** [comment]
The other strange thing is that it's only failing in this suite and not the others.

**Comment by msau42** [comment]
When I look at the kubelet log, I see the exec command coming through:
```
I0826 10:23:34.791478    1555 server.go:791] POST /exec/e2e-tests-volume-io-fwm9d/nfs-io-client/nfs-io-client?command=%2Fbin%2Fsh&command=-c&command=grep+-c+-m1+-f+%2Fopt%2Fnfs%2Fe2e-tests-volume-io-fwm9d       %2Fdd_if+%2Fopt%2Fnfs%2Fe2e-tests-volume-io-fwm9d%2Fnfs_io_test-1048576&error=1&output=1: (15.316631ms) 302 [[kubectl/v1.8.0 (linux/amd64) kubernetes/c241cbe] 10.142.0.2:46624]
```

I also see these suspicious kubelet [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/3/artifacts/gce-large-cluster-minion-group-1-r78f/kubelet.log) soon afterwards:
```
I0826 10:23:39.130030    1555 threshold_notifier_linux.go:113] eviction: threshold crossed
I0826 10:23:39.132721    1555 eviction_manager.go:258] hard memory eviction threshold crossed at <250Mi available

I0826 10:23:39.404590    1555 handler.go:325] Added event &{/ 2017-08-26 10:23:39 +0000 UTC oom {<nil>}}
I0826 10:23:39.404929    1555 manager.go:1141] Created an OOM event in container "/" at 2017-08-26 10:23:39 +0000 UTC
I0826 10:23:39.405094    1555 handler.go:325] Added event &{ 2017-08-26 10:23:39 +0000 UTC oomKill {0xc420811aa0}}
I0826 10:23:39.302012    1555 oom_watcher.go:68] Got sys oom event from cadvisor: &{/ 2017-08-26 10:23:39 +0000 UTC oom {<nil>}}
I0826 10:23:39.547991    1555 server.go:225] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"gce-large-cluster-minion-group-1-r78f", UID:"gce-large-cluster-minion-group-1-r78f", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SystemOOM' System OOM encountered
```

So I think the grep command is causing the node to run out of memory and get evicted.

I think we can fix this either by:
* Making the grep command more memory efficient.  I'm guessing it's reading the whole file into memory or,
* Make this test Serial so that it doesn't run in parallel with other pods, since it consumes a lot of memory.

**Comment by msau42** [comment]
An unrelated issue, is that the node allocatable feature didn't actually evict the pod.  Instead this pod got a system OOM kill.
/cc @dchen1107 @dashpole

**Comment by dashpole** [comment]
related to the memcg notifications, not node allocatable.  Thanks!

**Comment by jeffvance** [comment]
@msau42 any theories why we see this only for the nfs-io tests, and not the glusterfs-io test for instance?

**Comment by msau42** [comment]
the gluster test didn't run on this in this suite.

I'm suspecting that the reason why we didn't see a problem with this test on other suites is that the load could be higher here.  I've asked @verult to see if we can reduce the memory usage of the grep call.

**Comment by verult** [comment]
@msau42 pointed out that there are no newlines in the generated file, so when grep is called it could buffer the entire file in memory. Adding a newline at the end of the dd input file should do it.

**Comment by verult** [comment]
It seems like even if the generated file is broken up by newlines, grep could still use on the order of hundreds of MB of memory for a 100MiB file (even with the -m1 and -F options).

We could check the file line by line, but it would take a long time.

A better solution would be to check the MD5 file hash. It's fast and uses little memory. The expected hashes will be hard-coded into the test, and if different file sizes are added in the future, a hash needs to be computed and added as well.

**Comment by shyamjvs** [comment]
@verult Thanks a lot for fixing this!

**Comment by shyamjvs** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/51718
