### ISSUE TITLE
Ingress controller session affinity via cookies do not work with GCP

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubernetes#51711]
/kind bug

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: Google Cloud Platform

I'm not even sure if this is possible. 

**ingressProd.yaml**

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: wordpress
      annotations:
        kubernetes.io/ingress.class: "gce"
        ingress.kubernetes.io/affinity: "cookie"
        ingress.kubernetes.io/session-cookie-name: "route"
        ingress.kubernetes.io/session-cookie-hash: "sha1"
    spec:
      tls:
      - hosts:
        - ***.ddns.net
        secretName: production-tls
      rules:
        - host: ***.ddns.net
          http:
            paths:
            - path: /*
              backend:
                serviceName: wordpress
                servicePort: 80

With the above config it does not seem to add any additional cookies. And it seems to have the default round robin load balancing behaviour.

**Comment by chrissound** [comment]
@kubernetes/sig-network-bugs

**Comment by nicksardo** [comment]
As far as I know, only the nginx controller supports those annotations.

**Comment by chrissound** [comment]
A workaround is to set the session affinity in the google cloud platform console.

**Comment by chrissound** [comment]
Although I've set the session affinity manually via the GCP console, this does not seem to have taken any effect. 

Does anyone know how Kubernetes might be contributing to this issue?

**Comment by jaysonjc** [comment]
It seems that the ingress cookie affinity doesn't work in GKE since there is no direct POD load balancing (unlike nginx ingress controller). Is there any way to enable direct pod load balancing in GKE with session affinity?

**Comment by nicksardo** [comment]
You can fake it by using `externalTrafficPolicy: Local`, run a max of 1 pod per node for the respective service, and setting the sesionAffinity on the Backend Service. The Google LB will forward traffic to the same node and the traffic policy will prevent the traffic from being routed off that node. Of course, this only works if you don't have more than one selected pod on that node.  

> 2 backend services created (for 2 nodes)
for N nodes. One backend service is yours; the other is the default 404 server if you didn't specify a default backend.

Since this is not a K8s core problem or bug, I'm going to close it.
/close
