### ISSUE TITLE
Add pod-template-hash label to Deployments

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#51713]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

It would be nice if the Deployment object was labeled with the current `pod-template-hash` so that it's easier to find only the pods of the newest replicaset. Currently to find pods of the newest replicaset we need to find all the replicasets belonging to a deployment, get `pod-template-hash` from the one with the highest revision, and then get pods using `pod-template-hash` in label selector.

**Comment by kargakis** [comment]
Or a status field. 

cc: @janetkuo @tnozicka
