### ISSUE TITLE
Remove scheduler duplication with ExtendedResources and HugePages

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#51732]
**What happened**:
The scheduler has a concept of `ExtendedResources` which lets it schedule resources not in the default Kubernetes resource namespace.  HugePages are very similar to ExtendedResources in that they cannot be overcommitted, but that resource is expected to be in the Kubernetes resource namespace once it graduates out of alpha.

The scheduler should be refactored so that ExtendedResources is the superset of resources that do not support over-commit to avoid code duplication.

**Anything else we need to know?**:
See: https://github.com/kubernetes/kubernetes/pull/50859#discussion_r136400471

**Comment by derekwaynecarr** [comment]
@sjenning @aveshagarwal -- can either of you commit to making this change to address @bsalamat request?

**Comment by bsalamat** [comment]
Another aspect of Extended Resources, OIRs, or HugePages that is similar from scheduling point of view is that they are all scalar resources. They have a name and a number representing their quantity. Accounting for all these resource types should be done identically.

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-misc

**Comment by ConnorDoyle** [comment]
@bsalamat you can say the same thing about memory (unit is bytes as an integer.) Right now there are a two aspects that we infer based on resource names:
1. Allow-fractional-quantities. This is `false` for all first-class and extended resources except for `cpu`.
1. Allow-overcommit. This is `false` for extended resources and hugepages. There is a hardcoded overcommit-blacklist which is enforced in validation.

We should be able to standardize how all resources are handled in the scheduler with the help of these existing predicates. One thing to watch out for is that some log/event strings in predicate failure vary by resource. It would be nice if nobody had to touch the scheduler predicates when adding support for a new resource name.

**Comment by ConnorDoyle** [comment]
We could probably fix #50658 by handling resources generically even for names inside the `kubernetes.io/` domain.
