### ISSUE TITLE
CRI: Define more constants

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#51747]
For seccomp and apparmor, we all defined some constants `localhost/`, `runtime/default` etc.

We should define them in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/constants.go, so that runtime could share it.

@feiskyer @yujuhong @mrunalp @mikebrow
/cc @kubernetes/sig-node-api-reviews

**Comment by feiskyer** [comment]
+1
