### ISSUE TITLE
CRI: Behavior of empty AppArmor profile is not clearly defined.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#51746]
For seccomp, we defined:
```
    // Seccomp profile for the sandbox, candidate values are:
    // * docker/default: the default profile for the docker container runtime
    // * unconfined: unconfined profile, ie, no seccomp sandboxing
    // * localhost/<full-path-to-profile>: the profile installed on the node.
    //   <full-path-to-profile> is the full path of the profile.
    // Default: "", which is identical with unconfined.
```

However for apparmor, we only defined:
```
    // AppArmor profile for the container, candidate values are:
    // * runtime/default: equivalent to not specifying a profile.
    // * localhost/<profile_name>: profile loaded on the node
    //    (localhost) by name. The possible profile names are detailed at
    //    http://wiki.apparmor.net/index.php/AppArmor_Core_Policy_Reference
```

From the definition, it seems that empty apparmor profile will be "unconfined", because there is no other "unconfined" option.

However, it is not the case today. When apparmor profile is empty, we'll return empty https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers.go#L203.

However, in docker, it will apply `docker-default` if apparmor profile is empty, when apparmor is enabled on the OS. https://github.com/moby/moby/blob/6b262572028cc249b7da8cc55459197395fdb33e/daemon/oci_linux.go#L788-L792

IIUC, this means that, **as long as the node supports apparmor, `docker-default` will be applied to every pod, every container, no matter pod has apparmor label or not**

Is this the behavior we want? @tallclair 
We should clearly define what is the expected behavior.

@feiskyer @yujuhong @mrunalp @mikebrow 
/cc @kubernetes/sig-node-api-reviews

**Comment by resouer** [comment]
Do you think it's reasonable to apply `docker-default` in dockershim? As it is docker specific.

**Comment by feiskyer** [comment]
> * runtime/default: equivalent to not specifying a profile.

@Random-Liu There is no unconfined AppArmor problem, default is `runtime/default`, whose behavior is defined by runtime itself.

> Do you think it's reasonable to apply docker-default in dockershim? As it is docker specific.

@resouer In dockershim, yes. but Random's main concern is the behavior of  empty AppArmor profile.

**Comment by tallclair** [comment]
Agree with @feiskyer . The `runtime/default` is explicitly not defined at the Kubernetes level (hence the `runtime` prefix). For docker / containerd, this should be the docker-default profile. For everything else, it's up to the authors. As part of AppArmor graduating out of beta, we may want to consider defining a `kubernetes/default` profile (which would probably be identical to `docker-default` in practice).

**Comment by mikebrow** [comment]
And if we had one how would you point the runtime to that profile or would you simply specify it in a doc somewhere and the runtimes would have to generate it? I sort of figured if it's not runtime/default, or localhost/profilename that it would be a path to a profile that's been configured for the container. But at the moment it's invalid of not runtime/default or localhost/profile, right?

**Comment by tallclair** [comment]
The way apparmor currently works, the runtime expects the profile to already be loaded (in the kernel), and just takes a name that references it. If we had a Kubernetes default profile, I would expect the Kubelet to load the profile, and pass the name to the runtime.

**Comment by Random-Liu** [comment]
> @resouer In dockershim, yes. but Random's main concern is the behavior of empty AppArmor profile.

@tallclair It's still not clear to me what is the behavior for empty AppArmor profile.

Today, even if user doesn't apply any apparmor label, default docker apparmor profile will be applied. Is this expected behaviro?

**Comment by Random-Liu** [comment]
Mark 1.9. I think we should clearly define this in 1.9

**Comment by tallclair** [comment]
@Random-Liu Yes that's the intended behavior. I think it would be reasonable to define a default Kubernetes profile though.

**Comment by yujuhong** [comment]
> Today, even if user doesn't apply any apparmor label, default docker apparmor profile will be applied. Is this expected behavior?

@tallclair, this seems misleading to me... Whether the default apparmor profile will be applied to containers or not become a node-level decision, and is hard to detect by the end users. 
Perhaps this should be a cluster-level setting? We can set the default for every pod automatically.

Another question. Do we ever want to allow a container to run without any apparmor profile? This seems not doable today if apparmor is enabled on the node.

**Comment by tallclair** [comment]
Unfortunately AppArmor profiles aren't a cluster managed resource yet (I think they should be prior to AA going to GA). This means that it's hard to enforce anything at the cluster level. But for the ideal eventual state, I agree the defaulting should be done at the cluster level.

**Comment by luckyfengyong** [comment]
@Random-Liu Thanks for raising the issue. It also confused me. 
The application I deployed requires AppArmorProfile specified as "unconfined" together with few extra capabilities. I could run "docker run --security-opt apparmor=unconfined --cap-add=SYS_ADMIN --cap-add=SYS_RESOURCE --cap-add=IPC_OWNER ..." to launch the application. However in Kuberentes, according to following doc, I have to run the Pod as privilege mode. I cannot specify AppArmorProfile as "unconfined"  explicitly in Kubernetes. 

Any suggestion, I could specify AppArmorProfile as  "unconfined", but don't have to run Pod in privilege mode? 

<img width="881" alt="image" src="https://user-images.githubusercontent.com/8002217/30306435-235abb78-9746-11e7-9651-48a6ad1cae81.png">

**Comment by tallclair** [comment]
@luckyfengyong - Thanks for the report, that's a bug. I filed https://github.com/kubernetes/kubernetes/issues/52370 to track it.

**Comment by wgahnagl** [comment]
/assign @saschagrunert 
can we have an update on this ?

**Comment by saschagrunert** [comment]
I think we will not change the dockershim any more since it is deprecated since some releases. I propose to close this one, while assuming that container runtimes like CRI-O and containerd do the right thing.
/close
