### ISSUE TITLE
New SchedulerPredicates Conformance test is constantly failing

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes#51741]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

There are several CI e2e jobs that are failing this new Conformance test:

    [sig-scheduling] SchedulerPredicates [Serial] validates local ephemeral storage resource limits of pods that are allowed to run [Conformance] 1m6s
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:221
    Expected
        <bool>: false
    to equal
        <bool>: true
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:160

Here is one such failure:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5422

Moreover, this new test has been consistently failing on multiple e2e jobs ever since it was merged to master:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce
https://k8s-testgrid.appspot.com/google-aws#kops-aws-serial
https://k8s-testgrid.appspot.com/sig-scheduling#gce-serial
https://k8s-testgrid.appspot.com/sig-scheduling#gke-serial

Here is the pull request for the new test:
https://github.com/kubernetes/kubernetes/pull/50005

I don't know if this is a legitimate problem with the scheduler in these jobs and if the test is running and passing elsewhere, or if there is a flaw in the test itself.

@kubernetes/sig-scheduling-bugs 
@NickrenREN

**Comment by pipejakob** [comment]
CC @kubernetes/sig-scheduling-bugs to comment on the correctness of this new test, since it is failing both for kubeadm e2es and kops as well:

https://k8s-testgrid.appspot.com/google-aws#kops-aws-serial

I haven't been able to find any other e2e jobs where this test isn't skipped, so I don't know if it's green anywhere.

**Comment by pipejakob** [comment]
Also failing gce-serial and gke-serial:

https://k8s-testgrid.appspot.com/sig-scheduling#gce-serial
https://k8s-testgrid.appspot.com/sig-scheduling#gke-serial

**Comment by pipejakob** [comment]
Updated title/description since this isn't a kubeadm-specific CI failure.

**Comment by NickrenREN** [comment]
Sorry for that, I will look into it

/assign

**Comment by NickrenREN** [comment]
LocalEphemeralStorage will be added to node's capacity when `LocalStorageCapacityIsolation` feature gate is enabled. In e2e tests ,the feature gate is not enabled, so the error happened
Revert first to avoid constantly failing tests and then i will send a new PR again.

**Comment by pipejakob** [comment]
Thanks for looking into this, @NickrenREN! I'll be out of the office for the next few days (back on September 5th), so I would include more people on that PR so it's not stalled on my feedback. My personal vote is to change the test's tag from "[Conformance]" to "[Feature:EphemeralStorage]" so that test jobs will have to opt into running the test, but I don't know if we already have the pattern elsewhere of checking for whether or not a feature is enabled and skipping an enabled test anyway.

SIG Testing might have guidelines for best practices here.

**Comment by NickrenREN** [comment]
Sorry for not understanding the tag's meaning

> My personal vote is to change the test's tag from "[Conformance]" to "[Feature:EphemeralStorage]" so that test jobs will have to opt into running the test

yeah, that would be helpful

> SIG Testing might have guidelines for best practices here.

**Comment by ericchiang** [comment]
/kind e2e-test-failure
cc @kubernetes/sig-release-members

**Comment by ericchiang** [comment]
@pipejakob from what I can see this test has _never_ passed for certain test suites. e.g. https://k8s-testgrid.appspot.com/release-master-blocking#gke-serial

Would it be appropriate to revert the test?

**Comment by luxas** [comment]
@ericchiang See https://github.com/kubernetes/kubernetes/pull/51758; which fixes the main problem.
I just asked to bump the priority
