### ISSUE TITLE
Move AWS & GCE specific logic out of pkg/controller/cloud/pvlcontroller.go

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#51743]
/kind bug

**What happened**: 
https://github.com/kubernetes/kubernetes/pull/44680 adds support for persistent volume support to the cloud controller manager. However it adds GCE and AWS specific code in a generic module. 

**What you expected to happen**:
This logic should live under pkg/cloudproviders/provider/gce and pkg/cloudproviders/aws. We need to restructure things a little bit to move the logic appropriately.

**How to reproduce it (as minimally and precisely as possible)**:
Look at pkg/controller/cloud/pvlcontroller.go in https://github.com/kubernetes/kubernetes/pull/44680

**Anything else we need to know?**:

**Environment**:
In source

**Comment by luxas** [comment]
Sorry, I didn't see https://github.com/kubernetes/kubernetes/issues/51629 when requesting this; as it's older I'll close this as a dupe and we can have one thread only in https://github.com/kubernetes/kubernetes/issues/51629
