### ISSUE TITLE
Need `kubectl create pvc`

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#51742]
Was shocking to me we don't have it - i can create a pdb or quota but not the thing people actually need all the time.

@kubernetes/sig-cli-feature-requests

**Comment by xingzhou** [comment]
I think we used to have plans to add more `kubectl create xxx` sub command, but not sure why stopped. e.g. https://github.com/kubernetes/kubernetes/pull/43369
I can help develop on this one, /cc @kargakis and @adohe

**Comment by xingzhou** [comment]
@zjj2wry, are you working on this one or other sub commands?

**Comment by zjj2wry** [comment]
@xingzhou not start for ```kubectl create pvc```. i am work with ```kubectl create deamonset``` before.

**Comment by zjj2wry** [comment]
@xingzhou just feel free go for it. i will help reivew :)

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by adohe** [comment]
Just assign this one to me, will get someone to finish this.

**Comment by dsymonds** [comment]
Well this is disappointing. It was approved and seemed ready to submit over a year ago, but got dropped on the floor, and I really wanted to be able to use this today. Sigh.
