### ISSUE TITLE
Memory Eviction Memcg notifications are not effective.

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#51745]
While debugging https://github.com/kubernetes/kubernetes/issues/51717#issuecomment-326433510, we found that despite memcg notifications waking up the eviction manager, the eviction manager was unable to take action before a system oom ~6 seconds later.  The following sequence of events occurred:
1. Memory threshold crossed.
2. Memcg notifications triggers synchronize call in eviction manager
3. Eviction manager gets summary stats (~10 seconds old)
4. Eviction manager determines there is no pressure (because stats are old)
5. Repeat steps 1-4 a couple times (for ~6 seconds)
6. System OOM

cc @derekwaynecarr @sjenning @dchen1107 @vishh @yguo0905 
/sig-node

**Comment by dashpole** [comment]
This would be fixed by on-demand node-level stats.

**Comment by dims** [comment]
@dashpole what is needed for 1.9? (or can this move to 1.10)?

**Comment by dashpole** [comment]
This would be fixed by on-demand node level metrics: https://github.com/google/cadvisor/pull/1779
The implementation is on track for 1.9

**Comment by dashpole** [comment]
https://github.com/google/cadvisor/pull/1779 is the change in cadvisor required to fix this, which was just merged.  
The steps to fix this are:
update cadvisor godeps
Change kubelet stats collection to utilize changes in https://github.com/google/cadvisor/pull/1779

**Comment by dashpole** [comment]
ACK. In progress
ETA: Whenever https://github.com/kubernetes/kubernetes/pull/56112 is reviewed
Risks: Enabling a new feature.

**Comment by dashpole** [comment]
With further testing, this is not fixed entirely by on demand metrics.  The memcg notifications watch the memory.usage_in_bytes file.  However, we perform eviction based on the working set, which is memory.usage_in_bytes - memory.total_inactive_file.  This means that even with on-demand metrics, the memcg notifications cause the eviction manager to "wake up" before we have actually crossed the threshold.

I think any solution would require some discussion, and will not occur in the 1.9 timeframe.
Removing the milestone from this issue.
