### ISSUE TITLE
"the server could not find the requested resource" when create cron job

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#51769]
> Environment:
> 
> Kubernetes version (use kubectl version): v1.7.0
> Cloud provider or hardware configuration**:
> OS (e.g. from /etc/os-release): CentOS 7
> Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
> Install tools: Kubeadm
> Others:
> docker version : Docker version 1.12.6,
> My RPM version :
> docker-1.12.6-16.el7.centos.x86_64.rpm
> kubectl-1.7.0-0.x86_64.rpm
> kubernetes-cni-0.5.1-0.x86_64.rpm
> kubeadm-1.7.0-0.x86_64.rpm
> kubelet-1.7.0-0.x86_64.rpm

i use example in document https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ ,but it seems can not create cron job ,why?
```
[root@k8s-master ~]# kubectl create -f cronjobdemo.yml
error: error validating "cronjobdemo.yml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
[root@k8s-master ~]# cat cronjobdemo.yml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

```

**Comment by cblecker** [comment]
You likely haven't satisfied the [prerequisites](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#prerequisites).
---
/kind support
/close
