### ISSUE TITLE
Time zone error

### ISSUE THREAD

**Issue by ylf881011** [kubernetes/kubernetes#51789]
I am in China. Start a service at six o'clock in the afternoon. View the status of lastTransitionTime is missing at 10 am.
K8S there is no time zone to set the parameters?

![image](https://user-images.githubusercontent.com/16286574/29968028-599cc30e-8f4c-11e7-99b6-ba62636cccbe.png)

**Comment by dims** [comment]
@ylf881011 you are right it's in UTC, see the Z at the end. It's in UTC by design i believe

```
The UTC time zone is sometimes denoted by the letter Z—a reference to the equivalent nautical time zone (GMT), which has been denoted by a Z since about 1950
```
