### ISSUE TITLE
DaemonSet with PodNodeSelector AdmissionController keeps starting on unselected nodes

### ISSUE THREAD

**Issue by dohnto** [kubernetes/kubernetes#51788]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In our kubernetes cluster, we use **PodNodeSelector** Admission Controller with annotation format (`scheduler.alpha.kubernetes.io/node-selector`).
When a DaemonSet is spawned in such annotated namespace, the pod keeps starting even on nodes which are not selected by the nodeSelector and the pod keeps changing its status from `Pending` -> `MatchNodeSelector` -> `Terminating`

**What you expected to happen**:

Not to schedule on nodes which do not match nodeSelector.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
#!/bin/bash
# run.sh

minikube start --extra-config apiserver.Admission.PluginNames="PodNodeSelector"
kubectl apply -f namespace.yaml
kubectl -n test apply -f daemonset.yaml
kubectl -n test get pod -w
minikube stop
minikube delete
```

```yaml
# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    # force pods to run on realm nodes only
    scheduler.alpha.kubernetes.io/node-selector: "realm=test"
```
```yaml
# daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test
  labels:
    app: test
spec:
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        image: busybox
        command:
        - tail
        - -f
        - /dev/null
```
When you have all these files save, you just run
```
$ bash run.sh 
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
namespace "test" created
daemonset "test" created
NAME         READY     STATUS    RESTARTS   AGE
test-llfsf   0/1       Pending   0          0s
test-llfsf   0/1       MatchNodeSelector   0         5s
test-llfsf   0/1       Terminating   0         5s
test-llfsf   0/1       Terminating   0         5s
test-k4txm   0/1       Pending   0         0s
test-k4txm   0/1       MatchNodeSelector   0         0s
test-k4txm   0/1       Terminating   0         0s
test-k4txm   0/1       Terminating   0         0s
test-gj0r6   0/1       Pending   0         0s

```

**Anything else we need to know?**:

No

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:

Ubuntu 16.04.2 LTS

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
Linux tt-k8s1-w8.ko.seznam.cz 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by resouer** [comment]
I will try to reproduce it and take deep look to see if it's a bug.

**Comment by resouer** [comment]
BTW, @dohnto what's the content in your `--admission-control-config-file` file? Is it like this?
```
podNodeSelectorPluginConfig:
 clusterDefaultNodeSelector: <node-selectors-labels>
 namespace1: <node-selectors-labels>
 namespace2: <node-selectors-labels>
```

**Comment by resouer** [comment]
@dohnto I tried some case and can't reproduce this issue.

Did you enable `PodNodeSelector` in you cluster? i.e. adding `--admission-control=PodNodeSelector,...`  to kube-apiserver configure.

**Comment by dohnto** [comment]
@resouer Yes, I have passed the argument ```--admission-control=PodNodeSelector```, but not ```--admission-control-config-file`. 

So you cannot reproduce it from the minimal use-case using minikube I have provided? That is very strange, what version of minikube/kubernetes do you use?

**Comment by resouer** [comment]
@dohnto It's kubernetes 1.7.5 build from release. No minikube but it should make no difference.

Both annotation and admission-control-config-file work in my env.

**Comment by dohnto** [comment]
You are right, I have tested with different versions of minikube and it seems to be fixed in `1.7.3` but not in `1.7.2`

**Comment by dohnto** [comment]
But I cannot find any Changelog note about that, maybe, it was fixed as a sideaffect. Closing now, thank you @resouer

**Comment by jim-minter** [comment]
@resouer I'm able to recreate this on 1.7.6, it also affects OpenShift.  Are you able to reopen the issue?

I installed on Centos 7 using kubeadm.  

```
[root@localhost ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@localhost ~]# grep admission-control /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota,PodNodeSelector
    - --admission-control-config-file=/etc/kubernetes/accf.yaml
```

```
[root@localhost ~]# cat /etc/kubernetes/accf.yaml
podNodeSelectorPluginConfig:
  clusterDefaultNodeSelector: ""
  test: "realm=test"
```

(note 1: no node is labeled realm=test)
(note 2: I think that maybe omitting the --admission-control-config-file and associated whitelist is the reason why this issue was previously thought fixed)

```
[root@localhost ~]# kubectl create -f - <<'EOF'
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: test
    annotations:
      scheduler.alpha.kubernetes.io/node-selector: "realm=test"

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: test
    namespace: test
    labels:
      app: test
  spec:
    template:
      metadata:
        labels:
          app: test
      spec:
        containers:
        - name: test
          image: busybox
          command:
          - tail
          - -f
          - /dev/null
EOF
```

(removing the annotation scheduler.alpha.kubernetes.io/node-selector: "realm=test" causes things to work fine)

Then `kubectl get pods -n test` returns a different pod every time you run it.  I believe that the reason is that the controller schedules the pod to the node, but the kubelet rejects the pod because its labels don't match the node (having been changed by the admission controller).

On the kube-controller-manager pod you see the following tight loop:
```
I0922 21:00:28.327395       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: test-fhlrb
I0922 21:00:28.912531       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Warning' reason: 'FailedDaemonPod' Found failed daemon pod test/localhost.localdomain on node test-fhlrb, will try to kill it
E0922 21:00:28.927600       1 daemoncontroller.go:254] test/test failed with : deleted 1 failed pods of DaemonSet test/test
I0922 21:00:28.928046       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: test-fhlrb
I0922 21:00:28.941943       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: test-d0g3r
I0922 21:00:29.515387       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Warning' reason: 'FailedDaemonPod' Found failed daemon pod test/localhost.localdomain on node test-d0g3r, will try to kill it
E0922 21:00:29.532152       1 daemoncontroller.go:254] test/test failed with : deleted 1 failed pods of DaemonSet test/test
I0922 21:00:29.532629       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"test", Name:"test", UID:"8c547b3f-9fd8-11e7-87e7-525400d2c2ce", APIVersion:"extensions", ResourceVersion:"11030", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: test-d0g3r
...
```

On OpenShift in the same scenario in the node log we see:
```
Sep 21 10:44:58 ci-prtest-5a37c28-8332-ig-m-rv24 origin-node[16584]: I0921 10:44:58.122964   16584 kubelet.go:1835] SyncLoop (ADD, "api"): "apiserver-6tt97_extended-test-openshift-template-service-broker-7p1hk-7n2lr(e978319a-9eb9-11e7-ab1f-42010a800005)"
Sep 21 10:44:58 ci-prtest-5a37c28-8332-ig-m-rv24 origin-node[16584]: I0921 10:44:58.123086   16584 predicate.go:106] Predicate failed on Pod: apiserver-6tt97_extended-test-openshift-template-service-broker-7p1hk-7n2lr(e978319a-9eb9-11e7-ab1f-42010a800005), for reason: Predicate MatchNodeSelector failed
Sep 21 10:44:58 ci-prtest-5a37c28-8332-ig-m-rv24 origin-node[16584]: I0921 10:44:58.732648   16584 kubelet.go:1851] SyncLoop (DELETE, "api"): "apiserver-m35w7_extended-test-openshift-template-service-broker-tfpw1-rm365(e91be8de-9eb9-11e7-ab1f-42010a800005)"
Sep 21 10:44:58 ci-prtest-5a37c28-8332-ig-m-rv24 origin-node[16584]: I0921 10:44:58.738168   16584 kubelet.go:1845] SyncLoop (REMOVE, "api"): "apiserver-m35w7_extended-test-openshift-template-service-broker-tfpw1-rm365(e91be8de-9eb9-11e7-ab1f-42010a800005)"
Sep 21 10:44:58 ci-prtest-5a37c28-8332-ig-m-rv24 origin-node[16584]: I0921 10:44:58.744899   16584 kubelet.go:2028] Failed to delete pod "apiserver-m35w7_extended-test-openshift-template-service-broker-tfpw1-rm365(e91be8de-9eb9-11e7-ab1f-42010a800005)", err: pod not found
```

@deads2k @aveshagarwal

**Comment by jim-minter** [comment]
I believe that the end effect, that daemonset pods are only sent to the selected nodes, is correct.
The issue here, as I believe the OP states, is the looping recreating pods that are bound to fail.
The condition I've described here is probably a misconfiguration, but it would be good if it didn't cause the looping.

**Comment by jim-minter** [comment]
If I add `nodeSelector: { realm: test }` to the pod template in the DaemonSet manifest, then I get no pods being created, which is expected because there are no nodes labelled realm=test.

**Comment by aveshagarwal** [comment]
@jminter I am able to reproduce this on latest kube master, and here is an explanation, why this issue is happening: 

When DS controller processes a pod template, the pod template does not have updated node selectors. Due to this, the controller creates pod for each node based on the node selectors (either empty or some value) in the pod template. Once pods are created for each node, they go through the admission plugin chain and their node selector gets updated by PodNodeSelector admission plugin. But DS does not have any knowledge of this update. So once a pod is assigned to a node (kubelet) where its selector does not match with that of node/kubelet, the pods get into pending->failed node selector-terminated cycle.

I think one solution is that: dont processes/ignore DS pods by PodNodeSelector admission plugin.

Another solution (kind of ugly), allow PodNodeSelector to update DS's pod spec template, so that pods created for incorrect nodes are not recreated.

Also another way to avoid this issue would be to always set a DS' namespace's node selector annotation to empty so that the DS' pods are never updated by PodNodeSelector plugin.

**Comment by liggitt** [comment]
> one solution is that: dont processes/ignore DS pods by PodNodeSelector admission plugin.

no, *all* pods in a namespace under the control of PodNodeSelector (including DaemonSet pods) must conform to the selector enforced by the PodNodeSelector.

> Another solution (kind of ugly), allow PodNodeSelector to update DS's pod spec template

This essentially freezes the DS selector to whatever the limited node selector for the namespace is at point of creation. This doesn't seem terrible to me.

> Also another way to avoid this issue would be to always set a DS' namespace's node selector annotation to empty so that the DS' pods are never updated by PodNodeSelector plugin.

If you want an unlimited daemonset to be able to run pods on all nodes when using PodNodeSelector, exempting the namespace from selector enforcement is the correct way to do that.

**Comment by deads2k** [comment]
> Another solution (kind of ugly), allow PodNodeSelector to update DS's pod spec template
> This essentially freezes the DS selector to whatever the limited node selector for the namespace is at point of creation. This doesn't seem terrible to me.

that would make it impossible to distinguish: "I want to select nodes like this" and "This is what my pod node selector was yesterday". When the pod node selector is updated, what should happen?  Sometimes it should do X, sometimes it should do Y.

**Comment by liggitt** [comment]
We've had this argument before :)

The alternatives:
* make daemonsets aware of podnodeselector admission
* end up with lots of pods targeting node that will reject them

**Comment by deads2k** [comment]
> We've had this argument before :)
> 
> The alternatives:
> 
> make daemonsets aware of podnodeselector admission
> end up with lots of pods targeting node that will reject them

We have.  Daemonsets aren't resources normal users will make.  Those who make them should make their node selectors agree.  The daemonset controller should also be using the "ramp up pod creation" logic of the rest of the controllers, so if someone gets it wrong, the pain isn't too great.

**Comment by liggitt** [comment]
> Those who make them should make their node selectors agree.

How is that different from the podnodeselector admission plugin forcing the node selector into the daemonset pod template, except that it requires more manual steps? Both cases end up with a daemonset object containing a denormalized copy of the enforced node selector

**Comment by deads2k** [comment]
> How is that different from the podnodeselector admission plugin forcing the node selector into the daemonset pod template, except that it requires more manual steps?

The know their intent. When something changes, they know whether they want "all of the nodes I can" or "these specific nodes, no matter what I'm allowed".  A general bit of code can't know that.

**Comment by a4abhishek** [comment]
I am using Openshift cluster, My DS's Namespace's node selector annotation is empty. Still facing same issue. Can I get any suggestions.

**Comment by aveshagarwal** [comment]
@a4abhishek empty means have you set the annotation to `""`?
