### ISSUE TITLE
Add vultr block storage as persistent volume type

### ISSUE THREAD

**Issue by daurnimator** [kubernetes/kubernetes#51793]
/kind feature
/sig Storage

I'd like to be able to use [Vultr's block storage](https://www.vultr.com/features/blockstorage/) for persistent volumes for my kubernetes cluster.

API: https://www.vultr.com/api/#block
Go Library: https://github.com/JamesClonk/vultr

**Comment by resouer** [comment]
@daurnimator  I guess it would be easy to use [flexvolume](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/flexvolume) to implement your own  Vultr plugin. Make sense to you?

We are avoiding introducing any in-tree volume plugin and proposed CSI already.

**Comment by daurnimator** [comment]
> proposed CSI already.

What is CSI?

> We are avoiding introducing any in-tree volume plugin 

Will the existing cloud provider ones be moved out?

**Comment by resouer** [comment]
@daurnimator See: https://github.com/container-storage-interface/spec

But it's long term effort and can not solve your current problem.

Flexvolume is what I suggest.
