### ISSUE TITLE
AppArmor profile failing to be enforced on large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51791]
The "AppArmor load AppArmor profiles should enforce an AppArmor profile" e2e test in failing on our 5k-node gce clusters - https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness (run no. 8)
due to timeout:

```
Gave up after waiting 5m0s for pod "test-apparmor-bsrnw" to be "success or failure"
```

Seems like the test is trying to load the profiles across all the nodes using a daemonset and then running a test pod to check that. It's passing on our 2k-node clusters (https://k8s-testgrid.appspot.com/google-gce-scale#gce-large-correctness) but failing for 5k - suggesting that it's likely due to size of the cluster. I think it's the ds creation taking longer on large cluster.

cc @kubernetes/sig-node-bugs @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
@tallclair @mtaufen Seems like you're the most relevant here. Could one of you take a look into it?
Does increasing the timeout for the test-pod based on no. of nodes sound reasonable?

**Comment by shyamjvs** [comment]
@mtaufen Assigning it you since @tallclair is OOO. Feel free to reassign as apt.

**Comment by shyamjvs** [comment]
This is part of the correctness suite and large cluster tests are release-blocking.

**Comment by jdumars** [comment]
@countspongebob FYI

**Comment by mtaufen** [comment]
Reassigning to @tallclair, who is back on Tuesday. He wrote the AppArmor stuff and should be able to debug this quickly.
/assign @tallclair

**Comment by shyamjvs** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/51718

**Comment by shyamjvs** [comment]
@tallclair Could you manage to take a look into this?

**Comment by tallclair** [comment]
Sorry, I meant to reply to this! I have a fix, just need to confirm it works. I think you're right about the DaemonSet timing out. There's no reason this needs to load the profiles on every node, so the fix just runs a single loader, and uses pod affinity to co-schedule the test pod.

**Comment by shyamjvs** [comment]
Smooth!
