### ISSUE TITLE
Federation: Support federated ingress outside of GCP

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#51806]
/kind feature

Splitting off the subthread in https://github.com/kubernetes/kubernetes/issues/39989#issuecomment-305356470

This looks like it might have just got easier on AWS and cross-cloud:

[New – Application Load Balancing via IP Address to AWS & On-Premises Resources](https://aws.amazon.com/blogs/aws/new-application-load-balancing-via-ip-address-to-aws-on-premises-resources/)

I haven't gone through all the details yet but this seems like it might form a good base for cross-cloud load balancing.  As usual, the devil will be in the details.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#35.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
