### ISSUE TITLE
Different rate limits for control plane coordination

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#51817]
Pulled out from #49947.

Cluster components use the apiserver to effect changes in the cluster, but also to coordinate with each other (e.g., the scheduler uses it to do leader election).  If we want to support this long term, we need to provide a more reliable channel for these messages, so that the system doesn't stop making progress just because of a lost lease when there is a big backlog of work.

One way is a high rate limit for certain `(client,operation)` pairs.  In this example, `(kube-scheduler,renew)`.

I suspect we will have other components that need to coordinate with each other so that they can actually make progress.

@kubernetes/sig-api-machinery-feature-requests 
/sig scheduling
/kind feature

**Comment by lavalamp** [comment]
We have client side rate limiting. I agree that we should switch to server side rate limiting, and that we probably need different tiers of service for different requests.
