### ISSUE TITLE
Cleanup openapi pkg

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#51823]
Addresses the comments left in https://github.com/kubernetes/kubernetes/pull/51762, including:
- add UT for gvk.go
- tweak the signature and interface a bit to make it better.

**Comment by apelisse** [comment]
Also, you mentionned in a private discussion that we should maybe split the `Definition` and I wasn't too sure at that time what the reason was, but I now agree :-)

We should have:
```
DefinitionDoesntKnowAboutExtensions // This lives in kube-openapi

// And

ResourcesMapExtensionsToModels // This goes in Kubectl
```
