### ISSUE TITLE
User apiserver sidecar [brainstorming]

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#51830]
Basic problem:

You are tasked with upgrading ExampleCorp's cluster from Kubernetes 1.12 to 1.13. ExampleCorp runs 50 different user apiservers from 50 different companies/vendors, and not all of them have published versions for 1.13. 1.13 fixes some critical bugs in the admission control stack.

Claim: **Any feature of the generic apiserver library that doesn't have to be compiled in to a user apiserver, shouldn't be.** (this is an expansion of [my comment here](https://github.com/kubernetes/kubernetes/issues/49038#issuecomment-326127073))

Things that must be compiled in:
* encoding, decoding

Things that don't need to be compiled in:
* applying the dynamic admission control chain?
 * especially including quota?

I'm not 100% sure we are going to end up with a list long enough to justify this effort, but I want to start a conversation. If we did shift this direction, the example apiserver would begin shipping a pod spec, where one container was the example apiserver and the other is this hypothetical sidecar.

The sidecar <-> user apiserver interface would have to be carved in stone for this to make sense, obviously.

The Kubernetes control plane could use its own initializer [edit: admission webhook] to run the correct version of the sidecar.

**Comment by lavalamp** [comment]
cc @caesarxuchao @cheftako @bgrant0607

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-api-machinery-proposals
