### ISSUE TITLE
Cannot build 1.7.5 from the source tarball

### ISSUE THREAD

**Issue by davecheney** [kubernetes/kubernetes#51849]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

download 1.7.5 source tarball from the release page, place it in $GOPATH/src/k8s.io/kubernetes
```
% go install k8s.io/kubernetes/cmd/hyperkube
# k8s.io/kubernetes/cmd/kube-apiserver/app
cmd/kube-apiserver/app/server.go:357:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions
# k8s.io/kubernetes/federation/cmd/federation-apiserver/app
federation/cmd/federation-apiserver/app/server.go:221:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions
```
**What you expected to happen**:

successful build, $GOPATH/bin/hyperkube built

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

1.7.5

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):

ubuntu 16.04

- Kernel (e.g. `uname -a`):

Linux lucky 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xiangpengzhao** [comment]
Try `make hyperkube` instead. I don't think k8s components can be built by `go install`.

/sig release contributor-experience

**Comment by dixudx** [comment]
@davecheney  You need to run bazel to generate [`zz_generated.openapi.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/generated/openapi/def.bzl#L18), that's   where `GetOpenAPIDefinitions` is defined.

**Comment by davecheney** [comment]
Is it possible to include all the generated files with the source tarball?

**Comment by dixudx** [comment]
> Is it possible to include all the generated files with the source tarball?

Since these files can be generated, there is no reason to add such unnecessary files.

**Comment by davecheney** [comment]
It would be great to be able to build from the distributed source alone.

**Comment by dixudx** [comment]
> It would be great to be able to build from the distributed source alone.

You can running `make release` from the source code.

**Comment by davecheney** [comment]
Will do. Thanks for your time.
