### ISSUE TITLE
[kubelet] --node-labels does not work in kubelet

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#51858]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

The kubelet is started with `--node-labels=--node-labels=beta.kubernetes.io/foo=bar` :

```
/usr/bin/kubelet --node-labels=beta.kubernetes.io/foo=bar --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd
```

But there's no label added to kubelet:

```
Name:                   stackube-test
Role:                   
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/hostname=stackube-test
                        node-role.kubernetes.io/master=
Annotations:            node.alpha.kubernetes.io/ttl=0
```

**What you expected to happen**:

`beta.kubernetes.io/foo=bar` should present in node labels.

**How to reproduce it (as minimally and precisely as possible)**:

Start kubelet with `--node-labels=` been set
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes v1.7.5
- Cloud provider or hardware configuration**: baremetal
- OS (e.g. from /etc/os-release): CentOS 7.2
- Kernel (e.g. `uname -a`):  3.10.0
- Install tools: kubeadm
- Others:

**Comment by resouer** [comment]
@Random-Liu I'm not sure it's my only problem yet, but I can re-produce it in all my clusters. cc @feiskyer

**Comment by resouer** [comment]
xref: kubelet ignores some other flags: https://github.com/kubernetes/kubernetes/issues/51275

**Comment by liggitt** [comment]
Was the node previously started and registered? I think --node-labels only applies to the initial node registration

**Comment by resouer** [comment]
@liggitt Oh, yes, I did not notice the label is added after register.
