### ISSUE TITLE
kubectl run --pod-running-timeout doesn't work

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kubernetes#51850]
> /kind bug

**What happened**:
`kubectl run --pod-running-timeout=1m0s` doesn't wait for pods to appear not by default, not explicitly:

      --pod-running-timeout=1m0s: The length of time (like 5s, 2m, or 3h, higher than zero) to
    wait until at least one pod is running

**What you expected to happen**:
Expect it to pause until at least one pod is available.

**How to reproduce it (as minimally and precisely as possible)**:
Get it into the shell script:
```
minikube start --vm-driver=kvm
kubectl run kubermarkets --image=cybernode/cm-app --port=80 --pod-running-timeout=1m0s
kubectl get pods
```
there are no 1m pauses, and the output is the following
```
...
Kubectl is now configured to use the cluster.
replicationcontroller "kubermarkets" created
No resources found.
```

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): "Fedora 26 (Workstation Edition)"
- Kernel (e.g. `uname -a`):  4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by dixudx** [comment]
@abitrolly `pod-running-timeout` should be used together with `attach`. Here you just specify `pod-running-timeout`.

Without `attach`, `pod-running-timeout` will be ignored.

**Comment by abitrolly** [comment]
I've seen that `waitForPodRunning` is only called from attach command https://github.com/kubernetes/kubernetes/blob/55cb667b9ec975664609e736f49713ee24419b81/pkg/kubectl/cmd/run.go#L457 but my user journey is that I want to do a few queries after running deployment. The key is already there, so why not to reuse it?

**Comment by abitrolly** [comment]
I can issue a separate command to wait until `pods` are up - is there any?

**Comment by dixudx** [comment]
> my user journey is that I want to do a few queries after running deployment.

@abitrolly Did not understand what you really mean. This seems has nothing to do with `timeout`. You can still perform your queries.

> I can issue a separate command to wait until pods are up - is there any?

You can combine `kubectl run` and `kubectl get -w pod xyz`.

**Comment by abitrolly** [comment]
> @abitrolly Did not understand what you really mean. This seems has nothing to do with timeout. You can still perform your queries.

I am doing:

    kubectl run depone --image=nginx --port=80
    POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

And POD_NAME is empty, because pods didn't start yet.

> You can combine `kubectl run` and `kubectl get -w pod xyz`.

1. I don't know the name of the pod yet
2. If the pod still managed to start, (-w)atching it for changes will just hang, right?

**Comment by dixudx** [comment]
> And POD_NAME is empty, because pods didn't start yet.

@abitrolly You can `kubectl describe deploy depone` to find the root cause that blocks the creating of pods.

**Comment by abitrolly** [comment]
I mean that running this code leaves POD_NAME empty:

    kubectl run kubermarkets --image=cybernode/cm-app --port=80
    POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

Because `kubectl run` exists immediately without waiting for Pod resource to be created.

**Comment by abitrolly** [comment]
Let me explain once more what am I trying to achieve. I'd like to run pod and wait for it to start to get the POD_NAME for subsequent queries. This doesn't work right now, because `kubectl run` exits immediately without waiting.

**Comment by innovia** [comment]
@dixudx what do you mean attach? 

i dont see a command like that at all.

my use case is to run a job which spins up a pod (usually this takes time cause cluster autoscaler needs to bring up a new node) and to watch for the logs

can you explain how to achieve that?

**Comment by dixudx** [comment]
> what do you mean attach?

@innovia I mean `kubectl run --pod-running-timeout=xx --attach`.

**Comment by innovia** [comment]
@dixudx  this doesnt make sense - the help section for the kubectl logs clearly shows the options for the logs command - either they need to update the kubectl help to reflect that this is a run flag or  fix this

```
Options:
  -c, --container='': Print the logs of this container
  -f, --follow=false: Specify if the logs should be streamed.
      --include-extended-apis=true: If true, include definitions of new APIs via calls to the API server. [default true]
      --interactive=false: If true, prompt the user for input when required.
      --limit-bytes=0: Maximum bytes of logs to return. Defaults to no limit.
      --pod-running-timeout=20s: The length of time (like 5s, 2m, or 3h, higher than zero) to wait until at least one
pod is running
  -p, --previous=false: If true, print the logs for the previous instance of the container in a pod if it exists.
  -l, --selector='': Selector (label query) to filter on.
      --since=0s: Only return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to all logs. Only one of
since-time / since may be used.
      --since-time='': Only return logs after a specific date (RFC3339). Defaults to all logs. Only one of since-time /
since may be used.
      --tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise
10, if a selector is provided.
      --timestamps=false: Include timestamps on each line in the log output
```

**Comment by abitrolly** [comment]
/reopen

Need to test that there is a way to wait for a pod to start.

**Comment by Modelizer** [comment]
This does not work with `kubectl logs` as well.

**Comment by psazonparalect** [comment]
This does not work with kubectl logs as well. version 1.22

**Comment by abitrolly** [comment]
That could probably be triaged sooner with better, reproducible example in the issue description, but I am unlikely to work on that soon.

**Comment by psazonparalect** [comment]
`kubectl apply -f job_example.yaml -n default && kubectl get pods --selector=jobgroup=job-migration --output=jsonpath='{.items[*].metadata.name}' | xargs k logs -f --pod-running-timeout=20s`
output:
Error from server (BadRequest): container "migration" in pod "job-migration-l2drh" is waiting to start: ContainerCreating

My manifest for job:
`apiVersion: batch/v1
kind: Job
metadata:
  name: job-migration
  labels:
    jobgroup: job-migration
spec:
  template:
    metadata:
      name: job-migration
      labels:
        jobgroup: job-migration
    spec:
      containers:
      - name: migration
        image: chentex/random-logger:latest
        imagePullPolicy: Always
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Never
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 150
`
Intresting note: After the first launch command, when the image has already entered the local registry, the log tracking command via kubectl works.
I checked this case in different k8s clusters:

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
