### ISSUE TITLE
[SQ-blocking] Kubemark failing to start hollow-kubelet

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51856]
Seems like kubelet changes breaking kubemark yet again. We've started seeing this at ~16:30 PST yesterday:
https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-kubemark-e2e-gce

cc @jdumars @k8s-oncall @kubernetes/sig-release-members

**Comment by shyamjvs** [comment]
I'm looking at the [diff](https://github.com/kubernetes/kubernetes/compare/44c518218...73326ef01) when our 100-node kubemark CI job (https://k8s-testgrid.appspot.com/sig-scalability#kubemark-100) started failing.

There are 5 PRs, 2 of them are trivial ones and two other seem unrelated. It's almost surely this one:
#51307 Remove deprecated and experimental fields from KubeletConfiguration

cc @mtaufen @kubernetes/sig-node-bugs

**Comment by shyamjvs** [comment]
Fortunately, this time we have hollow-node logs directly available with my PR https://github.com/kubernetes/kubernetes/pull/51834 getting merged.
From one of the hollow-kubelet [logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51848/pull-kubernetes-kubemark-e2e-gce/50160/artifacts/e2e-50160-minion-group-vssd/kubelet-hollow-node-27nmr.log):

```
2017/09/02 07:22:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix: missing address"; Reconnecting to { <nil>}
E0902 07:22:25.095527     183 remote_runtime.go:69] Version from runtime service failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
E0902 07:22:25.100927     183 kuberuntime_manager.go:154] Get runtime version failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
F0902 07:22:25.100951     183 hollow_kubelet.go:93] Failed to run HollowKubelet: failed to create kubelet: rpc error: code = Unavailable desc = grpc: the connection is unavailable. Exiting.
```

It's continuously crashing and restarting with the above error. Seems like a config issue. I'll send out a revert for #51307.

**Comment by shyamjvs** [comment]
It's a shame that kubemark presubmit failed to catch the bug thrice now - sorry about it.
However, with https://github.com/kubernetes/test-infra/issues/4321 fixed, the hollow-node logs are getting collected again and it should now tell us what's going wrong.

**Comment by jdumars** [comment]
@shyamjvs could you elaborate on what, specifically, in kubernetes/kubernetes#51307 is causing the problem?

**Comment by shyamjvs** [comment]
Discussion about that happening under the revert pr.

**Comment by shyamjvs** [comment]
I reverted the revert PR (https://github.com/kubernetes/kubernetes/pull/51859) and the kubemark presubmit passed (as before). And from the hollow-node logs here's what seems to have happened:

- The test creates 5 hollow-nodes (on a single-node base cluster)
- All the 5 hollow-nodes were failing to start their hollow-kubelets and crashlooping due to receiving an empty value for the remote runtime service endpoint (which should've been set to 'unix:///var/run/dockershim.sock' on linux)
- The reason for that is (as @liggitt pointed out), hollow-kubelet is creating it's own KubeletFlags{} instance instead of using `NewKubeletFlags()`
- However after a few crashes, one of the 5 hollow-nodes magically sets the right value for the endpoint and is then able to let the test succeed (which just tries running a single pod in the kubemark cluster)

Here are the logs from the VM - http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/51859/pull-kubernetes-kubemark-e2e-gce/50261/artifacts/e2e-50261-minion-group-1m6g/
The 5th hollow-kubelet is the one where the magic happened.

cc @mtaufen @kubernetes/sig-node-bugs @jdumars

**Comment by shyamjvs** [comment]
3 things to do here:
- Set the RemoteServiceEndpoint in kubemark to the unix docker socket (@mtaufen)
- Change the kubemark presubmit (probably increase the no. of pods created and maybe also the no. of nodes and hollow-nodes) to catch such cases (I'll make the change)
- Understand what the hell happened in that magical hollow-node

**Comment by shyamjvs** [comment]
There are also a couple of other [checks](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scalability/empty.go#L37-L38) in the test that this failure smartly dodged - ones where we check that all nodes are schedulable and healthy. But here kubelets never even registered with the apiserver (except that magical one which did later) in order to be covered by those checks.

**Comment by shyamjvs** [comment]
I'll continue looking on monday.
