### ISSUE TITLE
Should support IPV6 for IPVS

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#51866]
We are working migrating ipv4 to ipv6, we should support ipv6 for IPVS. We should do the following things:

* remove ipv4 constraints of Node IPs(#52935)

* remove ipv4 in pkg/util/ipvs(#53120)

* use ipv6 conntrack tools

* use ipv6 iptables tools

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

/sig network  
/assign @m1093782566  
/cc @danehans

**Comment by leblancd** [comment]
FYI: I've just posted a PR (PR #52028 ) to fix the way that kube-proxy was calling conntrack without the
required "-f ipv6" CLI flag whenever conntrack was being executed for a service that's
using IPv6 addresses. There were a couple of lines in pkg/proxy/ipvs/proxier.go that needed to be
changed. I don't think I can add UT coverage for those lines until more support for IPv6 addresses
is added to ipvs/proxier.go. Cc @danehans

**Comment by m1093782566** [comment]
@leblancd 

ACK!

I will take care of ipvs/proxier.go, please feel free to ping me when you want my hand :)

**Comment by leblancd** [comment]
@m1093782566  Sounds good, ipvs/proxier.go is all yours. :) Likewise, let me know if I can help.

**Comment by m1093782566** [comment]
Sure.
