### ISSUE TITLE
--kubeproxy flag is not honored

### ISSUE THREAD

**Issue by erkules** [kubernetes/kubernetes#51882]
/kind bug
/sig cli

**What happened**:
--kubeproxy is not honored

**What you expected to happen**:

the configfile defined by --kubeproxy to be used

**How to reproduce it (as minimally and precisely as possible)**:

Using following Config:

`# cat controller.yml 
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://10.30.10.1:443
    certificate-authority: /etc/kubernetes/ssl/ca.pem
  name: api
contexts:
- context: 
    namespace: kube-system
    user: controller
    cluster: api
  name: api
current-context: api
users:
- name: controller
  user:
    client-certificate: /etc/kubernetes/ssl/controller.pem
    client-key: /etc/kubernetes/ssl/controller-key.pem`

It is not read when given as option:

`# kubectl --kubeconfig=/etc/kubernetes/ssl/controller.yml  config view
2017-09-04 00:43:13.146836 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-04 00:43:13.146889 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-04 00:43:13.146908 I | proto: duplicate proto type registered: google.protobuf.Timestamp
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
`

While setting KUBECONFIG works:

`# KUBECONFIG=/etc/kubernetes/ssl/controller.yml kubectl   config view
2017-09-04 00:45:00.691309 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-04 00:45:00.691358 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-04 00:45:00.691492 I | proto: duplicate proto type registered: google.protobuf.Timestamp
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://10.30.10.1:443
  name: api
contexts:
- context:
    cluster: api
    namespace: kube-system
    user: controller
  name: api
current-context: api
kind: Config
preferences: {}
users:
- name: controller
  user:
    client-certificate: /etc/kubernetes/ssl/controller.pem
    client-key: /etc/kubernetes/ssl/controller-key.pem
`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration**:

AWS

- OS (e.g. from /etc/os-release):
`NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`
- Kernel (e.g. `uname -a`):
Linux ip-10-12-7-54 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by zjj2wry** [comment]
can not reproduce this, mind add some version info for this issue.（kubectl version）

**Comment by erkules** [comment]
Thx zjj2wry. 
The version is v1.7.4. The full output is the first point under Environment in the initial Post.
