### ISSUE TITLE
`InitializerConfiguration` will impact deployment

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#51883]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

 /kind bug

> /kind feature

**What happened**:

1) Enable `Initializers` admission plugin.

```
root@k8s001:~# ps -ef  | grep apiserver
root      1346     1  3 11:05 ?        00:02:06 /opt/bin/kube-apiserver --logtostderr=false --log-dir=/var/log/kubernetes --v=4 --etcd-servers=http://192.168.56.11:2379 --insecure-bind-address=0.0.0.0 --port=8080 --kubelet-port=10250 --allow-privileged=true --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,ServiceAccount,Initializers,ResourceQuota --apiserver-count=1 --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key --runtime-config=batch/v2alpha1,admissionregistration.k8s.io/v1alpha1 --authorization-mode=RBAC --feature-gates=AdvancedAuditing=true,PersistentLocalVolumes=true,LocalStorageCapacityIsolation=true --allow-privileged --audit-policy-file=/etc/kubernetes/audit-policy.yaml --audit-log-path=/tmp/kubernetes.audit.log
```

You can see I was enabling both `Initializers` for `--admission-control` and `admissionregistration.k8s.io/v1alpha1` for `--runtime-config`

2) Create an InitializerConfiguration
```
root@k8s001:~/cases/init# cat initconfig.yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: sidecar
initializers:
- name: sidecar.initializer.kubernetes.io
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - deployments
```

```
root@k8s001:~/cases/init# kubectl apply -f ./initconfig.yaml
initializerconfiguration "sidecar" created
root@k8s001:~/cases/init# kubectl get InitializerConfiguration
NAME      AGE
sidecar   7s
```

3) Create an deployment
```
root@k8s001:~/cases# cat nginx2.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

```
root@k8s001:~/cases# kubectl apply -f ./nginx2.yaml
Error from server (Timeout): error when creating "./nginx2.yaml": Timeout: request did not complete within allowed duration
```

Creation failed.

4) Create again, report failed due to deployment already exist.
```
root@k8s001:~/cases# kubectl create -f ./nginx2.yaml
Error from server (AlreadyExists): error when creating "./nginx2.yaml": deployments.extensions "my-deploy" already exists
root@k8s001:~/cases#
```

5) `kubectl get deploy` does not report the nginx exist.
```
root@k8s001:~/cases# kubectl get deploy
NAME         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
helm-repo1   1         1         1            1           15h
```

6) `kubectl get deploy my-nginx` report the deploy exist
```
root@k8s001:~/cases# kubectl get deploy my-nginx
NAME       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-nginx   2         0         0            0           15h
```

7) get detail of the deploy
```
root@k8s001:~/cases# kubectl get deploy my-nginx -oyaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2017-09-03T12:07:37Z
  generation: 1
  initializers:
    pending:
    - name: sidecar.initializer.kubernetes.io
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "1499279"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/my-nginx
  uid: 79e0fe59-90a0-11e7-9ac2-08002759511a
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

The `pending` initializers caused the application cannot deployed, but there is no log which can help me troubleshooting such kind of issues.

**What you expected to happen**:
I hope that I can get some log in apiserver telling me that the deployment is going to add soe initializers in pending list.

/cc @caesarxuchao 

/cc @kubernetes/sig-api-machinery-bugs 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
We have some document here claiming follows here https://kubernetes.io/docs/admin/extensible-admission-controllers/#configure-initializers-on-the-fly

> You should first deploy the initializer controller and make sure that it is working properly before creating the initializerConfiguration. Otherwise, any newly created resources will be stuck in an uninitialized state.

But it would be great if we can also provide some logs which can help troubleshooting if user create the `initializerConfiguration` before `initializers`.

**Comment by dixudx** [comment]
@gyliu513 Just as the doc said,

>You should first deploy the initializer controller and make sure that it is working properly before creating the initializerConfiguration. Otherwise, any newly created resources will be stuck in an uninitialized state.

You have not started an initializer controller. So

```
  initializers:
    pending:
    - name: sidecar.initializer.kubernetes.io
``` 

will exist in the deployment metadata. The initializer controller is responsible to make changes and remove such pending initializers afterwards.

> kubectl get deploy does not report the nginx exist.

I've introduced a new flag named `include-uninitialized` in #50497. You can issue such uninitialized objects by `kubectl get deploy --include-uninitialized`. PTAL.

**Comment by gyliu513** [comment]
@dixudx Yes, that would help, but I still hope that we can provide some logs for troubleshooting.

**Comment by dixudx** [comment]
> But it would be great if we can also provide some logs which can help troubleshooting if user create the `initializerConfiguration` before `initializers`.

> I still hope that we can provide some logs for troubleshooting.

@gyliu513 Seems current initializer controllers are customized standalone processes to watch the new-born  resources, such as deployments. If the pending initializer names matched, the controllers will make some changes. It would be difficult to provide such logs, even warnings, if user creates the `initializerConfiguration` before `initializers controllers`.

Correct me if I'm wrong @ahmetb @caesarxuchao.

**Comment by ahmetb** [comment]
I think the apiserver logs are not exactly what would help the end user for objects that got stuck in the uninitialized state. What I'd like to see is an event in `kubectl describe`.

For example, if `Initializer` plugin can add an event with message like:

> Adding pending initializers: sidecar.initializer.kubernetes.io, sidecar2.initializer.kubernetes.io.

It would be easier for users to debug things when they realize "creation failed but somehow object still exists" as they'll probably do, "hmm let me inspect that using `kubectl describe`".

**Comment by caesarxuchao** [comment]
We need to document `--include-uninitialized` (just created https://github.com/kubernetes/kubernetes.github.io/issues/5310).

Totally agree that `kubectl describe` should make it obvious that the deployment is under initialization.

> if Initializer plugin can add an event with message

It sounds good but I noticed that only the PodPreset plugin reports events. Probably it's because of performance concerns, as admission controllers are in the critical path of API responses.

Alternatively we can update kubectl Describers to emphasis if an object is uninitialized.

I think we need to update kubectl Printers as well, so that `kubectl get deployment nginx` will indicate the object is under initialization. I don't know if we still have `Printers`, probably apiserver today returns a tabular response. If that's the case, then we need to update the server-side code.

cc @mengqiy

**Comment by lavalamp** [comment]
> What you expected to happen:
> I hope that I can get some log in apiserver telling me that the deployment is going to add soe initializers in pending list.

apiserver log is not typically visible to users and is not the place we want to report this.

Amending `describe` is a good idea.

Making events on failed, or timed-out, initializations might be another option, although we should think about system load.

**Comment by gyliu513** [comment]
+1 to Amending `describe`.

**Comment by dixudx** [comment]
> I don't know if we still have Printers, probably apiserver today returns a tabular response. If that's the case, then we need to update the server-side code.

@caesarxuchao Yes, we still have printers on `kubectl` client side.

> I think we need to update kubectl Printers as well, so that `kubectl get deployment nginx` will indicate the object is under initialization.

How about adding a new column named `Initialization` for all resources, such as `deploy`, `rs`, `sts`.
