### ISSUE TITLE
tls-cert-file is stored at different locations for variants of apiservers.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#51887]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Not all variants of api servers store the TLS cert files at /var/run/kubernetes. After the commit acba2cb was merged back in Feb, some variants such as kube-aggregator stores them at 'apiserver.local.config/certificates', but the hard-coded help message still says it will save the keys and certs generated into /var/run/kubernetes.

**What you expected to happen**:
Either we refactor the code so the help message prints an accurate location, or we change the help message to make it always true.

**How to reproduce it (as minimally and precisely as possible)**:
`kube-aggregator --help`

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`): at least 1.7 and above
- Cloud provider or hardware configuration**: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by tengqm** [comment]
@deads2k pls help confirm.

**Comment by lavalamp** [comment]
We should make the messages accurate.
