### ISSUE TITLE
[kubeadm] Need to approve csrs after installation.

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#51885]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

After:
 
```
kubeadm init --pod-network-cidr 10.244.0.0/16 --kubernetes-version stable
```
`kubectl logs` won't work (tls error) unless manually approve csrs on master.

```
kubectl certificate approve $(kubectl get csr | awk '/^csr/{print $1}')
```

**What you expected to happen**:

Offline talked with @luxas , manual approve is not expected.

**How to reproduce it (as minimally and precisely as possible)**:

Standard `kubeadm init` is enough.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Cloud provider or hardware configuration**: CentOS 7.2
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by luxas** [comment]
@resouer I need way more information (csr details, controller-manager logs and args, join command, etc)
Also you need to reopen this in the kubeadm repo :smile:

**Comment by resouer** [comment]
@luxas  No need, this can not be re-produced in fresh new installed cluster. It should be related to my env. Thanks!
