### ISSUE TITLE
CI Task  pull-kubernetes-e2e-kops-aws causing AWS EBS storage limit exceeded error

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#51897]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
```
W0904 11:21:50.610] W0904 11:21:50.609206    3004 executor.go:109] error running task "EBSVolume/c.etcd-events.e2e-46620.test-aws.k8s.io" (9m30s remaining to succeed): error creating PersistentVolume: VolumeLimitExceeded: You have exceeded your maximum gp2 storage limit of 20 TiB in this region. Please contact AWS Support to request an Elastic Block Store service limit increase.
```
See full log https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50780/pull-kubernetes-e2e-kops-aws/46620/build-log.txt

Related PR seeing issue - https://github.com/kubernetes/kubernetes/pull/50780

**Environment**:
Kubernetes CI

**Comment by justinsb** [comment]
test-infra issue is https://github.com/kubernetes/test-infra/issues/4361
