### ISSUE TITLE
Replicate cluster health and configuration outside etcd

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#5190]
Since we store both pod data (rc, services, events etcd) and node ip/hostnames in the same etcd instance, sysadmins might go blind because of too many user pods. I feel like hand reviving a cluster should never be necessary, but it's a safety net that people would like to have. Hand revivial might look something like:
- Log into the master and try to bring etcd back up manually
- If etcd is completely down, try to figure out which nodes are healthy
- Route new requests to a cluster bootstrapped with healthy nodes

This is currently very difficult because kubectl won't work, and without kubectl the sysadmin is essentially blind. 

```
$ ./cluster/kubectl.sh get nodes
current-context: "beeps-cluster"
F0309 18:43:01.495362   11274 get.go:173] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

The kubelets on the nodes are running and capable of reporting health status, and the apiserver is up, so it would be nice if we had a fallback. 

IIUC nodecache is now backed by etcd, so that won't work, but we might be able to get the (stale) list of nodes from the cache and ping their kubelets, or record the node hostnames to file, or something.

**Comment by bgrant0607** [comment]
FYI, it's possible to use etcdctl to list all the nodes in the registry.

**Comment by bprashanth** [comment]
I'm confused by the suggestion, I need to know the healthy minions when etcd is dead but the apiserver is up.

**Comment by bgrant0607** [comment]
That's even easier: apiserver should be caching all the state in memory, always.

**Comment by bprashanth** [comment]
That would work if the apiserver directly pinged the kubelets as a fallback if etcd goes down, since I want realtime node health

**Comment by bprashanth** [comment]
I take that back, it would work if the kubelets periodically sent their health and the apiserver had a write through cache. so I guess this will just fix itself when that happens.

**Comment by bgrant0607** [comment]
The plan is for kubelets to post back to apiserver, so apiserver would need to accept status posts in the event that etcd was down. I'm not sure that's a good idea.

Why not focus on getting etcd back up?

**Comment by bprashanth** [comment]
concurrency! 

In the current state of things, etcd gets into a crash loop where it's sometimes not possible to recover it fast enough (i.e it needs say 1G memory for state, + 20% memory to decompress a snapshot, but the machine has only 1G so it keeps crashing after the first OOM). I also don't expect sysadmins to understand the inner workings of etcd, i.e, they'd probably try `sudo /etc/init.d/etcd restart` and if that failed, just setup a new cluster for availability. 

Why not accept status posts when etcd is down?

**Comment by bprashanth** [comment]
also in a world where etcd might not run on the master I need to know where etcd is somehow to try and recover it, ideally that would be stored in some cluster configuration not in etcd.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests
