### ISSUE TITLE
client-go REST decoding into wrong type

### ISSUE THREAD

**Issue by nilebox** [kubernetes/kubernetes#51917]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
client-go REST method `Into` returns nil if a different type of object is returned.

**What you expected to happen**:
error informing about incompatible type returned

**How to reproduce it (as minimally and precisely as possible)**:
if an object of wrong type is passed into method `Into` decoding the result in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L1013, the passed object remains unchanged and `Decode` method returns an object of correct type. In this case, the `Into` method returns `nil`, and no error about wrong type is propagated.

**Comment by dixudx** [comment]
I don't think this is a bug. Just as the comment said, 

> 	// if a different object is returned, see if it is Status and avoid double decoding
	// the object.

it will only check that if the status is `StatusSuccess`, and return an error if not. For other types, default to return nil.

**Comment by lavalamp** [comment]
I think there is a bug here.

/assign @jpbetz
