### ISSUE TITLE
[QUESTION]e2e test failed with "unexpected error (code: 0) in ssh connection to master"

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#51924]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

## 1.**What happened**:
when i run e2e test with command (go run hack/e2e.go -v --test --test_args="--ginkgo.focus=\[Feature:Performance\]"), i got error mesage below:

##   2.Expected error:
      <*errors.errorString | 0xc4209d4c30>: {
          s: "unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:\"error getting SSH client to root@127.0.0.1:8080:22: 'dial tcp: address 127.0.0.1:8080:22: too many colons in address'\"}",
      }
      unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to root@127.0.0.1:8080:22: 'dial tcp: address 127.0.0.1:8080:22: too many colons in address'"}
  not to have occurred

## 3.**What you expected to happen**:
success running test

## 4.**How to reproduce it (as minimally and precisely as possible)**:
cd $GOPATH/src/k8s.io/kubernetes
go get -u github.com/jteeuwen/go-bindata/...
./hack/generate-bindata.sh
make WHAT='test/e2e/e2e.test'
make ginkgo
export KUBECTL_PATH=/usr/bin/kubectl
export KUBERNETES_PROVIDER=local
kubectl config view -o yaml >> /root/.kube/config
go run hack/e2e.go -v -test  --test_args="--host=http://${master_ip}:8080 --ginkgo.focus=\[Feature:Performance\]" >>log.txt

**Anything else we need to know?**:

## 5.**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

- Kernel (e.g. `uname -a`):
Linux ceph-deploy 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

does anybody know how to fix this problem, thank you in advence!

/sig scalability
/priority failing-test
kind/e2e-test-failure

**Comment by mattjmcnaughton** [comment]
In the error message you posed, I see 
```
...error getting SSH client to root@127.0.0.1:8080:22: 'dial tcp: address 127.0.0.1:8080:22: too many colons in address
```

It looks like that segment of the code is trying to use two ports for the ssh connection - `8080` and `22`. 

I believe you're getting the double port behavior because of the `--host` you've specified in `--test_args`.

```bash
go run hack/e2e.go -v -test --test_args="--host=http://${master_ip}:8080 --ginkgo.focus...
```

The host string already includes an unexpected port name (8080), so when the ssh connection code tries to append the typical ssh port (22), there are too many ports.

What happens if you try instead:
```bash
go run hack/e2e.go -v -test --test_args="--host=http://${master_ip} --ginkgo.focus...
```

Hope that helps :)

**Comment by vklonghml** [comment]
@mattjmcnaughton sorry for late, i will try your method, thks a lot

**Comment by yangyangliu9412** [comment]
I encountered the same problem and I have tried the solution by @mattjmcnaughton. It doesn't work out. @vklonghml  I wonder how did you solve the problem in the end?

I tried the command as : go run hack/e2e.go -- -v --test --test_args="--host=http://127.0.0.1 --ginkgo.focus=\[Feature:Performance\]" --provider=local

The error message I got was:

 Expected error:
      <*url.Error | 0xc420760060>: {
          Op: "Get",
          URL: "http://127.0.0.1/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0",
          Err: {
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: {
                  IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
                  Port: 80,
                  Zone: "",
              },
              Err: {
                  Syscall: "getsockopt",
                  Err: 0x6f,
              },
          },
      }
      Get http://127.0.0.1/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0: dial tcp 127.0.0.1:80: getsockopt: connection refused
  not to have occurred

**Comment by yangyangliu9412** [comment]
I solved the problem by "export KUBE_MASTER_IP="http://127.0.0.1". Then I got a new error ;(

**Comment by chenqiangzhishen** [comment]
also I meet the same issue
I tried @mattjmcnaughton 's suggestion, but failed as @yangyangliu9412

**Comment by chenqiangzhishen** [comment]
Please reopen it if you didn't get the solution of the issue @vklonghml , thanks.
