### ISSUE TITLE
[Flexvolume] unmount() is skipped and left metadata file uncleaned

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#51926]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

~~Flexvolume will call `os.Remove()` to cleanup the mount directory. This will return error when there're files in the mount directory.~~

But in [some implementation of flexvolume](https://github.com/kubernetes/frakti/blob/master/pkg/flexvolume/flexvolume.go), we need to write a file to store some metadata since flexvolume binary is "run once" and can not share information between two operations (e.g. `mount` and `unmount` etc). 

It seems like the `unmount` is skipped somehow and left uncleaned metadata file there.

**What you expected to happen**:

The directory been cleaned.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jsafrane** [comment]
`RemoveAll` is very dangerous operation that could potentially delete user data. It's task of the flex driver to clean up its directory on `unmount` so `os.Remove` is enough.

**Comment by resouer** [comment]
@jsafrane Yes, I changed the description of the issue, the root cause seems like `unmount()` is skipped somehow. That's why the metadata file is still there (yes, we did cleanup in `unmount()`)

**Comment by adelton** [comment]
I wonder if it's either driver which doesn't do attaching, and then `mount` and `umount` is used, or it's `mountdevice` and `unmountdevice`. At least that's what https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/nfs vs. https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/lvm suggest.

**Comment by resouer** [comment]
@adelton Fixed. It was due to I am using kubelet 1.7.4 which does not include #50596. Sorry for mess. After upgrade to 1.7.5, everything works.

cc @chakri-nelluri
