### ISSUE TITLE
error validating data: the server could not find the requested resource;

### ISSUE THREAD

**Issue by startopscollab** [kubernetes/kubernetes#51939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**: When I did kubectl create -f  cronjob.yaml I got following message

error: error validating "cronjob.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**: Creating of cron job

**How to reproduce it (as minimally and precisely as possible)**:
I am using yaml from kube docs, namely this one:

apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Centos 7
- Kernel (e.g. `uname -a`): Linux ip-10-1-0-140.us-west-2.compute.internal 3.10.0-514.26.1.el7.x86_64 #1 SMP Thu Jun 29 16:05:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kops

- Others:

**Comment by startopscollab** [comment]
kubectl create -f  cronjob.yaml --validate=false
error: unable to recognize "cronjob.yaml": no matches for batch/, Kind=CronJob

**Comment by dixudx** [comment]
@startopscollab 

* Please make sure you've enabled `batch/v2alpha1=true` in `--runtime-config` when starting `apiserver`;
* Please try quote `batch/v2alpha1`, that is `apiVersion: "batch/v2alpha1"`;

**Comment by zjj2wry** [comment]
ref #50890 i have add fallback for cronjob, if you don't have ```batch/v2alpha1```, will fallback to lower version cronjob
