### ISSUE TITLE
kube-aggregator help message needs improvement

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#51930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
> /kind feature

**What happened**:
```
kube-aggregator --help
...
      --proxy-client-cert-file string    client certificate used identify the proxy to the API server
      --proxy-client-key-file string     client certificate key used identify the proxy to the API server
...
```

**What you expected to happen**:

```
kube-aggregator --help
...
      --proxy-client-cert-file string    client certificate used to identify the proxy to the API server
      --proxy-client-key-file string     client key used to identify the proxy to the API server
...
```

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
@enriquetaso thanks for the update!

This is fixed.

https://github.com/kubernetes/kubernetes/blob/60cd056cb443c23b53240d274df4d5abc85c7aaf/staging/src/k8s.io/kube-aggregator/pkg/cmd/server/start.go#L81-L82

Closing.
/close
