### ISSUE TITLE
Add apiserver metric for #objects of a resource kind

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51953]
I think @fgrzadkowski was suggesting this sometime ago.

@smarterclayton @wojtek-t This will help us with measuring new api SLIs Wojtek proposed in his [doc](https://docs.google.com/document/d/1Q5qxdeBPgTTIXZxdsFILg7kgqWhvOwY8uROEf0j5YBw/edit?ts=598439ca). + we wouldn't need to list all objects each time we want to know their count (at the cost of some extra memory, but it's constant no. of metrics). Maybe some cluster-admin usecases you can probably think of?

If it SG, I'll take up the implementation.

cc @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-feature-requests

**Comment by wojtek-t** [comment]
I think the metric itself can be useful.

I'm not entirely sure how useful it would be for SLIs - it depends how exactly we would be exposing them and where we will be doing different aggregations
[BTW - you should link OSS doc, not google doc: https://github.com/kubernetes/community/blob/master/sig-scalability/slis/apimachinery_slis.md ]

Also, can you please summarize how you would like to expose those metrics? There are couple of questions that can be solved differently on the first glance:
- will apiserver be listing objects from etcd to expose their amount or are we going to use the cacher for it?
- listing from etcd can generate significant overhead, and I'm not a fan of this approach
- if not listing, we can use the state of watch cache to expose it but then:
(a) those metrics can potentially be stale (though then we have probably more serious problems than stale metrics
(b) what about resources for which cacher is not enabled

What I mean is that depending on what we do, the metric itself can impact scalability, so we need to be careful when doing that.


Another point is that depending on what metrics we will exactly expose for SLIs, where aggregation will be happening, etc. this metrics may actually not be needed to implement those [knowing number of objects is necessary only for LIST-related SLIs and when calling lists we probably have the necessary information anyway, so if we expose it correctly, it may not be needed - sorry for just waving hand],


So before saying yes/no, I would like to understand what exactly and how you would like to do.

**Comment by shyamjvs** [comment]
I don't prefer listing the objects (either from storage or cache) because it might end up adding considerable overhead (like you mentioned). My plan is the following:
- On each successful post(/put?) request, counter++
- On each successful delete request, counter--

This should be more light-weight IMO and similar to our current model of collecting some metrics in apiserver (i.e. on a per-request basis). Also I'd be using a gauge-type metric for this which iirc is lighter (in terms of memory and latency) compared to summary/histogram-type metrics which we're already using for different metrics (like latencies, response sizes, etc). Need to do some benchmarking to quantify the impact.

Some assumptions here:
1. When apiserver is started, all the counters will be at 0. This should be consistent with etcd (i.e. no objects of any resource type in it). To handle apiserver restarts, we can probably do an initial list to set the metric values.
2. All creates/deletes happen through requests to the apiserver and there are no other paths to do that (but iiuc this is a basic truth for k8s)
3. We can occasionally miss a few updates leading to slight inconsistency - but maybe we can live with some error? Otherwise we can periodically resync to correct the values - though I don't like how this is taking us closer to a watch-like solution which I wanted to avoid in the first place for overhead reasons.
4. ...something else I'm missing?

> (a) those metrics can potentially be stale (though then we have probably more serious problems than stale metrics

Covered this in point 1 and 3 above (to some extent).

> (b) what about resources for which cacher is not enabled

Good catch - I didn't know about this possibility. I thought all resources use caches (I'm stupid). But my solution above doesn't care about caches since we're measuring right during the request.

Some alternatives I thought about (in decreasing order of my preference):
- We can add these metrics to controller-manager which already holds shared informers for most (all?) object types. Basically we'll add event handlers to each of those shared informers to update the metric. This will eliminate the need to solve 1 and 3 above, and there will also be less server-side load. Maybe add a 'object-counter-controller' or sth?
- [Based on your comment] Use cacher for the resource if present, otherwise list from etcd
- List and get the count whenever you want - but the whole point is this doesn't sound too good on a periodic basis
- Chill

**Comment by wojtek-t** [comment]
> I don't prefer listing the objects (either from storage or cache) because it might end up adding considerable overhead (like you mentioned). My plan is the following:
- On each successful post(/put?) request, counter++
- On each successful delete request, counter--

This won't work in HA setups. So we can't make it.

**Comment by shyamjvs** [comment]
That's a good point. Actually other metrics like request counts, latencies, response size, etc make sense to be separate per apiserver, but this one needs to be same everywhere.
I was thinking of sth like each apiserver still keeps the metric (only that it just counts how many objects have been created using that apiserver - and adding it across all instances should give total objects).
But I think handling restarts will be tricky then, unless we store some state for the apiserver (but I'm not sure storing any state outside etcd is reasonable).

Also, what do you think about the option of using controller-manager?

**Comment by smarterclayton** [comment]
We already do almost this setup in kube-state-metrics.  I'd recommend
starting there - much of this discussion is the same as the arguments
leading to a separate tracker for metrics for this.

**Comment by wojtek-t** [comment]
I think kube-state-metrics is not installed by default in many different setups.

But I agree solving this problem properly without performance overhead probably requires during it externally and if so, Clayton`s suggestion sounds reasonable to me.

**Comment by shyamjvs** [comment]
Thanks for the input. I'll take a look at kube-state-metrics and try adding this metric to it.

**Comment by lavalamp** [comment]
Quota system could maybe do this. I don't think apiserver can reasonably do this.

**Comment by wojtek-t** [comment]
Yeah - if we could somehow expose it from etcd, that would be ideal solution (it's basically where this statistic should live).

**Comment by smarterclayton** [comment]
We have to map ranges to metrics though.

Another option is that we could gather this metric from the storage
periodically.  In etcd3 you can do a range count function this fairly
effective.  When watch caches are on, the size of the watch cache is
effectively this count.  If watch caches are off, you can measure LIST
length as it goes by or do periodic background list count checks.

On Fri, Sep 8, 2017 at 3:31 AM, Wojciech Tyczynski <notifications@github.com

**Comment by gmarek** [comment]
I'm looking into this now. My current plan is to add a periodic range count (as it turns out @smarterclayton also thought about this) and expose this as a metric. If someone know if I need to do some magic to make it work for CRDs I'm all ears (eyes?).
