### ISSUE TITLE
API for Key Management Service (KMS) plugins for secrets encryption key management

### ISSUE THREAD

**Issue by destijl** [kubernetes/kubernetes#51965]
/kind feature

In 1.7 we added the capability to encrypt secrets at the database layer using keys provided in a file on disk on the master. The next logical step is to protect those keys using a Key Management Service such as Vault or the KMS's provided by the major cloud providers. 

In 1.8 via [48574](https://github.com/kubernetes/kubernetes/pull/48574) we added a plugin mechanism and an implementation for Google Cloud KMS.  But this is based on the existing cloud provider integration point, so doesn't help the in-flight [Vault implementation](https://github.com/kubernetes/kubernetes/pull/51760) or any other non-cloud providers. See [design doc for more details](https://docs.google.com/document/d/19SbqLrSC_MpmxbLCxasubRJLaZxgqfw1KeIwg3fHHLU/edit).

As @luxas states in the PR:

> For beta, this has to work with out of tree cloud providers, and API server <-> KMS integration should > be done via some kind of interface, but not by compiling the KMS code into the API server.

This bug will track the effort to add that API interface.

@lavalamp 

@kubernetes/sig-api-machinery-feature-requests
@kubernetes/sig-auth-misc

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests @wlan0 @thockin @andrewsykim @prydie @jhorwit2 
Thank you @destijl for following this up!

Can you @sakshamsharma please link to the doc you wrote up on this matter?

**Comment by sakshamsharma** [comment]
@destijl please include this doc:
[Implementing KMS plugins](https://docs.google.com/document/d/19SbqLrSC_MpmxbLCxasubRJLaZxgqfw1KeIwg3fHHLU/edit?usp=sharing)

**Comment by ncdc** [comment]
fyi @mattmoyer

**Comment by lavalamp** [comment]
cc @cheftako

**Comment by destijl** [comment]
The person we originally had scheduled to work on this in Q4 isn't available. If one of the other people interested in KMS integrations can help push it forward to unblock things that would be great.

@khenidak @kksriram @stevesloka @mattmoyer

**Comment by khenidak** [comment]
Hey @destijl I remember the work was split on 3 phases. Ending at v1.10, which is saving secrets outside etcd, and completely relay on external KMS to store secrets. 

I am trying to understand what this feature exactly is? is this moving the in-tree current cloud provider Kms integration implementation to out-of-tree integration directly with apiserver? are we removing the old integration or keeping both?

**Comment by bgrant0607** [comment]
Also ref https://github.com/kubernetes/community/pull/1134

**Comment by destijl** [comment]
@khenidak the "A plan for secrets" doc is fairly significantly out of date, which I think is where you have the v1.10 idea. I'll try to get to updating and making that more accurate again. 

The current plan is to:

1. create this API, probably a gRPC call from the master to an out-of-process container that runs the KMS provider. The API should be very simple: IIRC it's just encrypt/decrypt.

2. deprecate the current integrations (Google KMS, Vault) and move them to the new API.

@sakshamsharma

**Comment by kksriram** [comment]
@destijl i caught up on the discussion here and on the Azure PR. Where in the k/k code can I find examples of out of tree providers (for other areas in kubernetes) that deal with a similar problem? I assume kms providers are not unique in suffering this problem. 

Webhooks in the authn and authz process?

**Comment by sakshamsharma** [comment]
@kksriram As far as I know, out-of-tree providers are not yet implemented in any stable form in k8s, although an implementation for cloudproviders is in the works. @luxas can perhaps point you to more details on that.

**Comment by luxas** [comment]
@kksriram @sakshamsharma There are out-of-tree cloudproviders in alpha in v1.8 yes, probably beta in v1.9
https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/
https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/
https://kubernetes.io/docs/concepts/architecture/cloud-controller/

Authn/authz webhooks: https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication & https://kubernetes.io/docs/admin/authorization/webhook/

There are other examples as well regarding CRI, CNI, etc. that might be useful, but I don't know exactly what you're after here.

**Comment by kksriram** [comment]
@luxas trying to find examples of out of tree providers elsewhere in kubernetes to see how they handle being loaded, called etc. I'll go take a look at the CCM stuff.

**Comment by ericchiang** [comment]
@kksriram try looking at CRI, since @destijl mentioned above that he was considering a gRPC API with basic encrypt/decrypt calls. https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/apis/cri

**Comment by kksriram** [comment]
A few of us in our team are discussing an initial strawman proposal. I hope to bring it to sig-auth tomorrow. I would have loved to get it out today for reviewers to read, but it might be tonight Pacific time before we can get anything meaningful together.

**Comment by destijl** [comment]
@kksriram that's great! I want to check expectations though: if your intention is to get the API reviewed and implemented for 1.9 and the vault integration rewritten to use it, I think that's unlikely given we're already past feature freeze and code freeze is coming up quickly.

**Comment by destijl** [comment]
@kksriram wrote up a strawman and shared with sig-auth this morning:
https://docs.google.com/document/d/1S_Wgn-psI0Z7SYGvp-83ePte5oUNMr4244uanGLYUmw/edit?ts=59f965e1#heading=h.d26ktd3t9943

**Comment by lavalamp** [comment]
That doc looks pretty good to me.
