### ISSUE TITLE
GCE Cluster is created with a Pending CSR

### ISSUE THREAD

**Issue by jcbsmpsn** [kubernetes/kubernetes#51966]
/kind bug

**What happened**:
Using `cluster/kube-up.sh` to create a GCE cluster on Google Cloud Platform, the resulting cluster starts, but the kubelet running on the master submits a request for a CSR to be signed. That CSR is submitted using the bootstrap certificate, which is not approved for signing server certificates. As a result, the CSR goes to `Pending` and stays there. The kubelet submits a new signing request about once an hour and the `Pending` certificates accumulate.

**What you expected to happen**:

The certificate should not be stuck in `Pending`. If a certificate is needed, it should be auto approved. If no certificate is needed, it shouldn't be requested.

**How to reproduce it (as minimally and precisely as possible)**:
1. `cluster/kube-up.sh`
2. `kubectl get csr | grep Pending`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```➜  kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1816+ce19a22fdfcf4b-dirty", GitCommit:"ce19a22fdfcf4bbea3e850ba01b76c8a524d0cca", GitTreeState:"dirty", BuildDate:"2017-03-28T21:38:54Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.660+81b2731c0dde69-dirty", GitCommit:"81b2731c0dde697bdcfcdbbd05daa749d8fb8fa8", GitTreeState:"dirty", BuildDate:"2017-09-01T23:57:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
Google Cloud Platform

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mikedanese** [comment]
fixed by retrying in sar approver
