### ISSUE TITLE
ci-kubernetes-e2e-gce-alpha-features is failing BeforeSuite: too many bad pods

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#51961]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/priority failing-test

Not sure which sig to add yet
/sig testing

**What happened**:
ci-kubernetes-e2e-gce-alpha-features is failing BeforeSuite since 09/02. Example failure:
```
I0905 17:24:01.360] Sep  5 17:24:01.360: INFO: The status of Pod event-exporter-856ccd8698-vjvss is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod fluentd-gcp-v2.0-44zb6 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod fluentd-gcp-v2.0-9hfm8 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod fluentd-gcp-v2.0-qpsbw is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod kube-dns-7797cb8758-czct8 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod kube-proxy-4fwd7 is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.361] Sep  5 17:24:01.360: INFO: The status of Pod kube-proxy-k9xf6 is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod kube-proxy-rnw8n is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod kubernetes-dashboard-76c679977c-94k8t is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod metrics-server-5dcccdfb48-9fgdh is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod npd-v0.4.1-6nhxv is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod npd-v0.4.1-r7xfr is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: The status of Pod npd-v0.4.1-zxfkx is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0905 17:24:01.362] Sep  5 17:24:01.360: INFO: 15 / 31 pods in namespace 'kube-system' are running and ready (592 seconds elapsed)
...
I0905 17:29:20.741] Sep  5 17:29:20.741: INFO: Error waiting for all pods to be running and ready: 13 / 31 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
I0905 17:29:20.742] There are too many bad pods. Please check log for details.
I0905 17:29:20.742] Failure [915.578 seconds]
I0905 17:29:20.742] [BeforeSuite] BeforeSuite 
I0905 17:29:20.743] /go/src/k8s.io/kubernetes/_o
```

Ref: https://k8s-testgrid.appspot.com/google-gce#gce-alpha-features&width=5&show-stale-tests=
OTOH, ci-kubernetes-e2e-gci-gce-alpha-features does not have the same failure:
https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features&width=5

**Comment by MrHohn** [comment]
From https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-alpha-features/15363/artifacts/bootstrap-e2e-minion-group-3547/kubelet.log.

For kube-proxy, it failed on running init container:
```
remote_runtime.go:209] StartContainer "1b7a785ebe781033cf61fd85be129f250de620aedc17b34e6b51398b68dd6350" from runtime service failed: rpc error: code = Unknown desc = failed to start container "1b7a785ebe781033cf61fd85be129f250de620aedc17b34e6b51398b68dd6350": Error response from daemon: linux mounts: Path /run is mounted on /run but it is not a shared or slave mount.
E0905 18:17:56.606374    3527 kuberuntime_manager.go:667] init container start failed: RunContainerError: failed to start container "1b7a785ebe781033cf61fd85be129f250de620aedc17b34e6b51398b68dd6350": Error response from daemon: linux mounts: Path /run is mounted on /run but it is not a shared or slave mount.
E0905 18:17:56.606428    3527 pod_workers.go:182] Error syncing pod 86ec20bb-9266-11e7-b224-42010a800002 ("kube-proxy-8wc6m_kube-system(86ec20bb-9266-11e7-b224-42010a800002)"), skipping: failed to "StartContainer" for "touch-lock" with RunContainerError: "failed to start container \"1b7a785ebe781033cf61fd85be129f250de620aedc17b34e6b51398b68dd6350\": Error response from daemon: linux mounts: Path /run is mounted on /run but it is not a shared or slave mount."
I0905 18:17:56.606472    3527 server.go:226] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-8wc6m", UID:"86ec20bb-9266-11e7-b224-42010a800002", APIVersion:"v1", ResourceVersion:"516", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod
```

Specifically, it failed on:
```
linux mounts: Path /run is mounted on /run but it is not a shared or slave mount.
```

Looking into whether it is a configuration mistake on manifest.

/assign

**Comment by MrHohn** [comment]
> Looking into whether it is a configuration mistake on manifest.

I believe this is not a configuration mistake. Saw the same issue occurred on some other pods as well:
```
E0905 18:17:59.982793    3527 pod_workers.go:182] Error syncing pod bbff731f40116761ee42bde401aa356e ("e2e-image-puller-bootstrap-e2e-minion-group-3547_kube-system(bbff731f40116761ee42bde401aa356e)"), skipping: failed to "StartContainer" for "image-puller" with RunContainerError: "failed to start container \"461ba9799487e669e3741387b673f14adc1c12bdd1e504646efc0112c8ddef4a\": Error response from daemon: linux mounts: Path /var/run/docker.sock is mounted on /run but it is not a shared or slave mount."
I0905 18:17:59.982855    3527 server.go:226] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"e2e-image-puller-bootstrap-e2e-minion-group-3547", UID:"bbff731f40116761ee42bde401aa356e", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod
I0905 18:17:59.982941    3527 server.go:226] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"e2e-image-puller-bootstrap-e2e-minion-group-3547", UID:"bbff731f40116761ee42bde401aa356e", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{image-puller}"}): type: 'Warning' reason: 'Failed' Error: failed to start container "image-puller": Error response from daemon: linux mounts: Path /var/run/docker.sock is mounted on /run but it is not a shared or slave mount.
...
E0905 18:18:06.843253    3527 kuberuntime_manager.go:691] container start failed: RunContainerError: failed to start container "b1f818f272e4bc4ebf94bac960e1bc49d27926ed3fa69c771d2f85916aa7a442": Error response from daemon: linux mounts: Path /etc/ssl/certs is mounted on / but it is not a shared or slave mount.
E0905 18:18:06.843335    3527 pod_workers.go:182] Error syncing pod 86daee26-9266-11e7-b224-42010a800002 ("fluentd-gcp-v2.0-g27vs_kube-system(86daee26-9266-11e7-b224-42010a800002)"), skipping: [failed to "StartContainer" for "fluentd-gcp" with RunContainerError: "failed to start container \"4dcc7a14048a9355e364f58b1751ae1c7307520f2f90755238833d121580a753\": Error response from daemon: linux mounts: Path /usr/lib64 is mounted on / but it is not a shared or slave mount."
, failed to "StartContainer" for "prometheus-to-sd-exporter" with RunContainerError: "failed to start container \"b1f818f272e4bc4ebf94bac960e1bc49d27926ed3fa69c771d2f85916aa7a442\": Error response from daemon: linux mounts: Path /etc/ssl/certs is mounted on / but it is not a shared or slave mount."
]
```
```
linux mounts: Path /var/run/docker.sock is mounted on /run but it is not a shared or slave mount.
...
linux mounts: Path /etc/ssl/certs is mounted on / but it is not a shared or slave mount
```

Checked the [diff commits](https://github.com/kubernetes/kubernetes/compare/917f9f02e...fc9e214a8), the mount propagation changes (https://github.com/kubernetes/kubernetes/pull/46444) seems suspicious. Looping in storage folks.

@jsafrane  @k8s-mirror-storage-test-failures 
/unassign

**Comment by jsafrane** [comment]
Mount propagation is highly suspicious indeed.

The root cause is that mount propagation alpha feature is enabled, but the host OS does not support that. Looking at the kernel version it's Debian Wheezy. Wheezy runs with the root filesystem with private mount propagation while mount propagation feature in Kubernetes expects that all directories that are used as HostPath volumes are on a mount with shared mount propagation. That results in error `... is mounted on / but it is not a shared or slave mount`.

The easiest option would be updating to Jessie (or COS).

Alternatively, we can enable mount propagation on Wheezy, it's simple `mount --make-rshared <mount>` for all mounts before kubelet starts. I had PR #44389 that enables mount propagation on all Kubernetes installs (via kube-up.sh), but since the feature is alpha I did not want to disturb all installations that don't have the feature enabled.

How can we run #44389 as part of installation for alpha-feature tests?

**Comment by ericchiang** [comment]
Assigning to the 1.8 milestone since this is breaking our gce-alpha-features e2e job.

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
Can we pass in an environment variable in the test job [env](https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-alpha-features.env) so that the mount propagation is only enabled when its set?

**Comment by MrHohn** [comment]
> Can we pass in an environment variable in the test job env so that the mount propagation is only enabled when its set?

@msau42 Not that I know of, as for this CI job alpha features are enabled all together by setting `KUBE_FEATURE_GATES=AllAlpha=true`. cc @krzyzacy

**Comment by ericchiang** [comment]
Don't know have a ton of background on this issue, but what happens when this feature gate gets turned on by default once it reaches beta? If it's not appropriate for all clusters it should probably have an additional flag to enable/disable it. And not only be automatically enabled based on the feature gate.

**Comment by msau42** [comment]
I mean an additional environment variable along with the feature gate.

Also, aren't we deprecating Debian soon?

**Comment by jsafrane** [comment]
> what happens when this feature gate gets turned on by default once it reaches beta

All kubelets then need to run on OS that supports mount propagation of any HostPath directory.

Any distro with systemd is fine. Only those that run something else (=Wheezy) need to re-bind `/` as rshared during boot. This should be clearly documented when we switch from alpha to beta.

**Comment by abgworrall** [comment]
Yep, CVM (debian) is not being supported as of 1.8, and support for it on earlier k8s versions ends on Sep 30. In #51487, we're going to be making COS (GCI) the default node image for testing sometime soon. If moving this testjob from CVM to COS would be helpful right now, that's a fairly easy change to make - set `KUBE_NODE_OS_DISTRIBUTION` to `gci` in the `testjob.env` file.

**Comment by msau42** [comment]
@abgworrall  We already have quite a few test suites (including this one) that have both debian and gci versions. As part of your work, will you be removing all these non-gci suites?

**Comment by abgworrall** [comment]
Arguably yes. It's possible that moving them from CVM to Ubuntu is the right thing to do, but overall that feels like an unscalable approach to OS image testing ( @yguo0905 , @mtaufen, @krzyzacy  )

**Comment by ericchiang** [comment]
> Yep, CVM (debian) is not being supported as of 1.8

Was this deprecation communicated somewhere during 1.7? I don't see it anywhere in the release notes, so it's a little surprising to me as someone who's not actively involved in sig-node or sig-storage.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deprecations

**Comment by yguo0905** [comment]
> I'm going to shovel all the node-image-type to a flag in config.json and we can flip all cvm to gci afterwards.

This would result in many duplicated tests since they are the same tests running on CVM and COS -- we need to convert the CVM ones that do not have a corresponding test on COS, and remove the rest.

I feel like one golden image (COS) would be enough for testing the k8s functionality? The Ubuntu tests are a subset and they are for validating the image.

**Comment by jsafrane** [comment]
From mount propagation point of view, it will work on COS out of the box. I let someone else decide if it's better to fix wheezy by merging #44389 or move to COS.

>> Yep, CVM (debian) is not being supported as of 1.8,

> it's a little surprising to me as someone who's not actively involved in sig-node or sig-storage

It's quite surprising to me too and I am from sig storage. Is it just deprecation on GCE / GKE or whole Kubernetes stopped running on Debian? And which Debian?

**Comment by abgworrall** [comment]
To summarise a bit ...

Container-VM (CVM) was a debian-7 derived OS distro that Google developed and maintained. Google has deprecated that particular distro since ~April this year, with a 'no more updates' deadline of 'September 2017'.

The replacement for CVM is Container-Optimized OS (COS, aka GCI), a linux distro that has ongoing support and maintenance from Google, and a steady stream of updates and bugfixes.

The GCE cluster stuff (and by extension, the automated e2e testing stuff) was mostly using the CVM OS  distro for node images. In #48279, the GCE cluster creation stuff started using COS instead of CVM for new GCE clusters. In this PR, test clusters will now also use COS instead of CVM.

Using COS instead of CVM for GCE clusters is not saying "k8s has stopped supporting debian". It's saying we shouldn't be using an OS distro that is going to stop getting patches in 22 days.

I appreciate this is kinda confused by the fact that the CVM distro was referred to as `debian` in the config files; but where you see `KUBE_NODE_OS_DISTRIBUTION=debian`, it actually triggered use of the CVM images.

**Comment by msau42** [comment]
So IIUC, we're going to be converting this test suite to use COS images soon, so we do not need #44389 to fix the failing tests.

However, we still may want to consider merging #44389 to support users that use Debian-based images (but not CVM).  But we won't have CI test coverage for it anymore.

**Comment by dims** [comment]
@msau42 @MrHohn @abgworrall Anything left to do for 1.8 specifically that has not merged yet? Should we close this or drop 1.8 if so?

**Comment by MrHohn** [comment]
> Anything left to do for 1.8 specifically that has not merged yet? Should we close this or drop 1.8 if so?

Per https://github.com/kubernetes/kubernetes/pull/52120#issuecomment-328577392, CVM is deprecated for 1.8. I'm closing this issue.

**Comment by ericchiang** [comment]
While there isn't release blocker, the e2e job is still failing on our blocking set of tests.

https://k8s-testgrid.appspot.com/release-master-blocking#gce-alpha-features

Re-opening this issue. Can someone remove this e2e test if it's no longer appropriate?

**Comment by jdumars** [comment]
@msau42 @MrHohn @abgworrall  Can someone remove this e2e test if it's no longer appropriate? (ASAP)

**Comment by abgworrall** [comment]
/assign @krzyzacy 
Sen, can you please retire the redundant CVM-variant testjobs inside release-master-blocking ?

**Comment by krzyzacy** [comment]
(obviously munger does not want to close a k/k issue from test-infra)
/close
