### ISSUE TITLE
COS m60 set low pids limit for docker.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#51977]
Forked from https://github.com/kubernetes/kubernetes/issues/51903#issuecomment-327290332.

Since m60, COS set 4000 pids limit for docker.service.

However, currently all containerd-shims are also inside the cgroup, and they are per-container.
Each containerd-shim has more than 10 threads based on the node size:
```
$ $ ps aux | grep containerd-shim
root       4218  0.0  0.0 293100 12588 ?        Ssl  Aug10   1:42 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
root      10240  0.2  0.0 422176  5476 ?        Sl   13:12   0:00 docker-containerd-shim 04065c55d068762a3b55d277874ddb4897315f113f1ac865975ae0ca7eb78151 /var/run/docker/libcontainerd/04065c55d068762a3b55d277874ddb4897315f113f1ac865975ae0ca7eb78151 docker-runc
lantaol   10328  0.0  0.0  23780  2228 pts/21   S+   13:12   0:00 grep --color=auto containerd-shim

$ pstree 10240
docker-containe─┬─nginx───nginx
                └─10*[{docker-containe}]
```

It's not hard to hit the limit, say 100 3-container pods may hit the limit.

We may want to:
1) Either patch kubernetes to change the limit to higher value;
2) Or patch COS directly, since this may be a regression for other COS user, too.

@yujuhong @dchen1107 @adityakali @wonderfly 
/cc @kubernetes/sig-node-bugs

**Comment by dchen1107** [comment]
cc/ @dnardo I guess this is the cause for some docker failures you observed.
