### ISSUE TITLE
[RFC] delete objects that take longer than 15s to initialize

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#51989]
### Motivation:
* It is bad user experience if the object shows up too long time after it's created.
* Long initialization latency means some CREATE requests are asynchronous, which breaks existing clients, causing problems like #48893.

### Solution: enforcing initialization timeout
* Add an apiserver flag `--initializer-timeout`, default to 15s
* If the initialization of an object takes longer than the timeout, either the apiserver or the control-plane will delete the object. 
* After deleting the object, the apiserver returns `NewServerTimeout` , which uses 500 internal error return code. As what 500 indicates, user can safely assume the creation has been cancelled and should retry.

### Why defaulting to 15 seconds
* Currently the default timeout of a short-running (i.e., non-watch) request is 30s. The initializer timeout needs to be less than 30s to keep CREATE requests synchronous.
* We are committed to maintain the 1s SLO for a CREATE request with all Kubernetes-native initializers enabled. It’s reasonable to ask thirdparty initializers to have a combined latency less than 15 seconds.

### Implementation
* In [WaitForInitialized](https://github.com/kubernetes/kubernetes/blob/fc3b8bd58b0b20f549148fccbcbb0498f6f16f27/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L368), if the object isn’t initialized in time, delete it using [deleteWithoutFinalizers](https://github.com/kubernetes/kubernetes/blob/fc3b8bd58b0b20f549148fccbcbb0498f6f16f27/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L478).
* APIserver is stateless and might crash, so we need a controller to garbage collect slow-to-initialize objects. The garbage collector will give objects longer initialization time, e.g., 2x`--initializer-timeout`, to avoid conflicting with apiserver’s decision.

@smarterclayton @lavalamp @deads2k @kubernetes/sig-api-machinery-api-reviews

**Comment by smarterclayton** [comment]
I am not really buying "everything distributed finishes in 15s".  There are lots of disruptions that will bring a pod down for longer than that.  I'm also skeptical that hard fail at 15s improves the experience (it does surface the problem for logging, which is good).

I think some form of boundary is reasonable.  I'm not sure the 1s SLO is a reason to do this - merely an example.  A pod takes more than 1s to start because the core behavior is async.  We hide uninitialized pods to preserve legacy behavior.  But I don't see any reason new clients cannot observe uninitialized resources by default.  It just complicates the workflow.

I think I could live with the things described above, but 15s and 30s seem arbitrary.   Perhaps we should tie the timeout to the users requested or default timeout, and make sure we have a way to propagate that.  Certainly the controller that cleans up the initializers should take into account other things, like removing initializers when their config is removed (unless we orphan them?).  I don't think it's unreasonable that eventually removing the config removes the initializer in a reliable way.

**Comment by smarterclayton** [comment]
My worry with a timeout is that the controller is the useful thing, and the timeout is really something we would want a controller to enforce.

**Comment by lavalamp** [comment]
cc @mml

**Comment by lavalamp** [comment]
(I owe a response here)

**Comment by smarterclayton** [comment]
Yeah I was thinking more about the behavior of removing an initializer and cleanup.  I really expect cleaning up an initializer config to happen for me, and to furthermore cleanup any pending initializations.  It doesn't seem unreasonable for that controller to enforce a liveness guarantee on pending initializations, but to do so in a controlled manner. 

We had talked about the API servers handling this via read repair.  But I think for cleanup of an initializer config there should be a graceful deletion phase where the Ic isn't removed until all resources are purged of their pending initializers.  And in that model, that implies a controller with visibility into initialized resources which could also perform liveness checking on the initializer config and potentially reflect that status in the IC, taking action as necessary.

**Comment by smarterclayton** [comment]
Also, if we do want to fail open for fail closed, the hypothetical controller can perform both actions.  Alternatively, if the apiservers track this for us, the cluster is not at risk of failure if the initializations controller goes down.

**Comment by lavalamp** [comment]
@smarterclayton it sounds like you're totally on board with there *being* a limit and a clean-up controller. I guess the only disagreement is what the default value for the limit ought to be?

I think it should be short, or cluster users will have a bad experience. I'm totally fine with it being flag-controllable, so the cluster admin can increase it if they know they have a slow initializer.

I can see an argument for letting it be set to a non-default value per-object at creation time, but that seems unnecessarily complex unless someone has a reallllly good use case.

**Comment by caesarxuchao** [comment]
>  I really expect cleaning up an initializer config to happen for me, and to furthermore cleanup any pending initializations. 

Instead, can we just let these pending initialization time out, and let the hypothetical controller delete the objects?
After deleting the ic, the cluster admin should wait 1s+initialization_timeout before turning off the initialization controller. Any pending initialization should be handled by then. And if there are remaining uninitialized objects, they would be deleted by the hypothetical controller anyway.

> could also perform liveness checking on the initializer config and potentially reflect that status in the IC

Let the hypothetical controller report initializer controller status sounds like a good idea. It can report what's the last time it deletes an object because the initializer times out, and total timed out objects.

**Comment by lavalamp** [comment]
> I really expect cleaning up an initializer config to happen for me, and to furthermore cleanup any pending initializations.

We can solve this with documentation: remove your initializer from the dynamic config, wait 30s (or whatever the timeout is), then stop your initializer controller.

**Comment by lavalamp** [comment]
I think the operation of verifying liveness of initializers is not the same as the operation of deleting objects that have taken too long to initialize. Maybe they can run in the same process, but there's no reason to do them both at the same time.

**Comment by smarterclayton** [comment]
Hrm - I think the point I was trying to make was that if an initializer is
expected to be alive and actions are attached to that liveness, then the
actions taken when liveness fails are tied to the thing evaluating
liveness, not the timeout.  I.e. "timeout" is a non-local action, whereas
"if liveness fails, resources with that initializer either fail or
continue" is a local action and easy to reason about.  Delete and wait is
spooky action at a distance (in some respects)

Another point - 30s is slow enough that the user is still waiting for
something to happen (and many of the resources that humans act on will not
have initializers, but many of the resources that machines act on will have
initializers) and an extra 15s or 30s isn't really an issue.  If we delete,
the user has to take a positive action to correct.  If we wait longer, it's
very likely the initializer will come back (however long it takes for a pod
to get rescheduled, pull, and start over).  If by waiting 30s we take the
user's time, AND the user ends up having to still wait for the initializer
to come back on their repeat action, doesn't that mean the user has to do
more work than they would if the timeout was substantially longer?

I feel like the point of the timeout as described in the original issue is
to make the user aware of a problem.  But an active user is probably aware
nothing is happening, while a passive / machine actor probably just doesn't
care.  The timeout isn't about letting the system make progress really -
it's just about giving a human a clue.  Is there a better way to give a
human a clue?
