### ISSUE TITLE
Remove timeout query parameter

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#51994]
The apiserver [parses](https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.0/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L395) the `timeout` query parameter, and uses it as the time limit when handling CREATE/PATCH/UPDATE/DELETE. I think this query parameter should be removed because
* Our SLO for non-streaming, single object API call is 1s, so the apiserver can safely timeout these verbs after a fixed number of seconds (currently the default is 30s). It doesn't need user's input.
* Clients can use the [http Client](https://golang.org/pkg/net/http/#Client)'s Timeout field if they want the behavior.
* The query parameter is not documented in swagger or our API doc, so perhaps not many people depend it. Removing it is not a big deal.

Note that Watch [respects](https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.0/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L344) `listOptions.timeoutSeconds`, not the `timeout` parameter.

cc @smarterclayton @lavalamp @mbohlool @kubernetes/sig-api-machinery-api-reviews

**Comment by dixudx** [comment]
@caesarxuchao SGTM. +1.

**Comment by mbohlool** [comment]
SGTM too. Specially because it, as you mentioned, it is not documented and duplicate. It is also create confusion for users as there are two timeout (http connection timeout and this one) and they don't know which one is honor by which part of the system.

**Comment by lavalamp** [comment]
SGTM!

**Comment by smarterclayton** [comment]
What about waiting for uninitialized resources?

**Comment by dixudx** [comment]
> What about waiting for uninitialized resources?

Just as @caesarxuchao said above, with appending `?includeUninitialized=true` as query parameter, clients can use the http Client's Timeout field if they want the behavior. Also the apiserver can safely timeout these verbs after a fixed number of seconds (currently the default is 30s).
