### ISSUE TITLE
Support for FPGA as a resource

### ISSUE THREAD

**Issue by tangzhankun** [kubernetes/kubernetes#51999]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
FPGA is becoming popular in data centers nowadays. More and more applications( including ML/DL) will utilize it to boost performance.  The hardware vendors such as Intel also invest in such area. So supporting for such a flexible, high performance-per-wat hardware accelerator in k8s is necessary.

We know that the hardware accelerator framework design is in progress. Please refer to [hardware-accelerator](https://github.com/kubernetes/community/pull/844) and [device -plugin](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/device-plugin.md). 

**What you expected to happen**:
This thread will focus on FPGA family accelerators's plugins and documents following above framework design. Discussions related to FPGA plugins common requirements that may needs framework changes to support also in here.

**Comment by dixudx** [comment]
@vishh PTAL. Related to your wip proposal.

**Comment by kargakis** [comment]
@kubernetes/sig-node-feature-requests

**Comment by ConnorDoyle** [comment]
Just 2 thoughts:

- issue description correctly points to device plugins as a prereq which should help to enable out-of-tree support.
- if we see proliferation of device plugins early on it might raise priority for centralizing the plugin ecosystem somehow

**Comment by vishh** [comment]
We can use this issue to possibly coordinate, but implementations of plugins have to reside out of tree. To begin with if someone can write up a document that summarizes the ecosystem around commonly used FPGAs, describe the use cases, usage patterns, application and orchestration requirements, that would be a good starting point.
I'm hoping with device plugins, these discussions can happen without requiring upstream maintainer involvement.

**Comment by tangzhankun** [comment]
@vishh Yeah, agree that the plugin code should be out of tree and a summary document is a good start.
We'll provide a draft.
@ConnorDoyle Could you elaborate the idea of plugin ecosystem?

**Comment by ConnorDoyle** [comment]
@tangzhankun yeah, it was a topic that was discussed informally during Resource Management Workgroup meetings a few months ago.

The main idea is to provide good user experience for consumers of device plugins. Here you can imagine a continuum of scenarios. On the extremely-decentralized end users would search the web for "Kubernetes + my-device" and try to figure out which one is the best fit based on GitHub README docs of varying quality and completeness. On the extremely-centralized end of the spectrum could be something like a mobile phone app marketplace, with a chain of trust spanning the user and the software vendor. Something in the middle could be a model based on one of the Linux package managers.

Some desirable qualities we talked about were:
- provide an easy way to find plugins, perhaps with a centralized registry
- normalized compatibility matrix (K8s, plugin, device, maybe drivers)
- provide guidelines on support level (alpha, beta, GA) and what each means
- encourage best practices for deployment

**Comment by ddysher** [comment]
@ConnorDoyle seems device plugin is going alpha in 1.8, is there any example plugin to take a look at?

**Comment by tangzhankun** [comment]
Please don't close this issue since the Intel-Docker on the FPGA accelerator is making headway. The plugin is too.

**Comment by dims** [comment]
looks like we can close this now? given support in the community like https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/cmd/fpga_plugin/README.md

/close
