### ISSUE TITLE
Terminating state of pod lasts too long

### ISSUE THREAD

**Issue by pshizhsysu** [kubernetes/kubernetes#52004]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**Labels**

> @kubernetes/sig-Node-bugs

**What happened**:
When deleting a deployment,  a pod stays "Terminating" state too long
> kubectl get pod -o wide | grep orderdeal
> m2m-orderdeal-2-1848417580-0n180                   1/1       Terminating   0          4d        <none>           10.142.233.108

There are no events by executing "kubectl describe pod m2m-orderdeal-2-1848417580-0n180"

I inspect the log of kubelet in 10.142.233.108, it says:
> docker_manager.go:1539] No ref for pod '"0b3742f44a88d269d823eeed72c70e7206ee68f0c7713a21ace7a1fb19e3c63e m2m-orderdeal-2 default/m2m-orderdeal-2-1848417580-0n180"'  

Then I check whether containers of the pod exist, just find that "pause" container has been deleted while the "orderdeal" container not

> docker ps | grep m2m-orderdeal-2-1848417580-0n180
> 0b3742f44a88        10.142.233.224:8021/m2m_product/ctg-m2m-orderdeal-war-alogic.war:1.0.0_Release-SNAPSHOT-7966       "/bin/krun.sh"           10 hours ago        Up 10 hours                             k8s_m2m-orderdeal-2.70ae298_m2m-orderdeal-2-1848417580-0n180_default_10f49274-8f50-11e7-903b-6c92bf1c00a8_3196f7cb

I tried to delete this container by "docker stop 0b3742f44a88 && docker delete 0b3742f44a88", while a moment later, the containers was created and running again 

**How to reproduce it (as minimally and precisely as possible)**:

so far I don't know how to reproduce this situation

**Environment**:

- Kubernetes version
>$ kubectl version
>Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.12", GitCommit:"19e81afecf5eb2b7838c35e2cbf776aff04dc34c", GitTreeState:"clean", BuildDate:"2017-04-20T21:01:06Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.12", >GitCommit:"19e81afecf5eb2b7838c35e2cbf776aff04dc34c", GitTreeState:"clean", BuildDate:"2017-04-20T20:55:26Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

- Docker Info
> Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

>Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
[docker@NM-302-SA5212M4-BIGDATA-2016-036 ~]$ docker info
Containers: 58
 Running: 53
 Paused: 0
 Stopped: 5
Images: 34
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 188.6GiB
Name: NM-302-SA5212M4-BIGDATA-2016-036
ID: 4DNK:GYCF:ZH3K:ACE6:H6DA:XINN:BWSB:IWB4:LB6D:ITL4:PPVP:WZWM
Docker Root Dir: /app/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.142.233.97:8021
 127.0.0.0/8
Live Restore Enabled: false

>WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.

**Comment by jiaxuanzhou** [comment]
would you paste some detailed info in kubelet.log to check the terminating behaviour of kubelet ?
Or you can try to config the graceful time in deployment template to shorten the terminating state.

**Comment by ShawnMilo** [comment]
If you're on Kubernetes 1.4 then I think this is a known issue. Under some circumstances you can have an oom issue, and there is no solution except restarting or replacing the node. Possibly due to not having the right `limits` (`limitranges`) set and having a pod use too much memory, causing a stability issue with Docker on the node. I believe I read that it's fixed in Kubernetes 1.7, but I did a quick search and wasn't able to find the issue where I read this stuff.

You _will_ be able to find a command that lets you delete the pod if you search around, but if you read the fine print, it _does_ delete it from the list when you run `kubectl get pods`, but it doesn't necessarily actually delete the pod from the node.

**Comment by everett-toews** [comment]
@pshizhsysu Is your pod using any `initContainers`?

I ran into similar symptoms in https://github.com/kubernetes/kubernetes/issues/54814
