### ISSUE TITLE
Node Annotations in Downward API

### ISSUE THREAD

**Issue by cliffburdick** [kubernetes/kubernetes#52000]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind feature

**What happened**:
The Downward API should provide a way to pull the node annotations.

**What you expected to happen**:
Currently the pod annotations are available from the interface, as well as a few pieces of information about the node:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

However, the node annotations are not available.

**How to reproduce it (as minimally and precisely as possible)**:
Not available.

**Anything else we need to know?**:
no

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration**: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0
- Install tools:
- Others:

**Comment by liggitt** [comment]
the downward API is intended to provide information from the pod object, not fields from other objects

**Comment by cliffburdick** [comment]
@liggitt It looks like Node IP and Node Name are already part of the API. Is there a better way to do that?

**Comment by liggitt** [comment]
that is because those are fields on the pod
