### ISSUE TITLE
Please remove port range restriction for nodePort field on nodePort type Services

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/kubernetes#52029]
Feature Request:  Please remove port range restriction for nodePort field on nodePort type Services

Rationale:

From the documentation:   _If you want a specific port number, you can specify a value in the nodePort field, and the system will allocate you that port or else the API transaction will fail (i.e. you need to take care about possible port collisions yourself). The value you specify must be in the configured range for node ports._

This restriction seems backwards to me.   It seems to me that a manually specified nodePort field should always be *outside* of the configured range for node ports.   The whole point of of nodePort is to make it externally accessible, (typically by opening a hole in the firewall) so I want to be extra sure that Kubernetes will never put a different service on that port if I ever remove that service but forget to close the firewall hole.

Specifying a value outside the range will also make taking care of possible port collisions easier.

**Comment by liggitt** [comment]
@kubernetes/sig-node-feature-requests 
@kubernetes/sig-network-feature-requests
