### ISSUE TITLE
kubectl get nodes should show API server version not client version

### ISSUE THREAD

**Issue by 2vcps** [kubernetes/kubernetes#52020]
/kind bug

**What happened**:
When doing kubectl get nodes version seems to be the client version.
Example

xxx@z-kube1:~$ kubectl get nodes
NAME      STATUS    AGE       VERSION
z-kube1   Ready     21d       v1.7.3
z-kube2   Ready     20d       v1.7.3
z-kube3   Ready     20d       v1.7.3

xxx@z-kube1:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**What you expected to happen**:
I would expect the "server version" to be displayed when the get nodes command is issued.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.8 and 1.7.3
- Cloud provider or hardware configuration**: VM
- OS (e.g. from /etc/os-release): "16.04.3 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):
Linux z-kube1 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dixudx** [comment]
@2vcps The version displayed here is `KubeletVersion`. Please check the version of your `kubelet` whether is `v1.7.3`.

**Comment by 2vcps** [comment]
kubelet version is 1.7.3. This makes sense. 
Little confused as my "server" version is showing 1.6.8, thought this all should match. Might be my own tweaking that caused this. Is it possible to make it more clear of what "version" each command is referring to? or is this something I should have known on my own. Thanks.

**Comment by dixudx** [comment]
> Is it possible to make it more clear of what "version" each command is referring to?

You can enable verbose log to see the full requests, such as `kubectl -v=10 get deploy`.

**Comment by spzala** [comment]
@2vcps hi, just wondering, seems like this issue can be closed now as it's no more a bug? Thanks!

**Comment by dixudx** [comment]
/close

Since this is not a bug, just a question.

**Comment by spzala** [comment]
@2vcps just fyi, https://stackoverflow.com/questions/tagged/kubernetes  is a good place to ask k8s questions. @dixudx thanks!
