### ISSUE TITLE
When I used configmap to mount assign directory , but it override the file in this  directory

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#52026]
**Is this a BUG REPORT or FEATURE REQUEST?**:

When I used configmap to mount assign directory , but it override the file in this  directory
 /kind bug
/kind feature

**What happened**:
my version is 1.4.6, and in 1.7.1 it also happened

kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.6-32+10d8ac899ab56c", GitCommit:"10d8ac899ab56c6d49dcdb3e155f9ebb98c498aa", GitTreeState:"clean", BuildDate:"2017-02-23T14:40:56Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.6-32+10d8ac899ab56c", GitCommit:"10d8ac899ab56c6d49dcdb3e155f9ebb98c498aa", GitTreeState:"clean", BuildDate:"2017-02-23T14:30:07Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}

step1： I created this configmap：

apiVersion: v1
data:
  DASHBOARD.CONF.INI: |
    [mysqld]
    log-bin = mysql-bin
    [port]
    serviceport="80"
  IMAGE_VERSION: v2.0
  OTHERKEYsdadasd: OTHERVALUE
  REPLICAS: "3"
kind: ConfigMap
metadata:
  creationTimestamp: 2017-09-06T14:14:54Z
  labels:
    cloud.tencent.com/config-id: ccscf-9tbe3089
    cloud.tencent.com/used-by-service: nginx
    cloud.tencent.com/version: v2-0
    cloud.tencent.com/version-id: "1135"
  name: nginx-ccscf-9tbe3089-v2-0
  namespace: default
  resourceVersion: "1922100704"
  selfLink: /api/v1/namespaces/default/configmaps/nginx-ccscf-9tbe3089-v2-0
  uid: c104ec0f-930d-11e7-be21-52540097701a

step2： I mount the REPLICAS to /etc/nginx  directory
     volumeMounts:
        - mountPath: /etc/nginx
          name: vol
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: REPLICAS
            mode: 511
            path: REPLICAS
          name: nginx-ccscf-9tbe3089-v2-0
        name: vol

There are some file in this directory in the images.

root@nginx2-3443468116-eq8j5:/etc/nginx# ls
conf.d		koi-utf  mime.types  nginx.conf   uwsgi_params
fastcgi_params	koi-win  modules     scgi_params  win-utf

step3: when I mount the configmap key to the pod, the files in /etc/nginx directory  is missing. I could only find the REPLICAS. 

root@nginx-546980478-zgahi:/etc/nginx# ls
REPLICAS

I expected the  REPLICAS file could be added to the directory, but it replace the directory then added the file.

**Comment by dixudx** [comment]
any detailed info? like Kubernetes version, related yaml files and how to reproduce it?

**Comment by liggitt** [comment]
volume mounts shadow any existing files in the specified directory
