### ISSUE TITLE
GKE e2e tests are failing to come up

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52045]
Master release blocking e2e tests are currently failing to come up. For example:
https://k8s-testgrid.appspot.com/release-master-blocking#gke

GCE tests are fine.

cc @kubernetes/test-infra-maintainers 
cc @spxtr (current testinfra on call)
cc @kubernetes/kubernetes-release-managers

**Comment by zmerlynn** [comment]
I've got an internal fix out for this that's being deployed imminently.

**Comment by krzyzacy** [comment]
cc @abgworrall

**Comment by zmerlynn** [comment]
I'm not clear why the top comment says "GCI tests are fine." `gke-gci` is just as red. (FWIW, this was injected by #51816 because one of the pods we deploy on masters was using the old `init-containers` notation.)

**Comment by abgworrall** [comment]
@zmerlynn , I've interpreted that as 'non-GKE tests are fine'.

**Comment by ericchiang** [comment]
@zmerlynn yes, sorry I meant pure gce tests. (too many initialisms)

**Comment by zmerlynn** [comment]
Up went green: https://k8s-testgrid.appspot.com/google-gke#gke. Closing!

**Comment by roberthbailey** [comment]
Thanks for jumping on this @zmerlynn
