### ISSUE TITLE
[network-policy] add e2e tests for EgressRule

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#52040]
Test Cases: 
- [ ] Egress blocking based on cidr to a set of pods
- [ ] Egress blocking based on namespace to a set of pods
- [ ] Egress blocking based on a set of pods to another set of  pods

**Comment by cmluciano** [comment]
Update: I'm working to try to enable these new features in a few CNI plug-ins so the tests can run locally.

**Comment by dims** [comment]
@cmluciano Can we please move out of 1.8 milestone?

**Comment by dims** [comment]
@cmluciano Can we please move out of 1.9 milestone? :)

**Comment by cmluciano** [comment]
this will be partially fixed with https://github.com/kubernetes/kubernetes/pull/55186 . I think it is safe to keep in the milestone.
