### ISSUE TITLE
make zsh completion work when the command isn't exactly `kubectl`

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#52050]
I have a zsh function called `kc` which runs `kubectl` for me.  I cannot figure out how to repurpose the zsh tab completion to work with it though.  The best I could come up with (using `complete -o default -o nospace -F __start_kubectl kc`), it refuses to complete unless the exact word `kubectl` is present.

```
% kc <C-d>
kubectl
% kc kubectl get n<TAB>
% kc kubectl get namespace
namespace      networkpolicy  node
```

If there is some trick that fixes this, that's fine.  Otherwise maybe we should just emit a zsh completion function in a zsh-native way.

/sig cli

**Comment by pwittrock** [comment]
@mml Thanks.  I don't think we have bandwidth to support zsh right now unless some zsh user wants to tackle this.  Closing for now, feel free to reopen in 6 months.

**Comment by marckhouzam** [comment]
Not sure if this is still issue is still relevant but still, in case it can help someone. 

For me, zsh completion works great with *aliases* but not with *functions*. 
If you define kc as a function:
```
kc(){kubectl $@}
```
then completion does not work (or at least I don't know how to make it work).
But if you define kc as an alias:
```
alias kc=kubectl
```
then completion works great.
