### ISSUE TITLE
Binding normal user to read pods only

### ISSUE THREAD

**Issue by codrut51** [kubernetes/kubernetes#52081]
I tried binding a normal user to read pods only but it still has access to read deployments and everything. The .yml document that I used is this: 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
- kind: User
  name: "dcnexttest@gmail.com"
  namespace: kube-system

**Comment by codrut51** [comment]
@assign user

**Comment by MHBauer** [comment]
I am not a sig-auth guy, but I've been messing with rbac stuff lately.

1. I don't have the `pod-reader` clusterrole by default on my setup. What does that clusterrole look like? 
2. Are you sure that user is not bound using a clusterrole with higher access?
3. Are you sure you are using that user when you connect?

**Comment by codrut51** [comment]
The role looks like this: 
kubectl create role pod-reader \
    --verb=get \
    --verb=list \
    --verb=watch \
    --resource=pods \
    --namespace=ns-1

**Comment by codrut51** [comment]
2. and 3. I created a user that has access to the cluster is not an admin or something like it.

**Comment by codrut51** [comment]
@MHBauer what role should be assigned to a normal user just to have access to the cluster? (I want to make sure that I did that correctly)

**Comment by liggitt** [comment]
Your binding is to a clusterrole with the name pod-reader, but you defined a role, not a clusterrole

**Comment by codrut51** [comment]
So I should use a clusterrole instead of a role?

**Comment by liggitt** [comment]
Yes
