### ISSUE TITLE
Unclear openapi cache strategy 

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#52089]
This pr https://github.com/kubernetes/kubernetes/pull/50404 introduced http cache into discovery client, only cache swagger file, and refetch depend on `If-None-Match` or sth else,  if I understand correctly, but from my observation, the behavior is unclear:

1. When I execute command like:
`kubectl create -f ~/xxx.yaml`  it will cache the openapi resource every time, seems even when I remove `http-cahce` folder and invoke this command again immediately, it will cache the binary file again. but some other command won't like this.

2. When I execute command like:
`kubectl get ... `  most of the time it won't cache the binary file from server, but sometimes it works, maybe 10min ttl ? (not sure yet)

3. When I execute command like:
`kubectl version`  it won't cache swagger file, instead of the response of GET
```
shiywang:.kube root $ cat http-cache/11ca6725dc674b71725152bc42cddfbf
HTTP/2.0 200 OK
Content-Length: 288
Content-Type: application/json
Date: Thu, 07 Sep 2017 13:22:23 GMT

{
  "major": "1",
  "minor": "9+",
  "gitVersion": "v1.9.0-alpha.0.243+156c4b443b005e",
```
I'm a little confused about the behavior above, also if we execute `kubectl create -f ...` with loglevel=10, it will print kind of `spew.Dump()` format output of binary data of swagger file, the output log is too long sometimes just take 5mins to print the whole result.

@apelisse @pwittrock  @liggitt  @mengqiy  @kubernetes/sig-cli-maintainers

**Comment by liggitt** [comment]
> kubectl create -f ... with loglevel=10, it will print kind of spew.Dump() format output of binary data of swagger file, is that right ?

loglevel 10 is requesting network trace, so it is expected you would see the content of discovery/schema docs

**Comment by liggitt** [comment]
> but some other command won't like this.

can you clarify what you mean by this?

**Comment by pwittrock** [comment]
My understanding is that the discovery service is cached using a different mechanism from the one in the linked PR.  The ttyl on that cache is 10m.

**Comment by shiywang** [comment]
@liggitt @pwittrock Thanks for explain, to be clear, my concern is enable this new cache mechanism via discovery request implementation isn't fine grain enough.

My understanding is this openapi (swagger2.0) is introduced to replace old swagger schema and only cache `swagger-2.0.0.pb-v1` (instead of discovery information) from server so that we could do some openapi validation in commands likes: `create`, `replace`, `convert`, `apply` etc... 

But currently we enable this http cache only by trigger [here](https://github.com/kubernetes/kubernetes/blob/d6348cc1ff72be719e0830da2c64ef1689499956/staging/src/k8s.io/client-go/transport/round_trippers.go#L62) which will cause command as long as using discovery client interact with server will be cached, as @pwittrock you said, those are two different mechanism, if so why we should cache discovery information here ? unless it will be deprecated soon.
```
shiywang:http-cache root $ more f56dd43c086a10001f66138611b7f541
HTTP/2.0 200 OK
Content-Length: 292
Content-Type: application/json
Date: Fri, 08 Sep 2017 07:51:11 GMT

{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"networking.k8s.io/v1","resources":[{"name":"networkpolicies","singularN
ame":"","namespaced":true,"kind":"NetworkPolicy","verbs":["create","delete","deletecollection","get","list","patch","update","watch
"],"shortNames":["netpol"]}]}
```
for some other command directly invoke discoveryclient like `kubectl apiversions` will not only cache discovery information, also cache response of server information.

```
shiywang:http-cache root $ cat 11ca6725dc674b71725152bc42cddfbf
HTTP/2.0 200 OK
Content-Length: 288
Content-Type: application/json
Date: Fri, 08 Sep 2017 08:34:31 GMT

{
  "major": "1",
  "minor": "9+",
  "gitVersion": "v1.9.0-alpha.0.445+adb38b9d892043",
  "gitCommit": "adb38b9d8920431a63e2cf5a44831b3ee7268075",
...
```

**Comment by apelisse** [comment]
> loglevel 10 is requesting network trace, so it is expected you would see the content of discovery/schema docs

Maybe we should truncate if the content is too big ...

**Comment by apelisse** [comment]
> this new cache mechanism via current discovery request trigger implementation isn't fine grain enough.

True. Maybe we could have only cached the openapi requests/responses. I didn't find a good way to have a finer grain than the "discovery client".

On the other hand, HTTP cache is meant to be mostly transparent. We could also have decided to enable the cache for *every* requests in Kubernetes, and it shouldn't have made much difference (it would have saved secrets and potentially sensitive information to disk, which is why we didn't do it), since the server mostly decides if/how cache items can be reused.

> for kubectl get ...
> 
> shiywang:http-cache root $ more f56dd43c086a10001f66138611b7f541
> HTTP/2.0 200 OK
> Content-Length: 292
> Content-Type: application/json
> Date: Fri, 08 Sep 2017 07:51:11 GMT
> 
> {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"networking.k8s.io/v1","resources":[{"name":"networkpolicies","singularN
> ame":"","namespaced":true,"kind":"NetworkPolicy","verbs":["create","delete","deletecollection","get","list","patch","update","watch
> "],"shortNames":["netpol"]}]}
> for kubectl apiversions/version ..
> 
> shiywang:http-cache root $ cat 11ca6725dc674b71725152bc42cddfbf
> HTTP/2.0 200 OK
> Content-Length: 288
> Content-Type: application/json
> Date: Fri, 08 Sep 2017 08:34:31 GMT
> 
> {
>   "major": "1",
>   "minor": "9+",
>   "gitVersion": "v1.9.0-alpha.0.445+adb38b9d892043",
>   "gitCommit": "adb38b9d8920431a63e2cf5a44831b3ee7268075",
> ...

Note that in these two examples, the response has been saved on disk, but it's never going to be used as cache because it doesn't have an `ETag` header set. So it doesn't really matter. Does it?
