### ISSUE TITLE
Statefulset container hostname full FQDN

### ISSUE THREAD

**Issue by felixPG** [kubernetes/kubernetes#52084]
/kind feature

**What happened**:

I have a statefulset with headless service and both work fine. The service that I run is an activemq instance that use DNS names to make the brokers of networks using multicast discovery. 
The problem is that activemq **use the hostname** to expose the uri for the discovery and when the other broker search the "exposed brokers" see the broker as **hostname:port**. 
Activemq try to reach the hostname:port and FAILED, because to reach the pods running the other broker the uri should be **hostname.service_name**
If i modified the /etc/hosts in every activemq brokers to **IP hostname.service_name** then all work OK, so, how I can archive this??? if kubernetes assign by default only the pod name to the hostname and NOT the full FQDN.

**What you expected to happen**:
Kubernetes assign the FULL FQDN to containers hostname

**Comment by JustinasKO** [comment]
This is needed for RabbitMQ too, without this clustering is pain.

**Comment by felixPG** [comment]
@JustinasKO I resolve the problem using the pod ip instead of hostname, when you use the pod ip in case of activemq then activemq expose the whole FQDN, but the feature of take a full fqdn throught env should be available.

**Comment by felixPG** [comment]
remove-lifecycle stale
