### ISSUE TITLE
RFE: e2e label internet connectivity.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#52098]
**PROBLEM STATEMENT:** 
It's normal for folks to build clusters in an air-gap'd environment.  In these environments access to the wider internet is strictly forbidden.  We've known that there are several tests in the test suite require internet connectivity e.g. xref: https://github.com/kubernetes/kubernetes/pull/51287 , and this poses a problem for folks wanting to validate their cluster.  

**PROPOSED SOLUTION:**
1.  Create a predefined [Tag/Label] that can easily skip these tests for this type of environment 
2. Create a framework function that detects and auto-skips tests that are known to require internet connectivity 

/cc @kubernetes/sig-testing-feature-requests

**Comment by bgrant0607** [comment]
I agree that this shouldn't be a conformance test. It can, however, be a regular e2e test.

cc @kubernetes/sig-architecture-feature-requests

**Comment by timothysc** [comment]
Fixed by #53381 - closing
