### ISSUE TITLE
Allow for both dynamic and static node ports

### ISSUE THREAD

**Issue by wackerman** [kubernetes/kubernetes#52124]
/kind feature
/sig node

**What happened**:
When using deployment automation from multiple teams, some have node ports set and some use dynamic allocation.

**What you expected to happen**:
It would be nice to be able to set the range of ports kubernetes uses for dynamic allocation and the range allowed to be used for fixed node port in the yamls.

**How to reproduce it (as minimally and precisely as possible)**:
deploy a service using dynamic allocated node port
deploy a service where the yaml sets the node port to the port allocated in the above deployment

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kargakis** [comment]
@kubernetes/sig-network-feature-requests

**Comment by smarterclayton** [comment]
It would also simplify intra-cluster firewall configuration if there was a well known range.

**Comment by benkeil** [comment]
That would be a nice feature.
