### ISSUE TITLE
StorageClass.ReclaimPolicy, PV.MountOptions, and SC.MountOptions need e2e tests

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kubernetes#52138]
https://github.com/kubernetes/kubernetes/pull/47987 for 1.8.
/assign

**Comment by nikhiljindal** [comment]
Looking at the PR description, it seems that https://github.com/kubernetes/kubernetes/pull/52350 adds tests for ReclaimPolicy only. What about MountOptions?

**Comment by wongma7** [comment]
those are coming also, I'll re-rename issue/point to another one 👍

**Comment by nikhiljindal** [comment]
Since the feature is in 1.8, we need tests in 1.8.
Adding this to 1.8 milestone.

**Comment by saad-ali** [comment]
This issue is a 1.8 blocker. The PRs for to fix it, #52350 and #52500, are approved/LGTM'd and awaiting merge. This issue can be closed as soon as those merge.
