### ISSUE TITLE
pull-kubernetes-e2e-gce-etcd3 failing: Quota 'SUBNETWORKS' exceeded

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#52140]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52134/pull-kubernetes-e2e-gce-etcd3/53203/

```
I0908 02:11:06.591] Creating new network: e2e-53203
W0908 02:11:54.162] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0908 02:11:54.162]  - Quota 'SUBNETWORKS' exceeded.  Limit: 150.0
```

/cc @kubernetes/sig-testing-bugs

**Comment by xiangpengzhao** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/51646 https://github.com/kubernetes/kubernetes/issues/51136

**Comment by yujuhong** [comment]
The job is fine now so I assume that the janitor kicked in and reclaimed the resources (unless someone manually did that).
Might still be worth looking into whether the quota is sufficient and/or why the network leaked.

/cc @krzyzacy @MrHohn based on their past activity on similar bugs.

**Comment by krzyzacy** [comment]
I think to solve the root issue, manual subnetwork will be the solution, or else everytime gcp add a new region we'll have to bump the quota again :-(

/assign @MrHohn

**Comment by krzyzacy** [comment]
(maybe we should open a separate issue for this)

**Comment by yujuhong** [comment]
Yep. Let's close this one now that the tests are not failing.
