### ISSUE TITLE
How to specify each pod with distinct config in replication controller?

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#52143]
Current rc make all pods replicas homogeneous.
Can I specify each pod with distinct configuration?Or does k8s has support for this ?

Our sotuation is:
we create pod by using rc and we need each pod with different volume config.Each of them has its own lv partition(lvm volume)

**Comment by mjaow** [comment]
area/controller-manager
area/apiserver
 sig/storage
@saad-ali 
@childsb

**Comment by k82cn** [comment]
for now, k8s did not support that :(.

/area controller-manager
/area apiserver
/sig storage

**Comment by mjaow** [comment]
@k82cn Is there some better method to support volume isolation or disk isolation?Without limitation,some of pods will consume all disk resources

**Comment by msau42** [comment]
Use statefulsets to have each pod use a different volume.
