### ISSUE TITLE
Make current-context a shell variable

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#52142]
Hi,

It's just a feature proposition, 

It wouldn't be better to have the `current-context` in the current shell ? (like Environment variable)

And create for exemple a `default-context` in the `.kube/config` file. 

Because is very annoying when switching between multi-clusters to have all your shell in the same context. 

Thanks.

(Maybe the question is already discuss, sorry if it's the case).

**Comment by valentin2105** [comment]
@k8s-sig-onprem-feature-requests

**Comment by zjj2wry** [comment]
have a flag ```--context``` can checkout context
