### ISSUE TITLE
Field selectors should refer to external types

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#52159]
Currently they work on internal types and this is very confusing (to put it lightly) for anyone who wants to use it. Consider example of nontrivial (i.e. non-identity) mapping:
```
external type A {
  foo string
}

internal type B {
  bar string
}
```
Where `bar` is an internal representation for `foo`. Currently field selectors can refer only to `bar`, which is something that's normally completely invisible for clients.

@kubernetes/sig-api-machinery-bugs @deads2k @sttts @bgrant0607

**Comment by deads2k** [comment]
> Where bar is an internal representation for foo. Currently field selectors can refer only to bar, which is something that's normally completely invisible for clients.

I've recently been digging into this in openshift.  There is a field selector key conversion function which can translate field keys and field selector values from external to internal.  I think it works, but I'm not completely sure how readable user errors are.

**Comment by bgrant0607** [comment]
Related: #3084

**Comment by lavalamp** [comment]
I don't believe this is true. The selectors are applied on the internal types, but the definition--the line that invokes them--ought to match the external types or it would be unusable.

**Comment by gmarek** [comment]
When I was playing with Events this is exactly what I found. I'll ping you PR when you can see this (when I'll get back to playing with Events).

**Comment by liggitt** [comment]
field selectors are run through a per-version conversion function that has the opportunity to transform them from the specified name (which matches the external field of the version they are run against) to the internal key (which matches the key of the fieldset built for matching against). 

We happen to have not made use of field selector name changes across versions, but the capability is there if we need it.
