### ISSUE TITLE
Incomplete result of "kubectl get pods"

### ISSUE THREAD

**Issue by olekzabl** [kubernetes/kubernetes#52167]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

kubectl get pods --all-namespaces -o yaml did not print anything about one of the pods in the cluster  (pod name is "pending", in namespace "default").
Screenshots:
![dmjcwwyqssd](https://user-images.githubusercontent.com/17475944/30213201-4aceba1a-94a8-11e7-8a89-6c5715e109ff.png)
![nr76qphn45f](https://user-images.githubusercontent.com/17475944/30213059-b2e70c3e-94a7-11e7-8374-0738f64040d3.png)

Let me know if I can provide more info to help.

**Comment by olekzabl** [comment]
+ @janetkuo

**Comment by olekzabl** [comment]
Update: "--all-namespaces" doesn't matter, since the pod is in "default" namespace.
"kubectl get pods" is also missing it in the result.

**Comment by spzala** [comment]
@olekzabl hmm..what version of k8s are you on? If I understood it right, I could not recreate it on minikube running v1.7.5. 
```$ kubectl get pods
NAME                    READY     STATUS             RESTARTS   AGE
pending                 1/1       Running            0          5m
podtest                 1/1       Running            9          33d``` 
and
```
$ kubectl get pods --all-namespaces -o yaml | grep "/api/v1/namespaces/default/pods/pending"
    selfLink: /api/v1/namespaces/default/pods/pending
```
and
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY     STATUS             RESTARTS   AGE
default       pending                       1/1       Running            0          7m
default       podtest                       1/1       Running            9          33d
```
