### ISSUE TITLE
[audit] Figure out timestamps in event objects

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#52160]
Ref https://github.com/kubernetes/kubernetes/issues/48561

Currently, there's a [`Timestamp`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/types.go#L88) field in the `audit.Event` object, which represents `Time the request reached the apiserver.`. There're several problems with it:

1. Since auditing process has several stages, each one generating a separate event object in the sink, name can be confusing: a person can understand it as a timestamp of the last auditing process stage.
1. There's another field in the Event, inherited from the ObjectMeta: `CreationTimestamps`. It's also confusing what it means: either the same what `Timestamp` currently means or the stage timestmap.
1. CreationTimestamp has seconds precision.
1. Currently CreationTimestamp is not populated and left as nil in the serialized object.
1. Currently there's no stage timestamp in the object, so it's not possible to understand from the last audit object, how much time the request took: you have to correlate events by the `AuditId` (which can be spoofed).

We agreed that the @soltysh's PR (https://github.com/kubernetes/kubernetes/pull/52030) will addressed the latter two points by populating the `CreationTimestamp` field with the stage timestamp, exposing this information and making `CreationTimestamp` field useful. However, that doesn't solve the problem of ambiguous names or `CreationTimestamp` precision. There are three options:

1. Leave it as it is.
1. Rename `Timestamp` field e.g. to `RequestStartTimestamp`
1. Remove `Timestamp` field, introduce two new fields `RequestStartTimestamp` and `StageTimestamp` and remove `ObjectMeta`. This is the only option that will allow to use timestamps to make an accurate estimation of how much time the request took, since `CreationTimestamp` has only seconds precision.

Renaming/removing field ofc will happen in the backward-compatible way, by creating a new field that will hold the same value and then actually removing the field in the next API release.

Because of the precision problem, the last options seems like the best approach.

/cc @sttts @soltysh @ericchiang @CaoShuFeng

**Comment by soltysh** [comment]
> 3. Remove Timestamp field, introduce two new fields RequestStartTimestamp and StageTimestamp and remove ObjectMeta (which is possible now, but not tested)

I thought during our discussion we agreed on `CreationTimestap` being what you call here `RequestStartTimestamp` (unless we get rid of `ObjectMeta` if that's possible), introducing a new `StageTimestamp` (or other name tbd), finally deprecating `Timestamp` since its name provides no information what kind of time it is.

**Comment by sttts** [comment]
> I thought during our discussion we agreed on CreationTimestap being what you call here RequestStartTimestamp

The opposite. `CreationTimestamp` is the event object creation time by definition of that field. The `Event.Timestamp` is the request time (also by definition, i.e. by our godoc).

**Comment by sttts** [comment]
> event object creation time by definition of that field

That we re-use that event object throughout the handler chain is our optimization and an implementation detail. From the outside we create one event per stage.

**Comment by CaoShuFeng** [comment]
>2.  Rename Timestamp field e.g. to RequestStartTimestamp
I vote for this option.
But I suggest to rename RequestStartTimestamp to RequestReceivedTimestamp.
And in the RequestReceivedStage:
ObjectMeta.CreationTimestamp is equal RequestReceivedTimestamp

**Comment by crassirostris** [comment]
@soltysh Yeah, sorry for confusion earlier, I meant what @sttts said

@CaoShuFeng I also prefer this option better, b/c removing ObjectMeta will require some testing and even after that something can break, and leaving CreationTimestamp empty doesn't look good

**Comment by soltysh** [comment]
Important requirement for this is that it should give very good precision, micro- or milisecond precision so we can measure actual time spent for processing requests.

**Comment by crassirostris** [comment]
> Important requirement for this is that it should give very good precision, micro- or milisecond precision so we can measure actual time spent for processing requests.

+1, I'll add this to the issue description

**Comment by hzxuzhonghu** [comment]
> 3. Remove Timestamp field, introduce two new fields RequestStartTimestamp and StageTimestamp and remove ObjectMeta. This is the only option that will allow to use timestamps to make an accurate estimation of how much time the request took, since CreationTimestamp has only seconds precision.

In order to improve precision, I think no use of CreationTimestamp is a better choise. We can define `two new fields RequestStartTimestamp and StageTimestamp` with a more precise time metric type.
