### ISSUE TITLE
Update Kubenet with CNI v0.6.x for IPv6

### ISSUE THREAD

**Issue by rpothier** [kubernetes/kubernetes#52179]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Kubenet does not support the latest CNI version which is required for IPv6.
IPv6 addresses cannot be assigned.

**What you expected to happen**:
IPv6 addressing.

**How to reproduce it (as minimally and precisely as possible)**:
use an IPv6 address with Kubenet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by squeed** [comment]
I don't think this issue is necessary; kubenet uses whatever CNI binaries are on the host, and those have been updated to 0.6.
