### ISSUE TITLE
Init container not removed when cronjob is updated

### ISSUE THREAD

**Issue by julia-stripe** [kubernetes/kubernetes#52177]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug 

**What happened**:

I created a cronjob with an init container. This works correctly. I then updated that cronjob (with `kubectl apply`) to no longer have an init container. This doesn't work -- after updating the cronjob, the init container is still there. (also, there are no error messages)

Strangely, **updating** the init container works correctly, but **removing** the init container does not work.

(I'm planning to work on fixing this, but wanted to report an issue first in case anyone has any thoughts)

**What you expected to happen**:

I expected the init container to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

I created a gist with a script that reproduces this issue at https://gist.github.com/julia-stripe/8b9ad694c9f0208828493f012582c863. Here's how to run the script:

```
minikube start
git clone https://gist.github.com/8b9ad694c9f0208828493f012582c863.git cronjob-init-containers
cd cronjob-init-containers
bash run.sh
```

Here's the relevant output:

```
======= CREATE cronjob with init container
cronjob "minikube-test-job" created
list of init containers: (correct)
[
  {
    "command": [
      "/bin/sh",
      "-c",
      "ls"
    ],
    "image": "gcr.io/google_containers/debian-iptables-amd64:v5",
    "imagePullPolicy": "IfNotPresent",
    "name": "init-myservice",
    "resources": {},
    "terminationMessagePath": "/dev/termination-log",
    "terminationMessagePolicy": "File"
  }
]
======= APPLY cronjob with no init container
cronjob "minikube-test-job" configured
list of init containers: (incorrect, should be empty)
[
  {
    "command": [
      "/bin/sh",
      "-c",
      "ls"
    ],
    "image": "gcr.io/google_containers/debian-iptables-amd64:v5",
    "imagePullPolicy": "IfNotPresent",
    "name": "init-myservice",
    "resources": {},
    "terminationMessagePath": "/dev/termination-log",
    "terminationMessagePolicy": "File"
  }
]
```

**Anything else we need to know?**:

a few more notes:

* modifying the init containers on a cron job also doesn't work
* modifying the init containers on a cron job **does** work if you use the legacy `pod.beta.kubernetes.io/init-containers` annotations, but deleting them still doesn't

I noticed that modifying or deleting the init container on a Job also doesn't work (see [this output](https://gist.github.com/julia-stripe/8b9ad694c9f0208828493f012582c863#file-run_output-txt)) for what happens. 

I'd expect modifying/deleting the init containers on a Job object to give a validation error, but instead it just silently fails. Overall everything related to changing init containers on jobs / cronjobs seems to not work well.

**Environment**:

- Kubernetes version: 1.7.0

**Comment by liggitt** [comment]
Probably a dupe of https://github.com/kubernetes/kubernetes/issues/47264

Fixed by #51816

**Comment by liggitt** [comment]
Do you see the alpha/beta initcontainer annotations on the API object? If so, unless you also change the annotations, changes to the API field will be ignored (see discussion in https://github.com/kubernetes/kubernetes/issues/47264#issuecomment-327541429 for how we ended up with that behavior)

To remove initcontainers from the cronjob with apply, I think you would need to explicitly null out the initcontainer annotations in your applied object.

**Comment by julia-stripe** [comment]
thanks so much, that workaround works!
