### ISSUE TITLE
Enable AWS Network Load Balancer for Services of type LoadBalancer

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#52173]
/kind feature

I want to be able to create LoadBalancer services and use AWS's [Network Load Balancer](https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/)

Going along with how AWS LB's are currently configured, it would be most convenient to have an annotation to specify an NLB. 

**Environment**:

- Cloud provider: AWS

**Comment by micahhausler** [comment]
@kubernetes/sig-aws

**Comment by yastij** [comment]
@justinb - do we plan to support this ?

**Comment by wieslaw-gat** [comment]
This would be very useful, since the NLB docs state that:

> With Network Load Balancer, the original source IP address and source ports for the incoming connections remain unmodified, so application software need not support X-Forwarded-For, proxy protocol, or other workarounds

**Comment by micahhausler** [comment]
Yea I'm current working on this feature, should have a PR soon. It'll be against the 1.9 release branch/master

**Comment by pmoosh** [comment]
@micahhausler - how are things coming along?

**Comment by bchav** [comment]
@micahhausler Brandon with AWS here. Anything we can do to help?

**Comment by micahhausler** [comment]
Hi @bchav, hoping to push up a branch today or tomorrow. I'd love high-level feedback (its not compiling yet, but more just around organization) I'll ping you when I've pushed it up

**Comment by jwickens** [comment]
see also kubernetes-incubator/kube-aws#945

**Comment by bayucandra** [comment]
@micahhausler , is NLB on Kubernetes support annotation `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"`? Because, when I have it then checking at my NLB attributes, I can't see proxy protocol enabled. Looks like I have to enable it manually. That annotation works well with ELB tough.

**Comment by micahhausler** [comment]
@bayucandra That isn't yet supported. See #57250
