### ISSUE TITLE
Kubelet is not creating the log symlink 

### ISSUE THREAD

**Issue by pegerto** [kubernetes/kubernetes#52172]
/kind bug

**What happened**:
Kubelet is not creating the log symlink for some containers at '/var/log/containers'

**What you expected to happen**:

The symlink is a requirement for fluentd, we expect to have a symlink for any running container inside a pod.

**How to reproduce it (as minimally and precisely as possible)**:

We run test with the following script and found many cases, but we could not reproduced in a dev environment.
```
#!/bin/bash 
docker ps -q | while read line;
do
  if [ `find /var/log/containers -name *$line* | wc -l` = "0" ]
  then
    name=`docker inspect --format {{.Name}} $line | head -c 8 `
    if [ $name != "/k8s_POD" ] 
    then
      docker inspect --format {{.Name}} $line 
    fi 
  fi  
done
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux master0 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
Containers: 26
 Running: 18
 Paused: 0
 Stopped: 8
Images: 20
Server Version: 1.12.6
Storage Driver: aufs
```

**Comment by yujuhong** [comment]
Kubelet creates a infra container for every pod with name prefix: `k8s_POD_`. These are not user containers and will not have log symlinks. Please check the names of those containers with missing symlinks to make sure they are not infra containers.

**Comment by pegerto** [comment]
Helo @yujuhong 

As far I can see in `1.5.7` where I have the issue with the missing symlinks, infra pod have a link. For instance

```
ls -la | grep c93a829c7dc0
lrwxrwxrwx  1 root root     165 Sep  5 08:01 kube-npd-1wjq2_kube-system_POD-c93a829c7dc0666ae8570e0a60b1247fa9fc749a21c78b6edd424d73301e382b.log -> /var/lib/docker/containers/c93a829c7dc0666ae8570e0a60b1247fa9fc749a21c78b6edd424d73301e382b/c93a829c7dc0666ae8570e0a60b1247fa9fc749a21c78b6edd424d73301e382b-json.log
```

But I can see missing links for other pods, especially for pods that are restarted, I can see that the symlink for the previous container is maintained.

Example
```
docker ps -q | while read line;
> do
>   if [ `find /var/log/containers -name *$line* | wc -l` = "0" ]
>   then
>     name=`docker inspect --format {{.Name}} $line`
>     echo $name | head -c 10
>     echo ""
>   fi
> done
/k8s_kube-
/k8s_sf-pl
```

**Comment by pegerto** [comment]
I have observe that the issue is not in the creation, but we have, from time deletion of the symlinks.

For example, when auditing the directory we see a deletion of a log file:

```
time="2017-09-12T02:00:00Z" level=info msg="event: "/var/log/containers/xx-xxxx-2017-09-08-15-03-55-52qbv_default_xx-xxxx-d453dc273906fe51cea3a5052a47aa5d33da4bcd09534d09345d692af321ba1d.log": REMOVE"
```

When the container in the pod is running without issues:
```
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 21877,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2017-09-08T15:04:45.112289746Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
```

Is possible that there is a race condition between the log rotation and the kubelet GC implementing a clean up on the symlinks:

https://github.com/kubernetes/kubernetes/blob/03971d3992b38e0a1ec2aef99d10752df479260f/pkg/kubelet/dockertools/container_gc.go#L235-L235

**Comment by pegerto** [comment]
This functionality is deprecated in the new versions
https://github.com/kubernetes/kubernetes/blob/9ac30e2c280f61a9629f3334f7e6e6424b7fb5f8/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L337-L348

**Comment by joelittlejohn** [comment]
Since #52417 is not yet merged, a full fix for this is some way off.

Does anyone have a workaround for this issue? We're seeing it in out k8s 1.5 cluster. If we disable log rotation, we'll occasionally fill a node with logs. If we enable log rotation, fluentd stops writing logs after a few hours due to this bug. We can reduce the likelihood of this happening by rotating less frequently, but is there a better workaround that can solve the problem?

**Comment by pegerto** [comment]
Hello joel, 

I understand that the effort to upgrade is not simple, so if the change is merge you will need to port of upgrade. I build workaround for a client some time ago.


Ideally you can run a daemonset that evaluate the sysmlinks and recreated when this symlink is deleted by the kubelet.

You will need access to the docker interface: 

This pice of code is all you need.
```
        const ext4MaxFileNameLen = 255
	podFullName := podName + "_" + podNamespace

	suffix := fmt.Sprintf(".%s", "log")
	logPath := fmt.Sprintf("%s_%s-%s", podFullName, containerName, dockerId)
	// Length of a filename cannot exceed 255 characters in ext4 on Linux.
	if len(logPath) > ext4MaxFileNameLen-len(suffix) {
		logPath = logPath[:ext4MaxFileNameLen-len(suffix)]
	}
	logSymLink := path.Join(containerLogsDir, logPath+suffix)

	_, err := os.Stat(logSymLink)
	if err != nil {	
		info, err := cli.InspectContainer(dockerId)
               err := os.Symlink(info.LogPath, logSymLink)
        }
}
```
Regards.

**Comment by joelittlejohn** [comment]
Thanks @pegerto. I think I'll implement this in bash and run as a service on the nodes (it's perfect for bash, and access to the symlinks and docker is easy that way).

**Comment by pegerto** [comment]
Hey @joelittlejohn 

Bash will do the work, we ran this in a container with the logstash demonset.


Regards

**Comment by joelittlejohn** [comment]
It's not fancy, but here's what I came up with.

I add the following units to the CoreOS cloud-config for my nodes:

```yaml
    - name: ensure-log-symlinks.service
      command: start
      content: |
        [Unit]
        Description=Ensure kubernetes has not deleted log symlinks
        [Service]
        Type=oneshot
        ExecStart=/bin/bash /etc/kubernetes/ensure-log-symlinks.sh
    - name: ensure-log-symlinks.timer
      command: start
      content: |
        [Unit]
        Description=Ensure kubernetes has not deleted log symlinks
        [Timer]
        OnUnitActiveSec=1min
        OnBootSec=10min
        [Install]
        WantedBy=timers.target
``` 

then add this script to the write-files section of the cloud-config (**note:** requires `jq`):

```yaml
  - path: /etc/kubernetes/ensure-log-symlinks.sh
    owner: root
    permissions: 0744
    content: |
      #!/usr/bin/bash
      #
      # See https://github.com/kubernetes/kubernetes/issues/52172#issuecomment-328819603
      #
      set -eu
      if [ -d /var/lib/docker/containers ]; then
        pushd /var/lib/docker/containers
        for POD_ID in *; do
          CONTAINER="$(cat $POD_ID/config.v2.json | jq '{Labels:.Config.Labels, LogPath, ID}')"
          CONTAINER_ID="$(echo $CONTAINER | jq -r .ID)"
          CONTAINER_NAME="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.container.name"]')"
          LOG_PATH="$(echo $CONTAINER | jq -r .LogPath)"
          POD_NAME="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.pod.name"]')"
          POD_NAMESPACE="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.pod.namespace"]')"
          SYMLINK_NAME="$(printf "%s_%s_%s-%s" "$POD_NAME" "$POD_NAMESPACE" "$CONTAINER_NAME" "$CONTAINER_ID" | cut -c 1-251)"
          SYMLINK_FILENAME=$(printf "/var/log/containers/%s.log" "$SYMLINK_NAME")

          if [ ! -f $SYMLINK_FILENAME ]; then
            echo "Missing log symlink $SYMLINK_FILENAME for $LOG_PATH, creating it now" | systemd-cat -t ensure-log-symlinks.sh
            ln -s $LOG_PATH $SYMLINK_FILENAME
          fi
        done
        popd
      fi
```

Of course for anyone that doesn't want to create a CoreOS (or similar) cloud-config in this way, you can just take the ensure-log-symlinks.sh script content and use that.

**Comment by cjyar** [comment]
@joelittlejohn Here's my solution which is based on yours. This uses a DaemonSet. It replaces symlinks in both /var/log/containers and /var/log/pods, since I was having trouble with that.

`log-linker.sh`:
```bash
#!/usr/bin/env bash

#
# Derived from https://github.com/kubernetes/kubernetes/issues/52172#issuecomment-346075080
#
set -eu
if [ ! -d /var/lib/docker/containers ]; then
    echo "/var/lib/docker/containers doesn't exist; aborting" 1>&2
    exit 1
fi

cd /var/lib/docker/containers

while true ; do
    for DOCKER_ID in *; do
        CONTAINER="$(cat ${DOCKER_ID}/config.v2.json | jq '{Labels:.Config.Labels, LogPath, ID}')"
        CONTAINER_ID="$(echo ${CONTAINER} | jq -r .ID)"
        CONTAINER_NAME="$(echo ${CONTAINER} | jq -r '.Labels["io.kubernetes.container.name"]')"
        LOG_PATH="$(echo ${CONTAINER} | jq -r .LogPath)"
        POD_NAME="$(echo ${CONTAINER} | jq -r '.Labels["io.kubernetes.pod.name"]')"
        POD_NAMESPACE="$(echo ${CONTAINER} | jq -r '.Labels["io.kubernetes.pod.namespace"]')"
        LINK1_NAME="$(printf "%s_%s_%s-%s" "$POD_NAME" "$POD_NAMESPACE" "$CONTAINER_NAME" "$CONTAINER_ID" | cut -c 1-251)"
        LINK1_FILENAME=$(printf "/var/log/containers/%s.log" "$LINK1_NAME")
        LINK2_FILENAME=$(echo ${CONTAINER} | jq -r '.Labels["io.kubernetes.container.logpath"]')

        if [ -n "${LINK1_FILENAME}" -a ! -e "${LINK1_FILENAME}" -a -e "${LOG_PATH}" ] ; then
            echo "Missing log symlink ${LINK1_FILENAME} for ${LOG_PATH}, creating it now"
            ln -s ${LOG_PATH} ${LINK1_FILENAME}
        fi

        if [ "${LINK2_FILENAME}" = "null" ] ; then
            LINK2_FILENAME=""
        fi
        if [ -n "${LINK2_FILENAME}" -a ! -e "${LINK2_FILENAME}" -a -e "${LINK1_FILENAME}" ] ; then
            echo "Missing log symlink ${LINK2_FILENAME} for ${LINK1_FILENAME}, creating it now"
            if [ ! -d "$(dirname ${LINK2_FILENAME})" ] ; then
                mkdir -p "$(dirname ${LINK2_FILENAME})"
            fi
            ln -s ${LINK1_FILENAME} ${LINK2_FILENAME}
        fi
    done

    sleep 60
done
```

`Dockerfile`:
```Dockerfile
FROM debian

RUN apt-get update && \
    apt-get install -y \
        jq

ADD log-linker.sh /
```

`deploy.yaml`:
```yaml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: log-linker
  namespace: kube-system
  labels:
    app: log-linker
spec:
  selector:
    matchLabels:
      app: log-linker
  template:
    metadata:
      labels:
        app: log-linker
    spec:
      containers:
      - name: log-linker
        image: your/image/path/here:latest
        command:
        - /log-linker.sh
        volumeMounts:
        - name: var-lib-docker
          mountPath: /var/lib/docker
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker
```

**Comment by patrickf55places** [comment]
@joelittlejohn @cjyar Could you guys to attach a license to that code (e.g. MIT) so that others can (safely) use it?

**Comment by patrickf55places** [comment]
For those watching this issue, joelittlejohn and cjyar updated their comments to license the code under MIT (you don't get notifications for edits). Thanks guys!

**Comment by mindw** [comment]
/remove-lifecycle rotten

We're seeing this in k8s 1.8.12

**Comment by AlexPereverzyev** [comment]
I've got similar issue after switching Docker's json file logging driver to non-blocking mode in /etc/docker/daemon.json - lots of 'Cannot create symbolic link because container log file doesn't exist!' warnings from kubelet and empty /var/log/containers directory.
Default, blocking mode works just fine. 
Could be timing issue, related to Docker log buffer size.

**Comment by hce137** [comment]
Just add more evidence, we got exactly the same issue as @AlexPereverzyev did.
kubelet 1.8.13, docker 17.12.1-ce

**Comment by dbluxo** [comment]
+1

**Comment by gtie** [comment]
This is still very much a problem (on 1.12.7 at least)

**Comment by zillaer** [comment]
1.13.7 reproduced

**Comment by mindw** [comment]
still a problem - since 1.10.x or so.
CoreOS.

**Comment by eyenx** [comment]
/reopen

Still a problem with 1.16 and cri-o

**Comment by sekerjak** [comment]
still reproducible

**Comment by tedyu** [comment]
Can admin reopen this issue (since users still encounter the problem) ?

**Comment by tedyu** [comment]
I think containerGC#evictPodLogsDirectories can maintain a cache which tracks the earliest time for the symlink for which Stat(logSymlink) returned NotExist.
Give each candidate symlink some grace period before deleting it.

This can avoid race with the docker log rotation.

**Comment by tedyu** [comment]
@pegerto 
Do you mind modifying the subject of this issue (since it was due to race condition between the log rotation and the kubelet GC) ?

thanks

**Comment by tedyu** [comment]
@yujuhong @derekwaynecarr @Random-Liu 
Can you take a look at my suggestion above ?

Meanwhile, I will see if there is better solution.

**Comment by zoftdev** [comment]
> Can admin reopen this issue (since users still encounter the problem) ?

Yes we found

**Comment by sftim** [comment]
I wonder if log rotation could use an atomic swap to avoid the race condition. I mentioned this in https://github.com/kubernetes/kubernetes/pull/89160/files#r412408067

**Comment by ashokbanerjee** [comment]
Is this being worked on? I think we are hitting this issue.

**Comment by irmiller22** [comment]
can also confirm that we're running into this issue with `1.18`.

**Comment by gyohuangxin** [comment]
I also met this issue in Kubernetes v1.20.0 and the kubelet log was confusing:
```
  Warning  FailedCreatePodSandBox  4h32m                   kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to mount container k8s_POD_etcd-master-2.zaas.pok.ibm.com_openshift-etcd_58fd7b76-6c16-4336-96dc-59e5f1bf77d3_0 in pod sandbox k8s_etcd-master-2.zaas.pok.ibm.com_openshift-etcd_58fd7b76-6c16-4336-96dc-59e5f1bf77d3_0(f9b01bbc1cc125f44fd77ac6491a5a7bba97d15915c03a4031ad783697de0a95): error recreating the missing symlinks: error reading name of symlink for &{"3b9c954748b3eba8f1f1a243a60a0464f6f8a88de888a6f2800aed03b2ee1dd5" '\x14' %!q(os.FileMode=2147484141) {%!q(uint64=844154993) %!q(int64=63757365315) %!q(*time.Location=&{Local [{UTC 0 false}] [{-576460752303423488 0 false false}] UTC0 9223372036854775807 9223372036854775807 0xc00047e680})} {'市' %!q(uint64=7597057) '\x03' '䇭' '\x00' '\x00' '\x00' '\x00' '\x14' {%!q(int64=1621768515) %!q(int64=814154993)} {%!q(int64=1621768515) %!q(int64=844154993)} {%!q(int64=1621768515) %!q(int64=844154993)} 'က' '\x00' ['\x00' '\x00' '\x00']}}: open /var/lib/containers/storage/overlay/3b9c954748b3eba8f1f1a243a60a0464f6f8a88de888a6f2800aed03b2ee1dd5/link: no such file or directory
```

**Comment by ehashman** [comment]
/triage accepted
/remove-priority awaiting-more-evidence

I think there's probably enough detail here to reproduce and attempt to fix this.

/help

**Comment by nitinkansal1984** [comment]
I am facing the same issue on docker desktop

**Comment by nitinkansal1984** [comment]
failed to try resolving symlinks in path "/var/log/pods/

**Comment by nitinkansal1984** [comment]
> It's not fancy, but here's what I came up with.
> 
> I add the following units to the CoreOS cloud-config for my nodes:
> 
> ```yaml
>     - name: ensure-log-symlinks.service
>       command: start
>       content: |
>         [Unit]
>         Description=Ensure kubernetes has not deleted log symlinks
>         [Service]
>         Type=oneshot
>         ExecStart=/bin/bash /etc/kubernetes/ensure-log-symlinks.sh
>     - name: ensure-log-symlinks.timer
>       command: start
>       content: |
>         [Unit]
>         Description=Ensure kubernetes has not deleted log symlinks
>         [Timer]
>         OnUnitActiveSec=1min
>         OnBootSec=10min
>         [Install]
>         WantedBy=timers.target
> ```
> 
> then add this script to the write-files section of the cloud-config (**note:** requires `jq`):
> 
> ```yaml
>   - path: /etc/kubernetes/ensure-log-symlinks.sh
>     owner: root
>     permissions: 0744
>     content: |
>       #!/usr/bin/bash
>       #
>       # See https://github.com/kubernetes/kubernetes/issues/52172#issuecomment-328819603
>       #
>       set -eu
>       if [ -d /var/lib/docker/containers ]; then
>         pushd /var/lib/docker/containers
>         for POD_ID in *; do
>           CONTAINER="$(cat $POD_ID/config.v2.json | jq '{Labels:.Config.Labels, LogPath, ID}')"
>           CONTAINER_ID="$(echo $CONTAINER | jq -r .ID)"
>           CONTAINER_NAME="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.container.name"]')"
>           LOG_PATH="$(echo $CONTAINER | jq -r .LogPath)"
>           POD_NAME="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.pod.name"]')"
>           POD_NAMESPACE="$(echo $CONTAINER | jq -r '.Labels["io.kubernetes.pod.namespace"]')"
>           SYMLINK_NAME="$(printf "%s_%s_%s-%s" "$POD_NAME" "$POD_NAMESPACE" "$CONTAINER_NAME" "$CONTAINER_ID" | cut -c 1-251)"
>           SYMLINK_FILENAME=$(printf "/var/log/containers/%s.log" "$SYMLINK_NAME")
> 
>           if [ ! -f $SYMLINK_FILENAME ]; then
>             echo "Missing log symlink $SYMLINK_FILENAME for $LOG_PATH, creating it now" | systemd-cat -t ensure-log-symlinks.sh
>             ln -s $LOG_PATH $SYMLINK_FILENAME
>           fi
>         done
>         popd
>       fi
> ```
> 
> Of course for anyone that doesn't want to create a CoreOS (or similar) cloud-config in this way, you can just take the ensure-log-symlinks.sh script content and use that.
> 
> Note: All code in this comment is licensed by me, the author, under the [MIT License](https://opensource.org/licenses/MIT).

Its not working for me.

log-linker-2pp8v                         0/1     Error         0          7s
PS C:\Users\kansa\OneDrive\Desktop\kubebatch2\gremlin> kubectl.exe logs log-linker-2pp8v -n kube-system                                /usr/bin/env: 'bash\r': No such file or directory
PS C:\Users\kansa\OneDrive\Desktop\kubebatch2\gremlin>

**Comment by nitinkansal1984** [comment]
I changed the base image from debian to ubuntu also. it didn;t work

**Comment by nitinkansal1984** [comment]
Never mind ! I used dos2unix and coverted the file format and then used it worked

**Comment by Yelijah** [comment]
I occuer the same problem. After many tries , I found the cause is that I changed docker log driver from json to others. When i change it back, it fixed. 
I hope that can help u.
