### ISSUE TITLE
Add e2e test to exercise device plugin failure handling upon kubelet restarts, device plugin restarts, and device failure

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#52189]
/kind feature

We would like to make sure the device plugin framework we added in 1.8 has proper handling upon the following failure scenario:

- Kubelet restarts: An e2e test we may add is to allocate a gpu device to a pod and then restart kubelet. After kubelet becomes ready again, verify that device plugin has correctly re-registered with the new kubelet instance. Then checks that we can allocate another gpu device to another pod. The gpu device allocated to the second pod needs to be different from the first one, which verifies that kubelet device plugin checkpoint works correctly. For this e2e test, we may use some functions in test/e2e/framework/util.go, e.g., RestartKubelet().

- Device plugin restarts: For this test, we can just use the nvidia gpu device plugin currently implemented. In the test, we can also start with allocating a gpu device to a pod first and then delete the device plugin DaemonSet. The current expected behavior is that the pod that is already allocated with a gpu can still keep running but new pod creation with gpu request should be pending. The node should report no capacity for gpu resource after the device plugin DaemonSet is deleted. Then create the DaemonSet again. Verifies the capacity for gpu resource on the node is correctly updated after the new device plugin reconnects and the new pod can be allocated with gpu devices. We may reuse some functions in test/e2e/framework/util.go, e.g.,  deleteResource(), in this test. 

- Device failure: There is already certain unit test coverage in pkg/kubelet/deviceplugin/endpoint_test.go and pkg/kubelet/cm/device_plugin_handler_test.go that for device state update handling. In this e2e test, we want to emulate device failure at lower level (i.e., below device plugin), and verifies that the device plugin can correctly detect and report that, and kubelet can update resource capacity accordingly. Note that this does depend on the healthy state monitoring functionality implemented in a device plugin, which is not implemented yet in the nvidia gpu device plugin.

FYI, the e2e test we already added to test basic device plugin functionality: test/e2e/scheduling/nvidia-gpus.go. May consider to generalize some logic in this file, e.g., creating a DaemonSet and creating a pod to use gpu resource, into functions that we may reuse in the failure tests.

**Comment by RenaudWasTaken** [comment]
Does it have to be GPUs ? Or rather should we have both ?

**Comment by jiayingz** [comment]
I think testing with a real device plugin implementation is necessary and currently gpu device plugin is the only one implemented. Tests with emulated device plugins would be extra bonus.

**Comment by jiayingz** [comment]
/remove-lifecycle stale

The first two parts are already tested by the added test/e2e/scheduling/nvidia-gpus.go, test/e2e_node/gpu_device_plugin.go, and the stub device plugin based test/e2e_node/device_plugin.go that @ScorpioCPH is working on. Once the stub device plugin based test/e2e_node/device_plugin.go is in, I am hoping we can extend it to test the device failure part.
