### ISSUE TITLE
[e2e tests] gke-serial and gci-gke-serial startup failures

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52181]
/kind e2e-test-failure
@kubernetes/test-infra-maintainers 
@kubernetes/kubernetes-release-managers 

The GKE serial and GCI CKE serial e2e tests are experiencing startup failures:

https://k8s-testgrid.appspot.com/release-master-blocking#gke-serial
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke-serial

Sorry if this is already being tracked.

**Comment by krzyzacy** [comment]
it timed out basically, I can bump the timeout, but is it normal?

**Comment by ericchiang** [comment]
> it timed out basically, I can bump the timeout, but is it normal?

bumping the timeout might be a reasonable place to start at least.

**Comment by krzyzacy** [comment]
The serial suites looks fine now.
/close
