### ISSUE TITLE
Better handling on duplicate registrations from a device plugin in Kubelet

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#52190]
/kind feature

In the current Kubelet device plugin implementation, we always accept the newest device plugin upon duplicate registrations. We took this policy so that if device plugin DaemonSet restarts, new connection can be re-established. However, this policy may not yield the desired behavior in certain cases, e.g., when the old device plugin is still correctly running and the new device plugin was deployed by mistake. We may consider to extend the current logic to verify whether an old device plugin with the same resource name is still alive before accepting the new registration. We may also consider to add the logic that de-prioritizes the registration for a given resource if it has been registered multiple times in a short period to make sure Kubelet would not be kept busy by a faulty device plugin.

**Comment by lichuqiang** [comment]
Yes, the protection of plugin registration is necessary.
So, How should we define "still alive"?  It seems currently, manager would automaticly remove an endpoint if its listAndWatch exit.

**Comment by tengqm** [comment]
test: PR #52616

**Comment by jiayingz** [comment]
@vikaschoudhary16 perhaps we can re-use this FR to track rate limiting on probe based plugin registration?
