### ISSUE TITLE
UX issue with updating objects with empty pending initializers list

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#52202]
**(SEE UPDATE at https://github.com/kubernetes/kubernetes/issues/52202#issuecomment-329888449)**

Currently, if you're writing an initializer controller, you're most likely using it to initialize a `Pod` and deploying the controller with `Deployment`. Therefore you're likely using the following trick to avoid the chicken and egg problem:

```yaml
metadata:
  initializers:
    pending: []
```

This bypasses the initializers for the pods and lets your controller to be deployed even though your InitializerConfiguration is configured to capture all pods.

Problem occurs when you **apply an update** to this Deployment with the same manifest containing empty pending list. You get error:

```
The Deployment "my-initializer" is invalid: metadata.initializers:
Invalid value: "null": field is immutable once initialization has completed
```

I think this is a somewhat major UX issue. It requires users to deploy the initializer controller with the `metadata.initializers.pending=[]` but later on when they need to update the controller with `kubectl apply`, they can't use the same manifest containing the empty list.

/area api
/area extensibility
/sig api-machinery
/kind bug
/assign @caesarxuchao

**Comment by smarterclayton** [comment]
We silently ignore some metadata updates, which is one option.  Potentially we shouldn't require empty initializers pending, but simply empty initializers (which means - init directly), and only ignore that.  Are there any examples of use of SMP for similar?

I'm not sure this meets the bar for 1.8 but if we can find an example of something consistent already in the API I'd be willing to review.

**Comment by ahmetb** [comment]
I don't have any concrete examples, there's an example initializer at [kelseyhightower/kubernetes-initializer-tutorial](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/2645c93e05f281c251ae7d835c7bb93dfdded0b8/deployments/envoy-initializer.yaml#L5) making use the `pending: []` trick, I use it myself, and I suspect many more initializers to come will use this, too. 

I'm not sure if this would work, but does setting `metadata.initializers.result.status = "Success"` provide a way to skip initialization? If not, we might actually need a separate field to signal skipping initialization.

**Comment by caesarxuchao** [comment]
Currently the initializer plugin [rewrites](https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.0/plugin/pkg/admission/initialization/initialization.go#L225-L227) `metadata.initializers.pending=[]` to `initializers=nil` on update, but that happens after it [rejects](https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.0/plugin/pkg/admission/initialization/initialization.go#L213-L214) updating already initialized objects. We can simply change their order.

**Comment by ahmetb** [comment]
I'd like to amend the issue, it's more serious than I thought. (thanks for bringing it to my attention @caesarxuchao):

------

If you're deploying your Initializer with `Deployment` and if you have an initializerconfiguration for `Pod` objects,  **it's impossible to deploy your initializer in the first place without deleting InitializerConfiguration first**:

1. `Deployment.metadata.initializers.pending=[]` is not inherited by the created `Pod`
2. Specifying `initializers.pending=[]` on `Deployment.spec.template` is not honored (this field is not propagated to the created Pod).

I think **(2)** should be fixed somehow, otherwise there will be no way of writing an initializer for Pods and deploying the initializer itself using Deployment/ReplicaSet/RC without deleting the InitializerConfiguration first.

Maybe what we need is an exclusion/exemption selector (or namespace(s)) as discussed in #51290 to allow deployment of Initializers themselves easier.

**Comment by caesarxuchao** [comment]
For 1, see https://github.com/kubernetes/kubernetes/issues/51299. I don't want to pursue that though, because *i)* we'll need to fix workload controllers one by one, and *ii)* we need to carefully consider permission issues.

I think we should focus on adding the namespace selector.
