### ISSUE TITLE
'kubectl attach' does not return output from the pod container

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes/kubernetes#52224]
/kind bug
**What happened**:
`kubectl attach <pod-name>` was not showing the output "Started, serving at 8080"
But  `kubectl logs <pod-name>` shows "Started, serving at 8080"

**What you expected to happen**:
`kubectl attach <pod-name>`  to show the output "Started, serving at 8080"

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json
2. Wait until pod running
3. kubectl attach doublecontainers

**Anything else we need to know?**:
It works on 1.6 release

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.502+736846baf91170-dirty", GitCommit:"736846baf9117051b6a75cc0dbb5807a628bb9e6", GitTreeState:"dirty", BuildDate:"2017-09-09T01:28:27Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.502+736846baf91170-dirty", GitCommit:"736846baf9117051b6a75cc0dbb5807a628bb9e6", GitTreeState:"dirty", BuildDate:"2017-09-09T01:28:27Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"

- Kernel (e.g. `uname -a`):
3.10.0-514.21.1.el7.x86_64

**Comment by dixudx** [comment]
@vikaschoudhary16 I don't think this is a bug, or *at least not a `Kubernetes` bug*. You will find the same behavior with `docker attach xxx`. 

If you want to get the logs, please use `kubectl logs -f doublecontainers -c hello-openshift` and `kubectl logs -f doublecontainers -c hello-openshift-fedora`, where you will find the expected log message.

**Comment by sjenning** [comment]
@ncdc you've been following this for longer.  Is this a valid issue? Is https://github.com/kubernetes/kubernetes/pull/52225 as valid fix?

**Comment by ncdc** [comment]
We need to resolve the discussion in https://github.com/kubernetes/kubernetes/issues/24070 first.
