### ISSUE TITLE
kube-proxy downgrade job applies 1.8 `ADMISSION_CONTROL` env on 1.7 master causes apiserver crashes looping

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#52226]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
From kube-proxy downgrade test suite: https://k8s-testgrid.appspot.com/sig-network#gci-gce-latest-downgrade-kube-proxy-ds&width=20.

After downgrade, test always fails on "Waiting for new master to respond to API requests".

Checked apiserver's log, found below error ([sample log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-latest-downgrade-kube-proxy-ds/107/artifacts/bootstrap-e2e-master/kube-apiserver.log)):
```
failed to initialize admission: Unknown admission plugin: Priority
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Downgrade master from 1.8+ to 1.7.X.

@kubernetes/sig-api-machinery-bugs 
(Hoping I'm pinging the right group.)

**Comment by liggitt** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by liggitt** [comment]
Is the priority admission plugin enabled by default or just in test configurations?

**Comment by liggitt** [comment]
cc @bsalamat

**Comment by bsalamat** [comment]
@liggit priority admission plugin is enabled by default:
https://github.com/kubernetes/kubernetes/pull/49322/files

Doesn't downgrading remove it from the list?

**Comment by bsalamat** [comment]
@MrHohn Are we passing the same set of flags that we used to pass to 1.8, to 1.7 after downgrading? This seems incorrect to me.

**Comment by MrHohn** [comment]
@bsalamat I'm not sure how flags are being handled during downgrade, this CI job uses the build-in e2e upgrade/downgrade framework. I logged on current running instance (https://prow.k8s.io/log?job=ci-kubernetes-e2e-gci-gce-latest-downgrade-kube-proxy-ds&id=156) and will post what I observe here soon.

**Comment by MrHohn** [comment]
Humm, seems like the flags changed a bit, but `Priority` was still passed in via `--admission-control` after downgrading master to 1.7.

On 1.8 master (note that `--advertise-address` is new):
```
/usr/local/bin/kube-apiserver
--v=2
--runtime-config=extensions/v1beta1
--delete-collection-workers=1
--cloud-config=/etc/gce.conf
--address=127.0.0.1
--allow-privileged=true
--cloud-provider=gce
--client-ca-file=/etc/srv/kubernetes/pki/ca-certificates.crt
--etcd-servers=http://127.0.0.1:2379
--etcd-servers-overrides=/events#http://127.0.0.1:4002
--secure-port=443
--tls-cert-file=/etc/srv/kubernetes/pki/apiserver.crt
--tls-private-key-file=/etc/srv/kubernetes/pki/apiserver.key
--requestheader-client-ca-file=/etc/srv/kubernetes/pki/aggr_ca.crt
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=/etc/srv/kubernetes/pki/proxy_client.crt
--proxy-client-key-file=/etc/srv/kubernetes/pki/proxy_client.key
--enable-aggregator-routing=true
--kubelet-client-certificate=/etc/srv/kubernetes/pki/apiserver-client.crt
--kubelet-client-key=/etc/srv/kubernetes/pki/apiserver-client.key
--service-account-key-file=/etc/srv/kubernetes/pki/serviceaccount.crt
--token-auth-file=/etc/srv/kubernetes/known_tokens.csv
--basic-auth-file=/etc/srv/kubernetes/basic_auth.csv
--storage-backend=etcd3
--storage-media-type=application/vnd.kubernetes.protobuf
--target-ram-mb=180
--service-cluster-ip-range=10.0.0.0/16
--etcd-quorum-read=false
--audit-policy-file=/etc/audit_policy.config
--audit-log-path=/var/log/kube-apiserver-audit.log
--audit-log-maxage=0
--audit-log-maxbackup=0
--audit-log-maxsize=2000000000
--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,PodPreset,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,Priority,ResourceQuota
--min-request-timeout=300
--runtime-config=batch/v2alpha1=true
--feature-gates=ExperimentalCriticalPodAnnotation=true,AdvancedAuditing=true
--advertise-address=35.193.82.245
--authorization-mode=Node,RBAC
--allow-privileged=true
```

On 1.7 master:
```
/usr/local/bin/kube-apiserver
--v=2
--runtime-config=extensions/v1beta1
--delete-collection-workers=1
--cloud-config=/etc/gce.conf
--address=127.0.0.1
--allow-privileged=true
--cloud-provider=gce
--client-ca-file=/etc/srv/kubernetes/pki/ca-certificates.crt
--etcd-servers=http://127.0.0.1:2379
--etcd-servers-overrides=/events#http://127.0.0.1:4002
--secure-port=443
--tls-cert-file=/etc/srv/kubernetes/pki/apiserver.crt
--tls-private-key-file=/etc/srv/kubernetes/pki/apiserver.key
--requestheader-client-ca-file=/etc/srv/kubernetes/pki/aggr_ca.crt
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=/etc/srv/kubernetes/pki/proxy_client.crt
--proxy-client-key-file=/etc/srv/kubernetes/pki/proxy_client.key
--enable-aggregator-routing=true
--kubelet-client-certificate=/etc/srv/kubernetes/pki/apiserver-client.crt
--kubelet-client-key=/etc/srv/kubernetes/pki/apiserver-client.key
--service-account-key-file=/etc/srv/kubernetes/pki/serviceaccount.crt
--token-auth-file=/etc/srv/kubernetes/known_tokens.csv
--basic-auth-file=/etc/srv/kubernetes/basic_auth.csv
--storage-backend=etcd3
--storage-media-type=application/vnd.kubernetes.protobuf
--target-ram-mb=180
--service-cluster-ip-range=10.0.0.0/16
--etcd-quorum-read=false
--audit-policy-file=/etc/audit_policy.config
--audit-log-path=/var/log/kube-apiserver-audit.log
--audit-log-maxage=0
--audit-log-maxbackup=0
--audit-log-maxsize=2000000000
--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,PodPreset,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,Priority,ResourceQuota
--min-request-timeout=300
--runtime-config=batch/v2alpha1=true
--feature-gates=ExperimentalCriticalPodAnnotation=true,AdvancedAuditing=true
--authorization-mode=Node,RBAC
--allow-privileged=true
```

**Comment by liggitt** [comment]
Do admission plugins get saved in a metadata var and persisted?

**Comment by MrHohn** [comment]
> Do admission plugins get saved in a metadata var and persisted?

Checked a bit, this parameter is generated based on the `ADMISSION_CONTROL` env, which is stored on gce metadata server as part of kube-envs:
https://github.com/kubernetes/kubernetes/blob/6737f505de1926fea162557fd5e38e3186e4e3e1/cluster/gce/gci/configure-helper.sh#L1341-L1342

Since we don't explicitly change `ADMISSION_CONTROL` during downgrade, the same set of admission controllers are passed in and causes this failure.

I think we should fix the e2e downgrade framework then...

**Comment by liggitt** [comment]
Does the e2e test framework install 1.7, then upgrade, then downgrade? Or does it install 1.8, then downgrade?

**Comment by MrHohn** [comment]
> Does the e2e test framework install 1.7, then upgrade, then downgrade? Or does it install 1.8, then downgrade?

It installs 1.8, then downgrade.

**Comment by liggitt** [comment]
Is that even supported? I wouldn't expect it to be. 

In a real scenario, metadata should have been locked to the 1.7-set vars and the priority admission plugin would not be enabled in 1.8

Seems like the e2e upgrade tests should resemble reality more

**Comment by MrHohn** [comment]
cc @krousey

**Comment by MrHohn** [comment]
> Does the e2e test framework install 1.7, then upgrade, then downgrade?

I think It makes sense to reconstruct this downgrade job into 1.7->1.8->1.7 model. Retitled a bit.

/assign
/unassign @bsalamat

**Comment by MrHohn** [comment]
Fixed via https://github.com/kubernetes/test-infra/pull/4544. Test is now passing.
