### ISSUE TITLE
kubectl exec echoes characters typed to output (?)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#52239]
(Not entirely sure if this is standard behaviour)

I was trying to get the nginx.conf from the ingress pod (and yes, I should have used `kubectl cp`).  While doing that I typed some keys, and some of the keys were included in the output:
```
kubectl exec -it -n kube-ingress  ingress-nginx-4158219343-5fmc3 cat /etc/nginx/nginx.conf > nginx.conf
```

**Comment by goblain** [comment]
can it be that this was just the local echo of terminal ? avoiding `-it` could be the solution for that.
