### ISSUE TITLE
Tracking: OpenStack Test Cloud for OpenStack Provider Testing

### ISSUE THREAD

**Issue by hogepodge** [kubernetes/kubernetes#52249]
This tracking issue, created at the request of @jamiehannaford (Issue #50246), will follow the enablement of K8s e2e testing on stable OpenStack clusters, using the upstream OpenStack Provider.

Currently changes to the OpenStack provider are not gate tested, which can result in uncaught regressions. This issue will track:

1. Deployment of one or more stable release OpenStack clusters.
  a. Initial cluster of latest stable release, Pike.
  b. Follow up clusters of n-1 and n-2 releases, Ocata and Newton.
2. Enabling automated e2e testing on K8s with the OpenStack provider on these clusters.

**Comment by hogepodge** [comment]
@kubernetes/sig-openstack-misc @kubernetes/sig-testing-misc

**Comment by hogepodge** [comment]
The OpenStack Foundation is currently negotiating with two vendors to provide permanent stable clouds for e2e testing. More information will be provided after the Denver Project Team Gathering on the availability of the first test cloud. Our expectation is a late September or early October delivery on the initial cloud.

**Comment by rootfs** [comment]
cc @kubernetes/sig-storage-misc

**Comment by FengyunPan** [comment]
cc @dims

**Comment by hogepodge** [comment]
Following up from the Denver PTG, delivery date of original two private clouds is being moved to late October. Working with a third public cloud provider for earlier access to a CI account.

**Comment by huzhengchuan** [comment]
cc @huzhengchuan

**Comment by hogepodge** [comment]
Work for adding OpenStack provider to CNCF CI/CD here. https://github.com/hogepodge/cross-cloud/tree/openstack

**Comment by dims** [comment]
@hogepodge - Any updates?

**Comment by hogepodge** [comment]
In progress, I've stood up the infrastructure, now getting the master and worker templates up and running.

**Comment by hogepodge** [comment]
@dims I mostly have the scaffolding up, the cloud-init script is failing because of misconfiguration. If you or anyone else wants to help out I'd love extra eyes on it. https://github.com/hogepodge/cross-cloud/tree/openstack

**Comment by dims** [comment]
@hogepodge do you have steps for me to follow? (to recreate the issue)

**Comment by jamiehannaford** [comment]
I can take a look too if I get some time this week.

Yeah I was gonna ask the same as @dims. What steps do I take to recreate this or just spin up an OS cluster using cross-cloud? Do you have any logs that might be useful?

**Comment by hogepodge** [comment]
Some of the variable are hard coded for vexxhost, so you should watch out for those.

I use `build.sh` to build the container.
You need to source your cloud authentication credentials into your environment.
Then `deploy.sh` to launch. It needs 8 vms, one bastion, one load balancer, three masters, three workers.
`destroy.sh` tears it all down.

The terraform scripts in the `openstack` directory stand up most of the infrastructure (I'm still working on an external load balancer). Terraform will create `cloud-init` scripts that are pulled in through the metadata service, and expect to be run on CoreOS. The failure I'm seeing right now is because of an unknown provider. I'm pretty sure the self-signed cert is also wrong.

**Comment by hogepodge** [comment]
Lots of updates pushed this evening. Still working on getting the installation finished off, but much more progress. On the master nodes the cloud-config is being set up and I can get individual API endpoints to appear. I still need to set up security groups on the nodes and load balancers to allow 8080 and 443. Still some debugging with TLS and the load balancers (they're running and the workers are associated, but pinging the balancer gives a 503 No available servers). I also added documentation to help folks get up to speed. I reduced the number of worker nodes since I'm running out of quota because of wedged instances and load balancers.

**Comment by hogepodge** [comment]
It appears that K8s and etcd are up and running, and with the security group added and the load balancers corrected, there's some amount of external access.

However, K8s is not serving on the local network, and can only be reached on the localhost.

**Comment by dims** [comment]
@hogepodge what version of docker? if i remember there there was an iptable rule that needed fixing

**Comment by hogepodge** [comment]
@dims Docker version 1.12.6, build d5236f0

**Comment by hogepodge** [comment]
I have the collection of master nodes up and running with external secure connectivity to a load balancer. Going to get cracking on the worker nodes next and see if the cluster is functioning properly.

**Comment by hogepodge** [comment]
Latest patches have full cluster up and running.

```
./kubectl get nodes
NAME                   STATUS    ROLES     AGE         VERSION
cross-cloud-master-1   Ready     master    <invalid>   v1.8.1
cross-cloud-master-2   Ready     master    <invalid>   v1.8.1
cross-cloud-master-3   Ready     master    <invalid>   v1.8.1
cross-cloud-worker-1   Ready     node      <invalid>   v1.8.1
cross-cloud-worker-2   Ready     node      <invalid>   v1.8.1
cross-cloud-worker-3   Ready     node      <invalid>   v1.8.1
```

Next steps are to check e2e tests. Also need to submit a PR to cncf to merge into their main repo. Will need to squash, document, and test a bit first.

**Comment by hogepodge** [comment]
Great news, after more patching and debugging, a number of issues have been resolved. Two weeks later than I wanted, but a bunch of upstream issues were resolved.

NAME                   STATUS    ROLES     AGE       VERSION
cross-cloud-master-1   Ready     master    2m        v1.8.1
cross-cloud-master-2   Ready     master    1m        v1.8.1
cross-cloud-master-3   Ready     master    2m        v1.8.1
cross-cloud-worker-1   Ready     node      43s       v1.8.1
cross-cloud-worker-2   Ready     node      48s       v1.8.1
cross-cloud-worker-3   Ready     node      49s       v1.8.1

**Comment by hogepodge** [comment]
https://github.com/cncf/cross-cloud/pull/111

**Comment by hogepodge** [comment]
cross-cloud tracking issue https://github.com/crosscloudci/crosscloudci/issues/9

**Comment by hogepodge** [comment]
New PR on crosscloudci project https://github.com/crosscloudci/cross-cloud/pull/128

**Comment by hogepodge** [comment]
Full integration testing implemented in https://github.com/kubernetes/cloud-provider-openstack. Closing.
