### ISSUE TITLE
Change `GCEDiskAlphaAPI` to `DiskAlphaAPI` in comments

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#52258]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In a number of comments in https://github.com/kubernetes/kubernetes/pkg/cloudprovider/providers/gce/gce.go mentions `GCEDiskAlphaAPI`.

**What you expected to happen**:

That flag is actually `DiskAlphaAPI` not `GCEDiskAlphaAPI`.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Comment by dims** [comment]
@saad-ali looks like there are 2 PR(s) for this issue, can you please review them? hoping we get this in for 1.8

**Comment by saad-ali** [comment]
Not a 1.8 blocker. Moving out of milestone.
