### ISSUE TITLE
util.sh missing when trying to run quickstart instructions

### ISSUE THREAD

**Issue by davecheney** [kubernetes/kubernetes#52255]
/kind bug

**What happened**:

Followed the quick start guide here https://github.com/kubernetes/kubernetes#to-start-developing-kubernetes

**What you expected to happen**:

make completed sucessfully

**How to reproduce it (as minimally and precisely as possible)**:
```
zapf(~) % go get -d k8s.io/kubernetes                                                                                 
package k8s.io/kubernetes: no Go files in /Users/dfc/src/k8s.io/kubernetes                                            
zapf(~) % cd $GOPATH/src/k8s.io/kubernetes                                                                            
zapf(~/src/k8s.io/kubernetes) % make                       
hack/make-rules/../../hack/lib/init.sh: line 39: /Users/dfc/src/k8s.io/kubernetes                                     
/Users/dfc/src/k8s.io/kubernetes/hack/lib/util.sh: No such file or directory                                          
make[1]: *** [_output/bin/deepcopy-gen] Error 1            
make: *** [generated_files] Error 2      
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration**: n/a
- OS (e.g. from /etc/os-release): macOS Sierra(10.12)

**Comment by feiskyer** [comment]
@davecheney The file does exist in kubernetes codebase, maybe it is removed in your local repo?

**Comment by davecheney** [comment]
Thanks for your reply. This is a clean checkout following the instructions
in the README (see issue report) so I don't think I removed the file --
most likely it's not part of the repo.

**Comment by feiskyer** [comment]
See <https://github.com/kubernetes/kubernetes/blob/master/hack/lib/util.sh>

**Comment by davecheney** [comment]
@feiskyer thank you for your reply. Please see the instructions in the project README whichdo no mention this file. https://github.com/kubernetes/kubernetes#to-start-developing-kubernetes

**Comment by tengqm** [comment]
possibly due to go get incompleteness?

**Comment by davecheney** [comment]
Go get returned no error, and I tried the steps twice.

**Comment by tengqm** [comment]
Tried but failed to reproduce the problem you reported.

**Comment by surajnarwade** [comment]
@davecheney Make sure
* `CDPATH` envvar is unset

**Comment by davecheney** [comment]
Thank you, I do have CDPATH set. Do you think it would be possible for the Makefile to unset this?

**Comment by surajnarwade** [comment]
@davecheney , maybe we can add simple line `unset CDPATH`

**Comment by surajnarwade** [comment]
@davecheney, For ref: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#build

**Comment by davecheney** [comment]
@surajnarwade Thank you for pointing that out. As I mentioned in the issue description I followed the quickstart instructions on the main README of the repo. If these instructions are incomplete because of the `CDPATH` requirement, could they be updated? Although I agree with you that it would be better to incorporate that into the makefile itself, then `CDPATH` doesn't need to be documented at all.

**Comment by mahdix** [comment]
I think the correct approach is to handle the case where CDPATH is defined in the system. This will make building the project easier and instructions simpler.

**Comment by cblecker** [comment]
I would also note:
Having a `CDPATH` set isn't an issue, it's only when a CDPATH doesn't search the cwd first. Having a `CDPATH` with a leading `:` solves for this use case.

**Comment by kulong0105** [comment]
will be better to use `readlink` to get the full dir ?
```
KUBE_ROOT="$(readlink -e  "$(dirname "${BASH_SOURCE}")/../..)"
```
