### ISSUE TITLE
GCE audit policy has an obsolete list of resources

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#52265]
Currently, GCE audit policy is v1alpha1 and doesn't match the list of resources in 1.8. It has to be updated before the release and e2e should check that it's correct.

**Comment by crassirostris** [comment]
@jdumars @calebamiles Are you OK with fixing this bug in 1.8?

**Comment by liggitt** [comment]
@tallclair the current mechanism of generating the GCE audit doesn't seem maintainable if we want to automatically pick up new resources. is there a reason we didn't exclude specific resources instead?

**Comment by tallclair** [comment]
The purpose of this list was to exclude third party resources, since we don't know what kind of data they could include (could be sensitive PII, could be large). Perhaps we could build in a way of identifying 3rd party resources.

**Comment by liggitt** [comment]
> Perhaps we could build in a way of identifying 3rd party resources.

We really don't want that distinction leaking into external layers like admission

**Comment by tallclair** [comment]
In that case maybe an e2e test to catch when a new group is added, but the list isn't updated.

**Comment by liggitt** [comment]
checking via a test would be preferable

**Comment by jdumars** [comment]
It looks like the last PR associated with this is on deck to merge soon.  Is there more to do here, or will that close out this issue?
