### ISSUE TITLE
Clarify ExternalNames are hostnames not DNS names

### ISSUE THREAD

**Issue by kyrias** [kubernetes/kubernetes#52266]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The documentation claims that `ExternalNames` should be DNS names, but stricter RFC-1123 hostname validation is enforced.

**What you expected to happen**:
The documentation should either specify that they need to be valid RFC-1123 hostnames, or the code should not reject valid DNS names.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `Service` with an `externalName` of `db_eu.example.com`, it throws the following error:

```
The Service "db-eu" is invalid: spec.externalName: Invalid value: "db_eu.example.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2

**Comment by kyrias** [comment]
@kubernetes/sig-docs
@kubernetes/sig-api-machinery

**Comment by adnavare** [comment]
Hi @kyrias Can you please point out what document this description of ExternalName has been given?

**Comment by kyrias** [comment]
@adnavare https://kubernetes.io/docs/api-reference/v1.8/#servicespec-v1-core

**Comment by adnavare** [comment]
@kyrias thanks. Can you assign this to me? Or can i assign on my own?

**Comment by kyrias** [comment]
I don't have permission to assign.  @dims might be able to help.

**Comment by dims** [comment]
hmm, yes, bot disagrees. So, at least those who are looking at the comments will see it @adnavare

**Comment by adnavare** [comment]
@dims  thanks. Can i submit a patch though?

**Comment by dims** [comment]
yes of course @adnavare

**Comment by adnavare** [comment]
I have submitted a PR here https://github.com/kubernetes/website/pull/6077

**Comment by stawii** [comment]
Why tho? It should handle any valid DNS names, not only host names. The external service name could be CNAME too so it does not have to comply to RFC-1123.
I believe `ExternalName` should be RFC-2181 valid (if my google-foo is right), or there should be an option to do-what-i-say and ignore checking, if possible.
