### ISSUE TITLE
man pages do not build reproducibly

### ISSUE THREAD

**Issue by bmwiedemann** [kubernetes/kubernetes#52269]
/kind bug

**What happened**:
When building kubernetes-1.7.0 packages for openSUSE, results differ for each build in `/usr/share/man/man1/kubectl.1` and other man pages.
> -\fB\-\-cloud\-provider\-gce\-lb\-src\-cidrs\fP=209.85.152.0/22,209.85.204.0/22,130.211.0.0/22,35.191.0.0/16
> +\fB\-\-cloud\-provider\-gce\-lb\-src\-cidrs\fP=35.191.0.0/16,209.85.152.0/22,209.85.204.0/22,130.211.0.0/22

coming from `pkg/cloudprovider/providers/gce/gce_loadbalancer.go`
that uses `netsets.ParseIPNets([]string{"130.211.0.0/22", "35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"}...)`
and probably sets do not have any specific order, so it would need to be sorted on output.

**What you expected to happen**:
Every build should give identical results. See https://reproducible-builds.org/ for why this matters.

**How to reproduce it (as minimally and precisely as possible)**:
See #48710

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.7.0
- OS (e.g. from /etc/os-release): openSUSE Tumbleweed

**Comment by bmwiedemann** [comment]
@ixdy somehow this bug seems to have been forgotten - can you help getting the right people to have a look?

**Comment by dims** [comment]
@bmwiedemann - can you please confirm that PR #57008 works for you?

**Comment by bmwiedemann** [comment]
I tested it and it looks good.

**Comment by ixdy** [comment]
/assign @dims 

I enjoy reading my highlights to find the issue has already been addressed. :)

**Comment by ixdy** [comment]
@bmwiedemann Sorry this wasn't addressed sooner. It does seem like it fell into a black hole, and pinging was the right way to resolve that. :)

**Comment by dims** [comment]
related to https://github.com/kubernetes/release/issues/637

/reopen
