### ISSUE TITLE
[e2e test]: pull-kubernetes-federation-e2e-gce test always fail

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/kubernetes#52270]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Tests about https://github.com/kubernetes/kubernetes/pull/51889 always generate pull-kubernetes-federation-e2e-gce failure. Seems not relevant to the PR https://github.com/kubernetes/kubernetes/pull/51889 after checking the details. 

**log:**
I0911 10:09:03.239] process 22525 exited with code 0 after 0.5m
I0911 10:09:03.239] Call:  git checkout -B test db809c0eb7d33fac8f54d8735211f2f3a8fc4214
W0911 10:09:04.570] Switched to a new branch 'test'
I0911 10:09:04.582] process 22538 exited with code 0 after 0.0m
I0911 10:09:04.583] Call:  git merge --no-ff -m 'Merge +refs/pull/51889/head:refs/pr/51889' 3e3f9990ddfc3a003aad71340dc1294daa6764f6
I0911 10:09:05.164] Merge made by the 'recursive' strategy.
I0911 10:09:05.169]  plugin/pkg/scheduler/algorithm/predicates/error.go |  39 +++----
I0911 10:09:05.169]  .../scheduler/algorithm/predicates/predicates.go   |  44 ++++----
I0911 10:09:05.169]  .../algorithm/predicates/predicates_test.go        | 115 +++++++++++++--------
I0911 10:09:05.169]  3 files changed, 114 insertions(+), 84 deletions(-)
I0911 10:09:05.170] process 22539 exited with code 0 after 0.0m
I0911 10:09:05.170] Checkout: /var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release master
I0911 10:09:05.170] Call:  git init k8s.io/release
... skipping 573 lines ...
I0911 10:22:30.580] md5sum(kubernetes-test.tar.gz)=0225e5099a5d437c9f404a5302ae54c7
I0911 10:22:31.161] sha1sum(kubernetes-test.tar.gz)=7528c3aada4254ce0458942a7eb928207940ffb7
I0911 10:22:31.161] 
I0911 10:22:31.162] Extracting kubernetes-test.tar.gz into /workspace/kubernetes
W0911 10:22:38.006] 2017/09/11 10:22:38 util.go:131: Step './get-kube.sh' finished in 11.992213626s
W0911 10:22:38.006] 2017/09/11 10:22:38 util.go:129: Running: ./federation/cluster/federation-down.sh
**`W0911 10:22:38.195] error: context "e2e-f8n-agent-pr-52-0" does not exist`**
I0911 10:22:38.296] Cleaning Federation control plane objects
I0911 10:22:38.608] No resources found
I0911 10:22:39.115] No resources found
I0911 10:22:39.263] +++ [0911 10:22:39] Removing namespace "f8n-system-agent-pr-52-0", cluster role "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-a-federation-e2e-gce-us-central1-f" and cluster role binding "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-a-federation-e2e-gce-us-central1-f" from "federation-e2e-gce-us-central1-a"
I0911 10:22:39.263] +++ [0911 10:22:39] Removing namespace "f8n-system-agent-pr-52-0", cluster role "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-b-federation-e2e-gce-us-central1-f" and cluster role binding "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-b-federation-e2e-gce-us-central1-f" from "federation-e2e-gce-us-central1-b"
I0911 10:22:39.263] +++ [0911 10:22:39] Removing namespace "f8n-system-agent-pr-52-0", cluster role "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-f-federation-e2e-gce-us-central1-f" and cluster role binding "federation-controller-manager:e2e-f8n-agent-pr-52-0-federation-e2e-gce-us-central1-f-federation-e2e-gce-us-central1-f" from "federation-e2e-gce-us-central1-f"
... skipping 20 lines ...
I0911 10:44:42.118] Creating federation control plane service...................................................................................................................................................................................................................................................Dumping Federation and DNS pod logs to /workspace/_artifacts
W0911 10:44:42.219] I0911 10:24:42.157731    4041 init.go:305] Creating a namespace f8n-system-agent-pr-52-0 for federation system components
W0911 10:44:42.219] I0911 10:24:42.179313    4041 init.go:314] Creating federation control plane service
W0911 10:44:42.219] 2017/09/11 10:44:42 util.go:131: Step './federation/cluster/federation-up.sh' finished in 20m0.402805001s
W0911 10:44:42.219] 2017/09/11 10:44:42 e2e.go:460: Dumping Federation logs to: /workspace/_artifacts
W0911 10:44:42.219] 2017/09/11 10:44:42 util.go:129: Running: ./federation/cluster/log-dump.sh /workspace/_artifacts
**`W0911 10:44:42.620] Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver, verb=get, resource=nodes, subresource=proxy)`**
W0911 10:44:42.623] 2017/09/11 10:44:42 util.go:131: Step './federation/cluster/log-dump.sh /workspace/_artifacts' finished in 553.886159ms
**`W0911 10:44:42.623] 2017/09/11 10:44:42 util.go:129: Running: ./federation/cluster/federation-down.sh`**
**`W0911 10:44:42.812] error: context "e2e-f8n-agent-pr-52-0" does not exist`**
I0911 10:44:42.913] Cleaning Federation control plane objects
I0911 10:44:43.028] service "e2e-f8n-agent-pr-52-0-apiserver" deleted
I0911 10:44:43.555] secret "default-token-d678j" deleted

**What you expected to happen**:

pull-kubernetes-federation-e2e-gce test pass.

**How to reproduce it (as minimally and precisely as possible)**:
Just trigger the test job.

**Anything else we need to know?**:
none

@kubernetes/test-infra-maintainers

**Comment by thockin** [comment]
@kubernetes/sig-federation-bugs

**Comment by sjenning** [comment]
This test has failed across all PRs since the last successful run on 9/9 @ 9:39CDT.  It is a blocking test.  The submit queue is blocked.

**Comment by fejta** [comment]
Please fix the tests, which look to be either a federation and/or auth issue.
@kubernetes/sig-federation-test-failures 
@kubernetes/sig-auth-test-failures 

I'd recommend reaching out to these teams on Google Groups as well as slack.

From a sig-testing point of view everything is working as intended. Testing starting failing, we're reporting the failures and holding merges until tests pass.
/remove-sig testing

**Comment by nikhiljindal** [comment]
cc @marun The current federation on call.

federation tests started failing as we ran out of quota.
We are manually deleting the leaked resources to get quota back so that tests start running, while we debug why are we leaking resources.

**Comment by csbell** [comment]
Quota is an issue on the CI tests (leaking health checks and firewall rules) but not the PR builder.

Still investigating.

**Comment by csbell** [comment]
Waiting on https://github.com/kubernetes/kubernetes/pull/52299

**Comment by nikhiljindal** [comment]
Resource leak root cause: https://github.com/kubernetes/kubernetes/issues/52315

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/4533 removed pull-kubernetes-federation-e2e-gce from the list of blocking presubmits; it will still run on presubmit, but it won't block

**Comment by ericchiang** [comment]
cc @kubernetes/sig-multicluster-test-failures

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#14.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
