### ISSUE TITLE
openstack cloud provider not working as `external` 

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#52276]
I have clonned the rancher-cloud-controller-manager repo and changed the main to point to `openstack`. Then, I executed `glide` and built the binary. I ran it in the same machine of my master cluster with: 
`/openstack-cloud-controller-manager --cloud-config cloud.conf --kubeconfig /etc/kubernetes/admin.conf -v=3`
I was able to execute it and the cloud provider seemed to work fine in verstion 1.7. However, this version doesn't have what I want, which is exposing the services with floating IPs. Then, I tried to executed the version from master. But when I see the help of the new `cloud-controller-manager`, all I see is:

``` 
      --alsologtostderr                         log to standard error as well as files
      --cloud-provider-gce-lb-src-cidrs cidrs   CIDRS opened in GCE firewall for LB traffic proxy & health checks (default 209.85.204.0/22,130.211.0.0/22,35.191.0.0/16,209.85.152.0/22)
      --log-backtrace-at traceLocation          when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                          If non-empty, write log files in this directory
      --log-flush-frequency duration            Maximum number of seconds between log flushes (default 5s)
      --logtostderr                             log to standard error instead of files (default true)
      --stderrthreshold severity                logs at or above this threshold go to stderr (default 2)
  -v, --v Level                                 log level for V logs
      --vmodule moduleSpec                      comma-separated list of pattern=N settings for file-filtered logging
```

So, I'm not sure on how the new cloud-controller-manager consumes the kubeconfig and cloud.conf files 

this is how my cloud.conf looks like:
```[Global]
username=user
password=pass
auth-url=https://ip:5000/v3
tenant-id=c869168a828847f39f7f06edd7305637
domain-id=2a73b8f597c04551a0fdc8e95544be8a
[BlockStorage]
bs-version=v2
[LoadBalancer]
subnet-id=6937f8fa-858d-4bc9-a3a5-18d2c957166a
```

/kind bug

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Install tools: kubeadm

**Comment by ss22ever** [comment]
@henriquetruta Thanks, I would like to take that.

**Comment by jamiehannaford** [comment]
@henriquetruta What image or codebase are you building from? The `cloud-controller-manager` binary in master has `--kubeconfig` flag defined [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/options/options.go#L91).

**Comment by dims** [comment]
@ss22ever @henriquetruta - Seems to work for me, see lines 265,266 shows the options. admittedly that's the first step, i still have to try running it

http://paste.openstack.org/show/621114/

Here's my repository:
https://github.com/dims/k8s-cloud-provider/

**Comment by ss22ever** [comment]
@dims @henriquetruta using your repo https://github.com/dims/k8s-cloud-provider/ and doing a make build shows me this output https://gist.github.com/ss22ever/885e9e19b91fa39248875a929c3a77df

**Comment by jamiehannaford** [comment]
@ss22ever You might need to make sure you're using the latest gophercloud. This commit was added recently: https://github.com/gophercloud/gophercloud/commit/d8b7bfe90431e0eafb697424b3a1fe2de76287d3.

**Comment by dims** [comment]
should be fixed now.

/close
