### ISSUE TITLE
`make clean` deleting unexpected files

### ISSUE THREAD

**Issue by mattjmcnaughton** [kubernetes/kubernetes#52271]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
After setting up an IntelliJ project files for the Kubernetes repo, I had IntelliJ related project files in the directory. Wanting to clean up some generated `bazel-*` files, I ran `make clean`. I was surprised to see that my IntelliJ project files were deleted as well.

**What you expected to happen**:

I would have expected `make clean` to remove only files generated by kubernetes development commands. I would not have expected it to not delete files that I created and intended to be long-lasting, but were only usable by me, and thus gitignored.

**How to reproduce it (as minimally and precisely as possible)**:

Create a IntelliJ project for Kubernetes that places `.idea/` or `.iml` files in the repo. Run `make clean`. The IntelliJ project will be deleted.

**Anything else we need to know?**:

I'm not entirely ensure what the correct behavior is here. I see the change to use `git clean -Xdf` was made recently by @cblecker in this [pr](https://github.com/kubernetes/kubernetes/pull/51911). The reasons stated in the pr make a lot of sense to me. However, I think this doesn't cover the edge case in which a file is gitignored because it should be long-lasting and it will be unique to each development environment, and thus should not be removed on every `make clean`.

I'd love to work on figuring out the proper behavior here, and submitting a pr to fix - please let me know how I can help :)

**Comment by cblecker** [comment]
@mattjmcnaughton I'd be interested if you have any suggestions of what to do here. There's a few file system workarounds (such as having your `.idea/` dir outside of the project and symlinking it in.. then you'd just have to restore the symlink after a `make clean`. I think it's more the assumption that it would only remove build artifacts, rather than removing all temp/.gitignored files.

**Comment by mattjmcnaughton** [comment]
@cblecker  I'm not super unfamiliar with idiomatic `make` files, so part of this may be my misunderstanding. My assumption was `make clean` would remove artifacts that could've been created by some make command (i.e. `make bazel-build`). I wouldn't have assumed it would remove all files.

What about having a `make clean` which only removes files generated by `make` and then a `make git-clean` (or `make prune` or `make clean-all`) which removes any gitignored files?

Thanks for your help with this :)

**Comment by xiangpengzhao** [comment]
Agree on `make clean` should only remove those things it created by itself (can be any make sub-commands in Makefile). It'd better not remove other files (even if they're untracked) which may be created by users or user tools. Maybe we can create a blacklist file which includes those things created by `make` and should be removed by `make clean`.

**Comment by mattjmcnaughton** [comment]
@xiangpengzhao that sounds like a good plan to me - @cblecker, what would you think of that is a fix? My understanding is that that would be similar to what was in place before, except before the list was missing artifacts we wanted `make clean` to remove.

**Comment by cblecker** [comment]
I think it's just a difference in assumption around what the command does. When I run "make clean" I want to ensure that that my working copy doesn't have any files that may change or interfere with a build. To me, this is any files we don't check into the repo. Maintaining a list of files that is safe to clean leaves us open to the list falling out of date (which it previously did, which is why the functionality was changed in the first place).

**Comment by mattjmcnaughton** [comment]
Yeah, I think you make a great point @cblecker that it seems like there are two different interpretations of what `make clean` does. I'm not super familiar with `make` - do you know which one is the more "traditional" interpretation?

One thing I think about is that it seems slightly more dangerous to delete too many, instead of too few files - one operation is very easy to address, whereas the other isn't. I think that leads me to prefer a slightly less aggressive `make clean`. 

Thoughts on if it would be helpful for me to write a pr so we have some concrete code to base this chat on?

**Comment by ixdy** [comment]
My opinion is that `make clean` deletes only things that were generated by something `make` did. If I want to delete other files I created, I call `git clean` instead.

**Comment by ixdy** [comment]
oh, but we're using `git clean -X`, which only deletes ignored files. that seems fine to me.

**Comment by mattjmcnaughton** [comment]
I created a [pr](https://github.com/kubernetes/kubernetes/pull/52848) with an optional different implementation so we could have something to compare the current behavior too. Let me know your thoughts :)

**Comment by cblecker** [comment]
IMO, The point of moving to using `git clean -X` was that anything in your dir that isn't a part of the checked in repo has the potential to impact the build. Temp files, generated files, _output directories, etc. The previous functionality maintained a smaller, manual list that *did* become out of date (not just in theory), and caused problems.

I'm open to solutions, but I don't feel great about returning to a manual list as that's what broke things in the first place.

**Comment by mattjmcnaughton** [comment]
You make a great point about the manual white list becoming out of date - and I think its particularly convincing that that's happened in practice.

I have two ideas:

1. Do you think that having two options - `make clean` and `make clean_all` - like in the diff - helps address this? The typical developer can use `make clean` on their local system, while automated processes creating builds can use `make clean_all`?
2. Alternatively, what if instead of having a whitelist of files to delete, we had a blacklist of files not to delete? This solves the issue which caused me to report this "bug" and the potential drift of the blacklist seems much less concerning.

Do either of those sound preferable? If so, I'll update my pr. Thanks for your thought on this @cblecker :)

**Comment by janetkuo** [comment]
I believe this is a bug introduced by #51911, therefore mark this as a bug instead of feature. 

etcd will also be removed by `make clean`, which isn't right.

**Comment by cblecker** [comment]
@janetkuo where is the local etcd being stored? do you have details on the bug?

**Comment by mml** [comment]
> IMO, The point of moving to using git clean -X was that anything in your dir that isn't a part of the checked in repo has the potential to impact the build. Temp files, generated files, _output directories, etc. The previous functionality maintained a smaller, manual list that did become out of date (not just in theory), and caused problems.

Are you talking about builds that take place *outside* of a docker container (or bazel sandbox)?  I don't think we should offer any guarantees about getting a good build outside of docker or a bazel sandbox.

If our containerized build is pulling in the wrong files, though, it seems we could fix that by writing code that is more specific about what it includes.

**Comment by lavalamp** [comment]
Yeah this is a terrible thing to do to people, I have all sorts of stuff in some of my kubernetes directories that I would not be happy if make clean obliterated.

**Comment by caesarxuchao** [comment]
I have dozens of utility shell scripts and example yaml files that are ignored via `.git/exclude/info`. I lost all of them after `make clean` T_T

**Comment by janetkuo** [comment]
> @janetkuo where is the local etcd being stored? do you have details on the bug?

etcd installed by hack/install-etcd.sh is in .gitignore too, so gets deleted by `make clean`:

https://github.com/kubernetes/kubernetes/blob/b6f6419423fc372a5e0a039153ff24b203ef8d8f/.gitignore#L60-L62

**Comment by cblecker** [comment]
@janetkuo Got it. Yeah, that's a problem.

I opened https://github.com/kubernetes/kubernetes/pull/53235 to move to a back to a static list of files to clean. It is more correct than a revert as it adds missing patterns, and it's safer than an `rm -rf`.
