### ISSUE TITLE
'systemctl enable kubelet' fails with 'Unit name kubelet is not valid' error on Linux machine

### ISSUE THREAD

**Issue by ArunSambandam** [kubernetes/kubernetes#52280]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug

**What happened**:

I am facing below error when I tried to enable kubelet, before setting up the master cluster

bash-4.2$ /usr/local/packages/aime/install/run_as_root "systemctl enable /scratch/athirugn/kubernetes/_output/dockerized/bin/linux/amd64/kubelet"
Failed to execute operation: Unit name kubelet is not valid.

**What you expected to happen**:

I am trying to setup Kubernetes Master Cluster. 

I have downloaded kubernetes using "git clone https://github.com/kubernetes/kubernetes" command
I was able to build the binaries using below steps

$ cd kubernetes ; make quick-release

and the exes are present under "_output/dockerized/bin/linux/amd6" directory
I presume that exes are ready-to-use, unlike installing the same from yum repository. Hence I have added the above path to $PATH as well, in my Linux box, so as to access all the exes from the same.

Please let me know on what I am missing here or how to resolve the issue.

**How to reproduce it (as minimally and precisely as possible)**:

$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernetes ; make quick-release
$ /usr/local/packages/aime/install/run_as_root "systemctl enable /scratch/athirugn/kubernetes/_output/dockerized/bin/linux/amd64/kubelet"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.507+db809c0eb7d33f", GitCommit:"db809c0eb7d33fac8f54d8735211f2f3a8fc4214", GitTreeState:"clean", BuildDate:"2017-09-11T14:59:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
**The connection to the server localhost:8080 was refused - did you specify the right host or port?**

- Cloud provider or hardware configuration**:
LINUX.X64 OEL7.2 VM box

- OS (e.g. from /etc/os-release):
NAME="Oracle Linux Server"
VERSION="7.2"
ID="ol"
VERSION_ID="7.2"

- Kernel (e.g. `uname -a`):
Linux slc12ndc 4.1.12-61.1.16.el7uek.x86_64 #2 SMP Fri Oct 21 14:23:20 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by ArunSambandam** [comment]
I came across below link to install and configure kubelet 
https://github.com/kelseyhightower/intro-to-kubernetes-workshop/blob/master/labs/install-and-configure-kubelet.md

=============================================================
bash-4.2# pwd
/scratch/athirugn/kubernetes
bash-4.2# curl -O https://storage.googleapis.com/configs.kuar.io/kubelet.service
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   504  100   504    0     0    623      0 --:--:-- --:--:-- --:--:--   622

bash-4.2# mv kubelet.service /etc/systemd/system/
bash-4.2# cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStart=/scratch/athirugn/kubernetes/_output/dockerized/bin/linux/amd64/kubelet
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

bash-4.2# systemctl daemon-reload
bash-4.2# systemctl enable kubelet
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.
bash-4.2# systemctl start kubelet
bash-4.2# systemctl start kubelet.service

bash-4.2# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-09-12 05:05:16 PDT; 1s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 128112 ExecStart=/scratch/athirugn/kubernetes/_output/dockerized/bin/linux/amd64/kubelet (code=exited, status=1/FAILURE)
  Process: 128110 ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
 Main PID: 128112 (code=exited, status=1/FAILURE)

Sep 12 05:05:16 slc12ndc systemd[1]: Unit kubelet.service entered failed state.
Sep 12 05:05:16 slc12ndc systemd[1]: kubelet.service failed.
=============================================================

From the failure (Process: 128112) in above output, it looks like kubelet is not recognized.

Is there any installation step that I am missing to use kubelet built out github download?

**Comment by andyxning** [comment]
@ArunSambandam 
> /usr/local/packages/aime/install/run_as_root "systemctl enable /scratch/athirugn/kubernetes/_output/dockerized/bin/linux/amd64/kubelet"
Failed to execute operation: Unit name kubelet is not valid.

Of cause, you can not use systemctl to enable an binary file.

> From the failure (Process: 128112) in above output, it looks like kubelet is not recognized.

Have you try to install docker.service in you machine? It is required for kubelet to work.
Or you should check the error log of kubelet service using `journalctl -u kubelet.service`.
