### ISSUE TITLE
[e2e failure] Pods should cap back-off at MaxContainerBackOff

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52282]
@kubernetes/kubernetes-release-managers 
@kubernetes/sig-node-test-failures 
@ihmccreery ref https://github.com/kubernetes/kubernetes/issues/19027

Test is failing on GCE slow and GCI GCE slow:

https://k8s-testgrid.appspot.com/release-master-blocking#gce-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-slow

Example failure

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow/8151#k8sio-pods-should-cap-back-off-at-maxcontainerbackoff-slow

**Comment by sjenning** [comment]
The test nodes appear to lose their authorization for accessing resources about 26m into the test.

One of many "Unauthorized" errors starting at 
```
E0908 21:58:49.869479    3529 secret.go:201] Couldn't get secret kube-system/default-token-jt4rt: Unauthorized
E0908 21:58:49.869506    3529 configmap.go:202] Couldn't get configMap kube-system/fluentd-gcp-config-v1.1: Unauthorized
```

**Comment by abgworrall** [comment]
@krzyzacy , does this ring any bells ?

**Comment by ericchiang** [comment]
The certificates are all expiring:

```
E0911 17:05:06.680865       5 authentication.go:64] Unable to authenticate the request due to an error: [x509: certificate has expired or is not yet valid, x509: certificate has expired or is not yet valid]
```

**Comment by dchen1107** [comment]
I believe this is the regression introduced https://github.com/kubernetes/kubernetes/pull/51844

cc/ @jcbsmpsn @mikedanese @ericchiang Can you guys take a look?

**Comment by ericchiang** [comment]
@dchen1107 thanks. I'll open a PR to revert that.

**Comment by ericchiang** [comment]
Revert here https://github.com/kubernetes/kubernetes/pull/52299
