### ISSUE TITLE
Setting annotation with prefix fails

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#52283]
`kubectl annotate` fails to set annotation containing prefix:

```
$ kubectl annotate node aleksandram-minion-group-9559 cluster-autoscaler.kubernetes.io/scale-down-disabled=true

The Node "aleksandram-minion-group-9559" is invalid: metadata.annotations: Invalid value: "cluster-autoscaler.kubernetes.io~1scale-down-disabled": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.502+5030391c0750ea-dirty", GitCommit:"5030391c0750eaa3fa7ccdef609ae7b22f29e477", GitTreeState:"dirty", BuildDate:"2017-08-30T08:48:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

This has been replicated on head (v1.9.0-alpha.0.408+ea017719e52138-dirty) and with different kubectl versions (1.7.0, 1.7.5). Same command succeeds in GKE running 1.7.4.

Running with v=10, kubectl reports sending the request to API server:

`Request Body: {"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io~1scale-down-disabled":"true"}}}` 

kubernetes/kubectl#60

cc @mwielgus

**Comment by goblain** [comment]
works fine for me on "from scratch" 1.5.2/1.6.6 1.6.6/1.6.6 also just tested on locally started v1.9.0-alpha.0.508+753e01f8f12a40

    request.go:836] Request Body: {"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/scale-down-disabled":"true"}}}

wonder how that `~1` got into your Request Body. Forgive the question but, are you certain your `/` in in fact backslash and not some different UTF character ?

**Comment by aleksandra-malinowska** [comment]
@goblain I think so. It seems kubectl 1.7.* changes this to ~1 (which worked fine with 1.7.4, as described above.) Setting the same string as annotation key using kubectl from repo works fine. Closing it as it was probably due mismatched client/server versions.
