### ISSUE TITLE
Performance improvements to CIDR allocator

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#52292]
Off-shoot of https://github.com/kubernetes/kubernetes/issues/52284. While going through the code today I found some potential improvements that can be made to cidr-allocator:

- [x] add concurrency to cloud-cidr-allocator queue processing
- [x] move node updates out of the main control loop to a separate channel
- [x] ~list instances from cloud provider periodically to find alias ranges of nodes, instead of making individual get calls (but use them as a fallback if list didn't have the result)~
(EDIT: this one's unneeded, as the other alternative I suggested [here](https://github.com/kubernetes/kubernetes/pull/52285#issuecomment-328809157) was implemented)
- [x] use node informer for getting nodes instead of making api calls
- [x] perform PATCHs instead of PUTs to nodes
- [ ] use rate-limited queue to requeue failed items instead of retrying N times back-to-back

cc @kubernetes/sig-network-misc @kubernetes/sig-scalability-misc @bowei @thockin @wojtek-t

**Comment by shyamjvs** [comment]
I'm taking up this issue. IMO, the first 3 are most important and will try to get them in this release.
Suggestions/comments?

**Comment by shyamjvs** [comment]
cc @gmarek (because node-controller :)

**Comment by bowei** [comment]
lgtm, btw -- I'm trying to move all of the logic into imap/... controllers in the future that are parallelized

**Comment by gmarek** [comment]
I assumed that Networking team takes over CIDR allocator. Your changes look fine. You need to be careful with parallelization, as IIRC CIDR map is not thread safe (it might have changed though).

**Comment by bowei** [comment]
There is an internal lock on the CIDR bitmap I noticed.

**Comment by shyamjvs** [comment]
@bowei I'm assigning this to you for remaining improvements. Feel free to redirect as apt.

**Comment by wojtek-t** [comment]
It seems that third will not actually improve things, so let's ignore it for now (it seems that now the limiting factor is qps limit in the k8s client).

For item 4, there is already @shyamjvs `s PR in flight, he will also send out a PR for item 5.
Once both of these are done, I think we should be in good enough shape and we may close this one.

**Comment by shyamjvs** [comment]
All the needed improvements here have been made except the last one (for which I sent out #56352).
