### ISSUE TITLE
GCE controller leaks firewall & health check resources if cluster UID is changed

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#52303]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

GCE controller leaks firewall & health check resources if cluster UID is changed.

**What you expected to happen**:

GCE controller should cleanup resources with old cluster UID.

**How to reproduce it (as minimally and precisely as possible)**:

1. Bring up a 1.7+ cluster on GCE.
2. Create a service with `type=LoadBalancer`.
3. Change cluster UID by editing ConfigMap `ingress-uid` in kube-system namespace.
4. Delete the service.
5. Resources are leaked.

**Anything else we need to know?**:
cc @nicksardo @csbell @madhusudancs @nikhiljindal

**Comment by yujuhong** [comment]
> GCE controller should cleanup resources with old cluster UID.

If cluster ID is mutable, won't we need something else to indicate that the resource is managed by this particular instance of controller OR getting a list of valid cluster IDs to perform garbage collection?

**Comment by nicksardo** [comment]
In the normal use case, changing this value isn't something normally done after service and ingress objects have been created. Ingress has long documented that orphaning resources is the expected behavior: https://github.com/kubernetes/ingress/blob/master/controllers/gce/BETA_LIMITATIONS.md#changing-the-cluster-uid

It would be nice to handle this, but I'm more concerned about orphaning resources with basic operation.

**Comment by MrHohn** [comment]
cc @bowei

**Comment by csbell** [comment]
Since changing the UID is central to multicluster operation, I'd argue that the controller (or at least the multicluster portion of the controller) should handle cases where the value changes as part of its lifecycle. cc @nikhiljindal

**Comment by nicksardo** [comment]
Why does multicluster operation change UIDs when ingresses and services exist?  Shouldn't it only change the UID at the start of the cluster before anything has been created?

**Comment by MrHohn** [comment]
> In the normal use case, changing this value isn't something normally done after service and ingress objects have been created. Ingress has long documented that orphaning resources is the expected behavior: https://github.com/kubernetes/ingress/blob/master/controllers/gce/BETA_LIMITATIONS.md#changing-the-cluster-uid

Per discussion offline, we think it is reasonable for gce controller to have the expectation that cluster UID won't change (as documented). Making change on UID may result in unexpected leakage.

I'm closing this issue.

**Comment by nikhiljindal** [comment]
> Why does multicluster operation change UIDs when ingresses and services exist? Shouldn't it only change the UID at the start of the cluster before anything has been created?

Yes, federation controller tries to set up the provider and cluster UIDs as soon as it starts. There is a race condition between the controller having sufficient time to set them and the user creating the resources.
For ingress, federation ingress controller has special code for waiting for provider and cluster UIDs to be setup before processing ingresses. We could do the same for federation service controller.

Filed https://github.com/kubernetes/kubernetes/issues/52315 to track the required changes to federation controllers.
