### ISSUE TITLE
bazel build failure: SHA of remote archive changed

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52307]
I don't see an existing issue, so opening one for tracking.

PR builds are currently failing due to the SHA of a remote archive changing.

https://github.com/kubernetes/kubernetes/pull/52299#issuecomment-328623722

> The sha256sum of that archive apparently changed.
>
> > $ wget https://github.com/bazelbuild/rules_go/archive/82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
...
$ sha256sum 82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
27a13726ff8621cfa4592fbef116b253043c2b093c8814265dc4489a0e67d229  82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
>
> ???

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/test-infra-maintainers 

cc @krzyzacy @ixdy

**Comment by spxtr** [comment]
cc @ixdy

**Comment by ixdy** [comment]
/assign

We can probably just bump the sha, but I'm trying to figure out what changed...

**Comment by ixdy** [comment]
I found a copy of the .tar.gz which matched the sha256sum (thanks @spxtr!)

There's no diff when I compare the extracted trees. There's also no diff if I compare the `tar tzvf` output on each.

The new and old gzip'd tarballs are slightly different sizes (old 135520 bytes, new 135557 bytes). If I ungzip them, they are the same size (921600 bytes) but they still have different sha256sums.

My best guess at this point is that there was some library change recently which is creating slightly different versions of these tarballs, but I don't know how it's different. I also don't know why the archive tarballs for other repos don't seem to have changed.

**Comment by ncdc** [comment]
go 1.8 vs 1.9 maybe?

**Comment by ixdy** [comment]
It seems like the order of some files in the tarball may have changed.

**Comment by ixdy** [comment]
Yeah, we're not alone:
https://github.com/bazelbuild/rules_go/issues/820
https://github.com/google/protobuf/issues/3619
https://github.com/bazelbuild/bazel/issues/3722
https://github.com/tensorflow/tensorflow/issues/12979

**Comment by ixdy** [comment]
I guess we should start mirroring these archives somewhere rather than depending on GitHub.
