### ISSUE TITLE
federation: Creating a Type LoadBalancer federated service and federated ingress can lead to resource leak

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#52315]
Steps to repro:
Create a federated service of type LoadBalancer and a federated ingress and then delete them.
Expected:
All GCP resources (health checks, firewall rules, instance groups, backend service, etc) should be deleted when service and ingress are deleted.
Actual:
GCP Health check and firewall rules are leaked sometimes.

Explanation:
In kubernetes release 1.7, we [updated the service controller](https://github.com/kubernetes/kubernetes/pull/45524) to create health check and firewall rules whose names are generated using providerID/clusterID ([providerID if it exists, else clusterID](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_clusterid.go#L111-L132)) and since providerID is set by federated ingress controller, service controller looks for a different name if ingress controller sets it after service controller created GCP resources. This race condition between the 2 controller leads to service controller leaking the original health check and firewall rule that it had created.

Possible fixes:
* Service controller should wait for providerID/clusterID to by synced before creating any GCP resources (this will not work in environments where ingress controller is disabled).
* Service controller should have the [same logic](https://github.com/kubernetes/kubernetes/blob/db809c0eb7d33fac8f54d8735211f2f3a8fc4214/federation/pkg/federation-controller/ingress/ingress_controller.go#L455) of syncing providerID and clusterID across clusters as ingress controller (need to ensure that the 2 controllers dont fight with each other).

**Comment by nikhiljindal** [comment]
cc @marun (current on call)
This is one of the reason why some our e2e tests are failing.
We have been leaking the resources for a long time. We ran out of quota now and hence the tests started failing.

As a short term fix, @madhusudancs is going to update his "clean leaked resources" script to clean health checks and firewall rules so that our tests dont run out of quota, but we need a proper fix for this.

**Comment by madhusudancs** [comment]
PR https://github.com/kubernetes/test-infra/pull/4545 is the short-term fix.

**Comment by nikhiljindal** [comment]
@kubernetes/sig-network-feature-requests 
/sig networking

**Comment by walteraa** [comment]
@nikhiljindal The same is happening to DNS entries. I think when a federated service is deleted, all entries referring to this service should be deleted as well. What do you think?

**Comment by nikhiljindal** [comment]
@walteraa Please feel free to file an issue for that. Please include steps to repro if you are able to repro it consistently.

**Comment by kinghrothgar** [comment]
I believe we maybe running into this.  When we spin up a federated ingress-gce, one of the 4 regions randomly ends up with in an extra unused backend:

![2018-01-11_15-19-45](https://user-images.githubusercontent.com/1952767/34846123-28c2787c-f6e5-11e7-9570-1e39bb198b43.png)

One region also always randomly gets set to CPU Utilization instead of Rate:

![2018-01-11_15-19-32](https://user-images.githubusercontent.com/1952767/34846165-4b0416ca-f6e5-11e7-9009-123735d5e685.png)

Each time it is a different region.  We are running 1.8.5-gke.0.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#214.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
