### ISSUE TITLE
CRI: Define the mount behavior when host path does not exist.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#52318]
Currently, Docker create the host directory if the host path does not exist.

For host path, Kubelet doesn't check the host directory existence, and pass the mount to docker directly. @msau42 

Given so, we should:
1) Either clearly define the expectation in CRI;
2) Or create the host directory ourselves when it doesn't exist.

/cc @yujuhong @feiskyer

**Comment by feiskyer** [comment]
I think kubelet should create the host directory if it is not exist.

**Comment by feiskyer** [comment]
Hmm, another problem is how to known whether hostPath is (expected) file or directory? Since it doesn't exist, we can only assume it is a directory?

**Comment by msau42** [comment]
There is a new field in the hostpath spec, that may help:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L629

**Comment by Random-Liu** [comment]
Another thing we may want to clearly define is: If when the host path is a symlink, what is the expected behavior.

**Comment by msau42** [comment]
@Random-Liu can you clarify, when you say "host path", are you referring specifically to hostPath volumes, or to any volume plugin's host-side path that gets passed into CRI?

**Comment by Random-Liu** [comment]
I believe it's `any volume plugin's host-side path that gets passed into CRI`.
