### ISSUE TITLE
Leaking node-healthcheck firewall rule

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#52347]
A couple of gce-scale-performance runs failed due to failing to delete the network, which in turn was due to a couple of leaked firewall-rules (I manually deleted the network later to fix it):

```
W0912 14:34:23.820] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W0912 14:34:23.820]  - The network resource 'projects/kubernetes-scale/global/networks/gce-scale-cluster' is already being used by 'projects/kubernetes-scale/global/firewalls/k8s-fw-a8986c438978c11e7bc7a42010a8e000'
W0912 14:34:23.820] 
I0912 14:34:23.921] Failed to delete network 'gce-scale-cluster'. Listing firewall-rules:
I0912 14:34:24.434] NAME                                     NETWORK            SRC_RANGES                                                    RULES      SRC_TAGS  TARGET_TAGS
I0912 14:34:24.434] k8s-2dd9fdb99ae3b676-node-http-hc        gce-scale-cluster  130.211.0.0/22,35.191.0.0/16,209.85.152.0/22,209.85.204.0/22  tcp:10256            gce-scale-cluster-minion
I0912 14:34:24.434] k8s-fw-a8986c438978c11e7bc7a42010a8e000  gce-scale-cluster  0.0.0.0/0 
```

Ref: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/31

cc @kubernetes/sig-network-bugs @bowei (assigning to you, feel free to reassign as apt)

**Comment by shyamjvs** [comment]
I digged up a bit and seems like the firewall is created by the service-controller as part of `EnsureLoadBalancer()`, which should've been deleted in `EnsureLoadBalancerDeleted()` but wasn't.
Feel free to close the bug if you think it's just a one-off failure.

**Comment by MrHohn** [comment]
Took a quick look, both [32th](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/32) and [31th](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/31) runs have these firewall rules initially but [29th](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/29) doesn't, which indicates something happen in the [30th](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/30) run.

But oddly there is no build log, logs in artifacts are empty as well. Likely that run is badly broken so cluster got terminated forcibly in the middle, and resource are leaked.

Will observe this suite a bit longer.

/assign
/unassign @bowei

**Comment by shyamjvs** [comment]
I think it wasn't caused by this job. We're running this one ([gce-scale-performance](https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance)) and [gce-scale-correctness](https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness) on alternating days in the project. And they both create clusters (network, etc) with the same name. And I think [run-12](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/11) of gce-scale-correctness leaked the firewall (and hence the network) as it's running some correctness tests around load-balancer.

**Comment by MrHohn** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/52495#issuecomment-329568213.

The resource leak was likely caused by test timeout --- GCE operations took too long to finish and the cluster was terminated ahead. Because heathcheck and firewall cleanup in gce controller are coupled with targetpool deletion, deleting cluster while targetpool deletion is pending will leak the resources.

**Comment by shyamjvs** [comment]
Fyi - this affected gce-scale-performance again (ref: run 35 of https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance):

```
I0915 07:05:06.825] Failed to delete network 'gce-scale-cluster'. Listing firewall-rules:
I0915 07:05:07.326] NAME                                          NETWORK            SRC_RANGES                                                    RULES      SRC_TAGS  TARGET_TAGS
I0915 07:05:07.326] k8s-573aeda2986fb435-node-http-hc             gce-scale-cluster  130.211.0.0/22,35.191.0.0/16,209.85.152.0/22,209.85.204.0/22  tcp:10256            gce-scale-cluster-minion
I0915 07:05:07.326] k8s-af4bacd9f991e11e7bcbc42010a8e000-http-hc  gce-scale-cluster  209.85.152.0/22,209.85.204.0/22,130.211.0.0/22,35.191.0.0/16  tcp:31642            gce-scale-cluster-minion
I0915 07:05:07.327] k8s-fw-addd54ec9991e11e7bcbc42010a8e000       gce-scale-cluster  0.0.0.0/0                                                     tcp:81               gce-scale-cluster-minion
I0915 07:05:07.327] k8s-fw-af4bacd9f991e11e7bcbc42010a8e000       gce-scale-cluster  0.0.0.0/0                                                     tcp:80               gce-scale-cluster-minion
I0915 07:05:07.327] k8s-fw-af72f6e8d992011e7bcbc42010a8e000       gce-scale-cluster  10.77.98.3/32                                                 tcp:80               gce-scale-cluster-minion
```

Is there a way to make sure they get deleted even in case of a timeout? I have a dirty hack in my mind - of deleting those as part of kube-down. Maybe you have some better suggestions?

**Comment by MrHohn** [comment]
> Is there a way to make sure they get deleted even in case of a timeout? I have a dirty hack in my mind - of deleting those as part of kube-down.

Consider the frequency this happens, I think it makes sense to implement some cleanup logic within the e2e test. Will give it a try.

**Comment by MrHohn** [comment]
Turned out we already have such cleanup logic, it is just we use an incorrect firewall name and forget to cleanup node health check resources as well. Sent https://github.com/kubernetes/kubernetes/pull/52751 to fix.

**Comment by shyamjvs** [comment]
@MrHohn Thanks for fixing!

**Comment by MrHohn** [comment]
@shyamjvs Sure thing, thanks for reporting!

**Comment by shyamjvs** [comment]
Reopening as it seems like the issue is not fixed yet. For e.g run-16 of https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness failed due to this:

```
W1005 07:03:03.073] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W1005 07:03:03.073]  - The network resource 'projects/kubernetes-scale/global/networks/gce-scale-cluster' is already being used by 'projects/kubernetes-scale/global/firewalls/k8s-fw-a8614c1e4a80f11e7a22642010a8e000'
W1005 07:03:03.073] 
I1005 07:03:03.174] Failed to delete network 'gce-scale-cluster'. Listing firewall-rules:
W1005 07:03:03.480] To show all fields of the firewall, please show in JSON format: --format=json
W1005 07:03:03.481] To show all fields in table format, please see the examples in --help.
W1005 07:03:03.481] 
I1005 07:03:03.795] NAME                                          NETWORK            DIRECTION  PRIORITY  ALLOW      DENY
I1005 07:03:03.795] k8s-a78c454a3a80f11e7a22642010a8e000-http-hc  gce-scale-cluster  INGRESS    1000      tcp:30860
I1005 07:03:03.795] k8s-a8614c1e4a80f11e7a22642010a8e000-http-hc  gce-scale-cluster  INGRESS    1000      tcp:32733
I1005 07:03:03.795] k8s-e2480bb157fd997d-node-http-hc             gce-scale-cluster  INGRESS    1000      tcp:10256
I1005 07:03:03.795] k8s-fw-a71c81150a80f11e7a22642010a8e000       gce-scale-cluster  INGRESS    1000      tcp:81
I1005 07:03:03.795] k8s-fw-a8614c1e4a80f11e7a22642010a8e000       gce-scale-cluster  INGRESS    1000      tcp:80
```

This is also affecting our [gce-scale-performance](https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance) job, both of them being release-blocking jobs.

@MrHohn Could you PTAL?

**Comment by MrHohn** [comment]
@shyamjvs By any chance we could make `gce-scale-correctness` and `gce-scale-performance` use different names so that it will be easier to target the leaking point? Also, in that way one leaking job will not affect the other. Or maybe we could also make different runs use different network names? The scalability job is expensive so it might be great if newer runs wouldn't be affected by the leaked resources from previous run.

I haven't figured out how exactly and when the resource are leaked, but given that the operation cycle of service controller and e2e test process proceed in an asynchronous manner (plus `gce-scale-correctness` always fail ESIPP tests https://github.com/kubernetes/kubernetes/issues/52495), there might be chances we will leak resource even after we put cleanup logic in e2e test.

Will take a deeper look later. Also what you suggested before --- deleting those as part of kube-down --- may also be a viable solution.

**Comment by shyamjvs** [comment]
> @shyamjvs By any chance we could make gce-scale-correctness and gce-scale-performance use different names so that it will be easier to target the leaking point?

I thought about this option, but it's better for them to share the same name for network and other resources (instance-prefix, etc) because that way we ensure that if one of them leaks some resources, the other will delete them during it's startup. Else we'll run out of quota in the scale-testing project (for e.g wrt routes or VMs) by trying to start another 5k-node cluster while the previous one still exists.

> Will take a deeper look later. Also what you suggested before --- deleting those as part of kube-down --- may also be a viable solution.

I went to pantheon and deleted the network and that went through successfully (though `gcloud compute network delete` fails). Wonder if the delete command in kube-down can be modified to delete all sub-resources of the network (like firewalls, etc) before deleting it?

**Comment by MrHohn** [comment]
> Wonder if the delete command in kube-down can be modified to delete all sub-resources of the network (like firewalls, etc) before deleting it?

Sounds reasonable to me. We may need yet another `DELETE_NETWORK_SUBRESOURCES` env to trigger it? As deleting everything correlated to that network sounds a bit dangerous.

**Comment by MrHohn** [comment]
> Sounds reasonable to me. We may need yet another DELETE_NETWORK_SUBRESOURCES env to trigger it? As deleting everything correlated to that network sounds a bit dangerous.

Well, took another look, seems like the actual thing that prevented us from deleting the network was mostly firewall rules, and deleting those sounds safe enough if we are going to delete the network anyway. Will try to make a PR for this.

**Comment by shyamjvs** [comment]
@MrHohn Thanks for fixing the issue with firewalls. However seems like the latest run of gce-scale-correctness still leaked the network (but doesn't seem due to firewall this time):

```
I1017 08:38:30.250] Deleting firewall rules remaining in network gce-scale-cluster: 
W1017 08:38:39.041] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W1017 08:38:39.041]  - The network resource 'projects/kubernetes-scale/global/networks/gce-scale-cluster' is already being used by 'projects/kubernetes-scale/regions/us-central1/subnetworks/gce-scale-cluster'
W1017 08:38:39.041] 
I1017 08:38:39.141] Failed to delete network 'gce-scale-cluster'. Listing firewall-rules:
W1017 08:38:39.423] To show all fields of the firewall, please show in JSON format: --format=json
W1017 08:38:39.423] To show all fields in table format, please see the examples in --help.
W1017 08:38:39.423] 
W1017 08:38:39.689] Listed 0 items.
```

ref: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/19

**Comment by shyamjvs** [comment]
I thought we're deleting the subnets in this case too when we're using custom subnets mode.

**Comment by MrHohn** [comment]
> I thought we're deleting the subnets in this case too when we're using custom subnets mode.

Yep, we are supposed to. I think the scale CI hit the same issue as https://github.com/kubernetes/test-infra/issues/5019 described. I've sent a PR for fixing it https://github.com/kubernetes/kubernetes/pull/54009.

**Comment by shyamjvs** [comment]
For the time-being I manually deleted the subnets and then the network to unblock the next scale job run. But it would be good to have this fixed soon.

cc @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
Closing this issue as we're now deleting all remaining firewall rules in the network before deleting the network itself in kube-down.
For other networking resources in general, we have issue #54323.
