### ISSUE TITLE
E2e conformance test `validates that NodeSelector is respected if matching` fails on an 1.7.5 AWS cluster with Ubuntu nodes

### ISSUE THREAD

**Issue by olegch** [kubernetes/kubernetes#52346]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig aws testing

**What happened**:
E2e conformance test `validates that NodeSelector is respected if matching` fails on an 1.7.5 AWS cluster with a reasonable configuration.

In more details:

When kubelet registers a node on AWS (with `--provider=aws` switch) it sets node name to full private DNS name of the instance (for example `ip-172-16-23-87.ec2.internal`), and the label `kubernetes.io/hostname` is set to the instance's short hostname (for example `ip-172-16-23-87`).

Now when we run e2e conformance tests, one of the tests (namely `validates that NodeSelector is respected if matching`) uses an assumption that `kubernetes.io/hostname` label must have the same value as the node name, and therefore fails.

As far as I can see it may be one of the following:
1) either the test uses a wrong assumption, and the test should be fixed;
2) or the kubelet AWS behaves incorrectly using different values for the node name and for `kubernetes.io/hostname` label value.

To complicate matters, the value of `kubernetes.io/hostname` may be system dependent.
E.g. on redhat based systems, it will be the full hostname, whereas on ubuntu based, it's the short one
(thanks @jsravn for pointing it out).

There may be several possible solutions to this:

1. always use `--hostaname-override` or `--nodename-override` or both for kubelet on AWS instances to ensure that they have the same values,
2. fix kubelet AWS provider so that by default it uses the same value for node name and hostname label
3. fix e2e test so that it does not assume that the values are the same

I personally think that there is nothing wrong with different node name and hostname, and that the test should be fixed (solution 3 above).

**What you expected to happen**:
E2e conformance tests pass even on clusters with nodes with different node name and `kubernetes.io/hostname` values.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.7.5`
- Cloud provider or hardware configuration**: `AWS`
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.3 LTS (Xenial Xerus)`
- Kernel (e.g. `uname -a`): `Linux ip-172-16-23-87 4.4.0-1030-aws #39-Ubuntu SMP Wed Aug 9 09:43:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Kublr, manual
- Others:

**Comment by uthark** [comment]
Looks like we need to add another label:

/kind e2e-test-failure
