### ISSUE TITLE
Static CPU manager policy should release allocated CPUs when container enters "completed" phase.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#52351]
/kind bug
/sig node

When the `restartStrategy` is set to `Never` and a container that was granted exclusive CPUs terminates with a normal exit status, the CPU Manager never receives a `RemoveContainer` call. Kuberuntime should be updated to invoke the container manager's `PostStopContainer` hook on detecting normal termination for these containers. This method is already idempotent since it is currently invoked both from kuberuntime's `killContainer` and `removeContainer` (the latter of which is invoked by GC.)

**How to reproduce it (as minimally and precisely as possible)**:

* Start singleton cluster with static CPU manager policy enabled.
* Start a guaranteed pod with a single container that consumes 1 CPU (to get an exclusive allocation) with restartPolicy never that simply exits `0`.
* Try to start a similar container that won't fit on the node unless the first container's CPU is reaped.
* Observe the second container fails with insufficient CPUs, and this problem does not resolve even after an extended period of time.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8 beta
- Cloud provider or hardware configuration**: all
- OS (e.g. from /etc/os-release): all

cc @derekwaynecarr @sjenning @balajismaniam

**Comment by sjenning** [comment]
Yikes, that's a fun issue.  I guess we need to listen for PLEG events?

**Comment by ConnorDoyle** [comment]
There's a spot in the kuberuntime sync where we think we can make the call.

**Comment by derekwaynecarr** [comment]
well, i knew i would miss something ;-)  good catch.

**Comment by ConnorDoyle** [comment]
All thanks to @balajismaniam's workload perf testing

**Comment by lichuqiang** [comment]
By the way, where is `RemoveContainer` of CPU manager called if `restartStrategy` is set to `Always` or `OnFailure`?
invoked by GC?

**Comment by lichuqiang** [comment]
Hi, @ConnorDoyle Besides, I wonder do we have a mechanism to recover things in state of CPU manager when kubelet restarts?
Here I have a trial, seems it doesn't work as expected, that is:
1. I added a few logs before and after the action of addcontainer and removecontainer in policy, to see the content of state:
2. created a pod that declares an exclusive CPU, and saw logs:
`I0913 16:26:13.006154   28005 policy_static.go:152] state before add---------------assignableCPUs: 1, state: &{{{0 0} 0 0 0 0} map[] {map[0:{} 1:{}]}}`
`I0913 16:26:13.006313   28005 policy_static.go:132] state after add---------------assignableCPUs: 0, state: &{{{0 0} 0 0 0 0} map[80527b1e97a6c51ed69b54abb3a5ea433c08cc33cd77a16fe8e56ebe8671fb24:{map[1:{}]}] {map[0:{}]}}`
3. restarted kubelet
4. deleted the pod, to compare the state `before remove` with that `after add`, I think if recovered, the content of them should be the same. but saw logs:
`I0913 16:28:45.280189   30216 policy_static.go:140] state before remove---------------assignableCPUs:1, state: &{{{0 0} 0 0 0 0} map[] {map[0:{} 1:{}]}}`
`I0913 16:28:45.280236   30216 policy_static.go:146] state after remove---------------assignableCPUs:1, state: &{{{0 0} 0 0 0 0} **map[] {map[0:{} 1:{}]}}`

Seems that the content in state did not recovered, this way, the CPU manager would behavior far from what we expected if kubelet restart.
Did I miss something important?

**Comment by balajismaniam** [comment]
@lichuqiang `RemoveContainer` is called as a part of internal container lifecycle pre-stop and post-stop hooks (see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L573 and https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L809). 

Regarding Kubelet restarts, it is a known issue and captured in https://github.com/kubernetes/kubernetes/issues/52031.

**Comment by derekwaynecarr** [comment]
priority/important-soon

**Comment by lichuqiang** [comment]
@balajismaniam  Well, I understand business in  `internal container lifecycle`, what I wonder is upper behavor, that is, the behavior of `sync` in containerRuntime, When a container with restartStrategy `Always` exits,  It seems that the runtime try to restart new container directly, without calling things like `killContainer`.  So I failed to see the place where remove related hooks called in this case, so here a have a trial:
1. create a pod whose container is in restartStrategy of `Always` and would exit after a perid
          `NAME        READY     STATUS    RESTARTS   AGE`
         `test-pod1   1/1       Running   0          3s`
2. container exited after a peiod:
         `NAME        READY     STATUS      RESTARTS   AGE` 
        `test-pod1   0/1       Completed   0          1m`
3. containerRuntime try to restart it but failed:
       `NAME        READY     STATUS                                         RESTARTS   AGE`
       `test-pod1   0/1       not enough cpus available to satisfy request   1          1m`
4. successfully restart after quite a preiod:
       `NAME        READY     STATUS    RESTARTS   AGE`
       `test-pod1   1/1       Running   5          3m`

So I think the resource is not recycled synchronously, and the remove related hook is called in GC.
Am I right? Does it works in the way we expected?

**Comment by ConnorDoyle** [comment]
@lichuqiang Yes, that's exactly correct. The linked PR with the fix for this issue also helps the situation you described to converge faster.
