### ISSUE TITLE
clean node controller from code that supports version prior to 1.5

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#52356]
As discussed on slack with @gmarek, we might want to clean the node controller from code that ensures backward compatibility for version 1.4 and earlier ones.

/sig node

**Comment by yastij** [comment]
@gmarek - how do we plan to devide this one ? 

The following order for merge should be fine I think:

- the tests for #52402 (we can split also test case deletion if it's too long to review)
- #52402 itself + adding const deletion
- change how we create nodecontroller
- delete `#forcefullyDeletePod()`

**Comment by gmarek** [comment]
Yeah, sounds good.

**Comment by yastij** [comment]
I'll create the PRs accordingly and assign you
