### ISSUE TITLE
Should be able to specific `unconfined` AppArmor profile

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#52370]
**What happened**:

There is no way to disable AppArmor, short of requesting `privileged`.

**What you expected to happen**:

Specifying a profile of `unconfined` should be allowed, and disable AppArmor on the container.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with the annotation:

```
container.apparmor.security.beta.kubernetes.io/$CONTAINER_NAME: unconfined
```

**Comment by liggitt** [comment]
is a profile named "unconfined" an actual profile, or a magic value?

**Comment by dixudx** [comment]
> is a profile named "unconfined" an actual profile, or a magic value?
@liggitt Not an actual profile. It is a special profile name ( or a magic value) that means do not have AppArmor profiles loaded.

**Comment by dixudx** [comment]
@tallclair `"unconfined"` is widely used by `apparmor` and `seccomp`, shall we make it a const var?

**Comment by tallclair** [comment]
@dixudx yes, I commented on the PR.
