### ISSUE TITLE
Openstack config drive as source of truth for instance metadata

### ISSUE THREAD

**Issue by richardalberto** [kubernetes/kubernetes#52378]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
/kind feature

**What happened**:
Openstack's config drive is used as source of truth for instance metadata. Config drive gets out of date pretty quick (as soon as the instance name is updated for example), this will result in an error when trying to start the kubelet service cause the name on the metadata (outdated now) won't match the openstack instance list.

**What you expected to happen**:
Allow the user to disable the use of openstack's config drive as sole source of truth. In other words force a search on the metadata service. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure kubelet service to use openstack as the cloud provider
3. `nova boot --config-drive true --flavor ... --image ... --security-groups "..." --key-name "..." --nic net-id=... currentname`
2. `nova update --name newname currentname`
3. Restart kubelet service

**Anything else we need to know?**:
The restriction is on the order of these calls: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/metadata.go#L146

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**:
Openstack
- OS (e.g. from /etc/os-release):
`NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"`
- Kernel (e.g. `uname -a`):
`Linux 1b24f0b2-c15a-4c67-aef2-be6a0fe378fe 4.4.0-83-generic #106~14.04.1-Ubuntu SMP Mon Jun 26 18:10:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by FengyunPan** [comment]
>Config drive gets out of date pretty quick (as soon as the instance name is updated for example), this will result in an error when trying to start the kubelet service cause the name on the metadata (outdated now) won't match the openstack instance list.

IMO, if getMetadataFromConfigDrive() is failed, we can call getMetadataFromMetadataService(). And if all of them are failed, we will return error. So this doesn't result in an error.

**Comment by richardalberto** [comment]
the issue is that getMetadataFromConfigDrive()  doesn't fail, but the results are out of date. getMetadataFromMetadataService() is never called in this scenario.

**Comment by FengyunPan** [comment]
Oh, I see. So can you file a PR to fix it?

**Comment by richardalberto** [comment]
Yeah I'll file a PR, but I wanted to discuss what's the best approach first. The way I see it we have 4 options:
1. Disable config drive with a flag in the kubelet service
2. Don't use the config drive at all, alway query the metadata service. 
3. Change order; query metadata service first and config drive second.
4. Use flag a on the kubelet to select which we want to use

or maybe something else?

**Comment by dims** [comment]
5. Disable config drive in your openstack installation? :)

**Comment by richardalberto** [comment]
Disabling config drive is not always an option, some deployment tools (ex. https://bosh.io) will enable the config drive for you when the vm is created.

**Comment by dims** [comment]
Ah, so looks like we need to supply an ordered list of what to check as a flag

**Comment by richardalberto** [comment]
@dims @FengyunPan do you guys think `cloud.conf` is the correct place for this flag?

**Comment by FengyunPan** [comment]
Yes.

**Comment by anguslees** [comment]
The openstack cloud provider contains deeply embedded assumptions that the node name == instance name.  Just warning that changing the instance name on the fly is not going to work down through the k8s/kubelet stack, even with this change.
