### ISSUE TITLE
Kubelet under MemoryPressure but there are much memory left on the node

### ISSUE THREAD

**Issue by saiwl** [kubernetes/kubernetes#52386]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kubectl describe node shows: 
```
MemoryPressure 	True 	Wed, 13 Sep 2017 12:54:10 +0800 	Wed, 13 Sep 2017 11:54:03 +0800 	KubeletHasInsufficientM
emory 	kubelet has insufficient memory available
```
But the allocated resources show:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  11590m (48%)	9500m (39%)	72888Mi (56%)	72888Mi (56%)
```
And some pods are evicted because of memory reclaiming.
The top shows that there is much free memory. So I can not understand why the node is under `MemoryPressure`.

I saw the following logs in kubelet's log:
```
I0913 15:20:47.884880  104204 helpers.go:826] eviction manager: thresholds - reclaim not satisfied: threshold [signal=memory.available, quantity=100Mi] observed -2097758044639028Ki
I0913 15:20:47.884883  104204 helpers.go:826] eviction manager: thresholds - updated stats: threshold [signal=memory.available, quantity=100Mi] observed -2097758044639028Ki
I0913 15:20:47.884896  104204 eviction_manager.go:288] eviction manager: node conditions - observed: [MemoryPressure]
I0913 15:20:47.884906  104204 eviction_manager.go:297] eviction manager: node conditions - transition period not met: [MemoryPressure]
I0913 15:20:47.884910  104204 helpers.go:826] eviction manager: thresholds - grace periods satisified: threshold [signal=memory.available, quantity=100Mi] observed -2097758044639028Ki
W0913 15:20:47.884917  104204 eviction_manager.go:331] eviction manager: attempting to reclaim memory
I0913 15:20:47.884936  104204 eviction_manager.go:345] eviction manager: must evict pod(s) to reclaim memory
```

**What you expected to happen**:
The node should not be under `MemoryPressure` and not pods will be evicted.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Both on v1.6.7 and v1.7.5. Restarting kubelet doesn't help.
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig kubelet

**Comment by saiwl** [comment]
Seems there is something wrong with kernel.
```
cat memory.usage_in_bytes
2148104380275290112
```

**Comment by ye** [comment]
I am also running into "kubelet has insufficient memory available" issue but the describe node output doesn't show obvious issues - @saiwl was there resolution / explanation you found on your case that can be shared?

**Comment by hfeng101** [comment]
I have got the same questions in using Kubernetes.
![image](https://user-images.githubusercontent.com/5158183/56946015-9a834180-6b5b-11e9-96b7-3526bd9bf3a0.png)

**Comment by salt-mountain** [comment]
Any additional information on this?

**Comment by jianzhangbjz** [comment]
@saiwl Any updates for this issue? Could you help reopen it if it still not be addressed?

**Comment by xiaoluhong** [comment]
/reopen
I have the same issue

**Comment by Zikoel** [comment]
Same problem here, any news?

**Comment by fangzi0813** [comment]
I have the same issue

**Comment by sladg** [comment]
Same problem on EKS with T3 nanos.

**Comment by rthamrin** [comment]
any update? its suddenly happen, and all my nodes agent are Notready

**Comment by cptTomato** [comment]
Same problem here. Node could help itself and is running smooth now, but want to fix that issue quickly.

**Comment by Zikoel** [comment]
In my case (I'm on GKE) I had an error on pool configuration! I setted the maximum spownable pod number on a node to a very small value (eg. 10, default 110). The node rapidly reach that number and k8s evict randomly the exceeded pods. What is wrong in my case is that the node log `MemoryPressure` so I have search the error in the wrong place for a lot of time! I understand that is only for my specific case but maybe this can help someone.

**Comment by freefri** [comment]
I have reopened this issue as a new issue https://github.com/kubernetes/kubernetes/issues/107899

Feel free to join the discussion there
