### ISSUE TITLE
Kubernetes Extended Scheduler Json example incorrectly mentioned 

### ISSUE THREAD

**Issue by gnavgire** [kubernetes/kubernetes#52391]
**BUG REPORT**:

@kubernetes/sig-scheduling
@kubernetes/sig-docs
 /kind bug

K8S Extended scheduler example provides incorrect Key for configuring Extenders:
https://github.com/kubernetes/kubernetes/blob/master/examples/scheduler-policy-config-with-extender.json mentions to configure extender by using "extenders" keyword however when configured this way the scheduler skips the extender configuration.

Scheduler Extender configuration needs to be provided with keyword "ExtenderConfigs":

Reproduce: Run scheduler using --policy-config-file using json from the above example extender URL.

Extended scheduler document needs to be updated with "ExtenderConfigs" instead on "extender"

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: Local cluster
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: hack/local-cluster-up.sh
- Others:

**Comment by xiangpengzhao** [comment]
cc @guangxuli

**Comment by wackxu** [comment]
I can help fix it.

**Comment by xiangpengzhao** [comment]
@wackxu seems like @guangxuli is already working on it :)

**Comment by wackxu** [comment]
@xiangpengzhao ok

**Comment by resouer** [comment]
@guangxuli Could you please update your progress here? We need to make sure all bugs fixes are alive instead of hanging on unknown status.

**Comment by xiangpengzhao** [comment]
@wackxu sent a PR #52467 but didn't associate it to the issue.

**Comment by guangxuli** [comment]
@resouer Sorry, I'm OOO these days, yeah, @wackxu had send a PR for this.

**Comment by guangxuli** [comment]
@gnavgire Are you sure the `extenders` invalid in your workaround? I reproduced the issue, the result seems that the keyword `extenders` works correctly.

**Comment by guangxuli** [comment]
@gnavgire hi, could you recheck the issue, or give some extra info for this. If it is not a issue please close this.

**Comment by gnavgire** [comment]
K8S Scheduler policy accepts "extenders" keyword for configuring extended scheduler configuration.

Thanks.
