### ISSUE TITLE
azuredisk CreateVolume should search storage account if no account specified

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#52396]
I found there is behavior change on CreateVolume func, the original design would search storage account if not provided, while from 1.7.2 it would not, see below:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blobDiskController.go#L83-L128
      comments from @rootfs:
If an invalid account name is provided, this line always hits and new storage accounts keep getting created. You can easily exhaust the storage account limit (50?) :)
1.6 code does it differently, see the comment here. No storage account is is going to be created if there is already one with the same sku and location.
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The storage account could be exhausted with current design in azure.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Will fix this in k8s v1.9

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rootfs** [comment]
ping @andyzhangx any update? thanks.

**Comment by andyzhangx** [comment]
@rootfs I have checked current code logic, even if I changed CreateVolume func to `search storage account if not provided`, there would be no chance for customer to use this scenario, see https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_provision.go#L154-L159, there are two options to make it work:
1) change `Dedicated` kind behavior, let it use CreateVolume func directly. `Dedicated` kind is an awful scenario, it will always create a new storage account for new vhd, should be depreciated in my opinion.
2) add a new kind name for azure disk, name could be `default`, `search`, `custom` ? , this will incorporate API change, and doc of azure disk should be updated.
Let me know your comments, thx.
also add @karataliu for the review.

**Comment by rootfs** [comment]
@andyzhangx see the [doc](https://github.com/kubernetes/examples/tree/master/staging/persistent-volume-provisioning#azure-disk), sku and location are search heuristics

**Comment by andyzhangx** [comment]
@rootfs I know current code is a breaking change to the doc, I would like to work out a way to make the code consistent with the doc, seems like option#1 would be the least effort to make it work.
