### ISSUE TITLE
how  to use variables in yaml file of kubernetes ?

### ISSUE THREAD

**Issue by RahulG115** [kubernetes/kubernetes#52409]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind feature
/app kubectl 
/sig cli

**Comment by spzala** [comment]
@RahulG115 hi, one option is use of helm https://github.com/kubernetes/helm for specifying variables in yaml. Also, questions should be asked on https://stackoverflow.com/questions/tagged/kubernetes for a quick answers. If you search there you will find few answers already out there. If you are fine with it, can you please close this issue? Thanks!

**Comment by RahulG115** [comment]
thanks !
@spzala

**Comment by spzala** [comment]
@RahulG115 np, thank you!
