### ISSUE TITLE
a pod have tolerate everything can't running on the node with Noschedule taint

### ISSUE THREAD

**Issue by du2016** [kubernetes/kubernetes#52400]
**What happened**:
a pod have tolerate everything can't running on the node with Noschedule taint

**What you expected to happen**:
pod have tolerate everything can running on the  Noschedule taint
**How to reproduce it (as minimally and precisely as possible)**:
create cluster with kubeadm, default the master have a taint: 
taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      timeAdded: null

then i create a pod :
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: test
spec:
  containers:
  - image: nginx
    name: test
  tolerations:
  - key: "key"
    operator: "Exists"
i think this pod  tolerate everything,why the pod can't  scheduler to the master node,and  events tell me :
No nodes are available that match all of the following predicates:: PodToleratesNodeTaints (1).

**Comment by wackxu** [comment]
@du2016 There is a superfluous words "key" in your yaml. The right yaml is as below:
```
tolerations:
- operator: "Exists"
```

**Comment by du2016** [comment]
thanks
