### ISSUE TITLE
Refactor kube-scheduler configuration

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#52428]
The kube-scheduler configuration API and CLI should be refactored according to the guidelines established in https://github.com/kubernetes/kubernetes/issues/32215 and as part of the broader goals outlined in https://github.com/kubernetes/features/issues/115.

The scope of this issue is to deprecate all kube-scheduler flags except one new flag, `--config`, which specifies the location of a serialized `KubeSchedulerConfiguration`. The `KubeSchedulerConfiguration` object itself (both internal and versioned) and the component entrypoint/bootstrapping will also be refactored as necessary to bring the style in line with the proposals in https://github.com/kubernetes/kubernetes/issues/32215.

@kubernetes/sig-cluster-lifecycle-feature-requests 
@kubernetes/sig-scheduling-feature-requests 
@kubernetes/sig-api-machinery-feature-requests 

/cc @ncdc @timothysc

**Comment by ncdc** [comment]
Since you're working on it...
/assign @ironcladlou

**Comment by mbohlool** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
Why is API Machinery tagged here? Is there something wrong with configmaps?

**Comment by ncdc** [comment]
It is probably more appropriate to notify kubernetes/api-reviewers (I'm purposefully omitting the leading at sign to they don't actually get notified) when the time comes. There is no proposal to move away from a config file (supplied via a configmap).

**Comment by lavalamp** [comment]
Thanks. boilerplate response: SIG API Machinery doesn't own the *contents* of the API.

**Comment by warmchang** [comment]
👍
