### ISSUE TITLE
Broken link in kubernetes/kubernetes github wiki page

### ISSUE THREAD

**Issue by heckj** [kubernetes/kubernetes#52430]
/kind bug

**What happened**:

Under the subject *Why can't my containers find the service they need to connect to?*, on the wiki page on github at https://github.com/kubernetes/kubernetes/wiki/User-FAQ there's a link that reads *environment variable names* that points to the old location for Kubernetes on github: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#how-do-they-work

**What you expected to happen**:

I expected the link to follow to documentation ;-)

**How to reproduce it (as minimally and precisely as possible)**:

* navigate in a browser to https://github.com/kubernetes/kubernetes/wiki/User-FAQ
* find the relevant text `environment variable names`
* click on the link

* you get a 404 since the repository (and related documentation) have been moved and updated.

**Anything else we need to know?**:

I think the correct destination is back in the documentation at https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#environment-variables

**Environment**:

Just a browser in this case

**Comment by heckj** [comment]
@kubernetes/sig-docs - found this while traversing from the kubernetes.io docs to the "User FAQ", which is apparently in the github wiki pages for kubernetes/kubernetes.

**Comment by xiangpengzhao** [comment]
FYI: https://github.com/kubernetes/community/issues/116

/cc @bgrant0607 @philips

**Comment by bgrant0607** [comment]
I just marked that page as obsolete. It will be removed once we ensure all important topics are covered by docs.

**Comment by heckj** [comment]
@bgrant0607 There's some doc updates that need to happen with that - there are 4 links from within the current kubernetes.io docs to that page if we're removing it:

 - `_data/tasks.yml`:    path: https://github.com/kubernetes/kubernetes/wiki/User-FAQ#how-do-i-change-the-size-of-my-cluster/
 - `docs/home/index.md`:* [User FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ)
 - `docs/tasks/debug-application-cluster/debug-application.md`:Users are highly encouraged to check out our [FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ).
 - `docs/tasks/debug-application-cluster/troubleshooting.md`:   * [User FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ)

**Comment by bgrant0607** [comment]
@heckj Thanks. Please file an issue on the kubernetes.github.io repo.
