### ISSUE TITLE
kubectl 1.7+ fails to get rollout history for any deployment on older clusters.

### ISSUE THREAD

**Issue by adrianchifor** [kubernetes/kubernetes#52434]
kubectl 1.7+ fails to get the rollout history for any deployment on our 1.5.7 cluster. However kubectl 1.5.7 works just fine.

We are using kubectl 1.7+ because any version below 1.7 appears to not preserve the order of environment variables when applying templates (issue #47248).

/kind bug

**What happened**:
`kubectl rollout history deployment/x` (Using 1.7.5)

```
deployments "x"
No rollout history found.
```

**What you expected to happen**:
`kubectl rollout history deployment/x` (Using 1.5.7)

```
deployments "x"
REVISION	CHANGE-CAUSE
7		<none>
8		<none>
9		<none>
10		<none>
```

**How to reproduce it (as minimally and precisely as possible)**:
Use kubectl 1.7.5 on k8s 1.5.7 cluster to get rollout history for deployments.

**Environment**:
- Kubernetes version: server 1.5.7, client 1.7.5
- Cloud provider: AWS
- OS: CoreOS server, OSX 10.11.6 client
- Kernel: Linux kernel 4.12.10 server, Darwin kernel 15.6.0 client

**Comment by msgongora** [comment]
I'm having same issue:
```
$ kubectl version && kubectl rollout history deploy/chatserver
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
deployments "chatserver"
No rollout history found.


$ ./kubectl-1.5.8 version && ./kubectl-1.5.8 rollout history deploy/chatserver
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.8", GitCommit:"e8c167a115ec662726904265d17f75a6d79d78d8", GitTreeState:"clean", BuildDate:"2017-10-01T00:19:21Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
deployments "chatserver"
REVISION	CHANGE-CAUSE
1		<none>
3		<none>
4		<none>
...
```

**Comment by alyyousuf7** [comment]
/remove-lifecycle stale

I'm facing the same issue on v1.10.2
