### ISSUE TITLE
Supporting docker log splitting in Kubernetes logging integrations

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#52444]
Follow-up of https://github.com/kubernetes/kubernetes/issues/52433

Docker 1.13 introduced a change into the logging mechanism (https://github.com/moby/moby/pull/22982), that split the log lines longer than 16K into chunks of no more than that. Current default logging integrations (fluentd-gcp and fluentd-es addons) do not support that and this might result in broken ingestion, i.e. when JSON parsing is broken for entries longer than 16K.

One possible solution is introducing a fluentd plugin to the configuration to concat such entries in the similar way https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions does it (assuming there is one out there, cc @tagomoris @repeatedly @edsiper for that)

/cc @igorpeshansky @fgrzadkowski @piosz

**Comment by igorpeshansky** [comment]
Presumably this should be done in the Docker fluentd logging driver... The discussion on https://github.com/moby/moby/issues/34620 seems to be leaning that way...

**Comment by repeatedly** [comment]
In fluentd logging driver side, journald driver approach is better: https://github.com/moby/moby/blob/80edccda708c6771824c245b4d634c2a9ce29795/daemon/logger/journald/journald.go#L110
I'm not sure buffering partial message in logging driver is good or not...

In fluentd side, implementing `in_docker_forward` or `filter_docker_xxx` is needed.

**Comment by dims** [comment]
@crassirostris @repeatedly @igorpeshansky do we need to block 1.8 release? can we please move this out of 1.8 if it's not?

**Comment by crassirostris** [comment]
@dims Moved to 1.9, since it's not specific for 1.8

**Comment by JorritSalverda** [comment]
Is there any way this can be fixed by running a custom fluentd? Or is there a fluentd docker driver github issue  I can follow for updates on when they expect to have this fixed? Txh

**Comment by crassirostris** [comment]
> Is there any way this can be fixed by running a custom fluentd?

Problem is that there's no fluentd plugin to fix the problem, so running a custom fluentd won't help, there's nothing to add to the configuration to make it work (unless you want to write your own solution)

> is there a fluentd docker driver github issue I can follow for updates on when they expect to have this fixed

https://github.com/moby/moby/issues/34855

They don't think it's a docker problem and don't plan to fix it

**Comment by JorritSalverda** [comment]
That seems fair from Docker's perspective. I'd rather have stable containers as well :)

So you're thinking of switching from the current log drive `json-file` - at least that's what my Google Container Optimized image in GKE 1.8.1 uses - to the journald driver to circumvent the problem? And then use a plugin like https://github.com/okushchenko/fluent-plugin-docker-journald-concat to recombine the partial messages?

**Comment by crassirostris** [comment]
@JorritSalverda

> So you're thinking of switching from the current log drive json-file

No, that's not the case. Solution is TBD, but if you export your logs to Stackdriver (that has a limit of 100KB per entry) you won't see the difference

**Comment by JorritSalverda** [comment]
I think there's still a difference in that the 100KB stackdriver logging limit is larger than the 16KB docker limit at which the partial messaging starts, so without proper recombination of those chunked messages you'll lose the ability to send log lines larger than 16KB into stackdriver.

However we're also running our own fluentd that sends messages straight into pub/sub, which has a limit of 10MB per message. And although we're trying to keep the messages much smaller than 16KB it would be nice to be able to send bigger messages without instrumenting our applications to push the messages into pub/sub themselves.

I hope you find a nice solution that will make this possible :)

**Comment by crassirostris** [comment]
/remove-lifecycle rotten

Still relevant, hasn't been fixed

**Comment by abedwardsw** [comment]
I've been reading up on this issue, it's really too bad docker would not allow the configurable log-max-size option, this would be an easy temporary workaround to the issue until fully resolved.   Regardless, I also wanted to point out a 2nd issue that the log splitting causes which might help increase the priority of this issue.

If you are using json logging and have MCD or Structured Arguements attributes in your log messages, what ends up happening unfortunately is the attributes are lost on the split messages.   This is a huge drawback right now.   In my case I am using spring cloud sleuth which adds span and traceid's to all log messages allowing you to easily filter and correlate all related logging messages.  When the messages are split, the traceid's are not part of the message in elasticsearch making filtering by traceid impossible.

My application logging is setup as follows:
https://developers.redhat.com/blog/2018/01/22/openshift-structured-application-logs/

is it still the plan to have fluentd put the logs back together into a single message?  can anyone update if any progress is being made?

thanks for your help.

**Comment by igorpeshansky** [comment]
/remove-lifecycle rotten

Still relevant, hasn't been fixed

**Comment by desaintmartin** [comment]
Would using the "concat" fluentd plugin be relevant?
https://github.com/fluent-plugins-nursery/fluent-plugin-concat
It seems to have explicit support for our specific use case.

**Comment by liangjacky** [comment]
trying to solve this as well. Having the same issue as @abedwardsw where long lines are being truncated and MDC gone.

**Comment by ju-la-berger** [comment]
Please see
* https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/59
* https://github.com/moby/moby/issues/37889

Basically, you have to consider three cases:
* A very long log message (single line) of more than 16 KB is split by Docker into multiple log messages.
* Your application log message has linebreaks, so it is split by Docker into multiple log messages.
* A combination of the above two cases.

However, in the end you want just one log record in your log management backend (e.g. just one document in ES).

Another big problem here is concurrency. Just concatenating all partial log messages as they arrive may be wrong. Let's say your app logs two events, called `a` and `b` here. Then the Docker log messages may be written to the JSON log file (or whatever Docker logging driver is used, e.g. in plain Docker or Docker Swarm) in this order:
```
a (first 16 KB)
b (first line)
a (another 5 KB)
b (second line)
b (third line)
```
The fluentd concat plugin cannot decide what to do. What records belong together?

The good message is: This can be solved (similar to https://github.com/moby/moby/issues/37889) as Docker logs contain all the needed information here:

https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/api/types/backend/backend.go#L32

So you just have to extend these methods and the `JSONLogs` struct by the partial log meta data:

https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/logger/jsonfilelog/jsonfilelog.go#L143
https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/logger/jsonfilelog/jsonlog/jsonlogbytes.go#L22

Then you have to fix https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/59 and bingo.

**Comment by ju-la-berger** [comment]
I just edited my above comment because I am not sure how the case of linebreaks (i.e. those written by the application) in log messages relate to this issue.

However, often you can control the logging of your application and let it write JSON to STDOUT (e.g. https://github.com/logstash/logstash-logback-encoder for Java / Spring Boot applications) so you do not have linebreaks.

Back to the original issue:

@desaintmartin: I have serious doubts that https://github.com/kubernetes/kubernetes/pull/68012 will do it under load with a lot of concurrent partial messages. I observed this in a Docker Swarm setup with fluentd and the concat plugin configured analogously.

**Comment by ju-la-berger** [comment]
@crassirostris Could you please reopen this issue?

The concurrency is the problem here: Let your container simultaneously produce two log messages of >16KB (let's say 20 KB). Then fluentd will concatenate all four messages to one large (16+16+4+4 KB = 40 KB) message. The fluentd (or whatever you use) needs to know the ID of the partial log metadata to concatenate only those messages with identical IDs. So this needs to be implemented in the (default) local JSON file log driver in Docker (moby).

**Comment by desaintmartin** [comment]
Problem is that ID comes with Docker 18.06 if I'm not wrong, this is why I didn't use it: do we want to require a docker version which is 2 months old?

**Comment by coffeepac** [comment]
@crassirostris is no longer much involved with the project.  if you would like to open this back up to alter the implementation, please file a new issue @ju-la-berger.

**Comment by desaintmartin** [comment]
If you do so, please ping me as well.

**Comment by kahootali** [comment]
@desaintmartin I have added the concat plugin 
```
      <filter **.log>
          @type concat
          key log
          multiline_end_regexp /\n$/
      </filter>
```
but still it is not concatenating, Any Idea?

**Comment by desaintmartin** [comment]
No idea why it does not work. For up-to-date information, I have inserted:
```
    # Concatenate multi-line logs (>=16KB)
    <filter kubernetes.var.log.containers.**>
      @type concat
      key log
      multiline_end_regexp /\n$/
      separator ""
    </filter>
```
Just after the kubernetes_metadate injection.
