### ISSUE TITLE
k8s.io/kubernetes/pkg/kubectl/apps.TestApps test continually failing in Test Grid

### ISSUE THREAD

**Issue by seans3** [kubernetes/kubernetes#52446]
/kind bug

test **k8s.io/kubernetes/pkg/kubectl/apps.TestApps** continually failing.

[Test Grid Failure](https://k8s-testgrid.appspot.com/sig-cli#unit-integration-cmd&sort-by-failures=&exclude-non-failed-tests=)
`
<testsuite tests="1" failures="1" time="1.033" name="k8s.io/kubernetes/pkg/kubectl/apps">
<properties>
<property name="go.version" value="go1.8.3"/>
</properties>
<testcase classname="apps" name="TestApps" time="0.000">
<failure message="Failed" type=""/>
</testcase>
</testsuite>
`

**Comment by seans3** [comment]
@kubernetes/sig-cli

**Comment by fejta** [comment]
@kubernetes/sig-apps-test-failures 
/assign @michelleN @mattfarina @prydonius 

@kubernetes/sig-cli-test-failures
@fabianofranz @pwittrock @adohe 

Will someone from sig-cli or sig-apps please review the PR that @seans3 made to fix this outage?

**Comment by pwittrock** [comment]
@fetja #52382 is nearly identical and was supposed to resolve it.  There seems to be another issue.  @mengqiy and @seans3 are looking into it.

**Comment by mattfarina** [comment]
Looking at [test grid](https://k8s-testgrid.appspot.com/sig-cli#unit-integration-cmd&sort-by-failures=&exclude-non-failed-tests=) now, it appears the test is passing again.

**Comment by pwittrock** [comment]
woot.  thanks @mattfarina
