### ISSUE TITLE
Add e2e tests for volume operatin metrics

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#52458]
We should have some e2e tests that verify volume operation metrics are accurate.

cc @msau42 

/sig storage

**Comment by gnufied** [comment]
https://github.com/kubernetes/features/issues/349

**Comment by nikhiljindal** [comment]
Any update on this?
If I understand correctly, there are no e2e tests currently for this new feature

**Comment by gnufied** [comment]
Not yet, I should have tests written by tomorrow.

**Comment by nikhiljindal** [comment]
Since the feature is in 1.8, we need tests in 1.8.
Adding 1.8 milestone.

**Comment by saad-ali** [comment]
@gnufied is out sick today. He says he will have a PR adding the test(s) out by tomorrow.

**Comment by jdumars** [comment]
@saad-ali can you keep me posted on this?  If it's not going to make 1.8 for some reason, we need to move it to 1.9 and cherry pick the work back.

**Comment by gnufied** [comment]
The tests are here - https://github.com/kubernetes/kubernetes/pull/52807

**Comment by saad-ali** [comment]
> @saad-ali can you keep me posted on this? If it's not going to make 1.8 for some reason, we need to move it to 1.9 and cherry pick the work back.

Sorry for the delay in getting back to you. PR https://github.com/kubernetes/kubernetes/pull/52807 is LGTM'd/approved and awating merge.
