### ISSUE TITLE
failing: [sig-instrumentation] Cluster level logging implemented by Stackdriver should ingest logs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#52457]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

EDIT: this probably shows it better
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=AAAAAAAAAAAAAA

I noticed this test started failing across all PR's in the pull-kubernetes-e2e-gce-bazel job this morning.

First failure I noticed:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52289/pull-kubernetes-e2e-gce-bazel/16038

Immediately followed by a pass:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-bazel/16039

Started continuously failing shortly afterwards:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce-bazel/16063

This is also apparently happening for the GKE postsubmit job:
- https://k8s-testgrid.appspot.com/release-master-blocking#gke
- (clicking the changes link for the failing test leads me to https://github.com/kubernetes/kubernetes/compare/be78d113b...991afb243)

**Comment by spiffxp** [comment]
@kubernetes/sig-instrumentation-test-failures FYI

**Comment by spiffxp** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=AAAAAAAAAAAAAA shows the full list of jobs this is hitting

**Comment by yujuhong** [comment]
dup of #52433

**Comment by spiffxp** [comment]
thanks, not sure how I didn't see the original issue, closing as dupe
