### ISSUE TITLE
Add e2e test for feature of exposing PVC usage metrics

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#52459]
In 1.8, we added a new feature https://github.com/kubernetes/features/issues/363  to expose PVC information through summary API so user can check the volume belongs to which PVC. We should add e2e test in summary_test.go under test/e2e_node.

**Comment by dims** [comment]
@jingxu97 @vkamra Can we please move this out of 1.8 milestone?

**Comment by vkamra** [comment]
@dims - I'm looking into adding this but yes we should move this out of 1.8. I don't have permissions to do that though.

**Comment by dims** [comment]
ack @vkamra 

@jdumars @kubernetes/kubernetes-release-managers Can we please move this out of 1.8?

**Comment by nikhiljindal** [comment]
Sorry am not sure why was this removed from 1.8 milestone. Are we not aiming to add the tests in 1.8?
Or Are we disabling the feature or are we fine shipping it without any e2e tests in 1.8?

**Comment by jingxu97** [comment]
The test is added in #52836. I think we can keep this feature in 1.8
