### ISSUE TITLE
Refactor service/endpoints list/watch part among different proxy modes

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#52464]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**What happened**:

There are huge duplication among different proxiers. For example, the service/endpoints list/watch part in iptables, ipvs and windows(to be get in soon). 

I think the more places this is replicated the harder it becomes to keep correct.

**What you expected to happen**:

I assume we may need to refactor it and let different proxiers consume the same code.

**Anything else we need to know?**:

/cc @thockin @wojtek-t @feiskyer @dcbw Any thoughts?

/area kube-proxy

/sig network

**Comment by m1093782566** [comment]
I think the following struct/function can be consumed by different proxiers:

```
type serviceChangeMap struct {
	sync.Mutex
	items map[types.NamespacedName]*serviceChange
}

type serviceChange struct {
	previous *api.Service
	current  *api.Service
}

func newServiceChangeMap() serviceChangeMap {
	return serviceChangeMap{
		items: make(map[types.NamespacedName]*serviceChange),
	}
}

func (scm *serviceChangeMap) update(namespacedName *types.NamespacedName, previous, current *api.Service) {
	scm.Lock()
	defer scm.Unlock()

	change, exists := scm.items[*namespacedName]
	if !exists {
		change = &serviceChange{}
		change.previous = previous
		scm.items[*namespacedName] = change
	}
	change.current = current
}
```

**Comment by m1093782566** [comment]
Then, we may need to introduce an abstract layer for `proxyEndpointsMap` & `proxyServiceMap`? I think that's the most challenging part of this work.

**Comment by m1093782566** [comment]
I find the most tricky part is 

```
type proxyServiceMap map[proxy.ServicePortName]*serviceInfo
type proxyEndpointsMap map[proxy.ServicePortName][]*endpointsInfo
```

Currently `serviceInfo` and `endpointsInfo` are proxy-specific, and if we keep them being proxy-specific, it's difficult to move the duplicated codes outside.

**Comment by wojtek-t** [comment]
Can we hide them behind some interface?
I very quickly looked into "serviceInfo" and the interface wouldn't be big,

Obviously the interface will not expose every information for those, because they will be different.
But then in the code using them, we can actually cast the interface to proxy-specific type.

I think that should actually work.

**Comment by m1093782566** [comment]
Thanks for your quick response, @wojtek-t 

I will try it and will let you know updates :)
