### ISSUE TITLE
`kubectl get nodes` does not work with admission controller NodeRestriction

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/kubernetes#52468]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
1)i add a log line in the
noderestriction module with admission.go, as follows:
 86 func (c *nodePlugin) Admit(a admission.Attributes) error {
 87         nodeName, isNode := c.nodeIdentifier.NodeIdentity(a.GetUserInfo())
 88         glog.Infof("@hml in noderestriction nodename=%s", nodeName)

2)start kube-apiserver with --admission-control=NodeRestriction

3)kubectl get nodes

**What you expected to happen**:
the above code will print a log in a kube-apiserver log file

**How to reproduce it (as minimally and precisely as possible)**:
but there is no log in kube-apiserver log file

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.3
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others

/area admission-control
/sig auth

**Comment by dixudx** [comment]
@vklonghml This may not be a bug. Please be aware of log level.

**Comment by vklonghml** [comment]
@dixudx i add --v=5 with kube-apiserver

**Comment by vklonghml** [comment]
i know what is the problem, because the admission controller could not admit the list(get, watch) request, so it can't admit the list request, so i will close this problem
