### ISSUE TITLE
Critical POD failure

### ISSUE THREAD

**Issue by m-no-2017** [kubernetes/kubernetes#52481]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- bug report

/kind bug
/sig scheduling

**What happened**:
- POD is not able to be scheduled again

**What you expected to happen**:
- POD should start (as it always did the past 13 days)
**How to reproduce it (as minimally and precisely as possible)**:
- I don't think that anyone else can reproduce this behaviour (err msg below)

**Anything else we need to know?**:
We restarted a POD (as we always do) and got the following error message:
<pre><code>Error response from daemon:
{"message":"invalid header field value \"oci runtime error: container_linux.go:247:
starting container process caused \\\"process_linux.go:320:
reading syncT run type caused \\\\\\\"write parent: broken pipe\\\\\\\"\\\"\\n\""}</code></pre>

**Environment**:
- Kubernetes version (use `kubectl version`):
- v1.7.2
- Cloud provider or hardware configuration**:
- bare-metal
- OS (e.g. from /etc/os-release):
- Ubuntu 16.04.03 LTS
- Kernel (e.g. `uname -a`):
- 4.11 (lowlatency)
- Install tools:
- Ansible
- Docker version:
- 1.12.6

**Comment by m-no-2017** [comment]
The specific POD is not able to be scheduled on any host in the cluster, even after a complete fresh setup of kubernetes (v1.7.2).  

As we are new to k8s, we are not able to figure out how we can even attempt to solve this (very critical) issue.

Anomalies:
- POD can be run with plain docker on every host
- no host able to run the container with k8s (same error msg from above on each)

Attempts:
- nuked the whole k8s cluster (2 times, still same error mesasge)
- removed docker and all depending directories/binaries/services
- rebooted the machines

Things we cannot do:
- nuke the physical machines (productive Ceph cluster runs on them)

Is there any expert who can help? @thockin 

Additional infos:
- the /sys/fs/cgroup/*/kubepods or kube-proxy directories cannot be removed and are still present even after a complete teardown

**Comment by m-no-2017** [comment]
Issue is solved:

The Problem was a malformed string (lots of special characters like ? ´ ` _.@ ... etc) in a k8s secret (generic, opaque). After a change of the secrets content it worked.

I must admit, that the error message was kind of misleading and did cost a ton of nerves due to a complete cluster teardown (2x times) in a productive environment.

**Comment by bgehman** [comment]
@m-no-2017 👍 thanks for reporting this -- helped me figure out that a colleague was not base64 encoding his secrets.  Led to the same cryptic error message.

**Comment by MPJHorner** [comment]
Same issue here. I was generating my BASE64 encoded string without UTF-8. (This was default on windows powershell. See below good/bad.

Both use `$Text = "My String to Encode"`

This **didn't work**:

`$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text); $EncodedText =[Convert]::ToBase64String($Bytes); $EncodedText`

This **did work.**

`$sEncodedString=[Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($Text)); $sEncodedString`
