### ISSUE TITLE
Make it possible to override the timeout on a GetLogs call in the client

### ISSUE THREAD

**Issue by mkmik** [kubernetes/kubernetes#52482]
/kind feature

I would like to be able to override the timeout on a `GetLogs` call in the Go client typed API.

The Go client typed pods API has a method GetLogs:

```
func (c *pods) GetLogs(name string, opts *v1.PodLogOptions) *restclient.Request
```

This Request embeds the http client setting obtained from the config, e.g.:

```
        config := ....
        config.Timeout = 1 * time.Minute
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, errors.Trace(err)
	}
        ...
        req := clientset.Pods(namespace).GetLogs(podName, &v1.PodLogOptions{Follow: follow})

        req.Context(ctx) // I can add a context here, further reducing the timeout, but I cannot relax it
        r, _ := req.Stream() 
        // now this call inherits the default timeout, but that value might make not make sense in a streaming call
```

The only option I have is to clone the config, create two clientsets.

Note: the request has a `Timeout` field but it only sets the `timeout=...` query parameter.

I would like to be able to override the effect that the `Timeout` config setting has on methods such as Request.Stream.

(I'm only stating the desired end goal; we can discuss about how to achieve that)

**Comment by mbohlool** [comment]
cc @roycaihw
