### ISSUE TITLE
dnskube and dnsmasq fail to achieve healthy state when RBAC is applied on minikube

### ISSUE THREAD

**Issue by vadimeisenbergibm** [kubernetes/kubernetes#52487]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`dnsmasq` fails to achieve healthy state and is killed and restarted infinetely.
`kubectl describe` contains: 
`Liveness probe failed: HTTP probe failed with statuscode: 503`

**What you expected to happen**:
`dnsmasq` to achieve the healthy state

**How to reproduce it (as minimally and precisely as possible)**:
`minikube start --extra-config=apiserver.Authorization.Mode=RBAC`

**Anything else we need to know?**:
Output of `kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c dnsmasq`:
```
I0914 13:05:35.457888       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0914 13:05:35.458075       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0914 13:05:35.467308       1 nanny.go:111] 
W0914 13:05:35.467334       1 nanny.go:112] Got EOF from stdout
I0914 13:05:35.467353       1 nanny.go:108] dnsmasq[10]: started, version 2.76 cachesize 1000
I0914 13:05:35.467358       1 nanny.go:108] dnsmasq[10]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0914 13:05:35.467361       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0914 13:05:35.467363       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0914 13:05:35.467366       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0914 13:05:35.467434       1 nanny.go:108] dnsmasq[10]: reading /etc/resolv.conf
I0914 13:05:35.467448       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0914 13:05:35.467450       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0914 13:05:35.467452       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0914 13:05:35.467455       1 nanny.go:108] dnsmasq[10]: using nameserver 10.0.2.3#53
I0914 13:05:35.467534       1 nanny.go:108] dnsmasq[10]: read /etc/hosts - 7 addresses
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Cloud provider or hardware configuration**: minikube 0.21.1 on OS X, using VirtualBox.
- OS (e.g. from /etc/os-release): macOS Sierra 10.12.5
- Kernel (e.g. `uname -a`): Darwin Kernel Version 16.6.0
- Install tools: minikube 0.21.1
- Others:

**Comment by MrHohn** [comment]
This doesn't seems relevant to RBAC.

@vadimeisenbergibm Could you share your configuration for `kube-dns` pod? `dnsmsaq`'s healthcheck is served by the [`sidecar` container](https://github.com/kubernetes/kubernetes/blob/85025ef7dc693c116efc5fbf199a4f7119c69186/cluster/addons/dns/kubedns-controller.yaml.base#L146-L169). And was kubedns container also restarting?

**Comment by vadimeisenbergibm** [comment]
@MrHohn I see now that `kube-dns` fails as well. The problem is similar to this one https://github.com/kubernetes/kubernetes/issues/50799.

`kube-dns` has `serviceAccountName` set to default due to the fact that it is not specified in the `kube-dns`' deployment of minikube - https://github.com/kubernetes/minikube/blob/0e6e930a7d5b1c401eaf46dce41abf8be941e47c/deploy/addons/kube-dns/kube-dns-controller.yaml.

Should I open an issue against kubectl/minikube for that?

**Comment by vadimeisenbergibm** [comment]
Verified that the problem disappears after:

1. `kube-dns` service account is created by applying https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kubedns-sa.yaml

2. `kube-dns` is redeployed with https://github.com/kubernetes/minikube/blob/0e6e930a7d5b1c401eaf46dce41abf8be941e47c/deploy/addons/kube-dns/kube-dns-controller.yaml plus line `serviceAccountName: kube-dns` added as described in #50799

**Comment by MrHohn** [comment]
> Should I open an issue against kubectl/minikube for that?

@vadimeisenbergibm Glad that you found the cause. Yes please, kubernetes/minikube seems to be a better place for this issue, thanks.

**Comment by MrHohn** [comment]
BTW I sent https://github.com/kubernetes/minikube/pull/1970.

**Comment by vadimeisenbergibm** [comment]
@MrHohn Great, thanks, closing this issue.
