### ISSUE TITLE
[e2e test] pull-kubernetes-e2e-gce-bazel  failure

### ISSUE THREAD

**Issue by guangxuli** [kubernetes/kubernetes#52492]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
pull-kubernetes-e2e-gce-bazel failed in PR https://github.com/kubernetes/kubernetes/pull/51889 for many times. But seems not relevant to this PR. A couple of PR tests also generates the failure.

ref https://github.com/kubernetes/kubernetes/pull/52479, https://github.com/kubernetes/kubernetes/pull/52406, https://github.com/kubernetes/kubernetes/pull/51889, etc.

**log:(not list all)**

error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/go/src/k8s.io/kubernetes/_artifacts --disable-log-dump=true: exit status 1

**What you expected to happen**:
test pass
**How to reproduce it (as minimally and precisely as possible)**:
just trigger the job normally.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aleksandra-malinowska** [comment]
Closing as this is a duplicate of #52433

**Comment by guangxuli** [comment]
Of course.

**Comment by guangxuli** [comment]
@aleksandra-malinowska Failure seems still exists. Shall we have fix this issue?
