### ISSUE TITLE
Authorization webhook is self-hosting-hostile

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#52511]
https://kubernetes.io/docs/admin/authorization/webhook/#configuration-file-format

Problems:
1. I need to change an input file to turn on or off the webhook, requiring an apiserver restart. (dynamic configuration would be better)
2. The destination should be phrased in terms of a Kubernetes service, both to be consistent with other similar things (aggregator, admission control webhook), and because just putting in a predicted cluster-provided DNS name won't work in all environments.

I propose that either the auth webhook be removed in favor of https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks once the latter graduates from alpha, or that the auth webhook be fixed to behave consistently.

**Comment by davidopp** [comment]
+1

I would imagine the most common way to implement a webhook authorizer will be as a pod running in the cluster. The configuration mechanism for the webhook authorizer should enable that use case.

Alternatively, removing it and telling people to use admission controller webhook is also reasonable (assuming it solves this problem, which I take from point 2 that it does), but then we need to make the admission controller webhook receive all requests including reads, which IIUC it does not today.

/cc @ericchiang 
/cc @kubernetes/sig-auth-misc for visibility (I assume it would be implemented by SIG api machinery)

**Comment by liggitt** [comment]
> removing it and telling people to use admission controller webhook is also reasonable (assuming it solves this problem, which I take from point 2 that it does)

The interfaces and uses are different. The authorizer is consulted for more things than admission, including speculative "can user u perform verb v on resource r" queries.

**Comment by filmil** [comment]
+1 as one of the people who is looking into running an authorizer as a pod.

**Comment by ericchiang** [comment]
Yeah this would be great.

Today we've got webhooks for token authentication, authorization, and audit events.

https://kubernetes.io/docs/admin/authorization/webhook/
https://kubernetes.io/docs/admin/authentication/#webhook-token-authentication
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#webhook-backend

Do we see any of these as less of a candidate for dynamic configuration?

> I propose that either the auth webhook be removedI propose that either the auth webhook be removed in favor of...

I think there are still use cases for API server flags for webhooks. e.g. for "hosted" solutions where you can interact with the Kubernetes API, but your provider doesn't want you to be able to modify the control plane too much or remove auth integrations.

**Comment by lavalamp** [comment]
> The interfaces and uses are different. The authorizer is consulted for more things than admission, including speculative "can user u perform verb v on resource r" queries.

The thing they do is super similar, and the admission control webhook is still alpha and easy to change.

**Comment by lavalamp** [comment]
> I think there are still use cases for API server flags for webhooks. e.g. for "hosted" solutions where you can interact with the Kubernetes API, but your provider doesn't want you to be able to modify the control plane too much or remove auth integrations.

Hosts can manage this with their own admission control plugin + RBAC, I think.

**Comment by tallclair** [comment]
Admission is an "AND", but authorization is an "OR". If the authorization webhook was moved to an admission plugin, then any user it authorized would also need to be authorized by a built-in authorization method.

/cc @cjcullen

**Comment by deads2k** [comment]
> I propose that either the auth webhook be removed in favor of https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks once the latter graduates from alpha, or that the auth webhook be fixed to behave consistently.

Authorization and admission are two different operations, for two different purposes, at two different points in the handling chain.  Authorization is a global filter on the server (absolutely everything passes through it) and it doesn't inspect the body, making ideal for handling opaque requests. Admission inspects the body and may or may not be associated with a particular request.  One is not a reasonable substitute for the other.

Authorization webhooks can already use a service DNS name just like aggregation  and admission. The only case I can think of where it may fail is the odd the GKE networking set up that doesn't allow DNS resolution and routing to the service network.  I don't think that its a good idea to make a hash of a well established integration for an odd one-off use case.  Maybe you could set up a proxy for yourself?

In terms of self-hosting, I think kubeadm would be able to set up a authz webhook config without much trouble if they really needed to. @luxas

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests 

+1 for dynamic reconfig. On top of this, implementing ComponentConfig (with dynamic reloads) would be great.

We really should get rid of all places where we rely on config files on disk. kubeadm supports Webhook authz today, but forces you to put your config file in a specific place. This works with both Static Pod hosted and self-hosted control plane.

Reloads however, will basically kill your self-hosted API server :(
(This will be fixed with better DaemonSet update strategies, but anyway)

**Comment by mattmoyer** [comment]
I'm +1 on this if we can make it safe. I brought this up at a SIG-Auth meeting a while back (2017-07-26) and have been thinking about it since. Some things that came up then:
 1. Hosted scenarios where you might not want "cluster admin" to actually have full control to override authentication/authorization/audit for the cluster.
 2. Potential for a privilege escalation footgun if a non cluster admin is able to edit/create the dynamic configuration resource.

These feel like things we could tackle. (1) might be solved by putting the new resource into a "dynamic configuration" API group that's not enabled by default. (2) seems solvable with RBAC (though it still adds surface area for potential misconfiguration).

**Comment by lavalamp** [comment]
@tallclair's point (union vs intersection) seems like the only valid reason above for maintaining both. So, OK, we need both.

The code paths and APIs can still significantly converge: the API specifying how apiserver should make the call should be the same for both mechanisms. The code that actually does the dialing can be the same.

**Comment by ericchiang** [comment]
I need to work on this authorizer during 1.9 to add support for the new rules review API added in 1.8, so webhook authorizers can be queried for what actions a user can perform. Maybe that'd be a good opportunity to start adding exploring this support?

https://github.com/kubernetes/features/issues/380

There's also a proposal to let authorizers return an "unequivocal deny" https://github.com/kubernetes/kubernetes/issues/51862. That would get around this union issue.

**Comment by deads2k** [comment]
> Maybe that'd be a good opportunity to start adding exploring this support?

I think we should agree on what we want to build here.  I'm not convinced that we should change the webhook config file format away from a generic kubeconfig file format that works using normal cluster dns and normal service network routing and instead using something that won't work for "normal" generic apiservers.

Even having the power to lookup individual services, resolve them to endpoints, choose an endpoint, and set up a custom dialer to move through an ssh tunnel, isn't a thing that any apiserver besides the kube-apiserver would ever want to do and even the kube-apiserver should explore other options (see https://github.com/kubernetes/kubernetes/issues/49402#issuecomment-330682787).

The current code makes it easy for the vast majority of apiservers, the one special one we know about can come in via the client interface we provide for the webhook if they want something different and fancy.

**Comment by lavalamp** [comment]
Are we talking about authn, authz, or both? It is not obvious to me that authn should be configurable dynamically. authz makes more sense.

I think traffic not going to stuff running on cluster nodes in all environments is a bug that should probably be fixed, although it would be super helpful to see the motivating use case because it's not obvious to me that it's good to let the auth stack be modified in this way.

TL;DR: use case / user journey / problem statement, please.

**Comment by filmil** [comment]
> Authorization webhooks can already use a service DNS name just like aggregation and admission. The 
> only case I can think of where it may fail is the odd the GKE networking set up that doesn't allow DNS
> resolution and routing to the service network.

Hm, I tested this claim on a GKE deployment and on [k8s-on-GCE][1] deployment.  In both cases, the k8s apiserver does not have access to service DNS names.  

- Is your expectation that it would have such access? In that case are GKE and the k8s sample deployments exceptions?
- What does the deployment in which this *is* possible look like?

[1]: https://kubernetes.io/docs/getting-started-guides/gce/

**Comment by lavalamp** [comment]
I think there is one concrete problem that everyone can agree on:

* authz webhook doesn't respect the networking rules. Given the input mechanism, it ought to:
  * parse the DNS name
  * if it's a k8s service, use the service resolver to find an endpoint
  * use the dialer to dial the endpoint

This would at least make it possible to dial out to nodes in all possible cluster configurations and resolve the layering violation (can't depend on DNS in nucleus code).

**Comment by deads2k** [comment]
> authz webhook doesn't respect the networking rules. Given the input mechanism, it ought to:
> parse the DNS name
> if it's a k8s service, use the service resolver to find an endpoint
> use the dialer to dial the endpoint

I don't agree that's a thing that should be done in the generic webhook mechanism.  That webhook was built to allow a client to be plugged in, so if `kube-apiserver` (and only that server) wants to do build a custom client and wire it in, that could be done.  But it must not leak in the genericapiserver.

**Comment by davidopp** [comment]
@deads2k I think I understand what you're suggesting we not do, but it's not clear to me what you are suggesting we *sould* do.
 
IIUC the goal here is that you can specify a service name  to the API server authz webhook config argument, and the API server will use that endpoint. And that this should work when you don't have a DNS server up.

We all agree the API server has the necessary information to map the service name to the authz webhook endpoint.

(And I believe that once we have the endpoint, "use the dialer to dial the endpoint" should "just work" and thus isn't really part of this discussion.)

What is the right way to do that mapping?

Is there any reason we shouldn't just do it the same way as the admission controller webhook mechanism, which IIUC already meets the requirements described above?

**Comment by filmil** [comment]
Hi all. I looked at the authorizer webhook code.  It is built mostly on top of `generic.Webhook`, which uses a constant client to call out to the webhook endpoints.  Dynamic resolution will probably need to redo resolution if the address endpoint changes.

In light of that understanding, my reading of the advice from @deads2k  from the previous comments is that `generic.Webhook`code should remain unchanged, but that it would be OK to build custom kube-apiserver logic on top of it. @deads2k, do I see it correctly?

**Comment by deads2k** [comment]
> We all agree the API server has the necessary information to map the service name to the authz webhook endpoint.

A genericapiserver does **not** have the necessary information .  The library is generic, not special just for the kube-apiserver (which does have the information to make a dialer).



> @deads2k I think I understand what you're suggesting we not do, but it's not clear to me what you are suggesting we sould do.

My objection is to the assertion: "authz webhook doesn't respect the networking rules".  That isn't the case.  It uses DNS like normal and routes it's traffic like any other normal app.   This works for every genericapiservers and nearly every installation of `kube-apiserver`.  `kube-apiserver` on GKE wants to do something that isn't following the networking rules.  If the `kube-apiserver` on GKE wants to set up a parallel parsing technique to build a dialer, more power to them, but that code should not live the genericapiserver (with the webhoook implementation).

**Comment by deads2k** [comment]
> In light of that understanding, my reading of the advice from @deads2k from the previous comments is that generic.Webhookcode should remain unchanged, but that it would be OK to build custom kube-apiserver logic on top of it. @deads2k, do I see it correctly?

Exactly.  Code in k8s.io/apiserver (the genericapiserver) shouldn't contain a snowflake for `kube-apiserver` running on GKE. 


I also still agree with @liggitt here https://github.com/kubernetes/kubernetes/issues/49402#issuecomment-330682787, about trying to push this responsibility out to a VPN.

**Comment by davidopp** [comment]
I don't understand the connection to GKE? My understanding is that the same problem exists in regular upstream code deployed with kube-up.sh.

**Comment by deads2k** [comment]
> I don't understand the connection to GKE? My understanding is that the same problem exists in completely vanilla upstream code deployed with kube-up.sh.

No.  This is only a problem when you're trying to run a `kube-apiserver` without DNS access to the name you're resolving and without IP routing access to the IP you're routing to.  The only place I know that happens today when running on GKE since they're using a one-off SSH tunneler that was hacked into `kube-apiserver`.

**Comment by davidopp** [comment]
> without DNS access to the name you're resolving

I thought the reason for this wasn't GKE, but because of an architectural feeling that we shouldn't rely on DNS being up for API server to function?

**Comment by deads2k** [comment]
> I thought the reason for this wasn't GKE, but because of an architectural feeling that we shouldn't rely on DNS being up for API server to function?

I don't share that architectural feeling.  DNS is normal way to lookup a DNS name.  Of all the apiservers that currently exist and will exist, **only** the kube-apiserver even has the power to resolve a service name (the others can't do the lookup).  And in GKE, when someone does decide to bypass normal resolution, the kube-apiserver developer ends up having to re-invent kube-dns and kube-proxy (or any drop-in replacement thereof).  That makes it impossible to swap our the networking routing layers like you can for any other deployment mechanism.

We should not follow the GKE, ssh-tunnel, full read of all services and endpoints required path for generic apiservers.  Generic apiservers should properly participate with normal integration into the cluster.  The webhook has a spot to set a special client.  If someone in the GKE path really needs that, that is the level to integrate it.

**Comment by tamalsaha** [comment]
I create Kubernetes clusters using Kubeadm which sets the kube apiservers dns policy to `ClusterFirst`. Given it uses host network, it should set dns policy to `ClusterFirstWithHostNet`. Is it safe/recommended for Kube api server to depend on kube-dns for resolving self hosted webhook serer's name?

cc: @luxas

**Comment by deads2k** [comment]
> Is it safe/recommended for Kube api server to depend on kube-dns for resolving self hosted webhook server's address?

The information has to originate from somewhere and the information originates from the API server.  Since multiple authentication and authorization plugins are possible, relying on kube-dns to pull that information and expose it via a standard mechanism seems very fair. The "alternative" relies on using that same cyclical information, but consumes it via a specific, non-standard mechanism.

**Comment by liggitt** [comment]
routing of authorization webhook network connectivity is included in https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md#kubernetes-api-server-outbound-requests

/close
