### ISSUE TITLE
Pod is Running but IP address is not assigned

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#52527]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

After the boot, kubelet created 1 pod just fine, but few seconds later, every other pod was created without network IP address.  Pod statuses were all Running, but IP address were missing. We use kubelet from hyperkube v1.7.5 image, and flannel CNI plugin.

There are several kubelet logs which indicate sandbox failure:

```
remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to start sandbox container for pod "...": operation timeout: context deadline exceeded
```

```
pod_workers.go:182] Error syncing pod d0dba632-98f7-11e7-a057-fa163e134835 ("...(d0dba632-98f7-11e7-a057-fa163e134835)"), skipping: failed to "CreatePodSandbox" for "...(d0dba632-98f7-11e7-a057-fa163e134835)" with CreatePodSandboxError: "CreatePodSandbox for pod "...(d0dba632-98f7-11e7-a057-fa163e134835)" failed: rpc error: code = 2 desc = failed to start sandbox container for pod "...": operation timeout: context deadline exceeded"
```

After we restarted kubelet, everything went fine.

**What you expected to happen**:

kubelet creates Pod, and if it is running, it should have IP address assigned.

**How to reproduce it (as minimally and precisely as possible)**:

The occurrence seems relatively rare.  This is the first case we confirmed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by genexp** [comment]
We're having this problem too.  Its very strange.  Specifically, our kube-dns/kubedns containers are showing up with 1 network adapter.  We use weave.

**Comment by bogdando** [comment]
I have very similar problem with openshift origin v3.6/v3.7 and flannel v0.7.1 w/o cri-o, using host-gw mode. Some configuration snippets JFYI https://pastebin.com/R7sgPcQv .

**Comment by kiennguyen294** [comment]
I have semilar issue with kube version 1.7.4.
When i create pod, pod is state running but not IP, but after restarted kubelet service, everything went fine.
Help me!
