### ISSUE TITLE
Should be able to set cluster-name for cloud controller manager

### ISSUE THREAD

**Issue by karataliu** [kubernetes/kubernetes#52522]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`cluster-name` is used by servicecontroller and routecontroller, for controller-manager, we have an option to set it, but for cloud-controller-manager, it will always be of default value 'kubernetes'.

Here are some examples where it was in use:

aws:
https://github.com/kubernetes/kubernetes/blob/6b39b017b4096028396719b062bf56c00ca8d7f3/pkg/cloudprovider/providers/aws/aws_routes.go#L69

azure:
https://github.com/kubernetes/kubernetes/blob/a5f766063ddb668f7a8dc924a20fe8e4bb441a37/pkg/cloudprovider/providers/azure/azure_util.go#L186

gce:
https://github.com/kubernetes/kubernetes/blob/80ea31fcbf1a416a7d380582a7139f4132e3fece/pkg/cloudprovider/providers/gce/gce_routes.go#L43

openstack
https://github.com/kubernetes/kubernetes/blob/eb86cc5e87c077fec088bc6061e4774344e5f5d9/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L904

**What you expected to happen**:
Having an option to set the value.

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by dims** [comment]
oops looks like a PR ready already :)
