### ISSUE TITLE
Kubernetes events will disappear after one hour

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#52521]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
If the deploy failed, then I can check pod events to see what is wrong. But the events will disappear after one hour, why do we have such design?

/sig apps

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
@gyliu513 you can configure the ttl of events as you wish by setting the flag `--event-ttl duration                                      Amount of time to retain events. (default 1h0m0s)` of kube-apiserver.

**Comment by gyliu513** [comment]
Thanks @xiangpengzhao do you know why default to 1hr, it is a bit short, I think that an ideal value should be 1day or even 1week so that the end user would have enough time to retrieve events as they want.

**Comment by xiangpengzhao** [comment]
@gyliu513 I have no idea... :(

**Comment by andyxning** [comment]
/unassign kind/bug

@gyliu513  @xiangpengzhao This is mainly for easing the burden on ETCD. Ref #4432 and #47532 .

**Comment by timothysc** [comment]
This is what eventer - https://github.com/kubernetes/heapster/tree/master/events  

and eventrouter - https://github.com/heptio/eventrouter are for. 

This issue goes back 2+ years and there are multiple ways to handle it.

**Comment by Umair841** [comment]
is there any way to add a pod based on events coming from another pod ??

**Comment by amarkevich** [comment]
@andyxning both mentioned issues are closed. any chance to have extended event lifetime by default?
