### ISSUE TITLE
IBM Cloud private 

### ISSUE THREAD

**Issue by zoumanakeita** [kubernetes/kubernetes#52534]
Hello Everyone,

I need your help for my cloud private install.

I've got the following errors after the installation of my private cloud.

***After the installation with my ubuntu terminal.
<img width="733" alt="errorserveraccess" src="https://user-images.githubusercontent.com/24225491/30481148-6cceda3a-9a1d-11e7-839
<img width="733" alt="errorserveraccess" src="https://user-images.githubusercontent.com/24225491/30481166-81b7d5be-9a1d-11e7-8acf-d5ef3f42cd0b.PNG">
<img width="744" alt="errorserveraccess2" src="https://user-images.githubusercontent.com/24225491/30481167-81b8cde8-9a1d-11e7-9c69-079f06d74ab3.PNG">

a-b22dca4835cd.PNG">

*** When I try to access some tabs on my dashboard.
<img width="473" alt="dashboard-error" src="https://user-images.githubusercontent.com/24225491/30481174-87d218c4-9a1d-11e7-8994-c18b3f39490f.PNG">

Thank you !

**Comment by zoumanakeita** [comment]
@kubernetes/master-<Cluster Lifecycle>
 area/cloudprovider

**Comment by k82cn** [comment]
@zoumanakeita , this's pure k8s community, I think you need to send email to cfchelp@ca.ibm.com to ask help :).
