### ISSUE TITLE
Addon resizer v2.0 keeps restarting pod every 1 minute in e2e tests

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#52535]
In ~30% of cluster size autoscaling test suite runs, Heapster pod starts restarting every 1-2 minutes for ~15 minutes. This causes flakes for two reasons: 
1. nodes don't become schedulable due to rescheduler repeatedly tainting nodes with CriticalAddonsOnly (which doesn't help as pod is deleted and created again, sometimes before the taint is lifted),
2. in HPA/CA integration test, HPA is unable to fetch metrics due to restarting Heapster.

Based on logs from addon resizer, it's being restarted every 1 minute and immediately sends request to increase resources. This doesn't seem to be due to changing requirements.

cc @piosz @mwielgus @x13n

**Comment by x13n** [comment]
I would like to switch to v2.0 again in https://github.com/kubernetes/kubernetes/pull/52152, which is to solve https://github.com/kubernetes/kubernetes/issues/50599. When I was testing that change, Heapster wasn't restarting repeatedly. How can I reproduce this?

**Comment by aleksandra-malinowska** [comment]
@x13n I'd start with manually deleting the node on which Heapster pod is scheduled, then maybe adding load to cluster and enabling autoscaling. This was observed in cluster size autoscaling tests, including [this one](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/autoscaling_timer.go), so running them could work, but it takes a long time.

**Comment by x13n** [comment]
Actually, this is a duplicate of https://github.com/kubernetes/kubernetes/issues/50599
/close
