### ISSUE TITLE
[e2e and upgrade failure] several GCE and GKE tests failing with: gce boskos failed to acquire project

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52554]
```
W0915 16:00:00.634] 2017/09/15 16:00:00 main.go:270: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: Post http://boskos/acquire?type=gce-project&state=free&dest=busy&owner=ci-kubernetes-e2e-gce-slow: dial tcp 10.63.250.132:80: i/o timeout
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-slow/8999

https://k8s-testgrid.appspot.com/release-master-blocking#gke
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce
https://k8s-testgrid.appspot.com/release-master-blocking#gce-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gke-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke-slow
https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial
etc.

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/test-infra-admins 
cc @kubernetes/test-infra-maintainers

**Comment by ericchiang** [comment]
Upgrade tests as well

https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-parallel
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster

**Comment by ericchiang** [comment]
The rest of the upgrade tests have failed with

```
W0915 15:27:07.270] 2017/09/15 15:27:07 main.go:270: Something went wrong: failed to prepare test environment: boskos does not have a free gke-project at the moment
```

e.g. https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/1304

**Comment by krzyzacy** [comment]
Current status: 
ref https://github.com/kubernetes/test-infra/issues/4571, boskos replicaset does not handle pv mount upon reshedule properly, I'll change that to a statefulset.
Deeper issue: prow encountered node pressure, since it's still on 1.6.9, node will kick out running tests rather than gc finished/errored pods, and the test can never finish running, they are keeping get rescheduled.

**Comment by foxish** [comment]
cc @crimsonfaith91, this looks related to the GKE test failures.

**Comment by crimsonfaith91** [comment]
@foxish yes, opening a bug report for it now.

**Comment by krzyzacy** [comment]
@foxish https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntustable1-k8sdev-ingress/594/ gke has a different issue

**Comment by krzyzacy** [comment]
/close

Should be stable now (except for the above gke issue)

**Comment by krousey** [comment]
@krzyzacy Is there an issue for that GKE issue?
