### ISSUE TITLE
Deprecate --enable-custom-metrics in kubelet?

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#52564]
The original PR that introduced the feature: #19944.

Before 1.6, if this flag was set, kubelet would label the docker containers accordingly so that cadvisor could report the custom metrics. The stats are included in the of kubelet's summary API (`/stats/summary`). 
Since 1.6+, kubelet switched to using the CRI implementation, and this feature was dropped silently. 

IIUC, the feature was in the Alpha phase, and HPA has already moved away (in 1.6) from consuming the custom metrics through kubelet. Can we simply deprecate the flag (since it's not actually used anywhere) or are there any concerns?

/cc @mwielgus @dchen1107

**Comment by DirectXMan12** [comment]
yep, that's fine.  It's long overdue for removal.

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-instrumentation-feature-requests

**Comment by dims** [comment]
@yujuhong @DirectXMan12 - is there a point in deprecation when the code was already dropped and the flag has no user/effect whatsoever? are we trying to protect people who have `--enable-custom-metrics` in their scripts from breaking?

**Comment by yujuhong** [comment]
@dims Yes.

**Comment by dims** [comment]
@yujuhong Looks like the PR is just ripping it out - https://github.com/kubernetes/kubernetes/pull/52629

**Comment by DirectXMan12** [comment]
@dims @yujuhong it's been unsupported for a while now, and it never left alpha.  Since it was alpha, I think we're fine just ripping it out.

**Comment by mdshuai** [comment]
same https://github.com/kubernetes/kubernetes/issues/54161 ; we can close this.

**Comment by DirectXMan12** [comment]
/close

as a duplicate
