### ISSUE TITLE
OpenStack cloud provider should allow exposing only the public IP

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/kubernetes#52566]
When creating a service passing the annotation `service.beta.kubernetes.io/openstack-internal-load-balancer: "false"`, two IPs are created in the service, a private and a public:
```
LoadBalancer Ingress:	10.11.4.90, 150.165.x.y
```

Having a private IP is not a desired scenario for service discovery in federated global environments.   If we have, for example, a cluster in GKE and join a local OpenStack cluster, this private IP is written in the DNS zone but the GKE cluster won't be able to access it. 

We could add an annotation to say we don't want the private IP to be registered in service's LoadBalancer Ingress field, like:

`loadbalancer.openstack.org/register-internal-ip=false` or
`service.beta.kubernetes.io/register-internal-ip=false` 

And when it's false, only the public IP would be written in the service, therefore in the DNS zone

/kind feature

**Comment by FengyunPan** [comment]
'loadbalancer.openstack.org/register-internal-ip=false' sounds better.

**Comment by anguslees** [comment]
I don't like adding annotations just to make things work.  I counter-propose just not publishing the private IP whenever there is also a floating-ip (without a configuration option to control this behaviour).
