### ISSUE TITLE
[upgrade tests] some upgrade tests are missing log artifacts

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52578]
Dup'ish of https://github.com/kubernetes/test-infra/issues/4323

We're seeing a lot of upgrade tests missing logs for the nodes and control plane components.

The following suites have logs:
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-parallel
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-new

The following suites appear to be missing logs:
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-master
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-master
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-parallel
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster

cc @kubernetes/test-infra-admins
cc @kubernetes/kubernetes-release-managers

**Comment by krzyzacy** [comment]
```
I0915 19:40:25.868] Detecting project
I0915 19:40:25.869] Project: k8s-jkns-e2e-gce-slow-1-2
I0915 19:40:25.869] Zone: us-central1-f
I0915 19:40:25.870] Dumping master logs to /workspace/_artifacts
I0915 19:40:26.823] Master not detected. Is the cluster up?
I0915 19:40:26.823] Dumping node logs to /workspace/_artifacts
I0915 19:40:27.559] Nodes not detected. Is the cluster up?
```

Something turned down the cluster? Or after upgrade the node name not matching `--filter` anymore?
(We should print out the gcloud calls from log_dump.sh)
cc @shyamjvs rings any bells to you?

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/567 has all the logs - I'll wait for a few more runs and check back.

**Comment by krzyzacy** [comment]
/assign

I think that's due to we redeployed project pool and janitor probably wiped off some gcp resources. New runs should be fine, I'll keep an eye here.

**Comment by shyamjvs** [comment]
I fixed this problem for master branch gke jobs. Backporting those fixes (https://github.com/kubernetes/kubernetes/pull/52360 & https://github.com/kubernetes/kubernetes/pull/52420) to whichever release these jobs are running against should fix it.

**Comment by shyamjvs** [comment]
@krzyzacy / @ericchiang Could one of you create a PR with those commits?

**Comment by krzyzacy** [comment]
doing it

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/pull/52668

**Comment by dims** [comment]
@krzyzacy @ericchiang Quick question from release team, Are we done with what's needed for 1.8 for this issue?

**Comment by apelisse** [comment]
I think this is fixed, can you confirm @krzyzacy

**Comment by krzyzacy** [comment]
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/2064/artifacts/ has logs, for above test you need to wait for a fresher run :-)

**Comment by krzyzacy** [comment]
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/468/ from 23p last night also have logs now, while build 467 does not have - @ericchiang I think we can close this.

/close
