### ISSUE TITLE
Add support for verifying attached but desired to be detached PVCs 

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#52573]
/kind Bug

A Volume can escape attach detach contoller for various reasons. i.e - even though volume is attached to a node, volume may not be present in actual state of world of A/D Controller.

For example:

1. User started a Pod `P` with PVC `VC` at time t1.
2. For some reason - `VC` was stuck in `waitForAttach` call on controller for 1 hour.
3. In meanwhile user gives up and deletes the Pod.
4. Attach eventually succeeds but `WaitForAttach`  already gave up after waiting for 30 minutes and hence this volume never gets added to Actual State of World.
 

Now this PVC can not be used again without manual intervention from an admin. There are in fact several cases that can cause this problem.

I am thinking of doing opposite of mechanism proposed in https://github.com/kubernetes/kubernetes/pull/34859 issue. I am thinking that, we can periodically poll all PVCs and verify if their volumes are attached to nodes, then we can go ahead and add the volume in Actual State of World of A/D Controller. We will also update `node.Status.AttachedVolume` with same information.

This will make sure, depending on whether volume indeed needs to be present in node (based on state in desired state of world), it could be detached properly.

cc @kubernetes/sig-storage-api-reviews

**Comment by gnufied** [comment]
The other cases, I can think of are:

1. controller crash before actual state could be written.
2. admin manually detaching a "stuck" volume while attach is still in progress.

**Comment by gnufied** [comment]
Spoke with @jingxu97 briefly offline and she pointed me to https://github.com/kubernetes/kubernetes/issues/32727 issue which also proposes a similar approach. We need to think through little bit and consider pros and cons and come up with a solution.

**Comment by eparis** [comment]
Might I suggest labeling volumes in the cloud provider. Any volume with the 'kubernetes-managed-attach=true' label which is found attached to a node that kube doesn't believe it should be attached to, should be detached by kubernetes.

**Comment by gnufied** [comment]
Tuesday me & @jingxu97 had a conversation offline about fixing this "category" of problems. We came up with two ideas:

1. *Make Attach errors carry additional context* : Currently when a Attach fails we are simply returning `false` and `error` from volume plugin code. What I was thinking is, we can extend this `error` to carry some additional meaning. We can create a subtype of `error` which is returned if volume plugin detects a dangling volume attached elsewhere. Attach detach controller can look for that special error and take steps to correct it.  I already wrote some code and I am testing it -https://github.com/gnufied/kubernetes/commit/7aea43014ff6d6bf4a74479e4f007179928630ae

Pros:
* It seems very minimal and each plugin can implement this error type if it wants to implement this behaviour. In a nutshell it can be gradually implemented for all volume types.
* No polling and hence does not SPAM cloudprovider APIs.

Cons:
* This will only detach dangling volumes when someone tries to reuse the same volume. It will not solve problem of dangling volumes until user tries to use it. This could mean that - it does not solve problem of deleting dangling volumes (because delete of such PVCs fail). 
* @jsafrane raised a good point that, we should not "force detach" volumes from running nodes and volume is reported as mounted. But this applies to all detach performed after 6 minutes - we need to review that code regardless of this change.

2. *Poll for all volumes in desired state of world* - The idea is we can poll for all volumes in desired state of world periodically and check with cloudprovider if they are attached somewhere. If they are attached, we can add the volumes to actual state of the world. This will cause dangling volumes to be detached if volume is not needed on given node. 

Pros:
* ...
Cons:
* Needs polling of Cloudprovider APIs and hence is bit costly.
* Suffers from same drawbacks as mentioned in approach#1. Such as - we do not perform detach of dangling volumes until user tries to use same volume elsewhere. 

Overall I think option#1 is a good idea and I am going to test the code and open a proper PR soonish. 

Also - to solve problem of deleting dangling PVCs I was thinking, if we can monitor for PVC delete events in attach/detach controller and add the PVC to actual state of world, if it is reported to be attached somewhere by cloudprovider. That will solve the problem of deleting dangling PVCs. cc @jingxu97

**Comment by justinsb** [comment]
From the AWS perspective, I would prefer option 2.  I think it fixes more problems and helps with debugging (and I think we'll likely surface more problems!)  Option 1 is good, but is fixing just one case.

For AWS we would get the state of all volumes, which is a single call as far as quota is concerned.  I suspect that most clouds actually have similar cost models - a high overhead for a call and then fetching 1 vs fetching 1000 is essentially the same cost.  I don't know of any cloud that "goes to the node" to get volume status.

In terms of implementation though, I think we just take the existing poll logic and poll all volumes.  If we are concerned about clouds with different models we could add a second interface or second call that is allowed to return "not implemented"...

**Comment by gnufied** [comment]
@justinsb what other problem you are thinking of? I will argue that both the approaches are exactly same when it comes to how they affect internals of attach detach mechanism.
