### ISSUE TITLE
[upgrade test failure] CronJob should adopt Jobs it owns that don't have ControllerRef yet

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52571]
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-parallel

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/567#k8sio-cronjob-should-adopt-jobs-it-owns-that-dont-have-controllerref-yet

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cronjob.go:327
wait for Job "adopt-1505507760" to be readopted
Expected success, but got an error:
    <*errors.errorString | 0xc4202b31c0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cronjob.go:322
```

/kind upgrade-test-failure

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/sig-apps-test-failures 

Assigning to the 1.8 milestone. Since we're late in the release cycle, we need to determine if this is a release blocker or not.

**Comment by enisoc** [comment]
This is not a blocker. The test should be skipped on 1.8+ clusters because the behavior is no longer desired after #47469.

/assign @crimsonfaith91

**Comment by crimsonfaith91** [comment]
I will add a skip to the test for 1.8+ clusters.

**Comment by apelisse** [comment]
That should be fixed now.
