### ISSUE TITLE
[Flexvolume] Consider adding json options to Unmount and Detach call-outs

### ISSUE THREAD

**Issue by jbw976** [kubernetes/kubernetes#52590]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

The Flexvolume `Unmount()` call-out provides only the mount dir to the flexvolume plugin driver as seen in
https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md#unmount
```
<driver executable> unmount <mount dir>
```

It would be useful if more context could be provided to the driver in the `Unmount()` call-out, similar to all the information that is provided in the json options to the `Mount()` call-out.

Of particular note would be:
```
kubernetes.io/pvOrVolumeName
kubernetes.io/pod.name
kubernetes.io/pod.namespace
kubernetes.io/pod.uid
```

The Rook Flexvolume plugin is currently parsing some of this information from the given mount dir, but that doesn't feel like it would be a stable or reliable longer term approach: https://github.com/rook/rook/pull/882

**Comment by VineetReynolds** [comment]
Is it possible to reopen this issue?

We have a similar usecase to Rook. We've written a custom Flexvolume driver, where we need access to the PV options during volume unmounting. We have a tiered storage solution where volumes are mounted on a local disk, but the volume is populated with data from a NAS solution (GlusterFS in our case, but could be NFS, Ceph or AWS S3). During unmounting, we need to backup the volume from local disk to NAS, and only then do we consider the volume to be successfully unmounted. So, knowing the actual directory alone, during unmounting is somewhat useless to perform a true unmount; more information is required, like the pod name, id, namespace etc. In our usecase, we need to back up subpath directories in volumes, so we rely on the subpath name being the same as the pod name (as a convention).

As a workaround to the options not being available, we capture the options during volume mounting, store them in pod-specific files in `/run`, and then unmount correctly. We in fact rely on logic similar to Rook, to parse the unmounted directory, to even get the pod id and volume names during unmounting. By providing the same options during unmounting, we wouldn't need to store these options.

This might be a flaky design, both from point of view of K8S and the flexvolume, given the requirement to rely on pod-specific data, so if this warrants a new topic to be opened, I'd be ok to start a new one.
