### ISSUE TITLE
Initializer support for updates

### ISSUE THREAD

**Issue by laverite** [kubernetes/kubernetes#52608]
How are updates to things like deployments to be handled within Initializers?  Currently I think you have to either delete and recreate a deployment, or write custom update code within the Initializer.  Is there another way to do this?
/kind feature

**Comment by liggitt** [comment]
Webhook admission is how you would inject admission checks for update/delete API calls. See https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks

**Comment by laverite** [comment]
@liggitt in my case i'm trying to mutate the incoming request (something like https://github.com/kelseyhightower/kubernetes-initializer-tutorial).  looks like the external webhook won't support that. is there another way for that use case?

**Comment by liggitt** [comment]
Adding support for mutation to external webhook admission is planned

**Comment by liggitt** [comment]
Alternately, you could simply write a controller that issues another update on the object in response to observed update events.
