### ISSUE TITLE
can i ping Docker Container from another machine using container ip

### ISSUE THREAD

**Issue by prateekarora151083** [kubernetes/kubernetes#5261]
I have installed kubernetes ( v0.6.2) on Ubuntu ( multi host) .

My Setup:
Master 10.23.48.79
Minion1 10.23.48.76
Minion2 10.23.48.77

I have created one container on "host": "10.23.48.76" with "podIP": "172.17.0.4" 

In my Use case i want my "host": 10.23.48.77 can communicate ( example : ping ) container ("podIP": "172.17.0.4" )  using container ip  ( means want to run command ping 172.17.0.4 on   "host": 10.23.48.77 ) that running on other "host": "10.23.48.76.

what is the way to achieve this scenario ?

Regards
Prateek

**Comment by ArtfulCoder** [comment]
Hi, you can create a service for your pod, (pod spec the container ), kubernetes will give a service ip that you can use to reach your container.
If you now access the container through the service ip, it will just work.

**Comment by prateekarora151083** [comment]
Thanks  but i think service cant solve my problem .
My  use case is : 

application is running on container ( "host": "10.23.48.76" with "podIP": "172.17.0.4")

and one "third party  service" is running on host 10.23.48.77

application want to perform some task on third party service .

before perform task some handshaking between application and third party  service happen. during handshaking third party  service ( running on host 10.23.48.77 )  try to connect with  container (  "podIP": "172.17.0.4") . i cant change the functionality of third party  service means  i cant configure " third party  service" to use  kubernetes service ip instead of container ip.

hope this time i give you clear picture of my use case.

**Comment by erictune** [comment]
Which Getting Started Guide are you using?

**Comment by prateekarora151083** [comment]
not any particular guide .
just search  about kubernetes  installation on internet . 
follow below link 
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides

**Comment by erictune** [comment]
are you following
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_multinodes_cluster.md
in particular?

**Comment by erictune** [comment]
Possibly you have not setup flannel correctly, or possibly that guide is
broken.
It is suspicious that you are using v0.6.2 but the guide says to use v0.12.0

**Comment by prateekarora151083** [comment]
No because when i installed kubernetes on ubuntu multi node  no such type of document is available . so just search on net and follow steps that already tried by someone.

**Comment by erictune** [comment]
I'm afraid we can't help much with debugging your setup then.

**Comment by thockin** [comment]
Please see docs/networking.md - the existence of a 172 IP suggests you have
not yet set up networking.

**Comment by prateekarora151083** [comment]
Thanks erictune , i will try to setup kubernetes with new document  that you mention

i need one clarification .
as per my current understanding using flannel containers on multiple node can talk to each other .

but can using flannel all nodes can also communicate with all containers on multiple node  (and vice-versa) ?

**Comment by erictune** [comment]
Take a look at docs/networking.md

**Comment by brendandburns** [comment]
Yes, nodes (e.g. the host VMs) should be able to talk to container IP
addresses over flannel.

**Comment by prateekarora151083** [comment]
Thanks
 i will try to setup kubernetes with flannel using https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_multinodes_cluster.md 
and try to achieve my use case .

**Comment by prateekarora151083** [comment]
Hi i am trying to do setup kubernetes  using following guide
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_multinodes_cluster.md
after configuration 

run this command 
/opt/bin/etcdctl  mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'
got following error
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

and also 
/opt/bin/kubectl get minions 
not display any list of minions

if you need i can copy all configuration files information

**Comment by brendandburns** [comment]
That error indicates etcd isn't running (or at least not on 127.0.0.1:4001)

what does ps -ef | grep etcd show?

**Comment by prateekarora151083** [comment]
ps -ef | grep etcd
root      6149     1  0 12:05 ?        00:00:00 /opt/bin/etcd -name infra1 -initial-advertise-peer-urls http://10.0.0.11:2380 -listen-peer-urls http://10.0.0.11:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster infra1=http://10.0.0.11:2380,infra2=http://10.0.0.31:2380,infra3=http://10.0.0.32:2380,infra4=http://10.0.0.34:2380,infra5=http://10.0.0.35:2380 -initial-cluster-state new
root      6156     1  0 12:05 ?        00:00:00 /opt/bin/kube-apiserver --address=0.0.0.0 --port=8080 --etcd_servers=http://127.0.0.1:4001 --logtostderr=true --portal_net=11.1.1.0/24

**Comment by brendandburns** [comment]
Ok, I _think_ it looks like etcd is listening on 10.0.0.11:2380 not
localhost:4001.

You'll need to configure both etcdctl and the kube-apiserver to talk to
http://10.0.0.11:2380 instead of http://127.0.0.1:4001

(or reconfigure etcd to listen on localhost)

--brendan

**Comment by prateekarora151083** [comment]
ok i will try 
but  i am using ./configure.sh present in kubernetes/cluster/ubuntu-cluster 
and it configure on http://10.0.0.11:2380

**Comment by prateekarora151083** [comment]
when i am trying with 10.0.0.11:2380 using below command 

/opt/bin/etcdctl --peers 10.0.0.11:2380  mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'

get error
Error:  cannot sync with the cluster using endpoints http://10.0.0.11:2380

**Comment by prateekarora151083** [comment]
Hi now my kubernetes setup is working
I just removed data dir infra1.etcd/ infra2.etcd/ infra3.etcd/ infra4.etcd/ infra5.etcd/ from all hosts and reconfigure all machines and its working
flannel interface also setup

i am facing one issue
i have five machine 10.0.0.11 10.0.0.31 10.0.0.32 10.0.0.34 10.0.0.35
for flannel i use this command 
/opt/bin/etcdctl mk /coreos.com/network/config '{"Network":"11.0.0.0/16"}'


so if i launch container on 10.0.0.32 machine then
from all machine ( docker or host) i am able to ping container ( exist in host 10.0.0.32 ) . but from container ( exist in host 10.0.0.32 ) i am only able to ping containers on all host and 10.0.0.32 host
but not able to ping 10.0.0.11 10.0.0.31 10.0.0.34 10.0.0.35 host.

**Comment by brendandburns** [comment]
Are you really specifying 11.0.0.0/16 for Flannel, or is that a typo?
 11.0.0.0 is in real IP, not private IP space, so you probably don't want
that.

If it is a typo and you instead actually specified 10.0.0.0/16 for Flannel,
then the problem is that flannel is overlapping with your main IP network.
You want to make sure that the CIDR for flannel, and your physical host
machines don't overlap.

--brendan

**Comment by prateekarora151083** [comment]
now i changes my hostmachine ips
10.10.0.11 ,10.10.0.31 , 10.10.0.32 , 10.10.0.34 ,10.10.0.35

for flannel
/opt/bin/etcdctl --peers 10.0.0.11:2380 mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'

then same error exist .

is my configuration right ?

**Comment by prateekarora151083** [comment]
sorry use this command
/opt/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'

**Comment by ArtfulCoder** [comment]
@prateekarora151083  
could you check the flanneld process on each host and check what etcd host and port it is talking to ?

**Comment by prateekarora151083** [comment]
result of ps -ef | grep flannelid
is
root     20525     1  0 09:42 ?        00:00:00 /opt/bin/flanneld

**Comment by ArtfulCoder** [comment]
I was trying to figure out what endpoint flanneld is hitting. What args is it running with ?

**Comment by prateekarora151083** [comment]
no arguments result show only 
root 20525 1 0 09:42 ? 00:00:00 /opt/bin/flanneld

**Comment by prateekarora151083** [comment]
Is it required to add   -ip-masq=true for flannel arguments.
I have Edited  /etc/default/flanneld
Added  FLANNEL_OPTS="-ip-masq=true"

then container ( exist in host 10.0.0.32 )  able to ping  10.0.0.11 10.0.0.31 10.0.0.34 10.0.0.35 host.

is above setting is correct or is there any other way to achieve my goal .

**Comment by thockin** [comment]
Sorry, Abhi is the right assignee.

**Comment by ArtfulCoder** [comment]
@prateekarora151083  I think you should have every flanneld process point to the same etcd cluster.
That is how the flanneld processes on the various machines co-ordinate with each other (via etcd).

You might want to check out  cat /proc/{flannel process id}/cmdline to see what the flanneld args are.
