### ISSUE TITLE
Kubectl gives the error "the server doesn't have a resource type "nodes""

### ISSUE THREAD

**Issue by prashantabkari** [kubernetes/kubernetes#52636]
**BUG REPORT**:

> /kind bug

**What happened**:
I re-installed the Kubernetes and performed kubeadm init and join from the worker too. But when i run kubectl get nodes it gives the following response

the server doesn't have a resource type "nodes"

What might be the problem here? Could not see anything in the /var/log/messages

**What you expected to happen**:
kubectl get nodes should return the list of worker nodes

**How to reproduce it (as minimally and precisely as possible)**:
Install kubeadm cluster by following the guide kubernetes.io/docs/setup/independent/install-kubeadm 
Unintstall kubeadm, kubectl, kubelet
Install again

**Anything else we need to know?**:
kubectl version gave the following info

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fversion'/><script>window.location.replace('/login?from=%2Fversion');</script></head><body style='background-color:white; color:white;'>

Authentication required

</body></html>

**Environment**:

- Cloud provider or hardware configuration**: 64 bit VM on Vbox
- OS (e.g. from /etc/os-release):CentOs 7
- Kernel (e.g. `uname -a`): Linux 192-168-1-101.tpgi.com.au 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by lichuqiang** [comment]
Seems there is something wrong with your kube-apiserver, you can take a look at the log of apiserver

**Comment by prashantabkari** [comment]
ran kubeadm reset and then init. But now get nodes seems to be giving the following error
"The connection to the server localhost:8080 was refused - did you specify the right host or port?"

KUBECONFIG is set but the admin.conf file is blank. So should the /etc/kubernetes/conf $HOME/.kube/config and $HOME/admin.conf be same? 

Also could not find the file log files. And all the containers are running.

**Comment by prashantabkari** [comment]
Ok. i got what the issue is. Not sure how admin.conf in $HOME is empty. But i copied /etc/kubernetes/conf to $HOME/admin.conf and it worked. 

Closing now.

**Comment by prashantabkari** [comment]
Hi guys - Just noticed this again. Was able to reproduce it. On performing multiple kubeadm reset and kubeadm init cycles. admin.conf unde $HOME has to be copied from /etc/kubernetes/admin.conf .
Not sure if this is documented anywhere.

**Comment by Vickey-Wu** [comment]
Hello, i get this error, too. 192-168-43-131 is master, 192-168-43-134 is node. os is ubuntu 16.04, k8s version is 1.11.0.
And i follow @prashantabkari's solution copy admin.conf to $HOME, I still got this error.
any help would be appreciated, thanks!
master error info
```
root@192-168-43-131:~# kubectl get nodes
error: the server doesn't have a resource type "nodes"
```
node info
```
root@192-168-43-134:~# kubeadm join 192.168.43.131:6443 --token uqqh3t.gib5xwqdpexpz7p0 --discovery-token-ca-cert-hash sha256:34e2617bf35c8fb49c6f28131b2bcc7f61236021026f2a3376534420d450f537
[preflight] running pre-flight checks
I0717 18:07:37.488803   22395 kernel_validator.go:81] Validating kernel version
I0717 18:07:37.489438   22395 kernel_validator.go:96] Validating kernel config
[discovery] Trying to connect to API Server "192.168.43.131:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.43.131:6443"
[discovery] Requesting info from "https://192.168.43.131:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.43.131:6443"
[discovery] Successfully established connection with API Server "192.168.43.131:6443"
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.11" ConfigMap in the kube-system namespace
[kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[preflight] Activating the kubelet service
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "192-168-43-134.master" as an annotation

This node has joined the cluster:
* Certificate signing request was sent to master and a response
  was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the master to see this node join the cluster.
```

**Comment by Vickey-Wu** [comment]
sorry, i misunderstood kubeadm init output, just run the following command as a regular user but root not, so i get this error when i use root, finally i run command with root and regular user then it work.
```
Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

**Comment by vagdevik** [comment]
In my case, I wanted to see the description of my pods. 

When I used `kubectl describe postgres-deployment-866647ff76-72kwf`, the error said **error: the server doesn't have a resource type "postgres-deployment-866647ff76-72kwf".**

I corrected it by adding pod, before the pod name, as follows:

`kubectl describe pod postgres-deployment-866647ff76-72kwf`
