### ISSUE TITLE
./hack/update-all.sh failed

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#52632]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug
/kind flake

**What happened**:

```
# ./hack/update-all.sh -a -v
.........
godep: Downloading dependency (if needed): k8s.io/utils/exec/testing
godep: Downloading dependency (if needed): vbom.ml/util/sortorder
godep: Error downloading some deps. Aborting restore and check.
!!! Error in /root/go/src/github.com/k8s.io/kubernetes/hack/godep-restore.sh:28
  Error in /root/go/src/github.com/k8s.io/kubernetes/hack/godep-restore.sh:28. 'GOPATH=${GOPATH}:${KUBE_ROOT}/staging godep restore "$@"' exited with status 1
Call stack:
  1: /root/go/src/github.com/k8s.io/kubernetes/hack/godep-restore.sh:28 main(...)
Exiting with status 1
!!! Error in ./hack/update-all.sh:60
  Error in ./hack/update-all.sh:60. '"${KUBE_ROOT}/hack/godep-restore.sh" ${V}' exited with status 1
Call stack:
  1: ./hack/update-all.sh:60 main(...)
Exiting with status 1
```

@sttts @smarterclayton 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
There are some discussion here https://groups.google.com/forum/#!msg/kubernetes-dev/KTFObcpKpb8/PtjmcSbTBwAJ , but still not clear how to workaround this, can anyone help? Thanks!

**Comment by sttts** [comment]
Which of the deps failed? `godep: Error downloading some deps. Aborting restore and check.`

**Comment by gyliu513** [comment]
The log does not show much, but only the above info.

After more checking, seems it is caused by that I do not have `hg` installed in my new dev env, after install hg via `apt install mercurial`, the `./hack/update-all.sh` works well. @sttts

**Comment by sttts** [comment]
@gyliu513 thanks for the update. Closing this.
