### ISSUE TITLE
resize admission plugin breaks dynamic provisioning

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#52658]
Currently the resize admission plugin - https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/persistentvolume/resize/admission.go checks for all kind of updates. 

This is problematic because this means that enabling the plugin blocks other kind of updates to PVC too. But PV controller in particular depends on ability to set `volumeName` after pvc creation for dynamic provisioning.

We need to make sure that, we are only checking for bound PVCs and only if user is trying to increase the PVC size.

/sig storage

cc @NickrenREN @saad-ali @childsb

**Comment by saad-ali** [comment]
Fix for this, PR #52659, is approved/LGTM'd and awaiting merge.
