### ISSUE TITLE
Map a resource to multiple signals in eviction manager

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#52661]
It is possible to have multiple signals that point to the same type of
resource, e.g., both SignalNodeFsAvailable and
SignalAllocatableNodeFsAvailable refer to the same resource NodeFs.
Change the map from map[v1.ResourceName]evictionapi.Signal to
map[v1.ResourceName][]evictionapi.Signal

**Comment by spiffxp** [comment]
/kind cleanup
/priority important/soon
taking a guess at labels to satisfy the milestone munger

**Comment by saad-ali** [comment]
Looks like the PR for this is just awaiting merge https://github.com/kubernetes/kubernetes/pull/47080
