### ISSUE TITLE
compilation issues with bazel 0.6.0

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#52677]
Kubernetes 1.8 and master currently builds with bazel 0.5.4 and `rules_go` at 82483596ec203eb9c1849937636f4cbed83733eb.

Upgrading `rules_go` to a newer version causes bazel 0.5.4 to crash (https://github.com/bazelbuild/rules_go/issues/783).

However, using bazel 0.6.0rc1 with the currently-pinned version of `rules_go` results in a build failure:
```
/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
```

This seems to be due to a flag default change in bazel 0.6.0. From the release notes:
> `--incompatible_comprehension_variables_do_not_leak` defaults to "true." Iteration variable becomes inaccessible after a list/dict comprehension.

There's no easy safe way to handle this upgrade. Probably the best way is to explicitly set `--incompatible_comprehension_variables_do_not_leak` to false in our `.bazelrc`, then as soon as bazel 0.6.0 is released, update `rules_go` and remove the default.

cc @BenTheElder @spxtr 

/kind bug
/area build-release

**Comment by mml** [comment]
@ixdy this does not appear to fix everything.  E.g.,

```
% /usr/bin/bazel query 'kind(test, rdeps(//..., set(test/e2e/BUILD test/e2e/e2e.go)))'
ERROR: /usr/local/google/home/mml/.cache/bazel/_bazel_mml/920e8e910767c8cc9d0ffccb50225969/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?)
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors
```

**Comment by ixdy** [comment]
Since we're still trying to figure out how to support multiple versions of bazel in prow, I've created cherry-pick PRs to make release-1.7 and release-1.8 build with bazel 0.6. (No idea if they'll keep working in bazel 0.7.)

**Comment by BenTheElder** [comment]
Small update, we don't have any super special solutions but we *do* have different bazel versions running Prow, release-1.6 builds with bazel `0.5.2` while other jobs use `0.6.1` currently.

**Comment by ixdy** [comment]
Kubernetes 1.7+ builds fine with bazel 0.6+ now, so I'm going to close this issue.
