### ISSUE TITLE
unable to follow logs for multiple pods concurrently

### ISSUE THREAD

**Issue by ssakhuja57** [kubernetes/kubernetes#52672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Tried to follow logs for multiple pods via `/api/v1/namespaces/<ns>/pods/<pod_id>/log?follow=true` and am seeing the output of each successfully at first, but then each of the commands die with `unexpected stream type "` until one is remaining, which continues to run successfully.

**What you expected to happen**:
Each of the commands should run successfully and none should crash.

**How to reproduce it (as minimally and precisely as possible)**:
- Pick a few different pod id's and concurrently follow their logs by curling `<kube_api>/api/v1/namespaces/<ns>/pods/<pod_id>/log?follow=true`
- observe that each runs properly initially
- after some time (less time if higher logging output from concerned pods), observe that all follow commands but one crash with `unexpected stream type "`

**Anything else we need to know?**:
Below are related errors in the minikube logs
`Sep 18 19:49:54 minikube localkube[3117]: E0918 19:49:54.395625    3117 kuberuntime_logs.go:201] Failed with err unexpected stream type "" when writing log for log file "/var/log/pods/ac9d21f0-9ca4-11e7-8cf7-0800272ac2f4/web_0.log": &{timestamp:{sec:63641360994 nsec:395319623 loc:<nil>} stream: log:[]}`
`Sep 18 19:49:54 minikube localkube[3117]: http: multiple response.WriteHeader calls`

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-11T21:52:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: none
- OS (e.g. from /etc/os-release): minikube v0.22.1 on MacOS with virtualbox driver
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by ssakhuja57** [comment]
@kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
The fix was merged and included in 1.7.6 (#51871). Please open a new issue if the problem remains after you upgrade. Thanks.

**Comment by ssakhuja57** [comment]
Thanks @yujuhong! Would you happen to know (or know who would know) when this version will be available with minikube? The latest version `v0.22.2` only has up to `1.7.5`.

**Comment by yujuhong** [comment]
@ssakhuja57, you'd get a better answer filing an issue against the minikube repository https://github.com/kubernetes/minikube
