### ISSUE TITLE
Checkpoint artifacts injected into a pod using device plugins in kubelet 

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#52678]
Device plugins expose an Allocate API which is not expected to be idempotent.
Kubelet checkpoints devices allocated to a pod. 
The artifacts (env vars, mounts, etc) provided by device plugins as part of allocation are not checkpointed by the kubelet.
So in the event of a kubelet restart and pod (re)start, kubelet will have to re invoke "allocate" on a pre-allocated device.
To solve this we either require device plugin allocate to be idempotent which requires plugins keeping track of allocations, or,
kubelet checkpoint artifacts provided by device plugins.

cc @kubernetes/sig-node-bugs

**Comment by lichuqiang** [comment]
I think we should not have too many restrictions on the behaviors of plugins. So to let kubelet checkpoint artifacts provided by device plugins might be a better way to solve this.

**Comment by tengqm** [comment]
@vishh Can we close this, since #55382 is in?
