### ISSUE TITLE
Add e2e test for testing detach volume after pod is evicted.

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#52676]
When pod is evicted, pod is terminated. After this change #45286, attach/detach controller should be able to detach the pod correctly so that new pod which uses the same volume will start up. We need to have an e2e test for this scenario.

**Comment by jeffvance** [comment]
@jingxu97 what environment is good for this e2e test? GCE or GKE or AWS? I see we have _e2e/storage/pd.go_ which has `detachPD` func,

**Comment by jeffvance** [comment]
@jingxu97 does the pod need to be evicted? Or would be ok to delete the pod and then check that the PD is detached. Then create a new pod using the same PD and test that it attaches?

**Comment by jeffvance** [comment]
ping @jingxu97 ^^

**Comment by jingxu97** [comment]
Here we want to test the detach behavior of evicted pods. So delete a pod directly is different from it. When Pod is evicted, the containers will be killed and the pod status is terminated. But the pod api object is not deleted from API server. Before PR #45286, such evicted pods will not trigger detach operation because the pod api object is not deleted from api server.  So the purpose of the test is to make sure detach operation is triggered for such evicted pods.

**Comment by jeffvance** [comment]
Thanks @jingxu97 Do you have a suggestion for how to force a pod to be evicted?

**Comment by msau42** [comment]
You could have the pod do some memory intensive application

**Comment by jeffvance** [comment]
@msau42 ah, like my use of `grep` in the io-streaming pr :-)

**Comment by ianchakeres** [comment]
@jeffvance - Here's another option to cause eviction: [Eviction API](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api).
