### ISSUE TITLE
Pod IP not accessible from master node

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/kubernetes#52671]
I have a 3 node kubernetes cluster, a master and two nodes on AWS that I created with kubeadm (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)

I have created some deployments from the master node and I can see that pods are created on the 2 nodes for each of the deployments. But the issue is I can't access the pod ip from the master or from the other node. So the pod ip is only accessible on the node where is pod is running.

Thanks.

**Comment by dcbw** [comment]
@ kubeadm people, what's the multi-node network setup that kubeadm creates, if any?  Does it use flannel to route pod traffic between nodes, or something else?  kubenet is local-node-only and does not set up routes to send pod traffic from the cni0 bridge on one node to another node.

**Comment by Rev1408** [comment]
I found this open bug in my search. Looks like this is related to docker >=1.13 and flannel

refer: https://github.com/coreos/flannel/issues/799

command to fix it
iptables -P FORWARD ACCEPT
