### ISSUE TITLE
Volume reconstruction after kubelet restarts might not work for some plugins. 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#52683]
/kind bug

When kubelet restarts, there is a reconstruction process in volume manager's reconciler. (Issue #33203 explains the reason why reconstruction of volume spec is needed after kubelet restarts.)
The volume spec uses the directory name for reconstruction. However, the directory name left on disk is not sufficient to reconstruct volume spec for some plugins such as glusterfs, flexvolume, fc, iscsi, vsphere, etc. We have the following issues with current approach.

1.  For some volume plugins, we use fake information to put into the actual state, which might cause problem during volume clean up (detach or unmount) because mount path will not be reconstructed correctly. For glusterfs, it requires to get endpoint API object with endpoint name when creating mounter. Because we could not get endpoint information from disk directory, so the reconstruction process will fail.
 
2. After kubelet restarts, desired state is populated first by listing all the pods and their volumes. We intended to not update the actual state if desired state already has the volume. However, because volume might be deleted from the desired state anytime. If at a point neither desired state and actual state has the volume information, node status updater might mark this volume is not in use which cause detach happen. So, current code does update actual state even if desired state already has this information for once after kubelet restarts. For some volume plugins such as flex volume, the reconstruction code does not check mount point exist or not. If in case the node restarts, even if mounts are gone, actual state still updates the volume which cause reconciler will never mount the volume even through mount points do not exist. There is a PR for fixing this issue by adding a check for mount points during reconstruction process. https://github.com/kubernetes/kubernetes/pull/51985

Proposed solution:

We already lists the reasons for volume reconstruction when kubelet restarts. However, due to the above issued, I am proposing to have a different reconstruct process. The main point of reconstruction is that a) mounted volume will be marked as VolumeInUse in node status b) mounted volume will be cleaned up if no longer needed. For a), only volume unique name is needed. For b) only the mount points (bind mount and global mount) are needed. All these information could be retrieved by reading the directory and mount points in the system. It is not necessary to go through the actual state and try to reconstruct all the information used by the state. When kubelet restarts, we can use a separate cache (called existingVolumesFromDisk) to store the volume name and their mounts. Node status updater will also include the volumes from this cache into VolumeInUser update. Reconciler will also scans the list from existingVolumesFromDisk. If the volume does not exist in either pending operation, actual state, or desired state, reconciler will unmount the volume with the mount path.

**Comment by jingxu97** [comment]
More details about the proposal mentioned above. The main problem we want to solve is to guarantee that,  after kubelet restarts
1. the exsiting volume list in node.Status.VolumesInUse should not be wiped out due to kubelet restarts. In another word, we have to make sure that the existing mounted volumes should be still in the list.
2. If pods are deleted during kubelet restarts, the mount points (bind mount and device mount) should be cleaned up.

For any pods that are added after kubelet restarts, we don't need to take any extra actions since reconciler should be able update desired state, actual state correctly.

For the pods that were added before kubelet restarts, there are two scenarios
1. pod is deleted from API server before kubelet restarts. 
In this case, when kubelet restarts, pod manager will not be able to see the pod object any more and will not add it to the desired state. After waiting for desired state to be populated from all sources, reconciler will go through a process of scanning the all pods' volume directories on the disk. If the mounted volume is not in desired state, reconciler can clean up the mount (the pod volume path contains plugin name and volume spec name. We can use these names to construct volume plugin's NewUnmounter and tear down the volume). Also need to check mount reference to see whether device mount path should be unmounted)

2. pod is deleted from API server right after kubelet restarts.
In this case, when kubelet restarts, pod manager will get the pod first and add it to the desired state. When reconciler scans the volume, since the volume is in desired state, reconciler will skip this volume. In the mean time, if pod is deleted, the mount will be left on the disk without a record. To solve this issue, we propose two approaches
(a). repeat the scan process mentioned in 1 periodically. So even if reconciler skip this volume in the first round because volume is still in desired state, reconciler can catch the left mounted volume in the second round. 
(b). delay deleting pod object from desired state in this case. Desired state populator can check whether there is a pending operation on this volume and whether it is already in actual state. If the volume is not in pending operation or actual state, it will not delete the pod for this round. This way, we give the reconciler a chance to recover this pod volume into the actual state. 

Compared approach (a) and (b), (a) is preferable because it is clearer code wise. Also (b) might has potential problem if reconciler fails to restore the volume into the actual state.

**Comment by msau42** [comment]
Also need to consider the cleanup of those volume plugins that do local attaching.

**Comment by jingxu97** [comment]
talked with @msau42 offline, it seems like volume plugin manager keeps all necessary information for unmounter which can clean up the mounts and also detach volume for plugins that have local attaching.

**Comment by mlmhl** [comment]
The new reconstruct process is really a good idea! I have some questions about the implement details:

1. Consider kubelet restarts between `MountDevice` and `volumeMounter.SetUp`, and pod is deleted before kubelet restarts, this scenario indicates that the global device path is mounted and pod volume path is not bound yet, so we can't find this volume if we only scan all pods' volume directories(`/var/lib/kubelet/pods/{podUID}/volumes`) on the disk. We also need to scan all volume plugins' directories(`/var/lib/kubelet/plugins`) to find such volumes.

2. As you mentioned:

> Reconciler will also scans the list from existingVolumesFromDisk. If the volume does not exist in either pending operation, actual state, or desired state, reconciler will unmount the volume with the mount path

So what's the update mechanism of this `existingVolumesFromDisk` cache? Maybe we can read from disk periodically.

**Comment by jingxu97** [comment]
@mlmhl, Thanks a lot for your inputs. 
1. Yes, plugin mount directories might exist without volume directories. Since it would be quite rare, I think we can add code to clean up this later as another PR.
2. For updating volume mounts information in node status, currently I am thinking to keep part of the original reconstruction code to do this job. 
The basic idea is 
a) for each volume scanned from pod volume directory, try to reconstruct the volume information into actual state. For volumes such as GCE, AWS, Azure, Vsphere, reconstruction can work well. After actual state is updated with the volume information, reconciler will take care of the rest. Node status updater will also be able to get the volume information and update the node status. This way we don't need to worry about node status update, or mounts cleanup failures since reconciler will keep trying.
b) for the rest of the volume plugins, reconstruction cannot work because of missing information. We can try to tear down the volume mounts (as a separate go routine to avoid hanging problem) before reconciler starts to work on the usual reconcile work. We only try to clean up volume mounts once. After reconciler starts to work, we don't repeat this process to avoid interfering with the reconciler work.

The existingVolumesFromDisk cache I menetioned might not work for some volume plugins because we cannot recover the unique volume ids. So for those volumes, we try our best to tear down first if they are no longer needed (i.e., not in desired state) and then there is not much we can do for now.

**Comment by mlmhl** [comment]
@jingxu97  Thanks for your explanation. By the way, what's the plan for this refactor? Are we going to put it in v1.10?

**Comment by jingxu97** [comment]
@mlmhl yes, I am working on it and will try to put it in v1.10. Your feedback is welcome. Also which type volume plugins you are typically using? Any help on testing would be appreciated!

**Comment by mtanino** [comment]
@jingxu97 
>>We already lists the reasons for volume reconstruction when kubelet restarts. However, due to the above issued, I am proposing to have a different reconstruct process. The main point of reconstruction is that a) mounted volume will be marked as VolumeInUse in node status b) mounted volume will be cleaned up if no longer needed. For a), only volume unique name is needed. For b) only the mount points (bind mount and global mount) are needed. 

I think we also need to consider Block volume case for volume reconstruction update.
There is a symbolic link under the pod volume directory(and also global map directory) instead of mount point when a volume is block.

By the way, do you already have PR for this update?

**Comment by jingxu97** [comment]
@mtanino I am preparing the PR now. For block volume, I checked the UnmountVolume and UnmountDevice tear down process. I think UnmountVolume is the same as other volume plugins. For UnmountDevice, I think  globalMapPath is needed for tear down so I modified the AttachedVolume data structure in actual_state_of_word to record this information.

**Comment by mtanino** [comment]
@jingxu97 
Thank you for the consideration. I'm waiting for the PR will be posted.

**Comment by mlmhl** [comment]
@jingxu97 Expect for your PR. I typically use rbd plugin now, and I will try my best to help testing your work after it done.
