### ISSUE TITLE
Federation tests are broken

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#52681]
https://k8s-testgrid.appspot.com/release-master-blocking#gce-federation

Federation tests are broken and blocking the release.

cc @kubernetes/sig-federation-bugs 
cc @jdumars

**Comment by apelisse** [comment]
cc @kubernetes/kubernetes-release-managers

**Comment by madhusudancs** [comment]
This should be fixed in about an hour. Ran the script to cleanup leaked resources. Next run should pass.

**Comment by csbell** [comment]
Leaks are gone, green is back.
