### ISSUE TITLE
kube-apiserver "no --service-cluster-ip-range specified" and "Defaulting to 10.0.0.0/24".

### ISSUE THREAD

**Issue by malc0lm** [kubernetes/kubernetes#52695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Running kube-apiserver without specifing "--service-cluster-ip-range" will print “no --service-cluster-ip-range specified” and exit. But it provide a default value "10.0.0.0/24". Do we need remove validation of --service-cluster-ip-range specified?
```
./kube-apiserver --etcd-servers="http://localhost:2379"  --storage-backend="etcd2" 
I0913 17:00:27.238377   51575 server.go:114] Version: v1.9.0-alpha.0.584+be78d113b1fa40
I0913 17:00:27.239013   51575 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
W0913 17:00:27.239063   51575 authentication.go:380] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
no --service-cluster-ip-range specified
```

**What you expected to happen**:
Since we have provided the default value '10.0.0.0/24', user need not to specify --service-cluster-ip-range in command line.
**How to reproduce it (as minimally and precisely as possible)**:
Run kube-apiserver without "--service-cluster-ip-range".
kube-apiserver --etcd-servers="http://localhost:2379" --storage-backend="etcd2" 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.572+9636522137039d", GitCommit:"9636522137039d48555d2441725133d69805e010", GitTreeState:"clean", BuildDate:"2017-09-13T05:45:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.584+be78d113b1fa40", GitCommit:"be78d113b1fa40cfa17e4973d3aa1b1c2e709edd", GitTreeState:"clean", BuildDate:"2017-09-13T08:56:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):4.10.0-33-generic
- Install tools:
- Others:

**Comment by wackxu** [comment]
I think the problem is that we do not set the default value for the ServiceClusterIPRange, 
we can see the code:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L619
and 
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/services.go
so the validation will fail.

**Comment by malc0lm** [comment]
@wackxu  No, it had set the default value in https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L294.

**Comment by wackxu** [comment]
@malc0lm We can see the execution sequence：
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L256-L263
In the function  `defaultOptions` we do not set the value and then we go to the function `Validate`,so there is something wrong. And the Line you point out is for construct `master.Config`. Maybe there is a little confusion.

**Comment by malc0lm** [comment]
@wackxu  So, I think why we must validate service-cluster-ip-range specificaiton which have already been provided a default value after validation: )

**Comment by wackxu** [comment]
@malc0lm I first think there may other use for Validate and ServiceClusterIPRange, So we can directly set the value for ServiceClusterIPRange and should not use DefaultServiceIPRange everywhere. I think you PR may be better

**Comment by mbohlool** [comment]
cc @jennybuckley
