### ISSUE TITLE
How can I get kubectl describe node output by using API?

### ISSUE THREAD

**Issue by bay1ts** [kubernetes/kubernetes#52694]
/kind feature

Is there any way can I get kubectl describe node 's output by using API or go client?
which api did describe node use?I just can't found them...

kubernetes 1.63

**Comment by itowlson** [comment]
I think the code for this is in `pkg/printers/internalversion/describe.go`, currently beginning at line 2451:

https://github.com/kubernetes/kubernetes/blob/4f2d7b93da2464a3147e0a7e71d896dd2bade9ad/pkg/printers/internalversion/describe.go#L2451

That code does the following:

* Get the node from the REST API by name
* Get the pods associated with the node from the REST API by doing a List operation with a selector of 
"`spec.nodeName` matches the node name, and status is not succeeded or failed"
* Get events if requested
* Format the `describe` result out of the node and pod data, using e.g. `node.Status` for the detailed VM/OS information.  See the `describeNode` function on line 2487ff for how the API objects map to the describe output.

**Comment by bay1ts** [comment]
thanks a lot!!!

**Comment by 871690991** [comment]
Brother, what's the matter? I need help. Which API to use
