### ISSUE TITLE
kubectl support cp cmd?

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#52701]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
l want cp some file to pod
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zjj2wry** [comment]
yes, you can use```kubectl cp -h``` get help info.

**Comment by munnerz** [comment]
Help output as of Kubernetes 1.7 (and [docs link](https://kubernetes.io/docs/user-guide/kubectl/v1.7/#cp)):

```
Copy files and directories to and from containers.

Examples:
  # !!!Important Note!!!
  # Requires that the 'tar' binary is present in your container
  # image.  If 'tar' is not present, 'kubectl cp' will fail.

  # Copy /tmp/foo_dir local directory to /tmp/bar_dir in a remote pod in the default namespace
  kubectl cp /tmp/foo_dir <some-pod>:/tmp/bar_dir

  # Copy /tmp/foo local file to /tmp/bar in a remote pod in a specific container
  kubectl cp /tmp/foo <some-pod>:/tmp/bar -c <specific-container>

  # Copy /tmp/foo local file to /tmp/bar in a remote pod in namespace <some-namespace>
  kubectl cp /tmp/foo <some-namespace>/<some-pod>:/tmp/bar

  # Copy /tmp/foo from a remote pod to /tmp/bar locally
  kubectl cp <some-namespace>/<some-pod>:/tmp/foo /tmp/bar

Options:
  -c, --container='': Container name. If omitted, the first container in the pod will be chosen

Usage:
  kubectl cp <file-spec-src> <file-spec-dest> [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

I think this issue can be closed as the feature already exists.
