### ISSUE TITLE
Kubectl Proxy to Dashboard broken in 1.7.6

### ISSUE THREAD

**Issue by discostur** [kubernetes/kubernetes#52729]
/kind bug

**What happened**:
Deployed a new cluster v1.7.6 with kubeadm and tried to access dashboard via kubectl proxy. I tested two links, but only one works:

```
broken:
http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

works:
http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
```

**What you expected to happen**:

Should work, because with kubernetes 1.7.5 it works without any problem.

**How to reproduce it (as minimally and precisely as possible)**:

deploy new cluster 1.7.6 with kubeadm (centos 7.4) and calico network provider

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
```
on prem
```

- OS (e.g. from /etc/os-release):
```
CentOS 7.4
```

- Kernel (e.g. `uname -a`):
```
Linux k8s-play01.customer-virt.eu 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
```
kubeadm 1.7.5
```

Already discussed the problem at the dashboard repository and it seems to be a problem with kube proxy
https://github.com/kubernetes/dashboard/issues/2368

**Comment by jenciso** [comment]
I have the same problem

**Comment by recyard** [comment]
Same issue here, the fact is if I add a trailing "/" to the following url, the dashboard will show.

http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

**Comment by TomskDiver** [comment]
@kubernetes/sig-network-bugs

**Comment by emwalker** [comment]
I'm seeing this issue in v1.8.0:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.8.0/src/deploy/recommended/kubernetes-dashboard.yaml
```
None of the workaround urls found in various places seem to work.  I'm wondering whether anyone else is also seeing this.

**Comment by pfalomorblab** [comment]
the wiki page has been removed. How can i see the link?
