### ISSUE TITLE
build proxy.go fails to build with "go build" command

### ISSUE THREAD

**Issue by dyatom** [kubernetes/kubernetes#52720]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
kind bug
> /kind feature

**What happened**:

Getting this error when building proxy.go 

C:\Projects\Go\src\k8s.io\kubernetes>go build cmd/kube-proxy/proxy.go
# k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi
pkg\kubectl\cmd\util\openapi\openapi_getter.go:57:42: cannot use s (type *"github.com/googleapis/gnostic/OpenAPIv2".Document) as type *"k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/OpenAPIv2".Document in argument to NewOpenAPIData

**What you expected to happen**:

proxy.go build success.

**How to reproduce it (as minimally and precisely as possible)**:

run "go build k8s.io/kubernetes/cmd/kube-proxy/proxy.go

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: local
- OS (e.g. from /etc/os-release): windows
- Kernel (e.g. `uname -a`): 2016
- Install tools: no
- Others: no

**Comment by liggitt** [comment]
build should be done using the makefile, which ensures correct vendor environment and prerequisites are built:

```
make WHAT=cmd/kube-proxy
```

**Comment by dyatom** [comment]
Sorry, but i didn't understand the solution here, i am following https://kubernetes.io/docs/getting-started-guides/windows/ to install K8S on windows and the instruction are to build the proxy using go build.
i downloaded make for windows and i am not able to compile proxy.go via make.
can you please elaborate a bit more?
