### ISSUE TITLE
Migrate from godep to dep

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/kubernetes#52728]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

When it comes to dependency handling, migrate from godep to [dep](https://github.com/golang/dep). There are two reasons for this:

1. godep development is essentially done. See https://github.com/tools/godep/graphs/contributors. Edward Muller, the primary author of godep, worked in the group that came to the conclusion to start dep and he has contributed to that.
2. Kubernetes is a sufficiently complex project. If dep can work for Kubernetes it will be able to work for most things.

Note, I realize that for k8s to make the change it may mean changes to dep.

**Comment by mattfarina** [comment]
@thockin before I dive headlong into this I would like to know whose blessing I'd need. Don't want to do the work if this isn't going to fly.

**Comment by fejta** [comment]
/assign @sttts @mattfarina 
/assign

Stefan aren't you working on this?

**Comment by sttts** [comment]
@fejta yes: https://github.com/kubernetes/kubernetes/pull/57795

**Comment by cblecker** [comment]
Closing as a dupe of #44873
/close
