### ISSUE TITLE
gci-gce-serial-1.8 timing out

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#52734]
The job [gci-gce-serial-1.8](https://k8s-testgrid.appspot.com/release-1.8-blocking#gci-gce-serial-1.8) is timing out.

Since [gci-gke-serial-1.8](https://k8s-testgrid.appspot.com/release-1.8-blocking#gci-gke-serial-1.8) looks okay this could be a infra config issue.

**Comment by ethernetdan** [comment]
cc/ @ericchiang

**Comment by ericchiang** [comment]
cc @kubernetes/test-infra-maintainers 
cc @abgworrall 
cc @kubernetes/kubernetes-release-managers

**Comment by krzyzacy** [comment]
/assign

I think I bumped gke-serial timeout last time, I'll do the same thing for gce-serial.

**Comment by abgworrall** [comment]
Is there any way to have a single timeout setting for all the serial testjobs ? This isn't the first time we've needed to tweak a job to match some other job ...

**Comment by krzyzacy** [comment]
@abgworrall makes sense - but this test in previous releases does not really take this long to finish

**Comment by BenTheElder** [comment]
@krzyzacy I think we may also need to bump the cross build timeout a bit: https://github.com/kubernetes/kubernetes/pull/49112#issuecomment-330492503
