### ISSUE TITLE
kube-proxy migration tests are failing: "metrics/v1alpha1: the server could not find the requested resource"

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#52740]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
https://k8s-testgrid.appspot.com/sig-network#gci-gce-latest-upgrade-kube-proxy-ds
&
https://k8s-testgrid.appspot.com/sig-network#gci-gce-latest-downgrade-kube-proxy-ds
are failing consistently since 9/15 with below error message:
```
Sep 19 13:42:51.893: Couldn't delete ns: "e2e-tests-sig-network-kube-proxy-upgrade-vjjgq": unable to retrieve the complete list of server APIs: metrics/v1alpha1: the server could not find the requested resource (&discovery.ErrGroupDiscoveryFailed{Groups:map[schema.GroupVersion]error{schema.GroupVersion{Group:"metrics", Version:"v1alpha1"}:(*errors.StatusError)(0xc4211e82d0)}})
```

Example failed build: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-latest-upgrade-kube-proxy-ds/1018

Checked the commits diff, seems likely to be caused by https://github.com/kubernetes/kubernetes/pull/50012.

@deads2k @k8s-mirror-api-machinery-bugs 

**Anything else we need to know?**:

To make thing clear, these two test suites:
1) Upgrade cluster from release/1.8 to master. Or
2) Upgrade cluster from release/1.8 to master and then downgrade cluster to release/1.8 again.

**Comment by mbohlool** [comment]
cc @derekwaynecarr

**Comment by MrHohn** [comment]
Test is no longer failing since 09/22/2017.
