### ISSUE TITLE
Extension API Server and Aggregator Server's OpenAPI spec missing x-kubernetes- extensions

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#52741]
Kube-apiserver has a customization method (TODO: link) to add `x-kubernetes-` extensions to openapi spec (such as `x-kubernetes-group-version-kind`). These extensions are missing from types like `apiregistration` that is aggregated from the Aggregator server itself. I assume they will be missing from API Extension Server too that is responsible for CRDs.

@apelisse

@kubernetes/sig-api-machinery-bugs

**Comment by nikhita** [comment]
Looks like this blocks https://github.com/kubernetes/kubernetes/issues/49465.

**Comment by tengqm** [comment]
/remove-lifecycle stale

I believe this is still an issue.
