### ISSUE TITLE
should creating a working CockroachDB cluster

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#52750]
Seems to be broken for [at least](
https://k8s-testgrid.appspot.com/google-gce#gce-statefulset&include-filter-by-regex=%5EOverall%24%7C%5C%5Bsig%5C-apps%5C%5D%5C%20StatefulSet%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Deploy%5C%20clustered%5C%20applications%5C%20%5C%5BFeature%5C%3AStatefulSet%5C%5D%5C%20%5C%5BSlow%5C%5D%5C%20should%5C%20creating%5C%20a%5C%20working%5C%20CockroachDB%5C%20cluster&width=5) the past two weeks.

/sig apps
/area test

**Comment by kargakis** [comment]
@janetkuo @kow3ns @resouer

**Comment by kargakis** [comment]
@kubernetes/sig-apps-test-failures

**Comment by kow3ns** [comment]
@a-robinson can you take a look please?

**Comment by a-robinson** [comment]
Absolutely, I'll take a look today. Sorry guys!

**Comment by kow3ns** [comment]
@a-robinson thanks!
