### ISSUE TITLE
sample-controller example repository

### ISSUE THREAD

**Issue by munnerz** [kubernetes/kubernetes#52752]
As discussed in https://github.com/kubernetes/apiextensions-apiserver/issues/4 and on Slack with @sttts, @nikhita and @colemickens, it'd be good to have a sample-controller example repository to go along with the current `k8s.io/sample-apiserver` repo.

It could show how to properly use the `k8s.io/code-generator` repository to generate code for CRD types, and how to set up a basic workqueue and sync controller. This could then be used as a basis/reference for others looking to built their own extensions.

**Comment by mbohlool** [comment]
cc @cheftako

**Comment by sttts** [comment]
Also note that this staging repo serves not only as an example (then we could move it out of k8s.io/kubernetes), but is our CI e2e test-case that code-generation for CRDs works (like sample-apiserver is for an UAS).

**Comment by sttts** [comment]
We still need the actual repo. Reopening. @eparis can you create it? Nobody spoke against the repo and the repo name on kube-dev https://groups.google.com/forum/#!topic/kubernetes-dev/WsqhzA2Bius. So I think we can go ahead and create it.

**Comment by nikhita** [comment]
https://github.com/kubernetes/sample-controller has been created (though there is no actual content there). Maybe this can be closed now.

**Comment by sttts** [comment]
> though there is no actual content there

Oops, forgot the new repo in the push script.

**Comment by sttts** [comment]
Tadaa, pushed https://github.com/kubernetes/sample-controller 🎉
