### ISSUE TITLE
Make kubectl awesome

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#5275]
Filing this as a GSoC project idea.

There are many ideas for kubectl improvements in the [CLI roadmap](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md).

Also see issues with the [CLI label](https://github.com/GoogleCloudPlatform/kubernetes/labels/component%2FCLI).

A few of the ideas have been implemented (I'll try to update it soon), but a batch of them could make a good project.

Someone who is interested in this should try out kubectl and identify where the current rough edges are.

**Comment by TamerTas** [comment]
There seems to be a lot of side effects/mutations  going on in `kubectl`. Providing a testable input and output would be a good starting point I think.

**Comment by you-n-g** [comment]
Hi. @bgrant0607 
I'm a prospective GSOC2015 participant.   kubernetes is the accepted GSOC2015 project that attracts me most . I'm getting familiar with it recently and plan to work on this idea.
I want to get started by working on a issue.  But it is a little hard for me to evaluate the workload of the issues. So @bgrant0607 , could you please recommend me a issue that is relatively easier for me to  get started? 
Thanks!

**Comment by bgrant0607** [comment]
@you-n-g If you want a project in kubectl specifically, how about a command similar to `kubectl version` that prints supported API versions, say `kubectl apiversions`? (Item 6 in cli-roadmap.md.)

Existing kubectl version code:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/version.go
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/version.go

Call client.ServerAPIVersions rather than client.ServerVersion:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/client.go#L118

**Comment by you-n-g** [comment]
Greatly Thanks for your such patient guidance!
I'll make PR soon :)

**Comment by you-n-g** [comment]
I've finished drafting [my proposal](https://github.com/you-n-g/gsoc2015/blob/master/proposal.md)
I'll submit it to google-melange in short time. 
Any suggestion?
Thanks!!

**Comment by bgrant0607** [comment]
@you-n-g Thanks for putting together the proposal! We would love to have lots of progress on this.

I think you may underestimate the amount of work required for some of the tasks, however. In particular, configuration reconciliation is challenging on its own -- see #4889. Also, the generator framework could potentially be a project on its own, and deployment manager compatibility likely has significant dependencies, such as sufficiently correct swagger models of API objects and a mechanism for awaiting object instantiation that doesn't yet exist.

In addition to just taking items from the roadmap, I recommend spending some time using kubectl in order to develop a user's perspective on what needs to be improved.

Please go ahead an submit the proposal via melange, however. You can continue to change it through the end of the week, IIUC.

**Comment by you-n-g** [comment]
@bgrant0607  I've updated [my proposal](https://github.com/you-n-g/gsoc2015/blob/master/proposal.md) and submitted it to melange. :)

**Comment by mikedanese** [comment]
Two ui-centric features that would make kubectl more awesome than it already is:

1) tab autocomplete
2) cluster state backup and restore (maybe akin to iptables model). something like:
```
[miked@pilot.prod: ~]# kubectl save > cluster-state.json
[miked@pilot.prod: ~]# kubectl restore < cluster-state.json
```

**Comment by baldwinSPC** [comment]
@mikedanese I would love to see tab auto-complete. 

Can anyone comment on if tab auto-complete is in progress? If not, we could take a stab at it on this end since we've been thinking of doing it just to save ourselves headaches :)

**Comment by mikedanese** [comment]
@eparis did some work upstream to support this spf13/cobra#69. there is a command that ships with the binary release that generates bash autocomplete [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/4a6ab7fd3698c5cc7172c5bd63efab320d1f2d17/cmd/genbashcomp/gen_kubectl_bash_comp.go). you can now genereate autocomplete by running:
```
genbashcomp /etc/bash_completion.d/
```

**Comment by eparis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/completions/bash/kubectl

are bash completions for kubectl

**Comment by eparis** [comment]
the bash completions are automatically generated from hack/run-gendocs.sh

feel free to find new things you wish were tab completed, I'll gladly work with you to get them implemented!

**Comment by eparis** [comment]
@mikedanese 

2) cluster state backup and restore (maybe akin to iptables model). something like:

wouldn't this be    `kubectl get -o json rc,pod,service,node | kubectl create -`

**Comment by baldwinSPC** [comment]
Awesome. Thanks @mikedanese @eparis

**Comment by baldwinSPC** [comment]
@eparis Reading through it all now to see what more can be added.

**Comment by bgrant0607** [comment]
For people who want to help out: cli-roadmap.md is gone. It was out of date.

You can filter issues using the component/kubectl label. Several issues are targeted for the [1.1 milestone](https://github.com/kubernetes/kubernetes/milestones). The main theme is making it easier to create and update resources.  Other improvements are always welcome, of course.

**Comment by bgrant0607** [comment]
cc @hurf @feihujiang
