### ISSUE TITLE
v1.8 hyperkube images don't allow the kubelet to mount

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#52789]
/kind bug

**What happened**:

When a cluster is provisioned using a containerised kubelet using the following images:

gcr.io/google-containers/hyperkube-amd64:v1.8.0-beta.0
gcr.io/google-containers/hyperkube-amd64:v1.8.1-beta.0

Pods with PVCs are not created because kubelet cannot mount the disks. If you look at events, you can see that it's missing some binaries:

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		1m		1	{default-scheduler }			Normal		Scheduled		Successfully assigned thindiskpod to node3
  1m		1m		1	{kubelet node3}				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-5h5x6" 
  1m		1m		5	{kubelet node3}				Warning		FailedMount		MountVolume.MountDevice failed for volume "pvc-4dc51e93-82c5-11e7-a497-0050569c48bf" : executable file not found in $PATH
```

This executable is `mkfs.ext4`. This problem can be resolved by mounting paths from the host into the rkt container, specifically `/usr/sbin` and `/usr/lib`.

Is this expected? @saad-ali mentioned in https://github.com/kubernetes/kubernetes/issues/50802, that mounting operations are moving out from the main process into containers. Is this part of that effort? This caught me quite unexpected, and I didn't find any docs or changelog entries which indicated additional host mounts were necessary.

If it's deliberate, I can close this until we perhaps document the breaking change. Is there a good place where we can document this?
If it's not, I'll leave this open as a tracking issue.

**What you expected to happen**:

The hyperkube image to work without lots of host mounts.

**How to reproduce it (as minimally and precisely as possible)**:

Run kubelet with rkt in one of the above listed images (see CoreOS' [kubelet-wrapper](https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper)).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.0.beta-1
- Cloud provider or hardware configuration**: OpenStack
- OS (e.g. from /etc/os-release): 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.3.0
VERSION_ID=1520.3.0
BUILD_ID=2017-09-15-2017
PRETTY_NAME="Container Linux by CoreOS 1520.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux jamie-terraform-worker-1 4.13.2-coreos #1 SMP Fri Sep 15 20:02:58 UTC 2017 x86_64 AMD Opteron 23xx (Gen 3 Class Opteron) AuthenticAMD GNU/Linux
```
- Install tools: tectonic-installer

**Comment by jamiehannaford** [comment]
Seems the base hyperkube image was changed:

https://github.com/kubernetes/kubernetes/blob/v1.8.0-beta.1/cluster/images/hyperkube/Makefile#L24
https://github.com/kubernetes/kubernetes/blob/v1.7.5/cluster/images/hyperkube/Makefile#L36

done in https://github.com/kubernetes/kubernetes/commit/66b9ae7cd86e1f594f57a6e5d3b11ef9f09460b3.

/cc @ixdy

**Comment by rphillips** [comment]
The pkg/util/mount/mount_linux source defaults to ext4 if a fstype is not selected. It makes sense to restore the e2fsprogs package within the base image.

**Comment by ericchiang** [comment]
cc @kubernetes/sig-node-bugs 
cc @kubernetes/sig-storage-bugs 
cc @kubernetes/kubernetes-release-managers 

This seems like something that should be in the 1.8 milestone. Can someone who owns the hyperkube image comment on that?

**Comment by saad-ali** [comment]
> Is this expected? @saad-ali mentioned in #50802, that mounting operations are moving out from the main process into containers. Is this part of that effort? This caught me quite unexpected, and I didn't find any docs or changelog entries which indicated additional host mounts were necessary.

Containerization of mount is not going to happen until 1.9 at the earliest. So if hyperkube is broken, it should be fixed before ship.

**Comment by edevil** [comment]
"modprobe" also went missing in 1.8 hyperkube images... Both kubelet and kube-proxy need it.

**Comment by jamiehannaford** [comment]
@edevil Are you noticing any buggy behaviour on those components without it? Would you mind creating an issue and/or PR to restore that dep

**Comment by edevil** [comment]
Done: https://github.com/kubernetes/kubernetes/issues/53396
And done: https://github.com/kubernetes/kubernetes/pull/53642

:)
