### ISSUE TITLE
How to fix GitVersion:"v1.7.5+$Format:%h$"

### ISSUE THREAD

**Issue by hongshibao** [kubernetes/kubernetes#52782]
I did some code change based on v1.7.5. After building, I run _**kubectl version**_ command, and found the git version of server version did not update correctly:

_Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5+$Format:%h$", GitCommit:"2e237a828d519eafadeacd3fc4b87557c45186a2", GitTreeState:"clean", BuildDate:"2017-09-18T09:05:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}_

How can I solve this issue?

**Comment by liggitt** [comment]
The official build scripts inject ldflags based on detected git version. Make sure you have fetched all git tags before building.
