### ISSUE TITLE
Kube-Proxy Server Problem

### ISSUE THREAD

**Issue by 3792274** [kubernetes/kubernetes#52791]
![image](https://user-images.githubusercontent.com/19231863/30646581-17df3078-9e4c-11e7-93ce-c7fe23a58001.png)

![image](https://user-images.githubusercontent.com/19231863/30646478-b5e1dce0-9e4b-11e7-8462-027685afada9.png)

 

![image](https://user-images.githubusercontent.com/19231863/30646487-ba87f770-9e4b-11e7-9a8f-b66b4a58bc71.png)

![image](https://user-images.githubusercontent.com/19231863/30646490-be362b26-9e4b-11e7-80ed-7ee8ca23b172.png)

Hello,everyOne,what's happend about this Error?
**Failed to retrieve node info: Get http://10.20.1.11:8080/api/v1/nodes/10.20.1.11: dial tcp 10.20.1.11:8080: getsockopt: connection refused**

**Comment by 3792274** [comment]
when i stop all iptables it worked. by the way docker 17
![image](https://user-images.githubusercontent.com/19231863/30648333-7135428a-9e50-11e7-98df-7448d8423306.png)
![image](https://user-images.githubusercontent.com/19231863/30648344-763929a4-9e50-11e7-89e7-d809bbdd39be.png)
![image](https://user-images.githubusercontent.com/19231863/30648350-7942c8d0-9e50-11e7-9927-abc13ba063f1.png)

**Comment by 3792274** [comment]
I have fix it

**Comment by cmluciano** [comment]
/close

issue fixed
