### ISSUE TITLE
Failing statefulset 1.6-to-1.8 upgrade tests

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#52808]
**What happened**:
Two failing tests:
`[StatefulSetBasic] should not deadlock when a pod's predecessor fails`
`[StatefulSetBasic] should provide basic identity`

Affected test suites:
`gke-gci-1.6-gci-1.8-upgrade-master`
`gke-gci-1.6-gci-1.8-upgrade-cluster`
`gke-cvm-1-6-gci-1-8-upgrade-master`
`gke-cvm-1-6-gci-1-8-upgrade-cluster`

Link for `gke-gci-1.6-gci-1.8-upgrade-master`: https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-gci-1.6-gci-1.8-upgrade-master&sort-by-failures=

**Anything else we need to know?**:
These are NOT release blocking failures.

It is due to removal of `pod.alpha.kubernetes.io/initialized` annotation by PR #49251. The tests require first pod to be created, be ready, and set to healthy before second pod is created. This is made possible by the annotation - it is set to `false` to halt creation of the second pod until the first pod is set healthy. However, for release 1.8, the annotation is removed. The tests will create the second pod immediately without waiting for the first pod to be set healthy, which results in the error `Too many pods scheduled, expected 1 got 2`.

**What we should do to resolve the issue?**:
We can either:
(1) re-design the tests so that they do not rely on the annotation,
(2) skip the tests (just these two tests, other statefulset tests are still passing), or
(3) do nothing (as it is expected) and communicate about this to the community

/cc @enisoc @foxish

**Comment by foxish** [comment]
@jdumars PTAL.

**Comment by jdumars** [comment]
@foxish @crimsonfaith91 Just to confirm, this is NOT release blocking, correct?

**Comment by crimsonfaith91** [comment]
@jdumars Yes, it is not release blocking.

**Comment by crimsonfaith91** [comment]
@jdumars As the failures are not release blocking, i think we can do nothing regarding the tests and communicate to the community. Does it sound good to you?

**Comment by foxish** [comment]
Have been triaged by @crimsonfaith91 and @enisoc. I wouldn't worry about these.

**Comment by jdumars** [comment]
Thank you all for looking into this.  I sincerely appreciate it!

**Comment by ericchiang** [comment]
Can someone please submit PRs to skip these tests if they're not release blocking? Having tests that we expect to fail produces a lot of overhead trying to capture branch healthiness. cc @kubernetes/sig-apps-test-failures

**Comment by crimsonfaith91** [comment]
@ericchiang I will do it.

**Comment by crimsonfaith91** [comment]
Can someone adds a label to this issue? I do not have the permission to do so.

**Comment by enisoc** [comment]
@crimsonfaith91 Was this not fixed by #53096?

**Comment by crimsonfaith91** [comment]
@enisoc Yes, it was fixed by #53096. The PR does link to this issue. This issue should be closed when the PR was merged. Closing.
