### ISSUE TITLE
'Check APIReachability' derailing many 1.5 testjobs

### ISSUE THREAD

**Issue by abgworrall** [kubernetes/kubernetes#52800]
I'm seeing this in all the GKE tests I use to check new OS images against, e.g. https://k8s-testgrid.appspot.com/google-gke#gci-gke-1.5

Not sure where to point this bug; so starting off with the patch manager, who must be sad that they've lost all the GKE test signal ...

/kind bug
/assign @mwielgus 
/cc @saad-ali @krzyzacy

**Comment by krzyzacy** [comment]
we already stopped 1.5 testing support
/close
