### ISSUE TITLE
DynamicProvisioner E2E slow tests failing

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#52815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

A couple of `DynamicProvisioner` tests the the `slow` GKE and GCE suites have been consistently failing since yesterday. See [testgrid](https://k8s-testgrid.appspot.com/google-gke#gci-gke-slow&include-filter-by-regex=DynamicProvisioner)

**What you expected to happen**:
Tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:
Look at failing tests.

**Anything else we need to know?**:
The failing tests correspond to the merge of https://github.com/kubernetes/kubernetes/pull/52350

CC @wongma7 @kubernetes/sig-storage-test-failures @kubernetes/sig-storage-bugs

**Comment by saad-ali** [comment]
From [one of the sample failures](
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/10825) it looks like a nil reference:

```
I0919 20:07:34.755] [91m[1mâ€¢! Panic [14.207 seconds][0m
I0919 20:07:34.755] [sig-storage] Dynamic Provisioning
I0919 20:07:34.755] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/framework.go:22[0m
I0919 20:07:34.755]   DynamicProvisioner Default
I0919 20:07:34.755]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:674[0m
I0919 20:07:34.755]     [91m[1mshould create and delete default persistent volumes [Slow] [It][0m
I0919 20:07:34.755]     [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:611[0m
I0919 20:07:34.755] 
I0919 20:07:34.755]     [91m[1mTest Panicked[0m
I0919 20:07:34.756]     [91mruntime error: invalid memory address or nil pointer dereference[0m
I0919 20:07:34.756]     /usr/local/go/src/runtime/panic.go:489
I0919 20:07:34.756] 
I0919 20:07:34.756]     [91mFull Stack Trace[0m
I0919 20:07:34.756]     	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0919 20:07:34.756]     k8s.io/kubernetes/test/e2e/storage.testDynamicProvisioning(0x3be63b3, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3be0369, 0x3, ...)
I0919 20:07:34.756]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:112 +0xc44
I0919 20:07:34.756]     k8s.io/kubernetes/test/e2e/storage.glob..func12.4.1()
I0919 20:07:34.756]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:610 +0x237
I0919 20:07:34.757]     k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420d75380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0919 20:07:34.757]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:371 +0x219
I0919 20:07:34.757]     k8s.io/kubernetes/test/e2e.TestE2E(0xc420cb1a00)
I0919 20:07:34.757]     	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:47 +0x2b
I0919 20:07:34.757]     testing.tRunner(0xc420cb1a00, 0x3d32098)
I0919 20:07:34.757]     	/usr/local/go/src/testing/testing.go:657 +0x96
I0919 20:07:34.757]     created by testing.(*T).Run
I0919 20:07:34.757]     	/usr/local/go/src/testing/testing.go:697 +0x2ca
```

Introduced [here](https://github.com/kubernetes/kubernetes/pull/52350/files#diff-921d685551b184e272cde1307bb72338R112).

**Comment by saad-ali** [comment]
Unable to get in touch with @wongma7 so @verult from my team will take a look. If we can fix the tests in the next couple of hours we'll send out a PR to do so, otherwise we will roll back the offending PR.

**Comment by verult** [comment]
Looks like it might be caused by deferencing `class` when it could be nil:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L112
and
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L117

Verifying the fix.

**Comment by saad-ali** [comment]
Fix from @verult is https://github.com/kubernetes/kubernetes/pull/52819 awaiting merge
