### ISSUE TITLE
kubectl proxy doesn't redirect to kubernetes dashboard correctly

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#52813]
/kind bug

I created a cluster (tried both on GKE and GCE) running Kubernetes 1.7.6

I ran `kubectl proxy`

Then I tried to access http://127.0.0.1/ui
It redirected to http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy which showed a blank page.

It should have either redirected to:
http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/ (note the trailing /)
 or
http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/ (note the placement of proxy).
Both these URLs work.

**Comment by TomskDiver** [comment]
duplicate: https://github.com/kubernetes/kubernetes/issues/52729
