### ISSUE TITLE
Add e2e tests for Metrics Server and Master Metrics API

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#52811]
Need e2e tests for https://github.com/kubernetes/features/issues/271 which is being released as part of release 1.8.

cc @piosz who is working on the tests.

**Comment by luxas** [comment]
@nikhiljindal Is this blocking the v1.8 release?

**Comment by nikhiljindal** [comment]
Yes. I am hoping that we wont ship 1.8 without any e2e tests for this feature?

I will let @piosz and the release team take a call, if it comes to that. Hopefully we will have e2e tests soon without causing delays to the release.

**Comment by ericchiang** [comment]
This is extremely late to be adding an e2e tests considering we just spent the last three weeks stabilizing the existing tests :(

If e2e tests are absolutely required lets get them in ASAP.

Removing the failing tests labels because this isn't a failing test.

cc @kubernetes/kubernetes-release-managers

**Comment by jdumars** [comment]
@nikhiljindal @piosz this is a serious impact on the 1.8 release.  We need to understand **exactly** what the risk is of shipping without this test in place, as well as some evidence that the test is stable.

**Comment by nikhiljindal** [comment]
Sorry am not as familiar with this feature. I will let @piosz comment on that.

**Comment by piosz** [comment]
@jdumars apologies for the delay but I'm fighting with a cold. I'm working on them, hopefully will finish it today. The original plan was to test it through HPA e2e tests, but we decided to not use metrics-server by default in HPA (see #52553).

**Comment by liggitt** [comment]
if it is not enabled by default for HPA in 1.8, then I don't think the e2e tests are release-blocking

**Comment by ericchiang** [comment]
Commented on the feature repo but the release team has concerns about adding e2e tests this close to the release https://github.com/kubernetes/features/issues/271#issuecomment-331511152

I agree with @liggitt. If this isn't on by default we should remove this from the milestone.

**Comment by piosz** [comment]
The feature is enabled by default but no other component uses it. The rollout plan is as follow:
- in 1.8 metrics-server was introduced
- in 1.9 we switch HPA to use it by default

I agree that having e2e tests is not a release blocker as HPA doesn't use it.

**Comment by luxas** [comment]
> The feature is enabled by default 

To clarify, in GKE only AFAIK, right?

**Comment by piosz** [comment]
GCE/GKE

**Comment by piosz** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/53205
(we test metrics-server in HPA e2e tests which uses metrics from metrics-server)
