### ISSUE TITLE
AzureDisk provisioning doesn't use correct endpoint for Azure Germany

### ISSUE THREAD

**Issue by Xorecs** [kubernetes/kubernetes#52812]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When creating a Persistent Volume Claim on a cluster hosted in Azure Germany (using ACS-Engine), with the azuredisk provisioner, the wrong endpoint for blob storage is used:
Warning         ProvisioningFailed      Failed to provision volume with StorageClass "default": Put https://redacted.blob.core.windows.net/redacted?restype=container: dial tcp: lookup redacted.blob.core.windows.net on redacted: no such host

The PVC used:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-vc
  labels:
    type: diskstorage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

**What you expected to happen**:
The correct endpoint for Azure Germany is: https://redacted.blob.core.cloudapi.de/

**How to reproduce it (as minimally and precisely as possible)**:
-

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Cloud provider or hardware configuration**: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04

**Comment by Xorecs** [comment]
Small Update:
I checked the relevant provisioning files (from ACS-Engine). These all appear to be correct and set the GermanCloud for k8s. All other Azure related features (load balancing etc) works as expected, only the storage gives errors at this moment.

**Comment by Xorecs** [comment]
@kubernetes/sig-azure-bugs
@kubernetes/sig-storage-bugs

**Comment by rootfs** [comment]
cc @andyzhangx

**Comment by andyzhangx** [comment]
https://github.com/kubernetes/kubernetes/pull/50673 already fixed this issue, need to cherry-pick to v1.7, I will follow it.

**Comment by andyzhangx** [comment]
cherry pick fix (https://github.com/kubernetes/kubernetes/pull/52962) is approved, will be merged soon

**Comment by andyzhangx** [comment]
@Xorecs  It's already fixed in master & cherry-pick to v1.7
https://github.com/kubernetes/kubernetes/pull/50673
https://github.com/kubernetes/kubernetes/pull/52962
Could you close this issue? thx

**Comment by RickWisgerhof** [comment]
Thanks @andyzhangx . Closing this issue!

**Comment by Xorecs** [comment]
Thanks @andyzhangx !
