### ISSUE TITLE
ThirdParty resource e2e test should not be marked as conformance

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#52822]
TPR was alpha and alpha features are not required for conformance:

```
ThirdParty resources [Flaky] [Disruptive] Simple Third Party
  creating/deleting thirdparty objects works [Conformance]
  /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/third-party.go:75
[BeforeEach] ThirdParty resources [Flaky] [Disruptive]
  /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:130
```

This is a bug against the 1.7 test suite.

@WilliamDenniss

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing-pr-reviews

**Comment by smarterclayton** [comment]
Fixed in 1.8 because we deleted this test

**Comment by smarterclayton** [comment]
Also @kubernetes/sig-architecture-api-reviews want to confirm we don't consider alpha features a requirement for a conformant Kubernetes implementation.  I know this is still in the backlog but I would expect we could get lazy consensus that alpha is not conformant.

**Comment by bgrant0607** [comment]
Alpha APIs aren't enabled by default, so that they can't be in the default conformance profile for a given release.

**Comment by bgrant0607** [comment]
TPR is also either officially deprecated or will be soon, so it doesn't make sense to add it to conformance.

**Comment by bgrant0607** [comment]
BTW, was there a follow up to the original profile doc?

https://docs.google.com/document/d/1JsE9itAzL-ZSqKbd5rYnHKKSFW6xK4m50wBj1lTz6Do/edit#heading=h.omclf9vogl3x

**Comment by smarterclayton** [comment]
I think that counts as agreement.

**Comment by bgrant0607** [comment]
Correct. :-)

**Comment by WilliamDenniss** [comment]
No followup to the original doc yet. The conformance work group agreed to reduce scope and focus on the core profile to begin with, but profiles are covered in the terms of the program and will be worked on shortly.

**Comment by bgrant0607** [comment]
Alpha and Beta APIs aren't part of conformance at the current time.
