### ISSUE TITLE
Volume reconstruction logic does not do defaulting

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#52820]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In volume manger, volume reconstruction code (which recovers orphaned volumes from mounts), constructs internal objects to represent the volumes, but does not run through validation or defaulting. This can cause issues like https://github.com/kubernetes/kubernetes/issues/52242 where a new field is introduced but not set in the reconsturction version of the object. We should handle this better.

CC @kubernetes/sig-storage-bugs 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saad-ali** [comment]
For HostPath we should disable volume construction altogether.

**Comment by jingxu97** [comment]
I have filed an issue related to internal volume reconstruction process during kublet restarts. The new proposed approach is very different from the current design. Will work on it in detail for 1.9
#52683

**Comment by msau42** [comment]
FYI, volume reconstruction was not the cause of hostpath nil ptr issue.  I just double checked, hostpath volumes do not create any directory under the pod's volumes. Instead it just bind mounts from the global path directly to the container.  So hostpath volumes will not have any directories under the pod directory to reconstruct.

**Comment by msau42** [comment]
However, this issue could still crop up for other volume plugins that add new fields, don't add the new field to ConstructVolumeSpec(), and make assumptions in the plugin code that the new field is set.
