### ISSUE TITLE
Creating e2e test suite for IPVS in upstream CI

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#52834]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Currently, IPVS proxier does not run any e2e test cases. 

**What you expected to happen**:

I think it's important to create test suite for IPVS in upstream CI which will help a lot in moving IPVS existing alpha.

**Anything else we need to know?**:

@Lion-Wei Let's work together.

/sig network

**Comment by Lion-Wei** [comment]
There are to ways to do this work:

1. Use `kubeadm`, but `kubeadm` doesn't support any kube-proxy config right now, so I had this pr #53962 , and also,  `kubernetes-anywhere` need support it too, see this pr: kubernetes/kubernetes-anywhere#464
2. Use `gce/kube-up.sh` build cluster. See this pr: kubernetes/test-infra#5209

The second way is much easier and faster, but I was told they gonna deprecated the `kube-up.sh`, so in the long term, we still need `kubeadm` and `kubernetes-anywhere`'s support.

If anybody have better way or have some suggestion about this, please let me know, I'll be really appreciate, Thanks.
