### ISSUE TITLE
Hyperledger fabric on bluemix Kuburentes 1.7.4 failed due to Chaincode instatatiate failed ..Setup working fine on kuburnets 1.5

### ISSUE THREAD

**Issue by knagware9** [kubernetes/kubernetes#52852]
This issue due to docker version on Kuburenets..

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
![image](https://user-images.githubusercontent.com/25450953/30706257-716b3028-9f15-11e7-9d62-0bea2db239ce.png)

**Comment by cmluciano** [comment]
My guess is that there are permissions missing from RBAC. Please take a look here https://kubernetes.io/docs/admin/authorization/ and see if that helps. 

Without more information, I cannot tell what k8s specifically is doing to block this creation.

**Comment by knagware9** [comment]
any resolution of the issue

**Comment by cmluciano** [comment]
@knagware9 Need more details on what is not creating. Please post logs from the pods and any relevant k8s events.

**Comment by knagware9** [comment]
Ok Thanks....It seems issue with my application ,,same issue I am facing in local enviroment..:)

**Comment by cmluciano** [comment]
/close 

Please reopen or repost on StackOverflow if you continue to have problems
