### ISSUE TITLE
REST api - namespace entity contains namespace attribute as part of the metadata

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#5286]
Namespace entity, as other entities, contains ObjectMeta (metadata), which contains in turn also a namespace property, which is :
a. duplication of information
b. can be updated to a completely different value than the namespace it's in.

so imho this is a bug and can cause inconsistency and confusion.

**Comment by abonas** [comment]
cc @mfojtik

**Comment by derekwaynecarr** [comment]
It should be prevented setting Namespace.Namespace here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L206

Were you able to set it on create or update?

**Comment by abonas** [comment]
I just rechecked on latest master.
I was able to create it using the following input, got 201 CREATED back, but it looks as the namespace property was omitted.

{
    "kind": "Namespace",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "staging",
       "namespace":"some"
    },

}

**Comment by derekwaynecarr** [comment]
did you do this via curl or kubectl?

----- Original Message -----

**Comment by abonas** [comment]
> did you do this via curl or kubectl?

REST client (http)

**Comment by bgrant0607** [comment]
Closing as dupe of #13579
