### ISSUE TITLE
[e2e test failure] [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52871]
The test added in https://github.com/kubernetes/kubernetes/pull/52807 has been extremely flaky since it's introduction, and is messing with our e2e test signal.

https://k8s-testgrid.appspot.com/release-master-blocking#gke-serial
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial
https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke-serial

Since the test was only added yesterday would is be okay to revert it for now?

cc @gnufied @jeffvance @nikhiljindal
cc @kubernetes/sig-storage-test-failures
cc @kubernetes/kubernetes-release-managers

**Comment by jeffvance** [comment]
**gke-serial** err= "Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering" from [`metricsGrabber.GrabFromControllerManager()`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/f)

**Comment by jeffvance** [comment]
**gke-serial** err="Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering" from call to `metricsGrabber.GrabFromControllerManager()`, [L154](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/metrics/metrics_grabber.go#L154)

**Comment by gnufied** [comment]
ack looking into it. thanks @jeffvance for initial debugging.

**Comment by gnufied** [comment]
I am opening a PR shortly. Basically two problems:

1. In some environments we don't have access to controller manager's metrics, so we are going to skip that.
2. In some cases no metric may be emitted yet and hence nothing might be there in old map.


I am going to add some retry in fetching updated metrics just in case for more robust behaviour.

**Comment by gnufied** [comment]
Opened PR - https://github.com/kubernetes/kubernetes/pull/52874 

Sorry about it. :(

**Comment by gnufied** [comment]
@jpbetz I have opened another PR to fix this - https://github.com/kubernetes/kubernetes/pull/54377. I think that, this should fix the flake for good.
