### ISSUE TITLE
iptables start kubelet cluster  not working

### ISSUE THREAD

**Issue by 3792274** [kubernetes/kubernetes#52882]
I have a problem ,when the iptables start ,then the node can't connect to servers.
````
master &  etcd:   10.20.1.11
node1 &  etcd:    10.20.1.12
node2 &  etcd:    10.20.1.13

OS: CentOS7
Docer Version:ce-17
kubernetes version:1.6.0
````
**The Docker Version**
![image](https://user-images.githubusercontent.com/19231863/30729713-3b5db7e2-9f94-11e7-8f2f-e1767e8bbbd5.png)

**I have deployment a nginx Server**
![image](https://user-images.githubusercontent.com/19231863/30729699-1c4fc3ae-9f94-11e7-9c2c-f4c2756d6c30.png)

--------------------------------------------------------------------------
````1.First ,Stop the iptables ````
 

````In the master(10.20.1.11) can  access the server :10.254.105.210````
![image](https://user-images.githubusercontent.com/19231863/30729788-bea88014-9f94-11e7-8008-d68c33ed38ce.png)

````In the node(10.20.1.12) can  access the server :10.254.105.210````
 

-------------------------------------------------------------------------
**BUT,if start iptables in master ,the the node can't access to the server,only the master can access the server,what can i do to fix this ,i want use iptables,**
 
 

````this is the iptables setting````
 
![image](https://user-images.githubusercontent.com/19231863/30729959-ee691754-9f95-11e7-8c29-2a012ff76416.png)

Thank You

/sig network

**Comment by jianzhangbjz** [comment]
Could you post your network info of the cluster here? May be your iptables rules are conflict with the network.

**Comment by 3792274** [comment]
**it happend a big problem,when delete all,create new deployments and server ,in all client it can't access .**
![image](https://user-images.githubusercontent.com/19231863/30730884-aff10cfa-9f9c-11e7-93a3-b5425c7ec24b.png)

**Comment by 3792274** [comment]
@jianzhangbjz   ipconfig info
![image](https://user-images.githubusercontent.com/19231863/30731044-a353e250-9f9d-11e7-91a3-5dc1b34879da.png)

![image](https://user-images.githubusercontent.com/19231863/30731049-afe102c8-9f9d-11e7-99f0-092b3249b48c.png)

![image](https://user-images.githubusercontent.com/19231863/30731059-bab5aea6-9f9d-11e7-91ca-6d2d9a87e7fd.png)

**Comment by 3792274** [comment]
@jianzhangbjz 我想你是懂中文的吧。
我发现 k8s根本没有创建任何iptables的规则或过滤等，好像是没有权限操作一样。
后来我偶然间增加了一条规则
````
iptables -P OUTPUT ACCEPT
service iptables save
service iptables restart
cat /etc/sysconfig/iptable
````
发现，iptables的规则突然增加了很多，这在以前是没有的，见我上面的iptables图。
下面的是增加后的样子。
![image](https://user-images.githubusercontent.com/19231863/30733488-b6903fb0-9fa9-11e7-84d8-bb4e197a903c.png)

**Comment by jianzhangbjz** [comment]
@3792274 I suggest you'd better post this in English here so that more people could help you.  The kube-proxy component is working normal?

**Comment by 3792274** [comment]
kube-proxy worked.OK,I fix it.  thank you.

**Comment by jianzhangbjz** [comment]
You're welcome. So, could we close this issue?

**Comment by cmluciano** [comment]
/assign

@3792274 Please close this issue if it is fixed
