### ISSUE TITLE
kube-apiserver.log  has invisible control character 

### ISSUE THREAD

**Issue by suneeta-mall** [kubernetes/kubernetes#52890]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
kube-apiserver.log uses invisible control character in logging. None of the other k8s logs use this character. 
```
kube-apiserver.log:55:I0922 00:17:12.144729       5 wrap.go:42] GET /api/v1/namespaces/default: (841.773µs) 200 [[kube-apiserver/v1.7.2 (linux/amd64) kubernetes/922a86c] 127.0.0.1:38142]
``` 
here ```841.773µs``` is Invisible control character ```841.773Âµs```
**What you expected to happen**:
Expects log formats and encoding to be consistent across all k8s log files.
**How to reproduce it (as minimally and precisely as possible)**:
Just the log message itself

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by suneeta-mall** [comment]
@kubernetes/sig-api-machinery-bug

**Comment by liggitt** [comment]
this is simply using glog and a stringified time.Duration:

https://github.com/kubernetes/kubernetes/blob/63cc42a861be4351cfe5274d203c4e3386dacf59/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L151

the `µ` character (U+00B5) is two bytes (0xC2 0xB5):
```
		case u < uint64(Millisecond):
			// print microseconds
			prec = 3
			// U+00B5 'µ' micro sign == 0xC2 0xB5
			w-- // Need room for two bytes.
			copy(buf[w:], "µ")
```

that is not the same as two unicode code points U+00C2 (Â) and U+00B5 (µ)

**Comment by suneeta-mall** [comment]
Thanks for looking into this @liggitt. I am not quite sure if I am following where the error is coming from then.
I have a fluentd daemon set https://github.com/fluent/fluentd-kubernetes-daemonset that collects logs from all instances (nodes/masters) but master logs specifically speaking kube-apiserver.log fail to convert to UTF-8.

**Comment by liggitt** [comment]
inspecting a captured apiserver.log in hex, the character is logged as `0xC2 0xB5`, which is the correct [UTF-8 encoding of µ](http://graphemica.com/%C2%B5)
