### ISSUE TITLE
[audit] Always retry sending to webhook

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#52909]
Currently webhook doesn't retry if server returns a server error: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L104

However, for audit logs dropping the whole batch in case of an occasional 5XX might not be a great idea. Maybe it's worth to retry webhook not until the first error? Or at least make it configurable

/cc @sttts @soltysh @ericchiang @CaoShuFeng @piosz @tallclair @kubernetes/sig-api-machinery-bugs

**Comment by hzxuzhonghu** [comment]
configurable +1. Always retry may waste apiserver a lot of resource.

**Comment by ericchiang** [comment]
Is that not what `apierrors.IsInternalError` does? https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L101

We should probably just switch those cases to respond to status codes instead of expecting API server errors then, right?

**Comment by hzxuzhonghu** [comment]
Current logic is to retry with backoff when kinds of timeout, server suggest, internal server error.  But some times when server use reverse proxy, Gateway Timeout may caused by server down. In this case, client should not try, unless audit event is very important.  However, Backoff retry is not very terrible when we limit the send routine #52907   

```
	wait.ExponentialBackoff(backoff, func() (bool, error) {
		err = webhookFn()
		// these errors indicate a need to retry an authentication check
		if apierrors.IsServerTimeout(err) || apierrors.IsTimeout(err) || apierrors.IsTooManyRequests(err) {
			return false, nil
		}
		// if the error sends the Retry-After header, we respect it as an explicit confirmation we should retry.
		if _, shouldRetry := apierrors.SuggestsClientDelay(err); shouldRetry {
			return false, nil
		}
		if apierrors.IsInternalError(err) {
			return false, nil
		}
		if err != nil {
			return false, err
		}
		return true, nil
	})
```

**Comment by hzxuzhonghu** [comment]
But I think to make it work more reliably, client should set timeout. This is controllable, otherwise client may be suspended until a very long time.   So explicitly set http timeout is necessary.

**Comment by crassirostris** [comment]
> configurable +1. Always retry may waste apiserver a lot of resource.

Makes sense

> But some times when server use reverse proxy, Gateway Timeout may caused by server down.

Another possibility -- 502, caused by crashed backend replica behind a proxy

> So explicitly set http timeout is necessary

Agree

**Comment by caesarxuchao** [comment]
cc @jpbetz

**Comment by crassirostris** [comment]
Actually, I realized that 502 is not a problem because it's captured by `InternalError`. However, I would still like to have an option to always retry the webhook until the completion or until it runs out of attemts. Currently, even slight blip in networking, which causes e.g. `connection reset by peer`, in a reasonably big cluster will cause the webhook to lose several hundreds if not thousands audit events.

**Comment by crassirostris** [comment]
Note, that K8s rest client will not retry response if it fails b/c of the networking error, since it's a POST: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L657

I now tend to think that it shouldn't even be configurable: network error should be always retries in the webhook, as it's most probably transient
