### ISSUE TITLE
Service proxy and persistent connection

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#5292]
@davidopp

We had an interesting discussion with a potential client and they have raised an important question regarding services.
Let's assume that we have:
- 50 back-ends
- 5 front-ends with a very high throughput that simply forwards heavy requests to backends using persistent connection
  In this scenario we will utilize only 5 backends, instead of 50. Currently I can imagine that we have a custom logic in service proxy to solve this, but this gets even worse if we start using iptables instead of proxying connections.

This issue is mostly to ignite the discussion whether we want to do something around that or not.

**Comment by davidopp** [comment]
> this gets even worse  if we start using iptables instead of proxying connections.

(because there is no longer a programmable indirection point where we could insert the load-balancing logic @fgrzadkowski described)

My take-away from this is that maybe we should keep both options available, i.e. not rip out the code that implements the current load-balancing technique (though the current load-balancing obviously won't work directly for persistent connections, but it is closer than doing nothing at all).

**Comment by thockin** [comment]
I don't understand.  They intentionally use persistent connection and then
are surprised that we can't utilize the backends more?  I must be
misunderstanding.

They could not persist connections, or they can open more connections and
round-robin them themselves?

What am I not understanding about this?

On Wed, Mar 11, 2015 at 9:12 AM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
In their approach the client gets a list of all of the backends and sets up persistent connections to (I can't remember -- either all or most) of them and then does its own request distribution across the connections. We can do this in Kubernetes by having their client watch the service endpoint information from the API server and then set up the persistent connections based on that information, completely bypassing the service proxy. The question is whether that is a good long-term solution. An alternative is for them to write their own custom service proxy, i.e. move the logic for discovering the endpoints, setting up the persistent connections, and balancing load, out of their client and into the service proxy. The observation was that this model is closer to the model we use today (where the service proxy interposes itself into the traffic stream) than the model we are moving towards (where the service proxy just configures iptables and doesn't get involved in passing traffic back and forth).

**Comment by thockin** [comment]
Right, OK.  Our proxy is L3, so we obviously can not balance at granularity
less than a connection.  They want an L7(ish) service proxy, which we do
not have.

As you say, they can implement it (not very hard) or just do
connection-balancing in the client (also not very hard but more coupled to
k8s).

The iptables changes would also be L3, and should be (almost) behaviorally
indistinguishable from today's proxy.

**Comment by erictune** [comment]
Tim, you don't say whether Kubernetes should at some point offer an L7
balancing as part of the service abstraction.

**Comment by thockin** [comment]
Probably, but it's not clear whether the sessions in question are L7 HTTP
or some other application layer protocol.  Doing L3 is (relatively) easy
without any userspace help (we just need to implement it).  L7 will be
somewhat more difficult.
