### ISSUE TITLE
Add metric and rate limit for mutating operations

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#5295]
The test in https://github.com/GoogleCloudPlatform/kubernetes/pull/5274 starts a bunch of operations on the server that fight over changing boundPods. Eventually apiserver crashed.

We should measure how many mutating operations we have, and we should rate-limit it. Giving some clients a bad experience is better than making the system unusable for everyone.

**Comment by erictune** [comment]
@lavalamp Obsolete because boundPods are gone, or still needed?

**Comment by lavalamp** [comment]
Hmm... less important, but would still be valuable, I think. I'll downgrade to P3.

**Comment by smarterclayton** [comment]
We have metrics for this.  A common failure mode of large clusters is to have one component start writing more and bring down the cluster.  So we probably still want to have a way to rate limit writes by client out of a global pool.
