### ISSUE TITLE
kubectl top node/pod should have option like "--watch"

### ISSUE THREAD

**Issue by u2takey** [kubernetes/kubernetes#52963]
/kind feature

kubectl top node/pod should have option like "--watch" for watching node/pod resource usage.

**Comment by liggitt** [comment]
this would just be a poll of the metrics endpoint. would that have a meaningfully different output from `watch kubetctl top ...`?

**Comment by u2takey** [comment]
@liggitt no difference, just poll of metrics like watch. (watch cmd may not installed by  none-linux users).

**Comment by knightXun** [comment]
using '"watch -n 1 'kubectl top node' " can get same result.

**Comment by jtlz2** [comment]
/reopen Any update on this?

The linked ticket #61332 has been closed as a dupe of this one.

/remove-lifecycle rotten

**Comment by izmailoff** [comment]
> this would just be a poll of the metrics endpoint. would that have a meaningfully different output from `watch kubectl top ...`?

Perhaps the watch option could keep connection open avoiding overhead of establishing a new connection every second.

**Comment by khalilj** [comment]
+1

**Comment by Cediddi** [comment]
I don't understand how opening a new connection for every tick is preferable over implementing this issue with reusing a single connection. This feature request is valuable.

**Comment by NeelavaChatterjee** [comment]
> I don't understand how opening a new connection for every tick is preferable over implementing this issue with reusing a single connection. This feature request is valuable.

+1
This should be taken up.

**Comment by marcelloromani** [comment]
> using '"watch -n 1 'kubectl top node' " can get same result.

Not everybody works on Linux. Not every environment has `watch` available.

**Comment by edrandall** [comment]
There's plenty of evidence here.
/reopen

**Comment by ThermodynamicBeta** [comment]
I do not have watch on my system, this would be great
