### ISSUE TITLE
why I use type: loadbalancer  expose a service  get  EXTERNAL-IP pending? ON GCE。

### ISSUE THREAD

**Issue by myonlyzzy** [kubernetes/kubernetes#52980]
I  create a service on k8s cluster that install on gce apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: guestbook
But   EXTERNAL-IP is all pending .
NAME       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
frontend   10.233.38.145   <pending>     80:30007/TCP   1h

**Environment**:
- Kubernetes version ：Kubernetes v1.7.5+coreos.0
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release):centos7
- Kernel (e.g. `uname -a`): Linux node1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:  ansible
- Others:

**Comment by PbTG** [comment]
From what I have understood, this might be related to [kubeadm/issues/425](https://github.com/kubernetes/kubeadm/issues/425). If you go to that issue you'll find a temporal FIX until [kubernetes/pr/52376](https://github.com/kubernetes/kubernetes/pull/52376) is applied on GKE.

**Comment by nicksardo** [comment]
`kubectl describe ...` the service to see the events. It could be ^, but that only occurs with specific auth settings.
