### ISSUE TITLE
Kubernetes yum repos are not updated

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes#52982]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Using the official kubernetes yum repo, I tried to install version 1.6.10. But it seems that the latest version uploaded is 1.6.7. Is this on purpose, an omission or nobody is maintaining this anymore?

**What you expected to happen**:
To install version 1 6.10 from rpms using the official repo.

**How to reproduce it (as minimally and precisely as possible)**:
Add the official yum repo and do "yum install kubelet-1.6.10"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cristifalcas** [comment]
The repo used was the one from https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by rmb938** [comment]
It also don't seem to have the latest 1.7.x updates. It is currently missing 1.7.6 and 1.7.7.
