### ISSUE TITLE
***WINDOWS*** build proxy.go fails to build with "go build" command

### ISSUE THREAD

**Issue by dyatom** [kubernetes/kubernetes#52984]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug
> /kind feature

**What happened**:

Getting this error when building proxy.go

C:\Projects\Go\src\k8s.io\kubernetes>go build cmd/kube-proxy/proxy.go
k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi
pkg\kubectl\cmd\util\openapi\openapi_getter.go:57:42: cannot use s (type *"github.com/googleapis/gnostic/OpenAPIv2".Document) as type *"k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/OpenAPIv2".Document in argument to NewOpenAPIData
**What you expected to happen**:
proxy.go build success.
**How to reproduce it (as minimally and precisely as possible)**:
run "go build k8s.io/kubernetes/cmd/kube-proxy/proxy.go

**Anything else we need to know?**:

I am following https://kubernetes.io/docs/getting-started-guides/windows/

Environment:
Kubernetes version (use kubectl version): 1.7.3
Cloud provider or hardware configuration**: local
OS (e.g. from /etc/os-release): # windows
Kernel (e.g. uname -a): 2016
Install tools: no
Others: no

**Comment by dyatom** [comment]
@SIG-Windows

**Comment by dyatom** [comment]
@kubernetes/sig-windows

**Comment by liggitt** [comment]
fwiw, cross-build is green, so windows builds are at least running - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-cross

**Comment by jianzj** [comment]
@dyatom  Hello , actually I met the same issue with you. And it may should be package problem when building, go use the wrong place package.

To make it work, you would just delete directory `vendor` and retry, it will work and build out `proxy.exe` .

Feel free to have a try .

**Comment by rjmorse** [comment]
The instructions (from v1.5) referenced specified [building on Windows ](https://github.com/kubernetes/website/blob/9d9f87257a7f7377dc7b876242a800d5b794b407/docs/getting-started-guides/windows/index.md#component-setup) which has known issues. The instructions were [updated with v1.9](https://github.com/kubernetes/website/pull/6180) to reflect the cross-build method (Windows binaries are built on Linux) and the node binaries are now readily available for download. More appropriate compilation steps are also provided now.  This issue should be closed.
