### ISSUE TITLE
v1.8.0 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#53004]
Please link to this issue or comment on this issue with known errata for the 1.8.x release. This follows what we have done for prior releases.

We will be populating the "Known Issues" section of 1.8.0 and above release notes based on this issue

FYI @jdumars @radhikapc @bradamant3 
cc/ @kubernetes/kubernetes-release-managers

**Comment by mbohlool** [comment]
https://github.com/kubernetes/minikube/issues/1996

**Comment by ericchiang** [comment]
Audit logs can impact API server performance https://github.com/kubernetes/kubernetes/issues/51899

**Comment by Bradamant3** [comment]
Do y'all want the writers to add these to the release notes? Or are others shepherding release note content? (The audio discussion in burndown meeting was pretty garbled on my end.)

**Comment by janetkuo** [comment]
`kubectl set image` on ReplicaSet and DaemonSet occasionally returns version errors #53040

**Comment by caesarxuchao** [comment]
Object count quota doesn't handle uninitialized objects correctly. https://github.com/kubernetes/kubernetes/issues/53109.

**Comment by janetkuo** [comment]
`kubectl set` commands on ReplicaSet and DaemonSet occasionally return version registration errors #53040

**Comment by liggitt** [comment]
> delete pods API calls have increased latency at high scale #51899

strawman text for release note known issue:

> A performance issue was identified in large-scale clusters that occurs when deleting thousands of pods simultaneously across hundreds of nodes. Kubelets in this scenario can encounter increased latency of `delete pod` API calls, above the target service level objective of 1 second. Resolution of the performance issue is being tracked in https://issue.k8s.io/51899.

**Comment by liggitt** [comment]
Kubelets using TLS bootstrapping (`--bootstrap-kubeconfig`) or certificate rotation (`--rotate-certificates`) store certificates in the directory specified by `--cert-dir`. The default location (`/var/run/kubernetes`) is automatically erased on reboot on some platforms, which can prevent the kubelet from authenticating to the API server after a reboot. Specifying a non-transient location, such as `--cert-dir=/var/lib/kubelet/pki`, is recommended.

For more information, see [#53288](https://issue.k8s.io/53288).

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/53356#issuecomment-333748618
documentation added in https://github.com/kubernetes/kubernetes/pull/53436

> `kubeadm init` and `kubeadm join` invocations on newly installed systems can encounter a `/var/lib/kubelet is not empty` message during pre-flight checks that prevents setup. If this is the only pre-flight failure, it can be safely ignored with `--skip-preflight-checks`.

**Comment by mattmoyer** [comment]
Known issue for 1.8.0-1.8.1 (issue: https://github.com/kubernetes/kubeadm/issues/485, cherry picked fix for release-1.8: https://github.com/kubernetes/kubernetes/pull/53660):
> Clusters created or upgraded with kubeadm 1.8.0 and 1.8.1 have a stored copy of the join token in the kubeadm-config ConfigMap in the kube-system namespace. This could be a security concern if --tokenTTL=0 was specified. Upgrading to 1.8.2 will sanitize the ConfigMap.
