### ISSUE TITLE
CNI known issues from  0799f5732f..0.6.0

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#53007]
So kubernetes is running CNI version 0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff and there were issues where people seemed to assume we were running CNI 0.6.0.  But we chose (https://github.com/kubernetes/kubernetes/issues/49480) not to upgrade to 0.6.0 in 1.8

However, this is now a 1.8 release concern, in that presumably some of the commits in between 0799f5732f and 0.6.0 are important.

Can we please get a list, suitable for populating the known-issues for the 1.8 release notes, but also (more critically) to verify that none of the known issues might be considered release-blocking.

e.g. no hostPort support with CNI providers
e.g. promisc mode https://github.com/kubernetes/kubernetes/issues/49480#issuecomment-326581571

cc @kubernetes/sig-network-misc

**Comment by justinsb** [comment]
FYI @jdumars @radhikapc @Bradamant3

**Comment by grodrigues3** [comment]
@bowei fyi

**Comment by jdumars** [comment]
If this becomes a known issue, please track it here:  #53004

**Comment by jdumars** [comment]
@justinsb does this still need to be in the 1.8 milestone, or can I move it to 1.9?

**Comment by caseydavenport** [comment]
FYI @dcbw

**Comment by justinsb** [comment]
@jdumars up to you ... personally I think we should wait for the list of important changes, because at least we should document the recommend CNI version (0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff) and make clear that hostPort remains unsupported, but I also just don't know what else is in there.   The promiscuous thing seems odd if the comment is accurate, in that we moved the code from kubelet to CNI, but we didn't update CNI to a version with the moved code (?).

**Comment by jdumars** [comment]
@justinsb @caseydavenport @dcbw Ok, My inclination is to assume this will _not_ be blocking, but leave it in the 1.8 milestone anyway until tomorrow morning just so we have visibility.  If you work some wizardry that needs to go into 1.8, we'll assess urgency at that point.  Assume this will be work tackled in 1.8.x and 1.9, and if necessary, please wax poetic in the "known issues" issue #53004 so our community can make sense out of what actually happened here.   Thank you SO much for this work, care, and attention @justinsb .

**Comment by jdumars** [comment]
I'm giving this an additional 2 hours before I label it non-release-blocking. @justinsb Any updates here? @caseydavenport

**Comment by caseydavenport** [comment]
A bit late, but I'm not currently aware of a reason this should block 1.8.

**Comment by bowei** [comment]
@justinsb addition of promiscuous mode in CNI was one step towards the transition from kubenet => CNI, but some of the other required pieces (ebtables) are not in place, so the transition has not happened yet.

**Comment by dnardo** [comment]
@justinsb and we may end up removing that promisc mode work around if we end up going with something like point to point.

**Comment by squeed** [comment]
This should not block 1.8; there are no code changes needed within k8s if the end-user wishes to upgrade their CNI plugins. While bundling an old version of the CNI plugins is unfortunate, it's not a "regression" per se.

**Comment by bowei** [comment]
Is anyone going to update the CNI included with k8s to the latest version? This is a good time to do it so we get the entire 1.8 cycle for soak.

**Comment by feiskyer** [comment]
> Is anyone going to update the CNI included with k8s to the latest version? 

There is a PR #51250.

**Comment by ericchiang** [comment]
Since the intent of this issue seems to be "verify there's nothing wrong with CNI for 1.8" can we close this in favor of more concrete actions (e.g. "update vendored CNI code" or "add testing for CNI plugin x")?

**Comment by chrislovecnm** [comment]
@ericchiang 

If I am reading this correctly there where action items that @justinsb  recomended

> Can we please get a list, suitable for populating the known-issues for the 1.8 release notes, but also (more critically) to verify that none of the known issues might be considered release-blocking.

> e.g. no hostPort support with CNI providers
> e.g. promisc mode #49480 (comment)

Have those been completed?

I agree we need another couple of issues open.

**Comment by ericchiang** [comment]
> Have those been completed?

No known issues for CNI were added to the 1.8 release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#known-issues

And per caseydavenport and squeed's comments no CNI related issues were considered release blocking.

**Comment by timothysc** [comment]
FWIW - 0.6.0 is being executed on for 1.9 https://github.com/kubernetes/kubernetes/pull/51250 . 

I'll leave it for others to PR for known issues.

**Comment by dims** [comment]
@timothysc @justinsb - do you know if anyone is going to pick up this issue? Looks like it will miss the 1.9 boat otherwise

**Comment by caseydavenport** [comment]
Is there anything to be done here? 

IIUC we've made the changes in v1.9 to include CNI v0.6.0, and there are no known issues to track here?

If that's correct, I think we can close this issue.

**Comment by justinsb** [comment]
Let's just close.  I'm sure this will come up as part of "how do we do releases in a multi-repo" world at the dev summit :-)
