### ISSUE TITLE
The kubernetes-dashboard addon does not contain the RBAC binding it needs

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#53011]
Right now, if you run the dashboard addon (cluster/addons/dashboard/), you'll get 403s for all of the accesses. I'm guessing https://github.com/kubernetes/kubernetes/pull/46750 deleted the ClusterRoleBinding that it was implicitly depending on.

The dashboard yaml should include a dashboard-specific service account, along with a ClusterRoleBinding that grants it all of the (vast) powers it needs.

**Comment by liggitt** [comment]
The current release of the dashboard actually supports running with limited power and having the user log in with an api token

**Comment by cjcullen** [comment]
I think there's nothing for us to do here then? By default, you get a more locked down dashboard, and the [instructions](https://github.com/kubernetes/dashboard/wiki/Access-control) show how to go back to the insecure way if needed.
