### ISSUE TITLE
kubelet/config unit test fails in release-1.6 bazel test

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#53016]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-6/1501

```
E0925 18:02:44.909915       9 event.go:259] Could not construct reference to: '&v1.Pod{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"foo", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.PodSpec{Volumes:[]v1.Volume(nil), InitContainers:[]v1.Container(nil), Containers:[]v1.Container{v1.Container{Name:"ctr", Image:"image", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]v1.ContainerPort(nil), EnvFrom:[]v1.EnvFromSource(nil), Env:[]v1.EnvVar(nil), Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), Requests:v1.ResourceList(nil)}, VolumeMounts:[]v1.VolumeMount(nil), LivenessProbe:(*v1.Probe)(nil), ReadinessProbe:(*v1.Probe)(nil), Lifecycle:(*v1.Lifecycle)(nil), TerminationMessagePath:"", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*v1.SecurityContext)(0xc42048e630), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(nil), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", DeprecatedServiceAccount:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", HostNetwork:false, HostPID:false, HostIPC:false, SecurityContext:(*v1.PodSecurityContext)(nil), ImagePullSecrets:[]v1.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*v1.Affinity)(nil), SchedulerName:"", Tolerations:[]v1.Toleration(nil)}, Status:v1.PodStatus{Phase:"", Conditions:[]v1.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*v1.Time)(nil), InitContainerStatuses:[]v1.ContainerStatus(nil), ContainerStatuses:[]v1.ContainerStatus(nil), QOSClass:""}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'FailedValidation' 'Error validating pod foo_(foo) from test, ignoring: metadata.namespace: Required value'
E0925 18:02:44.913620       9 event.go:259] Could not construct reference to: '&v1.Pod{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.PodSpec{Volumes:[]v1.Volume(nil), InitContainers:[]v1.Container(nil), Containers:[]v1.Container(nil), RestartPolicy:"", TerminationGracePeriodSeconds:(*int64)(nil), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"", NodeSelector:map[string]string(nil), ServiceAccountName:"", DeprecatedServiceAccount:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", HostNetwork:false, HostPID:false, HostIPC:false, SecurityContext:(*v1.PodSecurityContext)(nil), ImagePullSecrets:[]v1.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*v1.Affinity)(nil), SchedulerName:"", Tolerations:[]v1.Toleration(nil)}, Status:v1.PodStatus{Phase:"", Conditions:[]v1.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*v1.Time)(nil), InitContainerStatuses:[]v1.ContainerStatus(nil), ContainerStatuses:[]v1.ContainerStatus(nil), QOSClass:""}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'FailedValidation' 'Error validating pod foo_() from test, ignoring: [metadata.namespace: Required value, spec.containers: Required value, spec.restartPolicy: Required value, spec.dnsPolicy: Required value]'
E0925 18:02:44.918749       9 file.go:72] unable to read config path "random_non_existent_path": path does not exist, ignoring
E0925 18:02:44.920555       9 file.go:72] unable to read config path "/tmp/dir-test718662150/test_pod_config_0": path does not exist, ignoring
--- FAIL: TestReadPodsFromFileChanged (5.00s)
	file_linux_test.go:388: Simple pod: Expected update, timeout instead
```

/assign @yujuhong 

Could you look at this or reassign someone? Thanks.

**Comment by ixdy** [comment]
well, this is fun - I can't get this to reproduce locally, even if I use bazel 0.5.2.

**Comment by ixdy** [comment]
also, this test used to pass - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49833/pull-kubernetes-bazel/33226/?log#log

**Comment by yujuhong** [comment]
Strange. The test started failing in http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-6/1322/artifacts/
But there weren't any relevant change in https://github.com/kubernetes/kubernetes/compare/fc4902f588aca0...7093e81946f244

Also can't reproduce as @ixdy said.

**Comment by yujuhong** [comment]
@ixdy has there been any change in the infra side that could've caused this?

**Comment by ixdy** [comment]
There were quite a few changes in test-infra over that span: https://github.com/kubernetes/test-infra/compare/a9e415c3b...48217f8e2

though nothing that looks super suspicious.

**Comment by ixdy** [comment]
maybe we should just skip this test? still have no idea how to progress on this.

**Comment by BenTheElder** [comment]
If/when this is ever fixed we should revert https://github.com/kubernetes/test-infra/pull/5067 but in the meantime this will unblock 1.6 which is somewhat broken for bazel anyhow.

**Comment by yujuhong** [comment]
```
I1018 23:01:58.361] E1018 23:01:41.773144       9 file.go:72] unable to read config path "/tmp/dir-test828923742/test_pod_config_0": path does not exist, ignoring
```
Assuming the error is relevant, would anything cause the files in `/tmp` to be cleaned up before the test is done (besides the test itself)?

**Comment by ixdy** [comment]
I just kicked off a bazel test run on prow using the v1.6.7 tag, from early July: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-6/1778

The test is still failing, even though it'd previously passed at that version.

This does suggest it's a test-infra issue, though I'm still not sure how.

@yujuhong it's possible some other test is cleaning up `/tmp`.

**Comment by yujuhong** [comment]
> This does suggest it's a test-infra issue, though I'm still not sure how.

Me neither, but re-assigning the bug to you for now since I don't know how to recreate the test environment and track file deletions. :-)

**Comment by BenTheElder** [comment]
Fun fact, hitting something suspiciously similar on 1.7 running unit on Prow:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52755/pull-kubernetes-unit-prow/34/?log#log
This test smells :-(

**Comment by BenTheElder** [comment]
and on 1.8... https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56592/pull-kubernetes-unit-prow/37/

**Comment by yujuhong** [comment]
> and on 1.8... https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56592/pull-kubernetes-unit-prow/37/

Is the test flaking or failing consistently?

**Comment by BenTheElder** [comment]
It fails consistently on branches older than master it seems. We are using docker in docker on prow instead of some rather old docker on jenkins for this version though.

**Comment by BenTheElder** [comment]
I think this particular issue has been solved this by mounting a tmpfs to /tmp in the job container.

**Comment by BenTheElder** [comment]
I think this is back :/ https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56900/pull-kubernetes-unit/16/

**Comment by BenTheElder** [comment]
Heh well, 1.6 is out of support now. Oh well. I don't think we have this issue going forward /shrug

**Comment by ixdy** [comment]
procrastination and laziness saves the day!
