### ISSUE TITLE
[audit] Restore audit logging in the scalability tests

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#53020]
As a result of https://github.com/kubernetes/kubernetes/issues/51899, audit logging was disabled in the scalability tests by https://github.com/kubernetes/test-infra/pull/4720

After https://github.com/kubernetes/kubernetes/issues/53006 is fixed, those tests should again have audit logging enabled to verify the scalability of this feature.

/cc @tallclair

**Comment by crassirostris** [comment]
I think this is a critical bug, since it doesn't allow us to load test audit logging, which is an important thing for a beta feature

**Comment by crassirostris** [comment]
Still blocked on https://github.com/kubernetes/kubernetes/issues/53006
ETA: 1/12/2017
Risks: Not closing https://github.com/kubernetes/kubernetes/issues/53006

**Comment by jberkus** [comment]
@crassirostris 

Please provide a status update and plan for this issue.  Since #53006 isn't getting into 1.9, do you plan to proceed on this issue?  If so, what's ETA for delivery?  You're past the exception deadline.  Thanks!

**Comment by crassirostris** [comment]
Sorry, I forgot to update this bug. We decided, that for this release the fix is too complicated to include, so we're moving this effort to 1.10

**Comment by jberkus** [comment]
escalating priorities since we're in Code Freeze

/priority critical-urgent
/remove-priority important-soon
