### ISSUE TITLE
Kubernetes create symlink /var/log/containers for /var/log/pods/.../*.logs normally is /var/lib/docker/containers

### ISSUE THREAD

**Issue by bamb00** [kubernetes/kubernetes#53022]
> /kind bug
> /sig apps

**What happened**:
The symlink /var/log/containers created by Kubernetes is for /var/lib/docker/containers prior to docker 1.12.5.  In 1.12.6 the path /var/lib/docker/container is replace by /var/log/pods/UID.../*logs.

**What you expected to happen**:
/var/log/containers symlink to /var/lib/docker/containers

**How to reproduce it (as minimally and precisely as possible)**:
- Install docker 1.12.6
- Install Kubernetes v1.6.6
- Fluentd 0.12.31 
- Deploy fleuntd as daemonset

**Anything else we need to know?**:

     Name:           fluentd-wp5wb
     Namespace:      default
     Node:          kubernetes_hostname/xxx.xx.xx.xx
     Start Time:     Mon, 25 Sep 2017 20:17:30 +0000
     Labels:         app=fluentd
                         pod-template-generation=1
     Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"default","name":"fluentd","uid":"8ef7253d-a22e-11e7-a673-00505691e898","apiVersion...
     Status:       Running
     IP:             10.xx.x.x
     Controllers:    DaemonSet/fluentd
     Containers:
       fluentd:
         Container ID:       
     docker://89c57714d89ae41a9ebbae535d757c42cc35eb0f85f6900c53641e430a4bb128
          Image:              fluentd:0.12.31
          Image ID:           docker-pullable://devhub-docker.cisco.com/vnf-docker-
         dev/fluentd@sha256:bb390bd767533b386b9290680143dce161aa96de38feb433abc3c7bef443a7c4
         Port:
         Command:
           fluentd
           -c
            /etc/fluent/fluent.conf
          State:              Running
          Started:          Mon, 25 Sep 2017 20:22:09 +0000
          Ready:              True
          Restart Count:      0
         Requests:
            cpu:      1
            memory:   256Mi
         Environment:
            Container:        fluentd
            Mounts:
                /etc/fluent from config-volume (rw)
                /var/lib/docker/containers from varlibdockercontainers (ro)
                /var/lib/fluentd from fluentdposfiles (rw)
                /var/log from varlog (ro)
                /var/run/secrets/kubernetes.io/serviceaccount from fluentd-token-n3w09 (ro)
     Conditions:
       Type          Status
       Initialized   True
       Ready         True
       PodScheduled  True
     Volumes:
        config-volume:
          Type:       ConfigMap (a volume populated by a ConfigMap)
          Name:       fluentd-config
          Optional:   false
        fluentdposfiles:
          Type:       HostPath (bare host directory volume)
          Path:       /tmp/fluentd
        varlibdockercontainers:
          Type:       HostPath (bare host directory volume)
          Path:       /var/lib/docker/containers
        varlog:
          Type:       HostPath (bare host directory volume)
          Path:       /var/log
        fluentd-token-n3w09:
          Type:       Secret (a volume populated by a Secret)
          SecretName: fluentd-token-n3w09
       Optional:   false
       QoS Class:      Burstable
      Node-Selectors: <none>
      Tolerations:    node.alpha.kubernetes.io/notReady=:Exists:NoExecute
                      node.alpha.kubernetes.io/unreachable=:Exists:NoExecute
      Events:         <none>

From fluentd pod:
     
     # ls -l /var/log/containers
      kube-proxy-tm0d9_kube-system_kube-proxy-32913036aac7df20384146713b3ebe12533d2d4d4438624d0f9ec6fcb499b4e1.log -> /var/log/pods/0485305c-a22d-11e7-a673-00505691e898/kube-proxy_0.log

     # cd /var/log/pods/0485305c-a22d-11e7-a673-00505691e898
     # ls -l kube-proxy_0.log
      kube-proxy_0.log -> /var/lib/docker/containers/32913036aac7df20384146713b3ebe12533d2d4d4438624d0f9ec6fcb499b4e1/32913036aac7df20384146713b3ebe12533d2d4d4438624d0f9ec6fcb499b4e1-json.log

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.6, v.1.7.0
- Cloud provider or hardware configuration**: vsphere
- OS (e.g. from /etc/os-release): CentOS 7.3
- Kernel (e.g. `uname -a`): 3.10.0-514.2.2.el7.x86_64
- Install tools: fluentd 0.12.31
- Others: docker 1.12.6

**Comment by crassirostris** [comment]
/sig node

This is WAI, see the [CRI log management proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md). `/var/log/containers/` is going to be deprecated in the future

**Comment by bamb00** [comment]
OK.  I see the proposal to improve kubectl logs usage.  That's down the road.  I need help or understand why the current symlink /var/log/containers is pointing to /var/log/pods/pod_UID/*.logs is also a symlink to /var/lib/docker/containers/...

Is this permanent until the /var/log/containers is replace by /var/log/pods?

**Comment by crassirostris** [comment]
> I need help or understand why the current symlink /var/log/containers is pointing to /var/log/pods/pod_UID/*.logs is also a symlink to /var/lib/docker/containers/...

Because this is how Kubelet is implemented :) Do you have some problems with that? If so, please describe them

> Any changes need to be made to fluentd td-agent

Eventually -- yes, to the configuration and to https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter
