### ISSUE TITLE
Pods cannot communicate with service cluster IP mode iptables with macvlan

### ISSUE THREAD

**Issue by Surya361** [kubernetes/kubernetes#53089]
> Uncomment only one, leave it on its own line: 
>
/kind bug
/kind feature

**What happened**:
Networking: cni with macvlan
The pods which are deployed are not able to communicate with any service virtual ips, because macvlans dont go through the host system iptables chain rules, which applies DNAT in case of iptables proxy
**What you expected to happen**:
The iptables list should somehow be injected to the macvlan slave interfaces too
**How to reproduce it (as minimally and precisely as possible)**:
Networking: cni with a macvlan 
Create pods and service
exec into the pod and try to connect to the service ip port map

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.7.5
- Cloud provider or hardware configuration**: baremetal
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):4.4.0
- Install tools:manual installtion
- Others:

**Comment by Surya361** [comment]
@kubernetes/sig-network-bugs
/sig network

**Comment by wanghaibo** [comment]
we do it by set multi interfaces to a pod like this:
1. macvlan: eth0@if4: inet 10.10.83.28/16 scope global eth0
2. flannel: net0@if10822:  inet 10.244.0.41/24 scope global net0

and add route like this:
default via 10.10.0.1 dev eth0 
10.10.0.0/16 dev eth0  proto kernel  scope link  src 10.10.83.28 
10.96.0.0/16 via 10.244.0.1 dev net0 
10.244.0.0/24 dev net0  proto kernel  scope link  src 10.244.0.41 
10.244.0.0/16 via 10.244.0.1 dev net0

**Comment by eyz** [comment]
Would this explain why pods on macvlan could not query kube-dns, as it is exposed on a service IP as well?

**Comment by xiaoxubeii** [comment]
Same problem here, the pod container cannot access clusterip because of not host iptables rules.

**Comment by Surya361** [comment]
@eyz Yes it is the reason, if your service ip cidr is the default one

**Comment by jkraj** [comment]
@Surya361 Does changing service ip cidr to actual one will work?. Do you have any workaround for this?

**Comment by Surya361** [comment]
@jkraj nope it dosent kubernetes manages service ips via iptables, no host will be responding to the arp queries made to the service ip. we ditched macvlan in favour of bridged network to get this working. there are a couple of solutions with macvlan itself, you could make one of the kube boxes the default gateway for the service cidr, and when the packet hits the node, the iptables rules that kube injects, will be able to properly route the packet but you have to be careful, along with DNAT you should also masquerade the source ip

**Comment by shaohk** [comment]
@Surya361 How did U solve this issue?

**Comment by KevinTHU** [comment]
@wanghaibo thanks for your answer, it's a useful method, but how you did it, with multus-cni? or others?

**Comment by SongYintao** [comment]
> @wanghaibo thanks for your answer, it's a useful method, but how you did it, with multus-cni? or others?

  [CNI-Genie](https://github.com/cni-genie/CNI-Genie) will address your problem

**Comment by KevinTHU** [comment]
@SongYintao thank you for your reply, I have find a way to do it with multus-cni, and write a instruction on [ZhiHu](https://zhuanlan.zhihu.com/p/73863683). CNI-Genie is also good, but not that user friendly, so I don't choose it finally.

**Comment by plpan** [comment]
when using macvlan in bridge mode, steps to make this work:
1. create a macvlan device in host network namespace,
2. route the packet to ClusterIP in container via this specific macvlan device
