### ISSUE TITLE
Consume ImageFS stats from StatsProvider in ImageGCManager

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#53083]
`ImageGCManager` currently uses the ImageFS stats from cadvisor during image garbage collection. This will not work for containerd, where such stats are provided via CRI instead of cadvisor. We should change the `ImageGCManager` to get the stats from the `StatsProvider`, which abstracts away of cadvisor stats vs CRI stats.

/sig node
/assign
/cc @Random-Liu

**Comment by yujuhong** [comment]
It's too close to the release. I don't think we can get this fixed for 1.8.1. 
We should target this for 1.8.1 though.
