### ISSUE TITLE
Known object count quota problems with uninitialized objects

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#53109]
### Background: when is quota charged
The object count quota is charged when an object is created, no matter if it's initialized or uninitialized. This is to protect the system from having too many uninitialized objects.

Other quotas are charged when objects are initialized. They don't suffer from the problems.

### Problems with replenishing the object count quota
* if the object is deleted uninitialized, the object count quota is not replenished immediately, because the quota replenishment controller doesn't observe uninitialized objects.
* the resource quota controller does a full [resync](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/resource_quota_controller.go#L146) every [5mins](https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.1/cmd/kube-controller-manager/app/options/options.go#L74). It lists every objects in the informer and recalculate the quota usage. The informer doesn't include uninitialized objects, so the controller will wrongly replenish the object count quota for uninitialized objects.

### Brain storming fixes

* Let the replenishment controller observe the uninitialized objects (e.g., https://github.com/kubernetes/kubernetes/pull/51247).

* Or, for the replenishment of object counts, we build a special informer that only observes uninitialized objects. Assuming that the number of uninitialized objects is small, storing uninitialized objects outside of the shared informer causes small overhead. 
  * We can add an fieldSelector or accept header to let apiserver only return uninitialized objects for list/watch.
  * Further, we can create a separate quota for uninitialized object counts.

### Related issues
https://github.com/kubernetes/kubernetes/issues/51820 notes multiple problems with the quota system. Fixing them all-at-once requires a redesign, which could cost multiple quarters. I want to graduate initializers to beta independent of #51820, so I filed this issue to discuss more targeted solutions.

@kubernetes/sig-api-machinery-bugs @lavalamp @liggitt @derekwaynecarr

**Comment by dixudx** [comment]
> Or, for the replenishment of object counts, we build a special informer that only observes uninitialized objects. Assuming that the number of uninitialized objects is small, storing uninitialized objects outside of the shared informer causes small overhead.
> * We can add an fieldSelector or accept header to let apiserver only return uninitialized objects for list/watch.
> * Further, we can create a separate quota for uninitialized object counts.

+1. Agree. With `fieldSelector`, this will be quite concise. Currently, `metadata.initializers` is not supported yet. We may need to add it.

**Comment by munnerz** [comment]
FYI, as of #54660 it is now possible to tweak the ListOptions used by a SharedInformerFactory in order to watch uninitialized objects. This would be a factory-wide tweak however, meaning all controllers in kube-controller-manager would need to handle uninitialized objects cleanly.

**Comment by liggitt** [comment]
the alpha initializers feature has been removed in 1.14

/close
