### ISSUE TITLE
kubectl fails to create tls secrets when key has passphrase

### ISSUE THREAD

**Issue by jpiper** [kubernetes/kubernetes#53100]
/kind bug

**What happened**:

If I have a private key with a passphrase, and I try to create a tls secret I get an error saying it failed to parse the private key

**What you expected to happen**:

I expect kubectl to prompt me to type in the passphrase for said key.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ openssl req -x509 -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=foo.bar.com"
$ kubectl create secret tls testsecret --key=tls.key --cert=tls.crt
error: failed to load key pair tls: failed to parse private key
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T22:14:38Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider or hardware configuration**:

CoreOS baremetal

- OS (e.g. from /etc/os-release):

Mac OS X 10.13

- Kernel (e.g. `uname -a`):

`17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64`

- Install tools:
- Others:

**Comment by zjj2wry** [comment]
this validate func check this, not clean about this validation is must.
```
if _, err := tls.LoadX509KeyPair(s.Cert, s.Key); err != nil {
	return fmt.Errorf("failed to load key pair %v", err)
}
```

**Comment by hzxuzhonghu** [comment]
It is not a bug of k8s.  go does not provide a method to load encrypted keyFile.
You can use openssl command to transform `openssl rsa -in encryedprivate.key -out unencryed.key`

**Comment by jpiper** [comment]
@hzxuzhonghu - I did that as a workaround, but the error message could be slightly more useful (I understand if go isn't providing anything better then that can be hard)

**Comment by hzxuzhonghu** [comment]
[crypto/tls: LoadX509KeyPair can't parse pem file that have password](https://github.com/golang/go/issues/10181)  Maybe k8s need to enrich the ability to satisfy all kinds of scenario.

**Comment by liggitt** [comment]
I'd expect a secret containing a password protected key to be a different type. The TLS type is used by things like ingress, and expect a non-password-protected key. You can create a secret with any content you want with `kubectl create secret generic generic --type=... --from-file=tls.crt=/path/to/cert --from-file=tls.key=/path/to/key`
