### ISSUE TITLE
calico node error in kubeadm environment

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#53111]
[root@master1 ~]# kubectl get pods -n kube-system -o wide
NAME READY STATUS RESTARTS AGE IP NODE
calico-etcd-2p27t 1/1 Running 0 7m 10.110.17.59 master1.kubeadm
calico-node-6753t 1/2 CrashLoopBackOff 6 7m 10.110.17.59 master1.kubeadm
calico-policy-controller-336633499-dn9dp 1/1 Running 0 7m 10.110.17.59 master1.kubeadm

[root@master1 ~]# kubectl log calico-node-6753t -n kube-system calico-node
W0927 21:51:31.309272 32763 cmd.go:392] log is DEPRECATED and will be removed in a future version. Use logs instead.
Skipping datastore connection test
Using autodetected IPv4 address on interface eth0: 10.110.17.59/24
Calico node 'localhost.localdomain' is already using the IPv4 address 10.110.17.59:

Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start
CentOS version：7.3.1611
kubernetes version：1.7.6
Docker version：1.12.6
Calico version：2.4.1

**Comment by caseydavenport** [comment]
@like-inspur I don't think this issue is appropriate for the kubernetes repo. 

Please let's continue discussion on the issue you raised against Calico: https://github.com/projectcalico/calico/issues/1139

/close
