### ISSUE TITLE
kube-dns and weave-net not get starting status was showing like ContainerCreating.

### ISSUE THREAD

**Issue by AnilPaladugu** [kubernetes/kubernetes#53117]
Every 2.0s: kubectl get pods --all-namespaces                                                                                                   Wed Sep 27 12:52:09 2017

NAMESPACE     NAME                                 READY     STATUS              RESTARTS   AGE
kube-system   etcd-vw-srv-001                      1/1       Running             2          55m
kube-system   kube-apiserver-vw-srv-001            1/1       Running             4          40m
kube-system   kube-controller-manager-vw-srv-001   1/1       Running             2          55m
kube-system   kube-discovery-1971138125-iigqz      1/1       Running             0          55m
kube-system   kube-dns-2247936740-8uj92            0/3       ContainerCreating   0          55m
kube-system   kube-proxy-amd64-b7i3j               1/1       Running             0          39m
kube-system   kube-proxy-amd64-d12hh               1/1       Running             0          39m
kube-system   kube-proxy-amd64-nvknq               1/1       Running             0          39m
kube-system   kube-scheduler-vw-srv-001            1/1       Running             2          55m
kube-system   weave-net-8f8pt                      0/2       ContainerCreating   0          37m
kube-system   weave-net-hwgzx                      0/2       ContainerCreating   0          37m
kube-system   weave-net-p626f                      0/2       ContainerCreating   0          37m

root@vw-srv-001:~# kubectl describe pod weave-net-8f8pt --namespace=kube-system
Name:           weave-net-8f8pt
Namespace:      kube-system
Node:           vw-srv-001/192.168.1.33
Start Time:     Wed, 27 Sep 2017 12:14:19 +0530
Labels:         name=weave-net
Status:         Pending
IP:             192.168.1.33
Controllers:    DaemonSet/weave-net
Containers:
  weave:
    Container ID:
    Image:              weaveworks/weave-kube:2.0.4
    Image ID:
    Port:
    Command:
      /home/weave/launch.sh
    Requests:
      cpu:              10m
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://127.0.0.1:6784/status delay=30s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /host/etc from cni-conf (rw)
      /host/home from cni-bin2 (rw)
      /host/opt from cni-bin (rw)
      /host/var/lib/dbus from dbus (rw)
      /lib/modules from lib-modules (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-5lewp (ro)
      /weavedb from weavedb (rw)
    Environment Variables:
      HOSTNAME:  (v1:spec.nodeName)
  weave-npc:
    Container ID:
    Image:              weaveworks/weave-npc:2.0.4
    Image ID:
    Port:
    Requests:
      cpu:              10m
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-5lewp (ro)
    Environment Variables:
      HOSTNAME:  (v1:spec.nodeName)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  weavedb:
    Type:       HostPath (bare host directory volume)
    Path:       /var/lib/weave
  cni-bin:
    Type:       HostPath (bare host directory volume)
    Path:       /opt
  cni-bin2:
    Type:       HostPath (bare host directory volume)
    Path:       /home
  cni-conf:
    Type:       HostPath (bare host directory volume)
    Path:       /etc
  dbus:
    Type:       HostPath (bare host directory volume)
    Path:       /var/lib/dbus
  lib-modules:
    Type:       HostPath (bare host directory volume)
    Path:       /lib/modules
  weave-net-token-5lewp:
    Type:       Secret (a volume populated by a Secret)
    SecretName: weave-net-token-5lewp
QoS Class:      Burstable
Tolerations:    dedicated=master:Equal:NoSchedule
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  38m           14s             175     {kubelet vw-srv-001}                    Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "GenerateRunContainerOptions: expected 4 fields in selinux; got 1 (context: )"

root@vw-srv-001:~# kubectl logs weave-net-8f8pt --namespace=kube-system
Error from server: a container name must be specified for pod weave-net-8f8pt, choose one of: [weave weave-npc]
root@vw-srv-001:~# kubectl describe pod kube-dns-2247936740-8uj92 --namespace=kube-system
Name:           kube-dns-2247936740-8uj92
Namespace:      kube-system
Node:           vw-srv-001/192.168.1.33
Start Time:     Wed, 27 Sep 2017 11:56:38 +0530
Labels:         component=kube-dns
                k8s-app=kube-dns
                kubernetes.io/cluster-service=true
                name=kube-dns
                pod-template-hash=2247936740
                tier=node
Status:         Pending
IP:
Controllers:    ReplicaSet/kube-dns-2247936740
Containers:
  kube-dns:
    Container ID:
    Image:              gcr.io/google_containers/kubedns-amd64:1.7
    Image ID:
    Ports:              10053/UDP, 10053/TCP
    Args:
      --domain=cluster.local
      --dns-port=10053
    Limits:
      cpu:      100m
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           170Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz delay=60s timeout=5s period=10s #success=1 #failure=1
    Readiness:          http-get http://:8081/readiness delay=30s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2v4u1 (ro)
    Environment Variables:      <none>
  dnsmasq:
    Container ID:
    Image:              gcr.io/google_containers/kube-dnsmasq-amd64:1.3
    Image ID:
    Ports:              53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
    Limits:
      cpu:      100m
      memory:   170Mi
    Requests:
      cpu:              100m
      memory:           170Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2v4u1 (ro)
    Environment Variables:      <none>
  healthz:
    Container ID:
    Image:              gcr.io/google_containers/exechealthz-amd64:1.1
    Image ID:
    Port:               8080/TCP
    Args:
      -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:53 >/dev/null && nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
      -port=8080
      -quiet
    Limits:
      cpu:      10m
      memory:   50Mi
    Requests:
      cpu:              10m
      memory:           50Mi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2v4u1 (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-2v4u1:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-2v4u1
QoS Class:      Guaranteed
Tolerations:    dedicated=master:NoSchedule
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  57m           57m             1       {default-scheduler }                    Normal          Scheduled       Successfully assigned kube-dns-2247936740-8uj92 to vw-srv-001
  46m           41m             4       {kubelet vw-srv-001}                    Warning         FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/secret/d129cce3-a34c-11e7-9e6c-2c4d54d1a8d1-default-token-2v4u1" (spec.Name: "default-token-2v4u1") pod "d129cce3-a34c-11e7-9e6c-2c4d54d1a8d1" (UID: "d129cce3-a34c-11e7-9e6c-2c4d54d1a8d1") with: Get https://192.168.1.33:443/api/v1/namespaces/kube-system/secrets/default-token-2v4u1: dial tcp 192.168.1.33:443: getsockopt: connection refused
  57m           1s              3356    {kubelet vw-srv-001}                    Warning         FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-2247936740-8uj92_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-2247936740-8uj92_kube-system(d129cce3-a34c-11e7-9e6c-2c4d54d1a8d1)\" using network plugins \"cni\": cni config unintialized; Skipping pod"

root@vw-srv-001:~# kubectl logs kube-dns-2247936740-8uj92 --namespace=kube-system
Error from server: a container name must be specified for pod kube-dns-2247936740-8uj92, choose one of: [kube-dns dnsmasq healthz]

can any please help me with this..

**Comment by AnilPaladugu** [comment]
@kubernetes/sig-user-experience<group-suffix>

**Comment by cmluciano** [comment]
@AnilPaladugu Can you clarify what the error you are seeing is? What is the output of 

```
kubectl logs weave-net-8f8pt - c weave --namespace=kube-system
kubectl logs kube-dns-2247936740-8uj92 -c kube-dns --namespace=kube-system
```

I'm wondering if Selinux is blocking weave/kube-dns container creation based on this message 
```
38m 14s 175 {kubelet vw-srv-001} Warning FailedSync Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "GenerateRunContainerOptions: expected 4 fields in selinux; got 1 (context: )"
```

This might require more Security Context settings, but I can't be certain. 

What is your installation method for Kubernetes?

**Comment by cmluciano** [comment]
cc @bboreham

**Comment by AnilPaladugu** [comment]
@cmluciano Thanks for your reply .

i just followed kubernetes documentation and this is link https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/..

**Comment by bboreham** [comment]
@AnilPaladugu I think you hit upon quite an old doc; it's citing version Kubernetes 1.4.

I think the latest version of that is https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

If you can try again with up-to-date versions and instructions it may work better, or at least it will be a better basis to debug from.

cc @lukemarsden who may want to update or take down that file.

**Comment by yuanfang2007** [comment]
I also had the same issue. I followed the kubernetes official documentation.


Every 2.0s: kubectl get pods --all-namespaces                                                                                           Fri Oct 20 17:16:31 2017

NAMESPACE     NAME                                       READY     STATUS              RESTARTS   AGE
kube-system   etcd-ip-172-31-30-207                      1/1       Running             0          17m
kube-system   kube-apiserver-ip-172-31-30-207            1/1       Running             0          18m
kube-system   kube-controller-manager-ip-172-31-30-207   1/1       Running             0          17m
kube-system   kube-discovery-1971138125-gog4c            1/1       Running             0          18m
kube-system   kube-dns-2247936740-wb3rt                  0/3       ContainerCreating   0          18m
kube-system   kube-proxy-amd64-cr2sn                     1/1       Running             0          17m
kube-system   kube-proxy-amd64-y065o                     1/1       Running             0          18m
kube-system   kube-proxy-amd64-y8jc7                     1/1       Running             0          17m
kube-system   kube-scheduler-ip-172-31-30-207            1/1       Running             0          17m
kube-system   weave-net-eppzu                            0/2       ContainerCreating   0          17m
kube-system   weave-net-jhtbz                            0/2       ContainerCreating   0          17m
kube-system   weave-net-uzmm3                            0/2       ContainerCreating   0          17m

**Comment by bboreham** [comment]
@yuanfang2007 next step is to find out why they are stuck in ContainerCreating - maybe it cannot download the image?

Check the kubelet logs.

**Comment by bboreham** [comment]
@yuanfang2007 next step is to find out why they are stuck in ContainerCreating - maybe it cannot download the image?

Check the kubelet logs.

**Comment by cmluciano** [comment]
/close 

issue stale

**Comment by sandeeplamb** [comment]
I had the same issue and I had because /var/log filesystem was 100% used. Once I did housekeeping of /var/log and managed to create some space, my containers started creating.

**Comment by nik786** [comment]
core1# cat /etc/systemd/system/weave.service 
[Unit]
Description=Weave Network
Documentation=http://docs.weave.works/weave/latest_release/
Requires=docker.service
After=docker.service
[Service]
EnvironmentFile=-/etc/kubernetes/weave
ExecStartPre=/opt/bin/weave launch --no-restart $PEERS
ExecStart=/usr/bin/docker attach weave
ExecStop=/opt/bin/weave stop
[Install]
WantedBy=multi-user.target

cat /etc/kubernetes/weave 
PEERS=""






core2# cat /etc/systemd/system/weave.service
 
[Unit]
Description=Weave Network
Documentation=http://docs.weave.works/weave/latest_release/
Requires=docker.service
After=docker.service
[Service]
EnvironmentFile=-/etc/kubernetes/weave
ExecStartPre=/opt/bin/weave launch --no-restart $PEERS
ExecStart=/usr/bin/docker attach weave
ExecStop=/opt/bin/weave stop
[Install]
WantedBy=multi-user.target

cat /etc/kubernetes/weave
PEERS="172.17.8.101"


core3#cat /etc/systemd/system/weave.service
[Unit]
Description=Weave Network
Documentation=http://docs.weave.works/weave/latest_release/
Requires=docker.service
After=docker.service
[Service]
EnvironmentFile=-/etc/kubernetes/weave
ExecStartPre=/opt/bin/weave launch --no-restart $PEERS
ExecStart=/usr/bin/docker attach weave
ExecStop=/opt/bin/weave stop
[Install]
WantedBy=multi-user.target

cat /etc/kubernetes/weave 
PEERS="172.17.8.101 172.17.8.102"




core1#./weave status | grep Connections
       Connections: 2 (2 established)

core2# ./weave status | grep Connections
    Connections: 2 (2 established)

core3#./weave status | grep Connections
    Connections: 2 (2 established)


./weave status | grep Range      
          Range: 10.32.0.0/12


this is the present ip range in following services


apiserver.service

--service-cluster-ip-range=10.254.0.0/24

controller.service

--cluster-cidr=10.254.0.0/16

kubelet

--cluster-dns=10.254.0.15


cat kubelet.service

/opt/bin/kubelet --kubeconfig=/opt/bin/kubeconfig    --address=0.0.0.0  --hostname_override=172.17.8.102  --cluster-dns=10.254.0.15  --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --v=0

but when im deploying busybox pod it gives pending state status 
kubectl get all -n kube-system -o wide

NAME          READY     STATUS    RESTARTS   AGE       IP        NODE
pod/busybox   0/1       Pending   0          14s       <none>    <none>
