### ISSUE TITLE
HA is not working when the masters have the same hostname

### ISSUE THREAD

**Issue by Smana** [kubernetes/kubernetes#53118]
/kind bug

@kubernetes/sig-architecture

**What happened**:

This issue have been posted on stackoverflow first : https://stackoverflow.com/questions/46435314/how-to-setup-ha-when-the-masters-have-the-same-hostname

Setting up high availability with 2 masters that have the same hostname but different domain names, for instance: 

- foo.domain1.tld
- foo.domain2.tld

We configured the high availability of the controller and scheduler with the option `--leader-elect=true`. The way it works is by setting a key in etcd (by default `kube-scheduler`). It can be seen in the scheduler logs

```
I0926 15:29:53.926628       1 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-scheduler", UID:"8b6d7117-a2cf-11e7-a32d-549f351a92e0", APIVersion:"v1", ResourceVersion:"3315810", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' foo became leader
```

I checked the key directly into etcd and the value written is the hostname, not the fqdn. So the elected master will always be foo though the masters have different domain names : `domain1.tld`, `domain2.tld`.

**What you expected to happen**:

Provide a way to set another value for the lock such as the option `--hostname-override`

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with 2 masters in order to provide high availability.
The schedulers and controller-manager configured with the parameter `--leader-elect=true`. Both masters **must** have the same hostname (the one that can be retrieved by using the command line `hostname`).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version : v1.7.5 
- Baremetal servers
- OS : ubuntu xenial
- Kernel : 4.4.0

**Comment by hzxuzhonghu** [comment]
```
id, err := os.Hostname()

resourcelock.ResourceLockConfig{
	Identity:      id,
	EventRecorder: recorder,
})
```
the id used should not only contain hostname, a random uid(or hostname+uid) may solve this conflict
