### ISSUE TITLE
Update gRPC library to pick up data race fix

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#53124]
**What happened**:
A test failed in an [unrelated PR](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49705/pull-kubernetes-unit/55317/) because of the data race in gRPC library. It is documented here https://github.com/grpc/grpc-go/issues/1316 and is fixed already.

An update to the gRPC library is necessary to pick up the fix. Not sure which sig owns this.

/kind bug
/kind flake
/sig api-machinery

**Comment by dixudx** [comment]
@ash2k I create a PR #53128 to update gRPC Godeps. PTAL.

**Comment by mindprince** [comment]
/assign
/reopen
The fix was reverted in https://github.com/kubernetes/kubernetes/pull/54400

**Comment by lavalamp** [comment]
cc @jpbetz

**Comment by ash2k** [comment]
Fixed by #57480.
