### ISSUE TITLE
Can't create persistent volume claim on AzureGermanCloud

### ISSUE THREAD

**Issue by ITler** [kubernetes/kubernetes#53138]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Not sure, but feels like a bug
/kind bug

**What happened**:
Can't create _persistentvolumeclaim_ as part of statefulset definition.

**What you expected to happen**:
a persistent volume should have been created as defined

**How to reproduce it (as minimally and precisely as possible)**:
    
    apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: nginx-test
      namespace: itops-testing
      labels:
        state: serving
    spec:
      replicas: 1
      serviceName: nginx
      template:
        metadata:
          labels:
            app: nginx-test
            environment: dev
        spec:
          volumes:
          - name: ps-test
            persistentVolumeClaim:
              claimName: ps-test
          imagePullSecrets:
          - name: registry
          containers:
          - name: nginx
            image: nginx
            volumeMounts:
              - name: ps-test
                mountPath: /tmp

      volumeClaimTemplates:
      - metadata:
          name: ps-test
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
          storageClassName: default

**Anything else we need to know?**:

    $ kubectl describe pvc
    Name:		ps-test-nginx-test-0
    Namespace:	itops-testing
    StorageClass:	default
    Status:		Pending
    Volume:
    Labels:		app=nginx-test
        environment=dev
    Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/azure-disk
    Capacity:
    Access Modes:
    Events:
      FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
      ---------	--------	-----	----				-------------	--------	------			-------
      1m		8s		8	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "default": Put https://p3601836075.blob.core.windows.net/1839508033?restype=container: dial tcp: lookup p3601836075.blob.core.windows.net on 168.63.129.16:53: no such host

**Environment**:
- Kubernetes version (use `kubectl version`):

      Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
      Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: This happens on Azure, but not public cloud, but **AzureGermanCloud** with _pay-as-you-go_ subscription type.
- OS (e.g. from /etc/os-release): `VERSION="16.04.1 LTS (Xenial Xerus)"`
- Kernel (e.g. `uname -a`): `Linux k8s-master-41067869-0 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `acs-engine` using this template:

		{
		  "apiVersion": "vlabs",
		  "location": "germanycentral",
		  "properties": {
			"orchestratorProfile": {
			  "orchestratorType": "Kubernetes",
			  "orchestratorRelease": "1.7"
			},
			"masterProfile": {
			  "count": 1,
			  "dnsPrefix": "${dns_prefix}",
			  "vmSize": "${vm_size_master}",
			  "vnetSubnetId": "${subnet_id}",
			  "firstConsecutiveStaticIP": "${first_master_ip}"
			},
			"agentPoolProfiles": [
			  {
				"name": "agentpool1",
				"count": ${worker_vm_count},
				"vmSize": "${vm_size}",
				"vnetSubnetId": "${subnet_id}",
				"availabilityProfile": "AvailabilitySet"
			  }
			],
			"linuxProfile": {
			  "adminUsername": "${admin_user}",
			  "ssh": {
				"publicKeys": [
				  {
					"keyData": "${ssh_pkey}"
				  }
				]
			  }
			},
			"servicePrincipalProfile": {
			  "clientID": "${service_principle_client_id}",
			  "secret": "${service_principle_client_secret}"
			}
		  }
		}

**Alternative approach tried out**
If changing `StorageClassName` to `managed-standard` creation of _pvc_ succeeds, but mounting to pod during container creation fails with:

    Events:
    FirstSeen	LastSeen	Count	From					SubObjectPath	Type		Reason			Message
    ---------	--------	-----	----					-------------	--------	------			-------
    2s		2s		1	default-scheduler					Normal		Scheduled		Successfully assigned nginx-test-0 to k8s-agentpool1-41067869-0
    2s		2s		1	kubelet, k8s-agentpool1-41067869-0			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-j5flf"
    2s		0s		3	attachdetach						Warning		FailedMount		AttachVolume.Attach failed for volume "pvc-a36112e4-a38d-11e7-a7d3-0017fa101081" : Attach volume "demo-dynamic-pvc-a36112e4-a38d-11e7-a7d3-0017fa101081" to instance "k8s-agentpool1-41067869-0" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a managed disk to a VM with blob based disks is not supported."

What did I miss?

**Comment by ITler** [comment]
@kubernetes/sig-Azure-bugs

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/50673?

**Comment by andyzhangx** [comment]
@liggitt Yes, and there is a cherry pick PR https://github.com/kubernetes/kubernetes/pull/52962 which is going to fix it in v1.7

**Comment by andyzhangx** [comment]
For another issue ```If changing StorageClassName to managed-standard creation of pvc succeeds, but mounting to pod during container creation fails```
That’s because your k8s cluster is based unmanaged VM, you could not attach managed disk to unmanaged VM, you could find detail doc here:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#new-azure-disk-storage-class-starting-from-v172

So my suggestion is you could set up a k8s cluster(v1.7.5) based on managed VM and use managed-standard storage class to create a pvc. The bug#53138 won’t block this scenario.
About how to create a k8s cluster based on managed VM, you could refer to 
https://github.com/Azure/acs-engine/blob/master/examples/disks-managed/kubernetes-vmas.json#L19

**Comment by ITler** [comment]
Will give it a try with managed VMs. Thank you for your support.

**Comment by andyzhangx** [comment]
@ITler It's already fixed in master & cherry-pick to v1.7
https://github.com/kubernetes/kubernetes/pull/50673
https://github.com/kubernetes/kubernetes/pull/52962
Could you close this issue? thx

**Comment by ITler** [comment]
Currently I am not able to efficiently test, as `acs-engine` doest not support 1.7.7+, but once they do, I will do testing. However I'm convinced that this will work now from K8s site, so I close

**Comment by andyzhangx** [comment]
This issue is fixed in v1.7.9, while it's not in v1.8.x, I added a new cherry-pick PR: https://github.com/kubernetes/kubernetes/pull/54615
