### ISSUE TITLE
[1.7.4] Networkpolicis missing from clusterrole admin/edit/view

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#53140]
We give full access to our namespaces via RBAC by binding the clusterrole `admin` to their user. According to the [documentation](https://kubernetes.io/docs/admin/authorization/rbac/#user-facing-roles) this should give them read and write access to almost all resources in their namespace. This does not seem to apply for [networkworkpolicies](https://kubernetes.io/docs/concepts/services-networking/network-policies/):

```
kubectl get networkpolicies
Error from server (Forbidden): User "X" cannot list networkpolicies.extensions in the namespace "default".: "No policy matched." (get networkpolicies.extensions)
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
There's also no mention of them in the clusterrole:
```
kubectl get clusterrole admin  -o yaml | grep network
```
I also can't find a mention of networkpolicies in the boostrap code on master: https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata

/kind bug
@kubernetes/sig-auth

**Comment by liggitt** [comment]
network policies fall into the category of objects a cluster-level admin could use to constrain a namespace (similar to resourcequota), and are therefore not included in the list of objects editable by a namespaced admin by default

a relevant discussion happened at https://kubernetes.slack.com/archives/C0EN96KUY/p1504021636000705

> seh [11:47 AM] 
> Another one of my regular “Why do the bootstrap roles not cover this?” questions:
> Is it intentional that the “admin” _ClusterRole_ does not allow creation off _NetworkPolicy_ objects?
> One could argue that the “edit” _ClusterRole_ should also allow the same. (edited)
> 
> liggitt [1:03 PM] 
> @seh if a cluster admin wanted to isolate a namespace, would they use a network policy to do so?
> 
> seh [1:06 PM] 
> I suppose they _could_, if they wanted to select on all pods in the namespace, and control who was allowed in.
> I have a situation in one of my clusters where the people creating the pods in their namespace want to set rules for who is allowed in to _their_ pods, so they own both the pods and the decision as to who they want to allow to talk to them.
> I expect that cluster administrators would want to use _NetworkPolicies_, but I think you’re looking for whether an administrator allowing a namespace-scoped “tenant” to use them would allow that tenant to circumvent some higher-level control.
> 
> liggitt [1:11 PM] 
> @seh, right... objects that can be used to limit a namespace (resourcequota, limitranges, networkpolicy) are tricky. You can make a case for a cluster admin wanting to use those to limit namespaced admins, and a case for a namespaced admin wanting to use them to put additional limits on parts of their namespaces, or both (cluster admin says "you can have 50 pods in this namespace", namespaced admin says "I'll allow 20 best effort pods, 20 time-bounded pods, and 10 guaranteed qos pods") (edited)
> there's not a terrific answer at the moment, but the bootstrap roles try to err on the side of omitting permissions that have use cases both ways, and letting a deployer add in extra ones they want (edited)

**Comment by spiddy** [comment]
Is this still the case? I just tested granting the `edit` role to a user in a namespace and he can manage networkpolicies inside that namespace.

I would expect this to be restricted as you say likewise with resourceQuotas (which is restricted to `[get list watch]`)

```
$ kubectl describe clusterrole edit|grep networkpolicies
  networkpolicies.extensions               []                 []              [create delete deletecollection get list patch update watch]
  networkpolicies.networking.k8s.io        []                 []              [create delete deletecollection get list patch update watch]
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
