### ISSUE TITLE
Update es examples to v5

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubernetes#53142]
Presently, the elasticsearch example Kubernetes configurations target elasticsearch v1.7.1, which is quite old. As of this writing, the latest elasticsearch release is v5.6.2, with many deployment changes since then. Could the elasticsearch examples be updated to target the v5 series of elasticsearch?

See https://github.com/pires/kubernetes-elasticsearch-cluster for a more up to date reference configuration.

**Comment by dims** [comment]
cc @pires

**Comment by pires** [comment]
hey @dims it's been a long while since I last contributed to the docs. i can do it soon but i need pointers on how to properly do it.

**Comment by dims** [comment]
@pires hey, so we need to update the stuff under examples/elasticsearch/

http://dims.dynu.net/hound/?q=elasticsearch&i=nope&files=examples%2F.*&repos=kubernetes

So basically update the images, yaml files etc and test that everything works (and submit a PR)

**Comment by pires** [comment]
Ah, so there's no documentation updates anymore. OK I'll take care of it, assign it to me.

**Comment by pires** [comment]
@mcandre @dims it seems that the example moved to https://github.com/kubernetes/examples. I am now reading that repo guidelines and will update this there. I'll open a PR that cleans this folder in the current repo and closes this issue.
