### ISSUE TITLE
PVC usage metrics e2e test is flaky

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#53150]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
[log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1896#sig-storage-serial-volume-metrics-should-create-volume-metrics-with-the-correct-pvc-ref)
[testgrid](https://k8s-testgrid.appspot.com/google-gce#gce-serial&include-filter-by-regex=%5EOverall%24%7C%5C%5Bsig%5C-storage%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20Volume%5C%20metrics%5C%20should%5C%20create%5C%20volume%5C%20metrics%5C%20with%5C%20the%5C%20correct%5C%20PVC%5C%20ref)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:172
PVC pvc-tk4f5, Namespace e2e-tests-pv-7bnp6 not found for kubelet_volume_stats_used_bytes
Expected
    <bool>: false
to be true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:229
```

**What you expected to happen**:
Test should not flake

/sig storage
/cc @kubernetes/sig-storage-bugs

**Comment by vkamra** [comment]
@gnufied @msau42 - You won't be able to assign this to me (not a kubernetes member). Am taking a look.

**Comment by jeffvance** [comment]
_volume_metrics.go_ could/should have more logging. either calling `By()` or more calls to `Logf()`.

**Comment by jeffvance** [comment]
The `AfterEach` does not appear to have been called since I don't see the `Logf` entry for deleting the PVC. Or, the client is nil and/or the pvc name is ""?

**Comment by vkamra** [comment]
@jeffvance - will add a couple of Logf() statements to log the samples - you're right that will help.

Once the volume is attached, volume stats are grabbed every `VolumeStatsAggPeriod` interval.

The thing I noticed in the logs is that we issue a delete for the pod at `Sep 25 12:54:41.226`

```Sep 25 12:54:41.226: INFO: Deleting pod pvc-tester-qmdtc```

but the volume only got attached/bound successfully at `Sep 25 12:55:45.572`

```Sep 25 12:55:45.572: INFO: At 2017-09-25 12:53:26 +0000 UTC - event for pvc-tk4f5: {persistentvolume-controller } ProvisioningSucceeded: Successfully provisioned volume pvc-837f3568-a1f0-11e7-9134-42010a800002 using kubernetes.io/gce-pd```

The test assumes [this](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_metrics.go#L142) blocks till the pod is running and PVC is attached but maybe that's not a valid assumption?

**Comment by vkamra** [comment]
Nevermind - That log message has 2 timestamps in it - the volume was provisioned at `2017-09-25 12:53:26`.

**Comment by vkamra** [comment]
Pushed https://github.com/kubernetes/kubernetes/pull/53168. The working theory being that volume stats were not collected within the wait earlier being used.

**Comment by jeffvance** [comment]
@vkamra did you figure out if I was correct in thinking that the framework `AfterEach` was invoked before the local `AfterEach`? That seems very, very unlikely but that is how it looked in the log.

**Comment by vkamra** [comment]
@jeffvance - I believe you're right that the framework `AfterEach` is being invoked before the local one. I observe the same in a [different](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1896#sig-scheduling-schedulerpredicates-serial-validates-maxpods-limit-number-of-pods-that-are-allowed-to-run-slow) test as well, so I don't think it's specific to this call.

Based on the [docs](https://onsi.github.io/ginkgo/), nested `AfterEach` blocks should be invoked inner->outer. It's not clear to be whether the local `AfterEach` is nested or at the same level as the framework block when I look at [NewDefaultFramework](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L117)
