### ISSUE TITLE
ENABLE_APISERVER_BASIC_AUDIT configuration out of date

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53154]
With 1.8, advanced auditing is enabled by default. This means that the `ENABLE_APISERVER_BASIC_AUDIT` flag is no longer accurate:
https://github.com/kubernetes/kubernetes/blob/e33dd983ed75d15245534c87ddaf843aa617638a/cluster/gce/gci/configure-helper.sh#L1355-L1368
It will no longer enable audit logging (due to lack of a policy file), and would not be "basic" auditing.

This flag should either be removed, or explicitly disable the `AdvancedAuditing` feature gate.

**NOTE**: I'm putting this in the 1.8 release because I think it should be cherrypicked in a patch release, but this is NOT a release blocker.

**Comment by crassirostris** [comment]
Thanks a lot for pointing this out!

I think we should not remove the ability have a basic audit enabled in this release. I will create a PR to fix this tomorrow

**Comment by tallclair** [comment]
Sounds good. I think we should still mark it as deprecated though (and remove it in 1.9)

**Comment by crassirostris** [comment]
SGTM

**Comment by jdumars** [comment]
@tallclair is this release blocking?  Please let me know ASAP.
