### ISSUE TITLE
Should return an error for namespaced delete collection on non-namespaced resource.

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#53159]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: If you perform a namespaced delete collection on a non-namespaced resource it will delete ALL instances of that resource. This is especially dangerous as the NamespaceController will issue a namespace delete collection for all resources on the terminating namespace.

**What you expected to happen**: I expected a 4XX error explaining that you cannot perform a namespaced delete collection on this resource.

**How to reproduce it (as minimally and precisely as possible)**:
Install the sample api-server.
Create an extra namespaces, bar.
Create a fischer (either in the default namespace or a namespace foo). (Fischer is still not namespaced, Flunder is now namespaced, check staging/src/k8s.io/sample-apiserver/pkg/registry/wardle/fischer/strategy.go)
Then either curl or delete the namespace bar and wait for it to actually be deleted.
CURL) curl -k -v -XGET  -H "User-Agent: kubectl/v1.8.0 (linux/amd64) kubernetes/49ae996" -H "Accept: application/vnd.kubernetes.protobuf" -H "Authorization: Bearer <token/>" https://<master ip/>/apis/wardle.k8s.io/v1alpha1/namespaces/bar/fischers
DELETE NAMESPACE) kubectl delete namespace bar

kubectl get fischers (expect something to get something back)

**Anything else we need to know?**: Leaving as an exercise for the implementer issues like should other namespace operations also fail but at a minimum the delete collection should.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.0
- Cloud provider or hardware configuration**: GCE

**Comment by WanLinghao** [comment]
can you give an example in detail?
by the way ,what is fischers, I don't remember k8s has this kind of resources.

**Comment by liggitt** [comment]
those are sample resources used as examples/tests

**Comment by cheftako** [comment]
As @liggit mentioned they are our aggregator sample resources. The code for them can be found under https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver. We currently have to resources there flunders and fischers. I recently changed flunders to be a namespaced resource but left fischers as a not namespaced resource so we could test both behaviors.

**Comment by liggitt** [comment]
That was the intent as well, as the RootScopedResources portion of the registration indicates. The strategy was a copy/paste error we should figure out how to make impossible
