### ISSUE TITLE
DynamoDb Support for API Server

### ISSUE THREAD

**Issue by SaranBalaji90** [kubernetes/kubernetes#53162]
# **DynamoDB Support for API Server**

## **Introduction**
Kubernetes is an open-source software for deploying and managing containerized applications. Kubernetes nodes are broadly classified into two groups, Master and Worker nodes. Master nodes provide the cluster’s control plane and worker nodes runs applications. In Kubernetes control plane, ApiServer acts as front-end component. All other components of Kubernetes talk to backend data store through ApiServer. 

## **Requirements for data store**

1.  **Support for watch on Key**
    Most of Kubernetes components instead of invoking get operations regularly on data store, they tend to subscribe for event notifications whenever a key is added/updated. Before subscribing to event notifications, they perform read operations to fetch the existing keys/value in data store and then starts listening for new events.

1.  **Support for Optimistic locking when updating the record**
    Every key in Kubernetes data store must be associated with a version number to support optimistic locking. If the version number in the request matches the record then the operation will succeed.

1.  **Support for backup and restore**
    In order to support crash recovery, data store should support backup and restore functionality. 

## **Etcd**
Etcd is an open-source software for building distributed in house key value store. Applications using etcd can invoke their watch API to track their changes on the key. The Watch API can also be invoked on key prefix rather than complete key name. Also, etcd associates every operation with monotonically increasing sequence number (Also called Revision number). At present, Kubernetes uses Etcd for their backend data store.

## **Data storage architecture**
Kubernetes stores data as key value pair. It uses revision number associated with record for optimistic locking. Kubernetes relies heavily on the etcd watch API to track events associated with keys. These watch operations are invoked mostly on key prefix. 

For example, the token controller is the first controller process that gets initiated. These token controllers are responsible for generating secrets for new service accounts. Therefore, instead of performing get for every few seconds to find new service accounts, it watches on “serviceaccount” prefix to get events whenever new service account is added.

## **DynamoDB Support**
DynamoDB is a fully managed NoSql database service which provides strong consistency, data durability and also highly available by replicating the data across three availability zones. With the support of DynamoDB, Kubernetes customers are no longer required to setup etcd clusters on their end. With managed data store support, users do not need to worry about provisioning servers, upgrading OS or data store. DynamoDB also supports auto scaling which automates capacity management for tables and indexes.

## **DynamoDb Schema**
Table-1: $ClusterName_Metadata
HashKey: Identifier

Attribute-1: SeqIdentifier, SeqNumber
Comments: Put/Update/Delete on KubeMaster will increment the value of SeqNumber by 1. 

Table-2: $Clustername_KubeMaster
Attributes: Key, Value, CreateRevision, ModRevision, Version, Datetime and TTL
Constraints: Key attribute is the HashKey and ModRevision is the RangeKey.
Comments: 
CreateRevision indicates the sequence number when the key is created. 
ModRevision indicates the sequence number when the key is last modified. 
Version number indicates the number of times key has been modified. 
Datetime indicates the time at which value is updated.
TTL indicates time how long record will be persisted in the database.

 Following diagram shows how DynamoDBManager and ApiServer communicate

![image](https://user-images.githubusercontent.com/5009646/30938608-78f07a1e-a38f-11e7-8a6c-fc31dfc9e7ea.png)

All writes from API Servers get forwarded to the leader, who increments the sequence number and writes the record to DynamoDb in order.  

## **K8s Storage API Operations**
This section explains how APIs will be implemented through DynamoDb.

1. **Get**
     Input parameters: Key, ModRevision (optional) 
     Implementation: Invokes DynamoDb.Get operation. If ModRevision is specified then conditional expression is used to fetch the record. Otherwise, the API will return the latest updated record for the key.

2. **Create**
     Input parameters: Key, Value, TTL(optional)
     Implementation: Invokes DynamoDb.Put operation. It uses Conditional expression to insert only if the key doesn’t exist before.

3. **Update**
     Input parameters: Key, Value, ModRevision, TTL(optional)
    Implementation: Invokes DynamoDb.Put operation. It uses conditional expression to update only if ModRevision number matches the record in datastore.

4. **Delete**
     Input parameters: Key, ModRevision (required for ConditionalDelete API)
     Implementation: Invokes DynamoDb.Delete operation. It uses conditional expression to verify if ModRevision matches the record in datastore.

5. **List**
     Input parameters: Key, ModRevision (optional)
     Implementation: Invokes DynamoDb.Scan operation to retrieve all the keys that matches with prefix of give input key and filters out those which has ModRevision less than given value.

6. **Watch**
      Input parameters: Key, recursive (boolean), initialRevision
      Implementation:
          *) Uses DynamoDB streams to watch for given Key. DynamoDB streams are ordered flow of information about changes to items in an Amazon DynamoDB table. Items in the streams appear in same sequence as actual modification to items.
          *) Also builds prefix tree data structure to store the watch Keys. Watch keys are stored along with a recursive flag. Values for these nodes also includes, list of channels to which the events have to be forwarded.

Following diagram explain how watch will be implemented

![image](https://user-images.githubusercontent.com/5009646/30938565-4c7c3842-a38f-11e7-9244-e51e24a091ea.png)

## **DynamoDb Manager Components:**
**Request Handler:**   

1. For every input request, unique channel is created to hold the data from the stream (let’s call this BufferChannel)
1. Generates a unique watch id and invokes StreamHandler to insert these resources into prefix tree.
1. If initialRevision is specified, request handler invokes List API and forwards the items returned to output channel in the request.
1. Finally, it loops through the BufferChannel and forwards the events to output channel.

**Stream Handler (Invokes ddb streams):**

1. Whenever an item is found in stream, watch will retrieve all the nodes from prefix tree whose key matches the prefix of the item in the stream. 
1. Constructs the event and forwards it to buffered channel.
1. When a key is deleted and if it’s not a recursive watch. The channels are closed and removed from the node values.

## **Plugin support for Additional Data store**
(This section gives high level overview of interaction between API server and data store. Implementation details to follow up separately)

Current APIServer and Etcd interaction is implemented as follows,

![image](https://user-images.githubusercontent.com/5009646/30938574-5405bc82-a38f-11e7-8f13-49678070f2bb.png)

Get and Watch requests from clients are served from cache if possible. If revision number is not specified then the requests gets forwarded to Store which communicates with etcd.

In proposed architecture, there is an additional interface named DataStore to abstract the actual storage layer. ApiServer should create a DynamoDbMgr client to communicate with the DynamoDbMgr component. DynamoDbMgr client and the server communicate through gRPC.

Following diagram explains the proposed implementation 

![image](https://user-images.githubusercontent.com/5009646/30938580-5ae44884-a38f-11e7-9ca6-ddc4ea6bb3a0.png)

**Comment by SaranBalaji90** [comment]
cc @deads2k @lavalamp @nckturner @liggitt @smarterclayton @k8s-mirror-api-machinery-pr-reviews Can you please review and give your initial comments on the overall design.

**Comment by SaranBalaji90** [comment]
@kubernetes/sig-api-machinery-proposals

**Comment by lavalamp** [comment]
Prior situation: https://github.com/kubernetes/kubernetes/pull/31622#issuecomment-327606218

Doc the SIG approved (pending a few changes that won't affect this) earlier today: https://docs.google.com/document/d/1i0xzRFB-uGLmLYueLMBTpHrOot9ScFxpkkcVcZHVbyA/edit#

**Comment by bgrant0607** [comment]
@SaranBalaji90 

Thank you for your proposal, but I'm sorry, but this is not feasible.

We recently decided to go all-in on etcd3 for the indefinite future, and closed the original long-standing request for pluggable storage backends:
https://github.com/kubernetes/kubernetes/issues/1957

**Comment by eswarbala** [comment]
@bgrant0607 @lavalamp Concern about test and supportability matrix bloat I understand. But there are alternatives and as discussed in the last meeting, CNI sets a good precedence. The networking ecosystem for k8s is vibrant with the CNI infra in place and I think it reasonably avoids overextending the test requirements as well. 

It will be nice to at least discuss the possible alternatives here and give an opportunity for folks who are interested in seeing the storage abstraction survive and evolve.

**Comment by bgrant0607** [comment]
@eswarbala I agree that it's possible, but it's not feasible. The API machinery team is stretched too thin.

I suggest getting involved with SIG API machinery and chop wood and carry water for a while, help complete ongoing efforts, fix bugs, and learn the system design and project conventions.

For example, we could use help making the OpenAPI spec more correct and complete:
https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/7HgRM8mm3qY

**Comment by lavalamp** [comment]
If you really have to do this, a shim that converts etcd3 protocol to DynamoDB is the only option I see. That makes the magnitude of what you'd be undertaking clear. We intend to start using arbitrarily large portions of the etcd3 feature set, so it would have to be a really good shim.

The doc I linked contains a list of the directions we want to evolve in. But we're not ready to do that at the moment, we have much more urgently absent extension points to add. If this proposal as written were implemented, it would make it at least twice as difficult to do things like split objects to store spec and status separately, or switch to storing by UID and keep name as an index. Not to mention the ongoing maintenance burden of making sure things work over updates. We couldn't afford the upkeep on this.

And from another perspective, I am not aware of any user visible benefit from doing this. (In contrast to your example of CNI, where there is a user visible benefit of being able to interact with arbitrary preexisting networking environments.) In fact we are now recommending that extension apiservers install their own copy of etcd, via CoreOS's etcd-operator. We definitely don't want extension authors to have to provide a different install script/mechanism for every cluster environment. So letting the storage mechanism leak through, being visible to users--in short, having an alternative here actually hampers the ecosystem, which is the opposite of what we want to accomplish with the work to add extension mechanisms. Even if there is potential benefit to cluster operators, it wouldn't be enough to compensate for this.

**Comment by eswarbala** [comment]
@lavalamp Appreciate the explanation. As far as the user benefit in enabling different datastore implementations, it enables K8s usage in environments with certain data policies. I think this [comment](https://github.com/kubernetes/kubernetes/issues/1957#issuecomment-137616217) from 2 years ago about data policy requirements, still stands.  We did consider the etcd3 shim, but it seemed more natural to evolve with the defined abstraction than to evolve to etcd3 APIs. Will catch up on the doc you pointed.

@bgrant0607 Definitely be engaged with SIG-API machinery along with others. Thanks for the link.

**Comment by xiang90** [comment]
@lavalamp @SaranBalaji90 

> If you really have to do this, a shim that converts etcd3 protocol

Luckily, etcd already has a 100% compatible built-in shim. We had the plan to do etcd atop cloud spanner, tikv, etc.

All you need to do is to implement a small interface: https://github.com/coreos/etcd/blob/master/mvcc/backend/backend.go#L49-L60. Then you can start a one node etcd as an etcd-shim to that backend.

**Comment by lavalamp** [comment]
@eswarbala I'm not aware of a big Kubernetes user blocked by such a policy. But assuming they exist, we have to balance that sort of request with what is healthy for the project.

I won't deny that orgs often have bizarre policies. But to me (and speaking strictly for myself here) a policy which is read to mean that Kubernetes can't use etcd ought also be read to mean that e.g. windows can't use its registry. That doesn't seem like a reasonable requirement.
