### ISSUE TITLE
kubelet converts and validates pods multiple times

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#53171]
To read a pod manifest file from disk (or from the http source), kubelet execute the following code to 
 1. Decode a on-disk v1 pod manifest to an internal pod object (the defaults are applied in this process).
 2. Validate the internal pod.
 3. Convert the internal pod back to a v1 pod. 
https://github.com/kubernetes/kubernetes/blob/64fde98206fcb764958d62a1a4a03c0420d72b45/pkg/kubelet/config/common.go#L108-L137

The downstream pod cache (which gets v1 pods from different sources) performs similar operations:
 1. Convert the v1 pod to an internal pod.
 2. Validate the internal pod.
https://github.com/kubernetes/kubernetes/blob/64fde98206fcb764958d62a1a4a03c0420d72b45/pkg/kubelet/config/config.go#L327-L337

One of two conversion/validation should be removed, and some of them should be simplified.

**Comment by dixudx** [comment]
@yujuhong If no one is working on this, I will take it.
