### ISSUE TITLE
New Federation API Resource for ClusterDaemonSets

### ISSUE THREAD

**Issue by nutchalum** [kubernetes/kubernetes#53178]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
I want a to have a new federation api resource _**ClusterDaemonSets**_

**What you expected to happen**:
This works a little like **_DemonSets_** resource.
_**DemonSets**_ makes sure every nodes must have a pod running in it.
_**ClusterDaemonSets**_ makes sure every clusters must have a pod running in it.

For example
Every cluster must has a kubernetes-dashboard.
I want to make sure there's only one (or more) dashboard **per cluster**
I can do that by using federation feature and create a Deployment and then scaling it out.
However, If one cluster is down, It'll try to make a pod in other cluster instead.
I want a resource to make sure there's only **one or more per cluster**
And if the cluster is gone, It won't try to pop up in other cluster

**Anything else we need to know?**:
Thank you.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#11.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
