### ISSUE TITLE
Consider re-organizing `kubelet.cm` package into multiple sub-dirs

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#53170]
We have shipped many features in `kubelet.cm` with plenty of files. I would suggest re-org `kubelet.cm` into multiple sub-folders like this:

```
kubelet
- cm
   - cpumanager
   - cpuset
   - cgoupmanager
   - containermanager
   - deviceplugin
   - nodecontainer
   - podcontainer
   - qoscontainer
   - helpers
   - util
   - types.go
```

@vishh  @derekwaynecarr Make sense to you?

**Comment by dolftax** [comment]
@resouer I'm working on this.

**Comment by resouer** [comment]
@dolftax Please note that the other files I did not mentioned belong to existing folders. For example, `containermanager`.

**Comment by resouer** [comment]
@kubernetes/sig-node-pr-reviews Please help to confirm if this refactor is worthy.

@dolftax Please keep a eye on this issue.

**Comment by derekwaynecarr** [comment]
If you have a PR or branch I can look at, I am +1 on cleaning up the structure.

**Comment by derekwaynecarr** [comment]
I cant tell what is a folder or not a folder in this hierarchy, so a branch is probably the best thing I can look at to know what is proposed.

**Comment by resouer** [comment]
@derekwaynecarr Thanks for quick response.

@dolftax Please work out a PR with `[WIP]` in the title for further discussion.

**Comment by dolftax** [comment]
@resouer Working on it.

**Comment by dchen1107** [comment]
Thanks for taking the task to clean up the code structure, and am looking forward to reviewing your pr. But I am not sure what you proposed above is the right sub-dirs structure.

**Comment by dolftax** [comment]
Sure. Will discuss over the PR. That would be better.

**Comment by resouer** [comment]
@dchen1107 Just a rough idea, we can move to @dolftax 's PR for further discussion later.

@dolftax I think you can add a sub-dirs structure in the description of the PR, it would be helpful.

**Comment by dolftax** [comment]
@resouer @dchen1107 Let me know if I'm headed in the right direction. Read comments on the state of the PR here - https://github.com/kubernetes/kubernetes/pull/53258#issue-261693727
