### ISSUE TITLE
Kubectl binary execute worng

### ISSUE THREAD

**Issue by kweisamx** [kubernetes/kubernetes#53180]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind bug

**What happened**:
When I get the kubectl binary with
`curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/darwin/amd64/kubectl
`
from the document [doc](https://kubernetes.io/docs/tasks/tools/install-kubectl/)

I do the step and execute the binary get wrong with
`bash: /usr/local/bin/kubectl: cannot execute binary file: Exec format error`

**What you expected to happen**:
it work that I can controller cluster

**Environment**:
- OS (e.g. from /etc/os-release):Linux Mint 18 (Ubuntu16.04)
- Kernel (e.g. `uname -a`): x86_64 x86_64 x86_64 GNU/Linux

Thanks

**Comment by zjj2wry** [comment]
what your system? seems you download darwin kubectl

**Comment by kweisamx** [comment]
I use the Linux Mint 18.3, but the kernel is the same like Ubuntu 16.04

**Comment by zjj2wry** [comment]
you should download a linux kubectl instead of mac.

**Comment by kweisamx** [comment]
oops!
That my fault ,thank you!

**Comment by seemacalibrecode** [comment]
Unlink kubectl using "rm '/usr/local/bin/kubectl'
and then link again using "brew link kubernetes-cli"

This worked for me on Mac.

If you want to install freshly on mac, use "brew install kubectl"

**Comment by piedepoy** [comment]
wow, I searchin and you help me.! thanks @seemacalibrecode

**Comment by Nethminiromina** [comment]
> Unlink kubectl using "rm '/usr/local/bin/kubectl'
> and then link again using "brew link kubernetes-cli"
> 
> This worked for me on Mac.
> 
> If you want to install freshly on mac, use "brew install kubectl"

Life saver. Thank you @seemacalibrecode

**Comment by spatilmoz** [comment]
always happen to run into this issue since i installed cloud sdk in the incorrect directory. kubectl is part of Google cloud SDK install (need not be done separately ) in case you happen to install kubectl outside of SDK use brew install 
@seemacalibrecode thats the perfect solution 👍

**Comment by dims** [comment]
@spatilmoz do you think we need to update the docs? https://kubernetes.io/docs/tasks/tools/install-kubectl/ i do see the option for using `brew` here https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-homebrew-on-macos

**Comment by spatilmoz** [comment]
yeah the documentation has it already @dims. if curl doesnt work then brew could be used. Thanks

**Comment by AmirAliSoftwareEngineer** [comment]
@seemacalibrecode  Hi there, I'm having an  issue with an install kubectl in MacBook Pro M2 

I got an error while running  brew link kubernetes-cli on ubuntu 


looking forward to your response

**Comment by etoilestar** [comment]
hello. I have the same problem, and my system is aarch64 with linux, how to install this software?

**Comment by Srinathsj17** [comment]
My system is ubuntu, amd64 .,same "cant exec binary" error. Any suggestion.,

 Tried different packages and check with KUBECTL.CHECKSUM and the status is ok.

Any suggestions

**Comment by aqiao** [comment]
> My system is ubuntu, amd64 .,same "cant exec binary" error. Any suggestion.,
> 
> Tried different packages and check with KUBECTL.CHECKSUM and the status is ok.
> 
> Any suggestions

Any update on this?
