### ISSUE TITLE
how to  resize tty by k8sapi

### ISSUE THREAD

**Issue by merakdu** [kubernetes/kubernetes#53199]
how to  resize tty by k8sapi,i can not find the rezie api,how to resize it

**Comment by ncdc** [comment]
@merakdu assuming you want to do this via an interactive exec or attach session, take a look at `pkg/kubectl/cmd/exec.go`, specifically the part that calls `t.MonitorSize()` and where the `sizeQueue` is passed to `p.Executor.Execute()`.

**Comment by merakdu** [comment]
thank you,i miss the sizequeue inStreamOptions.
