### ISSUE TITLE
Environment variables containing colon not allowed

### ISSUE THREAD

**Issue by MortenChristiansen** [kubernetes/kubernetes#53201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Problem:**
Kubernetes does not support `:` in environment variables. I can see that the subject has recently been discussed in [PR #48986](https://github.com/kubernetes/kubernetes/pull/48986). .NET Core uses `:` to replace config variables as mentioned in [this comment](https://github.com/kubernetes/kubernetes/pull/48986#issuecomment-318628326). The limitation in kubernetes requires me to perform some ugly hacks to override the config values.

**Proposed Solution:**
I'm in favor of the sentiment that kubernetes should not censor environment variables at all, but specifically I would like `:` to be allowed.

**Comment by MortenChristiansen** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by mattfarina** [comment]
Is the ask here to just support `:` or all characters allowed in Windows Environment Variables?

I ask because if I read the docs right I can do...

```
C:\>set _(){}[]$*+-\/"#',;.@!?=xyz

C:\>echo %_(){}[]$*+-\/"#',;.@!?%
xyz
```

**Comment by MortenChristiansen** [comment]
For my specific use case I need `:`. However, my opinion is that Kubernetes should not in any way limit which environment variable names you can use, since it cannot know what an application might need. Since  people cannot always choose their own variable names, it can be blocking for Kubernetes adoption. Whether I hit a new character I need "unlocked" tomorrow I do not know, but today the `:` will allow me work with .NET application settings as they are intended. Of course there may be any number of important concerns of which I am unaware so I leave the choice to greater minds than my own :)

**Comment by ryan-peachey-seon** [comment]
Hi, I have encountered this limitation as well.  Our apps were initially developed on windows, and use asp.net core for running them in linux now.  But the asp.net libraries create environment variables that include `:`.

**Comment by alahijani** [comment]
For .Net Core, the current (ugly) workaround is to use double underscores, like `Logging__LogLevel__Default` instead of `Logging:LogLevel:Default`.

It's documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?tabs=basicconfiguration#simple-configuration).

**Comment by bsteciuk** [comment]
FYI, I've started work on this issue, limited to just allowing the ':' character in environment variables for now.

**Comment by kow3ns** [comment]
I don't think we should do this. In Linux ":" is a path separator and completely invalid to use in an POSIX environment variable name. In .NET Core you use "__" in place of ":" in order get the desired configuration functionality to work as documented. I don't see why we should support non-portable naming. This will allow for manifests that only work in windows.

**Comment by michmike** [comment]
Given that we will not implement this issue, @bsteciuk  please update the getting started guide for windows to include this workaround for environment variables. thanks!

**Comment by bgrant0607** [comment]
I agree with double underscores:
https://stackoverflow.com/questions/40094998/asp-net-core-environment-variable-colon-in-linux

**Comment by thockin** [comment]
ACTUALLY, : is a valid character in POSIX.  All It says about env variables names (AFAICT) is:

`names shall not contain the character '='`

It specifies the names that POSIX tools can use, but does not restrict non-POSIX names at all.

Most *shells* do not support all of the punctuation characters, but C `setenv()` does:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
        int r = setenv("foo:bar", "value", 1);
        if (r != 0) {
                printf("failed to setenv\n");
                exit(1);
        }
        char *s = getenv("foo:bar");
        printf("getenv = %s\n", s);
}
```

(BTW, it took me a long time to make that compile because my fingers are used to Go now :)

**Comment by liggitt** [comment]
There are now multiple PRs in-progress trying to address this:
* https://github.com/kubernetes/kubernetes/pull/69415 (allow all characters except `=`, stale)
* https://github.com/kubernetes/kubernetes/pull/78910 (allow `:` only)
* https://github.com/kubernetes/kubernetes/pull/83032 (allow all characters except `=`)

Let's agree here on what we will do, then pick one PR to focus on implementing that.

First, there was a thread at https://github.com/kubernetes/kubernetes/pull/69415#issuecomment-438832067 expressing concern about expanding to all characters. Hoisting here:

@smarterclayton:
> Going from a strict set to “everything” is scary because we have no way to take that back once it’s part of the public API. I’d rather continue to selectively add things.

@jbeda:
> To echo what @smarterclayton is saying -- it feels to me like this is an easy place for us to introduce security vulnerabilities depending on how we set or pass these things down. I don't have anything concrete in mind but env variables are scary from a security PoV.

@thockin:

> Those security concerns are about how env vars are used and not about the shape/form of them.
> 
> This PR is exclusively about the shape/form.
> 
> I don't think it is useful of friendly to force people to PR each new character we want to support. Every time we have this incompatible-potential event. We'd do better to follow POSIX.
> 
> Now, that said, the RIGHT answer is to do OS-dependent validation, but we don't know the target OS at this point, so maybe we should validate the intersection of OSes? But that means adding a new OS could restrict the allowed-set, which is verboten. That seems unlikely.
> 
> Kubelet ultimately has to defend against bad pods, so it should probably be Kubelet that has final say in validating and rejecting (or omitting) bad env vars. At that point, the only character that seems universally disallowed is `=`. POSIX has a list of compatible characters (all ASCII), which includes control characters. If we feel the need to limit it to printable characters, I could live with that.
> 
> E.g. `unicode.IsPrint(r) && r < unicode.MaxASCII`. We can debate `IsPrint()` vs `IsGraphic()`, for which the delta seems to be tabs.
> 
> That makes it not "everything" but a broader starting point.


Second, if we relax validation, we need to phase it in over two releases, as described at https://github.com/kubernetes/kubernetes/pull/69415#issuecomment-461094828:

> In version X (currently v1.17):
> 
> 1. handle the expanded values, and tolerate persisted objects with the expanded values:
>    1a: update validation to validate the expanded values
>    1b: update consumers of the field to handle the expanded values
>    1c: allow an update of an object already using the expanded values to continue using them
> 2. prevent new use of the expanded values:
>    2a: prevent creation of a new object using the expanded values
>    2b: prevent an update of an object not yet using the expanded values from starting to use them
> 
> In some later version, the restrictions on create and update (2a,2b) can be removed.
> 
> * This should be done no earlier than X+1 (currently v1.18, so a skewed HA control plane does not consider persisted data invalid, and single version control plane rollback is safe).
> * This could require a longer waiting period, depending on the consumers that were updated in 1a, what behavior they had prior to being updated, and what level of skew is supported.
>   
>   * Did they skip the new data in a safe way? (e.g. not set the new envvar)
>   * Did they skip the new data in an unsafe way? (e.g. format a volume as a filesystem instead of a block device... if so, this is probably a sign the API change is not a safe one to make at all)
>   * Did they hard fail? Could require waiting until the oldest supported version of the consumer is version X (when the new data was handled), or could be the desired behavior (block incorrect use of objects containing the new data)
> 
> This is the same process we have to follow when allowing a new enum value (e.g. adding "SCTP" as a valid port protocol).
> 
> In this case, it appears kubelets do not validate envvar names coming from the API, and only warn on invalid envvar names resulting from secret/configmap -> envvar mappings. That means we could relax validation in 1.17, and remove create/update restrictions in 1.18.

**Comment by thockin** [comment]
I remain in favor of expanding it once and for all.  I simply have not had time/impetus to pursue it.

I do wonder if we have made our own lives extra complicated by overly-difficult compat rules that have little or no meaningful impact.

E.g. Adding an enum value should probably be something that is explicitly allowed, and client-side validators should warn but allow overrides (or validate based on openAPI, and enumerate there).  That way, we don't need 2 releases.

E.g. Client-side validation of regex-ish values is of dubious value compared to the pain it incurs.  Could we simply say "don't do that" and assert that expanding validation is allowed and considered compatible?

To do anything, we'd need to respect existing rules while we transition, so it's unlikely to help THIS case.

**Comment by liggitt** [comment]
> I do wonder if we have made our own lives extra complicated by overly-difficult compat rules that have little or no meaningful impact.

The two-release rollout outlines above is for server-side validation, not client-side (for skewed clusters and rollback compatibility, which are very impactful)

**Comment by liggitt** [comment]
I agree client-side validation of API data as duplication of the API server's job is not desired/recommended. 

For API objects used to store data for consumption (configmaps, secrets, envvars, etc), my main concern is how consumers of those values will handle expanded value spaces (we don't know if they're being used in file names, in database columns that can only hold ascii characters, etc). For envvars, something like omitting unprintable/control characters seems sensible.

**Comment by hpandeycodeit** [comment]
@liggitt Can we say that following are the remaining points/issues that need to be discussed before we proceed further: 

1. Whether to roll out the changes in a single release or 2 releases and The two-release rollout is for server-side validation and not for the client-side. 
2. How consumers will handle expanded value spaces.

**Comment by liggitt** [comment]
> Can we say that following are the remaining points/issues that need to be discussed before we proceed further:
> 1. Whether to roll out the changes in a single release or 2 releases

I don't think there's a lot to discuss there. Loosening validation in a single release breaks multi-server upgrade and single-version rollback scenarios. From my perspective, it must be rolled out over 2 releases at minimum.

> 2. How consumers will handle expanded value spaces.

I think that is the primary open question, and would inform what bounds we placed on the values (whitespace, control characters, unprintable characters, etc)

**Comment by hpandeycodeit** [comment]
@liggitt Do you think the PR #83032 can be reviewed with the above open question?

**Comment by liggitt** [comment]
> Do you think the PR #83032 can be reviewed with the above open question?

We can queue up a review for it. @thockin / @smarterclayton, either of you available to look at that?

The things I would expect to see:
* A feature gate controlling the loosening of the envvar name validation, initially in alpha state and defaulting to false
* Two sets of validation logic for envvar names:
  * Current validation
  * Relaxed validation
* Everywhere we validate envvar names in API objects, plumbing a parameter whether we want the strict or relaxed validation
  * At the top level validation method when validating API create requests, use the strict validation if the feature gate is off
  * At the top level validation method when validating API update requests, use the strict validation if the feature gate is off and the old object passes strict envvar name validation
  * Unit tests around this validation, testing every combination of create/update, old object with/without relaxed envvar values, feature gate enabled/disabled
* e2e tests demonstrating we can actually construct an environment with envvar names at the edges of what we support and it makes it into the container successfully (envvar names containing newlines/whitespace, unprintable characters, multi-byte characters, "difficult" characters like `'"*?;/\()&$`, etc)

**Comment by mohag** [comment]
/remove-lifecycle rotten

The issue is still present

**Comment by mohag** [comment]
/remove-lifecycle stale

Still present

**Comment by mohag** [comment]
/remove-lifecycle stale

Still present

**Comment by marosset** [comment]
cc @immuzz is this something we can get the .NET team to look at?
We may be able to fix the .NET use cases (but obviously this would not address all cases)

**Comment by mohag** [comment]
/remove-lifecycle rotten

Still present

**Comment by mohag** [comment]
/remove-lifecycle rotten

Still present

**Comment by mohag** [comment]
/remove-lifecycle stale

Still present

**Comment by mohag** [comment]
/remove-lifecycle rotten

Pandering to the robotic overlords

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/53201#issuecomment-571254145 is the latest status.

If someone wants to do this, which I support, that's your roadmap.  This warrants a KEP, albeit a small one.   I wish I had the time to tackle all of these myself, but I just don't.

This should not be a very hard one.

**Comment by alculquicondor** [comment]
/remove-sig apps
/sig node
?

**Comment by HirazawaUi** [comment]
/assign 
I will provide a mini KEP for it if no one is working on it yet
