### ISSUE TITLE
Bug in "validates resource limits of pods that are allowed to run"

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#53216]
[This](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/predicates.go#L233) is the test.  It uses cached results from listing the nodes, and they are inaccurate by the time the test runs.  In particular, the cached size is usually the full size of the machine (2000 millicores in my tests), but by the time the test runs, the kubelet has reduced the machine size to 1930 millicores (to account for overhead), but the test still uses the stale sizes to compute how many 500 millicore pods will fit.  (@dchen1107 will recognize this problem.)

This often works fine, because we are only counting up an integer number of 500 millicore pods, and you have to "get lucky" for those 70 millicores to make the difference on one machine.  But sometimes they do make a difference, and I seem to be able to trigger this bug easily.

_Feel free to stop reading here_

I will fix the test and backport it to 1.7.  This raises the question of how to manage "releasing" upgrades to conformance definitions (going forward.  I don't expect us to fix that here).  We don't need to release 1.7.7 just to get this fix, but we may want to issue fresh binaries as the definition of "1.7 conformance" has been corrected.  @erictune mentioned this to me the other day.  One simple idea is to continue using the release-1.7 branch, but revise the conformance definitions separately, and with numbers that look different enough that they can't be confused with kubernetes point releases.  Something like `c1.7 rev 0`, `c1.7 rev 1` (`c` for conformance?).

/sig scheduling
/assign

**Comment by mml** [comment]
cc @bsalamat

**Comment by bsalamat** [comment]
Thanks @mml for looking into it. I was also working on this in parallel yesterday and [my PR](https://github.com/kubernetes/kubernetes/pull/53169) should address the problem that you have observed as well. The new code creates one pod per node and does not use "all" the CPU on a node. It uses most of the CPU and leaves some room for overheads. So, I believe it will address the problem.

**Comment by mml** [comment]
Closing this as a dup of #53066
