### ISSUE TITLE
[CLEANUP] Service controller should not import node label constants from kubeadm

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#53217]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Ref https://github.com/kubernetes/kubernetes/pull/44745, https://github.com/kubernetes/kubernetes/pull/53146.

service_controller pacakges imports couple node labels constants from kubeadm, which will eventually be moved to https://github.com/kubernetes/kubeadm.
https://github.com/kubernetes/kubernetes/blob/422f5e37b9b45706cac1575fad648e96ba0ce2e7/pkg/controller/service/service_controller.go#L40
https://github.com/kubernetes/kubernetes/blob/422f5e37b9b45706cac1575fad648e96ba0ce2e7/pkg/controller/service/service_controller.go#L595-L603

**What you expected to happen**:
k8s itself should have well-known-labels defined as API or types and service controller should import those instead.

The well-known-labels works are tracked/being discussed by https://github.com/kubernetes/kubernetes/pull/39112.

**Anything else we need to know?**:
This may not be actionable immediately but is something we should cleanup eventually.

**Comment by luxas** [comment]
/assign @dims 
this was fixed, right?

**Comment by dims** [comment]
yes, fixed in https://github.com/kubernetes/kubernetes/commit/a4574bbb042402974a0269651ca42bc9e8137c72

/close
