### ISSUE TITLE
Docker version not parsed properly. (17.06.1-ce)

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kubernetes#53215]
/kind bug

**What happened**:
I haven't seen any ill effects of this yet, but they may be subtle and I haven't had a chance to rundown the codepaths.

Error in my 1.7.6 kubelet logs:
Unable to parse docker version "17.06.1-ce": illegal zero-prefixed version component "06" in "17.06.1-ce"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Install a kubelet on a machine with 17.06.1-ce docker

**Anything else we need to know?**:
nada
**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.6
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1548.0.0
VERSION_ID=1548.0.0
BUILD_ID=2017-09-27-0012
PRETTY_NAME="Container Linux by CoreOS 1548.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux ip-172-16-203-31 4.13.3-coreos-r1 #1 SMP Tue Sep 26 23:51:59 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux

- Install tools:
- Others:

**Comment by yujuhong** [comment]
kubelet should only parse the docker API version, not the docker engine version.
What's the output of `docker version`?

**Comment by dims** [comment]
@SleepyBrett yes please show us your `docker version` as @yujuhong mentioned. 

Also fyi, looking at the code in 1.7.x branch, a couple of validations are skipped if we are not able to parser the docker api version, see here:
https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/kubelet/dockershim/cm/container_manager_linux.go#L94

**Comment by dims** [comment]
/close

Please reopen if needed
