### ISSUE TITLE
kubectl provides a way to find which RoleBinding/ClusterRoleBinding is related to a serviceAccount

### ISSUE THREAD

**Issue by flyer103** [kubernetes/kubernetes#53248]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind feature

**What happened**:
When I encounter a problem which is caused by no proper permissions, I want to find which RoleBinding/ClusterRoleBinding is related to the serviceAccount the Pod uses. But there's no simple way to do this without traversing all of the bindings.

**What you expected to happen**:
`kubectl` could provide a simple method to solve the above problem such as:

```shell
$ kubectl get rolebinding SERVICE_ACCOUNT_NAME POD
$ kubectl get clusterrolebinding SERVICE_ACCOUNT_NAME POD
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Related stackoverflow problems: [Is there a way to find the RoleBinding/ClusterRoleBinding related to a serviceAccount?](https://stackoverflow.com/questions/46482455/is-there-a-way-to-find-the-rolebinding-clusterrolebinding-related-to-a-serviceac)

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by flyer103** [comment]
@kubenetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
reverse-index APIs are not typically provided... you can locate this info from the existing API by filtering client-side:

```sh
$ kubectl get clusterrolebindings -o json | jq -r '
  .items[] | 
  select(
    .subjects // [] | .[] | 
    [.kind,.namespace,.name] == ["ServiceAccount","kube-system","node-controller"]
  ) |
  .metadata.name'

system:controller:node-controller

**Comment by weibeld** [comment]
You can display an overview of which ServiceAccounts the RoleBindings and ClusterRoleBindings reference with the following command:

~~~bash
kubectl get rolebindings,clusterrolebindings \
  --all-namespaces  \
  -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE ACCOUNTS:subjects[?(@.kind=="ServiceAccount")].name'
~~~

And then you could `grep` for the ServiceAccount you're looking for.

**Comment by weibeld** [comment]
There's also the [rbac-lookup](https://github.com/reactiveops/rbac-lookup) tool. It allows to display all the (Cluster)Roles and (Cluster)RoleBindings for subjects (users, ServiceAccounts, groups).

You can display all the (Cluster)Roles and (Cluster)RoleBindings for a specific ServiceAccount like this:

~~~bash
rbac-lookup NAME -k serviceaccount -o wide
~~~

**Comment by CermakM** [comment]
For shell users [this](https://gist.github.com/CermakM/ad343a1dece01757e6a8719b9a956cce) simple function added to `~/.config/fish/config.fish` kinda does the trick

**Comment by zimmertr** [comment]
Using @weibeld's solution [here](https://github.com/kubernetes/kubernetes/issues/53248#issuecomment-480036473), we can also create a shell function ourselves to effectively replicate the feature we desire. For example:

```
$> tail -n 6 ~/.bashrc
function get_bindings(){

    kubectl get rolebindings,clusterrolebindings \
      -n $1 \
      -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind=="ServiceAccount")].name' | grep $2
}
```
```
$> get_bindings "kubernetes-dashboard" "tj"
ClusterRoleBinding   <none>                 tj                                                     tj
```

This function accepts two arguments, one Namespace and one ServiceAccount. If I search the `kubernetes-dashboard` namespace for my personal ClusterAdmin ServiceAccount `tj`, you will see the requisite `ClusterRoleBinding` returned.

Hope this helps!

Hope this helps.

**Comment by clowa** [comment]
> You can get an overview of all the (Cluster)RoleBindings and the ServiceAccount(s) they reference with the following command:
> 
> ```shell
> kubectl get rolebindings,clusterrolebindings \
>   --all-namespaces  \
>   -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind=="ServiceAccount")].name'
> ```
> 
> And then you could `grep` or `awk` for the ServiceAccount you're looking for.

If @weibeld's example didn't work for you and you got the message `error: unrecognized identifier ServiceAccount`, you just need to escape the `"` via `\"`.
This should work:
```bash
kubectl get rolebindings,clusterrolebindings `
  --all-namespaces  `
  -o custom-columns='KIND:kind,NAMESPACE:metadata.namespace,NAME:metadata.name,SERVICE_ACCOUNTS:subjects[?(@.kind==\"ServiceAccount\")].name'
``` 

Thanks to everyone who added his ideas and solutions in this issue. 🚀

**Comment by kushalShukla-web** [comment]
Is this issue still open
