### ISSUE TITLE
Running of Initializers and GenericAdmissionWebhook seem to be out of order.

### ISSUE THREAD

**Issue by lumjjb** [kubernetes/kubernetes#53243]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
With `Initializers` and `GenericAdmissionWebhook` enabled. When an initializer for a `pod` was registered and a webhook registered for operations `CREATE, UPDATE` for  resources `pods` was created.
Upon creation of a `pod`, the webhook was provided the action to allow/deny the pod before the initializer was allowed to initialized the pod.

**What you expected to happen**:

According to: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/admission_control_extension.md

After initialization or on any update, these hooks would be invoked in parallel against the remote servers and any rejection would reject the mutation. This indicates that upon a creation of a resource of which an initializer is registered to initialize and a webhook registered to hook, the initializer should complete it's initialization before the webhook looks at the pod spec.

**How to reproduce it (as minimally and precisely as possible)**:
Ran a minikube cluster with the following config:
```
minikube start \
    --extra-config=apiserver.Admission.PluginNames="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,GenericAdmissionWebhook" \
    --kubernetes-version=v1.7.5
```
Create a sample initializer for a pod, create a sample GenericAdmissionWebhook for a pod to hook creation, and always deny. Create a pod, and the pod should be denied. Logs of the initializer should show that it did not initialize the pod.

```➜  server17 git:(master) ✗ kubectl get InitializerConfiguration -o yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1alpha1
  initializers:
  - failurePolicy: Ignore
    name: imgpolicy.initializer.kubernetes.io
    rules:
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      resources:
      - pods
  kind: InitializerConfiguration
  metadata:
    creationTimestamp: 2017-09-29T04:24:25Z
    generation: 1
    name: imgpolicy
    namespace: ""
    resourceVersion: "745"
    selfLink: /apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations/imgpolicy
    uid: 136fb4db-a4ce-11e7-9a83-0800273c45a1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

➜  server17 git:(master) ✗ kubectl get ExternalAdmissionHookConfiguration -o yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1alpha1
  externalAdmissionHooks:
  - clientConfig:
      caBundle: <<REMOVED>>
      service:
        name: webhook
        namespace: default
    failurePolicy: Ignore
    name: pod-image.k8s.io
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  kind: ExternalAdmissionHookConfiguration
  metadata:
    creationTimestamp: 2017-09-29T04:32:24Z
    generation: 1
    name: example-config
    namespace: ""
    resourceVersion: "1433"
    selfLink: /apis/admissionregistration.k8s.io/v1alpha1/externaladmissionhookconfigurations/example-config
    uid: 30e7c69a-a4cf-11e7-b8dc-0800273c45a1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

minikube version: v0.22.2

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-18T20:30:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

minikube 1.7.5 cluster, 1.7.5

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Mac OSX
- Kernel (e.g. `uname -a`): Darwin Kernel Version 15.6.0
- Install tools:
- Others:

**Comment by liggitt** [comment]
Admission (including webhook admission) gets to affect the initial object creation, prior to initializers acting on the object. That is working as designed. 

Initialization actually consists of a create, followed by multiple initializing updates. There is discussion about how admission should be called for those subsequent initializing updates in https://github.com/kubernetes/community/pull/1137/files, but the behavior on create is working as intended.
