### ISSUE TITLE
Introduce critical performance tests as (manually unblockable) post-submit blockers

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#53255]
As discussed in the release burndown meeting yesterday, here's a briefing of the issue:

Most of the folks (@smarterclayton, @liggitt, @jdumars, @gmarek and many from the release team) almost unanimously agreed with the requirement of post-submit blockers. Their absence is affecting us in multiple ways:

1.Release quality: We are shipping the release with a known performance regression violating our SLO (#51899) documented as a [known issue](https://github.com/kubernetes/features/blob/58315cc33c51f8f4d05364d80f0b66f5d980bad7/release-1.8/release-notes-draft.md#known-issues) - which would potentially leave some users unwilling to upgrade to 1.8. A proper fix to it was infeasible that close to the release, which wouldn't have been the case if we early-blocked on it. OTOH reverting the concerned PR would've also compromised us on release signal and kicked out a correctness fix from the release.

2.Eng productivity: We've spent multiple weeks of eng time to debug/fix the issues involved, complicated further by the fact that multiple of them got piled up due to lack of post blockers:
  - 2w of my time for running 2 rounds of bisection, debugging/fixing/studying code/logs (3 regressions - #52107 (node OOMs), #51899 (audit-log performance), #51899(kubelet-gc thundering herd))
  - 3-4d of @liggitt (senior member from RedHat) examining the issue, going through a PR diff storm, plotting some graphs, etc
  - 2w of folks from concerned SIGs combined (scalability, api-machinery, node, instrumentation) - involves debugging / PR fixes & reviews / issue reporting
  - 1w of release team's time combined (long burndown meeting(s) with multiple folks, slack discussions, triaging/understanding/documenting the regressions)

3.Release schedule: The release had to be pushed off by a day to resolve the issue and led to some chaos and discussion few hours before the release ETA.

Note that the proposal is not to block until the post-submit is fixed, but to block until we have a clear enough idea about the cause. We should then be able to unblock the queue (possibly manually) and work on the fix independently without needing to block further. This release is a clear example of how a little investment early on can reap huge benefits later.

cc @kubernetes/sig-release-members @kubernetes/sig-testing-feature-requests @dims @spiffxp

**Comment by shyamjvs** [comment]
Any thoughts/comments that you might have are more than welcome.

@jdumars It would be great if you could link to this issue from the release retrospective doc (if there's one).

**Comment by shyamjvs** [comment]
@krzyzacy Assigning it to you. Feel free to redirect as apt. Note that this is quite important.

**Comment by kargakis** [comment]
cc: @stevekuznetsov @spxtr @cjwagner

**Comment by jdumars** [comment]
This will be making an appearance in the retro for sure.

**Comment by krzyzacy** [comment]
@shyamjvs Is this around the same idea as https://github.com/kubernetes/test-infra/issues/4445? a few ideas:

- we had the idea which block the submit queue base on an issue 
- if the test is fast enough, we can run it as a postsubmit job, and which will provide clear signal for you to catch regressions

How about join our sig-testing meeting next Tue and we can talk about it?

**Comment by shyamjvs** [comment]
That one is different.. It's quite a fast one which we can potentially afford to run as a pre-submit and should help us catch few regressions.
However our releases are blocked on 5k-node job which often exposes issues that come up only at such scale (for e.g the ones we saw this release).

> we had the idea which block the submit queue base on an issue

That sounds reasonable, though I assume the workflow is going to be sth like:
(test failed) -> (issue created and potentially triaged) -> (SQ blocked on that issue, so it gets people's traction) -> (after looking into it, the submit-queue could be manually unblocked or kept blocked (if required) based on the build-cop's discretion)

> How about join our sig-testing meeting next Tue and we can talk about it?

Will try to dial in, can't commit at the moment though.

**Comment by krzyzacy** [comment]
@shyamjvs or we have daily community standups if you cannot make the weekly sig-testing meeting

**Comment by shyamjvs** [comment]
SG - Will join on one of the days (mon or tue) next week. Thanks.

**Comment by smarterclayton** [comment]
We may want to consider that prior to code freeze all signal needs to be
good, and that it's on the affected sigs to focus before code freeze that
any of the long pole post-submits are green.  No one felt the pain of the
post-submit until it was very late, which was too late.

**Comment by kargakis** [comment]
I know that testgrid is supposed to have notifications, maybe we could start spamming slack and/or email on poor results from a set of jobs until people take notice?

**Comment by cjwagner** [comment]
[Here](https://github.com/kubernetes/test-infra/tree/master/testgrid/config#email-alerts) is an explanation of how you can enable testgrid email alerts.

**Comment by shyamjvs** [comment]
@kargakis @cjwagner The issue here is not about getting alerts/notifications - we usually know when the tests start failing, especially because they're part of release-blocking suite. The real problem arises due to not blocking on those failures - as that allows for multiple regressions piling up on top of each other making debugging a nightmare, especially for such long-running tests (like we saw this release with 3 regressions, one on top of the other). It would've been much easier and productive to block on the failure and someone taking a quick look to identify the cause and unblock the queue immediately (without even needing to wait till the next run or the fix).

**Comment by kargakis** [comment]
I am not against blocking on postsubmits but we need community buy-in. Bring it up in the sig-testing call tomorrow?

**Comment by stevekuznetsov** [comment]
> It would've been much easier and productive to block on the failure 

@shyamjvs I believe in the past the benefit of blocking for N people that can actively work on fixing something was strongly outweighed by the detriment of blocking the queue for N*M others that were not affected by the issue, not able to fix it, etc. @smarterclayton can probably expand on that more. It seems like the entire k8s dev community needs to be on board for such a large change.

**Comment by shyamjvs** [comment]
Discussion in sig-testing sounds good. Let's talk about this further tomorrow.

**Comment by gmarek** [comment]
@stevekuznetsov - to be fair, k8s dev community was NOT on board with disabling post submit tests. We literally said that if we do that the thing that happened in 1.8 will happen for reasons already posted by @shyamjvs.

The question we need to answer is are we really willing to pay with system reliability for the *perceived* slowdown of development - no one is preventing anyone from working on fixed when merge queue is blocked. This is exactly what happens during the "code freeze", and it doesn't slow down the influx of fixes. It slows down the influx of new stuff that's not a fix if anything, but the question is whether it's a bad thing given the state of things.

It's not OK if some small group of people (this time it was mostly @shyamjvs and @liggitt if I'm not mistaken) pay the price for that, and spend weeks looking at logs and running experiments. IMO that's very far from a healthy environment.

**Comment by smarterclayton** [comment]
Putting the milestone approval label on because this is pretty important.

**Comment by shyamjvs** [comment]
Can we reach a reasonable consensus on this issue soon? It is affecting our release process/quality.

@wojtek-t - fyi

**Comment by krzyzacy** [comment]
hummm cc @cjwagner tide can block merge upon a certain issue right? If that's the case we just need to wait for enabling tide on the main repo. We can try on test-infra.

**Comment by cjwagner** [comment]
@krzyzacy I don't think that functionality has been implemented yet.

**Comment by shyamjvs** [comment]
@krzyzacy @cjwagner What's the plan of action here? Auto-filing an issue on failure and blocking SQ against it sounds like a good option. In any case, we need some mechanism to block on the failure (and it should be manually overridable).

**Comment by krzyzacy** [comment]
From technical point of view, maybe make tide block on some certain labels, and we can auto or manually apply the label. But we probably need to be obvious to tell people why merge is blocked. @cjwagner WDYT

**Comment by spiffxp** [comment]
Looking at the times posted in @shyamjvs's summary, I would like to know how blocking the submit queue would have shortened those times.  I have concerns that blocking the queue for durations of that length would have severely hampered our productivity and caused us to push the release out for much longer than a day.

**Comment by spiffxp** [comment]
I would prefer to see a policy of treating the release-*-blocking jobs as blockers to going through gates in the release process (e.g.: entering code freeze, cutting bits, existing code freeze).  If we cannot go through these gates in time, I would prefer to see the entire schedule shifted out by the delay, rather than treating the entirety of the remaining schedule as buffer to be eaten into.

**Comment by cjwagner** [comment]
@krzyzacy That plan sounds good to me. As discussed in a meeting, if we block by using a special label on issues, people can tell why the merge is blocked by searching github for open issues with that label just as Tide does. We can put links to that query in important places.

**Comment by shyamjvs** [comment]
>  I would like to know how blocking the submit queue would have shortened those times.

Blocking the SQ would've helped us in at least the following ways:
- we accumulated multiple regressions one on top of the other (listed in the PR description). This made debugging time much longer (and unpredictable) than what it would've been if we identified each of them on time. This brings me to the 2nd point..
- not blocking the SQ didn't put enough pressure on the issue for folks to start looking into it, until it was quite late (like @smarterclayton also said in https://github.com/kubernetes/kubernetes/issues/53255#issuecomment-333210985)

> I have concerns that blocking the queue for durations of that length would have severely hampered our productivity and caused us to push the release out for much longer than a day.

I'm not sure if that would've hampered the productivity severely. As I mentioned earlier, the block wouldn't be until the fix is rolled out and we have a green run, it would only be until someone (or a group of folks) look into what caused it (by taking a quick glance at the commit diff, or the logs, or if really really needed a handful of hours of bisection (but this probably can happen with the queue unblocked)). The key need here is to get traction on the issue ASAP, which only post-submit blockers can truly do imo :)

> If we cannot go through these gates in time, I would prefer to see the entire schedule shifted out by the delay, rather than treating the entirety of the remaining schedule as buffer to be eaten into.

I think a little investment early on can save lots of effort later on, as we saw in this release. By not having the blocker, we're essentially postponing solving the problem to a later point - by when it can get more complicated, more time to debug and more human effort involved (especially with performance regressions which can come from pretty much everywhere in the system).

**Comment by smarterclayton** [comment]
I would agree with the "little investment now can save lots of effort
later" - that's been shown to be the case for many of these performance
issues.  Even without blocking the queue, the desired outcome is ensuring
that early investment happens.  If there is opposition to blocking the
queue, are there suggestions on how to best incentivize the rapid triage in
event of failure?

**Comment by spiffxp** [comment]
If we make sure that tests actually stay green, we can use alerts to notify people when tests go from green to red, or from flaky to consistently failing.  SIG Testing has been working on e-mail based alerts from testgrid that would support this.

Part of what allows failures to sneak by is when they're red "but passing if you look at the logs."

**Comment by spiffxp** [comment]
https://k8s-testgrid.appspot.com/release-master-blocking#gce-scale-performance&width=20

This does not seem like a very good candidate to block the release.  It's passed once in the past 2 months.

https://k8s-testgrid.appspot.com/release-master-blocking#gce-scale-correctness&width=20

This has never passed.

**Comment by porridge** [comment]
On Tue, Oct 17, 2017 at 11:07 PM, Aaron Crickenberger <
notifications@github.com> wrote:

> https://k8s-testgrid.appspot.com/release-master-blocking#
> gce-scale-performance&width=20
>
> This does not seem like a very good candidate to block the release. It's
> passed once in the past 2 months.
>
> https://k8s-testgrid.appspot.com/release-master-blocking#
> gce-scale-correctness&width=20
>
> This has never passed.
>
FWIW, neither of these URLs work. Both just show "Unknown dashboard
release-master-blocking. Select a dashboard."

**Comment by fejta** [comment]
Some testgrid URLs changed this evening:
* https://k8s-testgrid.appspot.com/sig-scalability-gce-scale#gce-scale-performance&width=20
* https://k8s-testgrid.appspot.com/sig-scalability-gce-scale#gce-scale-correctness&width=20

**Comment by fejta** [comment]
Testgrid now supports alerting when a dashboard starts to fail: https://github.com/kubernetes/test-infra/tree/master/testgrid/config#email-alerts

**Comment by porridge** [comment]
Thanks! Sadly, the reason for most recent -correctness failure is not
viewable due to https://github.com/kubernetes/test-infra/issues/2580
Is there another way to see the logs?

**Comment by shyamjvs** [comment]
@porridge You should be able to access the logs directly using the gcs url - for e.g http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/19/

**Comment by dims** [comment]
@shyamjvs - is there any PR(s) for 1.9? (can we move/remove the milestone if not)

**Comment by krzyzacy** [comment]
I don't think that's gonna done before 1.9 - we haven't migrated k/k from submit-queue to tide yet, probably punt to next quarter.

/assign @cjwagner

**Comment by shyamjvs** [comment]
It's sad this hasn't been actioned this release. Let's ensure we have it for 1.10 at least.
@cjwagner I would be more than glad to discuss how to do this some time.

**Comment by spiffxp** [comment]
Per above discussion I kicked out of v1.9 milestone, we can add back in to v1.10 when we can guarantee commitment

**Comment by cjwagner** [comment]
I have a design doc to make Tide support merge blocking issues. PTAL: https://docs.google.com/document/d/11u0mbxXXi6AmSWxh_6jvg_ljJ7re8jxiqeyjcKcDSg0/edit#
Members of the `kubernetes-sig-testing` and `kubernetest-dev` google groups have access.

**Comment by shyamjvs** [comment]
/remove-lifecycle stale

I think with blocking scalability presubmits and some deflaking of large-scale performance jobs, we're now in [a decent shape](https://testgrid.k8s.io/sig-scalability-gce). We can probably hold this off, at least for now.

@wojtek-t - WDYT?

**Comment by wojtek-t** [comment]
Yes - it's not critical now.

**Comment by shyamjvs** [comment]
Thanks. Let's close this then.
