### ISSUE TITLE
Kubelet config flag --hairpin-mode=hairpin-veth no longer works as expected in k8s v1.7.4

### ISSUE THREAD

**Issue by DuncanSmith1126** [kubernetes/kubernetes#53269]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

@kubernetes/sig-Network-bugs

**What happened**:
After an in-place upgrade from kubelet 1.5.3 to 1.7.4 - pods that attempt to loadbalance to themselves via kubedns are unable to complete the request. The value of --hairpin-mode=hairpin-veth is seemingly ignored. 

**What you expected to happen**:
Pods that attempt to loadbalance to a service backed by itself should successful hairpin back around and the request should be successful. The --hairpin-mode=hairpin-veth flag should be respected, and hairpinning should be enabled on all created veths. 

**How to reproduce it (as minimally and precisely as possible)**:
With kubectl v1.7.4 pointed to a cluster configured to run kubelet 1.7.4 with the hairpin-mode=hairpin-veth flag and no value set for the --network-plugin flag
Deploy up some pods PodA and PodB and expose some port in PodA - have it respond to every request with some kind of ack
Deploy up some service that points to PodA
From PodB - send a request to the service and ensure you get an Ack from PodA
From PodA - send a request to the service - this will fail

**Anything else we need to know?**:

I've done enough digging to figure out exactly why this is happening. In our configuration, we don't rely on any CNI plugins to configure our veths. Previously, in 1.5.x - kubelet would use the `--hairpin-mode=hairpin-veth` flag to determine if the veth interfaces would have the hairpin configured. In 1.7.4 - this flag is dropped and not touched in the no-op plugin case after https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L205 . In the kubelet logs I do see some interesting lines - namely 

`Sep 29 18:53:19 *my node*.net hyperkube[18658]: W0929 18:53:19.924036   18658 docker_sandbox.go:342] failed to read pod IP from plugin/docker: Couldn't find network status for default/hairpin-bc3f8cdf7e6b-376814036-v8src through plugin: invalid network status for`

I'm invoking kubelet with 

root     18658  2.1  1.3 490740 76828 ?        Ssl  18:53   0:44 /usr/bin/hyperkube kubelet --logtostderr=true --v=2 --api-servers=https://<SOME_NODE>.net:8000 --address=0.0.0.0 --allow-privileged=true --node-labels=pool=piabpool,etcd_installed=true,master=true --anonymous-auth=false --client-ca-file=/data/certs/ca.crt --tls-cert-file=/data/certs/<SOME_NODE>.net.crt --tls-private-key-file=/data/certs/<SOME_NODE>.net.key --cgroup-driver=systemd --kubeconfig /etc/kubernetes/kubeconfig --node-ip=<SOME IP> --max-pods=110 --pod-infra-container-image gcr.io/google_containers/pause-amd64:3.0 --hairpin-mode=hairpin-veth --pod-manifest-path=/etc/kubernetes/kubelet.d

This behavior seems to be a regression from 1.5 - and it looks like I'm not the first person to run into some veth oriented confusion. 

See https://github.com/kubernetes/kubernetes/issues/45790 or https://github.com/kubernetes/kubernetes.github.io/pull/5599 for slightly more context. 

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: Private
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
...
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): 3.10.0-514.21.1.el7.x86_64
- Install tools: yum
- Others:

**Comment by DuncanSmith1126** [comment]
@kubernetes/sig-networking-bug

**Comment by DuncanSmith1126** [comment]
@kubernetes/sig-Network-bugs

**Comment by krmayankk** [comment]
@thockin

**Comment by liggitt** [comment]
is this different from #45790?

**Comment by DuncanSmith1126** [comment]
Related - but not quite the same. In that issue there's an actual CNI plugin being invoked by k8s, and since there was no standard for CNI Plugins and how they deal with hairpin - the issue was punted to containernetworking/cni#476 and closed.

In this case, since no CNI Plugins are specified in the kubelet command line, k8s defaults to a minimal behavior - NoopNetworkPlugin which sets the net/bridge/bridge-nf-call-iptables to 1 - and the --hairpin-mode flag gets dropped. This was not the case in 1.5.

**Comment by ravilr** [comment]
Looks like this is broken since 1.6 release for setups not using any network plugin.

**Comment by dcbw** [comment]
It looks like this was changed with the switchover from dockertools -> dockershim.  The kube docker runtime used to set this, but no longer does.  It's currently up to the network plugin (or if not using network plugins, whatever is configuring your networking) to do this.

**Comment by DuncanSmith1126** [comment]
Yeah - I kinda figured that was the direction this was headed in. Docs should be updated to reflect this - or a warning in the logs when the kubelet param is dropped.
