### ISSUE TITLE
kubectl top pod reports invalid memory usage

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#53265]
**What happened**:

    kubectl top pod

Report memory usage half of what should be.

`docker stats` and Google Stackdriver both report my container to be about 100 MB memory but `kubectl top pod` report only 40 MB is used.

It's hard for me to know which is accurate and it may be dependant on what "accurate" means. I know that `free` and `top` are not cgroup aware and will report system-wide memory usage and not just the container.

Note: My goal is to accurately see memory usage to know what I should put as kubernetes memory requirement.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.6 (client v1.7.6 as well)
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): gke

**Comment by darkprisco** [comment]
so, I didn't get if you solved or not.. I have the same problem. 
Please let me know.
Tks
