### ISSUE TITLE
Azure LB should support a resource id reference for public IP addresses...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#53274]
Currently the Azure load balancer assumes that a Public IP address is in the same resource group as the cluster. This is not necessarily true in all environments, in addition to accepting a Public IP, we should allow an annotation to the `Service` object that indicates what resource group the IP is present in.

**Comment by itowlson** [comment]
To clarify the requirement: this is in the scenario where a service is of type LoadBalancer, _and_ the `loadBalancerIP` has been set in the service spec.  Per the "Special notes for Azure" at https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer, we would still expect the IP address to be given as an IP address, _not_ a resource ID, and the user must still create the static IP address first; this issue asks only that relax the restriction that the IP address resource be in the same resource group as the cluster.  @brendandburns please let me know if I've misunderstood!
