### ISSUE TITLE
Broken doc link

### ISSUE THREAD

**Issue by steren** [kubernetes/kubernetes#53279]
404 on https://kubernetes.io/v1.0/docs/user-guide/kubeconfig-file/

I got here my googling [kubernetes config]

**Comment by FlorianOnmyown** [comment]
@steren the documentation you are looking for is now accessible here: https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

Unfortunately, I think that we will have to wait for Google bots to rescan the site to correct this behaviour.

**Comment by steren** [comment]
Could a redirect be possible? Yes Google will rescan, bit what about every
other page that deep links to this page?

**Comment by FlorianOnmyown** [comment]
I am not sure if this is possible.
