### ISSUE TITLE
TLS-bootstrapped kubelet loses client certs after reboot, node stays on NotReady status

### ISSUE THREAD

**Issue by hubo2005** [kubernetes/kubernetes#53288]
Updated description:

## Problem
The default `--cert-dir` path points to a transient location (`/var/run/kubernetes`) that is removed on reboot. The default `--kubeconfig` location points to a persistent location. This means that after a reboot, a kubelet can be stuck with configuration that is missing credentials needed to reach the API server.

## Solution
* `kubeadm` users:
  * Updated kubeadm packages (deb `1.8.0-01`, rpm `1.8.0-1`) have been released with a config change that prevents this issue from occurring. 
  * If you have a node that is already in this state:
      1. Verify this is the issue you are experiencing:
          * the `/etc/kubernetes/kubelet.conf` file references `/var/run/kubernetes/kubelet-client.crt`
          * the `/var/run/kubernetes/kubelet-client.crt` file does not exist
      2. update the kubeadm package
      3. remove the `/etc/kubernetes/kubelet.conf` file
      4. restart the kubelet to allow it to bootstrap
* Custom deployments should set the `kubelet` `--cert-dir` flag to a non-transient location, like `--cert-dir=/var/lib/kubelet/pki`

## Details

In 1.8.0, TLS bootstrapping (using `--bootstrap-kubeconfig`) writes certs to the `--cert-dir` path and a kubeconfig referencing those certs to the `--kubeconfig` path. That means that on reboot:
* the client certs are removed
* `--bootstrap-kubeconfig` is ignored, because `--kubeconfig` exists
* `--kubeconfig` cannot be loaded, which causes the kubelet to log an error (but not exit)

In 1.7, TLS bootstrapping inlined the certificates in the written `--kubeconfig`, which sidestepped the issue with the `--cert-dir` getting removed.

Original description: 

/sig-autoscaling
/kind bug

**What happened**:
 I have 1 master(174) and 2 nodes(175,171). I am restarting one of the node(171), when it came back, the kubelet on this server does not get started with errors:

> Sep 30 19:54:46 kube171 kubelet[2458]: W0930 19:54:46.526741    2458 server.go:381] invalid kubeconfig: invalid configuration: [unable to read client-cert /var/run/kubernetes/kubelet-client.crt for default-auth due to open /var/run/kubernetes/kubelet-client.crt: no such file or directory, unable to read client-key /var/run/kubernetes/kubelet-client.key for default-auth due to open /var/run/kubernetes/kubelet-client.key: no such file or directory]
Sep 30 19:54:46 kube171 kubelet[2458]: error: failed to run Kubelet: no client provided, cannot use webhook authorization

![y r0so03 6wtgbdv hn2h](https://user-images.githubusercontent.com/1670318/31045704-fbed0296-a61b-11e7-8cac-f33474e6116d.png)

when I look into the /var/run/kubernetes directory, two files are missing compare to pre-restart

>  **Before restarting:**
root@kube171:/var/run/kubernetes# ls -alh
total 16K
drwxr-xr-x  2 root root  120 Sep 30 19:43 .
drwxr-xr-x 27 root root 1020 Sep 30 19:43 ..
-rw-r--r--  1 root root  887 Sep 30 19:43 kubelet-client.crt
-rw-------  1 root root  227 Sep 30 19:43 kubelet-client.key
-rw-r--r--  1 root root 1.1K Sep 30 19:43 kubelet.crt
-rw-------  1 root root 1.7K Sep 30 19:43 kubelet.key

And after restarting

> Last login: Sat Sep 30 19:36:46 2017 from 192.168.4.234
xx@kube171:~$ cd /var/run/kubernetes
xx@kube171:/var/run/kubernetes$ ls -alh
total 8.0K
drwxr-xr-x  2 root root   80 Sep 30 19:45 .
drwxr-xr-x 25 root root  960 Sep 30 19:45 ..
-rw-r--r--  1 root root 1.1K Sep 30 19:45 kubelet.crt
-rw-------  1 root root 1.7K Sep 30 19:45 kubelet.key
xx@kube171:/var/run/kubernetes$

**What you expected to happen**:
Does the node suppose to be back be "READY" status automatically?

**How to reproduce it (as minimally and precisely as possible)**:
Just power off / restart the node can reproduce the issue

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
Bare Metal - Self hosted VMs

- OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux kube171 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm, kubectl, etc. Nothing special

- Others:
None
![1yg2s rbda3k0 3k y5huo](https://user-images.githubusercontent.com/1670318/31045695-d2021ef8-a61b-11e7-9deb-f38bb7aa8f3c.png)

**Comment by cblecker** [comment]
@kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
What is the full invocation of the `kubelet` command and content of the `--kubeconfig` (and `--bootstrap-kubeconfig` if used) files (with confidential data redacted)?

**Comment by liggitt** [comment]
cc @jcbsmpsn @mikedanese

**Comment by hubo2005** [comment]
Here is the 10-kubeadm.conf file content which I think might be the  kubelet command you were asking for:
![image](https://user-images.githubusercontent.com/1670318/31052693-90752acc-a6be-11e7-9700-e6f8951a4e6a.png)

the kubeconfig.conf file:
![image](https://user-images.githubusercontent.com/1670318/31052707-1334d78c-a6bf-11e7-8eb5-9664dd1f0ed9.png)

And the bootstrap-kubeconfig.conf:
![image](https://user-images.githubusercontent.com/1670318/31052713-405d9424-a6bf-11e7-87cc-559acb398dab.png)

No worry about data, this is just a local experimental environment. Hope these will do the help.

@liggitt

**Comment by KamilBaran** [comment]
I have the same issue. /var/run/kubernetes/kubelet-client.crt and /var/run/kubernetes/kubelet-client.key gets deleted when I reboot the node. Restarting kubelet only works fine.
I can run kubelet after restoring these files from a backup.

**Comment by liggitt** [comment]
Did the restart occur after an upgrade from 1.7.x, or was the kubelet at 1.8 before and after the restart?

**Comment by KamilBaran** [comment]
Kubelet 1.8 is the only one version on my node (before and after the restart).

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-bugs as this bug affects kubeadm a bit as well

**Comment by hubo2005** [comment]
this is a clean 1.8 installation with kubeadm, not upgrade from any version. @liggitt

**Comment by luxas** [comment]
@hubo2005 Thank you. It turns out that there is a bug in a feature kubeadm uses (Kubelet client certificate rotation).

Meanwhile, can you remove the flag `--rotate-certificates` flag in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` please and see if that "fixes" the issue?

We might release new debs tomorrow or so removing that flag as we don't want to enable a feature that does not work. We also hope that we can fix the underlying cert rotation issue in v1.8.1, but that is not clear yet...

Thanks again for reporting this bug!

**Comment by liggitt** [comment]
cc @smarterclayton

**Comment by hubo2005** [comment]
@luxas its my pleasure.
But remove the --rotate-certificates flag Or set --rotate-certificates=false Or remove the environment variable KUBELET_CERTIFICATE_ARGS from the kubelet ExecStart do't work, the error is still the same after reboot.
![image](https://user-images.githubusercontent.com/1670318/31056652-a23f5d1a-a707-11e7-88ed-63a4b8665aa5.png)

**Comment by liggitt** [comment]
@hubo2005 just to be sure, did you run `systemctl daemon-reload` after modifying the unit file?

**Comment by liggitt** [comment]
actually, I think this is an issue with `/var/run` being a transient folder, completely removed/recreated on reboot. Looking at the timestamps, the whole folder is being recreated. The server cert/key are regenerated at kubelet start, but the client certs obtained via bootstrapping remain missing.

In short, the issue is:
1. `--cert-dir` defaults to a transient directory (/var/run/kubernetes)
2. `kubeadm` places the `--kubeconfig` file in a non-transient directory, so it gets generated referencing files that get deleted on reboot
3. on reboot, the cert files are removed
4. next time the kubelet starts:
    * `--kubeconfig` exists, so it skips obtaining a client cert using `--bootstrap-kubeconfig`
    * there is no serving cert/key, so the kubelet creates one
    * `--kubeconfig` references a missing client cert/key, so the kubelet fails to contact the API server, logs a warning (not an error):
      > W1001 16:34:37.546738    9683 server.go:381] invalid kubeconfig: invalid configuration: [unable to read client-cert /var/run/kubernetes/kubelet-client.crt ...

The most obvious immediate resolution would be to set `--cert-dir` to a non-transient location.

**Comment by hulkholden** [comment]
I was seeing this too. I can confirm setting --cert-dir to a non-transient dir, deleting /etc/kubernetes/kubelet.conf and restarting results in a working node.

**Comment by luxas** [comment]
@liggitt so setting `--cert-dir` to `/var/lib/kubelet/pki` in the meantime in debs/rpms will miligate this issue, right?
Let's make sure @pipejakob sees this as well ^

Thanks for the digging @liggitt!

**Comment by liggitt** [comment]
> @liggitt so setting --cert-dir to /var/lib/kubelet/pki in the meantime in debs/rpms will miligate this issue, right?

Yes.

* 1.7 systems will tolerate that change (since the only thing that was used for was self-signed serving certs, which will happily regenerate in the new location)
* New 1.8.0 systems will happily generate TLS-bootstrapped certs in the new location
* Existing 1.8.0 systems that already bootstrapped will have to remove their `--kubeconfig` file, since their `--kubeconfig` files have the bad location persisted in them.

**Comment by liggitt** [comment]
Opened several PRs:
* https://github.com/kubernetes/kubernetes/pull/53316 adds the issue and workaround to the 1.8.0 known issues list
* https://github.com/kubernetes/kubernetes/pull/53317 changes the default `--cert-dir` for the kubelet, will pick to 1.8.x
* https://github.com/kubernetes/release/pull/426 changes the `--cert-dir` for kubeadm >= 1.8.0

**Comment by lucasvel** [comment]
Using kubeadm here and the proposed solution (referenced after this) hasn't worked for me:

- update the kubeadm package to 1.8.0-1
- remove the /etc/kubernetes/kubelet.conf file
- restart the kubelet to allow it to bootstrap

I'm getting 
`kubelet: error: failed to run Kubelet: cannot create certificate signing request: Unauthorized`
after restarting kubelet and the following entry in the API server logs:
`authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]`

I tried making the kubelet to bootstrap itself again using `--require-kubeconfig` but no luck (and got a deprecation warning).

Any recommendations?

**Comment by fredsted** [comment]
In case anyone else is facing similar issues on an older kubeadm cluster.

I fixed this by doing `kubeadm reset` on the node, then making a new token on a master using `kubeadm token create` and re-joining the node using 

```
kubeadm join x.x.x.x:6443 --token xxxxx.xxxxxx --discovery-token-ca-cert-hash sha256:xxxxx
```

**Comment by qixiaobo** [comment]
> In case anyone else is facing similar issues on an older kubeadm cluster.
> 
> I fixed this by doing `kubeadm reset` on the node, then making a new token on a master using `kubeadm token create` and re-joining the node using
> 
> ```
> kubeadm join x.x.x.x:6443 --token xxxxx.xxxxxx --discovery-token-ca-cert-hash sha256:xxxxx
> ```

How I wish I found this issue yesterday
Thanks to god ,I just use this commands by myself but A large waste of time for about 2 hours

**Comment by qixiaobo** [comment]
> > In case anyone else is facing similar issues on an older kubeadm cluster.
> > I fixed this by doing `kubeadm reset` on the node, then making a new token on a master using `kubeadm token create` and re-joining the node using
> > ```
> > kubeadm join x.x.x.x:6443 --token xxxxx.xxxxxx --discovery-token-ca-cert-hash sha256:xxxxx
> > ```
> 
> How I wish I found this issue yesterday
> Thanks to god ,I just use this commands by myself but A large waste of time for about 2 hours

I  just copy /var/lib/kubelet/pki/kubelet.crt and /var/lib/kubelet/pki/kubelet.key from other nodes.
And then  `kubeadm join --token xxx xxx:6443 --discovery-token-unsafe-skip-ca-verification`

**Comment by qixiaobo** [comment]
> > > In case anyone else is facing similar issues on an older kubeadm cluster.
> > > I fixed this by doing `kubeadm reset` on the node, then making a new token on a master using `kubeadm token create` and re-joining the node using
> > > ```
> > > kubeadm join x.x.x.x:6443 --token xxxxx.xxxxxx --discovery-token-ca-cert-hash sha256:xxxxx
> > > ```
> > 
> > 
> > How I wish I found this issue yesterday
> > Thanks to god ,I just use this commands by myself but A large waste of time for about 2 hours
> 
> I just copy /var/lib/kubelet/pki/kubelet.crt and /var/lib/kubelet/pki/kubelet.key from other nodes.
> And then `kubeadm join --token xxx xxx:6443 --discovery-token-unsafe-skip-ca-verification`
kubelet --version
Kubernetes v1.18.8-aliyun.1
