### ISSUE TITLE
Getting X509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by sarathcakurathi** [kubernetes/kubernetes#53313]
I am new to kubernetes, trying to configure it from terraform using these scripts. I created tls assets and copied to proper location as mentioned in ericandrewlewis/kubernetes-via-terraform
 but when i try to issue kubectl get pods or kubectl get nodes I am getting x509 certificate signed by unknown authority error either from k8s master or from terraform. Please help me.

**Comment by liggitt** [comment]
Typically, that means the CA certificate used to sign the apiserver certificates was not configured in the kubeconfig file used by kubectl. I'd suggest asking the question of the author of the scripts/docs used to set up the cluster
