### ISSUE TITLE
Attach documentation to API types and/or resources

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#5331]
Forked from #3060, based on [a comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/3060#issuecomment-78361868) by @smarterclayton.

Currently we can extract documentation from struct fields and represent them in the swagger for the API. We don't have a comparable mechanism for documenting whole types or resources. We'd like to be able to either directly embed documentation or at least link to API docs #3059.

go-restful provides a way to attach documentation to operations, so we'd just need a Description() interface function on the registry to attach the info to operations on a resource.

However, it would be nice to be able to put the documentation on the API types directly. The [swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md) does have a way to represent descriptions of ["model objects"](https://github.com/emicklei/go-restful/blob/master/swagger/swagger.go#L170), but go-restful doesn't yet populate it.

Go doesn't directly support tagging structs or types. We previously looked into some way to use godoc, but that looked very cumbersome.

We need a way to document structs, custom types #2971, and enum-like constants.

Perhaps we could develop a convention that would enable us to use the existing struct field tag mechanism, such as a tagged non-public/non-json "documentation" field (or anonymous field?), or a constant string whose name can be automatically derived from the type name.

cc @nikhiljindal

**Comment by bgrant0607** [comment]
@smarterclayton suggests attaching the descriptions to TypeMeta. That would work for top-level API objects.

**Comment by bgrant0607** [comment]
Some short descriptions can be found here: https://github.com/openshift/origin/pull/2914

See also #3060

**Comment by caesarxuchao** [comment]
After this [commit](https://github.com/emicklei/go-restful/commit/840de8cdfa1cb6acba339dcaf0c7811101eac06a), go-restful will populate model.description field from the contents of modelDescription tags attached to any struct fields, including embedded fields like `TypeMeta`.

However, swagger-ui does not render the model.description field in the generated webpage. We will work on this later.

**Comment by caesarxuchao** [comment]
There is a feature request for rendering the model.description here: https://github.com/swagger-api/swagger-ui/issues/1430

**Comment by bgrant0607** [comment]
cc @andronat @erictune

**Comment by andronat** [comment]
JFYI we are doing significant changes on how to handle information exposed to swagger: #10933

**Comment by bgrant0607** [comment]
We're doing this via comments now.
