### ISSUE TITLE
kube-proxy: Inconsistent settings for conntrack

### ISSUE THREAD

**Issue by pmichali** [kubernetes/kubernetes#53329]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Set conntrack_max and conntrack_max_per_core both to zero.

**What you expected to happen**:
Expected kube-proxy to leave settings for conntrack alone, but kube-proxy attempts to change hashsize and fails (see below).

The API indicates that these both could be set to zero to ignore them:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L153-L157

However, there is default logic, that, if both are zero, sets conntrack_max_per_core to a default value and that causes the hashsize change:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/componentconfig/v1alpha1/defaults.go#L83-L87

**How to reproduce it (as minimally and precisely as possible)**:
Check that host has conntrack max set to a value that is more than 4x hashsize, and then try to start kube-proxy with both conntrack max and max per core set to zero on the command line. You can use kubeadm-dind-cluster project to start cluster with these settings. It will fail to bring up kube-proxy (see below).

**Anything else we need to know?**:
Running under Docker-In-Docker (so kube-master is a container).

Have a system with max=1M and hashsize=64k, so kube-proxy wants to increase hashsize. 

Because of https://github.com/kubernetes/kubernetes/issues/25543#issuecomment-282503251
 the hashsize cannot be saved and kube-proxy fails. In short, the filesystem is marked as R/W, but one cannot write a new hashsize setting.

**Environment**:.
- Kubernetes version (use `kubectl version`): latest on master
- Cloud provider or hardware configuration**: bare-metal, using kubeadm-dind-cluster to bring up 3 node cluster on one host using nested docker.
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
Linux bxb-c2-78 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Using kubeadm-dind-cluster project
- Others: Host with large conntrack max setting (e.g. 1M)

**Comment by ncdc** [comment]
Would you say this is a dupe of #50787?

**Comment by pmichali** [comment]
From what I can tell, the default creation logic will set conntrack max per core to 32K, if both conntrack max and conntrack max per core are zero. I don't see where the incoming values come from (not the CLI), so they would be zero and default logic will set max per core, AFAICT.

Later during init processing, a config file is loaded (which has no conntrack settings), and the defaults are used.

One issue seems to be that any CLI arguments specified, are ignored, when loading the config file and then calling NewProxyServer(), preventing any override from that source.

A second issue seems to be that there is no way to tell when a user is specifying zero values from the CLI and when no setting is being specified. So, even if CLI values were to override, there's no way to tell if these zero values should be used (the attempt by kubeadm-dind-cluster repo is to set conntrack max and conntrack max per core to zero, so no changes occur).

Third, the command line help implies that zero can be used, to leave settings alone, but I don't see how that can happen, given there is no differentiation between unset and zero setting, AFAICT.

**Comment by pmichali** [comment]
Ideally, fixing #25543 would allow settings to be properly applied (systems with large conntrack max, would get their hashsize increased), and then the only issue would be handling the claim that one can set values to zero to leave them alone (maybe just remove that clause) and the acceptance of CLI values.

As it stands now though, because of #25543 we cannot change hashsize, and because CLI args are ignored we cannot override conntrack max (I tried setting to 256K, and kubeadm-dind-cluster tries to set to zero via command line) to prevent the need to change hashsize.

**Comment by ncdc** [comment]
@pmichali would you mind copying your comments over to #50787? I'd like to close this issue as a duplicate. Thanks!

**Comment by pmichali** [comment]
@ncdc Will do. Yes, it is a duplicate.
