### ISSUE TITLE
Opaque integer resources will get deleted by kubelet in v1.8

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#53342]
The introduction of device plugin support in kubelet ended up deleting Opaque Integer Resources that are not exposed via device plugins. 
Relevant code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L616).

Two things need to happen now in v1.8:
1. Add a test to catch this regression
2. Have kubelet not delete extended resources.

Cluster admins will have to manually remove extended resources exposed via device plugins when they remove plugins. 

@kubernetes/sig-node-bugs

**Comment by vishh** [comment]
FYI: OIR is an alpha feature

**Comment by vishh** [comment]
@ConnorDoyle

**Comment by jiayingz** [comment]
For 1.8, because we plan to have kubelet not delete extended resources in any cases, we also need to remove the logic of testing device plugin resource removal after device plugin DaemonSet is deleted in the Feature:GPUDevicePlugin e2e test. We will file a separate issue to track better handling on this.

**Comment by ConnorDoyle** [comment]
It looks like the linked code makes an assumption that device resources and extended resources are in 1:1 correspondence, but that wasn't the intent for extended resources. So, this problem applies not only to opaque integer resources. @vishh can we update the issue title?

**Comment by jiayingz** [comment]
@ConnorDoyle Other than OIR, what other resource scheduling do you think this regression might also affect?

I think the problem right now is that we can't distinguish device plugin resources from resource naming convention. This makes resource deletion harder as we will need some explicit mechanism to track and mark resource deletion. Also curious about the intention of the extended resources. Other than being outside kubernetes default namespace, does it have any scheduling implications like requiring special extensions at the node level or not?

**Comment by ConnorDoyle** [comment]
> Other than OIR, what other resource scheduling do you think this regression might also affect?

The release notes specify that extended resources are the replacement for OIR, so it would also affect users who try to migrate to extended resources.

> does it have any scheduling implications like requiring special extensions at the node level?

The intention of Extended Resources is that some of them may have node isolation support, but not all are expected to. Extended resources with no node isolation support are equivalent to OIRs, which allowed us to deprecate OIRs.

The scheduler handles all extended resources and OIRs the same way, whether they have node isolation support or not. I drew a little picture for anyone reading this who isn't as familiar with the existing categories of resource names in the scheduler. "Device resources" are shown separately. They are the subset of extended resources advertised by a device plugin.

![k8s resource classes](https://user-images.githubusercontent.com/379372/31110027-e987c76e-a7b8-11e7-8b25-53230ff4510f.png)

**Comment by lichuqiang** [comment]
How about defining a separate prefix for device plugin resources, instead of using that of extended resources(OIR) ?

**Comment by jiayingz** [comment]
Thanks a lot for the explanation, @ConnorDoyle. I didn't realize that we have already updated the document to mark OIR as replaced by extended resources. Once OIR is fully deprecated, we will only have first-class resources and extended resources. If I understand correctly, first-class resources are those that Kubernetes will provide native support and so they are in the default kuberenetes namespace. Otherwise, they should follow extended resource naming convension and their advertisements require extra configurations?

**Comment by RenaudWasTaken** [comment]
@vishh @jiayingz are we only trying to have kubelet not delete Opaque Integers ?

In that case, I'm wondering if the following solution might be cleaner:
- code on [line 613](https://github.com/kubernetes/kubernetes/blob/aa7d9b1da9ff82289568b2ee350721860c6e5bfa/pkg/kubelet/kubelet_node_status.go#L613) is the line that checks if the resource name is extended
- What if we checked if it's not an OIR ? i.e: `if v1helper.IsExtendedResourceName(k) && !v1helper.IsOpaqueResourceInteger(k) {`

That would prevent having to manually remove extended resources.

**Comment by ConnorDoyle** [comment]
> are we only trying to have kubelet not delete Opaque Integers ?

@RenaudWasTaken no, that's not sufficient; we need to also not delete extended resources that are unrelated to device plugins.

**Comment by ConnorDoyle** [comment]
After the regression fix provided by #53353, listing available options (please add if I missed anything from above)

_Option 1: Checkpoint resources advertised from device plugins._

As mentioned by @jiayingz:
> This makes resource deletion harder as we will need some explicit mechanism to track and mark resource deletion.

_Option 2: Determine whether a resource was advertised by a device plugin by pattern-matching the resource name._

As mentioned by @lichuqiang:

> How about defining a separate prefix for device plugin resources?

At first thought, that would probably involve moving them into the `kubernetes.io/` domain prefix.

**Comment by jiayingz** [comment]
Thanks a lot for the summary. FYI, filed a separate issue https://github.com/kubernetes/kubernetes/issues/53395 to track the long term solution after 1.8 so that we can focus this issue for 1.8 temporary fix.

**Comment by vishh** [comment]
Marking this fixed with #53353
