### ISSUE TITLE
pkg/ depends on cmd/

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#53341]
cmd/kubelet and cmd/kubeadm are both depended on in pkg/. pkg/ should not depend on cmd/

@kubernetes/sig-node-bugs 
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by luxas** [comment]
Yeah, I think I pointed this out in some PRs somewhere and asked for a bazel rule, but don't remember the exact context.

cc @ixdy @monopole @deads2k

**Comment by ixdy** [comment]
https://github.com/kubernetes/community/pull/598

Not a lot has changed recently.

**Comment by dims** [comment]
here's the current status:
```
[dims@dims-mac 12:57] ~/go/src/k8s.io/kubernetes ⟩ find pkg/ -name BUILD -exec grep -H -i -E "(//|//.*/)cmd" {} \; | grep -v pkg/kubectl/cmd
pkg/api/testing/BUILD:        "//cmd/kubeadm/app/apis/kubeadm/fuzzer:go_default_library",
pkg/controller/certificates/BUILD:        "//cmd/gke-certificates-controller:__subpackages__",
pkg/controller/service/BUILD:        "//cmd/kubeadm/app/constants:go_default_library",
pkg/kubelet/BUILD:        "//cmd/kubelet/app/options:go_default_library",
pkg/kubelet/volumemanager/reconciler/BUILD:        "//cmd/kubelet/app/options:go_default_library",
pkg/kubemark/BUILD:        "//cmd/kube-proxy/app:go_default_library",
pkg/kubemark/BUILD:        "//cmd/kubelet/app:go_default_library",
pkg/kubemark/BUILD:        "//cmd/kubelet/app/options:go_default_library",
pkg/master/BUILD:        "//cmd/kube-apiserver/app/options:go_default_library",
```

**Comment by mtaufen** [comment]
The `pkg/kubelet` dependency is on `ContainerRuntimeOptions` from `cmd/kubelet/app/options`. 
@yujuhong perhaps we should move the definition of these parameters into `pkg/kubelet`? It gets more complex if some of these parameters are exclusively consumed in `cmd`, since then it doesn't make sense to have them in `pkg`...

**Comment by yujuhong** [comment]
> The pkg/kubelet dependency is on ContainerRuntimeOptions from cmd/kubelet/app/options.

There are other constants too. @dims's PR above (#53458). Care to review that PR?  :-)

**Comment by luxas** [comment]
@dims can this be closed now?

**Comment by dims** [comment]
yes. thanks @luxas
