### ISSUE TITLE
Support revocations for certificates signed by Kubernetes

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#53348]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

There is the ability to sign certificates using Kubernetes since 1.7.0: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

It would be nice if there is a mechanism to revoke a given certificate if we no longer need it.

**Comment by F21** [comment]
@kubernetes/sig-auth

**Comment by ericchiang** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/18982

/close
