### ISSUE TITLE
in-cluster kubectl can't get nonResource URL in `local-cluster-up`

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#53349]
**Is this a BUG REPORT or FEATURE REQUEST?**: I think it's a bug, but I'm not sure.

/kind bug

**What happened**:
Related to test failure of #53232
In-cluster kubectl can't get `/swagger-2.0.0.pb-v1` file with following error (permission errors).
```
rbac.go:116] RBAC DENY: user "system:serviceaccount:default:default" groups ["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"] cannot
"get" nonResourceURL "/swagger-2.0.0.pb-v1" cluster-wide
wrap.go:42] GET /swagger-2.0.0.pb-v1: (1.342458ms) 403 [[kubectl/v1.9.0 (linux/amd64) kubernetes/2d8c20e] 192.168.9.3:54306]
```

**What you expected to happen**:
`200` :-)

**How to reproduce it (as minimally and precisely as possible)**:
```
hack/local-cluster-up.sh -O
kubectl run --restart=Never nginx --image=nginx
kubectl cp $(which kubectl) nginx:/tmp/
kubectl cp something.yaml nginx:/tmp/
kubectl exec nginx -t -- /tmp/kubectl apply -f something.yaml
```

`kubectl apply` will fetch the openapi schema to validate `something.yaml`, but fail because it doesn't have permission.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  HEAD
- Cloud provider or hardware configuration**: local
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: `hack/local-cluster-up.sh`
- Others:

@mbohlool says it also happens on GCE.

**Comment by cjcullen** [comment]
We have the `system:discovery` role that we use to grant anonymous access to discovery nonResourceURLs:
```
$ kubectl get clusterroles system:discovery -o yaml
...
rules:
- nonResourceURLs:
  - /api
  - /api/*
  - /apis
  - /apis/*
  - /healthz
  - /swaggerapi
  - /swaggerapi/*
  - /version
  verbs:
  - get
```

I'm guessing the other swagger URLs should also be added to that role? @liggitt?

**Comment by liggitt** [comment]
The swagger urls should be standardized and cleaned up before we expose them. The current pattern is nonstandard and not sustainable.

**Comment by apelisse** [comment]
@mbohlool has a proposal for that, but I don't think that's going to come out soon. I don't think it should block the removal of swagger 1.2 though ...

Can we hard-code the name for now?
```
/swagger.json
/swagger-2.0.0.pb-v1
```

**Comment by mbohlool** [comment]
yeah, I think we should hard code names here and patch this into 1.8 so kubectl works. We should clean this up for 1.9 but for 1.8, kubectl (and other clients in need of discovery) should have access to them.

```
- /swagger.json
- /swagger-2.0.0.json
- /swagger-2.0.0.pb-v1
- /swagger-2.0.0.pb-v1.gz
```

**Comment by apelisse** [comment]
It's only for in-cluster `kubectl`, and it automatically falls back on swagger 1.2 for kubectl 1.8, so it don't think it matters.

**Comment by cjcullen** [comment]
I think hardcoding the names should be okay. RBAC bootstrap roles are additive only, so clusters will have those names in their `system:discovery` role forever. I don't think that is a problem though, other than the cruft.

**Comment by liggitt** [comment]
I don't want to encourage use of endpoints we already plan to deprecate

**Comment by liggitt** [comment]
`/swagger.json` seems fine

**Comment by mbohlool** [comment]
For kubectl backward compatibility we need to at least have access to `/swagger-2.0.0.pb-v1`. kubectl 1.9 should work with in-cluster 1.8. Because other tools may have the same issue as kubectl and may use any of those endpoints, we need to add those too. This is only for 1.8 cluster (what we are going to patch into 1.8) and for 1.9 we would remove all of them and add one endpoint.

**Comment by mbohlool** [comment]
Actually we can't remove those endpoints in 1.9 even if we added the new endpoints. The promise of kubectl is it will work with one version before and one version after so if we want kubectl to work in-cluster 1.9, we need to keep these endpoints (and all them to the role above) for 1.9 too. The question here is not about encouraging use of those endpoints. The endpoints are there and borken in-cluster if we don't add them to the authorization role above.

**Comment by liggitt** [comment]
> For kubectl backward compatibility we need to at least have access to /swagger-2.0.0.pb-v1. kubectl 1.9 should work with in-cluster 1.8.

I don't think that's accurate. No cluster with authorization enabled has allowed those endpoints, and kubectl 1.8 must deal with lack of access to that URL for backwards compatibility.

> Because other tools may have the same issue as kubectl and may use any of those endpoints, we need to add those too.

Like I said, we shouldn't promote use of endpoints we plan to deprecate

**Comment by liggitt** [comment]
> This is only for 1.8 cluster (what we are going to patch into 1.8) and for 1.9 we would remove all of them and add one endpoint.

Permissions never tighten, they only expand.

**Comment by mbohlool** [comment]
Kubectl 1.8 will fall back to swagger 1.2. But we want to remove swagger 1.2 from kubectl 1.9. 

If we do not add auth in 1.8 branch to let kubectl access those endpoints in-cluster for 1.8, then kubectl 1.9 will not work within cluster 1.8 (as it won't have anything to fall back to).

For 1.9, I was wrong. Kubectl 1.8 will work within cluster 1.9 because it will fall back to swagger 1.2 that is still exists in 1.9.

**Comment by mbohlool** [comment]
Those endpoints are not deprecated in 1.8 so we should have auth to access them in cluster. If (and we should) deprecate them in 1.9, I am fine with not having auth to access them in cluster, though I am not sure why as they are going to be removed in 1.10 anyway.

**Comment by mbohlool** [comment]
> Permissions never tighten, they only expand.

Oh I see your point. then permission should be in 1.8 (because of the kubectl compatibility I argued in https://github.com/kubernetes/kubernetes/issues/53349#issuecomment-333703750) and hence it should remains in 1.9.

**Comment by liggitt** [comment]
I'd recommend updating 1.8.x to allow `/swagger.json` and to have `kubectl` use that path, since it's the only one of the current endpoints considered a standard path. IIRC, you verified that gzip and etag work properly on that endpoint, so the slight size difference between gzipped json and proto isn't worth the use of non-standard paths.

**Comment by liggitt** [comment]
For reference, for those concerned with size:

```sh
$ curl -k -s https://localhost:6443/swagger.json -H "Accept-Encoding: gzip" | wc -l
     535
$ curl -k -s https://localhost:6443/swagger-2.0.0.pb-v1.gz | wc -l
     556
```

**Comment by liggitt** [comment]
So it appears that https://github.com/kubernetes/kubernetes/pull/46803 changed client-go to request this endpoint as well. That's unfortunate.

I opened https://github.com/kubernetes/kubernetes/pull/53359 with the minimal exposure required to satisfy client-go 4.0/5.0.

The other two endpoints don't need to be exposed:
* `/swagger-2.0.0.json` is just a non-standard form of `/swagger.json` we don't want to encourage
* `/swagger-2.0.0.pb-v1.gz` is unnecessary, request `/swagger-2.0.0.pb-v1` with `Accept-Encoding: gzip`

@mbohlool, please update the openapi endpoints handler to serve an endpoint that uses standard `Accept`/`Accept-Encoding` header to determine the content to serve, as discussed

**Comment by apelisse** [comment]
> For reference, for those concerned with size

You're counting the number of `0x0A` in a binary file with `wc -l` 😄 . But the point is still valid, gzipping text is much more efficient than gzipping binary (I've tried that earlier too).
The problem with gzipped json is parse time. Json is much slower to parse than protobuf.

> @mbohlool, please update the openapi endpoints handler to serve an endpoint that uses standard Accept/Accept-Encoding header to determine the content to serve, as discussed

Yes, let's absolutely do that.

Once #53359 is merged, all of this should be fixed right? Thank you very much @liggitt

**Comment by liggitt** [comment]
> You're counting the number of 0x0A in a binary file with wc -l

ah, right

```sh
$ curl -k -s https://localhost:6443/swagger-2.0.0.pb-v1.gz -H "Accept-Encoding: gzip" | wc -c
  142611
$ curl -k -s https://localhost:6443/swagger.json -H "Accept-Encoding: gzip" | wc -c
  137175
```

> The problem with gzipped json is parse time. Json is much slower to parse than protobuf.

This is a symptom of requiring kubectl to parse a document containing the complete schema for every resource in every version in every API group in order to access any discovery information. That's a fundamental issue with the monolithic openapi doc approach we're taking (c.f. https://github.com/kubernetes/kubectl/issues/66#issuecomment-333600690). Trying to work around that issue by layering things like protobuf encodings on top of the openapi schema might help short-term, but doesn't seem like a good direction, and even that has its limits.
