### ISSUE TITLE
PersistentVolumeController should not hardcode recycler image

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53357]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The recycler pod image used by the NFS & HostPath persistent volume plugins is hardcoded to `gcr.io/google_containers/busybox`, here:
https://github.com/kubernetes/kubernetes/blob/080db40539b78a1c7a55912d5eab09a361ccf2fb/pkg/volume/plugins.go#L716

There are several problems with this approach:

1. No way to run a deployment off a custom repository. E.g. if an organization wanted full control of every image running in their cluster.
2. The hardcoded image is unversioned, meaning there is no way to ensure you're getting the latest version (and if latest is updated, there is no way to safely roll out the updates).

**What you expected to happen**:

The image, repository & tag should be configurable at deployment time, e.g. with a command-line flag. The default image should use a versioned tag (not latest).

**Comment by msau42** [comment]
Recycler is deprecated, so this code should be eventually removed.

**Comment by dims** [comment]
@msau42 - where is the deprecation notice?

https://github.com/kubernetes/kubernetes/pull/36760 did not get merged and i don't see any info in https://kubernetes.io/docs/concepts/storage/persistent-volumes/ about deprecation either

**Comment by msau42** [comment]
@erinboyd @childsb did we not send out an official deprecation notice for recycler?

**Comment by jsafrane** [comment]
There is `kube-controller-manager --pv-recycler-pod-template-filepath-nfs=/etc/my-recycler.yaml` that can point to yaml with a pod template. Isn't it enough?

**Comment by jsafrane** [comment]
I am closing this bug, user can configure complete recycler template, incl. container image name (and it's used in OpenShift so I know it works).

**Comment by saad-ali** [comment]
> where is the deprecation notice?

https://groups.google.com/forum/#!topic/kubernetes-dev/uexugCza84I

But agreed that documentation should be updated to indicate this. Opened https://github.com/kubernetes/kubernetes/issues/59060 and https://github.com/kubernetes/website/issues/7148
