### ISSUE TITLE
Update the volume e2e test images

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#53360]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig storage
/cc @kubernetes/sig-storage-bugs 

**What happened**:
We should update all the test server packages that we use for nfs, ceph, gluster, etc e2e tests since they are quite old, and users probably will probably use newer packages.

**Comment by rootfs** [comment]
||[client version in e2e host](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/e2e/init.sls)   |  [test image server version](https://github.com/kubernetes/kubernetes/tree/master/test/images/volumes-tester) |Image|Latest (stable) server version|
|---|---|---|---|---|
|  Ceph |  ? |0.94.5   |gcr.io/google_containers/volume-ceph:0.1|12.2.1|
| Gluster   | ?  |   3.8.8|gcr.io/google_containers/volume-gluster:0.4|3.10|

**Comment by jsafrane** [comment]
I started updating iSCSI, Gluster and Ceph RBD to Fedora 26 (Gluster 3.12.1,  Ceph "Jewel", 3.10.x) in #54300.
TODO: CephFS. Any volunteer?

**Comment by jsafrane** [comment]
sorry, Fedora 26 has Gluster 3.10.6, not 3.12

**Comment by jsafrane** [comment]
I updated  #54300 with CephFS

**Comment by mkumatag** [comment]
fixed part of #54300, hence closing this task.
