### ISSUE TITLE
inconsistency field exposure - spec.nodeName and status.hostIP

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kubernetes#53362]
**What happened**:

using fieldRefs to deploy containers like so:
```        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
we wanted to use status.hostIP, but that isn't exposed:
```Invalid value: "status.hostIP": error converting fieldPath: field label not supported: status.hostIP```

**What you expected to happen**:

hostIP should be supported too.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.5
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@rbtcollins Already had a PR #50235 related to this. 

/kind bug
/sig api-machinery

Also this issue seems like a dup of #50234. We should close this one, right?

**Comment by rbtcollins** [comment]
@dixudx no - #50235 and #50234 are about giving better errors. This bug is that there is no reason to have nodeName exposed but hostIP not exposed.

**Comment by dixudx** [comment]
> This bug is that there is no reason to have nodeName exposed but hostIP not exposed.

@rbtcollins Has been fixed in [#50235 v1/strategy.go#L47](https://github.com/dixudx/kubernetes/blob/472355c2e5e2b7355a2567bfc71f8e1c0bdb1cc0/pkg/api/v1/strategy.go#L47). PTAL.

**Comment by mbohlool** [comment]
The change @dixudx referred to is in 1.8. Does that fix the issue?

**Comment by dixudx** [comment]
@mbohlool  #50235 will fix this issue when it gets merged.

**Comment by liggitt** [comment]
hostIP downward API support was added in https://github.com/kubernetes/kubernetes/pull/42717
