### ISSUE TITLE
kubectl CLI should more effectively convey discovery

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#53387]
Now that discovery is complete as an API, and CRD and aggregation are in heavy use, we need to make some minor tweaks to kubectl to improve discoverability of apis from clients.

Common issues:

1. I want to see all resources that I might be able to create
2. I want to be able to disambiguate conflicting resources
3. I want to distinguish between cluster scoped and non-cluster scoped resources
4. I want an equivalent to the `all` shortcut that is actually all resource types that are namespace scoped

We want to orient brand new users to kubectl from a config perspective into:

1. what can i `get`
2. if i want to create a config resource, how do i specify it (`explain`, which could be better)
3. i want to know what a resource is *for*

Some thoughts:

1. `kubectl api-versions` is too simple, and needs to be better or removed
2. There should be a command that makes it easy to see the list of:
    1. all namespace scoped resources
    2. all cluster scoped resources
    3. the shortcuts of those resources
    4. what the resource does (potentially as a `-v` option)
    5. a brief discussion of how to deal with version conflicting names (pod v1beta.special.bar and pod v1)
    6. potentially what versions exist for those resources
3. `explain` and `get` should suggest that command when you specify something it doesn't recognize
4. We could piggyback this into get except discovery resources aren't quite a format API, so it would be somewhat hacky.  However, get and describe already work so a few special cases aren't terrible (we did reserve APIGroupList v1 and APIGroup v1)

Hypothetical

```
$ kubectl get apigroups
NAME      VERSIONS  RESOURCES
autoscaling v1         horizontalpodautoscaler

$ kubectl describe apis
API Groups
  autoscaling:
    v1: 
       Resources: horizontalpodautoscaler
    v2:
       ...

$ kubectl get apis
NAME      VERSIONS  RESOURCES
autoscaling v1         horizontalpodautoscaler

$ kubectl apis
GROUP      VERSIONS  RESOURCES
autoscaling v1         horizontalpodautoscaler

$ kubectl apis --group=autoscaling --version=v1
GROUP      VERSIONS  RESOURCES
autoscaling v1         horizontalpodautoscaler

$ kubectl explain
error: You must select a resource type to explain:

   Nicely formatted two column table - one for namespace scoped and one for cluster scoped
```

It should be easy to select all namespaced resources from a command - we should add:

```
$ kubectl get all-namespaced --all
$ kubectl describe all-namespaced
$ kubectl delete all-resources --all
```

We can't change `all` because of backwards compatibility (anyone with `kubectl delete all --all` would be broken if we change what all covers), but also because it's deliberately short to remain easy to type for end users.

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by derekwaynecarr** [comment]
I raised this topic w/ @smarterclayton when wanting to gather information from a user whose namespace was stuck terminating.  The user was making use of the service catalog extension, and from the issue report, it was unclear what resource remained that kept the namespace from deleting.

I felt the following commands would have helped understand the reason for the issue:
```
$ kubectl get all-namespaced --all
$ kubectl describe all-namespaced
```

**Comment by soltysh** [comment]
> 2. if i want to create a config resource, how do i specify it (explain, which could be better)

That's not quite clear to me, can you elaborate a bit. 

> 3. explain and get should suggest that command when you specify something it doesn't recogniz

Big fat 👍 

I'd add the aliases/shortcuts to the describe command.

**Comment by smarterclayton** [comment]
oc explain pod should probably have a mode that spits out a sample

**Comment by smarterclayton** [comment]
This is really annoying now that I'm dealing with more and more groups.

1. Explain should tell me what group something is
2. I need to be able to see info on a given resource type in the exact form that I would specify it to get (the so called "resource-arg" form `resource.version.group`).

I think this is the #1 issue dealing with extensions - no place to go to find them, no way to know how to use them in kubectl, no way to check that the ones I care about are registered.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by shiywang** [comment]
We have an `kubectl api-resource` command WIP: https://github.com/kubernetes/kubernetes/pull/42873 which is the advanced version of `kubectl api-versions` i think.

> explain and get should suggest that command when you specify something it doesn't recogniz

I have a pr which will remove those the hard-coded resource list [help info](https://github.com/kubernetes/kubernetes/blob/93fed120fbfd5c621387d636d53f8563ebddea39/pkg/kubectl/cmd/util/printing.go#L230-L266) of `kubectl get` instead provide a prompt for user that if you want to know which resource you want to use, please use `kubectl api-resource` to check.
I also have an idea using dyanmic fetch from `cached discovery` pr here seems being vetoed https://github.com/kubernetes/kubernetes/pull/51324.

**Comment by smarterclayton** [comment]
> For user could use get, describe explain to check api-resources/groups also sounds great, but that means the implementation is a little hacky ?

I think all that matters is how a user perceives them.  We spend a lot of time encouraging users to use get and describe.  As a user, I think I would expect to find them under get.   For instance, should a user be able to use -o?  Should they be able to sort?  Filter? 

I don't like having three commands - `kubectl api-versions`, `kubectl api-resources`, and `kubectl api-groups`.  I would expect a user to be told to use kubectl get, then to ask what can they retrieve using `kubectl get`, which `kubectl get --help` can answer.   But I would much rather we use `get` for all of our listing, even if it requires a slightly hacky implementation (and get already uses discovery and can read from disk, so it's not like we can't find a clean way to implement).

**Comment by smarterclayton** [comment]
I'll open this under kubectl.

**Comment by smarterclayton** [comment]
kubernetes/kubectl#123, let's move the discussion there
