### ISSUE TITLE
GKE GPU tests and GKE Device plugin tests are failing on master

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#53399]
/kind bug
/sig scheduling

https://github.com/kubernetes/kubernetes/pull/52723 resulted in GKE GPU tests and GKE Device plugin tests to fail.

Diff between passing and failing runs:
https://github.com/kubernetes/kubernetes/compare/924bd563b...4c115a862

GKE Device Plugin Tests:
https://k8s-testgrid.appspot.com/wg-resource-management#gke-device-plugin-gpu
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/95

GKE GPU Tests:
https://k8s-testgrid.appspot.com/wg-resource-management#gke-gpu
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gpu/1453

**Comment by k82cn** [comment]
Open  https://github.com/kubernetes/kubernetes/pull/53480 to handle GPU, let's check what will happen to device plugin test.

**Comment by k82cn** [comment]
The latest two tests were passed; it's fixed by #53480, so I'm going to close this one.
