### ISSUE TITLE
scheduling.k8s.io/v1alpha1 cannot be enabled

### ISSUE THREAD

**Issue by unixwitch** [kubernetes/kubernetes#53392]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

According to the [documentation for scheduling preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) two changes are required to enable it:

* Add `--feature-gates=PodPriority=true` to apiserver and scheduler.
* Add `--runtime-config=scheduling.k8s.io/v1alpha1=true` to apiserver.

So I modified the apiserver manifest:

```
    - --runtime-config=scheduling.k8s.io/v1alpha1=true
    - --feature-gates=PodPriority=true
```

And the scheduler manifest:

```
    - --feature-gates=PodPriority=true
```

`ps` confirms that both are running with the required changes.

However, I cannot create PodPriorities by following the example in the documentation:

```
[root@master-head-1 ~]# cat >example.yaml
apiVersion: v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
[root@master-head-1 ~]# kubectl apply -f example.yaml 
error: error validating "example.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"PriorityClass"}; if you choose to ignore these errors, turn validation off with --validate=false
```

`kubectl explain` also doesn't think the API is enabled:

```
[root@master-head-1 ~]# kubectl explain priorityclass
error: API version: scheduling.k8s.io/v1alpha1 is not supported by the server. Use one of: [apiregistration.k8s.io/v1beta1 extensions/v1beta1 apps/v1beta1 apps/v1beta2 authentication.k8s.io/v1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2beta1 batch/v1 batch/v1beta1 certificates.k8s.io/v1beta1 networking.k8s.io/v1 policy/v1beta1 rbac.authorization.k8s.io/v1 rbac.authorization.k8s.io/v1beta1 storage.k8s.io/v1 storage.k8s.io/v1beta1 apiextensions.k8s.io/v1beta1 crd.projectcalico.org/v1 v1]
```

The only relevant message in the apiserver log is:

```
I1003 15:06:43.611520       1 aggregator.go:138] Skipping APIService creation for scheduling.k8s.io/v1alpha1
```

**What you expected to happen**:

I expected to be able to create podpriority resources by following the example in the documentation.

**How to reproduce it (as minimally and precisely as possible)**:

See description.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release): CentOS Linux 7.4 (1708)
- Kernel (e.g. `uname -a`): Linux master-head-1 4.13.4-1.el7.elrepo.x86_64 #1 SMP Wed Sep 27 13:32:23 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Custom scripts
- Others:

**Comment by wackxu** [comment]
@unixwitch The example yaml of priorityclass is wrong, the right version is `v1alpha1`

**Comment by dims** [comment]
@unixwitch please try the recommendation from @wackxu and close this issue?

**Comment by binarybana** [comment]
@wackxu, unfortunately that version change to the YAML does not fix the problem for me either:
```
$ cat default.yaml
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: default
value: 100000
globalDefault: true
description: "This priority class is the default and should be higher than large sweep/batch jobs but lower than high priority jobs."

$ k create -f default.yaml
error: unable to recognize "default.yaml": no matches for scheduling.k8s.io/, Kind=PriorityClass
```
To me it looks like the 
```
I1003 15:06:43.611520       1 aggregator.go:138] Skipping APIService creation for scheduling.k8s.io/v1alpha1
```
error message points me to [this section](https://github.com/kubernetes/kubernetes/blob/73d1b38604d6f39ec77a94f0f411a46c765d1c4f/cmd/kube-apiserver/app/aggregator.go#L199-L228) where I don't see `scheduling.k8s.io` defined?

**Comment by wackxu** [comment]
@binarybana Yes, you are right, I have commit a pr to fix this.

**Comment by abhinavsinha001** [comment]
Not sure but after using the updated config I am able to create Priority Class successfully  but unable to use the feature while creating POD. Here are the errors observed

Getting following error while creating pod:
`Error validating pod nginx_default(8e139687-c655-11e7-9114-246e967a4158) from api, ignoring: [spec.priorityClassName: Forbidden: Pod priority is disabled by feature-gate, spec.priority: Forbidden: Pod priority is disabled by feature-gate]`

`kubectl explain priorityclass`
`error: group scheduling.k8s.io has not been registered`

The PodPriority is enabled in both API server and Scheduler
`- --feature-gates=PodPriority=true`
`- --runtime-config=scheduling.k8s.io/v1alpha1=true`

**Comment by mgdevstack** [comment]
I'm able to create PriorityClass and schedule pod with specified PriorityClass on Minikube 0.26.0.

``minikube start --kubernetes-version v1.10.0 --feature-gates=AllAlpha=true,PodPriority=true --extra-config=apiserver.runtime-config=scheduling.k8s.io/v1alpha1=true``

![image](https://user-images.githubusercontent.com/8110509/38945064-17a4fb04-4353-11e8-96f0-ad9fb614977d.png)

**Comment by pm-abhinav-sinha** [comment]
This issue was sorted - on kubeadm production setup, this flag needs to be enabled for kubelet as well - updated doc https://github.com/kubernetes/website/pull/6334#issuecomment-344586215

**Comment by sbisl** [comment]
@mgdevstack I've created the PriorityClass and deployed the pod with the specified PriorityClass. The pod is getting created. I'm wondering is there any way to check the PriorityClass of the pod either in UI or CLI? The steps you've shown is giving me the same result. Can you please help me ? Thanks in advance.
