### ISSUE TITLE
Expose etcd alerts and quota via metrics from the api servers

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#53405]
Currently many clusters that are secure want to isolate etcd from the outside world (for defense in depth reasons), and so it'll become very difficult to gather metrics from it.  Conversely, many failures around api servers revolve around failures in etcd.

There are three primary conditions that are important to the operation of etcd as viewed from the api server.

1. alerts and quota size of the etcd store
2. reachability latency / performance of the common commit operations from the storage layer to etcd
3. failure rate from the client to etcd

And possibly other relevant background activities like compaction.

I think we should consider reporting alarms from etcd (as well as reachability info) as Prometheus metrics on the api server.

@kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-instrumentation-feature-requests @kubernetes/sig-scalability-feature-requests

**Comment by smarterclayton** [comment]
@derekwaynecarr re: the failures we saw recently where we crossed the health threshold

**Comment by fgrzadkowski** [comment]
Should we instead have a dedicated component doing this kind of monitoring and exposing metrics? I think it'd be pretty weird to have apiserver expose status of all other components running on the master. WDYT?

**Comment by brancz** [comment]
We started [this](https://github.com/coreos/etcd/issues/8060) effort a while ago, in order to expose metrics on a separate port. It targeted to be released in etcd `v3.3.0`. That way we can expose metrics without exposing the entire client APIs. We could think of extending this and have separate client certificates in order to have additional authorization in place to give Prometheus fine grained access to only the metrics.

I agree with @fgrzadkowski, that some of the suggestions somewhat defeat the purpose of whitebox monitoring. In fact it's actually re-implementing parts of what Prometheus can already do. If people are worried about a "central" Prometheus having access from worker nodes (or any other origin than master nodes), then I would suggest putting a small size Prometheus server on the master nodes along with the apiserver processes, that only monitors the etcd cluster. If necessary for alerting you can then federate the necessary metrics into a single Prometheus server, but I don't actually think that would be necessary.

Alerts would still end up in a single Alertmanager cluster, and that's where alerts would be grouped to make meaningful notifications.

/cc @fabxc

**Comment by smarterclayton** [comment]
> We could think of extending this and have separate client certificates in order to have additional authorization in place to give Prometheus fine grained access to only the metrics.

I've seen many environments where that would be considered impossible - network access to etcd would be extremely dangerous and not worth the risk.  I'm not even sure that a reasonably paranoid cluster operator would want to take the risk of exposing that port, because that means that unaudited information might escape that could lead to cluster escalation.

I agree that in general I don't expect the API server to mindlessly expose every bit of the underlying metrics.  The three or four that matter are compaction, alarms, and db size and quota.  We certainly would have code in the api server that is going to react to these.  Is a limited set of duplication to maintain a higher security posture a real problem?

**Comment by smarterclayton** [comment]
Running a separate prometheus on the masters is potentially possible, but also has security implications (that's another bit of code that has to be audited).  I think from a general security perspective etcd is ring 0, api servers are ring 1, extensions are ring 2, and everything else is ring 3.  Ideally the connections between rings 0 and 1 are completely minimal.  For people less concerned about security, I don't think the etcd metrics are a problem.  For people who run serious clusters, I'm very concerned about the layering.

**Comment by smarterclayton** [comment]
Copying @kubernetes/sig-auth-misc re implications of etcd being exposed vs tradeoffs in some clusters

**Comment by smarterclayton** [comment]
Summary of discussion from sig-instrumentation meeting:

1. Ultimately it's better to have all the etcd metrics than just some of them
2. We talked about a number of proxying options, such as node and pod proxying, or adding a new proxy to the api server that could be configured to pointing to the local node
3. The easiest option probably is having the masters have etcd listen on a port (not accessible off the box) and create a service with endpoints that points to the etcd port, and have the service proxy access it.  The masters would then proxy to the etcd port (in an HA master + etcd setup), but others would not be able to access it.

**Comment by mbohlool** [comment]
cc @jpbetz

**Comment by brancz** [comment]
> The easiest option probably is having the masters have etcd listen on a port (not accessible off the box) and create a service with endpoints that points to the etcd port, and have the service proxy access it. The masters would then proxy to the etcd port (in an HA master + etcd setup), but others would not be able to access it.

I'm not sure if I'm misunderstanding, to me it seems like this is almost equivalent to having firewall rules, only that we proxy requests additionally through the apiserver.

For completeness, other suggestions and mentions that could be used in combination:

- separate port for metrics on etcd
- that port has additional client cert authentication and authorization
- network policy/firewall rules, and run separate Prometheus on masters or dedicated nodes meant to only monitor the cluster etcd

**Comment by Quentin-M** [comment]
Updating the thread with the relevant PR: https://github.com/coreos/etcd/pull/8242
