### ISSUE TITLE
unify on time unit for kube-apiserver logs

### ISSUE THREAD

**Issue by huydinhle** [kubernetes/kubernetes#53406]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
kube-apiserver logs time units are in both milliseconds and microseconds
```
message: I0927 18:41:55.838557 1 wrap.go:75] PUT /api/v1/namespaces/xxxx/configmaps/xxxx: (732.432µs) 200 [[xxxx/v0.0.0 (linux/amd64) kubernetes/$Format] x.x.x.x:47754]

message: I0927 18:41:55.838557 1 wrap.go:75] PUT /api/v1/namespaces/xxxx/configmaps/xxxx: (0.732ms) 200 [[xxxx/v0.0.0 (linux/amd64) kubernetes/$Format] x.x.x.x:47754]
```

**What you expected to happen**:
Can we have a configuration for kube-apiserver to use only miliseconds. Our logging team wants to standardize on one time unit only 
**How to reproduce it (as minimally and precisely as possible)**:
Just look at the logs for kube-apiserver

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.7
- Cloud provider or hardware configuration**: aws
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`): 4.12.7 
- Install tools: tack
- Others:

**Comment by huydinhle** [comment]
@kubernetes/sig-architecture

**Comment by dims** [comment]
@huydinhle - please see https://github.com/kubernetes/kubernetes/issues/52890#issuecomment-331772925

**Comment by huydinhle** [comment]
@dims  I'm not saying the log is incorrect, I agree with the design. However, can we have maybe an extra flag so that the logs that come out with the same time unit (eg: milliseconds) . 

Thank you for replying.

**Comment by huydinhle** [comment]
Since I need this particular feature, if you think the feature make senses, I can dig in and work on it also

**Comment by dims** [comment]
@huydinhle looks like you need a nod from @liggitt (not me!)

**Comment by tallclair** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/52981 to use microsecond precision timestamps in audit logs

**Comment by andrewgdavis** [comment]
code that utilizes "k8s.io/apiserver/pkg/server/httplog" Log() will be pretty printed due to the default to String in time.go.   An optional config for a time unit format might be passed down through apiserver/pkg/server/config.go to the genericfilters.WithPanicRecover(handler, c.XXXX), and implemented in httplog.go.  
however, that begs the question:  should the default be "as is: aka  pretty print" so as not to break those that rely on the current behavior; or should a standard time unit be applied as default, and be uniform across logging / auditing components.

**Comment by CaoShuFeng** [comment]
> Our logging team wants to standardize on one time unit only

I suggestion to use the audit feature of kuberenetes to gather logs ahout http request.
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by crassirostris** [comment]
@huydinhle FYI, what you're referring to are not audit logs. Audit logs are described [here in the documentation](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)

Using advanced auditing you can get the latency with ms precision by subtracting [`RequestReceivedTimestamp`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1beta1/types.go#L127) from [`StageTimestamp`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1beta1/types.go#L130)
