### ISSUE TITLE
NFS PV recycler unverified

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53413]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

If a pod is already running in the default namespace with the expected name (i.e. `recycler-for-VOL`), the PV recycle method just assumes it's a recycler pod. However, if it is not a recycler, it could result in the volume being reused without the data being cleared.

**What you expected to happen**:

The recycled volume should not be reused until the data has been verifiably deleted. The easiest approach would be to make it an error to not run the recycler pod successfully, i.e. delete these lines:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util.go#L83-L85
I think that should be safe, since the recycler will retry.

Other errors in that method should also be considered fatal, e.g.:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util.go#L92

**Comment by jeffvance** [comment]
How about generating a unique name for each recycler pod so that it doesn't matter what existing pods are named?

**Comment by saad-ali** [comment]
@childsb Could someone from your team pick this up?

**Comment by childsb** [comment]
Ack

**Comment by jsafrane** [comment]
OpenShift runs the recycler pod in a dedicated namespace, not visible to users. Maybe it could be a good idea to do so also in Kubernetes.

Anyway, killing the old recycler is probably the best option - it could be forged by user to block recycling and cheat quota.

/assign

**Comment by tallclair** [comment]
Agree with running in a dedicated namespace, but it sounds like this feature is just being deprecated, so it might not be worth the effort. Thanks for picking this up.
