### ISSUE TITLE
emptyDir volume does not empty in pod after physical node restart

### ISSUE THREAD

**Issue by at1984z** [kubernetes/kubernetes#53423]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
1. StatefulSet with emptyDir volume in pod spec and a container with a volumeMount onto that volume.
2. StatefulSet is created at scale 1 and the only pod is placed on a physical node.
3. This physical node reboots and comes back in less than 5 minutes fully operational.
4. The pod restarts on the same node.
5. emptyDir volume keeps the data from before restart.

**What you expected to happen**:
1. Expect the emptyDir volume to be empty.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create StatefulSet spec with one container that has one volumeMount onto a volume of type emptyDir.
2. The container entry point checks to see if a file present in the volumeMount and if the file is present writes "second time" into the file; otherwise, creates the file and writes "first time"; continues to "sleep inifinity" in either case.
3. Create one replica of the StatefulSet.
4. Reboot the physical node where the replica resides.
5. Check the contents of the file after the node completes reboot.

**Anything else we need to know?**:
1. Init container in such StatefulSet does execute in the described experiment.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.0
- Cloud provider or hardware configuration**: Intel(R) Xeon(R) CPU E5-2690 v3 24 cores; Ubuntu 16.04 LTS; Vagrant 1.9.3; VirtualBox 5.1.22
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):  Linux 4.4.0-96-generic
- Install tools: kubeadm 1.8.0-01
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
@at1984z, can you please share your statefulset yaml? It's odd that emptyDir keeps its data across reboots.

**Comment by msau42** [comment]
I think it is actually expected for the emptydir to remain because the Pod never got deleted from the node.

**Comment by at1984z** [comment]
@jsafrane, I will distill our production code into the minimal example and post it here. We encountered this behavior on k8s 1.5 first. Since, we're planning to move to 1.7.4, I've checked that the behavior is the same there as well. Moreover, both 1.5 and 1.7.4 do not execute Init containers either in the described scenario.

@msau42, although I see your point, I'd disagree, especially in light of the pod going through Init container execution in the described scenario. I'd perceive this fact as indication that new cycle of the pod's life starts and its emptyDir volumes are to be emptied as per the documentation. Should the described behavior be by design, it warrants a special note in the emptyDir volume description in the documentation.

**Comment by jingxu97** [comment]
Just add a little detail. When node reboots, since kubelet could not respond to master for a few minutes, node status is updated to "NotReady". From master point of view, it does not what is happening on the node, so after 5 minutes timeout, master node controller tries to evict pods (it might not succeed if kubelet is still not responding. Pod status will become unknown)

In your case, since reboot takes less than 5 minutes, pods are not touched which means that pods are still in api server showing running state. When node comes back and kubelet starts working, it will get pod list from api server and start the pod and its containers according to the pod spec. So during this time, no tear down of emptyDir will be triggered. (emptyDir tear down is triggered only if pod is deleted or terminated)

I am not very sure about your init container problem. Could you provide more details? Thanks!

**Comment by rootfs** [comment]
emptyDir defaults to medium, set emptyDir medium to memory will wipe the data after reboot

```yaml
volumes:
- name: foo
  emptyDir:
        medium: "Memory"
```

**Comment by at1984z** [comment]
@jingxu97, Can I interpret your description of emptyDir behavior in the described case as "by design"? That is it is not a bug but a feature.

@jingxu97, In k8s 1.5 and 1.7, Init container does not run in the described case when the node reboot and kubelet restart takes less than 5 minutes. In k8s 1.8, Init container does run.

@rootfs, This is a good workaround for emptyDir volumes of limited size. It will not work for the volumes of significant sizes. Another workaround is to wipe the emptyDir volume in Init container, although it will work in k8s 1.8 only, because Init container does not run in k8s prior 1.8 in the described case.

**Comment by at1984z** [comment]
@jsafrane, I've uploaded the file as shown below.
[sset-edir.yaml.gz](https://github.com/kubernetes/kubernetes/files/1357078/sset-edir.yaml.gz)
Should you confirm the emptyDir volume behavior as presented by @jingxu97, the issue could be closed.

**Comment by msau42** [comment]
While emptydir behavior is by design, maybe init container behavior is a bug.

**Comment by at1984z** [comment]
@msau42, re: Init Container - is it a bug in 1.8 or prior 1.8?

**Comment by msau42** [comment]
Since you see the issue in 1.8 and not 1.7, I would guess 1.8.

**Comment by at1984z** [comment]
@msau42, re: Init container behavior in a pod residing on physical node that reboots in less than 5 min.

In k8s version prior 1.8, Init container does not run upon physical node restart.
In k8s version 1.8, Init container does run upon physical node restart.

Which behavior is correct?

**Comment by msau42** [comment]
Can someone from @kubernetes/sig-node-bugs comment on the intended init container behavior?

**Comment by jingxu97** [comment]
cc @yujuhong

**Comment by Random-Liu** [comment]
> In k8s version prior 1.8, Init container does not run upon physical node restart.
In k8s version 1.8, Init container does run upon physical node restart.

I think the second one is the expected behavior now. https://github.com/kubernetes/kubernetes/pull/47599

**Comment by jingxu97** [comment]
@Random-Liu thanks for the information. Do we consider to cherrypick this PR back to 1.7 and earlier? It looks like a bug..

**Comment by yujuhong** [comment]
> Do we consider to cherrypick this PR back to 1.7 and earlier? It looks like a bug..

Unlikely. This (i.e., rerunning init containers) was never implemented since it was added, and the fix #47599 contains a lot of refactoring which is not appropriate for cherrypicks.

**Comment by msau42** [comment]
Sounds like this is intended behavior.  Can we close this issue?

**Comment by at1984z** [comment]
@msau42 The issue can be closed.

**Comment by msau42** [comment]
Thanks

/close
