### ISSUE TITLE
Cannot change 'default' Storage Class on Azure Disk /

### ISSUE THREAD

**Issue by lauxtermann-aram** [kubernetes/kubernetes#53428]
**BUG REPORT**:

/kind bug
/sig azure

**What happened**:
I cannot change the default storage class in Kubernetes v1.8.0 on azure. Everytime I run:

`kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`

I get the response that everything is done correctly: storageclass "default" patched.
`kubectl get storageclass`

After that I get:
```
default (default)            kubernetes.io/azure-disk
managed-premium              kubernetes.io/azure-disk
managed-standard (default)   kubernetes.io/azure-disk
```
I already set my managed disk as default, but everytime after 5 seconds it makes the default also a default, which mean that I have two default storage classes and that I cannot do any helm installs anymore.

Seeing how I used the ACS-Engine to make ARM templates and that I use managed disk I cannot use the default storage class.

**What you expected to happen**:
I expected the default class to be changed to:
`managed-standard (default)   kubernetes.io/azure-disk
`
Not having two default Storage classes

**How to reproduce it (as minimally and precisely as possible)**:

1. Set another storage class as default: 
`kubectl patch storageclass <other_class> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

2. Remove the default storage class label from the default.
`kubectl patch storageclass default -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'`

3. Wait 5 seconds and now you have:

```
default (default)            kubernetes.io/azure-disk
managed-premium              kubernetes.io/azure-disk
managed-standard (default)   kubernetes.io/azure-disk
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.0
- Cloud provider or hardware configuration**: Azure

**Comment by andyzhangx** [comment]
@lauxtermann-aram For setting default storage class, you should first edit file, set the default class as false
```
sudo vi /etc/kubernetes/addons/azure-storage-classes.yaml
```
And then continue your operation, let me know if that works, thx

**Comment by lauxtermann-aram** [comment]
@andyzhangx : Thank you for the advice, I works perfectly! 👍

**Comment by andyzhangx** [comment]
@lauxtermann-aram would you close this issue? thx

**Comment by OJezu** [comment]
@andyzhangx On which host is this file located, and how do I get there?

**Comment by andyzhangx** [comment]
I think you should edit the same file on all masters, otherwise it may be not consistent.

**Comment by andyzhangx** [comment]
BTW, with acs-engine v0.10.0 or above, the default storage class will be consistent with what your k8s cluster type, e.g. the default will be managed storage class if you create a managed k8s cluster.
