### ISSUE TITLE
Kubefed can't handle relative paths in kubeconfig

### ISSUE THREAD

**Issue by Thermi** [kubernetes/kubernetes#53431]
/kind bug

**What happened**:
Kubefed doesn't handle relative paths in kubeconfig correctly, like kubectl does.

**What you expected to happen**:
That kubefed handles it like kubectl.

**How to reproduce it (as minimally and precisely as possible)**:
Use relative paths in kubeconfig for credentials (e.g. CA certificates). Then use kubectl to see that it works from arbitrary directories. Then try to use kubefed and see it fail.

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+0b9efaeb34a2f", GitCommit:"638b0a06d928e7a12fa29bb12610158a235585d7", GitTreeState:"dirty", BuildDate:"2017-10-02T09:48:25Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
GCP
- OS (e.g. from /etc/os-release):
Ubuntu Xenial
- Kernel (e.g. `uname -a`): Irrelevant
- Install tools: GKE

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#8.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
