### ISSUE TITLE
kube-proxy/node-proxier clusterrole broken in 1.8

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubernetes#53433]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG
/kind bug

**What happened**:
After upgrading from v1.7.5 to v1.8.0, my kube-proxies (running as static pods) stopped working.
kube-proxy log shows:
```
E1004 13:09:44.836719       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.Endpoints: endpoints is forbidden: User "system:node-proxier" cannot list endpoints at the cluster scope
```

**What you expected to happen**:
It should be able to get necessary information to operate

**How to reproduce it (as minimally and precisely as possible)**:
Create kube-proxy certs with the following title: /CN=system:node-proxier/O=system:node-proxier

**Anything else we need to know?**:
I tried the following combinations with the same results:
CN=system:node-proxier/O=system:node-proxier
CN=kube-proxy/O=system:node-proxier
CN=system:node-proxier:nodeID/O=system:node-proxier

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.0
- Cloud provider or hardware configuration**: none
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: kubespray
- Others:

**Comment by liggitt** [comment]
This role is automatically granted to the `system:kube-proxy` user (see https://kubernetes.io/docs/admin/authorization/rbac/#core-component-roles), which has not changed since 1.7

If you want to define a `system:node-proxier` user, you must bind the role to that user with a deployment-specific clusterrolebinding:
```
kubectl create clusterrolebinding node-proxier-binding \
  --clusterrole=system:node-proxier \
  --user=system:node-proxier
```

**Comment by mattymo** [comment]
The correct cert subject is `CN=system:kube-proxy/O=system:node-proxier`

**Comment by kalise** [comment]
Hello,
I'm facing a similar issue with v1.8.1.
APIs server manually started without RBAC but only with Node authorizer:
`  --admission-control=NamespaceLifecycle,ServiceAccount,LimitRanger,DefaultStorageClass,ResourceQuota \
  --authorization-mode=Node \`

I get this error:
`systemctl status kube-proxy -l
...
kube-proxy[29050]: E1029 14:11:39.060323   29050 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:73: Failed to list *api.Endpoints: endpoints is forbidden: User "system:kube-proxy" cannot list endpoints at the cluster scope
...`

The kube-proxy certificate is:
`openssl x509 -in kube-proxy.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            46:a4:2e:b2:07:38:8e:3e:75:ed:b9:d1:f9:0c:b5:55:38:5b:e2:d4
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=IT, ST=Italy, L=Milan, O=Clastix Certification Authority, CN=clastix
        Validity
            Not Before: Oct 29 18:44:00 2017 GMT
            Not After : Oct 29 18:44:00 2018 GMT
        Subject: O=system:node-proxier, CN=system:kube-proxy
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
`
By enabling the RBAC in addition to Node authorizer, the kube-proxy user is authorized.
Thanks,

Adriano

**Comment by liggitt** [comment]
> By enabling the RBAC in addition to Node authorizer, the kube-proxy user is authorized.

That is the recommended configuration

**Comment by kalise** [comment]
@liggitt not a big deal but disagree with this. Why force to use both the Node and RBAC at same time to get system working? I think this is something to fix.
Thanks

**Comment by liggitt** [comment]
The node authorizer authorizes kubelets only. If you have other components in the system, you need another authorizer to allow their requests. The RBAC authorizer does that by default if they are using standard usernames.

**Comment by liggitt** [comment]
> Why force to use both the Node and RBAC at same time to get system working?

You're not forced to.

You can use the permissive authorization mode if desired at the cost of subdivided API access between any components. 

You can use RBAC only, grant the system:node role to all kubelets at the cost of subdivided kubelet API access.

There's a variety of options available, but combining the Node and RBAC authorizers will work well for most.

**Comment by kalise** [comment]
@liggitt Thanks you are right. In my mind, if we have two options: Node and RBAC, I assume they are independent each other, i.e. it is possible to enable only Node without having to enable the RBAC and get the system working. Anyway, not a big deal. :)

**Comment by m1093782566** [comment]
If I want kube-proxy to watch its own node, what clusterrole I should bind to kube-proxy?

**Comment by liggitt** [comment]
> If I want kube-proxy to watch its own node, what clusterrole I should bind to kube-proxy?

can you point to where kube-proxy watches nodes? if so, that should be added to the node-proxier role.

**Comment by m1093782566** [comment]
Thanks @liggitt and I have figured it out.

**Comment by liggitt** [comment]
Watching nodes is expensive… do we plan to have kube-proxy on every node watch nodes?

**Comment by m1093782566** [comment]
> Watching nodes is expensive… do we plan to have kube-proxy on every node watch nodes?

I agree watching node is expensive. But, I just have no better idea... To clarify, I mean kube-proxy watch its own node just like what we did for kubelet so that the cost is reduced?
