### ISSUE TITLE
CustomResourceDefinition support for federation

### ISSUE THREAD

**Issue by ljmatkins** [kubernetes/kubernetes#53432]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When I attempt to `kubectl apply` a CustomResourceDefinition to a federation, I receive the following error:

```error: unable to recognize "resourcedefinition.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition```

**What you expected to happen**:

It would be nice if federations supported this resource type, so that we can run applications expecting it on top of federated clusters.

**How to reproduce it (as minimally and precisely as possible)**:

1) Bring up a federated cluster
2) Create a `resourcedefinition.yaml` file (e.g. https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/)
2) Run `kubectl apply -f resourcedefinition.yaml` against the federated cluster

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.6
- Cloud provider or hardware configuration: GKE 1.7.6-gke.1
- OS (e.g. from /etc/os-release): debian stretch

**Comment by quinton-hoole** [comment]
Sounds like a useful feature. @ljmatkins are you willing/able to submit a design proposal?

**Comment by ljmatkins** [comment]
While willing, I'm not yet sufficiently familiar with the k8s federation design to provide much input!

I had some vague sense that this could maybe "just work like ConfigMaps or Secrets" --
 although that might just be wishful thinking. 😄

**Comment by quinton-hoole** [comment]
@ljmatkins I think you're probably right, but someone would need to think through the details.
Even if you don't design the internal implementation, if you could describe what you would like it to look like from the outside (i.e. how the API would look and behave, in your ideal world), that would be useful.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#9.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
