### ISSUE TITLE
apiserver doesn't shutdown cleanly

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#53438]
/kind bug

The apiserver does not clean up after itself when it does a controlled shutdown.  This means things like the internal kubernetes service endpoints still contain the ip information for an apiserver that no longer exists.  The system will eventually rectify the situation, but until that occurs there can still be service disruption (ie dns lookups) that need not occur.  If the apiserver goes through a controlled shutdown then it should clean up after itself, like de-registering from the internal kubernetes service.

**Comment by rrati** [comment]
@sttts Feel this is appropriate for sig-api-machinery

**Comment by mbohlool** [comment]
Can you be more explicit about things that API Server should clean up? For DNS example, do you mean the dns entry for API Server itself?

**Comment by rrati** [comment]
@mbohlool One big thing the apiserver should clean up is the list of endpoints of the internal kubernetes service in an HA apiserver configuration.  If I am running 3 apiservers then the endpoint will have 3 ips.  If one of the masters is shutdown it should remove itself from that list of endpoint ips in the kubernetes service

**Comment by hzxuzhonghu** [comment]
There may be case all three apiservers is behind a LB, and the `advertise-address` is set the same vip. It is hard to judge if the 3 apiservers use the same `advertise-address`.
