### ISSUE TITLE
Move gke-certificates-controller out of the main repository

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#53439]
from here : https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L191
```
# TODO(pipejakob) gke-certificates-controller is included here to exercise its
# compilation, but it doesn't need to be distributed in any of our tars. Its
# code is only living in this repo temporarily until it finds a new home.
```

**Comment by dims** [comment]
Looks like it was added here : https://github.com/kubernetes/kubernetes/commit/0d7a6eb058a057dd7f8af485e4f56f1588004a12

**Comment by dims** [comment]
cc @pipejakob @mikedanese @roberthbailey @bgrant0607 @thockin

**Comment by roberthbailey** [comment]
@abgworrall - this is related to sig-gcp and moving our gcp/gke specific code out of the main repo.
