### ISSUE TITLE
FR: streaming audit endpoint

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53455]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**:

Provide a pull-based stream for audit logging. This would look similar to a watch request to the API server, and provide a stream of audit events. I would not expect the stream to return any PREVIOUS events (i.e. no associated storage), it would only stream events that occurred after the stream was opened. This would be a new audit backend plugin.

The should also have some options to filter events. Minimally, there should be a namespaced version that only includes audit events tied to that namespace, so that RBAC can be used to grant subdivided access. Secondarily, it might be nice to be able request only events tied to a given user or resource.

**Motivation**:

The current audit backends (log & webhook) require very high privileges (file access to the master) or prior configuration (webhook). There are a number of use cases for dynamic and unprivileged access to the audit logs. Examples include:

- [audit2rbac](https://github.com/liggitt/audit2rbac) - generate RBAC rules from audit logs. It would be nice to simply point this tool at a running cluster. With the namespace subdivision, an admin could grant developers working in a namespace access to their audit logs to use this tool, without granting the full cluster audit logs.
- Debugging - related to the above point, API audit logs can be very useful for debugging, and this would provide an option to surface a subset of the logs to developers.
- 3rd party audit plugins - This isn't a strong use case as the stream would be less reliable than the push-based webhook, but there might be other use cases for plugging in logging tools to the stream.

**Challenges**:

Audit logs can be very noisy, so there is a risk that providing this stream (and potentially multiple connections) could have a performance impact. Subdividing the audit logs (namespaces, resources, etc.) would help. We could also potentially restrict this to metadata-level, though that would negatively impact the debugging use case (maybe a request parameter?). Also, the stream should not have the reliability guarantees as the webhook & log backends, if the stream is congested events will be dropped.

/cc @crassirostris @liggitt @destijl @sttts @kubernetes/sig-auth-feature-requests

**Comment by mbohlool** [comment]
cc @caesarxuchao

**Comment by crassirostris** [comment]
Another important use case:

In current e2e test audit events are read from the log file. However, there are a couple of problems:

- In load tests, a lot of audit events are produced. Network problem when transferring GBs of data will cause the tests to fail
- Log file can be rotated during the tests, which also triggers failure
- Current implementation cannot be used in any environment, it's tightly coupled with the configuration in `k8s.io/cluster/gce`

**Comment by shyamjvs** [comment]
@crassirostris @loburm Can we turn back on the audit tests on large-scale now?

**Comment by crassirostris** [comment]
@shyamjvs Nope, this feature is a pre-requisite for enabling audit tests on large scale

/remove-lifecycle stale

**Comment by CaoShuFeng** [comment]
Hi, @tallclair 
I have some questions about the implemention detail:

> Provide a pull-based stream for audit logging. This would look similar to a watch request to the API server, and provide a stream of audit events.

This is a plugin work as a server which needs to bind a port?

> The should also have some options to filter events. Minimally, there should be a namespaced version that only includes audit events tied to that namespace, so that RBAC can be used to grant subdivided access. 

This require a authentication progress.
But I think authentication should not be as complex as the apiserver, we chose one authentication method in the first?

> it might be nice to be able request only events tied to a given user or resource.
Totally agree!!!

**Comment by CaoShuFeng** [comment]
Hi, I'd be happy to work on this if no one has startted it.

**Comment by CaoShuFeng** [comment]
> it might be nice to be able request only events tied to a given user or resource.

Since audit events are non-nanmespaced objects, how to use RBAC to implement access control for this stream?

**Comment by CaoShuFeng** [comment]
Hi.
#64494

**Comment by CaoShuFeng** [comment]
@tallclair @loburm 
I made a KEP for this pull request. Please take a look.
Thanks.
https://github.com/kubernetes/community/pull/2241

**Comment by liggitt** [comment]
given the HA implications, the inverse of this (dynamic audit webhook registration) seems preferable

**Comment by tallclair** [comment]
Agreed. What I would actually like to see is an out-of-tree implementation of this. An application that is registered as a dynamic audit webhook and serves the audit stream (maybe with an in-memory history cache). It could either serve a custom API, or register itself as an extension API server.

**Comment by liggitt** [comment]
Sounds good. Closing this here then. 

/close
