### ISSUE TITLE
k8s use of AWS load balancers is a little surprising

### ISSUE THREAD

**Issue by ismith** [kubernetes/kubernetes#53463]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

I have a Spinnaker Load Balancer, of type LoadBalancer, usually created by an upsertLoadBalancer pipeline stage.

```
ismith@spinnaker-i-019dfda7b7069eb39:~$ kubectl get svc svcrepro
NAME       CLUSTER-IP    EXTERNAL-IP        PORT(S)        AGE
svcrepro   10.32.0.128   aebb29dc3996b...   80:31231/TCP   1m
```

By default, this is an external load balancer, and we can see that in the EXTERNAL-IP column; it’s truncated, but that’s an AWS ELB hostname, and if it were an internal ELB, it’d start with internal-.

Per https://github.com/kubernetes/kubernetes/issues/17620, the way to create an internal ELB is to add the annotation ‘service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0’.  And if I create a svc of type LoadBalancer, with that annotation, I get an internal ELB:
```
ismith@spinnaker-i-019dfda7b7069eb39:~$ kubectl get svc svcrepro-internal
NAME                CLUSTER-IP   EXTERNAL-IP        PORT(S)        AGE
svcrepro-internal   10.32.0.98   internal-a965...   80:30961/TCP   27s
```

So.  I if I go back to svcrepro - which is an external ELB - I can `kubectl edit svcrepro` and add that annotation, and then `kubectl describe svcrepro` does show new CreatingLoadBalancer and CreatedLoadBalancer events.  And I would expect for it to switch `svcrepro`'s underlying AWS ELB from external to internal, but it does not.  (The same is true in reverse, going from internal ELB to external.)

**What you expected to happen**:

See above.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

Even if it's not feasible to have a change in annotation cause a recreate of the load balancer, it'd be nice if there were some sort of visible error or failure event.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.5.3:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
AWS

**Comment by ismith** [comment]
@kubernetes/sig-aws-bugs

**Comment by sergeylanzman** [comment]
@ismith  
I think you can't change Scheme for ELB in AWS. Need to recreate ELB, but if you recreate ELB you get new ELB DNS name and it's bad because you need update route53 and etc.

**Comment by ismith** [comment]
Yeah, that sounds correct.  In my use case, we've got `mate` - to be replaced with `external-dns` - managing route53, but that's definitely a thing.

**Comment by sergeylanzman** [comment]
OK, but
`mate` depricate. You can use `https://github.com/kubernetes-incubator/external-dns`, but not all people use it's, and if them change schema => recreate ELB=> new DNS => other surprises.

**Comment by ismith** [comment]
Right. I believe my initial report addresses this:
```
Even if it's not feasible to have a change in annotation cause a recreate of the load balancer, it'd be nice if there were some sort of visible error or failure event.
```

Another option would be to have a way (flag?) to force the re-creation.
