### ISSUE TITLE
PodSecurityPolicy should not apply to mirror pods

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53467]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Mirror pods may be rejected by the PodSecurityPolicy admission controller.

**What you expected to happen**:

Mirror pods are a reflection of a pod being run directly by the Kubelet, meaning that the pod will be run regardless of the admission decision.

**How to reproduce it (as minimally and precisely as possible)**:

Bring up a cluster with the PodSecurityPolicy admission controller enabled (see https://github.com/kubernetes/kubernetes/pull/52367). Note that the static pods are "missing" (e.g. `kubectly get pods -n kube-system kube-controller-manager-${master_name}`).

/cc @liggitt

**Comment by liggitt** [comment]
We have to be careful here… what happens in the following scenario:

1. a user sets a mirror pod annotation
2. noderestriction admission plugin is not used

**Comment by tallclair** [comment]
The mirror pod annotation can only be set at pod creation, and [can't be changed](https://github.com/kubernetes/kubernetes/blob/9de85c2eabe79a52b4ae05e2932cce81afb02aa9/pkg/api/validation/validation.go#L178). Since the Kubelet ignores mirror pods, creating one only causes it to exist in the API, it won't actually run any workloads. I don't think the noderestriction admission plugin is relevant here, since it only applies to identifiable node users?

**Comment by liggitt** [comment]
PSP is also useful for composing into other checks on operations like exec ("a user cannot exec into a pod they could not have created"). Short circuiting on an annotation still seems odd to me.

cc @kubernetes/sig-auth-pr-reviews @deads2k

**Comment by tallclair** [comment]
Mirror pods don't have service accounts, so the normal mechanism for binding a PSP to a system pod doesn't work. On the other hand, we could just bind the privileged PSP to the `system:nodes` group.

Also, this is common practice. A handful of other admission controllers short-circuit on the mirror pod annotation:
  https://github.com/kubernetes/kubernetes/blob/9af339885b68990a96470cc4350514d2a1ec30c8/plugin/pkg/admission/priority/admission.go#L141-L143
  https://github.com/kubernetes/kubernetes/blob/9af339885b68990a96470cc4350514d2a1ec30c8/plugin/pkg/admission/podpreset/admission.go#L104-L106
  https://github.com/kubernetes/kubernetes/blob/9af339885b68990a96470cc4350514d2a1ec30c8/plugin/pkg/admission/initialization/initialization.go#L183-L190
  https://github.com/kubernetes/kubernetes/blob/9af339885b68990a96470cc4350514d2a1ec30c8/plugin/pkg/admission/serviceaccount/admission.go#L156-L162

**Comment by tallclair** [comment]
RE: composing - Skipping the PSP check for pod admission doesn't preclude using the PSP object for something like checking exec. At the most, it would just mean the code would need to be restructured (or only do the mirror pod check for create / update / patch verbs).

**Comment by liggitt** [comment]
> Mirror pods don't have service accounts, so the normal mechanism for binding a PSP to a system pod doesn't work

Right, PSP permissions for a particular pod are the combined permissions of the user making the request (which lets a powerful user do things in a restricted namespace) and the pod's service account (which lets permissions be delegated to a particular namespace for use by any users that can create pods in that namespace)

> Also, this is common practice. A handful of other admission controllers short-circuit on the mirror pod annotation

I agree it shouldn't mutate mirror pods, but not all of those are complete short-circuits (for example, the serviceaccount check actually prevents mirror pods from doing some things)

> RE: composing - Skipping the PSP check for pod admission doesn't preclude using the PSP object for something like checking exec. At the most, it would just mean the code would need to be restructured

I'd rather make it an explicit option to let composers opt in or out of ignoring permissions on mirror pods

**Comment by tallclair** [comment]
The node will run the pod either way, independent of the admission decision. If the PSP blocks the creation of a privileged mirror pod, I think this actually makes the cluster _less_ secure, because it could give the admin a false sense of security and a less accurate view into the cluster functioning. Furthermore, it could destabilize the cluster since the scheduler no longer has an accurate picture of the resource usage.

I know there are workarounds (bind the privileged policy to the nodes group), but this adds one extra step to setting up a functioning PSP cluster and has more ways it can fail (admin changes privileged policy).

**Comment by kfox1111** [comment]
Just ran into this during an upgrade.... kubeadm looks for the mirror pods before continuing, and doesn't spit out an error when it can't find them. It would be nice if this was documented somewhere.
