### ISSUE TITLE
Add docs on the predicates that prohibit a node from receiving load balancer service traffic

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#53473]
/kind feature
/area cloudprovider

We should add docs to the CCM that explains the conditions under which a node will be excluded from receiving traffic. It's fairly magical right now.

[Code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L587)

cc @andrewsykim

**Comment by andrewsykim** [comment]
I definitely agree! This also applies to kube-controller-manager. I think we need to do a better job in general when it comes to documenting small implementation details like this that can affect cluster behaviour in this way.
