### ISSUE TITLE
GCE: LBs on 1.7 can enter sync retry loop due to existing IP

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#53475]
/kind bug

**What happened**:
If the cloud provider attempts to reserve an IP and it's already reserved, it should continue syncing. Instead, it's returning an error and causing the service controller to retry.

https://github.com/kubernetes/kubernetes/blob/862b0bc4fd0b5aa7ae9bcfd6cb5527cd54a3b301/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L943-L949

The above code only checks for 409 status code, but we need to also check for code 400. If I recall correctly, 409 happens for naming conflicts while 400 occurs for external address conflict.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a load balancer service
1. Promote address to static with a random name.
1. Cause an LB sync.

/sig network
/area platform/gce

**Comment by nicksardo** [comment]
@yujuhong I don't think we gain anything by backporting the `GetAddressByIP` func to 1.7, right? Checking for both status codes seems to be sufficient.

**Comment by yujuhong** [comment]
> @yujuhong I don't think we gain anything by backporting the GetAddressByIP func to 1.7, right?

Correct. It could be a minor performance optimization, but wouldn't help with the correctness.

> Checking for both status codes seems to be sufficient.

Agreed.

**Comment by nicksardo** [comment]
Actually, it's not sufficient. Right after that block of code, it tries to retrieve the address by name - a name which may be the user's. 
https://github.com/kubernetes/kubernetes/blob/862b0bc4fd0b5aa7ae9bcfd6cb5527cd54a3b301/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L943-L954

I'm thinking this issue is not worth fixing.
