### ISSUE TITLE
`pull-kubernetes-verify` failing with `verify-swagger-spec` failure 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#53481]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
[pull-kubernetes-verify](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-verify/) is consistently failing the `hack/verify-swagger-spec.sh` step with:

```
I1004 21:15:37.949]     /go/src/k8s.io/kubernetes/hack/../api/swagger-spec
I1004 21:15:38.681] +++ [1004 21:15:38] SUCCESS
I1004 21:15:38.692] +++ [1004 21:15:38] Clean up complete
I1004 21:15:38.692] diffing /go/src/k8s.io/kubernetes/api/swagger-spec against freshly generated swagger spec
I1004 21:15:38.698] diff -Naupr -I 'Auto generated by' /go/src/k8s.io/kubernetes/api/swagger-spec/apps_v1.json /go/src/k8s.io/kubernetes/_tmp/swagger-spec/apps_v1.json
I1004 21:15:38.698] --- /go/src/k8s.io/kubernetes/api/swagger-spec/apps_v1.json	2017-10-04 21:15:38.112158862 +0000
I1004 21:15:38.698] +++ /go/src/k8s.io/kubernetes/_tmp/swagger-spec/apps_v1.json	2017-10-04 20:21:31.853618584 +0000
I1004 21:15:38.698] @@ -2503,7 +2503,7 @@
I1004 21:15:38.698]       },
I1004 21:15:38.698]       "kind": {
I1004 21:15:38.699]        "$ref": "v1.AzureDataDiskKind",
I1004 21:15:38.699] -      "description": "Expected values Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared"
I1004 21:15:38.699] +      "description": "Expected values Shared: mulitple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared"
I1004 21:15:38.699]       }
I1004 21:15:38.699]      }
I1004 21:15:38.700]     },
I1004 21:15:38.721] /go/src/k8s.io/kubernetes/api/swagger-spec is out of date. Please run hack/update-swagger-spec.sh
I1004 21:15:38.726] FAILED   hack/make-rules/../../hack/verify-swagger-spec.sh	39s
```

**What you expected to happen**:
`pull-kubernetes-verify` should not be failing. 

**How to reproduce it (as minimally and precisely as possible)**:
Look at `pull-kubernetes-verify` failed runs.

**Anything else we need to know?**:
Nope

**Comment by saad-ali** [comment]
Appears to be related to PR https://github.com/kubernetes/kubernetes/pull/49205
But that PR was merged on Oct 3, 8:17 PM PT and this test appears to have started failing on Oct 3 1:20 PM PT

CC @dixudx @ericchiang @jbeda @roberthbailey

**Comment by dixudx** [comment]
@saad-ali The error lay in `swagger-spec/apps_v1.json`, which is a new file introduced by #53278. That's why the batch CI gets failed. We need to get the file `swagger-spec/apps_v1.json` updated by rebasing the master branch and regenerating it.

**Comment by janetkuo** [comment]
FWIW #53278 is not merged yet. We can close this bug.
