### ISSUE TITLE
possibility to ignore cinder dynamic provision volume label

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#53488]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
/kind feature

**What happened**: Currently if we create cinder volumes dynamically, the zone label is added automatically to pv https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder_util.go#L214-L216 . After the zone label is added to volume, it means that pod cannot be started in any other zone than what label says. Volume zone label is kind of nodeselector to pod.

**What you expected to happen**: I except that we could override this setting. We have use-case where we have compute zone names: zone-1, zone-2 and zone-3, but then cinder volume zone name is nova. It means that dynamic provision does not work if we do not manually always remove pv label after creation. I except that we could have possibility to not add this volume label to cinder. After that pod can be provisioned in any zone because it does not have label.

So I suggest that we add flag `ignore-volume-label` to openstack cloudprovider.conf which will override this label thing.
 
**How to reproduce it (as minimally and precisely as possible)**: create cinder volume dynamically, and check labels.

**Comment by FengyunPan** [comment]
SGTM
