### ISSUE TITLE
Add metrics for total time spent in attach and detach

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#53494]
We should have a metrics for total time spent in attach and detach. This is different from operation metrics we are capturing currently, which captures time it took for attach or detach operation to succeed.

These metrics will capture total time overall it takes for a volume to be attached once it enters desired_state_of_world.  So basically, time taken for volume to appear in actual_state_of_world from desired_state_of_world.

Simiarly, for detach - this metric will capture time taken for volume to be removed from actual_state_of_world after it has been removed from desired_state_of_world.

/sig storage

**Comment by wenlxie** [comment]
+1

**Comment by gnufied** [comment]
The issue is still relevant. Will open PR shortly.

/remove-lifecycle stale
