### ISSUE TITLE
ABAC service account does not respect wildcard in name

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#53496]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
ABAC does not respect a wildcard in the serviceaccount. E.g. if I want _all_ service accounts in `kube-system` namespace to have full access to everything:

```json
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "system:serviceaccount:kube-system:*", "namespace":"*", "resource":"*", "apiGroup":"*", "nonResourcePath": "*"}}
```

No service accounts have access now.

**What you expected to happen**:
All serviceaccounts in `kube-system` would have full access.

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:
Nope.

It is possible that I misunderstood the docs and that wildcards are not allowed there (which would be a pain, but survivable).

**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.5

- Cloud provider or hardware configuration**:
AWS

**Comment by liggitt** [comment]
Wildcards in user and group names are not supported. 

Use the `system:serviceaccounts:kube-system` group to refer to all service accounts in the kube-system namespace

**Comment by deitch** [comment]
> Wildcards in user and group names are not supported

Aha. Thank you @liggitt . 

> Use the system:serviceaccounts:kube-system group to refer to all service accounts in the kube-system namespace

I know you already closed this, but perhaps we should reopen and rename it "Documentation missing on how to refer to all service accounts in a namespace"?

**Comment by liggitt** [comment]
Sure, I thought we already had that documented

**Comment by liggitt** [comment]
https://kubernetes.io/docs/admin/authentication/#service-account-tokens:

> Service accounts authenticate with the username **system:serviceaccount:(NAMESPACE):(SERVICEACCOUNT)**, and are assigned to the groups **system:serviceaccounts** and **system:serviceaccounts:(NAMESPACE)**.

**Comment by deitch** [comment]
Nice catch @liggitt thanks. I misunderstood that part.

Well, works for me. We need to switch to RBAC soon anyways.
