### ISSUE TITLE
client-gen creates the wrong group name in typed/{group}/{version}/fake package

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/kubernetes#53498]
**What happened**:
I have a Custom Resource Definition which I access using a generated clientset. I re-ran the client-gen command today and now my unit tests have broken (in addition to directories moving). I tracked down the error to GroupName being assumed to be {group} from the path rather than the defined GroupName variable in the codebase. This is a problem because I have set GroupName to "mygroup.mydomain.io", but the fake gets generated with a group name of "mygroup" as taken from the path.

**What you expected to happen**:
I expected the fakes to use GroupName as set in register.go in my API definitions directory.

**How to reproduce it (as minimally and precisely as possible)**:
go install k8s.io/code-generator/cmd/client-gen
client-gen \
  --input-base {myrepo}/pkg/api \
  --input "mygroup/v1" \
  --output-base ${GOPATH}/src \
  --clientset-name clientset \
  --clientset-path {myrepo}/pkg/client

**Anything else we need to know?**:
I previously ran the code generation on Sept 14 (or maybe 13?) and the generated code worked correctly, however, github.com/kubernetes/code-generators appears to have diverged drastically from the binary I ran at the time.

**Comment by briantkennedy** [comment]
@kubernetes/sig-api-machinery

**Comment by sttts** [comment]
@briantkennedy can you link to a small example showing the issue in code?

In kube we have for example networking.k8s.io with the external types at https://github.com/sttts/kubernetes/tree/84290ce35c4c5edfe2d1fdb0a105d30f00e2c5de/pkg/apis/networking/v1 and the fake client at https://github.com/sttts/kubernetes/blob/e6be341a644185a47b41a04883a7537a165bb3c9/staging/src/k8s.io/client-go/kubernetes/typed/networking/v1/fake/fake_networkpolicy.go#L35. The GroupName is correct.

Note this line: https://github.com/sttts/kubernetes/blob/b0b5de6eaf547ebe3fe5d4fc17cf6004a4b94c75/pkg/apis/networking/v1/doc.go#L22. Do you use that tag as well?

**Comment by mrIncompetent** [comment]
I ran into the same issue.
Adding the tag `// +groupName=nodeset.k8s.io` in the doc.go fixed it for me.
Though the tag must be directly above the package name. No new line allowed.
Otherwise it didn't worked.

**Comment by briantkennedy** [comment]
It turned out we added a docstring to the package and moved the "// +groupName" line out of the package docstring. On moving it back things are working fine again.

Thanks for the quick response, it was helpful.

**Comment by sttts** [comment]
@briantkennedy great to hear. Closing the issue.
