### ISSUE TITLE
Certificate error after changing IP address of kubernetes master machine

### ISSUE THREAD

**Issue by Frank-auckland** [kubernetes/kubernetes#53509]
/kind bug

**What happened**:
I deploy the kubernetes on AWS by using juju, the command shows as follow:

> juju deploy kubernetes-core

The juju status show as follow:
![screenshot from 2017-10-06 10-38-30](https://user-images.githubusercontent.com/20473627/31253767-91d1bc60-aa82-11e7-92a8-6cb7cf39acc2.png)

Then I change the IP address of the kubernetes master machine. After this, I can't connect to kubernetes.
It responded an error message as follow:

> Unable to connect to the server: x509: certificate is valid for 13.124.194.81, 172.31.20.111, 10.152.183.1, not 13.125.7.33

**What you expected to happen**:
I expected the connection between kube client and kube service is normal.
**How to reproduce it (as minimally and precisely as possible)**:
Change the kubernetes master instance IP address.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
AWS
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux frank-ThinkPad-L570 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
juju version is 2.2.4-xenial-amd64
- Others:

@justinsb

**Comment by XericZephyr** [comment]
Having the same issue. No idea how to fix it.
