### ISSUE TITLE
Emit client and server versions directly from e2e.test

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#53502]
`kubetest` currently emits the client and server versions it detects, but ideally we'd like to compare the server version with the client version *compiled into `e2e.test`*, and we'd also like to emit this in contexts where `kubetest` might not be involved.  (Currently https://github.com/heptio/kube-conformance which we use for official conformance testing is not using `kubetest`, but we hope to stop doing that.)

/kind feature
/assign

**Comment by mml** [comment]
@fejta in case you have any objections to this change.  Also, to maybe help me understand either (1) who is roughly "the owner" of the e2e binary (not the tests), and (2) where's the best place to inject this code?

**Comment by timothysc** [comment]
This is needed to 1.8 conformance testing, so I've bumped as cherry-pick.
