### ISSUE TITLE
resource-quotas units do not match

### ISSUE THREAD

**Issue by podollb** [kubernetes/kubernetes#53503]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind/feature
/sig cli

**What happened**:

When issuing the `kubectl get quota` the units of the output are different. It would be nice if the `Used` and `Hard` units were the same.

**What you expected to happen**:

Force the units to be the same, or allow them to optionally be the same via command line arg.

**How to reproduce it (as minimally and precisely as possible)**:

```
Name:			compute-resources
Namespace:		neptune-test
Resource		Used		Hard
--------		----		----
configmaps		17		100
limits.cpu		10700m		12
limits.memory		15616Mi		32Gi
persistentvolumeclaims	0		0
pods			6		50
replicationcontrollers	0		0
requests.cpu		2450m		10
requests.memory		8576668672	28Gi
resourcequotas		1		10
secrets			4		100
services		7		20
services.loadbalancers	0		0
services.nodeports	1		1
```

**Anything else we need to know?**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by podollb** [comment]
I guess I must not be doing that right.

**Comment by wackxu** [comment]
I would help fit it.

**Comment by wackxu** [comment]
I think it is just the intent of design for the authors. You can see the comment below

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L55-#L74
> Before serializing, Quantity will be put in "canonical form".

The output is the format that fit the "canonical form", so the units of quantity looks different sometimes.

**Comment by wackxu** [comment]
@nikhita Great, This should be removed, I can help fix this.

**Comment by nikhita** [comment]
@wackxu just created https://github.com/kubernetes/kubernetes/pull/60626 :grimacing:
