### ISSUE TITLE
Setting log-driver to journald breaks kubectl logs on GKE

### ISSUE THREAD

**Issue by aosmith** [kubernetes/kubernetes#53501]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: `kubectl logs` is broken after switching log driver to journald 

1.6.10
--

**What you expected to happen**: `kubectl logs` should work.

**How to reproduce it (as minimally and precisely as possible)**:  Spin up a new cluster on GKE via web UI.  Change the log-driver via `/etc/default/docker`.  Restart docker service.  Logs now appear in the journal but `kubectl logs` no longer works. 

**Anything else we need to know?**:
When running `kubectl logs` it seems like it's looking for the wrong file.  From my local:
```
kubectl logs heapster-v1.3.0-1288166888-25ppw --namespace=kube-system heapster
failed to open log file "/var/log/pods/43d5ebdf-a9fc-11e7-814c-42010a8001bf/heapster_1.log": open /var/log/pods/43d5ebdf-a9fc-11e7-814c-42010a8001bf/heapster_1.log: no such file or directory%
```
On the kubelet:
```
gke-testing2-default-pool-2715550c-149w 43d5ebdf-a9fc-11e7-814c-42010a8001bf # ls -lah
total 16K
drwxr-xr-x 2 root root 4.0K Oct  5 18:37 .
drwxr-xr-x 6 root root 4.0K Oct  5 18:37 ..
lrwxrwxrwx 1 root root  165 Oct  5 18:37 heapster-nanny_0.log -> /var/lib/docker/containers/f57d396fd31e6b3d5d5eb60475d2b42aa182b4866d55fb50a9eadc5efe181c67/f57d396fd31e6b3d5d5eb60475d2b42aa182b4866d55fb50a9eadc5efe181c67-json.log
lrwxrwxrwx 1 root root  165 Oct  5 18:37 heapster_0.log -> /var/lib/docker/containers/6815b08ccf1c2c4c465ee02b720bbb75477266ad8f65e752e251a4691138e809/6815b08ccf1c2c4c465ee02b720bbb75477266ad8f65e752e251a4691138e809-json.log
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.10-gke.1", GitCommit:"5399ab6217c2f2f4bb4de52a2a23ccc4cd034df2", GitTreeState:"clean", BuildDate:"2017-09-27T18:06:48Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
Same behavior with 1.7.5.

- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release):
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_RELEASE_BOARD=lakitu-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=90
CHROMEOS_RELEASE_BUILDER_PATH=lakitu-release/R60-9592.90.0
CHROMEOS_RELEASE_BUILD_NUMBER=9592
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=60
CHROMEOS_RELEASE_DESCRIPTION=9592.90.0 (Official Build) stable-channel lakitu
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9592.90.0
DEVICETYPE=OTHER
GOOGLE_RELEASE=9592.90.0
HWID_OVERRIDE=LAKITU DEFAULT
BUILD_ID=9592.90.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c0dda75c2c06905ff4a2e8b41de27d4f2d773856
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=60
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=60
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`): `Linux gke-testing2-default-pool-2715550c-149w 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux`
- Install tools:
- Others:

**Comment by aosmith** [comment]
For anyone else that finds this issue: It's really more a docker problem than a k8s problem, The solution  is dropping a custom systemd docker config with an init script.  Rebooting the docker daemon via `systemctl restart docker` is the problem, without an init script most changes are not persisted on an os level.

**Comment by jvassev** [comment]
Hi,
This is really a kubelet problem. The /containerLogs endpoint [expects](https://github.com/kubernetes/kubernetes/blob/b98d9407cfdc24c477ab8066d1fb69ea0983a2f9/pkg/kubelet/kuberuntime/logs/logs.go#L280) to find a log file in `/var/log/pods/...` as mentioned in the first comment.

On EKS, using journald as log-driver works as expected. Their fork of k8s contains traces if a journal library used:

```
kubelet --version
Kubernetes v1.16.8-eks-e16311

strings `which kubelet`
k8s.io/kubernetes/vendor/github.com/coreos/go-systemd/journal.appendVariable
k8s.io/kubernetes/vendor/github.com/coreos/go-systemd/journal.appendVariable.stkobj
k8s.io/kubernetes/vendor/github.com/coreos/go-systemd/journal.conn
....
```

Probably makes more sense to mention in the docs that only the `json-file` is currently supported.
