### ISSUE TITLE
Kubeadm 1.8.0 fails when cloud-provider and cloud-config are specified

### ISSUE THREAD

**Issue by SIGUSR2** [kubernetes/kubernetes#53504]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Bootstrapping new master node using kubeadm in a cloud environment fails due to kube-apiserver not having access to /etc/kubernetes/cloud-config. 

Kubeadm hangs at  
```
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
```
kube-apiserver doesn't start due to 
```
F1005 19:56:17.861521       1 plugins.go:115] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config", Err:0x2} 
```
**What you expected to happen**:
Cluster would start

**How to reproduce it (as minimally and precisely as possible)**:

```
cat > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf <<EOF
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=100.64.0.10 --cluster-domain=example.com"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true"
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud-config"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
EOF
```

```
cat > /etc/kubernetes/cloud-config <<EOF
[Global]
auth-url=http://10.11.12.13:35357/v3
region=myregion
tenant-name=mytenant
tenant-id=<insert UUID here>
domain-id=<insert UUID here>
username=openstack_user
password=******
EOF
```

```
cat > /etc/kubernetes/kubeadm.yaml <<EOF
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.8.0
networking:
  podSubnet: 172.17.0.0/16
  dnsDomain: example.com
  serviceSubnet: 100.64.0.0/16
cloudProvider: openstack
EOF
```

```
# use skip-preflight-checks to avoid kubeadm complaining that /var/lib/kubelet isn't empty
kubeadm init --config /etc/kubernetes/cloud-config --skip-preflight-checks
[ ... ]
# hangs
# ctrl + c 
docker logs $(docker ps -a | grep kube-apiserver | awk '{ print $1 }' | head -n1)
I1005 19:56:17.861203       1 server.go:114] Version: v1.8.0
I1005 19:56:17.861426       1 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
F1005 19:56:17.861521       1 plugins.go:115] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config", Err:0x2} 
```

**Anything else we need to know?**:
Setting external-hostname doesn't do any good, apiserver still fails, same error. Changing the `/etc/kubernetes/pki` mount to `/etc/kubernetes` in the kube-apiserver.yaml after kubeadm is stopped allows the apiserver to start. 

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**: openstack (probably valid in other clouds too)
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux head-ubuntu16 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Others:

**Comment by SIGUSR2** [comment]
cc  @kubernetes/sig-cluster-lifecycle-bugs

**Comment by jbeda** [comment]
Duplicate of https://github.com/kubernetes/kubeadm/issues/484
