### ISSUE TITLE
top pod and top node output is unstable ordered

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#53513]
`kubectl top pod` and node should sort by namespace / name so that results don't jump around.  We should consider adding sort, but only after we make a stable sort the default.

@kubernetes/sig-cli-bugs

**Comment by smarterclayton** [comment]
```
$ kubectl top nodes
NAME                  CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
origin-ci-ig-n-kkhm   839m         10%       16765Mi         56%
origin-ci-ig-n-kwtq   308m         3%        15457Mi         51%
origin-ci-ig-m-11v4   224m         11%       4648Mi          64%
```

```
NAME                  CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
origin-ci-ig-m-11v4   229m         11%       4652Mi          64%
origin-ci-ig-n-kwtq   382m         4%        15456Mi         51%
```

Also, why does it sometimes lose nodes?  Annoying

**Comment by dixudx** [comment]
> Also, why does it sometimes lose nodes? Annoying

@smarterclayton I did not reproduce this. I think this may be caused by the monitoring timeout of heapster. So that the data got missing.
