### ISSUE TITLE
code-generator: create stable and more extensible cli interface for top-level scripts – "kube-gen"

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#53524]
The scripts https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/generate-groups.sh and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/generate-internal-groups.sh were created to provide a standardized way of calling the generators for 90% of the CRD and UAS usa-cases. The command-line interface is simplistic, driven by the bash implementation rather than stability and extensibility in mind:

```shell
$ generate-groups.sh <generators> <output-package> <internal-apis-package> <extensiona-apis-package> <groups-versions> ...
```

I.e. the options are positional without flags syntax. Adding another option is impossible. Because https://github.com/kubernetes/kubernetes/pull/53449 should go into 1.8 as early as possible to give CRD users a tool to create especially deepcopy funcs easily, a proper Go implementation was out of reach because it is needs more changes, e.g. in Gengo (now merged). But mid-term we probably want to convert this to Go.

It was also suggested to turn k8s.io/code-generator into a Docker container to make it even easier to 3rdparties to generate code for Kubernetes style api types:

```shell
$ docker run -v $GOPATH:/go k8s.io/code-generator:1.8 generate-group github.com/foo/bar example:v1
```

Another line of thought is the question how and whether to use this also in Kubernetes itself instead of our pretty complex `Makefile.generated_files` mechanism.

**Comment by mml** [comment]
cc @pwittrock 

I'm also curious about how we might implement this.  Are we planning to make it a bazel target so that it can execute incrementally?

**Comment by pwittrock** [comment]
@mml just saw the comment.  I had a similar idea to what you suggest, and think that would be really cool to build, as well as providing some lower level tools the bazel rules could leverage.

**Comment by pwittrock** [comment]
@sttts where should this go?

https://github.com/kubernetes/code-generator/pull/17

**Comment by sttts** [comment]
> where should this go?

Usually into the community repo or even just as google doc. I would not commit it into k/code-generator.

**Comment by pwittrock** [comment]
@ssts move to kubernetes/community#1315

**Comment by mml** [comment]
ITYM @sttts

**Comment by sttts** [comment]
@pwittrock is this work stalled?

**Comment by sttts** [comment]
This turned into kubebuilder.
