### ISSUE TITLE
Upgrade to 1.8 left corrupted checkpoints

### ISSUE THREAD

**Issue by outcoldman** [kubernetes/kubernetes#53532]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
```
apt-get update && apt-get dist-upgrade
reboot
```
Only after I did ^ I started to read https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-8/

> Upgrading the kubeadm package on your system prior to upgrading the control plane causes a failed upgrade. 

But unfortunately there were no notes about what if you already got into this situation. In my case kube cluster was corrupted already (Master node was not ready).

I tried to run an upgrade for kubeadm

```
$ sudo kubeadm config upload from-flags [some flags I used (pod network)]
$ sudo kubeadm upgrade plan
[preflight] Running pre-flight checks
[upgrade] Making sure the cluster is healthy:
[upgrade/health] Checking API Server health: Healthy
[upgrade/health] Checking Node health: More than one Node unhealthy
[upgrade/health] FATAL: The cluster is not in an upgradeable state due to: there are NotReady Nodes in the cluster:
```

Checked the logs and have found issue with swap flag

```
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained:
```

Updated my kubelet config.

My node became Ready so I followed upgrade procedure, upgrade from 1.7.4 succeeded to 1.8.0.

After that all my pods failed to start with

```
Oct  5 19:52:26 outcoldbuntu kubelet[1136]: E1005 19:52:26.372706    1136 remote_runtime.go:115] StopPodSandbox "4e866f1867e52770b060441e23a58b4ab388a3a4f66b5f28a77ec74fd1c9501a" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "licenseserver-4096630682-8twvn_default" network: could not retrieve port mappings: checkpoint is corrupted.
Oct  5 19:52:26 outcoldbuntu kubelet[1136]: E1005 19:52:26.372748    1136 kuberuntime_manager.go:780] Failed to stop sandbox {"docker" "4e866f1867e52770b060441e23a58b4ab388a3a4f66b5f28a77ec74fd1c9501a"}
Oct  5 19:52:26 outcoldbuntu kubelet[1136]: E1005 19:52:26.372855    1136 kuberuntime_manager.go:580] killPodWithSyncResult failed: failed to "KillPodSandbox" for "69fbeb11-91c1-11e7-a34f-bc5ff44b93f5" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"licenseserver-4096630682-8twvn_default\" network: could not retrieve port mappings: checkpoint is corrupted."
Oct  5 19:52:26 outcoldbuntu kubelet[1136]: E1005 19:52:26.372907    1136 pod_workers.go:182] Error syncing pod 69fbeb11-91c1-11e7-a34f-bc5ff44b93f5 ("licenseserver-4096630682-8twvn_default(69fbeb11-91c1-11e7-a34f-bc5ff44b93f5)"), skipping: failed to "KillPodSandbox" for "69fbeb11-91c1-11e7-a34f-bc5ff44b93f5" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"licenseserver-4096630682-8twvn_default\" network: could not retrieve port mappings: checkpoint is corrupted."
```

After browsing the code I have found that it is better to have missing checkpoints than to have checkpoints with broken checksums https://github.com/kubernetes/kubernetes/blob/50fa5637b6dc9538c908fbdd632ff1d3c59f65da/pkg/kubelet/dockershim/docker_service.go#L325

So I just removed all the checkpoints under `/var/lib/dockershim/sandbox/*`

**What you expected to happen**:

1. Kubelet/kubeadm should not require disabling swap. At minimum not in upgrade.
2. Kubelet/kubeadm should not generate checkpoints with broken checksums in upgrades (not sure what can cause that). 
3. In case of broken checksums there are should be better way to get out of this situation.

**How to reproduce it (as minimally and precisely as possible)**:

I assume to try steps from above^

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by karlbunch** [comment]
Just experienced this exact issue.

* Kubernetes version (use kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Cloud provider or hardware configuration: [bare metal packet.net](https://www.packet.net/bare-metal/servers/type-2-virtualization/)

* OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
* Kernel (e.g. uname -a):
```
4.10.0-24-generic #28~16.04.1-Ubuntu SMP Wed Jun 14 11:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
## Workaround:
```
sudo rm /var/lib/dockershim/sandbox/*
```

Thanks @outcoldman for that, you saved me untold hours of golang digging.

**Comment by albertvaka** [comment]
I have the same messages in my logs. Is it safe to remove all the checkpoints under `/var/lib/dockershim/sandbox/*` ?
