### ISSUE TITLE
cni.go:119] Error loading CNI config file /etc/cni/net.d/10-calico.conf: error parsing configuration: invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by ylfforme** [kubernetes/kubernetes#53536]
i started calico fellow this page https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted and i get the cni config in /etc/cni/net.d，it‘s in json format。but i get this error in kubelet
cni.go:119] Error loading CNI config file /etc/cni/net.d/10-calico.conf: error parsing configuration: invalid character '}' looking for beginning of object key string
did i do something wrong？
this is the config
{
    "name": "k8s-pod-network",
    "type": "calico",
    "etcd_endpoints": "http://10.127.0.1:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s",
        "k8s_api_root": "http://172.16.0.3:8080",
    },
    "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
}
my kubernetes version is 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
and calico image is：
quay.io/calico/node:v1.0.2
calico/kube-policy-controller:v0.5.2
calico/ctl:v1.0.2

**Comment by dixudx** [comment]
@ylfforme Your json file is not valid. **Redundant comma** after `"k8s_api_root": "http://172.16.0.3:8080"`.

The valid json content should be

```json
{
	"name": "k8s-pod-network",
	"type": "calico",
	"etcd_endpoints": "http://10.127.0.1:2379",
	"log_level": "info",
	"ipam": {
		"type": "calico-ipam"
	},
	"policy": {
		"type": "k8s",
		"k8s_api_root": "http://172.16.0.3:8080"
	},
	"kubernetes": {
		"kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
	}
}
```

**Comment by ylfforme** [comment]
thank you very much
