### ISSUE TITLE
Service name not resolved after pod deployment update.

### ISSUE THREAD

**Issue by saivarunr** [kubernetes/kubernetes#53539]
I have a pod named 'frontend' with two containers ui and server in it, and a single service 'server' exposing them of type loadbalancer.

ui exposing on port 4200 and server exposing port 5000

After a recent update of the pods, using kubectl apply, with in the pod service 'server' couldn't be resolved, I don't know why,

when I say curl http://server:5000 it just waits and dies where as for http://localhost:5000 i would get the response,

it's not the case for the services which are not of this pod, I can access other services example:
curl http://spark:8080 would give me the response from the same pod.

Help me out here, thanks!

/sig network

**Comment by cmluciano** [comment]
Can you please update this issue with your kubernetes server version and what CNI plugin you are using?

It would also me helpful if you can post your pod and service specs (redactions where appropriate)

**Comment by saivarunr** [comment]
@cmluciano Did my side of researc

**Comment by saivarunr** [comment]
@cmluciano did my research on the issue, found the kube-proxy pod for the node on which these pods were deployed turned to **evicted** status


Service Spec:
Name:			frontend
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		app=frontend
Type:			LoadBalancer
IP:			100.64.241.208
Port:			ui	80/TCP
NodePort:		ui	31266/TCP
Endpoints:		100.96.6.2:4200
Port:			server	5000/TCP
NodePort:		server	32504/TCP
Endpoints:		100.96.6.2:5000
Session Affinity:	None
Events:			<none>


Pod spec:
Name:		frontend-547394297-nz1xn
Namespace:	default
Node:		<>
Start Time:	Thu, 12 Oct 2017 14:13:05 +0530
Labels:		app=frontend
		pod-template-hash=547394297
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"frontend-547394297","uid":"5d8ab15a-af29-11e7-88c7-1223f4bdeb24","api...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container xserver; cpu request for container ui
Status:		Running
IP:		100.96.6.2
Created By:	ReplicaSet/frontend-547394297
Controlled By:	ReplicaSet/frontend-547394297
Containers:
  server:
    Container ID: <>
    Image:		<>
    Image ID: <>
    Port:		5000/TCP
    Command: <>
    State:		Running
      Started:		Thu, 12 Oct 2017 14:14:09 +0530
    Ready:		True
    Restart Count:	0
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-s9690 (ro)
  ui:
    Container ID: <>
    Image:		<>
    Image ID: <>
    Port:		4200/TCP
    Command: <>
    State:		Running
      Started:		Thu, 12 Oct 2017 14:15:16 +0530
    Ready:		True
    Restart Count:	0
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-s9690 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-s9690:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-s9690
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	node_name=front_end_node
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:		<none>


I had to restart the node on which the kube-proxy evicted and then had to re-deploy to make sure it was working again. 
My bad I do not have logs of evicted kube-proxy pod! 

The node is a t2-medium

**Comment by cmluciano** [comment]
Node eviction is normally due to other applications on the node fighting for resources like CPU and Memory. Does this help at all?

**Comment by saivarunr** [comment]
@cmluciano is there a prescribed way of re-starting evicted pods, especially the pods of kube-system like kube-proxy? I had to restart the node itself!

**Comment by cmluciano** [comment]
Check what is eating up the memory during the time that they were evicted. Evicted pods should land elsewhere unless there are conditions like taints, whereby this would depend on specific nodes being available.

**Comment by cmluciano** [comment]
Take a look here https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/
