### ISSUE TITLE
kubeadm init with aws config complains missing ClusterID

### ISSUE THREAD

**Issue by tcederquist** [kubernetes/kubernetes#53538]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
New k8 cluster on aws by hand following docs at : https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
Also using config file for aws in a file and referece the file in init.
Fails to start - stalls while creating kube-controller-manager with:

     I1006 16:48:11.421975       1 controllermanager.go:109] Version: v1.8.0
     I1006 16:48:11.425600       1 leaderelection.go:174] attempting to acquire leader lease...
     I1006 16:48:11.437910       1 leaderelection.go:184] successfully acquired lease kube-system/kube-controller-manager
     W1006 16:48:11.438141       1 controllermanager.go:138] --use-service-account-credentials was specified without providing a --service-account-private-key-file
     I1006 16:48:11.439510       1 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"0f517bd9-aaac-11e7-8da7-0e6d35421f60", APIVersion:"v1", ResourceVersion:"2946", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-172-30-0-69.aws-ermas.com became leader
     I1006 16:48:11.457749       1 aws.go:847] Building AWS cloudprovider
     I1006 16:48:11.457836       1 aws.go:810] Zone not specified in configuration file; querying AWS metadata service
     E1006 16:48:11.672185       1 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
     W1006 16:48:11.672207       1 tags.go:78] AWS cloud - no clusterID filtering applied for shared resources; do not run multiple clusters in this AZ.
     F1006 16:48:11.672265       1 controllermanager.go:151] error building controller context: no ClusterID Found.  A ClusterID is required for the cloud provider to function properly.  This check can be bypassed by setting the allow-untagged-cloud option

I cannot find any documentation on setting ClusterID. Where would I put the allow-untagged-cloud option? Cannot find documentation on this either. Classified as a bug either in documentation or default settings blocking the master from starting on a bare bones install using the supplied documentation.

**What you expected to happen**:
Master to form and become ready. The docs work fine until AWS is specific in the config file.

**How to reproduce it (as minimally and precisely as possible)**:
- Create file: ~/kubeadm.conf
    - kind: MasterConfiguration
    - apiVersion: kubeadm.k8s.io/v1alpha1
    - cloudProvider: aws

kubeadm init --config kubeadm.conf

review the pod for the kube-controller-manager

**Anything else we need to know?**:

- Technically the master machine is realm joined. The machine is registered by its realm name not the amazon name and the kubectl get nodes shows the realm name of the machine, not the ec2 instance name.
- Also noticed the certificates are registered as the wrong machine name. @dreyk noted might be related to #44793. From another case #47695 that triggered my rebuilding the cluster to this point.

**Environment**:
- Kubernetes version (use `kubectl version`):

     Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
     Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:

     AWS on t2-medium ec2 instance

- OS (e.g. from /etc/os-release):

     CentOS Linux 7 (Core)

- Kernel (e.g. `uname -a`):

     Linux ip-172-30-0-69.aws-ermas.com 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by dreyk** [comment]
Do you have provider configuration?
/etc/kubernetes/cloud-config
```
[Global]
KubernetesClusterTag=my-cluster
KubernetesClusterID=my-cluster
```

**Comment by tcederquist** [comment]
@dreyk - thanks for the quick response! No file there so I added as suggested with read access and its stuck on the waiting for control plane, the container for kube-apiserver isn't starting with logs:

     [root@ip-172-30-0-176 ~]# docker logs 8dd8f7db18f5
     I1006 20:13:44.938083       1 server.go:114] Version: v1.8.0
     I1006 20:13:44.938255       1 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
     F1006 20:13:44.938273       1 plugins.go:115] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config", Err:0x2}
     [root@ip-172-30-0-176 ~]# getenforce
     Permissive

**Comment by petergardfjall** [comment]
I ran into this issue also. I managed to get it to work without using a `--cloud-config` file. But that requires you to adhere to some conventions of the aws cloud-provider. Most notably, you need to tag your AWS resources related to your Kubernetes cluster with a `kubernetes.io/cluster/<cluster-name>` tag (the tag value appears irrelevant). In this particular case, the master instance needs to have such a tag set. If no such tag is found, the aws provider will search for a "legacy" cluster tag, which can be specified in a cloud-config file as described by @dreyk [above](https://github.com/kubernetes/kubernetes/issues/53538#issuecomment-334847780).

The relevant code is found here: https://github.com/kubernetes/kubernetes/blob/v1.8.3/pkg/cloudprovider/providers/aws/tags.go#L108-L109

**Comment by vinayk06** [comment]
I was facing same issue.
I added tags to the ec2 instances, either through ASG or to the instance directly. I am using terraform. 
this resolved me the issue.
