### ISSUE TITLE
Device plugin should only handle allocations of resources managed by it

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#53548]
The resources managed by device plugin are a subset of the extended resources. The device plugin should only handle the resources managed by it, instead of all extended resources

https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/kubelet/cm/device_plugin_handler.go#L169

https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/kubelet/deviceplugin/utils.go#L57-L61

/kind bug
/assign @jiayingz 
/cc @vishh

**Comment by jiayingz** [comment]
Thanks a lot for reporting this issue, @yguo0905 ! I have a PR https://github.com/kubernetes/kubernetes/pull/53547 that hopefully can resolve this issue for 1.8. We still need to better handle device plugin resource cleanup in 1.9, which will be tracked in issue https://github.com/kubernetes/kubernetes/issues/53395.

**Comment by jiayingz** [comment]
Fixed with PR https://github.com/kubernetes/kubernetes/pull/53547
/close
