### ISSUE TITLE
Get the stats of container logs in kubelet for summary API

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#53549]
Kubelet has been changed to get the container stats from CRI for the new container runtimes, like containerd and cri-o. However, this does not include the stats of the container logs.

https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/kubelet/stats/cri_stats_provider.go#L235-L236

Since the kubelet passes the container log name to CRI. We can get the stats of the container logs in kubelet.

/assign
/cc @Random-Liu @yujuhong 
/sig node

**Comment by yujuhong** [comment]
> Since the kubelet passes the container log name to CRI.

Minor correction: pass the "container log path"

Thanks for filing an issue for this!

**Comment by yujuhong** [comment]
Closing this issue in favor of #55905, which has more details.
