### ISSUE TITLE
User-added NoSchedule taint causes eviction of DaemonSet

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#53556]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

/kind bug

**What happened**:

User added a NoSchedule taint to a node. It caused eviction of DaemonSet.

See https://groups.google.com/d/msg/kubernetes-users/me5A_6DOtn8/rQGeTTK2AQAJ for more details.

**What you expected to happen**:

NoSchedule should never cause eviction. That's why it's called NoSchedule, not NoExecute.

I think the problem is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1279). We should not set wantToRun to false if predicates.ErrTaintsTolerationsNotMatch is due to NoSchedule taint. (It's fine to set shouldSchedule to false.)

/cc @kubernetes/sig-cluster-lifecycle-bugs @gmarek

**Comment by k82cn** [comment]
It should be fixed in 1.7+ by https://github.com/kubernetes/kubernetes/commit/e3f40f3d229b55e59e33a54b0cfc809af730e071 .

**Comment by timothysc** [comment]
Yup, closing... feel free to reopen if another condition exists.  

/assign timothysc
