### ISSUE TITLE
Kubectl 1.8 does not work with minikube

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#53552]
This is a placeholder for kubernetes/minikube#1996 this is a known issue with minikube configuring openapi incorrectly.

Note: kubectl works with non-minikube Kubernetes clusters, this is just a configuration issue with minikube.

This issue will not be fixed in kubectl, but is just a placeholder for folks that run into the minikube issue.

**Comment by pwittrock** [comment]
cc @mehdy @apelisse

**Comment by pwittrock** [comment]
@kubernetes/sig-cli-bugs

**Comment by monopole** [comment]
Im using kubectl 1.8.2 to talk to minikube v0.23.0
https://github.com/kubernetes/minikube/issues/1996 appears closed.
