### ISSUE TITLE
Validate swagger spec on each commit

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#5356]
Once https://github.com/GoogleCloudPlatform/kubernetes/issues/4083 is fixed, we should include swagger validation as part of our tests.

It will probably be a lot easier when we move to swagger spec 2.0 as we will then be able to use the online validator (http://online.swagger.io/validator/)

**Comment by mbohlool** [comment]
The Swagger/OpenAPI spec is valid and tested here https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master_openapi_test.go on each commit. The old swagger 1.2 is deprecated and will be removed.
