### ISSUE TITLE
kube-proxy config should move out of ComponentConfig apigroup

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#53577]
As per mtaufen:

... when kube-proxy moves its configuration type out of ComponentConfig, they should move the validation code along with it. Validation code should live near the type it validates, and at present the KubeProxyConfiguration type still lives in ComponentConfig.

As an example of how to remove a type from ComponentConfig (and ALL components should be removing their configuration types from this api group, by the way), see what we did for KubeletConfiguration: #49051 followed by #50789.

**Comment by xiangpengzhao** [comment]
/assign
for kube-proxy part (KubeProxyConfiguration).
The other left part is the kube-scheduler (KubeSchedulerConfiguration), cc @guangxuli may be interested in it.

**Comment by guangxuli** [comment]
@xiangpengzhao okay, i will work on this.
