### ISSUE TITLE
apimachinery: add api to get the PATCH version of running k8s

### ISSUE THREAD

**Issue by prat0318** [kubernetes/kubernetes#53582]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**: Referring to [the original feature request added to helm charts](https://github.com/kubernetes/helm/issues/3013), we want to have different prometheus scraping endpoints for cadvisor for pre 1.7.2 and post 1.7.2 (like 1.7.3). Helm charts capabilities only provide us the MINOR version and not the PATCH version.

**What you expected to happen**: Able to query the PATCH version of kubernetes cluster.

**How to reproduce it (as minimally and precisely as possible)**:
If we look at [the API objects](https://github.com/kubernetes/apimachinery/blob/3b05bbfa0a45413bfa184edbf9af617e277962fb/pkg/version/types.go#L22-L32), the only ones listed are MAJOR and MINOR.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2 and 1.7.3

**Comment by prat0318** [comment]
@kubernetes/sig-api-machinery -feature-requests

**Comment by prat0318** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
At that level, I'd probably recommend semver comparisons against gitVersion

**Comment by mml** [comment]
@pwittrock I think we have code that does this already.  Can you confirm?
