### ISSUE TITLE
Deprecate rkenetes in favor of rktlet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#53601]
rktnetes is the old, in-tree rkt integration. [rktlet](https://github.com/kubernetes-incubator/rktlet) is new integration via CRI. 
We should deprecate and remove the rktnetes integration once rktlet is ready to take over.

Based on the [deprecation policy](https://kubernetes.io/docs/reference/deprecation-policy/), I think we can announce the deprecation of rktnetes once rktlet is ready, and remove the integration after one more release.

/cc @kubernetes/sig-node-bugs 
@lucab @iaguis @kinvolk, who have been working on rktlet
@euank @yifan-gu, who are the owners of rktnetes
@philips @thockin @dchen1107

**Comment by resouer** [comment]
cc @Crazykev who once asked me about this confusion and I suggest him to do a clean up. >_<

**Comment by Crazykev** [comment]
@resouer Thanks, very glad to do the clean up part.  @yujuhong Is there any plan for deprecation part?

**Comment by yujuhong** [comment]
> @yujuhong Is there any plan for deprecation part?

It depends on the progress of rktlet. The folks who are currently working on rktlet and are migrating off rktnetes would be a better source.

**Comment by dchen1107** [comment]
It was included in sig-node's 1.9 planning draft, and discussed at sig-node meeting. It was removed for 1.9 because 1) the user (for example: blablacar) is currently depending on it 2) rktlet is under development. We can announce the deprecation now to prevent more users from using it. Once rktlet is done, we can remove it completely.

**Comment by iaguis** [comment]
We're currently working towards an initial rktlet release, which will be tested by Blablacar. We'll give an update next week with the progress.

**Comment by yujuhong** [comment]
@iaguis what's the current progress of the rktlet release?

**Comment by yujuhong** [comment]
@iaguis thanks for the update!

I don't think rktnetes ever supports attach or port forward, so I don't think they should be the blocker for deprecating rktnetes.
Adding @yifan-gu @euank to confirm.

**Comment by yujuhong** [comment]
@iaguis @lucab (rktlet maintainers), I'd like to aim at officially deprecating rktnetes in k8s v1.10 (and encourage users to move to rktlet). 
Do you think this is reasonable? We can discuss more in the sig node meeting or on slack if you have concerns.

**Comment by yujuhong** [comment]
From the today's sig-node meeting, current rktlet maintainers (@iaguis, etc) mentioned that they may not have spare cycles to work on rktlet this release, but even as of today, rktlet already passes more tests than rktnetes. Given that, I propose we deprecate rktnetes in 1.10, and remove the code in the next release.

The deprecation process includes
 - Send out a deprecation announcement to kubernetes-users@, kubernetes-dev@, and kubernetes-sig-node@ with links to rktlet.
 - Add deprecation warning to kubelet when --container-runtime is set to rkt.

Can someone from the CoreOS (owner of rktnetes and initiator of rktlet) comment on whether the plan is okay? @philips @yifan-gu @euank

**Comment by yujuhong** [comment]
> @philips @yifan-gu @euank

/cc @jonboulle

**Comment by yifan-gu** [comment]
LGTM on my side.

**Comment by jonboulle** [comment]
I haven't been involved in active rkt development for a while, but this plan sounds fine to me based on everything I know about the latest rktnetes work.

**Comment by iaguis** [comment]
The plan sounds good to me. The only concern I have is whether Blablacar needs rktnetes for a longer time (cc @slallema).

**Comment by yujuhong** [comment]
> The plan sounds good to me. The only concern I have is whether Blablacar needs rktnetes for a longer time (cc @slallema).

I'd love to hear Blablacar's feedback on this.

At the same time, I think it might be reasonable for Blablacar not to upgrade kubernetes until they are ready. There hasn't been much active development in rktnetes, so staying on a known, good version, is better than upgrading kubernetes anyway IMO.

**Comment by yujuhong** [comment]
> LGTM, do you need any help from our side?

I think the rktnetes maintainers are the best candidate to send out the deprecation announcement :-)

Adding deprecation warning is trivial. If anyone wants to help, that'd be great.

**Comment by slallema** [comment]
Sorry for the delay, I was off last week.
We (BlaBlaCar) are moving away from rktnetes implementation so it's ok for us if it gets deprecated.
Thanks for asking :)

**Comment by yujuhong** [comment]
@yifan-gu has sent out the announcement.

Will close this once the PR gets merged.

**Comment by uablrek** [comment]
```
E0612 14:14:45.609710     201 remote_runtime.go:69] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
E0612 14:14:45.609797     201 kuberuntime_manager.go:172] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
F0612 14:14:45.609832     201 server.go:262] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
```

Seems like `rktlet` is dead and does not support >v1.10. It may be more honest to users to simply say "rkt is no longer supported"?
