### ISSUE TITLE
Deprecate cAdvisor port in K8s

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#53615]
I would like to remove the cAdvisor UI & API from Kubernetes. Motivations include:

- cAdvisor port is unauthenticated, and can leak internal cluster information
- We may eventually move away from embedded cAdvisor (as part of the migration to CRI)
- Alternatives exist (run a standalone cAdvisor daemon set in the cluster)

/cc @kubernetes/sig-node-bugs @kubernetes/sig-instrumentation-bugs

**Comment by piosz** [comment]
SGTM
Can we make sure that:
- standalone cadvisor deployment is ready (especially the deployment files exist)
- the information is widely broadcasted

Also, correct me if I'm wrong, but this means that there will be no more resource usage metrics in Prometheus `/metrics` endpoint.

cc @fabxc @brancz

**Comment by fgrzadkowski** [comment]
Excuse my ignorance, but does it affect /summary endpoint that heapster is
using?

--
Filip

**Comment by fabxc** [comment]
I think cAdvisor uses the global Prometheus metric registry, so as long as the kubelet imports some cAdvisor package adding metrics to that, the general `/metrics` endpoint will still expose them.  
Ideally that should not be the case since a standalone daemon set is preferable.

**Comment by brancz** [comment]
> this means that there will be no more resource usage metrics in Prometheus /metrics endpoint.

Starting with the `1.7.3` release those metrics are not available in the `/metrics` endpoint anymore, but the `/metrics/cadvisor` endpoint.

> I think cAdvisor uses the global Prometheus metric registry, so as long as the kubelet imports some cAdvisor package adding metrics to that, the general /metrics endpoint will still expose them.

I believe there was a refactoring in cAdvisor at some point, that allowed injecting a metrics registry, but I might be wrong.

> Excuse my ignorance, but does it affect /summary endpoint that heapster is using?

I believe a migration for this is what is meant in the description of the issue by "as part of the migration to CRI". This is something that will need to be either supported by the kubelet and/or by the CRI.

**Comment by yujuhong** [comment]
I believe the intention of this issue is to remove the port that exposing the cadvisor API and UI directly. It should not affect kubelet's summary API nor prometheus metrics endpoint for *existing* integration. 

In the future for non-docker runtimes integrating through CRI, we will turn off the embedded cadvisor's container stats collection. kubelet will then get the container metrics from the runtime directly through CRI. In that case, naturally a lot of cadvisor prometheus stats (regarding containers) will no longer be valid. That said, this is beyond the scope of this issue.

**Comment by brancz** [comment]
> kubelet will then get the container metrics from the runtime directly through CRI.

I was not aware that the CRI can be used to retrieve these metrics for containers. Could you link me to documentation/design for these?

**Comment by yujuhong** [comment]
> I was not aware that the CRI can be used to retrieve these metrics for containers. Could you link me to documentation/design for these?

https://github.com/kubernetes/community/blob/master/contributors/devel/cri-container-stats.md

**Comment by brancz** [comment]
> https://github.com/kubernetes/community/blob/master/contributors/devel/cri-container-stats.md

Neat, I didn't know this! Unfortunately I looked into the existing implementations and realized, that none of the implementations implement those calls today.

**Comment by brancz** [comment]
This is still applicable, and something we should work towards. Concrete things that need to be done:

* describe to users how one can use the `/metrics/cadvisor` endpoint on the secure handler of the kubelet
* implement stats endpoints for CRI providers (at least dockershim)

The first one primarily takes documentation and examples (and as it happens I'm already working on that), and the second one I also have on my list, but don't know when I'll get to it, so if someone is up for it feel free to grab it.

/remove-lifecycle stale

**Comment by tallclair** [comment]
> implement stats endpoints for CRI providers (at least dockershim)

That's definitely good to do, but I don't think it's a blocker for removing the cAdvisor endpoint. We can disable the endpoint while still runnnig cAdvisor internally to scrape the metrics.

**Comment by astefanutti** [comment]
I have an application that access cAdvisor data via the `/stats` endpoint exposed by the Kubelet. Unfortunately, it seems it does not work since Kubernetes 1.8.0, see #56297.

As a work-around, the application access cAdvisor directly from the exposed port `/api/v1/nodes/${node}:4194/proxy/api/v1.2/docker/${id}`.

So I see this as a blocker until #56297 is fixed.

**Comment by brancz** [comment]
@tallclair agreed. The `/metrics/cadvisor` endpoint on the secure handler is what people should be using in any case.

**Comment by astefanutti** [comment]
@brancz sure. cAdvisor provides short-term historical metrics which is very useful. That'd be ideal to have an equivalent historical metrics API (at least the last samples over a short-term moving window like cAdvisor exposes).

**Comment by brancz** [comment]
We're about to start discussing a well defined historical metrics API in sig-instrumentation :slightly_smiling_face:. Similar to the already existing resource and custom metrics API.

**Comment by brancz** [comment]
/remote-lifecycle stable

This is still to be done, but I think we have general consensus in sig-instrumentation to move forward with the deprecation within the kubelet. If the stats APIs are interesting to anyone, they can still deploy the daemonset. I'm not sure about dockershim, but cri-o does implement the CRI stats endpoints in 1.10.

Nonetheless dockershim is still the default so we should make sure the endpoints are implemented there before moving forward with this deprecation.

**Comment by brancz** [comment]
Those would certainly be good to fix :slightly_smiling_face:, but without the runtime implementing the stats endpoints, even when the above ones are fixed we're gonna error out with "unimplemented". I'm not sure dockershim has them implemented yet, but iirc there was some graceful handling, where if the runtime returns unimplemented, then cadvisor is asked. I'd like to make sure we don't do that anymore and for everything to still work with defaults, the dockershim implementation must also support the stats endpoints.

**Comment by astefanutti** [comment]
With the container stats endpoint fixed, deprecating the cAdvisor port is less impacting. Still, indeed, the endpoint implementation accesses cAdvisor directly and the CRI stats provider seems to rely on cAdvisor as well.

**Comment by brancz** [comment]
> CRI stats provider seems to rely on cAdvisor as well

Yes I’m aware that some CRIs Import cadvisor do to this, not great, but at least they “only” use it as a library, and some are also not doing this so I’d say we’re getting closer to getting rid of it.

**Comment by sjenning** [comment]
I think this is done right?
https://github.com/kubernetes/kubernetes/issues/56523
https://github.com/kubernetes/kubernetes/pull/59827
https://github.com/kubernetes/kubernetes/pull/63881
https://github.com/kubernetes/kubernetes/pull/65707

**Comment by brancz** [comment]
Yes it is.

**Comment by tallclair** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/56523
