### ISSUE TITLE
Implement windows kernel mode proxier UTs

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#53639]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Currently, upstream CI doesn't run any UT for windows kernel mode proxier. I feel like it's import to implement some UTs for window kernel mode proxier. 

I ALWAYS have some bandwidth and would love to contribute codes.

@kubernetes/sig-network-misc @thockin @bowei @dcbw wdyt? ^_^

@madhanrm Could you please help review PRs? :)

**What you expected to happen**:

1. mock something needed to run UTs for windows kernel mode proxier **everywhere**.

2. add some test cases.

3. remove `+build windows` flag in `winkernel/proxier_test.go`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network
/area kube-proxy

**Comment by m1093782566** [comment]
I find the most challenging part is that `winkernel/proxier.go` doesn't abstract `hcsshim` which is unable to run in !windows platform

**Comment by m1093782566** [comment]
@brendandburns @jdumars

**Comment by brendandburns** [comment]
Yeah, we should probably abstract that out...
