### ISSUE TITLE
Container spec hash changed. Container will be killed and recreated.

### ISSUE THREAD

**Issue by jmastr** [kubernetes/kubernetes#53644]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

During the update from v1.7.1 to v1.8.0 all docker containers were restarted, because container spec hash changed.

**What you expected to happen**:

No restart of the docker containers, because they did not change at all.

**How to reproduce it (as minimally and precisely as possible)**:

- get yourself a k8s cluster in v1.7.x
- update (at least the kubelet) to v1.8.0 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl get nodes`):
```
$ kubectl get nodes
NAME                                             STATUS    ROLES     AGE       VERSION
ip-172-22-250-20.eu-central-1.compute.internal   Ready     <none>    56m       v1.8.0
ip-172-22-250-21.eu-central-1.compute.internal   Ready     <none>    55m       v1.7.1
```
- Cloud provider or hardware configuration**:

AWS

- OS (e.g. from /etc/os-release):

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.2.0
VERSION_ID=1409.2.0
BUILD_ID=2017-06-19-2321
PRETTY_NAME="Container Linux by CoreOS 1409.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):

`Linux ip-172-22-250-20.eu-central-1.compute.internal 4.11.6-coreos #1 SMP Mon Jun 19 22:57:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux`

- Install tools:
- Others:

**Comment by jhorwit2** [comment]
👍 I ran into this earlier today. I was able to update the control plane & kube-proxy to 1.8.1 without any problems. Once I upgraded the kubelet though it caused container restarts.

**Comment by jmastr** [comment]
@jhorwit2 the log message one receives is at: https://github.com/kubernetes/kubernetes/blob/v1.8.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L508

The function, that calculates the hashes is at: https://github.com/kubernetes/kubernetes/blob/v1.8.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L408

```
func containerChanged(container *v1.Container, containerStatus *kubecontainer.ContainerStatus) (uint64, uint64, bool) {
	expectedHash := kubecontainer.HashContainer(container)
	return expectedHash, containerStatus.Hash, containerStatus.Hash != expectedHash
}
```

The hash function seems to not have changed. I suspect changes in the `container *v1.Container` object itself, which is at: https://github.com/kubernetes/kubernetes/blob/v1.8.0/pkg/api/types.go#L1753

One can see:
```
$ git diff v1.7.1..v1.7.8 --stat -- pkg/api/types.go
 pkg/api/types.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
but:
```
$ git diff v1.7.8..v1.8.0 --stat -- pkg/api/types.go
 pkg/api/types.go | 402 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 1 file changed, 350 insertions(+), 52 deletions(-)
```

**Comment by hzxuzhonghu** [comment]
But the new added field does not initiated, so the restart seems unreasonable.

**Comment by leopoldxx** [comment]
@hzxuzhonghu the result i tested was that the spew pkg also dumps the new add field(with nil value) to the hasher.
```
VolumeMounts:([]v1.VolumeMount)[{Name:(string)log ReadOnly:(bool)false MountPath:(string)/logs SubPath:(string) MountPropagation:(*v1.MountPropagationMode)<nil>}]
```
`MountPropagation` is the new added field.
so, if the container use `VolumeMounts`, then new MountPropagationMode will be included into the hash input, the hash result changed.
other new added fields are in the same situation.

**Comment by hzxuzhonghu** [comment]
@leopoldxx Do you have any idea about preventing this?

**Comment by zuzzas** [comment]
We've hit this as well. Caused a cluster-wide restart of every container.

**Comment by hongtao12310** [comment]
i also hit this issue as well, when I am upgrading cluster from v1.7.4 to v1.8.5. especially, the kubelet version from v1.7.4 to v1.8.5

**Comment by jrake-revelant** [comment]
Still seems to happen in 1.9.0

**Comment by dixudx** [comment]
> Still seems to happen in 1.9.0

I can confirm this. v1.9.0 has introduced new field attribute `VolumeDevices` for `Container`, which is causing the hash value get changed.

**Comment by warmchang** [comment]
👍

**Comment by zhangxiaoyu-zidif** [comment]
It will exist when we use docker.
I remember @yujuhong  had described it. There are details in this issues below:
https://github.com/kubernetes/kubernetes/issues/23104
https://github.com/kubernetes/kubernetes/issues/15089
https://github.com/kubernetes/kubernetes/pull/16414/

**Comment by yujuhong** [comment]
@zhangxiaoyu-zidif thanks for digging out the old issue!

Yes, any new field added to the container spec would cause the hash to change. This is not a new issue but new fields are added to the container spec rarely (compared with pod spec) so it doesn't happen so often.  As discussed in #23104, a new way to generate the hash (e.g., using only updatable fields) or other method for kubelet to examine and compare the state of the container against the spec is needed. 

Calling this (i.e., container restart) out in the 1.9 release note would be nice.

**Comment by KevinWang15** [comment]
Just wondering, why don't we calculate the container hash by 
> hash(podUid + "::" + containerName + "::" + containerImage)

since container image is the only mutable field?


I know we have to do some refactoring to `HashContainer(container *v1.Container)`, but wouldn't it be more reliable?
