### ISSUE TITLE
kubelet_test tests implementation not behavior

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#5365]
Currently kubelet_test verify the order of docker calls/image pulls. This is bad, as we'd want to test the outcome of some function, not the implementation of it. I suspect that this may be hard problem, involving writing better Docker mock, but maybe someone will have a better idea.

**Comment by vmarmol** [comment]
That's always hard, a better Docker fake will start looking more and more like Docker and we'd have to worry about replicating it's behavior. FWIW, I am also unhappy at the Kubelet tests. The mocks today don't give enough control to test failures either.
