### ISSUE TITLE
Do not evict critical pods

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#53659]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
If I create a deployment or daemonset and set the pods as critical pods with `scheduler.alpha.kubernetes.io/critical-pod: ''`, then the pods in the deployment or daemonset can still be evicted because they are not static pod.

**What you expected to happen**:
Do not evict critical pods even if they are not static pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by gyliu513** [comment]
/cc @jingxu97 

Some of the related code is here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L564-L568

**Comment by dixudx** [comment]
> My thinking is remove the check for `kubepod.IsStaticPod(pod)`

@gyliu513 I think we should keep checking static pods. They are quite different.
How about changing to this

```
if utilfeature.DefaultFeatureGate.Enabled(features.ExperimentalCriticalPodAnnotation) &&
 (kubelettypes.IsCriticalPod(pod) || kubepod.IsStaticPod(pod))
```

Since currently we won't mark a pod as static pod and critical pod at the same time.

**Comment by gyliu513** [comment]
@dixudx that make sense, thanks!

/cc @jingxu97 what do you think? Hope can get some comments from you.

**Comment by jingxu97** [comment]
cc @dashpole

**Comment by gyliu513** [comment]
@dashpole We have daemonset as well, for this case, the daemonset pod will keeps restarting on the host, I think this is not acceptable.

**Comment by dashpole** [comment]
@gyliu513 the solution in your case should be to increase [resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/) (and possibly also limits) for your pod.  The critical annotation was meant to solve a very specific scenario.  The more robust solution is [pod priority](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/pod-priority-api.md).

**Comment by gyliu513** [comment]
@dashpole For daemonset issues, it can not resolve the issue of the pods being evicted even with `resource requests` or `pod priority`.

Suppose I have a daemonset pod which request large resources, but after the daemonset pod running for a while, the pod may still be evicted due to some pressures, such as disk pressure etc.

So I think the fix is still necessary, we can ignore deployment as it can be rescheduled to other nodes, but for daemonset, as I mentioned above, it will keeps restarting and cannot function normally.

**Comment by dixudx** [comment]
> Since static pods have no controller, this means they cannot be evicted.

@dashpole Actually current implementation won't prevent this.

https://github.com/kubernetes/kubernetes/blob/1797255cd29e9d6afaf02f1e16e9c69940cf5392/pkg/kubelet/eviction/eviction_manager.go#L563-L568

From above logic, what if we have not enabled feature gate for `CriticalPod`, `static pods` can still be evicted, right? But this is not what we expected.

We need to modify the logic here as [my comment above](https://github.com/kubernetes/kubernetes/issues/53659#issuecomment-335490532).

Also critical pods and static pods are not usually coupled together.

Already submit a PR #53693. PTAL.

**Comment by dashpole** [comment]
> @dashpole Actually current implementation won't prevent this.

I meant that the critical pod annotation prevents static pods from being permanently evicted.  For pods that are non-critical, they can still expect to be evicted.

> Suppose I have a daemonset pod which request large resources, but after the daemonset pod running for a while, the pod may still be evicted due to some pressures, such as disk pressure etc.

Evicting pods is better than running out of disk and having an unready node.  The kubelet evicts the largest users of local storage when under disk pressure, so if your pod cannot tolerate evictions, avoid using local storage, and consider using remote storage solutions.  Alternatively, local storage as a first-class resource is currently alpha, and allows you to set requests and limits for container local storage.

> Also critical pods and static pods are not usually coupled together.

Kube-Proxy, which the critical pod feature was initially designed for, is an example of a pod which is both static and critical

**Comment by gyliu513** [comment]
@dashpole I have a case of deploying the calico node as daemonset with critical pod, and the daemonset calico pod keeps restarting and the network function does not work.

Yes, removing the critical pod annotation does works, but this may cause the calico pod cannot start if it restart when there are not enough resources.

**Comment by jingxu97** [comment]
@gyliu513 do you have an estimate how much your daemonSet  pods use? If it normally uses more than node capacity, we might consider using larger resources. 
Also by default, kubelet set hard threshold of disk eviction nodefs.available<10%,nodefs.inodesFree<5%, you can consider lower the value so that pods will not be evicted very easily. 

As @dashpole mentioned, the kubelet evicts the largest users of local storage when under disk pressure. After pod priority feature is in, we might reconsider this design. Please let me know if you have any comments. Thanks!

**Comment by gyliu513** [comment]
Kubernetes 1.8 already support daemonset tolerate MemoryPressure and DisPressure taints, I'm ok to close this one now. Thanks @dixudx @jingxu97 @dashpole 

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/workloads/controllers/daemonset.md#how-daemon-pods-are-scheduled
