### ISSUE TITLE
problem with hpa in multiplatform architucture 

### ISSUE THREAD

**Issue by tesi-nahid** [kubernetes/kubernetes#53650]
Hello guys,
I've implemented one deployment containing 2 pods , each pod running in different nodes(one in amd64 another in arm) ,I defined two label and node selector for each nod and pod respectively(type: "arch2 " for amd64 ,  type: "arch1" for rasspberry) ,
when I am autoscalling my deployment from this yaml file,only nodeselector "type: "arch2 "" is working ,meaning last node selector in Yaml file and all pods of my deployment will run on node with lable of "type: "arch2 " ,
Do you know what would be the problem?

I used these command:
//commands for autoscalling :  
kubectl autoscale deployment my-deployment  --cpu-percent=10  --min=1  --max=10 

// commands for exposing service:
kubectl expose deployment my-deployment --port=80

//commands for making load:
kubectl  run -i --tty load-generator --image=busybox /bin/sh
while true; do wget -q -O- http://my-deployment.default.svc.cluster.local; done

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx2
        image: armhfbuild/nginx
        ports:
        - containerPort: 80
        resources:
         requests:
          memory: "64Mi"
          cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
      nodeSelector:
       type: arch1
      tolerations:
      - key: "value1"
        operator: "Equal"
        value: "pi"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
         requests:
          memory: "64Mi"
          cpu: "250m"
         limits:
          memory: "128Mi"
          cpu: "500m"
      nodeSelector:
       type: arch2

**Comment by darkwise** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by MaciekPytel** [comment]
You define 'containers' twice in `spec`. This is the same as trying to assign two values to the same key in a dictionary - the second assignment overrides the first one (just put your yaml into any online parser and see the result).

Also what you're trying to do is conceptually wrong. Both deployment and hpa are generally meant to work with one kind of pods (this is a bit of simplification as deployment is meant to support rolling update). You should just create 2 separate deployments for different kinds of nodes.

Finally you will probably get better response time for this type of questions on stackoverflow than using github issues.

**Comment by tesi-nahid** [comment]
Thank you.in fact I defined two separate deployment per each node but with same lable and i defined one service again with same lable.now everything is working.
