### ISSUE TITLE
pkg/apis/extensions/validation/validation_test.go: extract function for creating valid PSP

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#53658]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind cleanup
/sig auth

**What happened**:
We have 2 functions for creating valid PSP that are local to different tests: [the first](https://github.com/kubernetes/kubernetes/blob/46c2bfe47df0806536f75f7c3e913aadd2ed05b9/pkg/apis/extensions/validation/validation_test.go#L2782-L2800) and [the second](https://github.com/kubernetes/kubernetes/blob/46c2bfe47df0806536f75f7c3e913aadd2ed05b9/pkg/apis/extensions/validation/validation_test.go#L2402-L2427).

Note that the second also set `AllowedHostPaths` field (it was added in [fab6044a3 commit](https://github.com/kubernetes/kubernetes/commit/fab6044a31cbba4205d9f1cddf10da48b0112223#diff-db71b9ae4bdf839c56ad9c2790730a5d)) but looks like this field isn't being used in tests.

**What you expected to happen**:
I suggest to extract them to a single function and use it in both tests.

CC @PI-Victor in case you're interesting in working on this.

**Comment by PI-Victor** [comment]
sure, if you can /assign you can assign it to me

**Comment by php-coder** [comment]
@PI-Victor No, I can't but you can claim that you're going to take it, so no one will steal it :)

**Comment by php-coder** [comment]
/close
as this idea was rejected: https://github.com/kubernetes/kubernetes/pull/53954#discussion_r157812365

**Comment by PI-Victor** [comment]
@php-coder anything else you need a hand with? byt the time i looked at this there was already a PR in progress, but i have more free time now.

**Comment by php-coder** [comment]
@PI-Victor Yes, here is https://github.com/kubernetes/kubernetes/issues/59123 While splitting could require some approvement beforehand, the second part is definitely a good change that could be considered as a bug and should be fixed.
