### ISSUE TITLE
Changing ExternalTrafficPolicy on GKE does not update load balancer health check

### ISSUE THREAD

**Issue by rgooding** [kubernetes/kubernetes#53657]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Changing externalTrafficPolicy from Cluster to Local on an existing service does not create a health check or reconfigure the load balancer to use it. This means the load balancer will now send traffic to unhealthy nodes, causing connection timeouts.

The Events section under `kubectl describe service` shows the ExternalTrafficPolicy change then CreatingLoadBalancer followed by `CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/metrics-ui-go: failed to ensure static IP X.X.X.X: error creating gce static IP address: googleapi: Error 400: Invalid value for field 'resource.address': 'X.X.X.X'. Specified IP address is already reserved., invalid`

Creating a brand new service with `externalTrafficPolicy = Local` works perfectly, the LB is created with a health check as expected.

**What you expected to happen**:
A health check should be created and the load balancer should be updated to use it

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service with externalTrafficPolicy unset or set to "Cluster"
2. Edit the service and change externalTrafficPolicy to "Local" (I tried `kubectl edit` and `kubectl patch`, both seem to have the same effect)
3. Check the load balancer config in GCP console or using gcloud commands.
`gcloud compute http-health-checks list` shows no new health checks and the load balancer is not updated.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.6-gke.1
- Cloud provider or hardware configuration**: Google Container Engine
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`): 4.4.64+
- Install tools:
- Others:

**Comment by MrHohn** [comment]
> How to reproduce it (as minimally and precisely as possible):
>
> 1. Create a service with externalTrafficPolicy unset or set to "Cluster"
> 2. Edit the service and change externalTrafficPolicy to "Local" (I tried kubectl edit and kubectl patch, both seem to have the same effect)
> 3. Check the load balancer config in GCP console or using gcloud commands.
> 4. gcloud compute http-health-checks list shows no new health checks and the load balancer is not > updated.

I failed to reproduce the issue following the steps:
```
$ kubectl get event
LASTSEEN   FIRSTSEEN   COUNT     NAME         KIND      SUBOBJECT   TYPE      REASON                  SOURCE               MESSAGE
7m         9m          2         my-nginx-1   Service               Normal    CreatingLoadBalancer    service-controller   Creating load balancer
6m         8m          2         my-nginx-1   Service               Normal    CreatedLoadBalancer     service-controller   Created load balancer
7m         7m          1         my-nginx-1   Service               Normal    ExternalTrafficPolicy   service-controller   Cluster -> Local

$ gcloud compute http-health-checks list
NAME                              HOST  PORT   REQUEST_PATH
a037e25c6ae0711e7888142010a800fd        31728  /healthz
```

Is there anything special about your service setup? Seems like you are requesting an IP address (by setting the `spec.loadBalancerIP` field) that is already reserved?
```
error creating gce static IP address: googleapi: Error 400: Invalid value for field 'resource.address': 'X.X.X.X'. Specified IP address is already reserved., invalid
```

Xref https://github.com/kubernetes/kubernetes/issues/53475

**Comment by cmluciano** [comment]
/remove-label sig-network

@kubernetes/sig-gcp-bugs

**Comment by kunickiaj** [comment]
/reopen
/remove-lifecycle rotten

Seeing the same issue here, a year later.
