### ISSUE TITLE
show SystemOOM in events and in pod termination status

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#53669]
### Setup
 - 2 nodes with 1GB ram
 - 10 pods with requests: 10M limits: 500M
 - fill em up until it fails (10x500m > 2x1G)
 - kubernetes v1.5.7 on aws

### Expected
some nice event telling me that the pod got SystemOOM - oomkilled and a nice termination status ... not just "Error" ... so we can report on this happening and it is obvious when debugging

### Actual
watching pods shows:
```
                "lastState": {
                    "terminated": {
                        "containerID": "docker://5954f621c17f13706c25a215db06fe2bf7b9a9a6c732a909eb0db39d62346724",
                        "exitCode": 137,
                        "finishedAt": "2017-10-10T17:41:58Z",
                        "reason": "Error",
                        "startedAt": "2017-10-10T17:20:37Z"
                    }
                },
```

... not very helpful ... (this is memcached exitcode when when -9 killed ... see https://forums.couchbase.com/t/regular-bucket-shutdown-and-exit-of-memcached-with-status-137/6046)

watching events shows: nothing related to the error ... just the new pod spinning up

kubelet logs show (sudo journalctl -u kubelet):

```
Oct 10 17:41:58 ip-10-0-211-82.us-west-1.compute.internal kubelet[4991]: I1010 17:41:57.858757    4991 manager.go:1126] Created an OOM event in container "/" at 2017-10-10 17:41:57 +0000 UTC
Oct 10 17:41:58 ip-10-0-211-82.us-west-1.compute.internal kubelet[4991]: I1010 17:41:57.858778    4991 oom_watcher.go:66] Got sys oom event from cadvisor: &{/ 2017-10-10 17:41:57 +0000 UTC oom {<nil>}}
0-0-211-82.us-west-1.compute.internal", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SystemOOM' System OOM encountered
Oct 10 17:41:58 ip-10-0-211-82.us-west-1.compute.internal kubelet[4991]: I1010 17:41:57.872612    4991 eviction_manager.go:272] eviction manager: no resources are starved
```

**Comment by gaorong** [comment]
@grosser From your kubelet log: ` Created an OOM event in container "/"`, why it would come as container "/" ? in mostly situation, it would comes as pattern: `/kubepods/pod23d2c685-24f5-11e9-8b87-000c292d53d3/1091db0703a369cf386468c488a408eb2b45038d950a59c42bb933531b535b33`

**Comment by grosser** [comment]
no idea

**Comment by gaorong** [comment]
thx, I got this, because some process which did not own by k8s/container was being killed.
