### ISSUE TITLE
syncRolloutStatus is missing test cases

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#53663]
Please see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/progress.go#L35 There are no unit tests currently for that method. This would be a good started PR for someone interested in helping with Kubernetes.

**Comment by kargakis** [comment]
I want this done by the end of this week so we can cherry-pick both the unit test and https://github.com/kubernetes/kubernetes/pull/53614 back to 1.7 and potentially 1.6.

**Comment by jekohk** [comment]
if nobody else is working on it, i'll look into this.

**Comment by kargakis** [comment]
Hey @jekohk. Please do so and cc me on your PR, I haven't had any time to start on it.
