### ISSUE TITLE
HPA scaling above spec.maxReplicas

### ISSUE THREAD

**Issue by clewis** [kubernetes/kubernetes#53670]
/kind bug

**What happened**:
Since upgrading to Kube 1.7.6, I'm seeing my HPAs scale above it's maxReplicas.  Because of this, it's rapidly creating pods, then terminating them, and repeat.

**What you expected to happen**:
I expected the HPA to never exceed maxReplicas.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: monolith-mq-remotefileops
  namespace: na-prod
spec:
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: monolith-mq-remotefileops
```

The HPA is logging:
```
2017-10-10T18:46:22Z: the desired replica count is increasing faster than the maximum scale rate
2017-10-10T18:46:22Z: the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
2017-10-10T18:46:22Z: the HPA controller was able to update the target scale to 8
2017-10-10T18:47:22Z: the desired replica count was more than the maximum replica count
2017-10-10T18:50:52Z: the time since the previous scale is still within both the downscale and upscale forbidden windows
2017-10-10T18:52:23Z: the HPA controller was able to update the target scale to 4
```

This seems to happen with the deployment's spec.resources.request.cpu is low, and the HPA shows the deployment using more than 175% of it's spec.resource.requests.cpu.  If I increase 
 the deployment's spec.resources.request.cpu to better match actual usage (so that the deployment is using 120% or less), it occurs much less often.

I deliberately set the spec.resources.request.cpu low, to ensure services were over provisioned during the first roll out of HPA.

I think the switch in pkg/controller/podautoscaler/horizontal.go after ```scaleUpLimit := calculateScaleUpLimit(currentReplicas)``` should be converted to individual if() statements.

**Anything else we need to know?**:
I am only setting spec.resource.requests.cpu on the deployment, not spec.resource.limits.cpu

Looking at the code in pkg/controller/podautoscaler/horizontal.go, the version that worked (1.6.2) would only scale up and down by 1.  The 1.7.6+ code is attempting to scale up by a larger amount.

The new code seems appropriate in large clusters, where maxReplicas is in the tens or hundreds.  It doesn't seem appropriate for clusters where maxReplicas is in the single digits.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
AWS m4.2xlarge, 5 nodes

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):
```
Linux ip-10-66-46-241 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
kops Version 1.7.0

- Others:

**Comment by DirectXMan12** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by DirectXMan12** [comment]
> I think the switch in pkg/controller/podautoscaler/horizontal.go after `scaleUpLimit := calculateScaleUpLimit(currentReplicas)` should be converted to individual if() statements.

Yeah, I think the bug is that we have a case short-circuiting another case.

**Comment by mattjmcnaughton** [comment]
I think your right @DirectXMan12 - we are not checking whether `scaleUpLimit > maxReplicas`. I submitted a diff with a fix and regression test.
