### ISSUE TITLE
Enable ip-masq-agent by default on GCE

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#53680]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

Created a cluster on GCE using the cluster/kube-up scripts and Calico enabled for NetworkPolicy.  The ip-masq-agent did not run as expected.

**What you expected to happen**:

The ip-masq-agent daemonset would run on each node providing outbound NAT and letting pods access the apiserver and wider internet.

**How to reproduce it (as minimally and precisely as possible)**:

```
export NETWORK_POLICY_PROVIDER=calico
./cluster/kube-up.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by caseydavenport** [comment]
CC @heschlie @dnardo

**Comment by caseydavenport** [comment]
I think we should just be enabling ip-masq-agent by default on GCE, setting the NON_MASQUERADE_CIDR=0.0.0.0/0, and labeling each node so the daemonset runs.

/sig-network

**Comment by caseydavenport** [comment]
CC @bowei

**Comment by caseydavenport** [comment]
@dnardo @bowei IIRC, I think we've opted _not_ to run ip-masq-agent by default?

If so, I can close this.

**Comment by dnardo** [comment]
Yes, for 1.7.12 and 1.8.6 we add the appropriate rules.  I think this can be closed.
