### ISSUE TITLE
Pod's Health Check

### ISSUE THREAD

**Issue by wjzhao** [kubernetes/kubernetes#53697]
Hello, I found the pod's health check just support GET method with http protocol at present, but in my work environment, I found PUT method or HEAD method maybe  better, so I want to give a little suggest that whether the next kubernetes version could support health check with PUT method, thank you!

**Comment by dixudx** [comment]
@wjzhao Why not use [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/), where you can perform the PUT/HEAD request as well.
