### ISSUE TITLE
Problem with Detach logic in EBS

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#53692]
/kind bug

There is a problem with EBS detach logic where when we start detach -  we remove the volume from node's  "VolumeAttached" property but if Detach fails because volume is mounted or something like that, we add back the volume to "VolumeAttached" property of node.

In EBS though, a detach is asynchronous and once issued there is no way to cancel it. So when we issue detach against a mounted device, it is guaranteed to be detached in future whenever volume eventually gets unmounted from node even though no further detach API calls are made against the same volume. In other words - detach is a fire and forget operation in EBS and EBS will keep retrying internally. 

So the problematic part is, when we add back such a volume to "VolumeAttached" propery of node and detach eventually succeeds in EBS, the state held by AttachDetach Controller does not reflect correct state. In this case, what can happen is - a race condition will trigger if some other pod tries to use same volume. For example:

1. Pod A is running on node N and pod gets deleted.
2. We tried to detach the volume but lets say first attempt of detach failed and volume was "busy".
3. We add back the volume to Node's Attached property and keep the volume in actual state of world.
4. Another pod B is added to same node N (and hence volume gets added back to desired state of world)
5. It notices that volume is already present in actual state of world and hence proceeds to use the volume.
6. Now between during the time difference between pod starting on kubelet and mount, the volume may be detached from node.

Admittedly - there is a VerifyVolumeAttached mechanism that will try to fix this but that mechanism is race prone as well. Also, if pod starts with assumption of device being present on certain path (like `/dev/xvdba`), then this mechanism will not gurantee same path for device.

**Comment by jingxu97** [comment]
In step 6, before kubelet tries to mount, it will check the device path. Although because of race condition, it is possible kubelet tries to mount while volume is detached. So mount will fail, kubelet will retry. Is there any other consequences from it?

**Comment by gnufied** [comment]
If mount fails pod will fail to start, while volume is still present in actual and desired state of world of A/D controller. 

Now, after awhile I think VerifyVolumesAttached mechanism will notice try to "fix" it, now it will remove the volume from actual state of world and that in turn will cause another attach.  Now device will be attached to a different path than before but I do not think kubelet will update device path and hence it will keep retrying to find device on same old path.
