### ISSUE TITLE
pod with resource limit and request show host info

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#53706]
I create pod with resource config like this：
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi

But when i enter the pod with bash，I find cpu and memory config are from host
/ # free
             total         used         free       shared      buffers
Mem:       8010284      4855560      3154724            0         1436
-/+ buffers:            4854124      3156160
Swap:      2097148            0      2097148
/ # cat /proc/cpuinfo| grep "processor"| wc -l
8

How can I get cpu and memory config from pod？

**Comment by embano1** [comment]
Actually, this is by design. The process (pod containers) live inside the OS (shared kernel). cGroups and namespaces are constructs to isolate the process, which processes are not really "aware" of. This can cause issues with older JREs, and other runtimes (e.g. GO), if your app tweaks its behaviour based on querying the host.

If you´re trying to let your process (container, pod) know which resources it should consume (to tweak its runtime behaviour), use pod spec refs in the manifest and inject/ pass them to the executable.

**Comment by like-inspur** [comment]
@embano1 how to use pod spec refs in the manifest ，define what envrionment variables to achieve？

**Comment by embano1** [comment]
You can read more about this approach here: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

For larger projects, consider [templating](https://blog.openshift.com/kubernetes-state-app-templating/).

**Comment by like-inspur** [comment]
@embano1 I plan to install haddop on kubernetes with ambari，because I create pod with privileged，ambari server get ambari agent host information is acturally physical host information，not pod information。I have read url above this，but still cannot solve this problem

**Comment by embano1** [comment]
Every process, no matter how you run it, without support for cgroups in the language runtime, will query (use) the host information. If you want to run a pod with memory limits and tune the process to not use more than the limit specified, either inject this information in advance (environment, cli arg) or make it dynamic based on the mem limit. This is where `resourceFieldRef` comes in handy.

For example, from the link above:

```
- name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.memory
```

Now you can use this ENV in your .yaml/ process.

**Comment by rushi47** [comment]
> /sig pod resource

Hey Can you help me with this, am stucked into same problem.

cc: @dims
