### ISSUE TITLE
azureDisk warns about disk format failure when successfull

### ISSUE THREAD

**Issue by tlyng** [kubernetes/kubernetes#53713]
While trying to resolve some azure-disk issues I am encountering I noticed some strange logs:

Oct 11 10:37:49 smblab-we-worker-0 kubelet-wrapper[1264]: I1011 10:37:49.508797    1264 azure_common_linux.go:153] azureDisk - Disk successfully formatted (mkfs): ext4 - /dev/sdd tt
Oct 11 10:37:49 smblab-we-worker-0 kubelet-wrapper[1264]: W1011 10:37:49.509230    1264 azure_common_linux.go:155] azureDisk - format of disk "/dev/sdd" failed: type:("ext4") target:("tt") options:("o")error:(<nil>)

Looking at the code it seem like an else clause is missing:

https://github.com/kubernetes/kubernetes/blob/0564d5298504cb57ec4d35cf4878e383f9504ed6/pkg/volume/azure_dd/azure_common_linux.go#L155

**Comment by dixudx** [comment]
/sig azure

> Looking at the code it seem like an else clause is missing:

@tlyng Right. PTAL #53719
