### ISSUE TITLE
Clean-up reconcileAutoscaler and improve it's unittest coverage

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/kubernetes#53728]
We recently had 2 serious bugs caused by non-trivial logic calculating desiredReplicas in hpa reconcileAutoscaler method (#48997, #53690). 

I think we should extract this part of logic (starting around https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L404) to a separate function and make sure it's covered with unittests for different possible edge condition. The logic itself takes a few ints as input (calculated desiredReplicas, min/max replicas, currentReplicas, ...) to produce a single integer value and set some status conditions, making it very easily unittestable if we extract it to a separate function.

WDYT @mwielgus, @DirectXMan12?

**Comment by mwielgus** [comment]
+100. It would be super unfortunate if we had yet another issue in this area of the code.

**Comment by DirectXMan12** [comment]
agreed. @mattjmcnaughton you've been going over these pieces of code recently, you want to tackle this?

**Comment by mattjmcnaughton** [comment]
Yes, I'd love to! Thanks for the ping.
