### ISSUE TITLE
Get clusters --show-labels does not work in a federation context

### ISSUE THREAD

**Issue by GabrielSVinha** [kubernetes/kubernetes#53729]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After labeling clusters in a Federation, when you type `kubectl get cluster <your-cluster> --show-labels` the `LABELS` field is empty.

**What you expected to happen**:
The `LABELS` fiels should contain information about the labels in the cluster
**How to reproduce it (as minimally and precisely as possible)**:
1.Create a federation control pane in any Cloud Provider and any DNS provider
2. Label your cluster:
```
kubectl label cluster <cluster-name> key=value
```
3. Get info aboyut the cluster with the `--show-labels` flag:

```
kubectl get cluster <cluster-name> --show-labels
```

Note: if you describe it, you see the labels being added:

```
kubectl describe <cluster-name>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.0
- Cloud provider or hardware configuration**: anyone
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux
- Install tools: curl
- Others:

**Comment by GabrielSVinha** [comment]
@kubernetes/sig-federation

**Comment by dixudx** [comment]
I'm working on it.
