### ISSUE TITLE
Can't deploy Kubernetes on localhost

### ISSUE THREAD

**Issue by daviddang91** [kubernetes/kubernetes#53725]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: I can't deploy Kubernetes on localhost

**What you expected to happen**:

I setup Kubernetes as below:

> sudo snap install conjure-up --classic
> conjure-up kubernetes

But I can't deploy on localhost, I got an error as below:
![screenshot from 2017-10-11 20-29-37](https://user-images.githubusercontent.com/9908743/31443624-25880ca8-aec4-11e7-8bdc-1e2f63d654df.png)

I tried to install LXS follow the guide on the error message, But it was not successful. so how to solve this issue?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**: Laptop assus X454L
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux David-Dang 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: sudo snap install conjure-up --classic
- Others:

**Comment by daviddang91** [comment]
@kubernetes/sig-contributor-experience-localhost

**Comment by dims** [comment]
Please log the bug here : https://github.com/juju-solutions/bundle-canonical-kubernetes/issues

Thanks,
Dims

**Comment by daviddang91** [comment]
I fixed this issue as below:
`newgrp lxd`
`usermod -G lxd ubuntu`
