### ISSUE TITLE
Container cannot be restarted by kubelet if it was removed while kubelet was down and its service account secret was changed

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#53726]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We converted the /var/lib/docker backend from BTRFS to DeviceMapper forcing a wipe of the partition.
The wipe was done while Kubelet was stopped on the Node. 
After docker was reconfigured properly and that Kubelet was started, not all containers we restarted. Those in namespaces where the default service account was refreshed could not start.

**What you expected to happen**:
I would have expected that all containers be restarted, even those with invalid default service account tokens (they do not use it)

**How to reproduce it (as minimally and precisely as possible)**:
* `kubectl create ns test`
* `kubectl create -n test -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/nginx-deployment.yaml`
* `kubectl -n test delete sa default`
* `ssh nodeRunningContainer`
* `systemctl stop kubelet`
* `docker rm -f <containerID#1> <containerID#2>`
* `systemctl start kubelet`

From this point on the container won't be scheduled in Docker, `journalctl -u kubelet -n 20`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
```
cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux mtl-blade32-14-vm2.nuance.com 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by liggitt** [comment]
> I would have expected that all containers be restarted, even those with invalid default service account tokens (they do not use it)

from a node's perspective, a service account secret is just another volume mount. the kubelet will not start a container it cannot set up volumes for.

pods can opt out of service account tokens with the `automountServiceAccountToken: false` field if they do not need them and wish to remove a dependency on them

**Comment by djsly** [comment]
Any reason why a pod will be restarted if I delete it from docket while keeping kubelet up even if its service account token folder doesn’t exists.  

Shouldn't the logic be the same between deleting a container with or without kubelet running at the time of the deletion.

**Comment by liggitt** [comment]
The kubelet has an in-memory short-term cache of secrets and configmaps required to be mounted. On restart, the kubelet has to rebuild that from the API server before it can rebuild those volume mounts

**Comment by djsly** [comment]
@liggitt any way we can disable the mounting of the default service account by defualt at the cluster level ? instead of having to specify `automountServiceAccountToken: false` in ALL manifest ?
Thanks!

**Comment by liggitt** [comment]
You can set it on the service account instead of each individual pod/deployment/rc/rs manifest. The automount behavior is not configurable cluster-wide.

**Comment by djsly** [comment]
@liggitt :Thanks for the prompt reply, actually I'm having issues with the default service account that is being automounted, anyways to configure it for `this` particular service account ? since we don't control its creation.

**Comment by djsly** [comment]
@liggitt kind re-ping, anyway we could force `automountServiceAccountToken: false` for the `default` service account ? 

thanks
