### ISSUE TITLE
KUBECONFIG contains the same path multiple times

### ISSUE THREAD

**Issue by Ecsy** [kubernetes/kubernetes#53723]
/kind bug
/sig cli

**What happened**:
The same path was added multiple times to KUBECONFIG env variable.

**What you expected to happen**:
```bash
$ export KUBECONFIG="/path/a.yml:/path/b.yml:/path/a.yml"
$ kubectl config current-context
a
$ kubectl config use-context b
Switched to context "b".
```

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ export KUBECONFIG="/path/a.yml:/path/b.yml:/path/a.yml"
$ kubectl config current-context
a
$ kubectl config use-context b
error: open /path/a.yml.lock: file exists
$ ls /path/a.yml.lock
ls: /path/a.yml.lock: No such file or directory
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:40:04Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration**:
Irrelevant
- OS (e.g. from /etc/os-release):
MacOS Sierra 10.12.6
- Kernel (e.g. `uname -a`):
Darwin Kernel Version 16.7.0
- Install tools:
brew install kubernetes-cli
- Others:

**Comment by wackxu** [comment]
I would help fix it.
