### ISSUE TITLE
Pod stuck in terminating due to preStop hook not executing on all containers

### ISSUE THREAD

**Issue by DimitriosLisenko** [kubernetes/kubernetes#53727]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I'm using a pod with a worker container and a sidecar container that connects to the database.

Originally, the worker had a preStop hook on it to stop accepting requests, and complete the ones it already accepted before terminating. Since it now needs the sidecar container to do so, after reading https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#how-pods-manage-multiple-containers, https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/, and #25908, I modified the preStop hook on the worker to create a file on a shared pod volume once it completes, and a preStop hook on the sidecar that waits for the creation of the file.

This works most of the time, but sometimes a weird situation happens where running `kubectl get pods` shows the pod as terminating with 0/2 ready:
```
NAME                                        READY     STATUS        RESTARTS   AGE
worker-high-1230252182-l4d3b                0/2       Terminating   0          4h
```

I can exec into both the containers - the sidecar is running the preStop hook (waiting for the file), and the worker container is running **without having run the preStop hook** - so there is a worker with old code still accepting jobs, the preStop hook on the sidecar will never complete (until the timeout).

**What you expected to happen**:
I expect the preStop hook to be run for both containers at least once in all scenarios - perhaps a mistaken assumption?

I also don't expect there to be any containers in a running state without having run the preStop hook during termination.

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce it fairly consistently by performing deploys (with different image tags) one after another - eventually you get pods stuck in this state.

**Anything else we need to know?**:
I had a look at the kubernetes logs, and this seems to stand out for me:
```
18:34:05.433939 1453 kubelet.go:1912] SyncLoop (PLEG): "worker-high-1230252182-l4d3b_central(963e24d3-ade9-11e7-87dd-42010a960029)", event: &pleg.PodLifecycleEvent{ID:"963e24d3-ade9-11e7-87dd-42010a960029", Type:"ContainerStarted", Data:"aad09149d791d077ac32a55357d0613740929100b3d1f4441e4e17b4f5a61026"}
18:34:06.016202 1453 kubelet.go:1894] SyncLoop (DELETE, "api"): "worker-high-1230252182-l4d3b_central(963e24d3-ade9-11e7-87dd-42010a960029)"
18:34:06.449067 1453 kubelet.go:1912] SyncLoop (PLEG): "worker-high-1230252182-l4d3b_central(963e24d3-ade9-11e7-87dd-42010a960029)", event: &pleg.PodLifecycleEvent{ID:"963e24d3-ade9-11e7-87dd-42010a960029", Type:"ContainerStarted", Data:"32b40b349dda705e776ceae0e0e9b77dffa911859fb0e23c2f573d2da87a3a15"}
18:34:07.671713 1453 kubelet_pods.go:936] Killing unwanted pod "worker-high-1230252182-l4d3b"
18:34:07.677285 1453 kuberuntime_container.go:561] Killing container "docker://32b40b349dda705e776ceae0e0e9b77dffa911859fb0e23c2f573d2da87a3a15" with 21601 second grace period
18:34:08.601532 1453 kubelet.go:1912] SyncLoop (PLEG): "worker-high-1230252182-l4d3b_central(963e24d3-ade9-11e7-87dd-42010a960029)", event: &pleg.PodLifecycleEvent{ID:"963e24d3-ade9-11e7-87dd-42010a960029", Type:"ContainerStarted", Data:"7d9475932ff3821009dd22cabab69165162b5fa107b15752f32be9333efa1d25"}
```

It looks like the the pod killing sequence begins and runs on the containers that are up (the sidecar for instance), and *then* the worker container comes up, without running through the container killing sequence that would run preStop.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: GKE

**Comment by DimitriosLisenko** [comment]
@kubernetes/sig-node-bug

**Comment by DimitriosLisenko** [comment]
@kubernetes/sig-node-bugs

**Comment by hzxuzhonghu** [comment]
It looks like your worker container is not up when delete pod.

**Comment by thkoch2001** [comment]
Hi Dimitrios,

I see that your similar support case with Google Engineering support has been closed. Therefor I think this issue can also be closed.
