### ISSUE TITLE
regression 1.6 => 1.7 - cinder plugin

### ISSUE THREAD

**Issue by mmaquevice** [kubernetes/kubernetes#53737]
Maybe there is a regression concerning the openstack provider plugin for cinder.

I manage to create a PVC in 1.6 (and the volume associated in openstack).

However in 1.7, I go the following error (with the same configuration):

```
E1011 16:13:44.309318       5 openstack_volumes.go:320] Failed to create a 3 GB volume: Invalid request due to incorrect syntax or missing required parameters.

I1011 16:13:44.309411       5 cinder_util.go:207] Error creating cinder volume: Invalid request due to incorrect syntax or missing required parameters.

I1011 16:13:44.309458       5 pv_controller.go:1331] failed to provision volume for claim "default/my-persistent-volume-claim" with StorageClass "standard": Invalid request due to incorrect syntax or missing required parameters.
```

**Comment by FengyunPan** [comment]
/sig storage
>Invalid request due to incorrect syntax or missing required parameters.

The log is hard to get the reason of this issuse. SO can you give some log about it from Cinder?

**Comment by mmaquevice** [comment]
Thanks for your reply @FengyunPan 
Indeed it is hard to debug with this log. Unfortunately I don't have access to server logs. I have tried with another openstack cloud provider and it works great.
It does not resolve the issue but I guess it is due to a specific implementation of openstack, I close the bug.

**Comment by jianglingxia** [comment]
have you  upgrade especially from non-OpenStack Cloud Provider to OpenStack Cloud Provider? 
the issue is 1.6 with OpenStack Cloud Provider upgrade 1.7 with OpenStack Cloud Provider? thanks

**Comment by mmaquevice** [comment]
The issue was from/to the same OpenStack Cloud Provider.

**Comment by jianglingxia** [comment]
do you know the follow question?
1、why config the OpenStack Cloud Provider ,the k8s use the nodename instead of ip?
2、if the nodename has two same and What to do？I read the code and no place to validate the same nodename.
thanks for reply
