### ISSUE TITLE
[e2e failure] "should function for client IP based session affinity" constantly fails

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#53741]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/priority failing-test
/sig network

**What happened**:
From https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow&sort-by-failures=&width=5,
`Services should function for client IP based session affinity: udp/http` seems to be broken right after they were added by https://github.com/kubernetes/kubernetes/pull/50447.

Example error message:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:225
Oct 11 16:39:42.406: Expect endpoints: map[], got: map[netserver-1:{}]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:222
```
and
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:249
Oct 11 16:37:49.106: test session affinity, cost time: 1m31.742990485s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:248
```

**Anything else we need to know?**:
@m1093782566 Is it as expected?

**Comment by m1093782566** [comment]
@MrHohn 

> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:249
Oct 11 16:37:49.106: test session affinity, cost time: 1m31.742990485s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:248

This is a mistake. Sorry for my debug lines sneak in - I was just wondering why this test case didn't run in upstream CI? 

> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:225
Oct 11 16:39:42.406: Expect endpoints: map[], got: map[netserver-1:{}]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:222

This check failed unexpectedly, let me try to find out why. I am working on it...

**Comment by MrHohn** [comment]
@m1093782566 Thanks. These two tests don't run on pull jobs as they are marked as `[slow]`, though https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow, https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features (and other CIs that include `[slow]`) would have them running.

**Comment by m1093782566** [comment]
> These two tests don't run on pull jobs as they are marked as [slow]

Do you mean when I raise a PR, these test cases will not be triggered? My question is how can I make sure my follow-up PR can fix this bug? Where can I access the log message when I raise a new PR?

**Comment by m1093782566** [comment]
Can I see the updated test results from https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow, https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features?

**Comment by MrHohn** [comment]
> Do you mean when I raise a PR, these test cases will not be triggered? My question is how can I make sure my follow-up PR can fix this bug? Where can I access the log message when I raise a new PR?

Yep, that is the current behavior. A hacky way to make it run on PR --- add a temporary commit to remove the word `[Slow]` from test name so some pull jobs (`pull-kubernetes-e2e-gce-etcd3` I think?) will run it. And you could view logs by clicking the `Details` button.

**Comment by MrHohn** [comment]
> Can I see the updated test results via directly visiting https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow, https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features?

Nope, this CI only includes changes that are merged. It is basically a cronjob that runs tests against head.
