### ISSUE TITLE
CRI: Debug API

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#53757]
Today, CRI only provides information needed by Kubelet.

But actually, Kubelet is not the only consumer of CRI. [`crilctl`](https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/crictl.md), which is a CLI tool for debugging purpose, also talks with CRI to get debug information for user.

Most operations provided in `crictl` are well covered by CRI already. The only thing missing is detailed debug information about `container`, `sandbox`, `image` and `container runtime` itself (think about `docker inspect` and `docker info`). For linux container based container runtime, it could be `Pid`, `Namespaces`, `Container Config` etc.

Since we want `crictl` to be portable across different CRI container runtimes, it has to get the debug information from CRI instead of from the underlying container runtime directly.

Ideally,
- Each container runtime should be able to provide runtime specific debug information via CRI.
- Kubelet should never consume that information.
- `crictl` should easily format and print the debug information to user.

**The debug information could just be a string in `json` format**, which could be easily combined, converted and printed.

As for how to expose the debug information through CRI, there are several options:
- **Option 1:** Add a `ContainerInfo` field in `ContainerStatusResponse`, and also corresponding fields in `PodSandboxStatusResponse`, `ImageStatusResponse` and `StatusResponse`. The `ContainerInfo` is just a string in json format.
  - Pros: Won't break existing CRI container runtime. If they don't want to provide this, they could just return empty.
  - Cons: This introduces extra overhead in each status call, the extra encoding/decoding in grpc will be a pain. And the more debug information a container runtime provides, the worse its performance is, which doesn't seem like an encouragement to more debug info.
- **Option 2 (Preferred):** Same with Option 1, but add a `Debug bool` option in `ContainerStatusRequest`, and also other status requests. Container runtime should only provide extra debug information when `Debug=true`.
  - Pros: Extra debug information doesn't add extra performance overhead in production.
  - Cons: The `Debug` option may be confusing to people, we may need another name.
- **Option 3:** Add separate CRI functions for the debug information.
  - Pros: More clear.
  - Cons: All CRI runtimes need to support these functions, at least need to return `not implemented` for those functions.
- **Option 4:** Separate CRI debug API. `crictl` should only use it when it is present, and just use CRI if it isn't.
  - Pros: Clean. The original CRI won't be affected at all.
  - Cons: More complex than option 2.

I personally prefer option 2, but am open to other options. :)

@yujuhong @feiskyer @mikebrow @abhi @mrunalp @runcom 
/cc @dchen1107 
/cc @kubernetes/sig-node-api-reviews

**Comment by feiskyer** [comment]
+1 for the proposal. detailed information could help a lot for validating cri-compatible runtimes and debugging container problems.

Option 2 also seems good to me, and it doesn't break kuberuntime since debug should be false by default. I suggest rename `Debug` to `Verbose`, which I think is more clear.

**Comment by WIZARD-CXY** [comment]
agreed with @feiskyer

**Comment by runcom** [comment]
+1 on option 2 and +1 for `Verbose`

**Comment by yujuhong** [comment]
`Verbose` sounds better.

**Comment by abhi** [comment]
+1 on ```verbose```
+1 on Option 2

**Comment by Random-Liu** [comment]
Cool, it seems that everyone is fine with Option 2 + Verbose.
I'll send out a PR then. :)

Thanks for providing suggestions!
