### ISSUE TITLE
Kube-proxy metrics bind

### ISSUE THREAD

**Issue by lukmanulhakimd** [kubernetes/kubernetes#53754]
> /kind bug

Whenever I try to change kube proxy metrics bind using flag `--metrics-bind-address=0.0.0.0`, it gives me:
```
Oct 12 07:25:50 R11U2-7U20N-1 kube-proxy[510997]: E1012 07:25:50.358481  510997 server.go:661] starting metrics server failed: listen tcp: address 0.0.0.0: missing port in address
```
Then, I added the port `--metrics-bind-address=0.0.0.0:10249`, the error changes.
```
Oct 12 07:25:58 R11U2-7U20N-1 kube-proxy[510947]: Error: invalid argument "127.0.0.1:10249" for --metrics-bind-address=0.0.0.0:10249: "0.0.0.0:10249" is not a valid IP address
```

I expect the metrics server to listen to 0.0.0.0:10249. Do I miss something?

**Environment**:
- Kubernetes version: v1.7.8
- Cloud provider or hardware configuration**: on-premise
- OS (e.g. from /etc/os-release): debian/stretch
- Kernel (e.g. `uname -a`): Linux R11U2-7U20N-1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
- Install tools: 
- Others:

**Comment by frodenas** [comment]
@lukmanulhakimd The `metrics-bind-address` is being [deprecated](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L128) and does NOT allow specifying a port. Have you tried using a config file? The `metricsBindAddress` field allows you to specify a port (an example [here](https://gist.github.com/ncdc/b53d5540fba4fb309b8c4c9b26fad487)).

**Comment by MrHohn** [comment]
Turned out we use a wrong type when validating `--healthz-bind-address` and `--metrics-bind-addres`. Sent #54191 for fixing this. Will try to cherrypick the fix as well.

**Comment by MrHohn** [comment]
New finding, `--metrics-bind-address` is broken on HEAD in a different way:
```
$ ./kube-proxy --metrics-bind-address=0.0.0.0
W1020 13:23:46.938126  188323 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
error: KubeProxyConfiguration.MetricsBindAddress: Invalid value: "0.0.0.0": must be IP:port
```

Seems to be introduced by https://github.com/kubernetes/kubernetes/pull/49087. @allencloud

**Comment by MrHohn** [comment]
Humm..We have some default logic for `KubeProxyConfiguration.MetricsBindAddress`:
https://github.com/kubernetes/kubernetes/blob/7d4f21d0d7d1afc4e121b15f2816fd198eba2caf/pkg/apis/componentconfig/v1alpha1/defaults.go#L45-L49 

Seems like for some reason it does not auto append the default port number OR the validation happens before defaulting.

**Comment by zhoulouzi** [comment]
I got the same issue  0.0.0.0  0.0.0.0:10249 both not work with kube-proxy 1.9.3 amd64

**Comment by Avanpourm** [comment]
It is a BUG. 

`
Conflict between  componentconfig.IPVar.Set(s string)  and validation.validateHostPort.
`

**Comment by MrHohn** [comment]
> Conflict between componentconfig.IPVar.Set(s string) and validation.validateHostPort.

@Avanpourm Could you elaborate the issue a bit more? Which k8s version are you on?

**Comment by jamie-liu** [comment]
I also meet the same issue with kubernetes 1.8. 
It's impossibe for Prometheus to fetch metrics from 127.0.0.1 in my case, any workaround?
I think we'd better reopen this issue.

**Comment by MrHohn** [comment]
@jamie-liu metrics binds to `127.0.0.1:10249` by default, are you trying to modify port as well?

@zhoulouzi @Avanpourm Thanks for reporting, I confirm the issue is remaining. `0.0.0.0:10249` (or any ip:port) does not work as intended even after the fix.

Reopening this and filed a new issue for conflict kubeproxyconfig validation.
/reopen

**Comment by jamie-liu** [comment]
Thanks for reopening the issue.
I want to bind metrics to 0.0.0.0:10249 as well. With address 127.0.0.1:10249, Prometheus cannot pull metrics from this address unless they are on the same node.

**Comment by MrHohn** [comment]
https://github.com/kubernetes/kubernetes/pull/62582 is fixing this.

**Comment by MrHohn** [comment]
https://github.com/kubernetes/kubernetes/pull/72682 should fix this.

**Comment by MrHohn** [comment]
Closing this as #72682 is merged.
/close
