### ISSUE TITLE
quota support for custom resources

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#53777]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

/kind feature

For standard resources like (pods, configmaps), we can use quota to limit the amount of these resources in cluster. However, for a user defined custom resource, we don't support quota.

**Comment by CaoShuFeng** [comment]
@deads2k 
@sttts

**Comment by CaoShuFeng** [comment]
We may use controller to act as a quota currently.

**Comment by sttts** [comment]
I think @ironcladlou is working on this already.

**Comment by ironcladlou** [comment]
I'm not yet actively developing it, but I've done some R&D with @derekwaynecarr.

**Comment by deads2k** [comment]
This should work in v1.9.

@derekwaynecarr did you write docs?

**Comment by deads2k** [comment]
> This should work in v1.9.
> 
> @derekwaynecarr did you write docs?

My mistake.  We *almost* have the mechanism.  We need to dynamically get at the different informers.

**Comment by khatamnejad** [comment]
Hi @ironcladlou @nikhita!

Is someone working on this issue and #798 actively? If no one is working on them, I think I should be able to do so.

**Comment by nikhita** [comment]
@khatamnejad Hi! I am working on this. :)

I was a little busy from the past few weeks with university work but I will be taking this up again (had already started working on this before).

**Comment by sttts** [comment]
> Is there a design doc for this?

Understanding @nikhita correctly this is more like a bug of missing dynamic informers (via discovery) in the quota controller than a limited design. So the change is similar to the changes we did for the garbage collector not too long ago.

**Comment by khatamnejad** [comment]
@sttts  Could you please point out to he Garbage Collector issue you've just mentioned? I am not sure how it is going to help uses define a limit/quota for the number of Custom Resources.

**Comment by nikhita** [comment]
> Could you please point out to he Garbage Collector issue you've just mentioned?

@khatamnejad Basically, we need to do something like this for the quota controller:

https://github.com/kubernetes/kubernetes/blob/23a9136d4e91e6af7369573805ffb7803785ec1b/pkg/controller/garbagecollector/graph_builder.go#L191-L197

**Comment by jingxu97** [comment]
@nikhita your PR "Support object count quota for custom resources" #64201 is trying to support object count quota. Is there any plan to support general resources that consumed by a CRD object? For example, I have a CRD to represent a volume snapshot which will consume storage. Thanks!

**Comment by yliaog** [comment]
@nikhita given that the dynamic informers, listers have been added, what k8s release should the 'crd object count resourcequota' target at?

**Comment by bukzor** [comment]
Is there any workaround that I can use for this issue, today?

Or, is there any facility for me, as a mere developer-user, to write sufficient extensions to accomplish something equivalent or at least analogous to custom-resource quotas?

**Comment by rmb938** [comment]
I also would like this feature to be implemented. My current workaround is to use a validating webhook to deny the creation of crd object when over the quota.

**Comment by raushan2016** [comment]
IS this feature now available @nikhita @mbohlool

**Comment by pastudan** [comment]
@raushan2016 it seems to be. I was able to successfully configure a resourcequota with a CRD of `certmanager.k8s.io/certificates` against a kubernetes 1.15.1 cluster

**Comment by ktrOpenSource** [comment]
Can resource quota be used to apply Hard limits on number of objects - across the cluster - irrespective of namespace.

Eg: Can I say max 10k objects of CRD type "example.com/toys" across namespace a,b,c,d,e ?

**Comment by yliaog** [comment]
that is not supported today
