### ISSUE TITLE
URL parameters are not forwarded by kube-proxy

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#53789]
https://deck-ci.svc.ci.openshift.org/log?job=test_branch_origin_extended_networking&id=887

If I try to access the service above from inside a pod in the same cluster, I can't see the parameters being forwarded. Is this intentional or not?
```
$ curl http://deck/log?job=test_branch_origin_extended_networking&id=887                                                                                                             
[1] 64
bash-4.2$ Missing job and ID query
```

@kubernetes/sig-network-bugs 

Running on:
```
oc v3.7.0-alpha.1+36865f9-1008
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

openshift v3.7.0-alpha.1+70fcade-21
kubernetes v1.7.0+695f48a16f
```

**Comment by kargakis** [comment]
cc @danwinship @dcbw

**Comment by danwinship** [comment]
kube-proxy is a TCP-level proxy; it doesn't have the ability to not forward URL parameters

oh. Note the "`[1] 64`"; it's spawning a subshell to execute "`id=887`". You need quotes around your URL.

**Comment by kargakis** [comment]
@danwinship thanks!
