### ISSUE TITLE
code generators are silent

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#53791]
**What happened**:

Invoking [`deepcopy-gen`](https://github.com/kubernetes/kubernetes/tree/c1062de2ff82362f28637b12053965398bad1588/staging/src/k8s.io/code-generator/cmd/deepcopy-gen) (and other code generators) does not output any information regardless of the selected log level, making the generation flow harder to troubleshoot.

**What you expected to happen**:

`deepcopy-gen` is verbose about what it does when the loglevel is set.

**How to reproduce it (as minimally and precisely as possible)**:

Navigate to `k8s.io/apiextensions-apiserver/examples/client-go` and execute:

```console
$ deepcopy-gen -v 5 -i ./apis/cr/v1 -h /dev/null
(no output)
```

**Anything else we need to know?**:

Using an updated `glog` package solves the problem, which seems surprising to me [looking at the commit history](https://github.com/golang/glog/compare/44145f04b68cf362d9c4df2182967c2275eaefed...master).

```console
$ deepcopy-gen -v 5 -i ./apis/cr/v1 -h /dev/null
...
ERROR: logging before flag.Parse: I1012 13:05:22.300800   39771 deepcopy.go:545] Generating deepcopy function for type k8s.io/apiextensions-apiserver/examples/client-go/apis/cr/v1.ExampleSpec
ERROR: logging before flag.Parse: I1012 13:05:22.301055   39771 deepcopy.go:545] Generating deepcopy function for type k8s.io/apiextensions-apiserver/examples/client-go/apis/cr/v1.ExampleStatus
ERROR: logging before flag.Parse: I1012 13:05:22.301313   39771 execute.go:67] Assembling file "/go/src/k8s.io/apiextensions-apiserver/examples/client-go/apis/cr/v1/deepcopy_generated.go"
ERROR: logging before flag.Parse: I1012 13:05:22.307813   39771 main.go:87] Completed successfully.
```

**Comment by antoineco** [comment]
I suspect an outdated vendored version of the `glog` package:
```
commit 44145f04b68cf362d9c4df2182967c2275eaefed
Author: David Symonds <dsymonds@golang.org>
Date:   Wed Sep 24 06:47:00 2014 +1000
```

**Comment by mml** [comment]
@antoineco if you have a PR to fix this, we will happily take it.

**Comment by antoineco** [comment]
The short answer seems to be that `pflag` ignores the standard go flagset. However this is supposed to be covered by this snippet, and from my experience that works fine:

https://github.com/kubernetes/gengo/blob/master/args/args.go#L159-L162

I can't figure out why the loglevel is not set properly in that particular case. @sttts any idea maybe?

**Comment by dims** [comment]
@antoineco - did the `--alsologtostderr` and `--logtostderr` not help you?

**Comment by sttts** [comment]
Have to take a look. I also saw a case that client-gen did not accept standard go flags.

**Comment by sttts** [comment]
Which branch of k8s.io/code-generator is this about? master or release-1.8?

**Comment by sttts** [comment]
`deepcopy-gen -v 5 -i ./apis/cr/v1 -h /dev/null --alsologtostderr` gives output. Isn't that the normal behaviour of glog that nothing is printed? Actually, I wouldn't mind to switch to `--alsologtostderr` by default though.

**Comment by antoineco** [comment]
@stts I'm on the master branch. I haven't tried `--alsologtostderr`, I was expecting everything to be written either on stdout or stderr without using any extra flag.

Like I said, if I delete the vendored glog and use `master` logs are written simply by setting the V flag.

Probably a misunderstanding then.

**Comment by antoineco** [comment]
(and just to provide a little bit more context, the issue I was trying to troubleshoot was that my deepcopy file didn't get generated. I figured put the deepcopy flag was not in `doc.go` but in another file, but without output this took me a while to figure. Newbie experience report ftw :)

**Comment by antoineco** [comment]
@sttts @dims sorry for taking so long to investigate.

Now that I got more familiar with `glog` I understand what you meant with `--alsologtostderr` and `--logtostderr`: the level of verbosity doesn't matter because `glog` writes everything to temp files and nothing to stdout/err by default.

I figured most projects I've been using set `flag.Set("logtostderr", "true")` explicitly, which makes a lot of sense for CLI tools like these code generators in my opinion.

Would you be open to a PR that sets this as the default for all [generators](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator/cmd)?

**Comment by sttts** [comment]
> Would you be open to a PR that sets this as the default for all generators?

Yes, would be great. Please use https://github.com/kubernetes/kubernetes/pull/56403 as the base.
