### ISSUE TITLE
CM Stackdriver Adapter e2e test is failing all the time 

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#53800]
https://k8s-testgrid.appspot.com/sig-instrumentation#gce-sd-monitoring
https://k8s-testgrid.appspot.com/sig-instrumentation#gke-sd-monitoring

**Comment by piosz** [comment]
cc @fgrzadkowski @mwielgus @MaciekPytel

**Comment by cmluciano** [comment]
bump @kubernetes/sig-instrumentation-bugs 

this also affects some sig-net tests https://k8s-testgrid.appspot.com/sig-network#gci-gce-ip-alias

**Comment by crassirostris** [comment]
That's a different issue, google cloud project is misconfigured

/cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
@cmluciano why a sig-network test need to run stackdriver test?

**Comment by crassirostris** [comment]
@krzyzacy These are basic tests which guarantee that no feature breaks logging, so it's OK

**Comment by cmluciano** [comment]
thanks @crassirostris

**Comment by krzyzacy** [comment]
ah, it's running under it's own peoject `k8s-jenkins-gce-gci-ip-aliases` rather than fetching from the pool, I'll find owner of the project as I don't have permission to configure it

**Comment by cmluciano** [comment]
> @cmluciano why a sig-network test need to run stackdriver test?

Good question, I'm not 100% sure so I'll defer to @crassirostris 's answer. 

I'm just trying to deflake sig-net's dashboard :P

**Comment by krzyzacy** [comment]
@crassirostris btw I'm not sure why it fails in the gke job

**Comment by krzyzacy** [comment]
Added the required roles, waiting for result from next run

**Comment by crassirostris** [comment]
@krzyzacy As I've mentioned, the original issue is unrelated

**Comment by crassirostris** [comment]
@krzyzacy Thanks!

**Comment by krzyzacy** [comment]
/unassign
https://k8s-testgrid.appspot.com/google-gce#gci-gce-ip-alias
the test is green now for ip-alias job
