### ISSUE TITLE
Lease reconciler creates incorrect kubernetes endpoint and lease files

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#53803]
/kind bug

The lease reconciler creates the kubernetes endpoint with a prefix of kube-apiserver-endpoint, however that is not the prefix that the rest of kube uses.  The end result is that the kubernetes service doesn't have an endpoint, and kubectl won't list the kubernetes endpoint.

The lease reconciler also creates lease files with a really long lease time instead of the default 15 seconds.

@liggitt @kubernetes/sig-api-machinery-bugs @sttts

**Comment by ncdc** [comment]
cc @rphillips xref #51698

**Comment by ncdc** [comment]
kube-apiserver-endpoint is used for the lease itself, from what I remember. I don't think that's an issue by itself.

**Comment by ncdc** [comment]
Oh but it does look like the endpointRegistry for the lease reconciler is misconfigured to use that

**Comment by rphillips** [comment]
i'll look into it

**Comment by rphillips** [comment]
what is the name that should be used?

**Comment by ncdc** [comment]
services/endpoints afaik - https://github.com/kubernetes/kubernetes/blob/efe6180806374f77431840cbd086a902f6e645a9/pkg/kubeapiserver/default_storage_factory_builder.go#L36

**Comment by ncdc** [comment]
Yeah, making that change locally fixed it for me

**Comment by ncdc** [comment]
But I'm not seeing the masterleases/apiServerIPInfo data in etcd, or I'm issuing the wrong command to find it

**Comment by rrati** [comment]
@ncdc I had that same problem.  The lease timeout is set way high, but for some reason that resulted in the lease files being created for only a very short time.  I'm not sure why.  Playing with the ttl amount got the lease files to stay around....forever.  I've got a PR I'm about to push to fix both issues.

**Comment by ncdc** [comment]
@rphillips FYI @rrati has a PR for this now

**Comment by mml** [comment]
cc @cheftako
