### ISSUE TITLE
Implement predicate ordering for the kubernetes scheduler

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#53812]
following the design proposal on kubernetes/community#1152 this will be the issue that will track down the work to implement predicates ordering, work to be done:

* set predicate ordering to create the proposed static ordering / tests
* export restrictiveness as a prometheus metric
* write docs and examples

also to be done based on customers feedback:

* implement the end-user ordering (scheduler policy parsing + override of the static ordering) / tests

I'll create the PRs accordingly, after  kubernetes/community#1152 is merged.

@gmarek @bsalamat @k82cn

**Comment by yastij** [comment]
@gmarek @bsalamat @k82cn - Also needs to be added to 1.9 milestone

**Comment by resouer** [comment]
@yastij I added the milestone, while updating your recent progress status would be helpful here.

**Comment by yastij** [comment]
I'll submit a first version tomorrow, with a minimal modification to implement ordering.
