### ISSUE TITLE
Conformance annotations require build checks to ensure format is adhered to

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/kubernetes#53810]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

/sig area/conformance

**What happened**:
Kubernetes conformance annotations are comments in the e2e test suite next to tests labeled [Conformance] and are used for generating a document that describes the list of conformance tests as identified by the Kubernetes Conformance workgroup.  Currently these annotation comments do not undergo a build check to ensure the annotation format is being adhered to.
**What you expected to happen**:
Annotation comments should  undergo a build check to ensure the annotation format is being adhered to.
**How to reproduce it (as minimally and precisely as possible)**:
Create a Conformance annotation in the e2e test suite for a conformance test and do not follow the prescribed format of 

/*
	  Testname: pods-exec-liveness-probe-not-restarted
	  Description: Make sure when exec liveness probe succeeds, the pod should
	         not be restarted.
*/
It("should *not* be restarted with a exec \"cat /tmp/health\" liveness probe [Conformance]", func() {

**Anything else we need to know?**:
See [PR #53742](https://github.com/kubernetes/kubernetes/pull/53742) for more details on this.

**Environment**:

**Comment by mml** [comment]
FYI I'm also working on a presubmit check to verify that any addition or removal of `[Conformance]` tags is reviewed big sig-architecture.  There may be some overlap, so if you have an implementation plan in mind, please let me know.

Thanks!

**Comment by brahmaroutu** [comment]
#52863 @mml The current tooling assumes that we leverage [Conformance] tag. Can you elaborate other options?

**Comment by mml** [comment]
I'm doing the same thing.  See my half-baked PR at #53909

**Comment by duglin** [comment]
@mml can we discuss on the conformance mailing list so that we avoid duplicate work. There might be some overlap but not completely.

**Comment by bradtopol** [comment]
So I have been adding lots of conformance annotations to the [Conformance] tests in the e2e test suite. Here are some real world issues I ran into that are related to this issue: 

In addition to make sure the comments have a test name and description it would be very helpful to  list all conformance tests that have no annotation comment associated with them and to also list if two tests have the same test-name.  Both could happen easier than you think and having the tool report those situations would really help to ensure the accuracy of the annotations.

**Comment by mml** [comment]
@brahmaroutu you are still working on this, correct?
