### ISSUE TITLE
Getting CRD Validation to Beta

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#53829]
This is a tracking issue for discussion about what needs to be done in order to move CRD Validation to Beta for 1.9.

Related links:
* [CRD Umbrella Issue (feature repo)](https://github.com/kubernetes/features/issues/95)
* [CRD Validation feature request](https://github.com/kubernetes/kubernetes/issues/38117)
* [CRD Validation Proposal (community repo)](https://github.com/kubernetes/community/pull/708)
* [CRD Validation implementation PR (alpha)](https://github.com/kubernetes/kubernetes/pull/47263)

Additional discussions:
* [CRD Validation using OpenAPI v3](https://github.com/kubernetes/kubernetes/issues/49879)

**Comment by sttts** [comment]
Seeing these feature, but they are not necessarily blocking for beta:
- defaulting https://github.com/kubernetes/kubernetes/pull/52034
- readonly fields
- JSON schema references to other APIGroups, e.g. embedding a PodSpec schema.

As far as I see, all of these can be added post-beta. Right now we forbid setting default values and marking fields as readonly. So nobody using validation now (or with a beta without these features) will be surprised when we add them.

JSON schema references to other APIGroups just do not exist right now. We have to "invent" a reference name space and resolve the references. This can be added anytime as an additional feature.

**Comment by sttts** [comment]
As discussed today in the [sig-api-machinery meeting](https://docs.google.com/a/google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit?usp=drive_web) there are no objections to move forward to beta. @colemickens will add updates for that in the features repo.

**Comment by nikhita** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/54579.

**Comment by deads2k** [comment]
> As discussed today in the sig-api-machinery meeting there are no objections to move forward to beta. @colemickens will add updates for that in the features repo.

Agree.

**Comment by colemickens** [comment]
It looks like @sttts has already updated the only tracking issue we have in kubernetes/features. I've sent the PR for the feature gate promotion: https://github.com/kubernetes/kubernetes/pull/54647

**Comment by colemickens** [comment]
And one for the docs: https://github.com/kubernetes/website/pull/6065
