### ISSUE TITLE
ServiceReference in ExternalAdmissionHookConfiguration can't be used by most consumers

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#53825]
The only server in the cluster which is guaranteed to be able to lookup services and endpoints is the `kube-apiserver`.  All other consumers of the `ExternalAdmissionHookConfiguration` API cannot use the service reference as-is.  We should optimize for the normal case and make this a DNS name.

The case in `APIServices` is different, since those are *only* terminated by the `kube-apiserver`

@kubernetes/sig-api-machinery-bugs

**Comment by caesarxuchao** [comment]
>  All other consumers of the ExternalAdmissionHookConfiguration API 

Are you referring to the user apiservers, or are there additional consumers?

If it's UAS, is moving ServiceResolver code to the generic apiserver enough to close this issue?

**Comment by deads2k** [comment]
> Are you referring to the user apiservers, or are there additional consumers?
> 
> If it's UAS, is moving ServiceResolver code to the generic apiserver enough to close this issue?

It's not even just UAS's.  The vast majority of `kube-apiserver` installations and the other webhook APIs use DNS and IP routing.  To my knowledge, only GKE uses the ssh tunnel.

**Comment by deads2k** [comment]
> If it's UAS, is moving ServiceResolver code to the generic apiserver enough to close this issue?

Moving the `ServiceResolver` into the genericapiserver is inappropriate since only the `kube-apiserver` can actually resolve services.

**Comment by deads2k** [comment]
/priority important-soon

Needed for beta since the API hurts all but one deployment of one component.

**Comment by caesarxuchao** [comment]
> Moving the ServiceResolver into the genericapiserver is inappropriate since only the kube-apiserver can actually resolve services.

The service resolver uses the services and endpoints API to resolve a service, I don't understand why "only the kube-apiserver can actually resolve services."

**Comment by deads2k** [comment]
> The service resolver uses the services and endpoints API to resolve a service, I don't understand why "only the kube-apiserver can actually resolve services."

No other API server will have permission to read random services and endpoints in the cluster.  That means the resolution will fail. They have to ignore the resolution attempt, which indicates the API doesn't serve most consumers.

**Comment by caesarxuchao** [comment]
Ok, agree that UAS shouldn't use ServiceResolver.

But I still think the service reference in the current registration API is enough. I think UAS can rely on kube-dns and kube-proxy to properly route "serviceName.namespaceName.svc" DNS name.

**Comment by deads2k** [comment]
> Ok, agree that UAS shouldn't use ServiceResolver.
> 
> But I still think the service reference in the current registration API is enough. I think UAS can rely on kube-dns and kube-proxy to properly route "serviceName.namespaceName.svc" DNS name.

You can actually encapsulate that inside of the dialer and `kube-apiserver` already passes a special dialer. See https://github.com/kubernetes/kubernetes/pull/54163#issuecomment-338260513

**Comment by dims** [comment]
@deads2k what do we need in this for 1.9? (Can we move this to 1.10)?

**Comment by deads2k** [comment]
> @deads2k what do we need in this for 1.9? (Can we move this to 1.10)?

Already addressed.
