### ISSUE TITLE
ClientCert used for GenericAdmissionWebhook is incorrect

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#53828]
The ClientCert used to identify the apiserver to the admission webhook should match the CA used to terminate client cert authentication, not the one used to terminate front proxies.  The current flags being used are incorrect.

@kubernetes/sig-api-machinery-bugs

**Comment by caesarxuchao** [comment]
What do you think the roles of these two CAs are? 

I think the proxy CA is to ensure the security of the control plane, and webhooks are part of the control plane, so using the proxy CA is better.

**Comment by deads2k** [comment]
The proxy CA is used to terminate a front proxy which is asserting an identity. The client CA is used to terminate a connection which is directly identifying a client.  This is a case of the latter: "this is who I am".  This is not a case of "the subject connecting is user Foo".

I would accept using a completely different CA if you wish, but the proxy CA is inappropriate.

**Comment by deads2k** [comment]
/priority important-soon

Needed for beta (even for alpha), because the current trust relationship is incorrect.

**Comment by caesarxuchao** [comment]
I agree with the general idea. Do you have in mind the exact client CA to reuse? Is `--tls-cert-file` the right one?

**Comment by deads2k** [comment]
> I agree with the general idea. Do you have in mind the exact client CA to reuse? Is --tls-cert-file the right one?

I would not re-use an existing cert.  Instead I would make an `--admission-kubeconfig` which matches `--authentication-kubeconfig` and `--authorization-kubeconfig` for the genericapiserver.   This kubeconfig file would contain whatever authentication and trust information was required.  For the kube-apiserver, I would recommend (but not require) creating a client certificate signed by the `--client-ca-file` since that delivers maximum topology flexibility on the cluster leveraging our already existent features.

As this API grows in beta, we could (probably should) seriously consider using a kubeconfig file with nicknames matching the admission registration hook names so that a single file can configure different authentication information.

**Comment by caesarxuchao** [comment]
Sorry, I meant to ask what CA to reuse, not cert. Updated.

Other than supporting multiple authentication methods, do we need the kubecofig for other reasons?

**Comment by mbohlool** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
I am not convinced? The client CA is for clients of apiserver to prove their identity. the proxy CA is for when the apiserver itself is the client and needs to prove its identity.

**Comment by lavalamp** [comment]
Please link to where the intended purpose of these certs is documented?

**Comment by deads2k** [comment]
> I am not convinced? The client CA is for clients of apiserver to prove their identity. the proxy CA is for when the apiserver itself is the client and needs to prove its identity.

The `--request-client-ca-file` signed clientcert is used when a client wants to assert that a request is being made a different subject (request-header auth from here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L59-L61).

The `--client-ca-file` signed clientcert is used when a client wants to make a request as the client it is using (client cert auth from here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L91-L94).

For webhooks, the request is made as the client making the request (like `--client-ca-file`).  However, since webhooks by their nature can speak to external systems, you cannot directly wire any certificate as the unequivocal client cert.  We use the `--authentication-token-webhook-config-file` (here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/authentication.go#L261-L263) to allow the integration with any external system or service.  The admission webhook needs a similar flag.

Tagging @kubernetes/sig-auth-misc in case anyone else from sig-auth wants to join in.

**Comment by lavalamp** [comment]
> For webhooks, the request is made as the client making the request (like --client-ca-file). 

Why would that be true for the dynamic admission webhooks? I would not expect it to be true.

**Comment by lavalamp** [comment]
dynamic admission webhooks should be verifying that the request is coming from apiserver.

**Comment by caesarxuchao** [comment]
@liggitt @lavalamp @deads2k have you reached agreement on this issue?

**Comment by caesarxuchao** [comment]
Is the `client-ca-file` used to sign client certificates for the clients that talk to the apiserver?

**Comment by lavalamp** [comment]
This came up again in the context of giving kube-apiserver a default that is more secure than the current unauth'd one (as it is hard to get files into the test environments to test this; also a default is way more user-friendly). I can't parse @deads2k description of the three CAs above, and unfortunately the links are not much more clear:

## option 1, ClientCAFile:

> requestheader-client-ca-file", s.ClientCAFile, ""+
> 		"Root certificate bundle to use to verify client certificates on incoming requests "+
>		"before trusting usernames in headers specified by --requestheader-username-headers

I take this to mean that if I have a client cert signed by something in this CA bundle, apiserver will trust me to state the request's username in a header. These certs are super powerful as they allow impersonating anyone.

## option 2, ClientCA: (note super confusing parameter name makes it sound the same as the previous)

>	fs.StringVar(&s.ClientCA, "client-ca-file", s.ClientCA, ""+
>		"If set, any request presenting a client certificate signed by one of "+
>		"the authorities in the client-ca-file is authenticated with an identity "+
>		"corresponding to the CommonName of the client certificate.")

I take this to mean that if I have a client cert signed by something in this CA bundle, apiserver will trust that the user is in the CN of the client cert.

I think @deads2k is trying to say that apiserver should mint itself a client cert signed by this CA (or get an admin to mint it at install time), and that generally everything (including webhooks) in a Kubernetes cluster should trust this CA in the same way (is this CA published in the configmap?). And that when apiserver is a client, it should identify itself in the same way any other client does. This whole chain of reasoning is not obvious but I'm currently thinking it's reasonable. It doesn't help us get a default though, which is the problem at hand.

## option 3, seems to be about another webhook which probably ought not to be reused since the purpose is different and the point of the default is what to do if the config file isn't present.

> fs.StringVar(&s.WebHook.ConfigFile, "authentication-token-webhook-config-file", s.WebHook.ConfigFile, ""+
>			"File with webhook configuration for token authentication in kubeconfig format. "+
>			"The API server will query the remote service to determine authentication for bearer tokens.")

**Comment by deads2k** [comment]
> option 3, seems to be about another webhook which probably ought not to be reused since the purpose is different and the point of the default is what to do if the config file isn't present.

That was an example of how the plumbing was solved for integration with arbitrary hooks in authentication.  Not a suggestion for re-use.

I think the default for the `kube-apiserver` (the `*` entry in the kubeconfig file), should be consistent with the generic apiservers and should be anonymous if not set.  Setting up a particular topology (for CI say), I'd be ok with adding a client certificate that is signed by `--client-ca-file` to the `*` entry in the kubeconfig file.

I wouldn't apply any default in the `kube-apiserver` code though.  That should continue to respect the kubeconfig file.

**Comment by lavalamp** [comment]
The annoying thing about adding a file is that (most likely) individual fixes need to be made to every cloud provider. We would need to test that the file is used anyway, so I agree that adding a default actually ends up making more work.

A default would be waaay more user friendly though :(

**Comment by lavalamp** [comment]
This has been changed already and can be closed, right?
