### ISSUE TITLE
ExternalAdmissionHookConfiguration cannot choose URL

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#53826]
The webhook admission plugin can only post to `/`.  This needs to be a configurable option so that we could host in a normal API server and possibly combine multiple admission webhooks together.

@kubernetes/sig-api-machinery-bugs

**Comment by caesarxuchao** [comment]
I will put this into consideration together with other API refactoring.

**Comment by deads2k** [comment]
> I will put this into consideration together with other API refactoring.

This is required to match parity with other webhooks like ImagePolicy, authentication, and authorization.  It's also essential for making it easy to build an admission webhook server out of our genericapiserver, which is really handy for handling the object decoding required for writing the actual hook itself.

**Comment by deads2k** [comment]
/priority important-soon

Needed for beta to make it possible to write a reasonable webhook target.

**Comment by caesarxuchao** [comment]
I had a discussion with @cheftako @mbohlool @lavalamp. The consensus is that we should add Path to the webhook configuration. It will default to root, and it has to be a DNS1123 label.

**Comment by liggitt** [comment]
> It will default to root, and it has to be a DNS1123 label.

URL paths are not DNS1123 labels... it should be a valid URL path (e.g. `/foo/bar/baz` should be allowed)

**Comment by caesarxuchao** [comment]
Right. Maybe make each segment DNS1123? I just want to use the least powerful characters for the url segments. I think DNS1123 is the most stringent string validation we have. I want to reserve special characters for purposes like string substitution.

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/kubernetes/pull/54145

**Comment by deads2k** [comment]
> Right. Maybe make each segment DNS1123? I just want to use the least powerful characters for the url segments. I think DNS1123 is the most stringent string validation we have. I want to reserve special characters for purposes like string substitution.

It needs to allow subdomains to allow matching recommended group names.  Also, why would you want string substitution?

**Comment by caesarxuchao** [comment]
> Also, why would you want string substitution?

So that a user can specify "$Group/$Version/$Resource/$Namespace..." in config.URLPath, and the webhook plugin can automatically expand them.
