### ISSUE TITLE
IPV6 Documentation 

### ISSUE THREAD

**Issue by mmueen** [kubernetes/kubernetes#53824]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig network
/area ipv6

**What happened**:
There is not consolidated documentation / guide available for deployment of Kubernetes with IPV6. The information is sparse and not at a single location, so it would be really helpful if all the documentation is compiled in wiki and act as a single stop for anyone trying to deploy kubernetes with IPV6.

**What you expected to happen**:
Complete guide of deploying Kubernetes with IPV6.
List of issues / components which lack IPV6 support right now.

**Environment**:
- Kubernetes version (use `kubectl version`): Latest
- Cloud provider or hardware configuration**: VirtualBox cluster, Ubuntu 16.04.1 host, CentOS 7 guests
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cmluciano** [comment]
cc @rpothier @danehans

**Comment by valentin2105** [comment]
if it can help : https://opsnotice.xyz/kubernetes-ipv6-only/
