### ISSUE TITLE
kubeadm join fails w/kubelet error: failed to "StartContainer" for "kubedns"

### ISSUE THREAD

**Issue by bladerunner512** [kubernetes/kubernetes#53844]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug
/sig cluster-lifecycle
/area kubeadm

**What happened**:
Used kubeadm init to initialize master, then used kubeadm to join slave. Master never sees adds slave node and slave kubelet has 'failed to "StartContainer" for "kubedns"' error

**What you expected to happen**:
Slave node should join cluster

**How to reproduce it (as minimally and precisely as possible)**:
1. Clean install of kubernetes
2. kubeadm init --token-ttl 0 --pod-network-cidr=10.244.0.0/16
3. Install pod network: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml
4. Join on slave node: kubeadm join --token <token> <master-ip>:<master-port> --discovery-token-ca-cert-hash sha256:<hash>

**Anything else we need to know?**:
NO_PROXY set "127.0.0.1, localhost, <master-ip>"

**Environment**:
- Kubernetes version (use `kubectl version`):
master@ubuntu:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Docker
Docker version: 17.09.0-ce

- Install tools:
- Others:

before join by slave:
master@ubuntu:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   etcd-ubuntu                      1/1       Running   0          10m
kube-system   kube-apiserver-ubuntu            1/1       Running   0          10m
kube-system   kube-controller-manager-ubuntu   1/1       Running   0          9m
kube-system   kube-dns-545bc4bfd4-s2wml        3/3       Running   0          9m
kube-system   kube-flannel-ds-tmpdg            1/1       Running   0          6m
kube-system   kube-proxy-nhmz8                 1/1       Running   0          9m
kube-system   kube-scheduler-ubuntu            1/1       Running   0          9m

master@ubuntu:~$ kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
ubuntu    Ready     master    11m       v1.8.1

join on slave node:
root@ubuntu:~# kubeadm join --token 888fb2.176443c7da1f21b9 192.168.80.158:6443 --discovery-token-ca-cert-hash sha256:43d13c540a4c70686b5a3bd54a0514eddcaf5d0f5876f5b3a059eee4de833609
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.09.0-ce. Max validated version: 17.03
[preflight] Starting the kubelet service
[discovery] Trying to connect to API Server "192.168.80.158:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.80.158:6443"
[discovery] Requesting info from "https://192.168.80.158:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.80.158:6443"
[discovery] Successfully established connection with API Server "192.168.80.158:6443"
[bootstrap] Detected server version: v1.8.1
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.

slave@ubuntu:~$ journalctl -u kubelet (note: /etc/kubernetes/pki/ca.crt file does exist):
Oct 11 09:58:32 ubuntu systemd[1]: Started kubelet: The Kubernetes Node Agent.
Oct 11 09:58:48 ubuntu kubelet[891]: I1011 09:58:48.621416     891 feature_gate.go:156] feature gates: map[]
Oct 11 09:58:48 ubuntu kubelet[891]: I1011 09:58:48.623782     891 controller.go:114] kubelet config controller: starting controller
Oct 11 09:58:48 ubuntu kubelet[891]: I1011 09:58:48.624160     891 controller.go:118] kubelet config controller: validating combination of defaults and flags
Oct 11 09:58:49 ubuntu kubelet[891]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Oct 11 09:58:49 ubuntu systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 09:58:49 ubuntu systemd[1]: kubelet.service: Unit entered failed state.
Oct 11 09:58:49 ubuntu systemd[1]: kubelet.service: Failed with result 'exit-code'.
Oct 11 14:58:59 ubuntu systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Oct 11 14:58:59 ubuntu systemd[1]: Stopped kubelet: The Kubernetes Node Agent.

slave@ubuntu:~$ systemctl status kubelet -o verbose  kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Thu 2017-10-12 18:18:24 CDT; 5min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 16668 (kubelet)
    Tasks: 16
   Memory: 66.0M
      CPU: 17.152s
   CGroup: /system.slice/kubelet.service
           └─16668 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki

Thu 2017-10-12 18:22:44.858901 CDT [s=3b7eb488ec754e91b013ca2a3dcf5e1e;i=188b;b=68d386d44bcc41e5a312b9e1f29398b0;m=1858abae7;t=55b61d14af415;x=5bde90da1a643271]
    PRIORITY=6
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=68d386d44bcc41e5a312b9e1f29398b0
    _MACHINE_ID=b23f6303dbee42f79605ace08839369a
    _HOSTNAME=ubuntu
    SYSLOG_FACILITY=3
    _CAP_EFFECTIVE=3fffffffff
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=kubelet
    _PID=16668
    _COMM=kubelet
    _EXE=/usr/bin/kubelet
    _CMDLINE=/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki
    _SYSTEMD_CGROUP=/system.slice/kubelet.service
    _SYSTEMD_UNIT=kubelet.service
    MESSAGE=I1012 18:22:44.857692   16668 kuberuntime_manager.go:738] checking backoff for container "kubedns" in pod "kube-dns-545bc4bfd4-s2wml_kube-system(b136f897-aece-11e7-9fe4-000c2941e694)"
Thu 2017-10-12 18:22:44.859228 CDT [s=3b7eb488ec754e91b013ca2a3dcf5e1e;i=188c;b=68d386d44bcc41e5a312b9e1f29398b0;m=1858abc2e;t=55b61d14af55c;x=85c3d43126b42c6c]
    PRIORITY=6
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=68d386d44bcc41e5a312b9e1f29398b0
    _MACHINE_ID=b23f6303dbee42f79605ace08839369a
    _HOSTNAME=ubuntu
    SYSLOG_FACILITY=3
    _CAP_EFFECTIVE=3fffffffff
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=kubelet
    _PID=16668
    _COMM=kubelet
    _EXE=/usr/bin/kubelet
    _CMDLINE=/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki
    _SYSTEMD_CGROUP=/system.slice/kubelet.service
    _SYSTEMD_UNIT=kubelet.service
    MESSAGE=I1012 18:22:44.858075   16668 kuberuntime_manager.go:748] Back-off 20s restarting failed container=kubedns pod=kube-dns-545bc4bfd4-s2wml_kube-system(b136f897-aece-11e7-9fe4-000c2941e694)
Thu 2017-10-12 18:22:44.859786 CDT [s=3b7eb488ec754e91b013ca2a3dcf5e1e;i=188d;b=68d386d44bcc41e5a312b9e1f29398b0;m=1858abe5c;t=55b61d14af78a;x=4d93e552d7b28619]
    PRIORITY=6
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=68d386d44bcc41e5a312b9e1f29398b0
    _MACHINE_ID=b23f6303dbee42f79605ace08839369a
    _HOSTNAME=ubuntu
    SYSLOG_FACILITY=3
    _CAP_EFFECTIVE=3fffffffff
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=kubelet
    _PID=16668
    _COMM=kubelet
    _EXE=/usr/bin/kubelet
    _CMDLINE=/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki
    _SYSTEMD_CGROUP=/system.slice/kubelet.service
    _SYSTEMD_UNIT=kubelet.service
    MESSAGE=E1012 18:22:44.858163   16668 pod_workers.go:182] Error syncing pod b136f897-aece-11e7-9fe4-000c2941e694 ("kube-dns-545bc4bfd4-s2wml_kube-system(b136f897-aece-11e7-9fe4-000c2941e694)"), skipping: failed to "StartContainer" for "kubedns" with CrashLoopBackOff: "Back-off 20s restarting failed container=kubedns pod=kube-dns-545bc4bfd4-s2wml_kube-system(b136f897-aece-11e7-9fe4-000c2941e694)"

**Comment by bladerunner512** [comment]
After switching from Flannel to Calico I get kublet 'Error syncing pod kube-dns':
MESSAGE=I1017 08:58:20.458189   92898 kuberuntime_manager.go:748] Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns...
MESSAGE=E1017 08:58:20.458293   92898 pod_workers.go:182] Error syncing pod b6b29930-aece-11e7-9319-000c2941e694 ("kube-dns...
MESSAGE=, failed to "StartContainer" for "dnsmasq" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=dnsmasq pod=kube-dns

**Comment by luxas** [comment]
Hi!

Thank you for filing this issue. We appreciate your interest in Kubernetes and kubeadm.
In order to make the kubernetes/kubernetes issue tracker more usable, we're routing issues to different repositories with different focuses.

I think this issue belongs in the kubeadm repository. Please move this issue to the [kubeadm repo tracker](https://github.com/kubernetes/kubeadm/issues) in order for the kubeadm team to be able to track this efficiently. If you disagree with my assessment of moving this issue, please speak up and/or reopen the issue.

Thank you and have a good day!
