### ISSUE TITLE
Init container not updating when applying new configuration

### ISSUE THREAD

**Issue by DrewEaster** [kubernetes/kubernetes#53883]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I've discovered what appears to be an issue with updating a pod/deployment specification's init containers. This issue does not exist when using the legacy approach for defining init containers (using the `pod.beta.kubernetes.io/init-containers` metadata annotation), but does appear when using the latest approach (`initContainers` section in the pod spec).

When I update the image to a new version/tag, it remains as the existing version/tag (i.e. the update does not propagate to the cluster as expected).

**What you expected to happen**:

I expect, like when using the legacy annotation approach, that any changes I make to the init container spec should be reflected appropriately.

**How to reproduce it (as minimally and precisely as possible)**:

Full details for how to reproduce are available here: https://github.com/DrewEaster/k8s-init-container-issue#steps-for-recreating-the-issue-using-minikube

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.5
- Cloud provider or hardware configuration**: GKE and Minikube

/sig cli

**Comment by liggitt** [comment]
Prior to 1.8, if you make changes to an init container, you must update both the annotation and the field

see https://github.com/kubernetes/kubernetes/issues/47264#issuecomment-327541429
