### ISSUE TITLE
Self-Hosted E2E Conformance Tests Fail kubectl Executions

### ISSUE THREAD

**Issue by gekart** [kubernetes/kubernetes#53894]
/kind feature

I am running self-hosted E2E conformance tests in a pod on every freshly deployed cluster (similar as in https://github.com/ozdanborne/k8s-e2e-containerized). e2e.test is started without any host, kubeconfig configuration and picks up the InClusterConfig correctly. All conformance tests pass nicely, except from kubectl executions.

kubectl gets executed by e2e.test as `kubectl --server=http://127.0.0.1:8080 ...` and therefore fails on connection refused. In the container running kubectl without --server, will work as expected, since I have service accounts set up correctly.

Looking into code, for some reason defaultHost is set to http://127.0.0.1:8080 ( https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L33 ). That value is not used within e2e.test as it seems, but is passed on to kubectl, only.

Omitting `--server=http://127.0.0.1:8080` would let the kubectl run with no problem, why is it set to that value (default proxy port is 8001)?

Currently I am mitigating by pre-exectuting `kubectl proxy --port=8080 &`
before running e2e.test.

**Comment by timothysc** [comment]
This is known, and there is a means to circumvent by passing in a kubeconfig.  

I've had a todo to fix this for a while, but I'll prioritize to get this fixed sooner. 

fyi - @chuckha

**Comment by dims** [comment]
@timothysc can you please leave some notes on how you wanted to fix this? i can take a shot at it

**Comment by timothysc** [comment]
@dims if you can write the in-cluster config out and set KUBECONFIG prior to the kubectl tests that would help.

**Comment by dims** [comment]
@timothysc : ack. 

@gekart : Can you please send me the list of tests that fails? So i can be sure my changes will work for you?

**Comment by dims** [comment]
@gekart - reviewing the code paths PR #53924 should do the trick, but would like to get that list of failed tests so i can confirm.

Thanks,
Dims

**Comment by gekart** [comment]
@dims every conformance test that shelling out kubectl is failing. as elegant as your PR looks, I think it won't work, due to authentication:

```
root@e2e-bash:/# kubectl get nodes
NAME                                           STATUS    AGE       VERSION
ip-10-0-39-242.eu-central-1.compute.internal   Ready     2d        v1.7.7
ip-10-0-58-247.eu-central-1.compute.internal   Ready     2d        v1.7.7
root@e2e-bash:/# echo "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
https://100.64.0.1:443
root@e2e-bash:/# kubectl --server="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" get nodes
Please enter Username: ^C
root@e2e-bash:/# 
```

kubectl will work out of the box on a pod with InClusterConfig, however, as soon as you start specifying one single parameter (such as --server), even if you do not change it compared to InClusterConfig, you will need to specify the rest, too.

**Comment by dims** [comment]
@gekart can you give me the list of the 20 tests please?

**Comment by gekart** [comment]
Sure, rerunning the tests, might take an hour.

**Comment by gekart** [comment]
`[k8s.io] Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:619
  [k8s.io] Kubectl run job
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:619
    should create a job from an image when restart is OnFailure [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1356

    Expected error:
        <exec.CodeExitError>: {
            Err: {
                s: "error running &{/usr/local/bin/kubectl [kubectl --server=http://127.0.0.1:8080 run e2e-test-nginx-job --restart=OnFailure --generator=job/v1 --image=gcr.io/google_containers/nginx-slim:0.7 --namespace=e2e-tests-kubectl-qplqh] []  <nil>  error: failed to discover supported resources: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused\n [] <nil> 0xc420731ec0 exit status 1 <nil> <nil> true [0xc42000eca0 0xc42000ece0 0xc42000ed00] [0xc42000eca0 0xc42000ece0 0xc42000ed00] [0xc42000ecd8 0xc42000ecf8] [0x1cebcc0 0x1cebcc0] 0xc420836300 <nil>}:\nCommand stdout:\n\nstderr:\nerror: failed to discover supported resources: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused\n\nerror:\nexit status 1\n",
            },
            Code: 1,
        }
        error running &{/usr/local/bin/kubectl [kubectl --server=http://127.0.0.1:8080 run e2e-test-nginx-job --restart=OnFailure --generator=job/v1 --image=gcr.io/google_containers/nginx-slim:0.7 --namespace=e2e-tests-kubectl-qplqh] []  <nil>  error: failed to discover supported resources: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused
         [] <nil> 0xc420731ec0 exit status 1 <nil> <nil> true [0xc42000eca0 0xc42000ece0 0xc42000ed00] [0xc42000eca0 0xc42000ece0 0xc42000ed00] [0xc42000ecd8 0xc42000ecf8] [0x1cebcc0 0x1cebcc0] 0xc420836300 <nil>}:
        Command stdout:
        
        stderr:
        error: failed to discover supported resources: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: getsockopt: connection refused
        
        error:
        exit status 1
        
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124`

**Comment by gekart** [comment]
```
Summarizing 24 Failures:

[Fail] [k8s.io] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if not matching [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:84

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run job [It] should create a job from an image when restart is OnFailure [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Pods Extended [k8s.io] Delete Grace Period [It] should be submitted and removed [Conformance] [Flaky] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:162

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl patch [It] should add annotations for pods in rc [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] SchedulerPredicates [Serial] [BeforeEach] validates resource limits of pods that are allowed to run [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:84

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl api-versions [It] should check if v1 is in available api versions [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl version [It] should check is all data is printed [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run --rm job [It] should create a job from an image, then delete the job [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run rc [It] should create an rc from an image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run default [It] should create an rc or deployment from an image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl label [BeforeEach] should update the label on a resource [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl logs [BeforeEach] should be able to retrieve and filter logs [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl expose [It] should create services for rc [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Guestbook application [It] should create and stop a working application [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should do a rolling update of a replication controller [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should create and stop a replication controller [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should scale a replication controller [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Proxy server [It] should support proxy with --port 0 [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1482

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl replace [It] should update a single-container pod's image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run deployment [It] should create a deployment from an image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl rolling-update [It] should support rolling-update to same image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

[Fail] [k8s.io] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if matching [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:84

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run pod [It] should create a pod from an image when restart is Never [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2124

Ran 149 of 652 Specs in 2600.345 seconds
FAIL! -- 125 Passed | 24 Failed | 0 Pending | 503 Skipped --- FAIL: TestE2E (2600.38s)
FAIL
```

**Comment by gekart** [comment]
See, there are three variants on how to invoke kubectl:

```
root@e2e-bash:/# kubectl --server=http://100.64.0.1:443 run e2e-test-nginx-job --restart=OnFailure --generator=job/v1 --image=gcr.io/google_containers/nginx-slim:0.7 --namespace=e2e-tests-kubectl-qplqh
error: failed to discover supported resources: Get http://100.64.0.1:443/api: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
root@e2e-bash:/# kubectl --server=https://100.64.0.1:443 run e2e-test-nginx-job --restart=OnFailure --generator=job/v1 --image=gcr.io/google_containers/nginx-slim:0.7 --namespace=e2e-tests-kubectl-qplqh
Please enter Username: ^C
root@e2e-bash:/# kubectl run e2e-test-nginx-job --restart=OnFailure --generator=job/v1 --image=gcr.io/google_containers/nginx-slim:0.7 --namespace=e2e-tests-kubectl-qplqh
Error from server (NotFound): namespaces "e2e-tests-kubectl-qplqh" not found
```

Only the third one gets to the API and and gets authorized.

**Comment by dims** [comment]
Excellent! thanks @gekart will take a look at the scenarios. thanks for digging in.
