### ISSUE TITLE
cannot apply networking.k8s.io/v1 - updates to networkpolicy spec are forbidden

### ISSUE THREAD

**Issue by boeboe** [kubernetes/kubernetes#53906]
Hi all,

/sig area/kubectl
/sig sig/network
@kubernetes/sig-network-bugs

We made the upstep from k8s 1.6 to 1.7.8 on our k8s clusters. As good k8s citizens, we have updated our NetworkPolicy yaml deployment files to use the new **networking.k8s.io/v1** apiVersion. It appears however that a retrieval of NetworkPolicies deployed this way, still use the **extensions/v1beta1** apiVersion. I suppose this is due to backwards compatibility concerns, which I can perfectly understand.

What is the issue however, is that we deploy our NetworkPolicies (in an automated way, using a cluster applier process within each namespace, that pulls the yaml config from git and applies them periodically) using "kubectl apply -f *.yaml". The kubectl client however refuses to do so, since he detects a _false_ change between what's deployed (extensions/v1beta1) and what's to be deployed (networking.k8s.io/v1). I'd expect the same compatibility check/measures at apply time (not only at fetch/retrieval time).

Does anyone have any advice on how to get around this? We know that we could write a more advanced cluster applier process that circumvents this corner cases in an if-then-else matter, but I would expect the kubectl client to handle those things, or am I overlooking a certain kubectl feature here?

Best regards,
Bart

**Comment by boeboe** [comment]
@kubernetes/sig-network-bugs

**Comment by liggitt** [comment]
> It appears however that a retrieval of NetworkPolicies deployed this way, still use the extensions/v1beta1 apiVersion. I suppose this is due to backwards compatibility concerns, which I can perfectly understand.

Without qualifying the resource, the extensions API group takes precedence. This will fetch the policies from the `networking.k8s.io` API group:

```
kubectl get networkpolicies.networking.k8s.io
```

Or even more specifically, the `v1` version of the `networking.k8s.io` API group:
```
kubectl get networkpolicies.v1.networking.k8s.io
```

**Comment by boeboe** [comment]
@liggitt can you please re-open this issue, since one cannot specify a fully-qualifying resource when applying through a yaml file.

    # cat networkpolicy.yaml
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: test-policy
    spec:
      podSelector:
        matchLabels:
          name: whatever
      ingress:
        - ports:
            - protocol: TCP
              port: 9090
    # k apply -f networkpolicy.yaml
    networkpolicy "test-policy" created
    # k get networkpolicy test-policy -o yaml
    apiVersion: extensions/v1beta1
    kind: NetworkPolicy
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"test-policy","namespace":"es4-acc-mon-prometheus"},"spec":{"ingress":[{"ports":[{"port":9090,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"name":"whatever"}}}}
      creationTimestamp: 2017-10-17T10:40:37Z
      generation: 1
      name: test-policy
      namespace: es4-acc-mon-prometheus
      resourceVersion: "54940382"
      selfLink: /apis/extensions/v1beta1/namespaces/es4-acc-mon-prometheus/networkpolicies/test-policy
      uid: 9cb5d845-b327-11e7-85ad-005056830d0a
    spec:
      ingress:
      - ports:
        - port: 9090
          protocol: TCP
      podSelector:
        matchLabels:
          name: whatever
    # k apply -f networkpolicy.yaml
    The NetworkPolicy "test-policy" is invalid: spec: Forbidden: updates to networkpolicy spec are forbidden.
    # k delete networkpolicy test-policy
    networkpolicy "test-policy" deleted

    # cat networkpolicy-fullname.yaml
    apiVersion: networkpolicies.v1.networking.k8s.io
    kind: NetworkPolicy
    metadata:
      name: test-policy
    spec:
      podSelector:
        matchLabels:
          name: whatever
      ingress:
        - ports:
            - protocol: TCP
              port: 9090
    # k apply -f networkpolicy-fullname.yaml
    error: unable to recognize "networkpolicy-fullname.yaml": no matches for /, Kind=NetworkPolicy

**Comment by liggitt** [comment]
> can you please re-open this issue, since one cannot specify a fully-qualifying resource when applying through a yaml file 

Resources in a yaml file are always fully qualified (they include the full api group and version)

That syntax for fully specifying a resource, api group, and api version is specific to `kubectl`

Your subsequent `get` is the unqualified bit, so the client defaults to the first API group and version containing that resource (extensions/v1beta1) and the server converts the saved object to that version and returns it to you

the following get would show it in the expected version
```
k get networkpolicies.v1.networking.k8s.io test-policy -o yaml
```

**Comment by liggitt** [comment]
The apply issue is likely related to defaulting or validation in the v1 group alone. 

The returned extensions/v1beta1 content for an unqualified get is unrelated

**Comment by cmluciano** [comment]
May be related https://github.com/kubernetes/kubernetes/pull/51955

**Comment by caseydavenport** [comment]
> The NetworkPolicy "test-policy" is invalid: spec: Forbidden: updates to networkpolicy spec are forbidden.

This is expected if running on a k8s < v1.8 cluster, since updates to NP were only introduced in v1.8. If you try to update on a v1.8 cluster is should succeed. 

> error: unable to recognize "networkpolicy-fullname.yaml": no matches for /, Kind=NetworkPolicy              

I think you've got the wrong apiVersion in your manifest -  `networkpolicies.v1.networking.k8s.io` should be `networking.k8s.io/v1`. The `networkpolicies.v1.networking.k8s.io` bit is just for the kubectl get command.

**Comment by boeboe** [comment]
@caseydavenport 

apply on network policy was working on k8s < 1.7, that is, if the policy applied was exactly the same as the one in the cluster (hence your remark indeed that updates are only supported from 1.8 onwards). My point is that on 1.7 an apply (with a no-update operation, as in yaml == cluster state) does not work since apiVersion issue legacy vs new.

**Comment by caseydavenport** [comment]
@boeboe oh yes, I see what you mean.  Thanks for clarifying.

**Comment by liggitt** [comment]
the objects as seen internally by the validation code are:
```
(networking.NetworkPolicySpec) {                                  (networking.NetworkPolicySpec) {
 PodSelector: (v1.LabelSelector) {                                 PodSelector: (v1.LabelSelector) {
  MatchLabels: (map[string]string) (len=1) {                        MatchLabels: (map[string]string) (len=1) {
   (string) (len=4) "name": (string) (len=8) "whatever"              (string) (len=4) "name": (string) (len=8) "whatever"
  },                                                                },
  MatchExpressions: ([]v1.LabelSelectorRequirement) <nil>           MatchExpressions: ([]v1.LabelSelectorRequirement) <nil>
 },                                                                },
 Ingress: ([]networking.NetworkPolicyIngressRule) (len=1 cap=1) {  Ingress: ([]networking.NetworkPolicyIngressRule) (len=1 cap=1) {
  (networking.NetworkPolicyIngressRule) {                           (networking.NetworkPolicyIngressRule) {
   Ports: ([]networking.NetworkPolicyPort) (len=1 cap=1) {           Ports: ([]networking.NetworkPolicyPort) (len=1 cap=1) {
    (networking.NetworkPolicyPort) {                                  (networking.NetworkPolicyPort) {
     Protocol: (*api.Protocol)(0xc427e1d4f0)((len=3) "TCP"),           Protocol: (*api.Protocol)(0xc427e1cd80)((len=3) "TCP"),
     Port: (*intstr.IntOrString)(0xc4219a3780)({                       Port: (*intstr.IntOrString)(0xc4219a30e0)({
      Type: (intstr.Type) 0,                                            Type: (intstr.Type) 0,
      IntVal: (int32) 9090,                                             IntVal: (int32) 9090,
      StrVal: (string) ""                                               StrVal: (string) ""
     })                                                                })
    }                                                                 }
   },                                                                },
   From: ([]networking.NetworkPolicyPeer) <nil>                      From: ([]networking.NetworkPolicyPeer) {
  }                                                                  }
 }                                                                  }
}                                                                  }
                                                                  }
```

note the ingress rule `From` field is nil on the left and an empty (but non-nil) slice on the right

this is the troublesome line:

https://github.com/kubernetes/kubernetes/blob/0a69594976467a56597ad805585b1947d8b4cec0/pkg/apis/extensions/v1beta1/conversion.go#L337

which initializes the From field to an empty slice when converting

**Comment by cmluciano** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/54109
