### ISSUE TITLE
Add "WhyPending" annotation to unschedulable pods

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#53908]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

Scheduler should attach an annotation with "WhyPending" key and a JSON formatted value to unschedulable pods. This annotation will help users and possibly external tools to know why the pod was unschedulable. Scheduler [generates such a message](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/core/generic_scheduler.go#L61) already, but it places it as a string in its logs. We should build a JOSN and annotate the pod as well.

The JSON should be something like this:

"TotalNodesEvaluated": 10
"NodeUnderMemoryPressure": 5
"NodeOutOfDisk": 3
"NodeNotReady": 1
"PodAntiAffinityRulesNotMatch": 1

/kind feature
/sig scheduling

**Comment by wackxu** [comment]
I would help fix it.

**Comment by wackxu** [comment]
If we really need this? The reason why pod can not schedule has been recorded to the pod status. We can see https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L180

**Comment by bsalamat** [comment]
@wackxu That's a good point, but the error message that is currently put in the pod status is raw. I think we can use the field and don't need to put an annotation, but we should refine the message. Here are my suggestions to make it more usable by scripts, etc:
1. Make the error message a JSON object.
2. The JSON object has a "type", which is FitError in most of the cases, but can be GenericError for other errors (more types can be added in the future).
3. The JSON object has a "message" which give details about the number of nodes evaluated, and the predicates that failed on nodes.

Example:
{
    "type": "FitError",
    "message": {
        "TotalNodesEvaluated": 10
        "NodeUnderMemoryPressure": 5
        "NodeOutOfDisk": 3
        "NodeNotReady": 1
        "PodAntiAffinityRulesNotMatch": 1
    }
}

**Comment by tengqm** [comment]
@bsalamat I like the JSON object idea. If we are going down this direction, maybe we want to ensure that the semantics of the `type` and `message` field are well defined. For `type`, a machine readable string would be fine. For `message`, I am not quite sure if an opaque object is generic enough. Thoughts?

**Comment by bsalamat** [comment]
I [asked the question](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/kubernetes-sig-architecture/ChUdPeemvWg) of whether we can use the pod condition or status message to put a JSON formatted message from sig-architecture and the answer is no. We are also told not to use annotations for this purpose. Looks like the recommended way to add a new field to PodStatus and put the JSON formatted message there.

**Comment by bgrant0607** [comment]
Comments from the email thread:

The scheduler can observe symptoms, but can't actually determine the underlying cause or the remedy, such as:

* Is there an unexpected taint on the nodes?
* Is there a bogus constraint on the pod?
* Would the pod fit if the resource request were reduced?
* Should the resource requests of other pods be reduced to more accurately reflect their usage?
* Does Node Allocatable need to be changed?
* Would the pod fit if another node of a particular flavor/size were added?
* Why didn't the node/cluster autoscaler add such a node?
* Why didn't the descheduler defragment the cluster?
* Why can't the pod preempt the other pods? Would it be able to schedule with a different priority?
* Is there a bogus PodDisruptionBudget, or did a disruption occur that legitimately blocks preemptions?

And that doesn't really even get into right-sizing, quota, QoS, horizontal pod autoscaling, and other resource-management issues.

In practice, a combination of visualization and simulation is needed to help users reason adequately about binpacking/scheduling.

In the API, we should focus on the most blatant/unambiguous, common mistakes/conditions, such as constraints preventing scheduling on all nodes, or resource exhaustion.

Consider how to present this information to users in a UI or CLI.  Can we extract user-meaningful advice from the information?

Additionally, we should think about whether future optimizations will change the information we can extract from the normal scheduling process (e.g. shortcutting predicate functions, only evaluating a subset of nodes in large clusters, etc.) and what impact that will have on the data we expose here and the tools that consume it, and whether it meets API stability expectations.

The size should be bounded.  For a 1000-node cluster, I wouldn't want 1000 different facts. OTOH, in a sufficiently large cluster, the most common reasons for not fitting may not necessarily be relevant. One might think that the number of facts would be bounded by the number of different types of scheduling constraints, but that's only true if the properties of failing constraints, such as labels, taints, conditions, and resources are not identified.
