### ISSUE TITLE
`kubefed join` do not clear garbage data if join failed

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#53928]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

 /kind bug

> /kind feature

**What happened**:

When I call `kubefed join`, it failed due to some invalid configuration, and then after update the configuration, call `kubefed join` again, it reports that there is an sa already in use and cannot add the cluster.

**What you expected to happen**:

We should clear the garbage sa, clusterrole, clusterrolebindings etc if `kubefed init` failed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig multicluster

**Comment by gyliu513** [comment]
Sorry I donot have the clear CLI as steps here, this was encountered in a customer site and I cannot get the data back, but this can be easily reproduced.

/cc @kubernetes/federation-maintainers

**Comment by gyliu513** [comment]
I was using Kubernetes 1.7.3

**Comment by clenimar** [comment]
this is indeed very annoying. I'll tackle this one.

**Comment by gyliu513** [comment]
Thanks @clenimar please go ahead with the fix even the assign does not work for now.

**Comment by irfanurrehman** [comment]
This issue was labelled for sig/multicluster and is thus moved over to kubernetes/federation#216.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
