### ISSUE TITLE
glusterfs create pvc failed

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#53939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

If the PVC is longer than 45 chars, then glusterfs will always failed to create PVC.

The reason is that glusterfs need to create an `endpointname` in form of `glusterfs-dynamic-<claimname>` and the length limit is 63, so the length limit for `claimname` is 45.

But I think that this is not reasonable, as we already have some hash methods to make sure the length of some endpoints do not exceed 63 chars, but for here, as we are adding `glusterfs-dynamic-` as prefix, so there should be some logic to hash the endpoint name again to make sure it does not exceeds 63 chars.

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L771-L775

```
 Name:       default-mq-stocktrader-m-default-mq-stocktrader-m-0
Namespace:  default
StorageClass:   standard
Status:     Pending
Volume:
Labels:     QM_IDENTIFIER=default-mq-stocktrader
        app=default-mq-stocktrader-m
Annotations:    volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Capacity:
Access Modes:
Events:
  FirstSeen LastSeen    Count   From                SubObjectPath   Type        Reason          Message
  --------- --------    -----   ----                -------------   --------    ------          -------
  1h        16m     218 persistentvolume-controller         Warning     ProvisioningFailed  Failed to provision volume with StorageClass "standard": glusterfs: create volume err: error creating volume Error calling v.allocBricksInCluster: database is in read-only mode
  16m       15m     3   persistentvolume-controller         Warning     ProvisioningFailed  Failed to provision volume with StorageClass "standard": glusterfs: create volume err: error creating volume Post http://9.37.142.219:30548/volumes: dial tcp 9.37.142.219:30548: getsockopt: connection refused
  15m       4s      63  persistentvolume-controller         Warning     ProvisioningFailed  Failed to provision volume with StorageClass "standard": glusterfs: create volume err: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-default-mq-stocktrader-m-default-mq-stocktrader-m-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-default-mq-stocktrader-m-default-mq-stocktrader-m-0": must be no more than 63 characters
```

/sig storage

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
// The 'endpointname' is created in form of 'gluster-dynamic-<claimname>'.

@gyliu513 I did not find prefix `dynamicEpSvcPrefix` or related string `glusterfs-dynamic-` are used/refered elsewhere. Seems we can safely remove it? ping @msau42 @saad-ali to confirm.

**Comment by gyliu513** [comment]
Not sure about this, let's wait some comments from @msau42 @humblec @saad-ali
