### ISSUE TITLE
UP-TO-DATE value of federation deployment is always 0

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#53930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

```
[root@ib17b03 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.3-11+f747daa02c9ffb", GitCommit:"f747daa02c9ffba3fabc9f679b5003b3f7fcb2c0", GitTreeState:"clean", BuildDate:"2017-08-28T07:04:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.3-11+f747daa02c9ffb", GitCommit:"f747daa02c9ffba3fabc9f679b5003b3f7fcb2c0", GitTreeState:"clean", BuildDate:"2017-08-28T07:04:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

UP-TO-DATE value of federation deployment is always 0.

This is the federation deployment
```
# kubectl get deployment --all-namespaces
NAMESPACE   NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
db          mariadb     1         1         0            0           1h
dbs         wordpress   1         1         0            0           1h
default     nginx       1         1         0            1           2h
dev         nginx       2         2         0            2           2h
qa          nginx       2         2         0            2           1h

# kubectl get clusters
NAME       STATUS    AGE
cluster1   Ready     3h
cluster2   Ready     2h
```

And there is deployment from child cluster
```
# kubectl get deployment --namespace=qa
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     2         2         2            2           1h

# kubectl get deployment --namespace=dev
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     2         2         2            2           2h
```

The `UP-TO-DATE` value of federation deployment should be consistent with child cluster.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig multicluster

**Comment by irfanurrehman** [comment]
This issue was labelled with sig/multicluster and is thus moved over to kubernetes/federation#217.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
