### ISSUE TITLE
k8s-1.8.1 failed init....

### ISSUE THREAD

**Issue by wxlrainGit** [kubernetes/kubernetes#53941]
when i init the k8s-1.8.1 like this:
kubeadm init --kubernetes-version v1.8.1 --pod-network-cidr=10.244.0.0/16
it will stay at 'This often takes around a minute; or longer if the control plane images have to be pulled.
' ,and not continue.
how can i solve it?

**Comment by liggitt** [comment]
Please report kubeadm-specific issues under https://github.com/kubernetes/kubeadm so they can be triaged and resolved as quickly as possible
