### ISSUE TITLE
Enforce compatability guarantees on apimachinery / apiserver as of 1.8

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#53959]
apiserver & apimachinery still have a warning "NO compatibility guarantees", but as these have now shipped we should stop changing the APIs.

Is this feasible?  If not, can we have detailed change-notes on every change?

One way to see the impact would be to split sample-apiserver out of the main repo, and create an e2e test to make sure that it is updated.  At the moment, the developer experience of working with apiserver & apimachinery is not _kubernetes_.

**Comment by mbohlool** [comment]
cc @lavalamp

**Comment by deads2k** [comment]
I don't think that these repos are ready for a meaningful API compatibility statement between releases (honestly, every release of client-go is a major version).  We know more core changes are coming as we look at admission webhooks this release.

A change log based on a subset of PRs from kubernetes could be useful.

**Comment by lavalamp** [comment]
I agree we need to think about versioning these. Practically speaking, I don't think we're ready to make a lot of promises yet. But a changelog and keeping sample apiserver up to date seem like reasonable things we can do.

**Comment by nikhita** [comment]
> A change log based on a subset of PRs from kubernetes could be useful.

/remove-lifecycle rotten
/kind feature

**Comment by nikhita** [comment]
> A change log based on a subset of PRs from kubernetes could be useful.

Fwiw, a change log for client-go, api, apimachinery exists in https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md. We have been updating it for every Kubernetes release.

Maybe we should include a change log for all api-machinery related staging repos.

/cc @sttts @caesarxuchao 
/remove-lifecycle stale

**Comment by nikhita** [comment]
Closing this since we have changelogs for apimachinery, api and client-go. If changelogs need to be added for _all_ staging repos, it deserves a new issue.

/close
