### ISSUE TITLE
failed to get cgroup stats w/ Docker 17.09.0-ce

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#53960]
/kind bug

**What happened**:

Kubelet v1.8.1 report a lot of error about Docker cgroup stats and system container stats. 

```
summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"

summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
```

**What you expected to happen**:

Not any error ?

**How to reproduce it (as minimally and precisely as possible)**:

Install Kubelet v1.8.1 and Docker 17.09.0-ce on Debian.

**Anything else we need to know?**:

```
root@alabama:~# ls -alh /sys/fs/cgroup/systemd/system.slice/docker.service
total 0
drwxr-xr-x  2 root root 0 Oct 16 15:52 .
drwxr-xr-x 59 root root 0 Oct 16 15:52 ..
-rw-r--r--  1 root root 0 Oct 16 15:56 cgroup.clone_children
-rw-r--r--  1 root root 0 Oct 16 15:56 cgroup.procs
-rw-r--r--  1 root root 0 Oct 16 15:56 notify_on_release
-rw-r--r--  1 root root 0 Oct 16 15:56 tasks
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1
- Cloud provider or hardware configuration**:  Premise Debian 9.1 VMs
- Kernel (e.g. `uname -a`): 4.9.0-3-amd64
- Install tools: Calico Node + CNI

**Comment by dixudx** [comment]
@valentin2105  This seems to be related to `cadvisor`, not a kubernetes issue.

**Comment by dims** [comment]
@valentin2105 @dixudx : did you see the workaround in https://stackoverflow.com/questions/46726216/kubelet-fails-to-get-cgroup-stats-for-docker-and-kubelet-services

**Comment by dchen1107** [comment]
@valentin2105 in k8s 1.8 release, we haven't done the validation for Docker 17.09.0-ce yet.

**Comment by valentin2105** [comment]
@dims With the workaround, I don't get any error any more. 

Thanks !

**Comment by dminca** [comment]
The workaround with kubelet arguments worked for me as well; thanks! 👍 running Kubernetes v1.13.2
