### ISSUE TITLE
GCE cloud provider only list the first 500 results of a resource

### ISSUE THREAD

**Issue by frodenas** [kubernetes/kubernetes#53968]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

GCP SDK `List` function returns the first 500 results of the resource, and if there are more results, a `nextPageToken` is also returned that can be used to get the next page of results in subsequent list requests. Most of the GCE cloud provider `List` calls don't use the `nextPageToken`, and therefore, they only return the first 500 results. They can be identified by this comment: `// TODO: use PageToken to list all not just the first 500`.

**What you expected to happen**:

`List` calls must use the `Pages` function that will go through all pages and therefore will return all results.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.8.1`
- Cloud provider or hardware configuration**: `gce`
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`):n/a
- Install tools: n/a
- Others: n/a

**Comment by nicksardo** [comment]
This has been addressed.

/close
