### ISSUE TITLE
Kubernetes fails to start in openstack [Certificate Issue ]

### ISSUE THREAD

**Issue by srinathmatti** [kubernetes/kubernetes#53983]
**This is a  BUG REPORT **:

When we are trying to create kubernetes cluster using openstack heat , it creates cluster stack[all the VM's and Network is created.] but master fails with services. Below are the list of Error that I see. I have used 1.8. , 1.7, 1.6 all have the same issue. We are following the below documentation
https://kubernetes.io/docs/getting-started-guides/openstack-heat/

Resources that are in wait state are 
master_wait_handle 
master_wait_condition

[centos@centostest7 ~]$ swift list intertrust.com-kubernetes
kubernetes-salt.tar.gz
kubernetes-server.tar.gz

**What happened**:
[  661.534633] cloud-init[4994]: [ERROR   ] Rendering exception occurred: Jinja variable 'salt.pillar object' has no attribute 'node_labels'
[  661.540079] cloud-init[4994]: [ERROR   ] Unable to manage file: Jinja variable 'salt.pillar object' has no attribute 'node_labels'
[  661.540200] cloud-init[4994]: [ERROR   ] Source file salt://kubelet/bootstrap-kubeconfig not found
[  661.540419] cloud-init[4994]: [ERROR   ] Source file salt://kubelet/ca.crt not found

[  664.154129] cloud-init[4994]: ID: fix-service-kubelet
[  664.154759] cloud-init[4994]: Function: cmd.wait
[  664.155370] cloud-init[4994]: Name: /opt/kubernetes/helpers/services bounce kubelet
[  664.156240] cloud-init[4994]: Result: False
[  664.156790] cloud-init[4994]: Comment: One or more requisite failed: kubelet./var/lib/kubelet/ca.crt, kubelet./etc/sysconfig/kubelet, kubelet./var/lib/kubelet/bootstrap-kubeconfig
[  664.158416] cloud-init[4994]: Changes:
[  664.158933] cloud-init[4994]: Summary for local
[  664.159539] cloud-init[4994]: -------------
[  664.160108] cloud-init[4994]: Succeeded: 64 (changed=11)
[  664.160765] cloud-init[4994]: Failed:     8
[  664.161369] cloud-init[4994]: -------------

**What you expected to happen**:
We expect to have the certificate and get the master node up with services.
 
**How to reproduce it (as minimally and precisely as possible)**:

export KUBERNETES_PROVIDER=openstack-heat
export STACK_NAME=KubernetesStack
export NUMBER_OF_MINIONS=3
export MAX_NUMBER_OF_MINIONS=3
export EXTERNAL_NETWORK=ext01
export MASTER_FLAVOR=ECS.C1.2-4
export MINION_FLAVOR=ECS.C1.2-4
export DNS_SERVER=8.8.8.8
export SWIFT_SERVER_URL=
export ENABLE_PROXY=false
KUBERNETES_KEYPAIR_NAME=/home/centos/kubernetes_keypair
export ST_AUTH_VERSION=1.0
export ST_AUTH=
export ST_USER=intertrust:swift
export ST_KEY=

we have edited the below files only for env variables as per our requirements 
-rw-r-----. 1 centos centos 2658 Oct 16 05:32 config-default.sh
-rw-r-----. 1 centos centos 1141 Oct 16 05:32 openrc-default.sh
-rw-r-----. 1 centos centos 1363 Oct 16 05:33 openrc-swift.sh
-rw-r-----. 1 centos centos 8981 Oct 16 05:37 util.sh

**Environment**:

- Kubernetes version
kubectl.sh  version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 213.95.154.95 was refused - did you specify the right host or port?
- Cloud provider or hardware configuration**: OpenStack 
- OS (e.g. from /etc/os-release):CentOS
- Kernel (e.g. `uname -a`): Linux centostest7.novalocal 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:

[log1.log](https://github.com/kubernetes/kubernetes/files/1387388/log1.log)
[second_try_log1.log](https://github.com/kubernetes/kubernetes/files/1387393/second_try_log1.log)

/sig Certificate
@kubernetes/sig-contributor-experience-bugs

**Comment by srinathmatti** [comment]
@pipejakob this is the similar issue as https://github.com/kubernetes/release/pull/386

**Comment by srinathmatti** [comment]
issue/bug

**Comment by dims** [comment]
Heat support is now deprecated - https://github.com/kubernetes/website/pull/5670

/close
