### ISSUE TITLE
apiserver aggregation: reason for separate CA

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#53990]
It isn't very clear from the docs why a second CA is needed:

> Kubernetes and the kube-apiserver have multiple CAs, so make sure that the proxy is signed by the aggregation layer CA and not by something else, like the master CA.

This is unintuitive.  I presume it would have been OK to have had a root CA with two children, instead of two root CAs, except for legacy reasons?  But what is the issue with reusing the same CA, particularly now that we hand out certs to all comers via the CSR API?

Can we instead chain the aggregation "CA" from the root CA?

**Comment by mbohlool** [comment]
cc @cheftako

**Comment by deads2k** [comment]
This probably fits better for @kubernetes/sig-auth-misc .  Having separate certificates ensures that a client acting as a front proxy (request header) never accidentally gets terminated as a direct client for the request being made.  It also makes sure there are discount identities for front proxies and direct API clients.  If they use the same CA, there is a risk of using one as the other that doesn't have to be there.

**Comment by cheftako** [comment]
I agree with @deads2k response. It is worth remembering that there are actually two CAs involved in the aggregation layer. There is the CA which signs the extension API servers, server certificate. This is used by the Kube API Server that the extension API server is who it thinks. This CA is set in the CABundle field in the APIService registration. It is up to the admin who registers the extension API server what CA to use here. However if the CA is compromised then you can spoof that extension API server. The other CA is the request header CA. This is used by the extension API server to authenticate that a request came from the Kube API Server/Aggregator. The CA used is controlled by the flags used to start the Kube API Server. In most scenarios we do not prevent you from reusing root CA. However as you allude, the CSR API will sign with the root CA. That means that there is a fairly simple social engineering attack an aggregator cert which is signed by that root CA. Once that happens it is fairly easy to either inject or read any data from that extension API Server. So we suggest using something other than the root CA.
