### ISSUE TITLE
DNSPolicy: Add "Host" as an alias for "Default" (proposal for a PR in progress)

### ISSUE THREAD

**Issue by evanj** [kubernetes/kubernetes#53992]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I am planning on attempting to add `dnsPolicy: Host` as an alias for `dnsPolicy: Default`, [as discussed on kubernetes-users](https://groups.google.com/d/msg/kubernetes-users/7JBq6jhMZHc/YfnlY5xtAQAJ), where @thockin said he would take PRs to do this. The reason is that it is slightly confusing that `dnsPolicy: Default` is not the default. I'm not entirely sure how to do this, but [the contributing guide suggests filing an issue](https://github.com/kubernetes/community#your-first-contribution). I think I need to make the following changes, let me know if this plan seems reasonable or if there is something I am missing:

1. Add a constant `DNSPolicy DNSHost = "Host"` to `pkg/api/types.go`: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2012 . It appears to me that this is enough to make this work, since `Kubelet.GetClusterDNS` only checks for `DNSClusterFirstWithHostNet` and `DNSClusterFirst`: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1412

2. Add the a test case to `TestGenerateRunContainerOptions_DNSConfigurationParams` https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods_test.go#L608 which ensures the pod that specifies `DNSHost` gets the same config as the one that specifies `DNSDefault`

3. Add `DNSHost` to the fuzzer list: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/fuzzer/fuzzer.go#L249

4. Add `DNSHost` to `validateDNSPolicy`: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2231

*Questions*:
* When would it be "safe" to switch internal uses of `DNSDefault` to `DNSHost`? The backwards incompatibility I can think of is if printing the value of a struct suddenly returns the string `Host`, older tools may not be able to cope. Thus, I think it is "safest" if Kubernetes itself continues using `DNSDefault` for a while (until the next major release?)
* How does the swagger API doc help string get generated? It seems to be the same one in a bunch of places, and I see tools for generating it, but I can't tell which is the "canonical" source.

**Comment by evanj** [comment]
@kubernetes/sig-network

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests
