### ISSUE TITLE
Tag client-go 5.0.x

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#54003]
We have pushed the 1.8.1 based client-go https://github.com/kubernetes/kubernetes/issues/53808. What do we need to tag 5.0.0 or 5.0.1?

TODO:
- [ ] update README.md
- [ ] create changelogs

**Comment by caesarxuchao** [comment]
We are going to do the tagging and update the release note and readme.

**Comment by tamalsaha** [comment]
@caesarxuchao, when can we expect this?

**Comment by caesarxuchao** [comment]
We are putting together the changelog at https://github.com/kubernetes/client-go/pull/313, will tag v5.0.0 after it's merged.

**Comment by caesarxuchao** [comment]
5.0.0 is created: https://github.com/kubernetes/client-go/releases/tag/v5.0.0

**Comment by sttts** [comment]
Closing.
