### ISSUE TITLE
Cannot view logs with -l/--selector for multi-container Pods using "kubectl logs"

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#54000]
/kind bug
/sig cli

**What happened**: I have a deployment called `wordpress` (labels: `app=wordpress`) that has two containers named `web`, `cloudsql-proxy`. It is running with `replicas:1`.

I tried to view the logs:

```
$ kubectl logs -l app=wordpress
Error from server (BadRequest): a container name must be specified for pod wordpress-1615343444-d95v3, choose one of: [web cloudsql-proxy]
```

So I clarified, by appending container name `web` to the command:

```
$ kubectl logs -l app=wordpress web
error: only a selector (-l) or a POD name is allowed
See 'kubectl logs -h' for help and examples.
```

It says only a "selector" OR "pod name" is allowed.
In this case I'm not specifying pod name, just the selector.
But it still fails with this error.

**What you expected to happen**:
The command to match the single replica pod and show logs from the container.

**How to reproduce it (as minimally and precisely as possible)**: 
Deploy two containers via a Deployment (replicas:1) and try to view its logs via -l/--label

**Environment**:
- Kubernetes version (use `kubectl version`): client 1.8, server v1.6.10-gke.1
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Google cloud-optimized OS (COS)

**Comment by cblecker** [comment]
@ahmetb You need to use the container flag:
```
  -c, --container='': Print the logs of this container
```
to specify which container you want to use. This information is available via `kubectl logs --help`.

Try the following:
```
kubectl logs -l app=wordpress -c web
```

/remove-kind bug
/kind support

**Comment by ahmetb** [comment]
my bad.

**Comment by cblecker** [comment]
no problem :)
