### ISSUE TITLE
kubectl run deployments are created without any change-cause annotation by default

### ISSUE THREAD

**Issue by heckj** [kubernetes/kubernetes#54014]
**Is this a BUG REPORT or FEATURE REQUEST?:**
/kind bug
/area kubectl

**What happened**:
I created a deployment using the kubectl run command, and then updated the image with the kubectl set command, thinking I was matching the documentation at https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
I expected that the set command would be reflected in the `kubectl rollout history` command, but instead the change-cause annotation was empty.

**What you expected to happen**:
I _think_ the correct thing would be for the kubectl run command to create an initial change-cause annotation when it is creating the deployment in the first place. I verified that if the annotation exists, the kubectl set command would indeed update it, but if the annotation doesn't exist, the set command won't update it.

**How to reproduce it (as minimally and precisely as possible)**:

- `kubectl run flask --image=quay.io/kubernetes-for-developers/flask:0.1.0`
- `kubectl set image deployment/flask flask=quay.io/kubernetes-for-developers/flask:0.1.1`
- `kubectl rollout history deploy flask`
```
deployments "flask"
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
```

**Anything else we need to know?**:

If an annotation is added manually after the run command creates the deployment, the kubectl set command will update the annotation:

- `kubectl delete deployment flask`
- `kubectl run flask --image=quay.io/kubernetes-for-developers/flask:latest`
- `kubectl annotate deployment/flask kubernetes.io/change-cause='initial deployment'`
- `kubectl set image deployment/flask flask=quay.io/kubernetes-for-developers/flask:0.1.1`

Then:
- `kubectl rollout history deployment/flask`
```
deployments "flask"
REVISION  CHANGE-CAUSE
1         initial deployment
2         kubectl set image deployment/flask flask=quay.io/kubernetes-for-developers/flask:0.1.1
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```json
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:45:05Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration**: minikube v0.22.3
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a

**Comment by heckj** [comment]
I _think_ cli is the appropriate sig. Please correct me if I'm wrong...
/sig cli

**Comment by wackxu** [comment]
Look at the code

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/set/set_image.go#L263

@heckj We should explicitly set flag "record" true or input resource info contains change-cause annotation then it will record the CHANGE-CAUSE, this is same with the command "kubectl run"

**Comment by heckj** [comment]
thanks @wackxu - I don't know the specifics of that code to understand what I'm reading. Am I correct in reading that it would always record the change if I added the `--record=true` option onto the `kubectl set` command, i.e. use

 - `kubectl set image deployment/flask flask=quay.io/kubernetes-for-developers/flask:0.1.1 --record=true`

and even without the annotation, a change-cause annotation will be created?

I'm a little unclear on why we update it if the annotation already exists, but don't otherwise add it by default.

**Comment by wackxu** [comment]
> Am I correct in reading that it would always record the change if I added the --record=true option onto the kubectl set command, i.e. use
 kubectl set image deployment/flask flask=quay.io/kubernetes-for-developers/flask:0.1.1 --record=true
 and even without the annotation, a change-cause annotation will be created

 @heckj Yes, you are right. If we  explicitly set flag "record" true, It will always record the change 

> I'm a little unclear on why we update it if the annotation already exists, but don't otherwise add it by default

I think for every update, the  REVISION and  `generation`  will be update meanwhile the annotation will be updated.The older annotation has been saved and we only need modify the annotation to the new change-cause.

**Comment by ShualLiu** [comment]
I think it's better to add some annotation in command instruction. For example, 
in "kubectl run -h ", we could remind users to use --record=true to record history.

**Comment by wackxu** [comment]
There already have annotation in  `kubectl run -h `
```
--record=false; Record current kubectl command in the resource annotation. If set to false, do not record the command. If set to true, record the command. If not set, default to updating the existing annotation value only if one already exists.
```

**Comment by ShualLiu** [comment]
thanks

**Comment by ShualLiu** [comment]
@wackxu thanks

**Comment by liggitt** [comment]
If recording is desired, users can request it with --record, as described in help.
