### ISSUE TITLE
Rerunning kubectl apply on the same file should not send an empty patch request

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#54010]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Running `kubectl apply -f manifest.yaml` multiple times (without changing the manifest) will cause kubectl to send empty patch requests. This is particularly problematic because the addon manager runs apply on the addon manifest directory regularly, and the result spams the audit log with empty requests.

**What you expected to happen**:
Kubectl should not send empty patch requests (unless an overriding flag is specified, e.g. `--force`).

**How to reproduce it (as minimally and precisely as possible)**:

```shell
$ cat > pod.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  name:   pause
spec:
  containers:
    - name:    pause
      image: gcr.io/google_containers/pause
EOF
# create the pod
$ kubectl apply -f ~/tmp/pod.yaml
# Reapplying the file sends a patch
$ kubectl apply -v=9 -f ~/tmp/pod.yaml |& grep PATCH
I1016 14:04:51.965444  119266 round_trippers.go:386] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubectl/v1.7.5 (linux/amd64) kubernetes/17d7182" https://104.155.171.61/api/v1/namespaces/default/pods/pause
I1016 14:04:52.006809  119266 round_trippers.go:405] PATCH https://104.155.171.61/api/v1/namespaces/default/pods/pause 200 OK in 41 milliseconds
# Look at the audit log for the patch content.
```

/cc @crassirostris

**Comment by hzxuzhonghu** [comment]
I am working on it.

**Comment by crassirostris** [comment]
Still not fixed, in version 1.8.2:

```
$ kubectl apply -v9999 -f ...  |& grep curl
I1108 21:35:06.440337   11329 round_trippers.go:417] curl -k -v -XGET  ...
I1108 21:35:07.203637   11329 round_trippers.go:417] curl -k -v -XGET  ...
I1108 21:35:07.342135   11329 round_trippers.go:417] curl -k -v -XPATCH ...
```

**Comment by liggitt** [comment]
fix is in master in https://github.com/kubernetes/kubernetes/pull/54046

**Comment by crassirostris** [comment]
Oh, sorry, I though it was cherry-picked already

**Comment by dixudx** [comment]
#55364 cherry-pick to release-1.8
