### ISSUE TITLE
etcd error in cluster downgrade: membership: cluster cannot be downgraded (current version: 3.0.17 is lower than determined cluster version: 3.1).

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#54027]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
From couple upgrade/downgrade testsuites:
- https://k8s-testgrid.appspot.com/etcd-upgrades#gce-latest
- https://k8s-testgrid.appspot.com/sig-network#gci-gce-latest-downgrade-kube-proxy-ds

After upgrade/downgrade, master instance never be able to come up again. From the etcd logs, we found below error being constantly emitted:
```
2017-10-16 21:07:10.954395 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-10-16 21:07:10.956442 I | membership: added member a97d80ddc090126a [https://bootstrap-e2e-master:2380] to cluster 91078bdbe2ed539b
2017-10-16 21:07:10.956606 N | membership: set the initial cluster version to 3.0
2017-10-16 21:07:10.956669 I | api: enabled capabilities for version 3.0
2017-10-16 21:07:10.975261 N | membership: updated the cluster version from 3.0 to 3.1
2017-10-16 21:07:10.975303 C | membership: cluster cannot be downgraded (current version: 3.0.17 is lower than determined cluster version: 3.1).
```

Examples:
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-upgrade-etcd/1995/artifacts/bootstrap-e2e-master/etcd.log
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-latest-downgrade-kube-proxy-ds/1698/artifacts/bootstrap-e2e-master/etcd.log

Failures seems to start occurring after https://github.com/kubernetes/kubernetes/pull/49393 went in.

**What you expected to happen**:

Etcd and apiserver should come up properly.

**Anything else we need to know?**:
@hongchaodeng  @jpbetz 
cc @jingax10 

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration**: GCE

**Comment by MrHohn** [comment]
@sig-api-machinery-test-failures
/area etcd

**Comment by MrHohn** [comment]
@kubernetes/sig-api-machinery-test-failures

**Comment by jingax10** [comment]
I investigated the issue a bit.

The etcd version for a k8s release is packed in cluster/saltbase/salt/etcd/etcd.manifest, e.g., the one from HEAD.

"env": [
      { "name": "TARGET_STORAGE",
        "value": "{{ pillar.get('storage_backend', 'etcd3') }}"
      },
      { "name": "TARGET_VERSION",
        "value": "{{ pillar.get('etcd_version', '3.1.10') }}"
      },
      { "name": "DATA_DIRECTORY",
        "value": "/var/etcd/data{{ suffix }}"
      }
        ],

On the other hand, etcd (https://github.com/coreos/etcd/blob/master/etcdserver/membership/cluster.go) has the following logic to detect downgrade. In case it happens, it will trigger a fatal error and log.

func mustDetectDowngrade(cv *semver.Version) {
	lv := semver.Must(semver.NewVersion(version.Version))
	// only keep major.minor version for comparison against cluster version
	lv = &semver.Version{Major: lv.Major, Minor: lv.Minor}
	if cv != nil && lv.LessThan(*cv) {
		plog.Fatalf("cluster cannot be downgraded (current version: %s is lower than determined cluster version: %s).", version.Version, version.Cluster(cv.String()))
	}
}

It sounds that it hits a lower version of etcd for the test.

Given this, I found etcd version was bumped up from 3.0.17 to 3.1.10 on 10/02/2017 (https://github.com/kubernetes/kubernetes/commit/39e5a566912b22a9eaeb5462fdc7eb55ea1bb837#diff-0fa055cac191706bf4aff2385d1bc750). However it is not in any tagged k8s release yet.

**Comment by cmluciano** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by xiangpengzhao** [comment]
Also encountered this in #57013.
@jingax10 did you mean that downgrade etcd from 3.1.x to 3.0.x is not allowed?

**Comment by jpbetz** [comment]
@xiangpengzhao Yes, etcd downgrades are not supported, see: https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_1.html#downgrade.

**Comment by MrHohn** [comment]
Thanks all, let's use https://github.com/kubernetes/kubernetes/issues/57013 for tracking. Closing this.
