### ISSUE TITLE
kubelet won't start - /etc/kubernetes/pki/ca.crt: no such file or directory

### ISSUE THREAD

**Issue by cmaxoutis** [kubernetes/kubernetes#54022]
/kind bug

**What happened**:
Performed a clean install on CentOS Linux release 7.4.1708 and started kubelet
`yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet
`
`
systemctl status kubelet
tail -100f /var/log/messages | grep kubelet

kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`

**What you expected to happen**:
kubelet starts successfully

**How to reproduce it (as minimally and precisely as possible)**:
`yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet`

`systemctl status kubelet
tail -100f /var/log/messages | grep kubelet
`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration**: 
`CentOS Linux release 7.4.1708 (Core) on virtualbox `

- OS (e.g. from /etc/os-release):
`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`

- Kernel (e.g. `uname -a`):
`Linux kubemaster 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
`kubelet kubeadm kubectl `
- Others:
docker-1.12.6-55.gitc4618fb.el7.centos.x86_64

**Comment by liggitt** [comment]
You have to initialize the kubelet config before it will start successfully. That is typically done with `kubeadm init` or `kubeadm join`

A clean package install places the kubelet in a crash loop pending valid configuration

**Comment by abdulrahmantkhalifa** [comment]
so how can somone reset the kubelet config concerning 'A clean package install places the kubelet in a crash loop pending valid configuration'

**Comment by artefactop** [comment]
To fix it, in the first join use the option `--discovery-token-unsafe-skip-ca-verification`
