### ISSUE TITLE
1.8.1 gce calico cni issue

### ISSUE THREAD

**Issue by marcwuk** [kubernetes/kubernetes#54037]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kube-up of k8s 1.8.1 on GCE. 
set NETWORK_POLICY_PROVIDER:-calico in config-default.sh
Nodes never reach Ready due to:
Ready                 False   Tue, 17 Oct 2017 06:14:34 +0000         Tue, 17 Oct 2017 06:07:24 +0000         KubeletNotReady                 runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**What you expected to happen**:
Nodes to reach Ready state.
**How to reproduce it (as minimally and precisely as possible)**:
download k8s 1.8.1.
edit kubernetes/cluster/gce/config-default.sh
set NETWORK_POLICY_PROVIDER:-calico 
kubernetes/cluster/kube-up.sh

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.8.1
- Cloud provider or hardware configuration**:
GCE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
> network plugin is not ready: cni config uninitialized

@marcwuk Seems you've not configured CNI. Please check your `kubelet` args whether you've set `--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin` and put `calico` binary and configs there.

**Comment by cmluciano** [comment]
@kubernetes/sig-gcp-misc
