### ISSUE TITLE
Fluentd-gcp-v2.0 prometheus port collides with another kube-proxy port

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#54063]
/kind bug

**What happened**:

On most of our GKE clusters **fluentd-gcp-v2.0** works fine, but our production clusters has most of the pods constantly crash looping due to the following startup error:

```
unexpected error error_class=Errno::EADDRINUSE error=#<Errno::EADDRINUSE: Address already in use - bind(2) for 0.0.0.0:31337>
```

Running `sudo netstat -tulpn | grep 31337` on one of the problematic hosts shows the port to be in use by kube-proxy:

```
tcp6       2      0 :::31337                :::*                    LISTEN      1821/kube-proxy 
```

The deamonset has `hostNetwork: true` but does not specify port 31337 because it's only scraped by the `prometheus-to-sd-exporter` sidecar container and doesn't necessarily need to be exposed on the host I guess.

Is there a reason for fluentd to require `hostNetwork: true`? In case it does is there a way to avoid conflicts by specifying the port in the daemonset so Kubernetes actually knows someone wants to use it?

**What you expected to happen**:

Fluentd to run fine without crash looping.

**How to reproduce it (as minimally and precisely as possible)**:

Run another deamonset with `hostNetwork: true` and listening to port 31337.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:

GKE master version 1.7.6-gke.1, node version 1.7.2

- OS (e.g. from /etc/os-release):

```
BUILD_ID=9460.73.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=e6c7193d61d7affc144ad703b74524ddd574d2ee
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=59
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=59
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

- Kernel (e.g. `uname -a`):

```
Linux gke-production-europ-auto-scaling-pre-204b0978-ldzl 4.4.52+ #1 SMP Thu Jul 13 11:47:20 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by JorritSalverda** [comment]
I did find the service of type `LoadBalancer` that has a `nodePort` equal to that port 31337 used by fluent-gcp. Can you change a node port on the fly and will the GCE network load balancer reconfigure or do I have to delete and recreate the service?

**Comment by crassirostris** [comment]
Fluentd was moved out of the host network
