### ISSUE TITLE
Networking-Granular Checks: Pods e2e  Conformance test Failed

### ISSUE THREAD

**Issue by stewart-yu** [kubernetes/kubernetes#54069]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

When  i run e2e Conformance test, thoes test failed:
[Fail] [k8s.io] Networking [k8s.io] Granular Checks: Pods [It] should function for node-pod communication: http [Conformance] 
[Fail] [k8s.io] Networking [k8s.io] Granular Checks: Pods [It] should function for intra-pod communication: udp [Conformance] 
[Fail] [k8s.io] Networking [k8s.io] Granular Checks: Pods [It] should function for node-pod communication: udp [Conformance] 
[Fail] [k8s.io] Networking [k8s.io] Granular Checks: Pods [It] should function for intra-pod communication: http [Conformance]
[Fail] [k8s.io] KubeletManagedEtcHosts [It] should test kubelet managed /etc/hosts file [Conformance]

Log looks like this: 

[k8s.io] Networking [k8s.io] Granular Checks: Pods 
  should function for intra-pod communication: http [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:38
[BeforeEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:130
STEP: Creating a kubernetes client
Oct 17 12:39:33.626: INFO: >>> kubeConfig: 
STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[It] should function for intra-pod communication: http [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:38
STEP: Performing setup for networking test in namespace e2e-tests-pod-network-test-rgdpv
STEP: creating a selector
STEP: Creating the service pods in kubernetes
Oct 17 12:39:33.657: INFO: Waiting up to 10m0s for all (but 0) nodes to be schedulable
STEP: Creating test pods
Oct 17 12:44:59.722: INFO: Unexpected error occurred: timed out waiting for the condition
[AfterEach] [k8s.io] Networking
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:131
STEP: Collecting events from namespace "e2e-tests-pod-network-test-rgdpv".
STEP: Found 14 events.
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:33.680921129 +0000 UTC - event for netserver-0: {default-scheduler } Scheduled: Successfully assigned netserver-0 to 192.168.0.25
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:33.87038608 +0000 UTC - event for netserver-0: {kubelet 192.168.0.25} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "default-token-8ns9f" 
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:34.895180444 +0000 UTC - event for netserver-0: {kubelet 192.168.0.25} Pulled: Container image "gcr.io/google_containers/netexec:1.7" already present on machine
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:35.394217619 +0000 UTC - event for netserver-0: {kubelet 192.168.0.25} Created: Created container
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:35.691409238 +0000 UTC - event for netserver-0: {kubelet 192.168.0.25} Started: Started container
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:55.695690198 +0000 UTC - event for test-container-pod: {default-scheduler } Scheduled: Successfully assigned test-container-pod to 192.168.0.25
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:55.700202036 +0000 UTC - event for host-test-container-pod: {default-scheduler } Scheduled: Successfully assigned host-test-container-pod to 192.168.0.25
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:55.945159728 +0000 UTC - event for test-container-pod: {kubelet 192.168.0.25} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "default-token-8ns9f" 
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:55.948003674 +0000 UTC - event for host-test-container-pod: {kubelet 192.168.0.25} SuccessfulMountVolume: MountVolume.SetUp succeeded for volume "default-token-8ns9f" 
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:57 +0000 UTC - event for host-test-container-pod: {kubelet 192.168.0.25} FailedSync: Error syncing pod
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:57.094652175 +0000 UTC - event for test-container-pod: {kubelet 192.168.0.25} Pulled: Container image "gcr.io/google_containers/netexec:1.7" already present on machine
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:58 +0000 UTC - event for host-test-container-pod: {kubelet 192.168.0.25} SandboxChanged: Pod sandbox changed, it will be killed and re-created.
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:58.110131519 +0000 UTC - event for test-container-pod: {kubelet 192.168.0.25} Created: Created container
Oct 17 12:44:59.727: INFO: At 2017-10-17 12:39:58.954561944 +0000 UTC - event for test-container-pod: {kubelet 192.168.0.25} Started: Started container
Oct 17 12:44:59.736: INFO: POD                                 NODE          PHASE    GRACE  CONDITIONS
Oct 17 12:44:59.736: INFO: cc-2lkm6                            192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:09:12 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: mysql-37j3m                         192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:11:22 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: ningx-zf0s2                         192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:09:34 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: s-1rfbd                             192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 20:22:52 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 20:23:00 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 20:22:52 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: sadfsafd-klh8f                      192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 19:56:21 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 19:56:40 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 19:56:21 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: sd-sc301                            192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:11:23 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: sdfsdf-8qrks                        192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 21:07:28 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 21:07:30 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 21:07:28 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: wordpress-d4k9h                     192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:10:48 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: host-test-container-pod             192.168.0.25  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:55 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:55 +0000 UTC ContainersNotReady containers with unready status: [hostexec]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:55 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: netserver-0                         192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:33 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:53 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:33 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: test-container-pod                  192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:55 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:59 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:39:55 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: fluentd-elasticsearch-192.168.0.25  192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:53:28 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:54:18 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:53:28 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: heapster-v1.4.0-2395533666-w9w58    192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:09:13 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: kube-dns-v17-dd0md                  192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:09:49 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-13 05:08:59 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: kube-proxy-192.168.0.25             192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:53:28 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:54:28 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-12 17:53:28 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: sonobuoy                            192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:37 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:40 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:37 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: sonobuoy-e2e-job-8749fc93234a4058   192.168.0.25  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:40 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:44 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-17 12:19:40 +0000 UTC  }]
Oct 17 12:44:59.736: INFO: 
Oct 17 12:44:59.741: INFO: 
Logging node info for node 192.168.0.25
Oct 17 12:44:59.744: INFO: Node Info: &Node{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:192.168.0.25,GenerateName:,Namespace:,SelfLink:/api/v1/nodes/192.168.0.25,UID:3df2554a-af76-11e7-851b-fa163e773679,ResourceVersion:627704,Generation:0,CreationTimestamp:2017-10-12 17:53:23.838290588 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{beta.kubernetes.io/arch: amd64,beta.kubernetes.io/os: linux,failure-domain.beta.kubernetes.io/zone: cn-north-1a,kubernetes.io/hostname: 192.168.0.25,name: test-fp-node-2,serverid: 84222bb8-00cc-430f-87e1-33db4abcf87c,},Annotations:map[string]string{node.alpha.kubernetes.io/ttl: 0,volumes.kubernetes.io/controller-managed-attach-detach: true,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:NodeSpec{PodCIDR:,ExternalID:192.168.0.25,ProviderID:,Unschedulable:false,Taints:[],},Status:NodeStatus{Capacity:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{8164458496 0} {<nil>}  BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Allocatable:ResourceList{cpu: {{2 0} {<nil>} 2 DecimalSI},memory: {{8059600896 0} {<nil>}  BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Phase:,Conditions:[{OutOfDisk False 2017-10-17 12:44:55 +0000 UTC 2017-10-12 17:53:23 +0000 UTC KubeletHasSufficientDisk kubelet has sufficient disk space available} {MemoryPressure False 2017-10-17 12:44:55 +0000 UTC 2017-10-12 17:53:23 +0000 UTC KubeletHasSufficientMemory kubelet has sufficient memory available} {DiskPressure False 2017-10-17 12:44:55 +0000 UTC 2017-10-12 17:53:23 +0000 UTC KubeletHasNoDiskPressure kubelet has no disk pressure} {Ready True 2017-10-17 12:44:55 +0000 UTC 2017-10-12 17:53:33 +0000 UTC KubeletReady kubelet is posting ready status}],Addresses:[{InternalIP 192.168.0.25} {Hostname 192.168.0.25}],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:10250,},},NodeInfo:NodeSystemInfo{MachineID:f21bcad2f362498d924ac24efcdd3e2a,SystemUUID:35434C36-C36A-42DF-A92D-0AFF1F3C2D13,BootID:386b1d40-6232-483b-80df-7f7b7f7c2472,KernelVersion:3.10.0-229.42.1.97.x86_64,OSImage:EulerOS V2.0SP1,ContainerRuntimeVersion:docker://1.11.2,KubeletVersion:cce-1.7.3.17+8857de1a267f8f-dirty,KubeProxyVersion:cce-1.7.3.17+8857de1a267f8f-dirty,OperatingSystem:linux,Architecture:amd64,},Images:[{[fluentd:1.11] 617825114} {[gcr.io/heptio-images/kube-conformance:v1.7.3] 504950988} {[mysql:latest] 412300183} {[wordpress:latest] 408332632} {[gcr.io/heptio-images/sonobuoy:latest] 326230178} {[117.78.33.214/dingshujie/apache-php:latest] 244663227} {[ops_agent:node] 200491883} {[gcr.io/google_containers/jessie-dnsutils:e2e] 190122856} {[kube-proxy:cce-1.7.3.17_8857de1a267f8f-dirty] 114793936} {[117.78.33.214/dingshujie/nginx-fp:v1 117.78.33.214/dingshujie/nginx:latest nginx:latest] 108275923} {[gcr.io/google_containers/nginx-slim:0.7] 86838142} {[gcr.io/google_containers/heapster:v1.4.0] 73395475} {[kubedns-amd64:1.5] 50815316} {[gcr.io/google_containers/addon-resizer:1.7] 38983736} {[quay.io/coreos/etcd:v3.2] 35749746} {[gcr.io/google_containers/nettest:1.7] 24051275} {[gcr.io/google_containers/hostexec:1.2] 13185747} {[gcr.io/google_containers/dnsutils:e2e] 8893907} {[gcr.io/google_containers/netexec:1.7] 8016035} {[exechealthz-amd64:1.0] 7115733} {[gcr.io/google_containers/serve_hostname:v1.4] 6222101} {[kube-dnsmasq-amd64:1.3] 5125973} {[gcr.io/google_containers/test-webserver:e2e] 4534272} {[gcr.io/google_containers/porter:4524579c0eb935c056c8e75563b4e1eda31587e0] 4413212} {[gcr.io/google_containers/liveness:e2e] 4387474} {[gcr.io/google_containers/eptest:0.1] 2970692} {[gcr.io/google_containers/mounttest-user:0.5] 1450761} {[gcr.io/google_containers/mounttest:0.8] 1450761} {[gcr.io/google_containers/busybox:1.24] 1113554} {[gcr.io/google_containers/pause-amd64:3.0] 746888} {[pause:2.0] 350164}],VolumesInUse:[],VolumesAttached:[],},}
Oct 17 12:44:59.744: INFO: 
Logging kubelet events for node 192.168.0.25
Oct 17 12:44:59.748: INFO: 
Logging pods the kubelet thinks is on node 192.168.0.25
Oct 17 12:44:59.751: INFO: Unable to retrieve kubelet pods for node 192.168.0.25
STEP: Dumping a list of prepulled images on each node to file /tmp/results/image-puller.txt
Oct 17 12:44:59.755: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "e2e-tests-pod-network-test-rgdpv" for this suite.
Oct 17 12:45:21.855: INFO: namespace: e2e-tests-pod-network-test-rgdpv, resource: bindings, ignored listing per whitelist
Oct 17 12:45:21.903: INFO: namespace e2e-tests-pod-network-test-rgdpv deletion completed in 22.144844571s

• Failure [348.277 seconds]
[k8s.io] Networking
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:619
  [k8s.io] Granular Checks: Pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:619
    should function for intra-pod communication: http [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:38

    Expected error:
        <*errors.errorString | 0xc42025ecb0>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:433

Other  Four test's log also  occure on "timed out waiting for the condition" 

**What you expected to happen**:

Those  test case paas.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"cce-1.7.3.15+b7e2f8894c928e-dirty", GitCommit:"b7e2f8894c928e631a63da37c703141c456f99b7", GitTreeState:"dirty", BuildDate:"2017-09-12T03:46:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"cce-1.7.3.17+8857de1a267f8f-dirty", GitCommit:"8857de1a267f8fa8075caccf446b2327ed76435c", GitTreeState:"dirty", BuildDate:"2017-09-15T02:03:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

`Docker Version`

Client:
 Version:        1.11.2
 UnicornVersion: 1.11.2.5
 API version:    1.23
 Go version:     go1.5.4
 Git commit:     6f3969d
 Built:          Mon Dec  5 13:26:15 2016
 OS/Arch:        linux/amd64

Server:
 Version:        1.11.2
 UnicornVersion: 1.11.2.5
 API version:    1.23
 Go version:     go1.5.4
 Git commit:     6f3969d
 Built:          Mon Dec  5 13:26:15 2016
 OS/Arch:        linux/amd64

**Comment by cmluciano** [comment]
@stewart-yu Are you using https://github.com/kris-nova/kubicorn ? Also this seems to be installing a version of k8s 1.7 with a dirty working tree. Can you comment on if you patched some things locally before creating a release?

**Comment by stewart-yu** [comment]
Just use https://scanner.heptio.com/,  run it in cluster with one node.

**Comment by stewart-yu** [comment]
It seems that  host-test-container-pod created in createTestPods function located in test/e2e/framework/networking_util.go with createContaining status all the same, This pod has attribute HostNetWork=true, if remove it, the pod can running.@cmluciano

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs 

failing test

**Comment by caseydavenport** [comment]
@stewart-yu how did you create your cluster?

**Comment by stewart-yu** [comment]
Sorry, i forgot close it. May be docker version too lower, i have upgrade  docker, it 's OK. @caseydavenport
