### ISSUE TITLE
RBAC policy for watching a single object?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#54079]
Related to https://github.com/kubernetes/kubernetes/issues/43299, what is the RBAC policy to lock down watching to a particular object (in my case, a secret)?

I've tried:
```
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list"]
  resourceNames: ["singleton"]
```

But that gives me "...cannot list secrets..."

It seems to need:

```
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","watch","list"]
```

This is using:

```
listOpts.FieldSelector = fields.OneTermEqualSelector("metadata.name", c.name).String()
```

**Comment by justinsb** [comment]
cc @liggitt

**Comment by liggitt** [comment]
authorization doesn't currently doesn't have the filter attributes on list/watch calls, so those are authorized unscoped to a particular resource name. that applies to all authorizers, not just RBAC

adding support for that is one aspect of https://github.com/kubernetes/kubernetes/issues/40403

**Comment by debianmaster** [comment]
@liggitt   now that custom resources are use extensively , it will be nice to have a built-in solution for filtering custom objects based on k8s native RBAC.    any workarounds that you can suggest?
- Admission controllers [ no get operations supported AFAIK]
- Pass all the objects in get operations and get only objects to which impersonated user has access to?

**Comment by liggitt** [comment]
watch/list support for single resources was added in https://github.com/kubernetes/kubernetes/pull/63469 in v1.11

The list/watch requests must set a fieldSelector of `metadata.name=$name`
