### ISSUE TITLE
Deprecate and Remove GCE specific feature - node dialer talking to the cloud provider

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#54076]
AddSSHKeyToAllInstances is on the CloudProvider interface. However *all* providers except GCE return cloudprovider.NotImplemented
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_instances.go#L200

This method is used by CreateNodeDialer:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L209

Please see discussion here:
https://github.com/kubernetes/kubernetes/issues/49402#issuecomment-328182008
https://github.com/kubernetes/kubernetes/pull/53912#issuecomment-337038897

**Comment by dims** [comment]
This is part of larger work - https://github.com/kubernetes/kubernetes/issues/48690

**Comment by dims** [comment]
Discussion on the mailing list - https://groups.google.com/d/msg/kubernetes-sig-api-machinery/bwJJ93qA99o/vHBeID_HAgAJ

**Comment by dims** [comment]
Please see discussion in the sig mailing list:
https://groups.google.com/d/msg/kubernetes-sig-api-machinery/bwJJ93qA99o/pRTVFaIlBAAJ

**Comment by dims** [comment]
w00h00.... are we there yet @liggitt ?

**Comment by liggitt** [comment]
getting there... the separate network proxy component is making progress (see ENABLE_EGRESS_VIA_KONNECTIVITY_SERVICE option and the `konnectivity-agent` addon

**Comment by matthyx** [comment]
This bug appears to have been addressed by https://github.com/kubernetes/kubernetes/pull/102297

/close
