### ISSUE TITLE
Zone labels are removed every kubelet restart in 1.8

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#54070]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:

I upgraded my cluster from 1.7 -> 1.8.1 and realized that all my failure domain & region labels were gone. 

**What you expected to happen**:

I expect those labels to remain

**How to reproduce it (as minimally and precisely as possible)**:

Without a cloud provider (bare metal) or with the CCM, restart a 1.8.x kubelet and you'll see that the node is updated w/o the zone labels. 

**Anything else we need to know?**:

The offending commit that caused this issue is [here](https://github.com/kubernetes/kubernetes/commit/80156474cf46b919b5d4b51a4676dc395c3e90dc#diff-6b0808bd1afb15f9f77986f4459601c2). The external cloud providers will also be impacted by this since the labels will be removed; however, since the cloud taint is gone they will never attempt to add those labels back. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.x

cc @mrIncompetent @wlan0 @luxas @andrewsykim

**Comment by jhorwit2** [comment]
IMO, the `updateDefaultLabels` method should *not* remove labels that do not exist on the initial node. That's a recipe for disaster.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/blob/76a4674bd47dc9a9d2148bc7cda3e630f43ec770/pkg/kubelet/kubelet_node_status.go#L170-L180

Agree. That loop should continue if the initial node does not have an opinion on one of the default labels:

```go
for _, label := range defaultLabels { 
  if _, hasInitialValue := initialNode.Labels[label]; !hasInitialValue {
    continue
  }
  ...
```
