### ISSUE TITLE
Liveness/Readiness Probes should treat any 2XX status as healthy

### ISSUE THREAD

**Issue by jakeswenson** [kubernetes/kubernetes#54082]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Liveness probes and readiness probes don't seem to treat 204 No Content as healthy (even though 2XX status codes are success statuses) 

**What you expected to happen**:
Any 2XX status should be treated as healthy.

**How to reproduce it (as minimally and precisely as possible)**:
Create an app with an endpoint returning 204 No Content and set the liveness/readiness probes to be that endpoint. 

Note app does not become healthy and does not respond. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: GCP/GKE
- OS (e.g. from /etc/os-release): cos
- Kernel (e.g. `uname -a`): GCP/GKE
- Install tools: N/A
- Others: N/A

**Comment by jakeswenson** [comment]
this feels like a /sig scheduling but I'm not sure...
/sig scheduling

**Comment by anfernee** [comment]
Looks like the code is doing the right thing in master: https://github.com/kubernetes/kubernetes/blob/4b0511dc8cc6d4fb4775e00198757d50b35856a6/pkg/probe/http/http.go#L95

**Comment by jakeswenson** [comment]
interesting. Maybe this was an older version than 1.7 ... let me double check. 
Thanks

**Comment by jakeswenson** [comment]
Apologies, It appears that the issue isn't kubernetes specifically. Its GCP health checks, which require 200 to be returned. https://cloud.google.com/compute/docs/load-balancing/health-checks#http_and_https_health_checks

Since kubernetes creates load balancers with health checks for services/ingress this was causing an issue making our traffic not route to kubernetes.

I'll file another issue as a feature request for this... is there a good sig to use? is sig/google cloud a thing?

**Comment by dchen1107** [comment]
cc/ @abgworrall for sig-gcp related

**Comment by nicksardo** [comment]
Kubernetes isn't the correct place for this request. https://issuetracker.google.com/savedsearches/559790 is a tracking page for GCP LB feature requests and issues. In fact, this has already been requested: https://issuetracker.google.com/u/1/issues/65486751.

Could you please close this issue?

**Comment by jakeswenson** [comment]
Yes. Thanks for the pointers
