### ISSUE TITLE
admission_test.go failed with go1.9.1

### ISSUE THREAD

**Issue by jingax10** [kubernetes/kubernetes#54086]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

When running k8s unit tests, TestAmit test case emitted an error as follows:

2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54246: remote error: tls: bad certificate
E1017 10:38:30.860166  110747 admission.go:199] failed calling admission webhook "disallow": Post https://127.0.0.1:35435/disallow: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
E1017 10:38:30.862514  110747 admission.go:199] failed calling admission webhook "disallowReason": Post https://127.0.0.1:35435/disallowReason: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54248: remote error: tls: bad certificate
E1017 10:38:30.866700  110747 admission.go:199] failed calling admission webhook "internalErr A": Post https://127.0.0.1:35435/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54252: remote error: tls: bad certificate
2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54254: remote error: tls: bad certificate
E1017 10:38:30.868555  110747 admission.go:199] failed calling admission webhook "internalErr B": Post https://127.0.0.1:35435/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54250: remote error: tls: bad certificate
E1017 10:38:30.868789  110747 admission.go:199] failed calling admission webhook "internalErr C": Post https://127.0.0.1:35435/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/17 10:38:30 http: TLS handshake error from 127.0.0.1:54256: remote error: tls: bad certificate
E1017 10:38:30.871811  110747 admission.go:199] failed calling admission webhook "allow": Post https://127.0.0.1:35435/allow: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
--- FAIL: TestAdmit (0.02s)
	admission_test.go:221: "match & disallow": expected allowed=false, but got err=<nil>
	admission_test.go:226: "match & disallow": expected an error saying "without explanation", but got <nil>
	admission_test.go:221: "match & disallow ii": expected allowed=false, but got err=<nil>
	admission_test.go:226: "match & disallow ii": expected an error saying "you shall not pass", but got <nil>
FAIL
FAIL	k8s.io/kubernetes/plugin/pkg/admission/webhook	0.555s

Notice that, I used gvm to switch golang versions. The test cases actually passed with go1.8.3 but not go1.9.1.

**What you expected to happen**:

TestAmit should pass when we bump up golang version in the future k8s releases.

**How to reproduce it (as minimally and precisely as possible)**:
Just run "make test"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
master branch
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by caesarxuchao** [comment]
We need to investigate if we can fix the problem in our code or if users will have to regenerate the cert,

**Comment by dims** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/54020

Also see the PR https://github.com/kubernetes/kubernetes/pull/54030
