### ISSUE TITLE
RBAC policy for creating a single object?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#54080]
What is the RBAC policy to lock down creating to a particular object (in my case, a secret)?

I've tried:

```
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
  resourceNames: ["singleton"]
```

But that gives me "...cannot create secrets..."

It seems to need:

```
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
```

(Similar to #54079)

**Comment by liggitt** [comment]
the object name is not in the URL of a create request, and therefore is unavailable to the authorization layer (for all authorizers, not just RBAC).

From https://kubernetes.io/docs/admin/authorization/rbac/#referring-to-resources:

> Notably, if resourceNames are set, then the verb must not be list, watch, create, or deletecollection. Because resource names are not present in the URL for create, list, watch, and deletecollection API requests, those verbs would not be allowed by a rule with resourceNames set, since the resourceNames portion of the rule would not match the request.

**Comment by liggitt** [comment]
There's discussion of adding crupdate support for secrets/configmaps which would allow update API calls to create as well.

**Comment by justinsb** [comment]
How does sig-auth do feature tracking?  Should we leave open?

**Comment by justinsb** [comment]
(PS thanks for confirming @liggitt )
