### ISSUE TITLE
Device plugin checkpointing should be more reliable

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#54088]
https://github.com/kubernetes/kubernetes/blob/64fde98206fcb764958d62a1a4a03c0420d72b45/pkg/kubelet/cm/device_plugin_handler.go#L253-L269

It should write to a temporary file and rename the file to ensure atomic writes. It should also fsync the file before closing to avoid data loss on machine reboots. 
You can check the examples in the kubelet package such as `pkg/kubelet/kubeletconfig` or `pkg/kubelet/dockershim/docker_checkpoint.go`

FYI, I also have a WIP PR (#54085) to extract the common logic into a utility package to increase code reusability.

/cc @jiayingz @vishh @mindprince

**Comment by jiayingz** [comment]
Thanks a lot for filing the issue and your suggestions! +1 for a common util of doing checkpointing. Please let us know when that is available.

**Comment by vikaschoudhary16** [comment]
cc @jeremyeder

**Comment by jiayingz** [comment]
FYI, @vikaschoudhary16 mentioned he will work on modifying device plugin checkpoint code to use the newly added file store utility.

**Comment by jberkus** [comment]
Since PR #56040 is not mergeable, should this issue be moved out of the 1.9 milestone?  Please update the status of the issue to indicate; I'm not clear on whether #56040 is a blocker for this issue, or whether #55382 implements it.  Thanks!

**Comment by tengqm** [comment]
I believe #55382 has implemented this. #56040 is a next step, not blocker.

**Comment by jiayingz** [comment]
Agree with @tengqm On the other hand, because https://github.com/kubernetes/kubernetes/pull/55382 hasn't been merged yet, we probably want to remove this issue from 1.9 blocker.

**Comment by jiayingz** [comment]
/close
issue should have been fixed with https://github.com/kubernetes/kubernetes/pull/55382
