### ISSUE TITLE
We should have a retrying cached discovery RESTMapper

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#54084]
Several clients and controllers want a caching discovery RESTMapper that regenerates its contents periodically and/or on failure, since discovery information is not guaranteed to stay static over the lifetime of a process -- new APIs may be registered after the initial discovery information has been fetched.  We should add an instance of this to the ControllerContext so that different controllers can share this information.

The cached discovery client half of this equation is already there (`"k8s.io/client-go/discovery".CachedDiscoveryInterface`), however, the equivalent RESTMapper half (`"k8s.io/client-go/discovery".DeferredDiscoveryRESTMapper`) doesn't quite do what we want -- the `"k8s.io/client-go/discovery/cached".MemCacheClient` implementation of `CachedDiscoveryInterface` always reports fresh (after the initial population), so `CachedDiscoveryRESTMapper` will never call `Invalidate` on it more than once, meaning we never update our cached discovery information.  We need to periodically invalidate the underlying cached discovery information for this to work properly.

Examples of things that want this:
- As input to the ScaleKindResolver used by the Scale client in the HPA controller
- namespace cleanup?
- GC?
- k8s-prometheus-adapter (external to kube)

**Comment by DirectXMan12** [comment]
cc @deads2k 
cc @kubernetes/sig-api-machinery-feature-requests 

as per https://github.com/kubernetes/kubernetes/pull/53743#pullrequestreview-69925396

**Comment by lavalamp** [comment]
Have you looked at the garbage collector? I believe it has a rest mapper that does this.

**Comment by derekwaynecarr** [comment]
This would be useful for quota monitoring.

See: https://github.com/kubernetes/kubernetes/pull/54320

**Comment by hzxuzhonghu** [comment]
I think this can be closed now. Because now we periodically invalidate the underlying cached discovery information.

**Comment by DirectXMan12** [comment]
is that part of the cache, or part of the setup code in kube-proper?  Other projects outside of kube proper use the discovery cache.

**Comment by DirectXMan12** [comment]
We need an easy-to-consume way to do this for ancillary repos as well.
