### ISSUE TITLE
TestCRD times out

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#54095]
TestCRD is hitting the 5min limit sometimes and getting killed:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/54040/pull-kubernetes-unit/58848/artifacts/junit_dbb07cf89b3516a97dd7efe0aecea5f6edb73152_20171017-190122.stdout

**Comment by enisoc** [comment]
According to the stack trace at the 5min cutoff point, this call had not yet returned:

https://github.com/kubernetes/kubernetes/blob/658956f0631c6bd3ecf9f756db4a0710efea98ea/cmd/kube-apiserver/app/testing/server_test.go#L250

**Comment by sttts** [comment]
I like the `// TODO DO NOT MERGE THIS` line.

**Comment by sttts** [comment]
Looks like this has nothing todo with CRDs, but etcd did not start working. The logs look like that it is about our kube-apiserver test fixture which involved many leaked storage objects and etcd clients. @frobware has a PR open tackling this https://github.com/kubernetes/kubernetes/pull/50690, while introducing some ugliness due to a `stopCh` we have to pass around.

**Comment by enisoc** [comment]
Because the test was killed due to timeout, it never prints the buffered log messages about proceeding to other steps. But if you look at the stack dump, it got all the way through creating the CRD, waiting for it to be established, creating the InitializerConfiguration, etc. So etcd did start working.

Even on a successful run, I see lots of those lines about trying to connect to etcd. I wonder if it's just timing out because it's slow. We allow 300s for each test, and on my machine in `-race` mode this takes 150s. If we run in `-race` mode in CI, I could easily see it running up against the timeout.

**Comment by sttts** [comment]
Those etcd lines are not from the TestCRD test (they actually appear before the server and is launched), but they slow down the tests a lot. We have reproduced that (@frobware did), one test alone is very stable, with all of those running a kube-apiserver, we are not far from the maximum until we time out. @frobware had added one further test (openapi aggregation) and it broke down.

**Comment by sttts** [comment]
The test runner from OpenShift https://github.com/openshift/origin/blob/master/test/integration/runner/runner_test.go would make this kind of integration tests much more stable. We are leaking a lot on test shutdown and it eventually slows us down so much that tests timeout.

**Comment by enisoc** [comment]
That makes sense. It sounds like this is basically a dupe of #49489, so I'll close it. Thanks for investigating.

**Comment by enisoc** [comment]
Reopening to continue tracking this particular test, because it's the top of the flakes chart:

http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1

Are there any workaround we can do on just this test while #50690 is still in progress?

**Comment by sttts** [comment]
> Are there any workarounds we can do on just this test while #50690 is still in progress?

A test runner which launches new processes or a better shutdown or we disable the test. I don't see any other solution. #50690 tried to go the second route, but hit resistance.

**Comment by BenTheElder** [comment]
cc @spiffxp

**Comment by spiffxp** [comment]
Trying to compare [[velodrome bigquery-metrics](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1)] to [[triage job=pull-kubernetes-unit](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-unit)]

This particular test isn't really showing much for [[triage test=TestCRD](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestCRD)] compared to [[triage test=TestDescribeServiceAccount](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestDescribeServiceAccount)]

**Comment by BenTheElder** [comment]
I'm not sure about the triage / bigquery results but I've been seeing this particular flake quite a bit while shepherding some PRs. 2-3x in a row on the same PR(s).

**Comment by spiffxp** [comment]
Why is a "unit" test spinning up apiserver and etcd?  Would it make sense to move this to test/integration?

**Comment by sttts** [comment]
> Why is a "unit" test spinning up apiserver and etcd? Would it make sense to move this to test/integration?

We saw the same issues in integration tests. That's why we haven't spent the time to move it.

https://github.com/kubernetes/kubernetes/pull/54704 is going to improve the situation.

**Comment by mml** [comment]
Was #54704 supposed to fix this?

**Comment by spiffxp** [comment]
It appears to have fallen off the [wall of shame](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1) and no longer shows as failing on [release-master-blocking#test-go](https://k8s-testgrid.appspot.com/sig-release-master-blocking#test-go&include-filter-by-regex=TestCRD&width=5).  I'm happy with it from a release perspective

It's failed twice in the last day according to [presubmits-kubernetes#pull-kubernetes-unit](https://k8s-testgrid.appspot.com/presubmits-kubernetes#pull-kubernetes-unit).  Need more evidence IMO

/priority important-longterm

**Comment by BenTheElder** [comment]
Forgot this issue is still open, still seeing this happen: https://github.com/kubernetes/kubernetes/pull/55095#issuecomment-341872178

**Comment by dims** [comment]
@stts Ack. i am travelling this week (Sydney) will be back over the weekend.

**Comment by sttts** [comment]
@dims will also take another look. This flakes a lot right now.

**Comment by yujuhong** [comment]
Another occurrence: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55034/pull-kubernetes-unit/63006/

**Comment by sttts** [comment]
Related: #55169 #55175

**Comment by spiffxp** [comment]
/close
This appears to have been fixed, it's not showing up on the wall of shame anymore
