### ISSUE TITLE
NewNvidiaGPUManager should not depend directly on Docker libdocker.Interface

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#54101]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go#L63

```
	// The interface which could get GPU mapping from all the containers.
	// TODO: Should make this independent of Docker in the future.
	dockerClient     libdocker.Interface
```

Related to https://github.com/kubernetes/kubernetes/issues/54090

**Comment by yujuhong** [comment]
related: #43240

**Comment by tianshapjq** [comment]
this may help for detecting the gpus: [Add per container GPU metrics](https://github.com/google/cadvisor/pull/1762)

**Comment by resouer** [comment]
We already have plan which targets at 1.10 cycle: https://github.com/kubernetes/kubernetes/issues/54012

**Comment by mindprince** [comment]
/remove-lifecycle stale

This code is going to be removed in the 1.11 cycle.

**Comment by dims** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/54012
