### ISSUE TITLE
create endpoint with pod hostname

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#54119]
I plan to deploy hadoop on kubernetes，when i deploy successfully，I need create service for ambari agent，so I can accees hdfs port from my external host。So I create endpoint and service like this:
kind: Endpoints
apiVersion: v1
metadata:
  name: hdfs
  namespace: bigdata
subsets:
  - addresses:
      - ip: 10.233.72.11
      - ip: 10.233.104.75
    ports:
      - port: 50070
        protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: hdfs
  namespace: bigdata
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 50070
    targetPort: 50070
    nodePort: 31176

I need to get ip of ambari agent pod from kubernetes，can I create endpoint with pod hostname？

**Comment by thockin** [comment]
This is a help-request, not a bug.  StackOverflow is probablybetter for you.

a) Use a selector, rather than manual endpoint creation
b) look at pod `hostname` and `subdomain` fields
c) create a headless service (clusterIP: None) with the same name as the pod `subdomain`
