### ISSUE TITLE
pull-kubernetes-e2e-kubeadm-gce is broken again

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#54118]
/kind bug

**What happened**:

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kubeadm-gce is solid red for over 24h

**What you expected to happen**:

Not all red.

I mentioned it in https://kubernetes.slack.com/archives/C09QZ4DQB/p1508249038000603 yesterday but didn't see any reaction, so I'm cranking up the volume a little.

@kubernetes/sig-testing-bugs 
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by luxas** [comment]
Please reopen this in kubernetes/kubeadm so the right team can track it (the kubeadm team)
Also, if you want to reach most of the kubeadm devs on Slack, ping the #sig-cluster-lifecycle channel.

Thanks for the notification!
