### ISSUE TITLE
statefulset mount rbd volume failed

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#54131]
I create statefulset pod with volume from ceph rbd，Pod status is always ContainerCreating
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ambari-test
  namespace: bigdata
spec:
  serviceName: "ambari-agent"
  template:
    metadata:
      labels:
        app: ambari-test
    spec:
      containers:
      - name: ambari-test
        image: registry.dev1.com:5000/ambari-agent:2.4.2.0.2.4
        imagePullPolicy: Always
        command:
           - /usr/local/bin/start.sh
        securityContext:
          privileged: true
        volumeMounts:
        - name: vol1
          mountPath: /mnt/vol1
  volumeClaimTemplates:
  - metadata:
      name: vol1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph
      resources:
        requests:
          storage: 1Gi

I found pod log info like this
kubectl describe pod ambari-test-0 -n bigdata
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		2m		2	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "vol1-ambari-test-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "vol1-ambari-test-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "vol1-ambari-test-0", which is unexpected.]
  2m		2m		1	default-scheduler			Normal		Scheduled		Successfully assigned ambari-test-0 to master3
  20s		20s		1	kubelet, master3			Warning		FailedMount		Unable to mount volumes for pod "ambari-test-0_bigdata(61c416e2-b3d9-11e7-9a13-005056b63f93)": timeout expired waiting for volumes to attach/mount for pod "bigdata"/"ambari-test-0". list of unattached/unmounted volumes=[vol1]
  20s		20s		1	kubelet, master3			Warning		FailedSync		Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "bigdata"/"ambari-test-0". list of unattached/unmounted volumes=[vol1]

**Comment by like-inspur** [comment]
I modify storageclass namespace and then recreate it，so statefulset create suceessfully。Why I can find storageclass from other namespace，but pod start failed with volume，I think this is bug!

**Comment by dixudx** [comment]
/sig storage

@like-inspur From the log
> SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "vol1-ambari-test-0", which is unexpected.

Seems scheduler did not find a satisfied volume for your PVC. Please help check your valid PVs.

> I modify storageclass namespace and then recreate it，so statefulset create suceessfully

`storageclass` is used to help PVC bound a satisfied PV.

**Comment by like-inspur** [comment]
@dixudx But other namespace not in storageclass define can see this storageclass，then pod mount volume failed like this. I think storageclass shoud be seen in one namespace not all namespaces
