### ISSUE TITLE
Conntrack table growing in linear fashion

### ISSUE THREAD

**Issue by fgbreel** [kubernetes/kubernetes#54138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
 I noticed a linear increase on my conntrack table.

from `netstat` or `ss` I found `8579` lines like these:
```
tcp        0      0 127.0.0.1:56848         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:40850         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:52616         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:54342         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:55110         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:41332         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:43940         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
tcp        0      0 127.0.0.1:36526         127.0.0.1:2379          ESTABLISHED 3053/kube-apiserver
```

also around `8583` like these

```
tcp        0      0 127.0.0.1:2379          127.0.0.1:44712         ESTABLISHED 3164/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:60098         ESTABLISHED 3164/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:41678         ESTABLISHED 3164/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:41736         ESTABLISHED 3164/etcd
```

**What you expected to happen**:
Less entries inside conntrack table.

**How to reproduce it (as minimally and precisely as possible)**:
1. build packages from github.com/kubernetes/release and install on a fresh debian stable host.
2. run `kubeadm init --apiserver-advertise-address=0.0.0.0 --pod-network-cidr=10.244.0.0/16`
3. configure CNI from this PR https://github.com/projectcalico/canal/pull/106
4. wait until `KubeletReady`
5. remove taint from master node (to be able to schedule pods on master).
6. at this point the `/proc/net/nf_conntrack` start to fill.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3 Processor DRAM Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3 Processor Integrated Graphics Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d5)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation B85 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
```
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux master.example.com 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```
- Install tools:
- Others:

![context-switches-kube](https://user-images.githubusercontent.com/893920/31716151-d56d9b1e-b406-11e7-97de-34c35838f9a8.png)
![conntrack-kube](https://user-images.githubusercontent.com/893920/31716152-d585047a-b406-11e7-9e25-df209fc0ee03.png)

**Comment by fgbreel** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by cmluciano** [comment]
Are you running a scale test whereby more and more pods/services are being created?

**Comment by fgbreel** [comment]
No, it's quite idle, if I restart `kube-apiserver` the conntrack table returns to normal state. 

Seems that kube API is keeping several connections opened with `etcd`

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc

**Comment by bowei** [comment]
Is the conntrack entries stable after restart of the API server or does it continue to grow.

**Comment by fgbreel** [comment]
It continues to grow.

  attached some graphs too.

Seems that kube API is establishing new connections instead of using the already established ones.

**Comment by lavalamp** [comment]
Does it also go down if you restart the master node's kubelet?

**Comment by lavalamp** [comment]
Are there any common errors showing up in the apiserver log?

Typically this is caused by a client failing to completely read the contents of a response, preventing the go http library from reusing the connection.

**Comment by lavalamp** [comment]
cc @cheftako has fixed a similar bug in the past.

**Comment by lavalamp** [comment]
cc @jpbetz that looks like a lot of connections to etcd?

**Comment by fgbreel** [comment]
> Does it also go down if you restart the master node's kubelet?

no, `ESTABLISHED` connections continues to grow since docker keep containers running.

> Are there any common errors showing up in the apiserver log?
> 
> Typically this is caused by a client failing to completely read the contents of a response, preventing the go http library from reusing the connection.

I found `644` entries like:

```
I1020 05:29:25.774400       1 trace.go:76] Trace[2043139971]: "Update /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" (started: 2017-10-20 05:29:25.107421972 +0000 UTC) (total time: 666.963565ms):
Trace[2043139971]: [666.926722ms] [666.899938ms] Object stored in database
I1020 05:29:25.774792       1 trace.go:76] Trace[1048842723]: "GuaranteedUpdate etcd3: *api.Endpoints" (started: 2017-10-20 05:29:25.107409201 +0000 UTC) (total time: 667.366554ms):
Trace[1048842723]: [667.354959ms] [667.239071ms] Transaction committed
I1020 05:29:25.774849       1 trace.go:76] Trace[1429885851]: "Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2017-10-20 05:29:25.10736389 +0000 UTC) (total time: 667.473105ms):
Trace[1429885851]: [667.437706ms] [667.410913ms] Object stored in database
I1020 05:33:19.828592       1 trace.go:76] Trace[813284104]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.325434235 +0000 UTC) (total time: 503.138728ms):
Trace[813284104]: [503.085308ms] [502.29792ms] Transaction committed
I1020 05:33:24.821864       1 trace.go:76] Trace[572828417]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.820747229 +0000 UTC) (total time: 5.001096086s):
Trace[572828417]: [5.001096086s] [5.000393198s] END
E1020 05:33:24.821893       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:24.822787       1 trace.go:76] Trace[802189716]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.821981108 +0000 UTC) (total time: 5.000791658s):
Trace[802189716]: [5.000791658s] [5.000306794s] END
E1020 05:33:24.822804       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:25.411019       1 trace.go:76] Trace[1373649910]: "GuaranteedUpdate etcd3: *api.Endpoints" (started: 2017-10-20 05:33:20.41038595 +0000 UTC) (total time: 5.000610395s):
Trace[1373649910]: [5.000610395s] [5.000504467s] END
E1020 05:33:25.411042       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:25.411165       1 trace.go:76] Trace[596178483]: "Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2017-10-20 05:33:20.41032577 +0000 UTC) (total time: 5.000828723s):
Trace[596178483]: [5.000828723s] [5.000791901s] END
```

Strange to see random timeouts when communication is done through `127.0.0.1` address. 

I'm attaching the logs from my `master` node kube-apiserver. 
I sanitized the nodes FQDN and IP addresses to:
- using `node{01..03}.example.com` and `master.example.com` names instead of real ones.
- `xx.xx.xx.xx` stands for my master public ip address.
- `aa.aa.aa.aa` is my remote public ip address.

[kube-apiserver-container-log.txt.gz](https://github.com/kubernetes/kubernetes/files/1401522/kube-apiserver-container-log.txt.gz)

This log are from the period in red:

![fw_forwarded_local-week-sc11](https://user-images.githubusercontent.com/893920/31815901-71b6b248-b58e-11e7-96d7-4738a8c98b8e.png)

**Comment by fgbreel** [comment]
> Does it also go down if you restart the master node's kubelet?

No, it continues to grow since docker keep the containers running.

> Are there any common errors showing up in the apiserver log?
> 
> Typically this is caused by a client failing to completely read the contents of a response, preventing the go http library from reusing the connection.

I found `644` entries like these:

```
I1020 05:29:25.774400       1 trace.go:76] Trace[2043139971]: "Update /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" (started: 2017-10-20 05:29:25.107421972 +0000 UTC) (total time: 666.963565ms):
Trace[2043139971]: [666.926722ms] [666.899938ms] Object stored in database
I1020 05:29:25.774792       1 trace.go:76] Trace[1048842723]: "GuaranteedUpdate etcd3: *api.Endpoints" (started: 2017-10-20 05:29:25.107409201 +0000 UTC) (total time: 667.366554ms):
Trace[1048842723]: [667.354959ms] [667.239071ms] Transaction committed
I1020 05:29:25.774849       1 trace.go:76] Trace[1429885851]: "Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2017-10-20 05:29:25.10736389 +0000 UTC) (total time: 667.473105ms):
Trace[1429885851]: [667.437706ms] [667.410913ms] Object stored in database
I1020 05:33:19.828592       1 trace.go:76] Trace[813284104]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.325434235 +0000 UTC) (total time: 503.138728ms):
Trace[813284104]: [503.085308ms] [502.29792ms] Transaction committed
I1020 05:33:24.821864       1 trace.go:76] Trace[572828417]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.820747229 +0000 UTC) (total time: 5.001096086s):
Trace[572828417]: [5.001096086s] [5.000393198s] END
E1020 05:33:24.821893       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:24.822787       1 trace.go:76] Trace[802189716]: "GuaranteedUpdate etcd3: *api.Node" (started: 2017-10-20 05:33:19.821981108 +0000 UTC) (total time: 5.000791658s):
Trace[802189716]: [5.000791658s] [5.000306794s] END
E1020 05:33:24.822804       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:25.411019       1 trace.go:76] Trace[1373649910]: "GuaranteedUpdate etcd3: *api.Endpoints" (started: 2017-10-20 05:33:20.41038595 +0000 UTC) (total time: 5.000610395s):
Trace[1373649910]: [5.000610395s] [5.000504467s] END
E1020 05:33:25.411042       1 status.go:62] apiserver received an error that is not an metav1.Status: etcdserver: request timed out
I1020 05:33:25.411165       1 trace.go:76] Trace[596178483]: "Update /api/v1/namespaces/kube-system/endpoints/kube-scheduler" (started: 2017-10-20 05:33:20.41032577 +0000 UTC) (total time: 5.000828723s):
Trace[596178483]: [5.000828723s] [5.000791901s] END
```

Strange to see timed out connections from since `etcd` and `kube-apiserver` are communicating though `127.0.0.1`:

```
[...]
tcp        0      0 127.0.0.1:2379          127.0.0.1:49216         ESTABLISHED 4145/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:49218         ESTABLISHED 4145/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:49220         ESTABLISHED 4145/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:49222         ESTABLISHED 4145/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:49224         ESTABLISHED 4145/etcd
tcp        0      0 127.0.0.1:2379          127.0.0.1:49226         ESTABLISHED 4145/etcd
[...]
tcp        0      0 127.0.0.1:49216         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49218         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49220         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49222         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49224         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49226         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
tcp        0      0 127.0.0.1:49228         127.0.0.1:2379          ESTABLISHED 4169/kube-apiserver
[...]
```

I'm attaching the logs for the period in red:

![fw_forwarded_local-week-sc11](https://user-images.githubusercontent.com/893920/31818421-5659f4a6-b598-11e7-90bb-cc3f14c597e8.png)

[kube-apiserver-container-log.txt.gz](https://github.com/kubernetes/kubernetes/files/1401707/kube-apiserver-container-log.txt.gz)

ps: I sanitized the logs by replacing my domain for `example.com` (ie: `master` and `node{01..03}`) and the master node public ip address to `xx.xx.xx.xx`. My office address was replaced to `aa.aa.aa.aa`.

**Comment by yliaog** [comment]
cc @yliaog

**Comment by gtie** [comment]
I see this issue after upgrade from K8s 1.7.5 to 1.8.1 as well. In some cases, the connection/memory acceleration is dramatic, and etcds start dying in ~30 minutes after restart (on a cluster with some 30-40 workers).

![selection_062](https://user-images.githubusercontent.com/2247364/32510270-5627aba2-c3f0-11e7-97f4-087e914cb76f.png)

Once memory is over on one of the etcd nodes, the container there is killed, and the connections get spilled over the two remaining alive nodes, and then they go belly-up as well.

**Comment by gtie** [comment]
It's worth noting that restarting etcd itself does not make the connections go away. They appear to be retried from the apiserver side, and as soon as etcd is back up, the flood resumes in full swing.

**Comment by jdumars** [comment]
Is there any new information on this issue?

**Comment by notjames** [comment]
we were seeing similar, if not the same, issues tracked here https://github.com/samsung-cnct/kraken/issues/203 et al. Turns out the fix for us was updating to k8s 1.8.2. The version of etcd was irrelevant for the symptoms we were experiencing. Sadly, we did not continue seeking a root cause once we found 1.8.2 solved our problems. Disregard the linked issues specifying the etcd version as fixing the issue. Etcd was a red herring.

**Comment by fgbreel** [comment]
I also upgraded from `1.8.0` to `1.8.3` and now seems to be more manageable, but I still have the crontab entry to remove `kube-apiserver` container every morning.

![conntrack](https://user-images.githubusercontent.com/893920/33010331-6b36c2a0-cdda-11e7-8ea1-da602411ef52.png)

I'll remove it today and keep it running during the week to observe the number of established connections.

**Comment by fgbreel** [comment]
After some days with crontab entry disabled the conntrack entries continues to increase, but in a very slow rate.

Which is okay.

`~1k` per day with `gcr.io/google_containers/kube-apiserver-amd64:v1.8.0`
vs
`~100` per day with `gcr.io/google_containers/kube-apiserver-amd64:v1.8.3`

![k8s-conn](https://user-images.githubusercontent.com/893920/33432499-75d8d0c6-d5d8-11e7-8823-db0b102c3a0e.png)

**Comment by gtie** [comment]
@notjames, thanks for the hint! The upgrade to 1.8.3 solved the issue for our clusters.

As part of the upgrade, we enabled collection of etcd app metrics, and those show etcd's `process_open_fds` remaining constant (at 200-300 after days of usage, supported by manual spot-checks of netstat). 

@fgbreel, is it possible that your conntrack metric is picking up something else than etcd connections?

**Comment by fgbreel** [comment]
@gtie I double checked with `netstat/ss` and new connections is being created, but it's okay with this rate. 

![screen shot 2017-12-01 at 12 24 42](https://user-images.githubusercontent.com/893920/33481068-39855db8-d693-11e7-971f-2be700df48ad.png)
![screen shot 2017-12-01 at 12 24 35](https://user-images.githubusercontent.com/893920/33481070-399de9fa-d693-11e7-8c1b-8b152f9f4ded.png)

Maybe we can close this issue.
