### ISSUE TITLE
should update out of date code comment for apps/v1beta2

### ISSUE THREAD

**Issue by wackxu** [kubernetes/kubernetes#54139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

PR https://github.com/kubernetes/kubernetes/pull/50164 have remove the remove apps/v1beta2 defaulting codes for obj.Spec.Selector and obj.Labels, but the API reference and code comment is not updated and it is confused for user, releated issue https://github.com/kubernetes/kubernetes/issues/53976

**What you expected to happen**:

update code comment

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by foxish** [comment]
cc @crimsonfaith91
