### ISSUE TITLE
 Whitelist net.core.somaxconn as a safe sysctl

### ISSUE THREAD

**Issue by tomoe** [kubernetes/kubernetes#54132]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

As a developer or an operator of an application without cluster admin permissions, I would like to configuire
net.core.somaxconn in pod configuration as explained in the following doc:
https://kubernetes.io/docs/concepts/cluster-administration/sysctl-cluster/

**What you expected to happen**:

I expect to be able to configure net.core.somaxconn in my pod configuration.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

IIUC, the kernel parameter gets initialized upon netns creation
https://github.com/torvalds/linux/blob/80cee03bf1d626db0278271b505d7f5febb37bba/net/core/net_namespace.c#L318

So, I think it's safe to whiltelist as a safe operation.
If we agree, I'd like to prepare a pull request. 

**Environment**:

- Kubernetes version (use `kubectl version`): HEAD of master on github
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@tomoe i'd recommend just creating the PR and have the debate there if needed

**Comment by tomoe** [comment]
@dims thx for following up. will bring one up soon.

**Comment by tomoe** [comment]
I will create a PR to the sysctl proposal as suggested in https://github.com/kubernetes/kubernetes/pull/54896#issuecomment-348235363

**Comment by julianvmodesto** [comment]
@tomoe is it feasible to mark `net.ipv4.tcp_max_syn_backlog` as safe for the same reasoning we can mark `somaxconn` as safe?

https://github.com/torvalds/linux/blob/4608f064532c28c0ea3c03fe26a3a5909852811a/net/ipv4/sysctl_net_ipv4.c#L858

If so, I can open a new issue for this.

**Comment by arpadkun** [comment]
I could not track this discussion further. Is this the last place, or has it been discussed further somewhere else? I would like to be able to set `net.core.somaxconn` values and wonder if this is still considered.
