### ISSUE TITLE
admission config file for UAS can't handle embedded objects

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#54159]
The config objects contained don't round trip.

**Comment by lavalamp** [comment]
I don't understand the description, can you expand a bit?

**Comment by mbohlool** [comment]
cc @caesarxuchao

**Comment by deads2k** [comment]
> I don't understand the description, can you expand a bit?

Without a nested encoder and decoder for the embedded objects, decoding and re-encoding didn't serialize back out correctly.  #53442 fixes the problem.
