### ISSUE TITLE
Kube-dns pods coming up super slowly in large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#54164]
Our 5k-node cluster jobs recently started failing even before the e2e tests start. The reason is the step which checks that all kube-system pods are running is timing out:

```
I1018 07:27:06.071] Oct 18 07:27:06.070: INFO: Waiting up to 10m0s for all pods (need at least 8) in namespace 'kube-system' to be running and ready
I1018 07:27:09.904] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-24tgk is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2cb7g is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2hn22 is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I1018 07:27:09.905] Oct 18 07:27:09.904: INFO: The status of Pod kube-dns-75f5545c67-2vdpq is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
...
```

cc @kubernetes/sig-scalability-misc @wojtek-t @porridge

**Comment by shyamjvs** [comment]
From the scheduler logs I'm seeing that the pods are being scheduled quite slowly, getting worse with time:

```
I1018 17:30:56.844196       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-bdz9v", UID:"9763f07f-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"37846", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-bdz9v to e2e-test-shyamjvs-minion-group-j8rz
I1018 17:31:17.701058       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-hwgzp", UID:"9763ee15-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"37847", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-hwgzp to e2e-test-shyamjvs-minion-group-kq67
I1018 17:31:38.057271       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-p5d89", UID:"9763f5c2-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"37848", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-p5d89 to e2e-test-shyamjvs-minion-group-m02b
I1018 17:31:58.967741       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-b7v7p", UID:"9d582708-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"41181", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-b7v7p to e2e-test-shyamjvs-minion-group-m8zw
I1018 17:32:20.654937       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-kgjjg", UID:"9d587f84-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"41183", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-kgjjg to e2e-test-shyamjvs-minion-group-n92b
I1018 17:32:41.592954       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-xrphw", UID:"9d588548-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"41184", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-xrphw to e2e-test-shyamjvs-minion-group-nkb3
I1018 17:33:03.040806       7 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-dns-75f5545c67-fkgm5", UID:"a948d3f3-b428-11e7-a488-42010a8e0002", APIVersion:"v1", ResourceVersion:"47192", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned kube-dns-75f5545c67-fkgm5 to e2e-test-shyamjvs-minion-group-p3j6
```

2-3 pods/min looks quite bad.

cc @kubernetes/sig-scheduling-bugs

**Comment by shyamjvs** [comment]
Also finding such traces:

```
I1018 17:19:31.146720       7 trace.go:76] Trace[1286759859]: "Scheduling kube-system/kube-dns-75f5545c67-2h6r6" (started: 2017-10-18 17:19:30.549179196 +0000 UTC) (total time: 597.502764ms):
Trace[1286759859]: [594.380145ms] [593.588469ms] Prioritizing
```

Seems like most of the time is being spent in priority calculation.

**Comment by shyamjvs** [comment]
From the pod spec, I'm seeing soft inter-pod anti-affinity at node-level topology:

```
        "affinity": {
            "podAntiAffinity": {
                "preferredDuringSchedulingIgnoredDuringExecution": [
                    {
                        "podAffinityTerm": {
                            "labelSelector": {
                                "matchExpressions": [
                                    {
                                        "key": "k8s-app",
                                        "operator": "In",
                                        "values": [
                                            "kube-dns"
                                        ]
                                    }
                                ]
                            },
                            "topologyKey": "kubernetes.io/hostname"
                        },
                        "weight": 100
                    }
                ]
            }
        },
```

I'm almost sure this is the one causing the mischief. We've been having performance issues with anti-affinity traditionally :p

**Comment by shyamjvs** [comment]
Ok... PR https://github.com/kubernetes/kubernetes/pull/52193 is the cause. It introduced anti-affinity to kube-dns. I think we should revert this change given known issues with anti-affinity.

@StevenACoffman @bowei @MrHohn @wojtek-t - Opinions?

**Comment by shyamjvs** [comment]
FYI - it is taking >80m until the last pod is scheduled when I'm running 5k-node cluster locally.

**Comment by bowei** [comment]
That's quite unfortunate. It looks like we should revert the change until the anti-affinity change is scalable enough to be used more broadly, unless the scheduler folks have a target fix for this use case. @bsalamat @davidopp

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-misc

**Comment by bsalamat** [comment]
We are very well aware of the performance issues in our affinity/anti-affinity functions, but I am not aware of a concrete solution at this point. This is partly due to the flexible design of affinity/anti-affinity concept.
My humble opinion at this point is to drop some of the flexibility as they are rarely used, in order to streamline the algorithm and improve performance.
Anyway, I think the proper solution to this problem needs more time than your requirements to address the issue in hand. So, you may want to change your configuration and drop the anti-affinity rule.

**Comment by porridge** [comment]
@bsalamat would it make sense to add a note to the anti-affinity user documentation to hint at performance problems at large scale, until this is fixed?

**Comment by shyamjvs** [comment]
Re-opening this issue as this problem has struck again. The following runs of our 5k-node scalability jobs failed to bring up the cluster on time:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/106
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/107
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/68
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/69

And the reason is kube-dns pods pending to be scheduled for a long time:

```
I0202 08:24:01.432] Feb  2 08:24:01.431: INFO: The status of Pod kube-dns-754f9cd4f5-26f4h is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0202 08:24:01.432] Feb  2 08:24:01.431: INFO: The status of Pod kube-dns-754f9cd4f5-2gnwp is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0202 08:24:01.433] Feb  2 08:24:01.431: INFO: The status of Pod kube-dns-754f9cd4f5-2h6qr is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0202 08:24:01.433] Feb  2 08:24:01.431: INFO: The status of Pod kube-dns-754f9cd4f5-2kcrd is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0202 08:24:01.433] Feb  2 08:24:01.431: INFO: The status of Pod kube-dns-754f9cd4f5-2nkwr is Pending (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
...
```

**Comment by shyamjvs** [comment]
These failures started happening about 4 days ago and I'm pretty sure it's this one:

Add self anti-affinity to kube-dns pods #57683

Sadly, we'll have to revert it again for now :(

cc @bsalamat @misterikkit - Seems like the improvements to anti-affinity performance made under https://github.com/kubernetes/kubernetes/issues/54189 weren't enough?

**Comment by cblecker** [comment]
@kubernetes/sig-scalability-test-failures

**Comment by bsalamat** [comment]
We need to find other improvements for the predicate. If we cannot find major improvement opportunities, we may have to change its design to be more scalable at the cost of the reducing its flexibility.

**Comment by wojtek-t** [comment]
@bsalamat - my personal opinion is that we need to change the design anyway. Having it work both ways (i.e. existing pods everywhere impacting placing of our pod) will always be painful (especially for things like cluster autoscaler)

**Comment by bsalamat** [comment]
@wojtek-t I agree. The symetrical application of anti-affinity is problematic. I also think we need to change it.

**Comment by wojtek-t** [comment]
> @wojtek-t I agree. The symetrical application of anti-affinity is problematic. I also think we need to change it.

Great. @davidopp - do you agree with that too?

**Comment by cheyang** [comment]
@bsalamat , @shyamjvs, I'm wondering after some affinity/anti-affinity optimization in scheduler, do you think  if it's fine to test coreDNS with anti-affinity policy in large cluster with 5000 nodes?

**Comment by wojtek-t** [comment]
We probably should try to see where we are - but this requires testing before enabling that.

**Comment by shyamjvs** [comment]
I agree with @wojtek-t.
@cheyang - Could we first try checking with a benchmark integration test ([e.g](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_bench_test.go)) as a proxy for real cluster test?

**Comment by misterikkit** [comment]
@cheyang Since the integration tests fake out the nodes, I think it's safe to crank it up to 5000 (that's the current largest integration test benchmark size)

I'm also hoping to refactor our benchmarks soon, so let me know if you have any thoughts about them.
