### ISSUE TITLE
Remove kubelet --enable-custom-metrics in v1.11

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#54161]
--enable-custom-metrics marked deprecated in https://github.com/kubernetes/kubernetes/pull/54154
The flag should be removed in v1.11.

**Comment by luxas** [comment]
I think we can remove it way faster than that (already in v1.9?) as it never left alpha and v1.6 removed the need for the flag.
cc @kubernetes/sig-autoscaling-bugs

**Comment by mattjmcnaughton** [comment]
Out of curiosity, what is the best practice for making a pr that (potentially) shouldn't be merged until a later version? Is there a way to specify that automatically, or do we just wait to merge it until 1.X is the next release?

I'm happy to tackle this if possible - I'd love to learn more about that part of k8s.

**Comment by mtaufen** [comment]
@luxas I'd rather just follow the standard deprecation policy.
@mattjmcnaughton Just wait until 1.X is the next release. Don't waste your time rebasing again and again while you wait ;).

**Comment by luxas** [comment]
@mtaufen For a feature that have been unusable since v1.6; I think that's not desirable. I'd vote for v1.10

**Comment by mtaufen** [comment]
@luxas Has the Kubelet rejected this flag in previous releases? Otherwise we should follow the CLI deprecation policy (1 release or 6 months, whichever is longer). It's possible people have the flag set in their shell scripts if they haven't gotten an automatic warning yet. Remember, unrecognized flags cause Kubelet crash loops.

**Comment by mtaufen** [comment]
This wouldn't be a problem if we'd marked it deprecated in the same release that it stopped being useful...

**Comment by luxas** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/60699
