### ISSUE TITLE
LoadConfig in e2e tests could be better

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#54168]
So, when we were trying to fix the use case where one runs the e2e tests inside a pod, we should pick up the InClusterConfig (serialize to disk and use that to run the tests), @timothysc spotted a few inconsistencies, some of the discussion is here:

https://github.com/kubernetes/kubernetes/pull/53924#issuecomment-337091717
https://github.com/kubernetes/kubernetes/pull/53924#issuecomment-337710289

Opening this issue to remind us to go back and fix these issues.

**Comment by antoniaklja** [comment]
@dims is it still valid? if yes, could you give me more context?

**Comment by dims** [comment]
@antoniaklja - if you see the 2 linked comments, the first one talks about where we do the check for the in-cluster config and the second one as about adding a common place where we can put the code for converting in-cluster-config to an on-disk kubeconfig. we need to try to clean up both those things. 

cc @timothysc

**Comment by antoniaklja** [comment]
Thanks @dims ! Let's summarize everything before I start working on that:
- flag `TestContext.NodeE2E` indicates if test is running on the node not within pod
- we would like to have just one check if test is running within pod or on the node
- we would like to move `LoadConfig()` into one common place (probably to `AfterReadingAllFlags`) and initialize and use it only once
- what do you think about storing `client *restclient.Config` in `t *TestContextType`?

**Comment by dims** [comment]
/close

let's reopen if needed
