### ISSUE TITLE
CRD resourceVersion is incremented without any modifications made to the object

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#54172]
/kind bug

**What happened**:

the `resourceVersion` of a CRD is incremented without any modifications made to the object

**What you expected to happen**:

the `resourceVersion` of a CRD to only be incremented whenever a modification to the object is made

**How to reproduce it (as minimally and precisely as possible)**:

create the following CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noxus.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: noxus
    singular: noxu
    kind: Noxu
    listKind: NoxuList
```

run:
```
$ curl '127.0.0.1:8080/apis/mygroup.example.com/v1alpha1/noxus'
{"apiVersion":"mygroup.example.com/v1alpha1","items":[],"kind":"NoxuList","metadata":{"continue":"","resourceVersion":"46613","selfLink":"/apis/mygroup.example.com/v1alpha1/noxus"}}
$ curl '127.0.0.1:8080/apis/mygroup.example.com/v1alpha1/noxus'
{"apiVersion":"mygroup.example.com/v1alpha1","items":[],"kind":"NoxuList","metadata":{"continue":"","resourceVersion":"46615","selfLink":"/apis/mygroup.example.com/v1alpha1/noxus"}}
```

The object was not modified, the `resourceVersion` started with `46613` and not a small number, like 1, also the `resourceVersion` is incremented in almost every second.

**Anything else we need to know?**:

It seems the `resourceVersion` of CRDs are correlated with the endpoint's `resourceVersion`:
```
$ curl '127.0.0.1:8080/apis/mygroup.example.com/v1alpha1/noxus'
{"apiVersion":"mygroup.example.com/v1alpha1","items":[],"kind":"NoxuList","metadata":{"continue":"","resourceVersion":"47098","selfLink":"/apis/mygroup.example.com/v1alpha1/noxus"}}
$ curl '127.0.0.1:8080/api/v1/endpoints' | grep resourceVersion
        "resourceVersion": "47099",
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration**:
VM
- OS (e.g. from /etc/os-release):|
`16.10 (Yakkety Yak)`
- Kernel (e.g. `uname -a`):
`4.9.17-040917`
- Install tools:
- Others:

1) Is this the expected behavior?
2) If yes, then the client-go library has a bug because if the users want to have a ListWatcher with a re-sync of lets say 5 minutes, to listen for changes of a particular CRD but they will get this error on the logs:

>request.go:692] Debug GET https://192.168.33.11:6443/apis/mygroup.example.com/v1alpha1/noxus?resourceVersion=45187&timeoutSeconds=414&watch=true
>E1018 12:39:10.316092   26543 streamwatcher.go:110] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Status" is registered for version "v1" for object {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 45187 (45713)","reason":"Gone","code":410}

This happens because the client-go watcher for that CRD didn't receive any event, which make sense since the CRD was not modified. Unfortunately this prevents the client-go's `resourceVersion` for that CRD watcher to be up to date with the `resourceVersion` from the server. When the watcher does a re-sync, the server `resourceVersion` is higher than the last `resourceVersion` stored by the CRDs watcher causing streamwatcher.go to bail out with that error.

**Comment by aanm** [comment]
FYI @sttts

**Comment by sttts** [comment]
> It seems the resourceVersion of CRDs are correlated with the endpoint's resourceVersion:

Looks totally unrelated. But the correlation is striking.

**Comment by sttts** [comment]
On a second look: you check the resource version for the LIST call, not the CRD or CR. I would bet this resource version is artificially created using an atomically increasing counter from etcd. That also would explain that it correlates between different resources. Also note that you are not accessing the CRD, but the CR endpoint.

I would close this issue as it looks like a misunderstanding of the resource version counter on lists of CRs.

**Comment by nikhita** [comment]
Just for completeness, to get the `resourceVersion` for the CRD, you need to:

```
$ curl '127.0.0.1:8080/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/noxus.mygroup.example.com' | grep resourceVersion
    "resourceVersion": "417",
```

With this, you can see that the `resourceVersion` is not incremented without any updates.
