### ISSUE TITLE
Heapster not running on release-1.7 when KUBE_ENABLE_CLUSTER_MONITORING=none

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#54170]
We set `KUBE_ENABLE_CLUSTER_MONITORING=none` in our scalability [job](https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-scale-performance.env) which earlier had the effect of not creating heapster (or any other monitoring related addons). But metrics-server pod seems to get created.

cc @kubernetes/sig-instrumentation-bugs @fgrzadkowski @x13n @piosz

**Comment by shyamjvs** [comment]
@fgrzadkowski Assigned to you as @piosz is on vacation. Feel free to redirect as apt.

**Comment by fgrzadkowski** [comment]
@shyamjvs metric service should be always created, as it's used by HPA. During our discussion I thought you have heapster and metric server running at the same time even though you set `KUBE_ENABLE_CLUSTER_MONITORING=none`. Is it the case? Do you have heapster running?

**Comment by shyamjvs** [comment]
As I mentioned offline:
- There is no heapster running when `KUBE_ENABLE_CLUSTER_MONITORING=none`. I was expecting the same would be the case for metrics-server also (as its doing a part of the work heapster was earlier doing).
- From the [config-test.sh](https://github.com/kubernetes/kubernetes/blob/5563fbfbe133844f261f3ee21704874e8ea8f8f0/cluster/gce/config-test.sh#L132-L137) file I'm seeing modes `none` and `standalone` allowed for the env var, where the latter means 'heapster only' and the former means 'no monitoring setup' (from the comments). So I expected that behaviour.
- Disabling heapster (now metrics-server) should hurt only HPA (from what you said). Which probably is still fine (just that HPA would be dysfunctional)?

I just checked for release-1.8, and it seems like the same case:

```
$ KUBE_ENABLE_CLUSTER_MONITORING=none ./cluster/kube-up.sh
$ kubectl get pods -n kube-system | grep "metrics-server"
metrics-server-v0.2.0-56fddcccfc-df7cb   0/1       Pending   0          1s
$ kubectl get pods -n kube-system | grep "heapster"
$
```

Will check for 1.7 too.

**Comment by fgrzadkowski** [comment]
I believe the correct behavior should be:

* for 1.8 - always run metric-server (for HPA to work); run heapster only
if KUBE_ENABLE_CLUSTER_MONITORING is set to something
* for 1.7 - always run heapster (for HPA to work), but with potentially
different configuration

--
Filip

**Comment by shyamjvs** [comment]
Sorry for the delay. Just checked, and seems like 1.7 doesn't run heapster when monitoring is disabled:

```
$ KUBE_ENABLE_CLUSTER_MONITORING=none ./cluster/kube-up.sh
$ kubectl get pods -n kube-system | grep "heapster"
$
```

@fgrzadkowski - fyi

**Comment by fgrzadkowski** [comment]
@shyamjvs I think that was a bug, because we needed heapster for HPA to work and I guess you didn't disable HPA...

In other words I believe that current behavior with metric server always running is the correct one. How bad is it for you? Is it easy to fix those failing tests?

@kubernetes/sig-instrumentation-bugs @kubernetes/sig-autoscaling-bugs

**Comment by shyamjvs** [comment]
It isn't causing our tests to fail, just a bit annoying with multiple logs in the build-log saying that the pod is pending. We have 2 options:
( ) create a special node large enough for it to schedule
(X) ditch the error

Anyway, the bigger issue seems to be heapster not running in 1.7 in that mode.
