### ISSUE TITLE
Add a fast path to inter-pod affinity/anti-affinity for hostname topology key

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#54189]
It is not a secret that [inter-pod affinity/anti-affinity predicate is much slower than other predicates](https://github.com/kubernetes/autoscaler/issues/257).
In my opinion the main reason for the slowness is the flexibility of the inter-pod affinity/anti-affinity rules. However, in most practical scenarios users do not need all the flexibility. For example, people often do not use arbitrary labels in topology key of the affinity rules. They often use node, zone, or region as the topology. Node in particular is used often. That's why I am proposing a fast path for the case that topology key is Node.
Today, the affinity/anti-affinity predicate does not have any distinction for topology keys and [scans all the pods](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L1001) in the cluster regardless. The logic should recognize "kubernetes.io/hostname" and scan only pods on the same node for this topology key.

**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature

/sig scheduling
cc/ @shyamjvs

**Comment by bsalamat** [comment]
ref/ #54164

**Comment by misterikkit** [comment]
We found some other simple optimizations that had a significant impact on the affinity predicate. I will upload PRs for those as well.

**Comment by shyamjvs** [comment]
Reopening this as the performance of anti-affinity still doesn't seem to be satisfactory enough on large clusters (i.e 5k nodes) - and it's causing them to fail to startup. Ref: issue #54164 

I can help with evaluating any performance improvements if needed.

**Comment by bsalamat** [comment]
The change @misterikkit sent improved performance of the predicate, but apparently it is not enough to make our large scale scalability tests happy.

**Comment by bsalamat** [comment]
@shyamjvs This issue is not about general performance improvment of affinity/anti-affinity. It was to implement a particular improvment which is already implemented. There are other performance improvement issues. I am going to close this one.

**Comment by shyamjvs** [comment]
Sounds good. Thanks.

**Comment by tsuna** [comment]
How come with kops 1.10.0 I still see all kube-dns pods on the same node because the kube-dns deployment doesn't specify any anti-affinity rule?

**Comment by misterikkit** [comment]
> How come with kops 1.10.0 I still see all kube-dns pods on the same node because the kube-dns deployment doesn't specify any anti-affinity rule?

I think you are correct. you can double-check with the `-o yaml` option to `kubectl get pods`. I have a v1.9 cluster in front of me, and kube-dns has no affinity rules. (I didn't use kops though)
