### ISSUE TITLE
Run kube-proxy in a Docker container

### ISSUE THREAD

**Issue by vmarmol** [kubernetes/kubernetes#5419]
Have it be a static pod started by the Kubelet.

**Comment by markturansky** [comment]
This would allow it to run iptables on OS X, wouldn't it?

**Comment by thockin** [comment]
First, kube-proxy needs to be able to open host ports dynamically - this
would require --net=host support.

Second kube-proxy needs to be able to update iptables so it would require
--privileged to be enabled.

**Comment by markturansky** [comment]
If kube-proxy were to run in docker, it would not be running in OS X itself.  The cmd would, but the server itself would be in a container running in the b2d VM.  It can manipulate iptables in the VM.

That last piece (b2d-ip:port) would enable me to curl from OS X into Kube with my service.  

I've developed most of Persistent Volumes on the Mac, but the service fronting my examples had to be tested on Linux.  That's the last piece of the puzzle.

**Comment by vmarmol** [comment]
That's what worries me about this approach. We'd need to expose both of those as options in the manifest. They're probably not options we want to give most jobs. Maybe we can limit it to static pods, but that sounds brittle.

**Comment by preillyme** [comment]
I agree with @vmarmol if it can be limited to only static pods then I think it would be okay. Otherwise it just seems too risky.

**Comment by thockin** [comment]
Anything can be done, its just a matter of whether it is worthwhile.  If
this let's us run other daemons in containers, it might be.

**Comment by bgrant0607** [comment]
FYI: @jmreicha Reported kube-proxy running out of fds. Not sure if it was a user limit or system limit yet.

If we change to iptables (#3760), would we just integrate that into Kubelet, which needs to watch services, anyway, in which case kube-proxy would go away?

**Comment by jmreicha** [comment]
I opened a new issue https://github.com/GoogleCloudPlatform/kubernetes/issues/5461 for my problem since we're not exactly sure what the problem is yet.

**Comment by bgrant0607** [comment]
Re. net=host and privileged: I'm not in favor of stricting to just static pods. We want to move such pods to a per-node controller, for one, and I also don't want API skew.

The right solution is policy enforcement, such as by using the admission control plugin.

**Comment by bgrant0607** [comment]
Host directories and host ports have the same issue.

**Comment by thockin** [comment]
Except that host ports an dirs were relatively easy to implement and are
done :)

But yes - these features are all "leaky" in a way that we wan to discourage
but maybe not disallow.

**Comment by bgrant0607** [comment]
I'm not saying that we definitely should implement net=host, just commenting on the way to restrict it. Sticking flags on kubelet and/or kube-proxy is a short-term hack that won't scale.

**Comment by vmarmol** [comment]
I'll start tackling this.

**Comment by brendandburns** [comment]
I don't think this makes the v1.0 bar.

**Comment by bgrant0607** [comment]
@vmarmol Are we setting ulimit (num. fds) of kube-proxy now at least?

**Comment by thockin** [comment]
I think this is part of upgrades.

**Comment by vmarmol** [comment]
This is part of upgrades which is why it was placed under v1.0.

@bgrant0607 we have for most providers, we need to add a check in the kube-proxy when it comes up.

**Comment by tamsky** [comment]
Placing kube-proxy in a docker container might resolve the concurrency issue triggering #7370.

kube-proxy would be the lone actor in its container.

Agree that `--privileged` and `--net=host` would be new requirements.

**Comment by vmarmol** [comment]
@tamsky wouldn't the iptables config still be in the host network so the same race would exist?

**Comment by tamsky** [comment]
@vmarmol I think you're right.
I'm so used to thinking that "iptables rules are per-container" that I forgot the implications of  `--net=host`.

**Comment by ArtfulCoder** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/compare/master...ArtfulCoder:proxypod

**Comment by thockin** [comment]
@mikedanese more to do or is this done?

**Comment by mikedanese** [comment]
done
