### ISSUE TITLE
Try ipset in kube-proxy

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#54203]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Two bugs reported in kube-proxy IPVS mode, see:

#53393 

#53775 

I think the root cause is missing SNAT(masq) rules. We can employ iptables, but I am worried about the performance issue. As @song-jiang and @fasaxc suggested, there is a better solution, the ipset. We can put the `ip:port` in a ip sets and then only need to build a static iptables rule, like

1. create a KUBE-MARK-MASQ chain in nat table,

```
Chain KUBE-MARK-MASQ (1 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK or 0x4000
```

2. jump to MASQUERADE when mark match 0x4000/0x4000

```
Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000
```

3. jump to KUBE-MARK-MASQ for any matched ipset,

```
ipset -N myset hash:ip,port
ipset -A myset 1.1.1.1,tcp:8080

iptables -A PREROUTING -m set --set myset {src,src|dst,dst} -j KUBE-MARK-MASQ
iptables -A OUTPUT-m set --set myset {src,src|dst,dst} -j KUBE-MARK-MASQ
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

/area kube-proxy

**Comment by m1093782566** [comment]
My plan is:

- [ ] wrapper ipset util, i.e list/create/delete ipset

- [ ] try ipset in kube-proxy ipvs mode, fix bugs in #53775, #53393

- [ ] try ipset in kube-proxy ipvs mode for masq-all and cluster-cidr

- [ ] try ipset in kube-proxy iptables mode.

I am working on at least 1, 2 and 3.

**Comment by m1093782566** [comment]
cc @cmluciano

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests

**Comment by chenchun** [comment]
@m1093782566 I think you have a few mistakes in your ipset example

```
ipset -N myset hash:ip,port
ipset -A myset 1.1.1.1,8080
iptables -t nat -A POSTROUTING -m set --match-set myset dst -j MASQUERADE
```
MASQUERADE is only valid in POSTROUTING chain.

**Comment by m1093782566** [comment]
oops.. My mistake.

My full example is, 

1. create a KUBE-MARK-MASQ chain in nat table,

```
Chain KUBE-MARK-MASQ (1 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK or 0x4000
```

2. jump to MASQUERADE when mark match 0x4000/0x4000

```
Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000
```


3. jump to KUBE-MARK-MASQ for any matched ipset,

```
ipset -N myset hash:ip,port
ipset -A myset 1.1.1.1,tcp:8080

iptables -A PREROUTING -m set --set myset {src|dst} -j KUBE-MARK-MASQ
iptables -A OUTPUT-m set --set myset {src|dst} -j KUBE-MARK-MASQ
```

Does it work for you :) 

BTW, I already sent a PR about using ipset in ipvs proxy mode, xref: https://github.com/kubernetes/kubernetes/pull/54219

Any comments are welcome.

**Comment by fasaxc** [comment]
@m1093782566 There's a small bug in your iptables rule there; to match a `hash:ip,port` rule, I think you need:
```
iptables -A PREROUTING -m set --set myset {src,src|dst,dst} -j KUBE-MARK-MASQ
```
You may also need `-p tcp`, but maybe that's taken care of by the protocol in the ipset itself.

**Comment by m1093782566** [comment]
@fasaxc 

Sorry, I am not sure I understand the bug...

What's the difference between 

```
iptables -A PREROUTING -m set --set myset {src,src|dst,dst} -j KUBE-MARK-MASQ
```

and 

```
iptables -A PREROUTING -m set --set myset {src|dst} -j KUBE-MARK-MASQ
iptables -A OUTPUT-m set --set myset {src|dst} -j KUBE-MARK-MASQ
```
?

**Comment by m1093782566** [comment]
**Help Wanted**

I want to solve the hairpin problem reported in #53775 and made a prototype mixed with ipset, iptables and ipvs.


1. I created a local up cluster with IPVS proxy mode.

2. I created a service with ClusterIP type

```
[root@SHA1000130405 net]# kubectl get svc
NAME            CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
nginx-service   10.0.0.205   <none>        3080/TCP   9m
```

3. the nginx-service has only 1 endpoints

```
[root@SHA1000130405 net]# kubectl get endpoints
NAME            ENDPOINTS             AGE
nginx-service   172.17.0.3:80         10m
```

4. I enabled **hairpin_mode** for all virtual devices on the host

```
[root@SHA1000130405 net]# pwd ; find . -name hairpin_mode | xargs cat
/sys/devices/virtual/net
1
1
1
```

5. The IPVS rules for the service looks like

```
[root@SHA1000130405 net]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.0.205:3080 rr
  -> 172.17.0.3:80                Masq    1      0          0         
```


6. The ipset information for kernel looks like

```
[root@SHA1000130405 net]# ipset list
Name: KUBE-LOOP-BACK
Type: hash:ip
Revision: 1
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 16576
References: 1
Members:
100.106.89.164
172.17.0.3
172.17.0.2

Name: KUBE-SERVICE-ACCESS
Type: hash:ip,port
Revision: 2
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 16656
References: 1
Members:
10.0.0.205,tcp:3080
10.0.0.10,tcp:53
10.0.0.1,tcp:443
10.0.0.10,udp:53
```

7. The iptables rules in *nat tables looks like

```
[root@SHA1000130405 net]# iptables -t nat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */

Chain KUBE-MARK-DROP (0 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK or 0x8000

Chain KUBE-MARK-MASQ (1 references)
target     prot opt source               destination         
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination         
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination         
KUBE-SVC-IPSETS  all  --  0.0.0.0/0            0.0.0.0/0            match-set KUBE-SERVICE-ACCESS dst

Chain KUBE-SVC-IPSETS (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  0.0.0.0/0            0.0.0.0/0            match-set KUBE-LOOP-BACK src
```

Everything looks good and the iptables rules is very clean. However, when I tried to curl the service `ClusterIP:Port`(10.0.0.205:3080) from the backend container(172.17.0.3), it hangs until time out. If I curl the container IP:Port directly, it works fine. Seems the hairpin issue has not been solved yet.

I assumed when I send a request to `ClusterIP:Port(10.0.0.205:3080)` from `container(172.17.0.3)`, the packet will walk through the PREROUTING chain, then it will directly jump to KUBE-SERVICES chain. 

Since the packet's destination IP matched the ipset KUBE-SERVICE-ACCESS's entry `10.0.0.205,tcp:3080`, then it will jump to KUBE-SVC-IPSETS chain. 

Since the packet's source IP matched the ipset KUBE-LOOP-BACK's entry `172.17.0.3`, it will jump to KUBE-MARK-MASQ chain, then the packet will marked `0x4000` and will get masqueraded when the packet reaches the POSTROUTING chain.

Am I missing something? @fasaxc @song-jiang @chenchun any comments are welcome!

**Comment by cmluciano** [comment]
@m1093782566 IIRC hairpin mode needs to be enabled by the CNI plugin. The [CNI bridge plugin](https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L49) supports this at the moment. I'm not sure if there are any 3rd  party CNI plugins that have enabled hairpin mode yet.

xref: https://github.com/kubernetes/kubernetes/issues/53269#issuecomment-334590862 , https://github.com/containernetworking/cni/issues/476

cc @squeed @caseydavenport

**Comment by fasaxc** [comment]
@m1093782566 can you post the `iptables-save` output?  I find it much easier to read than `iptables -L` (which also hides some detail).

**Comment by fasaxc** [comment]
I often use commands like this to get a quick idea of which rules are being hit:
```
sudo watch -n 0.1 -d "iptables -nvL -t nat | grep -v -e '    0     0' -e '^$'"
```
Then you could use tcpdump to snoop on the interfaces.  Does it all work in the non-hairpin case?

**Comment by m1093782566** [comment]
@cmluciano Thanks for your quick feedback. Hairpin mode works in kube-proxy iptables mode in my environment.

**Comment by squeed** [comment]
Hairpin mode for the CNI plugin isn't applicable here, because we're masquerading the source address.

One thing you may wish to consider is adding a rule that matches `(src == dst)` for which you'll need the bpf module. Something like

`iptabes -t nat -A POSTROUTING -m bpf $(nfbpf_compile RAW 'ip[12:4] = ip[16:4]') -j MASQUERADE`, and an equivalent for ipv6.

**Comment by m1093782566** [comment]
@fasaxc 

> Does it all work in the non-hairpin case?

Yes. When I visit serviceIP + Port from the host, I can receive the response.

**Comment by m1093782566** [comment]
@squeed 

I can't find `nfbpf_compile` in my system, should I re-compile kernel?

**Comment by m1093782566** [comment]
@fasaxc Thanks for your hint.

The full output of iptables-save command is shown below:

```
[root@SHA1000130405 k8s-yml]# iptables-save
# Generated by iptables-save v1.4.21 on Fri Nov  3 17:21:11 2017
*mangle
:PREROUTING ACCEPT [150128557:42155175146]
:INPUT ACCEPT [131218527:41029805014]
:FORWARD ACCEPT [184508:365561015]
:OUTPUT ACCEPT [125253222:31457338232]
:POSTROUTING ACCEPT [125437702:31822901807]
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
COMMIT
# Completed on Fri Nov  3 17:21:11 2017
# Generated by iptables-save v1.4.21 on Fri Nov  3 17:21:11 2017
*nat
:PREROUTING ACCEPT [26:1617]
:INPUT ACCEPT [4:737]
:OUTPUT ACCEPT [3:192]
:POSTROUTING ACCEPT [3:192]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-IPSETS - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SERVICES -m set --match-set KUBE-SERVICE-ACCESS dst -j KUBE-SVC-IPSETS
-A KUBE-SVC-IPSETS -m set --match-set KUBE-LOOP-BACK src -j KUBE-MARK-MASQ
COMMIT
# Completed on Fri Nov  3 17:21:11 2017
# Generated by iptables-save v1.4.21 on Fri Nov  3 17:21:11 2017
*filter
:INPUT ACCEPT [5986:2251210]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5668:2255347]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
-A INPUT -p udp -m udp --dport 60129 -j ACCEPT
-A INPUT -p udp -m udp --dport 49537 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 49537 -j ACCEPT
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
COMMIT
# Completed on Fri Nov  3 17:21:11 2017
```


BTW, I find some interesting information when I watch packets hit in iptables chain,

```
[root@SHA1000130405 ~]# watch -n 0.1 -d "iptables -nvL -t nat | grep -v -e '    0     0' -e '^$'"

Every 0.1s: iptables -nvL -t nat | grep -v -e '    0     0' -e '^$'                                           Fri Nov  3 17:36:39 2017

Chain PREROUTING (policy ACCEPT 28 packets, 1254 bytes)
 pkts bytes target     prot opt in     out     source               destination
 2651  151K KUBE-SERVICES  all  --  *	   *	   0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
Chain INPUT (policy ACCEPT 5 packets, 334 bytes)
 pkts bytes target     prot opt in     out     source               destination
Chain OUTPUT (policy ACCEPT 4 packets, 240 bytes)
 pkts bytes target     prot opt in     out     source               destination
  497 30922 KUBE-SERVICES  all  --  *	   *	   0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
Chain POSTROUTING (policy ACCEPT 4 packets, 240 bytes)
 pkts bytes target     prot opt in     out     source               destination
  502 31222 KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
Chain KUBE-MARK-DROP (0 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-MARK-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-SVC-IPSETS (1 references)
 pkts bytes target     prot opt in     out     source               destination
```

It looks that the following chains are never hit???

```
Chain KUBE-MARK-DROP (0 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-MARK-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in     out     source               destination
Chain KUBE-SVC-IPSETS (1 references)
 pkts bytes target     prot opt in     out     source               destination
```

When I 

```
tcpdump -i { eth0 | docker0 | kube-ipvs0 | veth8544848 |  vethb651cf2 | virbr0}
```

I can NOT find any packet with src/dst IP ClusterIP `10.0.0.157` or Container IP `172.17.0.3`. I wonder the packet is dropped by kernel silently?

**Comment by fasaxc** [comment]
@m1093782566 I still think you need to use `dst,dst` when matching the `KUBE-SERVICE-ACCESS` ipset.  `hash:ip,port` IP sets have two parameters, so you need to pass `dst,dst` to tell the kernel to pass the IP and port to the match.  I tried this locally and the kernel accepts `dst`, but it doesn't seem to match anything:

```
$ sudo ipset list
Name: test
Type: hash:ip,port
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 256
References: 2
Members:
8.8.8.8,udp:100
8.8.8.8,udp:53
```

Then I did `nslookup www.google.com 8.8.8.8` and it only hits the second rule:
```
[0:0] -A FOO -m set --match-set test dst -j LOG
[3:180] -A FOO -m set --match-set test dst,dst -j LOG
```

**Comment by m1093782566** [comment]
That's a nice example, @fasaxc 

I will try it and will let you know updates. Thanks!

**Comment by squeed** [comment]
For some reason Debian doesn't include an `nfbpf_compile`. I built a quick docker image:
```
docker run quay.io/casey_callendrello/nfbpf_compile "tcp port 443 && host 4.2.2.2"
```

**Comment by m1093782566** [comment]
@fasaxc 

ipset `dst,dst` works for me, it solves the hairpin issue. Thanks again :)

**Comment by m1093782566** [comment]
The PR (#54219, try the goodness of ipset in IPVS kube-proxy) is ready for review now. Any comments are welcome. I appreciate your thoughts. Thanks again!
