### ISSUE TITLE
`kubectl logs -f` is not working correctly on 1.8

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#54205]
/kind bug

`kubectl logs -f ` is not working on Kubernetes 1.8. It gets stuck and only returns when the container exits.

I tested it in GKE 1.6.11 and 1.7.8 and it works there. But doesn't work on GKE 1.8.0.

Here's a simple reproduction:
1. Create a 1.8.0 or 1.8.1 cluster.
2. Run a simple busybox container and `echo "hello"`.
```
$ kubectl run -i -t busybox --image=busybox --restart=Never
If you don't see a command prompt, try pressing enter.
/ # echo "hello"
hello
```
3. In another terminal, try `kubectl logs` without `-f`. It works.
```
$ kubectl logs po/busybox
/ # echo "hello"
hello
```

4. Try `kubect logs -f` now. It gets stuck.
```
$ kubectl logs po/busybox -f
```

5. Enter more commands in the busybox terminal but there are still no logs in the `-f` terminal.
```
...
/ # echo "hello"
hello
/ # echo "hi"
hi
```

6. In another terminal try `kubectl logs` without `-f` again. That still works.
```
$ kubectl logs po/busybox
/ # echo "hello"
hello
/ # echo "hi"
hi
```
7.  Exit the busybox container:
```
...
/ # echo "hi"
hi
/ # exit
```

8. Logs would show up on the `-f` terminal now.

/sig cli

cc - @pwittrock @jpbetz

**Comment by pwittrock** [comment]
Please file under kubernetes/kubectl

**Comment by mengqiy** [comment]
It seems this is not a kubectl bug, see https://github.com/kubernetes/kubectl/issues/89#issuecomment-340076151.

/reopen

**Comment by mindprince** [comment]
Also note https://github.com/kubernetes/kubectl/issues/89#issuecomment-339860831, this only happens in [GKE alpha clusters](https://cloud.google.com/container-engine/docs/alpha-clusters) (`--enable-kubernetes-alpha`) that turn on all alpha features.

**Comment by mengqiy** [comment]
@kubernetes/sig-api-machinery-bugs @kubernetes/sig-node-bugs

**Comment by mtaufen** [comment]
@yujuhong @Random-Liu to make sure this isn't something funky with CRI log streaming on the node side
@smarterclayton @erictune do either of you guys know who's responsible for log streaming through API server?

**Comment by yujuhong** [comment]
> @yujuhong @Random-Liu to make sure this isn't something funky with CRI log streaming on the node side

AFAIK, we did not change CRI log streaming in 1.8. Given that this only fails in Alpha clusters, it'd be easier to vet the Alpha features instead.

**Comment by yujuhong** [comment]
Adding sig-gcp since only this has been observed only in GKE alpha clusters so far. If anyone from @kubernetes/sig-gcp-bugs is willing to help out by narrowing down what Alpha features are related, that'd be great.

**Comment by yujuhong** [comment]
I turned off `APIResponseCompression` in the apiserver in a GKE cluster and the log function is working again.
/cc @kubernetes/sig-api-machinery-bugs @ilackarms

**Comment by ru-it-specialist** [comment]
Ubuntu 16.0.4.5
Kubernetes v1.11.3

Agree with @yujuhong !

If `APIResponseCompression=true` ---> "kubectl -f" dose not work

**Comment by tsprlng** [comment]
> I turned off `APIResponseCompression` in the apiserver in a GKE cluster and the log function is working again.
> /cc @kubernetes/sig-api-machinery-bugs @ilackarms

Would you mind sharing how you did this? This now seems to be happening on non-alpha clusters there. The feature gate's alpha status in the Kubernetes docs hasn't changed though.

**Comment by yanniszark** [comment]
This is still an issue in Alpha Clusters.
I encountered this while deploying a GKE 1.13.5-gke.10 alpha cluster.
Shouldn't this issue be re-opened? 

cc @pwittrock
