### ISSUE TITLE
Remove kubectl dependency: create, set

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubernetes#54212]
/sig cli
/assign

**Comment by zjj2wry** [comment]
Are you working for kubectl set command? if not start, i can help for this~

**Comment by shiywang** [comment]
@zjj2wry np, I will only cut `create` dependency.

**Comment by WanLinghao** [comment]
@zjj2wry do you  mean I should wait your PR #54554 merged then rebase?

**Comment by zjj2wry** [comment]
yes, because kubectl want remove dependency from main rep. because your PR have `k8s.io/pkg/api/..`, so will can not get `approve` from approver.

**Comment by WanLinghao** [comment]
@zjj2wry  never mind though, I will wait

**Comment by zjj2wry** [comment]
@WanLinghao will resolve it soon : )

**Comment by WanLinghao** [comment]
@zjj2wry what can I do for this dependency remove?

**Comment by zjj2wry** [comment]
@WanLinghao set command have remove dependency now, you can rebase it ~
