### ISSUE TITLE
Calico node failed to start

### ISSUE THREAD

**Issue by khj809** [kubernetes/kubernetes#54220]
Hi. I'm using kubernetes 1.8.1 and trying to make cluster with calico 2.6.2.
I configured everything same as doc says, but when I run `kubeadm join` on other machine, it keeps failing on running calico-node pod with `CrashLoopBackOff` status.
The first container (`install-cni`) of pod seems running well, and second container (`calico-node`) fails with following messages:
```
$ kubectl logs calico-node-zt9hd calico-node -n kube-system
Skipping datastore connection test
ERROR: Unable to access datastore to query node configuration
Terminating
Calico node failed to start
```
What am I doing wrong?

**Comment by cmluciano** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by luxas** [comment]
I think you need to pass `--pod-network-cidr=192.168.0.0/16` as outlined in https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

If that doesn't work, reopen this issue in a Calico repository, this is not a Kubernetes issue.
Thanks!
