### ISSUE TITLE
ErrorHandlers may got block if time jumps back to the past

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#54236]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
in func OnError() of ErrorHandlers in apimachinery
```
func (r *rudimentaryErrorBackoff) OnError(error) {
	r.lastErrorTimeLock.Lock()
	defer r.lastErrorTimeLock.Unlock()
	d := time.Since(r.lastErrorTime)
	if d < 0 {
		time.Sleep(r.minPeriod - d)
	}
	r.lastErrorTime = time.Now()
}
```
it is expected to go on sleep for some time if not meet the minPeriod. However, if time happens hops to the past in the process. `d := time.Since(r.lastErrorTime)` would be a negative number, thus, it may sleep a lot longer than we expected.

**What you expected to happen**:

The period for sleep should be reseted if time hops

**Comment by yliaog** [comment]
adding a check on whether d is < 0 should fix it, no? if d < 0, simply don't sleep.

**Comment by dims** [comment]
ooh, we have time travelling kubes now :)

**Comment by yliaog** [comment]
so if d < 0, it's better to sleep r.minPeriod.

**Comment by yliaog** [comment]
i think Go 1.9 [Monotonic Time support ](https://golang.org/doc/go1.9#monotonic-time) should fix it, as reported and verified in the other issue [54130](https://github.com/kubernetes/kubernetes/issues/54130)
