### ISSUE TITLE
cluster/gce uses deprecated gcloud parameter "mode"

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#54238]
/kind bug

**What happened**:

Warning printed by `e2e-up.sh`: `WARNING: mode is deprecated. Please use subnet-mode instead.`

**What you expected to happen**:

No warning.

**How to reproduce it (as minimally and precisely as possible)**:

`kubetest -v --up`

**Anything else we need to know?**:

This is my first e2e cluster. Logs with more context below.

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release): Description:	Ubuntu 14.04 LTS

```
2017/10/19 16:18:51 util.go:154: Running: ./hack/e2e-internal/e2e-up.sh
Project: k8s-scale-testing
Network Project: k8s-scale-testing
Zone: us-east1-x
... Starting cluster in us-east1-x using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
... calling kube-up
Project: k8s-scale-testing
Network Project: k8s-scale-testing
Zone: us-east1-x
+++ Staging server tars to Google Storage: gs://kubernetes-staging-6524d3db95/e2e-test-porridge-devel
+++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = 2b91b5046dc30dd52e7cdea6086191b16a02bb56)
+++ kubernetes-salt.tar.gz uploaded (sha1 = 3e7907f15509540958c02a427aff989a340b8601)
+++ kubernetes-manifests.tar.gz uploaded (sha1 = ef5169fc331f2d2fafaf37a7995bd0367f1eb11e)
INSTANCE_GROUPS=
NODE_NAMES=
Looking for already existing resources
Creating new auto network: e2e-test-porridge
WARNING: mode is deprecated. Please use subnet-mode instead.
Created [https://www.googleapis.com/compute/v1/projects/k8s-scale-testing/global/networks/e2e-test-porridge].
NAME               SUBNET_MODE  BGP_ROUTING_MODE  IPV4_RANGE  GATEWAY_IPV4
e2e-test-porridge  AUTO         REGIONAL
```

**Comment by porridge** [comment]
@kubernetes/sig-testing-bugs

**Comment by ixdy** [comment]
This is probably an issue in the `cluster/gce` scripts. @kubernetes/sig-gcp-bugs

**Comment by ixdy** [comment]
This has started failing in tests:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress/20432

**Comment by ixdy** [comment]
I think this might be only in the staging gcloud release; at least https://cloud.google.com/sdk/docs/release-notes doesn't mention this being removed.

**Comment by krzyzacy** [comment]
and yeah, gce-canary is also using staging gcloud /shrug

**Comment by krzyzacy** [comment]
/assign @rmmh 
I'll fix kubetest, @rmmh is patching k8s

**Comment by calebamiles** [comment]
@krzyzacy should we close this issue since the PR merged?

**Comment by krzyzacy** [comment]
@calebamiles waiting for https://github.com/kubernetes/kubernetes/pull/61203, and that need to be cherrypicked into older releases

**Comment by krzyzacy** [comment]
still need to cherrypick into previous releases

**Comment by liggitt** [comment]
> still need to cherrypick into previous releases

agreed, but isn't blocking 1.10 any more

/milestone clear

**Comment by krzyzacy** [comment]
cherrypick is done, closing
/close
