### ISSUE TITLE
1.7 audit policy format still valid in 1.8

### ISSUE THREAD

**Issue by alapidas** [kubernetes/kubernetes#54254]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

The [1.7 audit policy file format](https://github.com/kubernetes/website/blob/release-1.7/docs/tasks/debug-application-cluster/audit.md#audit-policy) is different than the [1.8 format](https://github.com/kubernetes/website/blob/release-1.8/docs/tasks/debug-application-cluster/audit.md#audit-policy).  The 1.8 docs say specifically that:
```
In Kubernetes 1.8 kind and apiVersion along with rules must be provided in the audit policy file. A policy file with 0 rules, or a policy file that doesn't provide a valid apiVersion and kind value will be treated as illegal.
```
It appears that the 1.7 format is still being accepted.

For example, here is 1 .7 audit policy file that 1.8 appears to accept:
```
    # Log all requests at the Metadata level.
    rules:
    - level: Metadata
```
With this policy file in place, I see metadata level audit logs emitted to my configured path.
I can't tell if the file is in fact being treated as illegal per the docs and just defaulting to JSON logging at the metadata level at the configured path, or if it's actually accepting it (I assume the latter.

**What you expected to happen**:
Per the 1.8 docs, the config file should be treated as illegal and I should be notified of such.

**How to reproduce it (as minimally and precisely as possible)**:
Star a 1.8 apiserver with the following `--audit-policy-file`:
```
    # Log all requests at the Metadata level.
    rules:
    - level: Metadata
```
Configure an `--audit-log-path` as well.  Start apiserver and watch the metadata level JSON audit logs hit the logfile.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**: Baremetal
- OS (e.g. from /etc/os-release): Hyperkube
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-instrumentation-bugs

**Comment by alapidas** [comment]
@kubernetes/sig-instrumentation

**Comment by ericchiang** [comment]
Tested locally an can confirm that the audit policy doesn't require an apiVersion and kind. I must have messed up my initial report when I thought I hit this issue.

I think we still want to encourage users to pick an apiVersion explicitly though so I'm not super worried about the release note, though it's unfortunate that isn't inaccurate.

Should we modify the release notes post hoc?

**Comment by liggitt** [comment]
can soften language to "may be treated as invalid", but I agree it should be required. I'd fix it in master

**Comment by CaoShuFeng** [comment]
@alapidas
Thanks very much for pointing this out.

When I made [this](https://github.com/kubernetes/kubernetes/pull/49115#pullrequestreview-54029500) pull request, I found that without Kind and Apiversion, we can load 0 policy, even there are some policies in the file.
So, I said:
`In Kubernetes 1.8 kind and apiVersion along with rules must be provided in the audit policy`

But today, I tested the 1.8 release binary, I also found that we can load policies from policy file without kind and apiversion.

I guess there are some improvemnts in the encode/decode stuff between my pr and the 1.8 release.

**Comment by liggitt** [comment]
> I guess there are some improvemnts in the encode/decode stuff between my pr and the 1.8 release.

I'm not sure I consider that an improvement… it's likely to lead to undefined behavior if we load policy files and interpret them without knowing what version they are

**Comment by CaoShuFeng** [comment]
> I'm not sure I consider that an improvement… it's likely to lead to undefined behavior if we load policy files and interpret them without knowing what version they are

OK.
I used "git bisect" and find out this begins to happen after pull request #48287
