### ISSUE TITLE
Kubeadm init should check that kubelet's cluster-dns config matches kubeadm's service-cidr

### ISSUE THREAD

**Issue by leblancd** [kubernetes/kubernetes#54252]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature
/sig network

**What happened**:
When you install kubeadm, it comes with a kubeadm config file (e.g. /etc/systemd/system/kubelet.service.d/10-kubeadm.conf on CentOS/RHEL) that has a default cluster-dns setting of 10.96.0.10.

If you then run kubeadm init with a --service-cidr (or networking:serviceSubnet setting in a kubeadm config file) that is different than the default service subnet of 10.96.0.0, then 'kubeadm init ...' does not detect and warn the user (e.g. during preflight) that there is an inconsistency between the configured service CIDR and the kubelet's --cluster-dns setting in /etc/.... When containers are then created by kubelet, kubelet will populate the pods' /etc/resolv.conf with a nameserver address (using the --cluster-dns setting) that does not match the kube-dns service IP that is based on the configured service CIDR.

**What you expected to happen**:
It would be good of one of these things happened in the situation described:
(1) 'kubeadm init ...' preflight warns the user to consider changing the --cluster-dns config, OR...
(2) 'kubeadm init ...' preflight errors out
(3) 'kubeadm init ...' goes ahead and modifies the --cluster-dns config (too dangerous?)

**How to reproduce it (as minimally and precisely as possible)**:
- Run 'kubeadm init ...' with a --service-cidr on the command line (or serviceSubnet in a kubeadm config file) that doesn't match the --cluster-dns setting in 10-kubeadm.conf, and then create some pods
- Create some pods
- Exec into the pod, and examine the nameserver populated in /etc/resolv.conf. It will be different than the kube-dns service IP.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Latest master
- Cloud provider or hardware configuration**: VirtualBox cluster, Ubuntu 16.04 host, CentOS 7 guest nodes
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by dixudx** [comment]
`--cluster-dns=10.96.0.10` is declared in `10-kubeadm.conf`, which is not maintained/created by `kubeadm init`. Actually this file is included in debian/rpm package when installing `kubelet`.

@leblancd I don't think it is appropriate to read `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` on `kubeadm` side. Moreover, this filepath can be changed as well. The only way to get the right path is to calling `systemd`. If so, we're making it complicated and coupled.

@luxas @gyliu513 WDYT?

**Comment by luxas** [comment]
This is a known issue. I'm pretty sure it's documented somewhere.
We're gonna use Kubelet Dynamic Config for this (https://github.com/kubernetes/kubeadm/issues/28). Will hopefully make v1.9

**Comment by stealthybox** [comment]
related:
- https://github.com/kubernetes/kubeadm/issues/282
- https://github.com/kubernetes/website/pull/4164/files
