### ISSUE TITLE
Umbrella Issue: Conformance 

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/kubernetes#54256]
/kind enhancement

This morning, K8s.io announced a new conformance program.  Tests for each of the sig should be delineated conformance tests using by marking them with `[Conformance]` as described [here](https://github.com/cncf/k8s-conformance/blob/master/instructions.md).

This issue will serve to track each of the sig's participation in marking their tests.

- [ ] API Machinery
- [ ] Apps
- [ ] Architecture
- [ ] Auth
- [ ] Autoscaling
- [ ] AWS
- [ ] Azure
- [ ] Big Data
- [ ] CLI
- [ ] Cluster Lifecycle
- [ ] Cluster Ops
- [x] Contributor Experience
- [ ] Docs
- [ ] Multicluster
- [ ] Instrumentation
- [ ] Network
- [ ] Node
- [ ] On Premise
- [ ] OpenStack
- [ ] Product Management
- [ ] Release
- [ ] Scalability
- [ ] Scheduling
- [ ] Service Catalog
- [ ] Storage
- [ ] Testing
- [ ] UI
- [ ] Windows

@WilliamDenniss

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by timothysc** [comment]
@grodrigues3 what is your intent with this issue?  Sigs are already aware, and promotion to ```[Conformance]``` requires @kubernetes/sig-architecture-feature-requests  approval and sig-testing verification for enforcement.

**Comment by spiffxp** [comment]
is there anything to be done here?

**Comment by bgrant0607** [comment]
This issue isn't being used.

/close
