### ISSUE TITLE
podAffinityTerm.topologyKey is required

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#54276]
The field is marked as optional:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2414

The comment also describes a use case for empty topologykey:
https://github.com/kubernetes/kubernetes/blame/master/staging/src/k8s.io/api/core/v1/types.go#L2410

But the validation rule says it's required: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2662

**Comment by caesarxuchao** [comment]
cc @kubernetes/sig-scheduling-bugs

**Comment by caesarxuchao** [comment]
cc @aveshagarwal

The validation rule is added by https://github.com/kubernetes/kubernetes/pull/49976

**Comment by caesarxuchao** [comment]
@aveshagarwal the release note of 49976 should go into the "action-required" section of the [1.8 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md), but it's currently in "Other notable changes".

**Comment by guangxuli** [comment]
@aveshagarwal It seems that we should also update the external api type comments. Right?

**Comment by aveshagarwal** [comment]
I will look into it today.

**Comment by guangxuli** [comment]
@aveshagarwal If you didn't work on this, I am pleasure to send PR to fix this. :)

**Comment by aveshagarwal** [comment]
yeah sure. thanks.
