### ISSUE TITLE
Increase the code coverage of NodeController (TaintBasedEviction feature)

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#54297]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**Description**:

As discussed at https://github.com/kubernetes/features/issues/166#issuecomment-338165103 , we need to increase the code coverage of NodeController's TaintBasedEviction feature for upgrading to beta.

/sig node

**Comment by k82cn** [comment]
Append UT coverage here:

[node.html.gz](https://github.com/kubernetes/kubernetes/files/1406751/node.html.gz),
 [node_scheduler.html.gz](https://github.com/kubernetes/kubernetes/files/1406750/node_scheduler.html.gz)

**Comment by Huang-Wei** [comment]
/close

close this as it's resolved by #69788
