### ISSUE TITLE
Move hyperkube code to kubernetes/common

### ISSUE THREAD

**Issue by staebler** [kubernetes/kubernetes#54299]
/kind feature

It would be beneficial to have the hyperkube code available to other kubernetes projects. The kubernetes-incubator/service-catalog project recently added the hyperkube code so that its apiserver and controller-manager could be run from the same binary. It would be nice if the same code could be shared by kubernetes/kubernetes and kubernetes-incubator/service-catalog rather than having to duplicate the code. Perhaps some other projects might be also use hyperkube if it were more easily consumable, as well.

**Comment by lavalamp** [comment]
I don't understand why this is tagged api machinery?
