### ISSUE TITLE
Extend service port backends in ingress objects

### ISSUE THREAD

**Issue by m-no-2017** [kubernetes/kubernetes#54295]
Short info:
- k8s v1.7.2 (soon going to v1.8.0)
- bare-metal
- OS: Ubuntu 16.04.03 LTS
- Kernel: 4.11 (lowlatency)

Until now, we only had default ports (80,443) for our ingress objects to connect to running web applications. To enhance the connectivity for our CI/CD environment I route all our services to a nginx-controller pod, which is configured through configmaps to enable e.g. the jnlp-port (50000) of jenkins (which is also running in the cluster).

For further development it would be a vast improvement (not only for us) to be able to add a service port list to the ingress objects to one host url.

For example
<pre><code>apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-name
  namespace: dummy-namespace
spec:
  rules:
  - host: dummy-url.foo
    http:
      paths:
      - backend:
          serviceName: central-nginx
          servicePort: 80, 8080, 9090 <-- today this is divided into 3x objects and urls
        path: /</code></pre>

_Hint:  
this is only possible if you modify your container ports in your ingress controller to support more than just the default ports!_

The respective nginx config could contain server blocks for the specific listening ports.  
To this day this is only possible with an ingress rule for every port needed, which means an own url for every port that needs to be exposed.

/kind feature

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests 

cc @bowei 

Request to make [servicePort a map](https://github.com/kubernetes/api/blob/master/extensions/v1beta1/types.go#L771) for "future Ingress"
