### ISSUE TITLE
conversion-gen --extra-peer-dirs references k8s.io/kubernetes types

### ISSUE THREAD

**Issue by munnerz** [kubernetes/kubernetes#54301]
As part of the effort to make Kubernetes API types and machinery more consumable, we are attempting to decouple the code generators from the main Kubernetes API codebase.

With the introduction of the new code generation scripts in https://github.com/kubernetes/kubernetes/pull/52186, we made it easy for external projects to consume generators and generate code for their own API groups.

However, when running these generators against my types, the default value of `--extra-peer-dirs` includes `k8s.io/kubernetes/pkg/api` and `k8s.io/kubernetes/pkg/api/v1` (here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/cmd/conversion-gen/main.go#L55-L56). This causes the conversion generator to panic if this repo path isn't available, which in my project it is not (to save having to vendor the entire k8s source tree).

I understand the need to include these extra peer dirs is so that we can generate conversions when one of my own types references the core API types, however none of my types do this.

I see a few courses of actions:

* Update conversion-gen to not panic if it cannot find a directory listed in --extra-peer-dirs
* Update conversion-gen defaults to not include `k8s.io/kubernetes/pkg/api` and `k8s.io/kubernetes/pkg/api/v1` (which is breaking, and raises the question: "what constitutes something that makes sense to be default here?")
* Update the generate-*-groups.sh script to somehow accept args just for one of the generators (so that we can pass --extra-peer-dirs to the generator without breaking calls to *other* types of generator that don't include the `--extra-peer-dirs` flag)

For the time being, I am calling the generate scripts twice in my `update-client-gen` script (see: https://github.com/jetstack-experimental/navigator/blob/6a8477646109a002f3fc5e2846f0e8bd2f5ec51f/hack/update-client-gen.sh#L12-L23)

/sig api-machinery
/cc @sttts @nikhita @hongchaodeng

**Comment by lavalamp** [comment]
cc @caesarxuchao
