### ISSUE TITLE
Move ClientConnectionConfiguration struct to its own api group

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#54318]
As we are working towards configuring all server components with configuration files instead of command line flags, most or all of them are going to need to be configured to talk to the apiserver. We should make sure there is a single struct definition for the client configuration. Currently, in the componentconfig api group, we have ClientConnectionConfiguration, and it's only used by the KubeProxyConfiguration right now. We have multiple PRs in flight related to configuration APIs:

#53645 - move KubeProxyConfiguration out of componentconfig and into its own api group
#52562 - convert kube-scheduler to use a configuration file

The first PR, if merged, will move ClientConnectionConfiguration from componentconfig to kubeproxyconfig.k8s.io.

The second PR also needs to use ClientConnectionConfiguration, and ultimately needs to have the new scheduler config structs in their own new api group.

I propose we create another api group, something like `kubeconfig.k8s.io`, to house the ClientConnectionConfiguration struct, so it can be shared by multiple API groups needing to specify client connection configuration details.

WDYT?

@kubernetes/sig-api-machinery-api-reviews @jbeda @smarterclayton @deads2k @liggitt @sttts @luxas @mikedanese @mtaufen @timothysc

**Comment by ncdc** [comment]
@ironcladlou since you're working on the scheduler config

**Comment by xiangpengzhao** [comment]
FYI: Move KubeSchedulerConfiguration out of componentconfig API group #54211
@guangxuli

**Comment by smarterclayton** [comment]
If we created a Kubeconfig group, are there unopinionated structs we can
move from Kubeconfig or are people going to want to do big refactors?

Unrelated note - has someone queued up making kubectl explain works with
the new server config types?  Not being able to see config docs sucks.


On Oct 20, 2017, at 11:46 PM, Peter (XiangPeng) Zhao <
notifications@github.com> wrote:

FYI: Move KubeSchedulerConfiguration out of componentconfig API group #54211
<https://github.com/kubernetes/kubernetes/pull/54211>
@guangxuli <https://github.com/guangxuli>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/54318#issuecomment-338361391>,
or mute the thread

**Comment by ncdc** [comment]
@smarterclayton I did the ones for KubeProxyConfiguration and I hope they're reasonable, but I wouldn't say they have much use elsewhere.

As to docs on the config, I have #52198... I hadn't even considered doing this via kubectl explain, but I think that's potentially much nicer. WDYT?

**Comment by timothysc** [comment]
I'm a +1 for consolidating the data, but I question the long term utility of using the api for what are essentially command line args vs. a versioned config file. 

/cc @mikedanese

**Comment by deads2k** [comment]
> If we created a Kubeconfig group, are there unopinionated structs we can
> move from Kubeconfig or are people going to want to do big refactors?

The kubeconfig structs are fairly generic.  I'm not sure we'd bring in the authProvider bits since support for those requires tight integration, but the basic connection information isn't specific.

**Comment by lavalamp** [comment]
This looks like an API change, not an API Machinery change? Feel free to reset the label if I misunderstood.

**Comment by jberkus** [comment]
Should this be moved out of 1.9?  The attached PRs for this issue don't seem to be near resolution.

**Comment by ncdc** [comment]
I chatted with @luxas briefly yesterday and this probably isn't critical for either of those PRs, so I'm removing the 1.9 milestone. These config structs aren't using protobuf (since we want human-readable/writeable config files), so if we happen to move the structs somewhere else, the json tags would remain the same.

**Comment by luxas** [comment]
This will probably alpha in v1.9 anyway, right?
I'm fine with that

**Comment by mikedanese** [comment]
What part of ClientConnectionConfiguration is not expressable in a kubeconfig yet?

**Comment by mikedanese** [comment]
ref #30395

**Comment by ncdc** [comment]
Upon further reflection, I don't think we need a new api group for this. We just need a common package that component configuration api groups (kubeproxy, scheduler, etc) can import and use.

**Comment by luxas** [comment]
@ncdc Go for it :smile:!
This would be something like metav1 for kubeconfigs, right?

**Comment by guangxuli** [comment]
@ncdc What's progress about creating a common package that put the common configuration? Need i start this work.

**Comment by ncdc** [comment]
@guangxuli sorry for the delayed response - I've been battling the flu.

We need to decide where to put it. Something like `pkg/configapi` maybe? I'm also wondering about how we deal with conversions between api versions for the actual config apis like kubeproxy. If we do this, ideally we'd just have a single package that has the common structs, and that could be referenced by both the internal and versioned component config api packages.

@liggitt do you have any recommendations?

**Comment by guangxuli** [comment]
@ncdc that's ok, pay attention to your health.

**Comment by luxas** [comment]
This has been fixed, we just forgot to close it. Good that the bot now closed it :+1:
