### ISSUE TITLE
Node still marks as ready when running out of processes

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#54313]
xref https://github.com/kubernetes/test-infra/issues/4892#issuecomment-337113390: So when node ran out of processes, the pod goes into crashloop, however node is still marked as ready and trying to restart the pod.

https://github.com/kubernetes/kubernetes/issues/43783 is related, but I think the node probably still need to be marked as unready and stop schedule pods there.

k8s version: 1.7.6 on gke

cc @yujuhong @dashpole 
/sig node

**Comment by k82cn** [comment]
I think `kubelet` should get the max process number from OS, and report it as a resources (we already has pod number configure for pod). We need to reserved some for system daemons.

**Comment by vishh** [comment]
I do not think pids should be a resource. Instead kubelet (or NPD) can expose lack of available pids (similar to inodes). 
Pids is not a resource users will understand how to use. Many users do not even understand how to use CPU and memory effectively.

**Comment by krzyzacy** [comment]
@vishh I think at least we should not schedule pods onto the node without enough pids

**Comment by BenTheElder** [comment]
> @vishh I think at least we should not schedule pods onto the node without enough pids

I just had a discussion about this with @dashpole, it would be great to have some mitigation for this.

**Comment by k82cn** [comment]
> I do not think pids should be a resource. Instead kubelet (or NPD) can expose lack of available pids (similar to inodes).

Great, so maybe report it as `PIDPressureNodeCondition`; and taint node by NodeController. @vishh , does that make sense? I can help on that :).

**Comment by vishh** [comment]
Yeah, adding a NodeCondition SGTM.

**Comment by WIZARD-CXY** [comment]
>Great, so maybe report it as PIDPressureNodeCondition; and taint node by NodeController. @vishh , does that make sense? I can help on that :).
Interesting, I can lend some help too.

**Comment by k82cn** [comment]
> Yeah, adding a NodeCondition SGTM.

Great, working on that :). 

@WIZARD-CXY , let me think about how to add it, may need your help :).

**Comment by k82cn** [comment]
List tasks here:
- [ ] Report PID pressure condition (https://github.com/kubernetes/kubernetes/pull/57136)
- [ ] Taint nodes for PID pressure
- [ ] Update related docs for PID pressure

**Comment by k82cn** [comment]
/close

All related tasks are done :)
