### ISSUE TITLE
Make networkpolicy e2e helper methods publicly accessible

### ISSUE THREAD

**Issue by ozdanborne** [kubernetes/kubernetes#54322]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/sig testing
/kind feature

**What happened**:

I'm writing e2e tests for Kubernetes that I do not plan to check into the Kubernetes repository. They test special cases of Calico-specific features so it would not make sense for them to get checked into the upstream Kubernetes repo.

I've managed to import most of the necessary testing libraries from Kubernetes into my code, but I am unable to 
access any of the [unexported helper methods for networking tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/network_policy.go#L316-L539).

**What you expected to happen**:

I'm wondering if my approach is valid, or if there is another way to write external kubernetes e2e tests.

I see a few solutions here.

1. Fork the entire Kubernetes repo and add my tests to the e2e package. I'd prefer not to do this as I'd then have to manage rebases and merges instead of managing vendor dependencies.
2. Copy the methods I need into my own tests. I'd prefer not to do this as it duplicates code.
2. Export the methods I need so that my tests can use them.
3. Export the methods I need and move them out of the e2e package and into a more appropriate helper package (like `framework` or a new `network_utils` package maybe?)

The methods I need include `cleanupNetworkPolicy`, `createNetworkClientPod`, `cleanupServerPodAndService`, `createServerPodAndService`, `testCannotConnect`, & `testCanConnect`.

I'm of course willing to implement this change but wanted to discuss the best approach first.

cc (I think): @cmluciano @pipejakob @danwinship

**Comment by danwinship** [comment]
Those functions are internal implementation details of the NetworkPolicy test, not generic utilities. There's no expectation that the test will continue to use those particular methods as opposed to similar-yet-slightly-different ones in a future release.

I'd say you should just copy+paste.
