### ISSUE TITLE
Nodes behind NAT not starting

### ISSUE THREAD

**Issue by mliker** [kubernetes/kubernetes#54337]
I have a hetzner vserver with a static private IP of 172.31.1.100 which is 1:1 NAT'ed from its external internet routable IP. When the node registers itself with the master it exposes its private IP which is not routable from a master even though nodename is set to a resolvable fqdn resolving to its external ip. When i manually set nodeIP to its external internet routable ip the node fails to start with the following error: 

```
Oct 20 11:45:16 n2 origin-node: W1020 11:45:16.882798    9085 kubelet_node_status.go:934] Failed to set some node status fields: failed to validate nodeIP: Node IP: "x.x.x.x" not found in the host's network interfaces
```

I tracked this error down to
https://github.com/kubernetes/kubernetes/blob/48da128d83a3a1dd94e4bcc1bfec997c23138a93/pkg/kubelet/kubelet_node_status.go#L1004

One workaround i applied and seems to be working is to set an ip alias on the node using the external ip but this is too hackish and in my opinion wrong.

Is the above scenario supported in any way?

openshift origin rpm: origin-node-3.6.0-1.0.c4dd4cf
kubernetes: 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-02T21:42:22Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

@kubernetes/sig-node-bugs

**Comment by alvaroaleman** [comment]
Yeah, this is definitely annoying. Is there a reason why the kubelet can't just emit a warning but take the locally unbound IP anyways?

**Comment by vfreex** [comment]
I'll take a look at this issue.

**Comment by alvaroaleman** [comment]
This fixes the issue but will most likely make lots of unit tests fail:

```
@@ -992,6 +992,7 @@ func (kl *Kubelet) defaultNodeStatusFuncs() []func(*v1.Node) error {
 
 // Validate given node IP belongs to the current host
 func (kl *Kubelet) validateNodeIP() error {
+       return nil
        if kl.nodeIP == nil {
                return nil
        }
```

**Comment by vfreex** [comment]
Using `--hostname-override=external-ip` arguments for `kubelet` works fine in my local testing environment.
Could you help verify this approach?

**Comment by alvaroaleman** [comment]
Well that works fine but has the obvious disadvantage that now the node has its ip as name. Is there a reason why `--node-ip`  must be an address bound to the node?

**Comment by thockin** [comment]
Would another (simpler) solution here be to simply add the NAT IP as a "local" IP (e.g. setting it on a local interface) so that validation would succeed?

**Comment by kaikash** [comment]
up

**Comment by AkihiroSuda** [comment]
For the record, the following steps worked for me:

- Add `--node-ip=${PUBLIC_IP}` to `KUBELET_EXTRA_ARGS`
https://github.com/rootless-containers/usernetes/blob/gen2-v20230906.0/Dockerfile.d/u7s-entrypoint.sh#L4-L5

- Add the "public" IP to eth0
```
ip addr add "${PUBLIC_IP}" dev eth0
```
https://github.com/rootless-containers/usernetes/blob/gen2-v20230906.0/Dockerfile.d/u7s-entrypoint.sh#L7-L9

- For Flannel, append `--public-ip=${PUBLIC_IP}` to the flags of `flanneld`
https://github.com/rootless-containers/usernetes/blob/gen2-v20230906.0/Dockerfile.d/u7s-entrypoint.sh#L12-L16


- Run `kubeadm` with the following config
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "${PUBLIC_IP}"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "${PUBLIC_IP}:6443"
```
https://github.com/rootless-containers/usernetes/blob/gen2-v20230906.0/kubeadm-config.yaml#L2-L13

- - -


However, I feel `ip addr add "${PUBLIC_IP}" dev eth0` is weird and I'd like to see this issue to be revisited again.

**Comment by danwinship** [comment]
> I have a hetzner vserver with a static private IP of 172.31.1.100 which is 1:1 NAT'ed from its external internet routable IP. When the node registers itself with the master it exposes its private IP which is not routable from a master

So, given #42125, this would be solvable with `kube-apiserver --kubelet-preferred-address-types ExternalIP,InternalIP`

**Comment by thockin** [comment]
> When the node registers itself with the master it exposes its private IP which is not routable from a master

This is not uncommon.  There are plenty of environments where this is true, and in fact there's an explict API for the control planes to talk back to nodes: https://github.com/kubernetes-sigs/apiserver-network-proxy

The downside of using the public IP is that you can end up sending traffic out the NAT and back in when you do node-to-node traffic.

**Comment by qabpea** [comment]
@danwinship @thockin I can see how what you suggest works for the API server. What about communication to and from PODs? Use a CNI that is smart enough to tunnel the traffic between the nodes?

**Comment by thockin** [comment]
It was not stated, but I assumed that nodes are on the same private network.  If that's not true, then it is more complicated.
