### ISSUE TITLE
Kubeadm E2E test using weave-net is broken with CNI version bump

### ISSUE THREAD

**Issue by medinatiger** [kubernetes/kubernetes#54330]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Kubeadm E2E test is currently broken due to the commit https://github.com/kubernetes/kubernetes/pull/51250. I report the same issue on my local cluster. If I revert PR 51250, everything works fine. We believe the current weave-net plugin doesn't work with the CNI version change.

Right now all kubeadm related development is blocked on this. Could we consider reverting this change from head until we figure out what's wrong in weave-net/CNI? 

More context in https://github.com/kubernetes/kubernetes/issues/54180

**Comment by medinatiger** [comment]
@kubernetes/sig-cluster-lifecycle-bugs 
@luxas 
@pipejakob

**Comment by luxas** [comment]
Please reopen this in kubernetes/kubeadm. There is an issue as e2e tests & PR job are failing, but locally the CNI bit seem to work for me, so I think it has something with building the debs to do.

> Right now all kubeadm related development is blocked on this

Not technically. We just don't have any coverage right now.

> Could we consider reverting this change from head until we figure out what's wrong in weave-net/CNI?

Not IMO. We just need to forward-fix the issue.

Closing this; you can reopen in kubernetes/kubeadm

**Comment by medinatiger** [comment]
@luxas, kubeadm e2e test still red. Do you have any progress or hint in terms how to fix it forward? Just to clarify, If I install k8s and kubeadm locally using deb, I can repro the issue on my test box. I could believe it's sth wrong with debs. In the meantime, CNI and plug-in like weave-net change is a big deal. We clearly didn't test it thoroughly for this PR. Reverting the change seems to be the clean solution.

**Comment by dixudx** [comment]
@medinatiger FYI kubernetes/release#446 bumps new CNI releases for deb/rpm packages.

**Comment by medinatiger** [comment]
@dixudx Thanks.

**Comment by cmluciano** [comment]
@dixudx Is this the fix needed to fix these tests?

**Comment by pipejakob** [comment]
@cmluciano I actually think that https://github.com/kubernetes/release/pull/446 will take us in the other direction. During the kubeadm e2e tests, we use the deb packages built by bazel. During our official release process, we use the debs built by anago (in the release repo). Bumping CNI in our bazel build broken our e2e tests. Bumping CNI in the release repo scripts will similarly break our official release builds as well.

If I understand the problem correctly, the only way to fix both of them is for the CNI *providers* like weave-net to be updated to handle the changes of upgrading CNI to 0.6.0.

**Comment by medinatiger** [comment]
I think this issue worth some more discussion. Re-open the case as it might not be affecting kubeadm only

**Comment by medinatiger** [comment]
sorry, i cannot reopen the issue as it's closed by @luxas. But let's continue to discuss the option here.

**Comment by dixudx** [comment]
> Is this the fix needed to fix these tests?

@cmluciano Yes, I think so

**Comment by luxas** [comment]
This will be fixed by https://github.com/kubernetes/kubernetes/pull/54573; @medinatiger this was due to the CNI binaries being extracted in the wrong place.

**Comment by medinatiger** [comment]
@luxas nice find!
