### ISSUE TITLE
kubectl cluster-info reports cluster is running when it is not

### ISSUE THREAD

**Issue by thedrow** [kubernetes/kubernetes#54349]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`kubectl cluster-info` reports that the cluster is running and returns exit code 0.
`kubectl cluster-info dump` correctly identifies that the cluster is not running and exists with exit code 1.

**What you expected to happen**:
`kubectl cluster-info` should fail when the cluster is not running.

**How to reproduce it (as minimally and precisely as possible)**:
Start and stop a kubernetes cluster using minikube and then type kubectl cluster-info.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: Local
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux Ubuntu16-HP-800 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: snap for kubectl. minikube local for k8s.
- Others:

**Comment by dims** [comment]
@kubernetes/sig-cli-bugs
