### ISSUE TITLE
Creating services with global IPs on GCP fails

### ISSUE THREAD

**Issue by Thermi** [kubernetes/kubernetes#54340]
**/kind** bug

**What happened**:
Kubernetes errors out, instead of creating an LB with the global IP

**What you expected to happen**:
That Kubernetes creates an LB with the global IP and points it at the nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Try to use a global IP in a service on GCP.

Kubernetes events:
```
2017-10-21 17:50:08 +0200 CEST   2017-10-21 17:48:45 +0200 CEST   5         traefik-ingress-lb-global.14efa08c9635a1b9   Service             Normal    CreatingLoadBalancer   service-controller   Creating load balancer
2017-10-21 17:50:10 +0200 CEST   2017-10-21 17:48:47 +0200 CEST   5         traefik-ingress-lb-global.14efa08d03ab078b   Service             Warning   CreatingLoadBalancerFailed   service-controller   Error creating load balancer (will retry): Failed to create load balancer for service default/traefik-ingress-lb-global: requested ip 35.201.103.46 is neither static nor assigned
to LB a5271bdeeb67711e7b13d42010a8400e(default/traefik-ingress-lb-global): <nil>
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+0b9efaeb34a2f", GitCommit:"638b0a06d928e7a12fa29bb12610158a235585d7", GitTreeState:"dirty", BuildDate:"2017-10-02T09:48:25Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GP
- Install tools: GKE

**Comment by cblecker** [comment]
Global IPs are for the [HTTP Layer 7 Load Balancer](https://cloud.google.com/container-engine/docs/tutorials/http-balancer) in GCE/GKE. You need to use an ingress resource to provision them. If you're looking for [TCP Layer 4 Load Balancer](https://cloud.google.com/container-engine/docs/tutorials/configuring-domain-name-static-ip#step_2a_using_a_service) via a Service, you must create a static regional IP instead.

---
/kind support
/area platform/gke
/close

**Comment by Thermi** [comment]
What you are writing is only partially true. It is possible to use global IPs for TCP and UDP load balancers. However, the possible ports are predefined. I'd expect that to work.
