### ISSUE TITLE
Add documentation to Dynamic Persistent Volumes about DefaultStorageClass admission control

### ISSUE THREAD

**Issue by danbopes** [kubernetes/kubernetes#54369]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I went to the [documentation page](), and read about dynamic provisioning. A default class was set, but the DefaultStoreClass admission plugin wasn't enabled, and I spent several hours searching as to why my pvc's weren't auto provisioning. 

**What you expected to happen**:
I would have liked to have seen more documentation mentioning that the Admission Plugin is required for dynamic provisioning, with a link [here](https://kubernetes.io/docs/admin/admission-controllers/#defaultstorageclass).

**Comment by tengqm** [comment]
please close this one and open another issue in kubernetes/website project.
