### ISSUE TITLE
Pod scheduling not respecting PVC zone (NoVolumeZoneConflict)

### ISSUE THREAD

**Issue by greenboxal** [kubernetes/kubernetes#54370]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig scheduling

(Not sure about the correct SIG)

**What happened**:

After migrating (or creating a new cluster) to 1.8, pods aren't getting assigned only to nodes in the same zone as its PVCs.

**What you expected to happen**:

Pods with a PVC should only be scheduled at nodes within the same zone.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start a new cluster in AWS (not sure if affects other cloud providers)
2. Add nodes in multiple availability zones (e.g.: us-west-2a, us-west-2b, us-west-2c)
3. Create a stateful set with dynamic PVC provisioning through AWS EBS. Also, add a topology anti-affinity to ensure that the pods will get spread between nodes

After this, the first pod will start correctly, but the second will fail to start as it will _probably_ be scheduled in the wrong availability zone. I'm saying `probably` because this behavior seems to have some randomness in it. I tried deleting the failing pod a couple times and sometimes I got lucky and the pod was scheduled in the correct zone.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Arch Linux
- Kernel (e.g. `uname -a`): Linux ip-10-0-50-163 4.12.10-1-ec2 #1 SMP Fri Sep 1 22:37:26 PDT 2017 x86_64 GNU/Linux
- Install tools: Custom Cluster from Scratch
- Others:

**Comment by k82cn** [comment]
@greenboxal , would you help to share pod, PVC yamls?

**Comment by greenboxal** [comment]
@k82cn here is it: https://gist.github.com/greenboxal/f360991e4c6ee6130c6655ec9e8287a2

The storage class is just a GP2 EBS.

**Comment by jakexks** [comment]
+1

The first pod in the statefulset works correctly. The second pod always gets scheduled in the incorrect zone for the volume.
```
AttachVolume.Attach failed for volume "pvc-d55479d3-c3d5-11e7-b334-0a1686dec4b4" : Error attaching EBS volume "vol-0cc689cf71b5c4148" to instance "i-0dee75d43c0299fd6": "InvalidVolume.ZoneMismatch: The volume 'vol-0cc689cf71b5c4148' is not in the same availability zone as instance 'i-0dee75d43c0299fd6'\n\tstatus code: 400, request id: 866aa429-a936-4468-b502-1486e075a969```

**Comment by msau42** [comment]
Can you paste your PV output so we can see the zone labels?

@kubernetes/sig-storage-bugs

**Comment by dodwyer** [comment]
@msau42 following up for @jakexks 

```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: aws-ebs-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    creationTimestamp: 2017-11-07T21:50:32Z
    labels:
      failure-domain.beta.kubernetes.io/region: us-east-1
      failure-domain.beta.kubernetes.io/zone: us-east-1e
    name: pvc-ad7289ca-c405-11e7-b40d-129decda85fc
    namespace: ""
    resourceVersion: "1042119"
    selfLink: /api/v1/persistentvolumes/pvc-ad7289ca-c405-11e7-b40d-129decda85fc
    uid: add46281-c405-11e7-b40d-129decda85fc
  spec:
    accessModes:
    - ReadWriteOnce
    awsElasticBlockStore:
      fsType: ext4
      volumeID: aws://us-east-1e/vol-0302be0d4c6d83144
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-cassandra-cassandra-0
      namespace: cassandra
      resourceVersion: "1042109"
      uid: ad7289ca-c405-11e7-b40d-129decda85fc
    persistentVolumeReclaimPolicy: Delete
    storageClassName: default
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubernetes.io/createdby: aws-ebs-dynamic-provisioner
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    creationTimestamp: 2017-11-07T21:52:40Z
    labels:
      failure-domain.beta.kubernetes.io/region: us-east-1
      failure-domain.beta.kubernetes.io/zone: us-east-1f
    name: pvc-f9bf0013-c405-11e7-b40d-129decda85fc
    namespace: ""
    resourceVersion: "1042394"
    selfLink: /api/v1/persistentvolumes/pvc-f9bf0013-c405-11e7-b40d-129decda85fc
    uid: fa2eb112-c405-11e7-b40d-129decda85fc
  spec:
    accessModes:
    - ReadWriteOnce
    awsElasticBlockStore:
      fsType: ext4
      volumeID: aws://us-east-1f/vol-01f7f95df1c83f427
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: data-cassandra-cassandra-1
      namespace: cassandra
      resourceVersion: "1042385"
      uid: f9bf0013-c405-11e7-b40d-129decda85fc
    persistentVolumeReclaimPolicy: Delete
    storageClassName: default
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by dodwyer** [comment]
This can be recreated by deploying the standard Cassandra Helm chart on a 1.8.2 k8s cluster. 

`helm install --namespace "cassandra" --set persistence.storageClass=default -n "cassandra" incubator/cassandra`

using the storageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: default
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1d, us-east-1e, us-east-1f
```

**Comment by msau42** [comment]
@dodwyer do your nodes also have the same zone label on them?

**Comment by dodwyer** [comment]
@msau42 here you go:

```
NAME                          STATUS    AGE       VERSION   EXTERNAL-IP   OS-IMAGE                                       KERNEL-VERSION   LABELS
ip-10-37-0-183.ec2.internal   Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=ip-10-37-0-183,kubernetes.io/role=worker
ip-10-37-0-51.ec2.internal    Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/hostname=master0,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-10-37-1-51.ec2.internal    Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1b,kubernetes.io/hostname=master1,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-10-37-3-100.ec2.internal   Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1d,kubernetes.io/hostname=ip-10-37-3-100,kubernetes.io/role=worker
ip-10-37-4-113.ec2.internal   Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1e,kubernetes.io/hostname=ip-10-37-4-113,kubernetes.io/role=worker
ip-10-37-5-19.ec2.internal    Ready     6d        v1.8.2    <none>        Container Linux by CoreOS 1576.1.0 (Ladybug)   4.13.9-coreos    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1f,kubernetes.io/hostname=ip-10-37-5-19,kubernetes.io/role=worker
```
We have a node available in the zone the PV is created within but the Pod is created on a different node in another zone.

**Comment by jakexks** [comment]
We rolled back to 17 and it works as expected, so this is definitely a bug in 1.8

**Comment by msau42** [comment]
@jakexks @dodwyer can you verify that you are using the default kubernetes scheduler, with the default scheduler policy?

**Comment by verult** [comment]
What are your node taints?

**Comment by msau42** [comment]
We are unable to reproduce the problem.  Please check your scheduler configuration and that you've enabled the VolumeZone predicate (it should be enabled if you're using the default scheduler).

**Comment by jakexks** [comment]
We don't do anything clever with our scheduler configuration, it's here: https://gist.github.com/jakexks/6d2ebb328b3ca14b35c22c3255f25fea

Are there any more logs I can provide? I'll try to do some more investigation, but identical config (with the hyperkube image rolled back to 1.7.10) schedules correctly

**Comment by jakexks** [comment]
Our master nodes have
```
Taints:             node-role.kubernetes.io/master:NoSchedule
```
Our worker nodes are untainted.

Example kubectl describe node: https://gist.github.com/jakexks/5e8bad5e28a76333cca069f22be249c2

**Comment by msau42** [comment]
Hm the predicate itself doesn't have much extra logging.  Only this potential [warning](https://github.com/kubernetes/kubernetes/blob/dd9981d038012c120525c9e6df98b3beb3ef19e1/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L511).  Maybe you can bump up your log level to 4 and see if you see that printed.

If that doesn't come up with anything useful, then we'll need to get help from someone that can debug in the AWS environment.  (We tested in gce and it's working)

**Comment by jakexks** [comment]
I bumped the log level to 4, and for my own interest, added more debug output to the scheduler:
https://github.com/jakexks/kubernetes/commit/e7a682dde6a60f9ae51904effe242e3858de4e67

I've attached everything you should need to reproduce this on AWS in this gist, including the output of the scheduler (with the leader election spam removed): https://gist.github.com/jakexks/56f9703b28e958b3f435af14ad760a55

Of particular interest to me is the fact that lines like
```
I1110 17:14:25.022358       5 predicates.go:1433] VolumeNode predicate allows node "ip-10-39-0-98.ec2.internal" for pod "cassandra-cassandra-0" due to volume "pvc-f74642a7-c639-11e7-9644-12d2abc93736"
```
appear in the scheduler log for the 1st (or "0") replica, which is the one that is scheduled correctly.

However, the second replica doesn't appear to hit any of those checks, and gets assigned to the wrong node. It's 100% reproducible in AWS from my side.

Succesfully scheduled pod: https://gist.github.com/jakexks/56f9703b28e958b3f435af14ad760a55#file-scheduler-log-L77

Unsucessfully scheduled pod: https://gist.github.com/jakexks/56f9703b28e958b3f435af14ad760a55#file-scheduler-log-L99

**Comment by msau42** [comment]
Thanks so much for taking the time to help debug!  Here's my thoughts on your logs:
- You can ignore the VolumeNode predicate messages.  Those are related to a new feature for specifying NodeAffinity on the PV, and is not applicable to EBS volumes yet.  EBS volumes should only care about the VolumeZone predicate.
- It seems like the volume zone predicate is either not being called on the second pod, or is exiting early before your added print statements.  Could you try adding a log at the beginning of the message, and any early exit points?

**Comment by jakexks** [comment]
I added more Printf debugging whenever the predicate is entered, and before any possible "return true" exits: https://github.com/jakexks/kubernetes/commit/0ca7c532567d8262d7966ca38e774708323d827c

This resulted in the following scheduler log:
https://gist.github.com/jakexks/c95abbddfe71bae306f48e1502a26b57

Kubernetes never even checks the predicate for the second pod (which is bizarre!)

Any ideas?

**Comment by msau42** [comment]
Can @kubernetes/sig-scheduling-bugs help look into this?  It seems like the predicates for the 2nd pod are not run for some reason.

**Comment by bsalamat** [comment]
@jakexks From the logs you posted, it looks like `EnableEquivalenceClassCache` is set to true. Have you tried disabling the equivalence cache by setting `EnableEquivalenceClassCache:false` (or just not enabling it) and see if you still see the same problem of the predicate not being called for the second pod?

**Comment by resouer** [comment]
I will take a look at this. It seems after 1.8 the newly added volume predicate affects equivalence class cache.

**Comment by msau42** [comment]
@resouer  The change in #56577 should be backported to 1.8 to fix this issue.  You'll have to replace VolumeBind predicate with NoVolumeNodeConflict.

**Comment by jakexks** [comment]
Just to follow up, removing the `AllAlpha=true` feature gate from our scheduler config (which disabled `EnableEquivalenceClassCache`) did solve it! Thanks for everyone's help.

**Comment by resouer** [comment]
@msau42 @jakexks Yes, so I will send out a cherry pick up the fix to in 1.8

**Comment by emwalker** [comment]
@jakexks I'm running into this issue as well.  Can you elaborate a little on your workaround?

**Comment by msau42** [comment]
@emwalker in your cluster bringup, you should not enable the `EnableEquivalenceClassCache` feature gate for the kube-scheduler.  If you're passing in the feature gate `AllAlpha=true`, that automatically expands to all features, including the equivalence cache, so you need to remove that too.

**Comment by srflaxu40** [comment]
I'm seeing this issue using KOPS with kops v1.8 am I SOL?

**Comment by dodwyer** [comment]
@srflaxu40 can you provide your kube-scheduler start-up parameters here?

**Comment by resouer** [comment]
@srflaxu40 One possible issue is related to `AllAlpha=true`, could you please check that? Also, the fix has been cherry picked to 1.8 last month, so upgrade your cluster to latest version will probably fix it.

**Comment by vjdhama** [comment]
I am seeing the same issue with kops v1.8.

Scheduler params:

```
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-scheduler --kubeconfig=/var/lib/kube-scheduler/kubeconfig
      --leader-elect=true --v=2 2>&1 | /bin/tee -a /var/log/kube-scheduler.log
    image: gcr.io/google_containers/kube-scheduler:v1.8.6```

**Comment by msau42** [comment]
Hi @vjdhama I think your issue is different.  Currently, dynamic provisioning doesn't understand that multiple volumes are related to one pod very well.  To get around this issue, you can either:
- set your StorageClass to restrict the zones
- use a statefulset for your pods.  The volume provisioner does have special logic to handle pvcs created by statefulsets

The fix for the underlying issue is being worked on, but will take a few more releases.  Detailed discussion here https://github.com/kubernetes/kubernetes/issues/41598

**Comment by msau42** [comment]
Let's use https://github.com/kubernetes/kubernetes/issues/49906 to discuss issue of scheduler and dynamic provisioning coordination.

The original reported problem of StatefulSets not being correctly scheduled in 1.8 alpha clusters has been fixed.
/close
