### ISSUE TITLE
[Proposal] Stub Device Plugin for E2E Test

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/kubernetes#54412]
# Stub Device Plugin for E2E Test

Kubernetes now supports `Device Plugin` in v1.8.0, but it is still an `Alpha` feature. We need to build stub Device Plugin for e2e test to stabilize this feature.

# Requirements

The stub approach of Device Plugin should:

- Ensure a consistent and reliable behavior of Device Plugin
- Be flexible to use and easy to config
- Be OS independent to run on most test environment

# Objectives

1. Build a stub device plugin framework for e2e test:
    * Read devices info from configuration files
    * Auto advertise these devices to kubelet by `Register` API
    * Implement `ListAndWatch` interface to update devices' states to kubelet
    * Add an easy approach to Add/Delete/Update devices online without restarting
    * Add a timer for auto start/shutdown
    * Leave a file for recording test result
2. Give some guideline with example to setup this stub device plugin framework.

# Non Objectives

# Design Details

## StubManager and StubWorker

The architecture of this stub framework is similar to `Master/Slave` model, there are one `StubManager` (with test config file) and some `StubWorker`s (with dummy device file):

**StubManager:**

Responsible for scheduling test processing:
- Watch changes of `config file`, and update device states into `dummy device file` on each node
- Launch `StubWorker` (DaemonSet) and `Pod` which will requests these devices
- Maintain test processing, such as simulating a Device failure

![StubManager](https://user-images.githubusercontent.com/5319646/31885223-558f1b64-b822-11e7-9831-e14025c09957.png)

**StubWorker:**

- A running stub device plugin instance which is deployed by `DaemonSet`
- Responsible for watching changes of `dummy device file`, then update devices' states to kubelet

![StubWorker](https://user-images.githubusercontent.com/5319646/31885231-5cb9d956-b822-11e7-85fe-44c3cebe408a.png)

## Device Representation

As mentioned above, devices info saved in a `config file`. `StubManager` will read this file to do some pre-test work, such as creating `dummy device files` on each node, launching `DaemonSet` with node selector if needed:

```
{
    "Nodes": [
        {
            // for node selector if needed.
            "NodeName": "stub-node-1"
            // SSH info.
            "SSH": "test:pwd@192.168.1.100",
            // timer will passed into DaemonSet by ENV setting,
            // in seconds, sleep 5 seconds then start this stub device plugin.
            "StartTimer": 5,
            // in seconds, start 10 minutes then shutdown this stub device plugin.
            "ShutDownTimer": 600,
            "Devices": [
                    {
                        "ID": "Stub-Device-1",
                        "State": "Healthy",
                        "Path": "/tmp/stub-device-1",
                        "Env": {
                            "Stub1": "stub1",
                        },
                    },
                    {
                        "ID": "Stub-Device-2",
                        "State": "Healthy",
                        "Path": "/tmp/stub-device-2",
                    },
                    {
                        "ID": "Stub-Device-3",
                        "State": "Unhealthy",
                        "Path": "/tmp/stub-device-3",
                    },
                    ...
                ],
        },
        {
            "NodeName": "stub-node-2",
            "SSH": "test:pwd@192.168.1.101",
            // if there is no timer specified, this device will launch immediately, and keep running.
            "Devices": [
                    {
                        "ID": "Stub-Device-1",
                        "State": "Healthy",
                        "Path": "/tmp/stub-device-1",
                        "Env": {

                        },
                    },
                    {
                        "ID": "Stub-Device-2",
                        "State": "Healthy",
                        "Path": "/tmp/stub-device-2",
                    },
                    {
                        "ID": "Stub-Device-3",
                        "State": "Unhealthy",
                        "Path": "/tmp/stub-device-3",
                    },
                    ...
                ],
        },
        ]
}
```

## Device Allocation Simulation

We need a `dummy device file` for allocation simulation, such as `/tmp/stub-device-1` `/tmp/stub-device-2`, so a stub device plugin could touch this file to claim that it is allocated. It is also returned to kubelet in `DeviceRuntimeSpec`  of `AllocateResponse`.

Also, we can echo string "Healthy"/"Unhealthy" into this file to represent this device is ok or not.

`StubWorker` will watch these files, and will update state to kubelet through the `ListAndWatch` API.

## Test Processing Definition

`StubManager` will watch the changes of config file, then ssh to `Node` and update `dummy device file`, so `StubWorker` will catch this changes.

We can define a custom test processing:

- Define the number of device plugins to be launched
- Deploy `Pods` to request these devices
- Set a device to unhealthy by changing config file

**Pre-Test**

In this phase, `StubManager` will ssh to every node to create dummy device file, which is defined in the `config file` as showed above.

**Device Plugin Initialization**

After dummy device files are created, `StubWorker` will:

- Read these files from `/tmp/` folder
- Do regular expression to get capacity of this device
- Get timer settings from ENV
- Sleep if needed then call `Register` API with this device name and capacity

**Create Pod to Request Devices**

After devices are registered, `StubManager` will deploy some Pods to request these devices to validate [Allocate()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/device_plugin_handler.go#L162) and [GetResources()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L617) interfaces.:

- Should wait here until all Pod succeeded
- Report error if any one pod fails

Of course, we can also delete a Pod to release device which is allocated to this Pod.

**Error Handling**

We should simulate an error case to test device deletion:

- Inject errors by changing config file
- `StubManager` caches these changes, then updates dummy device file on node
- `StubWorker` (Device Plugin endpoint) caches that some devices fail, then reports to Kubelet
- Kubelet will delete these devices

Opening this issue for discussion/suggestions, @jiayingz @vishh PTAL.

**Comment by jiayingz** [comment]
Thanks a lot for opening this issue, @ScorpioCPH 

I think when we discussed the need for a device plugin stub, the main motivation is to test kubernetes device plugin support in vendor independent and os independent ways. The implementation of the device plugin stub is expected to live in the kubernetes repository. With these in mind, I would suggest we start with something simple, and describe the concrete kubernetes behaviors we want to test through the device plugin stub. The master/worker model seems complicated and I am not sure the benefits from this complexity. Please let me know if I mis-understood the scope of this work. Thanks!

**Comment by ScorpioCPH** [comment]
@jiayingz Hi, leaving stub device plugin for e2e in the kubernetes repository is good to me.

The main idea of this proposal is `dummy device file`, which is responsible for `device representation`, so we can achieve vendor independent and os independent.

I think we can start with this and make one small step forward:
- implement `StubWorker` for e2e test with `dummy device file`.
- deploy some Pods to request these dummy devices to validate kubernetes behaviors.

WDYT?

**Comment by jiayingz** [comment]
+1 for starting with something simple. We can implement a simple stub first that we may use to test the similar functionality as the existing device plugin e2e test and e2e_node test do, and then see how we may extend the stub to test more things.

**Comment by ScorpioCPH** [comment]
PR for this proposal is here: https://github.com/kubernetes/kubernetes/pull/54792
