### ISSUE TITLE
[job failure] ci-kubernetes-e2e-gke-device-plugin-gpu failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#54429]
/priority failing-test
/priority critical-urgent
/sig scheduling
/area hw-accelerators

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gke-device-plugin-gpu has been failing since 2017-10-19
- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/289
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/290

I suspect https://github.com/kubernetes/kubernetes/pull/53031 caused this

This job in on the release-master-blocking dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22).  Is there work ongoing to bring this job back to green?

**Comment by spiffxp** [comment]
fyi @kubernetes/sig-scheduling-test-failures since you're [listed as the owning sig for this job](https://github.com/kubernetes/test-infra/blob/63c78503b8d644a28bb2c329548ecd030d93e3b2/jobs/config.json#L5646)

fyi @kubernetes/sig-node-test-failures since I think this was the sig label on the PR I suspect caused this

**Comment by bsalamat** [comment]
@jiayingz Is this expected?

**Comment by jiayingz** [comment]
Yes. We made a non-compatible API change in a recent PR on Kubernetes. Expect to resolve this soon after we update the device plugin side.

**Comment by jiayingz** [comment]
FYI, the test just turned green after Vish updated the device plugin side. I think we can close this bug now.

**Comment by bsalamat** [comment]
Thanks, @jiayingz!

**Comment by spiffxp** [comment]
/close
lgtm
