### ISSUE TITLE
POST request returns 422, possibly violating "Name Idempotency" 

### ISSUE THREAD

**Issue by kevintpeng** [kubernetes/kubernetes#54425]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Sending a POST request twice to the API to create a clusterIP service, whose address is fixed in the configuration, returns an HTTP 422 on the second request. The 422 response is complaining about the already consumed fixed IP address.

**What you expected to happen**:

Based on [Name idempotency](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#idempotency) from the docs, I'd expect that a service creation request should always return a 409 if the service already exists and it is a valid configuration file.

**How to reproduce it (as minimally and precisely as possible)**:

In an empty cluster (on something like the [interactive tutorial environment](https://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/)), run this command twice. The second one fails because of IP conflict (HTTP 422) rather than service name existence (HTTP 409).

```
$ echo "apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  clusterIP: 10.0.0.2
  ports:
    - port: 53
      protocol: TCP
" | kubectl create -f - -v 8
```

**Anything else we need to know?**:

**Environment**:
Running in the interactive tutorial.

- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lavalamp** [comment]
The code probably tries to grab the IP before writing the service, which is the step when the name idempotency is checked. The business logic here is probably

/sig networking
