### ISSUE TITLE
API server should return 40x instead of 500 for invalid patch

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#54423]
Currently the apiserver returns 500 if a patch request contains invalid patch, e.g., if you do `$ kubectl patch -f redis-master.yaml -p feafeczea`, and then check `kube-apiserver.log`, you will see 
```
logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"json: cannot unmarshal string into Go value of type map[string]interface {}\",\"code\":500}\n
```

The apiserver should either return a 422 (`NewInvalid`) or a 400 (`NewBadRequest`).

/kind bug
cc @kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Sounds right to me. Leaning towards 422.

**Comment by fraenkel** [comment]
This looks like a 400 not a 422 since its a malformed patch document.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/kubernetes/pull/54477.
