### ISSUE TITLE
Hyperkube doesn't support --experimental-dockershim for kubelet

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#54424]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kubelet has support for running in dockershim-only mode via a hidden flag named `--experimental-dockershim`, but this flag is ignored when kubelet is run using hyperkube binary, e.g. `./hyperkube kubelet --experimental-dockershim`.

**What you expected to happen**:
I expected `--experimental-dockershim` to have the same effect with hyperkube as it has with 'plain' kubelet binary.

**How to reproduce it (as minimally and precisely as possible)**:
Try to run kubelet in dockershim mode using hyperkube binary: `./hyperkube kubelet --experimental-dockershim` It'll start in normal mode instead.

**Anything else we need to know?**:
We use dockershim server for CRI Proxy part of [Virtlet](https://github.com/Mirantis/virtlet) project.
Virtlet is a CRI implementation for running VMs as pods, and thanks to that CRI proxy mechanism it's deployed as a DaemonSet itself. Unfortunately lack of `--experimental-dockershim` flag in hyperkube causes some deployment difficulties and as of now we have to import code from kubelet to run our own dockershim server.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1

I can fix this one myself if it's agreed that the change is useful.

**Comment by ivan4th** [comment]
@kubernetes/sig-node-bugs

**Comment by dims** [comment]
@ivan4th go for it. the debate can be on the PR :)
