### ISSUE TITLE
Is there no IP of kubernetes node?

### ISSUE THREAD

**Issue by dockerPractice** [kubernetes/kubernetes#54467]
NAME        STATUS      ROLES        AGE         VERSION
master      Ready         master         3h           v1.8.1
node1       Ready         <none>       3h           v1.8.1
node2       Ready         <none>       3h           v1.8.1

root@master:~/yml/1# kubectl get service
NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
kubernetes        ClusterIP   10.96.0.1     <none>        443/TCP          3h
my-service-name   NodePort    10.98.25.69   <none>        8080:30373/TCP   3m

I just wonder this, 'kubectl describe nodes | grep Addr'
As a result,

root@master:~/yml/1# kubectl describe nodes | grep Addr
Addresses:
Addresses:
Addresses:
Is there no IP of kubernetes node?

**Comment by dockerPractice** [comment]
즙딲즙딲

**Comment by juliohm1978** [comment]
Is you grep command line really filtering what you need? This is the output from kubectl on my system:

```
[...]

Addresses:
  ExternalIP:  172.31.134.91
  InternalIP:  172.31.134.91
  Hostname:    infra03-lab

[...]
```
So, grepping for "Addr" will give you the first line without any actual IP numbers.

**Comment by dockerPractice** [comment]
@juliohm1978 
I've learned that how to make service using 'kubectl create' command and then connect to service port from Web browser to show my service. So I have to find address about each node, but I can't...
How can I do it?

**Comment by juliohm1978** [comment]
I'm not sure why your setup does not show ExternalIP. My installation is on baremetal and this value is automatically populated with the node's public IP address. This might be related to your host setup and your cloud provider.

Off the top of my head, I would recommend making sure the host nodes have public IP addresses. They should be at least visible to other machines in the same network.
