### ISSUE TITLE
Deleting deployment sometimes leaves orphaned pod

### ISSUE THREAD

**Issue by cy490761462** [kubernetes/kubernetes#54471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/area controller-manager

**What happened**:
I use fabric kubernetes client v2.2.13 to delete deployment, but sometimes leaves orphaned pod.

**What you expected to happen**:
There should be no orphaned pod after a deployment is deleted

**How to reproduce it (as minimally and precisely as possible)**:
Just use fabric kubernetes client to delete on deployment. Sometimes this issue can be reproduced.

**Anything else we need to know?**:
Here is the log of controller manager when this issue is reproduced:
[podleft_bug_controller_manager.log](https://github.com/kubernetes/kubernetes/files/1410345/podleft_bug_controller_manager.log)

It seems like that deployment controller manager did not watch the event that deployment's replica number change to 0.
So deployment controller manager scales up the rs after the rs is scaled down.
I think there is bug in the logic of sync the deployment.
Could someone help see this issue? tks.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.4
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux hh-web-noah-api-s0002 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by cy490761462** [comment]
@sig-cluster-lifecycle-bugs

**Comment by grodrigues3** [comment]
@k8s-mirror-api-machinery-bugs

**Comment by grodrigues3** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by huaixichen** [comment]
I saw similar strange behavior in our environment as well. From logs point of view, it is hard to ping-pong whether it is a Fabric Java SDK issue or a Kubernetes scheduler issue...  From reproduction point of view, it is even harder, since I only saw it once in our production environment. 

Could anyone give my some sparks on this?

**Comment by oikomi** [comment]
hum, this issue also appears in our company's production environment, I'm collecting log information
, It seems to be a transactional error in controller manager.

**Comment by violalu** [comment]
It's better to try reproduce it with go client to exclude it's fabric jdk or kubernetes problem
