### ISSUE TITLE
Deleting a static pod will not reset it's restart count

### ISSUE THREAD

**Issue by roffe** [kubernetes/kubernetes#54476]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When deleting a static pod created from manifests in --pod-manifest-path it's restart count does not reset

**What you expected to happen**:
Pod to come up with restart count 0

**How to reproduce it (as minimally and precisely as possible)**:
```text
➜  ~ kubectl get po --namespace kube-system | grep apilb
kube-apilb-10.1.201.101                         2/2       Running   12         2m
kube-apilb-10.1.201.102                         2/2       Running   10         11d

➜  ~ kubectl delete po --namespace kube-system kube-apilb-10.1.201.101 && kubectl get po --namespace kube-system --watch | grep apilb
pod "kube-apilb-10.1.201.101" deleted
NAME                                            READY     STATUS    RESTARTS   AGE
kube-apilb-10.1.201.101               0/2           Pending    0                   0s
kube-apilb-10.1.201.101               2/2           Running    12                  3s
```

**Anything else we need to know?**:
I successfully reseted the restart count on one of these pods by doing the following:
- Stop kubelet on affected node
- Delete pod via kubectl with --force
- Delete related containers from Docker on host where Kubelet is stopped
- Restart Kubelet

**Environment**:
Kubernetes version (use `kubectl version`):
```text
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: `on-prem`
- OS (e.g. from /etc/os-release): `Container Linux by CoreOS stable (1520.6.0)`
- Kernel (e.g. `uname -a`): `Linux kubemaster01 4.13.5-coreos-r2 #1 SMP Thu Oct 12 03:21:09 UTC 2017 x86_64 Common KVM processor GenuineIntel GNU/Linux`
- Install tools: `manual deploy from own repo`
- Others:

**Comment by deads2k** [comment]
Static pods are owned by the kubelet.  The kubelet know the restart count locally and it also trusts the apiserver if the pod is present there.  I think this is behaving correctly.

**Comment by roffe** [comment]
I would like to contest that opinion. I have monitoring watching over the restart count and having to do this whole routin to reset the restart count is wrong.

**Comment by yujuhong** [comment]
@roffe is there a reason why you choose static pods over DaemonSets? The features static pods support are limited.

One issue I can think of is that kubelet generates the UID of the pod based on the manifest "content" (see #43420). That means you'd get the same UID even if you remove and re-add the manifest file in the directory. This makes tracking restart count locally on the node sticky (i.e., you'd have to remove the containers).

**Comment by roffe** [comment]
@yujuhong Thanks for the reply!

I run controller-manager, apiserver, kube-proxy & scheduler as static pod manifests on the master nodes. The first instructions i started with from CoreOS over a year ago did it this and it has worked well for me since.

The apilb pod is actually something needed before the apiserver is avail since it does loadbalancing of the apiserver calls on the node itself and the Kubelet is set to connect to this pod and not the apiserver.

I guess I could make a daemonset instead and drop into the manifest folder, should work just as well, havn't had any reason to change anything up until i ran into this.

**Comment by roffe** [comment]
It struck me now that a daemonset will not work since the apilb pods have different env variables on them to configure keepalived. I guess I will have to try to modify the keepalived image somehow to fit this, but that's offtopic

**Comment by roffe** [comment]
@yujuhong your advice was faulty. i cannot have daemonsets in static manifests
```
Can't process manifest file "/etc/kubernetes/manifests/kube-apilb.yaml": /etc/kubernetes/manifests/kube-apilb.yaml: couldn't parse as pod(invalid pod: &extensions.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apilb", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:extensions.DaemonSetSpec{Selector:(*v1.LabelSelector)(0xc4214eb5e0), Template:api.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-apilb"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:api.PodSpec{Volumes:[]api.Volume{api.Volume{Name:"kube-haproxycfg", VolumeSource:api.VolumeSource{HostPath:(*api.HostPathVolumeSource)(0xc4214eb7a0), EmptyDir:(*api.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*api.GitRepoVolumeSource)(nil), Secret:(*api.SecretVolumeSource)(nil), NFS:(*api.NFSVolumeSource)(nil), ISCSI:(*api.ISCSIVolumeSource)(nil), Glusterfs:(*api.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)(nil), RBD:(*api.RBDVolumeSource)(nil), Quobyte:(*api.QuobyteVolumeSource)(nil), FlexVolume:(*api.FlexVolumeSource)(
Oct 25 07:41:26 agi-cph-kubemaster01 kubelet-wrapper[19303]: E1025 07:41:26.601556   19303 file.go:149] Can't process manifest file "/etc/kubernetes/manifests/kube-apilb.yaml": /etc/kubernetes/manifests/kube-apilb.yaml: couldn't parse as pod(invalid pod: &extensions.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apilb", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:extensions.DaemonSetSpec{Selector:(*v1.LabelSelector)(0xc4217c8f00), Template:api.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-apilb"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:api.PodSpec{Volumes:[]api.Volume{api.Volume{Name:"kube-haproxycfg", VolumeSource:api.VolumeSource{HostPath:(*api.HostPathVolumeSource)(0xc4217c90c0), EmptyDir:(*api.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*api.GitRepoVolumeSource)(nil), Secret:(*api.SecretVolumeSource)(nil), NFS:(*api.NFSVolumeSource)(nil), ISCSI:(*api.ISCSIVolumeSource)(nil), Glusterfs:(*api.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)(nil), RBD:(*api.RBDVolumeSource)(nil), Quobyte:(*api.QuobyteVolumeSource)(nil), FlexVolume:(*api.FlexVolumeSource)(
```

**Comment by yujuhong** [comment]
> @yujuhong your advice was faulty. i cannot have daemonsets in static manifests

My advice was based on the information you gave BEFORE my last reply.

I was suggesting you to create a regular DaemonSet through the apisever. But since you need to have the pods running before the apiserver is up, using a DaemonSet is not possible.

**Comment by roffe** [comment]
@yujuhong thanks for clearing that. I hope #43420 gets implemented soon.

**Comment by roffe** [comment]
@antoinep92 the TL/DR; is that they don't want to implement it because it will restart all static pods when you deploy the fix.

I just gave up and learned to live with it....
