### ISSUE TITLE
DNS keeping old service entries

### ISSUE THREAD

**Issue by m-no-2017** [kubernetes/kubernetes#54486]
Short info:
- k8s v1.7.2 (soon going to v1.8.0)
- bare-metal
- OS: Ubuntu 16.04.03 LTS
- Kernel: 4.11 (lowlatency)

Kube-DNS image: <pre><code>gcr.io/google_containers/kubedns-amd64:1.9</code></pre>
Kube-DNSmasq image: <pre><code>gcr.io/google_containers/kube-dnsmasq-amd64:1.4</code></pre>
After I created some services (I'm speaking about the "holy trinity" heapster/grafana/influxdb) and changed their names, the old entries are still present on the DNS.

e.g. influxdb service

Current name,IP and namespace:
<pre><code>k8s-influxdb-rbac-svc, 10.97.125.172, kube-system</code></pre>
Previous name, IP and namespace:
<pre><code>k8s-influxdb-rbac, 10.97.215.189, kube-system</code></pre>

Outputs:

<pre><code>root@ubuntu:/# nslookup k8s-influxdb-rbac.kube-system.svc
Server:         10.97.0.10
Address:        10.97.0.10#53

Name:   k8s-influxdb-rbac.kube-system.svc.cluster.local
Address: 10.97.215.189</code></pre>
<pre><code>root@ubuntu:/# nslookup k8s-influxdb-rbac-svc.kube-system.svc
Server:         10.97.0.10
Address:        10.97.0.10#53

** server can't find k8s-influxdb-rbac-svc.kube-system.svc.cluster.local: NXDOMAIN</code></pre>
The old entry is not shown with:
<pre><code>kubectl -n kube-system get svc -o wide --show-all</code></pre>

The new entry has endpoints to the current pod it belongs to and is pingable but not resolvable by DNS, what is kind of blurry to me (again T_T).  
The old entry is resolvable and pingable but has no endpoint to the pod (ofc 'cause the pod is new, for the **new** service)

/kind bug
/sig network
@thockin

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by m-no-2017** [comment]
Update:  
RBAC seems to trigger this. Since the Kube-DNS is started with "system:serviceaccounts:kube-system:default" as ServiceAccount, there might be some sort of denial for service updates.  

If I specify a superuser (e.g. cluster-admin) it works as intended.

_Sidenote_:  
Kube-DNS (even with the new version v1.14.1) seems to ignore the second nameserver in /etc/resolv.conf.

To test it I changed the kubelet flag <pre><code>"--cluster-dns=DNS01,DNS02"</code></pre> to <pre><code>"--cluster-dns=DNS02,DNS01"</code></pre> and restarted the whole system (to be really sure).  
The dnspolicy is set to "default" (so I assume "ClusterFirst" if I can trust the [docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)).

Cluster DNS IP first in list ("--cluster-dns=DNS01,DNS02"):
- "very" high delay (3s+) in a "docker in docker" environment if I ping (or nslookup) services outside the cluster

Company DNS IP first in list ("--cluster-dns=DNS02,DNS01"):
- instant resolution and pings of/to all services outside the cluster
- no resolution of any cluster services
