### ISSUE TITLE
Kubelet "Error updating node status" appears when using keepalived on selected nodes

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes/kubernetes#54492]
> NOTE: This has been posted on [contrib/issues/2761](https://github.com/kubernetes/contrib/issues/2761), so I apologize in advance for the duplicate. Fact is, I'm not sure that I opened the original issue in the correct place. It's been over a month and it seems no one has ever looked at it. Hopefully, I'll get an answer, but feel free to close the issue if appropriate. Kind regards!

I'm deploying keepalived on two of my nodes to provide HA for an nginx service that will be also deployed on those nodes. Both keepalived and nginx are independent daemonsets running privileged containers to interface directly with the node's network (hostNetwork: true).

Nginx is deployed successfully, and the issue persists if I remove it. So, I'm running into problems trying to get keepalived to behave well with the node's kubelet service.

While keepalived is working as expected for its HA purpose, kubelet seems to get lost once virtual addresses are assigned to the node. It will fail to update the node status with the api server.

```
Sep 19 17:58:03 infra02-lab kubelet[25341]: E0919 17:58:03.368592   25341 kubelet_node_status.go:357] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/addresses\":[{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"Hostname\"}],\"$setElementOrder/conditions\":[{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"addresses\":[{\"address\":\"172.31.134.142\",\"type\":\"ExternalIP\"},{\"address\":\"172.31.134.112\",\"type\":\"ExternalIP\"},{\"address\":\"172.31.134.142\",\"type\":\"InternalIP\"},{\"address\":\"172.31.134.112\",\"type\":\"InternalIP\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2017-09-19T20:58:03Z\",\"lastTransitionTime\":\"2017-09-19T20:58:03Z\",\"message\":\"kubelet has sufficient disk space available\",\"reason\":\"KubeletHasSufficientDisk\",\"status\":\"False\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2017-09-19T20:58:03Z\",\"lastTransitionTime\":\"2017-09-19T20:58:03Z\",\"message\":\"kubelet has sufficient memory available\",\"reason\":\"KubeletHasSufficientMemory\",\"status\":\"False\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2017-09-19T20:58:03Z\",\"lastTransitionTime\":\"2017-09-19T20:58:03Z\",\"message\":\"kubelet has no disk pressure\",\"reason\":\"KubeletHasNoDiskPressure\",\"status\":\"False\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2017-09-19T20:58:03Z\",\"lastTransitionTime\":\"2017-09-19T20:58:03Z\",\"message\":\"kubelet is posting ready status. AppArmor enabled\",\"reason\":\"KubeletReady\",\"status\":\"True\",\"type\":\"Ready\"}]}}" for node "infra02-lab": The order in patch list:
Sep 19 17:58:03 infra02-lab kubelet[25341]: [map[address:172.31.134.142 type:ExternalIP] map[address:172.31.134.112 type:ExternalIP] map[address:172.31.134.142 type:InternalIP] map[address:172.31.134.112 type:InternalIP]]
Sep 19 17:58:03 infra02-lab kubelet[25341]:  doesn't match $setElementOrder list:
Sep 19 17:58:03 infra02-lab kubelet[25341]: [map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP] map[type:Hostname]]
```

For this particular node, 172.31.134.112 being the node's true IP and 172.31.134.142 is it's virtual IP.

Clearing up all the clutter from the error message, it boils down to

```
The order in patch list: [
  map[address:172.31.134.142 type:ExternalIP]
  map[address:172.31.134.112 type:ExternalIP]
  map[address:172.31.134.142 type:InternalIP]
  map[address:172.31.134.112 type:InternalIP]
]

doesn't match $setElementOrder list:

[
  map[type:ExternalIP]
  map[type:InternalIP]
  map[type:ExternalIP]
  map[type:InternalIP]
  map[type:Hostname]
]
```

Below is the json content created by kubelet prettyfied:

```
{
  "status": {
    "$setElementOrder\/addresses": [
      {
        "type": "ExternalIP"
      },
      {
        "type": "InternalIP"
      },
      {
        "type": "ExternalIP"
      },
      {
        "type": "InternalIP"
      },
      {
        "type": "Hostname"
      }
    ],
    "$setElementOrder\/conditions": [
      {
        "type": "OutOfDisk"
      },
      {
        "type": "MemoryPressure"
      },
      {
        "type": "DiskPressure"
      },
      {
        "type": "Ready"
      }
    ],
    "addresses": [
      {
        "address": "172.31.134.142",
        "type": "ExternalIP"
      },
      {
        "address": "172.31.134.112",
        "type": "ExternalIP"
      },
      {
        "address": "172.31.134.142",
        "type": "InternalIP"
      },
      {
        "address": "172.31.134.112",
        "type": "InternalIP"
      }
    ],
    "conditions": [...]
  }
}
```

I'm inclined to understand here that the api server is refusing the node update because of the fields ExternalIP and InternalIP are mixed out of order. Is this correct?

Is there anything I can do to workaround or fix this?

Kind regards.

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

/area kubelet
/kind support
/sig node
/sig contributor-experience
/sig onprem

**Comment by f0** [comment]
Hi, the problem also exist on kubernetes 1.8.5

**Comment by f0** [comment]
@juliohm1978  you can set --node-ip ${nodeip} falg for the kubelet, this "fixed" the problem in my case

**Comment by warmchang** [comment]
We have the same problem in v1.6.9:
```
Jan 03 15:42:56 paas-controller-192-168-80-2 kube-apiserver[26489]: E0103 15:42:56.990955   26489 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.ResourceQuota: Get https://localhost:6443/api/v1/resourcequotas?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
Jan 03 15:42:56 paas-controller-192-168-80-2 kube-apiserver[26489]: E0103 15:42:56.990954   26489 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.LimitRange: Get https://localhost:6443/api/v1/limitranges?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
Jan 03 15:42:56 paas-controller-192-168-80-2 kube-apiserver[26489]: E0103 15:42:56.990954   26489 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.ServiceAccount: Get https://localhost:6443/api/v1/serviceaccounts?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
Jan 03 15:42:56 paas-controller-192-168-80-2 kube-apiserver[26489]: E0103 15:42:56.990957   26489 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *storage.StorageClass: Get https://localhost:6443/apis/storage.k8s.io/v1beta1/storageclasses?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
Jan 03 15:42:56 paas-controller-192-168-80-2 kube-apiserver[26489]: E0103 15:42:56.990965   26489 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:70: Failed to list *api.Namespace: Get https://localhost:6443/api/v1/namespaces?resourceVersion=0: dial tcp [::1]:6443: getsockopt: connection refused
```

**Comment by juliohm1978** [comment]
Apologies for the delays on following this up.

After a full installation into v1.8.6, the problems seems to have gone away. Will reopen if the issue comes up again.

Thank you all.

**Comment by sjgiri** [comment]
Hi,
I'm seeing the same issue with version 1.11.3 and keepalived 0.11.

10.172.142.171 - virtual IP
10.172.142.38 - node IP

Nov 13 19:21:13 govmomi-worker-1-giri kubelet[3190]: E1113 19:21:13.759645    3190 kubelet_node_status.go:391] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/addresses\":[{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"ExternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"Hostname\"}],\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"PIDPressure\"},{\"type\":\"Ready\"}],\"addresses\":[{\"address\":\"10.172.142.171\",\"type\":\"ExternalIP\"},{\"address\":\"10.172.142.38\",\"type\":\"ExternalIP\"},{\"address\":\"10.172.142.171\",\"type\":\"InternalIP\"},{\"address\":\"10.172.142.38\",\"type\":\"InternalIP\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2018-11-13T19:21:13Z\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2018-11-13T19:21:13Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2018-11-13T19:21:13Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2018-11-13T19:21:13Z\",\"type\":\"PIDPressure\"},{\"lastHeartbeatTime\":\"2018-11-13T19:21:13Z\",\"type\":\"Ready\"}]}}" for node "govmomi-worker-1-giri": The order in patch list:
Nov 13 19:21:13 govmomi-worker-1-giri kubelet[3190]: [map[type:ExternalIP address:10.172.142.171] map[address:10.172.142.38 type:ExternalIP] map[address:10.172.142.171 type:InternalIP] map[address:10.172.142.38 type:InternalIP]]
Nov 13 19:21:13 govmomi-worker-1-giri kubelet[3190]:  doesn't match $setElementOrder list:
Nov 13 19:21:13 govmomi-worker-1-giri kubelet[3190]: [map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP] map[type:Hostname]]

I'd appreciate any hints to resolve this. Thanks!
