### ISSUE TITLE
Load kernel modules using init container in kube-proxy pod

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#54497]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig network

**What happened**:
Follow up of https://github.com/kubernetes/kubernetes/pull/52003. The mentioned PR mounts `/lib/modules` on host to the kube-proxy pod, so that a kube-proxy pod can load kernel modules by need or when `modprobe <kmod>` is run inside the pod.

Folks believed a better solution is to load kernel modules in init container instead as that has less security concerns, but we would like to get the alternative solution in first to unblock the IPVS beta work.This issue is opened for tracking the init container solution.

There already are some relevant comments on https://github.com/kubernetes/kubernetes/pull/52003, but might be great to put further discussion here.

Looping in folks from previous thread.
@vfreex @mikedanese @m1093782566 @cmluciano @dhilipkumars @tallclair @thockin

**Comment by Lion-Wei** [comment]
@cmluciano Hi, I work in Huawei, this  problem does lead some safety concern in our product, id you don't mind, I think I can give a shot. Thanks.

**Comment by cmluciano** [comment]
@Lion-Wei SGTM

**Comment by m1093782566** [comment]
I am going to close this issue in favor of discreating issues.

We are working on https://github.com/kubernetes/kubernetes/issues/59402 now.
