### ISSUE TITLE
kubectl get pods should report last restart time?

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#54491]
When a pod is being restarted, the time it last restarted is very relevant (if it was hours ago, I don't care).  We should consider some information being presented about how recent the restart is.

For example, real world example

```
$ kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
prometheus-0   5/5       Running   30         21h
```

I don't know when the time of the last restart was.  In this case it was 15 hours ago, so the 30 restarts actually doesn't matter.  The age is 21h, but that's not very useful.  Trying to find a middle ground would be useful.

**Comment by juliohm1978** [comment]
Nice suggestion. If not to clutter the simplified output, I suppose it could be part of the contents from `-o wide`.

**Comment by smarterclayton** [comment]
If we think RESTARTS is important enough to show in the normal columns, we
shouldn't force someone to call -o wide to make it be complete.  Restart
count alone isn't sufficient signal to make a decision.

**Comment by grodrigues3** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by zjj2wry** [comment]
i thank we can add a column `LASTSTARTED`. alse it should be close to `RESTARTS` column

**Comment by stewart-yu** [comment]
I think add a column `LASTSTARTED` need, keeping `RESTARTS` column also need. `LASTSTARTED` reflect short-term pod's status, `RESTARTS` reflect long-term pod's status recently. @zjj2wry

**Comment by zjj2wry** [comment]
when my pod do not have `lastState:`(my pod not running all the time). should the column show?

**Comment by davidopp** [comment]
I have a REALLY dumb question. What causes a pod to restart? (As opposed to being deleted.)

**Comment by VictorBHub** [comment]
@zjj2wry 'lastState:' contains info about the start and end of the last dead pod. 
the original suggestion, I think, was to show the current pod ready since time (the 'lastTransitionTime' under status.conditions on the element where "type": "Ready")

**Comment by epsniff** [comment]
@davidopp in our stack the main causes are OOMs and segfaults.

**Comment by etibroo** [comment]
> /assign

What happened after this? Is there a plan to include this?

**Comment by HerrTamm** [comment]
Also interested in the smae feature, it especially helps to debug services in general namespaces (e.g. kube-system), where multiple services and a lot of pods are running.

**Comment by rohitkhatana** [comment]
This feature should be there. It helps in identifying issue in much better/easy way. For example if we are facing issues during in a time window, in the that time window it is very relevant information to see.

**Comment by antoniocascais** [comment]
Totally agree with @rohitkhatana !

**Comment by diepes** [comment]
> I have a REALLY dumb question. What causes a pod to restart? (In-place on the same node. As opposed to being deleted.)

I think the container exiting on it's own,  e.g. app detecting a missing value at startup or faulty db connection and then electing to exit.

**Comment by soltysh** [comment]
For anyone willing to work on this, the last restart time should be an approximation from all the statuses of all containers and initcontainers. I will want to see extensive unit tests for this particular case.

**Comment by Ethyling** [comment]
Hey, I would like to work on this if possible. That would be my first contribution to Kubernetes so I may need help at some point

**Comment by soltysh** [comment]
@Ethyling go ahead, feel free to ping me on slack, but it might take a bit for me to reply :wink: due to upcoming code freeze for 1.21.

**Comment by Ethyling** [comment]
> @Ethyling go ahead, feel free to ping me on slack, but it might take a bit for me to reply wink due to upcoming code freeze for 1.21.

Hey @soltysh , thank you!

I currently have a first version:
```
$ kubectl get pods
NAME                                READY   STATUS                  RESTARTS   LAST RESTART   AGE
nginx-deployment-66b6c48dd5-sb297   1/1     Running                 1          9m30s          12m
nginx-deployment-79fbfbd7c8-hj8z5   0/1     Init:CrashLoopBackOff   5          54s            4m40s
```
I'm using the `LastTerminationState` attribute of the container status. I don't know if it's the right attribute to use. I will clean my code and open a PR. I think it will be easier to discuss

**Comment by Ethyling** [comment]
Hey @soltysh, I opened the PR, if you have some time to check it
