### ISSUE TITLE
Provide capability to query all children resources

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#54498]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

Currently for querying all children resources, a k8s user needs to define custom labelling. The problem comes to transferring knowledge of this labelling. For example, etcd operator might add labels `etcd_cluster=<cluster-name>` to etcd pods, services. But consumers of etcd operator needs to understand etcd operator's labelling convention. This has caused two problems:

- Even if detailed docs is provided, users are reluctant to follow it. They want to define their own labelling in order to query children resources. This causes inconsistency. And querying children resources is very common and everyone does (duplicates) it.
- It couples development team and consumer. Whatever labels has been created, modified, it will affect the consumers.

It's a better way to handle this if k8s can provide feature to query children resources:

- It is a very common use.
- k8s itself needs it as well, e.g. GC
- This is more efficient and simple if reserve index is built inside APIServer.

**Comment by juliohm1978** [comment]
While it sounds reasonable, wouldn't we run the risk of dumping the entire etcd database with a single query, depending on the objects deployed and how they relate to each other?

**Comment by caesarxuchao** [comment]
Off the top my head, we can do this in two ways:
1. Use the garbage collector's dependency graph as the ground truth. The drawback is the dependency graph has a latency.
2. Or we can add a `metadata.dependentsReference` field to each objects, and utilize the transaction support in etcd 3 to atomically create `ownerReference` and `depedentsReference`.

**Comment by hongchaodeng** [comment]
Actually this is also one item task for https://github.com/kubernetes/kubernetes/issues/34363, which justify the feature too.

**Comment by colemickens** [comment]
I'm going to work on investigating and writing up a proposal for this, probably starting next week.

**Comment by lavalamp** [comment]
1. Use the owner reference feature. (Definitely don't make everyone else understand your label system!)
2. We've talked in the past about giving the GC an API so it can answer queries like this, I think that is the way forward.

**Comment by hongchaodeng** [comment]
/reopen
/remove-lifecycle rotten
I think @colemickens mentioned [here](https://github.com/kubernetes/kubernetes/issues/54498#issuecomment-339760892) he would work on this.

**Comment by fabianvf** [comment]
@colemickens any luck?

**Comment by jzelinskie** [comment]
I don't think we ever got through any proposals for this. Our initial desire for the functionality was discovering resources being managed by Operators. The Operators managed by [OLM](https://github.com/operator-framework/operator-lifecycle-manager) are supposed to set ownerref on all created objects to a custom resource. We wanted this API for making it easy to display the resources that the Operator is managing behind the scenes of the CR. We do accomplish this today, but by forcing users to manually document what resource types and labels are being used in the manifest defining the Operator, rather than being able discovery it automatically.

**Comment by cmoulliard** [comment]
Will this issue closed then ?

**Comment by lavalamp** [comment]
I think I heard there is a way to query or at least dump the GC graph now?
