### ISSUE TITLE
Fix starvation problem in pod preemption

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#54501]
The first version of pod preemption implemented in K8s 1.8 suffers from a known starvation problem whose details are explained [here](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#starvation-of-preempting-pod). The issue should be fixed.

/sig scheduling
/assign

**Comment by resouer** [comment]
@bsalamat I think it would be better to have a task tracker here to collect all PRs and designs.

Btw, this seems to be a candidate in 1.9, right? If confirmed, we need to add milestone and release note to the issue & PR.

**Comment by bsalamat** [comment]
@resouer We do have a task tracker for priority and preemption: #47604

I agree about milestone for the issue and the PRs. I don't have permission to add milestones. I guess I should request it.

**Comment by jberkus** [comment]
What's the milestone status for this?  It is still a candidate for 1.9?  If so, can an owner add a milestone and approval status?  (also kind and priority)

**Comment by bsalamat** [comment]
@jberkus This is a candidate for 1.9.
@davidopp Could you please add a milestone?
