### ISSUE TITLE
Nginx ingress controller closes chunked encoding requests on when configuration reloads

### ISSUE THREAD

**Issue by jesseshieh** [kubernetes/kubernetes#54505]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a BUG REPORT
/kind bug
/sig network
@kubernetes/sig-network-bugs

**What happened**:
We found that if you have a long request/response connection such as a chunked encoding response, the request is prematurely truncated when the ingress controller reloads the nginx configuration.

**What you expected to happen**:
We expected the connection to remain open.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run an upstream server with an endpoint that responds with a long-lived chunked response. For example, one chunk every second for 100 seconds. The language shouldn't matter, but I am using an Elixir/Phoenix app with this action

    ```
      def stream(conn, params) do
        conn = conn
        |> put_resp_content_type("text/event-stream")
        |> send_chunked(200)

        for _ <- 1..100 do
          :timer.sleep(1000)
          conn |> chunk("hello")
        end

        conn
      end
    ```
2. Make a request with something like

        time curl --raw localhost/test/stream -H 'Host: bar.gigalixir.com'

3. After a random amount of time, the connection will close and curl will print

        curl: (18) transfer closed with outstanding read data remaining

    You can reproduce the issue by manually running the following inside the ingress controller container and waiting 10 seconds.

        nginx -s reload

It appears as though the nginx worker processes drain requests for 10 seconds when reloading before cutting the connections, which in my case is not long enough.

**Anything else we need to know?**:
I'm not sure what the proper fix is for this, but in my case, I am tailing logs through chunked encoding so I need the connection open basically indefinitely, but at least an hour or so.

**Environment**:
- Kubernetes version (use `kubectl version`):
    ```
    Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", 
    GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", 
    GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
    ```
- Cloud provider or hardware configuration**:
    GCE
- OS (e.g. from /etc/os-release):
    ```
    PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
    NAME="Debian GNU/Linux"
    VERSION_ID="7"
    VERSION="7 (wheezy)"
    ID=debian
    ANSI_COLOR="1;31"
    HOME_URL="http://www.debian.org/"
    SUPPORT_URL="http://www.debian.org/support/"
    BUG_REPORT_URL="http://bugs.debian.org/"

    ```
- Kernel (e.g. `uname -a`):
    `Linux kubernetes-minion-group-csn9 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux`
- Install tools:
    I'm using Kubernetes Ingress Controller with 
    `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.14`

    It also happens with
    `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15`
    `gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.13`

- Others:

**Comment by cmluciano** [comment]
cc @aledbf

**Comment by aledbf** [comment]
@jesseshieh you can adjust the drain of connections in the workers adjusting the value of the setting `worker-shutdown-timeout: XXXs` in the configuration configmap. The default value is 10 seconds.
That being said keep in mind that the old worker processes (with pending connections) will stay alive. This means you will see an increase in the nginx memory consumption.

**Comment by jesseshieh** [comment]
@aledbf thanks! Just to make sure I understand, if I set the timeout to something like 5 hours and the configuration is reloaded say every 60 seconds and there are no "long-running" connections, the workers should recycle themselves normally and quickly. It's only when there are "long-running" connections that old worker processes will stick around for potentially 5 hours and so the number of workers could potentially grow unbounded. Is that right? If so, I think this is worth a try and could solve my issue.

Is there any possibility of a solution that can reload configuration without recycling the workers? That way, the connections can stay open basically forever and without a growing number of workers. I'm not sure exactly, but I think something like Traefik can reload configs this way?

**Comment by aledbf** [comment]
> Just to make sure I understand, if I set the timeout to something like 5 hours and the configuration is reloaded say every 60 seconds and there are no "long-running" connections, the workers should recycle themselves normally and quickly.

Yes

> It's only when there are "long-running" connections that old worker processes will stick around for potentially 5 hours and so the number of workers could potentially grow unbounded. Is that right? If so, I think this is worth a try and could solve my issue.

Yes

> Is there any possibility of a solution that can reload configuration without recycling the workers? That way, the connections can stay open basically forever and without a growing number of workers.

This is not something we can change because it is how nginx works.

>  I'm not sure exactly, but I think something like Traefik can reload configs this way?

I am not familiar with traefik, maybe you should ask in the traefik repository.

**Comment by jesseshieh** [comment]
Thanks! Sounds like there's nothing more to do here so I'll go ahead and close this issue. I'll re-open if this doesn't work. Thanks again!

**Comment by jesseshieh** [comment]
Just found this while searching for `worker-shutdown-timeout` so linking here for posterity/reference.
https://github.com/kubernetes/ingress-nginx/issues/1373

**Comment by chestack** [comment]
configuring longer "worker-shutdown-timeout" works for me.

But there is a strange behavior is that NGINX will retry non-idempotent POST request in case that backend server(app) response back to nginx after all old workers shutdown(connections lost)
Could anyone help explain it, thanks

**Comment by chestack** [comment]
@aledbf ，thanks for your reply.

I did not config "proxy-next-upstream:" in nginx-custom-configuration configmap. So nginx **will not** retry POST  request, right? And there is only one replica of the upstream server.

Following is snippet of nginx.conf in my env:

```
    upstream openstack-servicecatalog-int-sc-port {
        # Load balance algorithm; empty for round robin, which is the default
        least_conn;

        keepalive 32;

        server 10.233.64.213:80 max_fails=0 fail_timeout=0;
    }
....

            proxy_set_header X-Real-IP              $the_real_ip;
            proxy_set_header X-Forwarded-For        $the_real_ip;
            proxy_set_header X-Forwarded-Host       $best_http_host;
            proxy_set_header X-Forwarded-Port       $pass_port;
            proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
            proxy_set_header X-Original-URI         $request_uri;
            proxy_set_header X-Scheme               $pass_access_scheme;

            # Pass the original X-Forwarded-For
            proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header Proxy                  "";

            # Custom headers to proxied server

            proxy_connect_timeout                   3s;
            proxy_send_timeout                      60s;
            proxy_read_timeout                      300s;

            proxy_redirect                          off;
            proxy_buffering                         off;
            proxy_buffer_size                       "4k";
            proxy_buffers                           4 "4k";
            proxy_request_buffering                 "off";

            proxy_http_version                      1.1;

            proxy_cookie_domain                     off;
            proxy_cookie_path                       off;

            # In case of errors try the next upstream server before returning an error
            proxy_next_upstream                     error timeout invalid_header http_502 http_503 http_504;

            rewrite /service_catalog/(.*) /$1 break;
            rewrite /service_catalog / break;
            proxy_pass http://openstack-servicecatalog-int-sc-port;

        }
```

**Comment by aledbf** [comment]
> So nginx will not retry POST request, right? 

No unless you enable [retry-non-idempotent](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#retry-non-idempotent)+

> And there is only one replica of the upstream server.

If you have only one server not sure it makes sense to retry.
Please keep in mind the default `proxy-next-upstream` value is the default `error` http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream

**Comment by Rukhsar290498** [comment]
After upgardeing ingress-nginx-controller to v1.11.5 and kube webhook version v20231226-1a7112e06; i am getting -upstream sent duplicate header line: "Transfer-Encoding: chunked", previous value: "Transfer-Encoding: chunked" while reading response header from upstream. in ingress-nginx logs.
