### ISSUE TITLE
Ubuntu minikube kubectl no resources

### ISSUE THREAD

**Issue by paddypopeye** [kubernetes/kubernetes#54512]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind bug

/sig CLI
/sig Cluster Ops SIG

**What happened**:
:/usr/local/bin# sudo minikube start
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

sudo kubectl get pods
No resources found.

**What you expected to happen**:
the command $ kubectl get pods,  should return similar to ...
NAME                              READY     STATUS              RESTARTS   AGE
hello-minikube-3383150820-vctvh   1/1       ContainerCreating   0          3s
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
kubectl and minikube installed in /usr/local/bin
minikube vm starts ok in virtual box... and can log in with user "docker" password "tcuser"
same behaviour with or without the use of "sudo" 

installed following 
https://kubernetes.io/docs/tasks/tools/install-kubectl/
https://github.com/kubernetes/minikube/releases

**Environment**:
- Kubernetes version (use `kubectl version`)  output of   "$: kubectl version"

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
root@luby-Aspire-5250:/usr/local/bin# sudo kubectl version 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
root@luby-Aspir

- Kernel (e.g. `uname -a`): 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: 
curl

curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

- Others:

**Comment by r2d4** [comment]
Minikube issues should be opened in https://github.com/kubernetes/minikube

Minikube and kubectl should not be run with `sudo`

**Comment by spzala** [comment]
@paddypopeye this is an expected behavior and as @r2d4 mentioned you can still open a separate minikube issue as a new requirement if you want. If you are okay with that approach, it would be great if you can close this issue. Thanks!

**Comment by paddypopeye** [comment]
not to sure you noticed that i said 
"same behaviour with or without the use of "sudo"

the same behaviour happens when sudo is not used

**Comment by spzala** [comment]
Thanks @paddypopeye

**Comment by XinchenWan** [comment]
I faced the same problem that there is no resources found. And if I didn't run minikube and kubectl with "sudo", it would call  "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

Can you tell me how to deal with this issue? @r2d4 @spzala @paddypopeye
