### ISSUE TITLE
can host-path StorageClass support   set  volume base dir?

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#54527]
I create the host-path StorageClass，add start parments  to kube-controller-manager 
`    - --enable-dynamic-provisioning=true
    - --enable-hostpath-provisioner=true`

the StorageClass yaml file :
`kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  namespace: bigdata
  name: hostpath
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/host-path`

i find the host path dir is /tmp ,can i change this base dir?

**Environment**:
- Kubernetes version (use `kubectl version`):1.6.4
- Cloud provider or hardware configuration**: 
- OS (e.g. from /etc/os-release): centos7.3
- Kernel (e.g. `uname -a`):3.10

**Comment by dixudx** [comment]
/sig storage

> i find the host path dir is /tmp ,can i change this base dir?

@davidstack Can not for now. `host_path` deleter has a **hard-coded regex for "/tmp"**. It only supports `/tmp` and removes the local directory so long as it is beneath `/tmp/*`.

**Comment by davidstack** [comment]
OK， thanks

**Comment by davidstack** [comment]
ok,thanks

**Comment by davidstack** [comment]
ok,thanks
