### ISSUE TITLE
GCE cluster can't start with basic audit enabled

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#54526]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Cluster startup times out. kube-apiserver never comes up.

**What you expected to happen**:

Cluster starts up.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
export ENABLE_APISERVER_BASIC_AUDIT=true
cluster/kube-up.sh
```

**Anything else we need to know?**:

This seems to be caused by https://github.com/kubernetes/kubernetes/pull/53225.

The kube-apiserver never comes up, and when I SSH into the master and run `sudo systemctl status kube-master-configuration` I see this error:

```
/home/kubernetes/bin/configure-helper.sh: line 1353: FEATURE_GATES: readonly variable
```

**Environment**: GCE
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mariida** [comment]
I meet the same error

**Comment by crassirostris** [comment]
Thanks, looking into it
