### ISSUE TITLE
kubelet.service fail to start up

### ISSUE THREAD

**Issue by yeaheo** [kubernetes/kubernetes#54542]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kubelet.service fail to start up

**What you expected to happen**:
kubelet.service start up success

**How to reproduce it (as minimally and precisely as possible)**:

``` bash
[root@test-node1 system]# systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 三 2017-10-25 16:08:09 CST; 8s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 18607 ExecStart=/usr/local/bin/kubelet $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBELET_API_SERVER $KUBELET_ADDRESS $KUBELET_PORT $KUBELET_HOSTNAME $KUBE_ALLOW_PRIV $KUBELET_POD_INFRA_CONTAINER $KUBELET_ARGS (code=exited, status=2)
 Main PID: 18607 (code=exited, status=2)

10月 25 16:08:09 test-node1 systemd[1]: Unit kubelet.service entered failed state.
10月 25 16:08:09 test-node1 kubelet[18607]: --vmodule moduleSpec                                       comma-separated list of pattern=N settings for file-filtered logging
10月 25 16:08:09 test-node1 kubelet[18607]: --volume-plugin-dir string                                 <Warning: Alpha feature> The full path of the directory in which to search for additional third party volume plugins (default "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/")
10月 25 16:08:09 test-node1 kubelet[18607]: --volume-stats-agg-period duration                         Specifies interval for kubelet to calculate and cache the volume disk usage for all pods and volumes.  To disable volume calculations, set to 0. (default 1m0s)
10月 25 16:08:09 test-node1 systemd[1]: kubelet.service failed.
10月 25 16:08:09 test-node1 systemd[1]: kubelet.service holdoff time over, scheduling restart.
10月 25 16:08:09 test-node1 systemd[1]: start request repeated too quickly for kubelet.service
10月 25 16:08:09 test-node1 systemd[1]: Failed to start Kubernetes Kubelet Server.
10月 25 16:08:09 test-node1 systemd[1]: Unit kubelet.service entered failed state.
10月 25 16:08:09 test-node1 systemd[1]: kubelet.service failed.
```

**Anything else we need to know?**:
kubelet.service file
``` xml
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/kubelet
ExecStart=/usr/local/bin/kubelet \
            $KUBE_LOGTOSTDERR \
            $KUBE_LOG_LEVEL \
            $KUBELET_API_SERVER \
            $KUBELET_ADDRESS \
            $KUBELET_PORT \
            $KUBELET_HOSTNAME \
            $KUBE_ALLOW_PRIV \
            $KUBELET_POD_INFRA_CONTAINER \
            $KUBELET_ARGS
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
kubelet.service config file
``` bash
###
## kubernetes kubelet (minion) config
#
## The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=192.168.8.67"
#
## The port for the info server to serve on
#KUBELET_PORT="--port=10250"
#
## You may leave this blank to use the actual hostname
KUBELET_HOSTNAME="--hostname-override=192.168.8.67"
#
## location of the api-server
KUBELET_API_SERVER="--api-servers=http://192.168.8.66:8080"
#
## pod infrastructure container
#KUBELET_POD_INFRA_CONTAINER="--pod-infra-container-image="
#
## Add your own!
KUBELET_ARGS="--cluster-dns=10.254.0.2 --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --require-kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-domain=cluster.local --hairpin-mode promiscuous-bridge --serialize-image-pulls=false"
```

**Environment**:
- Kubernetes version: 1.8.0
- Cloud provider or hardware configuration**: 1G 20G
- OS (e.g. from /etc/os-release):CentOS7 1708
- Kernel (e.g. `uname -a`): Linux test-node1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: binnary
- Others:

**Comment by yoo2767** [comment]
kubelet service fail to start up ,I dont konw how to resolve it ,

**Comment by php-coder** [comment]
Is it a duplicate for https://github.com/kubernetes/kubernetes/issues/54541 ?

**Comment by darrylsepeda** [comment]
I also have the same issue when the kubelet always show error status 1/FAILURE
```
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-10-25 15:20:06 UTC; 2s ago
     Docs: http://kubernetes.io/docs/
  Process: 32404 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
 Main PID: 32404 (code=exited, status=1/FAILURE)
```
is there any way to trace what makes this error?
or maybe is there any way to fix it?

**Comment by grodrigues3** [comment]
@kubernetes/sig-node-bugs

**Comment by hzxuzhonghu** [comment]
show logs related to kubelet use `journalctl`

**Comment by chinni505** [comment]
Nov 02 15:12:12 kubernetes-master kubelet[2313]: I1102 15:12:12.324007    2313 controller.go:114] kubelet config controller: starting controller
Nov 02 15:12:12 kubernetes-master kubelet[2313]: I1102 15:12:12.323899    2313 feature_gate.go:156] feature gates: map[]
Nov 02 15:12:12 kubernetes-master systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Nov 02 15:12:12 kubernetes-master systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 02 15:12:12 kubernetes-master systemd[1]: kubelet.service holdoff time over, scheduling restart.
Nov 02 15:12:02 kubernetes-master systemd[1]: kubelet.service failed.
Nov 02 15:12:02 kubernetes-master systemd[1]: Unit kubelet.service entered failed state.
Nov 02 15:12:02 kubernetes-master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Nov 02 15:12:02 kubernetes-master kubelet[2308]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Nov 02 15:12:02 kubernetes-master kubelet[2308]: I1102 15:12:02.076525    2308 controller.go:118] kubelet config controller: validating combination of defaults and flags
Nov 02 15:12:02 kubernetes-master kubelet[2308]: I1102 15:12:02.076519    2308 controller.go:114] kubelet config controller: starting controller
Nov 02 15:12:02 kubernetes-master kubelet[2308]: I1102 15:12:02.076409    2308 feature_gate.go:156] feature gates: map[]
Nov 02 15:12:01 kubernetes-master systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Nov 02 15:12:01 kubernetes-master systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 02 15:12:01 kubernetes-master systemd[1]: kubelet.service holdoff time over, scheduling restart.
Nov 02 15:11:51 kubernetes-master systemd[1]: kubelet.service failed.
Nov 02 15:11:51 kubernetes-master systemd[1]: Unit kubelet.service entered failed state.
Nov 02 15:11:51 kubernetes-master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Nov 02 15:11:51 kubernetes-master kubelet[2303]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Nov 02 15:11:51 kubernetes-master kubelet[2303]: I1102 15:11:51.831530    2303 controller.go:118] kubelet config controller: validating combination of defaults and flags
Nov 02 15:11:51 kubernetes-master kubelet[2303]: I1102 15:11:51.831519    2303 controller.go:114] kubelet config controller: starting controller
Nov 02 15:11:51 kubernetes-master kubelet[2303]: I1102 15:11:51.831386    2303 feature_gate.go:156] feature gates: map[]

**Comment by awesomemayank007** [comment]
please switchoff your swap memory i faced same problem and when i remove swap entry from my /etc/fstab file .then it worked in my case.also do swapoff

**Comment by zouhuigang** [comment]
@awesomemayank007  Yes, but it doesn't work. What should I do?Do I need to restart the server in VM?

**Comment by cseeger-epages** [comment]
Nov 02 15:12:02 kubernetes-master kubelet[2308]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

ca missing ?

**Comment by arunm8489** [comment]
#yum install -y kubelet kubeadm kubectl docker
Jst try installing docker 1.12...iam not getting solution with docker 1.17ce.( i think its not supported with kubelet)
Make swap off by #swapoff -a
Now reset kubeadm by #kubeadm reset
Now try #kudeadm init
after that check #systemctl status kubelet
it will be working

**Comment by MarounMaroun** [comment]
I had the same issue, `journalctl` revealed:

```bash
Mar 25 10:22:53 ubuntu kubelet[3216]: error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [
```

I ran:

```bash
swapoff -a
```

then restarted kubelet, all good.

**Comment by wuganghua2018** [comment]
when i use journalctl,the log shows HVMOP_pagetable_dying not supported:
[root@NKG1000136919 kubernetes]# journalctl
-- Logs begin at Wed 2018-08-22 15:46:45 CST, end at Wed 2018-08-22 16:43:17 CST. --
Aug 22 15:46:45 localhost.localdomain systemd-journal[134]: Runtime journal is using 8.0M (max allowed 389.9M, trying to le
Aug 22 15:46:45 localhost.localdomain kernel: Initializing cgroup subsys cpuset
Aug 22 15:46:45 localhost.localdomain kernel: Initializing cgroup subsys cpu
Aug 22 15:46:45 localhost.localdomain kernel: Initializing cgroup subsys cpuacct
Aug 22 15:46:45 localhost.localdomain kernel: Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc ve
Aug 22 15:46:45 localhost.localdomain kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-3.10.0-693.el7.x86_64 root=UUID=fdb6f8
Aug 22 15:46:45 localhost.localdomain kernel: e820: BIOS-provided physical RAM map:
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009f3ff] usable
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x000000000009f400-0x000000000009ffff] reserved
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x0000000000100000-0x00000000dfffefff] usable
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x00000000dffff000-0x00000000dfffffff] reserved
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x00000000fc000000-0x00000000ffffffff] reserved
Aug 22 15:46:45 localhost.localdomain kernel: BIOS-e820: [mem 0x0000000100000000-0x000000021f7fffff] usable
Aug 22 15:46:45 localhost.localdomain kernel: NX (Execute Disable) protection: active
Aug 22 15:46:45 localhost.localdomain kernel: SMBIOS 2.4 present.
Aug 22 15:46:45 localhost.localdomain kernel: DMI: Xen HVM domU, BIOS 4.1.2_115-900.260_ 11/06/2015
Aug 22 15:46:45 localhost.localdomain kernel: Hypervisor detected: Xen HVM
Aug 22 15:46:45 localhost.localdomain kernel: Xen version 4.1.
Aug 22 15:46:45 localhost.localdomain kernel: Xen Platform PCI: I/O protocol version 1
Aug 22 15:46:45 localhost.localdomain kernel: Netfront and the Xen platform PCI driver have been compiled for this kernel:
Aug 22 15:46:45 localhost.localdomain kernel: Blkfront and the Xen platform PCI driver have been compiled for this kernel:
                                              You might have to change the root device
                                              from /dev/hd[a-d] to /dev/xvd[a-d]
                                              in your root= kernel command line option
Aug 22 15:46:45 localhost.localdomain kernel: HVMOP_pagetable_dying not supported
Aug 22 15:46:45 localhost.localdomain kernel: e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
Aug 22 15:46:45 localhost.localdomain kernel: e820: remove [mem 0x000a0000-0x000fffff] usable
Aug 22 15:46:45 localhost.localdomain kernel: e820: last_pfn = 0x21f800 max_arch_pfn = 0x400000000
Aug 22 15:46:45 localhost.localdomain kernel: MTRR default type: write-back
Aug 22 15:46:45 localhost.localdomain kernel: MTRR fixed ranges enabled:
Aug 22 15:46:45 localhost.localdomain kernel:   00000-9FFFF write-back
Aug 22 15:46:45 localhost.localdomain kernel:   A0000-BFFFF write-combining
Aug 22 15:46:45 localhost.localdomain kernel:   C0000-FFFFF write-back
Aug 22 15:46:45 localhost.localdomain kernel: MTRR variable ranges enabled:
Aug 22 15:46:45 localhost.localdomain kernel:   0 base 0000F0000000 mask 3FFFF8000000 uncachable
Aug 22 15:46:45 localhost.localdomain kernel:   1 base 0000F8000000 mask 3FFFFC000000 uncachable
anybody know the reason?

**Comment by Jenychen1996** [comment]
the same question I have

**Comment by hassanejaz** [comment]
> #yum install -y kubelet kubeadm kubectl docker
> Jst try installing docker 1.12...iam not getting solution with docker 1.17ce.( i think its not supported with kubelet)
> Make swap off by #swapoff -a
> Now reset kubeadm by #kubeadm reset
> Now try #kudeadm init
> after that check #systemctl status kubelet
> it will be working

brilliant

**Comment by seirian** [comment]
> #yum install -y kubelet kubeadm kubectl docker
> Jst try installing docker 1.12...iam not getting solution with docker 1.17ce.( i think its not supported with kubelet)
> Make swap off by #swapoff -a
> Now reset kubeadm by #kubeadm reset
> Now try #kudeadm init
> after that check #systemctl status kubelet
> it will be working

**Thanks for your commented.**

**Comment by cp1408** [comment]
yeah...making "swapoff -a" worked for me as well.

but cud not see errror in journalctl for kubelet.

**Comment by amagura** [comment]
Sadly doesn't work on my machines.  :(

**Comment by robwithhair** [comment]
@awesomemayank007 OMG thank you!!! You saved my bacon.  Now why on earth would swap cause kubelet not to start?

**Comment by lbf19881016** [comment]
I close swap memory ,but also start kubelet,who can explaint ?

**Comment by dims** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/53533

**Comment by YuLimin** [comment]
check the status of getenforce & sestatus, and 

swapoff -a

setenforce 0 to Permissive

then retry it.

**Comment by Reham-Fahmy** [comment]
> > #yum install -y kubelet kubeadm kubectl docker
> > Jst try installing docker 1.12...iam not getting solution with docker 1.17ce.( i think its not supported with kubelet)
> > Make swap off by #swapoff -a
> > Now reset kubeadm by #kubeadm reset
> > Now try #kudeadm init
> > after that check #systemctl status kubelet
> > it will be working
> 
> **Thanks for your commented.**

could u provide me a link to download this version.

**Comment by Larry1314** [comment]
fixed for me after running the following cmd
```
swapoff -a
```

**Comment by r3dback** [comment]
that worked !! `swapoff -a'
All cluster Ready :)

**Comment by yogesh174** [comment]
It worked for me after changing the cgroup to systemd in docker. To do that I edited the `/etc/docker/daemon.json` file to 
```
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
```
And restarted docker with `sudo systemctl restart docker`
