### ISSUE TITLE
test flake: kubectl describe serviceaccount unittest will test occasionally

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#54564]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/kind flake
/kind cli

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@zjj2wry any obvious evidences?

**Comment by zjj2wry** [comment]
Fixed by #54628
