### ISSUE TITLE
PersistentVolumeSource should be read-only

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#54562]
/kind bug

Right now we do not validate PV updates so admin can update `PV.Spec.PersistentVolumeSource` at any time. Kubernetes has no facility to reflect this update - it won't magically re-mount an existing volume to e.g. a different NFS server. IMO the PersistentVolumeSource to be read-only and set to stone once created.

@kubernetes/sig-storage-bugs @kubernetes/sig-api-machinery-bugs

**Comment by gnufied** [comment]
I think it is a good idea to make the VolumeSource read-only but I am afraid ship has sailed in v1 and existing code/tooling that relies on the ability to modify PVs will break as a result of this change.

**Comment by ianchakeres** [comment]
@lavalamp - do you have any advice on how we should proceed on fixing this issue?
