### ISSUE TITLE
Sometimes the HBase cluster is normal, and it doesn't work properly after reboot

### ISSUE THREAD

**Issue by quanself** [kubernetes/kubernetes#54566]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by grodrigues3** [comment]
@quanself this issue does have enough information to reproduce it nor is the problem well define.  please update the description and assign to the appropriate sig using the instructions from the above comment

**Comment by dims** [comment]
/close

please see comment above and reopen if necessary
