### ISSUE TITLE
Giving the wrong unit under resource limits is not erroring, instead the pod creation fails.

### ISSUE THREAD

**Issue by MansoorMajeed** [kubernetes/kubernetes#54567]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I specified resource limits with wrong unit. Like below
```
resources:
      requests:
        memory: "64m"
        cpu: "250m"
      limits:
        memory: "128m"
        cpu: "500m"
```
Instead of `Mi` I gave `m` under memory limits in the pod definition.  It didn't show any error while trying to create the deployment. But the container never came up. It was continuously in the `ContainerCreating` mode.

Checking the pod description didn't give anything that is useful.
```
Events:
  FirstSeen     LastSeen        Count   From                                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                                            -------------   --------        ------                  -------
  22s           22s             1       default-scheduler                                               Normal          Scheduled               Successfully assigned xxxxxx-56b4864dd9-9x5gs to gke-xxxxxxx-default-pool-53b7e787-580g
  22s           22s             1       kubelet, gke-xxxxxxx-default-pool-53b7e787-580g                 Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-cwtq0"
  21s           1s              21      kubelet, gke-xxxxxxx-default-pool-53b7e787-580g                 Warning         FailedSync              Error syncing
pod
  20s           0s              21      kubelet, gke-xxxxxxx-default-pool-53b7e787-580g                 Normal          SandboxChanged          Pod sandbox changed, it will be killed and re-created.
```

**What you expected to happen**:
The kubectl should check for the syntax error and should display the error while trying to create the deployment.

**How to reproduce it (as minimally and precisely as possible)**:
Create a yml file with resource limits unit `m` for memory. Example `200m`. Try to create the deployment using `kubectl create -f file.yml`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1-gke.0
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): Mac OS, High Sierra
- Kernel (e.g. `uname -a`): Darwin MacBookPro 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
- Install tools:
- Others:

**Comment by sjevs** [comment]
I checked the source, the problem is that same Quantity logic is used for CPU and memory. For example:
https://github.com/kubernetes/kubernetes/blob/65b8f5bd98de5b4bd6b1f75c3e99280223c7723d/pkg/api/v1/defaults_test.go#L356
```
cpu, _ := resource.ParseQuantity("100m")
mem, _ := resource.ParseQuantity("100Mi")
```

and it is like this in whole project. Guys, open question. Main question: Do we want to change it? 

Meanwhile I will try to make a suggestion PR.

**Comment by sjevs** [comment]
Currently my suggestion:
```
cpu, _ := resource.ParseQuantity("100m", api.ResourceCPU)
mem, _ := resource.ParseQuantity("100Mi", api.ResourceMemory)
```
This new function would:
- call main `func ParseQuantity(str string) (Quantity, error)` 
- then validate the type and if needed throws exception.

What do you think?

**Comment by sjevs** [comment]
aaand btw, the changes would go to package https://github.com/kubernetes/apimachinery :)

**Comment by sjevs** [comment]
the place for changes `staging/src/k8s.io/apimachinery/pkg/api/resource/quantity_test.go`, BUT:

the problem is that, `k8s.io/apimachinery` is separated into different package, and the suggestion above to make changes in same quantity file is NOT valid anymore, since it would reference types`k8s.io/kubernetes/pkg/api`.

**Comment by vipulagarwal** [comment]
We ran into a similar problem when upgraded to 1.10 on GKE
