### ISSUE TITLE
can PDB work for DaemonSet?

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#54565]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE
/kind feature

**What happened**:
PDB doc doesn't explicitly explain if it can be applied to DaemonSet. But I think there is a use case for it and I cannot get it done by PDB.

In my use case, I have 3 ceph mon daemonsets running using node selectors. I set PDB for the ceph mon daemonsets. Then I removed node labels. All daemonsets were deleted:

Before deleting the node labels:
```console
# kubectl get poddisruptionbudgets -n ceph
NAME      MIN-AVAILABLE   ALLOWED-DISRUPTIONS   AGE
mon-pdb   1               2                     24s
```
After removing the node labels:
```console
# kubectl get poddisruptionbudgets -n ceph -o yaml
apiVersion: v1
items:
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: 2017-10-25T12:35:03Z
    generation: 1
    name: mon-pdb
    namespace: ceph
    resourceVersion: "6575264"
    selfLink: /apis/policy/v1beta1/namespaces/ceph/poddisruptionbudgets/mon-pdb
    uid: ecaaa9c8-b980-11e7-ae60-00259003b6e8
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        application: ceph
        component: mon
  status:
    currentHealthy: 0
    desiredHealthy: 1
    disruptedPods: null
    disruptionsAllowed: 0
    expectedPods: 0
    observedGeneration: 1
```

**What you expected to happen**:
PDB policy should be respected.

**How to reproduce it (as minimally and precisely as possible)**:
- create a 3 replica daemonset with node selector
- create a pdb for daemonset
- remove node label

**Anything else we need to know?**:
@kubernetes/sig-apps-misc 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by foxish** [comment]
PDB would protect against removals when an eviction is attempted (through `kubectl drain` perhaps). What was the expected result here in your case? Was it that the label removal operation would fail? I don't think that's an intended use-case for PDB.

**Comment by rootfs** [comment]
Node label removal could be accidental, I would expect PDB offers protection against this case.

**Comment by davidopp** [comment]
It's an interesting use case but as @foxish says PDB was only intended to protect against (voluntary) evictions. If you change labels then it should take that into account in determining whether an eviction (of pods that match the PDB's label selector) is allowed, but the API server won't block the label change.

Implementing what you're asking for would not be trivial, as today PDB is enforced by the /eviction subresource, which is not involved on label changes.

**Comment by rootfs** [comment]
thanks for the info
