### ISSUE TITLE
[e2e failure] [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicaSet Should scale ...

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#54574]
/priority critical-urgent
/sig autoscaling

This test case started failing recently and affects a number of jobs: [triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-autoscaling%5C%5D%20%5C%5BHPA%5C%5D%20Horizontal%20pod%20autoscaling%20%5C(scale%20resource%3A%20CPU%5C)%20%5C%5Bsig-autoscaling%5C%5D%20%5C%5BSerial%5C%5D%20%5C%5BSlow%5C%5D%20ReplicaSet%20Should%20scale#b75045e2cb613e12dca1)

This is affecting multiple jobs on the [release-master-blocking](https://k8s-testgrid.appspot.com/sig-release-master-blocking) testgrid dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22). Is there work ongoing to bring this job back to green?

[triage cluster b75045e2cb613e12dca1](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-autoscaling%5C%5D%20%5C%5BHPA%5C%5D%20Horizontal%20pod%20autoscaling%20%5C(scale%20resource%3A%20CPU%5C)%20%5C%5Bsig-autoscaling%5C%5D%20%5C%5BSerial%5C%5D%20%5C%5BSlow%5C%5D%20ReplicaSet%20Should%20scale#b75045e2cb613e12dca1)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:39
timeout waiting 15m0s for 5 replicas
Expected error:
    <*errors.errorString | 0xc4202cafe0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:128
```

Suspect range from [gci-gce-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial): https://github.com/kubernetes/kubernetes/compare/060b4b8b8...51244eb0f

Suspect range from [gci-gke-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial): https://github.com/kubernetes/kubernetes/compare/b1e2d7a9d...82a52a901

**Comment by spiffxp** [comment]
@kubernetes/sig-autoscaling-test-failures

**Comment by MaciekPytel** [comment]
@DirectXMan12 the moment this test started failing coincides exactly with merging of https://github.com/kubernetes/kubernetes/pull/53743. Which BTW is a very large commit to HPA which was not tagged with sig-autoscaling and therefore slipped us completely.

I think we should revert #53743 for now and merge it again after fixing it.

cc: @mwielgus

**Comment by DirectXMan12** [comment]
I apologize for missing the SIG autoscaling label (although I'm surprised that the bot didn't complain about it).

I'll track down why it's failing.

**Comment by DirectXMan12** [comment]
found the issue.  When you write your scaleTargetRef, it's important to actually specify an `APIVersion` field now (even if just the group, without the version).  It didn't matter before, but it was still poor form to just refer to `kind: ReplicaSet` without `apiVersion: extensions` (or `apps`).

**Comment by DirectXMan12** [comment]
will have a PR in a couple minutes

**Comment by DirectXMan12** [comment]
... aaand the `apps` API group doesn't set registry subresource versions correctly, so the group-version on scales returned by `apps` is `apps/v1beta2` (incorrectly).

**Comment by DirectXMan12** [comment]
PR posted ^

**Comment by spiffxp** [comment]
PR's continue to await review

**Comment by spiffxp** [comment]
/reopen
I'm still seeing this here https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial

Unless we decide to punt that job from release-master-blocking, this is now impacting 1.9.0-alpha.3 (https://github.com/kubernetes/sig-release/issues/27)

**Comment by spiffxp** [comment]
/status approved-for-milestone
(new comment since the bot doesn't accept edits) I can type, I swear

**Comment by abgworrall** [comment]
I'm also seeing this on our OS image validation testgrid: https://k8s-testgrid.appspot.com/sig-node-cos-image#e2e-gce-cosbeta-k8sdev-serial

**Comment by DirectXMan12** [comment]
Looking into the current set of failures

**Comment by DirectXMan12** [comment]
Looking at the failure logs, I'm seeing

```
horizontal.go:189] failed to query scale subresource for Deployment/e2e-tests-horizontal-pod-autoscaling-zxc9r/test-deployment: the server could not find the requested resource
```

So, I tried reproducing locally (provider=local, hack/local-up-cluster.sh), and I cannot.  HPA seems to be able to fetch scale properly for replicasets and deployments in a vanilla fresh cluster-up environment.  Is there something special about the way we stand up those test environments?

**Comment by frobware** [comment]
Going to investigate this too.

**Comment by frobware** [comment]
> I'm still seeing this here https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial

@spiffxp this appears to be passing now. As highlighted by @MaciekPytel on slack/sig-autoscaling, #55413 might be significant here.

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
Agree, this has moved off of release-master-blocking, with the exception of soak-gci-gce which I would like to kick out of the list of blocking tests wholesale anyway.

This is still affecting some upgrade tests, which I'm not actively watching yet.  Once we hit code freeze, I will be watching them, and will bump priority accordingly.  Does something need to be cherry-picked into the release-1.8 branch?
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade
- [triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-autoscaling%5C%5D%20%5C%5BHPA%5C%5D%20Horizontal%20pod%20autoscaling%20%5C(scale%20resource%3A%20CPU%5C)%20%5C%5Bsig-autoscaling%5C%5D%20%5C%5BSerial%5C%5D%20%5C%5BSlow%5C%5D%20ReplicaSet%20Should%20scale)

**Comment by dims** [comment]
/assign @frobware 

@frobware feel free to reassign/unassign, i assigned it based on your comment 2 days ago

**Comment by spiffxp** [comment]
/close
I'm no longer seeing this on sig-release-master-blocking or sig-release-master-upgrade

**Comment by spiffxp** [comment]
/reopen
FYI @kubernetes/sig-autoscaling-test-failures now that some of the upgrade jobs have been fixed, I'm seeing this again in a number of jobs:
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-master
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-cluster
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.8-downgrade-cluster

eg: [triage cluster b75045e2cb613e12dca1](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BHPA%5C%5D%5C%20Horizontal%5C%20pod%5C%20autoscaling%5C%20%5C(scale%5C%20resource%3A%5C%20CPU%5C)%5C%20%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D#b75045e2cb613e12dca1)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:41
timeout waiting 15m0s for 3 replicas
Expected error:
    <*errors.errorString | 0xc4202d9330>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:122
```

[triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BHPA%5C%5D%5C%20Horizontal%5C%20pod%5C%20autoscaling%5C%20%5C(scale%5C%20resource%3A%5C%20CPU%5C)%5C%20%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D)

@DirectXMan12 @frobware (taking a total guess) are there fixes that need to be cherry-picked into release-1.8?

**Comment by DirectXMan12** [comment]
@spiffxp I'd guess that we'd have to cherry-pick the test suite fixes back to the 1.8 test suite if you've got instances of the 1.8 test suite running against 1.9 code.

**Comment by DirectXMan12** [comment]
The fix needed should be #54586

**Comment by DirectXMan12** [comment]
I've reproduced locally.  The backport seems to fix the issue (just doing one final test run).  Should have a PR up shortly.

**Comment by spiffxp** [comment]
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by spiffxp** [comment]
/close
Thanks for the backport, I now see green for this test
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-master
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-cluster
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.8-downgrade-cluster
