### ISSUE TITLE
kubernetes / multi master cluster, apiserver data divergenge

### ISSUE THREAD

**Issue by fvigotti** [kubernetes/kubernetes#54576]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kubectl logs sometimes didn't work 
fail with error: `Error from server (NotFound): the server could not find the requested resource ( pods/log xmr-b0v3d)` but not always.. , after investigation 
I've found that for some pods, on one master servers for the same resource , ie : 
( given a pod xmr-b0v3d in "default" namespace ) 
`curl http://localhost:8080/api/v1/namespaces/default/pods/xmr-b0v3d/log?follow=true&tailLines=10`
I get results... on the other two master nodes I get 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource ( pods/log xmr-b0v3d)",
  "reason": "NotFound",
  "details": {
    "name": "xmr-b0v3d",
    "kind": "pods/log"
  },
  "code": 404
}
```

**What you expected to happen**:
all apiservers should be backed by same data 

**How to reproduce it (as minimally and precisely as possible)**:
I really don't know ;) 

**Anything else we need to know?**:
etcd cluster v3 is  healthy
```
https://xxxxx:2379 is healthy: successfully committed proposal: took = 1.555631ms
https://xxxxx:2379 is healthy: successfully committed proposal: took = 1.852799ms
https://xxxxx:2379 is healthy: successfully committed proposal: took = 2.463205ms
```
and  obviously all nodes points to sam etcd cluster
**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.7

I'm asking you what command I can use to better investigate this problem I'll be happy to deeply inspect this problem...

now what another weird things is that restarting kubelet on those master-nodes seems to fix the issue !?!?! after kubelet (only the kubelet) restart 
`curl http://localhost:8080/api/v1/namespaces/default/pods/xmr-b0v3d/log?follow=true&tailLines=10`
return results! ( port 8080 is binded to apiserver, why the kubelet influence that ? ) 

Thank you,
Francesco

**Comment by liggitt** [comment]
are you running with `--etcd-quorum-read=true`?

**Comment by fvigotti** [comment]
yes :) 
I'm still trying to understand why kubelet restart seems to resolve the issue ? even if then I've found other /log urls missing, again then a restart seems to resolve, but then again.. seems that sometimes those /log urls are missing on some master-nodes , 

does those urls are ridden from kubelet instead of etcd from the apiserver? 

what I can do to further investigate the problem ?

thank you,
Francesco
