### ISSUE TITLE
wrong controller-master detection

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#54570]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
/kind bug

**What happened**:
[This line](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blobDiskController.go#L546) is buggy. 
```go
func (c *BlobDiskController) shouldInit() bool {
	if os.Args[0] == "kube-controller-manager" || (os.Args[0] == "/hyperkube" && os.Args[1] == "controller-manager") {
		swapped := atomic.CompareAndSwapInt64(&initFlag, 0, 1)
		if swapped {
			return true
		}
	}
	return false
}
```
It prevents running hyperkube from other path. In fact, it shouldn't assume the code is just running in controller master at all, especially when cloud provider is running out of tree.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
@kubernetes/sig-windows-bugs 
@andyzhangx 
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@rootfs This code logic is to make sure the blobController only initialize once in controller-manager other than in other component, e.g. kubelet, do you have any suggestion to use similar implementation? Current design is azure pv code could only run in controller-manager.

**Comment by rootfs** [comment]
If the idea is to exclude other components, I prefer a black list, not a broken white a list as here.

**Comment by rootfs** [comment]
@andyzhangx there are multiple issues with this code:

- It shouldn't bootstrap any storage accounts at all. This is really poor user experience. Not all users want to/will use azure disk. These storage accounts are yet created without any explicit documentation or prior warning.

- Even with these storage accounts, it doesn't help accelerate PV provisioning.

- This is the only place to init [accounts here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blobDiskController.go#L327). If controller master is launched from a different path (which is *usually* the case), then `accounts` never gets initialized, and will cause a panic when being used.

**Comment by rootfs** [comment]
@kubernetes/sig-storage-bugs @kubernetes/sig-windows-bugs @kubernetes/sig-azure-misc

**Comment by andyzhangx** [comment]
@rootfs thanks for the check, put the storage accounts bootstrap in azure_dd/azure_provision.go could be more appropiate: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_provision.go#L68
that is only user select `Shared` kind and would like to create blob disks, then those accounts would be created and it would only initialize before first PVC is created.

**Comment by rootfs** [comment]
@andyzhangx SGTM, looking forward to your PR and 1.7/1.8 cherry picks

**Comment by andyzhangx** [comment]
I will attend a conf next week, will work out this PR and CreateVolume PR the week after next week.

**Comment by andyzhangx** [comment]
update: code complete, I need to do some test before sending PR:
https://github.com/andyzhangx/kubernetes/commit/bb42103fcafdd989e8776abbc8374c2c592fc356
