### ISSUE TITLE
Bring all prom-to-sd container to the same image version

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#54583]
Currently there are several, and some of them have problems with excessive logging

@loburm could you please do this?

**Comment by skeller88** [comment]
Any estimate on this fix? Asking because I'm seeing the issue referenced in https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/43

**Comment by loburm** [comment]
It was already fixed in head and in 1.8 long time ago. Fix was merged to 1.7 recently, so we are just waiting for new patch release.
