### ISSUE TITLE
chown: changing ownership of ‘/var/lib/postgresql/data’: Operation not permitted, when running in kubernetes with mounted "/var/lib/postgres/data" volume

### ISSUE THREAD

**Issue by arnold0617** [kubernetes/kubernetes#54601]
I am running docker.io/postgres:9.6.5 in kubernetes, pod crash loop back off all the time.

I found this message in log, "chown: changing ownership of ‘/var/lib/postgresql/data’: Operation not permitted"

**Comment by arnold0617** [comment]
I fixed this problem.

This is caused by the parameter of nfs,  after setting nfs mount parameter like below,  it works fine.
`/nfs/data *(rw,sync,no_subtree_check,no_root_squash)`

**Comment by mpun** [comment]
It worked for me. You saved my day.

**Comment by GalochkinKirov** [comment]
It does not work for me.

**Comment by GalochkinKirov** [comment]
To solve this problem do it:
1. Set NFS export dir:
"nfs/main *(rw,sync,no_subtree_check,no_root_squash)"
2. Set NFS volume like this:
```
  nfs:
    server: ***
    path: "nfs/main/data"
```
3. Update your entity configuration:
```          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              readOnly: false```

**Comment by malcolmm83** [comment]
I guess the only alternative really is run as non-root?

**Comment by GalochkinKirov** [comment]
No, it is not alternative.

**Comment by mhellsten** [comment]
I got past it by setting userid and groupid to 999 on the container (the IDs of the mysql user and groups inside the container).

**Comment by ThePlenkov** [comment]
@mhellsten did you use security context for this?
