### ISSUE TITLE
kubectl describe priorityclass show the wrong format for value and GlobalDefault

### ISSUE THREAD

**Issue by wackxu** [kubernetes/kubernetes#54608]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

**What happened**:

`kubectl describe priorityclass`  show the wrong format for value and GlobalDefault

```
name:           high-priority
Value:          %!s(int32=1000000)
GlobalDefault:  %!s(bool=false)
Description:    This priority class should be used for XYZ service pods only.
Annotations:    <none>
Events:         <none>
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Mikulas** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/60149
/close
