### ISSUE TITLE
node name override

### ISSUE THREAD

**Issue by utsav2307** [kubernetes/kubernetes#54626]
I am creating external load balancer in AWS using kubernetes, for that i provided --cloud-provider=aws option in my kube-apiserver, kubelet and kube-controller manager, and everything worked fine. But I noticed the name of the nodes, now Kubernetes is setting nodename by the node's IP like "ip-xx-xxx-xx-x.ec2.internal". Earlier it was proper hostname which i provided in kubelet as "--hostname-override=xxxx".

Any idea what can be the issue here and how it can be resolved?

**Comment by dixudx** [comment]
/sig aws
@utsav2307 Dup of #54482. I close it.
/close
