### ISSUE TITLE
Can't start e2e service "kubelet" on local e2e_node test

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/kubernetes#54622]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I want to run `e2e_node` test on `local` (ubuntu) with this cmd:
```shell
make test-e2e-node FOCUS="\[Feature:Docker\]" PARALLELISM=1
```

**What you expected to happen**:

e2e_node test pass

**How to reproduce it (as minimally and precisely as possible)**:

```shell
make test-e2e-node FOCUS="\[Feature:Docker\]" PARALLELISM=1
```

**Anything else we need to know?**:

After go into details I got this info:
```shell
invalid argument "--eviction-hard" for --feature-gates: malformed pair, expect string=bool
```
I think e2e_node start kubelet by this cmd `--feature-gates  --eviction-hard "memory.available..."` as  `feature-gates` is not set by default in [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/services/kubelet.go#L170):

```go
"--feature-gates", framework.TestContext.FeatureGates,
```
After fix it temporarily I got one more error about this issue:

```shell
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. 
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```shell
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```shell
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```shell
Linux cenph 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

I will send a PR to fix this if it is confirmed.

**Comment by Random-Liu** [comment]
@ScorpioCPH If your environment doesn't support swap, you could override kubelet flag with:
```
TEST_ARGS="--kubelet-flags=--fail-swap-on=false"
```

**Comment by ScorpioCPH** [comment]
@Random-Liu Thanks!

Could you take a look at this [PR](https://github.com/kubernetes/kubernetes/pull/55475):

- append `--feature-gates` if needed.
