### ISSUE TITLE
Next 1.8.2 sync of pubished staging/ repos

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#54638]
Now that https://github.com/kubernetes/kubernetes/releases/tag/v1.8.2 exists, I propose to do the next push of the staging repos.

As for the previous pushes:
- the push script: https://gist.github.com/anonymous/60717981ae44ed23bf52809a1e7d1356 (updated Oct 27)
- the last heads for a potential rollback: https://gist.github.com/anonymous/f24e88ebe3b5b3846d9d4c07dc746dde (updated Oct 26)
- the test script: https://gist.github.com/anonymous/f228c70627170a30a9c69f1789181594 (updated Oct 27)

The test script was run successfully.

We restrict the push to master and the 1.8 branches because https://github.com/kubernetes/kubernetes/pull/53583 blocks 1.7 right now (and probably similarly for 1.6, 1.5 if we want to keep them up-to-date at all).

**Comment by caesarxuchao** [comment]
I will test it today. https://github.com/kubernetes/kubernetes/pull/53583 is merged, will you rewrite the script or do that as a next step?

**Comment by sttts** [comment]
had seen wrong Godeps.json k8s.io/* revisions pointing to pre-august commits for 1.7 because not much changed in that branch. Have to check and probably add a workaround to use a minimum base commit where we switched the algorithm.

**Comment by caesarxuchao** [comment]
Can you share the setup of the kube-glide-test directory?

Other tests passed.

**Comment by sttts** [comment]
It's github.com/sttts/kube-glide-test. Updated the test https://gist.github.com/anonymous/f228c70627170a30a9c69f1789181594.

**Comment by sttts** [comment]
I have updated the sync.sh script with the HEADs of another run. All tags are the same as yesterday. After the federation removal PR went in, @marun and others need this as a baseline to move to the external repo.

**Comment by caesarxuchao** [comment]
Tests for the latest code in sttts repo passed. @eparis I think it's good to go.

**Comment by eparis** [comment]
https://gist.githubusercontent.com/anonymous/60717981ae44ed23bf52809a1e7d1356/raw/43c9e37ab0a1d76c29bbec766ac77ee03622af04/sync.sh

ran successfully to completion.
