### ISSUE TITLE
HPA scale-up/scale-down e2e tests failing on large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#54637]
The following 2 HPA tests are failing continuously on our [5k-node correctness job](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness):

- Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 1 pod to 2 pods
- Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] ReplicationController light Should scale from 2 pods to 1 pod

due to timeout:

```
timeout waiting 15m0s for 2 replicas
```

The job is part of release-master-blocking suite - so this needs to fixed asap.

cc @kubernetes/sig-autoscaling-bugs

**Comment by shyamjvs** [comment]
@DirectXMan12 - Assigning this to you as you're the expert here I guess :) Feel free to redirect as apt.

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-misc @porridge

**Comment by MaciekPytel** [comment]
@shyamjvs Those tests are broken in general, not just in scalability. Ref: https://github.com/kubernetes/kubernetes/issues/54574. I'll close this since it's effectively a duplicate.

**Comment by shyamjvs** [comment]
I'm seeing them pass on gce at smaller scale - https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce

**Comment by shyamjvs** [comment]
Besides I think there might be a different issue in large clusters as they have been failing for a month now. While #54574 seems to be a recent one.

**Comment by MaciekPytel** [comment]
Ok, sorry for closing the issue then, reopening it.

**Comment by shyamjvs** [comment]
Bumping the priority as this is blocking 1.9-alpha release. Umbrella issue - #55194

**Comment by shyamjvs** [comment]
Friendly ping @DirectXMan12 - would you have time to take a look into this?

**Comment by shyamjvs** [comment]
Friendly ping @DirectXMan12 - this is now one among the only two tests failing in our [release-blocking scalability job](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness). Note that this is blocking the upcoming release and needs to be fixed asap.

**Comment by shyamjvs** [comment]
Didn't look deeper, but from the c-m logs it seems like HPA failed to get the pod metrics, with multiple such errors:

```
E1109 08:54:37.215154       7 horizontal.go:189] failed to compute desired number of replicas based on listed metrics for ReplicationController/e2e-tests-horizontal-pod-autoscaling-5t6cf/rc-light: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
I1109 08:54:37.215201       7 event.go:218] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"e2e-tests-horizontal-pod-autoscaling-5t6cf", Name:"rc-light", UID:"67a71beb-c52b-11e7-ad28-42010a8e0002", APIVersion:"autoscaling/v2beta1", ResourceVersion:"1597455", FieldPath:""}): type: 'Warning' reason: 'FailedGetResourceMetric' unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by shyamjvs** [comment]
Looks like this issue got resolved. It's green for our run from today - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness
The failures here seem correlated to the ones in [gci-gce-serial](https://k8s-testgrid.appspot.com/google-gce#gci-gce-serial) job, for which it started being green since run 2498.
From the [diff](https://github.com/kubernetes/kubernetes/compare/3e1f81d97...bd36cfdec), @liggitt 's PR https://github.com/kubernetes/kubernetes/pull/55413 seems to have done the trick.

Closing this issue.. we can reopen if we start seeing it again.
/close

**Comment by spiffxp** [comment]
/reopen
@shyamjvs I'd rather take testgrid's word than have to interpret the results here.  I agree we've worked out the individual test failures.  But, the job is still failing. I need to see a green run to consider this closed.

**Comment by spiffxp** [comment]
/close
argh my bad I totally misread which issue I was looking at, _yes_ this test has been addressed, don't mind me

**Comment by porridge** [comment]
@shyamjvs please reopen, this is back to red today: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/28

**Comment by shyamjvs** [comment]
Sigh!

**Comment by shyamjvs** [comment]
cc @mwielgus @crassirostris (whom we had discussion with today)

**Comment by mwielgus** [comment]
This doesn't look like sig-autoscaling / HPA issue. The tests work fine on small clusters. It fails on big, however the size of HPA-scaled deployment is exactly the same. It fails with an error indicating Heapster node scraping problems. Leaving the final decision to @crassirostris as he is the current on-call for the monitoring team. From the sig-autoscaling perspective this issue is not a release blocking one, however:
* it should be investigated by the monitoring team ASAP
* scalability team should check what is the tipping point (500, 1000, etc)

**Comment by crassirostris** [comment]
This doesn't look like a regression: these tests were consistently failing on large scale since the beginning, so I also don't think we should block the release on this.

**Comment by shyamjvs** [comment]
FYI - this was passing reasonably continuously on gke-2000
https://k8s-testgrid.appspot.com/sig-scalability-gke#gke-large-correctness

**Comment by shyamjvs** [comment]
But it was failing almost always for gce (since the start of those jobs).

**Comment by porridge** [comment]
Since these tests are now disabled, I think we should file a new issue against @kubernetes/sig-instrumentation-bugs to make heapster scale, and close this one?

**Comment by shyamjvs** [comment]
Sg. Could you file the issue?

**Comment by porridge** [comment]
/close
in favor of #55887
