### ISSUE TITLE
Kubernetes HPA with custom metrics in 1.7

### ISSUE THREAD

**Issue by tesi-nahid** [kubernetes/kubernetes#54633]
I could not find how can I do custom metric (query per second) in kubernetes 1.7 .can you show me which  steps I should follow?

I found these 3 structure,but they are not the same.
[https://docs.bitnami.com/kubernetes/how-to/configure-autoscaling-custom-metrics/](url)

[https://github.com/mwielgus/kubernetes.github.io/blob/custom-metrics/docs/user-guide/horizontal-pod-autoscaling/index.md#support-for-custom-metrics](url)

[https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/](url)

**Comment by tesi-nahid** [comment]
sig/autoscaling 
/sig/autoscaling

**Comment by mattjmcnaughton** [comment]
Hi @tesi-nahid !

I think the Kubernetes 1.7 documentation on hpa with custom metrics could be helpful - here's the link: https://v1-7.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics

Let me know if you have any questions :)

**Comment by tesi-nahid** [comment]
Thank you @mattjmcnaughton.
I have some  problem with 
1-enabling aggregation layer
2- adding  autoscaling/ v2beta1  to apiserver

**Comment by mattjmcnaughton** [comment]
Cool - do you mind describing more about the problems that you're facing? I.e. posting error messages/stack traces/etc? Thanks!

**Comment by tesi-nahid** [comment]
thank you for your reply,the scenario that i am working is I have one cluster with 2 nodes,one amd64  and one raspberry pi ,hpa autoscalling for cpu-percent is working,but I  do not know how to do autoscalling for Qps(query per second)
 could you please tell me how can I do these configurations?
1- how can I enable aggregation layer?or where should I put this flag "--enable-aggregator-routing=true" ?
2-when I am adding these flags "
--requestheader-client-ca-file=<path to aggregator CA cert>
--requestheader-allowed-names=aggregator
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key> "
my cluster is not finding the server host and" Kubectl get nodes " is not working.
or adding "--runtime-config=api/all=true"  

3-for enable custom metric I just used "kubelet --enable-custom-metrics" in my nods,is it enough for enableing custom metrics?

**Comment by mattjmcnaughton** [comment]
@tesi-nahid Thanks for the extra detail, and apologies for the late response. 

This tutorial may be helpful: https://docs.bitnami.com/kubernetes/how-to/configure-autoscaling-custom-metrics/

If you have additional specific questions, I'd recommend the #sig-autoscaling channel on the kubernetes Slack. A lot of very knowledgeable, friendly people who will be able to help :)
