### ISSUE TITLE
Influxdb-related e2e shouldn't run when influxdb is not enabled on the cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#54636]
The e2e test 'Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.' is running in our [gce-scale-correctness job](https://k8s-testgrid.appspot.com/sig-scalability-gce-scale#gce-scale-correctness) and failing, while we're using the 'standalone' mode for monitoring (ref: https://github.com/kubernetes/test-infra/blob/67bc30718f5468cdd64675c2c710118f34af33c3/jobs/env/ci-kubernetes-e2e-gce-scale-correctness.env#L14) which iiuc doesn't start influxdb.

@fgrzadkowski - Assigning this to you. Feel free to redirect as apt.

cc @kubernetes/sig-instrumentation-bugs

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-misc @porridge

**Comment by shyamjvs** [comment]
This job is part of [master-release-blocking suite](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness). Bumping priority.

**Comment by loburm** [comment]
@shyamjvs You can assign this bug to me. And looks like the link to the job is broken, could you give a correct one?

**Comment by shyamjvs** [comment]
Sorry about it.. I renamed the dashboard in the meanwhile. Here's the one - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness

**Comment by spiffxp** [comment]
/status approved-for-milestone
accepting this as a member of @kubernetes/sig-scalability-bugs

**Comment by shyamjvs** [comment]
Bumping the priority as this is blocking 1.9-alpha release. Umbrella issue - #55194

**Comment by shyamjvs** [comment]
ping @fgrzadkowski @loburm
