### ISSUE TITLE
[Feature Request]: support custom JWT authentication

### ISSUE THREAD

**Issue by liubog2008** [kubernetes/kubernetes#54632]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

Kubernetes now can't authenticated by bearer token which is in JWT format. Opaque token can be authenticated by Webhook, which is not very suitable for JWT now.

**What you expected to happen**:

A plugin for JWT authentication, which support custom JWT (from oauth2 access_token) validation

**Anything else we need to know?**:
- why not use OIDC?
OIDC is used for client-app, for example, a web app. Backend of web app use id_token to authN user. When backend to access protected resource, access_token is used.
In our system, a kubernetes cluster is trusted as an API service but not a client app. We hope allow many clients with different client_id to visit apiserver. However, validator of OIDC id_token only accepts one client_id (apiserver only accept one client_id in args too).

- why not web hook
JWT can be validated without additional TokenReview request.

**Environment**:
- Kubernetes version 1.8

**Comment by ericchiang** [comment]
> In our system, a kubernetes cluster is trusted as an API service but not a client app. We hope allow many clients with different client_id to visit apiserver. However, validator of OIDC id_token only accepts one client_id (apiserver only accept one client_id in args too).

You might want to look at the authorized party claim which is used to indicate when a client requests tokens on behalf of other clients https://openid.net/specs/openid-connect-core-1_0.html#IDToken

I'm a little confused about what's being proposed in this feature. Do you just want to skip the audience check?

**Comment by liubog2008** [comment]
1. A token can be validated by multiple clusters
2. Dynamically client registration

I have tried authorized party claim, but `azp` is confusing and only dex implements it. And `dex` can't solve a problem that a powerful "client" will be set in apiserver  and all other clients need to trust it or be trusted by it.

**Comment by ericchiang** [comment]
I don't think this is going to progress forward unless there's a specific proposal about what should be implemented. "support custom JWT authentication" is too broad.

How would this be configured? What standards does it use? How would you express the validation?

**Comment by ericchiang** [comment]
Going to close this for now.  Would like to see a more concrete proposal since this issue is too broad.

/close
