### ISSUE TITLE
Pod Lifecycle: Escalate container failures to the pod

### ISSUE THREAD

**Issue by shrenikd** [kubernetes/kubernetes#54648]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Use Case 1:
A pod (in a deployment spec) contains container 'app' developed by team A (app developers) and container 'monitor' developed by team B (platform developers). The containers share a volume containing critical assets for the 'app' container. The 'monitor' container monitors and updates a those assets. Some asset updates require a restart of the 'app' container (hard requirement) and team B, as the platform supporting team, wants to provide a solution to restart the 'app' container without team A requiring to do anything about it. All team A must do is make sure their app can handle a graceful shutdown.

The aforementioned issue could be solved in the following ways, all of which are unappealing due to various reasons:
a) The 'monitor' container can send a SIGTERM to the 'app' container process (https://github.com/kubernetes/kubernetes/issues/1615).
b) Team B needs a way to add a liveness probe on the container 'app' without overwriting team A's liveness probe, i.e. support multiple liveness probes (https://github.com/kubernetes/kubernetes/issues/37218).
c) The 'monitor' container can talk to the kube-apiserver to do a pod restart by changing the Deployment spec. This requires pods to have ACLs to the apiserver(s), which we don't want.

Use Case 2:
A pod contains a container, among others, that encounters an I/O issue on the host its running on, for example low disk space or network issue, due to which it constantly fails and the kubelet constantly restarts it. In this scenario, it would be nice to be able to re-bounce the pod to a different host altogether under some controlled conditions. Sure the 'different host' may not be guaranteed, however, at least it presents an opportunity to do so. This may be against the semantics of a pod as defined today, however, this serves as an example where pod re-bounce is the only solution.

**What you expected to happen**:
The ability to declare a pod-level policy that declares the appropriate action for container failures escalated to the pod. For example, upon a container failure, a pod can decide to continue restarting that container alone for N retries (N could be infinity) and finally give up by marking the pod unhealthy so that manual actions can be taken. Another example is a policy where a pod could, upon container failure, decide to restart *all* containers. In yet another example, a pod may also have a policy where, upon container failure, the pod decides to kill itself entirely so that kube can rebounce it.

One of the more popular example with similar semantics is the 'supervision' mechanism in Akka.

**Comment by JnMik** [comment]
I think it would really be a must for a pod to be able to restart itself on a container failure, in some scenarios.
Simply because more and more kubernetes apps (vault, linkerd, istio, etc) uses sidecar containers, and if the core of these engines was not up and running when the application boot, the admission controller won't inject the sidecar probably, therefore the container will probably fail and reboot in loop because it needs a sidecar that isn't there and will never be. (The sidecar will never be injected, because the pod don't reload).

**Comment by kvp-cs** [comment]
There are so many voices requesting for this feature with so many live/genuine reasons and yet there is no response from the k8 community!
Any ideas on how to make this request get more attention? At least want k8 team to look into the concern and tell what they think about it.
