### ISSUE TITLE
Adding tag annotations on service manifest for ELB does not trigger update on AWS

### ISSUE THREAD

**Issue by nicolasbelanger** [kubernetes/kubernetes#54642]
**BUG REPORT**:
/kind bug
/sig aws

**What happened**:
Adding this annotation to an existing service: `{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}}` did not trigger an update on AWS ELB (no new tags).

**What you expected to happen**:
Expected to see those 2 new tags under the existing ELB:  `team=devops,env=qa`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service without annotation
2. Add the annotation `{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}}`
3. No tags on AWS

**Anything else we need to know?**:
Creating a new service WITH the annotation will create the expected tags on AWS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.9
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): Linux ip-xxxxx 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux
- Install tools:
- Others: Using Kops

**Comment by sbourgault-ssense** [comment]
+1

**Comment by fmedery** [comment]
+1

**Comment by gdecroux** [comment]
+1

**Comment by hetile-ssense** [comment]
+1

**Comment by yveschappe** [comment]
+1
