### ISSUE TITLE
FR: add "open in cloud shell" button to readme

### ISSUE THREAD

**Issue by marcacohen** [kubernetes/kubernetes#54646]
/kind feature

I'm happy to submit a PR to do this but wanted to first see if this is desired...

Google Cloud has a new feature called "Open in Cloud Shell" which supports invoking a URL that auto-starts a cloud shell session (via in-browser ssh to an auto-provisioned VM) with an auto-cloned repo specified in the URL. This might make a nice addition to the "To start developing Kubernetes" section of the readme file, the idea being to present a button that pops you into a cloud shell session with the k8s source code auto-cloned for you and ready to go.

Any interest? If so, I'd be happy to submit the PR. Thanks for your consideration.

**Comment by marcacohen** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by brendandburns** [comment]
I think that anything on the main page needs to be vendor/platform nuetral.

This seems like a natural thing to add to the vendor-specific pages like:
https://kubernetes.io/docs/getting-started-guides/gce/

But we shouldn't add this to any of the main pages.

Thanks
--brendan

**Comment by marcacohen** [comment]
Hi Brendan! Hope you are well.
That makes sense -- I'll look into sending a PR for the vendor specific page.
Thanks!
