### ISSUE TITLE
.proto files in k8s.io/api have outside refs

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#54650]
the proto files that are generated have outside refs. Probably just need two scripts.

https://github.com/kubernetes/api/blob/master/core/v1/generated.proto#L24

**Comment by smarterclayton** [comment]
"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto` should have a `-` in front of it when we generate.  I suspect that's the primary cause.  go-to-protobuf doesn't have a dependency pruner on the IDL because i didn't care enough.
