### ISSUE TITLE
Develop process for accepting examples

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#5465]
It's great to have people contribute examples. We should document the process for doing this. What files we need. e2e requirements. Best practices. How to deal with Docker images needed for the examples (if they need to be push?).
@jayunit100 @brendandburns

**Comment by jayunit100** [comment]
One idea:  the first step will be to say all examples need to have  source for containers which is in a folder called *containers/* that is in the top level so other projects like e2e tests depend on it as well.

**Comment by satnam6502** [comment]
I've been thinking for a while that we should put all the container sources in one place to make it easier to understand how many containers we use, what base images we use (to permit factorization) etc.

**Comment by jayunit100** [comment]
to get the details started, can i suggest something like this?

```
/kubernetes/containers > tree
.
├── build-and-release.sh
├── io.redis
│   └── Dockerfile
├── kube-api
│   └── Dockerfile
├── net.php.web
│   └── Dockerfile
├── org.apache.bigtop.bps-data-generator
│   └── Dockerfile
└── org.google.golang
```

**Comment by timothysc** [comment]
IMHO we should have 2 tao tse docs: 

1. tao tse e2e tests
2. tao tse examples

**Comment by jayunit100** [comment]
- agreed, two docs.  the question is : what is shared between e2e tests and examples?  One main thing is the *Dockerfile* itself.  so this lends us to the main question...
- the *main question* i have is : As part of the process,  shall we focus on dockerfiles as a first step?  if we can structure the way they are handled so that they arent scattered all over, that naturally paves a path to process for submitting *examples* AND porting examples into *e2e* tests.
- Additionally, solving the dockerfile sprawl will help make sure kube is secure and prevent the examples from bitrotting (b/c the examples will be testable themselves if there is a machin interprabble, structured model for how containers are build/released).

**Comment by jayunit100** [comment]
(bump) @satnam6502 @brendandburns :).  any updated thoughts on this?   I'd like to get some shell of a system in place that we could start cleaning examples up slowly into

**Comment by satnam6502** [comment]
@jayunit100 : utterly swamped right now, but I shall try to respond later if I can -- sorry for the delay.

**Comment by jayunit100** [comment]
if anyone can  suggest a minimal viable first iteration , then  we can start moving forward and try some things out.  ive suggested just one idea above, but not married to it.

**Comment by countspongebob** [comment]
Newish to the project, so please be gentle. :-)

We had a longish internal conversation on this today. We are working in two areas related to the topic. The first is a bunch of showcase setup (cassandra, opscenter, load generation, etc) that will be good example code. We have been using @brendandburns code as our starting point. So, having a contribution guideline for this gets a +1 from us.

The second is that we are having stability issues with our coreos/flannel/kubernetes configuration. To give a simple example, when "things aren't working" pod-to-pod communications are impacted.  We've been considering a test scenario where we deploy a cluster, and then deploy test containers into the cluster that test communications with each other to validate our underlying system (coreos/flannel in this case) has met requirements.  Perhaps this is a general purpose issue/test and is a poor example?

Would the kubernetes community consider this to be an integration test, an e2e test, or some flavor of an "example" where the deployment environment for the cluster is the example?

I think the project is not and should not be baking in environmental dependencies (like the host os or networking fabric) but we still need a way to validate that our entire stack is working (or at least working as far as kubernetes is concerned).

Very much appreciate any guidance on this.

**Comment by satnam6502** [comment]
So, indeed, right now things are scattered around. For example, Dockerfiles are in contrib/for-tests. contrib/for-demos etc. and in cluster/addons/.... and in other GitHub repos (cAdvisor). Some of this is organic, some of this reflects the fact that some Docker images have multiple uses (examples, e2e tests etc.)

First, I think we should not conflate the following situations:
* Making sure that the Kubernetes system is not prone to breakage due to an image change.
* Making sure that none of the images that Kubernetes depends on bit-rots.
* Making sure the examples build (and perhaps work).
* End to end tests for the Kubernetes system itself.
* Tests to make sure the examples work.

For this issue, let's just focus on what we can do to make it easier to accept examples.
Having a systematic place to put all the images might be nice -- but I think there is also an argument or having just one directory for an example which contains all its source. For example, for `myapp` I would put it in `examples/myapp`.

Now, how to prevent bit-rot? Why not start with a really simple approach and if that does not work we can try something more elaborate. Why not have a `examples/Makefile` that has a `build` rule that is designed to build each example. So when you contribute `myapp` you add the appropriate code to the build rule to compile your code, generate your Docker images etc. so at least that helps to stop bit-rot.

Then to keep the examples healthy we could ask for things that look like our e2e tests which you would add to `examples/e2e` and these an check to make sure the examples still work. We could use the same mechanism that we have in place for the core e2e tests in `tests/e2e` or we could try something simpler.

@zmerlynn @ixdy

**Comment by jayunit100** [comment]
Hi satnam, the `Makefile` suggestion does make sense as a stop-gap, assuming no unified resource for kube containers is going to be created.

**Comment by satnam6502** [comment]
Shall we consider a few specific examples? Shall we consider how the k8petstore example would work in such a scheme?

**Comment by jayunit100** [comment]
Sure. I can upgrade k8petstore in a pr which implements this scheme and we can bat it around some till we are happy with it as a example others can follow

**Comment by jayunit100** [comment]
there is one more idea to consider, docker secured builds.  lets consider that before we mandate dockerfiles to be in the repo.  @mattf used it in his spark pr https://github.com/GoogleCloudPlatform/kubernetes/pull/5602

**Comment by satnam6502** [comment]
Thanks. I don't know what a Docker secured build is... let me investigate!

**Comment by jayunit100** [comment]
Lets make sure to synergize with #6222 above ^^^ it might solve this issue.

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
how does https://github.com/kubernetes/contrib compare to examples?

**Comment by jayunit100** [comment]
https://github.com/kubernetes/kubernetes/issues/5465 @chrislovecnm heres the dupe :) ?

**Comment by jayunit100** [comment]
Can we close this in favor of  26023 ^ ?  the newer issue solves this without loss of generality.  And we already know that the `examples/` is going to obsoleted soon enough probably

**Comment by chrislovecnm** [comment]
@jayunit100 Why would yah say that `examples/` is going to be obsoleted?  Say it ain't so :)

**Comment by jayunit100** [comment]
I think there was close to consensus that many parts of it may be headed to contrib/ but at the same time it's not going to be happening slowly since so much inertia there

**Comment by ixdy** [comment]
I'm going to close this in favor of the kubernetes/charts repo.
