### ISSUE TITLE
NO FailedPostStartHook Error Message After Upgrade to 1.7.8

### ISSUE THREAD

**Issue by lovejoy** [kubernetes/kubernetes#54671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
NO FailedPostStartHook Error Message After Upgrade to 1.7.8
When we use 1.6.3 , We can get message like   Error syncing pod, skipping: failed to "StartContainer" for "xxxx" with PostStart handler: command '/xxxxxx' exited with 1: Hook do errexit, this is stderr : "PostStart Hook Failed" From Event, But After Upgrade to 1.7.8 ,the FailedPostStartHook Event  always have no message 

**What you expected to happen**:
we need the message to find out the poststarthook failed reason

**How to reproduce it (as minimally and precisely as possible)**:
Use PostStartHook And Fail It

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/commit/a02f10fa3a956a2fc1fe0328f58b7b1cea548264
pkg/kubelet/kuberuntime/kuberuntime_container.go
line 123 ,dont delete it 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:54:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):4.13.7-1.el7.elrepo.x86_64
- Install tools:
- Others:

**Comment by lovejoy** [comment]
@derekwaynecarr

**Comment by xiangpengzhao** [comment]
I think this was fixed from 1.8.
see: https://github.com/kubernetes/kubernetes/commit/9fcc25d1ed4a45e4ea09a6f30250d00a047275f4

**Comment by lovejoy** [comment]
@xiangpengzhao  
the error message is in handlerErr ,so https://github.com/kubernetes/kubernetes/commit/9fcc25d1ed4a45e4ea09a6f30250d00a047275f4 didnot fix this

**Comment by OJezu** [comment]
I've just updated to kubernetes 1.8 and still no error message in `kubectl describe pod <pod>`

However, I've never seen it there, as I've been using k8s for a few days, some of which were spent on searching how to debug hooks...

Anyway client and server version:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Server is running as a part of minikube

**Comment by xiangpengzhao** [comment]
@lovejoy @OJezu thanks for pointing it out! I send PR #54739. PTAL.

**Comment by lovejoy** [comment]
@xiangpengzhao  We also require the error message included in the **Event**， could you add it？

**Comment by xiangpengzhao** [comment]
Seems like the `handlerErr` is already included in the `msg` according to `m.runner.Run` implementation.

`msg, handlerErr := m.runner.Run(kubeContainerID, pod, container, container.Lifecycle.PostStart)`

https://github.com/xiangpengzhao/kubernetes/blob/3dfaa086b39ac18ae44dfc1614350f7eb1565fa4/pkg/kubelet/kuberuntime/kuberuntime_container.go#L161

**Comment by lovejoy** [comment]
the **m.runner.Run** in **master** seems same as **release-1.7** ,And I found the **msg** is empty in **release-1.7**，so the **handlerErr** may not included in **msg**.

**Comment by xiangpengzhao** [comment]
ping @sjenning and @derekwaynecarr for confirmation. thanks!

**Comment by lovejoy** [comment]
JUST FOR SOMEBODY WHO CARE ABOUT THE PostStartHook Event Message 
"the msg is empty " have really already been fixed in https://github.com/kubernetes/kubernetes/pull/56959
It's in release 1.7.12 but it seems the release note didn't mention this
