### ISSUE TITLE
need deep copy fuzz test helper

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#54698]
Writing an API repo, you need to check that your deep copy methods work in isolation.  We should provide a test function in apimachinery for this purpose outside of conversions.

**Comment by sttts** [comment]
We provide `roundtrip.RoundTripSpecificKindWithoutProtobuf`, compare https://github.com/kubernetes/kubernetes/blob/ecc811d263894ae54bbe62a3b1ba14847a260e95/staging/src/k8s.io/apiextensions-apiserver/examples/client-go/apis/cr/v1/roundtrip_test.go#L54. This lets you test types without internal types and therefore without conversions.

**Comment by sttts** [comment]
@soltysh you did something with RoundTripSpecificKindWithoutProtobuf and deepcopy recently. Do you have a link?

**Comment by soltysh** [comment]
I'll try to put the PR together, it's been waiting on my todo list for too long now.
