### ISSUE TITLE
registries: remove intermediate `type Registry interface` between ScaleREST and storage

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#54693]
Example: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/apps/statefulset/registry.go#L32

These do essentially only type-casts, do not simplify the code otherwise.

**Comment by sttts** [comment]
Looks like it's intensively used to mock registries in tests.

**Comment by lavalamp** [comment]
cc @jpbetz @caesarxuchao
