### ISSUE TITLE
kube-dns not using upstreamNameservers

### ISSUE THREAD

**Issue by joeyea323** [kubernetes/kubernetes#54707]
/kind bug

**What happened**:
- ConfigMap for kube-dns created with 1 internal upstream name server
- kube-dns pods replaced and verified logs picked up config:
          I1027 16:08:54.444583       1 sync.go:177] Updated upstreamNameservers to [###.###.###.###]
- push DNS request to kube-dns service IP for internal domain and it doesn't resolve (seems like it is only using what is defined in /etc/resolv.conf)

**What you expected to happen**:
DNS resolution for all domains outside of cluster.local should be pushed to the upstream name server to include the internal domain.

**How to reproduce it (as minimally and precisely as possible)**:
dig @[service IP] [record in local domain]

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.7
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu Server 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0-97-generic
- Install tools: acs-engine
- Others:

**Comment by cmluciano** [comment]
cc @bowei

**Comment by feiskyer** [comment]
@joeyea323 Are you using Default dnsPolicy?  upstreamNameservers only works with ClusterFirst dnsPolicy.

**Comment by peterver** [comment]
Ubuntu runs dnsmasq internally as well, meaning that there are no upstream nameservers to inherit by kube-dns.

You can set some upstream nameservers in kube-dns by adding a configmap : 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["8.8.8.8", "8.8.4.4"]
```

**Comment by strtdusty** [comment]
@peterver  I think the OP is saying that he is creating a configmap and verified that kube-dns picks up the upstreamNameservers.  I am seeing the same issue and, for what it is worth, am also running in Azure.
