### ISSUE TITLE
Test client authentication in admission webhook

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#54709]
Currently the e2e test (https://github.com/kubernetes/kubernetes/pull/54165) uses one-way tls authentication. We need to add client authentication. It will include generating client cert/key and plumbing them through kubeconfig file.

**Comment by nikhita** [comment]
looks like this is still relevant

/remove-lifecycle rotten

**Comment by liggitt** [comment]
For e2e, this would also require starting the cluster being tested with a webhook config file, which is difficult to ensure.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/82252 adds testing in integration, which is more reasonable since we control the server invocation
