### ISSUE TITLE
Apiserver times out PUTs to /api/batch/v1 endpoints after etcd leader election

### ISSUE THREAD

**Issue by julia-stripe** [kubernetes/kubernetes#54716]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

1. We had an etcd leader election because the etcd leader was killed
2. PUT requests to the apiserver's `"/apis/batch/v1/namespaces/<namespace>/jobs/<jobname>/status"` endpoints started timing out (http response code: 504). Requests to all other endpoints succeeded. 
  * Specifically: PUTs for job status and cronjob status failed (504), but PUTs for pod status succeeded. 
  * GETs of batch endpoints also succeeded
3. We restarted the apiserver and that fixed the problem

**What you expected to happen**:

I'd expect either all PUTs to fail or all PUTs to succeed (inside the same apiserver instance at the same time). I'm confused about how some resource PUTs would succeed but other resource PUTs would time out.

**How to reproduce it (as minimally and precisely as possible)**:

I realize this issue is probably hard to reproduce but would love any thoughts about how this could even be possible. My previous understanding of Kubernetes was that the apiserver connects to etcd, and the connection to etcd is either "working" or "not working" -- it doesn't depend on what kind of resource you're using.

I do not have steps to reproduce this -- I tried killing the etcd leader again and this time it went smoothly. So it seems that the issue doesn't always happen.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration: AWS
- OS: Ubuntu 16.04
- Kernel: 4.4
- Install tools: custom

**Comment by lavalamp** [comment]
My guess is that something went wrong with the caching layer. I take it those repro steps are a guess? I would guess that this bug would make random things stop working, not those specific endpoints.

@wojtek-t do you have any ideas?

**Comment by lavalamp** [comment]
cc @jpbetz

**Comment by julia-stripe** [comment]
Updated the issue description to say that I can't reliably reproduce this issue. It seems plausible that this bug is just making random things stop working.

**Comment by wojtek-t** [comment]
Hmm - I vaguely remember something similar.
@liggitt do you remember what exactly that was and in what version it was fixed?

**Comment by liggitt** [comment]
I've never seen a timeout... I've seen persistent `409 Conflict` errors returned when the watch cache was persistently stale[1] (fixed in 1.6.11, 1.7.7, 1.8.0) because etcd missed delivering watch events after a member rejoined[2] (fixed in etcd 3.2.6+[3])


[1] https://github.com/kubernetes/kubernetes/pull/43152#issuecomment-329583303
[2] https://github.com/kubernetes/kubernetes/pull/43152#issuecomment-329835310
[3] https://github.com/coreos/etcd/pull/8427

**Comment by liggitt** [comment]
xref #59074

this is likely resolved by https://github.com/kubernetes/kubernetes/pull/58008 in 1.10

1. etcd clients are constructed per resource
2. without the referenced PR, an established TCP connection to an etcd member can hang
