### ISSUE TITLE
[job failure] ci-kubernetes-verify-master

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#54711]
/priority critical-urgent
/priority failing-test

/sig release
/sig testing
because I'm taking a guess at who owns this job, [it doesn't have an owner right now](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L8915)

This job is on the release-master-blocking dashboard, and prevents us from cutting 1.9.0-alpha.2 (kubernetes/sig-release#22). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify

Last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/15486
First bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/15487
Suspect commit range: https://github.com/kubernetes/kubernetes/compare/7914aed80...aabfc5555

```
I1027 01:25:33.138] Godeps Verify failed.
I1027 01:25:33.138] If you're seeing this locally, run the below command to fix your directories:
I1027 01:25:33.138] patch -p0 < vendordiff.patch
I1027 01:25:33.139] (The above output can be saved as godepdiff.patch if you're not running this locally)
I1027 01:25:33.139] (The patch file should also be exported as a build artifact if run through CI)
I1027 01:25:33.139] Copying patch to artifacts..
I1027 01:25:33.139] Leaving /tmp/gopath.zr6T52 for you to examine or copy. Please delete it manually when finished. (rm -rf /tmp/gopath.zr6T52)
I1027 01:25:33.139] FAILED   hack/make-rules/../../hack/verify-godeps.sh	677s
```

**Comment by BenTheElder** [comment]
unit and verify CI/PR jobs could use an appropriate owner and have been quite flaky (we have a few *very* flaky unit tests) 😕

**Comment by cblecker** [comment]
/assign
Let me take a look

**Comment by BenTheElder** [comment]
At a glance this looks the same as the "first bad" but on PR verify
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/53561/pull-kubernetes-verify/58634/

**Comment by cblecker** [comment]
I think it's https://github.com/kubernetes/kubernetes/pull/53816.. a bunch of federation code was removed, that I think removed the need for deps, but the verify job didn't run as it only runs when deps are actually changed.

I'm verifying locally, but if this is the case, I can crank out a PR pretty quick to fix up.

**Comment by cblecker** [comment]
Fix is in https://github.com/kubernetes/kubernetes/pull/54714

**Comment by BenTheElder** [comment]
Thanks for tackling this @cblecker!
