### ISSUE TITLE
Race condition updating events for compression

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#5471]
There is a race condition in event compression logic in `pkg/client/record/event.go`. If the same event is created in rapid succession it is possible that ResourceVersion used to update one of the events becomes out-of-date and the update fails due to `Conflict`.

The fix for the race condition can not be implemented on the client side, because it requires doing an atomic increment operation: no client can control/guarantee the behavior of any other client and thus no client can implement an atomic increment operation using separate read/write REST calls.

The correct fix for this is to expose a new REST call on the API Server that can take an event key and `LastSeen` timestamp, and do the following operations atomically:
  1) Read the event object for the given event key
  2) Write the event object back with an incremented count and new `LastSeen` timestamp (timestamp should only be updated if it is more recent then the existing timestamp).

While this race condition exists in theory,  in practice it is unlikely to be triggered by our code because it requires either another client to do an update on an existing event object that it did not create or multiple threads on the same client doing the exact same operation on the exact same object in rapid succession and create an event for it--our code is mostly synchronous and does no identical event generating operations in parallel.

I am marking this bug as P2 because of the unlikely nature of it occurring in normal operation and the work required to implement the correct solution.

Branched from #5327 (even though this doesn't cause that issue, it needs to be tracked).

**Comment by liggitt** [comment]
events are intended for best effort advisory information. they already depend on well-behaved clients, and there is already existing client-side compression that can drop events in high volume scenarios.

getting a slightly different count or lastseen in the case where an identical event is being created rapidly is not concerning.
