### ISSUE TITLE
Pod in graceful termination should not be on the ready address list of related Endpoints objects

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#54723]
**What happened**:
Pod in graceful termination (Readiness: True, Status: Terminating) still shows up in the ready addresses section of related Endpoints objects. 

**What you expected to happen**:
Pod in graceful termination should show up in the unready addresses section of related Endpoints objects.

**How to reproduce it (as minimally and precisely as possible)**:
Set up service and point to pods that can handle graceful termination. Watch related Endpoints object while deleting a backend pod. 

**Anything else we need to know?**:
- The code to determine whether a pod should be in endpoints object is as follows:
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L563
- I am not sure whether users are relying on this broken behavior.

**Environment**:
kubernetes HEAD

**Comment by freehan** [comment]
Any objections?

cc @thockin @bowei @dchen1107 @yujuhong

**Comment by freehan** [comment]
I am not sure if users are relying on this broken behavior.

**Comment by bowei** [comment]
I thought there was another issue about this, not sure if it will be possible to dig it up...

**Comment by hzxuzhonghu** [comment]
This case DeletionTimestamp should be set,  so this pod should be not in endpoint subset.
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L438

**Comment by JoschaP** [comment]
+1

**Comment by yujuhong** [comment]
> This case DeletionTimestamp should be set, so this pod should be not in endpoint subset.
> https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L438

Agreed. Shouldn't this filter out terminating pods already? @freehan

**Comment by freehan** [comment]
I can reproduce this consistently on my cluster(build from HEAD). I will debug further and come back.

But everyone agrees on the expected behavior, right?

**Comment by freehan** [comment]
I figured out what is going on:

0. Set up a deployment with 3 replicas and service pointing to them. 
1. Scale down deployment by 1. One backend pod got deleted. 
2. Pod informer is going to inform endpoint controller of a pod update event. The event handler is here: https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L99
3. The handler checks if the pod is changed: https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L266
4. Since only DeletionTimestamp is set on the pod, hence the function thinks there is no change and return false.
5. Then event handler just skips refreshing the endpoints object here: https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/endpoint/endpoints_controller.go#L278


This bug only triggers when service backend pod got deleted. But if there is a new backend pod around the same time, it will reconcile. So rolling update will not trigger this. Only scale down will cause this problem.

**Comment by freehan** [comment]
This bug is introduced by #50934
