### ISSUE TITLE
Need to be able to control which nodes are added to a cloud load balancer.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#54743]
For various reasons (network topology, heterogenous nodes, etc) a user may want to control the addition of a node to a cloud load balancer.

A specific issue with the Azure Container Instances connector which introduces a _virtual_ node can be found here:

https://github.com/Azure/aci-connector-k8s/issues/51

The right way to do this is via a node annotation, e.g.

`alpha.service-controller.kubernetes.io/exclude-balancer`

**Comment by andrewsykim** [comment]
Setup the enhancement tracking issue for this https://github.com/kubernetes/enhancements/issues/724. Still discussing with sig-network on how we want to move forward with this.
