### ISSUE TITLE
Do we have any parameter to stop showing the mirror pod?

### ISSUE THREAD

**Issue by zhangmingld** [kubernetes/kubernetes#54747]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
We use static pod as our lb in the HA,and the node \master are on the same machine,so we can see mirror pod with "kubectl get pod --all-namespace",but k8s collect the performance data of these mirror pods，we dont need this。So，do we have any parameter to stop showing the mirror pod? 

**What you expected to happen**:
we have some parameter to stop showing the mirror pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lavalamp** [comment]
You can add labels and use a label selector to exclude pods with those labels?

The list of fields which are selectable is tightly controlled (due to performance/complexity considerations) and it's unlikely we'll be adding this to that list, sorry.
