### ISSUE TITLE
Feature request: ZFS utils in Hyperkube base image.

### ISSUE THREAD

**Issue by AaronFriel** [kubernetes/kubernetes#54765]
/kind feature

**What happened**:

Ran Hyperkube using ZFS backed storage. Lots of warnings in logs due to missing zfs utils. See #54754.

**What you expected to happen**:

No errors in the logs.

**How to reproduce it (as minimally and precisely as possible)**:

Install Docker CE, run Hyperkube with all Kubernetes directories on ZFS mounts.

**Anything else we need to know?**:

ZFS utils are absent from Hyperkube images. Need to add Jessie-Backports or move base image to Stretch and install `zfsutils-linux`.

**Comment by cblecker** [comment]
cc: @kubernetes/sig-storage-feature-requests @tallclair @ixdy

**Comment by AaronFriel** [comment]
This might not be a good idea. Not having the ZFS utilities in my image didn't prevent Kubernetes from working, it merely produced a large number of warnings from failures to query the zfs volumes.

But the result is now I see the docker container repeatedly query for all volumes using this command:

```
zfs get -t all -Hp all -r main/docker
```

This however is slow. It's very slow:

```
$ sudo time sh -c "zfs get -t all -Hp all -r main/docker > /dev/null"
0.71user 16.83system 0:19.70elapsed 89%CPU
```

It runs this every thirty seconds, I think. On a dual core virtual machine, this resulted in total CPU usage to go from 10% to 33%:

![image](https://user-images.githubusercontent.com/788800/32175268-6fa06ef6-bd52-11e7-88b2-57b272bfb1ce.png)

Not good.

**Comment by AaronFriel** [comment]
```
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957193    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/docker/dd355201c78bf95dfb248d57efcaa0bac632bf37f8e1e1d1d1906f4d64a0715f" =>
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957250    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/docker/abac4f99f90a969a655b060c8c5e787207ffa0d93de611dfb0dd408bc23ec63f" =>
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957440    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/docker" =>
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957479    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/volumes/kube" =>
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957503    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/docker/b40fbe63fdc7e4b01d81cc7e5dd8d640138304527159fc324031cb03f402a6ce" =>
Oct 30 09:24:36 unifi-host-170731 docker[5072]: E1030 14:24:36.957541    5267 fs.go:418] Stat fs failed. Error: exec: "zfs": executable file not found in $PATH: "zfs zfs get -Hp all main/docker/72aa2f9a89c03f769bde23daf8be82f2d48a9b14d2cd554ae4ebbd6500d74140" =>
```

Stat errors are vastly preferable to high CPU usage.

**Comment by AaronFriel** [comment]
Reverting my own change to hyperkube reduced CPU usage significantly: 
![image](https://user-images.githubusercontent.com/788800/32195242-c288f556-bd8a-11e7-9328-0c91c072d565.png)

**Comment by ixdy** [comment]
The hyperkube base image is now based on debian:stretch. If zfs-utils are still desired, it would be easy to add them.

**Comment by AaronFriel** [comment]
The performance cost of `zfs get all` seems to have gone back down to near zero on my system, and to be honest, I'm not sure why. I did do a storage migration to a new disk, it likely fixed some latent issue.

Is there a reason hyperkube is doing these stat operations with zfs? What is the downside of allowing these operations to fail as they do now?

**Comment by superseb** [comment]
/reopen

@AaronFriel Did you run into any issues running on ZFS without the utils or did you build your own image still?

@ixdy Is this something that would still be accepted? Adding contrib repo and installing zfsutils-linux in the image?

Seems that it queries imagefs and without the tools, it won't succeed on ZFS based imagefs and therefor not evict when thresholds are met.
