### ISSUE TITLE
Reduce cpumanager default logging verbosity

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#54804]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

On 1.8+ kubelet with --cpu-manager-policy=static, there is a constant stream of logging every 10 seconds or so in the following formats:

`kubelet: I1030 14:13:15.116477   23623 cpu_manager.go:239] [cpumanager] reconcileState: updating container (pod: kube-proxy-47dt8, container: kube-proxy, container id: f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986, cpuset: "0-31")`

for every pod, and

`kubelet: E1030 14:13:05.012702   23623 remote_runtime.go:302] UpdateContainerResources "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986" from runtime service failed: rpc error: code = Unknown desc = failed to update container "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986": Error response from daemon: Cannot update container f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986: rpc error: code = Unknown desc = failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod74095402-a88b-11e7-9aea-90b11c4094cf/f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986/devices.allow: invalid argument`

`kubelet: E1030 14:13:05.012729   23623 cpu_manager.go:242] [cpumanager] reconcileState: failed to update container (pod: kube-proxy-47dt8, container: kube-proxy, container id: f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986, cpuset: "0-31", error: rpc error: code = Unknown desc = failed to update container "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986": Error response from daemon: Cannot update container f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986: rpc error: code = Unknown desc = failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod74095402-a88b-11e7-9aea-90b11c4094cf/f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986/devices.allow: invalid argument)`

for every privileged pod where update would fail but looks expected.

**What you expected to happen**:

First set of logs should probably be suppressed or to the debug level.

Second set of logs should probably be better at distinguish expected case vs. unexpected case before logging that as errors.

**How to reproduce it (as minimally and precisely as possible)**:

Run kubelet with `--cpu-manager-policy=static --feature-gates=CPUManager=true`, and watch /var/log/messages or similar.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: baremetal/onprem
- OS (e.g. from /etc/os-release): CentOS 7.4.1708
- Kernel (e.g. `uname -a`): 4.13.8-1.el7.elrepo.x86_64
- Install tools: custom
- Others:

**Comment by ConnorDoyle** [comment]
Thanks for filing this bug. Do you plan to work on fixing it too, or should we find someone to pick it up?

**Comment by phsiao** [comment]
@ConnorDoyle I can take a look and see what I can or cannot do with this.

**Comment by phsiao** [comment]
"updating container" log line should be easy to deal with, it is doing a logging without setting a level, and if there is a convention on what should be the level of this type of logging (and similar in this file), I can submit a PR to add .V(x). support for it.  Any preference on how the logging level should be handled?

**Comment by ConnorDoyle** [comment]
I can help review #54865.

For the second part, it might be related to [this TODO](https://github.com/kubernetes/kubernetes/blob/c2a18cca6b79d4f3764d50f2c418b965e32864a2/pkg/kubelet/cm/cpumanager/cpu_manager.go#L272) we left for ourselves in the CPU manager code. We should fetch the current resource config and only update the `CpusetCpus` field.

**Comment by ConnorDoyle** [comment]
@nqn volunteered to look into the second half of this.

**Comment by phsiao** [comment]
Great.

Regarding the second half, the best I can find so far indicates that the error is the result of attempting to modifying devices.allow when the cgroup already has children.  I will dig more also just to confirm.

`rpc error: code = Unknown desc = failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod74095402-a88b-11e7-9aea-90b11c4094cf/f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986/devices.allow: invalid argument`

**Comment by phsiao** [comment]
Here is what I found:

```
Allowing or denying all by writing 'a' to devices.allow or devices.deny will
not be possible once the device cgroups has children.
```

https://www.kernel.org/doc/Documentation/cgroup-v1/devices.txt

**Comment by vishal-yadav** [comment]
Any update on the second part? Is it also fixed? Thanks.

**Comment by fieryvova** [comment]
This hasn't been fixed AFAIK. This error is only related to kube-proxy containers.

**Comment by Davidrjx** [comment]
@phsiao has there this issue related with kube-proxy been a solution, or it been ignorable?
