### ISSUE TITLE
Kubernetes 1.8 OpenApi Spec is invalid

### ISSUE THREAD

**Issue by ceridwen** [kubernetes/kubernetes#54815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I pass the 1.8 OpenAPI spec to Swagger's validator, I get an error that looks like:

```
# swagger-codegen validate -i openapi_kubernetes_1.8.json
attribute definitions.io.k8s.kubernetes.pkg.api.v1.PersistentVolume.description is unexpected
...
Exception in thread "main" io.swagger.codegen.cmd.ValidateException
	at io.swagger.codegen.cmd.Validate.run(Validate.java:34)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

The full output is at https://gist.github.com/ceridwen/a0007517d5410bdca0ae1653f136646f.

**What you expected to happen**:

I expected validation to pass.  Validation on the 1.6 and 1.7 specs passes.

**How to reproduce it (as minimally and precisely as possible)**:

Download https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.8/api/openapi-spec/swagger.json and run swagger-codegen version 2.2.3  on it.

**Environment**:
- Kubernetes version (use `kubectl version`): I noticed this issue on minikube v0.23.
- OS (e.g. from /etc/os-release): Mac OS X 10.12.6
- Kernel (e.g. `uname -a`): Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
- Others: swagger-codegen 2.2.3.

**Comment by mbohlool** [comment]
I am aware of this. As far as I remember, swagger-codegen still uses these description fields and we found it useful to include them. I just remember these were warnings at the time not errors. I maybe wrong, but I would say this works as expected unless you have a reason to see this a problem for any tool consuming OpenAPI spec.

**Comment by ceridwen** [comment]
I believe that swagger-codegen is more liberal with what it will generate code from than from what it considers to be valid OpenAPI.   The problem with this is that other tools are stricter about their interpretations.  I'm using a Python library that only operates on valid OpenAPI JSON to look at the spec, and like swagger-codegen in validate mode, it will throw an unhandled exception when I run it on the 1.8 spec.  I don't know enough about how swagger-codegen is using those description fields to understand the purpose they serve, but from my outsider's perspective, this means I can't use tools that are written based on what the spec says rather than on what swagger-codegen will accept.

**Comment by ceridwen** [comment]
I haven't had time to update the pull requests to modify the original files.  I can make new ones at that point.  However, I need to reply to @mbohlool's comment:

> Also as far as I can tell, #54815 is about extra description fields that are considered invalid in some OpenAPI validators but swagger-codegen is OK with it. 

`swagger-codegen generate` will generate code from this invalid spec, but `swagger-codegen validate` will crash with a stack trace.  This is not a valid spec.

**Comment by mbohlool** [comment]
The extra description is useful in swagger-codegen generated clients. It is in a gray area on validation when swagger-codegen actually using it. I suggest to process the spec after download and remove the description if the tool you are using complain about them.

**Comment by mbohlool** [comment]
Also I've tried [swagger-cli](https://www.npmjs.com/package/swagger-cli) validator on 1.8 spec and it said it is valid.

**Comment by ceridwen** [comment]
swagger-codegen validate outputs this gist: https://gist.github.com/ceridwen/959e120514e8e07d2a84de67b8f7437b  If swagger-cli is correct and the spec is valid, that means there are bugs in swagger-codegen and potentially other libraries.  Is this something I should take to them?

**Comment by mbohlool** [comment]
I think this is a grey area in the spec. Having an extra description field is not valid per say (have not mentioned in the spec) but it is not invalid too (as some tools like swagger-codgen generator part is using it). I would say the best course of action is to post process the spec and remove them for the tools that complain about it.
