### ISSUE TITLE
When running e2e tests, maybe call the "client" version the "e2e test" version?

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#54821]
This is to avoid some confusion that has come up when people are reading the instructions.  See also https://github.com/cncf/k8s-conformance/pull/33/files.

@WilliamDenniss 

/area conformance
/sig api-machinery
/kind feature
/assign

**Comment by mml** [comment]
These were just added in #53551

**Comment by WilliamDenniss** [comment]
+1 for "e2e test" version. A lot of people think `kubectl` when they hear "client".
