### ISSUE TITLE
can not get pod image name by jsonpath when use label selector

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#54851]
I tried to use label selector to get container image name, but it can not show the image name when lables selector provided.

```
hchenxa@hchen-mac:~/Documents/hchenxa/src/ICp/automation_test$ kubectl  get pods -n ivt --show-labels
NAME                          READY     STATUS    RESTARTS   AGE       LABELS
nginx-roll-3431990605-9p6bm   1/1       Running   0          11m       pod-template-hash=3431990605,run=nginx-roll
hchenxa@hchen-mac:~/Documents/hchenxa/src/ICp/automation_test$ kubectl get pods nginx-roll-3431990605-9p6bm --namespace=ivt -o jsonpath='{.spec.containers[*].image}'
nginx:1.13.3-alpine
hchenxa@hchen-mac:~/Documents/hchenxa/src/ICp/automation_test$ kubectl get pods -l run=nginx-roll --namespace=ivt -o jsonpath='{.spec.containers[*].image}'
hchenxa@hchen-mac:~/Documents/hchenxa/src/ICp/automation_test$
```

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`hchenxa@hchen-mac:~/Documents/hchenxa/src/ICp/automation_test$ kubectl  version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zjj2wry** [comment]
@hchenxa when use `label selector`, will return `KIND:List` Object. so cause you can not get pod image. 

you can use` kubectl get pods -l run=nginx-roll --namespace=ivt -o yaml`, then rewirite your `jsonpath` template.

**Comment by hchenxa** [comment]
Thanks @zjj2wry , now worked with `kubectl get pods -n ivt -lrun=nginx -o jsonpath='{.items[0].spec.containers[0].image}'`
