### ISSUE TITLE
use kubenetes to pull image pull from private registry is broken

### ISSUE THREAD

**Issue by samlyhuang** [kubernetes/kubernetes#54850]
docker version:17.09.0
system version: CentOS Linux release 7.2.1511 (Core) 
kubernetes version : 1.6.2

when i use kubectl to create a  deployment,find this issue :
Error syncing pod, skipping: failed to "StartContainer" for "rolling-update-test" with ErrImagePull: "rpc error: code = 2 desc = Error response _from_ daemon: {\"message\":\"Get http://192.168.31.150:5000/v2/nginx-web/manifests/v3: no basic auth credentials\"}"
Back-off pulling image "192.168.31.150:5000/nginx-web:v3"

but i find a file in path /root/.docker/config.json, the content of file is that :
{
        "auths": {
                "192.168.31.150:5000": {
                        "auth": "aGx5OkhMWWhseTEyM0A="
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/17.09.0-ce (linux)"
        }
}

what is my problem?

**Comment by samlyhuang** [comment]
sorry, I am new in kubernetes. Can you give an example ?
Thank you very mach

**Comment by huzhengchuan** [comment]
https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry 
I think this can help you!

**Comment by samlyhuang** [comment]
Thank you everyone,I have solved this problem. I use kubectl to create myregistrykey ,then pull images is successful.

**Comment by feiskyer** [comment]
cool. Closing the issue since it's been resolved. 

@samlyhuang feel free to reopen it if you still have problems.

**Comment by samlyhuang** [comment]
ok
