### ISSUE TITLE
Deprecated usage message is not getting printed 

### ISSUE THREAD

**Issue by yuexiao-wang** [kubernetes/kubernetes#54855]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Deprecated usage message is not getting printed , such as --container-port in kubectl export, --interactive in kubectl log,  --experimental-use-openapi-print-columns in kubectl get.

Because cobra is used in kubectl, the issue is imported by cobra.
https://github.com/spf13/cobra/issues/463
https://github.com/spf13/cobra/pull/466

Should we update cobra in vendor?

$ kubectl expose --help
Expose a resource as a new Kubernetes service. 
...
Options:
      ...
      --container-port='': Synonym for --target-port

$ kubectl log --help
...
Options:
     ...
      --interactive=false: If true, prompt the user for input when required.

**What you expected to happen**:
$ kubectl expose --help
Expose a resource as a new Kubernetes service. 
...
Options:
      ...
      --container-port='':  --container-port will be removed in the future, please use --target-port instead

$ kubectl log --help
...
Options:
     ...
      --interactive=false: This flag is no longer respected and there is no replacement.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuexiao-wang** [comment]
@kubernetes/sig-cli-bugs

**Comment by dixudx** [comment]
@yuexiao-wang Thanks for this issue.

PR #53631 has already included above bug-fixes, as well as enforcing required flags.
