### ISSUE TITLE
Inconsistent watch behavior with resourceVersion specified

### ISSUE THREAD

**Issue by yianL** [kubernetes/kubernetes#54878]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm working on a tool that reports deployment statuses to an external source, which utilizes the deployment watch api. However, I've seen some unexpected behavior with the watch api, and I couldn't find proper documentation for it:

- Scenario I: when you start a watch call with a resourceVersion that is too old, you will get a `410 Gone` error.
- Scenario II: when you start a watch call with a valid resourceVersion, you will get a stream of events that have newer resourceVersions replayed to you.
- Scenario III: when you start a watch call with no resourceVersion (null or empty string), you get a stream of only deployment `ADDED` events, and no other events such as `MODIFIED`, `DELETED` or `ERROR` events are replayed.

**What you expected to happen**:

The behavior in Scenario III is inconsistent with the documentation (https://kubernetes.io/docs/api-reference/v1.8/#watch-list-31), where it says resourceVersion will default to the beginning of history if not specified. I would expect if I don't provide a resourceVersion with the watch call, it will replay all the events Kubernetes have since the beginning of event history, not just `ADDED` events.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a deployment in an empty namespace, and log the resourceVersion at time of creation.
2. Start a watch call on deployments in the namespace with the resourceVersion, and see the history of events replayed one `ADDED`, and most likely a couple of `MODIFIED` events
3. Start a watch call on deployment in the namespace with no resourceVersion, and see only one `ADDED` event.

**Anything else we need to know?**:

Also, [Events in Stackdriver](https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/) mentioned the retention policy of one hour, but the watch api seems to be able to replay events from longer in the past. I wonder if there is a configuration or more documents around event retention policy?

**Environment**:
- Kubernetes version (use `kubectl version`): `{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: `minikube version: v0.22.3`
- OS (e.g. from /etc/os-release): `Buildroot 2017.02`
- Kernel (e.g. `uname -a`): `Darwin Kernel Version 16.7.0`o
- Install tools:
- Others:

**Comment by lavalamp** [comment]
The documentation is wrong / incomprehensible.

**Comment by yianL** [comment]
Hi @lavalamp , thanks for picking up the ticket. If the docs are wrong, can you briefly explain how it's supposed to work?

Another related question: is the event retention policy configurable in kubernetes?

**Comment by liggitt** [comment]
When resource version is unspecified, you get an ADDED event for every object in existence at the point in the when the watch is started, and all subsequent ADDED/MODIFIED/DELETED events for changes from that point.

**Comment by yianL** [comment]
Thanks for the clarification!
