### ISSUE TITLE
Service Nodeport and Healthcheck Nodeport Collision

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#54885]
I came across a cluster where it has 2 services with port collision. 

One service looks like this:
```
type: LoadBalancer
externalTrafficPolicy: Local
healthCheckNodePort: ${Collided Port}
```

The other looks like:
```
...
  annotation: cloud.google.com/load-balancer-type=Internal
Spec: 
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports
  - nodeport: ${Collided Port}
    ....
```

I checked the logic that allocates nodeport and healthcheck nodeport. They went thru the same node port allocator. Port allocation mainly happens in `initNodePorts`, `updateNodePorts` and `allocateHealthCheckNodePort`. The file in question is https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/registry/core/service/rest.go

**Comment by freehan** [comment]
cc @kubernetes/sig-network-bugs

**Comment by xiangpengzhao** [comment]
@freehan I'm not clear on your context. Which case were you facing?
- config and create the two services as you mentioned manifests, then get errors due to the collided ports?
- create the two services without specifying the two ports, then get the services and find they have collided ports?

Also, what is the expected behavior you were thinking of?
-

**Comment by freehan** [comment]
@xiangpengzhao When I checked the cluster, there were 2 services with colliding ports. I am not sure what brought the cluster into this state.

**Comment by xiangpengzhao** [comment]
It's strange... I will try to dig into it later.

**Comment by xiangpengzhao** [comment]
Seems like there is a race condition. PR #54999 sent. PTAL.

**Comment by freehan** [comment]
I first thought there was a race condition too. But I checked the API log. The operation on the 2 services are quite separated. Then I am not sure.

**Comment by xiangpengzhao** [comment]
Oh... So strange. I will take another look at the code to try to find some clues.
Btw, does the lock added to #54999 make any sense? It doesn't fix this issue though.

**Comment by nicksardo** [comment]
Found the issue. It's due to the nodeport repair controller ignoring the healthCheckNodePort.

**Comment by nicksardo** [comment]
Will send a PR and cherrypicks.
