### ISSUE TITLE
Azure: clusters with many services run out of NSG rules

### ISSUE THREAD

**Issue by itowlson** [kubernetes/kubernetes#54899]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**: When I expose a service of type LoadBalancer, the Azure cloud provider creates an inbound security rule in the network security group (NSG) associated with the subnet.  However, an Azure NSG has a limit of 200 inbound security rules.  A large cluster that exposes many services can exhaust this limit.

**What you expected to happen**: I should be able to expose over 200 services from a cluster.  (We should pin down what is an acceptable limit, because Azure will never allow us create an unlimited number of NSG rules.)

**How to reproduce it (as minimally and precisely as possible)**: Create a cluster and expose 500 services from it.

/sig azure

**Comment by feiskyer** [comment]
@itowlson Seems the NSG quota could only be increased by creating [request support](https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request) at azure portal. Is there any way to automate this via API?

**Comment by khenidak** [comment]
@feiskyer no, only support request.

**Comment by itowlson** [comment]
The proposed fix is:

- Provide a 'shared NSG rule'
- Introduce an annotation whereby the user can ask for the service to be exposed via the shared rule instead of a dedicated rule
- If a service has this annotation, add its public IP to the shared rule's destinations instead of creating a dedicated rule

This would allow up to 2000 destination IPs.  We need to work out what the scope of sharing is e.g. source address ranges, source address ranges + port, etc.

**Comment by jdumars** [comment]
Does this still need to be an open issue @itowlson ?

**Comment by khenidak** [comment]
No let us close. This was fixed in https://github.com/kubernetes/kubernetes/pull/55752
