### ISSUE TITLE
kubectl explain: Ignore trailing period

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#54891]
As a frequent user of `kubectl explain` I propose we ignore the trailing period (`.`) character in the argument passed to this command:

* As long as argument is non-empty when trailing period is removed, I think it's safe
* You use `kubectl explain` by keep adding fields (e.g. `service`, then `service.spec`,  then `service.spec.ports` ...) so it's very easy to forget a trailing `.` at the end.
* When a user leaves the `.` at the end, kubectl gives a super weird cryptic error (see below)

```sh
$ kubectl explain  ingress.spec.rules.http.paths.
error: field "" does not exist
```

I believe ignoring the trailing period(s) will be more forgiving and increase user success with `kubectl explain`. 
@jbeda might have something to add.

/kind bug
/sig cli

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/kubernetes/pull/54938.

**Comment by ahmetb** [comment]
> field "ingress.spec.rules.http.paths." doesn't exist

still does not help much. :) It would be good if it said `field "paths." does not exist` because then I can clearly see there's a trailing period in quotes, which is causing the problem.

**Comment by spzala** [comment]
@ahmetb :) agree! I have created a new PR and if you think it looks good, I will add some test. And I have no idea why I couldn't remove thumps down above in your comment :( ..didn't want to add it in first place but I guess too fast of click, sorry :(. Thanks! 
```
# cluster/kubectl.sh explain svc.status.xyz
error: field "xyz" does not exist
# cluster/kubectl.sh explain svc.status.xyz.
error: field "xyz." does not exist
```
@nikhita hi, I have a created a new PR with a different solution approach and possibly what we want as you could see above discussion. I have added you as a co-author to equally share the credit for PR :-) Hope that sounds good. Thanks!

**Comment by nikhita** [comment]
> I have added you as a co-author to equally share the credit for PR

That wasn't necessary but appreciated. :)

> It would be good if it said field `paths.` does not exist because then I can clearly see there's a trailing period in quotes, which is causing the problem.

Seems like the middle ground and best solution here since:

1. The user could have probably missed adding a field after the trailing period.
2. Clearly shows what's wrong.

But this clearly needs a discussion. IMO, in the end, whatever is easiest to the user should be done. :)

**Comment by spzala** [comment]
:) you sure deserve to be a co-author for that PR @nikhita
