### ISSUE TITLE
[e2e flake] [sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#54904]
/priority failing-test
/priority important-soon
/sig apps
/kind flake
@kubernetes/sig-apps-test-failures 

I remember mentioning this test case during the last sig-testing update at our community meeting, and see it's still [the top flake for a number of PR jobs](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1).  It also flakes across many of our postsubmit jobs: [triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=%5C%5Bsig-apps%5C%5D%20Job%20should%20run%20a%20job%20to%20completion%20when%20tasks%20sometimes%20fail%20and%20are%20not%20locally%20restarted)

[triage cluster 63a36434077ff31ae29e](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig-apps%5C%5D%20Job%20should%20run%20a%20job%20to%20completion%20when%20tasks%20sometimes%20fail%20and%20are%20not%20locally%20restarted#63a36434077ff31ae29e)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/job.go:87
Expected error:
    <*errors.errorString | 0xc420254ac0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/job.go:86
```

refs: 
- https://github.com/kubernetes/kubernetes/issues/35507
- https://github.com/kubernetes/kubernetes/pull/53380

**Comment by foxish** [comment]
It looks to me like the queue's exponential backoff is causing this failure. The quick fix may be just reducing the number of expected completions to 3 from 4.
However, from looking at the controller enqueue mechanism, it seems while we increase the backoff time every time there are additional failures, we don't reset that number when there are successful completions.
I can make an argument that we should be doing the latter as well. 

WDYT @kargakis @janetkuo?

**Comment by foxish** [comment]
I mean in specific - with parallelism=N, if there are N-1 successes and 1 failure, we'd still start increasing the backoff time. That seems odd to me.

**Comment by kargakis** [comment]
cc @soltysh

**Comment by spiffxp** [comment]
/kind bug

I'm leaving it to @kubernetes/sig-apps-bugs to decide whether to /status accept-for-milestone

**Comment by soltysh** [comment]
@foxish you're right the backoff should restart, my goal with this so it works similarly to how the backoff works in kubelet, with failed pods. I'll try to find some time next week and get it fixed properly.

/assign soltysh

**Comment by dims** [comment]
@soltysh @kubernetes/sig-apps-bugs Is this still on for 1.9?  Is there a PR already? (if not, Can we move it out to 1.10?)

**Comment by kow3ns** [comment]
I'd like to get this in for 1.9 as it causes a significant number of test flakes.

**Comment by soltysh** [comment]
@foxish I've finally spend some time today looking into it, the backoff limit is properly reseted to 0 (see #56702, where I've added a test). There's one gotcha, though. If a controller notices both failure and success at the same time, it won't clear the retires, the question is should it?

**Comment by foxish** [comment]
Hmm, that's a hard one - can we make that decision based on the actual numbers of those successes and failures? I imagine if we see 1 failure and 10 successes, the decision we want to take is different from when we see the inverse. @kow3ns for his thoughts.

**Comment by foxish** [comment]
I suggest we reduce the expected completions to 3 for this test. It would prevent us timing out. We can have the discussion of whether this is the right behavior in https://github.com/kubernetes/kubernetes/pull/56702. @soltysh

**Comment by soltysh** [comment]
> I suggest we reduce the expected completions to 3 for this test. It would prevent us timing out. We can have the discussion of whether this is the right behavior in #56702. @soltysh

Done in #56702, along with the unittest that I wrote for resetting the backoff limit.
