### ISSUE TITLE
gce-ipvs CI job failures

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#54916]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
 
There are some failures in ubuntu-gce-ipvs CI job. See, http://k8s-testgrid.appspot.com/google-gce#ubuntu-gce-ipvs

**What you expected to happen**:

We want to see CI job green!!

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

@Lion-Wei @stewart-yu in my team will together take care of gci-gce-ipvs CI job.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

**Comment by m1093782566** [comment]
cc @cmluciano

**Comment by cmluciano** [comment]
/assign 

adding myself for tracking purposes

**Comment by MrHohn** [comment]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/
Seems like tests are passing after https://github.com/kubernetes/kubernetes/pull/55004 went in.

**Comment by m1093782566** [comment]
@MrHohn Thanks for your information.

However, the current mode is userspace, instead of ipvs. I think we should push forward the pending PRs forward - #54120, #51874

**Comment by m1093782566** [comment]
#54120 went in, let's wait for #51874

**Comment by cmluciano** [comment]
Nice! The test grid is now passing since #54120

**Comment by m1093782566** [comment]
Glad to see gci-gce-ipvs CI job is running happily. I think we can close this issue.

Thanks all again!

**Comment by Lion-Wei** [comment]
I'm afraid we should reopen this issue, cause the CI still not using ipvs mode, kube-proxy pod can't load kernel modules correctly, this is the pr log:
```
Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_rr ip_vs_sh ip_vs_wrr nf_conntrack_ipv4]
Can't use ipvs proxier, trying iptables proxier
Using iptables Proxier.
```
But in my local environment, it works well.

**Comment by Lion-Wei** [comment]
@MrHohn , unfortunately, seems like kube-proxy can't switch to ipvs mode in ipvs Ci job, cause using "modprobe" load kernel modules failed. But it works well in my local environment, is there anything different on GCE? Any information or suggestion will be appreciate, thanks.

**Comment by MrHohn** [comment]
@Lion-Wei Seems like all of `ip_vs_rr`, `ip_vs_wrr`, `ip_vs_sh` are not available in the default GCE enviroment. Here is what I got from one of the GCI nodes:
```
# pwd
/lib/modules/4.4.64+/kernel/net/netfilter/ipvs
# ls
ip_vs.ko
# cat /etc/os-release
BUILD_ID=9592.90.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c0dda75c2c06905ff4a2e8b41de27d4f2d773856
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=60
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=60
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

Adding @kubernetes/sig-node-bugs for more insights. Why aren't those common IPVS modules included in GCI image?

**Comment by m1093782566** [comment]
cc @vfreex, any comments?

**Comment by vfreex** [comment]
@m1093782566 I guess the required kernel modules are not compiled in CI.
Can we get the kernel compilation config file of installed kernel and take a look?

**Comment by vfreex** [comment]
@m1093782566 BTW, actually I am not sure if all kernel modules like `ip_vs_rr`,` ip_vs_wrr`,` ip_vs_sh` are strictly required by the IPVS proxier. If they are required, maybe we should suggest Container-Optimized OS to compile those kernel modules.

**Comment by m1093782566** [comment]
Thanks for your suggestion. @Lion-Wei will do some tests and will update here if has some interesting findings.

**Comment by m1093782566** [comment]
cc @haibinxie

**Comment by Lion-Wei** [comment]
@m1093782566 @vfreex I just tested this. Turn out we do need `ip_vs_*` kernel modules.
Those kernel modules are correspond with IPVS schedulers, by default kube-proxy use scheduler `rr`, so `ip_vs_rr` is needed. 
If we did't specify the scheduler, ipvs will use `wlc`, then `ip_vs_wlc` is needed.
So, according to the test result, if the GCI image only have `ip_vs`, we can't create any ipvs rules...

**Comment by m1093782566** [comment]
cc @thockin

**Comment by Lion-Wei** [comment]
```
W1109 05:36:37.536088       7 proxier.go:660] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1109 05:36:37.537101       7 proxier.go:660] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1109 05:36:37.538469       7 proxier.go:660] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
E1109 05:36:37.541680       7 server_others.go:279] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_rr ip_vs_sh ip_vs_wrr nf_conntrack_ipv4]
I1109 05:36:37.541701       7 server_others.go:288] Can't use ipvs proxier, trying iptables proxier
I1109 05:36:37.543717       7 server_others.go:124] Using iptables Proxier.
```

**Comment by m1093782566** [comment]
@MrHohn 

Can we run IPVS CI with OS images other than GCI OS?

**Comment by cmluciano** [comment]
cc @ixdy I think I noted a comment from you about these modules recently, but I cannot find the issue/pr

**Comment by BenTheElder** [comment]
@cmluciano you did: https://github.com/kubernetes/kubernetes/pull/46580#issuecomment-342980714

**Comment by cmluciano** [comment]
cool so what do we need to do in this case @ixdy ?

**Comment by ixdy** [comment]
Not sure. I was mostly asking about the need to install `module-init-tools`/`kmod`, which I now understand.
For missing kernel modules, we'll probably need to follow up with the team maintaining the GCI image.

**Comment by dchen1107** [comment]
Yes, COS image doesn't have ip_vs_* modules because it never being requested. We requested a couple of days ago, and they are working on it. But it will take some time to release the changes. 

Meanwhile, since the feature was only enabled for a particular test job, you can build your own OS image, and override the default OS image for your test job.

**Comment by Lion-Wei** [comment]
@dchen1107 , Thanks, But I'm not very familiar with build OS image, is there any document or something about "how to build OS image and override the dafault OS image"? Really appreciate that.
> since the feature was only enabled for a particular test job, you can build your own OS image, and override the default OS image for your test job.

**Comment by dchen1107** [comment]
@Lion-Wei Just checked GKE Ubuntu OS image, and it has ip_vs_* modules by default. 

```
# modprobe ip_vs_rr
# modprobe ip_vs_wrr
# modprobe ip_vs_sh

# lsmod | grep ip_vs
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  0
ip_vs                 147456  6 ip_vs_rr,ip_vs_sh,ip_vs_wrr
libcrc32c              16384  2 raid456,ip_vs

If you want to run your test on GCE, you can use that image. There are a plenty of test jobs using Ubuntu image at https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml, you can start from there.

**Comment by Lion-Wei** [comment]
@dchen1107 Thanks

**Comment by m1093782566** [comment]
That's great! @dchen1107

**Comment by m1093782566** [comment]
IPVS CI is running, please check: http://k8s-testgrid.appspot.com/sig-network-gce#kubeadm-gce-ipvs

I am going to close this PR.

/close
