### ISSUE TITLE
Conformance tests: should provide Internet connection for containers - ping is blocked in Azure

### ISSUE THREAD

**Issue by cpanato** [kubernetes/kubernetes#54925]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The test checks the internet connectivity using ping, and in one of our case, when using Azure as cloud provider it block the ping by default and we are not enabling that because there is no need for that.
line of the test: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L52

Maybe this test can use another way to test the internet connectivity. I will be happy to provide a PR if you guys agree to change the way to check that.

https://blogs.msdn.microsoft.com/mast/2014/06/22/use-port-pings-instead-of-icmp-to-test-azure-vm-connectivity/

**Comment by cpanato** [comment]
@kubernetes/sig-testing

**Comment by dims** [comment]
already fixed : https://github.com/kubernetes/kubernetes/pull/53381
