### ISSUE TITLE
How to install and configure kubernetes using Ubuntu 14.04

### ISSUE THREAD

**Issue by bainim** [kubernetes/kubernetes#54929]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:

**What you expected to happen**:
I'm expecting to have a master and two slaves(nodes) 
**How to reproduce it (as minimally and precisely as possible)**:
I can't found how to get this scénario beacause all what i found is about ubuntu 16.04 and i think that there is a huge difference between the two ubuntu version.
Is there any example (clear and precise) about that?

**Anything else we need to know?**:

**Environment**:
- OS (ubuntu 14.04):
- Install tools:
 docker.io 
 ssl
 curl

**Comment by vbmade2000** [comment]
@bainim Have you checked `http://stuartingram.com/2016/08/31/installing-kubernetes-on-ubuntu-14-04/` ?

**Comment by dims** [comment]
Thanks for your interest in Kubernetes. Please use StackOverflow or the kubernetes-users mailing lists for these kinds of questions. (You will get many more people reading them there than filing an issue.)

https://stackoverflow.com/questions/tagged/kubernetes
https://groups.google.com/forum/#!forum/kubernetes-users

/close

**Comment by bainim** [comment]
Thank you for your response @vbmade2000  but in this example there is no nodes , i think that just about master !
