### ISSUE TITLE
failed to create rbd image: fork/exec /usr/bin/rbd: invalid argument, command output:

### ISSUE THREAD

**Issue by mattiasberge** [kubernetes/kubernetes#54941]
/kind bug
/sig storage

## **What happened**:
**logs of controller-manager**
W1101 14:05:30.134407       7 rbd_util.go:364] failed to create rbd image, output
W1101 14:05:30.134459       7 rbd_util.go:364] failed to create rbd image, output
W1101 14:05:30.134507       7 rbd_util.go:364] failed to create rbd image, output
E1101 14:05:30.134529       7 rbd.go:323] rbd: create volume failed, err: failed to create rbd image: fork/exec /usr/bin/rbd: invalid argument, command output:
I1101 14:05:30.134553       7 pv_controller.go:1331] failed to provision volume for claim "default/claim5" with StorageClass "fast": failed to create rbd image: fork/exec /usr/bin/rbd: invalid argument, command output:

## What you expected to happen:
rbd executed successfully to create a volume on the ceph pool 'kube'

## How to reproduce it (as minimally and precisely as possible):
**ceph config**
ceph admin key = AQAMZ/hZheYqAxAAURdTDYs4GPc378Vp0PLeqA==
ceph kube key = AQDcffhZ1i3HMxAA5oB+SuIbzSKc+9FDc5tKeQ==
ceph --cluster ceph auth get-or-create client.kube mon 'allow r' osd 'allow rwx pool=kube'

ceph-secrets for users (admin, kube) with base64 encoded key
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: QVFBTVovaFpoZVlxQXhBQVVSZFREWXM0R1BjMzc4VnAwUExlcUE9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-kube
data:
  key: QVFEY2ZmaFoxaTNITXhBQTVvQitTdUlielNLYys5RkRjNXRLZVE9PQ==

**Storageclass 'fast'**
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/rbd
parameters:
  monitors: 1:6789,2:6789,3:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kube
  userId: kube
  userSecretName: ceph-secret-kube

**PersistentStorageClaim**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: fast

**Executing 'rbd' inside of controller-manager works:**
$ kubectl exec -ti kube-controller-manager-st14d02ls-ztda11350501 -n kube-system rbd
   
2017-11-01 14:10:26.664691 7febc9f05780 -1 did not load config file, using default settings.
rbd: you must specify a command.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5+coreos.0", GitCommit:"070d238cd2ec359928548e486a9171b498573181", GitTreeState:"clean", BuildDate:"2017-08-31T21:28:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
. 3 masters / api servers

- OS (e.g. from /etc/os-release):
10x centos 7.3 nodes

- Kernel (e.g. `uname -a`):
4.9.44, custom kernel build.

- Install tools:
Kubespray

- Others:
docker 1.13
hyperkube 1.7.5
ceph version 0.94.10 (b1e0532418e4631af01acbc0cedd426f1905f4af

**Comment by kondas** [comment]
Hi, I've seen the same error when forgot to base64 encode the ceph secret key.
`ceph auth get-key client.admin | base64`

**Comment by kondas** [comment]
Also, are the monitor nodes IP address configured properly in the storage clas? 
Storageclass 'fast'
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: fast
provisioner: kubernetes.io/rbd
parameters:
**monitors: 1:6789,2:6789,3:6789**
adminId: admin

**Comment by mattiasberge** [comment]
Kondas,  I had the node IPs right and the password was base64 encoded.

I moved forward and tried another approach. Closing this issue
