### ISSUE TITLE
Namespaced dependent of cluster scoped resource is sometimes erroneously garbage collected

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#54940]
If a namespaced resource is owned by a cluster scoped resource, and the namespaced dependent is processed **before** the cluster scoped owner has ever been observed by the garbage collector, the dependent will be erroneously deleted. The cause is a race condition in the GC's [virtual node handling](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/graph_builder.go#L377). Currently, virtual nodes always inherit the namespace of the dependent, which is an invalid assumption when:

1. The owner is cluster scoped
2. The owner is namespaced but in a different namespace than the dependent

Under these conditions, the dependent will be deleted because the GC has misidentified the location of the owner, causing the dependent reference to always be considered dangling.

I've created some unit and integration tests in a branch which demonstrate the problems and will help serve as verification of the fix:

* A [unit test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/pkg/controller/garbagecollector/garbagecollector_test.go#L675) which demonstrates some problematic cases and attempts to describe the important behaviors more specifically.
* An [integration test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/test/integration/garbagecollector/garbage_collector_test.go#L433) which reproduces [this unit test](https://github.com/ironcladlou/kubernetes/blob/cluster-scoped-owner-gc-fix/pkg/controller/garbagecollector/garbagecollector_test.go#L736) (the problem reported in this issue). Requires `stress` to reproduce.

This was discovered by a test flake in OpenShift (https://github.com/openshift/origin/issues/17085). @caesarxuchao has [proposed some possible fixes](https://github.com/openshift/origin/issues/17085#issuecomment-340582560) to the cluster scoped owner bug.

/kind bug
@kubernetes/sig-api-machinery-bugs 

/cc @jim-minter

**Comment by caesarxuchao** [comment]
`OwnerReference` doesn't have a `namespace` field was by design, because we didn't see use cases of cross-namespace garbage collection. I still think we don't have such use cases.

Also, as your PR shows, without the `namespace` field, we can't reliably support the case where the owner is cluster-scoped while the dependent is namespace-scoped, or the reverse. These might be valid use cases. Do you mind sharing the use case in openshift?

How about just adding the namespace field to the ownerReference? For backwards compatibility, the apiserver can default the field to match dependent's namespace. Also, we can add validation rule to invalidate cross-namespace ownerRefs. If we go this way, we'll need api reviewers to evaluate the design.

**Comment by ironcladlou** [comment]
@caesarxuchao 
>However, as your PR shows, without the namespace field, we can't reliably support the case where the owner is cluster-scoped while the dependent is namespace-scoped, or the reverse.

I might be misunderstanding... my PR makes it possible for owner to be cluster scoped and dependent to be namespace scoped.

>These might be valid use cases. Do you mind sharing the use case in openshift?

@jim-minter found this while developing service broker stuff, where a cluster scoped object is created by the system which owns other objects created automatically in namespaces. I'll leave it to him to further elaborate on the rationale.

>How about just adding the namespace field to the ownerReference? For backwards compatibility, the apiserver can default the field to match dependent's namespace. Also, we can add validation rule to invalidate cross-namespace ownerRefs. If we go this way, we'll need api reviewers to evaluate the design.

I have some more questions about that which, as you say, would require some talking through (e.g. should the field be a pointer so empty namespace can represent cluster scoped?). First I'd like to clarify the cluster/namespace relationship stuff before trying to deal with cross-namespace, if that's okay.

**Comment by caesarxuchao** [comment]
> I might be misunderstanding... my PR makes it possible for owner to be cluster scoped and dependent to be namespace scoped.

I misread the code. Anyway, if the dependent is cluster-scoped, and owner is namespace-scoped, even your PR can't handle that, right?

**Comment by ironcladlou** [comment]
@caesarxuchao 

>I misread the code. Anyway, if the dependent is cluster-scoped, and owner is namespace-scoped, even your PR can't handle that, right?

I don't have a test case for it, but I'll bet it works already on master if both objects are in the uidToNode cache before processing (keep in mind my PR just fixes a race condition, doesn't actually introduce any new support), and the restmapper fix for the race is  generic.

HOWEVER, I just noticed a flake in the test-cmd GC CRD tests, and I'll be it's because of a stale restmapper during event processing of the CRDs. Which means when restmapping fails in virtual node processing we'll have to surface the error and retry... which seems less than ideal. I'm liking your idea to just make OwnerReference more explicit in the first place. Then we don't need any flaky rest mapping in here, right?

**Comment by caesarxuchao** [comment]
> I don't have a test case for it, but I'll bet it works already on master if both objects are in the uidToNode cache before processing (keep in mind my PR just fixes a race condition, doesn't actually introduce any new support), and the restmapper fix for the race is generic.

If the dependent is cluster-scoped, and owner is namespace-scoped, how do you infer what namespace the owner belong to when creating the virtual node?

> I'm liking your idea to just make OwnerReference more explicit in the first place. Then we don't need any flaky rest mapping in here

Yeah, that's what I thougtht.

**Comment by munnerz** [comment]
I can't comment on the test flake itself, but is it not possible for the garbage collector to determine that the owning type is non-namespaced via the discovery API?

**Comment by ironcladlou** [comment]
@munnerz 
>I can't comment on the test flake itself, but is it not possible for the garbage collector to determine that the owning type is non-namespaced via the discovery API? (which avoids the need for a namespace field, and drops the requirement for some cross-namespace check previously mentioned)

That's essentially the approach I took in https://github.com/kubernetes/kubernetes/pull/54943, but:

1. It introduces a failure/retry mode in a critical processing path (as the discovery client is occasionally stale and thus periodically refreshed)
2. It doesn't address inter-namespace references (which is of secondary importance)

Explicit references as @caesarxuchao suggests provides the controller with enough context to avoid discovery altogether, and also opens the door to inter-namespace references. It also makes for a more robust API over the implicit/inference based behavior I was exploring.

**Comment by liggitt** [comment]
GC was intentionally disallowed cross-namespace references to begin. If we revisit that, we need to consider carefully the implications, like leaking information about objects in other namespaces, and blocking deletion of objects in other namespaces.

**Comment by ironcladlou** [comment]
>GC intentionally disallowed cross-namespace references to begin. If we revisit that, we need to consider carefully the implications, like leaking information about objects in other namespaces, and blocking deletion of objects in other namespaces.

Info leak was a concern I had with inter-namespace references... would there be a similar concern with cluster scoped owners? Is this all to say that validation of the namespace field would have to tie into RBAC?

To be clear, you can actually create a cluster scoped owner reference today and it'll usually work unless you trigger the race described in this issue.

**Comment by lavalamp** [comment]
Allowing this (referencing a cluster scoped resource) would be a policy change; we should think about adding validation to prevent this in the mean time. kube-apiserver could at least prevent references of nodes & namespaces?

**Comment by lavalamp** [comment]
I think it does make sense to expand to allow a cluster scoped resource to be a parent.

**Comment by lavalamp** [comment]
@caesarxuchao can you file an issue to discuss expanding the owner reference to include cluster scoped resources?

**Comment by caesarxuchao** [comment]
> It doesn't address inter-namespace references (which is of secondary importance)

@ironcladlou I'm less concerned with the inter-namespace references, unless we have strong use cases.

Another case that will require explicitly adding the "Namespace" field to the ownerRef is where owner is namespace-scoped, and dependent is cluster-scoped. Again, before supporting that, we need to see compelling use cases.

I left a [comment](https://github.com/kubernetes/kubernetes/pull/54943/files#r148858189) in #54943, I think it will solve the failure/retry issue. And with that, I believe we can solve the case where owner is cluster-scoped, and dependent is namespace-scoped. What do you think?

**Comment by ironcladlou** [comment]
Revisiting this to add another scenario where things can go very wrong: if the timing works out favorably, a user can actually successfully create a cluster-owner -> namespace-dependent relationship that works with the GC. However, if you restart the controller process (and thus the GC), the processing of the *existing relationship* is again subject to the race, and often the dependent is deleted upon controller restart.

Just wanted to record the scenario for reference.

**Comment by ironcladlou** [comment]
@lavalamp @caesarxuchao Something I was mulling over with @liggitt and was curious to get your thoughts... given UID is required for an object reference for GC, and in the context of GC only the UID is important for existence checks, it seems like the use of namespace and name in the reference are both redundant and the source of internal complexity/ambiguity. Is this just a fact of life in the absence of field selectors? Is there value in reference namespace/name I'm missing? Other thoughts?

**Comment by liggitt** [comment]
Until we can look up by uid, you need the namespace and name for efficient live look up of as yet uncached objects
