### ISSUE TITLE
Heapster panics

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#54962]
I also hit https://github.com/kubernetes/heapster/issues/1838 when running cri-containerd as the container runtime.

The reason is that we don't populate stats like `UsageNanoCore` in cri-containerd integration now. @abhi is adding the containerd support in cadvisor, after that we should have full summary metrics.

However, heapster should not panic in this case anyway.

@piosz @kubernetes/sig-instrumentation-bugs Can we cut a heapster patch release and update heapster in the main repo?

**Comment by yujuhong** [comment]
> @piosz @kubernetes/sig-instrumentation-bugs Can we cut a heapster patch release and update heapster in the main repo?

+1. Many new CRI integration would run into this issue.

**Comment by brancz** [comment]
In fact, as far as I am aware, not a single CRI implementation currently implements any of the stats calls.

**Comment by yujuhong** [comment]
> In fact, as far as I am aware, not a single CRI implementation currently implements any of the stats calls.

I beg to differ: https://github.com/kubernetes-incubator/cri-containerd/blob/e723a5018b1b02d93f5e26a2f7df685fde5752fa/pkg/server/container_stats.go
That's the reason why @Random-Liu filed the issue.

**Comment by Random-Liu** [comment]
@brancz Yeah `cri-containerd` does implement the CRI stats. Currently it only support core metrics, which is a part of summary api. We are working on integration with cadvisor, before that some fields in summary api such as `NanoCoreSeconds` will be nil.

Current heapster version will crash when `NanoCoreSeconds` is nil, which shouldn't happen. :)

**Comment by brancz** [comment]
My bad, thanks for the pointer :slightly_smiling_face:. I'll correct my statement: I believe no CRI implementation except for cri-containerd implements the stats calls. The ones I explicitly checked are: dockershim, cri-o, rktlet.

**Comment by brancz** [comment]
Something I'm wondering about though:

> @abhi is adding the containerd support in cadvisor, after that we should have full summary metrics.

The intention of the stats calls is in order to be able to get rid of cAdvisor. Making the stats calls depend on cAdvisor seems to cover up the issues it has.

Re: https://github.com/kubernetes/kubernetes/issues/53615

**Comment by Random-Liu** [comment]
@brancz Here is the reason that we still have to integrate with cadvisor for now. https://github.com/kubernetes-incubator/cri-containerd/issues/341

**Comment by brancz** [comment]
If I understand correctly this is meant as a migration mean, so that both are possible for some time, and then we drop cAdvisor once a reasonable migration period has been granted.

**Comment by kawych** [comment]
I will take a look at Heapster and try to fix this.

@Random-Liu 
Can you advise how to reproduce the issue? This will help a lot with debugging and verifying a fix once it's ready.

**Comment by loburm** [comment]
@kawych this is already fixed at head and 1.4.3 version of heapster https://github.com/kubernetes/heapster/pull/1839. The problem that @Random-Liu is using kubernetes version from head and we have there 1.5.0-beta.0: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml#L30

I see two possible solutions:
1. Change version of heapster to 1.4.3 at head of kubernetes. Piotr mentioned that 1.5.0 has still a lot of problems, so it maybe makes sense.
2. Make a new release of heapster (1.5.0-beta.1) and after that bump version at head.

**Comment by loburm** [comment]
And thanks for taking this issue.

**Comment by yguo0905** [comment]
Not directly related to this issue:
@loburm, a more general discussion is at https://github.com/kubernetes/heapster/issues/1793. We'd like to understand which fields are required and optional in heapster, so that we won't crash heapster with partial result.

**Comment by Random-Liu** [comment]
@loburm We've merged a work around for now https://github.com/kubernetes/kubernetes/pull/55213. Hopefully it works.

But anyway, we should fix this in 1.9.

**Comment by dims** [comment]
@Random-Liu what needs to be done for 1.9 here?

**Comment by dims** [comment]
@Random-Liu we'll need an assignee as well

**Comment by Random-Liu** [comment]
@dims We just need to update heapster version. https://github.com/kubernetes/kubernetes/pull/55615
