### ISSUE TITLE
cpu_manager "failed to write a *:* rwm to devices.allow" error message

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#54967]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig node

**What happened**:

On 1.8+ kubelet with --cpu-manager-policy=static, there is a constant stream of logging every 10 seconds or so in the following formats:

`kubelet: E1030 14:13:05.012702 23623 remote_runtime.go:302] UpdateContainerResources "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986" from runtime service failed: rpc error: code = Unknown desc = failed to update container "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986": Error response from daemon: Cannot update container f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986: rpc error: code = Unknown desc = failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod74095402-a88b-11e7-9aea-90b11c4094cf/f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986/devices.allow: invalid argument`

`kubelet: E1030 14:13:05.012729 23623 cpu_manager.go:242] [cpumanager] reconcileState: failed to update container (pod: kube-proxy-47dt8, container: kube-proxy, container id: f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986, cpuset: "0-31", error: rpc error: code = Unknown desc = failed to update container "f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986": Error response from daemon: Cannot update container f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986: rpc error: code = Unknown desc = failed to write a *:* rwm to devices.allow: write /sys/fs/cgroup/devices/kubepods/burstable/pod74095402-a88b-11e7-9aea-90b11c4094cf/f0f24b4647d8a9694427eb7900ce93c8402f81d5b7724eb2207f1a4755f79986/devices.allow: invalid argument)`

for every privileged pod where update would fail but looks expected.

**What you expected to happen**:

It appears the error is expected, and should not be logged continuously.

**How to reproduce it (as minimally and precisely as possible)**:

On 1.8+ kubelet with --cpu-manager-policy=static, have privileged pods (such as kube-proxy) and watch system log.

**Anything else we need to know?**:

This is for a bug that originally reported in #54804, so there is a little bit of context there.  This is the second half of it.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: aremetal/onprem
- OS (e.g. from /etc/os-release): CentOS 7.4.1708
- Kernel (e.g. `uname -a`): 4.13.8-1.el7.elrepo.x86_64
- Install tools: custom
- Others:

**Comment by scheler** [comment]
I see this issue with 1.10.0 with --cpu-manager-policy=static, and I don't understand why this issue was closed without addressing.

The OP says the error message is harmless, but it is confusing, so it would be good if this is addressed.

**Comment by gurvindersingh** [comment]
any update on this as logs are swamping with this message.

**Comment by P1ng-W1n** [comment]
This issue seems to affect 1.11.0 as well.

**Comment by P1ng-W1n** [comment]
It seems to me that this issue affects kube-proxy related PODs only (at least on my systems):
According to the error message Kubelet tries to write 'a *:* rwm' into the POD's devices.allow file, however kube-proxy has an additional child group in that structure that forbids such action:

> $ find /sys/fs/cgroup/devices/kubepods/besteffort/podb8e15043-7dda-11e8-8c41-38eaa793e2f4/a28e5ed84558b3b7f94d66b49e428831cd2be6d40f09c07dec0e8f1a879a280a -name devices.allow
> /sys/fs/cgroup/devices/kubepods/besteffort/podb8e15043-7dda-11e8-8c41-38eaa793e2f4/a28e5ed84558b3b7f94d66b49e428831cd2be6d40f09c07dec0e8f1a879a280a/devices.allow
> /sys/fs/cgroup/devices/kubepods/besteffort/podb8e15043-7dda-11e8-8c41-38eaa793e2f4/a28e5ed84558b3b7f94d66b49e428831cd2be6d40f09c07dec0e8f1a879a280a/kube-proxy/devices.allow

> $ echo 'a *:* rwm' > /sys/fs/cgroup/devices/kubepods/besteffort/podb8e15043-7dda-11e8-8c41-38eaa793e2f4/a28e5ed84558b3b7f94d66b49e428831cd2be6d40f09c07dec0e8f1a879a280a/devices.allow
> -bash: echo: write error: Invalid argument
> $ echo 'a *:* rwm' > /sys/fs/cgroup/devices/kubepods/besteffort/podb8e15043-7dda-11e8-8c41-38eaa793e2f4/a28e5ed84558b3b7f94d66b49e428831cd2be6d40f09c07dec0e8f1a879a280a/kube-proxy/devices.allow 
> $ echo $?
> 0

A similar issue is described here: https://github.com/kubernetes/kubernetes/issues/66614

**Comment by P1ng-W1n** [comment]
Since I upgraded my cluster to 1.12.1 I can't see those errors in the syslog / journal. However, as far as I can see the default cgroup structure (and thus the location of the devices.allow files) did not change.
The default CM still refers to 'resourceContainer: /kube-proxy', so I'm not sure what has changed to solve (?) this issue:

# kubectl describe cm kube-proxy -n kube-system  |grep -i resour
resourceContainer: /kube-proxy

Could somebody else verify the same please?

**Comment by Arslanbekov** [comment]
Similar error, kubelet `1.12.1`

**Comment by zouyee** [comment]
related issue： https://github.com/moby/moby/issues/37918

**Comment by zouyee** [comment]
k8s: 1.15
First we stop kubelet and modified kube-proxy configmap to `resourceContainer: "/"`, then delete kube-proxy and restart kubelet

**Comment by P1ng-W1n** [comment]
> k8s: 1.15
> First we stop kubelet and modified kube-proxy configmap to `resourceContainer: "/"`, then delete kube-proxy and restart kubelet

Hi zouyee 

I'm not sure I understand this explanation. Could you go into more detail please? Or could you please share the commit that implements this behavior?

**Comment by borgerli** [comment]
# Reason

This problem happens when kube-proxy is deployed as DaemonSet, and eanables `static` cpu-manager-policy for kublet on k8s clusters older than 1.16( I verified 1.14, but not 1.15)

As discussed, this problem relates to the `resource-container` parameter of kube-proxy. Although it's deprecated, its default value is still `kube-proxy`, and kube-proxy under version 1.16 will still create the `kube-proxy` sub directory under its each cgroup subsystem dirs. And for the `devices` subsystem, it's not allow to write to `devices.allow` file when there is any sub directory. Otherwise, system will complain with `"invalid argument"` message.

# Solution
Set `resource-container` parameter of kube-proxy  to blank:

```
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - args:
        - --kubeconfig=/var/lib/kube-proxy/config
        - --hostname-override=$(NODE_NAME)
        - --v=2
        - --resource-container=
```

**Comment by chenqiangzhishen** [comment]
add `--resource-container=` seems the error disappeared, pls see after `Jul 08 15:48:47 ` logs output.

```
Jul 08 15:48:24 k8s-master1 kubelet[16135]: : unknown)
Jul 08 15:48:36 k8s-master1 kubelet[16135]: E0708 15:48:36.290996   16135 remote_runtime.go:350] UpdateContainerResources "cfc4ba0
Jul 08 15:48:36 k8s-master1 kubelet[16135]: : unknown
Jul 08 15:48:36 k8s-master1 kubelet[16135]: E0708 15:48:36.291035   16135 cpu_manager.go:183] [cpumanager] AddContainer error: rpc
Jul 08 15:48:36 k8s-master1 kubelet[16135]: : unknown
Jul 08 15:48:36 k8s-master1 kubelet[16135]: E0708 15:48:36.291059   16135 cpu_manager.go:252] [cpumanager] reconcileState: failed
Jul 08 15:48:36 k8s-master1 kubelet[16135]: : unknown)
Jul 08 15:48:47 k8s-master1 kubelet[16135]: E0708 15:48:47.449432   16135 remote_runtime.go:350] UpdateContainerResources "cfc4ba0
Jul 08 15:48:47 k8s-master1 kubelet[16135]: : unknown
Jul 08 15:48:47 k8s-master1 kubelet[16135]: E0708 15:48:47.449473   16135 cpu_manager.go:183] [cpumanager] AddContainer error: rpc
Jul 08 15:48:47 k8s-master1 kubelet[16135]: : unknown
Jul 08 15:48:47 k8s-master1 kubelet[16135]: E0708 15:48:47.449496   16135 cpu_manager.go:252] [cpumanager] reconcileState: failed
Jul 08 15:48:47 k8s-master1 kubelet[16135]: : unknown)
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.514253   16135 kuberuntime_manager.go:784] container start failed: Crea
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.514317   16135 pod_workers.go:190] Error syncing pod b17099b128e6a7e5a5
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.527577   16135 helpers.go:291] Failed to remove the conflicting contain
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.527717   16135 remote_runtime.go:109] RunPodSandbox from runtime servic
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.527775   16135 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "kub
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.527806   16135 kuberuntime_manager.go:697] createPodSandbox for pod "ku
Jul 08 15:49:08 k8s-master1 kubelet[16135]: E0708 15:49:08.527866   16135 pod_workers.go:190] Error syncing pod b17099b128e6a7e5a5
Jul 08 15:49:09 k8s-master1 kubelet[16135]: E0708 15:49:09.557208   16135 kubelet.go:1641] Failed creating a mirror pod for "kube
```
