### ISSUE TITLE
Azure Cloud Provider: Load Balancer

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#54961]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

/kind bug
/sig azure

**What happened**:
The following behaviors observed in Azure Cloud Provider
*Dangling LB Resources*
With hyper-active large clusters specially with a lot of create/delete services calls the provider does not cleanly delete IP Config/LB Rule/NSG Config. This can be tested with creating a fairly large cluster (100+ nodes) and creating multiple services.

*Expected behavior*: The provider should cleanly delete LB(ARM) resources when a service is un-provisioned. It must also cleanly remove resources if the create process failed, such as the case of reaching max of 60 IP per LB or intermitted failures during ARM calls).

*Collapsing NSG Rules*
ref: https://github.com/kubernetes/kubernetes/issues/54899

*Wrong LB Selected in clusters with 2+ availability sets*
A user who runs a cluster with many availability sets. This the SOP for large scale clusters, services are incorrectly always exposed on the first LB (which is subject to be deleted/changed in typical operating environment) even when there are other available LBs (attached to other availability sets in the same cluster).

*Expected Behavior*: The provider should use *all* the available LBs in the cluster instead of maxing the first one and failing to recognize other LBs..

please ref this issue for any fixes for the above

@jdumars  

**Environment**:
- Kubernetes version (use `kubectl version`):
1.6.x
1.7.x
1.8.x
- Cloud provider or hardware configuration:
Azure
- OS (e.g. from /etc/os-release):
(all)
- Kernel (e.g. `uname -a`):
(all)
- Install tools:
(all)

**Comment by jdumars** [comment]
I believe this has been resolved.  @khenidak pleas re-open if that's not the case.
