### ISSUE TITLE
Bug: Kubelet does not assign Host IP for pods with HostNetwork for --cloud-provider=external

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#54965]
I am trying to test CCM in DigitalOcean using Ubuntu 16.04 64-bit image using Kubeadm 1.8.0. I have found that Kubelet will not assign IP for pods with `HostNetwork: true`, if I start kubelet with `--cloud-provider=true`.  This breaks CNi plugins like Calico #510 .

Reproducible steps:
```
#!/bin/bash

set -x
set -eou pipefail

apt-get update -y
apt-get install -y apt-transport-https curl ca-certificates

curl -fSsL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list

apt-get update -y
apt-get install -y cron docker.io ebtables git kubectl kubelet socat kubeadm ntp || true

cat > /etc/systemd/system/kubelet.service.d/20-pharmer.conf <<EOF
[Service]
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
EOF
systemctl daemon-reload

kubeadm reset
kubeadm init --pod-network-cidr=192.168.0.0/16 --skip-token-print

mkdir -p ~/.kube
sudo cp -i /etc/kubernetes/admin.conf ~/.kube/config
sudo chown $(id -u):$(id -g) ~/.kube/config
```

```
root@c8:~# kubectl get pods -n kube-system -o wide
NAME                         READY     STATUS    RESTARTS   AGE       IP        NODE
etcd-c8                      1/1       Running   0          9m        <none>    c8
kube-apiserver-c8            1/1       Running   0          8m        <none>    c8
kube-controller-manager-c8   1/1       Running   0          8m        <none>    c8
kube-dns-545bc4bfd4-zcr9b    0/3       Pending   0          9m        <none>    <none>
kube-proxy-7ktph             1/1       Running   0          9m        <none>    c8
kube-scheduler-c8            1/1       Running   0          8m        <none>    c8
```
We are supposed to see the external IP of the Host for these pods (except kube-dns pod).

**Comment by tamalsaha** [comment]
/kind bug
Reopedn here from https://github.com/kubernetes/kubeadm/issues/514, since looks like Kubelet bug.

cc; @wlan0 @luxas @andrewsykim

**Comment by jhorwit2** [comment]
@tamalsaha  What's the output of `kubectl get nodes -owide`?

**Comment by jhorwit2** [comment]
Also, are you using RBAC?

**Comment by jhorwit2** [comment]
I'm going to guess the problem is that your rbac role for the CMM is missing:
```
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
```

Would you mind checking the logs of your CCM for something like 
```
E1105 22:06:05.789959       7 node_controller.go:188] Error patching node with cloud ip addresses = [failed to patch status "{\"status\":{\"addresses\":[{\"address\":\"<ip>\",\"type\":\"InternalIP\"},{\"address\":\"<ip>\",\"type\":\"ExternalIP\"}]}}" for node "<node>": nodes "<node>" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot patch nodes/status at the cluster scope]
```

**Comment by tamalsaha** [comment]
@jhorwit2, your response helped me solve this. Thank you!

In my case, I had not even deployed CCM, as I was hoping for the kube-dns etc pods to become ready. Now, I deployed DO's ccm right after `kube init` was finished. After that the master instance got IP and the kube-apiserver etc pods also got IP.

Regarding RBAC, I updated the docs :) https://github.com/kubernetes/website/pull/6111

**Comment by klausenbusk** [comment]
I assume this is the expected behavior? `bootkube` [need](https://github.com/kubernetes-incubator/bootkube/issues/453) the hostIP when starting `kube-apiserver` as a [pod](https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L151) (`--advertise-address=podIP`). So right now the only solution seems to be removing `--advertise-address` from `kube-apiserver`, but it was added for a reason: https://github.com/kubernetes-incubator/bootkube/issues/453.

Is there anyway I can let `kubelet` populate the `hostIP` until the CCM is ready?

**Comment by jhorwit2** [comment]
@klausenbusk You can use `--node-ip` flag on the kubelet. That has some limitations though.

**Comment by klausenbusk** [comment]
> @klausenbusk You can use --node-ip flag on the kubelet. That has some limitations though.

That doesen't seems to change anything, `podIP` is still blank.
