### ISSUE TITLE
etcd shutdown kubernetes after the delay becomes high

### ISSUE THREAD

**Issue by xiaosadexiaohai** [kubernetes/kubernetes#54981]
Under normal circumstances
![image](https://user-images.githubusercontent.com/18409309/32312576-85989b68-bf6c-11e7-85dc-37b7e3779dab.png)
Only in the case of etcd services
![image](https://user-images.githubusercontent.com/18409309/32312593-9c520f9c-bf6c-11e7-9988-fee0c1a3841b.png)
etcd machine shutdown case
![image](https://user-images.githubusercontent.com/18409309/32312620-b962c5d6-bf6c-11e7-9d78-92ad9bc2e7d0.png)

**Comment by lavalamp** [comment]
I'm sorry, we're having a hard time understanding this. Can you clarify?

**Comment by xiaosadexiaohai** [comment]
@lavalamp 
If etcd machine kube-api request after the machine will become very slow, but only the service does not slow etcd service will only slow down

**Comment by lavalamp** [comment]
I'm terribly sorry, I can't understand that, either-- if you write it in (guessing based on your user name) Mandarin we have some team members that will be able to read it?

**Comment by xiaosadexiaohai** [comment]
上图想表达的意思是:etcd直接关闭服务不会影响访问速度,但是如果直接关闭一台etcd的服务器就会造成延迟非常高 @lavalamp

**Comment by caesarxuchao** [comment]
What do you mean by "closing etcd service"?

The latency surge is expected if you shut down the etcd machine.
