### ISSUE TITLE
how kubernetes interact openstack when config the cloud provider to openstack

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#54984]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>/kind feature
> /kind feature

**What happened**:
when i config the para --cloud-config=/etc/kubernetes/kube_openstack_config  --cloud-provider=openstack
-bash-4.2# kubectl get nodes
NAME            STATUS    AGE       VERSION
k8s-jlx-node1   Ready     22d       v1.6.9+a3d1dfa6f4335
k8s-jlx-node2   Ready     1d        v1.6.9+a3d1dfa6f4335
how the kubelet interact openstack and get the nodename and instanceid
I read the code that some place get the instanceid in /var/lib/cloud/data/instance-id local filesystem 
and some place get the instanceid with the nodename to get the instanceid
and run the attachdisk and detachdisk use the instanceid with the nodename to get the instanceid?
thanks
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):k8sv1.6.9
- Cloud provider or hardware configuration:openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by FengyunPan** [comment]
@jianglingxia Have you read this doc:https://github.com/kubernetes/website/blob/master/docs/concepts/cluster-administration/cloud-providers.md ?

**Comment by FengyunPan** [comment]
By instance metadata. (configDrive/metadataService)
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/metadata.go

**Comment by edisonxiang** [comment]
Hey @jianglingxia , the reply of @FengyunPan is valuable, and also you can take a look at the Attach and Detach from here.
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/attacher.go

**Comment by jianglingxia** [comment]
thanks very much,if I have a cluster that the k8s version is 1.6,and have not config the the cloud provider of openstack ,
kubectl get node  maybe 
192.160.1.1 
1.1.1.1 
then upgrade the k8s to 1.8 and config the cloud provider of openstack,so 
kubectl get node  maybe 
k8s-node-1 
k8s-node-2
now the pod before in cluster that k8s is 1.6  upgrade 1.8 may down ? or if related the nodename changed  affect some place ?or how to do this?thanks @edisonxiang @FengyunPan

**Comment by edisonxiang** [comment]
Hey @jianglingxia, I have no more experiences about the upgrade, especially from non-OpenStack Cloud Provider to OpenStack Cloud Provider. I find [a email](https://groups.google.com/forum/#!topic/kubernetes-dev/zs-nfb7C4mw) about this. Maybe you can ping @k82cn to get more informations. @k82cn is a very good man.

**Comment by jianglingxia** [comment]
thanks @edisonxiang 
and
/cc @k82cn can you help me with the problem of upgrade especially from non-OpenStack Cloud Provider to OpenStack Cloud Provider?thanks

**Comment by jianglingxia** [comment]
I confuse that :
1、why config the OpenStack Cloud Provider ,the k8s use the nodename instead of ip?
2、if the nodename has two same and What to do？I read the code and no place to validate the same nodename.
thanks for your reply. @edisonxiang @FengyunPan 
![image](https://user-images.githubusercontent.com/25783555/33112607-098ae26e-cf8f-11e7-826b-275e02736b8f.png)

**Comment by FengyunPan2** [comment]
The name of nova vm always unique, or work bad on kubernetes.

**Comment by jianglingxia** [comment]
thanks,but openstack can let user create vm with same name,Unique identification is the instance id 
![image](https://user-images.githubusercontent.com/25783555/35952074-30e47886-0cb9-11e8-9f59-5f1364f6c6d7.png)
![image](https://user-images.githubusercontent.com/25783555/35952089-3e95a2e8-0cb9-11e8-9e0d-3533f0a7b311.png)
I think maybe we should valid the vm name in  code!

**Comment by FengyunPan2** [comment]
Nova allow vm have same name, but Kubernetes not allow. Kubernetes need unique name now. Kubernetes maybe use vm id in the future.

**Comment by jianglingxia** [comment]
oh,if future use vm id ,will design kubelet return id? like: 
kubectl get node
vmid     ....
our project has used cinder function,
kubectl get node return vm name
maybe Changes more .... if could ，Compatible name maybe!

**Comment by dims** [comment]
so looks like nothing to do here. closing. please reopen if needed

/close
