### ISSUE TITLE
Add net.ipv6.conf.all.disable_ipv6 to sysctl whitelist

### ISSUE THREAD

**Issue by fsouza** [kubernetes/kubernetes#55006]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

We've found an internal use case where we wanted to disable ipv6 in the container, and unfortunately net.ipv6.conf.all.disable_ipv6 is not white-listed. Could this option be added to the white list?

I can send a PR if that's an acceptable change.

**Comment by fsouza** [comment]
Oh, following the recommendation on #54132, I'll open the PR and have the discussion there.

**Comment by tbasim** [comment]
Hello is there any update on this issue?

**Comment by fsouza** [comment]
@tbasim I gave up 🙈 But feel free to reopen the issue/PR #55011 and try to get it merged 😁

**Comment by bowei** [comment]
/reopen

@dchen1107 -- what is the criteria for a whitelisted sysctl?

**Comment by ehashman** [comment]
cc @geofft
who was interested in updating the sysctl allowlist policy, is there a KEP for that yet?

**Comment by geofft** [comment]
Not yet. I think large amounts of `net.*` are safe, but I haven't gotten a chance to go through them / check kernel versions.
