### ISSUE TITLE
namespaces stuck in terminating

### ISSUE THREAD

**Issue by AndrewKoryakin** [kubernetes/kubernetes#55002]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
 Namespaces stuck terminating. 
**What you expected to happen**:
Namespaces deleted
**How to reproduce it (as minimally and precisely as possible)**:
I try to delete namespace, but one of nodes in cluster was unavailable at that time. 

**Anything else we need to know?**:
After node returned, nothing changed (only pods changed status from unknown to running). After all i can create any resources include namespaces, i can delete any resources except  namespaces. I cant delete namespaces, even now created namespaces.
**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: virtual machine(virsh)
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS \n \l
- Kernel (e.g. `uname -a`):Linux kube-master 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by AndrewKoryakin** [comment]
For those who have the same problem. Removal of ThirdPartyResources solved the problem

**Comment by liggitt** [comment]
do you have controller manager logs available?
is this reproducible on 1.8.x?

**Comment by nikhita** [comment]
Related https://github.com/kubernetes/kubernetes/issues/37554.
