### ISSUE TITLE
kubelet starts too many `udevadm trigger`

### ISSUE THREAD

**Issue by kabakaev** [kubernetes/kubernetes#55007]
/kind bug

**What happened**:
kubelet creates too many udev "change" events during Cinder volume attachment.
If volume attachement takes long, then udev event queue gets full, therefore
udev does not answer requests from docker, and PLEG makes the k8s node unhealthy.

**What you expected to happen**:
  * kubelet should not run `udevadm trigger` so often.
  * kubelet should run `udevadm settle --timeout=1 && udevadm trigger`

**How to reproduce it (as minimally and precisely as possible)**:
Deploy k8s on Openstack. Configure k8s cluster with --cloud_provider=openstack.
  * Cordon all nodes except one.
  * SSH into that node. Start `udevadm monitor` and let it run.
  * Create StorateClass for Cinder volumes.
  * Deploy StatefulSet with volumeClaimTemplate pointing to that StorageClass.
  * Optionally, immediately detatch the newly-created cinder volume manually
    through openstack CLI or web interface to simulate a slow cinder attachment.
  * Look back to the `udevadm monitor` to find thousands of udev events.
    In case of the "show" attachement, the "change" udev events will never stop.
  * Also run `top` to find that systemd-udevd consumes 100% CPU.
  * Also run `docker ps` to find that it hangs and never answers.

**Anything else we need to know?**:
Attachment of a new cinder volume includes execution of `udevadm trigger`
command, see links (1-3) below. The `udevadm trigger` generates a "change"
event for every single device on the /sys/devices SysFS. This can be seen by
running `udevadm monitor`.

The execution stack is as follows:
  * Volume Attacher Interface (1) runs WaitForAttach(), which is implemented in (2).
  * The Cinder's WaitForAttach() runs probeAttachedVolume() 2 times per second
    (lines 243 and 247). The "1 second" retry timeout is defined by (3).
  * The probeAttachedVolume() is defined in (4). It triggers SCSI rescan and
    generates udev "change" event on all devices by running `udevadm trigger`.

As you see, both scsi rescan and full udev rescan are triggered 2 times per second.

The scsi bus rescan leads to considerable latency of runnig I/O operations.

The sysemd-udevd is unable to process so many "change" events. The udev queue
gets full, leading to frozen `docker ps` operation that cAdvisor runs every 2 seconds.
After 3 minutes, kubelet marks itself unhealthy (5) due to PLEG (6).

(1) [Volume Attacher interface runs WaitForAttach()](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/volume.go#L176)
(2) [Cinder Attacher implementation of WaitForAttach()](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/cinder/attacher.go#L224)
(3) [1 second retry timeout](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/cinder/attacher.go#L237)
(4) [probeAttachedVolume()](https://github.com/kubernetes/kubernetes/blob/fc8bfe2d8929e11a898c4557f9323c482b5e8842/pkg/volume/cinder/cinder_util.go#L222)
(5) [PLEG healthcheck](https://github.com/kubernetes/kubernetes/blob/eb658d699ac074ef2a6f3808b13aacc6adfca786/pkg/kubelet/kubelet.go#L748)
(6) [PLEG implementation](https://github.com/kubernetes/kubernetes/blob/d196a4abbbf3f1ca458908abd42267b521a6faff/pkg/kubelet/pleg/generic.go#L133)

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: VmWare-integrated Openstack (ViO)
- OS (e.g. from /etc/os-release): PRETTY_NAME="CentOS Linux 7 (Core)"
- Kernel (e.g. `uname -a`): Linux os1pi013-kube-node02.novalocal 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: saltstack scripts.
- Others: docker-1.12.5-14.el7.centos

**Comment by edisonxiang** [comment]
Hey @kabakaev, I am willing to submit a PR to resolve this bug if you and the approvers like @dims allow it.

**Comment by dims** [comment]
@edisonxiang you don't need anyone's permission to file a PR. Go for it :)

**Comment by edisonxiang** [comment]
@dims Thanks dims. I will.
