### ISSUE TITLE
[apps/v1] Change DefaultGarbageCollectionPolicy for workload controllers

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#55027]
As part of the apps/v1 GA effort (https://github.com/kubernetes/features/issues/353) for v1.9, we'd like to consider changing the DefaultGarbageCollectionPolicy from `OrphanDependents` to `DeleteDependents` for Deployment, DaemonSet, ReplicaSet, and StatefulSet. This will make these objects consistent with the default behavior for all new objects. Clients that use the new GA version will no longer need to account for these objects being special.

For backward compatibility, the default policy will remain `OrphanDependents` if the `DELETE` request comes through one of the following legacy API versions:

* extensions/v1beta1
* apps/v1beta1
* apps/v1beta2

To accomplish this, we'll need to add a `genericapirequest.Context` argument to `DefaultGarbageCollectionPolicy()`, as is found on other methods in Strategy, and plumb it through from the caller. After that, the implementation will be similar to what we did for version-specific selector immutability (https://github.com/kubernetes/kubernetes/pull/50719).

cc @caesarxuchao @kow3ns @kubernetes/sig-apps-api-reviews 

- [x] Update code. (https://github.com/kubernetes/kubernetes/pull/55148)
- [ ] Update [docs](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy).

**Comment by liggitt** [comment]
+1

**Comment by enisoc** [comment]
/assign @kow3ns 
who is working on the docs change.
