### ISSUE TITLE
Kubelet.exe Crashes on Windows Server Core 

### ISSUE THREAD

**Issue by gkudra-msft** [kubernetes/kubernetes#55031]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kubelet.exe crashes on Windows Server Core. 

**What you expected to happen**:
Kubelet running and joining to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Build kubelet.exe from master and run it on a machine with Core (UI-less).

**Anything else we need to know?**:
There was a dependency introduced in PR #50396 on [this package](https://github.com/lxn/win/). This loads `OpenGL32.dll`, which isn't present on the UI-less Windows Core variant, thus causing a panic:

    panic: The specified module could not be found.

    goroutine 1 [running]:
    k8s.io/kubernetes/vendor/github.com/lxn/win.MustLoadLibrary(0x34a64bd, 0xc, 0xc)
            .../local/go/src/k8s.io/kubernetes/vendor/github.com/lxn/win/win.go:48 +0x73
    k8s.io/kubernetes/vendor/github.com/lxn/win.init.8()
            .../local/go/src/k8s.io/kubernetes/vendor/github.com/lxn/win/opengl32.go:117 +0x41
    k8s.io/kubernetes/vendor/github.com/lxn/win.init()
            <autogenerated>:1 +0x81
    k8s.io/kubernetes/pkg/kubelet/winstats.init()
            <autogenerated>:1 +0x77
    ...

Though the package is necessary, OpenGL is not. lxn/win#23 is open on the package to be Core-friendly, but it doesn't seem to be going anywhere.

**Environment**:
- Kubernetes version (use `kubectl version`): Built from #51063 directly.
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): Windows Server Standard Core 1709
- Kernel (e.g. `uname -a`): 16299.15.amd64fre.rs3_release.170928-1534

**Comment by martinivanov** [comment]
I've done some work on this [here](https://github.com/martinivanov/kubernetes/commit/c932cac1040abd1f4f89a0a915d0acdec62dd719). In general the parts required by kubernetes were copied to the project.

**Comment by andyzhangx** [comment]
@JiangtianLi FYI

**Comment by marono** [comment]
I've pulled from `master` and build `kubelet` and `kube-proxy` myself.
When running on Windows Server Core 1709 I'm now getting: 

`error: failed to run Kubelet: unable to read physical memory`

Am I missing a dependency of some sorts?

**Comment by andyzhangx** [comment]
I would suggest use https://github.com/Azure/acs-engine/releases/tag/v0.9.4 to deploy a windows 1709 based k8s cluster.

**Comment by marono** [comment]
Thanks @andyzhangx, will I be able to deploy ACS it on-premises? I stayed away from it as I thought it's only for Azure.

**Comment by andyzhangx** [comment]
@marono yes, acs-engine is only for azure, while you may take a reference for windows deployment scripts under: https://github.com/Azure/acs-engine/blob/master/parts/kuberneteswindowssetup.ps1

**Comment by JiangtianLi** [comment]
@marono How is your Windows Server Core 1709 deployed? Do you have a kernel32.dll in your [LoadLibrary search path](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx) besides system32?

**Comment by marono** [comment]
@JiangtianLi It's a clean deployment of the ISO in my MSDN subscription (haven't activated it though as I'm only trialing this stuff) on a VMWare fusion VM. 

OS version comes back as `10.0.16299.0` 

Haven't messed around with anything on it, really, just tried a couple versions of `kubelet` in the last couple days which means I've deployed `docker` latest (about which the kubelet complains that it's newer than the highest tested version). If you can indicate what sorts of information would be useful to debug this, I can send it over as it's just a test machine anyways.

In the meanwhile I'm going to refresh the VM just in case something that I've done caused a different version of `kernel32.dll` to be loaded onto it .

**Comment by marono** [comment]
Just retried it on a machine that's just been installed, haven't even deployed Docker to it and I get the same error. Is it supposed to only work in Datacenter Edition maybe ?

**Comment by JiangtianLi** [comment]
@marono Can you try `dumpbin /exports kernel32.dll|findstr GetPhysicallyInstalledSystemMemory` (on your local machine where you have dumpbin/Visual Studio installed and kernel32.dll is from Server Core %windir%\system32\) to see if kernel32.dll has GetPhysicallyInstalledSystemMemory exported? What is go version you used to build kubelet? What is the output of `reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v BuildLab` from Server Core?

To debug, can you move kubelet.exe to system32 and try?

Or you can write a toy C program using [GetPhysicallyInstalledSystemMemory](https://msdn.microsoft.com/en-us/library/windows/desktop/cc300158(v=vs.85).aspx), or go program using https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/winstats/perfcounter_nodestats.go#L35-L37 and https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/winstats/perfcounter_nodestats.go#L175-L182

**Comment by JiangtianLi** [comment]
@marono I build kubelet.exe from master HEAD and patched to Server Core 1709 deployed by ACS-Engine. GetPhysicallyInstalledSystemMemory worked fine. Did you have any finding? Also what is the go version you used to build kubelet.exe?

**Comment by marono** [comment]
Hey @JiangtianLi sorry for the delay, I was hoping to get all of that info yesterday, but it just didn't happen. Here's what I've got so far:
`go version`
```
go version go1.9.1 darwin/amd64
```

`dumpbin /exports kernel32.dll|findstr GetPhysicallyInstalledSystemMemory`
```
678  2A5 00011C80 GetPhysicallyInstalledSystemMemory
```

`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v BuildLab`
```
BuildLab    REG_SZ    16299.rs3_release.170928-1534
```

Will go ahead and create that test program you've pointed above ...

**Comment by JiangtianLi** [comment]
@marono I couldn't see what's wrong here. Can you try to move kubelet.exe to system32 directory and run from there? Also, is there any particular parameters you passed to kubelet.exe?

**Comment by marono** [comment]
Moved it and I get the same error. There's no parameters that I'm sending in, just copied the exe and executed it. Would you think it would help if I activated the OS?

**Comment by JiangtianLi** [comment]
So you just ran: `.\kubelet.exe`? Did you see the error from console?

**Comment by JiangtianLi** [comment]
@marono I am not sure if activating OS would help here. Might worth trying. What does `gwmi -class Win32_PhysicalMemory` show from your side?

**Comment by marono** [comment]
Yes, kubelet.exe has the following output:
```
C:\Users\Administrator>c:\Windows\system32\kubelet.exe
I1128 08:53:14.326505    1412 feature_gate.go:220] feature gates: &{{} map[]}
I1128 08:53:14.329451    1412 controller.go:114] kubelet config controller: starting controller
I1128 08:53:14.331497    1412 controller.go:118] kubelet config controller: validating combination of defaults and flags
W1128 08:53:14.353976    1412 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
I1128 08:53:14.355142    1412 server.go:182] Version: v1.10.0-alpha.0.584+ba09291ba785b0
I1128 08:53:14.356975    1412 feature_gate.go:220] feature gates: &{{} map[]}
I1128 08:53:14.356975    1412 plugins.go:101] No cloud provider specified.
W1128 08:53:14.356975    1412 server.go:328] standalone mode, no API client
error: failed to run Kubelet: unable to read physical memory
```

And `gwmi...`:
```
PS C:\Users\Administrator> gwmi -class Win32_Physicalmemory


__GENUS              : 2
__CLASS              : Win32_PhysicalMemory
__SUPERCLASS         : CIM_PhysicalMemory
__DYNASTY            : CIM_ManagedSystemElement
__RELPATH            : Win32_PhysicalMemory.Tag="Physical Memory 0"
__PROPERTY_COUNT     : 36
__DERIVATION         : {CIM_PhysicalMemory, CIM_Chip, CIM_PhysicalComponent, CIM_PhysicalElement...}
__SERVER             : KUBE-01-NODE-02
__NAMESPACE          : root\cimv2
__PATH               : \\KUBE-01-NODE-02\root\cimv2:Win32_PhysicalMemory.Tag="Physical Memory 0"
Attributes           : 0
BankLabel            : RAM slot #0
Capacity             : 4294967296
Caption              : Physical Memory
ConfiguredClockSpeed : 0
ConfiguredVoltage    :
CreationClassName    : Win32_PhysicalMemory
DataWidth            : 32
Description          : Physical Memory
DeviceLocator        : RAM slot #0
FormFactor           : 8
HotSwappable         :
InstallDate          :
InterleaveDataDepth  :
InterleavePosition   :
Manufacturer         :
MaxVoltage           :
MemoryType           : 2
MinVoltage           :
Model                :
Name                 : Physical Memory
OtherIdentifyingInfo :
PartNumber           :
PositionInRow        :
PoweredOn            :
Removable            :
Replaceable          :
SerialNumber         :
SKU                  :
SMBIOSMemoryType     : 3
Speed                :
Status               :
Tag                  : Physical Memory 0
TotalWidth           : 32
TypeDetail           : 512
Version              :
PSComputerName       : KUBE-01-NODE-02
```

**Comment by JiangtianLi** [comment]
@marono It isn't obvious to me why GetPhysicallyInstalledSystemMemory failed. Better to write a simple console application that LoadLibray and GetProcAddress and GetPhysicallyInstalledSystemMemory to see if there is any error. If so, use GetLastError to get error code.

**Comment by marono** [comment]
While working on my console app, I've deployed the same copy on a Hyper-V machine and I'm not getting the error. Most likely related to VMWare Fusion, I'll continue my investigation and post my findings here ...

**Comment by marono** [comment]
I can now confirm that on a VMware fusion host, `GetPhysicallyInstalledSystemMemory` returns error code `0x0d` (`The data is invalid.`), whereas on a Hyper-V host I get the expected result (amount of physical memory installed).

Here's my code, just in case you'll be wanting to eyeball it for mistakes:
 https://gist.github.com/marono/235bdedcf2cb2d123e4a6be168169255

**Comment by JiangtianLi** [comment]
@marono Good finding. Your code LGTM. I guess your VMware fusion host prevents reading from SMBIOS firmware table. If possible, could you help to try https://msdn.microsoft.com/en-us/library/windows/desktop/aa366589(v=vs.85).aspx on your VMware fusion host?

**Comment by marono** [comment]
Already done so, and I've got this change that enabled me to run `kubelet.exe` it in my scenario:

https://github.com/kubernetes/kubernetes/compare/master...marono:vmware-phys-memory-detection-fix?expand=1

Now, if you consider it's worth putting a PR, I'll do my best and go through the guidance on how to submit one ...

**Comment by JiangtianLi** [comment]
@marono Thanks for verifying. Your code looks mostly fine. Maybe you can refer to https://github.com/martinivanov/kubernetes/commit/c932cac1040abd1f4f89a0a915d0acdec62dd719 and remove use of endianness. Also if you want, I can submit a PR for you.

**Comment by marono** [comment]
@JiangtianLi have a look now, using structs ...
I'm going to let you know soon about the PR, I'd ideally like to do it myself as a 'get-to-know' exercise ...

**Comment by JiangtianLi** [comment]
@marono Okay, I'll let you do it and test on both VMware and HyperV machine. Also please add a few comment explain the total physical memory obtained from GlobalMemoryStatusEx and GetPhysicallyInstalledSystemMemory (https://msdn.microsoft.com/en-us/library/windows/desktop/cc300158(v=vs.85).aspx) and in parity with Linux's MemTotal from /proc/meminfo (used for Linux node). Thanks.

**Comment by JiangtianLi** [comment]
@marono Have you got time to work on it?

**Comment by PatrickLang** [comment]
Is there a new issue open for the VMware issue? I think it needs a separate tracking for a fix

**Comment by JiangtianLi** [comment]
@PatrickLang  @trondhindenes I have filed an issue https://github.com/kubernetes/kubernetes/issues/57110
@marono Seems you are blocked. I will fix it for you.

**Comment by marono** [comment]
Yes, please do, sorry for the lack of activity on this one, I was away for a bit...

**Comment by JiangtianLi** [comment]
@marono No worry. Thanks for reporting and helping me debug at the first place.

**Comment by beaudryj** [comment]
just a heads up this issue also bleads into ESX Hosted vms not just VMware fusion attempting @marono's build to see if it works on ESX

**Comment by JiangtianLi** [comment]
@beaudryj I have a PR here https://github.com/kubernetes/kubernetes/pull/57124.
