### ISSUE TITLE
Docker pull failing on `gcr.io/google_containers/` registry.

### ISSUE THREAD

**Issue by abrodersen** [kubernetes/kubernetes#55035]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`docker pull gcr.io/googe_containers/hyperkube:1.6.12` fails to download the image, giving the following error:
````
$ docker pull gcr.io/google_containers/hyperkube:1.6.12
Pulling repository gcr.io/google_containers/hyperkube
unauthorized: authentication required
````

**What you expected to happen**:
`docker pull` should have successfully downloaded the image.
**How to reproduce it (as minimally and precisely as possible)**:
Run `docker pull gcr.io/googe_containers/hyperkube:1.6.12` without any configured credentials.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.6.12`
- Cloud provider or hardware configuration: `libvirt + QEMU/KVM`
- OS (e.g. from /etc/os-release): 
````
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
````
- Kernel (e.g. `uname -a`): `Linux yggdresil 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Intel Core Processor (Broadwell)`
- Install tools: 
- Others:
````
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Oct 26 03:30:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Oct 26 03:30:45 2017
 OS/Arch:      linux/amd64
````

**Comment by justinsb** [comment]
There's a missing `v`

`docker pull gcr.io/google_containers/hyperkube:v1.6.12`
