### ISSUE TITLE
Kubernetes services fails with AWS cloud provider options

### ISSUE THREAD

**Issue by sudhakar-mnsr** [kubernetes/kubernetes#55048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I have created IAM policy, roles and attached them. I have given options --cloud-provider=aws and --cloud-config=/etc/aws/aws.config (in apiserver, controller-manager, kubelet)
> $ cat /etc/aws/aws.conf
> [Global]
> Zone = us-west-2a

The cluster is up and running when i remove --cloud-provider, --cloud-config options. 

**What you expected to happen**:
k8s services should be up and running even with cloud provider options. I dont see proper documentation for storage classes on AWS.
**How to reproduce it (as minimally and precisely as possible)**:
with kubernetes 1.7.2 start apiserver, controller-manager, kubelet with /etc/aws/aws.conf as mentioned above.

**Anything else we need to know?**:
If I restart the controller-manager it is up (only second time), but apiserver is not up even second time.
**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): SLES 12 SP2
- Kernel (e.g. `uname -a`): 4.4.21-69-default
- Install tools: Teradata proprietary tool (kubekit)
- Others:

**Comment by dims** [comment]
/close

please provide logs from apiserver, controller-manager, kubelet and we can re-open this bug.

Thanks,
Dims
