### ISSUE TITLE
Pod startup latency regression

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55060]
/kind bug

**What happened**:

In 5k node cluster tests pod startup latency has roughly doubled at all (50th, 90th, 99th, 100th) percentiles, apparently due to some change merged between Oct 16th and 20th. The following graph (for the ci-kubernetes-e2e-gce-scale-performance job) makes it obvious (note values are capped at 10s for readability):

![0jjh2pnsh7p](https://user-images.githubusercontent.com/489420/32377396-c4c39f36-c0a7-11e7-9f3f-19184b923c28.png)

The last run with good latency (3.2s@99%) was 49, on October 16th.
Since then it's been between 4.7s and ~5s at 99th %ile.
The [56th run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/56/) actually failed because the latency exceeded the threshold (5s). Since we're so close to the threshold, the test is now more flaky.

/cc @kubernetes/sig-scalability-bugs

**Comment by spiffxp** [comment]
/priority critical-urgent
/status approved-for-milestone
(curious if it'll let me do this without the issue being in milestone)

**Comment by spiffxp** [comment]
Can someone with repo write privileges add this to the v1.9 milestone?

**Comment by shyamjvs** [comment]
@porridge - Could you take a look into this? Also do we have a known commit range?

**Comment by porridge** [comment]
I can look at this, (I don't have the privileges to assign issues).

**Comment by shyamjvs** [comment]
/assign @porridge 
Thanks!

**Comment by shyamjvs** [comment]
You can comment with `/assign` to assign an issue to yourself.

**Comment by shyamjvs** [comment]
Seems like it changed b/w run-49 and run-52:

```
I1016 21:39:12.529] Oct 16 21:39:12.485: INFO: perc50: 1.843918852s, perc90: 2.54467047s, perc99: 3.265202677s
```

```
I1020 20:17:17.574] Oct 20 20:17:17.533: INFO: perc50: 3.344818382s, perc90: 4.06670982s, perc99: 4.709879947s
```

Diff - https://github.com/kubernetes/kubernetes/compare/77b83e446b4e65...ba66fcb63de9e9

**Comment by porridge** [comment]
FTR, lack of commit IDs in the testgrid headers filed as https://github.com/kubernetes/test-infra/issues/5357

**Comment by shyamjvs** [comment]
Also, looking at the components of pod startup latency, it seems the part which got slowed down is run-after-schedule latency:

```
I1016 21:39:12.500] Oct 16 21:39:12.482: INFO: perc50: 1s, perc90: 1s, perc99: 2s
```

```
I1020 20:17:17.547] Oct 20 20:17:17.531: INFO: perc50: 2s, perc90: 3s, perc99: 3s
```

My suspicion is some change around kubelet caused this.
cc @kubernetes/sig-node-bugs

**Comment by porridge** [comment]
I had a quick look at the diff. There is no smoking gun, but just judging by commit messages and `--stat`, the following sound like the ones worth looking at closer:
- 7cdbb6ae8f42e56f49d9ddd64e9e70869df3121f (bump cni vendor to v0.6.0)
- 786f460092f69d0128840fa0931992dbace94178 (kube-dns-anti-affinity: kube-dns never-co-located-in-the-same-node) **reverted** by 607c3d69670d624fef86ac21dd9f64ac16dde558
- e6540d422b22983b37380ed18ac337a4ef46acea (kube-dns-anti-affinity: Adjust to match different scheme)
- 5c026f6317e1351b069dc44b8870528b15802f3e (Upgrade to go1.9)

**Comment by porridge** [comment]
Next, I'm going to look at the pod startup latency data for smaller-scale tests to see whether the regression is also visible there.

**Comment by shyamjvs** [comment]
I just took a look at our 100-node CI [job](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce) and seems like the latency shot up across runs 7090 and 7091 (https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability?before=7099):

```
"data": {
        "Perc100": 2720.556802,
        "Perc50": 1909.607314,
        "Perc90": 2396.249513,
        "Perc99": 2712.457211
      },
```

```
"data": {
        "Perc100": 4945.584274,
        "Perc50": 3216.738616,
        "Perc90": 3986.762845,
        "Perc99": 4610.164308
      },
```

From the [diff](https://github.com/kubernetes/kubernetes/compare/88975e98d6f4a8...74cd0f0766b042), seems like it's the cni bump. Your guess was good :)

**Comment by porridge** [comment]
https://github.com/kubernetes/kubernetes/issues/54651 claims to be fixed by https://github.com/kubernetes/kubernetes/pull/54800 4 days ago, but we are still seeing elevated latency in the 100-node job running today's code.

**Comment by shyamjvs** [comment]
So indeed the bug was on kubelet side :)

**Comment by shyamjvs** [comment]
This has been fixed by @squeed 's PR above. Details here - https://github.com/kubernetes/kubernetes/issues/54651#issuecomment-343188666

**Comment by porridge** [comment]
FTR, this seems to have mostly recovered for the 5k nodes test too.
![tbi4xpy77zr](https://user-images.githubusercontent.com/489420/32726636-ec85b750-c879-11e7-832b-9351180bbca0.png)
