### ISSUE TITLE
imagePullPolicy: NotIfPresent + hash compare

### ISSUE THREAD

**Issue by nwest1** [kubernetes/kubernetes#55076]
/kind feature

**What happened**: 

**What you expected to happen**:
A new `imagePullPolicy` that would behave as `NotIfPresent`, but also compare the hash the tag points to of the underlying cached image.

The use case is to retain the optimization of `NotIfPresent` and also allow vanity tags (`v1`, `stable-1`) for non-breaking changes of an image.

An alternative would be adding some semantic versioning logic, but I think this would be more simple.

**Comment by mbohlool** [comment]
sig API machinery does not own the content of the API. I tagged sig node.

**Comment by justinsb** [comment]
How is this different from an ordinary image pull?  My belief is that an image pull resolves a name to a imageid, and then it only fetches if the imageid is not present.  So in the case of docker, it'll do a lookup of tag -> layer, and then will only fetch missing layers.

**Comment by nwest1** [comment]
Maybe that's my misunderstanding of how the image pull behaves. Browsing the code for a bit I could not find where it is examining hashes. As long as it's following what you describe, this isn't an issue and can be closed.
