### ISSUE TITLE
Proposal: IP addresses as a opaque counted resource

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#5507]
## IP addresses as a opaque counted resource

Currently Kubernetes scheduler is not aware of number of IP addresses available on a single node. We do have some assumptions about network masks, from which a number of available IPs can be inferred, but this is not general or configurable in any way. We want to create a simple counted resource published by kubelet and visible for scheduler, which will allow finer grained configurations to be used.
## Resources in Kubernetes

Resource validation in Kubernetes is performed as one of FitPredicates of Scheduler, namely ResourceFit predicate check. Available resources are computed by reading resources from NodeInfo, and subtracting resources of Pods currently bound to the given Node. The data comes (indirectly?) from etcd in a form of API Node > Spec > Capacity struct.

Capacity is a part of NodeStatus periodically updated by Kubelet in tryUpdateNodeStatus method (even though Capacity is a part of the NodeSpec). As of now, all Node capacity data is read from cAdvisor MachineInfo struct. During Node creation NodeController fills up Capacity in some way (either statically or get it from the cloud provider), but later on it’s overwritten by data provided by cAdvisor. IUUC Kubelet is the only entity which triggers modifications of Node entries after they are created. 
## IPs as resources

Introducing IP addresses as resources is straightforward: we need to add them to ResourceList/ResourceName and related places, and modify PodFitResources method in Scheduler. In current model it is assumed that we have one IP per Pod model, hence there’s no need of introducing additional scheduling requirements/usage info. In the future if we’d want to loosen this assumption changes to make will be pretty straightforward.

On top of those simple changes we need to decide how to keep the configuration. As it resides in NodeSpec, which is written by both Kubelet and NodeController it can be a part of any one of configurations (Node or Kubelet). If it were a part of Kubelet, then we’d need to wait for first “syncNodeStatus” call before setting it up. On the up side doing it in Kubelet will make the change of the IP number in runtime more robust (Kubelet is and will be overwriting Specs, so if anything else were to modify the value race condition would be possible).

**Comment by jlowdermilk** [comment]
@davidopp

**Comment by gmarek** [comment]
@tkulczynski

**Comment by eparis** [comment]
@mrunal @rajatchopra

**Comment by davidopp** [comment]
I discussed this with @erictune and @bgrant0607 and my feeling is that we should not have a separate resource for IP addresses; instead we should have a "max pods per host" (set on a per-host basis) with an upper bound == however many IP addresses are allocated per machine on the given provider. We need "max pods per host" anyway, and this way we could have one mechanism instead of two.

**Comment by gmarek** [comment]
Implementation wise it's just renaming of variables, as long as this is opaque resource if needed. I also agree that limiting number of pods by available IP addresses is more general.

The thing is that 'max pods per host' is more natural if we want to have just an opaque resource. IP addresses become useful only iff we plan to eventually give each Kubelet a collection of them for it to assign.

**Comment by rajatchopra** [comment]
Coming with blinkers on from #3350 and #5069, the networking plugins are going to be quite decoupled. There are already networking plugins that are thinking of multiple interfaces per pod. With that in mind, max_pods_per_host sounds like a decent please-all counter.
For any other needs, could we have a cluster wide object with annotations on it? So, any plugin can make use of any opaque object that it wants.

**Comment by gmarek** [comment]
Friendly ping

**Comment by thockin** [comment]
max pods makes sense to me, but I do think it would be nice if this lays the groundwork for arbitrary counted resources.

**Comment by gmarek** [comment]
Right, so you want to have generic "counted resource" thingy?

**Comment by thockin** [comment]
I think that makes sense for a number of things, "max pods" just being one.

**Comment by bgrant0607** [comment]
The resource specification used to represent both container limits and node capacity is already written as a generic counted resource thingy.

**Comment by gmarek** [comment]
Yup, that's what I used in related PR. I don't think anything more general or more specific is needed - it's easy to use, and allows exactly right amount of flexibility. Only thing that's not exactly right is the 'Unit' thing, as I believe that most use cases will use ordinary decimals.

**Comment by gmarek** [comment]
Obsolete.

**Comment by davidopp** [comment]
@gmarek I am not sure this is obsolete -- AFAIK it was never implemented.

**Comment by davidopp** [comment]
(Whether we do it as an opaque resource or as an integer resource is a separate issue.)

**Comment by aojea** [comment]
yep yep https://github.com/kubernetes/kubernetes/pull/115075

**Comment by thockin** [comment]
This idea was more like:

* Node says "I have 110 IPs".
* Some component adds 1 "ip" resource to each pod (except host network)
* Scheduler knows whether it can or cannot assign a new pod to a node by the "normal" resource counting.

Multi-network makes this harder, but also easier in that (some of) this info is being surfaced.

**Comment by aojea** [comment]
oh, so is a Pod IPs resource to be able to track them per node, I should have read at least the description 🙃

**Comment by thockin** [comment]
"resource" here is like "cpu" and "memory" not like "pods" and "services" :)

**Comment by aojea** [comment]
> "resource" here is like "cpu" and "memory" not like "pods" and "services" :)

so, this information comes from the networking/CNI plugin, however, the kubelet have zero visibility on the CNI, neither in its config, there is "no feedback loop between CNI and kubelet", maybe we should allow kubelet to interrogate the container runtime about the network config?

cc: @smarterclayton
