### ISSUE TITLE
kubectl get all does not include services

### ISSUE THREAD

**Issue by leon-gh** [kubernetes/kubernetes#55078]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Running **kubectl get all** displays most resources, but not services.

**What you expected to happen**:
I would expect that kubectl get all displays also services, since service is a resource.

**How to reproduce it (as minimally and precisely as possible)**:
shell$ **kubectl get services**
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
test-service    ClusterIP   100.71.255.214   <none>        5555/TCP   3d

shell$ **kubectl get all | grep test-service**
shell$

**Anything else we need to know?**:

**Environment**:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- OS: Debian GNU/Linux 8 (jessie)
- Kernel: Linux 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux

**Comment by huzhengchuan** [comment]
In my kubernetes cluster, kubectl get all can get services resource.

[root@go-g2tl7usxo6-0-2xpx3vddt3gt-kube-master-vsnphr6ujr65 escore]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2.36+4aaf39a5c0bc3d", GitCommit:"4aaf39a5c0bc3d3c0523c383316a461e6fbb12ec", GitTreeState:"clean", BuildDate:"2017-11-02T02:02:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2.36+4aaf39a5c0bc3d", GitCommit:"4aaf39a5c0bc3d3c0523c383316a461e6fbb12ec", GitTreeState:"clean", BuildDate:"2017-11-02T02:02:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

[root@go-g2tl7usxo6-0-2xpx3vddt3gt-kube-master-vsnphr6ujr65 escore]# kubectl get all -n kube-system | grep svc

svc/application             NodePort    10.254.241.37    <none>        80:30001/TCP                                 50d
svc/default-http-backend    ClusterIP   10.254.226.70    <none>        80/TCP                                       50d
svc/elasticsearch-logging   NodePort    10.254.108.251   <none>        9200:30002/TCP                               50d
svc/heapster                NodePort    10.254.35.111    <none>        80:30005/TCP                                 50d
svc/kibana-logging          NodePort    10.254.194.71    <none>        5601:30003/TCP                               50d
svc/kube-dns                ClusterIP   10.254.200.200   <none>        53/UDP,53/TCP                                50d

**Comment by spzala** [comment]
@leon-gh I could not recreate the issue as well with minikube or v1.9 alpha. Can you just run ```kubectl get all``` and see what's the output of it. 

```
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1288+07be0a057a7db3-dirty", GitCommit:"07be0a057a7db33362ec69f02b25f301be472d45", GitTreeState:"dirty", BuildDate:"2017-10-31T14:00:50Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1287+79d2f4f41c31d0-dirty", GitCommit:"79d2f4f41c31d0445e6b2932c6adcd8aebe7a727", GitTreeState:"dirty", BuildDate:"2017-10-18T02:50:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
# cluster/kubectl.sh get all
```
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
svc/kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   10d
```
# cluster/kubectl.sh get all | grep kubernetes
svc/kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   10d

**Comment by leon-gh** [comment]
Seems like it's related to the client/server being different in minor versions or something.
I think the issue can be closed.

kubectl that works (Ubuntu 14.04.3 trusty): (Note 1.7 both client/server)
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

kubectl that does not work (Debian GNU/Linux 8.9 (jessie)) (Note 1.8 client and server is 1.7)
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by spzala** [comment]
@leon-gh thanks for the quick update!! I agree with you, it's safe to close the issue. Can you please close it? Thanks!
