### ISSUE TITLE
separators for finalizer name and initializer name are different

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#55082]
Finalizer name requires "/" to separate segments and at least two segments.
Initializer name requires "." to separate segments and at least three segments ([code](https://github.com/kubernetes/kubernetes/blob/78ada62c3086f3d2e743b6e7cc696e390a619585/pkg/apis/admissionregistration/validation/validation.go#L41)).

We should make the requirement consistent. I favor the the initializer naming style.

/sig api-machinery

**Comment by resouer** [comment]
@caesarxuchao Just curious, is it clear why do we introduced a totally different name pattern when implementing `Finalizer`?

**Comment by lavalamp** [comment]
Finalizers were written first, actually.

**Comment by mlmhl** [comment]
Is this still required and could I work on it? I have a question before starting the job: Is this change compatible with the old version? As user can set a finalizer manually, and if we modified the separators, user can't submit a object with the old style finalizers.

**Comment by sch00lb0y** [comment]
I'll take this
