### ISSUE TITLE
Built in support for dedicated nodes with extended compute resources (auto toleration)

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#55080]
A typical user managing clusters with extended compute resources will want to reserve those resources for pods that require those resources. For example, a node with one or GPUs or FPGAs or special NICs will most likely be reserved for pods that need those resources. Essentially, such nodes will be treated as "dedicated" nodes. 
Taints is the kubernetes API to express the notion of dedicated nodes.
Tainting nodes with extended compute resources is even more important in the case of autoscaled clusters where a cluster autoscaler may spin up nodes with extended resources which (node) can then be consumed by pods that do not require the extended resource. Given that many of the extended resources are typically more expensive that the built-in ones like CPU, Memory and Storage, it is useful to Taint such nodes by default in general.
Tainting for extended resources can happen via device plugins or via Cluster lifecycle control plane depending on the environment.

Taints come with a problem though. The taints have to be standardized for k8s workloads to be portable. This issue is proposing the following solution to deal with this issue:
1. Use the extended resource name as the name of the Taint by default. For example, in the case of Nvidia GPUs the name of the taint expected will be `nvidia.com/gpu` and the effect is `NoSchedule`. Applying taints to nodes is still out of scope for core k8s since the extended resource control plane is out of tree.
2. Have the API server apply tolerations for pods that use extended resources. The default toleration will be for a name that matches the extended resource name and effect `NoSchedule`. API server is aware of first class vs extended resources already.

- Having additional tolerations for taints that do not exist will not cause any functional issues
- This solution will work generically for all extended resources out of box

Thanks to @lavalamp for this idea.

@derekwaynecarr @thockin @davidopp @smarterclayton @ConnorDoyle @bsalamat Any opinions or suggestions?

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-scalability-feature-requests 

This feature is part of https://github.com/kubernetes/features/issues/192

**Comment by davidopp** [comment]
> Tainting for extended resources can happen via device plugins or via Cluster lifecycle control plane depending on the environment.

I assume "cluster lifecycle control plane" is the only option if you want to avoid race conditions? (kubelet is ready before taint is created) Or would the device plugin be able to create a taint before the node goes ready?

Anyway, your proposal sounds reasonable (and I can't think of any other way to do it). As an aside, you can use a PreferNoSchedule if you don't want to completely prohibit pods that don't use the resource from running on the node.

**Comment by liggitt** [comment]
> it is useful to Taint such nodes by default in general.

 Wouldn't that require "perfect fit" tolerations for nodes  with more than one custom resource?

David, how are "prefer no schedule" taints  weighted by the scheduler relative to other scheduler priorities?

**Comment by ConnorDoyle** [comment]
>> it is useful to Taint such nodes by default in general.

> Wouldn't that require "perfect fit" tolerations for nodes with more than one custom resource?

Did you consider a single taint key for all nodes with one or more extended resources?

**Comment by jiayingz** [comment]
cc @jiayingz @mindprince

**Comment by davidopp** [comment]
I'm not sure what the "perfect fit" comment meant, or exactly what Connor was suggesting as an alternative.

Maybe we should clarify what the requirements are?

We have a cluster with two extended resources A and B. Some nodes have A (call those "A-type nodes"), some nodes have B (call those "B-type nodes"), some nodes have both (call those "AB-type nodes"), and some nodes have neither (call those "X-type nodes"). 

Without taints, the following would happen
Pods requests neither A nor B -> can schedule onto any node
Pod requests both A and B -> can schedule only onto AB-type nodes
Pod requests only A -> can schedule onto A-type and AB-type noes
Pod requests only B -> can schedule onto B-type and AB-type nodes

IIUC we want to use taints to add the further restrictions
* Pods that request neither A nor B cannot schedule onto A-type, B-type, or AB-type nodes
* Pods that request only A cannot schedule onto B-type nodes [do we also want to prohibit AB-type nodes?]
* Pods that request only B cannot schedule onto A-type nodes [do we also want to prohibit AB-type nodes?]

**Comment by liggitt** [comment]
> I'm not sure what the "perfect fit" comment meant, or exactly what Connor was suggesting as an alternative.

> do we also want to prohibit AB-type nodes?

That. If your only extended-resource node has both A and B resources, auto-adding an A and B taint such that an A-requiring (and even auto-A-taint-tolerating) pod would be unschedulable seems unexpected.

Making the auto-added taints PreferNoSchedule instead might make that more reasonable. Those taints could be elevated to NoSchedule if a "perfect fit" (only schedule pods that require all the extended resources the node has) is desired.

**Comment by davidopp** [comment]
> That. 

Does "that" mean yes or no?

**Comment by bsalamat** [comment]
I have several of questions/comments:
1. Wild-card tolerations could still cause trouble for users. Today, a toleration with empty key and empty effect tolerates all taints.
2. A similar problem may happen in shared clusters, but you cannot except all users to be well-behaving and cooperative. So, they may add special-resource tolerations to their pods.
3. Another possible solution is to extend the "extended resource" API so that and admin can mark some of these resources as rare. Scheduler can have a priority function to prefer nodes that don't have such resources over the ones with such resources.

**Comment by davidopp** [comment]
> Wild-card tolerations could still cause trouble for users. Today, a toleration with empty key and empty effect tolerates all taints.

Can you explain what you mean by "cause trouble"? I understand the general issue with security that you mentioned in your next point, but what problem do wildcard tolerations by themselves cause?

> A similar problem may happen in shared clusters, but you cannot except all users to be well-behaving and cooperative. So, they may add special-resource tolerations to their pods.

It's true today but can easily be fixed, see https://github.com/kubernetes/kubernetes/issues/48041#issuecomment-323266418

> Another possible solution is to extend the "extended resource" API so that and admin can mark some of these resources as rare. Scheduler can have a priority function to prefer nodes that don't have such resources over the ones with such resources.

PreferNoSchedule taint kinda does this; I think we should see if we can do this using existing taint techniques first, but if not then what you suggested might be reasonable.

**Comment by liggitt** [comment]
Prohibiting an A-requesting pod from running on an AB node is what I was calling requiring a "perfect fit" (since the node satisfied the pod's requests, but because it had additional capabilities, would reject the pod).

It's useful to be able to do that with taints, but making that happen automatically to the point of refusing to schedule the pod seemed weird

**Comment by davidopp** [comment]
Actually, what I wrote in the previous comment about security doesn't fully solve the security problem. It allows you to restrict which users can use the special devices, but can't prevent a user who is authorized to use the device when their pod requests the resource, from adding the toleration to a pod that doesn't request the resource. Whether this is worth securing against, I'm not sure.

**Comment by bsalamat** [comment]
> Can you explain what you mean by "cause trouble"? I understand the general issue with security that you mentioned in your next point, but what problem do wildcard tolerations by themselves cause?

The security issue is the main problem here, but a less important issue exists as well. Even in a single user cluster, if the user wants to create pods with wildcard toleration for any reason, such as HA, special config, special type of workloads, etc., those pods may land on nodes with rare resources and cause a similar problem.

**Comment by RenaudWasTaken** [comment]
> IIUC we want to use taints to add the further restrictions
> 1. Pods that request neither A nor B cannot schedule onto A-type, B-type, or AB-type nodes
> 2. Pods that request only A cannot schedule onto B-type nodes [do we also want to prohibit AB-type nodes?]
> 3. Pods that request only B cannot schedule onto A-type nodes [do we also want to prohibit AB-type nodes?]

@davidopp for 2 and 3 this we don't need taints to do that, it is already supported by the scheduler through extended resources. i.e:
1. Pods that request only A cannot be scheduled on B-type nodes as they don't advertise resource A.
2. Pods that request only B cannot be scheduled on A-type nodes as they don't advertise resource B.

I think there is one clear requirement and two where we are unsure:
1. Pods that request neither A nor B cannot schedule onto A-type, B-type, or AB-type nodes
2. Pods that request only A [do we want to prohibit them on AB-type nodes?]
2. Pods that request only B [do we want to prohibit them on AB-type nodes?]

In terms of real world use case I'm guessing that the following is going to happen most of the time:
- A is an accelerator: FPGA, NVIDIA GPU, ...
- B is a high performance NIC: InfiniBand, ...

This mostly leads to me think that we might want to require a perfect fit. i.e prohibiting an A-requesting 
(or B-requesting) pods from running on an AB node.

**Comment by davidopp** [comment]
Sorry @RenaudWasTaken, you're correct.

Thinking about this more, I might just be echoing what @liggitt was saying, but it seems that  there are two reasonable policies (cluster admin chooses one for the whole cluster, or maybe for non-intersecting subsets of extended resources):

1) if you want to require perfect fit, then use NoSchedule taints in the manner originally proposed in this issue (one NoSchedule taint key per extended resource present on the node, and automatically add toleration for each extended resource requested in a pod)

2) If you don't want to require perfect fit, then use PreferNoSchedule taint. One PreferNoSchedule taint key per extended resource present on the node, and automatically add toleration for each extended resource requested in a pod.

I don't think it makes sense to use NoSchedule taint if you don't want to require perfect fit -- if your high-level policy is that it's fine to put pods that request only A, onto AB-type nodes, then you really don't have a policy of blocking pods that don't request B from running on nodes that have B.

To the question about how PreferNoSchedule taints are weighted, it's thrown into the mix with an equal weight along with everything else, which is probably less than ideal. We've never spent any time tuning the various priority function weighting factors (at least in upstream; it's quite possible people have done so locally in their own deployments). I think we're happy to take suggestions for different weights than we use today.

Regarding @bsalamat point on security, I guess we would have the admission controller that adds the tolerations for extended resources, reject pods that have a toleration for a resource they don't request. (Or, it would clear all tolerations for extended resources that the pod doesn't request before admitting the pod.)

**Comment by bsalamat** [comment]
> I don't think it makes sense to use NoSchedule taint if you don't want to require perfect fit -- if your high-level policy is that it's fine to put pods that request only A, onto AB-type nodes, then you really don't have a policy of blocking pods that don't request B from running on nodes that have B.

+1. I also think that NoSchedule taint is too restrictive and may clash with priority and surprise users. It is almost always undesirable if a system/production critical pod is not scheduled due to the special resource taint. Similarly, I believe in almost all scenarios users want higher priority pods to take precedence over lower priority pods. When a cluster is under resource pressure, those higher priority pods should still preempt lower priority pods and be scheduled on nodes with special resources even when they don't need the special resources.

> To the question about how PreferNoSchedule taints are weighted, it's thrown into the mix with an equal weight along with everything else, which is probably less than ideal. We've never spent any time tuning the various priority function weighting factors (at least in upstream; it's quite possible people have done so locally in their own deployments). I think we're happy to take suggestions for different weights than we use today.

I agree. Finding the right weights needs some research and experimentation.

> Regarding @bsalamat point on security, I guess we would have the admission controller that adds the tolerations for extended resources, reject pods that have a toleration for a resource they don't request. (Or, it would clear all tolerations for extended resources that the pod doesn't request before admitting the pod.)

This may not always work, especially if we decide to go with NoSchedule taint (as opposed to PreferNoSchedule), users probably want to add corresponding tolerations for rare resources to their system daemons and critical pods to ensure that they always schedule despite the fact that these pods may not need the rare resources. Automatic removal of the tolerations (or even rejecting such configs) would remove all of the options to ensure these pods will be scheduled when cluster is under resource pressure.

**Comment by davidopp** [comment]
> This may not always work, especially if we decide to go with NoSchedule taint (as opposed to PreferNoSchedule), users probably want to add corresponding tolerations for rare resources to their system daemons and critical pods to ensure that they always schedule despite the fact that these pods may not need the rare resources. Automatic removal of the tolerations (or even rejecting such configs) would remove all of the options to ensure these pods will be scheduled when cluster is under resource pressure.

That's a good point. We could make the admission controller configurable to always allow pods in certain namespaces (e.g. kube-system) and/or from certain users.

**Comment by vishh** [comment]
@liggitt @davidopp @bsalamat
Thanks for the awesome analysis. There are several interesting scenarios covered in this issue.
It's useful to think of the practicality of these use cases before deciding on an acceptable solution.

One thing to keep in mind is that k8s is **not requiring** placing Taints on nodes exposing extended resources. It is totally optional and left to the cluster deployment. For example a cluster built only with special nodes with extended resources may want to permit all pods successfully admitted to the cluster to run on any node. This is a realistic scenario today!

> Wild-card tolerations could still cause trouble for users. Today, a toleration with empty key and empty effect tolerates all taints.

The proposal is not to add wildcard tolerations. Instead have one to one mapping between extended resources and tolerations. The security aspect around which users can request tolerations with empty key is a tangential problem which may could be solved by tying to a namespace(s). 

> Scheduler can have a priority function to prefer nodes that don't have such resources over the ones with such resources.

Scheduler preference will not meet the autoscaling use case I described where in most public clouds a user will not expect to run a regular pods on nodes with special resources for cost reasons.

Now on requiring `perfect fit` vs `partial fit`, we have concrete use cases for perfect fit today. Realistically speaking, nodes with special resources are typically custom built to run a specific type of workload. As a project, we can recommend one of the following:
1. Not combining unrelated resources on nodes expected to be treated as dedicated nodes. 
2. Not place a taint on nodes exposing multiple unrelated extended resources. 
3. Expose a dummy extended resource which when requested will allow to run a set of nodes with multiple real extended resource (assuming the taint is based on the dummy extended resource)

> users probably want to add corresponding tolerations for rare resources to their system daemons and critical pods to ensure that they always schedule despite the fact that these pods may not need the rare resources

Critical (or high priority) regular or system pods that are expected to run on all nodes, like kube-proxy, node problem detector, etc., may end up requiring a wild card toleration. Applying such a toleration to critical system pods was another issue I was going to bring up, but it is not necessarily related to this issue though. For now, given that such pods are carefully curated, we can add tolerations manually. 

> I assume "cluster lifecycle control plane" is the only option if you want to avoid race conditions

That's true. Unless (or until) kubelet lifecycle phases takes device plugins into account, the race condition will persist. If the scheduler were to ignore any node where expected device plugins weren't registered yet, then this tainting race condition could be tackled via extensions. 

Now as a next step, would it be acceptable to introduce an admission controller that applies `NoSchedule` toleration with key as extended resources requested by a pod (`perfect fit`)?
We can consider extending it to `partial fit` and/or namespace specific wildcards in the future. 
Any objections @liggitt @davidopp @bsalamat?

**Comment by bsalamat** [comment]
> Now as a next step, would it be acceptable to introduce an admission controller that applies NoSchedule toleration with key as extended resources requested by a pod (perfect fit)?
We can consider extending it to partial fit and/or namespace specific wildcards in the future.
Any objections @liggitt @davidopp @bsalamat?

It is acceptable in my opinion, but please ensure that your solution can be easily extended to support partial fit and please plan to add the support in a near future release (perhaps 1.10?).

**Comment by liggitt** [comment]
Since external admission is scheduled for beta in 1.9, it would be ideal to start moving in the direction of making these external admission plugins.

**Comment by liggitt** [comment]
Also, ordering of admission plugins auto-adding/removing/validating tolerations is going to get really complex (especially if allowed tolerations start to become an intersection of per-namespace policy, cluster-wide policy, and dynamic pod-dependent policy)

Considering the ones we have today that add/validate tolerations and making sure the use cases they address individually can actually be handled when working in concert (along with additional plugins/use cases) is really important.

**Comment by vishh** [comment]
@bsalamat 
There really isn't an use case yet for `partial fit`. I do not mind adding support for it, but why carry a functionality (and code) without a clear use case? I suspect when we need `partial fit` we may need to introduce additional policy for when to apply partial vs perfect fit. I propose we refer on it.

@liggitt 
This admission controller would act on all pod objects. By external admission controllers I assume you meant webhooks. I'm concerned with placing an external process (or pod) in the main path for literally every k8s cluster that will run in public clouds (assuming most public clouds will support GPUs with autoscaling for example). Stabilizing such an external controller is a lot work compared to the functionality introduced by the admission controller (the logic introduced is pretty simple).
I'd expect it to take a couple of releases for streamlining and productionizing deployments and management of external webhooks. I'd like to avoid waiting for that future given that this feature will help k8s users save money today. WDYT? 
Are existing built-in admission controllers planned to be moved to webhooks in the future?

> Also, ordering of admission plugins auto-adding/removing/validating tolerations is going to get really complex (especially if allowed tolerations start to become an intersection of per-namespace policy, cluster-wide policy, and dynamic pod-dependent policy)

Yeah. The current proposal isn't as sophisticated as what we have discussed in this issue. If a pod has an extended resource `foo` without a toleration that will let it run on nodes with resource `foo` add a toleration for `NoSchedule` effect and taint key `foo`.
If/when we consider adding namespace level defaulting for critical pods, it might make sense to extend the same controller.
If there is any more complex policy that is not applicable to all users, it might make sense to keep them out of tree via webhooks. 

> Considering the ones we have today that add/validate tolerations and making sure the use cases they address individually can actually be handled when working in concert (along with additional plugins/use cases) is really important.

Yeah totally. What controllers add tolerations today in upstream? 
My mental model is to perform defaulting (or addition which is this proposal) prior to validation. Does that make sense?

**Comment by davidopp** [comment]
>  What controllers add tolerations today in upstream?

https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/admission/defaulttolerationseconds
https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/admission/podtolerationrestriction

IIRC only the first one is enabled by default in kube-up.sh, but I believe OpenShift uses the second one.

**Comment by liggitt** [comment]
> I'm concerned with placing an external process (or pod) in the main path for literally every k8s cluster that will run in public clouds (assuming most public clouds will support GPUs with autoscaling for example). Stabilizing such an external controller is a lot work compared to the functionality introduced by the admission controller (the logic introduced is pretty simple).

My main goal is for the core to not become overly opinionated on application of generic mechanisms like taints/tolerations and labels/selectors. Auto-adding taints to nodes based on declared resources, and auto-adding tolerations to pods based on requested resources is a clever and useful application of those mechanisms, but one that seems reasonable to layer on (via a controller or admission plugin). The more variants in valid use cases, the less certain I am that the implementation belongs in core. Even if this wasn't accomplished via admission for 1.9, it seems like it could be done with a controller via the normal API (taints and tolerations can both be added after creation).

I also question the statement "The taints have to be standardized for k8s workloads to be portable."

We should work to accomplish the goal of reserving extended resource nodes for pods that need them, without requiring workload authors to be aware of a taint/toleration scheme. Otherwise, we're encouraging workload authors to add speculative tolerations to their pods (e.g. "I don't know if this cluster is using extended resource taints, but just in case they are, I'm going to add some tolerations to my deployment/rc/job", etc.), which also hurts portability.

**Comment by vishh** [comment]
>  Even if this wasn't accomplished via admission for 1.9, it seems like it could be done with a controller via the normal API (taints and tolerations can both be added after creation).

I wasn't aware of the fact that altering tolerations is possible post admission. Let me think through this scenario a bit more.

> I also question the statement "The taints have to be standardized for k8s workloads to be portable."

The goal is to help with portability and not hinder it. Portability is made possible by not requiring users to add tolerations. Instead of each cluster admin having to define, develop and stabilize a controller for this mechanism, I felt it makes sense to provide a standardized solution in addition to policy. Given that the policy is opt-in, it is not imposed on all cluster admins either.

**Comment by derekwaynecarr** [comment]
I think having a controller that taints nodes with extended resources makes sense.  Having that controller also apply tolerations to pods with extended resources also makes sense.  Like @vishh I think many users would want to have high-cost pods run on high-cost nodes, and would prefer to not let low-cost pods on high-cost nodes.  An add-on like the referenced controller would make sense in many deployments.

**Comment by vishh** [comment]
@derekwaynecarr adding taints via a controller is a bit racy for reasons discussed earlier. Taint may be added after a low-cost pod gets scheduled on a dedicated node. If kubelet implements evictions based on taints, then maybe we could set NoScheduleNoExecute effect which might help with this. 
Relying on cluster control plane or defining additional lifecycle hooks in the node lifecycle will help here.

By controller did you mean as part of admission or post admission?

**Comment by lavalamp** [comment]
> I also question the statement "The taints have to be standardized for k8s workloads to be portable."

I think the thing that needs to be standardized is the taint/toleration name <-> custom resource name relationship.

Auto-adding the toleration to a pod based on the resource seems 100% harmless to everyone not using custom resources, and very likely to be useful to those using them. Namespacing the toleration/taint (if possible) should make it very unlikely to interfere with anything that has been customized in the cluster. Therefore I don't object to doing it in OSS (prepare create or defaulting?). I also don't object to doing it as a webhook / initializer. I suggested the former as it is lower risk for @vishh's timeline.

However--I really think we should leave it up to the system administrator (and/or cloud provider) whether or not to taint the nodes, and whether it should be preference or mandatory. Doing that automatically in OSS seems as likely to hurt as help. Only people / things that understand the custom resource know if it is actually expensive or not.

**Comment by liggitt** [comment]
> Auto-adding the toleration to a pod based on the resource seems 100% harmless to everyone not using custom resources

Not for systems restricting allowed tolerations because taints are used to partition clusters.

**Comment by vishh** [comment]
> Not for systems restricting allowed tolerations because taints are used to partition clusters.

Such `special` systems can turn off the proposed admission controller right?

**Comment by davidopp** [comment]
Seems harmless if the toleration admission controller and whatever adds the taints are enabled by command-line flag as the discretion of the cluster deployment script/tool? So some platforms could do it and others could choose not to. 

Personally I don't really object to doing it as a built-in admission controller... We already have some in there that most people don't use (not that this is a great argument in general, but given that the 1.9 deadline is so close and we don't really have any other admission control mechanisms as a stable option yet, it doesn't seem unreasonable to me...

**Comment by liggitt** [comment]
> Seems harmless if the toleration admission controller and whatever adds the taints are enabled by command-line flag as the discretion of the cluster deployment script/tool? 

tainting out of tree seems reasonable to me

> Personally I don't really object to doing it as a built-in admission controller... We already have some in there that most people don't use (not that this is a great argument in general, but given that the 1.9 deadline is so close and we don't really have any other admission control mechanisms as a stable option yet

Adding tolerations can be done by a regular controller, doing it in admission is just an optimization. I'd prefer to see the toleration-adding done out of tree, since that is currently possible, but I won't block on it.

**Comment by davidopp** [comment]
Sounds like @liggitt is OK with this now, so I'm going to mark this as "approved for milestone" (though I'd love to know exactly what that means -- is it documented anywhere?).

**Comment by MaciekPytel** [comment]
For future reference, using `PreferNoSchedule` for `partial fit` discussed above will not work too well with autoscaling, as autoscaler only calculates scheduler predicates, not priorities. `perfect fit` with `NoSchedule` taints (which AFAIU is what we're going with anyway for now) should work fine.

**Comment by liggitt** [comment]
> perfect fit with NoSchedule taints (which AFAIU is what we're going with anyway for now)

if I understood correctly, we're only discussing implementing the toleration-adding in an admission plugin, and letting taints be added via existing methods on the discretion of the deployer

**Comment by tengqm** [comment]
My gut feeling is that the proposal of using "taint/toleration" for extended resources is somehow leading us astray. It is a dangerous move. I can fully apprehend the endeavor to keep the core simple, rock solid. I can totally understand the wish to reuse/extend an existing tool to new use cases. However, we could still be wrong.

From a user's viewpoint, the requirement is simple. e.g.: My workload W must run on a node with 1 GPU. The proposal is trying to translate to "Pod P can tolerate a node polluted by 1 GPU", instead of "Pod P *must* be scheduled to a node equipped with 1 GPU". The semantics of the translated version is weird. If you take the discussion of "rescheduler" vs "descheduler" into this picture, you will realize how awkward a solution it is when we are trying to solve a "scheduling" problem using an idea that "deschedule" workloads.

Even if we have successfully educated our users so that they get used to it. There are other intricate problems which the "taint/toleration" proposal cannot address. The extended resources we are trying to support have more variants than the node allocatables today. We are not yet doing a perfect job in scheduling CPUs and memory, for example, we don't differentiate CPU cores from each other so we are wasting LLC caches blindly. We don't support NUMA yet (IIRC). We are only *counting* CPU cores instead of modeling them as a resource with characteristics. This may be okay with CPU, but not with GPU, FPGA, IBs, NVMes etc. The platform has to report exactly the model of the card for the program to decide whether a bit-file can be used. Representing all those models as different taint keys for Pods to tolerate? I don't see a future of it. Over-simplification can serve a demo's purpose but not real-life use cases.

However, if we take a step back and rethink the problem we want to solve. We are already trying to have device plugins advertise new resource types on a node. These info are exposed from a node view. We already support several ways to extend the schedulers i.e. scheduler extender, multi-scheduler, etc. We can have a rich collection of scheduler predicates and/or priortizers. Can we brainstorm on better schedulers and leave "taints" as is, i.e treat "taints" as constraints, something you want to *avoid* instead of something you *want badly*?

If we decide now to use "taints/toleration" as a workaround (sorry, that is my feeling), I'm afraid we are just postponing some more general problems to be solve into the future. Meanwhile we are introducing new problems such as how to coordinate the "descheduling" logic with the new "scheduling" policies. We will be presenting extended resources as both "resources" and "taints", an ill-formed model that is gonna trap us for a long time.

**Comment by davidopp** [comment]
> Can we brainstorm on better schedulers and leave "taints" as is, i.e treat "taints" as constraints, something you want to avoid instead of something you want badly?

I think that's what we're doing here.

If a pod needs GPU, then it requests the GPU extended resource, and can only be scheduled onto a node with GPU. (You can call this "want badly" in your terminology).

The taint is purely being used to keep pods that don't require GPU off of GPU nodes ("want to avoid" in your terminology).

An alternative to taints would be to build special logic into the scheduler (and I guess also descheduler) to automatically detect rare resource(s) and avoid putting pods on those nodes unless they require the rare resource(s). This is a reasonable thing to do IMO, but more work than using taints. It might be a good next step in the future.

**Comment by derekwaynecarr** [comment]
as long as it’s optional, what’s described sgtm .  it seems like a useful pattern many users would explore on their own to ensure high cost workloads are steered to high cost nodes.

**Comment by mindprince** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/55839
/close
