### ISSUE TITLE
SharedInformerFactory needs CoreV1() and similar methods

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#55085]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The Clientset has deprecated the non versioned interfaces such as Core() (staging/src/k8s.io/client-go/kubernetes/clientset.go) in preference to versioned interfaces such as CoreV1(). However the SharedInformerFactory has not yet (staging/src/k8s.io/client-go/informers/factory.go) deprecated these methods in preference to versioned methods. 

**What you expected to happen**:
We should keep these consistent.

**Comment by liggitt** [comment]
I don't think so. Informers already require specifying a version, which is what we care about: `Core().V1()`

The deprecated clientset methods implicitly gave you a version without it being specified (`Core()` was the same as `CoreV1()`), but could change if a new version was introduced
