### ISSUE TITLE
upgrade to v1.7.8 causes duplicate fluentd-gcp daemonsets on GKE

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#55099]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

upgrade to v1.7.8 causes duplicate fluentd-gcp daemonsets on GKE
```
$ kubectl -n kube-system get ds
NAME                       DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                                             AGE
calico-node                0         0         0         0            0           projectcalico.org/ds-ready=true                           30d
fluentd-gcp-v2.0           183       183       116       183          116         beta.kubernetes.io/fluentd-ds-ready=true                  200d
fluentd-gcp-v2.0.9         183       133       40        133          40          beta.kubernetes.io/fluentd-ds-ready=true                  1d
```

**What you expected to happen**:

There should be only one fluentd-gcp daemonset.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade any pre-v1.7.8 cluster on GKE to v1.7.8

**Anything else we need to know?**:

Seems to be related to https://github.com/kubernetes/kubernetes/pull/52565

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools: GKE
- Others:

**Comment by crassirostris** [comment]
Thanks for reporting

/cc @janetkuo @kawych

**Comment by crassirostris** [comment]
I've just checked and it works for me: after an update, at first both DS exist then the old one gets deleted. @janetkuo do you have any ideas as to what's going on with DaemonSet upgrade on master upgrade?

@guoshimin Meanwhile, try deleting the old DaemonSet

**Comment by guoshimin** [comment]
Interesting. Our other cluster didn't have this problem. After deleting the old DS everything seems to be working fine. I'll close the issue.
