### ISSUE TITLE
Makefile:396: recipe for target 'cross' failed

### ISSUE THREAD

**Issue by sykpour** [kubernetes/kubernetes#55100]
Even I have enough memory,  I install kubernetes from 1.7.0 source still error. error info as follow:

[kubernetes-1.7.0]# sudo make quick-release
+++ [1104 13:17:31] Verifying Prerequisites....
+++ [1104 13:17:31] Building Docker image kube-build:build-ac3d17de29-5-v1.8.3-1
+++ [1104 13:17:43] Syncing sources to container
+++ [1104 13:17:45] Running build command...
+++ [1104 13:17:56] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 13:17:56] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 13:17:57] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
    vendor/k8s.io/apiextensions-apiserver
    plugin/cmd/kube-scheduler
pkg/credentialprovider/rancher/rancher_registry_credentials.go:24:2: open /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/rancher/go-rancher/client/generated_log_config.go: file name too long
vendor/github.com/opencontainers/runc/libcontainer/capabilities_linux.go:10:2: open /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/syndtr/gocapability/capability/capability.go: no such file or directory
vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:24:2: open /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/ugorji/go/codec/decode_go14.go: no such file or directory
pkg/cloudprovider/providers/vsphere/vsphere.go:38:2: open /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/vmware/govmomi/find/doc.go: no such file or directory
!!! [1104 13:17:59] Call tree:
!!! [1104 13:17:59]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:710 kube::golang::build_binaries_for_platform(...)
!!! [1104 13:17:59]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1104 13:17:59] Call tree:
!!! [1104 13:17:59]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1104 13:17:59] Call tree:
!!! [1104 13:17:59]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:89: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:396: recipe for target 'cross' failed
make: *** [cross] Error 1
!!! [1104 13:17:59] Call tree:
!!! [1104 13:17:59]  1: build/../build/common.sh:513 kube::build::run_build_command_ex(...)
!!! [1104 13:17:59]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [quick-release] Error 1

**Comment by flybd5** [comment]
Exact same problem here in MacOS, using the very latest OSX beta. No matter what I do the build won't get past that point. After three days of trying different things I am giving up on this.

$ make quick-release
+++ [1104 02:04:59] Verifying Prerequisites....
+++ [1104 02:04:59] Using Docker for MacOS
+++ [1104 02:05:00] Building Docker image kube-build:build-32f91f5d20-5-v1.9.1-1
+++ [1104 02:05:07] Creating data container kube-build-data-32f91f5d20-5-v1.9.1-1
+++ [1104 02:06:06] Syncing sources to container
+++ [1104 02:06:14] Running build command...
+++ [1104 02:07:02] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:07:02] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:07:05] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1104 02:07:14] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:07:14] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:07:17] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1104 02:07:22] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:07:22] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:07:25] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [1104 02:07:30] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:07:31] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:07:33] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/openapi-gen
+++ [1104 02:07:41] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:07:41] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:07:44] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
    vendor/k8s.io/apiextensions-apiserver
    plugin/cmd/kube-scheduler
+++ [1104 02:18:09] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:18:09] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:18:12] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kubeadm
    cmd/kubelet
+++ [1104 02:18:35] Multiple platforms requested, but available 1G < threshold 11G, building platforms in serial
+++ [1104 02:18:35] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:18:35] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:18:38] Building go targets for darwin/amd64:
    cmd/kubectl
+++ [1104 02:19:42] Building go targets for linux/amd64:
    cmd/kubectl
+++ [1104 02:20:17] Multiple platforms requested, but available 1G < threshold 11G, building platforms in serial
+++ [1104 02:20:17] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1104 02:20:17] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1104 02:20:20] Building go targets for darwin/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
go build k8s.io/kubernetes/cmd/genkubedocs: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! [1104 02:28:10] Call tree:
!!! [1104 02:28:10]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:706 kube::golang::build_binaries_for_platform(...)
!!! [1104 02:28:10]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1104 02:28:10] Call tree:
!!! [1104 02:28:10]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1104 02:28:10] Call tree:
!!! [1104 02:28:10]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:92: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:442: recipe for target 'cross' failed
make: *** [cross] Error 1
!!! [1104 02:27:49] Call tree:
!!! [1104 02:27:49]  1: build/../build/common.sh:551 kube::build::run_build_command_ex(...)
!!! [1104 02:27:49]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [quick-release] Error 1

**Comment by ianchakeres** [comment]
I'm having the same problem building on mac osx, high sierra 10.13.2. I updated xcode and its command line tools.

```
$ uname -a
Darwin ichakeres-ltm.internal.salesforce.com 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

```
$ docker --version
Docker version 17.09.1-ce, build 19e2cf6
```

**Comment by ianchakeres** [comment]
I increased the memory for docker again on mac osx (from 3.5G to 4.5G), and I was able to successfully `make quick-release`.

@sykpour @flybd5 - Can you please test building after allocating more memory to docker?

**Comment by csunny** [comment]
@ianchakeres   At the beginning,  my docker memory is 2.0G,  and then i increased to 3.5G, but the problem was also  here, finalily, I increased to 5.0, and i was successful.    so happy,  thank you very much.

**Comment by flybd5** [comment]
I gave up on this and just installed the binaries, which seem to work fine.
