### ISSUE TITLE
/debug endpoint on nodes should get its own ACL rule, otherwise have to give root access on nodes

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#55121]
`/debug/pprof` on nodes is protected under the generic proxy rule for a node, which allows a high level of privilege under a node.  While in theory profiling can be used to extract sensitive info from a node, in general it is less powerful than the permissions required on the node.  The desire is to set up an automated debug endpoint that can capture profile traces for a cluster for participating members, and we would prefer not to give that component full access to nodes.

There may be some backward compatible implications of changing how node proxy ACL works, so we may have to do two checks to preserve the old path.

**Comment by smarterclayton** [comment]
/sig auth
@liggitt as we discussed

**Comment by mikedanese** [comment]
How many releases do we want to accept both?
