### ISSUE TITLE
Make CRI logs parsing to a library

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#55136]
We should make the CRI log parsing code in kubelet to be a library. So that container runtimes and external tools don't need to copy the whole code ( vendor it instead ).

Referring https://github.com/kubernetes-incubator/cri-tools/issues/169.

**Comment by yanxuean** [comment]
I can help on it.

**Comment by feiskyer** [comment]
@yanxuean Thanks. I have a branch ready for this. Will open a PR later and ping you when it is out.

**Comment by yanxuean** [comment]
ok
