### ISSUE TITLE
Collect prometheus metrics for custom resources

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#55146]
I can't find any api server metrics for custom resources.

@kubernetes/sig-api-machinery-bugs

**Comment by mbohlool** [comment]
What kind of metrics are you interested in? @enisoc @nikhita

**Comment by kargakis** [comment]
> What kind of metrics are you interested in? @enisoc @nikhita

Request latencies.

**Comment by kargakis** [comment]
Response sizes

**Comment by kargakis** [comment]
I am observing LISTS of ~1k # of CRs take up to ~1m to complete from time to time and I am not sure this is expected. Trying to figure out if metrics align with what I am seeing in logs.

**Comment by smarterclayton** [comment]
I would expect all CRDs to report metrics exactly the same as normal API resources.  They may need the full resource name and group (as opposed to just resource name, which built in resources return).
