### ISSUE TITLE
cluster e2e image puller should use `crictl`.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#55141]
Currently e2e image puller is using `docker pull`.
However for alternative runtime, e.g. cri-containerd, there won't be `docker pull`.
We should use `crictl pull` instead.

For now, I'll disable `PREPULL_E2E_IMAGES` for cri-containerd cluster e2e test. But we should fix this anyway.

@kubernetes/sig-node-bugs @yujuhong @feiskyer @mikebrow @abhi @miaoyq @yanxuean

**Comment by feiskyer** [comment]
@Random-Liu Am I missing something? e2e image puller has already swithed to CRI image service for remote runtime. Why should we switch to crictl?

https://github.com/kubernetes/kubernetes/blob/210626577b17ab014589e983b50b7cb821181a6c/test/e2e_node/image_list.go#L104-L129

**Comment by yujuhong** [comment]
> @Random-Liu Am I missing something? e2e image puller has already swithed to CRI image service for remote runtime. Why should we switch to crictl?

On the other hand, can we use the CRI puller even if runtime is set to `docker`? I believe the only exception would be `rkt`.

> We should use crictl pull instead.

@Random-Liu why `crictl pull`? Do we require `crictl` for node e2e tests?

**Comment by Random-Liu** [comment]
@feiskyer This issue is talking about the image puller in cluster e2e: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/e2e-image-puller/e2e-image-puller.manifest

> On the other hand, can we use the CRI puller even if runtime is set to docker? I believe the only exception would be rkt.

@yujuhong Yeah. That's how CRI works, right?

> why crictl pull? Do we require crictl for node e2e tests?

If not crictl pull, we need to write another binary ourselves. So the problem is why not `crictl`?
We could always build it into the image if we don't want it on the host. :)

**Comment by feiskyer** [comment]
@Random-Liu Got it. Right, crictl is the right tool there.

**Comment by yujuhong** [comment]
@Random-Liu I think we missed the "cluster" e2e keyword in your description, hence the confusion. Using `crlctl` in the image sounds good to me.

**Comment by Random-Liu** [comment]
@yujuhong I'll add "cluster". Thanks!

**Comment by Random-Liu** [comment]
This is fixed by https://github.com/kubernetes/kubernetes/pull/63357.
