### ISSUE TITLE
DNS endpoint for headless services with no ports

### ISSUE THREAD

**Issue by m4rcu5** [kubernetes/kubernetes#55158]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**:
When deploying a headless service without port definition, there is no DNS endpoint created.

**What you expected to happen**:
That there would be a valid DNS entry for the service that has just been created.

**How to reproduce it (as minimally and precisely as possible)**:
Use the example configuration from [the documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records-and-hostname-based-on-pods-hostname-and-subdomain-fields), but leave out the following section:
```
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
```

**Anything else we need to know?**:
Searching trough the issues, it seems I expect the "unexpected" behavior from ticket #49686, which might been fixed in #49722 and PR #47250

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+f38e43b221d08", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"not a git tree", BuildDate:"2017-10-18T09:41:00Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`minikube version: v0.23.0`

**Comment by m4rcu5** [comment]
@kubernetes/sig-network-bugs

**Comment by xiangpengzhao** [comment]
@m4rcu5 #47250 allows a headless service without ports and updates service endpoints for the service.
I note that you mentioned DNS endpoint. How did you check the DNS endpoint?
Thanks!

**Comment by m4rcu5** [comment]
@xiangpengzhao If I copy the complete example found in the [documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records-and-hostname-based-on-pods-hostname-and-subdomain-fields) you can resolve the endpoints as follows:
```
~ % kubectl exec -ti busybox1 -- nslookup busybox-2.default-subdomain.default.svc.cluster.local                           
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      busybox-2.default-subdomain.default.svc.cluster.local
Address 1: 172.17.0.3 busybox-2.default-subdomain.default.svc.cluster.local
```

If we recreate the example leaving out the ports, we get the following result:
```
~ % kubectl exec -ti busybox1 -- nslookup busybox-2.default-subdomain.default.svc.cluster.local 
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'busybox-2.default-subdomain.default.svc.cluster.local'
command terminated with exit code 1
```

Describing the `default-subomain` also does not show any endpoints:
```
Name:              default-subdomain
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          name=busybox
Type:              ClusterIP
IP:                None
Session Affinity:  None
Events:            <none>
```

**Comment by wallrj** [comment]
In https://github.com/jetstack/navigator/pull/128 I'm encountering this problem too.
 * I create a headless service with an empty Ports list 
 * Create a statefulset referring to that service
 * Pods created by the stateful set cannot resolve each others stable names.

I see the following errors in the cluster logs

```
I1115 15:29:11.020497       1 dns.go:552] Could not find endpoints for service "cass-cassandra-1510759748-1969-cassandra-seedprovider" in namespace "test-cassandracluster-1510759748-1969". DNS records will be created once endpoints show up.
I1115 15:29:11.020153       1 dns.go:552] Could not find endpoints for service "cass-cassandra-1510759748-1969-cassandra-seedprovider" in namespace "test-cassandracluster-1510759748-1969". DNS records will be created once endpoints show up.
```


```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.2-gke.0", GitCommit:"52ea03646e64b35a5b092ab32bb529400c296aa6", GitTreeState:"clean", BuildDate:"2017-10-24T23:31:18Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by zcourts** [comment]
Also experiencing something similar though it may not be the exact same thing.

I have GlusterFS configured in a 1.8 cluster. The gluster replicas were created via a stateful set and thus has a headless service to go with it.

If I try to use the glusterfs volume in a pod, in the same namespace (default) then the pod comes online fine and is able to mount the volume. 

I tried using the same gluster volume in a pod in a different namespace but it fails to resolve the endpoints. I've tried  `gluster-host`, `gluster-host.namesapce` and `gluster-host.namespace.svc.cluster.local` but all result in the same issue saying endpoint cannot be found. 

I moved the deployment into the default namespace and it started working as expected (using `gluster-host`, haven't tested the other names but I expect they now work too).

**Comment by kevindrosendahl** [comment]
Hi @xiangpengzhao,

I believe there's a bug in #47250 that is not allowing the endpoints for a headless service with no ports to be created.

At https://github.com/kubernetes/kubernetes/blob/v1.9.0/pkg/controller/endpoint/endpoints_controller.go#L457 and https://github.com/kubernetes/kubernetes/blob/v1.9.0/pkg/controller/endpoint/endpoints_controller.go#L577, the endpoints controller is adding a port with `Port: 0` to the EndpointSubset that is eventually included in the newEndpoints which gets created/updated.

In the API, this EndpointSubset is being validated at https://github.com/kubernetes/kubernetes/blob/v1.9.0/pkg/apis/core/validation/validation.go#L4632, and the port with `Port: 0` is failing validation at https://github.com/kubernetes/kubernetes/blob/v1.9.0/pkg/apis/core/validation/validation.go#L4651

This results in the server returning a 422, and the endpoints controller dropping the service out of its queue:

Logs from API:
```
I1220 23:54:16.831821       1 handler.go:160] kube-aggregator: POST "/api/v1/namespaces/default/endpoints" satisfied by nonGoRestful
I1220 23:54:16.831883       1 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/default/endpoints" satisfied by prefix /api/
I1220 23:54:16.831971       1 handler.go:150] kube-apiserver: POST "/api/v1/namespaces/default/endpoints" satisfied by gorestful with webservice /api/v1
I1220 23:54:16.834799       1 wrap.go:42] POST /api/v1/namespaces/default/endpoints: (7.962773ms) 422 [[kube-controller-manager/v1.9.0 (linux/amd64) kubernetes/925c127/system:serviceaccount:kube-system:endpoint-controller] 192.168.99.103:52396]
```

Logs from endpoint controller:
```
I1220 23:54:16.825460       1 endpoints_controller.go:415] About to update endpoints for service "default/nginx-headless-portless"
I1220 23:54:16.826048       1 endpoints_controller.go:512] Update endpoints for default/nginx-headless-portless, ready: 1 not ready: 0
I1220 23:54:16.836018       1 endpoints_controller.go:388] Finished syncing service "default/nginx-headless-portless" endpoints. (10.542651ms)
I1220 23:54:16.836384       1 endpoints_controller.go:375] Error syncing endpoints for service "default/nginx-headless-portless": Endpoints "nginx-headless-portless" is invalid: subsets[0].ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive
```

Steps to reproduce (logs above from this example):
```
$ minikube -p headless-service-bug start --kubernetes-version v1.9.0 --bootstrapper kubeadm --extra-config=apiserver.v=5 --extra-config=controller-manager.v=5
...

$ kubectl run nginx --image=nginx

$ cat << EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-portless
  namespace: default
spec:
  clusterIP: None
  selector:
    run: nginx
  type: ClusterIP
EOF

$ kubectl get services
NAME                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes                ClusterIP   10.0.0.1     <none>        443/TCP   3m
nginx-headless-portless   ClusterIP   None         <none>        <none>    1m

$ kubectl get endpoints
NAME         ENDPOINTS             AGE
kubernetes   192.168.99.103:8443   3m

$ cat << EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-with-port
  namespace: default
spec:
  clusterIP: None
  selector:
    run: nginx
  type: ClusterIP
  ports:
  - port: 12345
EOF

$ kubectl get services
NAME                       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
kubernetes                 ClusterIP   10.0.0.1     <none>        443/TCP     6m
nginx-headless-portless    ClusterIP   None         <none>        <none>      3m
nginx-headless-with-port   ClusterIP   None         <none>        12345/TCP   9s

$ kubectl get endpoints
NAME                       ENDPOINTS             AGE
kubernetes                 192.168.99.103:8443   6m
nginx-headless-with-port   172.17.0.5:12345      12s
```

Hope this helps.

**Comment by MrHohn** [comment]
Open https://github.com/kubernetes/kubernetes/pull/62497 for fixing.

**Comment by xiangpengzhao** [comment]
@MrHohn I had been missing this issue for a long time. Just found it again a couple days ago but haven't found a solution yet. Thanks for the fixing!
