### ISSUE TITLE
could not determine public dns AWS log spam

### ISSUE THREAD

**Issue by winjer** [kubernetes/kubernetes#55177]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig aws

**What happened**:

Every few seconds I get spam in my logs about "Could not determine public DNS from AWS metadata" from every node. This is really very spammy.

**What you expected to happen**:

No spam.

**How to reproduce it (as minimally and precisely as possible)**:

Launch a private topology cluster with kops.

**Anything else we need to know?**:

There will never be a public-hostname in the metadata for private topology clusters.  This line:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L1051

Should be glog.V(4) i suspect, like line 1033 above it.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Jessie
- Kernel (e.g. `uname -a`): 4.4.78-k8s
- Install tools: kops
- Others:

**Comment by xiangpengzhao** [comment]
@winjer fixed in #55214. PTAL. Thanks!

**Comment by winjer** [comment]
Thanks @xiangpengzhao! On a side note the metadata should probably be cached to stop thrashing the API but I don't know enough to be sure.
