### ISSUE TITLE
Can't retreive Pod Networks with kubectl apply

### ISSUE THREAD

**Issue by Theoooooo** [kubernetes/kubernetes#55170]
**What happened**:
Installed Master and Slave with the kubernetes documentation : https://kubernetes.io/docs/setup/independent/install-kubeadm/
Created a Cluster : https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ 
The cluster can be started
After this, i tried to install a Pod Network to start working with slaves inside the cluster

**What you expected to happen**:
The API i try to install should be pulled. But it's not working

**How to reproduce it (as minimally and precisely as possible)**:
Install docker 17.03 on the master,
Install Kubeadm, Kubectl and Kubelet like the documentation 
Created a cluster.
Try to pull the pod network Calico
Got error everywhere and i'm not able to pull any API with the "kubectl apply"

**Anything else we need to know?**:
There is the error from this command to install Calico : kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

`Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a80c0 0xc420112000 kube-system calico-config https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc420d03340 0xc420d03340  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": configmaps "calico-config" is forbidden: User "system:node:sca4-rt" cannot get configmaps in the namespace "kube-system": no path found to object
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a8900 0xc42033a770 kube-system calico-etcd https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc420d02318 0xc420d02318  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": daemonsets.extensions "calico-etcd" is forbidden: User "system:node:sca4-rt" cannot get daemonsets.extensions in the namespace "kube-system"
Error from server (Forbidden): error when creating "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": services is forbidden: User "system:node:sca4-rt" cannot create services in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a9380 0xc4206ba3f0 kube-system calico-node https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc420d02f88 0xc420d02f88  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": daemonsets.extensions "calico-node" is forbidden: User "system:node:sca4-rt" cannot get daemonsets.extensions in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a9a40 0xc4200423f0 kube-system calico-kube-controllers https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc420d03bf0 0xc420d03bf0  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": deployments.extensions "calico-kube-controllers" is forbidden: User "system:node:sca4-rt" cannot get deployments.extensions in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a9bc0 0xc42022b810 kube-system calico-policy-controller https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000c200 0xc42000c200  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": deployments.extensions "calico-policy-controller" is forbidden: User "system:node:sca4-rt" cannot get deployments.extensions in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a9c80 0xc4202e8b60  calico-cni-plugin https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000c540 0xc42000c540  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": clusterrolebindings.rbac.authorization.k8s.io "calico-cni-plugin" is forbidden: User "system:node:sca4-rt" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4209a9ec0 0xc4202e9f80  calico-cni-plugin https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000c7d8 0xc42000c7d8  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": clusterroles.rbac.authorization.k8s.io "calico-cni-plugin" is forbidden: User "system:node:sca4-rt" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4205aa000 0xc4201aed20 kube-system calico-cni-plugin https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000c990 0xc42000c990  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": serviceaccounts "calico-cni-plugin" is forbidden: User "system:node:sca4-rt" cannot get serviceaccounts in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4205aa240 0xc4201afea0  calico-kube-controllers https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000cb00 0xc42000cb00  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": clusterrolebindings.rbac.authorization.k8s.io "calico-kube-controllers" is forbidden: User "system:node:sca4-rt" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4205aa540 0xc4201fd3b0  calico-kube-controllers https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000cd38 0xc42000cd38  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": clusterroles.rbac.authorization.k8s.io "calico-kube-controllers" is forbidden: User "system:node:sca4-rt" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4205aaa80 0xc4204a80e0 kube-system calico-kube-controllers https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml 0xc42000cf20 0xc42000cf20  false}
from server for: "https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml": serviceaccounts "calico-kube-controllers" is forbidden: User "system:node:sca4-rt" cannot get serviceaccounts in the namespace "kube-system"
`

**Environment**:
- Kubernetes version 1.8.2
- Linux Debian SMP 4.9.30-2+deb9u5

**Comment by bluebenno** [comment]
same methodology and error here. ubuntu 16.04,  1.8.3,  docker 17.03.2~ce-0~ubuntu-xenial.  
In my case a *reinstall* after kubeadm reset

**Comment by Theoooooo** [comment]
@bluebenno These both solutions doesn't work. Changing the driver just doens't allow me to start my cluster and reinstalling kubeadm after a reset do nothing. I still have the same problem.
I also mention i start my cluster with the CIDR-POD-NETWORK for calico 192.168.0.0/16

**Comment by Theoooooo** [comment]
After messing around, i finally got around of my problems with reinstalling my entire linux. I also checked again everything said in the documentation. That was weird

**Comment by Theoooooo** [comment]
Hey i open this again because maybe i find why this is hapenning. 
When you reset your cluster and launch it again, all the serviceaccounts are not deleted (i think). Because of this, when i try to do any command, i don't have any authorization because kubectl use the previous account, which is forbidden : 
`Error from server (Forbidden): serviceaccounts is forbidden: User "system:node:sca4-rt" cannot list serviceaccounts at the cluster scope`
I got this error for every command.

**Comment by nilanjan-samajdar** [comment]
@Theoooooo and @jonduttweiler 
I ran into this issue while setting up a Kubernetes Cluster with kubeadm.
The problem occurs because `kubeadm init` generates the `admin.conf`, but does not replace the `admin.conf` file in case it is already present. 
Hence, in case the access certificates for the cluster users changed, `kubectl` will continue using the older (redacted) configuration and any Cluster level operation will be forbidden by the API gateway.
You can see evidence of the issue when you do a `kubectl config view`, where any ca-certificate status will show as `REDACTED`.
So in case you are having trouble, just delete the `admin.conf` before you do a `kubeadm init`.
This should resolve the issue.

**Comment by Theoooooo** [comment]
@nilanjan-samajdar 
Hmmmmm i think about this issue later but i didn't have access anymore to my cluster. school is over ^^
Well thank you for the solution. I'm gonna write it somewhere in my brain because i have a funny feeling i will encounter this issue when i will make a kubernetes cluster again :D

**Comment by bidyut1990** [comment]
@nilanjan-samajdar   I did a kubectl reset and it does remove the admin.conf file for me. But I am running into this issue regardless. Is this something to do with the older calico setup. So for background, I had done a kubectl init without the "pod-network-cidr" required for calico and had setup calico on the master node as well. But sensing that this wouldnt work, i did kubectl reset, wiped off older iptables and removed older calico-data file. And then did a fresh kubectl init with the proper cidr parameter. But now calico doesnt set up due to the same error messages.

**Comment by bidyut1990** [comment]
Just tried the same kubectl init command with sudo privilege  after removing older contexts and now calico doesnt give me those errors. SO i think it worked!
But on the other hand, i see that kube-dns pod is not starting and remains in ContainerCreating state. Should this be a problem . 
Also "calico-node" pod is in CrashLoopBackOff state. Any experts?

**Comment by jonduttweiler** [comment]
Hello  @bidyut1990 , you should check what's happen in these pods using kubectl logs <pod_name> , try first with calico-node, because the dns pod may need this to boot,
Greetings, 
Jonatan

**Comment by bidyut1990** [comment]
@jonduttweiler - Thanks for the tip. I went ahead with Weavenet for the pod network as of now. If i switch back and face this issue with calico , then i ll try your advise.

**Comment by jonduttweiler** [comment]
@bidyut1990  When something crashes, your best friends are the logs.
