### ISSUE TITLE
Does ACS Kubernetes supports the volume and mounts for Windows Container? I search this information on web for while, but I am not able to find it. Need Help! Thanks! Feng

### ISSUE THREAD

**Issue by fengli858** [kubernetes/kubernetes#55176]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
please talk to the folks from microsoft - https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-kubernetes-walkthrough

/close
