### ISSUE TITLE
Why retry_handler for AWS not consitent with AWS SDK defined conditions of retryableCodes and throttleCodes??

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes/kubernetes#55182]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig aws
> /kind feature

**What happened**:
Kubernetes code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/retry_handler.go#L84

From AWS SDK ..
https://github.com/aws/aws-sdk-go/blob/master/aws/request/retryer.go#L28
var retryableCodes and throttleCodes

AWS SDK provides IsErrorRetryable and isThrottle functions.
 instead of just checking for rate limit exceed error message.
Also do we retry even AWS says error is due to throttling? 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
It is about the code at master in gituhb.
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by etsangsplk** [comment]
https://github.com/kubernetes/kubernetes/pull/55187

**Comment by justinsb** [comment]
This isn't request level retries, this is the global rate-limiter backoff: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/retry_handler.go#L35-L37

**Comment by etsangsplk** [comment]
@justinsb 
Thanks. I am very new to the codebase. So let me check if I understand you correctly, the comment means that if k8s issue a k8s request that result in a set of AWS calls, if any of the AWS calls resulted in a Rate Limit exceed from AWS side, this counts against for cluster wide, because everyone need to be delayed, stopped etc.

Also, a side note: I made a mistake in the error. AWS request may return other error code as "limit reached" from various services of which some k8s are not using.

var throttleCodes = map[string]struct{}{
	"ProvisionedThroughputExceededException": {},
	"Throttling":                             {},
	"ThrottlingException":                    {},
	"RequestLimitExceeded":                   {},  <----- k8s
	"RequestThrottled":                       {},  <----???
	"TooManyRequestsException":               {}, // Lambda functions    <-----
	"PriorRequestNotComplete":                {}, // Route53
}
AWS sdk go code:
https://github.com/aws/aws-sdk-go/blob/master/aws/request/retryer.go#L28

**Comment by justinsb** [comment]
Correct @etsangsplk :-)

We still have the "normal" AWS retry logic - this is just an additional backoff.

Suggestion:  I like to look at the git history.  Blame leads to https://github.com/kubernetes/kubernetes/commit/b269e8f43cfd17edb32ff3107a2b5ab1fcb4ad8e, which links to https://github.com/kubernetes/kubernetes/pull/19335 .  Hopefully that'll have a little bit more context!
