### ISSUE TITLE
[job failure] soak-gce-gci

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#55196]
/priority critical-urgent
/priority failing-test
/area platform/gcp
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 
FYI @kubernetes/sig-testing-test-failures

This job has been failing since 2017-10-25.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-alpha.3](https://github.com/kubernetes/sig-release/issues/27). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#soak-gce-gci

/assign @krzyzacy @fejta 
IIRC correct I brought this up during a sig-testing meeting and was told there's work in progress to redo how soak tests are done, can you fill in some details here?  It's unclear to me whether I should be poking at test case owners, or if our infra is still in flux here

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-release-1.8-all#gci-gce-soak-1.8 looks much better, maybe master branch has some leaks or other stuff that did some damage to the existing cluster? Before suite should not fail.

The 10/31 cluster will be recycled tomorrow, let's wait and see the next suite of tests.

**Comment by krzyzacy** [comment]
@spiffxp https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-soak-gce-gci-test/ the previous Jenkins version was also red all the time, this job should not be blocking the release or anything.

**Comment by krzyzacy** [comment]
the new cluster looks healthier, you might want to assign to specific test owners now
/unassign

**Comment by abgworrall** [comment]
There is an issue with node runtime memory that might be significant; I'm chasing it.

All the other failures all seem due to #55194 , the scale-correctness stuff timing out.

On that basis, I think this test is useful and I'd like to retain it.

**Comment by spiffxp** [comment]
@abgworrall 
>On that basis, I think this test is useful and I'd like to retain it.

I think you're referring to https://github.com/kubernetes/test-infra/pull/5529, where I discussed that removing the job from sig-release-master-blocking won't remove the job from https://k8s-testgrid.appspot.com/google-soak

/close
The job itself is now failing due to an individual test failure, which I'll chase separately unless it turns out this is the only job it's failing for
