### ISSUE TITLE
[job failure] gci-gke-ingress

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#55195]
/priority critical-urgent
/priority failing-test
/area platform/gke
/kind bug
/status approved-for-milestone
@kubernetes/sig-network-test-failures
FYI @kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-02.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-alpha.3] (kubernetes/sig-release#27). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-ingress

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress/16163
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress/16164
- latest bad as of filing: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress/16308
- suspect changelog: https://github.com/kubernetes/kubernetes/compare/55e216f56...3a15fdbe7

This seems like the same failures as #55189

**Comment by spiffxp** [comment]
>ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=You cannot create more than 3 clusters in zone us-central1. To create more than 3, you must request an increase of your Google Compute Engine quota for region us-central1 to 25 CPUS or more.

Thanks to the fixes for #55189, the job is now oscillating between passing and this failure mode.

**Comment by abgworrall** [comment]
@krzyzacy , is this a simple quota bump, or a leak, or what ?

**Comment by abgworrall** [comment]
We have a theory about this (we're leaking cluster resources, which are a thing in GKE but not GCE). @krzyzacy will take a look later, and hopefully this job will become stable.

**Comment by krzyzacy** [comment]
(which seems not the case? `gcloud container clusters list` gives me nothing, or I'm doing this wrong)

**Comment by dims** [comment]
@abgworrall @krzyzacy one of you want to be the assignee for this bug please?

**Comment by abgworrall** [comment]
/assign @krzyzacy 
... until the theory is proved false

**Comment by krzyzacy** [comment]
after https://github.com/kubernetes/test-infra/pull/5548 the boskos pool should be gradually cleaning up ancient leaked clusters. I'll let it soak and check back tomorrow.

**Comment by krzyzacy** [comment]
/unassign
/sig network
now looks like the test is panicking
cc @kubernetes/sig-network-bugs

**Comment by spiffxp** [comment]
The "test panicked" issue is also affecting gci-gce-ingress, I'll open an issue shortly and keep this open

**Comment by spiffxp** [comment]
Now tracking this against v1.9.0-beta.1 (https://github.com/kubernetes/sig-release/issues/27)

**Comment by MrHohn** [comment]
https://k8s-testgrid.appspot.com/google-gke#gci-gke-ingress
Test is no longer failing, seems #56128 fixed it.

/close
