### ISSUE TITLE
Openstack Cloud Provider and VM's With an IPv6 Address Cause System Pods to Have IPV6 Addresses

### ISSUE THREAD

**Issue by rfliam** [kubernetes/kubernetes#55202]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

When the Kubernetes openstack cloud provider is enabled, pods with network=host advertise with an ipv6 address if the machine has an ipv6 address instead of ipv4.

This breaks things like Calico and seems to create all sorts of weird issues.

**What you expected to happen**:

The machine uses it's ipv4 addresses, as ipv6 is still largely unsupported in kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

- Build an openstack instance with both an ipv4 and ipv6 address
- Install a kube environment using kubeadm (following [this guide](http://henriquetruta.com/2017/09/13/openstack-cloud-provider/) )
- Check pod ip's after enabling the openstack cloud provider
```
po/kube-proxy-8jjl4                                        1/1       Running   2          1h        2001:558:fc0a:6:f816:3eff:fe86:887d   kube-master-01.openstacklocal
po/kube-scheduler-kube-master-01.openstacklocal            1/1       Running   2          1h        2001:558:fc0a:6:f816:3eff:fe86:887d   kube-master-01.openstacklocal
```
- Check addresses on node:
```addresses:							 
  - address: 2001:558:fc0a:6:f816:3eff:fe86:887d	     
    type: InternalIP
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.2
- Cloud provider or hardware configuration: Openstack Mitaka
- OS (e.g. from /etc/os-release): CentOS-7
- Kernel (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64
- Install tools: kubeadm 1.8.2
- Others:

**Comment by rfliam** [comment]
@kubernetes/sig-openstack-bugs

**Comment by dims** [comment]
yep, there's a plan for alpha ipv6 support in k8s for 1.9 - https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/D_VxCZIvbe4/-NCHNdnaCQAJ

**Comment by FengyunPan** [comment]
It seems a big feature, sounds good.

**Comment by dims** [comment]
/sig network

cc @danehans 

/remove-sig openstack

**Comment by anguslees** [comment]
I strongly suggest this is not a bug.  If you're using the host network, and you've configured IPv6 addresses on the host (explicitly or implicitly), then you *should* see IPv6 addresses for host pods.

If IPv6 addresses are an issue for your infrastructure, then the solution is to not configure IPv6 addresses on the host (and file a "should support ipv6" bug with your infrastructure component).

In particular, blacklisting IPv6 addresses at the application layer (in k8s) is *harmful* to anyone who is using IPv6 (now or in the future) and is not an acceptable solution to the original issue.

**Comment by rfliam** [comment]
There are _plenty_ of valid reasons to blacklist IPV6 addresses being exposed to kubernetes.

First and foremost in Kube 1.8 (and 1.9) most infrastructure components use host networking. Most do not; however, support ipv6. This includes core kube components like **_etcd_**. In kube 1.8 if IPV6 addresses are exposed for pods like etcd **_the cluster won't start_**. That's a pretty serious issue. And while fixing all the places that IPV6 is broken in kube would be _great_, a cursory glance through the code, the linked initiatives, etc. says that's a long way off. 

To be clear IPV6 works fine in my infrastructure. It does _not_ work fine with kube. And I may want the host to have IPV6 support for other applications than kube. Or I may want IPV6 on the host so my pods can use it, but not expose that info to kube (which breaks it). We do this in many places in our infrastructure.

Having the feature to filter ipv6 addresses be flag-able is perfectly reasonable. Indeed the most sensible long term route is allowing me to specify which interface is reported to kube, because multiple IPV4 addresses can have a similar effect.

**Comment by dims** [comment]
How about we add a config option to filter out ipv6 but leave the current behavior as is?

**Comment by anguslees** [comment]
Right, so it sounds like the bugs are:
- kube is only publishing a single address for the node (rather than one for each family, or all addresses for all families)
- whatever is *consuming* the address information from kube should filter out whatever families are unsupported by that application
- kubelet/controller-manager should have an override flag so the admin can just arbitrarily declare which specific addresses are advertised for a node
- (ipv6 support throughout the ecosystem is not complete yet)

?
