### ISSUE TITLE
Literal "$Format" in API server logs

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55219]
/kind bug

**What happened**:

I see the literal string "(dollar_sign)Format" in the API server logs:

```
I1101 07:05:53.364424       7 wrap.go:42] GET /api/v1/namespaces/kube-system/services/default-http-backend: (1.73008ms) 404 [[glbc/v0.0.0 (linux/amd64) kubernetes/$Format] 127.0.0.1:52702]
```

Note that most lines are fine, it seems that just some binaries don't have the placeholder substituted:

```
I1101 07:06:29.825192       7 wrap.go:42] POST /apis/authorization.k8s.io/v1beta1/subjectaccessreviews: (361.716µs) 201 [[kube-controller-manager/v1.9.0 (linux/amd64) kubernetes/7f9f847/system:serviceaccount:kube-system:certificate-controller] [::1]:50612]
```

**What you expected to happen**:

Expected to see kubernetes commit ID or tag name in all cases.

**How to reproduce it (as minimally and precisely as possible)**:

Run an e2e test, grep for Format in API server log.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: GCE

**Comment by porridge** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by stewart-yu** [comment]
i will have a look.

**Comment by justinsb** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/33532 ?

**Comment by stewart-yu** [comment]
why just occurred in request to "/api/v1/namespaces" or "/api/v1/endpoints", it's so strange!

**Comment by porridge** [comment]
I think it depends on the client binary, and is only indirectly correlated
with the URI.

**Comment by stewart-yu** [comment]
It seen that thoes format error log in apiserver not match this output format in client-go/rest/config.go, and no other output format like this.
![image](https://user-images.githubusercontent.com/30410021/32588412-82319190-c549-11e7-8025-be5739e5001d.png)

**Comment by justinsb** [comment]
It's because the format has not been substituted here:https://github.com/kubernetes/ingress-gce/blob/master/vendor/k8s.io/client-go/pkg/version/base.go#L55

**Comment by lavalamp** [comment]
This is the User-Agent header, which apiserver emits unaltered. IOW, this is a client bug, not an apiserver bug.

**Comment by lavalamp** [comment]
If you can figure out which client is doing it wrong, we can give this bug to them?

**Comment by porridge** [comment]
As you can see in https://github.com/kubernetes/kubernetes/issues/55219#issue-271738940 in the dev environment I've seen, it was at least glbc. I've also seen it sent by kube-dns and heapster.

**Comment by porridge** [comment]
What I mean is that it seems to be a problem in the build procedure for a subset of k8s binaries.

**Comment by stewart-yu** [comment]
I have set up cluster with local-up, seen that just using `kube-dns` have format error in kube-apiserver log. I will continue to effort.

**Comment by justinsb** [comment]
@lavalamp it's client-go that has to provide instructions IMO, then we can poke people that aren't following the instructions; I don't know of any guidance right now.  Possibilities:

* client-go could stamp the version into each branch, e.g. at https://github.com/kubernetes/client-go/blob/release-4.0/pkg/version/base.go  
* client-go could require the caller to use ldflags e.g. to specify the version
* the caller could be required to pass an additional parameter during client initialization, to specify the user agent at runtime via whatever mechanism they are using.

It's not overly clear to me whether this useragent is supposed to be the client-go version or the app version.

**Comment by porridge** [comment]
regarding client-go vs app version:
![version](https://user-images.githubusercontent.com/489420/32712189-825437ac-c843-11e7-85b5-cea919b7f145.gif)
why not have both?

**Comment by stewart-yu** [comment]
Does something  embed into relative images? i have strong feeling about it.

**Comment by porridge** [comment]
What do you mean by "relative images"?

**Comment by stewart-yu** [comment]
I think `glbc` 、` kube-dns` and `heapster` have own images, but others use client-go

**Comment by nikhita** [comment]
> I think glbc 、kube-dns and heapster have own images, but others use client-go

I'm going to add good-first-issue on this because the fix for others can follow the same directions as that of the fix for kubedns: https://github.com/kubernetes/dns/pull/163.

/remove-lifecycle stale
/good-first-issue

**Comment by niki-1905** [comment]
Can I work on this?

**Comment by nikhita** [comment]
> Can I work on this?

@niki-1905 yes, please go ahead! :rocket:

**Comment by dczombera** [comment]
@niki-1905 Are u still working on it?
If not, I'd like to take over. :)
