### ISSUE TITLE
Improve robustness of certificate setup during e2e cluster creation

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55229]
/kind bug

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/24?log#log failed with

```
W1102 07:04:27.366] cat: /tmp/tmp.SCCiCqM3nQ/easy-rsa-master/aggregator/pki/issued/proxy-client.crt: No such file or directory
```

This is not the first time: [flake1](https://github.com/kubernetes/kubernetes/issues/39335#issuecomment-270853343), [flake2](https://github.com/kubernetes/kubernetes/issues/40139#issuecomment-273880602).

**What you expected to happen**:

Not fail.

**How to reproduce it (as minimally and precisely as possible)**:

TBD

**Anything else we need to know?**:

The current theory (from the flake1 above) is:

${CERT_DIR}/pki/issued/kubelet.crt wasn't found inside cluster/common.sh:create-certs even though it was surely written in generate-certs (as it didn't exit with non-zero status), so I feel that most probably the /tmp directory was cleared by the daily cron-job meant to delete /tmp

However I'm not convinced this is true... AFAICT, the e2e runs in a docker container, which I don't think runs the tmp reaper. So this could only be valid if we are mounting /tmp from the host system.

/cc @shyamjvs 
/assign

**Comment by porridge** [comment]
@kubernetes/sig-scalability-bugs

**Comment by porridge** [comment]
Looks like error handling in shell functions `setup-easyrsa`, `generate-certs` and `generate-aggregator-certs` is just broken, they always succeed.

**Comment by porridge** [comment]
Basically writing reliable shell code is hard. I consider myself pretty fluent in shell, and yet this surprised me. Perhaps I'm missing something:

```
$ cat c.sh 
#!/bin/bash
set -e

echo parens
( false; echo :survived; ) || { echo failed1; }

echo curlies
{ false; echo :survived; } || { echo failed2; }

function func {
 set -e
 false
 echo :survived
}

echo func followed by curlies
func || { echo failed3; }

echo func followed by echo
func || echo failed4

echo func in an if
if ! func ; then
  echo failed5
fi

echo direct
func
echo end
$ bash c.sh ; echo $?
parens
:survived
curlies
:survived
func followed by curlies
:survived
func followed by echo
:survived
func in an if
:survived
direct
1
$ 
```

OTOH builtins(1) manpage says this is expected:

>               -e      Exit immediately if a pipeline (which may consist of a single simple command), a list, or a compound command (see SHELL GRAMMAR
>                       above),   exits  with a non-zero status.  The shell does not exit if the command that fails is part of the command list immedi‐
>                       ately following a while or until keyword, part of the test following the if or elif reserved words, part of  any  command  exe‐
>                       cuted  in  a  &&  or || list except the command following the final && or ||, any command in a pipeline but the last, or if the
>                       command's return value is being inverted with !.  If a compound command other than a subshell returns a non-zero status because
>                       a  command  failed  while  -e  was being ignored, the shell does not exit.  A trap on ERR, if set, is executed before the shell
>                       exits.  This option applies to the shell environment and each subshell environment separately (see COMMAND  EXECUTION  ENVIRON‐
>                       MENT above), and may cause subshells to exit before executing all the commands in the subshell.
> 
>                       **If  a  compound command or shell function executes in a context where -e is being ignored, none of the commands executed within
>                       the compound command or function body will be affected by the -e setting, even if -e is set and a  command  returns  a  failure
>                       status.   If  a  compound command or shell function sets -e while executing in a context where -e is ignored, that setting will
>                       not have any effect until the compound command or the command containing the function call completes.**
>

**Comment by porridge** [comment]
Hello @kuberne

**Comment by porridge** [comment]
I'm sure @roberthbailey will be equally surprised this error handling code never worked since he [added it back in 2015](https://github.com/kubernetes/kubernetes/commit/9ab41db7ea3c7e167cbb72a307d1b9c200f8f195#diff-420e5229cfe0f54223f75636d6a0ca5cR524). Or maybe not, given the TODO :-)

Hello @kubernetes/sig-cluster-lifecycle-bugs I suppose you own `cluster/common.sh`?
Any opinions on approaches to fixing this? There is this [one weird hack](https://unix.stackexchange.com/a/254676) to work around this shell behaviour, but (un)fortunately it cannot be easily used here because some of these functions set environment variables to be used elsewhere.

There is this other TODO around here as well:

> TODO(roberthbailey): Replace easyrsa with a simple Go program to generate
> the certs that we need.

Are there actual plans to do this?

**Comment by roberthbailey** [comment]
> I'm sure @roberthbailey will be equally surprised this error handling code never worked since he added it back in 2015. Or maybe not, given the TODO :-)

Yeah, error handling in bash sucks. Testing your shell example a bit, it looks like the sub-shell will only exit with a non-zero code if the last command exits with a non-zero code. So something like

```bash
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

echo parens
(set -o errexit
set -o nounset
set -o pipefail
false &&
echo :survived ) || {
  echo failed1;
}
```

Does the right thing because we chain each command to the previous command and the overall subshell exit code is what we expect. 

> Are there actual plans to do this?

We now have kubeadm, which is a go program that generates certs. The kube-up "code" (if you can call it that) is in maintenance mode because we know that it is fragile.

**Comment by roberthbailey** [comment]
> There is this one weird hack to work around this shell behaviour, but (un)fortunately it cannot be easily used here because some of these functions set environment variables to be used elsewhere.

I don't see anywhere where we set environment variables in subshells. We use existing variables, but which new ones do you see being created / set?

**Comment by porridge** [comment]
generate-certs calls kube::util::ensure-cfssl which sets CFSSL_BIN
and CFSSLJSON_BIN

**Comment by porridge** [comment]
More failures:
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/7874

**Comment by porridge** [comment]
This happened again, this time with the working debugging code in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sig-cli/275

```
W1116 04:47:10.514] Unable to successfully run 'cfssl' from /go/bin:/usr/local/go/bin:/google-cloud-sdk/bin:/workspace:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; downloading instead...
W1116 04:47:10.514] ++ uname -s
W1116 04:47:10.514] + kernel=Linux
W1116 04:47:10.514] + case "${kernel}" in
W1116 04:47:10.514] + curl -s -L -o cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
W1116 04:47:10.514] + curl -s -L -o cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
W1116 04:47:10.514] + chmod +x cfssl
W1116 04:47:10.515] + chmod +x cfssljson
W1116 04:47:10.515] + CFSSL_BIN=/tmp/tmp.2OaRCvO3D4/cfssl/cfssl
W1116 04:47:10.515] + CFSSLJSON_BIN=/tmp/tmp.2OaRCvO3D4/cfssl/cfssljson
W1116 04:47:10.515] + [[ ! -x /tmp/tmp.2OaRCvO3D4/cfssl/cfssl ]]
W1116 04:47:10.515] + [[ ! -x /tmp/tmp.2OaRCvO3D4/cfssl/cfssljson ]]
W1116 04:47:10.515] + popd
W1116 04:47:10.515] + command popd
W1116 04:47:10.515] + popd
W1116 04:47:10.516] + echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","client auth"]}}}'
W1116 04:47:10.516] + /tmp/tmp.2OaRCvO3D4/cfssl/cfssljson -bare kubelet
W1116 04:47:10.516] + /tmp/tmp.2OaRCvO3D4/cfssl/cfssl gencert -ca=pki/ca.crt -ca-key=pki/private/ca.key -config=ca-config.json -
W1116 04:47:10.516] /tmp/tmp.2OaRCvO3D4/cfssl/cfssljson: line 1: syntax error near unexpected token `newline'
W1116 04:47:10.516] /tmp/tmp.2OaRCvO3D4/cfssl/cfssljson: line 1: `<!DOCTYPE html>'
W1116 04:47:10.516] + echo '{"CN":"kubelet","names":[{"O":"system:nodes"}],"hosts":[""],"key":{"algo":"rsa","size":2048}}'
```

This means the root cause is essentially https://github.com/kubernetes/kubernetes/issues/55589

**Comment by shyamjvs** [comment]
Do we know what options we have here to fix this?
It'll get particularly expensive to lose our scale runs due to this flake.

**Comment by porridge** [comment]
Ideally all contexts where cfssl is executed should have it pre-installed. I don't know what they are, though, not even mentioning how they are created.

**Comment by porridge** [comment]
Current status:
- the error handling improved in  #55675 was enough to establish that the root cause for these failures was in fact the same as #55589, which will be tracked there
- the only other thing worth leaving here is improving the error handling of certificate setup code, possibly via rewriting that whole area as a small go program in place of bash functions, retitling this issue to that effect.
/unassign

**Comment by jlucktay** [comment]
I'm having trouble with this at the moment, and may have devised a way out of it.

- macOS 10.13.4
- Kubernetes 1.10.1
- openssl 1.0.2o (installed via [Homebrew](https://brew.sh))

[This open issue](https://github.com/OpenVPN/easy-rsa/issues/74) with easy-rsa seems to be the root cause, and [this specific comment re: exporting EASYRSA_OPENSSL](https://github.com/OpenVPN/easy-rsa/issues/74#issuecomment-334691069) has helped me get past it.

In `kubernetes/cluster/gce/util.sh` ahead of the two blocks of `easyrsa` calls within the functions `generate-certs` and `generate-aggregator-certs`, I added an `export` line like this:
```
export EASYRSA_OPENSSL="/usr/local/Cellar/openssl/1.0.2l/bin/openssl"
```

Hope this is helpful! 🙂
