### ISSUE TITLE
Error syncing pod / PercpuUsage had 0 cpus, but the actual number is 2; ignoring extra CPUs

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#55226]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
After first installation 1 mater and 1 node, i have errors on node kubelet service

> 19044 pod_workers.go:182] Error syncing pod 4bb5a2c6-c352-11e7-af21-000c29d74419 ("kube-dns-545bc4bfd4-jz7zh_kube-system(4bb5a2c6-c352-11e7-af21-000c29d74419)"), skipping: failed to "StartContainer" for "kubedns" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubedns pod=kube-dns-545bc4bfd4-jz7zh_kube-system(4bb5a2c6-c352-11e7-af21-000c29d74419)"
   19044 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 2; ignoring extra CPUs
   19044 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 2; ignoring extra CPUs

**Environment**:
- Kubernetes version (use `kubectl version`): **1.8.2**
- Cloud provider or hardware configuration: **vmware**
- OS (e.g. from /etc/os-release): **centos 7.4**
- Kernel (e.g. `uname -a`): **3.10.0-693.5.2.el7.x86_64**
- Install tools:
- Others:

/sig Scheduling
/sig Node

**Comment by slowaak** [comment]
I'm observing the same issue
#### Environment ####
- Kubernetes version 1.8.2
- Cloud: Raspberry PI 3 cluster
- OS: PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v1.1.1"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.5.0"
- Kernel: Linux pi2 4.4.50-hypriotos-v7+ #1 SMP PREEMPT Sun Mar 19 14:11:54 UTC 2017 armv7l GNU/Linux

**Comment by gabrielfsousa** [comment]
the firt error is 

>  failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "kube-dns-545bc4bfd4-jz7zh_kube-system": CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "575db4b11f595f2a48056211a74bb07737c516b47fbe020b8d9c0ac130d72310"

**Comment by gabrielfsousa** [comment]
found my problem
forgot to disable and stop firewalld on node

**Comment by javefang** [comment]
Have you found a solution to the original problem in your first post? I'm seeing the same error message in kubelet logs. Centos 7.4 and k8s 1.8.2

**Comment by einyx** [comment]
same for the centos error

**Comment by vdavidoff** [comment]
I see this, too, after updating from 1.7.2 to 1.8.4 on Ubuntu. This was reported a bunch during the upgrade process, and it's hard to make sense of what's relevant in terms of long term / non-temporary issues, but since then the only Pod that _seems_ to be causing this to occur is a short lived CronJob Pod. Although this gets logged almost every time that pod is launched, I did observe one time it didn't occur, but I don't know why. The only thing I noticed for sure was that when the message _didn't_ occur, the `Waiting for volumes to attach and mount for pod` message in kubelet's logs came before `Start housekeeping for container`. I don't know if that's actually relevant though.

It looks like this message comes from `setCpuStats` in `vendor/github.com/google/cadvisor/container/libcontainer/helpers.go`, specifically triggered by the following apparently getting 0 back: `numPossible := uint32(len(s.CpuStats.CpuUsage.PercpuUsage))`. I don't know enough about cAdvisor to know why that might happen, though (that is, why the stat meant to represent per-cpu usage for a cgroup would be empty, suggesting there are no CPUs available in the cgroup).

**Comment by lokendras395** [comment]
Facing the same issue with one worker node,
worker node os specs
"""
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
"""

kubelet logs
"""
Dec 19 14:02:49 jp-blr-r1-node3 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Dec 19 14:02:49 jp-blr-r1-node3 systemd[1]: Started Kubernetes Kubelet.
Dec 19 14:02:49 jp-blr-r1-node3 systemd[1]: Starting Kubernetes Kubelet...
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.884913   28949 feature_gate.go:156] feature gates: map[]
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.885001   28949 controller.go:114] kubelet config controller: starting controller
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.885008   28949 controller.go:118] kubelet config controller: validating combination of defaults and flags
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.891828   28949 mount_linux.go:168] Detected OS with systemd
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.891853   28949 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.891874   28949 client.go:95] Start docker client with request timeout=2m0s
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.899548   28949 feature_gate.go:156] feature gates: map[]
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:49.899760   28949 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set e
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:49.906507   28949 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.servi
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:49.993395   28949 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 
Dec 19 14:02:49 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:49.993541   28949 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dia
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.072574   28949 fs.go:139] Filesystem UUIDs: map[3ca5b393-d55a-4aa4-8bee-4d8788699644:/dev/sda1 d96d2a7b-cc3f-4739-90
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.072622   28949 fs.go:140] Filesystem partitions: map[tmpfs:{mountpoint:/dev/shm major:0 minor:18 fsType:tmpfs blockS
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.078540   28949 manager.go:216] Machine: {NumCores:16 CpuFrequency:1700000 MemoryCapacity:67269701632 HugePages:[{Pag
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[4] Caches:[{Size:32768 Type
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.079791   28949 manager.go:222] Version: {KernelVersion:3.10.0-693.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.080714   28949 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.083364   28949 container_manager_linux.go:252] container manager verified user specified cgroup-root exists: /
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.083395   28949 container_manager_linux.go:257] Creating Container Manager object based on Node Config: {RuntimeCgrou
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.083548   28949 container_manager_linux.go:288] Creating device plugin handler: false
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.083648   28949 server.go:686] Using root directory: /var/lib/kubelet
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.083675   28949 kubelet.go:283] Watching apiserver
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:50.089414   28949 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling b
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.089442   28949 kubelet.go:517] Hairpin mode set to "hairpin-veth"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.089673   28949 plugins.go:187] Loaded network plugin "cni"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.097585   28949 plugins.go:187] Loaded network plugin "cni"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.097607   28949 docker_service.go:207] Docker cri networking managed by cni
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.177194   28949 docker_service.go:224] Setting cgroupDriver to cgroupfs
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.177996   28949 docker_legacy.go:151] No legacy containers found, stop performing legacy cleanup.
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.178065   28949 kubelet.go:606] Starting the GRPC server for the docker CRI shim.
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.178092   28949 docker_server.go:51] Start dockershim grpc server
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.258044   28949 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260171   28949 kuberuntime_manager.go:177] Container runtime docker initialized, version: 17.03.2-ce, apiVersion: 1.
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260500   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/aws-ebs"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260525   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/empty-dir"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260541   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/gce-pd"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260568   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/git-repo"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260582   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/host-path"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260595   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/nfs"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260611   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/secret"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260626   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/iscsi"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260644   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/glusterfs"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260659   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/rbd"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260676   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/cinder"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260690   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/quobyte"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260706   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/cephfs"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260722   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/downward-api"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260737   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/fc"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260752   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/flocker"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260765   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/azure-file"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260783   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/configmap"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260800   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/vsphere-volume"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260815   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/azure-disk"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260830   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/photon-pd"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260846   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/projected"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260860   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/portworx-volume"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260876   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/scaleio"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260944   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/local-volume"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.260962   28949 plugins.go:420] Loaded volume plugin "kubernetes.io/storageos"
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.262135   28949 server.go:718] Started kubelet v1.8.2
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:50.262226   28949 kubelet.go:1234] Image garbage collection failed once. Stats initialization may not have completed ye
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.262234   28949 server.go:128] Starting to listen on 0.0.0.0:10250
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.262268   28949 server.go:148] Starting to listen read-only on 0.0.0.0:10255
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.263947   28949 server.go:296] Adding debug handlers to kubelet server.
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264346   28949 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264399   28949 volume_manager.go:244] The desired_state_of_world populator starts
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264407   28949 volume_manager.go:246] Starting Kubelet Volume Manager
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264421   28949 status_manager.go:140] Starting to sync pod status with apiserver
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264507   28949 container_manager_linux.go:446] [ContainerManager]: Discovered runtime cgroups name: /system.slice/do
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264551   28949 kubelet.go:1768] Starting kubelet main sync loop.
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:50.264557   28949 container_manager_linux.go:603] [ContainerManager]: Fail to get rootfs information unable to find dat
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264589   28949 kubelet.go:1779] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg 
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.264595   28949 qos_container_manager_linux.go:320] [ContainerManager]: Updated QoS cgroup configuration
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.356157   28949 factory.go:355] Registering Docker factory
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:50.356202   28949 manager.go:265] Registration of the rkt container factory failed: unable to communicate with Rkt api 
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: W1219 14:02:50.356355   28949 manager.go:276] Registration of the crio container factory failed: Get http://%2Fvar%2Frun%2Fcrio.soc
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.356373   28949 factory.go:54] Registering systemd factory
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.356653   28949 factory.go:86] Registering Raw factory
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.356926   28949 manager.go:1140] Started watching for new ooms in manager
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.360884   28949 manager.go:311] Starting recovery of all containers
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.364632   28949 kubelet_node_status.go:280] Setting node annotation to enable volume controller attach/detach
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.366552   28949 kubelet_node_status.go:443] Recording NodeHasSufficientDisk event message for node 172.16.48.113
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.366614   28949 kubelet_node_status.go:443] Recording NodeHasSufficientMemory event message for node 172.16.48.113
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.366630   28949 kubelet_node_status.go:443] Recording NodeHasNoDiskPressure event message for node 172.16.48.113
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.366658   28949 kubelet_node_status.go:83] Attempting to register node 172.16.48.113
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.401659   28949 kubelet_node_status.go:134] Node 172.16.48.113 was previously registered
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.401687   28949 kubelet_node_status.go:86] Successfully registered node 172.16.48.113
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.403871   28949 kuberuntime_manager.go:898] updating runtime config through cri with podcidr 10.0.10.0/24
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.404115   28949 docker_service.go:306] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.404439   28949 kubelet_network.go:276] Setting Pod CIDR:  -> 10.0.10.0/24
Dec 19 14:02:50 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:50.404439   28949 kubelet_network.go:276] Setting Pod CIDR:  -> 10.0.10.0/24
Dec 19 14:02:55 jp-blr-r1-node3 kubelet[28949]: I1219 14:02:55.264773   28949 kubelet.go:1779] skipping pod synchronization - [container runtime is down]
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.332637   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.333266   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.333737   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.334338   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.334799   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.335392   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
Dec 19 14:02:56 jp-blr-r1-node3 kubelet[28949]: E1219 14:02:56.335821   28949 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 16; ignoring extra CPUs
""""
