### ISSUE TITLE
There is no node role label of new joining node

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubernetes#55232]
kube version: 1.8.2
docker version: 17.10.0-ce

```
# kubectl get node --show-labels
NAME      STATUS    ROLES     AGE       VERSION   LABELS
uy08-07   Ready     master    7h        v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-07,node-role.kubernetes.io/master=
uy08-08   Ready     <none>    1h        v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-08
```

The node role is `<none>` defaultly?

And I add a label manully like this:
```
# kubectl label node uy08-08 node-role.kubernetes.io/node=
node "uy08-08" labeled

# kubectl get node --show-labels
NAME      STATUS    ROLES     AGE       VERSION   LABELS
uy08-07   Ready     master    7h        v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-07,node-role.kubernetes.io/master=
uy08-08   Ready     node      1h        v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-08,node-role.kubernetes.io/node=
```

Is this a bug?

**Comment by wackxu** [comment]
`kubeadm join` command do not explicitly label the  `role` of node, If it is needed, I can help fix it.

**Comment by liggitt** [comment]
node roles are not yet defined in kubernetes. additionally, nodes should not start labeling themselves with roles (see https://github.com/kubernetes/community/pull/911 for discussion of why labels should be applied to nodes, not self-applied by nodes)

if you would like to request a particular cluster setup tool like kubeadm add role labels to nodes, that feature request could be opened against that tool's repo (https://github.com/kubernetes/kubeadm/, https://github.com/kubernetes/kops/, etc)

**Comment by tsunamireversal** [comment]
I have same issue, I'm trying to understand...
Are you saying that we should manually label nodes as "master" if we want them to behave as master nodes after joining? That they won't do that by themselves?

**Comment by kolikons** [comment]
might be useful https://github.com/kolikons/label-watch
