### ISSUE TITLE
CRD watcher doesn't refecth resource version

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#55230]
/kind bug

**What happened**:
When using an informer there's an error message that appears from time to time:
```
ERROR: logging before flag.Parse: W1106 08:06:18.084082   17360 reflector.go:334] github.com/openshift-evangelists/crd-code-generation/cmd/example/main.go:61: watch of *v1.Database ended with: too old resource version: 197074 (197765)

ERROR: logging before flag.Parse: W1106 08:12:49.127370   17360 reflector.go:334] github.com/openshift-evangelists/crd-code-generation/cmd/example/main.go:61: watch of *v1.Database ended with: too old resource version: 197765 (198293)
```

**What you expected to happen**:

The error not to show up :-)

**How to reproduce it (as minimally and precisely as possible)**:

The bug is difficult to replicate but easy to understand why, the following steps provide an example of a watcher for a CRD.

`go get -d github.com/openshift-evangelists/crd-code-generation`
`cd $GOPATH/src/github.com/openshift-evangelists/crd-code-generation`
`kubectl create -f ./artifacts/`
`wget https://gist.githubusercontent.com/aanm/e1f2486aad5793619b46299ce775befc/raw/79b89a9d16867be2839de1251bd9261a65d875c1/main.go`
`mv main.go ./cmd/example/main.go`
`cd ./cmd/example/`
`gobuild ./...`
`./example -kubeconfig ...`
`# Wait for the messages to appear, it usually takes 6 minutes for a message to appear`

I believe the problem is this particular line https://github.com/kubernetes/kubernetes/blob/v1.8.2/staging/src/k8s.io/client-go/tools/cache/reflector.go#L299

The generated code will create a watcher that does a GET on an endpoint similar to this one:

`http://127.0.0.1:8080/apis/example.com/v1/databases?resourceVersion=242437&timeoutSeconds=481&watch=true`

Since the `resourceVersion` of the *list call* keeps increasing, and the watcher will never receive an event for add / deletion / modification, when the `timeoutSeconds` is reached, the line 307 of `staging/src/k8s.io/client-go/tools/cache/reflector.go` is executed with the previous `resourceVersion`. Since this value is way older than the current one stored by kube-apiserver, the api-server returns the error `too old resource version: 197765 (198293)`.

Shouldn't we refetch the `resourceVersion` after the timeoutseconds is reached?

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.8.1`
- Cloud provider or hardware configuration: VM
- OS (e.g. from /etc/os-release): `ubuntu 16.10`
- Kernel (e.g. `uname -a`): `4.9.17-040917-generic`

/cc @nikhita

**Comment by liggitt** [comment]
getting a "version too old" error and having to start over listing and watching again is normal for watches of slow-moving resources. that's an expected usage pattern

**Comment by joestringer** [comment]
Can we somehow make this error less noisy? Our users often see this in the logs because it prints directly to stderr, and it looks like there's a bug but according to the above it's expected. If it's expected, does it need to be printed?

**Comment by techcet** [comment]
Does this need to an `ERROR`? Would `INFO` or `WARN` suffice for expected behaviour?

**Comment by nikhita** [comment]
> Does this need to an ERROR?

The ERROR is mostly due to https://github.com/kubernetes/kubernetes/issues/17162.
