### ISSUE TITLE
Firewall rule e2e test failing on large clusters due to misconfig

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#55246]
The following e2e is failing continuously on our [5k-node](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness) (and [2k-node](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-large-correctness)) correctness jobs:

```
Firewall rule should have correct firewall rules for e2e cluster
```

due to some misconfiguration:

```
incorrect source ranges [10.64.0.0/11], expected [10.64.0.0/14]: found differences: map[10.64.0.0/11:{}]
```

The job is part of [release-master-blocking suite](https://k8s-testgrid.appspot.com/sig-release-master-blocking) and needs to be fixed asap.

cc @kubernetes/sig-network-bugs

**Comment by shyamjvs** [comment]
/assign

I'll try to take a quick look. But it would be great to have someone from @kubernetes/sig-network-misc help here.

**Comment by shyamjvs** [comment]
Ok.. So the actual source range for the firewall (i.e 10.64.0.0/11) is coming from [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-common.sh#L96) where we're calculating the cluster-ip-range (during cluster startup) based on cluster size.

And the wrong value of `10.64.0.0/14` is used by the e2e-testing framework as a default (see - https://github.com/kubernetes/kubernetes/blob/3aba6451a755852c601eab0af500705242ebfb82/test/e2e/framework/test_context.go#L245). While ideally the right value should've been available through the env var `CLUSTER_IP_RANGE` which overwrites the default (see - https://github.com/kubernetes/kubernetes/blob/3aba6451a755852c601eab0af500705242ebfb82/test/e2e/framework/test_context.go#L360).

Something is wrong around kubetest in setting this env var (or passing the right flag value) to ginkgo.
cc @kubernetes/test-infra-maintainers

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
Umbrella issue - #55194

**Comment by krzyzacy** [comment]
hummm we should print out the ip range in kubetest, as https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-common.sh#L98

**Comment by shyamjvs** [comment]
This issue has been fixed after my above fixes. Latest green run - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/26
/close
