### ISSUE TITLE
release-1.8 GKE test failure "Services should work after restarting apiserver"

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#55244]
In the [release1.8 blocking test suite](https://k8s-testgrid.appspot.com/sig-release-1.8-blocking#gci-gke-serial-1.8). "[sig-network] Services should work after restarting apiserver [Disruptive]" has started failing regularly with the error:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:434
Nov  4 02:53:35.323: error restarting apiserver: error running gcloud [container clusters --project=k8s-gke-upg-c1-4-g1-6-up-clu --zone=us-central1-b upgrade e2e-856 --master --cluster-version=1.8.3-beta.0.88+dc6c4c5dcebb7e --quiet]; got error exit status 1, stdout "", stderr "Upgrading e2e-856...\n.....done.\nERROR: (gcloud.container.clusters.upgrade) Operation [<Operation\n endTime: u'2017-11-04T02:53:29.555870594Z'\n name: u'operation-1509764009232-95e55dde'\n operationType: OperationTypeValueValuesEnum(UPGRADE_MASTER, 3)\n selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/433788295746/zones/us-central1-b/operations/operation-1509764009232-95e55dde'\n startTime: u'2017-11-04T02:53:29.232057635Z'\n status: StatusValueValuesEnum(DONE, 3)\n statusMessage: u'Patch failed'\n targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/433788295746/zones/us-central1-b/clusters/e2e-856'\n zone: u'us-central1-b'>] finished with error: Patch failed\n"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:414
```

The first occurance I can find is in build [841](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial-stable1/841). But it has been failing more consistently since around build [856](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial-stable1/856).

**Comment by jpbetz** [comment]
cc @tallclair

**Comment by bboreham** [comment]
That's a `gcloud` error; the code only wants to restart the api-server but from the comments there is no way to do that on GKE so it does an "upgrade" to the same version.

The error is nothing to do with networking.

**Comment by enisoc** [comment]
This may have the same root cause as #55189. We're having problems with almost all GKE e2e test due to clusters getting stuck during startup.

**Comment by jpbetz** [comment]
Thanks @bboreham, removing sig-networking label.

**Comment by jpbetz** [comment]
GKE upgrades now work and tests are passing agian.
