### ISSUE TITLE
kubectl aging plugin does not respect current namespace

### ISSUE THREAD

**Issue by jojje** [kubernetes/kubernetes#55255]
/kind bug
/sig cli

**What happened**:
Tried to list the age of pods in the `kube-system` namespace in an otherwise empty cluster

    $ kubectl --namespace kube-system plugin aging
    The Magnificent Aging Plugin.
    No pods

**What you expected to happen**:
That the pods in the `kube-system` namespace would have been listed

**How to reproduce it (as minimally and precisely as possible)**:

1. Copy the aging.rb and plugin.yml from https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/plugins/examples/aging into `${HOME}/.kube/plugins/aging/`.
2. Run the command: `kubectl --namespace kube-system plugin aging`

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration: minikube & GKE
- OS (e.g. from /etc/os-release): Mac OSX El Capitan
- Kernel (e.g. `uname -a`): Darwin Kernel Version 15.6.0
- Install tools: Google Cloud SDK

**Comment by shiywang** [comment]
hi @jojje for cli issue, could you please file it in this repo https://github.com/kubernetes/kubectl next time ? thanks !!

**Comment by jojje** [comment]
@shiywang Will the k8s github bots be able to resolve `#<issue number>` references in commit messages made in kubernetes/kubernetes PRs be able to find the corresponding issue ticket in that _other project_?

_Semi-OT but related:_
I know there's an overall intention to refactoring k8s proper into many distinct projects, so it would be helpful if either the contributor guide contained a mapping of each and every module making up a k8s release with its corresponding github project and protocol governing the component. Or if each directory (module) in kubernetes/kubernetes contains its own README.md explaining the contribution protocol. 

Right now documentation and information about ownership, contribution and protocols of various project modules are a sprawl and a bit of a mess, creating a significant barrier to entry (contribution). What's the proper place and form to discuss these sort of things?

**Comment by shiywang** [comment]
@jojje thanks, I think those are some good suggestions,  as far as I know you could send an email to our mailling-list(google-groups) or cc @kubernetes/sig-contributor-experience-proposals ?
