### ISSUE TITLE
Incorrect QoS class for Pod with no resource request/limit

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#55278]
/kind bug
/sig node

**What happened**:

A Pod with no resource request and limit should be assigned `BestEffort` QoS class. 

**What you expected to happen**:

Instead it should be assigned `Burstable` QoS.

**How to reproduce it (as minimally and precisely as possible)**:

Created an AWS cluster as:

```
kops create cluster  \
 --name example.cluster.k8s.local   \
--master-count 3   \
--node-count 5  \
 --zones us-west-2a,us-west-2b,us-west-2c   \
--yes
```

Deployed a Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```

Resources are shown as:

```
$ kubectl get pod/nginx-pod -o jsonpath={.spec.containers[].resources}
map[requests:map[cpu:100m]]
```

With no request and limit resources explicitly specified, the Pod is assigned the QoS class of `Burstable`. This was verified as:

```
$ kubectl get pod/nginx-pod -o jsonpath={.status.qosClass}
Burstable
```

This should have been `BestEffort` instead.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
> map[requests:map[cpu:100m]]

it's 0.1 cpu in request.

**Comment by arun-gupta** [comment]
@k82cn the configuration file had no requests/limits defined. Is this a default value assigned to all resources? Wondering when is `BestEffort` QoS ever assigned to a resource?

**Comment by uday1bhanu** [comment]
HI @arun-gupta,
I think this might have been fixed with 1.8.0 version. I tried the same pod spec with minikube(**v1.8.0**) and the `kubectl get pod/nginx-pod -o jsonpath={.status.qosClass}` shows **BestEffort** as expected.

**Comment by wenslayer** [comment]
I'm still seeing this bug with 1.8.4:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:12:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ cat templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

$ kubectl apply -f templates/pod.yaml
pod "nginx-pod" created

$ kubectl get pod/nginx-pod -o jsonpath={.spec.containers[].resources}
map[requests:map[cpu:100m]]

$ kubectl get pod/nginx-pod -o jsonpath={.status.qosClass}
Burstable
```

**Comment by cji** [comment]
Could this be due to the ([undocumented](https://github.com/kubernetes/kubernetes/issues/34401)) resource request default of 100m causing [this check to fail](https://github.com/kubernetes/kubernetes/blob/dd9981d038012c120525c9e6df98b3beb3ef19e1/pkg/apis/core/helper/qos/qos.go#L80-L81) which then falls through to [Burstable](https://github.com/kubernetes/kubernetes/blob/dd9981d038012c120525c9e6df98b3beb3ef19e1/pkg/apis/core/v1/helper/qos/qos.go#L97)?

**Comment by andyrhee** [comment]
I think cji is right.  This is more of a kops (undocumented) feature than a k8s'.  In fact, minikube doesn't have the same feature.  Also, this feature affects only the **default** namespace created by kops:
```
$ kubectl describe limits -n default
Name:       limits
Namespace:  default
Type        Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---  ---  ---------------  -------------  -----------------------
Container   cpu       -    -    100m             -              -

$ kubectl describe limits -n kube-system
$
```

**Comment by christopherhein** [comment]
@arun-gupta I was able to update our documentation about using limits and BestEffort base on @andyrhee's comment. This should probably be closed.

**Comment by arun-gupta** [comment]
Thanks @christopherhein, will close!
