### ISSUE TITLE
Using --show-labels with incompatible ‘kubectl get’ arguments should error out

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#55290]
Passing `--show-labels` to the following `kubectl get` commands do not make a difference, because the printer is not the table printer:

- `kubectl get pods -o=yaml --show-labels`
- `kubectl get pods -o=json --show-labels`
- `kubectl get pods -o=name --show-labels`
- ...

Current behavior is that the `--show-labels` simply doesn’t make a difference since it’s not applicable.

In these cases, we must error out with a message like _“--show-labels option cannot be used with yaml printer”_.

I think it’s sane to error out when usage of a flag is always going to be incompatible in the presence (or some values–) of certain flags.

A caveat is that `--show-labels` is valid in the context of `-o=wide` or `-o=custom-columns=...` options.

/sig cli
/kind bug
Version: kubectl v1.8.2

**Comment by charrywanganthony** [comment]
I would like to fix it ASAP.

**Comment by charrywanganthony** [comment]
I found `--show-kind` seems have the same problem. @ahmetb
