### ISSUE TITLE
Flex volume use wrong device path to mount volume after node or cluster reboot and device path change

### ISSUE THREAD

**Issue by jolestar** [kubernetes/kubernetes#55314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
1. kubernetes store node's volume and devicePath in etcd.

such as:

| volumeID| pv  | devicePath|
|----------|----|-----------|
|vol-1  | pvc-1 |/dev/vdc|
|vol-2 | pvc-2 |/dev/vde|

2. when cluster or node reboot (such as machine power off)，In some cases，devicePath will change. 

such as:

| volumeID| pv  | devicePath|
|----------|----|-----------|
|vol-1  | pvc-1 |/dev/vde|
|vol-2 | pvc-2 |/dev/vdc|

But kubelet still use old device to volume mapping in etcd.
Controller-manager call flex volume isattached command with arg vol-1, flex volume plugin return true.
Kubelet call flex volume waitforattach command with /dev/vdc and vol-1, flex volume also return true(Because vol-1 is attached and device path /dev/vdc does exist). 
So, kubelet call flex volume mountdevice command to mount pvc-1 dir to /dev/vdc,  but /dev/vdc is actually vol-2. 
This bug will result in pv is not available or data corruption.

**What you expected to happen**:

Provide a mechanism to update the mapping between volume and device after reboot.

**How to reproduce it (as minimally and precisely as possible)**:

reboot node or cluster, in some condition.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.9
- Cloud provider or hardware configuration: qingcloud
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`):  4.4.0-97-generic
- Install tools:
- Others:

**Comment by taherv** [comment]
If you are supporting attach/detach API flexvol (aka attachable plugins) then ideally you should not return the actual devicename (/dev/vdx) from the attach call. I know I am differing with the documentation here.
Attach should return enough information about the volume that you can then find the right path during the mountdevice call. For e.g., for a SCSI drive, you can return something like Bus/Adapter/Target/Lun.
The return value of attach is kinda opaque to Kubernetes or FlexVolume, it will just get given back to you in other api calls like isattached or mountdevice.


Pinging @chakri-nelluri to confirm/deny my explanation .....

**Comment by jolestar** [comment]
@taherv  If there is no other way, this is also a method. I considered return device uuid，and flex plugin use uuid to find real device path, then use mount util (SafeFormatAndMount) to mount device . i

**Comment by mtanino** [comment]
@taherv @jolestar 

>> For e.g., for a SCSI drive, you can return something like Bus/Adapter/Target/Lun.

FC plugin supports following parameters to avoid to use unexpected device across kubelet node reboot.
- WWN + lun => find device from /dev/disk/by-path
- WWID => /dev/disk/by-id

I didn't  see current flex plugin implementation, seems flex needs similar functionality?

**Comment by jolestar** [comment]
@mtanino  yes, flex also needs that functionality. Otherwise it is difficult to write a correct flex plugin.

**Comment by taherv** [comment]
You can still implement this in your flexvol plugin, the API allows you to do what I suggested ....

**Comment by chakri-nelluri** [comment]
Infra code today expects device path from an attach call.
https://github.com/kubernetes/kubernetes/blob/b983cee8b8b9d84bf397212a0b5d354ffa4071e5/pkg/volume/volume.go#L165

But, I agree with @taherv. AFAIK the field is not interpreted by infra. @jingxu97 do you see any issues with it?

@jolestar in today's flow, the assumption is volume will not be automatically attached on a reboot and the attach will be re-triggered by controller manager after isAttached returns false.
The workload can migrate from node to another node (at least it used to) when a node reboots and having the volume reattach on reboot breaks that flow.

**Comment by jolestar** [comment]
@chakri-nelluri  I understand, our cloud infra will attach the volume automatically, so that's causing the problem. Our current fix is the attach volume method no longer returns the real device path, each time mountdevice, flex plugin calls the IaaS API to get the actual device path.
