### ISSUE TITLE
Federated service discovery failed in hybrid cloud: OpenStack + GKE

### ISSUE THREAD

**Issue by arthur0** [kubernetes/kubernetes#55326]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Following the  [guide](https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/) to set up federation with kubefed and [another one](https://kubernetes.io/docs/tasks/federation/set-up-coredns-provider-federation/) to set up CoreDNS as DNS provider, is not possible to have service discovery based on region and availability zone for the OpenStack cluster.
```
|   Clusters   |   Provider    |  Region      | Zone           | FCP | 
|--------------|---------------|--------------|----------------|-----|
| os-br        |   OpenStack   | RegionOne    | nova           |  *  |
| gke-us       |   GCE         | us-central1  | us-central1-a  |     |
```
The deployment and service are correctly spread in the two clusters. 
The `status.loadBalancer.ingress` for the service in the `os-br` cluster has two IPs, but it's already fixed by this [PR](https://github.com/kubernetes/kubernetes/pull/52609).
```
$ kubectl get svc -n ns --context gke-us
NAME       TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)
nodename   LoadBalancer   10.11.249.249   104.154.142.100   80:31814/TCP
$ kubectl get svc -n ns --context os-br
NAME       TYPE           CLUSTER-IP     EXTERNAL-IP                 PORT(S) 
nodename   LoadBalancer   10.107.93.68   10.11.4.210,150.165.85.10   80:31240/TCP
```
For the following scenarios, I ran the busybox pod in the same namespace as my service:
`kubectl -n ns exec -ti busybox -- sh`

**Scenario 1: Without region and zone.**
```
/ # nslookup nodename.ns.federation.svc.example.com
Address 1: 104.154.142.100 100.142.154.104.bc.googleusercontent.com
Address 2: 150.165.85.10
Address 3: 10.11.4.210
```

**Scenario 2: With region and zone**
```
/ # nslookup nodename.ns.federation.svc.us-central1-a.us-central1.example.com
Address 1: 104.154.142.100 100.142.154.104.bc.googleusercontent.com

/ # nslookup nodename.ns.federation.svc.nova.regionone.example.com
nslookup: can't resolve 'nodename.ns.federation.svc.nova.regionone.example.com'
```
**Scenario 3: Only region**
```
/ # nslookup nodename.ns.federation.svc.us-central1.example.com
Address 1: 104.154.142.100 100.142.154.104.bc.googleusercontent.com

/ # nslookup nodename.ns.federation.svc.regionone.example.com
nslookup: can't resolve 'nodename.ns.federation.svc.regionone.example.com'
```

**What you expected to happen**:
For the three scenarios, I don't understand the `100.142.154.104.bc.googleusercontent.com` register in the service hosted in GCE.
I think the `Address 1` should have only one register `104.154.142.100` and even if the `100.142.154.104.bc.googleusercontent.com` is a valid registry, it should be added in as a new address.

For scenarios 2 and 3 I expect to have service discovery, based on region and zone, for services hosted in OpenStack cluster.

**How to reproduce it (as minimally and precisely as possible)**:
In the OpenStack cluster:
[1](https://kubernetes.io/docs/tasks/federation/set-up-coredns-provider-federation/) Deploy etcd-operator and CoreDNS
[2](https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/) Set up federation using Kubefed

**Anything else we need to know?**:
The etcd-operator seems healthy:
```
kubectl run --rm -i --tty fun --image quay.io/coreos/etcd --restart=Never -- /bin/sh
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 put foo bar
OK
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 get foo
foo
bar
/ # ETCDCTL_API=3 etcdctl --endpoints http://etcd-cluster-client.default:2379 del foo
1
```

Initially, I thought the problem might be if the coredns version, so I tried with newest versions, but I got the same result. My current coredns chart config:
```
replicaCount: 3
image:
  repository: coredns/coredns
  tag: "011"
  pullPolicy: IfNotPresent
isClusterService: false
serviceType: "NodePort"
middleware:
  prometheus:
    enabled: false
  errors:
    enabled: true
    file: "stdout"
  kubernetes:
    enabled: false
  etcd:
    enabled: true
    zones:
    - "example.com."
    endpoint: "http://etcd-cluster-client.default:2379"
```

Logs from Federation Controller Manager: [fed-controller-mannager.txt](https://github.com/kubernetes/kubernetes/files/1454774/fed-controller-mannager.txt)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version --context os-br
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl version --context gke-us
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-gke.1", GitCommit:"aba494e68a76583d2d7d1b9c97e4a97a19c3a920", GitTreeState:"clean", BuildDate:"2017-10-27T23:54:39Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
cc @shashidharatd 
/sig multicluster
/sig openstack

**Comment by dims** [comment]
/remove-sig openstack

not really related to any change in openstack code

**Comment by arthur0** [comment]
I found the problem.
The OpenStack regions are case sensitive (and the default region is `RegionOne`).
The Kubernetes Service Discovery is DNS-based and case sensitive does not make sense in this context.
So the Cluster region (`apiVersion: federation/v1beta1`) is created using camel case too. 
```
$ kubectl get cluster <openstack> -o yaml --context federation | grep region
  region: RegionOne
$ kubectl get cluster <gce> -o yaml --context federation | grep region
  region: asia-east1
```
I'm not sure if a change to fix this bug should be made on the OpenStack provider or the federation side.

**Comment by irfanurrehman** [comment]
This issue was labelled with sig/multicluster and is thus moved over to kubernetes/federation#218.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
