### ISSUE TITLE
Kube-Proxy blocks ipv6 nodePorts when running in ipv4 mode

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#55337]
/kind bug

**What happened**:

Kube-Proxy binds to IPv6 nodeports

**What you expected to happen**:

Kube-Proxy not doing anything ipv6-related when running with `--bind-address=0.0.0.0` arg

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Kube-Proxy with `--bind-address=0.0.0.0` arg
2. Create a nodeport service
3. Run `ss -6ltpn|grep kube-proxy`

**Anything else we need to know?**:

`kube-proxy:v1.9.0-alpha.1.2092_444a161d227565`

**Comment by Lion-Wei** [comment]
It says `bind-address` is the IP address for kube-proxy to server on, set to 0.0.0.0 for all interfaces... I'm not sure whether if set `bind-address=0.0.0.0`, then kube-proxy should blocks ipv6 nodeports,,,

**Comment by alvaroaleman** [comment]
I am not sure I understand your point. If run with `bind-address=0.0.0.0`, kube-proxy does not create any iptables rules for ipv6, it just listens on the ipv6  node ports which means they can not be used.

When kube-proxy is run with `bind-address=::` it will create iptables rules for both ipv4 and ipv6. From that behavior I assumed that `bind-address=0.0.0.0` means use ipv4 only. Correct me if I am wrong there.
