### ISSUE TITLE
Scheduler should not use an assignment filter when installing event handlers for Pods

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#55333]
Scheduler uses filters [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L167) and [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L187) when installing event handlers on Pod informers. The filters separate assigned and unassigned pods. However, this causes scheduler to receive a non-intuitive sequence of events when a Pod is scheduled and bound to a node. Scheduler first receives a "delete" event for the unassigned pod followed by an "add" event for the assigned pod. This is confusing and could cause unexpected behavior in future developments.
These events are sent due to [the logic of cache controller filter when handling updates](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/controller.go#L231).

In order to get an update event when a pod is scheduled, we need to remove the filtering on assigned vs. unassigned pods and check the assignment status of Pods in the handler functions.

/kind feature
/sig scheduling

**Comment by lichuqiang** [comment]
> This is confusing and could cause unexpected behavior in future developments.

Not quite sure about your meaning here. Could you give it a practical use case?

**Comment by bsalamat** [comment]
@lichuqiang As I have already mentioned, this is already confusing, because when a pod is scheduled, we see a delete followed by an add events for the pod, while we should instead see an update for the pod.

**Comment by guangxuli** [comment]
After practice in my local cluster, confirm that the event order looks like: delete->add->udpate, which consistent with @bsalamat has mentioned.

**Comment by lichuqiang** [comment]
I have no doubt about the behavior in event, just a little doubt about part of 
> and could cause unexpected behavior in future developments.

That is, whether the issue is motivated by practical use case or is of structure optimization:)

**Comment by bsalamat** [comment]
@lichuqiang What I meant is that this behavior is not obvious and people who are not aware of it may write code with the assumption that the update event handler is invoked when a pod is assigned. This could potentially introduce subtle bugs which are hard to debug.

**Comment by lichuqiang** [comment]
@bsalamat Oh, Gotcha. Many thanks for explanation.

**Comment by guangxuli** [comment]
hi @bsalamat do you have plan to fix this confusing, if not, i'd like to go deeply into details and fix this confusing. :)

**Comment by bsalamat** [comment]
@guangxuli I am pretty occupied. I actually filed the issue with the hope that someone would help fix the issue. I am glad that you want to work on it. I will be happy to review PRs. Thanks!

/assign @guangxuli

**Comment by guangxuli** [comment]
@bsalamat i have to confirm that if we remove the filtering on unassigned and assigned pod, how we distinguish when to delete from queue and when to add to cache. Do you mean move all these action to  update handler?

**Comment by bsalamat** [comment]
@guangxuli If we remove filtering, we will see an update for a pod that goes from unassigned to assigned. Then we can compare and find what has changed for the pod and call appropriate functions. That said and after working more closely with the event handlers in the past couple of weeks, I think the way they are set up today (existing code) is probably more efficient. The alternative of looking at the pods and comparing them with their old state is less efficient. So, I think we can leave the code as is and just add a comment explaining the events we receive when an unassigned pod is assigned.

**Comment by guangxuli** [comment]
okay, got it, thanks, hmm, i think the event we receive when an unassigned pod is assigned is in the[ here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/controller.go#L238), do you mean we should add the comments to function `addPodToCache` or other places?

**Comment by bsalamat** [comment]
I think we should add the comment in factory.go somewhere around [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L164) and mention the events that we receive when an unassigned pod is assigned.

**Comment by bsalamat** [comment]
Actually, I think we don't need to fix this (as explained in [my comment](https://github.com/kubernetes/kubernetes/issues/55333#issuecomment-345549189) above). I am going to close this issue.
