### ISSUE TITLE
Dockershim doesn't consider seccomp profile root?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#55359]
While auditing absolute/relative path behavior in the Kubelet, I came across this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers_linux.go#L61-L66

```
	if !strings.HasPrefix(seccompProfile, "localhost/") {
		return nil, fmt.Errorf("unknown seccomp profile option: %s", seccompProfile)
	}

	fname := strings.TrimPrefix(seccompProfile, "localhost/") // by pod annotation validation, name is a valid subpath
	file, err := ioutil.ReadFile(filepath.FromSlash(fname))
```

It looks like it just ignores the root directory altogether, and reads relative to the Kubelet's CWD.

/cc @tallclair @yujuhong @feiskyer

**Comment by yujuhong** [comment]
@feiskyer could you take a look? Thanks!

**Comment by feiskyer** [comment]
@mtaufen Not really, the seccompProfile is the full path passed from CRI:

https://github.com/kubernetes/kubernetes/blob/338ee7f5d56eb506082b7683566440ec1b271f8c/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L217-L223

**Comment by feiskyer** [comment]
Hmm, comments is wrong. Will send to PR to fix the comments.

**Comment by feiskyer** [comment]
@tallclair do you mean add a filed in podspec instead of annoations?

**Comment by tallclair** [comment]
Isn't it already a field?

I meant that instead of a `string seccomp_profile_path` we have something like (pseudocode):
```go
seccomp *seccomp_spec

type seccomp_spec struct {
  // profile name, copied verbatim from k8s api
  profile_name string
  // absolute path to load the profile from. empty for hardcoded profiles.
  load_path *string
}
```

**Comment by feiskyer** [comment]
@tallclair It's a field in CRI already, but still comes from kubernetes pod annotations, not a field of PodSpec.

**Comment by mtaufen** [comment]
@feiskyer so are you saying the annotation now has to contain an absolute path on the node? Is there validation for this somewhere? It looks like the code in `pkg/kubelet/dockershim/helpers_linux.go` just trims the prefix, including the `/` after localhost, and then just reads that path, which would be relative because it doesn't have a leading `/`. AFAICT from messing around in the go playground, nothing there adds a leading `/`. https://play.golang.org/p/_A6DBoSG1V
