### ISSUE TITLE
Proposal: Let K8s support change internal storage configMap K/V to external config server

### ISSUE THREAD

**Issue by xiaods** [kubernetes/kubernetes#55368]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
we are working on build a config server with k8s, we are proposal enable a external config server to support store configMap based on external config Server.  it benefit for enterprise config management purpose. 

**background**: 
This configuration data can then be used as:
* Environment variables
* Command-line arguments for a container
* Config files in a volume

kubelet have no --from-config-server flag to change configmap store logic to external config server.

**What you expected to happen**:

vim pkg/kubelet/configmap/configmap_manager.go + 66
```
66 func (s *simpleConfigMapManager) GetConfigMap(namespace, name string) (*v1.ConfigMap, error) {

```

we know the kubelet can parse the configMap's logic. So i want to add a parameter to let kubelet to know the node can support fetch configs from external config server.

**Anything else we need to know?**:

anyone can do me a favor to give some advice, thanks a lot.

**Environment**:
- Kubernetes version (use `kubectl version`): upstream
- Cloud provider or hardware configuration:  no
- OS (e.g. from /etc/os-release): macos
- Kernel (e.g. `uname -a`):  N/A
- Install tools:  Linux
- Others: N/A

**Comment by duffqiu** [comment]
![configmap uml-2](https://user-images.githubusercontent.com/5739682/32685285-0ed07668-c6c9-11e7-8942-1463abd7eb11.png)

Something like this
