### ISSUE TITLE
initialresources admission plugin flags pollute all commands

### ISSUE THREAD

**Issue by wackxu** [kubernetes/kubernetes#55374]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 kind feature

**What happened**:

The same problem as issue https://github.com/kubernetes/kubernetes/issues/55284

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mindprince** [comment]
/close
Removed in https://github.com/kubernetes/kubernetes/pull/58784
