### ISSUE TITLE
get.go doesn't handle metav1.Status returned by rest.client

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#55409]
Discovered here: https://github.com/openshift/kubernetes/pull/43/commits/0d5291cc63b7b3655b11bc15e8afb9a078049d09

The metav1.Status causing a panic on get projectrequests.

**Comment by mfojtik** [comment]
@smarterclayton as requested.

**Comment by smarterclayton** [comment]
I plan on fixing this by tolerating it in the places it needs to be tolerated by making clients have to exlpcitily ask for unstructured content when they expect it.  That would lead to v1.status being converted to unstructured on demand in the edge case where it appears.
