### ISSUE TITLE
DockerValidator should use the CRI, not the Docker API

### ISSUE THREAD

**Issue by runcom** [kubernetes/kubernetes#55414]
The DockerValidator in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/docker_validator.go which is used by kubeadm preflights checks is using the Docker API directly. With kubernetes/kubernetes#55055 we're moving dockerisms to use crictl and the CRI. The DockerValidator should use crictl to gather Docker version via the CRI Version endpoint. However, the CRI isn't exposing the docker graphdriver (hence the need for an issue to track). We need to understand if and how those additional info are to be exported by the CRI.

/cc @luxas @Random-Liu @feiskyer

**Comment by runcom** [comment]
@kubernetes/sig-node-bugs

**Comment by runcom** [comment]
I'm working on this.

**Comment by feiskyer** [comment]
+1 for switching to CRI, e.g. return such information in StatusResponse.Info. 

However, the CRI API only defines a map, which doesn' t include pre-defined keys for things such as graphdriver.  Since graphdriver is used in validation, I think we should think it as a required info.

@Random-Liu @runcom Do you think we should pre-define some welll-knows keys for this?

**Comment by runcom** [comment]
@feiskyer What I had in mind was a best effort using the Status.Response.Info. We can define some keys for graphdriver but I won't have them mandatory, I can work on this BTW.

**Comment by feiskyer** [comment]
If not mandatory, how to pass kubeadm preflights checks? Just omit the check for non-docker runtime?

**Comment by runcom** [comment]
> Just omit the check for non-docker runtime?

it's already omitted for non-docker runtime, but I thought we could make the check via the CRI w/o calling docker directly.

**Comment by luxas** [comment]
/lifecycle frozen
Reopening this issue.
@runcom @Random-Liu @feiskyer is there anything we can/should do here at this moment in time?
xref https://github.com/kubernetes/kubeadm/issues/533

**Comment by ehashman** [comment]
/sig cluster-lifecycle

Closed in https://github.com/kubernetes/kubernetes/pull/84718 when this file was removed.

/close
