### ISSUE TITLE
kube-proxy: session affinity stops working when ESIPP=Local

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#55429]
/kind bug

https://github.com/kubernetes/kubernetes/issues/50866#issuecomment-343283650

**What happened**:
Traffic from the same client IP does not get routed to the same endpoint when externalTrafficPolicy=Local and sessionAffinity=ClientIP

**Comment by MrHohn** [comment]
Sent out a fix on https://github.com/kubernetes/kubernetes/pull/55519.
