### ISSUE TITLE
kubectl exec does not respect readOnlyRootFilesystem

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#55428]
On v1.5.7

execing into a container with readOnlyRootFilesystem leaves the filesystem writeable
... it works fine when the container is regularly booted though a kubernetes Deployment

**Comment by containscafeine** [comment]
Hey @grosser, I was not able to reproduce this on v1.5.7.

I tried the following deployment file -
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd
  name: httpd
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd
      name: httpd
    spec:
      containers:
      - args:
        - localhost
        command:
        - ping
        image: centos/httpd
        name: httpd
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
```

I could not write anything to the running container after execing into it -

```console
$ kubectl exec -it httpd-1679090448-lx5p0 bash
[root@httpd-1679090448-lx5p0 /]# touch hi
touch: cannot touch 'hi': Read-only file system
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.7-dirty", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"dirty", BuildDate:"2017-11-14T09:54:28Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.7-dirty", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"dirty", BuildDate:"2017-11-14T09:54:28Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

I also tried -
- deploying only the pod from a file
- deploying using `kubectl run` command
- deploying without any `securityContext` set, and then later use `kubectl edit` to set it
All of the above worked as expected and the filesystem remained read only.

Could you please help with your environment and how to reproduce the issue?

**Comment by grosser** [comment]
thx for checking ... and sorry for the noise ... I'm unable to reproduce now ... so I must have done something wrong when first deploying that pod :(
