### ISSUE TITLE
Multiple ResourceQuota in a namespace should not be allowed

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#55430]
/kind bug
/sig api-machinery

**What happened**:

Could create multiple ResourceQuota objects

**What you expected to happen**:

https://kubernetes.io/docs/concepts/policy/resource-quotas/ states `There should be at most one ResourceQuota object in a namespace.`

kubectl should fault if more than one `ResourceQuota` is attempted to be created.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl create quota foo --hard=pods=100
resourcequota "foo" created
$ kubectl create quota bar --hard=pods=100
resourcequota "bar" created
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mbohlool** [comment]
cc @derekwaynecarr

**Comment by arun-gupta** [comment]
Seems like this is a valid use case as discussed at https://github.com/kubernetes/kubernetes/issues/23698 but the docs have not been updated yet.
