### ISSUE TITLE
Blank tokens in  `--token-auth-file`

### ISSUE THREAD

**Issue by bkochendorfer** [kubernetes/kubernetes#55434]
> /kind feature

**What happened**:
While following through this tls [bootstrapping guide](https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/#token-authentication-file) I accidentally made a file with blank tokens. (format was `,kubelet,kubelet`). I noticed that there was a particular format recommended in this guide but I don’t see that we do any verification of the token when [loading the file](https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/token/tokenfile/tokenfile.go#L43). I also noted that you can enter any string as a token and authenticate.

**What you expected to happen**:
I'd expect the apiserver to verify the token length, or at least warn if no token is provided. I did verify that when the token is set to blank a user is not able to auth by providing an empty string as the token in `~.kube/config`.

**How to reproduce it (as minimally and precisely as possible)**:
Run the `kube-apiserver` with `--token-auth-file` pointing to a file with the value `,kubectl,kubectl`

**Anything else we need to know?**:
Nope.

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```bash
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
I will do this verify.
