### ISSUE TITLE
CheckpointNotFoundError is not returned on GetCheckpoint on error

### ISSUE THREAD

**Issue by madhanrm** [kubernetes/kubernetes#55446]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
ErrKeyNotFound error is thrown when checkpoint is not found.
Behavior broken by last commit 2fd59d9960c87c32910fe9d275d835d979cbc553

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stewart-yu** [comment]
can you provide how to reproduce it?

**Comment by yujuhong** [comment]
Will send a fix shortly.

**Comment by madhanrm** [comment]
@yujuhong  Thanks. I was about to raise a PR. Validating on windows. Somehow missed it on previous validation

**Comment by madhanrm** [comment]
@yujuhong , I need this fix for the following function to return null and no error when checkpoint is not found.

// GetPodPortMappings returns the port mappings of the given podSandbox ID.
func (ds *dockerService) GetPodPortMappings(podSandboxID string) ([]*hostport.PortMapping, error) {
        // TODO: get portmappings from docker labels for backward compatibility
        checkpoint, err := ds.checkpointHandler.GetCheckpoint(podSandboxID)
        // Return empty portMappings if checkpoint is not found
        if err != nil {
                return nil, err
        }

Any reason why the PR was closed?

**Comment by yujuhong** [comment]
@madhanrm  #55641 changed the code completely and the error is no longer needed.

**Comment by madhanrm** [comment]
@yujuhong  The error I was getting is "key not found" ie checkpoint doens;t actually exist.

Am expecting to get a nil error for that in the GetPodPortMappings function. Let me try out the latest code to validate this.

**Comment by madhanrm** [comment]
@yujuhong  If the error code is removed completely, should the below code be fixed to take care of the comment? "// Return empty portMappings if checkpoint is not found" 
Can we atleast check for "KeyNotFound" and return nil error?

The CNI network call would fail in this case, which is breaking CNI in windows.

checkpoint, err := ds.checkpointHandler.GetCheckpoint(podSandboxID) 
 	// Return empty portMappings if checkpoint is not found 
 	if err != nil { 
-		if err == errors.CheckpointNotFoundError { 
-			glog.Warningf("Failed to retrieve checkpoint for sandbox %q: %v", podSandboxID, err) 
-			return nil, nil 
-		} 
 		return nil, err

**Comment by madhanrm** [comment]
Closing this issue, and opened #55819  to continue tracking this.
