### ISSUE TITLE
`kube-apiserver` should export readiness information

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#55453]
`kube-apiserver` should have a concept of whether it is currently ready for connections or not. It could say not when it is shutting down, initializing, or disconnected from etcd. This can be checked by kubelet and fed to a load balancer to keep clients from attempting to connect to a replica which is not ready.

#54849 adds a more graceful shutdown path, we should build on that.

**Comment by lavalamp** [comment]
cc @mml

**Comment by yliaog** [comment]
cc @yliaog

**Comment by mml** [comment]
/remove-lifecycle stale

We need to be very clear about cases when we would export this and how it might effect health-checking (and kill-and-restart logic).  We don't want to get so clever that we hamstring our ability to kill broken processes.

**Comment by roycaihw** [comment]
/reopen
/remove-lifecycle rotten
cc @cheftako

**Comment by mml** [comment]
/remove-lifecycle stale

*From: *fejta-bot <notifications@github.com>
*Date: *Wed, May 15, 2019 at 2:07 PM
*To: *kubernetes/kubernetes
*Cc: *Matt Liggett, Mention

Issues go stale after 90d of inactivity.
