### ISSUE TITLE
Pods scale up to a random number

### ISSUE THREAD

**Issue by fieryvova** [kubernetes/kubernetes#55477]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I was following [horizontal-pod-autoscale-walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ "hpa walkthrough").

In step 2 I set `--max=1` instead of `--max=10`.
After going through step 3, there were 4 pods running php-apache instead of 1.

The interesting thing is that if I set `--max=2` the pods will scale up to 2.

<details><summary>kubectl get events</summary><p>
<pre>11         Successfully pulled image "gcr.io/google_containers/hpa-example"
4m         4m          1         php-apache-253401759-0sn8r   Pod                       spec.containers{php-apache}   Normal    Created                        kubelet, kubenode11         Created container  
4m         4m          1         php-apache-253401759-0sn8r   Pod                       spec.containers{php-apache}   Normal    Started                        kubelet, kubenode11         Started container  
28s        28s         1         php-apache-253401759-4j454   Pod                                                     Normal    Scheduled                      default-scheduler           Successfully assigned php-apache-253401759-4j454 to kubenode13
28s        28s         1         php-apache-253401759-4j454   Pod                                                     Normal    SuccessfulMountVolume          kubelet, kubenode13         MountVolume.SetUp succeeded for volume "default-token-q78zs"
27s        27s         1         php-apache-253401759-4j454   Pod                       spec.containers{php-apache}   Normal    Pulling                        kubelet, kubenode13         pulling image "gcr.io/google_containers/hpa-example"
28s        28s         1         php-apache-253401759-9qfrp   Pod                                                     Normal    Scheduled                      default-scheduler           Successfully assigned php-apache-253401759-9qfrp to kubenode12
28s        28s         1         php-apache-253401759-9qfrp   Pod                                                     Normal    SuccessfulMountVolume          kubelet, kubenode12         MountVolume.SetUp succeeded for volume "default-token-q78zs"
27s        27s         1         php-apache-253401759-9qfrp   Pod                       spec.containers{php-apache}   Normal    Pulling                        kubelet, kubenode12         pulling image "gcr.io/google_containers/hpa-example"
28s        28s         1         php-apache-253401759-f1c4l   Pod                                                     Normal    Scheduled                      default-scheduler           Successfully assigned php-apache-253401759-f1c4l to kubenode13
28s        28s         1         php-apache-253401759-f1c4l   Pod                                                     Normal    SuccessfulMountVolume          kubelet, kubenode13         MountVolume.SetUp succeeded for volume "default-token-q78zs"
27s        27s         1         php-apache-253401759-f1c4l   Pod                       spec.containers{php-apache}   Normal    Pulling                        kubelet, kubenode13         pulling image "gcr.io/google_containers/hpa-example"
8m         8m          1         php-apache-253401759         ReplicaSet                                              Normal    SuccessfulCreate               replicaset-controller       Created pod: php-apache-253401759-0sn8r
28s        28s         1         php-apache-253401759         ReplicaSet                                              Normal    SuccessfulCreate               replicaset-controller       Created pod: php-apache-253401759-f1c4l
28s        28s         1         php-apache-253401759         ReplicaSet                                              Normal    SuccessfulCreate               replicaset-controller       Created pod: php-apache-253401759-4j454
28s        28s         1         php-apache-253401759         ReplicaSet                                              Normal    SuccessfulCreate               replicaset-controller       Created pod: php-apache-253401759-9qfrp
8m         8m          1         php-apache                   Deployment                                              Normal    ScalingReplicaSet              deployment-controller       Scaled up replica set php-apache-253401759 to 1
2m         7m          10        php-apache                   HorizontalPodAutoscaler                                 Warning   FailedGetResourceMetric        horizontal-pod-autoscaler   unable to get metrics for resource cpu: no metrics returned from heapster
2m         7m          10        php-apache                   HorizontalPodAutoscaler                                 Warning   FailedComputeMetricsReplicas   horizontal-pod-autoscaler   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
28s        28s         1         php-apache                   HorizontalPodAutoscaler                                 Normal    SuccessfulRescale              horizontal-pod-autoscaler   New size: 4; reason: cpu resource utilization (percentage of request) above target
28s        28s         1         php-apache                   Deployment                                              Normal    ScalingReplicaSet              deployment-controller       Scaled up replica set php-apache-253401759 to 4
</pre></p></details>  
  

**What you expected to happen**:
I expected only 1 pod to be running because of the maximum amount of replicas that I specified was 1.

**Environment**:
- Kubernetes version: v1.7.3, v1.8.0
- Cloud provider or hardware configuration: Baremetal, minikube
- OS: Ubuntu 16.04
- Kernel: 4.4.0-97-generic
- Install tools: kubespray, minikube

/sig autoscaling

**Comment by dixudx** [comment]
> After going through step 3, there were 4 pods running php-apache instead of 1.

This is because default `scaleUpLimitMinimum` is 4 when replica is set to 1.

When increasing the load, `desiredReplicas` will be set to `scaleUpLimit` if larger. 

https://github.com/kubernetes/kubernetes/blob/d6cabaf706631b3713e897f49b1e86d1f637a119/pkg/controller/podautoscaler/horizontal.go#L433-L446

**Comment by fieryvova** [comment]
So this is a feature then?

**Comment by mattjmcnaughton** [comment]
Thanks for reporting this @fieryvova ! I think this is the same error as https://github.com/kubernetes/kubernetes/issues/53670 which was fixed in https://github.com/kubernetes/kubernetes/pull/53690.

Upgrading to either Kubernetes 1.8.2 or 1.7.9 should fix this issue.

**Comment by fieryvova** [comment]
@mattjmcnaughton OK. Thanks for letting me know!
