### ISSUE TITLE
AWS cloud provider needs too many permissions for Static Pods

### ISSUE THREAD

**Issue by zegl** [kubernetes/kubernetes#55482]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig aws

**What happened**:

```
Nov 10 14:44:53 {HIDDEN} kubelet[25169]: I1110 14:44:53.525456   25169 aws.go:847] Building AWS cloudprovider
Nov 10 14:44:53 {HIDDEN} kubelet[25169]: error: failed to run Kubelet: could not init cloud provider "aws": error finding instance {HIDDEN}: "error listing AWS instances: \"UnauthorizedOperation: You are not authorized to perform this operation.\\n\\tstatus code: 403, request id: {HIDDEN}\""
```

**What you expected to happen**:

That the AWS cloud provider should work with minimal permissions.

**How to reproduce it (as minimally and precisely as possible)**:

Using standalone `kubelet` with `--cloud-provider=aws`.

The Instance IAM Role only has the following permissions:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage"
            ],
            "Resource": "*"
        }
    ]
}
``` 

**Anything else we need to know?**:

Attempting to use Docker images from a private EC2 Container Service with static pods in kubelet.

**Environment**:
- Kubernetes version (use `kubectl version`): `Kubernetes v1.8.2` (kubelet version)
- Cloud provider or hardware configuration: `AWS EC2`

**Comment by justinsb** [comment]
Integration with AWS requires a bunch of permissions; there's no functionality currently to turn some of them off or not today other than turning off the cloudprovider entirely.
