### ISSUE TITLE
kubectl top needs to use the actual metrics client

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#55489]
/kind feature

`kubectl top` is currently using a bespoke client which talks directly to Heapster.
Considering that Heapster will soon no longer be required, `kubectl top` should
use the actual metrics client instead (from `k8s.io/metrics`), which will also make
use of the resource metrics API (`metrics.k8s.io`) as an aggregated API.

cc @kubernetes/sig-cli-feature-requests 
cc @kubernetes/sig-instrumentation-feature-requests

**Comment by brancz** [comment]
As a leisure proposal I'd say we keep heapster support around for the moment and just default to using the metrics-server, but fall back to heapster if the metrics-server is not available, and add flags for the metrics-server similar to how they exist for heapster today.

**Comment by brancz** [comment]
@fgrzadkowski @piosz do you think this needs a fully fledged feature + design or should someone just go ahead and implement this support in `kubectl`?

**Comment by fgrzadkowski** [comment]
My feeling is that it's pretty straight forward. We have an aggregated API which is the same as one exposed in Heapster. I guess the main difference will be which client libraries we use for it. A good example is HPA which is flag controlled whether it uses Heapster or metric-server. This code is a good starting point: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/autoscaling.go#L41

**Comment by fgrzadkowski** [comment]
@brancz which flag do you in heapster do you mean?

**Comment by brancz** [comment]
Sorry I wasn't clear enough, I meant the flags on kubectl to configure which heapster to request from, although I realized that that was silly, as the metrics-server is an aggregated API, and we can just request them from the apiserver as usual. I'd suggest we try to discover whether the apiserver is serving the metrics API and use that if it does, and otherwise fall back to the current way.

**Comment by brancz** [comment]
```
$ kubectl top pod --help
Display Resource (CPU/Memory/Storage) usage of pods. 

The 'top pod' command allows you to see the resource consumption of pods. 

Due to the metrics pipeline delay, they may be unavailable for a few minutes since pod creation.

Aliases:
pod, pods, po

Examples:
  # Show metrics for all pods in the default namespace
  kubectl top pod
  
  # Show metrics for all pods in the given namespace
  kubectl top pod --namespace=NAMESPACE
  
  # Show metrics for a given pod and its containers
  kubectl top pod POD_NAME --containers
  
  # Show metrics for the pods defined by label name=myLabel
  kubectl top pod -l name=myLabel

Options:
      --all-namespaces=false: If present, list the requested object(s) across all namespaces. Namespace in current
context is ignored even if specified with --namespace.
      --containers=false: If present, print usage of containers within a pod.
      --heapster-namespace='kube-system': Namespace Heapster service is located in
      --heapster-port='': Port name in service to use
      --heapster-scheme='http': Scheme (http or https) to connect to Heapster as
      --heapster-service='heapster': Name of Heapster service
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)

Usage:
  kubectl top pod [NAME | -l label] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

There are the `--heapster-namespace`, `--heapster-port`, `--heapster-scheme`, `--heapster-service` flags.

**Comment by fgrzadkowski** [comment]
Makes sense. Though if we switch to metric-server in release X and still keep heapster then users with kubectl in version X will just query metric server and no fallback is required, and for older version we will keep heapster running for 1 release to give them time for migration and again, we don't need fallback for them. WDYT?

**Comment by brancz** [comment]
That sounds good to me. I've started implementing support in kubectl top for using the metrics server instead of heapster. I'll reference the PR here once I get it into a working state. My current plan is to not touch the heapster parts as much as I can so that we can just delete the dead code once we decide to remove heapster support.

**Comment by fgrzadkowski** [comment]
Thanks @brancz!

**Comment by brancz** [comment]
I have the two commands working but it's probably too late for this to land in 1.9, as I still have to adapt tests. Oh well, next cycle :slightly_smiling_face: .

**Comment by smarterclayton** [comment]
That’s the 1.9 Motto
