### ISSUE TITLE
Add proxy parameters to kubefed client

### ISSUE THREAD

**Issue by miguelcastilho** [kubernetes/kubernetes#55480]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I used kubefed to depoy the federation apiserver and controller-manager. I found that the controller-manager needs a proxy as environment variables, I checked the kubefed and the controller-manager documentation and there is no parameter to add a proxy. I had to edit the deployment manually to add the proxy environment variables.

**What you expected to happen**:
I expect kubefed to accept parameters to configure a proxy.

**How to reproduce it (as minimally and precisely as possible)**:
Boot the federation components using kubefed behind a proxy. Check the logs for communication errors.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.3
- Cloud provider or hardware configuration: Bare-metal (OpenStack)
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:

**Comment by liggitt** [comment]
kubefed and federation issues should be opened against https://github.com/kubernetes/federation/
