### ISSUE TITLE
CRI: Support daemon logs for other CRI container runtime in fluentd?

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#55501]
We have changed fluentd to support CRI container log format.

However, for daemon logs, fluentd still only supports docker.

Should we add this support upstream?
/cc @kubernetes/sig-node-feature-requests

**Comment by resouer** [comment]
@Random-Liu Which daemon logs are you referring to may I ask?

**Comment by crassirostris** [comment]
@resouer AFAIU, e.g. `containerd` daemon logs. Currently, `docker` name is hardcoded in the fluentd configurations, e.g. [there](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml#L253)

**Comment by Random-Liu** [comment]
@crassirostris Thanks! Yeah, I mean `containerd`, `cri-containerd`, `cri-o` logs.

**Comment by yujuhong** [comment]
@Random-Liu, I think you made some changes so that the fluentd configuration is parameterized. Is there anything left?

**Comment by Random-Liu** [comment]
I think we can close this one now. This is addressed in https://github.com/kubernetes/kubernetes/pull/59103
