### ISSUE TITLE
Add comments info when kubectl drain/cordon/uncordon

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#55527]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
For now, when we `cordon`/`uncordon`/`drain` a node from a k8s cluster, we can not add a comment describing the reason to do so. An comment is useful for recording the reason in case someone else want to know the root cause.
**What you expected to happen**:
when running `kubectl cordon/uncordon/drain NODE`, we can add a comment and running like this: `kubectl cordon/uncordon/drain NODE COMMENT`

/cc @kubernetes/sig-node-feature-requests

**Comment by tianshapjq** [comment]
but how can we review the reason after draining the pods? from _kubectl describe pod_?

**Comment by andyxning** [comment]
The original point is that when someone or k8s mark a node as notready we can not see the root reason for doing so. Instead we need to describe the node to see which condition or taint lead to making the node not ready.

If we can see the root reason for makeing a node notready or unschedulable when get a node, it should be user friendly. :)

As for the pods running on the not ready or unschedulable node, actually i do not think about this.

**Comment by andyxning** [comment]
Working on a PR to add this support. ETA is about one week.

**Comment by curlup** [comment]
@andyxning any progress on that?
