### ISSUE TITLE
Kubectl doesnt work on node

### ISSUE THREAD

**Issue by gustavomr** [kubernetes/kubernetes#55531]
Im working setting up a cluster and using this guide https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

On master I started everything using kubeadm init, then using export KUBECONFIG=/etc/kubernetes/admin.conf to get kubectl work and then deploy wave using: 
export kubever=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever" 

On node I used kubeadm join to registre on master but I need to use kubectl command in order to deploy wave (if I don´t use this my node stuck NotReady). When I tried to execute kubectl gives me The connection to the server localhost:8080 was refused - did you specify the right host or port?

I think this error is because I dont have admin.conf on node machine. What I need to do? Execute kubeadm init in order to generate it or copy this file from master?

**Comment by dixudx** [comment]
> localhost:8080 was refused - did you specify the right host or port?

@gustavomr You need to configure the `~/.kube/conf` on your minion nodes. Please refer to this file on your master node.

**Comment by gustavomr** [comment]
@dixudx you’re right!
