### ISSUE TITLE
code sync broken (?): code-generator missing 1.9.0-alpha.2 tag

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55536]
It looks like code-generator has been synced since 1.9.0-alpha.2 was tagged (https://github.com/kubernetes/code-generator), but the code-generator repo is missing the 1.9.0-alpha.2 tag.

@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
@sttts

**Comment by nikhita** [comment]
Syncing is back in action and https://github.com/kubernetes/code-generator is now upto date.
