### ISSUE TITLE
CRD watch does not work with protobuf encoding

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55541]
When a CRD clientset is built with `ContentType = "application/vnd.kubernetes.protobuf"`, CRD watch is not notified of updates.
	
I think this was root cause of my suspicion around CRD watch being broken (#55538)

**Comment by justinsb** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
@enisoc 

I'm very surprised you can do proto with CRDs? How does the system interact with the metadata?

**Comment by ncdc** [comment]
@lavalamp you can't. CRDs only support JSON.

**Comment by enisoc** [comment]
As @ncdc said, CRD only supports JSON, for the reason @lavalamp alluded to. We allow the custom objects to be effectively schemaless, so there's no source of truth from which to generate protobuf definitions.

**Comment by liggitt** [comment]
When I try to establish a watch requesting proto content, I get a 415 error as expected. Are you seeing something different?

**Comment by nikhita** [comment]
ping @justinsb ^

**Comment by nikhita** [comment]
I guess we can close this?
