### ISSUE TITLE
apimachinery codegen is not goimports "clean"

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55542]
codegen produces code that is not stable under goimports, which makes life harder for CI / for checking it in to the repo.

For example:

```
> pkg/client/informers/externalversions/factory.go
@@ -19,16 +19,15 @@ limitations under the License.
 package externalversions
 
 import (
-       reflect "reflect"
-       sync "sync"
-       time "time"
-
...
        runtime "k8s.io/apimachinery/pkg/runtime"
        schema "k8s.io/apimachinery/pkg/runtime/schema"
        cache "k8s.io/client-go/tools/cache"
+       reflect "reflect"
+       sync "sync"
+       time "time"
 )
```

The system imports should be printed before other imports, with a single blank line.

I suspect that aliasing a package to the same name will likely be frowned upon in future as well...

@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Yeah this probably could use a fix in gengo, actually.

**Comment by jdumars** [comment]
/assign @djpinchoff

@justinsb @lavalamp Dave is an aspiring contributor and would like to look into fixing this bug.  Would you two be willing to help answer questions as needed?

**Comment by dungeonmaster18** [comment]
Hi, I am a new here. I wanted to take this issue but can someone guide me how to go about this. Thanks

**Comment by rahulkrishnanfs** [comment]
I would like to contribute to this issue. Please some one guide me how to start with this

**Comment by allenpetersen** [comment]
I've started working on this issue. I fixed up gengo to use the same code that goimports uses. I'm in the process of updating the godep dependency to pull in the new code.
