### ISSUE TITLE
Kuernetes do not support schedule based on disk I/O

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#55552]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Kubenretes has many priorities, such as least request, most request etc, but do not have predicates based on disk io, it is better to have such priorities to enable schedule based on disk io.

@kubernetes/sig-scheduling-feature-requests 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidopp** [comment]
I think this is a duplicate of #54923

**Comment by gyliu513** [comment]
Good to know, thanks @davidopp
