### ISSUE TITLE
Master node not becoming "Ready" after cluster init due to CNI issues

### ISSUE THREAD

**Issue by dennisjac** [kubernetes/kubernetes#55550]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After initializing a cluster with `kubeadm init --pod-network-cidr 10.22.33.128/25` and installing the kube-router networking addon with `kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml` the master node has the status "NotReady". In particular the node description contains the following message for the "Ready" type: `runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

**What you expected to happen**:
The master node should end up in the "Ready" state.

**How to reproduce it (as minimally and precisely as possible)**:
  * Follow the instructions on `https://kubernetes.io/docs/setup/independent/install-kubeadm/` on a CentOS 7 System.
  * run `kubeadm init --pod-network-cidr 10.22.33.128/25" and wait for the cluster to successfully initialize.
  * run `kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml` and make sure you don't get any errors
  * use `kubectl get nodes` and `kubectl describe node <node>` to see the state/error mentioned above

**Anything else we need to know?**:
From reading around the net it seems that some form of config is supposed to be found in `/etc/cni/net.d` but the directory `/etc/cni` doesn't exist.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Simple virtual machine with 4G ram, 2 cpus and 50G storage.

- OS (e.g. from /etc/os-release):
CentOS 7.4

- Kernel (e.g. `uname -a`):
Linux node1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Only the tools mentioned on the installation page.

**Comment by dennisjac** [comment]
@kubernetes/sig-Network-bugs

**Comment by jiulongzaitian** [comment]
i have found the seem question when i used calico network:
`  kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml    .`
similary， the node host lack of cni configure file in /etc/cni/net.d.   and i found that cni container failed to write configue file when it start by it`s logs.    after reboot the node host, it`s ok.

**Comment by dennisjac** [comment]
SELinux is already completely disabled on the system.

Which component is supposed to create the CNI configuration and where in the install process is this supposed to happen?

**Comment by jiulongzaitian** [comment]
can you show the install-cni  container logs?

**Comment by vherron12** [comment]
[root@node1-k8s ~]# kubectl get nodes --show-labels
NAME                    STATUS     ROLES     AGE       VERSION   LABELS
node1-k8s               NotReady   master    22h       v1.9.3    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=node1-k8s,node-role.kubernetes.io/master=
node2-k8s.localdomain   NotReady   <none>    22h       v1.9.3    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=node2-k8s.localdomain
node3-k8s.localdomain   NotReady   <none>    22h       v1.9.3    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=node3-k8s.localdomain
[root@node1-k8s ~]# kubectl run curl –image=radial/busyboxplus:curl -i –tty
error: --image is required
[root@node1-k8s ~]# kubectl run curl –-image=radial/busyboxplus:curl -i –tty
error: --image is required
[root@node1-k8s ~]# kubectl run curl --image=radial/busyboxplus:curl -i –tty
Error from server (Forbidden): deployments.extensions is forbidden: User "system:node:node1-k8s" cannot create deployments.extensions in the namespace "default"
[root@node1-k8s ~]# kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e88300 0xc420432bd0 kube-system kube-router-cfg https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc4215961d8  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": configmaps "kube-router-cfg" is forbidden: User "system:node:node1-k8s" cannot get configmaps in the namespace "kube-system": no path found to object
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e883c0 0xc4201cf9d0 kube-system kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc4215964b0  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": daemonsets.extensions "kube-router" is forbidden: User "system:node:node1-k8s" cannot get daemonsets.extensions in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e88480 0xc420109420 kube-system kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc421596530  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": serviceaccounts "kube-router" is forbidden: User "system:node:node1-k8s" cannot get serviceaccounts in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc422494300 0xc4203ead20  kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc421604068  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": clusterroles.rbac.authorization.k8s.io "kube-router" is forbidden: User "system:node:node1-k8s" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4224943c0 0xc420426c40  kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc4216040f0  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": clusterrolebindings.rbac.authorization.k8s.io "kube-router" is forbidden: User "system:node:node1-k8s" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
[root@node1-k8s ~]# kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e34600 0xc42011d110 kube-system kube-router-cfg https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc4215f20b8  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": configmaps "kube-router-cfg" is forbidden: User "system:node:node1-k8s" cannot get configmaps in the namespace "kube-system": no path found to object
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e346c0 0xc420155880 kube-system kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc421584200  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": daemonsets.extensions "kube-router" is forbidden: User "system:node:node1-k8s" cannot get daemonsets.extensions in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e34780 0xc4202b4b60 kube-system kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc421584280  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": serviceaccounts "kube-router" is forbidden: User "system:node:node1-k8s" cannot get serviceaccounts in the namespace "kube-system"
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e34840 0xc420377f10  kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc421584340  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": clusterroles.rbac.authorization.k8s.io "kube-router" is forbidden: User "system:node:node1-k8s" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420e34900 0xc420495e30  kube-router https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml 0xc4215843b8  false}
from server for: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml": clusterrolebindings.rbac.authorization.k8s.io "kube-router" is forbidden: User "system:node:node1-k8s" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
[root@node1-k8s ~]# 

I'm getting this kind of error. Can anyone help with this?
