### ISSUE TITLE
Support restricting list/watch/get to "metadata-only"

### ISSUE THREAD

**Issue by anguslees** [kubernetes/kubernetes#55564]
/kind feature

I have several situations with controllers - in particular around Secrets - where I'd _like_ to be able to say "you can create+find+delete the resources you want, but not read them".  Right now, "finding" implies having full read access, since list/watch/get gives you the entire resource definition (and status).

Crazy suggestion:  Implement a common `.../metadata` subresource that returns *just* the ObjectMeta/TypeMeta.  This can then be used in RBAC rules to allow list/watch and delete(*) without giving access to the full body.

(*)  perhaps delete is only allowed on the parent resource - I imagine it will be simpler if the subresource can't be mutated.  This assumes the subresource UID/resourceVersion is the same as the parent, so we can avoid races between reading subresource and manipulating parent resource.

**Comment by lavalamp** [comment]
@smarterclayton is working on making it possible for the server to return just this data.

However it won't be easy (possible?) to put an RBAC rule on that, as it's negotiated via HTTP headers.

@deads2k or @liggitt may have ideas. I'd want to think very carefully before doing something drastic like adding a ton of subresources.

**Comment by liggitt** [comment]
also, metadata isn't guaranteed to be free of confidential data. `kubectl apply` puts full copies of object data in annotations

**Comment by anguslees** [comment]
@liggitt: urgh, I'd forgotten about that delightful feature of `kubectl apply`.  Yep, that sinks this as an idea - closing.
