### ISSUE TITLE
cloud-provider framework doesn't call event handler when service type changed

### ISSUE THREAD

**Issue by dunjut** [kubernetes/kubernetes#55585]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Service type changed from `LoadBalancer` to `ClusterIP`, none of the LoadBalancer interfaces of cloud-provider code framework (`EnsureLoadBalancer/EnsureLoadBalancerDeleted/UpdateLoadBalancer`) got called.
As a result, silently changing service type to `ClusterIP` without cloud-provider informed about it leads to a LoadBalancer resource leak in our cloud environment.

**What you expected to happen**:
UpdateLoadBalancer or EnsureLoadBalancerDeleted get called so we are informed to clean up the cloud resources.

**How to reproduce it (as minimally and precisely as possible)**:
1, create service type=LoadBalancer
2, edit service, change type from LoadBalancer to ClusterIP
3, check cloud-provider logs (or other means) to see if cloud-provider knows this changing event

**Anything else we need to know?**:
We're using our own cloud-provider implement, not AWS, Azure or any other public clouds. However, I think this is not much relevant to the behavior.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Kubernetes is running on bare-metals. We've implemented our own cloud-provider for OpenStack Neutron based network solution.

- OS (e.g. from /etc/os-release):
Ubuntu 16.04.2 LTS

- Kernel (e.g. `uname -a`):
Linux $hostname 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:  kubeadm
- Others:

**Comment by dunjut** [comment]
@kubernetes/sig-cloud-provider-bugs

**Comment by hzxuzhonghu** [comment]
I will dig into it.

**Comment by hzxuzhonghu** [comment]
@dunjut Seems not serviceController issue. It already implement delete LB when no need LB. See `func (s *ServiceController) createLoadBalancerIfNeeded(key string, service *v1.Service) (error, bool) {
`

**Comment by dunjut** [comment]
@hzxuzhonghu I think `serviceController` is part of `kube-controller-manager`, and yes I think it already does the correct logic in the `createLoadBalancerIfNeeded` code snippet. Then it must be an issue of `cloud-provider` issue.

Can you reproduce it following my steps?

**Comment by hzxuzhonghu** [comment]
What cloud-provider are you using?

**Comment by hzxuzhonghu** [comment]
>We're using our own cloud-provider implement, not AWS, Azure or any other public clouds.

check your logic

**Comment by dunjut** [comment]
@hzxuzhonghu The thing is, we log at the very beginning of every LoadBalancer interfaces, but nothing prints out after I change a service's type from LoadBalancer to ClusterIP. So even our logic is wrong, at least we should be able to see a log of function call.

If you can't reproduce this issue according to my steps, then it must be something wrong of our own. Can you help confirm that?

**Comment by dunjut** [comment]
@thockin can you please help take a look at this?

**Comment by dunjut** [comment]
@freehan @bowei can you please help take a look at this?

**Comment by jhorwit2** [comment]
@dunjut are you able to test this on 1.8? I'm not able to reproduce it.

```
  Normal  Type                  10s (x2 over 10s)  service-controller  LoadBalancer -> ClusterIP
  Normal  DeletingLoadBalancer  9s                 service-controller  Deleting load balancer
```

Is your provider implementation public by chance? I don't see any logic in the service controller that has changed related to this type of update. Also, the service controller is the same across the KCM and CCM, so `createLoadBalancerIfNeeded` has no differences.

**Comment by dunjut** [comment]
@jhorwit2 yes, I reproduced this issue on 1.8

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rajatjindal** [comment]
in my case I changed the service from http to https, and load balancer on AWS was not updated.

do u think it might be due to same issue?

**Comment by jhorwit2** [comment]
@rajatjindal could you please create another issue for that.
