### ISSUE TITLE
[Bug-Report] kube-scheduler: NodeInfo cache is not consistent with etcd

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#55587]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Fail to schedule one pod to one node because kube-scheduler thinks this node doesn't have enough resources.

However, this node have enough resources for this pod actually.

**What you expected to happen**:

successfully schedule this pod to this node.

**How to reproduce it (as minimally and precisely as possible)**:

As we all know, delete event is not reliable. For some reasons, scheduler miss pod delete event, so it doesn't recycle corresponding resources for this node.

reproduce steps:

- we have pod-A and node-A, pod-A is scheduled to node-A. node-A doesn't have free resources now.
- delete pod-A.
- before pod-A delete event is sent to kube-scheduler, restart kube-apiserver.
- create pod-B(same resource request with pod-A) and try to schdule to node-A.

The last step will fail unless we restart kube-scheduler.

**Anything else we need to know?**:

Delete event is not reliable. In this scene, NodeInfo.requestedResource is not right.I think we should take some necessary measures to deal with it.

for example, we can check NodeInfo.Pods periodically to verify if this pod is already deleted or not. If pod is already deleted, we should update nodeInfo cache to recycle resources occupied by this pod.

**Environment**:

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5.1.1.0.158+32bf05fbb7ea04-dirty", GitCommit:"32bf05fbb7ea04eae309151c997ebcd607f91f61", GitTreeState:"dirty", BuildDate:"2017-10-20T08:34:57Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5.1.1.0.169+7eee5030cd10eb-dirty", GitCommit:"7eee5030cd10eb57924cf20ecc4149678710414d", GitTreeState:"dirty", BuildDate:"2017-11-09T06:55:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by guangxuli** [comment]
IMO, in that case every event will not be reliable, hmm but how we check NodeInfo.Pods periodically? It sounds a expensive process.

**Comment by shenlanse** [comment]
> IMO, in that case every event will not be reliable

@guangxuli     
I don‘t think so. Update and add events always have same processing. When apiserver is restarted, client-side  List-Watch will be restarted too, Update and Add events will never be lost( because we generally only care about the last state instead of intermediate state). However, Delete event is different, disappear is disappear, restart is useless.

**Comment by shenlanse** [comment]
When scheduler restart List-Watch( pod and node ), schedulerCache doesn't resconstruct its cache completely.

This exception happened in our product environment and not easily to find.

**Comment by resouer** [comment]
@shenlanse What's your Kubernetes version may I ask?

**Comment by shenlanse** [comment]
@resouer v1.3.5.  After checking scheduler implementation of v1.8, I think this problem still exists.

**Comment by resouer** [comment]
The prerequisites is you need to stop scheduler before `podInformer` watched pod delete happens. If it's true, this use case is not likely worth fixing ... it's expected.

**Comment by shenlanse** [comment]
@resouer It has nothing to do with 'stop kube-scheduler'. kube-apiserver restarted or exit unnormally will resulting in this problem  possibly.

**Comment by resouer** [comment]
Yeah, I meant apiserver, the idea stands.

**Comment by shenlanse** [comment]
Ok， thanks. Close it.
