### ISSUE TITLE
10-calico.conflist not loaded

### ISSUE THREAD

**Issue by felskrone** [kubernetes/kubernetes#55599]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug-Report

/kind bug

**What happened**:
I tried to setup canal/calico, but the kubelet fails to load the 10-calico.conflist file. The kubelets log states 'cni config uninitialized'.

```bash
16:31 worker03 kubelet[897]: E1107 17:16:31.443948     897 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "busybox-w3_default(306aae5c-c3d7-11e7-9d9a-0022195f6b5b)" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_306aae5c-c3d7-11e7-9d9a-0022195f6b5b_0 in sandbox 2c4d4abf9049c94a95da3e6e129b015f420754185c31fafe0fe60144e8dc6d3e: cni config uninitialized
Nov 07 17:16:31 worker03 kubelet[897]: E1107 17:16:31.443975     897 kuberuntime_manager.go:618] createPodSandbox for pod "busybox-w3_default(306aae5c-c3d7-11e7-9d9a-0022195f6b5b)" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_306aae5c-c3d7-11e7-9d9a-0022195f6b5b_0 in sandbox 2c4d4abf9049c94a95da3e6e129b015f420754185c31fafe0fe60144e8dc6d3e: cni config uninitialized
Nov 07 17:16:31 worker03 kubelet[897]: E1107 17:16:31.444031     897 pod_workers.go:182] Error syncing pod 306aae5c-c3d7-11e7-9d9a-0022195f6b5b ("busybox-w3_default(306aae5c-c3d7-11e7-9d9a-0022195f6b5b)"), skipping: failed to "CreatePodSandbox" for "busybox-w3_default(306aae5c-c3d7-11e7-9d9a-0022195f6b5b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"busybox-w3_default(306aae5c-c3d7-11e7-9d9a-0022195f6b5b)\" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_306aae5c-c3d7-11e7-9d9a-0022195f6b5b_0 in sandbox 2c4d4abf9049c94a95da3e6e129b015f420754185c31fafe0fe60144e8dc6d3e: cni config uninitialized"
```

If i rename the config to 10-calico.conf it gets picked up, but the error just changes to 'no plugin name provided'.

```bash
Nov 07 20:10:11 worker03 kubelet[3925]: E1107 20:10:11.604519    3925 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_88d62a8d-c3ef-11e7-9d9a-0022195f6b5b_0 in sandbox 7a1ad45ffbe861e17836f2331240d180bbaf26019833a85c6006920fd14d8b6d: no plugin name provided
Nov 07 20:10:11 worker03 kubelet[3925]: E1107 20:10:11.604614    3925 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "busybox-w3_default(88d62a8d-c3ef-11e7-9d9a-0022195f6b5b)" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_88d62a8d-c3ef-11e7-9d9a-0022195f6b5b_0 in sandbox 7a1ad45ffbe861e17836f2331240d180bbaf26019833a85c6006920fd14d8b6d: no plugin name provided
Nov 07 20:10:11 worker03 kubelet[3925]: E1107 20:10:11.604641    3925 kuberuntime_manager.go:618] createPodSandbox for pod "busybox-w3_default(88d62a8d-c3ef-11e7-9d9a-0022195f6b5b)" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_88d62a8d-c3ef-11e7-9d9a-0022195f6b5b_0 in sandbox 7a1ad45ffbe861e17836f2331240d180bbaf26019833a85c6006920fd14d8b6d: no plugin name provided
Nov 07 20:10:11 worker03 kubelet[3925]: E1107 20:10:11.604794    3925 pod_workers.go:182] Error syncing pod 88d62a8d-c3ef-11e7-9d9a-0022195f6b5b ("busybox-w3_default(88d62a8d-c3ef-11e7-9d9a-0022195f6b5b)"), skipping: failed to "CreatePodSandbox" for "busybox-w3_default(88d62a8d-c3ef-11e7-9d9a-0022195f6b5b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"busybox-w3_default(88d62a8d-c3ef-11e7-9d9a-0022195f6b5b)\" failed: rpc error: code = 2 desc = failed to create network for container k8s_infra_busybox-w3_default_88d62a8d-c3ef-11e7-9d9a-0022195f6b5b_0 in sandbox 7a1ad45ffbe861e17836f2331240d180bbaf26019833a85c6006920fd14d8b6d: no plugin name provided"
```
The config itself is the ConfigMap straight from the canal.yaml [here](https://github.com/projectcalico/canal/blob/master/k8s-install/1.7/canal.yaml#L18) without any changes. 

```json
  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.3.0",
        "plugins": [
            {
                "type": "calico",
                "log_level": "info",
                "datastore_type": "kubernetes",
                "nodename": "__KUBERNETES_NODE_NAME__",
                "ipam": {
                    "type": "host-local",
                    "subnet": "usePodCidr"
                },
                "policy": {
                    "type": "k8s",
                    "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
                },
                "kubernetes": {
                    "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                    "kubeconfig": "__KUBECONFIG_FILEPATH__"
                }
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true},
                "snat": true
            }
        ]
    }
```

**What you expected to happen**:
That the kubelet loads the 10-calico.conflist and configures cni properly.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a Kubernetes 1.7.x Cluster and try to run the canal.yaml linked aboved. More details also described here https://github.com/projectcalico/canal/issues/111 

**Anything else we need to know?**:

**Environment**:
- Kubernetes versions tested: 1.7.6 and 1.7.10
- Hardware configuration: DELL various, from R200, R420, R710
- Debian Stretch
- Kernel 4.9.0-3-amd64

**Questions:**
Does the kubelet indeed support *.conflist files? If so, what version does that require?

Does the kubelet support CNI-Plugin-Lists described [here](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration-lists)?  If so, what version does that require?

Are the any command line parameters to the kubelet that may affect the support of *.conflist files besides '--cni-bin-dir', '--cni-conf-dir' and '--network-plugin'?

Thanks!

PS: I also tried on [SO](https://stackoverflow.com/questions/47188004/kubelet-does-not-recognize-10-calico-conflist), but no luck.

**Comment by felskrone** [comment]
@kubernetes/sig-node-bugs

I hope this is correct :-)

**Comment by tmjd** [comment]
@felskrone The kubelet does support conflist. I've brought up K8s multiple times with Calico and Canal (I work on them). The problem might be how the kubelet is ran though, I think a few deployment methods run the kubelet in a container and do not mount in the necessary directories where the CNI configuration and binaries are written.  Specifically Canal and Calico will write the configuration to `/etc/cni/net.d` and binaries to `/opt/cni/bin`, so the kubelet will need access to those.

I hope this helps.

**Comment by felskrone** [comment]
@tmjd Thanks for your response. My k8s-services (kubelet, kube-proxy, etc.) are not containerized in any way. They run directly on the nodes as daemons managed with systemd, meaning they have  full access to the configs in /etc/cni/net.d/.

What would be a good approach for debugging this? I tried with the verbosity-level of the kubelet, but that tells me nothing besides "cni config unitialized". 

Is there any way to get more output?

PS: I just setup my cluster from scratch again with deleting etcd-db, all kubelet-data and images on the nodes, etc. but the error persists.

**Comment by pikeszfish** [comment]
I have the same problem when I use
- kubelet 1.7.11
- calico and calico-ipam
- portmap
- CNI config name `10-calico.conf`

kubelet output something like 
```
Error syncing pod ... , skipping: failed to "KillPodSandbox" for "..." with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"...\" network: no plugin name provided"
```

But it's OK when I rename config name to `10-calico.conflist`

**Comment by tmjd** [comment]
@pikeszfish I think what you are seeing is different.  When you are using portmap and calico the config must be a list which the kubelet requires to have the `conflist` suffix.

@felskrone You can set a logging level with `-v Level`, sorry I'm not sure what the Level should be but I'd probably try `Debug`.

**Comment by caseydavenport** [comment]
@pikeszfish that's expected - if you include the portmap plugin in your config, it _must_ end in the `.conflist` suffix.
