### ISSUE TITLE
kubernetes apiserver does not update if another "kube-apiserver.yaml.bak" is present in the same directory

### ISSUE THREAD

**Issue by P4otocol** [kubernetes/kubernetes#55596]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**: Kubernetes api server does not update with the information specified in "/etc/kubernetes/manifests/**kube-apiserver.yaml**" when another file with similar name exists in the same directory. Ex : "**kube-apiserver.yaml.bak**"

**What you expected to happen**: It should update the actual "kube-apiserver.yaml" and not use the backup file created with the similar name.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a backup file of "/etc/kubernetes/manifests/kube-apiserver.yaml" as **kube-apiserver.yaml.bak** in the same directory.
2) Update the kube-apiserver.yaml and save it.
3) The changes made will not be updated or sometimes the api-server crashes. (Do a "**ps -ef | grep api**" and observer that changes will not be updated).
4) Now move the backup file to a different directory and try again, the changes made to the kube-apiserver will be reflected.

**Anything else we need to know?**: This bug was observed when checking issue "kube-apiserver cannot see its configured basic-auth file #5778"

**Environment**:
- Kubernetes version (use `kubectl version`):  1.8.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): Linux
- Install tools:
- Others:

**Comment by dixudx** [comment]
@P4otocol This is not a bug. Actually all the files under the manifest path are treated as regular files, regardless of file suffix.

`kube-apiserver.yaml.bak` is read after `kube-apiserver.yaml`, so whatever you have changed in `kube-apiserver.yaml.bak` will be overwrote.
