### ISSUE TITLE
[juju] the log file for kubeapi-load-balancer is not rotated by default

### ISSUE THREAD

**Issue by axinojolais** [kubernetes/kubernetes#55602]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
one of my kubeapi-load-balancer unit ran out of disk because the log file set up by the Juju charm (`/var/log/nginx.access.log`) is not rotated.

**What you expected to happen**:
the log file should be rotated by default. You can make that happen easily if you log to `/var/log/nginx/*.log`

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy a kubernetes cluster with juju.
1. connect to the kubeapi-load-balancer unit : the log file above is not rotated.

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-78-generic
- Install tools: ?
- Others: ?

**Comment by barryprice** [comment]
Seems this was fixed last month:

https://github.com/kubernetes/kubernetes/commit/57059ea4428265cdea7e4c79646ad476fe79fcd8#diff-62515902f2f0b074724269361a1c42b3

as part of this PR:

https://github.com/kubernetes/kubernetes/pull/56979

**Comment by ktsakalozos** [comment]
We can close this. The fix is released.
