### ISSUE TITLE
Garbage collection for legacy container log  is useless

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#55607]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

`Kubelet` has a garbage collection to clean up unused containers, and containers' logs will be removed in the `GarbageCollect` method too. But  the garbage collection code for legacy container log(merged by this [PR](https://github.com/kubernetes/kubernetes/pull/34858), in this [commit](https://github.com/kubernetes/kubernetes/pull/34858/commits/fad4672e725877830407e2e4694fed7ceae5fe0a)) doesn't work, as the `Remove` operation is invoked only if the `logSymlink` is **not** exist(The code as follows). But if it is non-existent, we have nothing to remove, and the `logSymlink` usually exist as we find them by `Glob` method.

```go
for _, logSymlink := range logSymlinks {
    if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
        err := osInterface.Remove(logSymlink)
        if err != nil {
            glog.Errorf("Failed to remove container log dead symlink %q: %v", logSymlink, err)
        }
    }
}
``` 

Do we really need this operation here? As the container logs(both cir logs and legacy logs) are removed before according containers removed, so there won't have left logs of a removed container theoretically.

If we needn't this operation here, I will submit a PR later to remove this code. Otherwise, maybe we need a effective way to inspect whether according `Pod` is deleted or not.

**Comment by dixudx** [comment]
@Random-Liu I think it should be

```Go
if _, err := osInterface.Stat(logSymlink); !os.IsNotExist(err) {
   ...
}
```

**Comment by mlmhl** [comment]
@dixudx  I think this code maybe still a problem as it doesn't check whether according `Pod` is deleted or not, so it will remove all existing legacy logs even if according containers are running normally.
