### ISSUE TITLE
Request body failed to be serialized in audit event

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#55616]
I observe the following error in the logs:

```
... request.go:152] Auditing failed of request: encoding failed: policy.Eviction is not suitable for converting to "v1"
```

Any ideas where this comes from?

/cc @tallclair @sttts @soltysh @CaoShuFeng @ericchiang

**Comment by sttts** [comment]
There is no v1 version of policy, isn't there?

**Comment by sttts** [comment]
And `"v1"` is a GroupVersion as far as I see. This means the gv is actually core/v1.

**Comment by sttts** [comment]
@crassirostris can you reproduce this? Would be helpful to know the exact request (http path especially and verb). Maybe a `debug.PrintStack()` output would also help.

**Comment by crassirostris** [comment]
@sttts I'll try to repro this with more details. Meanwhile this is the piece of code responsible for the message: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/audit/request.go#L152

**Comment by hzxuzhonghu** [comment]
I think its because the request resource is with invalid version. `type Eviction struct` have no v1 version

**Comment by crassirostris** [comment]
OK, couldn't repro within one day. It probably came from some faulty e2e test, nvm

**Comment by grosser** [comment]
seeing the same and it's hard to debug ... need the requesting serviceaccount in the log :(

**Comment by tallclair** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/84571
