### ISSUE TITLE
Cannot resolve internal DNS intermittently on GKE 1.8.2

### ISSUE THREAD

**Issue by stevenaldinger** [kubernetes/kubernetes#55610]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

What happened:

DNS (kube-dns) fails to resolve intermittently for internal services when a pod is running on the same node as a kube-dns pod.

What you expected to happen:

Successfully resolve DNS regardless of which node a pod is scheduled on.

How to reproduce it (as minimally and precisely as possible):

Spin up 3 node cluster running `v1.8.2-gke.0` on `Google Container Engine`.

(Sorry, not sure if default namespace has same issue but can't check til much later)

Create a namespace, call it `phabricator`.

Deploy a service, such as `mariadb` in `phabricator` namespace.

Deploy a pod in `phabricator` namespace that tries to `nslookup` `mariadb.phabricator` in a loop.

If the pod gets scheduled to the same node as one of the (two in my case) kube-dns pods, most of the time `mariadb.phabricator` will not be resolved, occasionally it will.

If the pod gets scheduled to a node that no kube-dns pods are running on, resolution will work consistently.

Anything else we need to know?:

I immediately created `cluster-admin` service accounts or added cluster-binding for the default service account to `cluster-admin`.

I literally deleted and recreated the cluster 10+ times in the last 8 hours and its a very, very reproducible thing for me.

Environment:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.2-gke.0", GitCommit:"52ea03646e64b35a5b092ab32bb529400c296aa6", GitTreeState:"clean", BuildDate:"2017-10-24T23:31:18Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Node info:

```
Kernel Version:             4.4.0-1027-gke
OS Image:                   Ubuntu 16.04.3 LTS
Operating System:           linux
Architecture:               amd64
Container Runtime Version:  docker://1.12.6
Kubelet Version:            v1.8.2-gke.0
Kube-Proxy Version:         v1.8.2-gke.0
```

**Comment by jeremywadsack** [comment]
@stevenaldinger Did you have any Events on the `kube-dns` pod(s) during this time?

We found that when the CPU usage was very high (>95%) or memory usage was high enough to cause requests to be denied (e.g. "SLUB: Unable to allocate memory on node -1" in `dmesg` on the node), that we'd see errors in the `kube-dns` health check:

```
Readiness probe failed: Get http://10.0.4.206:8081/readiness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Liveness probe failed: Get http://10.0.4.206:10054/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

This would cause DNS resolution failures across our cluster (including other health checks to fail, therefore). 

Given your test case of "`nslookup` `mariadb.phabricator` in a loop" makes me wonder if you're pinning the CPU on the node.
