### ISSUE TITLE
Always retry audit webhook

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#55621]
For background processes like buffered audit logging it makes sense to always retry the request. This won't change the user request latencies but will increase the reliability for any system that received those events

Audit logging is different from auth[nz], the latter can be retried by user, audit logs are gone for good, once the webhook decides not to retry

/cc @sttts @tallclair @ericchiang @CaoShuFeng

**Comment by lavalamp** [comment]
@mml thinks this may be a dup of an existing request.

I'm a little nervous about making a queue that could get really big if the drain on it starts failing 100% of the time?

**Comment by crassirostris** [comment]
@lavalamp 

> I'm a little nervous about making a queue that could get really big if the drain on it starts failing 100% of the time?

Regarding memory consumption: for buffered audit logging backend, queue size is limited by 10k objects by default, is it enough to feel safe about it being full?

Regarding influences on API latencies: if queue is full, events are dropped, audit path is never blocking in buffered mode
