### ISSUE TITLE
Cut and vendor cAdvisor v0.28.1 for the 1.9 release.

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#55628]
This issue tracks progress for the cAdvisor release corresponding to the kubernetes 1.9 release.
Cutting the cAdvisor release is currently targeted for 11/17.
This cAdvisor release should include per-container GPU stats, on-demand metrics, and containerd stats, among other things.

cc @dchen1107 @Random-Liu @derekwaynecarr @abhi @mindprince 
/sig node
/kind feature

**Comment by jberkus** [comment]
This is a reminder from the release team that Code Slush starts Monday, Nov. 20th.  This issue needs to have an associated, approved PR by then, or needs to be removed from the milestone.  Thanks!

**Comment by dashpole** [comment]
@jberkus I thought PRs didnt need to be approved until code freeze?  My timing with cutting the cAdvisor release (which is scheduled for today) was designed to give me a few days to get the godep update into kubernetes/kubernetes.  Where are these policies listed?

**Comment by dashpole** [comment]
This is required to fix https://github.com/kubernetes/kubernetes/issues/55909, which should fix flaky node tests.

**Comment by euank** [comment]
This should also fix https://github.com/coreos/bugs/issues/1965; cc @rphillips if you'd like to do any further verification / track that.

**Comment by jberkus** [comment]
@dashpole here: https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md#code-slush

**Comment by jberkus** [comment]
Sorry, my mistake: you're correct that you have until Wednesday for the PR.  Sorry for the noise; we've been changing PR handling with automation and I misunderstood what had to be approved today.
