### ISSUE TITLE
HPA not scaling due to evicted pods

### ISSUE THREAD

**Issue by ryanschwartz** [kubernetes/kubernetes#55630]
/kind bug
**What happened**:
HPA fails to launch additional pods due to pods in evicted state, even with utilization significantly over target.

**What you expected to happen**:
When HPA pods reach the target utilization, new pods should be allocated and provisioned.
 
**How to reproduce it (as minimally and precisely as possible)**:
Launch a HPA, let the pods fill the disk on the host which will trigger evictions due to "Pod The node was low on resource: [DiskPressure]", HPA will exceed target and not allocate additional pods.

**Anything else we need to know?**:
Seems related to #55051 and #54525 though those are not specific to HPA.

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): cos-stable-57-9202-64-0 kernel commit id 01693b885a081b92a166f9492e4ae712f08ac1a9
- Kernel (e.g. `uname -a`):Linux gke-prod1-use1b-v2-64850c24-35s4 4.4.70+ #1 SMP Mon Sep 18 12:43:08 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

**Comment by ryanschwartz** [comment]
@kubernetes/sig-scheduling

**Comment by onionjake** [comment]
Are there any workarounds while we wait for a fix?  We have ran into this on a 1.8.4 GKE cluster.

**Comment by bskiba** [comment]
@DirectXMan12 I am thinking of fixing this by excluding pods with Phase=Failed from the unreadyPods that are taken into account. It seems the right thing to do as they will not become running again. Do you see any issues?

**Comment by DirectXMan12** [comment]
that seems decent -- anything that will never be running again should not be factored into our calculations.

**Comment by jberkus** [comment]
oops, missing priority was my fault, moving back into milestone:

/priority critical-urgent
/remove-priority important-soon
