### ISSUE TITLE
Kubelet: Resolve paths from dynamic config payloads against unpacked config file location

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#55645]
See https://github.com/kubernetes/kubernetes/pull/53833#issuecomment-344009912

We have to do this before dynamic config leaves alpha. This requires some changes to how dynamic config checkpoints payloads, so defering this work for now to focus on https://github.com/kubernetes/kubernetes/issues/55644 instead.

**Comment by mtaufen** [comment]
This work was completed across #55648 and #56995

**Comment by jberkus** [comment]
Reminder: this PR needs status/approved-for-milestone, or it will be automatically kicked on at Code Freeze (monday).

**Comment by jberkus** [comment]
Reminder: this issue needs status/approved-for-milestone, or it will be automatically kicked on at Code Freeze (monday).

**Comment by mtaufen** [comment]
This was resolved in https://github.com/kubernetes/kubernetes/pull/55648
