### ISSUE TITLE
TestCascadingDeletion during pull-kubernetes-unit-test flaky 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#55652]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55575/pull-kubernetes-unit/64726/
```
go test -v k8s.io/kubernetes/test/integration/garbagecollector -run TestCascadingDeletion$
panic: close of closed channel
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
/usr/local/go/src/runtime/panic.go:491 +0x283
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:259 +0xb80
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:123 +0x39
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:211 +0x20f
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:172 +0xd9
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go:268 +0xc9
				from junit_3a3d564eebb1750e5c904cc525d117617fc0af51_20171113-090812.xml
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mindprince** [comment]
A lot of tests in `test/integration/garbagecollector` are very flaky.

From http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=7&fullscreen&orgId=1&from=now-7d&to=now and http://storage.googleapis.com/k8s-metrics/flakes-latest.json

`TestMixedRelationships`, `TestCRDDeletionCascading` and `TestCustomResourceCascadingDeletion` are the top 3 flaky tests among all kubernetes tests.

/assign @ironcladlou @deads2k @caesarxuchao

**Comment by hzxuzhonghu** [comment]
#55653  fix double close channel panic related to https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55575/pull-kubernetes-unit/64726/

**Comment by mindprince** [comment]
Is this issue ready to be closed? Did that PR fix the reason for flakes in all these tests?

**Comment by BenTheElder** [comment]
This is still a problem, these tests are still the flakiest
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56097/pull-kubernetes-unit/67068/

**Comment by hzxuzhonghu** [comment]
@BenTheElder @mindprince My fix is double close channel panic. This one is not fixed. May be I shoud edit the title.

**Comment by BenTheElder** [comment]
we also need a new issue then, I'm a bit overloaded ATM could one of @hzxuzhonghu @mindprince open a new one with the garbagecollector failures?

**Comment by hzxuzhonghu** [comment]
OK

**Comment by caesarxuchao** [comment]
I'll try to debug some of these.

**Comment by hzxuzhonghu** [comment]
I created a new issue #56121

**Comment by BenTheElder** [comment]
Thanks!
