### ISSUE TITLE
service-controller doesn't react to node changes

### ISSUE THREAD

**Issue by langyenan** [kubernetes/kubernetes#55662]
By now, service-controller watches Service but is oblivious of Node changing. If Node is added or removed from cluster while service keeps unchanged, service-controller will not update Node info into load balancer.  
Shouldn't service-controller get informed when Node is added/removed?

**Comment by hzxuzhonghu** [comment]
service controller does sync node periodically(100s).

**Comment by langyenan** [comment]
@hzxuzhonghu found it, thanks
