### ISSUE TITLE
CRI: container runtime interface support PodSandboxImage config

### ISSUE THREAD

**Issue by goby** [kubernetes/kubernetes#55676]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When use remote container runtime, the remote can't get any PodSandboxImage config set by kubelet `--pod-infra-container-image` 

**What you expected to happen**:
We want the all container runtime should know what's right PodSandboxImage

**How to reproduce it (as minimally and precisely as possible)**:
1. Add in new node with [frakti](https://github.com/kubernetes/frakti) into k8s cluster
2. The kubelet with `--pod-infra-container-image=goby/pause-amd64:3.0 --container-runtime=remote --container-runtime-endpoint=/var/run/frakti.sock` options
3. I expect frakti can create sandbox container with `goby/pause-amd64:3.0`, but get default `gcr.io/google_containers/pause-amd64:3.0`(k8s version: v1.8.2)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: bootstrap by kubeadm v1.8.2
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by dixudx** [comment]
@goby use `--container-runtime=docker` instead.

**Comment by dixudx** [comment]
/assign 

I will work on this.

**Comment by goby** [comment]
@dixudx good news! thanks!

**Comment by dixudx** [comment]
@goby Actually we do a no-op when the container runtime is `remote`.

https://github.com/kubernetes/kubernetes/blob/891b471064ddc10aa1e903c7af3162ef157f17ad/pkg/kubelet/kubelet.go#L649-L651

This is why `PodSandboxImage` config can not be set by flag `--pod-infra-container-image`.
