### ISSUE TITLE
Pods with GPU requests should be rejected early if Accelerators feature gate is off

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#55679]
/kind bug

*What happened**:
When requesting a Pod creation with alpha.kubernetes.io/nvidia-gpu specified, I was hoping that the creation is a failure because I didn't enable the Accelerators feature gate. However, it succeeded. The pod is stuck in Pending status which is fine.

**What you expected to happen**:
I'm expecting that a Pod requesting GPU will be rejected when its container resource requirements are validated. Having the GPU usage guarded by the feature gate will help cleaning removing it in future when device plugin stabilizes.

**How to reproduce it (as minimally and precisely as possible)**:
Disable Accelerators feature gate and create a Pod with GPU request or limit, the pod is successfully created. It means that the feature gate is not doing its job.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mindprince** [comment]
/close

This is deprecated in 1.10 and going to be removed in 1.11: https://github.com/kubernetes/kubernetes/pull/61498
