### ISSUE TITLE
Deprecated "RemoteContainerRuntime"?

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#55688]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
@kubernetes/sig-node-proposals 

When instantiating a new Kubelet object, there is a no-op for `--container-runtime=remote`.

https://github.com/kubernetes/kubernetes/blob/ea66c00522e0ac5171a6656fda0601b600856528/pkg/kubelet/kubelet.go#L642-L646

Actually such remote runtime has already been incorporated in `kubetypes.DockerContainerRuntime`. There is no need to keep it.

Another usage of `kubetypes.RemoteContainerRuntime` is 

https://github.com/kubernetes/kubernetes/blob/ea66c00522e0ac5171a6656fda0601b600856528/pkg/security/apparmor/validate.go#L114-L117

**What you expected to happen**:

I think it's safe to deprecate `kubetypes.RemoteContainerRuntime`.

**Comment by resouer** [comment]
You mis-understood it :) `RemoteContainerRuntime` is used to describe any CRI runtime implementations rather than Docker. It is always needed unless Docker runtimes is moved from in-tree to another remote container runtime.

I will close this one.

**Comment by dixudx** [comment]
Thanks @resouer for the explanation.
