### ISSUE TITLE
Sporadically get ImagePullBackOff

### ISSUE THREAD

**Issue by ITler** [kubernetes/kubernetes#55691]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I run Kubernetes Cluster 1.7.5 (seen in older versions as well and tested in 1.7.9 as well) on AzureGermanCloud. (K8s is provisioned via Resource Manager template created by `acs-engine`). When it comes to pod deployment, several images will be pulled from one dedicated AWS EC2 container service. To be able to login there, I use `aws ecr get-login [...]` to get login credentials and provide them as a K8s `docker-registry` secret to a dedicated Kubernetes namespace, in which I deploy my applications. Usually, it perfectly works, but **sporadically**, I end up with different deployments to fail in this manner: 

    Warning  Failed      4m (x17 over 1h)   kubelet, k8s-agentpool1-41067869-0  Failed to pull image "URLtoAwsEC2/some_image:tag": rpc error: code = 2 desc = unauthorized: authentication required
    Warning  FailedSync  4s (x302 over 1h)  kubelet, k8s-agentpool1-41067869-0  Error syncing pod
    Normal   BackOff     4s (x285 over 1h)  kubelet, k8s-agentpool1-41067869-0  Back-off pulling image "URLtoAwsEC2/some_image:tag"

It seems to happen randomly. There is no change to registry URL or image's names. Too, the image's tag has no influence on behavior (could be *latest* as well as custom one). Sometimes only one image can't be pulled, another day another image or even multiple can't be pulled. I can't see a pattern. Local docker pulling works like a charm, that's why I guess, this is not an issue on AWS side. There is no change when recreating secrets, individually, delete affected pods and deployments or even tear down and re-provision whole Kubernetes cluster.
What could I check? How could I debug that deeper?
 
**What you expected to happen**:
Work always

**How to reproduce it (as minimally and precisely as possible)**:
Reproducing can't be forced. It's happening, randomly. However, I'm experiencing this since a while, but usually it was magically disappearing. First exception is this week, as I've got issues with same image since yesterday. 
1. Bootstrap Kubernetes
2. Get secret with login credentials for *EC2 container service* in place
3. Deploy pods `kubectl apply -f somefile.yaml`

**Anything else we need to know?**:
No idea what, please ask.

**Comment by ITler** [comment]
@kubernetes/sig-azure-bugs

**Comment by ITler** [comment]
Can't say if this is relevant, but I found that:

```
/var/log/containers/kube-apiserver*.log

{"log":"I1115 07:09:49.472755       1 wrap.go:42] GET /api/v1/namespaces/demo/secrets/registry?resourceVersion=0: (800.44µs) 200 [[hyperkube/v1.7.9 (linux/amd64) kubernetes/19fe919] 172.20.10.4:54810]\n","stream":"stderr","time":"2017-11-
{"log":"I1115 07:09:49.910348       1 logs.go:41] http: TLS handshake error from 168.63.129.16:59459: EOF\n","stream":"stderr","time":"2017-11-15T07:09:49.911205518Z"}
```
I can't judge, if both entries belong together. However `172.20.10.4` is the IP of K8s agent node (currently I use only one node for testing purpose). No clue about `168.63.129.16`, but `whois`tells it belongs to Microsoft network, which is interesting, as AzureGermanCloud should only follow Azure specification, rather than use MS infrastructure.

I couldn't find any other log files showing issues related to image pulling.

**Comment by ITler** [comment]
Error on our site.. No issue here

**Comment by mcwienczek** [comment]
Could you explain what was the reason? We are having similar problem

**Comment by ITler** [comment]
@mcwienczek  Not sure anymore, but as far as I can remember, this was our problem and had nothing to do with k8s.
Double-check, if you really deploy docker registry secret to the correct namespace. Keep in mind, that the login credentials are valid for 24hrs only
