### ISSUE TITLE
AWS EBS volumes from snapshot

### ISSUE THREAD

**Issue by dzoeteman** [kubernetes/kubernetes#55693]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

**What you expected to happen**:
Be able to dynamically provision an AWS EBS volume from a snapshot
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Right now it's not possible to dynamically provision an EBS volume from a snapshot. This is a very useful feature for testing, for example. You can spin a database ready with a dataset in seconds.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.9
- Cloud provider or hardware configuration: AWS

**Comment by dzoeteman** [comment]
I would like to work on this feature as my first contribution. Do I need to create a proposal for this? I think this is not a huge change; an addition in the awsElasticBlockStore config (snapshotID), and add it to the CreateVolume request in the AWS cloudprovider.

**Comment by gnufied** [comment]
Look into snapshot effort https://github.com/kubernetes-incubator/external-storage/tree/master/snapshot which currently sits in that external tree for more information. It already covers restoring PV objects from snapshots.
