### ISSUE TITLE
tolerations.AreEqual() does not take default value into account

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#55719]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig api-machinery

**What happened**:

When using `scheduler.alpha.kubernetes.io/defaultTolerations`, if "Operator" is missing tolerators.AreEqual() returns false even if the pod spec tolerations matches but with an explicit operator `Equal`.

**What you expected to happen**:

"Operator" is default to `Equal`, and I would expect AreEqual() returns true if `Operator` is missing because it defaults to be `Equal`.

**How to reproduce it (as minimally and precisely as possible)**:

With PodTolerationRestriction admission controller enabled, set annotation 

`scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key":"tkey",value":"tvalue","effect":"NoSchedule"}]'`

in a namespace, and tolerate the following in a pod spec,

```
      tolerations:
      - effect: NoSchedule
        key: tkey
        operator: "Equal"
        value: "tvalue"
```

The pod would fail to create due to

`namespace tolerations and pod tolerations conflict`

**Anything else we need to know?**:

Happy to look into it and submit a PR if this is a bug that should be fixed.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: bare metal/on-prem
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): 4.13.8
- Install tools: custom/ansible
- Others:

**Comment by lavalamp** [comment]
We don't want clients to make up defaults if the server didn't set it.

**Comment by lavalamp** [comment]
@thockin this is like the 3rd time this issue has come up for me today...
