### ISSUE TITLE
`kubectl get all` lists some resource types twice

### ISSUE THREAD

**Issue by atombender** [kubernetes/kubernetes#55720]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`kubectl get all` prints the replica set section twice.

**What you expected to happen**:

It should not print dupes.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
$ kubectl get all -l app=myapp
NAME                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/myapp        4         4         4            4           169d

NAME                                  DESIRED   CURRENT   READY     AGE
rs/myapp-1031441472        0         0         0         159d
rs/myapp-1066912010        0         0         0         159d
rs/myapp-1627954893        0         0         0         140d
rs/myapp-1660980575        0         0         0         154d
rs/myapp-2403377231        0         0         0         137d
rs/myapp-2479791910        4         4         4         53d
rs/myapp-3454720083        0         0         0         145d
rs/myapp-3461390017        0         0         0         139d
rs/myapp-3554658816        0         0         0         162d
rs/myapp-3624978688        0         0         0         169d
rs/myapp-378637676         0         0         0         154d
rs/myapp-4151746477        0         0         0         139d
rs/myapp-702975759         0         0         0         159d

NAME                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/myapp        4         4         4            4           169d

NAME                                  DESIRED   CURRENT   READY     AGE
rs/myapp-1031441472        0         0         0         159d
rs/myapp-1066912010        0         0         0         159d
rs/myapp-1627954893        0         0         0         140d
rs/myapp-1660980575        0         0         0         154d
rs/myapp-2403377231        0         0         0         137d
rs/myapp-2479791910        4         4         4         53d
rs/myapp-3454720083        0         0         0         145d
rs/myapp-3461390017        0         0         0         139d
rs/myapp-3554658816        0         0         0         162d
rs/myapp-3624978688        0         0         0         169d
rs/myapp-378637676         0         0         0         154d
rs/myapp-4151746477        0         0         0         139d
rs/myapp-702975759         0         0         0         159d

NAME                                        READY     STATUS    RESTARTS   AGE
po/myapp-2479791910-9w7zx        1/1       Running   0          14d
po/myapp-2479791910-k2p44        1/1       Running   0          14d
po/myapp-2479791910-nb5lj        1/1       Running   0          14d
po/myapp-2479791910-wjmcn        1/1       Running   1          14d

NAME                        TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
svc/myapp        NodePort   10.7.245.217   <none>        80:32046/TCP   169d
```

Correct:

```
$ kubectl get rs,pod -l app=myapp
NAME                                  DESIRED   CURRENT   READY     AGE
rs/myapp-1031441472        0         0         0         159d
rs/myapp-1066912010        0         0         0         159d
rs/myapp-1627954893        0         0         0         140d
rs/myapp-1660980575        0         0         0         154d
rs/myapp-2403377231        0         0         0         137d
rs/myapp-2479791910        4         4         4         53d
rs/myapp-3454720083        0         0         0         145d
rs/myapp-3461390017        0         0         0         139d
rs/myapp-3554658816        0         0         0         162d
rs/myapp-3624978688        0         0         0         169d
rs/myapp-378637676         0         0         0         154d
rs/myapp-4151746477        0         0         0         139d
rs/myapp-702975759         0         0         0         159d

NAME                                        READY     STATUS    RESTARTS   AGE
po/myapp-2479791910-9w7zx        1/1       Running   0          14d
po/myapp-2479791910-k2p44        1/1       Running   0          14d
po/myapp-2479791910-nb5lj        1/1       Running   0          14d
po/myapp-2479791910-wjmcn        1/1       Running   1          14d
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.8.1-gke.1
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhiljindal** [comment]
I see deployments were listed twice as well.

@kubernetes/sig-cli-bugs

**Comment by lichuqiang** [comment]
I'll post a PR to fix it.

**Comment by liggitt** [comment]
the current behavior is correct, given the discovery information published. `replicasets` in the `apps` group are not inherently related to `replicasets` in the `extensions` group as far as the generic aliasing behavior is concerned.

if we don't want both to appear, I'd pursue changing how the server exposes aliases for those types so that only on group or the other lists the `all` alias for itself

**Comment by lichuqiang** [comment]
In fact, as I'm not familiar with api-machinery, I wonder why certain resources exists in both groups.
How we expect user to use them when installing resources?
Is any of them would got removed in the near future?

**Comment by liggitt** [comment]
> In fact, as I'm not familiar with api-machinery, I wonder why certain resources exists in both groups.

Several began life in the `extensions` group and are being migrated to their final homes in the `apps` group. There must be a period of overlap where they can be created/accessed via either group to allow for seamless migration, then they will be removed from the extensions group.

**Comment by lichuqiang** [comment]
Oh, I see. Thanks for explanation. So I think the problem is not an issue of cli to some extent

**Comment by tengqm** [comment]
Maybe the API docs ( https://kubernetes.io/docs/concepts/overview/kubernetes-api/ ) could be of some help. There are some links on that page if you want to dig more. :)

**Comment by dixudx** [comment]
/close

Since this is not bug. @atombender You can reopen it if needed.

**Comment by atombender** [comment]
@dixudx: It might not be a bug on the backend, but it's certainly inconsistent behaviour:  `kubectl get all` should be equivalent to `kubectl get pod,rs,service,deploy,[... rest of types.]`, but it isn't. `kubectl get all` isn't a strict superset.

```
$ kubectl get all | grep "rs/" | wc -l
1158
$ kubectl get rs | wc -l
580
```

That's unexpected. It may be strictly correct in terms of the API protocol, but `kubectl` is a UI that shouldn't leak internal concerns that only confuse. (It also confuses tools that use `kubectl` programmatically to interact with a cluster, which now has to de-dupe the output of `kubectl get all`, for no particularly good reason.)

**Comment by liggitt** [comment]
> `kubectl get all` should be equivalent to `kubectl get pod,rs,service,deploy,[... rest of types.]`, but it isn't

yes, it is

it is equivalent to `kubectl get [...all types listed in discovery as belonging in the 'all' alias]`

that expands to `kubectl get pods.v1,replicasets.v1.apps,replicasets.v1beta1.extensions,...`

> but kubectl is a UI that shouldn't leak internal concerns

I agree. It is because kubectl is just a UI presenting the information surfaced by the API that we have this behavior. Kubectl is basing its behavior on discovery documents published by the API. Handling those generically means it should not bake in magic knowledge that `deployments.v1.apps` and `deployments.v1beta1.extensions` are the same resource.

**Comment by atombender** [comment]
@liggitt I didn't know `kubectl` supported that. That's not documented in the `--help`, and at least some of the types are not working for me:

```
$ kubectl get deployments.v1beta1.extensions | wc -l 
63
$ kubectl get pods.v1 | wc -l
the server doesn't have a resource type "pods" in group "v1"
0
```

The help text implies that `all` is an alias for the resource types listed, which does not show API namespace names (e.g. it's just `pods`, not `pods.v1`).

**Comment by liggitt** [comment]
sorry, `pods.v1.` (note trailing dot... the form is `<resource>.<version>.<group>`, and pods are in the legacy `""` group)

**Comment by anorth2** [comment]
So you're saying it's *valid* for `kubectl get all` to return my replicasets, pods, deployments twice, and no services......
