### ISSUE TITLE
API conventions for webhook (imperative) communication

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#55729]
I think we haven't taken a principled stance on how imperative API calls ought to work in Kubernetes. Most of our API surface area is REST calls and the current API system is optimized for those. We have a few outliers which are special snowflakes (logs, exec, attach, portforward, proxy). But we are recently adding more and more webhooks to the system, and expanding the target audience of who will be implementing the webhooks; and I think therefore it's time to make sure the API patterns we use will make sense to the people who need to implement the webhooks.

Currently, webhooks in the system use the REST styled spec/status objects. But this doesn't make a lot of sense:
1. Why "spec" and "status" instead of "request" and "response"? People will at a minimum have to look up in the API documentation to figure out what they should do. It may feel "natural" to folks who have been working on Kubernetes for the past year or two, but I think that's status quo or familiarity bias, and it won't make sense to anyone fresh to the system.
2. These objects are not intended for long-term persistence; they are not really objects. They are ephemeral constructs that only exist during one small part of the overall request path.
3. The input and output of our existing webhooks are very different data types. It is not very natural to phrase such things as different fields in the same object type. (Imagine writing these as a go function, having the fields of e.g. AdmissionReview as the input parameters and also having the fields of AdmissionReview as the output parameters: `func Review(inSpec spec, _ status) (_spec, outStatus status)`; I think few reviewers on the project would accept that.)

Arguments I have heard in favor of the current one-object system:
 * There's just one type for webhook authors to look up.
   * My response: FooRequest and FooResponse are not really more burdensome to look up.
 * Consistency with our current webhooks
   * My response: consistency with a bad idea belongs in the "con" section. @cheftako says "I'd rather explain why this one is different than explain why we did it a way that we consider wrong."

How do you know if a given thing should follow webhook rules or normal Kubernetes API rules?
* It supports exactly one verb (likely POST)
* It is probably used by control plane infrastructure during the course of servicing a top level (e.g., initiated by a user via `kubectl`) API request.

So, rough proposal:
* Webhooks / imperative calls shall have a specific metadata type.
* Webhook calls will have separate FooRequest and FooResponse types.
* Neither the Request nor the Response shall contain "spec" or "status" fields.

HookMeta should look like this, not sure if we need any other fields right now:

```go
// HookMeta contains metadata that is used to track webhook (imperative) requests.
// Webhooks must echo back everything here in their response.
// This is different from ObjectMeta and ListMeta because webhook (imperative) calls
// do not represent objects, nor do they represent lists of objects: they represent commands.
type HookMeta struct {
  // UID is a time-and-space unique identifier to this particular invocation of the webhook.
  // It is useful for matching up logs / audit logs between caller and callee, and for proving
  // that the callee is responding to the correct response (doesn't have any weird
  // caching bugs, for example).
  UID UID
}
```

And an example webhook API might be:

```go
type AdmissionReviewRequest struct {
  TypeMeta `json:",inline"`
  HookMeta `json:"metadata"`

  Kind GVR
  Resource GVR
  Namespace string
  Name string
  ...
}

type AdmissionReviewResponse struct {
  TypeMeta `json:",inline"`
  HookMeta `json:"metadata"`
  
  Allowed bool
  Status *metav1.Status
  
  // mutating webhooks may set...
  PatchType string
  Patch []byte
}
```

Finally, what should we do about existing webhooks which do not use this format? I think, for any that are alpha, we should require they change to this format for beta. For ones seeking to go beta -> v1, we should consider the costs to making existing implementations change, with a bias towards making the API change for v1. For webhooks that are already in v1 (SubjectAccessReview?), we should not change until we're ready to go to v2.

**Comment by smarterclayton** [comment]
Is this really worth changing?  We've basically locked in a pattern for a number of things (like SAR and RAR) - introducing something new and novel, even if it's better, doesn't seem like a good use of time.

**Comment by deads2k** [comment]
> Is this really worth changing? We've basically locked in a pattern for a number of things (like SAR and RAR) - introducing something new and novel, even if it's better, doesn't seem like a good use of time.

Also SubjectRulesReview, TokenReview, and ImageReview.

**Comment by smarterclayton** [comment]
Note I agree with your points - if we were starting fresh, these are the arguments I would make (also, I made these arguments before).  But is it really worth coming up with something new?

**Comment by lavalamp** [comment]
We are making something new, as it happens. Do we want to keep repeating the same mistakes?

**Comment by smarterclayton** [comment]
We're making something new that is at least consistent with existing web hook calls.  If we add one more pattern to the mix, does that actually make end users lives better?  They'd have to reason about why it was one way for one type of web hook, and different ways for the other web hooks.

**Comment by lavalamp** [comment]
I think that is offset by doing it in a more sensible way. Like, probably everyone is going to understand the FooRequest and FooResponse pattern.

Additionally, I am not sure the same users for existing webhooks will be the majority of users for the new webhooks. If that is the case, few actual people will be inconvenienced.

Of note you are like the 5th person to say you wanted it like this from the very beginning-- I'm not sure how we ended up with a system that everyone claims they didn't want.

**Comment by lavalamp** [comment]
I'm making a bigger deal of this than I would ordinarily; @cheftako pointed out that if we're going to beta, we really ought to be doing it with an API we believe in.

**Comment by smarterclayton** [comment]
> I'm not sure how we ended up with a system that everyone claims they didn't want.

Worse is better.  We shipped, got something working, etc.

> I think that is offset by doing it in a more sensible way.

Do I need to link the XKCD with 15 standards?

**Comment by erictune** [comment]
Nitpick:

"Is a Webhook" is a subset of "Is Imperative". SubjectAccessReview is not a webhook, but it is imperative.

**Comment by lavalamp** [comment]
Yeah, I went with "HookMeta" because "ImperativeCallMeta" was quite a mouthful. Definitely open to other names.

**Comment by lavalamp** [comment]
> Do I need to link the XKCD with 15 standards?

1 -> 2 is a lot more sensible than 14 -> 15 =D

**Comment by jbeda** [comment]
For the record, having a consistent pattern (even if it is a little funky) is preferred over inventing new terminology.

I also think that there is a good chance that for some of these patterns (at some point) we may want to introduce an async flow.  That creates a middle ground where something is logically a request/response type thing but isn't expected to be answered while the caller is on the line.  I look at the CSR API as a perfect example of that.  It could logically be implemented as a webhook but, because we understood there might be a human in the loop, it was implemented as an async request.

**Comment by cheftako** [comment]
Is standardization of imperative/declarative across disparate calls really the form of standardization we want? The majority of our APIs are symmetric and declarative. So standardizing on a set of terminology and libraries has brought us a lot of benefit. It has been an excellent way to communicate both similarities and intended usage patterns of calls which are fundamentally consistent. The APIs we are talking about now, are not symmetric and as @lavalamp points out they are not declarative. So I think attempting to shoehorn them into the existing standards is disingenuous, confusing and I think in the long wrong it will actually harm the very standards we are trying to uphold. If the standard no longer means its symmetric or declarative, then it will no longer mean anything.

**Comment by lavalamp** [comment]
There is 0 chance this api will turn into an async thing. We have initializers for that already.

**Comment by smarterclayton** [comment]
Another topic:  I'm skeptical on HookMeta because we also want request identifiers for regular API calls and they won't go on the hooks themselves.  I.e. a Pod POST should be able to carry a request identifier, and we aren't going to add that to ObjectMeta without a lot more discussion.  I'd simplify your proposal to avoiding HookMeta for now.

**Comment by lavalamp** [comment]
We could also set such things in headers, but I didn't make progress last time I recommended a thing like that.

**Comment by smarterclayton** [comment]
I actually had a PR open for it....

**Comment by smarterclayton** [comment]
The reason we have one object for the other review types is because it simplifies audit and reasoning.  That's not a meaningless advantage - it simplifies client implementations, reduces the amount of distributed doc, can be written to other places.

request/response is very RPC.  I agree that these are request/response patterns.  I'd probably fall on the "why introduce a novel way to represent something" side of the argument - the moment we have a new pattern, I'm going to have some young blood excited and eager to introduce SubjectAccessReview v2, and then I'll have to waste time discussing how refactoring existing stuff may not be the highest priority the project has (even if we probably will do it someday).

**Comment by jbeda** [comment]
@lavalamp Are we talking about a specific API or are we talking about the pattern in general? While we may be sure that a specific API won't ever be async, this issue is about the larger theme about how we think about these.  And I don't have confidence that the line is as bright as we are making it out to be.

**Comment by lavalamp** [comment]
> the moment we have a new pattern, I'm going to have some young blood excited and eager to introduce SubjectAccessReview v2, and then I'll have to waste time discussing how refactoring existing stuff may not be the highest priority the project has (even if we probably will do it someday).

Just direct them to me, I will explain how APIs Are Forever. (Which is also why I'm still yammering on about this at all.)

Also I think @cheftako's point was understated-- forcing everything into the declarative spec/status model makes the model lose meaning. If only declarative things are phrased in declarative ways, then seeing a declarative object tells you a lot about the API you're about to interact with. If everything is phrased that way, then it tells you nothing about the API you're about to interact with.

**Comment by erictune** [comment]
@jbeda Initializers are similar to Webhooks but better suited for async.  
See discussion here:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/admission-control-webhooks.md#comparison-of-webhooks-and-initializers
