### ISSUE TITLE
Build tags should be in properly suffixed files

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#55750]
From https://github.com/kubernetes/kubernetes/pull/55712#issuecomment-344421233:
>We should add a verify check that build tags are only used in appropriately suffixed files.
>
>`// +build linux shouldn't occur in a file that isn't marked as OS-specific.`

Based on [this](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool), this isn't really a golang enforced thing, but we use it to trigger the cross compile in CI.

---
/area build-release
/sig testing

**Comment by cblecker** [comment]
cc @rmmh @ixdy @kubernetes/sig-testing-misc

**Comment by cblecker** [comment]
I whipped up a verify script to do this (https://github.com/kubernetes/kubernetes/pull/55749), although I'm not sure if this is actually something we want to do.

**Comment by BenTheElder** [comment]
Let's do this. Cross build is frequently broken by incompatible method signature changes between platforms.
We can:
- enforce build tags in file names
- match these in `run_if_changed` for `pull-kubernetes-cross`
- [enforce cross is blocking on these PRs](https://github.com/kubernetes/test-infra/issues/5584)

**Comment by thockin** [comment]
How does the cross test not catch these busted PRs?

**Comment by BenTheElder** [comment]
> How does the cross test not catch these busted PRs?

1) Cross runs against PRs that change files matching a regex since it's an expensive job, so it may not have run against these bad PRs since they change files without `_platform` in the file name.
2) [Cross isn't currently blocking because there was a bug with this type of run_if_changed job](https://github.com/kubernetes/test-infra/issues/5584), the bug should be fixed now so we can make cross block PRs that it runs against once we fix it.

**Comment by cblecker** [comment]
/remove-lifecycle stale
Not stale, but https://github.com/kubernetes/kubernetes/pull/59289 is a better direction

**Comment by BenTheElder** [comment]
yeah, cross *was* made blocking again but #59289 is the way to go for anything besides touching the build scripts. that's cheap enough we can just run it on every PR

**Comment by cblecker** [comment]
#59289 was merged

**Comment by BenTheElder** [comment]
though not blocking *yet*, I want to very soon, so far it looks great
