### ISSUE TITLE
kubelet unable to mount volumes in azure statefulsets

### ISSUE THREAD

**Issue by brucemartins** [kubernetes/kubernetes#55763]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

/sig azure

**What happened**:
statefulsets running on azure fail to mount volumes to the container 
**What you expected to happen**:
the kubelet should mount the volume as expected as a part of launching the stateful set, it appears the kubelet does not create the directory based on strace 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Volumes are created in azure, they are attached to the proper nodes, it seems based on the below strace that the kubelet cannot mount the volume because the directory does not exist ?

**** strace *****
[pid  3835] execve("/usr/bin/mount", ["mount", "-t", "ext4", "-o", "bind", "/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b2272457455", "/var/lib/kubelet/pods/70c047b8-c9ba-11e7-903a-02420ac83d03/volumes/kubernetes.io~azure-disk/pvc-70bf5e10-c9ba-11e7-903a-02420ac83d03"], ["LANG=en_US.UTF-8", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"]) = 0
[pid  3835] mount("/var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b2272457455", "/var/lib/kubelet/pods/70c047b8-c9ba-11e7-903a-02420ac83d03/volumes/kubernetes.io~azure-disk/pvc-70bf5e10-c9ba-11e7-903a-02420ac83d03", 0x7fea36c2c240, MS_MGC_VAL|MS_BIND, NULL) = -1 ENOENT (No such file or directory)
[pid  3835] +++ exited with 32 +++
[pid 10477] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=3835, si_status=32, si_utime=0, si_stime=0} ---

**** end strace ****

**Environment**:
- Kubernetes version (use `kubectl version`): 
v1.7.10

- Cloud provider or hardware configuration:
kubelet config

  --cloud-provider=azure \
  --cloud-config=/etc/kubernetes/cloud/cloud.cfg \
  --v=0

/etc/kubernetes/cloud/cloud.cfg
{
  "tenantId": "xxxxx-xxxx-xxxxx-xxxxxx-xxxxxxxxx",
  "subscriptionId": "xxxxxx-xxxx-xxxxxx-xxxx-xxxxxxx",
  "aadClientId": "xxxxxxxxxxxxxxxxxx",
  "aadClientSecret": "xxxxxxxxxxxxxxxxxxxx",
  "resourceGroup": "myresource",
  "location": "eastus",
  "subnetName": "app-subnet",
  "securityGroupName": "Internal",
  "vnetName": "my-network"
}
- OS (e.g. from /etc/os-release):
[root@kubenode6 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:  
ansible
- Others:

**Comment by andyzhangx** [comment]
@brucemartins could you also share your pod info and kubelet log in that agent node? 
```
kubectl describe pod PODNAME
id=`docker ps -a | grep "hyperkube kubelet" | awk -F ' ' '{print $1}'`
docker logs $id > $id.log 2>&1
vi $id.log
```
It seems attaching disk on agent does not succeed.

**Comment by brucemartins** [comment]
@andyzhangx azure seems to have the disk attached, I recently tried with a newer version of CENTOS 7.3 with the same results, but here is the below
`Name:           es-data-0
Namespace:      vms
Node:           kubenode4/10.20.0.10
Start Time:     Fri, 17 Nov 2017 20:32:06 +0000
Labels:         app=elasticsearch
                controller-revision-hash=es-data-3894916895
                name=es-data
                version=2.4.5
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"vms","name":"es-data","uid":"5fecf696-cbd6-11e7-816b-0242ac110003","apiVersion":...
                pod.alpha.kubernetes.io/initialized=true
Status:         Pending
IP:
Created By:     StatefulSet/es-data
Controlled By:  StatefulSet/es-data
Containers:
  es-data:
    Container ID:
    Image:              registry.service.consul:5000/elasticsearch:2.4.5
    Image ID:
    Ports:              9200/TCP, 9300/TCP
    Args:
      -Des.cluster.name=vms_es
      -Des.node.data=true
      -Des.node.master=false
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.discovery.zen.ping.unicast.hosts=elasticsearch
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Limits:
      cpu:      500m
      memory:   4Gi
    Requests:
      cpu:              500m
      memory:           4Gi
    Liveness:           http-get http://:9200/_cluster/health delay=180s timeout=5s period=10s #success=1 #failure=3
    Environment:        <none>
    Mounts:
      /usr/share/elasticsearch/data from vol-elastic (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-760g0 (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  vol-elastic:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vol-elastic-es-data-0
    ReadOnly:   false
  default-token-760g0:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-760g0
    Optional:   false
QoS Class:      Guaranteed
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  7m            7m              2       default-scheduler                       Warning         FailedScheduling        PersistentVolumeClaim is not bound: "vol-elastic-es-data-0" (repeated 11 times)
  7m            7m              1       default-scheduler                       Normal          Scheduled               Successfully assigned es-data-0 to kubenode4
  7m            7m              1       kubelet, kubenode4                      Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-760g0"
  7m            1m              11      kubelet, kubenode4                      Warning         FailedMount             MountVolume.SetUp failed for volume "pvc-5ff1e88c-cbd6-11e7-baf6-0242ac110003" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 /var/lib/kubelet/pods/5ff37135-cbd6-11e7-baf6-0242ac110003/volumes/kubernetes.io~azure-disk/pvc-5ff1e88c-cbd6-11e7-baf6-0242ac110003 ext4 [bind]
Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 does not exist


  5m    1m      3       kubelet, kubenode4              Warning FailedMount     Unable to mount volumes for pod "es-data-0_vms(5ff37135-cbd6-11e7-baf6-0242ac110003)": timeout expired waiting for volumes to attach/mount for pod "vms"/"es-data-0". list of unattached/unmounted volumes=[vol-elastic]
  5m    1m      3       kubelet, kubenode4              Warning FailedSync      Error syncing pod`


here is the kubelet snippet

`Nov 17 20:46:16 kubenode4 kubelet[48577]: W1117 20:46:16.039588   48577 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Nov 17 20:46:26 kubenode4 kubelet[48577]: W1117 20:46:26.049454   48577 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Nov 17 20:46:26 kubenode4 kubelet[48577]: E1117 20:46:26.528342   48577 mount_linux.go:122] Mount failed: exit status 32
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting command: mount
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 /var/lib/kubelet/pods/5ff37135-cbd6-11e7-baf6-0242ac110003/volume
Nov 17 20:46:26 kubenode4 kubelet[48577]: Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 does not exist
Nov 17 20:46:26 kubenode4 kubelet[48577]: I1117 20:46:26.528426   48577 azure_mounter.go:109] azureDisk - SetupAt:Mount disk:kubernetes-dynamic-pvc-5ff1e88c-cbd6-11e7-baf6-0242ac110003 at dir:/var
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting command: mount
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 /var/lib/kubelet/pods/5ff37135-cbd6-11e7-baf6-0242ac110003/volume
Nov 17 20:46:26 kubenode4 kubelet[48577]: Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 does not exist
Nov 17 20:46:26 kubenode4 kubelet[48577]: , will attempt to clean up
Nov 17 20:46:26 kubenode4 kubelet[48577]: E1117 20:46:26.528553   48577 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/azure-disk/5ff37135-cbd6-11e7-baf6-0242ac110003-pvc-5ff1e88c-
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting command: mount
Nov 17 20:46:26 kubenode4 kubelet[48577]: Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 /var/lib/kubelet/pods/5ff37135-cbd6-11e7-baf6-0242ac110003/volume
Nov 17 20:46:26 kubenode4 kubelet[48577]: Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/b3759809597 does not exist`

**Comment by andyzhangx** [comment]
@brucemartins 
thanks for reporting this issue, could be something wrong with `formatAndMount` code. I would like to repro it on azure by myself. 
Do you have guideline or best practice how to deploy k8s on centos? I used to deploy on Ubuntu by acs-engine.

**Comment by brucemartins** [comment]
i was able to resolve it @andyzhangx  there was a bug in the deployment code, which was causing the --cloud-provider and --cloud-config to not be read properly due to a missing "\"  I will close this and appreciate your help with this

**Comment by andyzhangx** [comment]
good to know, thx
