### ISSUE TITLE
I am not able to start Kubernetes cluster

### ISSUE THREAD

**Issue by sinha29492** [kubernetes/kubernetes#55765]
I was following steps mentioned in below link to start kubernetes cluster 
https://cloud.google.com/solutions/real-time/kubernetes-pubsub-bigquery
I am not able to start the cluster. I am trying to execute this in Windows machine using cygwin 64. Initially I was getting an error as dir name is invalid command -
/cygdrive/c/Users/avinsinha/AppData/Local/Google/Cloud SDK/kubernetes/cluster/../cluster/kube-util.sh: line 21: dirname: command not found
To resolve this I tweaked the script and replaced dirname command with pwd. Now I am getting below error.
 Please help me to resolve the problem.
Below is the error that I am getting :
$ kube-up.sh
/cygdrive/c/Users/avinsinha/AppData/Local/Google/Cloud SDK/kubernetes/cluster/../cluster/kube-util.sh: line 38: [: /cygdrive/c/Users/avinsinha/AppData/Local/Google/Cloud: binary operator expected
... Starting cluster using provider: gce
... calling verify-prereqs
Skeleton Provider: verify-prereqs not implemented
... calling verify-kube-binaries
./kube-up.sh: line 44: verify-kube-binaries: command not found

**Comment by sinha29492** [comment]
Sorry I did not get you. What exactly are u asking for ?

**Comment by dims** [comment]
Windows is not a supported platform for kube-up.sh AFAIK. Sorry.

/close

**Comment by ashishkarpe-compumatrice** [comment]
Add '/home/ubuntu/kube/kubernetes/client/bin' to your PATH to use newly-installed binaries.
Creating a kubernetes on ubuntu...
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Skeleton Provider: verify-prereqs not implemented
... calling verify-kube-binaries
./cluster/kube-up.sh: line 65: verify-kube-binaries: command not found
****************************************************************************
Is ubuntu suported ? runnung ubuntu on aws instance so tried provider as aws

**Comment by shenshouer** [comment]
version of v1.10.5:

```
➜  kubernetes export VAGRANT_DEFAULT_PROVIDER=parallels
export KUBERNETES_PROVIDER=vagrant
➜  kubernetes ./cluster/kube-up.sh
... Starting cluster using provider: vagrant
... calling verify-prereqs
Skeleton Provider: verify-prereqs not implemented
... calling verify-kube-binaries
./cluster/kube-up.sh: line 65: verify-kube-binaries: command not found
```

**Comment by EdisonSu768** [comment]
version of v1.11.1:
```
./cluster/kube-up.sh
... Starting cluster using provider: vagrant
... calling verify-prereqs
Skeleton Provider: verify-prereqs not implemented
... calling verify-kube-binaries
./cluster/kube-up.sh: line 65: verify-kube-binaries: command not found
```

macOS 10.13.3
