### ISSUE TITLE
kubemark jobs are failing

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#55770]
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-500
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000

/sig scalability
cc @kubernetes/sig-scalability-bugs

**Comment by shyamjvs** [comment]
Let's close this one.. as the other bug has more info.
/close
