### ISSUE TITLE
Azure disk dose not work as expected

### ISSUE THREAD

**Issue by weherdh** [kubernetes/kubernetes#55776]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
For unmanaged disk, now it is not working
**What you expected to happen**:
Works well
**How to reproduce it (as minimally and precisely as possible)**:
```
# kubectl get sc
NAME      PROVISIONER                AGE
scazure   kubernetes.io/azure-disk   4h
# kubectl get sc scazure -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: 2017-11-15T03:15:24Z
  name: scazure
  resourceVersion: "5718"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/scazure
  uid: 3896d86f-c9b3-11e7-9c74-000d3a139483
parameters:
  location: eastus
  storageAccount: storage
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete

# kubectl describe pvc azpvc
Name:          azpvc
Namespace:     default
StorageClass:  scazure
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=scazure
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/azure-disk
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  6s (x2 over 17s)  persistentvolume-controller  Failed to provision volume with StorageClass "scazure": Create Storage Account: %!!(MISSING)(EXTRA string=001), error: storage.AccountsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDoubleEncodedRequestUri" Message="The request URI 'https://management.azure.com:443/subscriptions/.../resourceGroups/openshift/providers/Microsoft.Storage/storageAccounts/%!!(MISSING)(EXTRA%!s(MISSING)tring=001)?api-version=2017-06-01' is not valid, because it contains double encoding sequence '%!'(MISSING)."
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2.734+2d64ce5e8e45e2", GitCommit:"2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761", GitTreeState:"clean", BuildDate:"2017-11-14T03:26:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.2.734+2d64ce5e8e45e2", GitCommit:"2d64ce5e8e45e26b02492d2b6c85e5ebfb1e4761", GitTreeState:"clean", BuildDate:"2017-11-14T03:26:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): RHEL7
- Kernel (e.g. `uname -a`):
- Install tools: ansible
- Others:

**Comment by andyzhangx** [comment]
@weherdh I cannot reproduce your issue with v1.9.0, in your storage class, an azure disk would be provisioned in storage account `storage`, it may fail because name `storage` is already occupied, but in your case it's a strage string: `%!!(MISSING)(EXTRA%!s(MISSING)tring=001)`. 
So could you also paste the controller manager log, below is the way how to get it:
```
id=`docker ps -a | grep "hyperkube controlle" | awk -F ' ' '{print $1}'`
docker logs $id > $id.log 2>&1
vi $id.log
```
There should be an important log like following:
```
azureDisk - no key found for storage account ...
```

**Comment by weherdh** [comment]
I did not run containerized k8s, I deployed a cluster by ansible: https://github.com/kubernetes/contrib/tree/master/ansible. I got the controller message as below:
```
# journalctl -u kube-controller-manager.service | grep azureDisk
Nov 16 02:48:41 example.com kube-controller-manager[568]: I1116 02:48:41.526836     568 azure_blobDiskController.go:239] azureDisk - creating blob data disk named:kubernetes-dynamic-pvc-b2346ab2-c9db-11e7-9c74-000d3a139483 on StorageAccountType:Standard_LRS StandAlone:false
Nov 16 02:48:41 example.com kube-controller-manager[568]: I1116 02:48:41.526851     568 azure_blobDiskController.go:679] azureDisk - failed to identify a suitable account for new disk and will attempt to create new account
Nov 16 02:48:41 example.com kube-controller-manager[568]: I1116 02:48:41.778003     568 azure_blobDiskController.go:604] azureDisk - Creating storage account %!(EXTRA string=001) type Standard_LRS
Nov 16 02:48:56 example.com kube-controller-manager[568]: I1116 02:48:56.527296     568 azure_blobDiskController.go:239] azureDisk - creating blob data disk named:kubernetes-dynamic-pvc-b2346ab2-c9db-11e7-9c74-000d3a139483 on StorageAccountType:Standard_LRS StandAlone:false
```
I am quit sure there is already a storage account in its resource group which is assigned in sc's parameter:
```
parameters:
  location: eastus
  storageAccount: storage
```
I do not know why controller does not find it and wants to create a new one. But in our subscription the storage account has reached the max number and cannot be created anymore, the error is different from this.

**Comment by weherdh** [comment]
cc @rootfs

**Comment by andyzhangx** [comment]
@weherdh would you add `kind: dedicatged` in your stroage class, and try again?
In your case, `setUniqueStrings` is not invoked due to:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_blobDiskController.go#L546

I am working out a PR to fix this, as a workaround, you could try storage class like following:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
parameters:
  kind: dedicatged
  location: eastus
  storageAccount: storage
```

Let me know if that works, thx

**Comment by weherdh** [comment]
Yes. working now with this parameter added:
```
# kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
azpvc     Bound     pvc-c5b3836c-ca92-11e7-a25b-000d3a139483   1Gi        RWO            scazure        5s
```
