### ISSUE TITLE
Missing permissions for "system:kube-controller-manager" role

### ISSUE THREAD

**Issue by vendrov** [kubernetes/kubernetes#55778]
I'm using only RBAC authorization and I created manually API token from existing service-account (following this guide: https://kubernetes.io/docs/admin/service-accounts-admin/#to-create-additional-api-tokens)

The new secret has been created but it was empty without any data. I looked at the kube-manager-controller logs and I found this error:

`E1114 22:42:53.439415       6 tokens_controller.go:326] error populating serviceaccount token test/web-token for service account web-serviceaccount: User "system:kube-controller-manager" cannot get secrets in the namespace "test". (get secrets web-token)`

I found that the user above is bind to the "system:kube-controller-manager" Cluster-Role, after I added the missing permissions "get" **and** "update" for secrets, I created a new secret again and this time it was populated.

The kube-controller "use-service-account-credentials" flag is **enabled**

We use K8S 1.6.2 on Ubuntu 16.04

kind bug
@kubernetes/sig-auth-bugs
/sig auth

**Comment by redbaron** [comment]
default RBAC  groups and policies evolved quite a lot since 1.6.x times, you might find it easier to use 1.8.x for all RBAC features

**Comment by vendrov** [comment]
@redbaron - Would you mind to approve that this has been fixed in the next releases?

**Comment by vendrov** [comment]
Seems your are right, it has been fixed in this commit:
https://github.com/kubernetes/kubernetes/commit/32735173dfd081997066bfaeb9b2783bc9f52f51
