### ISSUE TITLE
apiserver: allow to pass a listener into genericapiserver bootstrapping

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#55784]
We should allow to pass a tcp listener into an API server via GenericApiServer config. This will allow us to use kernel zero-port allocation `localhost:0` to find a free port instead of the retry loops we have everywhere in tests.

At the moment we pass a port via the options into the config. A zero port does not work because the loopback clients created during apiserver initialization need to know the port before. Passing a listener into the server instead would allow us to use a zero port beforehand and bootstrapping order should be fine.

Solves https://github.com/kubernetes/kubernetes/issues/42224.

**Comment by hzxuzhonghu** [comment]
I will work on this.
