### ISSUE TITLE
Load test metadata-proxy

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#55797]
Offshoot of regression - https://github.com/kubernetes/kubernetes/issues/55695

We are supporting "100 pods per node" in k8s officially (https://kubernetes.io/docs/admin/cluster-large/#support) and need to make sure metadata-proxy allows those many pods to access the metadata service simultaneously.

cc @kubernetes/sig-node-bugs @ihmccreery @cjcullen @loburm

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-misc

**Comment by ihmccreery** [comment]
Xref https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/12
