### ISSUE TITLE
Horizontal Pod Autoscaler doesn't have permissions to read Custom Metrics API

### ISSUE THREAD

**Issue by kawych** [kubernetes/kubernetes#55805]
/kind bug

**What happened**:
E2e tests for Horizontal Pod Autoscaler using Stackdriver Custom Metrics are failing on HPA reading from custom metrics API: https://k8s-testgrid.appspot.com/sig-autoscaling#gci-gce-autoscaling
From test logs:
I1115 06:22:31.893] Nov 15 06:22:31.888: INFO: At 2017-11-15 06:07:57 +0000 UTC - event for custom-metrics-objects-hpa: {horizontal-pod-autoscaler } FailedGetObjectMetric: unable to get metric foo-metric: Pod on e2e-tests-horizontal-pod-autoscaling-mdc6q stackdriver-exporter-pod/unable to fetch metrics from API: pods.custom.metrics.k8s.io "stackdriver-exporter-pod" is forbidden: User "system:anonymous" cannot get pods.custom.metrics.k8s.io/foo-metric in the namespace "e2e-tests-horizontal-pod-autoscaling-mdc6q"

**What you expected to happen**:
HPA is supposed to be able to read custom metrics API, as defined here: https://github.com/kubernetes/kubernetes/blob/f34fb9b0ab37daf71d2d246db7e13a88a41ff359/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml#L497

**How to reproduce it (as minimally and precisely as possible)**:
This e2e test can be run manually with command:
go run hack/e2e.go -- -v --build --up --test --test_args="--ginkgo.focus=\[Feature:CustomMetricsAutoscaling\]"

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: GCE

@liggitt @shyamjvs @aleksandra-malinowska PTAL

**Comment by kawych** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by liggitt** [comment]
that indicates the API aggregator and metrics server don't have authentication configured correctly. What environment is this in and what setup method is it using?

**Comment by kawych** [comment]
Note that this is not custom.metrics.k8s.io as opposed to metrics.k8s.io, which is the metric server's API. The API server for custom.metrics.k8s.io was deployed with this yaml file: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/adapter-beta.yaml

The behavior I expected was that HPA will use permissions specified here: https://github.com/kubernetes/kubernetes/blob/f34fb9b0ab37daf71d2d246db7e13a88a41ff359/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml#L497

Previously additional cluster role binding was created for HPA, system:anonymous and system:unauthenticated, but it was removed in https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/65 because
1. I expected the permission for SA horizontal-pod-autoscaler to be sufficient
2. There is a bug that ClusterRoles can't be created on GKE without some additional workaround (don't have a link right now, can look for it if needed).

Is my understanding correct? If not, what's the purpose of cluster role and cluster role binding system:controller:horizontal-pod-autoscaler?

**Comment by mattjmcnaughton** [comment]
Looks like https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/68 has been closed - nice work @kawych :) Does that mean this issue can be closed?

**Comment by kawych** [comment]
According to my understanding, this is still not fixed, I think that HPA should be able to read custom metrics without creating additional cluster role and cluster role binding.

@liggitt @mwielgus @DirectXMan12 - is it correct? Or, if the current behaviour is intended, can you please explain why do we have cluster role and cluster role binding "system:controller:horizontal-pod-autoscaler"?

**Comment by DirectXMan12** [comment]
the HPA controller should be able to read anything in the `custom.metrics.k8s.io` with default cluster policy -- it shouldn't require any additional roles to do so.  If it does, that's a bug.  If it's coming through as `system:anonymous` or `system:unauthenticated`, that means that your CM adapter or your aggregator isn't doing delegated authentication properly (it's probably not a bug in the policy or in Kubernetes proper).  Try running the aggregator and the CM adapter with higher verbosity levels, but I suspect it's due to this: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/adapter-beta.yaml#L80 which is incorrect (you need the proxy CA).  Please read through: https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md

**Comment by MaciekPytel** [comment]
Just removing the --requestheader-client-ca-file flag from yaml seems to fix the issue. I tested it and HPA can now access custom metrics just using the default cluster policy. @DirectXMan12 thanks for pointing me in the right direction.
