### ISSUE TITLE
`kubectl run` should support the command to execute the container with

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#5581]
So you can do easy demos of "run image X and tell it to run command Y forever".

**Comment by smarterclayton** [comment]
Or even better it should be after a `--` like exec.

**Comment by smarterclayton** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/2316 will make this easier / possible.

**Comment by bgrant0607** [comment]
I'm not sure I understand.

Are you asking for the ability to generate the new RC, not unlike run-container, and for that generator to accept both the container image and the container command?

**Comment by smarterclayton** [comment]
run-container should support an additional option which is --command.  It's pretty common in the "i have this image, I want to run it" that the thing I want to run isn't the default command, or is a variant on the default command where I add options and flags.  For example, I have an image that starts apache.  I want to try testing it with debug flags because it's not working when I go the "normal" path.  I use run-container to quickly spin the image up and test it, if it doesn't work i delete it and retry.  Or flags to other daemons.

----- Original Message -----

**Comment by bgrant0607** [comment]
Ok.Totally agree.

**Comment by smarterclayton** [comment]
Oh, I didn't realize I typo'd the title.... run-container, not rollingupdate

**Comment by smarterclayton** [comment]
Ideal CLI design would be like `exec`:

    kubectl run-container <name> --image=... [-- <command>]

i.e.

    kubectl run-container mypod --image=centos:centos7 -- /bin/bash sleep 1d

**Comment by bgrant0607** [comment]
Would those map to Command or to Args? Or do you imagine using a heuristic to decide (e.g., first arg has a leading slash implies Command)?

**Comment by thockin** [comment]
Docker precedent - they are "args" (what docker calls CMD).  We may also want a --command flag (docker's --entrypoint).

**Comment by smarterclayton** [comment]
I'm thinking args is the default and command is available via a flag, like Tim suggests.

**Comment by thockin** [comment]
It's the only sane way, if you want to support containers that have
ENTRYPOINT - I wish we didn't have to, but I think we do.

**Comment by Iwan-Zotow** [comment]
Looks like one could do this today with kubectl run job0 --image=gcr.io/PID/IID --overrides='{"apiVersion": "v1", "spec": {"template":{"spec": {"containers": [ {"name": "job0", "image": "gcr.io/PID/IID", "args":[ "arg0", "arg1", ...] } ] } } } }'
