### ISSUE TITLE
CSR approver controller should be able to approve CSRs for control plane components

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#55822]
cc @kubernetes/sig-auth-feature-requests 
cc @mikedanese @jcbsmpsn

For self-hosted Kubernetes, I'd like to be able to bootstrap new API servers, and possibly etcd instances, on new nodes after I've bootstrapped the kubelet. Possibly through an init container that creates a CSR, then passes it along to the app. These boil down to:

* Approve a client certificate request for a specific CN.
* Approve a serving certificate request for a specific DNS name or IP address.

Because all of the existing CSR approval processes are node specific I can't whitelist a service account to request arbitrary CNs like "system:apiserver"  or "system:etcd"

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by deads2k** [comment]
The client certificate may be fulfilled differently based on the outcome of the container identity, but the serving certificate would be pretty useful.  Getting a signed serving certificate for a service is half of the problem.  How would you distribute the signing CA to various actors and pods who need to verify the server?

**Comment by ericchiang** [comment]
> The client certificate may be fulfilled differently based on the outcome of the container identity, but the serving certificate would be pretty useful.

The certificates API records the user info that made the request, while container identity is about credentials. Won't the csrapprover be acting on username/uid/groups/extra regardless of the container identity outcome?

> How would you distribute the signing CA to various actors and pods who need to verify the server?

For our use cases, the CA is the API server CA. It'd be in the same bundle passed to pods for their in-cluster client.

**Comment by deads2k** [comment]
> For our use cases, the CA is the API server CA. It'd be in the same bundle passed to pods for their in-cluster client.

I don't think that this should be a starting recommendation.  In the general case, a portable pod spec would need understand the distinction between trust for various actors.  Assuming that the same signing key signed both doesn't seem right.



> The certificates API records the user info that made the request, while container identity is about credentials. Won't the csrapprover be acting on username/uid/groups/extra regardless of the container identity outcome?

I would not have started designing an API there.  It seems like the general case is "subject A requests a certificate for subject B".  I'd want to work out how the general case could or should work before doing a specific simplification.

In addition, the work I've been hearing about has been around having a different, pluggable mechanism for asserting container identity and then using that to make higher level assertions like "this container can have an identity of that SA"

**Comment by mikedanese** [comment]
> a portable pod spec would need understand the distinction between trust for various actors. Assuming that the same signing key signed both doesn't seem right.

Can you outline a scenario? This is simple for the case where I want a pod to trust all cluster local actors but I can see how this becomes complex when we introduce multiple clusters.

**Comment by bjhaid** [comment]
> This is simple for the case where I want a pod to trust all cluster local actors but I can see how this becomes complex when we introduce multiple clusters.

We have multiple clusters and were going down this route to unify our CA across this clusters, our plan is to have one root CA and generate an intermediate CA per cluster which will allow workloads trust themselves across our clusters, hence I am interested in this featur. I'll like to be able to specify RBAC to allow a SA submit/approve a CSR for a particular set of domain names or some sub-resource that can identify the CSR.
