### ISSUE TITLE
Logging bottleneck in RBAC for denials

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#55821]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

For extremely high volumes of requests (e.g. many pod create requests, each doing many PSP authorization calls, detailed [here](https://docs.google.com/document/d/1IIcHHE_No1KMAybW5krIphdN325eGa2sxF2eqg2YAPI/edit#)), the log line in the RBAC authorizer becomes a bottleneck:

https://github.com/kubernetes/kubernetes/blob/cbdd18eee97369197dc3db0d3c85bf261e529903/plugin/pkg/auth/authorizer/rbac/rbac.go#L116

**What you expected to happen**:

I expect RBAC to be able to handle high volumes of simultaneous authorizations. A couple options include:

- Raise the verbosity level on that log, basically disabling it when high performance is a concern (suggested by @liggitt , now that we have better audit logging)
- Throttling the log write rate, skipping writes when the rate is too high
- Buffering the log (maybe in combination with the throttle)

Either way, the PodSecurityPolicy case is not working as intended, I don't think writing thousands of denies for PodSecurityPolicies to the log is useful (we could also just skip logging on the `use` verb).

**How to reproduce it (as minimally and precisely as possible)**:

See [PodSecurityPolicy Scale Testing](https://docs.google.com/document/d/1IIcHHE_No1KMAybW5krIphdN325eGa2sxF2eqg2YAPI/edit#heading=h.1ns3f93w7sor) (although it will be somewhat fixed by https://github.com/kubernetes/kubernetes/pull/55643)

/cc @kubernetes/sig-scalability-bugs @kubernetes/sig-auth-bugs

**Comment by hzxuzhonghu** [comment]
>Raise the verbosity level on that log, basically disabling it when high performance is a concern (suggested by @liggitt , now that we have better audit logging)

agree with this
