### ISSUE TITLE
Missing name field in Pod example in docs

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#55838]
**What happened**:
https://kubernetes.io/docs/api-reference/v1.8/#pod-v1-core shows an example of a `Pod` but the container does not have a name which is a required field (I get an error from kubectl with this example).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.8.3 server and client

/kind bug
/kind documentation
/sig docs

**Comment by edisonxiang** [comment]
Hi @ash2k , I submit a PR to solve it. Welcome to review. Thanks.
