### ISSUE TITLE
IPVS kube-proxy will flush all existing ipvs rules in its startup

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#55857]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

@pires reported the bug.

kube-proxy resets IPVS configuration even though `--mode=iptables`

on a node before ever running kube-proxy

```
$ toolbox ipvsadm -l
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  11.14.170.10:etcd-server wlc
  -> vm-pb9g.c.massive-bliss-781. Masq    1      0          0         
  -> vm-wrk6.c.massive-bliss-781. Masq    1      0          0         
  -> vm-16sr.c.massive-bliss-781. Masq    1      0          0         
TCP  11.22.117.27:http wlc
  -> vm-wrk6.c.massive-bliss-781. Masq    1      0          0         
TCP  11.53.156.194:sun-sr-https wlc
  -> vm-pb9g.c.massive-bliss-781. Masq    1      0          4         
  -> vm-wrk6.c.massive-bliss-781. Masq    1      0          3         
  -> vm-16sr.c.massive-bliss-781. Masq    1      0          3         
TCP  11.193.111.100:etcd-client wlc
  -> vm-pb9g.c.massive-bliss-781. Masq    1      0          0         
  -> vm-wrk6.c.massive-bliss-781. Masq    1      0          0         
  -> vm-16sr.c.massive-bliss-781. Masq    1      0          0         
TCP  11.244.244.158:cslistener wlc
  -> vm-pb9g.c.massive-bliss-781. Masq    1      0          0         
  -> vm-wrk6.c.massive-bliss-781. Masq    1      0          0         
  -> vm-16sr.c.massive-bliss-781. Masq    1      0          0         
(...)
```

after running kube-proxy `--mode=iptables`

```
$ toolbox ipvsadm -l
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Currently we assume only ipvs proxier will create ipvs rules, ipvs proxier will flush all ipvs rules when clean up.  Users do this operation should be with caution. But, seems the comment message in codebase is not enough. We need to figure out how to fix it.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

cc @thockin @caseydavenport

**Comment by m1093782566** [comment]
Since there is no way to tell if a given ipvs rule is created by IPVS proxier of not. Should kube-proxy provide a new flags `--cleanup-ipvs` and kube-proxy will clean up ipvs rules only if `--cleanup-ipvs=true` in its start up?

The question is if `kube-proxy --clean` should legacy ipvs rules or not because it still has the risk of cleaning IPVS rules by other processes. If not, should users type

```
kube-proxy --clean; kube-proxy --clean-ipvs
```

 to clear the inactive proxy rules?

It's an open question, welcome comment...

**Comment by pires** [comment]
not @eparis but @pires reported the issue ;)

**Comment by pires** [comment]
Also, the existing flag is `--cleanup`.

**Comment by prateekgogia** [comment]
> kube-proxy resets IPVS configuration even though --mode=iptables

If the mode is `--mode=iptables`, why does kube-proxy has to clean IPVS rules ?

**Comment by m1093782566** [comment]
> If the mode is --mode=iptables, why does kube-proxy has to clean IPVS rules ?
Because iptables proxy need to clean legacy proxy rules which maybe created by ipvs proxier.

**Comment by pires** [comment]
As suggested over Slack, instead of making this implicit, I'd make it explicit with a new flag or reuse `--cleanup` (that would clean-up all the IPVS and IPTables rules.

**Comment by m1093782566** [comment]
@pires 

My concern is if we reuse `--cleanup`, it may break the existing logic if iptables proxier. I prefer a new flag.

**Comment by pires** [comment]
I'm fine with that. Are we waiting on more feedback or someone to own the fix?

**Comment by m1093782566** [comment]
@pires I can own the fix. And, can we wait on more feedback?

**Comment by m1093782566** [comment]
I try to enumerate all cases:

**1. don't run proxy**

```
kube-proxy --cleanup-ipvs // don't run proxy, will clean only ipvs rules

kube-proxy --cleanup // don't run proxy, will clean all inactive rules, incluing iptables, userspace and ipvs rules
```

**2. run iptables proxy**

```
kube-proxy --mode=iptables // run proxy, will clean only userspace proxy rules.

kube-proxy --mode=iptables --cleanup // run proxy, will clean userspace, iptables, and ipvs rules

kube-proxy --mode=iptables  --cleanup-ipvs // run proxy, will clean only ipvs rules
```

**3. run userspace proxy**

```
kube-proxy --mode=userspace // run proxy, will clean only iptables rules

kube-proxy --mode=userspace --cleanup-ipvs // run proxy, will clean only ipvs rules

kube-proxy --mode=userspace --cleanup // run proxy, will clean userspace, iptables and ipvs rules
```

**4. run ipvs proxy**

```
kube-proxy --mode=ipvs --cleanup // run proxy, will clean userspace, iptables and userspace rules

kube-proxy --mode=ipvs --cleanup-ipvs // run proxy, will clean only ipvs rules

kube-proxy --mode=ipvs // run proxy, will clean only userspace and iptables rules
```

Is that fine?

**Comment by roffe** [comment]
Instead of having multiple flags for different cleanups i suggest we collect them under `--cleanup` that accepts a list of items ( e.g `--cleanup=iptables,ipvs `)

I am in favor of the cleanup at start. It ensures there is no iptable/ipvs rules left in corner cases like  switching mode and don't having the cleanup-flag set. 

It has to be stated properly in the documentation so everyone is clear on the implicit behavior. 

I suggest introducing `--cleanup-at-start` that would take the same list as --cleanup. ( e.g `--cleanup-at-start=iptables,ipvs`) to allow full control over the cleanup process both at start & exit.

**Comment by roffe** [comment]
Some ideas

--cleanup can take true/false/iptables/ipvs - true = clean all avail. iptables, ipvs etc. false = no cleanup at exit. if specific value or list is given, only clean those. this should also ensure backwards compatible with existing configurations  (default to true should be sane for most users)

--cleanup-at-start same as above, true clean all, false, no clean, if specific value or list is given, only clean those ( default to true should be sane for most users )

I belive that when `--cleanup-at-start` is set it should have precedence over the implicit behavior of `--mode` at startup allowing the operator to override it but keep the current functionality intact without config changes for existing users

**Comment by caseydavenport** [comment]
Alternatively, we do have a `--mode` flag already.

Couldn't the UX just be:

```
kube-proxy --cleanup --mode=ipvs
```

```
kube-proxy --cleanup --mode=iptables
```

**Comment by vfreex** [comment]
Another alternative idea is automatically cleaning up the rules whose virtual server address is in clusterCIDR.

**Comment by pires** [comment]
@vfreex i like that solution! But still, it should be made explicit to the user the automated clean-up that exists today.

@m1093782566 so, with all this feedback, what say you? I am willing to contribute as well.

**Comment by roffe** [comment]
> Another alternative idea is automatically cleaning up the rules whose virtual server address is in clusterCIDR, because I think those addresses shouldn't be managed by users.

This should be the bare minimum check to use when evaluating if the rules should be deleted "if != clusterCIDR skip" :)

**Comment by m1093782566** [comment]
apart from clusterCIDR, there are some other ipvs vips such as, external IPs, load balancer ingress IPs and node IPs. So, clusterCIDR may not work well in all cases.

**Comment by m1093782566** [comment]
With so many feedback, I am going to send a PR...

Welcome comments :)

**Comment by vfreex** [comment]
Using "--cleanup" option seems feasible, but not ideal.
How about checking the target server address?
Personally I would be in favor of "smart" behaviors. :)

**Comment by m1093782566** [comment]
@vfreex 

> How about checking the target server address?

Seems tricky. Do you have any good idea?

**Comment by vfreex** [comment]
@m1093782566 Actually... no.
