### ISSUE TITLE
Windows getting-started-guide missing

### ISSUE THREAD

**Issue by inorton** [kubernetes/kubernetes#55862]
/kind bug

**What happened**:

The documents for windows at https://kubernetes.io/docs/getting-started-guides/windows/ are missing

**What you expected to happen**:

View the getting-started-guide

**How to reproduce it (as minimally and precisely as possible)**:

Visit the page

**Anything else we need to know?**:

**Comment by dims** [comment]
@inorton Do you mind moving this to https://github.com/kubernetes/website issues?

**Comment by inorton** [comment]
H
These have come back now
