### ISSUE TITLE
Improve the speed of build-go.sh

### ISSUE THREAD

**Issue by you-n-g** [kubernetes/kubernetes#5586]
I'm a new contributor to kubernetes.
I deploy kubernetes on my computer or VPS.
I found it is slow to compile the project by  ./hack/build-go.sh
So I'm wondering if there is any way to speed it up to make it faster to be more friendly to the developers?

**Comment by piosz** [comment]
How long does it take to compile the project for you? It takes <1 minute to compile it on my desktop and as for me it's a very good time in comparison to any other project I used to work.
