### ISSUE TITLE
flake: test failures with "read: connection reset by peer; some request body already written" when creating/changing objects

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55860]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Example message:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:288
creating { ReplicationController} load-small-223
Expected error:
    <*errors.errorString | 0xc421a485e0>: {
        s: "Error creating replication controller: Post https://35.185.119.78/api/v1/namespaces/e2e-tests-load-30-nodepods-1-trc47/replicationcontrollers: read tcp 10.60.151.252:56160->35.185.119.78:443: read: connection reset by peer; some request body already written",
    }
    Error creating replication controller: Post https://35.185.119.78/api/v1/namespaces/e2e-tests-load-30-nodepods-1-trc47/replicationcontrollers: read tcp 10.60.151.252:56160->35.185.119.78:443: read: connection reset by peer; some request body already written
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:540
```

It happened a few tests, not all of them scalability:
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/191
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gce-2-test/3501
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/48
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-staging-default-latest-upgrade-cluster/79
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/30
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/25
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/77
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/78

It also happens on the GET alone, examples:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/9011
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/9000
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/9127
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/99
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/10054
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/45
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/92
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/93

**What you expected to happen**:

This should be retried at some level.

**Comment by porridge** [comment]
@kubernetes/sig-scalability-bugs 
/assign

**Comment by porridge** [comment]
@kubernetes/sig-api-machinery-misc this seems like a problem that should be solved once for all users - for example note how in [one of the failures](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-staging-default-latest-upgrade-cluster/79) it's `kubectl create` that fails when trying to create a secret.

**Comment by porridge** [comment]
Another scalability job failed due to this. Added link to first comment.
Putting under umbrella issue - #55194

**Comment by porridge** [comment]
/priority critical-urgent
this blocks #55194

**Comment by porridge** [comment]
Dear sig-api-machinery leads, @lavalamp @deads2k what's your take on this? Is better a retry mechanism in the plans?

**Comment by shyamjvs** [comment]
I'm not sure if this is an issue in api-machinery. FMU it is the client which should retry the POST request and correspondingly react based on the response (i.e "object already exists" or if something retriable).

cc @wojtek-t

**Comment by wojtek-t** [comment]
Client itself is retrying a bunch of different problems. In particular it is retrying in case of some errors returned by apiserver.

However, "connection reset by peer" is an infrastructure layer error. So it's not the error returned by apiserver, but the real error. Retrying those errors is more tricky, because we can't easily say if that request reached apiserver and was processed (and if so successfully or not) or not.
So I don't think we can automatically retry this error in a "correct" way.

**Comment by shyamjvs** [comment]
That sounds reasonable. WDYT about the following options (which might be better than not retrying at all):

- Try to GET the object you just posted and see if it was created, If not, resend the POST request. If there's a race with the previous POST, one of them would just fail(?)
- Retry the POST anyway (as we do not have any return code available from the apiserver for the previous request) hoping that it would go through. If it AlreadyExists, we'd get a 409.

**Comment by porridge** [comment]
Isn't sig-api-machinery taking care of the client code as well?
As for automatic retry, I was wondering why the API uses POST rather than
PUT...
I suppose more clients would prefer automatic failure retries in exchange
for having to send an explicit GET to check for unexpected pre-existing
resources in the cases they really care. That's why I asked sig leads.
In my mind, the alternative is that everyone implements their own retry
logic, with unique bugs, etc.

**Comment by porridge** [comment]
On Tue, Nov 21, 2017 at 4:17 PM, Shyam JVS <notifications@github.com> wrote:

> That sounds reasonable. WDYT about the following options (which might be
> better than not retrying at all):
>
>    - Try to GET the object you just posted and see if it was created, If
>    not, resend the POST request. If there's a race with the previous POST, one
>    of them would just fail(?)
>    - Retry the POST anyway (as we do not have any return code available
>    from the apiserver for the previous request) hoping that it would go
>    through. If it AlreadyExists, we'd get a 409.
>
>
The problem is that you don't know if the 409 is because the resource has
already been there in the first place (i.e. the first POST would have
returned it as well), or a result of the first POST which in fact inserted
the resource but just failed to propagate this information back to the
caller.

**Comment by shyamjvs** [comment]
> The problem is that you don't know if the 409 is because the resource has already been there in the first place

In that case we shouldn't use this mechanism (unless you're fine with the object pre-existing?) :)
In general, I think different clients would want to handle this situation differently based on their needs.

**Comment by yliaog** [comment]
as @wojtek-t mentioned, there is retry implemented in client-go library, but just for GET. For other cases, it is left to the clients to decide what to do based on their specific situations.

https://github.com/kubernetes/client-go/blob/076e344c86e52f088b78615f815b245f6d613537/rest/request.go#L653
		if err != nil {
			// "Connection reset by peer" is usually a transient error.
			// Thus in case of "GET" operations, we simply retry it.
			// We are not automatically retrying "write" operations, as
			// they are not idempotent.
			if !net.IsConnectionReset(err) || r.verb != "GET" {
				return err
			}

**Comment by smarterclayton** [comment]
We definitely can't blanket do it, but for most idempotent create actions we could handle it pretty cleanly.  It would be a fair amount of ugly code that would be domain specific to the actual object being POSTed (not all objects POSTed to Kube endpoints have idempotent naming).  I'm not sure the complexity in the client stack is worth it unless a large number of users benefit from it.

**Comment by smarterclayton** [comment]
Do we know what the actual failure cause was (or if there was only one)?

**Comment by porridge** [comment]
@smarterclayton we don't know, every time I looked, the response looked successful or completely missing on the apiserver side. Does it really matter what it was? I mean, network communication can fail for many reasons.

**Comment by porridge** [comment]
Regarding the "is solving retries in client library worth it" question: I've been on a project which did not have retries done properly in its infancy, the client libraries did not have any builtin retry support, and it turned out that intermittent failures were killing us as soon as we started to scale up. I suspect many projects which move to cloud have a very similar experience.

**Comment by porridge** [comment]
FTR, this broke two scale-performance tests in a row now...

**Comment by porridge** [comment]
new umbrella issue: https://github.com/kubernetes/kubernetes/issues/56062

**Comment by porridge** [comment]
@yliaog we're getting surprisingly many of these failures with GET requests - see the list in initial comment. I don't think the retry code you linked to is kicking in actually, because in that case we should not be seeing the "connection reset" error message at all, AFAICT?

**Comment by wojtek-t** [comment]
As discussed with @shyamjvs offline, he will add retrying in our tests. That should hopefully fix most of the problems.

**Comment by shyamjvs** [comment]
I'm reopening this issue as we should also add retries for other CRUD calls.

**Comment by shyamjvs** [comment]
It seems like we still haven't resolved flakes during creation that happen due to transport layer failures:


https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/12247
