### ISSUE TITLE
Does K8s 1.8.x support Windows server 2016?

### ISSUE THREAD

**Issue by orangedeng** [kubernetes/kubernetes#55861]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I am following the https://kubernetes.io/docs/getting-started-guides/windows/ to add a windows node on Kubernetes 1.8.3 cluster. My kubelet has connected to api server but can not run any pod.
following is the pod status:
```
Name:         nanoserver
Namespace:    default
Node:         172.22.101.132/172.22.101.132
Start Time:   Thu, 16 Nov 2017 17:08:32 +0800
Labels:       name=nanoserver
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"nanoserver"},"name":"nanoserver","namespace":"default"},"spec":{"contain...
Status:       Pending
IP:           
Containers:
  iis:
    Container ID:  
    Image:         microsoft/nanoserver
    Image ID:      
    Port:          <none>
    Command:
      powershell
      sleep
      9999
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7hww5 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-7hww5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7hww5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=windows
Tolerations:     <none>
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               20m                 default-scheduler        Successfully assigned nanoserver to 172.22.101.132
  Normal   SuccessfulMountVolume   20m                 kubelet, 172.22.101.132  MountVolume.SetUp succeeded for volume "default-token-7hww5"
  Warning  FailedCreatePodSandBox  18m (x12 over 20m)  kubelet, 172.22.101.132  Failed create pod sandbox.
  Warning  FailedSync              42s (x92 over 20m)  kubelet, 172.22.101.132  Error syncing pod
```
and kubelet keep showing
```
E1116 17:29:39.718878    4684 kubelet_network.go:167] checkLimitsForResolvConf: open /etc/resolv.conf: The system cannot find the path specified.
E1116 17:29:40.324355    4684 eviction_manager.go:238] eviction manager: unexpected err: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E1116 17:29:45.746797    4684 kuberuntime_sandbox.go:39] GeneratePodSandboxConfig for pod "nanoserver_default(b7ead396-caad-11e7-8c1f-080027e093ef)" failed: open /etc/resolv.conf: The system cannot find the path specified.
E1116 17:29:45.748297    4684 kuberuntime_manager.go:633] createPodSandbox for pod "nanoserver_default(b7ead396-caad-11e7-8c1f-080027e093ef)" failed: open /etc/resolv.conf: The system cannot find the path specified.
E1116 17:29:45.748297    4684 pod_workers.go:182] Error syncing pod b7ead396-caad-11e7-8c1f-080027e093ef ("nanoserver_default(b7ead396-caad-11e7-8c1f-080027e093ef)"), skipping: failed to "CreatePodSandbox" for "nanoserver_default(b7ead39
6-caad-11e7-8c1f-080027e093ef)" with CreatePodSandboxError: "GeneratePodSandboxConfig for pod \"nanoserver_default(b7ead396-caad-11e7-8c1f-080027e093ef)\" failed: open /etc/resolv.conf: The system cannot find the path specified."
E1116 17:29:50.391548    4684 eviction_manager.go:238] eviction manager: unexpected err: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): server: ubuntu 16.04 client: windows server 2016
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I have tried running aspnet pod on windows server 2016, it works well:
```
kubectl create -f https://raw.githubusercontent.com/andyzhangx/Demo/master/windows/basic/aspnet-pod.yaml
```

To narrow down your issue, would you first run following container on your windows server:
```
docker run -d --name aspnet microsoft/aspnet
docker run -d --name nanoserver microsoft/nanoserver
```

**Comment by messmerxx** [comment]
O have more or less similar problems. I can run docker run -d --name aspnet microsoft/aspnet
docker run -d --name nanoserver microsoft/nanoserver

But when I create a pod with master. It doesn't work. On my node,I see error message kube dns linux can not be downloaded. It is true, because the node is windows.
Is there kube dns image for windows? Thanks

**Comment by andyzhangx** [comment]
@messmerxx you should not run a pod on master, it's not k8s way. 
you could use `nodeSelector` to make sure that windows pod will run on Windows node, see example here:
https://github.com/andyzhangx/Demo/blob/master/windows/basic/aspnet-pod.yaml

**Comment by messmerxx** [comment]
Thanks for your reply. I think I typed it wrongly.the pod will be deployed on node.after removing or cleaning up the kube dns colltrollers for the cluster,the problem is gone.

But I am not be able to start the weave net pod on my windows node.do you know why? Does k8s support weave net on windows server 2016? Thank you very much.

**Comment by messmerxx** [comment]
Which networking mode have you already tried? Did it work?@andyzhangx

**Comment by CindyXing** [comment]
I am curious as well. @andyzhang, can you share some details here for the network setting? To my understanding, windows 2016 server kernel has some issues supporting k8s CNI. Thanks.

**Comment by andyzhangx** [comment]
As I know, weave net is not supported on Windows now. In Windows 2016 server, the default network mode is kubenet, and from [Windows Server version 1709](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-1709), it also supports [Azure CNI plugin](https://github.com/Azure/azure-container-networking).

You could reach [here](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#using-azure-integrated-networking-cni) for more details:

**Comment by michmike** [comment]
@orangedeng do you mind if we close this ticket? you should reach to the sig-windows slack channel for resolving additional questions. 
Here's the getting started guide with all the details
https://github.com/kubernetes/community/tree/master/sig-windows
