### ISSUE TITLE
kubectl logs Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy)

### ISSUE THREAD

**Issue by zzq392342084** [kubernetes/kubernetes#55872]
kubectl create command works correctly,but kubectl logs and kubectl exec not :
_Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes,subresource=proxy)_

kubectl version
_Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:03:38Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}_

**Comment by liggitt** [comment]
That means the api server has not been given a credential to use to authenticate to kubelets when proxying log/exec requests. 

See apiserver configuration as described in https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication

**Comment by adeelahmadch** [comment]
I also ran into this issue after upgrading from `1.18.16` to `1.19.8` using kops. After upgrade, I was not able to execute `kubectl logs` commands any more and was getting following error;

`Error Msg: Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy) ( pods/log pod-name)`

In my case, I have to add the following lines to fix it. I have `authorizationMode: Node,RBAC` just incase if you are wondering. 

`
kubeAPIServer:
    kubeletClientCertificate: /srv/kubernetes/kubelet-server.crt
    kubeletClientKey: /srv/kubernetes/kubelet-server.key

kubelet:
    anonymousAuth: false
`

**Comment by Parrryy** [comment]
Just to clarfiy, @adeelahmadch this is the kops cluster file that's been edited?

**Comment by adeelahmadch** [comment]
> Just to clarfiy, @adeelahmadch this is the kops cluster file that's been edited?

@Parrryy Yes its kOps cluster file.

**Comment by Parrryy** [comment]
The only change required for me was to add this to the spec.
```
kubelet:
    anonymousAuth: false
```

And following a rolling-update with Kops.

**Comment by okechukwu-opara** [comment]
you can add "--validate=false" at the end of your script.
