### ISSUE TITLE
DNS resolve error for kubectl exec -ti <podname>

### ISSUE THREAD

**Issue by rakeshkulkarni6** [kubernetes/kubernetes#55870]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /sig network
> /kind feature

**What happened**:
I have deployed cluster using acs engine. The cluster seems to be fine. I have deployed some pods and created service for them when iI tried to login to login to container using kubectl exec -ti /bin/bash its throwing dns resolve error for master and agents. error sample.:

root@hostname:/home/user# kubectl exec apache-dns-test-1639388633-hh2gr nslookup kubernetes
Error from server: error dialing backend: dial tcp: lookup hostname on 168.63.129.16:53: no such host

**What you expected to happen**:
If i execute "kubectl exec -ti apache-dns-test-1639388633-hh2gr bash" than it should be take me to running container shell. but its giving error.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We have Active directory DNS in our environment and master is created with HOST entry in DNS server. 
the master and agent node container nameserver entry in/etc/resolv.conf as pert inherited from azure vnet.the resolve.conf contains two dns servers 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Output:

root@rbdecchcovamw00:/home/cloudinfraadmin# cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.71.101.30 rbdecchcovamw00.northeurope.cloudapp.azure.com
root@rbdecchcovamw00:/home/cloudinfraadmin# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.10.102.4
nameserver 10.10.102.8
nameserver 168.63.129.16
search rebuscloud.co.uk reddog.microsoft.com

root@rbdecchcovamw00:/home/cloudinfraadmin# kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
apache-2843085959-8hh5c     1/1       Running   0          1h
busybox1                    1/1       Running   0          25m
my-nginx-3337555774-jdfkh   1/1       Running   0          51m
root@rbdecchcovamw00:/home/cloudinfraadmin# kubectl exec -ti busybox1 bash
Error from server: error dialing backend: dial tcp: lookup rbdecchcovaaw00 on 168.63.129.16:53: no such host
root@rbdecchcovamw00:/home/cloudinfraadmin#

**Comment by feiskyer** [comment]
@rakeshkulkarni6  Did you edit the /etc/resolv.conf manully, seems something are missing in the file. e.g. on my busybox pod, it looks

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local <other-domain>
options ndots:5
```

**Comment by andyzhangx** [comment]
you may try other image to narrow down the issue, e.g. nginx
try below example:
https://github.com/andyzhangx/Demo/tree/master/linux/basic

**Comment by rakeshkulkarni6** [comment]
@feiskyer  I have found solution for this if we are using custom DNS at vnet/nic level we need to edit /etc/dhcp/dhclient.conf with KUBEDNS IP and cluster.local as domain to supersede /etc/resolv.conf

**Comment by bowei** [comment]
@rakeshkulkarni6 if you have found a solution, can you close this issue?

**Comment by jdumars** [comment]
Closing due to staleness.
