### ISSUE TITLE
Why not reject another pod to use a pvc when it has access mode "ReadWriteOnce" and using by other pod?

### ISSUE THREAD

**Issue by mingshuaiwang** [kubernetes/kubernetes#55875]
For example, 
PVC pvc_eg has access mode "ReadWriteOnce" , and using by Deployment deployment_eg, why not Kube-apiserver check and reject other Deployment to use it  at admission stage?

**Comment by mingshuaiwang** [comment]
@kubernetes/sig-storage-proposals

**Comment by gnufied** [comment]
We are currently guarding this in attach/detach controller so as RWO volumes can not be used by multiple pods at once. 

The apiserver does not guard against creation of pods though. Attach/Detach controller just prevents attaching volumes to multiple nodes.

**Comment by mingshuaiwang** [comment]
User realize that the pvc they want to use is occupied by other pod(or deployment or some other resource) only when they found that their new pod(or other resource) can not running up.  In this case, user experience is not good.  
What about add a new admission for apiserver, this admission will attach a label(status=using) to pvc when pod(or other resource) using the pvc. When new pod(or other resource) want to use this pvc, this new admission found that the pvc with mode "RWO" is using by other resource then will reject the creation of the new resource.  User will know pvc they want to use is not available immediately, and they cannot use it in new pod(or other resource) creation.

**Comment by mingshuaiwang** [comment]
@kubernetes/sig-storage-proposals
