### ISSUE TITLE
heapster does not scale to large clusters

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#55887]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

In https://github.com/kubernetes/kubernetes/issues/54637#issuecomment-344584988 we found that Horizontal Pod Autoscaler test fails on large clusters, despite its deployment under test is tiny (1-2 nodes). The conclusion was that the reason is most likely that heapster fails to scrape metrics from thousands of nodes in a timely manner (the test does pass on large scale, but very rarely).

**How to reproduce it (as minimally and precisely as possible)**:

Run a gce-large-correctness job (2k nodes).

**Anything else we need to know?**:

Interestingly, on 2k GKE cluster the HPA tests pass: https://github.com/kubernetes/kubernetes/issues/54637#issuecomment-344587938

**Comment by porridge** [comment]
@kubernetes/sig-instrumentation-bugs

**Comment by shyamjvs** [comment]
@fgrzadkowski Assigning this to you - feel free to redirect it as apt. Thanks.

**Comment by wojtek-t** [comment]
If it passes on GKE and not on GCE, it most probably is configuration issue (e.g. too few resources or sth like that).

**Comment by porridge** [comment]
FWIW, I happened to stumble on possibly relevant warnings in controller manager log from the failing test (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/28)

```
E1114 21:37:44.230112       7 horizontal.go:189] failed to compute desired number of replicas based on listed metrics for ReplicationController/e2e-tests-horizontal-pod-autoscaling-4mfs6/rc-light: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
I1114 21:37:44.230166       7 event.go:218] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"e2e-tests-horizontal-pod-autoscaling-4mfs6", Name:"rc-light", UID:"dc3bed25-c982-11e7-8959-42010a8e0002", APIVersion:"autoscaling/v2beta1", ResourceVersion:"1210810", FieldPath:""}): type: 'Warning' reason: 'FailedComputeMetricsReplicas' failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
I1114 21:37:44.230210       7 event.go:218] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"e2e-tests-horizontal-pod-autoscaling-4mfs6", Name:"rc-light", UID:"dc3bed25-c982-11e7-8959-42010a8e0002", APIVersion:"autoscaling/v2beta1", ResourceVersion:"1210810", FieldPath:""}): type: 'Warning' reason: 'FailedGetResourceMetric' unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by piosz** [comment]
It's not about Heapster but Metrics Server. I agree with Wojtek - most likely it's a configuration issue.

**Comment by serathius** [comment]
Looks like both Metric Server and Heapster resources requirements are scaled to the point that they do not fit on dedicated heapster minion. They request about 8.3 GB of memory both on machine that provides 16GB, resulting in only one of them running and second one being stuck in unschedulable state.

**Comment by shyamjvs** [comment]
Thanks for looking into this @serathius . We're [using](https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-large-correctness.env#L8) a special node (of size n1-standard-4) for heapster to run - seems like that's not enough.

Could you confirm if everything goes fine with n1-standard-8?

**Comment by wojtek-t** [comment]
Sounds reasonable - bumping it should be trivial.

**Comment by serathius** [comment]
I verified that heapster and metric server is working, but didn't check if HPA tests pass.

**Comment by shyamjvs** [comment]
Would you be able to run those HPA tests on a large cluster (at least 2k-node)? Then we may be able to get rid of [this TODO](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L69) and have HPA tests included back in our scalability correctness tests.

**Comment by serathius** [comment]
On it
