### ISSUE TITLE
Openapi generator and the RawExtension type

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#55890]
The Service Catalog includes the `RawExtension` type in `ServiceInstance.spec.parameters`. The openapi schema generated for it is wrong. It has two problems:
- it includes the `Raw` field, which is marked as required
- it doesn't allow additional properties to be included under it

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT
/kind bug

**What happened**:
If the Service Catalog openapi schema is exposed to kubectl (this currently requires a few tweaks and a patch), it reports validation errors when creating a ServiceInstance resource. 

**What you expected to happen**:
The schema should allow ServiceInstance.spec.parameters to include arbitrary properties and not require the `Raw` property to be included.

**How to reproduce it (as minimally and precisely as possible)**:
not easy at the moment (I'll add instructions later if I'm unable to fix this myself)

**Anything else we need to know?**:
I'd like to tackle this problem myself, but I need guidance. Should openapi-gen handle this automatically for all occurences of RawExtension, or should each field of type `RawExtension` be json-tagged individually? 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by luksa** [comment]
@mbohlool I've heard you're the goto guy for the openapi-gen. Please help? :)

**Comment by luksa** [comment]
OK, I've found I can specify a custom schema for RawExtension the way it's done in Time and MicroTime. 
The remaining problem is how to specify that the RawExtension object can be of any type. Using `anyOf` is not supported currently - if I use it in the schema, the API server dies with:

```
openapi.go:37] Failed to register open api spec for root: ERROR $root.definitions.io.k8s.apimachinery.pkg.runtime.RawExtension has invalid property: anyOf
```

**Comment by ash2k** [comment]
We've just hit this.

/remove-lifecycle rotten
/lifecycle frozen

**Comment by yue9944882** [comment]
hitting this 😞

**Comment by mbohlool** [comment]
According to this: https://swagger.io/docs/specification/data-models/data-types/#free-form

the raw extension can define its openapi type as:

```
type: object
```

or alternatively

```
type: object
additionalProperties: true
```

@sttts what do you think?
@luksa do you still work on this or you want me to send a PR?

**Comment by jennybuckley** [comment]
Would changing the definition of RawExtension to this help the situation? (adding `json:",inline"`)
```
type RawExtension struct {
    ...
    Raw []byte `json:",inline" protobuf:"bytes,1,opt,name=raw"`
    ...
}
```
I noticed that this removes Raw from the openapi defintion of it, without changing how it is marshalled or unmarshalled (since we have custom functions for that)
