### ISSUE TITLE
Detach is broken from stopped nodes in AWS

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#55892]
Currently detach is broken for stopped nodes in AWS because stopped nodes can't be fetched in AWS cloudprovider, that causes `getInstanceByNodeName` to throw "Node Not found error" and that in turn means detach calls silently fail.

**Comment by gnufied** [comment]
/sig aws
/sig storage

cc @kubernetes/sig-storage-bugs

**Comment by justinsb** [comment]
Putting into 1.9 so we can track it.

**Comment by jberkus** [comment]
@justinsb if this issue is going to be in 1.9, we need daily updates on resolution.  Please update it within 24 hours, thanks!

**Comment by gnufied** [comment]
@jberkus there is a fix proposed for it. The fix has been tested.  We need to add PR https://github.com/kubernetes/kubernetes/pull/55893 to 1.9 milestone so as this issue can be closed.

**Comment by jberkus** [comment]
@justinsb, can you add status/accepted-for-milestone to this issue?  Thanks.
