### ISSUE TITLE
no kind "Deployment" is registered for version "apps/v1beta2"

### ISSUE THREAD

**Issue by dusansusic** [kubernetes/kubernetes#55894]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> kind bug

**What happened**:
It's not possible to create Deployment with nginx example provided in documentation. 

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f https://raw.githubusercontent.com/kubernetes/website/master/docs/concepts/workloads/controllers/nginx-deployment.yaml

```
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/kubernetes/website/master/docs/concepts/workloads/controllers/nginx-deployment.yaml": Deployment in version "v1beta2" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1beta2"
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.7, 1.8.0 
- Cloud provider or hardware configuration: virtualbox cluster with 2 nodes. 
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`): Linux node1 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Others: Kuberenetes is provisioned with Rancher v1.7.7

**Comment by dusansusic** [comment]
@kubernetes/contributor-experience

**Comment by ryanmcginnis** [comment]
Hitting this, too, using the same example.

**Comment by stewart-yu** [comment]
I  think you should change the `version` to `apps/v1beta1`

**Comment by dusansusic** [comment]
working with `version`: `apps/v1beta1`

**Comment by ryanmcginnis** [comment]
But it should work with a 1.8.0+ cluster, and it doesn't. Why?

**Comment by barbarosalp** [comment]
Yes, working with version: apps/v1beta1

**Comment by janetkuo** [comment]
apps/v1 is only available in Kubernetes 1.9.0+ clusters.

**Comment by minherz** [comment]
I have similar issue when using Kubernetes 1.8.5-gke.0 in GKE.

**Comment by centromere** [comment]
@janetkuo Why did you close this? You said:

> For 1.8 cluster, use apps/v1beta2 Deployment instead.

The OP however, did exactly what you said to do:

> Deployment in version "v1beta2" cannot be handled as a Deployment...

and it still did not work.

**Comment by janetkuo** [comment]
@centromere 
> kubectl create -f https://raw.githubusercontent.com/kubernetes/website/master/docs/concepts/workloads/controllers/nginx-deployment.yaml

The config @dusansusic used is an `apps/v1` Deployment. This API version isn't supported until 1.9.0+.

**Comment by janetkuo** [comment]
@centromere I think that aforementioned config file had been updated when I saw this issue. It was originally `apps/v1beta2` when @dusansusic used it. 

So updating my response: `apps/v1beta2` is only supported in 1.8.0+ clusters. @dusansusic would you reopen this issue if you saw this error in an 1.8.0+ cluster when trying to create a `apps/v1beta2` Deployment?

**Comment by minherz** [comment]
The official kubernetes documentation [clearly states](https://kubernetes.io/docs/reference/workloads-18-19/) that versions 1.8.* uses deployment `apiVersion` as `apps/v1beta2` and versions 1.9.* as `apps/v1`. In the original post it was stated that the problem exists for versions 1.7.7 and 1.8.0. However, it is unclear whether version 1.8.0. was the cluster or kubectl.

**Comment by victorp13** [comment]
Small tip: To find out what exact apps/xxx api version your cluster supports, use 

`kubectl api-versions`
and the exact apps/xxx version will be listed there

**Comment by abdennour** [comment]
You should upgrade your cluster. If you are using minikube under OSX, here we go:

```sh
brew cask reinstall minikube
# minikube stop
# minikube start
```

**Comment by Rub21** [comment]
Sometimes the solution is only to add `quote` in all numeric variables: e.g 👇 

```
- name: POSTGRES_PORT
  value: {{ .Values.db.env.POSTGRES_PORT | quote }}
```

**Comment by da-123** [comment]
i have got the same issue can anybody help me I am new to Kubernetes:
here is the log 
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]

my kubectl version is 1.16 I think the API version is not supported how can i fix such kind of issues

**Comment by metsie2912** [comment]
@da-123,
Try setting:
```
    apiVersion: apps/v1
    kind: Deployment
```

**Comment by piaic65617** [comment]
I was also following the same issue 
I was using _apps/v1beta2_ for my Replicaset.
But when I checked _kubectl api-versions_
apps/v1beta2 was not listed.
so I used just _apps/v1_ and it worked.

**Comment by dhodyrahmad** [comment]
Hi, Im work with minikube version: v1.16.0 and I had the same problem but in my case all api-versions i used are listed on kubectl api-versions but still not works. did I missed something?


this is  my kubectl api-versions
```
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1
events.k8s.io/v1beta1
extensions/v1beta1
flowcontrol.apiserver.k8s.io/v1beta1
metrics.k8s.io/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

this is the error:
```Error from server (BadRequest): error when creating "test.yaml": deployment in version "v1" cannot be handled as a Deployment: no kind "deployment" is registered for version "apps/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"```

**Comment by shirtee19** [comment]
scheme.go

**Comment by shirtee19** [comment]
Error from server (BadRequest): error when creating "config.yml": pod in version "v1" cannot be handled as a Pod: no kind "pod" is registered for version "v1" in scheme "pkg/api/legacyscheme/scheme.go:30

I changed the version from v1 to v2----------also changed apps/v1 to apps/v2 but it still giving me the same error above. please any idea what could be the issue here. Below is my Yaml file

apiVersion: apps/v2
kind: pod
metadata:
   name: web
   labels:
     env: prod
     author: ttnwt
spec:
  containers:
  - name: sample-container
    image: nginx:alpine
    ports:
    - containerport: 80
~

**Comment by metsie2912** [comment]
@shirtee19 
In Yaml, whitespace is really important (which I don't see as you pasted your yaml as normal text). Also, character cases are important. 
apiVersion could be:
`apiVersion: v1`
That should be sufficient, at least in the Kubernetes version I'm running.
kind needs to be:
`kind: Pod`
under ports (example snippet, note capitalization):
```
apiVersion: v1
kind: Pod
metadata:
  name: sample
  labels:
    app: sample
spec:
  containers:
    - name: sample-container
      image: someimage:tag
      ports:
        - containerPort: 80
 ```

Please try to adjust your yaml accordingly. 
If still not working, please do not use this really old thread anymore. Use the search function, and if an answer is not found, open a new thread for your particular issue.

**Comment by Saurabh18R** [comment]
I tried all versions still getting this error.
![1](https://user-images.githubusercontent.com/83106834/209447376-9eecb099-a76f-4aa9-a629-c898d4358420.jpg)
![2](https://user-images.githubusercontent.com/83106834/209447379-b1833f98-ea40-4cdc-b533-bca6a407aa76.jpg)

**Comment by David-Inkheart** [comment]
Had a similar issue. Seems I was using tabs for indentation as against spaces and was not indenting correctly too. So, changing to spaces and using proper indentation as needed helped clear the error.
My yaml file final look:  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
