### ISSUE TITLE
kubectl "--selector=name=foo" flag does not work for cronjobs

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#55904]
/kind bug

**What happened**:

The kubectl "--selector=name=foo" flag does not work for cronjobs.

```
$ kubectl --namespace=foo get cronjob --selector=name=foo-cron
No resources found.
```
```
kubectl --namespace=foo get cronjob
NAME                      SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
foo-cron                  10 15 * * *   False     0         <none>
```
```
$ kubectl --namespace=foo get cronjob -o yaml
apiVersion: v1
items:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    annotations:
      kubernetes.io/change-cause: kubectl create --namespace=foo --filename=foo-cron.yaml --record=true
    creationTimestamp: 2017-11-16T22:00:49Z
    name: foo-cron
    namespace: foo
    resourceVersion: "93779831"
    selfLink: /apis/batch/v2alpha1/namespaces/foo/cronjobs/foo-cron
    uid: abcdefgh-cb19-11e7-b08e-005056ae4211
  spec:
...
```

**What you expected to happen**:

The "--selector=name=foo-cron" kubectl flag should return cronjobs with corresponding metadata.

**How to reproduce it (as minimally and precisely as possible)**:

Create cronjob with "name: foo-cron" in top-level metadata, then attempt "kubectl get cronjob --selector=name=foo-cron".

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:12:08Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`): 4.4.0-89-generic
- Install tools: N/A
- Others: N/A

**Comment by liggitt** [comment]
--sector matches labels, and that cronjob doesn't have a label "name"

You could use a field selector of metadata.name=foo-cron

**Comment by DreadPirateShawn** [comment]
Bah. Apologies for the noise, and thanks.
