### ISSUE TITLE
pull-kubernetes-verify verify-openapi-spec failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#55917]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: all recent `pull-kubernetes-verify` tests are failing against `hack/make-rules/../../hack/verify-openapi-spec.sh` EG: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54053/pull-kubernetes-verify/63091/

**What you expected to happen**: This shouldn't be failing so widely

**How to reproduce it (as minimally and precisely as possible)**:
Run `pull-kubernetes-verify` against a PR, it fails.

**Anything else we need to know?**: It also failed against a canary migration of verify to Prow against a dummy PR that has no code changes: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-verify-prow/88/

/sig testing

**Comment by BenTheElder** [comment]
FYI @mtaufen who spotted this.

**Comment by BenTheElder** [comment]
```
I1117 03:43:26.181] diff -Naupr -I 'Auto generated by' /go/src/k8s.io/kubernetes/api/openapi-spec/swagger.json /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json
I1117 03:43:26.182] --- /go/src/k8s.io/kubernetes/api/openapi-spec/swagger.json	2017-11-17 03:43:26.150921285 +0000
I1117 03:43:26.182] +++ /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json	2017-11-17 03:17:36.914463379 +0000
I1117 03:43:26.182] @@ -2,7 +2,7 @@
I1117 03:43:26.182]    "swagger": "2.0",
I1117 03:43:26.182]    "info": {
I1117 03:43:26.182]     "title": "Kubernetes",
I1117 03:43:26.182] -   "version": "v1.9.0"
I1117 03:43:26.182] +   "version": "v1.10.0"
I1117 03:43:26.183]    },
I1117 03:43:26.183]    "paths": {
I1117 03:43:26.183]     "/api/": {
I1117 03:43:26.183] /go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh
I1117 03:43:26.193] FAILED   hack/make-rules/../../hack/verify-openapi-spec.sh	119s
```

/cc @dashpole 
/assign

**Comment by xiangpengzhao** [comment]
I remember the same issue happened when release-1.8 branch was created. Seems like there is some script should be updated but I forget which one.

**Comment by BenTheElder** [comment]
At the moment I suspect https://github.com/kubernetes/kubernetes/pull/55353

**Comment by yanxuean** [comment]
I will fix it.

**Comment by david-mcmahon** [comment]
Something definitely not looking right about this release branch.  Investigating...

**Comment by xiangpengzhao** [comment]
This is the third time (or more) we encounter this similar issue. (1.7/1.8/1.9 branches were cut).  ref: https://github.com/kubernetes/kubernetes/pull/46863 https://github.com/kubernetes/kubernetes/pull/51851.

But seems like this time is caused by something different.

**Comment by david-mcmahon** [comment]
@enisoc and I looked and have updated the tag on master to unblock the submit queue.  Fix for the branch coming tomorrow as well as a fix to the root cause.

**Comment by enisoc** [comment]
Found the first glimmer of green: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55148/pull-kubernetes-verify/63165

**Comment by david-mcmahon** [comment]
But the version is still at 1.9.0.  Will we need to force a tag update on the SQ?

**Comment by enisoc** [comment]
More recent runs have v1.10.0: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55927/pull-kubernetes-verify/63173

Seems like it fixed itself?

**Comment by mchangxe** [comment]
was facing this issue as well a few hours ago, not anymore though

**Comment by ericchiang** [comment]
I'm hitting this on one of my PRs (https://github.com/kubernetes/kubernetes/pull/53922) and it looks like other recent PRs are hitting it too (https://github.com/kubernetes/kubernetes/pull/55961)

Inspecting the history I found the commit that changed it to v1.10.0, but that PR doesn't look associated with an PR. Maybe it was mistakenly pushed to master?

https://github.com/kubernetes/kubernetes/commit/a82460d772b94e2b11b65daa47c0a7fb4854b0ad#diff-eab8237a1f6f95a356426dec2fe326d0

cc @dashpole

**Comment by enisoc** [comment]
@ericchiang It's normal that master has been updated to `v1.10.0` at this time. I think what happened is that your PR is trying to revert to `v1.9.0` because your local git repo doesn't have the latest tags from upstream. It should get fixed if you locally update your tags (`git fetch upstream --tags`) and then run the generator again.

**Comment by BenTheElder** [comment]
Seems safe to
/close
this now, thanks for fixing this :-)
