### ISSUE TITLE
kubectl prints wrong context when using --context

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#5592]
When I use `--context` flag kubectl still prints default context:

<pre>
$ ./cluster/kubectl.sh <b>--context=ivory-honor-865_e2e-test-filipg</b>` get pods
<b>current-context: "ivory-honor-865_kubernetes"</b>
...
</pre>

Command works correctly (i.e. uses context from --context flag) but this is misleading.

**Comment by dims** [comment]
We don't print current-context: any more. Can we close this bug?

**Comment by AdoHe** [comment]
@dims since the behavior is correct, feel free to close this one.

**Comment by dims** [comment]
closing per @AdoHe 's last comment
