### ISSUE TITLE
kubernetes api time cost

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#55929]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
time  kubectl get pod -n qinzhao
NAME                                                READY     STATUS     RESTARTS   AGE
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-w98mj        0/1       Init:0/1   0          11s
cifid-tyyrtjuzwlns-cisid-gjudsxsu3rmf-hbqx0-mgw9c   0/1       Init:0/1   0          13s

real    0m10.480s
user    0m5.895s
sys    0m0.460s
[root@master-test-105 tmp]# 
[root@master-test-105 tmp]# 
[root@master-test-105 tmp]# 
[root@master-test-105 tmp]# 
[root@master-test-105 tmp]# 
[root@master-test-105 tmp]# time  kubectl get pod -n  lijiaob-space2
NAME                        READY     STATUS    RESTARTS   AGE
sshproxy-2055042783-0vpfw   1/1       Running   0          2h
webshell2-348936596-dqpfg   1/1       Running   0          2h

real    0m0.325s
user    0m0.221s
sys    0m0.035s

different namespaces, time cost different

**What you expected to happen**:
every namespace cost equal time
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-custom", GitCommit:"edfa36536aae18a8821cd5eeab13741e0291bb79", GitTreeState:"clean", BuildDate:"2017-11-08T08:50:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hzxuzhonghu** [comment]
@timchenxiaoyu Always reproduce?

**Comment by timchenxiaoyu** [comment]
yes

**Comment by hzxuzhonghu** [comment]
improve kubectl log level, see log .

**Comment by hzxuzhonghu** [comment]
Also watch apiserver log .

**Comment by timchenxiaoyu** [comment]
[12.517µs] [12.517µs] About to List from storage
[3.672445919s] [3.672433402s] Listing from storage done
[3.676800574s] [4.354655ms] Self-linking done
[4.388004794s] [711.20422ms] Writing http response done (3429 items)

**Comment by timchenxiaoyu** [comment]
kubectl get pod -n qinzhao --show-all|wc -l
3110
[root@master-test-105 tmp]# kubectl get pod -n qinzhao --show-all
NAME                                                READY     STATUS       RESTARTS   AGE
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-5tf98        0/1       Init:Error   0          2h
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-5thf4        0/1       Init:Error   0          3h
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-5tjtp        0/1       Init:Error   0          1h
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-5vgrg        0/1       Init:Error   0          2h
cifid-h1brxegb7z-cisid-h1t4exbxb-mbwdt-5vn99        0/1       Init:Error   0          1d

**Comment by hzxuzhonghu** [comment]
Not that, some thing like this `I1117 11:04:12.834673  113951 wrap.go:42] GET /api/v1/namespaces/kube-system/serviceaccounts/horizontal-pod-autoscaler: (1.932724ms) 200 [[hyperkube/v1.9.0 (linux/amd64)`
 And kubectl --v=10

**Comment by timchenxiaoyu** [comment]
two many dead job(pods) lead query slowly

**Comment by roycaihw** [comment]
cc @jennybuckley
