### ISSUE TITLE
The current device plugin endpoint TestRun UT doesn't work

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/kubernetes#55920]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

For now, UT `TestRun` in `pkg/kubelet/cm/deviceplugin/endpoint_test.go` doesn't work because callback function will never be called, `callback function` is rewritten in this function `esetup()`:

```go
e, err := newEndpoint(socket, "mock", make(map[string]pluginapi.Device), func(n string, a, u, r []pluginapi.Device) {})
```
Another thing, i'm wondering why we rewrite device health in function `ListAndWatch` which in this file: `pkg/kubelet/cm/deviceplugin/device_plugin_stub.go` 

```go
	var devs []*pluginapi.Device

	for _, d := range m.devs {
		devs = append(devs, &pluginapi.Device{
			ID:     d.ID,
			Health: pluginapi.Healthy,
		})
	}

	s.Send(&pluginapi.ListAndWatchResponse{Devices: devs})
```

**What you expected to happen**:

UT assertion should be executed.

**How to reproduce it (as minimally and precisely as possible)**:

Add some logs in callback function of `TestRun()`, it will show nothing. 

**Anything else we need to know?**:

I will send a PR to fix this.

/cc @jiayingz @RenaudWasTaken @lichuqiang WDYT?
/sig node

**Comment by RenaudWasTaken** [comment]
Good catch @ScorpioCPH
