### ISSUE TITLE
pod should be deleted with force option with taint based eviction

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#55934]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

 /kind bug

> /kind feature

**What happened**:

With taint based eviction enabled, if I shutdown a worker node or stop the kubelet service on the node, the pod running on that node will be evicted and re-scheduled to other available nodes.

The problem is that the original pod running on the off node will keeps in `Terminating` state and never disappear. I have to delete it with `--grace-period=0 --force` option or bring back the off node.

```
[root@ib17b05 ~]# kubectl get pods -owide
NAME                        READY     STATUS        RESTARTS   AGE       IP             NODE
my-nginx-54d9957dd5-gtdws   1/1       Terminating   1          18m       10.1.169.132   9.21.53.17
my-nginx-54d9957dd5-pf8qh   1/1       Running       0          9m        10.1.160.131   9.21.53.24
```

**What you expected to happen**:

We should delete the pods on off node with `--grace-peroid=0 --force` option to make sure that they do not appear on dashboard.

/cc @gmarek 

/sig node

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
I think that we need to fix this issue, as with statefulset, if one node goes down, then the statefulset will never come back as the statefulset request the pod must be deleted before re-create due to the name was same even if statefulset restart.

/sig app

**Comment by gmarek** [comment]
That's the desired behavior. cc @smarterclayton

**Comment by gyliu513** [comment]
Thanks @gmarek what is the reason that we do not want to delete the pods by force? How to handle the case of statefulset for such case?

**Comment by smarterclayton** [comment]
The kubelet is the only process allowed to force delete pods.  Please read the [pod safety design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/pod-safety.md) for a deeper explanation why.

**Comment by gyliu513** [comment]
ok, I see, thanks @smarterclayton and @gmarek , I will close this one as we already have document for the behavior.
