### ISSUE TITLE
pvc: glusterfs provisioner create volume with the wrong size

### ISSUE THREAD

**Issue by saheienko** [kubernetes/kubernetes#55937]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Create 50Gi podVolumeClaim with glusterfs provisioner.

**What you expected to happen**:
I expected 50Gi volume would be created, instead of 54Gi.
```
$ k get pvc -o yaml test-volume-gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
  creationTimestamp: 2017-11-17T10:16:43Z
  name: test-volume-gi
  namespace: default
  resourceVersion: "478898"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/test-volume-gi
  uid: 68eddbe2-cb80-11e7-8724-002590e72b34
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: regular
  volumeName: pvc-68eddbe2-cb80-11e7-8724-002590e72b34
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 54Gi
  phase: Bound
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create storage class with glusterfs as dynamic provisioner.
2. Create podVolumeClaim.

**Anything else we need to know?**:
Commit, that cause it: https://github.com/kubernetes/kubernetes/commit/77be9123f7f38ffb3a0a4ae79f698e49ffff56a6

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-dirty", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"dirty", BuildDate:"2017-10-19T11:36:32Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saheienko** [comment]
@kubernetes/sig-storage
/sig storage

**Comment by saheienko** [comment]
Is it better to check binary/decimal format?

```
	volSizeBytes := capacity.Value()
	// Glusterfs creates volumes in units of GBs
	var sz int
	switch capacity.Format {
	case resource.BinarySI:
		sz = int(volume.RoundUpSize(volSizeBytes, 1024*1024*1024))
	default:
		sz = int(volume.RoundUpSize(volSizeBytes, 1000*1000*1000))

	}
```

**Comment by stewart-yu** [comment]
make sense

**Comment by gnufied** [comment]
The bug doesn't exist in the commit you linked. Heketi can't provision volume in chunks of GiB that you are requesting, so it is never going to provision 50GiB if you asked for 50GiB. It will round the value upto GB and provision it. 

For example, if you are asking for 50GiB it will provision 51GiB after rounding upto to GBs. The problematic line in code is - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L732 

That line incorrectly assumes returned integer from `CreateVolume` function to be in GiB whereas it is in GB, it should be relatively easy fix to change that line.  So If you request 50GiB it will give you 54GB and 51GiB.

**Comment by saheienko** [comment]
Yeah, inside the container i got:
```
$ k exec -it web-0 sh
# df -hT      
Filesystem                                    Type            Size  Used Avail Use% Mounted on
10.0.0.5:vol_9b93bfd8c134ca081e1044c67d369cb3 fuse.glusterfs   54G   34M   54G   1% /usr/share/nginx/html
```

**Comment by gnufied** [comment]
Yep, the problem is in how the size is represented in PV. @saheienko can you make a PR for fixing it?

**Comment by saheienko** [comment]
Yes, it would be great.

**Comment by humblec** [comment]
Completely agree to what @gnufied wrote. @saheienko thanks for the PR.

**Comment by saheienko** [comment]
Hello. 

I've tried to migrate from Gi to G and got stucked.

Heketi creates volumes in GB ([api](https://github.com/heketi/heketi/wiki/API#volume_create)), that means 1024\*1024\*1024 ([src](https://github.com/heketi/heketi/blob/9d2ef4bbaf547f5b86055e935f1d583196a069f1/apps/glusterfs/volume_entry.go#L27)) or Gi in k8s format.

So, when I create pvc with 50Gi, gluster plugin parses it as 54G and than heketi creates volume as 54Gi in k8s format.

And revious df output means Gi too:

```bash
$ kubectl exec -it web-0 sh
# df -hT      
Filesystem                                    Type            Size  Used Avail Use% Mounted on
10.0.0.5:vol_9b93bfd8c134ca081e1044c67d369cb3 fuse.glusterfs   54G   34M   54G   1% /usr/share/nginx/html

# df --help 
...
SIZE is an integer and optional unit (example: 10M is 10*1024*1024).  Units          
are K, M, G, T, P, E, Z, Y (powers of 1024) or KB, MB, ... (powers of 1000).         
...
``` 

PS
Sorry for insistence, but it really makes sense for my project.

**Comment by saheienko** [comment]
@humblec @gnufied
