### ISSUE TITLE
Document EBS Node with impaired volume taint

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#55946]
We should properly document node with impaired volumes taint, so as users know what that means and how to fix it.

/sig aws
/sig storage

**Comment by akumria** [comment]
/reopen

@gnufied  Happy to give this a try as a first contribution - where should I document the taint?

Over here: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ ?

**Comment by rcjsuen** [comment]
I have a node with `NodeWithImpairedVolumes=true:NoSchedule` right now and while I got the general idea from #55558, it would be great to have this explained in the official documentation. Thanks!

**Comment by TheoBrigitte** [comment]
I also ran into an issue where 4 out of 11 nodes where tainted with `NodeWithImpairedVolumes=true:NoSchedule`, this resulted in many pods not being scheduled, some documentation would be appreciated.


How about something along those lines ?

> When an AWS EBS volume is stuck in attaching state for more than 30mn on a node, it will be marked as unschedulable with the following taint:
> ```
>  taints:
>  - effect: NoSchedule
>    key: NodeWithImpairedVolumes
>    value: "true"
> ```


What is the procedure to follow when such taint is observed, reboot the node and manually remove the taint ?

**Comment by gnufied** [comment]
Yeah the generation procedure is drain the node and reboot it and manually remove the taint. @akumria sorry for super late response but we can document this https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore .

**Comment by rcjsuen** [comment]
@gnufied How can I help with getting this documented?

**Comment by jammerful** [comment]
@gnufied Yes, please let us know how to document this. Just ran into this taint.

**Comment by gandhiano** [comment]
maybe this can be reopened? /reopen

**Comment by BouweCeunen** [comment]
I don't have Volumes which are in an unattached state, I'm getting this daily, it's getting quite annoying. Anyone any idea why this would happen so much?

**Comment by pappnase99** [comment]
Just ran into this taint of which i've never heard of before. The volumes on the tainted node were all working fine. Some documentation about how to deal with this situation would be much appreciated.

**Comment by BouweCeunen** [comment]
It has never happened to me on T2 instances on AWS, can anyone also confirm? It could be related to nitro instances: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances. I'm seriously considering writing a script to patch and remove this taint when it occurs.

**Comment by TomMD** [comment]
This is the first result Google has for `NodeWithImpairedVolumes=true:NoSchedule`.  It's a sad state for support.

**Comment by BouweCeunen** [comment]
Indeed, I made a deployment that removes this taint when it occurs as a last resort. 😄 Didn't have any issues since.
https://github.com/BouweCeunen/clear-impaired-volumes-taint

**Comment by gnufied** [comment]
The reason we taint such nodes is - because once a node has one or more volumes stuck in "attaching" state, it most likely means any attempts to attach new volumes to same node will result in same failure. 

There could be two reasons for volume stuck in attaching state:

1. It could be because node has reached attach limit and in which case obviously new volumes can not be attached to the same node either. 
2. The second reason is - in some cases when force detached is used from a node, it can cause any attempts to attach new volumes to be stuck in "attaching" state.

In Kubernetes we do not have a way to allow scheduling of pods without volumes but still block pods with volumes via taints. So k8s behaviour is bit heavy handed but it helps problems from compounding in production.  I have personally seen more than 10 volumes stuck in attaching state to the same node because of any aforementioned reason.
