### ISSUE TITLE
Error from server (BadRequest): container

### ISSUE THREAD

**Issue by hosein33** [kubernetes/kubernetes#55958]
/sig scalability
/kind bug
I've create a deployment and a service archiva app  and deployed them using kubernetes , that stuck in ContainerCreating and log is : 
Error from server (BadRequest): container "archiva" in pod "archiva-deploy-868271406-p7v7q" is waiting to start: ContainerCreating

**Comment by dixudx** [comment]
@hosein33 Please run `kubectl describe pod archiva-deploy-868271406-p7v7q` to see the detailed events.

Also this may not be a bug of kubernetes. Please ssh to the docker host and find the root cause.

**Comment by mujeebishaque** [comment]
I am facing the same issue. The logs say, the container in pod waiting to start. kubectl describe output doesn't show any anomaly or error.
