### ISSUE TITLE
Support out-of-tree authentication providers

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#55968]
Two use-cases for authentication for which we likely can't force a standard:
* End user authentication: We want to support a variety of standard and non-standard end user authentication portocols to vendors with possibly interactive login flows.
* Node bootstrap authentication: We want to support secure node bootstrap authentication in mixed deployment environments where node attestation information comes from a variety of sources and in a variety of formats (e.g. TPM attestation doc, vm signed metadata).

The current model for authentication providers is in-tree:

https://github.com/kubernetes/client-go/blob/master/rest/plugin.go#L29-L36

This model is not scalable. We need to explore an extension mechanism that can support these use-cases out of tree. A good test will be to move the existing plugins, (e.g. GCP) to out of tree plugins that use the extension. We can then add support of the extension point to kubernetes conformance.

@kubernetes/sig-auth-feature-requests

**Comment by mikedanese** [comment]
Categories of authentication protocols that might be employed:
* Bearer token auth
* Request signing (JWS, AWS v4)
* Transport layer (TLS Client Auth, Token Binding)

Possible extension mechanisms:
* Exec
* IPC
* Dynamic loading

Current auth provider signature:
```golang
func(*http.Request) (*http.Response, error)
```

**Comment by ericchiang** [comment]
There was discussion in the past of just being able to provide an exec command that would print a bearer token to stdout, which was going to be used for different flavors of gcp. Will try to dig up that conversation.

**Comment by ericchiang** [comment]
I think we should just add the exec plugin described in https://github.com/kubernetes/kubernetes/issues/35530. We can expand for other uses cases that don't include bearer tokens later.

/assign

**Comment by mattmoyer** [comment]
+1 on an `exec` plugin. I have a use case for something like that to work with https://github.com/heptio/authenticator.

**Comment by liggitt** [comment]
similar request in https://github.com/kubernetes/kubectl/issues/62, could be solved with an "exec for cert+key" auth plugin

**Comment by ericchiang** [comment]
Proposal here https://github.com/kubernetes/community/pull/1503

**Comment by jberkus** [comment]
has there been any work on this since December?  If not, please remove it from the 1.10 milestone,  Thanks!

@liggitt @ericchiang

**Comment by mikedanese** [comment]
@jberkus https://github.com/kubernetes/kubernetes/pull/59495

**Comment by jberkus** [comment]
@mikedanese in that case, can you add status/approved-for-milestone to both this issue and the PR?  thanks!

**Comment by mikedanese** [comment]
Only half of the proposal is implemented. Let's finish off the TLS bits.

**Comment by mikedanese** [comment]
tracked in https://github.com/kubernetes/kubernetes/issues/61421 now
