### ISSUE TITLE
Add Pod-level Resource Usage Stats

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#55978]
With all the features related to pod-level management ([pod cgroup](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/pod-resource-management.md#add-pod-level-metrics-to-kubelets-metrics-provider), [pod-level resource management](https://github.com/kubernetes/kubernetes/issues/27204) and [local ephemeral storage isolation](https://github.com/kubernetes/features/issues/361)) added recently, it becomes necessary to provide more Pod-level metrics including CPU, memory and ephemeral storage usage consumed by individual pod. Pod-level accounting could help solve the following issues

- Pod level monitoring can help account for pod resource usage overhead that is otherwise accounted to the node.
- For local disk usage, ephemeral storage might be used by volumes (pod-level property) or consumed by containers. Although kubelet reports volume usage at pod-level, there is no way to tell whether the volume is using ephemeral storage or not. So users could not figure out how much total ephemeral storage is used by a pod.

The first step of exposing pod-level is Kubelet Summary API change:

- CPU and memory: the usage information should be obtained by cAdvisor’s pod-level cgroup
- Ephemeral-storage: the usage is calculated as the sum of all containers usage and all local ephemeral volume usage including emptyDir (where medium is not memory or hugepages) , configureMap, and downwardAPI. 

The next step requires the following changes:
1. Add pod-level metrics to master metric server so that other k8s components can use the metrics (e.g., kubectl top)
2. Add to heaspter to scrape the metrics so that stackdriver can use them.

**Comment by jberkus** [comment]
Hey, since the related PR is approved-for-milestone, can you mark this issue the same way?  Thanks.

**Comment by jberkus** [comment]
Should this issue be resolved, at this point, given the PR merges?

**Comment by jingxu97** [comment]
The changes for Kubernetes 1.9 part is finished, so close this issue.
