### ISSUE TITLE
kube-proxy takes too long to bind port on external (host) ip

### ISSUE THREAD

**Issue by gree-gorey** [kubernetes/kubernetes#55975]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I use kube-proxy:v1.9.0-beta.0 in ipvs mode.
When creating many services (~30k) with external ip type, it takes too long for kube-proxy to open and bind ports on the host. When I ran `watch -n1 "netstat -plnt | grep kube-proxy | wc -l"` I see that it opens ab 1-2 ports per second, so it would take 50 minutes to bind 3000 ports and 8 hours to bind all 30k ports that I created. And this happens every time I restart the machine or the pod with kube-proxy. There is no errors in kube-proxy log:
```
I1117 19:16:15.503831       1 feature_gate.go:184] feature gates: map[SupportIPVSProxyMode:true]
W1117 19:16:15.503932       1 server.go:181] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I1117 19:16:15.980189       1 server_others.go:164] Using ipvs Proxier.
I1117 19:16:16.050181       1 server_others.go:188] Tearing down inactive rules.
I1117 19:16:16.225460       1 server.go:420] Version: v1.9.0-beta.0
I1117 19:16:16.247298       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I1117 19:16:16.247629       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I1117 19:16:16.247740       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1117 19:16:16.247822       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1117 19:16:16.247999       1 config.go:102] Starting endpoints config controller
I1117 19:16:16.248028       1 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
I1117 19:16:16.248089       1 config.go:202] Starting service config controller
I1117 19:16:16.248099       1 controller_utils.go:1019] Waiting for caches to sync for service config controller
I1117 19:16:17.062950       1 controller_utils.go:1026] Caches are synced for endpoints config controller
I1117 19:16:17.248246       1 controller_utils.go:1026] Caches are synced for service config controller

```
kube-api responding also without errors:
```
Trace[643705522]: [1.087755086s] [1.087749316s] Listing from storage done
I1117 21:07:46.063215       1 trace.go:76] Trace[1226540394]: "List /api/v1/services" (started: 2017-11-17 21:07:45.379258292 +0000 UTC) (total time: 683.890471ms):
Trace[1226540394]: [538.226979ms] [538.220216ms] Listing from storage done
Trace[1226540394]: [683.888591ms] [131.297142ms] Writing http response done (29400 items)

```
So, it seems to me there is something wrong with kube-proxy.
What can cause this?
Also, kube-proxy use large amount of CPU (from 50% to 150%).

**What you expected to happen**:
Kube-proxy opens and binds external ip ports in a reasonable amount of time.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Kube-proxy flags:
```
        - /usr/local/bin/kube-proxy
        - --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf
        - --cluster-cidr=10.244.0.0/16
        - --feature-gates=SupportIPVSProxyMode=true
        - --proxy-mode=ipvs
        - --ipvs-scheduler=rr
        - --ipvs-sync-period=1m
```

**Environment**:
- Kubernetes version (use `kubectl version`): kubelet=1.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux 4.4.0-98-generic
- Install tools: kubeadm=1.8.3
- Others: kube-proxy-amd64:v1.9.0-beta.0

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by gree-gorey** [comment]
I just wonder, why kube-proxy have to open ports in the first place?
Why cannot it add rules in ipvs for external IP, just like it does for cluster IP? It would be much more efficient (it seems to me).
I think kube-router does smth similar, adding external IP rules in ipvs.
Or am I missing smth?

**Comment by m1093782566** [comment]
> I just wonder, why kube-proxy have to open ports in the first place?

Because kube-proxy needs to hold the port in case of the port is occupied by other processes.

> Why cannot it add rules in ipvs for external IP, just like it does for cluster IP? It would be much more efficient (it seems to me).

IPVS kube-proxy does add rules for external IP. Can you check the result of `ipvsadm -ln`  or kube-proxy.log?

**Comment by gree-gorey** [comment]
OK, now I get it.
Yes, it does add rules.
But the problem still is that it takes very long time to loop through all the services and add them.
