### ISSUE TITLE
Enable gating node e2e tests in CI for CPU manager component.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#55980]
/sig node
/kind feature

Node e2e tests exist for the CPU manager but cannot run because they require multiple CPUs to be available in the test VM. Before allowing the feature to graduate from alpha to beta, these tests should be made gating to prevent regressions.

**Comment by balajismaniam** [comment]
The results from a periodic job for the node e2e test are available in https://k8s-testgrid.appspot.com/wg-resource-management#kubelet-serial-gce-e2e-cpu-manager. 
Note that this not a gating test. The recommendation from the community was to start with a periodic job, work on stabilizing the tests in the k8s CI/CD env if required and then make it a gating test at a later time.

**Comment by balajismaniam** [comment]
The CPU manager tests are not gating yet. 
/remove-lifecycle stale
