### ISSUE TITLE
Use clients with explicit version

### ISSUE THREAD

**Issue by supereagle** [kubernetes/kubernetes#55993]
Clients without explicit version have been deprecated, and most of their usage has been fixed by #49763 and #50776. However, some new usage are introduced during the long merging process of the two PRs. In order to avoid this case, need to fix these usage in a short time, and remove the deprecated clients.

Work Items:
- [x] Clean up the usage of deprecated clients
  - [x] ~Admissionregistration~ (Has been cleaned up, needs no action)
  - [x] ~Apps~ (Has been cleaned up, needs no action)
  - [x] Authentication #56411
  - [x] ~Authorization~ (Has been cleaned up, needs no action)
  - [x] ~Autoscaling~ (Has been cleaned up, needs no action)
  - [x] Batch #56263
  - [x] ~Certificates~ (Has been cleaned up, needs no action)
  - [x] Core #55991
  - [x] Extensions #55995 
  - [x] ~Networking~ (Has been cleaned up, needs no action)
  - [x] Policy #56413
  - [x] Rbac #56654
  - [x] ~Scheduling~ (Has been cleaned up, needs no action)
  - [x] ~Settings~ (Has been cleaned up, needs no action)
  - [x] ~Storage~ (Has been cleaned up, needs no action)
- [ ] Remove the deprecated clients

@caesarxuchao @k82cn @sttts @kevin-wangzefeng

**Comment by caesarxuchao** [comment]
cc @roycaihw we should put a deprecation notice fro this in the next client-go release note.

**Comment by caesarxuchao** [comment]
Could you try to remove all the deprecated clients locally, and see if there is any unexpected effects?

**Comment by supereagle** [comment]
@caesarxuchao  I use this way to verify that all usage of deprecated clients has been completely cleaned up. The check is to run `make verify`, `make test` and `make test-integration`, is there any other additional check?

**Comment by sttts** [comment]
> cc @roycaihw we should put a deprecation notice fro this in the next client-go release note.

We have that for ages already in the clientset go files.

**Comment by supereagle** [comment]
@caesarxuchao I find some new codes still use these deprecated clients, is there any timetable to remove these clients?
