### ISSUE TITLE
kubelet not able to read /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

### ISSUE THREAD

**Issue by rremella** [kubernetes/kubernetes#55997]
I am getting this below issue when I say kubeadm init , looks kubelet is failing to start

[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
^A[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by that:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
        - There is no internet connection; so the kubelet can't pull the following control plane images:
                - gcr.io/google_containers/kube-apiserver-amd64:v1.8.3
                - gcr.io/google_containers/kube-controller-manager-amd64:v1.8.3
                - gcr.io/google_containers/kube-scheduler-amd64:v1.8.3

-- Unit kubelet.service has begun starting up.
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.163574   29808 feature_gate.go:156] feature gates: map[]
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.163663   29808 controller.go:114] kubelet config controller: starting controller
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.163670   29808 controller.go:118] kubelet config controller: validating combination of defaults and flags
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.168495   29808 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.168522   29808 client.go:95] Start docker client with request timeout=2m0s
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.169917   29808 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.173723   29808 feature_gate.go:156] feature gates: map[]
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.173851   29808 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.173879   29808 server.go:324] standalone mode, no API client
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.176122   29808 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.serv
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.186910   29808 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.187028   29808 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: di
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.196183   29808 fs.go:139] Filesystem UUIDs: map[f239b13f-f4ef-490d-90e3-dfece431b444:/dev/vda1]
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.196208   29808 fs.go:140] Filesystem partitions: map[tmpfs:{mountpoint:/dev/shm major:0 minor:17 fsType:tmpfs block
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.198786   29808 manager.go:216] Machine: {NumCores:2 CpuFrequency:2599998 MemoryCapacity:16658718720 HugePages:[{Pag
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.202252   29808 manager.go:222] Version: {KernelVersion:3.10.0-514.26.2.el7.x86_64 ContainerOsVersion:CentOS Linux 7
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.202792   29808 server.go:232] No api server defined - no events will be sent to API server.
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.202814   29808 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.204682   29808 container_manager_linux.go:252] container manager verified user specified cgroup-root exists: /
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.204707   29808 container_manager_linux.go:257] Creating Container Manager object based on Node Config: {RuntimeCgro
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.204842   29808 container_manager_linux.go:288] Creating device plugin handler: false
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.207979   29808 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.208006   29808 kubelet.go:517] Hairpin mode set to "hairpin-veth"
Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.210637   29808 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 18 08:35:14 tops1 kubelet[29808]: I1118 08:35:14.215302   29808 docker_service.go:207] Docker cri networking managed by kubernetes.io/no-op
Nov 18 08:35:14 tops1 kubelet[29808]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from dock
Nov 18 08:35:14 tops1 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Nov 18 08:35:14 tops1 systemd[1]: Unit kubelet.service entered failed state.
Nov 18 08:35:14 tops1 systemd[1]: kubelet.service failed.

contents of file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf as below

Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"

**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Doing kubeadm init
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@rremella Can you please move this to https://github.com/kubernetes/kubeadm/issues ?

**Comment by dixudx** [comment]
> Nov 18 08:35:14 tops1 kubelet[29808]: W1118 08:35:14.169917 29808 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d

@rremella Please remove `KUBELET_NETWORK_ARGS` in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`. And then `systemctl daemon-reload`.

**Comment by dixudx** [comment]
/close

dup of #48798
