### ISSUE TITLE
Pass pod labels to containers and to lifecycle hooks

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#560]
For context, see: https://groups.google.com/d/msg/google-containers/frOLMyNl5U4/W5_DQUL933IJ

Idea specifically is to have a <service_name>_LABELS env var in addition to the service's port.

Filing as an issue to track discussion. I'm unsure if it's generally useful enough to justify the extra complexity.

**Comment by smarterclayton** [comment]
Somewhat opinionated proposal of how downward API could be exposed as env for both labels and service values described here:

https://github.com/GoogleCloudPlatform/kubernetes/issues/1768#issuecomment-71331800

Essentially, do a limited form of env var substitution as pre-processing pass on the Pod prior to invoking docker start.  Walk the list once to get all the user provided env, then go through and allow env substitution and let the substitution values pull from a) kubernetes "downward env API" source (service vars, labels, pod info) and b) env vars.  Optionally, we could include c) env in the image.  Then we would pass that entire env to the container.

This would mean we would never inject env into the user's container by default (so no hidden magic variables except service hosts for now), but users would be able to selectively include variables by name.  The kube downward env API vars could be appropriately namespaced.

**Comment by thockin** [comment]
And then users who want the actual string "$" in their env vars need to
escape them?  Puke.

I could buy a new block of env vars that are explicitly handled this way,
but not the default block.

**Comment by smarterclayton** [comment]
There would be a flag that says you want this.  I'm not insane, just dangerous.  Like "Resolve":true or "expand":true

**Comment by smarterclayton** [comment]
I clarified in the other one this was explicit opt in on a per var basis, but forgot to copy that here.

**Comment by thockin** [comment]
I could probably live with that.  As per the migration issue - exposing
some of this stuff is actually detrimental to migration.  Tread carefully.

**Comment by smarterclayton** [comment]
True.  I was thinking as a default of exposing only host, port, and maybe a few attributes off the pod.  We could then nuke the docker style env vars.

At least here we have a way to do a migration, vs with magic env vars that show up and people use without you being able to tell.

**Comment by pmorie** [comment]
@smarterclayton Clarifying for the record that by flag in your above comment you mean attribute on `api.EnvVar`.  Confirm?

**Comment by smarterclayton** [comment]
Yes, although a separate block is also reasonable.  Is a separate block easier to reason about, or confusing to new users?

**Comment by pmorie** [comment]
@smarterclayton I think a separate block that is designated as being resolved is probably easier to reason about, but that's my own subjective opinion.  @sdminonne, any opinions about that?

**Comment by bgrant0607** [comment]
FWIW, this should probably be discussed in #386.

As @thockin cautioned and as mentioned in #3949, I wouldn't expose a pod's host.

Note that any property encoded in an env. var. would require a container restart when its value changed.

I'd prefer a separate block, similar to the distinction between labels and annotations.

**Comment by sdminonne** [comment]
I would prefer to avoid a new block. 
I've a few reasons for that:
1) In our use cases we really need labels to be injected in the pod (for example to prefix logs which will be sent to log server pods). We'll use labels to constrain scheduling algorithms and would like to avoid having a block for the scheduler and a block for env var injection.
2) A new block is another group of info in an already crowded json/yaml file

Looking at https://github.com/GoogleCloudPlatform/kubernetes/issues/386 (@smarterclayton I wasn't aware of it when we started the discussion about this) the /etc/labels file (proposed by @bgrant0607) sounds a reasonable solution. The container applications are free to use or ignore this information and dynamic updates to it. The syntax key=label is fine.

**Comment by thockin** [comment]
I have a slight preference for a new block, but the /etc/labels file or
something like it sounds OK too.  The nice thing about a new block is that
we can extend it to define new things like "also expose labels as a file at
this path".  Extending Env is more restircted.

**Comment by smarterclayton** [comment]
Good point - it would be nice to make that flexible.  We could also introduce a volume type that can pull labels or volumes.  I guess the question is - what is the boundary for volume types?  File generation?  File generation from a template?  Retrieving keys from etcd and then transforming them?  Or is that a job for sidecar containers or pre start lifecycle hooks?

**Comment by thockin** [comment]
Right now volumes are run-once.  If you need something active, as in a git
syncer, it's not a volume.  we might want to extend the volume abstraction,
but later.

**Comment by pmorie** [comment]
After some thought and discussion with @sdminonne, @EricMountain-1A, and @smarterclayton, I had some thoughts on this:

1.  We know different users will want this information both as volumes and environment variables
2.  There are other sources of data users want in this manner (secrets, service metadata)
3.  The `VolumeSource` / kubelet volume plugin abstraction is a good one (my opinion) for exposing different information into pods as volumes
4.  Should there be a similar source abstraction for environments?  I don't think simply generating env vars will be sufficient for all cases (for example, you wouldn't want to expose secret data as env vars using the current mechanism since the data can be captured by a container commit)

Thinking through the possibility of a source abstraction for environments in the context of this issue:

1.  Add a new `DynamicContext` block to a pod; this block will allow you to adapt different sources of information (labels, service metadata, etc)
2.  Add a new `EnvironmentSource` abstraction to a container; the existing method of specifying values for environment becomes something like `ManualSource`
3.  Add a new `DynamicContextSource` for environment variables; this will allow you to adapt pieces of `DynamicContext` into environment variables
4.  Add a new `DynamicContextVolumeSource` for volumes; this will allow you to adapt piece of the dynamic context into volumes / files

Other source of information can be adapted with new Source implementations.

Typing this out, I'm not sure if I like it.

Any thoughts, @smarterclayton @sdminonne @EricMountain-1A @thockin @bgrant0607 @lavalamp ?

**Comment by smarterclayton** [comment]
That's a lot of things to add to a pod.  I don't know that genericizing the source of the info is the solution though, because it adds more abstractions in a common path.  If you can dynamically mutate env prior to create, that's enough for basic adaptation / exposing downward api info into pods. If you want to do more sophisticated calculation, do it in your pod.

I haven't had time to write up detailed feedback of the proposed generated env structure, but I think we want to be careful to do two things:

1. Clearly identify which values are coming from the downward API, so that we can migrate and version the downward API
2. Only solve the bare minimum of substitution to allow transforming multiple variables and interspersed constants into one (host/port/protocol -> url, base paths for secrets / volumes -> full path)

More complex calculation can be done in the container.

**Comment by pmorie** [comment]
@smarterclayton It seems heavy to me too.

**Comment by EricMountain-1A** [comment]
@pmorie I'm tempted to not have kubernetes inject environment variables into containers, and limit the proposal to making labels and other metadata available simply through volumes - then it's up to containers to decide how they want to use this data.  This would simplify your proposal, and if the volume abstraction is later extended to allow for dynamic updates of this data - as mentionned above by @thockin - at least containers have the option to refresh the data (periodically, inotify...), whereas you'd never be able to update their environment variables.

Having a generic way to generate volumes from a variety of sources of data sounds good (with minimal computation as @smarterclayton said). @sdminonne is working on a proposal for [getting metadata into containers](https://github.com/sdminonne/kubernetes/blob/labels_to_container_proposal/docs/design/labels_to_pods.md) - it could be adapted to cover secrets, e.g:

````
"generated": [
     {"volume":
       [ { "path": "/etc/secret1",
           "from": "secrets",
           "type": "tmpfs",
         }
      ]
    },
    {"volume":
       [ { "path": "/etc/labels",
           "from": "labels",
           "entries":
               [ { "generate": "%s",
                   "name": "name" }
               ]
         }
      ]
    }
]
```

**Comment by thockin** [comment]
I could get behind a volume plugin to expose some of these things, I
guess.  The only real difference between a volume plugin and a container
that writes to disk is the startup ordering.

But again, if you ever want this info updated dynamically, I don't think
you want a volume, you want a container.  For now, any change to the pod
structure (e.g. labels) should trigger a restart, but it should eventually
be possible to update labels on the fly.

As a straw man, we should have some way to map "static-ish" kubernetes data
onto env vars.  E.g. put the pod's  namespace into MY_POD_NS and name into
MY_POD_NAME.  Now run a side-car container that does a watch on
$MY_POD_NAME.$MY_POD_NS and updates a shared EmptyDir whenlabels change.

**Comment by smarterclayton** [comment]
> On Feb 17, 2015, at 12:23 AM, Tim Hockin <notifications@github.com> wrote:
> 
> I could get behind a volume plugin to expose some of these things, I
> guess. The only real difference between a volume plugin and a container
> that writes to disk is the startup ordering.
> 
> But again, if you ever want this info updated dynamically, I don't think
> you want a volume, you want a container. For now, any change to the pod
> structure (e.g. labels) should trigger a restart, but it should eventually
> be possible to update labels on the fly.
> 
> As a straw man, we should have some way to map "static-ish" kubernetes data
> onto env vars. E.g. put the pod's namespace into MY_POD_NS and name into
> MY_POD_NAME. Now run a side-car container that does a watch on
> $MY_POD_NAME.$MY_POD_NS and updates a shared EmptyDir whenlabels change.

That's a good straw man.  I have a large enough set of use cases for simple env composition that I don't think it's wasted effort, but it does need to focus on the simplest possible expression and use case (it's ok to limit the scope of expressiveness). It's a 20-30% tool

> 
> On Mon, Feb 16, 2015 at 6:23 AM, Eric Mountain @ Amadeus <

**Comment by sdminonne** [comment]
@smarterclayton @thockin (if I'm understanding correctly)
so an EmptyDir for modifiable metadata (as far as I know only label) and ENV vars for static ones. 
Using a new block to define these new behaviors. 
@smarterclayton do you think what reported by @EricMountain-1A 
```
"entries":
               [ { "generate": "%s",
                   "name": "name" }
               ]
``` 
is enough in term of expressiveness or do you think we need something more complex?

**Comment by pmorie** [comment]
@sdminonne I imagined the following:

1.  Static values exposed as environment vars or with a new volume plugin
2.  For dynamic values:
    1.  Create an `EmptyDir` volume in your pod
    2.  Make a container that uses the downward API to project information from the master into the volume (the sidecar container)
    3.  Watch the files in the volume from your 'main' container

Does that match your reading?

**Comment by sdminonne** [comment]
@pmorie  it does.
Thanks

**Comment by pmorie** [comment]
@sdminonne @smarterclayton @thockin Are there enough commonalities about the dynamic data from the downward API that it can be a shared component, ie `kubernetes/pod-info-sidecar` ?

**Comment by pmorie** [comment]
@sdminonne Expanding a little bit, I was referring to an image for the proposed sidecar container that would handle populating a shared volume with dynamic data about the pod, and whether that image would have enough common utility that it should be a system component.  Put another way, is this a common enough use-case (get a volume with dynamic info about the pod projected into it by another container in the pod) that kubernetes should offer a docker image that does it?

**Comment by sdminonne** [comment]
@pmorie thanks for the explanation.
So we may end up with: a set of env variables injected in the POD, and  a `system` docker container where info can be found about PODs and those info are available via a shared filesystem?

**Comment by pmorie** [comment]
@sdminonne correct. The sidecar container would need auth to access the master, either via a secret consumed in the volume or something like the [LOAS Daemon](https://github.com/GoogleCloudPlatform/kubernetes/issues/2209).

**Comment by thockin** [comment]
Why would it need auth?  It all seems strictly read-only...

As for feature set, less is more unless there's no other choice.  I'd love
to say that the downward API is *just* about customizing env vars, and the
sidecar container can be more flexible.  Can we get away with that?

And yes, I think that a generic "sync kubernetes info to files" container
would be a great piece of the overall system.

**Comment by smarterclayton** [comment]
----- Original Message -----
> Why would it need auth?  It all seems strictly read-only...
> 
> As for feature set, less is more unless there's no other choice.  I'd love
> to say that the downward API is *just* about customizing env vars, and the
> sidecar container can be more flexible.  Can we get away with that?

I think so for the near term.  We can take real use cases to handle the container case, and adapt them in later if necessary.

**Comment by pmorie** [comment]
@sdminonne @thockin @smarterclayton @bgrant0607 

Continuing to flesh out the sidecar container outlined above:

```json
{
  "id": "kubernetes-info-test-pod",
  "kind": "Pod",
  "apiVersion":"v1beta2",
  "labels": {
    "name": "kubernetes-info-test-pod"
  },
  "desiredState": {
    "manifest": {
      "version": "v1beta1",
      "id": "kubernetes-info-test-pod",
      "containers": [{
        "name": "client-container",
        "image": "busybox",
        "command": [ "cat", "/etc/kubernetes-info/labels" ],
        "volumeMounts": [{
          "name": "kubernetes-info-volume",
          "mountPath": "/etc/kubernetes-info",
          "readOnly": true
        }]
      },
      {
        "name": "kubernetes-info-sidecar",
        "image": "kubernetes/kubernetes-info",
        "command": [ "write-kubernetes-info", "/etc/kubernetes-info"],
        "volumeMounts": [{
          "name": "kubernetes-info-volume",
          "mountPath": "/etc/kubernetes-info",
        }]
      }],
      "volumes": [{
        "name": "kubernetes-info-volume",
      }]
    }
  }
}
```

**Comment by sdminonne** [comment]
@pmorie thanks for this. 
@smarterclayton @thockin let's take the testcase which I already mentioned. Propagating labels to prefix log for aggregation (something similar to https://github.com/GoogleCloudPlatform/kubernetes/issues/4255). In this case at the `run` of the container we should write the file in /etc/kubernetes-info updating it at each `label`, `update`.
The updates should be triggered by the presence of a container named `kubernetes-info-sidecar`?

**Comment by pmorie** [comment]
Had a good chat w/ @sdminonne and @EricMountain-1A this morning.  Dario is going to prototype a new docker image for the sidecar container that will accept parameters for:

1.  The pod name and namespace
2.  A target directory to project information into
3.  Flags for which info to project (initially it will just support labels)

Example:

    project-pod-info --name=<pod name> --namespace=<pod namespace> --output-path=/pod-info --labels

The sidecar will poll the API server for information about the Pod (we had talked about watching, but I had forgotten that there is no watch API for pods) and refresh the information in the shared volume.

**Comment by pmorie** [comment]
@sdminonne @EricMountain-1A see @thockin's comments re: atomic update here: https://github.com/GoogleCloudPlatform/kubernetes/issues/4673#issuecomment-75359764

**Comment by bgrant0607** [comment]
Dumping info into files was also discussed in #386. I certainly prefer that over environment variables.

However, I think that doesn't address @smarterclayton's concerns about accidental coupling, opt-in for specific information, and adapting to application expectations rather than forcing them to adapt to Kubernetes conventions (other than deployment-time adapters).

**Comment by sdminonne** [comment]
Just add  https://github.com/GoogleCloudPlatform/kubernetes/pull/5093 as a possible implementation.

**Comment by bgrant0607** [comment]
Done enough, via downward API
