### ISSUE TITLE
[feature proposal] add SMB(cifs) volume plugin

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#56005]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**feature proposal**:
I would like to contribute a common SMB(one version called cifs) volume plugin, but not sure whether there is already some work on this.  There is already an implementation of SMB azure file (https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/azure_file), but it's under cloudprovider directory and it depends on azure, while I would like to implement a common SMB volue plugin.

SMB intro: https://en.wikipedia.org/wiki/Server_Message_Block

Current k8s volume support list on Windows:
https://github.com/andyzhangx/Demo/tree/master/windows#k8s-volume-support-on-windows-server-1709

Would appreciate any comments, thanks.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig storage
/assign

**Comment by andyzhangx** [comment]
@jdumars for comments

**Comment by feiskyer** [comment]
cc @kubernetes/sig-storage-feature-requests

**Comment by andyzhangx** [comment]
@kubernetes/sig-windows-feature-requests

**Comment by michmike** [comment]
hi @andyzhangx, can you please join the sig-windows slack channel where windows development is happening. i would love to discuss this feature request at our next meeting. ping me in Kubernetes slack (mmichael) for details

**Comment by rootfs** [comment]
@andyzhangx would flex or csi work? There are already cifs flex drivers around.

**Comment by andyzhangx** [comment]
@rootfs that's good question, I will try flex on Windows first, it's in my list.

**Comment by andyzhangx** [comment]
@michmike I am already in sig-windows, just mute in the group. And I am in China, the meeting time is too late for me, could you just paste your discussion result here? Thanks.
I raised this feature proposal just want to know whether there is some requiremnt for a new upstream SMB plugin, or a working cifs flex driver is enough?

**Comment by andyzhangx** [comment]
BTW, this month, azure released `Windows Server version 1709`, by this OS, azure disk & file mount  is already supported on Windows starting from v1.7.2.
You could find detailed info here:
https://github.com/andyzhangx/Demo/tree/master/windows#k8s-volume-support-on-windows-server-1709

**Comment by michmike** [comment]
@andyzhangx  we record all our meetings on youtube here https://www.youtube.com/playlist?list=PL69nYSiGNLP2OH9InCcNkWNu2bl-gmIU4

Right now, we have not discussed this at all, but we can add it for discussion after v1.9 ships.

**Comment by ieugen** [comment]
I would like to have such a feature as well. Any progress?

**Comment by andyzhangx** [comment]
There is already a [cifs flexvolume plugin on Linux](https://github.com/andyzhangx/kubernetes-drivers/tree/master/flexvolume/cifs), and I will write a cifs CSI driver on windows

**Comment by andyzhangx** [comment]
And before writing a new cifs CSI driver for windows, we need to make sure CSI driver works on windows well first, it depends on https://github.com/kubernetes-csi/drivers/issues/79

**Comment by PatrickLang** [comment]
Flexvolume driver for SMB here: https://github.com/Microsoft/K8s-Storage-Plugins

**Comment by jingxu97** [comment]
@andyzhangx with csi-proxy project, I think it provides a way to implement a generic CSI smb driver. Do you still have interests in working on it?

**Comment by andyzhangx** [comment]
> @andyzhangx with csi-proxy project, I think it provides a way to implement a generic CSI smb driver. Do you still have interests in working on it?

yes, it's tracking here: https://github.com/Azure/kubernetes-volume-drivers/issues/48,  will work out a working driver first.

**Comment by andyzhangx** [comment]
the new driver functionality is actually  subset of https://github.com/kubernetes-sigs/azurefile-csi-driver since it won't need dynamic provisioning, I am planning to create a new project, e.g. `smb-csi-driver`, put it under https://github.com/kubernetes-sigs/ finally. 
The new CSI driver https://github.com/kubernetes-sigs/smb-csi-driver would work on both linux and windows node, and it only provides static provisioning(user should bring their own SMB server address).

**Comment by jingxu97** [comment]
@andyzhangx that's great! Wondering whether we need to open a KEP for this or not in here https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows?

**Comment by msau42** [comment]
Would Kubernetes-csi be a good place for a generic smb driver? We already have common build and release infrastructure. Also generic nfs driver is also in the same org.

**Comment by andyzhangx** [comment]
> Would Kubernetes-csi be a good place for a generic smb driver? We already have common build and release infrastructure. Also generic nfs driver is also in the same org.

@msau42 thanks, the new smb driver should be under 
https://github.com/kubernetes-csi/csi-driver-smb

Since this driver would work on both linux and windows node, not sure it's necessary to open a KEP on sig-windows.

Anyway, let me work out an initial working version first. Should not take too much time.

**Comment by andyzhangx** [comment]
Update: here is the initial working SMB CSI driver:
https://github.com/csi-driver/csi-driver-smb
Will migrate to https://github.com/kubernetes-csi/csi-driver-smb

**Comment by andyzhangx** [comment]
already created a repo migration tracking issue here: https://github.com/kubernetes/org/issues/1867
