### ISSUE TITLE
kubedns: Waiting for services and endpoints to be initialized from apiserver...

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubernetes#56006]
kube version: 1.8.3
os version: debian stretch

```
# kubectl get po --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP              NODE
kube-system   calico-etcd-6wgrn                          1/1       Running   0          20m       192.168.5.42    uy05-13
kube-system   calico-kube-controllers-55449f8d88-xff4k   1/1       Running   1          20m       192.168.5.105   uy08-08
kube-system   calico-node-25q7h                          2/2       Running   0          20m       192.168.5.105   uy08-08
kube-system   calico-node-mdt45                          2/2       Running   0          20m       192.168.5.42    uy05-13
kube-system   kube-apiserver-uy05-13                     1/1       Running   0          2m        192.168.5.42    uy05-13
kube-system   kube-controller-manager-uy05-13            1/1       Running   1          35m       192.168.5.42    uy05-13
kube-system   kube-dns-545bc4bfd4-x7hmp                  2/3       Running   23         36m       192.168.4.73    uy08-08
kube-system   kube-proxy-7bkqc                           1/1       Running   0          36m       192.168.5.42    uy05-13
kube-system   kube-proxy-r4nxk                           1/1       Running   0          22m       192.168.5.105   uy08-08
kube-system   kube-scheduler-uy05-13                     1/1       Running   1          36m       192.168.5.42    uy05-13
```
```
# kubectl logs -f kube-dns-545bc4bfd4-x7hmp -n kube-system -c kubedns
I1119 04:37:29.093631       1 dns.go:48] version: 1.14.4-2-g5584e04
I1119 04:37:29.094340       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I1119 04:37:29.094379       1 server.go:113] FLAG: --alsologtostderr="false"
I1119 04:37:29.094386       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I1119 04:37:29.094391       1 server.go:113] FLAG: --config-map=""
I1119 04:37:29.094394       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I1119 04:37:29.094397       1 server.go:113] FLAG: --config-period="10s"
I1119 04:37:29.094402       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I1119 04:37:29.094410       1 server.go:113] FLAG: --dns-port="10053"
I1119 04:37:29.094415       1 server.go:113] FLAG: --domain="cluster.local."
I1119 04:37:29.094422       1 server.go:113] FLAG: --federations=""
I1119 04:37:29.094426       1 server.go:113] FLAG: --healthz-port="8081"
I1119 04:37:29.094429       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I1119 04:37:29.094433       1 server.go:113] FLAG: --kube-master-url=""
I1119 04:37:29.094443       1 server.go:113] FLAG: --kubecfg-file=""
I1119 04:37:29.094446       1 server.go:113] FLAG: --log-backtrace-at=":0"
I1119 04:37:29.094452       1 server.go:113] FLAG: --log-dir=""
I1119 04:37:29.094458       1 server.go:113] FLAG: --log-flush-frequency="5s"
I1119 04:37:29.094461       1 server.go:113] FLAG: --logtostderr="true"
I1119 04:37:29.094464       1 server.go:113] FLAG: --nameservers=""
I1119 04:37:29.094467       1 server.go:113] FLAG: --stderrthreshold="2"
I1119 04:37:29.094470       1 server.go:113] FLAG: --v="2"
I1119 04:37:29.094473       1 server.go:113] FLAG: --version="false"
I1119 04:37:29.094480       1 server.go:113] FLAG: --vmodule=""
I1119 04:37:29.094530       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I1119 04:37:29.094761       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I1119 04:37:29.094771       1 dns.go:147] Starting endpointsController
I1119 04:37:29.094775       1 dns.go:150] Starting serviceController
I1119 04:37:29.094952       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1119 04:37:29.094968       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I1119 04:37:29.594991       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E1119 04:37:30.066141       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
E1119 04:37:30.066166       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
I1119 04:37:30.094969       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:30.595007       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:31.094993       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:31.594999       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:32.094993       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:32.594963       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:33.094997       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:33.594998       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:34.094982       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E1119 04:37:34.130043       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
E1119 04:37:34.130069       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
I1119 04:37:34.594959       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:35.094959       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:35.594950       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:36.094985       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:36.594967       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:37.095005       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E1119 04:37:37.202635       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
E1119 04:37:37.203735       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
I1119 04:37:37.594987       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:38.094999       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:38.594953       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:39.094941       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:39.594995       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1119 04:37:40.095000       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
```

**Comment by hzxuzhonghu** [comment]
@KeithTt  Would you give more details? We can know dns can not access kubernetes service from the log.

**Comment by KeithTt** [comment]
@hzxuzhonghu I was trying to create a HA master cluster, and I found that it was the config issue, thanks.

**Comment by stanfordbangaba** [comment]
@KeithTt Kindly share your solution, facing the same issue here

**Comment by ricklagerweij** [comment]
@KeithTt what was wrong in the configuration?

**Comment by KeithTt** [comment]
@ricklagerweij There is a cert issue, and this lead to kinds of problems, because it can not connect to apiserver...I spend much time looking for it. Hope you lucky....

**Comment by ricklagerweij** [comment]
@KeithTt I solved it yesterday, it was indeed a cert issue. Creating the cert with extensions I specified the pod cidr instead of the service cidr which caused issues for kube-dns (logs of this container specified the issue), recreated it with the service cidr but the container was using its cache so it wasn't instantly solved.

Cheers!

**Comment by rakeshkulkarni6** [comment]
@KeithTt 

Hi I am facing this issue from many days can you please help me to resolve the issue. it would be helpful if you can share me your cluster definition file. please find the response logs from api server.

root@rbcicchcovamw00:/home/cloudinfraadmin# kubectl logs kube-dns-v20-3003781527-c3z2w kubedns -n kube-system
I0103 14:03:07.741791       1 dns.go:48] version: 1.14.4-2-g5584e04
I0103 14:03:07.744761       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0103 14:03:07.744821       1 server.go:113] FLAG: --alsologtostderr="false"
I0103 14:03:07.744845       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0103 14:03:07.744854       1 server.go:113] FLAG: --config-map=""
I0103 14:03:07.744860       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0103 14:03:07.744865       1 server.go:113] FLAG: --config-period="10s"
I0103 14:03:07.744883       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0103 14:03:07.744890       1 server.go:113] FLAG: --dns-port="10053"
I0103 14:03:07.744898       1 server.go:113] FLAG: --domain="cluster.local."
I0103 14:03:07.744916       1 server.go:113] FLAG: --federations=""
I0103 14:03:07.744924       1 server.go:113] FLAG: --healthz-port="8081"
I0103 14:03:07.744940       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0103 14:03:07.744946       1 server.go:113] FLAG: --kube-master-url=""
I0103 14:03:07.744971       1 server.go:113] FLAG: --kubecfg-file=""
I0103 14:03:07.744978       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0103 14:03:07.744987       1 server.go:113] FLAG: --log-dir=""
I0103 14:03:07.744993       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0103 14:03:07.744999       1 server.go:113] FLAG: --logtostderr="true"
I0103 14:03:07.745004       1 server.go:113] FLAG: --nameservers=""
I0103 14:03:07.745009       1 server.go:113] FLAG: --stderrthreshold="2"
I0103 14:03:07.745015       1 server.go:113] FLAG: --v="2"
I0103 14:03:07.745020       1 server.go:113] FLAG: --version="false"
I0103 14:03:07.745028       1 server.go:113] FLAG: --vmodule=""
I0103 14:03:07.745174       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0103 14:03:07.746902       1 server.go:200] Skydns metrics not enabled
I0103 14:03:07.746916       1 dns.go:147] Starting endpointsController
I0103 14:03:07.746924       1 dns.go:150] Starting serviceController
I0103 14:03:07.747568       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0103 14:03:07.747623       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0103 14:03:08.247152       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:08.747147       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:09.247214       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:09.747158       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:10.247146       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:10.747125       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:11.247178       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:11.747220       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:12.247115       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:12.747138       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:13.247134       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:13.747169       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:14.247125       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:14.747119       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:15.247165       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:15.747147       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:16.247114       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:16.747137       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:17.247124       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:17.747127       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0103 14:03:17.748994       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
E0103 14:03:17.749000       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
I0103 14:03:18.247152       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:18.747151       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:19.247163       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:19.747153       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:20.247123       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:20.747134       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:21.247115       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:21.747199       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:22.247146       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:22.747126       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:23.247144       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:23.747141       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:24.247124       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:24.747161       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:25.247156       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:25.747220       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:26.247145       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:26.747153       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:27.247178       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:27.747139       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:28.247276       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:28.747129       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0103 14:03:28.750881       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E0103 14:03:28.751093       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
I0103 14:03:29.247109       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:29.747141       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:30.247105       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:30.747120       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:31.247142       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:31.747143       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:32.247099       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:32.747112       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:33.247122       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:33.747137       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:34.247114       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:34.747183       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:35.247188       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:35.747174       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:36.247130       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:36.747139       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:37.247154       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:37.747143       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:38.247136       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:38.747165       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:39.247184       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:39.747186       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0103 14:03:39.752629       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
E0103 14:03:39.752707       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
I0103 14:03:40.247088       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:40.747109       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:41.247148       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:41.747140       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:42.247142       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:42.747136       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:43.247161       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:43.747350       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:44.247182       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:44.747176       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:45.247160       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:45.747158       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:46.247184       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:46.747152       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:47.247180       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:47.747153       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:48.247095       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:48.747163       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:49.247177       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:49.747138       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:50.247155       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:50.747161       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0103 14:03:50.754363       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E0103 14:03:50.754493       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
I0103 14:03:51.247240       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:51.747221       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:52.247125       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:52.747188       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:53.247168       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:53.747240       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:54.247134       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:54.747198       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:55.247303       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:55.747190       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:56.247160       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:56.747457       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:57.247190       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:57.747218       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:58.247170       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:58.747166       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:59.247174       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:03:59.747172       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:00.247151       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:00.747184       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:01.247137       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:01.747180       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0103 14:04:01.756420       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: net/http: TLS handshake timeout
E0103 14:04:01.756546       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: net/http: TLS handshake timeout
I0103 14:04:02.247159       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:02.747133       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:03.247159       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:03.747159       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:04.247123       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:04.747127       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:05.247164       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:05.747169       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:06.247146       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:06.747157       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0103 14:04:07.247173       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
F0103 14:04:07.747143       1 dns.go:168] Timeout waiting for initialization
root@rbcicchcovamw00:/home/cloudinfraadmin# kubectl get pods -n kube-system
NAME                                      READY     STATUS             RESTARTS   AGE
heapster-342135353-xqz1r                  2/2       Running            0          18h
kube-addon-manager-rbcicchcovamw00        1/1       Running            5          28d
kube-apiserver-rbcicchcovamw00            1/1       Running            5          28d
kube-controller-manager-rbcicchcovamw00   1/1       Running            5          28d
kube-dns-v20-3003781527-c3z2w             2/3       CrashLoopBackOff   4          3m
kube-dns-v20-3003781527-gdvl2             0/3       Terminating        448        18h
kube-dns-v20-3003781527-x8jnj             0/3       Terminating        448        18h
kube-dns-v20-3003781527-zf9dn             2/3       CrashLoopBackOff   4          3m
kube-proxy-0r4vm                          1/1       Running            4          32d
kube-proxy-6xp1q                          1/1       Running            5          32d
kube-proxy-b4288                          1/1       Running            4          32d
kube-scheduler-rbcicchcovamw00            1/1       Running            5          28d
kubernetes-dashboard-3617030121-4fq0l     0/1       CrashLoopBackOff   210        18h
tiller-deploy-2745651589-xzn92            1/1       Running            0          18h
root@rbcicchcovamw00:/home/cloudinfraadmin# ls

**Comment by ricklagerweij** [comment]
@rakeshkulkarni6  at what IP is your apiserver listening, 10.0.0.1 is not the default IP, 10.96.0.1 is.

**Comment by mslebodnik** [comment]
same issue here. wondering why connecting  https://10.96.0.1:443/api/v1/services?resourceVersion=0: 
when API server is listnening on 6443

root# kubectl logs -n kube-system kube-dns-6f4fd4bdf-v88k8 kubedns
E0206 14:20:24.171371       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0206 14:20:24.171878       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout

**Comment by tcheronneau** [comment]
@mslebodnik I've the exact same issue. 
It's trying to connect to port 443 except my API server is 6443 but I can't find where is my error. 
Did you managed to solve it ? 

Thanks.

**Comment by sa-shukla** [comment]
I am also running into same issue. Any resolution on the issue?

**Comment by tcheronneau** [comment]
For me the error was from my side (misconfiguration). 
So it was not really an issue. You should look into your network configuration it was my problem.

**Comment by sa-shukla** [comment]
we have a http_proxy available within the network which possibly is causing issues for me. Any recommendation on the proxy settings?

Do you have any insight into what I should be looking for on the network side?

I saw that API service runs internally on IP 10.96.0.1 . Is this IP pingable and reachable from all the nodes?

**Comment by chaiyuxiao** [comment]
same issue.

[root@localhost ~]# kubectl get po -n=kube-system | grep kube-dns
kube-dns-2425271678-bz097                       2/3       CrashLoopBackOff   5          49m

When I disabled firewalld and reboot system (centos release).

[root@localhost ~]# kubectl get po -n=kube-system | grep kube-dns
kube-dns-2425271678-bz097                       3/3       Running   0          54m

kube-dns is running all the time when the firewalld disalbed

**Comment by Davidrjx** [comment]
@KeithTt @ghost cert config you specified located in snippet?
```
...
apiServer:
  certSANs:
  - ...
  - ...
...
```
