### ISSUE TITLE
A new master can skip auth??

### ISSUE THREAD

**Issue by zhuhesheng** [kubernetes/kubernetes#56012]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> /kind bug

**What happened**:
My Englist is poor.
I have a master node(ip:6443 tls and  localhost:8080,)
when I add a master node, I use a configuration file that was not authenticated,(only 8080),and it can list all nodes!!!!
schedule too
**What you expected to happen**:
**

**How to reproduce it (as minimally and precisely as possible)**:
add a new no ca master node

**Anything else we need to know?**:
no
**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration: 

node 115  ---tls---- master ca

no ca master
::::::::::::::
apiserver
::::::::::::::
KUBE_API_ARGS="--storage-backend=etcd3 --etcd-servers=http://10.29.15.115:2379,http://10.29.15.128:2379,http://10.29.15.129:2379 --insecure-bind-address=0.0.0.0 --insecure-port
=8080  --service-cluster-ip-range=192.168.0.0/16 --service-node-port-range=30000-39999 --admission_control=NamespaceLifecycle,LimitRanger,DefaultStorageClass,ResourceQuota --lo
gtostderr=false --log-dir=/var/log/kubernetes --v=2"
::::::::::::::
controller-manager
::::::::::::::
KUBE_CONTROLLER_MANAGER_ARGS="--master=http://10.29.15.129:8080 --logtostderr=false --log-dir=/var/log/kubernetes --v=2"
::::::::::::::
scheduler
::::::::::::::
KUBE_SCHEDULER_ARGS="--master=http://10.29.15.129:8080 --logtostderr=false --log-dir=/var/log/kubernetes --v=2"
- OS (e.g. from /etc/os-release):
centos 7 
- Kernel (e.g. `uname -a`):
3.10
- Install tools:
binary
- Others:
no

**Comment by liggitt** [comment]
yes, `--insecure-port` surfaces an unsecured port on localhost, and defaults to 8080 for backwards compatibility.

It is recommended that you disable this with `--insecure-port=0`
