### ISSUE TITLE
Broken serialization of escaped ~~quotes~~ characters due to jsoniter

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#56018]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig api-machinery

**What happened**:

While working on https://github.com/kubernetes/kubernetes/pull/55168, roundtrip tests were flakey:

```
roundtrip.go:325: CustomResourceDefinition: v1beta1.CustomResourceDefinition: Spec: v1beta1.CustomResourceDefinitionSpec: Validation: v1beta1.CustomResourceValidation: OpenAPIV3Schema: v1beta1.JSONSchemaProps: AdditionalProperties: readObjectFieldAsBytes: expect : after object field, parsing 13210 ...ties":{"\"... at
```

The error comes from jsoniter here:

https://github.com/kubernetes/kubernetes/blob/27b3681cece5bc4c63e067a1595edbc5bb5964a0/vendor/github.com/json-iterator/go/feature_iter_object.go#L195

Related jsoniter issues:

- https://github.com/json-iterator/go/issues/50
- https://github.com/json-iterator/go/issues/191

Even though both issues appear to be fixed, when I bump jsoninter, I get:

```
roundtrip.go:325: CustomResourceDefinition: v1beta1.CustomResourceDefinition: Spec: v1beta1.CustomResourceDefinitionSpec: Validation: v1beta1.CustomResourceValidation: OpenAPIV3Schema: v1beta1.JSONSchemaProps: AdditionalProperties: readObjectFieldAsBytes: expect : after object field, but found r, error found in #10 byte of ...|ties":{"\"r騸炎oǧ|..., bigger context ...|�內錧嗾qȲ蒅ǧ煠"}}],"patternProperties":{"\"r騸炎oǧrƝś鈟踍":{"id":"羳l聿殦@钆Ł3+��|...
```

**What you expected to happen**:

Serialization tests to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run the roundtrip tests for apiextensions-apiserver in https://github.com/kubernetes/kubernetes/pull/55168.

```
go test -v  k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install
```

**Anything else we need to know?**:

Fwiw this solution - https://github.com/soltysh/origin/pull/8 - works. Not sure if we want to incorporate into kubernetes as of now (?).

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign @thockin @mfojtik

**Comment by thockin** [comment]
Can you craft this as a test case against json-iterator/go?  They have a
suite that exists to compare stdlib parsing and their parsing, and any
place it differs they want to fix it.  It will also force you boil it down
to a trivial example.

Once fixed there, I am happy to re-vendor it.

On Sun, Nov 19, 2017 at 4:01 AM, Nikhita Raghunath <notifications@github.com

**Comment by mfojtik** [comment]
@nikhita https://github.com/soltysh/origin/pull/8 reverts the JSON parser back to stdlib (which also revealed some problems in k8s fuzzer (https://github.com/openshift/origin/pull/17115/commits/8ef5b4106818ed5959a79a277f65a0b057536752#diff-cebb28754bf68601a0cee0fefad51ceeR144).

**Comment by sttts** [comment]
Even after the bump our used `ConfigFastest` "by definition" expects simple strings as object keys. This does not match the stdlib.

I have prepared https://github.com/kubernetes/kubernetes/pull/56055 to fix flakes in roundtrip tests because the go fuzzer fills in newlines and other escape sequences.

**Comment by lavalamp** [comment]
cc @mml

**Comment by nikhita** [comment]
For the record, from the discussion in https://github.com/kubernetes/kubernetes/pull/56055#issuecomment-345789060, `ConfigCompatibleWithStandardLibrary` works after a bump.

**Comment by thockin** [comment]
If we think that is the right answer, doing a bump is pretty easy.  Can we
get a PR with a test case that fails, so we can fix the test case with a
jsoniter bump?

On Thu, Nov 30, 2017 at 1:40 PM, Nikhita Raghunath <notifications@github.com

**Comment by sttts** [comment]
> If we think that is the right answer

Who can answer this?

**Comment by thockin** [comment]
It seems tome to be the safest answer.  I have not characterized the perf
impact or how much we care...

**Comment by thockin** [comment]
Can we run the json-iterator benchmarks against something like a fuzzed
Pod, and see how ConfigCompatible... rates vs ConfigFastest vs literal
stdlib ?
