### ISSUE TITLE
Measure performance/scalability impact of preemption

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#56032]
Our scheduling SLO and associated scalability tests don't involve preemption. We should at least measure the performance impact.

cc/ @bsalamat @shyamjvs 

/kind feature
/sig scheduling
/sig scalability

**Comment by bsalamat** [comment]
ref #59244

**Comment by shyamjvs** [comment]
#59244 seems to be an unrelated failure.

I waited to have at least a couple of failure runs to be able to assert this confidently.
Indeed it seems like the feature has affected the scheduler performance on large clusters (2k-nodes).

I took a look at one of our failed runs, and seems like we got bottlenecked very much by scheduling while saturating the cluster with density pods:

```
I0201 18:32:13.022] Feb  1 18:32:13.021: INFO: Density Pods: 60000 out of 60000 created, 2241 running, 1 pending, 57758 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:32:23.022] Feb  1 18:32:23.021: INFO: Density Pods: 60000 out of 60000 created, 2247 running, 0 pending, 57753 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:32:33.020] Feb  1 18:32:33.020: INFO: Density Pods: 60000 out of 60000 created, 2252 running, 0 pending, 57748 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:32:43.021] Feb  1 18:32:43.020: INFO: Density Pods: 60000 out of 60000 created, 2256 running, 1 pending, 57743 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:32:53.021] Feb  1 18:32:53.021: INFO: Density Pods: 60000 out of 60000 created, 2262 running, 1 pending, 57737 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:33:03.021] Feb  1 18:33:03.020: INFO: Density Pods: 60000 out of 60000 created, 2266 running, 1 pending, 57733 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:33:13.021] Feb  1 18:33:13.020: INFO: Density Pods: 60000 out of 60000 created, 2271 running, 1 pending, 57728 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0201 18:33:23.022] Feb  1 18:33:23.021: INFO: Density Pods: 60000 out of 60000 created, 2276 running, 1 pending, 57723 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
```

This is at a point where are all the pods have been created, but they're blocked on being scheduled (represented by the 'waiting' state). There are roughly 5 pods being scheduled every 10s (it's 2 orders of magnitude slower than before).

I'll revert it for our scalability job, but we should definitely work on improving it's performance. Also, I would be interested to know the algorithm that you're using here.

**Comment by bsalamat** [comment]
I will investigate this issue. We do not expect priority and preemption to cause a significant slow down when cluster has enough capacity to run pods. Preemption logic kicks in when a pod cannot be scheduled because it cannot fit.

**Comment by bsalamat** [comment]
Today, I found some time to look into the problem. It was not preemption itself that was slowing us down, it was getting the list of "nominated Pods" from the scheduling queue which was the problem. ActiveQ of scheduling queue does not have a hash table to track the pods nominated for nodes and getting the list causes an O(n) scan. When there are many pods in the scheduling queue, this O(n) scanning slow us down. I am sending a PR soon to address the issue.

**Comment by bsalamat** [comment]
@shyamjvs My recent PR for improving performance of the new scheduling queue is merged. My local benchmarking shows that performance of the new queue after this PR is on par with the FIFO (old mechanism). Could you please re-enable priority and preemption for the scalability tests? Thanks!

**Comment by shyamjvs** [comment]
Sure @bsalamat - I'll send out a PR enabling it.

**Comment by shyamjvs** [comment]
@bsalamat Seems like your change did help a bit (~70 pods scheduled every 10s, compared to ~5 before):

```
I0217 13:34:07.248] Feb 17 13:34:07.248: INFO: Density Pods: 60000 out of 60000 created, 4763 running, 7 pending, 55230 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0217 13:34:17.249] Feb 17 13:34:17.249: INFO: Density Pods: 60000 out of 60000 created, 4807 running, 34 pending, 55159 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0217 13:34:27.251] Feb 17 13:34:27.250: INFO: Density Pods: 60000 out of 60000 created, 4907 running, 0 pending, 55093 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0217 13:34:37.249] Feb 17 13:34:37.248: INFO: Density Pods: 60000 out of 60000 created, 4984 running, 8 pending, 55008 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0217 13:34:47.247] Feb 17 13:34:47.247: INFO: Density Pods: 60000 out of 60000 created, 5057 running, 18 pending, 54925 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0217 13:34:57.245] Feb 17 13:34:57.245: INFO: Density Pods: 60000 out of 60000 created, 5139 running, 8 pending, 54853 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
```

(source: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/58/build-log.txt)

But it's still quite slow from what it was without preemption. I'll re-revert the change back to make the tests green.

**Comment by shyamjvs** [comment]
You can also find pod-startup latency %iles [here](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/58/artifacts/PodStartupLatency_density_2018-02-17T16:25:13Z.json) and see that the 99th %ile is 5 mins (which is way above our 5s SLO).

**Comment by bsalamat** [comment]
@shyamjvs Sorry for the trouble. I was trying our [scheduler performance benchmarks](https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf) and they seemed to have similar results with and without enabling preemption. It looks like the tests that are slow are a different set of tests. Do you know how I can run them locally/in my dev cluster?

**Comment by shyamjvs** [comment]
>Sorry for the trouble.

No problem :)

> I was trying our scheduler performance benchmarks and they seemed to have similar results with and without enabling preemption.

I'm a bit skeptic whether those benchmarks give a very reliable signal, as the difference in results might not actually be perceived due to their variance? Also FWIW, those benchmarks are integration tests running just the scheduler and etcd iiuc (not sure if that should affect anything though).

> It looks like the tests that are slow are a different set of tests.

Yes, the one I'm referring to is our 'real cluster' density test (where we're creating many many pods quickly to saturate the cluster).

> Do you know how I can run them locally/in my dev cluster?

To run both our load and density test, use `--ginkgo.focus=\[Feature:Performance\]` while running the e2e tests. To run just the density test (to save time), use `--ginkgo.focus=\[sig\-scalability\]\sDensity\s\[Feature\:Performance\]\sshould\sallow\sstarting\s30\spods\sper\snode\susing\s\{\sReplicationController\}\swith\s0\ssecrets\,\s0\sconfigmaps\sand\s0\sdaemons$`

Btw - I plan to add an optional-presubmit job for 2k-node performance soon. Once that's done, you should be able to kick those tests against your PR with a single command.

**Comment by redbaron** [comment]
Is it possible to benchmark scheduler performance locally? I'd like to evaluate some ideas, before submitting full PR

**Comment by shyamjvs** [comment]
@redbaron: Yes, you should be able to run the benchmarks locally (they're nothing but integration tests) by running:

```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_ARGS="-run='XXX' -bench=. -benchmem
```

**Comment by bsalamat** [comment]
> I plan to add an optional-presubmit job for 2k-node performance soon. Once that's done, you should be able to kick those tests against your PR with a single command.

@shyamjvs did you find the chance to add those presubmit tests?

**Comment by shyamjvs** [comment]
I finally found some time today to add a scalability presubmit suite (ref: https://github.com/kubernetes/test-infra/pull/7168) :)
Once that's in, you should be able to trigger performance tests against your PR using:

- `/test pull-kubernetes-e2e-gce-100-performance` (for 100-node)
- `/test pull-kubernetes-e2e-gce-big-performance` (for 500-node)
- `/test pull-kubernetes-e2e-gce-large-performance` (for 2000-node)

Some things to note though:
- The last one is a bit time-consuming and costly, so we should try to trigger it sparingly
- We're currently suffering from a scalability regression at HEAD (ref: https://github.com/kubernetes/kubernetes/issues/60589) which may affect your results (fix is out and hopefully goes in soon)

**Comment by shyamjvs** [comment]
@bsalamat That PR is now merged and those pre-submits should be available. Please free to try them and let me know if you face some issues.

**Comment by bsalamat** [comment]
@shyamjvs I tried the density test with 30 pods per node that you suggested above. I let the test run until it fails while priority and preemption was enabled in my cluster which had 3 nodes. The test ran for 28 times successfully and then it failed. While running, I was checking the scheduler logs. The 90 pods created in the test were being scheduled in several seconds. And eventually when the test failed, the failure didn't have anything to do with the scheduler. It was the cluster that was no longer ready. The failure seemed to be related to fluentd being killed and could no longer run on the master node. I saw lots of error messages like the following:

Mar  6 20:59:49.574: INFO: At 2018-03-06 20:59:42 -0800 PST - event for fluentd-gcp-v3.0.0-vdzp6: {kubelet e2e-test-bsalamat-master} UnexpectedAdmissionError: Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: cpu, q: 82), ]

BTW, the "preemption" message that you see in the log has nothing to do with the scheduler preemption. It is a message by kubelet eviction logic indicating that there is no pod to evict.

So, at this point and given the recent flakiness of the scalability tests, are we certain that the failures that we used to see after #59671, were related to the scheduler performance?

And, thanks for adding the tests. I will try runing them and see how it goes.

**Comment by shyamjvs** [comment]
Not sure why the fluentd error happened, but it indeed seems to me like it may be unrelated to scheduler (or maybe even scalability at that small scale). However:

> So, at this point and given the recent flakiness of the scalability tests, are we certain that the failures that we used to see after #59671, were related to the scheduler performance?

Could you confirm which issue you're referring to by 'scheduler performance'? If you mean test runs we ran with preemption enabled, I believe it is indeed related to scheduler performance for the reasons I explained in https://github.com/kubernetes/kubernetes/issues/56032#issuecomment-363823222 and https://github.com/kubernetes/kubernetes/issues/56032#issuecomment-366725927. And:

- Re flakes: Yes, we do see them from time to time in our scale tests - but those are generally due to lack of robustness in testing framework (e.g not retrying in case of failed API calls, etc) and we're in the effort of de-flaking. However for the failures we saw with pre-emption enabled - I didn't find any connection to flakes. The effect actually was clearly seen in the scheduler throughput (as I explained in those comments).

- Re regression: That's a good point - we were probably suffering from a regression around that time. But the effect on scheduler still seems likely related to pre-emption as it seemed to mostly recover after disabling it back. That said, as you say, it might be safest to test this while we're free of any regressions :)

**Comment by bsalamat** [comment]
Thanks, @shyamjvs. Unfortunately, I don't have enough quota to bring up a very large k8s cluster in GCE and try the test, but I will try to create a dummy PR and try your recently added CI tests.

**Comment by dims** [comment]
@bsalamat @shyamjvs the fluentd-gcp problem is being looked at here - https://github.com/kubernetes/kubernetes/issues/60763#issuecomment-372809909

**Comment by bsalamat** [comment]
@shyamjvs I created #61070 and ran `pull-kubernetes-e2e-gce-100-performance` a couple of times. It once failed and once succeeded. The one time that it failed, it was a timeout, but the timeout didn't seem to be related to performance. All the pods had been scheduled successfully and quickly, but one of the pods had never scheduled. This issue may not necessarily be performance related. Given that we have a new scheduling queue when priority and preemption is enabled, there may be a bug in the queue implementation. I am going to try larger tests and will investigate the issue.

**Comment by shyamjvs** [comment]
Bobby - Note that the project where these presubmits run has almost it's
entire quota busy in debugging a serious scalability regression atm (issue
#60589). So running anything larger than 100-node (or even that) might
timeout waiting to get enough VMs.

**Comment by shyamjvs** [comment]
Sorry for this inconvenience - hopefully we resolve that soon.

**Comment by bsalamat** [comment]
@shyamjvs 
The scalability tests that you added to presubmit tests often fail without enabling preemption. The smallest one (`pull-kubernetes-e2e-gce-100-performance`) runs by default and fails often. Could you please take a look?

**Comment by shyamjvs** [comment]
> The smallest one (pull-kubernetes-e2e-gce-100-performance) runs by default

Yes, I just turned it on yesterday to run by default on all PRs. However, note that I've made it non-blocking until the job stabilizes.

> and fails often. Could you please take a look?

The reason for those failures is understood and I've sent fixes for it (https://github.com/kubernetes/test-infra/pull/7555, https://github.com/kubernetes/kubernetes/pull/62172). Will try to make it green soonish.

**Comment by vhosakot** [comment]
I'm scaling pods in k8s and see a lot of pods in `UnexpectedAdmissionError` state too.

```
test-rs-ue80jl-0-zmf2n                  0/1       UnexpectedAdmissionError   0          51s
test-rs-ue80jl-0-zpr9s                  0/1       UnexpectedAdmissionError   0          24s

$ kubectl get pods | grep UnexpectedAdmissionError | wc -l
145
```
Would be nice if pods in `UnexpectedAdmissionError` state are retried gracefully so that they come up.

Related: https://github.com/kubernetes/kubernetes/issues/70010
