### ISSUE TITLE
too hard to install k8s in china

### ISSUE THREAD

**Issue by duansheli** [kubernetes/kubernetes#56038]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
in china
it's difficult to install k8s 
we have great greatfire

we can not reach the site
http://packages.cloud.google.com/yum/repos
gcr.io

**What you expected to happen**:
get install k8s successful

**How to reproduce it (as minimally and precisely as possible)**:

we need yum repo mirror
and gcr.io images

**Anything else we need to know?**:
For Chinese developers
It's too hard to install k8s without VPN

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fluffywar** [comment]
@team/huawei

**Comment by ShualLiu** [comment]
@fluffywar It's a good idea to build a ss server for yourself... I bought a remote server to set the proxy. Then you could use such as Prioxy to set global agent.
 `God bless you.`

**Comment by Maslow** [comment]
+1

Just push the docker images used by kubernetes to docker hub (hub.docker.com). Anyone all of world can access it. In the meanwhile, the additional advantage of it is that we can pull these images from docker hub fastly through a local registry mirror provider which like Alibaba's docker images registry mirror in China.

**Comment by aries-zhang** [comment]
I raised an issue in the doc repo https://github.com/kubernetes/website/issues/6710 , but this problem is closed because it belongs to this repo.

Other than docker images, google's apt source is also blocked, so is it possible to use apt's official sources as an alternative?

**Comment by aries-zhang** [comment]
Anyone?

**Comment by Maslow** [comment]
who u r

**Comment by cao7113** [comment]
haha, so hard to develop in china

**Comment by jasonhubs** [comment]
Too hard too study kubernetes,too hard too participate in google open source products in China! Everythig  about google.

**Comment by wu0407** [comment]
gco.io images mirror on aliyun https://dev.aliyun.com/list.html?namePrefix=google-containers

**Comment by wu0407** [comment]
https://packages.cloud.google.com mirror on https://mirrors.aliyun.com/kubernetes

**Comment by maguowei** [comment]
thanks @wu0407   https://github.com/maguowei/kubernetes-for-china

**Comment by RainingNight** [comment]
Any official news?

**Comment by originsmike** [comment]
This recently got much easier. Now, you can get `kubeadm init` to succeed inside China...in 10 minutes.

@maguowei has a good start for installing kubeadm and related tools from mirrors.aliyun.com's repo.

As far as I know, kubelet still needs a bit of manual configuration:

```bash
# Add this to the ExecStart config in /etc/systemd/system/kubelet.service
--pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause-amd64:3.1
```

Then, you can modify kubeadm's imageRepository setting to direct it to download container images from Aliyun's mirror:

```bash
kubeadm config print-default > kubeadm.conf    # this only works in kubeadm v1.11+
sed -i "s/imageRepository: .*/imageRepository: registry.cn-hangzhou.aliyuncs.com\/google_containers/g" kubeadm.conf
# Change podSubnet and kubernetesVersion to suit your needs
kubeadm init --config kubeadm.conf
```

I just did this on an Aliyun VM. Still have yet to set up a network though.

**Comment by originsmike** [comment]
I completed the networking part and wrote a more-or-less complete guide: https://github.com/kaiterra/misc/blob/master/kubernetes-china-aliyun.md

**Comment by dims** [comment]
Looks like the url moved a bit - https://github.com/kaiterra/misc/tree/master/kubernetes-china-aliyun

**Comment by dims** [comment]
@feiskyer mentioned - Azure manages a mirror of kubernetes packages, including helm charts - See http://mirror.azure.cn/kubernetes/

**Comment by originsmike** [comment]
@dims thanks!

**Comment by sfitts** [comment]
We're running into this as well (attempting to support our customers in China).  FWIW the Aliyun mirrors are great, but they only work from inside of AliCloud.  The Azure mirror doesn't seem to include a container registry.  So I guess right now the answer is a per-environment mirror for "gcr.io"?  Does anyone know if China Unicom maintains a mirror for their cloud?

**Comment by dims** [comment]
long-term-issue (note-to-self)

**Comment by zerda** [comment]
@sfitts You can use the Aliyun mirrors and container registry outside of AilCloud.

Here are some quick tips.
- https://mirrors.aliyun.com/kubernetes/apt/ for https://apt.kubernetes.io/
- https://mirrors.aliyun.com/docker-ce/linux/ubuntu for https://download.docker.com/linux/ubuntu
- registry.aliyuncs.com/google_containers for k8s.gcr.io
- docker registry mirrors can be https://registry.docker-cn.com

I have written a step by step tutorial in Chinese, hope this can help someone. https://kubethink.com/posts/create-an-on-premises-cluster-in-china-v1-12/

**Comment by RainingNight** [comment]
Why not support `imageRepository` argument in Kubeadm init and join?

**Comment by MicroIdea** [comment]
@zerda thanks for your tips.
I'm curious about who maintains this registry: registry.aliyuncs.com/google_containers, is it official by Aliyun?

**Comment by MicroIdea** [comment]
> @zerda thanks for your tips.
> I'm curious about who maintains this registry: registry.aliyuncs.com/google_containers, is it official by Aliyun?

Found this: https://github.com/AliyunContainerService/sync-repo, so I think it's maintained by Aliyun container service.

**Comment by zerda** [comment]
> Why not support `imageRepository` argument in Kubeadm init and join?

In 1.13, kubeadm will support the `--image-repository` flag for customizing what registry to pull images from. #71135

**Comment by NeverMore93** [comment]
> @fluffywar It's a good idea to build a ss server for yourself... I bought a remote server to set the proxy. Then you could use such as Prioxy to set global agent.
> `God bless you.`

if I use proxy,how can I add cluster CIDR to no proxy

**Comment by kuchaguangjie** [comment]
the CCP make programmer's life much harder in China.

**Comment by zenglian** [comment]
> > Why not support `imageRepository` argument in Kubeadm init and join?
> 
> In 1.13, kubeadm will support the `--image-repository` flag for customizing what registry to pull images from. #71135

--image-repository = ？

**Comment by uzxmx** [comment]
Here's the summary of gcr mirror status in China:

* `gcr.azk8s.cn` not working (for private use)
* `gcr.mirrors.ustc.edu.cn` not working (sometimes)
* Aliyun mirror needs to login before pulling

For me, currently the best way is to access gcr images from offical docker registry.  For anyone who's interested in using official docker registry or a mirror like `docker.mirrors.ustc.edu.cn` to access gcr images, you can find useful information [here](https://github.com/uzxmx/dockerhub-build-trigger).

**Comment by dims** [comment]
cc @bartsmykla

**Comment by john-yick** [comment]
Just to add I am working on a one-click installation from within China. I have the master-node script mostly setup now. It uses the aliyun CDN for installation and takes ~2-3 mins from a fresh install of CentOs with docker pre-installed to have K8 running.[k8-setup]( https://github.com/john-yick/k8-setup) still learning K8 but it does seem much harder to get things up and running within China, compared from outside.

**Comment by uzxmx** [comment]
@john-yick In a bare-metal or development machine, I highly recommend using [kubespray](https://github.com/kubernetes-sigs/kubespray). You can configure to use mirrors for images which are slow to download in China. Also if you like using terminal to work, I recommend using vagrant + kubespray to do some experiments of k8s cluster. I made [my own k8s box](https://github.com/uzxmx/boxes/tree/master/k8sbox) which I can use to setup a cluster with several vms. For a new cluster, I just run `box create`, and after that, only `vagrant up`, `vagrant ssh` and `vagrant halt` are needed.

**Comment by yogeek** [comment]
I want to deploy a k8s cluster in AWS China with kubeadm and found very useful information in this discussion but it seems that some images are still missing.
Using this :
```
kubeadm config images pull --kubernetes-version=v1.17.6 --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
```
most k8s images are pulled but not all.
For example :
`registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.17.6` is not found.

Do you know where I can raise an issue for this please ?

**Comment by john-yick** [comment]
@yogeek Give this a try [https://github.com/gotok8s/gotok8s](https://github.com/gotok8s/gotok8s) I managed to setup a 3 node k8 setup quickly using the scripts here.

**Comment by yogeek** [comment]
@john-yick thanks for your help. However, the registry you proposed does not contain the v1.17.6 images neither...

Result with your gotok8s repo : 1.17.6 and 1.17.5 are missing, 1.17.4 is ok
```
$ docker pull gotok8s/kube-controller-manager:v1.17.6
Error response from daemon: manifest for gotok8s/kube-controller-manager:v1.17.6 not found
root@ip-10-1-1-28:~# docker pull gotok8s/kube-controller-manager:v1.17.5
Error response from daemon: manifest for gotok8s/kube-controller-manager:v1.17.5 not found

$ docker pull gotok8s/kube-controller-manager:v1.17.4
v1.17.4: Pulling from gotok8s/kube-controller-manager
597de8ba0c30: Pull complete
2a738a57dbcd: Pull complete
Digest: sha256:44ef7d1e0bea072379d7a5d49d3051632ffa25558319e34431eb8719696ca2d1
Status: Downloaded newer image for gotok8s/kube-controller-manager:v1.17.4
```

Result with aliyun mirror repo : 1.17.6 is missing, 1.17.5 is ok
```
$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.17.6
Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.17.6 not found

$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.17.5
v1.17.5: Pulling from google_containers/kube-controller-manager
597de8ba0c30: Pull complete
e7af35b1a1d5: Pull complete
Digest: sha256:3278ed92fcabc7a922f76d3caab42ee8d2ad47cf6470a89bfcce203dca6599c5
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.17.5
```

I would rather use the aliyun mirror if possible (closer) but I do not understand why all the images are not present...

Can someone explain how the replication to the mirrors is done please ?
Why some images are missing and others not for the same K8S version ?

**Comment by john-yick** [comment]
@yogeek So The way I ran it is using a shell script that is here [https://github.com/john-yick/k8-setup/blob/master/setup.sh](https://github.com/john-yick/k8-setup/blob/master/setup.sh) I haven't tested with the latest version of K8 but it could be that the CI is just mirroring/caching the image which is why it is unavailable.

**Comment by uzxmx** [comment]
@yogeek Don't know how aliyun mirror works, but AWS China should be find to pull images from dockerhub, I'm also using AWS China.

**Comment by shoce** [comment]
For those who is looking for a way to install k0s in china: use airgap install, worked perfectly for me. Just need to put  a bundle file into `/var/lib/k0s/images/` and run `k0s install ...`, docs here https://github.com/k0sproject/k0s/blob/main/docs/airgap-install.md

**Comment by dai-mk** [comment]
> @sfitts You can use the Aliyun mirrors and container registry outside of AilCloud.
> 
> Here are some quick tips.
> 
>     * https://mirrors.aliyun.com/kubernetes/apt/ for https://apt.kubernetes.io/
> 
>     * https://mirrors.aliyun.com/docker-ce/linux/ubuntu for https://download.docker.com/linux/ubuntu
> 
>     * registry.aliyuncs.com/google_containers for k8s.gcr.io
> 
>     * docker registry mirrors can be https://registry.docker-cn.com
> 
> 
> I have written a step by step tutorial in Chinese, hope this can help someone. https://kubethink.com/posts/create-an-on-premises-cluster-in-china-v1-12/

Just to add, for AWS is also a mirror at https://gallery.ecr.aws/

**Comment by dsadsjd** [comment]
dsa1

**Comment by dsadsjd** [comment]
but now install dashboard so difficult, Kubernetes officials will not manage this issue
