### ISSUE TITLE
Test failing with [discovery error for unexpected group: schema.GroupVersion{Group:"metrics.k8s.io", Version:"v1beta1"}]

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56044]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/27 failed with:
```
STEP: Destroying namespace "e2e-tests-pod-disks-mp8xp" for this suite.
Nov 14 08:44:17.673: INFO: discovery error for unexpected group: schema.GroupVersion{Group:"metrics.k8s.io", Version:"v1beta1"}
Nov 14 08:44:17.673: INFO: Couldn't delete ns: "e2e-tests-pod-disks-mp8xp": unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server could not find the requested resource (&discovery.ErrGroupDiscoveryFailed{Groups:map[schema.GroupVersion]error{schema.GroupVersion{Group:"metrics.k8s.io", Version:"v1beta1"}:(*errors.StatusError)(0xc4202bdef0)}})
```

Dear @kubernetes/sig-api-machinery-bugs can you please help figure out what this means?
/priority failing-test

Umbrella issue - #55194

**Comment by stewart-yu** [comment]
i will help fix it

**Comment by porridge** [comment]
/priority critical-urgent
this blocks #55194

**Comment by lavalamp** [comment]
cc @Random-Liu

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/pull/55764 looks like fixed this. 

now it's failing for other reasons, like:
W1128 22:06:27.727] ERROR: (gcloud.beta.compute.instances.create) Could not fetch resource:
W1128 22:06:27.727]  - The zone 'projects/kubernetes-scale/zones/us-east1-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.

**Comment by porridge** [comment]
If you think it's fixed, let's close this one.
/close
We'll reopen if it reappears.
