### ISSUE TITLE
Test "[sig-storage] Pod Disks schedule a pod w/ RW PD(s) mounted to 1 or more containers, write to PD, verify content, delete pod, and repeat in rapid succession [Slow] using 1 containers and 2 PDs" sometimes fails at large scale

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56041]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

This test failed in the 5000 node test: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/30

Perhaps this is the same as https://github.com/kubernetes/kubernetes/issues/30689, I have not investigated.

@kubernetes/sig-storage-bugs 
/priority failing-test

**Comment by porridge** [comment]
Umbrella issue - #55194

**Comment by jeffvance** [comment]
looking into this...

**Comment by msau42** [comment]
This occasionally flakes for non-scale suites too:
https://k8s-testgrid.appspot.com/sig-storage#gci-gce-slow

**Comment by jeffvance** [comment]
[pd.go L269](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/pd.go#L269) --
[testPDPod()](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/pd.go#L514) which instantiates a *v1.Pod and 2 small slices. The error below is repeated for several pages:
```
ov 16 14:20:19.249: INFO: Get container metadata-proxy-v0.1-2nd44/prometheus-to-sd-exporter usage on node gce-scale-cluster-master. CPUUsageInCores: 0, MemoryUsageInBytes: 12201984, MemoryWorkingSetInBytes: 12201984
Nov 16 14:20:19.249: INFO: Get container etcd-server-events-gce-scale-cluster-master/etcd-container usage on node gce-scale-cluster-master. CPUUsageInCores: 0.171440754, MemoryUsageInBytes: 1336213504, MemoryWorkingSetInBytes: 1204805632
Nov 16 14:20:19.249: INFO: Get container kube-apiserver-gce-scale-cluster-master/kube-apiserver usage on node gce-scale-cluster-master. CPUUsageInCores: 10.521037138, 
... 
```
until:
```
Nov 16 14:34:20.104: INFO: Get container metadata-proxy-v0.1-2nd44/metadata-proxy usage on node gce-scale-cluster-master. CPUUsageInCores: 0.000203785, MemoryUsageInBytes: 24645632, MemoryWorkingSetInBytes: 24645632
Nov 16 14:34:27.684: INFO: Unexpected error occurred: timed out waiting for the condition
```
Perhaps an OOM error?

**Comment by jeffvance** [comment]
@msau42 The flake you show above also fails on the same pod Create() after creating the 2 pds.

**Comment by porridge** [comment]
/priority critical-urgent
this blocks #55194

**Comment by msau42** [comment]
@jeffvance the event you pointed out looks suspicious and could explain why the pod never came up:
```
I1116 14:35:09.356] Nov 16 14:34:50.810: INFO: At 2017-11-16 14:19:28 +0000 UTC - event for pd-test-2755c8c7-cad9-11e7-9c22-0242ac110003: {attachdetach-controller } FailedMount: AttachVolume.Attach failed for volume "testpd1" : GCE persistent disk not found: diskName="gce-scale-cluster-74ae69c4-cad7-11e7-9c22-0242ac110003" zone="us-east1-a"
```

**Comment by jeffvance** [comment]
@msau42 do you think this is a flaky test (which could be due to a sometimes flaky test env) or a real bug?

**Comment by msau42** [comment]
The names of the PDs created, and the name of PD that the pod is trying to attach is not matching up:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/12210/build-log.txt
```
I1121 10:05:31.773] [1mSTEP[0m: creating 2 PD(s)
I1121 10:05:31.774] Nov 21 09:49:50.385: INFO: Successfully created a new PD: "bootstrap-e2e-4f0038aa-cea1-11e7-8afa-0a580a3c1fe3".
I1121 10:05:31.774] Nov 21 09:49:53.949: INFO: Successfully created a new PD: "bootstrap-e2e-511ad1a5-cea1-11e7-8afa-0a580a3c1fe3".

I1121 10:05:31.779] Nov 21 10:05:12.835: INFO: At 2017-11-21 09:49:54 +0000 UTC - event for pd-test-533a996f-cea1-11e7-8afa-0a580a3c1fe3: {attachdetach-controller } FailedMount: AttachVolume.Attach failed for volume "testpd1" : GCE persistent disk not found: diskName="bootstrap-e2e-efb9305b-cea0-11e7-8afa-0a580a3c1fe3" zone="europe-west1-c"
```

**Comment by msau42** [comment]
I think it's a bug in the test.

My suspicion is the `diskNames` slice.  It is not cleaned up in between tests, so you will be using the disk names of the previous test in the 2nd test.

**Comment by jeffvance** [comment]
@msau42 Thanks. I'll investigate.
