### ISSUE TITLE
AfterSuite failures in gce-(large/scale)-correctness tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#56058]
I'm seeing the jobs go through fine, but failing during AfterSuite action. E.g:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/15
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/32

From the [build-log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/15/build-log.txt) of the first one, I'm seeing the following:

```
I1118 06:40:42.351] [91m[1m[AfterSuite] AfterSuite [0m
I1118 06:40:42.351] [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:254[0m
I1118 06:40:42.351] 
I1118 06:40:42.351]   [91m[1mTest Panicked[0m
I1118 06:40:42.351]   [91mclose of closed channel[0m
I1118 06:40:42.351]   /usr/local/go/src/runtime/panic.go:491
I1118 06:40:42.352] 
I1118 06:40:42.352]   [91mFull Stack Trace[0m
I1118 06:40:42.352]   	/usr/local/go/src/runtime/panic.go:491 +0x283
I1118 06:40:42.352]   k8s.io/kubernetes/test/e2e/framework.(*containerResourceGatherer).StopAndSummarize(0xc420d06690, 0xc426e97290, 0x3, 0x3, 0xc4210c0930, 0x0, 0x0, 0x0)
I1118 06:40:42.352]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:292 +0x47
I1118 06:40:42.352]   k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc42118a7e0)
I1118 06:40:42.352]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:324 +0xbc1
...
```

The panic suggests that it was attempted to close a closed channel, more specifically it seems to be the `stopCh` of the resource-gatherer from the stack-trace:

https://github.com/kubernetes/kubernetes/blob/2aaab817de5c90340cf94913df166f389d8d6aca/test/e2e/framework/resource_usage_gatherer.go#L291-L293

cc @kubernetes/sig-scalability-misc @porridge

**Comment by shyamjvs** [comment]
@porridge Could you take a look into this?

**Comment by porridge** [comment]
I wonder whether it's related to https://github.com/kubernetes/kubernetes/issues/56046 or https://github.com/kubernetes/kubernetes/issues/56047

**Comment by shyamjvs** [comment]
Yeah.. this seems like the same one as #56047 (however slightly demystified here :).

So on slightly digging up a bit, it seems like this StopAndSummarize() function is called on the resourceGatherer after each e2e tests.
And these correctness e2e tests are run with some parallelism (25 iirc) on ginkgo - which means that this channel was possibly tried to be closed by an e2e while the other one was still inside the StopAndSummarize() function.

**Comment by shyamjvs** [comment]
/assign
I'll also try taking a look into this, maybe later in the day.

**Comment by porridge** [comment]
Umbrella issue - #55194

**Comment by porridge** [comment]
/priority critical-urgent
this blocks #55194

**Comment by porridge** [comment]
Regarding:

> And these correctness e2e tests are run with some parallelism (25 iirc) on ginkgo - which means that this channel was possibly tried to be closed by an e2e while the other one was still inside the StopAndSummarize() function.


I was under the impression that the parallelism is achieved by running multiple separate ginkgo processes.

**Comment by porridge** [comment]
The only place where `StopAndSummarize` is called is with `AddonResourceConstraints` as the second argument. And AFAICT in `-correctness` tests `AddonResourceConstraints` is guaranteed to be empty (since the only place where it's set to a non-empty value is in `scalability/density.go` which does not run as part of `-correctness`).

The code which calls `StopAndSummarize` was relatively recently touched by @jiayingz so he/she may want to chime in.

**Comment by porridge** [comment]
Actually @jiayingz's change is probably unrelated.

The more likely culprit (judging by timing and scope) is #55525 by @miaoyq 
/cc @janetkuo and @caesarxuchao who discussed the changes to AfterEach in that PR.

From what I gathered so far, in some cases AfterEach runs more than once now, panicking as soon as it reaches `StopAndSummarize`.

**Comment by MrHohn** [comment]
FYI a similar test panic issue was fixed by https://github.com/kubernetes/kubernetes/pull/56128. Ref https://github.com/kubernetes/kubernetes/issues/56089#issuecomment-345912419. Not sure if this is the same.

**Comment by porridge** [comment]
It could well be the same, or something very similar elsewhere.
This one [failed again](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/33) on code before your PR was merged. Another -correctness test won't run soon, but I'll try to do some digging to try and figure out if it was the same duplicate call.

**Comment by porridge** [comment]
I cannot say it with 100% certainty, but I think  #56128 should have fixed this one too.
The reason we fail in `containerResourceGatherer.StopAndSummarize` (which is invoked earlier by `AfterEach`) rather than `framework.AllNodesReady` is most likely that resource gathering is not enabled for most jobs, but is enabled for scalability jobs.
/close

**Comment by porridge** [comment]
(BTW I did check that all of the affected scalability jobs did run the ingress test which had the duplicate AfterEach call).

**Comment by shyamjvs** [comment]
Thanks for looking into this - let's keep a watch on today's run of 2k-node correctness.
