### ISSUE TITLE
L7 LB controller using too much CPU in the 5k-node density test

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56051]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

@kubernetes/sig-network-bugs 
@kubernetes/sig-scalability-bugs 
/priority failing-test

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/65 failed with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135
Expected error:
    <*errors.errorString | 0xc43b4a73d0>: {
        s: "Container l7-lb-controller-v0.9.7-gce-scale-cluster-master/l7-lb-controller is using 0.704569649/0.6998 CPU",
    }
    Container l7-lb-controller-v0.9.7-gce-scale-cluster-master/l7-lb-controller is using 0.704569649/0.6998 CPU
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:365
```

Attached graph shows that it's not a huge increase from normal usage.
Dear SIG networking, is this expected? Should we just bump the limit?
![l7](https://user-images.githubusercontent.com/489420/33017724-abf3a312-cdf3-11e7-967c-eff70470af4c.png)

Please note this is in a release-blocking job.

**Comment by porridge** [comment]
Umbrella bug: https://github.com/kubernetes/kubernetes/issues/56052

**Comment by shyamjvs** [comment]
We were seeing a similar issue for memory a while ago (https://github.com/kubernetes/kubernetes/issues/54135) for l7-lb-controller.
