### ISSUE TITLE
[job failure] gce-scale-performance

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56052]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

This is an umbrella bug for https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/ problems.

@kubernetes/sig-scalability-bugs 
/priority test-failure

**Comment by spiffxp** [comment]
Tracking against v1.9.0-beta.1 (https://github.com/kubernetes/sig-release/issues/34)

**Comment by spiffxp** [comment]
I'm adding this to the milestone and renaming to match the other job failure issues I'm using for release-master-blocking jobs, if you'd rather I open a separate issue let me know

**Comment by spiffxp** [comment]
/priority critical-urgent
/priority failing-test
/status approved-for-milestone
FYI @kubernetes/sig-scalability-test-failures

**Comment by porridge** [comment]
ACK. In progress.
No ETA.

**Comment by porridge** [comment]
ACK. In progress. No ETA.

**Comment by porridge** [comment]
ACK. In progress: causes of previous failures were fixed, it's now suffering from [prow-related test-infra instability](https://github.com/kubernetes/test-infra/issues/5700) after it has been moved from jenkins.
ETA: 02/12/2017 (when the next run should complete)
Risks: if causes https://github.com/kubernetes/test-infra/issues/5700 is unfixed, the job can as last resort be moved back to jenkins

**Comment by spiffxp** [comment]
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by spiffxp** [comment]
/status in-progress
I've witness @porridge and @shyamjvs keeping watch over this job and its failures

We have a green run as of Dec 1st https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/74

Leaving open to see if the trend continues

**Comment by porridge** [comment]
We have 2 green runs in a row now, for the first time since 1st half of November. I think we can tentatively declare a success and close this issue.

**Comment by spiffxp** [comment]
/close
I'm inclined to agree.  For the record, those two green runs are:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/74
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/75

**Comment by spiffxp** [comment]
/reopen
Reopening because: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/77
```
Error creating replication controller: 
Post https://35.196.238.128/api/v1/namespaces/e2e-tests-load-30-nodepods-2-hq5kg/replicationcontrollers: 
read tcp 10.60.247.51:51014->35.196.238.128:443: 
read:
connection reset by peer; some request body already written
```

I don't think this is a performance regression but I'd like to keep track of ongoing failures of this job in the context of v1.9.0 (https://github.com/kubernetes/sig-release/issues/40)

**Comment by porridge** [comment]
FTR, cause for failure of 77 is tracked in the issue linked from its
gubernator page.

**Comment by porridge** [comment]
The cause for last 2 failures was #55860, sounds like it should be in the
milestone as well.

**Comment by enisoc** [comment]
Our latest report from sig-scalability is that these test issues are due to flakiness and are not release-blockers.

I'm removing the v1.9 milestone. Let me know if you have any concerns.
