### ISSUE TITLE
kube-proxy/iptables commands should use the wait ("-w") param

### ISSUE THREAD

**Issue by fvigotti** [kubernetes/kubernetes#56056]
/kind bug

currently running kubernetes  1.8.2 but the same affect all versions up to 1.8.4 and I suppose 1.9.x

I have some programs that works with iptables ( weave-cni , custom firewalls , stats, etc )
I've noticed sporadic errors logged from various instances of kube-proxy
ie:
```console
Failed to execute iptables-restore: exit status 1 (iptables-restore: line 683 failed, 1 proxier.go:1573]
```

looking at proxier.go I've seen that you are not using the "-w" iptables arguments which is a MUST when you are dealing with possible concurrent execution of iptables ( and this is the case because you cannot be sure that kube-proxy is the only program that call iptables in the system ) 

so , I suggest to add as argument  `-w 5` , or what you consider sane to iptables commands (or write a logic in go to handle iptables locking.. but why when there is already this argument for that specific case ? :) )

as it is now It is triggering errors in logs which then are monitored and also trigger my alerting systems , and I don't know if internally cause further issue, but anyway the wait param for iptables is here be used :) .

Thank you,
Francesco

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/iptables.go#L417

We already use wait, as long as iptables is > 1.4.20 - where are you seeing that we don't?
