### ISSUE TITLE
add support for host devices

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#5607]
It would be nice if the [container api payload](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L372) had support for exposing host devices to the container (like `docker run --device` does).

The kubelet could pass it [go-dockerclient](https://github.com/fsouza/go-dockerclient) once they add support for it (https://github.com/fsouza/go-dockerclient/issues/241), or create container with the docker remote api by passing an addition member in the `/create` `HostConfig` payload:

```
{
    "PathOnHost": "/dev/deviceName",
    "PathInContainer": "/dev/deviceName",
    "CgroupPermissions": "mrw"
}
```

**Comment by proppy** [comment]
So it's now fixed on the go-dockerclient side https://github.com/fsouza/go-dockerclient/commit/e4fcc92bd5588da5e50f491ebecf631349299c0f

**Comment by therc** [comment]
We need to expose GPUs to the containers. I can write the PR and (given my previous experience with a types.go change) rebase it over and over. What are the odds of it getting accepted? The first  thought to mind is how to secure it, as in @erictune's linked issue.

**Comment by therc** [comment]
I could place it behind a kubelet or apiserver flag, which is off by default.

**Comment by osterman** [comment]
I need this feature so we can run `s3fs` inside of k8s. Will have to use `fleet` for now :(

**Comment by praoreo** [comment]
@proppy 
Hi,

What is the syntax to mention device information in yaml/json file? I tried giving the below in .json file, but got "found invalid field device for v1.PodSpec" error.  I am using 1.3.6 kubernetes version.

```
                                "device": {
                                        "PathOnHost": "/dev"
                                },
                                "nodeSelector": {
```

**Comment by maci0** [comment]
I don't think it has been implemented yet. But it seems what @therc wants to do has. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go has some nvidia stuff.

It's still missing support for other devices.
It used to work in docker with volume mounts, my guess it when they introduced --device they locked down the volume mounts using device cgroups
https://www.kernel.org/doc/Documentation/cgroup-v1/devices.txt

**Comment by farmdawgnation** [comment]
Hey what's the status here?

We need this as well. I haven't contributed to Kubernetes before, but it looks like a lightweight way to provide some (initial) support for this is to support a container annotation for it. That looks like it would get piped into the PodSandboxContext which I could in turn use to pass the requisite arguments into the host config for the Docker container creation.

**Comment by drekle** [comment]
I also believe that I really need this.  I will be trying to deploy a pod to a specific node which uses a napatech card or other networking devices.

**Comment by jbiel** [comment]
FWIW the following was working for me to pass through a sound card device ~3 months ago. [Privileged mode](https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities) was the key and according to the docs it looks like it should still work.

```
      containers:
      - name: foo
        ...
        volumeMounts:
        - mountPath: /dev/snd
          name: dev-snd
        securityContext:
          privileged: true
      volumes:
      - name: dev-snd
        hostPath:
          path: /dev/snd
```

**Comment by farmdawgnation** [comment]
Yeah, that'll work with privileged mode. The rub is we run code in a multi-tenant environment so that's a non-starter for our security requirements. Mounting devices using `--device` is safer.

**Comment by thockin** [comment]
The status of this is that we have not had a proposal for an API to capture this.  The issue is that the API needs to be plausible across multiple runtimes.

**Comment by farmdawgnation** [comment]
@thockin Got it. I'm not super familiar with the Kubernetes proposal process, but I'm willing to suggest some things.

Does it need to be _plausable_ across multiple runtimes or _implementable_ across multiple runtimes? The latter would imply that if rkt doesn't support something, then we can't have any kind of support for it in Docker at all.

I know that there's already some pattern of using container annotations for things that are vendor specific. Is that an option here?

**Comment by maci0** [comment]
+1

**Comment by tcf909** [comment]
+1

Currently hostDevice option requires full privileged security rather than cap_adds -- very uneasy about this vs segmented cap permissions.

**Comment by thockin** [comment]
Sorry, I never replied!

When I say "plausible" I mean that at least the major runtimes maintainers
have looked at the API proposal and agreed that the semantic is doable,
even if they don't have the requisite support yet.

Annotations could work, but I worry that it becomes a de facto API, so I'd
rather think about that up front.

The issue for me is coupling - as soon as you allow users to specify
details like this, they are forced to understand the host machines in great
detail.  Which machines have the device?  What is the /dev name of the
device?  How do I know that nobody else is using the device at the same
time?  These are the questions that need answering, or rather - what can we
do automatically to prevent users from having to know the answers to these?

In a lot of cases, the upcoming opaque integer resources are better in
pretty much every way.  If you say "this machine has 1 instance of '
mycompany.com/soundcard'" and provide the metadata for it, we can schedule
to that and map the device and provide mutual exclusion all automatically.

**Comment by gavrie** [comment]
@thockin: It does sound interesting to use opaque integer resources for this. Is there a way to add metadata to such a resource? I couldn't find one in the documentation.

Your concern about growing a de facto API with annotations is understandable. On the other hand, it might be useful to provide a way to access devices and see how people use it in the real world before designing an API that then captures those real world requirements in a clean way.

Specifically, I'm interested in allocating node-local block devices to containers (or pods). If a node has a certain amount of local SSDs, I want to be able to use such an SSD directly from a pod. Metadata would include the capacity of the SSD, its device node, and maybe other fields such as device type.

The [resource model design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resources.md) mentions this, but it seems to be way down the road.

Would there be a simple way to allow usage of local devices on the short term and thereby gather real world requirements, without requiring the use of privileged containers?

**Comment by thockin** [comment]
@ConnorDoyle for opaque resources

@msau42 for local-storage stuff

**Comment by thockin** [comment]
@dchen1107 @yujuhong I am anxious about an annotation for this, but it certainly has come up and we don't have a "real" answer yet.

**Comment by msau42** [comment]
[Local storage](https://github.com/kubernetes/features/issues/121) is covered here and will be a long-term project.  For the short term, the only ways now to utilize local SSDs are hostpath volumes or a distributed fs like glusterfs.

**Comment by maci0** [comment]
I also want this so, I can mount **/dev/kvm** into an unprivileged container.
Currently kubernetes has an alpha api to mount nvidia video cards into the container, does this work across all runtimes as well, if not why does --device need to be any different ?

**Comment by yujuhong** [comment]
@thockin, there are two APIs involved in this issue: the kubernetes api and the api between kubelet and the container runtime (a.k.a. CRI). For the former I think supporting opaque resources makes sense. As for the latter, the CRI already includes [devices](https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/kubelet/api/v1alpha1/runtime/api.proto#L490) in its API in order to support the GPU devices in Alpha. The change was introduced in #35597.

**Comment by maci0** [comment]
Exactly my point. Most of the code should be there, the kubernetes api just doesn't expose that functionality yet.

**Comment by thockin** [comment]
Supporting named devices in the CRI layer is perhaps appropriate, but
supporting it at the cluster API layer isn't good.

**Comment by ConnorDoyle** [comment]
Coming into this late, just adding some notes about opaque resources. Opaque Integer Resources (OIRs) are alpha as of v1.5. The missing feature to support this use case is how to extend node-level isolation to an opaque resource. There are discussions happening this month about how to accomplish that. This is happening in sig-node and the resource management workgroup. At last mention, @derekwaynecarr is working on a proposal for isolation extensions. At the same time, @vishh @dchen1107 and @thockin have asked for a proposal to explore some kind of lifecycle hook to let operators execute extra steps during pod/container setup and teardown.

Agree with @thockin on not putting device names into the pod spec. Unless Kubernetes will include specializations for all sorts of devices, users would need some external way (an API) to do the matchmaking from resource type to concrete device name on the host.

**Comment by vishh** [comment]
I feel https://github.com/kubernetes/community/blob/master/contributors/design-proposals/volume-hostpath-qualifiers.md can be extended to have kubelet auto whitelist hostpath devices for the respective containers.

**Comment by tobegit3hub** [comment]
Any progress about this? We need to expose the `devices` like `/dev/fuse` for unprivileged containers.

Using `--privileged` is not good especially when we don't want to expose all GPU devices for every container.

**Comment by prateek2408** [comment]
By going through the comments it seems that the issue is party solved but a final fix is yet to come.
Is my understanding correct ?

If yes then what part is left. I can take that as there is a requirement where I need to expose an Nvidia card to one of the Kubernetes Pod/Container

**Comment by cmluciano** [comment]
@prateek2408 No GPU alpha support was added to 1.6. We do have some cleanup to extend the feature to other non-Docker runtimes https://github.com/kubernetes/kubernetes/issues/43240

**Comment by prateek2408** [comment]
@cmluciano Thanks for the info. Currently as there is no support to pass a specific GPU card to a kubernetes pod then for a workaround if I launch a kubernetes pod with privileged mode then I would get access to all the PCI resources. 

Is my understanding correct ?, If yes have you tried it ?

**Comment by cmluciano** [comment]
@prateek2408  I have not tried that myself. Are you interested in selecting a specific family of GPU cards on the node or are there more advanced topology mechanisms that you need?

**Comment by prateek2408** [comment]
@ cmluciano I tired with privileged mode and it worked fine. However I went through this feature and came to know that it is not recommended to run a container in privileged mode as it exposes all the resources and can cause security problems. 

Going further I have a use case where I want to assign a particular GPU card and it would be even better if I can assign a portion of GPU to a particular container/pod. Memory also I want to provide only a specific percentage of GPU Ram to the container. So resource wise it would be something like this:-

Container 1 resources
1. CPU - 1
2. RAM- 256 MB
3. GPU- 0.2 percentage 
4. GPU RAM- 500 MB 

Right now I am going through docker container api's and  exploring on how can I achieve this. 
If it can be done by docker then we can add this feature in the CRI

**Comment by thockin** [comment]
Even within this topic there are multiple issues in play:

1) how to allow things like /dev/fuse which need some privilege but are
virtual by nature

2) how to allow specific GPUs

3) do we allow time-slicing on GPUs?

To (3), I am not GPU expert, but as I understand it, the GPU RAM isn't
protected and isn't fast to load, so timeslicing would probably be really
bad.

**Comment by cmluciano** [comment]
I too am not an expert at GPU time-slicing and serach results only seem to return research papers on the subject. @prateek2408 for GPU specific features, I would add a comment/use-case to  #44107.

There will also be some work to advance the Device support in https://github.com/kubernetes/kubernetes/issues/43240.

**Comment by therc** [comment]
@prateek2408 there is no way to provide "only a specific portion of GPU RAM to a container". Multiple processes can access the same device and each allocate RAM, but there's no MMU on the device to protect one process' data from the others. One thing that perhaps Nvidia could implement is letting their memory allocator look at an optional environment variable with a GPU memory limit, which Kubelet or similar would set. If the process goes above the value, execution could terminate (or allocations fail). That assumes cooperation from the process and it only helps with processes that allocate beyond their reservation. Again, no protection there. A malicious container could still overwrite the variable with a much larger value before calling any of Nvidia's functions. A more secure way could perhaps involve some cgroup-level metadata that the process can't change. But a rogue container could just patch the change in the Nvidia libraries :-)

More recent Nvidia chips allow for some overlap between different processes. Kepler contexts are serialized and switch on entire kernel boundaries (unless you divide the computations manually into timeslices), while Pascal has a new timer and contexts can be swapped at the single instruction level.
Even on those, though, just like with memory, it's hard to reserve and enforce slices of GPU time.

With Kubernetes 1.5 (but not anymore in 1.6), if your machine has only one GPU, you can use a workaround to have multiple pods share it. It's ugly, but it works, as long as you're OK with having no enforcement.

**Comment by tobegit3hub** [comment]
We can discuss the issues of GPU in another thread. Here we need to run the container with `--device` parameter just like how `docker` does.

I think @vishh 's proposal can fix this. Is anyone working on this now?

**Comment by urzds** [comment]
@tobegit3hub You mean [the volume hostpath qualifiers proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/volume-hostpath-qualifiers.md)?

I prepared a proposal for what we call the [Container Device Interface (CDI)](https://github.com/urzds/kubernetes/blob/proposal/container-device-interface/docs/proposals/container-device-interface.md): A generic way to allocate devices to containers.

----

We use Kubernetes to schedule scientific 3D visualisation applications onto a cluster. Hence our containers use GPUs / DRM and other device nodes (e.g. TTYs).  Scheduling of Pods to Nodes with a capacity for such devices can be dealt with using [Opaque Integer Resources (OIR)](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#opaque-integer-resources-alpha-feature), where scripts external to Kubernetes handle device discovery and capacity reporting (see e.g. [kube-gpu-resources](https://github.com/urzds/kube-gpu-resources)).  The [Container Runtime Interface (CRI)](https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md) already supports [binding host device nodes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L586) to a container.  What is currently missing is a way for the Kubelet to generically allocate the available devices of a certain type to a container while it is being started.  The Container Device Interface (CDI) shall bridge this gap.

----

Please find the [full text of the proposal](https://github.com/urzds/kubernetes/blob/proposal/container-device-interface/docs/proposals/container-device-interface.md) in our copy of the Kubernetes proposal documents.  We would love to hear feedback from the community on this proposal.

**Comment by prateek2408** [comment]
@tobegit3hub  - I will look into CDI and see how it can fit it my use-case, Thanks

**Comment by vishh** [comment]
GPUs are planned to be exposed as a first class resource. Accessing
arbitrary host device is different from accessing well known devices like
NICs or GPUs. We are aiming for having the kubelet discover non-standard
host devices based on an internal API and have these devices be exposed as
schedulable resources.
The specifics of this design is yet to be finalized.

@tobegit3hub <https://github.com/tobegit3hub> the link to your proposal is
broken.

**Comment by urzds** [comment]
@vishh Some questions regarding your proposal:
* What is the reasoning behind using an internal API instead of calling out to an external one?
  - In case it is not clear from my proposal: I except an external API to be much better extensible and thus more flexible, especially with regards to additional capabilities of hardware.
* How do you plan to support e.g. PCIe SR-IOV capabilities using this approach?
* What distinguishes GPUs from other device / accelerator types like Xeon Phi or FPGAs from a view-point of Kubernetes?
* How can I help bring the design proposed by "you" (the Resource Management WG?) forward?
* Is a preliminary draft of that design available somewhere?

**Comment by igoratencompass** [comment]
+1 for this I also have a need for /dev/fuse access

**Comment by ZongqiangZhang** [comment]
+1 need for /dev/fuse access, which is used by s3fuse

**Comment by ZongqiangZhang** [comment]
+1 need for /dev/fuse too

**Comment by x1957** [comment]
+1

**Comment by shenshouer** [comment]
+1 need for /dev/nvidia*

**Comment by ateleshev** [comment]
+1 need for /dev/kvm

**Comment by DjangoPeng** [comment]
@vishh +1.  Could you have a look at [#10642](https://github.com/tensorflow/tensorflow/issues/10642), I think it's need to add `/dev/nvidia-uvm` into container.

**Comment by thockin** [comment]
/dev/fuse and /dev/kvm are pretty fundamentally different than
/dev/nvidia-* and I think they warrant a different solution.

Interestingly, to use /dev/fuse you have to be running with privileges
anyway (right?) so you can literally hostPath mount /dev/fuse today.  Not a
great answer, but it seems to work.

As for an API - what I want to avoid is codifying linuxisms into the kube
API any more than they already are, and I don't want to expose hardware
where it isn't safe.

Something like the original proposal (call it `hostDevice` or something) +
a whitelist of safe devices, maybe?

How about non-docker runtimes like CRI-O and containerd - do they have the
requisite support?

**Comment by tobegit3hub** [comment]
Thanks @thockin . We have tested that mounting `/dev/fuse` as `hostPath` could not work so we have to run `Pod` with privileges in Kubernetes.

However, if we have native `docker`, we can mount `/dev/fuse` with `--device` which will work. And we can not pass the parameter of `--device` in Kubernetes yet.

That's our requirements and it would be great if it supports for `docker` and other container runtimes.

**Comment by maci0** [comment]
exactly, years ago it used to work in docker with `--bind` but later they introduced `--device` and it stopped working with `--bind`.
Thats why `hostPath` is not a feasible option.

**Comment by Iodun** [comment]
+1 need for /dev/fuse

**Comment by DylanGraham** [comment]
Looking for /dev/net/tun support :)

**Comment by vishh** [comment]
Mounting devices requires cgroup updates. That's why hostpath isn't working as-is. I still think my proposal in https://github.com/kubernetes/kubernetes/issues/5607#issuecomment-275267734 is worth exploring further. 

If there is any scheduling necessary for device files, then I'd recommend following the device plugin route - https://github.com/kubernetes/kubernetes/issues/5607#issuecomment-275267734

**Comment by vishh** [comment]
@DjangoPeng The issues you mention with Nvidia GPUs should have been addressed in the recent releases (>= 1.6). If not please open a separate bug.

**Comment by DjangoPeng** [comment]
@vishh Thanks! I'd like to follow up.

**Comment by tvalentyn** [comment]
Is it right that we will be able to mount nvidia devices to containers in 1.8 with
https://github.com/kubernetes/kubernetes/pull/46597 ? If not what is the status?

**Comment by vishh** [comment]
@tvalentyn you don't have to `mount` devices. Kubernetes provides extensions and Nvidia provides plugins which will automate management of GPUs at scale. So you only `request a GPU` and mounting happens automatically via plugins. 

This issue is beyond just GPUs. As I mentioned earlier what's missing is https://github.com/kubernetes/kubernetes/issues/5607#issuecomment-275267734
I'm not sure if #46597 addresses my suggestions. If it does, this issue can be closed IMO.

**Comment by tvalentyn** [comment]
Thanks @vishh, I understand that there may be a better way for Kubernetes to manage GPUs devices eventually. It is still work in progress, right?  

Since issue refers to mounting any device to the container (including GPU devices), I would still ask stakeholders to clarify current status. We can use `--device` to add devices with docker, but with `kubelet`, AFAIK we don't have such option.  Perhaps  @dixudx  or @thockin can comment whether #46597  enables this?

**Comment by dixudx** [comment]
```
root@x86-server01:~# docker run -it --rm --privileged -v /dev/fuse:/dev/fuse ubuntu:xenial bash
root@0864c5bfa870:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
none            1.1T  207G  808G  21% /
tmpfs            16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
udev             16G     0   16G   0% /dev/fuse
/dev/sda2       1.1T  207G  808G  21% /etc/hosts
shm              64M     0   64M   0% /dev/shm
root@0864c5bfa870:/# uname -a
Linux 0864c5bfa870 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@0864c5bfa870:/# stat -L --printf "%F" /dev/fuse
character special fileroot@0864c5bfa870:/# 
```

> We can use `--device` to add devices with docker, but with `kubelet`, AFAIK we don't have such option.

@tvalentyn #46597 did provide a way to mount such host devices, by setting `Type` in `HostPathVolume`. For example, we can set `Type` to `CharDevice` for `/dev/fuse`. In addition, we may also need to make sure container running in privileged mode by setting `SecurityContext.Privileged=true`.

This feature is only available from v1.8.  Currently you can find the doc [here](https://github.com/kubernetes/kubernetes.github.io/pull/5503), which will be available in [volumes#hostpath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) when v1.8 get released officially.

**Comment by andrewsykim** [comment]
@dixudx I've tried running this host path config on my deployment:
```
  volumeMounts:
      - mountPath: /dev/fuse
         name: dev-fuse
... 
volumes:
      - hostPath:
          path: /dev/fuse
          type: CharDevice
        name: dev-fuse
```

But from the kubelet I see 
```
Warning		FailedMount		MountVolume.SetUp failed for volume "dev-fuse" : hostPath type check failed: /dev/fuse is not a character device
```

On the host /dev/fuse is definitely a character device
```
$ ls -al /dev/fuse
crw-rw-rw- 1 root root 10, 229 Nov 14 19:55 /dev/fuse
```

**Comment by RRAlex** [comment]
/remove-lifecycle rotten

For people wanting to run packer (with /dev/kvm) inside k8s, this is an essential issue.
`--privileged` is way overkill and a --device equivalent would be very useful, maybe via a `hostDevice:` option?

**Comment by msau42** [comment]
@jiayingz does the device plugin interface cover this use case?

**Comment by jiayingz** [comment]
The device plugin API does allow a device plugin to pass Kubelet the host devices to be created in container runtime, but I am not sure what is the extra requirement of this feature.

**Comment by andrewsykim** [comment]
related to my issue earlier regarding character devices, I think it was a bug, fix is in https://github.com/kubernetes/kubernetes/pull/60440

**Comment by asigatchov** [comment]
I need for /dev/dri/renderD128

**Comment by hiyijian** [comment]
I need for /dev/infiniband

**Comment by hustcat** [comment]
+1 for this.

I'v write a [RDMA device plugin](https://github.com/hustcat/k8s-rdma-device-plugin) for kubernetes.

We need pass device `/dev/infiniband/rdma_cm` for all container which use RDMA device for run RDMA application in container.

**Comment by cmluciano** [comment]
@hustcat this is awesome! Have you presented this on a Resource-Management WG call yet?

**Comment by hustcat** [comment]
@cmluciano I didn't do that. I'd like to present this on next Resource-Management WG call.

**Comment by resouer** [comment]
@msau42 @jiayingz This issue is out-of-date actually. CRI already support `devices` for long time and that's how device plugins works. But the user requirements here seems to be: specifying devices I want in the container. This is kinda conflict with DP right now which relies on Kubelet to maintain devices info and call `Allocate(devIDs)` to do that.

@hustcat How did you workaround `/dev/infiniband/rdma_cm` right now? 

I would also suggest to close this one and create a new issue to track this, with the background of DP and CRI.

**Comment by t3hmrman** [comment]
He all, sorry to bump an old thread, but to my knowledge this doesn't actually fix the issue:

I'm trying to run QEMU (I found out that I'm basically walking in the footsteps of [Dalton Hubble from CoreOS](https://gist.github.com/dghubble/c2dc319249b156db06aff1d49c15272e)) and `/dev/kvm` use is looking to be a requirement for me (for both performance and some key QEMU features), but I don't want to run all privileged containers.

The new ticket seems to focus on making Device Plugins more flexible but when I read the [device plugin docs](https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/), there is a huge issue -- devices can't be shared, and `/dev/kvm` is most certainly shared.

I would even settle for a way to run a `privileged` container but restrict the accessible device paths in the container. From what I can read the closes thing would be a current combination of `privileged` container and `allowedHostPaths`, but I don't think it quite works that way.

**Comment by guanyuding** [comment]
+1 need for /dev/fuse

**Comment by micw** [comment]
@t3hmrman I found https://github.com/kubevirt/kubernetes-device-plugins/blob/master/docs/README.kvm.md which may solve your particular use case.

**Comment by micw** [comment]
It should be possible to create a generic device plug-in which gets a device node as argument as well as a number of allowed instances.

**Comment by t3hmrman** [comment]
Hi @micw Thanks for the suggestion! That definitely looks like it would solve my problem (and others'), and it explains how kubevirt can get the functionality they provide. 

Since posting here I've started using [untrusted workload runtimes w/ `containerd`](https://github.com/containerd/containerd/releases/tag/v1.1.0) in combination with the [`kata-containers`](https://katacontainers.io/) to run pods in VMs, and in the future intend to use the [runtime class proposal](https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md) to solve this instead. These days `kata-containers` has a super easy to use installer as well, and I can only imagine that it will get better/easier as the runtime class proposal moves towards GA.

As far as running QEMU *inside* an actual pod, it seems like `kubevirt` or `runtimeClass`-annotation enabled controllers are the better way to go for now. That generic device plug-in does sound good though -- would likely solve all the other cases mentioned

**Comment by OJFord** [comment]
@thockin, you wrote:
> Interestingly, to use /dev/fuse you have to be running with privileges anyway (right?) so you can literally hostPath mount /dev/fuse today. Not a great answer, but it seems to work.

and @dixudx said similar, but this is not true in Docker - 'just' `cap_add: - SYS_ADMIN` is enough.

**Comment by dinathom** [comment]
Is it true then that the only way in k8s to access host block device is to use a privileged container? So the volumeMode=Block would not mean anything (to read/write into the device) unless this is running in a privilege container?

**Comment by kfox1111** [comment]
your application could read the block device directly too. stuff like, kvm would do that. or some databases. No privilege is needed in that case.

**Comment by dinathom** [comment]
@kfox1111 that seems different from what I read here: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privileged 
how would the application have the ability to read the device unless the container allows it via some additional capabilities? 

The reason kvm works ( did not test this but from the documentation ) is because of  device plugins that whitelist /dev/kvm.

**Comment by kfox1111** [comment]
I don't believe you need any special privilege in linux to read from a block device. only unix permissions to the block device. You do need special privilege to mount a block device. If the storage driver plumbs through the device and gives it the right permissions, I think it works.

I believe /dev/kvm is an entirely different thing as it isn't a blockdev.

**Comment by kfox1111** [comment]
Hmm... no. there seems to be a capability restricted in docker by default that normal users on the host dosn't have.

**Comment by bluebeach** [comment]
+1
I need access /dev/mem in my unprivileged container .
any help!!!

**Comment by bluebeach** [comment]
I Just find a plugin that can support add device /dev/mem without privileged !!!
https://github.com/honkiko/k8s-hostdev-plugin

**Comment by shufanhao** [comment]
> I Just find a plugin that can support add device /dev/mem without privileged !!!
> https://github.com/honkiko/k8s-hostdev-plugin

Actually, this solution also need run the daemonSet with ```securityContext:
          privileged: true```

**Comment by shufanhao** [comment]
+1
also need access /dev/mem in unprivileged container and don't want to run any pod with ```securityContext: privileged: true```

**Comment by kfox1111** [comment]
What? According to the man page for /dev/mem (http://man7.org/linux/man-pages/man4/mem.4.html)
```
      "/dev/mem is a character device file that is an image of the main
       memory of the computer.  It may be used, for example, to examine (and
       even patch) the system."
```
If you can touch that file, you are privileged whether its flagged or not... That shoulnd't be handed over to unprivileged containers IMO.

**Comment by xt94c4t9ce** [comment]
I'm surprised this bug's closed because the original problem doesn't seem to be fixed.

On Kubernetes 1.18.8 with Docker 19.03.12, I'm not able to use a mapped host block device in a container without running the container in privileged mode.

The original problem here was that Docker's --device functionality wasn't available in Kubernetes, and that problem remains.

Or, is there a solution to this that I've missed?  Thank you.

**Comment by patrijua** [comment]
I also find this surprising that there seems to not be a way to use host connected devices from containers without compromising security. We would need to access /dev/ttyUSB0 chardevice from container and we do not want to run anything as privileged.  So if there's a solution, please share. Thanks!

**Comment by YaShanBoy** [comment]
> It would be nice if the [container api payload](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L372) had support for exposing host devices to the container (like `docker run --device` does).
> 
> The kubelet could pass it [go-dockerclient](https://github.com/fsouza/go-dockerclient) once they add support for it ([fsouza/go-dockerclient#241](https://github.com/fsouza/go-dockerclient/issues/241)), or create container with the docker remote api by passing an addition member in the `/create` `HostConfig` payload:
> 
> ```
> {
>     "PathOnHost": "/dev/deviceName",
>     "PathInContainer": "/dev/deviceName",
>     "CgroupPermissions": "mrw"
> }
> ```

How to integrate with k8s？？？？

**Comment by pre** [comment]
As of 01/2021 it doesn't seem to be possible to mount eg. /dev/fuse without `privileged:true` 

The relevant issue seems to be https://github.com/kubernetes/kubernetes/issues/7890

**Comment by pre** [comment]
Per 01/2021 it does not seem to be possible to mount (at least FUSE) host devices without `privileged: true`: https://github.com/kubernetes/kubernetes/issues/7890#issuecomment-762400026

**Comment by pre** [comment]
Mouting host devices without `privileged: true` is possible via the Kubelet device api using a Device Manager! 

See details in https://github.com/kubernetes/kubernetes/issues/7890#issuecomment-766088805
