### ISSUE TITLE
[job failure] gke-device-plugin-gpu

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56078]
/priority critical-urgent
/priority failing-test
/area platform/gke
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-18.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gke-device-plugin-gpu

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/645
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/646
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/663

**Comment by jiayingz** [comment]
/assign @mindprince 

Rohit, should this issue be fixed with your recent pr that updates image used in the test?

**Comment by mindprince** [comment]
This was caused by https://github.com/kubernetes/kubernetes/pull/55988 which broke bringing up alpha clusters on GKE.

I added a change to GKE infra which would get rolled out soon and the tests would be green again.

**Comment by spiffxp** [comment]
/close
Thanks for the fix.  Latest run is green https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu/685
