### ISSUE TITLE
[job failure] gci-gce-slow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56079]
/priority critical-urgent
/priority failing-test
/area platform/gcp
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-17.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-slow

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/12108
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/12109
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/12190
- suspect commit range: https://github.com/kubernetes/kubernetes/compare/56e62b684...3ec7487c0

**Comment by MrHohn** [comment]
https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow
Test is no longer failing, seems #56128 fixed it.

/close
