### ISSUE TITLE
[Windows] No outbound internet connection from windows containers

### ISSUE THREAD

**Issue by masroorhasan** [kubernetes/kubernetes#56076]
/bug
/sig network
/sig windows

**What happened**:
Deployed Kubernetes Cluster on Azure Container Service (via portal). Azure creates the resource group with all cluster related resources (VMs, load balancers, nsg rules, etc). Cluster is working fine in terms of k8s resource deployment. 

Deployed simple IIS server on the cluster:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: iis
spec:
  containers:
  - name: iis
    image: microsoft/iis:nanoserver
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
```

However, the IIS server container has no outbound internet connection. Verified with accessing the container via `kubectl exec -it iis -- powershell` and then pinging external IP, for example:
```sh
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reser

PS C:\> ping www.google.com

Pinging www.google.com [172.217.3.164] with 32 bytes of da
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.217.3.164:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

`ipconfig` from inside the `iis` container:
```sh
PS C:\> ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (Container NIC 4985007b):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::adab:f843:ca7a:c664%33
   IPv4 Address. . . . . . . . . . . : 10.244.1.174
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (Container NIC 4053100c):

   Connection-specific DNS Suffix  . : **************************.xx.internal.cloudapp.net
   Link-local IPv6 Address . . . . . : fe80::75ff:25d4:4313:e70c%37
   IPv4 Address. . . . . . . . . . . : 172.19.170.9
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.19.160.1
```

I've read around the docs and some stackoverflow, thus tried to set various dnspolicies to deploy a new IIS Pod:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: iis-hostnet-dnspolicy
spec:
  containers:
  - name: iis
    image: microsoft/iis:nanoserver
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
#   hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
#   dnsPolicy: Default
```

Running into same problems with various dnspolicies being set - there seems to be total block of outbound access to internet. I've read that kubernetes is flaky with windows network bridges (?), however there is no way for me to verify. 

**What you expected to happen**:

Expected `ping` to respond and verify that there is outbound internet connection.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a cluster on Azure Container Service (via portal). 
2. Deploy a Pod to your cluster (i.e. IIS).
3. Attach shell to running Pod and try to access (i.e. ping) to outbound internet.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```sh
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Cloud provider is Azure container service with windows minions.
A windows minion hardware configuration:
```sh
C:\Users\MasroorH> kubectl describe node 19190k8s9000
Name:                   19190k8s9000
Role:
Labels:                 beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/instance-type=Standard_DS2_v2
                        beta.kubernetes.io/os=windows
                        failure-domain.beta.kubernetes.io/region=westus2
                        failure-domain.beta.kubernetes.io/zone=0
                        kubernetes.io/hostname=19190k8s9000


Addresses:
  InternalIP:   10.240.0.4
  Hostname:     19190k8s9000
Capacity:
 cpu:           2
 memory:        7Gi
 pods:          110
Allocatable:
 cpu:           2
 memory:        7Gi
 pods:          110
System Info:
 Machine ID:                    19190k8s9000
 System UUID:
 Boot ID:
 Kernel Version:                10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)

```

- OS (e.g. from /etc/os-release):

```sh
CreationTimestamp:      Fri, 27 Oct 2017 15:31:02 -0700
Conditions:
  Type                  Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----                  ------  -----------------                       ------------------                      ------                          -------
  NetworkUnavailable    False   Fri, 27 Oct 2017 15:31:20 -0700         Fri, 27 Oct 2017 15:31:20 -0700         RouteCreated                    RouteController created a route
  OutOfDisk             False   Mon, 20 Nov 2017 09:37:21 -0800         Wed, 15 Nov 2017 01:52:31 -0800         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure        False   Mon, 20 Nov 2017 09:37:21 -0800         Wed, 15 Nov 2017 01:52:31 -0800         KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure          False   Mon, 20 Nov 2017 09:37:21 -0800         Wed, 15 Nov 2017 01:52:31 -0800         KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                 True    Mon, 20 Nov 2017 09:37:21 -0800         Wed, 15 Nov 2017 01:52:31 -0800         KubeletReady                    kubelet is posting ready status
Addresses:
  InternalIP:   10.240.0.4
  Hostname:     19190k8s9000
Capacity:
 cpu:           2
 memory:        7Gi
 pods:          110
Allocatable:
 cpu:           2
 memory:        7Gi
 pods:          110
System Info:
 Machine ID:                    19190k8s9000
 System UUID:
 Boot ID:
 Kernel Version:                10.0 14393 (14393.1715.amd64fre.rs1_release_inmarket.170906-1810)
 OS Image:
 Operating System:              windows
 Architecture:                  amd64
 Container Runtime Version:     docker://Unknown
 Kubelet Version:               v1.7.7-7+e79c96c8ff2d8e
 Kube-Proxy Version:            v1.7.7-7+e79c96c8ff2d8e
PodCIDR:                        10.244.2.0/24
```

- Others:
I've browsed a few stackoverflow articles and the general consensus is to just to use `acs-engine` instead of native ACS (via portal), for example:
https://stackoverflow.com/questions/42774110/azure-container-service-with-kubernetes-containers-not-able-to-reach-internet

It's a last resort option, but I'm trying to understand the networking issues/bug that might be blocking the containers from having access to outside internet.

Please feel free to let me know if this is Azure specific issue then I can move the issue to Azure repo - however some help here regarding solving this issue/bug would be much appreciated.

Thanks.

**Comment by masroorhasan** [comment]
After a lot of debugging and digging around (with Ops help) it has been resolved - its actually not a Kubernetes issue (sorry for opening it here) 

If anyone is curious - the issue is because the agent nodes (windows server 2016) has no public IP or NSG rules applied to it during cluster creation (by ACS deployment). If anyone runs into similar issues - please double check your agent's public IP in the attached network interface and NSG rules. 

As a side - I guess ACS is relying on admin to go configure the nodes after a deployment (?). This would seem strange to me since nodes are suppose to dynamically scale in and out depending on load (ideal scenario), so it seems unreasonable that admin has to do post-configuration.

Closing the issue. Thx :).

**Comment by 4c74356b41** [comment]
the explantion doesnt make sense. [Standalone VM with no Instance Level Public IP address](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#standalone-vm-with-no-instance-level-public-ip-address) has internet in Azure by default (unless you block it with NSG). And NSG allow internet (outbound) by default. Also, agent nodes ARE attached to the load balancer and load balancer is properly configured (of you go to the VM blade it will show you the outbound IP).

I've created 1.7.2,1.7.9,1.8.1,1.9.2 clusters with\without ACS (directly with ACS engine) same result. I cant seem to comprehend how the internet is not there if the LB is configured properly.

**Comment by masroorhasan** [comment]
@4c74356b41 LB was not configured properly as our vnet is wired specifically to be in our domain. As mentioned on the second post - its not a kubernetes issue. I've incorrectly said it might even be an azure issue since its actually our vnet configuration. I'm new to kubernetes + azure configuration thus the issue was not explained as well (+ incorrect assumptions).
