### ISSUE TITLE
GCE CreateVolume allocates in chunks of GiB incorrectly

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#56081]
GCE PDs are allocated in chunks of GBs (not GiB) but `CreateVolume` function incorrectly creates volume in chunks of GiB -  https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L86

cc @msau42 

/sig storage
@kubernetes/sig-storage-pr-reviews

**Comment by edisonxiang** [comment]
Hey @msau42 @gnufied,  I submit a pr #56600 for this issue.
Your suggestions are very important. Thanks.
