### ISSUE TITLE
[Azure] Internal Load Balancer doesn't add NSG rules for the internal Services unlike the Public LB

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#56086]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When we create an internal LB in Azure using `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` the new LB called <clustername>-internal gets created and the frontend IP configured with the right rules. 

The problem is that the NSG associated with the IP of the Internal frontend configuration never gets configured. 
**What you expected to happen**:
The NSG to have the proper rules, similar to what occurs with public IP LB

**How to reproduce it (as minimally and precisely as possible)**:
Create a service with an annotation; `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`
Configure your azure.json to use an external VNet (not sure if that is necessary, that's what we have)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.10
- Cloud provider or hardware configuration:
Azure
- OS (e.g. from /etc/os-release):
centOS 7.3
- Kernel (e.g. `uname -a`):
- Install tools:
In House (salt-based)
- Others:

**Comment by djsly** [comment]
@kubernetes/sig-azure-bugs

**Comment by karataliu** [comment]
There is a default NSG rule there for always allowing VNET traffics, thus it does not add value to have a redundancy rule for internal load balancers.
Are you also using cluster managed NSG with custom vnet? It should work if you do not change the default NSG settings.

**Comment by djsly** [comment]
While this is true on a cluster deployed using ACS/AKS, etc. When using vanially with an external Vnet managed by a different team. The Vnet/Subnet/NSG might be subject to different sets of rules. 

In our case, the NSG where the nodes are attached locks down inbound traffic and opens up a limited set of ports. For example the range for the node Port is indeed open. 

The problem with the Internal LB is that the internal IP resides in the same Subnet/NSG and the fronting PORT is defined by the service, therefore we need to have the same dynamic hole punching logic from the Public LB applied to Internal LB.

**Comment by karataliu** [comment]
If you specify 'loadBalancerSourceRanges' in service spec, then the NSG rule will always apply.

In the case you mentioned, the NSG already contains rules for restricting traffic in vnet, it might also require the exposed k8s service to be accessed from limited sources, thus having 'loadBalancerSourceRanges' also sounds reasonable here.

**Comment by djsly** [comment]
thanks! I will try and let you know

**Comment by djsly** [comment]
@karataliu I finally found some time to test, it turns out that setting `spec.LoadBalancerSourceRanges` does indeed help us out. I have a problem still and it is that I do not know all of the peered networks in advanced. I would like like to be able to set a serviceTag for all of the `virtualNetwork` but I guess the spec doesn't allow it...

`The Service "influxdb" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[VirtualNetwork]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24`

**Comment by karataliu** [comment]
@djsly Yeah, `LoadBalancerSourceRanges` accepts IP range values only.
Supporting service tags could be done via some additional annotations, that would be a new feature.

**Comment by jdumars** [comment]
@djsly is it ok to close this issue?  If there's a new feature needed, let's create a separate issue and track in SIG-Azure.

**Comment by djsly** [comment]
Sure, let me open up a new issue.
