### ISSUE TITLE
[job failure] gci-gke-slow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56080]
/priority critical-urgent
/priority failing-test
/area platform/gke
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-17.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-slow

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/12451
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/12452
- first bad (with Test): https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/12477
- latest bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-slow/12565

**Comment by abgworrall** [comment]
This has the same root cause as #56089 , and I suspect all GKE failures have this root cause.

**Comment by MrHohn** [comment]
https://k8s-testgrid.appspot.com/google-gke#gci-gke-slow
Test is no longer failing, seems #56128 fixed it.

/close
