### ISSUE TITLE
Refactor PV scheduling library into separate package

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56098]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig storage
/assign

**What happened**:
Move the new pv scheduling library code into a separate package so that the scheduler doesn't need to pull in the entire persistentvolume controller package.

**Comment by cofyc** [comment]
/assign
After [this] is done, this will be easy.

**Comment by cofyc** [comment]
@msau42 
hi, where you want to put scheduling library?
