### ISSUE TITLE
Add scheduler integration test for volume predicate equivalence cache invalidation

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56104]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 
/assign

**What happened**:
Need to test equivalence cache invalidation for VolumeBinding predicate

**Comment by msau42** [comment]
The tests should include all the conditions described in #58797

**Comment by resouer** [comment]
cc #60753 after updating the hash calculation method, `VolumeBinding` tests fail. I am looking into it.

**Comment by msau42** [comment]
Thanks so much for taking this on!  I would be happy to review

**Comment by misterikkit** [comment]
Feel free to add me as reviewer as well.

**Comment by msau42** [comment]
/remove-lifecycle stale
/lifecycle frozen

Ecache is being redesigned.  Need to re-evaluate this afterwards

**Comment by resouer** [comment]
@msau42 It would be safe to close this one after https://github.com/kubernetes/kubernetes/pull/71399 is in.
