### ISSUE TITLE
Update to etcd client 3.2.11

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#56114]
## Upgrade Kubernetes to use etcd client 3.2.11

The [etcd 3.2.10](https://github.com/coreos/etcd/releases/tag/v3.2.10) and [etcd 3.2.11](https://github.com/coreos/etcd/releases/tag/v3.2.11) client code includes a backport of a new gPRC balancer (https://github.com/coreos/etcd/pull/8840), and data race fixes to gPRC (https://github.com/coreos/etcd/pull/8867, https://github.com/grpc/grpc-go/pull/1687) found by the recently updated etcd functional tester.

https://github.com/kubernetes/kubernetes/issues/47131 suggests that load balancer issues may be responsible for a variety of reported HA etcd cluster issues.  Unfortunately, the reports lack sufficient detail to reproduce, so we can't say for sure which, if any, will be resolved by this fix. We do know, however, that the etcd functional test suite, which was updated to test a more comprehensive set of failure modes for 3.2.11, passes with these fixes in place, providing a strong signal that these fixes are essential to running HA etcd clusters.

Upgrading Kubernetes to use the 3.2.11 client will require upgrading from grpc 1.3.0 to 1.7.4. We expect the bulk of the work to be performing this grpc upgrade, which will require regenerating grpc bindings and updating grpc code and . See the [etcd client upgrade checklist](https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_2.md#client-upgrade-checklists-3210) for details.

We plan to target the Kubernetes 1.10 release, and backport to 1.9 (and possibly 1.8) if/when the fix proves stable.

(For the corresponding etcd server 3.2.11 upgrade see #56438)

**Comment by timothysc** [comment]
We need to do this as soon as master branch opens back up.  

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by jpbetz** [comment]
To bump etcd to 3.2.11 we must also bump grpc to 1.7.4. When attempting to bump the grpc, godep reported this error:

```
godep: no buildable Go source files in /usr/local/google/home/jpbetz/Projects/k8s/src/k8s.io/kubernetes/_output/local/go/src/google.golang.org/grpc/grpclb/grpc_lb_v1                                                                                                                              
 !!! Error in hack/godep-save.sh:69
...
```

Previously, we depended on grpc 1.3.0. In grpc 1.6.0 https://github.com/grpc/grpc-go/pull/1466 `grpclb/grpc_lb_v1/grpclb.pb.go` was deleted. And it appears we have multiple dependencies transitive dependencies on the package it exported:

```
./src/github.com/containerd/containerd/vendor/google.golang.org/grpc/grpclb.go: lbpb "google.golang.org/grpc/grpclb/grpc_lb_v1"
./src/github.com/google/cadvisor/vendor/google.golang.org/grpc/grpclb.go:       lbpb "google.golang.org/grpc/grpclb/grpc_lb_v1"
./src/github.com/docker/docker/vendor/google.golang.org/grpc/grpclb.go: lbpb "google.golang.org/grpc/grpclb/grpc_lb_v1"
```

The versions of `containerd`, `cadvisor` and `docker` that kubernetes currently depends on all depend on `grpc v1.3.0`. We could upgrade to `containerd v1.0.0` which depends on `grpc v1.7.2`, but master of `docker` and `cadvisor` still depend on `grpc v1.3.0`.

@menghanl the removal of `grpclb/grpc_lb_v1/grpclb.pb.go` in https://github.com/grpc/grpc-go/pull/1466 appears to backward incompatible change? Was this deliberate? Any recommendations on upgrade paths?

cc @timothysc @gyuho

**Comment by jpbetz** [comment]
Looks like I might just need to upgrade grpclb as well. Trying it out now.

**Comment by jpbetz** [comment]
Was able to appease `godep save` by adding a doc.go placeholder in the empty `grpc/grpclb/grpc_lb_v1`.

**Comment by drewwells** [comment]
What versions of k8s support etcd 3.2.11?
