### ISSUE TITLE
how to disable multiattach of iSCSI volume

### ISSUE THREAD

**Issue by wenjun93** [kubernetes/kubernetes#56149]
**Is this a BUG REPORT or FEATURE REQUEST?:**
/kind feature

**What happened:**
suppose already created a pod with iSCSI pvc, when kubelet down, pod is evicted and rescheduled to another node, while the old pod is still serving traffic and still writing the volume, how could we prevent this situation? Is there anyway to disable iSCSI volume multi-attach like cinder?

**Comment by wenjun93** [comment]
duplicated with #48953

**Comment by wenjun93** [comment]
@mtanino What's the logic of preventing multi-attach of iSCSI volume after implement iSCSI attacher interface? In attachdetach controller reconciler `isMultiAttachForbidden()` works for this, right? thanks.

**Comment by mtanino** [comment]
@wenjun93 @rootfs 

Correct. When you specify accessModes=ReadWriteOnce to iSCSI Persistent Volume, attachdetach controller reconciler isMultiAttachForbidden() works to prevent volume multi-attach between multiple kubelet node.

Note: this function only prevent multi-attach between multi kubelet node. User can attach this PV/PVC to multiple pods inside one kubelet node. This is current design.

**Comment by wenjun93** [comment]
@mtanino @rootfs

**Comment by wenjun93** [comment]
We cannot determine whether node is totally down or only kubelet down when node becomes `NotReady`, and pod's on `NotReady` nodes may still be serving traffic, so the problem is do we still need to update `node.Status.VolumesAttached` field for `NotReady` nodes, I would propose to determine if volume type is rbd/iSCSI/fc and node is NotReady [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L216), if both true, then don't update node status, new pod will not be created then, thus volume will not be mounted to multiple nodes. 
For evicted pod, we must ensure: (1)new pod can be created; (2) the old pod is totally down, at least volume is detached. For rbd/iSCSI/fc volumes, we can have an external controller to do this, like: (1) restart the NotReady node to disconnect the volume, (2)forcedetach: update node status in apiserver), then volume can be attached to another node, new pod can be created.

**Comment by mtanino** [comment]
@wenjun93 

Which kubernetes version are you using? Is this same question of this issue?
https://stackoverflow.com/questions/41926177/kubernetes-rescheduling-of-pods-after-a-node-becomes-unreachable

When I tried to reproduced this problem, a pod with iSCSI volume wasn't automatically rescheduled when kubeket node went down. After Kubelet became `NotReady`, Pod became `Unknown` status but the pod wasn't rescheduled to another, dokcer container kept running on original kubelet node.
Can you describe more detail steps to reproduce this?

>> I would propose to determine if volume type is rbd/iSCSI/fc and node is NotReady

Also I'm not sure why we need this kind of fix only for rbd/iSCSI/fc?
If this problem happens, do all storage plugin affect this problem?

@msau42 @jingxu97 @rootfs 
Any comment for this?

/sig node

**Comment by wenjun93** [comment]
@mtanino Sorry for not being clear, the case is, when the pod is created by replication controller, when pod became Unknown, a new pod will created with the same volume.

**Comment by mtanino** [comment]
@wenjun93 
When I create a pod with iSCSI volume in replicaset, after kubelet node2 goes down, new pod was rescheduled on another node(kubelet node1) with same iSCSI volume but the new pod didn't never come up since multiattach isn't permitted.

`Multi-Attach error for volume "pv0001" Volume is already exclusively attached to one node and can't be attached to another`

I think this is your expected behaviour.

```
root# kubectl describe po/rss-site-d574bcdcb-c62mv                                                                          [~/k8s-sample/replicaset]
Name:           rss-site-d574bcdcb-c62mv
Namespace:      default
Node:           k8s-node1/x.x.x.x
Start Time:     Thu, 30 Nov 2017 22:29:30 -0500
Labels:         app=web
                pod-template-hash=813067876
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/rss-site-d574bcdcb
Containers:
  front-end:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           80/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t4hjb (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nginx-pvc01
    ReadOnly:   false
  default-token-t4hjb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-t4hjb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age   From                                       Message
  ----     ------                 ----  ----                                       -------
  Normal   Scheduled              2m    default-scheduler                          Successfully assigned rss-site-d574bcdcb-c62mv to k8s-node1
  Warning  FailedAttachVolume     2m    attachdetach-controller                    Multi-Attach error for volume "pv0001" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulMountVolume  2m    kubelet, k8s-node1                         MountVolume.SetUp succeeded for volume "default-token-t4hjb"
  Warning  FailedMount            4s    kubelet, k8s-node1                         Unable to mount volumes for pod "rss-site-d574bcdcb-c62mv_default(d744c801-d647-11e7-8d92-525400ed3c79)": timeout expired waiting for volumes to attach/mount for pod "default"/"rss-site-d574bcdcb-c62mv". list of unattached/unmounted volumes=[data]
```

**Comment by wenjun93** [comment]
@mtanino Thanks so much for your testing, the code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go#L108) will remove terminated pod from desiredStateOfWorld, will the pod not be deleted after a while?

**Comment by mtanino** [comment]
@wenjun93 
There are two dswp, one is in kubelet and the other is in a/d controller. Your link is a/d controller's one.
I believe steps are;
- A/D controller is referring  kubelet's dsw therefore if kubelet node2 goes down and never come back, a/d controller's dsw isn't updated.
- As a result, if there is a pod with volume on kubelet node2 which goes down, a/d controller considers that the volume is still attached to node2, then a/d controller prevents to attach this volume when pod is rescheduled to another node.

**Comment by mtanino** [comment]
The feature to prevent multiattach for iSCSI plugin is available from Kubernetes v1.8.

**Comment by wenjun93** [comment]
@mtanino 
`A/D controller is referring kubelet's dsw therefore if kubelet node2 goes down and never come back, a/d controller's dsw isn't updated.`

What's the way `A/D controller is referring kubelet's dsw`? The way A/D controller communicate with node2's kubelet is `node.Status.volumeAttached` saved in apiserver , when node2 goes down and became notReady, A/D controller will still manage the node, see pod terminating, remove the pod's volume from A/D dsw, and after `UpdateNodeStatus()`, new pod's volume can be attached to node1. 
 I believe there is some misunderstanding from my point, I see the `Multi-Attach error` event is posted only 2 min ago, and the dswp loop duration is 1min, I think the new pod will be created after some time, could you provide the logs after the duration?

**Comment by mtanino** [comment]
@wenjun93

>> when node2 goes down and became notReady, A/D controller will still manage the node, see pod terminating, remove the pod's volume from A/D dsw, and after UpdateNodeStatus(), new pod's volume can be attached to node1.

Did you see Pod terminating of kubelet node2? I suppose this happens after kubelet service on node2 comes back again. correct?

After the pod was terminated, what's the status of pod and volume?
- Was the pod directory(/var/lib/kubelet/pod/poduid) unmounted and cleaned up successfully?
- Was the volume detached from kubelet node2 and plugin directory(/var/lib/kubelet/plugins/iscsi/...) unmounted and cleaned up successfully?

>>Which kubernetes version are you using?

Do you use latest master?

**Comment by dElogics** [comment]
"disable"
When was it enabled may I ask?
Agreeing with what mtanino says, the relocated container never starts and stays stuck in ContainerCreating, which is something problematic on my end since it fails the self healing property of Kubernetes.
