### ISSUE TITLE
Consider to back up device plugin checkpoint data on tmpfs

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#56159]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
From the discussion in PR review of using file store utility for device plugin checkpointing:
https://github.com/kubernetes/kubernetes/pull/55382#discussion_r152095025
@vishh suggested we consider to store checkpoints on tmpfs instead of durable storage and take the additional perf gains,
assuming that kubelet on node reboot will re-admit all pods.
We should consider this option and possibly store checkpoint data in a file under a tmpfs directory that only kubelet has access to.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tengqm** [comment]
So we are assuming that users will know that memory consumed by tmpfs will be accounted into container's memory usage thus increase the limit accordingly? 
Do we have an idea of how much performance gain are we expecting?
My current assumption is that the checkpoint data won't be accessed frequently.

**Comment by jiayingz** [comment]
The storage for the checkpoint is used by kubelet, so it shouldn't be accounted into any container's memory usage.

**Comment by jiayingz** [comment]
Btw, it is a good question about performance vs persistence tradeoff. We may want to carry some scaling test to answer this question, which may be better discussed in PR https://github.com/kubernetes/kubernetes/pull/56040

**Comment by jiayingz** [comment]
@vikaschoudhary16 as you are working on a common node-level checkpoint manager, you may also want to consider whether we need to persist checkpoint data upon node reboot. It seems this is not required by either device plugin checkpoint or dockershim checkpoint.
