### ISSUE TITLE
HPA not working: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics

### ISSUE THREAD

**Issue by varuntalus** [kubernetes/kubernetes#56165]
I did a deployment using yaml file and created PODs.

Next I am trying to create a HPA object to autoscale my application based on the resource utilization i.e. cpu.

But HPA is not working and giving me below error:

_**Conditions:**_
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://X.X.X.X:****/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dcnum'") has prevented the request from succeeding (get services http:heapster:)
**_Events:_**
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedComputeMetricsReplicas  51m (x411 over 4h)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://X.X.X.X:****/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dcnum'") has prevented the request from succeeding (get services http:heapster:)
  Warning  FailedGetResourceMetric       1m (x505 over 4h)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://X.X.X.X:****/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dcnum'") has prevented the request from succeeding (get services http:heapster:)

The above issue says, trying to reach: 'http://X.X.X.X:****/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dcnum'

but I am able to get the response when I curl this URL. I get OK response when I do wget. The above IP and port is pointing to the heapster running in the cluster. 

Moreover, I am able to see the resource utilization of cluster objects (pods, nodes etc...) in grafana properly. Which means heapster seems to be working fine. It is fetching the resource metrics from cluster and storing them in influx db successfully and Grafana is able to pick it and display.

But then why HPA is not able to receive the resource metrics response from heapster. Also while doing "kubectl top pod xyz", it is not showing me the details, rather giving me below error:

"top_pod.go:192] Metrics not available for pod default/cnumvar-59d5dd8598-tdp2rdd"_

Please let me know what could be the reason for this issue. How can it be fixed. 

kubernetes version: 1.8.3
Heapster version: 1.4.0

**Comment by varuntalus** [comment]
@kubernetes/sig-piosz-**_test-failures_**
sig/autoscaling

**Comment by varuntalus** [comment]
Can anyone please look into this issue. 

Is there a compatibility concern of k8s version with heapster version? I am using below versions:

**_kubernetes version: 1.8.3
Heapster version: 1.4.0_**

**Comment by varuntalus** [comment]
@kubernetes/sig-autoscaling-bugsTeam members are private

**Comment by varuntalus** [comment]
cc @piosz 

Could you please help me with this issue. I saw many related issues raised earlier (e.g. **_#47334_**) but could not find proper solution to this problem.

**Comment by varuntalus** [comment]
**_Please find below the Heapster logs:_**

I1122 06:49:31.201472       1 heapster.go:72] /heapster --source=kubernetes:https://x.x.x.x:6443?inClusterConfig=false&insecure=true --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
I1122 06:49:31.201521       1 heapster.go:73] Heapster version v1.3.0
I1122 06:49:31.201558       1 configs.go:61] Using Kubernetes client with master "https://x.x.x.x:6443" and version v1
I1122 06:49:31.201570       1 configs.go:62] Using kubelet port 10255
I1122 06:49:31.247217       1 influxdb.go:252] created influxdb sink with options: host:monitoring-influxdb.kube-system.svc:8086 user:root db:k8s
I1122 06:49:31.247260       1 heapster.go:196] Starting with InfluxDB Sink
I1122 06:49:31.247288       1 heapster.go:196] Starting with Metric Sink
I1122 06:49:31.265793       1 heapster.go:106] Starting heapster on port 8082
I1122 06:50:05.105538       1 influxdb.go:215] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system.svc:8086"
E1122 08:19:05.000399       1 kubelet.go:282] Node cluster-2 is not ready

**_below are the logs for HPA:_**

[root@cluster-1 log]# less messages | grep -i hpa
Nov 20 12:43:48 cluster-1 journal: I1120 07:13:48.201747       1 horizontal.go:145] Starting HPA controller
Nov 20 12:43:48 cluster-1 journal: I1120 07:13:48.201805       1 controller_utils.go:1041] Waiting for caches to sync for HPA controller
Nov 20 12:43:48 cluster-1 journal: I1120 07:13:48.701929       1 controller_utils.go:1048] Caches are synced for HPA controller
Nov 20 13:49:35 cluster-1 journal: I1120 08:19:35.161992       1 horizontal.go:145] Starting HPA controller
Nov 20 13:49:35 cluster-1 journal: I1120 08:19:35.162013       1 controller_utils.go:1041] Waiting for caches to sync for HPA controller
Nov 20 13:49:36 cluster-1 journal: I1120 08:19:36.562098       1 controller_utils.go:1048] Caches are synced for HPA controller
Nov 21 10:49:57 cluster-1 journal: I1121 05:19:57.697177       1 horizontal.go:145] Starting HPA controller
Nov 21 10:49:57 cluster-1 journal: I1121 05:19:57.697202       1 controller_utils.go:1041] Waiting for caches to sync for HPA controller
Nov 21 10:49:59 cluster-1 journal: I1121 05:19:59.297420       1 controller_utils.go:1048] Caches are synced for HPA controller
Nov 21 15:50:04 cluster-1 journal:  "jweToken": "{\"protected\":\"eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0\",\"aad\":\"eyJleHAiOiIyMDE3LTExLTIxVDEwOjM1OjAzWiIsImlhdCI6IjIwMTctMTEtMjFUMTA6MjA6MDNaIn0\",\"encrypted_key\":\"YX0uo4rb5-x32gHDaWPeEZovdLFQ3D8SBWrbtAyaVmdhfm4LU0zdY-9aWuUI6cdRJdPKWIVY3eFoU74AtF__FUudku_AGwumICJuxhZVhadz7kENNdRcuucS2SCkGoyT4i_yr1z9O6Bgpuc5hsY1hZO5iH1py4QWO6FkGOagmM7QfNSKJ-u8RAvWCwvhvGfBuARmqBpNP7C9l23_m5YME4E6J9IZ5DEyy4V-ywIgEOjwPvnWci

**_There are few more logs which are there:_**
Nov 21 12:03:16 cluster-1 journal: 2017/11/21 06:33:16 Metric client health check failed: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://10.X.X.X:8082/healthz'") has prevented the request from succeeding (get services heapster). Retrying in 30 seconds.
Nov 21 12:03:19 cluster-1 journal: E1121 06:33:19.292078       1 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/cnum: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://10.X.X.X:8082/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dcnum'") has prevented the request from succeeding (get services http heapster:)

**Comment by mattjmcnaughton** [comment]
Thanks for reporting! I can try my best to help you debug.

When you say you can successfully curl the heapster endpoint, what machine are curling from? As I'm seeing a similar error when trying to contact `10.X.X.X:8082/healthz` in your logs, I'm wondering if there is an issue with the different machines talking to each other. Additionally, do you see any logs on the heapster pod around when the auto-scaling is failing?

Could you share more about how you're hosting Kubernetes and any security groups/ingress/egress rules that may exist? Thanks :)

**Comment by varuntalus** [comment]
**_Kubernetes Cluster:_**

We have set-up a cluster of 3 VMs. 1 is master and other two are working as worker nodes. These VMs are part of the private cloud and there is no direct internet access available on these machines.

On cloud gateway we have set ingress\egress\security group where we mentioned the port ranges to be available for the cluster to work. We have also mentioned the ports for our specific applications also.

We curl the Heapster endpoint from one of the worker nodes where the heapster POD was running.

We can see that the machines are all connected. Telnet and ping are working absolutely fine.

At the time of creating HPA there was no error in the Heapster logs.

________________________________________________________________________

After debugging more into this issue we could see that the API server was not able to connect to the Heapster component. Somehow the resource metrics were not reaching to API server and that's why the HPA was not working at all.

As I mentioned earlier the cluster is in the private cloud and does not have any open internet access so we used the Proxy to connect to the internet at the time of installation. And we used the below proxies:
http_proxy, https_proxy and no_proxy(ip-1, ip-2 & ip-3, localhost, 127.0.0.1). We mentioned all these proxies in the /etc/environment file.

We added these proxies in the below locations as well:
a) /etc/systemd/system/dockerservice.d
b) /usr/lib/systemd/system/docker.service

So during the installation itself the apiserver.yaml, controller-manager.yaml and scheduler.yaml files got these proxy settings added in these as env variables. Due to this the internal communication of the cluster components was bound to happen via these proxies. But at the time of HPA creation when resource metrics were being captured and sent by heapster, they were not reaching to the HPA component. This is because Heapster was trying to connect to the proxy first. To resolve this we removed the proxies from the node where Heapster was running and then the "curl" started working. But still HPA was not able to receive because even API server was trying to connect through proxy.

**_Resolution:_**
We removed the proxies from APIServer.yaml manually and from all the locations on the master as well as worker nodes and then we found the communication started working.

**_Queries:_**
1. Is the above approach correct to resolve these kind of issues? Or else should we do the installations offline (without internet by keeping the required RPMs and images on local)?
2. We have removed the proxies from APIserver.yaml only and the cluster started working as expected, but do we need to remove these proxies from Controller-Manager.yaml and Scheduler.yaml as well.
3. After doing this work around we were able to successfully deploy and run our applications and they were getting autoscaled based on the resource metrics properly. But we could see there some delay (1-2 mins) in reflecting the actual metrics on the graphs and kubectl CLI. Is it normal or we have to tune something somewhere in the cluster?
4. We need to do autoscaling based on some other factors as well e.g. "num of requests coming in" etc..
How can we achieve this?
5. We are trying to deploy our application in load balanced mode (in our private cloud) but it is not working. Do we need to have external physical LB in place to do the load balancing in K8s. We tried using "nginx" (Ingress Controller) and the "Ingress Resource", we got them deployed and run successfully but still Load balancing is not working because we are not getting any "External IP" assigned. Please let us know if we are missing something in this setup for LB.

**Comment by mattjmcnaughton** [comment]
Glad to hear you got this working, @varuntalus !

Here is my best effort at answering your questions:

1-2. I'm not positive... sorry :( I'd recommend checking out #sig-autoscaling in the kubernetes slack.
3. Do you mean there is a 1-2 min delay in seeing auto-scaling impact metric levels on your pods? If so, I'd say that's fairly expected. When k8s triggers an auto-scaling event, it sets the desired replicas to a certain level. The scheduler must then allocate the new pods sufficient to reach this desired level. Then pods need to pull down the images, start the containers, etc... before the new pod shares in the work and we see an improvement in resource utilization. Additionally, if existing requests to the service are infrequent or long-running, it may be a while before sufficient new requests come to the new pod to balance the load.
4. It sounds like "custom metric auto-scaling" is what you're looking for. I'd recommend checking out these two links as a starting point: https://docs.bitnami.com/kubernetes/how-to/configure-autoscaling-custom-metrics/ and https://medium.com/@marko.luksa/kubernetes-autoscaling-based-on-custom-metrics-without-using-a-host-port-b783ed6241ac.
5. I think, from looking at the [docs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips), that Kubernetes will not assign `externalIPs`. It leaves that task to the cluster administrator. After you have an `externalIP`, you should be able to specify it in the documented format above, and Kubernetes will balance incoming traffic on that IP to all the pods in your service.

Hope that's helpful :)

**Comment by DirectXMan12** [comment]
1-2. Several things depend on the API server being able to contact pod IPs (and nodes), but the controller-manager and scheduler should only have to contact the API server.

3. As @mattjmcnaughton mentioned, several factors affect scale time, including the metrics collection interval in Heapster/metrics-server (1 minute, but can be configured to be as low as 30s), the HPA sync interval (30s by default, IIRC, configurable on the controller manager), the HPA forbidden windows (configurable on the controller manager), and pod startup latency.

4. What @mattjmcnaughton said, except that second link is no longer valid.  There's also a walkthrough here: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md

5. In order to use a Service of type `LoadBalancer`, you need to have some external application watching for those services and provisioning load balancers (and setting the `ExternalIP` field).  In public clouds, this is often done by the cloud infrastructure.  In private clouds, you'll need to set something up yourself.  There are several existing solutions available, IIRC

**Comment by varuntalus** [comment]
@DirectXMan12 , @mattjmcnaughton 

Thanks a lot for your comments. I will try these and come back in case of any issues.

**Comment by varuntalus** [comment]
@DirectXMan12 
I tried to follow the links which you provided for Custom Metrics set-up.

I enabled the Aggregator Layer on the API Server and configured the Controller Manager to use Custom Metrics.

Next I tried to deploy the Prometheus Monitoring system. But I got the below error while deploying:

**_"error: unable to recognize "sample-prometheus-instance.yaml": no matches for monitoring.coreos.com/, Kind=Prometheus"_**

How can we resolve this issue? We do not have access to CoreOS API versions. How to use this in our K8s cluster? Please let me know if there are any additional steps which I need to follow before deploying Prometheus Monitoring system.

**Comment by DirectXMan12** [comment]
Sounds like you're not using the walkthrough I linked to, but the Bitnami one.  In that case, you'd need to set up the Prometheus Operator first.

**Comment by DirectXMan12** [comment]
If you have specific adapter problems, please file a bug against the Prometheus custom metrics adapter repository, and not here on the main Kubernetes bug tracker.

**Comment by max-rocket-internet** [comment]
I think I have the same issue here except that pod autoscaling DOES work.

Kubernetes version: 1.8.4
Platform: AWS, deployed with kops 1.8.0
Heapster version: `k8s.gcr.io/heapster:v1.5.1`

I was using the [default kops heapster](https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.7.0.yaml) but tried a later version to see if it fixes the probme. I installed the later version of heapster using helm:

```
helm install stable/heapster --namespace kube-system --name heapster --set image.tag=v1.5.1 --set rbac.create=true
```

I see these events on every `hpa` resource:

```
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedComputeMetricsReplicas  29m                horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
  Warning  FailedGetResourceMetric       29m                horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
  Warning  FailedGetResourceMetric       29m                horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("unknown") has prevented the request from succeeding (get services http:heapster:)
  Warning  FailedComputeMetricsReplicas  29m                horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("unknown") has prevented the request from succeeding (get services http:heapster:)
  Warning  FailedGetResourceMetric       28m (x26 over 5d)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  28m (x26 over 5d)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
  Normal   SuccessfulRescale             10m (x3 over 18h)  horizontal-pod-autoscaler  New size: 2; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             6m (x8 over 20h)   horizontal-pod-autoscaler  New size: 3; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             2m (x3 over 19h)   horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
```

Logs from `heapster`:

```
$ kubectl -n kube-system logs heapster-heapster-7bd988f7fc-746nk heapster
I0228 09:31:45.148881       1 heapster.go:78] /heapster --source=kubernetes.summary_api:''
I0228 09:31:45.148930       1 heapster.go:79] Heapster version v1.5.1
I0228 09:31:45.149096       1 configs.go:61] Using Kubernetes client with master "https://100.64.0.1:443" and version v1
I0228 09:31:45.149112       1 configs.go:62] Using kubelet port 10255
I0228 09:31:45.149717       1 heapster.go:202] Starting with Metric Sink
I0228 09:31:45.156126       1 heapster.go:112] Starting heapster on port 8082
W0228 09:42:25.000397       1 manager.go:152] Failed to get all responses in time (got 3/4)
E0228 09:44:12.239161       1 manager.go:101] Error in scraping containers from kubelet_summary:10.0.18.25:10255: Get http://10.0.18.25:10255/stats/summary/: dial tcp 10.0.18.25:10255: getsockopt: connection timed out
```

Logs from `kube-controller-manager`:

```
I0228 09:57:38.403953       5 horizontal.go:589] Successfully updated status for staging-myapp1
I0228 09:58:07.792016       5 horizontal.go:589] Successfully updated status for staging-myapp2
I0228 09:58:07.808331       5 horizontal.go:589] Successfully updated status for staging-myapp3
I0228 09:58:08.421269       5 horizontal.go:509] Successful rescale of staging-myapp1, old size: 3, new size: 4, reason: cpu resource utilization (percentage of request) above target
I0228 09:58:08.429036       5 horizontal.go:589] Successfully updated status for staging-myapp1
I0228 09:58:08.431285       5 replica_set.go:454] Too few "default"/"staging-myapp1-fc6b5598" replicas, need 4, creating 1
I0228 09:58:08.433819       5 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"staging-myapp1", UID:"e957762c-187a-11e8-b36b-02eebcc07bb2", APIVersion:"extensions", ResourceVersion:"9523817", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set staging-myapp1-fc6b5598 to 4
I0228 09:58:08.438581       5 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"staging-myapp1-fc6b5598", UID:"e913d745-1bcd-11e8-b36b-02eebcc07bb2", APIVersion:"extensions", ResourceVersion:"9523819", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: staging-myapp1-fc6b5598-6jqjq
I0228 09:58:08.451576       5 deployment_controller.go:483] Error syncing deployment default/staging-myapp1: Operation cannot be fulfilled on deployments.extensions "staging-myapp1": the object has been modified; please apply your changes to the latest version and try again
I0228 09:58:08.470903       5 deployment_controller.go:483] Error syncing deployment default/staging-myapp1: Operation cannot be fulfilled on deployments.extensions "staging-myapp1": the object has been modified; please apply your changes to the latest version and try again
```

Any ideas? The events look concerning but pod autoscaling does work.

**Comment by max-rocket-internet** [comment]
Actually, I just had a pretty large failure of the HPA due to this issue:

```
$ kubectl describe hpa staging-myapp1
Name:                                                  staging-myapp1
Namespace:                                             default
Labels:                                                app=myapp1
                                                       environment=staging
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 23 Feb 2018 10:21:21 +0100
Reference:                                             Deployment/staging-myapp1
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  186% (372m) / 40%
Min replicas:                                          1
Max replicas:                                          60
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     False   BackoffBoth         the time since the previous scale is still within both the downscale and upscale forbidden windows
  ScalingActive   True    ValidMetricFound    the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired replica count is within the acceptible range
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Normal   SuccessfulRescale             21m (x6 over 1d)  horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             16m               horizontal-pod-autoscaler  New size: 6; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             12m               horizontal-pod-autoscaler  New size: 9; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             8m (x2 over 1h)   horizontal-pod-autoscaler  New size: 19; reason: cpu resource utilization (percentage of request) above target
  Warning  FailedGetResourceMetric       5m (x2 over 6h)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("unknown") has prevented the request from succeeding (get services http:heapster:)
  Warning  FailedComputeMetricsReplicas  5m (x2 over 6h)   horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("unknown") has prevented the request from succeeding (get services http:heapster:)
  Normal   SuccessfulRescale             1m (x13 over 5d)  horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
```

1. 19 pods with 186% utilisation
2. `failed to get cpu utilization`
3. Scale down to 1 pod 😯

**Comment by onlonely** [comment]
So am I


get hpa
```
NAME        REFERENCE              TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
deploy-27   Deployment/deploy-27   <unknown> / 85%   3         10        3          48s
```
dzqd_pdssyy01:/app/ecs/k8s#kubectl describe hpa deploy-27
```
Name:                                                  deploy-27
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           kubernetes.io/change-cause=kubectl autoscale Deployment deploy-27 --min=3 --max=10 --cpu-percent=85 --record=true
CreationTimestamp:                                     Thu, 01 Mar 2018 16:31:03 +0800
Reference:                                             Deployment/deploy-27
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 85%
Min replicas:                                          3
Max replicas:                                          10
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Warning  FailedGetResourceMetric       26s   horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  26s   horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by MaciekPytel** [comment]
@max-rocket-internet Note that the scale down to 1 replica happened 4 minutes after failing to get utilization (based on event timings), so they're not necessarily related. HPA will not perform any action if it can't get utilization. 
Transient problems with getting metrics are common immediately after pod is created and during/after heapster restart. I guess would also happen in case of any other problem with heapster, but I don't know much about heapster internals.

**Comment by max-rocket-internet** [comment]
OK thanks for the info @MaciekPytel !

**Comment by max-rocket-internet** [comment]
I've seen this again today:
1. Scaling up
2. `unable to get metrics for resource`
3. Sharp scale down
4. Scale back up again.

```
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             30m (x5 over 5d)   horizontal-pod-autoscaler  New size: 2; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             25m (x8 over 6d)   horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             21m (x2 over 6d)   horizontal-pod-autoscaler  New size: 8; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             17m                horizontal-pod-autoscaler  New size: 16; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale             13m                horizontal-pod-autoscaler  New size: 28; reason: cpu resource utilization (percentage of request) above target
  Warning  FailedComputeMetricsReplicas  9m (x61 over 10d)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedGetResourceMetric       9m (x61 over 10d)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Normal   SuccessfulRescale             7m                 horizontal-pod-autoscaler  New size: 15; reason: All metrics below target
  Normal   SuccessfulRescale             3m                 horizontal-pod-autoscaler  New size: 30; reason: cpu resource utilization (percentage of request) above target
```

Maybe the sharp scale down from 28 > 15 is not related but this was during a load test so load should be constant and not fluctuating at all.

**Comment by DirectXMan12** [comment]
this sounds like not an HPA issue, at this point, but probably a metrics server issue.  We'd need to see logs from metrics-server, and/or controller-manager logs

**Comment by iiitux** [comment]
referenced https://github.com/kubernetes/kubernetes/issues/57673   #issue 
set kube-controller-manager startup parameter --horizontal-pod-autoscaler-use-rest-clients=false to slove the problem。

**Comment by DirectXMan12** [comment]
@iiitux that only solves the issue if you're not running metrics-server, and are instead running Heapster.

**Comment by integrii** [comment]
This is a two stage issue in my environment.

First, the breakage above was due to a missing route to the heapster pod from the api server pods.  You can see this in the error I posted before.   I tracked this down to WeaveNet failing to create the proper routes on some nodes in the overlay network (typical weave net instability).

After fixing this problem, HPAs started working and `system:admin` users can again use `kubectl top pods`.

However, I now seem to have a permissions issue for non-admin users.  Even with permissions to `list`, `get`, and `watch` `services`, users are still unable to use `kubectl top pods`.

Users get the following error:
```
Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"http:heapster:\" is forbidden: User \"USER@COMPANY.com\" cannot get services/proxy in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"http:heapster:","kind":"services"},"code":403}
```

Strangely, the same user can `list`, `describe`, and `get` all services in the `kube-system` namespace.  I also don't believe there is a proxy RBAC control limiting things here....

**Comment by integrii** [comment]
@bidyut1990 For us, the HPA issue was due to `weave-net` (our CNI) exploding underneath and causing select connectivity problems.  Our other issue was running `kubectl top pods` didn't work for non-admins.  That is apparently "better" in newer versions of Kubernetes, so we just deal with it for now.

**Comment by bidyut1990** [comment]
@integrii Oh ok . Thanks for getting back!!. I am trying to make it work by changing a particular parameter(--horizontal-pod-autoscaler-use-rest-clients) in kube-controller-manager manisfest. Lets see if that works. Referred to https://github.com/kubernetes/kubernetes/issues/57673
