### ISSUE TITLE
[PodSecurityPolicy] "MayRunAs" strategies

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#56173]
/kind feature

For strategies governing optional fields (e.g. SupplementalGroups & FSGroup) we should have an strategy that enforces allowed options without setting the defaults. E.g. `MayRunAs` - If a supplemental group is set on the pod spec, it must be in the allowed range, if no supplemental group is set, it is left unset.

**Comment by parlakisik** [comment]
If nobody is working in this case . i can take it .

**Comment by tallclair** [comment]
@parlakisik thanks, go for it!

**Comment by php-coder** [comment]
@parlakisik Hi, could you update the current status of this? Are you working on this? Are you still would like to implement this? Thanks!

**Comment by parlakisik** [comment]
@php-coder Hi , I didn't have time to test my code. I am still interested in implementing this one .

**Comment by php-coder** [comment]
@parlakisik There is a PR for that feature already: https://github.com/kubernetes/kubernetes/pull/65135 JFYI.

**Comment by parlakisik** [comment]
@php-coder  agh , i forgot to send merge request. thanks for information. i will be more quicker next time.

**Comment by parlakisik** [comment]
@php-coder  is this feature merged ? can i push my code ? 
what is the status about other task ?

**Comment by php-coder** [comment]
@parlakisik the code is already here (see #65135) but it's not merged yet.

**Comment by parlakisik** [comment]
thats great . thanks.
