### ISSUE TITLE
Heapster should generate pod and node lifecycle events. 

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#5617]
Heapster needs to watch pod and node status updates and generate appropriate metrics such as container restarts, oom kills, node failures, etc.

**Comment by vishh** [comment]
Heapster should watch the apiserver for node and pod status changes and convert the status changes to appropriate metrics to support alerting.
The main lifecycle events that are required for 1.0 are node failures, container restarts and container OOM kills.

**Comment by andyxning** [comment]
@vishh and updates on this issue?

**Comment by piosz** [comment]
This is out of the scope of the current Heapster. Some relevant resources:
https://github.com/kubernetes/kube-state-metrics
https://github.com/kubernetes/kubernetes/blob/master/docs/design/monitoring_architecture.md

Closing as obsolete.
