### ISSUE TITLE
Expand heapster metric backend to expose all available metrics

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#5618]
Currently heapster exposes cpu, memory and network stats. It needs to expose filesystem, diskio and container load stats. More details on the metrics can be inferred from the cadvisor API [here](https://github.com/google/cadvisor/blob/master/info/v1/container.go)

**Comment by vishh** [comment]
Exposing filesystem usage and network usage of pods is required for v1.0. The rest can be added post v1.0

**Comment by piosz** [comment]
/close
obsolete
