### ISSUE TITLE
Try to make scheduler volume binding more extendable

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56180]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 
@kubernetes/sig-scheduling-feature-requests  

**What happened**:
Before volume scheduling moves to beta, see if there's a way to make the volume binding changes more pluggable to:
* better support custom schedulers
* make it easier for other cluster-level resources to integrate into the pod scheduling flow

**Comment by bsalamat** [comment]
cc/ @vishh @yguo0905

**Comment by msau42** [comment]
It looks like scheduler has started implement [plugin hooks](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/scheduler/scheduler.go#L478) for the scheduler v2 framework.  @cofyc can you look into refactoring the volume scheduling code to use the new framework?

**Comment by msau42** [comment]
Thanks for the clarification Bobby!  I think we can still at least prototype and help find issues since volume scheduling is one of the more complicated plugins.

**Comment by cofyc** [comment]
## Design (Draft)

### Filter

Implement scheduler filter plugin in which we call FindPodVolumes to find all feasible nodes and save pre-bound PVs and pre-provisioned PVCs in pod binding cache.

### Reserve

Implement scheduler reserve plugin in which we call AssumePodVolumes to assume pre-bound PVs and pre-provisioned PVCs of selected node. 

### Pre-bind

Implement scheduler pre-bind plugin in which we call BindPodVolumes to bind pre-bound PVs and provision pre-provisioned PVCs.

If successfully, continue to bind pod.
If failed, exit scheduling cycle with non-unscheduable error.

### Clean pod binding cache

#### When pod is removed from scheduling queue

https://github.com/kubernetes/kubernetes/blob/b9631a881f327b58ff52654cbb448927226bf05a/pkg/scheduler/factory/factory.go#L598-L60

## References

- https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduling-framework.md
- https://github.com/kubernetes/community/pull/3082

**Comment by cofyc** [comment]
depdencies:

- kubernetes client: https://github.com/kubernetes/kubernetes/pull/82432
- shared informer factory: https://github.com/kubernetes/kubernetes/pull/83663

**Comment by cofyc** [comment]
another issue is how to pass `KubeSchedulerConfiguration.BindTimeoutSeconds` to volume binder plugin.
