### ISSUE TITLE
add NFS volume support for windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#56188]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Currently NFS volume is not supportd for windows. There is built-in client for NFS, but it’s limited to v2 and v3 (whereas, majority of the market has moved on to v4). So as long as there is no support for NFS v4, we could **not** start up this work in k8s.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/assign

**Comment by andyzhangx** [comment]
@PatrickLang for awareness

**Comment by PatrickLang** [comment]
/priority important-longterm

This needs to get on the Windows OS backlog, so I don't have an ETA. I'm looking for suggestions on what the workflow should be and how we should label these on the sig-windows slack

**Comment by PatrickLang** [comment]
Actually given [priority definitions](https://github.com/kubernetes/community/blob/master/contributors/devel/issues.md#define-priority) this should be:
/priority backlog

**Comment by andyzhangx** [comment]
Hi @PatrickLang Someone is asking whether nfs mount will be supported on Windows, so according to below conclusion, we will **never** support nfs mount on Windows, right?

Currently NFS volume is not supportd for windows. There is built-in client for NFS, but it’s limited to v2 and v3 (whereas, majority of the market has moved on to v4). So as long as there is no support for NFS v4, we could **not** start up this work in k8s.

**Comment by pjh** [comment]
This Microsoft support page seems to indicate that Windows Server has supported NFS v4 since 2012R2: https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview

> NFS in Windows Server includes Server for NFS and Client for NFS. A computer running Windows Server can use Server for NFS to act as a NFS file server for other non-Windows client computers. Client for NFS allows a Windows-based computer running Windows Server to access files stored on a non-Windows NFS server.
> ...
> New and changed functionality in Network File System includes support for the NFS version 4.1

So it seems that the lack of v4 client support should not be a reason that NFS volume support can't be done for Windows.

That said, my understanding is that nobody uses NFS on Windows and everybody uses SMB/CIFS instead, so we still have a good reason to not bother adding NFS volume support for Windows.

**Comment by pjmagee** [comment]
So, Kubernetes supports NFS using Windows Containers?

**Comment by andyzhangx** [comment]
> So, Kubernetes supports NFS using Windows Containers?

No, it's not implemented yet.

**Comment by andyzhangx** [comment]
reopen this issue since there is a PR(https://github.com/kubernetes/utils/pull/180) working on this issue

**Comment by andyzhangx** [comment]
use `net use` works for Windows Container on NFSv3 protocol(no official NFSv4 client is on Windows now: https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview#windows-and-windows-server-versions)
```console
Microsoft Windows [Version 10.0.17763.1339]
(c) 2018 Microsoft Corporation. All rights reserved.
azureuser@4820k8s000 C:\Users\azureuser>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
PS C:\Users\azureuser> powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
PS C:\Users\azureuser> Install-WindowsFeature NFS-Client
Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Client for NFS}
PS C:\Users\azureuser> exit
azureuser@4820k8s000 C:\Users\azureuser>net use /PERSISTENT:YES \\account.blob.core.windows.net\andyblobnfs\pvc-80e0b096-a126-4a05-a100-b957c2335e2e
The command completed successfully.

azureuser@4820k8s000 C:\Users\azureuser>mklink /D blobnfs \\account.blob.core.windows.net\andyblobnfs\pvc-80e0b096-a126-4a05-a100-b957c2335e2e
symbolic link created for blobnfs <<===>> \\account.blob.core.windows.net\andyblobnfs\pvc-80e0b096-a126-4a05-a100-b957c2335e2e

docker run -d -v C:\Users\azureuser\blobnfs:C:\mnt --name busybox e2eteam/busybox:1.29
```

**Comment by arocki7** [comment]
Is this implemented now? or yet to be implemented?

**Comment by andyzhangx** [comment]
> Is this implemented now? or yet to be implemented?

@arocki7 there is some initial work to support NFSv3 on Windows in csi-proxy, while it's not supported yet, still on-going.

**Comment by himanshuz2** [comment]
Please prioritize this. This feature is required in AKS particularly for hybrid deployments with Linux and Windows Nodes and deployments that connect cloud and on-premise.

**Comment by himanshuz2** [comment]
This Microsoft page indicates that NFSv3 is available.  I don't understand where it says it is not production ready. 
Windows supports multiple versions of the NFS client and server, depending on operating system version and family.

Operating Systems	NFS Server Versions	NFS Client Versions
Windows 7, Windows 8.1, Windows 10	N/A	NFSv2, NFSv3
Windows Server 2008, Windows Server 2008 R2	NFSv2, NFSv3	NFSv2, NFSv3
Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, Windows Server 2019, Windows Server 2022	NFSv2, NFSv3, NFSv4.1	NFSv2, NFSv3

https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview

**Comment by Mik4sa** [comment]
@andyzhangx Is there any progress here?
Can we reopen it?
