### ISSUE TITLE
pvc: glusterfs provisioner volume size

### ISSUE THREAD

**Issue by saheienko** [kubernetes/kubernetes#56192]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Continue to https://github.com/kubernetes/kubernetes/issues/55937

I've tried to migrate from Gi to G and got stuck.

Heketi creates volumes in GB ([api](https://github.com/heketi/heketi/wiki/API#volume_create)), it means 1024\*1024\*1024 ([src](https://github.com/heketi/heketi/blob/9d2ef4bbaf547f5b86055e935f1d583196a069f1/apps/glusterfs/volume_entry.go#L27)) or Gi in k8s format.

So, when I want pv/pvc with 50Gi (50\*1024\*1024\*1024 bytes), gluster plugin parses it as 54G (54\*1000\*1000\*1000 bytes) and than heketi creates volume as 54GB (54\*1024\*1024\*1024 bytes).

df output means Gi too:

```bash
$ kubectl exec -it web-0 sh
# df -hT      
Filesystem                                    Type            Size  Used Avail Use% Mounted on
10.0.0.5:vol_9b93bfd8c134ca081e1044c67d369cb3 fuse.glusterfs   54G   34M   54G   1% /usr/share/nginx/html

# df --help 
...
SIZE is an integer and optional unit (example: 10M is 10*1024*1024).  Units          
are K, M, G, T, P, E, Z, Y (powers of 1024) or KB, MB, ... (powers of 1000).         
...
``` 

It makes sense for my project. We take volume (as bytes), try to import it to k8s as pv and get such situation now:
```
volume n*1024*1024*1024 bytes -> k8s N*1000*1000*1000 -> heketi/glusterfs N*1024*1024*1024
```
or
```
volume n*GB(binary) -> k8s pvc n*Gi(binary) -> k8s pv N*G(decimal) -> glusterfs volume N*GB(binary)
```

**Comment by saheienko** [comment]
heketi parse volume size as Gi
https://github.com/heketi/heketi/blob/master/pkg/kubernetes/pv.go#L35

**Comment by gnufied** [comment]
@saheienko you are correct that Heketi allocates in chunks of GiBs but it documents incorrectly about it.  I have filed a bug with them - https://github.com/heketi/heketi/issues/915

In the meanwhile, I will open a PR for fixing it. Volume resizing has to be fixed to take into account GiB allocation as well.

**Comment by obnoxxx** [comment]
FYI: new change proposed to heketi to clarify documentation and messages to explicitly state GiB: https://github.com/heketi/heketi/pull/935

GB is just ambiguous. Most people understand (1000)^3, some (1024)^3...
