### ISSUE TITLE
[job failure] gci-gke-serial

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56214]
/priority critical-urgent
/priority failing-test
/area platform/gke
/kind bug
/status approved-for-milestone
@kubernetes/sig-gcp-test-failures 

This job has been failing since 2017-11-21.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial

- last good up: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/4382
- first bad up: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/4383
- latest bad up: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/4388
- suspect commit range: https://github.com/kubernetes/kubernetes/compare/a69f9dad9...1489d1944

My guess at the relevant error:
```
W1122 05:44:11.209] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W1122 05:44:11.210]  endTime: u'2017-11-22T05:44:09.847888679Z'
W1122 05:44:11.210]  name: u'operation-1511328415799-870d2272'
W1122 05:44:11.210]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W1122 05:44:11.210]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/329270376361/zones/us-central1-f/operations/operation-1511328415799-870d2272'
W1122 05:44:11.210]  startTime: u'2017-11-22T05:26:55.799159085Z'
W1122 05:44:11.210]  status: StatusValueValuesEnum(DONE, 3)
W1122 05:44:11.210]  statusMessage: u'All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 3 have registered. Cluster may be unhealthy.'
W1122 05:44:11.211]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/329270376361/zones/us-central1-f/clusters/e2e-4383'
W1122 05:44:11.211]  zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 3 have registered. Cluster may be unhealthy.
```

**Comment by abgworrall** [comment]
Most recent run passed; the failures are something down inside cluster creation. I'll see if there's a pattern with other GKE jobs.

**Comment by abgworrall** [comment]
Yep, pretty much every GKE job failed with the same error during that same time window.

**Comment by spiffxp** [comment]
/close
Agree, this was a GKE bug, latest run is green https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/4389 

Since this job takes ~5h to run, it takes me ~5h to see a green even after the error was fixed
