### ISSUE TITLE
Kube-aggregator can't access /swagger.json on some aggregated API servers

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#56220]
The Service Catalog API server looks at the existing RBAC rules (in the core k8s API server) to decide whether a client can access a nonResourceURL, such as `/swagger.json`. As I understand it, other API servers will use the same technique. 

The problem is that there is no `nonResourceURLs: ["/swagger.json"]` in the `system:kube-aggregator` ClusterRole. Additionally, there's no ClusterRoleBinding for the kube-aggregator in the default bootstrap policy. This prevents the aggregator from getting the OpenAPI schema from the aggregated API server.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The aggregator log shows the following:
```
Nov 22 15:09:10 minikube localkube[3220]: E1122 15:09:10.691211    3220 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 403, Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:aggregator\" cannot get path \"/swagger.json\"","reason":"Forbidden","details":{},"code":403}
```

**What you expected to happen**:
The aggregator should be able to access the OpenAPI schema of the underlying API servers.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Service Catalog API server patched with https://github.com/kubernetes-incubator/service-catalog/pull/1208
2. Examine the log of the aggregator

**Anything else we need to know?**:
I can fix this myself; I'd just like to confirm that adding the nonResourceURL and the missing ClusterRoleBinding for the aggregator is OK or not.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.8556+d1e067be1f3065-dirty", GitCommit:"d1e067be1f30654867769ae9dd9aaa2e30513c21", GitTreeState:"dirty", BuildDate:"2017-11-15T21:38:13Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
minikube version: v0.23.0

**Comment by liggitt** [comment]
`/swagger.json` was allowed to be accessed by all authenticated users in https://github.com/kubernetes/kubernetes/pull/53359

That is fixed in 1.8.2+
