### ISSUE TITLE
kubelet/cm and kubelet/stats/cadvisor cleanup

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#56227]
neither feature or kind, but more a need to refactor the package to clean-up code.

https://github.com/kubernetes/kubernetes/pull/55969#discussion_r152615610

we have to similar code blocks that basically iterate over a list of paths, and determine if the path corresponded to a pod cgroup.

After the referenced PR, the logic is scattered across two packages.  Ideally the /stats/cAdvisor package would have a common utility function that took a list of paths and returned a map of podUid to path so we don't have to understand the cgroupfs structure in two places.

/cc jingxu97

**Comment by derekwaynecarr** [comment]
/sig node
@jingxu97

**Comment by xiangpengzhao** [comment]
cc @yanxuean
