### ISSUE TITLE
[e2e] gci-gce-audit isn't run on release branches

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#56235]
@spiffxp noticed that we only run gci-gce-audit on master and there's no equivalent job for the release branches https://github.com/kubernetes/test-infra/issues/5558#issuecomment-346385580

cc @crassirostris @kubernetes/sig-auth-test-failures 

I think we probably just want to run the job on the 1.9 release branch for 1.9 until we figure out how to enable it for all e2e tests (https://github.com/kubernetes/kubernetes/issues/56210).

**Comment by crassirostris** [comment]
Actually https://github.com/kubernetes/kubernetes/pull/55953 would solve the immediate problem: it allows to test audit for all e2e tests in gce env

Bumping the priority and moving to 1.9 release then

**Comment by crassirostris** [comment]
https://github.com/kubernetes/kubernetes/pull/55953 needs one change, but Marian is OOO today
ETA: Nov 27
No risks

**Comment by ericchiang** [comment]
ACK.  In progress
ETA: 28/11/2017
Risks: Release branch doesn't run audit e2e tests.
