### ISSUE TITLE
Revisit volume scheduler pod cache cleanup

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56236]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig storage
/sig scheduling
/assign

**What happened**:
The scheduler volume binder keeps a cache of PV matches per pod to pass from the volume binding predicate to the assume volume function.

There are two race conditions where pod update/delete can come while we are processing the pod in scheduleOne.  To handle these 2 races, there are two calls to `factory.volumeBinder.DeletePodBindings(pod)` in `MakeDefaultErrorFunc` for very specific scenarios.  We should see if there's a simpler or more generic way to handle these race conditions.

We also have to handle the scenario where the volume binding predicate passes, but other predicates fail, causing scheduling to fail.  We don't want to clear the pod binding cache in that case because the volume binding predicate result got cached in the equivalence cache, and won't be run again.  Therefore, the pod binding cache will be empty when it comes to assume volume.

One possible way to handle this could be to search again for the matching volumes in AssumePodVolumes if the pod binding cache is empty but some volumes need binding.

**Comment by cofyc** [comment]
> There are two race conditions where pod update/delete can come while we are processing the pod in scheduleOne. To handle these 2 races, there are two calls to factory.volumeBinder.DeletePodBindings(pod) in MakeDefaultErrorFunc for very specific scenarios. We should see if there's a simpler or more generic way to handle these race conditions.

In new design (https://github.com/kubernetes/kubernetes/pull/72045), these two calls can be removed. Pod binding cache will be recreated at beginning of schedule loop, and will be cleared when pod is removed from scheduling queue.

> We also have to handle the scenario where the volume binding predicate passes, but other predicates fail, causing scheduling to fail. We don't want to clear the pod binding cache in that case because the volume binding predicate result got cached in the equivalence cache, and won't be run again. Therefore, the pod binding cache will be empty when it comes to assume volume.

In new design, because pod binding cache will not be cleared on scheduler error handler. So no races here. Cached pod binding will be used in binding operation when pod is scheduable again when other predicates passed.

**Comment by cofyc** [comment]
/close
Closing via https://github.com/kubernetes/kubernetes/pull/72045.
