### ISSUE TITLE
[Test Failure] Disk metrics appear to be off on coreos

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#56234]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report
/kind bug

**What happened**:
https://github.com/kubernetes/kubernetes/pull/54316 improved disk eviction testing to make it more precise.  For example, it expects a pod which uses 299 Mb of disk not to be evicted if it sets its limit to 300 Mi.  As shown on [the testgrid](https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-flaky-gce-e2e&include-filter-by-regex=PriorityLocalStorage), this test passes for all OS distributions except CoreOS.  I have ruled out an issue with the storage driver and backing filesystem since both COS and CoreOS use overlay backed by extfs.

**What you expected to happen**:
I expected the pod using 299Mb not to be evicted when its limit is 300 Mb.
I expected not to see this event:
`reason: 'Evicted' pod ephemeral local storage usage exceeds the total limit of containers {{314572800 0} {<nil>} 300Mi BinarySI}`

**How to reproduce it (as minimally and precisely as possible)**:
The container runs this command to use 299Mb:
`i=0; while [ $i -lt 299 ]; do dd if=/dev/urandom of=%s${i} bs=1048576 count=1; i=$(($i+1)); done; while true; do sleep 5; done`
Each iteration writes 1Mb to disk, producing a total of 299 Mb of disk usage.
The pod has `limits` set to 300Mi.
The test has the LocalStorageCapacityIsolation feature gate enabled.

**Anything else we need to know?**:
This may be a discrepancy in the `du` (which we use to measure container disk usage) or `dd`, which is used by the test to write exact quantities of disk.

**Comment by ericchiang** [comment]
cc @rphillips can you take a look at this after thanksgiving?

**Comment by rphillips** [comment]
I bumped the coreos image... going to see if it clears up the flake

**Comment by rphillips** [comment]
One more code snippet that is interesting: https://github.com/kubernetes/kubernetes/blob/87db26b50dbccc074a0d83c86adfefd5296b856e/pkg/kubelet/eviction/eviction_manager.go#L548-L551

**Comment by dashpole** [comment]
thats the container's root filesystem

**Comment by rphillips** [comment]
@dashpole correct. the feature appears to add and compare to the quota:

```
[container's used `logs` disk space] + [container's used `rootfs` disk space]
```

The reproducible steps do not take into account the rootfs space. If the quota is set to 300Mi, then the under loop count would have to take into account the rootfs space to not exceed the limit. I do not see anywhere in the tests or the reproduce steps this part of the calculation.

**Comment by dashpole** [comment]
The `rootfs` refers only to the writable layer of the container, and excludes base (image) layers.  With the provided command, the only files that are in the container's rootfs are the ones written by the command, and should amount to 299Mb.  Additionally, the container does not write any logs (through stdout), so that value should be 0.

**Comment by dashpole** [comment]
I ran a quick test on a vm with the current image, and found that both `du` and `dd` correctly wrote and measured disk space correctly.  I also tested as it inside a container, and verified that we are measuring the container's writable layer correctly.  My guess now is that it has something to do with how we calculate disk usage by logging with journald.  I am looking into it

**Comment by dashpole** [comment]
Actually, the previous comment was incorrect.  When I ran the test, I found that each file was 1028 kb instead of 1024 kb, which resulted in the command writing 300.3 Mb instead of 299 Mb.  I will change the test to require slightly less precision.

This appears to be because an empty file in coreos takes up 4 kb.  Test this by running `touch testfile && du  testfile`.  On other OS we test on, empty files use 0 kb.  This is what accounts for the difference.

**Comment by rphillips** [comment]
I tracked down an issue to the dd call. The stdout and stderr need a redirect to /dev/null to suppress the following messages:

```
1+0 records in
1+0 records out
```
Problem Line:
https://github.com/kubernetes/kubernetes/blob/24042ce6e700be767176e2e9438d6d97de69f578/test/e2e_node/eviction_test.go#L631

Fix:
```golang
return podWithCommand(volumeSource, resources, name, fmt.Sprintf("i=0; while [ $i -lt %d ];", diskConsumedMB)+" do dd if=/dev/urandom of=%s${i} bs=1048576 count=1 &>/dev/null ; i=$(($i+1)); done; while true; do sleep 5; done")

```

**Comment by rphillips** [comment]
@dashpole I PRed that fix and changed it to stderr, since the other tests seem to use stderr.

**Comment by dashpole** [comment]
leaving this open until we get a green run

**Comment by rphillips** [comment]
I'll continue to test locally to see if I find anything else.

**Comment by rphillips** [comment]
@dashpole opened PR https://github.com/kubernetes/kubernetes/pull/56641 with the help of @squeed . CoreOS defaults to using the actual size instead of the apprent size.
