### ISSUE TITLE
the pause-amd64:3.0 image on gcr.io has an empty schema2 manifest

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#56253]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
the pause-amd64:3.0 image on gcr.io has an empty schema2 manifest, which prevents is from being pulled by proxy/caches which only support V2 registries.

**What you expected to happen**:
Being able to pull `gcr.io/google_containers/pause-amd64:3.0 using a V2 manifest compatible client.

**Anything else we need to know?**:
The proxy/cahce is requesting this ` Manifest from docker-remote-google 'v2/google_containers/pause-amd64/manifests/3.0' not found`

@kubernetes/sig-node-bugs
@kubernetes/sig-release-bugs

**Comment by djsly** [comment]
@kubernetes/sig-node-bugs
@kubernetes/sig-release-bugs

**Comment by djsly** [comment]
After talking with @enisoc , he mentionned the following

> I did just notice something though. The new images we push with each release have a "Type" column that says "Docker Manifest, Schema 2". For pause-amd64, the "Type" column is empty so it could be that because we never update the pause container, maybe it's in an old manifest schema,  it contains this: `"schemaVersion": 1,`

**Comment by dixudx** [comment]
@djsly AFAIK, `gcr.io` does not support [Image Manifest Version 2, Schema 2](https://docs.docker.com/registry/spec/manifest-v2-2/) currently.

**Comment by djsly** [comment]
Im not sure which exact version x schéma X is needed. 

What I know is that we can download through the proxy/cache all other Kubernetes kube-system images, only the pause image is giving us trouble.  

Therefore, I would say that having the image available using the same format as the other kube-system images would be the request here.

**Comment by ixdy** [comment]
Yeah, we haven't updated the pause image in a while, since it doesn't really ever change. I'm not sure whether rebuilding + pushing over the existing tag is safe, or if we should bump to `3.1` or something. @tallclair thoughts?

**Comment by phsiao** [comment]
If we do rebuilding/updating the image, that would help resolve #50865 and a bunch of similar issues.

**Comment by eghobo** [comment]
@ixdy it's better/save to go with new tag

**Comment by ixdy** [comment]
@phsiao I didn't realize there were changes to the pause binary that were never actually deployed. It seems like we should probably just do that (and bump the tag).

**Comment by djsly** [comment]
@ixdy that sounds great. Any idea when the existing 3.0 tag could be pushed again?

**Comment by ixdy** [comment]
We shouldn't push over the 3.0 tag; we should push a 3.1 or 4.0 tag instead.

I'm not sure who owns the pause container who should drive this. Maybe sig-node and/or @verb?

**Comment by verb** [comment]
It seems like it should be sig-node. I'll look into it.

**Comment by verb** [comment]
The new container has been built, can you test with k8s.gcr.io/pause-amd64:3.1?

**Comment by djsly** [comment]
Its working! thanks!

I was able to pull it through our artifactory proxy

**Comment by verb** [comment]
excellent, thanks for checking.

/assign @verb
