### ISSUE TITLE
Remove json tags from pkg/client/clientcmd/api/types.go

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#5625]
Forked from #3933.

The internal representation should never be serialized, so it shouldn't have json tags, and it most certainly should depend on the presence of json tags on pkg/api/types.go. Please remove this dependency.

In particular, pkg/client/clientcmd/api/types_test.go serializes objects directly from the internal representation without applying the appropriate conversion to the v1 types.

cc @deads2k @jlowdermilk

**Comment by deads2k** [comment]
We're also using them when reflecting down and navigating through the structure for setting values and the in-memory versions are used by the template expressions.

I can take a go at this, but there will be ripples.  The most obvious is that expressions like 
```
{{ (index .clusters (index . "current-context")).server}}
```
will be replaced by
```
{{if $currContext := (index . "current-context")}}{{range .clusters}}{{ if eq .name $currContext }}{{ .cluster.server }}{{end}}{{end}}{{end}}
```

I've heard rumors that we may be relaxing the restriction on "never serialize a map".  Is that true?  Should we introduce a v2 serialization that uses maps to keep the expressions reasonable?  If we do, are we allowed to forcibly migrate from v1 to v2 serializations?

**Comment by bgrant0607** [comment]
Referring to the internal representation in such template expressions is an abstraction violation and is not the solution to your problem.

Re. maps: Current plan is to stick to lists, but please comment on #4889 with your use case.

Re. Go templates: Comment on #4348. 

Another alternative would be to use jq or something similar.

**Comment by deads2k** [comment]
@jlowdermilk I know you added the templates to enable some pieces of scripting to work nicely.  I can see a few hits in the code tree that I think I can fix.  Are there additional ripples on your side (jenkins or whatever other tools you have for automated testing)?

**Comment by jlowdermilk** [comment]
@deads2k, afaik the only affect on jenkins/automated testing is the usage in cluster/common.sh to create/read kubeconfig on kube-up.

**Comment by deads2k** [comment]
I'd like to split this into two parts.
 1. change `kubectl config view` to use the proper serialization.  This impacts all templates.  See https://github.com/GoogleCloudPlatform/kubernetes/pull/6476.
 1. update `kubectl config set` and `kubectl config unset` to navigate using the serialized version of the json tags.  I think the navigation itself should look the same externally, but internally we'll have to detect navigating through a type with a "name"/"value" slice.

**Comment by liggitt** [comment]
JSON tags were removed from all internal types except these in #38406

**Comment by alejandroEsc** [comment]
should this issue be closed?

**Comment by liggitt** [comment]
no, they still exist
