### ISSUE TITLE
Equivalence cache pod hashing doesn't work for StatefulSets with PVCs

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#56265]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
@kubernetes/sig-scheduling-bugs 
/assign

**What happened**:
When I run my e2e test on my own cluster with only my feature gates enabled, the StatefulSet test passes.  However, when the e2e test runs in CI, where all feature gates are enabled, the test is failing.  I'm suspecting there is some integration issue with other scheduling alpha features.

The symptom I see, is that my predicate is only getting run against one node for 10 minutes.  After 10 minutes, the predicate starts to get run across all the nodes again.  Also, this is hit on the second pod in the StatefulSet.  The first StatefulSet pod has no problems.

```
I1122 23:40:20.418567       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-tb58"
I1122 23:40:20.440905       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-tb58"
I1122 23:40:20.493613       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-tb58"
I1122 23:40:20.792998       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-tb58"
...
I1122 23:50:14.795526       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-tb58"
I1122 23:50:14.795964       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-master"
I1122 23:50:14.796184       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-3dbd"
I1122 23:50:14.796385       5 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-persistent-local-volumes-test-jbrwq/local-volume-statefulset-1", node "bootstrap-e2e-minion-group-k9mj"
```

**Comment by msau42** [comment]
cc @bsalamat

**Comment by msau42** [comment]
Scheduler logs are here:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/17600/artifacts/bootstrap-e2e-master/

**Comment by msau42** [comment]
I can try to manually bring up e2e clusters with different feature gate combinations, to try to figure out which other alpha feature is causing the issue.

I wonder if it is the same issue as #54370

**Comment by msau42** [comment]
If it helps, the only node that keeps repeating for the 2nd StatefulSet pod is the node that the 1st StatefulSet pod got scheduled on.

**Comment by bsalamat** [comment]
@msau42 I would suggest trying to disable PodPriority and Scheduler Equivalence Cache alpha features and see if the tests still fail.

**Comment by resouer** [comment]
It sounds like related to Equivalence Cache, I can take a look, together with #54370. While still need feedback from @msau42 after disabling equivalence class alpha feature gate.

**Comment by msau42** [comment]
When I enable EquivalenceCache, I get the same symptom as #54370.  The predicates are not called at all for the 2nd statefulset pod.  When I disable EquivalenceCache, the test passes.

**Comment by resouer** [comment]
Thanks. I will take a look at this. It seems after 1.8 the newly added volume predicate affects equivalence class cache.

**Comment by msau42** [comment]
There were no new volume predicates added in 1.8

**Comment by resouer** [comment]
I mean "Topology aware volume scheduler", it's not in 1.8?

**Comment by msau42** [comment]
Volume node predicates was added in 1.7 and topology aware volume scheduling is 1.9.  

So it seems like there were scheduler changes made in 1.8 that broke stateful sets.  I would start by looking into the naming of the statefulset pods and how you hash them.

**Comment by msau42** [comment]
@resouer @bsalamat I am looking through the equivalence cache unit tests, and `TestGetHashEquivalencePod` looks very suspicious.  If I understand the test correctly, as long as the OwnerReference is the same, then the pod will generate the same hash value even if the pod name is different.  That assumption does not work for statefulsets because each pod replica in the statefulset can have different volume specs, so the pods should not be considered the same in terms of evaluating predicates.

**Comment by msau42** [comment]
Ah yes, according to #36238, it is intended behavior.  But it doesn't work for StatefulSets.  So we need to come up with a way to handle StatefulSets.

**Comment by msau42** [comment]
One possible way is to make an exception for StatefulSets and also include the pod name when hashing.

Another possible big hammer is to invalidate all the volume predicates after `assume` and any error in `scheduleOne`, so essentially volume predicates are never cached.

**Comment by bsalamat** [comment]
@resouer, since you know eCache better than anyone else, could you please let us know what you think would be the best solution to address the problem?

**Comment by foxish** [comment]
> Another approach which I currently prefer is in assume phase, we can invalidate CheckVolumeBinding only for pod with PV defined and StatefulSet as ControllerRef. So the subsequent pods will be checked again.

This sounds like we'd be introducing even more of a special case here which won't work if we have an operator that tries to schedule pods similar to a statefulset. One potential solution here seems to me like we could teach the equivalence cache about PVCs. Is there any reason why that is not preferred?

**Comment by msau42** [comment]
Can each predicate register some function or return one more value that will determine if the predicate should be cached?  That keeps it more pluggable.  Then we can just have all the volume predicates return 'no caching' for now.  Considering this is still an alpha feature, I would rather aim for correctness rather than performance.

I would like to get this fixed in 1.8 and 1.9.  Statefulsets are the primary use case for Local PV, so the feature is currently not functional in alpha clusters where all the feature gates are enabled by default.  Also, the scenario of multi-zonal StatefulSets with volumes is a regression for alpha clusters.

**Comment by bsalamat** [comment]
> Can each predicate register some function or return one more value that will determine if the predicate should be cached? That keeps it more pluggable. Then we can just have all the volume predicates return 'no caching' for now. Considering this is still an alpha feature, I would rather aim for correctness rather than performance.

This is something that we need to do, at the same time this is not a great solution for the problem in hand. The PV predicate is applied to all types of pods and is cache-able for all pod except StatefulSets. Disabling caching it for all types of pods is not ideal.
In my opinion, our hashing for pods must be changed to include PVCs. This is inline with what @foxish suggested.

**Comment by msau42** [comment]
Ah, I see.  If you include the UIDs of all the Pod's PVCs in the hash, then each Statefulset pod is going to have a different hash, while each ReplicaSet pod is going to have the same hash.  And this will also work for pods created by operators as well.  Yes, this sounds much better.

**Comment by resouer** [comment]
Sure, I will send out a fix immediately.

**Comment by msau42** [comment]
ACK.  Ready to merge
ETA: 12/5/2017
Risks: Fix required changing volume predicate ecache invalidation a bit
