### ISSUE TITLE
Scheduler should delete a node from its cache if it gets "node not found" error

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#56261]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In case scheduler misses a node delete event, or cleaning the node from scheduler cache errors out, node will stay in scheduler cache forever and scheduler will try to schedule pods on it and keeps seeing an error similar to:

E1123 00:00:00       7 factory.go:913] Error scheduling namespace pod-1: node 'node-xyz' not found; retrying

When scheduler sees these "not found" errors for a node, it should delete the node from its cache. In order to tolerate transient errors, it is better if it deletes the node when it keeps seeing this error multiple times and over some period of time.

/sig scheduling

**Comment by wackxu** [comment]
I can help fix it.

**Comment by JorritSalverda** [comment]
In all my Kubernetes controllers I back up watch handlers with a full scan every now and then to reconciliate as a safety net. I guess that would help with this kind of errors as well. Thanks for looking into this.

**Comment by bsalamat** [comment]
@JorritSalverda Thanks for the suggestion. That sounds like a better approach. I think we should have periodic full scan to deal with similar scenarios. We should probably do it for all cached objects, not just nodes.

**Comment by wackxu** [comment]
@bsalamat @JorritSalverda Sorry, I do not know that how we can do periodic full scan because `sharedInformer`  seems has not `relist` function. and it consumes a lot of resources for doing periodic full scan also.

**Comment by JorritSalverda** [comment]
Okay, just removing the node from the cache - like you suggested - is then probably the most straightforward way to do it.

**Comment by bsalamat** [comment]
I also suspected that periodic resync would be prohibitively expensive, but I don't have any concrete numbers. If it is not acceptable, as @JorritSalverda said, we can stick to the first solution of removing the node when scheduler faces a "node not found" error. We should not remove the node right away. I'd suggest trying again to get the node and if the node is still not found, then remove it from the scheduler cache.
Doing the same thing for Pods would be useful too, but that would be a separate PR.

**Comment by timothysc** [comment]
Closing from merge of #56622
