### ISSUE TITLE
CloudNodeController should use patch to update node

### ISSUE THREAD

**Issue by karataliu** [kubernetes/kubernetes#56276]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In method AddCloudNode of CloudNodeController, there are some calls through cloud provider, e.g. InstanceID, GetZoneByProviderID. The cloud provider implementations would often involve network I/O, thus might result in timeout or failure.

The code calling cloud provider lies between the fetch of node object https://github.com/kubernetes/kubernetes/blob/e9f7970caa586d2f0b58c99cde807ab036cd128c/pkg/controller/cloud/node_controller.go#L296
and the update of node object.
https://github.com/kubernetes/kubernetes/blob/e9f7970caa586d2f0b58c99cde807ab036cd128c/pkg/controller/cloud/node_controller.go#L366

During the gap, the node status could be also updated by others, and later the update call would fail.
In this case the node's cloudprovider taint flag would not be removed.

**What you expected to happen**:
CloudNodeController should be able to update node as long as there is no conflict.

**How to reproduce it (as minimally and precisely as possible)**:
A quick repro is to add code to sleep for a period before updating the node object.

**Anything else we need to know?**:

**Environment**:
v1.8.0

**Comment by yastij** [comment]
@karataliu - spotted this too, I'll send a quick fix. But since it's code freeze It won't make it to 1.9
