### ISSUE TITLE
Error from server (Forbidden): Forbidden (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy )

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubernetes#56277]
kube version: 1.8.3
os version: debian stretch

I can not access any logs by kubectl:
```
# kubectl logs -f kube-controller-manager-uy08-07 -n kube-system
Error from server (Forbidden): Forbidden (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy) ( pods/log kube-controller-manager-uy08-07)
```

I generate the certs manually by openssl:

```
#apiserver-kubelet-client
openssl genrsa -out apiserver-kubelet-client.key 2048
openssl req -new -key apiserver-kubelet-client.key -out apiserver-kubelet-client.csr -subj "/O=system:masters,/CN=kube-apiserver-kubelet-client"
openssl x509 -req -set_serial $(date +%s%N) -in apiserver-kubelet-client.csr -CA ca.crt -CAkey ca.key -out apiserver-kubelet-client.crt -days 365 -extensions v3_req -extfile apiserver-kubelet-client-openssl.cnf
```
```
[ v3_req ]

# Extensions to add to a certificate request

keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
```

It seems that the cert are available, have I missed anthing?

**Comment by liggitt** [comment]
Ensure the apiserver's kubelet credential has the correct permissions to access the kubelet endpoints needed to satisfy the log fetch

See https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authorization

> When running in this mode, ensure the user identified by the --kubelet-client-certificate and --kubelet-client-key flags passed to the apiserver is authorized for the following attributes:
> * verb=*, resource=nodes, subresource=proxy
> * verb=*, resource=nodes, subresource=stats
> * verb=*, resource=nodes, subresource=log
> * verb=*, resource=nodes, subresource=spec
> * verb=*, resource=nodes, subresource=metrics

As an example, GCE deployments set up this RBAC role: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/rbac/kubelet-api-auth/kubelet-api-admin-role.yaml

**Comment by KeithTt** [comment]
@liggitt How about on debian? I tried your example, but do not work.

**Comment by liggitt** [comment]
that is just the role. to grant that permission to your user you'd also need to bind the role to the apiserver's username, similar to https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/rbac/kubelet-api-auth/kube-apiserver-kubelet-api-admin-binding.yaml

Based on the error you were getting, it would be something like this:
```
kubectl create clusterrolebinding my-apiserver-kubelet-binding \
  --clusterrole=kubelet-api-admin \
  --user=kube-apiserver-kubelet-client
```

**Comment by KeithTt** [comment]
@liggitt thanks a lot, it works.

Two questions:

1、Can these information be written in the certs by openssl manually when generate certs?

2、How to get all the users before I want to grant some user? It seems there is not a `user` resource type.

**Comment by liggitt** [comment]
> Can these information be written in the certs by openssl manually when generate certs?

No, certificates authenticate a user, they do not authorize them.

> How to get all the users before I want to grant some user? It seems there is not a user resource type.

Correct. The source of authentication is intended to be external to kubernetes (via a pki, or authenticating proxy, or openid token minter, etc). See https://kubernetes.io/docs/admin/authentication/#users-in-kubernetes

> Normal users are assumed to be managed by an outside, independent service. An admin distributing private keys, a user store like Keystone or Google Accounts, even a file with a list of usernames and passwords. In this regard, Kubernetes does not have objects which represent normal user accounts. Regular users cannot be added to a cluster through an API call.

**Comment by KeithTt** [comment]
@liggitt 

I got it, `--user=kube-apiserver-kubelet-client` username was the value of `CN` in openssl command.

I will read the docs you provide detailedly. 

Thanks a lot for your time.

**Comment by liggitt** [comment]
Ah, misunderstood the question. Yes, the username pulled from the CN of the certificate is part of the cert generation process.

**Comment by KeithTt** [comment]
haha, thanks again.
