### ISSUE TITLE
kubefed init can not use namespace that already exist in the cluster

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#56281]
when i create the kubernetes controller plane in ‘default’ namespace, it failed with this reason:

> > `Creating a namespace default for federation system components...Error from server (AlreadyExists): namespaces "default" already exists`

the reason i want to use the default namespace is here [Ceph StorageClass](https://github.com/kubernetes/examples/blob/master/staging/persistent-volume-provisioning/README.md), where i want use ceph rbd as the backend of etcd, but the ceph rbd need a ceph-secret must exist at the namespace.
        So, should the kubefed allow use exist namespace?

**Comment by tengqm** [comment]
dup of kubernetes/federation#19 ?

**Comment by davidstack** [comment]
dup of kubernetes/federation#19 . i move my problem desc to kubernetes/federation#19
