### ISSUE TITLE
Detailed container stats via Kubelet API proxy returns 503 in 1.8 version

### ISSUE THREAD

**Issue by astefanutti** [kubernetes/kubernetes#56297]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

In version 1.8.0, accessing the container stats via Kubelet API proxy using the `/{namespace}/{podName}/{uid}/{containerName}` path returns 503.

**What you expected to happen**:

In versions prior to 1.8.0, the container stats were returned.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ minikube start --kubernetes-version v1.8.0
$ curl -k -H "Authorization: Bearer $(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t' | awk '$1=$1')" \
 https://$(minikube ip):8443/api/v1/nodes/minikube/proxy/stats/<namespace>/<pod_name>/<uid>/<container_name>

...

< HTTP/1.1 503 Service Unavailable
< Date: Thu, 23 Nov 2017 14:29:19 GMT
< Content-Length: 133
< Content-Type: text/plain; charset=utf-8
< 
Error: 'EOF'
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.0
- OS (e.g. from /etc/os-release): Mac OS X
- Install tools: Minikube

**Comment by astefanutti** [comment]
@kubernetes/sig-instrumentation-bugs @kubernetes/sig-node-bugs

**Comment by DirectXMan12** [comment]
does the summary API also have issues? `/stats/summary`?

**Comment by astefanutti** [comment]
The summary API works as expected. The affected endpoints are:

https://github.com/kubernetes/kubernetes/blob/e551886c5e62c3e182f211300bc22e80cd8d46e5/pkg/kubelet/server/stats/handler.go#L102-L103

**Comment by DirectXMan12** [comment]
> The summary API works as expected

Hmm... this fell of my radar a bit.  If you go directly to the node, do you get a response?

**Comment by astefanutti** [comment]
@DirectXMan12 no response either. I've created #62544 that fixes the issue. I think there has been a refactoring introduced in version 1.8 that broke the sequence of objects initialisation for that endpoint.
