### ISSUE TITLE
kubernetes support mutil ceph rbd storageclass in mutil namespace environment

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#56309]
I test pod mount volume through pvc on storageclass ceph must exist in the same namespace with secret. Now I want mutil namespace environment, so each namespace need to create its own storageclass.
kubectl create ns like
ceph osd pool create like 128
ceph auth get-or-create client.like mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=like'
I creaet ceph-secret-like in namespace like and storageclass ceph-like use pool like and secret ceph-secret-like
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: ceph-like
provisioner: kubernetes.io/rbd
parameters:
monitors: 10.110.17.56:6789,10.110.17.57:6789,10.110.17.58:6789
adminId: admin
adminSecretName: ceph-secret
adminSecretNamespace: default
pool: like
userId: like
userSecretName: ceph-secret-like
imageFormat: "1"
When I create pvc in namespace like，its status is pending, and log show like this:
Warning ProvisioningFailed 3m (x17 over 7m) persistentvolume-controller (combined from similar events): Failed to provision volume with StorageClass "ceph-like": failed to create rbd image: exit status 1, command output: 2017-11-24 03:08:55.020934 7fe5c270d780 -1 did not load config file, using default settings.
2017-11-24 03:08:55.032621 7fe5c270d780 0 librados: client.admin authentication error (1) Operation not permitted
rbd: couldn't connect to the cluster!

**Comment by sbezverk** [comment]
@like-inspur which version of kubernetes you are using? The support for secret in a different namespace got merged about 2 weeks ago. If you are using older than that version, it will not work.
