### ISSUE TITLE
kubeadm init hangs with getsockopt: connection refused. k8s=1.7.5

### ISSUE THREAD

**Issue by tzurE** [kubernetes/kubernetes#56303]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cli

**What happened**:
Try to init a k8s cluster after reset and cleanup.
I've seen more and more issues on this, but none of the solutions applies here. 
Machine is Ubuntu 16.04.

I've tried all the regular stuff other issues were suggesting :
1. Swap is off
2. cgroupfs is in the env
3. firewalld disabled

Basically, the Kube-api server pod keeps restarting with the etcd pod (watch docker ps), no idea why.
**What you expected to happen**:
Init to finish and cluster to go up
**How to reproduce it (as minimally and precisely as possible)**:
Ubuntu 16.04
kubeadm init  --pod-network-cidr=10.244.0.0/16

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.7.5
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 4.4.0-101-generic
- Install tools: kubeadm

**journalctl logs:**

Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: I1123 17:59:17.266052    8266 kuberuntime_manager.go:457] Container {Name:kube-apiserver Image:gcr.io/google_containers/kube-apiserver-amd64:v1.8.3 Command:[kube-apiserver --requestheader-allowed-names=front-proxy-client --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --requestheader-username-headers=X-Remote-User --insecure-port=0 --requestheader-group-headers=X-Remote-Group --service-cluster-ip-range=10.96.0.0/12 --service-account-key-file=/etc/kubernetes/pki/sa.pub --client-ca-file=/etc/kubernetes/pki/ca.crt --secure-port=6443 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --allow-privileged=true --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --experimental-bootstrap-token-auth=true --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-extra-headers-prefix=X-Remote-Extra- --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota --authorization-mode=Node,RBAC --advertise-address=9.151.163.60 --etcd-servers=http://127.0.0.1:2379] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[cpu:{i:{value:250 scale:-3} d:{Dec:<nil>} s:250m Format:DecimalSI}]} VolumeMounts:[{Name:k8s ReadOnly:true MountPath:/etc/kubernetes SubPath:} {Name:certs ReadOnly:false MountPath:/etc/ssl/certs SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:6443,Host:127.0.0.1,Scheme:HTTPS,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:8,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePo
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: licy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: I1123 17:59:17.267843    8266 kuberuntime_manager.go:741] checking backoff for container "kube-apiserver" in pod "kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: I1123 17:59:17.268220    8266 kuberuntime_manager.go:751] Back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: E1123 17:59:17.268484    8266 pod_workers.go:182] Error syncing pod 757e5c05c19263e8368481d88de4ab2f ("kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: E1123 17:59:17.692720    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: E1123 17:59:17.830607    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:17 tzur-k8s-master kubelet[8266]: E1123 17:59:17.831832    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: I1123 17:59:18.243584    8266 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: I1123 17:59:18.246540    8266 kubelet_node_status.go:82] Attempting to register node tzur-k8s-master
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: E1123 17:59:18.247338    8266 kubelet_node_status.go:106] Unable to register node "tzur-k8s-master" with API server: Post https://9.151.163.60:6443/api/v1/nodes: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: E1123 17:59:18.694888    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: E1123 17:59:18.832019    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:18 tzur-k8s-master kubelet[8266]: E1123 17:59:18.833057    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: E1123 17:59:19.696824    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: E1123 17:59:19.924547    8266 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'tzur-k8s-master' not found
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: W1123 17:59:19.928206    8266 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: E1123 17:59:19.928778    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: E1123 17:59:19.929065    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:19 tzur-k8s-master kubelet[8266]: E1123 17:59:19.929384    8266 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 23 17:59:20 tzur-k8s-master kubelet[8266]: E1123 17:59:20.697992    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:20 tzur-k8s-master kubelet[8266]: E1123 17:59:20.930167    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:20 tzur-k8s-master kubelet[8266]: E1123 17:59:20.931580    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:21 tzur-k8s-master kubelet[8266]: E1123 17:59:21.699121    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:21 tzur-k8s-master kubelet[8266]: E1123 17:59:21.931436    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:21 tzur-k8s-master kubelet[8266]: E1123 17:59:21.932624    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:22 tzur-k8s-master kubelet[8266]: E1123 17:59:22.447160    8266 event.go:209] Unable to write event: 'Patch https://9.151.163.60:6443/api/v1/namespaces/default/events/tzur-k8s-master.14f9c117933836b8: dial tcp 9.151.163.60:6443: getsockopt: connection refused' (may retry after sleeping)
Nov 23 17:59:22 tzur-k8s-master kubelet[8266]: E1123 17:59:22.700712    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:22 tzur-k8s-master kubelet[8266]: E1123 17:59:22.932683    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:22 tzur-k8s-master kubelet[8266]: E1123 17:59:22.933822    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:23 tzur-k8s-master kubelet[8266]: E1123 17:59:23.702489    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:23 tzur-k8s-master kubelet[8266]: E1123 17:59:23.934114    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:23 tzur-k8s-master kubelet[8266]: E1123 17:59:23.934838    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:24 tzur-k8s-master kubelet[8266]: E1123 17:59:24.704114    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:24 tzur-k8s-master kubelet[8266]: W1123 17:59:24.931117    8266 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 23 17:59:24 tzur-k8s-master kubelet[8266]: E1123 17:59:24.931683    8266 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 23 17:59:24 tzur-k8s-master kubelet[8266]: E1123 17:59:24.935126    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:24 tzur-k8s-master kubelet[8266]: E1123 17:59:24.936202    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: I1123 17:59:25.247777    8266 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: I1123 17:59:25.251763    8266 kubelet_node_status.go:82] Attempting to register node tzur-k8s-master
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: E1123 17:59:25.252719    8266 kubelet_node_status.go:106] Unable to register node "tzur-k8s-master" with API server: Post https://9.151.163.60:6443/api/v1/nodes: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: E1123 17:59:25.705344    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: E1123 17:59:25.936171    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: E1123 17:59:25.936878    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: I1123 17:59:25.961066    8266 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Nov 23 17:59:25 tzur-k8s-master kubelet[8266]: E1123 17:59:25.967240    8266 kubelet.go:1607] Failed creating a mirror pod for "etcd-tzur-k8s-master_kube-system(9ef6d25e21bb4befeabe4d0e4f72d1ca)": Post https://9.151.163.60:6443/api/v1/namespaces/kube-system/pods: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: I1123 17:59:26.268410    8266 kuberuntime_manager.go:457] Container {Name:etcd Image:gcr.io/google_containers/etcd-amd64:3.0.17 Command:[etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379 --data-dir=/var/lib/etcd] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:certs ReadOnly:false MountPath:/etc/ssl/certs SubPath:} {Name:etcd ReadOnly:false MountPath:/var/lib/etcd SubPath:} {Name:k8s ReadOnly:true MountPath:/etc/kubernetes SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:2379,Host:127.0.0.1,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:8,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: I1123 17:59:26.270494    8266 kuberuntime_manager.go:741] checking backoff for container "etcd" in pod "etcd-tzur-k8s-master_kube-system(9ef6d25e21bb4befeabe4d0e4f72d1ca)"
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: I1123 17:59:26.270985    8266 kuberuntime_manager.go:751] Back-off 5m0s restarting failed container=etcd pod=etcd-tzur-k8s-master_kube-system(9ef6d25e21bb4befeabe4d0e4f72d1ca)
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: E1123 17:59:26.271251    8266 pod_workers.go:182] Error syncing pod 9ef6d25e21bb4befeabe4d0e4f72d1ca ("etcd-tzur-k8s-master_kube-system(9ef6d25e21bb4befeabe4d0e4f72d1ca)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=etcd pod=etcd-tzur-k8s-master_kube-system(9ef6d25e21bb4befeabe4d0e4f72d1ca)"
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: E1123 17:59:26.706909    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: E1123 17:59:26.937280    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:26 tzur-k8s-master kubelet[8266]: E1123 17:59:26.938196    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:27 tzur-k8s-master kubelet[8266]: E1123 17:59:27.708754    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:27 tzur-k8s-master kubelet[8266]: E1123 17:59:27.938486    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:27 tzur-k8s-master kubelet[8266]: E1123 17:59:27.939225    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:28 tzur-k8s-master kubelet[8266]: E1123 17:59:28.709930    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:28 tzur-k8s-master kubelet[8266]: E1123 17:59:28.939947    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:28 tzur-k8s-master kubelet[8266]: E1123 17:59:28.940702    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:28 tzur-k8s-master kubelet[8266]: I1123 17:59:28.960813    8266 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
Nov 23 17:59:28 tzur-k8s-master kubelet[8266]: E1123 17:59:28.965030    8266 kubelet.go:1607] Failed creating a mirror pod for "kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)": Post https://9.151.163.60:6443/api/v1/namespaces/kube-system/pods: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: I1123 17:59:29.266342    8266 kuberuntime_manager.go:457] Container {Name:kube-apiserver Image:gcr.io/google_containers/kube-apiserver-amd64:v1.8.3 Command:[kube-apiserver --requestheader-allowed-names=front-proxy-client --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --requestheader-username-headers=X-Remote-User --insecure-port=0 --requestheader-group-headers=X-Remote-Group --service-cluster-ip-range=10.96.0.0/12 --service-account-key-file=/etc/kubernetes/pki/sa.pub --client-ca-file=/etc/kubernetes/pki/ca.crt --secure-port=6443 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --allow-privileged=true --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --experimental-bootstrap-token-auth=true --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-extra-headers-prefix=X-Remote-Extra- --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota --authorization-mode=Node,RBAC --advertise-address=9.151.163.60 --etcd-servers=http://127.0.0.1:2379] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[cpu:{i:{value:250 scale:-3} d:{Dec:<nil>} s:250m Format:DecimalSI}]} VolumeMounts:[{Name:k8s ReadOnly:true MountPath:/etc/kubernetes SubPath:} {Name:certs ReadOnly:false MountPath:/etc/ssl/certs SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:6443,Host:127.0.0.1,Scheme:HTTPS,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:8,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePo
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: licy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: I1123 17:59:29.268180    8266 kuberuntime_manager.go:741] checking backoff for container "kube-apiserver" in pod "kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: I1123 17:59:29.268537    8266 kuberuntime_manager.go:751] Back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: E1123 17:59:29.268913    8266 pod_workers.go:182] Error syncing pod 757e5c05c19263e8368481d88de4ab2f ("kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-tzur-k8s-master_kube-system(757e5c05c19263e8368481d88de4ab2f)"
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: E1123 17:59:29.711668    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: E1123 17:59:29.996364    8266 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'tzur-k8s-master' not found
Nov 23 17:59:29 tzur-k8s-master kubelet[8266]: E1123 17:59:29.999638    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:400: Failed to list *v1.Service: Get https://9.151.163.60:6443/api/v1/services?resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:30 tzur-k8s-master kubelet[8266]: E1123 17:59:30.000146    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:408: Failed to list *v1.Node: Get https://9.151.163.60:6443/api/v1/nodes?fieldSelector=metadata.name%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused
Nov 23 17:59:30 tzur-k8s-master kubelet[8266]: W1123 17:59:30.000554    8266 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Nov 23 17:59:30 tzur-k8s-master kubelet[8266]: E1123 17:59:30.000910    8266 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 23 17:59:30 tzur-k8s-master kubelet[8266]: E1123 17:59:30.712940    8266 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.151.163.60:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dtzur-k8s-master&resourceVersion=0: dial tcp 9.151.163.60:6443: getsockopt: connection refused

**Comment by vbmade2000** [comment]
@tzurE Are you still facing the same issue ?

**Comment by tzurE** [comment]
Yes. We have a 1.6 environment that is broken because of this.

**Comment by vbmade2000** [comment]
Ok. Is there a $KUBELET_NETWORK_ARGS param in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf ?

**Comment by timothysc** [comment]
Closing as stale. 

If you can repro on later versions e.g. 1.9+ please feel free to repo under https://github.com/kubernetes/kubeadm repo.

**Comment by sejushah17** [comment]
Hi ,

Is this issue resolved? I am also facing the same issue with Kubernetes version 1.10.1

Can anyone please help on this?

Regards
Sejal

**Comment by RakeshNagarajan** [comment]
Facing the same issue

**Comment by tzurE** [comment]
unresolved for us as well. we needed to clean everything and reinstall it to fix it.
