### ISSUE TITLE
ReplicaSet not spread amongst failure domains

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes#56306]
/kind bug

I create a GKE cluster with three zones, one node in each.  I create a Deployment/ReplicaSet with 3 replicas with kubectl run.

**What happened**: Two pods end up on node 1 and one pod on node 2.

**What you expected to happen**: One pod each on three nodes

**How to reproduce it (as minimally and precisely as possible)**:
Use kubectl run to create a deployment.  (If you don't get this outcome, delete it and try again until you do.)

<pre>
$ kubectl get nodes --show-labels
NAME                                             STATUS    AGE       VERSION        LABELS
gke-gke-highlights-regional-pool-62b7bad4-26v0   Ready     10m       v1.7.8-gke.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=n1-standard-1,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=regional-pool,<b>failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-c</b>,kubernetes.io/hostname=gke-gke-highlights-regional-pool-62b7bad4-26v0
gke-gke-highlights-regional-pool-884432cb-qw4n   Ready     10m       v1.7.8-gke.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=n1-standard-1,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=regional-pool,<b>failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-b</b>,kubernetes.io/hostname=gke-gke-highlights-regional-pool-884432cb-qw4n
gke-gke-highlights-regional-pool-ca7f6c0d-dbsr   Ready     8m        v1.7.8-gke.0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=n1-standard-1,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=regional-pool,<b>failure-domain.beta.kubernetes.io/region=europe-west1,failure-domain.beta.kubernetes.io/zone=europe-west1-d</b>,kubernetes.io/hostname=gke-gke-highlights-regional-pool-ca7f6c0d-dbsr

$ kubectl run hello-web --image=gcr.io/google-samples/hello-app:1.0 --port=8080 --replicas=3
deployment "hello-web" created

$ kubectl describe pod | grep Node:
Node:		gke-gke-highlights-regional-pool-ca7f6c0d-dbsr/10.132.0.14
Node:		gke-gke-highlights-regional-pool-884432cb-qw4n/10.132.0.15
Node:		gke-gke-highlights-regional-pool-ca7f6c0d-dbsr/10.132.0.14

</pre>
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.8 and 1.8.3:

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-gke.0", GitCommit:"86d3ac5eaf57223302c95e7d9fc1aeff55fb0c15", GitTreeState:"clean", BuildDate:"2017-11-08T21:42:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): COS

**Comment by bsalamat** [comment]
To ensure spreading, you need to provide anti-affinity for your pods. Without anti-affinity, there is no guarantee that your pods will be spread among available nodes/zones/etc.

**Comment by craigbox** [comment]
This feature predates anti-affinity?

**Comment by davidopp** [comment]
> To ensure spreading, you need to provide anti-affinity for your pods. Without anti-affinity, there is no guarantee that your pods will be spread among available nodes/zones/etc.

Specifically, requiredDuringSchedulingIgnoredDuringExecution if you want a guarantee. Even doing preferredDuringSchedulingIgnoredDuringExecution isn't a guarantee.

> This feature predates anti-affinity?

Automatic best-effort spreading by set (ReplicaSet etc.) predates anti-affinity.

BTW the reason why these things aren't guaranteed is that the scheduler decides which node is best for a pod by adding up a bunch of different criteria, and spreading is just one factor, so it can be outweighed by one or more other factors (like trying to balance resource usage, trying to run on a node that already has the container image cached, etc.).

**Comment by davidopp** [comment]
BTW the documentation on this stuff is [here](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/)

**Comment by ravisantoshgudimetla** [comment]
@craigbox Can you please let us know, if the issue still persists with pod anti-affinity with requiredDuringSchedulingIgnoredDuringExecution flag? If not, can you close this issue?

**Comment by craigbox** [comment]
Setting anti-affinity works as expected.
However, https://kubernetes.io/docs/admin/multiple-zones/#pods-are-spread-across-zones doesn't make any mention of it.

That should be updated to reflect current state.

/remove-lifecycle stale

**Comment by hakman** [comment]
Not sure if this is the right place to ask, but the issue seems related to one of the e2e tests failing in a Multi-AZ setup: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-misc-ha-uswest2/1232000858179244033.

Any thoughts about the `[sig-scheduling] Multi-AZ Clusters should spread the pods of a replication controller across zones`?

**Comment by johngmyers** [comment]
@hakman That flake is probably #89178

**Comment by liggitt** [comment]
@ahg-g is this still an issue? I thought this was implemented

**Comment by craigbox** [comment]
@ahg-g You're absolutely right.  I wonder why I stopped getting notifications for this?

Closed fixed!
