### ISSUE TITLE
kubedns Unauthorized getting initial ConfigMap, failed to list endpoints

### ISSUE THREAD

**Issue by mjj29** [kubernetes/kubernetes#56304]
/kind bug

**What happened**:

Started up a clean kubernetes environment using minikube. DNS services are not available. Logs on the kubedns container:

I1123 16:41:41.217180       1 dns.go:48] version: 1.14.4-2-g5584e04
I1123 16:41:41.218130       1 server.go:66] Using configuration read from ConfigMap: kube-system:kube-dns
I1123 16:41:41.218177       1 server.go:113] FLAG: --alsologtostderr="false"
I1123 16:41:41.218195       1 server.go:113] FLAG: --config-dir=""
I1123 16:41:41.218203       1 server.go:113] FLAG: --config-map="kube-dns"
I1123 16:41:41.218208       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I1123 16:41:41.218213       1 server.go:113] FLAG: --config-period="10s"
I1123 16:41:41.218219       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I1123 16:41:41.218224       1 server.go:113] FLAG: --dns-port="10053"
I1123 16:41:41.218234       1 server.go:113] FLAG: --domain="cluster.local."
I1123 16:41:41.218241       1 server.go:113] FLAG: --federations=""
I1123 16:41:41.218247       1 server.go:113] FLAG: --healthz-port="8081"
I1123 16:41:41.218252       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I1123 16:41:41.218257       1 server.go:113] FLAG: --kube-master-url=""
I1123 16:41:41.218266       1 server.go:113] FLAG: --kubecfg-file=""
I1123 16:41:41.218271       1 server.go:113] FLAG: --log-backtrace-at=":0"
I1123 16:41:41.218281       1 server.go:113] FLAG: --log-dir=""
I1123 16:41:41.218286       1 server.go:113] FLAG: --log-flush-frequency="5s"
I1123 16:41:41.218291       1 server.go:113] FLAG: --logtostderr="true"
I1123 16:41:41.218296       1 server.go:113] FLAG: --nameservers=""
I1123 16:41:41.218304       1 server.go:113] FLAG: --stderrthreshold="2"
I1123 16:41:41.218309       1 server.go:113] FLAG: --v="2"
I1123 16:41:41.218314       1 server.go:113] FLAG: --version="false"
I1123 16:41:41.218321       1 server.go:113] FLAG: --vmodule=""
I1123 16:41:41.218651       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I1123 16:41:41.218973       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I1123 16:41:41.218986       1 dns.go:147] Starting endpointsController
I1123 16:41:41.218992       1 dns.go:150] Starting serviceController
I1123 16:41:41.219676       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1123 16:41:41.219687       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E1123 16:41:41.235769       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Unauthorized
E1123 16:41:41.235852       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Unauthorized
E1123 16:41:41.235896       1 sync_configmap.go:86] Error getting ConfigMap kube-system:kube-dns err: Unauthorized
E1123 16:41:41.235905       1 dns.go:183] Error getting initial ConfigMap: Unauthorized, starting with default values
E1123 16:41:41.236814       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: Unauthorized
I1123 16:41:41.736168       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1123 16:41:42.236351       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

Exec ping kubernetes:

ping: bad address 'kubernetes'

**What you expected to happen**:

No errors in kubedns logs, containers can resolve services.

**How to reproduce it (as minimally and precisely as possible)**:

Started minikube with --vm-driver=none on a server with docker 17.09 installed. I can reproduce it on this machine (I removed all the k8s containers/images and the MINIKUBE_HOME then started again so everything was installed from scratch). However, I have another machine which _should_ be identical on which kubernetes in this configuration works fine, so I don't know why it reproduces here

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Minikube version 0.23

- Cloud provider or hardware configuration:
Local server running in a vmware image

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

- Kernel (e.g. `uname -a`):
Linux x-vm-amd64-rhel7-certs.apama.com 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mjj29** [comment]
/area dns
I'm afraid I don't know what sig label I should have, but looks like there's an appropriate area tag, so adding that

**Comment by liggitt** [comment]
What version of kube-dns are you running? I didn't think kube-dns did configmap lookups any longer

**Comment by mjj29** [comment]
Whatever came with what as far as I can tell is the most recent version of minikube. I didn't do anything to install it and I don't know how to change to another version

**Comment by mjj29** [comment]
Hi, does anyone have any more information on this? I'd really like to get my DNS working. I literally have no idea where to start looking. My guess is that the DNS kubelet doesn't have access to my authorization key for the minikube API - but I don't know where to look for the configuration to make that work

**Comment by mjj29** [comment]
Hi, further help would be useful. I've just installed another server in exactly the same way. This time I get this error:

Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: x509: certificate is valid for 127.0.0.1, 10.0.0.1, not 10.96.0.1

Now, on the working server my kubernetes service looks like: kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   26d
but on the non-working server it looks like: kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   16h
this suggests what the issue is - the kubernetes service is using a different IP than its certificate was created for the problem is that I have no idea what the difference between the two systems is. For reference the .minikube directory doesn't contain any reference to 10.96 in it and appears to be identical so if someone could tell me how to either a. regenerate the certificate with the correct address (I don't even know where it is), b. change the IP that the kubernetes service binds to or c. disable certificate verification that would be really useful, thanks

**Comment by mjj29** [comment]
Bump! I would really love some help with this. Thanks.

**Comment by mjj29** [comment]
Further update: after upgrading to the latest (0.24.1) minikube the DNS is running fine - except it's bound to 10.0.0.10. Explicitly looking up on that IP works fine, but containers get 10.96.0.10 written to their resolv.conf, so they can't look them up. Any idea why DNS might bind to 10.0/16 but pods think it's on 10.96/16 ?

**Comment by mjj29** [comment]
aaaand now I'm back to this:

E0102 16:55:29.329539       1 sync_configmap.go:86] Error getting ConfigMap kube-system:kube-dns err: Unauthorized
E0102 16:55:29.329549       1 dns.go:183] Error getting initial ConfigMap: Unauthorized, starting with default values
E0102 16:55:29.330219       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: Unauthorized
E0102 16:55:29.332126       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Unauthorized
E0102 16:55:29.332261       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Unauthorized

**Comment by liggitt** [comment]
for config, kube-dns can either
1. read config from a configmap mounted into the pod (via the `--config-dir` flag, as used in https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube-dns.yaml.in#L129)
2. actively make API calls to read config map objects directly (via the `--config-map` and `--config-map-namespace` flags)

the default role does not grant any read permissions for approach 2. if you want your kube-dns pod to read configmaps from the API, you need to grant the pod's service account permission to read the config map you specified.

**Comment by mjj29** [comment]
I shall leave this closed because I've found an independent work around, but I don't believe that addresses any of my issues. My expectation is that the DNS service will work out of the box. I don't _want_ my kube-dns pod to do anything in particular about configuration - but I do expect it to be able to serve DNS. Clearly something is misconfigured in this case, but I haven't tried to give it any configuration to be misconfigured. If I need to configure it to work at all then I've not seen anything to tell me what configuration it needs, nor do I know where I should provide the --config-dir or --config-map arguments. This isn't a pod I started myself, it came with the system.

Thanks for your reply, however.

**Comment by liggitt** [comment]
If that is how minikube set up the DNS pod, then I would recommend reporting an issue to minikube that they're out of the box configuration does not work

**Comment by leoudimg** [comment]
> If that is how minikube set up the DNS pod, then I would recommend reporting an issue to minikube that they're out of the box configuration does not work

This issue happens in bare metal installation too... so I think this is not a issue from minkube
