### ISSUE TITLE
Kubelet sometimes hangs on startup

### ISSUE THREAD

**Issue by mcginne** [kubernetes/kubernetes#56300]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After rebooting a host (Which had been previously cordoned and drained) I notice that sometimes the node stays `NotReady`. If I look at the kubelet logs it looks like kubelet has hung early on in initialisation. The logs show it stopped at the following point:

```
Nov 23 15:01:40  kubelet.service[1375]: I1123 15:01:40.777556    1375 feature_gate.go:156] feature gates: map[]
Nov 23 15:01:40  kubelet.service[1375]: W1123 15:01:40.777734    1375 server.go:289] --cloud-provider=auto-detect is deprecated. The desired cloud provider should be set explicitly
Nov 23 15:01:40  kubelet.service[1375]: I1123 15:01:40.804425    1375 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.service"
```

If I restart Kubelet it initialises fine straight away.

**What you expected to happen**:

Kubelet initialise straight away after a host reboot.

**How to reproduce it (as minimally and precisely as possible)**:
Cordon - Drain - then reboot node (I'm using sudo reboot -f)

However the issue only occurs probably 33% of the time - other times kubelet starts normally, so probably some timing issue.

**Anything else we need to know?**:
I used kill -3 to kill the process - so will attach the logs that include the stack traces when it is hung.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-1+2e77a3c658dd5d", GitCommit:"2e77a3c658dd5df223ca52b927ba2bbd80b24377", GitTreeState:"clean", BuildDate:"2017-10-20T08:11:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-1+2e77a3c658dd5d", GitCommit:"2e77a3c658dd5df223ca52b927ba2bbd80b24377", GitTreeState:"clean", BuildDate:"2017-10-20T08:11:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Running on IBM cloud VMs (16 core 32GB memory)
- OS (e.g. from /etc/os-release):
16.04.2 LTS (Xenial)
- Kernel (e.g. `uname -a`):
4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/sig api-machinery

**Comment by mcginne** [comment]
Logs attached:
[kubeletHung_trim.txt](https://github.com/kubernetes/kubernetes/files/1499727/kubeletHung_trim.txt)

**Comment by tengqm** [comment]
looks like your rkt engine is down

**Comment by tengqm** [comment]
/remove-sig api-machinery
@kubernetes/sig-node-bugs
/sig node

**Comment by mcginne** [comment]
Strange you say rkt engine is down - we're using docker to run containers - don't believe we configured rkt for anything..

**Comment by tallclair** [comment]
That's a cAdvisor bug - it spits out a warning about not being able to connect to rkt when not running rkt. You can ignore it.
