### ISSUE TITLE
runtime.Unstructured.UnstructuredContent() is easy to misuse

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#56316]
**What happened**:
In #51526 I introduced an optimization - do a deep copy instead of to and from JSON roundtrip to convert anything that implements `runtime.Unstructured`. I then discovered that the method that is used there `UnstructuredContent()` in both `Unstructured` and `UnstructuredList` may mutate the original object.
https://github.com/kubernetes/kubernetes/blob/160cf97fa426dcf355357a81e7824840afd52bcc/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L83-L88
https://github.com/kubernetes/kubernetes/blob/160cf97fa426dcf355357a81e7824840afd52bcc/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured_list.go#L55-L72
This is problematic because previously (before #51526) there was no mutation and because this is unexpected and may lead to data races - it is bad behaviour to mutate original object when you just want a copy of it.
**This issue was fixed by #55871**.

However the underlying issue is not fixed here - `UnstructuredContent()` is brittle and dangerous. Method name does not imply that it mutates data when you call it. And godoc does not mention that either:
https://github.com/kubernetes/kubernetes/blob/e7e313d6d23f4e4619944049a265270353c19cf8/staging/src/k8s.io/apimachinery/pkg/runtime/interfaces.go#L233-L249
Something needs to be done about it IMO.

This method is misused in these places (mutation side effect is not intended):
https://github.com/kubernetes/kubernetes/blob/8442a118ea91c1ccb6a4b2d1505359732608b5cf/pkg/printers/jsonpath.go#L117-L152
https://github.com/kubernetes/kubernetes/blob/091a9dfc35a10637c464b7f5e1e2ec2d25d7067f/pkg/printers/customcolumn.go#L203-L242
https://github.com/kubernetes/kubernetes/blob/d2a62fd42234a96cbab2dbcf402c168c59b41784/pkg/printers/humanreadable.go#L685-L742

Also `UnstructuredContent()` implementation in `UnstructuredList` does not implement the behaviour required by godoc in `runtime.Unstructured`.

**What you expected to happen**:
There should be a method that returns the current unstructured contents without mutation and perhaps not providing the write-through effect.

/kind bug
/sig api-machinery

**Comment by rchakra3** [comment]
Is this still required and could I work on it? I'm looking for something to work on as a new contributor :)

**Comment by nikhita** [comment]
> Is this still required and could I work on it?

Yes and yes! :)

**Comment by rchakra3** [comment]
Perfect, I'll get started on it!

**Comment by rchakra3** [comment]
@ash2k @nikhita I've got https://github.com/kubernetes/kubernetes/pull/57713 out. I'd appreciate a review :)
