### ISSUE TITLE
unable to connect Pod network to mongodb running at outside kubernetes cluster at host network

### ISSUE THREAD

**Issue by dpprabhuindia** [kubernetes/kubernetes#56318]
Hi,

I request anyone help to fix the above said issue, I have deployed my nodejs applications on kubernetes cluster(running on Vagrant virtualbox with 1 master and 3 nodes) successfully but with mongodb server via public domain name instead using local LAN IP address CIDR 10.0.2.0/24.

My diagnostics I able to ping/connect mongodb server 10.0.2.34 from master and node VMs with public network (10.0.2.0/24) on Virtual Box, but not from pods.

I have tried with calico and flannel kubernetes dns crashes.

I found that this can be fixed with this steps

1. Flannel CNI enabled
2. kube-proxy set to --masquerade-all
3. Run a pod on the flannel network and try to reach an external IP.

Am new to kubernetes and pod networking, I request anyone here help me on how to do above steps please

**Comment by dpprabhuindia** [comment]
Hi,

Am new to github, can you please help me to add sig list/group

**Comment by thockin** [comment]
I think you need to file this against flannel, or whatever you used to install it.
