### ISSUE TITLE
k8s v1.6.1 support GPU isolation?

### ISSUE THREAD

**Issue by fengyu10** [kubernetes/kubernetes#56310]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
kubernetes node have two nvidia GPU,
create pod use file:
apiVersion: v1
kind: ReplicationController
metadata: {name: gputest, namespace: hdp-teu-dia}
spec:
  replicas: 1
  template:
    metadata:
      labels: {component: gputest}
    spec:
      containers:
      - command: [/bin/bash, -c, touch /workspace/gputest.$(hostname).syslog && tail -f /workspace/gputest.$(hostname).syslog]
        env:
        - {name: ALLOCATE_GPU_NUM, value: '1'}
        image: 10.126.98.3:5000/tensorflow.hadoop:1.2.1-gpu-py2-58cluster
        lifecycle:
          postStart:
            exec:
              command: [/bin/bash, -c, echo postStart]
        name: gputest
        ports:
        - {containerPort: 8888}
        resources:
          limits: {alpha.kubernetes.io/nvidia-gpu: '1', cpu: '2', memory: 2G}
          requests: {cpu: '2', memory: 2G}
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /usr/local/nvidia, name: driver, readOnly: true}
      nodeSelector: {type: gpu}
      volumes:
      - hostPath: {path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.26}
        name: driver

go in container run GPU task, 
GPU resource use:
![image](https://user-images.githubusercontent.com/31887880/33194482-3661f16a-d10b-11e7-947e-d932d99e0e8a.png)

Intercept part log:
2017-11-24 03:32:14.346796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:08:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-11-24 03:32:14.555657: W tensorflow/stream_executor/cuda/cuda_driver.cc:523] A non-primary context 0x8c65450 exists before initializing the StreamExecutor. We haven't verified StreamExecutor works with that.
2017-11-24 03:32:14.556956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:84:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-11-24 03:32:14.557008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 0 and 1
2017-11-24 03:32:14.557028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:832] Peer access not supported between device ordinals 1 and 0
2017-11-24 03:32:14.557206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 
2017-11-24 03:32:14.557217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y N 
2017-11-24 03:32:14.557222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   N Y 
2017-11-24 03:32:14.557237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:08:00.0)
2017-11-24 03:32:14.557244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K40c, pci bus id: 0000:84:00.0)

resources request one GPU card, now the task use Two GPU card resources, This kind of circumstance, should not be visible only a GPU card?Can only use a GPU card resources?

so k8s v1.6.1 not support GPU isolation？

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.6.1
- Docker version 1.12.2, build bb80604
- CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- nvidia: Tesla K40c 
- nvidia Driver Version: 375.26

**Comment by WanLinghao** [comment]
I don't get your idea very well. 
you have a node with two GPUs and create a task which requests just one. Then what you expect is  that   only one GPU  can be observed in the task since you just requested one, but actually you observe two GPUs.
Is that what you want to say?

**Comment by fengyu10** [comment]
@WanLinghao yes,To apply for a GPU card resources, Why two GPUs card memory is being used。

**Comment by WanLinghao** [comment]
execute 

> kubectl exec -it pod-name --container container-name -- /bin/bash

connect into container,
then execute 

> find / -name \*nvidia\*

**Comment by fengyu10** [comment]
@WanLinghao find / -name *nvidia*
/dev/nvidiactl
/dev/nvidia1
/dev/nvidia0
/dev/nvidia-uvm-tools
/dev/nvidia-uvm
/etc/ld.so.conf.d/nvidia.conf
/proc/irq/153/nvidia
/proc/irq/152/nvidia
/proc/driver/nvidia-uvm
/proc/driver/nvidia
/sys/bus/pci/drivers/nvidia
/sys/kernel/slab/nvidia_stack_cache(91:c3ea7f7ac2bebc62c27a7835cb2edd772fe4230fa074311c71ced4fca3e1dd18)
...
/sys/module/drm/holders/nvidia_drm
/sys/module/i2c_core/holders/nvidia
/sys/module/drm_kms_helper/holders/nvidia_drm
/sys/module/nvidia_modeset
/sys/module/nvidia_modeset/holders/nvidia_drm
/sys/module/nvidia
/sys/module/nvidia/drivers/pci:nvidia
/sys/module/nvidia/holders/nvidia_modeset
/sys/module/nvidia/holders/nvidia_uvm
/sys/module/nvidia_drm
/sys/module/nvidia_uvm
/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
/usr/local/nvidia
/usr/local/nvidia/lib64/libEGL_nvidia.so.0
/usr/local/nvidia/lib64/libEGL_nvidia.so.1
...


Want to ask kubernetes v1.6.1 doesn't support GPU card isolation? To apply for a card with GPU resources, should use a GPU card memory,in addition a GPU should be in a state of invisible.

**Comment by WanLinghao** [comment]
I have take a glance at the code of v1.6.1, seems that  it does support card isolation.Since I got only one GPU on my PC, so I can't do a deep research.
I think bug does exist

**Comment by ddii** [comment]
Delete <<  securityContext: {privileged: true} >> at the pod yaml.

and re-deploy and check nvidia-smi

**Comment by fengyu10** [comment]
@ddii yes, How well you solve my problem. thank you
