### ISSUE TITLE
delete loadbalancer fail  cloud-provider=openstack

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/kubernetes#56313]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Maybe bug

**What happened**:
when delete service type=LoadBalancer,  service is deleted,
but loadbalancer not deleted in neutron.
error log:  resource not found

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.9
- Cloud provider or hardware configuration:  openstack 
- OS (e.g. from /etc/os-release): ubuntu 14.04
- Kernel (e.g. `uname -a`): 4.2.0-27-generic
- Install tools:
- Others:

**Comment by FengyunPan** [comment]
@hongli-my Can you show me the logs about this issue from kube-controller-manager service?

**Comment by dims** [comment]
/close

need more info
