### ISSUE TITLE
kube-proxy IPVS: cannot access 127.0.0.1:nodeport

### ISSUE THREAD

**Issue by xujieqwe** [kubernetes/kubernetes#56320]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

use kube-proxy ipvs mode, create a service with nodeport
but cannot access 127.0.0.1:nodeport.

**What you expected to happen**:

we can access 127.0.0.1:nodeport in iptables mode, so ipvs should also support this 

**How to reproduce it (as minimally and precisely as possible)**:

1.  run kube-proxy with ipvs
2. create a service with nodeport, get ipvs nodeport rule like below:
```
TCP  10.19.140.10:30338 rr
  -> 172.16.74.4:8080             Masq    1      0          0 
```
3. curl 127.0.0.1:30338
```
# curl 127.0.0.1:30338
curl: (7) Failed connect to 127.0.0.1:30338; Connetion refused
```

**Anything else we need to know?**:

iptables use 'ADDRTYPE matches dst-type LOCAL' to handle nodeport access
but I see ipvs only handles interface contains eth{x}, 
however, we should consider some other ips as "local ip", e.g 127.0.0.1 in lo interface

BTW
I've tried to stop kube-proxy and manually add 127.0.0.1:nodeport ipvs rules. e.g:
```
TCP  127.0.0.1:30338 rr
  -> 172.16.74.4:8080             Masq    1      0          0   
```
then try curl 127.0.0.1:30338 will get hung

**Environment**:
- Kubernetes version : 1.8
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- Install tools:
- Others:

/sig network
/area kube-proxy
/area ipvs

**Comment by xujieqwe** [comment]
@m1093782566

**Comment by m1093782566** [comment]
@xujieqwe 

AFAIK, IPVS does't work on loopback interface.

**Comment by m1093782566** [comment]
IMO, loopback should be used only for bouncing packets for local delivery, why NodePort use it proxy outbound traffic? xref: #21070

**Comment by xujieqwe** [comment]
we find use 127.0.0.1:nodeport can make things very convenient.
In our working envrionment, we have alreay exposed an docker image hub service and use 127.0.0.1:nodeport to pull docker images.

If there will be a flag to kube-proxy specifying which nodeport IP range to use. I think we should first make sure that all the "Local IP:nodeport" could be accessible, then users can choose which ip they want to bind in their particular environment.

@m1093782566

**Comment by m1093782566** [comment]
I just come up with an idea about better implementing nodeport type service via ipvs - get rid of eth{i} assumption. We can get all LOCAL type address from local route table with `ip route` command? For example,

```
[root@100-106-179-225 ~]# ip route show table local type local proto kernel
100.106.179.225 dev eth0  proto kernel  scope host  src 100.106.179.225 
127.0.0.0/8 dev lo  proto kernel  scope host  src 127.0.0.1 
127.0.0.1 dev lo  proto kernel  scope host  src 127.0.0.1 
172.16.0.0 dev flannel.1  proto kernel  scope host  src 172.16.0.0 
172.17.0.1 dev docker0  proto kernel  scope host  src 172.17.0.1 
192.168.122.1 dev virbr0  proto kernel  scope host  src 192.168.122.1 
10.64.77.3 dev kube-ipvs0 proto kernel  scope host  src 192.168.122.1 
```

Because we bind Cluster IPs(e.g `10.64.77.3` in our example) to the dummy interface in IPVS proxier, we need to filter the them out so that we can get the Node IPs. 

Fortunately, the dummy interface created by IPVS proxier is known as `kube-ipvs0`, so we just need to specify the `dev kube-ipvs0` flag in `ip route` command, for example,

```
[root@100-106-179-225 ~]# ip route show table local type local proto kernel dev kube-ipvs0
10.64.77.3 dev kube-ipvs0 proto kernel  scope host  src 192.168.122.1 
```

I have already initiated a discussion on sig-network mailing list. Will start to work towards it if community guys are happy with the proposal.

Any comments are welcome!

**Comment by xujieqwe** [comment]
I like this idea. However, I concern about the loopback interface implementation of IPVS.
I've tried some methods to make 127.0.0.1:nodeport accessible, but still didn't work.

> I just come up with an idea about better implementing nodeport type service via ipvs - get rid of eth{i} assumption. We can get all LOCAL type address from local route table with ip route command

**Comment by m1093782566** [comment]
From the output of ` ipvsadm -lcn` when I curl `127.0.0.1:nodeport`.  I find the source IP is loopback address, so packet never leaves the container.

```
IPVS connection entries
pro expire state       source             virtual            destination
TCP 00:02  SYN_RECV    127.0.0.1:39092    127.0.0.1:31210    172.17.0.4:80
```

**Comment by m1093782566** [comment]
From my test, I find `127.0.0.1:nodeport` works only if real server work on localhost, e.g.

```
[root@SHA1000130405 k8s-yml]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  127.0.0.1:30111 rr
  -> 127.0.0.1:8080               Masq    1      0          1
```

**Comment by m1093782566** [comment]
@fasaxc 

Any thoughts? Does calico has similar user cases?

**Comment by fasaxc** [comment]
@m1093782566 We have worked around similar issues for OpenStack, where a VM can reach itself via its floating IP (VIP) but I don't think we've tried this with IPVS.  When you say that MASQUERADE doesn't work, did you try an iptables MASQUERADE action, or was that IPVS masquerade (which is names the same but works differently).

**Comment by m1093782566** [comment]
Thanks for your reply, @fasaxc 

I tried iptables MASQUERADE and didn't try IPVS masquerade. I don't know the difference between them. How can I try IPVS masquerade? full-nat mode?

**Comment by fasaxc** [comment]
@m1093782566 Afraid I don't know the IPVS options very well.

**Comment by m1093782566** [comment]
Okay, thanks all the same.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/57922 ?

**Comment by m1093782566** [comment]
yes, same issue

**Comment by thockin** [comment]
Can we close one?

**Comment by m1093782566** [comment]
one issue is better than two. 

Let's close this issue and discuss in thread #57922.

/close
