### ISSUE TITLE
StatefulSet creates multiple controllerrevisions on controller restart

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#56355]
version: v1.10.0-alpha.0-469-g6b1b6d504a

When you create StatefulSet and restart statefulset controller, while it's starting it will create multiple controllerrevisions. See https://github.com/openshift/origin/issues/17435#issuecomment-346499744

I've traced this to a [recent change adding collision avoidance](https://github.com/kubernetes/kubernetes/pull/50490) which made newRevision not re-entrant anymore and uncovered bug where statefulset controller doesn't wait on syncing revision informer.

/sig apps
/cc @smarterclayton @kow3ns @enisoc @liyinan926

--
I need to verify the rest next week but I suspect collision avoidance will be problematic in cases of picking up objects from queue multiple times before changes propagate to the informer - that probably needs expectations or revert. Also for cases of rollback (I am not sure if we support it yet or not) it wouldn't work probably either because if the collisionCount would be different, the hash for controllerRevision being rollbacked to would differ too.

**Comment by tnozicka** [comment]
/assign

I'll send a PR to wait for revision informer while starting statefulset controller.

**Comment by liggitt** [comment]
Are there other app controllers that use collision avoidance and/or revision info that are similarly affected?
