### ISSUE TITLE
The kubernetes version is now 1.8, this script maybe out-of-date.

### ISSUE THREAD

**Issue by knightXun** [kubernetes/kubernetes#56376]
https://github.com/kubernetes/kubernetes/blob/e640521f015300f63b55e800e52e2b583bbc9b1a/cluster/windows/kube-startup.ps1#L36

**Comment by andyzhangx** [comment]
@knightXun This file is obsolete, it has moved to https://github.com/Azure/acs-engine/blob/master/parts/kuberneteswindowssetup.ps1, we use acs-engine to deploy k8s cluster on azure.

**Comment by knightXun** [comment]
@andyzhangx thanks

**Comment by andyzhangx** [comment]
@knightXun would you close this issue? thx.

**Comment by knightXun** [comment]
oK
