### ISSUE TITLE
Heapster should aggregate custom metrics of core cluster components

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#5637]
The api server and the kubelet now expose custom metrics. These are useful for introspection and performance analysis of the system. Heapster needs to aggregate them and push to monitoring backends.

**Comment by timothysc** [comment]
@vishh so would you add /metrics scraping similar to Prometheus?

**Comment by vishh** [comment]
Yes. I was planning on having heapster scrape metrics from all the core
system components to begin with.

**Comment by timothysc** [comment]
@vishh Currently heapsters instructions show it to be run as an introspective service inside of k8's but then it will not have access to the scheduler & kcm /metrics endpoints.  Is there a plan to handle this or is the intention to live outside of k8's?

/cc @jayunit100

**Comment by vishh** [comment]
There is an open issue for that #6428. I plan to address that first and that should make it easy to handle master components.

**Comment by bgrant0607** [comment]
@vishh @a-robinson Can this be closed?

**Comment by vishh** [comment]
@bgrant0607 We do not have a mechanism to collect metrics from kube components in a portable manner. So I'd say this issue still needs some attention.

**Comment by bgrant0607** [comment]
@vishh Why can't Prometheus just be used for that?

**Comment by bgrant0607** [comment]
Ref #6981

**Comment by vishh** [comment]
We can. But that would mean that existing users of heapster based pipeline have to run prometheus as well. Given that kube already support collecting metrics exposed in prometheus compatible format, it should be straightforward to plumb those metrics via heapster.

**Comment by a-robinson** [comment]
It could be either heapster or prometheus, but neither has been done.
