### ISSUE TITLE
apiserver uses wrong CommonName to verify service certificates for aggregated API Server when External admission controller is enabled

### ISSUE THREAD

**Issue by patrickshan** [kubernetes/kubernetes#56385]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After you configured webhook admission controller (ExternalAdmissionHookConfiguration) inside your cluster pointing to a service, apiserver will try to verify your new APIService certs against that admission controller service's Common Name. 
For example, a webhook admission controller is registered inside the cluster pointing to a service called "webhook" inside kube-system namespace (Common Name is webhook.kube-system.svc in this case). When you try to register a new APIService called `v1beta1.testapiservice.k8s.io` pointing to a service `testapiservice` inside `testns` namespace after that webhook admission controller was registered, you will see error inside apiserver log like this:
`E1127 01:22:06.230506       1 controller.go:111] loading OpenAPI spec for "v1beta1.testapiservice.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'x509: certificate is valid for testapiservice, testapiservice.testns, testapiservice.testns.svc, testapiservice.testns.svc.cluster.local, not webhook.kube-system.svc'`
And aggregation layer cannot talk to the custom apiserver due to invalid certs.

**What you expected to happen**:
apiserver should only verify the new aggregated API Server certs against its own service's Common Name and shouldn't verify it against webhook admission controller service's Common Name.

**How to reproduce it (as minimally and precisely as possible)**:
1. register a webhook admission controller inside your cluster like the example [here](https://github.com/caesarxuchao/example-webhook-admission-controller) using service webhook.kube-system.svc
2. register a new aggregated API Server using service testapiservice.testns.svc
3. aggregation layer cannot talk to the custom apiserver  and kube-apiserver generates error logs because it couldn't find valid Common Name `webhook.kube-system.svc` for your aggregated API Server service. 

**Anything else we need to know?**:
On the other hand admission controller works fine without any problem in this case described above.
We also tried deploying them in a different order. So deploy the aggregated API Server first and then register the admission controller webhook. In that case, the aggregated API server works fine but admission controller webhook won't work. From kube-apiserver log, you can see it's trying to verify the webhook admission controller service certs against aggregated API Server service's Common Name.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: Aws
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1576.2.0 (Ladybug)
- Kernel (e.g. `uname -a`): 4.13.11-coreos
- Install tools:
- Others:

/sig api-machinery

**Comment by ash2k** [comment]
`testapiservice` is actually Service Catalog api server in our case. The errors I'm seeing in the Service Catalog's apiserver logs are all like this line:
```
I1127 01:15:33.404595       1 logs.go:41] http: TLS handshake error from 10.252.49.128:39810: remote error: tls: bad certificate
```
I.e. the Aggregation layer is failing to establish TLS connection with service catalog's api server.

Error from Service Catalog's controller manager pod:
```
F1127 03:48:10.306802       1 controller_manager.go:198] error running controllers:
failed to get supported resources from server:
unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1:
an error on the server ("Error: 'x509: certificate is valid for service-catalog-apiserver, service-catalog-apiserver.service-catalog, service-catalog-apiserver.service-catalog.svc, service-catalog-apiserver.service-catalog.svc.cluster.local, localhost, not kitt-ac-webhook.kube-system.svc'\nTrying to reach: 'https://10.150.103.42:443/apis/servicecatalog.k8s.io/v1beta1'") has prevented the request from succeeding
```
Controller Manager is trying to talk to the Service Catalog's apiserver via Aggregation Layer (it can talk directly but that is not how it is configured in our case). If I read the error above correctly, **Aggregation Layer tries to talk to Service Catalog's api server using the `kitt-ac-webhook.kube-system.svc` host name which obviously does not match the TLS certificate used on the server side. `kitt-ac-webhook` is the webhook described above.**

Registration object:
```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.servicecatalog.k8s.io
spec:
  caBundle: ....
  group: servicecatalog.k8s.io
  groupPriorityMinimum: 10000
  service:
    name: service-catalog-apiserver
    namespace: service-catalog
  version: v1beta1
  versionPriority: 20
status:
  conditions:
  - lastTransitionTime: 2017-11-27T03:43:43Z
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```

**Comment by ash2k** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
@deads2k @caesarxuchao

**Comment by liggitt** [comment]
Is this reproducible against master?

**Comment by liggitt** [comment]
looks like the tls transport cache key construction doesn't include ServerName

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/cache.go#L84-L92

**Comment by liggitt** [comment]
should be updated, picked back to the point where ServerName was added

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/56415 to resolve
