### ISSUE TITLE
Allow modification of existing pod labels on the fly via configuration

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#56381]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig validation

**What happened**:

Kubernetes forbids updating on existing pod's labels on the fly. But in my case, I want to update a pod's label so that add/remove it from service/endpoints. Is it possible to only suppress the validation of pods' label field via configuration without modifying [k8s validation src code](https://github.com/kubernetes/kubernetes/blob/83e46f0a9ede14431e1ae0950e8bd8fc6a1c43e2/pkg/apis/core/validation/validation.go#L3246)?

> Forbidden: pod updates may not change fields other than spec.containers[ *].image, spec.initContainers[*].image, spec.activeDeadlineSeconds or spec.tolerations (only additions to existing tolerations)

Integration of [spinnaker](https://github.com/spinnaker/spinnaker) with k8s is working by rolling updating pod's label in order to update the endpoint, so banning this modification entirely breaks its working mechanism.

**What you expected to happen**:
Allow modification of existing pod labels on the fly via configuration

**Comment by liggitt** [comment]
Pod label updates are allowed. Changes under spec are not allowed. What admission plugins do you have enabled?

**Comment by yue9944882** [comment]
@liggitt 
Following admission is enabled
> --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota

**Comment by liggitt** [comment]
that message comes from validation that only looks at the pod spec, not the metadata labels/annotations

do you have the update or patch request that is actually being sent to the API server to compare to the current pod?

**Comment by yue9944882** [comment]
@liggitt I carefully compared the difference of the spec between the old and the new pod. But their spec are completely the same. I got errors in my golang program as shown below:

>"message":"Pod \"apollo-dev-yxb-monitor-v000-4fpj9\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)"

But according [to this line of code](https://github.com/kubernetes/kubernetes/blob/83e46f0a9ede14431e1ae0950e8bd8fc6a1c43e2/pkg/apis/core/validation/validation.go#L3319):

I should got the %v formatted spec diff between the pods but nothing is appended in my error msg.

I am COMPLETELY sure I didn't modify the spec of pod but only metadata.labels field.

**Comment by yue9944882** [comment]
@liggitt I carefully compared the difference of the spec between the old and the new pod. But their spec are completely the same. I got errors in my golang program as shown below:

>"message":"Pod \"apollo-dev-yxb-monitor-v000-4fpj9\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)"

But according [to this line of code](https://github.com/kubernetes/kubernetes/blob/83e46f0a9ede14431e1ae0950e8bd8fc6a1c43e2/pkg/apis/core/validation/validation.go#L3319):

I should got the %v formatted spec diff between the pods but nothing is appended in my error msg.

I am COMPLETELY sure I didn't modify the spec of pod but only metadata.labels field.

**Comment by yue9944882** [comment]
@liggitt I carefully compared the difference of the spec between the old and the new pod. But their spec are completely the same. I got errors in my golang program as shown below:

>"message":"Pod \"apollo-dev-yxb-monitor-v000-4fpj9\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)"

But according [to this line of code](https://github.com/kubernetes/kubernetes/blob/83e46f0a9ede14431e1ae0950e8bd8fc6a1c43e2/pkg/apis/core/validation/validation.go#L3319):

I should got the %v formatted spec diff between the pods but nothing is appended in my error msg.

I am COMPLETELY sure I didn't modify the spec of pod but only metadata.labels field.

**Comment by yue9944882** [comment]
@liggitt 
After dumping out the diff of pod spec in my case, I finally realize that this error is caused by the modification of struct `EmptyDirVolumeSource` in release v1.7.8. The field `SizeLimit` is changed from `resource.Quantity` to `*resource.Quantity` which make older version of [client-go](https://github.com/kubernetes/client-go) and [kubernetes-client](https://github.com/kubernetes-client/java) incompatible with apiserver after v1.7.8.

So the fact is, when the client sdk retrieves the spec of an existing pod then try to update its label (for example), then following error will be returned by apiserver.

>Forbidden: pod updates may not change fields other than spec.containers[ ].image, spec.initContainers[].image, spec.activeDeadlineSeconds or spec.tolerations (only additions to existing tolerations)

**Comment by yue9944882** [comment]
So I want make a Pull Request to [ValidatePodUpdate](https://github.com/kubernetes/kubernetes/blob/85f0a1ac42daac3fcd6e7a9431c0bcabc3c653a5/pkg/apis/core/validation/validation.go#L3246) function to make it judge if `SizeLimit` field is a pointer to `resource.Quantity` then make perform a type convertion and continues its validation.

**Comment by liggitt** [comment]
What version of the API server are you seeing this against?

**Comment by yue9944882** [comment]
@liggitt  I'm using v1.7.8

**Comment by yue9944882** [comment]
Merged. 
Closing this issue.
