### ISSUE TITLE
Add a heapster monitoring backend that provides both alerting and graphing functionalities

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#5640]
Heapster with InfluxDB and Grafana provides a simple monitoring visualization solution. But alerting is critical to users and providing an off the box monitoring solution that supports alerting will help users.
Possible candidates include,
- Google Cloud Monitoring
- Prometheus
- Bosun + InfluxDB
- Reimann + InfluxDB
- Sensu

There are quite a few other solutions that are not captured here. The goal is to provide a simple monitoring solution, that serves as a reference implementation, and one that kubernetes users can use with minimal configuration.

**Comment by multilinear** [comment]
Meteor is currently planning to use prometheus for this, since a lot of k8s is already being built using prometheus APIs, and it's unquestionably the richest most flexible of the available tools, particularly where aggregations are concerned. I want it for application layer monitoring as well as pulling in k8s/docker information, and I'd rather use one tool.

I'm trying to figure out how to get data from heapster into prometheus right now (or directly from the kublet I supose, if that's the easiest way). #6981 implies going through heapster is the path k8s intends to go. 

FYI: I believe heapster already supports GCM as a back-end.

**Comment by albertocsm** [comment]
this https://github.com/bosun-monitor/bosun/issues/618 looks promissing

**Comment by pires** [comment]
Prometheus already supports InfluxDB and others and seems the best solution so far.

**Comment by resouer** [comment]
What's the status of this issue? Any PR for this?

**Comment by timothysc** [comment]
This seems like a one of many good topics for the monitoring working group.

**Comment by vishh** [comment]
There is an [open PR](https://github.com/GoogleCloudPlatform/heapster/pull/379) to add Reimann support in heapster.
+1 for discussing this in a monitoring work group.

**Comment by multilinear** [comment]
I'm no longer poking at this anymore by the way, I had planned to try and do something but got pulled elsewhere.

**Comment by paralin** [comment]
I'd like to prod at this issue a little bit since alerting would be really nice in production.

**Comment by pires** [comment]
The [TICK stack](https://influxdata.com/get-started/what-is-the-tick-stack/) from the guys that brought InfluxDB seems really cool.

**Comment by bgrant0607** [comment]
cc @a-robinson

**Comment by jnardiello** [comment]
No news on this? Guys, having a production ready monitoring system is absolutely critical to anyone willing to put k8s in prod. Current default solution with `influxdb` + `grafana` might be great for visualization but is completely lacking of alerting. 

More specifically, I honestly think that Prometheus as of today is the most promising project to integrate.

**Comment by timothysc** [comment]
@jnardiello I believe many folks are using sysdig, zabbix, ganglia... or the host of other monitoring tools to provide alerting and out-of-band monitoring.

**Comment by vishh** [comment]
@jnardiello Sysdig has good integration with kubernetes. So does Prometheus. What according to you is missing?

**Comment by jnardiello** [comment]
@vishh Actually, I must say that I was completely wrong and that my previous comment was quite pointless. Just to partially justify myself, as I wrote it I was just getting started on k8s monitoring.
I didn't know two key facts:
- That Prometheus can integrate with k8s without heapster
- That influxdb has a pairing service for alerting.

I've started implementing prometheus on our cluster and I must say that I'm really happy with it.

**Comment by zouyee** [comment]
@jnardiello hi！ Are you willing to share your experience using k8s with prom

**Comment by geoand** [comment]
Alerting is supported in Grafana since version 4.0 beta (see [this](https://grafana.com/blog/2016/11/09/grafana-4.0-beta-release/)). It would be awesome if there was some way to configure alerting using the standard Grafana + InfluxDB setup of Heapster

**Comment by bgrant0607** [comment]
This issue doesn't belong here.
