### ISSUE TITLE
[e2e failure] [sig-storage] PersistentVolumes-local [Feature:LocalPersistentVolumes] [Serial] when StatefulSet has pod anti-affinity should use volumes spread across nodes

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56412]
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
@kubernetes/sig-storage-test-failures 

This test has been failing since 2017-11-22 in [gci-gce-alpha-features](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-alpha-features) which is on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking), and prevents us from cutting [v1.9.0-beta.1] (kubernetes/sig-release#34). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-alpha-features

- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/17599
- this is also failing on (non-release-blocking) [gci-gce-gke-alpha-features](https://k8s-testgrid.appspot.com/google-gke#gci-gke-alpha-features)
- triage cluster [c49044b7fa3094fa3e5a](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=PersistentVolumes-local#c49044b7fa3094fa3e5a)
- suspect commit range: https://github.com/kubernetes/kubernetes/compare/4e2f5e221...f8ffbd9d6

**Comment by spiffxp** [comment]
/remove-area platform/gke
bad copy-pasta

**Comment by msau42** [comment]
This is a new test that was added for a 1.9 alpha feature but actually exposed a bug with a different 1.8 alpha feature.  Some discussion in #56265.

Since this seems to be a bug introduced in 1.8, I'm not sure if it needs to block 1.9.

cc @resouer

**Comment by sbezverk** [comment]
@msau42 Curious if for https://github.com/kubernetes/kubernetes/issues/56265
you observe the same failure in kubelet log.

W1122 20:59:45.133477    1454 predicate.go:94] Failed to admit pod fluentd-gcp-v2.0.10-g7pvq_kube-system(11737a80-cfc8-11e7-90e2-42010a800002) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: cpu, q: 30), ]
