### ISSUE TITLE
[e2e failure] [sig-scheduling] ResourceQuota should create a ResourceQuota and capture the life of a ...

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56429]
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
/area platform/gke
@kubernetes/sig-scheduling-test-failures
owns the tests
@kubernetes/sig-cluster-lifecycle-test-failures
this is passing in other jobs so I'm pinging the job owner
@kubernetes/sig-gcp-test-failures 
this looks GKE specific

These test has been failing since at least 2017-11-13 for the [gke-gci-1.8-gci-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.8-gci-master-upgrade-cluster-new) job, which is on the [sig-release-master-upgrade dashboard](https://k8s-testgrid.appspot.com/sig-release-master-upgrade), and prevents us from cutting v1.9.0-beta.1 (kubernetes/sig-release#34). Is there work ongoing to bring these tests back to green?

[triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new&test=%5C%5Bsig-scheduling%5C%5D%20ResourceQuota%20should%20create%20a%20ResourceQuota%20and%20capture%20the%20life%20of%20a)

[triage cluster 3d2a887b26f025c4d4c8](https://storage.googleapis.com/k8s-gubernator/triage/index.html#3d2a887b26f025c4d4c8)
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/resource_quota.go:420
Expected error:
    <*errors.StatusError | 0xc421897290>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "configmaps \"test-configmap\" is forbidden: status unknown for quota: test-quota",
            Reason: "Forbidden",
            Details: {
                Name: "test-configmap",
                Group: "",
                Kind: "configmaps",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    configmaps "test-configmap" is forbidden: status unknown for quota: test-quota
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/resource_quota.go:436
```

Sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/1512

**Comment by abgworrall** [comment]
This kinda looks like an apparmor thing, overall:

```
Error creating Pod
Expected error:
    <*errors.StatusError | 0xc421a16000>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "Pod \"test-apparmor-dh62h\" is invalid: metadata.annotations[container.apparmor.security.beta.kubernetes.io/test]: Invalid value: \"unconfined\": invalid AppArmor profile name: \"unconfined\"",
            Reason: "Invalid",
            Details: {
                Name: "test-apparmor-dh62h",
                Group: "",
                Kind: "Pod",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"unconfined\": invalid AppArmor profile name: \"unconfined\"",
                        Field: "metadata.annotations[container.apparmor.security.beta.kubernetes.io/test]",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    Pod "test-apparmor-dh62h" is invalid: metadata.annotations[container.apparmor.security.beta.kubernetes.io/test]: Invalid value: "unconfined": invalid AppArmor profile name: "unconfined"
not to have occurred
```

The apparmor upgrade tests aren't done as part of the GCE suite; just the GKE suite.

@tallclair , WDYT ?

**Comment by tallclair** [comment]
@abgworrall That looks unrelated to the quota failure? Also AFAICT the test and codepath hasn't been cherrypicked to 1.8 (added in https://github.com/kubernetes/kubernetes/pull/52395)

**Comment by tallclair** [comment]
Oh, sorry, just realized you were asking about the upgrade test. Yes, that is a bug in the test, since that feature is added in 1.9, it's expected to fail before the upgrade. Still looks unrelated to quota though.

**Comment by abgworrall** [comment]
Oh, I was blindly hoping that the apparmor failure would explain subsequent 'forbidden' things. Turns out this appamor thing was reported separately in #56422.

**Comment by abgworrall** [comment]
OK, I'm not sure what `configmaps "test-configmap" is forbidden: status unknown for quota: test-quota` is all about, but it's happening consistently inside some [sig-scheduling] tests, so I'm punting it over there.

**Comment by tallclair** [comment]
/unassign

I fixed https://github.com/kubernetes/kubernetes/issues/56422, which was the issue that @abgworrall referenced above. I'm not the right person to own the configmap failure.

**Comment by janetkuo** [comment]
Looking at other ResourceQuota failures, it's not configmap-specific. Somehow the cluster failed to check all resource quota status.

**Comment by davidopp** [comment]
@derekwaynecarr can you take a look at this?

cc/ @bsalamat

**Comment by bsalamat** [comment]
The check that fails is:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/controller.go#L422

It is unfortunate that the ResourceQuota tests are located in the `scheduling` directory.
@derekwaynecarr Can you please take a look? This is blocking the release.

**Comment by derekwaynecarr** [comment]
My wife just had a child this week.  I’m not sure if i will have time to look at this.  I will try tomorrow morning.

**Comment by derekwaynecarr** [comment]
Is this test doing an upgrade or downgrade?  We have support for new quota resource names that would not be understood by 1.8 servers.

**Comment by derekwaynecarr** [comment]
what differentiates the gke specific tests from the gce specific tests?

for example:
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.8-master-upgrade-cluster-new

it looks like the same test in concept, but not gke specific, and in that env, the quota tests are all passing

**Comment by bsalamat** [comment]
> it looks like the same test in concept, but not gke specific, and in that env, the quota tests are all passing

Makes sense. Let me take a look then.

**Comment by spiffxp** [comment]
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

FWIW this magically started passing:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/1562
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/1563

So it may have been a GKE-specific fix?  I'll leave it to @bsalamat to explain if something happened.

I'm OK with this being closed with said explanation, even if it's "gremlins"

**Comment by bsalamat** [comment]
I spent some time yesterday looking into the code, but nothing seemed wrong and the fact that the tests were passing fine in non-GKE tests was indicating that a config problem on GKE must be causing the failure. If there has been any change of configuration on GKE in since yesterday, that might be what has fixed the issue.

**Comment by spiffxp** [comment]
/close
GKE gremlins, got it.  I will reopen if this starts failing again
