### ISSUE TITLE
[e2e failure] [sig-cluster-lifecycle] Downgrade [Feature:Downgrade] cluster downgrade should maintain a functioning cluster [Feature:ClusterDowngrade]

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#56426]
/priority critical-urgent
/priority failing-test
/kind bug
/status approved-for-milestone
/area platform/gke
@kubernetes/sig-cluster-lifecycle-test-failures
owns the test
@kubernetes/sig-gcp-test-failures
this looks GKE-specific

This test has been failing since at least 2017-11-13 for the following jobs:
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.8-downgrade-cluster-parallel
- https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.8-downgrade-cluster

These jobs are on the [sig-release-master-upgrade dashboard](https://k8s-testgrid.appspot.com/sig-release-master-upgrade), and prevent us from cutting v1.9.0-beta.1 (kubernetes/sig-release#34). Is there work ongoing to bring this test back to green?

[triage report](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Downgrade%5C%20%5C%5BFeature%3ADowngrade%5C%5D%5C%20cluster%5C%20downgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AClusterDowngrade%5C%5D)

[triage cluster 1a3779e6777a416e5ddf](https://storage.googleapis.com/k8s-gubernator/triage/index.html#1a3779e6777a416e5ddf)
```
...ResponseError: code=400, message=Cluster master cannot be upgrade to \\\"1.8.4-beta.0.69+9befc2b8928a94\\\"...
```

Sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/839

**Comment by janetkuo** [comment]
Similar issue as #56422. Fix is underway.

**Comment by janetkuo** [comment]
The `Cluster master cannot be upgrade to` bug has been fixed, which uncovered some underlying `[sig-instrumentation]` tests failures. 

Closing this one as new bugs should be opened for`[sig-instrumentation]` test failures. cc @spiffxp

**Comment by spiffxp** [comment]
/reopen
I'm not quite ready to close this yet because I see this test flipped back to failing around midnight here https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.8-downgrade-cluster-parallel

but I do agree the sig-instrumentation test is a separate issue

**Comment by spiffxp** [comment]
Now tracking against v1.9.0-beta.2 (kubernetes/sig-release#39)

**Comment by janetkuo** [comment]
The failures are different. All failing `BeforeSuite` are newly added. Suspect that affects other tests.

**Comment by janetkuo** [comment]
Un-assigning myself, as the original bug is fixed and verified.

**Comment by janetkuo** [comment]
Why are `BeforeSuite` failing, and why aren't them running before? Not sure if it's specific to any sig. Can someone from test-infra take a look?  @kubernetes/test-infra-maintainers

**Comment by krousey** [comment]
@janetkuo After the downgrade completes, another set of normal e2e test runs start. These are called the skew tests. The upgrade step runs to completion and is mostly successful (the HPA test is failing). After that, the next suite is trying some basic validation of the health of the cluster and running into this error:

```console
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:261
Dec  1 20:29:25.707: Error waiting for all pods to be running and ready: 4 / 19 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                                   NODE                                         PHASE   GRACE CONDITIONS
kube-dns-6c679dcc5f-bzswz             gke-bootstrap-e2e-default-pool-2457d662-r9kv Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:43:05 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:43:05 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:43:05 +0000 UTC Reason: Message:}]
kube-dns-6c679dcc5f-kp2fk             gke-bootstrap-e2e-default-pool-2457d662-r9kv Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:30:38 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:30:50 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:30:38 +0000 UTC Reason: Message:}]
kube-dns-7cc95b7957-jzh98             gke-bootstrap-e2e-default-pool-2457d662-wjdb Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:52:12 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:52:12 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [dnsmasq kubedns]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:52:12 +0000 UTC Reason: Message:}]
metrics-server-v0.2.0-97c97dd68-g9wnj gke-bootstrap-e2e-default-pool-2457d662-r9kv Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:30:34 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 20:23:30 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [metrics-server]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2017-12-01 19:30:34 +0000 UTC Reason: Message:}]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:199
```
You can ignore the other "BeforeSuite" errors. Ginkgo is running 25 nodes. It does the sanity test on one node which fails. The other 24 report that the failure happened on the first node.

Looks like dns and metrics are not happy after downgrade.

**Comment by krousey** [comment]
Pulled this from the build log on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/905?log#log. Maybe someone can figure out what's going wrong.

```console
I1201 20:29:28.366] Dec  1 20:24:23.010: INFO: Logs of kube-system/kube-dns-7cc95b7957-jzh98:kubedns on node gke-bootstrap-e2e-default-pool-2457d662-wjdb
I1201 20:29:28.366] Dec  1 20:24:23.010: INFO:  : STARTLOG
I1201 20:29:28.366] I1201 20:22:39.733623       1 dns.go:48] version: 1.14.4-2-g5584e04
I1201 20:29:28.367] I1201 20:22:39.734661       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I1201 20:29:28.367] I1201 20:22:39.734785       1 server.go:113] FLAG: --alsologtostderr="false"
I1201 20:29:28.367] I1201 20:22:39.734803       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I1201 20:29:28.367] I1201 20:22:39.734810       1 server.go:113] FLAG: --config-map=""
I1201 20:29:28.368] I1201 20:22:39.734901       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I1201 20:29:28.368] I1201 20:22:39.734907       1 server.go:113] FLAG: --config-period="10s"
I1201 20:29:28.368] I1201 20:22:39.734914       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I1201 20:29:28.368] I1201 20:22:39.734920       1 server.go:113] FLAG: --dns-port="10053"
I1201 20:29:28.369] I1201 20:22:39.734932       1 server.go:113] FLAG: --domain="cluster.local."
I1201 20:29:28.369] I1201 20:22:39.734957       1 server.go:113] FLAG: --federations=""
I1201 20:29:28.369] I1201 20:22:39.734977       1 server.go:113] FLAG: --healthz-port="8081"
I1201 20:29:28.369] I1201 20:22:39.734995       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I1201 20:29:28.369] I1201 20:22:39.735000       1 server.go:113] FLAG: --kube-master-url=""
I1201 20:29:28.370] I1201 20:22:39.735011       1 server.go:113] FLAG: --kubecfg-file=""
I1201 20:29:28.370] I1201 20:22:39.735016       1 server.go:113] FLAG: --log-backtrace-at=":0"
I1201 20:29:28.370] I1201 20:22:39.735029       1 server.go:113] FLAG: --log-dir=""
I1201 20:29:28.370] I1201 20:22:39.735038       1 server.go:113] FLAG: --log-flush-frequency="5s"
I1201 20:29:28.371] I1201 20:22:39.735043       1 server.go:113] FLAG: --logtostderr="true"
I1201 20:29:28.371] I1201 20:22:39.735063       1 server.go:113] FLAG: --nameservers=""
I1201 20:29:28.371] I1201 20:22:39.735069       1 server.go:113] FLAG: --stderrthreshold="2"
I1201 20:29:28.371] I1201 20:22:39.735088       1 server.go:113] FLAG: --v="2"
I1201 20:29:28.372] I1201 20:22:39.735093       1 server.go:113] FLAG: --version="false"
I1201 20:29:28.372] I1201 20:22:39.735101       1 server.go:113] FLAG: --vmodule=""
I1201 20:29:28.372] I1201 20:22:39.735458       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I1201 20:29:28.372] I1201 20:22:39.735926       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I1201 20:29:28.372] I1201 20:22:39.735968       1 dns.go:147] Starting endpointsController
I1201 20:29:28.373] I1201 20:22:39.736010       1 dns.go:150] Starting serviceController
I1201 20:29:28.373] I1201 20:22:39.736123       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1201 20:29:28.373] I1201 20:22:39.736150       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I1201 20:29:28.374] I1201 20:22:40.236252       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

--- snip because it repeats ---

I1201 20:29:28.391] I1201 20:23:09.736248       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 20:29:28.391] E1201 20:23:09.736974       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.55.240.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.55.240.1:443: i/o timeout
I1201 20:29:28.392] E1201 20:23:09.737910       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.55.240.1:443/api/v1/services?resourceVersion=0: dial tcp 10.55.240.1:443: i/o timeout
I1201 20:29:28.392] I1201 20:23:10.236370       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

--- snip because it repeats ---

I1201 20:29:28.409] I1201 20:23:39.236345       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I1201 20:29:28.409] F1201 20:23:39.736309       1 dns.go:168] Timeout waiting for initialization
```

**Comment by grodrigues3** [comment]
@fejta guessing this might be test-infra related.  Can you PTAL?

**Comment by krzyzacy** [comment]
isn't it because downgrade is failing between run 898/899? it's odd that there's no k/k or test-infra changes involved.

**Comment by krzyzacy** [comment]
cc @MrHohn 
https://k8s-testgrid.appspot.com/sig-release-1.8-all#gci-gke-1.8&width=20 is also failing with before suite - I suspect it's a gke issue @grodrigues3

**Comment by spiffxp** [comment]
I no longer see this specific test case failing as of 
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster/529
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/910

There are a bunch of individual test case failures in the non-parallel job that all seem related the pods not being ready, which may be related to a node not coming back up?

The parallel job is failing because of a sig-instrumentation test case that merits its own issue

**Comment by MrHohn** [comment]
Some updates, the previous test failure (kube-dns, dashboard etc. failed to become ready [1]) was caused by iptables NAT table being flushed twice, which was fixed by https://github.com/kubernetes/kubernetes/pull/56729.

The latest failure (fluentd failed to become ready [2]) seems different, check the kubelet logs [3] and found below error being constantly logged:
```
E1205 13:55:06.280912    1388 configmap.go:202] Couldn't get configMap kube-system/fluentd-gcp-config-v1.2.3: configmaps "fluentd-gcp-config-v1.2.3" not found
```

We need better assignee to look into this. @kubernetes/sig-instrumentation-test-failures 
/unassign @dnardo @MrHohn 

[1] - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster/528
[2] - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster/538
[3] - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster/538/artifacts/gke-bootstrap-e2e-default-pool-c2090219-m798/kubelet.log

**Comment by MrHohn** [comment]
Assigning relevant folks to take a look
/assign @crassirostris @piosz

**Comment by crassirostris** [comment]
This is a problem with addon manager or DaemonSet controller:

1.9: fluentd DaemonSet in version 2.0.10 is using ConfigMap in version 1.2.3
1.8: fluentd DaemonSet in version 2.0.9 is using ConfigMap in version 1.2.2

I see at some point there are pods from both DaemonSets on the node:

```
I1205 09:30:13.798109    1389 kubelet.go:1837] SyncLoop (ADD, "api"): "fluentd-gcp-v2.0.9-r9ggr_kube-system(e2b9c0b9-d99e-11e7-a970-42010a800009)"
I1205 09:30:13.802068    1389 kubelet.go:1837] SyncLoop (ADD, "api"): "fluentd-gcp-v2.0.10-5jmf5_kube-system(e2b990cb-d99e-11e7-a970-42010a800009)"
```

/assign @janetkuo 
Could you please take a look?

**Comment by spiffxp** [comment]
/close
This issue has outlived its scope, the test case originally described has since been fixed

@crassirostris @janetkuo I opened https://github.com/kubernetes/kubernetes/issues/57047 to track the [sig-instrumentation] test failures.
