### ISSUE TITLE
Deprecate v1beta1 network policy

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes#56423]
NetworkPolicy v1 will be the default in 1.9. We can now mark [v1beta1](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/extensions/v1beta1/types.go) as deprecated.

- [x] Mark field types as deprecated #56425
- [x] Add deprecation note to release notes in 1.9
- [x] Send announcement to kube-dev, kube-announce, and sig-net mailing lists

**Comment by fisherxu** [comment]
@cmluciano Can we remove v1beta1 network policy now after v1.9?

**Comment by cmluciano** [comment]
@fisherxu I think that we can

**Comment by cmluciano** [comment]
Announcement sent to kube-dev
