### ISSUE TITLE
AggregationController causing API lag

### ISSUE THREAD

**Issue by goblain** [kubernetes/kubernetes#56430]
/kind bug

**What happened**:

After launching metrics-server my Kube API became unresponsive. with a lot of following in apiserver logs

    Nov 27 16:37:06 ns3033879.ip-51-255-71.eu docker[27628]: I1127 15:37:06.669483       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
    Nov 27 16:37:36 kubemaster docker[27628]: E1127 15:37:36.837123       1 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'dial tcp 10.12.185.191:443: i/o timeout'
    Nov 27 16:37:36 kubemaster docker[27628]: Trying to reach: 'https://10.12.185.191:443/swagger.json', Header: map[]
    Nov 27 16:37:36 kubemaster docker[27628]: I1127 15:37:36.837147       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.

`10.12.185.191` is the ClusterIP of metrics-server service. I assume I made some error bringing metrics-server to the cluster (upgraded from previous versions), but why would it brak apiserver ?

    $ time kubectl --namespace kube-system get pod
    ...
    real    8m1.773s
    user    0m0.212s
    sys     0m0.020s

managed to solve the issue by

    kubectl --namespace kube-system delete apiservice v1beta1.metrics.k8s.io

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: baremetal

**Comment by mumoshu** [comment]
I'm experiencing a similar issue in https://github.com/kubernetes-incubator/kube-aws/issues/1039.

FWIW, my cluster has only 1 controller node. When I recreate the controller node for upgrades, apiserver reports those timeouts and controller-manager never become up and running.

**Comment by DirectXMan12** [comment]
@kubernetes/sig-api-machinery-bugs not sure what the root cause is here, but at the very least, we should have a way to disable OpenAPI aggregation fetching for a particular service, or at least it should back off more aggressively.

**Comment by DirectXMan12** [comment]
cc @deads2k @mbohlool

**Comment by mbohlool** [comment]
I am still not sure this is OpenAPI aggregation. OpenAPI aggregation happening in another thread/controller with a retry mechanism. If an aggregation fails for an APIService, it will not block any functionality for that APIService (other than not having an OpenAPI spec). Is there a way to reproduce this?

**Comment by luxas** [comment]
Is this something to consider for v1.9?

**Comment by DirectXMan12** [comment]
> I am still not sure this is OpenAPI aggregation.

The perf issue might not be (we'd have to reproduce), but the logspam seems to be.

**Comment by mbohlool** [comment]
OpenAPI aggregator would try less (exponentially) on a request failure. We can definitely reduce number of logs. But we should change the title of this bug or create a new one for logspam and continue discussion about OpenAPI aggregation there.

**Comment by showermat** [comment]
I've had the same issue with the metrics server slowing down API accesses until I deleted the API service.  For what it's worth, the ultimate cause was that I forgot to include `--enable-aggregator-routing=true` in the kube-apiserver manifest.

**Comment by olemarkus** [comment]
/remove-lifecycle stale

This seems still to be an issue.

**Comment by lavalamp** [comment]
If including --enable-aggregator-routing=true fixes the problem, then the
root cause is network connectivity. A broken networking setup will break
the OpenAPI aggregation and ALSO break any synchronous access that happens
on the serving path--we should figure out what that is...

**Comment by john-delivuk** [comment]
After enabling the `--enable-aggregator-routing=true` flag I still continue to continue to see the same behavior. I also notice that this seems to be prevalent when we scale, our prod infrastructure which is much larger suffers, but I don't notice any issues in our dev, and testing environments.

**Comment by lavalamp** [comment]
How many replicas of the metrics apiserver are you running? Maybe it just
can't keep up with the load? If we can reproduce this with sample
apiserver, that might be good--we could then fix & verify via test that an
aggregated apiserver that's struggling shouldn't interfere with the rest of
the control plane.

**Comment by john-delivuk** [comment]
I suspected that but what should be hitting it? I had no HPA's enabled. I did scale up to 2 replicas just to see, but not effect.

**Comment by DirectXMan12** [comment]
I suspect it's not the metrics API server -- I've seen in other cases in my testing, where just the presence of an API service can cause weird performance profiles.  I've mainly only noticed it when the given API server doesn't serve an OpenAPI spec, but I seem to recall having seen it elsewhere.

**Comment by khelll** [comment]
I have installed the Prometheus custom metrics adapter which worked for 2 hours then, the cluster became unresponsive and I started to see the same error above for **both** custom metrics and metrics. Only when I disabled the adapter things went back to normal. 
So, I guess @DirectXMan12 hunch about one API service going down is taking this down seems right.

**Comment by khelll** [comment]
More updates, the metrics server is suffering again even when the custom metrics server is not there anymore. Please discard my note above.

**Comment by matohavo** [comment]
/remove-lifecycle stale

Still an issue with k8s 1.11.1 - this ate 2 of my days, kubectl requests taking minutes.
Seems like it started after changing /etc/resolv.conf (making the node unable to resolve for a while).

Mentioned hotfix worked: 
`kubectl --namespace kube-system delete apiservice v1beta1.metrics.k8s.io`

**Environment:**

Kubernetes version: v1.11.1 (server)
Cloud provider or hardware configuration: baremetal (Ubuntu bionic)
Installer: RKE

**Comment by ssgtmas** [comment]
/reopen
This is still an issue. v1.13.3. Remove the metrics-server deployment, but not the apiservice to recreate. Here are the full steps:
1) Apply metrics-server (k8s.gcr.io/metrics-server-amd64:v0.3.1)
2) Create a namespace
3) Delete the metrics server deployment only.
4) Try to delete the namespace
It stays there forever in 'Terminating' state.

**Comment by stefanlasiewski** [comment]
@goblain Are you able to re-open this? It was still an issue when I checked recently (Running Rancher, as shown in rancher/rancher#17248), and it's an issue for @ssgtmas as well.

**Comment by aleksystasiak** [comment]
> /reopen
> This is still an issue. v1.13.3. Remove the metrics-server deployment, but not the apiservice to recreate. Here are the full steps:
> 
>     1. Apply metrics-server (k8s.gcr.io/metrics-server-amd64:v0.3.1)
> 
>     2. Create a namespace
> 
>     3. Delete the metrics server deployment only.
> 
>     4. Try to delete the namespace
>        It stays there forever in 'Terminating' state.

I'm having same issue on 1.13.4 when metrics-server breaks request to delete namespace
Also some requests to apiserver will fail or hang from same reason 
/reopen

**Comment by RamanPndy** [comment]
> I've had the same issue with the metrics server slowing down API accesses until I deleted the API service. For what it's worth, the ultimate cause was that I forgot to include `--enable-aggregator-routing=true` in the kube-apiserver manifest.

Thanks.
this will surely resolve the api server lag issue but still extension api server controller manager pod is crashing. I have installed service-catalog. catalog api-server is running fine but catalog controller manager keep crashing with following logs :
I0619 09:37:44.170086       1 controller_manager.go:306] Created client for API discovery
I0619 09:37:44.170158       1 round_trippers.go:419] curl -k -v -XGET  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXRhbG9nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXItdG9rZW4tYmNzdngiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic2VydmljZS1jYXRhbG9nLWNvbnRyb2xsZXItbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjEzNzVlZjg3LTkyNzUtMTFlOS1iNWJhLTAwNTA1NmE1ZWZiNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXRhbG9nOnNlcnZpY2UtY2F0YWxvZy1jb250cm9sbGVyLW1hbmFnZXIifQ.ih-xpWuuco0RRiEgVfCyfFeSKHv0oqRV7VHaalaBDk6LdwiA90v7QGBynb3zuPWALwr_IsuDdxZ6eewR6pKMeOBcew16Va9kbB7zrZBnIbtiqK0aOxO9Dmmx0wKTfsfQ7I4jH7ZunhUKHGvnKW1Mx2Q-TDVXoNQ3rj1qgLYINTUVwdvzuUUa3GBnrrpIXhYci5CQkSv7DV57t_48MsoMw6d9zNtxMNzkaLQIkvJdA_uLSITkTEsoSe4yGQi9fBj6X6VD0BCFazNNznQk-J_ALJfuqcWCTdP94n7vOlStqJggXivXgPffTBWL-qk3IyGeGb93fI-KvgXzMEdPWvZxCg" -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.2.1 (linux/amd64) kubernetes/6c6a49d/service-catalog-controller-discovery" 'https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s'
I0619 09:38:16.170350       1 round_trippers.go:438] GET https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s  in 32000 milliseconds
I0619 09:38:16.170379       1 round_trippers.go:444] Response Headers:
E0619 09:38:16.170409       1 controller_manager.go:311] Failed to get supported resources from server: Get https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
F0619 09:38:16.170431       1 controller_manager.go:236] error running controllers: failed to get api versions from server: "timed out waiting for the condition", "Get https://10.233.0.1:443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

and following are the kube-apiserver logs:
I0619 09:28:00.579629       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.
E0619 09:28:24.682199       1 memcache.go:135] couldn't get resource list for servicecatalog.k8s.io/v1beta1: Get https://[::1]:6443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0619 09:29:26.693437       1 memcache.go:135] couldn't get resource list for servicecatalog.k8s.io/v1beta1: Get https://[::1]:6443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0619 09:30:00.579827       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.servicecatalog.k8s.io

E0619 09:30:26.508009       1 upgradeaware.go:343] Error proxying data from client to backend: read tcp 161.92.248.32:6443->161.92.248.32:42488: read: connection reset by peer
E0619 09:30:28.708471       1 memcache.go:135] couldn't get resource list for servicecatalog.k8s.io/v1beta1: Get https://[::1]:6443/apis/servicecatalog.k8s.io/v1beta1?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0619 09:31:00.580031       1 controller.go:111] loading OpenAPI spec for "v1beta1.servicecatalog.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: request timed out, Header: map[]
I0619 09:31:00.580059       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.servicecatalog.k8s.io: Rate Limited Requeue.

Please suggest any resolution of this.

**Comment by weiqiang333** [comment]
Although my kube-apiserver server started the kube-rpoxy it still needs to be configured --enable-aggregator-routing=true, which has haunted me for a long time.

**Comment by stefanlasiewski** [comment]
Adding a note for people who find this issue via Google. Keep in mind that error messages with `v1beta1.metrics.k8s.io` can be misleading and can be due to multiple underlying causes. That is one reason why this ticket was allowed to become stale and closed. If you run into this error, do a quick sanity check and look for more routine causes of your cluster failure.

For example, just last week my entire cluster failed to come up after a power outage. The first error I found was the familiar error with `v1beta1.metrics.k8s.io`:

`E1016 23:19:50.840814 1 available_controller.go:353] v1beta1.metrics.k8s.io failed with: Get https://10.43.123.100:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

The underlying cause was actually that the `etcd` members couldn't reach each other due to a  firewall issue:

```
root@docker01:~# docker logs --tail 100 -f etcd
2019-10-17 22:27:11.005468 W | rafthttp: health check for peer asdasdasdasd123 could not connect: dial tcp 192.168.100.100:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
2019-10-17 22:27:11.005497 W | rafthttp: health check for peer 123123123123asd could not connect: dial tcp 192.168.100.101:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
```

So, as you read the responses in this thread, just be aware that errors with `v1beta1.metrics.k8s.io` may actually be caused by something else.
