### ISSUE TITLE
Move Printer methods in cmdutil.Factory to separate interface in separate file

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#56431]
Tracking https://github.com/kubernetes/kubernetes/pull/54867#issuecomment-346254791

The point of this would be to make printer code more readable by adding a new interface (`PrinterFactory`?) to [cmdutil/Factory](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go) and implementing it in its own file, effectively splitting printer code from the `BuilderFactory` interface.

cc @mengqiy @fabianofranz @smarterclayton

**Comment by davidxia** [comment]
@juanvallejo Hi, I'm new to developing kube. I was hoping to contribute a PR. Is this issue still relevant? If so, is your suggestion above still the recommended approach?

**Comment by juanvallejo** [comment]
Hi @davidxia , yep this is still relevant to solve.
The suggestion above would probably be the easiest approach.
1. Creating a new file (probably under `pkg/kubectl/cmd/util/factory_printing.go`)
2. Having the implementation object called `ring3Factory`, which composes both a `clientAccessFactory` and an `objectMappingFactory` (take a look [at how factory_builder.go does it](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_builder.go#L36-L48), should be pretty similar)
3. Moving all printer-related methods from `factory_builder.go` to this new file.
4. Creating an interface for this [in factory.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L229). It should pretty much consist of all 5 or so printer-related methods currently under `BuilderFactory` and nothing more.
5. Once you've moved all printer-related methods from `factory_builder` to the new file, wire in the new "printingFactory" [by instantiating it and composing it in the main factory here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L276).

Thanks

cc @fabianofranz for any additional feedback

**Comment by davidxia** [comment]
Great. I can get started if this is the agreed upon way forward.
-- 
David Xia
davidxia.com

**Comment by MorrisLaw** [comment]
@davidxia @juanvallejo is this still being worked on?

**Comment by davidxia** [comment]
@MorrisLaw Sorry, I haven't gotten around to it. Feel free to pick it up if not done already.

**Comment by juanvallejo** [comment]
@MorrisLaw Due to a recent series of patches refactoring the cmdutil factory, printing methods are now no longer part of it. This issue can be closed.

Thanks
