### ISSUE TITLE
Upgrade to etcd server 3.2.14

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#56438]
## Upgrade Kubernetes to use etcd server 3.2.14

The [etcd 3.2.14](https://github.com/coreos/etcd/releases/tag/v3.2.14) server includes critical [bbolt freelist corruption and fragmentation fixes](https://github.com/coreos/etcd/pull/8813) that are essential for HA clusters.

For Kubernetes 1.10, we should make etcd 3.2.14 the default etcd version. This will require a upgrade similar to the [etcd 3.1.10 upgrade for kubernetes 1.9](https://github.com/kubernetes/kubernetes/pull/49393).

We plan to target the Kubernetes 1.10 release, and backport to 1.9 (and possibly 1.8) if/when the fix proves stable.

(For the corresponding etcd client 3.2.14 upgrade see #56114)

**Comment by jpbetz** [comment]
cc @gyuho @xiang90 @wojtek-t @mml @cheftako

**Comment by gyliu513** [comment]
I filed an issue to upgrade to etcd 3.2.14 at https://github.com/kubernetes/kubernetes/issues/58654 as 3.2.14 has a critical fix for large scale cluster. 

Any comments to track the upgrade in this issue? I want to close https://github.com/kubernetes/kubernetes/issues/58654 and update this issue from etcd 3.2.13 to 3.2.14, comments @jpbetz @timothysc @liggitt

**Comment by jpbetz** [comment]
@gyliu513 I've updated this issue to reflect that we will bump to 3.2.14.

**Comment by dkirrane** [comment]
I'm using kubeadm `v1.10.2` and noticed `kubeadm init` it is pulling `k8s.gcr.io/etcd-amd64:3.1.12`
