### ISSUE TITLE
pkg/kubectl/cmd/resource test failed

### ISSUE THREAD

**Issue by jingax10** [kubernetes/kubernetes#56449]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

pkg/kubectl/cmd/resource test failed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

make test WHAT=./pkg/kubectl/cmd/resource

Running tests for APIVersion: v1,admissionregistration.k8s.io/v1alpha1,admissionregistration.k8s.io/v1beta1,admission.k8s.io/v1beta1,apps/v1beta1,apps/v1beta2,apps/v1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,events.k8s.io/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,storage.k8s.io/v1alpha1,
+++ [1127 16:25:40] Running tests without code coverage
panic: test timed out after 2m0s

goroutine 74 [running]:
testing.startAlarm.func1()
	/usr/lib/google-golang/src/testing/testing.go:1160 +0xf9
created by time.goFunc
	/usr/lib/google-golang/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4205661e0, 0x1c50f3e, 0xe, 0x1ce4120, 0x2bd0201)
	/usr/lib/google-golang/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4205661e0)
	/usr/lib/google-golang/src/testing/testing.go:1006 +0x64
testing.tRunner(0xc4205661e0, 0xc4207cfde0)
	/usr/lib/google-golang/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42011ea80, 0x2bc4fa0, 0x18, 0x18, 0xc4207cfe78)
	/usr/lib/google-golang/src/testing/testing.go:1004 +0x2d8
testing.(*M).Run(0xc4210bbf18, 0x52927d)
	/usr/lib/google-golang/src/testing/testing.go:923 +0x111
main.main()
	k8s.io/kubernetes/pkg/kubectl/cmd/resource/_test/_testmain.go:90 +0xdb

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2bd0600)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.0
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 35 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/google-golang/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/google-golang/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/google-golang/src/os/signal/signal_unix.go:28 +0x41

goroutine 53 [select]:
net/http.(*Transport).getConn(0xc4205664b0, 0xc421c1f290, 0x0, 0xc42164f3e0, 0x5, 0xc42164f420, 0x12, 0x0, 0x0, 0xc42005dc00)
	/usr/lib/google-golang/src/net/http/transport.go:948 +0x5bf
net/http.(*Transport).RoundTrip(0xc4205664b0, 0xc421abd300, 0xd, 0xc422ea38f0, 0x27)
	/usr/lib/google-golang/src/net/http/transport.go:400 +0x6a6
k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*bearerAuthRoundTripper).RoundTrip(0xc4223103c0, 0xc421abd300, 0xa, 0xc420b92980, 0x35)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:315 +0x186
k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc422310420, 0xc421abd200, 0xc422310420, 0x0, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:193 +0x10c
net/http.send(0xc421abd100, 0x29fab80, 0xc422310420, 0x0, 0x0, 0x0, 0xc4231b5030, 0x0, 0xc420e54cb8, 0x1)
	/usr/lib/google-golang/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0xc420fc06f0, 0xc421abd100, 0x0, 0x0, 0x0, 0xc4231b5030, 0x0, 0x1, 0xc420e54d40)
	/usr/lib/google-golang/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0xc420fc06f0, 0xc421abd100, 0x0, 0x1a, 0x0)
	/usr/lib/google-golang/src/net/http/client.go:602 +0x28d
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request(0xc420c9c900, 0xc420e54fa8, 0x0, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:663 +0x2ab
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do(0xc420c9c900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:735 +0xb7
k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroups(0xc4223104a0, 0xc42301d0e0, 0x53, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:128 +0xdb
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*CachedDiscoveryClient).ServerGroups(0xc4213c31c0, 0x0, 0xc420e55448, 0x68c380)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/cached_discovery.go:122 +0x102
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*CachedDiscoveryClient).ServerResources(0xc4213c31c0, 0x1c47c36, 0x4, 0x0, 0x0, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/cached_discovery.go:94 +0x40
k8s.io/kubernetes/pkg/kubectl/categories.discoveryFilteredExpander.Expand(0x29fc140, 0xc42039d800, 0x2ba3c1a15f90, 0xc4213c31c0, 0x1c47c36, 0x4, 0x2, 0xc421acc050, 0xc421acc083, 0xc420e556f0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/categories/categories.go:108 +0xaa
k8s.io/kubernetes/pkg/kubectl/categories.(*discoveryFilteredExpander).Expand(0xc4223104c0, 0x1c47c36, 0x4, 0x0, 0x29fb3c0, 0xc421c1efc0, 0x6841f3)
	<autogenerated>:1 +0x73
k8s.io/kubernetes/pkg/kubectl/categories.discoveryCategoryExpander.Expand(0x29fc1c0, 0xc4223104c0, 0x2ba3c1a15f90, 0xc4213c31c0, 0x1c47c36, 0x4, 0x0, 0xc422cd2c80, 0x1, 0x1)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/categories/categories.go:55 +0x5af
k8s.io/kubernetes/pkg/kubectl/categories.(*discoveryCategoryExpander).Expand(0xc4223104e0, 0x1c47c36, 0x4, 0x1, 0xc422cd2c80, 0x1, 0x1)
	<autogenerated>:1 +0x73
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).ReplaceAliases(0xc422a26480, 0x1c47c36, 0x4, 0xc422323c00, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:486 +0x409
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).ResourceTypeOrNameArgs(0xc422a26480, 0x1, 0xc422323ca0, 0x2, 0x2, 0x1c4ddd5)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:459 +0xc23
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).Flatten(...)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go:244
k8s.io/kubernetes/pkg/kubectl/cmd/resource.(*GetOptions).Run(0xc4200c4240, 0x2a26b80, 0xc4223235a0, 0xc420447b00, 0xc422323ca0, 0x2, 0x2, 0x0, 0x0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go:247 +0x27f
k8s.io/kubernetes/pkg/kubectl/cmd/resource.NewCmdGet.func1(0xc420447b00, 0xc422323ca0, 0x2, 0x2)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go:149 +0x115
k8s.io/kubernetes/pkg/kubectl/cmd/resource.TestGetObjects(0xc420f240f0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get_test.go:379 +0x40d
testing.tRunner(0xc420f240f0, 0x1ce4120)
	/usr/lib/google-golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/google-golang/src/testing/testing.go:789 +0x2de

goroutine 72 [IO wait]:
internal/poll.runtime_pollWait(0x2ba3c1979f00, 0x77, 0xc420042000)
	/usr/lib/google-golang/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421dc4218, 0x77, 0xc4210b9100, 0x54cadb, 0xc4210b9148)
	/usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc421dc4218, 0xc4210b9100, 0xc4210b9180, 0x6a3613)
	/usr/lib/google-golang/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc421dc4200, 0x1ce5e80, 0x2a16ac0)
	/usr/lib/google-golang/src/internal/poll/fd_unix.go:403 +0x37
net.(*netFD).connect(0xc421dc4200, 0x2a16ac0, 0xc420d4ea20, 0x0, 0x0, 0x29fb740, 0xc42164f440, 0x0, 0x0, 0x0, ...)
	/usr/lib/google-golang/src/net/fd_unix.go:152 +0x2b6
net.(*netFD).dial(0xc421dc4200, 0x2a16ac0, 0xc420d4ea20, 0x2a19ae0, 0x0, 0x2a19ae0, 0xc421c1f350, 0x0, 0x6bef7e)
	/usr/lib/google-golang/src/net/sock_posix.go:142 +0xe9
net.socket(0x2a16ac0, 0xc420d4ea20, 0x1c475c3, 0x3, 0x2, 0x1, 0x0, 0x0, 0x2a19ae0, 0x0, ...)
	/usr/lib/google-golang/src/net/sock_posix.go:93 +0x1c0
net.internetSocket(0x2a16ac0, 0xc420d4ea20, 0x1c475c3, 0x3, 0x2a19ae0, 0x0, 0x2a19ae0, 0xc421c1f350, 0x1, 0x0, ...)
	/usr/lib/google-golang/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0x2a16ac0, 0xc420d4ea20, 0x1c475c3, 0x3, 0x0, 0xc421c1f350, 0x2bf0c80, 0x0, 0x0)
	/usr/lib/google-golang/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x2a16ac0, 0xc420d4ea20, 0x1c475c3, 0x3, 0x0, 0xc421c1f350, 0xbe7f4944d65e3f9c, 0x1f9ff72ea3, 0x2bd0280)
	/usr/lib/google-golang/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x2a16ac0, 0xc420d4ea20, 0xc421dc4100, 0x2a06fc0, 0xc421c1f350, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/dial.go:567 +0x3e2
net.dialSerial(0x2a16ac0, 0xc420d4ea20, 0xc421dc4100, 0xc422d4b8b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/dial.go:535 +0x247
net.(*Dialer).DialContext(0xc4203667e0, 0x2a16a80, 0xc420014208, 0x1c475c3, 0x3, 0xc42164f420, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/lib/google-golang/src/net/dial.go:417 +0x746
net.(*Dialer).Dial(0xc4203667e0, 0x1c475c3, 0x3, 0xc42164f420, 0x12, 0x24002301d260, 0x110, 0x110, 0xc422af25a0)
	/usr/lib/google-golang/src/net/dial.go:333 +0x75
net.(*Dialer).Dial-fm(0x1c475c3, 0x3, 0xc42164f420, 0x12, 0xc422d4b850, 0xc420069998, 0x51ab09, 0x60)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/cache.go:71 +0x52
net/http.(*Transport).dial(0xc4205664b0, 0x2a16a80, 0xc420014208, 0x1c475c3, 0x3, 0xc42164f420, 0x12, 0xc421519500, 0x0, 0x0, ...)
	/usr/lib/google-golang/src/net/http/transport.go:887 +0x7b
net/http.(*Transport).dialConn(0xc4205664b0, 0x2a16a80, 0xc420014208, 0x0, 0xc42164f3e0, 0x5, 0xc42164f420, 0x12, 0x5994a6, 0x5a1cad48, ...)
	/usr/lib/google-golang/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0xc4205664b0, 0x2a16a80, 0xc420014208, 0xc421c1f2c0, 0xc42301d1a0)
	/usr/lib/google-golang/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
	/usr/lib/google-golang/src/net/http/transport.go:942 +0x393

goroutine 73 [select]:
net.(*netFD).connect.func2(0x2a16ac0, 0xc420d4ea20, 0xc421dc4200, 0xc42301d380, 0xc42301d320)
	/usr/lib/google-golang/src/net/fd_unix.go:129 +0xf2
created by net.(*netFD).connect
	/usr/lib/google-golang/src/net/fd_unix.go:128 +0x2a3
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/resource	120.352s
make: *** [test] Error 1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): head
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: golang 1.9.2

**Comment by jingax10** [comment]
@kubernetes/sig-node

**Comment by stewart-yu** [comment]
I will have a look

**Comment by stewart-yu** [comment]
It OK, no problem.
```
+++ [1128 10:17:53] Running tests without code coverage
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/resource	0.592s
```

**Comment by jingax10** [comment]
Thanks for looking into it! Have you synced to head? I can still reproduce it locally (with golang 1.9.2).

**Comment by stewart-yu** [comment]
Yes

**Comment by jingax10** [comment]
I cannot reproduce it until today. Strange. Anyway, just close it :-)

/close
