### ISSUE TITLE
Issues at volume plugin interface VolumesAreAttached() 

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#56455]
There are two things attach detach controller do in  reconciler:
-  reconcile()
-  sync()
At the sync(), take cinder plugin for example, it calls VolumesAreAttached() (https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L181) to check the volume status with a node, if the volume is not attached, then will call actualStateOfWorld.MarkVolumeAsDetached() (https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L192) to remove the volume from asw. The reconcile() will do the attach operation again for the removed volume.

The issue is:

VolumesAreAttached() calls attacher.cinderProvider.DisksAreAttached(), 

```
func (os *OpenStack) DisksAreAttached(instanceID string, volumeIDs []string) (map[string]bool, error) {
	attached := make(map[string]bool)
	for _, volumeID := range volumeIDs {
		isAttached, _ := os.DiskIsAttached(instanceID, volumeID)
		attached[volumeID] = isAttached
	}
	return attached, nil
}
```
DisksAreAttached() calls DiskIsAttached()

```
// DiskIsAttached queries if a volume is attached to a compute instance
func (os *OpenStack) DiskIsAttached(instanceID, volumeID string) (bool, error) {
	volume, err := os.getVolume(volumeID)
	if err != nil {
		return false, err
	}

	return instanceID == volume.AttachedServerId, nil
}
```

If os.getVolume return errors(which maybe caused by cinder down or something else), then it will return the bool value as `false`, that means the volume will be mark as not detached at DisksAreAttached(). Then `actualStateOfWorld.MarkVolumeAsDetached` will be called to mark the volume as detached. During this time, delete  the pod that using the volume , the volume will not be detached.

@dims  @jingxu97  Can you help to check this issue?

For the DiskIsAttached() called by Attach() , any error returned by  os.getVolume() will be treated as the volume not attached, that make sense. But at DisksAreAttached(), which is  used to reconcile the attached volume, if  os.getVolume() has errors, is it better to treated the volume had been attached but not detached?

**Comment by dims** [comment]
cc @FengyunPan @anguslees

**Comment by zetaab** [comment]
@dims can you close this

**Comment by dims** [comment]
/close

thanks @zetaab
