### ISSUE TITLE
more host port control

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#56458]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

Host ports are system-wide rare resource.
It would be helpful for administrator to get ways to reserve and distribution host ports to each namespace.
The follow three features would be helpful:
1. Node port limitation per namespace
2. Disallow NodePort on specific hosts. (For example node want reserve some special ports, containers should not uses these ports.)
3. Node port allocation control per user role

I have feagure out some ideas for these features:
1. Node port limitation per namespace
Add nodeport to [podResource quota](https://github.com/kubernetes/kubernetes/blob/24042ce6e700be767176e2e9438d6d97de69f578/pkg/quota/evaluator/core/pods.go#L47 )
2. Disallow NodePort on specific hosts.
Introduce a new --reserved-ports to kubelet and support this in kube-scheduler.
3. Node port allocation control per user role
TODO

**Comment by CaoShuFeng** [comment]
@kubernetes/sig-network-feature-requests

**Comment by liggitt** [comment]
PodSecurityPolicy supports limiting the allowed host ports in a pod spec

**Comment by thockin** [comment]
What is motivating this request?  Jordan's answer is best, I think.

**Comment by CaoShuFeng** [comment]
PSP controls the range of hostports a user can use.
Can we add a quota to control  total amount of host ports in each namespace?

**Comment by CaoShuFeng** [comment]
https://github.com/kubernetes/kubernetes/pull/57319
