### ISSUE TITLE
why? Running Java is bad

### ISSUE THREAD

**Issue by haqiaolong** [kubernetes/kubernetes#56457]
Hello, my application is a Java, only to set up a cpuset performance, if not is to set the default host auditing, this will frequently switch CPU, lead to low performance, do you have any good solution?

**Comment by haqiaolong** [comment]
area/kubectl

**Comment by tengqm** [comment]
try CPUManager

**Comment by haqiaolong** [comment]
what is CPUManager ? @tengqm

**Comment by haqiaolong** [comment]
How do you do that?Do you manage it yourself? @tengqm

**Comment by tengqm** [comment]
@haqiaolong https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

**Comment by haqiaolong** [comment]
tks @tengqm
