### ISSUE TITLE
add PV resize support for azure disk

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#56463]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
According to https://github.com/kubernetes/features/issues/284, some volumes(e.g. aws, nfs, ceph) has already supported PV resizing, need to add PV resize support for azure disk

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
PV resize doc is here:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/grow-volume-size.md

Update:
For azure disk, there is blocking issue: it does not support disk resize on a Running VM. I will try to work on resizing an azure disk which is not in attached state. May dig into more details later. 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by andyzhangx** [comment]
Hi @gnufied , is PV size grow feature still in alpha in master now? How do I open this feature, set `--feature-gates=ExpandPersistentVolumes=true` in kubelet, kube-apiserer and kube-controller-manager config?

`

**Comment by andyzhangx** [comment]
@gnufied I have figured out that `--feature-gates=ExpandPersistentVolumes=true` should be set in kubelet, kube-apiserer, kube-controller-manager, kube-scheduler config, and also need to enable ` PersistentVolumeClaimResize` in apiserver admission control. It works well.

**Comment by jdumars** [comment]
@andyzhangx should we go ahead and close this issue?

**Comment by gnufied** [comment]
@andyzhangx also https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/persistentvolume/resize/admission.go#L160 file needs to be updated to allow resizing. This plugin provides additional checks for resizing.

**Comment by andyzhangx** [comment]
@jdumars  For azure disk, there is blocking issue: it does not support disk resize on a Running VM.
I would suggest work on [add size grow feature for **azure file**](https://github.com/kubernetes/kubernetes/pull/57017) first, @gnufied could you review #57017 , it works well in my testing env.

**Comment by jberkus** [comment]
Adding priority important-soon to this issue so that it can stay in 1.10.  If that is incorrect, please update.

\priority important-soon

**Comment by jberkus** [comment]
@justaugustus @andyzhangx  does this look on track for 1.10?  if so, please add status/approved-for-milestone before Monday 26th.  Thanks!

**Comment by jberkus** [comment]
@andyzhangx @justaugustus PR has been merged, can this issue be closed?

**Comment by justaugustus** [comment]
@jberkus yup, looks like it's in. Thanks for flagging!
/close

**Comment by justaugustus** [comment]
Awww shucks, looks like I don't have magic powers.
@andyzhangx please close this when you have a chance?

**Comment by andyzhangx** [comment]
@jberkus  @justaugustus  [PV resize for azure disk code](https://github.com/kubernetes/kubernetes/pull/57017) has been merged, while for azure disk work is just in investigation state mainly  because there is blocking issue: it does not support disk resize on a Running VM.

**Comment by andyzhangx** [comment]
could someone move this issue out of milestone v1.10, thanks.

**Comment by Morriz** [comment]
Why was this closed? This is not fixed by that crappy #64386 PR. This is the kubernetes repo, and this refers to k8s apis being implemented correctly iyam. The PR that you closed this with does NOT support disk resize on a Running VM. Your words @andyzhangx. Please reopen this.

**Comment by andyzhangx** [comment]
> Why was this closed? This is not fixed by that crappy #64386 PR. This is the kubernetes repo, and this refers to k8s apis being implemented correctly iyam. The PR that you closed this with does NOT support disk resize on a Running VM. Your words @andyzhangx. Please reopen this.

@Morriz pls track this issue for online resize feature: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/273
