### ISSUE TITLE
Change the host IP address, kubeadm reset, use ''kubectl get nodes'' will dial to the old ip address  

### ISSUE THREAD

**Issue by chenqy930** [kubernetes/kubernetes#56476]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug
> /kind feature

**What happened**:
I changed the host IP address, and use ''kubeadm reset'' and ''kubeadm init'', it successed as follow output coming:
You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 99b82f.4dfbd8d922e35566 192.168.1.140:6443 --discovery-token-ca-cert-hash sha256:6e5f986986a8119b03076f14eb010bf46a09afe6c4e6811313f39dc069f26c5e

we can see that it already use the new IP address 192.168.1.140

then when I tried ''kubectl get nodes'', the result is:
Unable to connect to the server: dial tcp 192.168.41.134:6443: i/o timeout
192.168.41.134 is the old IP address.

It seems everything related to kubectl can not work now.

**What you expected to happen**:
dial to the new IP address, and ''kubectl get nodes'' can print out the appropriate node information.

**How to reproduce it (as minimally and precisely as possible)**:
the steps as mentioned in ''what happened'' section. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Unable to connect to the server: dial tcp 192.168.41.134:6443: i/o timeout
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"

- Kernel (e.g. `uname -a`):
Linux master 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Others:

**Comment by dixudx** [comment]
@chenqy930 Please move this issue [kubeadn](https://github.com/kubernetes/kubeadm).

Also can you run `kubectl config view` to verify the server address defined in cluster.

**Comment by chenqy930** [comment]
Sorry for the late reply.
kubectl config view shows as follows 
root@master-1:/home/k8s# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://192.168.41.134:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
It shows that the cluster server address is  https://192.168.41.134:6443, the old one.
So how can I change that to a new one?

**Comment by dixudx** [comment]
@chenqy930 You can try to manually update this conf file.

Seems something got misconfigured during the installation.

**Comment by errordeveloper** [comment]
After you do `kubeadm init`, you need to copy `/etc/kubernetes/admin.conf` to `~/.kube/config`. It looks like this was done once, but not after the user ran `kubeadm init` the second time.

/close

**Comment by ukreddy-erwin** [comment]
The IP address of the k8s master should be updated as we moved to a different network.How to update that instead of completely resetting the kubeadm. As there are many nodes, it is pathetic to join them again.
