### ISSUE TITLE
code-generator: add "This file is generated" to every generated file

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#56489]
This is a follow-up of https://docs.google.com/a/google.com/document/d/1N1pBov7Odpg_u-kILHcswYh4VO-aMlYQdFIH64DYeek/edit?usp=sharing.

We could even put the complete command line of the generator in that line.

**Comment by sttts** [comment]
Prototyped https://github.com/kubernetes/kubernetes/pull/56496.

**Comment by cblecker** [comment]
@sttts are you looking for help to carry your prototype? or should we remove the `help wanted` label?

**Comment by rahulkrishnanfs** [comment]
@sttts @cblecker I would like to contribute this issue :-)

**Comment by mattkelly** [comment]
Thanks for pointing me here @nikhita. How do people feel about instead following the convention I outlined here: https://github.com/kubernetes/code-generator/issues/30?

**Comment by sttts** [comment]
> I do think that adding the entire command line is a bit excessive FWIW.

This was only a prototype. And yes, we have command lines that are excessive when printed in the files.

Following the convention of kubernetes/code-generator#30 sounds great.

@rahulkrishnanfs feel free to pick up my prototype PR.

**Comment by anubhakushwaha** [comment]
@rahulkrishnanfs Working on this one? :smile:
