### ISSUE TITLE
pod fails with CrashLoopBackOff

### ISSUE THREAD

**Issue by keithjohnhowe** [kubernetes/kubernetes#56491]
Everytime I try to run this yaml file in minikube it fails with a CrashLoopBackOff error.
I have been tried a number of things to get this working and would welcome some input.
I have included the yaml file and various relevant logs.

$cat alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
spec:
  replicas: 3
  resources:
    requests:
      memory: 400Mi

global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'webhook'
receivers:
 - name: 'webhook'
   webhook_configs:
   - url: 'http://alertmanagerwh:30500/'

 kubectl logs alertmanager-main-0 alertmanager
time="2017-11-28T12:14:32Z" level=info msg="Starting alertmanager (version=0.9.1, branch=HEAD, revision=9f5f4b2a516d35cfaf196530b277f1d109254569)" source="main.go:109" 
time="2017-11-28T12:14:32Z" level=info msg="Build context (go=go1.9, user=root@3b87d661c3dd, date=20170929-12:59:03)" source="main.go:110" 
time="2017-11-28T12:14:32Z" level=info msg="Loading configuration file" file="/etc/alertmanager/config/alertmanager.yaml" source="main.go:235" 
time="2017-11-28T12:14:32Z" level=error msg="Loading configuration file failed: No routes provided" file="/etc/alertmanager/config/alertmanager.yaml" source="main.go:238" 

minikube logs
Nov 28 12:18:08 minikube localkube[3198]: I1128 12:18:08.531398    3198 kuberuntime_manager.go:738] checking backoff for container "alertmanager" in pod "alertmanager-main-0_default(9c3fcc63-d430-11e7-b728-08002736ff5b)"
Nov 28 12:18:08 minikube localkube[3198]: I1128 12:18:08.531602    3198 kuberuntime_manager.go:748] Back-off 5m0s restarting failed container=alertmanager pod=alertmanager-main-0_default(9c3fcc63-d430-11e7-b728-08002736ff5b)
Nov 28 12:18:08 minikube localkube[3198]: E1128 12:18:08.531664    3198 pod_workers.go:182] Error syncing pod 9c3fcc63-d430-11e7-b728-08002736ff5b ("alertmanager-main-0_default(9c3fcc63-d430-11e7-b728-08002736ff5b)"), skipping: failed to "StartContainer" for "alertmanager" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=alertmanager pod=alertmanager-main-0_default(9c3fcc63-d430-11e7-b728-08002736ff5b)"

 minikube version
minikube version: v0.23.0

**Comment by dims** [comment]
@keithjohnhowe - looks like the error is from https://github.com/prometheus/alertmanager/blob/master/config/config.go#L262 So you probably need to open an issue in https://github.com/prometheus/alertmanager/issues rather than here in the main kubernetes repository. sounds fair?

/close
