### ISSUE TITLE
//cmd/kubeadm fails to build in pure Go mode under Bazel due to cadvisor dependencies

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#56516]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

I've been working on updating our `rules_go` dependency to be able to build our "static" binaries with cgo disabled to match the output from the non-bazel build.

It almost works, but `//cmd/kubeadm` is failing to build because it's trying to link in an empty library:
```
ERROR: .../code/kubernetes/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/raw/BUILD:3:1: GoCompile vendor/github.com/google/cadvisor/container/raw/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/raw.a failed (Exit 1): compile failed: error executing command
  (cd .../.cache/bazel/_bazel_jgrafton/75e5737b0f848bf1b7c3ab3303c8bf72/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/compile -go bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/bin/go -root_file bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/ROOT -goos linux -goarch amd64 '-cgo=0' -package_list external/go_sdk/packages.txt -src vendor/github.com/google/cadvisor/container/raw/factory.go -src vendor/github.com/google/cadvisor/container/raw/handler.go -dep github.com/golang/glog -dep github.com/google/cadvisor/container -dep github.com/google/cadvisor/container/common -dep github.com/google/cadvisor/container/libcontainer -dep github.com/google/cadvisor/fs -dep github.com/google/cadvisor/info/v1 -dep github.com/google/cadvisor/machine -dep github.com/google/cadvisor/manager/watcher -dep github.com/opencontainers/runc/libcontainer/cgroups -dep github.com/opencontainers/runc/libcontainer/cgroups/fs -dep github.com/opencontainers/runc/libcontainer/configs -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/golang/glog/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/common/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/libcontainer/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/fs/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/info/v1/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/machine/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/manager/watcher/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/cgroups/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/configs/linux_amd64_pure_stripped/go_default_library~/' -o 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/raw/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/raw.a' -trimpath . -I . -- -p github.com/google/cadvisor/container/raw)

Use --sandbox_debug to see verbose messages from the sandbox
vendor/github.com/google/cadvisor/container/raw/factory.go:23:2: import .../.cache/bazel/_bazel_jgrafton/75e5737b0f848bf1b7c3ab3303c8bf72/bazel-sandbox/4839007188253519489/execroot/__main__/bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/libcontainer/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/libcontainer.a: reading input: EOF
2017/11/28 15:05:07 error running compiler: exit status 1
Target //cmd/kubeadm:kubeadm failed to build
```

The issue seems to be that `cmd/kubeadm` depends on `pkg/kubelet/apis/kubeletconfig/validation`, which in turn depends on `pkg/kubelet/cm` for a few constants.

`pkg/kubelet/cm` is a fairly large package, and it has has build-tag controlled cgo and !cgo variants. The cgo variant depends on cadvisor, libcontainer, and other such cgo-heavy libraries, whereas the !cgo variants do not.

`go build` is pretty lazy about compiling dependencies, so it never builds cadvisor, libcontainer, etc in pure mode. Bazel doesn't have this ability, however, and so it tries to build these libraries in pure mode and fails.

Trying to get these end libraries to build in pure mode seems futile, especially since nobody would ever use them that way. A more viable fix is to break out the constants needed by `pkg/kubelet/apis/kubeletconfig/validation` into a separate package, which simplifies the build and prevents us from ever depending on these cgo-heavy libraries.

I'm not sure if there's precedence for this sort of refactoring, or where exactly the constants should go.

/area build-release

**Comment by ixdy** [comment]
/sig node

maybe?

**Comment by ixdy** [comment]
The offending section of pkg/kubelet/apis/kubeletconfig/validation/validation.go:
https://github.com/kubernetes/kubernetes/blob/8226973ae87688e6bd24ea14a643f2741ce94b4d/pkg/kubelet/apis/kubeletconfig/validation/validation.go#L92-L102

**Comment by ixdy** [comment]
and I think I didn't notice this earlier because `kubeadm` started validating kubelet configs only a few days ago as a result of #56280.

@xiangpengzhao @luxas as FYI (or if you have any thoughts)

**Comment by xiangpengzhao** [comment]
>A more viable fix is to break out the constants needed by pkg/kubelet/apis/kubeletconfig/validation into a separate package

Moving those constants to  `pkg/kubelet/types/constants.go` might be one choice. @mtaufen @yujuhong WDYT?

**Comment by mtaufen** [comment]
Should be ok to move the constants to a common place.

**Comment by xiangpengzhao** [comment]
@mtaufen PR #56516 sent. Please take a look, thanks!

@ixdy how can I verify this issue against the PR #56516 locally?

**Comment by BenTheElder** [comment]
@xiangpengzhao I beleive you can verify this with the changes in https://github.com/kubernetes/kubernetes/pull/56820 applied and then `make bazel-build` or `bazel build //cmd//kubeadm/...`

**Comment by BenTheElder** [comment]
Also it seems your PR link was busted, https://github.com/kubernetes/kubernetes/pull/56661 looks to be what you meant :-)

**Comment by xiangpengzhao** [comment]
@BenTheElder thanks for pointing out the way and my broken link! (I didn't remember why I copied this issue number as my PR number... :sweat_smile: )
