### ISSUE TITLE
The e2e_node/gpu_device_plugin.go test has been failing in the past few days

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#56518]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The test has been failing since Nov 22nd. Looks like it is because the test restarts Kubelet and then calls getLocalNode() which checks for node readiness.
Not sure why this problem only started to show up recently.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ScorpioCPH** [comment]
@jiayingz Hi, Just FYI, [tempSetCurrentKubeletConfig will restart kubelet](https://github.com/kubernetes/kubernetes/pull/54792#discussion_r151065335). Maybe it is helpful for you.
