### ISSUE TITLE
Kubeproxy's Windows proxy modes don't work.

### ISSUE THREAD

**Issue by gkudra-msft** [kubernetes/kubernetes#56522]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: When running `kubeproxy.exe`, and passing the `--proxy-mode=kernelspace` flag which was introduced in [PR #51064 ](https://github.com/kubernetes/kubernetes/pull/51064), the following error occurs:

```
error: KubeProxyConfiguration.Mode.ProxyMode: Invalid value: "kernelspace": must be 
userspace,iptables,ipvs or blank (blank means the best-available proxy (currently iptables)
```

**What you expected to happen**: The proxy should work as it used to, supporting this mode.

**How to reproduce it (as minimally and precisely as possible)**: 

    ./kube-proxy.exe --proxy-mode=kernelspace

**Anything else we need to know?**: This was introduced after the validation was refactored in [this PR](https://github.com/kubernetes/kubernetes/pull/49087) which regressed validation for `--proxy-mode=kernelspace`. IPVS validation (and thus support) was later added [here](https://github.com/kubernetes/kubernetes/pull/53780), but we need another mode for Windows.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0-alpha.0.684+51033c4dec6e00
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`):  Windows Server Core 1709
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by enisoc** [comment]
Tentatively adding milestone so we can track getting consensus on release-blocking status.
