### ISSUE TITLE
GCE cloud provider does not update backend nodes on EnsureLoadBalancer for external LBs

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#56527]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig network
/area cloudprovider

**What happened**:

The cloud provider interface [states](https://github.com/kubernetes/kubernetes/blob/e5aec8645d740123dfc8f1400b66bca05673b833/pkg/cloudprovider/cloud.go#L100) that `EnsureLoadBalancer` should `create a new load balancer 'name', or update the existing one`. The GCE provider does this for [internal load balancers](https://github.com/kubernetes/kubernetes/blob/e57accbd03b1265340fdd266d0afe2b7a8e1c171/pkg/cloudprovider/providers/gce/gce_loadbalancer_internal.go#L408) but not for [external load balancers](https://github.com/kubernetes/kubernetes/blob/e57accbd03b1265340fdd266d0afe2b7a8e1c171/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L675-L676). 

Every other in-tree provider implements `EnsureLoadBalancer` by fully updating the load balancer including updated backend nodes: [AWS](https://github.com/kubernetes/kubernetes/blob/7f8521819d3677c98cf88344d8cbee0b72a681ab/pkg/cloudprovider/providers/aws/aws.go#L3553), [Azure](https://github.com/kubernetes/kubernetes/blob/e57accbd03b1265340fdd266d0afe2b7a8e1c171/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L260), [openstack](https://github.com/kubernetes/kubernetes/blob/e57accbd03b1265340fdd266d0afe2b7a8e1c171/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L767), [cloudstack](https://github.com/kubernetes/kubernetes/blob/e57accbd03b1265340fdd266d0afe2b7a8e1c171/pkg/cloudprovider/providers/cloudstack/cloudstack_loadbalancer.go#L146) 

And the following out-of-tree providers do as well [DigitalOcean](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/loadbalancers.go#L153) and Oracle (not oss yet). 

**What you expected to happen**:

I expect that all cloud providers implement `EnsureLoadBalancer` by creating or fully updating the load balancer if it already exists. 

Related discussion: https://github.com/kubernetes/kubernetes/pull/55336#discussion_r150386720

/cc @MrHohn @wlan0 @luxas @andrewsykim @thockin

**Comment by MrHohn** [comment]
/assign
Make sense to make `EnsureLoadBalancer`  implementation in GCE consistent with others for the ease of up-coming service controller enhancement. This sounds like a 1.10 task.

**Comment by nicksardo** [comment]
@jhorwit2, is this task blocking you on another attempt at refactoring the service controller sync logic?

**Comment by jhorwit2** [comment]
@nicksardo yup
