### ISSUE TITLE
authorize API requests in the API and non-API separately

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#5652]
There are currently two different ways of determining request information: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/handlers.go#L264 and the system of record: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/api_installer.go#L97 that actually dispatches the calls.

Having two mechanisms for determining what verb/namespace/resource/subresource/etc information on the request means that the authorizer can end up out of sync with reality.  Collapsing the determination of request information to a single spot with a separate authorize call is one way to eliminate the duplication and avoid false authorization matches due to out of sync request information parsing.

@smarterclayton I think this would address the problem we're having with subresource policy determinations.

**Comment by smarterclayton** [comment]
In general api_installer knows exactly what to tell policy.  By definition, if you're not using api_installer you dont want api behavior.  So I would say all api calls are handled one way, everything else is by definition not an api call and falls into the "by path" access check.  That would address @erictune's original concern about being able to bypass access control by accident - api installer always enforces, and there's a wildcard outside of it:

**Comment by erictune** [comment]
Yeah, this is working as intended, like Clayton says.  Okay to close?

**Comment by smarterclayton** [comment]
This was a placeholder for david to update the policy to integrate tightly with api_installer (for knowing what we're operating on, like admission controller) and loosely on all other resources.

**Comment by smarterclayton** [comment]
We fixed this.
