### ISSUE TITLE
should move GPU support into DevicePlugins option?

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#56553]
I noticed a device-plugin model was described by the document below:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md
And the document says:

> The targeted devices include GPUs, High-performance NICs, FPGAs, InfiniBand, Storage devices, and other similar computing resources that require vendor specific initialization and setup. 

So, the manage of GPU should be part of device-plugin.
However, currently the way to support GPU is adding kubelet Accelerators option.
And the way to support device-plugin feature is adding kubelet DevicePlugins option.

Is this temporary? Should move GPU support option into DevicePlugins?

**Comment by lichuqiang** [comment]
Yep, GPU has already been supported by DevicePlugin, you could find related plugin implementation [here](https://github.com/NVIDIA/k8s-device-plugin),
but for now, since DevicePlugin is alpha, we did not remove the original support for GPU, and meant to remove it once the feature is considered stable enough.

**Comment by tengqm** [comment]
Another thing where people may get confused is that the current GPU usage is not properly gated by the "Accelerators" feature gate: #55680.
The long term direction, as @lichuqiang commented, is to converge to the device plugin model. You can find more from the umbrella tracker: #53497

**Comment by WanLinghao** [comment]
@lichuqiang , so in the future , should we remove the whole Accelerators option?

**Comment by lichuqiang** [comment]
I think so, since the flag is for GPU only, If I'm not mistaken

**Comment by WanLinghao** [comment]
@lichuqiang @tengqm 
I have read the code under ./pkg/kubelet/cm/deviceplugin/ 
The story goes like, kubelet creates a grpc server and the plugin communicates with it by socket.
Among them, Register() function works as registering a plugin.
However, I can't find any invoke of Register() function on k8s.
So how it was registered, who  are supposed to make a plugin register request?

**Comment by lichuqiang** [comment]
You could find API definition in ./pkg/kubelet/apis/deviceplugin

**Comment by tengqm** [comment]
@WanLinghao https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md

**Comment by cmluciano** [comment]
related https://github.com/kubernetes/kubernetes/issues/54011

**Comment by mindprince** [comment]
The documentation at https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/ is updated to talk about GPU support through device plugins now. (PR https://github.com/kubernetes/website/pull/6736)

Accelerators feature gate is deprecated: https://github.com/kubernetes/kubernetes/pull/57384

/close
