### ISSUE TITLE
/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go should be name to elasticsearch_logging_discovery 

### ISSUE THREAD

**Issue by howudoing** [kubernetes/kubernetes#56560]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go should be name to elasticsearch_logging_discovery .
In /cluster/addons/fluentd-elasticsearch/es-image/run.sh and /cluster/addons/fluentd-elasticsearch/es-image/Dockerfile, filename "elasticsearch_logging_discovery" without ".go" is used, so if filename is "elasticsearch_logging_discovery.go", build will fail.
 
**What you expected to happen**:
as mentioned above

**How to reproduce it (as minimally and precisely as possible)**:

as mentioned above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by crassirostris** [comment]
Dockerfile points to a binary, not a source file. Everything WAI, please take a look at the Makefile
