### ISSUE TITLE
Kubelet can orphan pod dirs

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#5657]
In a pathological case, it seems that kubelet's pod-dirs (a checkpoint, more or less) can get orphaned.

1) create pod
2) kubelet crashes
3) api server deletes pod
4) docker containers for that pod die
5) kubelet restarts

The /var/lib/kubelet/pods/$uid dir is orphaned.

Kubelet should look for orphaned pods by scanning that and checking the live state and deleteing anything that it can, same as we do with volumes.

**Comment by thockin** [comment]
@dchen1107

**Comment by vmarmol** [comment]
Assigning to myself.

**Comment by thockin** [comment]
Related: Let's be cautious about expanding checkpointing - it is tempting
to drop more info into these dirs, and it would overall make kubelet
cleaner (e.g. I'd LOVE to get rid of volume Builder/Cleaner).  I think we
SHOULD checkpoint more but we should put energy into a common way to do
that reliably, given our wealth of scars around this from internal work :)

**Comment by dchen1107** [comment]
In a long term (not v1 blocker though), we need a disk manager in kubelet like what I mentioned in another PR review since image GC is indeed related to Container GC. Cleaning up those orphan dirs is another example. We should have a consistent policy on container / image / pod recycle.

**Comment by thockin** [comment]
My point was that the existence of those dirs is a checkpoint of sorts - we
can use that for better cleanup, but we should proceed carefully :)

**Comment by vmarmol** [comment]
LOL, interestingly enough this is already implemented and it was implemented ~2.5 months ago by you @thockin :)

https://github.com/GoogleCloudPlatform/kubernetes/commit/ca89aa6528c918985d3527f9b7aa76aa0c219696

Closing as fixed.

**Comment by thockin** [comment]
No, I fixed orphaned volumes, but this is about the pod directories.  I was able to manually win the race and have a pod dir that never gets cleaned up even though the pod is long gone.

**Comment by yujuhong** [comment]
@thockin, I think you did implement this in https://github.com/kubernetes/kubernetes/commit/ca89aa6528c918985d3527f9b7aa76aa0c219696#diff-bf28da68f62a8df6e99e447c4351122dR1068
I don't think we use the pod directories as checkpoints at all in kubelet as of now.

**Comment by thockin** [comment]
I don't think this is resolved, but I am somewhat removed from kubelet - it's pretty easy to test manually

**Comment by bgrant0607** [comment]
Believed to be obsolete.
