### ISSUE TITLE
Enhance "resourceNames" field's capability in RBAC Roles to give permissions to all instances of a resource matching some pattern

### ISSUE THREAD

**Issue by mayanksinghsachan** [kubernetes/kubernetes#56582]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Currently, we are using `resourceNames` field in RBAC roles to allow permissions for a particular instance of any resource(like pods, secrets. etc) like below
```
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["my-pod"]
  verbs: ["get"]
```
But consider a situation where we create a *deployment*with name say "my-deployment" and now we want to give permissions to check logs of pod(created by this deployment). Pods created by deployment will have name like `my-deployment-xxxxx-xxxx`.
So, We can add `resourceNames: ["my-deployment-xxxxx-xxxx"]` in role which will give permissions only for pod with name `my-deployment-xxxxx-xxxx`.
But if this pod get deleted, then deployment will create new pod with name say `my-deployment-yyyyy-yyyy`. So, now we have to update existing role with `resourceNames: ["my-deployment-yyyyy-yyyy"]` to give permissions for new pod `my-deployment-yyyyy-yyyy`.

**What you expected to happen**:
`resourceNames` field in RBAC role should be enhanced to give permissions to all instances of a resource matching some pattern.
For example, if we define `resourceNames: ["my-deployment"]` in role, then user should be given access to all instances of a resource which contains string "my-deployment" in instance name.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`): `GitVersion:"v1.8.2-2+d68ca389c3219c"`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by mikedanese** [comment]
Subdividing namespaces is not trivial. The current advice is to use different namespaces. Are you primarily concerned with dividing access between users or service accounts?

**Comment by mayanksinghsachan** [comment]
@mikedanese It has nothing to do with subdividing namespaces. Also, this feature request is neither specific to users nor service accounts.

@dixudx @liggitt 
Actually my requirement is to have a Role which gives permissions to a user to check logs of pod which are created by some deployment and even if pod gets deleted and new pod gets created by deployment, then admin should not have need to update existing role.

But with the current RBAC features, we can define role like below to check logs of a pod created by some deployment:
```
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: ["my-pod-xxxx"]
  verbs: ["get"]
```
But when that pod gets deleted, then deployment will create new pod and admin has to update existing role to give user permission for checking logs of new pod created by deployment.

**Note: I think current way is not feasible as admin has to continuously monitor when pod created by deployment got deleted and new pod got created and then admin need to update existing role accordingly each time**.
So, I feel `resourceNames` field in RBAC role should be enhanced to give permissions to all instances of a resource matching some pattern as mentioned in description section of issue.

**Comment by liggitt** [comment]
Subdividing access on name prefix isn't a strong subdivision. Permissions that allowed access to a pods for a deployment named "my" would also allow access to pods for a deployment named "my-app"

**Comment by mayanksinghsachan** [comment]
@liggitt Agree.
Do you think is there any other good way to satisfy my requirement given in issue description??

**Comment by liggitt** [comment]
Not really. I think attempts to subdivide namespaces ("access to logs of pods from only some deployments", etc) like this are likely to be both complex and fragile. I'd echo what @mikedanese said.

**Comment by phemmer** [comment]
I'm also in the same boat of needing this feature. Our situation is that we have a "production" namespace, a "staging" namespace, etc, of which all our various applications are deployed to. We want to grant each application owner access to their own resources, but since names of things like pods are auto-generated, we can't without granting access to the whole namespace.

The `nonResourceURLs` attribute already supports this by way of adding a trailing `*` to the value.

**Comment by dedsm** [comment]
I have a similar request, it would make rbac really powerful if you can specify a regex in the resourceNames to match, I deploy the whole infrastructure in feature branches in my development cluster into new namespaces with a prefix per user, it would be nice to be able to say something like 
```rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resourceNames: ["userA-*"]
```
to allow that user to manage any namespace as long as they start with "userA-"

**Comment by ericchiang** [comment]
> We want to grant each application owner access to their own resources, but since names of things like pods are auto-generated, we can't without granting access to the whole namespace.

There are more issues than just RBAC here. For example if I have the ability to create a pod, I can mount any secret or service account token from a namespace into that pod, even if RBAC prevents me from getting that secret. That's part of why Mike Danese said earlier that "Subdividing namespaces is not trivial." Even if RBAC was more expressive, the security boundary is still the namespace. 

> to allow that user to manage any namespace as long as they start with "userA-"

The API server doesn't support returning filtered lists based on authorization. If a user lists or watches all namespaces what would they see? Again, adding features to RBAC doesn't change that limitation.

For those following this thread, treat namespaces as the security boundary. Trying to carve up an individual namespace has a lot of nuanced pitfalls.

**Comment by liggitt** [comment]
I would add that prefix matching without a delimiter is generally a bad idea. Letting user `bob` manage all namespaces that match `bob-*` sounds great until user `bob-tables` shows up

**Comment by whereisaaron** [comment]
The current RBAC is pretty limited in this regard. The `resourceNames` attribute is IMHO almost without a use case, since it can't name/identify any workload, not Deployments, StatefulSets, nor Jobs, as Pod names and quantities are dynamic at runtime.

I agree that a pattern match on the names is not the best model either, for the reasons others have expressed above. I suggest RBAC could take a leaf from NetworkPolicy and support a label selector to scope Roles and Cluster roles. I think that gives a clean, intensional match that is consistent with the Kubernetes model for subdividing resources.

It also combines consistently with the `resources` selector, to allow e.g. access to list/describe both Pods and Deployments (but not Secrets) that have the required labels.

**Comment by liggitt** [comment]
> The resourceNames attribute is IMHO almost without a use case, since it can't name/identify any workload, not Deployments, StatefulSets, nor Jobs, as Pod names and quantities are dynamic at runtime.

It is currently used for bounding permissions to specific leader lock resources, and read access to specific secrets/configmaps.

> I suggest RBAC could take a leaf from NetworkPolicy and support a label selector to scope Roles and Cluster roles. I think that gives a clean, intensional match that is consistent with the Kubernetes model for subdividing resources.

See https://github.com/kubernetes/kubernetes/issues/44703#issuecomment-324826356 for a discussion of the issues with label selector support in RBAC.

**Comment by whereisaaron** [comment]
Label selectors for RBAC have been proposed before. And while not rejected as a concept, the implementation requires several breaking changes under the hood, so probably punted to RBAC v2 😐

https://github.com/kubernetes/kubernetes/issues/44703

Looks like that although `resourceNames` is not very useful, but it was something that could be easily added to the current implementation of admission controllers.

We've coded ourselves into a corner here sadly 😥

**Comment by Zatvobor** [comment]
I've moved some `Deployment`s to`StatefulSet`s, so it can be managed/described over `resourceNames`.

And yes, please reconsider the solution for managing `Deployment`.
For example:
```
# a unique identity of StatefulSet pods
resourceNames: [["foo", "*"]]
```
```
# a unique identity of (Deployment) pods
resourceNames: [["foo", "*", "*"]]
```

**Comment by 2rs2ts** [comment]
Another use case: the Kubernetes Service Catalog. It makes secrets based on ServiceBinding names (from what I understand) and we don't want to give it the ability to CRUD _all_ secrets in whatever Namespace is using the Service Catalog to create things with the AWS Service Broker. If we could restrict the secrets it could manipulate to specific names we could avoid giving it an escalation path to get ServiceAccount tokens.

**Comment by 2rs2ts** [comment]
By the way, "fragile" is better than "broken" which is what the current system that requires you to give way too broad access is :)

**Comment by gmatev** [comment]
One other use case to consider here. We have an application that can run in a multi-tenant cluster collocated with other applications. The application itself orchestrates a number of user workloads. Ideally it would be able to deploy some of these workloads in a separate namespace for each user. On a multi-tenant cluster, we would like to find a way to give the application service account the permission to create and delete namespaces, but this should only be limited to namespaces that it creates. Having prefix support in resourceName in RBAC can allow for an appropriately scored ClusterRole and ClusterRoleBinding.

**Comment by jpenekusu** [comment]
My use case is, given a chaos engineering service hosted in a namespace, to make chaos engineering on cluster namespaces. I would like to reduce the attack surface in case the chaos engineering service account is stolen. This is why I would like to be able to create a role that can grant delete permission on pods given a pattern match on pod resourceName (i.e: regex) or labels.

**Comment by cameronkerrnz** [comment]
I've been looking at how to configure similar restrictions. In my use-case, I have a pod that is running shinyproxy (has backends for Docker Engine, Docker Swarm or Kubernetes); this pod will talk to the Kubernetes API to create and delete pods that run shiny-server; each with a slightly different configuration (it starts one pod for each user and shuts down the pod on logout or after some period).

I have created a ServiceAccount and a local Role and RoleBinding which effectively has to give it access to do all-things to all pods in its namespace. Obviously not a good security posture (eg. if broken into it could start pods that do crypto-mining)

Looking at the above commentary it is fairly clear that extending resourceNames to support a pattern could be useful for pods, but only to the extent of read-only operations. For anything that involves changing pods it would appear to be a weaker mechanism than would be desired; I would rate it similar to sudo in that regard (which in itself would point to value, but one that could easily lead to unexpected insecurities in configuration).

Presumably OPA (OpenPolicyAgent) is the answer to this. OPA is a CNCF Graduated project and seems to at least be firmly on the radar of K8S distributions such as OpenShift and Rancher at least, and has Google and Microsoft as some of its key contributors (see https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/). OPA effectively involves a validating (and mutating) admission webhook, but with an implementation where the policy language and machinery are already created for you. In my use-case, it would be very useful for ensuring pod creation/mutation/deletion requests that shinyproxy is making to the K8S API match expectations.

Without OPA (or something like it), I would need to use multiple namespaces (shinyproxy in one namespace, its pods in another), but that is only a partial solution; OPA would provide for a stronger and more flexible set of controls.

**Comment by davi5e** [comment]
IMHO I don't think OPA should be considered the way to go...

There could be a way to cascade RBAC permission where applicable, as for example having readonly permissions to Deployments would yield the same permissions to its ReplicaSets and then further down to Pods. Like so resourceNames would become very useful...

There could be some CRDs where this would also help. Take cert-manager, where issued certificates are represented by Secrets in a namespace. The same logic would apply.

Overall, I don't know if this get into "subdividing namespaces" territory, but if at all feasible we'd all benefit while broadening the current use case for the resourceNames field.

**Comment by tap52384** [comment]
Is it possible to create a role that would apply to pods with the same label? If so, that's one way to fix things.

**Comment by rcmorano** [comment]
JFTR, the use case that brought me to this issue is I have a `Job` that I would like it would be able to delete/restart some pods, but obviously, I cannot know before hand the name the pod for the job will take so I cannot define the appropriate RBAC.

**Comment by thannaske** [comment]
I stumbled across this while attempting to limit a ServiceAccount to manage SSL certificates which are stored as Secrets alongside with application specific-secrets the SA should not be able to read. In my opinion this is a valid use case for this feature request without violating the principle of resource separation by Namespaces.

**Comment by leewoobin789** [comment]
setting rules based on certain wildcarded reource names would bring enormous benefits in ecosystems and also other cncf projects, where the RBAC ClusterRoles are having way too high privileges. i kindly ask you to reconsider it again. :)

**Comment by thomas7kuo** [comment]
Please reopen this issue. I have a legit [use case](https://stackoverflow.com/questions/70356303/k8s-access-control-to-single-pod/70358418#70358418) and it could enhance the security and access control for many systems

**Comment by donistz** [comment]
We also have a problem that can be resolved with a pattern for the resource inside RBAC. We want to grant read access for some dynamically created secrets in the namespace to users who should not be able to read all secrets of that namespace.  We don't want to maintain dynamically the role definitions for our service account and users every time when a new secret is created.

**Comment by pierluigilenoci** [comment]
> Please reopen this issue. I have a legit [use case](https://stackoverflow.com/questions/70356303/k8s-access-control-to-single-pod/70358418) and it could enhance the security and access control for many systems

@thomas7kuo you can try to do a PR for the case in question and I am sure that if all safety and design requirements are met it will be approved.

**Comment by sjwl** [comment]
What if we leverage the [labelSelector](https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/#labelSelector) method?

```
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceSelector:
    matchLabels:
      appID: my-app-id
  verbs: ["get"]
```

not suggesting the implementation would be easier just because we're leveraging a familiar method used for other areas like [podSelector](https://kubernetes.io/docs/reference/_print/#NetworkPolicySpec) or [namespaceSelector](https://kubernetes.io/docs/reference/_print/#MutatingWebhookConfiguration), only that it's a method well understand already and not introducing something new like a regex expression to define scope.

**Comment by ghostsquad** [comment]
Any chance this can be reopened?

**Comment by pierluigilenoci** [comment]
@mar-pan @ghostsquad this ticket has been closed for 4 years, I assume that the chances of it being reopened are very low.

I share the hope with you but I assume that it is more effective to try to reopen a new one (linking the old one in the description). 😉

**Comment by liggitt** [comment]
> What if we leverage the [labelSelector](https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/#labelSelector) method?

That requires access to information (content of the incoming and/or existing object) the Kubernetes authentication layer does not have. Authentication only has access to information in the request headers and URL.

> I assume that it is more effective to try to reopen a new one (linking the old one in the description). 😉

Please don't do that, this is unlikely to make progress as a new issue that's a duplicate of this one. A proposal that works through the design along with the implications of such a change can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps), but the feedback from area maintainers has consistently been that subdividing access to objects within a namespace based on fuzzy-matching of names is not recommended.

**Comment by tyger** [comment]
Writing to check if anything changed on this front and this request can be reopened?

My understanding so far:
* As auth system of K8s does only takes into account URL and header of REST API request, there is no technical limitation to implement wildcard functionality for `resourceNames` property.
* The fact that it might be misleading is recognised and seems to be generally accepted by requesters, however it will require disclosure in documentation that wildcards shouldn't be taken lightly.
* Comment above about giving permission to create pod, won't protect from getting access to secrets is not really relevant here as it will work that way without wildcards anyway.

Is there any particular impediments to implement it except for "it is not recommended to subdivide namespaces"? 

I believe the essence of the ask here is to make auth filtering rules a bit more flexible, that's it, no expected change of the authentication and authorisation concepts.

**Comment by antonmatsiuk** [comment]
another use case for this is to allow port-forward of a specific Pod. Since Deployments/ReplicaSets create Pods with dynamic names, it's not possible to limit without wildcard support on `resourceNames`

**Comment by SamuZad** [comment]
@liggitt is there any chance this issue could be reopened?

As people have pointed out, there are legit use cases (such as pods with or jobs which have dynamically created names), for which this would help immensely. 

As others have pointed out, the requesters acknowledge that there would be risks associated, but the alternative is arguably worse:

For instance, having to give access to users to exec into all pods in a namespace because there is no way to natively handle dynamically generated pod names

And not every use case can be handled by "external" policy engines

**Comment by JuryA** [comment]
Hello,

I understand your perspective on the subdivision of access based on name prefixes. However, I must respectfully disagree. From an RBAC standpoint, allowing wildcards in determining access control can be a powerful tool when used responsibly by knowledgeable administrators. It is not a bug, but rather a feature that can be harnessed effectively.

In my opinion, label selectors and wildcards should be allowed as they can make it easier to manage resources and avoid conflicts with different prefixes. Administrators should be trusted to use these tools properly without the need for excessive hand-holding.

I fully agree with @tyger... Now, it's not safer but even worse. No offense...

**Comment by yellowpattern** [comment]
In trying to come up with a way to deal with #121800 , it is necessary to grant a service account permission to delete pods. I don't want the service account to be able to delete any pod, rather just the ones that get orphaned from jobs.

This is a frustrating situation: kubernetes doesn't want to automate pod cleanup after jobs and kubernetes doesn't want to provide safety mechanisms for automating the cleanup of said pods through custom scripts.

**Comment by atheiman** [comment]
1. I don't understand why this issue is closed, you have dozens/hundreds of users requesting it with valid use cases.
1. I don’t understand why adding more capability in rbac rules with a glob syntax is fundamentally rejected. The only reason I see given in this thread is that a rule could accidentally specify more resource names than intended. Well with the current implementation administrators have to grant access to *every* resource because `rules.resourceNames` is impractical to update with dynamic named resources.<br/>If administrators cannot use a new `resourceNames` glob syntax safely, then they are probably already omitting `resourceNames`. And if they determine the glob syntax is too dangerous, they can just not use a wildcard in any of their rules. But they will quickly find that they need a wildcard for a scenario similar to the dozens of use cases listed above.

**Comment by cbaenziger** [comment]
I think there's some very cool work being discussed in SIG-Auth which might address my use-case here.

See [slide 19 of KubeCon NA 2024 presentation "Pushing Authorization Further: CEL, Selectors and Maybe RBAC++"](https://static.sched.com/hosted_files/kccncna2024/07/SIG-Auth%202024%20Deep%20Dive%20-%20Pushing%20Authorization%20Further.pdf) which lists "Allow access based on namespace or name prefix" as a user-story being considered.

**Comment by kdx99** [comment]
We have users we want to give the permissions to update namespaces, except those starting with openshift- and kube-.
At the moment we must give them permissions for all namespaces which gives creative users the possibility to read out resources they shouldn't. If we could use regexes for namespaces in clusterroles the situation would be much more secure.

As for the arguments from further-up related to the denial of that feature:
- _"Subdividing namespaces is not trivial. The current advice is to use different namespaces."_
  -> Namespace names are not known ahead. We can only provide an exclude list.
- _"Permissions that allowed access to a pods for a deployment named "my" would also allow access to pods for a deployment named "my-app""_
-> It is in the scope of the user to configure properly regex and permissions. Otherwise new features could not be implemented at all by fear of misconfiguration.
- _"attempts to subdivide namespaces like this are likely to be both complex and fragile"_
-> Providing global permissions by lack of more granular config options makes things much more fragile.

**Comment by jglick** [comment]
HNC seems like it would have been a cleaner solution for certain use cases, but is apparently abandoned (https://github.com/kubernetes-retired/hierarchical-namespaces/issues/405 https://github.com/kubernetes/org/issues/5484) with discussions mentioning https://projectcapsule.dev/ and https://cybozu-go.github.io/accurate/ as possible alternatives.
