### ISSUE TITLE
Feature request: Include resource annotations in audit report Metadata level

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#56586]
We would like to create a "trusted" application deployment history using audit logs https://github.com/kubernetes/features/issues/22. When we deploy YAMLs in Kubernetes , we annotate them with git commit hash. Now, we want to write an audit webhook that to create a deployment history/timeline based on that information. From the docs this seems possible for the main api server. I saw that aggregate servers are not supported yet. https://github.com/kubernetes/kubernetes/issues/54551

One of the limitations of `Metadata` log level is that it does not include resource annotations. So, we need to set log level to `Request` which will have potential performance implications.

@crassirostris told me on slack that there will be support for filtering in future releases for audit logs. So, I wanted to file a feature request for this use-case.

/cc @crassirostris @liggitt @soltysh @bgrant0607

**Comment by tallclair** [comment]
I'm going to argue against this feature for 2 reasons:
1. Annotations can contain arbitrary data, and thus be arbitrarily large. The matadata log-level should not (for performance & storage).
2. The metadata log-level does not include any information from the request object, so the object doesn't need to be decoded to log it. This is beneficial for performance, but also lets us log (at metadata) objects that the apiserver doesn't understand (e.g. in the aggregated apiserver case).

Given the above, I think it's better to add this to the usecases for log filters, and log at the request-level while filtering out the bulk of the request.

**Comment by soltysh** [comment]
I agree with @tallclair here, so this should not be re-opened. 
/close
