### ISSUE TITLE
locked up on building

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#56597]
+++ [1130 00:59:11] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/openapi-gen
+++ [1130 00:59:23] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1130 00:59:23] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1130 00:59:24] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
    vendor/k8s.io/apiextensions-apiserver
    plugin/cmd/kube-scheduler
    cluster/gce/gci/mounter

**Comment by duglin** [comment]
sorry for the sig/testing label - was just testing something. Perhaps someone could remove it for me?

**Comment by cblecker** [comment]
@Gr1dd We need some more information..
- What environment (OS/ARCH) are you building under?
- What branch/commit are you building?
- What command did you use to build?

**Comment by nikhita** [comment]
Is this issue still valid? `make` seems to work fine (even on HEAD).
