### ISSUE TITLE
Need example: NFS server

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#5659]
Now that #4601 is merged it would be great to have an example pod that ran an NFS server against a GCEPD (for now, and a persistent volume when it is in)

**Comment by jsafrane** [comment]
AFAIK running a NFS server as a pod is impossible for two reasons:

1) NFS needs at least two ports. 111/udp (or tcp; portmap) and (usually) 2049/tcp (NFS). More ports may be needed for rpc.mountd, rpc.lockd, rpc.statd, rpc.rquotad, rpc.idmapd etc. For now, kubernetes can't handle one service with two or more ports. Tracked as #1802.

2) NFS clients need to know IP/hostname of the service in advance to create appropriate .yaml. From [example yaml](../blob/master/examples/storage/persistentvolume-nfs-example.yaml):

    nfsMount:
       server: "172.17.0.2"
       path: "/tmp"
       readOnly: false

AFAIK, at the time of definition of the pod, the hostname or IP address of another service (=NFS server) may not be known yet. Using a service name (or labels) would probably help here. So far I did not notice any DNS being set up by Kubernetes.

**Comment by thockin** [comment]
to 1) it is possible to fake this with two services, but multi-port is
coming soon (O(days))

2) You can spin up your NFS server with a static IP or we should make sure
hostnames work in nfsMount (which should probably just be called nfs,
actually)

We definitely set up DNS for services.

**Comment by ddysher** [comment]
Going to take a look at this issue if no one is already working on it.

**Comment by jsafrane** [comment]
I'm looking at it too. I'm learning all this stuff on the way and progressing slowly.

I worked around 1) by using nfs4, https://github.com/jsafrane/kubernetes-nfs-example/tree/master/exporter

Now the actual client example...

**Comment by ddysher** [comment]
ok, i'll unassign myself.

I think multi-port service is coming, maybe this is also a good place to demonstrate that?

Also, you need to run priviledged container, which is a cluster wide capability. I hope there is an esier way to run it.

**Comment by thockin** [comment]
Multi-port is in.

**Comment by jsafrane** [comment]
Created PR #6350

Out of curiosity, how do I assign the PR to me? I don't see any button / gear in "Assignee" block.

**Comment by jsafrane** [comment]
The PR was merged. I'll try to "turn it into e2e test" here, as requested by @brendandburns.

**Comment by jsafrane** [comment]
And just for reference, the example is NFSv4 using single port, it is *not* a multi-port service example.

**Comment by jsafrane** [comment]
NFS e2e test: #6755
