### ISSUE TITLE
propose: support kubefed nodeSelector label

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/kubernetes#56609]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
scheduler schedules federated-apiserver to a random availabe node
**What you expected to happen**:
schedule to specific nodes
**How to reproduce it (as minimally and precisely as possible)**:
set up federation service

**Anything else we need to know?**:
I suggest to add a flag to kubefed command, or support a config file to customize deployment

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tengqm** [comment]
@ggaaooppeenngg please consider close this one and file an issue in the kubernetes/federation project (https://github.com/kubernetes/federation).

**Comment by ggaaooppeenngg** [comment]
@tengqm thx, I want to do a simple hack first, and find it's gone in current repo：）
