### ISSUE TITLE
Kubelet can't start with "--cloud-provider=aws"

### ISSUE THREAD

**Issue by max8899** [kubernetes/kubernetes#56610]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

kubelet can't start with --cloud-provider=aws --cloud-config=/etc/kubernetes/cloud-config

**What you expected to happen**:

kubele could start and using cloud-config for aws

**How to reproduce it (as minimally and precisely as possible)**:

Start kubelete with "--cloud-provider=aws --cloud-config=/etc/kubernetes/cloud-config" and the cloud-config file like this(from aws document):

[default]
aws_access_key_id = YOUR_AWS_ACCESS_KEY_ID
aws_secret_access_key = YOUR_AWS_SECRET_ACCESS_KEY

**Anything else we need to know?**:

**Environment**: centos7.3
- Kubernetes version (use `kubectl version`): v1.8.4
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): 
Linux ip-172-31-34-134.us-west-2.compute.internal 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: yum install kubelet
- Others:

logs:
error: failed to run Kubelet: could not init cloud provider "aws": unable to read AWS cloud provider config file: 2:4: illegal character U+005F '_'

**Comment by max8899** [comment]
@kubernetes/sig-<awz>-<bugs>

**Comment by tianshapjq** [comment]
you have to /sig node
BTW, seems there are some unrecognized character in your config file, maybe you can change some special characters and try again.

**Comment by max8899** [comment]
@kubernetes/sig-aws-bugs

**Comment by max8899** [comment]
@tianshapjq I've confirmed many times, it's the same with my working aws credentials. And I'm confusing why there is no doc for this? It cost me many time to read the code to find the cloud config file format.

**Comment by redbaron** [comment]
@max8899 please do `base64 </etc/kubernetes/cloud-config` and paste result here.

**Comment by dims** [comment]
Looks like this was a bad config file. closing bug.

/close

**Comment by sibtainabbas10** [comment]
What was the issue in the `cloud-config`? Can anyone share the correct contents of `cloud-config`?

**Comment by max8899** [comment]
@sibtainabbas10 If you are using aws, replace cloud-config with IAM role will solve the problem, I don't think my config is in bad format, I think the official doc needs to be more specific.

**Comment by sibtainabbas10** [comment]
@max8899 Hi, I would really appreciate it if you could share you cloud-config file or whatever config you made to make it work. Thanks.

**Comment by max8899** [comment]
@sibtainabbas10 

You can assign a role with this policy to your EC2 instances:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}

**Comment by sibtainabbas10** [comment]
Hi @MaSattari, I used the following `cloud-config` 

```
[Global]
KubernetesClusterTag=kubernetes
KubernetesClusterID=kubernetes
```

Make sure you have set a tag on all resources in the form of KubernetesCluster=<cluster name> (Cluster name is usually kubernetes by default)
a) All instances (master and worker nodes)
b) One and only one Security Group for each instance should be tagged. This will be modified as necessary to allow ELBs to access the instance

**Comment by MaSattari** [comment]
@sibtainabbas10 Thak you for your response.
I am using AWS ECR, I was asking for setting this credentials within  cloud-config .
Do you have any idea?

**Comment by max8899** [comment]
Hi @MaSattari 
In my case, I didn't specify any cloud config, starting kubelet with `kubelet --cloud-provider=aws ` and assign your aws ec2 with this IAM role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
``` 
That works for me.

**Comment by max8899** [comment]
@rsareth  It's a template for test:)，you can add permissions according to your demands.

**Comment by rsareth** [comment]
@max8899 Ok :-) thank you for your response.

BTW, do you have some clear tutorials/howtos on how to pull docker images from AWS ECR Registry, please? I didn't find any.

Thanks!!

**Comment by max8899** [comment]
@rsareth may be you can find it on aws docs

**Comment by rsareth** [comment]
@max8899 I just read again and I found it. As I was running the getting started for aws eks, I just added new right to my eks role!!!

Thank you anyway ;-)
