### ISSUE TITLE
should validate admission plugin names --admission-control

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#56614]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
`--admission-control` param is not validated in func Validate 

**What you expected to happen**:

validate admission plugins, if not registered, return err to prevent going on until call `AdmissionOptions.ApplyTo`. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
from the user's perspective, a reasonable error is returned
