### ISSUE TITLE
Random network latency

### ISSUE THREAD

**Issue by terencechow** [kubernetes/kubernetes#56628]
**BUG REPORT**:

> /kind bug

**What happened**:

I am running a kubernetes cluster with 2 restify servers and 1 mysql service. These are run locally with minikube using virtualbox. 1 server is my API and another is my backend which speaks to the local mysql database.

In my restify server I use the audit logger which tells me latency times of a request. Looking at the code of restify, the audit logger tracks the latency of a request from when it is received to the moment it is sent back. Therefore it isn't the moment the Client has received the full response, but the time from when the API has received a request, to when it has started to send a response back.

I'm using Postman as my client. When I use Postman to make a request to my API it says the latency is around 300 ms. However my audit logger from the API says it is only 200ms. 100ms seems like a big difference between my API and Postman, considering this is all within the same computer.

What could cause this difference in latency? Note that the audit logger in my backend shows 100ms, but the audit logger of my API (which does close to 0 processing and is mostly a pass through layer), is showing 200ms, so it seems like there is another 100ms added between servers. Again, 100ms for a request on the same computer seems fairly large no?

In short, I'm seeing an addition 100ms - 200ms for each request on the same computer which seems extremely odd. What could be the cause of this?

**What you expected to happen**:

Response times of the audit logger to match that of Postman

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Local virtualbox using minikube
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Darwin Quills-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by redbaron** [comment]
do numbers converge when you use HTTP keepalive? It might be that 100ms is spent on DNS resolution

**Comment by terencechow** [comment]
Unfortunately I'm not seeing any difference when using HTTP keepalive.

**Comment by terencechow** [comment]
I decided to remove kubernetes from the equation to compare the difference.

Below are the differences between running locally & in minikube kubernetes. The differences are quite significant. almost 2x slower running with kubernetes. I understand there is also an ingress controller in front of my node server in minikube but does that really result in slower performance by 2x? 

What might I be missing and how can I speed this up? I.e. If I have a microservices architecture you can imagine adding an extra 100ms per service means my services can barely make an extra 1 or 2 hops. 

Note everything is local or VM in my tests so there is no network latency

1 node server running locally at port:7000 and mysql running locally at port 3306. 
`ab -c 5 -n 500  localhost:7000/assignments?projectIds=3` 
```
Concurrency Level:      5
Time taken for tests:   5.173 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      127417000 bytes
HTML transferred:       127327000 bytes
Requests per second:    96.66 [#/sec] (mean)
Time per request:       51.727 [ms] (mean)
Time per request:       10.345 [ms] (mean, across all concurrent requests)
Transfer rate:          24055.40 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       2
Processing:    29   51  10.0     48      92
Waiting:       25   49   9.8     46      90
Total:         29   51  10.0     48      92

Percentage of the requests served within a certain time (ms)
  50%     48
  66%     50
  75%     52
  80%     56
  90%     69
  95%     74
  98%     80
  99%     83
 100%     92 (longest request)
```

Running in minikube with virtualbox, local-ingress + 1 node server + 1 mysql-service. 
`ab -c 5 -n 500  backend.dev.myproject.com/assignments?projectIds=3`

```
Concurrency Level:      5
Time taken for tests:   11.711 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      127513000 bytes
HTML transferred:       127327000 bytes
Requests per second:    42.69 [#/sec] (mean)
Time per request:       117.110 [ms] (mean)
Time per request:       23.422 [ms] (mean, across all concurrent requests)
Transfer rate:          10633.07 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0       2
Processing:    28  116  40.0    104     335
Waiting:       16   80  33.9     73     313
Total:         29  117  40.0    104     335

Percentage of the requests served within a certain time (ms)
  50%    104
  66%    118
  75%    134
  80%    147
  90%    169
  95%    185
  98%    225
  99%    280
 100%    335 (longest request)
```

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs
