### ISSUE TITLE
genericapiserver: RecommendedOption should include admission

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#56627]
The admission webhook story of 1.9 includes that extension API server can/will use the admission webhooks registered automatically. For that the webhook admission plugin must be set up in each extension API server. This should be automatic, i.e. part of the `RecommendedOptions`.

**Comment by hzxuzhonghu** [comment]
I can add admission plugin to the RecommendedOptions.

**Comment by hzxuzhonghu** [comment]
Yes, it should be same as audit /authn/ athz.
