### ISSUE TITLE
kubectl --request-timeout no effect for the exec command?

### ISSUE THREAD

**Issue by fengyu10** [kubernetes/kubernetes#56620]
**Is this a BUG REPORT?**:

Uncomment only one, leave it on its own line: 
/kind bug

**What happened**:
i create po use file：
apiVersion: v1
kind: ReplicationController
metadata: {name: gputest2, namespace: hdp-teu-dia}
spec:
  replicas: 1
  template:
    metadata:
      labels: {component: gputest2}
    spec:
      containers:
      - command: [/bin/bash, -c, touch /workspace/gputest.$(hostname).syslog && tail -f /workspace/gputest.$(hostname).syslog]
        env:
        - {name: HADOOP_USER_NAME, value: hdp_teu_dia}
        image: 10.126.98.3:5000/tensorflow.hadoop:1.2.1-gpu-py2-58cluster
        name: gputest2
        ports:
        - {containerPort: 8888}
        - {containerPort: 6006}
        resources:
          limits: {alpha.kubernetes.io/nvidia-gpu: '1', cpu: '2', memory: 2G}
          requests: {cpu: '2', memory: 2G}
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /workspace, name: workspace}
      nodeSelector: {type: gpu}
      volumes:
      - hostPath: {path: /opt/soft/dia/hdp_teu_dia/gputest2}
        name: workspace

Pod operation condition：
![image](https://user-images.githubusercontent.com/31887880/33421507-3dbfbd20-d5ed-11e7-806d-33676b8d570d.png)

I perform the following commands：
date && kubectl exec gputest2-tt944 --namespace=hdp-teu-dia --request-timeout=10s -- /bin/sh -c "sleep 16200" && date
Why didn't command after 10 s end???
or kubectl --request-timeout no effect for the exec command

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use kubectl version):1.6.1
- Docker version 1.12.2, build bb80604
- CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. uname -a): 3.10.0-327.el7.x86_64
- nvidia: Tesla K40c
- nvidia Driver Version: 375.26

**Comment by adelca** [comment]
Why was this closed?
