### ISSUE TITLE
how to renew the certificate when apiserver cert expired?

### ISSUE THREAD

**Issue by EvolveZy** [kubernetes/kubernetes#56626]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.7.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: use kubeadm install

**Comment by ericchiang** [comment]
This is up to the install method and deployment tools. The Kubernetes API server doesn't have logic to do rotation.

For kubeadm's case, you'd need to use the CA kubeadm generates to sign a new serving certificate for the API server, replace the existing key and cert file on disk, then restart the API server.

You might want to ask in https://github.com/kubernetes/kubeadm/issues for kubeadm specific instructions for this.
