### ISSUE TITLE
The Device Plugin with normial network interface controller to Pod 

### ISSUE THREAD

**Issue by kweisamx** [kubernetes/kubernetes#56634]
/sig network 

I see the doc of kuberentes device plugin at this [link](https://kubernetes.io/docs/concepts/cluster-administration/device-plugins/)

Could I ask if the device plugin support normal NIC that we use in our server or computer for container?

Thanks

**Comment by tengqm** [comment]
What is the use case you want to support? The device plugin framework is pretty flexible. Do you see a particular use case that warrants a change to the framework?
If there is no additional requests, please consider close this issue?

**Comment by fabiand** [comment]
This is an additional request.

After all network devices are just another host resource.

**Comment by vishh** [comment]
Network setup for pod IIUC is handled by runtimes. I don't see how device plugins can help since it is at the kubelet level. 
What if the underlying runtime does not employ network namespaces?

**Comment by fabiand** [comment]
@vishh I do not disagree.
But let me ask from a different angle: Shall device plugins live up to become the _generic_ way of providing "devices" or "host resources" to pods and containers - to workloads?

If yes, then we need to take more devices (including networking) into account, and potentially enhance the DP API.

If no, then it would be helpful to narrow the scope of DPs.

**Comment by BSWANG** [comment]
The resources for device plugins allocated are container level. But the network interfaces are pod/sandbox level.
