### ISSUE TITLE
CPU/Memory resource not allocated on a windows server 2016 node

### ISSUE THREAD

**Issue by messmerxx** [kubernetes/kubernetes#56637]
**this is a BUG REPORT**:

**What happened**:
I have created a kubernetes cluster with one master (linux ubuntu) and one node (windows server 2016) in AWS environment. After i can use RDP to remotely log into the windows server 2016 node. on this node, i have downloaded kuberntes releases for windows node (kubectl, kubelet etc.). 

I can start kubelet to connect to the api server (master). the node status is ready. but when i executed command "kubectl edit node ...windows_server2016_node_name...", i see that the "CPU" "Memory" in "allocatable" and "capacity" are always set to 0. so if i create a deployment or deploy a pod to windows node, it will fail. because the cpu/memory is always 0 and the scheduler can not deploy a pod to the node.
 
what could be the reason? on linux, it is possible to set "kube-reserved" and "system-reserved", i do not think it is possible for windows server 2016. 

so how the cpu, memory resources are allocated on a windows server 2016 node?

**What you expected to happen**:
i expected the cpu/ memory resources to be able to be allocated for pod deployment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes 1.8.3
- Cloud provider or hardware configuration: AWS EC2, Windows server 2016 with containers (node machine), ubuntu amazon linux image (master)
- OS (e.g. from /etc/os-release): ubuntu 4.4, windows server 2016
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

here is one screenshot.
![resourceallocation_windows](https://user-images.githubusercontent.com/19169562/33440613-ba4720ce-d5f0-11e7-8a55-001e83766d41.PNG)

here is my node informaiton. some fields are empty and not set automatically. could the problem have something to do with the nodeinfo?

![resourceallocation_windows1](https://user-images.githubusercontent.com/19169562/33442870-7cd7ebdc-d5f6-11e7-88ab-26991bcaec3e.PNG)

**Comment by dashpole** [comment]
cc @kubernetes/sig-windows-bugs

**Comment by messmerxx** [comment]
Hi dashpole, with "cc @kubernetes/sig-windows-bugs", will this issue be sent to the mailing list? Thanks a lot. hope, i will get a response as soon as possible. 
it should be a fundamental problem to deploy applications in windows server 2016 with containers.

**Comment by michmike** [comment]
hi @messmerxx , which instructions did you use to set up your cluster?

**Comment by messmerxx** [comment]
hi @michmike, thanks for your reply.
i followed the instruction like this:
https://kubernetes.io/docs/getting-started-guides/windows/

i have created a windows server 2016 node. on this node, i have downloaded kubernetes 1.8.3 binaries for windows node. on the node, i started the kubelet.exe. i can register this windows node with linux master successfully.

on the master, i ran "kubectl get node", the node is ready. if i ran "kubectl edit node xxx", i will see, the cpu/memory is not allocated, always with 0. so if i deployed a pod, i will get error. because there is no cpu allocatable for the pod.

any idea to allocate resources on windows server 2016? thanks a lot!!

**Comment by messmerxx** [comment]
@michmike, i think kubelet installed on windows server 2016 node shall be able to allocate resources with kubelet options, right?

i started kubelet.exe with the following command:
PS C:\tools\node\bin> .\kubelet.exe --feature-gates "KubeletConfigFile=true,CPUManager=true" --hostname-override=10.121.
4.112 --resolv-conf="" --kubeconfig "C:\tools\node\bin\manifests\kubeconfig-linux" --node-labels "kubernetes.io/role=nod
e" --max-pods=2

kubeconfig-linux config file:
apiVersion: v1
clusters:
- cluster:
    server: https://api.internal.xxxxxx.com
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
kind: Config
users:
- name: kubelet
  user:
    client-certificate-data: xxx
    xxx

**Comment by michmike** [comment]
@messmerxx  those instructions are outdated. we are updating them with v1.9 of k8s (to be released this month)

here's the most up to date instructions. https://github.com/apprenda/kubernetes-ovn-heterogeneous-cluster

can you please follow them instead?

**Comment by messmerxx** [comment]
@michmike : thank you very much for your information.

right now, i want to deploy my application with a simple kubernetes cluster. one master with linux, one node with windows server 2016.

everything else worked perfectly with 1.8.3. the problem is the cpu/memory allocation on windows node. why the cpu/memory "capacity" and "allocatable" always 0?

what could go wrong? any suggestions? thanks.

**Comment by messmerxx** [comment]
on the windows server 2016 i can create windows docker container images and run the containers successfully.

**Comment by messmerxx** [comment]
with kubernetes 1.8.3, provides kubelet options for windows to allocate the cpu/memory resources? Thank you very much for your reply.

**Comment by bsteciuk** [comment]
@messmerxx This is likely due to running kubelet 1.8.3, which would not have the work done in PR #50396 , which adds Windows server metrics.  I'm currently using a 1.9 kubelet (1.9.0-alpha.3 - which includes the changes made in that PR) on Windows Server 2016, and those node values are filled in for me:
```
status:
  addresses:
  - address: 10.111.36.2
    type: InternalIP
  - address: one9-worker-windows-2
    type: Hostname
  allocatable:
    cpu: "4"
    memory: 4Gi
    pods: "110"
  capacity:
    cpu: "4"
    memory: 4Gi
    pods: "110"
```

**Comment by bsteciuk** [comment]
It's also worth noting, that if you're using Windows Server Core, #55031 will prevent that alpha from working for you.  This has been fixed and will be present in the next beta build due out soon.

**Comment by messmerxx** [comment]
@bsteciuk : thank you very much for your information.

my windows node has the this version info:
windows server 2016, Version 1607, OS Build 14393.1770.

so you mean with this windows server version, kubelet.exe will crash according to the bug report for kubernetes 1.9.3 alpha, am i right? 

when exactly is the beta build?

thank you very much.

best regards,
Kejun Xu
![win_version](https://user-images.githubusercontent.com/19169562/33449525-53c8b47a-d609-11e7-9826-172c0e8aee55.png)

**Comment by messmerxx** [comment]
@bsteciuk my current windows is "Microsoft Windows Server 2016 Base with Containers - ami-ce7ac5a1
Microsoft Windows 2016 Datacenter edition with Containers" from AWS.

if i use "Microsoft Windows Server 2016 Base Nano - ami-c712ada8
Microsoft Windows 2016 Datacenter Edition Nano." from AWS, could it work with kubelet.exe from 1.9.3 alpha?
Thanks a lot!

**Comment by bsteciuk** [comment]
@messmerxx The bug referenced above affects Windows Server Core, which is a stripped down, minimal variant of Windows Server, and since Nano is a stripped down Server Core, it's likely Nano would be affected as well.  

I would expect that the 1.9.0-alpha.3 kubelet would run without hitting that bug on your Microsoft "Windows Server 2016 Base with Containers" machine.

**Comment by messmerxx** [comment]
@bsteciuk thank you very much for your information. i have tried the kubernetes 1.9.3 alpha version on my windows server 2016 node. and it worked!
thanks.

**Comment by sravs1993** [comment]
Hello people,
I tried to create a kubernetes cluster with windows node and linux master. I used the windows server 2016 base ami. My cluster is formed and in linux master it says the node is Not Ready. And in the windows node it says kubelet service does not exist. Can anybody please help me with this?

**Comment by michmike** [comment]
@sravs1993 , your best option for help and support is our slack channel. please post there to get immediate help and guidance
