### ISSUE TITLE
kubectl exec $podname -- /bin/sh -c "sleep 16200", Why run 4 hours is over?

### ISSUE THREAD

**Issue by fengyu10** [kubernetes/kubernetes#56631]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Uncomment only one, leave it on its own line: 
/kind bug

**What happened**:
create RC file:
apiVersion: v1
kind: ReplicationController
metadata: {name: gputest, namespace: hdp-teu-dia}
spec:
  replicas: 1
  template:
    metadata:
      labels: {component: gputest}
    spec:
      containers:
      - command: [/bin/bash, -c, touch /workspace/gputest.$(hostname).syslog && tail -f /workspace/gputest.$(hostname).syslog]
        image: 10.126.98.3:5000/tensorflow.hadoop:1.2.1-gpu-py2-58cluster
        name: gputest
        ports:
        - {containerPort: 8888}
        - {containerPort: 6006}
        resources:
          limits: {alpha.kubernetes.io/nvidia-gpu: '1', cpu: '2', memory: 2G}
          requests: {cpu: '2', memory: 2G}
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /workspace, name: workspace}
      nodeSelector: {type: gpu}
      volumes:
      - hostPath: {path: /opt/soft/dia/hdp_teu_dia/gputest}
        name: workspace

![image](https://user-images.githubusercontent.com/31887880/33430939-4c3d9c26-d60d-11e7-9581-d49dbb8272c9.png)

Now run the following command:
date && /usr/local/bin/kubectl exec gputest-vzt7q --namespace=hdp-teu-dia -- /bin/sh -c "sleep 16200" && date
![image](https://user-images.githubusercontent.com/31887880/33431075-f5e00048-d60d-11e7-928d-a6128b08a511.png)

Why only performed for 4 hours, not 4.5 hours？？？
16200s = 4.5h
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use kubectl version):1.6.1
- Docker version 1.12.2, build bb80604
- CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. uname -a): 3.10.0-327.el7.x86_64
- nvidia: Tesla K40c
- nvidia Driver Version: 375.26

**Comment by luksa** [comment]
I'm guessing something closes the connection after exactly 4 hours. Try running: 
```
kubectl exec $pod -- /bin/sh -c "for i in {1..5}; do echo 'sleeping for 1 hour'; sleep 3600; done"
```
This should keep the connection between kubectl and the API server open.

**Comment by fengyu10** [comment]
@luksa According to the way you perform,
date && kubectl exec gputest-zzjn6 --namespace=hdp-teu-dia -- /bin/sh -c "for i in {1..5}; do echo 'sleeping for 1 hour'; sleep 3600; done" && date
![image](https://user-images.githubusercontent.com/31887880/33467783-fbe84156-d691-11e7-91b6-43e96829f8ef.png)
Run the command over an hour!!!
Why this happens???

**Comment by luksa** [comment]
@fengyu10 is your `/bin/sh` actually busybox? if so, it doesn't handle `for i in {1..5}`properly. Instead, use `for i in 1 2 3 4 5` or ``for i in `seq 1 5` ``
