### ISSUE TITLE
Kube proxy issue |area/kube-proxy

### ISSUE THREAD

**Issue by mmanishpandey** [kubernetes/kubernetes#56640]
Is this a BUG REPORT 

 /kind  bug

Gettting following error in kube proxy logs  , this kube proxy runing on master node 
.12.154:6443: getsockopt: connection refused
E1114 19:39:40.157790       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.196.12.154:6443/api/v1/endpoints?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused
E1114 19:39:40.159497       1 reflector.go:201] k8s.io/kubernetes/pkg/proxy/config/api.go:46: Failed to list *api.Service: Get https://10.196.12.154:6443/api/v1/services?resourceVersion=0: dial tcp 10.196.12.154:6443: getsockopt: connection refused

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+1a3f593", GitCommit:"1a3f593cf0182255938f48eb2e68110c4c049c54", GitTreeState:"clean", BuildDate:"2017-08-02T18:32:44Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+59f69d2", GitCommit:"59f69d284801d7df9639d83f4407cad73ea467be", GitTreeState:"clean", BuildDate:"2017-07-24T23:56:46Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
VM with 24 GB RAM and 16 Vcpu
- OS (e.g. from /etc/os-release):Oracle lunix 7.3
- Kernel (e.g. `uname -a`): Linux den01tdz 4.1.12-61.1.27.el7uek.x86_64 #2 SMP Fri Feb 3 12:31:56 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:kubectl , kubeadm
- Others:

**Comment by cblecker** [comment]
Duplicate of #56642
