### ISSUE TITLE
fluentd-gcp throwing errors "No such file or directory"

### ISSUE THREAD

**Issue by sankate** [kubernetes/kubernetes#56653]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
After upgrading to k8s 1.7.10 I am seeing these errors

`fluentd-gcp: 2017-11-30 23:34:35 +0000 [warn]: emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ sys_fail2 - (/var/log/fluentd-buffers/kubernetes.containers.buffer..b55f3b6683f4036be.log, /var/log/fluentd-buffers/kubernetes.containers.buffer..q55f3b6683f4036be.log)"`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.10
- Cloud provider or hardware configuration: Google GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by janetkuo** [comment]
This is a known regression in 1.7 (more context: #50477) and is fixed in 1.8. We'll need to cherrypick the fix back to 1.7.

**Comment by loburm** [comment]
@janetkuo should we expect that it's fixed in 1.7.12?

**Comment by YacheLee** [comment]
I solved this bug  on 1.8.10-gke.2 by deleting one of the fluentd-gcp pods. But I still can not link the reasons why this happens on GKE 1.8.
