### ISSUE TITLE
OpenStack load-balancer should have a node health-check 

### ISSUE THREAD

**Issue by FengyunPan** [kubernetes/kubernetes#56657]
Related to: #14661

/sig openstack
/assign

**Comment by zetaab** [comment]
@FengyunPan imo it has health-check https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L836 That is added to each member in lbaas pool. It means that if member does not answer it is dropped away from the load.

**Comment by FengyunPan** [comment]
Yeah, that's right.
