### ISSUE TITLE
CloudProvider reconciler/controller for required dependencies

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#5665]
A number of resources in Kubernetes need to be synced with the cloud provider -- disks, VMs, load balancers.  See e.g. https://github.com/GoogleCloudPlatform/kubernetes/issues/5180

Options are:
- Each XController has a big switch statement and calls out to the appropriate provider when a matching resource needs create/delete/update.  For Nodes (VMs), LoadBalancers, firewalls, etc.
- There's a CloudProviderGCEController that's responsible for observing current state of project and updating it to match desired.  Individual within-cluster controllers only concern themselves with intra-cluster changes.

**Comment by smarterclayton** [comment]
I kind of like the latter, in that it doesn't require recompilation of all controllers for one provider changing.  Being able to push more into a cloud provider specific controller over time means they can evolve independently.

**Comment by brendandburns** [comment]
I don't think that this makes the v1.0 list.

**Comment by alex-mohr** [comment]
#5180 tracks adding a reconciler pattern for loadbalancers.  I don't think we have an issue tracking this for other components like firewalls?  If any of the underlying resources disappear, the cluster becomes dysfunctional.  E.g., if something deletes a firewall "owned" by a k8s cluster, we should recreate it.

**Comment by ddysher** [comment]
We already have this problem #3643, how can we eliminate the number of calls?

**Comment by bgrant0607** [comment]
There shouldn't be any big switch statements in the code. The purpose of cloudprovider.Interface is to abstract away differences between different cloud providers. The API we have today definitely isn't sufficient for our needs, however. 

That said, it could make sense to push provider-specific functionality to a pluggable controller. We'd then need to present relevant infrastructure resources and linkages to them in the API.

Either way, I don't think we want to be in the business of implementing basic provisioning mechanisms for every cloud provider under the sun. We should delegate the heavy lifting to an IaaS abstraction layer.

See also #2770.

**Comment by roberthbailey** [comment]
Closing this as the current direction is to move towards cloud-controller-manager binaries, which is being tracked separately.
