### ISSUE TITLE
Nginx C

### ISSUE THREAD

**Issue by amanrawka** [kubernetes/kubernetes#56671]
Hey 
I was trying to set the cookies in the browser using nginx C but not able to change the cookies in the browser, I am making changes in the headers_out.headers in that I am making changes in Set-cookies parameter. The changes are reflected in  the logs, but not able to see in the browser. Also when I reload the page the default cookies gets restored. 

Looking for a solution.

**Comment by dims** [comment]
/close

Can you please open one in the nginx project?
