### ISSUE TITLE
Weird connection performance behavior on NodePort based service

### ISSUE THREAD

**Issue by SukantGujar** [kubernetes/kubernetes#56672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

We are experiencing very weird connection speed issues on a NodePort based Nginx setup. Here's what our setup looks like:

1. There's a Master cluster and then there are several Tenant Clusters.
2. The Master cluster has a NodeJS based gateway proxy which is exposed at port 80/443 as a  k8s LoadBalancer service.
3. Every Tenant cluster has a Nginx gateway service exposed as a k8s NodePort service.
4. All network traffic to tenant clusters is routed from Master cluster Gateway to the Tentant Nginx.
5. Every tenant is assigned a unique sub-domain, e.g.  `performancetest1-fskan`.
6. Tenant traffic reaches Master cluster Gateway in the form of https://(tenant subdomain).dev.p10.io.
7. The Master proxy then routes this traffic to the tenant Nginx.

This image may help clarify the setup:
![trafficerouting](https://user-images.githubusercontent.com/6153264/33469916-8383821c-d68b-11e7-881c-779be39d0a78.png)

We decided to baseline the performance of one of our Tenant service and found something very puzzling... 

When we are making calls using tenant sub-domain (`GET https://performancetest1-fskan.dev.p10.io/svc/explorer`), the average network time is around 350 to 470ms. But when we are directly hitting the tenant (`GET https://104.196.205.173:32022/svc/explorer`), the time is around 700 to 800ms. This is completely unexpected as the sub-domain traffic has two bounces while the IP:NodePort traffic directly hits the tenant NGINX.

Here's a screenshot where the left side represents sub-domain based call, while the right side is IP:NodePort:
![trafficstats](https://user-images.githubusercontent.com/6153264/33470193-f7831f1e-d68c-11e7-8163-ca06a97740ab.png)

Any ideas why the direct call is so slow compared to the bounced sub-domain based call?

**What you expected to happen**:

IP:NodePort based call must not be slower than the sub-domain proxied call.

**How to reproduce it (as minimally and precisely as possible)**:

You should be able to make these calls from your machine as they are public.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7+
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs
