### ISSUE TITLE
version info in v1.9.0-beta.0 is incorrect.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#56699]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig release
/sig cluster-lifecycle
/priority failing-test

**What happened**:
kubeadm-gce-upgrade-1.8-1.9 fails due to:
```
I1130 19:49:18.591] [upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.9.0-beta.0". Enjoy!
I1130 19:49:18.591] 
I1130 19:49:18.591] [upgrade/kubelet] Now that your control plane is upgraded, please proceed with upgrading your kubelets in turn.
I1130 19:49:18.653] + [[ 0 -ne 0 ]]
I1130 19:49:18.654] make: Leaving directory '/workspace/kubernetes-anywhere'
I1130 19:49:18.655] Nov 30 19:49:18.654: INFO: Checking master version
I1130 19:49:33.703] Nov 30 19:49:33.701: INFO: Unexpected error occurred: master had kube-apiserver version 1.9.0-alpha.3.139+e7258eecaa6724 which does not start with 1.9.0-beta.0
```
https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-upgrade-1-8-1-9/158/build-log.txt

**What you expected to happen**:
Test succeeds.

**How to reproduce it (as minimally and precisely as possible)**:
See the runs in https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-upgrade-1.8-1.9

**Anything else we need to know?**:
`wget https://storage.googleapis.com/kubernetes-release/release/v1.9.0-beta.0/kubernetes.tar.gz`

`cat version`:
`v1.9.0-alpha.3.139+e7258eecaa6724`

Oops!

I think this is the reason why the test fails.

/cc @enisoc @luxas @kubernetes/sig-cluster-lifecycle-test-failures 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
@david-mcmahon I see you tagged https://github.com/kubernetes/kubernetes/releases/tag/v1.9.0-beta.0. Can you please help check this?

/cc @dashpole

**Comment by xiangpengzhao** [comment]
Since 1.9.0-beta.1 has already been cut, I think we should update `gs://kubernetes-release/release/latest-1.9.txt`. and this should fix the test. @dashpole can you help update it?

**Comment by xiangpengzhao** [comment]
Another question, I don't find this job config in https://github.com/kubernetes/test-infra/blob/master/jobs/config.json. Am I missing something? @krzyzacy

**Comment by krzyzacy** [comment]
@xiangpengzhao ci/latest-x.x.txt is uploaded by https://github.com/kubernetes/release/blob/master/push-build.sh#L189-L191

**Comment by luxas** [comment]
`https://storage.googleapis.com/kubernetes-release/release/latest-1.9.txt` is now pointing to `v1.9.0-beta.1`, so I'd expect the next job run to succeed

**Comment by enisoc** [comment]
@david-mcmahon and I believe this is a one-time problem due to a bug that existed at the time v1.9.0-beta.0 was built, but was then fixed in https://github.com/kubernetes/release/pull/465.

We also fixed the branch CI by retroactively updating the tag, but the wrong tag had already been baked into the v1.9.0-beta.0 binaries. We didn't consider that a problem because beta.0 is not an actual release.

**Comment by luxas** [comment]
Thanks for the info @enisoc! With https://github.com/kubernetes/release/pull/465 merged I think we can close this then :+1:

**Comment by xiangpengzhao** [comment]
Test case `[sig-cluster-lifecycle] master-upgrade` in https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-upgrade-1.8-1.9 passes now. 

But there are still other failures (`[sig-apps] statefulset-upgrade`, `hpa-upgrade`, `service-upgrade`) in the job. This may need folks from associated sigs to pay some attention.

**Comment by luxas** [comment]
> But there are still other failures ([sig-apps] statefulset-upgrade, hpa-upgrade, service-upgrade) in the job. This may need folks from associated sigs to pay some attention.

@xiangpengzhao This is ok and expected. We don't deploy heapster (needed for hpa-upgrade, don't use a cloud-provided LoadBalancer (needed for service-upgrade) and don't deploy a default StorageClass for PersistentVolumes in statefulset-upgrade. This is all fine and as green as we can get it right now.

**Comment by xiangpengzhao** [comment]
@luxas thanks for clarifying :)
