### ISSUE TITLE
update eventRecorder to handle event series using the new Event API group

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#56694]
before working to start working on #56514 , we need to make changes to the eventRecorder so that it can handles event series.

[The design doc.](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/events-redesign.md) shows how it will work.

/sig scalability

cc @gmarek

**Comment by yastij** [comment]
So from what I've read event series are a set of ismorphic events happening not farther away from each other, how should we estimate this lapse of time ? cc @timothysc @wojtek-t @gmarek

**Comment by timothysc** [comment]
@kubernetes/sig-scalability-misc

**Comment by wojtek-t** [comment]
Reopening, because there are some tests we still want to add before we start using it.
@yastij is working on that.

**Comment by soggiest** [comment]
Since there appears to more work needed on this issue I'm moving this to 1.16
/milestone v1.16

**Comment by yastij** [comment]
@soggiest - closing this as we added the testing for this in #78486

/close
