### ISSUE TITLE
kubernetes-1.9.3alpha, weave-net sandbox pod can not be started "No such network: host" on windows server 2016 node

### ISSUE THREAD

**Issue by messmerxx** [kubernetes/kubernetes#56696]
**like a BUG**:

**What happened**:

i have a kubernetes cluster with a master (ubuntu linux) and a windows server 2016 node. on the windows server 2016 node, i have installed kubernetes binaries for windows node of version 1.9.3 alpha. on my windows node, i tried to execute kubelet.exe to register my windows node to master successfully. on the master, i have created a deployment, a pod shall be created on the windows node and the container shall be started.

on the windows node, i have created a transparent network with the following command:
docker network create --driver transparent transparent
the network "transparent" has been created successfully. and then on the windows node, i set the environment variable:

$env:CONTAINER_NETWORK = transparent

.\kubelet.exe --feature-gates "KubeletConfigFile=true" --hostname-override=10.121.4.112 --resolv-conf="" --kubeconfig "C:\tools\node\bin\manifests\kubeconfig-
linux" --node-labels "kubernetes.io/role=node" --max-pods=2 --allow-privileged=true --pod-infra-container-image="apprenda/pause" --host-network-sources="*"

with the above command, i can register my windows node to my master successfully. my pod was not created successfully. and i have seen the error messages from kubelet.exe

E1201 19:22:15.486973    5012 kuberuntime_manager.go:647] createPodSandbox for pod "weave-net-gt7pj_kube-system(ac13f23d-d6cb-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-gt7pj": Error response fro
m daemon: No such network: host

i have followed the instruction like:
https://kubernetes.io/docs/getting-started-guides/windows/

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

start kubelet.exe on windows server 2016 node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3 alpha
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): windows server 2016
- Kernel (e.g. `uname -a`):
- Install tools:

- Others:

**Comment by messmerxx** [comment]
kube-system   kube-dns-autoscaler-758959bc85-vvzmg                                   0/1       Pending   0          1h
kube-system   kube-dns-d46d5575c-nghk8                                               0/3       Pending   0          4m
kube-system   kube-dns-d46d5575c-vjwpf                                               0/3       Pending   0          2d
kube-system   weave-net-d52g9                                                        0/2       ContainerCreating   0          41s

the above pods can not be started successfully.

the "kube-system" images are linux images. how to switch to windows images?

Thanks.

**Comment by messmerxx** [comment]
code = Unknown desc = failed to start sandbox container for pod "weave-net-rz2pv": Error response from daemon:
No such network: host"
-------
the error message in the above logs. i tried to create a network  with "host" driver on windows node. but without success. the plugin can not be found.
No such network: host" --> does this error message mean that the "host" network driver is used?

**Comment by messmerxx** [comment]
i have made some progress.

but now i still get the problem:
E1201 19:22:15.486973 5012 kuberuntime_manager.go:647] createPodSandbox for pod "weave-net-gt7pj_kube-system(ac13f23d-d6cb-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-gt7pj": Error response fro
m daemon: No such network: host

**Comment by messmerxx** [comment]
No such network: "host"

is a host network required?

**Comment by messmerxx** [comment]
@michmike what could be the problem?
failed to start sandbox container for pod "weave-net-gt7pj": Error response fro
m daemon: No such network: host

thank you very much for your reply.
best regards,
Kejun Xu

**Comment by messmerxx** [comment]
@michmike additional information:

this error is occurred while creating apprenda/pause image. here is a screenshot.

![weave](https://user-images.githubusercontent.com/19169562/33500685-f6c472ce-d6d9-11e7-9f35-93c70bf4c96c.png)

**Comment by messmerxx** [comment]
@michmike 

i found one article. currently, cni networking is not supported on windows server 2016 by kubernetes. any work around to make weave-net pod running on windows node?

thank you very much.

https://blogs.technet.microsoft.com/networking/2017/04/04/windows-networking-for-kubernetes/

Today, with the publicly available versions of Windows server and client you can deploy Kubernetes with the following restrictions:

One container per Pod
CNI Network Plugins are not supported
Each container requires two container endpoints (vNICs) with IP routing manually plumbed
Service IPs can only be associated with one Container Host and will not be load-balanced
Policy specifications (e.g. network security) are not supported

**Comment by messmerxx** [comment]
@michmike it seems to be that you are working on networking for containers on windows server 2016.

perhaps weave net is not yet supported for windows server 2016, can openVSwitch networking work with kubernetes 1.9.3 alpha in a kubernetest cluster with linux master and windows server 2016 node?

http://blog.kubernetes.io/2016/07/update-on-kubernetes-for-windows-server-containers.html

thank you very much.

**Comment by bboreham** [comment]
I can confirm that Weave Net is currently Linux-only.

**Comment by messmerxx** [comment]
@bboreham thank you very much for your confirmation.

in AWS environment with the following settings:
kubernetes 1.9.3 alpha
windows server 2016 as NODE
ubuntu linux as Master

which networking plug-in can work? does anyone have the experience?
calico, open virtual networking?

thank you very much!

**Comment by messmerxx** [comment]
i checked the documentation of open virtual switch, which can support windows.

https://github.com/openvswitch/ovn-kubernetes

but for my small cluster, one master and one windows node, OVN is overwhelming!!!

**Comment by messmerxx** [comment]
E1201 19:22:15.486973 5012 kuberuntime_manager.go:647] createPodSandbox for pod "weave-net-gt7pj_kube-system(ac13f23d-d6cb-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-gt7pj": Error response fro
m daemon: No such network: host

----
for this error, i think kubernetes can not find the host network. why? 

a bug in kubernetes?

thanks

**Comment by michmike** [comment]
hi @messmerxx  we will support a few CNI options for windows when Kubernetes v1.9 is released and we will document them appropriately with the release. Stay tuned for updates in about 2 weeks.

1. Upstream L3 Routing - IP routes configured in upstream ToR
2. Host-Gateway - IP routes configured on each host
3. Open vSwitch (OVS) & Open Virtual Network (OVN) with Overlay - OVS switch extension and OVN controller creates VXLAN overlay network

**Comment by funky81** [comment]
Hi @michmike , any examples for ToR?

**Comment by michmike** [comment]
@funky81 https://kubernetes.io/docs/getting-started-guides/windows/#upstream-l3-routing-topology
