### ISSUE TITLE
AWS NLB service errors with more than one port

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#56703]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

/sig aws

**What happened**:

Create an NLB service on 1.9 with 2 ports, and get this error:

```
I1201 15:16:49.358871       5 aws.go:2753] Adding security group ingress: sg-f8559f84 [{
  FromPort: 30781,
  IpProtocol: "tcp",
  IpRanges: [{
      CidrIp: "0.0.0.0/0",
      Description: "kubernetes.io/rule/nlb/client=a788d91b9d6aa11e7b7f806f096e0fe7"
    }],
  ToPort: 30781
} {
  FromPort: 3,
  IpProtocol: "icmp",
  IpRanges: [{
      CidrIp: "0.0.0.0/0",
      Description: "kubernetes.io/rule/nlb/mtu=a788d91b9d6aa11e7b7f806f096e0fe7"
    }],
  ToPort: 4
} {
  FromPort: 32363,
  IpProtocol: "tcp",
  IpRanges: [{
      CidrIp: "0.0.0.0/0",
      Description: "kubernetes.io/rule/nlb/client=a788d91b9d6aa11e7b7f806f096e0fe7"
    }],
  ToPort: 32363
} {
  FromPort: 3,
  IpProtocol: "icmp",
  IpRanges: [{
      CidrIp: "0.0.0.0/0",
      Description: "kubernetes.io/rule/nlb/mtu=a788d91b9d6aa11e7b7f806f096e0fe7"
    }],
  ToPort: 4
}]
W1201 15:16:49.430537       5 aws.go:2760] Error authorizing security group ingress "InvalidParameterValue: The same permission must not appear multiple times\n\tstatus code: 400, request id: a317f99c-6360-4314-a17c-eeeebfbce0ea"
```

Kubernetes is attempting to create the ICMP rule for MTU discovery once per port, resulting in an error. Creating a service with a single port does not experience this error.

**What you expected to happen**:

The service should be created.

**How to reproduce it (as minimally and precisely as possible)**:

Create a 2 port service in a 1.9 beta cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9 beta1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): any
- Kernel (e.g. `uname -a`): any

Ping @alebdf @justinsb

**Comment by jpds** [comment]
Which release did this land in? I'm seeing this in `1.9.3`.

**Comment by FrederikNS** [comment]
It looks like it only landed in 1.10.0-alpha.2.

**Comment by hellojoshuatonga** [comment]
I'm also seeing this in `1.9.3`

**Comment by baldeynz** [comment]
I'm also seeing this in 1.9.7. Can we please backport this to 1.9.x?

**Comment by nickychow** [comment]
I'm also seeing this in 1.9.9. Can we please backport this to 1.9.x?

**Comment by hristovpln** [comment]
Also on 1.9.10
