### ISSUE TITLE
GCE - configure-helper.sh - masquerade rules that were added in 1.7.11 and 1.8.4 get flushed.

### ISSUE THREAD

**Issue by dnardo** [kubernetes/kubernetes#56727]
It looks like when I cherry picked back the changes from pr/54838 I must have missed the part where we moved the flush up from where we star the kubelet to the configure firewall function.  This causes the rules to get flushed after we write them out.

Fix is to remove the the second flush and cherry pick it back into 1.7 and 1.8

**Comment by MrHohn** [comment]
cc @bowei @thockin

**Comment by MrHohn** [comment]
Ref #54838.

**Comment by MrHohn** [comment]
I believe this is fixed.
/close
