### ISSUE TITLE
Back-port scheduler cache panic fix to 1.8 and 1.7

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#56730]
There was a bug in scheduler which is fixed in 1.9 and later as a part of [this PR](https://github.com/kubernetes/kubernetes/pull/55039). We need to backport it to 1.8 and 1.7.

The sequence of events to trigger this issue is:
 - Pod fails predicates, pod condition was updated with the predicate error.
 - Pod passes predicates
 - Pod fails bind, pod condition was updated with the bind error.

The Conditions in assumedPod is the same ptr as in pod because [assumedPod is a shallow copy](https://github.com/kubernetes/kubernetes/blob/release-1.8/plugin/pkg/scheduler/scheduler.go#L320), not a DeepCopy of pod.
Changing the assumedPod condition causes a cache panic.

/kind bug
/sig scheduling
/assign

**Comment by bsalamat** [comment]
cc/ @yguo0905

**Comment by yguo0905** [comment]
This is great!

**Comment by liggitt** [comment]
Picks appear to have merged

/close
