### ISSUE TITLE
has somebody got weave-net to run on windows server 2016 node in a kubernetes cluster?

### ISSUE THREAD

**Issue by messmerxx** [kubernetes/kubernetes#56744]
can weave-net be supported on windows server 2016 in a kubernetes cluster environment??

i have used:
kubernetes 1.9.3 alpha

if i create a weave-net network with docker on windows server 2016, the error message is "plugin can not be allocated"

if i create a weave-net pod on windows server 2016, i got the error messages.

E1202 10:58:09.775691 7076 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response from daemon: No such network: host
E1202 10:58:09.775691 7076 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response from
daemon: No such network: host
E1202 10:58:09.776690 7076 kuberuntime_manager.go:647] createPodSandbox for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response fro
m daemon: No such network: host

https://github.com/weaveworks/weave/issues/3193

can somebody help?

thank you very much.

**Comment by m-no-2017** [comment]
The thing how "weave-net" works does make it quite "simple" to use under Linux. You basically download the CNI to the respective paths the DaemonSet requires and launch it in the cluster.

If I would try to test a Windows implementation, I'd adjust the mounted volumes for the CNI and lib stuff in the [yaml-daemonSet](https://raw.githubusercontent.com/weaveworks/weave/master/prog/weave-kube/weave-daemonset.yaml) file (at the "volumes" section).

There may be some other Windows CNI solutions that can operate with the respective OS.
The general approach (at my side) would be:
- Start a bare-metal cluster (K8s v1.8)
- Make sure everything is UP&RUNNING
- Launch the weave-net.yaml DaemonSet with adjusted values and see what works (or does not work)

But idk if this is even possible.
(Dependencies to libs, modules, NICs, networking strategy and so on can be a blocker)

**Comment by feiskyer** [comment]
@messmerxx As said by @bboreham at https://github.com/weaveworks/weave/issues/3193#issuecomment-348697832, Weave Net is currently Linux-only, it doesn't run on Windows.

**Comment by feiskyer** [comment]
@messmerxx I'm closing this since this is not supported.
