### ISSUE TITLE
kube-dns-autoscaler create clusterrole failed in k8s 1.6 

### ISSUE THREAD

**Issue by zousheng** [kubernetes/kubernetes#56748]
Hi,

When I tried to deploy kube-dns-autoscaler, the rbac create clusterrole failed due to below error:

rror from server (Forbidden): error when creating "dns-autoscale.yaml": clusterroles.rbac.authorization.k8s.io "system:kube-dns-autoscaler" is forbidden: attempt to grant extra privileges: [{[list] [] [nodes] [] []} {[get] [extensions] [deployments/scale] [] []} {[update] [extensions] [deployments/scale] [] []} {[get] [extensions] [replicasets/scale] [] []} {[update] [extensions] [replicasets/scale] [] []} {[get] [extensions] [replicationcontrollers/scale] [] []} {[update] [extensions] [replicationcontrollers/scale] [] []}] user=&{noah qunar [system:authenticated] map[]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /swaggerapi /swaggerapi/* /version]}] ruleResolutionErrors=[]

any advice? 

thanks

**Comment by liggitt** [comment]
you are trying to grant permissions you do not have. in order to grant permissions via RBAC, you must already have the permissions you are trying to grant.

see https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping for more information

**Comment by zousheng** [comment]
Thanks
