### ISSUE TITLE
kubelet possible CNI network plugins on windows server 2016 node

### ISSUE THREAD

**Issue by messmerxx** [kubernetes/kubernetes#56752]
the kubelet.exe CNI flag can be set by

--network-plugin=xxx

can someone tell me, what are the supported CNI plugins for windows server 2016?

i tried weave-net on my windows server 2016 node, but it failed. weave-net is not supported on windows. #56696

thank you very much.

**Comment by messmerxx** [comment]
https://github.com/kubernetes/kubernetes/issues/56696

**Comment by rjmorse** [comment]
I believe this is resolved by comments at https://github.com/kubernetes/kubernetes/issues/56696#issuecomment-348874784 and updated docs with v1.9 release at https://kubernetes.io/docs/getting-started-guides/windows/
