### ISSUE TITLE
Open Virutal Network/Open VSwitch is the only solution for kubernetes windows cluster?

### ISSUE THREAD

**Issue by messmerxx** [kubernetes/kubernetes#56751]
dear all,

after doing some research, i found out that currently most of the networking plugins are not supported for windows node in a kubernetes cluster.

it seems to be Open Virutal Network/Open VSwitch is the only solution for kubernetes windows cluster. but for my small kubernetes cluster, one linux master and one windows node, OVN is overwhelming!

https://github.com/openvswitch/ovn-kubernetes

what do you think? thanks a lot.

**Comment by rjmorse** [comment]
The [Getting Started guide for Windows](https://kubernetes.io/docs/getting-started-guides/windows/) was [updated a bit after](https://github.com/kubernetes/website/pull/6180) you created this issue.  OVN/OVS is not the only solution for networking in a heterogeneous cluster.  It is probably the most complete option as of today IMO.

**Comment by feiskyer** [comment]
There are also a few other plugins support windows

- [flannel](https://github.com/coreos/flannel/releases/tag/v0.10.0)
- [Azure CNI](https://github.com/Azure/azure-container-networking)
- [overlay and host-gw are WIP](https://github.com/containernetworking/plugins/pull/85)

**Comment by khenidak** [comment]
CC: @jdumars

**Comment by feiskyer** [comment]
Yep, supported plugins have been listed https://github.com/kubernetes/kubernetes/issues/56751#issuecomment-361118099. Let's close the issue.

/close
