### ISSUE TITLE
Test flake: 4.9 kernel vs [sig-network] Network should set TCP CLOSE_WAIT timeout`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#56763]
e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-cncf-canary/475

I think that `[sig-network] Network should set TCP CLOSE_WAIT timeout` fails on a 4.9 kernel.

It appears that the test is looking for `cat /proc/net/ip_conntrack`, but on 4.9 I have `/proc/net/nf_conntrack` instead.
 
cc @bowei @kubernetes/sig-network-bugs

**Comment by krzyzacy** [comment]
(also affecting pr-kops job which blocks the queue http://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kops-aws)

**Comment by justinsb** [comment]
Ah - if it's queue blocking we can just tie 1.10 back to jessie in kops...

**Comment by justinsb** [comment]
PR to have kops use jessie for the stable channel in 1.9 & 1.10 is https://github.com/kubernetes/kops/pull/4002

The jobs I just switched to alpha (https://github.com/kubernetes/test-infra/pull/5783) are going to stay broken, so we still need to decide what to do here.

**Comment by zouyee** [comment]
using nf_conntrack instead?

**Comment by justinsb** [comment]
@zouyee haven't drillled down to know whether it's jessie vs stretch or 4.4 vs 4.9, but yes - on my stretch machines I have nf_conntrack ad not ip_conntrack.  The PR switches back to jessie with 4.4, so we should get ip_conntrack back.

**Comment by zouyee** [comment]
in netfilter group email, you will find 
`ip_conntrack_* helper modules have been replaced by nf_conntrack_* when available and moved from net/ipv4/netfilter to net/netfilter.`

**Comment by bowei** [comment]
That's unfortunate -- anyone have any ideas other than trying both locations?

**Comment by cblecker** [comment]
Looks like this was fixed in https://github.com/kubernetes/kubernetes/pull/57896.
/close

**Comment by jayunit100** [comment]
4.19.126-1.ph3 <- seems like im getting failures in this test on this kernel as well.
