### ISSUE TITLE
`kubectl get all` does not list secrets

### ISSUE THREAD

**Issue by danderson** [kubernetes/kubernetes#56764]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I created a secret with `kubectl create secret generic test --from-literal=foo=bar`, which succeeded. But then when I ran `kubectl get all`, the secret wasn't listed. This confused me for a while, until I tried `kubectl get secrets` and saw that my secret does indeed exist.

**What you expected to happen**:

I expected `kubectl get all` to list secrets.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl create secret generic test --from-literal=foo=bar`
kubectl get all
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

Bare metal cluster, bootstrapped with `kubeadm`.

- OS (e.g. from /etc/os-release):

Debian Testing

- Kernel (e.g. `uname -a`):

Linux pandora 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux

**Comment by stewart-yu** [comment]
See here [https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all)

**Comment by bunyk** [comment]
[Link there](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all) is broken
