### ISSUE TITLE
unable to connect SQL service from other pods

### ISSUE THREAD

**Issue by jk1510karti** [kubernetes/kubernetes#56788]
I've created two pods top of Azure Kubernetes cluster 1) Application 2) MS SQL server

both pods are exposed via Azure Loadbalancer and both having External IPs. I am unable to use the External IP in my application config file. But I can connect that SQL Server from anywhere. For some reason I am unable to telnet DB IP from Application container.

the connection is getting timeout. but I can ping/telnet the DB's cluster ip. So I have tried to use the DB cluster IP in my config file to check if the connection is successful but no luck.

Could someone help me with this ?  sig/azure

**Comment by andyzhangx** [comment]
@jk1510karti could you provide
1. your pod config
2. k8s version
3. your exact repro steps
If you want help, it's better provide detailed info, so other guys could repro your issue easily.

**Comment by jdumars** [comment]
@jk1510karti if this is still a valid issue, can you please provide the info requested by @andyzhangx ?
