### ISSUE TITLE
Prevent the deletion of a PVC that is referenced by an active pod

### ISSUE THREAD

**Issue by arashadahamad** [kubernetes/kubernetes#56786]
**Is this a BUG REPORT 

> /kind bug

**What happened**:
There is a pod which is using pvc(nfs) when I delete pvc first and then delete pod (even with very less different between pod and pvc deletion) then pod goes to in terminate state forever
 This is happened because pvc deleted first before unmounted from pod(by kubelet)
hence unmount failed and it left pod in terminate state.

**What you expected to happen**:
If pvc already deleted then unmounting should happen properly and pod should not be in terminate state.

**How to reproduce it (as minimally and precisely as possible)**:
STEP 1: Create a nfs based pvc
STEP 2- Create a pod which will write the data to pvc
STEP 3- deleted the pvc and pod may be use following command
           $kubectl delete pvc <pvc_name> ; kubectl delete pod <pod name which is using pvc>

**Anything else we need to know?**:
checked on 1.7.4 and 1.8.2 kube version and its re-creatable

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2 and 1.8.4
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu 16.4
- Kernel (e.g. `uname -a`):  4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by arashadahamad** [comment]
FYI,  This looks same as https://github.com/kubernetes/kubernetes/pull/46573 PR

**Comment by stewart-yu** [comment]
I can help to fix it.

**Comment by arashadahamad** [comment]
Thanks @stewart-yu,  it would be good if you can share the plan

**Comment by stewart-yu** [comment]
I think more had disscued in [there](https://github.com/kubernetes/kubernetes/issues/45143) @arashadahamad

**Comment by dixudx** [comment]
/close

This has been fixed by #55824.

**Comment by arashadahamad** [comment]
@dixudx , I see this fix is available only in https://github.com/kubernetes/kubernetes/releases/tag/v1.9.0-beta.1

what about the 1.7 and 1.8 version

**Comment by dixudx** [comment]
@jsafrane @pospispa Any plan to cherry pick this feature to 1.7 and 1.8?

**Comment by pospispa** [comment]
I personally don't plan to cherry-pick this feature into K8s 1.8 or 1.7. I don't know if such cherry-picking could be justified.

**Comment by jsafrane** [comment]
I'd rather not backport features to older releases. Even though it's technically a bugfix, it brings a new admission plugin, new controller and new feature gate and that's IMO too much.
