### ISSUE TITLE
Kubernetes Flannel CNI does not re-create POSTROUTING MASQUERADE rules

### ISSUE THREAD

**Issue by danielmorlock** [kubernetes/kubernetes#56797]
/kind bug

**What happened**:
Starting k8s with flanneld CNI on an Ubuntu 16.04 server results in the following POSTROUTING rules:
    
     $ iptables -t nat -L POSTROUTING
    Chain POSTROUTING (policy ACCEPT)
    target     prot opt source               destination         
    KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
    MASQUERADE  all  --  172.17.0.0/16        anywhere            
    CNI-f4a2ba37b7c45a6f0a75e202  all  --  10.2.26.0/24         anywhere             /* name: "podnet" id: "2aa1bac9288bab51c08479e0998e9a6f7098842be68a9838fd2753fa73788411" */
    CNI-b80f40077ee30b3f1ed96374  all  --  10.2.26.0/24         anywhere             /* name: "podnet" id: "907ea36a07e665576b60f3f0d058f02df41ba0c1ed16732a10a93272e3cd5646" */
    CNI-46eb2ecbdd92da901b16fef9  all  --  10.2.26.0/24         anywhere             /* name: "podnet" id: "4fdaff97d2523014cd40cd9c7aaf574687a27ffc379434616544de6bd283fc46" */

Which is fine since outgoing traffic from 10.2.26.0/24 is properly masqueraded:

    Chain CNI-f4a2ba37b7c45a6f0a75e202 (1 references)
    target     prot opt source               destination         
    ACCEPT     all  --  anywhere             10.2.26.0/24         /* name: "podnet" id: "2aa1bac9288bab51c08479e0998e9a6f7098842be68a9838fd2753fa73788411" */
    MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "podnet" id: "2aa1bac9288bab51c08479e0998e9a6f7098842be68a9838fd2753fa73788411" */

After a flush, all iptables gets re-created but the CNI rules which results in PODs not having external access i.e. to the internet. 

**What you expected to happen**:

Since `kube-proxy` re-create all masquerading rules, we also expect that these POSTROUTING rules are also re-created after an iptables flush (i.e. from firewalld). 

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup k8s
2. Check iptables: `$ iptables -t nat -L POSTROUTING`
3. Flush iptables: `$ iptables -t nat -F`
4. Wait for `kube-proxy` to re-create iptables and check again.

After restarting `flanneld` the POSTROUTING rules are re-created again.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Bare metal, x86_64
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.2 LTS`
- Kernel (e.g. `uname -a`): `4.4.0-101-generic`

**Comment by cmluciano** [comment]
@kubernetes/sig-network-bugs

**Comment by caseydavenport** [comment]
This sounds like a flannel bug, rather than a bug in Kubernetes. Could you please raise against https://github.com/coreos/flannel instead?

/assign
/close
