### ISSUE TITLE
Please add Selector support to the LimitRange feature

### ISSUE THREAD

**Issue by Hardy2015** [kubernetes/kubernetes#56799]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We have a namespace containing 700 replication controllers. They belong to an app, that exists in two sizes, the one small with only two pods, the other more sophisticated with four pods. When we started with K8s we wrote an app to create RCs on request. All specifications are inside rc.yaml and service.yaml. Meanwhile we notice, that maintaining those >700 RCs would be much easier, if we had decoupled some attributes. We had a look at ConfigMaps (works for environment variables), PodPresets and LimitRanges (works for resource limits). LimitRanges would be perfect for everything that had been left open by ConfigMaps, IF we could specify DIFFERENT LimitRanges for the small and the more sophisticated RCs. Such differentiation could be done through selector support. Yet selectors are not supported in LimitRanges. Could you kindly add this feature? 

**What you expected to happen**:

Behavior like in PodPresets. S.th. like this: 
```
    spec:
      selector:
        matchLabels:
          instanceType: sophisticated
 ```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- n.a.

**Comment by Hardy2015** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by wackxu** [comment]
Agree with @Hardy2015 , I think this is a really good use experience for users when the LimitType is `pod`, Can anyone give some thoughts? If we agree do this, I can help done it.

**Comment by yue9944882** [comment]
+1

**Comment by wackxu** [comment]
In our company, we also need this feature, I think it is very useful.

We can implement this by serveral steps:
1. only when LimitType is `pod`, then we can set `selector`, we add validation when create `LimitRange`
2. when  `selector` is nil, then it match all the pods, It is backwards compatible
3. update `LimitRange admission controller` and test

@derekwaynecarr Any thoughts?

**Comment by wackxu** [comment]
@derekwaynecarr Any thoughts about this feature?

**Comment by krishnakc1** [comment]
Hello, can someone comment if this feature is already present? I looked at the documentation and do not seem to find it

**Comment by zhan9san** [comment]
Could we add selector based on pod labels?

We want to set different `limits` of pods based on pod labels?

**Comment by fabiand** [comment]
I'd expect an admin to setup the policy of what workloads are accounted towards which quota. 
However, pod labels are managed by workload owner - giving the owner the ablity to make the decision about accounting.

I wondered if something like Pod Adminssion Policies could be used for quota in order to have a more flexile approach on the server side to decide if or if not a pod should be accounted to a quota.
