### ISSUE TITLE
use Taints instead of node condition in the cloud node_controller

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#56796]
following the discussion with @wlan0, we should use taints instead of node conditions to mark node unusable to wait for routes to be initialized by cloud provider.
Obviously route_controller has to update the taints once it initializes the routes.

/sig node

**Comment by jhorwit2** [comment]
@wlan0 @yastij I think instead of moving to taints first we should follow this progression:

1. Remove the route specific logic from the node controller and only have it in the route controller. This first iteration will continue to use conditions as it does today. 
2. Move to taints. 

Thoughts?

**Comment by yastij** [comment]
I'm fine with this progression
