### ISSUE TITLE
kubeAPIServer Upgrade error with autoscaling/v2alpha1 

### ISSUE THREAD

**Issue by Deshke** [kubernetes/kubernetes#56800]
/kind bug
**What happened**:

kops upgrade 1.7.10 to 1.8.4
```
docker logs 4229f681c739
Flag --address has been deprecated, see --insecure-bind-address instead.
I1204 15:51:11.735696       7 server.go:114] Version: v1.8.4
I1204 15:51:11.736135       7 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
I1204 15:51:11.736196       7 aws.go:847] Building AWS cloudprovider
I1204 15:51:11.736235       7 aws.go:810] Zone not specified in configuration file; querying AWS metadata service
I1204 15:51:11.833294       7 tags.go:76] AWS cloud filtering on ClusterID: dev.k8s.domain.tld
I1204 15:51:11.836823       7 server.go:644] Initializing deserialization cache size based on 0MB limit
I1204 15:51:11.836839       7 server.go:663] Initializing cache sizes based on 0MB limit
I1204 15:51:11.836922       7 aws.go:847] Building AWS cloudprovider
I1204 15:51:11.836962       7 aws.go:810] Zone not specified in configuration file; querying AWS metadata service
I1204 15:51:12.205536       7 tags.go:76] AWS cloud filtering on ClusterID: dev.k8s.domain.tld
error in initializing storage factory: group version autoscaling/v2alpha1 that has not been registered
```

happens with `kops edit cluster $name`
```yaml
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2alpha1: "true" 
      batch/v2alpha1: "true"  
      cloudProvider: aws
```

**What you expected to happen**:
`kops update cluster $name` does validate the configuration of the cluster and if  non supported configurations appear at least a **WARNING** is shown 

**How to reproduce it (as minimally and precisely as possible)**:

try to upgrade a cluster from 1.7.x to 1.8.x with the runtimeConfig for Cronjobs and HPA for deployments

```yaml
  kubeAPIServer:
    runtimeConfig:
      autoscaling/v2alpha1: "true" 
      batch/v2alpha1: "true"  
      cloudProvider: aws
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
 ``` 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): 
- Install tools: 
```
kops version
Version 1.8.0 (git-5099bc5) 
```

- Others:

* https://kubernetes.slack.com/archives/C3QUFP0QM/p1512403695000567
* https://kubernetes.slack.com/archives/C3QUFP0QM/p1512404683000553

**Comment by chrislovecnm** [comment]
To be clear this is not a kops bug, bit it appears that alpha autoscaling api group was removed in 1.8. Version was bumped from alpha to beta, without having alpha remain in 1.8.

I assume that alpha should have remained?

**Comment by Deshke** [comment]
would make sense, to leave alpha enabled but give out a warning that v1alpha1 is deprecated in 1.8 and will be removed in 1.9?

**Comment by roycaihw** [comment]
Alpha API versions are supported for 0 releases before removing. See https://kubernetes.io/docs/reference/deprecation-policy/

/close
