### ISSUE TITLE
Updating statefulset from v1beta1 to v1beta2

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#56806]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

I have a stateful set that I created with api version v1beta1, I'm trying to update it to add a new annotation in the pod template using the v1beta2 api version in the update request but the update does not roll the pod. It seems that updating pods of stateful sets only works if it was initially created at version v1beta2, which I believe is a bug.

See
https://gist.github.com/ryanmcnamara/55c1327754b9fbc4518f2334f4e184b0
I did
```
kubectl apply -f v1beta1.yml
# wait for running pod
kubectl apply -f v1beta2.yml # has api version v1beta2
# observe no change in pod, probably expected
kubectl apply -f v1beta2_updated.yml # has a new annotation
# Existing pod is not rolled, unexpected
```
However (after deleting the statefulset)

```
kubectl apply -f v1beta2.yml
# Wait for running pod
kubectl apply -f v1beta2_updated.yml
# Pod is rolled as expected
```

- Kubernetes version (use `kubectl version`):
version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitCommit:"f18e43226af9f1c38a7cbeba0045baf435a125d7", GitTreeState:"clean", BuildDate:"2017-11-17T17:36:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitCommit:"f18e43226af9f1c38a7cbeba0045baf435a125d7", GitTreeState:"clean", BuildDate:"2017-11-17T17:34:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by danielqsj** [comment]
@ryanmcnamara 
Because the default `spec.updateStrategy` for the StatefulSet kinds is `OnDelete`.
If you want to roll update, you should change `spec.updateStrategy` to `RollingUpdate`.

**Comment by ryanmcnamara** [comment]
@danielqsj 
Hmm I'm getting some conflicting docs about this
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/apps/v1beta2/types.go#L126 
states that the default is RollingUpdate
While https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies states the default is OnDelete

At any rate it appears the default really is RollingUpdate, because my second test 
```
kubectl apply -f v1beta2.yml
# Wait for running pod
kubectl apply -f v1beta2_updated.yml
# Pod is rolled as expected
```
Actually does roll the pod.

It appears that 
```
kubectl apply -f v1beta2.yml
```
and
```
kubectl apply -f v1beta1.yml
kubectl apply -f v1beta2.yml
```
end up storing different objects in k8s, which doesn't make sense to me

**Comment by danielqsj** [comment]
@ryanmcnamara 
Sorry my previous comment is incomplete.
What I mean is the default `spec.updateStrategy` for the StatefulSet `v1beta1` kinds is `OnDelete`.
You could find it in [1.8 release note](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#defaults). 

> The default spec.updateStrategy for the StatefulSet and DaemonSet kinds is RollingUpdate for the apps/v1beta2 group version. You can explicitly set the OnDelete strategy, and no strategy auto-conversion is applied to replace default values.

**Comment by danielqsj** [comment]
@ryanmcnamara 
Code is here:
v1beta1: https://github.com/kubernetes/kubernetes/blob/bb72237375dfb32f2928e39354a42c40afc98fc1/pkg/apis/apps/v1beta1/defaults.go#L36
v1beta2:
https://github.com/kubernetes/kubernetes/blob/bb72237375dfb32f2928e39354a42c40afc98fc1/pkg/apis/apps/v1beta2/defaults.go#L57
