### ISSUE TITLE
Print what HTTP request we were handling when we print a stack trace

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#56816]
This would make debugging a little easier:  when we print a stack trace into the log, can we annotate it to show which (if any) HTTP request we were handling?

cc @lavalamp 
/sig api-machinery
/area apiserver
/area logging
/kind feature

(Also, we could use an area/debugging label.)

**Comment by hzxuzhonghu** [comment]
Already print http request.  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go#L38

**Comment by sttts** [comment]
@mml can you comment on @hzxuzhonghu's linked code? What is missing?

**Comment by MorrisLaw** [comment]
@mml @hzxuzhonghu @sttts is this issue still being determined whether or not it is already addressed in [the above linked file](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go#L38)?

**Comment by hzxuzhonghu** [comment]
Yes, and I think this issue can be closed.
