### ISSUE TITLE
CSI Mounter should create target path during SetUpAt call

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#56815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When a the internal k8s csi driver calls the external CSI driver for mounting (NodePublish) it is not creating the mount location.

**What you expected to happen**:
The internal CSI driver should create the target path to avoid bypassing security measures to allow external driver pod to do it.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to have an external CSI driver mount a path to a pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saad-ali** [comment]
Closed with https://github.com/kubernetes/kubernetes/pull/56836
