### ISSUE TITLE
hpa event still said can't find metrics from heapster even the system use metrics-server

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#56827]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**Description of problem:**
Now --horizontal-pod-autoscaler-use-rest-clients is default true, I have deploy metrics-server and no heapster, but in hpa envet it still said "no metrics returned from heapster".
Actually hpa already get metrics from metrics-server

**Version-Release number of selected component (if applicable):**
v1.10.0-alpha.0.697+2c9ffc0e887a86-dirty

**Steps to Reproduce:**
```
# kubectl get --raw /apis/metrics.k8s.io/v1beta1/namespaces/default/pods | python -m json.tool
{
    "apiVersion": "metrics.k8s.io/v1beta1",
    "items": [
        {
            "containers": [
                {
                    "name": "hello-openshift",
                    "usage": {
                        "cpu": "0",
                        "memory": "748Ki"
                    }
                }
            ],
            "metadata": {
                "creationTimestamp": "2017-12-04T08:42:08Z",
                "name": "hello-openshift-8k7bl",
                "namespace": "default",
                "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/hello-openshift-8k7bl"
            },
            "timestamp": "2017-12-04T08:42:00Z",
            "window": "1m0s"
        },
        {
            "containers": [
                {
                    "name": "hello-openshift",
                    "usage": {
                        "cpu": "0",
                        "memory": "736Ki"
                    }
                }
            ],
            "metadata": {
                "creationTimestamp": "2017-12-04T08:42:08Z",
                "name": "hello-openshift-q2q5n",
                "namespace": "default",
                "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/hello-openshift-q2q5n"
            },
            "timestamp": "2017-12-04T08:42:00Z",
            "window": "1m0s"
        }
    ],
    "kind": "PodMetricsList",
    "metadata": {
        "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods"
    }
}
# kubectl get hpa
NAME           REFERENCE                               TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
resource-hpa   ReplicationController/hello-openshift   0% / 80%   2         10        2          12m
# kubectl describe hpa/resource-hpa
Name:                                                  resource-hpa
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Mon, 04 Dec 2017 03:30:11 -0500
Reference:                                             ReplicationController/hello-openshift
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (0) / 80%
Min replicas:                                          2
Max replicas:                                          10
ReplicationController pods:                            2 current / 2 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound  the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             12m                horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       11m (x4 over 11m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from heapster
  Warning  FailedComputeMetricsReplicas  11m (x4 over 11m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster
```

**Expected results:**
In event shouldn't have heapster realted info

**Comment by mdshuai** [comment]
@DirectXMan12

**Comment by mattjmcnaughton** [comment]
Hi @mdshuai ,
Thanks for reporting this!

From looking at the code in `pkg/controller/podautoscaler/metrics/{legacy_metrics_client,rest_metrics_client}.go, it looks like both metrics clients can print the message `"no metrics returned from heapster"`. Specifically, with both the legacy client and the rest client, resource (i.e. non-custom metrics) are still generated by heapster. However, with the REST metrics client, heapster reports them to `kube-aggregator`, and the REST client reads them from there. More details in [this commit](https://github.com/kubernetes/kubernetes/commit/d6fe1e87642c9d325766ede9f6a0a7dd3c579ff2). I agree with you that the REST metrics client error message is confusing.

@DirectXMan12 can you confirm my understanding is correct? If yes, I tagged you in a pr that has error message wording that I think might be a little bit clearer. If not, just let me know and I can close the pr and we can work on another solution :)

----------

With respect to why you aren't finding any metrics - are you running heapster with the `--api-server=true` flag?

Hope this helps :)

**Comment by DirectXMan12** [comment]
@mattjmcnaughton yeah, I've been meaning to fix that error message for a while.  It's misleading as it is.  Thanks for submitting a PR to fix it.

Your understanding is mostly correct, but your wording is a bit off.  In the case of legacy metrics, they all come from Heapster using an old version of the resource metrics API, talking directly to Heapster.  In the case of the REST metrics client, Heapster is bypassed, and whatever is registered with the aggregator is used.  This is generally metrics-server, which does its own collecting.

Instead of using Heapster with the `--api-server=true` flag (which doesn't fully work any more), you should run metrics-server instead.

**Comment by mattjmcnaughton** [comment]
Thanks for the additional clarification @DirectXMan12 ! Very helpful :)
