### ISSUE TITLE
GCE cloud provider AlphaFeatureGate can't handle more then 1 feature

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#56833]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
If the `alpha-feature` field in `/etc/gce.conf` contains multiple entries, e.g. `alpha-features = NetworkTiers,DiskAlphaAPI,NetworkEndpointGroup`, none of them are enabled.

Log message:
```
$ cat /var/log/kube-controller-manager.log | grep -i "alpha feature "
E1205 04:26:39.285851       5 gce.go:263] Encountered error for creating alpha feature gate: alpha feature "Network
Tiers,DiskAlphaAPI,NetworkEndpointGroup" is not supported.
```

**What you expected to happen**:
Each of the comma-separated entries should be enabled.

**How to reproduce it (as minimally and precisely as possible)**:
Read above.

**Anything else we need to know?**:
Root cause appears to be the value of `configFile.Global.AlphaFeatures` is  not split before being used in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L275

CC @freehan @yujuhong  

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stewart-yu** [comment]
I think it's better to process `comma-separated entries` in read `/etc/gce.conf`

**Comment by hzxuzhonghu** [comment]
https://godoc.org/gopkg.in/gcfg.v1#example-ReadStringInto--Multivalue

**Comment by yujuhong** [comment]
I uploaded a PR (#56857) to parse the comma-separated values while still supporting the original gcfg muiltvalue mechanism (i.e., allowing setting the field multiple times) pointed out by the the above comments; this ensures backward compatibility (even though I don't know if anyone is using it that way).  I'll let the reviewers decide which method they prefer.
