### ISSUE TITLE
DenyEscalatingExec admission controller should check psp hostNetwork

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#56838]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

currently only `hostIPC ` `hostPID` are checked in `DenyEscalatingExec` admission controller

**What you expected to happen**:

hostNetwork should also be checked to deny exec /attach

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ericchiang** [comment]
cc @kubernetes/sig-auth-feature-requests
