### ISSUE TITLE
new feature: use 'kubectl exec' to attach pod which has already completed.

### ISSUE THREAD

**Issue by loadwiki** [kubernetes/kubernetes#56841]
Now we use k8s to run some distributed machine learning jobs written by python.
Some times the pod command or argument may be wrong format and the pod complete immediately.
For instance, put command 'python train_cifar10.py --batch_size=128' instead of the correct format 'python train_cifar10.py --batch-size=128'. In such situation, pod completed immediately either. There would be no chance to execute "kubec exec" to do some debug things in the container.Even the docker cli couldn't be able to restart the pod to reconstruct the container context.
The example bellow is so simple that we don't need to resume the container. However, there is complicated circumstance such as lack some script files or data files caused running failure. The developers couldn't get enough information from container's stderr.
So, could developers use 'kubectl exec' to attach pod which has already completed, especially in the dev environment? Maybe we can add a special flag when we create the pod,  ensure these pods will live after entrypoint process exits. Containers without the flag will exit as usual, after the  entrypoint process exits . 
It would be a great help for the engineer who developed apps on k8s cluster.

**Comment by loadwiki** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by caesarxuchao** [comment]
If sig node decides to support this feature and requires sig api-machinery's help, please then add the sig/api-machinery label back.

**Comment by s1113950** [comment]
Current workaround for this we use is monkeypatch the deployment command with a `sleep infinity & wait` but it would be great if this feature existed so no workarounds were necessary.
