### ISSUE TITLE
When api server /healthz fails, put info for diagnosis into its log.

### ISSUE THREAD

**Issue by aknrdureegaesr** [kubernetes/kubernetes#56856]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I had a problem in my cluster which caused the `/healthz` check of the API server to fail. This in turn caused the `kubelet` to keep restarting it.

I logged in to the master node running both and had a look at the log that catches the API server's `stdout` and `stderr`.

What I found there was (after unquoting)

```
[+]ping ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[+]poststarthook/extensions/third-party-resources ok
[-]poststarthook/ca-registration failed: reason withheld
[+]poststarthook/start-kube-apiserver-informers ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
healthz check failed
```

**What you expected to happen**:

I hoped to find diagnostic information in the log. (The `reason withheld` felt almost like a slap in the face.)

**How to reproduce it (as minimally and precisely as possible)**:

Whether this is reproducible, I don't know, but here is what we did: We messed up our cluster by running an application POD with a bad health check of its own. This was "deployed" for a long time.  On that (non-master) node, `docker ps --all` ended up showing a few thousand of shut-down Docker containers waiting to be cleaned up. Eventually, the problem infected the API server through a mechanism not understood.

But _any_ way to mess up the cluster sufficiently so the API server `/healthz` fails reliably should be sufficient. 

**Anything else we need to know?**:

I checked the source code and found, in `kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go`:

```
if check.Check(r) != nil {
    // don't include the error since this endpoint is public.  If someone wants more detail
    // they should have explicit permission to the detailed checks.
    fmt.Fprintf(&verboseOut, "[-]%v failed: reason withheld\n", check.Name())
    failed = true
} else {
```

I speculate "detailed checks" means another REST resource. So I checked the [API ref](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/). But there, I could not find anything pertinent.

From a user experience point of view: A failing `/healthz` check of the API server will (often) result in termination of that server. So the suggestion is to fire an HTTP request against a POD that's in the process of being shut down? To me, the log really does seem like a more appropriate place for such diagnostic information.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Running a `kops` cluster on AWS.
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-version
cat: /etc/os-version: No such file or directory
```
AMI `k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28 (ami-0072de6f)`
- Kernel (e.g. `uname -a`):
4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux
- Install tools:
Kops
- Others:

**Comment by aknrdureegaesr** [comment]
Judging from other items I've seen, this is probably the right label:

@kubernetes/sig-api-machinery-feature-requests

**Comment by hzxuzhonghu** [comment]
@aknrdureegaesr I think  `/healthz/poststarthook/bootstrap-controller` may give more details.  see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go#L78

**Comment by hzxuzhonghu** [comment]
This is intended, would wind closing this issue?
