### ISSUE TITLE
Openstack LBAAS: members not added automatically

### ISSUE THREAD

**Issue by akalambu** [kubernetes/kubernetes#56855]
When i use cloud provider Openstack and i use LoadBalancer to expose a service i see that the load balancer gets created but the nodes are not added as members to the load balancer pool

Expected result
LBAAS pool gets created but also members need to be added to the pool

**Comment by FengyunPan** [comment]
It seems a bug, but I never meet it. Can you show more logs?

**Comment by zetaab** [comment]
@akalambu can you provide more information, like what version of kubernetes and when creating service type: loadbalancer information about all resources. For instance kubectl get svc -o wide and neutron lbaad-loadbalancer-list and then list pool members and stuff like that. Also controller logs are needed

**Comment by dims** [comment]
/close

@akalambu please let me know if you want me to reopen this issue
