### ISSUE TITLE
Job backoff limit workings when parallelism > 1

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#56853]
This issue was born out of the discussion from https://github.com/kubernetes/kubernetes/issues/54904 and https://github.com/kubernetes/kubernetes/pull/56702. 

In short:
Job controller has an exponential backoff in place when failures happen to a job. As long as the parallelism is one, it's clear when a failure or success happens, the latter clears the backoff. The problem is when parallelism > 1, which can lead to situation where the controller can observe successful and failed pod at the same time and won't clear the backoff leading to further retries and longer wait times (see https://github.com/kubernetes/kubernetes/issues/54904 for extensive details about the problem in e2e)

Possible solutions:

1. leave everything as is
2. when both success and failure are observed clear the backoff

Pros and cons:

Ad. 1.
Aside from (https://github.com/kubernetes/kubernetes/issues/54904) I wonder if users got affected by it. Does it make sense to fix it at all?

Ad. 2.
This approach make sense in some situation, but the question arise, should that be controlled by a user. What if I have 9 failures and 1 success (parallelism = 10), should I still clear the backoff? Maybe we should introduce user controller field to set the failure rate in this case.

**Comment by soltysh** [comment]
/cc @foxish @kow3ns @clamoriniere1A
@kubernetes/sig-apps-feature-requests

**Comment by sdminonne** [comment]
@soltysh (jumping here 'cause @clamoriniere1A forwarded me this). I personally think that the right approach is to reset the back-off as soon we have a successful pod run to complete. 
Back-off was introduced, at least in our case,  to reduce the impact of _bad configured_  PodSpec in Jobs. If in your run you do have some successful run it means you've a good config and you just keep trying (not that differently what we did before `backoff`).
I don't think it's worth asking user finer tune config. `JobSpec` is already complex enough.
My 2 cents.

**Comment by mattfarina** [comment]
cc @kow3ns

**Comment by soltysh** [comment]
I agree with @sdminonne, any success should immediately clear the backoff flag, since it shows the job is configured properly and the problem is only temporary. I'll assign it to myself, but anyone is open to submit a PR fixing this.

**Comment by clamoriniere1A** [comment]
Hi @soltysh 
I started to implement the pod success check in order to clear the backoff delay in case of at least one of the pods succeed.
https://github.com/kubernetes/kubernetes/compare/master...clamoriniere1A:feature/JobBackoffWithParallelism
let me know if you are fine with this approach, and then I will go further with unit-tests and end2end tests.

**Comment by jberkus** [comment]
@soltysh @clamoriniere1A is the rest of the work on this issue getting done for 1.10?  Please update, and add approved-for-milestone if this is on track for 1.10.

**Comment by clamoriniere1A** [comment]
@jberkus @soltysh, I updated my change with missing unit-tests and created the PR:  https://github.com/kubernetes/kubernetes/pull/60202
