### ISSUE TITLE
Unable to use FakeScaleClient in tests

### ISSUE THREAD

**Issue by p0lyn0mial** [kubernetes/kubernetes#56865]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
While implementing `generic scaler` in `kubectl` I wanted to mock `scale client` in order to write some unit tests. My initial idea was to employ `FakeScaleClient`, so I extended existing code and registered desired types in the `Scheme`. Later on I realised that the `scale client` doesn't accept `version`. Every call made from within my test ended up with an error saying "no registered kinds for". Which makes sense since the `Scheme` holds very specific `gvks`

One way of resolving this issue would be to provide a `RESTMapper` that would resolve to proper `gvk` just before the actual look up in the `Scheme`. But it turned out that we don't have a fake `RESTMapper` or I couldn't find one. 

Another idea would be to derive `RESTMapper` from `fake discovery` but this doesn't seem to be viable approach.

As a workaround I created `scale client` from scratch in my unit test. Once this issue is resolved the test could be adapted to the new approach.

**Comment by DirectXMan12** [comment]
We do actually have an effective equivalent of a fake rest mapper, I've used it before.  I just have to dig up the right pattern.

**Comment by p0lyn0mial** [comment]
@DirectXMan12 any update on that :) ?

**Comment by DirectXMan12** [comment]
Having gone through, I'm unclear on what the issue is here.  This is an example that converts the current code to use the built-in scale client: https://github.com/p0lyn0mial/kubernetes/pull/2

**Comment by p0lyn0mial** [comment]
apparently, I didn't know how to use `fake` client. Thanks for showing how to do this, I'm closing the issue.
