### ISSUE TITLE
FlexVolume does not work on Windows node

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#56875]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I have tried FlexVolume on a Windows node, it does not work. I am now working on this feature now.
Below is the FlexVolume initialization error
```
E1205 09:27:58.705853     644 driver-call.go:225] Failed to unmarshal output for command: init, output: , error: unexpected end of JSON input
W1205 09:27:58.705853     644 driver-call.go:147] FlexVolume: driver call failed: executable: c:\volumeplugins/foo~cifs/cifs, args: [init], error: exec: "c:\\volumeplugins/foo~cifs/cifs": file does not exist, output: 
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/assign
@kubernetes/sig-windows-feature-requests

**Comment by andyzhangx** [comment]
Detailed steps about how to use flexvolume on Windows with this PR:
https://github.com/andyzhangx/Demo/tree/master/windows/flexvolume

**Comment by michmike** [comment]
cc: @bsteciuk
