### ISSUE TITLE
Request failing when I restart the pod

### ISSUE THREAD

**Issue by AnkitVaidya01** [kubernetes/kubernetes#56883]
When I am trying to restart the pod, the request going to that pod are failing. Ideally request should get transfer to other live pod. I have added prestop and postStart in my deployment yaml. Please suggest

{{- end}}
        - name: TZ
          value: "{{.Values.containerinfo.env.tz}}"
        image: "{{.Values.containerinfo.image}}:{{.Values.containerinfo.imageTag}}"
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "300"]
          postStart:
            exec:
              command: ["sleep", "20"]
        imagePullPolicy: "{{.Values.containerinfo.imagePullPolicy}}"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 18080
          initialDelaySeconds: {{.Values.containerinfo.livenessProbe.initialDelaySeconds}}
          timeoutSeconds: {{.Values.containerinfo.livenessProbe.timeoutSeconds}}
        name: "pod-category-service-container"
        resources:
          requests:
            memory: "{{.Values.containerinfo.resources.requests.memory}}"
          limits:
            memory: "{{.Values.c

**Comment by wanghaoran1988** [comment]
@AnkitVaidya01 I can't get you, could you please use the issue template to provide enough infomation if you really need a hand?

**Comment by AnkitVaidya01** [comment]
I deployed 3 pods. Putting load on it with approx 70 tps. During the test I have deleted one pod out of three then what should be the result? I am getting request failure in test. @k8s-bot @k8s-merge-robot

**Comment by foxylion** [comment]
@AnkitVaidya01 It is hard to give you any tip. Try to give more information on what you are trying to achieve.

- Link us the real deployment file (not a template)
- More details about the test (What tool? How do you access the deployment?)
- What version of Kubernetes do you use?
- Etc. (just look at the issue template: https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by AnkitVaidya01** [comment]
Please close the thread. My issue is resolved.

**Comment by feiskyer** [comment]
Closing based on https://github.com/kubernetes/kubernetes/issues/56883#issuecomment-351287625.
