### ISSUE TITLE
How to setup a hadoop cluster in a kubernetes cluster?How can I do that multiple pods in different nodes in a intranet?

### ISSUE THREAD

**Issue by dahaian** [kubernetes/kubernetes#56885]
I would like to setup a hadoop cluster in a kubernetes cluster.There are 4 nodes for kubernetes cluster.
I create a pod for hadoop master in a kubernetes cluster node.And I create three pods for hadoop slaves in the other 3 nodes.I have to do that all the pods in a intranet each other.I want to do that multiple pods in different nodes in a intranet. What should I do?Any help is appreciated!

**Comment by dims** [comment]
please look at solutions like:
https://github.com/kubernetes/charts/tree/master/stable/hadoop

/close

**Comment by dahaian** [comment]
@dims Thank you very much.And I want to know how to setup a hbase cluster?How to make the multiple pods in different nodes in a intranet?
