### ISSUE TITLE
`nettest` web server crashes in `PreStop` conformance test when default service account is disabled

### ISSUE THREAD

**Issue by jlhawn** [kubernetes/kubernetes#56897]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

I get a failure in the `PreStop` conformance test:

```
[Fail] [k8s.io] PreStop [It] should call prestop when killing a pod [Conformance]
```

**What you expected to happen**:

I expect it to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run this conformance test against a cluster which does not enable the default `ServiceAccount` admission controller plugin.

**Anything else we need to know?**:

The `nettest` web server relies on service account credentials to be able to *`contactOthers`*, i.e., discover peer endpoints within the same namespace. This is an operation that is completely unrelated to the thing that the `PreStop` test is checking for. The `nettest` web server should not need to access the api server for this test to pass. The `PreStop` test should either use a different web server container image or supply an option to disable this `contactOthers` feature of the `nettest` web server.

The kube-apiserver returns a `403 Forbidden` response when the `nettest` pod tried to check the server version: https://github.com/kubernetes/kubernetes/blob/master/test/images/nettest/nettest.go#L246 This crashes the web server, causing the `PreStop` test to ultimately timeout.

@kubernetes/sig-testing
@kubernetes/sig-testing-misc
@kubernetes/sig-testing-bugs
@kubernetes/sig-testing-test-failures

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8

**Comment by jlhawn** [comment]
Maybe @k8s-merge-robot doesn't read edited issue descriptions?

@kubernetes/sig-testing-bugs
@kubernetes/sig-testing-test-failures

**Comment by cjwagner** [comment]
Most bot commands do not detect commands that were added as a result of an edit. This is to avoid re-executing a command if a different part of the comment or issue is edited.

**Comment by spiffxp** [comment]
/remove-sig testing
/sig node
this is a test owned by sig-node

/sig architecture
this is a conformance test that's maybe making an unfair assumption
