### ISSUE TITLE
Specify openstack metadata endpoint to be HTTPS

### ISSUE THREAD

**Issue by bputt** [kubernetes/kubernetes#56892]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind feature

**What happened**: The openstack cloud-provider plugin doesn't allow you to update the metadata url to use HTTPS. The HTTP option is not available for me.

I'm not able to use the config drive, so the metadata url is my only option: https://github.com/kubernetes/kubernetes/issues/47392

You can see the url is statically set:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/metadata.go

```metadataUrlTemplate    = "http://169.254.169.254/openstack/%s/meta_data.json"```

**What you expected to happen**:

I'd like to be able to configure the ability to use HTTPS and specify a ca-cert

**Anything else we need to know?**:
Self signed certs

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: openstack
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): Linux 3.10
- Install tools:
- Others:

**Comment by dims** [comment]
@bputt i have a fix in progress for kubeadm+config_drive (and a tip about privileged containers) over at https://github.com/kubernetes/kubeadm/issues/588

I am not familiar with this pattern of a https:// based metadata url, is this a public cloud provider? can you name names? :)

Thanks,
Dims

**Comment by bputt** [comment]
@dims thanks for working on the other issue. I can't provide information about the provider, but I was able to modify the source code and add some https logic to get everything working. I may submit a PR in January.
