### ISSUE TITLE
Consider a structured KubeletConfigOk field in Node.Status

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#56896]
Currently, the Kubelet reports its configuration status in a NodeCondition with type KubeletConfigOK. This has limited use, because most of the node condition is not machine readable. A machine can tell if the config is OK, but can't easily aggregate details of the NodeConfigSource in use (especially if the node has rolled back to its last-known-good config).

We should consider adding a structured field to Node.Status instead, to facilitate machine consumption of the configuration status:
```
type NodeStatus struct {
    ...
    Config NodeConfigStatus
    ...
}

type NodeConfigStatus struct {
    Status ConditionStatus // one of True, False, or Unknown, machine-readable, as it is in a NodeCondition
    // Reports the config the Kubelet runtime chose to use
    ActiveSource *NodeConfigSource // now machine-readable, since it's a structured, versioned API type
    // ACK from the Kubelet that it has seen the currently set Node.Spec.ConfigSource
    AssignedSource *NodeConfigSource // now machine-readable, since it's a structured, versioned API type
    // Kubelet's chosen last-known-good source
    LastKnownGoodSource *NodeConfigSource // now machine-readable, since it's a structured, versioned API type
    // human-readable error string describing any problems with the configuration
    Error string 
    // human-readable string providing additional information about the configuration status
    Message string 
}
```

/cc @liggitt @mikedanese @dchen1107

**Comment by jiaxuanzhou** [comment]
consider adding a field of allocatable resource of cpu/mem/gpu in the status as well!

**Comment by jberkus** [comment]
@mtaufen  Hey, this issue looks like a feature.  If it's going to be in the 1.10 milestone, it needs kind/ and priority/ tags, and needs to be tracked in /features.

**Comment by mtaufen** [comment]
This would be part of https://github.com/kubernetes/features/issues/281 if we did it, but I don't think this specific item is in for 1.10.
