### ISSUE TITLE
Add support for dns name as a field in NetworkPolicyPeer and the application of that

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#56901]
/kind feature

Today NetworkPolicyPeer supports ipBlock, namespaceSelector, and podSelector.  This leaves one use case that is fairly common for dns name-based restrictions.  I think we should support that by having a way to express peers for both ingress and egress via dns domain name.

/sig network

**Comment by phsiao** [comment]
Some context in #22469.

**Comment by cmluciano** [comment]
We briefly discussed DNS selection in https://github.com/kubernetes/kubernetes/issues/50453. The reason why we did not move forward is because we would need an HTTP proxy.

**Comment by phsiao** [comment]
Had a chat with @cmluciano, there are a two potential issues with supporting DNS name.

1. DNS name and its resolution is "static", but the connection may not be.   For example, a http server can decide to redirect based on Host, and the layer 3/4 network policy controller logic would not be able to follow that.  As a result it becomes a usability problem.
2. Dynamic DNS entries.  Some DNS name can return different IP based on IP-sharding, geo-fencing, or just randomization, and it is a functional breakage if the pod and the network policy controller gets different results.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests

**Comment by redbaron** [comment]
DNS whitelisting does't require HTTP proxy if same agent can see both DNS requests and IP traffic.

 In kubernetes world that for instance can be a kube-proxy acting as DNS interceptor (or as an explicitly configured DNS server via kubelet), which then performs DNS resolution, observes response and open iptables rules before passing response to a POD.

iptables rules  should include every A  and AAAA record returned in the response and can be implemented using `ipset` with entry ttl being response TTL + 10 seconds (configurable). 

Implemented like that, it can support DNS whitelisting for arbitrary protocols, not only TCP.

**Comment by thockin** [comment]
I really don't think we want to impose DNS refreshing on implementations of NetworkPolicy without a bunch of REALLY REALLY good use cases that just CAN NOT be solved any other way.  Do we have such use cases?

**Comment by redbaron** [comment]
@thockin AFAIK PCI compliance requires DNS whitelisting solution to be on the path to the internet.
