### ISSUE TITLE
1.9 beta sync of pubished staging/ repos

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#56905]
I propose to do the next push of the staging repos.

As for the previous pushes:

- the push script: https://gist.github.com/sttts/6824e5f3822e0f0969c65ff4bba14772 (updated Dec 7 v2)
- the last heads for a potential rollback: https://gist.github.com/be24792c03554b797566b7cd6e363d0f (Dec 6)
- the test script: https://gist.github.com/53aa32d0d17370f92a5350f2bf52bfba (updated Dec 7)

The test script has successfully been run.

We restrict the push to master, 1.8 and 1.9 branches because #53583 blocks 1.7 right now (and probably similarly for 1.6, 1.5 if we want to keep them up-to-date at all).

**Comment by caesarxuchao** [comment]
In the push script for client-go:
```
git push git@github.com:kubernetes/client-go.git :refs/heads/release-1.9 ${tags}
```

Is it because we haven't created release-6.0 branch for client-go? Shall I go ahead and create the branch manually? It looks like I should the branch point is be88969207dfd2ca8a1678c59f4f8dc9ad691bc4?

**Comment by caesarxuchao** [comment]
Otherwise lgtm.

**Comment by sttts** [comment]
> In the push script for client-go:

Good spot. Was a typo in my sync script generator. Updating.

**Comment by caesarxuchao** [comment]
lgtm. Thanks!

**Comment by sttts** [comment]
Pushed everything but client-go's master branch (which is protected).

**Comment by sttts** [comment]
The master branch issue was resolved. Closing.
