### ISSUE TITLE
Remove alpha from Flex Volume docs

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/kubernetes#56920]
/kind bug

Flex volume docs still stay the feature is Alpha. We made it GA in Kube 1.8 time frame. We have to update the docs to reflect it.

/sig storage

**Comment by chakri-nelluri** [comment]
@saad-ali @matchstick Can we push this change for 1.9 or it is too late?

**Comment by saad-ali** [comment]
Code freeze is lifted Monday, Dec 11 so any changes to the core kubernetes repo (this one) required for 1.9 should be in by then. 

If this is purely a change to the kubernetes.io docs then we should move this issue to https://github.com/kubernetes/website/ (changes to the official kubernetes.io docs are made and tracked there.). If not, let's itemize all the required changes.

**Comment by shay-berman** [comment]
Hi Saad and Chakri

As Chakri mentioned, FlexVolume was already GA in 1.8 but was not reflected in relevant docs.
So since its only documentation thing, try to give this issue high priority if posible so it will be part of the 1.9 release.

Thanks
Shay Berman

**Comment by chakri-nelluri** [comment]
@saad-ali Verified that we need no changes from apiserver side to mark Flex GA. 
Opened: https://github.com/kubernetes/website/issues/6641

**Comment by chakri-nelluri** [comment]
@saad-ali Just realized the core api types have Flex as Alpha. We need a PR to fix it. If it is too late for 1.9, please feel free to target it for patch release.

**Comment by saad-ali** [comment]
Chakri could you clarify? Isn't `FlexVolumeSource` already part of v1 (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L308)?

**Comment by verult** [comment]
Are you referring to the documentation for FlexVolumeSource here? https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L306

**Comment by saad-ali** [comment]
Ah ok! I would support change this documentation (comment on FlexVolumeSource) for 1.9 to drop alpha wording. Please reach out to the release team to see if they will allow this change (since it is just a documentation change it is very low risk).

**Comment by saad-ali** [comment]
I will mark it for 1.9, the release team can choose to remove it if it is too late.

**Comment by shay-berman** [comment]
@chakri-nelluri and @saad-ali thanks for making it happened in k8s 1.9 time frame! Really appreciate your responsiveness.  

Consider to open a ticket to patch k8s 1.8 as well with FlexVolume as v1. As mentioned above it was already marked as v1 in 1.8 time frame.

Thanks
