### ISSUE TITLE
Statefulsets from 1.7 become unschedulable after an upgrade to 1.8

### ISSUE THREAD

**Issue by tommyvn** [kubernetes/kubernetes#56930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

After an upgrade from 1.7 to 1.8 the pods from my Elasticsearch statefulsets are scheduled to dead nodes and so stuck in a Pending state.

I've removed some fields from the copy-paste below for brevity.

`kubectl -n instrumentation describe pod elasticsearch-master-0` yields
```
Name:           elasticsearch-master-0
Status:         Pending
Created By:     StatefulSet/elasticsearch-master
Controlled By:  StatefulSet/elasticsearch-master
Conditions:
  Type           Status
  PodScheduled   False
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  2s (x6 over 17s)  default-scheduler  node 'ip-10-68-88-85.ap-southeast-2.compute.internal' not found
```

but `ip-10-68-88-85.ap-southeast-2.compute.internal` is long dead since the upgrade as `kubectl -n instrumentation get nodes` shows:
```
NAME                                              STATUS    ROLES     AGE       VERSION
ip-10-68-105-51.ap-southeast-2.compute.internal   Ready     node      20h       v1.8.4
ip-10-68-124-73.ap-southeast-2.compute.internal   Ready     master    20h       v1.8.4
ip-10-68-44-100.ap-southeast-2.compute.internal   Ready     node      20h       v1.8.4
ip-10-68-57-170.ap-southeast-2.compute.internal   Ready     master    20h       v1.8.4
ip-10-68-64-16.ap-southeast-2.compute.internal    Ready     master    20h       v1.8.4
ip-10-68-78-64.ap-southeast-2.compute.internal    Ready     node      20h       v1.8.4
```

**What you expected to happen**:

After an upgrade from 1.7 to 1.8 the pods from my Elasticsearch statefulsets are scheduled to ready nodes.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy statefulsets to a kubernetes 1.7 cluster created by kops 1.7.1.
1. Run a `kops upgrade` using kops 1.8.0 to upgrade to kubernetes 1.8.4, followed by the kops managed rolling restart.
1. See stateful sets in Pending state with the above mentioned error.

**Anything else we need to know?**:

I tried deleting pods, I tried deleting and recreating statefulsets, I set my statefulset apiVersion to `apps/v1beta2` as it was `apps/v1beta1` on kubernetes 1.7, all yield the same unscheduled state. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): kops derived debian 8
- Kernel (e.g. `uname -a`): 4.4.102-k8s
- Install tools: kops 1.8.0
- Others:

**Comment by tommyvn** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by tommyvn** [comment]
I had an idea to try create a new statefulset by changing the name before applying, thinking maybe it's a hangover from some pod/statefulset data hanging around somewhere it shouldn't, but even a newly named statefulset wants to schedule to the non-existent node. I guess that means is some node data hanging around rather.

**Comment by tommyvn** [comment]
On my Statefulset I have some pod affinity configured to keep instances on separate nodes and availability zones. If I remove my affinity configuration completely from my spec in my statefulset and apply that it now schedules out to ready nodes.

Somewhere the affinity data for old nodes still exists and the scheduler is trying to use that to schedule to a no longer existing node.

**Comment by resouer** [comment]
@tommyvn What's your cluster configuration may I ask? Any alpha feature enabled?

**Comment by tommyvn** [comment]
I've got `batch/v2alpha1` enabled for scheduled tasks, weave for cni and it's a private topology but aside from that it's a fairly standard kops setup.

I have made some more progress BTW, I wanted to turn the debugging up for kube-scheduler to see if it would tell me _why_ it was scheduling to a dead node, but after restarting kube-scheduler it started scheduling to ready nodes again. Is there perhaps some cached state in kube-scheduler that was cleared on a restart?

**Comment by yastij** [comment]
@tommyvn - we do have a cache for the scheduler, any logs available before kube-scheduler restart ?

**Comment by yastij** [comment]
@tommyvn - It might help us to get full logging before/after upgrade if you can reproduce it.

from what I know the cache gets updated when a node is deleted. When a node is deleted it emits an event, and based on that  we have event handler for deletes, adds, updates... that reacts on this event.

waiting for logs if it is reproducible, also putting @bsalamat on the loop

**Comment by bsalamat** [comment]
We have seen this issue in other clusters as well. As you guys guessed, it is caused by stale node information in scheduler cache. We have a pending PR to address this issue. Hopefully, it will be in the next 1.9 patch release:
https://github.com/kubernetes/kubernetes/pull/56622

**Comment by PhilippeDupont** [comment]
I faced the same issue upgrading from 1.7.10 to 1.7.11 using kops and affinity for a zookeeper statefuulset. Removing the affinity fixed it. Thanks @tommyvn
