### ISSUE TITLE
kubelet_node_status syncNodeStatus stopped running 

### ISSUE THREAD

**Issue by lzlicd** [kubernetes/kubernetes#56938]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After restart kubelet and docker service, kubelet stopped posting node status.

**What you expected to happen**:
Node become ready again and continue post node status every 10s.

**How to reproduce it (as minimally and precisely as possible)**:
Not 100% reproducible, one out of several times when restart kubelet and docker services.

**Anything else we need to know?**:
syncNodeStatus seems stopped running, cannot see "Using node IP:" logs every 10s, kubelet service is in active status though. Restart kubelet can fix this issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"

- Kernel (e.g. `uname -a`):
``` Linux test0shared0-samminionatlasdir1-1-prd.eng.sfdc.net 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux ```

**Comment by yujuhong** [comment]
Looks like #53207
