### ISSUE TITLE
Provide a mechanism in Kubelet device plugin manager to ensure per-container-creation Allocate gRPC call

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#56943]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
For certain types of devices, it is desirable to make sure an Allocate device plugin gRPC call is issued before starting a container. Currently, this is not guaranteed when containers are restarted. For more details, see discussions in issue https://github.com/kubernetes/kubernetes/issues/56022 and PR https://github.com/kubernetes/kubernetes/pull/56818

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cmluciano** [comment]
@kubernetes/sig-node-feature-requests

**Comment by RenaudWasTaken** [comment]
This is a blocker for beta at least for the NVIDIA device plugin.

**Comment by vikaschoudhary16** [comment]
I have started working on this.
