### ISSUE TITLE
A common Kubelet Plugin Communication Establish Model

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#56944]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
We are seeing the need for a common Kubelet plugin discovery model that can be used by different types of node-level plugins, such as device plugins, CSI, and CNI, to establish communication channels with Kubelet. During the design proposal reviews of device plugins and CSI, two models have been discussed: one is to have Kubelet export a registration service and plugins register themselves through this service; the other is for Kubelet to probe plugins under a canonical directory. We would like to get some consensus from the community on which model we should take in the future.

As a starting point of discussion, I wrote a draft doc comparing these two models: https://docs.google.com/document/d/1dtHpGY-gPe9sY7zzMGnm8Ywo09zJfNH-E1KEALFV39s
Please feel free to add comments either in the doc or in this issue.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tengqm** [comment]
@kubernetes/kubernetes-wg-resource-management

**Comment by tengqm** [comment]
@kubernetes/kubernetes-wg-resource-management

**Comment by tengqm** [comment]
@kubernetes/kubernetes-sig-node

**Comment by mtaufen** [comment]
If we go the directory route, I'd prefer a directory passed to the kubelet via a flag, rather than a magic location. 

Would the Kubelet have to periodically re-scan the directory to dynamically react to changes, or would it only have to scan it once per restart? 
Do plugins also have to be told where this directory is, so they can populate it, or does someone have to set up some config in this directory and also some config on a plugin?

If we did a registration service, would plugins have to re-register themselves on every Kubelet restart, or would the registrations be cached to disk?

**Comment by lichuqiang** [comment]
> Would the Kubelet have to periodically re-scan the directory to dynamically react to changes, or would it only have to scan it once per restart?

I guess to feel the change of plugins, kubelet need things like a "fileWatcher" to watch the change in the directory.

And @jiayingz have descriptions of your comments in the referenced doc .

**Comment by lichuqiang** [comment]
>We can introduce special plugin pod for which we automatically setup its environment to communicate with kubelet. Even if Kubelet runs in a container, it is easy to config the communication path between plugin and Kubelet.

@jiayingz Wondering how the special plugin pod here looks like, do we need to introduce something built-in ?

**Comment by jiayingz** [comment]
@mtaufen for the directory probing model, I thinking setting it as a flag on both kubelet and plugin sides is feasible with Kubelet dynamic config support that plugins can get this flag setting from Kubelet config configMap. I have limited knowledge on that side and probably need to ping you for help if we want to go that path.

I think Kubelet may need to create a go routine to watch for inotify events and then scan the directory once per restart. The two processes need to be coordinated through a lock and are resilient to duplicate plugin creations.

In the registration model, I think either way works. In the current implementation, plugins need to re-register on every Kubelet restart, but we can eliminate this requirement by having Kubelet record the registered plugin sockets in its checkpoint.

**Comment by jiayingz** [comment]
@lichuqiang for special plugin pod, we may possibly introduce something built-in, but I think that may be a bit overkill at the moment. Right now, I think a regular pod spec seems sufficient to be used in both models.

**Comment by mtaufen** [comment]
Another benefit of the service model: hard for plugins to accidentally unregister each-other (vs directory, where they could delete each-other's registrations by accident).

**Comment by jiayingz** [comment]
@mtaufen that is a valid concern. I think this is related to the security model we would like to take. If we are taking the directory discovering approach, we probably need to require plugins to run in privileged mode, which kind-of implies that we trust them at the first-citizen level.

**Comment by jiayingz** [comment]
cc @chakri-nelluri

**Comment by jiayingz** [comment]
From offline discussions with a few folks, the general feedback is that although both approaches can be made to work, consistency and simplicity are also important.
This puts in favor of the kubelet probing model. I think we can make the call to use that model in the general kubelet plugin pkg and start implementing that now.

@chakri-nelluri please feel free to assign this issue to yourself if you have time to implement it in 1.10. I think @vikaschoudhary16 and I can help review the PR from device plugin perspective once it is available. We will switch device plugin to use this pkg after it is merged, which hopefully can also happen in 1.10.

**Comment by vikaschoudhary16** [comment]
yeah, lets target to get it merged in 1.10. @chakri-nelluri please let me know in case you need any help.

**Comment by chakri-nelluri** [comment]
@vikaschoudhary16 @jiayingz Assigned it to myself and will target it for 1.10.

**Comment by saad-ali** [comment]
+1 for probing approach
