### ISSUE TITLE
provide an interface for ipam in node controller

### ISSUE THREAD

**Issue by martinyunify** [kubernetes/kubernetes#56949]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind feature

**What happened**:
ipallocator in nodecontroller only support gce cloudprovider
 
**What you expected to happen**:
should remove this constaint and let cloud provider to decide whether they would implement this feature

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
no 
https://github.com/kubernetes/kubernetes/blob/a505d1bc7854c0581fc8dcbc007ee0063d0fdfb3/pkg/controller/node/ipam/cloud_cidr_allocator.go#L87

**Comment by thockin** [comment]
@cheftako
