### ISSUE TITLE
when i set kube-apiserver.yaml  "- --service-node-port-range=10-65535" it will show the eror log ,but it set "- --service-node-port-range=1000-65535",it will be ok !!  why? /kind bug

### ISSUE THREAD

**Issue by jishandong** [kubernetes/kubernetes#56950]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@jishandong could you please update the description and title of the issue to include more information like your version, the logs, and your CLI args to the apiserver.  Thanks!

**Comment by dims** [comment]
haven't heard from you @jishandong, please open a fresh bug with details mentioned above

/close

**Comment by jishandong** [comment]
The  configure file   "/etc/kubernetes/manifests/kube-apiserver.yaml" , it has the  parameter "- --service-node-port-range="" ".When I set up it range from 1000 to 65536, it's no problem to execute this command "kubectl get nodes". But when I set up for 80-65535, or when the numbers start to be smaller, execute the similar command "kubectl get nodes" as follows: "The connection to the server 10.29.37.121:6443 was refused - did you specify the right host or port?" 。I has check the error ，the container fo kube-apiserver 's status is exited.Have you ever met a similar problem？ and solve it？ my k8s version is 1.8.1 。
