### ISSUE TITLE
Kill pods with unmatched node label

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#5695]
(due to node label update, etc)

**Comment by bprashanth** [comment]
The node controller is already aware of edge transitions ( https://github.com/GoogleCloudPlatform/kubernetes/blob/b2ed6b325550fd5f73ddb1bcf6c259c8e91e964e/pkg/cloudprovider/controller/nodecontroller.go#L347), currently the only transition its capable of detecting is an unhealthy node. One conceivable solution would be to teach it to react to other edge transitions triggered off a watch, like an update to node labels.

**Comment by bgrant0607** [comment]
There will also be enforcement in Kubelet, at least at pod admission time #5715.

**Comment by bprashanth** [comment]
At admission time the scheduler should check through a fit predicate anyway rigth? There is a race of course.
