### ISSUE TITLE
HttpGet handler in container lifecycle has no check on statusCode of the response

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#56963]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When performing a container lifecycle action in `HTTPGet` form, we only check the error  and the content of the response, but does not check its statusCode [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L128). Is there any special consideration about the point?

/sig node

**Comment by liggitt** [comment]
it looks like the container lifecycle http requests are somewhat underspecified. only a hard fail in the get will result in an error. also, some of the fields (scheme and headers) in the http get action aren't honored by lifecycle
