### ISSUE TITLE
Adding externel configuration file 

### ISSUE THREAD

**Issue by bainim** [kubernetes/kubernetes#56968]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Hello every one ,
i'm working on kubernetes and elasticsearch 
i followed this link :https://github.com/kubernetes/examples/tree/master/staging/elasticsearch
what i want is to add a volume to be like this on :
`folder_path/config:/usr/share/elasticsearch/config`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu-server 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@bainim please open a bug here https://github.com/kubernetes/examples/issues

/close
