### ISSUE TITLE
Controller-manager unable to update service endpoints

### ISSUE THREAD

**Issue by andor44** [kubernetes/kubernetes#56972]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We have some services whose endpoints are not getting updated when the set of backing pods change. We see in the controller-manager logs repeated attempts to update the endpoints, and they all fail with the message
```
I1208 17:36:04.198106       1 endpoints_controller.go:375] Error syncing endpoints for service "XXX-namespace/XXX-servicename": Operation cannot be fulfilled on endpoints "XXX-endpointsname": the object has been modified; please apply your changes to the latest version and try again
```
and it eventually gives up:
```
W1208 17:37:26.161953       1 endpoints_controller.go:380] Dropping service "XXX-namespace/XXX-service" out of the queue: Operation cannot be fulfilled on endpoints "XXX-service": the object has been modified; please apply your changes to the latest version and try again
```

It seems to happen only to some services, but it happens to those consistently, every time. Deleting and recreating the service "resolves" the problem.

We tried watching the key in etcd with `etcdctl -o json watch /registry/services/endpoints/XXX-namespace/XXX-service -f` and *nothing* is modifying it, i.e. we see no reason why the resource should be out of date.

We see in the API server logs that it is returning HTTP 409 to the controller manager.

**What you expected to happen**:
The endpoints get correctly updated.

**How to reproduce it (as minimally and precisely as possible)**:
Don't know.

**Anything else we need to know?**:
We're running this cluster on etcd 2 still, which we suspect might be related. We have another cluster that is very similar to this one that is running against etcd 3 which does not exhibit this behavior. As far as I can tell etcd 2 is still officially supported, therefore I'd expect to not have issues of this kind.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: On-prem, bare metal _and_ VMs
- OS (e.g. from /etc/os-release): CoreOS stable
- Kernel (e.g. `uname -a`): `4.13.9-coreos`
- Install tools: Custom Ansible playbooks
- Others: etcd 2.3.7

**Comment by andor44** [comment]
Don't really know what SIG applies here: API machinery, cluster ops, something else?

**Comment by dims** [comment]
let's start with api machinery

/sig api-machinery

**Comment by jpbetz** [comment]
I would strongly recommend upgrading to etcd3. Use of etcd2 with kubernetes 1.8+ is not well supported. There is no automated e2e testing for etcd2 in 1.8+ and the etcd client code vendored in to kubernetes for etcd2 is unsupported. I'm not sure what official documentation about etcd2 support, but the _de-facto_ support is very limited. We need to establish a formal etcd version deprecation policy, document it, and help the community migrate to etcd3. I'll own that.

**Comment by andor44** [comment]
I wonder if #53795 could be related? We do not set anything for this flag explicitly. Does this default to true or false?

**Comment by rafarost** [comment]
Hello... We have a similar environment here and I believe we are facing exactly the same issue... We did the same workaround (delete + create services) and apparently it was "fixed".  Do you guys have any news on it? Thanks

**Comment by ruanchen** [comment]
I face the same problem, when i use glusterfs as a storage,the log like this:

[root@k8s-test-bk-1 ~]# kubectl get svc | grep fastdfs-group0
glusterfs-dynamic-storage-data-fastdfs-group0-storage0-0   ClusterIP   10.254.207.133   <none>        1/TCP                           2h
glusterfs-dynamic-storage-data-fastdfs-group0-storage0-1   ClusterIP   10.254.234.38    <none>        1/TCP                           2h

[root@k8s-test-bk-1 ~]# kubectl get ep | grep fastdfs-group0   
glusterfs-dynamic-storage-data-fastdfs-group0-storage0-1   172.20.0.12:1,172.20.0.34:1,172.20.0.35:1           2h
