### ISSUE TITLE
Use a more recent version of go-yaml

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#56976]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The version of go-yaml (53feefa2559fb8dfa8d81baad31be332c97d6c77) vendored by kubernetes has this bug: https://github.com/go-yaml/yaml/issues/75

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
If KUBECONFIG uses the exclamation mark syntax, for example:
```
expiry-key: ! '{.credential.token_expiry}'
```
kubectl will fail to parse it.

**Anything else we need to know?**:
It was fixed in go-yaml here: https://github.com/go-yaml/yaml/commit/670d4cfef0544295bc27a114dbac37980d83185a

I'll be happy to contribute a fix, but I'd like to know if it will be accepted.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by caesarxuchao** [comment]
Could you investigate what other changes are added to go-yaml if we take the update?

**Comment by caesarxuchao** [comment]
cc @jennybuckley

**Comment by jennybuckley** [comment]
Almost all the changes to go-yaml between the version we are using and the bug fix are to comments or variable names.
The licence changed from LGPLv3 to http://www.apache.org/licenses/LICENSE-2.0 which should be fine.
Also 3 bug fixes, so hopefully we aren't relying on any of these bugs.
https://github.com/go-yaml/yaml/commit/a5b47d31c556af34a302ce5d659e6fea44d90de0
https://github.com/go-yaml/yaml/commit/406cad6bb47dd7d9a123d005fb8ff766f6463051
https://github.com/go-yaml/yaml/pull/171/files
