### ISSUE TITLE
one admission controller can be passed multiple times to --admission-control

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#56998]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

For example, if a user start kube-apiserver with `--admission-control=ResourceQuota,foo,ResourceQuota` , quota will be calculated twice when one object is created.

/assign

I will fix this.
This issue is addressed for some suggestions.

**Comment by CaoShuFeng** [comment]
/cc @deads2k 
What's your opinion about this?

**Comment by hzxuzhonghu** [comment]
I think this issue can be closed. Since admission refactor has been done.

**Comment by deads2k** [comment]
> I think this issue can be closed. Since admission refactor has been done.

Yes, this is done.
