### ISSUE TITLE
YAMLDecoder Read function always returns n=0 bytes

### ISSUE THREAD

**Issue by sel** [kubernetes/kubernetes#56999]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:  

In a go program, using the YAML utility package "k8s.io/apimachinery/pkg/util/yaml", the
YAMLDecoder Read function always returns n=0 bytes, indicating that nothing was read.

**What you expected to happen**:

The number of bytes read should be returned as specified in the [Read contract](https://golang.org/pkg/io/#Reader)

**How to reproduce it (as minimally and precisely as possible)**:

```
func TestYAMLDecoder(t *testing.T) {
	d := `---
stuff: 1
	test-foo: 1
`
	s := NewDocumentDecoder(ioutil.NopCloser(bytes.NewReader([]byte(d))))
	b := make([]byte, len(d))
	n, err := s.Read(b)
	if err != nil || n != len(d) {
		t.Fatalf("unexpected body: %d / %v", n, err)
	}
}
```
See https://github.com/sel/kubernetes/commit/86d02ac36811dfadad089f9a5d2ceb95b1288056#diff-3b3ea800b8ebe625d0defd76c2e6f827

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}`
- Cloud provider or hardware configuration: minikube & AWS
- OS (e.g. from /etc/os-release): macOS 10.13.1 (17B1003)
- Kernel (e.g. `uname -a`): Darwin 17.2.0
- Install tools:
- Others: `go version go1.9.2 darwin/amd64`

**Comment by sel** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by jennybuckley** [comment]
@jennybuckley
