### ISSUE TITLE
scheduler computes general predicates twice 

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#57003]
While implementing, predicate ordering, I found out that we were registering the following predicates here: 

https://github.com/kubernetes/kubernetes/blob/bb72237375dfb32f2928e39354a42c40afc98fc1/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L65-L82 

But we are also registering them using the following:
https://github.com/kubernetes/kubernetes/blob/bb72237375dfb32f2928e39354a42c40afc98fc1/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L162

As the underlying data structure that holds predicates is a map and since the keys are different, the scheduler will compute these twice for every decision.

/sig scheduling
/kind enhancement
/assign

**Comment by yastij** [comment]
cc @resouer @gmarek @bsalamat

**Comment by resouer** [comment]
@yastij Let me explain this a little bit :)

The default scheduler only knows the group of predicates registered in this function:
https://github.com/kubernetes/kubernetes/blob/bb72237375dfb32f2928e39354a42c40afc98fc1/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L119

So it will only use `GeneralPredicates` which is registered there.

**Comment by yastij** [comment]
@resouer - what about the other ones, from what i see `#registerFitPredicate()` will also to the same map ? How are they ignored ?

**Comment by yastij** [comment]
Indeed you're right, closing this as it works as expected (we might benefit from a refactoring here, i'll explore it later)
