### ISSUE TITLE
Cannot fetch certificate data using jsonpath

### ISSUE THREAD

**Issue by sheerun** [kubernetes/kubernetes#57001]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`kubectl config view -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'`
[68 64 192 9 49 3]

**What you expected to happen**:

kubectl displays config in base64 or pem format. Instead it returns bunch of numbers

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
azure
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):
Linux k8s-master-41BA549E-0 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

/sig cli

**Comment by charrywanganthony** [comment]
maybe it will be too long to display in base64?

**Comment by sheerun** [comment]
It displays literally 4 number. Not sure what is going on but certainly not what I expected
