### ISSUE TITLE
Mismatch between crio.sock location in crio and kubelet

### ISSUE THREAD

**Issue by norbertvannobelen** [kubernetes/kubernetes#57005]
BUG REPORT

While configuring the kubelet with:
`--container-runtime-endpoint="unix:///var/run/crio.sock"`
And having the sock file on that location (default location from cri), the following error occurs:

`Dec 10 18:30:52 kubeworker01 kubelet[15060]: W1210 18:30:52.739721   15060 manager.go:291] Registration of the crio container factory failed: Get http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info: dial unix /var/run/crio/crio.sock: connect: no such file or directory`

Later line:
`Dec 10 18:30:50 kubeworker01 kubelet[15060]: I1210 18:30:50.712558   15060 remote_runtime.go:43] Connecting to runtime service unix:///var/run/crio.sock`

Uses the correct socket.

Result:
Disruptive in understanding other failures.
Containers still start.

**Environment**:
- Kubernetes version: 1.8.0-5, 1.9.0-beta.2
- Cloud provider: gce
- OS: Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux kubeworker01 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: The hard way
- Others:
Full kubelet config (as of now):
```
/usr/local/bin/kubelet 
--allow-privileged=true 
--cluster-dns=10.32.0.10 
--cluster-domain=cluster.local 
--container-runtime=remote 
--container-runtime-endpoint=unix:///var/run/crio.sock 
--image-pull-progress-deadline=2m 
--image-service-endpoint=unix:///var/run/crio.sock 
--kubeconfig=/var/lib/kubelet/kubeconfig 
--cni-conf-dir=/etc/cni/net.d 
--cni-bin-dir=/opt/cni/bin 
--network-plugin=kubenet 
--register-node=true 
--runtime-request-timeout=10m 
--tls-cert-file=/var/lib/kubelet/kubeworker01.pem 
--tls-private-key-file=/var/lib/kubelet/kubeworker01-key.pem 
--v=2
```

Internal log reference: syslog.v6.3

**Comment by dixudx** [comment]
This is because `cadvisor` uses `/var/run/crio/crio.sock`, while `kubelet` is using `/var/run/crio.sock` as default.

We should make them consistent. Fixed in #57023. PTAL.

**Comment by sttts** [comment]
What are the consequences? Is it more than cosmetical? Does it the usage of CRI-O in 1.9.0 or how does it affekt users?

**Comment by sttts** [comment]
/assign @sjenning 

Is this relevant for CRI-O in 1.9.0?

**Comment by norbertvannobelen** [comment]
It (at this moment) mostly looks cosmetical, however when I add a cloud provider (--cloud-provider=gce in this case) to the kubelet config, the whole thing breaks consistently on PLEG. I am trying to figure out if there is a relation between that and the crio.sock.

**Comment by enisoc** [comment]
@dchen1107 @derekwaynecarr Can you weigh in on whether this is a release-blocker for 1.9.0?

**Comment by enisoc** [comment]
Tentatively adding milestone so we can track getting a judgement from sig-node.

**Comment by runcom** [comment]
fixed in packaging yeah, from 1.8 we moved to "/var/run/crio/crio.sock" so you need to start kubelet with that socket path

**Comment by dchen1107** [comment]
Discussed at sig-node earlier today, and this is not a release blocker. Also like @derekwaynecarr mentioned above, the issue was fixed in the packaging.

**Comment by ganga1980** [comment]
Hi, @derekwaynecarr 

I am hitting the same error in this thread on my Openshift4.2 cluster which has configured CRIO on the kubelet. I would like to hit /var/run/crio/crio.sock to get inventory of the containers.  Any body has any insights why I am hitting this error?

[root@myocp42-pdqlw-worker-eastus3-lgsrx /]# curl -v --unix-socket /var/run/crio/crio.sock http://localhost/info
*   Trying /var/run/crio/crio.sock...
* Immediate connect fail for /var/run/crio/crio.sock: No such file or directory
* Closing connection 0
curl: (7) Couldn't connect to server
[root@myocp42-pdqlw-worker-eastus3-lgsrx /]#

sshadmin@gangams-ci-1:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+8bbaf43", GitCommit:"8bbaf43", GitTreeState:"clean", BuildDate:"2020-01-17T17:43:42Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"
