### ISSUE TITLE
ImageGCFailed attempting to remove images in use by running containers

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#57006]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:

The kubelet is attempting to GC images that are in use by running containers that the kubelet manages (we have no running containers on a host outside of k8s control). 

```
  Warning  ImageGCFailed            20m (x508 over 1d)  kubelet, host  (combined from similar events): wanted to free 25419897241 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container aec6e63fe827"}
  Warning  ImageGCFailed            11m                 kubelet, host  wanted to free 24121289113 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 2c6622239d05"}
  Warning  ImageGCFailed            6m                  kubelet, host  wanted to free 23035570585 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container b65a78dd8f12"}
  Warning  ImageGCFailed            1m                  kubelet, host  wanted to free 22244608409 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = 2 desc = Error response from daemon: {"message":"conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 50f53d79ea51"}
```

**What you expected to happen**:

I expect the kubelet to not attempt to remove images being used by running containers or at least not spam events for this. 

**How to reproduce it (as minimally and precisely as possible)**:

I _think_ the way to reproduce this is to have your kubelet reach eviction thresholds because that's how i noticed it. 

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): The kubelet is v1.7.6

**Comment by jhorwit2** [comment]
It seems the image it's trying to delete is the pause container in use by pods running in the host network.

**Comment by huangjiasingle** [comment]
@jhorwit2  it's also hapened in my k8s cluster of v1.7.6
