### ISSUE TITLE
gce-1.9-1.8-downgrade fails due to etcd crashloopbacking

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#57013]
/kind bug
/priority failing-test
/sig cluster-lifecycle testing

This test fails:
https://k8s-testgrid.appspot.com/sig-release-1.9-all#gce-1.9-1.8-downgrade

Some clues:

- waiting for new master timeout:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/build-log.txt
```
== Waiting for new master to respond to API requests ==
W1204 16:55:41.879] 2017/12/04 16:54:57 util.go:196: Interrupt after 15h0m0s timeout during kubetest --test --test_args=--ginkgo.focus=\[Feature:ClusterDowngrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=upgrade --v=true --check-version-skew=false. Will terminate in another 15m
```

- master healthz check failed:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/artifacts/bootstrap-e2e-master/kube-apiserver.log
```
logging error output: "[+]ping ok
[-]etcd failed: reason withheld
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
[-]poststarthook/ca-registration failed: reason withheld
[+]poststarthook/start-kube-apiserver-informers ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[-]autoregister-completion failed: reason withheld
healthz check failed
"
 [[curl/7.38.0] 35.184.43.102:54282]
```

- etcd is crashloopbacking:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/artifacts/bootstrap-e2e-master/etcd.log
```
2017-12-04 02:24:01.495921 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-12-04 02:24:01.506968 I | membership: added member a97d80ddc090126a [https://bootstrap-e2e-master:2380] to cluster 91078bdbe2ed539b
2017-12-04 02:24:01.507103 N | membership: set the initial cluster version to 3.1
2017-12-04 02:24:01.507116 C | membership: cluster cannot be downgraded (current version: 3.0.17 is lower than determined cluster version: 3.1).
```

I guess the cause may be something associated with etcd version compatibility. @xiang90 @hongchaodeng any thoughts or suggestions? Thanks!

This is also posted in https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/c4MW3R5v4v0

/cc @enisoc @luxas @krzyzacy  @kubernetes/sig-cluster-lifecycle-test-failures @kubernetes/sig-release-test-failures

**Comment by xiangpengzhao** [comment]
xref: #54027
/cc @jingax10

**Comment by luxas** [comment]
cc @wojtek-t

**Comment by luxas** [comment]
cc @jpbetz @xiang90 @hongchaodeng @timothysc 

From my understanding, this is expected as etcd can't handle downgrades.
I think this has been worked around though in previous releases by avoiding to downgrade etcd on k8s downgrade. That's what we're gonna do in kubeadm at least

**Comment by jpbetz** [comment]
Yes, per the etcd [upgrade docs](https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_1.html#downgrade), "[automatic] downgrade from this completed state is not possible... Please backup the data directory of all etcd members to make downgrading the cluster possible even after it has been completely upgraded."

**Comment by xiangpengzhao** [comment]
@jpbetz thanks! Is there any way to configure the downgrade test not to downgrade etcd?
However, this might cause another problem: if we don't downgrade etcd from 3.1.10 to 3.0.17 when downgrading cluster from 1.9 to 1.8, can the 1.8 cluster work well against 3.1.10 etcd since the officially supported etcd version of 1.8 is 3.0.17?

**Comment by wojtek-t** [comment]
@xiangpengzhao great question. We would probably need to setup tests to actually test it, but I really believe that it should work fine (k8s 1.8 has already etcd client in 3.1.10 version).
And also, we don't really have big choice here - that's the only thing we can do/recommend doing.

**Comment by xiangpengzhao** [comment]
@wojtek-t reasonable. Totally agreed :)

So now the concern here is that how we should configure the downgrade test not to downgrade etcd to avoid the job failing. @kubernetes/sig-testing-misc any ideas on the config of this job?

**Comment by krzyzacy** [comment]
cc @kubernetes/sig-storage-misc

**Comment by wojtek-t** [comment]
I'm pretty sure we used to do that in the past (when we were doing etcd 2.2.1 -> etcd 3.0.17 upgrade in 1.5 -> 1.6 release (though those might have been manual tests). 

Assuming that the tests are setup on GCE, it should be enough to set some env variables for the downgrade to pin the downgrade to a particular release:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L156
ETCD_IMAGE and ETCD_VERSION seem to be those ones.

**Comment by xiangpengzhao** [comment]
@wojtek-t thanks for the info! I will send a PR (touching some e2e/cluster-lifecycle) trying to specify the etcd version 3.1.10 when the cluster downgrade target version is 1.8 but I'm not sure if it's a good solution for this issue.

**Comment by krousey** [comment]
FYI I'm proposing https://github.com/kubernetes/test-infra/pull/5909 to unblock the tests from running. A better long-term fix is needed.

**Comment by xiangpengzhao** [comment]
@krousey I send another workaround https://github.com/kubernetes/kubernetes/pull/57108. I guess it won't conflict with your PR. It may be a starting of a long-term fix.

**Comment by enisoc** [comment]
We need a good release note to warn users that they need to prevent an etcd downgrade if they downgrade k8s.

We filled in the warning from 1.6 as a placeholder, but it needs to be updated for this specific issue:

https://docs.google.com/document/d/1veHHyDH9VoNTwP6yy9u2Q7Jj1hnBJGVPv3NPHInImgU/edit#heading=h.n8bxz8ayqnw9

We also should add a warning to the upgrade script, similar to this one from 1.6:

https://github.com/kubernetes/kubernetes/blob/d052476c303c5d567ea5b222eef46faabfd078cb/cluster/gce/upgrade.sh#L514-L538

cc @jpbetz @hongchaodeng who were involved with the update to 3.1.10 (https://github.com/kubernetes/kubernetes/pull/49393)

Can anyone advise on the above?

**Comment by jpbetz** [comment]
@enisoc Looks like we need something along the lines of:

```
The default etcd version in 1.9 has changed from 3.0 to 3.1.

ETCD DOES NOT SUPPORT DOWNGRADES: If you wish to downgrade to to etcd 3.0 after this upgrade, you must backup your etcd state before upgrading.

It's HIGHLY recommended that etcd be backed up before this step!!

Documentation about etcd 3.1 upgrades can be found at https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_1.html.

It's HIGHLY recommended that etcd be backed up before this step!!

Would you like to continue with an upgrade to etcd 3.1, and lose the ability to downgrade to etcd 3.0? [y/N] 
```

**Comment by jpbetz** [comment]
@enisoc The idea you mentioned of checking for `ETCD_IMAGE` and `ETCD_VERSION` env vars is a really good one. `ETCD_IMAGE` is the docker tag of the gcr.io/google-containers/etcd for image to run etcd from. Each image contains multiple etcd binaries. For example:

```
docker run -ti gcr.io/google-containers/etcd:3.1.11 /bin/sh
/ # ls -lah /usr/local/bin
total 188252
drwxr-xr-x    2 root     root        4.0K Dec  5 11:11 .
drwxr-xr-x    4 root     root        4.0K Dec  5 11:11 ..
-rwxr-xr-x    1 root     root       13.3M Dec  5 11:10 attachlease
-rwxr-x---    1 root     root       15.6M Dec  5 11:11 etcd
-rwxr-x---    1 root     root       13.7M Dec  5 11:10 etcd-2.2.1
-rwxr-x---    1 root     root       16.6M Dec  5 11:10 etcd-2.3.7
-rwxr-x---    1 root     root       19.3M Dec  5 11:11 etcd-3.0.17
-rwxr-x---    1 root     root       15.6M Dec  5 11:11 etcd-3.1.11
-rwxr-x---    1 root     root       13.7M Dec  5 11:11 etcdctl
-rwxr-x---    1 root     root       12.1M Dec  5 11:10 etcdctl-2.2.1
-rwxr-x---    1 root     root       14.2M Dec  5 11:10 etcdctl-2.3.7
-rwxr-x---    1 root     root       17.6M Dec  5 11:11 etcdctl-3.0.17
-rwxr-x---    1 root     root       13.7M Dec  5 11:11 etcdctl-3.1.11
-rwxr-x---    1 root     root       10.0K Dec  5 11:10 migrate-if-needed.sh
-rwxr-xr-x    1 root     root       18.5M Dec  5 11:10 rollback
```
`ETCD_VERSION` determine which etcd binary is run. It is passed to [migrate-if-needed.sh](https://github.com/kubernetes/kubernetes/blob/d052476c303c5d567ea5b222eef46faabfd078cb/cluster/images/etcd/migrate-if-needed.sh#L21) as [TARGET_STORAGE](https://github.com/kubernetes/kubernetes/blob/494be59fda71f466590766d2b0313718e3498997/cluster/saltbase/salt/etcd/etcd.manifest#L57) which is used to select the exact etcd binary.

If I understood your suggestion right, we could check if `ETCD_VERSION` and `ETCD_IMAGE` are set to before emitting a warning in `kubernetes/cluster/gce/upgrade.sh` and skip the warning if they are set to 3.0.17 and etcd upgrade will not occur.

**Comment by enisoc** [comment]
I manually verified that the following works as expected to downgrade from 1.9 to 1.8:

```sh
ETCD_IMAGE=3.1.10 ETCD_VERSION=3.1.10 gce/upgrade.sh v1.8.5
```

* Before upgrading, my 1.8 cluster had etcd 3.0.17.
* After upgrading, my 1.9 cluster had etcd 3.1.10.
* After downgrading, my 1.8 cluster had etcd 3.1.10 still.

I'll work on adding a prompt to `gce/upgrade.sh` if these are unset.

**Comment by xiangpengzhao** [comment]
The latest downgrade test is running with the config by https://github.com/kubernetes/test-infra/pull/5909 :
Note the `--env=ETCD_VERSION=3.0.17`
```
I1212 23:21:44.980] Call:  /workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py --check-leaked-resources --check-version-skew=false --env=ETCD_VERSION=3.0.17 --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf --env-file=jobs/platform/gce.env --extract=ci/k8s-stable1 --extract=ci/k8s-beta --gcp-node-image=gci --gcp-zone=us-central1-f --provider=gce --skew '--test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8' --timeout=900m '--upgrade_args=--ginkgo.focus=\[Feature:ClusterDowngrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci'
```

But the test still seems to stuck on waiting for new master: `== Waiting for new master to respond to API requests ==`. There is no more log so I'm not sure if it's still due to etcd. @enisoc @krousey

**Comment by krzyzacy** [comment]
also xref https://github.com/kubernetes/kubernetes/issues/56879#issuecomment-351242966

**Comment by xiangpengzhao** [comment]
@krzyzacy thanks! I didn't notice that comment :)

**Comment by xiangpengzhao** [comment]
Let's wait for the next run against https://github.com/kubernetes/test-infra/pull/5920 :)

@krzyzacy Is there anyway to stop the current stuck run? It lasts so long (~15h) for each run.

**Comment by krzyzacy** [comment]
@xiangpengzhao you should be able to reference the `-parallel` variant, which runs more often

**Comment by krousey** [comment]
Which just had it's first green run.
