### ISSUE TITLE
The cloud node controller makes redundant calls to fetch the node addresses

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#57015]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network
/area cloudprovider 

**What happened**:

The cloud node controller fetches the node's addresses in [`AddCloudNode`](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L313). This logic is the exact same logic that happens in [`updateNodeAddress`](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L160) which [`AddCloudNode` calls](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L372). 

**What you expected to happen**:

I expect that `getNodeAddressesByProviderIDOrName` not be called twice in the same synchronous block of code. 

/assign

**Comment by lcfang** [comment]
Hi, @jhorwit2 , I doubt what conflicts will have when using `getNodeAddressesByProviderIDOrName` twice?

**Comment by jhorwit2** [comment]
@lcfang it causes two calls for the cloud provider when one will do.

**Comment by thockin** [comment]
@cheftako

**Comment by thockin** [comment]
Ping @cheftako
