### ISSUE TITLE
Diverse e2e Conformance Checks Failed

### ISSUE THREAD

**Issue by pekfi** [kubernetes/kubernetes#57035]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug
 /kind e2e-test-failure 
/sig storage
/sig auth
/sig testing

**What happened**:

Failure [19.458 seconds]
[sig-auth] ServiceAccounts
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/framework.go:22
  should mount an API token into pods [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/auth/service_accounts.go:246

  Expected error:
      <*errors.errorString | 0xc42084e480>: {
          s: "expected \"content of file \\\"/var/run/secrets/kubernetes.io/serviceaccount/ca.crt\\\": -----BEGIN CERTIFICATE-----\\nMIIDDTCCAfWgAwIBAgIJAO5dAxj+P13NMA0GCSqGSIb3DQEBCwUAMB0xGzAZBgNV\\nBAMMEmF0dS1kc3QtY2x1c3Rlci1jYTAeFw0xNzA2MDIxMTQ5MTdaFw00NDEwMTgx\\nMTQ5MTdaMB0xGzAZBgNVBAMMEmF0dS1kc3QtY2x1c3Rlci1jYTCCASIwDQYJKoZI\\nhvcNAQEBBQADggEPADCCAQoCggEBANKePBIBqUC1tVkipB7/8YCQmwPXgmWPwg74\\nc2pVsvB+R7wBxi2VtVas1efYJjQq7scSdOtg5WxjQJx3GS2tzlne2Lqgth8jb5km\\nDZu2CfILhNT5tNHIWQ0faaDm91BuXNMmUC1c+w+vYyXiNUUQ5UWIMLAp1TpJuo8r\\n86Y+25AtOaUPvU3H0yRJFmwTZdinlctjk9kxvj+MzKfEkkKXbIlUMv/zP6mlctcz\\n7b/NqqsMJTcGcSKDdE3gVSf7zin+YUpRHt/c2bLYiuudnZMRIXkGRJ7m4HKxlH6E\\npGvItTh233pf5G7YryBfwKG25mPMFXrN23mhm3I2eDnFan+GflMCAwEAAaNQME4w\\nHQYDVR0OBBYEFOIDbpOwiv3SYXND6cWROJZk7/vFMB8GA1UdIwQYMBaAFOIDbpOw\\niv3SYXND6cWROJZk7/vFMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB\\nAGbGdWuXZZLITqdkvLfQ8jsY5w/8VWHbcu9t5ZWBQlNwS/T2r8+6vxz2fzp5yJFC\\n6CadGg0P0f5u35Aga7AJk6gTvfC80XiPDoHkGj/4mZ+cnokK+xv9J5AWa/TcNL0q\\nTTf4z5PeqHzchaFK5k7KnBAQCz/0xKKpmGs8fXAier9L9ON4oBkRNixtFQO0/I0M\\no06uuMlnlj2TY7EpuI4OHBjVCGcOpEK0SDprqN3pY7Et331MP87BlCsyh0zgvKRJ\\nvBp7dQo3w9hYc88fC/wR1AVGDggOMjSyxD4UPayrz/7HrxhH0VA8OjMNSZVn/oXf\\nXxjSeSn9b9LuaOj8H0guEpg=\\n-----END CERTIFICATE-----\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: content of file \"/var/run/secrets/kubernetes.io/serviceaccount/ca.crt\": -----BEGIN CERTIFICATE-----\n  
[Fail] [k8s.io] Downward API volume [It] should provide container's cpu limit [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
.......

Failure [12.862 seconds]
[k8s.io] Downward API volume
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
  should provide container's cpu limit [Conformance] [sig-storage] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:163

  Expected error:
      <*errors.errorString | 0xc420ebe170>: {
          s: "expected \"2\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: 2\n    ",
      }
      expected "2\n" in container output: Expected
          <string>:
      to contain substring
          <string>: 2

  not to have occurred
.....

Failure [12.855 seconds]
[k8s.io] Downward API volume
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
  should provide container's cpu request [Conformance] [sig-storage] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go:181

  Expected error:
      <*errors.errorString | 0xc420edb540>: {
          s: "expected \"1\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: 1\n    ",
      }
      expected "1\n" in container output: Expected
          <string>:
      to contain substring
          <string>: 1

  not to have occurred
.....

Failure [12.911 seconds]
[k8s.io] Projected
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
  should provide container's cpu limit [Conformance] [sig-storage] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected.go:902

  Expected error:
      <*errors.errorString | 0xc421775180>: {
          s: "expected \"2\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: 2\n    ",
      }
      expected "2\n" in container output: Expected
          <string>:
      to contain substring
          <string>: 2

  not to have occurred
.........

Failure [10.905 seconds]
[k8s.io] Projected
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
  should provide container's memory limit [Conformance] [sig-storage] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected.go:911

  Expected error:
      <*errors.errorString | 0xc420a46410>: {
          s: "expected \"67108864\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: 67108864\n    ",
      }
      expected "67108864\n" in container output: Expected
          <string>:
      to contain substring
          <string>: 67108864

  not to have occurred
.....

 Failure [12.909 seconds]
[k8s.io] Projected
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:635
  should provide container's memory request [Conformance] [sig-storage] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/projected.go:929

  Expected error:
      <*errors.errorString | 0xc421c479d0>: {
          s: "expected \"33554432\\n\" in container output: Expected\n    <string>: \nto contain substring\n    <string>: 33554432\n    ",
      }
      expected "33554432\n" in container output: Expected
          <string>:
      to contain substring
          <string>: 33554432

  not to have occurred
......

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
sonobuoy conformance test manual

docker pull gcr.io/heptio-images/kube-conformance:v1.8

docker run -it -v /etc/kubernetes/admin.conf:/config --name conformance18 gcr.io/heptio-images/kube-conformance:v1.8 bash

mkdir /tmp/results
cd
/usr/local/bin/e2e.test --repo-root=/kubernetes --ginkgo.skip='Alpha|Disruptive|Feature|Flaky|Kubectl' --ginkgo.focus=Conformance --provider="local" --report-dir="/tmp/results" --kubeconfig="/config" --ginkgo.noColor=true | tee /tmp/results/e2e-$(date +%F-%H%M%S).log

**Anything else we need to know?**:
sonobuoy container 1.8 (latest)
[Fail] [sig-auth] ServiceAccounts [It] should mount an API token into pods [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
[Fail] [k8s.io] Downward API volume [It] should provide container's cpu limit [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
[Fail] [k8s.io] Downward API volume [It] should provide container's cpu request [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
[Fail] [k8s.io] Projected [It] should provide container's cpu limit [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
[Fail] [k8s.io] Projected [It] should provide container's memory limit [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191
[Fail] [k8s.io] Projected [It] should provide container's memory request [Conformance] [sig-storage]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2191

sonobuoy container 1.7.3
[Fail] [k8s.io] Downward API volume [It] should provide container's memory limit [Conformance] [Volume]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2242
[Fail] [k8s.io] Projected [It] should provide container's memory request [Conformance] [Volume]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2242
[Fail] [k8s.io] Projected [It] should provide container's cpu request [Conformance] [Volume]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2242
[Fail] [k8s.io] Downward API [It] should provide pod and host IP as an env var [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2242
[Fail] [k8s.io] Networking [BeforeEach] should provide Internet connection for containers [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:41
[Fail] [k8s.io] ServiceAccounts [It] should mount an API token into pods [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2242

**Environment**:
- Kubernetes version (use `kubectl version`):
1.8.4
- Cloud provider or hardware configuration:
bare metal VM, external ETCD 3.2.9, cluster, CNI calico-node 2.6.3
- OS (e.g. from /etc/os-release):
RHEL7
- Kernel (e.g. `uname -a`):
3.10.0-693.5.2.el7.x86_64
- Install tools:
puppet
- Others:
docker 1.12.6/1.13.1

**Comment by liggitt** [comment]
it appears log output from the test pods was not being captured correctly. are there docker or kubelet logs from this run?

**Comment by pekfi** [comment]
[github-messages-20171208-failure1.txt](https://github.com/kubernetes/kubernetes/files/1555117/github-messages-20171208-failure1.txt)
[github-messages-20171208-failure2.txt](https://github.com/kubernetes/kubernetes/files/1555118/github-messages-20171208-failure2.txt)
[github-messages-20171208-failure3.txt](https://github.com/kubernetes/kubernetes/files/1555119/github-messages-20171208-failure3.txt)
[github-messages-20171208-failure4.txt](https://github.com/kubernetes/kubernetes/files/1555120/github-messages-20171208-failure4.txt)
[github-messages-20171208-failure5.txt](https://github.com/kubernetes/kubernetes/files/1555121/github-messages-20171208-failure5.txt)
[github-messages-20171208-failure6.txt](https://github.com/kubernetes/kubernetes/files/1555122/github-messages-20171208-failure6.txt)

**Comment by liggitt** [comment]
cc @deads2k

**Comment by liggitt** [comment]
do all the log lines with issues have newlines? @mrunalp could https://github.com/kubernetes/kubernetes/pull/55631 be related?

**Comment by liggitt** [comment]
@pekfi what logdriver are you using for docker?

**Comment by pekfi** [comment]
/usr/bin/dockerd-latest --add-runtime docker-runc=/usr/libexec/docker/docker-runc-latest --default-runtime=docker-runc --authorization-plugin=rhel-push-plugin --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-latest -g /var/lib/docker-latest --selinux-enabled **--log-driver=journald** --signature-verification=false --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/vg_data-docker--latest--pool --storage-opt dm.use_deferred_removal=true

**Comment by pekfi** [comment]
problem solved, update to docker version docker-client-latest-1.13.1-36.git9a813fa.el7.x86_64 docker-common-1.12.6-68.gitec8512b.el7.x86_64 docker-latest-1.13.1-36.git9a813fa.el7.x86_64 docker-rhel-push-plugin-1.12.6-68.gitec8512b.el7.x86_64

**Comment by deads2k** [comment]
@stevekuznetsov applicable to us?

**Comment by stevekuznetsov** [comment]
Might be? Lots of log errors when using Docker+`journald` smells like that classic issue...
