### ISSUE TITLE
Test flake: Missing local artifacts : /workspace/_artifacts

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#57032]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind flake
/area test

**What happened**:
The CIs complain

> W1211 08:08:13.941] Traceback (most recent call last):
W1211 08:08:13.941]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 170, in <module>
W1211 08:08:13.941]     main(ARGS.branch, ARGS.script, ARGS.force, ARGS.prow)
W1211 08:08:13.942]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 138, in main
W1211 08:08:13.942]     check(*cmd)
W1211 08:08:13.942]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 54, in check
W1211 08:08:13.943]     subprocess.check_call(cmd)
W1211 08:08:13.943]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W1211 08:08:13.943]     raise CalledProcessError(retcode, cmd)
W1211 08:08:13.944] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/workspace/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/workspace/k8s.io/:/workspace/k8s.io/', **'-v', '/workspace/_artifacts:/workspace/artifacts'**, '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/workspace/k8s.io/kubernetes', '--tmpfs', '/tmp:exec,mode=1777', 'gcr.io/k8s-testimages/kubekins-test:1.9-v20171018-6ddbad97', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/test-dockerized.sh')' returned non-zero exit status 2
E1211 08:08:13.950] Command failed
I1211 08:08:13.950] process 617 exited with code 1 after 4.8m
E1211 08:08:13.950] FAIL: pull-kubernetes-unit
I1211 08:08:13.951] Upload result and artifacts...
I1211 08:08:13.951] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57023/pull-kubernetes-unit/70209
**W1211 08:08:13.951] Missing local artifacts : /workspace/_artifacts**
W1211 08:08:13.952] metadata path /workspace/_artifacts/metadata.json does not exist

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/57023/pull-kubernetes-unit/70209
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/57023/pull-kubernetes-unit/70212
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/57023/pull-kubernetes-unit/70236

@ixdy @mkumatag `/retest` does not work.

**What you expected to happen**:
No such errors

**Comment by ixdy** [comment]
That's not a flake, it's a broken build.

Gubernator is hiding the relevant bits, though:
```
I1211 08:08:10.319] +++ [1211 08:08:10] Building go targets for linux/amd64:
I1211 08:08:10.319]     cmd/kubeadm
W1211 08:08:12.915] vendor/github.com/google/cadvisor/container/crio/factory.go:24:2: build constraints exclude all Go files in /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/libcontainer
W1211 08:08:12.924] !!! [1211 08:08:12] Call tree:
W1211 08:08:12.927] !!! [1211 08:08:12]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:707 kube::golang::build_binaries_for_platform(...)
W1211 08:08:12.929] !!! [1211 08:08:12]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W1211 08:08:12.935] !!! [1211 08:08:12] Call tree:
W1211 08:08:12.938] !!! [1211 08:08:12]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W1211 08:08:12.944] !!! [1211 08:08:12] Call tree:
W1211 08:08:12.946] !!! [1211 08:08:12]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W1211 08:08:12.947] make[1]: *** [all] Error 1
W1211 08:08:12.951] make: *** [test-cmd] Error 1
I1211 08:08:13.052] Makefile:92: recipe for target 'all' failed
I1211 08:08:13.052] Makefile:292: recipe for target 'test-cmd' failed
```

cc @rmmh

**Comment by dims** [comment]
Right, @dixudx did see the note from me about the cgo / `import "C"` so let's close this out.

/close
