### ISSUE TITLE
kube 1.8 deployment garbage collection doesn't work with --leader-elect=false

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/kubernetes#57044]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

If a 1.8.x  kubernetes master with a single controller-manager is configured with --leader-elect=false, deleting a deployment through the API with v1meta.DeletePropagationForeground doesn't work.

The deployment has its deletionTimestamp set and a foregroundDeletion finalizer is added, but the pod, rc and deployment are not deleted.

**What you expected to happen**:

The pod, rc and deployment should be deleted when the controller-manager uses --leader-elect=false.

**How to reproduce it (as minimally and precisely as possible)**:

I used kubeadm with calico networking, and modified the controller-manager configuration via

sudo sed -i /etc/kubernetes/manifests/kube-controller-manager.yaml -e '/leader-elect/ s/true/false/'

and then ran https://github.com/kubernetes/client-go/blob/master/examples/create-update-delete-deployment/ to create and delete deployments.

**Anything else we need to know?**:

I suspect the problem is related to this change:
https://github.com/kubernetes/kubernetes/commit/253b047d89eac2b5a3074ece31842a8e1c4302d2

It appears to require leader election before the GC controller will finish initialization.
Looking at controller-manager logs with leader-elect=false, I saw this log entry from garbagecollector/graph_builder.go:

   "GraphBuilder running"

I did not see the "started %d new monitors, %d currently running" log entry at the end of the startMonitors() function.  That seems consistent with the GC controller waiting for "<-gb.informersStarted"

**Environment**:
- Kubernetes version (use `kubectl version`): tested with 1.8.2 and 1.8.4
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): vagrant virtualbox with the ubuntu/xenial64 box
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:

**Comment by jmcmeek** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by cmluciano** [comment]
@kubernetes/sig-api-machinery-bugs 

cc @deads2k Have you seen this in Openshift?

**Comment by roycaihw** [comment]
cc @ironcladlou @caesarxuchao

**Comment by jmcmeek** [comment]
I think this problem occurs because controllermanager.go initialiuzes the stop channel top nil when leader-elect=false.  This causes garbage collector graph_builder to exit early.

The following release-1.8 patch seems to fix the problem.  controllermanager.go creates a dummy channel which will never be closed and allows the garbage collector graph builder to work like it does when leader-elect is true.

```
diff --git a/cmd/kube-controller-manager/app/controllermanager.go b/cmd/kube-controller-manager/app/controllermanager.go
index 33a2e8c7a7..6d6646257f 100644
--- a/cmd/kube-controller-manager/app/controllermanager.go
+++ b/cmd/kube-controller-manager/app/controllermanager.go
@@ -163,7 +163,9 @@ func Run(s *options.CMServer) error {
        }
 
        if !s.LeaderElection.LeaderElect {
-               run(nil)
+               stopCh := make(chan struct{})
+               defer close(stopCh)
+               run(stopCh)
                panic("unreachable")
        }
 
@@ -441,10 +443,6 @@ func CreateControllerContext(s *options.CMServer, rootClientBuilder, clientBuild
                }
        }
 
-       if informerUserCloud, ok := cloud.(cloudprovider.InformerUser); ok {
-               informerUserCloud.SetInformers(sharedInformers)
-       }
-
        ctx := ControllerContext{
                ClientBuilder:      clientBuilder,
                InformerFactory:    sharedInformers,
```

**Comment by rtheis** [comment]
@jmcmeek: do you really need to remove the following code?

```
-       if informerUserCloud, ok := cloud.(cloudprovider.InformerUser); ok {
-               informerUserCloud.SetInformers(sharedInformers)
-       }
```

**Comment by jmcmeek** [comment]
@rtheis That change was not intended.  I also noticed that after I saved my change.  I redid the patch and edited my previous comment to reflect that.

**Comment by ironcladlou** [comment]
Agree with the diagnosis and fix, @jmcmeek are you going to open a PR?

**Comment by jmcmeek** [comment]
@ironcladlou Yes, I can do that.  Reading your PR guidelines and ours.

**Comment by jmcmeek** [comment]
@ironcladlou Will I need to go through [cherry-pick process](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md) to get this into the release-1.8 and release-1.9 branches?
