### ISSUE TITLE
[API] Service ClusterIP should be able to be disabled (for headless services)

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#57069]
Hi,

I run a **Kubernetes 1.8.x IPv6-only** cluster from few weeks now and everything works fine except one of the most painful problem, `Services ClusterIP`. 

When creating a `ClusterIP: None` service on Kubernetes, you can speak to the service name (like `kubernetes.default.svc.cluster.local` using Endpoints (Pod IP) instead of Cluster IP (10.32.x.x/16). 

It would be awesome, for the 1.9.x branch to be able to disable ClusterIP on the `Kube-APIServer` side. For example, with this args : 

```
--service-cluster-ip-range=None
```
The impact of this should replace `type: ClusterIP` to `clusterIP: None` in Kubernetes Services. 

It would be a great thing for people who want to avoid ClusterIP NAT for specific services (Like UDP stuffs, SIP, DNS) which is recommended avoiding packet manipulation. 

Another thing, actually if you enable IPv6 in your cluster (dual-stack) because of the IPv4 ClusterIP,  IPv6 will not be used a lot. 

If  `--service-cluster-ip-range=None` can turn by default `clusterIP: None`, the APIServer should record the Pod's IPv6 by default instead of the IPv4 one (in dual-stack cluster). 

Here is my IPv6-only configuration detailed in a blog post : 
https://opsnotice.xyz/kubernetes-ipv6-only/

Any thought about that ?

/sig network
@kubernetes/sig-network

**Comment by xiangpengzhao** [comment]
/cc @danehans 
@kubernetes/sig-network-feature-requests

**Comment by leblancd** [comment]
@valentin2105 
Would it make sense to split this proposal into 2 issue requests? It seems to me that there are 2 parts to this, the first being independent of IPv4 vs IPv6 operation, and the second being something to consider when dual-stack support is added. If I'm understanding correctly, here are the 2 parts to the proposal:
1. Allow "--service-cluster-ip-range=None" on the command line to force ALL services in headless mode. This should be independent of IPv4 vs. IPv6 operation, as far as I can tell.
2. If a service is running headless in a dual-stack configuration (dual-stack net yet supported as of 1.9.0), then the IPv6 Pod address(es) should be favored over IPv4 in responses to DNS lookups e.g. to "kubernetes.default.svc.cluster.local". Did I get that correct? As an alternative, could kube-dns / coreDNS return both A and AAAA records and let the app that's referencing kubernetes.default.svc.cluster.local decide which to use?
BTW, I get a certificate error when I try your link. Is this content available at another link?

**Comment by valentin2105** [comment]
Hi @leblancd 

You're totally true, it's two different Issues, 

This one can be focused on "**Disable ClusterIP on Cluster-wide**" because (in v4 or v6) people may want to totally disable the use of IPTables for network traffic, to avoid NAT and got headless mode on all services. 

I will open another issue to talk about the **need of support both IP protocol on API and Kube-DNS** side and I think like you, it’s better to let the app choose between IPv4 or v6.
KubeDNS will act like a classic DNS server that answer both A and AAAA. 

Do k8s-API 1.9.x will support `Pod.IP` for IPv4 AND IPv6 ? 
Because in dual-stack, actually in 1.8.x API got only the IPv4 IP. 

About the blog post, I use ECDSA certs, so it should work on Google-Chrome / Safari normally ?

**Comment by leblancd** [comment]
@valentin2105 The k8s-API for 1.9.0 supports pod addresses that are either IPv4 OR IPv6, not both. The API is only aware of a single IP per pod at the moment (uses a singleton, not an array of addresses). Some CNI network plugins are ahead of Kubernetes in terms of dual-stack support (such as Calico and bridge)... but if you configure your CNI in dual-stack mode, Kubernetes will only report one of the addresses (the address that your CNI/IPAM plugin happens to allocate first, I believe). Similarly for services, kube-proxy for Kubernetes 1.9.0 can only run in IPv4-only mode (iptables) or IPv6-only mode (ip6tables).

**Comment by thockin** [comment]
I don't think we want to disable cluster IP services by a flag.  This is something you could do with a custom admission controller - but rather than mutating the svc, just reject it.

dual-stack is a WHOLE other can of worms.
