### ISSUE TITLE
spec.hostname cannot be set after pod admission

### ISSUE THREAD

**Issue by mlowery** [kubernetes/kubernetes#57065]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Admittedly, this is a rather exotic use case but at least one other user (#47268) also needs pod hostnames that depend on where the pod is scheduled. The ultimate goal is that when the `hostname` command is run inside any container of the pod, it returns this value.

As I state in https://github.com/kubernetes/kubernetes/issues/47268#issuecomment-350751809, we have accomplished this in Kubernetes 1.6 with the following pieces:

1. Custom controller that sets `spec.hostname` after the pod has been scheduled. (As a reminder, Kubernetes 1.6 allows setting this field after apiserver admission. This has since been disallowed in Kubernetes 1.8.)
2. Custom soft admit handler in kubelet that returns error until `spec.hostname` has been set, effectively stalling the creation of the `pause` container.

The obvious answer is to modify the validation to allow `spec.hostname` to be set after apiserver admission. But I appreciate the hesitance to do so given its lack of general utility. In other words, if a user sets this field after admission, they have a reasonable expectation that something will happen in response. I don't believe anything happens in response to this modification today.

But the alternative is to put the custom hostname in an annotation and have a kubelet net plugin do something with it. According to #47268, this doesn't work. There's also a bit of dirtiness that `spec.hostname` is ignored and does not reflect the actual pod hostname.

**What you expected to happen**:

Be able to set `spec.hostname` after pod admission (or another alternative).

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network
@kubernetes/sig-network

**Comment by thockin** [comment]
Can we just use #47268 instead of having 2 bugs?
