### ISSUE TITLE
SharedInformer should expose a method to notify underlying listerWatcher status

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#57074]
When we use a shared informer, after CacheSync, we can not know whether the underlying reflector works well. If Reflector.listerWatcher can not List/Watch successfully due to network, the resource we can use is outdated, which is not acceptable we we use a kind of configurations resource.  

1.  We should provide a way to let client know whether informer works well now.
2.  We should provide a way to let client know when/why the informer underlying list/watch fail.

So client can decide to goon working or send warning info to monitor system or something else.

**Comment by sch00lb0y** [comment]
@hzxuzhonghu 
I think we should have something like ErrFunc in ResourceEventHandlerFuncs to expose  such error .
It'll will great if you can share opinion on this and even I'm willing to pick this issue.

**Comment by yue9944882** [comment]
Note that this feature would be also helpful in the case when we try to list/watch secrets via informer but the RBAC authentication reject the client-side's list/watch request. 

Via current logic, we don't really know why list/watch failed. Providing a way to peek the underlying error will do the trick.

**Comment by hzxuzhonghu** [comment]
@kubernetes/sig-api-machinery-misc
