### ISSUE TITLE
kube-apiserver auto generated spf13/cobra documentation misses `--v` switch.

### ISSUE THREAD

**Issue by aknrdureegaesr** [kubernetes/kubernetes#57098]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I checked the [official documentation](https://kubernetes.io/docs/reference/generated/kube-apiserver/) for the command line switches of `kube-apiserver`.  I know that there is such a switch `--v`, but it does not get documented there.

**What you expected to happen**:

That official documentation should be complete, as far as command line switches is concerned.

**How to reproduce it (as minimally and precisely as possible)**:

Look at [documentation](https://kubernetes.io/docs/reference/generated/kube-apiserver/).

**How to reproduce (somewhat more elaborated and slightly speculatively):**

* Run `build/run.sh make` as suggested in the [build instructions](https://github.com/kubernetes/kubernetes/blob/b97e17603b76edf7344f49a7632b1f764d5386e6/build/README.md)
* Run `mkdir /tmp/foo` and `cd _output/dockerized/bin/linux/amd64 && ./genkubedocs /tmp/foo kube-apiserver`

Result seen: The resulting `/tmp/foo/kube-apiserver.md` is also lacking the documentation for `--v`, after doing the above on v1.8.5 aka `cce11c6a18`.

(I assume, but I am not absolutely sure, that this is how the web site documentation is produced.)

**Anything else we need to know?**:

#### Related bug

I filed this [as bug 6571](https://github.com/kubernetes/website/issues/6571) in `kubernetes/website` and they asked me to file it here, too.

#### Command line documentation is ok

When one runs `kube-apiserver --help`, the `--v` switch is documented as expected.

**Comment by aknrdureegaesr** [comment]
@kubernetes/sig-cli

**Comment by nikhita** [comment]
This is documented now.

/close
