### ISSUE TITLE
Kubectl doesn't print GPU allocated when using kubectl describe node xxxx

### ISSUE THREAD

**Issue by jackytu** [kubernetes/kubernetes#57094]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We are using kubernetes to manage a machine learning cluster with GPU devices, and  need to know the GPU resource status of each node,  for cluster management.  However, the GPU status is not printed, when using `kubectl describe node xxx`, to get the resource status  of  a node with GPU devices,  just as the following:

![image](https://user-images.githubusercontent.com/3814418/33878936-db9707a0-df67-11e7-9071-3cb33e2d6d10.png)

**What you expected to happen**: 
Print the GPU status of the node with GPU devices, and each pod on this node,  like the CPU&Memory resources,  when using  `kubectl describe node xxxxx`.

**How to reproduce it (as minimally and precisely as possible)**:
describe a node with GPU devices using command `kubectl describe node xxx`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.9.0-0.bpo.3-amd64
- Install tools: 
- Others:

**Comment by vikaschoudhary16** [comment]
i see there `alpha.kubernetes.io/nvidia-gpu: 4` under the `Capacity` and `Allocatable` in the screenshot you pasted or is it expected result?

**Comment by scprek** [comment]
/remove-lifecycle rotten

Interested in GPU information in `Allocated resources`

**Comment by clkao** [comment]
With https://github.com/kubernetes/kubernetes/pull/46079, 1.11.0 `kubectl describe node` actually prints GPU allocated, but not with percentage of capacity like gpu/mem:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource        Requests        Limits
  --------        --------        ------
  cpu             12916m (40%)    20406m (63%)
  memory          205368Mi (39%)  215159406592 (39%)
  nvidia.com/gpu  4               4
```

**Comment by skyhills13** [comment]
@clkao Hello. Is there any way to know the allocated GPU Id? Not only the number of allocated gpus.

**Comment by cep21** [comment]
@skyhills13 I have the same question.  Did you ever figure it out?

**Comment by skyhills13** [comment]
@cep21 Nope. I could only know the host of allocated GPU. But I found out that allocated GPU Ids are always same in sequential order. If you request one GPU, GPU Id is always 0 and if you request 2, Ids are 0 and 1. You can use this if you need Id for using them somewhere in the code.
