### ISSUE TITLE
kube-dns (10.96.0.10) unavailable on minion nodes

### ISSUE THREAD

**Issue by irishandyb** [kubernetes/kubernetes#57096]
/kind bug

**What happened**:

I have deployed a fresh `1.8.5` cluster with a single master and single minion via `kubeadm`.
I have deployed `flannel` as the CNI plugin.
The cluster appears healthy and all `kube-system` pods (including `kube-proxy` and `kube-dns`) are up and running with no errors in the logs (only a single warning detailed below).

Any pods that are scheduled on the minion node do not have access to `kube-dns` on `10.96.0.10`.

On the master node, `10.96.0.10` is accessible:
```
[centos@k8s-kube-master-0 ~]$ dig google.com @10.96.0.10

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.1 <<>> google.com @10.96.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17191
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             154     IN      A       216.58.201.46

;; Query time: 2 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Tue Dec 12 11:07:02 UTC 2017
;; MSG SIZE  rcvd: 55
```

However on the minion node, `10.96.0.10` is inaccessible:

```
[centos@k8s-kube-node-0 ~]$ dig google.com @10.96.0.10                                                                                                                                                    

               

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.1 <<>> google.com @10.96.0.10
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Note - I tested the above `dig` commands on the master and minion nodes both on the nodes themselves and within pods on the nodes.

**What you expected to happen**:

The minion node (and pods running on the minion) should be able to access `kube-dns` via `10.96.0.10`.

**How to reproduce it (as minimally and precisely as possible)**:

[Create a fresh 1.8.5 cluster via `kubeadm`](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)

Attempt to run `dig google.com @10.96.0.10` on the minion node as above.

**Anything else we need to know?**:
- I have followed the [service-debugging/troubleshooting](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service) guide.

When I reach the [does-the-service-work-by-dns](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#does-the-service-work-by-dns) section - the `nslookup` fails (hangs/timeout).

Interestingly when I reach the [does-the-service-work-by-ip](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#does-the-service-work-by-ip) section - the service does work by IP and all of the endpoints do return their hostnames - so it seems to be just DNS that is a problem.

However, I am unclear of the steps outlined in the [is-the-kube-proxy-working](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service//#is-the-kube-proxy-working) section.
The section calls out checking `kube-proxy` logs via `/var/log/kube-proxy.log` or `journalctl` but there is no `kube-proxy.log` on my minion server nor any `kube-proxy` related messages in `journalctl` (apart from the `kubelet` logs related to deloying the `kube-proxy` pod).
My interpretation of the troubleshooting guide is to check for the `kube-proxy` logs on the host node itself, however I can only access them via the `kube-proxy` pod logs - which contain:
```
W1212 10:20:33.731679       1 server.go:191] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
W1212 10:20:33.801444       1 server_others.go:268] Flag proxy-mode="" unknown, assuming iptables proxy
I1212 10:20:33.803386       1 server_others.go:122] Using iptables Proxier.
I1212 10:20:33.824248       1 server_others.go:157] Tearing down inactive rules.
I1212 10:20:33.921035       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I1212 10:20:33.921098       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I1212 10:20:33.922396       1 conntrack.go:83] Setting conntrack hashsize to 32768
I1212 10:20:33.922621       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1212 10:20:33.922656       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1212 10:20:33.923269       1 config.go:202] Starting service config controller
I1212 10:20:33.925494       1 controller_utils.go:1041] Waiting for caches to sync for service config controller
I1212 10:20:33.925616       1 config.go:102] Starting endpoints config controller
I1212 10:20:33.925627       1 controller_utils.go:1041] Waiting for caches to sync for endpoints config controller
I1212 10:20:34.025776       1 controller_utils.go:1048] Caches are synced for service config controller
I1212 10:20:34.025839       1 controller_utils.go:1048] Caches are synced for endpoints config controller
```

Note: That warning on the first line is very interesting - I note that the `kube-proxy` command line is as below and that the `--cluster-cidr` is being passed on the command line.
```
/usr/local/bin/kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf --cluster-cidr=10.244.0.0/16
```
If `all flags other than --config, --write-config-to, and --cleanup are depreciated` then - does that mean that `--cluster-cidr` is being ignored and needs to be set in the `kubeconfig.conf` file by `kubeadm`?

For the remaining sections in this troubleshooting guide:
[is-kube-proxy-writing-iptables-rules](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-kube-proxy-writing-iptables-rules) - yes
[is-kube-proxy-proxying](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-kube-proxy-proxying) - yes

- I have tried Flannel, Calico, and Multus
Always installed to a freshly install k8s cluster, always with the same result, thus I do not think that this is a CNI plugin issue.
- I have followed the [dns-pod-service/#how-do-i-test-if-it-is-working](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#how-do-i-test-if-it-is-working) troubleshooting guide but as above - the `nslookup` fails.

- I do pass the appropriate `--pod-network-cidr` or `--pod-network-cidr=` to `kubeadm init` depending on the CNI plugin (`--pod-network-cidr=10.244.0.0/16` in the case of flannel)

- I have checked the logs for `kube-proxy`, `kube-dns` and `flanneld` - all of which only contain healthy looking `info` level messages (apart from the one `kube-proxy` `warning` message above).

- I ensure to set `net.ipv4.ip_forward=1` and `net.bridge.bridge-nf-call-iptables=1` via `sysctl`

- As per the suggestions in #45459 - I am using flannel `0.9.1` and I pass `--iptables=false` to `dockerd` in the Docker systemd unit.

- I pass `--iface=eth0` to flanneld as suggested in [flannel issue #535](https://github.com/coreos/flannel/issues/535)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", 

GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", 

GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Deploying to Openstack Mikata.
- OS (e.g. from /etc/os-release):
I have tried both CentOS 7.3.1611 and Ubuntu 16.04.
- Kernel (e.g. `uname -a`):
`Linux k8s-kube-master-0 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
`kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- There is no firewalld or iptables services running

**Comment by irishandyb** [comment]
Adding sig labels as per @k8s-merge-robot 

@kubernetes/sig-network-bugs

@kubernetes/sig-openstack-bugs

(also adding Openstack as I am running on Mitaka and perhaps there is a slim chance this issue is related to running k8s on OS).

**Comment by irishandyb** [comment]
Was able to get to the bottom of this with the help of @shaun.crampton over on the Calico slack #flannel.

This was not a k8s issue but rather an oversight on my behalf with regard to the OpenStack Security Group configuration.

My Security Group had Ingress rules for TCP (1-65353) - however I was missing rules for UDP traffic thus the DNS traffic was being dropped by the Security Group at the OpenStack network layer.

Happily closing the issue  :)

Andy

**Comment by shengshuaijohnson** [comment]
> Was able to get to the bottom of this with the help of @shaun.crampton over on the Calico slack #flannel.
> 
> This was not a k8s issue but rather an oversight on my behalf with regard to the OpenStack Security Group configuration.
> 
> My Security Group had Ingress rules for TCP (1-65353) - however I was missing rules for UDP traffic thus the DNS traffic was being dropped by the Security Group at the OpenStack network layer.
> 
> Happily closing the issue :)
> 
> Andy

OMG u savvvvvvvvvve me !!!!!

**Comment by naprawogiubiwam** [comment]
🤔
