### ISSUE TITLE
E2E: Logf() always adding a newline to the message

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#57102]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`Logf()` is always appending a new line to its message:
https://github.com/kubernetes/kubernetes/blob/b97e17603b76edf7344f49a7632b1f764d5386e6/test/e2e/framework/util.go#L266-L272

In some places of code, the message is already has a newline character and it leads to doubled new lines in the logs.

**What you expected to happen**:
I'm not sure what is the correct behavior here. One of the options could be to append a new line conditionally.

**Comment by MorrisLaw** [comment]
@php-coder I'm new to Kubernetes and would like to start contributing. Is it ok if I assign myself this issue?

**Comment by MorrisLaw** [comment]
I can't assign this to myself, as I am not a member yet. But I am still going to take this issue.

**Comment by timothysc** [comment]
I'll help him on reviews so assigning.
