### ISSUE TITLE
kube-dns returns NXDOMAIN when not yet synced with apiserver

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#57111]
**What happened**:
when kube-dns has not yet synced with the apiserver, it return NXDOMAIN for all cluster names

**What you expected to happen**:
It should return SERVFAIL

**Anything else we need to know?**:
NXDOMAIN is the wrong status. It even can be cached by downstream DNS servers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4

**Comment by thockin** [comment]
@johnbelamaric

**Comment by thockin** [comment]
See https://github.com/kubernetes/dns/issues/186
