### ISSUE TITLE
Windows Kubelet.exe fails to start on VMWare Fusion due to GetPhysicallyInstalledSystemMemory fails

### ISSUE THREAD

**Issue by JiangtianLi** [kubernetes/kubernetes#57110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Windows kubelet.exe uses GetPhysicallyInstalledSystemMemory to get physical memory installed on Windows machine and reports it as part of node metrics to heapster, etc. On VMWare Fusion, GetPhysicallyInstalledSystemMemory fails to read data from SMBIOS firmware tables and returns error code 0x0d. That causes kubelet.exe on Windows to bail out. It is also reported on Virtualbox.

**What you expected to happen**:
Windows kubelet.exe should be able read to physical memory on the system and shouldn't exit.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet.exe on VMWare Fusion or Virtualbox .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: VMWare Fusion or Virtualbox

**Comment by michmike** [comment]
this will likely get fixed after 1.9 is released

**Comment by JiangtianLi** [comment]
@michmike Sure, I am fixing it. Unfortunately it missed the 1.9 train.

**Comment by rchampag** [comment]
Hi, any idea on when this might get fixed? Thanks!

**Comment by rchampag** [comment]
@JiangtianLi, thanks for the swift reply! I need to learn some new (for me) github skills to get that PR.

**Comment by michmike** [comment]
@JiangtianLi  i just approved the PR again. we should be good to go. can you please check
