### ISSUE TITLE
REST api - plural error message when failed to create a single namespace

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#5712]
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "namespaces \"staging\" already exists",
  "reason": "AlreadyExists",
  "details": {
    "id": "staging",
    "kind": "namespaces"
  },
  "code": 409
}

cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
The generic registry co-mingles the EndpointName with Kind:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L174

Right now, all of our EndpointNames are in the plural form across all registries.
