### ISSUE TITLE
Calico won't be scheduled on tainted nodes

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#57120]
/kind bug

**What happened**:

Deployed a GCE cluster using Calico, tainted some nodes.

Calico did not run on those nodes, and as a result no other pods could run on that node.

**What you expected to happen**:

Calico should tolerate all taints, and run on all nodes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

CC @dnardo

**Comment by dnardo** [comment]
cc @mindprince
