### ISSUE TITLE
Unexpected command output nsenter: cannot open : No such file or directory

### ISSUE THREAD

**Issue by ChipmunkV** [kubernetes/kubernetes#57137]
/kind bug

**What happened**:

Sometimes pods start with no network and stay that way. Their services aren't reachable.

**What you expected to happen**:

Pod should have some `eth@` interface, not only the `lo`. Host's iptables should contain some DNAT and --dport rules instead of REJECT rules with "default/my-service: has no endpoints" comments.

**How to reproduce it (as minimally and precisely as possible)**:

Happens on reboot for a small percentage of pods.

**Anything else we need to know?**:

On system boot or when deleting that kind of pod, there are logs like that in kubelet:
```
NetworkPlugin cni failed on the status hook for pod "<POD>": Unexpected command output nsenter: cannot open : No such file or directory
```

Killing the pod starts a new one that's functional.

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Single node, bare metal, bridge networking plugin:
```
{
	"name": "knet0",
	"type": "bridge",
	"bridge": "kbr0",
	"isDefaultGateway": true,
	"forceAddress": false,
	"ipMasq": true,
	"hairpinMode": true,
	"ipam": {
		"type": "host-local",
		"subnet": "10.10.0.0/16"
	}
}

```

- OS: Ubuntu 16.04.3 LTS
- Kernel: 4.4.0-103-generic 126-Ubuntu
- Install tools: kubeadm
- Others: N/A

**Comment by thockin** [comment]
Any clues how to repro this?  without that it will likely just sit here...

**Comment by pacoxu** [comment]
similar issue

POD status is "Failed" and then "Terminating", but cannot be removed util manually remove it.
