### ISSUE TITLE
client-go: "go get" of master branch is not compilable

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#57147]
We delete all k8s.io/* dependencies from vendor/ directory of exported staging repos for the master branch. Current kube-openapi master branch (which `get get` will download) is not compatible with current k8s.io/client-go master branch.

Broken travis build: https://travis-ci.org/kubernetes/client-go/builds/315272939

**Comment by luksa** [comment]
Wait, it's broken even after https://github.com/kubernetes/kube-openapi/pull/28 was merged?

**Comment by sttts** [comment]
@luksa is kubernetes/kube-openapi#28 vendored into kube already?

**Comment by luksa** [comment]
No, but my initial change that broke everything isn't either. kubernetes/kube-openapi#28 should have fixed the go get problem. So, I'm surprised you're still seeing it.

**Comment by sttts** [comment]
@luksa maybe a rerun helps.

**Comment by sttts** [comment]
@luksa 🎉   https://travis-ci.org/kubernetes/client-go/builds/315272939
