### ISSUE TITLE
image_gc_manager can remove images unrelated to k8s

### ISSUE THREAD

**Issue by cyphar** [kubernetes/kubernetes#57145]
/kind bug
/sig node

**What happened**:

If you have a host which has pulled images that are not used as part of kubernetes (they aren't images that are used by any pods), and then trigger `image_gc_manager`, those images may be removed (if they're large enough). This can cause a lot of issues if you have a system that uses both k8s and more traditional containers on the same container runtime (for instance if you have k8s running but also some management tools that run in containers outside of k8s).

**What you expected to happen**:

`image_gc_manager` should (ideally) only remove images that were pulled by kubelet in the first place. From my understanding the purpose of `image_gc_manager` is to avoid image store churn if you have pod churn, while also allowing for disk reclaim. It's an amortization over removing all images that a pod was using if it was the last pod using said images. Therefore it would make sense

**How to reproduce it (as minimally and precisely as possible)**:

On a kubernetes host:
```
% docker pull alpine
% # wait a while
% dd if=/dev/zero of=/waste_space.bin bs=1G count=20
% # now wait for image_gc_manager to trigger
% docker images | grep alpine # missing, assuming you have no pods with alpine
```

**Environment**:
- Kubernetes version (use `kubectl version`): `1.7.7` (but the code still exists in `master`)
- Cloud provider or hardware configuration: SUSE CaaS Platform 2
- OS (e.g. from /etc/os-release): SUSE CaaS Platform 2

**Comment by cyphar** [comment]
There are two solutions I would propose.

1. When pulling images, we store the set of images that were pulled by kubelet (in a `FileStore`). When we GC, we do not consider images that were not pulled by kubelet. When an image is removed we remove it from the `FileStore`. This is a CRI-agnostic implementation which requires limited on-disk storage for the set of images pulled by us. One potential issue is that `FileStore.List` may be inatomic based on how `readdir(2)` works, which could result in us missing images that were added recently. But because of the `GC` semantics this shouldn't be an issue.

2. We change the semantics of the CRI API's `ListImages` gRPC call. The idea would be that runtimes would only return images that were fetched by the `PullImage` API. This is a similar idea to (1) except the burden is now on CRI implementations (though I believe only `docker` and possible `rkt` would really care about this since `containerd` has namespaces and `cri-o` is single-purpose). The nice thing about this is that it the runtime could store this information in whatever form it likes (for example it could be stored inside the image with labels, or by having a separate store for k8s) and it would also make all of the code in Kubernetes that uses `ListImages` act consistently in the case of unknown images. The downside is that it could result in a pointless pull request to a runtime for an image that already exists (but this could be seen as just promoting the status of the image to being "wanted" by the kubelet).

Are either of these solutions favourable?

**Comment by inercia** [comment]
In my view, solution 1) could lead to some inconsistencies between the runtime storage and the FileStore. What if an image is removed in the docker storage? Is it going to be notified to the `kubelet`?

**Comment by cyphar** [comment]
This issue is still applicable.

/remove-lifecycle stale
