### ISSUE TITLE
scheduler cache error messages do not read well

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#57152]
/kind bug

There are several error messages in the scheduler cache that are confusing to read, at least one of these surfaced up to end users via Events. I noticed these two in particular but there may be others:

`pod %v state wasn't initial but get assumed`
`pod %v state wasn't assumed but get forgotten`

Whether or not these should actually be surfacing as events, the messages should be cleaned up.

**Comment by jwforres** [comment]
cc @aveshagarwal

**Comment by jwforres** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by guangxuli** [comment]
Seems that these are internal or implement details in scheduler, do our end users can fully understand what the events really mean?  I think it is depend on our own implement.
@aveshagarwal  idea?

**Comment by ravisantoshgudimetla** [comment]
I believe, the problem is with `%v` in the message but I am not able to reproduce it, @jwforres, can you please share steps to reproduce this.

**Comment by jwforres** [comment]
No unfortunately, one of our users reported seeing it when there system was in a bad state, not in a reproducible way. The point of the issue is just that the grammar in those messages is bad, which should be fixable even if you can't get them to fire.
