### ISSUE TITLE
ConfigMap data key-naming shouldn't be limited to DNS-naming only

### ISSUE THREAD

**Issue by RobertDiebels** [kubernetes/kubernetes#57158]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I tried creating a ConfigMap from a file. The file's name does not meet the validation specifications for a ConfigMap data key. This causes kubectl to forgo creating the ConfigMap.

**What you expected to happen**:
I expect that the ConfigMap is created regardless of which characters occur in the file-name. Reasoning behind this is that a ConfigMap can be mounted as a volume. All keys in the ConfigMap's data option are then mapped as file-names into the volume. I would expect file-names to be valid keys. Or an option to specify the file name if I mount the configMap as a volume.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a file and place a '@' in its name.
- Use `kubectl create configmap name --from-file <insert filepath>` to create a ConfigMap

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.7.0`
- Cloud provider or hardware configuration: `minikube`
- OS (e.g. from /etc/os-release): `Windows 10`
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

**Comment by liggitt** [comment]
You can specify the key to place the file content into when creating the config map 

You can also specify in the volume mount what path to place which key into with the projected volume type

**Comment by RobertDiebels** [comment]
@liggitt "You can specify the key to place the file content into when creating the config map"
Correct but the key format is limited. From the [reference](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#configmap-v1-core): 
Data contains the configuration data. Each key must consist of alphanumeric characters, '-', '_' or '.'.

So I can't create a ConfigMap from a file with a '@' in it. Even-though this is a valid file-name.

"You can also specify in the volume mount what path to place which key into with the projected volume type"
This works! Thanks for pointing that out!

Consider the issue resolved. I'm still interested in why the data keys are limited like this. I don't think yaml has a limitation on key-naming. I'm not that familiar with yaml however.

**Comment by liggitt** [comment]
correct, the data keys were limited to safe cross platform filenames and envvar names
