### ISSUE TITLE
v1.9.0 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/kubernetes#57159]
/kind bug

Please link to this issue or comment on this issue with known errata for the 1.9.x release. This follows what we have done for prior releases.
We will be populating the "Known Issues" section of 1.9.0 and above release notes based on this issue

FYI @enisoc @nickchase @Bradamant3  
cc/ @kubernetes/kubernetes-release-managers

**Comment by enisoc** [comment]
Some things that previously were in the milestone but were punted to 1.9.1:

* Continuous polling of webhook admission registration objects #56357
* Introduce buffer to audit log output #53006
* CRD is stuck with "orphan" finalizer #56348
* apiserver timeouts after rolling-update of etcd cluster #47131

**Comment by crassirostris** [comment]
Audit logging buffering will probably be pushed back until the next minor release. It's too big to go into the patch release IMO

**Comment by enisoc** [comment]
I think we are also punting this to 1.9.1:

https://github.com/kubernetes/kubernetes/issues/54940

**Comment by luxas** [comment]
Should we still keep this open?

**Comment by hamzaabi** [comment]
is the issue fixed, if yes please tell me how?
