### ISSUE TITLE
kube-controller constantly running into garbage collection for non-existing resources

### ISSUE THREAD

**Issue by nydalal** [kubernetes/kubernetes#57166]
k8s version - 1.5.2

kube-controller constantly running into garbage collection for non-existing resources. It prevents deployment of new pods in cluster and all pods remain in "Pending" state.

pod and node throws error about Affinity, which is also mis-leading.
Warning FailedScheduling {default-scheduler } pod (kube-state-metrics-2632609649-9qbk0) failed to fit in any node

E1213 19:52:59.140993 7 garbagecollector.go:593] Error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:metatypes.OwnerReference{APIVersion:"v1", Kind:"Pod", UID:"d934203c-d686-11e7-a2d6-06a07ccc906e", Name:"heimdall-2390169327-xmdr2", Controller:(*bool)(nil)}, Namespace:"jenkins-vrbc-turnkey-test-kr-82"}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, owners:[]metatypes.OwnerReference{metatypes.OwnerReference{APIVersion:"extensions/v1beta1", Kind:"ReplicaSet", UID:"d93293cb-d686-11e7-a2d6-06a07ccc906e", Name:"heimdall-2390169327", Controller:(*bool)(0xc422389608)}}}: namespaces "jenkins-vrbc-turnkey-test-kr-82" not found
I1213 19:52:59.191372 7 garbagecollector.go:761] none of object [v1/Pod, namespace: jenkins-vrbc-turnkey-test-kr-82, name: heimdall-2390169327-xmdr2, uid: d934203c-d686-11e7-a2d6-06a07ccc906e]'s owners exist any more, will garbage collect it
E1213 19:52:59.241081 7 garbagecollector.go:593] Error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:metatypes.OwnerReference{APIVersion:"v1", Kind:"Pod", UID:"d934203c-d686-11e7-a2d6-06a07ccc906e", Name:"heimdall-2390169327-xmdr2", Controller:(*bool)(nil)}, Namespace:"jenkins-vrbc-turnkey-test-kr-82"}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{}, owners:[]metatypes.OwnerReference{metatypes.OwnerReference{APIVersion:"extensions/v1beta1", Kind:"ReplicaSet", UID:"d93293cb-d686-11e7-a2d6-06a07ccc906e", Name:"heimdall-2390169327", Controller:(*bool)(0xc422389608)}}}: namespaces "jenkins-vrbc-turnkey-test-kr-82" not found
I1213 19:52:59.291332 7 garbagecollector.go:761] none of object [v1/Pod, namespace: jenkins-vrbc-turnkey-test-kr-82, name: heimdall-2390169327-xmdr2, uid: d934203c-d686-11e7-a2d6-06a07ccc906e]'s owners exist any more, will garbage collect it

**Comment by yliaog** [comment]
do you still see the same issues when upgrading to the latest version 1.9?

as documented in https://kubernetes.io/docs/home/, "Kubernetes is supported for three minor versions at a time. This includes the current release version and two previous versions"
