### ISSUE TITLE
Support online file system resize for PVs

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#57185]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

In current implement, we only support offline file system resize for PVs in kubelet, as this operation is executed by the `MountVolume` operation. If a resize request was submitted after the volume mounted, it won't be resized.

**What you expected to happen**:

Support online file system resize for PVs.

**Anything else we need to know?**:

I think the key point is how kubelet to discover volumes need resize operation. If kubelet just watch all PVCs, it will receive the whole PVCs in the cluster, including ones not attached to this node, so this approach maybe increase the pressure of apiserver/etcd as the scale of the cluster increases(in other words, more kbuelets in cluster).

A feasible solution maybe:

1. Add a label  `expandable-volume-mounted-{nodeName}=yes` or something like this to PVC, indicated that this PVC has been mounted to `{nodeName}`, we can do this after the mount operation succeeded, and remove it after the umount operation finished. Thus the kubelet can only watch PVCs mounted to itself. For better performance, we can add this label only for expandable volumes. Of course, we need a `reconciler` to promise this label.
2. Kubelet watches all PVCs mounted to itself with a label selector, and checks whether the PVC in `Resizing` state or not. If so, puts a `VolumeToResize` object, or something like this, to the cache.
3. Add an resize operation to the `VolumeManager`'s `reconcile` go routine, follows the attach/mount operation. This resize operation will processes all `VolumeToResize` objects. Of course, we need to check whether the volume exactly mounted in the `ActualStateOfWorld`.
4. Maybe we need to add a `OnlineResizeSupported` method for the volume plugin, used to check whether the volume type and file system supports online resize or not.

Do we have any plan for this feature? If not, can I submit a more detailed proposal for this?

**Comment by gnufied** [comment]
Rather than watching for PVCs, a kubelet can watch for pods that are running on it and we can add a annotation to pod that volume it is using requires a resize. This is just a rough idea though because all nodes watching for all PVCs will put considerable strain on etcd and I am not sure I like that very much.

**Comment by mlmhl** [comment]
Thanks @gnufied , it exactly will put considerable strain on `etcd` if all nodes watching for all PVCs, so in my proposal I add a label `expandable-volume-mounted` for the PVC, and this label will be added only if PVC received a resize request and the `RequiresFSResize` of according volume plugin return true. If these prerequisites are set up, we set this label to the `nodeName` of the node which the PVC mounted to, and kubelet can only watch those PVCs with this label set to its own node name. This approach may reduce the pressure on `etcd`.

Through deep thinking, your proposal maybe a better one as kubelet needn't to watch any PVCs. But I have a few questions:

1. Where to add this annotation for pod? `operationGenerator.GenerateExpandVolumeFunc` maybe a candidate, we can add annotations to pod if `RequiresFSResize` returns true, but the `ExpandController` need to share the `DesiredStateOfWorld` with `AttachDetachController`, and add a `GetPodsInVolume`(or something like this) method, in order to find which pod is using this PVC.
2. Where to remove this annotation for pod? Maybe we can remove this annotation inside `operationGenerator.resizeFileSystem`, just after the resize operation succeeded.
3. If a PVC is used by multi pods, need we to add annotation for each pod? If so, it maybe increase some pressure on etcd. Or we can just select one pod to add this annotation.
4. As a pod can use multi PVCs and these PVCs can be resized concurrently, so the annotation's template may be `pvc-resizing-{pvcName}=true` or `pvc-resizing-{pvcName}={requestSize}` to distinguish between different PVCs.

Have you already started this work? If not, can I do it?

**Comment by gnufied** [comment]
@mlmhl no I have not started work on online file system resizing yet. Feel free to open a proposal for 1.10. I will be happy to review and move along as best as I can.

Regarding - adding annotation to pod:

The resize controller has to obviously check if pvc is being used in a pod, so it does get tricky pretty fast.  I think adding label to pvc works too, but the problem is - labels can be edited by users and hence we should be careful about adding a label on which critical functionality depends on.

**Comment by mlmhl** [comment]
Thanks @gnufied , I've already started this job and will open a proposal for 1.10 as soon as possible.

**Comment by mlmhl** [comment]
Hi @gnufied , I've submit a proposal for this feature: [kubernetes/community#1535](https://github.com/kubernetes/community/pull/1535), look forward to your review.

**Comment by gnufied** [comment]
We are planning to tackle this problem in 1.11

/remove-lifecycle stale

**Comment by gnufied** [comment]
We will consider this as done for now. we will move all of online expansion GA along with rest of volume expansion.

/close
