### ISSUE TITLE
Elevated kube-apiserver memory usage caused 100-node test failure

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#57182]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-api-machinery-bugs 
@kubernetes/sig-scalability-bugs 
umbrella issue: https://github.com/kubernetes/kubernetes/issues/56062
/priority failing-test

**What happened**:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8937 failed with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135
Expected error:
    <*errors.errorString | 0xc42ca80e60>: {
        s: "Container kube-apiserver-e2e-scalability-master/kube-apiserver is using 1515.359375/1500 MB of memory",
    }
    Container kube-apiserver-e2e-scalability-master/kube-apiserver is using 1515.359375/1500 MB of memory
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:366
```

See graph:
![gprhyounud8](https://user-images.githubusercontent.com/489420/33978653-161f4ccc-e0a1-11e7-81bf-d4844776fb99.png)

This is similar to https://github.com/kubernetes/kubernetes/issues/56061
Because of https://github.com/kubernetes/kubernetes/issues/56340 it's hard to see exactly where this started.

**Comment by yliaog** [comment]
please provide heap dump from pprof

**Comment by porridge** [comment]
@yliaog how do I do that post-facto? Doesn't this require launching kube-apiserver with profiling enabled for the whole duration of the test?

**Comment by yliaog** [comment]
yes, it would require profiling enabled during the test

**Comment by porridge** [comment]
Another occurence:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/9171

**Comment by porridge** [comment]
I'm not sure this will be easy to reproduce, given it's not so frequent, but I will take a stab at it.
