### ISSUE TITLE
Secure etcd API /w TLS on kubeadm init

### ISSUE THREAD

**Issue by stealthybox** [kubernetes/kubernetes#57184]
/kind feature
/area etcd
/area kubeadm
/area security
/sig cluster-lifecycle

**What happened**:
When initializing a cluster with kubeadm, the local connection to etcd is insecure.
Anyone logged into the master machine has implicit root access via the etcd port.

**What you expected to happen**:
kubeadm should generate TLS identities for etcd.
The connection should be secure -- unaccessible without valid credentials.

**Anything else we need to know?**:
This was discussed in in the kubeadm working group: [Wed 13 December 2017](https://docs.google.com/document/d/16CEsBSSGm3sMpvB_cFnKnqqi1OxhIcyX3lVwBpIyMHc/edit#heading=h.6bl6aiqaw2a).

**Functionality**:
- Generate Server and Peer cert for etcd
- Generate Client cert for apiserver
- Add flags / hostMounts for etcd static pod
- Add flags / hostMounts for apiserver static pod
- During the upgrade case from 1.9 → 1.10, generate the new certs

**Considerations**:
Shoud we use the existing kubernetes CA or create a dedicated etcd CA ?
- Start /w kubernetes CA for simplicity

**Comment by roberthbailey** [comment]
Leigh -- can you open this issue in https://github.com/kubernetes/kubeadm instead of here? (we are using that repo to track kubeadm issues / features, even though the code is still in the main repo)

**Comment by stealthybox** [comment]
Moved to https://github.com/kubernetes/kubeadm/issues/594

**Comment by roberthbailey** [comment]
thanks!
