### ISSUE TITLE
group version `apiextensions.k8s.io/v1beta1` that has not been registered

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#57189]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig apps

**What happened**:
When running with `runtime-config=apiextensions.k8s.io/v1beta1`, apiserver will failed with
> error in initializing storage factory: group version apiextensions.k8s.io/v1beta1 that has not been registered

It is quite misleading. Since currently `apiextensions.k8s.io/v1beta1` is being enabled by default even without setting `runtime-config=apiextensions.k8s.io/v1beta1`.

The root cause is that `apiextensions.k8s.io/v1beta1` has not been registered to `legacyscheme.Registry`. To solve this, `apiextensions.k8s.io/v1beta1` has to be initialized as known groupVersions.

A regular way to mitigate this is to promote the gvk registration/install to `pkg/apis`, like other apis/objects currently. @janetkuo @sttts WDYT?

/cc @kubernetes/sig-apps-bugs 

**What you expected to happen**:
No such error.

**How to reproduce it (as minimally and precisely as possible)**:
Start apiserver with `runtime-config=apiextensions.k8s.io/v1beta1`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sttts** [comment]
> A regular way to mitigate this is to promote the gvk registration/install to pkg/apis, like other apis/objects currently. @janetkuo @sttts WDYT?

I understand the pain and inconcistency of `--runtime-config`. But we certainly don't want to mix apiextensions code with the main kube-apiserver code. Instead, we need some better logic to distribute the options of `--runtime-config` to the delegated API server it belongs to.

**Comment by sttts** [comment]
Spontaneous thoughts: kube-apiserver is actually a delegation chain of aggregator+kube+apiextensions. Let's pass down runtime-config through the chain, each layer removing the groups it knows about.

**Comment by hzxuzhonghu** [comment]
/assign
We will fix it.

**Comment by hzxuzhonghu** [comment]
@dixudx  I just notified  has a pr, Would you still want to do this?

**Comment by dixudx** [comment]
@hzxuzhonghu No, you go ahead. Currently I don't have too much bandwith on this.
Just as @sttts commented the legacyschema is legacy. That pr is not on the right track.

I would like to have a review when you've got a PR for this. Thanks for your help.

**Comment by hzxuzhonghu** [comment]
ok

**Comment by zhangbei59** [comment]
I have the same pro ,help me !

**Comment by hzxuzhonghu** [comment]
The pr #57228 can solve this.

**Comment by zhangbei59** [comment]
sorry ,my pro is #57925,not same as this!
