### ISSUE TITLE
Pod instance should not reboot if the current node meets the new applied node affinity rule

### ISSUE THREAD

**Issue by vinsonxing** [kubernetes/kubernetes#57181]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

I have a running pod (pod-1), deployed via a k8s deployment (deploy-1), on k8s node-1. Someday, I want to patch node affinity to this deployment (kubectl patch ). For example, the target node must have label 'data=allowed'.
My steps:
1.  Add label 'data=allowed' to node-1 first
2. Patch the node affinity definition to deploy-1

The pod-1 is rebooted after the patch, even the current node where pod-1 is on has meet the node affinity rule (Step 1).

**What you expected to happen**:
My expectation is that the pod-1 should not be rescheduled by k8s, since it is already on node-1.
Or provide a configuration to prevent rebooting. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vinsonxing** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by k82cn** [comment]
I'd like to add sig-arch for a broader discussion about this feature. Currently, controllers manage pod's lifecycle, and scheduler handles resource assignment (except DS); if want to handle such case, controller may delegate some lifecycle handler to scheduler, e.g. eviction, or involves some scheduler's policy check in controllers. That's case definitely need more discussion :).

/cc @bgrant0607 @davidopp @timothysc @bsalamat

**Comment by bgrant0607** [comment]
I understand why someone would want this, but it's not so easy.

1. Controllers don't update pods in place -- see #9043. They create new ones, sometimes indirectly, as with Deployment, which creates new ReplicaSets when the pod template changes.
2. Pods are largely immutable, so the controllers can't modify them even if they were smart enough to.
3. Controllers don't reason about scheduling constraints, as @k82cn mentioned. However, there are other reasons why they might -- see #4301 and #41394.

**Comment by bgrant0607** [comment]
Noted in #9043
