### ISSUE TITLE
Misleading kubectl error: the server doesn't have a resource type "po"

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#57198]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When using kubectl 1.9.0-beta.1+, if you run `kubectl get po`, while the API server is unreachable, you get the following misleading error: `the server doesn't have a resource type "po"`.

**What you expected to happen**:
In versions 1.9.0-alpha.3 and lower, you get the proper error: `The connection to the server 127.0.0.1:1 was refused`.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ curl -sL https://storage.googleapis.com/kubernetes-release/release/v1.9.0-beta.1/bin/linux/amd64/kubectl -o /tmp/kubectl \
&& chmod +x /tmp/kubectl \
&& /tmp/kubectl -s http://127.0.0.1:1 get po 
the server doesn't have a resource type "po"
```

If you try the same command with kubectl *1.9.0-alpha.3*, you get the correct error message:
```
$ curl -sL https://storage.googleapis.com/kubernetes-release/release/v1.9.0-alpha.3/bin/linux/amd64/kubectl -o /tmp/kubectl \
&& chmod +x /tmp/kubectl \
&& /tmp/kubectl -s http://127.0.0.1:1 get po 
The connection to the server 127.0.0.1:1 was refused - did you specify the right host or port?
```
You also get the same error message in kubectl *1.9.0-beta.1*, if you use the *full resource name* instead of the abbreviation:
```
$ curl -sL https://storage.googleapis.com/kubernetes-release/release/v1.9.0-beta.1/bin/linux/amd64/kubectl -o /tmp/kubectl \
&& chmod +x /tmp/kubectl \
&& /tmp/kubectl -s http://127.0.0.1:1 get pod
The connection to the server 127.0.0.1:1 was refused - did you specify the right host or port?
```

**Anything else we need to know?**:
This is a regression between 1.9.0-alpha.3 and 1.9.0-beta.1

/sig cli

**Comment by luksa** [comment]
/sig release

https://github.com/kubernetes/kubernetes/issues/57159

**Comment by niuzhenguo** [comment]
I can reproduce this when cached discovery expired when API server unreachable.

**Comment by niuzhenguo** [comment]
And this happend because we changed to fallback to hardcoded types when there's err. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_object_mapping.go#L93-L94
I can add a PR to check "connection refused" err and not fallback in this case.

**Comment by Ghazgkull** [comment]
This is still an issue in kubectl v1.11.2

**Comment by luksa** [comment]
Hmm, @michidk are you sure? I've just tried it with v1.12.1 and can't reproduce it anymore. Can you provide steps to reproduce the error?

**Comment by michidk** [comment]
Not sure if this is a different issue, but I tried it with `kubectl get pod`
After wasting time debugging because I thought kubectl was already connected to that node but some resource didn't exist, I found this thread and looked into things that could prevent the kubectl from connection to the cluster. I then completely reconfigured kubectl.
Sadly I can't reproduce it right now, because I don't know what was wrong before.

**Comment by luksa** [comment]
ok, then I'll re-close this.

**Comment by cbrunnkvist** [comment]
I can reproduce this and yes the error is/was quite misleading (especially when the error was not happening on my machine but in a CI environment):

*kubectl v1.13.5*:
```
cbrunnkvist@hostname:~$ KUBECONFIG=~/.kube/known-problematic.config kubectl.old version
error: You must be logged in to the server (the server has asked for the client to provide credentials)
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
cbrunnkvist@hostname:~$ KUBECONFIG=~/.kube/known-problematic.config kubectl.old get pods
error: the server doesn't have a resource type "pods"
```

*kubectl v1.16.6-beta.0*:
```
cbrunnkvist@hostname:~$ KUBECONFIG=~/.kube/known-problematic.config kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
cbrunnkvist@hostname:~$ KUBECONFIG=~/.kube/known-problematic.config kubectl get pods
error: You must be logged in to the server (Unauthorized)
```
