### ISSUE TITLE
Query free resources (specially number of GPUs) on nodes

### ISSUE THREAD

**Issue by definitelyuncertain** [kubernetes/kubernetes#57193]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

/sig api-machinery

Currently, `kubectl describe node` only shows CPU and memory usage pod-wise on the node. What would be great is if, for each resource the amount remaining that can be allocated is shown, including the number of GPUs remaining.

Perhaps a new section could be added to the output as follows:

```
Free:
 alpha.kubernetes.io/nvidia-gpu:  1
 cpu:                             3
 memory:                      5000000Ki
 pods:                            103
```

**Comment by pineking** [comment]
see https://github.com/kubernetes/kubernetes/pull/57146

**Comment by definitelyuncertain** [comment]
While the work in that PR is certainly necessary for the GPU part, there is still no way to check how much is left except by manually adding up each pod's consumption subtracting from the total allocatable. My request is for a feature that does exactly this and prints the summary.

**Comment by jianzhangbjz** [comment]
@definitelyuncertain Maybe this #46079 could meet your request.
