### ISSUE TITLE
sample-controller errors when starting:  Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by G-Harmon** [kubernetes/kubernetes#57205]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report
/kind bug

**What happened**:
I'm following the directions to run the sample controller on https://github.com/kubernetes/sample-controller
When running it as directed, it gives these errors:
$ go run *.go -kubeconfig=$HOME/.kube/config
E1214 10:34:25.188240  177579 reflector.go:205] k8s.io/sample-controller/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"
E1214 10:34:26.188769  177579 reflector.go:205] k8s.io/sample-controller/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1alpha1.Foo: v1.ListOptions is not suitable for converting to "samplecontroller.k8s.io/v1alpha1"

**What you expected to happen**:
Not to generate these errors.

**How to reproduce it (as minimally and precisely as possible)**:
1) Have a working kube config.
2) checkout kubernetes/sample-controller
3) run it: ~/go/src/k8s.io/sample-controller$ go run *.go -kubeconfig=$HOME/.kube/config

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.845+542486186fd684-dirty", GitCommit:"542486186fd684db939098ffadeb1aa5dcd63498", GitTreeState:"dirty", BuildDate:"2017-10-02T22:37:04Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GKE
- OS (e.g. from /etc/os-release):
my workstation is 14.04.5 LTS, Trusty Tahr
- Kernel (e.g. `uname -a`):
my workstation kernel is 4.4.0-96-generic
- Install tools:
- Others:
go version 1.9

**Comment by G-Harmon** [comment]
cc @munnerz - Hi, it looks like you checked this in with #52753.  What all do I need to do to get this to work?
@smarterclayton

**Comment by munnerz** [comment]
Hey - thanks for this report. I'm not sure how, but we were missing an extra line in register.go. I've put in #57243 to resolve this (and it's working for me now :tada:)
