### ISSUE TITLE
LimitRange can block pod termination

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#57201]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
https://bugzilla.redhat.com/show_bug.cgi?id=1509309

A LimitRange added to a namespace after it has pods can prevent terminating pods from being deleted if they do not conform to the min/max criteria.

**What you expected to happen**:
LimitRange should ignore pods that are marked for deletion as they really cannot change their resource requirements.

**Comment by jennybuckley** [comment]
cc @cheftako
