### ISSUE TITLE
Issue: container won't set Request resources (CPU & RAM) properly

### ISSUE THREAD

**Issue by mkotsollaris** [kubernetes/kubernetes#57203]
> /kind bug

I am trying to set a fixed resource value to my kubernetes container. When I try the following:
```
//var k8sJobSpec v1batch.Job
//cont = &k8sJobSpec.Spec.Template.Spec.Containers[0]
log.Println("Before", cont.Resources.Requests.Memory())
cont.Resources.Requests.Memory().SetMilli(512) //new wanted value
log.Println("After", cont.Resources.Requests.Memory())
log.Println("Before", cont.Resources.Requests.Cpu())
cont.Resources.Requests.Cpu().SetScaled(2, resource.Giga) //new wanted value
log.Println("After", cont.Resources.Requests.Cpu())
```
I get:
```
Before 0
After 0
Before 0
After 0
```
Not sure if this is a bug or (most likely) I am doing something wrong. Why doesn't Set update my values to the newer ones? How can I set the CPU & RAM resources properly? 

@kubernetes/sig-contributor-experience/bugs

**Comment by dims** [comment]
@mkotsollaris take a look at https://github.com/dims/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/resource.go#L36-L42 When it is not originally set in the Requests (it's a ResourceList), one cannot set the new value in the data structure returned by Memory()

Something like this should work: (https://github.com/dims/kubernetes/blob/master/test/e2e/scheduling/preemption.go#L86)
cont.Resources.Requests[v1.ResourceMemory] = resource.NewQuantity(int64(512), resource.BinarySI) 

Same for the Cpu() as well

**Comment by mkotsollaris** [comment]
Thank you. That worked with a small modification since you need to `make` the map prior adding the `KV`:
```
cont.Resources.Requests = make(map[v1core.ResourceName]resource.Quantity)
cont.Resources.Requests[v1core.ResourceMemory] = *resource.NewQuantity(int64(manifest.Template.Resources.RamGB), resource.BinarySI)
cont.Resources.Requests[v1core.ResourceCPU] = *resource.NewQuantity(int64(manifest.Template.Resources.CpuCores), resource.BinarySI)
```
Adding it here in case someone needs it in the future. 

Cheers!

**Comment by mkotsollaris** [comment]
@dims May I ask if you are aware on how can I have a Quantity of different types each time (e..g, KB, MB, TB etc)? For instance, I want to have something like this: 
````
cont.Resources.Requests[v1core.ResourceMemory]="100GB"
cont.Resources.Requests[v1core.ResourceCPU]="200KiB"
```

How could I translate Quantity into these values?

**Comment by dims** [comment]
@mkotsollaris i believe you can use `MustParse` and/or `ParseQuantity` from quantity module:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L134
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L276

**Comment by mkotsollaris** [comment]
Thanks, `NewQuantity` works too!
