### ISSUE TITLE
API support for identifying application types

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#5721]
For logging and monitoring purposes identifying application types (mysql, jvm, etc)  is necessary. Monitoring and logging agents are built to handle different application types natively. 
Possible approaches:
- Labels - Declare some well known label keys that can be used to identify applications.
- Extend the API to include optional per-container application types
- Use API [plugins](https://github.com/GoogleCloudPlatform/kubernetes/issues/991)

cc @satnam6502 @bgrant0607

**Comment by bgrant0607** [comment]
Labels are not an option. They aren't for carrying semantic information between components.

Use annotations for now. We can decide whether to extend the API later, after we get more experience.

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
@bparees we probably want to decorate our image streams, rcs, builds, services, and etc with this as we go.  Especially generation.  Defining a convention will help various aspects (we should also get the label metadata work atomic has done integrated as wel).

**Comment by bparees** [comment]
we're already decorating image streams based on info we pull from the docker image, @ncdc did that work so the console can consume them.    pushing that info down to builds/services/etc constructed from those image streams makes sense.

**Comment by vishh** [comment]
cc @dchen1107 @munangst

**Comment by smarterclayton** [comment]
xref #6573

----- Original Message -----

**Comment by bgrant0607** [comment]
cc @saad-ali

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by mattfarina** [comment]
/remove-lifecycle stale

This is relevant to the app def working group discussions on labels and annotations.

**Comment by bgrant0607** [comment]
cc @kow3ns

**Comment by bgrant0607** [comment]
This is being covered by things like the Application API, workload-specific controllers, etc.
