### ISSUE TITLE
add support for specifying namespace when using `gcloud container clusters get-credentials` command

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#57237]
/kind feature

`gcloud container clusters get-credentials _clusterName_ --namespace=_namespaceName_ --name=_contextName_` should write the context to `KUBECONFIG` instead of having to manually edit the KUBECONFIG file in order to create a context tied with a particular namespace.

**Comment by pinnacle-hk** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by mengqiy** [comment]
@ghost Please file a bug to gcloud if you haven't done so. Here is not the right place for it.
