### ISSUE TITLE
Nodes kill all containers when no connectivity to master

### ISSUE THREAD

**Issue by vasili439** [kubernetes/kubernetes#57236]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature
/sig node

**What happened**:
We have master node inside AWS and some nodes on bare metal inside 3rd party datacenter. Connection between DC and AWS built over Internet so it could be not so stable. When there is a connection outage for 3-5 minutes node leaves cluster (i.e. I can't see it with kubectl get nodes). After that housekeeping removes all pods from the remote node (with kube-proxy) and I see only:

```
root@vl1-35:~# docker ps              
CONTAINER ID        IMAGE                                                                                     COMMAND                  CREATED             STATUS              PORTS               NAMES
25057c0f3d6d        google/cadvisor@sha256:09c8d73c9b799d30777763b7029cfd8624b8a1bd33af652ec3b51a6b827d492a   "/usr/bin/cadvisor..."   6 days ago          Up 6 days                               k8s_cadvisor_cadvisor-vl1-35.itcapital.io_default_ed250e3dd1b5a27ab9af53a977c969a4_1
db161dd60898        gcr.io/google_containers/pause-amd64:3.0                                                  "/pause"                 6 days ago          Up 6 days                               k8s_POD_cadvisor-vl1-35.itcapital.io_default_ed250e3dd1b5a27ab9af53a977c969a4_2

```
When connection is restored kubelet cannot register node on master:
```
Dec 15 07:56:55 vl1-35 kubelet[32590]: E1215 07:56:55.194569   32590 kubelet_node_status.go:386] Error updating node status, will retry: error getting node "vl1-35.itcapital.io": nodes "vl1-35.itcapital.io" not found
Dec 15 07:56:55 vl1-35 kubelet[32590]: E1215 07:56:55.251218   32590 kubelet_node_status.go:386] Error updating node status, will retry: error getting node "vl1-35.itcapital.io": nodes "vl1-35.itcapital.io" not found

``` 

Issue can be fixed with "systemctl restart kubelet" and put all labels back to my new-old node once again (kubelet label node ....)

**What you expected to happen**:
Continue normal operation when connectivity will be restored

**How to reproduce it (as minimally and precisely as possible)**:
Apply on master node:
iptables -I INPUT 1 -p tcp -s "node ip"/32 --dport "api server port" -j DROP
and wait for 3-5 minutes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
aws + bare metal
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
Linux ip-172-28-68-60 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Others:

**Comment by errordeveloper** [comment]
I sound like your cluster spans multiple DCs, and I don't believe this is was supported. Have you considered setting up separate control planes for each DC and using something to reconcile your configuration? You could use multi-cluster aka federation, but there are simpler ways to ensure your deployments are in sync.
It is known that some folks wish to do something similar to enable bursting to public cloud on demand, but that's hard to achieve as Kubernetes had been designed with single DC use-case in mind (i.e. low level latency, no split-brain). If you need a burst capability, you can do that with zero-node clusters that autoscale on demand.
Happy to provide some more ideas, if you want to chat on Slack... However, I don't think this is a bug.

/ping @jbeda @thockin @brendanburns
