### ISSUE TITLE
undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions

### ISSUE THREAD

**Issue by zmmwl** [kubernetes/kubernetes#57234]
I got below error when I was trying to compile kube-apiserver(release-1.7 branch) using goland UI tool :
src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:380: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions

It's true that GetOpenAPIDefinitions is missing in package "k8s.io/kubernetes/pkg/generated/openapi" but the strange thing is that I can build it successfully in command line using make. 

Could anyone tell me if it's an issue? Thanks!

**Comment by dixudx** [comment]
@zmmwl This is not a bug. This file will be auto-generated when building.

Please run `make kube-apiserver` to build your `kube-apiserver` binary.

**Comment by zmmwl** [comment]
@dixudx thanks!
