### ISSUE TITLE
Enhance event message for scheduler

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#57244]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

If there are some scheduler errors when I create some pods, I will get some event message as following:

```
No nodes are available that match all of the following predicates:: MatchNodeSelector (2), NodeUnderDiskPressure (1).
```

People often ask me what does `(2)` and `(1)` means in this message, so my proposal is enhance the message a bit as following:

```
No nodes are available that match all of the following predicates:: MatchNodeSelector (2 nodes failed), NodeUnderDiskPressure (1 node failed).
```

/cc @kubernetes/sig-scheduling-bugs 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@gyliu513 dup of #52166.
Already fixed in #52515.
/close

**Comment by gyliu513** [comment]
Thanks @dixudx I think the fix of #52515 is not good enough, as it can work well with error message started with `Node`, such as `2 NodeUnderMemoryPressure`, `1 NodeUnderDiskPressure`, but there are different error messages as here https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/error.go#L33-L54

```
        ErrDiskConflict                          = newPredicateFailureError("NoDiskConflict")
	ErrVolumeZoneConflict                    = newPredicateFailureError("NoVolumeZoneConflict")
	ErrNodeSelectorNotMatch                  = newPredicateFailureError("MatchNodeSelector")
	ErrPodAffinityNotMatch                   = newPredicateFailureError("MatchInterPodAffinity")
	ErrPodAffinityRulesNotMatch              = newPredicateFailureError("PodAffinityRulesNotMatch")
	ErrPodAntiAffinityRulesNotMatch          = newPredicateFailureError("PodAntiAffinityRulesNotMatch")
	ErrExistingPodsAntiAffinityRulesNotMatch = newPredicateFailureError("ExistingPodsAntiAffinityRulesNotMatch")
	ErrTaintsTolerationsNotMatch             = newPredicateFailureError("PodToleratesNodeTaints")
	ErrPodNotMatchHostName                   = newPredicateFailureError("HostName")
	ErrPodNotFitsHostPorts                   = newPredicateFailureError("PodFitsHostPorts")
	ErrNodeLabelPresenceViolated             = newPredicateFailureError("CheckNodeLabelPresence")
	ErrServiceAffinityViolated               = newPredicateFailureError("CheckServiceAffinity")
	ErrMaxVolumeCountExceeded                = newPredicateFailureError("MaxVolumeCount")
	ErrNodeUnderMemoryPressure               = newPredicateFailureError("NodeUnderMemoryPressure")
	ErrNodeUnderDiskPressure                 = newPredicateFailureError("NodeUnderDiskPressure")
	ErrNodeOutOfDisk                         = newPredicateFailureError("NodeOutOfDisk")
	ErrNodeNotReady                          = newPredicateFailureError("NodeNotReady")
	ErrNodeNetworkUnavailable                = newPredicateFailureError("NodeNetworkUnavailable")
	ErrNodeUnschedulable                     = newPredicateFailureError("NodeUnschedulable")
	ErrNodeUnknownCondition                  = newPredicateFailureError("NodeUnknownCondition")
	ErrVolumeNodeConflict                    = newPredicateFailureError("VolumeNodeAffinityConflict")
	ErrVolumeBindConflict                    = newPredicateFailureError("VolumeBindingNoMatch")
```

Customer will be confused if they got message `2 PodAntiAffinityRulesNotMatch`, does it means 2 pods failed or 2 nodes failed?

So I still prefer the original message but enhance it a bit as I proposed `MatchNodeSelector (2 nodes failed)`, comments?

**Comment by gyliu513** [comment]
@dixudx  seems I cannot open this, any comments for the above comments?

**Comment by dixudx** [comment]
> Customer will be confused if they got message 2 PodAntiAffinityRulesNotMatch, does it means 2 pods failed or 2 nodes failed?

> So I still prefer the original message but enhance it a bit as I proposed MatchNodeSelector (2 nodes failed)

@gyliu513 Reasonable. Most users may not get familiar with these selectors/predications. 

After the change, the message may look like,

```
0/2 nodes are available:: MatchNodeSelector (2 nodes not matched), NodeUnderDiskPressure (1 node not matched).
```

**Comment by k82cn** [comment]
How about add description of those reasons, e.g. predicate (number of failed nodes) after `... the following predicates:`

**Comment by gyliu513** [comment]
+1 to @dixudx 's proposal, thanks!

**Comment by dixudx** [comment]
> Also I suggest we should modify predicateNames for error message

@gyliu513 Seems we'd better not change the predicateNames in order to make it stable and backward compatible. Refer to below comments in codes,

> 	// The predicateName tries to be consistent as the predicate name used in DefaultAlgorithmProvider defined in
	// defaults.go (which tend to be stable for backward compatibility)

echo to @k82cn 
How about changing to 

> 0/2 nodes are available: following predicates MatchNodeSelector (2 nodes), MatchInterPodAffinity (1 node) failed.

**Comment by bsalamat** [comment]
I think we should add a more human-readable failure message for each predicate and print that message instead of the predicate name in the scheduler unschedulable message. For example, the message for "MatchNodeSelector" predicate can be something like "Nodes didn't match node selector".

**Comment by bsalamat** [comment]
This issue is already addressed.
