### ISSUE TITLE
Enable Network Load Balancers to register nodes by IP address

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#57249]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig aws

Creating an NLB service (with v1.9+) in Kubernetes registers instances by instance ID, which [limits the instance types](http://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html#register-deregister-targets) to only newer instance classes. A new service annotation would be the obvious way to enable target registration by IP address.

**Comment by rajatjindal** [comment]
@micahhausler can you please reopen this ticket. We are looking forward for support of registering instances by IP as we believe we are running into intermittent timeout issues as explained in: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout

**Comment by owlwalks** [comment]
Could we reopen this issue, I can spend some time to make this happen. I'm also thinking we shouldn’t classify this as a feature but a bug because provisioning private NLB won’t work with instance id (hairpin)

**Comment by rajakshay** [comment]
Is there any plans on adding this feature. We are running into the same issue mentioned here: https://github.com/kubernetes/kubernetes/issues/57249#issuecomment-450539833 

This would be a really nice feature to have. I can pickup this work. TBH, I am a little surprised that there hasn't been much movement or ask for this feature yet.

**Comment by dschunack** [comment]
/reopen

We have the same problem, private NLB won’t work with instance id

**Comment by mautematico** [comment]
We're facing this same issue with NLB and M1, M2, M3 instance types.

We're currently not using those instance types (i.e. creating a new NodeGroup without conflicting instance types) while there is a fix on service-controller
