### ISSUE TITLE
Receiving consecutive ADD calls for the same Windows container.

### ISSUE THREAD

**Issue by saiyan86** [kubernetes/kubernetes#57253]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig Azure

**What happened**:
For Windows docker containers, we receive consecutive ADD calls for the same container without DEL in between. 

**What you expected to happen**:
We expect to receive ADD calls in ADD-DEL cycle instead of consecutive ADD calls.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a kubernetes service.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Microsoft Azure

- OS (e.g. from /etc/os-release):

Microsoft Windows [Version 10.0.16299.19]

- Kernel (e.g. `uname -a`): 

N/A

- Install tools:

N/A

- Others:

N/A

**Comment by andyzhangx** [comment]
what's the ADD-DEL call? can you explain more?

**Comment by saiyan86** [comment]
Sure. The ADD-DEL calls are made when creating endpoint for containers.

**Comment by saiyan86** [comment]
From https://github.com/containernetworking/cni/blob/master/SPEC.md:

"The container runtime must order ADD and DEL operations for a container, such that ADD is always followed by a corresponding DEL. DEL may be followed by additional DELs, however, and plugins should handle multiple DELs permissively (i.e. plugin DEL should be idempotent)."

**Comment by feiskyer** [comment]
@saiyan86 This is what expected of windows containers. See here for why ADD is called consecutively

https://github.com/kubernetes/kubernetes/blob/6b57037432fa7d4e4157fd9d92b7aa33b3be16f1/pkg/kubelet/network/cni/cni_windows.go#L38-L39
