### ISSUE TITLE
Should validate ipset util

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#57269]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There is no validation for ipset set and entry in pkg/util/ipset.

**What you expected to happen**:

We should validate them before call ipset exec. IPVS should validate ipset entry before adding it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

/area ipvs

**Comment by thockin** [comment]
@rramkumar1
