### ISSUE TITLE
[v1.8.5] about custom scheduler

### ISSUE THREAD

**Issue by dongkunn** [kubernetes/kubernetes#57263]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind scheduling

**What happened**:
When I test Custom scheduler, but my pods status is still pending.
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

I made a new custom scheduler and 3 test pods like k8s sample yaml
but, pods using 'default-scheduler' works well, but pods using 'my-scheduler' doesn't work.

I don't know how to fix this problem.
Please help me.

**What you expected to happen**:
pods is made by my-scheduler will be 'Running'

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl apply -f my-schudler.yaml
NAME                                     READY     STATUS    RESTARTS   AGE
kube-system   my-scheduler-656856794f-s7hdw                   1/1       Running       0          18m

2. when i setup ks8s using kubeadm, authorization option set to Node, RBAC, so I modified clusterrole like this
kubectl edit clusterrole system:kube-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - kube-scheduler
  - my-scheduler
  resources:
  - endpoints
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:

3. kubectl apply -f no.yaml
kubectl apply -f default.yaml
kubectl apply -f my-scheduler.yaml
NAME                                     READY     STATUS    RESTARTS   AGE
annotation-default-scheduler             1/1       Running   0          17m
annotation-second-scheduler              0/1       Pending   0          17m
no-annotation                            1/1       Running   0          18m
sticky-node-scheduler-8447869685-9jl9q   1/1       Running   0          26m

**Anything else we need to know?**:
my k8s was made by kubeadm,
and all options are default.
and I use weave net plugin.
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubernetes custom schedule

- Others:

**Comment by liggitt** [comment]
What's in the log output of your custom scheduler pod?

**Comment by dongkunn** [comment]
this is my-scheduler log
but there is no event because this pod status is pending.
this is never scheduled.

[root@localhost ~]# kubectl describe pods annotation-second-scheduler
Name:         annotation-second-scheduler
Namespace:    default
Node:         <none>
Labels:       name=multischeduler-example
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"multischeduler-example"},"name":"annotation-second-scheduler","namespace...
Status:       Pending
IP:           
Containers:
  pod-with-second-annotation-container:
    Image:        gcr.io/google_containers/pause:2.0
    Port:         <none>
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mkxpj (ro)
Volumes:
  default-token-mkxpj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mkxpj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by dongkunn** [comment]
there is no log.
I think custom scheduler is blocked because of something. but I don't know reason.

**Comment by liggitt** [comment]
The my-scheduler-656856794f-s7hdw pod is not running? In the description, it showed as running
