### ISSUE TITLE
Device manager only considers extended resource limits when allocating devices.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/kubernetes#57276]
/kind bug
/sig node
/area hw-accelerators

**What happened**:
In `/pkg/kubelet/cm/deviceplugin/manager.go` devices are allocated from a function called `allocateContainerResources`. This function inspects only container resource limits, ignoring container resource requests. This is a usability problem because it is valid to omit limits for extended resources. If limit is omitted for a device resource, then the scheduler properly places the pod with respect to available node resources. However, the device manager never dispatches to the device plugin for that resource. The result is that the user application cannot access the requested device from inside the container.

**What you expected to happen**:
Following the documented behavior of extended resources, I expected that specifying a container resource request for a device would cause the device subsystem to properly configure access for my workload.

**How to reproduce it (as minimally and precisely as possible)**:
* Launch an alpha GKE cluster with GPU support enabled.
* Attempt to run any program that accesses the GPU from a container where the resource is specified in requests but omitted from limits.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8+
- Cloud provider or hardware configuration: device plugins enabled, devices available.

**Comment by ConnorDoyle** [comment]
Related issue: #57170

**Comment by ConnorDoyle** [comment]
cc @jiayingz @RenaudWasTaken @vikaschoudhary16 @vishh @balajismaniam

**Comment by tengqm** [comment]
FYI. The said issue has been fixed in #56398.

There are several valid cases when requesting extended resources:

- The user can specify 'limits' only. The API server will automatically set 'requests' to be equal to 'limits'.
- The user specify 'limits' and 'requests', and they are equal.
- The user specify 'requests' only. We can either reject the request saying that 'limits' must be set, or implicitly treat 'limits' as equal to 'requests'.

**Comment by ConnorDoyle** [comment]
Hi @tengqm, went with #57278 to begin since it was ready to go and smaller (easier to revert if necessary.) Hopefully it's easy to rebase your work on top of that. Sorry for the inconvenience.

**Comment by vishh** [comment]
I feel the documented behavior is incorrect. The original intention was to always require `requests = limits` for extended resources until we have better APIs to express bursting scenarios. 
I vote for fixing the documentation and fixing the validation logic and having kubelet use limits only.
