### ISSUE TITLE
invalid manifest for CoreDNS logging when started with kubeadm

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#57277]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG
> /kind bug

**What happened**:

When CoreDNS is deployed by default using feature-gates of kubeadm, it does not log anything when processing a DNS query.

That is due to change of log option of CoreDNS in latest version.
that version was bumped up in kubeadm, but the manifest was not adapted to the new log option.

- initial change of 'log stdout' in CoreDNS : https://github.com/coredns/coredns/issues/1218
- version of CoreDNS 1.0.0 bumped into Kubeadm : #56802

NOTE: I guess we should also changed manifests for kube-up : see #55728

The change in manifest expected is to remove the option "stdout" in the line "log ...". As it is now interpreted as a scope of domain to log.

Invalid manifest:
>   Corefile: |
>      .:53 {
>           errors
>           **log stdout**
>           health
>         ....
> 

Correct manifest:
>    Corefile: |
>      .:53 {
>           errors
>           **log**
>           health
>         ....

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9 and MAIN
- Cloud provider or hardware configuration: any
- Install tools: kubeadm, kube-up

## Workaround for installation that needs the log 

1. update the configmap for coredns

`kubectl get configmaps -n kube-system coredns -o yaml | sed "s/log stdout/log/g" | kubectl replace -f -
`

2. restart the coredns deployment

`
kubectl scale deployment --replicas=0 -n kube-system coredns
`
`
kubectl scale deployment --replicas=1 -n kube-system coredns
`

**Comment by fturib** [comment]
NOTE: only log is impacted. CoreDNS working as expected.

**Comment by fturib** [comment]
I have a question : 

the initial manfiest is done for the image 0.9.10 of CoreDNS.
Bumping the version of CoreDNS was done by changing the version in version.go file (see #56802)
which means that the image's version is STILL 0.9.10 in the manifests ... and the corefile config is correct against the version of the manifest.

QUESTION: when modifying the version.go, is there a way to upgrade the manifest by program ? I guess at the time the new version number is applied on the manifest ...

**Comment by xiangpengzhao** [comment]
@fturib thanks for reporting this! I send PR https://github.com/kubernetes/kubernetes/pull/57296 to update the Corefile.

> when modifying the version.go, is there a way to upgrade the manifest by program ?

I don't think of a way so far. I guess we can't unless there is a way to get the Corefile from some place of  upstream (CoreDNS).
