### ISSUE TITLE
[v1.9.0] Kubelet unable pull image

### ISSUE THREAD

**Issue by yuonch** [kubernetes/kubernetes#57273]
I run a dashboard which used my private docker registry with kube 1.9.0.
First, I had create one secret  ,and I can  pull image with "docker pull" use the username and password which in dockercfg.
![image](https://user-images.githubusercontent.com/312469/34070814-5c3128b8-e2a7-11e7-9043-f00fcf99bada.png)
But, the kubelet can't pull image.
![image](https://user-images.githubusercontent.com/312469/34070753-c490c87e-e2a6-11e7-8b94-a656a04a6758.png)
![image](https://user-images.githubusercontent.com/312469/34070761-ddef74f0-e2a6-11e7-9a75-1013e70093bb.png)
This is the kubelet log :
![image](https://user-images.githubusercontent.com/312469/34070789-1ec9d556-e2a7-11e7-9f06-a6aaa8e4cc73.png)

**Comment by cmoad** [comment]
I am also unable to pull an image from a private repo using `imagePullSecrets` on a service account when generating the secret using version 1.9.0 of kubectl. I am running k8s v1.8.0 in minikube. When I downgraded kubectl to 1.8.5 and regenerated the secret with the same command, the image pulled fine.

**Comment by hd-deman** [comment]
same for me (

**Comment by dims** [comment]
Duplicate of #57427 let's please use that as it has more details.

/close
