### ISSUE TITLE
Kubernetes-cni issue with 1.9.0 - no ip address available in range

### ISSUE THREAD

**Issue by ieugen** [kubernetes/kubernetes#57280]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I've upgraded my cluster from 1.8.5 -> 1.9.0. I upgraded the packages on my system and then used the kubeadm upgrade instructions. The upgrade went well. I changed docker logging config and restarted docker. Kube-dns did not start and I had two of them. Also my deployments did not start as well.

**What you expected to happen**:
I expected my cluster to work normally as expected. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new cluster with 1.8.5.
2. Update packages to 1.9.0
3. kubeadm upgrade plan
4. kubeadm upgrade apply 1.9.0
5. weep.

**Anything else we need to know?**:

The main issue is that pods don't find an IP address: 
````
 E1216 23:50:16.116098   28152 pod_workers.go:186] Error syncing pod 6f5b9673-e2b5-11e7-a0f5-001e67d35991 ("kube-dns-6f4fd4bdf-xrj4w_kube-system(6f5b9673-e2b5-11e7-a0f5-001e67d35991)"), skipping: failed to "CreatePodSandbox" for "kube-dns-6f4fd4bdf-xrj4w_kube-system(6f5b9673-e2b5-11e7-a0f5-001e67d35991)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-6f4fd4bdf-xrj4w_kube-system(6f5b9673-e2b5-11e7-a0f5-001e67d35991)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"kube-dns-6f4fd4bdf-xrj4w_kube-system\" network: failed to allocate for range 0: no IP addresses available in range set: 10.244.0.1-10.244.0.254"
````
Now, I have checked to see what happens in `/var/lib/cni/networks` and I have found that all the addresses are filled up:
````
/var/lib/cni/networks# ls cbr0/
10.244.0.10   10.244.0.123  10.244.0.147  10.244.0.170	10.244.0.194  10.244.0.217  10.244.0.240  10.244.0.35  10.244.0.59  10.244.0.82
10.244.0.100  10.244.0.124  10.244.0.148  10.244.0.171	10.244.0.195  10.244.0.218  10.244.0.241  10.244.0.36  10.244.0.6   10.244.0.83
10.244.0.101  10.244.0.125  10.244.0.149  10.244.0.172	10.244.0.196  10.244.0.219  10.244.0.242  10.244.0.37  10.244.0.60  10.244.0.84
10.244.0.102  10.244.0.126  10.244.0.15   10.244.0.173	10.244.0.197  10.244.0.22   10.244.0.243  10.244.0.38  10.244.0.61  10.244.0.85
10.244.0.103  10.244.0.127  10.244.0.150  10.244.0.174	10.244.0.198  10.244.0.220  10.244.0.244  10.244.0.39  10.244.0.62  10.244.0.86
10.244.0.104  10.244.0.128  10.244.0.151  10.244.0.175	10.244.0.199  10.244.0.221  10.244.0.245  10.244.0.4   10.244.0.63  10.244.0.87
10.244.0.105  10.244.0.129  10.244.0.152  10.244.0.176	10.244.0.2    10.244.0.222  10.244.0.246  10.244.0.40  10.244.0.64  10.244.0.88
10.244.0.106  10.244.0.13   10.244.0.153  10.244.0.177	10.244.0.20   10.244.0.223  10.244.0.247  10.244.0.41  10.244.0.65  10.244.0.89
10.244.0.107  10.244.0.130  10.244.0.154  10.244.0.178	10.244.0.200  10.244.0.224  10.244.0.248  10.244.0.42  10.244.0.66  10.244.0.9
10.244.0.108  10.244.0.131  10.244.0.155  10.244.0.179	10.244.0.201  10.244.0.225  10.244.0.249  10.244.0.43  10.244.0.67  10.244.0.90
10.244.0.109  10.244.0.132  10.244.0.156  10.244.0.18	10.244.0.202  10.244.0.226  10.244.0.25   10.244.0.44  10.244.0.68  10.244.0.91
10.244.0.11   10.244.0.133  10.244.0.157  10.244.0.180	10.244.0.203  10.244.0.227  10.244.0.250  10.244.0.45  10.244.0.69  10.244.0.92
10.244.0.110  10.244.0.134  10.244.0.158  10.244.0.181	10.244.0.204  10.244.0.228  10.244.0.251  10.244.0.46  10.244.0.7   10.244.0.93
10.244.0.111  10.244.0.135  10.244.0.159  10.244.0.182	10.244.0.205  10.244.0.229  10.244.0.252  10.244.0.47  10.244.0.70  10.244.0.94
10.244.0.112  10.244.0.136  10.244.0.16   10.244.0.183	10.244.0.206  10.244.0.23   10.244.0.253  10.244.0.48  10.244.0.71  10.244.0.95
10.244.0.113  10.244.0.137  10.244.0.160  10.244.0.184	10.244.0.207  10.244.0.230  10.244.0.254  10.244.0.49  10.244.0.72  10.244.0.96
10.244.0.114  10.244.0.138  10.244.0.161  10.244.0.185	10.244.0.208  10.244.0.231  10.244.0.26   10.244.0.5   10.244.0.73  10.244.0.97
10.244.0.115  10.244.0.139  10.244.0.162  10.244.0.186	10.244.0.209  10.244.0.232  10.244.0.27   10.244.0.50  10.244.0.74  10.244.0.98
10.244.0.116  10.244.0.14   10.244.0.163  10.244.0.187	10.244.0.21   10.244.0.233  10.244.0.28   10.244.0.51  10.244.0.75  10.244.0.99
10.244.0.117  10.244.0.140  10.244.0.164  10.244.0.188	10.244.0.210  10.244.0.234  10.244.0.29   10.244.0.52  10.244.0.76  last_reserved_ip.0
10.244.0.118  10.244.0.141  10.244.0.165  10.244.0.189	10.244.0.211  10.244.0.235  10.244.0.3	  10.244.0.53  10.244.0.77
10.244.0.119  10.244.0.142  10.244.0.166  10.244.0.19	10.244.0.212  10.244.0.236  10.244.0.30   10.244.0.54  10.244.0.78
10.244.0.12   10.244.0.143  10.244.0.167  10.244.0.190	10.244.0.213  10.244.0.237  10.244.0.31   10.244.0.55  10.244.0.79
10.244.0.120  10.244.0.144  10.244.0.168  10.244.0.191	10.244.0.214  10.244.0.238  10.244.0.32   10.244.0.56  10.244.0.8
10.244.0.121  10.244.0.145  10.244.0.169  10.244.0.192	10.244.0.215  10.244.0.239  10.244.0.33   10.244.0.57  10.244.0.80
10.244.0.122  10.244.0.146  10.244.0.17   10.244.0.193	10.244.0.216  10.244.0.24   10.244.0.34   10.244.0.58  10.244.0.81
````
 and flannel creates a lot of files without stopping:
````
/var/lib/cni/flannel#  ls | wc ; date 
   1207    1207   78455
Sat Dec 16 23:53:25 UTC 2017
root@staging:/var/lib/cni/flannel#  ls | wc ; date 
   1212    1212   78780
Sat Dec 16 23:53:27 UTC 2017
root@staging:/var/lib/cni/flannel#  ls | wc ; date 
   1214    1214   78910
Sat Dec 16 23:53:28 UTC 2017
````

**Environment**:
- Kubernetes version (use `kubectl version`):
````
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
````
- Cloud provider or hardware configuration: bare metal, single node
- OS (e.g. from /etc/os-release): 
````
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
````
- Kernel (e.g. `uname -a`):  4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux
- Install tools: kubeadm
- Others: flannel 0.9.1 

For some reason the system ends up with 2 `deploy/kube-dns` and 
````
 kubectl -n kube-system get all 
NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
ds/kube-flannel-ds   1         1         1         1            1           beta.kubernetes.io/arch=amd64   33m
ds/kube-proxy        1         1         1         1            1           <none>                          38m

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns               1         2         1            1           38m
deploy/kubernetes-dashboard   1         1         1            1           30m

NAME                                DESIRED   CURRENT   READY     AGE
rs/kube-dns-545bc4bfd4              1         1         1         38m
rs/kube-dns-6f4fd4bdf               1         1         0         4m
rs/kubernetes-dashboard-79ddfdc44   1         1         1         30m

NAME                 DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
ds/kube-flannel-ds   1         1         1         1            1           beta.kubernetes.io/arch=amd64   33m
ds/kube-proxy        1         1         1         1            1           <none>                          38m

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns               1         2         1            1           38m
deploy/kubernetes-dashboard   1         1         1            1           30m

NAME                                DESIRED   CURRENT   READY     AGE
rs/kube-dns-545bc4bfd4              1         1         1         38m
rs/kube-dns-6f4fd4bdf               1         1         0         4m
rs/kubernetes-dashboard-79ddfdc44   1         1         1         30m

NAME                                           READY     STATUS              RESTARTS   AGE
po/etcd-staging.gr8pi.net                      1/1       Running             0          3m
po/kube-apiserver-staging.gr8pi.net            1/1       Running             0          4m
po/kube-controller-manager-staging.gr8pi.net   1/1       Running             0          4m
po/kube-dns-545bc4bfd4-xs7zw                   3/3       Running             6          38m
po/kube-dns-6f4fd4bdf-wvmgp                    0/3       ContainerCreating   0          2m
po/kube-flannel-ds-8nb76                       1/1       Running             3          33m
po/kube-proxy-fvtzr                            1/1       Running             0          4m
po/kube-scheduler-staging.gr8pi.net            1/1       Running             0          4m
po/kubernetes-dashboard-79ddfdc44-p6sfv        1/1       Running             4          30m

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
svc/kube-dns               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP   38m
svc/kubernetes-dashboard   NodePort    10.103.193.125   <none>        80:30940/TCP    30m
````

**Comment by ieugen** [comment]
This also happens after reseting and re-installing cluster 

`kubeadm reset` + `rm -rf /var/lib/cni/flannel/* ` and `rm -rf /var/lib/cni/networks/cbr0/* ` and `ip link delete cni0 flannel.1` .

**Comment by ieugen** [comment]
I can confirm downgrading to 1.8.5 makes cluster work after re-install.

**Comment by xiangpengzhao** [comment]
> For some reason the system ends up with 2 deploy/kube-dns

Some discussion here: https://github.com/kubernetes/kubernetes/issues/55720

**Comment by squeed** [comment]
Interesting; taking a look. I wonder if it is the old kubenet GC code no longer working.

**Comment by ieugen** [comment]
Thanks @xiangpengzhao.  55720 explains the duplication. Not sure if it explains the bug about container not starting and IP's getting exhausted.

**Comment by Riptawr** [comment]
Same issue on Ubuntu 16.04.1 LTS

**Comment by pytimer** [comment]
Same issue on Centos7.2

**Comment by hansedong** [comment]
I same issue on Centos 7.2.1511

**Comment by mehrdadpfg** [comment]
same issue here on debian 9  with kube-router

**Comment by 2008chny** [comment]
Same issue on Centos7.4

**Comment by JoeJasinski** [comment]
Same issue on Raspberry PI (Hyperiot) with Flannel networking. A reset solves it for a bit, but comes back after a cluster reboot. 

```
Dec 28 00:04:45 node4 kubelet[8024]: E1228 00:04:45.997242    8024 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "nginx-596ddc9cb7-q78q4_default" network: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254
Dec 28 00:04:46 node4 kubelet[8024]: E1228 00:04:45.997544    8024 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "nginx-596ddc9cb7-q78q4_default(78e796f5-eb7c-11e7-b903-b827ebd42d30)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "nginx-596ddc9cb7-q78q4_default" network: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254
Dec 28 00:04:46 node4 kubelet[8024]: E1228 00:04:45.997659    8024 kuberuntime_manager.go:647] createPodSandbox for pod "nginx-596ddc9cb7-q78q4_default(78e796f5-eb7c-11e7-b903-b827ebd42d30)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "nginx-596ddc9cb7-q78q4_default" network: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254
Dec 28 00:04:46 node4 kubelet[8024]: E1228 00:04:45.998144    8024 pod_workers.go:186] Error syncing pod 78e796f5-eb7c-11e7-b903-b827ebd42d30 ("nginx-596ddc9cb7-q78q4_default(78e796f5-eb7c-11e7-b903-b827ebd42d30)"), skipping: failed to "CreatePodSandbox" for "nginx-596ddc9cb7-q78q4_default(78e796f5-eb7c-11e7-b903-b827ebd42d30)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-596ddc9cb7-q78q4_default(78e796f5-eb7c-11e7-b903-b827ebd42d30)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"nginx-596ddc9cb7-q78q4_default\" network: failed to allocate for range 0: no IP addresses available in range set: 10.244.1.1-10.244.1.254"
```

**Comment by sarmadali20** [comment]
same issue CentOS Linux release 7.4.1708 (Core)

**Comment by midoblgsm** [comment]
I had the same issue on Ubuntu 16.04.1 LTS (using flannel for the networking), following #39557 resolved the issue for me:
I did (on the node having the issue): 

```bash
kubeadm reset
systemctl stop kubelet
systemctl stop docker
rm -rf /var/lib/cni/
rm -rf /var/lib/kubelet/*
rm -rf /etc/cni/
ifconfig cni0 down
ifconfig flannel.1 down
ifconfig docker0 down
ip link delete cni0
ip link delete flannel.1
```
then restarted docker and kubelet and did the `kubeadm join` dance again.

**Comment by rossedman** [comment]
@midoblgsm this worked for me, thank you very much.

**Comment by hwchiu** [comment]
@midoblgsm  this worked for me!! thanks.

**Comment by John-Lin** [comment]
@midoblgsm it works like a charm!!

**Comment by squeed** [comment]
This isn't a problem with Kubernetes, rather one with Flannel and the host-local ipam plugin.

I recommend you configure your host-local ipam plugin to use a dataDir in `/run`, instead of the default in `/var/lib`. That will mean that IPAM is cleared on every reboot.

I think this issue can be closed. Perhaps the recommended Flannel configuration should be updated, but that's an issue for the Flannel repository.

**Comment by tomdee** [comment]
@squeed Could you raise a flannel issue to track this if the config in that repo needs to be updated?

**Comment by brentpearson** [comment]
"I recommend you configure your host-local ipam plugin to use a dataDir in /run, instead of the default in /var/lib. That will mean that IPAM is cleared on every reboot."

Could someone please explain how to do this?

**Comment by robertglen** [comment]
this is new behavior as far as I can tell under K8S 1.9.x.  The only cluster I have running 1.9.x is the only one suddenly showing this issue.    I have 79256 files in /var/lib/cni/flannel/   and /var/lib/cni/network/cni0 has one file per IP in the /24 assigned to the node.   pods stuck in container creating, and kubelet on the node complains of the error in the original post saying no more IPs in the block.

Something is up

**Comment by squeed** [comment]
Hmm. Has anything changed w.r.t. the pod lifecycle for newly restarted kubelets? Perhaps it is no longer doing network teardowns when the pod doesn't exist, e.g. on reboot.

**Comment by drpreag** [comment]
When create flannel network you must use this:
kubeadm init --pod-network-cidr 10.244.0.0/16
Flannel must use 10.244.0.0/16, any else will fail. 

Second, debian 9 has problem with k8s networking, I switched to Ubuntu.

**Comment by ieugen** [comment]
@drpreag , could you please elaborate on the statement:  
> Second, debian 9 has problem with k8s networking, I switched to Ubuntu.

**Comment by drpreag** [comment]
I can't say what is going on and what is a reason, but I had a lot of problems with cluster on debian 9 machines (master + 3 nodes). Every time once in a while flannel pods crashed/restarted, also Dashboard crashes all the time. Pods can't ping. Can't expose out of cluster... I could bet it was a network problem.

After I deployed all a same to Ubuntu server 16.04. lts VMs (100% same k8s deploy scripts) all works fine.

I am in a phase of learning kubernetes, so not able to resolve a problem, it was easier to change OS.
Btw K8s is 1.10.0, dashboard 1.8.2

**Comment by ieugen** [comment]
Ok, thanks for sharing. What docker version are you using - I assume kernel is from stable or backports?

**Comment by drpreag** [comment]
18.03.0-ce stable

**Comment by ieugen** [comment]
@drpreag : I believe that is the issue. Kubernetes is validated to be work in production with just a few docker version: 

> On each of your machines, install Docker. Version v1.12 is recommended, but v1.11, v1.13 and 17.03 are known to work as well. Versions 17.06+ might work, but have not yet been tested and verified by the Kubernetes node team.

https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by RahulG115** [comment]
due to restart policy it keeps on creating the containers and assign it to interface , delete all ips and then create pods , only ip u get will be the pod ip .
this is a bug of not cleaning the pod ip when container unable to start.

**Comment by XANi** [comment]
I'be got same problem on kube-router so it is definitely NOT a flannel-only problem

**Comment by BostjanBozic** [comment]
We are experiencing same issue. Might be though that reason is we recreated whole cluster and forgot to clean up /var/lib/cni/networks/cbr0. Any idea if we do that now (at least for old IPs) would it make sense or would it cause some issues? I see in #383 that it works, but just want to ask around if anyone else tried it before

**Comment by jansmets** [comment]
same issue here. resetting the node and clearing out /etc/cni/... worked, for now.

**Comment by kivoli** [comment]
We’re having the same issue with 1.10, flannel and containerd. Clearing out `/var/lib/cni/networks/cbr0` is sufficient …

I adapted a [one-liner from 2016](https://github.com/kubernetes/kubernetes/issues/34278#issuecomment-254686727) from #34278 for `crictl`:
```bash
cd /var/lib/cni/networks/cbr0                                                                                                                                                                                      
for hash in $(tail -n +1 * | egrep '^[A-Za-z0-9]{64,64}$'); do
  if [ -z $(crictl pods --no-trunc | grep $hash | awk '{print $1}') ]; then
          grep -ilr $hash ./ | xargs rm
  fi;
done
```
Thanks, @bprashanth.

**Comment by mhristache** [comment]
Can someone explain who is responsible of cleaning up `/var/lib/cni/networks/`?

I have:

```bash
# cat last_reserved_ip
10.244.0.41
```

But there is a file inside `/var/lib/cni/networks/flannel.1` for all IPs above `10.244.0.41` and I get the error reported in this ticket:

```bash
# ls 10.244.0.2
10.244.0.2    10.244.0.202  10.244.0.206  10.244.0.21   10.244.0.213  10.244.0.217  10.244.0.220  10.244.0.224  10.244.0.228  10.244.0.231  10.244.0.235  10.244.0.239  10.244.0.242  10.244.0.246  10.244.0.25   10.244.0.253  10.244.0.28   
10.244.0.20   10.244.0.203  10.244.0.207  10.244.0.210  10.244.0.214  10.244.0.218  10.244.0.221  10.244.0.225  10.244.0.229  10.244.0.232  10.244.0.236  10.244.0.24   10.244.0.243  10.244.0.247  10.244.0.250  10.244.0.254  10.244.0.29   
10.244.0.200  10.244.0.204  10.244.0.208  10.244.0.211  10.244.0.215  10.244.0.219  10.244.0.222  10.244.0.226  10.244.0.23   10.244.0.233  10.244.0.237  10.244.0.240  10.244.0.244  10.244.0.248  10.244.0.251  10.244.0.26   
10.244.0.201  10.244.0.205  10.244.0.209  10.244.0.212  10.244.0.216  10.244.0.22   10.244.0.223  10.244.0.227  10.244.0.230  10.244.0.234  10.244.0.238  10.244.0.241  10.244.0.245  10.244.0.249  10.244.0.252  10.244.0.27 
```

Thank you

**Comment by insertjokehere** [comment]
The script that @kivoli posted above is enough to get a node out of this state (for me at least), don't need to do a full node reset

**Comment by jsenon** [comment]
I've made this tool, if somebody is interested https://github.com/jsenon/api-cni-cleanup

**Comment by squeed** [comment]
For the record, Kubernetes will call a CNI DEL for old and stale sandboxes.

However, if you're force-removing /var/run/docker, then it will assume the sandboxes are already cleaned up, and IP addresses will leak.

**Comment by trevex** [comment]
@squeed How does this interact though with "stateless" pxebooted bare-metal clusters. Would this not imply, that potentially every restart leaks IP addresses?

**Comment by squeed** [comment]
@trevex it depends on what you're using for IPAM. If you use the CNI host-local one, it stores its state on disk, so that is *also* thrown away and you don't have any leaks. If you're using one that stores state in an external place (e.g. Infoblox), then you need to think a bit more carefully.

By default, kubenet uses the host-local IPAM, so it won't be affected.

The problem is when you flush `/var/{lib,run}/docker` but not `/var/lib/cni`.

**Comment by trevex** [comment]
@squeed Thank you for clearing this up for me.

**Comment by asdfsx** [comment]
> This isn't a problem with Kubernetes, rather one with Flannel and the host-local ipam plugin.
> 
> I recommend you configure your host-local ipam plugin to use a dataDir in `/run`, instead of the default in `/var/lib`. That will mean that IPAM is cleared on every reboot.
> 
> I think this issue can be closed. Perhaps the recommended Flannel configuration should be updated, but that's an issue for the Flannel repository.
Is there any difference between `/var/lib` and `/run`? Why using `/run` will solve the problem? @squeed

**Comment by matthiasr** [comment]
`/run` (at least on most systems) is automatically cleaned out on boot.

Is it safe to flush `/var/lib/cni` without also flushing `/var/{lib,run}/docker`? we run into this after node crashes, but we'd rather not re-pull all the images after every reboot.

**Comment by matthiasr** [comment]
FWIW, I don't think this is a *flannel* issue per se, and it still happens in 1.12.1.

We use plain kubenet on the cluster in question, and the path is [set by Kubernetes](https://github.com/kubernetes/kubernetes/blob/eab977f6d4f70ee67ddde756d20e45d428f2a5f5/pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go#L64). There was code to fix this [generally by GCing](https://github.com/kubernetes/kubernetes/pull/34373) but that code no longer seems to be there, I don't know when it disappeared.

**Comment by zhangguanzhang** [comment]
for docker fix:
```
cd /var/lib/cni/networks/cbr0
ls -1 | grep -P '([0-9]{1,3}\.){3}[0-9]{1,3}' | while read file;do
  hash=$(grep -Pom1 '\S+' $file)
  docker inspect $hash &>/dev/null || rm -f $file
done
```
