### ISSUE TITLE
question about pod exec

### ISSUE THREAD

**Issue by readless** [kubernetes/kubernetes#57284]
when i request the pod(on node node-A) exec api , if i do not config the ip of node-A in the k8s master's /etc/hosts, i will get the error from k8s master such as "can not resolve node-A " ,what should i do ,thanks

**Comment by resouer** [comment]
@readless What runtime you are using, Docker?

Generally kubelet should return it's IP to apiserver so you can send EXEC to that IP addr, instead of it's hostname. So I wonder how your kubernetes & kubelet is installed? Is there any special configuration being made?

**Comment by readless** [comment]
i request the url 
`wss://**:6443/api/v1/namespaces/**/pods/**/exec?stdout=1&stdin=1&stderr=1&tty=1&command=/bin/sh&command=-i`
, (this pod is running on the node named node-A)
but the api master logs 
`kube-apiserver[43544]: E1218 09:09:24.846961   43544 status.go:62] apiserver received an error that is not an metav1.Status: error dialing backend: dial tcp: lookup node-A on **:53: server misbehaving`
when i add the node-A ip to the /etc/hosts, the url work .
so how can i let the master use the node ip other than the node name to connect with node

**Comment by resouer** [comment]
@readless Could you please add `-v=10` to help me to track your HTTP requests when doing `kubectl exec`?

I guess it's not configuration issue.

**Comment by resouer** [comment]
Please pay attention to what URL is returned by kubelet for you to do `exec`

**Comment by ncdc** [comment]
This is not a bug. Your apiserver needs to be able to resolve the node's address, via DNS or /etc/hosts.
