### ISSUE TITLE
Initial support for resource quota and limit range on extended resources

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#57300]
/kind feature
/area hw-accelerators

**What happened**:
We hope to support extended resource quota through the new resource class API in the long term. but given that this is a valuable feature that people may want asap, and the modification would be relatively small, we should consider implementing this with the current resource API for now.

- [x] support for resource quota
- [x] support for  limit range

/assign

**Comment by lichuqiang** [comment]
@jiayingz @vishh I've made the change for resource quota in #57302, PTAL :)
As for the issue of limit range, I looked into related codes and did several tests, seems the limitrange for ER has already been supported without any change.
Please let me know if I missed something.

**Comment by mindprince** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/46639 which has a lot more discussion.

**Comment by lichuqiang** [comment]
Thanks for reminding, I would update related PR to refer to the issue.
As for this one, it's more of a track of related tasks in v1.10. and includes limitrange other than resourceQuota.

**Comment by jiayingz** [comment]
As I understand, we don't seem to need limit range given that current ER doesn't allow any overcommit.

@lichuqiang could you add an agenda to the RM workgroup meeting to summarize the change you made to support ER resource quota to get some general feedback? Thanks!

**Comment by mindprince** [comment]
Yeah, since ERs don't support overcommit, LimitRange defaulting doesn't make sense for them. But LimitRange can still be used for enforcing max, I think.

I would suggest updating this to be just for limitrange and use the other issue for resource quota.

**Comment by jiayingz** [comment]
As @lichuqiang mentioned, LimitRange max/min already works for ER. Even LimitRange default also works for ER, which seems debatable and I think we may want to get some consensus on whether we want to explicitly disable this.

**Comment by jiayingz** [comment]
Thinking a bit more on LimitRange default on ER, I guess it could be useful in example use cases that admins want to enforce SW licence requests in every running pod.

**Comment by lichuqiang** [comment]
Closing the issue due to https://github.com/kubernetes/kubernetes/pull/57302
