### ISSUE TITLE
How pod preemption happen between multi schedulers?

### ISSUE THREAD

**Issue by gongweibao** [kubernetes/kubernetes#57315]
From [document](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/) I know that a Pod must be scheduled by one scheduler. Such as scheduler `A` schedule pod `a` and scheduler `B` schedule pod `b`.

The question is that:  can `a` preempt `b` if `b` is already running? Which scheduler will do this operation?

And I found the preemption is [described](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) as `When a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible`. And then all the schedulers should follow the same priority rules? If a scheduler has its own priority, what will happen?

/sig scheduling

**Comment by gongweibao** [comment]
I found the preemption is [described](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) as `When a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible`. And then all the schedulers should follow the same priority rules? If a scheduler owner forgot it, pods will be scheduled in a loop?

**Comment by resouer** [comment]
@gongweibao Today's design of multiple schedulers is like a "main scheduler" with  an "auxiliary scheduler", and the later is assumed to be very simple and trying to avoid any cache (there will be inconsistency). In this case, I will not say preemption can work for the "auxiliary scheduler".

cc @bsalamat who leads priority/preemption work.

**Comment by bsalamat** [comment]
Multiple schedulers must follow the same priority rule: higher integer value of Pod priority indicates higher priority for the Pod. In multi-scheduler scenarios, all the schedulers must follow this rule if they all want to implement preemption.

**Comment by gongweibao** [comment]
Thanks! It's useful!
