### ISSUE TITLE
should ignore the "Not Found error" when ensure ipset set or entry are deleted

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#57318]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

should ignore the "Not Found error" when ensure ipset set or entry are deleted.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

/area ipvs

**Comment by thockin** [comment]
@rramkumar1
