### ISSUE TITLE
Return Custom Resources ONLY for the API Version in which they were stored

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#57339]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

/kind feature

It's currently common to hear discussion of CRDs and apiserver aggregations and then the conclusion that CRDs can't be used due to a lack of ability to version them properly and thus it's not possible to build operators that may have their CRDs change and evolve over time as they have no way to version and migrate.

Given the limited use of the apiVersion field, as-is, for Custom Resources, would it make sense to change how the Custom Resource APIs work such that Custom Resources can only be retrieved for the apiVersion for which they were stored? This would allow operators to handle multiple apiVersions as different versions of the Custom Resource itself, and would enable the ability for operators to automatically migrate and upgrade the Custom Resources they know about.

**Comment by liggitt** [comment]
disjoint namespaces for custom resources in different versions would break users of the APIs and make consumers deal with them differently than other kube resources. If we allow multiple versions for CRDs, we'll need to do it in a way that is consistent with other kubernetes APIs externally
