### ISSUE TITLE
kubelet dependency to kubernetes-cni failure

### ISSUE THREAD

**Issue by lynx-coding** [kubernetes/kubernetes#57334]
/kind bug
/sig architecture

**What happened**:
When trying to install kubelet I got the following error:
`kubelet : Depends: kubernetes-cni (= 0.5.1) but 0.6.0-00 is to be installed`

**What you expected to happen**:
The dependency should be resolved by the kubelet package itself, but I get the error.

**How to reproduce it (as minimally and precisely as possible)**:
Remove kubernetes-cni from your Ubuntu 16 machine and run "apt install kubelet=1.8.5*"

**Anything else we need to know?**:
- When I install kubernetes-cni in version 0.5.1 by myself, it works, but usually this should work out of the box.
- `apt-cache policy kubernetes-cni` only shows "0.5.1-00"

**Environment**:
- Kubernetes version: 1.8.5
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS (Xenial Xerus)
- Kernel: 4.4.0-31-generic
- Install tools: apt

**Comment by kubadawczynski** [comment]
This issue is related to all packages in *-01 version
```
Package: kubelet
Version: 1.6.12-00
Installed-Size: 135636
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (>= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.6.12-00_amd64_c302b5075f37fc8bdc251b2170b1b7b358c0faaf993ee1f0cf20204e971009ef.deb
Priority: optional
SHA256: c302b5075f37fc8bdc251b2170b1b7b358c0faaf993ee1f0cf20204e971009ef
Section: misc
Size: 18309998

Package: kubelet
Version: 1.6.12-01
Installed-Size: 135636
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.6.12-01_amd64_f61d249652954ea98d139332c81d1fb99db2b56d40265bc4aa88b7e8a1210740.deb
Priority: optional
SHA256: f61d249652954ea98d139332c81d1fb99db2b56d40265bc4aa88b7e8a1210740
Section: misc
Size: 18303806
```

Why *-00 versions require kubernetes-cni (>= 0.5.1) and *-01 require specific version of kubernetes-cni

**Comment by dixudx** [comment]
> Why *-00 versions require kubernetes-cni (>= 0.5.1) and *-01 require specific version of kubernetes-cni

@kubadawczynski We've bumped CNI to 0.6.0 in v1.9, which is incompatible with older versions less than v1.9. So we made this restriction.

@pipejakob Seems the version restriction we made in kubernetes/release#486 did not work as expected.

```
Package: kubelet
Version: 1.9.0-00
Installed-Size: 144333
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.6.0), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Description-md5: 0bad32a8f0183e699705f1585a26664c
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.9.0-00_amd64_100df9788226fe76ce828503cf24b8c4c6f9705f15504093844c9138e0b2a97f.deb
Priority: optional
SHA256: 100df9788226fe76ce828503cf24b8c4c6f9705f15504093844c9138e0b2a97f
Section: misc
Size: 20452588

Package: kubelet
Version: 1.8.5-01
Installed-Size: 134598
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Description-md5: 0bad32a8f0183e699705f1585a26664c
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.8.5-01_amd64_af944a975e45ee2889cfb6117de955a68f7e8233ab831d073a179eccde1a3298.deb
Priority: optional
SHA256: af944a975e45ee2889cfb6117de955a68f7e8233ab831d073a179eccde1a3298
Section: misc
Size: 19254630

Package: kubelet
Version: 1.8.5-00
Installed-Size: 134598
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: iptables (>= 1.4.21), kubernetes-cni (>= 0.5.1), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Description-md5: 0bad32a8f0183e699705f1585a26664c
Homepage: https://kubernetes.io
Filename: pool/kubelet_1.8.5-00_amd64_19c18818c0a5efc2fdbc86c87407db05d1de403b01a35e3a145b23cf3995ce5c.deb
Priority: optional
SHA256: 19c18818c0a5efc2fdbc86c87407db05d1de403b01a35e3a145b23cf3995ce5c
Section: misc
Size: 19250488
```

v1.8.5 is not the only victim. All the `1.*-01` packages are affected. And `apt-get install kubelet=1.*-00` will still install `kubernetes-cni=0.6.0`.

/cc @luxas 
/priority critical

**Comment by dixudx** [comment]
Filed a PR kubernetes/release#489 to fix this.
@luxas @enisoc @pipejakob PTAL.

**Comment by dixudx** [comment]
The root cause of this issue is the version mismatch.

The required kubernetes-cni version for kubelet<1.9 is `0.5.0`, which is not a right version. It should be `0.5.0-00`.

Should be `0.6.0-00` for kubelet>=1.9 also.

**Comment by luxas** [comment]
cc @pipejakob @mikedanese @enisoc @mbohlool @jpbetz @kubernetes/sig-cluster-lifecycle-bugs

**Comment by agarwal-vivek** [comment]
bash-4.1$ sudo yum install kubelet-1.8.4 kubeadm-1.8.4
Loaded plugins: aliases, changelog, downloadonly, fastestmirror, kabi, presto, refresh-packagekit, security, tmprepo, verify, versionlock
Loading support for kernel ABI
Setting up Install Process
Loading mirror speeds from cached hostfile
 * ol6_latest: pd-yum-den-01.us.oracle.com
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.8.4-0 will be installed
--> Processing Dependency: kubectl >= 1.6.0 for package: kubeadm-1.8.4-0.x86_64
--> Processing Dependency: kubernetes-cni for package: kubeadm-1.8.4-0.x86_64
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: iptables >= 1.4.21 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: socat for package: kubelet-1.8.4-1.x86_64
--> Running transaction check
---> Package kubectl.x86_64 0:1.9.0-0 will be installed
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: iptables >= 1.4.21 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: socat for package: kubelet-1.8.4-1.x86_64
---> Package kubernetes-cni.x86_64 0:0.6.0-0 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: kubernetes-cni = 0.5.1
           Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
               kubernetes-cni = 0.3.0.1-0.07a8a2
           Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-0
           Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-1
           Installing: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
               kubernetes-cni = 0.6.0-0
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: iptables >= 1.4.21
           Installed: iptables-1.4.7-14.0.1.el6.i686 (@base)
               iptables = 1.4.7-14.0.1.el6
           Available: iptables-1.4.7-3.el6.i686 (ol6_latest)
               iptables = 1.4.7-3.el6
           Available: iptables-1.4.7-4.el6.i686 (ol6_latest)
               iptables = 1.4.7-4.el6
           Available: iptables-1.4.7-5.1.el6_2.i686 (ol6_latest)
               iptables = 1.4.7-5.1.el6_2
           Available: iptables-1.4.7-9.el6.i686 (ol6_latest)
               iptables = 1.4.7-9.el6
           Available: iptables-1.4.7-11.0.1.el6.i686 (ol6_latest)
               iptables = 1.4.7-11.0.1.el6
           Available: iptables-1.4.7-16.0.2.el6.i686 (ol6_latest)
               iptables = 1.4.7-16.0.2.el6
           Available: iptables-1.4.7-16.0.5.el6.i686 (ol6_latest)
               iptables = 1.4.7-16.0.5.el6
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: socat
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
kernel-uek-doc-3.8.13-118.13.3.el6uek.noarch is a duplicate with kernel-uek-doc-3.8.13-44.1.1.el6uek.noarch
bash-4.1$ sudo yum update iptables-1.4.7-14.0.1.el6.i686
Loaded plugins: aliases, changelog, downloadonly, fastestmirror, kabi, presto, refresh-packagekit, security, tmprepo, verify, versionlock
Loading support for kernel ABI
Setting up Update Process
Loading mirror speeds from cached hostfile
 * ol6_latest: pd-yum-den-01.us.oracle.com
Resolving Dependencies
--> Running transaction check
---> Package iptables.i686 0:1.4.7-14.0.1.el6 will be updated
---> Package iptables.i686 0:1.4.7-16.0.5.el6 will be an update
--> Finished Dependency Resolution
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for iptables which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of iptables of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude iptables.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of iptables installed, but
            yum can only see an upgrade for one of those arcitectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of iptables installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: iptables-1.4.7-16.0.5.el6.i686 != iptables-1.4.7-14.0.1.el6.x86_64
bash-4.1$ sudo yum install kubelet-1.8.4 kubeadm-1.8.4
Loaded plugins: aliases, changelog, downloadonly, fastestmirror, kabi, presto, refresh-packagekit, security, tmprepo, verify, versionlock
Loading support for kernel ABI
Setting up Install Process
Loading mirror speeds from cached hostfile
 * ol6_latest: pd-yum-den-01.us.oracle.com
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.8.4-0 will be installed
--> Processing Dependency: kubectl >= 1.6.0 for package: kubeadm-1.8.4-0.x86_64
--> Processing Dependency: kubernetes-cni for package: kubeadm-1.8.4-0.x86_64
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: iptables >= 1.4.21 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: socat for package: kubelet-1.8.4-1.x86_64
--> Running transaction check
---> Package kubectl.x86_64 0:1.9.0-0 will be installed
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: iptables >= 1.4.21 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: socat for package: kubelet-1.8.4-1.x86_64
---> Package kubernetes-cni.x86_64 0:0.6.0-0 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: kubernetes-cni = 0.5.1
           Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
               kubernetes-cni = 0.3.0.1-0.07a8a2
           Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-0
           Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-1
           Installing: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
               kubernetes-cni = 0.6.0-0
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: iptables >= 1.4.21
           Installed: iptables-1.4.7-14.0.1.el6.i686 (@base)
               iptables = 1.4.7-14.0.1.el6
           Available: iptables-1.4.7-3.el6.i686 (ol6_latest)
               iptables = 1.4.7-3.el6
           Available: iptables-1.4.7-4.el6.i686 (ol6_latest)
               iptables = 1.4.7-4.el6
           Available: iptables-1.4.7-5.1.el6_2.i686 (ol6_latest)
               iptables = 1.4.7-5.1.el6_2
           Available: iptables-1.4.7-9.el6.i686 (ol6_latest)
               iptables = 1.4.7-9.el6
           Available: iptables-1.4.7-11.0.1.el6.i686 (ol6_latest)
               iptables = 1.4.7-11.0.1.el6
           Available: iptables-1.4.7-16.0.2.el6.i686 (ol6_latest)
               iptables = 1.4.7-16.0.2.el6
           Available: iptables-1.4.7-16.0.5.el6.i686 (ol6_latest)
               iptables = 1.4.7-16.0.5.el6
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: socat
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
kernel-uek-doc-3.8.13-118.13.3.el6uek.noarch is a duplicate with kernel-uek-doc-3.8.13-44.1.1.el6uek.noarch

**Comment by paulvanbladel** [comment]
Is there currently a workaround?

**Comment by dixudx** [comment]
@paulvanbladel Already filed a PR kubernetes/release#489 to fix this.

Currently for kubelet<1.9, you need to downgrade `kubernetes-cni` to `0.5.1` manually.

**Comment by paulvanbladel** [comment]
@dixudx Thanks a lot for the prompt help (not so familiar with apt). That did the trick.

**Comment by wsargent** [comment]
@dixudx I had to add 0.5.1-00 specifically `aptitude install kubernetes-cni=0.5.1-00`

**Comment by dixudx** [comment]
> add 0.5.1-00 specifically aptitude install kubernetes-cni=0.5.1-00

@wsargent Yes, this is the current workaround for kubelet<1.9.0. We may need to specify the exact version for `kubernetes-cni` before kubernetes/release#489 gets merged.

**Comment by luxas** [comment]
This bug was fixed long time ago.

**Comment by mozmut** [comment]
I think this issue should reopen because of last night update Fri, 05 Oct 2018 23:13:00 UTC

```
$ apt-get update && apt-get install -y kubeadm kubelet kubectl

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by 1e100** [comment]
Could it be a build race condition? I.e. some packages are already built, but others aren't yet? That's what the error seems to suggest. `1.12.1` DEBs weren't there just a few hours ago.

**Comment by bladedoyle** [comment]
Please re-open this, its still an issue:

```
$ sudo apt-get update && sudo apt-get install --reinstall -y kubelet kubeadm
...
The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
```

**Comment by igormilovanovic** [comment]
Still happening on ubuntu xenial:
```
root@master:~# apt-get update && apt-get install -y --allow-unauthenticated kubeadm kubelet kubectl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
 kubelet : Depends: kubernetes-cni (= 0.6.0) but 0.6.0-02 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mavimo** [comment]
https://github.com/kubernetes/kubernetes/issues/69489

**Comment by AnandShivaSingh** [comment]
When we can expect  a resolution for this issue?.Its seriously frustrating.

**Comment by aaronteague** [comment]
Temporary workaround:

`apt-get install kubernetes-cni=0.6.0-00`

**Comment by enthurohini** [comment]
It is happening because, `kubernetes-cni` lates version is `0.6.0-02` which is incompatible with kubeadm and kubelet. it can be solved by installing specific version of `kubernetes-cni` that is `0.6.0-00`. 
Command:
`apt-get install kubernetes-cni=0.6.0-00`

Solution found here: http://jee-appy.blogspot.com/2018/10/kubelet-depends-kubernetes-cni-060-but.html

**Comment by vistalba** [comment]
Same issue here. I just `apt-mark hold kubernetes-cni` beacuse version 0.6.0-00 was already installed. Just to not upgrade this package.

Please reopen.
