### ISSUE TITLE
kube-dns does not work

### ISSUE THREAD

**Issue by ZhengRongTan** [kubernetes/kubernetes#57332]
**Env**:

kubernetes 1.7.11
docker 1.12.6
flannel 0.7.1

**What happened**:

kube-dns does not work, see below:

[root@k8s-node-1 ~]# docker exec -it busybox /bin/sh
/ # cat /etc/resolv.conf
nameserver 169.169.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
/ # nslookup kubernetes
Server:    169.169.0.10
Address 1: 169.169.0.10

nslookup: can't resolve 'kubernetes'

**sidecar log**:

[root@k8s-master kubedns]# kubectl --server=https://10.202.107.30:6443 --certificate-authority=/var/run/kubernetes/ca.crt --client-certificate=/var/run/kubernetes/cs_client.crt --client-key=/var/run/kubernetes/cs_client.key logs -n kube-system pods/kube-dns-4290396712-47vvj -c sidecar
ERROR: logging before flag.Parse: I1218 13:51:58.237796       1 main.go:49] Version v1.14.0-2-g38b2ca3
ERROR: logging before flag.Parse: I1218 13:51:58.238227       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
ERROR: logging before flag.Parse: I1218 13:51:58.238295       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
ERROR: logging before flag.Parse: I1218 13:51:58.238376       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
ERROR: logging before flag.Parse: W1218 14:07:18.501915       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:49567->127.0.0.1:53: read: connection refused
ERROR: logging before flag.Parse: W1218 14:07:23.502392       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37431->127.0.0.1:53: read: connection refused
ERROR: logging before flag.Parse: W1218 14:07:28.502818       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:41912->127.0.0.1:53: read: connection refused

the configuration file are downloaded from th official website.

SOS. Can someone point me in the right direction? Have spent a lot of time trying to figure this one out.
Thanks in advance
__

**Comment by ZhengRongTan** [comment]
kubelet added params --cluster-dns=169.169.0.10 --cluster-domain=cluster.local

**Comment by bowei** [comment]
Can you use `dig +verbose`?

**Comment by ZhengRongTan** [comment]
after install the docker in the machine, the docker engine will add a policy "FORWARD DROP", let the iptables -FORWARD ACCEPT , then fixed
