### ISSUE TITLE
Examples/K8PetStore: Adding   add persistence to k8petstore (used also in soak tests)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#5734]
We want to add persistence layer to k8petstore, so that redis transactions can sink into mysql or cassandra.  that will allow for soak testing of disk as well as memory/cpu which is already done.

**Comment by mbforbes** [comment]
Naive question: Is the purpose for testing? Or is this needed fundamentally as a storage feature as well?

**Comment by roberthbailey** [comment]
Soak testing.

**Comment by CaptTofu** [comment]
I will be working on a container that has percona xtradb cluster for just this thing, per discussion with jayunit100

**Comment by jayunit100** [comment]
It's for both. For testing having MySQL is synergistic with Patrick's goals, but also, for tests it will allow us to create churn on the disks in real world access patterns

**Comment by jayunit100** [comment]
@CaptTofu any thoughts on mysql side of this ? or postgre is ok?
