### ISSUE TITLE
Some API documentation contains broken HTML

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#57362]
/kind bug

**What happened**:
Some API documentation contains broken HTML. Some type comments in the Go source use syntax that is being interpreted as HTML, such as `<topologyKey>` in [PodAffinityTerm](https://github.com/kubernetes/api/blob/1afd21c1b728221c821dfe71c17ce5ee8061e31b/core/v1/types.go#L2608)

Examples:

- https://kubernetes.io/docs/api-reference/v1.8/#podaffinityterm-v1-core
- NodeSpec.providerID, in 
  https://kubernetes.io/docs/api-reference/v1.8/#nodespec-v1-core

**What you expected to happen**:
Generated HTML should match the code comments, as it does on godoc.org. i.e. https://godoc.org/k8s.io/api/core/v1#PodAffinityTerm

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig docs

**Comment by steveperry-53** [comment]
@misterikkit I should be able to take a look at this in January. It involve fixing the doc generation code at [kubernetes-incubator/reference-docs/gen-apidocs](https://github.com/kubernetes-incubator/reference/docs/gen-apidocs).

**Comment by adnavare** [comment]
Hi @steveperry-53 : I can look into this issue if you are fine?

**Comment by chenopis** [comment]
@steveperry-53 submitted a fix, which has been merged, so this can be closed.

**Comment by misterikkit** [comment]
@steveperry-53 This is fixed, right?

**Comment by steveperry-53** [comment]
Yes this is fixed.
