### ISSUE TITLE
"--raw cannot read from a url" raised if the filename has a prefix "http"

### ISSUE THREAD

**Issue by niuzhenguo** [kubernetes/kubernetes#57370]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Currently when run kubectl create with --raw, it will raise "--raw cannot read from a url " if the filename has a prefix "http", which is not proper as we may have filenames like "httptest" or similar.

**What you expected to happen**:
Restrict the url check with "https://" or "http://" prefix.

**How to reproduce it (as minimally and precisely as possible)**:
Run 'kubectl create --raw URI -f' with a filename which has a "http" prefix.

**Comment by liggitt** [comment]
--raw should start with `/`

**Comment by liggitt** [comment]
the message could be improved, but I think the check is reasonable (I'd actually change it to error if the raw path doesn't start with `/`)

**Comment by niuzhenguo** [comment]
@liggitt This is the filename url check, not the raw path. I think you mean this https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/create.go#L138-L139
