### ISSUE TITLE
Time window for PodSecurityPolicy

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#57373]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
For large k8s clusters for thousands of customers, the maintain of PSP would be one significant issue for operators as different customers always send requests on requesting allowable host paths, privileges, capabilities for pods for debug/trace purpose. 
For cluster operators, they have to create PSPs for different customers, and delete the PSPs after the use of them. 
Operators have to have another system to trace which PSPs are created for which customers, and when to delete them, and _evict pods_ which have leaked permissions.

**What you expected to happen**:
1. A time window can be defined for PSPs. The PSPs are active and customers can create allowable privileged pods.
2. After time window exceeded, the pods, which have leaked privileges, are evicted by evict manager.
3. PSPs with time window can be garbage collected by PSP GC.

/cc @kubernetes/sig-auth-feature-requests

**Comment by php-coder** [comment]
> A time window can be defined for PSPs. The PSPs are active and customers can create allowable privileged pods.

It doesn't seem to be related to a PSP itself but rather to access to a PSP. User/service account has access to the particular PSP while a `RoleBinding`/`ClusterRoleBinding` that grants such an access exists. In other words, you want to manage life time for a binding rather for a PSP.

> After time window exceeded, the pods, which have leaked privileges, are evicted by evict manager.

When you (or your script) revokes access to a PSP, it's possible to find all the pods that were run by a user/SA and stop them. I'm trying to say, that it's possible to do at this time with existing API.

It also possible to specify `spec.activeDeadlineSeconds` to kill containers after some time, that together with `restartPolicy: Never` allows to run a Pod only once and to be run only for a some time. These 2 fields can be enforced by custom admission plugin. The only tricky moment here is to account for pod restarts during a lifetime.

**Comment by armstrongli** [comment]
> In other words, you want to manage life time for a binding rather for a PSP.

Yes from this perspective. To bring the feature to manage role binding and cluster role binding, the models would be like 
* time windows
* cluster role bindings
* role bindings
* PSP(s)

It brings 
* independent models
* one admission controller to verify pod creation
* one garbage collector to recycle role bindings, cluster role bindings[must have]
* evict manager to evict pods which have privileged permissions

And it doesn't make sense to add time window to role binding or cluster role binding.

> It also possible to specify spec.activeDeadlineSeconds to kill containers after some time, that together with restartPolicy: Never allows to run a Pod only once and to be run only for a some time. 

The users are free to use any pod specs as they want. The pods can get restarted at anytime. It is one work around to use `activeDeadlineSeconds` & `restartPolicy` rather than a solution.

The expected reactions on the deadline of revoking permissions is to evict the pods which are using extra capabilities in the deleted PSP.

**Comment by liggitt** [comment]
Extra PSP permissions aren't the type of thing that can be easily cleaned up by a controller. A privileged pod with host path access can set up things that live outside the pod and are not cleaned up when the pod is removed.

Rather than trying to grant/revoke/scrub PSP permissions dynamically, I'd suggest partitioning permissions by namespace, and controlling which nodes those namespaces can schedule to with the PodNodeSelector admission plugin.
