### ISSUE TITLE
Node affinity on PodSecurityPolicy

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#57372]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
There're different groups of nodes in one k8s cluster, and not all the nodes are open to every user, or open on the PSP to all the nodes. e.g. one service account has privileged permission. It means that the service account can create any pod on any node, and can act as root to the OS.

**What you expected to happen**:
it would be like that PSP can be defined with node selector. With this definition, one pod, which has the allowed PSP actions, is scheduled to the selected nodes, instead of other nodes.

/cc @kubernetes/sig-auth-feature-requests

**Comment by deads2k** [comment]
Can't you already achieve this effect by placing the node selector scheduling restrictions on the namespace containing your service account?  I like the idea of keeping my pod scheduling decisions separate from my PSP decisions, since it keeps the number of interactions and intersections smaller.

**Comment by armstrongli** [comment]
@deads2k 
I like the idea, too, to keep the scheduling out of PSP decisions. There're some limitations on the node selector: 
* users can modify their namespace and change the default actions on namespace - node selector
* there can be spec conflicts between the node selector defined by podNodeSelector and the pods' specs

with podNodeSelector, it means limit the namespace to bind to one group of nodes to schedule pods on nodes.

The PSP change is to define the white list to the nodes which are allowed to schedule the privileged(or special host path, or run as specific users) pods. For regular pods, they are not impacted on schedule.

**Comment by deads2k** [comment]
> users can modify their namespace and change the default actions on namespace - node selector

Using standard RBAC rules they cannot. We were very careful about that.



> there can be spec conflicts between the node selector defined by podNodeSelector and the pods' specs

The admission plugin rejects those.

**Comment by hzxuzhonghu** [comment]
I agree with Namespace node selector.

**Comment by armstrongli** [comment]
@deads2k @hzxuzhonghu Thank you for your suggestions.
