### ISSUE TITLE
ReadOnly/Writable AllowedHostPath for PodSecurityPolicy

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#57371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
For `AllowedHostPath`, the white list would allow any pod to have the path mounted to pods. There're no limitations on the path. It means that any pod can read/write data to the host path. For regular log path, it can be accepted. For corner case that the path have corp root ca files(or this kind of file), it is a risk to have every pod to have write access.

**What you expected to happen**:
it would be like host path can be defined as `ReadOnly` or not. For readonly host paths, all pods which have write mount requests are rejected as `not allow to mount readonly path as writable`. For none-readonly white list, the paths can be mounted as usual.

/cc @kubernetes/sig-auth-feature-requests

**Comment by resouer** [comment]
PSP only remind me of game stuff if you do not claim it as Pod Security Policy (as I guess) ... 

Mind to give it a name in all issues you filed with "PSP" :)

**Comment by ericchiang** [comment]
cc @jhorwit2

**Comment by jhorwit2** [comment]
I started on something here https://github.com/oracle/kubernetes/pull/11 but haven't had time to get back to it :/ I was hoping to find time in 1.9 cycle.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/features/issues/5
