### ISSUE TITLE
CrashLoopBackOff error

### ISSUE THREAD

**Issue by Vidyayadav20** [kubernetes/kubernetes#57388]
I have created Azure Container Registry where I have pushed one image but while deploying application using yaml file it is giving crashLoopBackOff error.
after running describe pod command getting following message 

  Type     Reason                 Age                From                           Message
  ----     ------                 ----               ----                           -------
  Normal   Scheduled              46s                default-scheduler              Successfully assigned hello-world to k8s-agent-2cad2c16-1
  Normal   SuccessfulMountVolume  46s                kubelet, k8s-agent-2cad2c16-1  MountVolume.SetUp succeeded for volume "default-token-wl06v"
  Normal   Pulling                45s                kubelet, k8s-agent-2cad2c16-1  pulling image "acrvidya.azurecr.io/hello-world:redis-v1"
  Normal   Pulled                 39s                kubelet, k8s-agent-2cad2c16-1  Successfully pulled image "acrvidya.azurecr.io/hello-world:redis-v1"
  Normal   Created                24s (x3 over 39s)  kubelet, k8s-agent-2cad2c16-1  Created container
  Normal   Started                24s (x3 over 39s)  kubelet, k8s-agent-2cad2c16-1  Started container
  Normal   Pulled                 24s (x2 over 38s)  kubelet, k8s-agent-2cad2c16-1  Container image "acrvidya.azurecr.io/hello-world:redis-v1" already present on machine
  Warning  BackOff                8s (x4 over 37s)   kubelet, k8s-agent-2cad2c16-1  Back-off restarting failed container
  Warning  FailedSync             8s (x4 over 37s)   kubelet, k8s-agent-2cad2c16-1  Error syncing pod

Any solution for this ? what might be the issue with this ?

**Comment by andyzhangx** [comment]
`docker run -d acrvidya.azurecr.io/hello-world:redis-v1` on agent VM to make sure the container would work?

**Comment by jdumars** [comment]
@Vidyayadav20 any update on this?
