### ISSUE TITLE
Getting start guide for Vagrant doesn't work

### ISSUE THREAD

**Issue by juzna** [kubernetes/kubernetes#5739]
I followed the [getting start guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md) and encountered several problems:

## running containers failed
```bash
$ ./cluster/kubectl.sh run-container my-nginx --image=dockerfile/nginx --replicas=3 --port=80
Running: ./cluster/../cluster/vagrant/../../platforms/darwin/amd64/kubectl --auth-path=/Users/juzna/.kubernetes_vagrant_auth run-container my-nginx --image=dockerfile/nginx --replicas=3 --port=80
unknown flag: --image
```

Error message is very confusing, complains about unknown flag, but that flag is correct. When I tried the same just without --replicas and without  --port, the command succeeded.

## salt command not found
Tutorial says I should run:
`$ sudo salt '*minion-1' cmd.run 'docker images'`

But salt command is not present on my Mac OS X, and the tutorial doesn't say anything about it. Where should I get it? It worked when I ssh-ed to the vagrant master machine: `vagrant ssh master`.

## some services are running, guide says they should not
After starting the first nginx container, the guide says `cluster/kubectl.sh get services` should say no services are running. But is shows some services already:
```
$ cluster/kubectl.sh get services
Running: cluster/../cluster/vagrant/../../platforms/darwin/amd64/kubectl --auth-path=/Users/juzna/.kubernetes_vagrant_auth get services
NAME                LABELS                                    SELECTOR            IP                  PORT
kubernetes          component=apiserver,provider=kubernetes   <none>              10.247.0.2          443
kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.247.0.1          80
skydns              k8s-app=skydns                            k8s-app=skydns      10.247.0.10         53
```
I don't know why they are there.

**Comment by juzna** [comment]
Also, all the guide mentions command `cluster/kubectl.sh`, but then it links to [guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md) which uses only `kubectl`. Such command doesn't exist on my Mac OS X, where do I find it?

**Comment by uruddarraju** [comment]
sudo salt '*minion-1' cmd.run 'docker images' should be run on your master

```
kubernetes          component=apiserver,provider=kubernetes   <none>              10.247.0.2          443
kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.247.0.1          80
skydns              k8s-app=skydns                            k8s-app=skydns      10.247.0.10         53
```

These are the core kubernetes system services which are required by default.

After you do make release, you would find your kubectl command in 

```cluster/../cluster/vagrant/../../platforms/darwin/amd64/```

**Comment by mbforbes** [comment]
@juzna did @uruddarraju's comment fully address the second two issues you were having?

It looks like maybe your question about the `--image` flag is remaining. I believe this flag may have changed around v9 or v10. Are you running a recent version of kubernetes? (`kubectl version`)

**Comment by gravis** [comment]
May I add, that the install script isn't working for me?

```
$ export KUBERNETES_PROVIDER=vagrant; wget -q -O - https://get.k8s.io | bash
$ 
$ echo $?
$ 0
```

The problem seems to be with curl CAs:

```
Downloading kubernetes release  to /Users/plafoucriere/kubernetes/kubernetes.tar.gz
--2015-04-28 10:10:04--  https://storage.googleapis.com/kubernetes-release/release//kubernetes.tar.gz
Resolving storage.googleapis.com... 173.194.40.140, 173.194.40.139, 173.194.40.138, ...
Connecting to storage.googleapis.com|173.194.40.140|:443... connected.
ERROR: cannot verify storage.googleapis.com's certificate, issued by 'CN=Google Internet Authority G2,O=Google Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to storage.googleapis.com insecurely, use `--no-check-certificate'.
Unpacking kubernetes release
Creating a kubernetes on gce...
install.sh: line 49: cd: kubernetes: No such file or directory
install.sh: line 50: ./cluster/kube-up.sh: No such file or directory
Kubernetes binaries at /Users/plafoucriere/kubernetes/kubernetes/cluster/
You may want to add this directory to your PATH in $HOME/.profile
Installation successful!
```

If the google CA should be installed somewhere, it should be documented as well.

Configuration:

* Mac OS 10.10.3
* wget from homebrew (GNU Wget 1.16.3 built on darwin14.1.0.)

Removing wget from the install script solved it. Do I need to open another issue this? (title will be pretty much the same...)
thanks

**Comment by chris-rock** [comment]
The easiest way to install kubectl on mac:

```bash
# Mac
$ wget https://storage.googleapis.com/kubernetes-release/release/v0.17.0/bin/darwin/amd64/kubectl -O /usr/local/bin/kubectl
$ chmod +x /usr/local/bin/kubectl
$ kubectl version

```

**Comment by mcortinas** [comment]
I try it using vagrant in Mac Os X (yosemite) recently and i kubernetes-master starts without the main services such as kube-apiserver and kube-controller-manager.
Moreover, the modifier --show-time in salt binary is deprecated, I think.

**Comment by thomschke** [comment]
same problem with pre-release v0.17.1 (i'm using MacOS 10.10.3)

**Comment by brona90** [comment]
@chris-rock 

I believe the easiest way to install kubectl is using brew: 

```{r, engine='bash', count_lines}
$ brew install kubernetes-cli
```
