### ISSUE TITLE
Error: 'tls: oversized record received with length 20527' Trying to reach: 'https://10.32.0.6:9090/'

### ISSUE THREAD

**Issue by sachinar** [kubernetes/kubernetes#57395]
Getting this error while running kube-dashboard 

Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.32.0.6:9090/'
@kubernetes

**Comment by dims** [comment]
Can you please file this issue in https://github.com/kubernetes/dashboard/issues ?

/close
