### ISSUE TITLE
Unable to update cronjob image using kubectl set image

### ISSUE THREAD

**Issue by okke-formsma** [kubernetes/kubernetes#57393]
/kind feature

**What happened**:
I would like to use a newer version of my image in a cronjob, but I can't update the cronjob template using 'kubectl set'

**What you expected to happen**:
I would expect to issue a command like the following, but it's not possible to update a cronjob template.

    kubectl set image cronjob python=python:3.5

**How to reproduce it (as minimally and precisely as possible)**:
create a cronjob and try to update the image that is pulled for each job.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
azure
- Install tools:
acs-engine

**Comment by okke-formsma** [comment]
I have found the following way to update the image;

    kubectl patch -f definition.yaml --type=json -p='[{"op":"replace", "path": "/spec/jobTemplate/spec/template/spec/containers/0/image", "value":"python:3.5"}]"

Still it would be nice to use the same tool (kubectl set image) for both deployments and cronjobs.

**Comment by xingzhou** [comment]
yeap, the ```UpdatePodSpecForObject``` method does not handle cronjob situation. In addition, ```CronJob``` does not contain a direct Pod template spec, instead, it contains ```JobTemplate``` which contains the pod spec. I will try to give a fix on this then.

**Comment by webbrandon** [comment]
👍

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/57742

**Comment by richtera** [comment]
Which version will contain the new kubectl set image support for cronjobs? Is this just a command line patch or also system images?

**Comment by richtera** [comment]
@calebmcelroy oh cool. Thanks I'll be able to fix my scripts and simplify things

**Comment by yashsaini77** [comment]
> @richtera, it's in v1.10. Seem to be just a command line patch.
> 
> This worked for me:
> `kubectl set image cronjob/cronjobmetadataname python=python:3.5`
> 
> I know this is an older thread but hopefully it helps someone else!

what is exactly the cronjobmetadataname here
