### ISSUE TITLE
Support service.spec.sessionAffinity mode that allows affinity based on arbitrary headers

### ISSUE THREAD

**Issue by pjfanning** [kubernetes/kubernetes#57402]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind feature
/sig node

Problem:
The current `ClientIP` mode is based on the `X-Forwarded-For` header. It would be nice to support affinity based on other headers.

Proposed Solution:
In this proposed solution, the idea is to take the X-Tenant HTTP header, hash it and have the Service apply sessionAffinity based on this hash.
service.spec.sessionAffinity=HttpHeader
service.spec.sessionAffinityConfig.headerName=X-Tenant

Page to Update:
https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by pjfanning** [comment]
/lifecycle/frozen

**Comment by thockin** [comment]
Service is an L4 concept.  We can not impose L7 processing in Services.  It's not based on XFF header, it's based on client IP.
