### ISSUE TITLE
kube-apiserver cannot recover under load

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#57405]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
@kubernetes/sig-scalability-bugs 
@kubernetes/sig-api-machinery-bugs 
/priority important-longterm

**What happened**:

In https://github.com/kubernetes/kubernetes/issues/56714#issuecomment-352756379 I killed `kube-apiserver` process in a 5000 node cluster under load (in the middle of replication controllers for a total of 150k pods ramping up).

It is not able to recover. It seems that:
1. (presumably) its caches are cold, so
2. it is no longer able to respond to all requests (most responses in its log are 429s), I also see some 5xxs, so
3. its container liveness probe is failing, so it is being periodically killed by kubelet, so
4. it is not able to stay alive long enough to rebuild its caches, so - back to (1)

**What you expected to happen**:

It should have enough breathing room to recover. Probably by a combination of:
1. bumping the `initialDelaySeconds` in its `livenessProbe`
2. clients (in particular kubelet) using exponential backoff

**How to reproduce it (as minimally and precisely as possible)**:

Bring up a 5k-node cluster, start sig-scalability density test. When the number of running pods reported by the test reaches 100k, kill the `kube-apiserver` process on the master.

**Comment by porridge** [comment]
FWIW, I bumped `initialDelaySeconds` to an hour, but there is almost no sign of recovery after half an hour so far.

**Comment by porridge** [comment]
Looks like I'm able to make it recover by blackholing all incoming kubelet traffic with iptables on the master, and trickling it back with a veeeeery tiny teaspoon (will take hours to complete).

**Comment by dims** [comment]
cc @shyamjvs

**Comment by mbohlool** [comment]
> Looks like I'm able to make it recover by blackholing all incoming kubelet traffic with iptables on the master, and trickling it back with a veeeeery tiny teaspoon (will take hours to complete).

Can you elaborate on how you fix this?

**Comment by porridge** [comment]
@mbohlool I did the following:
- in one ssh session to the master I ran a combination of `tail` and `awk` on `kube-apiserver.log` which counted the ratio of 429 to non-429 statuses in the last several dozen thousand responses, in a loop - as a status check
- in another session:
  - I retrieved the list of /24 netblocks in which the clients (mostly kubelets) resided from `kube-apiserver.log`. Luckily with 5k nodes there were quite a few of these netblocks (on the order of a hundred) so I was able to use them as a unit of blackholing that was not too big.
  - for each such netblock I ran `iptables -A INPUT -s $block -j DROP` (which blackholed nearly all traffic)
  - then I ran `iptables -D INPUT 1` a few times (which added back an initial trickle)
  - waited for the other session to show near-zero 429 response rate
  - started loop such as `while sleep $N; do iptables -D 1 INPUT 1;done` which gradually increased the trickle
  - looked at the status check and periodically adjusted $N up and down to keep a decent (~few %) rate of 429 responses
  - once I got rid of most of the blackholes, I stopped the loop and removed the rest manually, to avoid removing the entries that were there before

**Comment by timothysc** [comment]
If the kubelets are no-longer respecting backoff on phone home that is an issue.  There has been a ton of work in this area over the years.
