### ISSUE TITLE
Kubernetes does not flush logs in real-time

### ISSUE THREAD

**Issue by kevincvlam** [kubernetes/kubernetes#57414]
/kind bug
@kubernetes/sig-instrumentation-bugs

**What happened**:

Ran a container that does some work, logging was suppressed then got dumped suddenly when calling kubectl logs on the pod.

**What you expected to happen**:

Logging should be available as the the logs are produced. Note that when running this container locally with docker the logs are seen as expected.

**How to reproduce it (as minimally and precisely as possible)**:

We have a container that is running and downloads some files from GCS and then processes them, using standard output via python print() statements to update progress.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4-gke.0
- Cloud provider or hardware configuration: GKE

**Comment by kevincvlam** [comment]
@kubernetes/sig-instrumentation-bugs

**Comment by yujuhong** [comment]
Might be related to #54205. Did this happen in an Alpha cluster?

**Comment by kevincvlam** [comment]
We don't use the -f option, but yes this happened on an Alpha cluster

**Comment by yujuhong** [comment]
I think this is fixed now in GKE by disabling the problematic alpha feature (cc @mindprince in case I'm wrong).
Could you create a new Alpha cluster to see if the problem exists?

**Comment by kevincvlam** [comment]
Thank @yujuhong! I just tried this on a brand new alpha cluster on v1.8.4-gke.1. Unforunately, saw the same issue where logs weren't being made availble via kubectl logs.

**Comment by mindprince** [comment]
> We don't use the -f option

This is different than https://github.com/kubernetes/kubernetes/issues/54205 then.

**Comment by mindprince** [comment]
>  logging was suppressed then got dumped suddenly when calling kubectl logs on the pod.

What do you mean logging was suppressed? It would be helpful if there's a simple reproducible test case.

**Comment by kevincvlam** [comment]
As in, there is some logging output that I expect to see as the python script progresses (from print()) statements, but when run on kubernetes vs. docker I don't see the logging output, and at some point it is suddenly returned by kubectl logs.

Yes, this is running some internal code.. I can see about trying to find a simple way to reproduce it. Hopefully that above helps, and thanks for your help!

**Comment by kevincvlam** [comment]
I'm not sure if this exactly reproduces my error. But here's something that was unexpected, and seems at least strongly releated.

I created a simple python container that would print('Hello') every 3 seconds. Created a simple pod that created the container and the logs didn't show up via kubectl.

Steps to reproduce:

1. Create container from Dockerfile and hello.py:

Dockerfile:
`FROM python:3.6.3
COPY hello.py .
CMD python3 hello.py`

hello.py:
`import time

while True:
    print('hello')
    time.sleep(3)`

2. Create pod from yaml:

apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: <your-image>
    imagePullPolicy: Always

3. Observe that kubectl logs hello doesn't show any output. 

A few more things to note:
If I do something like `kubectl run -it hello --image=<my-image>` I see the python script running properly and also the pod created shows the logs as expected when calling kubectl logs on it. (Though this creates a deployment iiuc). 

Hope that helps narrow it down a bit!

**Comment by kevincvlam** [comment]
Creating the above, I figured out and was able to fix our issue via setting 'tty': True on our pods. Thanks! 

Will close issue.

**Comment by jeremysprofile** [comment]
Another solution, for future searchers willing to change their `Dockerfile`, is adding
```
ENV PYTHONUNBUFFERED=1
```
