### ISSUE TITLE
PodNodeSelector and PodTolerationRestriction feature status is unclear

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#57424]
/kind bug

@kubernetes/sig-scheduling-bugs 

Newer admission controllers generally call out when they're alpha/beta. While `PodNodeSelector` and `PodTolerationRestriction` don't have an explicit status, they rely on alpha annotations.

https://kubernetes.io/docs/admin/admission-controllers/

```
scheduler.alpha.kubernetes.io/node-selector
scheduler.alpha.kubernetes.io/defaultTolerations
scheduler.alpha.kubernetes.io/tolerationsWhitelist
```

Are these alpha features? I've seen them come up a lot lately, particularly in the context of multitenancy and devoted nodes.

https://docs.google.com/document/d/1jAcsC4sLgEV9__TdgJrMvPa3G73G62tFtMcKQgeIlHM/edit#

**Comment by resouer** [comment]
@ericchiang The last two are introduced in #30302 and does not follow alpha feature practices (or probably too early when there're no such practices ).

The first one is even earlier #24980

We may need to remove them to `well_known_labels`, and also make them GA, and fix their names since they actually hits #51246 ...

**Comment by ericchiang** [comment]
@colemickens has volunteered to take this.

/assign @colemickens

**Comment by embano1** [comment]
Agree with @ericchiang that this is confusing at the moment. Reading [Extensible Admission is Beta](http://blog.kubernetes.io/2018/01/extensible-admission-is-beta.html) confused me when I read the code on PodNodeSelector 

```go
// The annotation key scheduler.alpha.kubernetes.io/node-selector is for assigning
// node selectors labels to namespaces
var NamespaceNodeSelectors = []string{"scheduler.alpha.kubernetes.io/node-selector"}
```
https://github.com/kubernetes/kubernetes/blob/v1.9.2/plugin/pkg/admission/podnodeselector/admission.go#L41

Glad this is being tracked.

**Comment by liggitt** [comment]
* Should probably drop the alpha from the annotations and include in well known annotations constants
* Also need to update the admission plugin config to read from a versioned config object

**Comment by wackxu** [comment]
@liggitt I can help do it. Can you take a look at https://github.com/kubernetes/kubernetes/issues/58198

**Comment by colemickens** [comment]
Hey @wackxu I'm working on this right now. Just a heads up.

**Comment by wackxu** [comment]
> Should probably drop the alpha from the annotations and include in well known annotations constants
Also need to update the admission plugin config to read from a versioned config object

@colemickens Hi, The second I have done almost half work, Can I continue on the second and the first you can continue working on.

**Comment by colemickens** [comment]
Sounds great. Thanks @wackxu!

**Comment by colemickens** [comment]
@wackxu I forgot we had discussed this. The PRs I have open for PNS/PTR (#60284, #60285) have the versioned config changes (and tests) included.

**Comment by adampl** [comment]
Does anyone know if anything has been done about it?

**Comment by adampl** [comment]
@ericchiang could you reopen?
