### ISSUE TITLE
unable to use azure disk in StatefulSet since /dev/sd* changed after detach/attach disk

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#57444]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
In a customer [case](https://github.com/Azure/acs-engine/issues/1918), customer is unable to use azure disk in StatefulSet since /dev/sd* changed after detach/attach disk. 
Currently we are using `/dev/sd*` to reference the data disk which could be changed in some condition, see code: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_common_linux.go#L140

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. create 5 StatefulSet with 1 replica and 1 azure disk mount each
2. delete 1 StatefulSet and recreate the same StatefulSet 
3. There would be azure disks could not be usable since /dev/sd* changed
Update:
It seems that on azure china, this issue could repro very easily.

**Anything else we need to know?**:
I have checked the official doc: [Troubleshoot Linux VM device name change](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/troubleshoot-device-names-problems)
`device names could be changed after you restart a Linux VM or reattach the data disks`

**Environment**:
- Kubernetes version (use `kubectl version`): from v1.6.0 to v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

@rootfs @brendandburns @khenidak
@kubernetes/sig-azure-misc 
I am working on a fix for this issue, would use `/dev/disk/by-id/` instead  of `/de/sd*`

**Comment by khenidak** [comment]
We changed how we find disks on nodes https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_common_linux.go#L69 quite some time back. What server version is this?

**Comment by andyzhangx** [comment]
@khenidak yes, I have already checked the code, the point is we are still using `/dev/sd*` to "mount -bind" k8s path, while `/dev/sd*` could be changed when VM is attach/detaching data disks, see [Troubleshoot Linux VM device name change](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/troubleshoot-device-names-problems)
And I have also checked related AWS, GCE code, they are using `/dev/disk/by-id/` other than `/dev/sd*`, see 
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/aws_ebs/attacher.go#L172

This issue could be stably repro on Azure China, while I could not repro that on other region up to now.
I have already got a fix for this, still in testing now.

**Comment by andyzhangx** [comment]
also add @rootfs for awareness, I am working on a fix to use `/dev/disk/by-id/` other than `/dev/sd*`.

**Comment by malachma** [comment]
@andyzhangx I would not use "/dev/disk/by-id" instead utilize the special UDEV rules we have created for our VMs --> https://github.com/Azure/WALinuxAgent/blob/master/config/66-azure-storage.rules
They have the advantage that they create symlinks for all of the disks attached to the VM and the LUN assigned to a disk remains the same. 
The sysmlinks you find under /dev/disk/azure. For a master-node you will see a layout like the following.

```
/dev/disk/azure# ls
resource  resource-part1  root  root-part1  scsi1
```
In scsi1 you find the additonal (data) disks
```
ls -l scsi1/
total 0
lrwxrwxrwx 1 root root 12 Dec 20 13:55 lun0 -> ../../../sdc
lrwxrwxrwx 1 root root 13 Dec 20 13:56 lun0-part1 -> ../../../sdc1
```
A newly assigned disk is goign to appear as lun1,lun2,...
Since we are not able to guaranty the order in which disks get assigned to a VM I would go and base the code on this already created layout

**Comment by andyzhangx** [comment]
@malachma thanks for the check. So do you mean we use `/dev/disk/azure/scsi1/lun0`, `/dev/disk/azure/scsi1/lun1` instead? actually in Azure VM with UDEV rules created, they have no difference, they link to the same /dev/sd* (see below layout). While I also got some customer cases(e.g. coreos, see #54334), they don't have such UDEV rules created, which means `/dev/disk/azure/` does not exist, **I would say `/dev/disk/by-id` would be more common, every linux distro would that path.**
From debugging perspective, the `/dev/disk/azure` path is more intuitive.

```
$ tree /dev/disk/azure
/dev/disk/azure
â”œâ”€â”€ resource -> ../../sdb
â”œâ”€â”€ resource-part1 -> ../../sdb1
â”œâ”€â”€ root -> ../../sda
â”œâ”€â”€ root-part1 -> ../../sda1
â””â”€â”€ scsi1
    â”œâ”€â”€ lun0 -> ../../../sdi
    â”œâ”€â”€ lun1 -> ../../../sdm
    â”œâ”€â”€ lun2 -> ../../../sdk
    â”œâ”€â”€ lun3 -> ../../../sdd
    â”œâ”€â”€ lun4 -> ../../../sdn
    â”œâ”€â”€ lun5 -> ../../../sdo
    â””â”€â”€ lun6 -> ../../../sdp

$ tree /dev/disk/by-id
/dev/disk/by-id
â”œâ”€â”€ scsi-14d53465420202020084897c5d3b63e40b33e5366948bea04 -> ../../sda
â”œâ”€â”€ scsi-14d53465420202020084897c5d3b63e40b33e5366948bea04-part1 -> ../../sda1
â”œâ”€â”€ scsi-14d534654202020203029d99a5aa748269b06442f6ff17647 -> ../../sdn
â”œâ”€â”€ scsi-14d534654202020204813c2ad85a081ccc753db38576d452b -> ../../sdo
â”œâ”€â”€ scsi-14d5346542020202084f9ce759d867c3235a5878d74ca8876 -> ../../sdm
â”œâ”€â”€ scsi-14d53465420202020b69a86866e103d32bbb0719a1d84ee7d -> ../../sdk
â”œâ”€â”€ scsi-14d53465420202020c3074656d0702ece07ad335e264627bd -> ../../sdd
â”œâ”€â”€ scsi-14d53465420202020df342a4501f6891002f0813bfb81aa3f -> ../../sdp
â”œâ”€â”€ scsi-14d53465420202020f33d0b57aa587d1001d2e7bb08b525ed -> ../../sdi
â”œâ”€â”€ scsi-3600224808ff93eba1a06b32e48b5e483 -> ../../sdb
â”œâ”€â”€ scsi-3600224808ff93eba1a06b32e48b5e483-part1 -> ../../sdb1
â”œâ”€â”€ wwn-0x600224808ff93eba1a06b32e48b5e483 -> ../../sdb
â””â”€â”€ wwn-0x600224808ff93eba1a06b32e48b5e483-part1 -> ../../sdb1
```

**Comment by andyzhangx** [comment]
BTW, I have a azure disk debugging doc: [Debug Azure disk attachment issue](https://github.com/andyzhangx/Demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md) which uses `/dev/disk/azure`, it's really intuitive for debugging perpurse.

**Comment by malachma** [comment]
@andyzhangx it is right that at the end we point to /dev/sdi like in the sample above

> lun0 -> ../../../sdi

the advantage we have with the lun0 is that it acts as an abstraction layer where we can be sure that an application is always utilizing the disk with lun0, independent what actuall device name gets assigned to it. So at the moment it is _../../../sdi and after a reboot it could become ../../../sdk_. But thanks to these UDEV rules /dev/disk/azure/scsi1/lun0 will always point to the right device behind it.

I also would favour the usage of the lun over the disk-id if from a maintanance/support point of view as we can directly correlate what lun belongs to what disk. Otherwise I have at first fo to the VM directly to find out what disk might have an issue

Regarding the centos issue, if we have the waagent installed on it then those new UDEV rules should be available as well. So it wonders me that we do not have them working well. At least I had not seen any customer SR who had reported an issue with those rules specifically on CentOS

**Comment by andyzhangx** [comment]
@malachma It's not centos, it's coreos issue, see https://github.com/kubernetes/kubernetes/issues/50150
If we use `/dev/disk/azure/scsi1/lun0`, then we would heavily depends on UDEV rules.

**Comment by malachma** [comment]
@andyzhangx I agree that one depends on these special UDEV rules in this case , but on each Azure VM the agent is to be installed anyway, so that is background why I suggested to use the LUNs

**Comment by khenidak** [comment]
I think @malachma proposal is the cleanest and safest. However we will have to tell *all* Azure users that they have to have azure UDEV rules configured in nodes, even if WAAGENT is not installed.

**Comment by andyzhangx** [comment]
I did hit the issue, using an ACS based Kubernetes cluster running 1.7.7. We are already in the process of moving over to AKS based clusters, so was simply hoping that there would be some escalated effort to bring 1.8.7 into AKS given that the azure-disk provisioner is the default StorageClass.Not sure if you are looking for any more debug info at this time, but I still have the affected pod active and should be able to get you some more information, so just let me know.

@peskybp that's great, I would like to take a look to make sure it's that issue, could you follow this [guide](https://github.com/andyzhangx/Demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md) to collect the data.

**Comment by peskybp** [comment]
Sadly the node became NotReady, and the cluster redeployed the pod to a separate node, which has rectified the issue.  We have been seeing the issue with far frequency, so I will make sure to gather the data next time it pops up.

**Comment by peskybp** [comment]
That said, the reason I was confident it was this issue previously is that when I exec'd into the shell, I got the "Input / Output error" upon trying to "ls" the mount point.

Furthermore, attempting to re-mount that point gave an error to the extent of "Special device /dev/sde does not exist"

**Comment by andyzhangx** [comment]
@peskybp Could you recall  the VM had restarted before you hit that disk issue? Or just after attach/detach disk, that issue come up?
