### ISSUE TITLE
make spec.HostPorts in initContainer clear

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#57443]
I found that kubelet will not allocate hostports specified from initContainers.
And PodFitsHostPorts in kube-scheduler does not take initContainer into consideration.

Also, kube-apiserver think such pod is illegal, but I think it OK.
```
$ cat two-files-counter-pod-streaming-sidecar.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  hostname: name
  subdomain: subdomain
  initContainers:
  - name: init-step1
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      sleep 10;
    ports:
      - containerPort: 8081
        hostPort: 8081
  - name: init-step2
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      sleep 10;
    ports:
      - containerPort: 8081
        hostPort: 8081    # this port does not conflict with the previous one, because initContainer runs in sequential order.
  containers:
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        i=$((i+1));
        sleep $i;
      done
$ kubectl create -f two-files-counter-pod-streaming-sidecar.yaml 
The Pod "counter" is invalid: spec.initContainers[1].ports[0].hostPort: Duplicate value: "TCP//8081"
```

We should make the behavior of spec.HostPorts in initContainer clear

**Comment by dixudx** [comment]
> I found that kubelet will not allocate hostports specified from initContainers

@CaoShuFeng Exactly. I think this makes sense. Since initContainers are expected to be completed, we should not expose extra port mappings during creating pod sandbox, which may bring in security risks.

**Comment by CaoShuFeng** [comment]
> @CaoShuFeng Exactly. I think this makes sense. Since initContainers are expected to be completed, we should not expose extra port mappings during creating pod sandbox, which may bring in security risks.

Sounds good to me.
