### ISSUE TITLE
etcd  status healthy to unhealthy from time to time when with 1000 kubernetes node

### ISSUE THREAD

**Issue by garyyang85** [kubernetes/kubernetes#57447]
I am using kubernetes 1.5.7 and etcd 3.0.17. Just setup a large cluster with 1000 kubernetes node and etcd cluster with 3 members. It works well for one day. Since today, I found the etcd status is changed healthy or unhealthy from time to time. I found all the etcd logs are like below:
2017-12-20 09:32:26.905008 W |etcdserver: apply entries took too long [23.411359ms for 2 entries]
2017-12-20 09:32:26.905041 W | etcdserver: avoid queries with large range/delete range!

I know from here:  https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean
It is maybe caused by slow disk network or cpu. But I am wonder if this will cause etcd unhealthy status and then cause kubectl cmd can not used?  Thanks.

 area/etcd
/sig etcd

**Comment by garyyang85** [comment]
I am also trying to move events to another etcd according to the large cluster advice, but seems the --etcd-servers-overrides=/registry/events#http://ip:port do not work, there is also a issue here: 
https://github.com/kubernetes/kubernetes/issues/57440
hope can get your response! Thanks very much.

**Comment by jennybuckley** [comment]
cc @jpbetz

**Comment by jiaxuanzhou** [comment]
this is io related issue, may there is bottle-neck of the disk

**Comment by WanLinghao** [comment]
try 
etcd --quota-backend-bytes=8388608

**Comment by dhilipkumars** [comment]
cc @kubernetes/sig-api-machinery-bugs

**Comment by jpbetz** [comment]
@garyyang85 See also https://github.com/kubernetes/kubernetes/issues/57440 for configuring/debugging `--etcd-servers-overrides`.

**Comment by jpbetz** [comment]
@garyyang85  For etcd scalability/performance where etcd reports "avoid queries with large range/delete range" please try to narrow down the issue further to the specific operations made to etcd by kubernetes that are expensive. A couple way to do this:

- Use the [debug endpoint](https://coreos.com/etcd/docs/latest/op-guide/monitoring.html#debug-endpoint) to review requests and their latencies
- Inspect the WAL log (using [etcd-dump-logs](https://github.com/coreos/etcd/tree/master/tools/etcd-dump-logs)) to see what exact operations have been executed
- Use a metrics collector (https://coreos.com/etcd/docs/latest/metrics.html) to get a high level overview of request load and latency

If you're able to narrow down the issue to a specific set of requests to etcd from kubernetes, please let us know.
