### ISSUE TITLE
`kubectl get -o json` swallows collection metadata & resourceVersion

### ISSUE THREAD

**Issue by cben** [kubernetes/kubernetes#57459]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`kubectl get -o json nodes`
(not only nodes, also resourcequotas, probably any collection?)
outputs correct metadata for each entity, but empty metadata & resourceVersion, selfLink for the **collection**:
```
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Node",
            "metadata": {
                ...
                "resourceVersion": "20654",
                "selfLink": "/api/v1/nodes/localhost",
                "uid": "c5eeefc3-e4bf-11e7-be0a-5eba880b8555"
...
...
    ],
    "kind": "List",
    "metadata": {},
    "resourceVersion": "",
    "selfLink": ""
}
```

Same with `kubectl get -o yaml nodes`:
```
...
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

This is a client-side problem, because `kubectl get --loglevel=11 nodes` shows server does return collection metadata including resourceVersion:
```
I1220 16:15:06.517586   15855 request.go:991] Response Body: {"kind":"NodeList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/nodes","resourceVersion":"20835"},"items":[...]}
```

**What you expected to happen**:
get -o json/yaml should display collection-level metadata.
Also note it tries to display `resourceVersion` & `selfLink` on top level, I'd expect them to be inside `metadata`, as received from server (and per API lists like https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#nodelist-v1-core don't have `resourceVersion` & `selfLink` fields directly, they have `metadata`.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl get -o json nodes | tail`

**Anything else we need to know?**:

**Environment**:
Openshift (via minishift), but happens with `kubectl` and as shown above server responses are OK, it's kubectl client problem.

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-09T21:39:40Z", GoVersion:"go1.9beta2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-01T06:24:02Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: ThinkPad T450s laptop
- OS (e.g. from /etc/os-release):  Fedora 27.  
- Kernel (e.g. `uname -a`): `4.14.5-300.fc27.x86_64` on maching running kubectl, `4.4.41-boot2docker` inside minishift VM.
- Install tools:  kubectl from `origin-clients-3.6.0-1.fc27.x86_64` package, openshift 3.6.0 server from Minishift 1.9.0.

**Let me know if reproducing on real upstream kubernetes would help**

**Comment by liggitt** [comment]
cc @smarterclayton 
for aggregation of get output into virtual List object

**Comment by niuzhenguo** [comment]
For such single resource collection request, how about not setting builder.flatten? It's actually no need to aggregate the output into a virtual List object.

**Comment by liggitt** [comment]
> For such single resource collection request, how about not setting builder.flatten? It's actually no need to aggregate the output into a virtual List object.

The output of `kubectl get ... -o yaml` is an API... I would not expect the type to change from v1.List

**Comment by niuzhenguo** [comment]
@liggitt Sure, without Flatten set, such request already got a List object with all properties we needed. Flattening the original object and aggregate the items into a virtual list is not necessary in such case and will empty metadata & resourceVersion, selfLink for the collection.

**Comment by liggitt** [comment]
Doesn’t it get a PodList, not a List?

**Comment by niuzhenguo** [comment]
@liggitt Yes, it's a PodList, but afterwards it will get replaced with List https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/resource/get.go#L619-L631

**Comment by cben** [comment]
/remove-lifecycle stale
Still happens with kubectl v1.9.1+cbc5b49.

**Comment by cben** [comment]
/remove-lifecycle stale
Still happens with kubectl v1.10.3 (against openshift 3.9 & 3.10 clusters)
