### ISSUE TITLE
Create resource deployment report timeout but create other resource success

### ISSUE THREAD

**Issue by lklkxcxc** [kubernetes/kubernetes#57452]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
root@node-1:~/prometheus# kubectl create -f prometheus-01.yaml
clusterrolebinding "prometheus-operator" created
clusterrole "prometheus-operator" created
serviceaccount "prometheus-operator" created
Error from server (Timeout): error when creating "prometheus-01.yaml": Timeout: request did not complete within allowed duration

root@node-1:~/prometheus# etcdctl --endpoints https://10.0.0.33:2379 cluster-health
member 203058f8d922e5d9 is healthy: got healthy result from https://10.0.0.33:2379
member 20c1df3bc6c542ae is healthy: got healthy result from https://10.0.0.29:2379
member 82d6f167d2559682 is healthy: got healthy result from https://10.0.0.35:2379
cluster is healthy

root@node-1:~/prometheus# kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
etcd-2               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"} 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
create deployment resoure

**Anything else we need to know?**:

**Apiserver logs output**:
1220 10:30:15.409248       1 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (2.620446ms) 200 [[hyperkube/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e/leader-election] 127.0.0.1:56544]
I1220 10:30:15.439516       1 trace.go:76] Trace[1844338211]: "Create /apis/extensions/v1beta1/namespaces/default/deployments" (started: 2017-12-20 10:29:45.438316221 +0000 UTC) (total time: 30.001156076s):
Trace[1844338211]: [30.001156076s] [30.00067321s] END
I1220 10:30:15.439742       1 wrap.go:42] POST /apis/extensions/v1beta1/namespaces/default/deployments: (30.001743718s) 504
goroutine 253175 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4262c1c70, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4262c1c70, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42613e840, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:201 +0xb5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc4279f8210, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:173 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x48af8be, 0x10, 0x7fed7a78d070, 0xc4264a38c0, 0x9a9e640, 0xc422ac79e8, 0xc421874400, 0x1f8, 0x9a81dc0, 0xc4264a3830)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:91 +0x8d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7fed7a6e41b8, 0xc4299cbfb0, 0x9aa2000, 0xc4219cee40, 0x489834b, 0xa, 0x4890bd4, 0x7, 0x9a9e640, 0xc422ac79e8, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:113 +0x220
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7fed7a6e41b8, 0xc4299cbfb0, 0x9a6bb40, 0xc4264a37a0, 0x9aa2000, 0xc4219cee40, 0x489834b, 0xa, 0x4890bd4, 0x7, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:132 +0x16b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc429ea8a00, 0x9a6bb40, 0xc4264a37a0, 0x9a9e640, 0xc422ac79e8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:80 +0x10e
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1(0x9a9e640, 0xc422ac79e8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:478 +0x113a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulCreateResource.func1(0xc4279f8030, 0xc42cb76240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1069 +0xd5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc4279f8030, 0xc42cb76240)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:145 +0x207
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420ec06c0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc420ec06c0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x48a6adb, 0xe, 0xc420ec06c0, 0xc4208a4cb0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420c0b4e0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        <autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42b477480, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42b47fc00, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4241c1180, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x48ab319, 0xf, 0xc42770b4d0, 0xc4241c1180, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc424c3fde0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        <autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37a
net/http.HandlerFunc.ServeHTTP(0xc4282045f0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:98 +0x5a0
net/http.HandlerFunc.ServeHTTP(0xc424475cc0, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x21b2
net/http.HandlerFunc.ServeHTTP(0xc428204640, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc428204690, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc424c3fe00, 0x7fed701d2b40, 0xc422ac79d8, 0xc421874400)
        /usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc424c3fe80, 0x9aa5640, 0xc422ac79d8, 0xc421874400, 0xc42cb76120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x1ca

logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within allowed duration\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}\n"
 [[kubectl/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e] 10.0.0.33:38304]
I1220 10:30:15.497238       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: (2.892078ms) 200 [[hyperkube/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e] 127.0.0.1:54426]
I1220 10:30:15.707636       1 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (3.245752ms) 200 [[hyperkube/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e/leader-election] 127.0.0.1:56518]
I1220 10:30:15.726583       1 wrap.go:42] PUT /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (17.391995ms) 200 [[hyperkube/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e/leader-election] 127.0.0.1:56518]
I1220 10:30:16.015625       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1alpha1/externaladmissionhookconfigurations: (4.971095ms) 200 [[hyperkube/v1.8.2+coreos.0 (linux/amd64) kubernetes/4c0769e] 127.0.0

**Environment**:
- Kubernetes version (use `kubectl version`):1.83
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0-104-generic
- Install tools: kubespray
- Others:

**Comment by mbohlool** [comment]
There is not much information in the log to say why the request is timing out. Can you consistently reproduce this? Is it possible to give steps for us to reproduce?

**Comment by lklkxcxc** [comment]
@mbohlool I created any deployment resource that always report “Timeout“,but I can create pod and many kind of resources. I only found apiserver error log when I created deployment resource. Can you tell me what you need  information in the log ?

**Comment by mbohlool** [comment]
@lklkxcxc we need a way to reproduce it. Can you start with a fresh k8s cluster and use (hopefully) minimum configuration/yamls to reproduce it and send those to us to reproduce it?

**Comment by cwocwo** [comment]
The same error:
```
I0630 06:40:37.557192       1 trace.go:76] Trace[1053630075]: "Create /apis/extensions/v1beta1/namespaces/istio-system/deployments" (started: 2018-06-30 06:40:07.555180406 +0000 UTC m=+8157.958285796) (total time: 30.001958172s):
Trace[1053630075]: [30.001958172s] [30.000606503s] END
I0630 06:40:37.557483       1 wrap.go:42] POST /apis/extensions/v1beta1/namespaces/istio-system/deployments: (30.002977734s) 504
goroutine 335777 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4333adea0, 0x1f8)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4333adea0, 0x1f8)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42b736ea0, 0x1f8)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc4288e6fc0, 0x1f8)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:258 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x49f024d, 0x10, 0x7fd67f5a0350, 0xc4310ad180, 0xa731a00, 0xc425a06a88, 0xc431ae3400, 0x1f8, 0xa712640, 0xc42a1f98c0)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7fd67c114478, 0xc4305bd650, 0xa735640, 0xc422c47500, 0x49dcc0e, 0xa, 0x49d689c, 0x7, 0xa731a00, 0xc425a06a88, ...)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:123 +0x32b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7fd67c114478, 0xc4305bd650, 0xa6fc400, 0xc42a1f9830, 0xa735640, 0xc422c47500, 0x49dcc0e, 0xa, 0x49d689c, 0x7, ...)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:142 +0x163
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc424c6e8c0, 0xa6fc400, 0xc42a1f9830, 0xa731a00, 0xc425a06a88, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:67 +0x10c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1(0xa731a00, 0xc425a06a88, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:120 +0x1404
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulCreateResource.func1(0xc4288e6bd0, 0xc4316f2420)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1080 +0xd5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc4288e6bd0, 0xc4316f2420)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:199 +0x208
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4210fc870, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb18
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4210fc870, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x49e9062, 0xe, 0xc4210fc870, 0xc420619a40, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x4e0
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420dc7b80, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42b36ab80, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x15f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42d669c40, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4255e0150, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x49ecbd5, 0xf, 0xc4266170e0, 0xc4255e0150, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc426219460, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc4254642d0, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:165 +0x42a
net/http.HandlerFunc.ServeHTTP(0xc4262ccac0, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc425464320, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc425464370, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc426219480, 0x7fd6741885e0, 0xc425a06a78, 0xc431ae3400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc426219520, 0xa738e80, 0xc425a06a78, 0xc431ae3400, 0xc430516720)
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /workspace/anago-v1.9.5-beta.0.52+f01a2bf98249a4/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab

logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within allowed duration\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}\n"
 [[kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf] 10.17.7.70:54412]
```
