### ISSUE TITLE
Move Priority and Preemption to Beta

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#57471]
This is to track the progress of work on moving pod priority and preemption to Beta.

/kind feature

- [x] Write a design doc on how to support preemption in DaemonSet controller.
- [x] Remove DaemonSet controller scheduling logic and let DaemonSet Pods be schedule by default scheduler.
- [ ] Add support for multi-scheduler preemption to default scheduler (this is targeted for 1.11).
- [x] Ensure that cluster setup tools start scheduler as a part of cluster bring-up. This is needed for scheduling DaemonSet Pods.
- [x] Change nominated-node-name annotation to a field in PodStatus.
- [x] Add metrics for number of preemptions and number of victims.
- [x] Change critical pods’ template to use priority
- [x] Get rid of the rescheduler
- [x] Write a doc on how Kubelet evictions work with priority
- [x] Update the comment of PriorityClassName and also the priority design doc to describe "system" priorities.
- [x] Enable priority and preemption in our existing scalability tests.
- [x] Move apis/scheduling/v1alpha1 to apis/scheduling/v1beta1
- [x] Write a roll out plan

/sig scheduling
/assign

**Comment by bsalamat** [comment]
@aveshagarwal and @ravisantoshgudimetla,
Do you guys think you have time to work on any of the items here? I have written a design doc on supporting preemption in DS controller which I am going to share with all soon and then we can decide which solution to pick and how to proceed there.
Adding metrics for preemption is something that would be great if you could help.

**Comment by bsalamat** [comment]
@dashpole, Do we already have a doc on how Kubelet eviction works with priority? If not, do you think you can add one?

**Comment by dashpole** [comment]
I added it to the eviction design docs: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#eviction-strategy

We may want to add it to the open-source documentation as well: https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

**Comment by bsalamat** [comment]
@dashpole, Thanks! Yes, it would be great if you could update the user docs as well.

**Comment by aveshagarwal** [comment]
@bsalamat sure @ravisantoshgudimetla  and I can surely work on some of the items.

**Comment by aveshagarwal** [comment]
@bsalamat I will go through your design doc soon,

**Comment by ravisantoshgudimetla** [comment]
@bsalamat - I will also go through the docs. I believe I can get started on adding metrics preemptions in meanwhile.

**Comment by ravisantoshgudimetla** [comment]
@bsalamat Can you explain "Get rid of the rescheduler" means?

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla this rescheduler: https://github.com/kubernetes/contrib/tree/master/rescheduler which is based on critical pod annotation, as the same functionality will be handled by priority and preemption feature.

**Comment by ravisantoshgudimetla** [comment]
I am off next week but I will get started on following items

Change critical pods’ template to use priority
Get rid of the rescheduler 

unless someone has already started on it.

**Comment by ravisantoshgudimetla** [comment]
@bsalamat For critical pod's template to use priority & , I am planning to do following things:

- Update IsCriticalPod f(n) to use priorityClass `system-node-critical` and other relevant changes.
- Add e2e test.
- In priority admission controller do a automatic assignment of `system-node-critical`, in case the pod has just critical pod annotation set(for backwards compatibility).
- Add deprecation note to  `Rescheduler` section and pod tolerations in `Config` section of https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ and add `system-node-critical` is needed for critical pods.

Please let me know, if I have missed any item.

**Comment by bsalamat** [comment]
@ravisantoshgudimetla Thanks for the update and your help. Your plan sounds good to me. I have a couple of small comments:
1. I think ` IsCriticalPod` should return true for both `system-node-critical` and `system-cluster-critical` priorities. We should create a function to check these two priorities and returns true for system critical pods. The function should be usable by other components. So, maybe apis/core/v1/helpers is the right place.
1. I also think that we should probably assign `system-cluster-critical` instead of `system-node-critical` automatically for critical pods. `system-cluster-critical` is a bit lower priority than `system-node-critical`, so it may cause fewer surprises, yet it is high enough to not get preempted under normal circumstances.

**Comment by bsalamat** [comment]
The design doc how to handle preemption for DaemonSet Pods is available [here](https://docs.google.com/document/d/1v7hsusMaeImQrOagktQb40ePbK6Jxp1hzgFB9OZa_ew). The document includes tasks and their release target.

**Comment by wanghaoran1988** [comment]
@bsalamat I have some free time in the fowlling weeks, fell free let me know what can I help here.

**Comment by bsalamat** [comment]
@ravisantoshgudimetla 
FYI, I have identified the following system critical add-ons so far that need to have a critical priority:

Kube-dns: system-cluster-critical
Kube-proxy: system-node-critical
Kubernetes-dashboard: system-cluster-critical
fluentd: system-node-critical
ip-masq-agent: system-node-critical
nvidia-gpu-device-plugin: system-node-critical
metadata-proxy: system-node-critical
metrics-server: system-cluster-critical
heapster: system-cluster-critical
influxGrafana: system-cluster-critical
calico-node: system-node-critical
kube-dns-autoscaler: system-cluster-critical

**Comment by bsalamat** [comment]
Rollout plan for Priority and Preemption can be [found here](https://docs.google.com/document/d/1-ZDLZ1HJp209saJl_XVhOaXZYXFUqgI7B6C3Lx5N4_w/).
As usual, you need be a member of [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) to gain access to the doc.

**Comment by ravisantoshgudimetla** [comment]
@bsalamat In the self-hosting kubernetes, should the tool like kube-adm need to add system-node-priority to etcd, apiserver pods etc, so that scheduler won't preempt them?

**Comment by bsalamat** [comment]
@ravisantoshgudimetla etcd, apiserver, etc usually run on the master node and the master node is marked unschedulable. So, the scheduler shouldn't preempt any pods on those nodes. Besides, those pods do not go through admission controllers AFAIK. So, even if we add priority to them, their priority won't be resolved.

**Comment by timothysc** [comment]
PSA CNI-providers: this will eventually be a default for critical pods, which would affect your deployments. 

@kubernetes/sig-network-misc @caseydavenport @errordeveloper

**Comment by jberkus** [comment]
adding /priority important-soon to keep tracking this for 1.10

/priority important-soon

Please break out the items from this tracker that will actually be added to 1.10, and add each of those issues/PRs to the 1.10 milestone with other appropriate labels.  Thanks!

**Comment by bsalamat** [comment]
I changed the milestone. We won't be able to test all pieces of this work with real workloads in time for 1.10.

**Comment by bsalamat** [comment]
ref/ #59630 #59636 #59862 #61161 kubernetes/website#7678

**Comment by ravisantoshgudimetla** [comment]
@bsalamat I think #57963 and #63724 are remaining PRs for moving to beta. 

Are the following items needed now:

- Add support for multi-scheduler preemption to default scheduler (this is targeted for 1.11).
- Ensure that cluster setup tools start scheduler as a part of cluster bring-up. This is needed for scheduling DaemonSet Pods.
-  Enable priority and preemption in our existing scalability tests.

If yes, do we have PRs for them or they need to be created?

**Comment by ravisantoshgudimetla** [comment]
@bsalamat I did a grep to find list of files containing rescheduler. Got the following:
uild/lib/release.sh
CHANGELOG-1.4.md
CHANGELOG-1.5.md
CHANGELOG-1.6.md
cluster/gce/gci/configure-helper.sh
cluster/gce/util.sh
cluster/gce/config-default.sh
cluster/gce/config-test.sh
cluster/gce/manifests/kube-proxy.manifest
cluster/gce/manifests/BUILD
cluster/gce/manifests/rescheduler.manifest
cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml
cluster/addons/fluentd-gcp/fluentd-gcp-configmap-old.yaml
cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml
cluster/log-dump/log-dump.sh
pkg/kubelet/types/pod_update.go
test/e2e/scheduling/BUILD
test/e2e/scheduling/rescheduler.go
test/test_owners.json
test/test_owners.csv
Some of them have a mention of rescheduler in comments but I will remove relevant rescheduler pieces in the code base and will create a PR sometime next week.

**Comment by bsalamat** [comment]
@ravisantoshgudimetla  Sounds good! Thanks. From the name of the files, it doesn't seem to me that there is any critical piece that we must address ASAP, but I may be wrong.

**Comment by bsalamat** [comment]
Priority and preemption has been moved to Beta in 1.11.

Rescheduler is not completely removed in 1.11, but it is used only to create room for critical DaemonSet pods. Other critical pods in the system must use priority and scheduler will be responsible for scheduling them.

**Comment by MohdAhmad** [comment]
@bsalamat will this automatically be applied for critical pods you've identified above or will their spec need to be updated?

```
FYI, I have identified the following system critical add-ons so far that need to have a critical priority:

Kube-dns: system-cluster-critical
Kube-proxy: system-node-critical
Kubernetes-dashboard: system-cluster-critical
fluentd: system-node-critical
ip-masq-agent: system-node-critical
nvidia-gpu-device-plugin: system-node-critical
metadata-proxy: system-node-critical
metrics-server: system-cluster-critical
heapster: system-cluster-critical
influxGrafana: system-cluster-critical
calico-node: system-node-critical
kube-dns-autoscaler: system-cluster-critical```

**Comment by bsalamat** [comment]
@MohdAhmad We have already made changes to run those pods with proper priority. Please check this PR #59237 and let us know if we have missed anything. Kube-proxy's priority is also set in a different PR.

**Comment by bsalamat** [comment]
Priority and preemption has been promoted to Beta since K8s 1.11.
