### ISSUE TITLE
Cinder persistent volume can not be attached to the new node after shut down the current node

### ISSUE THREAD

**Issue by xiangfeiz** [kubernetes/kubernetes#57497]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I created a ReplicationController with a pod using a Cinder PVC as volume. When I used 'nova stop' to shut down the node where the pod is put (and where the Cinder Volume is attached to), the pod got rescheduled to another node but it can't become active because the Cinder Volume stays attached to the old node and k8s can't attach it to the new node because its state is 'in-use'.

**What you expected to happen**:
K8s should be able to detach the Cinder Volume from the old node so that it can be attached to the new node.

**How to reproduce it (as minimally and precisely as possible)**:
1 Create k8s cluster with OpenStack provider
2 Create a PVC
3 Create ReplicationController with a pod using the PVC as volume
4 Wait until the Pod becomes active
5 Find which node the Pod is located and use 'nova stop' to shutdown that node
6 Check the Pod status and it remains in ContainerCreating.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.8.1
- Cloud provider or hardware configuration:
OpenStack cloud provider
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
Linux k8s-master-0-53eacf69-fc5c-4660-a010-26e1852474f5 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by xiangfeiz** [comment]
/sig storage
/sig openstack
cc @kubernetes/sig-storage-bugs

**Comment by xiangfeiz** [comment]
I think the issue is the same as #50004 which is for k8s 1.7. Nova instance is powered off but not deleted. And the Cinder volume remains attached to the powered off node forever.

Here are the controller manager log

`I1222 03:49:17.229946       1 openstack_instances.go:46] Claiming to support Instances
I1222 03:49:56.150268       1 controller_utils.go:249] Recording status change NodeNotReady event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.150732       1 controller_utils.go:163] Update ready status of pods on node [k8s-node-1-979313c3-1398-410c-b6ea-f96937119184]
I1222 03:49:56.151851       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 status is now: NodeNotReady
I1222 03:49:56.162459       1 controller_utils.go:180] Updating ready status of pod server-kztg9 to false
I1222 03:49:56.166769       1 controller_utils.go:180] Updating ready status of pod heapster-7645fccd79-mh7l7 to false
I1222 03:49:56.183304       1 controller_utils.go:180] Updating ready status of pod kube-dns-6c9966dc4f-2cwnp to false
I1222 03:49:56.193211       1 controller_utils.go:180] Updating ready status of pod kube-flannel-7gscn to false
I1222 03:49:56.204867       1 controller_utils.go:180] Updating ready status of pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 to false
I1222 03:49:56.224518       1 openstack_instances.go:46] Claiming to support Instances
I1222 03:49:56.298864       1 node_controller.go:721] Deleting node (no longer present in cloud provider): k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.299857       1 controller_utils.go:237] Recording Deleting Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 because it's not present according to cloud provider event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.301073       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 event: Deleting Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 because it's not present according to cloud provider
I1222 03:49:56.320952       1 attach_detach_controller.go:478] error removing node "k8s-node-1-979313c3-1398-410c-b6ea-f96937119184" from desired-state-of-world: failed to delete node "k8s-node-1-979313c3-1398-410c-b6ea-f96937119184" from list of nodes managed by attach/detach controller--the node still contains 1 volumes in its list of volumes to attach
I1222 03:50:01.300488       1 node_controller.go:597] Controller observed a Node deletion: k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:01.300609       1 controller_utils.go:237] Recording Removing Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 from Controller event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:01.300754       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 event: Removing Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 from Controller
I1222 03:50:09.293534       1 gc_controller.go:162] Found orphaned Pod server-kztg9 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.293760       1 gc_controller.go:62] PodGC is force deleting Pod: default:server-kztg9
I1222 03:50:09.301296       1 replication_controller.go:450] Too few "default"/"server" replicas, need 1, creating 1
I1222 03:50:09.313332       1 gc_controller.go:166] Forced deletion of orphaned Pod server-kztg9 succeeded
I1222 03:50:09.313344       1 gc_controller.go:162] Found orphaned Pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.313350       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:09.329219       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"server", UID:"438dd85f-e6c6-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4341", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: server-4h8z2
I1222 03:50:09.368987       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 succeeded
I1222 03:50:09.369011       1 gc_controller.go:162] Found orphaned Pod kube-flannel-7gscn assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.369016       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-flannel-7gscn
W1222 03:50:09.372822       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.373103       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.394772       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-flannel-7gscn succeeded
I1222 03:50:09.394784       1 gc_controller.go:162] Found orphaned Pod kube-dns-6c9966dc4f-2cwnp assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.394788       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-dns-6c9966dc4f-2cwnp
I1222 03:50:09.404898       1 replica_set.go:454] Too few "kube-system"/"kube-dns-6c9966dc4f" replicas, need 2, creating 1
I1222 03:50:09.421790       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kube-dns-6c9966dc4f", UID:"8768d405-e6c4-11e7-9440-fa163e115b6e", APIVersion:"extensions", ResourceVersion:"4348", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kube-dns-6c9966dc4f-qxvxc
I1222 03:50:09.437312       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-dns-6c9966dc4f-2cwnp succeeded
I1222 03:50:09.437324       1 gc_controller.go:162] Found orphaned Pod heapster-7645fccd79-mh7l7 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.437328       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:heapster-7645fccd79-mh7l7
W1222 03:50:09.473128       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.473894       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.474853       1 replica_set.go:454] Too few "kube-system"/"heapster-7645fccd79" replicas, need 1, creating 1
I1222 03:50:09.487849       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"heapster-7645fccd79", UID:"8cade959-e6c4-11e7-9440-fa163e115b6e", APIVersion:"extensions", ResourceVersion:"4344", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: heapster-7645fccd79-7g5ns
I1222 03:50:09.506880       1 gc_controller.go:166] Forced deletion of orphaned Pod heapster-7645fccd79-mh7l7 succeeded
W1222 03:50:09.574144       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.574474       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
W1222 03:50:09.674371       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.674712       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
`
The Multi-Attach error kept repeating. I have waited for an hour and nothing changed to Cinder Volume and Pod.

**Comment by xiangfeiz** [comment]
I think the issue is the same as #50004 which is for k8s 1.7. Nova instance is powered off but not deleted. And the Cinder volume remains attached to the powered off node forever.

Here are the controller manager log
<pre>
I1222 03:49:17.229946       1 openstack_instances.go:46] Claiming to support Instances
I1222 03:49:56.150268       1 controller_utils.go:249] Recording status change NodeNotReady event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.150732       1 controller_utils.go:163] Update ready status of pods on node [k8s-node-1-979313c3-1398-410c-b6ea-f96937119184]
I1222 03:49:56.151851       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 status is now: NodeNotReady
I1222 03:49:56.162459       1 controller_utils.go:180] Updating ready status of pod server-kztg9 to false
I1222 03:49:56.166769       1 controller_utils.go:180] Updating ready status of pod heapster-7645fccd79-mh7l7 to false
I1222 03:49:56.183304       1 controller_utils.go:180] Updating ready status of pod kube-dns-6c9966dc4f-2cwnp to false
I1222 03:49:56.193211       1 controller_utils.go:180] Updating ready status of pod kube-flannel-7gscn to false
I1222 03:49:56.204867       1 controller_utils.go:180] Updating ready status of pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 to false
I1222 03:49:56.224518       1 openstack_instances.go:46] Claiming to support Instances
I1222 03:49:56.298864       1 node_controller.go:721] Deleting node (no longer present in cloud provider): k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.299857       1 controller_utils.go:237] Recording Deleting Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 because it's not present according to cloud provider event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:49:56.301073       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 event: Deleting Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 because it's not present according to cloud provider
I1222 03:49:56.320952       1 attach_detach_controller.go:478] error removing node "k8s-node-1-979313c3-1398-410c-b6ea-f96937119184" from desired-state-of-world: failed to delete node "k8s-node-1-979313c3-1398-410c-b6ea-f96937119184" from list of nodes managed by attach/detach controller--the node still contains 1 volumes in its list of volumes to attach
I1222 03:50:01.300488       1 node_controller.go:597] Controller observed a Node deletion: k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:01.300609       1 controller_utils.go:237] Recording Removing Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 from Controller event message for node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:01.300754       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-node-1-979313c3-1398-410c-b6ea-f96937119184", UID:"5aaeea95-e6c4-11e7-9440-fa163e115b6e", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 event: Removing Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 from Controller
I1222 03:50:09.293534       1 gc_controller.go:162] Found orphaned Pod server-kztg9 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.293760       1 gc_controller.go:62] PodGC is force deleting Pod: default:server-kztg9
I1222 03:50:09.301296       1 replication_controller.go:450] Too few "default"/"server" replicas, need 1, creating 1
I1222 03:50:09.313332       1 gc_controller.go:166] Forced deletion of orphaned Pod server-kztg9 succeeded
I1222 03:50:09.313344       1 gc_controller.go:162] Found orphaned Pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.313350       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184
I1222 03:50:09.329219       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"server", UID:"438dd85f-e6c6-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4341", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: server-4h8z2
I1222 03:50:09.368987       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-proxy-k8s-node-1-979313c3-1398-410c-b6ea-f96937119184 succeeded
I1222 03:50:09.369011       1 gc_controller.go:162] Found orphaned Pod kube-flannel-7gscn assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.369016       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-flannel-7gscn
W1222 03:50:09.372822       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.373103       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.394772       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-flannel-7gscn succeeded
I1222 03:50:09.394784       1 gc_controller.go:162] Found orphaned Pod kube-dns-6c9966dc4f-2cwnp assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.394788       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:kube-dns-6c9966dc4f-2cwnp
I1222 03:50:09.404898       1 replica_set.go:454] Too few "kube-system"/"kube-dns-6c9966dc4f" replicas, need 2, creating 1
I1222 03:50:09.421790       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"kube-dns-6c9966dc4f", UID:"8768d405-e6c4-11e7-9440-fa163e115b6e", APIVersion:"extensions", ResourceVersion:"4348", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kube-dns-6c9966dc4f-qxvxc
I1222 03:50:09.437312       1 gc_controller.go:166] Forced deletion of orphaned Pod kube-dns-6c9966dc4f-2cwnp succeeded
I1222 03:50:09.437324       1 gc_controller.go:162] Found orphaned Pod heapster-7645fccd79-mh7l7 assigned to the Node k8s-node-1-979313c3-1398-410c-b6ea-f96937119184. Deleting.
I1222 03:50:09.437328       1 gc_controller.go:62] PodGC is force deleting Pod: kube-system:heapster-7645fccd79-mh7l7
W1222 03:50:09.473128       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.473894       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.474853       1 replica_set.go:454] Too few "kube-system"/"heapster-7645fccd79" replicas, need 1, creating 1
I1222 03:50:09.487849       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"heapster-7645fccd79", UID:"8cade959-e6c4-11e7-9440-fa163e115b6e", APIVersion:"extensions", ResourceVersion:"4344", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: heapster-7645fccd79-7g5ns
I1222 03:50:09.506880       1 gc_controller.go:166] Forced deletion of orphaned Pod heapster-7645fccd79-mh7l7 succeeded
W1222 03:50:09.574144       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.574474       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
W1222 03:50:09.674371       1 reconciler.go:267] Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" (UniqueName: "kubernetes.io/cinder/255e41db-d440-45c4-9aa1-e9aca8296a8a") from node "k8s-node-0-979313c3-1398-410c-b6ea-f96937119184" Volume is already exclusively attached to one node and can't be attached to another
I1222 03:50:09.674712       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"server-4h8z2", UID:"3497421b-e6cb-11e7-9440-fa163e115b6e", APIVersion:"v1", ResourceVersion:"4375", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' Multi-Attach error for volume "pvc-3af68a81-e6c6-11e7-9440-fa163e115b6e" Volume is already exclusively attached to one node and can't be attached to another
</pre>
The Multi-Attach error kept repeating. I have waited for an hour and nothing changed to Cinder Volume and Pod.

**Comment by xiangfeiz** [comment]
@jingxu97 @FengyunPan

**Comment by arno01** [comment]
The same issue here. This is how I work it around:

1. kubectl: delete pvc & pv;
2. openstack server remove volume <your_vm> <your_volume_id>;
3. kubectl: create pv & pvc again;
4. wait few seconds and the POD will turn into a Running state again.

**Comment by FengyunPan** [comment]
cc @zetaab

**Comment by zetaab** [comment]
I can confirm this issue. The main problem here is that if you shutdown nova instance(using openstack GUI/API), it is automatically deleted from kubernetes cluster as well. After that it seems that kube cannot handle that correctly. I tested this and added some debug logging. 

originally pod was running in kube-dev-node-1-1 and I shutdowned it from openstack GUI.

Now nodes
```
% kubectl get nodes
NAME                  STATUS    ROLES     AGE       VERSION
kube-dev-master-1-0   Ready     <none>    17m       v1.9.1-beta.0
kube-dev-node-1-0     Ready     <none>    15m       v1.9.1-beta.0
```

Cinder:
```
% openstack volume list
+--------------------------------------+-------------------------------------------------------------+--------+------+--------------------------------------------+
| ID                                   | Display Name                                                | Status | Size | Attached to                                |
+--------------------------------------+-------------------------------------------------------------+--------+------+--------------------------------------------+
| 0c5d4dc7-b2a0-499b-b57e-48dcd59067cb | kubernetes-dynamic-pvc-ca974bca-ea76-11e7-ab9a-fa163ec3591c | in-use |    8 | Attached to kube-dev-node-1-1 on /dev/vdb  |
+--------------------------------------+-------------------------------------------------------------+--------+------+--------------------------------------------+
```

And what says kubernetes debug logs:

```

**Comment by jingxu97** [comment]
@zetaab thanks for reporting this issue. Could you please confirm for cinder, if the node instance is shundown, will it be deleted from the cloud provider? Also in this situation, the volume is still attached to the node even after the node is deleted from cloud provider?
AFAIK, other cloud providers such as GCE, AWS, if node is deleted from cloud provider, the volume should be detached automatically. If cinder is different, we have to solve the issue for it.

**Comment by zetaab** [comment]
if we shutdown cinder node (openstack cloud provider), it is deleted from the kubernetes cluster. And if that happens, the volume is still attached to node when the node is shutdowned in cloud provider. Currently if you want shutdown node, you need drain it really carefully (that there isnt any pods which have PVC attached) and after that you can shutdown it. Otherwise if you shutdown node which had PVC pods, then that pod is not going to be running before that single shutdowned node is back up and running (the cinder is attached there 24/7).

**Comment by rootfs** [comment]
The multi-attach error looks what prevents the cinder volume attaching to new instance. When the node is removed from the k8s cluster, are volumes attached to that node removed as well?

**Comment by zetaab** [comment]
No those are not removed or detached if node is removed from cluster.

@rootfs check https://github.com/kubernetes/kubernetes/issues/56846 possible fix for this

**Comment by wenlxie** [comment]
The same issue with: https://github.com/kubernetes/kubernetes/pull/53855
