### ISSUE TITLE
Federation does not resolve Hostname, need to use IP

### ISSUE THREAD

**Issue by tommyknows** [kubernetes/kubernetes#57505]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When adding a cluster to the federation (with `kubefed join`) the "server" field (in kubeconfig) needs to be an IP-Adress. If I use "server: https://hostname:6443", the cluster will be offline when executing `kubectl get clusters` due to `Cluster is not reachable`

**What you expected to happen**:
I expect the federation to be able to work with hostnames as well - as it works with kubectl too. Or at least, it should be documented somewhere that you need to use IP-Addresses.

**How to reproduce it (as minimally and precisely as possible)**:
Create a federation cluster and trying to add a cluster that uses hostnames instead of IPs.

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: On-Premise / OpenStack
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0

**Comment by tommyknows** [comment]
@kubernetes/sig-multicluster-bugs

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#199.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
