### ISSUE TITLE
kube-proxy's default behavior of using nodeIP 127.0.0.1 when nodeIP is nil seems problematic

### ISSUE THREAD

**Issue by 3dinfluence** [kubernetes/kubernetes#57518]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

kube-proxy came up cleanly but mis-configured iptable rules due to a mis-match in the hostname and node name within the cluster triggering a default behavior.  In this case the hostname returned the fqdn of the host and the cluster only had the hostname.  This resulted in the following warning messages when kube-proxy started.

```
W1220 16:46:26.875651       1 server.go:580] Failed to retrieve node info: nodes "node07.example.com" not found
W1220 16:46:26.875785       1 proxier.go:471] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
```
Which then presents itself as pods not being able to access clusterip ip addresses with no route errors.

**What you expected to happen**:

Would it be better to fail to in this scenario rather than try to fall back to some default?  I spent a good amount of time trying to track down the Error messages that were a result of this before finally working back to taking a closer at the Warning message.

**How to reproduce it (as minimally and precisely as possible)**:

Start the kube-proxy with `--hostname-override` set to an invalid hostname should recreate this issue.

**Anything else we need to know?**:

While I think we can chalk up this issue to mis-configuration the purpose of opening this issue is really to have a conversation about the default behavior.  I've seen several other issues filed that appear to be related to this behavior: #35641, #37414, #40653.

* Would throwing an error and exiting non-zero be a better default action when the nodeIP is nil?
* What use case(s) does a default of `127.0.0.1` support?
* If there must be a default behavior here maybe the IP address on the interface associated with the default gateway is a better default than `127.0.0.1`?
* Maybe the issue isn't in the proxier code but the kube-proxy itself should error when it fails to get node info rather than a warning?

**Environment**:
I'm not sure how much of this is important to this but here's what my environment was when I ran into this.
- Kubernetes version: 1.8.5
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Centos 7 and Ubuntu 16.04

**Comment by 3dinfluence** [comment]
@kubernetes/sig-network

**Comment by dcbw** [comment]
This similar (though not the same symptom) as https://github.com/kubernetes/kubernetes/issues/37414 for which https://github.com/kubernetes/kubernetes/pull/47262 was supposed to fix it but was closed.

One of the objections was up til now, kube-proxy has had no requirement that the hostname = nodename or even that the hostname be defined.  Making kube-proxy exit on failure to retrieve the node object might cause regressions in some legitimate use-cases.  But I have no idea what those are.  @thockin @justinsb ?

**Comment by thockin** [comment]
I have a hard time imagining what the legit cases might be.  I am confused, though - I only see this field being used in one very specific place, that would not have the effect you are claiming.

**Comment by thockin** [comment]
@rramkumar1

**Comment by JoshuaAndrew** [comment]
@thockin   @3dinfluence  @m1093782566  @rramkumar1

I ran into the issue above too, when I ran kube-proxy with  ipvs mode enabled.
This problem causes IPVS unavailability, because kube-proxy can not create kube-ipvs0 interface on host

```
I0309 02:20:50.634530       1 feature_gate.go:184] feature gates: map[SupportIPVSProxyMode:true]
I0309 02:20:50.776657       1 server.go:391] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
I0309 02:20:50.823405       1 server_others.go:180] Using ipvs Proxier.

W0309 02:20:50.831191       1 server.go:586] Failed to retrieve node info: Get https://10.96.0.1:443/api/v1/nodes/k8s-node-2: dial tcp 10.96.0.1:443: getsockopt: connection refused
W0309 02:20:50.833609       1 proxier.go:257] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP

W0309 02:20:50.833657       1 proxier.go:266] IPVS scheduler not specified, use rr by default
I0309 02:20:50.834225       1 server_others.go:205] Tearing down inactive rules.
I0309 02:20:50.929677       1 server.go:426] Version: v1.9.2
```



```
func getNodeIP(client clientset.Interface, hostname string) net.IP {
	var nodeIP net.IP
	node, err := client.Core().Nodes().Get(hostname, metav1.GetOptions{})
	if err != nil {
		glog.Warningf("Failed to retrieve node info: %v", err)
		return nil
	}
	nodeIP, err = utilnode.InternalGetNodeHostIP(node)
	if err != nil {
		glog.Warningf("Failed to retrieve node IP: %v", err)
		return nil
	}
	return nodeIP
}
```


Environment:
I'm not sure how much of this is important to this but here's what my environment was when I ran into this.

- Kubernetes version: 1.9.2
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/redhat-release): CentOS Linux release 7.4.1708 (Core)

**Comment by m1093782566** [comment]
> This problem causes IPVS unavailability, because kube-proxy can not create kube-ipvs0 interface on host

I can't see the error message from log? If kube-proxy failed to create kube-ipvs0 dummy interface, it will log something like "Failed to create dummy interface: kube-ipvs0, error:...".

**Comment by JoshuaAndrew** [comment]
@m1093782566 
there is no errors message about this. but I can not see kube-ipvs0 & dummy interface.

```
[root@k8s-node-2 ~]# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:85:4b:56 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.223/23 brd 192.168.1.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe85:4b56/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:fa:7c:5c:24 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:faff:fe7c:5c24/64 scope link 
       valid_lft forever preferred_lft forever
6: cali290ce5a918f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
7: cali4a1b18ae7e7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
12: cali796aac6575c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
19: cali76729ac6749@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by luxas** [comment]
@kubernetes/sig-network-bugs Any chance we could get this prioritized as a bug fix for v1.11?

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by detiber** [comment]
@luxas @thockin After putting a bit more thought into this, would it be possible to standardize on an environment variable that could be set through the downward api to override the default behavior of treating the hostname as the node name in the proxy? That would simplify the configuration on the kubeadm side (no need to override the command with the downward api, only setting the appropriate env variable), and would also provide a more accurate way to retrieve the actual node name for kube-proxy when deployed as a daemonset without the need to interact with the kubelet directly.

I would suggest that we could use `NODE_NAME` for this purpose.

I'd also be happy to take a stab at implementing the changes needed for the v1.12 cycle.

**Comment by gitcubehub** [comment]
Pods not getting scheduled on the new node joined to the cluster using kubespray 
The node joined to the cluster but new pods schedueld on the nodes are failing with error "get https://10.233.0.1 : dial tcp 10.233.0.1: 443 connection refused"

Network plugin - calico
kube-proxy running in ipvs mode

1. From new worker node, can connect to master server ip address over 6443
2. From new worker node, cannot access cluster ip 10.233.0.1 over port 443
3. Calico, nodelocaldns and kube-proxy pods are in running state on new node
4. Kube-proxy logs show error "invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP"
Unable to write event: 'Post https://127.0.0.1:6443/api/v1/namespaces/default/events dial tcp 127.0.0.1:6443 connection
refused" 
5. ipvsadm -ln output do not show any services
6. ip addr show output do not show kube-ipvs0 and calico interfaces

Can someone please help. Thanks
