### ISSUE TITLE
Node controller unresponsive, not cleaning up node/evicting pods when node fails due to memory pressure

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#57531]
/kind bug
/sig node

**What happened**:
Node controller does not evict pods when node is unresponsive. Node controller logs stop existing as well, process looks like its still running.
Pods scheduled on stressed node are stuck in "Unknown" state *indefinitely* (I only waited 20 mins).

The dead node:
https://gist.github.com/davidz627/8abbb756ff33e6514d130b8a10b3791d

The pods:
https://gist.github.com/davidz627/27859fca226f8a7be42d0984c0fb8e51

Node controller logs:
https://gist.github.com/davidz627/638a62bcb0b3d815eff19f02e7652afe
There are no logs after this point. Even after waiting 20 min.

**What you expected to happen**:
After some amount of time the node controller should evict pods in unknown state. Reschedule them elsewhere. Maybe clean up/restart the dead node (not sure if it's supposed to do this).

**How to reproduce it (as minimally and precisely as possible)**:
You should be able to repro the basic error by

1.  Create a pod: https://gist.github.com/davidz627/707ae63ff2825a43b6be698750a13d91
2.  Get shell into container: kubectl exec -it shell-demo -- /bin/bash
3.  Run command: "bomb () { bomb | bomb & }; bomb"
4.  Wait about 10 minutes. (maybe theres a faster way to stress kill the node)
5.  Pod will enter unknown state as kubelet stops responding from node memory pressure
6.  Pod and other pods on affected node will stay in unknown state *forever*

These repro steps do not match exactly to the logs and pods I linked above, those were just my pods from testing for a different thing and is slightly more complicated to repro.

The big issue that manifests for my exact use case is that since my deployment includes a GCE PD it will not be able to reschedule the pod to a different node until the old pod is removed. The old pod is never removed because it is stuck in the "Unknown" state

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0-alpha.1.110+3d652cae0391cf
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Container-Optimized OS
- Kernel (e.g. `uname -a`): Linux kubernetes-minion-group-4vzp 4.4.86+ #1 SMP Thu Dec 7 20:11:11 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

**Comment by davidz627** [comment]
/assign Random-Liu
can you take a look into this?

**Comment by jiaxuanzhou** [comment]
there is another similar scenario, when we crash the kubelet of one node, the status of the node will change to "NotReady" , there are some similar issues(i just compared pods created by deployment and statefulset):
when it reached the eviciton-time-out(default 5m), the event has recorded each pod has been evicted,:
1,  the pods created by deployment will be evicted immediately by node controller and new pods are created;
2, the pods created by statefulset always be "Unkown" and apps could still access the pods.

**Comment by davidz627** [comment]
Upon further investigation it does look like the pods are getting terminated eventually (~50 minutes after node is lost):

dyzz@dyzz:~/Testing$ kubectl get pods shell-demo2 --watch
NAME          READY     STATUS    RESTARTS   AGE
shell-demo2   1/1       Running   0          45s
shell-demo2   1/1       Running   0         1m
shell-demo2   1/1       NodeLost   0         6m
shell-demo2   1/1       Unknown   0         6m
dyzz@dyzz:~/Testing$ kubectl get pods
NAME          READY     STATUS              RESTARTS   AGE
memlimit      0/1       ContainerCreating   0          4m
shell-demo2   1/1       Unknown             0          36m
dyzz@dyzz:~/Testing$ kubectl get pods shell-demo2 --watch
NAME          READY     STATUS    RESTARTS   AGE
shell-demo2   1/1       Unknown   0          36m
^Cdyzz@dyzz:~/Testing$ kubectl get pods
NAME          READY     STATUS              RESTARTS   AGE
memlimit      0/1       ContainerCreating   0          10m
shell-demo2   1/1       Unknown             0          42m
dyzz@dyzz:~/Testing$ kubectl get pods shell-demo2 --watch
NAME          READY     STATUS    RESTARTS   AGE
shell-demo2   1/1       Unknown   0          43m
shell-demo2   0/1       Terminating   0         53m
shell-demo2   0/1       Terminating   0         55m
shell-demo2   0/1       Terminating   0         55m

**Comment by liggitt** [comment]
> After some amount of time the node controller should evict pods in unknown state. Reschedule them elsewhere. 

@smarterclayton is this expected for all pods, including ones from statefulsets?

**Comment by smarterclayton** [comment]
Pods are not removed from down nodes unless one of the following conditions happens:

1. an admin deletes the pod or node explicitly
2. the node comes back and acknowledges the deleted pods
3. the cloud provider deletes the instance, at which point the node controller sees the instance no longer exists and then deletes the node (1 above) which causes the pod to be deleted.

**Comment by jingxu97** [comment]
cc @yujuhong @dashpole 
Could you please confirm whether this is expected behavior.  Thanks!

**Comment by dashpole** [comment]
This is not memory pressure, it is a fork bomb, and consumes all of the processes on the node, preventing any node functionality that would consume a process (I think in this case it is preventing any api status updates).  This is a known issue https://github.com/kubernetes/kubernetes/issues/43783.

**Comment by yujuhong** [comment]
> Could you please confirm whether this is expected behavior. Thanks!

What @smarterclayton said in https://github.com/kubernetes/kubernetes/issues/57531#issuecomment-355139769 is the intended behavior.

The node controller will try "evict" the pods -- but in this case, the "eviction" simply means setting the DeletionTimestamp on the pods. Since kubelet is not functioning, it will not actually reclaim the resources and remove the pods. If you enable cluster autoscaler in GKE, for example, the autoscaler will delete the node after it has been not ready for a while. 

> Upon further investigation it does look like the pods are getting terminated eventually (~50 minutes after node is lost):

@davidz627, kubectl is not very consistent in displaying a single "STATUS" message for the pods. I think the "NodeLost" and "Unknown" mean the same thing in this context. Even after the DeletionTimestamp is set, `kubectl` may still choose to show you "Unknown" or "NodeLost". I didn't dig into its code to see when it'd choose "Terminating" over others, but I don't think it mean much here. As for reproducing the issue, you can simply stop the kubelet service on the node, e.g., `sudo systemctl stop kubelet` on COS.

**Comment by davidz627** [comment]
Ok, looks like #43783 captures this scenario.

However, I'm still confused as to why the pods/node were able to recover after ~50 minutes. It seems to me as though there is some mechanism for recovery from this, but it is taking *too long* to kick in.

**Comment by jingxu97** [comment]
@davidz627 what do you mean by "node is lost" after 50 mins?

**Comment by davidz627** [comment]
@jingxu97 kubelet on the node stops responding.
