### ISSUE TITLE
Odd Image Size

### ISSUE THREAD

**Issue by iloayuil** [kubernetes/kubernetes#57535]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I found an odd phenomenon about image size,  the size of v1.5.1 is much smaller than that of v3.6.1. See below:
**v1.5.1**
![v1 5 1](https://user-images.githubusercontent.com/4462994/34282543-270af552-e701-11e7-8f0f-e6318f888c31.png)
**v3.6.1**
![v3 6 1](https://user-images.githubusercontent.com/4462994/34282550-312c89c4-e701-11e7-8fb6-c57e3d01e743.png)
**Detailed Comparison Table**
![table](https://user-images.githubusercontent.com/4462994/34282576-735bc4ae-e701-11e7-9a15-11815dff995d.png)

So I checked each Dockerfile,  found no big difference except the deployment way of docker-registry binary, which is `COPY bin/dockerregistry /dockerregistry` in v1.5.1 while `yum --enablerepo=origin-local-release install -y origin-dockerregistry` in v3.6.1. 
Below is complete Dockerfile:
**v1.5.1**

> FROM openshift/origin-base
> COPY config.yml $REGISTRY_CONFIGURATION_PATH
> COPY bin/dockerregistry /dockerregistry
> LABEL io.k8s.display-name="OpenShift Origin Image Registry" \
> io.k8s.description="This is a component of OpenShift Origin and exposes a Docker registry that is integrated with the cluster for authentication and management."
> USER 1001
> EXPOSE 5000
> VOLUME /registry
> ENV REGISTRY_CONFIGURATION_PATH=/config.yml
> CMD DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_SERVICE_HOST}:${DOCKER_REGISTRY_SERVICE_PORT} /dockerregistry ${REGISTRY_CONFIGURATION_PATH}

**v3.6.1**

> FROM openshift/origin-base
> RUN INSTALL_PKGS="origin-dockerregistry" && \
> yum --enablerepo=origin-local-release install -y ${INSTALL_PKGS} && \
> rpm -V ${INSTALL_PKGS} && \
> yum clean all
> COPY config.yml ${REGISTRY_CONFIGURATION_PATH}
> LABEL io.k8s.display-name="OpenShift Container Platform Image Registry" \
> io.k8s.description="This is a component of OpenShift Container Platform and exposes a Docker registry that is integrated with the cluster for authentication and management." \
> io.openshift.tags="openshift,docker,registry"
> USER 1001
> EXPOSE 5000
> VOLUME /registry
> ENV REGISTRY_CONFIGURATION_PATH=/config.yml
> CMD /usr/bin/dockerregistry ${REGISTRY_CONFIGURATION_PATH}
Could someone explain to me?
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ncdc** [comment]
The images you reference are from OpenShift. I'd recommend asking the OpenShift team about them. You can find them at https://github.com/openshift/origin/
