### ISSUE TITLE
Enable gitRepo Volume on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#57546]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
gitrepo on Windows is not supported yet as git is not built-in on Windows host now

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. create a pod with gitrepo mount on windows
kubectl create -f https://raw.githubusercontent.com/andyzhangx/Demo/master/windows/gitrepo/aspnet-gitrepo.yaml

2. watch kubectl describe po aspnet-gitrepo
```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  1m            1m              1       default-scheduler                       Normal          Scheduled               Successfully assigned aspnet-gitrepo to 36830k8s9000
  1m            1m              1       kubelet, 36830k8s9000                   Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-g35gn"
  1m            1s              8       kubelet, 36830k8s9000                   Warning         FailedMount             MountVolume.SetUp failed for volume "git-volume" : failed to exec 'git clone https://github.com/andyzhangx/Demo.git':
 : executable file not found in %!!(MISSING)P(MISSING)ATH%!!(MISSING)(NOVERB)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign
@PatrickLang for awareness

**Comment by jdumars** [comment]
Removing the SIG-Azure label, since this appears to be Windows-specific.
