### ISSUE TITLE
Implement the cluster bootstrap API

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#5754]
Pulled out of [#2303](https://github.com/GoogleCloudPlatform/kubernetes/issues/2303#issuecomment-62776961):

Task list:
- [ ] Finish definition of the bootstrap API
- [ ] Implement a new binary/mode for serving the bootstrap API
- [ ] Host the bootstrap API on k8s.io
- [ ] Have the unified binary race to be the master via the bootstrap API.  Have it publish it's location.
- [ ] Have the minion use the bootstrap API to find the api server and self-register
- [ ] Have kubectl use the bootstrap API to find the api server (and CA for the api server).

---

Quick spec that could work for bootstrap service.
# Kubernetes Cluster Bootstrap API

When bootstrapping up a cluster, there are two things that we need to do: Identify the master of the cluster (for both worker nodes and clients) and establish the 'admin' credentials for administering the cluster.

The Kubernetes Cluster Bootstrap API is optional -- it is possible to get clusters started without using this API.  It is also possible to easily run this API inside of a constrained private network.

The basic flow -- some of these steps are optional to further lock down the security of the cluster.
1. The user creates a new cluster.  This is typically an unauthenticated operation.  As a result of creating the cluster, the user gets back a set of information:
   - A `cluster-id` that is used as part of the `cluster-bootstrap-url`.  This should be guarded but is not super sensitive.
   - A `bootstrap-auth-token`.  This is a single use token.  It can be used to establish a single writer into the bootstrap API.  It is typically time bounded (1 hour?)
   - Credentials for the cluster admin account.  This includes a public cert and a private key used for TLS client auth.
2.  The user starts up a set of servers and gives them the `cluster-bootstrap-url` along with the `bootstrap-auth-token`.
3. The servers boot up and race to see who can claim to be master.  They do this using the `bootstrap-auth-token`.  Only one wins and writes its addresses to the bootstrap API.
4. Other servers that don't win the race use the bootstrap API to find the master.  They then register themselves with the master.  If the master automatically accepts those workers or not is a matter of policy out of scope of the bootstrap API.
5. The server that won the master race can add more 'writer' keys to the bootstrap API.  That way if the master dies a new master can be elected and update the bootstrap API.
6. The user uses a Kubernetes client (kubectl) to talk to the cluster.  They can either specify the appropriate config data directly or can simply specify the `cluster-bootstrap-url`.  `kubectl` will use the admin key with client TLS to identify itself to the master.
7. From here more scoped (password?) auth can be configured and the cluster can be further configured.

Further notes:
- The user can create/supply their own admin public cert when creating the cluster.  Or they can opt out of using the bootstrap API to set up the admin credentials altogether.  The admin cert can be cleared at any time.
- The IP range that the master claims can be restricted to a known good range.
## API Definition
- `<base>` **must** be over TLS.  We would host a public one on `https://k8s.io`.
- Auth:
  - All auth is done via client TLS certs.  There are three levels of auth:
    - `none` -- this method/endpoint is publicly accessible.  The random `cluster-id` is the only protection.
    - `bootstrap-cert` -- this method/endpoint is accessible to any cert in the bootstrap-cert list or the admin-cert.
    - `admin-cert` -- this method/endpoint is only accessible to the admin-cert.  If there is no admin-cert or the admin-cert is lost, this can never be modified or accessed.
- `<base>/k/`
  - `POST`: creates a new cluster bootstrap endpoint.
    - Auth: `none`
    - Post body:
      - admin client options -- `NONE`, `CREATE`, or specify a cert
      - bootstrap cert -- list of certificates that can be used to write to the bootstrap API.
      - bootstrap token request -- true (with time limit) if a bootstrap token should be returned.
      - master IP range -- the master IP must be confined to this range.
    - Response:
      - cluster id -- long random string
      - cluster url -- `<base>/k/<cluster-id>`
      - bootstrap token
      - The public cert and private
- `<base>/k/<cluster-id>/bootstrap-certs` This is the list of TLS client certs that are allowed to write to the bootstrap API endpoint.
  - `GET`: returns the list of bootstrap-certs along with the time and IP address that added them.
    - Auth: `bootstrap-cert`
  - `PUT` - updates the list of bootstrap-certs.  Users **must** use an ETag to ensure that concurrent writes aren't clobbered.  The admin-cert cannot be modified with this method.
    - Auth: `bootstrap-cert`
- `<base>/k/<cluster-id>/claim-token`  Used to add an entry to the bootstrap-cert list via a token.
  - `POST`
    - Auth: None, but must present valid one use token
    - Returns: Nothing, 200 if everything is good.
- `<base>/k/<cluster-id>/mint-token` Create a new one use token that can be used to add a `bootstrap-cert`
  - `POST`
    - Auth: `bootstrap-cert`
    - Post Body: the time limit.  Up to 24 hours.
    - Response: The token.
- `<base>/cluster-meta/<cluster-id>/admin-cert`
  - `GET`: Gets the public key used for the admin account.
    - Auth: `bootstrap-cert`
  - `PUT`: Sets a new admin key. Can be cleared completely in which case there _is_ no admin key.
    - Auth: `admin-cert`
- `<base>/cluster-meta/<cluster-id>/master`.  This is used to get/set the current master for the cluster.
  - This resource includes:
    - The current IP of the master.  This is what other nodes in the cluster should use.
    - Preferred IPs or DNS names for clients.  This is a priority list from most likely to least likely.
    - The CA cert used for server identification.  If blank, then any system trusted CA would suffice.
  - `GET`: Gets the current master.
    - Auth: `none`
  - `PUT`: Sets the master.
    - Auth: `bootstrap-cert`
    - Optimistic concurrency here -- the user **must** use ETag to make sure that they aren't clobbering others in a start up race.

cc @kubernetes/sig-cluster-lifecycle

**Comment by smarterclayton** [comment]
What would we need to do to make OpenShift also be able to support this (when running in Kube-integrated mode)?

**Comment by roberthbailey** [comment]
The idea (from [clustering.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/clustering.md)), is that you'd point each kubelet at the bootstrap API when it starts up and it would find the appropriate cluster to join and do so securely (possibly) without any human intervention. Basically, this would make it more seamless to get a cluster up and running in a secure manner because you wouldn't have to handle key distribution yourself. 

For OpenShift, this may not actually be necessary/useful; "static" clustering, which will be implemented first (and for 1.0) may be sufficient for you.

If you want to use "dynamic" clustering, then for OpenShift you'd need to point the kubelets at a bootstrap endpoint. You could use the standard endpoint (proposal is to host it on https://k8s.io) or you could set a custom endpoint (e.g. running on a private network).

**Comment by smarterclayton** [comment]
> On Mar 22, 2015, at 11:55 PM, Robert Bailey <notifications@github.com> wrote:
> 
> The idea (from clustering.md), is that you'd point each kubelet at the bootstrap API when it starts up and it would find the appropriate cluster to join and do so securely (possibly) without any human intervention. Basically, this would make it more seamless to get a cluster up and running in a secure manner because you wouldn't have to handle key distribution yourself.
> 
> For OpenShift, this may not actually be necessary/useful; "static" clustering, which will be implemented first (and for 1.0) may be sufficient for you.
> 
> If you want to use "dynamic" clustering, then for OpenShift you'd need to point the kubelets at a bootstrap endpoint. You could use the standard endpoint (proposal is to host it on https://k8s.io) or you could set a custom endpoint (e.g. running on a private network).
> 
I think for the open source version k8s.io is a good place to point.  @liggitt in case you weren't following this yet.

**Comment by bgrant0607** [comment]
cc @kelseyhightower

**Comment by mikedanese** [comment]
Both etcd and swarm have this. I think the next piece of work here is to take this draft and turn it into a proposal.

https://github.com/docker/swarm/tree/master/discovery
https://github.com/coreos/discovery.etcd.io

cc @davidopp @fgrzadkowski @polvi

**Comment by davidopp** [comment]
@colemickens

**Comment by bgrant0607** [comment]
Ref #20439

**Comment by mikedanese** [comment]
As an alternative to this API, @jdef proposed using SRV, and TLSA records.

cc @quinton-hoole who was advocating DNS over a custom service.

**Comment by roberthbailey** [comment]
@jdef Can you expand on that a bit? Would each cluster have it's own set of records, and thus it's own unique domain name?

**Comment by mikedanese** [comment]
I think we could trim this proposal down or find a way to break it up to focus on the problem domain:

* Nodes find the API.
* Nodes trust the API.

and separate the bits:

* API trusts the node. (covered by #23172)
* Bring up a control-plane.

This greatly reduces the scope of the project. IIUC, @jdef proposed SRV/TLSA as a solution to the smaller problem domain.

**Comment by smarterclayton** [comment]
SRV/TLSA is complicated to do in many non cloud environments.  Zone
files are tightly controlled.  It's nice as an option.

**Comment by gtank** [comment]
Agree that DANE probably isn't what we want to rely on here. I have no objection to supporting it, but it is a complex dependency for a feature that should make clustering easier.

**Comment by mikedanese** [comment]
> I think we could trim this proposal down or find a way to break it up to focus on the problem domain:
> 
> Nodes find the API.
> Nodes trust the API.

What follows is a simplified strawman that solves the quoted problem domain.

Cluster automation does:
```
curl -XPOST -d @ca.crt https://bootstrap.k8s.io/new?size=3
> {"clusterID":"38513a77a48c378e3130cbf64e3b8d5c5329003eeb257e52c807be9fbe13be54"}
```
The clusterID is a 256bit random string. This creates a resource at path:
```
https://bootstrap.k8s.io/<cluster-id>
```
with type
```go
type ControlPlaneEndpoint struct {
    api.TypeMeta
    ObjectMeta api.ObjectMeta

    RootCertificateAuthorityPublicKey string
    Endpoints []string
}
```
apiservers are started with --cluster-id <cluster-id> and register PATCH the resource at the path to add their URL (protocol://hostname:port or --advertise-address) to a list of Endpoints. Once the Endpoints array contains <size> entries the resource becomes read only. <size> should be equal to the --master-count config parameter on apiserver binary.

Kubelets joining the cluster are started with --cluster-id and discover the API servers certificate and endpoint by querying the well known location of the bootstrap API.

We would implement a self hostable bootstrap API for airgapped clusters but host a default API off of the k8s.io domain.

**Comment by bgrant0607** [comment]
Question from another thread: Why is it easier to parameterize kubelets with cluster-id than with apiserver address? Or is that not the problem this is intended to solve?

**Comment by mikedanese** [comment]
The list of apiserver endpoints as well as the root ca.crt are distributed through the bootstrap api. These parameters may change over the lifetime of the cluster, but the cluster-id will not. cluster-id is a "const pointer" to the current values of these parameters.

Lesser benefits:
* one paramter is better than two.
* uid's are easier to distribute than ca.crts and uuids are easier to pass on the command line.

**Comment by mikedanese** [comment]
The cluster-id can also double as a preshared secret to authorize the creation of a certificate signing request in the kubelet TLS bootstrap flow. While it's not neccessary to have an cluster bootstrap API behind the cluster-id for this, it does integrate the two bootstrap steps nicely.

**Comment by zhouhaibing089** [comment]
> API trusts the node. (covered by #20439)

@mikedanese I am a little bit confused here, #20439 is about getting certificates for kubelet, how could it cover `API trusts the node`? IIUC, when kubelet posts CSR requests to api-server, api-server does not have a way to say "I trust you", right?

**Comment by kargakis** [comment]
@jbeda @luxas is this fixed now?

**Comment by mikedanese** [comment]
This was subsumed by certs api and discovery api.

**Comment by jbeda** [comment]
Agreed.  Yay!
