### ISSUE TITLE
ceph rbd device path missed in Node.Status.VolumesAttached

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#57544]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

If a ceph rbd PVC was used, its `DevicePath` in `Node.Status.VolumesAttached` will always be empty, even though it has been already mounted on the machine.

**What you expected to happen**:

The reason is: Currently, `AttachDetachController` is responsible for updating `Node.Status.VolumesAttached`, using the returned parameter of volume plugin's `Attach` method as the volume's `DevicePath`. However, the `Attach` method for rbd volume plugin does nothing, and the real attach operation is performed by `WaitForAttach` method, which is invoked inside `operationGenerator.GenerateMountVolumeFunc` or `operationGenerator.GenerateMapVolumeFunc`, by kubelet. `WaitForAttach` method returns the real device path, but not updated to the `Node.Status` ever.

Candidate solutions:

1. A simple solution is we update the volume's `DevicePath` in `Node.Status` just after the `WaitForAttach` operation succeeded(inside `operationGenerator.GenerateMapVolumeFunc` and `operationGenerator.GenerateMountVolumeFunc`), and fail the whole map/mount operation if the update operation failed. This solution is enough for our demand, but may bring more pressure to `etcd`. If this is a problem, we can make `WaitForAttach` to return a bool value indicating whether the `DevicePath` updated or not, and only update node's status if `DevicePath` updated.
The node status update operation maybe look like this:

```go
func (og *operationGenerator) updateNodeStatus(volumeName v1.UniqueVolumeName, devicePath, nodeName string) error {
	if len(volumeName) == 0 || len(devicePath) == 0 || len(nodeName) == 0 {
		return nil
	}
	glog.V(5).Infof("Update node %s status: volume: %s, device path: %s", nodeName, volumeName, devicePath)

	// Fetch current node object
	node, fetchErr := og.kubeClient.CoreV1().Nodes().Get(nodeName, metav1.GetOptions{})
	if fetchErr != nil {
		return fetchErr
	}
	originNode := node.DeepCopy()

	updated := false
	for i := range node.Status.VolumesAttached {
		attachedVolume := &node.Status.VolumesAttached[i]
		if attachedVolume.Name == volumeName && attachedVolume.DevicePath != devicePath {
			updated = true
			attachedVolume.DevicePath = devicePath
			break
		}
	}
	if !updated {
		return nil
	}

	_, updateErr := nodeutil.PatchNodeStatus(og.kubeClient.CoreV1(), types.NodeName(nodeName), originNode, node)
	return updateErr
}
```

2. A more elegant solution is updating the `DevicePath` cached in `ActualStateOfWorld`, and update the `DevicePath` in `Node.Status.VolumesAttached` periodically by kubelet. But there's a tricky situation: If kubelet restarts between the volume mounted and `Node.Status` reported, we need a method to find the volume's device path and report it again. A possible solution is that using `mount.GetDeviceNameFromMount` to find `DevicePath` by `GlobalMountPath`. This may make the implement complicated.

I'm inclined to be the first one. Do we have any other better options? If not, I will submit a PR for the first solution later.

**Comment by mlmhl** [comment]
@kubernetes/sig-storage-bugs

**Comment by rootfs** [comment]
this is true for all non-hypervisor assisted volumes (iscsi, fc, rbd). we are looking for a new attach/detach approach

cc @mtanino

**Comment by mlmhl** [comment]
Yeah, we can discuss a better approach here @rootfs  @saad-ali  @mtanino

**Comment by mtanino** [comment]
@mlmhl @rootfs 

Could you let me know the exact steps which problems happens?

As @rootfs mentioned above, DevicePath in the volume object isn't updated for all non-hypervisor assisted volumes. I proposed following approach to update volume object and then save devicePath to etcd.

https://github.com/kubernetes/kubernetes/issues/54108
https://github.com/kubernetes/kubernetes/pull/54264

But this approach wasn't accepted.
As @saad-ali mentioned in the following PR and issue, rbd, iSCSI and FC plugin need be updated to use attacher/detacher just only for the purpose of accessMode check. But currently I think we don't have enough bandwidth to update this.
I think current recommended way to get devicePath is using GlobalMountPath or store parameter file on GlobalMountPath as you mentioned.

By the way, you are mentioning that Mapped operations for RBD plugin, but the plugin haven't supported Block Volume yet. It's on going at https://github.com/kubernetes/kubernetes/pull/56651

**Comment by mlmhl** [comment]
Nice explanation @mtanino . The problem I mentioned above is that when a user submits a `Pod` with a rbd volume, the whole work flow of this volume are:

1. A/D controller finds this volume and invokes `Attach` method of rbd volume plugin, this method will do nothing of rbd, see [here](https://github.com/kubernetes/kubernetes/blob/dc44a3174c0aec1c2138dbeb9d81552618004bd2/pkg/volume/rbd/attacher.go#L80).

2. kubelet finds this volume and invokes `OperationGenerator.GenerateMountVolumeFunc` to mount this volume. This method will perform following operations in turn:
    - invoke `WaitForAttach` method of volume plugin, this method will execute `rbd map ..` command(see this [code](https://github.com/kubernetes/kubernetes/blob/dc44a3174c0aec1c2138dbeb9d81552618004bd2/pkg/volume/rbd/rbd_util.go#L232)) for rbd plugin. After this method, the volume is mapped to current node
    - invoke `MountDevice` method of volume plugin and mark this device mounted if succeeded(by `actualStateOfWorld.MarkDeviceAsMounted`)
    - invoke `SetUp` method of volume mounter, and mark the volume as mounted if succeeded(by `actualStateOfWorld.MarkVolumeAsMounted`)

The `umount` and `rbd unmap ..` operations will be invoked in `OperationGenerator.GenerateUnmountDeviceFunc`.

Suppose an error occurs between `WaitForAttach` and `MountDevice`(for example [resizeFileSystem](https://github.com/kubernetes/kubernetes/blob/dc44a3174c0aec1c2138dbeb9d81552618004bd2/pkg/volume/util/operationexecutor/operation_generator.go#L500) or [GetDeviceMountPath](https://github.com/kubernetes/kubernetes/blob/dc44a3174c0aec1c2138dbeb9d81552618004bd2/pkg/volume/util/operationexecutor/operation_generator.go#L506) return an error), the whole `GenerateMountVolumeFunc` method fails immediately and doesn't mark the device as mounted. If the pod was deleted before kubelet's next attempt, kubelet won't invoke `GenerateUnmountDeviceFunc` for this volume as we doesn't mark the device as mounted. so the volume is left as mapped state and can not map to other node any more.

By the way, do we have any plan to refactor the attach/detach mechanism of rbd, iSCSI and FC plugin?

**Comment by mtanino** [comment]
@mlmhl 
I think this problem is related to item `Improve local volume attaching (iscsi, etc.)` on sig-storage planning list, but currently no one assigned to it. We are looking for volunteer for this refactor, so if you can try, it's very helpful.

**Comment by mlmhl** [comment]
@mtanino 
I'm very glad to help moving this refactor along. I'm not sure if we have any existing issue or feature to track this, is this the issue #54108?

**Comment by mtanino** [comment]
@mlmhl 
Great! thank you for the help.
Seems only Kubernetes member can be assigned to the issue, but feel free to open new PRs and use issue #54108 for it.

Also if you also want to help `Improve local volume attaching (iscsi, etc.)` on sig-storage planning list, I recommend to attend bi-weekly sig-storage meeting and talk to @saad-ali about your voluntary contribution. Then he can assign you to the item.

Kubernetes Storage SIG Meeting Notes/Agenda
https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit#heading=h.2nsyf0bggxox

**Comment by rootfs** [comment]
@mlmhl thanks, help is welcome

**Comment by mlmhl** [comment]
Thanks @mtanino , @rootfs . I will try my best and post any progress in issue #54108 .
