### ISSUE TITLE
Enable iSCSI volume on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#57548]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
iSCSI is not supported on Windows because symbolic link does not work on Windows, depends on a moby issue fix: [Symlink for ca.crt & token files are broken on windows containers](https://github.com/kubernetes/kubernetes/issues/52419)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/assign
@PatrickLang I know someone from Windows team is working on this, could you @ this person? Thanks.

**Comment by PatrickLang** [comment]
Flexvolume plugin for iSCSI here: https://github.com/Microsoft/K8s-Storage-Plugins

**Comment by PatrickLang** [comment]
@andyzhangx - should we close since https://github.com/Microsoft/K8s-Storage-Plugins is available?
