### ISSUE TITLE
Make kubernetes/staging/src/k8s.io/foo the authoritative source for all files that live in kubernetes/foo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#57559]
This is like #54398 but I'd like to get consensus that everything except `vendor/` should be moved over, not just README and LICENSE files.  

I bumped into this (undocumented?) policy that staging is authoritative when I was trying to get a consistent code-of-conduct.md checked in everywhere, which led me to open #57473

Now I'd like to get CONTRIBTUING.md files that state this policy (no PR's here, go to kubernetes/kubernetes), and finishing syncing over all files that are in repo roots.  Please comment here if there are files that can't be synced over

```
spiffxp@whodis:k8s.io (master %)$ for d in $(ls -1 | grep -v .txt); do echo ...$d...; ls -a1 $d >staging-$d.txt; ls -a1 ~/w/kubernetes/$d >published-$d.txt; diff -yW60 --suppress-common-lines {staging,published}-$d.txt; done | grep -v '\(.git\|vendor\)$'
...api...
...apiextensions-apiserver...
...apimachinery...
			     >	hack
...apiserver...
			     >	hack
...client-go...
			     >	.github
			     >	.travis.yml
			     >	CHANGELOG.md
			     >	INSTALL.md
			     >	README.md
...code-generator...
...kube-aggregator...
...metrics...
			     >	CONTRIBUTING.md
LICENSE			     |	IMPLEMENTATIONS.md
			     >	code-of-conduct.md
...sample-apiserver...
			     >	.gitignore
...sample-controller...
```

**Comment by spiffxp** [comment]
/cc @kubernetes/sig-api-machinery-proposals
since the majority of the published repos are api-machinery related

/cc @sttts @kubernetes/kubernetes-staging-publish-cops 
since we talked about this on slack and I'm trusting the cops to know if this is the correct policy

**Comment by sttts** [comment]
There is no technical reason to have any file in the external repos that is not authorative in staging/. 

As client-go has a slightly different release cycle (= is released some days after the kube release), it might make sense to keep markdown files (CHANGELOG, README, INSTALL) external.

We can start a discussion to move those files also into k/k **and** to synchronize the published repos with the kube release. If we do that, we have to make client-go releases blocking for kube. I am not completely sure whether the benefit outweights the synchronization/communication overhead though. While it will be good to have day-one client-go releases, this also means that we have to create developer changelogs in time and test vendoring (godep, glide, dep) in time. The release team in its current form does not have this as a focus and would probably need another role which is responsible for that topic. Do we want that?

**Comment by sttts** [comment]
metrics/CONTRIBUTING.md+IMPLEMENTATIONS.md should move, @DirectXMan12

**Comment by lavalamp** [comment]
This is not api machinery specific.

**Comment by sttts** [comment]
@spiffxp can you exclude the client-go README, INSTALL.md and CHANGELOG to move this topic forward? client-go needs further discussion and thoughts around the release process.

**Comment by spiffxp** [comment]
@sttts I think I'm doing what you've asked in #57571, the only client-go files I'm adding to k/k staging are:
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- CONTRIBUTING.md

**Comment by sttts** [comment]
> I think I'm doing what you've asked in #57571

Yes, just make sure those files are removed from the client-go repo before. After that #57571 can go in.

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/client-go/pull/356 to remove the .md files.  Will leave the .travis.yml file there for now

**Comment by spiffxp** [comment]
Will wait to see what the results of the latest sync bring

**Comment by spiffxp** [comment]
/close

I'm going to call this done.  Moving the markdown files out of client-go to here would require rescoping the release cycle.

```
...api...
...apiextensions-apiserver...
BUILD			     <
...apimachinery...
...apiserver...
...client-go...
			     >	.travis.yml
			     >	CHANGELOG.md
			     >	INSTALL.md
			     >	README.md
...code-generator...
...kube-aggregator...
BUILD			     <
...metrics...
...sample-apiserver...
BUILD			     <
...sample-controller...
BUILD			     <
```
