### ISSUE TITLE
Can't ping service in same kubernetes namespace

### ISSUE THREAD

**Issue by vistalba** [kubernetes/kubernetes#57556]
BUG REPORT

**What happened**:
I try to ping a service in the same namespace.
Ping is not working but http works fine.

**What you expected to happen**:
Ping should answer.

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: standalone
- OS (e.g. from /etc/os-release): ubuntu 16.04 lts
- Kernel (e.g. `uname -a`): 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by m1093782566** [comment]
@vistalba 

Ping ClusterIP never works - ClusterIP is a virtual IP and you can't ping it.
