### ISSUE TITLE
Kubectl doesn't respect --user parameter when execution create clusterrolebinding

### ISSUE THREAD

**Issue by mpashka** [kubernetes/kubernetes#57555]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig area/kubectl
/sig sig/cli

**What happened**:
If default user is configured in kubectl. When applying kubectl command:
kubectl --user='admin' create clusterrolebinding <role_name> --clusterrole=view --group=<group_name>
Kubectl ignores --user parameter. And I get error
Error from server (Forbidden): User "<default_user>" cannot create clusterrolebindings...

**What you expected to happen**:
This should result in creating appropriate clusterrolebinding on behalf of admin user.
admin user is to be used for api server authentication, not viewer.

**How to reproduce it (as minimally and precisely as possible)**:
Setup kubernetes cluster.

Configure kubectl. Create cluster configuration, context, 2 users, set default context. To reproduce this issue create two users in kubectl config - one user with permissions to create clusterrolebinding (admin) and another without (viewer). Set user without permissions (viewer) as default for context.

Apply kubectl create clusterrolebinding with different user specified. E.g.
kubectl --user='admin' create clusterrolebinding <role_name> --clusterrole=view --group=<group_name>

Instead of successfully created clusterrolebinding I get error message:
Error from server (Forbidden): User "viewer" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope. (post clusterrolebindings.rbac.authorization.k8s.io)

**Anything else we need to know?**:
There are at least 2 workarounds:
Specify admin user as default in kubectl config
Create file with clusterrolebinding and apply kubectl create -f <file_name>

**Environment**:
- Kubernetes version (use `kubectl version`): This is kubectl bug. I checked this with kubectl 1.7.11 and 1.9.0
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

@kubernetes/sig-cli-bugs

**Comment by mpashka** [comment]
@kubernetes/sig-cli-bugs

**Comment by php-coder** [comment]
Maybe it's better to fill the issue there: https://github.com/kubernetes/kubectl/issues

**Comment by mpashka** [comment]
Created an issue in kubectl: https://github.com/kubernetes/kubectl/issues/188
