### ISSUE TITLE
The plugin directory is not useful

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#57579]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

There is not much value in keeping a few components in plugin/cmd/ and plugin/pkg when everything else lives in cmd/ and pkg/

**What you expected to happen**:

Components that would be moved:
plugin/cmd/kube-scheduler
plugin/pkg/scheduler

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @thockin 
/sig scheduling

**Comment by ravisantoshgudimetla** [comment]
@misterikkit - I believe this could be closed since the PR got merged.

**Comment by misterikkit** [comment]
@ravisantoshgudimetla I have moved the scheduler out of plugin, but admission and auth remain.

**Comment by ravisantoshgudimetla** [comment]
Thanks @misterikkit, I was too hasty in my earlier comment. Can you please break this into sub-issues or remove sig-scheduling label. The only problem I have with single issue with all the labels is if I query for issues with sig-scheduling label, this issue shows up even though there is no action item remaining on the scheduling side.

**Comment by misterikkit** [comment]
I have modified this issue to be scheduler-specific, and I will file new ones for the remaining work.

**Comment by ravisantoshgudimetla** [comment]
Thanks @misterikkit
