### ISSUE TITLE
Kubernates cannot get nodes error

### ISSUE THREAD

**Issue by ganeshmedhekar** [kubernetes/kubernetes#57598]
Hi,
We are deploying kubernates 1.8 setup on AWS private VPC which is having DHCP enabled with our AD running on AWS EC2 instance. We are using Route 53 subdomain.
The setup complete but when we run the below command find the issiue with the DNS resolution.
Command and error:
$ kops validate cluster
Using cluster from kubectl context: test-cluster.example.com

Validating cluster test-cluster.example.com

cannot get nodes for "test-cluster.example.com": Get https://api.test-cluster.example.com/api/v1/nodes: dial tcp xxx.xxx.xxx.xxx:443: i/o timeout

**Comment by ganeshmedhekar** [comment]
Require immediate help on this.  thanks @freeformz @brosner @gnufied @ncdc

**Comment by dims** [comment]
you are probably better off opening an issue in https://github.com/kubernetes/kops/issues

**Comment by ganeshmedhekar** [comment]
Thanks!
