### ISSUE TITLE
Kubernetes should not mount default service account credentials by default

### ISSUE THREAD

**Issue by vincentwoo** [kubernetes/kubernetes#57601]
> /kind bug

**What happened**:

Kube [automounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) default service account credentials, which allows any compromised pod to run API commands against the cluster. This seems like a very odd choice from a security standpoint - I only just discovered this was the case after a couple years of running a Kube cluster in production.

**What you expected to happen**:

Pods not having cluster-modifying power by default.

**How to reproduce it (as minimally and precisely as possible)**:

Run a default Kube cluster and pod.

**Anything else we need to know?**:

n/a

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.1", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-12-08T17:24:53Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE

**Comment by nielsole** [comment]
This shouldn't be the case of you use RBAC if I read the docs correctly: https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions
Which authorization plugin do you use?

**Comment by vincentwoo** [comment]
I'm not using any as far as I am aware. I am running default GKE.

**Comment by dixudx** [comment]
@vincentwoo There are several options for this. You can choose one based on your needs.

* Using RBAC to grant limited access to certain namespaces/resources. You can revoke the access at anytime.
* Create another serviceaccount  and use `Initializer` to inject this to new-created pods automatically, which will override default serviceaccount. Revoke at anytime.
* Most convenient way to  opt out of automounting API credentials for a service account is to  set `automountServiceAccountToken: false` on the service account for version 1.6+.
* For a single pod, you can also opt out of automounting API credentials for a particular pod by setting `automountServiceAccountToken: false` in `PodSpec`.

**Comment by vincentwoo** [comment]
I definitely opted out when I figured it out, but I was posting an issue because I don't think users understand that (at least on GKE) write-level credentials get mounted by default. If that's correct, it seems very dangerous.

**Comment by vincentwoo** [comment]
Upon attempting to reproduce this on a fresh GKE cluster, my default service account did not have sufficient permissions. I'm closing this one as user error - either my cluster is old and the default changed, or I did something crazy earlier that I no longer remember.

**Comment by gflarity** [comment]
I still see this on new clusters. The Default service account gets mounted that user has the keys to the kingdom. See: https://hackernoon.com/capturing-all-the-flags-in-bsidessf-ctf-by-pwning-our-infrastructure-3570b99b4dd0

**Comment by krmayankk** [comment]
I think there are two layers of security, authentication and authz. The more layers we have to prevent an attack the better. Currently the model is that a pod will always mount the token by default. this makes them talk to apiserver and be able to authenticate, but they dont have permission to do anything. If an attacker is able to somehow hack that layer of authz, he has full access.
So in my mind the write thing to do is disable mounting the token by default. reopening this hence

/reopen
@kubernetes/sig-auth-bugs for comments ?

**Comment by liggitt** [comment]
disabling by default is not backwards compatible, so is not a realistic option until (if) a v2 Pod API is made

**Comment by BenTheElder** [comment]
@liggitt what about the deployment tools agreeing to configure the default service account with `automountServiceAccountToken: false` for new clusters? Technically this wouldn't be changing the API as far as I can tell?

**Comment by mikedanese** [comment]
Deployment tools are free to do that if they are ok with breaking users on upgrade, although this isn't something that e.g. GKE could do.

**Comment by BenTheElder** [comment]
> ... if they are ok with breaking users on upgrade

To be clear I was only suggesting on wholly new clusters at some new version of the $DEPLOYER.
Is that really an unreasonable change? 

Taking GKE for example -- didn't an update stop deploying the dashboard by default for new clusters but it could still be opted into, which would also be true for configuring the default service account? Or when RBAC became default?

**Comment by mikedanese** [comment]
I'm not implying that it's unreasonable, just that it's going to be a hard pill to swallow for GA distributions of Kubernetes. I could see this happening in the [v2](https://github.com/kubernetes/kubernetes/issues/8190) pod API.

**Comment by Nowaker** [comment]
Instead of changing the default for everyone, can we at least get a configuration option for that?

I'm not super-familiar with Kubernetes internals, but maybe it would belong to Kubernetes API server, which could be configured to autoset `automountServiceAccountToken: false` if `automountServiceAccountToken` is not explicitly defined.

**Comment by BenTheElder** [comment]
@Nowaker you can set this on the service account https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

So for example `kops` could opt to set this on the default service account: `automountServiceAccountToken: false`

**Comment by Nowaker** [comment]
@BenTheElder Creating a new namespace auto-creates a new service token that is set to automount so it's not a viable solution. Any other suggestions how we can ensure `automountServiceAccountToken: false` is a default?

**Comment by Nowaker** [comment]
Note: my coworker just found https://github.com/karydia/karydia.

> Karydia inverts the following insecure default settings:
>
> - **Unmount service account token**
> - Restrict system calls by adding a seccomp profile
> - Run with minimal privileges by adding a non-root user
> - Disallow privilege escalation
> - Restrict network communication by automatically adding one or multiple network policies to each namespace

While I'm happy with the workaround, the idea that one has to use a third party service to revert some insecure default settings is still pretty mind boggling.

**Comment by Nowaker** [comment]
This is a valid security concern, shouldn't be closed.

/reopen

**Comment by Nowaker** [comment]
Still a valid concern.

**Comment by matoszz** [comment]
Also, is anyone aware of how to simply set a newly created service account as the namespace "default"? There appears to be no way of even creating a new account and using that as the default pods would assume.

**Comment by dwdraju** [comment]
@matoszz I don't think we cannot set custom serviceAccount with other name as default unless explicitly specifying on pod definition:
```
spec:
  containers:
  - image: nginx
    name: nginx
  serviceAccountName: nginx-sa
```

**Comment by knrt10** [comment]
DId someone found the solution to this?

**Comment by sgandon** [comment]
Is there a way to specify a template for the *default* service account that is being used when a new namespace is created ? because that would be a ways of solving this issue I believe.

**Comment by knrt10** [comment]
One way to do it is by mutating the admission controller, and then patch `automountServiceAccountToken: false` to it, so that when a user creates new namespace it won't be mounted.

**Comment by sftim** [comment]
> ability to set global behavior for the default user settings within namespaces

The thing Kubernetes uses to achieve that is quite often an admission controller.

**Comment by liggitt** [comment]
Implementing this would be a significant compatibility break. I don't see a reasonable way to roll out this requested change as default Kubernetes behavior.

/close

**Comment by ecki** [comment]
I think with RBAC and a non-priveledged default SA this is lass of an issue nowadays. Would still be good if Umsetzung the automount for the default Account is a bit less noisy (if you apply a new namespace and a default Account, even when it is in the Same yaml Bauch the SA default gets autocreated, causing kubectl to warn about applying to a not-owned object. So would be good to not even Create them by (new api) defaults.
