### ISSUE TITLE
Move `KubeControllerManagerConfiguration` to `pkg/controller/apis/`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#57618]
The `KubeControllerManagerConfiguration` that is now located in `pkg/apis/componentconfig` should be moved out to `pkg/controller/apis/kubecontrollermanagerconfig` instead

Relevant issues/PRs:
 - https://github.com/kubernetes/kubernetes/issues/53577
 - https://github.com/kubernetes/kubernetes/pull/54211
 - https://github.com/kubernetes/kubernetes/pull/53645
 - https://github.com/kubernetes/kubernetes/pull/55234
 - https://github.com/kubernetes/kubernetes/pull/49051
 - https://github.com/kubernetes/kubernetes/issues/52428
 - https://github.com/kubernetes/kubernetes/pull/52562

@xiangpengzhao has showed interest in helping with this. There is more work to be done that moving indeed, but moving to its own API group/directory is a good first step on our way to beta and beyond for ComponentConfig for the k-c-m. I think @cheftako might be able to help with this at some point in the future as well, maybe with cleaning up the API types/adding structure/etc when prepping for beta (i.e. https://github.com/kubernetes/kubernetes/issues/52428)

We're hoping to get this usable in at least alpha for v1.10

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-architecture-feature-requests

**Comment by madhuri-rai07** [comment]
@luxas Hi, I am looking to contribute to the project and this looks something where I can start with. Can I work on this if possible?

**Comment by luxas** [comment]
@madhuri-rai07 That sounds great! Please do work on this, and feel free to ask help from @xiangpengzhao or me if you need anything to make this happen :smile:.
The references to prior discussions are all there, so just dig in :wink:

**Comment by madhuri-rai07** [comment]
@luxas Thank you so much :)

**Comment by xiangpengzhao** [comment]
@madhuri-rai07 awesome! :+1: 
As are referenced, https://github.com/kubernetes/kubernetes/pull/49051 (kubelet) and https://github.com/kubernetes/kubernetes/pull/53645 (kube-proxy) have been merged. They can be examples.

**Comment by timothysc** [comment]
Please follow the examples from the scheduler, proxy, and kubelet as guides.

**Comment by guangxuli** [comment]
@madhuri-rai07 if you work on this, have you any idea about where the `LeaderElectionConfiguration `struct should be placed. because `LeaderElectionConfiguration `is used both by controller and scheduler.
when i leave `LeaderElectionConfiguration ` in `conponentconfig` and refer in scheduler, the bazel test will not be passed successfully in PR #53577.

@luxas @timothysc any idea?

**Comment by luxas** [comment]
cc @ncdc similar problem as https://github.com/kubernetes/kubernetes/issues/54318

**Comment by xiangpengzhao** [comment]
cc @kris-nova

**Comment by guangxuli** [comment]
@madhuri-rai07 are you woking on this, if not, i am happy to send a PR to move controller configuration out of componentconfig package.

**Comment by jberkus** [comment]
Does #58565 complete this issue?  If so, can you add approved-for-milestone?  If not, is it expected to finish for 1.10?

@guangxuli @madhuri-rai07

**Comment by jberkus** [comment]
Reminder: code freeze begins in 7 hours. If you plan to complete this item for 1.10, please add status/approved-for-milestone to it and have a plan for how it's going to merge in the next few days.  Thanks!
@luxas @guangxuli @madhuri-rai07

**Comment by madhuri-rai07** [comment]
@guangxuli @jberkus I am not working on this due to other priorities. Thanks!

**Comment by sttts** [comment]
This is a kube-controller-manager only type for configuration. It belongs into cmd/kube-controller-manager/apis or something like that. Let's not move anything into pkg/.

**Comment by timothysc** [comment]
This is unlikely to be completed within this milestone, punting to 1.11

**Comment by nikhita** [comment]
/remove-lifecycle stale

should this be added to the 1.12 milestone?

**Comment by luxas** [comment]
@nikhita yes I hope we can prioritize this in v1.12 and go with something like `k8s.io/componentconfig` for this
cc @sttts @liggitt @mtaufen @thockin

**Comment by luxas** [comment]
KEP in progress in gdocs for this, will be converted to md soon: https://docs.google.com/document/d/1-u2y03ufX7FzBDWv9dVI_HyiIQZL8iz3o3vabeOpP5Y/edit#heading=h.iaigv0q3o3ur

**Comment by dims** [comment]
Looks like this dropped off the v1.12 plans. Please re-add milestone if needed for v1.12

/milestone clear

**Comment by luxas** [comment]
@dims how come? We're actively working on this for v1.12

**Comment by dims** [comment]
@luxas i did not see any update since Jul 2nd... hence the confusion that this was one of the PR(s) that keeps getting moved from milestone to another.

**Comment by luxas** [comment]
ah ok, the KEP is active and the tracking issue is https://github.com/kubernetes/kubernetes/issues/67233.

**Comment by luxas** [comment]
This has now been fixed with https://github.com/kubernetes/kubernetes/pull/67469 :tada:
