### ISSUE TITLE
Graduate the Lease Endpoint Reconciler to beta in v1.11

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#57617]
ref: https://github.com/kubernetes/kubernetes/pull/51698 and https://github.com/kubernetes/community/pull/939

An e2e test should be added, and the default should be updated.

/assign @rphillips 

cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-api-machinery-pr-reviews

**Comment by rphillips** [comment]
Thanks @luxas. I can take this on.

**Comment by rphillips** [comment]
Could someone point me to where the manifests are for the e2e test suites, I am happy to submit the patches?

**Comment by rphillips** [comment]
@luxas Are there API server e2e tests currently?

**Comment by liggitt** [comment]
there are not HA API server tests that I'm aware of

**Comment by rphillips** [comment]
I opened a PR for the default changes. Are there suggestions on a good E2E test to write if we don't have HA API server tests?

**Comment by jberkus** [comment]
@rphillips @liggitt what is needed for this issue to complete?  Do you think you'll get that by Monday, which is Code Freeze?

**Comment by rphillips** [comment]
We need some E2E testing or add an integration test as defined [here](https://github.com/kubernetes/kubernetes/pull/58474#issuecomment-366801923). It will not be done today.

**Comment by jberkus** [comment]
@rphillips so are you planning to move it to 1.11, then?  It's about to be automatically kicked out of 1.10 by automation.

**Comment by rphillips** [comment]
@jberkus I do not have permission to change the milestone. If you could kindly change it, that would be awesome!

**Comment by cblecker** [comment]
Reopening as this was reverted in https://github.com/kubernetes/kubernetes/pull/63380
