### ISSUE TITLE
Network Policy can not work with service

### ISSUE THREAD

**Issue by jzwlqx** [kubernetes/kubernetes#57629]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network

**What happened**:

As the example described in [network policy](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy) , when calico/cilium/weave-net is used, the policy in 'Limit access to the nginx service' phase limits that only those pods with label 'access=true' can access the nginx service. However, it not true. 

In my kubernetes cluster with calico, it turns out that the pods with label 'access=true' can access pod under nginx deploy but not nginx service. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce this, just let nginx pods and pods with 'access=true' run at different nodes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.9.0
- Cloud provider or hardware configuration:
vagrant
- OS (e.g. from /etc/os-release):
centos 7
- Kernel (e.g. `uname -a`):
Linux 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by thockin** [comment]
Sorry - we have tests and many users who are using this - you'll have to provide more details and a simple reproduction case for us to make any progress on this.

**Comment by thockin** [comment]
Can we take help-requests to the kubernetes-users mailing list?  I doubt this is a bug, and if it is, we can reopen.
