### ISSUE TITLE
local-up-cluster startup failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#57628]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I pull the latest code, and run with below cmd. But the cluster is not up. 
```
root@SZX1000353068:/mnt/go/src/k8s.io/kubernetes# ./hack/local-up-cluster.sh
```

And I notice the kube-apiserver.log, 
```
unknown flag: --authorization-mode
Usage of /mnt/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/hyperkube:
...
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  GitCommit:"980a5e80b12b35cb724aa276b8b589b5e96dd80f"
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@hzxuzhonghu : can you please check if you can see the authorization-mode parameter when you run things by hand?

```
[dims@bigbox 21:09] ~/go/src/k8s.io/kubernetes ⟩ ./_output/local/bin/linux/amd64/hyperkube apiserver --help 2>&1 | grep authorization-mode
      --authorization-mode string                               Ordered list of plug-ins to do authorization on secure port. Comma-delimited list of: AlwaysAllow,AlwaysDeny,ABAC,Webhook,RBAC,Node. (default "AlwaysAllow")
      --authorization-policy-file string                        File with authorization policy in csv format, used with --authorization-mode=ABAC, on the secure port.
      --authorization-webhook-config-file string                File with webhook configuration in kubeconfig format, used with --authorization-mode=Webhook. The API server will query the remote service to determine access on the API server's secure port.
```

**Comment by dims** [comment]
@hzxuzhonghu Can you please try the fix above?

**Comment by hzxuzhonghu** [comment]
@dims your pr does not fix it yet?  If not, I can help.

**Comment by hzxuzhonghu** [comment]
ok, thanks

**Comment by hzxuzhonghu** [comment]
only remove ` utilflag.InitFlags()`

**Comment by hzxuzhonghu** [comment]
reopen #57650, make less modifications.

**Comment by zjj2wry** [comment]
sorry, i miss hyper...
