### ISSUE TITLE
Add a --retry option to kubectl

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#5762]
In the experiments reported in issue #5761 I tried to clean up pods using:

```
$ kubectl delete pods -l name=serve-hostname --namespace=serve-hostnames-3537
```

but this kept failing and I ended up having to re-issue this command until I reached a fixed point. We should add a `--retry` flag that keeps re-trying the command until it has worked:

```
kubectl delete --retry pods -l name=serve-hostname --namespace=serve-hostnames-3537
```

While we continue to suffer from scalability errors I think it is important to have such a feature. @jlowdermilk @mbforbes

**Comment by smarterclayton** [comment]
What error was the kubelet returning?  Was this an explicit busy, or a timeout triggered by the server?  We *should* already be retrying API operations from pkg/client when they return a status code of 429 - https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L567.  We *should* also be doing that for other HTTP class timeout errors (controllable via the caller).

**Comment by satnam6502** [comment]
```
W0322 23:42:59.839243   18137 serve_hostnames.go:143] Failed to create pod serve-hostname-0-0: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

**Comment by thockin** [comment]
That reminds me - we need to vendor in the newest etcd client lib which has
somewhat better errors.

**Comment by bgrant0607** [comment]
--retry shouldn't be necessary. The client library should retry retry-able failures automatically.

**Comment by xied75** [comment]
:+1: 

Is this related to https://github.com/kubernetes/kubernetes/issues/14280 ?

I'm using kube-aws to spin up clusters on aws, I'm also using aws route53 A record for my kube api node, now it seems that after you create a new A record in route53, it takes some time for this to stabilize, this is kind of show stopper as I need to fire lots of kubectl cmd once the cluster is up, some of the kubectl cmd will fail to resolve DNS name thus error, given there is no --retry, it basically forces me to bash script around each every single kubectl cmd, which is very messy.

It should either be a new option of --retry, or fix it at client lib side.

I wonder why so less people complain about this, are we all firing kubectl by hand?

**Comment by chancez** [comment]
> --retry shouldn't be necessary. The client library should retry retry-able failures automatically.

I don't know if that's always the case, especially in modern kubernetes. There are plenty of potentially transient failures that clients don't retry. For example, if an operation fails because the API server can't reach a webhook (validating/mutating/etc) then the client will get a failure, but it's not going to retry. There's so many cases that don't get retried because a lot of stuff shouldn't be retried automatically.

I still think a `--retry` option could be useful, as it lets the user decide what should be retried in cases where the client can't know if it should.
