### ISSUE TITLE
Kubelet won't start on CentOS bare-metal (ca.crt and bootstrap-kubelet.conf issue)

### ISSUE THREAD

**Issue by jaroslavdextems** [kubernetes/kubernetes#57631]
Kubelet wont start 
error at step "RUNNING HANDLER [kubernetes/master : Master | wait for the apiserver to be running]"

 /kind bug

**What happened**:
kubelet: error: failed to run Kubelet: 

file /etc/kubernetes/bootstrap-kubelet.conf   --doesn't exist
file /etc/kubernetes/pki/ca.crt ----doesn't exist

tail /var/log/messages
k8s-master1 kubelet: error: failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory

k8s-node-1 kubelet: error: failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory

**What you expected to happen**:
I expect cluster to be built

**How to reproduce it (as minimally and precisely as possible)**:
I've tried to setup cluster of two nodes (1 master+etcd & 1 worker node)

invertory-production.cfg
k8s-master-1 ansible_ssh_host=XX.XX.XX.XX
k8s-node-1 ansible_ssh_host=XX.XX.XX.XX

[kube-master]
k8s-master-1

[etcd]
k8s-master-1

[kube-node]
k8s-node-1

[k8s-cluster:children]
kube-node
kube-master

sudo ansible-playbook -u root -b -e docker_dns_servers_strict=no -e http_proxy=http://proxy:port -i /home/user/kubespray/inventory/inventory-production.cfg /home/user/kubespray/cluster.yml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- Cloud provider or hardware configuration:
Bare-metal
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@jaroslavdextems can you please add more information to the ticket like what you are using to install Kubernetes.

**Comment by dims** [comment]
@jaroslavdextems looks like you are using kubespray, can you please log an issue with them? https://github.com/kubernetes-incubator/kubespray/issues they can escalate it to this main kubernetes/kubernetes repository if it is appropriate.

/close
