### ISSUE TITLE
AttachDisk--cinder volume error event Invalid request due to incorrect syntax or missing required parameters

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#57639]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
pod use cinder volume,but the event is 
![image](https://user-images.githubusercontent.com/25783555/34368732-1f3bacb0-eaf1-11e7-80c7-5f7610bbac24.png)
![image](https://user-images.githubusercontent.com/25783555/34368771-76a56ed2-eaf1-11e7-8955-6f773d83d918.png)
the pod is running but record the event!thanks
**What you expected to happen**:
no the error event
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):k8s 1.6.9
- Cloud provider or hardware configuration:openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
/assign @dims 
can you help me with the problem?thanks!

**Comment by wenlxie** [comment]
Can you use `nova volume-attach <node uuid> <volume>` command to  check whether the volume really can be attached to that volume?

**Comment by NickrenREN** [comment]
Since the pod is running, the cinder volume is finally attached and mounted successfully, right ? @jianglingxia

**Comment by jianglingxia** [comment]
yes,has attached the node that the pod scheduled!
![image](https://user-images.githubusercontent.com/25783555/34369738-7d68f4de-eaf9-11e7-9c45-266911262914.png)
![image](https://user-images.githubusercontent.com/25783555/34369748-99a58ac2-eaf9-11e7-90c0-7519634a5920.png)
![image](https://user-images.githubusercontent.com/25783555/34369781-d97182b4-eaf9-11e7-99e4-5b448c77a4ae.png)

**Comment by NickrenREN** [comment]
So the failure events are the intermediate events and finally we attach and mount the volume successfully. Just need to add successful events

**Comment by jianglingxia** [comment]
but What caused this error log？
the code in openstack_volume.go and the func is AttachDisk
![image](https://user-images.githubusercontent.com/25783555/34369948-2d7c0b08-eafb-11e7-9a5c-5e022baeb6bb.png)
the err not equal nil so the error log print and record!
the kube-controller-manager log is:
![image](https://user-images.githubusercontent.com/25783555/34369939-1ed2288a-eafb-11e7-9c8d-4173ecdc1d11.png)
and the full log 
[log.txt](https://github.com/kubernetes/kubernetes/files/1588277/log.txt)

**Comment by NickrenREN** [comment]
According to your logs, the err happened when kubernetes tried to call `attach` operation.
And the `Invalid request due to incorrect syntax or missing required parameters.` was logged by `gophercloud`

```
I1226 15:50:04.667608   11785 reconciler.go:208] Started AttachVolume for volume "kubernetes.io/cinder/706d8c36-12e0-493e-a25c-aa59ded5eba8" to node "default-np-55"
E1226 15:50:11.599262   11785 openstack_volumes.go:66] Failed to attach 706d8c36-12e0-493e-a25c-aa59ded5eba8 volume to 8f06c529-62d7-46ad-bb40-f5865ff09648 compute: Invalid request due to incorrect syntax or missing required parameters.
I1226 15:50:11.599321   11785 attacher.go:92] Attach volume "706d8c36-12e0-493e-a25c-aa59ded5eba8" to instance "8f06c529-62d7-46ad-bb40-f5865ff09648" failed with Invalid request due to incorrect syntax or missing required parameters.
E1226 15:50:11.599397   11785 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/cinder/706d8c36-12e0-493e-a25c-aa59ded5eba8\"" failed. No retries permitted until 2017-12-26 15:50:12.599367669 +0800 CST (durationBeforeRetry 1s). Error: Failed to attach volume "pvj" on node "default-np-55" with: Invalid request due to incorrect syntax or missing required parameters.
I1226 15:50:11.599745   11785 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"test", Name:"mysql-0", UID:"611788bb-ea11-11e7-988b-fa163eddae5f", APIVersion:"v1", ResourceVersion:"1677", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Failed to attach volume "pvj" on node "default-np-55" with: Invalid request due to incorrect syntax or missing required parameters.
```

**Comment by jianglingxia** [comment]
so is a bug ?and How to solve it?thanks

**Comment by wenlxie** [comment]
Can you do some check that:
1) nova show <node uuid>|grep -i attach, can you see the volume id?
2) cinder show <volume id>|grep -i attach, can you see the node uuid?

**Comment by wenlxie** [comment]
This is the first time when you do the attach, and then it encounter this error,
Attach controller try to do another attach after that, then it success. 
I think you can check  the nova-compute log to see  why the first attach was error.

**Comment by NickrenREN** [comment]
I do not think it is a bug, at least not a kubernetes bug. @jianglingxia 
the error is returned by gophercloud and likely to be related to nova-compute.
kubernetes just calls the interface and records the error

**Comment by jianglingxia** [comment]
yeah,agree with you @NickrenREN ,the err return by the func of
 _, err = volumeattach.Create(cClient, instanceID, &volumeattach.CreateOpts{
		VolumeID: volume.ID,
	}).Extract()
and k8s call the interface in vendor,if not kubernetes bug,so solve the problem must need solve the gophercloud code first?
![image](https://user-images.githubusercontent.com/25783555/34372429-9239934e-eb0f-11e7-9c0c-bcf9df514674.png)
the cinder api.log is
![image](https://user-images.githubusercontent.com/25783555/34372624-0b2b8f22-eb11-11e7-9ed9-fa555d4d719f.png)
and the cinder-manage log
[cinder-manage.log](https://github.com/kubernetes/kubernetes/files/1588452/cinder-manage.log)
the volume log
![image](https://user-images.githubusercontent.com/25783555/34372802-1fed334c-eb12-11e7-8e42-7827b9e1e592.png)
thanks! @wenlxie

**Comment by wenlxie** [comment]
I am also think this is not a bug.
The error  `Invalid request due to incorrect syntax or missing required parameters.` means the attach request response code is 400. 
You can check the nova-compute log  to check why nova response 400.
It doesn't mean the request message really has something wrong.

**Comment by jianglingxia** [comment]
sorry,So long to active the issue,I've been working on this problem but in nova compute /var/log/cinder/api.log have not found 400 code but 404, Is it not in this log of api.log?can help me with it?thanks for all!
![image](https://user-images.githubusercontent.com/25783555/34594232-c82b939c-f20a-11e7-8fea-af60e984b5a2.png)

**Comment by jianglingxia** [comment]
in /var/log/nova/nova-api.log there has 400
![image](https://user-images.githubusercontent.com/25783555/34713226-918eee16-f560-11e7-85cf-61d2cce1b9aa.png)
![image](https://user-images.githubusercontent.com/25783555/34713263-a20d343c-f560-11e7-8e18-8b2df83e01a2.png)
and I manually attach a volume to server with using the command
nova --debug volume-attach 08c445ea-cf3f-4fbb-8198-21b033fef273(serverID) 706d8c36-12e0-493e-a25c-aa59ded5eba8(volumeID)
![image](https://user-images.githubusercontent.com/25783555/34713363-fe2ff89e-f560-11e7-90a1-9064c150ca3d.png)
return HTTP 200,not 400
 I guess maybe the gophercloud code of http request body had some problem,maybe the device para. @NickrenREN @wenlxie  thanks!

**Comment by wenlxie** [comment]
Can you try the same server id and volume id with the nova log to do manually attach? 
@jianglingxia

**Comment by jianglingxia** [comment]
![image](https://user-images.githubusercontent.com/25783555/34754163-104c57ac-f5f7-11e7-8079-95d6a4e61510.png)
![image](https://user-images.githubusercontent.com/25783555/34754173-210fc51a-f5f7-11e7-8f26-5829d2e23393.png)
@wenlxie thanks

**Comment by wenlxie** [comment]
@jianglingxia sorry for misleading.
In your scenario, the first volume attach request returned 400, but then attach/detach controller try to do attach again, then the request  returned 200, so the volume is definitely can be attached. These two requests should be the same request. so that's why we don't think this is an issue related with request body issue.
I suppose what you are concern is why nova returned 400 the first time. In Nova you can see the details.

**Comment by jianglingxia** [comment]
the first requet and response
![image](https://user-images.githubusercontent.com/25783555/34975875-d67ace6e-face-11e7-8d1a-ab300ff7c54e.png)
![image](https://user-images.githubusercontent.com/25783555/34975958-30c607da-facf-11e7-932c-5a4292c5e117.png)
the second request and response
![image](https://user-images.githubusercontent.com/25783555/34976010-7a8d31cc-facf-11e7-92c1-2034de7ac381.png)
![image](https://user-images.githubusercontent.com/25783555/34976031-9732e128-facf-11e7-8f74-b94a8b0e411c.png)
because of the first request attach volume and attached to the computer,return 200 and the volume status is in-use so then send the second request result the 400 error! 
so question that the second request is k8s attach/detach controller  send ? if yes,maybe check the volume status then send request,if the volume is in-use we cannot send the second request,what about you? @wenlxie @NickrenREN @FengyunPan  thanks

**Comment by jianglingxia** [comment]
there has two problem that two log:
1)FailedMount     Failed to attach volume "pvj" on node "k8s-master-jlx" with: volume 867a1d87-b39f-44ba-888e-4a60b933219f is not attached to 2d93f5b6-4350-4f1e-9a30-f22cee84f7bc
2)FailedMount     Failed to attach volume "pvj" on node "k8s-master-jlx" with: Invalid request due to incorrect syntax or missing required parameters.
the first one is that the GetAttachmentDiskPath func return fmt.Errorf("volume %s is not attached to %s", diskName, instanceID) lead the 1)log
the second one is that send two request attach message
/cc @jsafrane @jingxu97  thanks!

**Comment by jingxu97** [comment]
@jianglingxia I am not very sure what is your problem from your last comment. Could you pls explain more?

**Comment by jianglingxia** [comment]
thanks for your review this issue, @jingxu97 
create a pod with cinder volume,finally we attach and mount the volume successfully,but in the intermediate there has two failure event,as follows：
![image](https://user-images.githubusercontent.com/25783555/35075973-fafc1cee-fc30-11e7-95fe-225f908a7425.png)
the controller manager log details:
[controller-manager.txt](https://github.com/kubernetes/kubernetes/files/1641287/controller-manager.txt)
I guess the error:Invalid request due to incorrect syntax or missing required parameters. is send two attach request,the first request return 200 and successfully mounted,but send second request,the volume status is in-use,so return 400 code lead the error log.
we can see that k8s log has two request:
I0118 09:13:15.458848   27352 requests.go:47] jlx cinder create r.Err <nil>
I0118 09:13:22.733164   27352 requests.go:47] jlx cinder create r.Err Invalid request due to incorrect syntax or missing required parameters.

the nova log is:

2018-01-18 09:19:38.754 9159 INFO nova.api.openstack.compute.contrib.volumes [req-6fe1ab79-f289-4c06-aedb-e06f27898767 f21d92877f2b4005be3e532f27ab04b0 d0b676089a19434ab07b06c834c1ddc3 - - -] Attach volume 867a1d87-b39f-44ba-888e-4a60b933219f to instance 2d93f5b6-4350-4f1e-9a30-f22cee84f7bc at None

2018-01-18 09:19:39.790 9159 INFO nova.osapi_compute.wsgi.server [req-6fe1ab79-f289-4c06-aedb-e06f27898767 f21d92877f2b4005be3e532f27ab04b0 d0b676089a19434ab07b06c834c1ddc3 - - -] 10.62.101.116 "POST /v2/d0b676089a19434ab07b06c834c1ddc3/servers/2d93f5b6-4350-4f1e-9a30-f22cee84f7bc/os-volume_attachments HTTP/1.1" status: 200 len: 386 time: 1.0473170

2018-01-18 09:19:40.917 9145 INFO nova.api.openstack.compute.contrib.volumes [req-2e04ff1e-c30c-44d9-8c23-573383be0e16 f21d92877f2b4005be3e532f27ab04b0 d0b676089a19434ab07b06c834c1ddc3 - - -] Attach volume 867a1d87-b39f-44ba-888e-4a60b933219f to instance 2d93f5b6-4350-4f1e-9a30-f22cee84f7bc at None

2018-01-18 09:19:47.065 9145 INFO nova.osapi_compute.wsgi.server [req-2e04ff1e-c30c-44d9-8c23-573383be0e16 f21d92877f2b4005be3e532f27ab04b0 d0b676089a19434ab07b06c834c1ddc3 - - -] 10.62.101.116 "POST /v2/d0b676089a19434ab07b06c834c1ddc3/servers/2d93f5b6-4350-4f1e-9a30-f22cee84f7bc/os-volume_attachments HTTP/1.1" status: 400 len: 290 time: 6.1587050


but the first error log:volume 867a1d87-b39f-44ba-888e-4a60b933219f is not attached to 2d93f5b6-4350-4f1e-9a30-f22cee84f7bc,
I cannot understand why execute the last return lead the err!
![image](https://user-images.githubusercontent.com/25783555/35076948-c1ef6b86-fc35-11e7-8471-c6934e070cf5.png)

thanks for your reply! @NickrenREN @jingxu97

**Comment by FengyunPan** [comment]
The k8s 1.6.9 is too old.
Have you tested it on k8s 1.8+?
OTOH, "two failure even" had been fixed long time, please check: #44536

**Comment by jianglingxia** [comment]
sorry,maybe I can't find the issue,but thanks very much,the pr merge in v 1.7+,Iwill test it in k8s 1.8+!

**Comment by jingxu97** [comment]
@jianglingxia does these error message always happen when starting a pod or occupationally? I think there might be some race condition which cause reconcile try to send attach operation twice.

**Comment by jianglingxia** [comment]
always and every time,I I will build a 1.8 environment and test it then report the result,thanks!

**Comment by jianglingxia** [comment]
in the same vm and k8sv1.8.5 test result follow,the problem solved and I will close the issue，thanks all！
[root@controller:/home/ubuntu]$ kubectl get po -o wide -w
NAME      READY     STATUS    RESTARTS   AGE       IP        NODE
web       0/1       Pending   0          0s        <none>    <none>
web       0/1       Pending   0         0s        <none>    k8s1.8-master
web       0/1       ContainerCreating   0         0s        <none>    k8s1.8-master
web       1/1       Running   0         18s       172.17.0.2   k8s1.8-master

Events:
  Type    Reason                 Age   From                    Message
  ----    ------                 ----  ----                    -------
  Normal  Scheduled              3m    default-scheduler       Successfully assigned web to k8s1.8-master
  Normal  SuccessfulMountVolume  3m    kubelet, k8s1.8-master  MountVolume.SetUp succeeded for volume "default-token-sf4f7"
  Normal  SuccessfulMountVolume  2m    kubelet, k8s1.8-master  MountVolume.SetUp succeeded for volume "pvj"
  Normal  Pulled                 2m    kubelet, k8s1.8-master  Container image "gcr.io/google_containers/nginx:1.7.9" already present on machine
  Normal  Created                2m    kubelet, k8s1.8-master  Created container
  Normal  Started                2m    kubelet, k8s1.8-master  Started container
