### ISSUE TITLE
1.9的kube-apiserver启动报错

### ISSUE THREAD

**Issue by 502155589** [kubernetes/kubernetes#57649]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by 502155589** [comment]
Dec 27 16:32:59 localhost systemd: Failed to start Kubernetes API Server.
Dec 27 16:32:59 localhost systemd: Unit kube-apiserver.service entered failed state.
Dec 27 16:32:59 localhost systemd: kube-apiserver.service failed.
Dec 27 16:33:01 localhost systemd: Started Session 627 of user root.
Dec 27 16:33:01 localhost systemd: Starting Session 627 of user root.
Dec 27 16:33:04 localhost systemd: kube-apiserver.service holdoff time over, scheduling restart.
Dec 27 16:33:04 localhost systemd: Starting Kubernetes API Server...
Dec 27 16:33:04 localhost kube-apiserver: I1227 16:33:04.699257   45976 server.go:121] Version: v1.9.0
Dec 27 16:33:04 localhost kube-apiserver: I1227 16:33:04.699511   45976 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
Dec 27 16:33:04 localhost kube-apiserver: W1227 16:33:04.701752   45976 authentication.go:378] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
Dec 27 16:33:04 localhost kube-apiserver: --etcd-servers must be specified
Dec 27 16:33:04 localhost systemd: kube-apiserver.service: main process exited, code=exited, status=1/FAILURE
Dec 27 16:33:04 localhost systemd: Failed to start Kubernetes API Server.
Dec 27 16:33:04 localhost systemd: Unit kube-apiserver.service entered failed state.
Dec 27 16:33:04 localhost systemd: kube-apiserver.service failed.
Dec 27 16:33:09 localhost systemd: kube-apiserver.service holdoff time over, scheduling restart.
Dec 27 16:33:09 localhost systemd: Starting Kubernetes API Server...
Dec 27 16:33:10 localhost kube-apiserver: I1227 16:33:10.148730   45991 server.go:121] Version: v1.9.0
Dec 27 16:33:10 localhost kube-apiserver: I1227 16:33:10.148886   45991 services.go:35] Network range for service cluster IPs is unspecified. Defaulting to 10.0.0.0/24.
Dec 27 16:33:10 localhost kube-apiserver: W1227 16:33:10.148976   45991 authentication.go:378] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
Dec 27 16:33:10 localhost kube-apiserver: --etcd-servers must be specified
Dec 27 16:33:10 localhost systemd: kube-apiserver.service: main process exited, code=exited, status=1/FAILURE
Dec 27 16:33:10 localhost systemd: Failed to start Kubernetes API Server.
Dec 27 16:33:10 localhost systemd: Unit kube-apiserver.service entered failed state.
Dec 27 16:33:10 localhost systemd: kube-apiserver.service failed.

**Comment by wenlxie** [comment]
```
Dec 27 16:33:10 localhost kube-apiserver: W1227 16:33:10.148976 45991 authentication.go:378] AnonymousAuth is not allowed with the AllowAll authorizer. Resetting AnonymousAuth to false. You should use a different authorizer
Dec 27 16:33:10 localhost kube-apiserver: --etcd-servers must be specified
```

**Comment by huzhengchuan** [comment]
more detail https://kubernetes.io/docs/setup/ to deploy kubernetes.

**Comment by hzxuzhonghu** [comment]
@502155589 It is not a bug, could you clise it.
