### ISSUE TITLE
PVC does not allow "highly available" pods in cluster

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#57643]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG
/kind bug

**What happened**: persistentvolumeclaims are not moved to another node in two cases:

1) if pod (with pvc) is running in node which is deleted from the cluster

```
{"log":"I1226 23:21:55.189745       1 openstack_volumes.go:332] volume 0c12971f-da26-44a7-9333-1dba7e3f7be6 is already attached to node kube-dev-node-1-1 path /dev/vdb\n","stream":"stderr","time":"2017-12-26T23:21:55.189918768Z"}
{"log":"I1226 23:21:55.189860       1 attacher.go:159] Attach volume \"0c12971f-da26-44a7-9333-1dba7e3f7be6\" to instance \"1af64c3e-264d-4ec1-ae7b-6199fb9bb475\" failed with: disk 0c12971f-da26-44a7-9333-1dba7e3f7be6 path /dev/vdb is attached to a different instance (12db4669-6145-449e-99b7-453031b71bb0)\n","stream":"stderr","time":"2017-12-26T23:21:55.189943108Z"}
{"log":"I1226 23:21:55.190080       1 actual_state_of_world.go:464] Report volume \"kubernetes.io/cinder/0c12971f-da26-44a7-9333-1dba7e3f7be6\" as attached to node \"kube-dev-node-1-1\"\n","stream":"stderr","time":"2017-12-26T23:21:55.190220094Z"}
{"log":"I1226 23:21:55.191217       1 event.go:218] Event(v1.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"nginx-deployment-5fc77998d-gfws9\", UID:\"25d323df-ea92-11e7-bfcf-fa163ee4a110\", APIVersion:\"v1\", ResourceVersion:\"1198\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedMount' AttachVolume.Attach failed for volume \"pvc-e46022b2-ea91-11e7-bfcf-fa163ee4a110\" : disk 0c12971f-da26-44a7-9333-1dba7e3f7be6 path /dev/vdb is attached to a different instance (12db4669-6145-449e-99b7-453031b71bb0)\n","stream":"stderr","time":"2017-12-26T23:21:55.191381995Z"}
{"log":"E1226 23:21:55.191456       1 nestedpendingoperations.go:263] Operation for \"\\\"kubernetes.io/cinder/0c12971f-da26-44a7-9333-1dba7e3f7be6\\\"\" failed. No retries permitted until 2017-12-26 23:23:57.190305974 +0000 UTC m=+1057.372010350 (durationBeforeRetry 2m2s). Error: \"AttachVolume.Attach failed for volume \\\"pvc-e46022b2-ea91-11e7-bfcf-fa163ee4a110\\\" (UniqueName: \\\"kubernetes.io/cinder/0c12971f-da26-44a7-9333-1dba7e3f7be6\\\") from node \\\"kube-dev-node-1-0\\\" : disk 0c12971f-da26-44a7-9333-1dba7e3f7be6 path /dev/vdb is attached to a different instance (12db4669-6145-449e-99b7-453031b71bb0)\"\n","stream":"stderr","time":"2017-12-26T23:21:55.191599561Z"}
{"log":"I1226 23:21:55.212179       1 actual_state_of_world.go:384] Set detach request time to current time for volume kubernetes.io/cinder/0c12971f-da26-44a7-9333-1dba7e3f7be6 on node \"kube-dev-node-1-1\"\n","stream":"stderr","time":"2017-12-26T23:21:55.212487697Z"}
{"log":"I1226 23:21:55.212270       1 node_status_updater.go:71] Could not update node status. Failed to find node \"kube-dev-node-1-1\" in NodeInformer cache. Error: 'node \"kube-dev-node-1-1\" not found'\n","stream":"stderr","time":"2017-12-26T23:21:55.212525699Z"}
```

this means that we are raising NewVolumeDanglingError, which should be raised if the pvc is not attached to correct node. However, the problem is that node does not exist in cluster anymore where it was attached.

2) if pod is running in node which goes "notready" state, for instance something wrong with the machine.

```
Events:
  Type     Reason                 Age              From                        Message
  ----     ------                 ----             ----                        -------
  Normal   Scheduled              11m              default-scheduler           Successfully assigned nginx-deployment-5fc77998d-2nzl9 to kube-dev-node-1-1
  Warning  FailedAttachVolume     11m              attachdetach-controller     Multi-Attach error for volume "pvc-c350c73a-ea94-11e7-bfcf-fa163ee4a110" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulMountVolume  11m              kubelet, kube-dev-node-1-1  MountVolume.SetUp succeeded for volume "default-token-v2vhf"
  Warning  FailedMount            2m (x4 over 9m)  kubelet, kube-dev-node-1-1  Unable to mount volumes for pod "nginx-deployment-5fc77998d-2nzl9_default(0770d96e-ea95-11e7-bfcf-fa163ee4a110)": timeout expired waiting for volumes to attach/mount for pod "default"/"nginx-deployment-5fc77998d-2nzl9". list of unattached/unmounted volumes=[vol]
````

The problem in this case is that actualstateofworld contains status that notready node has volume attached https://github.com/zetaab/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L269-L279 At least in openstack this means that pod is not moved at all to new node. This is very problematic if we want to have highly available service in kubernetes cluster. If node breaks, we should have possibility toi failover pods automatically to new node.

**What you expected to happen**: I except that I should have highly available pod, but now it looks like pod with PVC cannot move to another node after current node crashes. The problem now is with disk detach in both cases. In case 1) https://github.com/zetaab/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L269 we could check here what is status of this node where the volume is attached. For instance if node status from cloudprovider is shutdowned - we can detach the disk without any problem or risk? Case 2) is difficult, because the pod can be still running there in "notready" node, and if we just detach volume it might lead to data corruption? However, IMO we must have some way to detect is the pod running there correctly and if not -> detach volume and live goes on. I am thinking healthchecks, could they detach volume in that case?

**How to reproduce it (as minimally and precisely as possible)**:

case 1)

1. make pod with pvc to some node
2. shutdown that node from cloudprovider gui/api (node should be removed from `kubectl get nodes`)
3. after sometime pod is moved to another node but volume is not detached?

case 2)
1. create pod with pvc to some node
2. disable that node docker+kubelet from autostart, and restart node (now the node is not going to be removed from the cluster, its there but notready state)
3. check does the pod failover to another node 

Some logs https://github.com/kubernetes/kubernetes/pull/56846

**Comment by wenlxie** [comment]
For issues 2. 
The node become `NotReady`, then the pod will become into `unknown` status after eviction.
pod's container state is `running` , pod's phase is `running`

attach_detach_controller has logical to deal with `terminating` pod's volumes. 
But it not suitable to deal with this scenario.
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/volumehelper/volumehelper.go#L102
I used to create an issue for how to deal with this situation: https://github.com/kubernetes/kubernetes/issues/51597

**Comment by zetaab** [comment]
original issue 1 is fixed for AWS in https://github.com/kubernetes/kubernetes/pull/55893 and fixed for openstack in https://github.com/kubernetes/kubernetes/pull/56846

still that issue 2 exist in both, should we close this issue and continue in https://github.com/kubernetes/kubernetes/issues/51597 what you think @wenlxie

**Comment by wenlxie** [comment]
@zetaab  I agree with @jingxu97 's comments at https://github.com/kubernetes/kubernetes/pull/56846 and we are going to do node auto remediation to handle this situation(e.g. reboot the node first, if it not work, then  delete the node from cloud provider and cluster.)

> @zetaab About when node in "unknown" state, our current suggestion is to have some outside controller to monitor it and delete the node from Kuberenetes API server. From kubernetes point of view, since node is "unknown", we can not be sure what is happening and make a decision to delete pod and detach volume, which might cause data corruption or data loss. If cluster admin/user monitors the node and decides to delete the node from kuberentes API server, that will solve the issue.

Now we changed function `IsPodTerminated` as following to detach the volume for `UNKNOWN` pod. We will remove this after node remediation works. 

```
func IsPodTerminated(pod *v1.Pod, podStatus v1.PodStatus) bool {
	return podStatus.Phase == v1.PodFailed || podStatus.Phase == v1.PodSucceeded || (pod.DeletionTimestamp != nil && notRunning(podStatus.ContainerStatuses) || deleteExpired(pod))
}
```
```
func deleteExpired(pod *v1.Pod) bool {
	if pod.DeletionTimestamp != nil {
		deleteTimeStamp := pod.DeletionTimestamp
		gracePeriod := int64(*pod.DeletionGracePeriodSeconds)

		if gracePeriod == int64(0) {
			gracePeriod = int64(2)
		}

		if time.Now().After(deleteTimeStamp.Add(time.Duration(gracePeriod) * time.Second)) {
			return true
		}
	}
	return false
}
```
We also have concerns like @jingxu97 before add such code, but we think this helps us because we have many nodes went down then pod become 'unknown' and we can tolerates the data corruption.


> still that issue 2 exist in both, should we close this issue and continue in #51597 what you think 
We can keep both, Your issue has more infos than mine, maybe  ##51597  should be closed. 
 
Thanks

**Comment by wenlxie** [comment]
@zetaab I found I had a similar PR to fix one condition which caused  issue 1 before. https://github.com/kubernetes/kubernetes/pull/53855
I just removed the `Status: "ACTIVE"` from the nova list options.

Thanks for you patch.

**Comment by ssfilatov** [comment]
Is this resolved? I see that issue 1 was merged, but it seems that when pod gets UNKNOWN status, the  volume is not detached(issue 2). 
I have 1.9.8 kube with openstack cloudprovider
