### ISSUE TITLE
 deployment support more type deployments

### ISSUE THREAD

**Issue by woshihaoren** [kubernetes/kubernetes#57641]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
Now only support Canary deployments
use Canary deployments need two yaml files. 
if has more project need Canary，will double yaml  file.

**What you expected to happen**:
more deployments
like one deployment  deploy pod that supports different versions of proportion.

**Comment by krmayankk** [comment]
i agree we should support canary deployments same way statefulset supports it now, and bring them both at feature parity. @kargakis @janetkuo is anyone working on this ?

**Comment by janetkuo** [comment]
Dup with #11505. Closing. Please check/join the discussions there.
