### ISSUE TITLE
kubctl explain resourcequota.spec.hard incomplete

### ISSUE THREAD

**Issue by dyson** [kubernetes/kubernetes#57653]
/kind bug

**What happened**:
Ran:
```
kubectl explain resourcequota.spec.hard
```

**What you expected to happen**:
To see list of available hard resource quota limits.
Instead there is only a link to a page that 404's.

**How to reproduce it (as minimally and precisely as possible)**:
Run:
```
kubectl explain resourcequota.spec.hard
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
:; kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05",GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4",GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME=Buildroot
VERSION=2017.02
ID=buildroot
VERSION_ID=2017.02
PRETTY_NAME="Buildroot 2017.02"
```

**Comment by huzhengchuan** [comment]
@kubernetes/sig-cli-bugs

Maybe it's better to fill the issue there: https://github.com/kubernetes/kubectl/issues

**Comment by dyson** [comment]
Wasn't sure where it belonged. Happy to open there and close here.

**Comment by dyson** [comment]
Moved to https://github.com/kubernetes/kubectl/issues/190
