### ISSUE TITLE
kubectl 1.9.0 fails during create resource

### ISSUE THREAD

**Issue by 007** [kubernetes/kubernetes#57666]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Tried to create a resource from YAML via stdin, got no-op error
```
Error from server (NotFound): the server could not find the requested resource
```

**What you expected to happen**:
Expected resource to be created

**How to reproduce it (as minimally and precisely as possible)**:
Use 1.9.0 kubectl against a 1.6.2 kube server. This command doesn't do anything, but shows the failure mode / difference between the two versions.
```
echo '---' | kubectl create -f -
```

**Anything else we need to know?**:
Works fine with kubectl 1.8.4 against same server - throws error and falls back appropriately
```
Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
```

Error message for 1.9.0 is
```
GET https://api.$my.$k8s.$server/swagger-2.0.0.pb-v1 404 Not Found in 424 milliseconds
```
with a bunch of extra stuff, and
```
I1227 12:09:00.519012   95554 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "unknown"
      }
    ]
  },
  "code": 404
}]
F1227 12:09:00.519048   95554 helpers.go:119] Error from server (NotFound): the server could not find the requested resource
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS via `kops`
- OS (e.g. from /etc/os-release):
OSX
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig cli
/area kubectl

**Comment by liggitt** [comment]
1.9 to 1.6 skew is not supported. kubectl currently supports 1 version forward and backward skew.

**Comment by laurentiu-miu** [comment]
So why is it closed?

**Comment by laurentiu-miu** [comment]
kubectl 1.10.0 fails during create resource ...
Is it possible to downgrade or something? 
Why is this bug closed?
