### ISSUE TITLE
kube-proxy can't create clusterIP ipvs rules when externalTrafficPolicy=Local

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#57678]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:

When setting `externalTrafficPolicy=Local` in ipvs proxy mode, kube-proxy can't create clusterIP ipvs rules.

**What you expected to happen**:

Create clusterIP rules, so that can access service from internal.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a service with backends in different node.
- Set service `externalTrafficPolicy` to `Local`.
- Access the service cluster IP from the node which don't have service backend.

**Comment by thockin** [comment]
@rramkumar1
