### ISSUE TITLE
DNS entries not exposed for StatefulSet and headless service in Kubernetes 1.8 or 1.9

### ISSUE THREAD

**Issue by heckj** [kubernetes/kubernetes#57671]
/kind bug

I believe this is a bug, but I'm uncertain of the specifics expected beyond the documentation. I was creating a statefulset and headless service, vetting the documentation at https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

**What happened**:

The sample deployments are available in public github:
https://github.com/kubernetes-for-developers/kfd-nodejs/blob/0.4.0/deploy/redis.yml (dependent service) and https://github.com/kubernetes-for-developers/kfd-nodejs/blob/0.4.0/deploy/nodejs.yml - example failing service.

When I create the stateful set, it operates as expected - creating replicas and coming online normally. When I attempted to validate the DNS entries within the cluster for the headless service is where I ran into issues. 

I used the command:

    kubectl run -i --tty --image busybox dns-test --restart=Never --rm /bin/sh

to create a temporary pod, in the same namespace. 

Per the documentation, I expected "nslookup nodejs-0.nodejs" to return a value, or at the very least "nslookup nodejs-0.nodejs.default.svc.cluster.local" to return a value. Instead I received the following:

    / # nslookup nodejs-0.nodejs
    Server:    10.96.0.10
    Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
    nslookup: can't resolve 'nodejs-0.nodejs'
    / # nslookup nodejs-0.nodejs.default.svc.cluster.local
    Server:    10.96.0.10
    Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
    nslookup: can't resolve 'nodejs-0.nodejs.default.svc.cluster.local'

I can run an nslookup within an individual pod, and it will see itself, but not it's neighbor:

    kubectl exec -it nodejs-1 -- /bin/sh

    /src # nslookup nodejs-1
    nslookup: can't resolve '(null)': Name does not resolve
    Name:      nodejs-1
    Address 1: 172.17.0.6 nodejs-1.nodejs.default.svc.cluster.local
    /src # nslookup nodejs-0.nodejs
    nslookup: can't resolve '(null)': Name does not resolve
    nslookup: can't resolve 'nodejs-0.nodejs': Name does not resolve

And when I look at the service endpoint, it shows the endpoints are listed:

    kubectl describe service nodejs-service

    Name:              nodejs-service
    Namespace:         default
    Labels:            <none>
    Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nodejs-service","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"n...
    Selector:          app=nodejs
    Type:              ClusterIP
    IP:                None
    Port:              web  3000/TCP
    TargetPort:        3000/TCP
    Endpoints:         172.17.0.4:3000,172.17.0.6:3000
    Session Affinity:  None
    Events:            <none>

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

   minikube start --kubernetes-version v1.9.0 --bootstrapper kubeadm
   git clone https://github.com/kubernetes-for-developers/kfd-nodejs -b 0.4.0
   kubectl apply -f deploy/
 
**Anything else we need to know?**:

I've reproduced this with the latest minikube and both a 1.8 cluster and a 1.9 cluster bootstrapped with kubeadm, both with identical results.

**Environment**:
- Kubernetes version (use `kubectl version`):

    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: minikube w/ kyperkit and minikube w/ virtualbox VM

    minikube version: v0.24.1

- OS (e.g. from /etc/os-release):

    NAME=Buildroot
    VERSION=2017.02
    ID=buildroot
    VERSION_ID=2017.02
    PRETTY_NAME="Buildroot 2017.02"

- Kernel (e.g. `uname -a`):

    Linux minikube 4.9.13 #1 SMP Thu Oct 19 17:14:00 UTC 2017 x86_64 GNU/Linux

**Comment by heckj** [comment]
@kubernetes/sig-apps-bugs

**Comment by heckj** [comment]
Should I have seen an error somewhere that indicated the mismatch?

**Comment by krmayankk** [comment]
@heckj the headless service is a different  k8s resource then the StatefulSet resource referring the headless service using it. Currently k8s doesnt verifying cross references across resources. So i believe this kind of validation is left to uber(read higher level) software. @kow3ns @smarterclayton any comments on this ?

**Comment by smarterclayton** [comment]
You are correct

**Comment by thedodd** [comment]
I am running into this issue on GKE @ `1.8.5-gke.0`. StatefulSet's `spec.serviceName` matches the service's `metadata.name`. No other issues. Simply can not resolve specific statefulset memeber's DNS name.

```
# This works:
root@rabbitmq-1:/# nslookup rabbitmq
Server:		10.120.240.10
Address:	10.120.240.10#53

Name:	rabbitmq.default.svc.cluster.local
Address: 10.120.248.234

# This does not:
root@rabbitmq-1:/# nslookup rabbitmq-0
Server:		10.120.240.10
Address:	10.120.240.10#53

** server can't find rabbitmq-0: NXDOMAIN
```

```bash
# Pods:
kubectl get pods
NAME                                     READY     STATUS    RESTARTS   AGE
rabbitmq-0                               1/1       Running   0          9m
rabbitmq-1                               1/1       Running   0          9m
```

**Comment by troyanov** [comment]
@thedodd can you provide your Headless Service definition? Have you tried adding `clusterIP: None` for Headless Service?

**Comment by thedodd** [comment]
@troyanov so, I was using `1.8.5-gke.0`, and after upgrading to `1.8.7-gke.1` the DNS started working as expected. 

And yes, to be sure, I already had the `clusterIP: None` set already.

**Comment by thedodd** [comment]
Issue resolved.

**Comment by thatsmybirthday** [comment]
@thedodd how?

**Comment by kuznero** [comment]
@thedodd how exactly? Can you please post you solution here?

**Comment by Freyert** [comment]
This is happening to me on the following versions:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I have a stateful set with just `1` replica.

The `serviceName` matches the service's name:

```yaml
  #statefulset 
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: mongo-hidden-secondary
        release: hidden-secondary
    serviceName: hidden-secondary-mongo-hidden-secondary
    template:
```

```
#Service
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: 2018-12-05T18:13:15Z
    labels:
      app: mongo-hidden-secondary
      chart: mongo-hidden-secondary-0.0.0
      heritage: Tiller
      release: hidden-secondary
    name: hidden-secondary-mongo-hidden-secondary
    namespace: hidden-secondary
    resourceVersion: "31270202"
    selfLink: /api/v1/namespaces/hidden-secondary/services/hidden-secondary-mongo-hidden-secondary
    uid: 6f89eaaf-f8b9-11e8-8e07-06946796fc80
  spec:
    clusterIP: None
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    publishNotReadyAddresses: true
    selector:
      app: mongo-hidden-secondary
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
```

**Comment by VJalili** [comment]
Same issue here (starting RabbitMQ with statefulset): 

```
DIAGNOSTICS
===========

attempted to contact: ['rabbit@rabbitmq-1','rabbit@rabbitmq-2',
                       'rabbit@rabbitmq-3','rabbit@rabbitmq-4']

rabbit@rabbitmq-1:
  * unable to connect to epmd (port 4369) on rabbitmq-1: nxdomain (non-existing domain)

rabbit@rabbitmq-2:
  * unable to connect to epmd (port 4369) on rabbitmq-2: nxdomain (non-existing domain)

rabbit@rabbitmq-3:
  * unable to connect to epmd (port 4369) on rabbitmq-3: nxdomain (non-existing domain)

rabbit@rabbitmq-4:
  * unable to connect to epmd (port 4369) on rabbitmq-4: nxdomain (non-existing domain)
```
