### ISSUE TITLE
Deprecate and disable the wiki

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#57689]
Like kubernetes/community#116 but for the wiki in kubernetes/kubernetes

I suspect much of the content in the wiki is harmfully out of date.  Most of the edits in the last year have involved reminding people just how out of date the wiki is.  I would like to:
- delete the obviously out of date stuff I am comfortable making a call on
- migrate out the content I can't make a call on to kubernetes/community/sig-foo/migrated-from-wiki
- disable the wiki

/priority important-soon
/sig contributor-experience
/kind cleanup
/assign
FYI @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by spiffxp** [comment]
Pages
- [ ] https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ
  - this should live in kuberentes/community if we don't already have CLA-related content there
- [ ] https://github.com/kubernetes/kubernetes/wiki/Debugging-FAQ
  - ??? is this content sufficiently available / answered on the website?
- [ ] https://github.com/kubernetes/kubernetes/wiki/Developer-FAQ
  - remove, it's literally just "TODO"
- [ ] https://github.com/kubernetes/kubernetes/wiki/Github-and-Build-Cop-Rotation
  - remove, it points to a dead link, and the build cop role has been retired
- [ ] https://github.com/kubernetes/kubernetes/wiki/Networking-Features-under-development
  - remove, this is just a set of issue links, all but https://github.com/kubernetes/kubernetes/issues/28366 and https://github.com/kubernetes/kubernetes/issues/28651 have been closed
- [ ] https://github.com/kubernetes/kubernetes/wiki/Release-1.3
 - remove, this is redirect to to kubernetes/features (which should be a redirect to kubernetes/sig-release)
- [ ] https://github.com/kubernetes/kubernetes/wiki/Release-1.4
 - remove, this is redirect to to kubernetes/features (which should be a redirect to kubernetes/sig-release)
- [ ] https://github.com/kubernetes/kubernetes/wiki/Services-FAQ
  - ??? is this content sufficiently available / answered on the website?
- [ ] https://github.com/kubernetes/kubernetes/wiki/Slack-Team-Information
  - remove, this is a redirect to kubernetes/community
- [ ] https://github.com/kubernetes/kubernetes/wiki/Special-Interest-Groups-(SIGs)
  - remove, this is a redirect to kubernetes/community
- [ ] https://github.com/kubernetes/kubernetes/wiki/User-FAQ
  - remove, this is marked as obsolete
- [ ] https://github.com/kubernetes/kubernetes/wiki/User-Support-Rotation
  - remove, this is a redirect to a dead link (I'm not sure the on-call-user-support role exists anymore?)
- [ ] https://github.com/kubernetes/kubernetes/wiki/Weekly-Community-Video-Conference
  - remove, this is a redirect to kubernetes/community
- [ ] https://github.com/kubernetes/kubernetes/wiki/Why-Kubernetes%3F
  - remove, this is a redirect to the website

**Comment by spiffxp** [comment]
Edited https://github.com/kubernetes/kubernetes/wiki to point back here

If there are no wild objections to this I will proceed as planned tomorrow

**Comment by idvoretskyi** [comment]
@spiffxp 

>  https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ

CLA-bot may be dependent on this link. cc @foxish

**Comment by cblecker** [comment]
Submitted https://github.com/kubernetes/community/pull/1552 to rewrite/organize CLA.md in k/community, and https://github.com/kubernetes/test-infra/pull/6115 to update the link from the CLA bot.

**Comment by spiffxp** [comment]
At this point I believe I have opened up PR's with all repos that have any links pointing here.  Once they're all merged I will delete the tombstones I've dropped in the wiki, and disable the wiki

**Comment by spiffxp** [comment]
All PR's have been merged (save for kubernetes-docs-cn, which is a sync, so I'm considering it merged)

**Comment by spiffxp** [comment]
/close
The wiki has been disabled
