### ISSUE TITLE
Enable FlexVolume to support volume resizing

### ISSUE THREAD

**Issue by xingzhou** [kubernetes/kubernetes#57685]
Related feature ticket at: https://github.com/kubernetes/features/issues/304

We already have prepared the draft code for the FlexVolume, will submit the PR for discussion once the testings are done

/sig-storage

/cc @gnufied & @chakri-nelluri

**Comment by saad-ali** [comment]
No issue needed in kubernetes/kubernetes, the feature repo issue is sufficient to track this.
