### ISSUE TITLE
cpumanager: using container resources f

### ISSUE THREAD

**Issue by hankya** [kubernetes/kubernetes#57681]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Using cpumanager/static policy, If kubelet restart, cpus assigned to container by cpumanager could differ from last time

**What you expected to happen**:
With cpumanager/static, cpus assigned to container should not change

**How to reproduce it (as minimally and precisely as possible)**:
1. Start kubelet with --feature-gates=CPUManager=true \ --cpu-manager-policy=static;
2. Create pod, check assigned cpus
3. Restart kubelet
4. Check assigned cpus for the same pod, it diff from step 2

**Anything else we need to know?**:
cpuset-cpus is in the container itself,  kubelet should be able to recover it during reconcile period 

**Environment**:
- Kubernetes version (use `1.8.1`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `4.4.0-33.bm.1-amd64`):
- Install tools: custom
- Others:

**Comment by flyingcougar** [comment]
cpu manager supports checkpointing now - please retest
