### ISSUE TITLE
IPVS proxier update service too slow, it waits until a sync period.

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#57698]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

IPVS proxier update service too slow, it waits until a sync period.

**What you expected to happen**:

Any k8s service update should trigger IPVS virtual service update.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a k8s service

2. update it's session affinity type

3. to see if ipvs virtual service has changed - NO!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig network

/area ipvs

**Comment by thockin** [comment]
@rramkumar1
