### ISSUE TITLE
kubernetes/pkg/api not compiling with go 1.8.3

### ISSUE THREAD

**Issue by asridharan** [kubernetes/kubernetes#57691]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 bug

**What happened**:
I am using a `vendored` k8s api package:
 k8s.io/kubernetes/pkg/api/pod

I am trying to build a k8s go client using the k8s/client-go package. However when I trying building with go 1.8.3 I get the following build errors:
```
bash-3.2$ go build main.go
# github.com/asridharan/edgelb-k8s/vendor/k8s.io/kubernetes/pkg/api
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:41: scheme.AddGeneratedDeepCopyFuncs undefined (type *runtime.Scheme has no field or method AddGeneratedDeepCopyFuncs)
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:42: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:46: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:50: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:54: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:58: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:62: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:66: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:70: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:74: undefined: conversion.GeneratedDeepCopyFunc
vendor/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:74: too many errors
```
**What you expected to happen**:
Build k8s go client.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout out the code from this repo
https://github.com/asridharan/edgelb-k8s

Install golang 1.8.3 and setup your $GOPATH appropriately.

Run `glide update --strip-vendor`
Do `go build main.go`

**Anything else we need to know?**:

**Environment**:
Mac OS X El Capitan (10.11.4)

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by asridharan** [comment]
Closing this out. Turns out I was setting the version dependency correctly. Had to use the correct version of the k8s go-client along with the correct version of the k8s.

**Comment by johnweldon** [comment]
@asridharan can you say which versions you used for both to resolve this?

**Comment by asridharan** [comment]
@johnweldon this is my `glide.yaml`:
```
import:
- package: k8s.io/client-go
  version: v5.0.0
- package: k8s.io/kubernetes
  version: v1.8.0
  subpackages:
  - pkg/api
```
The above dependency worked for me.

**Comment by yjimk** [comment]
For anyone else coming across this and using [dep](https://github.com/golang/dep) for dependency management. Adding these overrides to `Golang.toml` resolved the issue for me.

Might need to fiddle with the versions a little depending on your setup

```
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.7"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.7"

[[override]]
  name = "k8s.io/client-go"
  version = "7.0.0"
```

**Comment by chiefy** [comment]
adding on to @yjimk said, I had to use `1.8.x` of kubernetes + apimachinery to work w/ client-go `5.0.1`
