### ISSUE TITLE
Watcher error loop "Unable to decode an event from the watch stream" from bad CR manifests

### ISSUE THREAD

**Issue by jessesuen** [kubernetes/kubernetes#57705]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We are developing controller which uses an cache.SharedIndexInformer to watch events against our custom resource. However, when `kubectl create -f manifest.yaml` is run using a bad manifest, specifically one that fails to unmarshall into the CR datastructure due to mismatched field data types, the watcher will fall into an infinite loop and begin rapidly spewing out the following errors in a tight loop:

```
E1229 01:59:53.317248    3559 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.Foo: Spec: v1alpha1.FooSpec: DeploymentName: ReadString: expects " or n, but found [, error found in #10 byte of ...|entName":["example-f|..., bigger context ...|1e7-b3e3-4e0b1a127ace"},"spec":{"deploymentName":["example-foo"],"replicas":1}}|...
E1229 01:59:53.319798    3559 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.Foo: Spec: v1alpha1.FooSpec: DeploymentName: ReadString: expects " or n, but found [, error found in #10 byte of ...|entName":["example-f|..., bigger context ...|1e7-b3e3-4e0b1a127ace"},"spec":{"deploymentName":["example-foo"],"replicas":1}}|...
```

When the watch gets into this state, the controller ceases to function since its informer no longer sends any events from the watch. As soon as the malformed CR is deleted, theses errors stop and the informer starts sending events again.

**What you expected to happen**:

The watcher should not fall into an tight error loop preventing the watch from functioning. The malformed CR should be ignored.

**How to reproduce it (as minimally and precisely as possible)**:
This is reproducible using the sample-controller example: https://github.com/kubernetes/sample-controller:
```
$ go get k8s.io/sample-controller
$ go run *.go -kubeconfig=$HOME/.kube/config
```
`kubectl create -f` the following malformed manifest
```
apiVersion: samplecontroller.k8s.io/v1alpha1
kind: Foo
metadata:
  name: example-foo
spec:
  # deploymentName is supposed to be a string and not a list
  deploymentName: [example-foo]
  replicas: 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `minikube version: v0.24.1` on macOS
- OS (e.g. from /etc/os-release): macOS
- Kernel (e.g. `uname -a`):
`Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64`
- Install tools: minikube

**Comment by liggitt** [comment]
I'm not sure ignoring the invalid data is valid. Once you allow that to happen, the internal store is essentially in an indeterminate state

**Comment by jessesuen** [comment]
What other option is there? It is not possible to block a CR (which doesn't adhere to a specific data structure) from being created. So we have to live with the fact that there may be CRs with incongruent data types. Now, if an informer is established and specifies a particular runtime.Object, and the watch encounters an resource which cannot decode to that object, it seems the logical choice is to ignore it. Having the watch ignore resources which it cannot decode, is akin to establishing a watch on which had a label selector applied to it.

**Comment by jessesuen** [comment]
As an experiment, I added a continue statement in the in `streamwatcher.go::receive()` which partially solves this problem, by allowing the receive loop to move past the undecodable resource, as opposed to returning and immediately falling back into the problematic state. 
```
default:
	msg := "Unable to decode an event from the watch stream: %v"
	if net.IsProbableEOF(err) {
		glog.V(5).Infof(msg, err)
	} else {
		glog.Errorf(msg, err)
		continue // <-- added
	}
}
```

However this only solves half of the problem. On every resync period, the ListAndWatch() will kick in, and it will then start failing in `reflector.go::ListAndWatch()`. But luckily the listFunc is user supplied to the ListWatch, and I believe it should be possible to write a list function that is more accepting of incongruent resources.

**Comment by liggitt** [comment]
> It is not possible to block a CR (which doesn't adhere to a specific data structure) from being created.

It is with the CRD validation feature (see https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation)

If you don't want to use that, and really want to allow arbitrarily structured objects to be persisted, then you could have the watch decode into a [runtime.Unstructured](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L31-L46) object, and use [runtime.DefaultUnstructuredConverter.FromUnstructured(unstructuredObj, typedObj)](https://github.com/kubernetes/kubernetes/blob/2cbb07a4394ef4cfc1666e114674a047023ed178/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L124-L144) to obtain a typed object at point of use. That maintains the store integrity and lets you handle conversion errors as you wish, while still knowing about the existence of the malformed objects.

> Now, if an informer is established and specifies a particular runtime.Object, and the watch encounters an resource which cannot decode to that object, it seems the logical choice is to ignore it.

No, as mentioned before, that leaves the internal store in an inconsistent state.

> Having the watch ignore resources which it cannot decode, is akin to establishing a watch which has a label selector applied to it.

No, that's a principled filter that maintains a local cache of resources that match the specified selector.

**Comment by jessesuen** [comment]
> If you don't want to use that, and really want to allow arbitrarily structured objects to be persisted, then you could have the watch decode into a runtime.Unstructured object,

Fair enough. It's not that we _want_ to allow them to be persisted (we don't) - we just did not have a mechanism to prevent it. I agree that CRD validation would be ideal, but is not very practical for us at the moment since we incorporate a lot of k8s types (container, volumes, volumeClaimTemplates, secretSelectors) as part of our CR, and coming up with the validation schema for all of them will be difficult. I will follow your advice of decoding into the runtime.Unstructured object and converting them at point of use.

That said, is the conclusion of this bug is that it is acceptable for the watch to stop functioning and fall into this tight error loop?

**Comment by caesarxuchao** [comment]
cc @yliaog

**Comment by jessesuen** [comment]
In case anyone else requires the workaround for this. This was the change necessary to protect our controller from bad manifests:
https://github.com/argoproj/argo/commit/8d96ea7b1b1ba843eb19a0632bc503d816ab9ef3
