### ISSUE TITLE
kube-apiserver is never killed gracefully

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#57707]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When kube-apiserver's livenessProbe suggests that pod is unhealthy, kubelet tries to kill its container with 30 seconds grace period.
The container is killed ungracefully with SIGKILL when grace period passes. This happens each time.

```
Dec 29 13:07:05 kubelet[1579]: kuberuntime_container.go:561] Killing container "docker://763de1ad420fc26c5fd4997bac7cc44f5c540a123778fc18b636eb24fbc83d5a" with 30 second grace period
Dec 29 13:07:36 audit: EXECVE argc=5 a0="docker-runc" a1="kill" a2="--all" a3="763de1ad420fc26c5fd4997bac7cc44f5c540a123778fc18b636eb24fbc83d5a" a4="SIGKILL"
Dec 29 13:07:36 kubelet[1579]: kubelet.go:1917] SyncLoop (PLEG): "kube-apiserver-gke-05f87b26119bc247ce64-b9bf-08d2-vm_kube-system(1073a53f8bbfcf5f46fe7e4b66f4663f)", event: &pleg.PodLifecycleEvent{ID:"1073a53f8bbfcf5f46fe7e4b66f4663f", Type:"ContainerDied", Data:"763de1ad420fc26c5fd4997bac7cc44f5c540a123778fc18b636eb24fbc83d5a"}
```

**What you expected to happen**:

I expected that SIGTERM will be passed to kube-apiserver which will try to gracefully stop before 30 seconds pass (at least in some cases).

**How to reproduce it (as minimally and precisely as possible)**:

- Inject kube-apiserver failure (e.g. `iptables -I INPUT -i lo -p tcp --dport 8080 -j REJECT`)
- Watch kubelet logs for container's death
- You will see that container is killed after 30 seconds each time

**Anything else we need to know?**:
I believe the problem is that in kube-apiserver.manifest uses '/bin/sh -c CMD' as a PID1 process which doesn't pass SIGTERM signals to child process.  See https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html#a-common-pitfall-while-handling-the-sigterm

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.11

**Comment by yue9944882** [comment]
Seems like it is decided by [docker](https://github.com/moby/moby)'s mechanism?

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L242](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L242)

@mborsz 
Looks like without `/bin/sh -c CMD` the pipe command `1>>/var/log/kube-apiserver.log 2>&1` will have to be removed which will make the logs hard to track. There is indeed some [walk-arounds](https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash) which makes kube-apiserver run in background `&` and trapping SIGTERM then send a SIGTERM to apiserver's PID.

**Comment by wojtek-t** [comment]
@kubernetes/sig-node-bugs @kubernetes/sig-cluster-lifecycle-bugs 
I think this is the case for all our components, not just kube-apiserver.

@roberthbailey - FYI

**Comment by mborsz** [comment]
@yue9944882 

How about using 'exec'-based solution suggested here: https://unix.stackexchange.com/a/196053/268453?
In our case it means prepending 'exec':

```
exec /usr/local/bin/kube-apiserver {{params}} --allow-privileged={{pillar['allow_privileged']}} 1>>/var/log/kube-apiserver.log 2>&1
```

I did changed this in my cluster and the process seems to meet requirements:
* fd/1 and fd/2 are redirected to /var/log/kube-apiserver.log
* container is killed instantaneously

If everyone is fine with such a solution, I can prepare PR adding 'exec ' in front of all kubernetes/cluster/saltbase/salt/kube-apiserver/*.manifest using '/bin/sh -c CMD' pattern.

**Comment by yue9944882** [comment]
@mborsz  
Can `exec`  be omitted like it was before [https://github.com/kubernetes/kubernetes/commit/96439b5a528ef66da47252e0b2dd0927f6938e7d](https://github.com/kubernetes/kubernetes/commit/96439b5a528ef66da47252e0b2dd0927f6938e7d)?

**Comment by mborsz** [comment]
@yue9944882 
Not sure if understand what you mean.
Before 96439b5 there was no logs, so /bin/sh -c wasn't needed.
`exec`-based solution seems to have all required properties.
What is your concern about using it?

**Comment by yue9944882** [comment]
@mborsz 
I just tried `exec` and it works fine for me. 👍
