### ISSUE TITLE
[E2E Node] [Alpha: DynamicKubeletConfig] setKubeletConfiguration will return before new configuration has taken effect

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/kubernetes#57701]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Run e2e node test with `tempSetCurrentKubeletConfig()`, and wait for new configuration take effect.
But it will return `before` new configuration has taken effect.

**What you expected to happen**:

`setKubeletConfiguration()` will return with new configuration has taken effect.

**How to reproduce it (as minimally and precisely as possible)**:

Run any e2e node test with `DynamicKubeletConfig`.

**Anything else we need to know?**:

This is because we use period = 10 * time.Second and jitterFactor = 0.2 in [cc.syncConfigSource(client, nodeName)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubeletconfig/controller.go#L220-L222).
In extreme scenarios, it will take at least 12 seconds for Kubelet to catch this new config.

We use this [logic](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/util.go#L175-L186) to check whether kubelet is restarted:
```go
// poll for new config, for a maximum wait of restartGap
Eventually(func() error {
	newKubeCfg, err := getCurrentKubeletConfig()
	if err != nil {
		return fmt.Errorf("failed trying to get current Kubelet config, will retry, error: %v", err)
	}
	if !reflect.DeepEqual(*kubeCfg, *newKubeCfg) {
		return fmt.Errorf("still waiting for new configuration to take effect, will continue to watch /configz")
	}
	glog.Infof("new configuration has taken effect")
	return nil
}, restartGap, pollInterval).Should(BeNil())
```
This `Eventually()` will return OK immediately as `newKubeCfg` has been set to etcd, but kubelet don't restart with this `newKubeCfg`.
This function `setKubeletConfiguration` will return before new configuration has taken effect.

I will send a PR to fix this.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/area kubelet
/sig node
/assign @mtaufen 
/cc @vishh @jiayingz @derekwaynecarr @dchen1107 @liggitt 
PTAL, Thanks!

**Comment by mtaufen** [comment]
The comment that `newKubeCfg` will immediately contain the new (presumably changed) config prior to a Kubelet restart is incorrect. `getCurrentKubeletConfig()` scrapes the values from the Kubelet's /configz endpoint, which won't have updated to the new configuration until after the Kubelet has restarted.

**Comment by ScorpioCPH** [comment]
@mtaufen Hi, thanks for your explanation!

>  which won't have updated to the new configuration until after the Kubelet has restarted.

I add some timestamps to test this, but the result is not the some as you described.
For example, `getCurrentKubeletConfig()` returned at `00:00:00`, but Kubelet restarted at `00:00:03`.

And after reading the code,  `getCurrentKubeletConfig()` is just call this API: `api/v1/proxy/nodes/{node_name}/configz`, and i don't find any code about waiting for Kubelet has restarted. Could you point me these code please? Thanks very much!

**Comment by mtaufen** [comment]
Are you actually changing the configuration object's values? 
`getCurrentKubeletConfig()` will return the old values until the Kubelet restarts (because /configz will return the old values until the Kubelet restarts). In any case where you actually change the config values, the `reflect.DeepEqual` assertion will fail until the Kubelet restarts, and thus you'll wait for the restart before continuing past the `Eventually`.

**Comment by mtaufen** [comment]
> @mtaufen Thanks, I think this is because Kubelet will read dynamic-kubelet-config/checkpoints on starting, the configuration is always equal to the last time changed. So getCurrentKubeletConfig() will return immediately.

`getCurrentKubeletConfig()` returns as soon as it gets a 200 response from /configz. Nothing to do with which config the Kubelet read. If the Eventually is exiting early, it's probably because no values were changed. The Kubelet may not have even restarted yet.  

> But I have another question here: should we double check the newCfg is not equal to the oldCfg before we call setKubeletConfiguration(newCfg) in tempSetCurrentKubeletConfig()?

That's probably a useful optimization.

**Comment by ScorpioCPH** [comment]
> If the Eventually is exiting early, it's probably because no values were changed. The Kubelet may not have even restarted yet.

Yes, I agree with you.

> That's probably a useful optimization.

@mtaufen Hi, https://github.com/kubernetes/kubernetes/pull/57812, PTAL, Thanks.
