### ISSUE TITLE
kubernetes service failing to find upstreams

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#57710]
/kind bug

Running on GKE: K8 1.8.4

After a few rollouts of a deployment, eventually the ClusterIP service fails to detect upstream pods.  Note the `Endpoints:                <none>` on the service.  We have tried deleting both the service and the deployments to no avail.

Service:
```
❯ kubectl describe service at-consumer-platform
Name:                     at-consumer-platform-service
Namespace:                default
Labels:                   app=at-consumer-platform
                          chart=helm-at-consumer-platform-0.1.78
                          heritage=Tiller
                          release=at-consumer-platform
                          version=11
Annotations:              cloud.google.com/load-balancer-type=Internal
Selector:                 app=at-consumer-platform
Type:                     LoadBalancer
IP:                       10.178.4.40
IP:                       10.176.0.10
LoadBalancer Ingress:     10.176.0.10
Port:                     http-web  80/TCP
TargetPort:               %!d(string=http-web)/TCP
NodePort:                 http-web  30727/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

Pods (selecting by the same label):
```
❯ kubectl get pod -l app=at-consumer-platform
NAME                                    READY     STATUS    RESTARTS   AGE
at-consumer-platform-668548c9b7-gml9h   2/2       Running   0          12m
```

```
❯ kubectl describe pod at-consumer-platform-668548c9b7-gml9h
Name:           at-consumer-platform-668548c9b7-gml9h
Namespace:      default
Node:           gke-platform-dev-default-pool-0c3859a1-p8pb/10.176.0.4
Start Time:     Fri, 29 Dec 2017 15:25:44 +0000
Labels:         app=at-consumer-platform
                pod-template-hash=2241047563
```

**Comment by Stono** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by Stono** [comment]
This screenshot shows the GUI version, which does show the pods under the service (but i presume it's just doing a pod selector).  This contradicts the CLI reponse

![Uploading Screen Shot 2017-12-29 at 15.41.36.png…]()

**Comment by Stono** [comment]
OK - I have got to the bottom of this late on a friday problem.
Due to an error in the helm template, the container specification was missing the port, subsequently the load balancer couldn't health check it (hence no health upstreams).

This is totally user error, but perhaps some better error messages like `Pods matched but failed to find named port` or something along those lines would help a lot here!

**Comment by lavalamp** [comment]
This is not api machinery. But you may want to figure out why `%!d(string=http-web)/TCP` is in the TargetPort.
