### ISSUE TITLE
kubectl cp: target file is not renamed correctly when using a different source and target filename

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#57712]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When using `kubectl cp` the target file has an incorrect name.

Strangely enough, this shouldn't be possible.

**What you expected to happen**:

The target file has the name I specified.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl cp ./my-file.tar.gz my-pod:/data/bar.tar.gz
```

... the file will actually appear as `data/my-file.tar.gz`

**Anything else we need to know?**:

Related to #40869

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a gi
t tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}                              
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTr
eeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}                    
```

- Cloud provider or hardware configuration: Minikube
- OS (e.g. from /etc/os-release): Gentoo
- Kernel (e.g. `uname -a`): `4.12.12-gentoo`
- Install tools: minikube

**Comment by ShualLiu** [comment]
I make a test. The latest version has fixed it.

**Comment by niuzhenguo** [comment]
@ShualLiu Yes, there's no such issue on master branch.

**Comment by paralin** [comment]
I see the client was 1.6 and server 1.8. Likely some incompatibility.
