### ISSUE TITLE
CSI adapters for existing in-tree volume plugins

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#57715]
As discussed in wg-cloudprovider and sig-storage meetings, @ublubu and me started working on CSI adapters fthe cloudprovider-side of volume plugins. This issue is here to track progress.

Currently the first being worked are AWS, CGE and Azure, if anyone is interested feel free send PRs.

cc @wlan0 @ublubu @jsafrane 

/sig storage
/assign

**Comment by karataliu** [comment]
Good to see this.

Regarding the 'adapters' here, does it mean something built upon the current cloud volume plugins, and it implements CSI driver interface or such? And where will the code be placed?

Currently cloud volume plugins mostly have dependency on corresponding cloud providers, which is planned to be moved out-of-tree. What's the plan for the CSI implementations, will they also be moved?

**Comment by ublubu** [comment]
The existing volume sources will be around for a while, so we can't yet move the provider-specific code out of the tree. In the meantime, we're wrapping existing volume implementations into CSI plugins (using the framework provided by https://github.com/kubernetes-csi). Presumably, users will switch to CSI over time and then we can move the volume implementations out-of-tree and remove the old volume sources.

**Comment by khenidak** [comment]
CC:- @andyzhangx @jdumars

**Comment by andyzhangx** [comment]
/reopen
Since it's not done
