### ISSUE TITLE
kubectl should be backwards compatible

### ISSUE THREAD

**Issue by Dundee** [kubernetes/kubernetes#57748]
Kubectl is currently not backwards compatible.

When I use kubectl v1.9.0 with cluster v1.6.3, I cannot edit deployments.

I get error "Error from server (NotFound): the server could not find the requested resource" similar to #9945.

It's sometimes not so easy to upgrade the cluster (as the client).
I think either kubectl should work with all older cluster versions with the same MAJOR version or if compatibility breaks are needed, then MAJOR version should be raised.

/kind bug

**Environment**:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
kubectl supports one version forward and backward skew:

from https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

> a client should be skewed no more than one minor version from the master, but may lead the master by up to one minor version. For example, a v1.3 master should work with v1.1, v1.2, and v1.3 nodes, and should work with v1.2, v1.3, and v1.4 clients.
