### ISSUE TITLE
how to get the pod ip when access external service

### ISSUE THREAD

**Issue by du2016** [kubernetes/kubernetes#57740]
**What happened**:

when pod in k8s access external service,the snat policy will replace pod ip by node ip ,some times i want to get the pod ip to trouble shooting,but i got node ip

**What you expected to happen**:

external service can get the pod ip

**Comment by hzxuzhonghu** [comment]
Can not make this, without snat, data packet can not be back.

**Comment by du2016** [comment]
@hzxuzhonghu add static route or other ways can do this ,such as i can run ospf on every node

**Comment by hzxuzhonghu** [comment]
Sorry, I don't have much knowledge about  `ospf `. But does it need config on both sides.

**Comment by du2016** [comment]
yes,it need config on every node or switch ,bgp or ospf can get through  container network and physical network,when i do this ,i think i don't need snat or dnat rules except cluster ip

**Comment by hzxuzhonghu** [comment]
I see a little, but seems this is not only kubernetes can handle.

**Comment by du2016** [comment]
thank you,i will have a look about calico, may by calico calico this

**Comment by hzxuzhonghu** [comment]
If you really need your server to distinguish client by ip, there is another way,  get podip in client side, and include in request each time.

**Comment by du2016** [comment]
ok  thanks
