### ISSUE TITLE
Support pod resource updates

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#5774]
Following the doc [https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl-update.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl-update.md), 

I tried the command :

```
$ kubectl update pods my-pod --patch='{ "apiVersion": "v1beta1", "desiredState": { "manifest": [{ "cpu": 100 }]}}'
```

It says:

```
some fields are immutable
```

Is it a bug or the doc provided a bad example?

**Comment by roberthbailey** [comment]
@bgrant0607 can you please take a look and assign appropriately for a fix (code or documentation)?

**Comment by hurf** [comment]
I volunteer myself to fix this once the 'which side' problem is comfirmed .

**Comment by bgrant0607** [comment]
We should allow resources to be updated.

It looks like they are included in container hash, so the container should be deleted and re-created with the new values.

@dchen1107 @vishh Can you think of anything else we need to do to permit resource updates other than just relax validation?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/validation/validation.go#L697

**Comment by gmarek** [comment]
@hurf: I'll assign myself to take a lock for you on this issue (only owners can be assigned). If for whatever reason you'll want to release it cc me in a comment.

**Comment by vishh** [comment]
@bgrant0607: Nope. I think its safe to turn on pod resource updates.

**Comment by dchen1107** [comment]
Since we all agreed on kubelet is the last line of defense on resource quota / mission control, I am ok on pod resource updates.;

**Comment by hurf** [comment]
@gmarek - Thanks, I'm working on it.

**Comment by gmarek** [comment]
@hurf - what's the status of this?

**Comment by hurf** [comment]
@gmarek - My work on this has been interrupted by other stuff, but this week I have just gone back to this, I will finish it and submit a patch ASAP.

**Comment by gmarek** [comment]
@hurf - ping?

**Comment by hurf** [comment]
@gmarek - alive, code finished and will submit soon. The change is loosen the validation as bgrant pointed out and changed a test.

**Comment by hurf** [comment]
@gmarek - Sorry for the delay for I'm also working on other issues. Please review the patch, if it's not working as what's in your mind, please tell me and I'll modify the patch.

**Comment by bgrant0607** [comment]
FYI @jszczepkowski

**Comment by bgrant0607** [comment]
@resouer why do you want to update resources of a running pod, as opposed to replacing the pod? Docker restarts the container, regardless, and pods of continuously running applications should be running under replication controllers, so rolling-update could be used to roll out updated limits.

**Comment by resouer** [comment]
@bgrant0607  Actually, I don't. Just try to track the original issue.

Honestly, I think we should implement the limit/request model completely in prior to this.

**Comment by bgrant0607** [comment]
Resource QoS has been implemented: #12182

**Comment by davidopp** [comment]
ref/ #9043

**Comment by kargakis** [comment]
This was probably related to patch trying to remove fields that it shouldn't. Please retry with the latest `kubectl patch` command and play around with the different strategies.

**Comment by davidopp** [comment]
We never implemented in-place resource update. It's actually pretty complicated to do it right.

**Comment by tnachen** [comment]
Will love to see some discussion around the work needed here to make this happen. Is there any existing docs about designing yet or?

**Comment by davidopp** [comment]
@kubernetes/sig-node-feature-requests

**Comment by Novex** [comment]
I'd also love to see this progress. What's the next step and is there anything I can do to help out?

**Comment by kisshore** [comment]
Hello @vinaykul ,
Is there any update of it ? is that document got approved?

**Comment by kisshore** [comment]
When docker supporting 

> #docker update

 command , why not kubernetes?

**Comment by hustcat** [comment]
+1 for this feature

**Comment by erolosty** [comment]
+1 here too

**Comment by vinaykul** [comment]
> Hello @vinaykul ,
> Is there any update of it ? is that document got approved?

@kisshore @hustcat @erolosty sig-autoscaling has taken the initiative and started a [new merged KEP](https://github.com/kubernetes/community/pull/2908/commits/4ad6fa7c27f4a21c27a6be83c2dc81c43549fa55) based on our design and the IBM proposal.

Based on my conversations with Beata / Solly during KubeCon this past week, we need the blessings of sig-node. 

We are hoping to get the design finalized and then work on implementation, reviews, unit-tests, VPA integration (we have a working prototype based on our current design) etc.. 

CC: @DirectXMan12 @bskiba @derekwaynecarr @bsalamat

**Comment by M0nsieurChat** [comment]
> > Hello @vinaykul ,
> > Is there any update of it ? is that document got approved?
> 
> @kisshore @hustcat @erolosty sig-autoscaling has taken the initiative and started a [new merged KEP](https://github.com/kubernetes/community/pull/2908/commits/4ad6fa7c27f4a21c27a6be83c2dc81c43549fa55) based on our design and the IBM proposal.
> 
> Based on my conversations with Beata / Solly during KubeCon this past week, we need the blessings of sig-node.
> 
> We are hoping to get the design finalized and then work on implementation, reviews, unit-tests, VPA integration (we have a working prototype based on our current design) etc..
> 
> CC: @DirectXMan12 @bskiba @derekwaynecarr @bsalamat

Hello, we are highly interested in the inPlace ResizingPolicy for using the Vertical Pod Autoscaler.
I have trouble finding if the relevant commits have already been merged in Kubernetes in order to test / leverage this interesting feature.

**Comment by riking** [comment]
KEP updated recently: https://github.com/kubernetes/enhancements/pull/686

/remove-lifecycle rotten
/reopen

**Comment by xiaods** [comment]
@andyxning  any update on it.

**Comment by xiaods** [comment]
any update?

**Comment by vinaykul** [comment]
/remove-lifecycle stale

Redesigned API changes is under review: https://github.com/kubernetes/enhancements/pull/1883

**Comment by vinaykul** [comment]
/remove-lifecycle stale

KEP approved and targeted for next release. Implementation in progress.

**Comment by pacoxu** [comment]
/triage accepted
/remove-priority awaiting-more-evidence
/priority important-soon
for next release
