### ISSUE TITLE
Wrong DeviceMountPath for ceph rbd volume plugin

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#57744]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

The `GetDeviceMountPath` method for ceph rbd volume plugin generates the path with code as follows:

```go
func makePDNameInternal(host volume.VolumeHost, pool string, image string) string {
	return path.Join(host.GetPluginDir(rbdPluginName), "rbd", pool+"-image-"+image)
}
```

So the device mount path's format will be:  `{pluginName}/rbd/...`, this implementation has two problems:

1. Inconsistent with other volume plugins, as all the other plugins return `{pluginName}/mounts/...`, see [EBS](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/volume/aws_ebs/aws_ebs.go#L387) as an example.

2. The `ConstructVolumeSpec` method of ceph rbd plugin is not working properly, because rbd plugin uses [getDeviceNameFromMount](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/util/mount/mount_linux.go#L342) method to find the device mount path(just like all the other plugins do), and `getDeviceNameFromMount` method assumes the device mount path's format is `{pluginName}/mounts/...`(see [this line](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/util/mount/mount_linux.go#L352)).

**What you expected to happen**:

The device mount path of rbd plugin should be `{pluginName}/mounts/...`.

**Anything else we need to know?**:

Do we have any reason for this design? If not, I will submit a PR to fix this, the adjusted `makePDNameInternal` method maybe look like this:

```go
func makePDNameInternal(host volume.VolumeHost, pool string, image string) string {
	// Backward compatibility for the old path format:
	// /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/pool-image-image
	legacyDir := path.Join(host.GetPluginDir(rbdPluginName), "rbd", pool+"-image-"+image)
	info, err := os.Stat(legacyDir)
	if err == nil && info.IsDir() {
		// The device mount path has already been created with the old format, return it.
		return legacyDir
	}
	// Return the new format path.
	return path.Join(host.GetPluginDir(rbdPluginName), mount.MountsInGlobalPDPath, pool+"-image-"+image)
}
```

/sig storage

**Comment by rootfs** [comment]
nice catch @mlmhl 

There are two ways to fix this:
- Change mount path. But this will introduce compatibility issues during upgrade.
- Use [mount.GetDeviceNameFromMount](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/util/mount/mount.go#L171), instead of [mounter.GetDeviceNameFromMount](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/util/mount/mount_linux.go#L335) [here](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/volume/rbd/rbd.go#L351)

PR welcome @mlmhl

**Comment by rootfs** [comment]
cc @wenjun93

**Comment by mlmhl** [comment]
Hi @rootfs , there is a difference between `mount.GetDeviceNameFromMount` and `mounter.GetDeviceNameFromMount`: `mount.GetDeviceNameFromMount` returns the device path, such as `/dev/rbd0`, and `mounter.GetDeviceNameFromMount` returns the device mounted path, such as `/var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/{pool}-image-{image}`. What we really want is the second one, as we need to find the pool and image name. So we can't just simply replace `mounter.GetDeviceNameFromMount` with `mount.GetDeviceNameFromMount`.

Maybe we can find the mounted path specially for rbd plugin, use `GetMountRefsByDev`, the code looks like this:

```go
func (plugin *rbdPlugin) ConstructVolumeSpec(volumeName, mountPath string) (*volume.Spec, error) {
	mounter := plugin.host.GetMounter(plugin.GetPluginName())
	refs, err := mount.GetMountRefsByDev(mounter, mountPath)
	if err != nil {
		return nil, err
	}
	sourceName := ""
	// baseMountPath is the prefix of device global mounted path, such as:
	// /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd
	baseMountPath := filepath.Join(plugin.host.GetPluginDir(rbdPluginName), "rbd")
	for _, ref := range refs {
		if dstrings.HasPrefix(ref, baseMountPath) {
			sourceName, err = filepath.Rel(baseMountPath, ref)
			if err != nil {
				return nil, err
			}
			break
		}
	}
	if len(sourceName) == 0 {
		return nil, fmt.Errorf("can't find source name from mounted path: %s", mountPath)
	}

	// other code...
}
```

**Comment by rootfs** [comment]
@mlmhl thanks

let make a forward moving plan:
- fix `makePDNameInternal` and append `mount.MountsInGlobalPDPath` to the global path
- keep `mounter.GetDeviceNameFromMount` in `ConstructVolumeSpec`. If no path is found, fall back to old path scheme using your code

**Comment by mlmhl** [comment]
Nice idea @rootfs , I've submit a PR for this, PTAL.

**Comment by wenjun93** [comment]
@rootfs @mlmhl I've checked and the reason is that I tested with the old release branch, see https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/util/mount/mount.go#L191, after release-1.8, the `getDeviceNameFromMount` has been changed with `mounts` in mount path, and causes the problem. thanks for your PR @mlmhl.

**Comment by rootfs** [comment]
@mlmhl i read `getDeviceNameFromMount` again. There is another return path [here](https://github.com/kubernetes/kubernetes/blob/da9a4d5da9ecc6f687c873fb990d662b1f9f98b2/pkg/util/mount/mount_linux.go#L364). So in rbd, the missing `mounts` dir will not make into [this return](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L360), but the second return should still give us the dir we need `{pool}-image-{image}`

**Comment by mlmhl** [comment]
You are right @rootfs , `getDeviceNameFromMount` indeed has two return path, but the second return still can't meet our needs. Because the `mountPath` parameter of `getDeviceNameFromMount` is the mount path for a specific pod, such as `/var/lib/kubelet/pods/80043ba0-f1b7-11e7-8c96-0800273c9701/volumes/kubernetes.io~rbd/pvc-6d931b5d-f1b7-11e7-8c96-0800273c9701`, its format is `/var/lib/kubelet/pods/{podUID}/volumes/{volumePluginName}/{volumeName}`, so `path.Base(mountPath)` will return the volume name. This volume name is returned by `volume.Spec`(see [here](https://github.com/kubernetes/kubernetes/blob/afbbd394c125ff443fb711741e6e06f996920ffd/pkg/volume/plugins.go#L328)), usually is the PV's name or the name specified in `Pod.Spec.Volumes`, both of these are not `{pool}-image-{image}`.
