### ISSUE TITLE
Add  a structure of realtime allocated resource in node status 

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/kubernetes#57773]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> 
> /kind feature

**What happened**:

**What you expected to happen**:
Hope to add a structure in node status to record the resource could be allocated for the pods to be scheduled to the node, or a structure of allocated resource list of the node:
```
type NodeStatus struct {
     ...
    // Allocated represents the resource already allocated by the pods running on the node, kubelet will update the phase when there is event of pod ADD/DELETE
    Allocated ResourceList `json:"allocated,omitempty" protobuf:"bytes,2,rep,name=allocated,casttype=ResourceList,castkey=ResourceName"`
    ...
}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by jiaxuanzhou** [comment]
@ resouer

**Comment by feiskyer** [comment]
@jiaxuanzhou What's the use cases of this?

cc @kubernetes/sig-node-feature-requests

**Comment by jiaxuanzhou** [comment]
@feiskyer when there are several k8s clusters , when wanting to launch some apps or jobs to the target cluster, the orchestrator need to know the total resource of each cluster in coarse-grained, and also  need to know the allocated resource of the node in the target cluster to decide the scale of the apps or jobs to launch.

**Comment by jiaxuanzhou** [comment]
@resouer @feiskyer any update?

**Comment by feiskyer** [comment]
@jiaxuanzhou Allocated resources could already be fetched from node status and pod list (see kubectl describe node).

**Comment by jiaxuanzhou** [comment]
@feiskyer yes ,i see it, but when to get the result of the allocated totally, we need to list all the pods of the node and calculate it, it is not the right way and low performance to do it, so we suggest kubelet calculating it and update it to not status, or would you suggest any other solutions to figure it out? 
thanks

**Comment by jiaxuanzhou** [comment]
on the other hand, instead we can also record the the requested resource of the pods belong to the node in the prometheus interface.

**Comment by resouer** [comment]
I totally understand what you are asking. 

But I would suggest you don't try to require API change of node in sig-node, but try to ask exporting this information from kube-scheduler. 

Because it is scheduler that maintains this information by a internal data structure named `nodeInfo`, if register part of its info into kube-scheduler's metric, you'll be set.

**Comment by resouer** [comment]
Feel free to ping me if you agree to close this one and create a new issue in sig-scheduling. I can help with that.

**Comment by jiaxuanzhou** [comment]
@resouer Harry, i considered that before, if we collect the metrics from scheduler, we can not export the total objs of the pods related with nodes, as there is no available api to get the pods objs from scheduler;  if just want to add metrics in prometheus interface, only total requested resource of the cluster could be calculated and export to prometheus counter.
 i still wish the metric of the requested resources could be scraped by prometheus in sig/node, as there are container_spec_cpu_quota for cpu limits and container_spec_memory_limit_bytes for mem limits, but there are no metrics of the requested resources, do you agree to add the metrics of the requested resources(container level or pod level, even node level, all works)?

**Comment by resouer** [comment]
Of course you can ...  Please take a look at `NodeInfo` data structure as I mentioned above: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedulercache/node_info.go#L39 It definitely contains everything you want, and again, kubelet does not even care about `resources.request` , it's a 100% scheduler knowledge.

The issue need to be discussed will the metrics expected to be exported, which will be much simpler than changing a core API object.
