### ISSUE TITLE
Possible error while using `kubeadm upgrade`

### ISSUE THREAD

**Issue by rajansandeep** [kubernetes/kubernetes#57783]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
In the scenario when I have CoreDNS installed via `kubeadm init` and I want to continue using CoreDNS after `kubeadm upgrade`, the upgrade is unsuccessful and it gives an error:

```
....
bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy
[upgrade/postupgrade] FATAL post-upgrade error: timed out waiting for the condition
```
I suspect this occurs as it times out waiting for the kube-dns deployment, which is non-existent in this scenario.

**What you expected to happen**:
Successfully upgrade kubernetes using `kubeadm upgrade` with no errors.

**How to reproduce it (as minimally and precisely as possible)**:
- Use `kubeadm init --feature-gates CoreDNS=true` to install CoreDNS.
- Then upgrade using `kubeadm upgrade apply v1.10.0-alpha.1 --feature-gates CoreDNS=true --allow-experimental-upgrades`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by luxas** [comment]
Please move this issue to the kubeadm repo.

**Comment by StodaraHodan** [comment]
update on what the issue was?
