### ISSUE TITLE
if create a endpoint independently, restart kubernetes master, this endpoint should not be deleted.

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/kubernetes#57794]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
if create a endpoint independently, restart kubernetes master, this endpoint was deleted.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L531
this function do some cleanup when master restart. But if we want create a endpoint for other purpose, not for service. so this function is redundant.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by freehan** [comment]
@kubernetes/sig-network-misc

**Comment by thockin** [comment]
This is part of the design of Endpoints - you need to create a Service to go with it, or it will get cleaned up.

**Comment by zhangxiaoyu-zidif** [comment]
Thanks, Tim! @thockin . I see it is the design of service. Some people wanted to create endpoint for gluster(storage) without service. by accident, the kubernetes master restarted, so the endpoint lost because of cleanup. You see, some customers are always imaginative. they could create any possible usage scenario.

**Comment by MrHohn** [comment]
FYI The endpoint cleanup logic in endpoint controller was deactivated by https://github.com/kubernetes/kubernetes/pull/57747.

**Comment by zhangxiaoyu-zidif** [comment]
@MrHohn  Thanks！
