### ISSUE TITLE
labels for endpoints object

### ISSUE THREAD

**Issue by kidiyoor** [kubernetes/kubernetes#57815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

How to create a service which load balance between multiple external IPs. ?

I do not want create a single endpoints object and add multiple IPs since each external IP has its own lifecycle. 

Selector less service won't help since it requires endpoints to have same name as service, hence I can't have multiple endpoints object.

why does endpoints object doesn't support labels ?

**Comment by kidiyoor** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by lavalamp** [comment]
Not API Machinery.
