### ISSUE TITLE
./cluster/kube-up.sh doesn't seem to work with OpenStack API v3?

### ISSUE THREAD

**Issue by soichih** [kubernetes/kubernetes#57814]
I am trying to following this doc to install Kubernetes on my OpenStack account (Jetstream public cloud)
> https://kubernetes.io/docs/getting-started-guides/openstack-heat/

I have following on my openrc.sh

```
...
export OS_AUTH_URL=https://our.openstack.org:35357/v3
export OS_IDENTITY_API_VERSION=3
```

When I run `./cluster/kube-up.sh`, I get following error message.

```
$ KUBERNETES_PROVIDER=openstack-heat ./cluster/kube-up.sh
... Starting cluster using provider: openstack-heat
... calling verify-prereqs
swift client installed
glance client installed
nova client installed
heat client installed
openstack client installed
... calling veriy-kube-binaries
... calling kube-up
kube-up for provider openstack-heat
[INFO] Execute commands to create Kubernetes cluster
Container POST failed: https://our.openstack.org:8080/swift/v1/kubernetes 403 Forbidden   AccessDenied
Failed Transaction ID: tx000000000000000084e3e-005a4d8b5b-43c73ca0-default
```

I am seeing this error on Ubuntu 16 machine running Kubenetes release v1.7.12. 

Is auth version 3 not supported by kube-up script?

**Comment by dims** [comment]
@soichih the openstack heat based kube-up is deprecated. please see details and alternatives at https://github.com/kubernetes/website/pull/5670#issuecomment-355019548
