### ISSUE TITLE
pull-kubernetes-cross consistently failing with docker registry TLS handshake timeouts

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#57822]
Since about 6:00 PT today (Jan 3 2017), `pull-kubernetes-cross` tests [are failing across the board](https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&job=pull-kubernetes-cross) with docker registry TTLS handshake timeouts:

```
Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
...
Get https://gcr.io/v2/: net/http: TLS handshake timeout
```

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/56534 was a big change around then, though nothing obvious in it jumps out at me

**Comment by liggitt** [comment]
Never mind.… 6AM

**Comment by cblecker** [comment]
@kubernetes/sig-testing-misc 
Looks infra related

**Comment by jpbetz** [comment]
`pull-kubernetes-cross` is passing again, presumably due to https://github.com/kubernetes/test-infra/pull/6148.  Thanks!
