### ISSUE TITLE
kube-aggregator APIServiceRegistrationController no need watch services

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#57836]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Currently APIServiceRegistrationController watch service change and find the related APIServices related if any. Then it AddAPIService/RemoveAPIService for APIAggregator.  

I dig into the kube-aggregator and find it no need totally, because `AvailableConditionController` update 
APIServices status when related service or endpoint change. So if  `APIServiceRegistrationController ` does not watch services, it will not miss any event for  APIServices.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
> AvailableConditionController update APIServices status when related service or endpoint change. So if APIServiceRegistrationController does not watch services, it will not miss any event for APIServices.

that does not follow. AvailableConditionController modifies the APIService object. APIServiceRegistrationController must still watch the APIService objects to observe those changes.

**Comment by liggitt** [comment]
oh, I misread the description. You're saying APIServiceRegistrationController doesn't need to watch v1.Service objects
