### ISSUE TITLE
service.spec.selector is not io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#57848]
looking at current swagger.json `selector` type in `core.v1.service` is `object`, shouldn't  it be LabelSelector like it was done in https://github.com/kubernetes/kubernetes/pull/19840 ?

/sig api-machinery

**Comment by liggitt** [comment]
no, they're different types.

a service selector is `map[string]string`:
https://github.com/kubernetes/kubernetes/blob/fa2ea5284e608854c9ad5e00699ee013ad3ae886/staging/src/k8s.io/api/core/v1/types.go#L3390-L3397

a deployment selector is metav1.LabelSelector:
https://github.com/kubernetes/kubernetes/blob/fa2ea5284e608854c9ad5e00699ee013ad3ae886/staging/src/k8s.io/api/apps/v1/types.go#L272-L275
