### ISSUE TITLE
Resize cluster: Method not found.

### ISSUE THREAD

**Issue by lvthillo** [kubernetes/kubernetes#57847]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
Nodes did not resize

**What you expected to happen**:
Resize nodes

**How to reproduce it (as minimally and precisely as possible)**:
```
$ gcloud beta container clusters resize cluster-1 --size=0 --region europe-west1
Pool [default-pool] for [cluster-1] will be resized to 0.

Do you want to continue (Y/n)?  y

ERROR: (gcloud.beta.container.clusters.resize) NOT_FOUND: Method not found.
```

**Anything else we need to know?**:
I used Regional (beta) during the setup (europe-west1).

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.7.11-gke.1
- Cloud provider or hardware configuration:
Google Cloud
- OS (e.g. from /etc/os-release):
cos

**Comment by benoit74** [comment]
/kind bug

@lvthillo
This is not a Kubernetes issue but a gcloud SDK issue. Please address your issue to gcloud SDK maintainers.
Obviously I would suggest that your gcloud SDK is most probably out-of-date.
Anyway, we cannot help on this repository, so I recommend to close the issue.
/close

**Comment by lvthillo** [comment]
@benoit74 I'll do, no it's up to date. It was the first install on that machine yesterday, I even ran the update. But it's still in beta. (region)
