### ISSUE TITLE
taint command fails to remove a schedule

### ISSUE THREAD

**Issue by tvinhas** [kubernetes/kubernetes#57842]
/kind bug

**What happened**: 
There's probably some information missing on the docs, or it might be my incapacity to properly find it, but when running `kubectl taint nodes kube11 beta.kubernetes.io/arch=amd64:NoSchedule-` to remove a manually added NoSchedule taint, it fails by saying:
```
root@kubemaster:~# kubectl taint nodes kube11 beta.kubernetes.io/arch=amd64:NoSchedule-
error: invalid taint effect: NoSchedule-, unsupported taint effect
See 'kubectl taint -h' for help and examples.
```

**What you expected to happen**: 
To remove the taint added by the command: `kubectl taint nodes kube11 beta.kubernetes.io/arch=amd64:NoSchedule`

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubectl taint nodes kube11 beta.kubernetes.io/arch=amd64:NoSchedule` and then `kubectl taint nodes kube11 beta.kubernetes.io/arch=amd64:NoSchedule-`

**Anything else we need to know?**:
Tried different combinations, but all failed. Was suggested on slack to use ` kubectl uncordon kube11` but it failed since I didn't use `cordon` in the first place.
Would like to know how to exactly achieve that so I maybe can help updating the documentation as others might have this problem too.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
lient Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/arm"} Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/arm"}
```
- Cloud provider or hardware configuration: Raspberry Pi 3
- OS (e.g. from /etc/os-release): Raspbian Linux 9 (stretch)
- Kernel (e.g. `uname -a`): 4.9.59-v7+
- Install tools: kubeadm
- Others:

**Comment by bsalamat** [comment]
Have you tried
`kubectl taint nodes kube11 beta.kubernetes.io/arch-` or
`kubectl taint nodes kube11 beta.kubernetes.io/arch:NoSchedule-` or

**Comment by tvinhas** [comment]
@bsalamat thanks a lot! Both commands you provided work fine.

I'll add those to the documentation as an example on how to untaint a node, as others might have the same issues I had.
