### ISSUE TITLE
Cronjob started on the wrong schedule after edit

### ISSUE THREAD

**Issue by gzzo** [kubernetes/kubernetes#57853]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

/kind bug

**What happened**: I edited a cronjob's schedule, and the cronjob started immediately after the edit.

I changed the schedule from "30 11 * * 5" (so 11:30AM UTC on Friday) to "0 11 * * 5" (so 11:00AM UTC on Friday) at 23:49 UTC on Thursday.  After the edit, the cronjob created a task immediately.

Even weirder, when I describe the cronjob, it's last scheduled time is wrong.
```
Name:                       cron-send-newsletter-invites
Namespace:                  production
Labels:                     cron=cron-email
Annotations:                <none>
Schedule:                   0 11 * * 5
Concurrency Policy:         Forbid
Suspend:                    False
Starting Deadline Seconds:  <unset>
Selector:                   <unset>
Parallelism:                <unset>
Completions:                <unset>
Pod Template:
  Labels:  <none>
  Containers:
   cron-mednet-web:
    Image:  email:production-0.16
    Port:   <none>
    Command:
      send-newsletter
    Environment:              <none>
    Mounts:                   <none>
  Volumes:                    <none>
Last Schedule Time:           Fri, 29 Dec 2017 06:00:00 -0500
Active Jobs:                  <none>
Events:
  Type    Reason            Age   From                Message
  ----    ------            ----  ----                -------
  Normal  SuccessfulCreate  27m   cronjob-controller  Created job cron-send-newsletter-invites-1514545200
  Normal  SawCompletedJob   14m   cronjob-controller  Saw completed job: cron-send-newsletter-invites-1514545200
  Normal  SuccessfulDelete  14m   cronjob-controller  Deleted job cron-send-newsletter-invites-1513677600
```

**What you expected to happen**: I expected the cronjob to run at its newly scheduled time, not immediately.

**How to reproduce it (as minimally and precisely as possible)**:  Unable to reproduce immediately, will come up with a minimal example if possible.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: AWS
- Install tools: kops

**Comment by xingzhou** [comment]
Can not reproduce the issue on master branch code. Which version are you using?

**Comment by gzzo** [comment]
@xingzhou 1.8.3

One thing that I could have made clearer in the bug description is that I ran `kubectl describe` shortly before posting this issue, so Jan 4 2018.  

This is important since the events that are listed have ages of 27m and 14m, which means that a job was created but somehow the cronjob didn't register that (since the Last Schedule Time is still on Dec 29 2017).

If this was fixed between 1.8.3 and master, do you know any commits I can look at which would have fixed this issue?

**Comment by xingzhou** [comment]
@gzzo, I checkout the tag v1.8.3 of K8s, but still can not reproduce the issue in my env, here is the version I used:
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-dirty", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"dirty", BuildDate:"2018-01-09T03:03:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-dirty", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"dirty", BuildDate:"2018-01-09T03:03:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

if you have separate env, you can take a try on this version. 
Besides, any errors or incidents from the log?

**Comment by gzzo** [comment]
I don't have a separate env handy.

Is it possible that (since startingDeadlineSeconds is unset) the scheduler would schedule a job (thinking it was supposed to run it in the past) after I edited the schedule?

**Comment by gzzo** [comment]
Given that I'm unable to reproduce this issue, I'm closing it.

**Comment by swibrow** [comment]
I also seen this happen to us today. We often enable and disable our test env shutdown cronjop. When I enabled the cron it created a job straight away and last scheduled time is incorrect.
```Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by marceloboeira** [comment]
Same problem here, 

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:27:47Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

From my perspective the schedule must change to something that the `lastScheduledDate` will be not compliant of.

I've seen this behavior already for jobs with small interval, it's not a big issue, but for daily tasks that run at specific times it might be.

My diff:

```
schedule: "0 10 * * *" -- BEFORE
schedule: "0 16 * * *" -- AFTER
```
AND most importantly, I changed it before 10, which I guess make it worse. 

My guess is that the scheduler thinks it didn't run still from the last scheduled date and it tries to run right away.

**Comment by swibrow** [comment]
After reading the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), this is expected behaviour. My fix was to add the following to the jobTemplate.spec:
```
    spec:
      startingDeadlineSeconds: 360
```

**Comment by marceloboeira** [comment]
@swibrow thx. I'll try that. Quite implicit, but it makes sense.

![anigif_sub-buzz-14489-1504742289-8](https://user-images.githubusercontent.com/1898225/46601831-b4d9cd00-caee-11e8-9563-bd9b2b8c7b49.gif)

**Comment by khiav223577** [comment]
Similar to https://github.com/kubernetes/kubernetes/issues/63371
