### ISSUE TITLE
Kubelet package in yum repo not signed

### ISSUE THREAD

**Issue by MarkDeckert** [kubernetes/kubernetes#57855]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

/kind bug

**What happened**:

When trying to do a yum update to 1.9.1 from the kubernetes yum repo, yum update fails and get error: "*long random string* kubelet-1.9.1-0.x86_64.rpm is not signed" 

**What you expected to happen**:  Package to be signed

**How to reproduce it (as minimally and precisely as possible)**: yum update -y

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1 (updating from 1.9.0)
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): CentOS 7
- Install tools: yum

**Comment by shadowlan** [comment]
I met the same issue when run 
```
setenforce 0
yum install -y kubelet kubeadm kubectl
```
the error mgs is "Package efde37cfcd34c8232daafb0337b8ba5fda70100ab6988fca71ba30ce929311dd-kubelet-1.9.1-0.x86_64.rpm is not signed. "
I am using the same kubernetes repository, but yesterday, it installed kubelet-1.9.0-0.x86_64 without any issue.

**Comment by MorgenSun** [comment]
below yum command can manage the previous version install , let`s wait K8S fix this problem soon 

yum install -y kubelet-1.9.0-0.x86_64 kubeadm-1.9.0-0.x86_64 kubectl-1.9.0-0.x86_64

**Comment by MarkDeckert** [comment]
Success.  Thanks!

**Comment by mbohlool** [comment]
I reverted this change as it broke all other versions, will try again tomorrow.

**Comment by oonisim** [comment]
Try to revert to 1.8.6 which has dependency on kubernetes-cni 0.6.0 but it looks there is a dependency on 1.9.1 kubelet?

    ================================================================================
     Package                Arch           Version         Repository          Size
    ================================================================================
    Installing:
     kubernetes-cni         x86_64         0.6.0-0         Kubernetes         8.6 M
    Installing for dependencies:
     kubelet                x86_64         1.9.1-0         Kubernetes          17 M
    
    Transaction Summary
    ================================================================================
    Install  1 Package (+1 Dependent package)
    
    Total size: 25 M
    Installed size: 128 M
    Downloading packages:
    Package efde37cfcd34c8232daafb0337b8ba5fda70100ab6988fca71ba30ce929311dd-kubelet-1.9.1-0.x86_64.rpm is not signed

**Comment by mbohlool** [comment]
should work now. Please verify.

**Comment by oonisim** [comment]
Hi @mbohlool I could install 1.9.1 on CentOS 7 /AWS.

    $ kubectl get nodes
    NAME                                         STATUS    ROLES     AGE       VERSION
    ip-172-31-1-43.us-west-1.compute.internal    Ready     <none>    31s       v1.9.1
    ip-172-31-4-117.us-west-1.compute.internal   Ready     master    3m        v1.9.1
    ip-172-31-4-61.us-west-1.compute.internal    Ready     <none>    31s       v1.9.1
    
    kubectl get pods -n kube-system
    NAME                                                                 READY     STATUS    RESTARTS   AGE
    etcd-ip-172-31-4-117.us-west-1.compute.internal                      1/1       Running   0          2m
    kube-apiserver-ip-172-31-4-117.us-west-1.compute.internal            1/1       Running   0          1m
    kube-controller-manager-ip-172-31-4-117.us-west-1.compute.internal   1/1       Running   0          1m
    kube-dns-6f4fd4bdf-wc7r7                                             3/3       Running   0          2m
    kube-flannel-ds-cjvjl                                                1/1       Running   0          40s
    kube-flannel-ds-jpnlr                                                1/1       Running   0          40s
    kube-flannel-ds-kc85l                                                1/1       Running   0          2m
    kube-proxy-f7j4n                                                     1/1       Running   0          40s
    kube-proxy-fgg9r                                                     1/1       Running   0          40s
    kube-proxy-wmzft                                                     1/1       Running   0          2m
    kube-scheduler-ip-172-31-4-117.us-west-1.compute.internal            1/1       Running   0          2m
    kubernetes-dashboard-6ddcb6df4c-hhxkc                                1/1       Running   0          2m
    tiller-deploy-587df449fb-d95xl                                       1/1       Running   0          2m

**Comment by oonisim** [comment]
Hi @mbohlool, may I clarify? If I recall correctly, 1.8.6 has dependency on kubernetes-cni-0.6.0 as in https://github.com/kubernetes/release/issues/97.

It  looks cni has a dependency on 1.9.1 kubelet, so even when I installed 1.8.6, kubelet is 1.9.1.

    $ sudo yum install kubernetes-cni-0.6.0-0.x86_64
    Loaded plugins: fastestmirror
    Loading mirror speeds from cached hostfile
    * base: mirror.sfo12.us.leaseweb.net
    * epel: s3-mirror-us-west-1.fedoraproject.org
    * extras: centos.s.uw.edu
    * updates: linux.mirrors.es.net
    Resolving Dependencies
    --> Running transaction check
    ---> Package kubernetes-cni.x86_64 0:0.6.0-0 will be installed
    --> Processing Dependency: kubelet for package: kubernetes-cni-0.6.0-0.x86_64
    --> Running transaction check
    ---> Package kubelet.x86_64 0:1.9.1-0 will be installed
    --> Finished Dependency Resolution
   .....
    
    Transaction Summary
    ================================================================================
    Install  4 Packages

    Total download size: 44 M
    Installed size: 209 M
    Downloading packages:
    --------------------------------------------------------------------------------
    Total                                               23 MB/s |  44 MB  00:01
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction
    Installing : kubectl-1.8.6-0.x86_64                                       1/4
    Installing : kubeadm-1.8.6-0.x86_64                                       2/4
    Installing : 2:docker-1.12.6-68.gitec8512b.el7.centos.x86_64              3/4
    Installing : flannel-0.7.1-2.el7.x86_64                                   4/4
    Verifying  : flannel-0.7.1-2.el7.x86_64                                   1/4
    Verifying  : kubectl-1.8.6-0.x86_64                                       2/4
    Verifying  : kubeadm-1.8.6-0.x86_64                                       3/4
    Verifying  : 2:docker-1.12.6-68.gitec8512b.el7.centos.x86_64              4/4

    Installed:
    docker.x86_64 2:1.12.6-68.gitec8512b.el7.centos  flannel.x86_64 0:0.7.1-2.el7
    kubeadm.x86_64 0:1.8.6-0                         kubectl.x86_64 0:1.8.6-0

Therefore, it looks version get mixed. Is this supposed to be like this?

    $ kubectl get nodes
    NAME                                         STATUS    ROLES     AGE       VERSION
    ip-172-31-1-43.us-west-1.compute.internal    Ready     <none>    12s       v1.9.1
    ip-172-31-4-117.us-west-1.compute.internal   Ready     master    2m        v1.9.1
    ip-172-31-4-61.us-west-1.compute.internal    Ready     <none>    12s       v1.9.1

    $ kubectl version -o yaml
    clientVersion:
    buildDate: 2017-12-21T06:34:11Z
    compiler: gc
    gitCommit: 6260bb08c46c31eea6cb538b34a9ceb3e406689c
    gitTreeState: clean
    gitVersion: v1.8.6
    goVersion: go1.8.3
    major: "1"
    minor: "8"
    platform: linux/amd64
    serverVersion:
    buildDate: 2017-12-21T06:23:29Z
    compiler: gc
    gitCommit: 6260bb08c46c31eea6cb538b34a9ceb3e406689c
    gitTreeState: clean
    gitVersion: v1.8.6
    goVersion: go1.8.3
    major: "1"
    minor: "8"
    platform: linux/amd64

    $ docker ps | grep kube-api
    4df4870548b3        gcr.io/google_containers/kube-apiserver-amd64@sha256:f0658f0c3344abaae3217d6e08612ea8816a0cdeea1fdd48776dd55d07f17d30

    $ sudo journalctl -b CONTAINER_ID=4df4870548b3
    -- Logs begin at Sat 2018-01-06 22:36:55 UTC, end at Sun 2018-01-07 01:40:14 UTC. --
    Jan 07 01:34:50 ip-172-31-4-117.us-west-1.compute.internal dockerd-current[19273]: I0107 01:34:50.922029       1 server.go:114] Version: v1.8.6

    $ kubelet --version
    Kubernetes v1.9.1

**Comment by mbohlool** [comment]
Is this something that introduced with 1.9.1 release? If not, it deserve its own issue. I tried to make sure all packages previously available in the repo (before 1.9.1 release) are the same. If I failed there, we should keep this issue open until it get fixed.

**Comment by oonisim** [comment]
@mbohlool not sure. Last time I installed 1.8.6, it said kubernetes-cni was a requirement to install kubelet (if I am correct), so I insalled it first and did not see any dependency from cni to kubelet. I have no idea who is managing the RPM dependency from cni to kubelet and when it was placed.
