### ISSUE TITLE
Manifest list for kubernetes images

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#57869]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

This issue if for tracking the work related to pushing manifest list for kubernetes images(infra and test)

List of images for which manifest need to be created:

- [x] [pause](https://github.com/kubernetes/kubernetes/tree/master/build/pause) - https://github.com/kubernetes/kubernetes/pull/57723
- [x] kubernetes to use manifest pause image - https://github.com/kubernetes/kubernetes/pull/59056
- [x] dns
- [x] [etcd](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd) - https://github.com/kubernetes/kubernetes/pull/59664
- [x] [debian-hyperkube-base](https://github.com/kubernetes/kubernetes/tree/master/build/debian-hyperkube-base) - https://github.com/kubernetes/kubernetes/pull/59664
- [x] [hyperkube](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube) - https://github.com/kubernetes/kubernetes/pull/59664
- [x] [debian-base](https://github.com/kubernetes/kubernetes/tree/master/build/debian-base) - https://github.com/kubernetes/kubernetes/pull/59664
- [x] [test/images](https://github.com/kubernetes/kubernetes/tree/master/test/images)
- [x] [debian-iptables](https://github.com/kubernetes/kubernetes/tree/master/build/debian-iptables) - https://github.com/kubernetes/kubernetes/pull/59664
- [ ] [dashboard]()
- [x] Manifest images for k8s release images - https://github.com/kubernetes/release/pull/516

**Comment by vielmetti** [comment]
I'd add dashboard to this as well, based off the issue at https://github.com/kubernetes/dashboard/issues/2811

**Comment by luxas** [comment]
@mkumatag can you provide a status update on this issue?
I'd really want this fully working in v1.10... :)

**Comment by mkumatag** [comment]
@luxas I've created one more PR for pushing manifest for few more images, reference - https://github.com/kubernetes/kubernetes/pull/59664

**Comment by vielmetti** [comment]
A problem related to manifests and `containerd` was addressed here: https://github.com/kubernetes/kubernetes/issues/65253

**Comment by vielmetti** [comment]
An update of this issue would be welcomed to track the status of all affected images, since I think at least some of the linked issues have progressed.

**Comment by mkumatag** [comment]
all the k8s core images are now fat manifest, hence closing this task. Will create a separate task for creating manifest for ecosystem images(e.g dashboard, metric-server etc...)

**Comment by ixdy** [comment]
@mkumatag did you have a issue open tracking other images? I noticed today that kube-addon-manager (cluster/addons/addon-manager) is multi-arch but not using a manifest list yet.
