### ISSUE TITLE
how to map load balancer to node

### ISSUE THREAD

**Issue by abhijt-zanak** [kubernetes/kubernetes#57876]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
when I create service having load balancer , it adds all the nodes in to load balancer .

**What you expected to happen**:
I want to add specific node to load balancer. however , it adds all the nodes from cluster.

**How to reproduce it (as minimally and precisely as possible)**:
create 3 nodes, and create service having load balancer

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`):Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by abhijt-zanak** [comment]
@kubernetes/sig-kops
/sig elb

**Comment by abhijt-zanak** [comment]
sig/elb

**Comment by thockin** [comment]
Can you explain why you want to add a specific node?

**Comment by abhijt-zanak** [comment]
I was facing an issue, however, that issue is resolved.
Initially, i thought the issue is related having all the nodes inside ELB, It was not the case.

**Comment by dims** [comment]
/close

sounds like we can close this up.
