### ISSUE TITLE
kubeadm init fail to start etcd container for k8s 1.9 cluster on CentOS 7

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/kubernetes#57870]
We try to install K8s 1.9 cluster without internet using kubeadm in China. So we prepull all the images to local machine.
The firewalld is disabled and stop.

**What happened**:
We run the command:
`sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version=v1.9.0`

Then it hangs on the log below
`This might take a minute or longer if the control plane images have to be pulled.` 

Check the kubelet log, found the log for failing to start etcd container:
`1月 05 11:49:10 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:10.224981   25744 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
1月 05 11:49:10 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:10.551168   25744 kuberuntime_manager.go:514] Container {Name:etcd Image:gcr.io/google_containers/etcd-amd64:3.1.10 Command:[etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379 --data-dir=/var/lib/etcd] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:etcd ReadOnly:false MountPath:/var/lib/etcd SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:2379,Host:127.0.0.1,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:15,TimeoutSeconds:15,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:8,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
1月 05 11:49:10 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:10.551321   25744 kuberuntime_manager.go:758] checking backoff for container "etcd" in pod "etcd-ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal_kube-system(408851a572c13f8177557fdb9151111c)"
1月 05 11:49:10 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:10.551487   25744 kuberuntime_manager.go:768] Back-off 5m0s restarting failed container=etcd pod=etcd-ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal_kube-system(408851a572c13f8177557fdb9151111c)
1月 05 11:49:10 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:10.551527   25744 pod_workers.go:186] Error syncing pod 408851a572c13f8177557fdb9151111c ("etcd-ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal_kube-system(408851a572c13f8177557fdb9151111c)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=etcd pod=etcd-ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal_kube-system(408851a572c13f8177557fdb9151111c)"
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:11.090446   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.135.80.73:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:11.091470   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.135.80.73:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal&limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:11.092383   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://10.135.80.73:6443/api/v1/nodes?fieldSelector=metadata.name%3Dajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal&limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:11.108272   25744 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: I0105 11:49:11.112456   25744 kubelet_node_status.go:82] Attempting to register node ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
1月 05 11:49:11 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:11.112816   25744 kubelet_node_status.go:106] Unable to register node "ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal" with API server: Post https://10.135.80.73:6443/api/v1/nodes: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:12 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:12.091178   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.135.80.73:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:12 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:12.092031   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.135.80.73:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal&limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:12 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:12.093052   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://10.135.80.73:6443/api/v1/nodes?fieldSelector=metadata.name%3Dajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal&limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
1月 05 11:49:13 ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal kubelet[25744]: E0105 11:49:13.092093   25744 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.135.80.73:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.135.80.73:6443: getsockopt: connection refused
`

Then using '**docker logs**' to check the failed etcd container log:
`2018-01-05 03:33:35.127695 I | etcdmain: etcd Version: 3.1.10
2018-01-05 03:33:35.127891 I | etcdmain: Git SHA: 0520cb9
2018-01-05 03:33:35.127897 I | etcdmain: Go Version: go1.8.3
2018-01-05 03:33:35.127900 I | etcdmain: Go OS/Arch: linux/amd64
2018-01-05 03:33:35.127906 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2018-01-05 03:33:35.150880 C | etcdmain: listen tcp 192.157.208.178:2380: bind: cannot assign requested address
`

In my environment, our IP is 10.135.XX.XX, why does etcd try to bind to the weired **192.157.208.178**?

**What you expected to happen**:
The kubeadm should be initialized successfully.

**How to reproduce it (as minimally and precisely as possible)**:
`sudo kubeadm reset`
`sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version v1.9.0
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

kubeadm verison:
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
$ uname -a
Linux ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
$ sudo docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-8:1-4198598-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.029 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.67 GB
 Metadata Space Used: 1.446 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 15.51 GiB
Name: ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
ID: YNTH:ESPS:NHS7:ZTBG:WPF6:6UXW:ZEE5:JXMU:IVXJ:DWJW:64BF:OY5C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

- Others:
The local k8s images are as follow:
$ sudo docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kube-proxy-amd64                v1.9.0              f6f363e6e98e        2 weeks ago         109.1 MB
k8s.gcr.io/kube-proxy-amd64                              v1.9.0              f6f363e6e98e        2 weeks ago         109.1 MB
gcr.io/google_containers/kube-apiserver-amd64            v1.9.0              7bff5aa286d7        2 weeks ago         210.4 MB
k8s.gcr.io/kube-apiserver-amd64                          v1.9.0              7bff5aa286d7        2 weeks ago         210.4 MB
k8s.gcr.io/kube-controller-manager-amd64                 v1.9.0              3bb172f9452c        2 weeks ago         137.8 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.9.0              3bb172f9452c        2 weeks ago         137.8 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.9.0              5ceb21996307        2 weeks ago         62.7 MB
k8s.gcr.io/kube-scheduler-amd64                          v1.9.0              5ceb21996307        2 weeks ago         62.7 MB
quay.io/coreos/flannel                                   v0.9.1-amd64        2b736d06ca4c        7 weeks ago         51.31 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.7              db76ee297b85        10 weeks ago        42.03 MB
k8s.gcr.io/k8s-dns-sidecar-amd64                         1.14.7              db76ee297b85        10 weeks ago        42.03 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.7              5d049a8c4eec        10 weeks ago        50.27 MB
k8s.gcr.io/k8s-dns-kube-dns-amd64                        1.14.7              5d049a8c4eec        10 weeks ago        50.27 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.7              5feec37454f4        10 weeks ago        40.95 MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64                   1.14.7              5feec37454f4        10 weeks ago        40.95 MB
gcr.io/google_containers/etcd-amd64                      3.1.10              1406502a6459        4 months ago        192.7 MB
k8s.gcr.io/etcd-amd64                                    3.1.10              1406502a6459        4 months ago        192.7 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        20 months ago       746.9 kB
k8s.gcr.io/pause-amd64                                   3.0                 99e59f495ffa        20 months ago       746.9 kB

**Comment by Arnavion** [comment]
Essentially the container is running as this:

```sh
$ docker run -it --rm gcr.io/google_containers/etcd-amd64:3.1.10 etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379 --data-dir=/var/lib/etcd

2018-01-06 00:20:55.741853 I | etcdmain: etcd Version: 3.1.10
2018-01-06 00:20:55.741911 I | etcdmain: Git SHA: 0520cb9
2018-01-06 00:20:55.741918 I | etcdmain: Go Version: go1.8.3
2018-01-06 00:20:55.741924 I | etcdmain: Go OS/Arch: linux/amd64
2018-01-06 00:20:55.741931 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2018-01-06 00:20:55.749180 C | etcdmain: listen tcp 10.177.146.133:2380: bind: cannot assign requested address
```

The `:2380` IP corresponds to the `--listen-peer-urls` parameter which kubeadm isn't supplying, so etcd is deriving it manually but with a bogus value.

If I run it with an explicit value it works:

```sh
$ docker run -it --rm gcr.io/google_containers/etcd-amd64:3.1.10 etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379 --data-dir=/var/lib/etcd --listen-peer-urls=http://127.0.0.1:2380

2018-01-06 00:22:39.916377 I | etcdmain: etcd Version: 3.1.10
2018-01-06 00:22:39.916438 I | etcdmain: Git SHA: 0520cb9
2018-01-06 00:22:39.916445 I | etcdmain: Go Version: go1.8.3
2018-01-06 00:22:39.916454 I | etcdmain: Go OS/Arch: linux/amd64
2018-01-06 00:22:39.916461 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2018-01-06 00:22:39.916587 I | embed: listening for peers on http://127.0.0.1:2380
2018-01-06 00:22:39.916639 I | embed: listening for client requests on 127.0.0.1:2379
...
```

I don't know if this is a bug in etcd (deriving a bad IP to listen on) or kubeadm (not providing the `--listen-peer-urls` explicitly) or docker (giving etcd a bad IP).

**Comment by Arnavion** [comment]
Ah, this is the same as https://github.com/coreos/etcd/issues/9070 and https://github.com/kubernetes/kubernetes/issues/57709

I do indeed have a `localhost.<domain in search path>` that resolves to the IP in the error.

@tjliupeng Check if you have one too, and if it has the IP in your error.

**Comment by tjliupeng** [comment]
@Arnavion , could you explain what <domain in search path> exactly is? Could you give an example?

Thanks

**Comment by Arnavion** [comment]
`cat /etc/resolv.conf`

You will probably have a line like `search foo`

If you now do `nslookup localhost.foo` it'll probably resolve to `192.157.208.178`

**Comment by CoolElvis** [comment]
I had same issue. 
It seems a mistake in default config etcd  --listen-peer-urls=http://locahost:12380
I add "--listen-peer-urls=http://127.0.0.1:12380" to /etc/kubernetes/manifests/etcd.yaml 
and Kubernetes master has initialized successfully!

**Comment by Arnavion** [comment]
Yes, that is one of the workarounds listed in the issue I linked. The other is you can add it to the kubeadm init config.

**Comment by tjliupeng** [comment]
Before the first execution of "kubeadm init", there is no file existed in /etc/kubernetes/manifests/. So, you have to wait the failure of "kubeadm init" and then you can change the etcd.yaml, right?

**Comment by tjliupeng** [comment]
@Arnavion @CoolElvis , when I use the command
`sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version v1.9.0 --config ./kubeadm.yaml
`
kubeadm tried to access the google site to download the https://dl.k8s.io/release/stable-1.9.txt, but we are in a local network environment which has limited access to Google.

Then I try to modify the etcd.yaml. But I don't know how to make the file change effect. If this file is existed in the `/etc/kubernetes/manifest/` before `kubeadm init` is executed, `kubeadm init` would be failed or overwrite the etcd.yaml with the argument "--ignore-preflight-errors".

How to achieve that?

**Comment by tjliupeng** [comment]
Ok, if using the `--config` option, all the kubeadm init arguments should be configured in the config file. I move the kubernetesVersion and pod-network-cidr to the config file and the initialization is finished successfully.

**Comment by sunriax** [comment]
The Problem is that there is an Issue so that the Kubernetes Master ETCD can´t start up you have to create a kubernetes config file for kubeadm init and try this #57709 Take a look on @Arnavion Anarvions comment!

**Comment by tjliupeng** [comment]
This issue is resolved.
