### ISSUE TITLE
PVC with a non-empty selector can’t have a PV dynamically provisioned

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#57878]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind feature

**What happened**:
when I create a pvc with selector,cann't dynamically create pv!
![image](https://user-images.githubusercontent.com/25783555/34598811-e474126c-f229-11e7-989c-a6af9ee19c40.png)
![image](https://user-images.githubusercontent.com/25783555/34598826-f481424c-f229-11e7-916b-ba090bc5a2cf.png)

![image](https://user-images.githubusercontent.com/25783555/34598758-9d41466c-f229-11e7-9f72-f2eca74d7df0.png)

**What you expected to happen**:
can dynamically create pv with the same selector of pvc
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.6.9
- Cloud provider or hardware configuration:openstack 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mlmhl** [comment]
Should we support this feature(support both dynamic provision and label selector at the same time)? @jsafrane @saad-ali @jingxu97 

A possible use scenario maybe that:

1. User sets `StorageClass.ReclaimPolicy` to `Recycle`, and creates a PVC with specific  `StorageClassName` and `Selector`. Then pv-controller dynamically creates a PV with these labels.
2. User is done with their volume and deletes the PVC objects from the API, the PV object becomes `Available`.
3. Some time later, user creates a new PVC and sets the same `Selector` to reuse the PV before.

I'm curious about how much this demand can be.

**Comment by jianglingxia** [comment]
yeah,if use dynamically create pv,when delete the pv,maybe happened the scenario:
before
pv1 binding pvc1; pv2 binding pvc2;
later
pv1 binding pvc2;pv2 binding pvc1;but user maybe want the result are:pv1 binding pvc1; pv2 binding pvc2; the same with before and data consistent ,thanks! @mlmhl

**Comment by wenlxie** [comment]
@mlmhl I think this feature had supported now. 
 `pv_controller.go`->`syncUnboundClaim` -> `volume, err := ctrl.volumes.findBestMatchForClaim(claim)`

@jianglingxia Can  pvc1 and pvc2 use different labels?

**Comment by jianglingxia** [comment]
thanks @wenlxie but now the issue about dynamically provisioned,in doc1.9:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
![image](https://user-images.githubusercontent.com/25783555/34699924-1a86704a-f51b-11e7-852b-5f20b5ef898f.png)
yes,pvc1 and pvc2 use different labels!
in the Following design-proposals why the current do not support the feature?thanks all
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-provisioning.md
