### ISSUE TITLE
Extend the current Kubernetes WebUI

### ISSUE THREAD

**Issue by preillyme** [kubernetes/kubernetes#5789]
We've extended the current Kubernetes WebUI and are working to merge it back into the mainline project.

**Comment by preillyme** [comment]
We have a p0 for setting the defaults for out of the box consumption.
Currently, we rely on defaults set in ```www/master/config/development.json```.
These defaults need to be set correctly in releases, such that the user can run the application out of the box.

**Comment by bcbroussard** [comment]
Thanks @preillyme. Although https://github.com/GoogleCloudPlatform/kubernetes/pull/5790 is labeled a WIP, the new web UI does currently work with some default out of box settings from `development.json`. Only a few little cleanup tasks remain. The UI comes with two example dashboards:

The **Dashboard** view developed by Kismatic shows all of the same data as the Kubernetes CLI, along with a bar gauge graph of node health based on cAdvisor data. 

The **Graph** view developed by @jackgr and his team at Google is an interactive force directed graph visualization of a Kubernetes cluster.

We would love to hear thoughts on this initial version and where to take the web UI in the future.

**Comment by roberthbailey** [comment]
@preillyme thanks for the great work you've done so far working on a UI.

Have you read through [faster reviews] (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/faster_reviews.md) yet? The PR you sent was both labeled a work in progress and also contains 250+ commits and 20k lines of code. Would it be possible to break it up into some smaller sized chunks so that it would be possible for us to review?

**Comment by preillyme** [comment]
@roberthbailey: Okay, I've moved the two base components out to separate repositories for now: https://github.com/kubernetes-ui/dashboard and https://github.com/kubernetes-ui/graph respectively.

**Comment by preillyme** [comment]
The main repository for the chrome only is available at: https://github.com/kubernetes-ui/kubernetes-ui

**Comment by bgrant0607** [comment]
Superseded by kubernetes/dashboard.
