### ISSUE TITLE
Failed to start kubelet.service: Unit not found.

### ISSUE THREAD

**Issue by bidianqing** [kubernetes/kubernetes#57904]
![image](https://user-images.githubusercontent.com/12196280/34620601-f47b3512-f280-11e7-872c-026dad624ffe.png)
Please tell me what to do?

**Comment by dims** [comment]
did you try doing a `systemctl daemon-reload` and then starting kubelet?

if that does not work, try the suggestions made under the heading `Locate this type of problem, often used in the order` at:
https://www.codeday.top/2017/06/22/29521.html

/close

**Comment by Proteles** [comment]
https://www.codeday.top/2017/06/22/29521.html link broken

please provide actual content for solution.

**Comment by bhdrk** [comment]
@dims 's answer `systemctl daemon-reload` solved the problem.

**Comment by Prateeknandle** [comment]
hi,  I'm getting the same issue but it's not getting resolved, when I run `systemctl start kubelet.service` I got `Failed to start kubelet.service: Unit kubelet.service not found`


> did you try doing a `systemctl daemon-reload` and then starting kubelet?
> 
> if that does not work, try the suggestions made under the heading `Locate this type of problem, often used in the order` at: https://www.codeday.top/2017/06/22/29521.html
> 
> /close

**Comment by Kumar2106** [comment]
@bhdrk it is not resolving the issue.

**Comment by obdif** [comment]
@Kumar2106 please do you later find solution to the kubelet.service not starting

please help, I've been facing the same error for weeks now. please help 🙏🏽🙏🏽

**Comment by SlypetsArtem** [comment]
Try replacing the local Kubernetes cluster. For example, this is a minikube, use the command: minikube start.
This error has disappeared: kubelet.service could not be started: kubelet.service module was not found.
