### ISSUE TITLE
Turn off per-cpu stats in kubelet cAdvisor

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubernetes#57905]
/kind feature
/sig node

Kubelet does not use per-CPU stats, and https://github.com/google/cadvisor/pull/1852 will allow us to disable them.

My motivation for wanting this is to cut the overhead of collecting and storing CPU usage metrics - with 16-core machines I get 16x as many timeseries as I need.

**Comment by dashpole** [comment]
Those values are set [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L111) for the kubelet.

**Comment by dashpole** [comment]
this is fixed by https://github.com/kubernetes/kubernetes/pull/60106
