### ISSUE TITLE
kubectl create secret tls reads key and cert twice, which breaks with bash process substitution

### ISSUE THREAD

**Issue by groner** [kubernetes/kubernetes#57909]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```
:; kubectl create secret tls tls-secret --cert <( ... ) --key <( ... ) -o yaml
apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  creationTimestamp: 2018-01-05T19:30:39Z
  name: tls-jenkins
  namespace: default
  resourceVersion: "12677128"
  selfLink: /api/v1/namespaces/default/secrets/tls-secret
  uid: e95bfab7-f24e-11e7-bf77-0a695a1f84f0
type: kubernetes.io/tls
```

The supplied cert and key are replaced with empty strings.

**What you expected to happen**:

The supplied cert and key are in the secret.

**How to reproduce it (as minimally and precisely as possible)**:

This example uses openssl to generate a key and self signed cert, but any key/cert pair should suffice if openssl isn't available.

```
:; openssl req -x509  -new -batch -nodes -keyout demokey.pem -out democert.pem
:; kubectl create secret tls tls-secret \
    --cert <( cat democert.pem ) \
    --key <( cat demokey.pem ) \
    -o yaml
```

The process substitution in this example is trivial and could be replaced with a direct reference to the file paths.  This is simplified for demonstration only.  In practice I want to use process substitution to pull the cert/key from other sources without using temporary files.

**Anything else we need to know?**:

`strace` reveals the cert and key files being read twice.  Of course this only works once when using a pipe/socketpair.  I suspect the [`validate()` function](https://github.com/kubernetes/kubernetes/blob/d0c4c5647f6ae683e55b5562e37fef7b7c54f72d/pkg/kubectl/secret_for_tls.go#L136) is responsible for the first read.

```
[pid 17208] openat(AT_FDCWD, "/dev/fd/63", O_RDONLY|O_CLOEXEC) = 3
[pid 17208] epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3001872240, u64=140401187811184}}) = 0
[pid 17208] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 17208] fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
[pid 17208] fstat(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid 17208] read(3, "-----BEGIN CERTIFICATE-----\nMIID"..., 512) = 512
[pid 17208] read(3, "oXehxtfTG+9CEX9goAZ6pGzEU8ZResSp"..., 1024) = 717
[pid 17208] read(3, "", 2355)           = 0
[pid 17208] epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc4207a748c) = 0
[pid 17208] close(3)                    = 0
[pid 17208] openat(AT_FDCWD, "/dev/fd/62", O_RDONLY|O_CLOEXEC) = 3
[pid 17208] epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3001872240, u64=140401187811184}}) = 0
[pid 17208] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 17208] fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
[pid 17208] fstat(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid 17208] read(3, "-----BEGIN PRIVATE KEY-----\nMIIE"..., 512) = 512
[pid 17208] read(3, "nyQVEZzfIcc9eA6WkAP5b0YUdBUX8jLI"..., 1024) = 1024
[pid 17208] read(3, "s+VZoo5tH8hWzNhSipKJhjxshG1K0KuI"..., 2048) = 168
[pid 17208] read(3, "", 1880)           = 0
[pid 17208] epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc4207a748c) = 0
[pid 17208] close(3)                    = 0
[pid 17208] openat(AT_FDCWD, "/dev/fd/63", O_RDONLY|O_CLOEXEC) = 3
[pid 17208] epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3001872240, u64=140401187811184}}) = 0
[pid 17208] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 17208] fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
[pid 17208] fstat(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid 17208] read(3, "", 512)            = 0
[pid 17208] epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc4207a7634) = 0
[pid 17208] close(3)                    = 0
[pid 17208] openat(AT_FDCWD, "/dev/fd/62", O_RDONLY|O_CLOEXEC) = 3
[pid 17208] epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3001872240, u64=140401187811184}}) = 0
[pid 17208] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 17208] fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
[pid 17208] fstat(3, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
[pid 17208] read(3, "", 512)            = 0
[pid 17208] epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc4207a7634) = 0
[pid 17208] close(3)                    = 0
```

This looks similar to #56372, but the proposed fix appears to be specific to the kubeconfig management code.

**Environment**:
- Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools:
- Others:

**Comment by kfox1111** [comment]
I just hit this too.

**Comment by thorbenvh8** [comment]
Directly referencing the file works for me.
```cmd
# create a key and cert
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
# transform key to rsa
cat key.pem | openssl rsa > tls.crt
# generate secret
kubectl create secret tls tls-secret --cert cert.pem --key tls.crt --dry-run -o yaml
```

> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wknapik** [comment]
Yes! Don't force me to store secrets on disk, when there's no reason to.

**Comment by zjj2wry** [comment]
/unassign
failed while add more e2e test. Who is interested in continuing to repair it?

**Comment by abstrctn** [comment]
As a workaround, the `generic` secret type can be used with process substitution, although (naturally) you won't get the validation built into the `tls` secret type.

```bash
kubectl create secret generic NAME --from-file=tls.key=<( ... ) --from-file=tls.crt=<( ... )
```

If you want to keep the `type` set to be tls, you can concatenate the templated output from above with a `type: kubernetes.io/tls` line:

```bash
kubectl create secret generic NAME \
  --from-file=tls.key=<( ... ) --from-file=tls.crt=<( ... ) -oyaml --dry-run | \
  cat <(cat -) <(echo "type: kubernetes.io/tls") | \
  kubectl create -f -
```

**Comment by liggitt** [comment]
fix is open in https://github.com/kubernetes/kubernetes/pull/67713
