### ISSUE TITLE
Remove non-standard, undocumented, unused, or deprecated github labels

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#57911]
This, of course, begs the question of "where are the github labels documented" because they're not, really (#34255)

We have a "standard" subset propagated across all repos at https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml.  We could start by documenting those.  [This PR](https://github.com/kubernetes/test-infra/pull/2706 was where I tried to get the standard subset ) is the best place I could find for what/why we picked the standard subset that we did.  [This kubernetes-dev thread](https://groups.google.com/d/msg/kubernetes-dev/0rTJ6wjcitg/VNH8fKArAAAJ) was the second best place.

I suspect there are more labels than just the above "standard" labels that should be kept here.

---

For now, I'm using this as a scratchpad for labels we should just straight up remove from this repo.  At kindest, I could drop comments of (open) issues that had these issues prior to removal.

Miscellaneous labels to remove:

- https://github.com/kubernetes/kubernetes/labels/beta-blocker
- https://github.com/kubernetes/kubernetes/labels/non-release-blocker
- https://github.com/kubernetes/kubernetes/labels/release-blocker
- https://github.com/kubernetes/kubernetes/labels/requires-release-czar-attention
- https://github.com/kubernetes/kubernetes/labels/team%2Ftest-infra
- https://github.com/kubernetes/kubernetes/labels/stale

Anything that has (deprecated - do not use) in its name:

- https://github.com/kubernetes/kubernetes/labels/flake-has-meta%20%28deprecated%20-%20do%20not%20use%29
- https://github.com/kubernetes/kubernetes/labels/requires-release-czar-attention%20%28deprecated%20-%20do%20not%20use%29
- https://github.com/kubernetes/kubernetes/labels/sig%2Ffederation%20%28deprecated%20-%20do%20not%20use%29
  - also https://github.com/kubernetes/kubernetes/labels/sig%2Ffederation
  - (ensure these issues have sig/multicluster first)
- https://github.com/kubernetes/kubernetes/labels/team%2Fux%20%28deprecated%20-%20do%20not%20use%29

Labels that we haven't used in quite some time:

- https://github.com/kubernetes/kubernetes/labels/cla%3A%20no
- https://github.com/kubernetes/kubernetes/labels/cla%3A%20yes
- https://github.com/kubernetes/kubernetes/labels/needs-ok-to-merge
- https://github.com/kubernetes/kubernetes/labels/ok-to-merge
- https://github.com/kubernetes/kubernetes/labels/do-not-merge
  - replace these with a do-not-merge/hold label

Old priority labels can be removed:

- https://github.com/kubernetes/kubernetes/labels/priority%2FP0
- https://github.com/kubernetes/kubernetes/labels/priority%2FP1
- https://github.com/kubernetes/kubernetes/labels/priority%2FP2
- https://github.com/kubernetes/kubernetes/labels/priority%2FP3

/priority important-soon
/kind cleanup
/sig contributor-experience
/assign

**Comment by spiffxp** [comment]
I did a pass through kubernetes/test-infra/label_sync/labels.yaml recently and will use automation to remove a few of the org-wide labels.  Will open a kubernetes/community issue for that.

That said, I think it's time to remove these labels on this repo specifically.  Next step: e-mail out to kubernetes-dev

**Comment by cblecker** [comment]
Two comments:
- the sig-federation -> multicluster should be handled by label_sync as it's org wide
- do-not-merge is a label that was previously added by someone with write access, while hold is something that anyone (including the PR author) can remove. this isn't a direct translation, and I'd recommend not removing this label at this time.

The rest look fine to me. Although, I'd really like to get a repo-specific label management tool in place.

**Comment by jberkus** [comment]
Aside from @cblecker's comments, LGTM.

**Comment by spiffxp** [comment]
>the sig-federation -> multicluster should be handled by label_sync as it's org wide

That was handled by https://github.com/kubernetes/test-infra/pull/6167, there was still detritus left over at some point, but it seems to have been handled at this point

>do-not-merge is a label that was previously added by someone with write access, while hold is something that anyone (including the PR author) can remove. this isn't a direct translation, and I'd recommend not removing this label at this time.

Fair point, I'm wondering how many of these still need the label applied such that nobody but people with repo write access can remove, or whether /hold and asking people to behave would be enough.  I'll do the rest first and revisit this.  At the very least I think it'd be nice to migrate it to prefixed, eg do-not-merge -> do-not-merge/manually-applied or something

**Comment by spiffxp** [comment]
(Editing this as I go, will remove when done)

----

Miscellaneous labels to remove:

- ~https://github.com/kubernetes/kubernetes/labels/beta-blocker~
  - no open issues/prs, removed
- ~https://github.com/kubernetes/kubernetes/labels/non-release-blocker~
  - none of the issues that use it are in 1.10, removed
- https://github.com/kubernetes/kubernetes/labels/release-blocker
  - used by https://github.com/kubernetes/kubernetes/pull/61127 so holding off
- ~https://github.com/kubernetes/kubernetes/labels/requires-release-czar-attention~
  - no open issues/prs, removed
- ~https://github.com/kubernetes/kubernetes/labels/team%2Ftest-infra~
  - no open issues/prs, removed
- ~https://github.com/kubernetes/kubernetes/labels/stale~
  - has already been migrated to lifecycle/stale via automation

Anything that has (deprecated - do not use) in its name:

- ~https://github.com/kubernetes/kubernetes/labels/flake-has-meta%20%28deprecated%20-%20do%20not%20use%29flake~
  - no open issues/prs, removed
- ~https://github.com/kubernetes/kubernetes/labels/requires-release-czar-attention%20%28deprecated%20-%20do%20not%20use%29~
  - removed
- https://github.com/kubernetes/kubernetes/labels/sig%2Ffederation%20%28deprecated%20-%20do%20not%20use%29
  - also https://github.com/kubernetes/kubernetes/labels/sig%2Ffederation
  - (ensure these issues have sig/multicluster first)
- https://github.com/kubernetes/kubernetes/labels/team%2Fux%20%28deprecated%20-%20do%20not%20use%29

Labels that we haven't used in quite some time:

- https://github.com/kubernetes/kubernetes/labels/cla%3A%20no
- https://github.com/kubernetes/kubernetes/labels/cla%3A%20yes
- https://github.com/kubernetes/kubernetes/labels/needs-ok-to-merge
- https://github.com/kubernetes/kubernetes/labels/ok-to-merge
- https://github.com/kubernetes/kubernetes/labels/do-not-merge
  - replace these with a do-not-merge/hold label

Old priority labels can be removed:

- https://github.com/kubernetes/kubernetes/labels/priority%2FP0
- https://github.com/kubernetes/kubernetes/labels/priority%2FP1
- https://github.com/kubernetes/kubernetes/labels/priority%2FP2
- https://github.com/kubernetes/kubernetes/labels/priority%2FP3

>https://github.com/kubernetes/kubernetes/labels/beta-blocker

removed 

>https://github.com/kubernetes/kubernetes/labels/non-release-blocker

none of the issues that use it are in the current release, removed

>https://github.com/kubernetes/kubernetes/labels/release-blocker

currently used by https://github.com/kubernetes/kubernetes/pull/61127 so holding off

>https://github.com/kubernetes/kubernetes/labels/requires-release-czar-attention

removed

https://github.com/kubernetes/kubernetes/labels/team%2Ftest-infra
https://github.com/kubernetes/kubernetes/labels/stale

**Comment by spiffxp** [comment]
Labels have been removed. We went from 220 to 178 for this repo.  There are 87 in the labels.yaml file used to propagate labels across repos.  Where are all the differences coming from, and what could we do next?

```
$ grep name labels.yaml | sed -e 's/- name: //g' | cut -d/ -f1 | uniq -c | sort -rg
  76 area
  30 sig
  15 kind
   6 size
   6 priority
   6 do-not-merge
   4 queue
   4 milestone
   4 close
   3 status
   3 lifecycle
   2 committee
   1 retest-not-required-docs-only
   1 retest-not-required
   1 release-note-none
   1 release-note-label-needed
   1 release-note-action-required
   1 release-note
   1 release-blocker
   1 needs-sig
   1 needs-rebase
   1 needs-ok-to-test
   1 lgtm
   1 help wanted
   1 cherrypick-candidate
   1 cherrypick-approved
   1 approved
   1 'cncf-cla: yes'
   1 'cncf-cla: no'
   1 'cla: human-approved'
```
- Most of the non-standard labels are `area/` or `kind/` labels. Personally I think that's too much choice, but it would be interesting to see what the data says.
- The `status/` and `milestone/` labels aren't "standard", but then, this is the only repo that uses them right now
- The `do-not-merge` label I would like to turn into a prefixed label, ie: `do-not-merge/manual`... that can be done separately

Will open other issues for followup
/close
