### ISSUE TITLE
`kubectl apply --prune` with ability to ignore a namespace

### ISSUE THREAD

**Issue by RochesterinNYC** [kubernetes/kubernetes#57916]
/kind feature

The use case that I was trying to get `kubectl apply --prune` to accommodate was to have it act as a sort of syncing tool between the targeted cluster and a git monorepo containing all resource manifests that we want deployed in the cluster (this monorepo would essentially represent "here are the ONLY resources we want deployed to a cluster in namespaces other than the `kube-system` one). In the `kube-system` namespace (this is on GKE), there are resources that we do not really manage and hence do not want to touch or delete. I was wondering if it's currently possible or would be possible to run some variation of `kubectl apply --prune` to achieve the following:

- Ensure all resources in the git monorepo are deployed to the cluster
- Ensure that all resources that were running in the cluster but not represented in the git monorepo are deleted
- Ignore pruning resources in a specific namespace (`kube-system`), but do not ignore applying resources to that namespace

I understand there's a prune whitelist, but it seems that it's not for namespaces or the like but rather for resource types ?

Things we've tried:
- Applying a metadata label to all resources in the monorepo (ex. `status=deployed`) and running `kubectl apply -R -f . --prune -l status=deployed`. This will avoid the `kube-system` namespace resources (because they do not have the `status=deployed` label) and will delete running resources 
from the cluster once they have their `status` label changed in the resource manifest. However, deleting a resource manifest file and running that apply command will not delete the the running resource correlated with the deleted resource manifest file.
- `kubectl apply -R -f . --prune --all` will prune resources in the `kube-system` namespace

**Comment by RochesterinNYC** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by RochesterinNYC** [comment]
The use case about wanting `--prune` to prune a resource correlated with a deleted resource manifest file seems related to https://github.com/kubernetes/kubernetes/issues/40635

**Comment by pascalgn** [comment]
@RochesterinNYC We are also storing our resources in git, but we're using [autoapply](https://github.com/autoapply/autoapply) with a custom script _per namespace_, which works fine.

However, I had a look at your issue and could not reproduce your first point:

```yaml
# ls test/
configmap.yaml  nginx.yaml
# cat test/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  labels:
    status: deployed
data:
  hello: "world"
# cat test/nginx.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    status: deployed
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```

Apply works fine:
```
# kubectl apply --prune -l status=deployed -R -f test/
configmap/test-config created
pod/nginx created
# kubectl apply --prune -l status=deployed -R -f test/
configmap/test-config unchanged
pod/nginx unchanged
```

And so does delete:
```
# rm test/configmap.yaml 
# kubectl apply --prune -l status=deployed -R -f test/
pod/nginx unchanged
configmap/test-config pruned
# cp backup/configmap.yaml test/
# rm test/nginx.yaml 
# kubectl apply --prune -l status=deployed -R -f test/
configmap/test-config created
pod/nginx pruned
# rm test/*
# kubectl apply --prune -l status=deployed -R -f test/
error: error reading [test/]: recognized file extensions are [.json .yaml .yml]
# touch test/empty.yaml
# kubectl apply --prune -l status=deployed -R -f test/
error: no objects passed to apply
```
(those last errors being due to #40653, as you already pointed out)

Maybe it was a bug in an earlier version? I was using 1.11/1.12 for the test:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
