### ISSUE TITLE
limit/continue paging of fakeclient doesn't work

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#57927]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

Fake client doesn't have a support for paging when invoking `List`.

[https://github.com/yue9944882/kubernetes/blob/3837a7402a9f58acc1f911bfe6b418d39ed056e2/staging/src/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go#L348](https://github.com/yue9944882/kubernetes/blob/3837a7402a9f58acc1f911bfe6b418d39ed056e2/staging/src/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go#L348)

`Limit` and `Continue` fields in ListOption is simply ignored, so the paging won't be working. Supporting paging will make it easy to test [pager](https://github.com/yue9944882/kubernetes/blob/3837a7402a9f58acc1f911bfe6b418d39ed056e2/staging/src/k8s.io/client-go/tools/pager/pager.go) related utilities.

**What you expected to happen**:

Paging on fake client. It would be better with multi-thread support.

**Anything else we need to know?**:

Supporting multi-thread paging needs the `List` know if itself is invoked from a different context / go-routine at first. Things can be rather more complicated when we try to judge contexts from the fake client. And this also applies to all the other functionalities of fake client needs multi-thread support.

**Comment by liggitt** [comment]
This seems close to the limit of what the fake client should support.

**Comment by yue9944882** [comment]
@liggitt 

How about explicitly retrieve a new "context" from fake client like:

```go
import "k8s.io/client-go/kubernetes"
var clientset kubernete.Interface = fake.NewSimpleClientset(..).NewContext()
```
or wrap the default fake clientset by a decorator:
```go
defaultFakeClientset := fake.NewSimpleClientset(..)
var clientset kubernete.Interface = ContextedClientset(defaultFakeClient)
```

IDK if it is really necessary but providing these utilities for testing can make it easier for try out paging functionalities locally.

**Comment by liggitt** [comment]
> providing these utilities for testing can make it easier for try out paging functionalities locally

possibly, though that behavior is complex and stateful enough that I’d really rather just test it against a real rest handler. At some point, so much code is required to fake the behavior it becomes likely the fake code has bugs. I have similar feelings about faking watch event delivery in response to fake client updates (https://github.com/kubernetes/kubernetes/pull/57504)

**Comment by yue9944882** [comment]
@liggitt 
> I have similar feelings about faking watch event delivery in response to fake client updates (#57504)

Testing watch against a real server, can make it even more complex in my case. Because generally each time for testing ( or CI building), we will only provision only one server like minikube for a build which is also stateful. Especially testing in parallel will make server's behavior hard to track because read/write/watch may happen at a random order which may potentially "make some noise" to the watch, asserting in test can be painful. With a single-test-scoped fakeclient may reduce the overhead of testing not only a `Watch` call, and also some user-customized utilities coupled with `Watch`. As #54075 reported.

>  I’d really rather just test it against a real rest handler.

Actually for this in my case, I did have the test against minikube, because no other choice is available. And it's okay for now, but still I'm not sure if anyone like me is looking forward to this feature.

**Comment by lavalamp** [comment]
cc @yliaog
