### ISSUE TITLE
Create custom resource type in non-exist namespace succeeded

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kubernetes#57933]
/kind bug
I read the issue https://github.com/kubernetes/kubernetes/issues/23713, seems we have NamespaceLifecycle admission control to reject the creation of k8s defined resource while I am using https://github.com/kubernetes-incubator/apiserver-builder to create several custom defined resource by adding a aggregated apiserver. 
I wonder if main apiserver's NamespaceLifecycle admission control can handler self defined resources?

**What happened**:
Create the custom defined resource with non-exist namespace succeeded
**What you expected to happen**:
deny the  creation of custom defined resource with none-exist namespace.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
none
**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:

**Comment by WIZARD-CXY** [comment]
@derekwaynecarr ptal

**Comment by hzxuzhonghu** [comment]
I think NamespaceLifecycle admission controller not run on  your apiserver.
Is your traffic flows like below?
client---->kube-aggregator----->self-apiserver

**Comment by WIZARD-CXY** [comment]
@hzxuzhonghu the flow is more look like this
client -> main k8s apiserver -> addon apiserver -> self-defined apiserver

**Comment by WIZARD-CXY** [comment]
I look through the code and I think it is not supported in main apiserver for now and I filed a new issue in https://github.com/kubernetes-incubator/apiserver-builder/issues/206

**Comment by WIZARD-CXY** [comment]
I'd like to use main apiserver to delegate some admission-control for the addon apiserver.

**Comment by hzxuzhonghu** [comment]
>I'd like to use main apiserver to delegate some admission-control for the addon apiserver.

Seems not possible, kube-aggregator has no admission control, its a proxy only.

**Comment by WIZARD-CXY** [comment]
> Seems not possible, kube-aggregator has no admission control, its a proxy only.
If not possible now, we can add it. I think it is reasonable to  use main apiserver to delegate some admission-control for the addon apiserver.

**Comment by hzxuzhonghu** [comment]
Already a issue #56627, and a pr #56660

**Comment by liggitt** [comment]
> If not possible now, we can add it. I think it is reasonable to use main apiserver to delegate some admission-control for the addon apiserver.

Not really. Doing so requires decoding the request body by the main apiserver, which doesn't know about your API types. You also have to consider the case where a request is made directly to your api server. It should have a coherent authentication/authorization/admission setup, otherwise a direct request could bypass namespace lifecycle checks

**Comment by liggitt** [comment]
Closing as duplicate of https://github.com/kubernetes/kubernetes/issues/56627

**Comment by WIZARD-CXY** [comment]
@hzxuzhonghu #56660 just what I want to add too, cool!
