### ISSUE TITLE
Kubectl apply on PVC loses storageClassName

### ISSUE THREAD

**Issue by boeboe** [kubernetes/kubernetes#57946]
When I try to create a persistentvolumeclaim using **kubectl apply**, the **spec.storageClassName** field is dropped. You need to use kubectl create instead.

Is this expected behaviour? I am using PVC within an OpensShift template, which I process in order to do updates on my namespace (hence using the apply iso create sub-command of kubectl/oc).

    oc process -f template.yaml | apply -f - -n test-namespace

On our kubernetes cluster we are using the apply subcommand to support updates from our CI/CD pipeline.

Reproduction traces:

    # cat pvc.yaml
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "test-pvc"
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1Gi"
      storageClassName: heketi
      
    # kubectl apply -f pvc.yaml
    persistentvolumeclaim "test-pvc" created

    # kubectl get pvc test-pvc -o yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: '{"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata":{"name":"test-pvc","creationTimestamp":null},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}},"status":{}}'
      creationTimestamp: 2018-01-07T19:31:26Z
      name: test-pvc
      namespace: es6-acc-log-fluentd
      resourceVersion: "95120636"
      selfLink: /api/v1/namespaces/test-namespace/persistentvolumeclaims/test-pvc
      uid: 59f859cc-f3e1-11e7-819a-005056830d0a
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending

    # kubectl describe pvc test-pvc
      Name:          test-pvc
      Namespace:     test-namespace
      StorageClass:
      Status:        Pending
      Volume:
      Labels:        <none>
      Annotations:   kubectl.kubernetes.io/last-applied-configuration={"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata":{"name":"test-pvc","creationTimestamp":null},"spec":{"accessModes":["ReadWriteOnce"],"reso...
      Finalizers:    []
      Capacity:
      Access Modes:
      Events:
        Type    Reason         Age               From                         Message
        ----    ------         ----              ----                         -------
        Normal  FailedBinding  9s (x12 over 2m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

**Comment by liggitt** [comment]
What version of kubectl are you using?

**Comment by boeboe** [comment]
@liggitt 

    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T19:58:48Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by stewart-yu** [comment]
occur also in `master` branch @liggitt
