### ISSUE TITLE
kubelet stopped working unexpectedly

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/kubernetes#57955]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
01:02:50 3 Jan, 2018, One of my workers entered NotReady status unexpectedly

The kubelet log of the worker at that time:
```
$ systemctl status kubelet
* kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-01-01 18:36:42 CST; 1 day 17h ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 29130 ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin (code=exited, status=0/SUCCESS)
  Process: 29117 ExecStartPre=/usr/bin/mkdir -p /etc/cni/net.d (code=exited, status=0/SUCCESS)
 Main PID: 29137 (kubelet)
    Tasks: 72
   Memory: 253.5M
      CPU: 5h 41min 45.736s
   CGroup: /system.slice/kubelet.service
           |-29137 /kubelet --address=0.0.0.0 --allow-privileged=true --cluster-dns=192.168.192.10 --cluster-domain=cluster.local --cloud-provider= --port=10250 --lock-file=/var/run/lock/kubelet.lock --exit-on-lock-contention --node-labels=worker=true --pod-manifest-path=/etc/kubernetes/manifests --kubeconfig=/etc/kubernetes/kubeconfig.yaml --require-kubeconfig=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --logtostderr=true
           `-29355 journalctl -k -f

Jan 03 01:00:30 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:00:30.988485   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:00:41 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:00:41.094537   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:00:51 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:00:51.193735   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:01 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:01.314097   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:11 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:11.406249   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:21 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:21.510539   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:31 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:31.607629   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:41 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:41.707686   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:01:51 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:01:51.806283   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Jan 03 01:02:01 ae01.pek.prod.com kubelet-wrapper[29137]: W0102 09:02:01.905585   29137 helpers.go:793] eviction manager: no observation found for eviction signal allocatableNodeFs.available
```

Then, kubelet logs stoped here until I found it entering NotReady status several hours later.
 
The kube-controller-manager logs at that time:
```
I0103 01:02:50.475290       1 controller_utils.go:285] Recording status change NodeNotReady event message for node ae01.pek.prod.com
I0103 01:02:50.475329       1 controller_utils.go:203] Update ready status of pods on node [ae01.pek.prod.com]
I0103 01:02:50.475405       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ae01.pek.prod.com", UID:"f739dd60-49d7-11e7-b36b-1866dae7138c", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node ae01.pek.prod.com status is now: NodeNotReady
I0103 01:02:50.582487       1 controller_utils.go:220] Updating ready status of pod ceph-admin to false
I0103 01:02:50.784024       1 controller_utils.go:220] Updating ready status of pod ceph-mon-xtc5j to false
I0103 01:02:50.993792       1 controller_utils.go:220] Updating ready status of pod ceph-osdaa-fgpt6 to false
I0103 01:02:51.152119       1 controller_utils.go:220] Updating ready status of pod ceph-osdab-6bw67 to false
I0103 01:02:51.319113       1 controller_utils.go:220] Updating ready status of pod ceph-osdac-0h3nj to false
I0103 01:02:51.502803       1 controller_utils.go:220] Updating ready status of pod ceph-osdad-p5cl7 to false
I0103 01:02:59.024278       1 controller_utils.go:220] Updating ready status of pod kube-proxy-ae01.pek.prod.com to false
I0103 01:02:59.299461       1 controller_utils.go:220] Updating ready status of pod node-exporter-9tww1 to false
W0103 01:05:01.654148       1 reflector.go:323] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:72: watch of *v1beta1.ThirdPartyResource ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [711850627/711848663]) [711851626]
I0103 01:07:14.592488       1 nodecontroller.go:644] Node is unresponsive. Adding Pods on Node ae01.pek.prod.com to eviction queues: 2018-01-03 01:07:14.592477202 +0800 CST is later than 2018-01-03 01:02:50.475279459 +0800 CST + 4m20s
I0103 01:07:14.759150       1 controller_utils.go:274] Recording Deleting all Pods from Node ae01.pek.prod.com. event message for node ae01.pek.prod.com
I0103 01:07:14.759246       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ae01.pek.prod.com", UID:"f739dd60-49d7-11e7-b36b-1866dae7138c", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingAllPods' Node ae01.pek.prod.com event: Deleting all Pods from Node ae01.pek.prod.com.
I0103 01:07:15.047285       1 controller_utils.go:89] Starting deletion of pod ceph-sas/ceph-admin
I0103 01:07:15.047426       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ceph-sas", Name:"ceph-admin", UID:"273810cc-c558-11e7-987d-1866dae7138c", APIVersion:"v1", ResourceVersion:"711850606", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod ceph-admin from Node ae01.pek.prod.com
I0103 01:07:23.419960       1 controller_utils.go:89] Starting deletion of pod default/kube-proxy-ae01.pek.prod.com
I0103 01:07:23.420062       1 event.go:218] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-proxy-ae01.pek.prod.com", UID:"e302d011-d4da-11e7-a89d-1866dae7138c", APIVersion:"v1", ResourceVersion:"711850741", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod kube-proxy-ae01.pek.prod.com from Node ae01.pek.prod.ucarinc.com
I0103 01:07:24.104385       1 nodecontroller.go:431] Pods awaiting deletion due to NodeController eviction
```

While at that time, access 10250 and 10255 port got no response:
```
# wget https://localhost:10250/metrics --no-check-certificate
--2018-01-03 10:53:36--  https://localhost:10250/metrics
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:10250... connected.
Unable to establish SSL connection.

# wget http://localhost:10255/healthz
--2018-01-03 15:10:09--  http://localhost:10255/healthz
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:10255... connected.
HTTP request sent, awaiting response... ^C
```

And strace the kubelet process, it just hung there:
```
# strace -p 29137 
Process 29137 attached
futex(0x92873b0, FUTEX_WAIT, 0, NULL^CProcess 29137 detached
 <detached ...>
```

**What you expected to happen**:
kubelet doesn't hang at no reason

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
I have another node entered NotReady status too, all phenomenon is almost the same, except the kubelet log:
```
$ systemctl status kubelet
* kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-11-29 16:04:21 CST; 1 months 4 days ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 22966 (kubelet)
    Tasks: 75
   Memory: 364.2M
      CPU: 1w 3h 13min 2.144s
   CGroup: /system.slice/kubelet.service
           |-22966 /kubelet --address=0.0.0.0 --allow-privileged=true --cluster-dns=192.168.192.10 --cluster-domain=cluster.local --
cloud-provider= --port=10250 --lock-file=/var/run/lock/kubelet.lock --exit-on-lock-contention --node-labels=worker=true --pod-manife
st-path=/etc/kubernetes/manifests --kubeconfig=/etc/kubernetes/kubeconfig.yaml --require-kubeconfig=true --network-plugin=cni --cni-
conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --logtostderr=true
           `-23109 journalctl -k -f

Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
Jan 02 10:31:41 ae02.pek.prod.com kubelet-wrapper[22966]: fatal error: runtimeÂ·unlock: lock count
```

and the output of strace:
```
# strace -p 22966
Process 22966 attached
read(25, ^CProcess 22966 detached
 <detached ...>
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10+coreos.0", GitCommit:"db06c5223888db5169a6126fb82f323fce1f1eeb", GitTreeState:"clean", BuildDate:"2017-11-07T14:06:30Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Baremetal

- OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.5.0
VERSION_ID=1298.5.0
BUILD_ID=2017-02-28-0013
PRETTY_NAME="Container Linux by CoreOS 1298.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

- Kernel (e.g. `uname -a`):
Linux ae01.pek.prod.com 4.9.9-coreos-r1 #1 SMP Tue Feb 28 00:06:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz GenuineIntel GNU/Linux

- Others:
I'm running kubelet with rkt .

**Comment by likunbyl** [comment]
@kubernetes/sig-node-bugs

**Comment by wenlxie** [comment]
Can you use command `localhost:10248/debug/pprof/goroutine?debug=2` to get ths stack?
It is very helpful to debug such kind of issue.

**Comment by likunbyl** [comment]
Thank you , wenlxie.

I'm sorry I had recovered these node by 'systemctl restart kubelet' command, so I supposed the stack of kubelet of that time is not available, I guess this command should be ran at the kubelet hung time.

And  I still doubt if that command can be ran successfully,  since I had accessed port 10255 or 10250 at that time and got no response at all.

Anyway, in case I get these information at next kubelet hang time, I will upload to here for somebody to take a look at it.

**Comment by likunbyl** [comment]
Today, I had another node entered this situation, and tried localhost:10248/debug/pprof/goroutine?debug=2 to  debug it, but no response. Is there anything else I can do ?

**Comment by jiaxuanzhou** [comment]
@kubernetes/sig-node-bugs this bug also  happened in our production environment too, i have tried dlv/gdb and pprof, but no useful message found, 
port 10248 seems not working, i can not get any response from :10248/debug/pprof/goroutine
here is the gdb infos:
(gdb) attach 18527
Attaching to process 18527
Reading symbols from /usr/bin/kubelet...(no debugging symbols found)...done.
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[New LWP 129173]
[New LWP 46837]
[New LWP 186571]
[New LWP 173705]
[New LWP 6272]
[New LWP 121724]
[New LWP 28573]
[New LWP 68392]
[New LWP 102072]
[New LWP 77019]
[New LWP 19413]
[New LWP 19368]
[New LWP 19367]
[New LWP 19179]
[New LWP 19175]
[New LWP 19146]
[New LWP 19144]
[New LWP 19143]
[New LWP 19142]
[New LWP 19129]
[New LWP 19127]
[New LWP 19096]
[New LWP 18734]
[New LWP 18733]
[New LWP 18598]
[New LWP 18597]
[New LWP 18596]
[New LWP 18587]
[New LWP 18586]
[New LWP 18583]
[New LWP 18582]
[New LWP 18579]
[New LWP 18578]
[New LWP 18577]
[New LWP 18576]
[New LWP 18575]
[New LWP 18574]
[New LWP 18573]
[New LWP 18570]
[New LWP 18569]
[New LWP 18566]
[New LWP 18565]
[New LWP 18564]
[New LWP 18563]
[New LWP 18557]
[New LWP 18556]
[New LWP 18547]
[New LWP 18546]
[New LWP 18544]
[New LWP 18543]
[New LWP 18542]
[New LWP 18541]
[New LWP 18539]
[New LWP 18531]
[New LWP 18530]
[New LWP 18529]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /lib64/libnss_dns.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_dns.so.2
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
0x0000000000462af3 in runtime.futex ()

**Comment by jiaxuanzhou** [comment]
@vishh @derekparker would you please help? thanks

**Comment by zq-david-wang** [comment]
I got similar issue in my k8s1.6 cluster, node was stuck in NotReady state..
>enn-yc-27 # systemctl status kubelet
> ● kubelet.service - Kubernetes Kubelet Server
>    Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
>    Active: active (running) since 一 2018-02-26 23:45:58 CST; 6 days ago
>      Docs: https://github.com/GoogleCloudPlatform/kubernetes
>   Process: 48987 ExecStartPre=/usr/sbin/sysctl net.core.somaxconn=512 (code=exited, status=0/SUCCESS)
>   Process: 48978 ExecStartPre=/usr/sbin/modprobe rbd (code=exited, status=0/SUCCESS)
>  Main PID: 48990 (kubelet)
>    CGroup: /system.slice/kubelet.service
>            ├─48990 /usr/local/bin/kubelet --logtostderr=false --log-dir=/var/log/kubernetes/kubelet --v=2 ...
>            └─49106 journalctl -k -f
> 
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: runtime·unlock: lock count
> 3月 05 04:48:25 enn-yc-27 kubelet[48990]: fatal error: schedule: holding locks
>

**Comment by Arslanbekov** [comment]
We have the same error.
Please confirm, does PR https://github.com/kubernetes/kubernetes/pull/63492 resolve this issue?
