### ISSUE TITLE
rbd volume plugin should support image feature adjustment according to kernel version 

### ISSUE THREAD

**Issue by wenjun93** [kubernetes/kubernetes#57960]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
kernel rbd driver doesn't support all rbd features, currently is 3 (kernel version < 4.9) and 7 (kernel version 4.9+), while newest rbd backend support rbd_default_feature 63 or higher. Attach will fail if kernel doesn't support the rbd volume feature.

**What you expected to happen**:
rbd volume plugin now support natively provision of feature 1 and 3 [PR 45805](https://github.com/kubernetes/kubernetes/pull/45805). however, to support external rbd volume provisioner like [standalone-cinder](https://github.com/kubernetes-incubator/external-storage/tree/master/openstack/standalone-cinder) I think should we support rbd feature adjustment according to kernel version and backend rbd_default_feature. 
Before attach, kubelet can do this:
- get kernel version, get rbd volume feature
- if kernel version doesn't support rbd volume feature, disable some of the features to fit kernel version with `rbd feature disable` command line.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We can also disable the kernel unsupported features from rbd backend side. However, some features are useful for rbd management(etc. object-map, disable this feature will decrease the rbd backend performance a bit), so a better way is to do this from user side(kubelet). 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rootfs** [comment]
kernel version is not reliable to filter rbd features. RHEL/CentOS kernels do not strictly follow upstream kernel release.
