### ISSUE TITLE
Scheduler refuses to start in version 1.9.1 when specifying volume feature gates

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#57961]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When starting the `kube-scheduler` with version 1.9.1 and the `PersistentLocalVolumes` and `VolumeScheduling` feature gates it tries to list/get/watch storage classes, but the RBAC bootstrap clusterrole `system:kube-scheduler` does not contain these privileges.
Following, the scheduler cannot start:
```
I0108 10:26:27.006404       1 server.go:551] Version: v1.9.1
I0108 10:26:27.006814       1 factory.go:837] Creating scheduler from algorithm provider 'DefaultProvider'
I0108 10:26:27.006834       1 factory.go:898] Creating scheduler with fit predicates 'map[NoVolumeZoneConflict:{} MaxAzureDiskVolumeCount:{} MatchInterPodAffinity:{} GeneralPredicates:{} CheckNodeMemoryPressure:{} PodToleratesNodeTaints:{} CheckVolumeBinding:{} MaxEBSVolumeCount:{} MaxGCEPDVolumeCount:{} NoDiskConflict:{} CheckNodeDiskPressure:{} CheckNodeCondition:{}]' and priority functions 'map[NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{} SelectorSpreadPriority:{} InterPodAffinityPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{}]'
I0108 10:26:27.007121       1 server.go:570] starting healthz server on 0.0.0.0:10251
E0108 10:26:27.054334       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list storageclasses.storage.k8s.io at the cluster scope
```

**What you expected to happen**:
The [bootstrap rule for `kube-scheduler`](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L405-L429) contains privileges to read `StorageClasses`, so that the scheduler can start properly.

**How to reproduce it (as minimally and precisely as possible)**:
Start a `kube-apiserver` and a `kube-scheduler` as follows: `/hyperkube scheduler --config=/var/lib/kube-scheduler-config/config.yaml --feature-gates=PersistentLocalVolumes=true,VolumeScheduling=true --v=2` where` config.yaml` looks like:
```yaml
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /var/lib/kube-scheduler/kubeconfig
leaderElection:
  leaderElect: true
```

**Anything else we need to know?**:
After modifying the `system:kube-scheduler` clusterrole by granting `get`, `list`, `watch` verbs on apiGroup `storage.k8s.io` for resources `storageclasses` it started successfully.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS

**Comment by wackxu** [comment]
I can help fix it

**Comment by msau42** [comment]
This should have been added here: https://github.com/kubernetes/kubernetes/pull/55039/commits/01a8772111e5b5d057e9580e7787ca0ffae43233#diff-eee450e334a11e0b683ce965f584c3c4

We have alpha e2e tests that are running fine.

**Comment by liggitt** [comment]
Did you also set the feature gate when starting the apiserver?

**Comment by liggitt** [comment]
The bootstrap role only gains those permissions when enabling the alpha feature gate

**Comment by rfranzke** [comment]
Yes, I set it on the apiserver and on the controller-manager as well.

**Comment by liggitt** [comment]
Can you provide the content of the `system:kube-scheduler` clusterrole you see after starting the apiserver with the PersistentLocalVolumes feature gate enabled?

**Comment by liggitt** [comment]
As mentioned by @msau42 those permissions get included in the role automatically when the apiserver is started with those feature gates

https://github.com/kubernetes/kubernetes/blob/5911f87dadb91a0670183ece1cefce9c24ff4251/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L485-L495

**Comment by rfranzke** [comment]
Thanks for taking a look - I tried once again with a fresh cluster and now it worked as expected. Probably I have misspelled something in the apiserver configuration last week. Closing the ticket therefore. Again, thank's for your time!

**Comment by dhawal55** [comment]
I'm seeing this issue intermittently. I'm using bootkube v0.13 to deploy my permanent kube-components (v1.11). 1/10 times my scheduler is not able to schedule any pods and the logs have this same error:
`E0302 00:56:21.169412       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:scheduler" cannot list storageclasses.storage.k8s.io at the cluster scope
E0302 00:56:22.172445       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:130: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:scheduler" cannot list storageclasses.storage.k8s.io at the cluster scope`

**Comment by msau42** [comment]
Did you set the feature gate on the apiserver when you brought up the cluster for the first time?

**Comment by mariusgrigoriu** [comment]
Speaking for @dhawal55, we do not have the feature gates mentioned in the thread set. However, according to the docs, those feature gates are enabled by default since 1.10.

**Comment by dhawal55** [comment]
I'm still facing this issue intermittently. Let me know if you need any other details

**Comment by msau42** [comment]
Can you show what permissions your `system:kube-scheduler` clusterrole has?

**Comment by dhawal55** [comment]
```kubectl describe clusterrole system:kube-scheduler 
Name:         system:kube-scheduler
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources                    Non-Resource URLs  Resource Names    Verbs
  ---------                    -----------------  --------------    -----
  bindings                     []                 []                [create]
  endpoints                    []                 [kube-scheduler]  [delete get patch update]
  endpoints                    []                 []                [create]
  events                       []                 []                [create patch update]
  nodes                        []                 []                [get list watch]
  persistentvolumeclaims       []                 []                [get list watch]
  persistentvolumes            []                 []                [get list watch]
  pods                         []                 []                [delete get list watch]
  pods/binding                 []                 []                [create]
  pods/status                  []                 []                [patch update]
  replicationcontrollers       []                 []                [get list watch]
  services                     []                 []                [get list watch]
  replicasets.apps             []                 []                [get list watch]
  statefulsets.apps            []                 []                [get list watch]
  replicasets.extensions       []                 []                [get list watch]
  poddisruptionbudgets.policy  []                 []                [get list watch]```

**Comment by msau42** [comment]
Thanks, it's missing the roles referenced [here](https://github.com/kubernetes/kubernetes/issues/57961#issuecomment-357584046).  Is this from a freshly created cluster at 1.11?  Can you also show the cmd line arguments when starting the kube-apiserver?

**Comment by dhawal55** [comment]
@msau42 Thanks for your quick response and helping me with this issue. 

Yes, this is from a freshly created v1.11.8 cluster. 

The code you referenced is not in `master` branch or any of the previously tagged versions. I see it for `system:persistent-volume-provisioner` role but not for `system: kube-scheduler` role. Also, I get this issue sometimes only. I have fully working clusters with the same definition of `system-kube-scheduler` role but occasionally, creating new cluster with the same code base fails.

Here's my apiserver cmd line arguments:
`
- command:
    - /usr/bin/flock
    - --exclusive
    - --timeout=30
    - /var/lock/api-server.lock
    - /hyperkube
    - apiserver
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority
    - --advertise-address=$(POD_IP)
    - --allow-privileged=true
    - --apiserver-count=5
    - --audit-log-path=-
    - --audit-policy-file=/etc/apiserver/audit_policy.config
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/ssl/kube-apiserver/ca.crt
    - --cloud-provider=aws
    - --enable-swagger-ui
    - --etcd-cafile=/etc/ssl/etcd/ca.crt
    - --etcd-certfile=/etc/ssl/etcd/tls.crt
    - --etcd-keyfile=/etc/ssl/etcd/tls.key
    - --etcd-servers=https://localhost:2379
    - --external-hostname=hydrogen.platform.r53.example.com
    - --feature-gates=AdvancedAuditing=true
    - --kubelet-client-certificate=/etc/ssl/kube-apiserver/tls.crt
    - --kubelet-client-key=/etc/ssl/kube-apiserver/tls.key
    - --runtime-config=api/all=true
    - --secure-port=443
    - --service-account-key-file=/etc/ssl/service-account/service-account.pub
    - --service-cluster-ip-range=25.0.0.0/16
    - --storage-backend=etcd3
    - --enable-swagger-ui
    - --tls-cert-file=/etc/ssl/kube-apiserver/tls.crt
    - --tls-private-key-file=/etc/ssl/kube-apiserver/tls.key
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: gcr.io/google_containers/hyperkube:v1.11.8
`

**Comment by dhawal55** [comment]
I see that `system:kube-scheduler` user is also mapped to `system:volume-scheduler` cluster role which should grant it access to `storageclasses`.

**Comment by dhawal55** [comment]
I copied the scheduler's serviceAccount token in my local kubectl config and ran the `kubectl auth can-i get storageclasses` and it returns `no`. However, as per the `system:volume-scheduler` clusterrolebinding, it should have permission. Is it possible that apiserver is not merging permissions assigned from multiple rolebindings correctly?

**Comment by liggitt** [comment]
if you are using a service account token for the scheduler, then it is not using the `system:kube-scheduler` user. how are you running your scheduler?

**Comment by dhawal55** [comment]
@liggitt Aha, you are right. I use bootkube to deployer kube-scheduler. It uses `scheduler` serviceaccount which is only mapped to `system:kube-scheduler` clusterrole and not `system:volume-scheduler` clusterrole. Thank you for pointing it out.

**Comment by dhawal55** [comment]
@liggitt If I run `kube-scheduler` as a pod, is there any way to use the built-in `system:kube-scheduler` user instead of serviceaccount?
