### ISSUE TITLE
Cluster E2E Test should not use docker CLI directly.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#57979]
Some cluster E2E tests ssh into the node and use `docker ps` and `docker kill` to operate containers directly, such as:
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L3905
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L3936
* https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L3963

We should install `crictl` during bootstrap and those tests should use `crictl` instead.

@yujuhong @feiskyer @mrunalp 
/cc @kubernetes/sig-node-bugs  @kubernetes/sig-testing-bugs

**Comment by antoniaklja** [comment]
let me sort this out

**Comment by Random-Liu** [comment]
@antoniaklja Thanks for offering help! I've got a PR ready for this. https://github.com/kubernetes/kubernetes/pull/58024
