### ISSUE TITLE
Mutating Admission Webhooks: apiserver needs to default patched objects

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#57982]
Example: if you add an initContainer to a pod, you have to set fields that ought to have system-applied defaults.

It is not future-safe for webhook authors to supply their own defaults, therefore I believe we should fix this and backport it.

**Comment by liggitt** [comment]
Agree that all external->internal transitions should have defaults applied server side. I'd expect:

1. apply patch
2. apply defaults
3. convert to internal

**Comment by lavalamp** [comment]
Similar problem: https://github.com/kubernetes/kubernetes/issues/42764
