### ISSUE TITLE
Outdated list of admission controllers in gce/config-default.sh 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#57983]
We should keep the admission controllers list in sync:

https://github.com/kubernetes/kubernetes/blob/df2428c6dd30c591444c9bd9b5e8322986da331a/cluster/gce/config-default.sh#L301-L302

https://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use
```
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ValidatingAdmissionWebhook,ResourceQuota,DefaultTolerationSeconds,MutatingAdmissionWebhook
```

@lavalamp @caesarxuchao

**Comment by lavalamp** [comment]
The docs are more recent than the config.

**Comment by lavalamp** [comment]
Actually there's a few plugins that aren't mentioned by the docs, I don't know off the top of my head.

**Comment by deads2k** [comment]
> The docs are more recent than the config.

No, they are different.  NodeRestriction should definitely be recommended.  Didn't look much beyond that.

We really need to move to the model we in the generic apiserver of recommended order, recommended off, and the others are on.  We plan to complete the work that allows you to turn some on without having the specify the fully ordered list.

**Comment by sttts** [comment]
Now we have a default list of admission controllers enabled without any arguments, the use of admission-control is deprecated.
