### ISSUE TITLE
Kubelet Regularly Crashing

### ISSUE THREAD

**Issue by sstelfox** [kubernetes/kubernetes#57981]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:

Kubelet's are regularly crashing (goroutine panics) on my nodes with several different stack traces. I was experiencing this on 1.9.0, I just upgraded to 1.9.1 and it is continuing to happen.

**What you expected to happen**:

For Kubelets to remain running and ready in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

My control plane seems to be stable (and are on separate machines). There are three "controller" servers behind an nginx TCP load balancer, each running and etcd node, an apiserver instance, a scheduler instance, and a controller-manager instance.

The worker nodes (three as well) connect to the API via the load balancer and are running docker, kubelet, and kube-proxy. The flags kubelet is being started up with are listed in the `Others` section.

Usually this crashes sometime between 2 minutes and 3 hours, on average it's seems it is more common around an an hour and a half.

**Anything else we need to know?**:

I don't know if this is relevant but there are no pods in the kubernetes cluster under any namespace with the exception of the `kube-dns` deployment from this repo. Two of the nodes seem to be going down and they are not the nodes that have kube-dns running on them.

This is configured with the bridge CNI plugin, using `host-local` ipam and is using the stock Gentoo ebuild / package with the ~amd64 flag. All pod IPs can directly route between each other, the local networks, and the internet (this is NAT'd at the gateway). There are no network policies.

The two stack traces occur at different code paths so may be two separate issues. I'm not familiar enough with the kubernetes code base to determine the relationship.

[This issue](https://github.com/kubernetes/kubernetes/issues/57028) seems similar but I'm not sure if it's directly connected.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"archive", BuildDate:"2018-01-08T14:45:45Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"archive", BuildDate:"2018-01-08T15:11:39Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

Bare metal Gentoo hosts adapted from Kubernetes the Hard Way.

- OS (e.g. from /etc/os-release):

```
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

- Kernel (e.g. `uname -a`):

Linux worker03 4.14.8-gentoo-r1whisper #6 SMP Thu Jan 4 18:22:50 UTC 2018 x86_64 Intel Xeon E3-12xx v2 (Ivy Bridge) GenuineIntel GNU/Linux

- Install tools:

N/A

- Others:

Kubelet is being started up with the following flags:

```
--client-ca-file=/var/lib/kubernetes/ca.pem \
--tls-cert-file=/var/lib/kubelet/worker01.pem \
--tls-private-key-file=/var/lib/kubelet/worker01-key.pem \
--anonymous-auth=false \
--authorization-mode=Webhook \
--kubeconfig=/var/lib/kubelet/kubeconfig \
--cluster-dns=10.32.0.10 \
--cluster-domain=cluster.local \
--fail-swap-on=false \
--eviction-hard='memory.available<256Mi' \
--network-plugin=cni \
--pod-cidr=10.200.1.0/24 \
--container-runtime=docker \
--node-labels=env=test \
--image-pull-progress-deadline=2m \
--runtime-request-timeout=15m \
--register-node=true \
--v=2
```

I put the two complete stack traces [in a gist](https://gist.github.com/sstelfox/cae1474dcf575b332cf8a28804ee58f7) but the most relevant parts seem to be:

```
unexpected fault address 0xc420dac140
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc420dac140 pc=0xc420dac140]

goroutine 211 [running]:
runtime.throw(0x38a42e3, 0x5)
        /usr/lib64/go/src/runtime/panic.go:605 +0x95 fp=0xc420aa6c98 sp=0xc420aa6c78 pc=0x42ea55
runtime.sigpanic()
        /usr/lib64/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc420aa6ce8 sp=0xc420aa6c98 pc=0x445947
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
        /var/tmp/portage/sys-cluster/kubelet-1.9.1/work/kubelet-1.9.1/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:244 +0xa3
```

And:

```
panic: runtime error: index out of range
fatal error: panic holding locks

goroutine 189 [running]:
runtime.throw(0x38c896e, 0x13)
	/usr/lib64/go/src/runtime/panic.go:605 +0x95 fp=0xc420de5b18 sp=0xc420de5af8 pc=0x42ea55
panic(0x3177a60, 0x5743ac0)
	/usr/lib64/go/src/runtime/panic.go:451 +0x579 fp=0xc420de5bc0 sp=0xc420de5b18 pc=0x42e619
runtime.panicindex()
	/usr/lib64/go/src/runtime/panic.go:28 +0x5e fp=0xc420de5be0 sp=0xc420de5bc0 pc=0x42cffe
runtime.selectgo(0xc420de5e98, 0xc420b368a0)
	/usr/lib64/go/src/runtime/select.go:363 +0x1df2 fp=0xc420de5e58 sp=0xc420de5be0 pc=0x441752
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4211aa4b0, 0x5f5e100, 0x0, 0xc4211aa401, 0xc420066120)
	/var/tmp/portage/sys-cluster/kubelet-1.9.1/work/kubelet-1.9.1/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:145 +0x17e fp=0xc420de5f28 sp=0xc420de5e58 pc=0x57c17e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4211aa4b0, 0x5f5e100, 0xc420066120)
	/var/tmp/portage/sys-cluster/kubelet-1.9.1/work/kubelet-1.9.1/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc420de5f60 sp=0xc420de5f28 pc=0x57bfed
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).Run(0xc420c59800, 0x576ec20, 0xc420c02780, 0xc420066120)
	/var/tmp/portage/sys-cluster/kubelet-1.9.1/work/kubelet-1.9.1/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:135 +0xdd fp=0xc420de5fc0 sp=0xc420de5f60 pc=0x2b1dc0d
runtime.goexit()
	/usr/lib64/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420de5fc8 sp=0xc420de5fc0 pc=0x45fe31
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	/var/tmp/portage/sys-cluster/kubelet-1.9.1/work/kubelet-1.9.1/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:244 +0xa3
```

**Comment by sstelfox** [comment]
Looking through the issues this may also be related: https://github.com/kubernetes/kubernetes/issues/57955

**Comment by hzxuzhonghu** [comment]
which go version are you using, seems like panic in select.go

**Comment by sstelfox** [comment]
@hzxuzhonghu That is actually included in the kubernetes version but specifically:

> GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"
