### ISSUE TITLE
kubefed not installing right ....

### ISSUE THREAD

**Issue by rangapv** [kubernetes/kubernetes#57995]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

Labels:
/ sig federation
**What happened**:
kubefed install not working right...

I did the following.....
Step 1:
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/kubernetes-client-linux-amd64.tar.gz
  tar -xzvf kubernetes-client-linux-amd64.tar.gz

Step 2:
sudo snap install kubefed --classic
  kubefed version

Error:
/snap/kubefed/260/kubefed: 1: /snap/kubefed/260/kubefed: Syntax error: redirection unexpected

**What you expected to happen**:
kubefed version should display the right version number 
Like  kubefed version #(like 1.7.0)

**How to reproduce it (as minimally and precisely as possible)**:
Clean Install of K*s 1.9 and then the above Step1 and step 2

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9 
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.13.0-1002-gcp #5-Ubuntu SMP Tue Dec 5 13:20:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: snap
- Others:

**Comment by liggitt** [comment]
please move this to the https://github.com/kubernetes/federation/issues/ repo
