### ISSUE TITLE
pull-kubernetes-verify failing due to bitbucket.org being down

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#58005]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
@kubernetes/sig-testing-bugs 

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57552/pull-kubernetes-verify/70802/ failed with:
```
I0109 13:45:01.919] +++ [0109 13:45:01] Downloading dependencies - this might take a while
W0109 13:45:02.602] # cd .; git clone https://bitbucket.org/bertimus9/systemstat.git /go/src/k8s.io/kubernetes/_output/dockerized/go/src/bitbucket.org/bertimus9/systemstat
W0109 13:45:02.603] Cloning into '/go/src/k8s.io/kubernetes/_output/dockerized/go/src/bitbucket.org/bertimus9/systemstat'...
W0109 13:45:02.603] fatal: unable to access 'https://bitbucket.org/bertimus9/systemstat.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
W0109 13:45:02.604] godep: error downloading dep (bitbucket.org/bertimus9/systemstat): exit status 128
W0109 13:47:50.706] godep: Error downloading some deps. Aborting restore and check.
W0109 13:47:50.986] !!! [0109 13:47:50] Call tree:
W0109 13:47:50.987] !!! [0109 13:47:50]  1: /go/src/k8s.io/kubernetes/build/../build/common.sh:551 kube::build::run_build_command_ex(...)
W0109 13:47:50.989] !!! [0109 13:47:50]  2: /go/src/k8s.io/kubernetes/build/run.sh:39 kube::build::run_build_command(...)
I0109 13:47:51.089] FAILED   verify-staging-godeps.sh	185s
```

**What you expected to happen**:

The dependencies should be fetched when the container for running this test is built, not at test time.

**Comment by VRuzhentsov** [comment]
@porridge It can be bitbucket connection issues
https://status.bitbucket.org/incidents/z029156p1svh

**Comment by BenTheElder** [comment]
> The dependencies should be fetched when the container for running this test is built, not at test time.

The dependencies *are* verified, but the verify script does some hacks to compare vendor changes against master. https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh

**Comment by ixdy** [comment]
The intent of the verify-godeps check is to verify that you can clone all of the godeps. It's non-hermetic and routinely broken by definition.

**Comment by fejta** [comment]
This looks like a /close?

**Comment by porridge** [comment]
On Tue, Jan 9, 2018 at 11:23 PM, Jeff Grafton <notifications@github.com>
wrote:

> The intent of the verify-godeps check is to verify that you can clone all
> of the godeps. It's non-hermetic and routinely broken by definition.
>
Ouch. So what will happen if one of the dependencies' upstreams disappears
one day? All k8s development halts until the dependency is ripped out?

**Comment by porridge** [comment]
Perhaps this test should only be looking at dependencies added in the PR?..
