### ISSUE TITLE
ClusterIP exposed service not reachable

### ISSUE THREAD

**Issue by Ragnaroek** [kubernetes/kubernetes#58019]
/kind bug

**What happened**:
Created a deployment with port definition
```
    "ports": [
    {
       "containerPort": 18081,
       "protocol": "TCP"
    }
    ],
```
port is exposed in the docker container.

```
kubectl port-forward <pod-name> 18081:18081
```
and doing a curl request (http api exposed) works as it should be.

exposed the service with (on Azure, but for ClusterIP that shouldn't matter?)
```
kubectl expose deployment <deployment-name> --type=ClusterIP
```
Now trying to reach the pods in the deployment with the same curl command as in the port-forward but with hostname
```
curl http://<deployment-name>:18081/
```
curl responds with 
```
Failed to connect to <deployment-name> port 18081: Connection refused
```
**What you expected to happen**:

Pod/Deployment reachable with service name <deployment-name> (derived from deployment)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Kubernetes 1.8.2 on Azure

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-09T07:26:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Azure

kube-proxy prints this error/warning:
 time="2018-01-09T06:11:21Z" level=warning msg="Running modprobe ip_vs failed with message: ``, error: exec: \"modprobe\": executable file not found in $PATH"
time="2018-01-09T06:11:21Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed." 

but according to the fix in 1.8.3 that shouldn't be the problem / have no impact?

@kubernetes/sig-azure-bugs

**Comment by Ragnaroek** [comment]
@kubernetes/sig-azure-bugs

**Comment by m1093782566** [comment]
Are you using IPVS proxy mode?

Please make sure ipvs is enabled in your kernel.

**Comment by Ragnaroek** [comment]
Since this is a Azure managed installation, I don't know what is configured.
But the error in kube-proxy then would explain the behaviour. I check with Microsoft what is configured.

**Comment by Ragnaroek** [comment]
No IPVS is not enabled:
W0109 06:11:21.642284       1 server_others.go:263] Flag proxy-mode="" unknown, assuming iptables proxy
I0109 06:11:21.643972       1 server_others.go:117] Using iptables Proxier.
I0109 06:11:21.751161       1 server_others.go:152] Tearing down inactive rules. 

so that shouldn't be the cause?

**Comment by y325A** [comment]
I am also experiencing this issue using a service with externalIPs.

My Windows nodes can connect to the service using the external IP (without going out to the internet) but my Linux master is unable to. I can provide additional debug information if anyone needs me to run anything.

**Comment by Ragnaroek** [comment]
I found out what the problem was. It was NOT in Kuberetes.
The prozess in the docker container did only accept connections from localhost by default for security reasons. 

Very helpful was this document:
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#running-commands-in-a-pod
