### ISSUE TITLE
Delays starting deployments seemingly caused by "Unable to mount volume" errors

### ISSUE THREAD

**Issue by hjwp** [kubernetes/kubernetes#58016]
/kind bug

**What happened**:
Our deployments depend on PVC/PV HostPaths as well as ConfigMaps.  The volumes are unique for users, but users may have multiple deployments that share them.
In production (but not in dev) we are seeing systematic issues where deployments take a long time to start (order of 10 minutes), and we see a lot of errors in the logs saying "Unable to mount volumes" / "timeout expired waiting for volumes to attach/mount".
HostPaths are pointing at a local NFS mount (we did also try direct individual NFS mounts from deployments, but thought switching to a single mount might help).

**What you expected to happen**:
We'd expect deployments to start up promptly with no problems mounting.  Our NFS servers are under fairly heavy load, so slow, but they are there.

**How to reproduce it (as minimally and precisely as possible)**:
We've struggled to reproduce this in dev environments, so load may be a factor.

**Anything else we need to know?**:

Example log line:

```
kubelet[22504]: E0109 18:47:25.720040   22504 kubelet.go:1628] Unable to mount volumes for pod "harrynu-234-deployment-799c88df7d-bsw2q_default(4a9d46ee-f56c-11e7-a531-0a7ee8fefcaa)": timeout expired waiting for volumes to attach/mount for pod "default"/"harrynu-234-deployment-799c88df7d-bsw2q". list of unattached/unmounted volumes=[homedir varwww tmp varlog etcpasswd etcgroup etcsubversionservers etcpipconf binrunscheduledtaskpy bingist-runnersh binuserwsgiwrapperpy binlaunchbashinvirtualenvpy binpastartdjangowebappwithvirtualenvpy binwsgifiletemplatepy binsnakesaypy default-token-vd4qb]; skipping pod

kubelet[22504]: E0109 18:47:25.721274   22504 pod_workers.go:182] Error syncing pod 4a9d46ee-f56c-11e7-a531-0a7ee8fefcaa ("harrynu-234-deployment-799c88df7d-bsw2q_default(4a9d46ee-f56c-11e7-a531-0a7ee8fefcaa)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"harrynu-234-deployment-799c88df7d-bsw2q". list of unattached/unmounted volumes=[homedir varwww tmp varlog etcpasswd etcgroup etcsubversionservers etcpipconf binrunscheduledtaskpy bingist-runnersh binuserwsgiwrapperpy binlaunchbashinvirtualenvpy binpastartdjangowebappwithvirtualenvpy binwsgifiletemplatepy binsnakesaypy default-token-vd4qb]

```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:  AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64
- Install tools:
- Others:

**Comment by hjwp** [comment]
PS having seen #54263 we tried switching off cadvisor with `--cadvisor-port=0` on node, no effect.

**Comment by hjwp** [comment]
@kubernetes/sig-storage-bugs

**Comment by jingxu97** [comment]
@hjwp Could you please share your kubelet log with us so we can debug the issue? You can email me jinxu at google.com. Thanks!

**Comment by hjwp** [comment]
Wow thanks for the speedy response! Will do.  Am assuming you don't want all 1.3gigs of logs so I'll just send the last few hours or so, do ask if you want the whole lot.

**Comment by gpjt** [comment]
Co-worker of @hjwp here -- just a note to say that after we upgraded from 1.9.2 to 1.10.0, things got much better.   Deployments now take about five minutes to start instead of several hours, so while it's still not perfect, it's at least usable.   This issue can be closed.

**Comment by jingxu97** [comment]
@gpjt thanks for the update. Close it the issue.
