### ISSUE TITLE
Automated Debian Base Images

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#58012]
**What would you like to be added**:

Our core/base images should be built and housed on Kubernetes Community Infra.

- `debian-base`
- `debian-iptables`

**Why is this needed**:

From @rphillips:

Currently, the Debian base images used to create the hyperkube and other images use a Base Debian docker image that is generated and pushed to gcr.io. It would be awesome to automate the debian base images to automatically be built so they contain patched binaries with security updates.

By enabling this functionality, builds would always use a modern base image with patched binaries.

From @justaugustus:

We currently depend an extremely small set of Googlers to push these images.
There's minimal public documentation or visibility into this process and it creates a bottleneck when trying to do updates. This is especially detrimental from a security standpoint.

### Image building

- [x] (https://github.com/kubernetes/kubernetes/pull/90558, https://github.com/kubernetes/test-infra/pull/17424) Initial image building job
- [x] (https://github.com/kubernetes/test-infra/pull/17475, https://github.com/kubernetes/test-infra/pull/17476, https://github.com/kubernetes/test-infra/pull/17485) Updated image building jobs
- [x] (https://github.com/kubernetes/test-infra/pull/17496) Fix args for `debian-{base,iptables}` and pause image builds
- [ ] Consider pulling in content from @hoegaarden's original PR: https://github.com/kubernetes/kubernetes/pull/80909

### `debian-base`

- [x] (https://github.com/kubernetes/kubernetes/pull/90665) bump the `debian-base` image tag
- [x] (https://github.com/kubernetes/k8s.io/pull/832) promote the `debian-base` image
- [x] (https://github.com/kubernetes/kubernetes/pull/90697) update dependents to use the new `debian-base` image

### `debian-iptables`

- [x] (https://github.com/kubernetes/kubernetes/pull/90697) bump the `debian-iptables` tag
- [x] (https://github.com/kubernetes/k8s.io/pull/839) promote the `debian-iptables` image
- [x] (https://github.com/kubernetes/kubernetes/pull/90782) update dependents to use the new `debian-iptables` image

### Cherry picks

- [x] `debian-base` and `debian-iptables`
  - [x] 1.18: https://github.com/kubernetes/kubernetes/pull/90863
  - [x] 1.17: https://github.com/kubernetes/kubernetes/pull/90938
  - [x] 1.16: https://github.com/kubernetes/kubernetes/pull/90940

### Close out issues related to base image CVEs

/assign
cc(build-image OWNERS): @dims @BenTheElder @cblecker @listx 
cc: @kubernetes/release-engineering @kubernetes/product-security-committee 
/sig release
/area release-eng dependency security
/priority important-soon
/milestone v1.19

**Comment by ixdy** [comment]
cc @tallclair @rvkubiak

**Comment by rvkubiak** [comment]
I'm starting work in a week or two on automating builds for a first batch of "core" images.  We've yet to define core images, but this sounds like a good candidate.

If you could provide a link to the image on GCR, or better yet the source it's built from, I'll add this to the list.

**Comment by rphillips** [comment]
Awesome. One other thing to keep in mind regarding the -iptables and -hyperkube-base images is that kubernetes relies on binaries within the image to shell out to... (df, iptables, many others). We should try and preserve the status quo with the dependencies (for now) within the images.

**Comment by rvkubiak** [comment]
I haven't started yet, but if you have spare cycles you can probably make some progress.  I don't have a doc yet, but the idea is that we create Google Container Builder (https://cloud.google.com/container-builder/) configs that can build each addon.  Once we have the builds working in GCB then we can setup build triggers, although we haven't yet proposed what we want to trigger on to generate new builds.

The plan is to do this for 30 "core" addons as an example, so if you create GCB configs for the mentioned base images that would be a good start.

I am wrapping up my last project and should be starting on a proposal for this work in the next couple days.  We'll definitely share this with the release SIG before moving full steam ahead, but since we're already building Kubernetes releases using GCB I'm hopeful that we'll have good support for this plan.

**Comment by rphillips** [comment]
Thanks for the update... Does GCB have multiarch support (amd64, arm, arm64, ppc64le, s390x)? The current base images are built for those architectures using qemu.

**Comment by rphillips** [comment]
I created a prototype using container builder and uploaded the repo here https://github.com/rphillips/kubernetes-base-image-builder. The resulting build pushes all supported cross platform images into GCR.

**Comment by listx** [comment]
I'm interested in spending some cycles on this as well (I only realized yesterday that some of the core addons that @rvkubiak identified depend on these so-called debian base images). @rphillips: I've taken a look at your prototype but am curious why you decided to use the remote builder and not just plain GCB.

**Comment by rphillips** [comment]
@listx Hi! The make process builds cross platform images using qemu. qemu needs root privileges for the running kernel to forward foreign (ppc, mips, etc) system calls to the proper qemu emulator. When I was testing this, GCB did not support root or privileged access to the main machine, thus the need for the remote builder.

**Comment by AishSundar** [comment]
I was looking into doing something very similar for building k8s test images under https://github.com/kubernetes/kubernetes/tree/master/test/images. We also need support to build cross platform images using qemu.

/cc

**Comment by rphillips** [comment]
@rvkubiak Your previous comment said that you might be starting on this soon. Were you able to start on automating these builds? If you need another set of hands; I can certainly help.

**Comment by listx** [comment]
@rphillips rvkubiak handed off the work that he had with the ~30 core addon images to me. I only ran into this issue by accident while doing my own research about the current state of how debian-hyperkube-base was built.

Ultimately, who/what system would run the automation of running these remote cloud builds of these base images? Like, what is stopping us (open source K8s community) from adopting the prototype work you already have? And what would "adopting the prototype" actually mean?

Sorry for the volume of questions, but I'm trying to understand the big picture.

**Comment by AishSundar** [comment]
I asked the GCB community within Google about using qemu in the step and here's the response

"The build steps are run with root privileges ([`docker run --privileged`](https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/build/build.go#L961)). 
You should make a qemu docker image that you can use as a step."

Since we are already using the [qemu docker image](https://github.com/kubernetes/kubernetes/blob/3cb73605aa6679b24a4cefadd41eb2669b06bab9/build/debian-hyperkube-base/Makefile#L55), ideally it should work.

@rphillips what issue were you running into using qemu on GCB?

**Comment by listx** [comment]
FWIW I wrote a quick GCB yaml to see what the errors would be like, and it actually built successfully. This is what I used:

```
steps:
- name: gcr.io/cloud-builders/git
  args:
  - "clone"
  - "https://github.com/kubernetes/kubernetes"
- name: gcr.io/cloud-builders/docker
  dir: "/workspace/kubernetes/build/debian-base"
  env:
  - 'TMPDIR=/workspace'
  entrypoint: bash
  args:
  - -c
  - |
    set -ex
    apt-get install -y --no-install-recommends make
    for arch in amd64 arm arm64 ppc64le s390x; do
      ARCH=$arch make build
    done
timeout: 10800s
```

You can run it with: `gcloud container builds submit --no-source --config debian-base.vanilla.addon.yaml` where `debian-base.vanilla.addon.yaml` is the file with the above contents. I skipped the image pushing part because it wasn't vital to the experiment.

**Comment by rphillips** [comment]
@listx awesome... so we can simplify my experiment. We would just need to spin up the infrastructure on google's side (credentials, etc) to be able to leverage daily builds.

**Comment by listx** [comment]
@rphillips That's where it gets difficult. For now, just having a GCB yaml (including pushing of images to a registry) that the community could use would go a long way, as it would at least establish some measure of build provenance and also a hermetic build environment. I am working on a standardized GCB yaml building system (custom container + detection of built images to push to a registry from inside the GCB), which can hopefully be open sourced.

The real, serious solution to this ticket is the system that will automatically build and push these base images to a registry. But the elephant in the room is, what qualifies an image to be pushed to gcr.io/google-containers? What kind of testing? Not to mention the fact that we're not even getting into automated building of all child images that depend on these base images (I think this is standard practice in Linux distros where, a patched library of, e.g., libpng requires a rebuild of all child packages that depend on it to receive the same security fix).

**Comment by rphillips** [comment]
@listx I suggest pushing all images that successfully build, and leave it up to Kubernetes to bump to a specific version (ie: date based release).

**Comment by ixdy** [comment]
This is still a good idea in want of an owner, I believe.

**Comment by listx** [comment]
I think this issue is blocked by https://github.com/kubernetes/k8s.io/issues/157. At least, that issue seems to directly touch on this sort of problem.

**Comment by justaugustus** [comment]
/assign @justaugustus @cpanato @ameukam 
Related: https://github.com/kubernetes/kubernetes/issues/71719
/remove-lifecycle stale
/lifecycle frozen
/milestone v1.18

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering

**Comment by smourapina** [comment]
Hello @justaugustus, @cpanato, @ameukam! 
Bug Triage team here for the 1.18 release pinging issues without recent activity. This is a friendly reminder that code freeze is approaching (5 March). Do you still intend to include this issue for 1.18? Thanks in advance!

**Comment by tallclair** [comment]
Relevant discussion of whether we should just from debian-base to an upstream (debian:buster-slim) instead: https://github.com/kubernetes/kubernetes/pull/80909#issuecomment-564317233

**Comment by smourapina** [comment]
Hello @tallclair!
Code freeze for 1.18 is starting in 5 March (less than 1 week from now) and while there is still some time, we want to ensure that each issue that is part of the milestone has a chance to be finished. 
Is this still intended for milestone 1.18, or would it make sense to move it to 1.19?

**Comment by justaugustus** [comment]
Thanks for checking in. It looks like it's going to take a little work to think about removing the images altogether, so:
/milestone clear

**Comment by immutableT** [comment]
cc @immutableT

**Comment by justaugustus** [comment]
See description for updated status.

**Comment by jtslear** [comment]
@justaugustus I see we've updated the description indicating the inclusion into v1.19.  With code freeze closing in, is this still the intention?

**Comment by jtslear** [comment]
Due to reaching the code freeze deadline, I'm going to bump this to the next release.

/milestone v1.20

**Comment by mkorbi** [comment]
Heyho @rphillips @listx I wanted to check how it is going?
The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each relevant issue has a chance to be considered.

As the issue is tagged for 1.20, is it still planned for this release?

**Comment by justaugustus** [comment]
Debian images are now being built in GCB (triggered by Prowjobs) (ref: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md)
They've also been migrated to https://github.com/kubernetes/release/tree/master/images/build and are maintained by the Release Engineering subproject, so I'm considering this closed.

Feel free to ping if there are any questions.
/close
