### ISSUE TITLE
admission-control flag should have a reasonable order

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#58039]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

In most use case, `NamespaceLifecycle` comes behind `Initializers`.

According to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L69 `NamespaceLifecycle` plugin should be the first one . 

**What you expected to happen**:

 `NamespaceLifecycle` be the first ordered in `--admission-control`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jbeda** [comment]
/sig api-machinery

What is the impact on users?  From what I see, this is a non-mutating admission controller and so there shouldn't be a problem with the order.

But I'm not expert here so someone from api-machinery should verify.

**Comment by hzxuzhonghu** [comment]
commented on https://github.com/kubernetes/kubernetes/pull/58040#issuecomment-357116973

**Comment by sttts** [comment]
Can this be closed after we have a default order?

**Comment by hzxuzhonghu** [comment]
I think we can.
