### ISSUE TITLE
Deprecate --azure-container-registry-config

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#58034]
WRT https://github.com/kubernetes/kubernetes/pull/57613#issuecomment-355794478, container registry credentials should be included in a `${kubelet_root_dir}/config.json` docker `config.json` file instead.

We deprecated `--google-json-key` for this reason in #57613, but `--azure-container-registry-config` is more tricky, because the file it references is not static. 

We need to figure out what the alternative is for dynamically providing pull credentials to nodes.

/cc @smarterclayton @andyzhangx @brendandburns @colemickens @feiskyer @jdumars @karataliu

**Comment by feiskyer** [comment]
I think we need to enable Managed Service Identity (MSI) for all instances before deprecating `--azure-container-registry-config`. To do this, we also need to grant VM access to Resource Group in Azure IAM (e.g. config Azure AD in acs-engine).

@brendandburns @jdumars WDYT?

**Comment by justaugustus** [comment]
I think this is still active. Right, @feiskyer?
/remove-lifecycle stale

**Comment by feiskyer** [comment]
@justaugustus Thanks, this is still ative

**Comment by justaugustus** [comment]
@feiskyer -- What's the status of this?

**Comment by feiskyer** [comment]
@justaugustus Sorry, no progress yet. 

@khenidak @brendandburns Any ideas on this?

**Comment by justaugustus** [comment]
@feiskyer -- pinging again on this one.

**Comment by feiskyer** [comment]
We're not making any progress yet in this release. Still seeking the possible solutions for non-MSI cases, secret is one option for this.

/milestone v1.15

Related https://github.com/kubernetes/cloud-provider/issues/13 and https://github.com/kubernetes/kubernetes/issues/74379.

**Comment by dims** [comment]
None one is working on this. Let's move this out of 1.15

/milestone v1.16

**Comment by feiskyer** [comment]
@dims thanks. This missed v1.15 feature timeline. LGTM of moving to v1.16.

**Comment by xmudrii** [comment]
@feiskyer Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by feiskyer** [comment]
/milestone clear

@craiglpeters is preparing a KEP for this, but it's still not ready yet.

**Comment by ritazh** [comment]
Will follow this KEP for implementation https://github.com/kubernetes/enhancements/pull/1406

**Comment by craiglpeters** [comment]
This should be addressed by https://github.com/kubernetes-sigs/cloud-provider-azure/issues/289
/milestone v1.18

**Comment by smourapina** [comment]
Hello @craiglpeters @mtaufen @ritazh !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is a few weeks from now. Is this issue still intended for 1.18? Thanks in advance!

**Comment by smourapina** [comment]
C/O @kubernetes/sig-node-pr-reviews:
Code freeze for release 1.18 is starting in 5 March (less than 1 week from now) and we want to ensure that each issue has a chance to be finished on time. Is this still on track for this deadline?

**Comment by craiglpeters** [comment]
/milestone v1.19
The work on the KEP hasn't started yet, so moving this to 1.19

**Comment by bai** [comment]
👋 Hello from Bug Triage team! Wanted to follow up on this issue with a friendly reminder that the code freeze for 1.19 is starting June 25th (about 4 weeks from now).

As this issue is tagged for 1.19, is it still planned for this release?

**Comment by bai** [comment]
Hey 👋 Bug Triage here. Wanted to follow up on the status of this issue as we're approaching code freeze on 12.11.2020. This issue is tagged for 1.20, is it still planned for this release?

**Comment by erismaster** [comment]
👋   Hi Bug Triage here, seeing that there is not much recent activity here, and we are pretty late into code freeze, I am going to remove the milestone label. 

/milestone clear

**Comment by adisky** [comment]
/triage accepted
/priority backlog
I think we would be able to remove the flag once external kubelet credential provider promoted to GA
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2133-kubelet-credential-providers
