### ISSUE TITLE
Need reliable controller loop creation guarantees.

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#58032]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
A Deployment caused the creation of a ReplicaSet. 
The deployment has a emptyDir: sizeLimit: "0" in it.
However the Replica Set converted this into a emptyDir: {}.
This caused an equality failure during verification in the replication set creation in the controller.
As a result we ended up endlessly creating replica sets.
This problem can be significantly exacerbated by mutating webhooks.
We need a better mechanism for validating creation than a simple equality check.

**What you expected to happen**:
A valid ReplicaSet was created and then modifications to it did not cause endless creation.

**How to reproduce it (as minimally and precisely as possible)**:
1) emptyDir: sizeLimit: "0" is no longer a valid deployment (It was in an earlier release) . Create it manually in etcd.
2) Create a mutating webhook for replica set which alters some trivial field.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration: GCE
 
/sig apps

**Comment by liggitt** [comment]
Same issue as https://github.com/kubernetes/kubernetes/issues/57167, probably just need one open to track

**Comment by cheftako** [comment]
It is the same issue. Thank you for finding that. At some level though I think we should probably have an umbrella issue, as I think this pattern may be in use in more places than just the Deployment->ReplicaSet work flow. I had intended this to be more of the umbrella issue, however I clearly did not do a good job of conveying that.

**Comment by kow3ns** [comment]
I don't think we actually have this issue anywhere else ATM. DS, STS, Job, ChronJob, Node, PV, and PVC should no be susceptible at least.
