### ISSUE TITLE
Cannot Deploy Kubernetes 1.9.1 with kudeadm

### ISSUE THREAD

**Issue by Venkat-Sudharsanam** [kubernetes/kubernetes#58055]
I tried to install Kubernetes as per the documentation with the help of kubeadm.

# kubeadm init --pod-network-cidr=10.244.0.0/16
[init] Using Kubernetes version: v1.9.1
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Starting the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [gsg1pm-ft0376 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.10.31.181]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
	- There is no internet connection, so the kubelet cannot pull the following control plane images:
		- gcr.io/google_containers/kube-apiserver-amd64:v1.9.1
		- gcr.io/google_containers/kube-controller-manager-amd64:v1.9.1
		- gcr.io/google_containers/kube-scheduler-amd64:v1.9.1

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
couldn't initialize a Kubernetes cluster

# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 90-local-extras.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-01-10 13:27:05 IST; 5s ago
     Docs: http://kubernetes.io/docs/
  Process: 17637 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET
 Main PID: 17637 (code=exited, status=1/FAILURE)

Jan 10 13:27:05 GSG1PM-FT0376 systemd[1]: kubelet.service: Unit entered failed state.
Jan 10 13:27:05 GSG1PM-FT0376 systemd[1]: kubelet.service: Failed with result 'exit-code'.

 journalctl -xeu kubelet
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
Jan 10 13:27:15 GSG1PM-FT0376 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.906633   17706 feature_gate.go:220] feature gates: &{{} map[]}
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.906692   17706 controller.go:114] kubelet config controller: starting controller
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.906700   17706 controller.go:118] kubelet config controller: validating combinatio
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: W0110 13:27:15.915407   17706 cni.go:171] Unable to update cni config: No networks found in /etc/
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.918935   17706 server.go:182] Version: v1.9.1
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.918971   17706 feature_gate.go:220] feature gates: &{{} map[]}
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:15.919063   17706 plugins.go:101] No cloud provider specified.
Jan 10 13:27:15 GSG1PM-FT0376 kubelet[17706]: E0110 13:27:15.938538   17706 certificate_manager.go:314] Failed while requesting a signed certif
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.007500   17706 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.007907   17706 container_manager_linux.go:242] container manager verified user spe
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.007925   17706 container_manager_linux.go:247] Creating Container Manager object b
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.008075   17706 container_manager_linux.go:266] Creating device plugin manager: fal
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.008284   17706 kubelet.go:290] Adding manifest path: /etc/kubernetes/manifests
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.008350   17706 kubelet.go:313] Watching apiserver
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: E0110 13:27:16.011087   17706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Fai
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: E0110 13:27:16.014018   17706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: E0110 13:27:16.017477   17706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Fai
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: W0110 13:27:16.019501   17706 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" bu
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.019871   17706 kubelet.go:571] Hairpin mode set to "hairpin-veth"
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: W0110 13:27:16.019979   17706 cni.go:171] Unable to update cni config: No networks found in /etc/
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.020026   17706 client.go:80] Connecting to docker on unix:///var/run/docker.sock
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.020054   17706 client.go:109] Start docker client with request timeout=2m0s
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: W0110 13:27:16.022281   17706 cni.go:171] Unable to update cni config: No networks found in /etc/
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: W0110 13:27:16.030354   17706 cni.go:171] Unable to update cni config: No networks found in /etc/
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.030410   17706 docker_service.go:232] Docker cri networking managed by cni
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.046495   17706 docker_service.go:237] Docker Info: &{ID:VTV4:JBFG:M6VB:OI25:G4HW:5
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: 
Jan 10 13:27:16 GSG1PM-FT0376 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 13:27:16 GSG1PM-FT0376 systemd[1]: kubelet.service: Unit entered failed state.
Jan 10 13:27:16 GSG1PM-FT0376 systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Environment**:
- Kubernetes version (use `kubectl version`):

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):

root@GSG1PM-FT0376:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux GSG1PM-FT0376 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by dims** [comment]
@Venkat-Sudharsanam : the following two log lines are chopped off 

```
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: I0110 13:27:16.046495 17706 docker_service.go:237] Docker Info: &{ID:VTV4:JBFG:M6VB:OI25:G4HW:5
Jan 10 13:27:16 GSG1PM-FT0376 kubelet[17706]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver:
```

Can you please check what the complete lines are? I bet you are running into the problem described here : https://github.com/kubernetes/kubernetes/issues/43805

Also, please use https://github.com/kubernetes/kubeadm/ to report  kubeadm issues. i'll close this one.

/close

**Comment by Venkat-Sudharsanam** [comment]
I tried with the solution in #43805 & #53333

cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=cgroupfs"

Still getting the same error:

Below the output you have asked for:

-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished shutting down.
Jan 11 13:22:14 GSG1PM-FT0376 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.235540   28213 feature_gate.go:220] feature gates: &{{} map[]}
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.235735   28213 controller.go:114] kubelet config controller: starting controller
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.235748   28213 controller.go:118] kubelet config controller: validating combination of defaults and flags
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: W0111 13:22:14.263126   28213 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.272475   28213 server.go:182] Version: v1.9.1
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.272544   28213 feature_gate.go:220] feature gates: &{{} map[]}
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.272687   28213 plugins.go:101] No cloud provider specified.
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: W0111 13:22:14.272744   28213 server.go:328] standalone mode, no API client
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: W0111 13:22:14.293186   28213 server.go:236] No api server defined - no events will be sent to API server.
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.293203   28213 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.312565   28213 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.312623   28213 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.313172   28213 container_manager_linux.go:266] Creating device plugin manager: false
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: W0111 13:22:14.322347   28213 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.322436   28213 kubelet.go:571] Hairpin mode set to "hairpin-veth"
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.325773   28213 client.go:80] Connecting to docker on unix:///var/run/docker.sock
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.325832   28213 client.go:109] Start docker client with request timeout=2m0s
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: W0111 13:22:14.330447   28213 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.336974   28213 docker_service.go:232] Docker cri networking managed by kubernetes.io/no-op
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: I0111 13:22:14.351044   28213 docker_service.go:237] Docker Info: &{ID:PMUF:KFJE:N6ZM:EZB3:XGI2:PHD6:MRPN:H6V2:6HX7:B7SK:IDAK:4HKI Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:aufs DriverStatus:[[Root Dir /var/lib/docker/aufs] [Backing Filesystem extfs] [Dirs 0] [Dirperm1 Supported true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[]} MemoryLimit:true SwapLimit:false KernelMemory:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:15 OomKillDisable:true NGoroutines:22 SystemTime:2018-01-11T13:22:14.339342638+05:30 LoggingDriver:json-file CgroupDriver:systemd NEventsListener:0 KernelVersion:4.8.0-36-generic OperatingSystem:Ubuntu 16.04.2 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc420418e70 NCPU:4 MemTotal:7995658240 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:GSG1PM-FT0376 Labels:[] ExperimentalBuild:false ServerVersion:1.13.1 ClusterStore: ClusterAdvertise: Runtimes:map[runc:{Path:runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:0xc42022d680} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID: Expected:aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1} RuncCommit:{ID:N/A Expected:9df8b306d01f59d3a8029be411de015b7304dd8f} InitCommit:{ID:N/A Expected:949e6facb77383876aeff8a6944dde66b3089574} SecurityOptions:[name=apparmor name=seccomp,profile=default]}
Jan 11 13:22:14 GSG1PM-FT0376 kubelet[28213]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"
Jan 11 13:22:14 GSG1PM-FT0376 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Jan 11 13:22:14 GSG1PM-FT0376 systemd[1]: kubelet.service: Unit entered failed state.
Jan 11 13:22:14 GSG1PM-FT0376 systemd[1]: kubelet.service: Failed with result 'exit-code'.
~

**Comment by wrightrocket** [comment]
I kept getting the error message like: 
- There is no internet connection, so the kubelet cannot pull the following control plane images...
even though I knew I was connected to the Internet.

Although I had an entry for my hostname in /etc/hosts, this problem did not go away until I added the A and PTR records for the hostname on my DNS server, and pointed my host to it in /etc/resolv.conf.

**Comment by qiyongxiao** [comment]
Hell,guys:
   I'm the same as yours issues. And you get it out? I use docker-ce 18.0v
