### ISSUE TITLE
at large scale, kube-apiserver CPU-starves to death at 8qps of "Endpoints PATCH"

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#58050]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
@kubernetes/sig-api-machinery-bugs 
@kubernetes/sig-scalability-bugs 
/priority important-soon
FYI @shyamjvs @gmarek @wojtek-t 

**What happened**:

In a 5k-node cluster, the `kube-apiserver` running on a 64-core master, is unable to handle 8qps of `Endpoints` PATCH requests. Its CPU usage exceeds 60 cores for extended amounts of time, at which point kubelet's liveness checks fail, and apiserver is killed.

![repro](https://user-images.githubusercontent.com/489420/34760018-559eaa80-f5de-11e7-97f3-993f3286877b.png)

In the above graph, the blue line is `kube-apiserver`'s CPU usage in cores, and the red line is the request rate of `PATCH /api/v1/namespaces/default/endpoints/endpoints-test`.

The PATCH requests above are simply fliping a single `Endpoints` object back and forth between two states: one in which it has 400 fake child addresses, and another in which it has 401 of them. There are no associated `Service`s, `Deployment`s or `Pod`s. Just mutating the `Endpoints` object is enough.

I plan to run this again to collect a profile, but I suspect it will be very similar to the one in https://github.com/kubernetes/kubernetes/issues/55779#issuecomment-356282189 - i.e. CPU is burned in memory management due to the expensive `Endpoints` deep-copying when serving the 5000 watches from kube-proxy.

**What you expected to happen**:

For one thing, propagating `Endpoints` objects should scale better. Some ideas on improvements in this area are in https://github.com/kubernetes/kubernetes/issues/55779#issuecomment-354453653 and two comments which follow it, and generally revolve around caching the serialized representation of `Endpoints` objects.

I think there should also be a more generic load shedding mechanism in the API server that would protect against meltdown is these kinds of problems.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a 5000 node cluster
2. log into the master and write the following files:
```
==> aa <==
apiVersion: v1
kind: Endpoints
metadata:
  name: endpoints-test
subsets:
- addresses:

==> xx <==
  - ip: 10.64.105.3
    nodeName: e2e-test-porridge-minion-group-1-3f94
    targetRef:
      kind: Pod
      name: kube-dns-6c857864fb-zrxsn
      namespace: kube-system
      resourceVersion: "30570"
      uid: 2a89ce5a-f1f4-11e7-86f6-000000000000

==> zz <==
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---

==> stress.sh <==
#!/bin/bash

function size() {
  local len=$1
  local i
  if [ ! -e "cache-$len" ]; then
    { cat aa ;
    for i in `seq $len`
    do
      sed -e "s/000000000000/$(printf %012d $i)/" xx ;
    done;
    cat zz ; } > cache-$len
  fi
  cat cache-$len
}

( echo 400 12 2.5;
  echo 400 30 1;
  echo 400 60 0.5;
  echo 400 120 0.25;
  echo 400 240 0.125;
  echo 400 480 0.0625; ) | while read size count half_delay
do
  echo "$(date -u +'%Y-%m-%d %H:%M:%S.%3N'),$size,$count,$half_delay"
  rm -f cache-$size cache-$((size+1))
  for i in `seq $count`
  do
    size $size
    sleep $half_delay
    size $((size+1))
    sleep $half_delay
  done | kubectl apply -f - >/dev/null
done
```
3. optional: start the following command to collect CPU usage of the API server to graph it later:
```
pid=$(pgrep kube-apiserver);prev=0;while sleep 0.2;do read f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 curu curs rest < /proc/$pid/stat;cur=$((curu+curs));if ((prev));then echo "$(date -u +'%Y-%m-%d %H:%M:%S.%3N'),$cur,$prev,20.0";fi;prev=$cur;done > /tmp/cpu-$pid.csv &
```
4. bash stress.sh > 400.csv
5. optional: `kill %1` to stop CPU usage gathering

**Anything else we need to know?**:

The above may at first seem like a use case which nobody would ever exercise. However the opposite is true: an `Endpoints` is created for every `Service`, so the above scenario will happen for example when a moderately-sized (compared to cluster size) `Deployment` which exposes a `Service` is resized by a few dozen pods.

In fact this is how this problem was initially found. See https://github.com/kubernetes/kubernetes/issues/55779 for the epic story of tracking this down from an apparent TLS connection flake in a sig-cli end-to-end test. That is why the toy `Endpoints` in the repro resembles a `kube-dns` one.

I suppose the same may also happen in case of a crashlooping `Deployment`. In that case, because of https://github.com/kubernetes/kubernetes/issues/57405, API server will likely stay down indefinitely.

I think that with a larger `Endpoints` object, and/or more of them and/or at a higher request rate, this will also be reproducible on somewhat smaller clusters.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10 alpha
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Container-Optimized OS 10032.71.0
- Kernel (e.g. `uname -a`): 4.4.86+
- Install tools: kubetest --up

**Comment by porridge** [comment]
Here are a couple of profiles of a busy API server (taken with 4qps of traffic rather than 8, because usage is high enough and the server is still stable at that point). And a profile of an idle one for comparison: 
[endpoints-busy.pdf](https://github.com/kubernetes/kubernetes/files/1618266/endpoints-busy.pdf)
[endpoints-busy2.pdf](https://github.com/kubernetes/kubernetes/files/1618265/endpoints-busy2.pdf)
[endpoints-idle.pdf](https://github.com/kubernetes/kubernetes/files/1618267/endpoints-idle.pdf)

**Comment by timothysc** [comment]
An endpoint patch is essentially a broadcast to the whole system, this does not surprise me.

**Comment by jennybuckley** [comment]
cc @lavalamp

**Comment by jennybuckley** [comment]
cc @yliaog

**Comment by lavalamp** [comment]
This is a (if not "the") fundamental scaling limitation of the system right now, it needs to be fixed before we can grow beyond 5k nodes.

Endpoint controller could be modified to batch up modifications (works if it's the same endpoints changing over and over again).

Alternatively we need to batch delivery to kube-proxies.

You could try running more parallel instances of kube-apiserver to distribute the read load between them. I'm not super confident this will work but it's the only thing you can try that doesn't require Kubernetes changes.

**Comment by wojtek-t** [comment]
> This is a (if not "the") fundamental scaling limitation of the system right now, it needs to be fixed before we can grow beyond 5k nodes.

I agree it is "the".
I don't think we have any plans to grow beyond in 5k at least now.

> Endpoint controller could be modified to batch up modifications (works if it's the same endpoints changing over and over again).

It already does batching. We may just want to be more conservative with it.

> You could try running more parallel instances of kube-apiserver to distribute the read load between them. I'm not super confident this will work but it's the only thing you can try that doesn't require Kubernetes changes.

Yes this will work (if we want to workaround it somehow now).

**Comment by bgrant0607** [comment]
New Endpoint API: https://github.com/kubernetes/enhancements/issues/752

**Comment by thockin** [comment]
I'm duping this with https://github.com/kubernetes/kubernetes/issues/73324
