### ISSUE TITLE
Now  I had get csr and approved the node ,but I can't get nodes by excute"kubectl get nodes" ? why?

### ISSUE THREAD

**Issue by zhangbei59** [kubernetes/kubernetes#58059]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/sig  kubelet
/sig node

**What happened**:
I have  two nodes ,they all start kubelet service ,and the master had get csr and certificat approved them,
but now i can't got nodes? 
when i excute kubectl get nodes on the master ,i got the result "no resource found."
like this;

[root@c7test_master kubernetes]# kubectl get csr
NAME                                                   AGE       REQUESTOR           CONDITION
node-csr-kFTXK0rd8YDqLIpOJjnaK9MviixmdF2GryBOI66VtHI   21m       kubelet-bootstrap   Approved
node-csr-p4ZuR-C5f3AE_0GGzebYt2bnAeThxZJbgIfVdtxHKQY   21m       kubelet-bootstrap   Approved
[root@c7test_master kubernetes]# kubectl get nodes
No resources found.
[root@c7test_master kubernetes]# 

**What you expected to happen**:
i what to know the reason
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
client and server all are 1.9

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
centos 7.4
- Kernel (e.g. `uname -a`):
3.1
- Install tools:
- Others:
[root@c7test_master kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-03T22:18:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
[root@c7test_master kubernetes]#

**Comment by losphantom** [comment]
I got the same problem

**Comment by toddrosner** [comment]
Same problem here...
