### ISSUE TITLE
Kubernetes 1.8.3 - Error: etcdserver: mvcc: required revision has been compacted.

### ISSUE THREAD

**Issue by ricklagerweij** [kubernetes/kubernetes#58067]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
New changes performed from the master respond with:
Error: etcdserver: mvcc: required revision has been compacted.

Existing calico pod can't be scheduled, we are trying to kill the pod to let it restart since other replica's do work as expected.

**What you expected to happen**:
Pod should be deleted and restarted on the node.

**How to reproduce it (as minimally and precisely as possible)**:
Simply give the kube-apiserver the delete command for this pod in the namespace kube-system

**Anything else we need to know?**:
We have etcd clustered on virtual machines outside the cluster, this has always worked as expected.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.8.3
- Cloud provider or hardware configuration:
vSphere Virtual Machines
- OS (e.g. from /etc/os-release):
CentOS 7.4
- Kernel (e.g. `uname -a`):
4.13.12-1.el7.elrepo.x86_64
- Install tools:
Kubeadm
- Others:
Etcd version 3.2.7-1

**Comment by ricklagerweij** [comment]
@kubernetes/sig-onprem-<group-suffix>

**Comment by ricklagerweij** [comment]
Couldn't find an etcd signature

**Comment by liggitt** [comment]
"etcdserver: mvcc: required revision has been compacted." is not an error, it's an expected message when a watch is attempted to be established at a resource version that has already been compacted

without more information, this isn't recreatable or debuggable.

do you have etcd, apiserver, kubelet, or controller manager logs?

**Comment by ricklagerweij** [comment]
@liggitt thanks for your feedback, every action gives the following output;
Error from server: etcdserver: mvcc: database space exceeded

Apparently there is a 2gb quota by default which is exceeded by 2/3 of our etcd nodes (replication I assume) which causes these other issue's.

**Comment by ricklagerweij** [comment]
@liggitt currently we can't get seem to get the kube-apiserver running again after a kubelet restart, I've extended the quota backend size of etcd. 2 etcd nodes give an error on startup right now "another etcd process is using "/var/lib/etcd/member/sna p/db" and holds the file lock." These db files are 2.1gb, the other db file is 32mb on the first node, a significant difference in sizes. 
Trying to start the apiserver on the master gives the following error
Jan 11 13:53:56 master.local.cluster.domain.com kubelet[4089]: I0111 13:53:56.958643    4089 kubelet_node_status.go:280] Setting node annotation to enable volume controller attach/detach
Jan 11 13:53:56 master.local.cluster.domain.com kubelet[4089]: I0111 13:53:56.961540    4089 kubelet_node_status.go:83] Attempting to register node master.local.cluster.domain.com 
Jan 11 13:53:59 master.local.cluster.domain.com  kubelet[4089]: E0111 13:53:59.461660    4089 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-apiserver-master.local.cluster.domain.com .1508c292527da89c", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-apiserver-master.local.cluster.domain.com ", UID:"5edfdb6345b6565f5801dbc67df7158f", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}, Reason:"BackOff", Message:"Back-off restarting failed container", Source:v1.EventSource{Component:"kubelet", Host:"master.local.cluster.domain.com "}, FirstTimestamp:v1.Time{Time:time.Time{sec:63651272008, nsec:315152540, loc:(*time.Location)(0x53199c0)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63651272008, nsec:315152540, loc:(*time.Location)(0x53199c0)}}, Count:1, Type:"Warning"}': 'etcdserver: mvcc: database space exceeded' (will not retry!)

**Comment by ricklagerweij** [comment]
"Unable to register node"

**Comment by lavalamp** [comment]
Something is wrong with your etcd cluster, this is almost certainly not an apiserver problem. There's an alarm you might need to disable.

**Comment by ricklagerweij** [comment]
There was indeed an alarm, solved this issue by compacting the latest revision, defrag and turn the alarm off.

**Comment by lijinghuatongxue** [comment]
> There was indeed an alarm, solved this issue by compacting the latest revision, defrag and turn the alarm off.

how turn the alarm off ?
