### ISSUE TITLE
HA Kubernetes kube-proxy won't work correct

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#58068]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

We had the issue that we shutdown one of the HA API servers (we have 3) and the internal Service IP for the Kubernetes API stopped working. All Request to the internal service IP for the API failed. Also the iptables rules didn't get an update to send no traffic to the missing API server (also the missing API server wasn't removed as an endpoint from the API).

**What you expected to happen**:

1.) I would expect that if I shutdown one API server in a 3 API server HA setup only 1/3 of the requests are lost not all
2.) I would expect that if I kill an API server that the according API server will be removed as an endpoint (after an given waiting period).

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with 3 HA API Servers and shutdown one API server. Try now to reach the service IP of the API Server

**Anything else we need to know?**:

- Networking: Calico
- API server runs as systemd unit (not containerized)
- kube-proxy runs as container

**Environment**:
- Kubernetes version (use `kubectl version`):
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare-Metal
- OS (e.g. from /etc/os-release):
```bash
cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux kmaster-unicorn-prod-01-bs001 4.14.11-coreos #1 SMP Fri Jan 5 11:00:14 UTC 2018 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux
```
- Install tools: Matchbox from CoreOS
- Others:

**Comment by ncdc** [comment]
Have you looked at the lease endpoint reconciler? https://kubernetes.io/docs/admin/high-availability/#endpoint-reconciler

**Comment by johscheuer** [comment]
Yes, we also set the `--apiserver-count` to 3. Actually the strange thing is that all requests stop working since we would expect that ~2/3 of the requests should still work.

**Comment by ncdc** [comment]
There's no need to set `--apiserver-count` if you're using the lease endpoint reconciler. I just noticed however that your server is 1.8.5. The lease endpoint reconciler wasn't added until 1.9. You'll need to upgrade if you want to take advantage of it.
