### ISSUE TITLE
Pods can't communicate with kube-apiserver in multi master cluster

### ISSUE THREAD

**Issue by gbialas** [kubernetes/kubernetes#58071]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
I have deployed k8s cluster using magnum with 3 masters and 3 nodes:

[DEV]root@ucsubu3000:~/.kube# kubectl get nodes
NAME STATUS AGE VERSION
k8s-test-xtlwldidn5vg-master-0 Ready,SchedulingDisabled 36m v1.7.7
k8s-test-xtlwldidn5vg-master-1 Ready,SchedulingDisabled 36m v1.7.7
k8s-test-xtlwldidn5vg-master-2 Ready,SchedulingDisabled 36m v1.7.7
k8s-test-xtlwldidn5vg-minion-0 Ready 34m v1.7.7
k8s-test-xtlwldidn5vg-minion-1 Ready 34m v1.7.7
k8s-test-xtlwldidn5vg-minion-2 Ready 34m v1.7.7

But it looks like there is problem with authenticating to kube-apiserver from pods.

In coredns logs I see:

E0110 10:11:07.239014 5 reflector.go:214] github.com/coredns/coredns/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *api.Endpoints: the server has asked for the client to p
rovide credentials (get endpoints)
E0110 10:11:07.239326 5 reflector.go:214] github.com/coredns/coredns/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *api.Service: the server has asked for the client to pro
vide credentials (get services)
E0110 10:11:07.239455 5 reflector.go:214] github.com/coredns/coredns/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *api.Namespace: the server has asked for the client to p
rovide credentials (get namespaces)

In dashboard logs I see:

[DEV]root@ucsubu3000:~/.kube# kubectl -n kube-system logs kubernetes-dashboard-3804488410-xwxcv
Using HTTP port: 9090
Creating API server client for https://10.254.0.1:443
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials
Refer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md

When I deploy helm in tiller logs I see:

[tiller] 2018/01/10 10:44:07 preparing install for
[storage] 2018/01/10 10:44:07 getting release "muddled-woodpecker.v1"
[storage/driver] 2018/01/10 10:44:07 get: failed to get "muddled-woodpecker.v1": the server has asked for the client to provide credentials (get configmaps muddled-woodpecker.v1)
[tiller] 2018/01/10 10:44:07 info: generated name muddled-woodpecker is taken. Searching again.
[storage] 2018/01/10 10:44:07 getting release "guilded-fish.v1"
[storage/driver] 2018/01/10 10:44:07 get: failed to get "guilded-fish.v1": the server has asked for the client to provide credentials (get configmaps guilded-fish.v1)
[tiller] 2018/01/10 10:44:07 info: generated name guilded-fish is taken. Searching again.
[storage] 2018/01/10 10:44:07 getting release "foiled-bunny.v1"
[storage/driver] 2018/01/10 10:44:07 get: failed to get "foiled-bunny.v1": the server has asked for the client to provide credentials (get configmaps foiled-bunny.v1)
[tiller] 2018/01/10 10:44:07 info: generated name foiled-bunny is taken. Searching again.
[storage] 2018/01/10 10:44:07 getting release "yodeling-antelope.v1"
[storage/driver] 2018/01/10 10:44:07 get: failed to get "yodeling-antelope.v1": the server has asked for the client to provide credentials (get configmaps yodeling-antelope.v1)
[tiller] 2018/01/10 10:44:07 info: generated name yodeling-antelope is taken. Searching again.
[storage] 2018/01/10 10:44:07 getting release "anxious-kiwi.v1"
[storage/driver] 2018/01/10 10:44:07 get: failed to get "anxious-kiwi.v1": the server has asked for the client to provide credentials (get configmaps anxious-kiwi.v1)
[tiller] 2018/01/10 10:44:07 info: generated name anxious-kiwi is taken. Searching again.
[tiller] 2018/01/10 10:44:07 warning: No available release names found after 5 tries
[tiller] 2018/01/10 10:44:07 failed install prepare step: no available release name found
**What you expected to happen**:
Pods are working correctly.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy k8s cluster using magnum.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-10-02T10:03:16Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Openstack
- OS (e.g. from /etc/os-release): Fedora Atomic 26
- Kernel (e.g. `uname -a`): 4.13.9-200.fc26.x86_64
- Install tools:
- Others:

**Comment by dims** [comment]
@gbialas sounds like something you need to take up with the magnum team (especially the credentials references). they can escalate to this repository if needed.

/close
