### ISSUE TITLE
decrease pod with pvc failover time in case of node is shutdowned.

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#58079]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE

/kind feature

**What happened**: If kubernetes node is shutdowned, pod which contains pvc are failovered quite slowly. 

**What you expected to happen**: I except that if node is shutdowned it should not wait maxWaitForUnmountDuration in https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L201

Currently this "failover" if node is shutdowned takes something like 9-10minutes. If we could get rid of this maxWaitForUnmountDuration we could do this less than 2 minutes. So we could check in reconciler if node state is "safe" we can detach the volume without waiting 6 minutes. I would say safe state is SHUTDOWN in case of openstack and also in aws?

**How to reproduce it (as minimally and precisely as possible)**:

1. make deployment which have pvc (for instance cinder or ebs)
2. check in which node it is running, and shutdown that node from cloudprovider gui/api, in case of amazon from amazon console.
3. after sometime pod is moved to another node and started there, but it takes sometime because it waits maxWaitForUnmountDuration before it will detach the volume from shutdowned node.

**Anything else we need to know?**: this exist at least in openstack, but I think it exist in all cloudproviders. I tried to search fix for this from another cloudproviders without success.

Some discussion in another PR https://github.com/kubernetes/kubernetes/pull/56846

**Environment**:
- Kubernetes version (use `kubectl version`): master

cc @jingxu97 @gnufied

**Comment by waynr** [comment]
@zetaab Hey, I just spent a couple hours getting somewhat caught up on this and related issues/PRs. I'm wondering if you can point me to the latest viable effort toward addressing the PVC failover time in the case of node shutdown?

For reference, I'm currently working on a local branch off the `v1.9.3` tag with your https://github.com/kubernetes/kubernetes/pull/56846 fix backported and I'm seeing the timeouts mentioned here. I was considering also backporting https://github.com/kubernetes/kubernetes/pull/58169 but you mentioned there

> I think this solution is not going to work in future because kubernetes (at least in openstack) is moving to direction where node is not deleted from kube cluster if not really deleted from cloudprovider itself. 

I also see that https://github.com/kubernetes/kubernetes/pull/60009 is awaiting merge and you mention that we need the functionality introduced there to immediately detach volumes. I'm wondering if you have any work in progress on the immediate volume detach based on this PR or if https://github.com/kubernetes/kubernetes/pull/58169 (which as far as I can tell is not based on the new shutdown taint PR) is the latest effort to address the timeout issue.

If you don't have any further work in progress on top of https://github.com/kubernetes/kubernetes/pull/60009 I would be happy to help out by building on that with any advice you might have.

**Comment by zetaab** [comment]
@waynr that idea kind of hit the wall. People does not accept using node taints to detach the volume. If node is shutdown. That was our target. I do not have ideas how we could improve this situation easily.

**Comment by waynr** [comment]
Is that based on your discussion with @wlan0 here: https://github.com/zetaab/kubernetes/commit/0313435c0fe9e6ecf881b1baef973eada9e06baa#r27938288 ? Or is there additional mailing list or slack discussion I can review to get some background?

**Comment by zetaab** [comment]
https://github.com/kubernetes/kubernetes/issues/46442 that contains some discussion.

**Comment by waynr** [comment]
Thanks, I'm still a little confused as to whether https://github.com/kubernetes/kubernetes/issues/58635 supercedes the older https://github.com/kubernetes/kubernetes/issues/46442 but I feel like I'm starting to understand the issues involved a little better.

**Comment by dev00** [comment]
With version 1.10.5 I see a rather interesting behaviour:
Draining a node is quite fast, volumes are rescheduled and reattached within a minute (so our OpenStack is not the issue).

When shutting down a node (without draining it, simulating a node failure) we see the pods being rescheduled as soon as the node is removed from the node list - however, the volume is not rescheduled until about 5 minutes. This makes so sense, as a pod with a pv will never be able to start without the pv (means, until the pv is attached).

I don't know wether this is considered a bug or not, this should be decided by more experienced people ;)

**Comment by waynr** [comment]
@dev00 https://github.com/kubernetes/kubernetes/pull/64930 should address the problem you are seeing.
