### ISSUE TITLE
Configmap control characters YAML/JSON+JSON/YAML conversion error

### ISSUE THREAD

**Issue by RobertDiebels** [kubernetes/kubernetes#58073]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Kubectl throws an error about control characters when converting JSON to YAML or YAML to JSON.

**What you expected to happen**:
I expect that the conversion to run properly. I'm mounting the ConfigMap as a volume into a Deployment. The data-string a file can contain should not be limited by conversion from one format to another.
Otherwise I would expect the `create configmap` to throw an error or some kind of notification that control characters shouldn't be present in files that are being converted to a ConfigMap. Or anything before a conversion takes place.

**How to reproduce it (as minimally and precisely as possible)**:
_JSON-YAML_
1. Create a file with control characters in it.
2. Run `kubectl create configmap genesis --from-file /directory/your/file/is/in`
3. Run 'kubectl get configmap genesis -o yaml'
4. Error message is shown 'error: error converting JSON to YAML: %!(EXTRA *errors.errorString=yaml: control characters are not allowed)'

_YAML-JSON_
1. Create a yaml-file
2. Create a ConfigMap configuration within the file.
3. Create a data-key (mine is called genesis.block)
4. Add a data-value containing control characters.
5. Run `kubectl create -f /yaml/file`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): Windows 10
- Kernel (e.g. `uname -a`):  n/a
- Install tools: minikube
- Others:

**Comment by RobertDiebels** [comment]
@kubernetes/sig-apps-bugs
@kubernets/sig-cli-bugs

**Comment by liggitt** [comment]
> Add a data-value containing control characters.

configmaps can only contain utf-8 content, not binary content.

see https://github.com/kubernetes/kubernetes/issues/32432
