### ISSUE TITLE
Separate GCE Instance Name from Kubelet hostname

### ISSUE THREAD

**Issue by akshaymankar** [kubernetes/kubernetes#58084]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
On GCP, when you set --hostname-override, the cloud provider assumes that it is instance name of the VM.

**What you expected to happen**:
I expect `kubelet` to have separate parameter to provide cloud ID to the GCE cloud provider so that I can generate kubelet certificate before actually starting the worker. 

**How to reproduce it (as minimally and precisely as possible)**:
On GCP, start kubelet with --hostname-override which is not the same as GCP instance name of the VM, but is resolvable by some DNS which is configured on the master.

**Anything else we need to know?**:
Other cloud providers ( I checked AWS, vSphere and Openstack) do not make such an assumption. They source the cloud ID from other places. Maybe the behaviour should be kept consistent.

Here are the possible places of change:
- [Assumption that GCE Instance name is same as node name](https://github.com/kubernetes/kubernetes/blob/2f39e8a04550aff88537c608edea1faf2b088678/pkg/cloudprovider/providers/gce/gce_util.go#L128-L132
)
- [Assumption that hostname override should change node name](https://github.com/kubernetes/kubernetes/blob/2f39e8a04550aff88537c608edea1faf2b088678/pkg/kubelet/kubelet.go#L360-L362)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Ubuntu Trusty
- Kernel (e.g. `uname -a`): Linux 4.4.0-103-generic
- Install tools: CFCR (Kubo) 
- Others: N/A

**Comment by mtaufen** [comment]
Some additional context from an old Slack discussion that fizzled out (my fault, I never followed up):
@akshaymankar 
>The `--hostname-override` flag on kubelet is used for `kubeapi-server` to `kubelet` communication. The overridden hostname also becomes the node name. And the GCE cloud provider assumes that the node name is also the cloud id of the VM.  
>
>This disables me from generating kubelet certificates before creating the VM.
>
>Ideally, the `kubelet` would take another flag which the cloud provider can use to locate the VM in the cloud. This allows us to use `--hostname-override` as the correct dns name e.g `node-1.worker.internal` instead of `vm-guid`.
>
>Would somebody here be able to comment on this?

@mtaufen
>So if I'm reading that right, you want to set hostname and node name separately? And the avenue is basically adding a --cloud-node-name flag? It sounds pretty reasonable on the surface but I have to go re-read the --hostname-override related code to refresh my memory of how all that works.

@akshaymankar 
>Hi, yes either of the two solutions will work for me:
>- setting node name and hostname separately, or
>- setting node name and cloud id in gcp cloud provider separately.
>
>The second solution makes more sense to me because other cloud providers don't make this assumption. They figure out cloud id from other means.
>
>This is the place where that assumption is made in the gce cloud provider: https://github.com/kubernetes/kubernetes/blob/v1.9.1/pkg/cloudprovider/providers/gce/gce_util.go#L130

**Comment by mtaufen** [comment]
I'm assuming node name always matches the name of the corresponding Node object in the API. Is this correct?

**Comment by mtaufen** [comment]
@thockin (if you remember) were things just done this way for expedience? It sounds like:
- `--hostname-override` (just overrides hostname)
- `--nodename-override` (just overrides node name)
- `--cloud-id-override` (just overrides cloud-id)

would be the solution most isomorphic to the configuration space (I haven't read the code in a while, though...).

**Comment by thockin** [comment]
I have low recollection of this area, sorry.  What you describe sounds reasonable, but do we need them all?

**Comment by akshaymankar** [comment]
I like the idea of three separate flags, I will try to make a PR with that implemented.

**Comment by akshaymankar** [comment]
**Update**: As a first step, we (me and @mordebites) are working on separating `instance-name` from being same as `node-name`. We considered using `--cloud-id-override`, but it seems like every cloud provider has a different way of figuring this out. And having a flag doesn't necessarily make sense.

So, we think it would be best to take `instance-name` from cloud-config.ini passed as `--cloud-config`. 

We're planning to use this to update `spec.providerID` property of node, so `kube-controller-manager` can also figure out the `instance-name` properly.

We'd love to hear what you think about this.

**Comment by akshaymankar** [comment]
**Update** We were able to move forward with the work. We decided to not add a flag for `--cloud-id-override` as the problem is limited to GCE. So we chose to put it as a configuration in the cloud config. We've called it `instance-name`. 

We have made [this commit](https://github.com/CFCR/kubernetes/commit/2b206579e5061ae1d0d451dc4df0911c3ac11b95). We'd love to get some feedback from anybody more well versed with the code around GCE cloud provider/kubelet. 

@mtaufen, @thockin Could you please give us some feedback on the solution?

**Comment by mikedanese** [comment]
> This disables me from generating kubelet certificates before creating the VM.

I don't understand this. Is this because you don't know the VM name before you create the VM?

**Comment by akshaymankar** [comment]
Yes, we are using [BOSH](https://github.com/cloudfoundry/bosh) to spin up VMs, it generates a uuid for a every VM. So, we cannot predict the name of the VM before creating it.

**Comment by mikedanese** [comment]
I think what your after is https://github.com/kubernetes/community/pull/602. Would getting that to beta fix your issue?

**Comment by akshaymankar** [comment]
Ideally yes, TLS bootstrapping server certificates will work. But I am not sure how the automatic authorization of the CSR would work. Because then that component would need to know about nodes and their instance-names.
