### ISSUE TITLE
CRI: Debug API revisited

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#58102]
When Kublet and crictl get debug information the information is specified in a status response struct, for example: 
 ```
 type ContainerStatusResponse struct {
  	// Status of the container.
  	Status *ContainerStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
 	// Info is extra information of the Container. The key could be abitrary string, and
 	// value should be in json format. The information could include anything useful for
 	// debug, e.g. pid for linux container based container runtime.
 	// It should only be returned non-empty when Verbose is true.
 	Info map[string]string `protobuf:"bytes,2,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
 }
```
The info map portion of these structs was implemented in pr #53965. This has proven useful, however if more than one piece of information is added to the Info map, the order of the output is not guaranteed because go maps do not preserve order. This causes data to become hidden when the amount of information placed into the Info map is large. 

Sorting the output was considered but the desired order may not be the sort order. 

Specifying predefined static sets of key values was considered but there are multiple CRI implementation types so just one set of keys & values would not suffice and the target will be constantly moving. Note: It is suggested that the CRI implementations begin to separately specify (at least for their type of CRI implementation) standardized keys, sequence, and structures for values. Then if agreed these can be proposed later on as additions to this CRI api. But this is out of scope for now.

The CRI tools and CRI implementation teams have had some discussion on this topic and one proposal is we use an array of name value pairs instead of the Info map.

Option 1: add an array of key value pairs `Detail [][]string{}` or via array of structs with key value pairs inside and deprecate Info map (avoids breaking change allows order to be set)
Option 2: add an array of keys to specify order for the map `Keys []string{}` (avoids breaking change allows order to be set)
Option 3: do nothing forcing runtimes to create one mega structure in the map if they want to set order)
Option 4: do option 1 but swap Info map for the Info array of key value pairs (since breaking changes are allowed)

@Random-Liu @yujuhong @feiskyer @abhi @mrunalp @runcom
/cc @dchen1107
/cc @kubernetes/sig-node-api-reviews

**Comment by abhi** [comment]
@mikebrow can't we do something like this and implement Len and Swap? So CRI implementations can defined their desired order ? 
 
```
type desiredOrder struct{ info map[string]string }

func (d desiredOrder) Less(i, j string) bool { 
....
}

sort.Sort(desiredOrder{info}) 
```

**Comment by mikebrow** [comment]
@abhi option 2 above is for the implementation to define their desired order via an array of keys that we would iterate through when we generate the output.

**Comment by Random-Liu** [comment]
@mikebrow I prefer option 1. Given our discussion, we are still at the stage that we can make non-backward-compatible change to do things right. And I believe only `cri-containerd` implements the debug field today.

/cc @mrunalp @runcom 
/cc @yujuhong

**Comment by mikebrow** [comment]
Sure, if we are allowed to break backward compatibility let's go with option 1 and use the same variable name. As for array of KeyValue struct vs [][]string{}, that works for me,.. and that gives the ability to easily add additional field(s) later on.

**Comment by Random-Liu** [comment]
Actually another option is that, if people are fine with the current one field approach, we can keep current API, which avoids breaking change.

Here is an example of `crictl inspect` output today:

<p>
  <details>
    <summary>crictl inspect output exapmle</summary><p>

    {
      "status": {
        "id": "6dce0bc1e1ec1a0c55db8d43097b1091a12e9160c5c2a06f3b2175f89d7c0154",
        "metadata": {
          "attempt": 0,
          "name": "fluentd-gcp"
        },
        "state": "CONTAINER_RUNNING",
        "createdAt": "2018-01-09T06:22:17.810574637Z",
        "startedAt": "2018-01-09T06:22:17.983425Z",
        "finishedAt": "1970-01-01T00:00:00Z",
        "exitCode": 0,
        "image": {
          "image": "gcr.io/google-containers/fluentd-gcp:2.0.11"
        },
        "imageRef": "gcr.io/google-containers/fluentd-gcp@sha256:b39915927d0e41c4cbd71e41f17c42e2adac70012f45805890e033debb4fa1e1",
        "reason": "",
        "message": "",
        "labels": {
          "io.kubernetes.container.name": "fluentd-gcp",
          "io.kubernetes.pod.name": "fluentd-gcp-v2.0.11-7f9jb",
          "io.kubernetes.pod.namespace": "kube-system",
          "io.kubernetes.pod.uid": "6925b67a-f505-11e7-b364-42010a800002"
        },
        "annotations": {
          "io.kubernetes.container.hash": "3cf903c9",
          "io.kubernetes.container.restartCount": "0",
          "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
          "io.kubernetes.container.terminationMessagePolicy": "File",
          "io.kubernetes.pod.terminationGracePeriod": "30"
        },
        "mounts": [
          {
            "containerPath": "/var/log",
            "hostPath": "/var/log",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": false,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/var/lib/docker/containers",
            "hostPath": "/var/lib/docker/containers",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": true,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/host/lib",
            "hostPath": "/usr/lib64",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": true,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/etc/fluent/config.d",
            "hostPath": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~configmap/config-volume",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": false,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/var/run/secrets/kubernetes.io/serviceaccount",
            "hostPath": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~secret/fluentd-gcp-token-dqgfg",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": true,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/etc/hosts",
            "hostPath": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/etc-hosts",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": false,
            "selinuxRelabel": false
          },
          {
            "containerPath": "/dev/termination-log",
            "hostPath": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/containers/fluentd-gcp/3f0fd76a",
            "propagation": "PROPAGATION_PRIVATE",
            "readonly": false,
            "selinuxRelabel": false
          }
        ],
        "logPath": "/var/log/pods/6925b67a-f505-11e7-b364-42010a800002/fluentd-gcp_0.log"
      },
      "info": {
        "sandboxID": "6825b7bd202afb897e1fd027029bf8dd6861efdd66fcb186968313f02cde557a",
        "pid": 8643,
        "removing": false,
        "snapshotKey": "6dce0bc1e1ec1a0c55db8d43097b1091a12e9160c5c2a06f3b2175f89d7c0154",
        "snapshotter": "overlayfs",
        "config": {
          "metadata": {
            "name": "fluentd-gcp"
          },
          "image": {
            "image": "sha256:a6c1ff9366b5329f9137be403afd7443bee449ac7c50151e85a4cd968ff57daa"
          },
          "envs": [
            {
              "key": "FLUENTD_ARGS",
              "value": "--no-supervisor -q"
            },
            {
              "key": "METRICS_SERVER_PORT",
              "value": "tcp://10.0.2.70:443"
            },
            {
              "key": "KUBERNETES_SERVICE_PORT",
              "value": "443"
            },
            {
              "key": "MONITORING_INFLUXDB_SERVICE_PORT_HTTP",
              "value": "8083"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8086_TCP_ADDR",
              "value": "10.0.57.7"
            },
            {
              "key": "KUBE_DNS_PORT_53_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "KUBE_DNS_PORT_53_TCP_ADDR",
              "value": "10.0.0.10"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_PORT_80_TCP_ADDR",
              "value": "10.0.124.127"
            },
            {
              "key": "HEAPSTER_PORT_80_TCP_PORT",
              "value": "80"
            },
            {
              "key": "KUBE_DNS_PORT_53_UDP",
              "value": "udp://10.0.0.10:53"
            },
            {
              "key": "KUBE_DNS_PORT_53_TCP",
              "value": "tcp://10.0.0.10:53"
            },
            {
              "key": "HEAPSTER_PORT_80_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "KUBE_DNS_PORT_53_UDP_PORT",
              "value": "53"
            },
            {
              "key": "KUBE_DNS_PORT_53_TCP_PORT",
              "value": "53"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8083_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "METRICS_SERVER_PORT_443_TCP",
              "value": "tcp://10.0.2.70:443"
            },
            {
              "key": "KUBERNETES_DASHBOARD_PORT_443_TCP",
              "value": "tcp://10.0.47.132:443"
            },
            {
              "key": "KUBERNETES_SERVICE_HOST",
              "value": "10.0.0.1"
            },
            {
              "key": "HEAPSTER_PORT_80_TCP",
              "value": "tcp://10.0.189.28:80"
            },
            {
              "key": "KUBE_DNS_PORT_53_UDP_ADDR",
              "value": "10.0.0.10"
            },
            {
              "key": "METRICS_SERVER_PORT_443_TCP_ADDR",
              "value": "10.0.2.70"
            },
            {
              "key": "MONITORING_GRAFANA_PORT_80_TCP",
              "value": "tcp://10.0.233.246:80"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_PORT_80_TCP",
              "value": "tcp://10.0.124.127:80"
            },
            {
              "key": "KUBE_DNS_SERVICE_PORT_DNS",
              "value": "53"
            },
            {
              "key": "CALICO_TYPHA_PORT_5473_TCP_PORT",
              "value": "5473"
            },
            {
              "key": "MONITORING_GRAFANA_SERVICE_PORT",
              "value": "80"
            },
            {
              "key": "KUBERNETES_DASHBOARD_PORT_443_TCP_PORT",
              "value": "443"
            },
            {
              "key": "HEAPSTER_SERVICE_PORT",
              "value": "80"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8083_TCP",
              "value": "tcp://10.0.57.7:8083"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_PORT",
              "value": "tcp://10.0.124.127:80"
            },
            {
              "key": "KUBERNETES_DASHBOARD_SERVICE_PORT",
              "value": "443"
            },
            {
              "key": "KUBE_DNS_SERVICE_PORT",
              "value": "53"
            },
            {
              "key": "MONITORING_INFLUXDB_SERVICE_HOST",
              "value": "10.0.57.7"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT",
              "value": "tcp://10.0.57.7:8083"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8083_TCP_PORT",
              "value": "8083"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8083_TCP_ADDR",
              "value": "10.0.57.7"
            },
            {
              "key": "CALICO_TYPHA_SERVICE_HOST",
              "value": "10.0.17.249"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PORT",
              "value": "80"
            },
            {
              "key": "KUBERNETES_PORT_443_TCP",
              "value": "tcp://10.0.0.1:443"
            },
            {
              "key": "KUBE_DNS_PORT",
              "value": "udp://10.0.0.10:53"
            },
            {
              "key": "MONITORING_GRAFANA_PORT_80_TCP_PORT",
              "value": "80"
            },
            {
              "key": "HEAPSTER_PORT_80_TCP_ADDR",
              "value": "10.0.189.28"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8086_TCP",
              "value": "tcp://10.0.57.7:8086"
            },
            {
              "key": "KUBERNETES_DASHBOARD_PORT_443_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "KUBERNETES_PORT_443_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "HEAPSTER_SERVICE_HOST",
              "value": "10.0.189.28"
            },
            {
              "key": "MONITORING_INFLUXDB_SERVICE_PORT",
              "value": "8083"
            },
            {
              "key": "METRICS_SERVER_PORT_443_TCP_PORT",
              "value": "443"
            },
            {
              "key": "MONITORING_GRAFANA_PORT",
              "value": "tcp://10.0.233.246:80"
            },
            {
              "key": "MONITORING_GRAFANA_PORT_80_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "KUBERNETES_DASHBOARD_SERVICE_HOST",
              "value": "10.0.47.132"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8086_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "CALICO_TYPHA_PORT_5473_TCP",
              "value": "tcp://10.0.17.249:5473"
            },
            {
              "key": "CALICO_TYPHA_PORT_5473_TCP_ADDR",
              "value": "10.0.17.249"
            },
            {
              "key": "METRICS_SERVER_PORT_443_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "HEAPSTER_PORT",
              "value": "tcp://10.0.189.28:80"
            },
            {
              "key": "CALICO_TYPHA_SERVICE_PORT",
              "value": "5473"
            },
            {
              "key": "METRICS_SERVER_SERVICE_HOST",
              "value": "10.0.2.70"
            },
            {
              "key": "METRICS_SERVER_SERVICE_PORT",
              "value": "443"
            },
            {
              "key": "MONITORING_GRAFANA_SERVICE_HOST",
              "value": "10.0.233.246"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_SERVICE_PORT",
              "value": "80"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_SERVICE_HOST",
              "value": "10.0.124.127"
            },
            {
              "key": "KUBERNETES_DASHBOARD_PORT",
              "value": "tcp://10.0.47.132:443"
            },
            {
              "key": "KUBE_DNS_PORT_53_UDP_PROTO",
              "value": "udp"
            },
            {
              "key": "CALICO_TYPHA_PORT_5473_TCP_PROTO",
              "value": "tcp"
            },
            {
              "key": "CALICO_TYPHA_SERVICE_PORT_CALICO_TYPHA",
              "value": "5473"
            },
            {
              "key": "KUBERNETES_PORT_443_TCP_ADDR",
              "value": "10.0.0.1"
            },
            {
              "key": "KUBE_DNS_SERVICE_PORT_DNS_TCP",
              "value": "53"
            },
            {
              "key": "MONITORING_INFLUXDB_SERVICE_PORT_API",
              "value": "8086"
            },
            {
              "key": "MONITORING_INFLUXDB_PORT_8086_TCP_PORT",
              "value": "8086"
            },
            {
              "key": "KUBERNETES_DASHBOARD_PORT_443_TCP_ADDR",
              "value": "10.0.47.132"
            },
            {
              "key": "KUBERNETES_SERVICE_PORT_HTTPS",
              "value": "443"
            },
            {
              "key": "MONITORING_GRAFANA_PORT_80_TCP_ADDR",
              "value": "10.0.233.246"
            },
            {
              "key": "KUBERNETES_PORT_443_TCP_PORT",
              "value": "443"
            },
            {
              "key": "KUBE_DNS_SERVICE_HOST",
              "value": "10.0.0.10"
            },
            {
              "key": "CALICO_TYPHA_PORT",
              "value": "tcp://10.0.17.249:5473"
            },
            {
              "key": "DEFAULT_HTTP_BACKEND_SERVICE_PORT_HTTP",
              "value": "80"
            },
            {
              "key": "KUBERNETES_PORT",
              "value": "tcp://10.0.0.1:443"
            }
          ],
          "mounts": [
            {
              "container_path": "/var/log",
              "host_path": "/var/log"
            },
            {
              "container_path": "/var/lib/docker/containers",
              "host_path": "/var/lib/docker/containers",
              "readonly": true
            },
            {
              "container_path": "/host/lib",
              "host_path": "/usr/lib64",
              "readonly": true
            },
            {
              "container_path": "/etc/fluent/config.d",
              "host_path": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~configmap/config-volume"
            },
            {
              "container_path": "/var/run/secrets/kubernetes.io/serviceaccount",
              "host_path": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~secret/fluentd-gcp-token-dqgfg",
              "readonly": true
            },
            {
              "container_path": "/etc/hosts",
              "host_path": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/etc-hosts"
            },
            {
              "container_path": "/dev/termination-log",
              "host_path": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/containers/fluentd-gcp/3f0fd76a"
            }
          ],
          "labels": {
            "io.kubernetes.container.name": "fluentd-gcp",
            "io.kubernetes.pod.name": "fluentd-gcp-v2.0.11-7f9jb",
            "io.kubernetes.pod.namespace": "kube-system",
            "io.kubernetes.pod.uid": "6925b67a-f505-11e7-b364-42010a800002"
          },
          "annotations": {
            "io.kubernetes.container.hash": "3cf903c9",
            "io.kubernetes.container.restartCount": "0",
            "io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
            "io.kubernetes.container.terminationMessagePolicy": "File",
            "io.kubernetes.pod.terminationGracePeriod": "30"
          },
          "log_path": "fluentd-gcp_0.log",
          "linux": {
            "resources": {
              "cpu_shares": 102,
              "memory_limit_in_bytes": 314572800,
              "oom_score_adj": 947
            },
            "security_context": {
              "namespace_options": {},
              "run_as_user": {}
            }
          }
        },
        "runtimeSpec": {
          "ociVersion": "1.0.0",
          "process": {
            "user": {
              "uid": 0,
              "gid": 0
            },
            "args": [
              "/bin/sh",
              "-c",
              "/run.sh $FLUENTD_ARGS"
            ],
            "env": [
              "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
              "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1",
              "FLUENTD_ARGS=--no-supervisor -q",
              "METRICS_SERVER_PORT=tcp://10.0.2.70:443",
              "KUBERNETES_SERVICE_PORT=443",
              "MONITORING_INFLUXDB_SERVICE_PORT_HTTP=8083",
              "MONITORING_INFLUXDB_PORT_8086_TCP_ADDR=10.0.57.7",
              "KUBE_DNS_PORT_53_TCP_PROTO=tcp",
              "KUBE_DNS_PORT_53_TCP_ADDR=10.0.0.10",
              "DEFAULT_HTTP_BACKEND_PORT_80_TCP_ADDR=10.0.124.127",
              "HEAPSTER_PORT_80_TCP_PORT=80",
              "KUBE_DNS_PORT_53_UDP=udp://10.0.0.10:53",
              "KUBE_DNS_PORT_53_TCP=tcp://10.0.0.10:53",
              "HEAPSTER_PORT_80_TCP_PROTO=tcp",
              "KUBE_DNS_PORT_53_UDP_PORT=53",
              "KUBE_DNS_PORT_53_TCP_PORT=53",
              "MONITORING_INFLUXDB_PORT_8083_TCP_PROTO=tcp",
              "METRICS_SERVER_PORT_443_TCP=tcp://10.0.2.70:443",
              "KUBERNETES_DASHBOARD_PORT_443_TCP=tcp://10.0.47.132:443",
              "KUBERNETES_SERVICE_HOST=10.0.0.1",
              "HEAPSTER_PORT_80_TCP=tcp://10.0.189.28:80",
              "KUBE_DNS_PORT_53_UDP_ADDR=10.0.0.10",
              "METRICS_SERVER_PORT_443_TCP_ADDR=10.0.2.70",
              "MONITORING_GRAFANA_PORT_80_TCP=tcp://10.0.233.246:80",
              "DEFAULT_HTTP_BACKEND_PORT_80_TCP=tcp://10.0.124.127:80",
              "KUBE_DNS_SERVICE_PORT_DNS=53",
              "CALICO_TYPHA_PORT_5473_TCP_PORT=5473",
              "MONITORING_GRAFANA_SERVICE_PORT=80",
              "KUBERNETES_DASHBOARD_PORT_443_TCP_PORT=443",
              "HEAPSTER_SERVICE_PORT=80",
              "MONITORING_INFLUXDB_PORT_8083_TCP=tcp://10.0.57.7:8083",
              "DEFAULT_HTTP_BACKEND_PORT=tcp://10.0.124.127:80",
              "KUBERNETES_DASHBOARD_SERVICE_PORT=443",
              "KUBE_DNS_SERVICE_PORT=53",
              "MONITORING_INFLUXDB_SERVICE_HOST=10.0.57.7",
              "MONITORING_INFLUXDB_PORT=tcp://10.0.57.7:8083",
              "MONITORING_INFLUXDB_PORT_8083_TCP_PORT=8083",
              "MONITORING_INFLUXDB_PORT_8083_TCP_ADDR=10.0.57.7",
              "CALICO_TYPHA_SERVICE_HOST=10.0.17.249",
              "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PROTO=tcp",
              "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PORT=80",
              "KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443",
              "KUBE_DNS_PORT=udp://10.0.0.10:53",
              "MONITORING_GRAFANA_PORT_80_TCP_PORT=80",
              "HEAPSTER_PORT_80_TCP_ADDR=10.0.189.28",
              "MONITORING_INFLUXDB_PORT_8086_TCP=tcp://10.0.57.7:8086",
              "KUBERNETES_DASHBOARD_PORT_443_TCP_PROTO=tcp",
              "KUBERNETES_PORT_443_TCP_PROTO=tcp",
              "HEAPSTER_SERVICE_HOST=10.0.189.28",
              "MONITORING_INFLUXDB_SERVICE_PORT=8083",
              "METRICS_SERVER_PORT_443_TCP_PORT=443",
              "MONITORING_GRAFANA_PORT=tcp://10.0.233.246:80",
              "MONITORING_GRAFANA_PORT_80_TCP_PROTO=tcp",
              "KUBERNETES_DASHBOARD_SERVICE_HOST=10.0.47.132",
              "MONITORING_INFLUXDB_PORT_8086_TCP_PROTO=tcp",
              "CALICO_TYPHA_PORT_5473_TCP=tcp://10.0.17.249:5473",
              "CALICO_TYPHA_PORT_5473_TCP_ADDR=10.0.17.249",
              "METRICS_SERVER_PORT_443_TCP_PROTO=tcp",
              "HEAPSTER_PORT=tcp://10.0.189.28:80",
              "CALICO_TYPHA_SERVICE_PORT=5473",
              "METRICS_SERVER_SERVICE_HOST=10.0.2.70",
              "METRICS_SERVER_SERVICE_PORT=443",
              "MONITORING_GRAFANA_SERVICE_HOST=10.0.233.246",
              "DEFAULT_HTTP_BACKEND_SERVICE_PORT=80",
              "DEFAULT_HTTP_BACKEND_SERVICE_HOST=10.0.124.127",
              "KUBERNETES_DASHBOARD_PORT=tcp://10.0.47.132:443",
              "KUBE_DNS_PORT_53_UDP_PROTO=udp",
              "CALICO_TYPHA_PORT_5473_TCP_PROTO=tcp",
              "CALICO_TYPHA_SERVICE_PORT_CALICO_TYPHA=5473",
              "KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1",
              "KUBE_DNS_SERVICE_PORT_DNS_TCP=53",
              "MONITORING_INFLUXDB_SERVICE_PORT_API=8086",
              "MONITORING_INFLUXDB_PORT_8086_TCP_PORT=8086",
              "KUBERNETES_DASHBOARD_PORT_443_TCP_ADDR=10.0.47.132",
              "KUBERNETES_SERVICE_PORT_HTTPS=443",
              "MONITORING_GRAFANA_PORT_80_TCP_ADDR=10.0.233.246",
              "KUBERNETES_PORT_443_TCP_PORT=443",
              "KUBE_DNS_SERVICE_HOST=10.0.0.10",
              "CALICO_TYPHA_PORT=tcp://10.0.17.249:5473",
              "DEFAULT_HTTP_BACKEND_SERVICE_PORT_HTTP=80",
              "KUBERNETES_PORT=tcp://10.0.0.1:443"
            ],
            "cwd": "/",
            "capabilities": {
              "bounding": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_FSETID",
                "CAP_FOWNER",
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETFCAP",
                "CAP_SETPCAP",
                "CAP_NET_BIND_SERVICE",
                "CAP_SYS_CHROOT",
                "CAP_KILL",
                "CAP_AUDIT_WRITE"
              ],
              "effective": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_FSETID",
                "CAP_FOWNER",
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETFCAP",
                "CAP_SETPCAP",
                "CAP_NET_BIND_SERVICE",
                "CAP_SYS_CHROOT",
                "CAP_KILL",
                "CAP_AUDIT_WRITE"
              ],
              "inheritable": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_FSETID",
                "CAP_FOWNER",
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETFCAP",
                "CAP_SETPCAP",
                "CAP_NET_BIND_SERVICE",
                "CAP_SYS_CHROOT",
                "CAP_KILL",
                "CAP_AUDIT_WRITE"
              ],
              "permitted": [
                "CAP_CHOWN",
                "CAP_DAC_OVERRIDE",
                "CAP_FSETID",
                "CAP_FOWNER",
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_SETGID",
                "CAP_SETUID",
                "CAP_SETFCAP",
                "CAP_SETPCAP",
                "CAP_NET_BIND_SERVICE",
                "CAP_SYS_CHROOT",
                "CAP_KILL",
                "CAP_AUDIT_WRITE"
              ]
            },
            "apparmorProfile": "cri-containerd.apparmor.d",
            "oomScoreAdj": 947
          },
          "root": {
            "path": "rootfs"
          },
          "mounts": [
            {
              "destination": "/proc",
              "type": "proc",
              "source": "proc"
            },
            {
              "destination": "/dev",
              "type": "tmpfs",
              "source": "tmpfs",
              "options": [
                "nosuid",
                "strictatime",
                "mode=755",
                "size=65536k"
              ]
            },
            {
              "destination": "/dev/pts",
              "type": "devpts",
              "source": "devpts",
              "options": [
                "nosuid",
                "noexec",
                "newinstance",
                "ptmxmode=0666",
                "mode=0620",
                "gid=5"
              ]
            },
            {
              "destination": "/dev/shm",
              "type": "tmpfs",
              "source": "shm",
              "options": [
                "nosuid",
                "noexec",
                "nodev",
                "mode=1777",
                "size=65536k"
              ]
            },
            {
              "destination": "/dev/mqueue",
              "type": "mqueue",
              "source": "mqueue",
              "options": [
                "nosuid",
                "noexec",
                "nodev"
              ]
            },
            {
              "destination": "/sys",
              "type": "sysfs",
              "source": "sysfs",
              "options": [
                "nosuid",
                "noexec",
                "nodev",
                "ro"
              ]
            },
            {
              "destination": "/sys/fs/cgroup",
              "type": "cgroup",
              "source": "cgroup",
              "options": [
                "nosuid",
                "noexec",
                "nodev",
                "relatime",
                "ro"
              ]
            },
            {
              "destination": "/etc/resolv.conf",
              "type": "bind",
              "source": "/var/lib/cri-containerd/sandboxes/6825b7bd202afb897e1fd027029bf8dd6861efdd66fcb186968313f02cde557a/resolv.conf",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            },
            {
              "destination": "/dev/shm",
              "type": "bind",
              "source": "/var/lib/cri-containerd/sandboxes/6825b7bd202afb897e1fd027029bf8dd6861efdd66fcb186968313f02cde557a/shm",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            },
            {
              "destination": "/var/log",
              "type": "bind",
              "source": "/var/log",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            },
            {
              "destination": "/var/lib/docker/containers",
              "type": "bind",
              "source": "/var/lib/docker/containers",
              "options": [
                "rbind",
                "rprivate",
                "ro"
              ]
            },
            {
              "destination": "/host/lib",
              "type": "bind",
              "source": "/usr/lib64",
              "options": [
                "rbind",
                "rprivate",
                "ro"
              ]
            },
            {
              "destination": "/etc/fluent/config.d",
              "type": "bind",
              "source": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~configmap/config-volume",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            },
            {
              "destination": "/var/run/secrets/kubernetes.io/serviceaccount",
              "type": "bind",
              "source": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/volumes/kubernetes.io~secret/fluentd-gcp-token-dqgfg",
              "options": [
                "rbind",
                "rprivate",
                "ro"
              ]
            },
            {
              "destination": "/etc/hosts",
              "type": "bind",
              "source": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/etc-hosts",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            },
            {
              "destination": "/dev/termination-log",
              "type": "bind",
              "source": "/var/lib/kubelet/pods/6925b67a-f505-11e7-b364-42010a800002/containers/fluentd-gcp/3f0fd76a",
              "options": [
                "rbind",
                "rprivate",
                "rw"
              ]
            }
          ],
          "linux": {
            "resources": {
              "devices": [
                {
                  "allow": false,
                  "access": "rwm"
                }
              ],
              "memory": {
                "limit": 314572800
              },
              "cpu": {
                "shares": 102,
                "quota": 0,
                "period": 0
              }
            },
            "cgroupsPath": "/kubepods/burstable/pod6925b67a-f505-11e7-b364-42010a800002/6dce0bc1e1ec1a0c55db8d43097b1091a12e9160c5c2a06f3b2175f89d7c0154",
            "namespaces": [
              {
                "type": "pid"
              },
              {
                "type": "ipc",
                "path": "/proc/7616/ns/ipc"
              },
              {
                "type": "uts",
                "path": "/proc/7616/ns/uts"
              },
              {
                "type": "mount"
              },
              {
                "type": "network",
                "path": "/proc/7616/ns/net"
              }
            ],
            "maskedPaths": [
              "/proc/kcore",
              "/proc/latency_stats",
              "/proc/timer_list",
              "/proc/timer_stats",
              "/proc/sched_debug",
              "/sys/firmware",
              "/proc/scsi"
            ],
            "readonlyPaths": [
              "/proc/asound",
              "/proc/bus",
              "/proc/fs",
              "/proc/irq",
              "/proc/sys",
              "/proc/sysrq-trigger"
            ]
          }
        }
      }
    }

  </p></details>
</p>

**Comment by feiskyer** [comment]
What about just keeping current API and outputs the info alphabetically on the keys? We may add some helpers in crictl to facilitate users finding specific information, e.g. by keys or jsonpath?

**Comment by mikebrow** [comment]
The issue with alphabetic is alphabetic may be the worst sequence to use. Gives no control over to the runtimes other than adding alphabetic prefixes to the keys, or doing what we had to do in cri-containerd and creating one mega entry in the map.

**Comment by mikebrow** [comment]
Ok updated the options let's vote :-)  The only option I don't like is do nothing. My favorite option is option 2 because it's both non breaking and allows runtimes to optionally set the order they want for their keys when in verbose mode.

**Comment by runcom** [comment]
I know I'm super late, but I do also prefer going Option 1 with an array of array. That's pretty standard as well for ordered heterogeneous informations. An example of that is the additional information Docker outputs as part of the Storage driver used which is indeed using a `[][]string`. As for the sub arrays, I also agree a Key/Value struct would be better to further abstract it out the right way.
