### ISSUE TITLE
Don't make it easy to do bad things with resource versions

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#58112]
Right now, people looking at resource versions could easily make some assumptions about them which are true at the moment but might not be true in the future. If people bake these poor assumptions into enough clients, it could tie our hands in the future when we go to improve our storage stack.

I propose we perform a simple obfuscation step in the storage layer to expose any faulty assumptions now and thereby prevent users from worse breakage in the future.

**Comment by smarterclayton** [comment]
I think the implications of this are too wide reaching.  I agree that it's a good thing to do.  I don't think breaking anyone using this today is acceptable.

**Comment by smarterclayton** [comment]
Do we need more reasons for people to hate sig/api-machinery?

**Comment by smarterclayton** [comment]
A more measured change might be to make this no longer an integer by adding a character prefix in front of it.

**Comment by lavalamp** [comment]
Why not both? :)

I want to at least get this out behind a flag so people can test whether they are doing it wrong.

**Comment by liggitt** [comment]
If it's about testing or putting friction in the mindless "atoi(resourceVersion)" path to make it clear to clients parsing resource versions they are doing a Bad Unsupported Thing (TM), a simple alpha prefix accomplishes that without any of this complexity. 

Anything we do must absolutely be behind a gate and off by default for at least a release for HA skew reasons.
