### ISSUE TITLE
kubernetes setup with master and worker node in separate VPC 

### ISSUE THREAD

**Issue by ganeshmedhekar** [kubernetes/kubernetes#58136]
Hi,

We would like to deploy the kubernetes master and worker node in separate AWS-VPC . Is there is any way to do this. We have tried with KOPS but it doesn't support.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS or CentOS
- Kernel (e.g. `uname -a`):
- Install tools: Right now used KOPS but need to decide if other tool support multiple VPC option
- Others:

**Comment by brycecarman** [comment]
There is an option in the AWS cloud provider config file to pass the VPC. The difficult part however is that Kubernetes operates under the assumption that all nodes can communicate with each other. VPC peering may be on option here.
