### ISSUE TITLE
Allow update of PV/PVC.Spec.StorageClassName when moving from beta annotation

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#58147]
We should provide an upgrade path from PV/PVC with storage class specified in beta annotation to storage class specified in attribute. Right now, any update of `PV.Spec.StorageClassName` and `PVC.Spec.StorageClassName` is blocked by validation once a PV/PVC is created. The validation should allow update of `StorageClassName` if its value is the same as beta annotation.

/kind bug
/sig storage
@kubernetes/sig-storage-bugs

**Comment by mlmhl** [comment]
I've post a PR to admit upgrading storage class of PVC: #58256
By the way, we needn't extra work for upgrading storage class of PV right now, because [`ValidatePersistentVolumeUpdate`] doesn't validate the equality of `PersistentVolume.Annotations` and `PersistentVolume.Spec.StorageClass`.

**Comment by jsafrane** [comment]
fixed by #58256
/close
