### ISSUE TITLE
Move perfdash to a new home

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#58152]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup
@kubernetes/sig-scalability-misc 

First suggested in https://github.com/kubernetes/contrib/issues/762
Reminded by @foxish in  https://github.com/kubernetes/contrib/pull/2825#issuecomment-356925454

TODO:
- [ ] find a new home
- [ ] move code and related issues (e.g. #483)
- [ ] ...
- [ ] profit!

**Comment by porridge** [comment]
I have no strong feelings regarding the new place. test-infra? dedicated repo?
@kubernetes/sig-testing-feature-requests @krzyzacy @BenTheElder @lavalamp

**Comment by porridge** [comment]
cc @shyamjvs

**Comment by krzyzacy** [comment]
cc @fejta @spiffxp

**Comment by porridge** [comment]
There are no comments, so unless someone objects, I'm going to move contrib/perfdash to test-infra/perfdash.

**Comment by shyamjvs** [comment]
/assign @krzysied 

This has now been fixed thanks to Krzysiek. Perf-dash now lives in k8s/perf-tests.

**Comment by shyamjvs** [comment]
Ref https://github.com/kubernetes/contrib/pull/2885
