### ISSUE TITLE
Move auth out of plugin directory

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#58168]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**What happened**:

There is not much value in keeping a few components in plugin/pkg when everything else lives in and pkg/

This follows the work to move scheduler out of the plugin directory from #57579 (The end goal being to delete the plugin directory.)

**What you expected to happen**:

Components that would be moved:
plugin/pkg/auth

Because the pkg/auth/authorizer directory already exists, the actual move will look more like,
plugin/pkg/auth/authorizer/rbac -> pkg/auth/authorizer/rbac
plugin/pkg/auth/authorizer/node -> pkg/auth/authorizer/node

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @thockin 
/cc @kubernetes/sig-auth-misc
/sig auth

**Comment by deads2k** [comment]
This is suggesting that we move code that plugs into the kube-apiserver, but isn't directly owned by the kube-apiserver (apimachinery) out of plugins.  Why wouldn't we continue to consider this a plugin?
