### ISSUE TITLE
Move admission out of plugin directory

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#58167]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**What happened**:

There is not much value in keeping a few components in plugin/pkg when everything else lives in and pkg/

This follows the work to move scheduler out of the plugin directory from #57579 (The end goal being to delete the plugin directory.)

**What you expected to happen**:

Components that would be moved:
plugin/pkg/admission

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @thockin 
/cc @kubernetes/sig-node-feature-requests	
/sig node

**Comment by yujuhong** [comment]
I think this belongs to sig-scheduling.

**Comment by misterikkit** [comment]
@derekwaynecarr @deads2k You are listed as the owners of the code in question. Can you verify that this issue is in the correct SIG?

**Comment by deads2k** [comment]
> @derekwaynecarr @deads2k You are listed as the owners of the code in question. Can you verify that this issue is in the correct SIG?

I would not move these until the kube-apiserver moves into staging.  Even then, these will move with the kube-apiserver, but the plugin mentality is still a good one.  No back references, code that lives in one process that owned by other sigs, etc. 

I'm against moving the admission plugins to something specific like the scheduler.  The kube-apiserver isn't going to depend on the scheduler.  The scheduler owned admission plugins are plugins to the kube-apiserver that sig-scheduling owns the code for.  They are very plugin like.

**Comment by misterikkit** [comment]
Thanks for the quick reply. I am still new to this community, so I apologize for any missteps. I agree that these admission controllers are very plugin-like.

I wasn't aware of the plan to move kube-apiserver into a separate repo. I see that plugin/pkg/admission would have to move along with it. What is the plan for pkg/kubeapiserver? Is there an issue I can follow?

**Comment by deads2k** [comment]
> What is the plan for pkg/kubeapiserver? Is there an issue I can follow?

@sttts did you create one?

@misterikkit there are multiple issues that need resolution before we can completely such a move.  I just don't want to see a loss of the structure we already have and more "bad" package dependencies appearing.  sig-scheduling may own the code, but the admission plugin itself belongs in the kube-apiserver (as a plugin) for the time being.

**Comment by sttts** [comment]
> @sttts did you create one?

Don't think there is any. We should start one, with the big milestones of such a move.

I want to second that I don't like the idea of moving the plugins back into pkg. It would be a move into the wrong direction. Instead of separate discoupled packages we have to kill pkg, or at least move towards that.

**Comment by derekwaynecarr** [comment]
I agree w/ @deads2k and @sttts , each plug-in is managed by a discrete sig as well depending on the use case.
