### ISSUE TITLE
External services/PublicIPs not working with > 1 minion setup

### ISSUE THREAD

**Issue by vnugent** [kubernetes/kubernetes#5816]
Service::publicIPs works for me in a 1-minion/non-GCE cluster on Fedora.

When I have 2 minions external services are only accessible on the node from which pods are running.  For example, if kube deploys the pod to Minion1 then the external service is available on minion1:port, but not on minion2:port. In the example below the service is only available on 172.18.17.19:18085.
Btw I'm not using hostPort.

```
Client Version: version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}
Server Version: &version.Info{Major:"0", Minor:"9+", GitVersion:"v0.9.1-dirty", GitCommit:"3623a01bf0e90de6345147eef62894057fe04b29", GitTreeState:"dirty"}
```

```
# cat hawkular-snapshot-ext-service-qe.json
{
"id": "hawkular-endpoint-qe",
"kind": "Service",
"apiVersion": "v1beta1",
"port": 18085,
"containerPort": metrics-endpoint-qe,
"labels":{ "name": "hawkular-service-qe"},
"selector": {
"name": "hawkular-snapshot-qe"
},
"publicIPs": [172.18.17.18,172.18.17.19]
}
```

master
```
kubectl get services hawkular-endpoint-qe
NAME LABELS SELECTOR IP PORT
hawkular-endpoint-qe name=hawkular-service-qe name=hawkular-snapshot-qe 10.254.30.120 18085
```

Minion 1 172.18.17.18
```
-A KUBE-PORTALS-CONTAINER -d 10.254.30.120/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j REDIRECT --to-ports 56126
-A KUBE-PORTALS-CONTAINER -d 172.18.17.19/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j REDIRECT --to-ports 56126

-A KUBE-PORTALS-HOST -d 10.254.30.120/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j DNAT --to-destination 172.18.17.18:56126
-A KUBE-PORTALS-HOST -d 172.18.17.19/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j DNAT --to-destination 172.18.17.18:56126
```

Minion 2 172.18.17.19 - pod is running here
```
-A KUBE-PORTALS-CONTAINER -d 10.254.30.120/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j REDIRECT --to-ports 37089
-A KUBE-PORTALS-CONTAINER -d 172.18.17.19/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j REDIRECT --to-ports 37089

-A KUBE-PORTALS-HOST -d 10.254.30.120/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j DNAT --to-destination 172.18.17.19:37089
-A KUBE-PORTALS-HOST -d 172.18.17.19/32 -p tcp -m comment --comment hawkular-endpoint-qe -m tcp --dport 18085 -j DNAT --to-destination 172.18.17.19:37089
```

**Comment by brendandburns** [comment]
v0.9 is pretty old at this point.  Any chance you can try this on a more recent version?

Thanks!
--brendan

**Comment by vnugent** [comment]
Upgraded to v11.  Pods are now stuck in Pending after being deleted and redeployed...

**Comment by decker502** [comment]
I think that `publicIPs` take effect above v0.13.

**Comment by eparis** [comment]
publicIPs should work just fine in v.9

**Comment by eparis** [comment]
oh, what oyu are saying is that in v9 on the last in the list is getting the iptables rule written, interesting....

**Comment by mkulke** [comment]
Actually i noticed the same behavior (PublicIPs specificied in service files does create the correspondend NAT rules on the nodes), however it works fine for me with 0.11.0 and in 0.13.2 it does not.

**Comment by mkulke** [comment]
I investigated a bit, it seems that pkg/proxy/proxier.go#OnUpdate does not get called in a v0.13.2 setup, when activating a service it's supposed to log "Received update notice:" (on log level 4), in v0.13.2 this is missing, on v0.11.0 it shows up. So i suspect the information is not passed correctly to kube-proxy.

**Comment by mkulke** [comment]
After working out kube-register issues, i could try out v0.14.1, the issue seems to be gone in this version.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
