### ISSUE TITLE
Specify if a pvc should be pod-level or deployment level?

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#58176]
When dynamically creating a pvc and then referencing it from within a deployment, this claim becomes global across the deployment. So if I increase the deployment to more than one pod, everything from pod no. 2 onwards will fail as it the other pods will also attempt to claim the volume, but will be unable to do.

I want to be able to dynamically create a pv *per pod*, so that it provisions and tears down the disk as the pod is created and destroyed.

Is this currently possible? Or is it a feature request?

**Comment by mlmhl** [comment]
`Deployment` doesn't support this feature right now, maybe [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage) can satisfy your demand, it will create PV for each pod.

**Comment by huang-jy** [comment]
I took a look at that, but I cannot get it to work. For example, using the example provided on the documentation 

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

and 

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

I get the following:
```
service "nginx" created
Error from server (BadRequest): error when creating "statefulsets.yaml": StatefulSet in version "v1" cannot be handled as a StatefulSet: no kind "StatefulSet" is registered for version "apps/v1"
```

(I then have to delete the nginx service )

Is there something I need to add or apply to the cluster to get StatefulSets working?

**Comment by huang-jy** [comment]
Had to change top of the yaml to 

```yaml
apiVersion: apps/v1beta2
```

But it seems to work now.

I'm noticing that it is not deleting the pvcs and pvs if I delete the sts - so if I create a sts, it will create the pvc and pv for the first pod as expected. If I scale up it will create pvc and pv for that one, but if I delete the sts entirely, all the pvcs and pvs are not deleted. is this intended?

**Comment by mlmhl** [comment]
Yeah, this is intended, you need to delete all PVCs manually after pods or sts deleted.

**Comment by huang-jy** [comment]
It makes sense, I guess -- if I was to recreate the sts, it would reattach to the same pvcs right?
