### ISSUE TITLE
kubeadm TLS One-year term

### ISSUE THREAD

**Issue by fandaye** [kubernetes/kubernetes#58188]
sig/tls

    cat /etc/kubernetes/kubelet.conf |grep "client-certificate-data:" | awk -F ': ' '{print $2}' |base64 -d | openssl x509 -noout -text | grep Not
                Not Before: Jan 12 03:02:07 2018 GMT
                Not After : Jan 12 03:02:11 2019 GMT

The default certificate is only one year limit. How can I generate a new certificate if the one-year limit expires? Manual generation?

**Comment by errordeveloper** [comment]
You will get a new certificate when you upgrade. It's generally a good idea to upgrade more frequently then once a year. This is one of the reasons why kubeadm is still in beta, but the good news is that we are working to fix this soon.

**Comment by errordeveloper** [comment]
/close

Closing in favour of https://github.com/kubernetes/kubeadm/issues/206.
