### ISSUE TITLE
Hyperkube starts the Kubelet differently, and diverges from bootstrap logic as a result

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#58190]
@liggitt noticed that hyperkube is not starting Kubelet in a way that triggers pre-Run bootstrap logic.

See hyperkube: https://github.com/kubernetes/kubernetes/blob/master/cmd/hyperkube/kubelet.go
vs. vanilla Kubelet: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/kubelet.go

The current approach of calling directly into Run leaves hyperkube to diverge from pre-Run additions to the Kubelet's bootstrap process. This will need to be fixed for hyperkube to maintain important additions related to Kubelet configuration (loading config files, starting the controller that reconciles dynamic config, enforcing flag precedence, etc.).

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/issues/34732

**Comment by mtaufen** [comment]
fixed in #58408
