### ISSUE TITLE
Updating system date and time on master/nodes kills pods

### ISSUE THREAD

**Issue by simon3z** [kubernetes/kubernetes#5819]
It seems that updating the date and time on a single master/node host kills all the running pods.

I haven't had time to properly debug this and identify what actually triggers the issue (master or node side), and if anything can be done to fix this.

In general there could be multiple things to consider here:

1. in general it's better not to use date/time for timeouts but rather using monotonic system time
2. where the monotonic system time cannot be used (rate) because the value is persisted/shared among machines (future multiple master?)  then UTC should be used
3. changing the hosts timezone should not affect the timeouts

I haven't tested or checked these 3 items but I am mentioning them here for future reference.

I'll investigate them as soon as I'll have time to figure out what's going on (any info that would make my debug session faster is welcome!)

**Comment by simon3z** [comment]
I haven't investigated further but meanwhile I noticed that timeouts are calculated based upon update times generated by the nodes (e.g. kubelet when updating the node lastProbeTime).

This requires all the nodes to be in date/time sync (which is easy to achieve but it's something additional that we must rely upon).

A solution would be that apiserver would know the types (which already does) and it would fill-in the time when missing. So:

* kubelet would update the node status with empty lastProbeTime (apiserver would fill that in)
* nodecontroller can update the node status (e.g. to update the status to offline) leaving the lastProbeTime untouched (and apiserver would not override it)

this ensures that times (that apiserver knows about) would be in sync with just the apiserver machine clock.

**Comment by davidopp** [comment]
@simon3z we basically implemented what you suggested in #6217. Can you verify that this fixed the problem, and if so, close this issue? Thanks!

**Comment by simon3z** [comment]
@davidopp so in #6217 you're keeping an in-memory map of when nodecontroller saw the nodes reporting thier status? (in nodecontroller time).

If that's the case, it satisfies this issue as well. Thanks.

**Comment by davidopp** [comment]
Correct.

**Comment by davidopp** [comment]
But, it would be great if you have time to verify that this fixed the issue you originally reported here.
