### ISSUE TITLE
[FEATURE REQUEST] need a PodNodeAffinity admission control just like PodNodeSelector

### ISSUE THREAD

**Issue by Dieken** [kubernetes/kubernetes#58198]
According to https://kubernetes.io/docs/concepts/configuration/assign-pod-node/, nodeAffinity is more powerful than nodeSelector, and will replace nodeSelector,  so could you provide another admission control plugin "PodNodeAffinity"?

I need PodNodeSelector or better PodNodeAffinity to dedicate some worker nodes for a namespace, so I can divide a physical huge K8S cluster into some small virtual K8S clusters.

/kind feature
/sig api-machinery

**Comment by wackxu** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by wackxu** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by wackxu** [comment]
Is it needed since we have `taint` and `toleration` ?  What is difference between `PodNodeSelector ` and taint ? If it is necessary, I can help fix it.

**Comment by wackxu** [comment]
@k82cn @resouer

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests 

> What is difference between PodNodeSelector and taint ?

1. taint means which node pod can **NOT** use, selector means which nodes pod can **ONLY** use
1. regarding the PodNodeSelector admission, it's a kind of hard restriction; toleration is a kind of soft restriction, e.g. any pod can add toleration to use those nodes.

**Comment by resouer** [comment]
While one thing still not clear is what is this admission control plugin expected for?

**Comment by embano1** [comment]
@resouer `PodNodeSelector` admission controller has been useful in scenarios where a cluster admin wants to enforce certain placement logic and rules (whitelisting) during admission time. 

If there is no real use case for `PodNodeSelector`, there is none for `PodNodeAffinity`. Depends on how many people are using `PodNodeSelector`, for which reason and whether conceptually there's a better approach, that is not requiring a new admission controller plugin.

**Comment by Dieken** [comment]
@resouer  @embano1 @k82cn @wackxu 

Currently I use PodNodeSelector to divide a physical k8s cluster into multiple sub clusters by namespaces,  suppose I have four nodes node{1,2,3,4} and two namespaces ns{1,2}.

```
# pods in namespace ns1 can only use node1 and node2
kubectl label nodes node1 ns=ns1
kubectl label nodes node2 ns=ns1
kubectl annotate ns ns1 scheduler.alpha.kubernetes.io/node-selector=ns=ns1

# pods in namespace ns2 can only use node3 and node4
kubectl label nodes node3 ns=ns2
kubectl label nodes node4 ns=ns2
kubectl annotate ns ns2 scheduler.alpha.kubernetes.io/node-selector=ns=ns2
```

But in https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity:
```
nodeSelector continues to work as usual, but will eventually be deprecated, 
as node affinity can express everything that nodeSelector can express.
```

So I would like there will be admission plugin "PodNodeAffinity".

**Comment by blepoutr** [comment]
/reopen

We are having the same comments as @Dieken .
If the Nodeselector is deprecated to be replace by NodeAffinity, we should do the same for PodNodeselector admission controller (making it deprecated) and propose a new admission controller PodeNodeAffinity.

**Comment by adampl** [comment]
@Dieken please reopen.
