### ISSUE TITLE
field of Namespace in nodeRef is so odd

### ISSUE THREAD

**Issue by lcfang** [kubernetes/kubernetes#58200]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

I see the code in [https://github.com/kubernetes/kubernetes/blob/a97ce942e98441425b7ede4341dd4b0663164737/pkg/kubelet/kubelet.go#L459](https://github.com/kubernetes/kubernetes/blob/a97ce942e98441425b7ede4341dd4b0663164737/pkg/kubelet/kubelet.go#L459)
Here is the `nodeRef`, and these all fields are optional, since there is no `Namespace` for node, why it is here?

**What you expected to happen**:

Can we delete it here? Or can we add a new feature for node namespace isolation?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): the latest

**Comment by lcfang** [comment]
cc @Random-Liu @dchen1107 @yujuhong @vishh

**Comment by liggitt** [comment]
v1.ObjectReference is a generic object reference struct, used for both namespaced and unnamespaced references.

"" is the zero value for the namespace field. Omitting `Namespace:""` would result in an identical value

**Comment by lcfang** [comment]
Hi @liggitt ，thanks for your reply, I agree the result will be the same.
