### ISSUE TITLE
Proposal: Move match version check to part of the "version" subcommand

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#5820]
We have to jump through some significant gymnastics to make match version work (it happens when clients are created, but we want that to be abstract, but then we have to make sure it only happens once...).

Since the original intent was to verify your client tools, why not make it part of "kubectl version" via an optional check "--check"?  We can then unplumb it from the depths of the tools, and ensure all our test cases and test suites invoke it before build (test-cmd and e2e).

Thoughts?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-proposals
