### ISSUE TITLE
Minikube on windows does not start with a corporate proxy 

### ISSUE THREAD

**Issue by SriharshaAngadi** [kubernetes/kubernetes#58213]
/kind bug

**What happened**:

Trying to start minikube with command as :
**C:\>minikube start --docker-env="HTTP_PROXY=http://XXXX/YYY" \ --docker-env="HTTPS_PROXY=http://XXX/YYY" --alsologtostderr**
 over windows with corporate proxy, with Virtual box VM. It fails to start with the following error (Attached):
[ErrorWithoutStdErrorLog.txt](https://github.com/kubernetes/kubernetes/files/1626004/ErrorWithoutStdErrorLog.txt)
[ErrorWithStdErrorLog.txt](https://github.com/kubernetes/kubernetes/files/1626005/ErrorWithStdErrorLog.txt)
**I have also set the environment variables** 
**Proxy is present in the form of .PAC file**
**Used the IP from PAC file , still it does not work**
**What you expected to happen**:
MiniKube should have started. 
**How to reproduce it (as minimally and precisely as possible)**:
Start Mini kube with the below command:
**C:\>minikube start --docker-env="HTTP_PROXY=http://XXXX/YYY.pac" \ --docker-env="HTTPS_PROXY=http://XXX/YYY.pac" --alsologtostderr**

**Anything else we need to know?**:
Minikube starts fine without corporate proxy
**Windows 8 enterprise**:
- Kubernetes version command gave the following error
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommi
t:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2
017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd6
4"}
Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connecti
on could be made because the target machine actively refused it.
- hardware configuration: 
8Gb RAM 
64 Bit OS

- OS (e.g. from /etc/os-release):**Windows 8 enterprise**:
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by SriharshaAngadi** [comment]
I am not an able to add labels

**Comment by cblecker** [comment]
This repo is for the kubernetes software itself, not minikube. You may wish to open an issue with them directly: https://github.com/kubernetes/minikube/issues

/remove-kind bug
/kind support
/close
