### ISSUE TITLE
Document Kubernetes seccomp support

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/kubernetes#58211]
I'm trying to use the seccomp feature as we need to give an application some more permissions, so we need a custom seccomp profile.

There are 2 problems with the current feature:
- custom seccomp profiles need to be in a file on the node, this does not only break how kubernetes is configured, it also impossible in various setups (example: we are in GKE and can't just modify the image)
- no docs:

  - https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/design/seccomp.md this is only the proposal, I think this is implemented, but newer implementation have no docs at all
- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ mentions it is possible to use configure in the securityContext, but the reference and docs don't say how (but I can find PR's supporting the securityContext and seccomp)

My main problem is trying to get seccomp working without dropping GKE and spinning up a cluster from scratching, maintaining that, etc.

**Comment by pvanderlinden** [comment]
@kubernetes/docs/sig-docs-feature-requests @kubernetes/docs/sig-api-machinery-bugs

**Comment by php-coder** [comment]
Here is my request to add the docs: https://github.com/kubernetes/website/issues/3173

Also, I think that seccomp is more
/sig auth
than
/remove-sig api-machinery

**Comment by php-coder** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by zacharysarah** [comment]
Hey, I'm following up from docs. 👋 The next step for docs is to submit a PR to [kubernetes/website](https://github.com/kubernetes/website/) with proposed documentation.

**Comment by tallclair** [comment]
xref: https://github.com/kubernetes/features/issues/135#issuecomment-331592961

I'm working on getting some staffing from the google team, but if anyone outside wants to step up, this feature needs an owner.

For the issue of profile deployment, I'd like to see the ability to load profiles from a configmap.

**Comment by tallclair** [comment]
I'm narrowing this to the documentation piece. For the feature enhancement part, see https://github.com/kubernetes/enhancements/issues/135

/help

**Comment by tallclair** [comment]
/remove-lifecycle stale

This should be covered by https://github.com/kubernetes/enhancements/pull/1148

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by tallclair** [comment]
/milestone v1.18

blocker for https://github.com/kubernetes/enhancements/pull/1148

**Comment by gianarb** [comment]
Hello @tallclair   !
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18, or should it extend to the next one? Thanks in advance!

**Comment by tallclair** [comment]
/milestone clear

Seccomp to GA isn't happening for v1.18

**Comment by hasheddan** [comment]
Closing this out with https://github.com/kubernetes/website/pull/21278

/close
