### ISSUE TITLE
Kubeadm init blocks at "This might take a minute or longer if the control plane images have to be pulled."

### ISSUE THREAD

**Issue by tobiasetter** [kubernetes/kubernetes#58214]
/kind bug

**What happened**:
I tried to run kubeadm init.

**What you expected to happen**:
I wanted the kubernetes master to set up.

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.9.1
- Cloud provider or hardware configuration: contabo.com
- OS (e.g. from /etc/os-release): Ubuntu 16.04

I run:

 "kubeadm init"

what I can see in the console:

[init] Using Kubernetes version: v1.9.1
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
    [WARNING SystemVerification]: docker version is greater than the most recent version. Docker version: 17.12.0-ce. Max validated version: 17.03
    [WARNING FileExisting-crictl]: crictl not found in system path
[preflight]Strarting the kubelet service

... (generates keys, certificates and writes KubeConfig to disk --> no errors)

[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".

HANGS HERE

Does someone know, what could be the error? I did not find any error code.
Many thanks

**Comment by Sh4d1** [comment]
@tobiasetter did you manage to fix it ? I'm running into the same problem..

**Comment by edward-of-clt** [comment]
Is a duplicate of https://github.com/kubernetes/kubeadm/issues/684

**Comment by mixpix3ls** [comment]
Seems like a duplicate of that. I'm having a similar issue but the one referenced (684) is closed. I have tried getting `kubeadm` working on both CentOS 7 and Ubuntu 16.04.4 with no avail.

**Comment by tobiasetter** [comment]
@Sh4d1 I could fix it by setting a new hostname
