### ISSUE TITLE
[request] backport #56820 from master to 1.9

### ISSUE THREAD

**Issue by leifmadsen** [kubernetes/kubernetes#58220]
/kind bug

**What happened**: Unable to use artifacts created with Bazel on k8s 1.9

**What you expected to happen**: Artifacts created by Bazel on k8s 1.9 results in a Go coredump when attempting to install via kubeadm

**How to reproduce it (as minimally and precisely as possible)**: Use planter to build k8s 1.9. Load the resulting .tar container files into Docker via `docker load -i`, retag for -amd64, run `kubeadm init`. On 1.9 Go will coredump. With master, things are fine.

**Anything else we need to know?**: I've tested against master, and the changes in PR https://github.com/kubernetes/kubernetes/pull/56820 and related results in usable artifacts.

**Environment**: CentOS 7.3 x86_64
- Kubernetes version (use `kubectl version`): 1.10-alpha
- Cloud provider or hardware configuration: x86_64 VM on KVM
- OS (e.g. from /etc/os-release): CentOS 7.3
- Kernel (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- Install tools: kubeadm
- Others: Planter, bazel

**Comment by liggitt** [comment]
that seems like a significant change for a maintenance branch... have those changes been given enough soak time?

**Comment by ixdy** [comment]
@liggitt two points:
1. Those changes have been running in the master branch for close to a month now
2. AFAIK nothing official is using the bazel artifacts currently

So it seems like it would probably be safe to do?
Also the build stuff in 1.9 hasn't drifted too far from master yet.

**Comment by liggitt** [comment]
> AFAIK nothing official is using the bazel artifacts currently

ah, I thought that's how the build scripts were building

**Comment by BenTheElder** [comment]
presubmit / CI uses bazel builds heavily, but releases etc. use the
dockerized (non-bazel) builds currently. this should be safe to backport if
someone wants to take it on.

**Comment by fejta** [comment]
@kubernetes/sig-release-bugs 

We really ought to fix this if we can.

**Comment by leifmadsen** [comment]
I don't know... should we bother with this since 1.10 is released?

**Comment by leifmadsen** [comment]
Closing as a backport to 1.9 is no longer necessary (release containing fixes is available).
