### ISSUE TITLE
Move equivalence class based scheduling to beta

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#58222]
# Feature Description
- One-line feature description (can be used as a release note): Cache scheduling decisions of equivalent pods
  (It has been noted that this feature isn't user-facing, and we may not include it in release notes.)
- Primary contact (assignee): @resouer, @misterikkit
- Responsible SIGs: @kubernetes/sig-scheduling-feature-requests
- Design proposal link (community repo): [Equivalence class based scheduling in Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler-equivalence-class.md)
- Link to e2e and/or unit tests: [test/e2e/scheduling/equivalence_cache_predicates.go](https://github.com/kubernetes/kubernetes/blob/30b89d830b7fd0827576853d6a0db44b66a90d3d/test/e2e/scheduling/equivalence_cache_predicates.go)
- Reviewer(s) - (for LGTM) recommend having 2+ reviewers (at least one from code-area OWNERS file) agreed to review. Reviewers from multiple companies preferred:  @davidopp, @bsalamat , @erictune, @k82cn, @timothysc, @wojtek-t
- Approver (likely from SIG/area to which feature belongs): @davidopp, @wojtek-t
- Feature target (which target equals to which milestone):
  - Alpha already released: 1.8
  - Beta release target: 1.11
  - Stable release target: 1.12

This feature was already implemented by @resouer and is currently in alpha. There is some remaining work to get the feature ready for beta & ga.

### Original issue: 
- https://github.com/kubernetes/kubernetes/issues/17390

### Remaining issues (will be periodically updated):
- Full integration test is required: https://github.com/kubernetes/kubernetes/issues/56104
- Amend and enable e2e test: https://github.com/kubernetes/kubernetes/pull/56577#issuecomment-348700335
- Fix potential data race: [TODO](https://github.com/kubernetes/kubernetes/blob/30b89d8/pkg/scheduler/core/generic_scheduler.go#L482)
- Evaluate and fix potential improvements:
    - speed up invalidate operation (or not)[TODO]( https://github.com/kubernetes/kubernetes/blob/30b89d8/pkg/scheduler/core/generic_scheduler.go#L490) 
    - minimize invalidation scope, [TODO-1](https://github.com/kubernetes/kubernetes/blob/30b89d8/pkg/scheduler/factory/factory.go#L514) [TODO-2](https://github.com/kubernetes/kubernetes/blob/30b89d8/pkg/scheduler/factory/factory.go#L642)
- Compute pod equivalence based on pod properties and not OwnerReference.

/sig scheduling
/kind feature

**Comment by resouer** [comment]
Thanks @misterikkit for bringing this up! We may want to start with `Compute pod equivalence based on pod properties and not OwnerReference.` which looks like a fundamental issue?

 (I'm currently OOO and will back next week, sorry for response delay)

**Comment by misterikkit** [comment]
@resouer Thanks. For changing the equivalence computation, the existing logic is pretty well isolated. I should only need to change EquivalencePodGenerator.getEquivalencePod in pkg/scheduler/algorithm/predicates/utils.go.

However, I propose to refactor a lot of that logic to simplify it and make code updates easier. I'll try to send a PR for that soon.

**Comment by k82cn** [comment]
are we still target to 1.11 for this feature?

**Comment by misterikkit** [comment]
The goal is yes. Although I haven't created a PR yet to move it over.
I think we probably want some more tests in place to make sure that we're not missing weird edge cases. Also, we should collect metrics from e2e tests demonstrating the performance benefit.

**Comment by wojtek-t** [comment]
I vote for not doing it in 1.11 - this isn't urgent and we don't have full confidence in it.
Instead, we should enable it at the beginning of 1.12 and have it soaked for the whole release cycle.

**Comment by k82cn** [comment]
/milestone 1.12

In last sig-scheduling meeting, we decide to move this to next release.

**Comment by misterikkit** [comment]
The current plan is to do this in 1.12. Can someone update the milestone?

**Comment by resouer** [comment]
Milestone already cleared

**Comment by resouer** [comment]
Issue is up-to-date after #65714 

The on going task is #62226 and #66148 to add more integration tests for volume related predicates.

**Comment by dims** [comment]
@misterikkit @resouer  Does this still need the v1.12 milestone?

**Comment by resouer** [comment]
Though the blocker issue in 1.11 has been fixed, I don't think we can catch 1.12 code freeze since we are discussing re-org ecache to predicates pkg in https://github.com/kubernetes/kubernetes/pull/67241, which still need some agreement.

**Comment by dims** [comment]
ack. let me clear the milestone then @resouer 

/milestone clear

**Comment by resouer** [comment]
@misterikkit Seems it's now safe to close this one as we have #68720  now
