### ISSUE TITLE
Enable golinting for scheduler packages

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#58234]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

 /kind feature

**What happened**:
While working on #58061, noticed that following packages are excluded from golint checks:

pkg/scheduler/algorithm
pkg/scheduler/algorithm/predicates
pkg/scheduler/algorithm/priorities
pkg/scheduler/algorithm/priorities/util
pkg/scheduler/api
pkg/scheduler/api/latest
pkg/scheduler/api/v1
pkg/scheduler/core
pkg/scheduler/factory
pkg/scheduler/metrics
pkg/scheduler/schedulercache
pkg/scheduler/testing
pkg/scheduler/util

**What you expected to happen**:
We need to enable linting for them.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @bsalamat @k82cn

**Comment by ravisantoshgudimetla** [comment]
Procedure to verify:
 - Remove the entry(dirs from previous comment, for example:  pkg/scheduler/metrics) from hack/.golint_failures file.
- Run hack/verify-golint.sh. You will notice an error like this:
`pkg/scheduler/metrics/metrics.go:110:1: comment on exported function SinceInMicroseconds should be of the form "SinceInMicroseconds ...`
- Make changes to pkg/scheduler/metrics/metrics.go so that it confirms to golint.
- Run hack/verify-golint.sh. This shouldn't thrown an error related to pkg/scheduler/metrics now.

**Comment by tossmilestone** [comment]
@ravisantoshgudimetla I could work to fix this issue

**Comment by k82cn** [comment]
@tossmilestone , please go ahead to work on it.

**Comment by tossmilestone** [comment]
I have problem when working on lint errors in the auto-generated files, e.g. `pkg/scheduler/api/v1/zz_generated.deepcopy.go:265:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)`

`zz_generated.deepcopy.go` is auto generated by `deepcopy-gen`, and not suggested manually edited. I want to add the file to `hack/.golint_failures` to ignore the error, but it didn't work. `hack/verify-golint.sh` does not support ignoring file failure. 

@k82cn So could you give me some advice on how to solve the problem?
Thanks!

**Comment by nikhita** [comment]
> `hack/verify-golint.sh` does not support ignoring file failure.

You cannot add files in `hack/verify-golint.sh` but you can add package names. :)

I think it is reasonable to leave `pkg/scheduler/api/v1` in `hack/verify-golint.sh` to avoid failing on linting errors due to generated files, but correcting any other lint errors (in non-generated files) in `pkg/scheduler/api/v1`.

**Comment by tossmilestone** [comment]
@nikhita That's a reasonable solution, Thank you! And I think if `hack/verify-golint.sh` add the feature of ignoring file lint errors, it would be perfect. :)

**Comment by k82cn** [comment]
yes. maybe you can try to propose some PRs at https://github.com/kubernetes/code-generator  to address it.

**Comment by k82cn** [comment]
add `pkg/scheduler/api/v1` is also ok to me :)
