### ISSUE TITLE
Result of kubelet health checks not exposed

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#58235]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

The result of liveness and readiness probes performed by kubelet is not easily available other than through kubectl. Currently if a user wanted a time series graph detailing the health of their pod/container, it would not be possible.

If the results of these checks were properly exposed through a medium such as a Prometheus metric, it would highly benefit users. Using a prometheus metric would allow for integrations with Grafana, Stackdriver, etc. 

cc @dchen1107 @miekg

**Comment by DirectXMan12** [comment]
commented on the PR, copying here for visibility

> it could be done via a custom collector, and send ConstMetrics  on each collection, presumably.  We could even put it at a separate endpoint, so  that if the cardinality is too high for what you normal want, you can  just ignore this endpoint or deal with it separately...

**Comment by rramkumar1** [comment]
I'm thinking a separate endpoint might be the best approach. That way, IIUC, we could easily integrate with Heapster. I'm assuming we would want expose this endpoint on the kubelet so would it be something like /containerHealthChecks which then spits out JSON?

**Comment by rramkumar1** [comment]
ping @DirectXMan12 Does the approach I stated above sound good? I would like to get started ASAP

**Comment by DirectXMan12** [comment]
apologies, missed your update earlier.

> which then spits out JSON?

I'd have it spit out prometheus metrics so someone could easily collect them with prometheus if they wanted, but otherwise, that approach sounds good.

> we could easily integrate with Heapster

No.  I'd prefer not to add completely new metrics sources to Heapster.
