### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by haf** [kubernetes/kubernetes#58238]
The link in the readme here https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container is broken.

(As a wider effect; it's almost impossible to find a good example of a tool-type container to run with CronJobs that has kubectl already installed)

**Comment by haf** [comment]
@kubernetes/sig-docs

**Comment by cceckman** [comment]
@kubernetes/sig-docs-bugs , maybe (including `<group-suffix`)?

**Comment by radu-matei** [comment]
@haf - here's the reason why you don't find it anymore - it has been removed - https://github.com/kubernetes/examples/commit/559c64edb3639fe5b34637928e06ba28b308fa07

What exactly are you trying to do?

**Comment by haf** [comment]
@radu-matei I was just trying to use kubectl from the smallest possible container — in my case it became:

```
FROM alpine:3.6

# Install kubectl
# Note: Latest version may be found on:
# https://aur.archlinux.org/packages/kubectl-bin/
ADD https://storage.googleapis.com/kubernetes-release/release/v1.8.6/bin/linux/amd64/kubectl /usr/local/bin/kubectl

ENV HOME=/config

RUN set -x && \
    apk add --no-cache curl ca-certificates && \
    chmod +x /usr/local/bin/kubectl && \
    \
    # Create non-root user (with a randomly chosen UID/GUI).
    adduser kubectl -Du 6142 -h /config && \
    \
    # Basic check it works.
    kubectl version --client

USER kubectl

ENTRYPOINT ["/usr/local/bin/kubectl"]
```

But this had to be scavenged from github; it would be good to have a sample of using kubectl from within Kube somewhere in the docs; that's what I thought this link would link to.

I think you should remove examples that have been deprecated.

**Comment by radu-matei** [comment]
@cceckman -  should I remove the example completely, or should we add to the docs documentation on how to use a `kubectl` container?

I am thinking both in-cluster and out of cluster authentication (mounting the kubeconfig file inside the container)?
Thanks!

**Comment by php-coder** [comment]
@kubernetes/sig-docs

**Comment by cceckman** [comment]
Examples are useful for establishing / encouraging best practice- so if there's a best practice for "`kubectl` in container," sure, would be good to capture that. If it's discouraged, thenit should be removed. I've no idea which of those is preferred.

(I'm just a novice k8s user, not part of sig-docs- just stopped by to help get the group's attention. :-) )

**Comment by adnavare** [comment]
Hi @radu-matei : are we removing that broken link? If you want i can work on this issue?

**Comment by haf** [comment]
Not stale

**Comment by haf** [comment]
Why is it me who needs to keep talking to a computer about this? Either you fix it or close it, but stop letting a bot ping me?

**Comment by haf** [comment]
/remove-lifecycle stale

But I can't keep doing this, against a computer, so I'm closing this issue even though the premise; "what kubectl container to use?" is still unanswered. Here are options:

 - https://github.com/GoogleCloudPlatform/cloud-builders (see kubectl folder)
 - https://github.com/wernight/docker-kubectl
