### ISSUE TITLE
Add dry-run option to scheduler

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#58242]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
As of now, scheduler doesn't support dry-run. It would be great to have an option like that.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
that's a great feature; would you share some specific user case?

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by liggitt** [comment]
Cc @derekwaynecarr

**Comment by bsalamat** [comment]
This is a very useful feature that has been in our radar for a while. I can think of two possible implementation options: 1. add a feature to the scheduler to support dry-run, 2. create a separate tool that simulates a cluster by replicating its state on a independent machine and allows user to play with it. The two approaches have their own pros and cons. I think we should have a design doc to list all the advantages and disadvantages of each. Then we can decide how to proceed.

**Comment by liggitt** [comment]
> create a separate tool that simulates a cluster by replicating its state on a independent machine and allows user to play with it

for reference, openshift has cluster capacity tool that takes the current state of a cluster as a starting point, then runs simulated schedules of a prototypical pod for capacity calculations:
* https://docs.openshift.com/container-platform/3.6/admin_guide/cluster_capacity.html
* https://www.youtube.com/watch?v=uNQt5Y8RTZk

cc @aveshagarwal

**Comment by k82cn** [comment]
+1 to @bsalamat 's case
-100 for case https://github.com/kubernetes/kubernetes/issues/48657 :).

**Comment by aveshagarwal** [comment]
If the purpose of the dry-run is to check if where a new pod would be scheduled, then it can be checked easily with cluster capacity as follows: `./cluster-capacity --kubeconfig <path to kubeconfig> --podspec <input-pod-spec> --max-limit 1`  .  If a series of pods has to be checked, that there are 2 cases: 1) do pods in the series need to be scheduled independent of each other? if yes, then it can also be checked by the above cluster capacity command just by iterating on input series;  2) if pods in the series need to be scheduled collectively, then it does not exist in cluster capacity and would require implementation changes. Please note, may be its obvious, that the order of the pods in the series will also matter in this case.

**Comment by ravisantoshgudimetla** [comment]
+1 to cluster-capacity tool - One thing to note here is scheduler_perf(https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf) tool which is used for performance measurements does something similar but we generate the pod spec dynamically. It would be interesting to be able to provide a list of pod specs along with their arrival times(we can sort pods based on arrival times) and provide them to either of tools or include this as a feature in one of the tools.

**Comment by ravisantoshgudimetla** [comment]
/close

Closing this in favour of cluster-capacity analysis.
