### ISSUE TITLE
Kubernetes 1.9.1 component status checking does not work with bool value {"health":true} returned by etcd health monitoring API /health.

### ISSUE THREAD

**Issue by henrywang** [kubernetes/kubernetes#58240]
The etcd exposes health information via HTTP at /health in JSON format. The latest released etcd 3.3 changed in /health endpoint response value. This change can be found from [Upgrade etcd from 3.2 to 3.3](https://github.com/coreos/etcd/blob/91996607a347b3bb3bfdfd6543ab66b5a5da0694/Documentation/upgrades/upgrade_3_3.md).
Before
```shell
$ curl http://localhost:2379/health
{"health": "true"}
```
After
```shell
$ curl http://localhost:2379/health
{"health":true}

# Or
{"health":false,"errors":["NOSPACE"]}
```
But when it integrated with Kubernetes 1.9.1, the Kubernetes component status check will report an error when it checks etcd health status. Kubernetes should follow the new change in etcd.

```shell
$ etcdctl -v
etcdctl version: 3.3.0-rc.1
API version: 2

$ curl -L http://127.0.0.1:2379/health
{"health":true}
```

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl get componentstatuses
NAME                 STATUS      MESSAGE           ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   {"health":true}   json: cannot unmarshal bool into Go struct field etcdHealth.health of type string
```

**Comment by liggitt** [comment]
That seems like a breaking change in the etcd healthz api

**Comment by gyuho** [comment]
k8s needs something like this

```diff
diff --git a/staging/src/k8s.io/apiserver/pkg/storage/etcd/util/etcd_util.go b/staging/src/k8s.io/apiserver/pkg/storage/etcd/util/etcd_util.go
index 7c71fe24fc..9ed924b313 100644
--- a/staging/src/k8s.io/apiserver/pkg/storage/etcd/util/etcd_util.go
+++ b/staging/src/k8s.io/apiserver/pkg/storage/etcd/util/etcd_util.go
@@ -23,6 +23,7 @@ import (
        "net/http"
 
        etcd "github.com/coreos/etcd/client"
+       "github.com/coreos/etcd/etcdserver/api/etcdhttp"
 )
 
 // IsEtcdNotFound returns true if and only if err is an etcd not found error.
@@ -82,13 +83,8 @@ func GetEtcdVersion(host string) (string, error) {
        return string(versionBytes), nil
 }
 
-type etcdHealth struct {
-       // Note this has to be public so the json library can modify it.
-       Health string `json:"health"`
-}
-
 func EtcdHealthCheck(data []byte) error {
-       obj := etcdHealth{}
+       obj := etcdhttp.Health{}
        if err := json.Unmarshal(data, &obj); err != nil {
                return err
        }
```

And regenerate `vendor` directory to include `"github.com/coreos/etcd/etcdserver/api/etcdhttp/metrics.go"` file, which defines `etcdhttp.Health`.

**Comment by liggitt** [comment]
Etcd client upgrades are typically significant (see example impact in https://github.com/kubernetes/kubernetes/pull/57160). We're on the 3.2.x stream for 1.10, so I wouldn't expect a 3.3.x upgrade before the next release

**Comment by liggitt** [comment]
If it's just a matter of loosening the typing on the health struct in that package, that's way more contained. 

We have to continue working with etcd 3.1.x and 3.2.x servers, so switching to the 3.3 strongly typed struct isn't an option for us.

**Comment by gyuho** [comment]
Since 3.3 has not been released, etcd can still revert this change (just changing the type back to `string` should be enough).

We will get back to this next week.

**Comment by liggitt** [comment]
> Since 3.3 has not been released, etcd can still revert this change (just changing the type back to string should be enough).

Ah, excellent, I thought 3.3 was out already. I would strongly recommend keeping the current type intact

**Comment by liggitt** [comment]
opened https://github.com/coreos/etcd/pull/9143, in case it helps

**Comment by liggitt** [comment]
closing this issue, since I don't expect kubernetes to need to make changes here
/close

**Comment by rashidmahmood** [comment]
Had same issue, upgraded from 3.3.0 to 3.3.1 and it resolved.
