### ISSUE TITLE
add support for "cache"-style volumes

### ISSUE THREAD

**Issue by ndeloof** [kubernetes/kubernetes#58245]
**FEATURE REQUEST**: cache style volumes
/kind feature

**What happened**:
My application uses filesystem as a cache for some data. It can restart from sratch, but would benefit a "hot" cache on startup.
I only can use an `emptyDir` volume for now, as all other volumes strategies involve distributed storage or strong persistence constraints, while I'm looking for fast I/O.

**What you expected to happen**:
I'd like I could request a `cache` volume for my app, so that I get an `emptydir` first time app is ran on a node, then retrieve previous content if another pod for same app is later deployed on this same node.

**Comment by ndeloof** [comment]
@kubernetes/sig-Storage

**Comment by pmartin-brierley** [comment]
> 
> 
> **FEATURE REQUEST**: cache style volumes
> /kind feature
> 
> **What happened**:
> My application uses filesystem as a cache for some data. It can restart from sratch, but would benefit a "hot" cache on startup.
> I only can use an `emptyDir` volume for now, as all other volumes strategies involve distributed storage or strong persistence constraints, while I'm looking for fast I/O.
> 
> **What you expected to happen**:
> I'd like I could request a `cache` volume for my app, so that I get an `emptydir` first time app is ran on a node, then retrieve previous content if another pod for same app is later deployed on this same node.

Did you ever find a solution for this?

**Comment by ndeloof** [comment]
haven't found any workaround. Seems nobody cares about this use-case, which I expected to be pretty common.
