### ISSUE TITLE
kubeamd should support customize k8s's images 

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#58257]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
feature

**What happened**: 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
when l use kubeadm tools to create k8s cluster，it's default to pull imgaes from gcr.io , l think it's should support customize images by myself .
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huangjiasingle** [comment]
@kubernetes/sig-Kubeadm

**Comment by huangjiasingle** [comment]
@kubernetes/sig-kubeadm-feature

**Comment by dims** [comment]
@huangjiasingle yes, it's already there i believe. see at `unifiedControlPlaneImage` at https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by huangjiasingle** [comment]
@dims thanks you !
