### ISSUE TITLE
Do you want to support mips? Do you have a plan?

### ISSUE THREAD

**Issue by lmq3342xja** [kubernetes/kubernetes#58277]
Do you want to support mips? Do you have a plan?

**Comment by fejta** [comment]
@kubernetes/sig-architecture-feature-requests 
@kubernetes/sig-node-feature-requests 

On the other hand this report doesn't have a lot of info so maybe just close?

**Comment by bgrant0607** [comment]
There are no plans and no prior requests AFAIK, and we don't have hardware to test it.

It also looks like a pretty small niche at this point:
http://linuxgizmos.com/amd-reveals-arm-and-x86-soc-and-apu-plans/

Yes, closing.
