### ISSUE TITLE
Kube-dns can not start, who can help me

### ISSUE THREAD

**Issue by wottui** [kubernetes/kubernetes#58285]
[root@k8s_master network]# docker logs -f k8s_kubedns_kube-dns-7c8795467f-ddlfx_kube-system_3e2c1b1b-f9ef-11e7-8bc5-080027f57e7e_1
I0115 12:27:11.088709       1 dns.go:48] version: 1.14.4-2-g5584e04
I0115 12:27:11.113518       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0115 12:27:11.115558       1 server.go:113] FLAG: --alsologtostderr="false"
I0115 12:27:11.115582       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0115 12:27:11.115605       1 server.go:113] FLAG: --config-map=""
I0115 12:27:11.115615       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0115 12:27:11.115625       1 server.go:113] FLAG: --config-period="10s"
I0115 12:27:11.115668       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0115 12:27:11.115678       1 server.go:113] FLAG: --dns-port="10053"
I0115 12:27:11.115690       1 server.go:113] FLAG: --domain="cluster.local."
I0115 12:27:11.115703       1 server.go:113] FLAG: --federations=""
I0115 12:27:11.115714       1 server.go:113] FLAG: --healthz-port="8081"
I0115 12:27:11.115724       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0115 12:27:11.115734       1 server.go:113] FLAG: --kube-master-url=""
I0115 12:27:11.115744       1 server.go:113] FLAG: --kubecfg-file=""
I0115 12:27:11.115754       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0115 12:27:11.115769       1 server.go:113] FLAG: --log-dir=""
I0115 12:27:11.115780       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0115 12:27:11.115789       1 server.go:113] FLAG: --logtostderr="true"
I0115 12:27:11.115799       1 server.go:113] FLAG: --nameservers=""
I0115 12:27:11.115808       1 server.go:113] FLAG: --stderrthreshold="2"
I0115 12:27:11.115817       1 server.go:113] FLAG: --v="2"
I0115 12:27:11.115827       1 server.go:113] FLAG: --version="false"
I0115 12:27:11.115840       1 server.go:113] FLAG: --vmodule=""
I0115 12:27:11.132335       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0115 12:27:11.135984       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I0115 12:27:11.136006       1 dns.go:147] Starting endpointsController
I0115 12:27:11.136014       1 dns.go:150] Starting serviceController
I0115 12:27:11.149780       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0115 12:27:11.149801       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0115 12:27:11.636347       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:12.136389       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:12.636451       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:13.141095       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:13.636601       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:14.136593       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:14.639200       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:15.136263       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:15.636306       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:16.136395       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:16.636435       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:17.136483       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:17.636531       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:18.136565       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:18.636628       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:19.136750       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:19.637278       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:20.136388       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:20.636301       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:21.136417       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:21.636540       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:22.137893       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:22.636669       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:23.136707       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:23.636960       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:24.136360       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:24.636395       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:25.136427       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:25.637778       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:26.136538       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:26.636655       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:27.140558       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:27.636233       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:28.136316       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:28.636356       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:29.138755       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:29.643838       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:30.136546       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:30.636633       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:31.136683       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:31.636243       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:32.136339       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:32.636360       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:33.136441       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:33.636499       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:34.136555       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:34.636625       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:35.137084       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:35.636368       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:36.136325       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:36.636339       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:37.136414       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:37.636686       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:38.136540       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:38.636584       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:39.136219       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:39.636453       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:40.136279       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:40.636385       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:41.136408       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
E0115 12:27:41.191674       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: i/o timeout
E0115 12:27:41.192098       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: i/o timeout
I0115 12:27:41.636459       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:42.136313       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:42.637182       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:43.136654       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
I0115 12:27:43.636282       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

**Comment by manojdevs** [comment]
did you apply the iptable-rules to route the requests to the api service?

**Comment by fejta** [comment]
@kubernetes/sig-api-machinery-misc are addons part of scheduling or api-machinery?

**Comment by liggitt** [comment]
Cluster lifecycle (addons in general) or networking (dns in particular)
