### ISSUE TITLE
'Volume plugin streaming [Slow] NFS...' e2e test failing on large clusters

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#58280]
Noticing this is in our gce 5k-node cluster tests. It has been continuously failing for 4 runs now already:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/37
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/38 (and 39 and 40)

The e2e test concerned is - Volume plugin streaming [Slow] NFS should write files of various sizes, verify size, validate content
And it is failing due to:

```
size of file /opt/nfs/e2e-tests-volume-io-l6qlm/nfs_io_test-1073741824 is 891265024, expected 1073741824
not to have occurred
```

cc @kubernetes/sig-storage-bugs @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
cc @msau42 @saad-ali - Could one of you PTAL or redirect as apt?

**Comment by shyamjvs** [comment]
FTR, it is passing on small scale - https://k8s-testgrid.appspot.com/google-gce#gci-gce-slow

I took a quick look at the [diff](https://github.com/kubernetes/kubernetes/compare/6d98cdbbf...dc44a3174) and the following PR catches my attention at first sight:

#57037 test: e2e: support NFS test on overlayfs

**Comment by shyamjvs** [comment]
@porridge Do we have some umbrella issue for failing correctness tests on large scale atm?

**Comment by porridge** [comment]
Not really, we have https://github.com/kubernetes/kubernetes/issues/57323,
though.

**Comment by msau42** [comment]
#57037 does look very suspicious.  Before, the NFS server test image would use the container image layer for its data, and this change makes it use emptydir tmpfs instead.  @shyamjvs for the large scale tests, do you guys have default memory limits for pods?  That could potentially explain why it's failing on large scale tests and not the regular tests.

A possible fix could be to change it to use regular emptydir so it's not subject to any memory limits.

**Comment by shyamjvs** [comment]
> @shyamjvs for the large scale tests, do you guys have default memory limits for pods?

FMU we're not setting any memory limits for pods explicitly and it's the same e2e test running on both the large cluster and the small cluster. I'm not sure if there's sth (like an admission plugin) which secretly sets memory limits for pods based on cluster size - I'd be quite surprised if that's the case.

**Comment by msau42** [comment]
Hmm or it could be that in the scale test, the nodes are more loaded, so resources could be more constrained.  In any case, I think it's better for this test to not write to tmpfs, because it can write gigs of data.

**Comment by shyamjvs** [comment]
I would be surprised a bit if that was the case - as this test was passing for quite some time (https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness). So mostly unless sth changed around this e2e test or with storage/kubernetes, it doesn't seem to be so.

Anyhow, not writing gigs of data to tmpfs does sound good to me :) One more thing to note is we're using the following config for our large cluster:

```
NODE_SIZE=g1-small
NODE_DISK_SIZE=50GB
```

**Comment by msau42** [comment]
Yah so this test got changed from using disk to using memory by #57037, which is when this test started failing.  So I suspect it is related to either a memory limit or memory pressure.

**Comment by shyamjvs** [comment]
That seems to have [fixed it](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/61). Thanks @msau42.

**Comment by porridge** [comment]
More references FTR:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/39
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-correctness/40
