### ISSUE TITLE
Send prevnode down the line into the resource's match function

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#5828]
We already run both the current node and the previous node through the match function when a watch event fires (to classify the event: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/tools/etcd_helper_watch.go#L320). Why not send both of them into the filter so resources can implement custom comparison? There's at least one case that @thockin brought up with endpoints (where he didn't want to fire a watch if the order of a list changed), and it might be useful in general?

 @lavalamp

**Comment by thockin** [comment]
I can live without it.  I am worried about making more couplings to etcd
specifics..

**Comment by bgrant0607** [comment]
Obsolete
