### ISSUE TITLE
Services unreachable as they age

### ISSUE THREAD

**Issue by angadn** [kubernetes/kubernetes#58286]
As seen on: https://stackoverflow.com/questions/48263580/kubernetes-services-unreachable-as-they-age

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I've been having a really frustrating issue where Kubernetes services randomly stop being available on their cluster IPs after around a few hours of deployment. They almost seem to be ageing.

My pods are having `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet`. Here is where things get interesting - I have two namespaces (staging and production) on the afflicted cluster. On another identical cluster with just one namespace, this issue hasn't seem to have appeared yet!

On trying to look at the `kube-proxy` logs, here is what I see:

```
    admin@gke ~ $ tail /var/log/kube-proxy.log
    E0115 12:13:01.669222       5 proxier.go:1372] can't open "nodePort for staging/foo:foo-sip-1" (:31765/tcp), skipping this nodePort: listen tcp :31765: bind: address already 
    in use
    E0115 12:13:01.671353       5 proxier.go:1372] can't open "nodePort for staging/foo:http-api" (:30932/tcp), skipping this nodePort: listen tcp :30932: bind: address already in use
    E0115 12:13:01.671548       5 proxier.go:1372] can't open "nodePort for staging/our-lb:our-lb-http" (:32477/tcp), skipping this nodePort: listen tcp :32477: bind: address alrea
    dy in use
    E0115 12:13:01.671641       5 proxier.go:1372] can't open "nodePort for staging/foo:foo-sip-0" (:30130/tcp), skipping this nodePort: listen tcp :30130: bind: address already 
    in use
    E0115 12:13:01.671710       5 proxier.go:1372] can't open "nodePort for default/foo:foo-sip-0" (:30132/tcp), skipping this nodePort: listen tcp :30132: bind: address already 
    in use
    E0115 12:13:02.510177       5 proxier.go:1372] can't open "nodePort for default/our-lb:our-lb-http" (:31613/tcp), skipping this nodePort: listen tcp :31613: bind: address alrea
    dy in use
    E0115 12:13:06.577412       5 server.go:661] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
    E0115 12:13:11.578446       5 server.go:661] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
    E0115 12:13:16.580441       5 server.go:661] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
    E0115 12:13:21.583691       5 server.go:661] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
```

I've now deleted one namespace from the afflicted cluster and the remaining one seems to have fixed itself; but I am curious about why Kubernetes didn't warn me at the time of resource creation, and if it *wasn't* competing for resources, then why does it reassign them later on in a way that causes this issue? This can't be a DNS cache issue, because `getent hosts` shows me the right cluster IP for the service - that IP just isn't reachable! It really seems to me to be a **bug in the Kubernetes networking setup.**

Should I be creating an issue, or is there something obvious that I'm doing incorrectly?
**What you expected to happen**:
My services should be reachable by their internal cluster IP for all eternity

**How to reproduce it (as minimally and precisely as possible)**:
*As documented in What Happened*

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11-gke.1", GitCommit:"3500f53730c1fea7b57901977df165c3eb317bce", GitTreeState:"clean", BuildDate:"2017-12-08T18:05:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
gcloud n1

- OS (e.g. from /etc/os-release):
Default as is for GKE

- Kernel (e.g. `uname -a`):
Linux gke-asterisk-default-pool-227fb1ab-gq9t 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 GNU/Linux

@kubernetes/sig-network-bugs

**Comment by angadn** [comment]
@kubernetes/sig-network-bugs

**Comment by wedgeV** [comment]
Same issue here, seems to be triggered by `kube-proxy` getting restarted for some reason, and it's previously allocated ports not getting properly released.

**Comment by afking** [comment]
Same issue
