### ISSUE TITLE
kubeadm crt for kube-apiserver

### ISSUE THREAD

**Issue by kweisamx** [kubernetes/kubernetes#58291]
I want to use the restful api to call  kubernetes apiserver to get information
But When I try this 

```
APISERVER=$(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")
TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
curl $APISERVER/api --header "Authorization: Bearer $TOKEN" --cacert /etc/kubernetes/pki/ca.crt 
```
and It will output 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

I give the crt and token, but why it still show system:anonymous?

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.0
- Cloud provider or hardware configuration:
bare metal
- OS (e.g. from /etc/os-release):
ubuntu
- Install tools:
kubeadm

**Comment by liggitt** [comment]
verify $TOKEN actually contains the content you expect... if you are actually passing a token, you'll either get a 401 or be treated as the user the token identifies, not be treated as system:anonymous

this might be a better way to extract the token:

```
TOKEN=$(
  kubectl get secret --field-selector type=kubernetes.io/service-account-token -o name | \
  grep default-token- | head -n 1 | \
  xargs kubectl get -o 'jsonpath={.data.token}' | \
  base64 -D
)
```

/close
