### ISSUE TITLE
Move pkg/api helpers into pkg/apis/core

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#58292]
Follow-ups of https://github.com/kubernetes/kubernetes/pull/53651:

- [ ] move pkg/api/v1/service https://github.com/kubernetes/kubernetes/pull/58297
- [ ] move pkg/api/pod
- [ ] move pkg/api/v1/pod
- [ ] move pkg/api/endpoints
- [ ] move pkg/api/v1/endpoints
- [ ] move pkg/api/resource
- [ ] move pkg/api/v1/resource
- [ ] move pkg/api/v1/node
- [ ] move pkg/api/ref
- [ ] Move pkg/api/ref to only user plugin/pkg/auth/authorizer/node
- [ ] Move pkg/api/events to only user pkg/printers/internalversion
- [ ] Update import restrictions on pkg/apis/core

**Comment by sttts** [comment]
Commits are here https://github.com/kubernetes/kubernetes/pull/55492, but that monster PR is hard to review.

**Comment by lavalamp** [comment]
Is this a good idea? Won't we have to copy these things for every version? Do we really want helper functions to be part of our api surface area?

**Comment by sttts** [comment]
@lavalamp we discussed that already in https://github.com/kubernetes/kubernetes/pull/58297#discussion_r161750892. Also note that this is not about moving them to k8s.io/api anyway, just inside pkg/ of k/k.
