### ISSUE TITLE
Add option to configure load balance algorithm to service

### ISSUE THREAD

**Issue by cpnielsen** [kubernetes/kubernetes#58329]
Feature request:

When using `ipvs`, it is possible to set a specific scheduler up that determines, cluster-wide, which algorithm to use; `round-robin`, `least-connection`, etc.

It would be useful to have this option available on individual services. When no annotation is set or an unsupported algorithm is defined (or `ipvs` is not used), the service would fall back to the default set up for `kube-proxy`.

This would allow you to go with `round-robin` for your web service, `least-connections` for your database service, etc.

My suggestion would be to add it as a simple option, `scheduler` which would default to `rr` and offer the same options as `ipvs`. Alternatively, some "generic" names could be used to abstract it out to be future-proof.

/kind feature

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1

**Comment by m1093782566** [comment]
The problem is only IPVS proxier support algorithm other than rr and IPVS proxier is still an beta feature although there is a plan for moving it forward GA in v1.10.

**Comment by cpnielsen** [comment]
@m1093782566 I can understand, and it's not urgent, but I imagine there is most definitely a use case although it likely falls in the "nice to have"-category. My impression is also that above a certain size, IPVS is the only option (due to performance regressions at scale with iptables-based routing).

**Comment by namreg** [comment]
see https://github.com/kubernetes/kubernetes/issues/58329
