### ISSUE TITLE
Kubelet sandbox GC can close hostPorts that are in use by a different pod

### ISSUE THREAD

**Issue by awh** [kubernetes/kubernetes#58335]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

It is possible for sandbox GC to close a hostPort that is held open by kubelet, even though that hostPort is in use by a running pod.

**What you expected to happen**:

Sandbox GC should only close hostPorts if they were opened by kubelet on behalf of the sandbox in question.

**How to reproduce it (as minimally and precisely as possible)**:

This is not easy to reproduce because I believe it requires a preceding error tearing down pod networking. I think it goes something like this:

1. Pod A specifying hostPort 1234 is started. Kubelet opens the port to make sure it isn't in use, and installs NAT mappings that direct traffic to pod A.
1. Pod A is terminated by a deployment upgrade
1. Pod B specifying hostPort 1234 is started. Kubelet opens the port to make sure it isn't in use, and installs NAT mappings that direct traffic to pod B.
1. Sandbox GC for pod A closes hostPort 1234

I suspect the sandbox GC kicking in is contingent on the teardown for pod A not completing successfully for some reason.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0
- Install tools:
- Others:

**Comment by KielChan** [comment]
hi, i have came up with this problem yesterday, runtime gc will removing veth pairs when pod was deleted already but the the same name pod reassigned to the same node.
when gc failed on the first time(i.e. old pod was removed from the node),the second time(i.e. new pod reassigned to the node with same name)gc will remove the new pod veth pairs.

so, what i want to know is that why sandbox gc not consistent with kill container?if sandbox not gc already, new pod will never ever renewed.
