### ISSUE TITLE
CPU Manager using Node-level Checkpointing manager

### ISSUE THREAD

**Issue by flyingcougar** [kubernetes/kubernetes#58339]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
CPU manager uses its own checkpointing mechanism.

**What you expected to happen**:
CPU Manager uses Node-level Checkpointing manager (#56040)

**Comment by fejta** [comment]
@kubernetes/sig-node-feature-requests

**Comment by ConnorDoyle** [comment]
/kind cleanup
/assign
Blocked on main checkpoint manager PR

**Comment by ConnorDoyle** [comment]
/remove-lifecycle rotten
see fix in #59214
