### ISSUE TITLE
externalTrafficPolicy=Local(NodePort) source IP error

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes/kubernetes#58338]
i set key externalTrafficPolicy=Local in service type NodePort
and get wrong source IP: 10.1.29.23 and 10.4.59.1
10.1.29.x - k8s nodes subnet, 10.4.x.x - k8s pods subnet.

https://github.com/kubernetes/kubernetes/issues/57922#issuecomment-357562970

/kind bug
/sig network

**Environment**:
- Kubernetes version (use `kubectl version`): api v1.8.1 / kubectl v1.6.1
- Cloud provider or hardware configuration: hardware (vmware)
- OS (e.g. from /etc/os-release): CoreOS 1520.8.0
- Kernel (e.g. `uname -a`): Linux wd-test-m1 4.13.9-coreos #1 SMP GenuineIntel GNU/Linux
- Install tools:
- Others: 
flannel Backend Type: host-gw
kube-proxy --proxy-mode=iptables

**Comment by MrHohn** [comment]
Trying to understand --- does the request come out of a pod that locates on the same node?

In current implementation, when externalTrafficPolicy=Cluster, all packets targeting a nodePort service will traverse KUBE-MARK-MASQ chain first, which means:
- If a packet is forwarded to a pod on a different node, its source IP will be the node IP.
- If a packet is forwarded to a pod on the same node, its source IP will be the bridge network's IP.

Need to check the externalTrafficPolicy=Local(NodePort) case.

**Comment by beatlejuse** [comment]
request out of the ыныеуь, which is outside the Kubernetes cluster

**Comment by beatlejuse** [comment]
@MrHohn 
request out of the system, which is outside the Kubernetes cluster

**Comment by FengyunPan2** [comment]
I met this issuse too, any comment?

**Comment by bowei** [comment]
Can you give a tcpdump of the relevant flow (SYN/SYNACK/ACK exchange would be sufficient)

**Comment by MrHohn** [comment]
@beatlejuse Sorry for the delay, I failed to reproduce it in on my GCE cluster. As you are using flannel, I suspect it is the same issue as https://github.com/kubernetes/kubernetes/issues/52096 (and couple previously closed ones https://github.com/kubernetes/kubernetes/issues/44963, https://github.com/coreos/flannel/issues/734). Would be great if you could check whether that is the case.

**Comment by beatlejuse** [comment]
@MrHohn  about #52096 - yes, but i don't using Calico. and there's no solution.
i use flannel 0.10.0

**Comment by beatlejuse** [comment]
sum up:
1. the externalTrafficPolicy=Local option does not work as expected.
2. even if externalTrafficPolicy=Local worked, it makes traffic transmission more uncomfortable.

I decided not to use this method to transfer the source address.

**Comment by fpytloun** [comment]
I have just the same issue - using NodePort with externalTrafficPolicy=Local does not work and I cannot see correct source IP from pods.
Does anyone came up with solution or workaround to this issue?
