### ISSUE TITLE
controller manager deletes nodes before they have a chance to get ready

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#58334]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Cloud provider was having issues, so a newly provisioned node was not found shortly after creation. As soon as the node registers itself to apiserver, controller-manager immediately deletes it. This leads to error loops in kubelet on the new node as it doesn't expect itself to be deleted asynchronously, and also prevents pods from being scheduled, despite the node being perfectly healthy.

**What you expected to happen**:
controller-manager should wait for `node-startup-grace-period` to give the node a chance to come up  and the cloud provider to update its state. This allows the node to come up as expected, irrespective of the state of the cloud provider.

**Comment by jsravn** [comment]
This also affected us on vsphere. So it's a general issue for any cloud provider.

**Comment by prashima** [comment]
@kubernetes/vmware 
@prashima @divyenpatel

**Comment by cheftako** [comment]
Closing for lack of response
/close

**Comment by jsravn** [comment]
Sorry for missing the notification. It may be fixed - I haven't managed K8s clusters in a while now. It's pretty rare this happens - the provider has to fail to respond, or respond that it doesn't know about an instance.

Digging out my old notes, this is the log I saw:

```
I0116 11:56:58.692207       1 node_controller.go:585] Controller observed a new Node: "apiserver-00.s.sandbox.solar.sky"
I0116 11:56:58.692297       1 controller_utils.go:237] Recording Registered Node apiserver-00.s.sandbox.solar.sky in Controller event message for node apiserv
er-00.s.sandbox.solar.sky
I0116 11:56:58.692661       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"apiserver-00.s.sandbox.solar.sky", UID:"5aac2b87-fab4-11
e7-8d2d-005056a93029", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node apiserver-00.s.sandbox.solar.sky event:
 Registered Node apiserver-00.s.sandbox.solar.sky in Controller
E0116 11:56:58.740211       1 datacenter.go:75] Failed to find VM by Path. VM Path: Non-Production/sandbox/k8s-node/apiserver-00.s.sandbox.solar.sky, err: vm 
'Non-Production/sandbox/k8s-node/apiserver-00.s.sandbox.solar.sky' not found
I0116 11:56:58.740270       1 node_controller.go:721] Deleting node (no longer present in cloud provider): apiserver-00.s.sandbox.solar.sky
I0116 11:56:58.740290       1 controller_utils.go:237] Recording Deleting Node apiserver-00.s.sandbox.solar.sky because it's not present according to cloud pr
ovider event message for node apiserver-00.s.sandbox.solar.sky
I0116 11:56:58.740476       1 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"apiserver-00.s.sandbox.solar.sky", UID:"5aac2b87-fab4-11
e7-8d2d-005056a93029", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node apiserver-00.s.sandbox.solar.sky event: D
eleting Node apiserver-00.s.sandbox.solar.sky because it's not present according to cloud provider
```
