### ISSUE TITLE
CSI plugin does not support user credentials

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#58343]
Currently CSI plugin does not pass user credentials in NodePublishVolume and NodeUnpublishVolume calls.
/sig storage
/kind bug
/assign @sbezverk

**Comment by liggitt** [comment]
this is covered in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md#csi-credentials and is not part of the initial alpha release, but is planned

/close

**Comment by sbezverk** [comment]
@liggitt I am working on adding this functionality to CSI and this issue was opened to match with PR I am about to push. Please do not close right away, without at least asking in the thread the reason for this issue.

**Comment by liggitt** [comment]
Sorry for the confusion. If it is tracking current feature work it should not be classified as a bug

/open
/kind feature

**Comment by sbezverk** [comment]
@liggitt thanks, I was not sure whether it was a feature or bug, since certain fields were just missing from NodePublishVolumeRequest struct.
