### ISSUE TITLE
Add a subresource for Node.ConfigSource?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#58362]
Use-cases:
- Restrict access to the config source as tightly as possible, even if write access to other parts of Node is more widespread
- Providers can use webhook authorizers that return a deny response to block access to Node.ConfigSource, in the case that they are responsible for managing node config, without having to restrict write access to the entire Node.

This needs to be figured out before dynamic config can graduate.

/cc @bgrant0607 @thockin @liggitt @mikedanese @ihmccreery @dchen1107 @luxas

**Comment by mikedanese** [comment]
This is the approach we should take if we want to lock down node config updates separately from node spec updates.

**Comment by mtaufen** [comment]
Any other opinions on this? Jordan had thought it a little strange to do a subresource that's intended for giving access to a *more* privileged entity, since I guess most subresources are for giving access to *less* privileged entities than touch the primary resource. But maybe that's just tradition, and we can buck the trend?

**Comment by mikedanese** [comment]
The /approve subresource on certificatesigingrequests has that same semantics. I don't think there a really any other options if we want to handle this in the Authorizer subsystem.

**Comment by mtaufen** [comment]
xref #59805

**Comment by liggitt** [comment]
It seems odd to forbid setting/updating this field in the node spec via the normal Node API endpoint. That breaks `apply`, setting during creation, etc. I also can't think of any other fields that work this way except pod.spec.nodeName, which was built that way for the following reasons:
* pod.spec was intended to be largely immutable
* assignment of pod.spec.nodeName was seen as the domain of the scheduler component, which was intended to operate against the pods/binding subresource

node.spec is not immutable, and there's not a clear component responsible for updating node config.

**Comment by jberkus** [comment]
If this feature looks like it's going to get completed in the next couple days for Code Freeze, please add status/approved-for-milestone to it.  Otherwise, please change the milestone.  Thanks!

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/pull/59805#issuecomment-381660154

/close
