### ISSUE TITLE
Unable to decrypt ETCD data

### ISSUE THREAD

**Issue by gerardo8a** [kubernetes/kubernetes#58361]
/kind bug

**What happened**:
I encrypted the ETCD data using this documentation https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**What you expected to happen**:
Before encrypting I verified the data in ETCD was not encrypted. After encrypting all data I verified again in ETCD and data was encrypted. Verified by following the steps on the documentation. 

I followed the de-encryption section to revert back the encrypted data, but the data does not get reverted back, I followed the steps mentioned in the documentation by adding identity as the first provider but data does not get de-encrypted.

**How to reproduce it (as minimally and precisely as possible)**:
Encrypted all my etcd data but reverting back does not work.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+8e15523423554", GitCommit:"7186af2f6cd0df870c6cab4ab7b987a131b19eb8", GitTreeState:"dirty", BuildDate:"2017-10-04T00:41:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+8e15523423554", GitCommit:"7186af2f6cd0df870c6cab4ab7b987a131b19eb8", GitTreeState:"dirty", BuildDate:"2017-10-04T00:41:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Hardware on premises 

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.1 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.1:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.1"

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
Sounds like the same issue as https://github.com/kubernetes/kubernetes/issues/49565

**Comment by liggitt** [comment]
Actually, this was fixed in 1.7.8:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.7.md#changelog-since-v177

> When performing a GET then PUT, the kube-apiserver must write the canonical representation of the object to etcd if the current value does not match. That allows external agents to migrate content in etcd from one API version to another, across different storage types, or across varying encryption levels. This fixes a bug introduced in 1.5 where we unintentionally stopped writing the newest data. (#48394, @smarterclayton)

A separate bug is affecting the 1.8 and 1.9 branches, but 1.7.8+ is working properly.

Also note the documentation does not include the --all-namespaces flag to transform secrets in all namespaces. Opened https://github.com/kubernetes/website/pull/6985/files to fix that
