### ISSUE TITLE
code-generator: different deep copy functions generated

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#58374]
**What happened**:
We get different code generated on different computers.

Common things:
- Exactly the same code and dependencies. Copied the directory from one computer to another one, ran deep copy generator and the result is different.
- Latest `k8s.io/code-generator` from `release-1.8` branch - 306be794f1b124a9c939ab168e9ea3944387e66b
- `k8s.io/gengo` - 1ef560bbde5195c01629039ad3b337ce63e7b321
- Go 1.9.2

Result 1 - current `master` branch:
- Two mac laptops
- Travis CI. Linux builder running Ubuntu Trusty

Result 2 - PR https://github.com/atlassian/smith/pull/216:
- Internal CI builder. Ubuntu linux, build runs in a docker container with `FROM ubuntu:latest`
- Arch linux laptop.

We have another (internal) codebase where we are seeing the same issue with the same type (`metav1.Time`).

**What you expected to happen**:
The same code should be generated always.

**How to reproduce it (as minimally and precisely as possible)**:
1. You'll need `dep` and `Bazel`
2. Clone `go get -u github.com/atlassian/smith`
3. Run `make setup-base`
4. Run `make generate`
5. What version are you getting? If `git diff` is not showing anything it is version 1.

/kind bug
/sig api-machinery
/cc @sttts

**Comment by jennybuckley** [comment]
@jennybuckley

**Comment by sttts** [comment]
I am happy to debug this. But please cut it down to a simple deepcopy-gen call, i.e. without Makefile magic and bazel around. Even better: add a simple Dockerfile with the prerequisites and the call (direct deepcopy-gen call, no bazel please) which shows the different output on Linux (I have a Mac).

**Comment by sttts** [comment]
k8s.io/code-generator is not pinned in Gopkg.toml. This will break.

**Comment by ash2k** [comment]
/remove-lifecycle rotten
/lifecycle frozen

Still happens with 1.10 code generator sometimes - very annoying :) On both Linux and Mac. I need to look into this again - I've tried and made some progress but haven't gotten to the bottom of it.

**Comment by liggitt** [comment]
/close
for insufficient information and inactivity. please reopen if more details are available
