### ISSUE TITLE
awscli should not be installed at test time (and related pip warnings are distracting)

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#58387]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/priority critical-urgent
@kubernetes/sig-testing-bugs 

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54294/pull-kubernetes-e2e-kops-aws/69102/ failed

```
I0117 12:25:44.217]   Running setup.py install for PyYAML
I0117 12:25:44.322]     checking if libyaml is compilable
I0117 12:25:44.322]     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
I0117 12:25:44.335]     build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
I0117 12:25:44.335]      #include <yaml.h>
I0117 12:25:44.335]                       ^
I0117 12:25:44.336]     compilation terminated.
I0117 12:25:44.361]     
I0117 12:25:44.361]     libyaml is not found or a compiler error: forcing --without-libyaml
I0117 12:25:44.362]     (if libyaml is installed correctly, you may need to
I0117 12:25:44.362]      specify the option --include-dirs or uncomment and
I0117 12:25:44.362]      modify the parameter include_dirs in setup.cfg)
```

**Comment by ixdy** [comment]
That wasn't actually a failure - just a red herring in the log (which we should maybe fix, or at least hide).

**Comment by ixdy** [comment]
@kubernetes/test-infra-maintainers any thoughts on how we can make `pip` be less spammy here? (besides not using `pip` :)

**Comment by krzyzacy** [comment]
the actual failure is caused by quota in the new cncf aws account, which is being working on by aws side

**Comment by BenTheElder** [comment]
> (besides not using pip :)

OK but don't don't install python libraries at runtime? :-P
@krzyzacy doesn't seem to think anything from test-infra specifically is doing this (in this job anyhow).

**Comment by ixdy** [comment]
@BenTheElder we're doing a `pip install awscli` in kubetest:

https://github.com/kubernetes/test-infra/blob/c4be9c30bffbbb4339c1772a801f5ef03f2a9738/kubetest/main.go#L845-L851

**Comment by BenTheElder** [comment]
:astonished: we should not do that. let's move that into the image build.

**Comment by porridge** [comment]
@krzyzacy do you have a reference for the AWS quota problem? It seems to be broken still (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54294/pull-kubernetes-e2e-kops-aws/69061/)

**Comment by krzyzacy** [comment]
let's ref https://github.com/kubernetes/kubernetes/issues/58709 in the future, I'll close this one as this is not the actual failure

/assign
/close

**Comment by BenTheElder** [comment]
FWIW I'm going to make kubekins-e2e preinstall this now.
