### ISSUE TITLE
start checking taints wherever we check for node.Spec.Unschedulable

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#58406]
forked from #25320

As from the discussion with @gmarek and @bgrant0607 we have to start checking taints wherever we check for node.Spec.Unschedulable. Also overlaps on some parts with #57690 

/sig node
/assign

**Comment by yastij** [comment]
cc @augabet

**Comment by k82cn** [comment]
No sure the discussion history :); personally, prefer to deprecate `Unschedulable` and replace it with taint.

**Comment by yastij** [comment]
@k82cn - same here, the goal would be to deprecate its usage, start checking taints everywhere unschedulable is used. Also, as long as we as we have v1, we might have to keep checking for both.

**Comment by k82cn** [comment]
great, there's same subtask in my mind:

1. add deprecated description to `Unschedulable`
2. define the taint for `Unschedulable`
3. update `kubectl cordon/uncordon` command
4. replace `Unschedulable` with taint
5. maybe others ??

**Comment by yastij** [comment]
@k82cn - yup, but for 4 it is more something like check taints wherever we checn for unschedulablr, since we cannot just replace `node.Spec.Unschedulable` until v1 is gone.

**Comment by k82cn** [comment]
@yastij , my major point is to handle it task by task to make sure we did not miss anything :).

**Comment by yastij** [comment]
yes we definitely should

**Comment by yastij** [comment]
@gmarek - should we define a specific taint for unschedulable ? (i.e what happens when a user uses cordon/uncordon)

**Comment by gmarek** [comment]
I'm not sure about having specific Taint for Unschedulable is a good idea. Pretty much any Taint with NoSchedule effect will do (and this is what we should be checking).

**Comment by yastij** [comment]
@gmarek - I agree, in case of `kubectl cordon` we can add a taint with key `node.kubernetes.io/cordon` or something like that with a `NoSchdeule` effect. This might help us especially if the node has no taints.

**Comment by k82cn** [comment]
> Pretty much any Taint with NoSchedule effect will do (and this is what we should be checking).

@gmarek , not sure whether we should handle `Unschedulable` specially; AFAIK, `kubectl cordon` set this flag for node maintenance, this taint should not be tolerated.

**Comment by gmarek** [comment]
The whole point of moving from `Unschedulable` to Taints is to make things more configurable.

@bsalamat @davidopp as they're decision makers here.

**Comment by resouer** [comment]
If we are discussing about deprecate/re-implement `kubectl cordon` by Unschedulable taint, +1 as it make sense.

Current cordon is keeping causing confusion in community since you can always taint it, and it's what Kubernetes setup is doing for master today.

**Comment by bsalamat** [comment]
> not sure whether we should handle Unschedulable specially; AFAIK, kubectl cordon set this flag for node maintenance, this taint should not be tolerated.

I agree with @gmarek that we should use NoSchedule taint. I also agree that generally no pod should tolerate NoSchedule taints, but they may want to do so if the desire, knowing that anything could happen to the node they will scheduled on. For example, today DS pods tolerate "Unschedulable" bit. They may as well want to tolerate "NoSchedule" taints.

**Comment by k82cn** [comment]
> I also agree that generally no pod should tolerate NoSchedule taints, but they may want to do so if the desire, knowing that anything could happen to the node they are scheduled on. 

Agree; it's up to 'user' to decide whether tolerates the taint, we just need to taint it and doc what's happened in node for taints :)

**Comment by bsalamat** [comment]
> Agree; it's up to 'user' to decide whether tolerates the taint, we just need to taint it and doc what's happened in node for taints :)

We should have a mechanism that allows a cluster admin to limit types of tolerations that users can set. This is needed to prevent abuse in multi-tenant clusters. For example, cluster admin may want to taint nodes with rare resources to prevent pods from certain group of users to land on them. Users shouldn't be able to tolerate such taints. That said, this is a separate topic of its own which is related to policy and should be discussed separately.

**Comment by yastij** [comment]
@bsalamat - we’re already facing this in production for our spare nodes. I’ll bring this up in our next sig-meeting, I’ll also file an issue for this
