### ISSUE TITLE
Support strategic merge patch for custom resources

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#58414]
We should support strategic merge patch (smp) for custom resources if we plan to move CRDs to GA [1].

Currently, we face the following issues with regards to not supporting strategic merge patch:

- The garbage collector tries to perform a smp on the custom resources to remove the owner reference (https://github.com/kubernetes/kubernetes/issues/56348).
- Discussion for CRDs supporting smp only on metadata (https://github.com/kubernetes/kubernetes/pull/56606).
- We use special casing for custom resources (https://github.com/kubernetes/kubernetes/pull/53558) to generate an error message specifying that smp is not supported. We want to avoid such special casings.
- When a patch (json, merge) conflict occurs, the server fallsback to a smp to detect overlapping patch content. This assumption does not hold true for custom resources (https://github.com/kubernetes/kubernetes/issues/58017, https://github.com/kubernetes/kubernetes/pull/58064). To fix this, we will need to use special casing again, which is not desired.

/cc @sttts @deads2k @enisoc @mbohlool @liggitt @lavalamp @caesarxuchao @jennybuckley 

[1] https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/07JKqCzQKsc

**Comment by liggitt** [comment]
> We should support strategic merge patch (smp) for custom resources if we plan to move CRDs to GA 

I'm not sure I agree. Strategic merge patch has proved problematic both client-side and server-side. Designing a major addition to it seems like an investment in a direction we don't want to go.

**Comment by sttts** [comment]
> I'm not sure I agree.

Let's clarify: we need PATCH conflict retries for CRDs. If that is through SMP or something else does not matter. Or we officially accept that the PATCH behaviour is different for CRDs. Not sure we want this kind compromises.

**Comment by nikhita** [comment]
I'm not sure if we are going to support this but removing the stale label until it is decided what to do.

/remove-lifecycle stale

**Comment by nikhita** [comment]
> JSONPatch and JSON merge patch should work today, I think?

Yes, they do. :+1:

**Comment by liggitt** [comment]
SMP requirement for patch is removed by https://github.com/kubernetes/kubernetes/pull/63146

GC reliance on SMP should be tracked/resolved in https://github.com/kubernetes/kubernetes/issues/56348

agree with @lavalamp that we don't want to extend SMP usage to CRD

/close

**Comment by cben** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility says for strategic-merge-patch / CRDs column: "No, but similar functionality planned".  Should this be updated to "No" or "Not planned"?

**Comment by nikhita** [comment]
> Should this be updated to "No" or "Not planned"?

@cben Thanks for pointing it out. Created https://github.com/kubernetes/website/pull/10994 to say "No".
