### ISSUE TITLE
Update local pv e2e test for mount propagation

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#58416]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
Now that the local provisioner uses mount propagation, the provisioner e2e test should also test adding mount points after the provisioner has started

**Comment by msau42** [comment]
@ianchakeres, would you have time to look into this?

**Comment by ianchakeres** [comment]
FYI: @jsafrane
