### ISSUE TITLE
how to set  TXT DNS

### ISSUE THREAD

**Issue by liwjGhostcloud** [kubernetes/kubernetes#58424]
in my cluster i want to config a txt dns record that my eureka cluter can use dns add node.

the question 1: i find kube-dns have dnsmasq and i find it can config txt dns record and how to set TXT record just like `txt-record=txt.global.eureka.storytel,xxxx.xxxxx.xxxxx`
and the question 2: how to auto add record in the last of `txt-record`  when pod created

my kuberenets version is 1.8

**Comment by fejta** [comment]
Please use stackoverflow for support questions
/close
