### ISSUE TITLE
Is it meaningful about "TODO: rename the package of e2e_node to e2e-node"?

### ISSUE THREAD

**Issue by lcfang** [kubernetes/kubernetes#58423]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind feature

**What happened**:
As I see blow https://github.com/kubernetes/kubernetes/blob/b7100f1ee7231617891a100dd34b3490a1f578e4/test/e2e_node/doc.go#L18
 I wonder if it is meaningful? And what's the meaning of it?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): the latest k8s code
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fejta** [comment]
It means the package should be `e2e_node` not `e2e-node`. 

I don't think we need an issue for every TODO
/close
