### ISSUE TITLE
kubefed init authorization issue ...API server is running cases...

### ISSUE THREAD

**Issue by rangapv** [kubernetes/kubernetes#58432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
I installed kubefed init and tried the following two ways ...

1. sudo kubefed init fellowship --host-cluster-context=kubernetes-admin@kubernetes --dns-provider="google-clouddns" --dns-zone-name="example1.com." --etcd-persistent-storage=false --api-server-service-type="NodePort"
The federation API comes up but attempt to login fails at the browser....

Error at APIServer login:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

The second option I tried was

2. sudo kubefed init fellowship --host-cluster-context=kubernetes-admin@kubernetes --dns-provider="google-clouddns" --dns-zone-name="example1.com." --etcd-persistent-storage=false --api-server-service-type="NodePort"  --api-server-advertise-address="10.128.0.22" --apiserver-enable-basic-auth=true --apiserver-enable-token-auth=true --apiserver-arg-overrides="--anonymous-auth=false,--v=4" --controllermanager-arg-overrides="--controllers=services=false"

Here the login pop-up come up but I cant login.  
What is the login here , I tried kubectl config view and got the encode credentials (apparently it is using fellowship-basic-auth) which when I input with "admin" login and it gets me an API view...
Should I expect to see an dashboard of some sorts ?

**What you expected to happen**:
API-dashboard of some sorts....

**How to reproduce it (as minimally and precisely as possible)**:
Pls follow step 1 / step 2 above

**Anything else we need to know?**:
Federation API is coming up..it is just that it is using a default access which I am not able to access in STEP2 listed above...

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
GCP COmpute engine
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux instance-18-kubefed 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubefed init
- Others:

**Comment by rangapv** [comment]
sig/multicluster

**Comment by liggitt** [comment]
Please report kubefed issues against https://github.com/kubernetes/federation/issues

/close
