### ISSUE TITLE
Kubernetes-master juju layer hardcodes old nginx-ingress-controller image

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#58449]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

kubernetes-master juju layer harcodes old nginx-ingress-controller image:
```
    context['ingress_image'] = \     
        "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.13"     
    if arch() == 's390x':     
        context['ingress_image'] = \     
            "docker.io/cdkbot/nginx-ingress-controller-s390x:0.9.0-beta.13"
```

Because of that deployed environment is affected by https://github.com/kubernetes/ingress-nginx/issues/1876 and possibly other nginx-ingress-controller bugs

**What you expected to happen**:

Ideally I'd like the image to be configured using config option. If that's not possible I'd like the charm to be frequently updated so that it always uses latest stable image.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy  the kubernetes-worker juju charm with "ingress=true" config option.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0-91-generic
- Install tools: juju
- Others:

**Comment by errordeveloper** [comment]
@ktsakalozos do Juju-related issues belong here or perhaps folks should be referred to https://github.com/juju-solutions/bundle-canonical-kubernetes?

**Comment by ktsakalozos** [comment]
Thank you @jacekn for reporting this, and @errordeveloper for pointing to the project with the kubernetes bundle.

Yes it would be better for issues to be opened against https://github.com/juju-solutions/bundle-canonical-kubernetes so we have better visibility.

**Comment by errordeveloper** [comment]
@ktsakalozos thanks for your response. Is there an issue about whether `./cluster/juju` could be deprecated and remove in favour of the new repo or any other plans of this sort?

**Comment by ktsakalozos** [comment]
Hi @errordeveloper, there is this old thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-cluster-lifecycle/6bDBuem0gQY/k_jF9WfDCgAJ .

But I do not see anyone moving to the new repo https://github.com/kubernetes-providers

**Comment by fejta** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by errordeveloper** [comment]
@ktsakalozos I am tempted to close this...

**Comment by ktsakalozos** [comment]
@jacekn is it ok to close this issue from here and keep tracking it with:
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/470

**Comment by jacekn** [comment]
Yes I think so. If the juju-solutions project is better place to track I'll close this one.

**Comment by errordeveloper** [comment]
Thanks!
