### ISSUE TITLE
Kubeadm change the path of ca.crt from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt ?

### ISSUE THREAD

**Issue by kweisamx** [kubernetes/kubernetes#58464]
There ois No crt in the path of /var/run/secrets

I use kubeadm to install my kubernetes cluster, and where is the ca.crt location?

Thanks

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9
- Cloud provider or hardware configuration:
bare metal
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
Linux u1 4.4.0-87-generic
- Install tools:
Kubeadm

**Comment by timothysc** [comment]
For security and recoverable reboot conditions the location had changed to `--cert-dir=/var/lib/kubelet/pki` a while ago.
