### ISSUE TITLE
PodSecurityPolicy inside a namespace can't use ClusterRole, but works with Role

### ISSUE THREAD

**Issue by dimm0** [kubernetes/kubernetes#58495]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I created a ClusterRole with PodSecurityPolicy, and referenced it from a namespaced RoleBinding - it didn't work. Then I created exactly the same Role in that namespace and referenced that in RoleBinding - now it works.

**What you expected to happen**:
I expect the PodSecurityPolicies to work the same way as other RBAC rules and be able to use global ClusterRoles.

**How to reproduce it (as minimally and precisely as possible)**:

Broken:
```
kubectl create clusterrole psp:nautilus-user --verb=use --resource=podsecuritypolicy --resource-name=nautilususerpolicy
kubectl create rolebinding fake-user:psp:unprivileged --clusterrole=psp:nautilus-user --user=<user>
kubectl --as="<user>" auth can-i use podsecuritypolicy/nautilususerpolicy
no
```

Working:
```
kubectl create role psp:nautilus-user --verb=use --resource=podsecuritypolicy --resource-name=nautilususerpolicy
kubectl create rolebinding fake-user:psp:unprivileged --role=psp:nautilus-user --user=<user>
kubectl --as="<user>" auth can-i use podsecuritypolicy/nautilususerpolicy
yes
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Baremetal
- OS (e.g. from /etc/os-release):
Centos 7.4
- Kernel (e.g. `uname -a`):
Darwin dimm.sdsc.edu 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
- Install tools:
kubeadm

**Comment by liggitt** [comment]
when I run the first set of commands, `can-i` answers yes. are you running that in a script? authorization is based on a cache that can take a few ms to observe policy changes.

**Comment by liggitt** [comment]
my results:

```shell
kubectl create clusterrole psp:nautilus-user --verb=use --resource=podsecuritypolicy --resource-name=nautilususerpolicy
clusterrole "psp:nautilus-user" created
kubectl create rolebinding bob:psp:unprivileged --clusterrole=psp:nautilus-user --user=bob
rolebinding "bob:psp:unprivileged" created
kubectl --as="bob" auth can-i use podsecuritypolicy/nautilususerpolicy
yes

kubectl delete clusterrole psp:nautilus-user
clusterrole "psp:nautilus-user" deleted
kubectl delete rolebinding bob:psp:unprivileged
rolebinding "bob:psp:unprivileged" deleted
kubectl --as="bob" auth can-i use podsecuritypolicy/nautilususerpolicy
no

kubectl create role psp:nautilus-user --verb=use --resource=podsecuritypolicy --resource-name=nautilususerpolicy
role "psp:nautilus-user" created
kubectl create rolebinding alice:psp:unprivileged --role=psp:nautilus-user --user=alice
rolebinding "alice:psp:unprivileged" created
kubectl --as="alice" auth can-i use podsecuritypolicy/nautilususerpolicy
yes

kubectl delete role psp:nautilus-user
role "psp:nautilus-user" deleted
kubectl delete rolebinding alice:psp:unprivileged
rolebinding "alice:psp:unprivileged" deleted
kubectl --as="alice" auth can-i use podsecuritypolicy/nautilususerpolicy
no
```

**Comment by dimm0** [comment]
It really works now with your example. Sorry for bothering, I'll check my code again.
Thanks!

**Comment by dimm0** [comment]
The problem was:
```
  resources:
  - podsecuritypolicy
```

instead of

```
  resources:
  - podsecuritypolicies
```

Just as a follow-up, wouldn't it make sense for both to work?

**Comment by liggitt** [comment]
No, authorization treats resources opaquely. It doesn't do fuzzy matching or discovery to figure out singular -> plural conversions

**Comment by dimm0** [comment]
Ok, thanks
