### ISSUE TITLE
There is only one container log symlink in kubernetes1.5 but two in kubernetes1.6

### ISSUE THREAD

**Issue by zhangmingld** [kubernetes/kubernetes#58494]
**What happened**:
In our environment, we use "docker rm" to delete a "exited" k8s-managed container and we found that in kubernetes 1.5, the symlink is also deleted, but in kubernetes1.6, the symlink is not deleted.

When we check the code,we found ,in kubernetes1.5,the symlink is /var/log/containers,in kubernetes1.6,the symlink has two ,/var/log/containers and /var/log/pods

why we have two symlink in kubernetes1.6?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhangxiaoyu-zidif** [comment]
@zhangmingld  you found that kubernentes or docker created duplicated links in two different directory. And after running `docker rm`, one of these two links was left?

**Comment by YuxiJin-tobeyjin** [comment]
There are two symlinks;

**Comment by YuxiJin-tobeyjin** [comment]
@Random-Liu
