### ISSUE TITLE
No API token found for service account "default"

### ISSUE THREAD

**Issue by sree7569** [kubernetes/kubernetes#58508]
Hello,

I'm trying to create pods but it is giving below error.

[root@k8s-master pods]# kubectl create -f mysql.yaml

Error from server (ServerTimeout): error when creating "mysql.yaml": No API token found for service account "default", retry after the token is automatically created and added to the service account
[root@k8s-master pods]#

[root@k8s-master pods]# kubectl get serviceaccount
NAME      SECRETS   AGE
default   0         2h
[root@k8s-master pods]#
[root@k8s-master pods]#
[root@k8s-master pods]#
[root@k8s-master pods]# kubectl describe serviceaccount default
Name:           default
Namespace:      default
Labels:         <none>

Image pull secrets:     <none>

Mountable secrets:      <none>

Tokens:                 <none>

[root@k8s-master pods]#

How can I add the API token key ?. Please let me know if any details required.

**Comment by liggitt** [comment]
Your controller manager must be started with a `--service-account-private-key-file` flag, giving it the signing key to generate tokens.

The apiserver must be given the corresponding public key with a `--service-account-key-file` flag so it can verify the tokens.

See https://kubernetes.io/docs/admin/service-accounts-admin/#token-controller

/close
