### ISSUE TITLE
Need to fix data race when updating equivalence cache

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#58507]
Fix this TODO (raised by @bsalamat) : https://github.com/kubernetes/kubernetes/blob/30b89d830b7fd0827576853d6a0db44b66a90d3d/pkg/scheduler/core/generic_scheduler.go#L482

Part of: #58222  

One thoughts to fix this is, we can redesign the equivalence cache data structure to: 
1. Set `invalid` bool instead of deleting the entry. 
2. Include certain version tag in the entry, update the version per WRITE op (Update and Invalidate). 
2. Return the version after eCache predicate,  and check it before update eCache.

**Comment by k82cn** [comment]
Prefer to bsalamat@ 's option which is simpler :). Comparing to performance improvement by eCache, the lock is acceptable to me.

**Comment by yastij** [comment]
yup same here, going with the locking is easier and is acceptable. 

@resouer - also using a flag for invalidation might just move the problem from eCache to the flag ?

**Comment by resouer** [comment]
Oh I missed this notification somehow, busy on cleaning scheduler integration test.

Yep so if locking is acceptable, it should be cleanest way to fix this, optimistic control would be a more complicated story.

**Comment by yastij** [comment]
@resouer - are you handling this one ?

**Comment by resouer** [comment]
@yastij Already been taken by volunteer days ago :)
