### ISSUE TITLE
kubectl show old version of cluster after upgrade

### ISSUE THREAD

**Issue by dbuhtiyarov** [kubernetes/kubernetes#58514]
Hi Team

/kind bug
after cluster upgrade from version  1.9.1 to 1.9.2 (it went well) - "kubectl get nodes" show old version 
[root@****** ~]# kubectl get nodes
NAME                                        STATUS    ROLES     AGE       VERSION
****                        Ready     master    1d        **v1.9.1**
****                        Ready     <none>    1d        **v1.9.1**

in the same time

[root@**** ~]# kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.9.2
[upgrade/versions] kubeadm version: v1.9.2
[upgrade/versions] Latest stable version: v1.9.2
[upgrade/versions] Latest version in the v1.9 series: v1.9.2

Awesome, you're up-to-date! Enjoy!

[root@**** ~]# kubelet --version
Kubernetes v1.9.2

**Environment**:
- 1.9.1/1.9.2:
- AWS:
- Centos 7:

**Comment by zouyee** [comment]
1、delete node which has been joined
2、restart kubelet

**Comment by dbuhtiyarov** [comment]
**zouyee** Thank you su much - it's working now

**Comment by ckvtvm-arch** [comment]
same issue with control plane
