### ISSUE TITLE
Different Access modes for mounted volume in init container and actual container.

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kubernetes#58511]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
I am exploring persistent storage strategy for my services. I am using PersistentVolumes and PersistenVolumeClaims but the problem is that I am trying to mount the claim to initcontainer and container with different access modes. But currently you have to define the access mode in persistentVolumeClaim and then you have to mount the same claim to both initcontainer and contianer.

**What you expected to happen**:
What I want is that the initcontainer should mount the volume claim in write mode and do the required task and then the actual container mount the same volume claim in read only mode.

**How to reproduce it (as minimally and precisely as possible)**:
- Add a PersistentVolume.
- Add a PersistentVolumeClaim
- Try Mount this claim to initcontainer in ReadOnly mode and container in ReadWriteMany mode.

**Anything else we need to know?**:
Is there any way we can define different modes for initcontainer?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g. from /etc/os-release): linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mlmhl** [comment]
I think you can:

1. Set the access mode of the PVC as `ReadWrite`(`ReadWriteOnce` or `ReadWriteMany`, depends on what volume you are using), which means the volume should be mounted to the node as `ReadWrite` mode
2. Set `Pod.Spec.InitContainers.VolumeMounts.ReadOnly` to `false`(which is the default value), which means the volume should be mounted to the init container as `ReadWrite`
3. Set `Pod.Spec.Containers.VolumeMounts.ReadOnly` to `true`, which means the volume should be mounted to the actual container as `ReadOnly`

**Comment by andyzhangx** [comment]
This is not azure specific. I think you could define two sets of PV and PVC, one set is readonly, and another set is readwrite, and these two sets use same storage actually. BTW, even you set PV/PVC as readonly, container could still write data into PV/PVC, there is no read write resctricition in k8s actually.

**Comment by andyzhangx** [comment]
@mfaizanse It's a bug by design... [Access Modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) is only for matching PV now, `Pod.Spec.InitContainers.VolumeMounts.readOnly` could control actual readOnly or not in container.

**Comment by andyzhangx** [comment]
close this issue since it's by design, let me know if you have any question, thanks
/close
