### ISSUE TITLE
Failed to pull image kibana-openshift:5.6.3": rpc error: code = 2 desc = net/http: request canceled

### ISSUE THREAD

**Issue by MohamedElso** [kubernetes/kubernetes#58526]
I can't pulled a new image from my Repository... I get the following error message:
Failed to pull image "xyz:5500/my/kibana-openshift:5.6.3": rpc error: code = 2 desc = net/http: request canceled

Thanks

**Comment by fejta** [comment]
Please try stackoverflow and/or the kubernetes-users channel on slack
