### ISSUE TITLE
CSI Volume Plugin: Need to handle UserCredentials

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#58524]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:[
According to CSI Spec, NodePublishVolume](https://github.com/container-storage-interface/spec/blob/master/spec.md#node-service-rpc) should get user credentials in its own map. 

**What you expected to happen**:
CSI Volume plugin should get secret and pass into user credentials during volume publish calls.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig storage
@saad-ali @jsafrane @vladimirvivien @sbezverk 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
also see https://github.com/kubernetes-csi/external-provisioner/pull/29

**Comment by sbezverk** [comment]
@rootfs I think it is duplicate of the issue I submitted: https://github.com/kubernetes/kubernetes/issues/58343

**Comment by rootfs** [comment]
thanks @sbezverk, let's make this a 1.9 bug and wait for the your feature in 1.10

**Comment by rootfs** [comment]
per http://blog.kubernetes.io/2018/01/introducing-container-storage-interface.html, credentials are not supported in alpha. Closing.
