### ISSUE TITLE
Bringing server-side printing to beta summary

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#58536]
This is a tracker for the work items to bring server-side printing to beta in 1.10:

Server:

* [x] move the Table API to beta
* [ ] ~~put table API behind feature gate~~
* [ ] determine whether to have a shorthand mime-type for table (application/json+meta+v1+Table) or similar
* [x] Add better E2E tests that verify that all APIs implement the server side printer (https://github.com/kubernetes/kubernetes/pull/60580)
* [x] Add a unit test that verifies everyone implements printer (https://github.com/kubernetes/kubernetes/pull/60580)
* [x] Move the OpenAPI column rendering for CRD to the server in the CRD implementation #60269
* [ ] Do a final pass on the default metadata renderer (the generic one)
* [ ] Add a "example fuzzer" that returns a Table filled with all the values we could anticipate so that it's easy to test client impls
* [ ] Review the Table API with a JS web console user
* [ ] Stretch goal: look at a CSV mime type that uses table printing
* [x] Provide a table implementation for services #59510 

Client:

* [x] Have kubectl get fetch table resources and pass them into the printer (with fallback to client side printing if the server doesn't return a Table) (https://github.com/kubernetes/kubernetes/pull/55637)
* [x] Have a flag to disable server side rendering that defaults to false
* [x] Add client side tests that validate server side printing can be bypassed
* [ ] Sorting and printing should be using the table but with full objects returned via the print API `(?includeObject=Object)` and then doing the sort on nested, as should custom columns.
* [ ] We should also test service-catalog resources with Table printers. I have made a [note of this here](https://github.com/kubernetes/kubernetes/pull/55637#issue-152354172).

@juanvallejo

**Comment by smarterclayton** [comment]
Suggest we split this down the middle - I'll handle server side and Juan you can handle client side

**Comment by juanvallejo** [comment]
@smarterclayton 
> Suggest we split this down the middle - I'll handle server side and Juan you can handle client side

Sounds good to me. 
@soltysh fyi

**Comment by lavalamp** [comment]
cc @yliaog

**Comment by juanvallejo** [comment]
Existing prototype PR for item 1 under `Client`: https://github.com/kubernetes/kubernetes/pull/55637
Will rebase and add fallback, tests

**Comment by smarterclayton** [comment]
Overlapping #53224

**Comment by jberkus** [comment]
Hi!  This item is tagged as being for 1.10.  Given the checklist of tasks, which individual items are actually going into 1.10?

And, if you're tracking this for 1.10, can you please add kind/ and priority/ labels?  Thanks!

**Comment by adohe** [comment]
@smarterclayton could you please help update the status of this feature? I notice that this is release goal of SIG-CLI 1.10, also anything I could help with? I just got more time to focus on community stuff.

**Comment by juanvallejo** [comment]
@adohe I currently have client side changes proposed here:https://github.com/kubernetes/kubernetes/pull/55637 I still need to update to use v1beta1 instead of v1alpha1, but any feedback you have is appreciated

**Comment by pwittrock** [comment]
From @jberkus 

>Hey, the following issue is in SIG-CLI for the 1.10 milestone, but is missing Kind and Priority labels.  Can you please add those before Code Slush on Tuesday, or take the issue out of the milestone?  Thanks!

**Comment by jberkus** [comment]
Given that this is a tracker issue, can you break out the items which are actually going to get into 1.10, put those in their own issues with the milestone, and take this tracker out of the milestone?  Thanks!

**Comment by jberkus** [comment]
Hey, where are we with this feature overall?  Code Freeze starts today.  Are we still tracking this for 1.10, or does the rest of the work move to 1.11?

**Comment by juanvallejo** [comment]
@jberkus all client-side changes are merged, except for the last one.
sorting and custom columns will be addressed in 1.11.

Regarding the server-side, I believe @soltysh will address any remaining resources that need a TableConvertor for 1.11. @smarterclayton can you confirm if there is anything left to address on the server-side?

**Comment by smarterclayton** [comment]
We need to deliver a few tests to verify this doesn't regress during code
freeze but that's it.

**Comment by smarterclayton** [comment]
@soltysh can you link the 1.10 test PR in?

**Comment by soltysh** [comment]
This is https://github.com/kubernetes/kubernetes/pull/60580

**Comment by tpepper** [comment]
@smarterclayton with #60580 merged for the tests and #60712 opened for the carry overs to 1.11, is this 1.10 umbrella read to close now?

**Comment by soltysh** [comment]
@tpepper yes, sorry I've updated the initial description of the issue. All the remining bits are moved to #60712.
