### ISSUE TITLE
Delete notifications carry old ResourceVersion

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#58545]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Watch clients get DELETE-type events in which the contained object has the ResourceVersion of its last create/update, rather than the ResourceVersion that is current as of the delete.

This is a performance problem for reflectors, which keep track of the ResourceVersion using the received objects; if a watch should happen to end and get restarted after a delete, the reflector will restart from a (potentially very) old ResourceVersion.

Here is a demonstration.  In one shell start a watch on configmaps:
```
kubectl get configmaps -n foo -w -o json
```

In another shell make some configmaps, confirm the oldest has not changed, and then delete the first one:
```
kubectl create configmap -n foo a --from-literal=a=1
configmap "a" created
kubectl create configmap -n foo b --from-literal=b=1
configmap "b" created
kubectl create configmap -n foo c --from-literal=c=1
configmap "c" created
kubectl delete configmap a -n foo
configmap "a" deleted
```

Back in the first shell, observe that the delete reported the old ResourceVersion:
```
{"type":"ADDED","object":{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"a","namespace":"foo","selfLink":"/api/v1/namespaces/foo/configmaps/a","uid":"239166eb-fd64-11e7-8d7f-525400178201","resourceVersion":"2181459","creationTimestamp":"2018-01-19T22:00:19Z"},"data":{"a":"1"}}}
{"type":"ADDED","object":{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"b","namespace":"foo","selfLink":"/api/v1/namespaces/foo/configmaps/b","uid":"2769c179-fd64-11e7-8d7f-525400178201","resourceVersion":"2181471","creationTimestamp":"2018-01-19T22:00:25Z"},"data":{"b":"1"}}}
{"type":"ADDED","object":{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"c","namespace":"foo","selfLink":"/api/v1/namespaces/foo/configmaps/c","uid":"2bca456f-fd64-11e7-8d7f-525400178201","resourceVersion":"2181487","creationTimestamp":"2018-01-19T22:00:33Z"},"data":{"c":"1"}}}
{"type":"DELETED","object":{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"a","namespace":"foo","selfLink":"/api/v1/namespaces/foo/configmaps/a","uid":"239166eb-fd64-11e7-8d7f-525400178201","resourceVersion":"2181459","creationTimestamp":"2018-01-19T22:00:19Z"},"data":{"a":"1"}}}
```

**What you expected to happen**:
I am told that the DELETED event should carry a more recent ResourceVersion.

**How to reproduce it (as minimally and precisely as possible)**:
See the demonstration above.

**Anything else we need to know?**:
My kube apiserver is configured with `--storage-backend=etcd3`
My etcd server is a Docker container running the `quay.io/coreos/etcd:v3.2.4` image.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: local hardware
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux n17s2ctrl 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: local
- Others:

**Comment by smarterclayton** [comment]
This is a correctness issue - it should report the resource version of the deletion.

**Comment by liggitt** [comment]
looks like the watch cache filtering is returning the previous object content intact, including resource version
