### ISSUE TITLE
SSL connection failures to etcd should be logged by the apiserver.

### ISSUE THREAD

**Issue by bjhaid** [kubernetes/kubernetes#58552]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We upgraded to 1.9.1 and observed apiserver crashing at boot with no useful error messages. Upon taking a packet capture we found that the certificate being presented by etcd was "bad certificate", the v1.8.5 of the apiserver did not have a problem with this cert so this was very confusing, upon further investigation we found it was because the certs did not have a `DNS` field, and @liggitt confirmed this is because golang 1.9 has much stricter SSL certificate validation. This wouldn't have been so confusing for us if the kube apiserver logs had indicated that there was a problem with the certs etcd was presenting.

**What you expected to happen**:

Kube-apiserver should log SSL certifcate failures when communicating with etcd.

**How to reproduce it (as minimally and precisely as possible)**:

Generate an SSL cert for etcd without the DNS field and run k8s apiserver >= 1.9.1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on prem xen VMs
- OS (e.g. from /etc/os-release): debian jessie
- Kernel (e.g. `uname -a`): 
```
uname -a
Linux kube-controller01.sand.braintreepayments.com 4.4.0-1-amd64 #1 SMP Debian 4.4.43-1 (2017-01-30) x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by lavalamp** [comment]
cc @wenjiaswe

**Comment by wenjiaswe** [comment]
@bjhaid I am trying do reproduce this problem. Could you please attach the exact  "bad certificate" log message that you mentioned?

**Comment by bjhaid** [comment]
@wenjiaswe 
![image](https://user-images.githubusercontent.com/593852/35249582-2fcd581a-ff98-11e7-9d62-de1312432cbc.png)

from wireshark

**Comment by bjhaid** [comment]
```
             X509v3 Issuer Alternative Name: 
                 email:sys@foo.com
             X509v3 Subject Alternative Name: 
-                email:certmaster@foo.com
+                DNS:master01.foo.com, email:certmaster@foo.com
     Signature Algorithm: sha1WithRSAEncryption

```

is a diff indicating the difference between the "bad certificate" and the good one, you'll need to generate a cert has a SAN with the diff being deleted for etcd to correctly repro this, sorry if the information on the issue wasn't adequate to repro

**Comment by wenjiaswe** [comment]
@bjhaid, I tried to use a crt file with no DNS field for the etcd in kubernetes master, and restarted kube-apiserver, I actually didn't see any log entry regarding "bad certificate" issue in kube-apiserver.log, kubernetes run fine. I am not sure if it's because of my setting didn't simulate your scenario or if I looked at the wrong place for the error message. I actually couldn't recognize the image you attached earlier, could you please attach the log entry from kube-apiserver.log that shows the error?

**Comment by bjhaid** [comment]
@wenjiaswe 

> I tried to use a crt file with no DNS field for the etcd in kubernetes master, and restarted kube-apiserver

I created a repo to generate the broken cert for you:

https://github.com/bjhaid/bad_cert_repro

you should be able to use the `foo.bar.com` keys as it is, just modify your `/etc/hosts` to point your etcd node's ip address at `foo.bar.com` and you should be good, you can also modify `gen_bad_cert` to generate the cert matching the hostname you care about

>  I actually didn't see any log entry regarding "bad certificate" issue in kube-apiserver.log, kubernetes run fine

apiserver does not log anything about the problem, that's the reason why I opened the issue, the bad certificate was from a [pcap](https://en.wikipedia.org/wiki/Pcap) file generated from a [tcpdump](https://www.tcpdump.org/tcpdump_man.html) and analyzed with [wireshark](https://www.wireshark.org/).

>  I actually couldn't recognize the image you attached earlier

This image is from [wireshark](https://www.wireshark.org/)

> could you please attach the log entry from kube-apiserver.log that shows the error?

This is the point of this issue, apiserver does not log anything useful, it just crashes it's logs were useless in discerning the problem.

If you need further clarification, I am on k8s slack you can reach me there, my username is same as here (bjhaid)

**Comment by wenjiaswe** [comment]
@bjhaid 

Sorry I was working on something else and just got a chance to revisit this issue this week. I have my kubernetes on gce, set up the cert not exactly but very similar to your repo, with just some justification based on my setting (the two openssl command has different DNS like what you had):

> rm -f /etc/srv/kubernetes/pki/ca/index* /etc/srv/kubernetes/pki/ca/serial* /etc/srv/kubernetes/pki/ca/wjetcd.*
> touch /etc/srv/kubernetes/pki/ca/index.txt
> echo '01' > /etc/srv/kubernetes/pki/ca/serial
> 
> openssl req -subj "/C=US/ST=California/L=Sunnyvale/O=Wenjia/OU=Edu/CN=kube-apiserver" -out /etc/srv/kubernetes/pki/ca/wjetcd.csr -new -newkey rsa:2048 -nodes -keyout /etc/srv/kubernetes/pki/ca/wjetcd.key -reqexts SAN -config <(cat /etc/srv/kubernetes/pki/ca/wjetcdcsr.conf <(printf "[SAN]\nsubjectAltName=@alt_names\n\n[alt_names]\\nIP.1 = 35.192.50.60\nIP.2 = 127.0.0.1\nDNS.1 = kubernetes\nDNS.2 = kubernetes.default\nDNS.3 = kubernetes.default.svc\nDNS.4 = kubernetes.default.svc.cluster.local\nDNS.5 = kubernetes-master\nDNS.6 = kube-apiserver\nDNS.7 = localhost"))
> 
> openssl ca -in /etc/srv/kubernetes/pki/ca/wjetcd.csr -out /etc/srv/kubernetes/pki/ca/wjetcd.crt -keyfile /etc/srv/kubernetes/pki/ca.key -cert /etc/srv/kubernetes/pki/ca.crt -config <(cat /etc/srv/kubernetes/pki/ca/wjetcdcsr.conf <(printf "[SAN]\nsubjectAltName=@alt_names\n\n[alt_names]\\nIP.1 = 35.192.50.60\nIP.2 = 127.0.0.1\nDNS.1 = kubernetes\nDNS.4 = kubernetes.default.svc.cluster.local\nDNS.5 = kubernetes-master\nDNS.6 = kube-apiserver\nDNS.7 = localhost"))

I added --etcd-cafile in kube-apiserver.manifest:
> --etcd-cafile=/etc/srv/kubernetes/pki/ca.crt

I added the following in etcd.manifext:
> -cert-file=/etc/srv/kubernetes/pki/ca/wjetcd.crt --key-file=/etc/srv/kubernetes/pki/ca/wjetcd.key 

I am using kubernetes release 1.9.3, go1.9.2, Still not able to reproduce the problem. Is here anything I should have set up differently? 

@liggitt , I read some [previous conversation between you and @bjhaid saying that you have also seen this problem](https://kubernetes.slack.com/archives/C0EG7JC6T/p1516394881000271), would you mind sharing some insight about how you reproduced it or what I did it wrong that still not able to reproduce it? Also, I tried it manually and also tried some unit test. Do you know if[ tls_test.go](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/storagebackend/factory/tls_test.go) be good test for this scenario?
