### ISSUE TITLE
NFS test failures

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#58578]
We're observing some NFS test failures on kops-aws tests.  kops on AWS does not use the containerized mounter.

For example:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56132/pull-kubernetes-e2e-kops-aws/69965/

```
I0121 02:54:06.028] Jan 21 02:53:54.179: INFO: At 2018-01-21 02:48:44 +0000 UTC - event for pvc-tester-w4q98: {kubelet ip-172-20-41-247.us-west-2.compute.internal} FailedMount: MountVolume.SetUp failed for volume "nfs-qjgnk" : mount failed: exit status 32
I0121 02:54:06.028] Mounting command: systemd-run
I0121 02:54:06.029] Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/92f5e91d-fe55-11e7-a178-0690eca8f2ac/volumes/kubernetes.io~nfs/nfs-qjgnk --scope -- mount -t nfs 100.96.3.43:/exports /var/lib/kubelet/pods/92f5e91d-fe55-11e7-a178-0690eca8f2ac/volumes/kubernetes.io~nfs/nfs-qjgnk
I0121 02:54:06.029] Output: Running as unit run-30771.scope.
I0121 02:54:06.029] mount.nfs: rpc.statd is not running but is required for remote locking.
I0121 02:54:06.029] mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
I0121 02:54:06.030] mount.nfs: an incorrect mount option was specified
I0121 02:54:06.030] 
```

Is it a requirement to run rpc.statd, or should kubelet start it?  I can't see any recent code changes.  It feels like this is also flaking (rather than reliably failing), which is also confusing.

We did recently have to update the image & kernel for Meltdown / Spectre for kops-on-AWS.

**Comment by justinsb** [comment]
And it does look to be non-deterministic, as https://k8s-testgrid.appspot.com/google-aws#kops-aws shows: 22752 & '53 failed all the NFS tests, '54 failed 3/7, '55 failed 5/7, '56 and '57 failed 3/7 (but not the exact same 3), and '58 passed all 3.

(I'm assuming not a whole lot changed over that time interval)

**Comment by liggitt** [comment]
this appears to have failed 24 out of the last 35 kops runs.

the resulting PVC test errors started appearing early afternoon on 1/20: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=pvc-tester&job=pull-kubernetes-e2e-kops-aws

do we know what changed in the image changes around that time (https://github.com/kubernetes/kops/commits/master)

**Comment by justinsb** [comment]
Change should primarily have been the kernel -> 4.4.111, we also do a package update so we could have picked up a newer version of the NFS package or other supporting package.

We did try going to stretch for 1.10, but we still have / had the nf_conntrack issue so I reverted that to unblock the queue.

Also starting to add more tests, with other images ( e.g. https://github.com/kubernetes/test-infra/pull/6364 ) both so that we can get a heads-up before promoting images to stable, but also I guess we should try other OSes (e.g. I could add a test on RHEL).

**Comment by justinsb** [comment]
Proposed https://github.com/kubernetes/test-infra/pull/6367 to add a test for ubuntu-16.04, which should be similar.  That way we'll get an indication if it's a meltdown/spectre regression or something specific to the image.

Not sure how we should proceed here - we want to get the queue unblocked, but we don't really want to ignore the issue if it turns out to be real.  I guess we could ignore the NFS tests on the queue-blocking jobs, and ensure that we have non-blocking jobs that will continue to fail until it's resolved.

**Comment by zouyee** [comment]
At present, the pull-kubernetes-e2e-kops-aws job is widespread failed

**Comment by justinsb** [comment]
Correction: the kernel in the stable channel is 4.4.110.  The kernel in the alpha channel is 4.4.111.  PR to add testing of the alpha channel is https://github.com/kubernetes/test-infra/pull/6364
