### ISSUE TITLE
How Kubernetes to decide the pod delete when scale down ?

### ISSUE THREAD

**Issue by kweisamx** [kubernetes/kubernetes#58579]
May I ask the kubernetes when **scale up** deployment repica set, use scheduler to dispatch the pod to node,

but when **scale down**, how kubernetes to decide which pod to delete,

Not statefulset pod, it's normal deploment

is any source code to do about this? I can't find for a long time,

Thanks

**Environment**:
- Kubernetes version (use `kubectl version`):
kubernetes v.1.9.0
- Cloud provider or hardware configuration:
bare metal
- OS (e.g. from /etc/os-release):
ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
kubeadm
- Others:

**Comment by liggitt** [comment]
Relevant code is here:

https://github.com/kubernetes/kubernetes/blob/c9c6901303cd83fc0941c2c9964771404bf9cf9f/pkg/controller/replicaset/replica_set.go#L527

**Comment by kweisamx** [comment]
@liggitt Thank you!
