### ISSUE TITLE
[FEATURE REQUEST] support readOnly and type for ExtraVolumes in kubeadm

### ISSUE THREAD

**Issue by Dieken** [kubernetes/kubernetes#58587]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

apiServerExtraVolumes, controllerManagerExtraVolumes and schedulerExtraVolumes don't support "type" for volume definition and "readOnly" for volumeMount definition,  kubeadm always uses "type: DirectoryOrCreate" and "readOnly: true".

I would like to bind mount a file "audit-policy.yaml" which requires "type: File",   and a directory /var/log/kubernetes which requires "readOnly: false",  currently with kubeadm's master config file, I can't achieve that.

**What you expected to happen**:

Please support customization of "readOnly" and "type" for those three `*ExtraVolumes` parameters.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

I use Vagrant.

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux node01 4.4.0-111-generic #134-Ubuntu SMP Mon Jan 15 14:53:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:

kubeadm-1.9.2

- Others:

@kubernetes/sig-cluster-lifecycle-feature-requests

/sig cluster-lifecycle-feature-requests

**Comment by errordeveloper** [comment]
Have you managed to work around this or are you planning to open to propose a change in a PR?

**Comment by Dieken** [comment]
I used Ansible to patch /etc/kubernetes/manifests/kube-apiserver.yaml after the cluster was setup, an ugly workaround :-(

**Comment by rosti** [comment]
I'll give this a try.

**Comment by timothysc** [comment]
For future reference please open issues in the kubeadm repository https://github.com/kubernetes/kubeadm/issues

**Comment by timothysc** [comment]
Closing b/c #60428 addresses.  

If you feel otherwise please open issues under the https://github.com/kubernetes/kubeadm repo.
