### ISSUE TITLE
[PodSecurityPolicy] system:node (kubelet) cannot apply "use" verb to "podsecuritypolicies.extensions"

### ISSUE THREAD

**Issue by arno01** [kubernetes/kubernetes#58589]
Hi,

the closest issue that I've found is https://github.com/kubernetes/kubernetes/issues/53467 though is not really related to what I found while checking the issue further.

/kind bug

**What happened**:

The core essential Pods are not getting scheduled (visible?), though, I can see their containers are Up & Running:

```
[root@k8s-master2 ~]# kubectl get pods --all-namespaces -o wide
No resources found.
```

```
[root@k8s-master2 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                        PORTS               NAMES
8fcab1995899        gcr.io/google_containers/kube-scheduler-amd64            "kube-scheduler --ad…"   11 minutes ago      Up 11 minutes                                     k8s_kube-scheduler_kube-scheduler-k8s-master2_kube-system_4aeaf04163b153cb7d507dcaee2a075e_6
c60df9d40850        gcr.io/google_containers/kube-controller-manager-amd64   "kube-controller-man…"   11 minutes ago      Up 11 minutes                                     k8s_kube-controller-manager_kube-controller-manager-k8s-master2_kube-system_78e21daf3021ff100214487b10547692_6
1e3b1121d954        gcr.io/google_containers/kube-apiserver-amd64            "kube-apiserver --ad…"   11 minutes ago      Up 11 minutes                                     k8s_kube-apiserver_kube-apiserver-k8s-master2_kube-system_c8a6c1a94604ac0a5856d2c6f3cb6b8a_0
a91d91b43af2        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 11 minutes ago      Up 11 minutes                                     k8s_POD_kube-apiserver-k8s-master2_kube-system_c8a6c1a94604ac0a5856d2c6f3cb6b8a_0
d0c4c5fabd6a        gcr.io/google_containers/etcd-amd64                      "etcd --data-dir=/va…"   2 hours ago         Up 2 hours                                        k8s_etcd_etcd-k8s-master2_kube-system_59ee4f346043b976f34c38fb287f7e43_0
ad837a4fa845        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 2 hours ago         Up 2 hours                                        k8s_POD_etcd-k8s-master2_kube-system_59ee4f346043b976f34c38fb287f7e43_0
66e476fcc0b9        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 2 hours ago         Up 2 hours                                        k8s_POD_kube-scheduler-k8s-master2_kube-system_4aeaf04163b153cb7d507dcaee2a075e_0
027a8bac3d11        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 2 hours ago         Up 2 hours                                        k8s_POD_kube-controller-manager-k8s-master2_kube-system_78e21daf3021ff100214487b10547692_0
```

These 3 messages appearing every minute in the kubelet's log:

```
# journalctl -u kubelet -f
...
Jan 21 18:30:32 k8s-master2 kubelet[12323]: E0121 18:30:32.956897   12323 kubelet.go:1607] Failed creating a mirror pod for "kube-apiserver-k8s-master2_kube-system(bb9ce4c3d9bcfc3b1710c0cce9169ed2)": pods "kube-apiserver-k8s-master2" is forbidden: unable to validate against any pod security policy: []
Jan 21 18:30:33 k8s-master2 kubelet[12323]: E0121 18:30:33.928609   12323 kubelet.go:1607] Failed creating a mirror pod for "kube-scheduler-k8s-master2_kube-system(4aeaf04163b153cb7d507dcaee2a075e)": pods "kube-scheduler-k8s-master2" is forbidden: unable to validate against any pod security policy: []
Jan 21 18:30:34 k8s-master2 kubelet[12323]: E0121 18:30:34.013815   12323 kubelet.go:1607] Failed creating a mirror pod for "kube-controller-manager-k8s-master2_kube-system(78e21daf3021ff100214487b10547692)": pods "kube-controller-manager-k8s-master2" is forbidden: unable to validate against any pod security policy: []
```

**What you expected to happen**:

- The core essential Pods should be scheduled and visible upon ``kubectl get pods --all-namespaces``;
- Kubelet should not be having a problem using the PSP (PodSecurityPolicies) as seen in the kubelet log above;
- I presume that ``system:node`` ClusterRole should have an access to ``use`` verb to ``podsecuritypolicies.extensions``;

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy a fresh Kubernetes v1.9.1 using kubeadm command;
- Make sure to enable ``PodSecurityPolicy`` admission control;
- Check the kubelet's logs and see the repeating ``Failed creating a mirror pod for ... kube-apiserver, kube-scheduler and kube-controller-manager ... is forbidden: unable to validate against any pod security policy: []`` messages;

**Anything else we need to know?**:

I've got a fresh Kubernetes v1.9.1 install via kubeadm with the enabled ``PodSecurityPolicy``:

- kube-apiserver ``... --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota,PodSecurityPolicy,DenyEscalatingExec ... --authorization-mode=Node,RBAC ...``

My only psp in this test:

```
echo "
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
" | kubectl apply -f -
```

## checking whether the use action is allowed against PSP

Might this issue be due to a Node cannot apply ``use`` verb to ``podsecuritypolicies.extensions`` ?

Kubelet's x509 (client-certificate-data from ``/etc/kubernetes/kubelet.conf``) has: ``Subject: O=system:nodes, CN=system:node:k8s-master2``

> It actually ``cannot create selfsubjectaccessreviews`` so one can't really use ``auth can-i`` here. But checking the ``system:node`` ClusterRole, I couldn't find anything related to the podsecuritypolicy extension in there.

```
# kubectl --as system:node:k8s-master2 --as-group system:nodes auth can-i use podsecuritypolicies.extensions
Error from server (Forbidden): selfsubjectaccessreviews.authorization.k8s.io is forbidden: User "system:node:k8s-master2" cannot create selfsubjectaccessreviews.authorization.k8s.io at the cluster scope
```

According to the [Core Component Roles](https://github.com/kubernetes/website/blob/83dc3c58b13b47c081b7b50e43e5107104ec7fa3/docs/admin/authorization/rbac.md#L547) page, the ``system:node`` default ClusterRole should be automatically bound to the ``system:nodes`` group if the ``Node`` authorization mode is enabled (in K8s 1.8+).

### one more issue?

And I have just noticed (at the moment of writing this post), when I am running `` kubectl get psp example -o yaml``, it gives ``allowPrivilegeEscalation: true`` despite that I was setting ``privileged: false``

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1
- Cloud provider or hardware configuration: QEMU/KVM
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): Linux k8s-master2 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liggitt** [comment]
> I presume that system:node ClusterRole should have an access to use verb to podsecuritypolicies.extensions;

That is not the case. Since there are no default PodSecurityPolicy objects defined out of the box, you need to grant kublets (typically via the `system:nodes` group) permission to use a policy you  define. An example from GCE setup can be seen at https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/node-binding.yaml (which grants permission to a GCE-specific pod security policy)

> According to the Core Component Roles page, the system:node default ClusterRole should be automatically bound to the system:nodes group if the Node authorization mode is enabled (in K8s 1.8+).

Not quite... the automatic binding to the system:node role is deprecated in favor of the `Node` authorizer, and is no longer automatically created in 1.8+

>  I have just noticed (at the moment of writing this post), when I am running kubectl get psp example -o yaml, it gives allowPrivilegeEscalation: true despite that I was setting privileged: false

`allowPrivilegeEscalation` and `privileged` are distinct settings in the PSP and must be set to false individually.

/close

**Comment by arno01** [comment]
@liggitt oh, the "Legacy node ID" was something that I was really missing when checking the preexisting Roles and what added to my confusion was the Kubelet's x509 ``O=system:nodes`` which made me thinking there surely was nothing like ``Legacy node ID`` so I went the wrong path.

Should we add some note about this to the PSP Doc https://kubernetes.io/docs/concepts/policy/pod-security-policy/ ?

**Comment by dimm0** [comment]
Is there an example on how to enable psp with allowing everything in kube-system and restricting everywhere else?

**Comment by arno01** [comment]
@dimm0 having the ``PodSecurityPolicy`` admission control enabled will automatically prevent anything from its creation until there is at least one PSP exists and is binded to a service account / user / node via RoleBinding or a ClusterRoleBinding.

So until you create the PSP and properly bind it, it means it will be restricted everywhere else it hasn't been binded to. And then you can create different PSP's, e.g. privileged / unprivileged / ns-tailored ...

Example configuration:
https://github.com/kubernetes/kubernetes/tree/a1513161b3056d4c5ef711ab1c5314e97e90811a/cluster/gce/addons/podsecuritypolicies

**Comment by dimm0** [comment]
Thanks @arno01!
