### ISSUE TITLE
kubectl get --export shows stripped fields for custom resources

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#58597]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

For custom resources, `kubectl get --export` strips the values but keeps the fields - sort of destroying the purpose of `--export`.

Example:

```yaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  clusterName: ""
  name: my-new-cron-object
  namespace: ""
  resourceVersion: ""
  selfLink: /apis/stable.example.com/v1/namespaces/default/crontabs/my-new-cron-object
  uid: ""
spec:
  cronSpec: '* * * * */5'
  image: my-awesome-cron-image
```

**What you expected to happen**:

The stripped fields should not be shown.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a CRD.

```yaml
$ cat crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct

$ kubectl create -f crd.yaml
customresourcedefinition "crontabs.stable.example.com" created
```

2. Create the custom resource.

```yaml
$ cat crontab.yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image

$ kubectl create -f crontab.yaml
crontab "my-new-cron-object" created
```

3. Do a `kubectl get --export=true`

```yaml
$ kubectl get crontabs my-new-cron-object --export=true -oyaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  clusterName: ""
  name: my-new-cron-object
  namespace: ""
  resourceVersion: ""
  selfLink: /apis/stable.example.com/v1/namespaces/default/crontabs/my-new-cron-object
  uid: ""
spec:
  cronSpec: '* * * * */5'
  image: my-awesome-cron-image
```

**Anything else we need to know?**:

This occurs due to inconsistent marshalling for `Unstructured` objects. See https://github.com/kubernetes/kubernetes/pull/58332 for a fix.

Related issue: https://github.com/kubernetes/kubernetes/issues/50454#issuecomment-358927276 

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig api-machinery
/area custom-resources
/cc @sttts @errordeveloper @liggitt

**Comment by liggitt** [comment]
Isn't this a duplicate of https://github.com/kubernetes/kubernetes/issues/48211?

**Comment by nikhita** [comment]
> Isn't this a duplicate of #48211?

This occurs as a result of #48211. So we can probably close this issue.
