### ISSUE TITLE
Ability to "seed" an image

### ISSUE THREAD

**Issue by jmreicha** [kubernetes/kubernetes#5859]
One thing that we have found in testing so far with large image sizes is that it can take quite awhile to download the image.  In some scenario's we have found this to cause a disruption in service as the old containers go away faster thqn the new images can be pulled down and started up.

Is there any way to "seed" an image or possibly create some definition in a replication controller that will tell it to pull the image down first before blowing out old pods on a rollingupdate?

**Comment by davidopp** [comment]
From experience with our internal cluster management system at Google, I agree that many people find image pre-loading to be useful. I think we should implement this, but I think it is probably P3 given the amount of other stuff we are working on right now. I think it would not be too hard to implement in Kubernetes.

**Comment by jmreicha** [comment]
I am willing to take a look, I'm just not where to start.

If someone could help point me in the right direction I could take a stab at this or at least it will help me get a better idea of how some of the internals work.

**Comment by bgrant0607** [comment]
This will be resolved by #11942.

**Comment by jmreicha** [comment]
@bgrant0607 Great, thanks!
