### ISSUE TITLE
OpenID Connect Tokens - Underdocumented

### ISSUE THREAD

**Issue by piwi91** [kubernetes/kubernetes#58605]
I'm using OpenID Connect Tokens to authenticate to the Kubernetes platform. I ran into unauthorized errors because the default OpenID Connect Tokens (id_token) didn't have all required fields.
In the docs (https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens) I couldn't find any details what the Kubernetes authenticator expected so I had to figure it out myself. I think this documentation can be expanded with the fields required in the id_token.

Required fields (as far as I could test):
* `email` (I use this as username)
* `email_verified`
* `groups`

The missing `email_verified` field was causing the error.

**Comment by rithujohn191** [comment]
Note: https://github.com/kubernetes/kubernetes/pull/61508 changed the behavior to make `email_verified` not a required field.
