### ISSUE TITLE
Generate OpenAPI spec for registered CRDs

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#58603]
Currently, we don't generate the OpenAPI spec for registered CRDs. We should at least show the existence of the registered groups in the spec.

We should probably implement this before going GA (?)

/cc @sttts @mbohlool @deads2k @liggitt 

/sig api-machinery
/kind bug
/area custom-resources

**Comment by aakp10** [comment]
I'd like to work on this issue if it's not being worked on by anyone else. 
Currently I'm getting myself familiarised with the API machinery codebase, so I might take a couple of days for the PR.

**Comment by marcellodesales** [comment]
I'd like to implement my own Condition columns... Base on the following: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties

> In condition types, and everywhere else they appear in the API, Reason is intended to be a one-word, CamelCase representation of the category of cause of the current status, and Message is intended to be a human-readable phrase or sentence, which may contain specific details of the individual occurrence. Reason is intended to be used in concise output, such as one-line kubectl get output, and in summarizing occurrences of causes, whereas Message is intended to be presented to users in detailed status explanations, such as kubectl describe output.

Is this the right issue for the following?

# FROM 

```$ kubectl get app repo-abc1234
NAME                  AGE
repo-abc1234   4m
```

# TO 

* Adding the column `PARSED`

```$ kubectl get app repo-abc1234                
NAME                  AGE      URL                                          PARSED
repo-abc1234   4m           https://github.com/org/repo-abc1234            454/5000
```

**Comment by sttts** [comment]
@marcellodesales we need a follow-up of https://github.com/kubernetes/kubernetes/pull/60269.

**Comment by nikhita** [comment]
PR open: https://github.com/kubernetes/kubernetes/pull/67205

Thanks @roycaihw!! :tada:

**Comment by mbohlool** [comment]
/open

the fix is rolled back and a new fix is in progress.

**Comment by roycaihw** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/71192

feature being tracked by https://github.com/kubernetes/enhancements/issues/692

/close
