### ISSUE TITLE
why "kubectl get nodes" get NONE ROLE and NONE EXTERNAL_IP for nodes  

### ISSUE THREAD

**Issue by tjliupeng** [kubernetes/kubernetes#58609]
I install k8s 1.9.1 using kubeadm on my local network.

**What happened**:
[appuser@ajaisys-scm-ai-k8s-2-98734a5a ~]$ kubectl get nodes
```
NAME                                      STATUS    ROLES     AGE       VERSION
ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal   Ready     master    14d       v1.9.1
ajaisys-scm-ai-k8s-2-98734a5a.novalocal   Ready     <none>    14d       v1.9.1
ajaisys-scm-ai-k8s-3-24327814.novalocal   Ready     <none>    2h        v1.9.1
```
-[appuser@ajaisys-scm-ai-k8s-2-98734a5a ~]$ kubectl get nodes -o wide
```
NAME                                      STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal   Ready     master    14d       v1.9.1    <none>        CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64   docker://1.12.6
ajaisys-scm-ai-k8s-2-98734a5a.novalocal   Ready     <none>    14d       v1.9.1    <none>        CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64   docker://1.12.6
ajaisys-scm-ai-k8s-3-24327814.novalocal   Ready     <none>    2h        v1.9.1    <none>        CentOS Linux 7 (Core)   3.10.0-693.5.2.el7.x86_64   docker://1.12.6
```

**What you expected to happen**:
The external IP should be the node IP.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
    kubectl version:
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

kubeadm verison:
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by errordeveloper** [comment]
I'd help if you could provide the output of `kubectl get node --output yaml` to start with. This maybe somehow dependent on the configuration of your local network, but we can take a look at that later.

**Comment by tjliupeng** [comment]
@errordeveloper , below is the output of `kubectl get node --output yaml`:
`
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"12:ec:07:26:03:a3"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.135.80.73
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2018-01-08T01:28:26Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
      node-role.kubernetes.io/master: ""
    name: ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
    namespace: ""
    resourceVersion: "1914428"
    selfLink: /api/v1/nodes/ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
    uid: 39b0573d-f413-11e7-8174-fa163e9b0ad0
  spec:
    externalID: ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
    podCIDR: 10.244.0.0/24
    taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  status:
    addresses:
    - address: 10.135.80.73
      type: InternalIP
    - address: ajaisys-scm-ai-k8s-1-7a9fd2c5.novalocal
      type: Hostname
    allocatable:
      cpu: "8"
      memory: 16164796Ki
      pods: "110"
    capacity:
      cpu: "8"
      memory: 16267196Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: 2018-01-26T02:28:55Z
      lastTransitionTime: 2018-01-08T01:28:22Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
    - lastHeartbeatTime: 2018-01-26T02:28:55Z
      lastTransitionTime: 2018-01-08T01:28:22Z
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: 2018-01-26T02:28:55Z
      lastTransitionTime: 2018-01-08T01:28:22Z
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: 2018-01-26T02:28:55Z
      lastTransitionTime: 2018-01-22T11:56:22Z
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - deploymenttest:1.0
      sizeBytes: 226168168
    - names:
      - gcr.io/google_containers/kube-apiserver-amd64:v1.9.0
      - k8s.gcr.io/kube-apiserver-amd64:v1.9.0
      sizeBytes: 210373620
    - names:
      - gcr.io/google_containers/etcd-amd64:3.1.10
      - k8s.gcr.io/etcd-amd64:3.1.10
      sizeBytes: 192743523
    - names:
      - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
      sizeBytes: 189866039
    - names:
      - gcr.io/google_containers/kube-controller-manager-amd64:v1.9.0
      - k8s.gcr.io/kube-controller-manager-amd64:v1.9.0
      sizeBytes: 137750466
    - names:
      - gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.1
      sizeBytes: 120712806
    - names:
      - gcr.io/google_containers/kube-proxy-amd64:v1.9.0
      - k8s.gcr.io/kube-proxy-amd64:v1.9.0
      sizeBytes: 109093516
    - names:
      - gcr.io/google_containers/kube-scheduler-amd64:v1.9.0
      - k8s.gcr.io/kube-scheduler-amd64:v1.9.0
      sizeBytes: 62696260
    - names:
      - quay.io/coreos/flannel:v0.9.1-amd64
      sizeBytes: 51314612
    - names:
      - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
      - k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.7
      sizeBytes: 50270536
    - names:
      - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
      - k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.7
      sizeBytes: 42028742
    - names:
      - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
      - k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.7
      sizeBytes: 40947480
    - names:
      - gcr.io/google_containers/defaultbackend:1.4
      sizeBytes: 4844064
    - names:
      - gcr.io/google_containers/pause-amd64:3.0
      - k8s.gcr.io/pause-amd64:3.0
      sizeBytes: 746888
    nodeInfo:
      architecture: amd64
      bootID: 6f8f2d65-f4f8-4b5d-bf18-e3c112c24ef6
      containerRuntimeVersion: docker://1.12.6
      kernelVersion: 3.10.0-693.5.2.el7.x86_64
      kubeProxyVersion: v1.9.1
      kubeletVersion: v1.9.1
      machineID: f073c429a7456b53ec3e2c53460c5c8f
      operatingSystem: linux
      osImage: CentOS Linux 7 (Core)
      systemUUID: 5E134D8C-377E-4484-8FFD-7C829C402639
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"a2:f9:37:41:a4:c0"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.135.80.74
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2018-01-08T06:20:55Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: ajaisys-scm-ai-k8s-2-98734a5a.novalocal
    name: ajaisys-scm-ai-k8s-2-98734a5a.novalocal
    namespace: ""
    resourceVersion: "1914432"
    selfLink: /api/v1/nodes/ajaisys-scm-ai-k8s-2-98734a5a.novalocal
    uid: 15c622c1-f43c-11e7-8174-fa163e9b0ad0
  spec:
    externalID: ajaisys-scm-ai-k8s-2-98734a5a.novalocal
    podCIDR: 10.244.1.0/24
  status:
    addresses:
    - address: 10.135.80.74
      type: InternalIP
    - address: ajaisys-scm-ai-k8s-2-98734a5a.novalocal
      type: Hostname
    allocatable:
      cpu: "8"
      memory: 16164796Ki
      pods: "110"
    capacity:
      cpu: "8"
      memory: 16267196Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: 2018-01-26T02:28:54Z
      lastTransitionTime: 2018-01-08T06:21:08Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
    - lastHeartbeatTime: 2018-01-26T02:28:54Z
      lastTransitionTime: 2018-01-17T15:16:23Z
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: 2018-01-26T02:28:54Z
      lastTransitionTime: 2018-01-17T15:16:23Z
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: 2018-01-26T02:28:54Z
      lastTransitionTime: 2018-01-22T11:56:05Z
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - deploymenttest:1.0
      sizeBytes: 226168168
    - names:
      - gcr.io/google_containers/kube-apiserver-amd64:v1.9.0
      sizeBytes: 210373620
    - names:
      - gcr.io/google_containers/etcd-amd64:3.1.10
      sizeBytes: 192743523
    - names:
      - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
      sizeBytes: 189866039
    - names:
      - gcr.io/google_containers/kube-controller-manager-amd64:v1.9.0
      sizeBytes: 137750466
    - names:
      - gcr.io/google_containers/kube-proxy-amd64:v1.9.0
      sizeBytes: 109093516
    - names:
      - gcr.io/google_containers/kube-scheduler-amd64:v1.9.0
      sizeBytes: 62696260
    - names:
      - quay.io/coreos/flannel:v0.9.1-amd64
      sizeBytes: 51314612
    - names:
      - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
      sizeBytes: 50270536
    - names:
      - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
      sizeBytes: 42028742
    - names:
      - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
      sizeBytes: 40947480
    - names:
      - gcr.io/google_containers/defaultbackend:1.4
      sizeBytes: 4844064
    - names:
      - gcr.io/google_containers/pause-amd64:3.0
      sizeBytes: 746888
    nodeInfo:
      architecture: amd64
      bootID: d164490a-5590-40af-bae3-9d3888631e8a
      containerRuntimeVersion: docker://1.12.6
      kernelVersion: 3.10.0-693.5.2.el7.x86_64
      kubeProxyVersion: v1.9.1
      kubeletVersion: v1.9.1
      machineID: f073c429a7456b53ec3e2c53460c5c8f
      operatingSystem: linux
      osImage: CentOS Linux 7 (Core)
      systemUUID: E5A113A1-A48D-4466-A6E1-77EE1405DD2B
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"76:da:28:fa:3b:8b"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.135.80.75
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: 2018-01-22T07:23:32Z
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/hostname: ajaisys-scm-ai-k8s-3-24327814.novalocal
    name: ajaisys-scm-ai-k8s-3-24327814.novalocal
    namespace: ""
    resourceVersion: "1914433"
    selfLink: /api/v1/nodes/ajaisys-scm-ai-k8s-3-24327814.novalocal
    uid: 26c36639-ff45-11e7-8174-fa163e9b0ad0
  spec:
    externalID: ajaisys-scm-ai-k8s-3-24327814.novalocal
    podCIDR: 10.244.2.0/24
  status:
    addresses:
    - address: 10.135.80.75
      type: InternalIP
    - address: ajaisys-scm-ai-k8s-3-24327814.novalocal
      type: Hostname
    allocatable:
      cpu: "8"
      memory: 16164796Ki
      pods: "110"
    capacity:
      cpu: "8"
      memory: 16267196Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: 2018-01-26T02:28:31Z
      lastTransitionTime: 2018-01-22T07:23:11Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
    - lastHeartbeatTime: 2018-01-26T02:28:31Z
      lastTransitionTime: 2018-01-22T07:23:11Z
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: 2018-01-26T02:28:31Z
      lastTransitionTime: 2018-01-22T07:23:11Z
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: 2018-01-26T02:28:31Z
      lastTransitionTime: 2018-01-22T07:23:31Z
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - deploymenttest:1.0
      sizeBytes: 226168168
    - names:
      - gcr.io/google_containers/kube-apiserver-amd64:v1.9.0
      sizeBytes: 210373620
    - names:
      - gcr.io/google_containers/etcd-amd64:3.1.10
      sizeBytes: 192743523
    - names:
      - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
      sizeBytes: 189866039
    - names:
      - gcr.io/google_containers/kube-controller-manager-amd64:v1.9.0
      sizeBytes: 137750466
    - names:
      - gcr.io/google_containers/kube-proxy-amd64:v1.9.0
      sizeBytes: 109093516
    - names:
      - gcr.io/google_containers/kube-scheduler-amd64:v1.9.0
      sizeBytes: 62696260
    - names:
      - quay.io/coreos/flannel:v0.9.1-amd64
      sizeBytes: 51314612
    - names:
      - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
      sizeBytes: 50270536
    - names:
      - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
      sizeBytes: 42028742
    - names:
      - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
      sizeBytes: 40947480
    - names:
      - gcr.io/google_containers/defaultbackend:1.4
      sizeBytes: 4844064
    - names:
      - gcr.io/google_containers/pause-amd64:3.0
      sizeBytes: 746888
    nodeInfo:
      architecture: amd64
      bootID: 82b13ac8-3541-4654-9f6f-6adebece8d11
      containerRuntimeVersion: docker://1.12.6
      kernelVersion: 3.10.0-693.5.2.el7.x86_64
      kubeProxyVersion: v1.9.1
      kubeletVersion: v1.9.1
      machineID: f073c429a7456b53ec3e2c53460c5c8f
      operatingSystem: linux
      osImage: CentOS Linux 7 (Core)
      systemUUID: DC1E144D-1662-4B89-9337-725808AC881C
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
`

**Comment by errordeveloper** [comment]
It looks you actually have one IP address on each node, and it appears to be in a private range. If you have some kind NAT setup. If your cluster is functional, I wouldn't worry about it, otherwise try passing `--node-ip` to kubelet on each node with the address you'd like to assign to that node.
