### ISSUE TITLE
Running cloud-controller-manager should remove uninitialized taint

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#58613]
Once cloud-controller-manager is started we should remove the taint. right?

```
                "taints": [
                    {
                        "effect": "NoSchedule",
                        "key": "node.cloudprovider.kubernetes.io/uninitialized",
                        "value": "true"
                    }
```

**Comment by jhorwit2** [comment]
/area cloudprovider

@dims do you have anymore information on this? I can't reproduce this on existing nodes before the CCM was created or new nodes added to a cluster.

**Comment by dims** [comment]
@jhorwit2 i can recreate this using `hack/local-up-cluster.sh` by setting `EXTERNAL_CLOUD_PROVIDER=true` along with a CLOUD_CONFIG + CLOUD_PROVIDER env vars

**Comment by jhorwit2** [comment]
@dims If you're running a local cluster then how are you running the CCM? The only way the taint gets removed is if the instance was found in the cloud provider and setup (labels, addresses, etc) OK. The code can be found [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L314-L365)

**Comment by dims** [comment]
@jhorwit2 the local cluster is started within a openstack vm. so it's a one vm cluster. thanks for the pointer, will check it out

**Comment by dims** [comment]
@jhorwit2 - So ... when i use local-up-cluster, the kubelet starts up before the cloud-controller-manager. So the shared informer that calls `cnc.AddCloudNode` is never triggered.

diff --git a/pkg/controller/cloud/node_controller.go b/pkg/controller/cloud/node_controller.go
index 9f1c86e..51747dc 100644
--- a/pkg/controller/cloud/node_controller.go
+++ b/pkg/controller/cloud/node_controller.go
@@ -98,6 +98,19 @@ func NewCloudNodeController(
                nodeStatusUpdateFrequency: nodeStatusUpdateFrequency,
        }

```
+       stopChan := make(chan struct{})
+       go wait.Until(func() {
+               nodes, err := cnc.kubeClient.CoreV1().Nodes().List(metav1.ListOptions{ResourceVersion: "0"})
+               if err != nil {
+                       glog.Errorf("Error monitoring node status: %v", err)
+                       return
+               }
+               for i := range nodes.Items {
+                       cnc.AddCloudNode(&nodes.Items[i])
+               }
+               close(stopChan)
+       }, time.Second * 5, stopChan)
+
        nodeInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
                AddFunc: cnc.AddCloudNode,
        })
```
