### ISSUE TITLE
verify-openapi-spec.sh panics when "openapi-gen path outside of k8s.io/kubernetes"

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#58616]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig api-machinery

**What happened**:
When I run `hack/update-bazel.sh` it fails with error:
```console
$ hack/update-bazel.sh 
F0122 16:33:56.334332    5489 kazel.go:76] err walking generated: openapi-gen path outside of k8s.io/kubernetes: home/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apis/abac/v0
goroutine 1 [running]:
github.com/kubernetes/repo-infra/vendor/github.com/golang/glog.stacks(0xc420075700, 0xc420242000, 0xb9, 0x10d)
	/tmp/tmp.c69ewebVp3/go/src/github.com/kubernetes/repo-infra/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/kubernetes/repo-infra/vendor/github.com/golang/glog.(*loggingT).output(0x6e88e0, 0xc400000003, 0xc420240000, 0x6ca542, 0x8, 0x4c, 0x0)
	/tmp/tmp.c69ewebVp3/go/src/github.com/kubernetes/repo-infra/vendor/github.com/golang/glog/glog.go:717 +0x322
github.com/kubernetes/repo-infra/vendor/github.com/golang/glog.(*loggingT).printf(0x6e88e0, 0xc400000003, 0x5ebb23, 0x19, 0xc42019bee0, 0x1, 0x1)
	/tmp/tmp.c69ewebVp3/go/src/github.com/kubernetes/repo-infra/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/kubernetes/repo-infra/vendor/github.com/golang/glog.Fatalf(0x5ebb23, 0x19, 0xc42019bee0, 0x1, 0x1)
	/tmp/tmp.c69ewebVp3/go/src/github.com/kubernetes/repo-infra/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/tmp/tmp.c69ewebVp3/go/src/github.com/kubernetes/repo-infra/kazel/kazel.go:76 +0x2d4
!!! Error in hack/update-bazel.sh:51
  Error in hack/update-bazel.sh:51. 'kazel' exited with status 255
Call stack:
  1: hack/update-bazel.sh:51 main(...)
Exiting with status 1
```

**What you expected to happen**:
1) it shouldn't panic
2) it should show human readable error with suggestions how developer may fix it

**Environment**:
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0-beta1", GitCommit:"3258431", GitTreeState:"clean", BuildDate:"2018-01-08T18:34:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```console
$ pwd
/home/coder/git/src/home/kubernetes
$ echo $GOPATH 
/home/coder/git
```

**Comment by lavalamp** [comment]
@mbohlool @roycaihw

**Comment by mbohlool** [comment]
Is this on head? or do you have some code change then running update-bazel?

**Comment by php-coder** [comment]
@mbohlool it was on 3258431 commit but I believe nothing changed since then.

**Comment by mbohlool** [comment]
that commit is not merged? or forced push upon? I can't check it out in my local git. What I am trying to do is to reproduce this. Is there any branch/repo I can reproduce this on?

**Comment by php-coder** [comment]
> that commit is not merged? or forced push upon?

Yes, it's possible.

>  Is there any branch/repo I can reproduce this on?

The key here isn't in code but in the environment:

```console
$ pwd
/home/coder/git/src/home/kubernetes
$ echo $GOPATH 
/home/coder/git
```

Try to create a directory with k8s sources outside of the `$GOPTH` (symbolic link should be enough).

**Comment by mbohlool** [comment]
I think all generators assume a path structure for kubernetes that should be $GOPATH/src/k8s.io/kubernetes. Do we need to support code outside of this path?

**Comment by mbohlool** [comment]
OK. I get it now, so you are saying we should improve error reporting here :)
