### ISSUE TITLE
CSI Code Cleanup - Assemble shared utility functions in a central location

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#58628]
This is a maintenance TODO for CSI code organization.

**Comment by Lion-Wei** [comment]
I can help to do this. : )

**Comment by vladimirvivien** [comment]
@Lion-Wei Ok.  There are several common functions that could be relocated in a file `pkg/volume/csi/csi_util.go`.  Some functions are common and not meant to be re-used and so should not move. Let me know if that makes sense.

**Comment by Lion-Wei** [comment]
@vladimirvivien Thanks, sorry for delayed response.
I sended a pr to do this work, in that pr, I moved those functions to `csi_util.go` and added a ut file.
```go
func log(msg string, parts ...interface{}) string{}
func getCSISourceFromSpec(spec *volume.Spec) (*v1.CSIPersistentVolumeSource, error){}
func getCSIClient(volume, driverName string) *csiDriverClient{}
func getTargetPath(uid types.UID, specVolumeID string, host volume.VolumeHost) string{}
func getAttachmentName(volName, csiDriverName, nodeName string) string{}
func saveVolumeData(p *csiPlugin, podUID types.UID, specVolID string, data map[string]string) error{}
func loadVolumeData(dir string, fileName string) (map[string]string, error){}
```
Please let me know if have any error of misunderstanding. : )

**Comment by vladimirvivien** [comment]
@Lion-Wei no problem.  I added some comments on the PR.
