### ISSUE TITLE
K8s distributed masters configuration 

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes#58620]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Hello dear forum . I have distributed cluster configuratuon with 3 master nodes. I have  1.68 version. During ha test that we run the master leader machine was " killed". Election process of new master started immediately and new master with leader asigment appeared in few seconds. But despite the new leader cluster became unstable. It take minutes to get cluster status.only after 5 minutes cluster back responding and fully function. Such behavior is not looks me normal. What do you think? 
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by g1001p** [comment]
/sig bug
BUG REPORT
/sig bugs

**Comment by fejta** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by k82cn** [comment]
> the master leader machine 

api server?

**Comment by g1001p** [comment]
The leader is k8s controller. There are 3 api servera and all of them communicated with controller leader through load balancer.

**Comment by bsalamat** [comment]
It is not clear if this is related to the scheduler. The description given in the original post sounds like an API server issue to me.
