### ISSUE TITLE
CSI Access Mode - Ensure k8s access mode maps to CSI access mode properly

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#58632]
/kind bug

This is to ensure access Kubernetes volume access mode is properly (or better) mapped with the meaning of CSI access modes.

/sig storage

**Comment by linyouchong** [comment]
I want to help fixing it, but I don't know  what should the CSI access mode `SINGLE_NODE_READER_ONLY` mapped with?
ReadWriteOnce  -->  VolumeCapability_AccessMode_SINGLE_NODE_WRITER
       ?                   -->  VolumeCapability_AccessMode_SINGLE_NODE_READER_ONLY
ReadOnlyMany   -->  VolumeCapability_AccessMode_MULTI_NODE_READER_ONLY
ReadWriteOnce + ReadOnlyMany -->  VolumeCapability_AccessMode_MULTI_NODE_SINGLE_WRITER
ReadWriteMany  -->	VolumeCapability_AccessMode_MULTI_NODE_MULTI_WRITER

**Comment by vladimirvivien** [comment]
@linyouchong access modes is a feature that still being debated... There's no clear mapping right now between k8s access mode and its meaning in CSI.  

cc @saad-ali
