### ISSUE TITLE
Propose to add "stopped

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#58630]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by php-coder** [comment]
@jingxu97 Please, update the subject and description to add details.

**Comment by jingxu97** [comment]
@php-coder Sorry this is a mistake. Close this issue.
