### ISSUE TITLE
CSI - Move driver assertion calls inside client

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#58633]
Currently, method call `AssertSupportedVersion()` must be made explicitly.  Move that call inside the csi_client.go and do it automatically.

**Comment by linyouchong** [comment]
@vladimirvivien can you assign it to me ?

**Comment by Lion-Wei** [comment]
@linyouchong I saw you haven't do this yet, so I help solved this. Hope you don't mind. : )

**Comment by vladimirvivien** [comment]
@linyouchong I coudn't assign this 20 days ago... But I will assign to @Lion-Wei

**Comment by vladimirvivien** [comment]
@linyouchong you are welcome to review..  thanks!

**Comment by Lion-Wei** [comment]
@vladimirvivien  Thanks.

**Comment by linyouchong** [comment]
@vladimirvivien @Lion-Wei 
 That’s all right.

**Comment by vladimirvivien** [comment]
This issue should be closed. No longer needed.
