### ISSUE TITLE
Request to add namespace name and namespace UUID to metadata of on-disk log file

### ISSUE THREAD

**Issue by portante** [kubernetes/kubernetes#58638]
/kind feature

We assert that a log file on-disk (via CRI-O, or docker's json-file logging driver) should have metadata associated with that log file to describe the UUIDs _and_ names of the container, pod, **and** namespace associated with the log output to avoid k8s API calls later.  Today it does not _appear_ to include the namespace UUID or name (see https://github.com/kubernetes/kubernetes/blob/6caf34389b865be8b41811dc7c130c1006995d8a/pkg/kubelet/kuberuntime/helpers.go#L220).

Ideally (and arguably), a log collection system *should not be required* to query the Kube APIs about the log data in order to find the UUIDs of the k8s resource hierarchy associated with a container.  Only _optional_ metadata that decorates or enriches the log data would necessitate API calls to fetch that metadata; e.g., if one wanted to decorate logs with one or more labels or annotations from a pod or namespace.  A log collection system should be able to properly disambiguate and group logs accurately without additional API calls which might cause undo burden on the API server.  Since any metadata needed to be fetched via API calls is optional, it can be dropped when inconvenient or added later as a post-processing step.

The "location" of a container in a single k8s cluster is fully described by four pieces of information:

 * hostname
 * container UUID (and name)
 * pod UUID (and name)
 * namespace UUID (and name)

With the above information, understanding the origin of one or more log entries in an aggregation of logs can be accomplished unambiguously with respect to k8s in one cluster.  Today, it appears that k8s provides 3 of the 4 pieces of data, hostname (implicitly), container, and pod, when constructing the symlink for the log file path.

Can we consider adding namespace UUID and namespace name as well?

**Comment by dchen1107** [comment]
cc/ @yujuhong

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-instrumentation-misc

**Comment by yujuhong** [comment]
Discussed in the sig-node meeting. There are legacy symlinks for docker and (new) CRI log paths. I don't think we need to change the former. As for the latte, since there will be many CRI logging improvements planned for 1.10, it'd be the good time to start the discussion and make any necessary changes. 

@portante @derekwaynecarr do you have something in mind already about how the metadata should be incorporated?

Related issue for changing the fluentd to consume the CRI log paths: #36401

**Comment by yujuhong** [comment]
As for maintaining backward compatibility, for docker(shim), it'd need to recreate (delete and create new) the symlinks. As for other CRI runtimes, either draining the containers or creating symlinks from new to the old may be adopted.

**Comment by portante** [comment]
Encoding the information in the path of the log file seems reasonable still, but elongates the path, something like:

```
/var/log/containers/<namespace_name>.<namespace_UUID>/<pod_name>.<pod_UUID>/<container_name>.<container_UUID>.log
```

Which might allow for existing paths to be seen and recognized as the old form, with the new form detected by the hierarchy of directories.

Thoughts?

**Comment by yujuhong** [comment]
@portante the current CRI log path is `/var/log/pods/PODUID/CONTAINERNAME_INSTANCENUMBERlog`

Kubernetes API does not include a container UUID, so I assume you meant the ID created by the container runtime.
Currently, kubelet constructs the log path and passes it to the runtime *before* creating a container. The runtime will create a container and return an ID. As a result of this, it's not possible to include the container ID in the log path itself. Would the "instance number" (e.g., 1, 2, 3, ...) be sufficent?

**Comment by portante** [comment]
> @portante the current CRI log path is `/var/log/pods/PODUID/CONTAINERNAME_INSTANCENUMBER.log`

I think using container name and instance number is fine.  Are we still able to add namespace name, namespace UUID, and pod name, as well?  And can we consider providing the final container ID in an associated JSON file that collectors can read and depend on?  Perhaps just put all the metadata there: namespace name, namespace UUID, pod UUID, pod name, container name, instance number, and ID?

**Comment by portante** [comment]
Hi @yujuhong, newbie here with k8s: what does it mean to be "assigned" to an issue?  Thanks!

**Comment by yujuhong** [comment]
> Hi @yujuhong, newbie here with k8s: what does it mean to be "assigned" to an issue? Thanks!

I assigned the issue to the three of you just to keep track and ensure you will all be included in the upcoming discussions :-)

**Comment by jberkus** [comment]
@yujuhong if this feature is going to be in 1.10, please add a priority/ label for it.

Also, what's the tracking feature issue for this one?  I can't find a linked feature issue.

**Comment by jberkus** [comment]
@yujuhong does this issue/feature depend on getting that PR committed to rsyslog?  If so, do you think that will happen in time for 1.10?

**Comment by richm** [comment]
this issue/feature does not depend on https://github.com/rsyslog/rsyslog/pull/2466

**Comment by portante** [comment]
So where are we at with this feature?

Can we agree to leave the path as is, drop a JSON file with metadata next to the log file as an option, where that metadata at the least contains: pod name, namespace name, namespace UUID, container ID, container name?

One could consider fetching labels and annotations at the time the metadata file is created and adding those as well.

The key goal would be to NOT require a logging aggregation system to use k8s API calls to fetch pod name, namespace name, namespace UUID, container ID, and container name.  That prevents an over-abundance of API calls to k8s, and removes latency from the logging pipeline.

Actually, with the log file path currently, since it does not container a pod name, how would one fetch that information since we only know pod UUID, container name, and instance number metadata in the file path?

Can container names contain "underscores"?  If so, then using "_" as a separator in the filename is not ideal.

**Comment by crassirostris** [comment]
> Actually, with the log file path currently, since it does not container a pod name, how would one fetch that information since we only know pod UUID, container name, and instance number metadata in the file path?

Entity reading logs would need to maintain a mapping AFAIU

I would totally switch to something like `<namespace_name>/<pod_name>/<pod_UUID>/<container_name>_<attempt>.log` to make it easier to query metadata directly from the kubelet/apiserver later

**Comment by jberkus** [comment]
@portante @crassirostris if this feature is going to stay in 1.10, it needs status/approved-for-milestone label, and needs to either be priority/important-soon, or needs to be merged *today*.  In 7 hours, we enter code freeze.  Thanks!

**Comment by crassirostris** [comment]
I think it's up to @Random-Liu, @yujuhong and @portante, since I cannot implement it anyways

**Comment by jberkus** [comment]
Apologies for munger bug, it's actually 3 days.

**Comment by jberkus** [comment]
This feature issue will be removed from 1.10 in 24 hours if not update.

@portante @yujuhong @Random-Liu

**Comment by richm** [comment]
How do we request a feature like "please, this feature is really important to us, and probably the wider community, but our team currently doesn't have the resources to work on this in the time it will take this request to expire, but we would like to make sure the community knows about this feature in case someone can work on it, and please leave this request in a conspicuous place for at least a few months to give the community time to find it and process it"?

**Comment by dims** [comment]
@richm the issue is not being closed, just moved from milestone v1.10

**Comment by jberkus** [comment]
Removed from 1.10.

@richm you do it like this:

/help

**Comment by Random-Liu** [comment]
This release, let's at least add necessary metadata into the CRI log path to avoid regression.

Here is current status:
* Old path: /var/log/containers/PODNAME_PODNAMESPACE_CONTAINERNAME-CONTAINERID.log
* New path: /var/log/pods/PODUID/CONTAINERNAME/RESTARTCOUNT.log

Metadata missing:
* PodName
* PodNamespace
* ContainerID

PodName and PodNamespace are easy to add. However, `ContainerID` is a bit hard. The problem is that today kubelet generates and passes container log path to container runtime before creating a container, but kubelet only knows the container ID after container is created.

If we really think `ContainerID` is required, there are at least 2 options, but both of them have pros:
* Option 1: Kubelet only defines the log file name convention, and container runtime actually creates the log file. Container runtime knows the container id, and can add it into the filename. Pros: This is a breaking change. It requires kubelet, CRI and all container runtimes to make change.
* Option 2: Define CRI log path and log path for logging agent separately. We can put minimum things required into CRI log path, and create symlink for all container logs to include more metadata needed for logging agent, e.g. container id. Pros: Container ID is the only thing we can't generate before creating container today, does it worth maintaining the symlink just for container id?

**I think we need to at least add `PodName` and `PodNamespace` this release. As for `ContainerID`, we can add it only if we think it is required, and find a good solution to support it.**

**The new log path proposed `PodUID_PodName_PodNamespace/ContainerName/RestartCount.log`.**

To make sure the change is backward compatible, we need to:
1) Make sure kubelet get log path from container status, so that it can get correct log path for old containers. https://github.com/kubernetes/kubernetes/pull/63268
2) Handle old container log path garbage collection to make sure kubelet clean it up properly.

@kubernetes/sig-node-api-reviews @kubernetes/sig-instrumentation-api-reviews @feiskyer @yujuhong @dashpole @mrunalp @portante

**Comment by portante** [comment]
Also missing `PodNamespaceUID`, can we add that?  This will allow us to accurately support reviewing historical logs per-namespace (tenant) as the logs age and namespaces are potentially deleted without requiring a namespace lookup.

What about a third option:

 * Leave CRI log path as is, `PodUID/ContainerName/RestartCount.log`, and create a `PodUID/ContainerName/metadata.json` to hold the additional metadata of: `PodName`, `PodNamespace`, `PodNamespaceUID`, and `ContainerID`.

Then we just need to make sure we properly garbage collect the new `metadata.json` file, allowing old clients to work today, and new clients to take advantage of the additional metadata.

Thoughts?

**Comment by portante** [comment]
Adding `PodNamespaceUID` later would be fine.

In theory, there would be one namespace API fetch call per container log file creation, cacheable on the PodUID, as PodUID / PodNamespaceUID is a fixed relationship for all time, right?

**Comment by nikhita** [comment]
/remove-lifecycle stale

Looks like there is still some discussion pending and this does not have explicit clear directions for contributors to dive into. Removing the help wanted label.
/remove-help

**Comment by richm** [comment]
@jcantrill @ewolinetz

**Comment by portante** [comment]
@brancz, are there any plans to implement this request?

**Comment by brancz** [comment]
I don't think there is anyone with bandwidth to do this currently, but I think there is general consensus that this is a good idea, so if you want to go ahead and implement this, I'd say go for it!

**Comment by dashpole** [comment]
Namespace name has already been added: https://github.com/kubernetes/kubernetes/pull/74441.

The only thing potentially missing is namespace UID.  Is that still required?

**Comment by portante** [comment]
Having the namespace "name" and "UID" at the time the logs directory helps avoid unnecessary API calls to avoid ambiguity when archiving logs long term.

Logging subsystems which need to store logs for a "long" time will often be required to make sure that logs from one namespace don't leak into another namespace.  This includes making sure that two separate namespaces which share the same name but lived at different points at time don't conflict in the stored logs.

A logging system could get that mapping of name to UID itself, and many do today, but that adds another call to the master for each container, potentially.  A logging subsystem can try to "cache" the mapping to avoid API pressure, but the heuristic is shaking at best.

By providing the mapping once, authoritatively, at the time the log directory is created, we avoid ambiguity and unnecessary API calls.

It is not clear to me that placing metadata in directory names is the way to go.  A `metadata.json` file in the logging directory named using the UID of the container, which contains the namespace name, namespace UID, pod name, pod UID, and container name, would avoid file name limitations with the directory name.

**Comment by dashpole** [comment]
I brought this up at sig-node today. There was agreement that it was a reasonable request to add namespace UID.  There are still two concerns: scalability of having all nodes watching all namespaces, and the mechanism to expose namespace UID, as there are limitations (which you point out).  For the mechanism to expose metadata, i'd recommend either updating the CRI logging KEP with your proposed change, or creating a new KEP.  For the scalability concern, it is probably a good idea to raise the idea of kubelets watching all namespaces with sig-scalability to see if they think it is feasible, and what testing would be required to ensure the impact is small enough to be acceptible.

**Comment by portante** [comment]
> I brought this up at sig-node today. There was agreement that it was a reasonable request to add namespace UID.

Great!

> For the mechanism to expose metadata, i'd recommend either updating the CRI logging KEP with your proposed change, or creating a new KEP.

Happy to do this.  I am not sure about the KEP process, so if somebody could work with me on that, that would be great.

> For the scalability concern, it is probably a good idea to raise the idea of kubelets watching all namespaces with sig-scalability to see if they think it is feasible, and what testing would be required to ensure the impact is small enough to be acceptable.

Not sure a node would need to watch all namespaces.  They just need the UID of the namespace at the time a container for a pod is instantiated on a kubelet.  So a node runs a sub-set of pods, and in turn a sub-set of namespaces.  Seems like having the UID of the namespace included when the pod is created would be the more scalable way to do this.

I am not part of sig-scalability, but would be happy to work with somebody that is to discuss this.

**Comment by brancz** [comment]
@portante we were re-iterating on this issue in today's sig instrumentation meeting, and the guarantee that Kubernetes gives is that a namespace is unique at any point in time, so we were wondering what use cases this was a necessity for?

**Comment by dashpole** [comment]
This came up at sig-instrumentation today.  We were trying to figure out what kinds of problems you could prevent by adding namespace UID.

**Comment by portante** [comment]
The life-time of a namespace in kubernetes is potentially much shorter than log retention requirements placed on customers using that namespace, either self-imposed or legal.  A namespace might live for 2 months in a Kube deployment, but the logs might need to be retained for 1 year.

The UID ensures that re-used namespaces over time won't be tracked as the "same" when stored in some aggregated repository.

Because a UID is not provided along side the namespace name, the collection system will likely have to fetch the UID of that namespace repeatedly to make ensure it name to UID pairing is valid, and watch to know when the namespace is removed to make sure to break the association of name to UID.  All of this is fragile for long term storage considerations.

If Kube provided the UID and name at the same time, or even just the UID, then no API calls have to be made to Kube from a collection system in order for it to work properly.

**Comment by jcantrill** [comment]
> @portante we were re-iterating on this issue in today's sig instrumentation meeting, and the guarantee that Kubernetes gives is that a namespace is unique at any point in time, so we were wondering what use cases this was a necessity for?

This original ask stems from a collector being able to scrape logs for pods and namespaces which no longer exist.  Possibly this is an issue related to the GC of those artifacts?  We experienced this issue in cases where QE was creating, deleting, re-creating a namepace that had the same name.  Technically, the left over logs are from a different namespace and the only way to uniquely identify them was by namespace UUID.  There is a desire to be able to retrieve logs from deleted pods.  The only way really to do this would be by a known pod label or the like.

**Comment by brancz** [comment]
If I understand correctly, this is not about a namespace being deleted and re-created quickly, but rather the same namespace name being used after a longer period of time, and the inability to differentiate those.

**Comment by ewolinetz** [comment]
> the same namespace name being used after a longer period of time, and the inability to differentiate those

correct

**Comment by portante** [comment]
> If I understand correctly, this is not about a namespace being deleted and re-created quickly, but rather the same namespace name being used after a longer period of time, and the inability to differentiate those?

Yes.

** Long answer below to try to illustrate why adding the UID is beneficial to Kubernetes. **

The responsibility of any log aggregation system is to maintain access to logs via authorized users only.  It is NOT the responsibility of any Kubernetes deployment to ensure the log aggregation system can do that.

However, the way log aggregation systems ensure proper access to a namespace's logs is to either **_capture_** the UID of that namespace, or **_create_** its own UID for that namespace and maintain mappings over time.

The method of _creating_ a UID for a namespace is fragile at best, because log aggregation systems are only exposed to namespace names when log files are created, and are not aware of when namespaces come into existence.  The creation method is also fragile because the log collectors potentially see logs for namespaces at different times, which require coordination amongst collectors to agree on the proper UID.

The method of _capturing_ the UID *can* also be **fragile** and **expensive** when the log aggregation system sees a namespace name _without_ a UID and has to _query_ for that UID at a later time.  It is **fragile** in that potentially enough time has passed since the logs for a namespace were written that the namespace name no longer exists (and don't just consider QE examples here, if a node with logs goes down for a period of time, is repaired and returned to service, the existing logs on that node might be very old; there are many, many scenarios we can construct like this).  It is **expensive** in that each individual log collector needs to issue a query for the UID of a namespace, and can't effectively cache that mapping crossing re-starts or long stretches of time without seeing logs from that namespace.  The number of required queries grows with the total number of log collectors in operation (typically, # of nodes).

However ...

If Kubernetes always provides the UID with the namespace name, then any log aggregation system can **inexpensively** capture the namespace name and UID at that time, without issuing ANY queries for maintaining that mapping.  The **fragility** of the namespace name to UID mapping is then removed since the authority that maintains that mapping provided it at the time the log file was created.

**Comment by jingxu97** [comment]
@brancz will sig-instrumentation still want to handle this issue?
