### ISSUE TITLE
CoreOS multinode cluster getting started guide ignores networking

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#5863]
docs/getting-started-guides/coreos/coreos_multinode_cluster.md

This doc does not seem to mention networking at all.  People are following this doc and failing, which is not surprising given $subject

@kelseyhightower

**Comment by thockin** [comment]
I apologize, the cloud config files DO talk about flannel.  The doc should probably mention that

**Comment by kelseyhightower** [comment]
@thockin Right, the cloud-config setup flannel and we should update the guide to call that out.
