### ISSUE TITLE
Proposal: NetworkPolicy support for selecting pods in another namespace

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#58637]
People want the ability to specify specific pods within a (different) namespace in NetworkPolicies.

I propose we change the documentation/definition of `NetworkPolicyPeer` so that instead of saying "Exactly one of its fields must be specified", we say that there are 4 valid kinds of NetworkPolicyPeer:

1. If only `PodSelector` is set, then the peer selects the indicated pods in the same namespace as the NetworkPolicy.
2. If only `NamespaceSelector` is set, then the peer selects all pods in the indicated namespaces.
3. (**NEW**) If both `PodSelector` and `NamespaceSelector` are set, then the peer selects the indicated pods in the indicated namespaces. (And, in particular, if `PodSelector` is set and `NamespaceSelector` is `{}`, then the peer selects the indicated pods in all namespaces.)
4. If only `IPBlock` is set, then the peer selects the indicated IP addresses.

As before, it would be invalid to have a `NetworkPolicyPeer` in which all fields were unset, or in which both `IPBlock` and any other field were set.

This shouldn't create any compatibility issues: no old policies would be interpreted differently under the new rules, because the new rules only describe the interpretation of policies that would be invalid under the old rules. And likewise, policies using the new features would not be interpreted incorrectly by old plugins; they'd just be rejected as invalid.

/sig network
/kind feature

**Comment by tgraf** [comment]
I can't think of any case how this can break compatibility. I also think that this is what the user would expect anyway.

**Comment by salv-orlando** [comment]
I agree that there is no compatibility issue. Unless one considers a compatibility problem the fact that a policy spec that was failing before now is accepted (hopefully not, please don't!)

**Comment by thockin** [comment]
I'm concerned about how complex this becomes over time, if we add more fields here.  Today it is simple - exactly one.  If we allow one or two, but not any combination, it's awkward at best.

Can we make it a generic AND ?

Or maybe we should add a new struct field (good name needed) with PodSelector and NamespaceSelector fields?

**Comment by Lion-Wei** [comment]
I think we can use selectors in same `NetworkPolicyPeer` as AND, combine `NetworkPolicyPeer` list with OR.

**Comment by danwinship** [comment]
> If we allow one or two, but not any combination, it's awkward at best.

It's true

> Can we make it a generic AND ?

In theory, yes, but there are no proposed use cases for ipblock plus anything else, so it seems like extra work for implementors with no gain for users. It also potentially constrains us in the future.

> Or maybe we should add a new struct field (good name needed) with PodSelector and NamespaceSelector fields?

You don't want to call it "RemotePodSelector" or "ExternalPodSelector" or something like that if it can also select pods in the local namespace. So I feel like we'd be stuck with something clear but terrible like "PodAndNamespaceSelector"

    - from
      - podAndNamespaceSelector:
          namespaceSelector: {}
          podSelector:
            matchLabels:
              environment: production

Though one advantage of this is that it does prevent you from accidentally writing

    - from
      - namespaceSelector: {}
      - podSelector:
          matchLabels:
            environment: production

when you meant

    - from
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            environment: production

**Comment by sathieu** [comment]
I like this proposal, but this explicitly breaks the [The NetworkPolicy Resource](https://kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource) example.

Which says for:
```
  ingress:
  - from:
    - ipBlock:
        cidr: 172.17.0.0/16
        except:
        - 172.17.1.0/24
    - namespaceSelector:
        matchLabels:
          project: myproject
    - podSelector:
        matchLabels:
          role: frontend
```
- allows connections to TCP port 6379 of “role=db” pods in the “default” namespace from any pod in the “default” namespace with the label “role=frontend”
- allows connections to TCP port 6379 of “role=db” pods in the “default” namespace from any pod in a namespace with the label “project=myproject”
- allows connections to TCP port 6379 of “role=db” pods in the “default” namespace from IP addresses that are in CIDR 172.17.0.0/16 and not in 172.17.1.0/24

**Comment by sathieu** [comment]
Dup of #50451?

**Comment by danwinship** [comment]
It doesn't break that example; that has three separate `NetworkPolicyPeer` elements under `from`, so it selects three separate sets of traffic. The proposed new syntax would put the `namespaceSelector` and `podSelector` into the same `NetworkPolicyPeer`. ie, removing the `-` before `podSelector` in that example.

But that ties into what I was saying before about "accidentally writing X when you meant Y". YAML gets confusing if you have an array of a struct type where all of the fields in the struct are optional but it's also possible for more than one of them to be set. We have this problem with `NetworkPolicyIngressRule` and `NetworkPolicyPort` already. Eg

    ingress:
    - from: 
      - podSelector:
          matchLabels:
            app: frontend
      ports:
      - protocol: TCP
        port: 3306

("traffic from app=frontend pods to TCP port 3306")
vs

    ingress:
    - from: 
      - podSelector:
          matchLabels:
            app: frontend
    - ports:
      - protocol: TCP
        port: 3306

("traffic from app=frontend pods (to anywhere), **or** to TCP port 3306 (from anywhere)")
vs

    ingress:
    - from: 
      - podSelector:
          matchLabels:
            app: frontend
      ports:
      - protocol: TCP
      - port: 3306

("traffic from app=frontend pods to any TCP port, including (redundantly) port 3306")

(qv https://bugzilla.redhat.com/show_bug.cgi?id=1464251, https://bugzilla.redhat.com/show_bug.cgi?id=1529517)

**Comment by sathieu** [comment]
@danwinship Thanks.

**Comment by thockin** [comment]
I'm 100% in favor of this proposal.  Unsure about the new struct vs allowing pod AND namespace in the oneof scope.

Any further thoughts @danwinship  ?  What's your pref?

**Comment by danwinship** [comment]
Slight preference for the original proposal (specifying both `podSelector` and `namespaceSelector` in the same `NetworkPolicyPeer`).

Given that our syntax is already confusing (https://github.com/kubernetes/kubernetes/issues/58637#issuecomment-365262938), I'm not as worried about introducing one more confusable field. We should just explicitly point out the issue in the docs, and maybe update "kubectl describe networkpolicy" to be even clearer about the distinctions, and then remember all of this when designing NetworkPolicy v2. (1: We don't need to make *every* field an array. 2: Where we do have arrays-of-structs, try to have at least one required field in that struct.)
