### ISSUE TITLE
an error on the server ("missing route (service \"sample-api\" not found)") has prevented the request from succeeding (get flunders.wardle.k8s.io)

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#58642]
`Jan 22 22:15:31.659: Couldn't delete ns: "e2e-tests-statefulset-fg2hp": an error on the server ("missing route (service \"sample-api\" not found)") has prevented the request from succeeding (get flunders.wardle.k8s.io) (&errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"an error on the server (\"missing route (service \\\"sample-api\\\" not found)\") has prevented the request from succeeding (get flunders.wardle.k8s.io)", Reason:"InternalError", Details:(*v1.StatusDetails)(0xc4216bc960), Code:500}})`

* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20776
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20777
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20775
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20774
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20772
* ... A lot of them

@kubernetes/sig-api-machinery-bugs 
/cc @cheftako

**Comment by Random-Liu** [comment]
Still see this failure after #58697 is merged:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/20811
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce/1906

Reopen.

**Comment by liggitt** [comment]
Looks like the client doesn't differentiate between 500 and 503 here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go

It should. Will open a fix shortly

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/58735

**Comment by liggitt** [comment]
fix merged, will monitor https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/

**Comment by jennybuckley** [comment]
@cheftako

**Comment by Random-Liu** [comment]
@liggitt Thanks! :)

**Comment by liggitt** [comment]
haven't seen this in the 12 hours since the fix merged, was seeing it every 2-3 hours before.

/close
