### ISSUE TITLE
Manifests in test/e2e/testing-manifests/ingress related to GCE should be in a separate folder.

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#58640]
Manifests should ideally be in a folder gce/ for clarity.

/assign

**Comment by nikhita** [comment]
/remove-lifecycle stale

This looks like something a new contributor can take up so I'm going to label it as a good first issue. 

/good-first-issue

**Comment by LeafyLi** [comment]
Can I try working on this?

**Comment by nikhita** [comment]
@LeafyLi Go ahead, it's all yours! :tada:

**Comment by LeafyLi** [comment]
Is it recommended to build on Docker or local?

**Comment by surajnarwade** [comment]
@rramkumar1, @nikhita  , can you point me to the manifests related to GCE, I am little bit confused which one are the GCE related.

I would like to work on this :smile:

**Comment by vllry** [comment]
I'd like to work on this as a first-PR.
