### ISSUE TITLE
Update to etcd 3.2.14

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#58652]
For the 1.9 cycle we have incremental update to etcd 3.1.10 at https://github.com/kubernetes/kubernetes/issues/49386

For the 1.10 cycle, we should update the etcd to [3.2.X](https://github.com/coreos/etcd/blob/master/CHANGELOG.md#v3214-2018-01-11) to pick up the latest fix for etcd. 

We have did regression test for etcd 3.2.14 with both 1.9.x and master, it works fine.

/cc @kubernetes/sig-cluster-lifecycle-misc @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc

**Comment by timothysc** [comment]
There are PRs either pending or merged on this. 

/cc @jpbetz @wojtek-t @xiang90

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/57480 , https://github.com/kubernetes/kubernetes/pull/57230  

closing, and folks can PR if there are compelling reasons todo a minor version bump.

**Comment by gyliu513** [comment]
Thanks @timothysc , I have filed another issue https://github.com/kubernetes/kubernetes/issues/58654 to bump up the minor version for etcd due to a critical fix for large scale cluster.
