### ISSUE TITLE
godep save: Unable to find dependent package k8s.io/kubernetes/pkg/kubelet/apis in context of  /root/coding/src/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1

### ISSUE THREAD

**Issue by harryge00** [kubernetes/kubernetes#58656]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

Cannot `godep save`

```
# ./hack/godep-save.sh 
+++ [0123 11:53:43] Ensuring prereqs
+++ [0123 11:53:43] Running godep save - this might take a while
godep: Unable to find dependent package k8s.io/kubernetes/pkg/kubelet/apis in context of /root/coding/src/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1
!!! Error in ./hack/godep-save.sh:69
  Error in ./hack/godep-save.sh:69. 'GOPATH="${GOPATH}:$(pwd)/staging" godep save "${REQUIRED_BINS[@]}"' exited with status 1
Call stack:
  1: ./hack/godep-save.sh:69 main(...)
Exiting with status 1
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Lastest master 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Ubuntu 14.04.5 LTS, Trusty Tahr
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fejta** [comment]
Maybe ask about this in kubernetes-dev channel on slack if you can't figure it out?
