### ISSUE TITLE
Upgrade etcd to 3.2.14

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#58654]
We have upgrade etcd to 3.2.13 in https://github.com/kubernetes/kubernetes/pull/57480 and https://github.com/kubernetes/kubernetes/pull/57230 for Kubernetes 1.10.X

In etcd 3.2.14, there is one fix which [fixed a panic during a defrag like below with etcd v3.2.10 under heavy load (larger IO wait)](https://github.com/coreos/etcd/blob/master/CHANGELOG.md#v3214-2018-01-11)，this is a very important fix for a large scale kubernetes cluster which would cause etcd has high load, so it is better to bump the minor version for etcd a bit, from 3.2.13 to 3.2.14 for Kubernetes.

/area etcd
/sig api-machinery
/kind enhancement
/sig cluster-lifecycle
/sig scalability

/cc @kubernetes/sig-cluster-lifecycle-misc @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc @timothysc

**Comment by liggitt** [comment]
probably don't need this and https://github.com/kubernetes/kubernetes/issues/56438 both open

**Comment by wojtek-t** [comment]
@jpbetz - I think this is an important one.

**Comment by jpbetz** [comment]
Agreed. Updating to 3.2.14 instead of 3.2.13. We will use https://github.com/kubernetes/kubernetes/issues/56438 to track.

**Comment by gyuho** [comment]
just fyi. etcd CHANGELOG link is changed to https://github.com/coreos/etcd/blob/master/CHANGELOG-3.2.md#v3214-2018-01-11.
