### ISSUE TITLE
assign pod ip running in node with multiple network interface

### ISSUE THREAD

**Issue by huzhengchuan** [kubernetes/kubernetes#58678]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
Run application on kubernetes, the application use hostNetwork: true, and the application scheduler to node-A, the node-A has mutilple eth interface, I see the ip of pod is from the ip of node. but something want the other eth interface. because the eths interface has different performance.  how to set it? 
it will effect access services through kube-dns.

**What you expected to happen**:
want to set the ip of pod when pod use hostNetwork

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: baremetal 
- Kubernetes version (use `kubectl version`): kubernetes 1.8.3
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huzhengchuan** [comment]
the question can fix like this
https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by hibby50** [comment]
> the question can fix like this
> https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

Can you specify what section of that doc resolved the issue for you? I am running into the same problem

**Comment by CharlieR-o-o-t** [comment]
@huzhengchuan , 

If you run pod with `hostNetwork: true` kubelet will try to assign pod IP from **first** Node `InternalIP` address.
If no `InternalIP` addresses has been set to node - first  node`ExternalIP` will be used.

I don't know your case, seems, that it's better for you to build one logical network interface from two physical devices (interface bonding). Overwise - you will need customization on your cloud-provider controller to set node IPs in specific order.
