### ISSUE TITLE
pull-kubernetes-e2e-kops-aws is flaky due to quota setup in the cncf account

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#58709]
open an issue to track progress:

last update: https://kubernetes.slack.com/archives/C09QZ4DQB/p1516685722000284

cc @justinsb @chrislovecnm @mattlandis @arun-gupta 
/sig aws
/kind bug

**Comment by mattlandis** [comment]
The earlier VPC limit increase only went out to some regions.  I have pushed the VPC limit update to all regions.

Have a request in progress for increasing the instance limit to 60 for all regions.  Waiting for approvals should hear back in the next 24 hours.

Have someone looking into the 5k limit increase for scalability testing.  That may take longer.

**Comment by justinsb** [comment]
Thanks you @mattlandis (and @krzyzacy ).  And getting the smaller limit bump faster, followed by a bigger increase for scale testing seems like a great approach - we need the former "today", the latter is important but less critical!

**Comment by porridge** [comment]
This test finally passed for me in #54294, does it mean it's fixed? If so, then perhaps it should be retried on all PRs in which it failed in the last weeks?

**Comment by chrislovecnm** [comment]
Quotas have been fixed.

/assign
/close

**Comment by chrislovecnm** [comment]
@porridge yes people can retry their tests if they have not

**Comment by porridge** [comment]
I kind of hoped sig-testing has tools to trigger retries in a batch way
after such widespread issue is resolved.

**Comment by krzyzacy** [comment]
@porridge @fejta-bot will automatically drop `/retest` on affected PRs
