### ISSUE TITLE
GCE support for heterogenous nodes

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#5871]
We currently use a single managed instance group by default for GCE.  It's a user request that we should eventually support heterogenous nodes such that users can have e.g. a set of VMs optimized for DBs (high I/O b/w or more local SSD) and a different set for less-demanding pods (e.g. stateless frontends).

**Comment by roberthbailey** [comment]
+1

**Comment by zmerlynn** [comment]
What is the priority on this? Multiple MIGs would have a lot of ripples in
the code.

**Comment by alex-mohr** [comment]
At this point post v1.

**Comment by yawnt** [comment]
how far away is v1?

**Comment by alex-mohr** [comment]
@yawnt we don't have an ETA for v1 yet.  See https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0 for the set of open issues for that milestone.

**Comment by erickhan** [comment]
I think we should move this out of v1. @yawnt  and others, please share any feedback here or directly.

Impact if we do not have this: nodes will be of 1-size, leading to cases where a smaller size might have been ok.

Reasons I think move is appropriate: besides time and the priorities of other items, I would want to understand this in a multi-cloud world. The pattern here maybe different, as I look at the myriad "knobs" that cloud providers have. I worry that this (without more diligence) will have too many sharp edges.

**Comment by mikedanese** [comment]
Is this done? cc @fabioy

**Comment by roberthbailey** [comment]
GKE supports heterogeneous nodes. The kube-up shell scripts don't (although they do support multi-zone clusters, so maybe you could somehow take advantage of that to achieve the desired result). 

@mikedanese -- will the new deployment scripts support this? I don't think it's worth adding into the kube-up scripts at this point.

**Comment by mikedanese** [comment]
Ya it's pretty trivial in the new deployment scripts. Ok, I'm going to close then.

**Comment by roberthbailey** [comment]
excellent.

**Comment by erickhan** [comment]
nice to get these GH notifications. Congrats guys!
