### ISSUE TITLE
cloud provider could not be initialized

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#58729]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
add --cloud-provider=openstack --cloud-config=/etc/kubernetes/kube-openstack-conf 
**What you expected to happen**:
the kube-controller-manager service and the kubelet service not running

Jan 23 16:07:03 node-2 kube-controller-manager: F0123 16:07:03.221788   21103 controllermanager.go:181] error running controllers: cloud provider could not be initialized: could not init cloud provider "openstack": Post http://10.10.106.33:8089/v2.0/tokens: dial tcp 10.10.106.33:8089: getsockopt: no route to host

[kube-controller-manager.txt](https://github.com/kubernetes/kubernetes/files/1658338/kube-controller-manager.txt)
![image](https://user-images.githubusercontent.com/25783555/35312341-e97c27f6-00f5-11e8-8beb-7172779fd962.png)
the kubelet log is:
![image](https://user-images.githubusercontent.com/25783555/35312374-0e163f8e-00f6-11e8-8e77-9206274b3cdd.png)

**How to reproduce it (as minimally and precisely as possible)**:
all service running

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.6.9
- Cloud provider or hardware configuration:openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jianglingxia** [comment]
I see the err return that the func:
![image](https://user-images.githubusercontent.com/25783555/35312481-9ad2bd4e-00f6-11e8-99aa-b64a52483fec.png)
why initialize failed?thanks 
/assign @FengyunPan

**Comment by FengyunPan** [comment]
> Post http://10.62.106.33:8089/v2.0/tokens: dial tcp 10.62.106.33:8089: getsockopt: no route to host

What is '10.62.106.33:8089/v2.0'? Keystone? Auth_url?

> no route to host

Can't access openstack, please check '10.62.106.33:8089'.

**Comment by jianglingxia** [comment]
auth_url
![image](https://user-images.githubusercontent.com/25783555/35316784-713d0bfc-010e-11e8-818b-0aab206bd962.png)
but 
![image](https://user-images.githubusercontent.com/25783555/35317254-db30b71e-0110-11e8-8b8a-4f342d3c0220.png)

**Comment by stewart-yu** [comment]
can you use `1.9.0+` or `master` have a try? @jianglingxia

**Comment by dims** [comment]
1.6.9 is too old. yes please try newer versions like @stewart-yu mentions

/close

**Comment by SJYMickeyMouse** [comment]
@stewart-yu I use 1.9.0+，but i still meet this issue。
