### ISSUE TITLE
Setting kube-proxy port range with"BeginPort+Offset" format

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#58730]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

Implement this TODO:
[https://github.com/kubernetes/kubernetes/blob/35ed5338b104f41c91efb2b842e92fded6d0b509/staging/src/k8s.io/apimachinery/pkg/util/net/port_range.go#L53](https://github.com/kubernetes/kubernetes/blob/35ed5338b104f41c91efb2b842e92fded6d0b509/staging/src/k8s.io/apimachinery/pkg/util/net/port_range.go#L53)

**What you expected to happen**:

Start kube-proxy with a 'beginPort+offset' format port range configuration. This is needed when I want to allocate specific numbers of port from a host without extra manual calculation.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jennybuckley** [comment]
/sig network
Does anyone besides kube-proxy use this?
