### ISSUE TITLE
vSphere cloud provider should not require its own role and policy

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#58747]
In 1.9 vSphere cloud provider creates a new `vsphere-cloud-provider` client, new shared informer factory and lists nodes [here](https://github.com/kubernetes/kubernetes/blob/2f4cca73af088a0547feeab75c8dc3fb92fde6b6/pkg/cloudprovider/providers/vsphere/vsphere.go#L221)

IMO, the cloud provider should not create it's own client at all. GCE uses [SetInformer interface](https://github.com/kubernetes/kubernetes/blob/2f4cca73af088a0547feeab75c8dc3fb92fde6b6/pkg/cloudprovider/providers/gce/gce.go#L658), called by controller-manager to initialize the cloud provider. This way, GCE does not need extra policy and it shares the informer with all the controllers. `SetInformer` is called only in controller-manager process, i.e. for provisioning and attach/detach. Do you need the informer really in kubelet and/or API server? It's quite odd to list all nodes there.

/kind bug
/sig storage
/sig auth
@kubernetes/vmware 
@kerneltime @divyenpatel @BaluDontu

**Comment by divyenpatel** [comment]
@jsafrane issue regarding `client can not list nodes` is getting fixed with creating `ClusterRole` and binding with `vsphere-cloud-provider` ServiceAccount.

See https://github.com/kubernetes/kubernetes/issues/57279#issuecomment-359607201

@jsafrane is there a way in kubernetes, we can fix this without assigning permissions to  `vsphere-cloud-provider` serviceaccount?

We will look into SetInformer interface GCE uses.

**Comment by liggitt** [comment]
>  is there a way in kubernetes, we can fix this without assigning permissions to vsphere-cloud-provider serviceaccount?

cloud provider specific roles should be applied externally as we prepare for moving cloud provider specific components out of tree. 

> We will look into SetInformer interface GCE uses.

@deads2k had feedback on the way that was wired in that would be good to adjust before copying that pattern

**Comment by jsafrane** [comment]
@divyenpatel, thanks for the pointer to old issue.

I reworked this one to remove vsphere's own client (and policy).

**Comment by rayterrill** [comment]
Running into this same issue (manifested as "Kubernetes node nodeVmDetail details is empty" error upon pvc build using vsphere). Commenting to watch progress. Happy to help debug if needed.
