### ISSUE TITLE
Azure - Cloud Provider / ARM Calls

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#58770]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The cloud provider specifically in response to service sync loop produce a large # of GET calls against ```.../providers/network/loadbalancer``` and ```../providers/network/networkSecurityGroups```. This does not affect smaller clusters but does affect larger clusters as it quickly burn through [ARM calls quota limits](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits) This result into HTTP 429 HTTP code throttling the cloud provider. For an un-busy cluster this has no impact, however with cluster with large # of services / disks / DNS (via external-dns) coming in and out this will bring PUT/POST calls to a halt/or at least slow them significantly (because ARM will refuse calls above the limits). Note every PUT call is preceded with GET to the get the model before updating it.

**What you expected to happen**:
ARM calls should be at minimum for GET. 

**How to reproduce it (as minimally and precisely as possible)**:
Run large cluster 150 node+ with large number of create/delete services (add/edit/delete) w or w/o external DNS labels. Keep an eye on controller logs, cloud provider will start logging 429 response code from ARM.

**Environment**:
- Kubernetes version (use `kubectl version`): *
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): *
- Kernel (e.g. `uname -a`): *

**Proposed fixes: [1.10 timeframe]**
1. Generalize the cache for [used only by VM GET] (https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_cache.go) for **LB** models and **NSG** models. 
2. Replace ```ratelimiter.Accept()``` with ```ratelimiter.TryAccept()``` This forces the aggressive sync loop to backoff retry instead of flooding the waiting for available token from rate limiting bucket.
3. Tune cloud provider QPS (rate) to correct ARM buckets based on the limits above.
4. Split the rate limiting to READ/WRITE limiters due the huge gap between READ/WRITE limits in ARM. 

@jackfrancis @brendanburns @jdumars 
/sig-azure

**Comment by khenidak** [comment]
@kubernetes/sig-azure-misc

**Comment by feiskyer** [comment]
@khenidak Also noticed the problem when I'm scaling a lot of nodes. Will add a cache for LB and NSG next week.

**Comment by khenidak** [comment]
Closed with PRs linked. #3 above is configuration guidance which will be published separately.

@jdumars
