### ISSUE TITLE
User should be able to update `metadata.generation` field of a custom resource

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#58778]
User cannot update the generation field by themselves, because the apiserver clears the change in [BeforeUpdate](https://github.com/kubernetes/kubernetes/blob/40212c17cdf4d7bc2a45c495cf0d37ebab032578/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L103). This makes sense for native objects, because it would have confused controllers if user were allowed to change generation freely. The kubernetes's registry detects the spec change and increments the generation. But for custom resource, apiserver doesn't automatically increment `metadata.generation`, so it's reasonable to allow user to update it.

cc @nikhita @sttts @mbohlool @erictune

**Comment by caesarxuchao** [comment]
Relaying @erictune 's suggestion in an email:
```
For v1 CRDs, we could have a bit in the CRD where you say if you want spec to follow spec and status conventions, and if set, then generation should be managed.

For v1beta1 CRDs, we should just not block the user from updating metadata.
```

**Comment by liggitt** [comment]
I'd prefer to keep this unmodifiable until we have the spec/status bits available. Components rely on fields within metadata to follow uniform system-enforced behavior and should not have to be concerned that an object is a CRD and its generation is allowed to behave in unexpected ways

**Comment by sttts** [comment]
> But for custom resource, apiserver doesn't automatically increment

This comes with @nikhita's https://github.com/kubernetes/kubernetes/pull/55168. I agree with @liggitt that we should get in ASAP instead of thinking about workarounds.
