### ISSUE TITLE
Add "ExpandFS" interface to "ExpandableVolumePlugin"

### ISSUE THREAD

**Issue by xingzhou** [kubernetes/kubernetes#58786]
Per discussion in ["Growing FlexVolume Size"](https://docs.google.com/document/d/1dwom9xQ3Fg5F_jJrybr0slp-QsO3_CKiisxzNRoMhec/edit) proposal, we thought that it would be good to add a new interface named `ExpandFS` to `ExpandableVolumePlugin`. `ExpandFS` will be called when file system resizing is required (offline or online resizing in the future), and this call will let underneath volume plugin decide what to do finally (resize file system or both volume expansion and resizing file system)

Suppose this interface should take the same parameters as the `ExpandVolumeDevice` interface

/sig storage
/assign @gnufied

**Comment by verult** [comment]
Could you give a more concrete example for the use case?

**Comment by gnufied** [comment]
The use case is - similar to format and mount stuff. For example, we know that for most volume types format and mount can be done via a simple utility function that is common to all of them, but having the Mount function as part of volume plugin interface allows a volume plugin to perform certain bespoke actions if necessary. Most volume types currently simple call into `mount.SafeFormatAndMount` internally but allowing mount and unmount as interface function of plugin allows custom action to be performed if necessary.


In same way , having `ExpandFS` as a volume plugin function will allow flex to call custom code when file system resize happens. Other volume types will simply call out to `resizefs.Resize()` as it is being done currently but the hook will enable flex (or other volume types) to perform special actions that are only relevant to that volume type.

**Comment by verult** [comment]
Thanks for the clarification. Two points:

1. Perhaps it's better to call them `MasterExpand` and `NodeExpand` vs `ExpandDevice` and `ExpandFS`?
1. If `ExpandDevice` is a no-op for storage systems that require device resize to be done on the node, are we going to update the PVC with the size it's supposed to be if device resize were successful? What if `ExpandFS` fails?

**Comment by gnufied** [comment]
if `ExpandDevice` is a no-op for storage systems then just the PV size will be updated on the controller-manager as we do currently. If `ExpandFS` fails on the node, the PVC will not reflect user requested size in `pvc.Status` . I think this flow is not very different from current behavior where `ExpandFS` may fail even if `ExpandDevice` has succeeded.
