### ISSUE TITLE
Remove version suffix from cluster addon name

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#58785]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement
/sig cluster-lifecycle

**What happened**:
There are couple cluster addons that use name in format `*-<version>`:
- Metric server deployment:
https://github.com/kubernetes/kubernetes/blob/de694a8aa69e3138c3915c1518c548e96e73561c/cluster/addons/metrics-server/metrics-server-deployment.yaml#L26
- Heapster deployment: 
https://github.com/kubernetes/kubernetes/blob/5312989b04a8cea5128e78bb7f33975037ad3383/cluster/addons/cluster-monitoring/google/heapster-controller.yaml#L52
- Fluentd daemonset:
https://github.com/kubernetes/kubernetes/blob/6831581f1c86003d584a6dd52591bf59035f9f7c/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L4
- Event exporter deployment:
https://github.com/kubernetes/kubernetes/blob/e9dd8a68f60d2565069caed068f8fe4d493ea5ce/cluster/addons/fluentd-gcp/event-exporter.yaml#L32

It would be great to remove the version suffix from these addon names, so that:
1. During cluster upgrade, these addons can be rolling-updated instead of going through the creation & deletion phases, which may cause possibly downtime && duplicated instances.
2. The risk of orphaning the older version instances is reduced. This happened multiple times and was often caused by something totally irrelevant (e.g. configuration error on other addons wedged addon-manager).

As most of these components are relevant to instrumentation, adding sig
@kubernetes/sig-instrumentation-feature-requests

**Comment by MrHohn** [comment]
@stewart-yu Seems like the robot doesn't allow us to assign, but feel free grab the issue if you like.

But before starting the work, it might be better to see if folks from instrumentation would have other thought.

**Comment by DirectXMan12** [comment]
I generally agree with this suggestion, although I was under the impression that the issue was with the way the addon reconciler script worked.  Someone more familiar with that should chime in.

**Comment by MrHohn** [comment]
@DirectXMan12 The addon-manager is essentially doing `kubectl apply -f` periodically, hence any change on the addon resource will be applied upon cluster upgrade. That is also the way some other addons already followed since v1.5 (https://github.com/kubernetes/kubernetes/pull/36008).

**Comment by DirectXMan12** [comment]
ok, so sounds like it's fine to remove the version number.

**Comment by crassirostris** [comment]
I've experienced problems with updating addons without version in the name. Please verify it always works correctly before doing the work

**Comment by MrHohn** [comment]
> I've experienced problems with updating addons without version in the name. Please verify it always works correctly before doing the work

+1, and if there is any problem when rolling updating a daemonset/deployment/etc., we should fix the underlying issue.

**Comment by MrHohn** [comment]
Seems like this is not fixed yet.
/reopen
