### ISSUE TITLE
kubectl apply does not properly minimize patch when using JSON merge patch

### ISSUE THREAD

**Issue by davidhao3300** [kubernetes/kubernetes#58793]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report
/kind bug

**What happened**: Assume a CustomResource
original:
```
{
    "apiVersion": "company/v1",
    "kind": "CustomResource",
    "metadata": {
        "annotations": {},
        "name": "secrets",
        "namespace": "test"
    }
}
```
current:
```
{
    "apiVersion": "company/v1",
    "kind": "CustomResource",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"company/v1\",\"kind\":\"VaultSecret\",\"metadata\":{\"annotations\":{},\"name\":\"secrets\",\"namespace\":\"test\"}}\n"
        },
        "clusterName": "",
        "creationTimestamp": "2018-01-24T22:49:30Z",
        "deletionGracePeriodSeconds": null,
        "deletionTimestamp": null,
        "generation": 0,
        "name": "secrets",
        "namespace": "test",
        "resourceVersion": "4800",
        "uid": "d6e8e5d8-0158-11e8-be12-080027cce81e"
    },
    "time-processed": "2018-01-24T22:49:30"
}
```
modified:
```
{
    "apiVersion": "company/v1",
    "kind": "CustomResource",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"company/v1\",\"kind\":\"VaultSecret\",\"metadata\":{\"annotations\":{},\"name\":\"secrets\",\"namespace\":\"test\"}}\n"
        },
        "name": "secrets",
        "namespace": "test"
    }
}
```

original add-and-change patch current -> modified
```
{
    "metadata": {
        "clusterName": null,
        "creationTimestamp": null,
        "deletionGracePeriodSeconds": null,
        "deletionTimestamp": null,
        "generation": null,
        "resourceVersion": null,
        "selfLink": null,
        "uid": null
    }
}
```
filtered add-and-change patch (non-nulls only)
Note that at this point, the patch could have been optimized to `{}`
```
{"metadata":{}}
```

original deleted patch between original -> modified
```
{
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"company/v1\",\"kind\":\"VaultSecret\",\"metadata\":{\"annotations\":{},\"name\":\"secrets\",\"namespace\":\"test\"}}\n"
        }
    }
}
```
filtered deleted patch (nulls only)
Note that at this point, the patch could have been optimized to `{}`
```
{"metadata":{"annotations":{}}}
```

This results in a non-empty patch, which causes issues since we forbid patches to most users. We'd like for unchanged files to not result in unnecessary PATCH requests, as they result in forbidden requests.

**What you expected to happen**: The modified object above should resolve to an empty patch, and kubectl should not send a PATCH request to the apiserver.

**How to reproduce it (as minimally and precisely as possible)**: create a CustomResourceDefinition, create an instance of the resource using a file, forbid patching to the custom resource, re-apply the same file - you should receive a forbidden error.

**Anything else we need to know?**: This is totally kubectl-side issue - kubectl is calculating a patch, and then sends an unnecessary PATCH request to a non-optimal patch resolution.
I have a fix ready that fixes the issue, but need to wait for my company to read over the CLA.

The issue lies with the code block here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go#L116
The block fails to clean up nested maps that no longer contain any patches, eg `{a: { b: nil } }` filters nils to `{a: {} }` when really it can go further and resolve to `{}`

There's 2 solutions that I can see, I chose the former:
1) Modify the linked block above to remove empty filtered maps if they weren't already explicitly set in the original map
2) Preserve the existing code, and then in kubectl's apply.go go over the filtered patch and remove empty patches there

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6 client/server, but verified `kubectl` built off current master has the same issue.
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): N/A (kubectl running on Mac)
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Others:

**Comment by davidhao3300** [comment]
@kubernetes/sig-api-machinery-bugs
the oroblematic behavior exists in the apimachinery folder

**Comment by liggitt** [comment]
> This results in a non-empty patch, which causes issues since we forbid patches to most users. We'd like for unchanged files to not result in unnecessary PATCH requests, as they result in forbidden requests.

Not to detract from the reported issue, but expecting users to use apply without giving them patch permissions doesn’t really make sense.

**Comment by davidhao3300** [comment]
right - to clarify, we have a repo filled with managed config files. When someone updates the repo, we apply all the config files in the repo (automated), but we don't want certain people changing certain objects of the repo.

**Comment by davidhao3300** [comment]
Thus, even if unprivileged people don't change restricted resources, the apply command will fail overall because we unnecessarily attempt to patch a restricted resource that hasn't changed

**Comment by jennybuckley** [comment]
cc @mbohlool @lavalamp @jpbetz @mengqiy @caesarxuchao 
/sig cli

**Comment by nikhita** [comment]
@davidhao3300 Do you see this only for custom resources?

If so, it should mostly be solved by https://github.com/kubernetes/kubernetes/pull/58332.

**Comment by davidhao3300** [comment]
I did see this behavior only for custom resources, I'll check if the branch in that PR addresses this issue

**Comment by davidhao3300** [comment]
@nikhita confirmed that the PR does not fix this issue

**Comment by Quentin-M** [comment]
I have seen similar behaviors with:
- cluster scoped resources, that will try to set the namespace again
- any other resources, with annotations/labels being randomly set to {}.

**Comment by lavalamp** [comment]
We intend to move computation of the resource to the control plane, so this is **not** going to be supported long term even if kubectl is "fixed".

Is there a reason why you can't segregate the resources by permissions?

**Comment by liggitt** [comment]
Agree. Depending on kubectl apply not actually making changes seems odd.

**Comment by davidhao3300** [comment]
We currently depend on RBAC to make the call on whether a patch is acceptable or not. We'd rather not implement our own permissioning filter if possible unless it's simple to do.

If we do move this logic to the control plane, I think it's still reasonable to have an effectively empty patch is accepted as OK by the server? The long-term change doesn't seem to conflict with solving this issue

**Comment by liggitt** [comment]
> I think it's still reasonable to have an effectively empty patch is accepted as OK by the server? 

Definitely not. Requests are authorized as a whole. The situation you have is a case where no change would be allowed from the user. Rejecting a patch attempt regardless of content is reasonable in that case.

**Comment by davidhao3300** [comment]
That make sense - would you suggest an alternative in the long run then? Either a method to generate a patch on the client-side (would require view perms of the in-cluster actual resource of course), or something else?

**Comment by davidhao3300** [comment]
my guess that this issue https://github.com/kubernetes/features/issues/555 refers to the long-term planned change, and https://github.com/kubernetes/features/issues/491 would be the diff command on the client-side?

**Comment by liggitt** [comment]
> would you suggest an alternative in the long run then? Either a method to generate a patch on the client-side (would require view perms of the in-cluster actual resource of course)

Definitely not this. Client side patch generation hasn't proven viable

> something else?

@lavalamp's suggestion to partition the resources you have a user apply to the ones they are intended to have permissions on makes the most sense.

**Comment by davidhao3300** [comment]
We have a general deployment job that can be requested by any particular user. The deployment job renders a bunch of templates we have, and will be a collection of what we consider unprivileged objects (ConfigMaps and Deployments), and privileged objects (Secrets, Ingresses, etc.). We then attempt to apply the objects. If any fail due to rbac permissions, we ask the user to contact a privileged user to run the deployment.

In most cases, figuring out some form of segregation (excluding permissioned resources from being applied for unprivileged resources) is fine, and I can see how that would be implemented. However, we do want to be able to tell users that they're attempting to patch a resource they don't have permissions to. This would require us to be able determine if there's some difference between what's expected and what's actually on the server.

**Comment by liggitt** [comment]
> I would guess we'd do exactly the same permission checks

Yes, a dry run patch/update would be authorized just like a non-dry-run would

**Comment by davidhao3300** [comment]
if the dry-run accurately states whether any actual changes would occur with a patch (reduces empty patches as suggested in this issue), that would work for our case

the deploy job starts with a superuser who impersonates the person triggering the job, so we would have the permissions to do a dry run and see if a diff is generated

**Comment by davidhao3300** [comment]
I see that there'll be ways to figure this out in the long-run, thanks for discussing. I'll change the PR description to not say that it fixes this issue then

**Comment by lavalamp** [comment]
Thanks for being understanding! :) :)

**Comment by davidhao3300** [comment]
this was addressed in https://github.com/kubernetes/kubernetes/pull/59284
