### ISSUE TITLE
Problem with Kube-apiserver after configuring token auth and ABAC

### ISSUE THREAD

**Issue by am-shahraki** [kubernetes/kubernetes#58808]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

I have changed kube-apiserver.yaml to configure  token auth and ABAC
 - --token-auth-file=/etc/kubernetes/pki/auth.csv
    - --authorization-policy-file=/etc/kubernetes/pki/authp.json

I put the files in pki which is mount normally. Now the kube-apiserver cannot run. the log is 
...
{"log":"I0125 11:16:03.334976       1 logs.go:41] http: TLS handshake error from 158.39.163.7:45774: remote error: tls: bad certificate\n","stream":"stderr","time":"2018-01-25T11:16:03.335200075Z"}
{"log":"I0125 11:16:03.732438       1 controller.go:90] Shutting down OpenAPI AggregationController\n","stream":"stderr","time":"2018-01-25T11:16:03.732661834Z"}
{"log":"I0125 11:16:03.732455       1 crd_finalizer.go:254] Shutting down CRDFinalizer\n","stream":"stderr","time":"2018-01-25T11:16:03.732726088Z"}
{"log":"I0125 11:16:03.732442       1 autoregister_controller.go:160] Shutting down autoregister controller\n","stream":"stderr","time":"2018-01-25T11:16:03.73274292Z"}
{"log":"I0125 11:16:03.732479       1 customresource_discovery_controller.go:163] Shutting down DiscoveryController\n","stream":"stderr","time":"2018-01-25T11:16:03.732755142Z"}
{"log":"I0125 11:16:03.732493       1 crdregistration_controller.go:139] Shutting down crd-autoregister controller\n","stream":"stderr","time":"2018-01-25T11:16:03.732768202Z"}
{"log":"I0125 11:16:03.732446       1 naming_controller.go:285] Shutting down NamingConditionController\n","stream":"stderr","time":"2018-01-25T11:16:03.732779587Z"}
{"log":"I0125 11:16:03.732507       1 available_controller.go:274] Shutting down AvailableConditionController\n","stream":"stderr","time":"2018-01-25T11:16:03.732810037Z"}
{"log":"I0125 11:16:03.732525       1 apiservice_controller.go:124] Shutting down APIServiceRegistrationController\n","stream":"stderr","time":"2018-01-25T11:16:03.732821561Z"}
{"log":"I0125 11:16:03.732571       1 serve.go:129] Stopped listening on [::]:6443\n","stream":"stderr","time":"2018-01-25T11:16:03.73283106Z"}
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}- Cloud provider or hardware configuration:
bare-metal
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fejta** [comment]
@kubernetes/sig-auth-misc

**Comment by ericchiang** [comment]
The flags mentioned don't control TLS options:

```
--token-auth-file=/etc/kubernetes/pki/auth.csv
--authorization-policy-file=/etc/kubernetes/pki/authp.json
```

They allow users to authenticate with bearer tokens, and control API authorization.

https://kubernetes.io/docs/admin/authentication/#static-token-file
https://kubernetes.io/docs/admin/authorization/

The error implies something about a misconfigured TLS certificate.

```
{"log":"I0125 11:16:03.334976 1 logs.go:41] http: TLS handshake error from 158.39.163.7:45774: remote error: tls: bad certificate\n","stream":"stderr","time":"2018-01-25T11:16:03.335200075Z"}
```

I don't think there's enough information provided to indicate those features are buggy in some way. This question may be better for one of our help forms:

https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/#help-my-question-isnt-covered--i-need-help-now

/close
