### ISSUE TITLE
kube-scheduler doesn not have --write-config-to option

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/kubernetes#58805]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We face
```
WARNING: all flags than --config are deprecated. Please begin using a config file ASAP.
```
But there is no way to generate default config file

**How to reproduce it (as minimally and precisely as possible)**:
```
kube-scheduler --write-config-to ./scheduler.conf
Error: unknown flag: --write-config-to
```

**Environment**:
- Kubernetes version 1.9.2

**Comment by stewart-yu** [comment]
I'll take a look it

**Comment by tiukhtinvladimir** [comment]
Hi, same issue with controller-manager

**Comment by corest** [comment]
Any updates here? `1.9.2`, `1.9.3` and `1.10.beta.1` don't have this flag. Is it even will be supported?

**Comment by cjyar** [comment]
@k82cn Because the documentation on the config file format is either nonexistent or difficult to find. If the program itself can generate a template, that fulfills (most of) the need for documentation of the format.

**Comment by wanghaoran1988** [comment]
+1 for this, from my expirence, add an option to write the default config is really helpful.

**Comment by theonlydoo** [comment]
also in 1.10

**Comment by theonlydoo** [comment]
nb there is a pseudo template here :

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server_test.go#L174-L213

**Comment by Quentin-M** [comment]
Deprecating all flags, prompting folks to use config files in advance is great, except when there's no documentation nor example anywhere. That means that we can't actually migrate to the new settings, and I can't seem to find clear alpha/beta/stable status for the new config file spec, nor timeline for the removal. 

It is also pretty confusing that the scheduler expects us to use a config file, but the controller-manager does not?

**Comment by resouer** [comment]
@Quentin-M This issue indeed applies to kube-controller-manager. And there should already had deprecation policy.
