### ISSUE TITLE
Feature request: Support renaming PVC

### ISSUE THREAD

**Issue by gmile** [kubernetes/kubernetes#58811]
/kind feature

**What happened**:
After deleting a StatefulSet, it's not possible to rename a dynamically created PVC.

**What you expected to happen**:
After deleting a StatefulSet, it is possible to rename a dynamically created PVC.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a StatefulSet with one replica,
2. Make some state, e.g. write some data to disk, from within the replica,
3. Try to rename the PVC... oops, it's not possible (at least respective instructions are nowhere to be found)

**Anything else we need to know?**:

I was running Elasticsearch STS with 2 replicas. Suddenly one of the replicas hit its PVC disk quota limit. In order to increase the disk, I want to create a bigger disk and move the data there. I'm following this backup/restore procedure:

1. scale down my StatefulSet (comprising of 2 replicas),
2. create two new bigger PVCs,
3. for every existing smaller PVC:
    1. create a job,
    2. attach one small PVC and one big PVC to it,
    3. move `/data` folder from smaller PVC to bigger PVC,
    4. delete smaller PVC,
    5. rename bigger PVC to the name of the smaller PVC.
4. scale up my StatefulSet.

Without the ability to rename PVC, I either:
1. wait for GKE to enable Kubernetes 1.9, migrate my production cluster to it, and resize the PVC – all thanks to a respective new admission plugin https://github.com/kubernetes/kubernetes/pull/55815,
2. workaround, by copying the `/data` folder twice, e.g. split item 5 above into two, e.g.:
    1. delete smaller PVC,
    2. create another big PVC with the same name as smaller PVC,
    3. move data from big temp PVC to this new bigger PVC with correct name
    4. delete big temp PVC.

It would be MUCH easier if I could just rename PVC.

**Environment**:
- Kubernetes version (use `kubectl version`):

    ```
    kubectl version
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:11:08Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-gke.0", GitCommit:"ee9a97661f14ee0b1ca31d6edd30480c89347c79", GitTreeState:"clean", BuildDate:"2018-01-05T03:36:42Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 

    ```
    BUILD_ID=10032.71.0
    NAME="Container-Optimized OS"
    KERNEL_COMMIT_ID=c4c6234ae4f384ce00819c41b48ca8f6f1fa3ba8
    GOOGLE_CRASH_ID=Lakitu
    VERSION_ID=63
    BUG_REPORT_URL=https://crbug.com/new
    PRETTY_NAME="Container-Optimized OS from Google"
    VERSION=63
    GOOGLE_METRICS_PRODUCT_ID=26
    HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
    ID=cos
    ```

- Kernel (e.g. `uname -a`):

    ```
    Linux gke-preprod-api-application-workloads-edc114ec-bbw9 4.4.86+ #1 SMP Thu Dec 7 20:11:11 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
    ```

- Install tools: -
- Others: -

**Comment by liggitt** [comment]
Names are a fundamental part of the way the API identifies objects. Renaming an object would chang its identity, and is not supported. Is there an alternate way this use case could be addressed other than renaming?

**Comment by gmile** [comment]
@liggitt technically yes, it is possible to get around without renaming. As I mentioned above there are two options:

1. wait for GKE to enable Kubernetes 1.9, when PVC resizing is available https://github.com/kubernetes/kubernetes/pull/55815,
2. workaround, by copying the `/data` folder twice, e.g. split item 5 above into two, e.g.:
    1. delete smaller PVC,
    2. create another big PVC with the same name as smaller PVC,
    3. move data from big temp PVC to this new bigger PVC with correct name
    4. delete big temp PVC.

**Comment by gmile** [comment]
Since renaming is fundamental part and is not supported is any way, I guess I'm going to close this one.

Although renaming would be more convenient (and resizing would be even more convenient), I was able to solve my problem without renaming by double-copying the data.
