### ISSUE TITLE
Pods recreated without waiting for termination with strategy.type=Recreate

### ISSUE THREAD

**Issue by tomas-c** [kubernetes/kubernetes#58814]
/kind bug
/sig scheduling
/sig autoscaling

**What happened**:

Created a deployment with strategy.type=Recreate. Deleted a pod created by that deployment. Ran kubectl get pods. See the old pod being terminated and a new one being created.

This is an issue for pods that should only have one running instance.

Also same problem when using RollingUpdate strategy with maxSurge=0 and maxUnavailable=1.

**What you expected to happen**:

Expected for Kubernetes to wait for the old pod to be completely terminated.

**How to reproduce it (as minimally and precisely as possible)**:

Should be easy to reproduce with a pod that takes a while to terminate.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11-gke.1", GitCommit:"3500f53730c1fea7b57901977df165c3eb317bce", GitTreeState:"clean", BuildDate:"2017-12-08T18:05:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GCP

**Comment by tomas-c** [comment]
@kubernetes/sig-scheduling-bug
@kubernetes/sig-autoscaling-bug

**Comment by wanghaoran1988** [comment]
@tomas-c What do you mean "completely terminated" ? pods being removed ?

**Comment by tomas-c** [comment]
Hey @wanghaoran1988 

I meant the process running in the container being stopped/killed and the pod not being in the state "Terminating".

**Comment by kargakis** [comment]
This is not an issue during an upgrade since the controller waits for the old version to terminate before spinning up the new. Unfortunately, it is an issue with every other delete (user deletes, node drains). @kubernetes/sig-apps-feature-requests need to make a call on what should be the desired behavior in Recreate Deployments.

**Comment by tnozicka** [comment]
I understand Recreate strategy as the way/policy to create pods while changing from one RS to another on upgrade and it already waits there for no old pods to be running. If you want that guarantee between pods with the same revision, StatefulSet does that.

**Comment by kargakis** [comment]
Yeah, I agree with @tnozicka. We should at least document this behavior.

**Comment by janetkuo** [comment]
> **What you expected to happen:**
> Expected for Kubernetes to wait for the old pod to be completely terminated.

Old pod means the "old version" of Deployment pod. In your case, both the terminating and the recreated pods are "new version" of Deployment pods (new pods).
