### ISSUE TITLE
Cannot create a service that selects labels with prefix

### ISSUE THREAD

**Issue by poweld** [kubernetes/kubernetes#58821]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Attempted to create a service with a pod label selector for the label named `statefulset.kubernetes.io/pod-name`. Received the following error in response: `The Service "my-service" is invalid: spec.selector: Invalid value: "statefulset.kubernetes.io/pod-name": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

**What you expected to happen**:
The service would be created and select the pod(s) with the specified name

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubectl create -f test.yaml` where `test.yaml` contains the following:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - name: my-listener
    port: 8080
  selector:
    name: statefulset.kubernetes.io/pod-name
    value: my-statefulset-0
  type: ClusterIP
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):
`Linux poweld-laptop 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
- Others:

**Comment by MrHohn** [comment]
@poweld You put a `/` in the label value, which is not allowed. Do you want something like:
```
  selector:
    statefulset.kubernetes.io/pod-name: my-statefulset-0
```

**Comment by poweld** [comment]
Thank you @MrHohn  I'm not sure what I was thinking.
