### ISSUE TITLE
ElasticSearch e2e test is red.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#58837]
https://k8s-testgrid.appspot.com/google-gce#gci-gce-es-logging becomes completely red after https://github.com/kubernetes/kubernetes/pull/58525 is merged.

/cc @monotek @coffeepac

@kubernetes/sig-instrumentation-misc

**Comment by monotek** [comment]
Pretty sure this is because the needed 2.0.4 image is not yet available in gcr.io. See: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch

**Comment by StevenACoffman** [comment]
What makes a new image be generated? Or is it a manual process?

**Comment by coffeepac** [comment]
Manual process.

@piosz or @crassirostris can one of you two build and push the new 2.0.4 version?

**Comment by piosz** [comment]
apologies for the delay, @crassirostris is OOO, will be back on Monday

@crassirostris could you please build the image once you are back?

**Comment by StevenACoffman** [comment]
No worries. @piosz for the future, could this be automated, or should there be other people inside google notified? Any one person should be able to take vacations without holding up the show.

**Comment by crassirostris** [comment]
Will build/push it once https://github.com/kubernetes/kubernetes/pull/59665 is merged

**Comment by StevenACoffman** [comment]
@crassirostris Thanks!  #59665 is merged

**Comment by crassirostris** [comment]
Should be fixed soon

**Comment by monotek** [comment]
Image is available: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch@sha256:b8c94527b489fb61d3d81ce5ad7f3ddbb7be71e9620a3a36e2bede2f2e487d73/details/info

**Comment by crassirostris** [comment]
The last run is green: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-es-logging/21600

Thanks everyone for bringing this up
