### ISSUE TITLE
"tiller-deploy" pod could not become ready when there was a time jump from a future time to right time after the nodes reboot

### ISSUE THREAD

**Issue by clivez** [kubernetes/kubernetes#58853]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Background:
There is something wrong with the time in one of our systems, when reboot, the time on the nodes jumps to a future time, and after a few minutes, the chrony will change the time to right one.

At the beginning, we faced a node notReady problem, we restarted kubelet service after time changing back, the node bcame ready then.
Currently, the problem is, after that, the "tiller-deploy" pod could not become ready for a long time.

[root@bcmtrattlesnake-worker-01 ~]$ kubectl get pods -o wide -n kube-system
NAME                                                 READY     STATUS    RESTARTS   AGE       IP              NODE
default-http-backend-3623835380-ndl37                1/1       Running   3          1d        192.168.1.99    bcmtrattlesnake-worker-01
heapster-1268559602-19sf1                            1/1       Running   3          1d        192.168.1.98    bcmtrattlesnake-worker-01
kube-apiserver-bcmtrattlesnake-control-01            1/1       Running   4          1h        172.16.2.127    bcmtrattlesnake-control-01
kube-apiserver-bcmtrattlesnake-control-02            1/1       Running   4          46m       172.16.2.128    bcmtrattlesnake-control-02
kube-apiserver-bcmtrattlesnake-worker-01             1/1       Running   4          1d        172.16.2.129    bcmtrattlesnake-worker-01
kube-controller-manager-bcmtrattlesnake-control-01   1/1       Running   4          1h        172.16.2.127    bcmtrattlesnake-control-01
kube-controller-manager-bcmtrattlesnake-control-02   1/1       Running   5          46m       172.16.2.128    bcmtrattlesnake-control-02
kube-controller-manager-bcmtrattlesnake-worker-01    1/1       Running   4          1d        172.16.2.129    bcmtrattlesnake-worker-01
kube-dns-635741074-7lrj4                             3/3       Running   9          1d        192.168.1.101   bcmtrattlesnake-worker-01
kube-dns-635741074-cn4b1                             3/3       Running   0          47m       192.168.1.145   bcmtrattlesnake-control-01
kube-dns-635741074-t24vv                             3/3       Running   12         1d        192.168.1.96    bcmtrattlesnake-worker-01
kube-proxy-bcmtrattlesnake-control-01                1/1       Running   4          1h        172.16.2.127    bcmtrattlesnake-control-01
kube-proxy-bcmtrattlesnake-control-02                1/1       Running   4          46m       172.16.2.128    bcmtrattlesnake-control-02
kube-proxy-bcmtrattlesnake-worker-01                 1/1       Running   4          1d        172.16.2.129    bcmtrattlesnake-worker-01
kube-proxy-bcmtrattlesnake-worker-02                 1/1       Running   4          1d        172.16.2.130    bcmtrattlesnake-worker-02
kube-scheduler-bcmtrattlesnake-control-01            1/1       Running   4          1h        172.16.2.127    bcmtrattlesnake-control-01
kube-scheduler-bcmtrattlesnake-control-02            1/1       Running   5          45m       172.16.2.128    bcmtrattlesnake-control-02
kube-scheduler-bcmtrattlesnake-worker-01             1/1       Running   4          1d        172.16.2.129    bcmtrattlesnake-worker-01
kubernetes-dashboard-842212871-fkfzw                 1/1       Running   3          1d        192.168.1.100   bcmtrattlesnake-worker-01
tiller-deploy-1339847260-pk8hb                       0/1       Running   3          23h       192.168.1.3     bcmtrattlesnake-worker-02
[root@bcmtrattlesnake-worker-01 ~]$ 

[root@bcmtrattlesnake-worker-02 ~]$ kubectl get pod tiller-deploy-1339847260-pk8hb -o yaml -n kube-system
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-1339847260","uid":"b2d1992f-fffb-11e7-93d1-005056ad9d0f","apiVersion":"extensions","resourceVersion":"33537"}}
  creationTimestamp: 2018-01-23T08:58:15Z
  generateName: tiller-deploy-1339847260-
  labels:
    app: helm
    name: tiller
    pod-template-hash: "1339847260"
  name: tiller-deploy-1339847260-pk8hb
  namespace: kube-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tiller-deploy-1339847260
    uid: b2d1992f-fffb-11e7-93d1-005056ad9d0f
  resourceVersion: "341822"
  selfLink: /api/v1/namespaces/kube-system/pods/tiller-deploy-1339847260-pk8hb
  uid: 8c64842e-001b-11e8-a6df-005056ad9d0f
spec:
  containers:
  - env:
    - name: TILLER_NAMESPACE
      value: kube-system
    image: bcmt-registry:5000/gcr.io/kubernetes-helm/tiller:v2.6.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /liveness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: tiller
    ports:
    - containerPort: 44134
      name: tiller
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tgr51
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: bcmtrattlesnake-worker-02
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-tgr51
    secret:
      defaultMode: 420
      secretName: default-token-tgr51
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-01-23T08:58:15Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-01-24T07:38:16Z
    message: 'containers with unready status: [tiller]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-01-23T08:58:15Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e59395d228a4fd6baafe16f3e95b6b3183acbc0795f5a944760838e459e5b016
    image: bcmt-registry:5000/gcr.io/kubernetes-helm/tiller:v2.6.0
    imageID: docker-pullable://bcmt-registry:5000/gcr.io/kubernetes-helm/tiller@sha256:0b05e5c51e426f3ae9ef2beb990a10353e5e4c76d0be4a32d87589e459c605ce
    lastState:
      terminated:
        containerID: docker://58be98d8ac2a4140eb500a6906375d0fe3619b862b784479b56458f9351c8561
        exitCode: 255
        finishedAt: 2018-01-24T09:32:01Z
        reason: Error
        startedAt: 2018-01-24T07:15:01Z
    name: tiller
    ready: false
    restartCount: 3
    state:
      running:
        **startedAt: 2018-01-24T09:35:47Z**
  hostIP: 172.16.2.130
  phase: Running
  podIP: 192.168.1.3
  qosClass: BestEffort
  startTime: 2018-01-23T08:58:15Z

The node worker-02 actually rebooted at 7:3x, its time was changed to 9:3x, the tiller pod was reset at 9:35:47. And time of worker-02 was changed back to 7:xx a few minutes later.
The Ready status of this pod kept being false, but if we used “curl 192.168.1.3:44135/readiness” to check manually, it could return successfully. Seems k8s stopped to check the Ready status of this pod after the time change.

When I changed the time to a value ahead of 9:35:47
[root@bcmtrattlesnake-worker-02 ~]$ date
Wed Jan 24 08:33:53 UTC 2018
[root@bcmtrattlesnake-worker-02 ~]$ date -s 09:37:00
Wed Jan 24 09:37:00 UTC 2018
 
The “tiller” pod recovered immediately, and the result from  “kubectl get pod tiller-deploy-1339847260-pk8hb -o yaml -n kube-system” also shows that k8s did a readiness detection then.
[root@bcmtrattlesnake-worker-01 ~]$ kubectl get pods -n kube-system tiller-deploy-1339847260-pk8hb -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-1339847260","uid":"b2d1992f-fffb-11e7-93d1-005056ad9d0f","apiVersion":"extensions","resourceVersion":"33537"}}
  creationTimestamp: 2018-01-23T08:58:15Z
  generateName: tiller-deploy-1339847260-
  labels:
    app: helm
    name: tiller
    pod-template-hash: "1339847260"
  name: tiller-deploy-1339847260-pk8hb
  namespace: kube-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tiller-deploy-1339847260
    uid: b2d1992f-fffb-11e7-93d1-005056ad9d0f
  resourceVersion: "355295"
  selfLink: /api/v1/namespaces/kube-system/pods/tiller-deploy-1339847260-pk8hb
  uid: 8c64842e-001b-11e8-a6df-005056ad9d0f
spec:
  containers:
  - env:
    - name: TILLER_NAMESPACE
      value: kube-system
    image: bcmt-registry:5000/gcr.io/kubernetes-helm/tiller:v2.6.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /liveness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: tiller
    ports:
    - containerPort: 44134
      name: tiller
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 44135
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tgr51
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: bcmtrattlesnake-worker-02
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-tgr51
    secret:
      defaultMode: 420
      secretName: default-token-tgr51
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-01-23T08:58:15Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    **lastTransitionTime: 2018-01-24T09:37:03Z**
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-01-23T08:58:15Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e59395d228a4fd6baafe16f3e95b6b3183acbc0795f5a944760838e459e5b016
    image: bcmt-registry:5000/gcr.io/kubernetes-helm/tiller:v2.6.0
    imageID: docker-pullable://bcmt-registry:5000/gcr.io/kubernetes-helm/tiller@sha256:0b05e5c51e426f3ae9ef2beb990a10353e5e4c76d0be4a32d87589e459c605ce
    lastState:
      terminated:
        containerID: docker://58be98d8ac2a4140eb500a6906375d0fe3619b862b784479b56458f9351c8561
        exitCode: 255
        finishedAt: 2018-01-24T09:32:01Z
        reason: Error
        startedAt: 2018-01-24T07:15:01Z
    name: tiller
    ready: true
    restartCount: 3
    state:
      running:
        **startedAt: 2018-01-24T09:35:47Z**
  hostIP: 172.16.2.130
  phase: Running
  podIP: 192.168.1.3
  qosClass: BestEffort
  startTime: 2018-01-23T08:58:15Z

So, it seems k8s has some kind of defect in readiness detection in this time jump case. 

**What you expected to happen**:
k8s can check the pod Ready status correctly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by clivez** [comment]
Could it be the same reason with https://github.com/kubernetes/kubernetes/issues/54130 ?

**Comment by yliaog** [comment]
due to the time change (from future to back), kubelet won't update pod status.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L297

could you just kill the pod, and have it recreated?

/sig node
/remove-sig api-machinery

**Comment by clivez** [comment]
@yliaog thank you very much for your reply. The problem could be solved by killing the pod, the pod would be recreated immediately and become ready.
But my concern is that, as you know, the time change is common to some extent in production environment, I think it is not a very good method to let kubelet just stop to update pod status, maybe you can add some fix to this time change situation, for example, when LastTransitionTime is greater than current time, set LastTransitionTime equal to current time and so on. Please have a consideration, thank you again.

**Comment by yliaog** [comment]
or maybe upgrade to k8s 1.9.x built with go 1.9 with monotonic time (https://golang.org/doc/go1.9#monotonic-time)

I'll leave it for people from sig-node to weigh in

**Comment by clivez** [comment]
Hi @yliaog , If this kind of problem is solved in k8s 1.9.x, it will also be a acceptable choice.
Could you please help have a confirm whether this kind of problem is fixed in k8s 1.9.x built with go 1.9 with monotonic time? Thank you.

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/issues/54130#issuecomment-338912933

as tested by xialonglee

**Comment by clivez** [comment]
@yliaog , ok, that is a good news, k8s in our environment will be upgraded to 1.9 in the near future.
I think this issue could be closed now, thank you!
