### ISSUE TITLE
pull-kubernetes-e2e-gke failed consistently due to "cluster_api_version not found"

### ISSUE THREAD

**Issue by jingax10** [kubernetes/kubernetes#58886]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

pull-kubernetes-e2e-gke failed consistently

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gke

By looking into logs and checking the corresponding project k8s-jkns-pr-gci-gke on GCP, no k8s cluster is created.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

It runs automatically for new PRs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MrHohn** [comment]
Job is passing now.
/close
