### ISSUE TITLE
k8s.io/kubernetes/test/integration/scheduler TestAllocatable flaking

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#58881]
The aformentioned test case has been flaking for a while with following error:

```
/usr/local/go/src/testing/testing.go:1145 +0xf9
/usr/local/go/src/time/sleep.go:170 +0x44
/usr/local/go/src/testing/testing.go:790 +0x2fc
/usr/local/go/src/testing/testing.go:1004 +0x64
/usr/local/go/src/testing/testing.go:746 +0xd0
/usr/local/go/src/testing/testing.go:1002 +0x2d8
/usr/local/go/src/testing/testing.go:921 +0x111
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/main_test.go:26 +0x2a
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/framework/etcd.go:103 +0x2c
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/main_test.go:26 +0x41
k8s.io/kubernetes/test/integration/scheduler/_test/_testmain.go:76 +0x156
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x9f
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x203
/usr/local/go/src/runtime/netpoll.go:173 +0x57
/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
/usr/local/go/src/net/fd_unix.go:202 +0x52
/usr/local/go/src/net/net.go:176 +0x6d
/usr/local/go/src/bufio/bufio.go:213 +0x30b
/usr/local/go/src/io/io.go:309 +0x86
/usr/local/go/src/io/io.go:327 +0x58
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/transport/http2_client.go:1118 +0xbe
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/transport/http2_client.go:266 +0xc80
/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
```

**Comment by liggitt** [comment]
cc @kubernetes/sig-scheduling-test-failures

**Comment by liggitt** [comment]
causing many many failures:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77059/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77060/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77071/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77079/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77084/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77093/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77095/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/77096/

**Comment by liggitt** [comment]
looks like a spike of flakes around scheduler in the past day or so:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=pull-kubernetes-unit&test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fscheduler

**Comment by liggitt** [comment]
possibly corresponding with merge of https://github.com/kubernetes/kubernetes/pull/58555

**Comment by bsalamat** [comment]
#58555 is an improvement to an alpha feature which is disabled by default. Anyway, I will take a look.

**Comment by resouer** [comment]
I am re-running it locally. equiv class is enabled for scheduler integration test if I remembered correctly.

**Comment by bsalamat** [comment]
> Equiv class is enabled for most scheduler integration test (e.g. scheduler_test.go) if I remembered correctly.

Ah, that's right. Actually, Jonathan initially faced some flakiness during the development of the PR, but later on he thought those were addressed, but it doesn't seem so. He started his paternity leave. I guess at this point, we should revert his PR until we fix the issue.

**Comment by liggitt** [comment]
The revert cleaned up the failures
/close
