### ISSUE TITLE
Stricter server-side validation of JSON entities

### ISSUE THREAD

**Issue by simon3z** [kubernetes/kubernetes#5889]
In issue #5850 we mentioned that we may consider a stricter validation of the JSON entities (explicitly failing on unknown fields instead of ignoring them).

**Comment by simon3z** [comment]
Sorry @brendandburns I just noticed that you closed #5850, do you think that this issue should be closed as well? In https://github.com/GoogleCloudPlatform/kubernetes/issues/5850#issuecomment-85681865 @bgrant0607 mentioned:

> We should probably also do better server-side validation, but need to think through version-skew cases.

so I thought that it was worth to keep track of the possibility for a better server-side validation.

**Comment by bgrant0607** [comment]
I think it's a reasonable request, though not something we plan to implement soon.

**Comment by bgrant0607** [comment]
See also discussion in #4855.

**Comment by bgrant0607** [comment]
In #19501, it was proposed to make server-side validation optional.

**Comment by bgrant0607** [comment]
See also #39434

**Comment by bgrant0607** [comment]
cc @mbohlool

**Comment by rikatz** [comment]
@bgrant0607 @liggitt I guess this one can be closed, right? AFAIK we already have strict validation on server side for unknown fields

**Comment by liggitt** [comment]
> AFAIK we already have strict validation on server side for unknown fields

no, unknown fields get dropped by the server

**Comment by kevindelgado** [comment]
Fixed by #105916

**Comment by liggitt** [comment]
tracked in feature https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2885-server-side-unknown-field-validation

alpha in 1.23, targeting beta in 1.24
