### ISSUE TITLE
Move node-perf-dash to a new home

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#58891]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup
@kubernetes/sig-node-proposals 

First suggested in https://github.com/kubernetes/contrib/issues/762
Reminded by @foxish

TODO:
- [ ] Find a new home.
- [ ] Move the directory.
- [ ] Rename packages.

**Comment by mtaufen** [comment]
It probably fits in a dedicated repo.
