### ISSUE TITLE
Bug: k get nodes on AKS with Service Catalog returns nodes after 5 mins

### ISSUE THREAD

**Issue by sauryadas** [kubernetes/kubernetes#58893]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
kind bug
> /kind feature

**What happened**:
Service Catalog in Azure Container Service (AKS) cluster
$ kubectl get nodes 
 returns nodes after 5 mins;

**What you expected to happen**:
$ kubectl get nodes 
should return almost instantaneously 

**How to reproduce it (as minimally and precisely as possible)**:
Install Service Catalog on a AKS cluster 

**Anything else we need to know?**:

Logs
kubectl get nodes --v=10
I0126 23:18:03.092245     179 loader.go:357] Config loaded from file /home/ahmed/.kube/config
I0126 23:18:03.094725     179 cached_discovery.go:117] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/servergroups.json
I0126 23:18:03.095735     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/apiregistration.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.096621     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/extensions/v1beta1/serverresources.json
I0126 23:18:03.097567     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/apps/v1beta1/serverresources.json
I0126 23:18:03.098436     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/authentication.k8s.io/v1/serverresources.json
I0126 23:18:03.099231     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/authentication.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.099910     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/authorization.k8s.io/v1/serverresources.json
I0126 23:18:03.100329     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/authorization.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.100579     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/autoscaling/v1/serverresources.json
I0126 23:18:03.100802     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/batch/v1/serverresources.json
I0126 23:18:03.101106     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/certificates.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.101186     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/networking.k8s.io/v1/serverresources.json
I0126 23:18:03.101396     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/policy/v1beta1/serverresources.json
I0126 23:18:03.101776     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/rbac.authorization.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.101898     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I0126 23:18:03.102169     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/settings.k8s.io/v1alpha1/serverresources.json
I0126 23:18:03.102245     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/storage.k8s.io/v1/serverresources.json
I0126 23:18:03.104151     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/storage.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.104233     179 cached_discovery.go:70] returning cached discovery info from /home/ahmed/.kube/cache/discovery/aks_eus_aks_eus_rg_90ab37_0394e135.hcp.eastus.azmk8s.io_443/apiextensions.k8s.io/v1beta1/serverresources.json
I0126 23:18:03.104399     179 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.1 (linux/amd64) kubernetes/3a1c944" -H "Authorization: Bearer <bearer-token>" https://<api-server>.hcp.eastus.azmk8s.io:443/apis/servicecatalog.k8s.io/v1beta1

23:18:03.104399     179 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.1 (linux/amd64) kubernetes/3a1c944" -H "Authorization: Bearer <bearer-token>" https://<api-server>.hcp.eastus.azmk8s.io:443/apis/servicecatalog.k8s.io/v1beta1
I0126 23:18:33.790502     179 round_trippers.go:436] GET https://<api-server>.hcp.eastus.azmk8s.io:443/apis/servicecatalog.k8s.io/v1beta1 503 Service Unavailable in 30686 milliseconds
I0126 23:18:33.790527     179 round_trippers.go:442] Response Headers:
I0126 23:18:33.790534     179 round_trippers.go:445]     Content-Type: text/plain; charset=utf-8
I0126 23:18:33.790541     179 round_trippers.go:445]     Content-Length: 124
I0126 23:18:33.790548     179 round_trippers.go:445]     Date: Fri, 26 Jan 2018 23:18:33 GMT
I0126 23:18:33.806299     179 request.go:873] Response Body: Error: 'dial tcp 10.0.17.253:443: i/o timeout'
Trying to reach: 'https://10.0.17.253:443/apis/servicecatalog.k8s.io/v1beta1'
I0126 23:18:33.890206     179 request.go:1075] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'Error: 'dial tcp 10.0.17.253:443: i/o timeout'
**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.7
- Cloud provider or hardware configuration:
Azure 
- OS (e.g. from /etc/os-release):
Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
Non responsive add on api servers can cause discovery requests to hang. In 1.9, the apiserver is more proactive at removing such API servers from discovery

**Comment by fejta** [comment]
@kubernetes/sig-azure-misc

**Comment by errordeveloper** [comment]
Based on @liggitt's comment, it sounds like testing on 1.9 is a must, also I'm tempted to close as this should probably belong to https://github.com/kubernetes-incubator/service-catalog.
