### ISSUE TITLE
TestTaintNodeByCondition is flaking

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#58905]
/kind bug
/sig scheduling
/sig node
/sig testing

Example failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58141/pull-kubernetes-unit/77112
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58890/pull-kubernetes-unit/77121
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58890/pull-kubernetes-unit/77139

It's one of the top failing unit tests: https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-unit

/cc @kubernetes/sig-scheduling-test-failures

**Comment by bsalamat** [comment]
Looks like a few scheduler integration tests are flaky. There was another report earlier: #58881.
We are [reverting a suspect PR](https://github.com/kubernetes/kubernetes/pull/58903) until we find a fix.

**Comment by liggitt** [comment]
The revert cleaned up the failures
/close
