### ISSUE TITLE
kubeadm join and error [discovery] Failed to request cluster info, will try again: [Get https://10.0.0.10:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: x509: certificate is valid for 10.96.0.1, 10.0.2.15, not 10.0.0.10]

### ISSUE THREAD

**Issue by xpoveda** [kubernetes/kubernetes#58921]
Hi, I have solved the issue https://github.com/kubernetes/kubernetes/issues/58876 with the modification of IP in "kubeadm join". 

10.0.0.10 is the IP of master.

But now appears this another issue and I can't to add the node to cluster.

```
root@nodo2:~# kubeadm join --token 0f18b4.a5cf13ea12a0f971 10.0.0.10:6443 --discovery-token-ca-cert-hash sha256:79d41321a6bf165b24947d13a9315d8219c005f1faf958d47421a05245f7e763
[preflight] Running pre-flight checks.
        [WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.12.0-ce. Max validated version: 17.03
        [WARNING FileExisting-crictl]: crictl not found in system path
[discovery] Trying to connect to API Server "10.0.0.10:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.0.0.10:6443"
[discovery] Requesting info from "https://10.0.0.10:6443" again to validate TLS against the pinned public key
[discovery] Failed to request cluster info, will try again: [Get https://10.0.0.10:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: x509: certificate is valid for 10.96.0.1, 10.0.2.15, not 10.0.0.10]
```

root@master:~# kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
master    Ready     master    18m       v1.9.2

Thanks so much!!

Xavier.

**Comment by CesarF** [comment]
Same issue,

**Comment by dixudx** [comment]
@xpoveda Seems you've got multiple nics for the node.

Please try `kubeadm init --apiserver-advertise-address=10.0.0.10`.

**Comment by errordeveloper** [comment]
@Vishal-Gaur have you set `--apiserver-advertise-address`? If yes, what value have you used? I believe you want to use `--apiserver-advertise-address=192.168.70.21`.

**Comment by timothysc** [comment]
This appears to be a configuration problem and is stale.  If you are still having issues please reopen in the https://github.com/kubernetes/kubeadm repo.

**Comment by paulsubrata55** [comment]
the system time should be same across all nodes. At least it solved certificate issue in my case.
