### ISSUE TITLE
We should pass listener to SecureServingOptions in test

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#58936]
As we have add `Listener` to `SecureServingOptions `, we should stop using function like `FindFreeLocalPort` in test cases and create a listener and pass to `SecureServingOptions `.

Because `FindFreeLocalPort` just create a tcp listener and get its port and close it. By this we can not make sure the port not be used between this listener close and the kube-apiserver listener start.

**Comment by liggitt** [comment]
Probably a good idea. There are a couple flakes floating around where an integration test gets an "already in use" error

**Comment by hzxuzhonghu** [comment]
Ok, I can fix it with our guys @hanxiaoshuai.

**Comment by hzxuzhonghu** [comment]
create #58937 to fix k/k integration test.

**Comment by hzxuzhonghu** [comment]
@hanxiaoshuai Please fix other cases in apiextentions-apiserver.

**Comment by hanxiaoshuai** [comment]
@hzxuzhonghu OK
