### ISSUE TITLE
question about --tls-ca-file parameter in apiserver

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#58952]
kubernetes 1.7.6
apiserver run parmeter container --tls-ca-file,but I find it's not use in code ?
why ???

**Comment by timchenxiaoyu** [comment]
@sig/api

**Comment by dims** [comment]
@timchenxiaoyu fixed by @deads2k in https://github.com/kubernetes/kubernetes/pull/58968

**Comment by timchenxiaoyu** [comment]
thks！
