### ISSUE TITLE
kubectl fails with ambiguous error when having duplicate entry in KUBECONFIG. 

### ISSUE THREAD

**Issue by MQasimSarfraz** [kubernetes/kubernetes#58957]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I was trying to update the kubeconfig using:
`$ kubectl config set-cluster local1`
but it kept on failing with:
`error: open /home/qasim.sarfraz/.kube/config.lock: file exists`
mainly due to duplicate entry in `KUBECONFIG`.
**What you expected to happen**:
`Cluster "local1" set.`
**How to reproduce it (as minimally and precisely as possible)**:
`$ export KUBECONFIG=/home/qasim.sarfraz/.kube/config:/home/qasim.sarfraz/.kube/config`
`$ kubectl config set-cluster local1`
`error: open /home/qasim.sarfraz/.kube/config.lock: file exists`
I can avoid the duplicate entry in the `KUBECONFIG` but it would be great if error msg is bit more explanatory or helpful.

**Comment by errordeveloper** [comment]
cc @smarterclayton

**Comment by Lion-Wei** [comment]
I can help fix this problem. : )

**Comment by Lion-Wei** [comment]
I think this pr already fixed this problem.  
#53880 @wackxu

**Comment by liggitt** [comment]
cc @cjcullen 
issues with kubeconfig lock files
