### ISSUE TITLE
how can i build images of hyperkube

### ISSUE THREAD

**Issue by jcxian** [kubernetes/kubernetes#58950]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:
I want to build hyperkube image. How can i get the Dockerfile of hyperkube
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I want to compile the mirrors in the mips64el architecture
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@jcxian - i usually use `hack/dev-push-hyperkube.sh` just comment out the `docker push` on the last line.

**Comment by jcxian** [comment]
@dims thank you
