### ISSUE TITLE
iptables-restore invalid option in kube-proxy

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes/kubernetes#58956]
/kind bug

/sig network

when start service kube-proxy
/var/log/message :
I0129 19:40:03.709536   21148 iptables.go:381] running iptables-restore [-w5 -T nat --noflush --counters]
E0129 19:40:03.712093   21148 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: invalid option -- '5'
iptables-restore: line 7 failed
)

And i run command
```bash
iptables-restore -w5
iptables-restore: invalid option -- '5'
```
then run comman with arg value split by space
```bash
iptables-restore -w 5

```
no error output.
I'm worried about the iptables-restore will not execute because of this error.
Please fix it, thanks a lot.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.9.2
- Cloud provider or hardware configuration:None
- OS (e.g. from /etc/os-release):CentOS Linux release 7.4.1708 (Core) 
- Kernel (e.g. `uname -a`):3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: binary install
- Others:

**Comment by tossmilestone** [comment]
The `-w5` option is not the cause, you may check out the other `iptables-restore` logs to confirm it.

**Comment by liuhuiping2013** [comment]
i have verify iptables-restore command in two popular OS:
## CentOS 7.4
```
$ iptables-restore -h         
Usage: iptables-restore [-b] [-c] [-v] [-V]  [-t] [-h] [-W usecs]  
           [ --binary ]
           [ --counters ]
           [ --verbose ]
           [ --version]
           [ --test ]
           [ --help ]
           [ --noflush ]
           [ --wait=<seconds>
           [ --wait-interval=<usecs>
           [ --table=<TABLE> ]
           [ --modprobe=<command>]
```

## Ubuntu 16.04
```
$ iptables-restore -h         
Usage: iptables-restore [-c] [-v] [-t] [-h]
	   [ --counters ]
	   [ --verbose ]
	   [ --test ]
	   [ --help ]
	   [ --noflush ]
	   [ --table=\<TABLE\> ]
           [ --modprobe=<command>]
```

none of _"-w"_ option was found, this must be a mistake.

@tossmilestone

**Comment by tossmilestone** [comment]
The `iptables-restore` with `-w` option requires min version `v1.4.20`, can you check the version? And the usage may not be complete with all options, you can run the command with `-w` to verify it.

**Comment by anomaly256** [comment]
The problem is that kube-proxy is passing "-w5" to iptables-restore, which is invalid.  It should be "-w 5".  I'm hitting this problem too

**Comment by andrewhowdencom** [comment]
From `journalctl`:

```
Feb 20 18:45:57 sw-20160601-01 localkube[31719]: E0220 18:45:57.956015   31719 proxier.go:1667] Failed to execute iptables-restore: exit status 1 (iptables-restore: invalid option -- '5'
Feb 20 18:45:57 sw-20160601-01 localkube[31719]: Try `iptables-restore -h' for more information.
Feb 20 18:45:57 sw-20160601-01 localkube[31719]: )
```

From `strace -p ${PID} -f -s 8096 -e process`:

```
[pid 13285] execve("/sbin/iptables-restore", ["iptables-restore", "-w5", "--noflush", "--counters"], 0xc42eaecc80 /* 6 vars */ <unfinished ...>
[pid  5492] <... clone resumed> child_stack=NULL, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 13285
[pid 13285] <... execve resumed> )      = 0
[pid  5492] waitid(P_PID, 13285,  <unfinished ...>
[pid 13285] arch_prctl(ARCH_SET_FS, 0x7f63b37e0440) = 0
[pid 13285] exit_group(1)               = ?
[pid 13285] +++ exited with 1 +++
```

To me, this seems pretty definitive -- that block is wrong.

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
$ minikube version
minikube version: v0.25.0
```

**Comment by andrewhowdencom** [comment]
cc @danwinship as the original author

**Comment by srhb** [comment]
Any news here? This breaks kube-proxy with iptables >= 1.6.2

**Comment by andrewhowdencom** [comment]
Honestly, I haven't looked at the PR yet. Please have a go if you can do it <3 I am at 105% utilisation currently, though I had planned to try and look at it in the next few hours if possible.

**Comment by danwinship** [comment]
> Any news here? This breaks kube-proxy with iptables >= 1.6.2

Doh. Sorry, I was thinking this just broke *detection* of the wait flag. I missed that this was breaking things entirely. I'll submit a new PR

**Comment by srhb** [comment]
Right! 1.6.2 started failing entirely on the missing spaces, whereas restore <= 1.6.1 just ignored the flag with a warning. :)

**Comment by danwinship** [comment]
@kumudt you have a different problem, not related to this one. If you run with log level 5 it should show you the data it's feeding to iptables-restore so that you can see what "line 7" as referenced in the error message is. That should help figure out what's actually happening.

**Comment by kumudt** [comment]
Thanks @danwinship will do that and get back to you.

**Comment by kumudt** [comment]
@danwinship I have done that and these are the logs that I find. Does any of this seems scary?
```
I0423 08:41:37.583715       1 iptables.go:381] running iptables-restore [-T nat --noflush --counters]
E0423 08:41:37.660146       1 proxier.go:584] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)
I0423 08:41:37.660186       1 iptables.go:321] running iptables-save [-t filter]
I0423 08:41:37.661963       1 iptables.go:381] running iptables-restore [-T filter --noflush --counters]
```

**Comment by andrewhowdencom** [comment]
I don't have experience in this area, but if you run somthing like:

```
# as root
strace -p ${KUBELET_PID} -s 8096 -f 2>&1 | tee /tmp/strace.log
```

you'll be able to see the kubelet spawn the iptables-restore process, and see the input that it writes to it. If it's writing directly to iptables-restore you might be able to limit the output by running:

```
strace -p ${KUBELET_PID} -e trace=process,write -s 8096 -f 2>&1 | tee /tmp/strace.log
```

This advise is *more generally* about debugging the invocation of processes, and is here only to provide some guide to debug this further. See `man strace` for details.

**Comment by danwinship** [comment]
@gjtempleton as above, if you run with (eg, `kube-proxy -v 5 ...`), it should log the data that its sending to iptables, so that you can see what the bad "line 7" is. (The comment above on April 23 does not include that information... I'm not sure if @kumudt failed to set the log level correctly, or if he just didn't include the relevant portion of the logs.) If setting the log level doesn't seem to be working, you could do what @andrewhowdencom suggested, or else replace /usr/sbin/iptables-restore with a wrapper script that dumps its stdin to a temporary file and then runs the real iptables-restore on it, so you can see the data afterward.

**Comment by gjtempleton** [comment]
@danwinship Thanks we've already got a test cluster running with `-v=5` now, we were just hoping to shortcut the debugging if the root cause had already been found. 

Will update once we get the relevant output and chase down the cause and open a fresh issue if it's unrelated.

**Comment by gjtempleton** [comment]
Took a bit longer than expected. Managed to grab the output and more confused than when I started.

We ended up adding debug lines for `-v=5` ( https://github.com/gjtempleton/kubernetes/commit/15072ee901b6d5e419153bace7e8cb481687538d#diff-97649d13432b01b4e7669d728a2e2e82 ) to get the data being passed to iptables-restore. However this looks sane to me.

```
Jun 20 14:55:30 hostname kube-proxy[12444]: E0620 14:55:30.678597   12444 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
Jun 20 14:55:30 hostname kube-proxy[12444]: )
Jun 20 14:55:30 hostname kube-proxy[12444]: I0620 14:55:30.678628   12444 proxier.go:793] Data passed to iptables: *nat
Jun 20 14:55:30 hostname kube-proxy[12444]: :KUBE-SERVICES - [0:0]
Jun 20 14:55:30 hostname kube-proxy[12444]: :KUBE-POSTROUTING - [0:0]
Jun 20 14:55:30 hostname kube-proxy[12444]: :KUBE-MARK-MASQ - [0:0]
Jun 20 14:55:30 hostname kube-proxy[12444]: -X KUBE-SERVICES
Jun 20 14:55:30 hostname kube-proxy[12444]: -X KUBE-POSTROUTING
Jun 20 14:55:30 hostname kube-proxy[12444]: -X KUBE-MARK-MASQ
Jun 20 14:55:30 hostname kube-proxy[12444]: COMMIT
```

Additionally, this seems like it would be useful debugging to have and mirrors debug lines already existing, is it worth me raising an MR to get this in?

**Comment by danwinship** [comment]
Oh, huh, that's in IPVS-specific code. And failing in a way that really doesn't seem to make much sense...

So actually, that code has been rewritten in 1.10 (#55606). The PR doesn't mention this problem (it just talks about simplifying the code), but I'm not sure it's worth trying to debug the old version of the code further. Someone should see if the problem still exists in 1.10. If not maybe the new code could be backported to 1.9.

But anyway, this is now definitely totally unrelated to this PR (which was about kubernetes passing bad command-line flags to iptables-restore in the iptables proxier, not about passing possibly bad stdin in the ipvs proxier) so if you want to pursue it further you should file a new bug.

**Comment by dawidmalina** [comment]
I have exactly same issue with kubernetes 1.11.1 and ipvs:
```
I0905 20:09:11.677674       1 iptables.go:323] running iptables-save [-t nat]
I0905 20:09:11.731479       1 iptables.go:383] running iptables-restore [-T nat --noflush --counters]
E0905 20:09:11.733419       1 proxier.go:423] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)
I0905 20:09:11.733681       1 iptables.go:323] running iptables-save [-t filter]
I0905 20:09:11.737057       1 iptables.go:383] running iptables-restore [-T filter --noflush --counters]
I0905 20:09:11.738971       1 server.go:448] Version: v1.11.1
```

The log is only visible during kube-proxy startup (only)!

But there is a one strange thing. I am pretty sure that I am using ipvs:
```
I0905 20:09:11.567087       1 server_others.go:183] Using ipvs Proxier.
I0905 20:09:11.646988       1 proxier.go:346] nodeIP: 10.10.0.12, isIPv6: false
I0905 20:09:11.647037       1 proxier.go:403] minSyncPeriod: 0s, syncPeriod: 30s, burstSyncs: 2
```
But based on the log message:
```
proxier.go:423] Failed to execute iptables-restore for nat:
```
the logs is somehow from iptables proxier: https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/proxy/iptables/proxier.go#L423

The ipvs proxier have similar output but different line: https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/proxy/ipvs/proxier.go#L1139

How come that iptables proxier is executed when ipvs is configured?

**Comment by danwinship** [comment]
> I have exactly same issue with kubernetes 1.11.1

OK, can you open a new bug then, as this bug was about `iptables-restore: invalid option -- '5'` not `iptables-restore: line 7 failed`. (Though, apparently, the failure can occur in both the iptables and ipvs code?)

> How come that iptables proxier is executed when ipvs is configured?

At startup, kube-proxy runs the cleanup code for all 3 proxies (userspace, iptables, ipvs), so that if you were previously running in a different mode, that gets cleaned up before it sets up the new mode.

**Comment by opsnull** [comment]
@danwinship  new issue #68447

**Comment by jamestutton** [comment]
For anyone finding this thread the below workaround may work for now with Centos at least:

Ok so as a work around I have done:

```
yum downgrade http://mirror.centos.org/centos/7.5.1804/os/x86_64/Packages/iptables-1.4.21-24.el7.x86_64.rpm
```

and adding iptables-* to the exclude in /etc/yum.conf

```
[main]
.....
....
exclude=iptables-*
```

This is NOT a good fix as it rolling iptables back 4 releases but until kube-proxy is fixed this may be the only viable option for some

**Comment by danwinship** [comment]
> This is now potentially a larger issue with release of centos 7.6 and RHEL 7.6

If you're running OpenShift 3.7, you need to get [the latest release, 3.7.72](https://access.redhat.com/errata/RHSA-2018:2906). If you are running any other up-to-date version of kubernetes or OpenShift, you should not be seeing this bug.

**Comment by xjj001** [comment]
> 对于找到此主题的任何人，以下解决方法至少可以使用Centos：
> 
> 好的，所以我做了一个工作：
> 
> ```
> yum downgrade http://mirror.centos.org/centos/7.5.1804/updates/x86_64/Packages/iptables-1.4.21-24.1.el7_5.x86_64.rpm
> ```
> 并将iptables- *添加到/etc/yum.conf中的exclude中
> 
> ```
> [main]
> .....
> ....
> exclude=iptables-*
> ```
> 一些不是一个很好的解决方案，因为它滚动iptables返回4版本，但直到kube-proxy被修复，这可能是一些唯一可行的选择

good

**Comment by yujiaao** [comment]
> For anyone finding this thread the below workaround may work for now with Centos at least:
> 
> Ok so as a work around I have done:
> 
> ```
> yum downgrade http://mirror.centos.org/centos/7.5.1804/updates/x86_64/Packages/iptables-1.4.21-24.1.el7_5.x86_64.rpm
> ```
> 
> and adding iptables-* to the exclude in /etc/yum.conf
> 
> ```
> [main]
> .....
> ....
> exclude=iptables-*
> ```
> 
> This is NOT a good fix as it rolling iptables back 4 releases but until kube-proxy is fixed this may be the only viable option for some

404
