### ISSUE TITLE
Should deprecate kubeapiserver insecure http schema 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#58951]
Currently as authentication and authorization are both standard config for all clusters, the kubeapiserver insecure http handler is unsecure, which means the cluster is vulnerable to the attack.  So it should be deprecated, even removed totally. 

@deads2k @lavalamp @sttts @ncdc @liggitt

**Comment by deads2k** [comment]
I think removing the insecure option is a good idea.  

@kubernetes/sig-api-machinery-misc @smarterclayton 

@hzxuzhonghu Can you send an email the sig-apimachinery mailing list with a proposed timeline?  I think this should be like other GA features and have a one year clock.

**Comment by hzxuzhonghu** [comment]
Sure, I will send it ASAP.

**Comment by sttts** [comment]
:+1:
