### ISSUE TITLE
Cronjob won't start when setting resources memory limits

### ISSUE THREAD

**Issue by mdaley** [kubernetes/kubernetes#58966]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

cronjobs fail to run when there is a resource limit set for memory.  I've created a concise demonstration of the problem below.  This shows the problem both in our cluster in GCP (1.8.5-gke-0) and with minikube (latest version, kubernetes 1.9.0).

**What you expected to happen**:

The jobs should run when the `limits - memory` is set.

**How to reproduce it (as minimally and precisely as possible)**:

I've created a concise variant of the problem that we've experienced with cronjobs in our real Kubernetes cluster in GCP.

If I deploy to our cluster in GCP a slightly modified version of the kubernetes hello-world cron job from https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ where all I've done is added a `resources` element to limit CPU, then the cron job runs successfully every minute.  This is the config of the cronjob:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            resources:
              requests:
                cpu: "100m"
              limits:
                cpu: "100m"
          restartPolicy: OnFailure
```

However, when I add `memory` settings to the `resources` element, the jobs fail to start.  I made this change:

```
            resources:
              requests:
                cpu: "100m"
                memory: "1000m"
              limits:
                cpu: "100m"
                memory: "1000m"
```

That's quite a lot of memory for a small job!!

I also did the same in a locally running minikube.  The same problem occurs.

**Anything else we need to know?**:

`kubectl describe` on the a pod shows this:

```
Events:
  Type     Reason                  Age                From                                          Message
  ----     ------                  ----               ----                                          -------
  Normal   Scheduled               40s                default-scheduler                             Successfully assigned hello-1517238540-hh5j7 to gke-meters-pool-4vcpu-2fc6d3d5-9vs2
  Normal   SuccessfulMountVolume   40s                kubelet, gke-meters-pool-4vcpu-2fc6d3d5-9vs2  MountVolume.SetUp succeeded for volume "default-token-37dps"
  Warning  FailedCreatePodSandBox  29s (x8 over 39s)  kubelet, gke-meters-pool-4vcpu-2fc6d3d5-9vs2  Failed create pod sandbox.
  Warning  FailedSync              29s (x8 over 39s)  kubelet, gke-meters-pool-4vcpu-2fc6d3d5-9vs2  Error syncing pod
  Normal   SandboxChanged          28s (x8 over 38s)  kubelet, gke-meters-pool-4vcpu-2fc6d3d5-9vs2  Pod sandbox changed, it will be killed and re-created.
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5-gke0 (and 1.9 for minikube)
- Cloud provider or hardware configuration: Google Cloud Platform
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
i can't seem to recreate with latest master.  does using something else like `memory: "1G"` help?

**Comment by phsiao** [comment]
I think the problem is

```
memory: "1000m"
```

is too low --- that is 1 byte.

**Comment by mdaley** [comment]
[embarrassed grin] Oh, no, have I been silly.  Lower case m instead of upper case M.  I'll try this out tomorrow.
