### ISSUE TITLE
Does k8s support assigning unique identification to each pod?

### ISSUE THREAD

**Issue by mdianjun** [kubernetes/kubernetes#58962]
I create a Deployment with 5 pods, the requirement is that each application in each pod needs an unique identification(such as pod-1, pod-2, pod-3, pod-4, pod-5).  StatefulSet is not suitable，because pods couldn't be rescheduled when the node is NotReady.  Is there any ways to achieve this ?

**Comment by mdianjun** [comment]
@kubernetes/sig-apps-feature-requests
The requirement is that, when a pod is rescheduled to another node, the pod’s iidentification wouldn’t be changed.

**Comment by drinktee** [comment]
A pod is rescheduled to another node, which means old pod is deleted, and a new pod has created. Maybe you want a feature that when rs create/delete some pods, their names won't be changed.
