### ISSUE TITLE
Apiserver proxy rewriting not useful for intra-cluster links

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#5897]
Forked from #4440.

The apiserver proxy uses httputil.NewSingleHostReverseProxy. This rewrites URLs to a fixed scheme, host, and base path. This is not smart enough to facilitate translation of links to other (intra-cluster) services, pods, and nodes, which are all proxy-able directly. In fact, if someone puts the correct proxy links into their pages, the links are munged and broken by the reverse proxy.

Internally, we don't rewrite links. Applications use intra-cluster names (DNS and our internal NS) and addresses, and we have a few different mechanisms to route those to the reverse proxy.

If we want to stick with the rewriting approach, the proxy should recognize and translate intra-cluster names and addresses. #3481 proposed proxying by IP address in addition to resource path.

cc @enisoc @lavalamp @smarterclayton

**Comment by lavalamp** [comment]
I would love to get rid of the rewriting, it is really error-prone.

**Comment by lavalamp** [comment]
The only good part of the rewriting is that it works without external dependencies on any sort of discovery system. So it might be useful for debugging broken clusters. But the production proxy shouldn't do rewriting.

**Comment by smarterclayton** [comment]
Closing due to age and extreme lack of interest in fixing.
