### ISSUE TITLE
Remove load balancer requirement for standing up cluster federation

### ISSUE THREAD

**Issue by bputt** [kubernetes/kubernetes#58974]
/kind feature

**What happened**: I have 2 clusters setup and when I try to stand up cluster federation, it fails to start because I don't have a cloud provider with load balancer capabilities.

**What you expected to happen**: Kubeadm to initialize properly without need of a load balancer from a cloud provider. It'd be great if it could stand up a haproxy service and manage haproxy for its needs.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubeadm init --pod-network-cidr=10.32.0.0/12 --feature-gates=CoreDNS=true

kubefed init fellowship \
    --host-cluster-context=kubernetes-admin@kubernetes \
    --dns-provider="coredns" \
    --dns-zone-name="example.com."
```

Output (It goes on like this for a while)

```
Creating a namespace federation-system for federation system components... done
Creating federation control plane service..............................................................................................
```

**Anything else we need to know?**:

Your documentation does list that I need loadbalancer support, but there's got to be a way where we could use haproxy/nginx as a k8s service to solve this dependency.

```
Support for LoadBalancer services in member clusters of federation is mandatory to enable CoreDNS for service discovery across federated clusters
```

```
kubectl get svc --namespace=federation-system
NAME        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
apiserver   LoadBalancer   10.100.214.150   <pending>     443:30652/TCP   1m
````

```
kubectl describe svc apiserver --namespace=federation-system
Name:                     apiserver
Namespace:                federation-system
Labels:                   app=federated-cluster
Annotations:              federation.alpha.kubernetes.io/federation-name=fellowship
Selector:                 app=federated-cluster,module=federation-apiserver
Type:                     LoadBalancer
IP:                       10.100.214.150
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30652/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: Openstack icehouse
- OS (e.g. from /etc/os-release): Centos 7.latest
- Kernel (e.g. `uname -a`): 3.10.0-693.11.6.el7.x86_64
- Install tools:
- Others:

**Comment by shashidharatd** [comment]
please raise this issue in https://github.com/kubernetes/federation
i am closing this issue as this is federation specific.
/close
