### ISSUE TITLE
kubectl stopped working after reboot

### ISSUE THREAD

**Issue by marcofiocco** [kubernetes/kubernetes#58988]
/kind bug

**What happened**:
I've installed Kubernetes 1.9.2 on the master node (Ubuntu 16.04) including the dashboard. All the pods were running fine. But after rebooting, when I try to run `kubectl get nodes` or `kubectl get pods` I get:

`The connection to the server 10.50.88.230:6443 was refused - did you specify the right host or port?
`

If I run` kubectl cluster-info` I get:

```
Kubernetes master is running at https://10.50.88.230:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 10.50.88.230:6443 was refused - did you specify the right host or port?
```

But if I run `kubectl cluster-info dump` I get the same error.

**What you expected to happen**:
See the list of nodes and work as usual

**How to reproduce it (as minimally and precisely as possible)**:
I've installed Kubernetes 1.9.2 on the master node (Ubuntu 16.04) including the dashboard and using Flannel as pod network. All seemed to run fine. Then I rebooted and I got that error.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
1.9.2

- Cloud provider or hardware configuration:
CPU#/GHZ: 2, 1 GHz
RAM: 16 GB

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux ECS-9ce3f5ca 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Followed https://kubernetes.io/docs/setup/independent/install-kubeadm/

- Others:

**Comment by warpspeed6** [comment]
Had prob same issue as restart broke it for me with same error message... My env variable was the issue which was set to blank after restart...
solution for me was:
export KUBECONFIG=$HOME/.kube/config

Works after that....

**Comment by Rishi0405** [comment]
I got the same error, I forgot to turn off the swap. after disabling swap it worked.

**Comment by weisjohn** [comment]
My environment variable is set and I've turned off swap. Still having a problem though.

**Comment by rcarmonad** [comment]
I have the same issue. Turned of the swap and export the env.
Not working.

**Comment by solomatov** [comment]
I have the same issue. None of the workarounds helped.

**Comment by cyrilbkr** [comment]
I have the same issue with k8s 1.11.3 after a reboot

**Comment by marcstreeter** [comment]
I believe it has to do with what @Rishi0405 said about swap not being disabled. It also shows in this thread  https://discuss.kubernetes.io/t/the-connection-to-the-server-host-6443-was-refused-did-you-specify-the-right-host-or-port/552/4

**Comment by DamienVStone** [comment]
I don't know WTF, but after
`export KUBECONFIG=$HOME/.kube/config`
`sudo systemctl restart docker`
`sudo systemctl restart kubelet`
on **master** node, my cluster is ressurected

**Comment by LuckyPigeon** [comment]
Just like @DamienVStone mentioned. Be sure to check docker and kubelet status and start/restart them.

**Comment by Happyman0815** [comment]
Worked for me in Windows 10:
Execute in command line:

`ipconfig /flushdns`

I have this script now in my autostart folder and it works fine.

**Comment by jonsys** [comment]
> I don't know WTF, but after
> `export KUBECONFIG=$HOME/.kube/config`
> `sudo systemctl restart docker`
> `sudo systemctl restart kubelet`
> on **master** node, my cluster is ressurected

Thanks a lot @DamienVStone this worked for me.

**Comment by xiaojueguan** [comment]
In my case, I found my kubelet service is failed to start with reason: `Failed to run kubelet" err="failed to run Kubelet: running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false`. So i use `sudo swapoff -a ` to disable the swap and comment the swap part in `/etc/fstab`
