### ISSUE TITLE
Hash of a pod for Equivalence Cache should be calculated once per schedule

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#58989]
Today, [scheduler calculates equivalence hash of a Pod once per node](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L421). This seems unnecessary and should be done once for all the nodes. 

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

/sig scheduling

cc: @resouer @misterikkit

**Comment by resouer** [comment]
/assign

Thanks, will send fix per slack discussion.
