### ISSUE TITLE
make tolerations wildcardable

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#58981]
to graduate taints/tolerations to beta, we should make tolerations wildcard-able, so that we can have a toleration that tolerates all taints with certain key and effect.

/assign

**Comment by bsalamat** [comment]
Taints and tolerations is already a beta feature and supports wildcard tolerations. Please see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts.

**Comment by yastij** [comment]
Indeed, I wasn't aware of this, closing this one
