### ISSUE TITLE
RFC: Some thoughts about node e2e tests

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#59001]
Back in 1.5, sig-node defined a set of node conformance tests (i.e., tagged `[Conformance]`). However, there lacks follow-up efforts to maintain the set of conformance tests. IMO, except for a specific set of features which depend on the OS distribution, container runtime, and/or are still under development, most features/tests should be included in the set of node conformance tests. To maintain the set of the tests and to actually utilize the fact that we have "conformance" tests, I think we can start from the following items.

 * Run only the conformance tests in presubmit (`pull-kubernetes-node-e2e` suite) should focus only on the conformance tests.
 * The regular post submit node e2e suite should focus only on the conformance tests.
 * Any new node e2e test added should either be tagged as `[Conformance]` or `[Feature: XXX]`.
 * We should add a dedicated CI test job for features.

If a new test does not have any such tag, it will not be run anywhere in CI. This gives the feature owner some incentive to categorize and promote tests for their features.

*Prerequisite for doing this:*
- Scan and promote/demote tests from the conformance suite.
- Ensure each test is assigned a tag.

*Some potential improvements (details TBD):*
 - It should be able to optionally trigger feature-specific test jobs for a given PR.
 - Define a set of common tags such as `[Feature: Performance]`.

Thoughts? @kubernetes/sig-node-proposals @dchen1107 @derekwaynecarr 
/cc @abgworrall

**Comment by dchen1107** [comment]
LGTM. This is part of our CRI runtime qualification process.

**Comment by jberkus** [comment]
Please give this issue a priority and kind, or remove it from the milestone.  Thanks!

**Comment by jberkus** [comment]
I see a PR documenting the desired tests; what's the status of actual e2e tests for CRI?  Are we going to have some for 1.10?

**Comment by jberkus** [comment]
As a reminder, this issue is going to be automatically removed from 1.10 in 7 hours.  If you don't want that to happen because you expect to have work to commit in the next few days, please add status/approved-for-milestone to it.

**Comment by jberkus** [comment]
Since we are now in Code Freeze, escalating priorities.

/priority critical-urgent

/remove-priority important-soon

**Comment by yujuhong** [comment]
Moving this off the milestone since changing the tests categorization right now may affect the 1.10 release.

**Comment by yujuhong** [comment]
Updated proposal:
https://docs.google.com/document/d/1BdNVUGtYO6NDx10x_fueRh_DLT-SVdlPC_SsXjYCHOE/edit?usp=sharing

**Comment by tpepper** [comment]
@yujuhong this has been open for months and is not looking "critical-urgent" by plain english.  Can you demote this to a lower priority?  Also it's not clearly looking like this is on track for 1.11 with code slush/freeze coming very soon.  If this is not going to make the milestone, please remove.

**Comment by yujuhong** [comment]
The majority of the tasks have been completed. Closing this issue.
