### ISSUE TITLE
Error log in kubelet source file watch is misleading

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#59009]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

When something wrong with kubelet source file watching, like: https://github.com/kubernetes/kubernetes/issues/55928, kubelet will report a error message with: 

```
file_linux.go:114] Can't process manifest file "/etc/kubernetes/manifests/4913": open /etc/kubernetes/manifests/4913: no such file or directory
```

**What you expected to happen**:

This error message is misleading, which is in:

```
	// Reset store with manifest files already existing when starting
	if err := s.resetStoreFromPath(); err != nil {
		return fmt.Errorf("unable to read manifest path %q: %v", s.path, err)
```

It should always return the path of source file during error, instead of `4913`. We should find out what caused this magic number.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@resouer - see clue here - https://github.com/kubernetes/kubernetes/issues/55928#issuecomment-345203099

you probably used vi/vim to edit a file :) https://www.google.com/search?q=inotify+4913
