### ISSUE TITLE
Configure DNS options at cluster level

### ISSUE THREAD

**Issue by pierreozoux** [kubernetes/kubernetes#59031]
/kind feature
/sig network

We are having some little DNS issues as well. But we think it is normal as DNS is on top of UDP, and well, some packets are lost (The quantity of lost UDP packets is an other debate).

In our case, we think it would be easy to mitigate, and actually improve performances of our applications just by fine tuning the DNS options in `/etc/resolv.conf`.

Currently it uses the defaults which are (for the options we are interested in):
 - timeout: 5s
 - retries: 2

And we'd like to change it for:
 - timeout: 0.1s
 - retries: 5

Our application timeout the http request at 2500ms, so this dns timeout value is clearly useless in our case.

We can change this already at the pod level in various ways:
 - [ENV variable](https://stackoverflow.com/a/45403565/1703029) for NodeJS application
 - [PodStart hook](https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-359897058) command to modify `/etc/resolv.conf` - in our case, this doesn't work as the pod is not started as root

But we think this would be a nice to have to be able to fine tune these options at the cluster level.

I can see with the [current code](https://github.com/kubernetes/kubernetes/blob/277d86611198299698429b9deafbe6a226b472dc/pkg/kubelet/network/dns/dns.go#L42) that this is fixed and not configurable.

I'm tempted to do the fix myself, but I'm afraid of the testing part, if you point me to the right direction, and help me a bit, I'm willing to try the PR :)

**Comment by pierreozoux** [comment]
@kubernetes/sig-network-feature-requests

**Comment by dixudx** [comment]
@pierreozoux You can try to use `--resolv-conf` when starting `kubelet`. Refer to [kubelet Options](https://kubernetes.io/docs/reference/generated/kubelet/).

**Comment by MrHohn** [comment]
@pierreozoux One more pod level solution is using `dnsConfig`: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-dns-config

**Comment by MrHohn** [comment]
xref https://github.com/kubernetes/features/issues/504.

**Comment by pierreozoux** [comment]
@MrHohn I want a cluster level configuration (I don't want to have to specify this on each pod)

**Comment by MrHohn** [comment]
> Looking at the code, I don't see anywhere where the pod configuration would inherit from the node configuration.

@pierreozoux Sorry, there have been some movements around pod DNS codes, most of them now live in:
https://github.com/kubernetes/kubernetes/blob/48388fec7eaad4ac8d84fbe20673ffacf41964a1/pkg/kubelet/network/dns/dns.go#L324-L325

A pod will only inherit from the node DNS configuration when it sets `hostNetwork=True`, so using `--resolv-conf` flag might not be sufficient for your use case.

As you said, we should probably provide a knob for the default DNS option on pod.

**Comment by steven-sheehy** [comment]
Our company needs this feature as well to combat [DNS](https://github.com/kubernetes/kubernetes/issues/62628) [timeouts](https://github.com/weaveworks/weave/issues/3287) by enabling single-request-reopen option cluster wide. The [pull request](https://github.com/kubernetes/kubernetes/pull/62764) that added this as a default option was closed. dnsConfig is nice but we don't control every pod we deploy since some come from helm charts.

**Comment by steven-sheehy** [comment]
It would also be nice to configure the search paths as well without switching to host DNS since with CoreDNS autopath we no longer need ndots:5 and all the hardcoded kubernetes search paths usually in resolv.conf.

**Comment by thockin** [comment]
It seems unlikely that we will add a cluster-level config for this, but here's an opportunity for a cool ecosystem project.  Something like:

A per-namespace CRD that defines default DNS policy
An admission control webhook that sets DNS policy on pods according to the namespace policy

**Comment by vainu-arto** [comment]
@thockin What about adding this functionality to PodPresets? That would allow using the existing matcher it has to find the pods where policy needs to be set.

**Comment by MrHohn** [comment]
cc @prameshj

**Comment by ramnes** [comment]
> It seems unlikely that we will add a cluster-level config for this

**Comment by sshishov** [comment]
Looks funny when 2 bots talk to each other)))

**Comment by vivekgkwd** [comment]
Do we have a work around for this?

**Comment by jiafujiang** [comment]
Want a solution for this~

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/issues/59031#issuecomment-490761350

**Comment by alicancakil** [comment]
hello, I am also facing with same problem. I want to be able to set DNS policies at the cluster level. 

Is there any solution?

**Comment by thockin** [comment]
I mostly stand by this:

https://github.com/kubernetes/kubernetes/issues/59031#issuecomment-490761350

Things like Gatekeeper make it even easier, I think.

Why?  The shortest answer is that every new API we introduce add complexity and cost to the system - the code, the tests, the docs, etc.  It introduces new failure modes and new conditions that subsequent features need to consider, and we have to deal with it pretty much FOREVER.  As such, we need to be very cautious about adding APIs (be that new types or even just fields in an existing API).

When something can be solved by an ecosystem project without the Kubernetes project being involved, it's generally better.  It has the side benefits of being easier to develop *and* it's compatible with more kube versions (you can load a CRD on many back-revisions, but we would not port such a feature to stable releases).

**Comment by zengyuxing007** [comment]
There are too many related similar issues. Perhaps we can consider reopening this issue.
