### ISSUE TITLE
Load test in our scalability jobs failing while scaling RCs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#59043]
We're seeing such failures:

```
error while scaling RC load-small-279 to 3 replicas: Scaling the resource failed with: unable to get client for replicationcontrollers: unable to get full preferred group-version-resource for replicationcontrollers: the cache has not been filled yet
```

in the load test in all our scalability jobs running against head. For e.g:

- https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability?before=10414
- https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce?before=6124
- https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce?before=11606

/cc @kubernetes/sig-scalability-bugs  @porridge

**Comment by shyamjvs** [comment]
It's quite clearly a regression, and the [diff](https://github.com/kubernetes/kubernetes/compare/5ab8f8cea...235714e7f) suggests that the following PR could've likely caused the problem:

#58298 removes the remainder from ScalerFor method

**Comment by shyamjvs** [comment]
cc @p0lyn0mial @deads2k

**Comment by shyamjvs** [comment]
I'm almost sure it's that one. Let me verify if reverting helps.

**Comment by porridge** [comment]
Some references:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/10396
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/10397

**Comment by deads2k** [comment]
@DirectXMan12 Can you figure out what's going on with this?

**Comment by DirectXMan12** [comment]
I have a suspicion -- none of the e2e code seems to call Reset on the `DeferredDiscoveryRESTMapper`, which, IIRC, means it never calls `Invalidate` on the underlying memory discovery cache.

**Comment by DirectXMan12** [comment]
(FWIW, `Reset` is *supposed* to be called automatically, from what I can tell of the intentions, but I seem to recall that there may have been a logic issue in the `DeferredDiscoveryRESTMapper` which caused it to never be called...)

**Comment by DirectXMan12** [comment]
(Ah, yep, we'll never be able to construct the "delegate" rest-mapper if we don't have a valid cache, so we'll never get to the line that asks if we're fresh yet)

**Comment by Random-Liu** [comment]
Serial test is also broken. #59058
