### ISSUE TITLE
High API Server latency

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes/kubernetes#59049]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
After upgrading from `1.7.7` the API server latency for `post` has gone up.
`histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!="log",verb!~"CONNECT|WATCHLIST|WATCH|PROXY"}) WITHOUT (instance, resource)) / 1000000 > 1`

`
{job="kubernetes-apiservers",scope="cluster",verb="POST"} | 6.30666666666664
`
```
I0130 14:39:08.768922       7 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (6.348872ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:40:09.463910       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (6.954807ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:40:09.470983       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (6.420996ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:40:09.478187       7 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (6.561938ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:41:09.740432       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (6.648037ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:41:09.759723       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (18.477636ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:41:09.767937       7 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.447117ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:42:10.078397       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (6.316091ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:42:10.085555       7 wrap.go:42] POST /api/v1/namespaces/kube-system/serviceaccounts: (6.400554ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
I0130 14:42:10.093256       7 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.050314ms) 409 [[protokube/v1.8.1 (linux/amd64) kubernetes/$Format] 127.0.0.1:45574]
```

**What you expected to happen**:
The `post` latency should not be this high.

**How to reproduce it (as minimally and precisely as possible)**:
AFAIK upgrading `k8s` release in `aws` from `1.7.7` to `1.8.6` with `RBAC`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: `aws`
- OS (e.g. from /etc/os-release): `ubuntu`
- Kernel (e.g. `uname -a`): `Linux ip-172-20-117-22 4.4.0-1048-aws #57-Ubuntu SMP Tue Jan 9 21:45:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by naveensrinivasan** [comment]
cc @kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
How high did the latency used to be, and how high is it now? The snippet of logs is in the 6ms to 18ms range which is super fast (1s is the SLO).

**Comment by naveensrinivasan** [comment]
This is not happening anymore. Closing it for now.

**Comment by naveensrinivasan** [comment]
This is happening again.
![image](https://user-images.githubusercontent.com/172697/36035236-4ed675c6-0d84-11e8-8c9b-ba4c6b899178.png)

[https://raw.githubusercontent.com/naveensrinivasan/kubeapi/master/kube-apiserver.log](https://raw.githubusercontent.com/naveensrinivasan/kubeapi/master/kube-apiserver.log)
