### ISSUE TITLE
add PV resize support for iSCSI 

### ISSUE THREAD

**Issue by kmova** [kubernetes/kubernetes#59040]
/kind feature
/sig storage

**What happened**:
As per the [docs ](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), the support for expanding volumes has been added in 1.9 to the following:
- gcePersistentDisk
- awsElasticBlockStore
- Cinder
- glusterfs
- rbd

Related Feature: https://github.com/kubernetes/features/issues/284

**What you expected to happen**:
Support for expanding iSCSI PV

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
This feature depends on the iSCSI Target support for expanding the volumes. This feature can be used by dynamic provisioners that expose the volumes via iSCSI.

**Comment by mtanino** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by saad-ali** [comment]
CC @gnufied

**Comment by wavezhang** [comment]
+1, we also need PV resize support for CSI

**Comment by rgembalik** [comment]
+1 from me as well - in the end, it will remove much of inconvenient hassle while managing our PV's.

**Comment by kmova** [comment]
Working on a fix for this via iSCSI CSI driver.
