### ISSUE TITLE
fluentd isnt shipping logs to stackdriver

### ISSUE THREAD

**Issue by DinaWork** [kubernetes/kubernetes#59051]
**BUG REPORT**

I have an application deployed on kubernetes on GKE,
`Stackdriver Logging` is enabled on my cluster
fluntd-gcp image on my cluster (by default):
`gcr.io/google-containers/fluentd-gcp:2.0.9`

my logs  were all ok, seen in stackdriver,
but since a few days ago logs from one deployment (lets call it `my-app` )  stopped arriving in stackdriver
even though  they are logged from my app :

`kubectl logs -f my-app-3270987706-cx0r2  --namespace=production`

    {"time":"2018-01-30 16:11:13.155","msg":"ignoring xml"}
    {"time":"2018-01-30 16:11:14.155","msg":"success blabla"}

I see the following logs from `fluentd`:

    2018-01-30 16:11:46 +0000 [warn]: emit transaction failed: 
    error_class=Errno::ENOENT error="No such file or directory @ sys_fail2 -
     (/var/log/fluentd-buffers/kubernetes.system.buffer..b563203c1da7cb5e1.log, /var/log/fluentd-
    buffers/kubernetes.system.buffer..q563203c1da7cb5e1.log)" tag="docker"

----

    2018-01-30 16:11:46 +0000 [warn]: suppressed same stacktrace

-----

    2018-01-30 16:11:46 +0000 [error]: Exception emitting record: 
    No such file or directory @ sys_fail2 - 
    (/var/log/fluentd-buffers/kubernetes.system.buffer..b563203c1da7cb5e1.log,
     /var/log/fluentd-buffers/kubernetes.system.buffer..q563203c1da7cb5e1.log)

why logs arent shipped to stackdriver? how can I fix it? 

**Environment**:
- Kubernetes version: v1.7.11-gke.1 
- Cloud provider: GKE

**Comment by DinaWork** [comment]
Ill note that the logs of other apps do appear in stackdriver 
the logs of the failing app are very big - maybe thats why they fail to log?

**Comment by teddythetwig** [comment]
Hi @DinaWork we also just ran into this issue after one of our applications was hit with a large amount of requests over a short period of time. Did you figure out a way to clear out the fluentd buffer?

I can confirm as well that it only happens to one of the apps running in our GKE cluster.

**Comment by DinaWork** [comment]
@teddythetwig  

this was my solution
https://stackoverflow.com/questions/48442077/log-flood-after-master-upgrade-from-1-6-13-gke-0-to-1-7-11-gke-1

it seems it wasnt related to the large amount of logs
