### ISSUE TITLE
the source code of kube-apiserver , where is  the  AuthenticateRequest called when a request  come in ?

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#59066]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
l  found the autorization and autentication's handle was regisry ,but l can't find anywhere to call

**What you expected to happen**:
l want know where is call when the request come in

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huangjiasingle** [comment]
@kubernetes-apiserver-sig

**Comment by huangjiasingle** [comment]
@kubernetes/sig-apiserver

**Comment by huangjiasingle** [comment]
@kubernetes/sig Auth

**Comment by huangjiasingle** [comment]
@kubernetes/sig-Auth

**Comment by mikedanese** [comment]
It's a server filter:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go

that is added to the defautl request handler chain:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/config.go#L545

**Comment by huangjiasingle** [comment]
@mikedanese  yeal  l got it and understand it. thank you
