### ISSUE TITLE
Kubelet should fire sd notify to systemd (like genericapiserver) so it can have clean starts

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#59079]
There's no downside to including the notify if systemd is not installed, and we already run it on some processes like the API.  Adding it to the Kubelet is a no brainer.

For systemd enabled systems this brings us to parity with the other components when starting the kubelet in a unit file and improves the operational experience (restart and start wait until config has been read before reporting started).

@sjenning @derekwaynecarr @kubernetes/sig-node-bugs

**Comment by smarterclayton** [comment]
The harder problem is when to fire the notify - once static pods start, once the api is registered, or simply once the sync pod loop starts.

**Comment by dcbw** [comment]
@smarterclayton for starters just do it like openshift does; when kubelet has started like in cmd/kubelet/app/server.go::run() right before the `<-done`.  Then later we figure out a more intelligent way.

Perfect world would be once static pods have started and API has registered, but that could take a long time and you don't necessarily want to block dependent systemd units on that.

Anyway, first-pass at this in https://github.com/kubernetes/kubernetes/pull/60654

**Comment by smarterclayton** [comment]
The only reason we put it there in openshift is we didn't change the kubelet (which was arguably a mistake).  The start of the sync loop means we've correctly initialized everything except seeing a pod.  What is the start of the API gated on?
