### ISSUE TITLE
Confusing daemonset's retry creating failed daemon pods e2e test

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#59076]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
DaemonSet has an e2e test running `should retry creating failed daemon pods` that has dubious purpose.

**What you expected to happen**:
The e2e test should be refactored and commented clearer as it will be part of the conformance.

**Comment by crimsonfaith91** [comment]
@foxish @enisoc

**Comment by enisoc** [comment]
To elaborate, we're concerned that the following may not actually ensure that DaemonSet recreates Failed Pods:

https://github.com/kubernetes/kubernetes/blob/8b9aa35d4ed8681058ae49ced71750f6d1623fe4/test/e2e/apps/daemon_set.go#L241-L249

For example, it seems possible that the Node might simply overwrite the Pod status with its own information if it hasn't yet seen the change to the Phase.

Ideally, we should verify that the Pod UID we force to Failed no longer shows up in the DaemonSet's list of Pods after the DaemonSet becomes happy again.
