### ISSUE TITLE
admission/webhook: breaking change: POST and PUT error messages might change

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#59071]
Follow-up to #56761.

Suppose the kube-system namespace already exists.

Before admission webhooks, a POST of kube-system would produce a 409 conflict error because it already existed. Now, if an admission webhook would have blocked the request, users will see a 500 error instead.

Likewise for PUTs that disallow object creation, users will (with the right sort of webhook installed) observe a 500 instead of a 404.

Fundamentally this is because we run requests through the admission stack before any etcd GETs are issued. Should we change this, or just document the behavior change?

**Comment by sttts** [comment]
My immediate reaction is: 500 is wrong. 403 and 409 sound reasonable. If we used to have those, we should fix this in 1.9 going back to the old semantics. This is a bug IMO.

**Comment by jennybuckley** [comment]
cc @caesarxuchao

**Comment by jennybuckley** [comment]
cc @yliaog
