### ISSUE TITLE
k8s.io/apiextensions-apiserver/test/integration TestPatch flakes 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#59087]
I find so many flakes about this case.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58445/pull-kubernetes-unit/77656/

**Comment by nikhita** [comment]
Already being tracked in https://github.com/kubernetes/kubernetes/issues/42644.
