### ISSUE TITLE
how to rotate log for apiserver kubelet etc..

### ISSUE THREAD

**Issue by oule** [kubernetes/kubernetes#59081]
> kind/feature

hello everyone,
I use k8s 1.5.2
and don't know how to set it's param for apiserver kubelet proxy controller-manager scheduler
I want rotate it's logs

**Comment by islinwb** [comment]
https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level

**Comment by oule** [comment]
@islinwb 
thank you verymuch
上面说要使用kube-up.sh

**Comment by islinwb** [comment]
@oule I'm not familiar with it....  The doc says it depends on your `deployment tool`. (If your cluster is not deployed by ` kube-up.sh`, you should query docs about the  `deployment tool` you used ).
> Kubernetes currently is not responsible for rotating logs, but rather a deployment tool should set up a solution to address that. For example, in Kubernetes clusters, deployed by the kube-up.sh script, there is a logrotate tool configured to run each hour.

**Comment by jhorwit2** [comment]
@oule The components you mentioned don't support logging directly to files (only stdout/stderr) other than the  apiserver audit logs, which does support log rotation via the `--audit-log-*` flags. Supporting log rotation is going to depend on the the deployment tool that you're using so I'm going to close this issue. You should open this issue with the respective deployment tool that you use.  

You can see [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L321) how gce does this, which may help you set it up as well! 

/close
