### ISSUE TITLE
Ingress-Controller (with tcp-ports cm) anomaly regarding special ports

### ISSUE THREAD

**Issue by m-no-2017** [kubernetes/kubernetes#59096]
Architecture:
- 4x Nodes
- 2x Masters (HA), 2x Worker
- built up from scratch
- k8s version 1.7.2
- Ubuntu 16.04.03 LTS, kernel v4.11 (lowlatency)

There is a bug or routing flaw (as far as I can tell) in the following setup of k8s components:

- Ingress Controller (NGINX)
- Ingress Object (k8s ingress definition)
- NGINX proxy
- Service (k8s service definition)
- POD (k8s pod definition)

Our situation was a special ssh connection (port 6543) to a pod that holds our application.  
The thing that worked at the beginning was an entry in the "tcp-ports" configmap with the following pattern:
<pre><code>[port]: "[namespace]/[service-name]:[port]"</code></pre>
The general request chain from user (simple http/https requests) to cluster as I thought of is:
<pre><code>URL request > Ingress Controller > Ingress Object > NGINX > server block in NGINX conf > service of the pod > pod</code></pre>

The route somehow changes if you use the "tcp-ports"-variant. Its behaviour isn't equal to the NodePort usage in services (which would work I think). The "exposed" port (in our case 6543) was available and everything worked until there was a difference between the location of the pod and the dns cache of the requesting user.  
Our dns entries point to 4x IPs (101,102,103,104).

For example (fails):
- POD is scheduled on xxx.xxx.xxx.101
- User request (e.g. git clone) to the application was cached to xxx.xxx.xxx.102
- Result: timeouts (no connection at all)

For example (succeeds):
- POD is scheduled on xxx.xxx.xxx.101
- User request to the application was cached to xxx.xxx.xxx.101
- Result: everything works

I thought that the kube-proxy would work like always and route this specific traffic in the pattern I knew from e.g. NodePorts. In our case this isn't happening.

Just to check:
- DNS works
- kube-proxy works (with NodePorts and normal service connections)
- applications run without failures
- ingress controllers work
- ingress objects work (and get collected correctly by the controllers)
- nginx proxy works as intended

With normal ports (80/443) there are no problems at all.

/kind bug
/sig network

**Comment by jhorwit2** [comment]
@m-no-2017 Please open this issue under the [ingress controller repo](https://github.com/kubernetes/ingress-nginx). That'll ensure you get support in a reasonable time as tickets for that repo are not checked for in k8s core. 

/close

**Comment by jhorwit2** [comment]
@m-no-2017 FYI, if you're using the ingress controller above that does not use kube-dns/service IP. It routes directly to the backend pods.
