### ISSUE TITLE
Run Kubelet on Mac OS 

### ISSUE THREAD

**Issue by astro-5** [kubernetes/kubernetes#59105]
/kind feature

**What happened**:
Downloaded kubernetes source code and built it on Mac OS X. When I tried to build and run kubelet.go file, I got the below logs:
```
I0131 14:34:49.335567    2926 feature_gate.go:144] feature gates: map[]
W0131 14:34:49.335770    2926 server.go:469] No API client: no api servers specified
I0131 14:34:49.335872    2926 docker.go:364] Connecting to docker on unix:///var/run/docker.sock
I0131 14:34:49.335892    2926 docker.go:384] Start docker client with request timeout=2m0s
W0131 14:34:49.339829    2926 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
W0131 14:34:49.339978    2926 server.go:350] No api server defined - no events will be sent to API server.
I0131 14:34:49.339997    2926 server.go:509] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
E0131 14:34:49.340051    2926 server.go:564] Kubelet needs to run as uid `0`. It is being run as 502
W0131 14:34:49.340075    2926 server.go:574] setting OOM scores is unsupported in this build
W0131 14:34:49.340270    2926 iptables.go:142] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
W0131 14:34:49.340454    2926 kubelet_network.go:70] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0131 14:34:49.340473    2926 kubelet.go:494] Hairpin mode set to "hairpin-veth"
W0131 14:34:49.340566    2926 plugins.go:221] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
error: failed to run Kubelet: failed to create kubelet: cAdvisor is unsupported in this build
```

**What you expected to happen**:
Expect to build and run kubelet natively on Mac machines without VM.

/sig node
/area kubelet

**Comment by ryanhartje** [comment]
RIP

**Comment by ryanhartje** [comment]
@astro-5 there are a number of complications with running kubelet natively on MacOS, which is backed by XNU, which doesn't natively support namespaces or cgroups, thus doesn't natively support containers. 

Docker is run on mac by running inside a virtualization layer through hyperkit if I'm not mistaken. 

If these were all resolved, you'd still have the 3 errors you shared in your log output, which are that you're missing various files and configurations:
```
W0131 14:34:49.339829    2926 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
W0131 14:34:49.339978    2926 server.go:350] No api server defined - no events will be sent to API server.
```
Without CNI, you'll not be able to setup an overlay network without considerable networking knowledge.
Without an apiserver configured to connect to, running kubelet will be pointless as it won't do anything on its own.

```
E0131 14:34:49.340051    2926 server.go:564] Kubelet needs to run as uid `0`. It is being run as 502
```
You can't run Kubelet as your user, you'd need to run it as root, the user with id 0

```
error: failed to run Kubelet: failed to create kubelet: cAdvisor is unsupported in this build
```
cadvisor (if im not mistaken) relies on cgroups, which are not support in XNU (MacOS's kernel)

This will probably not be done, unless Apple decides to implement cgroups and namespaces. 

I hope this kind of explains why this kubelet, and other pieces of k8s, are run in VMs.
