### ISSUE TITLE
patch in combination with --local not working

### ISSUE THREAD

**Issue by ChrisTerBeke** [kubernetes/kubernetes#59117]
/kind bug

**What happened**:
Getting the following error:

```
error: cannot specify --local and server resources
```

**What you expected to happen**:
For the local file to be updated with the given patch

**How to reproduce it (as minimally and precisely as possible)**:
kubectl patch --local -o yaml -f YOUR_FILE_NAME -p YOUR_PATCH_HERE

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6
- Cloud provider or hardware configuration: Google Cloud console
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Linux cs-6000-devshell-vm-910dec8e-3555-4604-adc1-47728685a429 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by frankh** [comment]
Just wanted to add that I'm experiencing this bug too

**Comment by ChrisTerBeke** [comment]
/remove-lifecycle stale

:(

**Comment by opatroll** [comment]
With v1.12 it works without a server for me, with v1.11 it doesn't.

**Comment by ChrisTerBeke** [comment]
Haven't tried 1.12, but good to know a patch might be in place. Any k8s contributors that can update the status here?

**Comment by trevex** [comment]
I do not think this is completely resolved, because patch with `--local` on v1.12 seems to not support anything other than `--type=json`.

**Comment by fabianotessarolo** [comment]
@ChrisTerBeke have you tried this way:

E.g:
```bash
kubectl patch --local -o yaml -f kubernetes/deployments/helloworld.yaml -p "$(cat patch.yaml)" > helloworld.yaml
```

**Comment by ChrisTerBeke** [comment]
> @ChrisTerBeke have you tried this way:
> 
> E.g:
> 
> ```shell
> kubectl patch --local -o yaml -f kubernetes/deployments/helloworld.yaml -p "$(cat patch.yaml)" > helloworld.yaml
> ```
> 
> Here I'm using kubectl v1.13.2

This seems to work indeed. Since I've opened this ticket I moved to using simple `sed` commands instead, but I'll maybe give this a try again.

**Comment by etcshad0vv** [comment]
> @ChrisTerBeke have you tried this way:
> 
> E.g:
> 
> ```shell
> kubectl patch --local -o yaml -f kubernetes/deployments/helloworld.yaml -p "$(cat patch.yaml)" > helloworld.yaml
> ```
> 
> Here I'm using kubectl v1.13.2

But what is the point of using output and stream redirection, `--local` is not supposed to work on the contents of the file?
