### ISSUE TITLE
Kubelet device plugin APIs: Deallocate

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#59110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig node
/area hw-accelerators

**What happened**:
At the moment Device Plugin APIs are handling only `Allocate` stage.
Device plugins are not aware and not receiving events when Pod/Containers are stopping using particular device.

**What you expected to happen**:
We need to have `Deallocate` part of the API, even were for many devices that are currently in use it will be no-Op stub. 

Reasons and usage scenarios for `Deallocate`:

- Power management: in case of accelerators that are not always depending on controlling process from userland side (e.g. FPGA which has external network/GPIO interfaces) it is possible that after stopping of Pod where device was initially allocated, accelerator part of the code will be still processing data on external interfaces and consume significant amount of power. As we don't know when it will be next time allocated, it will be better to reset accelerator device and put it into power saving mode immediately after workload that requested it is terminated.
- Security: hw-accelerators often have internal memory and processing data not always cleared after processing. Doing reset/memory clean-up on next `Allocate` call means that between two points of time (termination of workload and next `Allocate`) some confidential information can be still present on the device (e.g. IPsec encryption keys, for crypto accelerators). It is better to have ability to cleanup device memory as soon as workload that requested it finishes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
cc: @RenaudWasTaken @ns-sundar @sameo

**Comment by RenaudWasTaken** [comment]
/cc @vishh @jiayingz @vikaschoudhary16 

Hello @kad !

Thanks for opening this issue! In general I'm in favor of adding a `Deallocate` call.

We do need to discuss what is the expected behavior in case of a crash. i.e: Do we want at most once of at least once call of that.
Currently the Allocate call has at least once behavior so it would make sense to have this call be the same.

In terms of implementation, @jiayingz and @vishh might have more insights than me, but I was thinking of hooking into the Kuberuntime pre-stop hook, and maybe have a path at container start to handle reboot ?

**Comment by vikaschoudhary16** [comment]
Or may be we would want to name it `DeInitialize`?


> We do need to discuss what is the expected behavior in case of a crash. i.e: Do we want at most once of at least once call of that.

@RenaudWasTaken IIUC, you are talking about container crash here. If a container crashes, does pre-stop hook get invoked? I am not sure on this.

To keep the behavior consistent with `Initialize`, may be we can use the same indication, `InitRequired` received from  DP, to decide on what all events to invoke `DeInitialize`.

**Comment by RenaudWasTaken** [comment]
> Or may be we would want to name it DeInitialize?

How about "Terminate"?

>>We do need to discuss what is the expected behavior in case of a crash. i.e: Do we want at most once of at least once call of that.

> @RenaudWasTaken IIUC, you are talking about container crash here. If a container crashes, does pre-stop hook get invoked? I am not sure on this.

No kubelet crash.

**Comment by fabiand** [comment]
We'd actually laos like to see this. For network devices it's helpful in order to clean them up once a network ns goes away.

**Comment by peter-bitfusion** [comment]
:+1:  Deallocation would be really helpful for us as well. is there any progress or plans around this?

**Comment by bart0sh** [comment]
@RenaudWasTaken @kad @rescuer  @jiayingz @vishh 

I have some time to implement this. Any suggestions on how to do it the best way?

**Comment by jiayingz** [comment]
Thanks a lot for your interests, @bart0sh 

Before we start the implementation, there are some questions I think we may want to discuss first.
- First, say if we add this API, should it be called before or after container stop? Or should it be called before or after pod stop?
- Second, if we add this API, should it be best effort or mandatory? I.e., if Deallocation fails, should we prevent the container/pod from being stopped? We currently garbage collect unused devices lazily by monitoring active pod list. It may be hard for us to implement mandatory Deallocation. If we implement Deallocation as best effort, it may not longer suit some of the listed use cases.

I would like to hear opinions on these questions from the folks who require this feature.

**Comment by fabiand** [comment]
We would like to see Deallocate in our KubeVirt DPs.

First, to us Deallocated would be helpful after container stop - i actually think this is relevant, because otherwise the workload can still be running.

Second, optional implementation sounds good - some need it (network devices) others don't.

@mpolednik @phoracek do you have more insights?

**Comment by RenaudWasTaken** [comment]
> So, if plugin was not able to properly deinitialise device, it should be changing health state for this device. Kubelet in that case will not be blocked and will not have complex error handling code. And plugin will be responsible for performing all needed steps in background to move device from unhealthy to healthy state.

I'm not sure we want to introduce the notion of Kubelet changing the device health state without the device plugin being aware of it.
That would either require us to introduce a mechanism to notify the device plugin that we changed the state of a device or (if we decide not to notify the device plugin) prevent the device plugin from taking actions to put this device in a correct state.

IMHO, the "best" solution would be to ignore it and leave it to the device plugin vendor to decide whether or not to notify kubelet that the device is in an unhealthy state.

**Comment by kad** [comment]
@RenaudWasTaken by changing health status, I mean as part of DP Deallocate code flow. So, instead of returning error code, Deallocate function inside plugin will change internal status of device to unhealthy. Not kubelet.

**Comment by jiayingz** [comment]
Thanks a lot for the inputs!

From the discussions so far, it sounds people feel Deallocation notification should be at container level and can tolerant certain delays and failures. In that case, I wonder whether this notification has to be sent from device plugin API or may be learned from other interface. E.g., for device monitoring, we have been discussing whether we may want to export device to pod/container binding information through a file API, and I wonder whether device de-allocation information can be learned through similar approach. Generally, I would prefer to not adding too many gRPC API functions. Even though we can say a gRPC function is optional, people still need to implement it when they sync to that API version.

**Comment by jiayingz** [comment]
@RenaudWasTaken no, I mean not-in-use device information may be learned from other interface, like a file API, if that is also used to support device monitoring.

**Comment by RenaudWasTaken** [comment]
> @RenaudWasTaken no, I mean not-in-use device information may be learned from other interface, like a file API, if that is also used to support device monitoring.

I think the request here is about doing `Deallocate` after container stop. Additionally I'm not sure we can extrapolate "not-in-use" = `Deallocate`.

Furthermore, I'm not sure we want to decide the `Deallocate` strategy based on an undecided monitoring API.

Finally it seems like the Device Plugin API is the correct API to add this call. Device specific operations at certain point of the container / pod lifecycle clearly are something that the DPA is meant to address.

**Comment by RenaudWasTaken** [comment]
> Even though we can say a gRPC function is optional, people still need to implement it when they sync to that API version.

We can and should advertise the two versions of the API (i.e: the version without the `Deallocate` call and the version with the additional `Deallocate` call) on the Kubelet socket.

That would not require old Device Plugin to implement the new API to work with a new version of K8s.

**Comment by kad** [comment]
@jiayingz I agree with @RenaudWasTaken : for me, device plugin API is the right spot to have Deallocate call. There are several reasons for that. One is about overall design that Kubelet is the ultimate decision maker on which devices are available and which are in use. Having some monitoring code that will be not aware about Kubelet state for device, and for kubelet not aware of monitoring state tracking sounds like a duplication of functionality. Second reason is about possibility of race conditions: monitoring code can be still doing something for device deallocate phase, and kubelet already be in the process of next Allocate for the same device.

Beside that, why to invent another interface if we already have gRPC interface between kubelet and device plugin ?

In overall, I think the piece of code inside kubelet that marks device as available for Allocate() is the right spot to call plugin to inform that device is released by workload and that device should be cleaned after usage, before we can allocate it for next container.

**Comment by jiayingz** [comment]
I also thought about allocation and de-allocation race problem, and it is actually one of the reasons I would prefer to not adding Deallocate into the device plugin gRPC API. To avoid single-point bottleneck, all of the gRPC calls in DeviceManager are not protected by any mutex lock. Now think about this scenario: Kubelet DeviceManager first gets a notification that containerA no longer uses device1 and sends a Deallocate gRPC call to that device plugin. Then it gets a device allocation request for a new containerB and device1 is the only available device for that resource. Now what should DeviceManager do? Should we block new Allocate request till Deallocate gRPC finishes? But as I mentioned, currently all gRPC calls are not protected by an mutex lock. Even though we may add some synchronous mechanism to block Allocate request, is it really desirable? We just discussed that Deallocate failure shouldn't block new allocation requests. Also if kubelet fails at this time, it is really hard for DeviceManager to know whether it needs to re-issue Deallocate gRPC calls or not when it comes back. Basically, if we add this API, it is hard to provide any guarantees on the synchronization between Allocate and Deallocate. We also can't provide any guarantee that a Deallocate call will be sent exactly once as Kubelet can't guarantee container stop event will be detected only once. If we add an API without well-defined guarantees, I am afraid that would more likely confuse people and be mis-used.

Btw, we probably want to refer this operation as PostStopContainer, as currently in DP API, Allocate is a pod-level operation. I noticed the comments above Allocate function is out-of-sync and will send a PR to fix it.

**Comment by kad** [comment]
@jiayingz regarding race condition: we have piece of code that adds device to allocatable pool in pkg/kubelet/cm/devicemanager/manager.go (updateAllocatedDevices). IMHO, Deallocate should be called in that function for all devices in the difference between previous state and new state (`m.allocatedDevices = m.podDevices.devices()`). This will make sure that deallocate will be called before any new allocate request for this device can be possible done. Regarding once/multiple times, I think in case deallocate() it is fine to call it multiple times. However, if we are looking at function I mentioned above, I don't see cases where it will be called multiple times: we have previous state of mapped devices to pods, and we have new actual state. we need just to run deallocate for all difference in those two states. Allocate will not be really blocked at this step, list of available/healthy devices will be just at that time smaller while deallocate performs operation.

**Comment by RenaudWasTaken** [comment]
> Kubelet DeviceManager first gets a notification that containerA no longer uses device1 and sends a Deallocate gRPC call to that device plugin. Then it gets a device allocation request for a new containerB and device1 is the only available device for that resource.

So the problem I'm seeing right now (correct me if I'm wrong) is that there is no "formal" Pod Stopped lifecycle event and it leads to the `Deallocate` call needing to be called in the `PodAdmit` (and thus being blocking).
I don't think there really is a race, we just need to figure out the lifecycle story.

I see two solutions:
- Reject the pod
- Try to implement the "Pod Stopped" event 
   - This might require a lot more work and seems to have a pretty large scope
   - On the other hand it seems the most sensible option because one of the goal is to shutdown a device to save power

> Also if kubelet fails at this time, it is really hard for DeviceManager to know whether it needs to re-issue Deallocate gRPC calls or not when it comes back.

Not really it comes back to my first question about the mechanism in case of crash: Do we want at most once or at least once call?

At least once seems the most reasonable mechanism for our use case and easy to implement: after a `Deallocate` just write to the checkpoint file.

**Comment by vikaschoudhary16** [comment]
My preferred approach for deallocate is to handle it out of kubelet or gRPC interface to keep things simple. Lets assume device plugin knows pod-to-device mapping, either it is through a file based contract b/w kubelet and device plugins or by passing pod-id in Allocate or some other way. Next device plugin can keep watching k8s api server for a [DELETED event](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/watch/watch.go#L46) on the pod object for each of the   pod-to-device mapping. In the event handling deallocate will be performed. One possible deallocate behavior could be to advertise Unhealthy state for the device under deallocate and if still receives Allocate for the same device, return error in response to the kubelet.

**Comment by RenaudWasTaken** [comment]
> My preferred approach for deallocate is to handle it out of kubelet or gRPC interface to keep things simple. Lets assume device plugin knows pod-to-device mapping, either it is through a file based contract b/w kubelet and device plugins or by passing pod-id in Allocate or some other way.

Let's not introduce a parallel API to the device plugin for pod / container lifecycle events.

> Next device plugin can keep watching k8s api server for a DELETED event on the pod object for each of the pod-to-device mapping. In the event handling deallocate will be performed.

That seems to me like it breaks the API responsibilities. Additionally even if we move the Deallocate at the pod level, we can't just watch the `Deleted` event as a Pod can end up in multiple other states before it's deleted: {Succeeded, Failed, Unknown}.
For example in the case of a Job, it'll tend to be deleted a lot later after it's finished.

There is a clear need for the `Deallocate` operation to be issued by Kubelet before it puts back the Device in the available pool.
If this is done by an alternative API where Kubelet doesn't issue the call, you find yourself handling races that defeat the purpose of that call.

**Comment by kad** [comment]
> There is a clear need for the Deallocate operation to be issued by Kubelet before it puts back the  Device in the available pool.
> If this is done by an alternative API where Kubelet doesn't issue the call, you find yourself handling races that defeat the purpose of that call.

I totally agree here with @RenaudWasTaken. We can call it differently than `Deallocate()`, name doesn't really matter. What matters is that Kubelet informs plugin that device is not anymore in use and that Kubelet is going to put device back into the pool of allocatable devices.

**Comment by vikaschoudhary16** [comment]
> Let's not introduce a parallel API to the device plugin for executing pod / container lifecycle events.

This is a no-api solution. Anyways from the comments above i can see that we all agree that Kubelet does not expect a return value from DeAllocate.

> Pod can end up in multiple other states before it's deleted: {Succeeded, Failed, Unknown}.
For example in the case of a Job, it'll tend to be deleted a lot later after it's finished.

Did you mean to say pod's container may end in multiple other states before pod gets deleted? 
Devices gets allocated at Pod level and even during container restarts, are still allocated. If we deallocate at container stop, we will have to issue Allocate as well again for each container restart. Do we want this behavior? 

Today, reclaim of devices happens lazily but it still happens at pod level. Approach that i suggested will just make it happen quicker and proactively.

**Comment by vikaschoudhary16** [comment]
> What matters is that Kubelet informs plugin that device is not anymore in use and that Kubelet is going to put device back into the pool of allocatable devices.

kubelet should not put device back in allocatable until Deallocate is not completed and to ensure this we will have to wrap gRPC calls in mutex. This could increase latency at UI.

**Comment by RenaudWasTaken** [comment]
> kubelet should not put device back in allocatable until Deallocate is not completed and to ensure this we will have to wrap gRPC calls in mutex. This could increase latency at UI and more complexity in device manager


- As mentioned higher you don't have to issue the `Deallocate` calls during pod admission.
- Additionally if you are not putting the devices in `Available` you don't need to lock `Allocate` and `Deallocate`
- Note that these calls are not ran in parallel so this won't increase latency.

> If we deallocate at container stop, we will have to issue Allocate as well again for each container restart. Do we want this behavior?

This simple model should be enough to cover our use cases:
![capture](https://user-images.githubusercontent.com/2519571/38423759-214e843e-39af-11e8-80a0-ccf08584ae83.PNG)

**Comment by kad** [comment]
> kubelet should not put device back in allocatable until Deallocate is not completed and to ensure this we will have to wrap gRPC calls in mutex. This could increase latency at UI and more complexity in device manager

In theory, we can workarround that. Correct me if I'm wrong:
- We have `updateAllocatedDevices()`. Code there uses mutex that is hold while list is updated. Here we just need to calculate difference and store it. Not long lock.
-  We can introduce here new list that will be serving as "deallocate" queue. Then, we can make goroutine to call gRPC in non-blocking way. Once gRPC call finished, device is removed from that list. Removal from queue list can be covered with lock, but gRPC call itself will be outside of mutex lock.
- In `devicesToAllocate`  we have code that calculates difference between available healthy devices (`m.healthyDevices`) and `m.allocatedDevices`. here we will need to add condition that  also count devices that are still in queue for gRPC call.

This way it should not cause UI latency, I think ?

**Comment by vikaschoudhary16** [comment]
@kad But this approach does not guarantee that deallocate will be invoked after container stop. This seems another form of lazy reclaim. 
I and @RenaudWasTaken had a small discussion on slack regarding an alternate approach. I would request you to please share your opinion there and once we have some level of consensus, may be we can create a proposal draft.

**Comment by klueska** [comment]
This issue has been raised once again in the form of a PR: https://github.com/kubernetes/kubernetes/pull/87223

**Comment by yuguorui** [comment]
> I just want to mention that I'm not aware of any scenario where hard sync Deallocate would be requirement for a network DP (correct me if I'm wrong). Virtual network interfaces are removed together with netns, physical interfaces are moved back to host netns and their IP configuration is removed. Deallocate functionality could be handled via Pod monitoring, but for convenience, any Deallocate API would make DP implementation easier.

In fact, there is currently no available public API in k8s to find the device corresponding to a pod. You can find the type of device a pod needs, but you can't find which device it is.

**Comment by RenaudWasTaken** [comment]
@yuguorui you should look at the podresources gRPC API, I'm pretty sure it does what you are looking for :) !

**Comment by yuguorui** [comment]
> @yuguorui you should look at the podresources gRPC API, I'm pretty sure it does what you are looking for :) !

Thanks for your advice!

**Comment by middlestone** [comment]
> 
> 
> /cc @vishh @jiayingz @vikaschoudhary16
> 
> Hello @kad !
> 
> Thanks for opening this issue! In general I'm in favor of adding a `Deallocate` call.
> 
> We do need to discuss what is the expected behavior in case of a crash. i.e: Do we want at most once of at least once call of that.
> Currently the Allocate call has at least once behavior so it would make sense to have this call be the same.
> 
> In terms of implementation, @jiayingz and @vishh might have more insights than me, but I was thinking of hooking into the Kuberuntime pre-stop hook, and maybe have a path at container start to handle reboot ?

@RenaudWasTaken  preStop is called when the pod/job is terminated. It is not getting called when the pod is completed successfully, so if we want to release network device after job completed, it seems that preStop is not a good workaround.
Before deallocate is merged, or for old version of kubernetes, do you have any suggestion? thanks in advance.

**Comment by bart0sh** [comment]
@middlestone if you're interested in this topic please consider recent activity here https://github.com/kubernetes/enhancements/pull/1949

**Comment by middlestone** [comment]
@bart0sh thanks, I am really interesting in device plugin for network devices.
