### ISSUE TITLE
hostname is not present in /etc/hosts

### ISSUE THREAD

**Issue by mpashka** [kubernetes/kubernetes#59112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Under some circumstances I get error in pod running elasticsearch that pod can't get local hostname. That is because local host name (pod name) was absent in /etc/hosts

**What you expected to happen**:
Local host name must be present in /etc/hosts to allow local host resolving.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not 100% sure, may be that issue started after assigning pods to another node because of node unavailability. 

**Anything else we need to know?**:
Elasticsearch (java) stack trace:
```
2018-01-31 13:58:16,381 main ERROR Could not determine local host name java.net.UnknownHostException: es-client-48892288-l844b: es-client-48892288-l844b: System error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:53)
...
Caused by: java.net.UnknownHostException: es-client-48892288-l844b: System error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
...
```
pod info:
```
Name:		es-client-48892288-l844b
Namespace:	logging
Status:		Running
IP:		
...
Events:
  2h		7s		636	kubelet, lga-kubnode06	spec.containers{es-client}	Warning		BackOff		Back-off restarting failed container
  2h		7s		636	kubelet, lga-kubnode06					Warning		FailedSync	Error syncing pod

```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Vmware VMs
8x Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Mem: 12G

- OS (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core) 

- Kernel (e.g. `uname -a`):
Linux 3.10.0-693.2.2.el7.x86_64

- Install tools:
Manually installed

- Others:

**Comment by chengyli** [comment]
We saw similar problem after kubernetes was upgraded from 1.6 to 1.7, and it seems that the container is using the hosts file from `/var/lib/docker/containers/<pause-container-id>/hosts` but not the hosts of pod `/var/kubelet/pods/<pod-id>/etc-hosts`. 

```
$ kubectl exec -it monstorservice  bash
bash-4.3# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```

Version information,
kubernetes: v1.7.4
OS: CentOS 7.3
Docker: 1.12.6
