### ISSUE TITLE
pkg/apis/core/validation/validation_test.go need a spliting and refactoring

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#59123]
1) The file with tests is huge (and the `validation.go` too):

```console
$ wc -l pkg/apis/core/validation/validation_test.go 
12227 pkg/apis/core/validation/validation_test.go
$ wc -l pkg/apis/core/validation/validation.go
4929 pkg/apis/core/validation/validation.go
```

I'd suggest to split them to a set of files.

2) Many tests could continue to work even if the code is broken.

In many places we have a check like this: `len(errs) == 0` that always succeed if at least one, not matter which one, error is present. We should test for the expected error message instead.

Related to https://github.com/kubernetes/kubernetes/issues/56230

@thockin WDYT? If you agree, I'll probably could start to slowly refactor them.

/kind cleanup
/area test

**Comment by PI-Victor** [comment]
could definitely work on this, after some feedback of course.

**Comment by php-coder** [comment]
As there is neither objections nor agreement, I suggest to use trial&error path. We can extract some tests from `validation_test.go` based on some rule and suggest to merge such a change. If it merges, then we're on the right way and subsequent PRs also will be accepted.

CC @marrrvin in case you're interested in try to do that :)

**Comment by marrrvin** [comment]
@php-coder I am in :)
