### ISSUE TITLE
Generator for CRD Validation Schema

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/kubernetes#59154]
Currently, a `CustomResourceDefinition` can define validation via an OpenAPI v3 Schema. As talked about in #59151, When CRDs to go GA, any field specified in a custom resource that is not allowed according to the provided OpenAPI v3 scheme will be ignored. This will require that a validation schema be robust. 

The lines of code required to define such a schema can quickly become very large. Hence, it would be helpful if a generator were created for such a task. It is my understand that the pieces to accomplish this are already present and just need to be pieced together.

/sig api-machinery
/area custom-resources
/kind feature
/assign

/cc @sttts @deads2k @liggitt @ash2k @mbohlool @lavalamp @jennybuckley @munnerz @colemickens @nikhita

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/code-generator/issues/28, https://github.com/kubernetes/sample-controller/issues/2.

**Comment by munnerz** [comment]
I've started putting this together and have a working prototype. I'll be making a PR shortly to get some discussion going.

We're likely going to need to add some new comment tags so we can set a string regex etc. for fields. How flexible do we want to be with this? Should the output of this tool serve as a basis to build your CR upon, or should we be using it in a `generate`/`validate-in-ci` fashion like other generators?

**Comment by munnerz** [comment]
I've opened https://github.com/kubernetes/kube-openapi/pull/37 which adds support for generating the openapiv3 json spec. It could easily be reworked into something re-usable to build a fully-fledged CRD generator.

What do people think? Generating the entire resource could be pretty useful, especially if the generator could then be run by `generate-groups.sh` (or its successor).

Should this turn into `Generator for CustomResourceDefinitions`?

**Comment by frankgreco** [comment]
In my opinion, I see the majority of uses cases for this being in the context of creating a crd resource via code. Hence, I think it makes the most sense to generate the entire crd struct (maybe using a method in my above comment). We could then place the generated crds in maybe `pkg/crds/group_name/version/crds.go`

I would love to hears other opinions :)

**Comment by wild-endeavor** [comment]
Any update on this?

**Comment by lavalamp** [comment]
The kube-openapi repo now has a binary that can theoretically do this transformation. I intend to have this added as one of the output artifacts. We have to upconvert from OpenAPI v2 to v3 first though.

**Comment by wild-endeavor** [comment]
sorry, which is the binary?  I don't think I'm looking in the right place.

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kube-openapi/blob/master/cmd/openapi-gen/openapi-gen.go

The paint is still wet. It doesn't do this *yet*, just to be clear.

**Comment by wild-endeavor** [comment]
Got it yeah.  I `go built` that already and ran it on my `types.go` but the only thing that that produced was the openapi go files, not the json validation spec.  (What are those files used for by the way?  These types are coming from a CRD/custom operator - is the point to make the API show up under `swagger.json` somehow?)

In any case, what do we think is the rough timeline for the validation bit?  Weeks or months or indefinite?

**Comment by lavalamp** [comment]
Right, it doesn't make the json validation spec *yet*--future work. But now we have a place to put that code!

I wonder if @pwittrock has someone who might be interested in working on this? Basically the step needed for an MVP is to convert openapi v2 to v3.

**Comment by mestery** [comment]
I'm very much interested in this as well, just curious on it's current status.

**Comment by lavalamp** [comment]
I did a similar thing here that might serve as a good pattern, if someone wants to give it a shot: https://github.com/kubernetes/kube-openapi/tree/master/cmd/openapi2smd

This is still on my list but not at the top :/

**Comment by lavalamp** [comment]
re: nullable

@apelisse / @mbohlool  does OpenAPI distinguish null from not present?

**Comment by apelisse** [comment]
> does OpenAPI distinguish null from not present?

yes it does. A required field can be null, an optional integer field can't be null (unless it's "nullable")

**Comment by munnerz** [comment]
kubebuilder has separated out their own CRD generator into the `sigs.k8s.io/controller-tools` repo: https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/crd

If you `go get sigs.k8s.io/cmd/crd`, you should then be able to run `crd generate --domain example.com` from the root of your project to generate entire CRD resources 😄 

You can see an example of it in action in the cert-manager repo: https://github.com/jetstack/cert-manager/pull/1322

I think this means this issue can be closed now, as the core of it seems to be resolved :tada:

/close

**Comment by artbegolli** [comment]
> kubebuilder has separated out their own CRD generator into the `sigs.k8s.io/controller-tools` repo: https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/crd
> 
> If you `go get sigs.k8s.io/cmd/crd`, you should then be able to run `crd generate --domain example.com` from the root of your project to generate entire CRD resources 😄
> 
> You can see an example of it in action in the cert-manager repo: [jetstack/cert-manager#1322](https://github.com/jetstack/cert-manager/pull/1322)
> 
> I think this means this issue can be closed now, as the core of it seems to be resolved 🎉
> 
> /close

An update for anybody who's looking to generate crds and found this link dead - this feature has been added to controller-gen here - https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen

Usage:

* `go get sigs.k8s.io/controller-tools/cmd/controller-gen`
* `controller-gen crd paths=<PATH_TO_TYPES_DIR>`
