### ISSUE TITLE
Probing container should *not* be restarted with a /healthz http liveness probe [Conformance] {E2eNode Suite}

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#59150]
We have noticed few months ago that this test flaked again(https://github.com/openshift/origin/issues/12072#issuecomment-335311564)

 Opening this issue again to start dicussion on the test.

Following are my observations after going through history and logs :
- We are bringing up a nginx container and trying to check if <container_IP:80> is available.
 - While this is not a bad idea, there are many things that could go wrong because of which nginx may not come to running. Some of them could be related to underlying infrastructure on which we have no control over, some could be related to network plugin being used etc. Some were mentioned in kubernetes/kubernetes#30714 (comment) as well.
    For example, the latest one failed with dial tcp 10.128.1.69:80: getsockopt: no route to host. This could be related to network setup as well.
-   This makes the test indeterministic and therefore flaky.

Since the goal this test is to check that a good container won't restart based on liveness probe, would it make sense to add a liveness command that checks for the existence of a particular directory that was created during container start up or something else instead of a HTTP GET.

/sig node
cc @Random-Liu

**Comment by tianshapjq** [comment]
[configure liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)
not sure if this is helpful, but to my understanding, this is technically already supported as described in this page. You just have to figure out which probe you need most, either httpGet or exec.

**Comment by ravisantoshgudimetla** [comment]
@tianshapjq It is not about configuring which probe to use. The problem is with test case flaking out and it flakes for what I believe could be an infrastructure related issue. I raised this issue to ensure that everyone is ok switching to exec from httpGet.

**Comment by ravisantoshgudimetla** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/container_probe.go#L114 - I just noticed that we already have a test which does exec liveness probe test. Do we still need this test? If not, can we delete it or increase timeouts?

**Comment by fejta** [comment]
@kubernetes/sig-node-test-failures
