### ISSUE TITLE
Node e2e serial local storage capacity isolation tests are failing

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#59155]
/kind bug

https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e

Example failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/3609

Pods that should be using less than their limits are being evicted for exceeding them.  These tests were passing before being moved to the serial suite from the flaky suite.

The only thing I can think of off the top of my head is that the GPU test adds something to containers that takes disk space.
cc @mindprince is that a possibility?

/sig node
/assign
/priority important-soon

**Comment by dashpole** [comment]
cc @kubernetes/sig-node-test-failures

**Comment by dashpole** [comment]
A container that hasn't written anything to disk on cos-63 (non-failing) reports a usage of 8192 bytes (8 kb), but a container that hasn't written anything to disk on cos-60 (failing) reports usage of 1318912 bytes (1.3 mb).  So something is added to these containers before the test starts writing to the container's writable layer.

**Comment by mindprince** [comment]
I don't think the GPU stuff should affect anything. But cc @jiayingz who worked on the node-e2e after me.

**Comment by jiayingz** [comment]
Agree with @mindprince that GPU e2e_node test doesn't seem to do anything that would affect disk usage.

**Comment by yujuhong** [comment]
According to the [test job configs](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/image-config-serial.yaml),  cos-stable2 is the only image using a different configuration: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/gci-init-gpu.yaml

Maybe that's relevant.

**Comment by dashpole** [comment]
I did confirm that the yaml file https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/gci-init-gpu.yaml is what is adding some directories to an empty container.
The directories added are:
`dev/`
--->`console`
--->`pts/`
--->`shm`
`etc/`
--->`hostname`
--->`hosts`
--->`mtab`
--->`resolve.conf`
`proc/`

all files and folders are empty, except `etc/mtab`, which appears to contain a bunch of mounts.

**Comment by dashpole** [comment]
It looks like we are double counting the writable layer (du run from the path we are using to monitor container disk usage, in a container that has written 100Mb, 102400Kb to disk):
`$ du .`
`4       ./upper/dev/pts`
`4       ./upper/dev/shm`
`12      ./upper/dev`
`4       ./upper/sys`
`4       ./upper/proc`
`4       ./upper/etc`
`102428  ./upper`
`4       ./merged/home`
`4       ./merged/dev/pts`
`4       ./merged/dev/shm`
`12      ./merged/dev`
`1136    ./merged/bin`
`4       ./merged/var/www`
`4       ./merged/var/spool/mail`
`8       ./merged/var/spool`
`16      ./merged/var`
`4       ./merged/tmp`
`4       ./merged/usr/sbin`
`8       ./merged/usr`
`4       ./merged/root`
`4       ./merged/etc/network/if-pre-up.d`
`4       ./merged/etc/network/if-post-down.d`
`4       ./merged/etc/network/if-up.d`
`4       ./merged/etc/network/if-down.d`
`20      ./merged/etc/network`
`40      ./merged/etc`
`4       ./merged/sys`
`4       ./merged/proc`
`103636  ./merged`
`4       ./work/work`
`8       ./work`
`206080  .`

No idea how we didn't catch this a long time ago... https://github.com/google/cadvisor/pull/1882 will fix this.

**Comment by dashpole** [comment]
This test now passes after https://github.com/kubernetes/kubernetes/pull/59595 was merged, which included google/cadvisor#1882
