### ISSUE TITLE
kube-proxy ipvs mode create unnecessary ip virtual server listener for k8s services

### ISSUE THREAD

**Issue by vincentmli** [kubernetes/kubernetes#59156]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
when running kube-proxy with ipvs mode, kube-proxy creates unnecessary ip virtual server listener for 
all local ip addresses on the node when the node has multiple interfaces with ip addresses

for example:

I have node with ip address below, only ip 192.168.1.3 is the actual node ip and part of k8s node network

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:a3:c8:7c brd ff:ff:ff:ff:ff:ff
    inet 10.3.72.11/16 brd 10.3.255.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::77cb:be1c:dc24:8adb/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::40:45d:be44:aef3/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:3b:51:d3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global ens4
       valid_lft forever preferred_lft forever
    inet6 fe80::f70a:7bac:ac1d:2a13/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::b2da:acea:1527:a657/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:61:06:49 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:61:06:49 brd ff:ff:ff:ff:ff:ff
6: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether a6:8c:e4:23:28:64 brd ff:ff:ff:ff:ff:ff
7: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 6e:2c:88:6f:44:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/32 brd 10.0.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.0.0.10/32 brd 10.0.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.0.0.144/32 brd 10.0.0.144 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
8: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 02:42:dd:8d:a7:53 brd ff:ff:ff:ff:ff:ff
    inet 172.16.58.1/24 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:ddff:fe8d:a753/64 scope link
       valid_lft forever preferred_lft forever

[root@fed-master kubernetes]# cluster/kubectl.sh get no -o wide
NAME          STATUS    ROLES     AGE       VERSION                                    EXTERNAL-IP   OS-IMAGE                 KERNEL-VERSION           CONTAINER-RUNTIME
192.168.1.3   Ready     <none>    2h        v1.10.0-alpha.2.185+1150de9ce65775-dirty   <none>        Fedora 26 (Twenty Six)   4.11.8-300.fc26.x86_64   docker://1.13.1
fed-node2     Ready     <none>    2h        v1.7.3                                     <none>        Fedora 26 (Twenty Six)   4.11.8-300.fc26.x86_64   docker://1.13.1

[root@fed-master kubernetes]# cluster/kubectl.sh get po -o wide
NAME          READY     STATUS    RESTARTS   AGE       IP            NODE
nginx-2rhmk   1/1       Running   0          2h        172.16.58.3   192.168.1.3
nginx-prfjq   1/1       Running   0          2h        172.16.54.2   fed-node2

[root@fed-master kubernetes]# cluster/kubectl.sh get svc -o wide
NAME           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE       SELECTOR
kubernetes     ClusterIP   10.0.0.1     <none>        443/TCP        2h        <none>
nginxservice   NodePort    10.0.0.144   <none>        80:32506/TCP   2h        app=nginx

as you can see, ipvs mode create unnecessary listener for all local ip addresses

[root@fed-master kubernetes]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.16.58.1:32506 rr <====not sure if this one is needed
  -> 172.16.54.2:80               Masq    1      0          0
  -> 172.16.58.3:80               Masq    1      0          0
TCP  192.168.1.3:32506 rr   <=====this one is needed
  -> 172.16.54.2:80               Masq    1      0          12
  -> 172.16.58.3:80               Masq    1      0          12
TCP  192.168.122.1:32506 rr <==========this is link virbr0 ip, not needed
  -> 172.16.54.2:80               Masq    1      0          0
  -> 172.16.58.3:80               Masq    1      0          0

TCP  10.0.0.144:80 rr <=====not sure if this one needed
  -> 172.16.54.2:80               Masq    1      0          0
  -> 172.16.58.3:80               Masq    1      0          0
TCP  10.3.72.11:32506 rr <====this is node management network ip, not needed
  -> 172.16.54.2:80               Masq    1      0          0
  -> 172.16.58.3:80               Masq    1      0          0
TCP  127.0.0.1:32506 rr <=====do we need this one?
  -> 172.16.54.2:80               Masq    1      0          0
  -> 172.16.58.3:80               Masq    1      0          0

**What you expected to happen**:

I would expect kube-proxy mode only created ip virtual listener on node ip for k8s services only, not for dummy interface virbr0 or management network ip

**How to reproduce it (as minimally and precisely as possible)**:

run kube-proxy with ipvs mode and create k8s service

**Anything else we need to know?**:
kube-proxy ipvs mode pkg/proxy/ipvs/proxier.go  has code comment below, maybe we need to re-think about the  node ip set design

// NodeIPs returns all LOCAL type IP addresses from host which are taken as the Node IPs of NodePort service.
// Firstly, it will list source IP exists in local route table with `kernel` protocol type.  For example,
// $ ip route show table local type local proto kernel
// 10.0.0.1 dev kube-ipvs0  scope host  src 10.0.0.1
// 10.0.0.10 dev kube-ipvs0  scope host  src 10.0.0.10
// 10.0.0.252 dev kube-ipvs0  scope host  src 10.0.0.252
// 100.106.89.164 dev eth0  scope host  src 100.106.89.164
// 127.0.0.0/8 dev lo  scope host  src 127.0.0.1
// 127.0.0.1 dev lo  scope host  src 127.0.0.1
// 172.17.0.1 dev docker0  scope host  src 172.17.0.1
// 192.168.122.1 dev virbr0  scope host  src 192.168.122.1
// Then cut the unique src IP fields,
// --> result set1: [10.0.0.1, 10.0.0.10, 10.0.0.252, 100.106.89.164, 127.0.0.1, 192.168.122.1]

// NOTE: For cases where an LB acts as a VIP (e.g. Google cloud), the VIP IP is considered LOCAL, but the protocol
// of the entry is 66, e.g. `10.128.0.6 dev ens4  proto 66  scope host`.  Therefore, the rule mentioned above will
// filter these entries out.

// Secondly, as we bind Cluster IPs to the dummy interface in IPVS proxier, we need to filter the them out so that
// we can eventually get the Node IPs.  Fortunately, the dummy interface created by IPVS proxier is known as `kube-ipvs0`,
// so we just need to specify the `dev kube-ipvs0` argument in ip route command, for example,
// $ ip route show table local type local proto kernel dev kube-ipvs0
// 10.0.0.1  scope host  src 10.0.0.1
// 10.0.0.10  scope host  src 10.0.0.10
// Then cut the unique src IP fields,
// --> result set2: [10.0.0.1, 10.0.0.10]

// Finally, Node IP set = set1 - set2

**Environment**:
- Kubernetes version (use `kubectl version`): 

[root@fed-master kubernetes]# cluster/kubectl.sh version

Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.2.185+1150de9ce65775-dirty", GitCommit:"1150de9ce657758360bb19202e3382fd657bf83e", GitTreeState:"dirty", BuildDate:"2018-01-31T18:57:28Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.2.185+1150de9ce65775-dirty", GitCommit:"1150de9ce657758360bb19202e3382fd657bf83e", GitTreeState:"dirty", BuildDate:"2018-01-31T18:57:28Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: none

locally running k8s
https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md

- OS (e.g. from /etc/os-release):

[root@fed-master kubernetes]# cat /etc/os-release
NAME=Fedora
VERSION="26 (Twenty Six)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Twenty Six)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy

- Kernel (e.g. `uname -a`):

Linux fed-master 4.11.8-300.fc26.x86_64 #1 SMP Thu Jun 29 20:09:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md
- Others:

**Comment by m1093782566** [comment]
@vincentmli 

Please reference #58052

Briefly speaking, IPVS proxier just want to emulate the `--dst-type LOCAL` in iptables. When #58052 goes in, you can configure the nodeport IP address ranges.

**Comment by vincentmli** [comment]
@m1093782566  thanks, that sounds quite a work from your side, appreciate it! I will try the fix when I get a chance

**Comment by m1093782566** [comment]
I am going to close this issue since it should be fix by #58052 

Please check the HEAD

/close
