### ISSUE TITLE
Track Linux User Namespaces in the Pod Security Policy

### ISSUE THREAD

**Issue by nathanjsweet** [kubernetes/kubernetes#59152]
/kind feature
/sig auth
This came out of the multi-tenancy discussion this afternoon:

**Problem**
Linux user namespaces are a powerful isolation primitive for containers that can offer a lot of security for containers and nodes. While it is the case that pods are ephemeral and don't need their node level configuration tracked specifically, user namespaces presents an exceptional challenge for pods that have persistent volumes.

**Example**
We have a deployment, _A_, and it lands on a node, _node0_, the initial pod has a persistent volume, and the pod is placed in a user namespace offset of 65536. Let's say this pod represents some kind of database. Some time passes, and _node0_ has a problem and all pods on it need to be evacuated. If the database with user namespace offset 65536 migrates and does not maintain its offset on the next node the filesystem on its persistent volume will be unreadable and unwritable to it.

**Solution**
~~I propose that k8s allow user namespaces to be tracked persistently in pod security policies, and that k8s will prevent collisions from occurring across pod security policies (i.e. no pod security policy can share a linux user namespace with another pod security policy, even across k8s namespaces). Either that, or make it an option in pod security policies that they have exclusivity to a user namespace (e.g. pod security policy, "foo", reserves 65536-131072, so no other pod security policy may have it, but "bar" PSP does not reserve 131072-196608, so "baz" may use it as well).~~

Add a `UserNamespace` ("namespace" is one word in the linux world, hence the lack of a capital "S") field to the [PodSecurityContext](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/api/types.go#L1578) struct that specifies the name of the user namespace to pass to the container runtime. In the kubelet code this field will then be used to specify the user namespace per-container. In situations like docker, where the user namespace is set at the daemon level, the kubelet will use the field just to make sure that volumes are initially "chown"-ed properly. It will be up to the person/agent deploying their hosts to make sure their hosts are properly configured. If there are user namespace mismatches across nodes, this code should not seek to correct them.

**Comment by php-coder** [comment]
> If the database with user namespace offset 65536 migrates and does not maintain its offset on the next node

When I looked at it last time, we had the idea for having identical `/etc/subuid`/`/etc/subgid` files on all the nodes in the cluster. This should solve the issue with different mappings between host and namespaced UIDs/GIDs.

CC @adelton

**Comment by nathanjsweet** [comment]
> When I looked at it last time, we had the idea of having identical /etc/subuid//etc/subgid files

@php-coder Interesting. In some ways I'm quibbling with my own proposal, but do you think maybe it's a better idea to keep it as dumb as possible, and just make it another namespace configuration. I think leaving it up to the api-user to make sure the nodes are configured properly is probably a better idea, and just allowing them to specify a user namespace name ("error-ing" out if its not present, which is what [runc does](https://github.com/opencontainers/runc/blob/c1287819af73a4408e089a358d28d18f6adb7dfc/libcontainer/configs/config_linux.go#L9), anyways).

If I can I'd like to edit my proposal to:
"UserNamespace" will be a field added to the [PodSecurityContext object](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/api/types.go#L1578). It will be up to the "deployer" of Kubernetes to make sure the hosts are configured correctly, though of course useful errors will be propagated in the event of a mis-configuration.

**Comment by php-coder** [comment]
> do you think maybe it's a better idea to keep it as dumb as possible

The approach that we tried (that was suggested by @pweil-) doesn't require PSP modification and looks simple enough.

> and just make it another namespace configuration.

It's not clear what do you mean here, could you elaborate on it?

> I think leaving it up to the api-user to make sure the nodes are configured properly is probably a better idea, and just allowing them to specify a user namespace name ("error-ing" out if its not present, which is what runc does, anyways).

Ok, here you again refers to "specify a user namespace name". Could you explain it with more details? How it will look like from technical point of view?

AFAIR docker doesn't allow you to specify a user namespace name. Even more, user namespace support is an option to the whole daemon and if you enable it, all the containers will be run in user namespaces. What I'm missing here? I like how you show examples, so you can use use-cases for a better understanding :)

BTW, WHDYT about using [node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/) for distinguishing nodes with userns and without?

> "UserNamespace" will be a field added to the PodSecurityContext object.

We have a lot of fields in the SecurityContext and PodSecurityContext already but they're directly related to security AND (in most of the cases) they directly translates to the `docker run` options. The option that you're suggesting to add doesn't meet such criteria. As I mentioned above, it's not a container-wide configuration but rather a daemon-wide configuration.

> It will be up to the "deployer" of Kubernetes to make sure the hosts are configured correctly

It's not clear what do you mean by "deployer" but it sounds like you're talking about [scheduler](https://kubernetes.io/docs/concepts/overview/components/#kube-scheduler). Based on the Kubernetes architecture, I doubt that such changes to the scheduler would be approved. Scheduler shouldn't be aware about hosts configuration AFAIU and such a function probably would violate Single Responsibility Principle.


@nathanjsweet BTW, have you seen https://github.com/kubernetes/features/issues/127 ?

**Comment by nathanjsweet** [comment]
> Ok, here you again refers to "specify a user namespace name". Could you explain it with more details? How it will look like from technical point of view?
>...
>We have a lot of fields in the SecurityContext and PodSecurityContext already but they're directly related to security AND (in most of the cases) they directly translates to the docker run options. The option that you're suggesting to add doesn't meet such criteria. As I mentioned above, it's not a container-wide configuration but rather a daemon-wide configuration.

Adding user namespace to the PodSecurityContext definitely counts as security related, IMO. Putting a container into a user namespace protects the node, and protects other pods. As far as making the SecurityContext correspond to the `docker run`, that seems awefully vendor specific. The OCI spec, specifically applies user namespaces directly to containers rather than being a node/host wide configuration. Rkt and CRI-O have support for this feature, it shouldn't be the prerogative of the kubernetes project to cater to the lowest common denominator.

> It's not clear what do you mean by "deployer" but it sounds like you're talking about scheduler. 

Sorry, I should have been more clear. I mean the human/agent creating the cluster. Leave it up to the person/agent deploying kubernetes to get it right. Kubernetes definitely allows kubelet failure to occur in a lot of scenarios where the host is misconfigured, this seems like similar situation to me.

> BTW, WHDYT about using node affinity for distinguishing nodes with userns and without?

This is a good idea, but sounds like something you can leave up to the agent/person again, to properly configure their hosts.

> BTW, have you seen kubernetes/features#127 ?

I haven't, but I'll check it out.

**Comment by adelton** [comment]
I believe there are two parts to the user namespace functionality. One is isolating the containers from the host (so that root process in container does not run as uid 0 on the host), another one is isolating the pods from each other.

With dockerd, the first part can be achieved with `--userns-remap` option. It then uses that single namespace for all containers and images. The https://github.com/kubernetes/kubernetes/pull/55707 tries to make that setup work by adding the necessary `Chown`s to places where normally root-owned directories would be used. It addresses the

```
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/2a2565e6-0801-11e8-a7b7-525400533a7a/containers/test-pod/031e6b2b\\\" to rootfs \\\"/var/lib/docker/165536.165536/overlay2/b1804f7f907c67699db8f4aa0a67334621c7ccd497fbd93a8a3c0c8f815fa30f/merged\\\" at \\\"/dev/termination-log\\\" caused \\\"stat /var/lib/kubelet/pods/2a2565e6-0801-11e8-a7b7-525400533a7a/containers/test-pod/031e6b2b: permission denied\\\"\""
```

errors that you would get under user-namespaced dockerd.

Unlike other runtimes, dockerd might not be supporting per container user namespaces, only using one namespace on the daemon level. The question is, does the community see value in being able to run with that single user namespace to at least support the isolation of containers from host as the https://github.com/kubernetes/kubernetes/pull/55707 is aiming to do?

**Comment by adelton** [comment]
For the second use case, using user namespaces to isolate pods from each other, I wonder if the ideal situation would be for the user / admin not having to deal with is at all and everything being automated the way uid allocation is now. Forcing the admin to specify namespace names seems error-prone.

That would mean that we'd need the ability to get the maximum uid used by container image, compute max of those values for all containers in the pod, and then allocate the uid range and on the node create user namespace matching that range.

The first step might require parsing the container image for all the distinct uids/gids used on directories and files, plus potentially looking at things like `/etc/passwd` and `/etc/group` in the image. Of course, `User` and `Group` directives in systemd unit files might also affect the allocated ids, to perhaps the image author should be able to specify those max values required in image metadata?

Would this level of automated setup be a reasonable goal?

**Comment by simo5** [comment]
I see three options:
1) Just host isolation (what docker supports now)
2) Pod isolation (automatic random assignment and all, to isolate one pod from another only)
3) Explicit user namespace and mapping assignment

The latter one would require configuration on the pod specification, I do not think peeking at images would make sense because the image defintion does not necessarily expose anything of use to calculate what range and what mapping should be used, and you also do not want to have to inspect all images in the pod to make that up.
It's on the user to provide configuration and images that are consistent.

**Comment by adelton** [comment]
Thanks for spelling out the option # 3. I agree that for that setup, the admin/user should make things consistent. Can we assume that that includes distributing matching `/etc/subuid` / `/etc/subgid` on the nodes, for example?

For the # 2, how do you propose the allocation to happen? I assume that one of the use-cases for the automatic allocation would be "I just want to run container from random image from D hub, make it as isolated from the others as possible". How much work do we expect from the user in such scenario? Is is acceptable to ask the user to write pod specification spelling out the uid range needed, for that use-case?

**Comment by nathanjsweet** [comment]
I would just like to make it clear that I'm advocating for option #3, as it keeps Kubernetes stupid to the node configuration. There are many possible use cases for user namespacing, some users might want all pods isolated from one another, while some might want to create a concept of "tenancy" where a group of pods are part of the same "tenant" and don't need to be isolated from one another, but need to be isolated from other tenants. Additionally, users might want to be in charge of the naming convention for the namespaces based on ids based in their database, etc. 

Finally, user namespaces are a finite resource. At best, [Linux allows up to 340 user namespaces](http://man7.org/linux/man-pages/man7/user_namespaces.7.html)(search "4.15" to find the relevant information in this man page), similar to how users manage other finite resources via tolerations and taints, users may need to manage user namepsaces based on their use cases as an exhaustible resource.

I think keeping Kubernetes as flexible as possible is the right direction to go.

It's worth noting that #3 doesn't preclude higher level security features. It would always be possible to have kubelet manage this on top of an architected option 3 solution. Doing the higher level abstraction first might make doing option #3 in the future more difficult (unless of course #3 is carefully considered as the higher level abstraction is created).

**Comment by simo5** [comment]
@adelton I think for the second case we can allow the user to specify/requet a range perhaps, but I would think we just want to allocate randomly by default, to keep things simple.
@nathanjsweet I am not sure what it menas to advocate for opetion 3, the 3 I mentioned before are seprate cases that I think should be supported in Kube, all of them should be, not any specific one.
If any of those cases can be subsumed into another one that is a nice thing, but the user needs to know what the infra "can offer them.
Also we need to decide the behavior if a user asks for some a more complicated configuration (that falls under case 3) but the system can onlly offer, say (1) (as current docker capabilities would imply IIUC).
Also should users be allowed to freely opt-in in to more confined options, or because of the resource constraints, the strategies to use user namespaces should always restricted to administrative decisions ? Or is there some middleground there (PSP) ?

**Comment by nathanjsweet** [comment]
> I mentioned before are seprate cases that I think should be supported in Kube, all of them should be, not any specific one.

I don't know enough to agree or disagree with you here. However, I do think 3 is the lowest-level abstraction and could be used to build out the other two.

> Also should users be allowed to freely opt-in in to more confined options, or because of the resource constraints, the strategies to use user namespaces should always restricted to administrative decisions ? Or is there some middleground there (PSP) ?

I think you are right to think about it in a capacity related way.

The one way I think it could be done in a way that makes the API competent enough to provide informative error handling to the users is if each host/node treated user namespace slots as a capacity constraint (I have no idea if CRI has a way to communicate that), so that deployments could fail with a useful message like `there are currently no nodes that can accommodate user namespace "tenant-0"` or in the case of option 2: `there are currently no nodes/hosts that can isolate this pod` (i.e. all 340 slots have been accounted for). One thing to think about is volumes, which add a complication for the person that wants all pods isolated from one another, their volumes will get messed up once they pass the 340 pod mark.

The way I see it the break down of the option is this:

|   | easy-to-implement | user-friendly | flexible | administrative burden         |
|---|-------------------|---------------|----------|-------------------------------|
| 1 | yes               | yes           | no       | low                           |
| 2 | no                | yes           | ??      | medium-high |
| 3 | yes               | no            | yes      | high                          |

**Comment by adelton** [comment]
> Finally, user namespaces are a finite resource. At best, Linux allows up to 340 user namespaces

@nathanjsweet, reading the man page, the limit of 340 is the number of lines in `/proc/<pid>/uid_map`, which is the number of mapping uid intervals in one user namespace. Are you sure that the number 340 is about the number of namespaces in the system?

**Comment by nathanjsweet** [comment]
>  reading the man page, the limit of 340 is the number of lines in /proc/<pid>/uid_map, which is the number of mapping uid intervals in one user namespace. Are you sure that the number 340 is about the number of namespaces in the system?

@adelton You're absolutely correct. I'm sorry for the misinformation. User namespaces themselves have not limits, but the mappings inside the namespace do.

**Comment by brauner** [comment]
I'm the author of that particular patch ( https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6397fac4915ab3002dc15aae751455da1a852f25 ). Without going into detail, what you need to know is `340` is the maximum number of lines you can have in `/proc/<pid>/uid_map` and `/proc/<pid>/gid_map` each.
