### ISSUE TITLE
IPv6-only pod get killed because of 'failed to get IP addresses for "eth0":'

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#59160]
**What happened**:
I got a fully IPv6-only v1.8.x cluster working at glance with Calico 2.x.

I try to deploy a new one on k8s v1.9.x and Calico 3.x.

When I schedule a IPv6-only pod, it got created nicely, got an IPv6 on his own network stack but get delete by kubelet few minutes after the creation because : 

```
 failed to get IP addresses for \"eth0\": <nil>"
```

**What you expected to happen**:

Get my pod running and the IPv6 displayed on `kubectl get pod -o wide`

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an IPv6 cluster, create a pod, wait.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- Cloud provider or hardware configuration: KVM VMs
- OS (e.g. from /etc/os-release): Debian 9.2
- Kernel (e.g. `uname -a`):  Linux  4.9.0-5-amd64
- Install tools: via Saltstack, own recipe.  
- Others:  Calico v3.0 / CNI v0.6.0 / Calico CNI 2.0

/sig network

**Comment by valentin2105** [comment]
Found the issue, it's on Cri-Containerd side.

**Comment by pmichali** [comment]
@valentin2105 Can you elaborate on what you found to be wrong? I've been trying to bring up K8s on bare metal with IPv6 and Kube-dns and user created pods are failing to come up with kubelet reporting permission denied when trying to add the IPv6 address to the pod:

kubelet[24092]: E0131 16:02:47.006479   24092 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-64b69dc4d-hmkvt_kube-system" network: failed to add IP addr {Version:6 Interface:0xc42000f1d0 Address:{IP:fd00:40::10:0:0:2 Mask:ffffffffffffffffffff000000000000} Gateway:fd00:40::10:0:0:1} to "eth0": permission denied

Using bridge plugin, on Ubuntu 16.04 x64 server. Just wondering if there is any connection, or if I'm seeing something unrelated (and maybe something on my test bed setup).

**Comment by valentin2105** [comment]
Hi @pmichali 
I don't know anything about BridgePlugin, but if you use Calico CNI, you can easily got IPv6 only on your cluster.

The problem was with cri-containerd and one if his dependency : 
https://github.com/containerd/cri-containerd/issues/580
It's currently get fixed.

With Docker, the IPv6 is directly added to the pod and viewable on k8s : 

```
NAME                       READY     STATUS    RESTARTS   AGE       IP                    
toolbox-5b4c9d799d-p5bnp   1/1       Running   1          10h       1404:f200:ff:533::2:3   
```

**Comment by pmichali** [comment]
I found for bridge plugin (one of the reference plugins for K8s that happens to support IPv6), that I needed to downgrade docker from 17.12.0-ce to 17.03.2-ce (other versions may work too). I no longer see the error and IPs are assigned fine.

I do plan on trying Calico too, in the near future.

**Comment by valentin2105** [comment]
As I send you on twitter, 17.09.1-ce work at glance in IPv6 too, (more new than 17.03)
