### ISSUE TITLE
Sometimes symlinks to container logs are not created. 

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes/kubernetes#59206]
**Is this a BUG REPORT or FEATURE REQUEST?**: Yes

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
When kubelet restarts (due to whatever reason) after a container has been started but symlinks to the container logs are not created, the symlinks are never created, and container logs can not be read and end up with error:

```
failed to open log file "/var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log": open /var/log/pods/c2cbd02c-dbe3-11e7-85de-0e10bc5ac50a/sti-build_0.log: no such file or directory
```
At the code level, If kubelet is restarted (due to any issue) after https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L135 ( m.runtimeService.StartContainer )  and before https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L145 (it also impact symlinks being created here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L243 ), both symlinks are not created even though container is started successfully.    

And the reason is that when kubelet restarted, the container was started successfully, and since creation of 2 symlinks (one symlink to container logs and one legacy symlink) is not associated with `started container` state, symlinks are never created, the container and its pods still completes successfully. The consequence is that container logs can not be read. 

The issue can happen with both init-containers and non-init (main) containers.

**What you expected to happen**:
Symlinks to logs are created, so that container logs can be read via kubectl log.

**How to reproduce it (as minimally and precisely as possible)**:
One way to reproduce is to instrument the kubelet code https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L241 by putting sleep and when the execution hits the sleep, stop and restart the kubelet. There might be other ways too.

**Anything else we need to know?**:
There are some issues that seems similar:
https://github.com/kubernetes/kubernetes/issues/52172
https://github.com/kubernetes/kubernetes/issues/45911
https://github.com/coreos/tectonic-forum/issues/183

**Environment**:
- Kubernetes version (use `kubectl version`): latest kube code
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@sjenning @dashpole

**Comment by aveshagarwal** [comment]
Some ways to address this (sorry if some are ugly):

1. In each sync (sync pod), check if symlinks are created or not, if not create them. A fix to address this way is here: https://github.com/aveshagarwal/kubernetes/pull/9

2. Create a flag in container status that stores if symlinks have been created or not. So that in each sync, this flag can be checked and, if false, symlinks can be created (if dont exists already, as it is possible that flag was not set even though symlinks were created). It could ensure that symlinks are created at some point in future. Flag, sort of, keeps state of if symlinks are created or not. 

3. . Associate creation of symlinks with container started state, so that conatiner is not considered started unless symlinks have also been created. I have been some discussions (forgot where) that there is plan to segregate log lifecycle from container lifecycle so this approach might not be really desired.

**Comment by aveshagarwal** [comment]
Also note, this issue not only affects symlinks, but impacts PostStart hooks too: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L156

**Comment by sjenning** [comment]
@aveshagarwal can you open up a PR for this based on your branch and open a new issue to track the issue where if we hit a `context deadline exceeded` on `StartContainer` or restart the kubelet in the middle of the `StartContainer()` that the container can still come up, as the runtime will continue to try to start the container.  If that happens, the post-start hooks will not be executed.
