### ISSUE TITLE
a lot of connection  Timeout failed issues

### ISSUE THREAD

**Issue by azzeddinefaik** [kubernetes/kubernetes#59205]
We recently noticed that we have a lot of connection failed issues, in large number of our pods:

ConnectionError: HTTPConnectionPool(host='service_name', port=80): Max retries exceeded with url: /url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91218e82b0>: Failed to establish a new connection: [Errno -3] Try again',))

And after further investigation we noticed a kube-dns issue that correlate reasonably with that.

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@azzeddinefaik Can you please supply more information about your setup and any logs that may be helpful.
