### ISSUE TITLE
deployment's collision avoidance mechanism is not triggered when a replicaset's non-PodTemplateSpec field is changed

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/kubernetes#59213]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Deployment's collision avoidance mechanism assumes that if a replicaset's PodTemplateSpec is semantically deep equal with the deployment's PodTemplateSpec, then the replicaset is the new replicaset for the deployment. This assumption does not take into account the case when the user updates only a field of the replicaset that does not reside within the replicaset's PodTemplateSpec, in which the collision avoidance mechanism should also be triggered.

**What you expected to happen**:
The collision avoidance mechanism should be triggered when a non-PodTemplateSpec field (e.g., `.Labels` field) of the replicaset is changed.

After making changes to `sync.go` (#59212), the `testDeploymentsControllerRef` e2e test can be elaborated (#59448) to verify the mechanism works as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a Deployment
2. wait for ReplicaSet and its Pod(s) to become ready
3. edit a non-PodTemplateSpec field of the ReplicaSet
4. observe that Deployment does not create a new ReplicaSet

/sig apps
/cc @enisoc @janetkuo

**Comment by janetkuo** [comment]
To clarify, we don't actually care about RS label changes in this case. What we do care about is the change of ownership between Deployment and its RSes.

**Comment by crimsonfaith91** [comment]
@janetkuo Update description of the issue. Tell me if it is still confusing.

**Comment by crimsonfaith91** [comment]
@enisoc Thanks for pointing to the `testDeploymentsControllerRef` e2e test.
