### ISSUE TITLE
Refactor proxiers to share implementation of ServiceHandler & EventHandler

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#59215]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind cleanup

**What happened**:
There is still some duplication among kernel space proxiers. Specifically, each proxier implements the ServiceHandler and EndpointsHandler in the exact same way. 

**What you expected to happen**:
Ideally, we could abstract each Proxier behind a KernelSpaceProxier interface which defines certain methods such as ServiceChangesMap(), EndpointsChangesMap(), etc. Then, the duplicated event handler code could be shared among proxiers.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
cc @m1093782566 

/area kube-proxy

/sig network

**Comment by m1093782566** [comment]
sounds good to me.
