### ISSUE TITLE
Resource exclusively access support on RBAC

### ISSUE THREAD

**Issue by yjiang5** [kubernetes/kubernetes#59216]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
kind feature

**What happened**:
In some situation, we don't want user to access both type of resources, i.e., one role can access either resource A, or resource B, but can't access both of them.

Currently this can't be achieved through RBAC yet.

**What you expected to happen**:
When user create roles to access both resource A/B, or create role bindings that, when combined, will make one user to access both resources, the creation should fail.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 
1.9
- Cloud provider or hardware configuration:
Generic server

- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3 LTS 

- Kernel (e.g. `uname -a`):
4.4.0-92-generic
- Install tools:
- Others:

/sig api-machinery

**Comment by hzxuzhonghu** [comment]
what's use case?

**Comment by liggitt** [comment]
That doesn't seem a very common use case. For specialized authorization strategies, the webhook authorizer might be a better fit

**Comment by liggitt** [comment]
Cc @kubernetes/sig-auth-feature-requests

**Comment by lavalamp** [comment]
I agree with @liggitt; this seems to be heading in the direction of turning RBAC into a DSL / Turing complete language. Please reopen with more explanation if you think that's not the right solution.
