### ISSUE TITLE
Document upgrade and downgrade steps for etcd 3.2 upgrade

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#59221]
For kubernetes 1.10, we've upgraded the default etcd version to 3.2. As part of this we also must document:
- Steps to upgrade etcd from 3.1 to 3.2
- Steps to rollback from 3.2 back to 3.1 if anything goes wrong. The downgrade path will be to use etcdctl save/restore, which requires downtime but can be performed with zero data loss.

**Comment by jberkus** [comment]
Please add priority and kind labels for this issue.  It looks needed for 1.10, but we need to know how to sort it when code slush comes, thanks!

**Comment by jberkus** [comment]
@jpbetz is there a documentation PR for this issue?  Please link, thanks.

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes/kubernetes/pull/60173.  Since we were able to incorporate the rollback support directly into `migrate-if-needed.sh`, it turns out that we don't need a whole lot of documentation here.

**Comment by jberkus** [comment]
@jpbetz can you please add status/approved-for-milestone so that this issue can stay in 1.10?  Thanks.
