### ISSUE TITLE
--configure-cbr0=true not recognised on 1.9.2

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/kubernetes#59257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
```
kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --configure-cbr0=true
unknown flag: --configure-cbr0
```

**What you expected to happen**:
As mentioned in documentation here https://kubernetes.io/docs/getting-started-guides/scratch/#networking I expected cbr0 to be created
**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.2
- OS (e.g. from /etc/os-release):
Debian 9.3

**Comment by islinwb** [comment]
It has been removed. (https://github.com/kubernetes/kubernetes/pull/34906)

**Comment by tiukhtinvladimir** [comment]
@islinwb Thanks. It will be fine to update documentation then

**Comment by dims** [comment]
looks like 7518 has merged

/close
