### ISSUE TITLE
pull-kubernetes-e2e-kops-aws is broken in 1.7 branch

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#59263]
pull-kubernetes-e2e-kops-aws is consistently failing on all PRs from 1.7 branch, e.g.:
https://github.com/kubernetes/kubernetes/pull/59164
https://github.com/kubernetes/kubernetes/pull/59192

OTOH, the AWS tests on 1.7 branch look pretty healthy:
https://k8s-testgrid.appspot.com/sig-release-1.7-blocking#aws-release-1.7

@justinsb @kubernetes/test-infra-maintainers @kubernetes/sig-aws-misc - can someone please take a look.
This is blocking next 1.7 patch release.

**Comment by justinsb** [comment]
Thanks for the heads up - looking!

**Comment by justinsb** [comment]
Ah - I think this is https://github.com/kubernetes/kubernetes/pull/55417 again, but with mkfifo.  When we did the equivalent of https://github.com/kubernetes/kubernetes/pull/57756 in kops, we added a dependency on mkfifo.  Again it's in the non-CI builds, and it's in >= 1.8, but I'll send a PR to add mkfifo to 1.7 CI

**Comment by justinsb** [comment]
PR is https://github.com/kubernetes/kubernetes/pull/59268

**Comment by wojtek-t** [comment]
@justinsb - thanks a lot for looking and fixing!

**Comment by wojtek-t** [comment]
This is now fixed - thanks!
