### ISSUE TITLE
kubelet manifest dir sync broken

### ISSUE THREAD

**Issue by roboll** [kubernetes/kubernetes#59275]
/kind bug

cc. @timothysc 

**What happened**:
Since https://github.com/kubernetes/kubernetes/pull/50984 - specifically https://github.com/kubernetes/kubernetes/pull/50984/files#diff-bf28da68f62a8df6e99e447c4351122dR303, kubelet always calls `cfg.Channel(kubetypes.ApiserverType)`, leading it to always register an apiserver source with the `PodConfig`. This leads to `PodConfig.SeenAllSources` to never return true in cases where the kubelet is not configured to communicate with an apiserver. 

The direct result of this is that when removing a manifest from the directory, kubelet never kills the containers.

**What you expected to happen**:

The containers get killed properly.

**How to reproduce it (as minimally and precisely as possible)**:

Configure kubelet standalone without an apiserver, and with a static pod manifest path. Add a manifest, then remove it. Observe the containers stick around. Set logging to greater than level 6, and see a lot of `Feb 02 16:57:17 i-0ad42c5386ecaee18 kubelet[2496]: I0202 16:57:17.315020    2524 config.go:99] Looking for [api file], have seen map[file:{}]`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2 (1.8.7 works)

**Comment by timothysc** [comment]
@kubernetes/sig-node-bugs - Is there a run a static manifest that's not a master test case in the node-e2e suite?

**Comment by yujuhong** [comment]
I don't think there are standalone kubelet tests since it's hard to observe the pod status.
