### ISSUE TITLE
OutOfDisk condition not set to Unknown when node not responding

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#59278]
```
Actual results:
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----             ------    -----------------                 ------------------                ------                     -------
  OutOfDisk        False     Fri, 02 Feb 2018 06:17:03 +0000   Thu, 01 Feb 2018 06:01:45 +0000   KubeletHasSufficientDisk   kubelet has sufficient disk space available
  MemoryPressure   Unknown   Fri, 02 Feb 2018 06:17:03 +0000   Fri, 02 Feb 2018 06:17:45 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure     Unknown   Fri, 02 Feb 2018 06:17:03 +0000   Fri, 02 Feb 2018 06:17:45 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
  Ready            Unknown   Fri, 02 Feb 2018 06:17:03 +0000   Fri, 02 Feb 2018 06:17:45 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
```

Looks like it was originally correct:
https://github.com/kubernetes/kubernetes/pull/48983/files#diff-209cdbcfa0c2a92c871efbfdb362860bR960

This a PR removed it:
https://github.com/kubernetes/kubernetes/pull/51294/files#diff-a44cd14a0381ca49bcbaaf967b3cc9b0L988

I think this just got caught up in a sweep to remove OutOfDisk from controllers and no one realized that we still needed this until it is removed entirely.

xref https://bugzilla.redhat.com/show_bug.cgi?id=1541263

@dashpole @derekwaynecarr @wjiangjay

**Comment by dashpole** [comment]
We should remove the generation of the OutOfDisk condition by the kubelet in 1.10
See https://github.com/kubernetes/kubernetes/issues/48843

**Comment by sjenning** [comment]
@dashpole I saw that was planned and this can be undone once that is done.  But in the meantime, and for 1.9 and 1.8, this is an issue.  Right?

**Comment by dashpole** [comment]
Yes, #59279 is still required :)
