### ISSUE TITLE
kubelte - unknown flag: --network-plugin-dir

### ISSUE THREAD

**Issue by tiukhtinvladimir** [kubernetes/kubernetes#59312]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
According to document https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#kubenet I am configuring kubelet to use exactly network plugins directory. But kubelet confugured to run with '--network-plugin-dir' flag returns a message
```
unknown flag: --network-plugin-dir
```

**What you expected to happen**:
Kubelet started

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.2
- OS (e.g. from /etc/os-release):
Debian 9.3

**Comment by jhorwit2** [comment]
@tiukhtinvladimir please use `--cni-bin-dir`, which is the replacement for `--network-plugin-dir`. 

PR: https://github.com/kubernetes/kubernetes/pull/53564

/sig docs
