### ISSUE TITLE
Apiserver crashed while reporting component statuses

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#59338]
In release 1.9.1:

```
goroutine 2503314 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.strSliceContains(0x0, 0x2, 0x2, 0x3b633e3, 0x2, 0xa6d667)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2096 +0x3b
k8s.io/kubernetes/vendor/golang.org/x/net/http2.configureTransport(0xc42e8c2e10, 0x0, 0x0, 0xc42e8c2e00)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/configure_transport.go:28 +0x13a
k8s.io/kubernetes/vendor/golang.org/x/net/http2.ConfigureTransport(0xc42e8c2e10, 0xd, 0x0)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:126 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net.SetTransportDefaults(0xc42e8c2e10, 0xc42e8c2e10)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net/http.go:107 +0xb2
k8s.io/kubernetes/pkg/probe/http.NewWithTLSConfig(0xc42e8aa780, 0xc428952610, 0xc428952618)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/probe/http/http.go:41 +0x5d
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*Server).DoServerCheck.func1()
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go:71 +0x3c
sync.(*Once).Do(0xc4312e75b0, 0xc4289526b8)
        /usr/local/go/src/sync/once.go:44 +0xbe
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*Server).DoServerCheck(0xc4312e7560, 0x80000, 0xc42001b300, 0xc42cfa1e58, 0x56d590, 0xc42e03d100, 0xc429b1c000)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go:67 +0x61
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).getComponentStatus(0xc4201075e0, 0xc423aab428, 0x6, 0xc4312e7560, 0x0)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:98 +0x40
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).List.func1(0xc423aab430, 0xc4201075e0, 0xc4312e75c0, 0xc423aab428, 0x6, 0xc4312e7560)
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:62 +0x73
created by k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).List
        /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:60 +0x15f
```

@kubernetes/sig-api-machinery-bugs

**Comment by yliaog** [comment]
@wojtek-t could you please provide more details, like how to reproduce this bug?

**Comment by wojtek-t** [comment]
I don't know - I've seen that in one of our prod clusters.

**Comment by wojtek-t** [comment]
I've just seens this in 1.7.11 release too

**Comment by mborsz** [comment]
I just tried to debug this a bit and my understanding is that:
1. strSliceContains call that causes panic according to stacktrace:
https://github.com/kubernetes/kubernetes/blob/1789a8513c745f274ff8ddc3c46948a4a2ff2468/vendor/golang.org/x/net/http2/configure_transport.go#L28-L30

2. NextProtos at that point is somehow malformed, because according to stacktrace:
> k8s.io/kubernetes/vendor/golang.org/x/net/http2.strSliceContains(0x0, 0x2, 0x2, 0x3b633e3, 0x2, 0xa6d667)

slice of nil array and len = cap = 2 has been passed (how to create such a slice?)

3. The reason is that t1.TLSClientConfig is modified concurrently from multiple goroutines, as it's shared between multiple componentstatuses:
See:
https://github.com/kubernetes/kubernetes/blob/89cbdc0d6ff54dff025113c6c8f15b95abcd721c/pkg/registry/core/componentstatus/rest.go#L54-L67
Where GetServersToValidate is:
https://github.com/kubernetes/kubernetes/blob/89cbdc0d6ff54dff025113c6c8f15b95abcd721c/pkg/registry/core/componentstatus/rest.go#L37-L41

https://github.com/kubernetes/kubernetes/blob/a5c46303a2ed2c252c69855b3e650103f08a5703/pkg/registry/core/rest/storage_core.go#L219

Where serversToValidate constructs response based on Backends():

https://github.com/kubernetes/kubernetes/blob/a5c46303a2ed2c252c69855b3e650103f08a5703/pkg/registry/core/rest/storage_core.go#L240-L246
...
https://github.com/kubernetes/kubernetes/blob/a5c46303a2ed2c252c69855b3e650103f08a5703/pkg/registry/core/rest/storage_core.go#L266-L277

And Backends() returns TLSConfig that is shared between multiple Backends:
https://github.com/kubernetes/kubernetes/blob/89cbdc0d6ff54dff025113c6c8f15b95abcd721c/staging/src/k8s.io/apiserver/pkg/server/storage/storage_factory.go#L321-L328

This is somehow unexpected, because according to https://golang.org/pkg/net/http/
> Clients and Transports are safe for concurrent use by multiple goroutines and for efficiency should only be created once and re-used.

**Comment by mborsz** [comment]
I think the comment from net/http doesn't apply here, as we are calling http2.ConfigureTransport concurrently:
https://github.com/kubernetes/kubernetes/blob/7aed66305127904a874289a1c78f5b5d5ad6b80c/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L101-L112

and http2.ConfigureTransport doesn't give any thread safe guarantees

**Comment by gbjuno** [comment]
same behavior on v1.8.4

`
I0214 02:48:50.709154   47166 trace.go:76] Trace[63796845]: "List /api/v1/componentstatuses" (started: 2018-02-14 02:48:50.078710849 +0800 CST) (total time: 630.396581ms):
Trace[63796845]: [630.039507ms] [630.012167ms] Listing from storage done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93e97c]

goroutine 5410539 [running]:
k8s.io/kubernetes/vendor/golang.org/x/net/http2.strSliceContains(0x0, 0x1, 0x0, 0x38b91c1, 0x2, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2096 +0x3c
k8s.io/kubernetes/vendor/golang.org/x/net/http2.configureTransport(0xc42c112780, 0x0, 0x0, 0x39e6900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/configure_transport.go:28 +0x136
k8s.io/kubernetes/vendor/golang.org/x/net/http2.ConfigureTransport(0xc42c112780, 0xd, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:126 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net.SetTransportDefaults(0xc42c112780, 0xc42c112780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net/http.go:107 +0xb2
k8s.io/kubernetes/pkg/probe/http.NewWithTLSConfig(0xc42392d380, 0xc4277d1608, 0xc4277d1600)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/probe/http/http.go:41 +0x62
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*Server).DoServerCheck.func1()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go:71 +0x3c
sync.(*Once).Do(0xc4336b3010, 0xc4277d16b8)
        /usr/local/go/src/sync/once.go:44 +0xbe
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*Server).DoServerCheck(0xc4336b2fc0, 0xc42e0766c0, 0xc420014000, 0xc42d7e89a0, 0xc42c2eac00, 0x1, 0x814d9c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/validator.go:72 +0x76
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).getComponentStatus(0xc420fc0d68, 0xc42784fee0, 0x6, 0xc4336b2fc0, 0x6ba130)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:98 +0x40
k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).List.func1(0xc42784ff60, 0xc420fc0d68, 0xc4336b30e0, 0xc42784fee0, 0x6, 0xc4336b2fc0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:62 +0x73
created by k8s.io/kubernetes/pkg/registry/core/componentstatus.(*REST).List
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/componentstatus/rest.go:64 +0x164
`

and i don't use http2 in k8s cluster communication.

**Comment by wojtek-t** [comment]
Fix for that is in #60069

**Comment by wojtek-t** [comment]
Once submitted, this should be cherrypicked to previous branches.

**Comment by wojtek-t** [comment]
Cherrypicks are here:
https://github.com/kubernetes/kubernetes/pull/60077
https://github.com/kubernetes/kubernetes/pull/60078

**Comment by wojtek-t** [comment]
It seems it's still not really fixed...

**Comment by wojtek-t** [comment]
Actually, it may potentially not be true - we only have evidence that this bug happened in clusters that are in 1.8.9 version (which has the fix), but it might potentially have happened before the upgrade....

**Comment by wojtek-t** [comment]
So I will close it for now until we have 100% proof for it.
