### ISSUE TITLE
Namespace directory nodes are not removed from etcd

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#5933]
The resource paths for each object in etcd follow a convention like the following:

```
/registry/pods/namespace1/pod1
/registry/pods/namespace1/pod2
/registry/pods/namespace2/pod1
/registry/pods/namespace2/pod2
```

The same pattern follows for all other namespace scoped resource types.

When we delete a namespace, we are properly deleting the individual resources (pod1 and pod2), but in etcd, we still get a directory node that represented what used to be that namespace's content directory.

For example, if we delete namespace1, we end up with the following empty directory in etcd.

```
/registry/pods/namespace1
```

We should develop a solution to purge these empty directories from etcd to maintain system performance over time.

We could do this at a lower-level:

1) some controller that purges empty dirs from etcd
2) or some other convention in our registry to ask that the folder node for a namespace is deleted as part of namespace termination

The remaining folders cause no end-user impact, but just result in unnecessary folders left in etcd repo.

**Comment by timothysc** [comment]
@rrati, @jayunit100 ^ this is what we were seeing.

**Comment by jayunit100** [comment]
I like the  (2) approach, as  that sounds closer to  *synchronous* then (1) ...

**Comment by derekwaynecarr** [comment]
I would like to support delete on the collection:

DELETE /namespaces/foo/pods

would kick-off special code in the registry that would result in the entire folder in etcd being deleted.

**Comment by kbeecher** [comment]
I'm interested in taking this one. I'd like to clarify a couple of things...

From reading @derekwaynecarr's 1st and 2nd messages, there seems to be two issues...
1. After deleting a namespace, that namespace's entry remains in etcd (and should be deleted).
2. After every resource within a namespace has been deleted, the (now empty) namespace should be deleted as well.

Have I understood that correctly?

**Comment by derekwaynecarr** [comment]
@kbeecher 

The issue is related to how nodes are structured in etcd.

If you create a namespace, you get a node in etcd at the following path:

```/registry/namespaces/foo```

If you add content to that namespace, you get content in a path structure dependent on the resource type.  So for example, if you add a pod `bar` to the namespace foo, you get a node in etcd at the following path.

```/registry/pods/foo/bar```

If you delete the namespace foo, our clean-up code will do the following:

```
DELETE node at /registry/namespace/foo
DELETE node at /registry/pods/foo/bar
```

but you are left with a folder node in etcd here:

```
/registry/pods/foo
```

The idea is that we extend the REST API to allow clients to say

```
DELETE /api/v1beta3/namespaces/foo/pods  [delete all pods in namespace foo]
```

Which should result in a call to etcd to 

```
DELETE folder at /registry/pods/foo [which will remove all the child nodes]
```

We would need to make the namespace_controller call that new REST API as part of this change.

So this issue requires the following:

1. Modify REST framework to support deleting all resources in a namespace
2. Modify generic.Etcd to expose that concept so all of our resources can use it
3. Modify the client packages to expose methods like client.Pods(ns).DeleteAll()
4. Modify the namespace_controller to call that new client method instead of doing the List, Delete each pattern it does now.

I am happy to help guide you if you work on this PR, but I would do it in the above order.

**Comment by timothysc** [comment]
@derekwaynecarr is this on the roadmap for 1.0?

**Comment by derekwaynecarr** [comment]
@timothysc i would like this fixed for 1.0, but I would appreciate community help if folks have cycles.

**Comment by timothysc** [comment]
#7018

**Comment by kbeecher** [comment]
@derekwaynecarr Thanks for the reply, that makes things clearer. Just one question...

I get the idea behind items 2, 3, and 4, and I'm familiar with some of those parts of the code. However, I'm not yet familiar with the REST framework. Consequently, I don't know where in the code to look to get started on item 1.

I also don't understand in what sense the REST framework needs modification - from looking at the comments above apiserver.GetAPIRequestInfo(), the request `DELETE /namespaces/foo/pods` is already a valid request, so if you could help me out there that'd be great.

**Comment by kbeecher** [comment]
I have written some code that I think should cover points 1 & 2 in your task breakdown. I expected that my changes would add a DELETE operation at the collection level in the swagger UI, but they haven't.

Could I somehow share the WIP with you to see if I'm missing something? If so, what would be best? A PR?

**Comment by derekwaynecarr** [comment]
A PR marked WIP works, and just mention me to take a look.  I will try it out and give some feedback.

**Comment by timothysc** [comment]
v3 will allow us to remove this pretty easily but we are now waiting 1 release before making registry and data model changes.

**Comment by liggitt** [comment]
etcd3 doesn't have directory nodes
