### ISSUE TITLE
[advanced audit]Audit rule matching logic incorrect when user attribute is nil

### ISSUE THREAD

**Issue by smurfralf** [kubernetes/kubernetes#59331]
/kind bug

**What happened**:

Advanced audit logging policy rules with specific users match requests that don't have user info.

**What you expected to happen**:

Rules with users should _only_ match transactions with those users. E.G for the reproduction steps below, the audit log should have a metadata entry for the `401` request/response caused by the catch-all rule since the first  `Level: None` rule should only apply to requests from the specified user.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable advanced auditing and define a Advanced Audit Logging policy rule that includes users and verbs followed by a catch-all rule, for example

```
  - level: None
    users: ["system:serviceaccount:kube-system:generic-garbage-collector"]
    verbs: ["get", "list"]

  - level: Metadata

```

2. Perform a request with an invalid authentication, for example
    a. Enable token authentication on the api server
    b. invoke `curl -H "Authorization: Bearer no_such_token" -k https://localhost:6443/apis/apps/v1/statefulesets`
     c. expect status `401` to be returned

3. Inspect the audit log (`kube-apiserver-audit.log` by default). With kube version 1.9.1 is no audit log entry is present for the above exchange.

**Anything else we need to know?**:

The bug is in the `ruleMatches` function of k8s.io/apiserver/pkg/audit/policy/checker.go. 

This clause

```
if len(r.Users) > 0 && attrs.GetUser() != nil {
   if !hasString(r.Users, attrs.GetUser().GetName()) {
      return false
   }
}
``` 
should be
```
if len(r.Users) > 0 {
   if attrs.GetUser() == nil || !hasString(r.Users, attrs.GetUser().GetName()) {
      return false
   }
}
``` 
     
**Environment**:
- Kubernetes version: git status v1.9.1 (locally built, running with `hack/local-up-cluster.sh`)

**Comment by smurfralf** [comment]
The same problem exists in the parallel clause in the same function for matching `UserGroups`.

**Comment by CaoShuFeng** [comment]
@smurfralf 
I can't reporduce this issue with the steps you provided.

I think the reproduce step should be:
1. define a policy rule like this:
```
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    users: ["tom"]                  # we only log Tom's events, so unauthorized request should not be saved.
    verbs: ["get","list"]
```
2. make an unauthorized request:
```
curl -H "Authorization: Bearer no_such_token" -k https://localhost:443/apis/apps/v1/statefulesets
```
3. check the audit log file, we found that not only Tom's request are saved, but also the unauthorized one
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2018-02-06T18:58:44Z"},"level":"Metadata","timestamp":"2018-02-06T18:58:44Z","auditID":"e959fdaf-eb2e-4755-90d4-0680a08f3015","stage":"ResponseStarted","requestURI":"/apis/apps/v1/statefulesets","verb":"list","user":{},"sourceIPs":["::1"],"objectRef":{"resource":"statefulesets","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401},"requestReceivedTimestamp":"2018-02-06T18:58:44.568671Z","stageTimestamp":"2018-02-06T18:58:44.568766Z"}
```

**Comment by CaoShuFeng** [comment]
https://github.com/kubernetes/kubernetes/pull/59398

@smurfralf 
Does the pull request fix this issue?
Sorry that I haven't understand your reproduce steps.

**Comment by smurfralf** [comment]
@CaoShuFeng: Fix looks good. Maybe this will help with the reproduce steps:
1) rules are applied in the order they are found. As soon as a rule matches (returns true) then the other rules below it are ignored.
2) The reproduce steps define two rules. If the first rule matches then the second one doesn't get used.
3) The first rule in the reproduce step says "Level: None" which means audit logging is skipped.
4) The second rule says "Level: Metadata" without condition. So if the second rule gets used, then you will always have an audit log entry.
5) Which equates to:  `if` audit log entry there? `then`  first rule did not match `else` first rule matched `end`.

**Comment by CaoShuFeng** [comment]
@smurfralf 

> Maybe this will help with the reproduce steps:

Your step is right. Thanks.

Let me describe this isssue in one sentence:
`A 401 request should not match an audit policy with user or group specified.`

**Comment by smurfralf** [comment]
@CaoShuFeng: Cool. Your sentence is correct. However its just a bit more restrictive than I'd want for the issue summary because 401 may not be the only way to get an event without user info.
