### ISSUE TITLE
gce-100 node cluster failing to come up against 1.8

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#59349]
Our gce-1.8 100-node scalability [job](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.8) is failing to create the cluster with:

```
Failed to create firewall e2e-scalability-stable1-minion-e2e-scalability-stable1-nodeports in k8s-e2e-gci-gce-scale-1-4
```

and has been failing continuously since run 523.

cc @kubernetes/sig-network-bugs

**Comment by shyamjvs** [comment]
@krzyzacy @MrHohn - Could one of you PTAL into this?

**Comment by shyamjvs** [comment]
Ok.. I took a quick look and found out the problem,

previously we were creating the firewall with name `e2e-scalability-1-6-minion-e2e-scalability-1-6-nodeports`, but then @krzyzacy's PR https://github.com/kubernetes/test-infra/pull/6538 to bikeshed 1.6 jobs changed the generated name for firewall to `e2e-scalability-stable1-minion-e2e-scalability-stable1-nodeports` which is failing to be created because the name is too long.

The gcloud docs say the name `Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'` which is not satisfied by the above.

**Comment by shyamjvs** [comment]
/assign

I'll send a fix reducing the length of the name.

**Comment by krzyzacy** [comment]
ah, thanks!
