### ISSUE TITLE
Dashboard add-on config ignores cert/key pair in a secret.

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#59354]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

When #58720 merged, it broke any Dashboard users that:
1. Directly use `cluster/addons/dashboard/dashboard-controller.yaml` from this project to configure their Dashboard.
and
2. Have a Dashboard cert/key pair as a secret rather than using one autogenerated by Dashboard.

**What you expected to happen**:

If users have a cert/key pair as a secret, Dashboard should use that. If they don't, then it should use its autogenerated one.

**Anything else we need to know?**:

Due to the other changes in #58720, a fix to revert the secret -> emptyDir change will need to wait until a new build of Dashboard has been released that includes https://github.com/kubernetes/dashboard/pull/2795

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/issues/57326
/close
