### ISSUE TITLE
`kubectl apply` on a apps/v1beta2 Deployment renders as extensions/v1beta1

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/kubernetes#59362]
/kind bug

Running `kubectl apply` on a `apps/v1beta2` deployment creates a deployment with apiVersion set to `extensions/v1beta1`, but the version in `kubectl.kubernetes.io/last-applied-configuration` is `v1beta2`. I'm not sure if the transformation is a bug or a feature. I expected the deployed resource to be of type `apps/v1beta2`, as requested.

Reproducing the error can be done on both v1.8 and v1.9 clusters, with the respective `kubectl` client version matching the cluster version.

```
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apps-bug
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: apps-bug
        image: nginx
EOF

deployment "apps-bug" created

$ kubectl get deployment apps-bug -o jsonpath="{.apiVersion}"
extensions/v1beta1

$ kubectl apply view-last-applied deployment apps-bug
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations: {}
  name: apps-bug
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: apps-bug
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8/1.9
- Cloud provider or hardware configuration: minikube for local testing, but can be seen on other cloud providers

**Comment by nikhita** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/58895.

Copying @liggitt's reply from https://github.com/kubernetes/kubernetes/issues/58895:

> kubectl get deployment without qualification gets the first version of deployments the server indicates it is capable of returning.

> The deployment you created can be retrieved in any of the supported versions. To get a specific group or version, fully qualify your get request:

```
kubectl get deployment.apps …
kubectl get deployment.v1beta2.apps … 
```

**Comment by bacongobbler** [comment]
thanks for pointing out the dupe! Couldn't find it when searching. Closing.
