### ISSUE TITLE
Node bootstrapping certificate should include an IP SAN

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes/kubernetes#59372]
/kind feature

**What happened**:

I created a cluster with kubeadm, and then configured the API Server flag `--kubelet-certificate-authority`. Everything seemed fine until I tried to use helm, at which point I got the following error:

```
Error: forwarding ports: error upgrading connection: error dialing backend: x509: cannot validate certificate for 10.70.35.7 because it doesn't contain any IP SANs
```

**What you expected to happen**:

When boostrapping the nodes, an IP SAN should be included in the CSR generated and sent via the kubelet. This seems to be handled by this function in `client-go`:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/certificate/csr/csr.go#L51

Which has no option to in include a node IP in the CSR.

**How to reproduce it (as minimally and precisely as possible)**:

Simply enable `kubelet-certificate-authority` checking on the API Server

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g. from /etc/os-release): CentOS 7
- Install tools: kubeadm

**Comment by liggitt** [comment]
The linked method requests a client certificate, not a serving certificate. The resulting certificate is not intended to be used for serving. 

/close

**Comment by liggitt** [comment]
Node bootstrapping only obtains a client certificate. A serving certificate is either 1) provided via command line flags, 2) self signed by the kubelet, or 3) requested via (separate) CSR if the alpha "rotate serving certs" feature is enabled.

**Comment by seh** [comment]
Note, however, then when the _kubelet_ generates the serving certificate when the `--rotate-certificates=true` flag is present, the resulting certificate [lacks the IP address SAN](https://sourcegraph.com/github.com/kubernetes/kubernetes@098996737475235ae6488048797227023e873ef9/-/blob/cmd/kubelet/app/server.go#L762) unless [the hostname happens to parse as an IP address](https://sourcegraph.com/github.com/kubernetes/client-go@master/-/blob/util/cert/cert.go#L187).

**Comment by stealthybox** [comment]
On a kubeadm v1.11.0 cluster, I can confirm that my kubelets do not have IP's in the SAN's:
```shell
for ip in $(k get no -owide --no-headers | awk '{print $6}'); do
  true | openssl s_client -connect ${ip}:10250 2>/dev/null | openssl x509 -noout -text | egrep 'DNS:|IP:'
done

# only outputs DNS SAN's
```

**Comment by stealthybox** [comment]
This requires me to set `&insecure=true` when doing webhook authentication from metrics-server and kube-prometheus.

**Comment by liggitt** [comment]
commented on https://github.com/kubernetes-incubator/metrics-server/issues/95#issuecomment-413229820 about the three methods for kubelets to get their serving certificates.

**Comment by dkoshkin** [comment]
@liggitt Im seeing the same behavior as @seh and @stealthybox 

Running a `v1.12.0-beta.0` cluster.
The node is reporting the IP:
```
status:
  addresses:
  - address: 9.0.5.3
    type: InternalIP
  - address: kube-node-0-kubelet.kubernetes
    type: Hostname
```
Bu the cert only has the DNS:
```
            X509v3 Subject Alternative Name:
                DNS:kube-node-0-kubelet.kubernetes
```

**Comment by liggitt** [comment]
what are your kubelet startup arguments?

**Comment by liggitt** [comment]
> when the _kubelet_ generates the serving certificate when the `--rotate-certificates=true` flag is present, the resulting certificate [lacks the IP address SAN](https://sourcegraph.com/github.com/kubernetes/kubernetes@098996737475235ae6488048797227023e873ef9/-/blob/cmd/kubelet/app/server.go#L762) unless [the hostname happens to parse as an IP address](https://sourcegraph.com/github.com/kubernetes/client-go@master/-/blob/util/cert/cert.go#L187).

when the kubelet generates the serving certificate itself, it is a self-signed certificate and TLS verification against it will always fail. whether it includes an IP SAN is secondary to the fact that it is a self-signed certificate and would not be trusted by anything verifying TLS connections to it against a configured trust bundle.

also, the `--rotate-certificates` flag only enabled rotation of client certificates. in 1.12, the kubelet can request serving certificates via the CSR API as well (xref https://github.com/kubernetes/kubernetes/pull/65480/files)

**Comment by dkoshkin** [comment]
@liggitt I modified the deployment with `--rotate-server-certificates` but I think I might still be missing a flag somewhere as I am still getting:
```
http: TLS handshake error from 192.168.1.3:43064: no serving certificate available for the kubelet
```
And only the client cert is generated `kubelet-client-current.pem`
Also I'm seeing the `csr` but its in `Pending` state
```
Name:               csr-8p2mt
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Mon, 03 Sep 2018 16:22:44 +0000
Requesting User:    system:node:kube-node-0-kubelet.kubernetes.mesos
Status:             Pending
Subject:
  Common Name:    system:node:kube-node-0-kubelet.kubernetes.mesos
  Serial Number:
  Organization:   system:nodes
Subject Alternative Names:
         DNS Names:     kube-node-0-kubelet.kubernetes.mesos
         IP Addresses:  9.0.3.70
Events:  <none>
```
Where the client csr was `Approved`
```
Name:               node-csr-6WPdWZFC4wrgtEBg_Tc8Q2MfOe5i9Vmd0W9jBjsAhSk
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Mon, 03 Sep 2018 16:10:15 +0000
Requesting User:    system:bootstrap:m50zjz
Status:             Approved,Issued
Subject:
         Common Name:    system:node:kube-node-0-kubelet.kubernetes.mesos
         Serial Number:
         Organization:   system:nodes
Events:  <none>
```

Flag for apisever, controller-manager and kubelet below:
```
- kube-apiserver
- --allow-privileged=true
- --authorization-mode=RBAC,Node
- --bind-address=0.0.0.0
- --client-ca-file=/data/client-ca-crt.pem
- --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction
- --enable-aggregator-routing=true
- --enable-bootstrap-token-auth=true
- --endpoint-reconciler-type=lease
- --etcd-cafile=/data/ca-crt.pem
- --etcd-certfile=/data/kube-apiserver-crt.pem
- --etcd-keyfile=/data/kube-apiserver-key.pem
- --etcd-prefix="/registry/cluster-0"
- --etcd-servers=https://etcd-0-peer:2379,https://etcd-1-peer:2379,https://etcd-2-peer:2379
- --feature-gates=RotateKubeletServerCertificate=true,RotateKubeletClientCertificate=true
- --insecure-bind-address=127.0.0.1
- --insecure-port=9000
- --kubelet-client-certificate=/data/kube-apiserver-crt.pem
- --kubelet-client-key=/data/kube-apiserver-key.pem
- --kubelet-preferred-address-types=InternalIP,InternalDNS,Hostname
- --max-mutating-requests-inflight=400
- --max-requests-inflight=1200
- --proxy-client-cert-file=/data/proxy-client-crt.pem
- --proxy-client-key-file=/data/proxy-client-key.pem
- --requestheader-allowed-names=aggregator
- --requestheader-client-ca-file=/data/aggregator-ca-crt.pem
- --requestheader-extra-headers-prefix=X-Remote-Extra-
- --requestheader-group-headers=X-Remote-Group
- --requestheader-username-headers=X-Remote-User
- --secure-port=6443
- --service-account-key-file=/data/service-account-key.pem
- --service-cluster-ip-range=10.100.0.0/16
- --target-ram-mb=4096
- --tls-cert-file=/data/kube-apiserver-crt.pem
- --tls-private-key-file=/data/kube-apiserver-key.pem
```
```
- kube-controller-manager
- --allocate-node-cidrs=true
- --bind-address=127.0.0.1
- --cluster-cidr=192.168.0.0/16
- --cluster-signing-cert-file=/data/internal-ca-crt.pem
- --cluster-signing-key-file=/data/internal-ca-key.pem
- --controllers=*,tokencleaner
- --feature-gates=RotateKubeletServerCertificate=true,RotateKubeletClientCertificate=true
- --kubeconfig=/data/kube-control-plane.conf
- --leader-elect=true
- --root-ca-file=/data/ca-crt.pem
- --service-account-private-key-file=/data/service-account-key.pem
- --use-service-account-credentials=true
```
```
./kubelet 
--address=9.0.3.70
--allow-privileged=true 
--anonymous-auth=false 
--authentication-token-webhook=true 
--authorization-mode=Webhook 
--bootstrap-kubeconfig=bootstrap.kubeconfig 
--cert-dir=/var/lib/mesos/slave/slaves/f78d0633-5537-4fd2-bac6-6673f5284275-S1/frameworks/f78d0633-5537-4fd2-bac6-6673f5284275-0006/executors/kubernetes__kube-node__99834ec8-03b3-43e8-ab81-40e952389235/runs/168b2309-284d-4450-8620-355e0005a91b/containers/0a0ea8cf-bc26-42e0-8aa5-be2ce019386d 
--cgroup-driver=cgroupfs 
--cgroup-root=/mesos/168b2309-284d-4450-8620-355e0005a91b 
--client-ca-file=ca-crt.pem 
--cluster-dns=9.0.3.70
--cluster-domain=cluster.local 
--event-burst=30 
--event-qps=15 
--eviction-hard=nodefs.available<100Mi,imagefs.available<100Mi 
--fail-swap-on=false 
--feature-gates=RotateKubeletServerCertificate=true,RotateKubeletClientCertificate=true 
--healthz-bind-address=9.0.3.70
--hostname-override=kube-node-0-kubelet.kubernetes.mesos 
--kube-api-burst=30 
--kube-api-qps=15 
--kube-reserved=cpu=1000m,memory=1024000Ki 
--kubeconfig=kubeconfig.yaml 
--max-pods=100 
--network-plugin=cni 
--node-ip=9.0.3.70 
--node-labels=name=kube-node-0-kubelet.kubernetes.mesos, 
--pod-cidr=192.168.0.0/16 
--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.1 
--pod-manifest-path=/var/lib/mesos/slave/slaves/f78d0633-5537-4fd2-bac6-6673f5284275-S1/frameworks/f78d0633-5537-4fd2-bac6-6673f5284275-0006/executors/kubernetes__kube-node__99834ec8-03b3-43e8-ab81-40e952389235/runs/168b2309-284d-4450-8620-355e0005a91b/containers/0a0ea8cf-bc26-42e0-8aa5-be2ce019386d/manifests/ 
--pods-per-core=10 
--read-only-port=0
--rotate-certificates=true 
--rotate-server-certificates=true 
--system-reserved=cpu=5000m,memory=27644148Ki
```
Thanks for the help!

**Comment by liggitt** [comment]
Serving certificate approval requires you to provide your own approver. The controller manager doesn't have enough information today to know if the SANs requested by the node are appropriate.
