### ISSUE TITLE
Ingress  ResourceVersion change  make many event  cause etcd  down

### ISSUE THREAD

**Issue by piaoyu** [kubernetes/kubernetes#59395]
**What happened**:   Ingress  ResourceVersion change  make many event  cause etcd  down
 
APIVersion:"extensions", ResourceVersion:"362943464", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/****
I0206 12:57:57.300714      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"answer2-task-prod-sz", UID:"c9437e72-019c-11e8-9112-6c92bf6b352c", APIVersion:"extensions", ResourceVersion:"362943468", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/***
I0206 12:57:57.300829      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"micro-chace-start-prod", UID:"43b09dfe-dc29-11e7-9fe8-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943469", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/****
I0206 12:57:57.300918      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"submitmeeting-ct-prod-sz", UID:"54f96838-fe94-11e7-9e09-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943473", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/****
I0206 12:57:57.301423      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"answer2-user-service-prod-sz", UID:"40f5bad9-003f-11e8-9112-6c92bf6b352c", APIVersion:"extensions", ResourceVersion:"362943474", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/**** 
I0206 12:57:57.301565      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"micro-chance-prod", UID:"8b5d2bea-d41e-11e7-8fe2-6c92bf6b352c", APIVersion:"extensions", ResourceVersion:"362943475", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/*****
I0206 12:57:57.301635      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"question-master-prod-sz", UID:"26b5d0f4-00fb-11e8-9112-6c92bf6b352c", APIVersion:"extensions", ResourceVersion:"362943476", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/question-master-prod-sz
I0206 12:57:57.301760      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"answer2-question-prod-sz", UID:"3618a647-00f0-11e8-95a2-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943477", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/*****
I0206 12:57:57.302251      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"vipserver-prod", UID:"76fcfbcd-cb90-11e7-b50b-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943478", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/****
I0206 12:57:57.302368      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"***** ", UID:"ee21ca96-0675-11e8-bb01-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943479", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/*****
I0206 12:57:57.302469      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"micro-task-start-prod", UID:"15c66199-efab-11e7-9e09-6c92bf6b3970", APIVersion:"extensions", ResourceVersion:"362943480", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/*****
I0206 12:57:57.302572      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"image-recognition-prod", UID:"0e05e12f-f5db-11e7-9112-6c92bf6b352c", APIVersion:"extensions", ResourceVersion:"362943485", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/******
I0206 12:57:57.304047      62 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"gnucyw", Name:"dthb4wxmp-prod-sz", UID:"b047fdf5-0814-11e8-9e22-6c92bf6b268c", APIVersion:"extensions", ResourceVersion:"362943487", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress gnucyw/****

[root@xxxx /home1/system/api-server]
#kubectl get cm  ingress-controller-leader-nginx -n kube-system  -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ingress-controller-leader-nginx","leaseDurationSeconds":30,"acquireTime":"2017-10-18T09:57:02Z","renewTime":"2018-02-06T05:23:41Z","leaderTransitions":0}'
  creationTimestamp: 2017-10-18T09:57:02Z
  name: ingress-controller-leader-nginx
  namespace: kube-system
  resourceVersion: "363435659"
  selfLink: /api/v1/namespaces/kube-system/configmaps/ingress-controller-leader-nginx
  uid: b06cf122-b3ea-11e7-9f5c-6c92bf6b1a70

[root@xxxxx /home1/system/api-server]
#kubectl get cm  ingress-controller-leader-nginx -n kube-system  -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ingress-controller-leader-nginx","leaseDurationSeconds":30,"acquireTime":"2017-10-18T09:57:02Z","renewTime":"2018-02-06T05:24:38Z","leaderTransitions":0}'
  creationTimestamp: 2017-10-18T09:57:02Z
  name: ingress-controller-leader-nginx
  namespace: kube-system
  resourceVersion: "363448807"
  selfLink: /api/v1/namespaces/kube-system/configmaps/ingress-controller-leader-nginx
  uid: b06cf122-b3ea-11e7-9f5c-6c92bf6b1a70

Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-dirty", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"dirty", BuildDate:"2018-01-16T08:20:16Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-dirty", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"dirty", BuildDate:"2018-01-16T08:20:16Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

/sig scalability

**Comment by wojtek-t** [comment]
Closing due to lack of information for any debugging.
