### ISSUE TITLE
Pulling images from AWS ECR with docker credsStore option

### ISSUE THREAD

**Issue by Imunhatep** [kubernetes/kubernetes#59406]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug
/sig aws

**What happened:**

Configuring docker authentication with:
```json
{
     "credsStore": "ecr-login"
}
```
This config.json paths are: 
~/.docker/config.json
/var/lib/kubelet/config.json

Docker pull cli works as expected, though kubelet cant pull image.

```log
kubelet[9952]: I0206 09:25:47.031324    9952 kuberuntime_manager.go:571] computePodActions got {KillPod:false CreateSandbox:false SandboxID:dcc95ded9ca8d4cafbb5a5b0321266acf7a605dceab1131195c405e7d3632e46 Attempt:0 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[]} for pod "private-job-deploy-79ccdb8877-9ktbf_default(1bdffc14-0b1e-11e8-821e-027319893e47)"
kubelet[9952]: I0206 09:25:47.032382    9952 kuberuntime_manager.go:732] container start failed: ImagePullBackOff: Back-off pulling image "123123123.dkr.ecr.eu-central-1.amazonaws.com/private-job:1.70.20"
kubelet[9952]: E0206 09:25:47.032595    9952 pod_workers.go:186] Error syncing pod 1bdffc14-0b1e-11e8-821e-027319893e47 ("private-job-deploy-79ccdb8877-9ktbf_default(1bdffc14-0b1e-11e8-821e-027319893e47)"), skipping: failed to "StartContainer" for "private-job-container" with ImagePullBackOff: "Back-off pulling image \"123123123.dkr.ecr.eu-central-1.amazonaws.com/private-job:1.70.20\""
kubelet[9952]: I0206 09:25:47.033096    9952 server.go:231] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"private-job-deploy-79ccdb8877-9ktbf", UID:"1bdffc14-0b1e-11e8-821e-027319893e47", APIVersion:"v1", ResourceVersion:"86709", FieldPath:"spec.containers{private-job-container}"}): type: 'Warning' reason: 'Failed' Error: ImagePullBackOff
kubelet[9952]: I0206 09:25:47.033296    9952 server.go:231] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"private-job-deploy-79ccdb8877-9ktbf", UID:"1bdffc14-0b1e-11e8-821e-027319893e47", APIVersion:"v1", ResourceVersion:"86709", FieldPath:"spec.containers{private-job-container}"}): type: 'Normal' reason: 'BackOff' Back-off pulling image "123123123.dkr.ecr.eu-central-1.amazonaws.com/private-job:1.70.20"
```

**What you expected to happen:**

Kubelet successfully pulls out image from ECR

**How to reproduce it (as minimally and precisely as possible):**

Using standalone kubelet with docker authentication helper from: [https://github.com/awslabs/amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) and configured docker by the docs

**Anything else we need to know?:**

Attempting to use Docker images from a private ECR on EC2 Instance.

If I provide token access with aws ecr get-login means, kubelet does work.

Alternative docker config does not work either:
```json
{
	"credHelpers": {
		"123123123.dkr.ecr.eu-central-1.amazonaws.com": "ecr-login"
	}
}
```

**Environment:**

Ubuntu 16.04

# kubelet --version
Kubernetes v1.9.2

Installed with kubeadm.

Cloud provider or hardware configuration: AWS EC2

**Comment by liztio** [comment]
working on this with @melaniecebula

**Comment by liztio** [comment]
We spent a lot of time looking at this issue, and unfortunately it's trickier than it looks

We're pretty sure this should work, based on the [this blog post](https://medium.com/@xynova/keeping-aws-registry-pull-credentials-fresh-in-kubernetes-2d123f581ca6), but we couldn't get the cloud provider logins to work. 

I think this does currently work, but it's not as simple to fix as this issue applies
