### ISSUE TITLE
Automatically load ipvs required kernel modules in startup scripts

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#59402]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Per #56732, seems init container can not cover all user cases - running kube-proxy without container for example. 

We need to automatically load kernel modules in all user cases so that declaring IPVS proxy GA in v1.10. Following are the list which should be coverd.

- [ ] kubeadm
- [ ] kubernetes-anywhere
- [ ] gce

cc @Lion-Wei @rramkumar1 @stewart-yu

**Comment by stewart-yu** [comment]
kubeadm 
/assign

**Comment by Lion-Wei** [comment]
I can do kubernetes-anywhere part : )

**Comment by rramkumar1** [comment]
I don't mind taking care of the gce part

**Comment by rramkumar1** [comment]
I would also just like to mention that loading the ipvs modules is a secondary goal here. The most important thing is making sure that the environment variable KUBE_PROXY_MODE is plumbed throughout all startup scripts. This will ensure that an ipvs cluster can be easily brought up and tested.

**Comment by Lion-Wei** [comment]
@rramkumar1 Sorry about that, I didn't notice. : (
I used gce built ipvs CI earlier, pretty familiar with this part.

**Comment by uablrek** [comment]
Please consider testing that the function exist, not that modules are loaded. I use a small dedicated system for test and had ipvs linked into the kernel (i.e no modules). I had to rebuild the kernel with modules for ipvs.
Almost any "ipvsadm" command should be sufficient to test the ipvs function and load the modules automatically if necessary. Ipvs is not the first to check for modules in Kubernetes but the check should be simple.
Best Regards,
L Ekman

**Comment by rramkumar1** [comment]
@m1093782566 What do you think about the above proposal?

**Comment by m1093782566** [comment]
I think all of them are already in.
