### ISSUE TITLE
Should we support pass request.Context into `attributesRecord`?

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#59415]
Now just think of one use cases:  

1. we want to support audit log for admission plugins.
2. pass something through admission plugins

**Comment by liggitt** [comment]
I don't think so... that object is serializable today, and request.Context would never be serializable

/close

**Comment by hzxuzhonghu** [comment]
>I don't think so... that object is serializable today for compatibility with externalized admission hooks, and request.Context would never be serializable

Our product has a private admission plugin in-tree and really need context to pass something useful.
Though this is just a private requirement, seems not common.

**Comment by hzxuzhonghu** [comment]
But if we want audit for in-tree plugins, is there a way to do?

**Comment by liggitt** [comment]
See work in progress in https://github.com/kubernetes/kubernetes/pull/58143
