### ISSUE TITLE
what is the difference between container_manager_linux.go in kubelet and dockershim?

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#59412]
I find two container_manager_linux in kubelet and they are all used.What is the diference between both of them?
One of them is kubelet/cm/container_manager_linux.go,another one is kubelet/dockershim/cm/container_manager_linux.go.
If I want to add some cgroup args to kubelet ,which code should I focus on?

/sig node
@dims

**Comment by jhorwit2** [comment]
@mjaow Please use the mentioned contact methods [here](https://github.com/kubernetes/community/tree/master/sig-node#contact) for asking questions like this. You'll receive prompter responses. 

Thanks!

/close
