### ISSUE TITLE
kubectl exec <pod> -it bash，and auto exit pod after 1 minitue

### ISSUE THREAD

**Issue by lf1029698952** [kubernetes/kubernetes#59411]
/kind bug

**What happened**:
I upgrade my k8s cluster to v1.7.11,
I use kubectl exec <pod> -it bash to enter the pod out of cluster, but it will auto exit pod after 1 minitue, 
and I kubectl exec <pod> -it bash in cluster master node, it dones't auto exit. 
but This situation does not exist in kubernetes v1.4.6

I suspect network firewall.
Is there anyone in this situation? Please guide to me, thanks!

```
date && kubectl exec php-devops-lark-web.dev.test-3486201886-0blhb -it bash --context=cq17 && date
2018年 02月 06日 星期二 09:59:52 UTC
[root@php-devops-lark-web data]# 
2018年 02月 06日 星期二 10:00:43 UTC
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- OS：CentOS Linux release 7.4.1708 (Core)
- Kernel: 3.10.0-693.el7.x86_64

**Comment by lf1029698952** [comment]
This is usually the load balancer timeout in front of an apiserver. Check the timeout from the ELB.
Thanks!
[https://github.com/kubernetes/kubernetes/issues/15702](url)

**Comment by lf1029698952** [comment]
This is my haproxy timeout config 50s, modify 10m, fix it.
I hope to help people who have the same situation with me.

**Comment by jhorwit2** [comment]
Sounds like this is resolved then! Good to hear!

/close

**Comment by Bala2103** [comment]
In my case there is no way to change the haproxy timout, I am using the below command to extend the session
while :; do sleep 59; echo -n ' ' >&2; done &

Please let me know . if there is any other suggestion for the people who have no access to those configurations

**Comment by anantadwi13** [comment]
> In my case there is no way to change the haproxy timout, I am using the below command to extend the session
> while :; do sleep 59; echo -n ' ' >&2; done &
> 
> Please let me know . if there is any other suggestion for the people who have no access to those configurations

perhaps you could send a null char instead of a whitespace
`while :; do sleep 10; echo -ne '\0' >&2; done &`
