### ISSUE TITLE
TestCRDDeletionCascading flake

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#59426]
@kubernetes/sig-api-machinery-bugs 
/kind test-flake
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59325/pull-kubernetes-unit/78868/

**Comment by jpbetz** [comment]
cc @ironcladlou @caesarxuchao

**Comment by rosti** [comment]
Saw this on #58960

**Comment by caesarxuchao** [comment]
Sorry, I haven't had time to look into this.

Let's see if @jennybuckley can get to this earlier than I do.

**Comment by thockin** [comment]
I'm seeing this a lot in the rush to code freeze.

**Comment by jberkus** [comment]
@thockin @caesarxuchao if this is actually a 1.10 bug, can you add status/approved-for-milestone to it?  Thanks.

**Comment by caesarxuchao** [comment]
Something suspicious from the [log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/59325/pull-kubernetes-unit/78868/artifacts/junit_e9d37341e9f7ab19ac436e5365ba6ae7c20eea71_20180206-163546.stdout), but probably it's not related to the failure:

```
I0206 16:44:45.416742   25213 graph_builder.go:655] 02f14c23-0b5d-11e8-ba73-0242ac110002 doesn't exist in the graph, this shouldn't happen
```

**Comment by caesarxuchao** [comment]
The garbage collector's behavior looks right, it does delete the dependent configmap:

```
I0206 16:44:44.457264   25213 garbagecollector.go:466] delete object [v1/ConfigMap, namespace: crd-mixed, name: dependentpn9mf, uid: 02f71c6a-0b5d-11e8-ba73-0242ac110002] with propagation policy Background
```

The tested start at 16:44:27.749419, and failed with "test timed out after 5m0s" at 16:44:50.786983. I'll check if other failed cases have the same causes.

**Comment by caesarxuchao** [comment]
The "Kubernetes Aggregated Failures" shows there is no "TestCRDDeletionCascading" failure in the last 67394 tests (https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fgarbagecollector). Maybe I used the wrong tool? cc @krzyzacy

**Comment by krzyzacy** [comment]
cc @rmmh because triage does not support pull-kubernetes-unit? I cannot find `TestCRDDeletionCascading` in https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-unit as well

**Comment by jennybuckley** [comment]
Most of the failures in https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit seem to from TestCRDDeletionCascading

**Comment by caesarxuchao** [comment]
@jennybuckley gave a new failure sample: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60331/pull-kubernetes-unit/83015/#k8siokubernetestestintegrationgarbagecollector-testcrddeletioncascading. (And the triage dashboard can't find it).

Anyway, the test [log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/60331/pull-kubernetes-unit/83015/artifacts/junit_e9d37341e9f7ab19ac436e5365ba6ae7c20eea71_20180226-204814.stdout) showed similar behavior.

The tested started at I0226 20:57:02.82247.
The gc behaved correctly:
```
I0226 20:57:19.869254   26923 garbagecollector.go:466] delete object [v1/ConfigMap, namespace: crd-mixed, name: dependentxkkr2, uid: 9c8e8ae2-1b37-11e8-804b-0242ac110002] with propagation policy Background
```
And the 5min timeout occurred 23s after the test began.
```
I0226 20:57:25.773446   26923 garbagecollector.go:177] no resource updates from discovery, skipping garbage collector sync
panic: test timed out after 5m0s
```

I'll check what's the 5min timeout for.

**Comment by caesarxuchao** [comment]
The 5 min timeout is for all the tests in the test/integration/garbagecollector package. The tests are run sequentially, so `TestCRDDeletionCascading` is the last one to run, and unfortunately uses up the 5 min quota. The two logs I looked into showed the test itself was healthy. We just need to increase the timeout limit for this package.

**Comment by caesarxuchao** [comment]
@krzyzacy found a lot of failure samples here: https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-unit. The first 11 of them failed because the 5m timeout.

**Comment by liggitt** [comment]
http://storage.googleapis.com/k8s-metrics/flakes-latest.json Indicates this is still present and severe.

**Comment by caesarxuchao** [comment]
I was trying to get recent failures, it seems we recently moved intergration tests out of the unit test suites,  https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&width=5, where there is no failure yet.

I'll try again tomorrow.

**Comment by krzyzacy** [comment]
(we rename the job this afternoon, it was named kubernetes-unit but only runs integration test)

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&width=5&include-filter-by-regex=TestCRDDeletionCascading

that looks all green so far

**Comment by liggitt** [comment]
Can we also check run time of the tests in that package over the past couple weeks? It seems like this just spiked. Did our tests slow down, or did we add tests to that package?

**Comment by jennybuckley** [comment]
@liggit
as far as I can tell the runtime of the test didn't spike ( #24509 shows the test running in just over 300s and also included the original bump of the timeout from 300s to 600s), but the timeout was accidentallt decreased from 600s back to 300s as an unintended side effect of #57521

**Comment by liggitt** [comment]
ah, ok

**Comment by jennybuckley** [comment]
@liggitt 
Since it has passed the last 26 times, is this safe to reclose
