### ISSUE TITLE
IPVS should have more e2e tests in CI

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#59427]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

IPVS only has one test currently in OSS CI and that test has been failing in the bootstrapping stage for quite a while. 

https://k8s-testgrid.appspot.com/sig-network-gce#kubeadm-gce-ipvs

Not only does this test need to be fixed, but more tests need to be added before IPVS can go GA.

- [x] Fix kubeadm test
- [x] Run sig-network tests
- [x] Run ingress tests
- [ ] Test against Network Policy

Most likely, #59402 is a prerequisite for this work.

/sig network
/area ipvs

**Comment by Lion-Wei** [comment]
To be clear, you mean add ipvs CI jobs for different cloud providers, such as /cluster/gce built environment. Or mean fix current CI job and add more test cases?

**Comment by rramkumar1** [comment]
I would say for sure fix the kubeadm test that is failing.

After that, I would suggest adding a couple new CI jobs. In my opinion, if you are able to pass the sig-network tests and the ingress tests with ipvs enabled, then I would be pretty confident everything is working as expected. 

For example, https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce displays the results for the sig-network tests on gce. 

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ingress is the same for the ingress tests on gce. 

Anyways, to create a new job that runs the ipvs proxier you will need to complete the work for  #59402.

**Comment by rramkumar1** [comment]
All relevant action items have been addressed. 
/close
