### ISSUE TITLE
[flaky unit test] pull-kubernetes-bazel-test failing on pkg/master

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#59450]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/kind flake

**What happened**: Mutliple PRs are seeing the same flaky failure on bazel test running pkg/master

**What you expected to happen**: Test to pass

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:
Seeing the following in the log.

2018-02-06 22:37:40.535268 I | integration: terminating 825844212551372936 (unix://localhost:8258442125513729360)
WARNING: 2018/02/06 22:37:40 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:8258442125513729360: connect: no such file or directory"; Reconnecting to {localhost:8258442125513729360 0  <nil>}

Failure log can be found at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59010/pull-kubernetes-bazel-test/29614/

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhirajh** [comment]
Seeing this issue with my PR too: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59303/pull-kubernetes-bazel-test/29687/

**Comment by cheftako** [comment]
Also saw this on https://github.com/kubernetes/kubernetes/pull/59287

**Comment by jsafrane** [comment]
Three times in a row in #59607, however I don't see how a volume plugin PR could affect integration tests

**Comment by rosti** [comment]
Saw this on #58960

**Comment by mikedanese** [comment]
#59844 will speed up this test.

**Comment by mithrav** [comment]
Is this fixed now?

**Comment by mikedanese** [comment]
I'd still like to turn this into an integration test.

**Comment by AishSundar** [comment]
@mikedanese can we close this issue ? I am not seeing this in the top flakes anymore, so looks like the fix to extend timeout worked?

**Comment by lingsamuel** [comment]
I meet this today https://github.com/kubernetes/kubernetes/pull/96141
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96141/pull-kubernetes-bazel-test/1323641965127929856
