### ISSUE TITLE
kubeadm init problem: kube-proxy CrashLoopBackOff

### ISSUE THREAD

**Issue by kirsazlid** [kubernetes/kubernetes#59461]
OS Version: CentOS Linux release 7.4.1708 (Core)
K8s Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Docker Version: docker-ce.17.09.0
#######
After installing all components of k8s 1.9 on my server, and finishing some necessary steps such as turn off the swap, enable the kubelet, unify the value of Cgroup Driver between docker and kubelet, etc.
Then I try to initialize master by executing the command:
kubeadm init --kubernetes-version=v1.9.0 --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.199.211
There is the information below after the command executed:
[init] Using Kubernetes version: v1.9.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.09.0-ce. Max validated version: 17.03
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Starting the kubelet service
[certificates] Using the existing ca certificate and key.
[certificates] Using the existing apiserver certificate and key.
[certificates] Using the existing apiserver-kubelet-client certificate and key.
[certificates] Using the existing sa key.
[certificates] Using the existing front-proxy-ca certificate and key.
[certificates] Using the existing front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Using existing up-to-date KubeConfig file: "admin.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "kubelet.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "controller-manager.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[apiclient] All control plane components are healthy after 19.501140 seconds
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[markmaster] Will mark node k8s.master as master by adding a label and a taint
[markmaster] Master k8s.master tainted and labelled with key/value: node-role.kubernetes.io/master=""
[bootstraptoken] Using token: c2d65f.2c885de26823599e
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token c2d65f.2c885de26823599e 192.168.199.211:6443 --discovery-token-ca-cert-hash sha256:6fa47ddd6b6e05f01520314bee1c64b47d721d6da27e148de843fc60d103cffc
#######
Then executing this command: kubectl get po -n kube-system, get this result:
NAME                                 READY     STATUS              RESTARTS   AGE
etcd-k8s.master                      1/1       Running             0          28m
kube-apiserver-k8s.master            1/1       Running             0          28m
kube-controller-manager-k8s.master   1/1       Running             0          28m
kube-dns-6f4fd4bdf-ljwrd             0/3       ContainerCreating   0          29m
kube-proxy-t5lwg                     0/1       CrashLoopBackOff    2          29m
kube-scheduler-k8s.master            1/1       Running             0          28m

dns and proxy are disfunctional, see proxy logs: kubectl get logs -f kube-proxy-t5lwg -n kube-system, get this message:
I0207 04:54:28.263076       1 feature_gate.go:184] feature gates: map[]
error: unable to read certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt for default due to open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory

Then see dns logs: kubectl describe pod kube-dns-6f4fd4bdf-ljwrd -n kube-system, get this message:
Name:           kube-dns-6f4fd4bdf-ljwrd
Namespace:      kube-system
Node:           k8s.master/192.168.199.211
Start Time:     Wed, 07 Feb 2018 12:52:51 +0800
Labels:         k8s-app=kube-dns
                pod-template-hash=290980689
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/kube-dns-6f4fd4bdf
Containers:
  kubedns:
    Container ID:  
    Image:         gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
    Image ID:      
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-rkst9 (ro)
  dnsmasq:
    Container ID:  
    Image:         gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
    Image ID:      
    Ports:         53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --no-negcache
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-rkst9 (ro)
  sidecar:
    Container ID:  
    Image:         gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
    Image ID:      
    Port:          10054/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-rkst9 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-rkst9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-rkst9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                 Message
  ----     ------                  ----               ----                 -------
  Normal   Scheduled               7m                 default-scheduler    Successfully assigned kube-dns-6f4fd4bdf-ljwrd to k8s.master
  Normal   SuccessfulMountVolume   7m                 kubelet, k8s.master  MountVolume.SetUp succeeded for volume "kube-dns-config"
  Normal   SuccessfulMountVolume   7m                 kubelet, k8s.master  MountVolume.SetUp succeeded for volume "kube-dns-token-rkst9"
  Warning  FailedCreatePodSandBox  7m (x12 over 7m)   kubelet, k8s.master  Failed create pod sandbox.
  Normal   SandboxChanged          2m (x290 over 7m)  kubelet, k8s.master  Pod sandbox changed, it will be killed and re-created.
#############
I don't know where goes wrong with the initializing process, appreciating your suggestions, thank you.

**Comment by ttarczynski** [comment]
I observe a very similar issue:

**What happened**
* after a successful completion of `kubeadm init` I get `kube-proxy` with status `CrashLoopBackOff`
```
# kubectl -n kube-system get pods
NAME                                  READY     STATUS             RESTARTS   AGE
etcd-ksa-m1.blue                      1/1       Running            0          1m
kube-apiserver-ksa-m1.blue            1/1       Running            0          1m
kube-controller-manager-ksa-m1.blue   1/1       Running            0          1m
kube-dns-6f4fd4bdf-24hcr              0/3       Pending            0          2m
kube-proxy-n5lxp                      0/1       CrashLoopBackOff   4          2m
kube-scheduler-ksa-m1.blue            1/1       Running            0          1m
```
* there's an error in `kube-proxy` logs:
```
# kubectl -n kube-system logs kube-proxy-n5lxp
I0312 16:39:01.667127       1 feature_gate.go:190] feature gates: map[]
error: unable to read certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt for default due to open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
```

**What you expected to happen**:
* `kube-proxy` pod in status `Running` after a successful `kubeadm init`

**How to reproduce it (as minimally and precisely as possible)**:
```
# kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=172.24.21.171 --node-name ksa-m1.blue
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Starting the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [ksa-m1.blue kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.24.21.171]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[apiclient] All control plane components are healthy after 38.501700 seconds
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[markmaster] Will mark node ksa-m1.blue as master by adding a label and a taint
[markmaster] Master ksa-m1.blue tainted and labelled with key/value: node-role.kubernetes.io/master=""
[bootstraptoken] Using token: 768699.7d86d2cf02c04378
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy
  
Your Kubernetes master has initialized successfully!
  
To start using your cluster, you need to run the following as a regular user:
  
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  
You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/
  
You can now join any number of machines by running the following on each node
as root:
  
  kubeadm join --token 768699.7d86d2cf02c04378 172.24.21.171:6443 --discovery-token-ca-cert-hash sha256:0e96dbb29a43792dc8ad806348d0a551ab9caf1e1b2fc4d4246df883009d4e46
```

**Anything else we need to know?**:
* I run docker with the following options:
```
# ps -elf | egrep 8307
4 S root      8307     1  0  80   0 - 354612 do_wai 15:02 ?       00:00:34 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current -H unix:///var/run/docker.sock --ip-forward=true --iptables=true --ip-masq=true -G 498 --log-driver=json-file --log-opt max-size=100m --log-opt max-file=10 --disable-legacy-registry=false -H tcp://0.0.0.0:2375 -G 498
4 S root      8313  8307  0  80   0 - 102019 futex_ 15:02 ?       00:00:00 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc --runtime-args --systemd-cgroup=true
```
* and with the following `daemon.json` config:
```
# cat /etc/docker/daemon.json 
{
    "storage-driver": "devicemapper",
    "storage-opts": [
    "dm.thinpooldev=/dev/mapper/centos7-thinpool",
    "dm.use_deferred_removal=true",
    "dm.use_deferred_deletion=true"
    ]
}
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
VM on OpenStack / KVM
- OS (e.g. from /etc/os-release):
```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux ksa-m1.blue 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
# rpm -qa | egrep 'docker|kube|oci|container' | sort
container-selinux-2.36-1.gitff95335.el7.noarch
container-storage-setup-0.8.0-3.git1d27ecf.el7.noarch
docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
docker-client-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
docker-common-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
kubeadm-1.9.2-0.x86_64
kubectl-1.9.2-0.x86_64
kubelet-1.9.2-0.x86_64
kubernetes-cni-0.6.0-0.x86_64
oci-register-machine-0-3.14.gitcd1e331.el7.x86_64
oci-systemd-hook-0.1.14-2.git9b1e622.el7.x86_64
oci-umount-2.3.1-2.gitbf16163.el7.x86_64
```
- docker version
```
# docker version 
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64
```

**Comment by kirsazlid** [comment]
@ttarczynski Hi, I've not solved this problem yet, since this initializing process is automatic, I can't figure out the reason at all.

**Comment by ttarczynski** [comment]
@kirsazlid I've just found it's related to the docker systemd configuration. I got some docker configs written by puppet. 

* the `docker-mountflags.conf` seems to be causing the problem
* I had this config:
```
# cat /etc/systemd/system/docker.service.d/docker-mountflags.conf
[Service]
MountFlags=private
```
* I was able to fix the `kube-proxy` problem by changing this to the default value:

```
# cat /etc/systemd/system/docker.service.d/docker-mountflags.conf
[Service]
MountFlags=slave
```
* after this change I have `kube-proxy` with status `Running`

```
# kubectl -n kube-system get pods
NAME                                  READY     STATUS    RESTARTS   AGE
etcd-ksa-m1.blue                      1/1       Running   0          18m
kube-apiserver-ksa-m1.blue            1/1       Running   0          18m
kube-controller-manager-ksa-m1.blue   1/1       Running   0          18m
kube-dns-6f4fd4bdf-lsclt              0/3       Pending   0          19m
kube-proxy-g29bt                      1/1       Running   0          19m
kube-scheduler-ksa-m1.blue            1/1       Running   0          18m
```

**Comment by kirsazlid** [comment]
@ttarczynski Yeah, my question is the same as your's. I don't have this file named 'docker-mountflags.conf', but I added the option 'MountFlags=private' into /usr/lib/systemd/system/docker.service myself after installed docker, now removing this option solves this problem. Thanks bro~
