### ISSUE TITLE
The number of parallel workqueue should be settable

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#59460]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

In the actual production environment, scheduler shows different performance when I set the number of parallel workqueue. And after continuous testing, the number that eventually fits me is 14.So I suggest that we should configure it.

**What you expected to happen**:
In the case of the default number of concurrent (16) can be modified through the configuration file.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wgliang** [comment]
https://github.com/kubernetes/kubernetes/blob/fa85bf7094a8a503fede964b7038eed51360ffc7/pkg/scheduler/core/generic_scheduler.go#L332

**Comment by k82cn** [comment]
That's interesting, would you share your data?

/assign , I'm not sure whether Bobby has time to handle that, I'll create PR for that if the data is proved :).

**Comment by wgliang** [comment]
This is obvious, you can test in an effective environment.And I have completed this PR,I just want to know your opinions.

**Comment by wgliang** [comment]
Parallelism and response time line chart:

![1518074989053-image](https://user-images.githubusercontent.com/8739301/35960637-69eaeb48-0ce5-11e8-950d-0982aa31b394.png)

**Comment by k82cn** [comment]
No objection to the new parameters, it provides an option to the user.
Compare to 16, 14 give a 5ms improvement per pod?

**Comment by wgliang** [comment]
Yes, this is data obtained in the test environment, which can be increased by 10ms in the production environment (3w nodes) or even more. I think it is important for the user to adjust this parameter, depending on the size of the cluster or different production environments, and it is also important for the user to improve performance for 5-10 ms or more.

**Comment by dixudx** [comment]
Fantastic!
I think we should write this down to our documentations as well.

**Comment by tossmilestone** [comment]
@wgliang How many cpu cores on one of your test servers?

**Comment by wgliang** [comment]
@tossmilestone In the course of testing and found no direct relationship with the number of CPUs, the number of CPU is 4 and 32, the performance characteristics are the same.I think may be related to the size of the cluster, or others.

**Comment by tossmilestone** [comment]
@wgliang got it, thanks for you reply, it's very helpful!

**Comment by wgliang** [comment]
@tossmilestone This is why I have not fully understood so far, I have been seeking the relationship between the most valuable and the CPU, but never found. I hope you can do it! :).

**Comment by ravisantoshgudimetla** [comment]
@wgliang The stats and idea are really interesting and thanks a lot for sharing them. 
- I think its the number of nodes in the cluster and pods on each node on which the response time(I believe you are talking about time taken for node assignment by scheduler) depends. 
- What is the cluster size when you ran this test? In the above graph is the cluster size invariant?
- The parallelization might also depend on the go runtime. There are tunable parameters like GOMAXPROCS, NumCPU  etc on which response time or throughput may depend on.

**Comment by bsalamat** [comment]
I agree with @ravisantoshgudimetla. We assign one node to each thread when processing predicates. Therefore, the number of nodes in your cluster. Also, the number of CPU cores on your machine should matter for large clusters. What is the size of the cluster that you obtained the results for.

**Comment by wgliang** [comment]
@ravisantoshgudimetla @bsalamat
The cluster size is 3w nodes, the number of CPUs is 32 physical CPUs. I agree with your idea, but setting 16 to different environments is not a good choice for me, and we should provide more elegant The way. Allow users to adjust this parameter according to their own environment (CPU number or size of cluster).

**Comment by k82cn** [comment]
Good point on `GOMAXPROCS` :)

**Comment by wgliang** [comment]
@k82cn I have tried to adjust this parameter, the default is the number of CPU.And I also try to set this value to a larger value, but there is no more obvious effect.

**Comment by ravisantoshgudimetla** [comment]
@wgliang - 
> The cluster size is 3w nodes.

IIUC, you have 3 nodes in the cluster? If yes, I think increasing the number of cores is not going to speed up the process. Everything could be done on a single core and even it may be faster on a single core since we have sync.Wait in the code which may cause lock when used across cores. Can you please let us know the usage stats of cores. I think at this point, a tool like scheduler_perf(https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf) which simulates large clusters may be helpful.

**Comment by wgliang** [comment]
@ravisantoshgudimetla Yes,I agree with you, and this is maybe the most likely reason I think.
Anyway, what is your opinion on configuring this parameter?

**Comment by ravisantoshgudimetla** [comment]
@wgliang 
TBH, while I am not against having this parameter configurable, we need some quantifiable data to see benefits. I believe if we want to publish some documentation as "increasing threads to 32 improves performance by 10 fold on a 4 core node or something similar" the existing data is not enough. I will let @bsalamat and @k82cn to take a call here.

**Comment by bsalamat** [comment]
I agree with @ravisantoshgudimetla. Given that the parallelism in scheduler is done when we evaluate our predicates for each node, it makes more sense if we evaluate the effect on a larger cluster.
Giving users the option to set the number of threads is an interesting idea, but I have a feeling that almost no one would use it unless if there is a significant improvement over the current implementation.

**Comment by wgliang** [comment]
I agree with what you said, but from the actual results of our cluster, it still has some effect. So, I still recommend this parameter as an option, the default value is 16.

**Comment by k82cn** [comment]
>  I think we should give users more scalability and configurability as long as they can improve performance.

We always balance configurability and complexity; "data" is a good support, and we need to make sure this is top factor of performance :).

**Comment by wgliang** [comment]
I can not do in-depth testing in our production environment, and the data that comes from me alone is not representative, if I can. Perhaps we need to conduct a specific test on this parameter in different sizes of clusters to verify the effectiveness. Or people who have an environment can verify this feature.
