### ISSUE TITLE
"kubectl logs <pod> -f" gets stuck for high output logs

### ISSUE THREAD

**Issue by gce-2017** [kubernetes/kubernetes#59477]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/area kubectl
> /kind feature

**What happened**:
The output of `kubectl logs -f` gets stuck for high output logs. Restarting the command doesn't fix the issue.
**What you expected to happen**:
To continue getting output from the command.
**How to reproduce it (as minimally and precisely as possible)**:
$ gcloud container clusters create --cluster-version=1.8.6-gke.0 test 
$ kubectl run debug --image=alpine -- /bin/sh -c "while true ; do date ; sleep 0.001 ; done" 
$ kubectl logs <debug's_pods> -f 

**Anything else we need to know?**:
The command gets stuck after around 5 minutes running. It doesn't happen for less frequents logs (e.g. using "sleep 0.01" instead of "sleep 0.001").
This was tested in GKE (Kubernetes Engine) and Kubernetes on GCE clusters.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.6 on GKE and v1.9.2 on GCE
- Cloud provider or hardware configuration: Google Cloud Platform
- OS (e.g. from /etc/os-release): Container-Optimized OS (GKE version 63, GCE version 60)
- Kernel (e.g. `uname -a`):
GKE nodes:
Linux gke-cluster-1-default-pool-4643f8f5-s95q 4.4.86+ #1 SMP Thu Dec 7 20:11:11 PST 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
GCE master and nodes:
Linux kubernetes-master 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
Linux kubernetes-minion-group-c0fv 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

- Install tools: Followed https://kubernetes.io/docs/getting-started-guides/gce/ for GCE cluster
- Others:

**Comment by bpziegler** [comment]
I also see this problem

**Comment by mikebocian** [comment]
/reopen
Same here. Restart helps, but after a while its the same.

**Comment by ktrOpenSource** [comment]
This bug still exists. How do I reopen this issue?

**Comment by ababkov** [comment]
Yep see this same issue as well - particularly problematic for queue workers where log output can be very high in bursts.

**Comment by augustgerro** [comment]
And maybe will be useful output only last **_n_** logs with tail-like command
`kubectl logs -f --tail 100`

**Comment by jimf5** [comment]
OK, this issue still takes place.

**Comment by wu0407** [comment]
use `crictl logs   --tail 10 -f 910ba0b8fdaf4` stuck same with `kubectl logs --tail 10 -f`, so that may be kubelet or cri problem.
```
containerd containerd.io 1.6.20 2806fc1057397dbaeefbea0e4e17bddfbd388f38

kubelet --version
Kubernetes v1.23.17
```

**Comment by Pawan-Bishnoi** [comment]
https://github.com/kubernetes/kubectl/issues/1548
