### ISSUE TITLE
kubeadm init hangs after kubeadm reset with api server error PostStartHook "ca-registration" failed: 

### ISSUE THREAD

**Issue by jasonrooks** [kubernetes/kubernetes#59487]
/kind bug

**What happened**:
"kubeadm init" hangs for about 30 minutes or so then returns with failed message.  

**What you expected to happen**:
"kubeadm init" should complete within a couple of minutes with information on how to join the nodes. 

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh CentOS 7 install preformed the following steps
kubeadm init

It ran as expected and I was able to run
kubectl get pods

I decided I wanted to use flannel and saw that I needed to use "kubeadm init --pod-network-cidr=10.244.0.0/16" instead. So I ran
kubeadm reset
then
kubeadm init --pod-network-cidr=10.244.0.0/16
It again ran successfully but then I could not use kubectl. Every attempt returned
kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

I again tried
kubeadm reset
and
kubeadm init --pod-network-cidr=10.244.0.0/16

This time and every time after  kubeadm init just hangs.

**Anything else we need to know?**:
I think kubeadm reset is not removing all that it needs to or that the CA Authority has been corrupted. 

I see this in the api server container log
I0207 14:00:55.924649       1 logs.go:41] http: TLS handshake error from 10.1.4.141:32858: read tcp 10.1.4.141:6443->10.1.4.141:32858: read: connection reset by peer
I0207 14:00:55.924723       1 logs.go:41] http: TLS handshake error from 10.1.4.141:32860: EOF
PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition

systemctl status kubelet -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2018-02-07 06:43:52 MST; 6min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 24035 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─24035 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki

Feb 07 06:50:22 cre-kubmas-dev kubelet[24035]: E0207 06:50:22.031519   24035 pod_workers.go:186] Error syncing pod f5b8388da096b6f06ca6302aa4668d84 ("kube-apiserver-cre-kubmas-dev_kube-system(f5b8388da096b6f06ca6302aa4668d84)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kube-apiserver pod=kube-apiserver-cre-kubmas-dev_kube-system(f5b8388da096b6f06ca6302aa4668d84)"
Feb 07 06:50:22 cre-kubmas-dev kubelet[24035]: E0207 06:50:22.335368   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://10.1.4.141:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcre-kubmas-dev&limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:22 cre-kubmas-dev kubelet[24035]: E0207 06:50:22.336899   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.1.4.141:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcre-kubmas-dev&limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:22 cre-kubmas-dev kubelet[24035]: E0207 06:50:22.338004   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.1.4.141:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: I0207 06:50:23.318162   24035 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: I0207 06:50:23.324431   24035 kubelet_node_status.go:82] Attempting to register node cre-kubmas-dev
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: E0207 06:50:23.324962   24035 kubelet_node_status.go:106] Unable to register node "cre-kubmas-dev" with API server: Post https://10.1.4.141:6443/api/v1/nodes: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: E0207 06:50:23.336136   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://10.1.4.141:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcre-kubmas-dev&limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: E0207 06:50:23.337726   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.1.4.141:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcre-kubmas-dev&limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused
Feb 07 06:50:23 cre-kubmas-dev kubelet[24035]: E0207 06:50:23.338684   24035 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.1.4.141:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.1.4.141:6443: getsockopt: connection refused

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: OnPrem VMware vSphere

- OS (e.g. from /etc/os-release): centos-release-7-4.1708.el7.centos.x86_64

- Kernel (e.g. `uname -a`):Linux cre-kubmas-dev 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Others:

**Comment by jasonrooks** [comment]
I was able to get it working by 


```
kubeadm reset
yum remove kubelet kubeadm kubectl
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet
kubeadm init --pod-network-cidr=10.244.0.0/16
```

Just doing a kubeadm reset and init again did not work for me.

**Comment by makanijatin** [comment]
I think you dont need to do the complete reset again but only this part will solve the problem

I found the solution in the kubernetes documentation
while following the documentation dont forgot to create .kube directory using this command
mkdir -p $HOME/.kube

Because as you need this command it will move the .kube directory
mv $HOME/.kube $HOME/.kube.bak

https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/
