### ISSUE TITLE
Refactor kube/cloud-controller-manager bootstrap wiring

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#59483]
Both controller manager still share a lot of code. We should follow the apiserver example and introduce a split between modular option structs and config. Each options struct holds a number of flags and is able to validate and create a config out of it. This way we can reuse options between different control plane components.

TODO:
- [x] PR for an initial split https://github.com/kubernetes/kubernetes/pull/59582
- [ ] move kube-controller-manager controller startup file into a startup directory
- [ ] move more setup code from startControllers into the config
- [ ] split up the huge set of flags into smaller option structs. https://github.com/kubernetes/kubernetes/pull/59582#discussion_r167258028
- [x] turn `Serve` func into a handler chain builder https://github.com/kubernetes/kubernetes/pull/59582#discussion_r167258465
- [ ] remove system integration flag values (like address, port) from component config https://github.com/kubernetes/kubernetes/pull/59582#discussion_r167324830

Features:
- [x] re-use SecureServingOptions from apiserver, part of https://github.com/kubernetes/kubernetes/pull/59408
- [x] re-use authentication from apiserver

**Comment by deads2k** [comment]
I think this is a very good idea and the general tenor of https://github.com/kubernetes/kubernetes/pull/59408 is moving us in the right direction.

**Comment by jhorwit2** [comment]
cc @wlan0
