### ISSUE TITLE
email_verified should not be part of required claims for OIDC JWT Validation

### ISSUE THREAD

**Issue by sreetummidi** [kubernetes/kubernetes#59496]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report
/kind bug

**What happened**:
This is related to https://github.com/kubernetes/kubernetes/issues/46806
I am trying to integrate Cloud Foundry UAA (https://github.com/cloudfoundry/uaa) with kubernetes using the OIDC flow and the JWT  validation is failing on the kubernetes side with an error of email_verified is required.

1.  email_verified is not a required claim in the OIDC core spec 
2.  From a security point of view email_verified is useful when Self Service is enabled which is true of internet identity providers
3. Enterprise User Provisioning workflow in almost all cases is admin driven and not self service and email_verified becomes an obsolete claim. 

With things as they stand today, this flow is not conducive to Enterprise Identity Providers.

**What you expected to happen**:
Authentication should succeeed
**How to reproduce it (as minimally and precisely as possible)**:
Pass a JWT which is missing email_verified claim using the OIDC flow into kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-auth-bugs

**Comment by sreetummidi** [comment]
@kubernetes/sig-auth-bugs

**Comment by ericchiang** [comment]
> email_verified is not a required claim in the OIDC core spec

It's not marked optional either, which was the original motivation for taking the safe route and assuming false if it wasn't provided.

https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

This would be a feature for us to detect the presence of the `email_verified` claim and act differently if it isn't there.

Do any other providers do this? Almost all that I've worked with do support this claim.

**Comment by sreetummidi** [comment]
Hi @ericchiang ,

Enterprise providers like ADFS , Okta don't support this as part of the user schema.  There is the concept of whether a use is active/enabled which is not the same as email verified always.  If a user is not active, a token should not be minted in the first place.

I am trying to understand what additional security does email_verified provided in the context of entire identity providers where there is no self self service use creation.

Thanks,
Sree

**Comment by ericchiang** [comment]
> Enterprise providers like ADFS , Okta don't support this as part of the user schema. There is the concept of whether a use is active/enabled which is not the same as email verified always. If a user is not active, a token should not be minted in the first place.

Okta supports `email_verified`, but it looks like ADFS doesn't:

https://developer.okta.com/docs/api/resources/oidc#scope-dependent-claims-not-always-returned
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

> I am trying to understand what additional security does email_verified provided in the context of entire identity providers where there is no self self service use creation.

We don't know when the provider is self-service or not. On our end, makes the client logic uniform and less error prone instead of trying to reason about the intent of the provider.

There's some discussion when we enabled this validation, including some UAA notes. https://github.com/kubernetes/kubernetes/pull/36087, specifically https://github.com/kubernetes/kubernetes/pull/36087#discussion_r86864492

**Comment by sreetummidi** [comment]
More than 80% of the enterprise customers of Cloud Foundry are using either AD/ADFS . This becomes a breaking change.  UAA can add a email_verified claim. However its going to be of little value if the underlying AD doesn't propagate that.  My two cents is this check doesn't make sense in an enterprise set up

**Comment by ericchiang** [comment]
@rithujohn191 has agreed to take this (can't assign her because she's not part of the org)

/sig auth
/kind feature
/milestone v1.11
/priority important-longterm
/status approved-for-milestone
