### ISSUE TITLE
go-bindata library issue

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#59491]
It was noted on twitter (https://twitter.com/francesc/status/961249107020001280) that the author of go-bindata (https://github.com/jteeuwen/go-bindata) deleted their account, and someone new created an account under the same name to re-prop up the repo.

We should probably review this as the status of this library (currently vendored in k/k), and if we want to keep using it, fork it, etc.

https://github.com/kubernetes/kubernetes/commits/master/vendor/github.com/jteeuwen/go-bindata

cc: @sttts @thockin @mikedanese

**Comment by cblecker** [comment]
This was added to vendor here: https://github.com/kubernetes/kubernetes/pull/35373

**Comment by mikedanese** [comment]
This one is maintained by go bazel team and is much simpler than go-bindata:

https://github.com/bazelbuild/rules_go/blob/c584696cf0df17ef56bdea5c7dee726bd269dafd/go/tools/builders/embed.go
