### ISSUE TITLE
DELETE requests for some objects get response data with Object instead of Status object

### ISSUE THREAD

**Issue by masroorhasan** [kubernetes/kubernetes#59501]
/kind bug

**What happened**:
DELETE request for pod resource is returning the entire pod resource in the response instead of the Status resource.

**What you expected to happen**:
Expecting the serialized response data to contain the Status resource instead of the Pod resource. 

Here is the response from the API server:
![image](https://user-images.githubusercontent.com/802678/35937904-79edfc86-0bfc-11e8-925d-907ddbce45cc.png)

Expecting 'Status' response according to the API documentation:
https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#delete-58

**How to reproduce it (as minimally and precisely as possible)**:
Delete a Pod using a client where the HTTP call can be traced. Observe the JSON response. 

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Azure (deployed using acs-engine)
- OS (e.g. from /etc/os-release):
Master: Debian GNU/Linux 8 (jessie)
Agent: windows (windows server 2016 datacenter)
- Kernel (e.g. `uname -a`):
Master: 4.4.0-112-generic
Agent: 10.0 14393 (14393.2007.amd64fre.rs1_release.171231-1800)
- Install tools:
- Others:

**Comment by liggitt** [comment]
That's an issue with the documentation (and possibly the openapi doc). Returning the deleted object is intentional.

**Comment by jpbetz** [comment]
@yliaog

**Comment by masroorhasan** [comment]
Thanks @liggitt. If the defined behavior is that the deleted 'Pod' object should be returned then there is definitely a bug in docs as well as the swagger spec. The swagger spec shows that its expecting a 'Status' object as well:
![image](https://user-images.githubusercontent.com/802678/36006126-f9791528-0cef-11e8-908f-b19101c9664f.png)

**Comment by electricsam** [comment]
The DELETE Job endpoint has the same problem (DELETE /apis/batch/v1/namespaces/{namespace}/jobs/{name}).  The documentation states a Status response, but it is actually the deleted Pod.  FWIW, these documentation issues/bugs cause exceptions in the Kubernetes Java client (https://github.com/kubernetes-client/java/issues/205).

**Comment by liggitt** [comment]
this is true for all types that set `ReturnDeletedObject: true` in their storage configuration

```
$ grep -r "ReturnDeletedObject: true" pkg 2>/dev/null
pkg/registry/core/pod/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/podtemplate/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/persistentvolumeclaim/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/namespace/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/persistentvolume/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/serviceaccount/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/core/resourcequota/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/storage/volumeattachment/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/storage/storageclass/storage/storage.go:		ReturnDeletedObject: true,
pkg/registry/extensions/podsecuritypolicy/storage/storage.go:		ReturnDeletedObject: true,
```

**Comment by yliaog** [comment]
https://github.com/kubernetes/apiserver/blob/dd002fed291506760ba79a43ca21c9a5086a6a5d/pkg/endpoints/handlers/rest.go#L1020

it does not always return the object though. sometimes status is returned instead.

**Comment by liggitt** [comment]
>  sometimes status is returned instead.

Status is always a valid option to be returned (401, 403, 404, 500 errors always return Status objects)

**Comment by roycaihw** [comment]
It's a known issue https://github.com/kubernetes-client/java/issues/86#issuecomment-334981383, as @kondapally1989 pointed out in https://github.com/kubernetes-client/java/issues/205
`oneof` is not supported in OpenAPI v2

ref https://github.com/kubernetes/kubernetes/issues/25716
