### ISSUE TITLE
IPVS needs better documentation

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#59505]
/kind documentation

**What happened**:
IPVS needs to be documented more.  Specifically, the existing documentation needs to be updated to properly describe how to bring up a cluster with ipvs in the kubeadm, local and gce case. Furthermore, there needs to be another piece of documentation that describes the main differences between iptables and ipvs and also dives into implementation differences between the two (ex. ipset). 

It would also be really nice if there could be some screenshots detailing the difference between iptables and ipvs rules (i.e bring up a cluster, create a service, dump iptables and ipvs rules, compare)

All this documentation should be added to pkg/proxy/ipvs

/assign @m1093782566 
/area ipvs
/sig network

**Comment by m1093782566** [comment]
@islinwb

**Comment by rramkumar1** [comment]
@islinwb It would be nice if you would also be able to add a section which shows the ipvs rules for a simple clusterIP service such as kube-dns. Maybe even show the iptables rules that are also created for this service. This would be helpful debugging information
