### ISSUE TITLE
Update local volume plugin to support block volumes 

### ISSUE THREAD

**Issue by dhirajh** [kubernetes/kubernetes#59500]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
At this time, block volume API is available but is not supported by local volumes plugin.

**What you expected to happen**:
Enhance local volumes plugin to support block volumes.

**Anything else we need to know?**:
This work is part of the overall effort in https://github.com/kubernetes/features/issues/121

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhirajh** [comment]
@msau42

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests
