### ISSUE TITLE
Ref: value in swagger.json file should be a string

### ISSUE THREAD

**Issue by salrashid123** [kubernetes/kubernetes#59513]
/kind bug

The ref: value should be a plain string in swagger 2+ and in the json spec cited

that is, in
[https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json)

we have 

```json
io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps": {
      "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
      "properties": {
        "$ref": { 
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
```

the ref value should be just a string 

see:
swagger 2 specs:
- [https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#reference-object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#reference-object)

and from 
- [https://tools.ietf.org/html/draft-zyp-json-schema-04#ref-json-reference](https://tools.ietf.org/html/draft-zyp-json-schema-04#ref-json-reference)

leads to:
 - [https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03)

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.9.2

**Comment by mbohlool** [comment]
cc @nikhiljindal 
This is interesting. Problem here is "$ref" is a field name not a json schema reference. [check here.](https://github.com/mbohlool/kubernetes/blob/6133d84835c59f157a8fb4596f98d2d3cf828bef/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go#L23-L22)
it is a grey area, but my understanding of spec is "$ref" is not applicable as a key in "properties" and this "$ref" will be parsed as a simple name instead of a schema reference, do you have a reason to believe that is not a case? (e.g. a tool failing?)

**Comment by salrashid123** [comment]
/cc  @aljim

We'd like to use Google Cloud Deployment Manager's [type provider](https://cloud.google.com/deployment-manager/docs/configuration/type-providers/creating-type-provider) capability to read in the swagger file and use that to manage k8s object.  Our parser fails on reading the file.

I don't have a formal swagger validator but i did also tried plugging k8s swagger into   swagger.io's editor and see errors related to $ref

![image](https://user-images.githubusercontent.com/11149054/36037265-1e612e12-0d71-11e8-9c6f-09a7138d11b0.png)

**Comment by salrashid123** [comment]
I looked  into this again and I think you're correct though i don't have a specific spec to cite precisely.

I can't repro the error above w/ the swagger editor w/ the snippet below nor with the swagger specs for k8s (must've been something different i did above)

The following spec is equivalent the issue cited originally and when i add it to the swagger editor, its accepted w/o errors:
```yaml
swagger: '2.0'
info:
  title: sample API
  version: 1.0.0
host: api.uber.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /products:
    get:
      summary: Product Types
      operationId: get_products
      parameters:
        - name: latitude
          in: query
          type: number
      tags:
        - Products
      responses:
        '200':
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
      $ref:
        type: string
      capacity:
        type: string
```

```$ref:```as a declared property works when set with ```{ type: string }```.

I also looked at the openAPI schema file find a similar declaration there:

- in [https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json)

```json
"pathItem": {
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^x-": {
      "$ref": "#/definitions/vendorExtension"
    }
  },
  "properties": {
    "$ref": {
      "type": "string"
    },
```
I havne't parsed through openapi and json specs covering these but atleast but i suspect this is working as intended.  Thoughts?

**Comment by salrashid123** [comment]
Also citing the following to  for draft 4->6:

- [http://json-schema.org/draft-06/json-schema-migration-faq.html](http://json-schema.org/draft-06/json-schema-migration-faq.html)

**Comment by mbohlool** [comment]
@salrashid123 thanks for the reference. it clearly said:

> $ref: it is now possible to describe instance properties named "$ref"

I assume we can close this issue with "work as intended" resolution, right?

**Comment by salrashid123** [comment]
FWIW,

```
wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json

wget https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json
```

then using python, the validation passes

```python
import json
import jsonschema
from jsonschema import validate

schema = json.load(open('schema.json'))
swagger = json.load(open('swagger.json'))
validate(swagger, schema)
```

i think that confirms it.  I'll close this issue out later this week unless i'm interpreting all this incorrectly.

**Comment by Capstan** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types seems to indicate explicitly that it uses 04 and _not_ 06.
