### ISSUE TITLE
Secret key validation is inconsistent with the documentation.

### ISSUE THREAD

**Issue by af-inet** [kubernetes/kubernetes#59516]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

I can upload a secret with keys that do not match `DNS_SUBDOMAIN`.

The documentation for secrets states:
```
The data field is a map. Its keys must match DNS_SUBDOMAIN, except that leading dots are also allowed. The values are arbitrary data, encoded using base64.
```
source: https://kubernetes.io/docs/concepts/configuration/secret/

**What you expected to happen**:

Either:
- the documentation should not state DNS_SUBDOMAIN is a requirement
OR
- the kubernetes API rejects invalid secret keys

**How to reproduce it (as minimally and precisely as possible)**:

apply this secret:

```
apiVersion: v1
data:
  # FOO_BAR=BAR
  FOO_BAR: QkFS
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
```

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration:** AWS
- **OS (e.g. from /etc/os-release):** 
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Kernel (e.g. `uname -a`):**
`Linux ip-10-108-95-220 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux`

- **Install tools:**
kops

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/kubernetes/blob/07e849c98698b19de636d6f7282dbc0b2edebde7/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L53](https://github.com/kubernetes/kubernetes/blob/07e849c98698b19de636d6f7282dbc0b2edebde7/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L53)
Now it only requires the prefix part (separated by slash) of key matches DNS_SUBDOMAIN. If no prefix is present, the key of secret/configmap should be a "qualified" name.[https://github.com/kubernetes/kubernetes/blob/07e849c98698b19de636d6f7282dbc0b2edebde7/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L35](https://github.com/kubernetes/kubernetes/blob/07e849c98698b19de636d6f7282dbc0b2edebde7/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L35)

**Comment by af-inet** [comment]
fix for this has been merged, closing 
https://github.com/kubernetes/website/pull/7675
