### ISSUE TITLE
verify-bazel.sh in pull-kubernetes-verify failing

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#59518]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

When running `hack/verify-bazel.sh` on my commits locally I got the following error:

```
!!! Error in hack/verify-bazel.sh:40
  Error in hack/verify-bazel.sh:40. 'cp -a "${KUBE_ROOT}" "${_tmp_kuberoot}/.."' exited with status 1
Call stack:
  1: hack/verify-bazel.sh:40 main(...)
Exiting with status 1
```

Affected PRs:
https://github.com/kubernetes/kubernetes/pull/59447
https://github.com/kubernetes/kubernetes/pull/59511

**Comment by cblecker** [comment]
@verult There's likely something up with your local environment. These jobs are running correctly in CI, although you need to look at the build log for output
