### ISSUE TITLE
Volume metrics e2e tests are failing

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#59517]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
/assign @gnufied 

**What happened**:
https://k8s-testgrid.appspot.com/sig-storage#gke-serial

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:239
Error getting c-m metricValues: Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering.
Expected error:
    <*errors.errorString | 0xc421b9e990>: {
        s: "Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering.",
    }
    Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering.
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:245
```

**Comment by msau42** [comment]
Oh it's only happening in GKE.  Hm I wonder if something changed regarding access to the master.  What is this test trying to do?

**Comment by gnufied** [comment]
Yeah, this was newly introduced.  These metrics report number of bound/unbound volumes etc - https://github.com/kubernetes/kubernetes/pull/57872

The fix seems pretty simple. We used to skip this test in environments where controller-manager is not registered. This test is going wrong way spotting that.

**Comment by gnufied** [comment]
cc @mlmhl

**Comment by gnufied** [comment]
Okay, so I made a fix - https://github.com/gnufied/kubernetes/tree/fix-storage-metric-failures and tried running it in a tight loop against a GCE cluster and it failed because of different reasons (but in same newly introduced metrics).

I propose, we revert https://github.com/kubernetes/kubernetes/pull/57872 until, it has been fixed for good.

**Comment by mlmhl** [comment]
Sorry for this, I add a `GrabFromControllerManager` operation in `BeforeEach` by forget to check `HasRegisteredMaster`.

@gnufied  Could you post the failures in GCE cluster? I only run these tests in my local environment before.

**Comment by gnufied** [comment]
The other failures were:

```
sig-storage] [Serial] Volume metrics
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22
  PVController
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:171
    should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:290

    Wrong pv controller metric pv_collector_unbound_pv_count(storage_class): wanted map[], got map[:0]
    Expected
        <map[string]int64 | len:1>: {"": 0}
    to equal
        <map[string]int64 | len:0>: {}

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:233
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
```

**Comment by mlmhl** [comment]
It seems that there are other PVs in the cluster when we running this test, the `calculateRelativeValues`(in this [code](https://github.com/kubernetes/kubernetes/blob/b922ffc491ed7016f6e8381a45633e8d0fe023ae/test/e2e/storage/volume_metrics.go#L449)) should be modified like this, we should only consider changed values:

```go
func calculateRelativeValues(originValues, updatedValues map[string]int64) map[string]int64 {
	relativeValues := make(map[string]int64)
	for key, value := range updatedValues {
		relativeValue := value - originValues[key]
		relativeValues[key] = relativeValue
	}
	for key, value := range originValues {
		if _, exist := updatedValues[key]; !exist && value > 0 {
			relativeValues[key] = -value
		}
	}
	return relativeValues
}
```

I will test this code in my local environment first.

**Comment by mlmhl** [comment]
@gnufied 
I've test in my local environment and reproduced this failure. As mentioned in the above comment, if there are other PV/PVCs exist in the cluster, this failure happens.

I post a PR #59646 to fix these two bugs, could you help to test it in GCE?
