### ISSUE TITLE
Incorrect start times can cause heapster to not have CPU stats

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#59524]
/kind bug
/sig node
/priority important-soon

When HPA is supposed to upscale it is intermittently unable to calculate the number of desired replicas because of missing metrics
`$ kubectl describe hpa <hpa-name>`
`  3d            29s             80      horizontal-pod-autoscaler                       Warning         FailedGetResourceMetric         unable to get metrics for resource cpu: no metrics returned from heapster`
`  3d            29s             80      horizontal-pod-autoscaler                       Warning         FailedComputeMetricsReplicas    failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster`

The kubelet was returning an invalid Start time for pods, containers, and the node:
`"podRef": {`
` "uid": "7efbdb50-0830-11e8-9e01-42010af0001e"`
`},`
`"startTime": "2018-02-07T09:53:05Z",`
`"containers": [`
`{`
` "startTime": "2018-02-07T09:53:05Z",`
` "cpu": {`
`  "time": "2018-02-07T09:53:03Z",`
` },`
` "memory": {`
`  "time": "2018-02-07T09:53:03Z",`
` },`
` "rootfs": {`
 `"time": "2018-02-07T09:53:03Z",`
 `},`
 `"logs": {`
 ` "time": "2018-02-07T09:53:03Z",`
 `},`
`},`

Here is the Heapster code that computes cpu usage rate (this is the metric for HPA): https://github.com/kubernetes/heapster/blob/release-1.4/metrics/processors/rate_calculator.go, which requires that the current and previous batch have the same start time.  A start time which changes often results in very few cpu metrics for heapster.

When cadvisor calculates the start time, it looks at the last time `cgroup.clone_children` was modified. https://github.com/google/cadvisor/blob/master/container/common/helpers.go#L56
This is an estimate, at best.  We recently changed cAdvisor to use docker's container creation time: https://github.com/google/cadvisor/pull/1806.
But we still need to get a real Pod, Node and system container Start time.

**Comment by dashpole** [comment]
See https://github.com/google/cadvisor/blob/master/container/common/helpers.go#L56.  We can't use the directory because it is modified each time a sub-cgroup is created.

**Comment by filbranden** [comment]
My suggestion was not about using the directory per-se... But using another piece of information rather than the timestamp to check when a cgroup was destroyed and re-created...

Such as the inode number.

In that case (and assuming it's preserved and not reused right away on re-creation), you could take it from the directory, or still get it from `cgroup.clone_children`, either should probably work...

What do you think?
