### ISSUE TITLE
Measure and optimize push-based heartbeats from Kubelet to NodeController

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#5953]
Kubelet POST nodeStatus every 2sec as heatbeat message now. NodeController will make decision or fix up the node phase based on those status message. But there is no need to write NodeStatus to etcd server every 2 sec. 

cc/ @ddysher @bgrant0607 @davidopp

**Comment by ddysher** [comment]
As discussed before, we can hold the status in memory and flush to etcd with a longer period; or we can have a rate limiter on etcd, and bypass excessive writes.

There are some other items left we need to fix after implementing the push mode, like the status subresource.  As @davidopp proposed, @gmarek will take more responsibilty for nodecontroller as a full time.  I'll discuss with him about his thoughts.

**Comment by lavalamp** [comment]
Kubelet POSTs to apiserver, correct? Apiserver can't "just" cache this in memory, because then it will not be replicable!

That 2s interval means we'll be giving etcd a steady stream of 50 qps for a 100 node cluster. That seems a little excessive but we should test and see if it's a problem before we do something hard to fix it.

**Comment by ddysher** [comment]
If master is replicated, I assume we will have a leader, not a peer system right?  If so, then it seems caching in memory will only be a problem during master election, which I think other components should be robust enough to make the the system work. e.g. node controller do not evit pods because master is not responding.

**Comment by gmarek** [comment]
@wojtek-t @fgrzadkowski as they are looking at performance now.

**Comment by wojtek-t** [comment]
Does it make sense to update NodeStatus every 2 seconds? IIUC, NodeStatus is mostly used to restart pods on a different node if that node is somehow dead (and to avoid future scheduling on it). If so, since we're updating pod status every 10 seconds, I think it doesn't make sense to update NodeStatus so often (or if we want to update NodeStatus so often, we should increate how often pod status is updated).

**Comment by zmerlynn** [comment]
A measly 50qps to update node status on a 100 node cluster really doesn't
sound hard, but 2s refresh for mostly static state is probably unnecessary
as well. Do we infer node liveness from pod status updates as well? It
seems reasonable to (and possibly piggyback NodeStatus on those messages,
since it's probably cheap to collect).

**Comment by gmarek** [comment]
I don't think that Pod Statuses impact Node liveness in any way.

To make sure I correctly understand what you wrote: you suggest to use PodStatus updates as a signal that Node is responsive, as both Node and Pod Statuses are updated by Kubelet. Right?

I don't think it's possible (read: it's too complicated) after @fgrzadkowski change, which makes PodStatus updated to be sent only when it changes. My feeling is that it wont be happening often enough to substitute regular health checks + we'd need a special case for empty Nodes.

**Comment by ddysher** [comment]
NodeStatus needs not to be updated every 2 sec, but heatbeat message should.  Currently node controller has no interaction with node, everything is observed from apiserver, is that intentional?  Instead, Node controller can open a long-lived connection with each node, with 2sec heatbeat from kubelet.  We can have a different NodeStatus update period from kubelet to apiserver.  Node controller needs to be smart enough to merge the two information.

Lowering NodeStatus update period is simple, but this is not just a performance issue.  NodeStatus will be observed by user, and pod eviction also depends on NodeStatus.

**Comment by fgrzadkowski** [comment]
@ddysher I thought the whole point of moving this logic to kubelet was to keep connection from kubelet to master (not the other way around). AFAIU this is needed for setups like GKE where we need nodes to be as self-contained as possible.

Regarding update frequency I think we should wait until we have some data regarding performance, but I don't think it make sense to update it every 2 sec, while we sync pods every 10 sec.

**Comment by davidopp** [comment]
Let's change it to 10 seconds. But let's wait for the NodeController changes to go in first and make sure that's working OK; in case we find bugs it is better to have less changing at the same time.

We can have NodeReachable updated more often, but we need to figure out how it will work. Let's wait to work on that.

**Comment by dchen1107** [comment]
@ghodss mentioned from #5864

Just as a heads up, I started up a completely idle 0.14.2 500 node cluster with an n1-standard-8 instance as the master and the master is completely 100% loaded to the point that 50% of requests return 429 due to node status GET's and PUT's. I know the target 1.0 size is 100 nodes but it would be great to optimize this at least a bit.

**Comment by fabioy** [comment]
It may be good to have a quick audit of all the requests being made to the master api server and to optimize them a bit. I took a snippet of the logs on the api server for a period of ~3 sec (edited to only include times and URLs, see below). Logs indicate about 50 reqs, or roughly 16 qps. A couple of observations:

- Nodes seem to do a GET followed immediately by a PUT. Could we merge these into a single call?
- A bunch of "/api/v1beta3/namespaces/...." calls that also happen at the periodic 2 sec.
- A bunch of calls to something with a path "/api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal" which returns a 404. This seems weird and worthy of investigation.

I think there may be a number of small things that can be done to help minimize the flood of requests to the master. As it is, the api server logs seem to grow at about 3k a sec...

16:45:42.09	GET /api/v1beta3/nodes/kubernetes-minion-cpmo.c.fabioy-cloud-test-1.internal:
16:45:42.11	PUT /api/v1beta3/nodes/kubernetes-minion-cpmo.c.fabioy-cloud-test-1.internal:
16:45:42.16	GET /api/v1beta3/nodes/kubernetes-minion-7oar.c.fabioy-cloud-test-1.internal:
16:45:42.17	PUT /api/v1beta3/nodes/kubernetes-minion-7oar.c.fabioy-cloud-test-1.internal:
16:45:42.53	GET /api/v1beta3/nodes/kubernetes-minion-x1jl.c.fabioy-cloud-test-1.internal:
16:45:42.54	PUT /api/v1beta3/nodes/kubernetes-minion-x1jl.c.fabioy-cloud-test-1.internal:
16:45:42.79	POST /api/v1beta1/replicationControllers?namespace=default: (38.084763ms) 409
16:45:42.83	GET /api/v1beta3/namespaces/default/pods/nginx-kubernetes-master: (4.792072ms)
16:45:42.83	POST /api/v1beta3/namespaces/default/events: (74.446989ms) 201 [[kubelet/v0.10
16:45:42.84	PUT /api/v1beta3/namespaces/default/pods/nginx-kubernetes-master/status: (16.1
16:45:42.86	POST /api/v1beta3/namespaces/default/events: (26.855479ms) 201 [[kubelet/v0.10
16:45:43.05	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (631.
16:45:43.05	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (410.
16:45:43.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (484.
16:45:43.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (418.
16:45:43.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (694.
16:45:43.09	GET /api/v1beta3/nodes/kubernetes-minion-sleo.c.fabioy-cloud-test-1.internal:
16:45:43.11	PUT /api/v1beta3/nodes/kubernetes-minion-sleo.c.fabioy-cloud-test-1.internal:
16:45:43.12	POST /api/v1beta1/replicationControllers?namespace=default: (24.705056ms) 409
16:45:43.46	GET /api/v1beta3/nodes: (3.116004ms) 200 [[kube-controller-manager/v0.10.0 (li
16:45:44.12	GET /api/v1beta3/nodes/kubernetes-minion-cpmo.c.fabioy-cloud-test-1.internal:
16:45:44.13	PUT /api/v1beta3/nodes/kubernetes-minion-cpmo.c.fabioy-cloud-test-1.internal:
16:45:44.18	GET /api/v1beta3/nodes/kubernetes-minion-7oar.c.fabioy-cloud-test-1.internal:
16:45:44.19	PUT /api/v1beta3/nodes/kubernetes-minion-7oar.c.fabioy-cloud-test-1.internal:
16:45:44.26	GET /api/v1beta3/services: (3.908725ms) 200 [[kube-controller-manager/v0.10.0
16:45:44.26	GET /api/v1beta3/namespaces/default/pods?labelSelector=name%3Delasticsearch-lo
16:45:44.27	GET /api/v1beta3/namespaces/default/endpoints/elasticsearch-logging: (647.329µ
16:45:44.27	GET /api/v1beta3/namespaces/default/pods?labelSelector=name%3Dkibana-logging:
16:45:44.27	GET /api/v1beta3/namespaces/default/endpoints/kibana-logging: (698.224µs) 200
16:45:44.28	GET /api/v1beta3/namespaces/default/pods?labelSelector=k8s-app%3Dkube-dns: (5.
16:45:44.28	GET /api/v1beta3/namespaces/default/endpoints/kube-dns: (677.093µs) 200 [[kube
16:45:44.29	PUT /api/v1beta3/namespaces/default/endpoints/kube-dns: (9.490548ms) 200 [[kub
16:45:44.30	GET /api/v1beta3/namespaces/default/pods?labelSelector=name%3DinfluxGrafana: (
16:45:44.31	GET /api/v1beta3/namespaces/default/endpoints/monitoring-grafana: (1.435451ms)
16:45:44.46	GET /api/v1beta3/namespaces/default/pods?labelSelector=name%3Dheapster: (12.17
16:45:44.54	GET /api/v1beta3/nodes/kubernetes-minion-x1jl.c.fabioy-cloud-test-1.internal:
16:45:44.56	PUT /api/v1beta3/nodes/kubernetes-minion-x1jl.c.fabioy-cloud-test-1.internal:
16:45:44.65	GET /api/v1beta3/namespaces/default/endpoints/monitoring-heapster: (1.03801ms)
16:45:44.84	GET /api/v1beta3/namespaces/default/pods/kube-dns-dulkc: (1.679144ms) 200 [[ku
16:45:44.86	GET /api/v1beta3/namespaces/default/pods?labelSelector=name%3DinfluxGrafana: (
16:45:44.86	PUT /api/v1beta3/namespaces/default/pods/kube-dns-dulkc/status: (15.393172ms)
16:45:45.05	GET /api/v1beta3/namespaces/default/endpoints/monitoring-influxdb: (1.119112ms
16:45:45.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (652.
16:45:45.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (492.
16:45:45.06	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (575.
16:45:45.07	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (767.
16:45:45.07	GET /api/v1beta3/nodes/kubernetes-master.c.fabioy-cloud-test-1.internal: (636.
16:45:45.11	GET /api/v1beta3/nodes/kubernetes-minion-sleo.c.fabioy-cloud-test-1.internal:
16:45:45.12	PUT /api/v1beta3/nodes/kubernetes-minion-sleo.c.fabioy-cloud-test-1.internal:

**Comment by ghodss** [comment]
Also from #5864, @quinton-hoole had an idea for how to reduce node status PUT's:

> As an aside, TCP keepalives are a very cheap way to do these sorts of remote heartbeats (all in-kernel). Then you can potentially do low latency edge-triggered rather than level triggered event reporting.

I don't know if you can assume that if a TCP connection is simply held open that a node is functioning properly, but you could have a blended approach where a kubelet is expected to create a connection to the master and hold it open for 60 seconds at a time, assuming no changes on the minion. If the connection dies and/or 60s+ seconds pass without a new connection, the kubelet's status can then be considered unknown.

**Comment by quinton-hoole** [comment]
Yes, you need to do some polling as a fallback, to cover the case of the process on the other end being running and network-reachable, but not healthy enough to reply to a health check, or do real work.  But you don't need to create a new TCP connection every 60s, rather just send a application-level heartbeat message to prove that the process is alive and well.  I don't think that this even needs to happen as often as 60s in practise.  Probably more like every few minutes, purely as an enti-entropy mechanism.

**Comment by davidopp** [comment]
I'm going to send out a PR in about 10 minutes to change the push rate to 10 seconds. IMO we're spending way too much time debating how to solve this issue cleverly.

**Comment by dchen1107** [comment]
+1 on @davidopp I am about to ping you on interval changes :-) We can iterate this later.

**Comment by davidopp** [comment]
@lavalamp suggested we should monitor CPU utilization during e2e tests. Once the master components are in pods we can get this from cAdvisor.

**Comment by fgrzadkowski** [comment]
@davidopp @lavalamp I don't think that measuring CPU utilization is the right thing to do. It will be extremely hard to tune the test and in the end we don't care about the utilization, but the latency of operations, which we should measure.

**Comment by wojtek-t** [comment]
@fgrzadkowski I agree that our goal should be defined in terms of "latency of operation" not in "CPU utilization". However, this doesn't mean that we shouldn't look at utilization at all.

What I would like to say is that having e.g. 90th-ile of operation latency at of say 1s with 10% utilization is different that 90th-ile operation latency of 1s with 90% utilization. Although from the user perspective it's more-or-less the same, the second case may suggest that we're close to our capacity [and we might need to optimize something]

**Comment by lavalamp** [comment]
Our SLAs should be on latency, but we absolutely need to know utilization so that we can correctly size master VMs.

**Comment by lavalamp** [comment]
Plus I expect a subtle performance bug to have a more noticeable effect on utilization than on a latency metric, although this is a bit speculative.

**Comment by timothysc** [comment]
@lavalamp memory utilization is of > importance imho, b/c CPU utilization appears skewed around garbage collection.

**Comment by ghodss** [comment]
For the record, even with #6535 setting refresh rate to 10 seconds, a 100 node cluster with a 16-core master still struggles to keep up with the load in an idle cluster. Mostly coming from port exhaustion of so many connections to a single etcd node (see #6559).

**Comment by timothysc** [comment]
@ghodss are you running against master?

**Comment by fgrzadkowski** [comment]
@lavalamp I'm not saying we should not measure it! I completely agree we need metrics for this. I'm just saying that IMO tests that explicitly check CPU utilization will be very flaky or will not check anything useful. But I might be wrong :)

**Comment by wojtek-t** [comment]
Kubelet was posting NodeStatus as often as possible (it was usually 5-10 times per second) - the flag change by @davidopp wasn't effective.
I'm fixing the issue with it in #6620.

**Comment by timothysc** [comment]
@wojtek-t awesome! can we close this one out then?

**Comment by davidopp** [comment]
I think we should leave this issue open since it discusses several other things
* adding more instrumentation
* optimizing the number of puts/gets
* having persistent puts vs. ephemeral puts

I'm open to re-titling it to something like "measure and optimize push-based heartbeats" or something like that.

**Comment by lavalamp** [comment]
@fgrzadkowski yeah I'm not saying to gate the test on it, I just want it recorded so we have a chart over time of how much CPU we consume during the test.

**Comment by quinton-hoole** [comment]
+1 to davidopp@ 's proposed retitling.

**Comment by davidopp** [comment]
OK I'm going to re-title now.

**Comment by yujuhong** [comment]
I will take a look at this.

**Comment by davidopp** [comment]
Removed from 1.0 because we don't think this is a bottleneck right now.

**Comment by gmarek** [comment]
@yujuhong, @dchen1107 - do we have any measurements?

**Comment by yujuhong** [comment]
No, this hasn't been prioritized since before v1.0. I will unassign myself since I won't be able to get to it anytime soon, so people working on scalability can pick it up if necessary.

**Comment by davidopp** [comment]
@kubernetes/rh-scalability @kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
Most of this has been addressed as part of ongoing scale tests.  Closing because we have a more comprehensive process in place.
