### ISSUE TITLE
kubectl expose does not work with kind and selector

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#59551]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Trying to expose a pod using a selector

**What you expected to happen**:
To be able to create a service with a kind and selector only

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl expose pod --selector='app=MYAPP' --name myappsvc --port=4242`

**Anything else we need to know?**:
It fails with:
```
$ k expose pod --selector='app=iscsi-demo-target' --name kk --port=55
error: resource(s) were provided, but no name, label selector, or --all flag specified
See 'kubectl expose -h' for help and examples.
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: minikube
- Others:

**Comment by fabiand** [comment]
Hm, let's give it a try

/sig api-machinery

**Comment by fabiand** [comment]
Yey.

**Comment by Lion-Wei** [comment]
I can help fix this problem
/self-assign

**Comment by fabiand** [comment]
Cool - How can I help to drive this forward?

**Comment by Lion-Wei** [comment]
@fabiand Sorry for the delay.
AFAIK, the `--selector` is the flag for the service this command created, but not the selector for pod to create service.
And I didn't find any example or usage for `kubectl expose` command to create a service of a selector selected pod, besides, `--all` flag is also not acceptable for this command. 
Cause people usually don't expose different pods to a single service...

This is how I understand, please let me know if I was wrong, thanks.

**Comment by Lion-Wei** [comment]
@fabiand Sorry for the delay.
AFAIK, the `--selector` is the flag for the service this command created, but not the selector for pod to create service.
And I didn't find any example or usage for `kubectl expose` command to create a service of a selector selected pod, besides, `--all` flag is also not acceptable for this command. 
Cause people usually don't expose different pods to a single service...

This is how I understand, please let me know if I was wrong, thanks.

**Comment by fabiand** [comment]
How I imagine this flag to work - and I actually thought it worked this way:

```
kubectl expose pod --selector='mylabel=myvalue' --name=mysvc --port=42
```

Here I'd expect that a service `mysvc` is created, exposing port `42` of all pods matching the labelSelector `mylabel=myvalue`.

**Comment by Lion-Wei** [comment]
Did some test, sames like `selector` usage is:
```shell
# k expose rc whoami --selector='app=whoami' --name lw --port=3000 --v=6
I0223 16:44:33.978679   74401 loader.go:357] Config loaded from file /var/run/kubernetes/admin.kubeconfig
I0223 16:44:34.001433   74401 round_trippers.go:436] GET https://localhost:6443/api/v1/namespaces/default/replicationcontrollers/whoami 200 OK in 10 milliseconds
I0223 16:44:34.047665   74401 round_trippers.go:436] POST https://localhost:6443/api/v1/namespaces/default/services 201 Created in 4 milliseconds
service "lw" exposed
```
And the service created is : 
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-02-23T08:44:34Z
  labels:
    app: whoami
    env: dev
  name: lw
  namespace: default
  resourceVersion: "360"
  selfLink: /api/v1/namespaces/default/services/lw
  uid: c59d2a20-1875-11e8-a7b4-286ed488d06a
spec:
  clusterIP: 10.0.0.190
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: whoami
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
The field `selector` is what we specified.

But I'm not sure how this command supposed to work...

**Comment by fabiand** [comment]
@Lion-Wei hey - thanks for your investiagtions!

I really wonder why you do have to specify the name of the RC, even if you specify a selector.

**Comment by fabiand** [comment]
@Lion-Wei hey - getting back to this.

So, in my understanding it should be like this: The *name* OR the *selector* must be specified. But specifying both of them makes not much sense to me.

After all I do not see why the name must be provided if we explicitly state the selector.

ideas?

**Comment by nikhita** [comment]
/remove-lifecycle rotten

I guess this is still relevant.

**Comment by IvanBoyko** [comment]
It's sad it was closed without resolution

**Comment by fabiand** [comment]
Yes ...

I think it's also an issue with the semantics. But what I am looking for is
a way to specify the selector be used to match the service to pods.

**Comment by gauravsjc02** [comment]
Mention the selector as well, for ex:-
    sudo kubectl expose rs myweb-rs --selector="key=value" --port=80 --type=NodePort

here, rs is the replica set having the name myweb-rs.
key and value must match with selector that we have mentioned in replica set file.

**Comment by zevisert** [comment]
For anyone else who finds this, you can work around this issue with kubectl expose by using the selector to get a name, provide your selector already matches something (eg, can't do this in advance). 

#### 0. Create some pods that we want to select. We can't use their name in the next commands
```console
> kubectl run some-pod-$RANDOM --image hello-world --labels=app=some-label-we-know --port 10001
pod/some-pod-31702 created
> kubectl run some-pod-$RANDOM --image hello-world --labels=app=some-label-we-know --port 10001
pod/some-pod-7514 created
```

#### 1. Use kubectl get all to name the resource.
If you know the resource type, you can use `kubectl get pods ...` instead with `kubectl expose pod` later.

```console
> kubectl get all --selector=app=some-label-we-know --output=name
pod/some-pod-31702
pod/some-pod-7514
```

#### 2. Select any ONE matching resource to base the selector from
If you pass multiple names to `kubectl expose` it will create multiple services. As long as the selector matches something, we should be okay.
```console
> kubectl get all --selector=app=some-label-we-know --output=name | head -n1
pod/some-pod-31702
```

#### 3. Use the discovered name to create a service from
```console
> kubectl expose $(kubectl get all --selector=app=some-label-we-know --output=name | head -n1) --name=example-expose-selector --selector=app=some-label-we-know --labels=app=some-label-we-know --dry-run=client --output=yaml 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: some-label-we-know
  name: example-expose-selector
spec:
  ports:
  - port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: some-label-we-know
status:
  loadBalancer: {}
```
