### ISSUE TITLE
KUBE_REPO_PREFIX unwork

### ISSUE THREAD

**Issue by maojiawei** [kubernetes/kubernetes#59553]
kubeadm version v1.8.2
I use `KUBE_REPO_PREFIX` but it's unwork.The config kubeadm create still use image from gcr.io .
![image](https://user-images.githubusercontent.com/5907733/35965990-86964c08-0cf7-11e8-8c49-afb4ff2fd9e2.png)

**Comment by maojiawei** [comment]
I found it.In kubeadm 1.8,we can use `kubeadm init--config=config file path`.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

**Comment by dixudx** [comment]
Kubernetes does not have such environment variable `KUBE_REPO_PREFIX`, which has already been removed since 1.8. Please refer to #48053 and #49018.

> we can use `kubeadm init--config=config`

Correct.

/close
