### ISSUE TITLE
Problems with kubemark image lifecycle

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#59567]
After looking at @thockin 's [PR](https://github.com/kubernetes/kubernetes/pull/57824), I realized that there are some problems with how we're using kubemark images for our CI-testing:

1. Every run of every kubemark job creates and pushes a kubemark image to the image registry of the project in which the cluster would be created. But the kubemark cluster setup uses the `<registry>/kubemark:latest` image. This means that a race b/w 2 kubemark jobs while pushing the image is possible, and it may happen that one job is using the image from another one. This can be solved by using a random image tag to uniquify the runs.

2. Every run of every kubemark job pushes a new image to a docker registry. So we have a huge list of leaked kubemark images in the projects where we're running kubemark jobs - e.g O(10^5) images in [one of our projects](https://pantheon.corp.google.com/gcr/images/k8s-jkns-pr-kubemark/GLOBAL/kubemark?gcrImageListsize=50) used for kubemark pre-submit. Each image is about 72 MB and at the cost of [0.026 $/GB](https://cloud.google.com/container-registry/pricing) for our GCS buckets, it's ~$180/month for that project. Another such project is of our kubemark-small job (running once every 20m) which has ~30k stale images. Overall, we're likely spending an estimated O(1000) $/month just on stale kubemark images. Few things we should do IMO:
  - delete the kubemark image at the end of the run
  - delete the pre-existing stale kubemark images
  - in general, make janitor garbage collect images also (cc @krzyzacy @BenTheElder )

3. PR https://github.com/kubernetes/kubernetes/pull/57824 changed the kubemark image registry to `staging-k8s.gcr.io`, instead of the earlier `gcr.io`. However, the manifest for the kubemark deployment [hasn't been updated](https://github.com/kubernetes/kubernetes/blob/3586986416b174d390376311c909d665416bf5c0/test/kubemark/resources/hollow-node_template.yaml#L38) - so all jobs will continue using old kubemark image (albeit the `:latest` one). This needs to be fixed asap.

cc @wojtek-t @porridge @kubernetes/sig-scalability-bugs 
/assign

**Comment by shyamjvs** [comment]
PR #59577 solves the 1st and 3rd issues above.

Wrt 2, the following seem to be the current set of projects running our kubemark jobs (there may be more abandoned ones from the past):

```
k8s-jkns-pr-kubemark - 68811 images
k8s-jenkins-kubemark - 29045 images
k8s-jenkins-blocking-kubemark - 9764 images
k8s-jenkins-gci-kubemark - 3633 images
k8s-scale-testing - 228 images
kubemark-scalability-testing - 105 images
```

We need to clean up all those images. Any ideas on what's the easiest way of doing it? I'm thinking of directly deleting the GCS directories holding those images (if that's possible). cc @krzyzacy @BenTheElder 

And for future, I'll send out a PR soon to do automatic GC as part of the run.

**Comment by krzyzacy** [comment]
@shyamjvs I still suggest we push the image as part of the build process :-)
for gc, isn't it we won't need anything except for the `:latest` one? Select all and delete?

**Comment by shyamjvs** [comment]
> @shyamjvs I still suggest we push the image as part of the build process :-)

I'm not sure I understand. Push where? Do you mean pack it in the release tar (like kube-proxy, etc)?

> for gc, isn't it we won't need anything except for the :latest one? Select all and delete?

Yeah, for now we can delete all the images (even the latest one, it'll probably just cause a few one-off failures of the current runs). In general we don't want to gc everything except the latest one as we're going to have multiple unique images in use at a given instant (see my point 1).

**Comment by shyamjvs** [comment]
I'm not sure - is it? The last I remember, I think we used to pack those docker images (and their tags) into the release tar which was downloaded onto every VM and docker used to locally load those dev image builds (instead of pushing them to somewhere in a gcr.io registry).

**Comment by BenTheElder** [comment]
we could run a script with `gcloud container images delete ...` in a cronjob if we had a reliable way to identify which images we want to get rid of.

**Comment by ixdy** [comment]
We still pack the docker images + tags into the release tarballs, since GCE/GKE/kops all still do sideloading, but we also push the images from the `ci-kubernetes-cross-build` to gcr.io/kubernetes-ci-images for the kubeadm CI jobs.

See https://github.com/kubernetes/test-infra/issues/1400 for more discussion on this.

**Comment by ixdy** [comment]
@BenTheElder maybe combine `gcloud help container images list-tags <image>` with an appropriate `--filter`?

**Comment by BenTheElder** [comment]
@ixdy probably? one issue is that images can be pushed with many tags

**Comment by ixdy** [comment]
you can use `gcloud container images list` to get the list of images, and then `list-tags` will list all tags matching your filter query.

**Comment by BenTheElder** [comment]
yeah, we'll need something like:
- list images we want to keep and their tags
- list all images and their tags
- delete set(all tags) - set(tags to keep)

**Comment by dekkagaijin** [comment]
Image retention policy is a feature we (GCR) are investigating.

@BenTheElder other what tags are you using to push? I see `KUBEMARK_IMAGE_TAG=$(head /dev/urandom | tr -dc 'a-z0-9' | fold -w 6 | head -n 1)` in combination with a `bazel run ... :push`, which is going to complicate matters by stripping the build timestamp from the image (thereby enabling reproducible builds). Would the unix timestamp be an acceptable alternative to a completely random tag?

If you're continually uploading new images under the exact same tag(s), most of the images will be untagged, and you can list the digests of such images like to:

```bash
gcloud container images list-tags gcr.io/${PROJECT_ID}/${REPO_NAME} --filter='-tags:*'  --format='get(digest)' --limit=unlimited
```
and delete like so:

```bash
gcloud container images delete --quiet gcr.io/${PROJECT_ID}/${REPO_NAME}@${DIGEST}
```

**Comment by BenTheElder** [comment]
I'm not sure what uploads are done for this job yet, or what tags would be acceptable but in other places, but in other places we have code that builds images which are doubly tagged (`:date-sha` and `:latest`), I think this pattern is fairly common.

We have some similar logic for getting rid of stale images on disk (for local caching). 
I definitely think we could hack something together, I just want to make sure we'll be able to avoid deleting things we should actually keep...

It sounds like for this one we can probably just delete images that aren't latest, but there are lots of other images we should probably do this for.

**Comment by dekkagaijin** [comment]
Ah. 

`--filter`'s a bit... interesting, but it shouldn't be too difficult to do the set difference above: https://cloud.google.com/sdk/gcloud/reference/topic/filters

**Comment by ixdy** [comment]
re: bazel-built docker images, I'm hoping we can fix https://github.com/bazelbuild/rules_docker/issues/155 at some point (so we can stamp them with real timestamps).

**Comment by dekkagaijin** [comment]
FYI https://github.com/bazelbuild/rules_docker/pull/364 has been merged, stamping should give you a good mechanism to reap images.

**Comment by shyamjvs** [comment]
I've sent out https://github.com/kubernetes/kubernetes/pull/68143 as a simple strategy to delete image right after startup.
