### ISSUE TITLE
Can't run Kubelet as a service on Windows

### ISSUE THREAD

**Issue by stuartio** [kubernetes/kubernetes#59562]
/kind bug
(this could be considered a feature if this was never intended to work)

**What happened**:

If creating a Windows service through Powershell New-Service command or cmd sc.exe the resulting service cannot start.

**What you expected to happen**:

The service to start

**How to reproduce it (as minimally and precisely as possible)**:

Setup Kubelet.exe on Windows with necessary prereqs. Run in a shell to confirm working. Then take the entire shell command and pass it as the BinaryPathName to New-Service in Powershell. Attempt to start the service through the Services snap-in or with Start-Service.

**Anything else we need to know?**:

I am assuming the signal handler for Kubelet is set up for Linux signals only, and not Windows.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0-alpha.3.299+c17b418f89e056 (manual build)
- Cloud provider or hardware configuration: Local VSphere
- OS (e.g. from /etc/os-release): Windows Server 1709
- Kernel (e.g. `uname -a`):
- Install tools: Manual
- Others:

**Comment by andyzhangx** [comment]
you may take [acs-engine](https://github.com/Azure/acs-engine) which runs kubelet on Azure as an example, the kubelet config would be like following:
https://github.com/andyzhangx/Demo/blob/master/acs-engine/deployment/windows/kubeletstart.ps1
