### ISSUE TITLE
run Nvidia GPU Device Plugin tests on Container Optimized OS only

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59584]
This flaked 5/14 times in the last week.

/priority failing-test
/priority important-soon
/sig scheduling
/kind flake

**Comment by mithrav** [comment]
[Feature:GPUDevicePlugin]

**Comment by mithrav** [comment]
@kubernetes/sig-scheduling-test-failures

**Comment by bsalamat** [comment]
We have so many tests in our dashboard. Please provide a link to the tests. The name of the test sounds like sig node to me.
@jiayingz @yguo0905

**Comment by mithrav** [comment]
Closing this as I no longer see the issue.
