### ISSUE TITLE
kubernetes/test/integration/garbagecollector/garbage_collector_test.go is flaky

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59585]
This flaked 11/66 times in the last week.

/priority failing-test
/priority important-soon
/sig api-machinery
/kind flake

Please correct sig if assigned inaccurately.

**Comment by mithrav** [comment]
@kubernetes/sig-api-machinery-test-failures

**Comment by yue9944882** [comment]
note that it is `TestCascadingDeletion` is failing

**Comment by mithrav** [comment]
Pinging for status

**Comment by cblecker** [comment]
Closing as dupe of #59426
