### ISSUE TITLE
Kubectl apply apply set/view last-applied

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59581]
This flaked 10/20 times in the last week.

/priority failing-test
/priority important-soon
/sig cli
/kind flake

**Comment by mithrav** [comment]
@kubernetes/sig-cli-test-failures

**Comment by mithrav** [comment]
Pinging for status

**Comment by mithrav** [comment]
Checking again

**Comment by mengqiy** [comment]
Ack. Sorry for the delay.
It will be harder to miss if it is filed in kubernetes/kubectl repo.

**Comment by mengqiy** [comment]
/assign @shiywang 
Assigning to the author who implemented the feature.

**Comment by mengqiy** [comment]
https://k8s-testgrid.appspot.com/sig-cli-master#gce&width=5 `Kubectl apply apply set/view last-applied` looks pretty healthy (0 failure).

@mithrav Do you have a pointer to the failing tests or the log? The issue description is not very helpful.

**Comment by mengqiy** [comment]
@mithrav ping

**Comment by AishSundar** [comment]
This test doesnt seem to be flaky anymore. Hence closing the issue. Will reopen if and when needed.

/close

**Comment by AishSundar** [comment]
@mengqiy does this link help in getting you the logs needed to debug the flake?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sig-cli/1757

The test is still failing intermittently, but the % if flake has come down.

**Comment by mengqiy** [comment]
@shiywang Please investigate this. Thanks.

Looks like it's related to the scaler.

**Comment by AishSundar** [comment]
soltysh@ any update on this please?

**Comment by mengqiy** [comment]
> error: Scaling the resource failed with: could not update the scale for deployments.extensions nginx-deployment: Operation cannot be fulfilled on deployments.extensions "nginx-deployment": the object has been modified; please apply your changes to the latest version and try again; Current resource version 1232

This test is flaky because it tries to do [`kubectl scale` on a deployment](https://github.com/kubernetes/kubernetes/blob/9bd4f12c336af339c35e773e1d71a37cad342f57/test/e2e/kubectl/kubectl.go#L779-L781) and it sometimes get an Optimistic Lock error. e.g. [log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sig-cli/1828/) and [log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sig-cli/1829/).

@p0lyn0mial Any idea why this happens?

**Comment by mengqiy** [comment]
I guess this issue may be fixed by https://github.com/kubernetes/kubernetes/pull/60455.
Let's wait and see.

**Comment by mengqiy** [comment]
Looks like the problem has been resolved :)
/close
