### ISSUE TITLE
//pkg/master:go_default_test flakes pull-kubernetes-bazel-test

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#59590]
/kind flake
@kubernetes/sig-scheduling-test-failures 

CI: https://k8s-testgrid.appspot.com/google-unit#bazel-test&width=5

presubmits (note that this will include noise from bad PRs): https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test

**Comment by bsalamat** [comment]
@fejta where should I look to find the flaky tests? I don't see scheduler tests flaking in the links provided.

**Comment by fejta** [comment]
What do you see then? Look for the //pkg/master:go_default_test row, which is at/near the top. Scroll to the right.

**Comment by bsalamat** [comment]
@fejta Am I missing something? Why //pkg/master is related to scheduler?

**Comment by fejta** [comment]
I have no idea.

https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv#L682 doesn't specify a sig for this package, so I guessed.

Please pass forward to the correct sig if you can find a better owner. If you put eh sig name in the test_owners.csv file we will apply it next time.

**Comment by bsalamat** [comment]
I actually don't know what is the right SIG, but I am going to ask around and will pass the issue to the right owner.
For the reference, scheduler tests are under //pkg/scheduler.

**Comment by cheftako** [comment]
This is a duplicate of #59450

**Comment by liggitt** [comment]
/close
duplicate of #59450, fixed in #59844
