### ISSUE TITLE
List ControllerRevision.v1.apps resource with kubectl get all

### ISSUE THREAD

**Issue by xiaolanz** [kubernetes/kubernetes#59596]
/kind feature

**What happened**:
kubectl get all

doesn't list controllerrevision resources

I have to list them specifically:
$k get controllerrevision
NAME                     KIND                         REVISION
example-foo-5d7dfd79c9   ControllerRevision.v1.apps   1
example-foo-74b44748d6   ControllerRevision.v1.apps   2

**What you expected to happen**:
I want cr to be listed with fields "revision" and "timestamp". 

kubectl get all

NAME                     REVISION                         TIMESTAMP
cr/example-foo-5d7dfd79c9      1      2018-02-08T18:58:23Z
cr/example-foo-74b44748d6      2    2018-02-08T18:58:23Z

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by charrywanganthony** [comment]
can you get the resource by `kubectl get controllerrevision ...`

**Comment by xiaolanz** [comment]
Yes.

**Comment by liggitt** [comment]
it's debatable which resources are included in the 'all' category. if @kubernetes/sig-apps-api-reviews determines this should be included (based on the criteria at https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all) it can be controlled by the controllerrevision rest storage. It seems like historical revisions would fall under "resources that are potentially unrecoverable" and not be included.

**Comment by xiaolanz** [comment]
What does "unrecoverable" mean?
