### ISSUE TITLE
Ingress level proxy and redirection to external websites or IPs

### ISSUE THREAD

**Issue by JasonShin** [kubernetes/kubernetes#59614]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
Please add features in Kubernetes Ingress to proxy and redirect traffic to external website or IPs

**What happened**:
It seems like you cannot do this using Ingress on its own so I had to create a Nginx service to do this job, which is somewhat wasteful.

**What you expected to happen**:
I want to simply configure redirection and proxy using Ingress configuration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I will improve the description of this issue after work.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zetaab** [comment]
could you please tell little bit more about use-case. Ingress is used when people connect from outside to services in kubernetes cluster. However, for me this issue looks like you want connect from inside kubernetes cluster to outside, then the correct term is egress.

**Comment by iKettles** [comment]
This is already achievable using an ExternalName Service with an Ingress rule that points to it.

**Comment by JasonShin** [comment]
@zetaab Haha.. you are right. Sorry about my lack of knowledge in Kubernetes.
@iKettles Thanks, I will give this a try soon

**Comment by JasonShin** [comment]
I'm closing this because ExternalName approach works
