### ISSUE TITLE
Rename StorageProtection feature and admission plugins

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#59639]
In 1.9 we introduced PVCProtection feature and admission plugin - user should not delete PVCs that are used by running pods, therefore Kubernetes protects them with finalizers.

In 1.10 we added protection of PVs - admin should not delete PVs that are bound to PVCs (unless they explicitly use some force, of course).

I don't want to have separate features and admission plugins for each object kind we protect, this can escalate quickly into StorageClassProtection and whatnot. I suggested name StorageProtection for admission plugin and feature. @thockin thinks that it's misleading, as we don't protect any storage, only Kubernetes API objects. What is better name?

* ObjectInUseProtection - will we (or someone else) enhance the controller / admission plugins to something non-storage related? It could be useful to have a controller that prevents deletion of X when Y that refers to X exists.
* StorageObjectInUseProtection?
* PVPVCProtection?

/bug
/sig storage
@kubernetes/sig-storage-pr-reviews 
@NickrenREN @pospispa

**Comment by NickrenREN** [comment]
vote for `StorageObjectInUseProtection`, since we may add `StorageClass Protection` later, and for non-storage related object, we can add new feature gate and controller for it ? not sure

**Comment by NickrenREN** [comment]
I can change them if necessary

/assign

**Comment by saad-ali** [comment]
Either `PVPVCProtection` or `StorageObjectInUseProtection` sound good to me.

**Comment by saad-ali** [comment]
CC @thockin @msau42

**Comment by jsafrane** [comment]
Let it be `StorageObjectInUseProtection`. @NickrenREN, can you please rename it?

**Comment by NickrenREN** [comment]
yes. sure. i will update them
