### ISSUE TITLE
use Tensorflow-GPU Image to Create Pod without applying for any GPU resource On the Machine with GPU card, but when i login the container.  I can use GPU to train my tensorflow Model

### ISSUE THREAD

**Issue by terryKing1992** [kubernetes/kubernetes#59631]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There I have an machine with GPU card. and I use kubectl + yaml file to start a container based on tensorflow image without applying any GPU resource. bug when I login this container, then use the below python script to run my tensorflow code. it is strange that the console can print the GPU info.
that means the container rally have one GPU resource.

```
  import tensorflow as tf
  session = tf.Session()
```

but in my yaml config file. I did not apply for any gpu resource.  the `request` and `limit` attribute's value have no gpu info.

**What you expected to happen**:
I want the container don't use GPU to train my tensorflow task. in other words, i  want the container have no GPU card. but in fact it rally have one. 

**How to reproduce it (as minimally and precisely as possible)**:
1、build a tensorflow-gpu image or download the official image with jupyter.
2、write an yaml file don't apply for any gpu resource
3、make sure the container can running on the machine that has one or more GPU card.

**Anything else we need to know?**:
I read about the k8s doc [https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/), but i have no idea about this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): V1.7.3
- Cloud provider or hardware configuration: standard configuration
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): Linux 3.10.0 X86_64
- Install tools: on manual
- Others: GPU Info K40.

any idea for this strange problem？ thanks a lot

**Comment by pineking** [comment]
@terryKing1992 this is the similar result as the limit set to 0.
a workaround is to use env to tell nvidia-container-runtime not to expose the GPU
https://github.com/kubernetes/kubernetes/issues/59629#issuecomment-364444680

**Comment by terryKing1992** [comment]
@pineking i will have a try, thanks for your reply~
