### ISSUE TITLE
kubectl timeout error is misleading

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#59658]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli
/area kubectl

**What happened**:

I ran `kubectl get deploy` while not on a network able to connect to the apiserver, which resulted in 

`the server doesn't have a resource type "deploy"`

If I run it with `--v=6` I see:
`I0209 10:24:41.786095   37193 cached_discovery.go:124] skipped caching discovery info due to Get https://<host>/api: dial tcp <ip>:443: i/o timeout`

**What you expected to happen**:

I expect that kubectl would show an error indicating that a timeout occurred so that it's clear to users what actually went wrong. 

**How to reproduce it (as minimally and precisely as possible)**:

Run kubectl with an invalid apiserver. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2

**Comment by martinmosegaard** [comment]
Maybe related to https://github.com/kubernetes/kubernetes/issues/57198
