### ISSUE TITLE
IPVS proxier doesn't handle nodes with iptables policy FORWARD DROP

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#59656]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Testing with the IPVS mode proxier on a host with iptables FORWARD policy = DROP, as configured by docker in recent versions, I found that traffic to NodePorts failed when the NodePort forwarded the traffic to another node.

Saw the iptables FORWARD=DROP counter increasing with each packet.

**What you expected to happen**:

IPVS mode should whitelist such traffic in a similar way to the iptables mode:

* iptables discussion: https://github.com/kubernetes/kubernetes/issues/39823
* PR implementing the fix for iptables mode: https://github.com/kubernetes/kubernetes/pull/52569

**How to reproduce it (as minimally and precisely as possible)**:

* install a routed network plugin; such as Calico (v3.0 required for IPVS NetworkPolicy support)
* enable ipvs mode on the kube-proxy
* create a server pod on one node with a NodePort service
* access the NodePort via another node (I was testing from a busybox pod on the other node)

**Anything else we need to know?**:

Setting the policy to ACCEPT manually is insecure but it acts as a workaround: `iptables -P FORWARD ACCEPT`

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): 
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux smc-kubeadm-node-0 4.13.0-1008-gcp #11-Ubuntu SMP Thu Jan 25 11:08:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Others:

**Comment by m1093782566** [comment]
Okay, but possibly we need an ipset-way to resolve it.

**Comment by fasaxc** [comment]
I think the same fix used in the iptables version should work, it's fairly static:

- if KUBE-MASQ is set, ACCEPT
- if to/from the cluster IP CIDR, ACCEPT

**Comment by m1093782566** [comment]
Fix goes in now, please check the head. Thanks!

**Comment by rramkumar1** [comment]
@fasaxc Can you confirm on your end whether the fixed worked?

**Comment by fasaxc** [comment]
I think @song-jiang is planning to take a look at this.

**Comment by rramkumar1** [comment]
@fasaxc If this problem was indeed not fixed, please reopen.
/close.
