### ISSUE TITLE
IPVS dev work

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#59662]
Using this issue to track outstanding dev work that needs to be completed before IPVS goes GA. 

- [x] Address open bugs 
    - [x] #60257
    - [x] #60305
    - [x] #59656
    - [x] #59507
    - [x] #59976
    - [x] #59505
    - [x] #60688
- [x] Address open PR's 
    - [x] #52528
    - [x] #59632
    - [x] #58052
- [x] Address test failures
    - [x] #61328
    - [x] #61090
    - [x] #61938 
    - [x] #63351
- [x] Resolve kernel module loading 
    - [x] #59402

/area ipvs
/sig network

**Comment by m1093782566** [comment]
Thanks @rramkumar1 for tracking all of them :)

**Comment by jiaxuanzhou** [comment]
@m1093782566 杜总活儿好啊，需要帮忙么，还有这么多

**Comment by m1093782566** [comment]
@jiaxuanzhou 注意影响

**Comment by jiaxuanzhou** [comment]
@m1093782566 :)

**Comment by Lion-Wei** [comment]
@rramkumar1 I think #59656 is finished, and hopefully #59507 will be solve and merged soon. Looking forward for ipvs GA in 1.11 :grinning:

**Comment by Lion-Wei** [comment]
@rramkumar1 I think all issue/pr in this list have been solved(except #57841, not sure we should do this, since iptables part#60074 not merged yet), 
Finially we can make ipvs GA. :grinning:
