### ISSUE TITLE
Per-pod identity for various workloads including DaemonSets and StatefulSets

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#59670]
/kind feature

There are many use cases where rather than relying on the single service account associated with each DaemonSet or StatefulSet, the application requires identity for each pod.

One specific use case is the Local Volume External Provisioner, which manages the creation and deletion of PersistentVolumes for local storage. It currently runs as a DaemonSet, and each provisioner pod has to modify PVs associated with local volumes on the node it's scheduled on. The problem is every pod has permissions to modify every PV, so if a single node gets compromised, all local storage PVs can get corrupted. Because there is no notion of per-pod identity, there isn't a mechanism today to have different access restrictions for each pod. Once per-pod identity is available, PV restrictions could possibly be implemented using an external admission webhook and PV provisioner annotations.

The existing provisioner is [here](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume/provisioner#design). [This design doc](https://github.com/kubernetes/community/pull/1105) discusses different ways to work around the lack of per-pod identity. [This section](https://github.com/verult/community/blob/1d98d3f0243ae4ff0f85c48f3c9e46feebd25499/contributors/design-proposals/local-pv-provisioner.md#security-requirements) is a summary of the security requirements.

/sig auth

**Comment by msau42** [comment]
It actually Creates and Deletes PVs, not modifies.

**Comment by ericchiang** [comment]
The TokenRequest work merged as alpha in 1.10 should be the first steps toward this feature. They allow non-persisted service account tokens with claim that include the pod ID they're request for.

https://github.com/kubernetes/kubernetes/issues/58790
https://github.com/kubernetes/community/pull/1460

There's still work to be done on the node side to replicate the current service account behavior, but it should cover this feature request.
