### ISSUE TITLE
Caching value of default priority in Priority admission controller is not HA safe

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#59679]
@liggitt [identified an issue](https://github.com/kubernetes/kubernetes/pull/59382#discussion_r166501664) in Priority admisison controller that could cause a problem in HA scenarios. The admission controller caches the value of default priority and uses it for Pods that do not provide a priority class. It invalidates the cache when another default priority class is added. In HA mode, another API server may observe addition of another priority class and the cache of the first API server may get stale.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig scheduling

**Comment by liggitt** [comment]
> if the API server loses leadership

There is no API server leadership. API requests are free to be handled by any server.

**Comment by bsalamat** [comment]
> There is no API server leadership. API requests are free to be handled by any server.

I see. So, the issue is even worse than what I described. Do you see any solution other than dropping the caching altogether?

**Comment by smarterclayton** [comment]
Doesn’t seem much different than any other admission controller cases.  We don’t aggressively bound liveness of other admission caches.  Probably if we want to do that we should consider a general solution.

**Comment by liggitt** [comment]
This is trying to prevent two objects both claiming they're the default. That doesn't seem strictly possible. Worth looking at what storage class did in this case (they also have a "default" indicator, though it's an annotation and might not be enforced)

**Comment by wackxu** [comment]
`storageclass` does not use the cache, instead, they query "default" from the informer cache every request.

**Comment by bsalamat** [comment]
> This is trying to prevent two objects both claiming they're the default. That doesn't seem strictly possible. 

The caching mechanism of the admission controller is only for finding default priority of pods. It is not used when ensuring that two objects both claim they are the default.

I am not sure about removing the caching completely. It could hurt performance much if we look up default priority for every pod, especially when a large number of pods are created for a collection. We should add a watch for priority classes and update the cache when a new default priority class is created.

**Comment by bsalamat** [comment]
I spoke with @lavalamp about the issue here. Given that informers cache objects and the admission controller uses an informer to list priority classes, we believe removal of caching inside the admission controller should not a have a significant impact on performance. So, #59712 is enough to address the issue.

**Comment by bsalamat** [comment]
This issue is addressed.

**Comment by lavalamp** [comment]
There is delay between an object being added/modified and it showing up in the informer. During that time, different apiservers may have different opinions about the active value. Is this a problem?

**Comment by bsalamat** [comment]
> There is delay between an object being added/modified and it showing up in the informer. During that time, different apiservers may have different opinions about the active value. Is this a problem?

This could also cause inconsistencies in resolving priority values of Pods when creation requests are handled by two API servers that have inconsistent defaults, but I am not sure if we could do much to prevent it.

We have done two changes to address the default priority class resolution in HA mode:
1. We no longer cache default priority class in the admission controller. So, the chance of cache having stale information is lower.
2. We no longer enforce having only one default priority class, instead we pick the lowest priority as default when more than one default priority class exist.

These two changes lower the possibility of having inconsistent information, but cannot completely eliminate having transient inconsistent values in multiple api servers.

**Comment by lavalamp** [comment]
This is not the only item for which it'd be nice to have a global lock on
apiserver or other synchronization mechanism. Will try to keep it in mind.
(other items: config changes, api version changes, admission webhook
enforcement, CRD handling, etc)
