### ISSUE TITLE
Overlay network refuse to work on 1st master node consistently

### ISSUE THREAD

**Issue by eroji** [kubernetes/kubernetes#59687]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I am trying to build a HA cluster with 3 master nodes, however, overlay network always breaks on master1 . Once Flannel is installed, all 3 masters become "Ready" and I see kube-dns pods starting up. I can also fetch the IP it has been assigned with, but when I try to ping it from each of the master nodes, only master2 and master3 are able to get a response. This happens every time if you try to init the cluster. This also means any other pods that start up subsequently is not reachable from master1.

**What you expected to happen**:
The init should work as expected and once overlay network is installed, all nodes should be able to reach all pods.

**How to reproduce it (as minimally and precisely as possible)**:
1. Installed external etcd with TLS
2. Install docker, kubelet, flanneld on master nodes
3. Configure and start flanneld with TLS authentication
4. Start docker and initalize cluster with kubeadm and supplied custom configure with all etcd endpoints and certs
5. Copy /etc/kubernetes/pki to master2, master3 and kubeadm init them as well
6. Modify kube-apiserver.yaml to enable endpoint-reconciller
7. Install flannel overlay pod and roles using kube-flannel.yml
8. Monitor master nodes become ready and kube-dns pod creation
9. Check what IP the pod is assigned with and try to ping it from each master node

**Anything else we need to know?**:
The etcd nodes (3) are external and using TLS authentication. I don't think that should matter.
I noticed the iptables rules changed once the flannel pod is installed
From:
```
Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
Chain KUBE-FORWARD (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.244.0.0/16        anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.244.0.0/16        /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED
Chain KUBE-SERVICES (2 references)
target     prot opt source               destination         
REJECT     tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns-tcp has no endpoints */ tcp dpt:domain reject-with icmp-port-unreachable
REJECT     udp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns has no endpoints */ udp dpt:domain reject-with icmp-port-unreachable
```
To:
```
Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
Chain KUBE-FORWARD (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  kube-master-01.mydomain.com/16  anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             kube-master-01.mydomain.com/16  /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED
Chain KUBE-SERVICES (2 references)
target     prot opt source               destination     
```
The pod kube-dns is running on master3
`kube-controller-manager-kube-master-03.mydomain.com   1/1       Running   1          27m       10.1.130.167   kube-master-03.mydomain.com`
The flannel pod on master3 shows routing error
```
I0210 01:21:39.994546       1 main.go:475] Determining IP address of default interface
I0210 01:21:39.996815       1 main.go:488] Using interface with name eth0 and address 10.1.130.167
I0210 01:21:39.996835       1 main.go:505] Defaulting external address to interface address (10.1.130.167)
I0210 01:21:40.016707       1 kube.go:131] Waiting 10m0s for node controller to sync
I0210 01:21:40.016779       1 kube.go:294] Starting kube subnet manager
I0210 01:21:41.016924       1 kube.go:138] Node controller sync successful
I0210 01:21:41.016970       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - kube-master-03.mydomain.com
I0210 01:21:41.016978       1 main.go:238] Installing signal handlers
I0210 01:21:41.017173       1 main.go:353] Found network config - Backend type: vxlan
I0210 01:21:41.017250       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
I0210 01:21:41.039621       1 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0210 01:21:41.039638       1 main.go:304] Running backend.
I0210 01:21:41.039650       1 main.go:322] Waiting for all goroutines to exit
I0210 01:21:41.039672       1 vxlan_network.go:60] watching for new subnet leases
I0210 01:21:41.098058       1 iptables.go:115] Some iptables rules are missing; deleting and recreating rules
I0210 01:21:41.098088       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 -j ACCEPT
I0210 01:21:41.100093       1 iptables.go:137] Deleting iptables rule: -d 10.244.0.0/16 -j ACCEPT
I0210 01:21:41.192839       1 iptables.go:115] Some iptables rules are missing; deleting and recreating rules
I0210 01:21:41.192876       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
I0210 01:21:41.193963       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 -j ACCEPT
I0210 01:21:41.195415       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0210 01:21:41.196919       1 iptables.go:137] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.244.2.0/24 -j RETURN
I0210 01:21:41.197745       1 iptables.go:125] Adding iptables rule: -d 10.244.0.0/16 -j ACCEPT
I0210 01:21:41.198468       1 iptables.go:137] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
I0210 01:21:41.199689       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
I0210 01:21:41.295330       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0210 01:21:41.297580       1 iptables.go:125] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.2.0/24 -j RETURN
I0210 01:21:41.299797       1 iptables.go:125] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
E0210 01:21:42.856864       1 vxlan_network.go:158] failed to add vxlanRoute (10.244.0.0/24 -> 10.244.0.0): invalid argument
```
**Environment**:
- Kubernetes version (use `kubectl version`): 1.93
- Cloud provider or hardware configuration: on-prem
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.17.1.el7.x86_64
- Install tools: yum, kubeadm
- Others:

**Comment by rsamo** [comment]
This happened to me recently and I spent nearly a day looking at it. It turns out that my docker0 interface wanted to use the same subnet as the cni0 interface from flannel. check that first with "ifconfig". If this is the case, the following will help you...

`vi /etc/sysconfig/docker

# Append to OPTIONS=
--bip=172.17.42.1/16

systemctl daemon-reload
systemctl restart docker`

Hope this helps!

**Comment by eroji** [comment]
This is resolved. Problem had to do with conflicting documentation where you are instructed to install both flanneld and flannel network pods which caused conflicts in creating the vxlan routes. Removing flanneld and only using pods works just fine.
