### ISSUE TITLE
ResourceVersion="0" causes API list chunking to behave unexpectedly

### ISSUE THREAD

**Issue by madari** [kubernetes/kubernetes#59684]
/kind bug
/sig api-machinery

**What happened**:

API chunking when listing pods does not seem to work with ResourceVersion="0". It seems that when that is set, the API server ignores the limit argument.

I found this out when attempting to use cache.Informer, which sets ResourceVersion=0 on the initial LIST. I filed a separate bug about this here https://github.com/kubernetes/client-go/issues/366. Please de-dupe as you see best. It's not clear whether this is a client or server issue, or both.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with more than one pods, run the following code accessing the cluster via `kubectl proxy -v=7` and notice how chunking is not happening:

```go
// client := ...
lw := &cache.ListWatch{
  ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
    options.Limit = 1
    // Uncommenting the following "fixes" the chunking:
    // if options.ResourceVersion == "0" {
    //  options.ResourceVersion = ""
    // }
    return client.Core().Pods(metav1.NamespaceAll).List(options)
  },
  WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
    return client.Core().Pods(metav1.NamespaceAll).Watch(options)
  },
}
_ informer := cache.NewInformer(lw, &apiv1.Pod{}, 0, cache.ResourceEventHandlerFuncs{})
informer.Run(context.Background())
```

**Environment**:

client-go Version: 78700dec6369ba22221b72770783300f143df150

Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
> It seems that when that is set, the API server ignores the limit argument.

Correct. That is working as intended, since specifying resourceVersion=0 removes the ability of the API server to return a continue token pinned at a particular resource version (since that would be in conflict with the resourceVersion you specified.

/close

**Comment by JohnRusk** [comment]
For more discussion, see https://github.com/kubernetes/client-go/issues/366
