### ISSUE TITLE
cadvisor can't get container label & customize config 

### ISSUE THREAD

**Issue by YanjieGao** [kubernetes/kubernetes#59717]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug

**What happened**:
Hope to get container level label & gpu metrics from cavisor. Kubelet build-in cadvisor can't get container label & no entrypoint to config customize configuration for cadvisor
**What you expected to happen**:
Kubelet build-in cadvisor could report container customize labels
could config cadvisor get gpu metrics.
**How to reproduce it (as minimally and precisely as possible)**:
Just deploy kubernetes and access node's http://hostip:4194/metrics to see the metrics.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration: Azure VM
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): Linux paigcr-a-gpu-1001 4.13.0-1007-azure #9-Ubuntu SMP Thu Jan 25 10:47:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by pineking** [comment]
@YanjieGao do you see some gpu metrics from http://hostip:4194/metrics  , like `container_accelerator_duty_cycle` `container_accelerator_memory_total_bytes` `container_accelerator_memory_used_bytes`

**Comment by DrmagicE** [comment]
I got the same issue. Any solutions? @YanjieGao
