### ISSUE TITLE
Reuse the `min*Nodes` slices in order to save GC time

### ISSUE THREAD

**Issue by tossmilestone** [kubernetes/kubernetes#59748]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Fix the following `TODO` : 
https://github.com/kubernetes/kubernetes/blob/69324f90e602ca088391f22221301beaf990984e/pkg/scheduler/core/generic_scheduler.go#L680-L681

The basic logic in `pickOneNodeForPreemption` of using the `min*Nodes` is continuing reducing the nodes slices through `minPDBViolatingNodes`, `minPriorityNodes`, `minSumPriorityNodes` and `minNumPodNodes`.  It needs 4 slices to do this.

This is my thought to reuse the `min*Nodes` slices:
* Use 2 nodes slices, such as `minNodesA`, `minNodesB`
* The reducing process becomes:
 `minNodesA` -> `minNodesB`
 Clear `minNodesA`
 `minNodesB` -> `minNodesA`
 Clear `minNodesB`
 `minNodesA` -> `minNodesB`

@bsalamat please give some suggestion, thanks :smile:

**Comment by bsalamat** [comment]
The challenge is that clearing a slice and reusing it still needs GC clean up, so it may not be effective. The size of slices shrink as we proceed through the function. So, having two slices and over-writing the elements in them can help reduce GC time, but this approach needs some additional checks to ensure we are not using stale elements.

**Comment by tossmilestone** [comment]
To avoid clearing the slices, this is my thought:
- Declare 2 length vars to indicate the actual length of the 2 node slices, instead of `len()`.
- Appending a node to a node slice will add 1 to the length var.
- Clearing a node slice will set the length var to 0.

@bsalamat WDYT

**Comment by bsalamat** [comment]
@tossmilestone Yes, I can't think of any better solution either, but remember that you should append only to the slice in the first for loop of the function. The second slice should be initialized with the same number of elements as the slice used in the first for loop. Setting elements of the slices should be done by indexing them (not by append) in the second, third, and forth loop.

**Comment by tossmilestone** [comment]
OK, I will submit a PR to implement it. @bsalamat
