### ISSUE TITLE
Invalid capacity 0 on windows image filesystem

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#59742]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

kubectl describe nodes <windows-node>

```
  Warning  InvalidDiskCapacity  5m (x1715 over 5d)   kubelet, 13488k8s9002  invalid capacity 0 on image filesystem
  Warning  ImageGCFailed        49s (x1715 over 5d)  kubelet, 13488k8s9002  invalid capacity 0 on image filesystem
```

**What you expected to happen**:

Kubelet should get correct stats on windows nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with windows nodes and run `kubectl describe nodes <node-name>`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jberkus** [comment]
adding priority so this can stay in 1.10

/priority important-soon

**Comment by jberkus** [comment]
@feiskyer if this issue is a 1.10 release blocker, please add status/approved-for-milestone to it before Code Freeze on Monday.  Thanks!

**Comment by loxal** [comment]
Got exactly the same issue on Fedora 32 for which reason the respective node remains `NotReady`.
