### ISSUE TITLE
kubectl exec fails when ValidatingWebhookConfiguration matches pods/exec resource

### ISSUE THREAD

**Issue by tsandall** [kubernetes/kubernetes#59759]
/kind bug

**What happened**: apiserver returns InternalError for `kubectl exec` when ValidatingWebhookConfiguration matches pods/exec resource.

**What you expected to happen**: Webhook should be invoked and admission control decision should be enforced on CONNECT operation

**How to reproduce it (as minimally and precisely as possible)**:

```
# Create a pod to connect to
$ kubectl create -f nginx-pod.yml
```

```
# Verify that exec works BEFORE creating ValidatingWebhookConfiguration
$ kubectl exec -it nginx hostname
nginx
```

```
# Create ValidatingWebhookConfiguration that matches pods/exec resource
$ cat webhook-registration.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: webhook
webhooks:
  - name: webhook.example.com
    rules:
      - operations: ["CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods/exec"]
    clientConfig:
      service:
        namespace: foo
        name: bar
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQ00wNnpLbi9qR2ZEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGd3TWpFd01UWTFNVE0xV2hnUE1qSTVNVEV4TWpZeE5qVXhNelZhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUtkVTdaM2p0b2hIeE9wRGw5dnFNTkxuOWgxNVpVeXN3bEVoZisrVi9ueUhsa0Q2ek1MZGZPRFQKMXFBL1cvazIxajRPUUdFRjRQQkFHcGxESjVYZ3E0QnM2TURWdjNiQXZYdUdTb2xrYkVNS25iTldzWmdKakZNdQpNZmU4Q2pYNTFVUkU5NlhLOUxYT2pUVFlXamtscFgrMStjSjRjZUhDVmhmb281TU9xaXhaUHhkTFgyR0xIcVNsCkprbXgyQzRKWktBQWE2azFiUmVPNENaS2NTRGZYUmkwS21rUUZERjdZR0JWbzRBRTZCNHFIZm43cTBXd3dwREIKaUJETkd2cGtQUjRVY3MyeWtWRStMbDYxaU1aS3pkbm1jYlRSVHFDK1pFL1pManNieHVwZDVmWm1rcW1na0xlagpiQnhRakYwNXYxSy90MFExbUVUTVpOVlVtb0pia0lrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkJoOUYyN2ZMb2M0NUNrcTAyNVhLZHRWdlh5OWRTU2tSSmJVMGhjSTJJaVhHeExVZkdBdFdFdm56ZDVNd0FXSloKQ1lTT2ZZMCt6WHNOZFE4dXVTVVFzOVE5dlcxcmlBUXQ5TFVpWEVkK3Nva1Zxbm43MXU5N0RuT2NkS3VkL1JsUQpvdFRTZU1ieTF2cUhYWUFReUhRTlp2NmdYaWRkaHFRUFJRejJHNjFUNDdnN21SL2szQVVwdHNUeFVjY0MrTzZyCjZHekpDaXg4ZEN0cmJPNCtLcFU5Y1VkdC96ZjgzNXFVZ211QTYvSXNNQi9ZcSs0a2RIM0krZy9xQTFic0sram4Kd3dmZERsVFVPd1Q1THk3T1lWbExsNlR4YVd3WjYzS21ubHM5Q0pLbmY2VngwL1F6Vncwb1ZtZzQ3cHdZZXZxUwpZcVFJWnBlMzB5QmhlSGpNZEUvaVFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

$ kubectl create -f webhook-registration.yaml
validatingwebhookconfiguration "webhook" created
```

```
# Try to exec into container AFTER creating ValidatingWebhookConfiguration
$ kubectl exec -it nginx hostname
Error from server (InternalError): Internal error occurred: converting (rest.ConnectRequest) to (v1.Pod): TypeMeta not present in src
```

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

Tested on minikube v0.25

**Comment by caesarxuchao** [comment]
@tsandall what aspect of the exec call does your webhook intend to verify?

We lack the proper api machinery to serialize/convert the `rest.ConnectRequest` object. Perhaps we can work something out to passing the `ConnectRequest.Options` to the webhook.

@sttts I saw you had a comment here, https://github.com/kubernetes/kubernetes/blob/f88ff2ab419f40399bb0f9662ed53888f5830fff/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L120, does it mean that we shouldn't write any admissions around "Connect" at all?

**Comment by tsandall** [comment]
@caesarxuchao at minimum the webhook should be able to identify the pod and container that exec is run against...having access to the command would be nice.

This worked pre-1.9 but I forget if the serialization was correct. There was an issue with the internal object representation being sent across the wire. I don't remember if that affected the webhook payload for CONNECT operations.

A couple problems that come to mind.

1. if the webhook operation is `'*'` then it will match CONNECT and prevent exec access
2. CONNECT is also used for port-forward IIRC

**Comment by caesarxuchao** [comment]
> @caesarxuchao at minimum the webhook should be able to identify the pod and container that exec is run against...having access to the command would be nice.

It seems the pod name will be in [ConnectRequest.Name](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/rest.go#L357) and the container name will be in [ConnectRequest.Options.Container](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3884). We need to forward the entire `ConnectRequest` to the webhook.

I'll wait for @sttts to reply, it seems he has plans for `CONNECT`.

**Comment by tsandall** [comment]
Forwarding the entire ConnectRequest is preferable from my point of view. In the mean time, I'll update the Open Policy Agent docs to avoid this issue (i.e., by specifying the operations w/o the wildcard.)

**Comment by sttts** [comment]
> does it mean that we shouldn't write any admissions around "Connect" at all?

We call Admit and Validate at that point. The comment meant that mutation does not make much sense there. Though with your suggestion to pass `ConnectRequest.Options` it might actually make sense to mutate.

But turning `rest.ConnectRequest` into a runtime.Object looks wrong. As a webhook author I would merely expect to get sent the real object behind the CONNECT request plus the options in a separate AdmissionReview fields.

**Comment by caesarxuchao** [comment]
> As a webhook author I would merely expect to get sent the real object behind the CONNECT request plus the options in a separate AdmissionReview field.

Agree that the webhook needs to see the real object, but the real object won't be included in the user's request. I think it's fine for the webhooks to GET the real object from the apiserver, like how the existing compiled-in admission controller does: https://github.com/kubernetes/kubernetes/blob/742a90cb5a4485c6db4ecd9b547b96335ec10745/plugin/pkg/admission/exec/admission.go#L105

> But turning rest.ConnectRequest into a runtime.Object looks wrong. 

I want to remove `ConnectRequest`, and move the `ConnectRequest.Name` and `ConnectRequest.ResourcePath` into the connect options, which are already properly versioned (see [NodeProxyOptions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4397) and [PodAttachOptions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4297)).
We'll also have to set the scope.Kind correctly, so that webhook controller can covert the options correctly. Currently scope.Kind is set to v1/pod and v1/node.
