### ISSUE TITLE
Pods can be easily escaped from using kubectl

### ISSUE THREAD

**Issue by molerus** [kubernetes/kubernetes#59751]
/kind bug

**What happened**:
If pod creation request doesn't contain k8s service account then it is given default one which is good for the namespace in which it runs. One can download and run kubectl from within a pod/container and execute commands against other pods within the namespace. This on its own is peculiar as one pod shouldn't probably have such permissions (at least not by default), but it gets even worse. One can also list pods and execute commands (eg. kubectl exec) against pods that reside in all namespaces including default one. Since the pods may run on machines with different security scopes this seems like pretty significant security hole. If I create service account devoid of any permissions the communication is blocked.

**What you expected to happen**:
 The pods shouldn't be assigned with default service account that allows access virtually to the entire cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create pods in different namespaces and kubectl exec bash into either of them. Download kubectl and run kubectl get pods --all-namespaces. kubectl exec into any other pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.12-gke.0", GitCommit:"f4f0bedb82a57dc32b21b8f15fe01e0b8411356b", GitTreeState:"clean", BuildDate:"2018-01-05T03:35:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GKE, master version 1.7.12-gke.0, node poll version 1.7.8-gke.0
- OS (e.g. from /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux infra2-controller-2999733264-fxk9p 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by phsiao** [comment]
It is not required to grant any service account in user namespace permission.   How do you set up your authorization?   Do you use RBAC?

**Comment by liggitt** [comment]
> One can download and run kubectl from within a pod/container and execute commands against other pods within the namespace. This on its own is peculiar as one pod shouldn't probably have such permissions (at least not by default)

Agreed. Default RBAC policy does not grant permissions to the default service accounts. Check your cluster setup to make sure you are using RBAC, and that nothing in your cluster setup is granting additional non-default permissions

/close
