### ISSUE TITLE
[e2e test failure] Volume metrics PVController

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#59763]
from https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Volume%20metrics%20PVController

Failed in 5 Jobs ▼
 24 ci-kubernetes-e2e-gke-ubuntustable1-k8sdev-serial ►
 23 ci-kubernetes-e2e-gci-gke-serial ►
 6 ci-kubernetes-e2e-gke-cosbeta-k8sdev-soak ►
 9 ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new ►
 8 ci-kubernetes-soak-gke-gci ►
Failed in 4 Tests ▼
 70 [sig-storage] [Serial] Volume metrics PVController should create unbound pvc count metrics for pvc controller after creating pvc only ►
 69 [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc ►
 67 [sig-storage] [Serial] Volume metrics PVController should create none metrics for pvc controller before creating any PV or PVC ►
 66 [sig-storage] [Serial] Volume metrics PVController should create unbound pv count metrics for pvc controller after creating pv only ►

/priority failing-test
/kind bug
/status approved-for-milestone
/sig gcp

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial
the job is on the master-blocking dashboard and the e2e test has been failing, please take a look

cc @jdumars @abgworrall

**Comment by msau42** [comment]
Also see #59517

**Comment by saad-ali** [comment]
Reverted PR in https://github.com/kubernetes/kubernetes/pull/59523
