### ISSUE TITLE
Error testing connection https://kubernetes.default: java.net.UnknownHostException: kubernetes.default: Name does not resolve

### ISSUE THREAD

**Issue by fengyd2018** [kubernetes/kubernetes#59783]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Enviroment:
kubernetes cluster, one master and two nodes.

Start Jenkins on kubernetes cluster.
Add kubernetes cluster to Jenkins cloud.

Input following information in "Kubernetes URL" and Test Connection:
https://kubernetes.default

Error log is printed:
Error testing connection https://kubernetes.default: java.net.UnknownHostException: kubernetes.default: Name does not resolve

**What you expected to happen**:
Connection test successful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`):
Linux k8s-master 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by zetaab** [comment]
is this really bug? Imo no, try using host kubernetes.default.svc.cluster.local or just kubernetes

**Comment by fengyd2018** [comment]
Hi,

I installed guestbook and found /etc/resolv.conf in the redis-slave container:
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local

But for the container jenkins,  /etc/resolv.conf is the same as the host computer.
I think that's why kubernetes.default cannot be resolved.
Don't know why.

**Comment by fengyd2018** [comment]
I have found the cause. hostNetwork is set as true. 
    spec:
      hostNetwork: true
 After I removed "hostNetwork: true",  /etc/resolv.conf in the jenkins container:
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local openstacklocal
options ndots:5

Obviously, hostNetwork is the cause.
Could you explain the reason?
