### ISSUE TITLE
error kube init 

### ISSUE THREAD

**Issue by Groga** [kubernetes/kubernetes#59794]
root@master manifests]# uname -a
Linux master.testdomain 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

root@master manifests]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 

swapoff -a 

cat 10-kubeadm.conf 
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_CERTIFICATE_ARGS=--fail-swap-off=false"
Environment="KUBELET_EXTRA_ARGS=-fail-swap-on=false" 
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
[1]+  Exit 1                  docker search httpd https://index.docker.io/v1/search?q=httpd

cat 90-local-extras.conf 
Environment = "KUBELET_EXTRA_ARGS = - fail-swap-on = false"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"

kubeadm reset
[preflight] Running pre-flight checks.
[reset] Stopping the kubelet service.
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Removing kubernetes-managed containers.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

[root@master manifests]# kubeadm init
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.12.0-ce. Max validated version: 17.03
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Starting the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [master.testdomain kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.150.1]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz/syncloop' failed with error: Get http://localhost:10255/healthz/syncloop: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
	- There is no internet connection, so the kubelet cannot pull the following control plane images:
		- gcr.io/google_containers/kube-apiserver-amd64:v1.9.3
		- gcr.io/google_containers/kube-controller-manager-amd64:v1.9.3
		- gcr.io/google_containers/kube-scheduler-amd64:v1.9.3

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
couldn't initialize a Kubernetes cluster

systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 90-local-extras.conf
   Active: activating (auto-restart) (Result: exit-code) since Вт 2018-02-13 14:34:13 MSK; 7s ago
     Docs: http://kubernetes.io/docs/
  Process: 10656 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=2)
 Main PID: 10656 (code=exited, status=2)

фев 13 14:34:13 master.testdomain kubelet[10656]: --system-cgroups /                                          ...oot.
фев 13 14:34:13 master.testdomain kubelet[10656]: --system-reserved mapStringString                               ...
фев 13 14:34:13 master.testdomain kubelet[10656]: --system-reserved-cgroup string                                 ...
фев 13 14:34:13 master.testdomain kubelet[10656]: --tls-cert-file string                                          ...
фев 13 14:34:13 master.testdomain kubelet[10656]: --tls-private-key-file string                               ...ile.
фев 13 14:34:13 master.testdomain kubelet[10656]: -v, --v Level                                               ...logs
фев 13 14:34:13 master.testdomain kubelet[10656]: --version version[=true]                                    ...quit
фев 13 14:34:13 master.testdomain kubelet[10656]: --vmodule moduleSpec                                        ...ging
фев 13 14:34:13 master.testdomain kubelet[10656]: --volume-plugin-dir string                                  ...c/")
фев 13 14:34:13 master.testdomain kubelet[10656]: --volume-stats-agg-period duration                          ...m0s)
Hint: Some lines were ellipsized, use -l to show in full.

journalctl -xeu kubelet
фев 13 14:34:44 master.testdomain kubelet[10678]: --make-iptables-util-chains                                           
фев 13 14:34:44 master.testdomain kubelet[10678]: --manifest-url string                                                 
фев 13 14:34:44 master.testdomain kubelet[10678]: --manifest-url-header --manifest-url-header 'a:hello,b:again,c:world' 
фев 13 14:34:44 master.testdomain kubelet[10678]: --max-open-files int                                                  
фев 13 14:34:44 master.testdomain kubelet[10678]: --max-pods int32                                                      
фев 13 14:34:44 master.testdomain kubelet[10678]: --minimum-image-ttl-duration duration                                 
фев 13 14:34:44 master.testdomain kubelet[10678]: --network-plugin string                                               
фев 13 14:34:44 master.testdomain kubelet[10678]: --network-plugin-mtu int32                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --node-ip string                                                      
фев 13 14:34:44 master.testdomain kubelet[10678]: --node-labels mapStringString                                         
фев 13 14:34:44 master.testdomain kubelet[10678]: --node-status-update-frequency duration                               
фев 13 14:34:44 master.testdomain kubelet[10678]: --oom-score-adj int32                                                 
фев 13 14:34:44 master.testdomain kubelet[10678]: --pod-cidr string                                                     
фев 13 14:34:44 master.testdomain kubelet[10678]: --pod-infra-container-image string                                    
фев 13 14:34:44 master.testdomain kubelet[10678]: --pod-manifest-path string                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --pods-per-core int32                                                 
фев 13 14:34:44 master.testdomain kubelet[10678]: --port int32                                                          
фев 13 14:34:44 master.testdomain kubelet[10678]: --protect-kernel-defaults                                             
фев 13 14:34:44 master.testdomain kubelet[10678]: --provider-id string                                                  
фев 13 14:34:44 master.testdomain kubelet[10678]: --read-only-port int32                                                
фев 13 14:34:44 master.testdomain kubelet[10678]: --really-crash-for-testing                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --register-node                                                       
фев 13 14:34:44 master.testdomain kubelet[10678]: --register-with-taints []api.Taint                                    
фев 13 14:34:44 master.testdomain kubelet[10678]: --registry-burst int32                                                
фев 13 14:34:44 master.testdomain kubelet[10678]: --registry-qps int32                                                  
фев 13 14:34:44 master.testdomain kubelet[10678]: --resolv-conf string                                                  
фев 13 14:34:44 master.testdomain kubelet[10678]: --rkt-api-endpoint string                                             
фев 13 14:34:44 master.testdomain kubelet[10678]: --rkt-path string                                                     
фев 13 14:34:44 master.testdomain kubelet[10678]: --root-dir string                                                     
фев 13 14:34:44 master.testdomain kubelet[10678]: --rotate-certificates                                                 
фев 13 14:34:44 master.testdomain kubelet[10678]: --runonce                                                             
фев 13 14:34:44 master.testdomain kubelet[10678]: --runtime-cgroups string                                              
фев 13 14:34:44 master.testdomain kubelet[10678]: --runtime-request-timeout duration                                    
фев 13 14:34:44 master.testdomain kubelet[10678]: --seccomp-profile-root string                                         
фев 13 14:34:44 master.testdomain kubelet[10678]: --serialize-image-pulls                                               
фев 13 14:34:44 master.testdomain kubelet[10678]: --stderrthreshold severity                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-buffer-duration duration                             
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-db string                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-host string                                          
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-password string                                      
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-secure                                               
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-table string                                         
фев 13 14:34:44 master.testdomain kubelet[10678]: --storage-driver-user string                                          
фев 13 14:34:44 master.testdomain kubelet[10678]: --streaming-connection-idle-timeout duration                          
фев 13 14:34:44 master.testdomain kubelet[10678]: --sync-frequency duration                                             
фев 13 14:34:44 master.testdomain kubelet[10678]: --system-cgroups /                                                    
фев 13 14:34:44 master.testdomain kubelet[10678]: --system-reserved mapStringString                                     
фев 13 14:34:44 master.testdomain kubelet[10678]: --system-reserved-cgroup string                                       
фев 13 14:34:44 master.testdomain kubelet[10678]: --tls-cert-file string                                                
фев 13 14:34:44 master.testdomain kubelet[10678]: --tls-private-key-file string                                         
фев 13 14:34:44 master.testdomain kubelet[10678]: -v, --v Level                                                         
фев 13 14:34:44 master.testdomain kubelet[10678]: --version version[=true]                                              
фев 13 14:34:44 master.testdomain kubelet[10678]: --vmodule moduleSpec                                                  
фев 13 14:34:44 master.testdomain kubelet[10678]: --volume-plugin-dir string                                            
фев 13 14:34:44 master.testdomain kubelet[10678]: --volume-stats-agg-period duration   

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

re-read many forums, nothing helped to solve the problem

journalctl -b -u kubelet

фев 13 16:48:01 master.testdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
фев 13 16:48:01 master.testdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
фев 13 16:48:01 master.testdomain systemd[1]: Starting kubelet: The Kubernetes Node Agent...
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.425053   28332 feature_gate.go:226] feature gates: &{{} map[]}
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.425262   28332 controller.go:114] kubelet config controller: starting controller
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.425279   28332 controller.go:118] kubelet config controller: validating combination of defaults and flags
фев 13 16:48:01 master.testdomain kubelet[28332]: W0213 16:48:01.433838   28332 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.439875   28332 server.go:182] Version: v1.9.3
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.440490   28332 feature_gate.go:226] feature gates: &{{} map[]}
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.440956   28332 plugins.go:101] No cloud provider specified.
фев 13 16:48:01 master.testdomain kubelet[28332]: E0213 16:48:01.498941   28332 certificate_manager.go:314] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post https://192.168.150.1
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.535688   28332 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.536252   28332 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.536292   28332 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRu
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.536644   28332 container_manager_linux.go:266] Creating device plugin manager: false
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.536915   28332 kubelet.go:290] Adding manifest path: /etc/kubernetes/manifests
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.536972   28332 kubelet.go:313] Watching apiserver
фев 13 16:48:01 master.testdomain kubelet[28332]: E0213 16:48:01.545377   28332 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.150.1:6443/api/v1/nodes?fieldSelector=metadata.nam
фев 13 16:48:01 master.testdomain kubelet[28332]: E0213 16:48:01.546344   28332 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.150.1:6443/api/v1/pods?fieldSelector=spec.n
фев 13 16:48:01 master.testdomain kubelet[28332]: E0213 16:48:01.547226   28332 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.150.1:6443/api/v1/services?limit=500&resourceVe
фев 13 16:48:01 master.testdomain kubelet[28332]: W0213 16:48:01.559035   28332 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.559092   28332 kubelet.go:571] Hairpin mode set to "hairpin-veth"
фев 13 16:48:01 master.testdomain kubelet[28332]: W0213 16:48:01.559210   28332 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.559296   28332 client.go:80] Connecting to docker on unix:///var/run/docker.sock
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.559328   28332 client.go:109] Start docker client with request timeout=2m0s
фев 13 16:48:01 master.testdomain kubelet[28332]: W0213 16:48:01.563392   28332 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
фев 13 16:48:01 master.testdomain kubelet[28332]: W0213 16:48:01.568975   28332 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.569088   28332 docker_service.go:232] Docker cri networking managed by cni
фев 13 16:48:01 master.testdomain kubelet[28332]: I0213 16:48:01.586549   28332 docker_service.go:237] Docker Info: &{ID:RFMW:ZMHU:KPUM:2M4F:TYZC:LASV:JVZS:3QNZ:ZA6W:MRSI:H5P7:AFBU Containers:0 ContainersRunning:0 ContainersPaused:0 Contai
фев 13 16:48:01 master.testdomain kubelet[28332]: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
фев 13 16:48:01 master.testdomain systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
фев 13 16:48:01 master.testdomain systemd[1]: Unit kubelet.service entered failed state.
фев 13 16:48:01 master.testdomain systemd[1]: kubelet.service failed.

**Comment by dims** [comment]
@Groga try this one - https://github.com/kubernetes/kubernetes/issues/43805#issuecomment-301274928
