### ISSUE TITLE
High flake rates on Downward API volume update e2e tests

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#59813]
There have been **178 flakes** in various forms of Downward API volume update tests **in the past week**. The flakes span several variations on the same underlying functionality (annotation/label update, direct downwardapi/projected) all rooted in the same underlying issue.

The issue afaict is that the volume manger is not getting the updated version of the pod and thus the update to the downward API volume is not happening, even after periodic syncs of the pod.

My investigation thus far is here:
https://bugzilla.redhat.com/show_bug.cgi?id=1538216#c2

This has been an ongoing issue for a *long* time.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&sig=storage&test=on%20modification

Specifically
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&sig=storage&test=on%20modification#29d7730339ad87387e21
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&sig=storage&test=on%20modification#00453201efe289cd34ce
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&sig=storage&test=on%20modification#f2925bc52d8730d3df2c
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&sig=storage&test=on%20modification#19fb1c2e8a094bfc157a

Previous incarnations of this issue (all closed):
https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+downward+api+modification+is%3Aclosed

Most recent issues closed due to inactivity without resolution:
https://github.com/kubernetes/kubernetes/issues/44226
https://github.com/kubernetes/kubernetes/issues/44227

Origin issues:
https://github.com/openshift/origin/issues/17605
https://github.com/openshift/origin/issues/17556

xref https://bugzilla.redhat.com/show_bug.cgi?id=1538216

@derekwaynecarr @dashpole @dchen1107 @vishh @smarterclayton @runcom @yujuhong @saad-ali

**Comment by jsafrane** [comment]
When kubelet gets an updated pod, `WaitForAttachAndMount` is called. It [marks the pod for refresh both is DesiredStateOfWorldPopulator (DSWP) and ActualStateOfWord (ASW)](https://github.com/kubernetes/kubernetes/blob/4afdc33c574bb6941db9563ccec3d7e58c956f8b/pkg/kubelet/volumemanager/volume_manager.go#L347): 

```
	// Some pods expect to have Setup called over and over again to update.
	// Remount plugins for which this is true. (Atomically updating volumes,
	// like Downward API, depend on this to update the contents of the volume).
	vm.desiredStateOfWorldPopulator.ReprocessPod(uniquePodName)
	vm.actualStateOfWorld.MarkRemountRequired(uniquePodName)
```

Now DSWP and reconciler race who gets the pod first.

* If DSWP gets the pod first, it replaces the pod in DSW. Reconciler then calls `SetUp` of volume plugin  with the new pod and the volume is refreshed with new pod annotations / labels.
* If reconciler runs first, it calls `SetUp` of  volume plugin  with the old pod and the volume is **not** refreshed. DSWP gets the pod later, it updates DSW, but reconciler does not refresh the volume until next periodical sync (60-90 seconds by default).

@jingxu97 @saad-ali any ideas how to fix it? I'll prepare PR that calls ASW.MarkRemountRequired() when DSWP processes pod. For that I need to pass pointer to ASW into DSWP and it feels ugly to me.

**Comment by jsafrane** [comment]
PR: #59813 It's not that bad as I thought.
