### ISSUE TITLE
Conflict with CRD short name

### ISSUE THREAD

**Issue by jwendell** [kubernetes/kubernetes#59812]
/kind bug

- Installed a CRD (DestinationPolicy) with the short name 'svc': Install went ok and `kubectl get svc` returned services
- Changed this CRD short name to 'dp'
- Installed another CRD (EgressRule) with the short name 'dp': Install was not so ok. Status reported a conflict in the short name and `kubectl get egressrule` fails with the message `the server doesn't have a resource type "egressrules"`
- Changed this (EgressRules) CRD short name to 'svc'. `kubectl get svc` returned egress rules!!

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+0d5291c", GitCommit:"0d5291c", GitTreeState:"clean", BuildDate:"2017-12-12T16:34:06Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
This may have already been fixed by https://github.com/kubernetes/kubernetes/pull/58861 and https://github.com/kubernetes/kubernetes/pull/59342

**Comment by jwendell** [comment]
@liggitt thanks. Do you know if those fixes are available at any released version so that I can try on minikube?

**Comment by liggitt** [comment]
I think they are just in the 1.10 dev stream

**Comment by nikhita** [comment]
> This may have already been fixed by #58861 and #59342

Can confirm that this does not occur on HEAD.

```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.153+064338951f219e", GitCommit:"064338951f219ea4393f57bddb7bee24dbe54f62", GitTreeState:"clean", BuildDate:"2018-02-19T16:52:44Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.153+064338951f219e", GitCommit:"064338951f219ea4393f57bddb7bee24dbe54f62", GitTreeState:"clean", BuildDate:"2018-02-19T16:52:44Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Could reproduce this on an earlier client version (1.8.5) though. So this is fixed now. :+1: 

Closing.

/close

**Comment by roytman** [comment]
Hi,
I repeated this test with K8s v 1.11
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
Looks like shortName conflicts between CRDs and core objects are not checked, and `kubectl get <shortName>` commands use the core objects' shortName mapping.

- Installed a CRD (DestinationPolicy) with the short name 'svc': Install went ok and kubectl get svc returned services.  **The CRD `Conditions` show "no conflicts found"** 
- Changed this CRD short name to 'dp'
- Installed another CRD (EgressRule) with the short name 'dp': Install was not so ok. Status reported a conflict in the short name and kubectl get egressrule fails with the message the server doesn't have a resource type "egressrules"
- Changed this (EgressRules) CRD short name to 'svc'.  **The CRD `Conditions` show "no conflicts found" kubectl get svc returned services!!**



/CC @nikhita

**Comment by liggitt** [comment]
shortnames can be used within different groups, like `kubectl get svc.mygroup.io`

**Comment by liggitt** [comment]
when unqualified by a group, shortnames follow server specified group priority, which resolves core api groups first. 

this matches behavior of actual names (non-shortnames). You could define a resource in your group named `services` and the results would be the same
