### ISSUE TITLE
kubectl port-forward should support re-attach

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#59816]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

With work being done in #59705 and #59809, it is now possible to select a pod from a collection of pods via resource/name.  It is now more natural to support re-attach if the selected pod terminated during a port-forward session to improve user experience.

**What you expected to happen**:

kubectl port-forward resource/name would re-attach to a new qualified pod if the selected one died, without having to re-run the command

**Comment by sgandon** [comment]
I really wish this was re-open cause restarting the port-forward every time the pod is restarted is annoying.
