### ISSUE TITLE
Flag bugs on kubectl expose

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#5981]
```
$ kubectl expose hostnames --port=80 --container-port=9376 --selector run-container=hostnames
unknown flag: --port
```

The actual problem is that I forgot the = after --selector.

So there are two bugs.  1) I should not need the =.  2) Wrong diagnostic

**Comment by deads2k** [comment]
See https://github.com/spf13/cobra/pull/79 for the first bug.

**Comment by eparis** [comment]
and https://github.com/spf13/cobra/pull/84 because i couldn't at first understand the fix to https://github.com/spf13/cobra/pull/79 and eventually realized I might be able to fix it by deleting code!

**Comment by deads2k** [comment]
I agree that spf13/cobra#84 is cleaner, but I don't know if cobra is mostly dead or not.   If we can't get the changes merged, carrying spf13/cobra#79 as an upstream patch is probably easier.

**Comment by eparis** [comment]
well, I can commit code to spf13/cobra as can brendan burns, so it doesn't have to be dead....

**Comment by kargakis** [comment]
This is not an issue anymore. @bgrant0607 @thockin

**Comment by bgrant0607** [comment]
Thanks @kargakis
