### ISSUE TITLE
Need proper fix for pkg/master timeout

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#59838]
/kind bug
/kind flake

**What happened**:
2 months ago the pkg/master test was reliably taking less the 60 seconds to complete.
It now reliably takes 90 seconds on decently powerful box and times out a 5 minute timeout on the CI boxes.
Please see #59685 and #59441.

As @mikedanese notes :-

The Validate calls to the vendored go-openapi library are which make the test slow:
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master_openapi_test.go#L91
We should probably do more perf and send a patch to upstream.

**What you expected to happen**:
Someone needs to fully investigate the fix the issue causing the significant slow down of this test.

**How to reproduce it (as minimally and precisely as possible)**:
Run the test and note how long it takes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jberkus** [comment]
Assigning appropriate priority based on description

@roycaihw have you made any progress on this issue?

/priority important-longterm
