### ISSUE TITLE
Node's providerID is wrong for azure vmss when using instance metadata

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#59855]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When useInstanceMetadata is set to true for vmss nodes, their providerID is wrong.

**What you expected to happen**:

Their providerID should be in format `
azure:///subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachineScaleSets/<scaleset-name>/virtualMachines/<instance-id>`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jberkus** [comment]
adding priority important-soon so that this issue can stay in 1.10.

Please update if incorrect.

\priority important-soon

**Comment by jberkus** [comment]
adding priority important-soon so that this issue can stay in 1.10. Please update if incorrect.

/priority important-soon
