### ISSUE TITLE
run hack/update-codegen.sh error

### ISSUE THREAD

**Issue by wackxu** [kubernetes/kubernetes#59856]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 kind bug

**What happened**:
whe I run `hack/update-codegen.sh`
```
make: Leaving directory '/root/xsw/src/k8s/kubernetes'
./hack/update-codegen.sh: line 66: INTERNAL_DIRS[@]: unbound variable
```

**What you expected to happen**:
run success

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sttts** [comment]
I tried k8s.io/sample-apiserver's hack/update-codegen.sh and it works fine. @wackxu please provide a minimal example reproducing the issue.

**Comment by wackxu** [comment]
@sttts Thanks for your help. It has been fixed by https://github.com/kubernetes/kubernetes/pull/59886. So we can close it.
