### ISSUE TITLE
Add option in restart policy to limit container restarts

### ISSUE THREAD

**Issue by ramato-procon** [kubernetes/kubernetes#59865]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
In some circumstances (e.g. OOMKilled) containers are restarted many times, if the restart policy is "Always". You can only decide to always "Fail" the pod or keep it running forever. 
**What you expected to happen**:
I would like to have an option to "Fail" the pod, after a configurable number of container restarts (maybe within a timeframe).
**How to reproduce it (as minimally and precisely as possible)**:
Pod with: Restart Policy "Always", Volume: Empty-Dir-Memory
Create a large file within the volume which exceeds the cgroup limit.
The pod will end up in a restart loop (I will create a separate bug Report for this).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by php-coder** [comment]
/sig node
@kubernetes/sig-node-feature-requests

**Comment by php-coder** [comment]
@ramato-procon No, I only marked it appropriately to pay attention.
