### ISSUE TITLE
Howto run kubernetes dashboard in background (not described)

### ISSUE THREAD

**Issue by mostworld77** [kubernetes/kubernetes#59864]
There is no information about, howto run kubelet proxy in background
or starting with systemstart (init script)

**Comment by liggitt** [comment]
`kubectl proxy` is not really intended to be run in the background, but if you wanted to, you could run it in the background like any other backgrounded process (e.g. `kubectl proxy &`)

/close

**Comment by amitkumarjain4u2u** [comment]
I had installed dashboard by following 

Below link:

https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

till step kubectl proxy i am getting results as expected but below URL is not accessible:

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#!/login

I have done all these steps on master.
my machine is an AWS machine.
Can anyone suggest what needs to be done for accessing above URL?

**Comment by rajaishwary** [comment]
@amitkumarjain4u2u Your aws server ip where pods are running will be different. 
So, you need to do kubectl port-forward to server's port which can be accessible as:

http://[host]:[port]/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#!/login

**Comment by mus-rachidi** [comment]
You can also use `nohup` if you want to ensure the process continues running even after the terminal is closed: 
`nohup kubectl proxy &`
