### ISSUE TITLE
Error message misleading with hostPath volumes under Windows

### ISSUE THREAD

**Issue by attilah** [kubernetes/kubernetes#59876]
/kind bug
/sig windows

**What happened**:

I tried to setup a volume mount under windows, but got a misleading error message.

volumeMounts part:
```
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
```

volumes part:

```
      volumes:
      - name: influxdb-storage
        hostPath:
          path: D:/influxdb
          type: DirectoryOrCreate
```

Error message on kubernetes dashboard was:

```
Error received from daemon, Invalid mode for /var/lib/influxdb
```

**What you expected to happen**:

Better error message to explain the problem better, since as turned out, not the ```volumeMounts``` part was wrong, but the ```hostPath.path``` was in the wrong format. As a kubernetes newbie I was searching for solutions for the ```volumeMounts``` part, but did not find anything...

After I modified it to ```/D/influxdb``` everything worked like a charm.

**How to reproduce it (as minimally and precisely as possible)**:

Create a kubernetes deployment under windows with a hostPath volume.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"20018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2
017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Microsoft Windows [Version 10.0.16299.214]
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by khenidak** [comment]
@JiangtianLi @andyzhangx @jdumars

**Comment by andyzhangx** [comment]
@attilah specify `/D/influxdb` will find `c:\D\influxdb` dir, if it does not exist, it will create a new dir as your specify `type: DirectoryOrCreate`
I think you wan to use `D:\influxdb` in hostPath, just use `path: D:\influxdb`

**Comment by attilah** [comment]
@andyzhangx D is my D drive, not a directory on C drive and that is what I want, and with the later specification Kubernetes correctly creates the directory if it does not exist on D drive.

**Comment by andyzhangx** [comment]
good to know, the file path format between linux and windows is a little different,
would you close this issue? thx.

**Comment by andyzhangx** [comment]
@attilah How do you get that error message? `Error received from daemon, Invalid mode for /var/lib/influxdb`, could you also run `kubectl describe po POD-NAME` and collect info?

**Comment by attilah** [comment]
I see that error in the Dashboard:

![image](https://user-images.githubusercontent.com/230432/36244693-1eed865e-11dc-11e8-8bc5-8b59869dae0b.png)

But also it present in the describe output:

```
Name:           influxdb-5df975b49d-qlprr
Namespace:      default
Node:           docker-for-desktop/192.168.65.3
Start Time:     Wed, 14 Feb 2018 23:06:34 -0800
Labels:         app=fooapp
                component=influxdb
                feature=monitoring
                pod-template-hash=1895316058
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"influxdb-5df975b49d","uid":"c19a2657-121e-11e8-ab29-00155d01380f...
Status:         Pending
IP:             10.1.0.110
Controlled By:  ReplicaSet/influxdb-5df975b49d
Containers:
  influxdb:
    Container ID:   
    Image:          influxdb:1.4.3-alpine
    Image ID:       
    Port:           8086/TCP
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:
      INFLUXDB_HTTP_AUTH_ENABLED:    <set to the key 'Monitoring_InfluxDb__HttpAuthEnabled' of config map 'externalconfig'>    Optional: false
      INFLUXDB_DB:                   <set to the key 'Monitoring_InfluxDb__DatabaseName' of config map 'externalconfig'>       Optional: false
      INFLUXDB_ADMIN_USER:           <set to the key 'Monitoring_InfluxDb__AdminUser' of config map 'externalconfig'>          Optional: false
      INFLUXDB_ADMIN_PASSWORD:       <set to the key 'Monitoring_InfluxDb__AdminPassword' of config map 'externalconfig'>      Optional: false
      INFLUXDB_USER:                 <set to the key 'Monitoring_InfluxDb__User' of config map 'externalconfig'>               Optional: false
      INFLUXDB_USER_PASSWORD:        <set to the key 'Monitoring_InfluxDb__UserPassword' of config map 'externalconfig'>       Optional: false
      INFLUXDB_READ_USER:            <set to the key 'Monitoring_InfluxDb__ReadUser' of config map 'externalconfig'>           Optional: false
      INFLUXDB_READ_USER_PASSWORD:   <set to the key 'Monitoring_InfluxDb__ReadUserPassword' of config map 'externalconfig'>   Optional: false
      INFLUXDB_WRITE_USER:           <set to the key 'Monitoring_InfluxDb__WriteUser' of config map 'externalconfig'>          Optional: false
      INFLUXDB_WRITE_USER_PASSWORD:  <set to the key 'Monitoring_InfluxDb__WriteUserPassword' of config map 'externalconfig'>  Optional: false
    Mounts:
      /var/lib/influxdb from influxdb-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-764z4 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  influxdb-storage:
    Type:          HostPath (bare host directory volume)
    Path:          W:\fooapp\influxdb
    HostPathType:  DirectoryOrCreate
  default-token-764z4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-764z4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                         Message
  ----     ------                 ----             ----                         -------
  Normal   Scheduled              1m               default-scheduler            Successfully assigned influxdb-5df975b49d-qlprr to docker-for-desktop
  Normal   SuccessfulMountVolume  1m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "influxdb-storage"
  Normal   SuccessfulMountVolume  1m               kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-764z4"
  Normal   Pulled                 2s (x8 over 1m)  kubelet, docker-for-desktop  Container image "influxdb:1.4.3-alpine" already present on machine
  Warning  Failed                 2s (x8 over 1m)  kubelet, docker-for-desktop  Error: Error response from daemon: invalid mode: /var/lib/influxdb
```

"Fun" fact, that I don't know what is happening with the hostPath.path, but these values are valid AND working:
- /W/fooapp/influxdb
- //W/fooapp/influxdb
- /////W/fooapp/influxdb

Hope this helps.

**Comment by jdumars** [comment]
@attilah just to limit variables, can you please downgrade your client to 1.8.x.  We do support version skew, but that would at least rule it out.  Please post results here after that. Thanks!

**Comment by attilah** [comment]
@jdumars how can I do that? I installed the docker for windows installer, not separate packages ;-)

**Comment by jdumars** [comment]
Oh... yikes I am not sure.  :) Despite working for Microsoft, I use a Mac.  Anyone have an idea here?

**Comment by andyzhangx** [comment]
@attilah so here `W:\` is an existing drive, right? It's an error from docker daemon: `Error: Error response from daemon: invalid mode: /var/lib/influxdb`, 
to narrow down this issue, could you try to run 
`docker run -d -v W:\fooapp\influxdb:c:\var\lib\influxdb influxdb:1.4.3-alpine` 
in your Windows agent.
According to this [stackoverflow issue](https://stackoverflow.com/questions/47091139/docker-mount-project-error-response-from-daemon-on-windows-10), it could be a [Windows shared drives config](https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/) problem

I also tried v1.8.2 on a Windows cluster by acs-engine, it won't have such issue.

**Comment by attilah** [comment]
@andyzhangx  in your sample cmd the ```c:\var``` does not make sense, no drives in Linux AFAIK. 

However all of these are working:
```
docker run -d -v /W/foobar:/var/lib/influxdb influxdb:1.4.3-alpine
docker run -d -v W:/foobar:/var/lib/influxdb influxdb:1.4.3-alpine
docker run -d -v W:\foobar:/var/lib/influxdb influxdb:1.4.3-alpine
docker run -d -v /////W/foobar:/var/lib/influxdb influxdb:1.4.3-alpine
```

The last one is weird for sure. I think that the left side of a local volume should be validated against the host os's path requirements BUT helpers (like forward slashes) should be allowed. (but not //////).

**Comment by robrich** [comment]
+1.  Just hit this issue with a Windows host running a Linux pod on Docker for Windows.  Changing from `path: C:/foo/bar` to `path: /C/foo/bar` solved it.  Sadly, https://kubernetes.io/docs/getting-started-guides/windows/#volumes suggests it could have been `path: "C:\\foo\\bar"` which I found didn't work.  The feature works correctly, but the error message is very misleading.  I'm glad I found this as the top result when searching for `kubernetes hostPath Error: Error response from daemon: invalid mode:`.

**Comment by khenidak** [comment]
@PatrickLang + @andyzhangx  the bot closed this. But is it *really* closed?

**Comment by andyzhangx** [comment]
I will take a look when I have bandwidth...

**Comment by juniormayhe** [comment]
This one was closed by the bot again. Do we have another issue opened related to hostPath in Windows? I have tried in git bash and command prompt all combinations:

  hostPath:
    path: "/D/tmp/sqldata"
or
  hostPath:
    path: "D:\\tmp\\sqldata"

but none worked. The message is always the same:

```
c:\tmp\sqldata>kubectl logs mssql
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
Your master database file is owned by mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2020-04-23 18:55:56.08 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2020-04-23 18:55:56.17 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2020-04-23 18:55:56.17 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2020-04-23 18:55:56.19 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2020-04-23 18:55:56.33 Server      Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)
        Mar 14 2020 16:10:35
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 18.04.4 LTS) <X64>
2020-04-23 18:55:56.33 Server      UTC adjustment: 0:00
2020-04-23 18:55:56.34 Server      (c) Microsoft Corporation.
2020-04-23 18:55:56.34 Server      All rights reserved.
2020-04-23 18:55:56.34 Server      Server process ID is 36.
2020-04-23 18:55:56.34 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2020-04-23 18:55:56.34 Server      Registry startup parameters:
         -d /var/opt/mssql/data/master.mdf
         -l /var/opt/mssql/data/mastlog.ldf
         -e /var/opt/mssql/log/errorlog
2020-04-23 18:55:56.34 Server      Error: 17113, Severity: 16, State: 1.
2020-04-23 18:55:56.34 Server      Error 87(The parameter is incorrect.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.
```

My kubectl version
```
D:\tmp\sqldata>kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Docker Desktop for Windows is 2.2.05

Did anyone manage to make hostPath work in Windows environment for setting up a permanent volume?

**Comment by unstableunicorn** [comment]
@juniormayhe 
We came across this after updating to docker-desktop 2.3.0.2. [issue#1703](https://github.com/docker/for-win/issues/1703#issuecomment-366701358) finally had the answer for us:
Instead of:
```
/C/path/to/file
```
It works with:
```
/host_mnt/c/path/to/file
```
I can not find any official information on this but I hope this helps someone else who comes across this issue.

**Comment by hadrian625** [comment]
@unstableunicorn 
You are a life saver. I had my setup work with hostPath in format /C/path/to/file. After a Docker update it suddenly didn't work. You solution is now the way hostPath volume mount works for Windows.
Thanks again.

**Comment by aalsabag** [comment]
Thank you @unstableunicorn . ```/host_mnt/c/path/to/file`` that did the trick!

**Comment by Joelbear5** [comment]
Breaking changes are not cool! But thanks for this!

**Comment by xanthoc** [comment]
> @attilah specify `/D/influxdb` will find `c:\D\influxdb` dir, if it does not exist, it will create a new dir as your specify `type: DirectoryOrCreate`
> I think you wan to use `D:\influxdb` in hostPath, right?, just use `path: 'D:\influxdb'`

I just do as below:
path: /some/funny/loc
type: DirectoryOrCreate
Everything looks fine; I mean I got data consistency. But I can't locate /some/funny/loc in my host. Where can I locate the '/some/funny/loc'?

**Comment by MiracleJy** [comment]
@xanthoc
Try `/mnt/wsl/mnt/some/funny/loc`.

k8s version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Filesystem architecture is as follows：
```
root@DESKTOP-06QSKHT:/mnt# tree -L 2 -d
.
├── c
│   ├── xxx
├── d
│   ├── xxx
└── wsl
    ├── docker-desktop
    ├── docker-desktop-bind-mounts
    ├── docker-desktop-data
    └── mnt
```

**Comment by sguidos** [comment]
I came across this post after updating my Docker Desktop for Windows to version 3.3 using WSL2 integration.  After several more hours of research, I came across the answer described here:  https://stackoverflow.com/questions/62812948/volume-mounts-not-working-kubernetes-and-wsl-2-and-docker/63524931#63524931  

What used to work as:

```
/C/path/to/file
```
Now works as:
```
/run/desktop/mnt/host/c/path/to/file
```
I hope this helps someone else who comes across this issue.

**Comment by sgd2z** [comment]
Thanks @sguidos - That saved me some headache.

**Comment by fmiqbal** [comment]
> ```
> /run/desktop/mnt/host/c/path/to/file
> ```

Ok this works, thank you so much. but, where is this mount file exactly? I dont find any on my distro (`Arch linux`) or `docker-desktop` or `docker-desktop-data` entry?

**Comment by beaudryj** [comment]
what.... a .... Joke......... 

Thank you! 


> I came across this post after updating my Docker Desktop for Windows to version 3.3 using WSL2 integration. After several more hours of research, I came across the answer described here: https://stackoverflow.com/questions/62812948/volume-mounts-not-working-kubernetes-and-wsl-2-and-docker/63524931#63524931
> 
> What used to work as:
> 
> ```
> /C/path/to/file
> ```
> 
> Now works as:
> 
> ```
> /run/desktop/mnt/host/c/path/to/file
> ```
> 
> I hope this helps someone else who comes across this issue.

**Comment by ahoehma** [comment]
Works only with "/run/desktop/mnt/host/" wtf :P

**Comment by jingxu97** [comment]
@andyzhangx is there something we should investigate?

/reopen

**Comment by sguidos** [comment]
> > ```
> > /run/desktop/mnt/host/c/path/to/file
> > ```
> 
> Ok this works, thank you so much. but, where is this mount file exactly? I dont find any on my distro (`Arch linux`) or `docker-desktop` or `docker-desktop-data` entry?

The folder mount for `/run/desktop/mnt/host/c` does not exist on the distro you installed in WSL2 - on that WSL2 distro, the mount point to your C:\ drive is the more obvious `/mnt/c`.

Realize that Kubernetes and Docker are **_not_** installed in your installed WSL2 distro.  Instead, Docker Desktop for Windows creates its own WSL2 VM called `docker-desktop` and installs Docker and Kubernetes on that VM.  Then Docker Desktop for Windows installs the `docker` and `kubectl` CLIs on your WSL2 distro (and also on your Windows machine) and configures them all to point to the Docker and Kubernetes instances it created on the `docker-desktop` VM.  This `docker-desktop` VM is hosting Docker and Kubernetes and also contains the `/run/desktop/mnt/host/c` mount point to your Windows C:\ drive and that can be used by your containers to persist data.

You can remote into the `docker-desktop` VM and see the `/run/desktop/mnt/host/c` mount point and folder structure by following the instructions (and discussion) at https://stackoverflow.com/a/62117039/11057678:
```
docker run -it --rm --privileged --pid=host justincormack/nsenter1
```

**Comment by RaynorGu** [comment]
How can I mount path in wsl(/home/user/project) into the k8s pod?
