### ISSUE TITLE
Etcd and SSL

### ISSUE THREAD

**Issue by cnaize** [kubernetes/kubernetes#5987]
Hello!
I have a question about `etcd` and `ssl`.

As it described here https://github.com/coreos/etcd/blob/master/Documentation/security.md, with `flannel` we can do something like this:
```none
/usr/bin/flanneld -etcd-endpoints=https://10.10.10.10:1010 -etcd-prefix=/coreos.com/network -etcd-cafile=ca.crt -etcd-certfile=client.crt -etcd-keyfile=client.key
```
How to do something like this with `kubernetes`?

I see `TODO: authorization, authentication` here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/security.md

Is it in plans? How to protect `etcd`?

**Comment by dchen1107** [comment]
cc/ @erictune

**Comment by roberthbailey** [comment]
We don't currently run flannel on GCE and as far as I know no one is actively working on this at the moment. The etcd instance that is used by the master will be protected by only being available on localhost (#5962) so we aren't currently concerned with making the connection to that etcd instance use https.

**Comment by cnaize** [comment]
And how we supposed to secure `etcd`?
`kubelet` listening `etcd` by `http`, everyone can delete all data from it.
And as I understood, our `pod`s can corrupt `etcd`'s data from inside too.

**Comment by derekwaynecarr** [comment]
cc/ @liggitt

**Comment by erictune** [comment]
If your kubelet is listening to etcd, then you are using an out-of-date cluster setup.
Which getting-started-guide did you use, and when?
New clusters have kubelet talking over SSL to the master.  Nothing uses etcd.

**Comment by erictune** [comment]
The GCE distro has the client port using 127.0.0.1.  It has no peer port. 

Some other distros have unprotected client and/or peer ports.

I filed #6067 about bringing the other distros up to that standard.

**Comment by erictune** [comment]
Appologies @cnaize 
I was reading the salt config, which is confusing, and led me to think we were using 127.0.0.1.
But you are quite right, we are using public IP.

**Comment by roberthbailey** [comment]
The etcd that is used by the master components is considered an implementation detail of the cluster and in most distributions is restricted to access on localhost. I'm going to mark this issue as obsolete but please reopen if you still have an interest in trying to secure etcd in your configuration.
