### ISSUE TITLE
Service controller has race at startup which causes UpdateLoadBalancer to not be called

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#59900]
/kind bug
/sig network
/assign

**What happened**:
Result: 
GCE loadbalancer had outdated target pools because the service controller failed to call UpdateLoadBalancer() for all services.

Why:
The node sync loop has the potential to run before any services of type loadbalancer are synced at service controller startup. The node sync loop gets its list of services from a cache/map - not the service lister. However, this map is populated at service sync...
Since GCE does not assert target pool membership in service sync (only node sync), the target pool was not updated until another node change is made.

```
2018-01-23 11:36:41.000 UTC  Starting service controller
2018-01-23 11:36:54.000 UTC  Caches are synced for service account controller
2018-01-23 11:36:54.000 UTC  Detected change in list of current cluster nodes. New node set: [A B C]
2018-01-23 11:36:54.000 UTC  Successfully updated 0 out of 0 load balancers to direct traffic to the updated set of nodes
```

Acceptable Fixes:
1. GCE updates target pools during EnsureLoadBalancer(). This has already been completed in #58368.
2. Node sync retrieves services from serviceLister instead of cache. Being done in #54569.

We can cherrypick the first fix to earlier versions, but if other clouds are affected by this, the second fix would be better.

**Comment by jhorwit2** [comment]
@nicksardo i'd hold off on this because i'm deleting all the cache logic in the finalizer PR https://github.com/kubernetes/kubernetes/pull/54569

**Comment by nicksardo** [comment]
> @nicksardo i'd hold off on this because i'm deleting all the cache logic in the finalizer PR #54569 and I moved to the lister.

Well aware of that - your PR is linked in the bug description.  However, the problem will still exist in pre-1.10 versions.

**Comment by bowei** [comment]
What would the backport targets (1.8, 1.9?)

**Comment by nicksardo** [comment]
Yes

**Comment by nicksardo** [comment]
/close

Fix 1 was cherrypicked to supported versions. Service refactoring still hasn't been merged yet, but it's no longer relevant for this bug.
