### ISSUE TITLE
kubectl logs should support log rotation for CRI container runtime.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#59902]
Today no matter for docker or other CRI container runtime, `kubectl logs` is **NOT** able to:
1) Trace back to back to rotated logs.
2) Detect current log file is rotated and start monitoring new log file.

Previously we don't support it, because docker doesn't follow CRI log format, and `kubectl logs` doesn't understand how docker rotate container logs.

However, after https://github.com/kubernetes/kubernetes/pull/59898, kubelet will be responsible for rotating container logs for CRI container runtime. And `kubectl logs` can know potentially support log rotation, because kubelet has all the information needed.

We can do this after https://github.com/kubernetes/kubernetes/pull/59898 lands.

@kubernetes/sig-node-feature-requests 
/kind feature

**Comment by ShahNewazKhan** [comment]
Any updates on this front?

**Comment by louygan** [comment]
which release will include this change?

**Comment by ehashman** [comment]
/help

Now that CRIContainerLogRotation is GA, we can potentially add this as a follow-on feature.

Due to the potential for version skew issues (https://github.com/kubernetes/enhancements/pull/2418#issuecomment-776075487) this will probably need a design doc or perhaps a small KEP.

**Comment by vaibhav2107** [comment]
Hi @Random-Liu,
Is this issue active to work on.

**Comment by dharmit** [comment]
Hi @Random-Liu @ehashman @derekwaynecarr, I'd like to work on this. I haven't worked on k8s code base except when using it as a library in the other project I mostly work on. But I will be able to pick things up. Can I assign?

/assign

**Comment by dharmit** [comment]
Sincere apologies for not having looked into this yet. Unassigning so that someone who has bandwidth can pick it up.

Sorry folks. :(

/unassign

**Comment by SaberStrat** [comment]
I take it it's not (just) that `kubectl` that can't handle rotated logs, it's the pods API?

**Comment by wu0407** [comment]
https://github.com/containerd/containerd/issues/8872

**Comment by zmedico** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/115702?

**Comment by xyz-li** [comment]
> Fixed by #115702?

I think this has been fixed by #115702.

**Comment by vaibhav2107** [comment]
As per the [comment](https://github.com/kubernetes/kubernetes/issues/59902#issuecomment-2272564093) we can close this issue
