### ISSUE TITLE
Implement InstanceShutdownByProviderID to Openstack.

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#59926]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE

/kind feature

Implement InstanceShutdownByProviderID to Openstack. InstanceShutdownByProviderID returns true if the instance is in safe state to detach volumes. Note: if instance is deleted we should not return error.

**Comment by dims** [comment]
@zetaab can we close this now? is there work to be done?
