### ISSUE TITLE
Ubuntu 16.04 LTS - Unable to locate package kubelet, kubeadm, kubectl

### ISSUE THREAD

**Issue by monique77** [kubernetes/kubernetes#59959]
Hi,

First, sorry my english is bad.

Dear,
I am using ubuntu 16.04 LTS, following the observations of the https://kubernetes.io/docs/setup/independent/install-kubeadm/

But in the step: apt-get install -y kubelet kubeadm kubectl     error appears:
apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl

Before i execute apt-get update and not erros, but after with command above not sucess.

root@niki-Inspiron-5458:/etc/apt/sources.list.d# ls
getdeb.list  getdeb.list.distUpgrade  kubernetes.list
root@niki-Inspiron-5458:/etc/apt/sources.list.d# cat kubernetes.list 
deb http://apt.kubernetes.io/ kubernetes-xenial main
root@niki-Inspiron-5458:/etc/apt/sources.list.d# 

Look my environment;

root@niki-Inspiron-5458:/etc/apt/sources.list.d# uname -a
Linux niki-Inspiron-5458 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:14 UTC 2018 i686 i686 i686 GNU/Linux

root@niki-Inspiron-5458:/etc/apt/sources.list.d# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

root@niki-Inspiron-5458:/etc/apt/sources.list.d# cat /proc/version
Linux version 4.4.0-112-generic (buildd@lgw01-amd64-017) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #135-Ubuntu SMP Fri Jan 19 11:48:14 UTC 2018

Please can help me? Tks so much. Sorry my english, i m Brazilian.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: i dont know
- OS (e.g. from /etc/os-release): answer above
- Kernel (e.g. `uname -a`): answer above
- Install tools: nothing
- Others: nothing

**Comment by monique77** [comment]
Hi, rdrgporto

Tks you response

Your steps above, i execute, but continue with erros; i add key, repository
root@niki-Inspiron-5458:/opt/openconnect# cat /etc/apt/sources.list.d/kubernetes.list 
deb http://apt.kubernetes.io/ kubernetes-xenial main

apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl

Any idea?

**Comment by monique77** [comment]
I forgot to speak, but my ubuntu is 32 bit, does it have to be 64bit?

**Comment by monique77** [comment]
Hi, rdrgporto how are you?

I installed ubuntu 64Bits and it worked, 

Tks so much

**Comment by monique77** [comment]
Now, i going to test with Oracle Linux.

**Comment by rdrgporto** [comment]
Hi @monique77,

**Docker** works only on **64bit** platform, so that, it is necessary to install **Kubernetes** on 64 bits.

Regards :vulcan_salute:

**Comment by monique77** [comment]
Hi, rdrgporto

Obrigado/ tks so much

**Comment by ashishkel** [comment]
Thanks to you rdrgporto

**Comment by Vickey-Wu** [comment]
why i can't add apt-key?
 `curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

**Comment by rdrgporto** [comment]
Hi @Vickey-Wu,

You can try it by using **wget**:

`wget https://packages.cloud.google.com/apt/doc/apt-key.gpg`


If you have some issue, maybe it is due to ISP (Internet service provider).

Regards :vulcan_salute:

**Comment by Vickey-Wu** [comment]
thank you @rdrgporto , because of  China special network, we can use google directly, but finally i get it from USTC(University of Science and Technology of China) open source software mirror, thanks for your  help.

**Comment by rdrgporto** [comment]
Hi @shivamchandra4,

Maybe you need to install **vim** in order to edit/create **kubernetes.list** file:

```
sudo apt-get update
sudo apt-get install vim
```

Moreover you could try **vi** or **nano**, that is:

```
sudo vi /etc/apt/sources.list.d/kubernetes.list
sudo nano /etc/apt/sources.list.d/kubernetes.list
```

Once you have some of these programs installed, you have to copy 
`deb http://apt.kubernetes.io/ kubernetes-xenial main ` and paste into **kubernetes.list** and make an update of Ubuntu repositories:

```
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni
```
Regards :vulcan_salute:

**Comment by shivamchandra3** [comment]
Hi @rdrgporto ,
Thanks for replying to my query.
I tried the above mentioned steps by you.

These 2 worked properly:
**sudo apt-get update
sudo apt-get install vim**

But when I tried : sudo vi /etc/apt/sources.list.d/kubernetes.list , I got the page stating "deb http://apt.kubernetes.io/ kubernetes-xenial main


"/etc/apt/sources.list.d/kubernetes.list" 1L, 53C "

I was not sure what to do over here. So, I ran the next 2 commands mentioned: 
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni

After this to be sure that kubectl is installed on my laptop, I ran **kubectl version**.
The response which I got was : Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fversion%3Ftimeout%3D32s'/><script>window.location.replace('/login?from=%2Fversion%3Ftimeout%3D32s');</script></head><body style='background-color:white; color:white;'>


Authentication required


</body></html>



Kindly suggest if I did something wrong in this process. I would rectify the same.

Regards,
Shivam Chandra

**Comment by rdrgporto** [comment]
Hi @shivamchandra3,

You have to run **kubeadm**:

`sudo kubeadm init `

Regards :vulcan_salute:

**Comment by sanjeevshar** [comment]
Hi @rdrgporto ,

I am having trouble installing Kubernetes. I have followed the instructions but   "apt-get update" reports error due to which "apt-get install" also fails. It may have something to do with corporate firewall but I do not know what to ask IT guys to get around the problem. 

# apt-get update
.......
.......
Reading package lists... Done
W: The repository 'http://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/main/binary-amd64/Packages  403  Proxy Unacknowledged
E: Some index files failed to download. They have been ignored, or old ones used instead.


# apt-get install -y kubelet kubeadm kubectl kubernetes-cni
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl
E: Unable to locate package kubernetes-cni

**Comment by rdrgporto** [comment]
Hi @sanjeevshar,

Did you add GPG key?

`curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -`

You could try too:

`sudo apt-get update --allow-unauthenticated`

Regards :vulcan_salute:

**Comment by gulnadaf** [comment]
Hi,
I am having ~14.04.1-Ubuntu .. 64bit system. followed all steps mentioned above but still getting exception. Kindly suggest.
"E: Unable to locate package kubelet"

Please see the screen shot of 
![image](https://user-images.githubusercontent.com/44694713/50513069-77685880-0abb-11e9-81bc-6b63e389757d.png)

**Comment by rdrgporto** [comment]
Hi @gulnadaf,

It is due to **Ubuntu version**. You are using **Ubuntu 14.04**. As far as I know, **Kubernetes** works from **Ubuntu 16.04**.

Regards :vulcan_salute:

**Comment by gulnadaf** [comment]
Thanks Rodrigo for quick revert. I was able to install "kubectl"
sudo apt-get install -y kubectl on Ubuntu 14.04.

So, upgrading Ubuntu version is the only option in hand?

**Comment by rdrgporto** [comment]
Hi @gulnadaf,

I have not worked on **Ubuntu 14.04**. I work on **Ubuntu 16.04** and **18.04**, so that, I am not quite sure that **Kubernetes** works on **Ubuntu 14.04**.

Regards :vulcan_salute:

**Comment by harshneelmore** [comment]
Hi,
I am running Ubuntu 18.04 with docker v 18.09.3, I have followed the steps mentioned above but still see the issue "E: Unable to locate package kubelet"

Following is are the steps followed - 
root@ubuntu:~# apt-get update && apt-get install -y apt-transport-https curl
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                             
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                         
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                       
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease                                                                        
Hit:6 https://packages.cloud.google.com/apt kubernetes-yakkety InRelease                                         
Reading package lists... Done                                
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.6).
apt-transport-https is already the newest version (1.6.8).
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
root@ubuntu:~# curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
OK
root@ubuntu:~# cat /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-yakkety main
root@ubuntu:~# apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "kubeadm", but there is a snap with that name.
Try "snap install kubeadm"


No apt package "kubectl", but there is a snap with that name.
Try "snap install kubectl"


No apt package "kubelet", but there is a snap with that name.
Try "snap install kubelet"

E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl


I need to install a specific version of kubelet, kubeadm and kubectl v=1.13.

**Comment by rdrgporto** [comment]
Hi, @harshneelmore 

Would do you mind to show  /etc/apt/sources.list.d/kubernetes.list file?

Thanks in advance,

Rodrigo

**Comment by harshneelmore** [comment]
Contents from kubernetes.list file

root@ubuntu:~# cat /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-yakkety main
root@ubuntu:~#

**Comment by harshneelmore** [comment]
Contents from kubernetes.list file

```
root@ubuntu:# cat /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-yakkety main
root@ubuntu:#
```

**Comment by rdrgporto** [comment]
Hi, @harshneelmore 

You should try with:

```
sudo vim /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
```

Regards

**Comment by harshneelmore** [comment]
Should I do this even if I am running Ubuntu 18.04(bionic) and not 16.04(xenial)?

**Comment by rdrgporto** [comment]
Hi,

For the moment, it is necessary to use Xenial repository, although you use Bionic.

You can find more information: https://kubernetes.io/docs/setup/independent/install-kubeadm/

Regards

**Comment by moluzhui** [comment]
> Hi,
> 
> For the moment, it is necessary to use Xenial repository, although you use Bionic.
> 
> You can find more information: https://kubernetes.io/docs/setup/independent/install-kubeadm/
> 
> Regards

Hi，I am running Ubuntu 16.04 with docker v 18.09.3.。I installed k8s according to the installation information of the website
`apt-get update && apt-get install -y apt-transport-https curl 
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -  
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update  
apt-get install -y kubelet kubeadm kubectl  
apt-mark hold kubelet kubeadm kubectl  
`

When I run the second command, I get the following error
`curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
gpg: no valid OpenPGP data found.
`
But I can download apt-key.gpg by chrome.
So I use xftp transmit it to Ubuntu server and 
`apt-key add apt-key.gpg
OK`
When I run the fouth command, update error
`apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease                 
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                          
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                        
Err:4 https://apt.kubernetes.io kubernetes-xenial InRelease                                                                                                                               
  Failed to connect to packages.cloud.google.com port 443: Connection refused
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:6 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]
Err:6 https://download.docker.com/linux/ubuntu xenial InRelease
  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
Fetched 216 kB in 2min 37s (1,372 B/s)
Reading package lists... Done
W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/xenial/InRelease  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Failed to connect to packages.cloud.google.com port 443: Connection refused
W: Some index files failed to download. They have been ignored, or old ones used instead.`

Please tell me what I should do to solve the problem. Thank you!

**Comment by rdrgporto** [comment]
Hi, @moluzhui 

I think that this kind of issue is related to proxy. Are the machine behind a proxy?

Regards

**Comment by moluzhui** [comment]
> Hi, @moluzhui
> 
> I think that this kind of issue is related to proxy. Are the machine behind a proxy?
> 
> Regards

I'm a student in China，But I use vnp to install it. Is there something wrong with my vpn?

**Comment by rdrgporto** [comment]
Hi, @moluzhui

You should try on a machine without VPN in order to be sure.

Regards

**Comment by moluzhui** [comment]
> Hi, @moluzhui
> 
> You should try on a machine without VPN in order to be sure.
> 
> Regards

it's also failed
```
Err:16 https://apt.kubernetes.io kubernetes-xenial InRelease                                                                                                                              
  Failed to connect to packages.cloud.google.com port 443: Connection refused
```

**Comment by issahamieh** [comment]
hello, @rdrgporto 
i will install this command but is not download it why?
sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni
Reading package lists... Done
Building dependency tree       
Reading state information... Done

No apt package "kubeadm", but there is a snap with that name.
Try "snap install kubeadm"


No apt package "kubectl", but there is a snap with that name.
Try "snap install kubectl"


No apt package "kubelet", but there is a snap with that name.
Try "snap install kubelet"

E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl
E: Unable to locate package kubernetes-cni

**Comment by rdrgporto** [comment]
Hi @issahamieh,

Have you added Kubernetes repository?

```
apt-get update && apt-get install -y apt-transport-https curl  
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -  
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update  
```

Regards

**Comment by kserge2001** [comment]
Hi  @rdrgporto ,

thank you for all your help 

I am running  Ubuntu 18.04.3 LTS
This is my reposittory file

# cat  /etc/apt/sources.list.d/kubernetes.list
deb https://apt-kubernetes.io/ kubernetes-xenial main

donwloaded the gpg key 

19:~# curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg |apt-key add -
OK
but having below issue 

:~# apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Err:4 https://apt-kubernetes.io kubernetes-xenial InRelease
  Could not resolve 'apt-kubernetes.io'
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 88.7 kB in 0s (187 kB/s)
Reading package lists... Done
W: Failed to fetch https://apt-kubernetes.io/dists/kubernetes-xenial/InRelease  Could not resolve 'apt-kubernetes.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by rdrgporto** [comment]
Hi @kserge2001,

```
sudo -i
apt-get update && apt-get install -y apt-transport-https curl  
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -  
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update  | grep kubernetes
```

Example:

```
root@rdrg:~# apt-get update | grep kubernetes
Obj:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
```

Regards

**Comment by redeagle84** [comment]
I was getting, for another package the error: _No apt package "kubectl", but there is a snap with that name._

It can be related with timezone too as you can see here : https://askubuntu.com/questions/1061675/apt-package-update-is-failing-for-ubuntu-18-04-lts/1061678#1061678

**Comment by renukamanavalan** [comment]
Installer per directions [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) in debian version 10.

Upon updating `/etc/apt/sources.list.d/kubernetes.list`, "`sudo -E apt-get update`" fails as below.
Likely it is some restrictions on host. Can you please suggest, how do I fix?

```
remanava@CO4PHY070071101:/etc/apt/apt.conf.d$ sudo -E apt-get update
Err:1 https://apt.kubernetes.io kubernetes-xenial InRelease
  Reading from proxy failed - read (115: Operation now in progress) [IP: 13.66.223.165 3142]
Hit:2 http://debian-archive.trafficmanager.net/debian buster InRelease                              
Hit:3 http://debian-archive.trafficmanager.net/debian-security buster/updates InRelease             
Hit:4 https://apt-mo.trafficmanager.net/repos/aplinux-prod xenial InRelease                         
Hit:5 http://debian-archive.trafficmanager.net/debian buster-updates InRelease                      
Hit:6 https://apt-mo.trafficmanager.net/repos/azurecore trusty InRelease
Hit:7 http://debian-archive.trafficmanager.net/debian buster-backports InRelease
Hit:8 https://apt-mo.trafficmanager.net/repos/azurecore bionic InRelease
Reading package lists... Done
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Reading from proxy failed - read (115: Operation now in progress) [IP: 13.66.223.165 3142]
W: Some index files failed to download. They have been ignored, or old ones used instead.
remanava@CO4PHY070071101:/etc/apt/apt.conf.d$ 
```

**Comment by rdrgporto** [comment]
> Installer per directions [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) in debian version 10.
> 
> Upon updating `/etc/apt/sources.list.d/kubernetes.list`, "`sudo -E apt-get update`" fails as below.
> Likely it is some restrictions on host. Can you please suggest, how do I fix?
> 
> ```
> remanava@CO4PHY070071101:/etc/apt/apt.conf.d$ sudo -E apt-get update
> Err:1 https://apt.kubernetes.io kubernetes-xenial InRelease
>   Reading from proxy failed - read (115: Operation now in progress) [IP: 13.66.223.165 3142]
> Hit:2 http://debian-archive.trafficmanager.net/debian buster InRelease                              
> Hit:3 http://debian-archive.trafficmanager.net/debian-security buster/updates InRelease             
> Hit:4 https://apt-mo.trafficmanager.net/repos/aplinux-prod xenial InRelease                         
> Hit:5 http://debian-archive.trafficmanager.net/debian buster-updates InRelease                      
> Hit:6 https://apt-mo.trafficmanager.net/repos/azurecore trusty InRelease
> Hit:7 http://debian-archive.trafficmanager.net/debian buster-backports InRelease
> Hit:8 https://apt-mo.trafficmanager.net/repos/azurecore bionic InRelease
> Reading package lists... Done
> W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Reading from proxy failed - read (115: Operation now in progress) [IP: 13.66.223.165 3142]
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> remanava@CO4PHY070071101:/etc/apt/apt.conf.d$ 
> ```

Hi, @renukamanavalan 

I think that this kind of issue is related to proxy. Is the machine behind a proxy?

Regards

**Comment by renukamanavalan** [comment]
I have two different machines using same as http & https proxy. But the proxy mentioned in spew is an external one. Yet I added it in apt.conf. This crossed this hurdle. 
Then it failed with "`E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.`"
So I ran as "`sudo -E apt-get -o Acquire::AllowInsecureRepositories=true  -o Acquire::AllowDowngradeToInsecureRepositories=true -o APT::Get::AllowUnauthenticated=true update`"
It passed the last hurdle, but failed as below.
```
E: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/main/binary-amd64/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 13.66.223.165 3142]
E: Failed to fetch https://apt-mo.trafficmanager.net/repos/aplinux-prod/dists/xenial/main/binary-amd64/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 13.66.223.165 3142]
E: Failed to fetch https://apt-mo.trafficmanager.net/repos/azurecore/dists/trusty/main/binary-amd64/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 13.66.223.165 3142]
E: Failed to fetch https://apt-mo.trafficmanager.net/repos/azurecore/dists/bionic/main/binary-amd64/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 13.66.223.165 3142]

```
Any tips for me?

```
remanava@CO4PHY070071101:/etc/apt/apt.conf.d$ cat /etc/apt/apt.conf.d/01ubuntu 
Acquire::http::proxy "http://13.66.223.165:3142/";
Acquire::ftp::proxy "ftp://13.66.223.165:3142/";
Acquire::https::proxy "https://13.66.223.165:3142/";

```

**Comment by Hanzy1996** [comment]
> > Hi, @moluzhui
> > You should try on a machine without VPN in order to be sure.
> > Regards
> 
> it's also failed
> 
> ```
> Err:16 https://apt.kubernetes.io kubernetes-xenial InRelease                                                                                                                              
>   Failed to connect to packages.cloud.google.com port 443: Connection refused
> ```
I have the same problem. Have you solved this problem?

**Comment by yevvievvy** [comment]
> Acquire::http::proxy "http://13.66.223.165:3142/";
> Acquire::ftp::proxy "ftp://13.66.223.165:3142/";
> Acquire::https::proxy "https://13.66.223.165:3142/";

Hi Renuka, Did you solve the issue?

**Comment by renukamanavalan** [comment]
Hi @yevvievvy , Thanks for checking. My problem is solved. Being a while back and in the midst of many active issues, I can't completely recall. But I guess I used /etc/apt/apt.conf.d/02proxy to help solve.
