### ISSUE TITLE
Should use predicates.XXX consts to instead of strings

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#59951]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
 /kind bug

**What happened**:

Per discussion in https://github.com/kubernetes/kubernetes/pull/59335/files#r168351460

**What you expected to happen**:

Use `predicates.XXX` consts to instead of strings

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yastij** [comment]
@resouer - we need an issue to track usage of strings instead of consts in the scheduler, as it is very easy to break something bc of this. can we use this issue to track the refactoring ?

**Comment by resouer** [comment]
@yastij This is not a break issue and only focus on `factory.go` :) 

Please feel free to open new one if needed.
