### ISSUE TITLE
Eviction tests are failing in node e2e serial suite

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#59983]
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e&include-filter-by-regex=Eviction

It correlates with tests setting the EvictionMinimumReclaim setting when using dynamic kubelet config.

This was caused by #53833, but my guess is that we can't use an empty EvictionMinimumReclaim setting like we do here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/eviction_test.go#L74

cc @mtaufen @Random-Liu 
cc @kubernetes/sig-node-test-failures

**Comment by dashpole** [comment]
It looks like the default is actually empty, so we can just remove those settings from the eviction test.

**Comment by mtaufen** [comment]
This is fixed by https://github.com/kubernetes/kubernetes/pull/59989.
The actual issue was that the test helper was using `reflect.DeepEqual` instead of `apiequality.Semantic.DeepEqual` to ensure config updated as expected.
