### ISSUE TITLE
Improve k8s support for multizone PDs.

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#59988]
/kind feature

* Add more e2e tests for multizone PDs.
* Align with ongoing volume topology work.

/sig storage
/assign

**Comment by jberkus** [comment]
Given the lack of responsiveness, this feature issue will be removed from 1.10 in 24 hours unless updated.

@verult

**Comment by verult** [comment]
Apologies for the delayed response. The last outstanding PR is https://github.com/kubernetes/kubernetes/pull/60450, which depends on a Go client that is currently in the process of being rolled out. Expect integration to be complete by this Friday, 3/9.

Also requested the status/approved-for-milestone label.

**Comment by saad-ali** [comment]
This is feature exception was requested and granted in https://groups.google.com/d/msg/kubernetes-milestone-burndown/pwI3QwuCYL4/ugg9UdhWAQAJ

**Comment by verult** [comment]
ACK.  In progress
ETA: 3/9/2018

**Comment by verult** [comment]
The dependency has been updated. #60450 ready for review, and I'm running e2e tests in parallel.
ETA: 3/9/2018
