### ISSUE TITLE
Use protobuf for scheduler extender communication

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#59980]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Scheduler as of now, uses json while communicating with  extender. It would be better if we can use protobuf. This is needed if we want to use extender for usage based scheduling.

cc @aveshagarwal 

 /kind feature
/sig scheduling

**Comment by resouer** [comment]
Per discussion during sig-scheduling meeting. Let's hold this issue and focus on scheduler as framework design.
