### ISSUE TITLE
CRASHLOOPBACKOFF: Exit Code: 127

### ISSUE THREAD

**Issue by VeryVeryGoodNews** [kubernetes/kubernetes#59995]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

When I run `kubectl create -f tensorflow_serving/example/inception_k8s.yaml` from the tensorflow tutorial, the command `kubectl get pods` yields

CrashLoopBackOff error with exit code 134

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl get pods
NAME                                    READY     STATUS             RESTARTS   AGE
inception-deployment-2217120516-3b765   0/1       CrashLoopBackOff   445        1d
inception-deployment-2217120516-d5xvm   0/1       CrashLoopBackOff   445        1d
inception-deployment-2217120516-tfjhr   0/1       CrashLoopBackOff   445        1d
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.12-gke.1", GitCommit:"f4f0bedb82a57dc32b21b8f15fe01e0b8411356b", GitTreeState:"clean", BuildDate:"2018-02-05T18:21:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GKE and GCE
- OS (e.g. from /etc/os-release): Ubuntu 16.01 Xenial
- Kernel (e.g. `uname -a`): Linux covenant-HP-ENVY-x360-m6-Convertible 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@VeryVeryGoodNews Please reopen this issue in the [tensorflow project](https://github.com/tensorflow/serving) since that's who owns the manifests. They do not monitor this project for bugs.

/close
