### ISSUE TITLE
Using systemd cgroup driver, failed to get stats for kubepods.slice/

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#59993]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Follow-on issue from: https://github.com/kubernetes/kubernetes/pull/57802

See the following when using cgroup-driver=systemd every 10s

```
$ cat /tmp/kubelet.log | grep Failed
E0216 18:02:29.460244     302 summary.go:102] Failed to get system container stats for "kubepods.slice/": failed to get cgroup stats for "kubepods.slice/": failed to get container info for "kubepods.slice/": unknown container "kubepods.slice/"
```

Issue is cAdvisor expects a leading / and never a trailing slash, but the expansion method used to do the conversion is omitting leading slash, and always having a trailing slash.

https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L399

we can probably look at a change in runc, or just fix-up the adapt function in kubelet in interim or fixup here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cgroup_manager_linux.go#L60

/kind bug
/sig node
/priority important-critical-soon

**Comment by derekwaynecarr** [comment]
fyi @dashpole @sjenning

**Comment by sjenning** [comment]
I applied @ravisantoshgudimetla fix for runc but I still get this error:
```
summary.go:102]  Failed to get system container stats for "/kubepods.slice": failed to get cgroup stats for "/kubepods.slice": failed to get container info for "/kubepods.slice": unknown container "/kubepods.slice"
```
The path looks to be corrected in the way suggested but we are still getting the error.

**Comment by sjenning** [comment]
Nope nevermind.  The issue was that it kept printing the error right.  I only see it only at the very beginning before cadvisor has populated everything.
