### ISSUE TITLE
[upgrade test failure] Garbage collector should support cascading deletion of custom resources

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#59997]
This flaked 3/4 times in the last week.

/priority failing-test
/priority important-soon
/sig api-machinery
/kind flake

**Comment by AishSundar** [comment]
@jennybuckley Pinging here for latest status on this. This test is now one of our top flakes failing pull-kubernetes-e2e-gce job 40 times.

**Comment by AishSundar** [comment]
Here's the latest test run results for this test to get more logs.

https://k8s-testgrid.appspot.com/sig-api-machinery#gce&include-filter-by-regex=collector&width=5&include-filter-by-regex=Garbage%20collector%20should%20support%20cascading%20deletion%20of%20custom%20resources

**Comment by jennybuckley** [comment]
The error message ```failed to create CustomResourceDefinition: Internal error occurred: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1"``` Is really similar to the one in https://github.com/kubernetes/kubernetes/issues/61355
I'm looking into if the fix for that will also be sufficient to fix this.

**Comment by jennybuckley** [comment]
We may want to reopen this until the fix is shown to actually work
/reopen

**Comment by AishSundar** [comment]
No failure 2 days since the fix. @jennybuckley the fix seemed to have worked. So please go ahead and close the issue. Thanks much.
