### ISSUE TITLE
Update volume scheduling design with event handling details

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#60002]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/sig storage
/kind bug
/assign

**What happened**:
There are some tricky conditions for determining if volume predicate equivalence cache needs to be invalidated (#58797), and also if unschedulable pods should move back to the active queue (#56163).  These conditions should be documented in the code and/or design doc.

**Comment by cofyc** [comment]
@msau42 I've been working on related issues, I'll take this.
/assign
