### ISSUE TITLE
Device unmap for local volume in block mode fails due to empty device path

### ISSUE THREAD

**Issue by dhirajh** [kubernetes/kubernetes#60025]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
A Pod is run with local volume mounted in block mode. When that pod is deleted, the tear down process fails because device unmap fails.  The device path appears to be empty, causing the unmap to fail.

**What you expected to happen**:
The teardown should have succeeded

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a PV for local volume in block mode. 
Delete the pod. Look at kubelet log files on the minion node to observe the error messages.

**Anything else we need to know?**:

Log messages:

Feb 18 09:21:43 kubernetes-minion-group-crj1 kubelet[1510]: E0218 09:21:43.910013    1510 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/local-volume/ff94baee-148c-11e8-b315-42010a8a0002-node1-ssd0\" (\"ff94baee-148c-11e8-b315-42010a8a0002\")" failed. No retries permitted until 2018-02-18 09:21:44.409981582 +0000 UTC m=+18534.512007063 (durationBeforeRetry 500ms). Error: "UnmapVolume.UnmapDevice on global map path failed for volume \"blkdata\" (UniqueName: \"kubernetes.io/local-volume/ff94baee-148c-11e8-b315-42010a8a0002-node1-ssd0\") pod \"ff94baee-148c-11e8-b315-42010a8a0002\" (UID: \"ff94baee-148c-11e8-b315-42010a8a0002\") : Failed to unmap device from map path. mapPath is empty"

Feb 18 09:21:43 kubernetes-minion-group-crj1 kubelet[1510]: I0218 09:21:43.908467    1510 reconciler.go:181] operationExecutor.UnmountVolume started for volume "blkdata" (UniqueName: "kubernetes.io/local-volume/ff94baee-148c-11e8-b315-42010a8a0002-node1-ssd0") pod "ff94baee-148c-11e8-b315-42010a8a0002" (UID: "ff94baee-148c-11e8-b315-42010a8a0002")

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10+
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): "Container-Optimized OS from Google"
- Kernel (e.g. `uname -a`): Linux  4.4.86+ 
- Install tools:
- Others:

**Comment by dhirajh** [comment]
@mtanino @msau42

**Comment by mlmhl** [comment]
This error is returned in this [line](https://github.com/kubernetes/kubernetes/blob/e267f46c8e19a68d8e5c4f056e4e2e46f260d6a4/pkg/volume/util/operationexecutor/operation_generator.go#L968). It same that we set the global mount path to `ASW` only if the volume plugin is attachable(see [here](https://github.com/kubernetes/kubernetes/blob/e267f46c8e19a68d8e5c4f056e4e2e46f260d6a4/pkg/volume/util/operationexecutor/operation_generator.go#L841)). However, local volume plugin is not attachable, so `volumeToUnmount.DeviceMountPath` will be empty and the `UnmapDevice` operation will fail.

I think we should extract the `MarkDeviceAsMounted` operation from the `if volumeAttacher != nil` block, and execute this operation just before we try to map the device to global map path, then this global map path can be cached in `ASW` for both attachable and non attachable volume plugins.

@mtanino  @msau42  Any comments? If not, I can help to fix this.

**Comment by mtanino** [comment]
@mlmhl 
Thank you for the investigation.
We've discussed this problem by offline yesterday. I proposed same fix which you mentioned above, then @dhirajh tested the fix works correctly with local volume plugin.
I'll push a PR soon.

**Comment by mtanino** [comment]
>> The device path appears to be empty, causing the unmap to fail.

Please note, `global unmap path` which was stored in `volumeToUnmount.DeviceMountPath` is empty. device path isn't related to this problem.

**Comment by mlmhl** [comment]
@mtanino
Sorry about that, this is a typo, what I mean is global mount path.

**Comment by mtanino** [comment]
@mlmhl 
No, no. My above comment is just note for the `What happened:` section. Your investigation is correct.
