### ISSUE TITLE
sample-controller should have an example of the polymorphic scale client

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#60023]
When subresources for custom resources (https://github.com/kubernetes/kubernetes/pull/55168) will be merged, we should include an example with the [polymorphic scale client](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/scale).

Not everyone knows about it and many will probably wonder how to use the scale subresource with `client-go`.

Ideas on how to incorporate this into the existing controller welcome.

/sig api-machinery
/kind feature

/cc @sttts @munnerz @DirectXMan12

**Comment by sttts** [comment]
Good task for new contributors.

**Comment by nikhita** [comment]
> Good task for new contributors.

:+1:

For anyone who works on this, there are a bunch of integration tests in the PR mentioned above (https://github.com/kubernetes/kubernetes/pull/55168) which uses the polymporphic scale client with custom resources. Might prove helpful.

**Comment by wanghaoran1988** [comment]
I'd like to take a look at this as a starter  learning CRD.
/assign

**Comment by nikhita** [comment]
/remove-lifecycle stale
/remove-help

I'll do a review of this tomorrow morning.

**Comment by nikhita** [comment]
We should still add this.

/remove-lifecycle rotten
/reopen
