### ISSUE TITLE
Proxy protocol is not working in openshift origin

### ISSUE THREAD

**Issue by apekshasao** [kubernetes/kubernetes#60030]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): centos 7.4
- Kernel (e.g. `uname -a`):Linux ose3master001.services.xxxxxx.avengrsdev.cs.saas.ca.com 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

I am using below command to enable proxy protocol on the nodes:
oc env dc/router ROUTER_USE_PROXY_PROTOCOL=true

But after enabling it my openshift stack wont come up

**Comment by liggitt** [comment]
thanks for the report, can you reopen this against https://github.com/openshift/origin/issues/new
