### ISSUE TITLE
HPA not working properly on 1.9.x keeps same amount of instances

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#60033]
/kind bug

**What happened**:
Hi, we've upgraded one of our clusters to 1.9 however since then autoscaling has been not working -- the amount of instances was kept constantly at the level we scaled it to before applying HPA. Does not matter whether we use the Rest metrics or the oldschool Heapster API.

**How to reproduce it (as minimally and precisely as possible)**:
Unsure honestly, it seems to work fine for other HPAs for other people.

**Anything else we need to know?**:

I've tracked it down to this:
`pkg/controller/podautoscaler/replica_calculator.go`
```
      if math.Abs(1.0-newUsageRatio) <= c.tolerance || (usageRatio < 1.0 && newUsageRatio > 1.0) || (usageRatio > 1.0 && newUsageRatio < 1.0) {
               // return the current replicas if the change would be too small,
               // or if the new usage ratio would cause a change in scale direction
               return currentReplicas, utilization, rawUtilization, timestamp, nil
}
```

however in our case the values were as follows:
`newUsageRatio: %!s(float64=0.14545454545454545), usageRatio: %!s(float64=1.7818181818181817)`
which means it was triggering the last || ORed check.

the pods have request/limit of 1 CPU, they actively cannot use more. The usage was around 990 - 999m with HPA target at 75% CPU so it was supposed to trigger.

I was trying to understand the usageRatio - whether it is <0; +inf) and 1.0 being the mid-point or (-inf; +inf) to scale down/up, sadly ran out of time. Will see if I can do further tracking down later this week or if somebody will know :)

Meanwhile commenting out the odd 1.0 checks seems to have worked and it is scaling fine either way.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2/1.9.3 (tested both)
- Cloud provider or hardware configuration: on-prem
- OS (e.g. from /etc/os-release): Debian
- Kernel (e.g. `uname -a`): 4.9.x branch (Debian Stretch)
- Install tools: manual

Ashley

**Comment by mattjmcnaughton** [comment]
Hi, thanks for reporting this @CallMeFoxie - happy to try and help you debug :)

Do you mind posting the `hpa` logs? 

Thank you for the `newUsageRatio` and `usageRatio` values - could you post a sequence of those over a longer time frame?

**Comment by CallMeFoxie** [comment]
`hpa` logs? There were no logs until I threw in some of my code, basically it was keeping the same count (and thus not rescaling), do not have the exact logs atm and cannot break it atm, maybe on Friday :)

the newUsageRatio and usageRatio were always around (+- 10%) the values I posted, never going through the 1.0 point.

**Comment by mattjmcnaughton** [comment]
Sorry, I wasn't clear about `hpa` logs. Can you post the output of running `kubectl get hpa HPA_NAME`?

Also, I wonder - do you have any pods that are not ready? I'm surprised to hear that there's a persistent difference between `newUsageRatio` and `usageRatio`.

**Comment by mattjmcnaughton** [comment]
Also friday sounds great - no rush :)

**Comment by CallMeFoxie** [comment]
ah. There were no events at the time, only controller was saying about the rebalance that there's no need to rebalance (as 2 == 2 replicas, the max was 90).

**Comment by DirectXMan12** [comment]
> I was trying to understand the usageRatio - whether it is <0; +inf) and 1.0 being the mid-point or (-inf; +inf) to scale down/up, sadly ran out of time. Will see if I can do further tracking down later this week or if somebody will know :)

basically, `newReplicas = usageRatio * oldReplicas`, so `0 < usageRatio < +Inf`, with `1.0` being the midpoint. Less than 1 means scale down (e.g. 0.5 means "scale down to half the current replicas), greater than 1 means scale up (e.g. 2.0 means "double the current replicas").

Based on the numbers that you're seeing, it sounds like you have a bunch of unready pods, or there were metrics missing for some pods.

So, the original usage ratio is calculated by skipping unready pods, and by ignoring missing metrics.  Then, we calculate a new usage ratio by treating the unready pods as having zero metrics, and by treating missing metrics as conservatively as possible for the scale direction (in your case, treating them as consuming zero metrics as well).  Thus, you see `usageRatio = 1.78 = (Pod1 + Pod2 + Pod3)/3/desired`, but then `newUsageRatio = (Pod1 + Pod2 + Pod3 + 0 + 0 + 0)/6/desired`.

**Comment by CallMeFoxie** [comment]
I see, so it is 0 < ratio < +inf. There were no pods in unready state, did not check the metrics but there were only 2 instances running.

Will try simulating it again without the hackpatch then, thanks.
