### ISSUE TITLE
types should be separated out of sample-apiserver

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60047]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
I made some golang clients of the sample api-server, using the API types defined in the sample-apiserver repo.  See https://github.com/MikeSpreitzer/k8api-scaletest .  I use glide to manage dependencies.  When I `glide update` or `glide install`, I get not only the main `vendor` but also `vendor/k8s.io/sample-apiserver/vendor`.  That additional vendor directory makes it impossible to compile the code.

**What you expected to happen**:
I expected there would be a way to write client code that compiles without manually deleting anything.

**How to reproduce it (as minimally and precisely as possible)**:
Make any client that uses anything from sample-apiserver.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
you need to flatten vendor (`glide install -v`)

**Comment by MikeSpreitzer** [comment]
d'oh!
