### ISSUE TITLE
k8s.io/apiserver imposes fixed low limit on the number of concurrent watches proxied to an aggregated api-server

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60042]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I tried running 300 controllers that watch a Kind of object served from an aggregated api-server, and the main api-server started timing out on operations it proxies to the aggregated api-server.  I had only one main api-server and one aggregated api-server.  CPU, memory, and network load were not an issue.

**What you expected to happen**:
I expected no such timeouts.

**How to reproduce it (as minimally and precisely as possible)**:
Run the aggregated api-server from k8s.io/sample-apiserver.  Build https://github.com/MikeSpreitzer/k8api-scaletest/tree/master/flunder-watch and run more than 250 flunder-watch concurrently.  Observe timeouts in the main api-server's log.

**Anything else we need to know?**:
The main api-server opens one HTTP/2 connection to the service IP of the aggregated api-servers and does all its proxying through streams inside that connection.  The most immediate problem is that k8s.io/apiserver, which is the basis of the aggregated api-serve as well as the main one, uses the default value of 250 max client-initiated streams per HTTP/2 connection.  See the default in https://github.com/golang/net/blob/master/http2/server.go .  The generic apiserver code does not call `golang.org/net/http2.ConfigureServer`, so the default applies.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8 and 1.9
- Cloud provider or hardware configuration: local hardware
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by lavalamp** [comment]
Thanks for finding this, looks like your PR is already approved. :)
