### ISSUE TITLE
Insecure aggregation should be possible

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60049]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
I spent a _long_ time doing problem determination for #60042 .   It would have been _much_ easier if I could have looked at the packets on the wire.  As it is, they were all encrypted by TLS, so I got no useful information out of them (they came too frequently for timing to be enough).

**What you expected to happen**:
I expected there to be a way, document and supported (at least for debugging purposes), to aggregate an api-server with cleartext communication between the main api-server and the aggregated one.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
> I expected there to be a way, document and supported (at least for debugging purposes), to aggregate an api-server with cleartext communication between the main api-server and the aggregated one.

I'm pretty opposed to surfacing and supporting this... it adds maintenance overhead and encourages use of a mode we don't ever want used in production.

For debugging/developing the apiserver itself, we could run a self-compiled one with the aggregator scheme hardcoded to http.

**Comment by MikeSpreitzer** [comment]
Would that be enough?  I do not see a code path in k8s.io/apiserver for serving insecurely.

**Comment by liggitt** [comment]
> I do not see a code path in k8s.io/apiserver for serving insecurely.

Ah, right. Again, that is intentionally omitted for all actual deployment scenarios.

**Comment by MikeSpreitzer** [comment]
And I agree that serving securely should be the norm.  My question is can we make it reasonably easy to run insecurely for development/debugging purposes.

**Comment by liggitt** [comment]
> My question is can we make it reasonably easy to run insecurely

That requires adding options we don't want to at least two components, and possibly to supporting APIs

> for development/debugging purposes

if we don't develop securely, we won't deploy securely. "run insecurely" options "for development/debugging purposes" have an insidious way of making it into production.

if non-TLS is desired to debug the aggregator itself, a custom dev build to aggregate over http seems reasonable

**Comment by deads2k** [comment]
I don't think we should do this.  I sympathize with packet sniffing difficulties (it wasn't easy to get working initially), but the cost to the rest of the stack as they try to reason about what should and should not happen with "sometimes" available authentication information is too great.  The bugs caused by insecure servers were more insidious, more frequent, affected more people (both authors and debuggers), and more severe.

**Comment by MikeSpreitzer** [comment]
OK, withdrawn.
