### ISSUE TITLE
Enable metav1beta1.Table responses on `kubectl get`

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#60045]
/kind feature

PR: https://github.com/kubernetes/kubernetes/pull/55637
Checks "Client" items from https://github.com/kubernetes/kubernetes/issues/58536

Updates `kubectl get` to request and handle metav1beta1.Table responses from the server.

Milestone v1.10

**Comment by juanvallejo** [comment]
cc @jberkus

**Comment by jberkus** [comment]
Can you add this to the 1.10 milestone?   A member of the SIG needs to do that.

**Comment by juanvallejo** [comment]
> Can you add this to the 1.10 milestone? A member of the SIG needs to do that.

ping @adohe or @soltysh

**Comment by lavalamp** [comment]
Can you edit the OP to explain the apparent contradiction? :)

**Comment by lavalamp** [comment]
cc @yliaog

**Comment by soltysh** [comment]
I've updated the milestone and closing this, since #55637 already merged.
