### ISSUE TITLE
Internal load balancer always created with empty backend pool

### ISSUE THREAD

**Issue by ilyalukyanov** [kubernetes/kubernetes#60060]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Azure internal load balancer created for a `Service` of type `LoadBalancer` has empty backend pool.

**What you expected to happen**:

VMs from the primary availability set should be added to the backend pool.

**How to reproduce it (as minimally and precisely as possible)**:

I reliably reproduce it using the following resource:
```
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "test-service",
    "namespace": "development",
    "annotations": {
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
    }
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 12345,
        "targetPort": 12345
      }
    ],
    "selector": {
      "app": "test-app"
    },
    "clusterIP": "10.0.100.2",
    "type": "LoadBalancer",
    "loadBalancerIP": "172.19.5.10"
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux k8s-master-34133888-0 4.13.0-1005-azure #7-Ubuntu SMP Mon Jan 8 21:37:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: ACS Engine
```
Version: canary
GitCommit: 7923b960
GitTreeState: clean
```
- Others:

**Comment by feiskyer** [comment]
@ilyalukyanov Have you created backend pods for this services? What's the output of `kubectl -n development describe service test-service`?

**Comment by ilyalukyanov** [comment]
@feiskyer thanks for your response.

Yes, backend pods for the service are created and ready. The output of `kubectl -n development describe service test-service` is:
```
Name:			test-service
Namespace:		development
Labels:			<none>
Annotations:		service.beta.kubernetes.io/azure-load-balancer-internal=true
Selector:		app=test-app
Type:			LoadBalancer
IP:			10.0.100.2
LoadBalancer Ingress:	172.19.5.10
Port:			<unset>	10008/TCP
NodePort:		<unset>	30664/TCP
Endpoints:		10.244.0.84:10008,10.244.2.85:10008
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		2m		1	service-controller			Normal		EnsuringLoadBalancer	Ensuring load balancer
  2m		2m		1	service-controller			Normal		EnsuredLoadBalancer	Ensured load balancer
```

I can reproduce it in 100% cases. No nodes in the backend pool and no association with an availability set:
![screen shot 2018-03-05 at 1 29 39 pm](https://user-images.githubusercontent.com/3818101/36952814-6a603414-2079-11e8-990c-18a697703152.png)

**Comment by feiskyer** [comment]
@ilyalukyanov Thanks of details. The issue should be fixed with https://github.com/kubernetes/kubernetes/pull/59747, which will be included in kubernetes v1.9.4. Could you verify whether the cherry-pick (https://github.com/kubernetes/kubernetes/pull/59754) solved the problem?

**Comment by ilyalukyanov** [comment]
@feiskyer Awesome, thanks for the fix! It's currently problematic for me to try, but we'll plan this work and I'll confirm here once I get a chance to test.

**Comment by feiskyer** [comment]
v1.9.4 is not released yet, it would need sometime to support this.

**Comment by diwakar-s-maurya** [comment]
@ilyalukyanov I was also facing the same issue as you. By upgrading the kubernetes version to v1.9.4, it got resolved.

**Comment by feiskyer** [comment]
@diwakar-s-maurya Thanks for the validation.

Let's close this issue since it's been resolved.

**Comment by ilyalukyanov** [comment]
Thank you guys!
