### ISSUE TITLE
How to delete orphaned pods for non existing nodes

### ISSUE THREAD

**Issue by ddehghan** [kubernetes/kubernetes#60066]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
One of my nodes went down and the remaining nodes could not support all the remaining pods. I rebooted the nodes to get the pods to restart but still some where not restarting so eventually I terminated the EC2 nodes. 

Now I still have some pods stuck 

**What you expected to happen**:

Now that I have these stuck pods how do I get rid of them. The nodes and deployment and replica sets are all deleted. Just these pods are left which I can't get rid of.

```
> kubectl delete pods grafana-grafana-68666bf8b-p47vq --force  --timeout=0s
pod "grafana-grafana-68666bf8b-p47vq" deleted

but in effect it was not deleted and it is still around no matter how many times I run the delete pods command.

```

**How to reproduce it (as minimally and precisely as possible)**:

```
> kubectl get pods | grep Terminating
kafka-cons-7f54bf4ff7-zxn2t                   0/4       Terminating   0          1d
grafana-grafana-68666bf8b-p47vq         0/1       Terminating   0          1d


> kubectl describe pod grafana-grafana-68666bf8b-p47vq
Name:                      grafana-grafana-68666bf8b-p47vq
Namespace:                 default
Node:                      ip-172-20-57-175.ec2.internal/172.20.57.175
Start Time:                Sun, 18 Feb 2018 22:31:09 -0800
Labels:                    app=grafana-grafana
                           component=grafana
                           pod-template-hash=242226946
                           release=grafana
Annotations:               checksum/config=7864d8107c05aec4bb7b398fc5ada6bdb4a197bb3ae3d1a3e5db347ceb162458
                           checksum/dashboards-config=bdae026110c4098fa1563d79ce64d392bf5c179d25cedaba8f2cae97b3db72bc
                           kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"grafana-grafana-68666bf8b","uid":"78043313-153e-11e8-9cb9-0aa40b...
Status:                    Terminating (expires Mon, 19 Feb 2018 23:50:55 -0800)
Termination Grace Period:  0s
IP:                        
Controlled By:             ReplicaSet/grafana-grafana-68666bf8b
Containers:
  grafana:
    Container ID:   docker://cfc193fd73cdeb782476d0fbf1904760942fe0ede088005b3a4d24f5de49a36b
    Image:          grafana/grafana:4.6.3
    Image ID:       docker-pullable://grafana/grafana@sha256:6397aafb899ef7a9ca61c2ef80863dbebce504620b044954d80203e0b8c1ada4
    Port:           3000/TCP
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      100m
      memory:   100Mi
    Readiness:  http-get http://:3000/api/health delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:
      GF_SECURITY_ADMIN_USER:      <set to the key 'grafana-admin-user' in secret 'grafana-grafana'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'grafana-admin-password' in secret 'grafana-grafana'>  Optional: false
    Mounts:
      /etc/grafana from config-volume (rw)
      /var/lib/grafana from storage-volume (rw)
      /var/lib/grafana/dashboards from dashboard-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-j52jh (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-grafana-config
    Optional:  false
  dashboard-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-grafana-dashs
    Optional:  false
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  grafana-grafana
    ReadOnly:   false
  default-token-j52jh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-j52jh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>


```

**Anything else we need to know?**:

The deployments and replica set are all done because i uninstalled Grafana via helm:

```
> helm delete grafana --purge

```

```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "grafana-grafana-68666bf8b-p47vq",
    "generateName": "grafana-grafana-68666bf8b-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/grafana-grafana-68666bf8b-p47vq",
    "uid": "78073a53-153e-11e8-9cb9-0aa40bb952d6",
    "resourceVersion": "1450268",
    "creationTimestamp": "2018-02-19T06:31:08Z",
    "deletionTimestamp": "2018-02-20T08:17:16Z",
    "deletionGracePeriodSeconds": 0,
    "labels": {
      "app": "grafana-grafana",
      "component": "grafana",
      "pod-template-hash": "242226946",
      "release": "grafana"
    },
    "annotations": {
      "checksum/config": "7864d8107c05aec4bb7b398fc5ada6bdb4a197bb3ae3d1a3e5db347ceb162458",
      "checksum/dashboards-config": "bdae026110c4098fa1563d79ce64d392bf5c179d25cedaba8f2cae97b3db72bc",
      "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"grafana-grafana-68666bf8b\",\"uid\":\"78043313-153e-11e8-9cb9-0aa40bb952d6\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"1312504\"}}\n"
    },
    "ownerReferences": [
      {
        "apiVersion": "extensions/v1beta1",
        "kind": "ReplicaSet",
        "name": "grafana-grafana-68666bf8b",
        "uid": "78043313-153e-11e8-9cb9-0aa40bb952d6",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ],
    "finalizers": [
      "foregroundDeletion"
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "config-volume",
        "configMap": {
          "name": "grafana-grafana-config",
          "defaultMode": 420
        }
      },
      {
        "name": "dashboard-volume",
        "configMap": {
          "name": "grafana-grafana-dashs",
          "defaultMode": 420
        }
      },
      {
        "name": "storage-volume",
        "persistentVolumeClaim": {
          "claimName": "grafana-grafana"
        }
      },
      {
        "name": "default-token-j52jh",
        "secret": {
          "secretName": "default-token-j52jh",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "grafana",
        "image": "grafana/grafana:4.6.3",
        "ports": [
          {
            "containerPort": 3000,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "GF_SECURITY_ADMIN_USER",
            "valueFrom": {
              "secretKeyRef": {
                "name": "grafana-grafana",
                "key": "grafana-admin-user"
              }
            }
          },
          {
            "name": "GF_SECURITY_ADMIN_PASSWORD",
            "valueFrom": {
              "secretKeyRef": {
                "name": "grafana-grafana",
                "key": "grafana-"
              }
            }
          }
        ],
        "resources": {
          "requests": {
            "cpu": "100m",
            "memory": "100Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "config-volume",
            "mountPath": "/etc/grafana"
          },
          {
            "name": "dashboard-volume",
            "mountPath": "/var/lib/grafana/dashboards"
          },
          {
            "name": "storage-volume",
            "mountPath": "/var/lib/grafana"
          },
          {
            "name": "default-token-j52jh",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "readinessProbe": {
          "httpGet": {
            "path": "/api/health",
            "port": 3000,
            "scheme": "HTTP"
          },
          "initialDelaySeconds": 30,
          "timeoutSeconds": 30,
          "periodSeconds": 10,
          "successThreshold": 1,
          "failureThreshold": 3
        },
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 300,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "ip-172-20-57-175.ec2.internal",
    "securityContext": {},
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.alpha.kubernetes.io/notReady",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.alpha.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ]
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-02-19T06:31:09Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-02-20T01:06:37Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [grafana]"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-02-19T06:31:09Z"
      }
    ],
    "hostIP": "172.20.57.175",
    "startTime": "2018-02-19T06:31:09Z",
    "containerStatuses": [
      {
        "name": "grafana",
        "state": {
          "terminated": {
            "exitCode": 0,
            "startedAt": null,
            "finishedAt": null
          }
        },
        "lastState": {},
        "ready": false,
        "restartCount": 0,
        "image": "grafana/grafana:4.6.3",
        "imageID": "docker-pullable://grafana/grafana@sha256:6397aafb899ef7a9ca61c2ef80863dbebce504620b044954d80203e0b8c1ada4",
        "containerID": "docker://cfc193fd73cdeb782476d0fbf1904760942fe0ede088005b3a4d24f5de49a36b"
      }
    ],
    "qosClass": "Burstable"
  }
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration:

EC2 T2 micro for nodes and master

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:

KOPS 1.8

- Others:

@kubernetes/sig-bugs

**Comment by ddehghan** [comment]
@kubernetes/sig-bugs /sig bugs

**Comment by zparnold** [comment]
We are having this issue too. It seems to occur only in one namespace for us (we have about 8.) It is worth noting in our case, this particular namespace has a high amount of churn from a deployment perspective (several times per day.) I fixed it once by deleting the namespace and manually removing the pods from etcd using a client. I suspect that's not a great answer though.

**Comment by zparnold** [comment]
@ddehghan Can you try something for me? (I'll try to replicate and fix this with a PR if I can.) Can you run `tail -f /var/log/kube-apiserver.log`, then run the command `kubectl delete pods grafana-grafana-68666bf8b-p47vq --force  --timeout=0s` and tell me what you see/post it here?

**Comment by jurgenweber** [comment]
I sometimes have pods that end up in a weird state, I am unsure if the cause is exactly the same as yours.

What I do is log onto the etcd server and use 
```
etcdctl rm /resources/<namespace>/pods/<podname>
```
( if unsure, start with etcdctl ls )

to remove from etcd and hence dashboard. I only do this in extreme circumstances and whe nI ahve confirmed the pod/container is most definitely not there.

**Comment by ddehghan** [comment]
unfortunately i don't have the repro environment anymore. We moved to google GCP to avoid all these issues of setting up a cluster.

**Comment by davidmessem** [comment]
I am having the same issue, Kubernetes 1.9.6, running on AWS 

I deleted a helm chart with a daemonset, and it just hung.
The helm chart is no longer listed when I run helm ls though.
I deleted the daemonset, and it tried to delete the pods, but the command just hung as well.
I then force deleted the pods (--force --grace-period=0), but those commands hung too.

Daemonset description:
> Name:           weave-scope-agent-devops-weavescope
> Selector:       app=weave-scope,component=agent,release=devops-weavescope
> Node-Selector:  ca7bc691-93a8-11e8-9b5b-acbc32a30105=ca7bc761-93a8-11e8-9b5b-acbc32a30105
> Labels:         app=weave-scope
>               chart=weave-scope-agent-0.9.2
>                component=agent
>                heritage=Tiller
>                release=devops-weavescope
> Annotations:    cloud.weave.works/launcher-info={
>   "server-version": "master-4fe8efe",
>   "original-request": {
>     "url": "/k8s/v1.7/scope.yaml"
>   },
>   "email-address": "support@weave.works",
>   "source-app": "weave-...
> Desired Number of Nodes Scheduled: 0
> Current Number of Nodes Scheduled: 0
> Number of Nodes Scheduled with Up-to-date Pods: 0
> Number of Nodes Scheduled with Available Pods: 0
> Number of Nodes Misscheduled: 6
> Pods Status:  9 Running / 0 Waiting / 0 Succeeded / 0 Failed
> Pod Template:
>   Labels:           app=weave-scope
>                     chart=weave-scope-agent-0.9.2
>                     component=agent
>                     heritage=Tiller
>                     release=devops-weavescope
>   Service Account:  weave-scope-agent-devops-weavescope
>   Containers:
>    weave-scope-agent:
 >    Image:      weaveworks/scope:1.9.0
 >    Port:       <none>
 >    Host Port:  <none>
>     Args:
>       --no-app
>       --probe.docker.bridge=docker0
>       --probe.docker=true
>       --probe.kubernetes=true
>       --probe.ebpf.connections=true
>       devops-weavescope-weave-scope.devops.svc:80
>     Environment:  <none>
>     Mounts:
>       /sys/kernel/debug from sys-kernel-debug (rw)
>       /var/run/docker.sock from docker-socket (rw)
>       /var/run/scope/plugins from scope-plugins (rw)
>   Volumes:
>    docker-socket:
>     Type:          HostPath (bare host directory volume)
>     Path:          /var/run/docker.sock
>     HostPathType:
>    scope-plugins:
>     Type:          HostPath (bare host directory volume)
>     Path:          /var/run/scope/plugins
>     HostPathType:
>    sys-kernel-debug:
>     Type:          HostPath (bare host directory volume)
>     Path:          /sys/kernel/debug
>     HostPathType:
> Events:            <none>

Pod description:

> Name:                      weave-scope-agent-devops-weavescope-4qf5t
Namespace:                 devops
Node:                      ip-xxxxxxxx.eu-west-1.compute.internal/xxxxxx <- DOESN'T EXIST ANYMORE
Start Time:                Thu, 21 Jun 2018 09:13:55 +0200
Labels:                    app=weave-scope
                           chart=weave-scope-agent-0.9.2
                           component=agent
                           controller-revision-hash=1846320508
                           heritage=Tiller
                           pod-template-generation=2
                           release=devops-weavescope
Annotations:               <none>
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  0s
IP:                        10.103.18.233
Controlled By:             DaemonSet/weave-scope-agent-devops-weavescope
Containers:
  weave-scope-agent:
    Container ID:  docker://183a46dcc85dc66fb14d53f73f60f67dcce3cb2662e5ab16ace7f37a8be69927
    Image:         weaveworks/scope:1.9.0
    Image ID:      docker-pullable://weaveworks/scope@sha256:8ae417ec8d221fedc6350b1d221469ffd6724be121f9ca6b2ab188f2161be1ca
    Port:          <none>
    Host Port:     <none>
    Args:
      --no-app
      --probe.docker.bridge=docker0
      --probe.docker=true
      --probe.kubernetes=true
      devops-weavescope-weave-scope.devops.svc:80
    State:          Terminated
      Exit Code:    0
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /sys/kernel/debug from sys-kernel-debug (rw)
      /var/run/docker.sock from docker-socket (rw)
      /var/run/scope/plugins from scope-plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-scope-agent-devops-weavescope-token-8qcvr (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  docker-socket:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
  scope-plugins:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/scope/plugins
    HostPathType:
  sys-kernel-debug:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:
  weave-scope-agent-devops-weavescope-token-8qcvr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  weave-scope-agent-devops-weavescope-token-8qcvr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:          <none>

Here are some relevant logs from the kube-apiserver.log

> 1 wrap.go:42] DELETE /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-9hlh4: (2.110988ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]10.103.18.224:59536]
I0731 04:42:00.057242       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: (149.323µs) 404 [[kube-apiserver/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52368]
I0731 04:42:00.180907       1 wrap.go:42] GET /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-v2-fjk2j: (1.140301ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.373263       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations: (753.38µs) 200 [[kube-apiserver/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52368]
I0731 04:42:00.381863       1 wrap.go:42] PUT /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-v2-fjk2j/status: (2.030187ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.435196       1 wrap.go:42] GET /api/v1/namespaces/devops/services/ingress-nginx: (726.037µs) 404 [[nginx-ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format] 10.103.18.224:59536]
I0731 04:42:00.501713       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations: (664.144µs) 200 [[kube-apiserver/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52368]
I0731 04:42:00.591470       1 wrap.go:42] DELETE /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-v2-fjk2j: (11.696005ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.635133       1 wrap.go:42] GET /api/v1/namespaces/devops/services/ingress-nginx: (669.206µs) 404 [[nginx-ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format] 10.103.18.224:59536]
I0731 04:42:00.731527       1 wrap.go:42] GET /api/v1/nodes/ip-xxxxxxxxxx.eu-west-1.compute.internal?resourceVersion=0: (463.536µs) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.735192       1 wrap.go:42] GET /api/v1/namespaces/devops/services/ingress-nginx: (747.118µs) 404 [[nginx-ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format] 10.103.18.224:59536]
I0731 04:42:00.749749       1 wrap.go:42] PATCH /api/v1/nodes/ip-xxxxxxxx.eu-west-1.compute.internal/status: (10.985521ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.774692       1 wrap.go:42] GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler: (769.48µs) 200 [[kube-scheduler/v1.9.6 (linux/amd64) kubernetes/9f8ebd1/leader-election] 127.0.0.1:52264]
I0731 04:42:00.780766       1 wrap.go:42] GET /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-9hlh4: (1.053494ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:00.982948       1 wrap.go:42] PUT /api/v1/namespaces/devops/pods/weave-scope-agent-devops-weavescope-9hlh4/status: (2.931563ms) 200 [[kubelet/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52060]
I0731 04:42:01.058112       1 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: (138.836µs) 404 [[kube-apiserver/v1.9.6 (linux/amd64) kubernetes/9f8ebd1] 127.0.0.1:52368]

**Comment by tsahoo** [comment]
Same case here 
After helm delete <helmchart name> --purge
Even I ran kubectl  delete pod <podname> --timeout=0s -n <namespace>

Its showing pod got deleted but when I do kubectl get pods -n <namespace>,the same pod is recreating.

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by synthesisdickie** [comment]
Thanks @jeremysf. I found the command that patches the pod's finalizers after a force deletion. For anyone still struggling, the command looks something like this: "kubectl patch pod [podname] -n [namespace] -p '{"metadata":{"finalizers":null}}'"

**Comment by joeyparis** [comment]
> Thanks @jeremysf. I found the command that patches the pod's finalizers after a force deletion. For anyone still struggling, the command looks something like this: "kubectl patch pod [podname] -n [namespace] -p '{"metadata":{"finalizers":null}}'"

When I run this command to patch the pod's finalizer I just get the response `pod "[podname]" not patched`. I tried it on a few of the pods but got the same message for all of them and they all remain with an "Unknown" status. Any ideas?

**Comment by chenbodeng719** [comment]
> I found the command that patches the pod's finalizers after a force deletion. For anyone still struggling, the command looks something like this: "kubectl patch pod [podname] -n [namespace] -p '{"metadata":{"finalizers":null}}'"

You save my life! God bless you!
