### ISSUE TITLE
local-up-cluster: cfssl is downloaded everytime, it should be downloaded just once

### ISSUE THREAD

**Issue by mrostecki** [kubernetes/kubernetes#60070]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

If you don't have cfssl in your `PATH`, then `local-up-cluster` script is downloading it on every execution, instead of downloading it once. It increases the execution time.

**What you expected to happen**:

If you don't have cfssl in `PATH`, `local-up-cluster.sh` script should download/install it only once and the next execution of script should just use the installed cfssl.

**How to reproduce it (as minimally and precisely as possible)**:

1. Ensure that you don't have `cfssl`
2. Execute `local-up-cluster.sh` script multiple times and observe that `cfssl` is downloaded every time.

**Anything else we need to know?**:

I think that the approach in the following function:

https://github.com/kubernetes/kubernetes/blob/master/hack/lib/util.sh#L740-L755

does not work and is too complicated. IMO we could just do `go get -u github.com/cloudflare/cfssl/cmd/...` if `cfssl` is not present in `PATH` and that's all. That script is for developers and it expects to have a working Golang environment, so I don't see any point in fetching OS-specific binary.

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: doesn't matter
- OS (e.g. from /etc/os-release):doesn't matter
- Kernel (e.g. `uname -a`): doesn't matter
- Install tools: local-up-cluster.sh
- Others:

**Comment by dims** [comment]
@mrostecki i've been meaning to chase this. Thanks for doing that. 

One observation, we have a precedent on what we do if etcd is not present. we can follow the same here 

https://github.com/kubernetes/kubernetes/blob/master/hack/lib/etcd.sh#L120-L121

essentially if etcd binaries are not present we download them into third_party and prompt the user to add that to the PATH.

**Comment by mrostecki** [comment]
@dims Good point. Maybe following the approach we already take with etcd would be better, because we will not do anything automatically (especially with `GOPATH`) and developer would take care of managing his `PATH` variable.

So. in case when `cfssl` is not installed, we may just point the user to a separate script for installing cfssl in `third_party` directory.

@cblecker WDYT? ^

**Comment by mrostecki** [comment]
And we may do that for every external dependency we need in `local-up-cluster.sh`, just for being consistent.

**Comment by cblecker** [comment]
I dug into this. The `kube::util::ensure-cfssl` function isn't just used in local-cluster-up, but it's also used in cluster/common.sh and cluster/gce/util.sh. As such we have to be very careful with changes to it (until such time as cluster/ is deprecated).

Right now the direction we're leaning with these is to actually vendor them, and install from vendor (see https://github.com/kubernetes/kubernetes/pull/57600 and https://github.com/kubernetes/kubernetes/pull/59210).

What I'd suggest is we wait and figure out the right vendoring pattern for these kind of utilities, and then apply this to cfssl/cmd too.

**Comment by dims** [comment]
@cblecker any update on vendoring pattern we'd prefer?
