### ISSUE TITLE
k8s.io/sample-apiserver is not exemplary wrt certificates

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60082]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
I just noticed that the sample apiserver is cheating wrt authentication and authorization.  Its `APIService` object's spec includes `insecureSkipTLSVerify: true`, which is not recommended.

**What you expected to happen**:
I expected the sample to be more exemplary.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by lavalamp** [comment]
Agree we should do better. We unfortunately have thus far been unable to come to agreement on how to pass identity information into aggregated apiserver (and webhook hosts).

cc @cheftako @deads2k

**Comment by munnerz** [comment]
FWIW, I have updated cert-manager with a real world example of this in action. It sets up an APIService (and then later a ValidatingWebhook which points at this APIService), using cert-manager itself to manage all the PKI required.

You can see an example of the required cert-manager manifests for this, here: https://github.com/munnerz/cert-manager/blob/e95e2327f2720aa45ed3f48ef2ecf6595972d380/contrib/charts/cert-manager/templates/webhook-pki.yaml

I have then created a little tool, `apiextensions-ca-helper` which will automatically update the `caBundle` field of the APIService with the CA certificate generated by cert-manager: https://github.com/munnerz/cert-manager/blob/e95e2327f2720aa45ed3f48ef2ecf6595972d380/contrib/charts/cert-manager/templates/webhook-ca-sync.yaml. This runs as a CronJob, currently every 24h (although this can obviously be changed or manually performed).

This actually works really nicely, and allows me to 'bootstrap' cert-manager itself in the absence of any other PKI infra.

I'm not sure if we can include this as part of sample-apiserver as a concrete example, but it could be valuable to mention this pattern (and maybe an example) in the README or the like so others can make use of it if they want to.
