### ISSUE TITLE
Stop accepting PRs to examples/ directory

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#60092]
https://github.com/kubernetes/kubernetes/tree/master/examples/
is now at
https://github.com/kubernetes/examples/ and has been there for many months.

However we're still seeing maintainers accept PRs to the `examples/` directory.  These PRs should be sent to the new repo instead.

Can someone help us set up some sort of CI test that prevent PRs that change `examples/` from getting merged?

We intend to copy the recent commits in the `examples/` to the new repo and delete the `examples/` directory for good. (We haven't done it so far mostly because we don't want to break people without proper notice.)

/sig contributor-experience

**Comment by BenTheElder** [comment]
We can configure a `blockade`:
https://github.com/kubernetes/test-infra/blob/59a11a83031401e9d2c5ca96a96d743f572fd5a0/prow/plugins.yaml#L63-L90

**Comment by BenTheElder** [comment]
PRing this in test-infra

**Comment by ahmetb** [comment]
This is now resolved since we added the blockade.
/close
