### ISSUE TITLE
Performance tests occasionally flaking while RC creation

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#60097]
I'm seeing such flakes occasionally during our load/density tests:

```
Number of reported pods for density60000-2-15628d31-e0f9-11e7-8065-0a580a3cfc83 changed: 2999 vs 3000
not to have occurred
```

```
Number of reported pods for load-small-4517 changed: 4 vs 5
not to have occurred
```

Ref:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/29/
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/35/
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/59/

We need to figure out why we're seeing them and try to fix.

cc @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
Seems like these isn't really a condition which should cause the tests to fail. As the #pods of an RC can decrease in certain cases, as mentioned in a comment at the relevant code path:

https://github.com/kubernetes/kubernetes/blob/dd9de90b0ad1aa78c2a8dd7d5238d8f769ffe771/test/utils/runners.go#L771-L777

/assign
I'll take a deeper look into this later.

**Comment by wojtek-t** [comment]
We chatted briefly with Shyam about it and I think that it actually should be a failure in our tests.

In huge majority of cases, this condition is triggered because some (more) nodes become unresponsive. And this is happening for some reason. And in many cases in the past, that reason was actually performance. So allowing for failing nodes, will mask the real problems that we actually have.

So I'm against removing that, because it will mask real problems.

**Comment by wojtek-t** [comment]
This happened also recently:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/155

**Comment by shyamjvs** [comment]
cc @mborsz - If you can take a look.

**Comment by mborsz** [comment]
/assign

In https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/181 I saw an instance of this issue.
In logs of the VM I see that all processes were restarted at some point, in GCE logs I was able to find information that the VM was restarted due to host error.

**Comment by shyamjvs** [comment]
Refreshing this bug.. Another similar flake observed recently - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/148

cc @krzysied

**Comment by nikopen** [comment]
Namespace deletion couldn't proceed because of a docker failure:

```
Sep 22 18:51:41.627: INFO: Condition Ready of node gce-scale-cluster-minion-group-nscr is false instead of true. Reason: KubeletNotReady, message: container runtime is down
```

```
Sep 22 20:09:52.749: INFO: namespace: **e2e-tests-density-30-4-2j5q6**, total namespaces: 20, active: 19, terminating: 1
Sep 22 20:09:52.787: INFO: POD                                                        NODE                                 PHASE    GRACE  CONDITIONS
Sep 22 20:09:52.787: INFO: density59940-3-7a8807a2-be8b-11e8-bd41-0a580a3c39c9-4n99l  gce-scale-cluster-minion-group-nscr  Running  1s     [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:23:15 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 19:05:11 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:40:44 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:19:01 +0000 UTC  }]
```

```
Sep 22 21:11:29.454: INFO: namespace: ***e2e-tests-density-30-8-wkh8v***, total namespaces: 17, active: 15, terminating: 2
Sep 22 21:11:29.494: INFO: POD                                                        NODE                                 PHASE    GRACE  CONDITIONS
Sep 22 21:11:29.494: INFO: density59940-7-7a8807a2-be8b-11e8-bd41-0a580a3c39c9-l5hw4  gce-scale-cluster-minion-group-nscr  Running  1s     [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:23:18 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 19:05:11 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:37:17 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-09-22 17:19:12 +0000 UTC  }]
```

```
Sep 22 21:17:41.643: INFO: Couldn't delete ns: **"e2e-tests-density-30-4-2j5q6"**: namespace e2e-tests-density-30-4-2j5q6 was not deleted with limit: timed out waiting for the condition, pods remaining: 1 (&errors.errorString{s:"namespace e2e-tests-density-30-4-2j5q6 was not deleted with limit: timed out waiting for the condition, pods remaining: 1"}),Couldn't delete ns: **"e2e-tests-density-30-8-wkh8v"**: namespace e2e-tests-density-30-8-wkh8v was not deleted with limit: timed out waiting for the condition, pods remaining: 1 (&errors.errorString{s:"namespace e2e-tests-density-30-8-wkh8v was not deleted with limit: timed out waiting for the condition, pods remaining: 1"})
```

@shyamjvs @krzysied

**Comment by jberkus** [comment]
@shyamjvs @nikopen is this test still flaky?  Is there any plan to de-flake it?

**Comment by wojtek-t** [comment]
Yes - it still happens. Yes - there is plan to deflake it this quarter.

**Comment by wojtek-t** [comment]
I don't think we observed anything like that any time in the last couple months. Closing.
