### ISSUE TITLE
Service-environment variables should be optional

### ISSUE THREAD

**Issue by xeor** [kubernetes/kubernetes#60099]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Every container gets ~8 environmentvariables per service exposing a lot of information, and there is no way to turn it off.

**What you expected to happen**:
This `docker` deprecated `--link` feature compatibility option to be an opt-in (or at least opt-out) option.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new container in a cluster where there are existing services. Check the `env`. You should see something like:

```
/ # env | grep KUBERNETES
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.233.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.233.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.233.0.1:443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_HOST=10.233.0.1

# one ingress-controller
/ # env | grep INGRESS_NGINX_EXT | wc -l
36
```

**Anything else we need to know?**:
The code doing this is https://github.com/kubernetes/kubernetes/blob/v1.9.3/pkg/kubelet/kubelet_pods.go#L551-L553, and some docs at https://kubernetes.io/docs/concepts/containers/container-environment-variables/.

Maybe things like this should be exposed using eg the downwards api instead (https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: on-prem
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

**Comment by mrostecki** [comment]
I like the idea of making those environment variables optional. I think it could be managed by a flag provided (`--enable-service-env`?).

I like the idea about exposing information about services in downward API as well, but that sounds like a very complicated feature, which would need to involve teaching downward API to select external resources by label selectors. IMO it definitely needs a separate issue and feature request in the community repo.

**Comment by xeor** [comment]
I would imaging this being nicer to have at the pod-definition, or maybe as an attribute? I can see this being useful some times, but I rather want it default off.

I don't know the inner details so say either way, nor have I ever used those variables to say if really when they are useful. Do people even use kubernetes without a dns controller of some sort (in other words, is this needed at all)?

**Comment by mrostecki** [comment]
>I would imaging this being nicer to have at the pod-definition, or maybe as an attribute?

An attribute seems to be better, at least for the first implementation - it will not require any API changes.

**Comment by krmayankk** [comment]
@xeor what is the use case for disabling these environment variables, security  ?

**Comment by mrostecki** [comment]
@krmayankk I wouldn't say that there is any specific usecase. They're just not needed. I'd say that currently Kubernetes users should access services by using DNS and there is no need for keeping IP addresses and ports in environment variables.

The pattern of having those variables is an old behavior of Docker (`--link` option, which is deprecated FWIK) and docker-compose.

**Comment by xeor** [comment]
@krmayankk there is not really a specific usecase as @mrostecki said.. It is more or less the reason that they are not needed. Even tho not really security related, it also exposed a lot of info about whats in it's namespace.
Felt like it was bloating up my pods `env` as well. everything from 0 to 6-8 entries per other pod in the namespace.

**Comment by krmayankk** [comment]
IMO if there is no real use case we shouldnt yet remove these environment variables. The primary reason being they are an excellent way for primitive service discovery for pods untill we have some other better way which is available in the default configuration . DNS is not available to kubernetes users by default and i would think by default we want to make it easy for our customers to use kubernetes. @thockin might have some thoughts here .

**Comment by huggsboson** [comment]
@krmayankk #18219 is one reason to allow them to be disabled.

**Comment by eroldan** [comment]
I came here after hours of debugging why a node app using Swagger library was generating his own URI as mydomain.tld:tcp://10.97.1.1:8082
These environment variables can clash with variables of own program or libraries, mainly SERVICENAME_PORT kind, generating unexpected problems and wasting operator time.
Being a broke (because ordering) discovery mechanism, my opinion is that this feature should be optional. Being able to disable it in the Service kind will resolve the situation still providing backwards compatibility.

**Comment by alkin** [comment]
@eroldan, I am having a similar issue. My app uses REDIS_PORT to connect to a redis database. Since the variable set by docker uses the tcp://IP:PORT format, i get the following error:

"unable to connect to tcp://redis:tcp://10.0.151.188:6379"

I believe having an option to disable the env variables would be a good solution to this problem.

**Comment by alexindigo** [comment]
We have use case, some apps (libs) try to pass _all available_ environment variables further downstream via arguments, and when we get to a certain number of containers in the cluster, it'd start to crash with `E2BIG` and we're unable to start any new container. So ability to disable it will go a long way. Thank you.

**Comment by dynek** [comment]
@alexindigo I had a similar issue with fcgi/php-fom and the workaround has been to unset all env variables before running it :-/

```for i in $(set | grep "_SERVICE_\|_PORT" | cut -f1 -d=); do unset $i; done```

**Comment by alexindigo** [comment]
Thanks @dynek, looks like this what I'd have to resort to. Hope there won't be naming conflicts. :)

**Comment by Stono** [comment]
I would like to +1 this, and validate the use case that they can cause code that runs perfectly fine locally to fail on k8s, due to env variables being quite commonly named they end up clashing with many scripts.

We need to be able to either turn them off, or have them prefixed with `K8S_`

**Comment by cablespaghetti** [comment]
Same issue as @alkin. Just spent quite a while workout out why I was getting an error for my redis.port property in my Java containers when I wasn't setting it. I guess I'll rename my redis service to something other than "redis". :(

**Comment by sgmiller** [comment]
Agreed.  This violates a security principle of providing only that information something needs to operate.  Should be a container or pod level attribute to disable or whitelist this information.

**Comment by PKJedi** [comment]
Ran into this as well, and debugging took a while.

In my case:

https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-env#L195

If I have something named node with an exposed port, the NODE_PORT env variable gets set for any rabbitmq container, causing it to CrashLoopBackOff

**Comment by RisingPhorce** [comment]
Three arguments against:
1.  Security:  If the container is compromised the attacker gets a nice list of services to try to pivot to and/or extract sensitive information from.  
2.  Scalability: Does this approach scale to 100's/1000's services?
3.  Least astonishment:  Behavior might be confusing in an environment with networking policies like calico.

**Comment by alexindigo** [comment]
@smarterclayton @deads2k  Wondering is there are other considerations that call for keeping it behavior as the only one available? I mean, introducing a flag that would be false by default, would be 100% backwards compatible, isn't it?

**Comment by termie** [comment]
oof, finally found this after hours of debugging, i am running a docker registry and the auth service is called "registry-auth" therefore creates a bunch of env vars that the container things are config values, super annoying to debug and since the advent of kube-dns it seems a bit superfluous

**Comment by vincentjorgensen** [comment]
I'm confused that this is closed. I don't expect environment variables in my container that I didn't explicitly set. Has this feature request been implemented in k8s now? Thanks.

**Comment by yivo** [comment]
@vincentjorgensen totally agree with you.

**Comment by huggsboson** [comment]
The issue was fixed in new versions of kube.  See #68754

**Comment by vincentjorgensen** [comment]
> The issue was fixed in new versions of kube. See #68754

Awesome @huggsboson. It doesn't seem to be in v1.12.0. Is is staged for a future release?

**Comment by huggsboson** [comment]
It looks like it was merged 14 days ago, so I'd expect it to be in the next release unless someone back ports it.

**Comment by huggsboson** [comment]
@bradhoekstra Does it make sense / is it possible to back port this feature to previous releases given the number of people wanting the new behavior?

**Comment by bradhoekstra** [comment]
@huggsboson My understanding is that new features are limited to minor releases; patch releases should be bug fix only. Since this didn't make it into 1.12 it will wait until 1.13.

**Comment by huggsboson** [comment]
@bradhoekstra Based on the comments, one could argue this is a bug fix.

I'm curious if it would be easy to backport or if code changes landing in the 1.13 timeframe made it easier to accomplish.

**Comment by nrvnrvn** [comment]
@bradhoekstra Is there a chance this could be reported back as a bug and the change backported as a bug fix to previous releases?
It is actually easy to backport but other than a mere PR what steps should be made?

**Comment by twbecker** [comment]
What's really frustrating is the only service vars that seem to be documented are $service_SERVICE_HOST and $service_SERVICE_PORT, when in fact there are lots of others that look like $service_PORT*. Can someone explain these or point to some docs that I was unable to find?

**Comment by bradhoekstra** [comment]
@twbecker https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

**Comment by twbecker** [comment]
@bradhoekstra thanks! Not sure how I missed this. Will definitely be nice when we can disable exposing those vars.
