### ISSUE TITLE
Azure Disk Detach are not working with multiple disk detach on the same Node. 

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#60101]
/kind bug

**What happened**:
I'm running a POD with three VolumeMount (AzureDisk PVC). If I delete the pod, it gets rescheduled on a different node. The 3 disks are unmounted from the original node (thanks to kubelet) and the disks are starting to get unattached from the VM.

Out of the three disks, only one was able to get unattached, it was properly reattached to the new node waiting to run the freshly restarted pod.

The other two Disks couldn't be detached. 

The controller manager keeps trying to attach from this point on while never trying to re-detach.

**What you expected to happen**:
Kube-controller-manager should retry detaching disks after failures.

**How to reproduce it (as minimally and precisely as possible)**:
* create a pod with 3 volume mounts (AzureDisk). 
* Kill the running pod.
* watch the status
If it works, retry

**Anything else we need to know?**:
kube-controller-manager logs (--v=4)

https://gist.github.com/djsly/3d934669f1a0db8f9a9a7d446f4962f9

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.12
- Cloud provider or hardware configuration: azure
- OS (e.g. from /etc/os-release): centOS 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.11.6.el7.x86_64
- Install tools: in-house (terraform + salt)

cc: @khenidak @feiskyer

**Comment by djsly** [comment]
/assign @feiskyer 

@feiskyer let me know if you need more logs.

**Comment by djsly** [comment]
[91d3b0a6-11b9-11e8-82b7-000d3a018ac3.log](https://github.com/kubernetes/kubernetes/files/1742540/91d3b0a6-11b9-11e8-82b7-000d3a018ac3.log)
[92317976-11b9-11e8-9620-000d3a017a13.log](https://github.com/kubernetes/kubernetes/files/1742541/92317976-11b9-11e8-9620-000d3a017a13.log)
[92972088-11b9-11e8-888f-000d3a018174.log](https://github.com/kubernetes/kubernetes/files/1742542/92972088-11b9-11e8-888f-000d3a018174.log)

Three disk ID.

one was detached / reattached properly

the other twos had errors since they were detached at the same time (3 concurrent detach, 1 pass, 2 fails)

After that the remaining two start looping with 
```
failed to detach azure disk "/subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174", err detach azure disk failure, disk  not found, diskURI: /subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174
```

**Comment by djsly** [comment]
This is one problem.
```
I0220 23:34:11.147986   73673 reconciler.go:231] attacherDetacher.DetachVolume started for volume "pvc-92972088-11b9-11e8-888f-000d3a018174" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174") on node "kn-edge-0"
I0220 23:34:11.150518   73673 operation_generator.go:714] Verified volume is safe to detach for volume "pvc-92972088-11b9-11e8-888f-000d3a018174" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174") on node "kn-edge-0"
I0220 23:34:22.153993   73673 attacher.go:147] azureDisk - VolumesAreAttached: check volume "<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174" (specName: "pvc-92972088-11b9-11e8-888f-000d3a018174") is no longer attached
I0220 23:34:22.154152   73673 operation_generator.go:173] VerifyVolumesAreAttached determined volume "kubernetes.io/azure-disk//subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/<rg_name>-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174" (spec.Name: "pvc-92972088-11b9-11e8-888f-000d3a018174") is no longer attached to node "kn-edge-0", therefore it was marked as detached.
```

the disk is still attached to the VM.

**Comment by djsly** [comment]
The problem is here. for managed disk, the diskName is empty, we should rely on diskURI to detect if a disk is attached. 

https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/azure/azure_controllerCommon.go#L263-L266

**Comment by djsly** [comment]
Azure Portal shows that a bunch of errors occurred, followed by three success. Each of those should have been the removal of a single disk. In the end, only 1 disk disappeared. 

<img width="508" alt="screen shot 2018-02-21 at 01 21 23" src="https://user-images.githubusercontent.com/4981802/36465938-a399e2a8-16a5-11e8-882c-d3bfffec156b.png">
<img width="591" alt="screen shot 2018-02-21 at 01 21 32" src="https://user-images.githubusercontent.com/4981802/36465939-a3abfc2c-16a5-11e8-878c-50ee22e78654.png">

My gut feeling is that the backoff logic doesn't refresh the list of disks to apply on the VM.

So we have three functions running all trying to delete a single disk. The deletion of performed using a VMUpdate call with a list of Disks (- the one we want to remove)

https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/cloudprovider/providers/azure/azure_controller_standard.go#L118

The new VM is construction based on the list of disks (-1)

https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/cloudprovider/providers/azure/azure_controller_standard.go#L128-L135

All three deletion logics start at the same time, causing race conditions with the azure api. 
`The request failed due to conflict with a concurrent request.`
or
`Cannot attach data disk 'cdb-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174' to VM 'kn-edge-0' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again.`

Eventually, the backoff logic will get through and the last VM update will re-add the two disks there were not part of the original deletion request. 

One solution could be to lock on disk deletion if they touch the same NodeName? Or queue the deletion request when an existing request is ongoing for the same node.

**Comment by andyzhangx** [comment]
@djsly you are right, there is no locking for detach disk, I will try to repro it and then use the locking fix to verify it, thanks for reporting.

**Comment by djsly** [comment]
@Andyzhangx let me know if you can’t reproduce. It’s easy for me. I could cook you up a  quick manifest.  

Thanks for looking into it.

**Comment by andyzhangx** [comment]
@djsly Your repro shows obvious evidence of race condition when detaching azure disk, I have commited a PR, pls take a look. Thanks for your reporting, it's really helpful.
