### ISSUE TITLE
Don't duplicate status in audit events

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#60108]
We [copy](https://github.com/kubernetes/kubernetes/blob/f8298702ffe644a4f021e23a616ad6a8790a5537/staging/src/k8s.io/apiserver/pkg/audit/request.go#L175) the `ResponseObject` into the `ResponseStatus` field of audit events. This was done to capture the response status even when the response is omitted, but results in (potentially large) duplicate data being sent. In some examples, the status message is repeated in the status details, resulting in a long message being duplicated 4 times.

I suggest that rather than copying the whole ResponseStatus, we selectively copy the bounded fields, specifically:
- status
- reason
- code

Note that this is a breaking change, and if there is agreement should be done before graduating audit to stable.

/kind bug
/sig auth
/priority important-soon

**Comment by jdumars** [comment]
Could you go ahead and add "approved-for-milestone" label to this, as well as status? That will help it stay in the milestone if this is a 1.10 blocker. Thanks!

**Comment by crassirostris** [comment]
Moving it to 1.11, together with graduating audit logging API to stable

**Comment by CaoShuFeng** [comment]
No one is working on this?
Mind if I assign it?

**Comment by tpepper** [comment]
@CaoShuFeng status check?  This has maybe gone dormant.  Is it still targeting 1.11?

**Comment by CaoShuFeng** [comment]
> @CaoShuFeng status check? This has maybe gone dormant. Is it still targeting 1.11?

Yes.
