### ISSUE TITLE
audit.Event.RequestObject underspecified for patch requests

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#60110]
The documentation on the [`RequestObject` field](https://github.com/kubernetes/kubernetes/blob/f8298702ffe644a4f021e23a616ad6a8790a5537/staging/src/k8s.io/apiserver/pkg/apis/audit/types.go#L117) of the `audit.Event` reads:

> API object from the request, in JSON format. The RequestObject is recorded as-is in the request
> (possibly re-encoded as JSON), prior to version conversion, defaulting, admission or
> merging. It is an external versioned object type, and may not be a valid object on its own.
> Omitted for non-resource requests.  Only logged at Request Level and higher.

This doesn't really fit the patch request model, which specifies an array of field operations rather than an actual object. E.g.
```
  "requestObject": [
    {
      "op": "replace",
      "path": "/spec/parallelism",
      "value": 0
    },
    {
      "op": "remove",
      "path": "/spec/template/spec/containers/0/terminationMessagePolicy"
    },
    {
      "op": "remove",
      "path": "/spec/template/spec/schedulerName"
    },
    {
      "op": "remove",
      "path": "/spec/template/spec/affinity"
    },
    {
      "op": "remove",
      "path": "/spec/backoffLimit"
    }
  ],
```

We should determine what the expected behavior is for a patch request. If this is working as intended, we should at least document this case.

/kind bug
/sig auth
/priority important-soon

**Comment by tpepper** [comment]
@tallclair even though you're suggesting not to, if you decide to push for this in 1.10 as per #58083 please remember to mark this one for the milestone.  I see you tentatively did on #60108 but not here.

**Comment by crassirostris** [comment]
I think it's hard to argue that these kind of requests is totally valid. I guess we have to just mention that in the documentation

**Comment by crassirostris** [comment]
Docs PR is merged, closing
