### ISSUE TITLE
High availability of Pods missing when nodes go down

### ISSUE THREAD

**Issue by K7king** [kubernetes/kubernetes#60120]
@kubernetes/sig-scalability
/sig scalability
**Is this a BUG REPORT or FEATURE REQUEST?**:
> kind bug

**What happened**: We created 20 node cluster on AWS EC2 where we created auto-scaling groups for the nodes and deployed 50 pods(with bare minimum resources). We manually terminated  18 of the VMs from AWS to check the high availability. But most of the pods were unavailable. 

**What you expected to happen**:
As 2 nodes were available, we expected that all the pods will be re-shuffled to the two existing nodes for the time being where AWS creates new VM's and once those becomes available, then again the pods will be reshuffled as per the availability.

**How to reproduce it (as minimally and precisely as possible)**:
Create 20 Node cluster in AWS and assign auto scaling groups to them.
Deploy good number (say 50) pods with bare minimum resources
From EC2 Console terminate 18 nodes and check the pods status using kubectl

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: AWS
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jhorwit2** [comment]
@K7king how long did you wait? The default timeout for evicting pods on failed nodes is 5 minutes, which can be set on the kube controller manager via the following flag. 

```
      --pod-eviction-timeout duration                                     The grace period for deleting pods on failed nodes. (default 5m0s)
```

> then again the pods will be reshuffled as per the availability

If i'm understanding you correctly, this won't happen. Once a pod is scheduled it won't be moved. Projects like the [descheduler](https://github.com/kubernetes-incubator/descheduler) plan to allow moving pods around to new nodes when certain conditions are met.

**Comment by wojtek-t** [comment]
> and deployed 50 pods(with bare minimum resources)

How did you deploy those pods?
If those were simple pods (not part of a deployments, ReplicaSet or sth like that), they won't be recreated - that's a core design principle for pods - once attached to a node, they are not moved.
