### ISSUE TITLE
The process to update portal IPs in ISCSI PVs.

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#60143]
**What happened**:

Suppose we filled the ISCSI PV spec and we have `TP` and `portal` as `IP1" and "IP2,"IP3` and the controller/node on ISCSI target of "IP3" failed or taken out for maintenance.  Currently this path is `always` failure from here on. Even if admin replaced this node or brought up a new node with new portal IP,  how can app pod make use of new path/IP ? or how can admin update ISCSI PV spec with the new portal IP?

**What you expected to happen**:
Provide a manual or automatic method to get the new portal listed in the ISCSI PV Spec or come up with a process to make use of new portal/IP.

**Comment by rootfs** [comment]
PV spec is expected to be immutable.

**Comment by humblec** [comment]
@rootfs true, but node replacement is a  requirement in an infra setup. Keeping that in mind, any workaround exist?. One thing which I can think of here is, admin can manually login to new target IP but this is not a solution as admin intervention is required at login time and also at logout time or pod schedule time again. Any other work arounds ?
