### ISSUE TITLE
[Proposal] enable azure cloudprovider to use EMSI certificate for authentication

### ISSUE THREAD

**Issue by rjtsdl** [kubernetes/kubernetes#60168]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
When install k8s on azure, we current depends on service principal (SPN) provided by user to get authentication to Azure cloud. The problem is, 
1. We left secrets on the node
2. Hard to manage SPN (note, SPN also has expiration time)

**What you expected to happen**:
Azure Identity team is working on **explicit managed service identity** (EMSI) feature. It takes over the managed part. And it give you a single identity as Azure resource to manage.

We need to add support for Azure cloudprovider to be able to use EMSI to authenticate with Azure. My proposal would be, add an optional flag in azure.json file
```
UserAssignedID  string `json:"userAssignedID"`
```

Azure already have a flag `UseManagedIdentityExtension`. (it was introduced before, for implicit managed service identity)

```
if UseManagedIdentityExtension == true {
      if UserAssignedID is valid {
            using EMSI
      } else {
            using Implict MSI
      }
} else {
     using SPN
}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rjtsdl** [comment]
@jdumars @khenidak TAL

**Comment by djsly** [comment]
cc: @eghobo, security team will be happy ;)

**Comment by andyzhangx** [comment]
@karataliu

**Comment by feiskyer** [comment]
Added in https://github.com/kubernetes/kubernetes/pull/66180.

/close
