### ISSUE TITLE
Pod startup errors bork StatefulSet rolling update

### ISSUE THREAD

**Issue by FUDCo** [kubernetes/kubernetes#60164]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

I'd like to think this is a bug, but I fear it may actually be a feature request.

**What happened**:

Pod startup failed during creation of or rolling update to a StatefulSet (for any of a number of reasons, e.g., a typo in an image name, or just a crash bug in the code being run).  Rollout remains stalled even if the update is rolled back or if the StatefulSet is updated again with a corrected image.  The only way to recover is via manual intervention (e.g., delete the pod that was failing, causing it to be recreated in the corrected state, and allowing subsequent pods to start).

**What you expected to happen**:

I expected updating the StatefulSet configuration with a corrected or reverted image spec to correct the problem.

**How to reproduce it (as minimally and precisely as possible)**:

(1) Define and create a StatefulSet with 2 replicas of a single container pod with some **non-working** image.
(2) Observe that StatefulSet comes up with pod 0 in a restart loop (e.g., Waiting: CrashLoopBackOff) and pod 1 does not start.
(3) Patch the StatefulSet to update the image to a **working** image.
(4) Observe that the condition of the pods does not change, even though the StatefulSet is now configured with the new, corrected image.
(5) Manually delete pod 0.
(6) Observe that pods 0 and 1 now both come up successfully running the new image.

Alternatively:

(1) Define and create a StatefulSet with 2 replicas of a single container pod with some **working** image.
(2) Observe that StatefulSet comes up with pods 0 and 1 both running successfully.
(3) Patch the StatefulSet to update the image to a **non-working** image.
(4) Observe that pod 1 is updated to the new image and goes into a restart loop (e.g., Waiting: CrashLoopBackOff) while pod 0 remains running the old image.
(5a) Patch the StatefulSet again to update the image to a third, **working** image.
(5b) Revert the image change in step (3), e.g., using `kubectl rollout undo`
(6) Observe that the condition of the pods does not change, even though the StatefulSet is now configured with the new, corrected image.
(7) Manually delete pod 1.
(8) Observe that pods 0 and 1 now both come up successfully running the new image.

**Anything else we need to know?**:

To my sensibilities this is just a bug: why would StatefulSet support rolling updates at all if there's no way for it to handle the failure case?  However, as I mentioned above, I fear this is actually a feature request.  Our use case is a CI/CD system, so end-to-end automation is essential.  I'm sure that with some effort we could implement the necessary monitoring and intervention by automated means via a kludgy combination of polling and timeouts, but the whole reason for switching to Kubernetes in the first place was to avoid having to write and debug that kind of fussy and error prone stuff.  StatefulSet seems to be in exactly the right place to know what needs to be done and to do it, but unfortunately it now appears to only handle the happy path.

Edited to add: Another manual intervention that is effective: rather than deleting the pod that is stuck in a restart loop, directly update the image in the pod itself.  This will result in a working pod and allow the rollout to resume.  Note that there is nothing that requires the image so used to be the same image as the one that the StatefulSet was updated with, but if this image update were to be done by the StatefulSet controller we'd get exactly the behavior I'd like to see.  From an uninformed outsider's perspective this seems like a small change to the rolling update logic.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration/OS/etc: Mac OSX running minikube v0.24.1

**Comment by lavalamp** [comment]
This is not api machinery or architecture.

/sig workloads

**Comment by lavalamp** [comment]
(I guess it's sig apps now)

**Comment by cloudbow** [comment]
How are others doing this. Is this fixed in some version of k8s

**Comment by svitlanacs** [comment]
+ 1 on experiencing problem so that the thread does not get stale.

Another alternative "solution" is to transfer over to Deployment + PV instead of StatefulSet.

**Comment by tonglil** [comment]
This is still an issue, is there a documented workaround or otherwise workflow that can allow update to a crashing STS to recover?

/reopen

**Comment by aiman-alsari** [comment]
This is an annoying issue as it requires manual intervention, and can really bog down a team that relies on automated workflows. I +1 reopening this

**Comment by rmb938** [comment]
I have also ran into this issue and cannot find a way to recover the statefulset without loosing the pv to pod mapping. This is very unfortunate and going to cause data loss trying to fix.

**Comment by lavalamp** [comment]
/reopen
/lifecycle-frozen

I personally have experienced this issue and agree it's super annoying.

**Comment by jturolla-nubank** [comment]
I can reproduce this issue, this is one of the biggest operational overheads in our setup. We usually delete the pod after the patch for a new image. 

> I have also ran into this issue and cannot find a way to recover the statefulset without losing the pv to pod mapping. This is very unfortunate and going to cause data loss trying to fix.

I cannot reproduce losing the pv to pod mapping.

**Comment by falmar** [comment]
Experiencing same issue with Kubernetes 1.12.2. Annoying to intervene and worse if it is a Production workload

**Comment by hossainemruz** [comment]
Experiencing same issue with Kubernetes 1.13.3. Any progress here?

**Comment by krmayankk** [comment]
@kow3ns  FYI

**Comment by falmar** [comment]
Everything points that this may be an intended behaviour.

My use case is a node going down or becomes unreachable, not sure if the scheduler is unable to determine the cause of the pod status and making the right decision, becuase evicting the pod to schedule it somewhere else could be a problem in case your pod's state depend on that node's file system.

Although my pods state is backed by block-storage, I want them to fail fast and be scheduled somewhere as the block-storage could be detached from source node and attached to new destination  node... but if there is no guarantee that CSI will be able to communicate the source node and make the detach happen or if the attachment will happen in 10s or 1h. all sort of problems can come along

I actually may need a different controller, the ordinal updates does not work well for quorum based system when I need the leader to be updated last, otherwise will have a several leader elections :(

**Comment by acondrat** [comment]
I can still see this in 1.14. Should we reopen this issue?

**Comment by vbence** [comment]
> Should we reopen this issue?
Yes, please

**Comment by kmangla9** [comment]
/reopen
/lifecycle-frozen

I am facing this same issue with 1.15. 
I need this on production for my project, I do not want any manual intervention. It is super annoying to manually delete pods/statefulsets and redeploy them.

**Comment by FUDCo** [comment]
> @kmangla9: You can't reopen an issue/PR unless you authored it or you are a collaborator.

Your wish is my command...

/reopen

**Comment by llussy** [comment]
I am facing this same issue with 1.24.

**Comment by vl-kp** [comment]
should we reopen this issue?

**Comment by FUDCo** [comment]
/reopen

I think there's a process issue here.  Automatically closing an issue If developers just ignore it for 3 months is astonishingly dysfunctional.  Closing your eyes does not make the problem go away.

It's been more than 5 years...
