### ISSUE TITLE
Need e2e or integration test for endpoints

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6020]
After #5939 goes in, we need an automatic test.  Filing now so as to not forget.

Specifically the repacking functionality needs a test to ensure we don't regress there.

**Comment by marekbiskup** [comment]
e2e test for multiport services is in #7970
Repacking test (integration) still missing.

**Comment by marekbiskup** [comment]
DNS test was moved to another file in #8230. This reduced the coverage of services tests. The discussion was the following:

From @thockin:
> The problem with removing it is that we now have no case in the service test that covers UDP, nor a case that covers multi-port services.

> We should at least leave a TODO here saying "TODO: We get coverage of TCP/UDP and multi-port services through the DNS test. We should have a simpler test for multi-port TCP here, at least.

From @marekbiskup:
> I must say I'm a bit lost. Is DNS the multiport service that is tested here? (tested by dig)
> Shall I test a custom service (like a web server created in a pod, with multiple ports)?

> One more thing:
> If I create the custom multiport service and then get data from it, shall I:
> A. read the data from the test client (like  c.Get().Prefix("proxy").Resource("services").Namespace(ns).Name(service.Name); btw, is there a way to specify the port?), Or:
> B. create another pod that reads the data using service name and port, resolved by DNS?

From @thockin 
> Yes, DNS is a multi-port service, so that's giving us coverage of the feature.  Creating our own service with 2 ports (which is what you were doing, right?) and testing it all the way through would be a good subsititute.

**Comment by marekbiskup** [comment]
@thockin, could you suggest the way of accessing service ports?

I think if I go with option B, I'll be still using the DNS and I don't know the reason why DNS test was moved away - I suppose DNS is not available in some cases(?).
Shall I proceed with option A? Will it generate the required coverage? How can I specify the port in this case?

**Comment by marekbiskup** [comment]
@thockin, I discussed the test with @piosz and I think can handle it without further directions from your side.

The plan is the following:
1. create a pod that would serve a given string at a given port
2. create a multiport service
3. verify that the correct string is served from each port of the service. (connect from the client and use API, not service name in DNS)

**Comment by thockin** [comment]
That sounds right to me.  Thanks!

**Comment by piosz** [comment]
Should this be closed?

**Comment by thockin** [comment]
I think so ?

**Comment by marekbiskup** [comment]
AFAIR, the reason why this isn't closed is that the tests only get the endpoints from the api server - they don't try to access them.
We wanted to create a test that also checks if pods are serving under the endpoints.

I suppose we have many other tests for this, so maybe we can close it.
