### ISSUE TITLE
hi,  what is the better way to know a pod‘s ip  if pod’s ip change？

### ISSUE THREAD

**Issue by derek0377** [kubernetes/kubernetes#60205]
hi,  what is the better way to know a pod‘s ip  if pod’s ip change？
watch etcd or some way else?

thanks very much!

**Comment by krmayankk** [comment]
@derek0377 here are some ways you can get help https://kubernetes.io/community/ .

**Comment by krmayankk** [comment]
closing this, since github issues are meant to report issues or create discussion on a feature.
/close
