### ISSUE TITLE
PV describe formatting issue

### ISSUE THREAD

**Issue by narkarum** [kubernetes/kubernetes#60203]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

```
Name:            pvc-f6d0523f-e01c-11e7-95c5-e25476aff4b0
Labels:          status=
                 volumeId=5df78942-ee33-49c0-8454-271faa139a20
Annotations:     pv.kubernetes.io/provisioned-by=ibm.io/ibmc-genesis-block
                 volume.beta.kubernetes.io/storage-class=ibmc-genesis-block-bronze
StorageClass:    ibmc-genesis-block-bronze
Status:          Pending
Claim:           default/claim1-genesis-block-bronze
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        2G
Message:         
Source:
    Type:    FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:      Options:  %v

    FSType:                                           ibm/ibmc-genesis
    SecretRef:                                        
    ReadOnly:                                         <nil>
%!(EXTRA bool=false, map[string]string=map[])Events:  <none>
```

**What you expected to happen**:

Source part should be well formatted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Ubuntu 16.04
- Kubernetes version (use `kubectl version`): 1.9.*/1.8.*
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
- Kernel (e.g. `uname -a`):

- Install tools:
- Others:

**Comment by stewart-yu** [comment]
It fixed in `release-1.10`, not cherry-pick to 1.9 and 1.8.
