### ISSUE TITLE
HA Kubernetes on Ubuntu

### ISSUE THREAD

**Issue by Venkat-Sudharsanam** [kubernetes/kubernetes#60207]
/kind bug

**First created a cluster with 1 master node.

And i tried to add other 2 master nodes. As documented in https://docs.google.com/document/d/1rEMFuHo3rBJfFapKBInjCqm2d7xGkXzh0FpFO0cRuqg

In master 1, i can see the other server as master.

But in the other servers im unable to perform commands like kubectl get nodes. Getting the below error:

kubectl get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: GCloud
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 

uname -a
Linux kub2 4.13.0-1008-gcp #11-Ubuntu SMP Thu Jan 25 11:08:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by mbert** [comment]
See recent addition to [Adding HA to kubeadm-deployed clusters](https://docs.google.com/document/d/1rEMFuHo3rBJfFapKBInjCqm2d7xGkXzh0FpFO0cRuqg):

Set up kubectl: 

		$ export KUBECONFIG=/etc/kubernetes/admin.conf

You may want to add the above line to ~/.profile or similar.

**Comment by Venkat-Sudharsanam** [comment]
@mbert  man you are awesome.

Thanks that worked

**Comment by jhorwit2** [comment]
@Venkat-Sudharsanam since it seems you have resolved this issue i'm closing this. If it should be reopened let me know. 

/close
