### ISSUE TITLE
[Feature Request] - Add a "cronProbe"

### ISSUE THREAD

**Issue by wgordon17** [kubernetes/kubernetes#60217]
/kind feature

I would like to have considered a "cronProbe" that supports cron-like scheduling, but be able to be run within the context of a container. The use case for this is to be able to run maintenance commands against a running container, without having to rely on an external pod/system to `oc exec` into the container. A livenessProbe can essentially already to this today, as long as the maintenance commands don't fail or timeout.

My proposal would be for the addition of a field to [probe](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#probe-v1-core) that can be used _instead of_ `periodSeconds`, something called `schedule` (stolen from the naming of [cronjob](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#cronjobspec-v1beta1-batch)).

An array would also have to be added to [container](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#container-v1-core) called "cronProbe", which can take a list of probes.

Also, the failure of a "cronProbe" should not be considered something that requires a kill and restart of the pod.

Some use cases are potentially be able to take data backups from RWO volumes, sending reports on a schedule, curling a link to let an application perform cron (like Drupal), running a maintenance command within a pod, e.g. DBMS organization or something like [`php artisan run`](https://stackoverflow.com/questions/48866257/openshift-3-cronjob-inside-running-container).

**Comment by sferich888** [comment]
I think @kubernetes/sig-scheduling-feature-requests is the right SIG for this?

**Comment by wgordon17** [comment]
Hey all, @kubernetes/sig-scheduling-feature-requests, any suggestions on this particular RFE?
