### ISSUE TITLE
Accessing clusterIP services from a pod on the same node fails in ipvs proxy mode

### ISSUE THREAD

**Issue by prameshj** [kubernetes/kubernetes#60257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
When a service of type externalName is setup, a test pod doing a DNS lookup of that externalName gets No Response in some cases. Upon investigation, I found that failure happens if the test pod request is sent to kube-dns pod running on the same node. If the request is load-balanced and sent to a different kube-dns pod on another node, the lookup is successful. 
I do not see this problem with iptables mode.

I think the error is because of the stage at which DNAT happens in iptables vs ipvs. In iptables mode, the request with dest ip as the cluster ip of kubedns is DNAT'ed in PREROUTING stage, so when route lookup happens, the destination has already changed to the pod IP.

However in ipvs case, the DNAT seems to be happening AFTER the route lookup, so the packet hits the EBTABLES OUTPUT chain which drops the packet. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Rerunning this test - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/465#sig-network-dns-should-provide-dns-for-externalname-services
The failure happens if the test pod doing the DNS lookup talks to kube-dns pod running on the same node. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by prameshj** [comment]
The bug was found when running the sig-networking dns test, but it is not specific to DNS. Anytime a pod reaches out to a clusterIP service which is DNAT'ed to a pod on the same node, we will see the problem.

**Comment by prameshj** [comment]
One possible fix is to use the hairpin-veth mode as default, we don't need the ebtables rules in that case.
https://github.com/kubernetes/kubernetes/pull/60166 makes the change to the default mode.

/cc @rramkumar1 @freehan @m1093782566

**Comment by m1093782566** [comment]
/cc @Lion-Wei 

@prameshj Are you using kubenet?

hairpin issue is resolved by #54219 - I tested it with calico.

**Comment by Lion-Wei** [comment]
I think the test"ci-kubernetes-e2e-gci-gce-ipvs" is definitely using kubenet, and some other failed cases in this test is also the same reason. This only happened in clusters which use kubenet as networkPlugin, but I haven't find the root cause... : (

**Comment by prameshj** [comment]
Yes, i am using kubenet and the cluster running the tests is also using kubenet like you pointed out.

**Comment by m1093782566** [comment]
@prameshj 

Would you please change the hairpin mode config in GCE setup to `hairpin-veth` to fix the CI errors in https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ipvs if #60166 can't get in at this release circle?

**Comment by prameshj** [comment]
We can try changing that temporarily to see how many tests pass in that mode. I only found one test failure that pointed to this issue. I suspect there might be other issues too, that need to be investigated.

**Comment by m1093782566** [comment]
Yeah, it would be great.

**Comment by prameshj** [comment]
https://github.com/kubernetes/test-infra/pull/7163

**Comment by rramkumar1** [comment]
Looks like switching back to hairpin-veth as the default fixed this (#60166). We can reopen if necessary.
/close
