### ISSUE TITLE
Cross build failed because of ne.Exec

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#60266]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Cross build failed:

```
# k8s.io/kubernetes/pkg/util/io
pkg/util/io/writer.go:61:21: cannot use echoArgs (type []string) as type string in argument to ne.Exec
pkg/util/io/writer.go:71:29: cannot use chmodArgs (type []string) as type string in argument to ne.Exec
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cblecker** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/60214
