### ISSUE TITLE
Windows containers creation failed because of rslave mounts

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#60274]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Windows containers creation failed because of rslave mounts.

```
 Error: Error response from daemon: invalid bind mount spec "c:\\var\\lib\\kubelet\\pods\\a260a7c4-1852-11e8-bb1d-000d3a19c1da\\volumes\\kubernetes.io~secret\\default-token-rj7qv:c:/var/run/secrets/kubernetes.io/serviceaccount:ro,rslave": invalid volume specification: 'c:\var\lib\kubelet\pods\a260a7c4-1852-11e8-bb1d-000d3a19c1da\volumes\kubernetes.io~secret\default-token-rj7qv:c:\var\run\secrets\kubernetes.io\serviceaccount:ro,rslave'
```

**What you expected to happen**:

Windows containers don't support mount propagation, we should disable it for windows.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@feiskyer What's your pod config for `rslave` mount?

**Comment by jdumars** [comment]
@michmike if you agree with this as a blocker for 1.10, could you go ahead and add "approved-for-milestone" label to this, as well as status? That will help it stay in the milestone.

**Comment by feiskyer** [comment]
> @feiskyer What's your pod config for rslave mount?

@andyzhangx  Any pods on Windows would meet same issue. It defaults to rslave now on master branch.
