### ISSUE TITLE
Move Taints and Tolerations to GA

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#60281]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

Taints and tolerations is a beta feature in Kubernetes 1.9. We would like to move it to GA status in 1.10.
My initial investigations show that we only need to update the docs to mention that it is GA.

Task tracker:
* [x] Update kubernetes.io and remove notions of the feature being Beta.

/sig scheduling
/assign

**Comment by jdumars** [comment]
Thank you for getting the docs in place for this. Could you go ahead and add "approved-for-milestone" label to it, as well priority and status?  That will help it stay in the milestone.

**Comment by jberkus** [comment]
Increasing priority to critical-urgent since we are now in Code Freeze.  Please update the issue regularly with status information.

/priority critical-urgent

**Comment by bsalamat** [comment]
I think we can close it. Not much needed to be done other than updating the docs and docs are already updated.
