### ISSUE TITLE
Allow setting labels when running kubectl create configmap/secret --from-file

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#60295]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What you expected to happen**:
When issuing `kubectl create configmap --from-file=...`, I'd like to be able to set labels on the created map instead of having to run a separate.
Having the same ability when creating generic secrets would also be useful.

/sig cli

**Comment by thomas-riccardi** [comment]
I encountered this need too:
I use `kubectl create configmap --from-file=foo --dry-run=true --output=yaml > foo.yaml` to generate a manifest file (alongside others), then call `kubectl apply` on multiple manifest files at once.
For pruning, I need to add a label on all resources, including the ConfigMap, otherwise it's just completely ignored by `kubectl apply`.
(full command: `kubectl apply --filename=foo-cm.yaml --filename=foo-deploy.yaml --prune=true --selector=service=foo`)

**Comment by karthikvadla** [comment]
any update on this?

**Comment by StevenACoffman** [comment]
This would be nice. Alternatively:
```
kubectl create configmap --from-file=... --overrides='{"metadata":{"label":"app": "awesomeapp"}}'
```

**Comment by hoeghh** [comment]
A workaround could be 

```
kubectl create configmap my-config --from-file=dashboards/ 
kubectl label  configmap my-config app=grafana
```

**Comment by prune998** [comment]
one year for this "simple" feature ? 
Will have to use kustomize instead...

**Comment by hdpdevops** [comment]
I was looking for this too. I ended up using `yq` like this:

`kubectl create configmap grafana-dashboard-nginx-json --from-file nginx.json --dry-run -o yaml | yq w - metadata.labels.grafana_dashboard 1 | kubectl apply -f -`

**Comment by nvtkaszpir** [comment]
you can create configmap and then patch it:

```shell
kubectl create configmap nginx-ingress-controller.json \
  --from-file=nginx-ingress-controller.json \
  --dry-run \
  --output yaml \
  | kubectl apply -f -

kubectl patch configmap nginx-ingress-controller.json \
  -p '{"metadata":{"labels":{"grafana_dashboard": "1"}}}'
```

**Comment by erwbgy** [comment]
Or even easier:
`
kubectl create configmap nginx-ingress-controller.json --from-file=nginx-ingress-controller.json \
&& kubectl label configmap nginx-ingress-controller.json grafana_dashboard=1
`

though it would be much nicer to be able to use --overrides directly like @StevenACoffman says above.

**Comment by luigi-riefolo** [comment]
Maybe I can help.
/assign

**Comment by tatsuhiro-t** [comment]
I encountered this issue too and found that kubectl label --local is quite handy:

```
$ kubectl create cm foo -o yaml --dry-run|kubectl label -f- --dry-run -o yaml --local f=b
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    f: b
  name: foo
```

and you can pipe it to kubectl apply -f- to send it to server.

**Comment by dsayan154** [comment]
@tatsuhiro-t when I pipe the output to kubectl label -f- --dry-run -o yaml --local, the metadata.namespace is getting overriden

**Comment by MartinSoto** [comment]
Any updates on this? Looks simple enough to me.

**Comment by luigi-riefolo** [comment]
the PR has never been reviewed, I don't know why.

here's the link:
https://github.com/kubernetes/kubernetes/pull/82986

**Comment by StevenACoffman** [comment]
Try rebasing it instead of merging?

**Comment by luigi-riefolo** [comment]
@StevenACoffman done

**Comment by soltysh** [comment]
See https://github.com/kubernetes/kubernetes/pull/82986#pullrequestreview-766536338
/close

**Comment by makusu2** [comment]
@soltysh Why?

**Comment by soltysh** [comment]
> @soltysh: Closing this issue.

@mpuckett159 brought it up during sig-cli last Wed, so you can check recording, but to leave a written word for others looking for answers. The short story is that all of the create sub-commands are meant as a starting point only and not full-featured command. One of the reasons for that is that we want the create sub-commands to be an entry point for newcomers to the ecosystem, whereas having multiple flags is causing a lot of confusions. 
Additionally, the fact that you can easily pipe a few commands together (here `kubectl create` with `kubectl label`) is sufficient for such use-cases. Lastly, for all production use-cases I'd encourage folks to switch to declarative (ie. `kubectl apply`) flow, see https://youtu.be/eOxy1PS5TyQ?t=780 for more details.
