### ISSUE TITLE
Do we need addon about Linkerd?

### ISSUE THREAD

**Issue by MengZn** [kubernetes/kubernetes#60309]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

I noticed there is istio example in cluster / addons.

Do we need addon's example of Linkerd?

**Anything else we need to know?**:

If we have such needs, I volunteered to accomplish this task.

**Comment by kow3ns** [comment]
@MengZn what is the value of adding this to kubernetes core vs contributing to the examples hosted at the 
[linkderd project](https://github.com/linkerd/linkerd-examples/tree/master/k8s-daemonset)?
