### ISSUE TITLE
Resizing GlusterFS PVC not working

### ISSUE THREAD

**Issue by alvarosIGZ** [kubernetes/kubernetes#60300]
/kind bug

**What happened**:
Hello.
So I have Kubernetes v1.9.2 installed via kubeadm with GlusterFS as persistent storage.
I can do create and delete pvc, and everything seems to work fine.
I've read that you can resize pvc but adding some properties to kube-apiserver. So I've edited and redeployed with feature-gates and the admission controller.
Then I create a storage class with the property allowVolumeExpansion: true, and a PVC associated to that SC.
When I edit the PVC, I can edit, it says edited, but nothing happens.
I've checked kubernetes master logs, heketi logs, and no logs and no errors.

**What you expected to happen**:

It fires a resize event and the pvc is resized.

**How to reproduce it (as minimally and precisely as possible)**:

Kubernetes 1.9.2 baremetal with glusterFS as persistent storage.

**Anything else we need to know?**:
I've been talking with @humblec and we've checked all the installation is fine, no error or misconfiguration.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.2

- Cloud provider or hardware configuration:

bare-metal CentOS. Installed with kubeadm.

- OS (e.g. from /etc/os-release):

- Kernel
Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by humblec** [comment]
@alvarosIGZ has enabled the feature gates and also enabled `allowVolumeExpansion`, the blocking point here is that, he is not seeing any logs when he edit the PVC in his master logs, also no notification in heketi about volume expand request. Not sure whats going wrong. @gnufied any thoughts on why the resize call is not reaching to glusterfs resizer?

**Comment by gnufied** [comment]
You have to start api-server, controller-manager both with feature gate enabled. Can you do: `ps aux` and print exact arguments with which they are running?

**Comment by alvarosIGZ** [comment]
So I updated controller-manager with feature-gates (I didn't have) and now it's working!! 
So thank you for the help
