### ISSUE TITLE
pull-kubernetes-e2e-kops-aws fails to pull apiserver image

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind flake
> /kind feature

**What happened**:
I got inconsistent results from pull-kubernetes-e2e-kops-aws regarding #60065 (see https://k8s-gubernator.appspot.com/pr/60065).  That test succeeded once and failed several times on the exact same commit.  I looked at a few of the failures.  They are not all the same, but a common problem is failing to pull the apiserver image due to an authorization failure.  See https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-e2e-kops-aws/76217/artifacts/54.242.232.237/kubelet.log and https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-e2e-kops-aws/75802/artifacts/35.172.194.120/kubelet.log for examples.  Here is the critical excerpt from the latter:
```
E0222 01:20:48.227370    1877 remote_image.go:108] PullImage "k8s.gcr.io/kube-apiserver:v1.8.9-beta.0.10_6852b6abe14e9f" from image service failed: rpc error: code = Unknown desc = unauthorized: authentication required
E0222 01:20:48.227398    1877 kuberuntime_image.go:50] Pull image "k8s.gcr.io/kube-apiserver:v1.8.9-beta.0.10_6852b6abe14e9f" failed: rpc error: code = Unknown desc = unauthorized: authentication required
```

**What you expected to happen**:
I expected consistent results from the testing.  I expected the test infrastructure to be able to create and use the Docker images involved.

**How to reproduce it (as minimally and precisely as possible)**:
Submit a PR that modifies the `release-1.8` branch of k8s.io/kubernetes.  (I did a PR against `master` and did not have this problem.)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
I see everything being pushed to the standard publicly readable bucket here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-e2e-kops-aws/76217/

@krzyzacy @justinsb should it even be pulling from k8s.gcr.io since we're using images from a PR?
This smells like a kops issue, kubetest appears to be building and pushing the images properly.

**Comment by krzyzacy** [comment]
/sig aws
@justinsb something need to be cherrypick back to 1.8?

**Comment by ixdy** [comment]
Oh, maybe.

I think kops side-loads the docker images, and so while k8s.gcr.io is an alias that resolves to gcr.io/google-containers on the GCR side, it isn't considered an alias in the local docker daemon.

I'm guessing kops is configured to look for the local docker images under the k8s.gcr.io registry, but 1.8 is probably still building the side-loaded images as gcr.io/google-containers.

OTOH I'm not sure how we coordinated the switch from gcr.io/google-containers to k8s.gcr.io for kops in the first place.

**Comment by MikeSpreitzer** [comment]
What is the thinking about what to do about this?

**Comment by chrislovecnm** [comment]
It does not make sense that a pull from a registry is flakey. It is a docker pull, so if the comtainer is there and the registry is happy it should work. Is this happening with 1.10 or 1.11 testing as well?

**Comment by chrislovecnm** [comment]
Also authorization require message is coming from the registry itself. This is an odd issue.

**Comment by justinsb** [comment]
Is this still happening? It should have been fixed by https://github.com/kubernetes/kops/pull/4494

**Comment by MikeSpreitzer** [comment]
I think this is fixed, I have not suffered this problem recently.
