### ISSUE TITLE
apimachinery passes through Unstructured in inconsistent ways

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#60312]
In https://github.com/kubernetes/kubernetes/pull/55650 support for `runtime.Unstructured` was added to `runtime.Scheme`. With https://github.com/kubernetes/kubernetes/pull/60113 we have to support `Unstructured` with custom typers and converters using `GroupVersions` that are not known to our legacy schemes. This is broken right now:

The versioning codec https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L171 ignores conversions for `Unstructured`. 

kubectl makes heavy use of this bug by using legacy codecs bound to the legacy scheme, but passing `Unstructured` objects with arbitrary GroupVersion to them. This fails because the scheme does not know the input GroupVersion. As a consequence not even the identity conversion is done (which would also be wrong if the target version is different).

Hence, if we can make the versioning codecs more strict (compare https://github.com/kubernetes/kubernetes/pull/60201) and add `Unstructured` conversion (needed for CRDs https://github.com/kubernetes/kubernetes/pull/60113), this leads to many broken kubectl tests.

Probably, we have to add the old `Unstructured` behaviour to the kubectl legacy codecs (e.g. using a wrapper). But even this is questionable.

**Comment by sttts** [comment]
This is a blocker for conversion support in CRDs.

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
@sttts was this resolved by https://github.com/kubernetes/kubernetes/pull/60201?

**Comment by sttts** [comment]
@liggitt unfortunately only part of it. I found another situation where `Unstructured` is not handled consistently. Will create a PR soon.

**Comment by liggitt** [comment]
@sttts @mbohlool did the last bits of this get flushed out by the CRD versioning work?

**Comment by sttts** [comment]
Should be fixed with the versioning work.

/close
