### ISSUE TITLE
couldn't initialize a Kubernetes cluster

### ISSUE THREAD

**Issue by srinil** [kubernetes/kubernetes#60322]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
        - There is no internet connection, so the kubelet cannot pull the following control plane images:
                - gcr.io/google_containers/kube-apiserver-amd64:v1.9.1
                - gcr.io/google_containers/kube-controller-manager-amd64:v1.9.1
                - gcr.io/google_containers/kube-scheduler-amd64:v1.9.1

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'
couldn't initialize a Kubernetes cluster
**What you expected to happen**:
successful initialization of  Kubernetes cluster 
**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.1
- Cloud provider or hardware configuration: NA
- OS (e.g. from /etc/os-release): redhat 7
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:

**Comment by dgabrysch** [comment]
What does "systemctl status kubelet" say?

**Comment by dgabrysch** [comment]
Do you have an internet connection?

**Comment by srinil** [comment]
hi,
kubelet.service  - kubelet: The Kubernetes Node Agent
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/kubelet.service.d
               10-kubeadm.conf
Active: active (running) since Fri 2018-02-23 15:33:18 EST; 1 day 4h ago
Docs: http://kubernetes.io/docs/
Main PID: 2445 (kubelet)
CGroup: /system.slice/kubelet.service
               2445 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet/conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path/etc/kube
 here loaded manually in to the local  docker repository , All those images exits in the local  docker repository in the system 
Thanks,
Srinil

**Comment by dgabrysch** [comment]
Does kubelet report any errors in the journal?

**Comment by srinil** [comment]
getting below errors
t/kube let. go :465: Failed to list Rv1. Service: Ge 2051 k8s. io/kubernetes/pkg/kubelet/config/apiserver. go:47 to list *v1. Node: Get h Failed to list Failed 2005] to list *v1. Pod nable to update cni Failed to list Ge config: No networks found in *vi. Node Get h /etc/cni/net. d o 51 container runt ime network not ready: NetworkReady false 2051 205j on 47 Failed to list *v1.pod 205 k8s.io/kubernetes/pkg/kubel :465 Failed to list Service: Ge et/kubelet. go:474 Failed to list *v1. Node: Get h 205 k8s.io/kubernetes/pkg/kubelet/kubelet. server. 47: Failed to list Rv1. Pod 205 i go :465: Failed to list service: Ge ger go: 2381 eviction manager 474 Failed to list w Node Get h vi unexpected err failed to get node info: node "vdlu 2005] 8s.io/kubernet Failed to list *v1. Pod 205] k8s.io/kubernetes/pkg/kubelet/kubelet. go:465: Failed to list *v1. Service Ge 205] k8s. io/kubernetes/pkg/kubelet go :474 Failed to list sev Node Get h et/kubelet,

**Comment by dgabrysch** [comment]
Ok, those are normal at bootstrapping. What about docker? In the kubelet logs, is there something like "failed to pull" or something? Oh and what is important are the "pause" containers,  did you prepull these images too?

**Comment by srinil** [comment]
gcr.io/google-containers/kube-apiserver-amd64 v1.9.1
gcr.io/google-containers/kube-scheduler-amd64 v1.9.1
gcr.io/google-containers/kube-proxy-amd64 v1.9.1 
gcr.io/google-containers/kube-controller-manager-amd64 v1.9.1
gcr.io/google-containers/k8s-dns-sidecar-amd64  1.14.5
gcr.io/google-containers/k8s-dns-kube-dns-amd64 v1.9.1
gcr.io/google-containers/k8s-dns-dnsmasq-nanny-amd64 1.14.5
gcr.io/google-containers/etcd-amd64  3.0.17
gcr.io/google-containers/pause-amd64 3.1

above are the images i prepulled . i am not seeing any error related to container pull
there are one additional error i am seeing kubelet_node_status unable to register node  node1 ith API server Post get  socketopt : connection refused - its 6443 port

**Comment by dgabrysch** [comment]
That error is normal,  kubelet waits for an api connection. I don't have any more idea, don't know how the OS is set up and so on:/

**Comment by srinil** [comment]
what else i can check, to make this run, 
OS  redhat 7
Kernel: 3.10

**Comment by dims** [comment]
please try https://github.com/kubernetes/kubeadm/issues

/close
