### ISSUE TITLE
pull-kubernetes-cross is failing

### ISSUE THREAD

**Issue by rvkubiak** [kubernetes/kubernetes#60335]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Testing my PR the pull-kubernetes-cross test failed to run 'make release'.
https://github.com/kubernetes/kubernetes/pull/60175
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60175/pull-kubernetes-cross/7264/

I0222 20:04:59.204] # k8s.io/kubernetes/pkg/util/io
I0222 20:04:59.205] pkg/util/io/writer.go:61:21: cannot use echoArgs (type []string) as type string in argument to ne.Exec
I0222 20:04:59.205] pkg/util/io/writer.go:71:29: cannot use chmodArgs (type []string) as type string in argument to ne.Exec
I0222 20:04:59.206] !!! [0222 20:04:59] Call tree:
I0222 20:04:59.206] !!! [0222 20:04:59]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:683 kube::golang::build_binaries_for_platform(...)
I0222 20:04:59.207] !!! [0222 20:04:59]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
I0222 20:04:59.212] Makefile:92: recipe for target 'all' failed
I0222 20:04:59.215] Makefile:442: recipe for target 'cross' failed
W0222 20:04:59.316] !!! [0222 20:04:59] Call tree:
W0222 20:04:59.316] !!! [0222 20:04:59]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W0222 20:04:59.316] make[1]: *** [all] Error 1
W0222 20:04:59.317] make: *** [cross] Error 1
W0222 20:04:59.510] !!! [0222 20:04:59] Call tree:
W0222 20:04:59.512] !!! [0222 20:04:59]  1: build/../build/common.sh:553 kube::build::run_build_command_ex(...)
W0222 20:04:59.514] !!! [0222 20:04:59]  2: build/release.sh:36 kube::build::run_build_command(...)
W0222 20:04:59.514] make: *** [release] Error 1
W0222 20:04:59.515] Traceback (most recent call last):
W0222 20:04:59.515]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0222 20:04:59.516]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0222 20:04:59.517]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0222 20:04:59.517]     check(*cmd)
W0222 20:04:59.518]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0222 20:04:59.518]     subprocess.check_call(cmd)
W0222 20:04:59.518]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0222 20:04:59.518]     raise CalledProcessError(retcode, cmd)
W0222 20:04:59.519] subprocess.CalledProcessError: Command '('make', 'release')' returned non-zero exit status 2
I0222 20:04:59.522] Makefile:382: recipe for target 'release' failed
E0222 20:04:59.522] Command failed
I0222 20:04:59.522] process 610 exited with code 1 after 29.9m
E0222 20:04:59.522] FAIL: pull-kubernetes-cross

**What you expected to happen**:
Presumably this is a flaky test.  I would expect the test not to fail since, as far as I can tell, the failure is unrelated to my PR.

**How to reproduce it (as minimally and precisely as possible)**:
Unknown

**Comment by feiskyer** [comment]
Fixed in #60214
