### ISSUE TITLE
[PodSecurityPolicy] restrict EnvVarSources

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#60330]
/kind feature

Even if you forbid mounting ConfigMap or Secret volumes in the PodSecurityPolicy, that data can still be accessed in the container via environment variables, through the EnvVars. I think it may make sense to add restrictions on EnvVar sources too.

Another usecase, courtesy Nathan Sweet:

> it would be nice if the downward api in K8s could be limited in a more granular fashion to create better pod/container isolation from the node/cluster.
> [...]
> In a situation where I don't trust the "deployer" of a pod, I want to limit what values they can see via the downwardAPI. Currently, through a PodSecurityPolicy, you can deny access to the downwardAPI, but there is useful information in it that I might want to grant the "deployer" access to (such as limits), but deny other pieces of information (such as node ip). 

/sig auth

**Comment by php-coder** [comment]
Sounds like `requiredDropsEnvVars []string`
