### ISSUE TITLE
failure when attempting to delete secret: invalid padding on input

### ISSUE THREAD

**Issue by jforman** [kubernetes/kubernetes#60345]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I incorrectly created a secret that I wanted to delete and recreate. When I tried to delete the secret:
* it does not show up in 'kubectl get secrets --all-namespaces'
* I cannot delete it due to the error: Error from server (InternalError): Internal error occurred: invalid padding on input

**What you expected to happen**:
The secret should have been deleted

**How to reproduce it (as minimally and precisely as possible)**:

core@corea-controller0 ~ $ ./kubectl delete secret kubernetes-dashboard-certs -n kube-system
Error from server (InternalError): Internal error occurred: invalid padding on input

**Anything else we need to know?**:

**Environment**: CoreOS Beta channel VMs running on Ubuntu libvirt host.
- Kubernetes version (use `kubectl version`):
core@corea-controller0 ~ $ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0", GitCommit:"79b15896576b7cd8f40d952f5e8307d29a21ac28", GitTreeState:"clean", BuildDate:"2018-02-14T19:41:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0", GitCommit:"79b15896576b7cd8f40d952f5e8307d29a21ac28", GitTreeState:"clean", BuildDate:"2018-02-14T19:08:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: See environment
- OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1662.2.0
VERSION_ID=1662.2.0
BUILD_ID=2018-02-14-0430
PRETTY_NAME="Container Linux by CoreOS 1662.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
core@corea-controller0 ~ $ uname -a
Linux corea-controller0.obfuscated.domain.net 4.14.19-coreos #1 SMP Wed Feb 14 04:08:06 UTC 2018 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux
- Install tools:
- Others:

Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: I0224 03:31:01.195440   21582 wrap.go:42] DELETE /api/v1/namespaces/kube-system/secrets/kubernetes-dashboard-certs: (3.120934ms) 500
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: goroutine 523445 [running]:
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42a382000, 0x1f4)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42a382000, 0x1f4)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42951b1e0, 0x1f4)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc4240973b0, 0x1f4)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:281 +0x45
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x3c6bd37, 0x10, 0x7f1747428008, 0xc4251d9f00, 0x92dd180, 0xc4222ad568, 0xc4293f5300, 0x1f4, 0x92c4600, 0xc4224e26c0)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7f174721b748, 0xc424097b30, 0x92dfc00, 0xc420925ce0, 0x0, 0x0, 0x3c52ada, 0x2, 0x92dd180, 0xc4222ad568, ...)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:123 +0x32b
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7f174721b748, 0xc424097b30, 0x92b2680, 0xc4224e2630, 0x92dfc00, 0xc420925ce0, 0x0, 0x0, 0x3c52ada, 0x2, ...)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:142 +0x163
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc4247d2c80, 0x92b2680, 0xc4224e2630, 0x92dd180, 0xc4222ad568, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:67 +0x10c
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.DeleteResource.func1(0x92dd180, 0xc4222ad568, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go:122 +0x845
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulDeleteResource.func1(0xc424097320, 0xc424c9d140)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1091 +0xc5
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc424097320, 0xc424c9d140)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:199 +0x208
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc42093cf30, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb18
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc42093cf30, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3c66452, 0xe, 0xc42093cf30, 0xc4200f3c70, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:152 +0x4e0
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4208de080, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         <autogenerated>:1 +0x75
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42ad86b80, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:93 +0x18a
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc4297c60c0, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4210f1b90, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3c69211, 0xf, 0xc42664d7a0, 0xc4210f1b90, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc425c782c0, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         <autogenerated>:1 +0x75
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:78 +0x2b1
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: net/http.HandlerFunc.ServeHTTP(0xc421ea0280, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /usr/local/go/src/net/http/server.go:1918 +0x44
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: net/http.HandlerFunc.ServeHTTP(0xc42acda5e0, 0x7f1746e056d0, 0xc4222ad518, 0xc4293f5300)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /usr/local/go/src/net/http/server.go:1918 +0x44
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc42acda660, 0x92e1a80, 0xc4222ad518, 0xc4293f5300, 0xc42637e540)
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab
Feb 24 03:31:01 corea-controller0.obfuscated.domain.net kube-apiserver[21582]: logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Internal error occurred: invalid padding on input\",\"reason\":\"InternalError\",\"details\":{\"causes\":[{\"message\":\"invalid padding on input\"}]},\"code\":500}\n"

**Comment by jforman** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
How did you create the secret? If you go directly to etcd, do you see the secret there?

**Comment by jforman** [comment]
@liggitt  I think this happened when I was testing k8s 1.10-beta.0 with a 1.9.3 kubectl

**Comment by daviddyball** [comment]
I've also been bitten by this issue. I'm running `1.9.3` and can't delete a secret that was created via Helm (chart was `kubernetes-dashboard`, but I doubt the chart was the issue).

Resolved by manually jumping into one of the `etcd` containers running on a master and doing

```
ETCDCTL_API=3 etcdctl --endpoints=[127.0.0.1:2380] del /registry/secrets/kube-system/kubernetes-dashboard
```

Annoying, but now resolved :-/

**Comment by prabhakar-oracle** [comment]
We do see this issue even with 1.19.
