### ISSUE TITLE
kubeadm HA etcd in pod

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubernetes#60374]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I am trying to make kubeadm HA as per doc : https://kubernetes.io/docs/setup/independent/high-availability/#run-etcd

From the document it is not clear:
- if I put the etcds on the masters, and I want to run etcd in the pod, do I need to start the etcd before I run the kubeadm init ? If so , how do I start the etcds as pods? 

I tried to create /etc/kubernetes/manifests/etcd.yaml as in the doc, before the kubeadm init, but then the kubeadm init fails with:
`FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists`

(note the document states that this file should exist and need not be generated when etcd collocated with master: "If you are hosting etcd on the master nodes, this has already been set up.")

**What you expected to happen**:
More clarifications in the documentation 

**How to reproduce it (as minimally and precisely as possible)**:
try to follow the doc.
**Anything else we need to know?**:
I am trying to add HA to the ansible project: https://github.com/ReSearchITEng/kubeadm-playbook .
Any additional suggestions are welcome.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.3
- Cloud provider or hardware configuration:
vagrant
- OS (e.g. from /etc/os-release):
ubuntu 16.04
- Install tools:
kubeadm

**Comment by dgabrysch** [comment]
Hi, I tried the same,  you can either tell kubeadm to ignore the error, or you can stop kubelet before the kubeadm init,  kubeadm starts kubelet then.

**Comment by dgabrysch** [comment]
Sorry for the Spam,  can not edit posts here :)
You will need to wait for the etcd pods to come up before you do the kubeadm init with ha config pointing to these etcds of course.

**Comment by ReSearchITEng** [comment]
@dgabrysch 
I understand it needs some "temporary" (bootstrap) cluster to deploy the etcd pods and afterwards the "actual/final" cluster, correct?
So, what are the options to start the etcd pods before the kubeadm init creates the cluster itself?

**Comment by dgabrysch** [comment]
Hi,

you simply throw in the etcd.yaml you created into /etc/kubernetes/manifests, kubelet should just be running on the nodes and the certificates for each should be there already. You can check out my ansible playbook, I am precreating the ssl keys and certs there on the nodes so etcd can use them when starting. So you don't need a cluster in front, just the kubelets running. Of course the etcd.yaml files need to match your hostnames and so on.

I can give you more details if you need some.

**Comment by dhabierre** [comment]
@ReSearchITEng : I have the same issue. Any idea about it? Thanks.

**Comment by timothysc** [comment]
So, the document explicitly states that a remote etcd cluster.  

We are probably going to stick with that constraint for a period of time.  

In the mean time please feel free to open and RFE: in the https://github.com/kubernetes/kubeadm/issues

**Comment by ReSearchITEng** [comment]
@dgabrysch  I like your ansible section for API HA: https://github.com/dgabrysch/k8s-bootstrap/blob/master/full-cluster.yaml . 
I would like to add it to https://github.com/ReSearchITEng/kubeadm-playbook/
I have some small questions (e.g. why generating other certs beyond etcd ones). 
Can you ping me on slack or email?

**Comment by dgabrysch** [comment]
@ReSearchITEng  Of course I can get in touch, but it seems I am too dumb to find yur contact info :/

**Comment by ReSearchITEng** [comment]
Same like github: researchiteng, in the https://kubernetes.slack.com

**Comment by elouanKeryell-Even** [comment]
It seems I am encountering a vicious circle:

- `kubeadm init` requires etcd pods to be already running (according to [this comment](https://github.com/kubernetes/kubernetes/issues/60374#issuecomment-368260047))
- etcd pods require kubelet
- kubelet require `kubeadm init`, for certificate creations
  - otherwise, fails with `unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`

I guess the solution is to perform certificate creation on your own, to break the "kubelet requires `kubeadm init`" dependency. However, this is not stated in the [documentation](https://kubernetes.io/docs/setup/independent/high-availability), so I don't think it works as is.

**Comment by Itfly** [comment]
The below init code works to me:
```
kubeadm init --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml,ExternalEtcdVersion --config=kubeadm-config.yaml
```
