### ISSUE TITLE
OSS gke tests fails check APIReachability

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60380]
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke
and all other blocking gke jobs

/priority failing-test
/kind bug
/status approved-for-milestone
/sig gcp

cc @jdumars @jberkus @abgworrall 
@mikedanese @Kashomon any idea here?

**Comment by Kashomon** [comment]
I see many errors of the form:

    stderr:
    error: No Auth Provider found for name "gcp"

**Comment by mikedanese** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/60334

**Comment by krzyzacy** [comment]
gke tests are green now, thanks for the fix!
