### ISSUE TITLE
[failing test] Loadbalancing: L7 GCE

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60381]
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-ingress

/priority failing-test
/kind bug
/status approved-for-milestone
/sig network

cc @jdumars @jberkus @bowei @MrHohn

**Comment by MrHohn** [comment]
Fix was opened as https://github.com/kubernetes/kubernetes/pull/59982.

**Comment by krzyzacy** [comment]
thanks!

**Comment by MrHohn** [comment]
Test is still flaky even after the fix. I will take a further look.
cc @rramkumar1

**Comment by krzyzacy** [comment]
@MrHohn looks like now it start to fail on a lot of L7 LB tests

**Comment by MrHohn** [comment]
That seems to be a different failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:113
Test Panicked
```

**Comment by MrHohn** [comment]
The new failure was introduced by https://github.com/kubernetes/kubernetes/pull/60504. When a nil error is passed into `IsProbableEOF`, test will panic:
https://github.com/kubernetes/kubernetes/blob/ad3f9a81a347c0f40fdb62923c3484db62674e43/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L57-L78

Sent #60591 for fixing.
cc @shyamjvs
