### ISSUE TITLE
[Device Plugin] Will Kubelet failed the pod with unhealthy device?

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#60388]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

I'm wonder what's the behavior in such scenario:
A running pod with existing device such like nvidia GPU. Then the device plugin reports the device GPU is unhealthy.  I'm wondering what's the behavior of kubelet on this. Will it kill the existing pod, then start a new pod to bind another health device on this node?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lioncruise** [comment]
I think you could list some detailed situations or cases in which unhealthy device caused kubelet failed pods. I seemed to meet the same problem before and did not find a reason.

**Comment by cheyang** [comment]
I'm just wondering the common behavior the kubelet(Device Manager) handles unhealthy device status report.

**Comment by cheyang** [comment]
When I checked the design doc, I found the following description:
```
If a device becomes unhealthy, kubelet is expected to evict all pods using that device and reduce the overall capacity of that device on that node.
```

Looks like that the pod should be evicted in design, but I failed to find it in the implementation. Can you help me to point out? Thanks in advanced.

**Comment by jiayingz** [comment]
We will not evict pods. With the recent change in 1.10, capacity will include unhealthy devices but allocatable will drop to zero.

**Comment by cheyang** [comment]
Thanks for your response. So it looks like it's not the same  as the design doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md#healthcheck-and-failure-recovery

```
If a device fails, the Device Plugin should signal that through the ListAndWatch gRPC stream. We then expect Kubelet to fail the Pod.
```
So does it mean that the behavior of handling unhealthy device change? If so, I suggest to change the design doc.

**Comment by jiayingz** [comment]
I have a pending PR to update the proposal: https://github.com/kubernetes/community/pull/1447
Unfortunately it has been sitting there for a while to get approval. I think I will update it to cope with a few 1.10 changes in 1.10 time frame.

**Comment by cheyang** [comment]
Great! Thank you for letting me know.

**Comment by pineking** [comment]
@jiayingz what's the reason for dropping allocatable to zero in recent change? I remember the value of allocatable is the healthy device count before the recent commits.

**Comment by jiayingz** [comment]
@pineking could you share more context for your question?

**Comment by pineking** [comment]
I mean suppose there are 8 GPUs in a node, when one GPU becomes unhealthy, the left 7 GPUs still can be working correctly,  I do not know why the allocatable set to zero,  should it be 7 as in the v1.9 implementation?

**Comment by jiayingz** [comment]
It should be 7 in both v1.9 and v1.10.

**Comment by pineking** [comment]
https://github.com/kubernetes/kubernetes/issues/60388#issuecomment-368399542
>We will not evict pods. With the recent change in 1.10, capacity will include unhealthy devices but allocatable will drop to zero.

@jiayingz perhaps I misunderstood your comment. Thanks for your reply and clarification.

**Comment by vikaschoudhary16** [comment]
Closing it because it seems query raised has got resolved.
