### ISSUE TITLE
Failed to build kubernetes with Go 1.10

### ISSUE THREAD

**Issue by ikruglov** [kubernetes/kubernetes#60389]
**Is this a BUG REPORT**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

Failed to build kubernetes with Go 1.10:

**What you expected to happen**:
kubernetes builds with Go 1.10

**How to reproduce it (as minimally and precisely as possible)**:

When building kubernetes using golang 1.10 hack/lib/golang.sh fail to realize that golang 1.10 is a higher version than 1.9.1.

IMO problem is [here](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L322).

It can be simply reproduced:

```
$ /bin/bash -c '[[ "go1.8" < "go1.9.1" ]] && echo True || echo False'
True
$ /bin/bash -c '[[ "go1.9.4" < "go1.9.1" ]] && echo True || echo False'
False
$ /bin/bash -c '[[ "go1.10" < "go1.9.1" ]] && echo True || echo False'
True
```

Last command should result into False

**Environment**:
- OS: Darwin ***** 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-
- Kubernetes version: 1.9.3:
- Install tools: golang-1.10

**Comment by ikruglov** [comment]
/sig release
@kubernetes/sig-release-bug

sorry if I picked wrong SIG

**Comment by ikruglov** [comment]
I'be looking into outdated file.
sorry for noise!!!

**Comment by thedrow** [comment]
I'm actually seeing the same with kubectl on Linux. Could it be related?

**Comment by matthewdupre** [comment]
This happens to me trying to build on Arch (with go 1.10).  Can this be reopened?
