### ISSUE TITLE
unit flake: pull-kubernetes-unit

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/kubernetes#60394]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/kind flake
/sig testing
/priority failing-test

**What happened**:
`pull-kubernetes-unit` intermittently fails on two of my PRs:
* #60011
* #60073 

despite no changes to PR.

**What you expected to happen**:
for all tests to pass :)

**Anything else we need to know?**:
I was thumbing through the [logs](https://k8s-gubernator.appspot.com/pr/60011) as I assumed there were issues specifically related to my PRs, but when checking the [PR logs](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit) for `pull-kubernetes-unit`, I noticed that this seems to be failing ~50% of the time.

![screenshot from 2018-02-25 18-02-48](https://user-images.githubusercontent.com/567897/36647606-3a1cfd1a-1a56-11e8-961d-ffa3b66e2e2f.png)

Links to a few of the [failing tests](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit/):
* https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit/82678.txt
* https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit/82675.txt
* https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit/82673.txt
* https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit/82668.txt

**Comment by nikhita** [comment]
The most flakiest test is `TestCRDDeletionCascading`, which looks to be causing these test failures. 

This is a dupe of https://github.com/kubernetes/kubernetes/issues/59426.

**Comment by justaugustus** [comment]
@kubernetes/sig-testing-test-failures --
Can we get someone to take a look and decide whether this is milestone-worthy?

cc: @jberkus

**Comment by BenTheElder** [comment]
Randomly sampling these failures it's also worth noting that lots of PR failures are just due to people submitting code that doesn't build or has merge conflicts. EG https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60445/pull-kubernetes-unit/82971/

@krzyzacy we *really* need to bikeshed this name. It's also worth knowing that unit tests run in `pull-kubernetes-bazel-test` and `pull-kubernetes-unit` is *integration* testing and we reallly need to rename this job :(
The "integration" tests are known to be quite flaky.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/7001

**Comment by jennybuckley** [comment]
#59426 is closed so is this closable?
Although now it looks like a new flake of TestKMSProvider is breaking pull-kubernetes-unit

**Comment by BenTheElder** [comment]
FYI https://github.com/kubernetes/test-infra/pull/7057#issuecomment-369384392

And yes, TestKMSProvider has some issues, it also doesn't cross compile properly. :/

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/60615 for TestKMSProvider

**Comment by liggitt** [comment]
TestKMSProvider is no longer flaky, and this job no longer exists

/close
