### ISSUE TITLE
updaing service annotation tags doesn't update AWS internal ELB 

### ISSUE THREAD

**Issue by omerh** [kubernetes/kubernetes#60393]
>/kind bug
/sig network

**What happened**: creating and then updating a service type: loadBalancer on AWS doesn't update tags from annotation.

**What you expected to happen**: When updating annotation for tags, I would want them to be updated on the ELB

**How to reproduce it (as minimally and precisely as possible)**:
Create a service using internal aws elb:
`kubectl apply -f https://gist.githubusercontent.com/omerh/772ffd0fa4b9441338bd29d433913d20/raw/92415849d36f5a3b4a1b344e117e6b2ce46d9618/service.yml`

Update service with name and tags `kubectl apply -f https://gist.githubusercontent.com/omerh/772ffd0fa4b9441338bd29d433913d20/raw/92415849d36f5a3b4a1b344e117e6b2ce46d9618/service1.yml`

**Environment**:
- Kubernetes version `Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS
- Install tools: kops

**Comment by jhorwit2** [comment]
/area cloudprovider 
/sig aws

The service controller [is passing](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/service_controller.go#L477) services to the clouds when the annotations change, so this is cloud provider specific.

**Comment by kgtw** [comment]
@jhorwit2 can this be re-opened, it is still an issue in 1.18.14
