### ISSUE TITLE
Can we add extended resource by set option of kubelet?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#60405]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
For now we can use CURL -patch to advertise a new resource for a node.like:
````
curl --header "Content-Type: application/json-patch+json" \
--request PATCH \
--data '[{"op": "add", "path": "/status/capacity/example.com~1dongle", "value": "4"}]' \
http://localhost:8001/api/v1/nodes/<your-node-name>/status
````
**What you expected to happen**:
What if I want to add a type of resouce (such as `local-storage`) for all my nodes?   Can we use an option of `kubelet` so that it can automatically add the resource  when it start with the option like:
`--extended-resource-map="local-storage:100Gi"`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):debian 9
- Kernel (e.g. `uname -a`):Linux hydev 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by fzu-huang** [comment]
sig/scalability

**Comment by k82cn** [comment]
nop, but you can use device plugin to build one. 

/sig node

maybe an example device plugin is better.
