### ISSUE TITLE
Deprecated preferred version for Deployment resources

### ISSUE THREAD

**Issue by ismailbaskin** [kubernetes/kubernetes#60419]
> /kind bug

**What happened**:
According to [1.9 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#apps) Deployment has been promoted to GA stability in the apps/v1 group version. 

But kubectl get deployment still use "extensions/v1beta1" version because of in the http://APISERVER/apis endpoint groups.1.preferredVersion.groupVersion = "extensions/v1beta1" comes before groups.2.preferredVersion.groupVersion = "apps/v1". 

Also kubectl run command still using deployment/v1beta1 as default generator.

I expected that all kubectl deployment commands use apps/v1 version for deployment.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3
- Cloud provider or hardware configuration: GKE - v1.9.2-gke.1
- OS (e.g. from /etc/os-release): Mac OS
- Kernel (e.g. `uname -a`): Darwin

**Comment by liggitt** [comment]
tracked by https://github.com/kubernetes/kubernetes/issues/43214
/close
