### ISSUE TITLE
salt script for kubelet default file does not run correctly on master

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#6042]
The salt template cluster/saltbase/salt/kubelet/default does not correctly get specialized.
The ipaddress is not found.
This causes kubelet to start without the api server specified on the master.

this can be verified by running "salt-call --local state.highstate" on the master node.

**Comment by thockin** [comment]
I don't see an ipaddress var in there?  Can you post the actual error?

**Comment by ArtfulCoder** [comment]
without the changes in this PR, we encounter the following error.

Because kubelet runs without the api-server flag, due to the following error,  kubelet does not function correctly or not function at all. (i.e. containers dont get refreshed etc)

----------
          ID: /etc/default/kubelet
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable list object has no element 0; line 10
              
              ---
              [...]
              
              {% if grains.apiservers is defined -%}
                {% set apiservers = "--api_servers=https://" + grains.apiservers + ":6443" -%}
              {% else -%}
                {% set ips = salt['mine.get']('roles:kubernetes-master', 'network.ip_addrs', 'grain').values() -%}
                {% set apiservers = "--api_servers=https://" + ips[0][0] + ":6443" -%}    <======================
              {% endif -%}
              
              
              {% set address = "--address=0.0.0.0" -%}
              {% set config = "--config=/etc/kubernetes/manifests" -%}
              [...]
              ---
     Changes:   
----------

**Comment by ArtfulCoder** [comment]
#6043

**Comment by zmerlynn** [comment]
I pointed out a different way to handle it in the PR: I don't think you need to specialize here, just set the grain correctly on the master.
