### ISSUE TITLE
[failing test] daemonset-upgrade in 1.9-master upgrade jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60437]
example: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-cluster-parallel, and other suites in the master-upgrade dashboard

/priority failing-test
/kind bug
/status approved-for-milestone
/sig apps

cc @jdumars @jberkus @mattfarina @kow3ns @prydonius

**Comment by kow3ns** [comment]
The ds controller is failing to place the Pod because of #60163. It should be fixed by #60386. @k82cn can you verify that this clears up after you merge please. ty.

**Comment by k82cn** [comment]
sure, I'll check it after #60386 merged :)

**Comment by jberkus** [comment]
Adding priority critical-urgent because we are in Code Freeze.

/priority critical-urgent

**Comment by krzyzacy** [comment]
assume https://github.com/kubernetes/kubernetes/pull/60672 will also fix this? @kow3ns

**Comment by janetkuo** [comment]
The fix #60386 was merged 7 hours ago. I confirmed that the test `[sig-apps] daemonset-upgrade` is green again.

**Comment by krzyzacy** [comment]
@janetkuo it's still failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master and other master upgrade suites

**Comment by kow3ns** [comment]
The tests are green again.
/close
