### ISSUE TITLE
set-based selectors are not working for the podnodeselector admission plugin

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#60438]
Forked from https://github.com/kubernetes/kubernetes/issues/59266

@kubernetes/sig-api-machinery-bugs 
@kubernetes/sig-scheduling-bugs

**Comment by wjiangjay** [comment]
I saw current podnodeselector admission only support string format label, so this issue want podnodselector support set-based selector?

**Comment by liggitt** [comment]
no, pods only support set-based selectors for the nodeSelector field, so that is all podnodeselector supports.

**Comment by dimm0** [comment]
I didn't get it, will podnodeselector admission controller support set-based selector?

**Comment by liggitt** [comment]
sorry, mistyped. The pod nodeSelector field is simple selector (`map[string]string`), so that is all that the PodNodeSelector admission plugin needs to support

**Comment by dimm0** [comment]
Why not set-based selector? I'm trying to run some daemonsets across all nodes in privileged namespaces, and it's impossible with the current simple selector.

**Comment by wanghaoran1988** [comment]
@dimm0 Does taints/toleration works for you?

**Comment by dimm0** [comment]
@wanghaoran1988 Yes, but that's much more than I need actually. I just need kube-system and a couple more namespaces to run on all nodes, regardless of labels.. But taints and tolerations would be awesome.

**Comment by dimm0** [comment]
I think I figured this. Can use another label which is the same for all nodes in the cluster.
