### ISSUE TITLE
Image Manager should return a copy of image list to avoid data race.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#60443]
See https://github.com/kubernetes/kubernetes/pull/60198#issuecomment-367627199.

Today kubelet image manager returns the internal image list cache to caller directly. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_gc_manager.go#L127

However, in `setNodeStatusImages` we sort the image list, which introduces a data race.

We should let image manager return a copy of image list instead of returning the list directly.

/cc @kubernetes/sig-node-bugs

**Comment by jberkus** [comment]
@Random-Liu Code Freeze for 1.10 begins in 2 hours.  If this issue represents a bug or change for 1.10, then it needs SIG approval in the form of a status/approved-for-milestone label.  It also needs a priority/  Thanks!
