### ISSUE TITLE
[Flaky Test] : [sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]

### ISSUE THREAD

**Issue by mithrav** [kubernetes/kubernetes#60463]
## Flaky Jobs:
* [presubmits-kubernetes-blocking#pull-kubernetes-integration](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&show-stale-tests=)
* [ci-kubernetes-e2e-gci-gce](https://k8s-testgrid.appspot.com/sig-api-machinery#gce&width=5)

## Flakiest test :
* [[sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64957/pull-kubernetes-e2e-gce/40826)

## Triage link
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-06-15&sig=api-machinery&job=ci-kubernetes-e2e-gci-gce&test=Garbage%20collector%20should%20orphan%20RS%20created%20by%20deployment%20when%20deleteOptions.PropagationPolicy%20is%20Orphan

/priority failing-test
/priority important-soon
/kind flake
/sig-api-machinery
@kubernetes/sig-api-machinery-bugs 

this failure is currently one of the top flake and repros in both Presubmits and CI jobs. This test is also part of the Conformance suite, which makes the flake far more critical. Can one of you please help triage this issue.

**Comment by liggitt** [comment]
flakes are continuing, hopefully added logging gives us more info to work with

**Comment by AishSundar** [comment]
@jennybuckley this test seems to flake quite a bit in the presubmits and its a conformance test on top of this. Can we please look into the new logs to see if we have more info to deflake this?

Triage: 
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-06-15&ci=0&pr=1&sig=api-machinery&test=Garbage%20collector%20should%20orphan%20RS%20created%20by%20deployment%20when%20deleteOptions.PropagationPolicy%20is%20Orphan

Logs: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65189/pull-kubernetes-e2e-gce/41961

**Comment by AishSundar** [comment]
FWIW this test seems to pass consistently in our conformance dashboards - https://k8s-testgrid.appspot.com/conformance-gce#GCE,%20master%20(dev). 

But seems to flake only in CI and Presubmits 
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-06-15&pr=1&sig=api-machinery&test=Garbage%20collector%20should%20orphan%20RS%20created%20by%20deployment%20when%20deleteOptions.PropagationPolicy%20is%20Orphan

**Comment by liggitt** [comment]
Do those run at different parallelism levels? It could be load/timeout sensitive

**Comment by liggitt** [comment]
> @jennybuckley this test seems to flake quite a bit in the presubmits and its a conformance test on top of this. Can we please look into the new logs to see if we have more info to deflake this?

I have also seen a general uptick in flakes in other e2e tests that could be sensitive to watch event latency, not just gc tests - for example, see the failures in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65547/pull-kubernetes-e2e-gce/42324/

**Comment by jberkus** [comment]
Hey, this test does not appear to be flaking anymore can we close this issue?

**Comment by jberkus** [comment]
Closing based on non-response.

/close

**Comment by lavalamp** [comment]
This was never actually fixed, looks like.
