### ISSUE TITLE
cloud node controller is removing nodes from cluster in reboot?

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#60479]
why cloud node controller is deleting nodes from cluster if we like reboot those. https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L148

Imo we should not delete nodes from if there is possibility that same node can return. The problem is that if we want to add some custom things like taints and labels to nodes, then reboot is removing these things. Currently we have own operator which will add these labels and taints after node is re-registered. node lifecycle controller is working in different way, it is not removing these nodes in AWS (and I hope that openstack part of it is moving to that direction in #59931 )

I suggest that we do not remove nodes if there is possibility that same node can return back to cluster. Which means that we need to modify specification to InstanceExistsByProviderID in Instances cloudprovider interface. (do we really need this function in interface, why we are not using it like similar way in node lifecycle controller? it just works.)

/kind feature

**Comment by zetaab** [comment]
cc @wlan0 @thockin

**Comment by zetaab** [comment]
cc @jhorwit2

**Comment by feiskyer** [comment]
> why cloud node controller is deleting nodes from cluster if we like reboot those. https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L148

For rebooting cases, I think `InstanceExistsByProviderID()` should return true because the virtual machine is still not deleted yet from Cloud. Are there any concerns about keeping stopped VM not removed?

**Comment by zetaab** [comment]
@feiskyer if we delete node if it is stopped we cannot detach volumes immediately because we do not know the real situation there. That is why I am doing PR #60009 after that we are not removing nodes anymore if those are shutdown. This will make it faster to failover pod which have pvc if the node is shutdown. In openstack this means from 10minutes something like 1minute (volume controller part is not implemented yet).

**Comment by jingxu97** [comment]
I agree to not remove the shutdown node from API server if they still exist in the cloudprovider. After  we add the code to taint the shutdown node, there will not be delay for volume controller to detach the volumes.

**Comment by feiskyer** [comment]
> I agree to not remove the shutdown node from API server if they still exist in the cloudprovider. After we add the code to taint the shutdown node, there will not be delay for volume controller to detach the volumes.

+1. @zetaab Do you agree with this after #60009?
