### ISSUE TITLE
Server side print returns generic information for deployments

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#60488]
/kind bug

**What happened**:
`kubectl get deploy --experimental-server-print` returns only name and creation timestamp.

**What you expected to happen**:
The server side print should return columns exactly the same as regular print we have right now.

/sig cli
/assign soltysh

**Comment by jdumars** [comment]
@soltysh if this is a 1.10 blocker, could you please add status/approved-for-milestone label?

**Comment by soltysh** [comment]
Done.
