### ISSUE TITLE
Add windows images for e2e tests  

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#60487]
FEATURE REQUEST

/kind feature

Over at sig-winows we've been starting the process of running e2e tests against clusters with windows nodes. The main issues we face is that the test images for the e2e tests are not configurable, the repositories are defined [here](https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go). It would be helpful to change these via env vars or passed in a config file.

The second issue is that the images used for testing are linux based. They can have separate docker files for windows and linux and have the image build script take that into account.

/sig testing
/sig windows

**Comment by BenTheElder** [comment]
/cc
Once this is solved please ping me / @kubernetes/test-infra-maintainers so we can discuss using this work in CI

**Comment by ixdy** [comment]
cc @mkumatag @luxas
