### ISSUE TITLE
Proxied Watches Do Not Scale Well (single aggregated api-server case)

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60484]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
In a configuration with one main api-server and one aggregated api-server, the amount of load that can be served is limited by some internal software resource rather than the underlying CPU, memory, and network.

I tried a bunch of the example controllers modified to work with Flunder objects from the sample api-server.  I scaled in two dimensions: rate of operations on Flunder objects, and number of controllers.  As I scale up, I can go farther when the controllers connect directly to the aggregated api-server than when they connect to the main api-server --- but as the proxied case hits its limits, there is no overload of CPU, memory, nor network.  See https://docs.google.com/document/d/1QJYvS6DMgmNYlUSQivcaxZJD3P66gDUb6RIPe4RO-4I for more details.  The last few trials have CPU, memory, and network resource usage readings per container and per node.

(I also have my doubts about how well proxying will scale as the api-servers are replicated.  But that is a separate issue --- now confirmed, see #61296.)

**What you expected to happen**:
I expected to hit a scaling limit only when I started running out of CPU, memory, or network bandwidth.

**How to reproduce it (as minimally and precisely as possible)**:
The experiments I reported on are pretty bare-bones.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.7
- Cloud provider or hardware configuration: local VMs
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0
- Install tools: kubespray
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
I updated the experiment write-up with some new trials.  The latest includes log and data files.

**Comment by MikeSpreitzer** [comment]
I added Prometheus monitoring, and two new trials of proxied watches.  One, with 4 loggers on each worker node, had big problems; the other trial had just 3 loggers on each worker node, and it got fairly decent results.

**Comment by MikeSpreitzer** [comment]
The Prometheus data shows that when using proxying the CPU usage (on the node running the aggregated api-server and its etcd server) is about half of what it is when the flunder-loggers connect directly to the aggregated api-server, and the network usage is nowhere near the network capacity.  But with proxying the informers lose sync and miss objects.

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability-misc

**Comment by MikeSpreitzer** [comment]
I have a simple demonstration of throughput being limited by a single HTTP/2 connection between two processes.  It is based on the code in https://github.com/MikeSpreitzer/k8api-scaletest/tree/master/go_httperf , which you may think of as a go&HTTP/2 based variant of `iperf`.

With two connections, I can get the requested throughput:
```
$ ./go_httperf -listen 9080 -base-url https://10.10.21.1:9080 -block-size 500 -blocks-per-request 2001 -period 0.004 -v=2 -connections 1 -threads 800 -connections 2
I0316 07:21:13.753689  116258 main.go:272] urlMid="https://10.10.21.1:9080/blocks?size=500&periodMS=4"
I0316 07:21:14.109748  116258 main.go:132] Saving TLS master keys to /tmp/9080.keys
I0316 07:22:13.760855  116258 main.go:64] clientBytes = 5263340500, 8.771177229138955e+07/sec since 2018-03-16 07:21:13.753587456 +0000 UTC m=+0.004340827
I0316 07:23:13.762302  116258 main.go:64] clientBytes = 11285085500, 1.0035995481690302e+08/sec since 2018-03-16 07:22:13.76081759 +0000 UTC m=+60.011570900
I0316 07:24:13.769328  116258 main.go:64] clientBytes = 17289746500, 1.0006597143025061e+08/sec since 2018-03-16 07:23:13.762289435 +0000 UTC m=+120.013042712
^C
```

With just one connection, it never gets there:
```
$ ./go_httperf -listen 9080 -base-url https://10.10.21.1:9080 -block-size 500 -blocks-per-request 2001 -period 0.004 -v=2 -connections 1 -threads 800 -connections 1
I0316 07:24:28.371342  116580 main.go:272] urlMid="https://10.10.21.1:9080/blocks?size=500&periodMS=4"
I0316 07:24:28.927634  116580 main.go:132] Saving TLS master keys to /tmp/9080.keys
I0316 07:25:28.395689  116580 main.go:64] clientBytes = 3336270500, 5.558190079074456e+07/sec since 2018-03-16 07:24:28.371266671 +0000 UTC m=+0.004483803
I0316 07:26:28.421377  116580 main.go:64] clientBytes = 6966462000, 6.0477292563473046e+07/sec since 2018-03-16 07:25:28.395671205 +0000 UTC m=+60.028888376
I0316 07:27:28.494583  116580 main.go:64] clientBytes = 10704244000, 6.222045592781867e+07/sec since 2018-03-16 07:26:28.421366017 +0000 UTC m=+120.054583081
I0316 07:28:28.512621  116580 main.go:64] clientBytes = 14391120000, 6.1429466149215795e+07/sec since 2018-03-16 07:27:28.494567706 +0000 UTC m=+180.127784800
I0316 07:29:28.519788  116580 main.go:64] clientBytes = 17975428500, 5.973133932397004e+07/sec since 2018-03-16 07:28:28.512605153 +0000 UTC m=+240.145822252
I0316 07:30:28.522833  116580 main.go:64] clientBytes = 21603854000, 6.047069097164362e+07/sec since 2018-03-16 07:29:28.519772831 +0000 UTC m=+300.152990023
^C
```

(This two processes are on the two VMs used in my recent scaling tests.  The number of connections was independently verified by `netstat`.)

**Comment by MikeSpreitzer** [comment]
After discovering the `--enable-aggregator-routing` command line flag on the main api-server, which is necessary to make it load-balance among replicated aggregated api-servers, I also noticed that the main api-server had been given a resource limit of 0.8 CPU!  After relaxing that, I found the proxied watches to work about as well as could be expected.
