### ISSUE TITLE
Kubelet failed to get node info: failed to get external ID from cloud provider: multiple results where only one expected

### ISSUE THREAD

**Issue by wayarmy** [kubernetes/kubernetes#60491]
Hi there,

I'm trying to install kubernetes cluster on Openstack with flag `--cloud-provider=openstack`. And when restart kubelet, i have error:
```
Feb 27 17:08:01 test1 kubelet[16407]: F0227 17:08:01.757592   16407 kubelet.go:1364] Kubelet failed to get node info: failed to get external ID from cloud provider: multiple results where only one expected
```

- The reason is on my openstack system, i have more than 1 instance with the same name `test1`. And i think it's the big problem when install kubernetes cluster on cloud-system.

Of course, when i change name of instance, everything is OK, but in the future, i don't know if there's some instances with the same name.

Please check this error for complete kubelet.

**Comment by greatbn** [comment]
I have same issue. When launch an instance with same name with other one, Kubelet can't start.

**Comment by dims** [comment]
do they have the same hostnames too? we need to be able to discover the vm that corresponds to where the code is running. (trying to avoid using uuid(s))

**Comment by nguyenduybinh** [comment]
i have the same issue when use kubernetes with cloud provider openstack.
When in my tenant have an instance with the same name with my kubernetes instance, Kubelet can't start.
I rename the instance, kubelet start ok ( openstack instance's name not hostname)
