### ISSUE TITLE
Failing to list pods with resourceVersion=0

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#60507]
Running `curl -k -v -XGET -H "Accept: application/json, */*" -H 'User-Agent: cluster-autoscaler/v0.0.0 (linux/amd64) kubernetes/$Format' 'http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0'` on master node in 1.9 cluster results in listing all pods that are assigned to some node.

The same on cluster running k8s version from HEAD:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0 HTTP/1.1
> Host: 127.0.0.1:8080
> Accept: application/json, */*
> User-Agent: cluster-autoscaler/v0.0.0 (linux/amd64) kubernetes/$Format
> 
< HTTP/1.1 200 OK
< Audit-Id: 54b8afbe-dbd1-4608-b6f7-1375d73532ce
< Content-Type: application/json
< Date: Thu, 01 Mar 2018 15:59:31 GMT
< Content-Length: 113
< 
{"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/pods","resourceVersion":"95581"},"items":[]}
* Connection #0 to host 127.0.0.1 left intact
```

Removing the part of selector with `spec.nodeName` results in listing all current pods, regardless of whether they're scheduled. 

This looks like a regression from 1.9 (and also breaks Cluster Autoscaler, which relies on selecting scheduled pods based on non-empty field.) Interestingly, it seems that the watch part still works (there are updates for scheduled pods that have been modified.)

cc @wojtek-t @mwielgus

(Edited to fix command)

**Comment by lavalamp** [comment]
Can you give more details? What is the difference in behavior from what you expected? Maybe the coffee hasn't kicked in yet but this sounds like how I'd expect it to behave?

**Comment by aleksandra-malinowska** [comment]
In 1.9, the result is the list of all scheduled pods (omitted due to length.)

In the version built from HEAD yesterday, the same request returns an empty list. There are pods running in the cluster, scheduled, with non-empty spec.nodeName.

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery-bugs @deads2k 

Sounds like backward-incompatible change somewhere in apiserver.

Maybe this is even something that we want to do, but definitely it needs to be intentional and probably have a release note or sth like that.

**Comment by jdumars** [comment]
If this is something we need to track for 1.10 can a SIG leader please add the status/approved-for-milestone label?  If it is a known issue, we should track it here:  #59764

**Comment by wojtek-t** [comment]
@aleksandra-malinowska @mwielgus - from what we talked yesterday it seems that it may not be a real issue but some problem with debugging?
If we believe this isn't an issue, can we close that?

**Comment by aleksandra-malinowska** [comment]
@wojtek-t the same image we're currently using with 1.9 fails with 1.10 (it seems to receive different data from API server for the list request.) Closing this for now as this isn't as obvious as originally described.

**Comment by aleksandra-malinowska** [comment]
Confirmed that this is different in 1.9 vs 1.10 and can be reproduced. The problem doesn't appear to be with selector, but with `resourceVersion=0`. This parameter is always added by [ListWatch](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L246). And as indicated by the comment there, the result isn't always empty - it returns only pods that have been modified since API server start. The problem with "catch up eventually" in this case is that it doesn't really happen (most pods aren't modified after every master restart). Removing this parameter results in the complete list being returned.

It's problematic because:
1) it's backwards incompatible (current stable release of Cluster Autoscaler can't be used with 1.10 unless this changes)
2) it makes ListWatch unreliable for tracking cluster state (since we'll never ever learn about objects that didn't change very recently, and every master node restart resets this)
3) it can't be fixed on application side without replacing ListWatch with manual list + watch

If this is the intended behavior, can we at least remove always setting resourceVersion=0 from ListWatch?

**Comment by wojtek-t** [comment]
> And as indicated by the comment there, the result isn't always empty - it returns only pods that have been modified since API server start. 

That isn't true. For List, it should return all the pods (potentially not from now, but from some time ago, but still a consistent state of all pods from that point in time).
And then watch should be served from that point and everything should work wrt to that.

If something changed in 1.10 wrt that, then it's a bug.

@liggitt - FYI

**Comment by aleksandra-malinowska** [comment]
> That isn't true. For List, it should return all the pods (potentially not from now, but from some time ago, but still a consistent state of all pods from that point in time).
>And then watch should be served from that point and everything should work wrt to that.
>
>If something changed in 1.10 wrt that, then it's a bug.

This is the behavior I observed on cluster built from HEAD this week. While debugging it, it went for ~day without API server restart, and List never returned the pods that weren't modified since that restart. Restarting the component doing ListWatch doesn't affect this.

**Comment by wojtek-t** [comment]
This is super strange.

Looking into the code, when the request has set the limit (which in your case it seems it have: "&limit=500&"), it shouldn't even be serve from cache, but directly from etcd:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher.go#L479

Can you please add logging on the apiserver side (around the place that I just pasted above) and see:
- whether we enter that branch or not
- what do we return a "listObj" there
?

**Comment by wojtek-t** [comment]
@smarterclayton - FYI

**Comment by aleksandra-malinowska** [comment]
Looks like the limit only matters if resourceVersion!=0:

`hasLimit := pagingEnabled && pred.Limit > 0 && resourceVersion != "0"`

I'll try it with added logging.

**Comment by wojtek-t** [comment]
OK - that's a good point.

What comes to my mind, is this https://github.com/kubernetes/kubernetes/pull/59871 - I don't know why it would break that, but this is touching this code, so maybe this is related? @shyamjvs

**Comment by jdumars** [comment]
If we suspect this might be a 1.10 blocker, could you add the status/approved-for-milestone label at your convenience?

**Comment by liggitt** [comment]
yes, driving this to resolution is a blocker
/status approved-for-milestone

**Comment by aleksandra-malinowska** [comment]
@wojtek-t Thanks for tips on how to debug this! After I added logging, it turned out that all objects are in cache, but for those older than the API server, `elem.Fields` and `elem.Labels` are `nil`, so they can't match any non-empty selector and are [filtered out](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher.go#L529). Since those fields are set when processing events, result includes only objects for which at least one event was observed. Setting those fields when filling cache fixes the issue.
