### ISSUE TITLE
kubectl completion failed to list file names

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#60517]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`kubectl create -f [Tab]` failed with the following message: `kubectl create -f __create_handle_filename_extension_flag: command not found`

@kubernetes/sig-cli-bugs 

**What you expected to happen**:
It should list filenames.

**How to reproduce it (as minimally and precisely as possible)**:
```console
$ source <(kubectl completion bash)
$ kubectl create -f [Tab]
```

It's a regression. This worked before 1.10.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0.807+744b5d3357cd14-dirty", GitCommit:"744b5d3357cd148faf6f03e7a188d4113d931b8c", GitTreeState:"dirty", BuildDate:"2018-02-27T19:24:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0.807+744b5d3357cd14-dirty", GitCommit:"744b5d3357cd148faf6f03e7a188d4113d931b8c", GitTreeState:"dirty", BuildDate:"2018-02-27T19:24:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by mengqiy** [comment]
cc: @superbrothers

**Comment by superbrothers** [comment]
https://github.com/spf13/cobra/pull/520/files#diff-3db5cab63dbb32fff4264f5449fd2904R314

It seems that the above change cause this bug. I'm going to update vendor github.com/spf13/cobra at just before that commit.

/ref https://github.com/kubernetes/kubernetes/pull/60135
/cc @eparis

**Comment by johnmccabe** [comment]
@superbrothers @janetkuo I've got a fix lined up for this, will raise the PR shortly..

![kubectl_autocomplete](https://user-images.githubusercontent.com/83862/36762756-0fbe5c44-1c1d-11e8-95e7-4f4197acc1a9.gif)

**Comment by johnmccabe** [comment]
@janetkuo / @superbrothers / @eparis I've raised spf13/cobra#643 which should hopefully sort this out

**Comment by johnmccabe** [comment]
The upstream fix is merged now.

**Comment by jberkus** [comment]
@johnmccabe does that mean we can close this issue?

**Comment by liggitt** [comment]
No, it means https://github.com/kubernetes/kubernetes/issues/60530 can be updated to pull in the fix

**Comment by jberkus** [comment]
OK, this issue needs status/approved-for-milestone then to indicate SIG approval.

I'm adding priority/critical-urgent because we're in Code Freeze and this is in the 1.10 milestone.

/priority critical-urgent
