### ISSUE TITLE
azure cloud provider tries to get loadbalancer for services that do not have Type=LoadBalancer

### ISSUE THREAD

**Issue by michaelburch** [kubernetes/kubernetes#60528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Repeating Warnings are received with message "Error creating load balancer" when creating service of type ClusterIP

**What you expected to happen**:
Service created without warnings

**How to reproduce it (as minimally and precisely as possible)**:
Deploy any service of type clusterip
``kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  clusterIP: 10.0.118.236
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
``

**Anything else we need to know?**:
controller-manager log entry 
{"log":"I0227 22:07:22.780677       1 event.go:218] Event(v1.ObjectReference{Kind:\"Service\", Namespace:\"default\", Name:\"nfs-server\", UID:\"3b785bd7-1bc4-11e8-8a1a-000d3a0396df\", APIVersion:\"v1\", ResourceVersion:\"64003\", FieldPath:\"\"}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service default/nfs-server: Service(default/nfs-server) - Loadbalancer not found\n","stream":"stderr","time":"2018-02-27T22:07:22.780844622Z"}
{"log":"I0227 22:07:23.009676       1 azure_backoff.go:193] LoadBalancerClient.List(CDPaaSdev) - backoff: success\n","stream":"stderr","time":"2018-02-27T22:07:23.00982832Z"}

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux 4.13.0-1007-azure
- Install tools: acs-engine
- Others:

**Comment by michaelburch** [comment]
@kubernetes/sig-azure

**Comment by rbankole** [comment]
same here..can confirm on similar environment via acs-engine
Kubernetes version (use kubectl version): 1.9.3
Cloud provider or hardware configuration: Azure
OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS

**Comment by oivindoh** [comment]
Can confirm, seeing same behaviour on 1.9.3

**Comment by lachie83** [comment]
I believe this is an upstream issue

**Comment by brendandburns** [comment]
I _think_ that this may have been fixed here:

https://github.com/kubernetes/kubernetes/pull/57991

**Comment by brendandburns** [comment]
We are cherry-picking this into 1.9.6 here:

https://github.com/kubernetes/kubernetes/pull/61260

**Comment by brendandburns** [comment]
and fwiw, while this spams the logs, it shouldn't affect operation of the service.

**Comment by feiskyer** [comment]
This is working as expected. See @brendanburns's comments [here](https://github.com/kubernetes/kubernetes/issues/61100#issuecomment-374402523). 

While the error message is misleading, #61260 removes them from events.

**Comment by feiskyer** [comment]
#61260 got merged. Let's close this issue.

/close
