### ISSUE TITLE
Kubernetes DNS resolution can be used to replace "real" DNS records

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#60534]
By creating a namespace called (for example) "com", a service in that namespace called (for example) "yahoo" will be resolved by other pods referencing yahoo.com (without the trailing dot).

```
kubectl create ns com
kubectl create service externalname yahoo -n com --external-name google.com 
```

Within a pod (even in another namespace) pinging yahoo.com then pings google.com's IP.  You can also create a real k8s service, it doesn't have to be `externalname`.

The problem here is that our DNS suffix resolution first considers google.com as a `<service>.<namespace>` name (adding the .svc.cluster.local. suffix and looking that up first)

As long as all pods are performing TLS validation this should only be a DoS issue, and is only possible when you have permissions to create namespaces on the cluster.

Concerned admins could pre-create and lock-down "critical" TLDs, and of course we should all be using the trailing dot where possible (i.e. `yahoo.com.` will not go through suffix-evaluation)

Another possible way of preventing arbitrary namespace creation could be a hook like https://github.com/openshift/kubernetes-namespace-reservation 

cc @thockin @philips as this may feed into broader DNS discussions

**Comment by thockin** [comment]
@bowei @kubernetes/sig-network-bugs 

https://docs.google.com/document/d/1V0Y1yPtjVa_EZ7jGaYLYnpAy5FNjcb0Y4NTQTUb3eSY/edit
