### ISSUE TITLE
kubectl top is failed in proxy environment

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#60544]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
`kubectl top` command is failed by the following error message when running `kubectl top` in proxy environment(export http_proxy=...).
```
error: failed to unmarshall heapster response: invalid character '\x15' looking for beginning of value
```

This error was caused by accessing the server listening on https with http.
Actually, kube-apiserver was accessed by http request. (I found a following kube-apiserver log)
```
http: TLS handshake error from 10.130.117.156:51248: tls: first record does not look like a TLS handshake
```

`kubectl top` command accesses to cluster addon heapster.
heapster listens to access of http.
But, kube-apiserver listens to access of https.

I think that the reason is a difference of destination address between Request structure and URL structure (in Request structure).
* Request structure is in RoundTrip function in staging/src/k8s.io/apimachinery/pkg/util/proxy/transport.go

Request structure example is shown as follow.

* http://10.244.0.121:8082 = Heapster Pod URI
  https://10.130.116.37:6443 = kube-apiserver URI

```
Method:GET
URL:http://10.244.0.121:8082/apis/metrics/v1alpha1/nodes?labelSelector=
Proto:HTTP/2.0
ProtoMajor:2
ProtoMinor:0
Header:map[
	X-Forwarded-For:[10.130.116.37]
	Accept:[application/json, */*]
	User-Agent:[kubectl/v1.9.3 (linux/amd64) kubernetes/d283541]
	Accept-Encoding:[gzip]
]
Body:<nil>
GetBody:<nil>
ContentLength:0
TransferEncoding:[]
Close:false
Host:10.130.116.37:6443
Form:map[]
PostForm:map[]
MultipartForm:<nil>
Trailer:map[]
RemoteAddr:10.130.116.37:37458
RequestURI:/api/v1/namespaces/kube-system/services/http:heapster:/proxy/apis/metrics/v1alpha1/nodes?labelSelector=
TLS:0xc42bbe2420
Cancel:<nil>
Response:<nil>
ctx:0xc42bc39740}I0223 01:58:34.062603
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others: 
  create kubernetes cluster in proxy environment
    export http_proxy=...
    export https_proxy=...

**Comment by devopsop** [comment]
I have the exact same problem

**Comment by devopsop** [comment]
Fixed the problem by commenting all the proxy env variables in the kube-api manifest

**Comment by shun-miyoshi-com** [comment]
@devopsop thank you your comment.
But, your idea is just a temporary measure. It won't solve the actual cause of the problem.
I posted a one of solution of this issue. (https://github.com/kubernetes/kubernetes/pull/60545)
