### ISSUE TITLE
pkg/client/auth/openstack does not persist the token it obtains

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/kubernetes#60541]
/kind feature

**What happened**:
The go client openstack auth provider used by kubectl does not persist the token it obtains. Every time kubectl is invoked, the openstack auth provider obtains a new token from Keystone. Because the token is typically long-lived[0], it can be persisted locally until it expires, or is revoked. Persisting the token will significantly reduce the load on the Keystone identity provider.

[0] By default, the token expires after 1 hour, but longer durations (8-24 hours) are common.

**What you expected to happen**:
The openstack auth provider persists the token it obtains, and thereafter obtains a new token from Keystone only when the current token has expired, or is revoked.

**How to reproduce it (as minimally and precisely as possible)**:
1. [Configure kubectl with openstack auth provider](https://github.com/dims/k8s-keystone-auth#new-kubectl-clients-v180-and-later)
2. Invoke kubectl multiple times while observing the Keystone access log

**Anything else we need to know?**:
The use case is not unique. For example, the gcp auth provider does persist the token it obtains.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.8

**Comment by dlipovetsky** [comment]
I'm working on a PR.

**Comment by dlipovetsky** [comment]
@kubernetes/sig-openstack-feature-requests

**Comment by dims** [comment]
@dlipovetsky sounds good. looking forward to seeing the PR. thanks!

**Comment by dlipovetsky** [comment]
@dims I've made progress and will keep working on the PR., but I just became aware of [support for exec-based, out-of-tree auth providers](https://github.com/kubernetes/kubernetes/pull/59495) may land in v1.10. I have not seen any indication that in-tree auth providers will be deprecated.

The exec-based auth provider means the `openstack` command-line client can be used to get a token. On the other hand, an out-of-tree auth provider must cache tokens using its own storage, because it cannot use the kubeconfig. The [`openstack` command-line client does not support caching tokens](https://github.com/openstack/python-openstackclient/blob/stable/queens/doc/source/cli/man/openstack.rst), as far as I know. Options are to add caching to the `openstack` command-line client, or write a caching wrapper.
