### ISSUE TITLE
Wrong node disk capacity calculation when imageFs and nodeFs mounts on different device

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#60558]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

I mount `/dev/vda`(500G) as imageFs and mounted `/dev/vdb`(50G) as nodeFs. 

When the pods on this node somehow use more than 50G storage ( e.g. temporary data writing to `devicemapper` for docker, or docker logs ) which is actually all written to `/dev/vda`, but these pods will begin to evict because of `DiskPressure`. There is still 450G-ish space left on `/dev/vda` and `/dev/vda` almost remains empty and it should not be a `DiskPressure` at all.

It seems like kubelet doesn't find that devices of imageFs and nodeFs are different.

**What you expected to happen**:

Kubelet don't update its status into `DiskPressure` when spare space is plenty.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
related #35136

**Comment by dashpole** [comment]
There are two different eviction signals, one for each device.  You can set `--eviction-hard=nodefs.available<10%`, or `--eviction-hard=imagefs.available<10%`.  If either partition crosses the threshold, you get DiskPressure.

What version of kubernetes is your node running?  Are you running with `--feature-gates=LocalStorageCapacityIsolation=true`?

**Comment by lw8008** [comment]
I got below logs from kubelet log:

I0807 20:22:54.903109   23335 helpers.go:823] eviction manager: observations: signal=nodefs.available, available: 9939024Ki, capacity: 10230Mi, time: 2018-08-07 20:22:40.580607795 +0800 CST m=+1099.270868592

i'm wondering how the capacity 10g comes from?

**Comment by lw8008** [comment]
I also got weird behavior for kubelet evict pod but has lots of free space in the node.

below comes from kubelet log:

I0807 20:22:54.903109 23335 helpers.go:823] eviction manager: observations: signal=nodefs.available, available: 9939024Ki, capacity: 10230Mi, time: 2018-08-07 20:22:40.580607795 +0800 CST m=+1099.270868592

i'm wondering how the capacity 10g comes from?

**Comment by instantlinux** [comment]
I would like this error message improved:
```
Jan  8 01:07:30 vinson kubelet[1514]: I0108 01:07:30.586617    1514 image_gc_manager.go:300] [imageGCManager]:
 Disk usage on image filesystem is at 85% which is over the high threshold (85%). Trying to free 481610956 bytes down to the low threshold (80%).
```
It doesn't give device name or mount point so I can't figure out which filesystem it's complaining about (there is plenty of space on mounted volumes, so perhaps it's looking at the thinpool LVM which I'm using for image storage).

Also, the garbage-collector barfs when it encounters statically-launched images started by _docker run_ rather than k8s.
