### ISSUE TITLE
Transactions for Entities and Event Recordings

### ISSUE THREAD

**Issue by simon3z** [kubernetes/kubernetes#6055]
It should be possible to update an entity and record events about interesting changes in a transactional fashion.

For example at the moment:

```
events = compare_entity_changes(old_entity, new_entity)
record_events(events)
update_entity(old_entity, new_entity)
```

Which means that if the controllers are crashing between record_event and update_entity the event(s) are recorded but the entity is not updated, leading to the re-generation of the same events once the controller is up again.

It should be possible to records the events and update the entity in an transactional all-or-nothing fashion.

Obviously this can be extended to any type of entity transaction (not just event recordings).

@bgrant0607 maybe #2904 is needed to actually do anything about this issue. Correct?
Are you using any other strategy for transactions in the current code?

**Comment by bgrant0607** [comment]
Yes, multi-object transactions would be necessary.

No, we haven't built our own transaction mechanism.

**Comment by smarterclayton** [comment]
We have no plans to do this in the near term, and if we do use transactions it would be extremely judiciously.

**Comment by lmktfy** [comment]
Relevant, I think, to #135497
