### ISSUE TITLE
Is it necessary to drain pods when upgrading kubelet on woker node

### ISSUE THREAD

**Issue by mdianjun** [kubernetes/kubernetes#60556]
I am upgrading k8s from 1.8.4 to 1.9.3 in my cluster with 300 nodes. If pods are drained when upgrading kubelet on worker nodes, it will result in workloads migration which is not our expectation.

Is it necessary to perform "drain pods" ? 

/sig cluster-ops

**Comment by dgabrysch** [comment]
From my point of view I think it's not necessary :) kubelet is starting/restarting/stopping pods to reach the desired state so it shouldn't stop your pods or Something.
