### ISSUE TITLE
cephfs mount error in non-default namespace

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#60568]
I test cephfs pv、pvc and pod mount with cephfs successfully in default namespace. But when I test these in other namespace, although I config ceph secret in this namespace, pod mount pvc still failed.
The config of PV is like this:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iot-mysql-ceph-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.110.20.161:6789
      - 10.110.20.162:6789
      - 10.110.20.163:6789
    user: admin
    secretRef:
      name: ceph-secret
      namespace: lynnyuan
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

The config of PVC is like this:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iot-mysql-ceph-pvc
  namespace: lynnyuan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

The config of pod is like this:
apiVersion: v1
kind: Pod
metadata:
  name: iot-mysql-tsdb-pod
  namespace: lynnyuan
spec:
  volumes:
  - name: iot-mysql-ceph-pvc-vlm
    persistentVolumeClaim:
      claimName: iot-mysql-ceph-pvc
  containers:
  - name: iot-mysql-tsdb-ctn
    image: registry.dev161.com:5000/iot/mysql:5.5.59
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: iot-mysql-ceph-pvc-vlm
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root"

The status of pv and pvc is bound, the status of pod is ContainerCreating, pod log is like this:
  Warning  FailedMount            1m    kubelet, slave1    MountVolume.SetUp failed for volume "iot-mysql-ceph-pv" : CephFS: mount failed: mount failed: exit status 2
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/8d0b63dd-1c65-11e8-8f5f-0050568848e8/volumes/kubernetes.io~cephfs/iot-mysql-ceph-pv --scope -- mount -t ceph -o name=admin,secret=AQBsMJFaZGakARAAZ+RYtrkCnX0/aa+jFp69DA== 10.110.20.161:6789,10.110.20.162:6789,10.110.20.163:6789:/like /var/lib/kubelet/pods/8d0b63dd-1c65-11e8-8f5f-0050568848e8/volumes/kubernetes.io~cephfs/iot-mysql-ceph-pv
Output: Running scope as unit run-5703.scope.
mount error 2 = No such file or directory
  Warning  FailedMount  1m  kubelet, slave1  MountVolume.SetUp failed for volume "iot-mysql-ceph-pv" : CephFS: mount failed: mount failed: exit status 2

**Comment by mlmhl** [comment]
Did you specify the `Path` field of `CephFSPersistentVolumeSource`? I didn't find it in your PV config.

**Comment by like-inspur** [comment]
I add path filed under cephfs for ceph pvc definition. but the problem still exists. @mlmhl  @freeformz @brosner @gnufied

**Comment by mlmhl** [comment]
@like-inspur 
Could you post your secret config?

**Comment by like-inspur** [comment]
The config of secret is like this:
apiVersion: v1
data:
  key: QVFCc01KRmFaR2FrQVJBQVorUll0cmtDblgwL2FhK2pGcDY5REE9PQ==
kind: Secret
metadata:
  name: ceph-secret
  namespace: lynnyuan
type: kubernetes.io/rbd

**Comment by likerj** [comment]
Thank you! @mlmhl @dims @freeformz
