### ISSUE TITLE
'kubectl describe node' got a wrong PodCIDR

### ISSUE THREAD

**Issue by shenxg13** [kubernetes/kubernetes#60573]
**What happened**:
Flannel subnet:
[root@192-168-0-53-kube02 ~]# cat /run/flannel/subnet.env 
FLANNEL_NETWORK=10.16.0.0/16
FLANNEL_SUBNET=10.16.25.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false

Pod IP:
[root@192-168-0-52-kube01 ~]# kubectl get pods -o wide
NAME                          READY     STATUS    RESTARTS   AGE       IP           NODE
dep-nginx-1-97759488f-d6wxt   1/1       Running   0          22m       10.16.25.5   192-168-0-53-kube02
dep-nginx-1-97759488f-tzkwj   1/1       Running   0          22m       10.16.25.4   192-168-0-53-kube02

but kubectl describe node:
[root@192-168-0-52-kube01 ~]# kubectl describe node 192-168-0-53-kube02
Name:               192-168-0-53-kube02
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=192-168-0-53-kube02
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Sat, 24 Feb 2018 15:56:18 +0800
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Wed, 28 Feb 2018 17:27:31 +0800   Sat, 24 Feb 2018 15:56:18 +0800   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Wed, 28 Feb 2018 17:27:31 +0800   Sat, 24 Feb 2018 17:03:31 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 28 Feb 2018 17:27:31 +0800   Sat, 24 Feb 2018 17:03:31 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready            True    Wed, 28 Feb 2018 17:27:31 +0800   Sat, 24 Feb 2018 17:03:41 +0800   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.0.53
  Hostname:    192-168-0-53-kube02
Capacity:
 cpu:     2
 memory:  4046936Ki
 pods:    110
Allocatable:
 cpu:     2
 memory:  3944536Ki
 pods:    110
System Info:
 Machine ID:                 8adb614084e14601aef16b0e94bc54ad
 System UUID:                35270B42-911F-D801-7D01-5D7814895F54
 Boot ID:                    9341d601-6947-44fd-bc54-17e6a9e8900f
 Kernel Version:             3.10.0-693.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://17.12.0-ce
 Kubelet Version:            v1.8.7
 Kube-Proxy Version:         v1.8.7
**PodCIDR:                     10.16.0.0/24**
ExternalID:                  192-168-0-53-kube02
Non-terminated Pods:         (2 in total)
  Namespace                  Name                           CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                           ------------  ----------  ---------------  -------------
  default                    dep-nginx-1-97759488f-d6wxt    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    dep-nginx-1-97759488f-tzkwj    0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  0 (0%)        0 (0%)      0 (0%)           0 (0%)
Events:         <none>
[root@192-168-0-52-kube01 ~]#

**What you expected to happen**:
The PodCIDR should be 10.16.25.0/24 I think.

**How to reproduce it (as minimally and precisely as possible)**:
[root@192-168-0-52-kube01 ~]# ps -ef|grep flanneld
root       828     1  0 Feb24 ?        00:01:14 /usr/local/bin/flanneld -etcd-cafile=/etc/kubernetes/ssl/k8s-root-ca.pem -etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem -etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem -etcd-endpoints=https://192.168.0.51:2379 -etcd-prefix=/coreos.com/network/ -iface=ens192

[root@192-168-0-52-kube01 ~]# cat /etc/cni/net.d/10-flannel.conflist 
{
    "name": "cbr0",
    "plugins": [
    {
        "type": "flannel",
        "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
        }
    }
    ]
}
[root@192-168-0-52-kube01 ~]#

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
[root@192-168-0-52-kube01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@192-168-0-52-kube01 ~]#

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vfreex** [comment]
Hi, can you put the results of the following commands on 192-168-0-53-kube02?

```
docker info
ip a
ps -ef | grep kubelet
```

**Comment by shenxg13** [comment]
[root@192-168-0-53-kube02 ~]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: 192-168-0-53-kube02
ID: OOHR:HXRU:J7RJ:KLY5:FYHA:7LDC:MFZP:WIS6:HFZ4:RTLA:COSA:IFL3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://9d3u26z6.mirror.aliyuncs.com/
Live Restore Enabled: false
[root@192-168-0-53-kube02 ~]#

[root@192-168-0-53-kube02 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:8b:7a:fc brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.53/24 brd 192.168.0.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8b:7afc/64 scope link 
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 3e:bc:d5:be:69:42 brd ff:ff:ff:ff:ff:ff
    inet 10.16.25.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::3cbc:d5ff:febe:6942/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:9b:f7:63:38 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP qlen 1000
    link/ether 0a:58:0a:10:19:01 brd ff:ff:ff:ff:ff:ff
    inet 10.16.25.1/24 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::e4f9:e6ff:fe1b:bc2d/64 scope link 
       valid_lft forever preferred_lft forever
7: veth54d9c1be@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP 
    link/ether de:55:c6:c5:e8:72 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::dc55:c6ff:fec5:e872/64 scope link 
       valid_lft forever preferred_lft forever
[root@192-168-0-53-kube02 ~]#

[root@192-168-0-53-kube02 ~]# ps -ef | grep kubelet
root      1184     1  1 Mar06 ?        03:29:01 /usr/local/bin/kubelet --address=192.168.0.53 --pod-infra-container-image=192.168.0.41/kube/pause-amd64:3.0 --bootstrap-kubeconfig=/etc/kubernetes/ssl/kubelet-bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cert-dir=/etc/kubernetes/ssl --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --cgroup-driver=systemd --cluster_dns=10.17.0.2 --cluster_domain=y.kube --v=2 --rotate-certificates --feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true
root     21415 21117  0 11:21 pts/0    00:00:00 grep --color=auto kubelet
[root@192-168-0-53-kube02 ~]#
