### ISSUE TITLE
Allow SecurityContext to be injected into pods via PodPreset

### ISSUE THREAD

**Issue by kevinjqiu** [kubernetes/kubernetes#60583]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

We would like the ability to have pods running in the cluster to have a Security Context preset for them, e.g., to disable running as root.

Currently, PodPreset only allows environment variables and volume mounts to be injected into the pod.

**What you expected to happen**:

Allow SecurityContext to be injected into the pods.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

I haven't found related discussion anywhere, but if this has been discussed before, please link and close the issue. Thanks.

**Comment by kevinjqiu** [comment]
I didn't find `sig/security` label so I guess api-machinery is the closest sig? (since it's partly related to the PodPreset api spec), but please change it to a more relevant sig you see fit. Thanks.

**Comment by wackxu** [comment]
I think you can try `PodSecurityPolicy`, which can  apply defaults to unset fields on a pod in order to admit it.

**Comment by liggitt** [comment]
[PodSecurityPolicy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) will default and enforce aspects of the pod security context

/close
