### ISSUE TITLE
[failing test] Nginx should conform to Ingress spec

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60588]
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-slow
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-slow

/priority failing-test
/kind bug
/status approved-for-milestone
/sig network

cc @jdumars @jberkus @bowei @MrHohn

**Comment by MrHohn** [comment]
Failure has the same symptom as https://github.com/kubernetes/kubernetes/issues/60381:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:673
Test Panicked
/usr/local/go/src/runtime/panic.go:491
```

**Comment by krzyzacy** [comment]
thanks @MrHohn , the slow suites are back to green now!
