### ISSUE TITLE
Defaulting mechanism for APIService.caBundle missing

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#60582]
The caBundle field in the aggregator's APIService type is required to be set: https://github.com/kubernetes/kubernetes/blob/9baae557daf7a505ee81d0383feb4b4d397f1aec/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go#L56

If we want to implement a cert generation and rotation controller (which is done downstream by OpenShift and could be done as third party component) for aggregated apiserver keys and certs, it is still necessary to set the caBundle field to the used CA.

It shouldn't be necessary to put this CA into each APIService object, especially because it makes those manifests different for every cluster. Instead they should be generic. Think of  `helm install some-apiserver`.

We want to have some kind of defaulting mechanism that allows to auto-default the caBundle field to a cluster-global value.

**Comment by sttts** [comment]
The same holds for admission webhooks: https://github.com/kubernetes/kubernetes/blob/2e3cb71583af376ef9e963e0441a57235c7dc885/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L263

**Comment by deads2k** [comment]
If you want to be able to rotate easily at a later date, I think we're looking at a server-wide default for trusting serving certificates (this is different than trusting client certificates).

**Comment by liggitt** [comment]
Would that not reasonably be the system roots?

**Comment by sttts** [comment]
> Would that not reasonably be the system roots?

I don't think we want to put a kube cluster only CA into the system root. That's IMO one layer too deep. The system doesn't have to trust the certs, only the apiserver has to.

**Comment by JoelSpeed** [comment]
I agree with @sttts , that would be one layer too deep.

This feature would be great for us. We are setting up a bunch of custom API servers and Mutating Webhooks. They all have certificates signed by the same CA (using the K8s CSR API) and we are having to substitute the same CA Bundle over and over. It makes deploying harder and since we don't want to check certificates in, we basically can't version control our `APIService` and `MutatingWebhookConfiguration` objects.

**Comment by munnerz** [comment]
FWIW, we are *not* using the K8S CSR API to manage these certificates currently.

As far as I was aware, this API was designed mostly for Node TLS bootstrap, so we prefer to manage our own CA (either through automation such as cert-manager or manually). It'd be great if this defaulting is not bound directly to the k8s certificates API, *or if it is*, we make a recommendation that all aggregated APIs/webhooks should use this API.

**Comment by munnerz** [comment]
(we = Jetstack, not Joel and I, sorry for the confusion in wording)

**Comment by liggitt** [comment]
API validation did not actually require this field be set. The field tag was corrected to show it was actually an optional field. When no CA bundle is specified, the system roots are used to secure the connection.

/close
