### ISSUE TITLE
go1.10 failing test: k8s.io/apiserver/pkg/authentication/request/x509

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#60598]
In go1.10, the following test fails:
```
$ go test -v ./vendor/k8s.io/apiserver/pkg/authentication/request/x509
=== RUN   TestX509
--- FAIL: TestX509 (0.02s)
        x509_test.go:700: server cert: Expected error, got none
=== RUN   TestX509Verifier
--- FAIL: TestX509Verifier (0.00s)
        x509_test.go:855: server cert disallowed: Expected error, got none
FAIL
FAIL    k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/x509       0.039s
```

cc: @kubernetes/sig-auth-bugs @liggitt

**Comment by liggitt** [comment]
go 1.10, kube 1.11, so confusing. Will look

**Comment by cblecker** [comment]
cc: @sttts too
I know Stefan bumped cfssl here: https://github.com/kubernetes/kubernetes/pull/60373
But checking out that PR and running the test locally didn't change the above failure

**Comment by liggitt** [comment]
Yeah, the unit tests use precanned test certs, not cfssl

**Comment by liggitt** [comment]
Looks like it could be an issue with go. From the release notes:

> crypto/x509
> Extended key usage restrictions are similarly now checked all at once. As a result, after a certificate has been validated, now it can be trusted in its entirety. It is no longer necessary to revalidate the certificate for each additional name or key usage

Will dig tomorrow, but it seems like 1.10 may have changed the behavior of key usage verification.

**Comment by hzxuzhonghu** [comment]
@liggitt @cblecker This is indeed cause by `// ServerAuth in a CA permits ClientAuth in the leaf.` https://github.com/golang/go/blob/master/src/crypto/x509/verify.go#L582-L588

**Comment by liggitt** [comment]
> This is indeed cause by // ServerAuth in a CA permits ClientAuth in the leaf. https://github.com/golang/go/blob/master/src/crypto/x509/verify.go#L582-L588

that comment doesn't make sense... the cert being checked is not a CA

**Comment by hzxuzhonghu** [comment]
Yes, but i think this is the root cause.

**Comment by liggitt** [comment]
similar issue reported in https://github.com/golang/go/issues/23884, fixed in https://github.com/golang/go/commit/0681c7c31b5922f08f31404023e6b295f35812fe

**Comment by liggitt** [comment]
@cblecker go1.10.1 has been released with a fix for this issue if you want to bump the branch testing against go1.10

**Comment by cblecker** [comment]
@liggitt Yup, saw that. Once the upstream docker images for golang are updated, then I'll update my PR.

**Comment by cblecker** [comment]
Looks like this is fixed. Thanks for diagnosing, @liggitt ! Going to close this out, but if anyone wants to track the rest of the upgrade, it's happening in https://github.com/kubernetes/kubernetes/pull/60597.
