### ISSUE TITLE
Tests failing with "Unknown host: storage.googleapis.com"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#60593]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
pull-kubernetes-e2e-kops-aws failed #60065 (see https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-e2e-kops-aws/77698/), with these complaints in build-log.txt:
```
...
W0228 19:37:19.722] ____Unknown host: storage.googleapis.com
W0228 19:37:19.742] ERROR: /go/src/k8s.io/kubernetes/build/debs/BUILD:83:1: no such package '@kubernetes_cni//file': Error downloading [https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz] to /root/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/external/kubernetes_cni/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz: Unknown host: storage.googleapis.com and referenced by '//build/debs:kubernetes-cni-data'.
W0228 19:37:20.119] ERROR: Analysis of target '//:push-build' failed; build aborted.
W0228 19:37:20.122] ____Elapsed time: 35.386s
W0228 19:37:20.123] ERROR: Build failed. Not running target.
...
```

**What you expected to happen**:
I expected the test infrastructure to not fail.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by BenTheElder** [comment]
Did this happen once or more than once? Given the number of builds we run it's not surprising that sometimes networking can flake, We do run on kubernetes :-)

This job generally fails due to AWS/Kops issues though, not push-build though, so this is somewhat surprising.

**Comment by MikeSpreitzer** [comment]
So far I have seen this just once.  A retest is queued.

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
The retest is running and well past that stage: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-e2e-kops-aws/77703/

**Comment by ixdy** [comment]
I've seen a few DNS failures recently. Not really sure what's going on.

**Comment by BenTheElder** [comment]
Yeah, I'm hoping it's just kube-dns which will hopefully behavior better after the next build-cluster upgrade :crossed_fingers: 
cc @MrHohn
