### ISSUE TITLE
kubeadm v1.10 release tracking issue

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#60608]
In following with history we will be curating action items here, but it's still a WIP, atm: https://github.com/kubernetes/kubeadm/milestone/5 

All non-bug-fixes for this release cycle should be merged, but there is still an ongoing list of bugs that folks may execute against for the remainder of the freeze and we will evaluating on a case-by-case basis.

/cc @detiber @jdumars @roberthbailey @kubernetes/kubernetes-release-managers @luxas @kubernetes/sig-cluster-lifecycle-misc

**Comment by jdumars** [comment]
Thank you for creating this issue!

**Comment by jberkus** [comment]
@timothysc 

Adding required tags.

Please use this issue to supply a frequent summary update of the issues you are tracking in the kubeadm repo and their status.  Especially, please call out and link to any bugs that are blockers for 1.10.

/kind feature
/priority critical-urgent

**Comment by jberkus** [comment]
@timothysc, @luxas can we have a general status update on the kubeadm issues? The issues themselves don't generally have status updates.  This is the last week before release, where are you with the kubeadm changes?

**Comment by timothysc** [comment]
@jberkus 

We're all green except for the 1.9-1.10 upgrade tests which appear to have other issues that are not kubeadm specific.  

Final default update PR is #61127 which will auto-close this issue.

**Comment by timothysc** [comment]
^ I don't know why we have this policy but it's ridiculous... @kubernetes/sig-contributor-experience-bugs

**Comment by jberkus** [comment]
@timothysc are there any 1.9-1.10 upgrade issues which aren't already represented by issues against kubernetes/kubernetes?  that is, are there any in the kubadm repo only?

**Comment by timothysc** [comment]
Not that I see atm, I still need to triage the inbound issues.
