### ISSUE TITLE
This might take a minute or longer

### ISSUE THREAD

**Issue by monique77** [kubernetes/kubernetes#60617]
Hi, People

Sorry my english is bad.  So, i need help!!!

I am using centos 7, e kuberletes v1.9 when execute command
i was looking ---> https://www.linuxtechi.com/install-kubernetes-1-7-centos7-rhel7/

kubeadm init not continue, stop 

[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING Port-6443]: Port 6443 is in use
	[WARNING Port-10250]: Port 10250 is in use
	[WARNING Port-10251]: Port 10251 is in use
	[WARNING Port-10252]: Port 10252 is in use
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[WARNING FileExisting-crictl]: crictl not found in system path
[certificates] Using the existing ca certificate and key.
[certificates] Using the existing apiserver certificate and key.
[certificates] Using the existing apiserver-kubelet-client certificate and key.
[certificates] Using the existing sa key.
[certificates] Using the existing front-proxy-ca certificate and key.
[certificates] Using the existing front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Using existing up-to-date KubeConfig file: "admin.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "kubelet.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "controller-manager.conf"
[kubeconfig] Using existing up-to-date KubeConfig file: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
<! ---------------HERE NOT TO DO NOTHING ----------------> i stop with Ctrl+c

i not using proxy, my /etc/resolv.conf using dns internal

**What happened**: nothing, long time, so i stop with ctrl+c

**What you expected to happen**: start master-cluster

**How to reproduce it (as minimally and precisely as possible)**: kubeadm init

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9
- Cloud provider or hardware configuration: i dont know speak
- OS (e.g. from /etc/os-release): lasted version
- Kernel (e.g. `uname -a`):
- Install tools: docker
- Others:

**Comment by dixudx** [comment]
> [WARNING Port-6443]: Port 6443 is in use
[WARNING Port-10250]: Port 10250 is in use
[WARNING Port-10251]: Port 10251 is in use
[WARNING Port-10252]: Port 10252 is in use

@monique77 These ports are using by other processes.

Please run `kubeadm reset` to revert any changes made to this host by `kubeadm init`. Or try to manually stop related processes.

Also please run `docker ps -a | grep kube` to find related container logs, such as apiserver.

**Comment by monique77** [comment]
Hi, dixudx  tks so much, worked!!!! But now i have others problems.

My objective is access dasboard kubernetes but ,  i see in log erros

When i execute 
kubectl apply -f https://git.io/weave-kube
The connection to the server x.x.x.x:8080 was refused - did you specify the right host or port?

Log kubernetes
E0301 19:49:43.573432       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.ReplicationController: Get https://x.x.x.x:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp x.x.x.x:6443: getsockopt: connection refused

Log docker
E0301 19:58:21.874268       1 reflector.go:205] k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go:590: Failed to list *v1.Pod: Get https://x.x.x.x:6443/api/v1/pods?fieldSelector=spec.schedulerName%3Ddefault-scheduler%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: dial tcp x.x.x.x:6443: getsockopt: connection refused

I dont know to do... because i execute this commands for authentication on dasboard kubernetes, bu i not sucess..  please help meee
ubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/pki/ca.crt --embed-certs=true --server='x.x.x.x'
kubectl config set-credentials admin --client-certificate=/etc/kubernetes/pki/ca.key --embed-certs=true --client-key=/etc/kubernetes/pki/ca.key
kubectl config set-context kubernetes --cluster=kubernetes --user=admin
kubectl config use-context kubernetes

kubectl config set-cluster demo-cluster --server=http://172.16.1.82:8080

**Comment by monique77** [comment]
Hi, People 

Now is worked!!!

**Comment by dhabierre** [comment]
Can you provide the 2034 link please?

**Comment by monique77** [comment]
https://github.com/kubernetes/dashboard/issues/2034
