### ISSUE TITLE
StatefulSet PodTemplateSpec Validation.

### ISSUE THREAD

**Issue by kow3ns** [kubernetes/kubernetes#60619]
**FEATURE REQUEST?**:
 /kind feature

We need better validation for the PodTemplateSpec of the StatefulSet kind. Currently its not using the default api validation for PodTemplateSpec because the volume claims will fail. We need to implement a solution that enables validation for the kind. The relevant code is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L55-L58).

**Comment by dixudx** [comment]
/assign

I would work on this.

**Comment by krmayankk** [comment]
i dont see a PR still @dixudx  are you still working on this ?

**Comment by dixudx** [comment]
Not yet. @krmayankk You can pick it up.

**Comment by krmayankk** [comment]
i will make a PR for this next week. Internally we already haven this check enabled when deploying statefulsets
