### ISSUE TITLE
Schedule even if extender is not available when using extender

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#60616]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
When using scheduler extender, if the extender is not available scheduling of all pods fail.
**What you expected to happen**:
I believe that we should let the scheduling happen but display error message that extender is failing.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yastij** [comment]
cc @bsalamat

**Comment by k82cn** [comment]
it dependents, some extender are used to sync up external resources.

**Comment by bsalamat** [comment]
I actually believe failing fast (i.e., not scheduling any pods) is a better strategy here. Our current behavior draws the attention of a cluster admin to the problem in the cluster. Being resilient to extender failures could cause such failures to remain unnoticed for a long time.

**Comment by ravisantoshgudimetla** [comment]
> I actually believe failing fast (i.e., not scheduling any pods) is a better strategy here

I agree with you but depending on the priority of extender(say if it is important or not), I think we should be lenient as well. An example would be usage based scheduling extender that I demonstrated last week. While it would be a definite advantage to have such extender, we should allow the scheduling to happen if extender is not available. This is also especially important if the extender runs in non-HA mode and frequent failure is a possibility. How about adding a flag like ignore-extender-failure(if we configure extender) to kube-scheduler.

**Comment by bsalamat** [comment]
> How about adding a flag like ignore-extender-failure(if we configure extender) to kube-scheduler.

What you said about non-critical extenders makes sense. I would add a flag to each extender's config (in scheduler policy config) to indicate whether the extender is critical or ignorable.

**Comment by ravisantoshgudimetla** [comment]
Thanks @bsalamat 
/cc @aveshagarwal

**Comment by resouer** [comment]
As I recent changed a lot of the code base of scheduler extender. I will take this if it's still help wanted.

**Comment by ravisantoshgudimetla** [comment]
Sure @resouer. Thanks for picking this up :)
