### ISSUE TITLE
kubernetes cassandra operator error - i getting below error while creating cassandra operator for kubernetes. Have anyone encountered this error before? 

### ISSUE THREAD

**Issue by arunkumar9050** [kubernetes/kubernetes#60620]
#kubectl create -f example-cassandra-cluster.yaml 

error: unable to recognize "example-cassandra-cluster.yaml": no matches for cassandra.database.instaclustr.com/, Kind=CassandraCluster
#cat   example-cassandra-cluster.yaml
apiVersion: "cassandra.database.instaclustr.com/v1beta2"
kind: "CassandraCluster"
metadata:
name: "example-cassandra-cluster"
spec:
size: 3
version: "3.11"
pod:
resources:
  limits:
    memory: "512Mi"

**Comment by kow3ns** [comment]
This is the wrong place to ask this question. I'm not sure which cassandra-operator you are using, but it's not part of core kubernetes. Please feel free to ask this question on slack (try the sig-apps channel), or stack-overflow.
/close
