### ISSUE TITLE
k8s ignore graceperiod while send stop to docker container

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#60631]
/kind bug

k8s ignore grace period and always set it to 2 second while stop docker container:
level=debug msg="Calling POST /v1.31/containers/9dabaac5698f3b6f628a6b812cc962c4913a2598656ba42e88b02877e545abfa/stop?t=2"
 - - -
GracePeriod must be provided as arg to docker stop

Tested with docker versions 17.03 - 17.12 ce

- Kubernetes version: v1.8.7.1-a
- Cloud provider or hardware configuration: Local installation
- OS (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- Kernel: Linux hostname 4.14.4-041404-generic
 - - -
I've try specify grace period by:
terminationGracePeriodSeconds: 300
and --grace-period=30 even --grace-period=0 ignored

Any suggestions?

Thanks!

**Comment by Nefelim4ag** [comment]
Looks like:
https://github.com/kubernetes/kubernetes/blob/2d1626028ed0d091008e65d7e379470a098942ff/pkg/util/version/version.go#L42
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/controller/node/util/controller_utils.go#L133

Causes to force deletion on pod with zero grace period.
But why bumped to 2 seconds, strange.

**Comment by dixudx** [comment]
This method has already been removed in #53447, since v1.9.

**Comment by Nefelim4ag** [comment]
Thanks!
 - - -
I fix that by change tag version to v1.8.7-a1
