### ISSUE TITLE
opencl with the gpu on kubernetes 

### ISSUE THREAD

**Issue by gofrane** [kubernetes/kubernetes#60643]
hello,
Please is there any possibility to run a opencl GPU applications on kubernetes ?

**Comment by lee-b** [comment]
/reopen
/remove-lifecycle rotten

This was never answered, and it seems crucial that k8s should provide OpenCL, if it's to be an open platform for ML workloads, independent of particular hardware vendors.

**Comment by zvonkok** [comment]
@gofrane @lee-b For OpenCL application one needs an OpenCL runtime installed by the vendor. The first step is to enable the GPU on your k8s cluster. See e.g. NVIDIAs documentation on how to do that. 

A GPU Pod e.g. `nvidia/cuda:11.1-base-ubuntu18.04` will have the NVIDIA OpenCL runtime installed (`/usr/lib64/libnvidia-opencl.so.450.80.02`) in the container. 

Here are some sample applications you can use in a Dockerfile base on the above-mentioned image to build a simple OpenCL application on k8s http://developer.download.nvidia.com/compute/cuda/3_0/sdk/website/OpenCL/website/samples.html
