### ISSUE TITLE
AWS ASG nodes may be kicked from the cluster by kube-controller-manager

### ISSUE THREAD

**Issue by chrisseto** [kubernetes/kubernetes#60644]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
* Nodes spun up by ASG have a variable delay at with tags are applied to them. The metadata API is not subject to this delay.
* Nodes poll the metadata API for information where the master(s) poll the actual EC2 API.
* This may cause a node to join a cluster and immediately be removed by the master (`kube-controller-manager`) due to it's lack of tags.
* Kubelet does not appear to have a rejoin functionality, resulting in a "zombie" node.

**What you expected to happen**:
Nodes should join the cluster and remain in it or kubelet should attempt to rejoin the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an ASG (I was using spot instances, uncertain if that has any relation) using a kops launch configuration.
2. Scale up to X nodes.
3. Notice that ~X/2 nodes did not join the cluster

**Anything else we need to know?**:
I was able to correct this issue (hackily) by adding the following into one of the kops start up scripts:
```bash
echo -e "Waiting for EC2 API to catch up... "
HOSTNAME="$(curl 169.254.169.254/latest/meta-data/hostname)"
REGION="$(curl 169.254.169.254/latest/meta-data/placement/availability-zone | sed -e 's/\(.*\)[a-z]/\1/')"

RETRIES=0
until [ $RETRIES -eq 3 ] || aws ec2 wait instance-exists --region $REGION --filters "Name=private-dns-name,Values=$HOSTNAME" "Name=instance-state-name,Values=running" "Name=tag:KubernetesCluster,Values=CLUSTERNAME"; do
  sleep $(( RETRIES++ ))
done
echo "Done"
```

I *think* kubelet should wait for the EC2 API and the EC2 metadata API to synchronize before attempting to join the cluster. I'm still looking for the best place to add that into the code, any pointers would be appreciated.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `AWS`
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-100-102-155 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`
- Install tools: `kops`
- Others: `N/A`

**Comment by chrisseto** [comment]
https://github.com/kubernetes/kubernetes/issues/57382

**Comment by mahmoudm** [comment]
Can we re-open this issue given that the linked issue + merged PR don't actually address the problem presented here? We are still encountering this race on 1.9.7 which has the linked fix. This is because the describeInstance API used by the kubelet does not filter by tag, while the controller-manager one does, thus still causing it to delete it and creating a zombie node. @chrisseto
