### ISSUE TITLE
Order of readiness probe and liveness probe

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#60647]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently, readiness probe and liveness probe are executed concurrently. But, IMO, liveness probe may only start after readiness probe succeeds, i.e., pod has been started successfully
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by DaoWen** [comment]
This appears to be a duplicate of #27114.

**Comment by andyxning** [comment]
Close this via [above comment](https://github.com/kubernetes/kubernetes/issues/60647#issuecomment-373839150).
