### ISSUE TITLE
isNotFound function is not working correctly in openstack cloudprovider

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#60658]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

/kind bug

**What happened**: when using cloud controller manager, `InstanceExistsByProviderID` function is not working correctly. Common function `isNotFound` is not return correct value if instance is deleted from cloudprovider.

**What you expected to happen**: I except that code should end to row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_instances.go#L131 if node is deleted from cloudprovider.

**How to reproduce it (as minimally and precisely as possible)**:

1. create kubernetes cluster to openstack cloudprovider using cloud controller manager
2. add debug print https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L417 after this row `glog.V(2).Infof("ensureNodeExistsByProviderIDOrExternalID: %s %v", exists, err)`
3. after cluster is up and running, delete one node from openstack and see the cloud controller log file
4. the result is `I0301 18:11:57.243500       1 node_controller.go:432] ensureNodeExistsByProviderIDOrExternalID: %!s(bool=false) Resource not found`

If this works correctly it should return nil as error, from this row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_instances.go#L131. But now the code is not going there because `isNotFound` is not working correctly. I debugged this `isNotFound` function, and when instance is deleted from openstack https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L608 this row variable e is `nil` and ok is `false`. So it is not working as should.

**Anything else we need to know?**: I am thinking that is this `isNotFound` working correcly in any other place currently in openstack cloudprovider.
 
**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: openstack mitaka

cc @anguslees as you are author of this `isNotFound` function. I am thinking could we just fix that using dirty way `err.Error() == ErrResNotFound` where ErrResNotFound is constant `var ErrResNotFound = "Resource not found"`

**Comment by dims** [comment]
@zetaab is this now fixed with the changes referenced?

**Comment by zetaab** [comment]
@dims yes all fixed this can be closed
