### ISSUE TITLE
A TokenRequestAuthorizer should allow serviceaccounts to request tokens for themselves

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#60659]
/sig auth
/kind feature

@liggitt wdyt?
@kubernetes/sig-auth-feature-requests 

ref https://github.com/kubernetes/kubernetes/issues/58790

**Comment by liggitt** [comment]
I'd be really hesitant to do that. Cons:
* a node could take a requested service account token (carefully required to be bound to a pod bound to the requesting node), turn around and create a token bound only to the service account
* a compromised pod would automatically have credential creating power

what are the pros?

**Comment by cjcullen** [comment]
I think the one pro is: 
- Applications don't need special interaction from kubelet in order to get tokens for the thing they want to talk to.

I agree there are sticky issues around expiration extensions, and binding erasure, but I don't think it's a completely crazy idea.

**Comment by mikedanese** [comment]
Closing this, let's reopen when we find a compelling reason to.
