### ISSUE TITLE
API server should expose a JWKS URL of it's current valid svcacct token keys

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#60660]
/sig auth
/kind feature

@kubernetes/sig-auth-feature-requests 

ref #58790

**Comment by mikedanese** [comment]
I'll fix this once https://github.com/square/go-jose/pull/179 goes in.

**Comment by fkpwolf** [comment]
@mikedanese does it get fixed? If so, what's the JWKS URL currently?

**Comment by mikedanese** [comment]
It's not fixed yet.

**Comment by janwillies** [comment]
would be nice to use this in envoy with `remote_jwks`
