### ISSUE TITLE
Kubelet does not garbage collect docker images based on devicemapper disk usage

### ISSUE THREAD

**Issue by hq-mot** [kubernetes/kubernetes#60662]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:

kubelet is monitoring nodefs and imagefs, but looks like it's not aware of device mapper pool. 
As a result, there are two problems:
  1. When device mapper actually starts running out of space ~90% kubelet is not aware of it so no diskPressure is reported and container will start dying.
  2.  Unexpected evictions and garbage collections.
      For example,  k8s was deleting images because /var/lib/docker/tmp was filling up when we did a docker load with a large sized image.tgz file.
**What you expected to happen**:
    kubenete should remove docker images when device mapper (docker image cache) usage is high. 
    kubenete should not remove docker images when /var/lib/docker/tmp was high.

**How to reproduce it (as minimally and precisely as possible)**:
    
  1.  Kubenete settings are below:
      "imageMinimumGCAge": "2m0s",
       "imageGCHighThresholdPercent": 85,
        "imageGCLowThresholdPercent": 80,
  2. dockerd is brought up using below command:
     /run/torcx/bin/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock --selinux-enabled=true --storage-driver=devicemapper --storage-opt=dm.basesize=10G --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true --exec-opt native.cgroupdriver=cgroupfs --selinux-enabled=false --iptables=false

     
  3.   docker info command output:
Containers: 67
 Running: 54
 Paused: 0
 Stopped: 13
Images: 40
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 17.98 GB
 Data Space Total: 20.4 GB
 Data Space Available: 2.416 GB
 Metadata Space Used: 5.304 MB
 Metadata Space Total: 213.9 MB
 Metadata Space Available: 208.6 MB
 Thin Pool Minimum Free Space: 2.039 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.119 (2016-03-04)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local pxd
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.13.9-coreos
Operating System: Container Linux by CoreOS 1520.8.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: cs1-1-1
ID: TCY7:JSEH:TRYC:7DWA:P4P5:7HNC:2RYZ:7IYL:HMLH:HVI7:TUHV:6GU7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

4. thinpool partition is created as below.
 format_sdd(){
 
  create_vg docker /dev/sdd
  /usr/sbin/lvcreate --wipesignatures y -n thinpool docker -l 95%VG
  /usr/sbin/lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG
  /usr/sbin/lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  /usr/sbin/lvchange --metadataprofile docker-thinpool docker/thinpool
  /usr/bin/rm -rf /var/lib/docker/*

}

**Anything else we need to know?**:
cadvisor api endpoint http://[ip]:4194/containers/  does not seem to monitor docker cache(device mapper):
       At a container level, he docker thinpool reported zero total:
       Filesystem
      FS #1: docker-thinpool
      0.00 Bytes / 0.00 Bytes (NaN%)
      At root level:
 	Filesystem 
	FS #1: /dev/mapper/docker-254:13-8409184-48e9c822b18044d5f7ea8cba57fb070c972d73440caf25e1408bb0d7bf0d5b81
	1.66 GB / 10.72 GB (15%)
	FS #2: tmpfs
	0.00 Bytes / 8.40 GB (0%)
	FS #3: /dev/sda9
	186.18 MB / 7.92 GB (2%)
	FS #4: /dev/mapper/vg_data-lv_docker
	310.46 MB / 8.58 GB (3%)
	FS #5: shm
	0.00 Bytes / 8.42 GB (0%)
	FS #6: /dev/mapper/vg_data-lv_log
	104.96 MB / 3.92 GB (2%)
	FS #7: /dev/mapper/vg_data-lv_var

**Environment**:
- Kubernetes version (use `kubectl version`):
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-rancher1", GitCommit:"6cb179822b9f77893eac5612c91a0ed7c0941b45", GitTreeState:"clean", BuildDate:"2017-12-11T17:40:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
  vmware esxi virtual machine on prem.

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
 $ uname -a
Linux cs1-1-1 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel GNU/Linux
- Install tools:
rancher/rke
- Others:

**Comment by hq-mot** [comment]
@kubernetes/apps.bugs

**Comment by vishh** [comment]
cc @derekwaynecarr @sjenning
