### ISSUE TITLE
Kubelet API to lookup pod name from socket

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#60661]
The kubelet should expose an API that allows a node agent to lookup a pod from an inet socket. This information could be exposed through the kubelet rest handler or through a hook in the network setup/teardown. This API will be used for secure caller ID by node agents so the information exported must be up to date and correct.

/sig auth
/sig node
/kind feature

@tallclair

**Comment by tallclair** [comment]
There are a number of plugin vendors (mostly monitoring) that reverse-engineer our cgroup or namespace setup to derive the source pod/container from something like the PID. A more general version of this API might allow looking up the Pod & container by various resources (including IP address)

**Comment by mikedanese** [comment]
We need to identify what constructs we want to attach identity to. Attaching identity to cgroups precludes us from implementing resource models where a node agent takes resources from pods in exchange for providing a service (i.e. VAT). For example, I could imagine a log shipping node agent that creates a thread per pod and drops those threads into the pod's cgroup. Do we want to keep our options here? Are there situations in which an unprivileged agent would need to enter a pod's network namespace? Container ID is also relevant but much further out https://lwn.net/Articles/740621/

**Comment by yujuhong** [comment]
> The kubelet should expose an API that allows a node agent to lookup a pod by it's IP.

Could you provide a use case for this or add a link to a relevant feature? I'm not sure what "secure caller ID by node agents" mean in this context.

> This information could be exposed through the kubelet rest handler or through a hook in the network setup/teardown.

I don't quite get how the network setup/tear hook is going to work -- do you mean supporting hooks through plugins or kubernetes API?

**Comment by liggitt** [comment]
Not sure this belongs to sig-auth… is it planned/committed for 1.11?

**Comment by ericchiang** [comment]
Sorry making my way through the `MILESTONENOTIFIER` backlog. Removing this for now since we still need a use case.

**Comment by mikedanese** [comment]
Identity integrations (e.g. spiffe) workload APIs over either UDS or localhost with no standard mechanism for mapping caller to pod. While UDS works reasonably well today, it will become problematic as container runtimes with stronger isolation become more prevalent. I would like to standardize this mechanism sooner rather than later. I'd think that sig-{auth,node,networking} are all stakeholders.

**Comment by ericchiang** [comment]
cc @squeed

**Comment by squeed** [comment]
I'm curious why this has to be a kubelet API. The kubelet doesn't really store this information; it basically just updates the `podspec.IP` field in the apiserver.  What is a case where talking to the apiserver doesn't work?

A second question: how should this API handle host network pods, where multiple pods have the same IP?

**Comment by mikedanese** [comment]
> I'm curious why this has to be a kubelet API.

It could work as long as the read is consistent. It feels like an unnecessary hop since the source of truth is local.

> The kubelet doesn't really store this information; it basically just updates the podspec.IP field in the apiserver.

It stores this information in memory and it's already available from the /pods handler. Whether the info is consistent or not is an implementation detail but we would be relying on consistency to maintain security.

> how should this API handle host network pods, where multiple pods have the same IP?

I was probably too prescriptive in the original issue description. I changed the (lookup by IP) to (lookup by inet socket). We can either:
* lookup pod by source IP of inet socket.
  * This attaches identity to the pod's network namespace. Anything in the network namespace, (e.g. a liveness or readiness probe executed by the kubelet) would be running as the identity of the pod.
  * This won't support host network pods. I think it's probably OK to treat hostnet pods as privileged.
* lookup pod by pid/gid of inet socket.
  * Attaches identity to the pid namespaces of the pod?
  * Would support host network pods but might be more expensive.

**Comment by squeed** [comment]
Well, when you put it that way, just adding one more cache to podmanager is easier :-).

**Comment by tallclair** [comment]
> It stores this information in memory and it's already available from the /pods handler. Whether the info is consistent or not is an implementation detail but we would be relying on consistency to maintain security.

Even if the information is consistent, this sounds ripe for a race condition vulnerability

**Comment by spikecurtis** [comment]
> lookup pod by pid/gid of inet socket.
>  - Attaches identity to the pid namespaces of the pod(? might be alternatives)
>  - Would support host network pods but might be more expensive.
>  - Wouldn't support host pid pods. Anything running in the host pid would be running as the host.

I don't think this will work for Kata Containers, and may not work for Windows containers (not an expert on what kind of caller info you can get from Windows sockets).

We currently have a FlexVolume + Unix Domain Socket solution prototyped and being tested. This attaches identity to a mount namespace. It's not the cleanest solution, but works fine on Linux. IMO, one of the main arguments for building a Kubelet API solution is that it can enable non-Linux use cases.

**Comment by mikedanese** [comment]
See CNI GET command: https://github.com/containernetworking/cni/pull/490

**Comment by bboreham** [comment]
The CNI GET command takes the container (pod) ID as a parameter, which seems to beg the question.

**Comment by mikedanese** [comment]
Alone it implements the reverse lookup of what we want here, but it could be used to confirm a forward lookup against a cached (i.e. potentially inconsistent) view of the pods on the node. The combination of the kubelet's pod cache and CNI GET seem sufficient to satisfy our functional and security requirements.

**Comment by mikedanese** [comment]
Assuming the CNI GET API guarantees a consistent view.

**Comment by dcbw** [comment]
> Assuming the CNI GET API guarantees a consistent view.

@mikedanese can you clarify this a bit for me?

**Comment by mikedanese** [comment]
Currently, the kubelet exposes a view of it's pod cache (including IPs of pods). If a process receives a request on localhost socket and wants to know which pod is on the other end it can:

1. read src ip of the socket
1. read the pod cache
1. find a pod with a matching ip
1. assume the connection came from that pod

The concern is that stale data in the cache mixed with pod ip address reuse may lead to the process misidentifying the calling pod. Assuming that CNI GET is accurate at the time of invocation, the process can instead:

1. read src ip of the socket
1. read the pod cache
1. find a pod with a matching ip
1. call CNI GET with pod ip to get pod id
1. if pod id from CNI matches pod id from cache, assume the connection came from that pod

**Comment by dcbw** [comment]
@mikedanese yeah, that's not what CNI GET is for.  CNI GET is "tell me the IP details of PodX or return an error if PodX has broken networking".  The original reason for GET was to (a) remove the nsenter crap from kubelet and (b) give kubelet a way to get pod IP/network-state on restart.

It's not meant to be a "tell me what pod has IP address Y", which is what I think you're looking for?

Lastly, CNI GET as currently implemented is also mostly a cache of the ADD response that CNI plugins can modify if they want to, but we don't anticipate plugins doing much of that because of plugin chaining logistics. (which I can explain more if you like).  So it's still a cache, just not on in kubelet because a year or two ago when discussing this problem, kubelet maintainers did not want to store that info there.  We've since gotten checkpoints which is a reversal of that stance, but still...

Besides, if the kubelet cache of PodIP :: PodID is *not* correct and timely, shouldn't that get fixed?  Also, at this time, kubelet does not expect the PodIP of a pod to change over its lifetime.  While it technically can, we discussed that at KubeCon Austin in the SIG Network sessions and decided it might be a worthwhile future goal but was not currently supported/expected.

**Comment by dcbw** [comment]
Instead I would suggest just using the kubelet pod cache, but look at *sandboxes* not pods.  Find the active sandbox with the given IP address and then return that sandbox's Pod ID.  If kubelet can't correctly track which containers are using which sandboxes, we've got bigger problems than this API.

**Comment by dcbw** [comment]
Also, I don't think your proposal works for hostnetwork pods, since every hostnetwork pod on the same node will share the host's IP address, so there's no way to differentiate pods by IP.

**Comment by mikedanese** [comment]
cc @alexcope

**Comment by mikedanese** [comment]
We worked around this by interacting with CRI directly.  I'll close this until we need greater support.
