### ISSUE TITLE
Secure etcd for all distros.  Etcd-in-Pod for apiserver.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#6067]
On all salt distros except redhat, etcd appears to use public IP for the client port (4001).

(There is still some possible cleanup to do in cluster/saltbase/salt/kube-apiserver/default to hardcode this.  See zmerlyn's comment.)

On some non-salt distros,  it accepts clients on the public address of the master node.
Some people may want this since they are running flanneld too.
I suggest that we solve this by running an apiserver-only etcd instance in a pod with the apiserver (the way we do for skydns).  @ArtfulCoder is working on this.  Then etcd will be secure because it is on the localhost of the Pod's netns.

On CoreOS/flannel-based distros, there will be multiple un-related etcd server-pools.  It is up to the user or the distro author to secure these etcds.  Examples here are libvirt-coreos, rackspace.

Once we move to replicated apiserver, we can setup TLS credentials for the peer-to-peer communication between the etcd-in-a-pods by generating certs and setting flags per example 3 in https://github.com/coreos/etcd/blob/master/Documentation/security.md

**Comment by dchen1107** [comment]
#5011 is the one targeting for v1.0

cc/ @lavalamp who is a different proposal beyond v1.0

**Comment by roberthbailey** [comment]
@erictune When I looked into this just a few days ago, I found etcd listening on all interfaces. The salt configuration is confusing (some of it says 127.0.0.1 and some says 0.0.0.0) and #4654 by @davidopp also makes it look like we are listening on all interfaces on GCE.

**Comment by erictune** [comment]
Yeah, I just figured this out now.  Files an issue about confusing salt config.
#6081

**Comment by kelseyhightower** [comment]
@roberthbailey Is this the case when running etcd2? I think we default to localhost across the board, but this may have more to do with the salt scripts.

**Comment by roberthbailey** [comment]
@kelseyhightower Our salt config specifically sets the bind address for etcd2 to 0.0.0.0. But with etcd in a pod, we won't need to use salt to pass the command line flags any longer.

**Comment by kelseyhightower** [comment]
@roberthbailey Ok. While it maybe obvious I'll just say it anyway. localhost in the pod is different from localhost on the host. So you might still need to set etcd2 to listen on 0.0.0.0 in the container if you are not using --net=host (docker). You'll also need to advertise the IP of the docker hosts for peer and client communication -- see: https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md

**Comment by ArtfulCoder** [comment]
We are running etcd in a pod with net=host

I believe localhost would be the same as the underlying host.

**Comment by kelseyhightower** [comment]
@ArtfulCoder OK, that clears things up. Yeah just set to localhost then or use etcd2 defaults.

**Comment by ArtfulCoder** [comment]
#6417

**Comment by bgrant0607** [comment]
Obsolete
