### ISSUE TITLE
Consider using grpc to refactor scheduler extender interface

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#60697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
As Device Plugin evolving, more use cases for scheduler extender begin to showing up, for example,  customized scheduling logic for extended resources.

The recent example I'm working on is: topology awareness of GPU devices for deep learning workloads training, see: https://github.com/kubernetes/kubernetes/issues/49964

In this use case, extender can be used to do the advanced scheduling based on GPU topology information.

But the current extender has some concerns:
1. HTTP server's performance.
2. The parameters between default scheduler and extender are not well structured,  not easy to maintain, and not versioned.

**What you expected to happen**:

We may consider to use grpc to handle extender, like what we did for Container Runtime Interface.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**One thing not sure is**: if this proposal alias with the long term goal of sig-scheduling?
Since we do have a design about [scheduler as framework](https://docs.google.com/document/d/1NskpTHpOBWtIa5XsgB4bwPHz4IdRxL1RNvdjI7RVGio/edit#). Will we keep scheduler extender feature in that roadmap? Or it will be deprecated. 

If the former case, then this proposal do make sense and worth further discussion and design.
Otherwise, this may be overkill and we can leave it as is.

cc @kubernetes/sig-scheduling-api-reviews @bsalamat @timothysc 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tossmilestone** [comment]
Seems relative to #59980

**Comment by resouer** [comment]
Per discussion during sig-scheduling meeting. Let's hold this issue and focus on scheduler as framework design.

**Comment by swatisehgal** [comment]
Can you please explain what is meant by "focusing on scheduler as framework design". Are we referring to making changes to way scheduler is currently customized (custom scheduler/scheduler extender) or are there intentions of replacing these current frameworks with a completely new mechanism/framework to customize scheduler ?

**Comment by resouer** [comment]
@swatisehgal Yes, we already proposed a new design of scheduler as framework several months ago. https://docs.google.com/document/d/1NskpTHpOBWtIa5XsgB4bwPHz4IdRxL1RNvdjI7RVGio/edit#

**Comment by swatisehgal** [comment]
Cool, thanks for sharing the document!
