### ISSUE TITLE
Annotations defined on services yaml don't get propagated to corresponding endpoints

### ISSUE THREAD

**Issue by matteosilv** [kubernetes/kubernetes#60703]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

>/kind feature
/sig api-machinery
/sig network

**What happened**:

Annotations defined on services yaml don't get propagated to corresponding endpoints

**What you expected to happen**:

Annotations defined on services yaml get propagated to corresponding endpoints (as it happens for labels)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: Google Cloud
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a

**Comment by jennybuckley** [comment]
cc @cheftako

**Comment by bmcstdio** [comment]
I would like to work on this!

**Comment by liggitt** [comment]
Requests for addition of new function is a feature request, not a bug. In general, annotations are not propagated from one object to another. What is the use case for propagating these, and what would be the implications of starting to do this?

**Comment by matteosilv** [comment]
There Is no way to annotate endpoints, since they are automatically created. I marked the issue as a bug, because labels gets propagated while annotations gets not.

**Comment by liggitt** [comment]
> labels gets propagated while annotations gets not

The original intent was not to automatically propagate all metadata fields. If there's a use case for that to be added for annotations, that should be proposed/described
