### ISSUE TITLE
Flexvolume e2e tests failing

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#60725]
/kind bug

https://k8s-testgrid.appspot.com/sig-storage#gce-serial

This is likely caused by a missing REMOUNT_VOLUME_PLUGIN_DIR flag in kube-env construction.

/assign
/sig storage

**Comment by krzyzacy** [comment]
xref #60003
/priority failing-test
/priority critical-urgent

**Comment by verult** [comment]
I'm aware of the solution, but I'm trying to understand how to limit the scope of the change to just COS images, instead of all VM distros.

**Comment by krzyzacy** [comment]
xref https://github.com/kubernetes/kubernetes/issues/60003

**Comment by verult** [comment]
Fix submitted, awaiting review: https://github.com/kubernetes/kubernetes/pull/60859

**Comment by verult** [comment]
PR approved; awaiting 1.10 milestone marker
