### ISSUE TITLE
There should be a way to offer mount options for NFS v1Volumes (not PV)

### ISSUE THREAD

**Issue by yokhahn** [kubernetes/kubernetes#60729]
While https://github.com/kubernetes/kubernetes/issues/17226 addressed this question, and https://github.com/kubernetes/website/pull/2743 fixes this for Persistent Volumes.  It does not for straight v1Volumes (or does not document how to do it... Where do I put the annotation?).

 /kind bug

**What happened**:
I was unable to tell kubernetes to mount an nfsv3 volume as a v1Volume

**What you expected to happen**:
Volume would mount

**How to reproduce it (as minimally and precisely as possible)**:
Try to use a v1 volume in a pod to mount a NFSv3 only server.

**Anything else we need to know?**:

**Environment**:
Kubernetes version 1.8 from typhoon.
On CoreOS
- OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
HOME_URL="https://coreos.com/"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
4.14.16-coreos #1 SMP Thu Feb 1 20:38:35 UTC 2018 x86_64

 @kubernetes/rh-storage  @kubernetes/sig-storage-bugs

**Comment by yokhahn** [comment]
If it is indeed decided to not allow for support of NFSv3 in the direct volume, it should probably be stated explicitly in the documentation.

**Comment by athornton** [comment]
This is biting me as well; in my case I'd like to specify local locks, but generally having a way to pass options, or a clear statement that if I need non-default options on my NFS mounts, I need to create PVs and PVCs and then mount the volumes to my pod with PersistentVolumeClaims, would be good.

**Comment by omegazeng** [comment]
Need this feature, too.

Like this: https://github.com/kubernetes/kubernetes/issues/31613#issuecomment-264006483

API doc: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#nfsvolumesource-v1-core

**Comment by liggitt** [comment]
There was significant discussion around this when introducing mount options in https://github.com/kubernetes/community/pull/321#issuecomment-279822350

The resolution was that mount options would only be supported for PV/PVC volume sources, not inline pod volumes.

/close
