### ISSUE TITLE
verify-bazel failing with 'cannot find package "github.com/bazelbuild/buildtools/build"' etc

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#60730]
/kind bug

verify-bazel is currently failing with the following stacktrace:
```
$ hack/verify-bazel.sh 
../../internal/config/directives.go:24:2: cannot find package "github.com/bazelbuild/buildtools/build" in any of:
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/build (vendor tree)
        [path]/.gvm/gos/go1.9.4/src/github.com/bazelbuild/buildtools/build (from $GOROOT)
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/buildtools/build (from $GOPATH)
../../internal/rules/construct.go:27:2: cannot find package "github.com/bazelbuild/buildtools/tables" in any of:
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/tables (vendor tree)
        [path]/.gvm/gos/go1.9.4/src/github.com/bazelbuild/buildtools/tables (from $GOROOT)
        /tmp/tmp.RKacdj87fR/go/src/github.com/bazelbuild/buildtools/tables (from $GOPATH)
!!! [0302 11:47:54] Call tree:
!!! [0302 11:47:54]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483
  Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483. '((i<3-1))' exited with status 1
Call stack:
  1: /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:483 kube::util::go_install_from_commit(...)
  2: ./hack/update-bazel.sh:34 main(...)
Exiting with status 1
!!! [0302 11:47:54] Call tree:
!!! [0302 11:47:54]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473
  Error in /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473. '((i<3-1))' exited with status 1
Call stack:
  1: /tmp/verify-bazel.5wHzRb/go/src/k8s.io/kubernetes/hack/lib/util.sh:473 kube::util::go_install_from_commit(...)
  2: ./hack/update-bazel.sh:34 main(...)
Exiting with status 1
!!! Error in hack/verify-bazel.sh:43
  Error in hack/verify-bazel.sh:43. 'GOPATH="${_tmp_gopath}" ./hack/update-bazel.sh' exited with status 1
Call stack:
  1: hack/verify-bazel.sh:43 main(...)
Exiting with status 1
```

Ironically, this is caused by a fix upstream which would probably prevent #60442 from occurring again - gazelle vendored `github.com/bazelbuild/buildtools` in https://github.com/bazelbuild/bazel-gazelle/pull/145, which means that when we hackily download gazelle's dependencies with `go get -d`, we no longer also download the `github.com/bazelbuild/buildtools` package.

We then checkout an older version of gazelle, which hasn't vendored `github.com/bazelbuild/buildtools`, and so the dependency is missing, and we fail to build.

For the master branch, we can probably just bump to latest gazelle. The older release branches will probably require more hacks.

Happy Friday!
/assign

**Comment by cblecker** [comment]
@ixdy Feel free to ping if you need assistance/reviews

**Comment by ixdy** [comment]
miraculously, @spiffxp's bash hacks save us on release-1.8 and release-1.9, as we check out the old version of gazelle and then run `go get -d`.
https://github.com/kubernetes/kubernetes/blob/136abdbde4d85d5beb595acc9c4c13f149b5589a/hack/lib/util.sh#L487-L488

**Comment by cblecker** [comment]
:bash_fire:
:golang_fire:

**Comment by bsalamat** [comment]
Not surprisingly I am seeing this issue when I run hack/update-bazel.sh:

./../internal/config/directives.go:24:2: cannot find package "github.com/bazelbuild/buildtools/build" in any of:
...

Is there any workaround?

**Comment by BenTheElder** [comment]
There's a PR in the main repo pending merge right now. https://github.com/kubernetes/kubernetes/pull/60732

**Comment by bsalamat** [comment]
Yeah, I did the same thing that @ixdy had done in [his PR ](https://github.com/kubernetes/test-infra/pull/7105/files) and it fixed my master branch.

**Comment by ixdy** [comment]
the submit queue is soooo sloooow
