### ISSUE TITLE
Can not get gpu usage from metrics

### ISSUE THREAD

**Issue by hochuenw** [kubernetes/kubernetes#60742]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I am currently using `metrics/v1beta1`, I have one container in each pod. Gpu usage got from metrics is always 0. Also, it seems podMetrics.Metadata.Labels lost all labels of one pod..

**What you expected to happen**:
gpu usage is updated correctly and i can get pod labels from `podMetrics`

**How to reproduce it (as minimally and precisely as possible)**:

```
import (
    "k8s.io/client-go/rest"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    metrics "k8s.io/metrics/pkg/client/clientset_generated/clientset/typed/metrics/v1beta1"
)

config, err := rest.InClusterConfig()
client := metrics.NewForConfigOrDie(config)
podMetricses := client.PodMetricses("my-namespace")
podMetricsList, err := podMetricses.List(metav1.ListOptions{})
for _, podMetrics := range podMetricsList.Items {
    // there is only one container in my pod. 
    containerUsage := podMetrics.Containers[0].Usage
    **// it is always 0**
    fmt.Println(containerUsage.NvidiaGPU().AsDec().String())
    **// it is always an empty map.**
    fmt.Println(podMetrics.ObjectMeta.Labels)
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by hochuenw** [comment]
@pineking connection refused.
```
$ curl http://localhost:4194/metrics
curl: (7) Failed connect to localhost:4194; Connection refused
```

**Comment by jyparketc** [comment]
@hochuenw do you enable  --cadvisor-port in kubelet?
Ref: https://kubernetes.io/docs/reference/generated/kubelet/

**Comment by hochuenw** [comment]
@jyparketc yes. 
```
--cadvisor-port=0
```

**Comment by jyparketc** [comment]
@hochuenw you have to set other port.


`--cadvisor-port : The port of the localhost cAdvisor endpoint (set to 0 to disable) (default 4194)`

**Comment by abushoeb** [comment]
I can access http://hostip:4194/metrics but I don't see any metrics with `container_accelerator` though I have GPU machines in the cluster. Could someone please tell me how to get GPU usage?

**Comment by jiaxuanzhou** [comment]
this could be fixed by one pr
