### ISSUE TITLE
What Is Kubernetes ?

### ISSUE THREAD

**Issue by manideepanchoori** [kubernetes/kubernetes#60752]
Can anyone help me to understand Kubernetes and Docker in a simple way please.

Thanks,
Manideep

**Comment by gogeof** [comment]
Interesting. And does kubernetes has limit itself on what it never do?

**Comment by yue9944882** [comment]
Kubernetes is the truth :-)

[https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/)

**Comment by dims** [comment]
/close

thanks @yue9944882
