### ISSUE TITLE
Deploy haveged as part of base image to prevent low-entropy situations

### ISSUE THREAD

**Issue by joaocc** [kubernetes/kubernetes#60751]
> /kind feature

Nodes can run into low entropy situations.
Currently, one approach to deal with with is to deploy a privileged pod to every node via DaemonSet. Having this installed on the base image would address this.

More info here:
* http://www.irisa.fr/caps/projects/hipsor/
* http://issihosts.com/haveged/

Packages exist for debian:
* https://packages.debian.org/wheezy/haveged
* https://packages.debian.org/sid/haveged

**Comment by joaocc** [comment]
Some tests to show how this is an issue. These were made on AKS, but it's very likely that the results will be similar in AWS, GoogleCloud and others...

Exec the following in any idle pod on an idle node (a ssh image like ```rastasheep/ubuntu-sshd:16.04 ``` will do)
```
apt-get update
apt-get install rng-tools
cat /proc/sys/kernel/random/entropy_avail
cat /dev/random | rngtest -c 1000
cat /proc/sys/kernel/random/entropy_avail
```
In a cluster where nodes did have haveged via chart installed, this is a typical result:
```
cat /dev/random | rngtest -c 1000
rngtest 5
Copyright (c) 2004 by Henrique de Moraes Holschuh
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rngtest: starting FIPS tests...
rngtest: bits received from input: 20000032
rngtest: FIPS 140-2 successes: 998
rngtest: FIPS 140-2 failures: 2
rngtest: FIPS 140-2(2001-10-10) Monobit: 0
rngtest: FIPS 140-2(2001-10-10) Poker: 2
rngtest: FIPS 140-2(2001-10-10) Runs: 0
rngtest: FIPS 140-2(2001-10-10) Long run: 0
rngtest: FIPS 140-2(2001-10-10) Continuous run: 0
rngtest: input channel speed: (min=1.039; avg=14.094; max=19073.486)Mibits/s
rngtest: FIPS tests speed: (min=1.295; avg=54.638; max=83.290)Mibits/s
rngtest: Program run time: 1704043 microseconds
```
Ina

**Comment by wknapik** [comment]
It would be nice to get some feedback from kubernetes developers. Random number generation is relevant to security, so it's not an issue to be ignored.

Is the haveged daemonset the recommended way to go about solving the problem ? What are the trade-offs, risks and alternatives ?

**Comment by dannyk81** [comment]
@wknapik we recently hit this issue on several clusters running workers on VMs, using a `haveged` daemonset seem to alleviate the entripy pool depletion, however the main concern (from what I'm reading) with this method is the quality/randomness of the generated pool.

**Comment by joaocc** [comment]
@wknapik The reason for having proposing this approach is that, after a cursory read on both the project's page (https://issihosts.com/haveged/) and the underlying algorithms (http://www.irisa.fr/caps/projects/hipsor/), it seemed to a sensible solution for "normal" usage.
In our case, facing a situation where entropy is depleted, execution slowed down tremendously, affecting the system usage.

**Comment by dannyk81** [comment]
For what it's worth, we've deployed a haveged daemonset on our test/pre clusters and it's working really well, I can't attest to the quality of random numbers but this solved out entropy depletion issues.

**Comment by wknapik** [comment]
Let's not close this without at least some guidance for those who find this issue in the future.

/remove-lifecycle stale

**Comment by wknapik** [comment]
Please provide [guidance](https://github.com/kubernetes/kubernetes/issues/60751#issuecomment-491289026) before closing.

/remove-lifecycle stale
