### ISSUE TITLE
[test failed] [1.10 upgrade][gci-gke] Kubernetes Dashboard should check that the kubernetes-dashboard instance is alive

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60767]
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master
also in https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke

/sig sig-ui
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus
/assign @danielromlein @floreks

**Comment by floreks** [comment]
We will investigate it.

**Comment by floreks** [comment]
@krzyzacy 

[Failed test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1385#sig-ui-kubernetes-dashboard-should-check-that-the-kubernetes-dashboard-instance-is-alive) points to a [code](https://github.com/kubernetes/kubernetes/blob/d361f68b505f55/test/e2e/ui/dashboard.go#L90) that was removed in [#53766](https://github.com/kubernetes/kubernetes/pull/53766/files#diff-9e908e48ca777eb2d536f65317277019L89). If it's not part of this upgrade then it should be cherry picked.

**Comment by krzyzacy** [comment]
/assign @liggitt 
as you are the PR author :-)

**Comment by liggitt** [comment]
just so I understand, these are tests in the release-1.9 branch running against a 1.10 master? requiring changes to previous release's tests seems like a mistake in how we're doing upgrade testing

**Comment by krzyzacy** [comment]
@liggitt after upgrade, we have two suite, run both 1.9 and master version of tests.

**Comment by krzyzacy** [comment]
Hi sig-ui this test is now also broken on master at https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke

please take a look
cc @floreks @liggitt

**Comment by floreks** [comment]
@krzyzacy I have checked the logs but I am not sure what could be causing service to just disappear:
```
STEP: Checking whether the kubernetes-dashboard service exists.
Mar  7 22:08:52.894: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
Mar  7 22:08:54.896: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
Mar  7 22:08:56.898: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
Mar  7 22:08:58.897: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
Mar  7 22:09:00.896: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
Mar  7 22:09:02.898: INFO: Service kubernetes-dashboard in namespace kube-system disappeared.
```

**Comment by liggitt** [comment]
The last green test was on c74c826452fb03

Since d112ffc2eb339c it has permanently failed

**Comment by krzyzacy** [comment]
looks green now

**Comment by liggitt** [comment]
/reopen
still failing in the upgrade test (running 1.9 e2e code): http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/61135
