### ISSUE TITLE
[failing test] should restart all nodes and ensure all nodes and pods recover

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60763]
This test is failing in gce serial suite:
http://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial

/sig cluster-lifecycle
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus 
/assign @roberthbailey @luxas @lukemarsden @jbeda

xref #60003

**Comment by krzyzacy** [comment]
this also fails in upgrade suite
xref https://github.com/kubernetes/kubernetes/issues/60764

**Comment by dims** [comment]
looks like `should restart all nodes and ensure all nodes and pods recover` is now green. guess it's still flaky

**Comment by timothysc** [comment]
Mar  7 16:52:36.943: At least one pod wasn't running and ready or succeeded at test start. 

^ The preconditions are not met at the start of the test... and the pods state shows as pending.  
Always seems to be a fluentd pod on the master node doesn't run.  Are things tainted properly?  

/cc @yujuhong & @mbforbes as they are the test authors.

**Comment by yujuhong** [comment]
FWIW, I didn't author the test, and the test didn't even run since it failed the precondition....

/unassign
/assign @bmoyles0117 
/assign @crassirostris 

fluentd pods are pending on the master nodes.

**Comment by krzyzacy** [comment]
status?

**Comment by krzyzacy** [comment]
ping

**Comment by crassirostris** [comment]
Looking into it

**Comment by crassirostris** [comment]
I have some problems with running e2e tests locally

@bmoyles0117 Could you please take a look? I will return to this tomorrow Europe time

**Comment by bmoyles0117** [comment]
I'm not sure what exactly is failing here. I was hoping to see if the two PRs we merged previously would have a positive impact on these failures. Is there any way of seeing whether or not those two PRs did or did not have a positive impact?

**Comment by yujuhong** [comment]
https://github.com/kubernetes/kubernetes/pull/60386 made DaemonSet controller schedules pods on "unschedulable" nodes. The changes lets the fluentd pod to be scheduled on the master, but there is no capacity on the master node to run this pod.
```
W0313 14:50:06.722518    1492 predicate.go:107] Failed to admit pod fluentd-gcp-v3.0.0-t8x6s_kube-system(d1edfd78-26cd-11e8-801c-42010a800002) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: cpu, q: 82), ]
```
/cc @k82cn @janetkuo

**Comment by k82cn** [comment]
> #60386 made DaemonSet controller schedules pods on "unschedulable" nodes.

`CheckNodeUnschedulablePredicate` is enabled by default: if node is 'unschedulable' (`spec.Unschedulable` is true), the pod will not schedule to it.

`CheckNodeConditionPredicate` already includes this check; #60386 is used to also enable this check when `TaintNodesByCondition` enabled.

**Comment by krzyzacy** [comment]
any solution here?

**Comment by yujuhong** [comment]
@k82cn @janetkuo fluentd is scheduled on the master node, which is marked unschedulable (`spec.unschedulable: true`). Is this working as intended?

**Comment by janetkuo** [comment]
> fluentd is scheduled on the master node, which is marked unschedulable (spec.unschedulable: true). Is this working as intended?

Yes, assuming fluentd is a DaemonSet pod. #60386 is nothing new; it's introduced to fix a regression in 1.10. 

As stated in DaemonSet [doc](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled): 
> The `unschedulable` field of a node is not respected by the DaemonSet controller.

**Comment by janetkuo** [comment]
> The changes lets the fluentd pod to be scheduled on the master, but there is no capacity on the master node to run this pod.

If fluentd Daemon pods aren't supposed to be scheduled on the master, taints should be added to the master; if instead those pods should be scheduled on the master, we should add more capacity to it.

**Comment by yujuhong** [comment]
fluentd's asking more cpu resources than 1.9 (the regression caused by #60613 masked the issue until now). Seems like this could be related to the introduction of fluentd-gcp-scaler.
/assign @crassirostris

**Comment by crassirostris** [comment]
@yujuhong 

> fluentd's asking more cpu resources than 1.9

That's unexpected, thanks for noticing

/assign @x13n 

Daniel, please take a look

**Comment by x13n** [comment]
fluentd-gcp in both 1.9 and 1.10 asks for the same amount of resources: 100m cpu request, 200Mi memory request (and 300Mi memory limit). Introducing fluentd-gcp-scaler didn't change these values.
@yujuhong Do you mean that CPU request increased? I see it is 100m now (as it was for 1.9), what values did you see for 1.9 and now?

**Comment by krzyzacy** [comment]
any updates?

**Comment by yujuhong** [comment]
The fluentd pod on the master from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3153:
https://gist.github.com/yujuhong/8044d7daaf169b5cd6b0c3d587579246

Both the `fluentd-gcp` and the `prometheus-to-sd-exporter` containers requests 100m cpu
```
                        "requests": {
                            "cpu": "100m",
                            "memory": "200Mi"
                        }
```
This amounts to 200m cpu. In v1.9, `prometheus-to-sd-exporter` did not have any cpu request IIRC. You can double check that.

**Comment by x13n** [comment]
Thanks! Looks like there is a bug in the scaler, so it sets resources on all containers instead of fluentd-gcp only. Scaler fix is in https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/130, I will create a PR with version bump once this is merged.

**Comment by x13n** [comment]
Actually, maybe better to
/reopen
until testgrid becomes green.

**Comment by jdumars** [comment]
ACK.  In progress
ETA: 19/03/2018

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.9-downgrade-cluster is green now
