### ISSUE TITLE
[test failed] regular resource usage tracking resource tracking for 0 pods per node

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60762]
This test is failing in gke serial suite:
http://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial

/sig node
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus 
/assign @dchen1107 @derekwaynecarr

also cc @dashpole @yujuhong @Random-Liu in case you already have some idea
xref #60003

**Comment by krzyzacy** [comment]
this also failed in upgrade jobs: http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-cluster

xref https://github.com/kubernetes/kubernetes/issues/60764

**Comment by krzyzacy** [comment]
cc @kubernetes/sig-node-bugs please update

**Comment by dashpole** [comment]
I don't think so.  This is a specific increase in the runtime (docker in this case) cpu usage

**Comment by bmoyles0117** [comment]
+ @qingling128 we should investigate this with @crassirostris, according to this report, the latest version of fluentd using our image is using more CPU that is acceptable. I didn't see this behavior in my tests, I wonder if it has anything to do with the parser fixes we added when we moved the multiformat into a plugin block.

**Comment by bmoyles0117** [comment]
Just ran my perf tests against the latest configuration, and I'm seeing > 600m usage for CPU. Will investigate how we can optimize this with Ling today.

**Comment by yujuhong** [comment]
@bmoyles0117 the test checks "docker daemon's" cpu usage when *only* system add-on pods are running, and the usage increases on all nodes. fluentd is one of the few pods that run on every node and the failure coincided with the fluentd version upgrade. On top of that,  fluentd frequently fail its own liveness checks.

Here are a few things that are worth checking IMO:
 1. Revert the PR (or run the test in a separate test cluster) to confirm whether fluentd is the culprit.
 2. Confirm whether the increase of "docker daemon" cpu usage is intended.
     * Why is fluentd failing the liveness checks so frequently? Is that expected. I've seen a few consecutive failures (although they were under the threshold, which is 3).
     * Is the newer version of fluentd logging more? Docker daemon is responsible for writing the container stdout/stderr logs to the disk, and the increase of logs could cause cpu spikes.
     * Just check the fluentd logs and see if there is anything abnormal.

**Comment by yujuhong** [comment]
/assign @crassirostris 

(since I can't assign it to @bmoyles0117 )

**Comment by bmoyles0117** [comment]
After doing some investigation, we discovered that this was due to an update in Fluentd v0.14 in how it manages its buffers. I've submitted a PR that resolves the liveness probe which should prevent the extreme spikes in CPU when the fluentd process is forcefully shut down.

**Comment by krzyzacy** [comment]
update?

cc @jdumars AI needed here

**Comment by bmoyles0117** [comment]
Two two PRs that should resolve this issue have been approved and will be merged soon.

#60951 
#60981
