### ISSUE TITLE
[test failed] Services should work after restarting apiserver

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60761]
This test is failing in both gce serial suite:
http://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial

/sig network
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus @MrHohn 
/assign @thockin @dcbw @caseydavenport 
PTAL

**Comment by krzyzacy** [comment]
xref https://github.com/kubernetes/kubernetes/issues/60003

**Comment by krzyzacy** [comment]
this also fails in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

**Comment by thockin** [comment]
Failing to connect to Services at all.

I can't even ping pod IPs:

```
# ping 10.64.4.14
PING 10.64.4.14 (10.64.4.14): 56 data bytes
92 bytes from kubernetes-minion-group-klr6.c.thockin-dev.internal
(10.240.0.5): Time to live exceeded
92 bytes from kubernetes-minion-group-klr6.c.thockin-dev.internal
(10.240.0.5): Time to live exceeded
92 bytes from kubernetes-minion-group-klr6.c.thockin-dev.internal
(10.240.0.5): Time to live exceeded
92 bytes from kubernetes-minion-group-klr6.c.thockin-dev.internal
(10.240.0.5): Time to live exceeded
^C--- 10.64.4.14 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by thockin** [comment]
```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group
default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group
default qlen 1000
    link/ether 42:01:0a:f0:00:04 brd ff:ff:ff:ff:ff:ff
    inet 10.240.0.4/32 brd 10.240.0.4 scope global dynamic eth0
       valid_lft 56265sec preferred_lft 56265sec
    inet6 fe80::4001:aff:fef0:4/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue
state DOWN group default
    link/ether 02:42:64:c4:26:bf brd ff:ff:ff:ff:ff:ff
    inet 169.254.123.1/24 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by thockin** [comment]
Wither cbr0 ?

**Comment by thockin** [comment]
So I can ping pods same-node and cross-node right up until it kills the apiserver.

**Comment by thockin** [comment]
@MrHohn @caseydavenport @danwinship - I could use help - have to shift attention soon.

**Comment by thockin** [comment]
FWIW, I am testing on a Calico-enabled node

**Comment by rramkumar1** [comment]
I'll take a look at this as well.

**Comment by thockin** [comment]
Weird, now even after a reboot, this condition is sticky.  I have a cluster in this state, if you want to poke.

**Comment by thockin** [comment]
ugh, now it is resolved.

**Comment by thockin** [comment]
I just repro'ed without the e2e - have a cluster, proved ping works, killed apiserver ping fails.

**Comment by thockin** [comment]
Interesting - docker shows the pods not running, but apiserver says they are alive.

**Comment by thockin** [comment]
Update: docker sees no running pods.  API server thinks kubelet is running them.  kubelet is getting "" from apiserver, even after kubelet restart.

**Comment by thockin** [comment]
Update and recap:

Bring up a cluster
Run some pods
Prove that pods are running and services work
pkill -9 apiserver
Wait.
Watch kubelets "lose" pods that were assigned to them
Observe that pods are not running and services do not work
Observe that apiserver says the pods are running
pkill -9 kubelet
Observe that it is still broken
kubectl delete one pod 
Observe that kubelet is fixed for that one pod, but not others

Q: Why is kubelet not getting a full listing when it restarts?

@lavalamp @smarterclayton 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/apiserver.go

**Comment by thockin** [comment]
@wenjiaswe

**Comment by lavalamp** [comment]
> kubectl delete one pod
> Observe that kubelet is fixed for that one pod, but not others

What exactly does it mean for it to be fixed for a deleted pod?

**Comment by thockin** [comment]
Kubelet started running the pod that was deleted - it got the update for that one.

**Comment by thockin** [comment]
The cluster I was testing was a week or 2 old.  I built a cluster from HEAD and I can not repro - @wenjiaswe said the same.

Is this test running against head of master?

**Comment by thockin** [comment]
I also ran the test manually against my new cluster and it passed

**Comment by caseydavenport** [comment]
FWIW I was also unable to reproduce this yesterday on a cluster from HEAD.

**Comment by MrHohn** [comment]
Did some investigations and had some findings for this specific failure:
```
Services should work after restarting apiserver [Disruptive] 6m1s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=\[sig\-network\]\sServices\sshould\swork\safter\srestarting\sapiserver\s\[Disruptive\]$'
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:407

Expected error:
    <*errors.errorString | 0xc421718f70>: {
        s: "service verification failed for: 10.0.176.6\nexpected [service1-97rbx service1-f7w5j service1-x4sbg]\nreceived []",
    }
    service verification failed for: 10.0.176.6
    expected [service1-97rbx service1-f7w5j service1-x4sbg]
    received []
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:438
```

Traced down a bit on the history, the first occurrence was https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3027/#sig-network-services-should-work-after-restarting-apiserver-disruptive.

From the [diff from its previous run](https://github.com/kubernetes/kubernetes/compare/d3dc4584f9dcf3...9a8b675d2c19fa), https://github.com/kubernetes/kubernetes/pull/59871 seems suspicious because it modified `watchcache`. Also found https://github.com/kubernetes/kubernetes/issues/60507#issuecomment-369654060 reported a relevant symptom:
> The problem doesn't appear to be with selector, but with resourceVersion=0. This parameter is always added by ListWatch. And as indicated by the comment there, the result isn't always empty - it returns only pods that have been modified since API server start. The problem with "catch up eventually" in this case is that it doesn't really happen (most pods aren't modified after every master restart).

The fix (https://github.com/kubernetes/kubernetes/pull/60715) for that was merged a day ago and may explained why we can't repro from HEAD anymore.

**Comment by wenjiaswe** [comment]
@MrHohn nice, is this issue reproducible without the fix (#60715)?

**Comment by MrHohn** [comment]
> nice, is this issue reproducible without the fix (#60715)?

Sorry should have had confirmed this, bringing up a cluster now.

**Comment by MrHohn** [comment]
Quick update: I was able to repro the same failure (https://github.com/kubernetes/kubernetes/issues/60761#issuecomment-370890783) from HEAD with #60715 reverted.

Though this test is now flaky on some other errors:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3108#sig-network-services-should-work-after-restarting-apiserver-disruptive
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3110#sig-network-services-should-work-after-restarting-apiserver-disruptive

They all seem to failed while communicating with apiserver.

**Comment by wenjiaswe** [comment]
Thanks @MrHohn ! So #60715 fixed the issue and I am curious about what introduced the issue. Do you happen to know when did this test start to fail? Just trying to find out what went wrong in between. We have some other possibly related issues so finding out the root cause of this one would be super helpful.

**Comment by MrHohn** [comment]
@wenjiaswe The first occurrence (for that exact failure) I noticed was https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3027, which happened on 2018-02-15 09:49 PST.

**Comment by thockin** [comment]
You all rock!  I see a couple greens on it now, but still mostly red?

**Comment by MrHohn** [comment]
> I see a couple greens on it now, but still mostly red?

The test is now flaky mostly on creating an exec pod after restarting apiserver. Some sample failures:
```
Message: "an error on the server (\"apiserver is shutting down.\") has prevented the request from succeeding (post pods)

or

Post https://146.148.93.99/api/v1/namespaces/e2e-tests-services-7xhz8/pods: unexpected EOF

or

Post https://35.193.65.117/api/v1/namespaces/e2e-tests-services-bpk66/pods: EOF
``` 

To elaborate a bit more, a snippet of the test procedure is:
- ssh to master and `sudo kill $APISERVER_PID` (sending a SIGTERM)
- Keep polling on /healthz on apiserver until 200 is returned.
- Create an exec pod for later steps (and failed on various erros --- EOF, connection refused, apiserver terminating).

According to above test failures, my suspicion is that the test is assuming the apiserver is restarted too soon. It is possible that apiserver captured SIGTERM and did a graceful termination, so that polling on /healthz may succeed even in the termination phase. I'm not surprised trying to create a pod via a terminating apiserver will hit those errors.

@kubernetes/sig-api-machinery-test-failures Could anyone confirmed the SIGTERM theory?

**Comment by MrHohn** [comment]
Test is now passing on gce but failing on gke. Apparently we don't have a way to trigger apiserver restart on gke at this moment. Sending a PR to skip this test on gke.

**Comment by MrHohn** [comment]
> Test is now passing on gce but failing on gke. Apparently we don't have a way to trigger apiserver restart on gke at this moment. Sending a PR to skip this test on gke.

Commented too quick. On gke we do a same-version master upgrade. Will send another fix :/
