### ISSUE TITLE
[test failed] [1.10 upgrade] Servers with support for Table transformation

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60765]
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig sig-api-machinery
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone
/milestone v1.10

cc @jdumars @jberkus 
/assign @lavalamp @deads2k

**Comment by krzyzacy** [comment]
xref https://github.com/kubernetes/kubernetes/issues/60764

**Comment by soltysh** [comment]
The three tests in `test/e2e/apimachinery/table_conversion.go` should be run only on 1.10+ servers. I'm just putting a PR together, should be up within next hour or so.

**Comment by soltysh** [comment]
Master fix is in https://github.com/kubernetes/kubernetes/pull/60797. 
1.10 fix in in https://github.com/kubernetes/kubernetes/pull/60798.

**Comment by liggitt** [comment]
/reopen
still failing in upgrade tests: http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

the 1.9 e2e tests are checking alpha response types that don't exist any more in 1.10

requires changing 1.9 to not test these alpha features in 1.10 that dropped support for those alpha features

**Comment by jdumars** [comment]
Is there anyone from @k8s-mirror-api-machinery-bugs that can look into this?

**Comment by juanvallejo** [comment]
@liggitt @jdumars looking into this

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/61139
