### ISSUE TITLE
[test failed] [1.10 upgrade]  Dynamic Provisioning DynamicProvisioner

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60766]
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig sig-storage
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone
/milestone v1.10

cc @jdumars @jberkus
/assign @saad-ali @childsb

**Comment by krzyzacy** [comment]
xref #60764

**Comment by jsafrane** [comment]
This looks similar to https://github.com/kubernetes/kubernetes/pull/56600. Were all tests there updated? @msau42, @jingxu97, WDYT?

**Comment by msau42** [comment]
@krzyzacy IIUC, this suite is running 1.9 versions of e2e tests against 1.9 + master?

If that's the case, then I think we need to change the 1.9 version of the e2e test to:
- Use G instead of Gi
- Check actual capacity >= expected

**Comment by msau42** [comment]
In #56600, the minor breaking change is already called out in the release note.

**Comment by gnufied** [comment]
+1 to changing 1.9 (and master)'s test to check for capacity >= expected. But 1.9 branch is frozen as well IIRC.

**Comment by krzyzacy** [comment]
if this is impacting 1.10 upgrade suite then please cherrypick & backport fixes to 1.9 :-)

**Comment by msau42** [comment]
Problem is 1.9 branch is frozen now, so we need to wait until it unfreezes to fix this test...

**Comment by verult** [comment]
Because this test is run in 1.9 as well, there needs to be a version check

**Comment by msau42** [comment]
I don't think you need a version check.  Just checking expected >= actual should work in both 1.9 and 1.10

**Comment by verult** [comment]
ACK

**Comment by verult** [comment]
PR submitted (https://github.com/kubernetes/kubernetes/pull/60899), awaiting review and 1.9 branch to be unfrozen.

**Comment by verult** [comment]
PR has been approved; awaiting 1.9 branch to be unfrozen

**Comment by saad-ali** [comment]
PR https://github.com/kubernetes/kubernetes/pull/60899 approved

**Comment by verult** [comment]
PR #60899 merged.
/close
