### ISSUE TITLE
Kube scheduler not finding PVC

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#60770]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

/kind bug

**What happened**:

Kube scheduler could not attach a PVC to a pod, it thought that the PVC did not exist when it did. The event on the pod was
pod name: svc-221087-0 
```
Events:
  Type     Reason                 Age                 From                                   Message
  ----     ------                 ----                ----                                   -------
  Warning  FailedScheduling       5m (x1212 over 6h)  default-scheduler                      persistentvolume "pvc-ff9e7a1a-2003-11e8-a139-0a14b2585426" not found (repeated 10 times)
```
And there were numerous logs in the kube scheduler:
```
Mar 04 23:30:23 ip-10-0-125-177 kube-scheduler[24283]: E0304 23:30:23.814007   24283 factory.go:913] Error scheduling rubix-skykube svc-221087-0: persistentvolume "pvc-ff9e7a1a-2003-11e8-a139-0a14b2585426" not found (repeated 10 times); retrying
```
And yet 
```
[rmcnamara ~]$ kubectl get pv pvc-ff9e7a1a-2003-11e8-a139-0a14b2585426
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                                      STORAGECLASS            REASON    AGE
pvc-ff9e7a1a-2003-11e8-a139-0a14b2585426   94Gi       RWO            Delete           Bound     namespace-name/svc-221087-etcd-data-4ea06403-svc-221087-0   my-aws-provisioner             6h
```

I restarted the kube-scheduler and the new instance was immediately able to find the PV and the pod in question was immediately scheduled. This makes me initially think this is a caching issue

**What you expected to happen**:

Expected the kube scheduler to find the PV without restart

**How to reproduce it (as minimally and precisely as possible)**:

This is the first time I've ever seen this, not sure how to get back into the state again.
Would definitely appreciate advice on how to in the future rule out if this is a caching issue or not.

**Anything else we need to know?**:

Additionally during this time there was another pod that couldn't be scheduled, however the reason for that was that a PVC couldn't be found. This was also immediately fixed on restart

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8+
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`):
```
[rmcnamara ~]$ uname -a
Linux ip-10-0-84-203 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yue9944882** [comment]
Information about PVC is retrieved via informer. The cache inside reflector might be outdated if it's too busy to apply watch events into indexer. But the `resyncPeriod` of informer is set to `0` currently so the reflector could not able to recover from overwhelming by watch events.

[https://github.com/kubernetes/kubernetes/blob/58731ae627ec195496222aa44b78d9dffef5ec21/cmd/kube-scheduler/app/server.go#L430](https://github.com/kubernetes/kubernetes/blob/58731ae627ec195496222aa44b78d9dffef5ec21/cmd/kube-scheduler/app/server.go#L430)

**Comment by ryanmcnamara** [comment]
Is it plausible that it wouldn't recover even after a long period of time (5 hours)?
The above message in the logs came something like 1000 times, as did the event
Agree changing the resync period could fix this and cause resync, but worried it's masking another bug.
