### ISSUE TITLE
the port field returned from kubectl get ingress cannot be customized

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#60781]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The value of port field shown when running kubectl get ingress is either 80 or 443, if the ingress controller expose another specified port. There is no way for ingress controller to update the status of ingress, and show it to the user.

**What you expected to happen**:
User should be able to view the right port of ingress controller when run kubectl get ingress command.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
> There is no way for ingress controller to update the status of ingress, and show it to the user.

WDYM? Ingress controller is not supposed to edit ingress proactively.

**Comment by qiujian16** [comment]
@yue9944882 commonly, ingress controller updates status of ingress resource

**Comment by zjj2wry** [comment]
> // TLS configuration. Currently the Ingress only supports a single TLS
	// port, 443. If multiple members of this list specify different hosts, they
	// will be multiplexed on the same port according to the hostname specified
	// through the SNI TLS extension, if the ingress controller fulfilling the
	// ingress supports SNI.
	// +optional
	TLS []IngressTLS


80 and 443 ports for the ingress controller configuration items, according to the field above port 443 can not be modified, I think kubectl can remove port 80, the controller can add an annotation for non-tls port (optional)
