### ISSUE TITLE
OpenAPI aggregator makes aggregation really slow

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#60810]
OpenAPI aggregation appears to block aggregation of the APIs and it is very slow.  Registering a dozen or so versions at the same time for openshift takes several seconds for each version, during which time the apiservice is unavailable.

Since we added etags to the openapi endpoints, clients who want the openapi will be alerted when they eventually aggregate.  Clients that don't need it will be able to use the endpoints straight away.

@sttts @mbohlool 
@kubernetes/sig-api-machinery-bugs

**Comment by mbohlool** [comment]
As far as I remember, OpenAPI aggregation is happening in another controller. Do you have some performance/trace data to see where/how the slowness is happening?

**Comment by deads2k** [comment]
I will work on a reproducer
