### ISSUE TITLE
Etcd salt defaults file is confusingly not used.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#6081]
Commit ba749284d0a8a12cf7067b9ba3b959cf55a1c375 by 
@davidopp says:
`Have etcd listen on all interfaces so that monit probes succeed. Closes #3852`.

Listening on all interfaces is the wrong thing to do from a security standpoint because it exposes etcd to modification.  

Once @ArtfulCoder change to put etcd in a pod is complete, then kubelet can monitor instead of monit, so then etc can be on 127.0.0.1.

It is confusing, because `DAEMON_ARGS` is set in `cluster/saltbase/salt/etcd/defaults`, which is where you normally set those things.  But that file is only pushed to the node by `cluster/saltbase/salt/etcd/init.sls` if the OS is red-hat.  What a mess.

**Comment by erictune** [comment]
This issue is really about the confusing salt config.  The

**Comment by zmerlynn** [comment]
Totally obvious. I don't see what you're complaining about.

**Comment by bgrant0607** [comment]
Fixed by #4442
