### ISSUE TITLE
Failure to update security groups for NLBs after rolling update

### ISSUE THREAD

**Issue by shrinandj** [kubernetes/kubernetes#60825]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

After a rolling update of the cluster, NLB kept failing health checks because security group did not have rules for new EC2 instance.

**What you expected to happen**:

Security group should have been updated with both TCP rules for NLBs to work correctly.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a service object with type LoadBalancer and adding the annotation for NLBs. FWIW, I had 6 services and each had their own NLBs. It’s possible that the bug happens when there are multiple NLBs causing multiple AWS updates.
- Perform a rolling update of the instance group. This causes the instances to be terminated and new ones to be brought up. AFAICT, this should result in two changes to the security group per EC2 instance. When the instance is terminated, the rules for that nodePort should be deleted. When the new node is created, the rule should be added again.
- However, after the rolling update, the rule doesn’t get added. As a result, the NLB’s health checks fail.

**Anything else we need to know?**:

- As mentioned earlier, this happened on a cluster where there were multiple NLBs.
- This doesn’t seem to be a deterministic failure. 
- The `kube-controller` log has the following error message:
```
I0305 18:04:40.968739       6 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kafka-1", Name:"outside-4", UID:"805bbe82-2033-11e8-ab46-06d9f670eba0", APIVersion:"v1", ResourceVersion:"6076", FieldPath:""}): type: 'Warning' reason: 'LoadBalancerUpdateFailed' Error updating load balancer with new hosts [ip-172-20-124-189.us-west-2.compute.internal ip-172-20-120-186.us-west-2.compute.internal ip-172-20-51-19.us-west-2.compute.internal ip-172-20-45-228.us-west-2.compute.internal ip-172-20-72-38.us-west-2.compute.internal ip-172-20-105-78.us-west-2.compute.internal ip-172-20-69-148.us-west-2.compute.internal ip-172-20-88-181.us-west-2.compute.internal ip-172-20-38-132.us-west-2.compute.internal ip-172-20-103-250.us-west-2.compute.internal ip-172-20-50-106.us-west-2.compute.internal ip-172-20-81-141.us-west-2.compute.internal ip-172-20-55-251.us-west-2.compute.internal ip-172-20-65-146.us-west-2.compute.internal ip-172-20-103-197.us-west-2.compute.internal]: InvalidPermission.NotFound: The specified rule does not exist in this security group.
```

- I manually edited the Service object to see if it would simply retrigger an update on the cloud resources. It actually did. The rules got added to the security group.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
kops 1.8.1
- Others:

**Comment by vikasuy** [comment]
@shrinandj did you find any workarounds?

we've run into this issue, where the security group rules got deleted. Specifically, we found that the security group missed the following:
1) TCP rule to allow traffic from NLB to Node Port 
2) TCP rule to allow traffic from NLB to Healthcheck Port
We added these manually back in to fix, but were surprised these were deleted in the first place.

**Comment by vikasuy** [comment]
This stackoverflow also is relevant: https://stackoverflow.com/questions/49523856/my-kubernetes-aws-nlb-integration-is-not-working

**Comment by shrinandj** [comment]
One workaround was to simply refresh the Kubernetes service object. We added/updated a label in the Kubernetes service object and found that it would make the corresponding changes in AWS.

**Comment by vikasuy** [comment]
thanks @shrinandj! have you been able to root cause why the rule doesn't get added? 
We're trying to re-produce the failure ourselves, too.

**Comment by suryamegham1729** [comment]
Any update on this bug fix release please?

**Comment by Overbryd** [comment]
Sorry to bother you with commenting on this issue. But I cannot find out in what version of Kubernetes this is expected to be released / was released.

Any clarification highly appreciated.
