### ISSUE TITLE
the "Reconfigure a Node's Kubelet in a Live Cluster" tutorial doesn't work

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#60821]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
i got some troubles in following this tutorial [reconfigure-kubelet](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/). It is recommended to reconfigure the kubelet with configmap, but when i use "kubectl edit node " to modify the kubelet configuration with setting eventRecordQPS=10, nothing changed though the output showing "node *** edited", and the ConfigOk status did not show up in the node status. For more info, the configmap, corresponding role and rolebinding can be all created successfully. Is  there anything i have missed or this tutorial needs to be updated?

**What you expected to happen**:
the node status changed as it's meant to be, such as the ConfigOK status showing up, and the eventRecordQPS should be equal to 10.

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the tutorial and it's stucked in the `Observe that the Node begins using the new configuration` section.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.0.1358+3e78c4904e1298-dirty", GitCommit:"3e78c4904e12983f5a921ac98b7c580c8c143a04", GitTreeState:"dirty", BuildDate:"2017-12-20T08:56:32Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.0.1358+3e78c4904e1298-dirty", GitCommit:"3e78c4904e12983f5a921ac98b7c580c8c143a04", GitTreeState:"dirty", BuildDate:"2017-12-20T09:01:04Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tianshapjq** [comment]
I'm not sure is anyone can answer this, is anyone I can refer to?

**Comment by tianshapjq** [comment]
or do I have to configure the node into the system:node group? or any prerequisites did I miss?

**Comment by tianshapjq** [comment]
I missed configuring the DynamicKubeletConfig to all components, just set to the kubelet.

**Comment by workhardcc** [comment]
@tianshapjq what is "DynamicKubeletConfig to all components", maybe I have the same issue with u.
