### ISSUE TITLE
[feature request] add --node-annotations command flag for kubelet

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#60832]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

add --node-annotations command flag for kubelet

**What you expected to happen**:

we want to store non-label-style information in node annotations when node registers, like nodeId,availableZone and so on.

However currently, kubelet doesn't support this feature, it only support --node-labels. 

I think it's a general feature.

**Comment by shenlanse** [comment]
@vikaschoudhary16  @jhorwit2 @liggitt

**Comment by liggitt** [comment]
`--node-labels` has been problematic (see https://github.com/kubernetes/community/pull/911). do we want to double down on this with annotations?

**Comment by shenlanse** [comment]
Thanks for your explanation. Close it.

**Comment by mattysweeps** [comment]
Please reopen this ticket. There's not enough justification to allow setting node labels in kubelet but not allow setting node annotations. The security differences between these two should be moot.

@liggitt if you provided @shenlanse with more information for why node annotations are roblematic, can you reiterate those reasons here?

As a last note: per [the API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#label-selector-and-annotation-conventions), labels are generally the user's domain. Hence my interest in using annotations.

**Comment by lizthegrey** [comment]
Likewise having this problem. We'd like to automatically apply some annotations to incoming nodes in a specific EKS nodegroup. This could be done for labels with `--kubelet-extra-args --node-labels=[...]`, but we can't do this with annotations, and instead will have to use an admission controller which is substantially more work/complexity.
