### ISSUE TITLE
fluentd-elasticsearch doesn't handle graceful termination

### ISSUE THREAD

**Issue by ant1441** [kubernetes/kubernetes#60841]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When the [fluentd-es](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml) DaemonSet Pods using the fluentd-elasticsearch [Docker image](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile) are killed, they do not handle the initial signal to gracefully terminate.
This means when the Pod is terminated, it takes at least 30 seconds, as kubernetes waits for the grace period to expire before sending SIGKILL, which does kill it.

**What you expected to happen**:
fluentd running in the container receives the initial TERM signal and gracefully exits, flushing its buffer while doing so.

**How to reproduce it (as minimally and precisely as possible)**:

* With a cluster running the _fluentd-elasticsearch_ DaemonSet, do (eg.) `kubectl delete fluentd-es-m45ws`
* Notice the Pod immediately shows as "Terminating" when running `kubectl get pods`
* Notice the Pod takes at least 30 seconds to terminate

**Anything else we need to know?**:

I have fixed this in my deployment by adding [dumb-init](https://github.com/Yelp/dumb-init) to the [Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile), just adding `dumb-init` to the apt packages to install and an `ENTRYPOINT`:

```
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
```

However, I noticed that when (running locally) I send the SIGTERM signal to the container it does not log "Received graceful stop" as it does when I send SIGINT to the container.
It does however exit immediately.

This may mean that logs are lost as they are not flushed when killing this Pod. This may be acceptable as this is the current behavior after the 30 second grace period.

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others:
  - Reproduced with the `k8s.gcr.io/fluentd-elasticsearch:v2.0.4` image

**Comment by pobodysnerfect** [comment]
this issue reproduces for me as well. worth mentioning that signal forwarding works fine in the fluentd managed docker images (I tested this):

https://github.com/fluent/fluentd-docker-image

we are definitely losing logs due to this issue because the buffer can only be flushed properly if the signal is forwarded properly.
/reopen
