### ISSUE TITLE
UpdateStatus doesn't work for CRDs (v1.10.0-beta.1)

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#60845]
/kind bug

**What happened**:
UpdateStatus doesn't work for CRD (receives a 404)

**How to reproduce it (as minimally and precisely as possible)**:

1. Start kube-apiserver with `--feature-gates=CustomResourceSubresources=true`
2. Get the sample-controller for CRDs
```
go get k8s.io/sample-controller
cd ${GOPATH}/src/k8s.io/sample-controller
git checkout aecec8f389159b335d6bcf0a4e96ea722058ec38
# apply the diff in [0]
./hack/update-codegen.sh
go run *.go -kubeconfig=$HOME/.kube/config
# on a different terminal but in the same directory run
# create a CustomResourceDefinition
$ kubectl create -f artifacts/examples/crd.yaml
# create a custom resource of type Foo
$ kubectl create -f artifacts/examples/example-foo.yaml
# You'll see, in the first terminal,
E0306 13:09:31.481700   24661 controller.go:236] error syncing 'default/example-foo': the server could not find the requested resource (put foos.samplecontroller.k8s.io example-foo)
```

[0]
```
diff --git a/controller.go b/controller.go
index a98ff1f..c7331b7 100644
--- a/controller.go
+++ b/controller.go
@@ -331,7 +331,7 @@ func (c *Controller) updateFooStatus(foo *samplev1alpha1.Foo, deployment *appsv1
        // update the Status block of the Foo resource. UpdateStatus will not
        // allow changes to the Spec of the resource, which is ideal for ensuring
        // nothing other than resource status has been updated.
-       _, err := c.sampleclientset.SamplecontrollerV1alpha1().Foos(foo.Namespace).Update(fooCopy)
+       _, err := c.sampleclientset.SamplecontrollerV1alpha1().Foos(foo.Namespace).UpdateStatus(fooCopy)
        return err
 }
 
diff --git a/pkg/apis/samplecontroller/v1alpha1/types.go b/pkg/apis/samplecontroller/v1alpha1/types.go
index 1f6eb1f..74ffc67 100644
--- a/pkg/apis/samplecontroller/v1alpha1/types.go
+++ b/pkg/apis/samplecontroller/v1alpha1/types.go
@@ -21,7 +21,6 @@ import (
 )
 
 // +genclient
-// +genclient:noStatus
 // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
 
 // Foo is a specification for a Foo resource
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.1", GitCommit:"37555e6d24c2f951c40660ea59a80fa251982005", GitTreeState:"clean", BuildDate:"2018-03-01T06:50:06Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.1", GitCommit:"37555e6d24c2f951c40660ea59a80fa251982005", GitTreeState:"clean", BuildDate:"2018-03-01T06:15:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

cc @sttts @nikhita

**Comment by nikhita** [comment]
> create a CustomResourceDefinition
$ kubectl create -f artifacts/examples/crd.yaml

This CRD does not contain fields required for enabling subresources.

https://github.com/kubernetes/sample-controller/blob/aecec8f389159b335d6bcf0a4e96ea722058ec38/artifacts/examples/crd.yaml.

Using the CRD in https://github.com/kubernetes/kubernetes/pull/60021 will work fine with `UpdateStatus`.

**Comment by aanm** [comment]
@nikhita That has solve it. Now I'm seeing a new non-expected behavior:

If I use `Update`, not `UpdateStatus`, to update the whole CR, including `"status"`, there's no error returned from kube-apiserver and the status field was unchanged.

Is this the expected behavior? Should I assume with `Subresources: status` set in the CRD, the `Update` does not update the CR status?

**Comment by nikhita** [comment]
> Is this the expected behavior? Should I assume with Subresources: status set in the CRD, the Update does not update the CR status?

Yes, this is expected behaviour.

`.status` is generally used to inform about the current status of whatever is being managed by the controller. Ideally, you don't want users to modify the status section as part of updates to the main resource since it could be modified to an inconsistent state. Only the controller should be able to update the status part.

Essentially, `/status` gives you the ability to control what parts can be updated by a "normal" user and what parts can be updated by the controller.

The current behaviour is:

- If you have a `.status` when you create the resource, it will be dropped i.e. you cannot set status during creation.
- Updates to the main resource will ignore changes to `.status`.
- Only updates to the `/status` subresource can update `.status`.

When 1.10 will be released, this information will be included in the docs: https://deploy-preview-7439--kubernetes-io-vnext-staging.netlify.com/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#subresources

**Comment by dvaldivia** [comment]
@nikhita but when in the life-cycle of the CR can the status be updated? Inside an informer `AddFunc` state, if `UpdateStatus` is attempted, an error is produced by the API server that the resource doesn't exist yet, hinting that the informer thinks the object already exist and it's not ready for updates yet, however `Update` succeeds if called, but any changes to `Status` get rolled back

**Comment by arashout** [comment]
@dvaldivia have you figured out where in the life cycle we should be calling `UpdateStatus`? I'm trying to call `UpdateStatus` within the `Reconcile` loop when using `kubebuilder` framework and I get the "not found" error you described above.
