### ISSUE TITLE
PSP: improve error message for invalid supplementalGroups/fsGroup

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#60847]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is request for improvements.

**What happened**:
When PodSecurityPolicy provider validates `SecurityContext.SupplementalGroups` or `fsGroup` fields of a pod, it shows an error like "999 is not an allowed group" if the group doesn't belong to the range(s).

**What you expected to happen**:
It should include to the error message also the allowed values -- the ranges against what we were validating this group. This will simplify user experience and debugging.

**How to reproduce it (as minimally and precisely as possible)**:
- run kubernetes cluster with PSP support
- create a PSP that allows fsGroup/SupplementalGroups in some ranges
- grant to a user access to this PSP
- try to create a pod that has fsGroup/SupplementalGroups outside of the allowed ranges

**Anything else we need to know?**:
In order to improve the current behavior, we need to modify `Validate()` function here: https://github.com/kubernetes/kubernetes/blob/48a7048d9819ee516b3cfdf5c458b5815b640138/pkg/security/podsecuritypolicy/group/mustrunas.go#L71-L76

Reported-by: @dmage 

@kubernetes/sig-auth-feature-requests 
/kind help

**Comment by lnsp** [comment]
This looks like a good first issue!

My suggestion would be something like `999 is not an allowed group (allowed [231 - 261], [300 - 312])`. I would also suggest to merge overlaying ranges in the log message, like `[100 - 300], [150 - 450]` as `[100 - 450]`, to keep the log as concise as possible.

I will look into it.

**Comment by php-coder** [comment]
> (allowed [231 - 261], [300 - 312])

Maybe something like "(expected to be in range [231 - 261], [300 - 312])" ?

> I will look into it.

Thank you!

**Comment by php-coder** [comment]
We can use the same approach that `runAsUser` strategy uses: https://github.com/kubernetes/kubernetes/blob/48a7048d9819ee516b3cfdf5c458b5815b640138/pkg/security/podsecuritypolicy/user/mustrunas.go#L60-L63

**Comment by lnsp** [comment]
Sure, that is probably the most consistent solution.
