### ISSUE TITLE
CUSTOM_KUBE_DASHBOARD_BANNER is unset

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#60850]
`./cluster/../cluster/../cluster/gce/util.sh: line 792: CUSTOM_KUBE_DASHBOARD_BANNER: unbound variable`

@konryd you added this variable - PTAL

**Comment by nikhiljindal** [comment]
Ping?
I see that in all failure log messages for `pull-kubernetes-e2e-gce-100-performance`.
Not sure if thats the cause or just an error message I can ignore?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign
since I bumped into this
