### ISSUE TITLE
kubectl commands are still very hard to unit test

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#6085]
I was trying to write a simple regression test for #6083, and discovered it is still a huge pain to write unit tests. You have to create a test factory, a fake RESTClient, custom build a client.Fake, call SetupArgs() on the command, and then separately parse the args to pass to the Run<command> function. It needs to be way simpler or we will continue to lack test coverage of kubectl functionality.

**Comment by smarterclayton** [comment]
With the new testclient.Fake, it should be easier to simulate resource loading calls (you can ignore network behavior and serve REST queries).

**Comment by quinton-hoole** [comment]
Why closed?

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to any that are still interesting to fix.

I removed the test-infra tag because it is very specific to kubectl.
