### ISSUE TITLE
Local cluster leaking memory at about 500 MB per day per process while idle

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#60854]
/kind bug
**What happened**: Start a cluster using ./hack/local-up.sh. 
Now just monitor the memory on kube-apiserver and kube-controller-manager. 
Without doing anything else note the memory on each process has grown by 500 MB each day.
Tried this for 5 days and saw this steady growth.

**What you expected to happen**:
Memory to remain relatively flat after some initial growth.

**How to reproduce it (as minimally and precisely as possible)**:
Run ./hack/local-up.sh and wait.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration: local
- OS (e.g. from /etc/os-release): Debian GNU/Linux
- Kernel (e.g. `uname -a`): Debian 4.9.65-3+deb9u2
- Install tools:
- Others:

**Comment by sttts** [comment]
![bildschirmfoto 2018-03-08 um 12 33 57](https://user-images.githubusercontent.com/730123/37149142-3b1bbbe6-22cd-11e8-8819-cc7a728e32c0.png)

**Comment by ncdc** [comment]
Copying some of what was discussed in Slack - we need to redo a test with `KUBE_CACHE_MUTATION_DETECTOR=false` set when running `hack/local-up-cluster.sh`. This disables the cache mutation detector, which holds on to "all the things" 😄.

**Comment by lavalamp** [comment]
@sttts What does the chart mean?

@ncdc yeah @cheftako determined that most of it is from the mutation detector (it really makes me nervous to have test code linked in to the production binaries).

**Comment by sttts** [comment]
> What does the chart mean?

It was a differential pprof memory chart of hack/local-cluster-up.sh. But as @ncdc noted, we have to run it without mutation detection. I did that for an hour yesterday and did not notice much memory leaking.

**Comment by cheftako** [comment]
After the suggested fix (turn of mutation detection), there was no noticeable increase on controller manager memory and the api-server memory increase was down to 8 MB per day. (on my setup)

**Comment by sttts** [comment]
@cheftako closing this to remove it from the release radar. Feel free to reopen if you think we still have an issue.
