### ISSUE TITLE
Node upgrades: version-aware upgrades

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6086]
See issue #6079 as the roll-up for node upgrades.

This component of the node upgrade mechanism should:
- query the versions of the nodes
- determine what version nodes should be
- determine the subset of the nodes to upgrade
- determine which version those nodes should be upgraded to
- pass the results to the rest of the upgrade mechanism and continue

Blocked by #4855:
- a concrete definition of a node spec: a version tuple of (kubelet, kube-proxy, docker, kernel/OS)
- the ability to query the versions of the nodes

References:
- The most relevant discussion regarding the node version spec and the allowed upgrade path is #4855.
- Adding node components version to the API was added in #5951.

**Comment by roberthbailey** [comment]
The blocking issue here (#4855) is marked as part of v1.0-post but this issue is in v1.0. What do we need to do to reconcile them and make sure that we have an upgrade story for 1.0?

**Comment by mbforbes** [comment]
(again, sorry, I'll try to do a quick cleanup of these GitHub issues soon)

Our upgrade plan for v1.0 is now vastly simplified. If I understand correctly, we do need to be able to query the versions of the nodes, but we:

- don't care about a version tuple (we're just using the binary version)
- don't need to do complicated logic to determine what version they "should" be as it'll just be requested
- don't need to do complicated logic to determine what version they're "allowed" to be at as it'll just be <= the master
- don't care about heterogenous node versions (e.g. if we request an upgrade to 0.16.0, and there are 10 nodes at 0.16.0 and 1 node at 0.15.0, then we'll still do a "destructive" update to all nodes)

Thus, this issue will be a no-op for 1.0 as the simple implementation will be sufficient for 1.0

I'll switch this to 1.0-post in case the versioning gets solved... though I have a hunch that once this works and we start churning forward with our current versioning scheme, we probably won't go back and rigorously formalize (in which case, we would just close this).

**Comment by bgrant0607** [comment]
Closing as obsolete.
