### ISSUE TITLE
CRD should prevent generation changes if spec does not update

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#60864]
/kind bug
/sig api-machinery
/assign @nikhita 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/strategy.go#L120 increments generation if spec changes, but if spec does not change or if subresources are disabled, I'd expect generation to be forced to stay the same

**Comment by nikhita** [comment]
> if spec does not change or if subresources are disabled, I'd expect generation to be forced to stay the same

In these cases, the strategy doesn't touch generation but it is forced to be same in `BeforeUpdate`:

https://github.com/kubernetes/kubernetes/blob/f196b7c7523dbf0d6ed703a93af73f54e9d2e42c/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L98-L103

**Comment by liggitt** [comment]
Ah, didn't realize it was done universally. 
/close
