### ISSUE TITLE
kube-proxy can't load xz compressed kernel ip_vs module

### ISSUE THREAD

**Issue by jejer** [kubernetes/kubernetes#60869]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kube-proxy failed to load ip_vs.ko.xz module

**What you expected to happen**:
compressed kernel module ip_vs could loaded by kube-proxy

**How to reproduce it (as minimally and precisely as possible)**:
This issue noticed on RHEL

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.4 (Maipo)
- Kernel (e.g. `uname -a`): Linux j-upgrade-worker-edge-01 3.10.0-693.2.2.el7.x86_64 #1 SMP Sat Sep 9 03:55:24 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: from scratch
- Others:
modprobe ip_vs works fine on node.

```
insmod failed in kube-proxy container
# insmod /lib/modules/3.10.0-693.2.2.el7.x86_64/kernel/net/netfilter/ipvs/ip_vs.ko.xz
insmod: ERROR: could not insert module /lib/modules/3.10.0-693.2.2.el7.x86_64/kernel/net/netfilter/ipvs/ip_vs.ko.xz: Invalid module format
```

kube-proxy log:
```
[root@j-upgrade-worker-edge-01 /etc/modprobe.d]$ docker logs 71a413c7b015
I0307 03:32:57.394549       1 feature_gate.go:184] feature gates: map[]
time="2018-03-07T03:32:57Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: could not insert 'ip_vs': Exec format error\ninsmod /lib/modules/3.10.0-693.2.2.el7.x86_64/kernel/net/netfilter/ipvs/ip_vs.ko.xz`, error: exit status 1"
time="2018-03-07T03:32:57Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
```

**Comment by dixudx** [comment]
> Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed.

@jejer Please help check whether ipvs module has been included in the kernel.

```
$ lsmod| grep ip_vs
```

**Comment by jejer** [comment]
Hi @dixudx 
I can load this module on node using modprobe and insmod:
```
[root@j-upgrade-worker-edge-01 ~]$ modprobe -r ip_vs
[root@j-upgrade-worker-edge-01 ~]$ lsmod|grep ip_vs
[root@j-upgrade-worker-edge-01 ~]$ modprobe ip_vs
[root@j-upgrade-worker-edge-01 ~]$ lsmod|grep ip_vs
ip_vs                 141092  0
nf_conntrack          133387  9 ip_vs,nf_nat,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4,nf_conntrack_ipv6
libcrc32c              12644  3 ip_vs,nf_nat,nf_conntrack
[root@j-upgrade-worker-edge-01 ~]$ modprobe -r ip_vs
[root@j-upgrade-worker-edge-01 ~]$ insmod /lib/modules/3.10.0-693.2.2.el7.x86_64/kernel/net/netfilter/ipvs/ip_vs.ko.xz
[root@j-upgrade-worker-edge-01 ~]$ lsmod|grep ip_vs
ip_vs                 141092  0
nf_conntrack          133387  9 ip_vs,nf_nat,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4,nf_conntrack_ipv6
libcrc32c              12644  3 ip_vs,nf_nat,nf_conntrack
[root@j-upgrade-worker-edge-01 ~]$
```

**Comment by vfreex** [comment]
Are you running kube-proxy in containers?
This is probably because the `modprobe` binary (usually provided by `kmod` package) in your container is NOT compiled with compression support. See `CONFIG_MODULE_COMPRESS`.

**Comment by jejer** [comment]
@vfreex ,
Yes, the image is gcr.io/google-containers/kube-proxy-amd64:v1.9.2

**Comment by vfreex** [comment]
@jejer Yeah, the `modprobe` in `gcr.io/google-containers/kube-proxy-amd64:v1.9.2` is not compiled with `CONFIG_MODULE_COMPRESS`, so that loading compressed kernel modules on hosts is not supported.

**Comment by ReSearchITEng** [comment]
I am facing the same with the default 1.10 image:
k8s.gcr.io/kube-proxy-amd64:v1.10.0

**Comment by jejer** [comment]
@ReSearchITEng I load ip_vs at boot time.
cat /etc/modules-load.d/ip_vs.conf
ip_vs

**Comment by ReSearchITEng** [comment]
@jejer , please confirm:
We can run k8s in containers, and  if we update /etc/modules-load.d/ip_vs.conf , on the host, there won't be a need for the container to call modproble any longer, so it does not matter if it's compiled with compress. 
This would word around the issue I guess, so modprobe can be even removed from the image.

**Comment by jejer** [comment]
@ReSearchITEng ,
Yes. guess kubelet run lsmod or something similar before modprobe.

**Comment by rifaterdemsahin** [comment]
is this normal ?
![image](https://user-images.githubusercontent.com/5270036/48490383-32df7100-e81d-11e8-8bee-8151cd4da198.png)

**Comment by jejer** [comment]
kube-proxy container based on a debian image, which don't support compressed module.
debian enabled compressed module support in kmod 25-1 at 21 Jan 2018.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772628

**Comment by ReSearchITEng** [comment]
One needs to make sure all the modules are loaded on the host, so the processes in the pod won't be required to load the these kernel modules, as they are already loaded. See this: https://github.com/ReSearchITEng/kubeadm-playbook/blob/master/roles/common/tasks/kernel_modules.yml

**Comment by randomvariable** [comment]
Confirming this issue.

We should ship modprobe with compressed support.

@jejer - does this mean if we update our build dependencies, we should be ok?

/assign

**Comment by jejer** [comment]
suppose update base image should fix this issue.

**Comment by dcbw** [comment]
@spencerhance
