### ISSUE TITLE
staging repositories not handled properly in bazel-built kubernetes-src.tar.gz

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#60863]
I've been experimenting with producing a kubernetes src tarball from bazel that includes all generated code, such that an end user (like an OS distro) would be able to build kubernetes binaries using solely `go build`.

The kubernetes-src.tar.gz produced by the [build rule in build/release-tars](https://github.com/kubernetes/kubernetes/blob/f196b7c7523dbf0d6ed703a93af73f54e9d2e42c/build/release-tars/BUILD#L39-L52) almost already works, except that the staging directory symlinks under vendor/k8s.io are not handled correctly; some of the auxiliary files are included, but none of the go files.

For example:
```console
$ bazel build build/release-tars/kubernetes-src.tar.gz --define PACKAGE_SRC=true
INFO: Analysed target //build/release-tars:kubernetes-src.tar.gz (2 packages loaded).
INFO: Found 1 target...
Target //build/release-tars:kubernetes-src.tar.gz up-to-date:
  bazel-bin/build/release-tars/kubernetes-src.tar.gz
INFO: Elapsed time: 3.197s, Critical Path: 2.37s
INFO: Build completed successfully, 3 total actions
$ tar tzvf bazel-bin/build/release-tars/kubernetes-src.tar.gz | grep vendor/k8s.io/apimachinery
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/.github/
-r-xr-xr-x 0/0             150 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/.github/PULL_REQUEST_TEMPLATE.md
-r-xr-xr-x 0/0             730 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/CONTRIBUTING.md
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/
-r-xr-xr-x 0/0            4873 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/Godeps.json
-r-xr-xr-x 0/0              27 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/OWNERS
-r-xr-xr-x 0/0             136 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/Readme
-r-xr-xr-x 0/0           11358 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/LICENSE
-r-xr-xr-x 0/0             243 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/OWNERS
-r-xr-xr-x 0/0            1251 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/README.md
-r-xr-xr-x 0/0             148 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/code-of-conduct.md
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/pkg/
-r-xr-xr-x 0/0              74 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/pkg/OWNERS
```
(Directory permissions also seem to be incorrect, which seems to be a bug in our fast build_tar implementation. The bazel-bundled one does not have this bug.)

I was able to fix this locally with a few basic changes:
* Adding `BUILD` files to all of the `staging/src/k8s.io` repos at their root to prevent any of these auxiliary files from ending up in the tarball. I believe this is because these files are matching the `package-srcs` glob in `vendor/BUILD`, but the `all-srcs` list does not follow symlinks (and hence the go files are missing, since those directories have BUILD files already).
* Explicitly adding a symlink attribute to the `kubernetes-src` `pkg_tar` rule with the staging symlinks:
```python
STAGING_DIRS = [
    "api",
    "apiextensions-apiserver",
    "apimachinery",
    "apiserver",
    "client-go",
    "code-generator",
    "kube-aggregator",
    "metrics",
    "sample-apiserver",
    "sample-controller",
]

pkg_tar(
    name = "kubernetes-src",
    srcs = select({
        ":package_src": ["//:all-srcs"],
        "//conditions:default": ["README-src.txt"],
    }), 
    extension = "tar.gz",
    package_dir = "kubernetes",
    strip_prefix = select({
        ":package_src": "//",
        "//conditions:default": ".",
    }), 
    symlinks = {"kubernetes/vendor/k8s.io/%s" % dir: "../../staging/src/k8s.io/%s" % dir for dir in STAGING_DIRS},
    tags = ["no-cache"],
)
```

What I haven't figured out yet is how best to manage that list of staging directories. (Extend kazel? Not excited about that, though.)

One other change is that we need to declare an explicit dependency on generated source files, since they are not picked up by globs; for example, in `pkg/generated/openapi/BUILD`:
```python
filegroup(
    name = "package-srcs",
    srcs = glob(["**"]) + [":zz_generated.openapi"],
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)
```

The good news is that with these changes I can extract kubernetes-src.tar.gz and `go build k8s.io/kubernetes/cmd/kube-apiserver` successfully.
(You can't do that in k/k without first running `make generated_files` or using bazel.)

/assign

**Comment by ixdy** [comment]
/assign
/remove-lifecycle stale

The new `go_path` work should improve this.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

@ixdy Is this still relevant?

**Comment by ixdy** [comment]
Yeah, the kubernetes-src tarball should still include all generated srcs.

I was hoping the new implementation of `go_path` would help with this, but I'm not so sure, since we'd need to explicitly list all `go_library`s in the tree or something. (This isn't a mode bazel is really great at.)

@jayconrod can you think of a better way to get all sources for the entire tree into a gopath?

**Comment by ixdy** [comment]
/remove-lifecycle rotten

I rediscovered and fixed the tarfile directory permissions issue in https://github.com/kubernetes/repo-infra/pull/104.

The other issues still remain. I'm not sure of the best approach, but we now have even more staging directories than we did before.

**Comment by ixdy** [comment]
I think I have found a workable approach: we can add a few lines to `hack/update-bazel.sh` to ensure that every staging repo has a `BUILD` file at its root, and we can then generate a `.bzl` file containing a list of these repos to use to create the necessary symlinks.

The issue with generated files no longer seems to be true (at least for openapi) - I think https://github.com/kubernetes/kubernetes/pull/71529 may have fixed that issue.
