### ISSUE TITLE
Scheduler should be able to rebuild its cache and compare it with the existing one

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#60860]
We have seen a few issues indicating that scheduler cache becomes stale and no longer reflects the most recent state of the cluster (#42433, #56057, #43806).
Scheduler cache issues can be very subtle to debug. In order to make it easier, we would like to build a mechanism in scheduler to resync its informers and rebuild its cache periodically and then compare the newly rebuilt cache to its existing cache and log error messages when it sees discrepancies. This feature will be disabled by default. We will probably enable it in our tests and in clusters where customers see stale cache issues

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

/sig scheduling

**Comment by yue9944882** [comment]
Related #60770

**Comment by anfernee** [comment]
@bsalamat this issue can be closed.

**Comment by bsalamat** [comment]
This is already built. The feature is triggered by sending SIGUSR2 signal to the scheduler process. We decided to not include periodic triggers as it would pollute scheduler flags with debugging args and the periodic triggering can be achieved by other means, for example by running a script that sends the signal to the scheduler.

We should build at least one or two integration tests that create a scheduler, adds a few pods and nodes, then deletes some of the pods and nodes and compares the cache by using this new feature.
