### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce is failing

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#60870]
http://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-kubemark-e2e-gce
starting this afternoon

/kind bug
/priority failing-test
/priority critical-urgent
/milestone v1.10

**Comment by krzyzacy** [comment]
/sig testing
/sig scalability

cc @jdumars @jberkus @shyamjvs @wojtek-t

**Comment by krzyzacy** [comment]
hummmmmmm
this might be the issue -
```
W0306 23:44:59.363] 2018/03/06 23:44:59 e2e.go:77: Calling kubetest -v --check-version-skew=false --test --test_args=--e2e-verify-service-account=false --dump-logs-on-failure=false --gather-resource-usage=true --report-dir=/workspace/_artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/14 --ginkgo.focus=\[Feature:Empty\]...
W0306 23:44:59.711] 2018/03/06 23:44:59 main.go:269: Flag parse failed: invalid argument "--check-version-skew=false" for "-v, --v" flag: strconv.Atoi: parsing "--check-version-skew=false": invalid syntax
W0306 23:44:59.712] 2018/03/06 23:44:59 e2e.go:79: err: exit status 1
```

but cc @BenTheElder our last kubekins bump was yesterday, and everything works fine, includes http://k8s-testgrid.appspot.com/sig-testing-canaries#kubemark-canary

**Comment by krzyzacy** [comment]
ok... kubemark-100-canary was not using `:latest` kubekins?
/shrug
fix incoming

**Comment by krzyzacy** [comment]
... my hypothesis: config updater did not actually updated prow config for https://github.com/kubernetes/test-infra/pull/7145, until https://github.com/kubernetes/test-infra/pull/7162

cc @cjwagner and I'll look at that code again

**Comment by jdumars** [comment]
Thanks @krzyzacy !

**Comment by krzyzacy** [comment]
the test-infra fix is actually for skew tests not for kubemark... I'll need to make the fix in k/k...

**Comment by krzyzacy** [comment]
I think the root issue is actually because kubemark testing script pulling another latest kubetest.. the k/k fix will bring kubemark presubmit back to green, k/t-i fix is not relevant to this job, but will be needed whenever we choose to bump kubekins again.

**Comment by krzyzacy** [comment]
okay that's healthy now, we'll still need to fix the kubemark script asap

**Comment by brancz** [comment]
I believe I'm getting the same failure here (based on and merging into 1.9 branch): https://github.com/kubernetes/kubernetes/pull/60921

**Comment by shyamjvs** [comment]
The same is being seen for our kubemark-small-last-release job - https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-small-last-release
Reopening the issue.. @krzyzacy could you please send cherrypick PR for 1.9 (and maybe also 1.8, depending on if we're running kubemark presubmit against it)?

**Comment by brancz** [comment]
Not sure if that's the right procedure, but I already cherry-picked this commit into #60921 to see if that resolves my issue, I'm happy to remove the commit again if that was wrong.

**Comment by BenTheElder** [comment]
Normally we follow https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md for cherry picks, we need to do this for any affected branches.

**Comment by krzyzacy** [comment]
I'll send the cherrypicks shortly

**Comment by jberkus** [comment]
At this point, should this issue be a blocker for 1.10 release?  Or is this open just for cherry-picks?

**Comment by krzyzacy** [comment]
it's not blocking 1.10

Cherrypicks has been open for older branches, they need to be merged to unblock those branches.

**Comment by krzyzacy** [comment]
all cherrypicks went in, closing
