### ISSUE TITLE
Remove remaining examples

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#60887]
I was working on separate demo based on guestbook-go example and wanted to push some updates to it's code. 
But looks like there are multiple versions. About 6 months ago some examples were moved to https://github.com/kubernetes/examples and have their README mention it. 
It was not noticed couple of times and resulted in new examples still being added to old location.
I think remaining examples should be moved and whole directory removed to avoid confusion. 

To allow anyone to pick that issue would be nice to for someone to describe what else should be done beside removing directory so nothing breaks (docs, etc.)

/area example
/kind cleanup
/sig apps
cc @ahmetb

**Comment by ahmetb** [comment]
@serathius +1000 for this. We recently added a blockade to this repo to prevent examples/ directory from being modified.

Would you be willing to take up this task? The only remaining work item is to bring the changes made to examples here to k/examples repo. This can be achieved 2 ways:
- preserve the git commit history (authors, commit messages) and port the commits there (sebgoa knows a way to do this, it's kind of non-trivial but still doable)
- just Ctrl+C/Ctrl+V everything, and look at "git diff" for each file to see if there's anything odd/backwards (as some stuff in k/examples are newer than here, and there might be some examples that are diverged in each repo).

We're currently looking for volunteers.

/cc @idvoretskyi

**Comment by serathius** [comment]
Looks like there is staging directory in new repo containing most of examples. 
Should examples be moved there? It's hard to spot because it's mixed with other examples. 
Just want to be sure before trying anything.

**Comment by ahmetb** [comment]
Yes, we need to bring updates to what's in `staging/`. The content outside `staging/` are maintained actively by me.

While importing stuff, there we need to make sure bringing the k/k-only changes to k/examples, while making sure the changes made only in k/examples aren't destroyed/lost. That should be about it, I'm happy to assist/review along the way.

**Comment by ahmetb** [comment]
https://github.com/kubernetes/examples/pull/210 now merged.

We can probably proceed with the deletion of `examples/`. (note that https://github.com/kubernetes/kubernetes/pull/60944 might be causing a conflict, wait for that to get in first).

**Comment by ixdy** [comment]
You probably know about all of these already, but binaries and tests that are depending on examples (perhaps just implicitly):
```console
$ bazel query 'kind(".*(_binary|_test)", rdeps(//..., //examples/...) - //examples/...)' | sort
//hack:verify-boilerplate
//pkg/kubectl/cmd:go_default_test
//pkg/kubectl/cmd/resource:go_default_test
//pkg/kubectl/cmd/set:go_default_test
//pkg/kubectl/resource:go_default_test
//test/e2e/framework:go_default_test
//test/e2e/framework/timer:go_default_test
//test/e2e:go_default_test
//test/e2e/manifest:go_default_test
//test/e2e/network/scale/localrun:localrun
//test/e2e_node:go_default_test
//test/e2e/scheduling:go_default_test
//test/integration/apiserver:go_default_test
//test/integration/auth:go_default_test
//test/integration/client:go_default_test
//test/integration/configmap:go_default_test
//test/integration/daemonset:go_default_test
//test/integration/defaulttolerationseconds:go_default_test
//test/integration/deployment:go_default_test
//test/integration/etcd:go_default_test
//test/integration/evictions:go_default_test
//test/integration/examples:go_default_test
//test/integration/garbagecollector:go_default_test
//test/integration/master:go_default_test
//test/integration/metrics:go_default_test
//test/integration/objectmeta:go_default_test
//test/integration/openshift:go_default_test
//test/integration/pods:go_default_test
//test/integration/quota:go_default_test
//test/integration/replicaset:go_default_test
//test/integration/replicationcontroller:go_default_test
//test/integration/scale:go_default_test
//test/integration/scheduler:go_default_test
//test/integration/scheduler_perf:go_default_test
//test/integration/secrets:go_default_test
//test/integration/serviceaccount:go_default_test
//test/integration/storageclasses:go_default_test
//test/integration/tls:go_default_test
//test/integration/ttlcontroller:go_default_test
//test/integration/volume:go_default_test
//test/soak/cauldron:cauldron
//test/soak/serve_hostnames:serve_hostnames
```

**Comment by ixdy** [comment]
direct dependencies being
```console
$ bazel query 'rdeps(//..., //examples/..., 1) - //examples/...' | sort
//:all-srcs
//build/release-tars:kubernetes
//pkg/kubectl/cmd:go_default_test
//pkg/kubectl/cmd/resource:go_default_test
//pkg/kubectl/cmd/set:go_default_test
//pkg/kubectl/resource:go_default_test
//test/e2e/generated:bindata
```

**Comment by ahmetb** [comment]
I think it's mostly kubectl, using some example manifest files. We've been able to move some of these manifests to https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests.

**Comment by serathius** [comment]
@ahmetb I'm currently deciding what to do with links to ``https://releases.k8s.io/HEAD/examples/`, which will be broken after removing `examples` directory. 
I asked on slack #sig-docs if it's ok to redirect everything to `https://github.com/kubernetes/examples/blob/master/`
Maybe you know reason for `releases.k8s.io` domain?

**Comment by ahmetb** [comment]
No I don't. Do these URLs appear in API reference docs? I believe it's maintained at https://github.com/kubernetes/k8s.io, you can suggest a PR with the redirection there.

**Comment by serathius** [comment]
great idea
I'm only worried that in new repo most of examples were moved to `staging` directory. 
Even if PR is accepted it would be hard to maintain

**Comment by idvoretskyi** [comment]
cc @thockin on the domain question.

**Comment by ahmetb** [comment]
I suspect the https://releases.k8s.io/HEAD/examples/ links are used almost only for the "storage" examples –which we can consider moving out of `staging/` directory. `staging/` directory exists, because we're probably gonna deprecate+delete a good amount (my guess is at least 70%) of those examples. Most of them are not maintained anymore, and that repo is not the right place to host it.
