### ISSUE TITLE
Set up kube-dns role in manifest and move it out of bootstrap

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#60897]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind cleanup
/sig network

**What happened**:
This has been brought up couple times:
- https://github.com/kubernetes/kubernetes/issues/23225#issuecomment-324376951
- https://github.com/kubernetes/kubernetes/pull/60833#issuecomment-371013456

Copied what was said, kube-dns default service account binding should not have been in bootstrap bindings, but part of the kube-dns RBAC manifest.

Also, we need to consider what to do with the federated cases where kube-dns requires additional access to nodes.

We should at least get some traction on this in the next cycle.
cc @liggitt @shashidharatd

**Comment by qiujian16** [comment]
would like to take a try if no one is working on it.

**Comment by ericchiang** [comment]
Was this announced as a depreciation? The only other time we removed a role we announced its deprecation beforehand https://github.com/kubernetes/kubernetes/pull/49638

**Comment by liggitt** [comment]
> Was this announced as a depreciation? The only other time we removed a role we announced its deprecation beforehand #49638

Hasn't been done yet, but removal would need to be done as a multi-release deprecation, I agree. That wouldn't preclude going ahead and setting up the binding/role in the manifest, and putting any new required permissions there.

**Comment by MrHohn** [comment]
This is still valid.
/remove-triage unresolved

**Comment by aojea** [comment]
@MrHohn is this still valid?

**Comment by pacoxu** [comment]
kube-dns releated seems to be deprecated.

Do we have same problem with system:coredns?

**Comment by MrHohn** [comment]
Closing this with kube-dns deprecated - I believe coredns has its RBAC set up differently.
