### ISSUE TITLE
kubeadm upgrade apply 1.9.0 fails to upgrade kubectl server

### ISSUE THREAD

**Issue by overip** [kubernetes/kubernetes#60893]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
I upgraded my k8s from 1.7.4 to 1.8.3. Then I tried to upgrade again from 1.8.3 to 1.9.0. The upgrade failed with the following error:
FATAL: The --version argument is invalid due to these errors:   - "There are kubelets in this cluster that are too old that have these versions [v1.7.4]"

The output of kubelet --version though is the following:
Kubernetes v1.9.0

**What you expected to happen**:
I expected a successful upgrade from k8s 1.8.3 to k8s 1.9.0

**How to reproduce it (as minimally and precisely as possible)**:
- Create 3 instances on AWS with Ubuntu 16.04
- Install k8s 1.7.4
- Install Weave 
- Upgrade k8s to 1.8.3 using kubeadm upgrade apply (following the official guide)
- Make sure that kubelet, kubectl, kubeadm are upgraded to 1.8.3
- Remove Weave, and upgrade Weave to the right version
- Upgrade k8s to 1.9.0 using kubeadm upgrade apply (following the official guide)
- The upgrade process fails, and show the error message pasted above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:
The output of kubectl version is the following:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

So it seems like that kubectl server was not upgraded.

**Comment by BenTheElder** [comment]
@overip those commands work in comments, not titles
Please re-file this issue against the kubeadm repo dedicated to kubeadm issues:
https://github.com/kubernetes/kubeadm
