### ISSUE TITLE
Static pod cannot pull image from private registry.

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#60913]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
We start apiserver/controller manager as static pods, and the images of kubernetes are saved in a private registry with authentication enabled. However, these images cannot be pulled due to authentication failure.

Docker login does not work, since kubelet does not leverage docker to pull image. It is better that we can have a flag in kubelet to set image pull secret for static pod.

**What you expected to happen**:
Image should be pulled and pod should be successfully spawned.

**How to reproduce it (as minimally and precisely as possible)**:
put apiserver image in a private registry, and start it using static pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
aren't the credentials in $kubelet-root-dir/.docker/config.json used?

**Comment by qiujian16** [comment]
@liggitt I do not think it is used, the kubelet will pull image at first here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_image.go#L87, and it fails because there is no image pull secret.

**Comment by liggitt** [comment]
Image pull secrets allow providing per-pod registry credentials. You can specify node-level registry credentials by placing docker credential files in the $kubelet-root-dir. That is what I'd expect to be done for static pods

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/blob/23e60ac9adefd5c6e5562765e942b492e6ce0f35/pkg/credentialprovider/provider.go

**Comment by qiujian16** [comment]
Oh, thanks! i will take look at it.

**Comment by qiujian16** [comment]
The reason is that I did not add HOME environment variable when starting kubelet, image can be successfully pulled after setting HOME for kubelet process. Close this issue.

@liggitt thanks for your help!
