### ISSUE TITLE
Support client certificate revocation

### ISSUE THREAD

**Issue by traghave** [kubernetes/kubernetes#60917]
Need help regarding revoking a already issued client certificates.

Steps to reproduce:

I added the groups information in the idtoken of oidcUser1 and configured the same groups
using "--oidc-groups-claim" in kubernetes

I've created created client certificate and key for use with kubectl.

openssl req -newkey rsa:2048  -out oidcuser.csr -nodes -keyout oidcuser.key -subj /CN=oidcUser/O=group1/O=group2
which works fine with
kubectl config set-credentials oidcuser --client-certificate=oidcuser.pem --client-key=oidcuser.key

Problem is if the user groups for oidcuser changes, then the certificate still have stale group information.

Is there any way we can configure apiserver to reject such certificates with assuming we have info related to certificate, key in hand?

**Comment by ericchiang** [comment]
Kubernetes doesn't have the ability to manage certificate revocation

Dupe of https://github.com/kubernetes/kubernetes/issues/18982

/close

**Comment by traghave** [comment]
@ericchiang
Could you suggest any alternative solution for this for time being?

**Comment by ericchiang** [comment]
Grant users bearer tokens instead of x509 certificates, use the kubelet client cert rotation, use RBAC and the node authorizer for authorization.
