### ISSUE TITLE
kubectl apply: print filename along with line number on parse errors

### ISSUE THREAD

**Issue by dwatzke** [kubernetes/kubernetes#60916]
/kind feature

**What happened**:
I ran this command on top of a directory that had an invalid yaml

`kubectl apply --validate=true --dry-run=true --filename=dir_with_multiple_yamls`

kubectl reported this error:

`error: error converting YAML to JSON: yaml: line 17: could not find expected ':'`

From that error message, one has no idea which file contains the syntax error.

Note that on certain different errors, filename is being reported, i.e. when you create a file that just contains "--".

**Minimal example**:

```
mkdir /tmp/kubetest
cd /tmp/kubetest
echo -e "--\na: b" > broken.yaml
kubectl apply --validate=true --dry-run=true --filename=$PWD
```

**What you expected to happen**:

on yaml parse error, kubectl should report filename as well as the line number -- at least in case directory is specified in kubectl apply

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.3+coreos.0 & v1.9.3+coreos.0

**Comment by dkrieger** [comment]
Similarly, when applying a multi-resource yaml file (separated by "---"), the line number given is relative to the resource, rather than the source file. This makes debugging errors when applying e.g. the output of `helm template .` extremely challenging.
