### ISSUE TITLE
Provide support for admission webhooks in all API servers out of the box

### ISSUE THREAD

**Issue by nilebox** [kubernetes/kubernetes#60924]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
There are generic admission controllers that are available in the core k8s API server, but not available in other API servers: ValidatingAdmissionWebhook, MutatingAdmissionWebhook, AlwaysAdmit, AlwaysDeny, EventRateLimit, OwnerReferencesPermissionEnforcement.
In order to use them in other API servers, e.g. Service Catalog (see https://github.com/kubernetes-incubator/service-catalog/issues/1812) we have to either add a dependency on `k8s.io/kubernetes`, or copy the source code.

**What you expected to happen**:
1. Move admission controllers that are not specific to the core API server to the `k8s.io/apiserver` repo
2. Enable MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission controllers by default, i.e. every API server using `k8s.io/apiserver` should get support for those admission controllers without having to manually register them.

**How to reproduce it (as minimally and precisely as possible)**:
See PR https://github.com/kubernetes-incubator/service-catalog/pull/1811 for amount of work that is needed to enable ValidatingAdmissionWebhook and MutatingAdmissionWebhook admission controllers in custom API server.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2

**Comment by nilebox** [comment]
@caesarxuchao

**Comment by deads2k** [comment]
This was a requirement for beta.  We added it here: https://github.com/kubernetes/apiserver/blob/release-1.9/pkg/admission/plugin/webhook/validating/admission.go 

I suspect that we may have missed some required permissions and should probably create an aggregated cluster role to manage "apiservers should have these", but the core code for enabling it is present.

**Comment by nilebox** [comment]
Already resolved in #56627, closing.
