### ISSUE TITLE
Kubernetes without docker

### ISSUE THREAD

**Issue by monique77** [kubernetes/kubernetes#60928]
< Please, People
I want to install Kubernetes without docker. Please send me article with step to step.
-->
My objective is to install Master kubernets without docker, but, at site oficial kubernetes no search.

But, is advisable to install kubernetes master without docker?

**Environment**:
- Kubernetes version (use `kubectl version`): V1.9
- Cloud provider or hardware configuration: nothing
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708
- Kernel (e.g. `uname -a`):  3.10.0-693.17.1.el7.x86_64
- Install tools:
- Others:

**Comment by ericchiang** [comment]
Yes It's possible to run the control plan components (kube-apiserver, kube-controller-manager, kube-scheduler) on the host without docker, and only run the kubelet (Kubernetes' node agent which talks to docker) on worker nodes.

Beside kubeadm, which uses docker on the controller nodes, the Kubernetes project doesn't maintain install strategies for Kubernetes. Please consider looking at one of the many conformant installers for an open source reference for how you might do this yourself or pick one that already makes this choice:

https://www.cncf.io/certification/software-conformance/
https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0

/close
