### ISSUE TITLE
Scheduler logs exploding in large clusters - Can crash master!

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#60933]
Today while running our 2k-node scalability presubmit against PR https://github.com/kubernetes/kubernetes/pull/60891, I noticed that scheduler throughput has fallen by ~4-5 times from the normal, i.e 100 pods/s -> 25 pods/s. Simultaneously, another 2k-node run I was manually running (against ~same code) showed normal throughput. I compared the scheduler manifests and only difference found was `--v=1` vs `--v=4`.

When I looked at size of scheduler logs, they were huuuugely differing (116KB vs 21GB):

```
shyamjvs@e2e-test-shyamjvs-master /var/log $ ls -al kube-scheduler.log 
-rw-r--r-- 1 root root 116826 Mar  8 14:47 kube-scheduler.log
```

vs

```
shyamjvs@e2e-3-master /var/log $ ls -al kube-scheduler.log 
-rw-r--r-- 1 root root 21479967994 Mar  8 14:48 kube-scheduler.log
```

And about 99% of those logs were just these kinds of lines:

```
I0308 14:41:44.900343       1 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-density-30-8-fzpjw/density60000-7-d7ba3921-22d8-11e8-a055-0a580a3c9dc0-srs4v", node "e2e-3-minion-group-9f72"
I0308 14:41:44.900375       1 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-density-30-8-fzpjw/density60000-7-d7ba3921-22d8-11e8-a055-0a580a3c9dc0-srs4v", node "e2e-3-minion-group-qhkb"
I0308 14:41:44.900072       1 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-density-30-8-fzpjw/density60000-7-d7ba3921-22d8-11e8-a055-0a580a3c9dc0-srs4v", node "e2e-3-minion-group-l75c"
I0308 14:41:44.900470       1 scheduler_binder.go:133] FindPodVolumes for pod "e2e-tests-density-30-8-fzpjw/density60000-7-d7ba3921-22d8-11e8-a055-0a580a3c9dc0-srs4v", node "e2e-3-minion-group-j4jf"
```

They're coming from the scheduler volume-binder:

https://github.com/kubernetes/kubernetes/blob/b3ba80b223bb3d21807d473eb4ed3ca0735d6f9f/pkg/controller/volume/persistentvolume/scheduler_binder.go#L129-L133

FMU that log would be printed ~O(#nodes*#pods) which is way too much for our officially supported (5k nodes, 150k pods) limit.
Also seems like `--v=4` is default verbosity level in our GCE config-default/test setups (correct me if I'm wrong) and that can eat up the whole disk. Which is what happened in the 2k-node run:

```
shyamjvs@e2e-3-master /var/log $ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root        1249792   471620    778172  38% /
...
/dev/sda1       47259264 47242880         0 100% /mnt/stateful_partition
```

As a result the apiserver started crash-looping and the test failed.

cc @kubernetes/sig-scheduling-bugs @kubernetes/sig-storage-misc @msau42 (who seems to have added that log) @wojtek-t

**Comment by shyamjvs** [comment]
I can try to bring down verbosity level for our scalability job, but IMO that's not the best thing to do (as we wouldn't be testing prod setup).
I believe we should instead increase it's verbosity to 6 at least. Thoughts?

**Comment by shyamjvs** [comment]
I'll send out a PR to increase the verbosity. However, there are few things we need to think about:

- run our scalability tests against the prod default verbosity instead of reduced value
- ensure that devs don't add log lines at V4 that are expected to be more than linear in #objects (or sth like that)
- generally shield from all master components crashing just because one of them spewed tons of logs (maybe we're already having some mechanisms that we may want to enable for our scale tests)

**Comment by msau42** [comment]
Shyam, I thought prod clusters have are log level 2 by default, and test clusters are log level 4

**Comment by shyamjvs** [comment]
I see.. thanks. Just verified that prod's at 2. Wdyt about increasing verbosity of that line though (as otherwise it doesn't seem to allow us to scale test with higher verbosity)?

**Comment by msau42** [comment]
Yah that's fine. I would prefer level 5 though

**Comment by jdumars** [comment]
Do we want to approve this for the milestone and make it blocking for the 1.10 release?  Also, does this merit being added to #59764 ?

**Comment by shyamjvs** [comment]
It's a relatively smaller problem and I've already sent the fix above (yet to merge). I'm fine either way.

**Comment by jdumars** [comment]
We can let the fix go through, then close this issue.  If there's something (even with the fix) that we feel needs to pass on to the user community, I'd love a volunteer to just quickly write that up in #59764 

Thanks again for all of your hard work here everyone!

**Comment by shyamjvs** [comment]
@jdumars Since this doesn't seem to be in production setup (though it may be for some), not sure how much it'll effect users. Also seems like this came in 1.10? (in which case it might be ok as we'll fix it before the release)

**Comment by shyamjvs** [comment]
Ok.. I checked it and seems like it was actually introduced in 1.9 (https://github.com/kubernetes/kubernetes/pull/55039)
@msau42 - Could you confirm? This may need 1.9 users running large clusters to be aware with the problem at v=4.

**Comment by jdumars** [comment]
Thanks so much for clarifying that. It might be worth a quick mention in the release notes, even if technically it's not a specific-to-1.10 issue.

**Comment by msau42** [comment]
In 1.9 the feature is alpha gated so users should not really be using it in production...
