### ISSUE TITLE
'./build/run.sh make test' generates call stack dump instead of summary in the end when test failed

### ISSUE THREAD

**Issue by y2kenny** [kubernetes/kubernetes#60946]
/kind bug

**What happened**:
When running ./build/run.sh make test, this is the result when there's a failed test:
```
ok      k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apiserver    0.035s
!!! Error in hack/make-rules/test.sh:402
 Error in hack/make-rules/test.sh:402. 'return ${rc}' exited with status 1
Call stack:
 1: hack/make-rules/test.sh:402 main(...)
Exiting with status 1
Makefile:184: recipe for target 'test' failed
make: *** [test] Error 1
!!! [0307 12:21:35] Call tree:
!!! [0307 12:21:35]  1: ./build/../build/common.sh:553 kube::build::run_build_command_ex(...)
!!! [0307 12:21:35]  2: ./build/run.sh:39 kube::build::run_build_command(...)
!!! Error in ./build/../build/common.sh:626
 Error in ./build/../build/common.sh:626. '((i<4-1))' exited with status 2
Call stack:
 1: ./build/../build/common.sh:626 kube::build::run_build_command_ex(...)
 2: ./build/../build/common.sh:553 kube::build::run_build_command(...)
 3: ./build/run.sh:39 main(...)
Exiting with status 1
```

**What you expected to happen**:
A summary of test results (pass, failed, no-ex, etc.)

**How to reproduce it (as minimally and precisely as possible)**:
./build/run.sh make test with a failing test.

**Environment**:
Checked out code at master:5364f7beb8
Ubuntu 16.04.3 LTS
kernel: 4.10.0-40-generic
$ go version
go version go1.9.4 linux/amd64
$ docker version
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:42:18 2017
OS/Arch: linux/amd64
Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:56 2017
OS/Arch: linux/amd64
Experimental: false

**Comment by kikisdeliveryservice** [comment]
I ran into this exact same issue on macOS 10.13.3 when I ran "./build/run.sh make test" today.
**Environment**
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm
Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
