### ISSUE TITLE
Provide client cert for liveness/readiness probe check

### ISSUE THREAD

**Issue by wattli** [kubernetes/kubernetes#60952]
Currently liveness/readiness probe only support http/TLS, but not mTLS, which blocks us from using this feature for mTLS services. 

We should provide option to let kubelet send client cert to services.

**Comment by wattli** [comment]
@timstclair , FYI

**Comment by tallclair** [comment]
/sig node

Is there any reason the Kubelet shouldn't always send it's client cert for HTTPS probes?

**Comment by PiotrSikora** [comment]
@tallclair The way client certificates work is that server requests client certificate during TLS handshake if it expects one (by providing list of recognized CAs), and client sends its client certificate only if server asked for it, so there is no reason not to provide client certificate.

Does this answers your question?

**Comment by tallclair** [comment]
Yep! Specifically, I like to avoid adding extra options to the API :)

**Comment by lookuptable** [comment]
@wattli which client cert are you referring to? The same cert that kubelet uses to talk with the master, or a different client cert that is signed by, for example, Istio CA?

**Comment by hzxuzhonghu** [comment]
>which client cert are you referring to? The same cert that kubelet uses to talk with the master, or a different client cert that is signed by, for example, Istio CA?

@lookuptable The latter.

**Comment by wattli** [comment]
Currently i think kubelet only has node cert. For simplicity, sending this cert to pod is good enough, all we need at server side (pod) is to add the root bundle of node cert.

**Comment by wattli** [comment]
Two questions for you @tallclair 
1) If we simply provide client cert for all https traffic, would this be any backward compatibility issue, personally i don't think so, but just want to double check
2) For GKE case, the cert is placed at a well-known place, but what about OSS? Is the path also fixed or it varies on different implementation?

**Comment by tallclair** [comment]
> If we simply provide client cert for all https traffic, would this be any backward compatibility issue, personally i don't think so, but just want to double check

I don't think so.

> For GKE case, the cert is placed at a well-known place, but what about OSS? Is the path also fixed or it varies on different implementation?

The path is configurable. More importantly, we're going to start rotating the cert soon.

> which client cert are you referring to? The same cert that kubelet uses to talk with the master, or a different client cert that is signed by, for example, Istio CA?

I was talking about the cert that the kubelet uses to authenticate to the master. Istio can verify that using the master CA.

**Comment by PiotrSikora** [comment]
I see 2 issues with re-using node certificate:

1. Istio proxies would need to include k8s master CA as a trusted CA. Does it change at all after initial setup? Is the CA available at fixed path in each container or would it need to be redistributed to proxies on a regular basis?

2. Istio uses certificates with SPIFFE Identity, which node certificates presumably don't provide, so while the mTLS connection would be accepted, Istio wouldn't see health-checker's identity, which might need to be handled as a special case and/or become a show-stopper at some point in the future.

Those are not a deal-breakers, but something to think about.

**Comment by wattli** [comment]
Istio proxies would need to include k8s master CA as a trusted CA. Does it change at all after initial setup? Is the CA available at fixed path in each container or would it need to be redistributed to proxies on a regular basis?

_- It's a very good question, for GKE, it's fixed and the CA root is long lived, like 10 years iirc. But not sure about OSS, @tallclair ?_

Istio uses certificates with SPIFFE Identity, which node certificates presumably don't provide, so while the mTLS connection would be accepted, Istio wouldn't see health-checker's identity, which might need to be handled as a special case and/or become a show-stopper at some point in the future.

_- Currently there is an option for kubelet not verify server cert, i.e., the cert issued by Istio._ 

Those are not a deal-breakers, but something to think about.

**Comment by wattli** [comment]
A use case https://github.com/istio/istio/issues/2628

**Comment by mkuendig** [comment]
We have the same issue? As this got closed, is there any chance that this will be ever implemented?

We do have a Java App that requires mTLS and we can't have a second port open for  healtchecks.

We do plan to move to istio at some point, but not in the next 12 months.

**Comment by mkuendig** [comment]
@wattli Any chance you can reopen this?
