### ISSUE TITLE
Node upgrades: write in Go and hook into pkg/cloudprovider

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6095]
See issue #6079 as the roll-up for node upgrades.

While the basic mechanisms (#6099, #6088) will be an out-of band process in Bash, we would like to have the mechanism be written in Go and hook into `pkg/cloudprovider`.

Aside from being generally more robust and maintainable, this will mean that our deployment and upgrade mechanisms can share code (as both move towards `pkg/cloudprovider` support). Also, hosted solutions can then upstream and share code for deployment and upgrades.

References:
- It was first mentioned in #3333 in [this comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/3333#issuecomment-69270075) that we don't want the upgrade mechanism to be a tangled mess of Bash scripts.
- The `kubedeploy` tool, which is related to sharing code for cluster-level operations and Bash &rarr; Go tooling, was proposed in #5472.

**Comment by roberthbailey** [comment]
This was tracking a feature improvement for kube-up, which is deprecated. Each installer does their own version of node upgrades, some of which are in-place.

/close
