### ISSUE TITLE
StatefulSet container not able to resolve hostname

### ISSUE THREAD

**Issue by agupta1** [kubernetes/kubernetes#60964]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When trying out Running a Replicated StatefulSet cluster example on kubernetes site, clone-mysql init container of mysql-1 Pod cannot resolve hostname of previous StatefulSet instance mysql-0.mysql and therefore fails.

kubectl get pods -o wide
NAME      READY     STATUS                  RESTARTS   AGE       IP             NODE
mysql-0   2/2       Running                 0          32m       192.168.1.12   kubenode1
mysql-1   0/2       Init:CrashLoopBackOff   10         31m       192.168.3.8    kubenode2

kubectl describe pod mysql-1
Name:           mysql-1
Namespace:      default
Node:           kubenode2/192.168.56.5
Start Time:     Fri, 09 Mar 2018 00:45:59 -0500
Labels:         app=mysql
                controller-revision-hash=mysql-84cf766458
                statefulset.kubernetes.io/pod-name=mysql-1
Annotations:    <none>
Status:         Pending
IP:             192.168.3.8
Controlled By:  StatefulSet/mysql
Init Containers:
  init-mysql:
    Container ID:  docker://22e5aef4defd684f7886ab20c77f091311b695a220ed1d1f4b5890e8eea83281
    Image:         mysql:5.7
    Image ID:      docker-pullable://docker.io/mysql@sha256:227d5c3f54ee3a70c075b1c3013e72781564000d34fc8c7ec5ec353c5b7ef7fa
    Port:          <none>
    Command:
      bash
      -c
      set -ex
# Generate mysql server-id from pod ordinal index.
[[ `hostname` =~ -([0-9]+)$ ]] || exit 1
ordinal=${BASH_REMATCH[1]}
echo [mysqld] > /mnt/conf.d/server-id.cnf
# Add an offset to avoid reserved server-id=0 value.
echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
# Copy appropriate conf.d files from config-map to emptyDir.
if [[ $ordinal -eq 0 ]]; then
  cp /mnt/config-map/master.cnf /mnt/conf.d/
else
  cp /mnt/config-map/slave.cnf /mnt/conf.d/
fi

    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 09 Mar 2018 00:46:10 -0500
      Finished:     Fri, 09 Mar 2018 00:46:10 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/conf.d from conf (rw)
      /mnt/config-map from config-map (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nsrnn (ro)
  clone-mysql:
    Container ID:  docker://5e8db63fce5c99364162c7102f08394fa04e7c8f6a6a6f38736247a334481b2b
    Image:         gcr.io/google-samples/xtrabackup:1.0
    Image ID:      docker-pullable://gcr.io/google-samples/xtrabackup@sha256:29354f70c9d9207e757a1bae6a4cbf2f57a56b18fe5c2b0acc1198a053b24b38
    Port:          <none>
    Command:
      bash
      -c
      set -ex
# Skip the clone if data already exists.
[[ -d /var/lib/mysql/mysql ]] && exit 0
# Skip the clone on master (ordinal index 0).
[[ `hostname` =~ -([0-9]+)$ ]] || exit 1
ordinal=${BASH_REMATCH[1]}
[[ $ordinal -eq 0 ]] && exit 0
# Clone data from previous peer.
ncat --recv-only mysql-$(($ordinal-1)).mysql 3307 | xbstream -x -C /var/lib/mysql
# Prepare the backup.
xtrabackup --prepare --target-dir=/var/lib/mysql

    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 09 Mar 2018 01:15:46 -0500
      Finished:     Fri, 09 Mar 2018 01:16:06 -0500
    Ready:          False
    Restart Count:  10
    Environment:    <none>
    Mounts:
      /etc/mysql/conf.d from conf (rw)
      /var/lib/mysql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nsrnn (ro)
Containers:
  mysql:
    Container ID:
    Image:          mysql:5.7
    Image ID:
    Port:           3306/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      200m
      memory:   256M
    Liveness:   exec [mysqladmin ping] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mysql -h 127.0.0.1 -e SELECT 1] delay=5s timeout=1s period=2s #success=1 #failure=3
    Environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:  1
    Mounts:
      /etc/mysql/conf.d from conf (rw)
      /var/lib/mysql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nsrnn (ro)
  xtrabackup:
    Container ID:
    Image:         gcr.io/google-samples/xtrabackup:1.0
    Image ID:
    Port:          3307/TCP
    Command:
      bash
      -c
      set -ex
cd /var/lib/mysql

# Determine binlog position of cloned data, if any.
if [[ -f xtrabackup_slave_info ]]; then
  # XtraBackup already generated a partial "CHANGE MASTER TO" query
  # because we're cloning from an existing slave.
  mv xtrabackup_slave_info change_master_to.sql.in
  # Ignore xtrabackup_binlog_info in this case (it's useless).
  rm -f xtrabackup_binlog_info
elif [[ -f xtrabackup_binlog_info ]]; then
  # We're cloning directly from master. Parse binlog position.
  [[ `cat xtrabackup_binlog_info` =~ ^(.*?)[[:space:]]+(.*?)$ ]] || exit 1
  rm xtrabackup_binlog_info
  echo "CHANGE MASTER TO MASTER_LOG_FILE='${BASH_REMATCH[1]}',\
        MASTER_LOG_POS=${BASH_REMATCH[2]}" > change_master_to.sql.in
fi

# Check if we need to complete a clone by starting replication.
if [[ -f change_master_to.sql.in ]]; then
  echo "Waiting for mysqld to be ready (accepting connections)"
  until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 1; done

  echo "Initializing replication from clone position"
  # In case of container restart, attempt this at-most-once.
  mv change_master_to.sql.in change_master_to.sql.orig
  mysql -h 127.0.0.1 <<EOF
$(<change_master_to.sql.orig),
  MASTER_HOST='mysql-0.mysql',
  MASTER_USER='root',
  MASTER_PASSWORD='',
  MASTER_CONNECT_RETRY=10;
START SLAVE;
EOF
fi

# Start a server to send backups when requested by peers.
exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
  "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root"

    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /etc/mysql/conf.d from conf (rw)
      /var/lib/mysql from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nsrnn (ro)
Conditions:
  Type           Status
  Initialized    False
  Ready          False
  PodScheduled   True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-mysql-1
    ReadOnly:   false
  conf:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  config-map:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      mysql
    Optional:  false
  default-token-nsrnn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-nsrnn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   Scheduled              34m                 default-scheduler   Successfully assigned mysql-1 to kubenode2
  Normal   SuccessfulMountVolume  34m                 kubelet, kubenode2  MountVolume.SetUp succeeded for volume "data-0"
  Normal   SuccessfulMountVolume  34m                 kubelet, kubenode2  MountVolume.SetUp succeeded for volume "conf"
  Normal   SuccessfulMountVolume  34m                 kubelet, kubenode2  MountVolume.SetUp succeeded for volume "config-map"
  Normal   SuccessfulMountVolume  34m                 kubelet, kubenode2  MountVolume.SetUp succeeded for volume "default-token-nsrnn"
  Normal   Pulled                 34m                 kubelet, kubenode2  Container image "mysql:5.7" already present on machine
  Normal   Created                34m                 kubelet, kubenode2  Created container
  Normal   Started                34m                 kubelet, kubenode2  Started container
  Normal   Pulled                 32m (x4 over 34m)   kubelet, kubenode2  Container image "gcr.io/google-samples/xtrabackup:1.0" already present on machine
  Normal   Created                32m (x4 over 34m)   kubelet, kubenode2  Created container
  Normal   Started                32m (x4 over 34m)   kubelet, kubenode2  Started container
  Warning  BackOff                4m (x119 over 33m)  kubelet, kubenode2  Back-off restarting failed container
kubectl logs mysql-1 -c clone-mysql
+ [[ -d /var/lib/mysql/mysql ]]
++ hostname
+ [[ mysql-1 =~ -([0-9]+)$ ]]
+ ordinal=1
+ [[ 1 -eq 0 ]]
+ ncat --recv-only mysql-0.mysql 3307
+ xbstream -x -C /var/lib/mysql
Ncat: Could not resolve hostname "mysql-0.mysql": Name or service not known. QUITTING.
+ xtrabackup --prepare --target-dir=/var/lib/mysql
xtrabackup version 2.4.4 based on MySQL server 5.7.13 Linux (x86_64) (revision id: df58cf2)
xtrabackup: cd to /var/lib/mysql
xtrabackup: Error: cannot open ./xtrabackup_checkpoints
xtrabackup: error: xtrabackup_read_metadata()
xtrabackup: This target seems not to have correct metadata...
InnoDB: Number of pools: 1
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.
xtrabackup: Error: xtrabackup_init_temp_log() failed.
[agupta@kubemaster replication]$
**What you expected to happen**:
It should resolve the hostname mysql-1.mysql and create pods.

**How to reproduce it (as minimally and precisely as possible)**:
Try running Replicated StatefulSet cluster example.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
MacBook Pro 15, VirtualBox
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):
Linux kubemaster 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
 kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Docker
docker version
Docker version 1.12.6, build 3e8e77d/1.12.6
- Others:

**Comment by agupta1** [comment]
/sig bug
Thanks, Anand 

    On Thursday, March 8, 2018, 10:41:56 PM PST, k8s-ci-robot <notifications@github.com> wrote:  
 
 
@agupta1: There are no sig labels on this issue. Please add a sig label.
 
A sig label can be added by either:
   
   -    
mentioning a sig: @kubernetes/sig-<group-name>-<group-suffix>   
e.g., @kubernetes/sig-contributor-experience-<group-suffix> to notify the contributor experience sig, OR

   -    
specifying the label manually: /sig <group-name>   
e.g., /sig scalability to apply the sig/scalability label


Note: Method 1 will trigger an email to the group. See the group list.
The <group-suffix> in method 1 has to be replaced with one of these: bugs, feature-requests, pr-reviews, test-failures, proposals

Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository.

**Comment by hoeghh** [comment]
Could it be related to https://github.com/kubernetes/kubernetes/issues/39197 ?
The service needs to be headless for the dns to work for statefulsets.

**Comment by zrml** [comment]
Has this ever been resolved? I'm finding the exact same issue and yes the service is headless...
thanks

**Comment by tschirmer** [comment]
I've found the same issue on kubernetes 1.19 (EKS). Has this been fixed?

**Comment by novotnej** [comment]
After three days pulling my hair out I can confirm that this has not been fixed (or perhaps became broken again). My service is headless, service selector is set correctly.

This could be a core-dns issue, because when I exec into the pods (mysql-0 and mysql-1), after several attempts the hostnames will resolve successfully, but weirdly sometimes it doesn't even resolve its own name, let alone of the second pod.

**Comment by tschirmer** [comment]
In my case, I found that prior to the upgrade to 1.19, our pods would have access to port TCP and UDP port 53 for DNS resolution, regardless of the network policy configurable, and afterward we needed to ensure the network policy was allowing port 53 for all pods. We're not sure why it wasn't enforced prior to this (we would expect that to be the case), but the name resolution started up again once we created the appropriate network policy.
