### ISSUE TITLE
Scheduler should use pod UID instead of "namespace/name" in its cache

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#60966]
The key that scheduler uses to store a pod in its ["assume" cache is "namespace/name"](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedulercache/cache.go#L126) of the pod. As I explained in https://github.com/kubernetes/kubernetes/issues/56682#issuecomment-371742634, this can cause issues if a pod that is being scheduled is deleted and a replacement pod with the same name and namespace is created. In order to avoid this problem, scheduler should use pod UID instead of "namespace/name" as the key in its "assume" cache.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig scheduling

**Comment by dixudx** [comment]
@bsalamat I am wondering whether `pod.UID` is always a non-empty string.
Shall we add a fallback strategy for this?

**Comment by vfreex** [comment]
Using UID sounds reasonable to me!
