### ISSUE TITLE
Node upgrades: provider agnosticism

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6096]
See issue #6079 as the roll-up for node upgrades.

While the basic mechanisms (#6099, #6088) will be built for the GCE and GKE providers, we want node upgrades to work for all supported cloud providers.

This issue really depends on the rewrite from Bash &rarr; Go by hooking into `pkg/cloudprovider` (#6095). After that is complete, ideally the addition of support for other cloud providers will be automatic if they implement the required interfaces. In reality, there may be more a bit more plumbing, refactoring, cloud-specific implementation, and testing required to close this issue with confidence.

**Comment by erictune** [comment]
@erictune

**Comment by roberthbailey** [comment]
This was tracking a feature improvement for kube-up, which is deprecated. Each installer does their own version of node upgrades, some of which are in-place.

/close
