### ISSUE TITLE
pod  frequent create and delete by daemonset controller when kube-apiserver enabled PodNodeSelector admission controll

### ISSUE THREAD

**Issue by lidajia** [kubernetes/kubernetes#60960]
/kind bug

Pod  frequent create and delete by daemonset controller when kube-apiserver enabled PodNodeSelector admission controll. When the daemonset's nodeSelector not cover the nodeSelector configured in PodNodeSelector adminssion controll, the schedule of daemonset pods will conflict with the PodNodeSelector adminssion controll. Is daemonset controller should cover this case?

**Comment by aveshagarwal** [comment]
This has been discussed before, and here is my comment: https://github.com/kubernetes/kubernetes/issues/51788#issuecomment-331986761 .

Please close this issue.

**Comment by aveshagarwal** [comment]
Also annotate your DS's namespace by setting scheduler.alpha.kubernetes.io/node-selector:"".
