### ISSUE TITLE
Node upgrades: in-place upgrades

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6099]
See issue #6079 as the roll-up for node upgrades.

This issue is to do an in-place upgrade of the kubelet and kube-proxy binaries while a node is running. Docker and the kernel/OS are not changed. This upgrade can only be performed if the requested new version of kubelet and kube-proxy are compatible with the existing Docker and kernel/OS version; see #4855 for more details on versioning.

We simply want to download the new (kube*) node binaries, stop the old ones, and start the new ones (#1573). That way, the pods continue to run, and we don't have to migrate any storage. Possible complications include:
- #3333 leftover state or configuration of the VM will cause unwanted side effects after the upgrade is complete
- the configuration of the node (environment variables, flags passed to kube_, something salt does) might change between kube_ versions
- when kube\* binaries are stopped, the master might think the pods are all gone, and schedule new copies of the pods elsewhere throughout the cluster

The following requirements follow:
- smart salt stanzas: idempotency, can run on a previously salted node
- must have an upgrade grace period where the pods are considered alive even if they cannot be health-checked by kubernetes

The tests for this feature are tracked in #7256.

References:
- #4855 cluster versioning
- #3333 lively debate about kubelet & kube-proxy upgrades, specifically in-place _vs_ fresh-node
- #1573 online kubelet upgrades; the original issue for this work item

**Comment by alex-mohr** [comment]
@fabioy may be starting to look at this

**Comment by davidopp** [comment]
#17393 is relevant

**Comment by ghodss** [comment]
We upgraded our kubelets from 1.0.1 to 1.1.3 today and when the new kubelet came up, it restarted all the pods on the server, which seems unnecessarily disruptive. Why does it do this? I ask because if you simply stop the kubelet then start it again without doing an upgrade, the pods are left untouched. Why specifically during an upgrade do the pods get kicked?

cc @lopopolo @erictune

**Comment by erictune** [comment]
Might be due to kubelet using docker labels differently?  @kubernetes/goog-node might know.

**Comment by gitfred** [comment]
Folks, are there any steps being taken towards online updates?

**Comment by davidopp** [comment]
Unfortunately there are many duplicate issues open on this topic, but I don't know which ones to close.
In any event, #17397 and #23104 are probably the most relevant at the moment.
Nobody is working on it but we know it's important. We're currently trying to find someone to do it.

**Comment by davidopp** [comment]
(To clarify: the "it" is in-place node upgrade. Whether it will guarantee to not kill running pods is TBD.)

**Comment by roberthbailey** [comment]
This is the cluster lifecycle backlog, but since no one is actively working on it I'm going to un-assign.

**Comment by roberthbailey** [comment]
This was tracking a feature improvement for kube-up, which is deprecated. Each installer does their own version of node upgrades, some of which are in-place. 

/close
