### ISSUE TITLE
Formally deprecate the gitRepo volume type

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#60999]
cc @kubernetes/sig-auth-feature-requests 
cc @kubernetes/sig-storage-feature-requests 

gitRepo stopped accepting new features a while ago https://github.com/kubernetes/kubernetes/issues/17676#issuecomment-228650586 and today this behavior can easily be achieved through an init container. The kubelet shelling out to git on the host can also be a security issue on un-trusted repos.

https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841

**Comment by tallclair** [comment]
xref: https://groups.google.com/forum/#!topic/kubernetes-announce/CTLXJ74cu8M

**Comment by tallclair** [comment]
What is the action item for 1.11 here? Just to announce the deprecation in the release notes?

Alternatively we could remove the gitRepo volume handling from the Kubelet, and instead inject an init container to setup the volume (e.g. https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841). Could this approach have backward compatability issues?
