### ISSUE TITLE
pull-kubernetes-e2e-gke and ci-kubernetes-e2e-gci-gke failing (e86a79dc0b9fe8a51016)

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#61009]
Both these job started failing at the same time.

Comparison of both repo and infra commits:
https://github.com/kubernetes/kubernetes/compare/c74c82645...d112ffc2e
https://github.com/kubernetes/test-infra/compare/8c7800b6d...8c9bca22f

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Kubernetes%20Dashboard%20should%20check%20that%20the%20kubernetes-dashboard%20instance%20is%20alive#e86a79dc0b9fe8a51016

The only PR there I'm not sure about is https://github.com/kubernetes/test-infra/pull/7170. @cjwagner thoughts?

cc: @kubernetes/sig-gcp-test-failures @kubernetes/sig-testing-test-failures

**Comment by cblecker** [comment]
also cc: @krzyzacy

**Comment by dims** [comment]
@cblecker is this different from https://github.com/kubernetes/kubernetes/issues/60767 ?

**Comment by BenTheElder** [comment]
I don't think it's https://github.com/kubernetes/test-infra/pull/7170, that was just as change to git + ssh checkout logic which shouldn't be used for these jobs. 

As per the #sig-release discussion I think you two are both right that the dashboard is off by default now, PRing test-infra config to enable it...

**Comment by BenTheElder** [comment]
PR jobs appear to be passing now after https://github.com/kubernetes/test-infra/pull/7217

**Comment by cblecker** [comment]
Looks like the CI job is clear too: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/23620

Thanks @BenTheElder !
