### ISSUE TITLE
Use of glog for logging is problematic

### ISSUE THREAD

**Issue by obeattie** [kubernetes/kubernetes#61006]
**FEATURE REQUEST**:

/kind feature

**What happened**:

Kubernetes uses [golang/glog](https://github.com/golang/glog) extensively for logging. While this is reasonable enough for the Kubernetes binaries, sizeable parts of the codebase are re-used as client libraries (eg. `k8s.io/client-go`). This presents several problems for users of the libraries:

* glog [registers a bunch of flags in an `init` function](https://github.com/golang/glog/blob/23def4e6c14b4da8ac2ed8007337bc5eb5007998/glog.go#L398-L411), and offers no programmatic way to configure its behaviour. It can be [surprising](https://github.com/heptio/contour/blob/d9e4883d318b0ed5e8fc0592a147f634994ac7f8/cmd/contour/contour.go#L40-L45) to users of the k8s libraries that they have to call `flag.Parse()`, and this is easy to get wrong (eg. coredns/coredns#1597).
* glog's default behaviour is to log to a file on disk. A user of a library wouldn't typically expect it to write files without explicitly configuring it to do so.
* Worse, if glog cannot create a file, it [calls `os.Exit`](https://github.com/golang/glog/blob/23def4e6c14b4da8ac2ed8007337bc5eb5007998/glog.go#L691). This can be very harmful, and since it's common to run containerised binaries with a read-only root filesystem, can be easy to trigger.
* glog doesn't perform any management of the files it writes, so without something like `logrotate` running (especially problematic in a container) the log files just accumulate.

I think we need to find a way to fix this: the use of glog makes working with the k8s client libraries very difficult. A [recent Twitter discussion on this topic](https://twitter.com/peterbourgon/status/972177627996831744) shows this is a widely-held concern.

**Comment by obeattie** [comment]
@kubernetes/sig-architecture-feature-requests

**Comment by obeattie** [comment]
Personal 2¢: while replacing glog completely with something else might be the best long-term solution, doing so seems like it would be a long road. Coming to a consensus on a replacement and rewriting all existing calls to glog to use that replacement doesn't seem like it will happen quickly.

The problems caused by this are quite harmful _now_, so I think it's pragmatic to mitigate those without replacing glog completely. It seems like that would involve something like:

1. Forking glog
2. Making it programmatically configurable
3. Making it log to stdout/stderr by default
4. Removing its flags, adding those as explicit k8s flags instead, and using them to configure the library

I'd be happy to take a go at this, but it's probably only worthwhile doing that if there's enough agreement that it would be an acceptable thing to do (a PR that changes the glog import path would benefit from merging pretty fast since it would get out of date very quickly.)

**Comment by errordeveloper** [comment]
@obeattie thanks for enumerating these issue in full, I agree with all of them and we should start doing something about it. I think most developers are partly aware of some of these issues, but I am not sure if anyone else has enumerated these issues as well as you did here.

**Comment by bboreham** [comment]
I agree glog should be fixed, forked or replaced.  
Note the glog README says "Feature requests will be ignored.", which points towards the latter two.

Interested in your view @thockin

**Comment by alexellis** [comment]
I was part of the initial [Twitter thread](https://twitter.com/peterbourgon/status/972177627996831744) - my main concerns are: the `init()` does too much and cannot be deferred.

A forked/updated glog should ideally not run `init()` or have an environmental variable that can be set to avoid it running `init()` until it's desirable - for instance how can you unit test this (you can't)?

The override should ideally not mandate the use of args/flags to configure logging.

To the point @thockin raised by his Go logging interface project (mentioned in the tweet thread) - there should be an interface available so that the underlying test framework/implementation can be abstracted away from the consuming code.

https://github.com/thockin/logr

**Comment by alexellis** [comment]
Related issue: https://github.com/coredns/coredns/issues/1597 (closed)

**Comment by alexellis** [comment]
@obeattie wdyt?

**Comment by alexellis** [comment]
Pinging some people who we've spoken to about this - @bboreham  @munnerz - @thockin had some ideas in the hallway at KubeCon CPH about how to approach this as a piecemeal solution gradually replacing glog with an interface implemented by glog for a non-harm change.

**Comment by bgrant0607** [comment]
Creating a more complete list of requirements and desirable properties would be useful.

**Comment by tallclair** [comment]
2 more problems with glog I'd like to add:

1. Logs are untestable (by unit tests). There is no good way to get at the log file, or intercept logs.
2. No way to direct logs to a specific file. As a result, a lot of our system addons log to stderr, and then use a shell to redirect the logs to a file. This is problematic for a whole bunch of reasons.

> Forking glog

+1. I think a sensible path forward would be:

1. Fork glog, address the immediate problems without changing the interface
2. (simultaneously) collect requirements & review existing log libraries to identify the library we want to migrate to
3. Reimplement our glog fork as an adapter to the new logging library
4. Gradually migrate log usage to the new library interface (or an alternative interface we design).

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by dims** [comment]
@tallclair @alexellis  @bboreham @munnerz @thockin @bgrant0607 Here's an experiment for forking glog into the k/k repo - https://github.com/kubernetes/kubernetes/pull/69333

**Comment by thockin** [comment]
I'd love to see us move to something like https://github.com/go-logr/logr (planned to rename to lager, maybe?) and I am willing to help strategize how.

Starting at leaf packages and working backwards, we should be able to replace the `glog` calls with methods on the abstract interface implemented in terms of glog.  This forces us to think through how to plumb it around into libraries and across interfaces.  As we get closer to main(), we can talk about switching the implementation to some other log lib, and callers can break their dependencies on literal glog.

**Comment by tallclair** [comment]
I guess there are 2 different approaches here with the same end goal:
1. (the approach in this PR) Adopt a new logging backend (library), and then gradually migrate logging calls to the new interface. By forking glog, it means we could flip the fork over to keep it's interface and flip the implementation over to the new library.
2. (@thockin's proposal) Gradually migrate logging calls to a new interface (still backed by glog), and then flip over the backend.

Some of the problems with our current logging approach are addressed with a new interface, while others are better addressed with a new backend. I guess which approach we take depends somewhat on which set of problems we're prioritizing.

**Comment by geekofalltrades** [comment]
Prometheus is also infected:
https://github.com/coreos/prometheus-operator/issues/1932
https://github.com/prometheus/prometheus/issues/4795

**Comment by wking** [comment]
> I'd love to see us move to something like https://github.com/go-logr/logr (planned to rename to lager, maybe?) and I am willing to help strategize how.

Also in this space is `https://github.com/go-log/log`, which aims for the simpler printf-style approach from [Dave's blog][1].  I'm definitely in favor of having a pluggable interface of some sort for this to enable client-go (and other library) consumers to plug in their own implementation, which may not be glog or a fork of glog).

[1]: https://dave.cheney.net/2015/11/05/lets-talk-about-logging
[2]: https://godoc.org/github.com/go-log/log#Logger
[3]: https://godoc.org/github.com/go-log/log#Logger

**Comment by dcbw** [comment]
klog PR is https://github.com/kubernetes/kubernetes/issues/70264

**Comment by dims** [comment]
Please see https://groups.google.com/d/msg/kubernetes-dev/7vnijOMhLS0/1oRiNtigBgAJ 

I'd love to see follow ups on what can be done better now that we have `klog`

/close
