### ISSUE TITLE
e2e test for hostport collision should not use port 80

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#61018]
The test

```
predicates.go: It("validates that there is no conflict between pods with same hostPort but different hostIP and protocol", func() {
```

uses port 80, which is often in use on clusters (in our case, masters have an ingress controller listening on 80).  The test should use something in the high range that is unlikely to conflict or use a smarter algorithm for finding a port to validate.

@kubernetes/sig-scheduling-bugs @aveshagarwal fails in openshift

**Comment by aveshagarwal** [comment]
@smarterclayton I am looking into it.

**Comment by aveshagarwal** [comment]
@smarterclayton I looked into the test and it seems that another option would be for the test to not use 127.0.0.1 to avoid such conflict with infra (or any other important) pods on 127.0.0.1. As the test is using 127.0.0.1 and 127.0.0.2, I think we could just use 127.0.0.2 and 127.0.0.3 instead.

**Comment by aveshagarwal** [comment]
so it seems there are following options we can use:

1. Use 127.0.0.2 and 127.0.0.3 instead of 127.0.0.1 and 127.0.0.2.
2. Manually pick some high random port number.
3. Use something like following to pick unused port:

```
net.Listen("tcp", "127.0.0.1:0")
```
and then extract random port from it.

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes/kubernetes/pull/61038 with option 1 as it seems safer than 2 to me. Let me know if there is any concern, or if we would want to go with 2 or 3 option or something else.

**Comment by aveshagarwal** [comment]
@derekwaynecarr
