### ISSUE TITLE
Coscheduling in Kubernetes

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#61012]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Motivation**

Kubernetes has become a popular solution for orchestrating containerized workloads; it has been largely successful in orchestrating serving and storage workloads, and, with native K8s support for Spark. Meanwhile, the community also try to run Machine Learning (ML) workloads on Kubernetes, e.g. [kubeflow/tf-operator](https://github.com/kubeflow/tf-operator); during the intergration with [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator), we identified **first** two requirements to the scheduler:

1. **coscheduling**: the Pods of the job will not start/create untill the job got eough resources for all of its Pods
2. **job group**: the framework need a group of jobs work together to run, e.g. driver and worker in Spark, master and workers in TensorFlow

/cc @bsalamat @vishh @jlewi @foxish @kubernetes/sig-scheduling-feature-requests

**Comment by k82cn** [comment]
There's the demo from [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator):

**gang-scheduling**: https://www.youtube.com/watch?v=TKhoWafrYvk
**job group**: (by task priority) https://www.youtube.com/watch?v=I_rPl72HzKE

Will append design doc for gang-scheduling in upstream before end of week :)

**Comment by resouer** [comment]
It's little bit confusing why opening this issue as long as it already works with kube-arbitrator?  😕

**Comment by k82cn** [comment]
We incubated kube-arbitrator because of the complexity of batch system, it's more smooth to upgrade feature by feature.

gang-scheduling is a common requirements from HPC (e.g. MPI) and ML (TF); It had been asked several times in kube-arbitrator, so I'd like to also handle it in upstream. The kube-arbitrator will align the interface/behaviour with this feature in upstream if necessary.

In kube-arbitrator, we also provide some other features, e.g. policy based resource sharing (DRF by default), preemption (on-going); I'll open related issues when they're 'hot' enough :)

**Comment by k82cn** [comment]
Some domes on what issue gang-scheduling are going to resolve, and what we had done in kube-arbitrator: [default scheduler](https://youtu.be/oQgEmoOyf_U) and [kube-batchd](https://youtu.be/hhwU7reNJDU)

**Comment by k82cn** [comment]
xref https://github.com/kubernetes/kubernetes/issues/14188 , https://github.com/kubernetes/kubernetes/issues/16845

**Comment by vishh** [comment]
+1 for handling gang scheduling independent of resource sharing. I can help shepherd it with @bsalamat. 
We should consider the overall lifecycle of Gangs of pods and not just creation. For example. what happens if one of the pods gets evicted in a gang and cannot get scheduled back again? 
I'd also like to stress on the importance of being user friendly. We cannot assume that there will be specialized Operators that will hide the complexity behind gang scheduling. 

cc @mindprince who is also looking into this problem.

**Comment by ConnorDoyle** [comment]
Volunteering myself to help with reviews

**Comment by bsalamat** [comment]
> For example. what happens if one of the pods gets evicted in a gang and cannot get scheduled back again?

This is one idea: gangs should specify the number of replicas and the minimum number of live replicas, let's call it `minReplicas`. The controller creates as many instances (Pods) as the number of replicas. Scheduler will not schedule any of the replicas until at least as many as `minReplicas` can be scheduled. The rest of the replicas are scheduled if there are free resources. When the number of running pods drops below `minReplicas`, the controller kills the remaining running replicas.

**Comment by hongchaodeng** [comment]
> That's great; I'm drafting the doc for this, not ready yet. I'll send the invitation to you for discussion, and then publish for community review when it's ready.

+1 for reviewing the design doc.

We have heavy use of gang scheduling and its variants -- large cluster size (10k+), and a number of bundles to be deployed in a fast way to save time and resources.
- https://www.nytimes.com/2017/11/10/business/alibaba-singles-day.html
- https://myslide.cn/slides/6376

My 2c:

For such a large cluster, the default k8s scheduler couldn't meet our scale. Thus, we have to write our own scheduler.

For locking multiple pods, if not using the [transaction model][transaction_model], then we would need to do reservation. If there is only one scheduler, we can lock reserved resources in scheduler cache. But for multi-scheduler case, we would need to implement complicated Transaction logic like locking the Pod as reserved in APIServer and GC. Initially, assuming one scheduler is fine. But we do need to consider multi-scheduler case for longer term.

> Scheduler will not schedule any of the replicas until at least as many as minReplicas can be scheduled. The rest of the replicas are scheduled if there are free resources.

The minReplica sounds a good idea. We have another solution that seems to solve similar problem but from the other way. We have a use case that is to relax/degrade requirements. For example, there might be affinity/exclusivity constraints on scheduling pods. But if there aren't enough resources to satisfy the entire group to be scheduled and relaxing some constraints could lead to successful schedule, those requirements could be "relaxed". This is similar to "Preferred". Let's talk more about this on the API in the design doc.

Thanks in advance and look forward to this feature!

[transaction_model]:https://github.com/kubeflow/tf-operator/issues/165#issuecomment-347426621

**Comment by resouer** [comment]
@hongchaodeng  Resource hoarding is tricky in multiple scheduler, considering the coming scheduler as framework work, we may want to focus on single scheduler for now.

One nits: any English version of the slides?

**Comment by hongchaodeng** [comment]
cc @mitake 
I know that you would be interested :)
Could you write down your use case here too?

**Comment by mitake** [comment]
Hi @hongchaodeng, thanks for ccing me :)

In our use case, the gang scheduling feature is required for executing distributed learning task of deep learning frameworks (e.g. TensorFlow or MXNet).

Such frameworks have two processes in the learning task: parameter server and worker. Basically, the parameter servers and workers which belong to a single learning task must be scheduled at once. If the learning task lacks one of the processes, the task cannot make progress (visual description can be found in page 7 - 10 of this slide: https://schd.ws/hosted_files/kccncna17/95/kc_cnc_na17_mitake.pdf).

This is our use case of the gang scheduling feature. Currently I'm working on integrating tf-operator and kube-arbitrator. kube-arbitrator seems to be promising but if it can be supported in the vanilla k8s, it will be very convenient :)

**Comment by hongchaodeng** [comment]
@bsalamat @k82cn @resouer 

It's mentioned in the sig-scheduling meeting there is already a design doc. Can anyone share it here and involve open discussion as early as possible?

**Comment by k82cn** [comment]
@hongchaodeng , here is the doc: https://docs.google.com/document/d/1AUwcvTtULNvow5M9e428FnlvINO1uQ7ojRoTGuTp4DA/edit?usp=sharing ; shared with sig-scheduling google group last week :)

**Comment by k82cn** [comment]
@mindprince , also have a prototype here: https://github.com/k82cn/kubernetes/commits/gang-scheduling-working , built it based on `PodSchedulingGroup` option; one concern for this option is performance to build pods' relationship by selector.

/cc @bsalamat @vishh 


Tested following case as demo:

**Nodes**: only one node with `8 cpus`

**Steps***:
1. Create a Deployment (`d-1`) with 4 replicas, 1 cpu per replica
1. Create PodSchedulingGroup (`psg-1`), `MinAvailabe` is 5, selector is (`app:d-2`)
1. Create a Deployment (`d-2`) with 5 replicas, 1 cpu per replica
1. Delete Deployment `d-1`

**Result**:
1. All Pods of Deployment `d-2` are pending at `step 3`
1. All Pods of Deployment `d-2` are running after `step 4`
