### ISSUE TITLE
KUBE_GIT_VERSION contains extraneous comma when building from git archive source.tgz

### ISSUE THREAD

**Issue by ravilr** [kubernetes/kubernetes#61029]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Download the kube release source artifact from https://dl.k8s.io/v1.9.3/kubernetes-src.tar.gz and do a build.  All the kube binaries have a extraneous comma in the version:
$ /usr/bin/kube-proxy --version
Kubernetes v1.9.3,

**What you expected to happen**:

kube binaries built from git archive source tgz to show the correct version without extra comma.

this was introduced in https://github.com/kubernetes/kubernetes/pull/55353
git attribute export-subst on https://github.com/kubernetes/kubernetes/blob/v1.9.3/hack/lib/version.sh#L48  creates a string format like ''HEAD -> release-1.9, tag: v1.9.3, origin/release-1.9' . so,  the regex capture should ignore ','  

@david-mcmahon @ixdy @lavalamp

**Comment by ixdy** [comment]
The issue is that our regex didn't handle the case where the tag isn't the last part of the string filled in by `$Format:%D$`:

https://github.com/kubernetes/kubernetes/blob/ba535d57f6e2eb338f6fbf121d6be2e6f9204136/hack/lib/version.sh#L45-L51

One the 1.9.3 source tarball linked, this looks like
```bash
https://github.com/kubernetes/kubernetes/blob/ba535d57f6e2eb338f6fbf121d6be2e6f9204136/hack/lib/version.sh#L45-L51
```

This should be a pretty easy fix - I don't think commas are allowed in semantic version strings.

/assign @ixdy @david-mcmahon

**Comment by ixdy** [comment]
This PR likely affects v1.10 as well. I have a fix out: https://github.com/kubernetes/kubernetes/pull/61068

**Comment by ixdy** [comment]
Confirmed: this affects v1.10.0-beta.0 (trying https://dl.k8s.io/v1.10.0-beta.0/kubernetes-src.tar.gz):
```console
$ hack/print-workspace-status.sh
KUBE_GIT_VERSION should be a valid Semantic Version
Please see more details here: https://semver.org
```

Though applying my fix from #61068 reveals a different bug:
```console
$ hack/print-workspace-status.sh | grep gitVersion
gitVersion v1.11.0-alpha.0
```

The issue then is that there are multiple tags matching that commit when it was built:
```bash
    # When a 'git archive' is exported, the 'HEAD -> release-1.10, tag: v1.11.0-alpha.0, tag: v1.10.0-beta.0, origin/master, origin/HEAD' below will look
    # something like 'HEAD -> release-1.8, tag: v1.8.3' where then 'tag: '          
    # can be extracted from it.                                                     
    if [[ 'HEAD -> release-1.10, tag: v1.11.0-alpha.0, tag: v1.10.0-beta.0, origin/master, origin/HEAD' =~ tag:\ (v[^ ,]+) ]]; then
     KUBE_GIT_VERSION="${BASH_REMATCH[1]}"                                          
    fi                                                                              
```

**Comment by ixdy** [comment]
disregard the second part of my comment above (at least for now); v1.10.0-beta.1 has a more reasonable string:
```bash
    # When a 'git archive' is exported, the 'HEAD -> release-1.10, tag: v1.10.0-beta.1, origin/release-1.10' below will look
    # something like 'HEAD -> release-1.8, tag: v1.8.3' where then 'tag: '          
    # can be extracted from it.                                                     
    if [[ 'HEAD -> release-1.10, tag: v1.10.0-beta.1, origin/release-1.10' =~ tag:\ (v[^ ]+) ]]; then                                                                                                              
     KUBE_GIT_VERSION="${BASH_REMATCH[1]}"                                          
    fi
```
(but it still demonstrates the original bug this issue mentions)

**Comment by tpepper** [comment]
@kubernetes/sig-release-bugs we need a sig lead to status/approved-for-milestone here

**Comment by krzyzacy** [comment]
/status approved-for-milestone
sure, good to be fixed :-)

**Comment by tpepper** [comment]
@kubernetes/sig-release-bugs aaaaaand priority increased and re-added to milestone....

**Comment by ixdy** [comment]
Master branch is fixed. Creating cherry-pick PRs now:
* 1.9: #61120
* 1.8: #61121
* 1.7: #61122

**Comment by ixdy** [comment]
Cherry pick PRs are in. Next patch release of each branch should be fixed.
/close
