### ISSUE TITLE
Controller-manager sees higher mem-usage when load test runs before density

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#61041]
I accidentally turned off our load test in PR https://github.com/kubernetes/kubernetes/pull/60973. But thanks to it, I observed this pattern in our controller-manager memory usage during density test:

![controller-maanger-load-density-variance](https://user-images.githubusercontent.com/4333971/37290872-ac62ef2a-260d-11e8-988e-b05d359744f4.png)

You can see the jump after run 11479 when I re-enabled load test. And all subsequent spikes are seen in runs when the density test was preceeded by load test. We were seeing similar issues in past, but IIRC it was for kube-proxies. My feeling is this is related to endpoints-controller processing backlog - but need to confirm.

@wojtek-t - Is it sth already observed in the past? Do we consider it WAI or should we try to fix it?

@kubernetes/sig-scalability-bugs

**Comment by shyamjvs** [comment]
So this is **also seen in the apiserver**:

![apiserver-mem-usage-load-density-variance](https://user-images.githubusercontent.com/4333971/37292174-9d5fe8cc-2610-11e8-9898-0b100e0c3e69.png)

**Comment by wojtek-t** [comment]
It hopefully shouldn't be endpoint controller. Note that we don't start the second test before all namespaces from the previous one are deleted. That means endpoint controller wouldn't be able to update endpoints object becuase of non-existing namespace.
I hope that we would observe the higher number of errors somewhere if that's the case.

**Comment by shyamjvs** [comment]
I looked into the apiserver logs, and can't find any calls that have 'load' mentioned in them after the first call which has 'density' mentioned in it. This could potentially mean that the memory usage is coming from watches that are not initiated by the e2e (i.e sth like kube-proxy or kubelet watches).

**Comment by shyamjvs** [comment]
I have one idea to check if it is sth around services. Let's disable them in our load test for the job and see.

**Comment by shyamjvs** [comment]
> It hopefully shouldn't be endpoint controller. Note that we don't start the second test before all namespaces from the previous one are deleted. That means endpoint controller wouldn't be able to update endpoints object becuase of non-existing namespace.

That's true. But IIUC it's still possible that endpoints-controller is using memory, for e.g to process watch events for endpoints updates (coming from load test deletion phase)?

**Comment by wojtek-t** [comment]
I don't think it's watch related.
Yes - CM may accumulate some memory, because it allocated a lot in the past. And without memory-pressure not everything might have been cleared yet.

I don't think we should spent too much time on it now.

**Comment by shyamjvs** [comment]
Makes sense.

> I don't think we should spent too much time on it now.

Sure... But this is just taking very small time while I'm running bisection for the pod-startup regression in the background :)

**Comment by jberkus** [comment]
@shyamjvs, @wojtek-t does this look more like a problem with the test, or does this look like a real user-affecting performance problem related to the other performance issues?

**Comment by shyamjvs** [comment]
This needs more digging, but AFAIU it's not a regression and we've been seeing it for a while already I think.
Wrt users this may not be much of a problem, but I'd want to hear out @wojtek-t on this.

**Comment by shyamjvs** [comment]
> related to the other performance issues?

By "other performance issues" if you mean the recent ones that I've been hunting down (https://github.com/kubernetes/kubernetes/issues/60500, https://github.com/kubernetes/kubernetes/issues/60589), then I don't think so. Not 100% sure - but I believe they're different.
