### ISSUE TITLE
HostPath mounts failing with "Path is not a shared or slave mount"

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#61058]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After upgrading from v1.9.2 -> v1.10.0-beta.2, containers using hostpath mounts are failing with:
```
        exitCode: 128
        finishedAt: 2018-03-12T19:25:03Z
        message: 'linux mounts: Path /opt/kubelet/dev is mounted on / but it is not
          a shared or slave mount.'
        reason: ContainerCannotRun
        startedAt: 2018-03-12T19:25:03Z
```

The message `linux mounts: Path /opt/kubelet/dev is mounted on / but it is not a shared or slave mount` seems like it's from the docker daemon, but the docker daemon was not updated during the upgrade so I had assumed a behaviour in the kubelet had changed that would cause this. 

**What you expected to happen**:
Pod should be running as usual, but it fails with `RunContainerError`. 

**How to reproduce it (as minimally and precisely as possible)**:
Run Kubernetes cluster using host path mount. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.2", GitCommit:"63dad40a0391b7af32c34fdbf41fa199c3b247ad", GitTreeState:"clean", BuildDate:"2018-03-07T20:30:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by gnufied** [comment]
Can you post the pod specs?

**Comment by andrewsykim** [comment]
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-03-13T01:18:38Z
  generateName: nginx-deployment-759c777d5f-
  labels:
    app: nginx
    pod-template-hash: "3157333819"
  name: nginx-deployment-759c777d5f-95jt4
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-deployment-759c777d5f
    uid: 756f6333-265c-11e8-9c07-46e1b2da1c8d
  resourceVersion: "27220358"
  selfLink: /api/v1/namespaces/default/pods/nginx-deployment-759c777d5f-95jt4
  uid: 75726e0e-265c-11e8-9c07-46e1b2da1c8d
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log/dev/
      name: hostdevlog
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-5vjxh
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: <REDACTED>
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /opt/kubelet/dev
      type: ""
    name: hostdevlog
  - name: default-token-5vjxh
    secret:
      defaultMode: 420
      secretName: default-token-5vjxh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T01:18:38Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T01:18:38Z
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T01:18:38Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bfca0e763ed34c7894bd8ec5ba9ef92ecbb1db0d7ad8a371595b0c0afa99224d
    image: nginx:1.7.9
    imageID: docker-pullable://nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
    lastState:
      terminated:
        containerID: docker://bfca0e763ed34c7894bd8ec5ba9ef92ecbb1db0d7ad8a371595b0c0afa99224d
        exitCode: 128
        finishedAt: 2018-03-13T01:18:45Z
        message: 'linux mounts: Path /opt/kubelet/dev is mounted on / but it is not
          a shared or slave mount.'
        reason: ContainerCannotRun
        startedAt: 2018-03-13T01:18:45Z
    name: nginx
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'failed to start container "bfca0e763ed34c7894bd8ec5ba9ef92ecbb1db0d7ad8a371595b0c0afa99224d":
          Error response from daemon: linux mounts: Path /opt/kubelet/dev is mounted
          on / but it is not a shared or slave mount.'
        reason: RunContainerError
  hostIP: 10.124.80.204
  phase: Running
  podIP: 172.17.92.9
  qosClass: BestEffort
  startTime: 2018-03-13T01:18:38Z


```

**Comment by andrewsykim** [comment]
Disabling the MountPropagation feature fixes the issue

**Comment by andrewsykim** [comment]
Here's the part of docker that seems to be doing the check: https://github.com/moby/moby/blob/master/daemon/oci_linux.go#L454-L465

**Comment by andrewsykim** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
The error means that either docker sees has the mount where `/opt/kubelet/dev` resides (is it `/`?) as not (r)shared. rshared should be the default mount propagation for all mounts when systemd is the init.

What docker version do you use? What Ubuntu version? Did you do any modifications to mount propagation on the host? Please post /proc/1/mountinfo (to see what the host/systemd thinks) and /proc/<pid of docker daemon>/mountinfo (to see what docker thinks).

**Comment by andrewsykim** [comment]
This is on docker v1.12.6. `/opt/kubelet/dev` is on the `/` mount. I've been using that host path for quite a while so it's likely that its mount propagation mode was not changed when I upgraded versions. I am also not using systemd for init.

**Comment by jberkus** [comment]
@gnufied @jsafrane @dchen1107 @derekwaynecarr @saad-ali @childsb 

Should this bug be a blocker for 1.10?

**Comment by andrewsykim** [comment]
`/` mount from `/proc/self/mountinfo`
```
25 0 253:1 / / rw,noatime - ext4 /dev/vda1 rw,errors=remount-ro,data=ordered
```

lsblk
```
$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0    10G  0 disk
sdb       8:16   0    10G  0 disk
vda     253:0    0   320G  0 disk
├─vda1  253:1    0   320G  0 part /
└─vda15 253:15   0     1M  0 part
```

**Comment by andrewsykim** [comment]
btw, this is on Ubuntu 14.04 (not using systemd)

**Comment by jsafrane** [comment]
Heh, good old Ubuntu... Kubernetes expects that it runs with `/` (or whatever holds the hostpaths that you want to use in pods) with rshared mount propagation. systemd does that during boot automatically, on other distros you need to add a new service or add a command to Kubernetes init script before running Docker:

```
mount --make-rshared /
```

This should be enough for Docker to work.

I hope it's documented somewhere when 1.10 ships.

**Comment by jsafrane** [comment]
@jberkus, IMO, it's not a blocker.

**Comment by andrewsykim** [comment]
Thanks @jsafrane for the update, it should definitely be included in the `Action Required` section of the CHANGELOG

**Comment by andrewsykim** [comment]
https://github.com/kubernetes/kubernetes/pull/61126 PTAL

**Comment by jsafrane** [comment]
I updated release notes draft with a note in "Before Upgrading" section.

**Comment by fabiand** [comment]
Can this be fixed on the Kubernetes side? Or will it always require a manual workaround?

**Comment by jsafrane** [comment]
@fabiand, I gave up and changed the default to "private" in master and I am waiting for approvals for 1.10.x backport, see https://github.com/kubernetes/kubernetes/pull/62633

**Comment by andrewsykim** [comment]
@jsafrane does that mean mount propagation will work as expected (with CSI) for older distros like ubuntu 14 that aren't on systemd?

**Comment by palladius** [comment]
I have the same problem on Mac (works like a charm on Ubuntu).

$ docker -v
Docker version 20.10.2, build 2291f61

ricc@macbookpro:~/prometheus-node-exporter$🐼  docker run -it   --net="host"   --pid="host"   -v "/:/host:ro,rslave"   prom/node-exporter:latest   --path.rootfs=/host 
docker: Error response from daemon: path / is mounted on / but it is not a shared or slave mount.
ERRO[0000] error waiting for container: context canceled

**Comment by Omar2788** [comment]
use :
mount --make-rshared /

**Comment by tyza66** [comment]
<img width="989" height="384" alt="Image" src="https://github.com/user-attachments/assets/8d4effb6-1ed1-4d90-b883-59f9a525d810" />

我是在OpenHarmony上遇到的 （Linux指令不全且BusyBox无法补齐缺少的一些东西）

我也遇到了

使用挂载 软链接 甚至安全工具socat制作一个孪生串口抽象文件（伪终端）

仍无法解决

**Comment by tyza66** [comment]
如果mount无法给予挂载标识符shared （或者linux指令不全的话）
条件允许下

使用privileged:true
这样会全局挂载，相当于所有设备都挂载进容器
已验证可用

<img width="566" height="216" alt="Image" src="https://github.com/user-attachments/assets/819a472c-e9c7-4318-90d4-b9c062c36734" />

**Comment by tyza66** [comment]
Final fix:
https://github.com/containerd/containerd/pull/12373
https://github.com/moby/moby/pull/51193

**Comment by tyza66** [comment]
Final fix:
https://github.com/containerd/containerd/pull/12373
https://github.com/moby/moby/pull/51193
