### ISSUE TITLE
eviction-{hard,soft} stops working till kubelet restarted when using devicemapper for imagefs

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#61062]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When a kubelet is configured to have eviction-hard and eviction-soft, I have seen it **twice** now that imagesfs is more than 90% utilized and started generating errors, but eviction or garbage does not kick in till kubelet is restarted.

The kubelet is configured with this eviction related arguments
```
--eviction-hard=imagefs.available<10%,memory.available<500Mi,nodefs.available<5%,nodefs.inodesFree<5% --eviction-soft=imagefs.available<30%,nodefs.available<10% --eviction-soft-grace-period=imagefs.available=2m,nodefs.available=2m --eviction-max-pod-grace-period=600
```

In the most recent example, this is the state of the system be found in

```
# lvs
  LV                                                                 VG      Attr       LSize   Pool             Origin Data%  Meta%  Move Log Cpy%Sync Convert
  images                                                             docker  twi-aotz-- 120.00g                         91.13  61.06                           
```

And there were no sign of eviction in syslog.

After `systemctl restart kubelet`, then this started to be logged

```
Mar 12 16:24:39 4zb0cx1 kubelet: W0312 16:24:39.987590   20880 eviction_manager.go:332] eviction manager: attempting to reclaim imagefs
Mar 12 16:24:39 4zb0cx1 kubelet: I0312 16:24:39.987629   20880 helpers.go:1070] eviction manager: attempting to delete unused containers
Mar 12 16:24:40 4zb0cx1 kubelet: I0312 16:24:40.127526   20880 helpers.go:1080] eviction manager: attempting to delete unused images
Mar 12 16:24:41 4zb0cx1 kubelet: W0312 16:24:41.371115   20880 eviction_manager.go:142] Failed to admit pod <pod name>) - node has conditions: [DiskPressure]
```

**What you expected to happen**:

Eviction happens when the imagefs utilization reaches 70% and 10%.

**How to reproduce it (as minimally and precisely as possible)**:

Don't have a way to reproduce it yet.

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: baremetal servers
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core) 
- Kernel (e.g. `uname -a`): 4.14.15-1.el7.elrepo.x86_64
- Install tools: custom using ansible
- Others:

**Comment by phsiao** [comment]
Found another node in this state, collecting information that I can think of.

```
# curl localhost:10255/stats/summary
:
   "runtime": {
    "imageFs": {
     "time": "2018-03-12T20:51:43Z",
     "availableBytes": 41150672896,
     "capacityBytes": 48106139648,
     "usedBytes": 164744368216,
     "inodesFree": 23363937,
     "inodes": 23500800,
     "inodesUsed": 136863
    }
:
```

```
# lvs
  LV                                    VG      Attr       LSize   Pool             Origin Data%  Meta%  Move Log Cpy%Sync Convert
  images                                docker  twi-aotz-- 120.00g                         84.73  55.77                          
```

```
# docker info
Containers: 46
 Running: 36
 Paused: 0
 Stopped: 10
Images: 154
Server Version: 17.12.1-ce
Storage Driver: devicemapper
 Pool Name: docker-images
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data Space Used: 109.2GB
 Data Space Total: 128.8GB
 Data Space Available: 19.68GB
 Metadata Space Used: 149.7MB
 Metadata Space Total: 268.4MB
 Metadata Space Available: 118.7MB
 Thin Pool Minimum Free Space: 12.88GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.13-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.9GiB
Name: 3ck8xv1
ID: O7JP:3BFB:UXAF:52AG:A42Y:2THR:HE2O:YW6O:WSWL:A7SG:56B2:R4OR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

**Comment by phsiao** [comment]
Looks similar to #44189.

**Comment by phsiao** [comment]
cc @derekwaynecarr devicemapper-related issue

**Comment by StephenSorriaux** [comment]
Encountered same problem today with the following environment:

Environment:

Kubernetes version (use kubectl version): 1.9.6
Cloud provider or hardware configuration: cloud AWS
OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
Kernel (e.g. uname -a): 3.10.0-693.17.1.el7.x86_64
Install tools: custom using ansible

**Comment by gtie** [comment]
I'm running into this issue as well, though restarting kubelet does nothing for me. As seen in the kubelet summary output, the imageFs usage numbers do not add up (namely the usage size is 3x the capacity size). The incorrect numbers would be a reason for the ImageGC code not to run at all (with or without kubelet restart) - that's what I'm observing on my side.

Kubelet logs show an error like:
`Error response from daemon: devmapper: Thin Pool has 37100 free data blocks which is less than minimum required 40876 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior`

When that happens, it can be quite disrupting as new containers get scheduled on the affected node, but docker can't start them. The node is still reported as healthy, and continues to accept new pods.

My environment:

> K8s: 1.10.3
> Cloud: AWS
> OS: CentOS Linux release 7.4.1708
> Kernel: 3.10.0-693.21.1.el7.x86_64
> Runtime: Docker 1.13.1
