### ISSUE TITLE
Node upgrades: investigate putting the mechanism on the master

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#6106]
See issue #6079 as the roll-up for node upgrades.

The basic node upgrade mechanisms (#6099, #6088) will be out-of-band, e.g. run on a user's desktop. We might instead want to have the master run the node upgrade process. In this case, the user would just tell the master to upgrade the cluster and it would coordinate the upgrade procedure for all applicable nodes.

This issue is to investigate the pros and cons of doing so and either (a) close this issue with a description of why it'd be better to keep out-of-band, or (b) implement transferring the mechanism to the master.

Like other `area/upgrade` issues, this probably should be addressed only after the P1 issues are completed, and the node upgrade mechanism is written in Go (#6095).

**Comment by erictune** [comment]
@erictune

**Comment by roberthbailey** [comment]
I'm going to close this and move the discussion to https://github.com/kubernetes/kubernetes/issues/7459, where @lavalamp proposes a cluster controller that runs on the master and drives node upgrades.
