### ISSUE TITLE
[gci-gce-ipvs failed]service loadbalancer source range don't work in ipvs proxy mode

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#61090]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Service loadbalancer source range don't work in ipvs proxy mode.
Which result in gci-gce-ipvs CI failed.
http://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ipvs

**How to reproduce it (as minimally and precisely as possible)**:
In gce environment.
1. Create a service with backend.
2. Change service type to `LoadBalancer`
3. Add service `loadBalancerSourceRanges`
4. wait util service external IP is specified.
5. Access the service from pod inside `loadBalancerSourceRanges` and pod out of the  `loadBalancerSourceRanges`.

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: gce
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: cluster/kube-up.sh
- Others:

**Comment by rramkumar1** [comment]
@Lion-Wei The test seems to be flaky now. Can you take a look please?

**Comment by Lion-Wei** [comment]
I don't know why, but I think this flaky have the similiar reason with other normal service-test cases, like
```
Services should be able to up and down services
Services should create endpoints for unready pods
```

Those flaky are pretty annoying, problem is, I have run those cases in my own environment many times, never fail... : (

But still, I'll do my best to find the reason.
