### ISSUE TITLE
tolerations add to replicationController not working

### ISSUE THREAD

**Issue by tianyaning** [kubernetes/kubernetes#61092]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
scene 1：
I try to add tolerations to replicationController before the replicationController is created.
It works well, and after the replicationController created,  both itself and it's pods have the same tolerations. 
But when i scale the replicationController, something strange happened: The replicationController have no tolerations and the new pod also have no tolerations.

scene 2：
I try to add tolerations to a replicationController which is already exists. 
When i scale the replicationController, the replicationController have no tolerations and the new pod also have no tolerations.

I always thought the tolerations in replicationController will never gone. Am I wrong?
or the kubernetes version does not support？

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.6.6

**Comment by kow3ns** [comment]
My first though would be that round tripping the resource through this client version is stripping the tolerations.
