### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce failing with ERROR: (gcloud.compute.instances.delete) Could not fetch resource

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#61112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
This looks like a problem with the automated testing.  See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60065/pull-kubernetes-kubemark-e2e-gce/81204?log#log for an example.  Note the entry
```
W0313 10:25:15.700] 2018/03/13 10:25:15 process.go:150: Running: ./test/kubemark/stop-kubemark.sh
W0313 10:25:17.378] ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
W0313 10:25:17.378]  - The resource 'projects/k8s-jkns-pr-kubemark/zones/us-central1-f/instances/e2e-81204-kubemark-master' was not found
```
and others like it.

**What you expected to happen**:
I expected the GCE resource wrangling to not fail.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): release-1.8
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing-bugs

**Comment by MikeSpreitzer** [comment]
This test seems to be consistently failing.  See https://k8s-gubernator.appspot.com/pr/60065

**Comment by BenTheElder** [comment]
The actual failure is:
W0313 10:28:48.391] 2018/03/13 10:28:48 main.go:273: Flag parse failed:
invalid argument "--check-version-skew=false" for "-v, --v" flag:
strconv.Atoi: parsing "--check-version-skew=false": invalid syntax

This is a known issue, there's a cherry pick out to fix. Part of the
kubemark script is updating kubetest itself (!) and calling it incorrectly.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/60940
