### ISSUE TITLE
Volume manager should not mount the volumes for pods rejected by kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#61137]
This came up when I was checking the kubelet logs for #60763

Kubelet admits or rejects pods assigned to the node in its sync loop, and would not start syncing a pod until it's admitted. In the meantime, volume manager works independently to mount volumes for the assigned pods, as long as they are not in a terminated state. This causes issues where kubelet already rejected (or is about to reject) a pod, but their volumes are mounted. The volume manager should wait and check the results of the admission before attempting to mount.

/cc @kubernetes/sig-storage-bugs 
/cc @kubernetes/sig-node-bugs

**Comment by gnufied** [comment]
@yujuhong volume manager uses kubelet's pod manager as source for picking pods that needs volumes. Once a pod gets rejected by kubelet, shouldn't it be removed from pod manager? and in that case - next reconcilliation loop of volume manager should remove the pod from desired state of world.

What do you suggest should be source of truth for volume manager to pick pods from?

**Comment by gnufied** [comment]
This is still a valid bug.

**Comment by matthyx** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Please re-open this bug once you have provided more information.

/triage needs-information
/close
