### ISSUE TITLE
kubemark presubmit should not use e2e.go and then rebuild kubetest

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#61141]
as a follow up issue for https://github.com/kubernetes/kubernetes/issues/60870

now in older branches (1.8, and 1.7) it gets error while rebuilding stale kubetest from e2e.go
```
W0313 22:54:40.441] 2018/03/13 22:54:40 e2e.go:151: The kubetest binary is older than 24h0m0s.
W0313 22:54:40.441] 2018/03/13 22:54:40 e2e.go:156: Updating kubetest binary...
W0313 22:55:17.326] # k8s.io/test-infra/vendor/github.com/json-iterator/go
W0313 22:55:17.326] ../../test-infra/vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map
W0313 22:55:27.407] 2018/03/13 22:55:27 e2e.go:75: err: go get -u k8s.io/test-infra/kubetest: exit status 2
W0313 22:55:27.407] exit status 1
```
which is caused by the go version difference between 1.8 and master

I'll try to move those logic to kubetest to unblock 1.8 branch

/kind bug
/priority failing-test
/sig testing
/sig scalability
/assign

cc @cblecker @jpbetz @BenTheElder @shyamjvs

**Comment by liggitt** [comment]
and 1.7

**Comment by krzyzacy** [comment]
well.. looks like I need to untangle all the bash in that script.. that might take a bit

in the meantime sent https://github.com/kubernetes/test-infra/pull/7289 as a short-term workaround, I'll leave this issue open until the real fix is in.

**Comment by MikeSpreitzer** [comment]
I am still getting `../../test-infra/vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map` from pull-kubernetes-kubemark-e2e-gce.  For example, see the tests of #60802

**Comment by krzyzacy** [comment]
@MikeSpreitzer odd.. I'll try to push https://github.com/kubernetes/test-infra/pull/7267 through asap

**Comment by krzyzacy** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/7267
