### ISSUE TITLE
kubelet /stats reports 500 when a container is not found

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#6115]
There seems to be a delay between the container creation and the cadvisor being notified of such a container change (through inotify) and registers the container. This leads to a case where cadvisor might report the container not found while it actually exists. Because [docker is able to find the container](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2029), kubelet returns the raw error (instead of `ErrContainerNotFound`).

```
I0327 22:13:10.418373   30839 event.go:138] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"bar-controller-wbo6m", UID:"63459b0e-d4ce-11e4-98a4-42010af04d55", APIVersion:"v1beta1", ResourceVersion:"110606", FieldPath:"spec.containers{bar}"}): reason: 'created' Created with docker id d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2
I0327 22:13:12.153278   30839 event.go:138] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"bar-controller-wbo6m", UID:"63459b0e-d4ce-11e4-98a4-42010af04d55", APIVersion:"v1beta1", ResourceVersion:"110606", FieldPath:"spec.containers{bar}"}): reason: 'started' Started with docker id d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2
I0327 22:13:20.911539   30839 server.go:140] HTTP InternalServerError: Internal Error: unable to find Docker container "d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2"
(SKIPPED THE BACKTRACE)
I0327 22:13:28.415407   30839 factory.go:71] Using factory "docker" for container "/docker/d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2"
I0327 22:13:28.426950   30839 manager.go:659] Added container: "/docker/d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2" (aliases: [k8s_bar.b80fe20f_bar-controller-wbo6m_default_63459b0e-d4ce-11e4-98a4-42010af04d55_0844342d d97df25e70f82640924c01e9a60ed5b18b26e154660321ecd9d4bbb2808c0ee2], namespace: "docker")
```

This happened when kubelet was trying to start 10~20 containers in a short period of time on a regular node created by e2e. Since it was a relative high load, this scenario should rarely happen. That said, it'd still be nice if Kubelet can report ContainerNotFound instead of exposing the 500 errors.

**Comment by yujuhong** [comment]
The umbrella issue for stats api is #4489

**Comment by vmarmol** [comment]
That's certainly not a race we expect to lose, but the behavior you mention should be what we do.
