### ISSUE TITLE
stuck at Container creating

### ISSUE THREAD

**Issue by bilalAchahbar** [kubernetes/kubernetes#61163]
I have an weave network plugin.

inside my folder /etc/cni/net.d there is a 10-weave.conf

> {
>     "name": "weave",
>     "type": "weave-net",
>     "hairpinMode": true
> }

My weave pods are running and the dns pod is also running
But when i want to run a pod like a simple nginx  wich will pull an nginx image 
The pod stuck at container creating , describe pod  gives me the error , failed create pod sandbox.

When i run journalctl -u kubelet i get this error
`
 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d`

is my network plugin not good configured ?

i used this command to configure my weave network 
kubectl apply -f https://git.io/weave-kube-1.6
After this won't work i also tried this command
kubectl apply -f “https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d ‘\n’)”

I even tried flannel and that gives me the same error. 
The system i am setting kubernetes on is a raspberry pi.
I am trying to build a raspberry pi cluster with 3 nodes and 1 master with kubernetes

**Comment by Lion-Wei** [comment]
Not sure have you solved this problem already.
But before network plugin enabled, kubelet always have this log. I think you need to paste the pod describe result/kubelet this pod related log, to solve this problem.

**Comment by chenchix** [comment]
Same error here, using 1.11 and a master in a PC (x86_64) and workers in arm64 board.

Any update?

**Comment by pvrbharg** [comment]
I do not have this issue when I tried on most current release level on my RHEL 7.5 instance on intel - I used 1.11.2 release with coredns plugin. Thanks.
