### ISSUE TITLE
Jobs and pods are never deleted with a foreground propagation policy

### ISSUE THREAD

**Issue by Overv** [kubernetes/kubernetes#61175]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I created a job and deleted it with the foreground propagation policy, but it is never actually deleted. Same issue with a pod. It will be "Terminating" forever.

**What you expected to happen**:

I expected the pod/job to disappear within a few seconds/minutes and not still be there after hours.

**How to reproduce it (as minimally and precisely as possible)**:

Create a job or pod, issue a DELETE with `'{"kind": "DeleteOptions", "apiVersion": "v1", "propagationPolicy":"Foreground"}'` and it will never be deleted until you change the propagation policy to `Background`. Even when no pods or other dependents are associated with it anymore. Same with just a single pod, it will be "Terminating" forever until you delete it with background propagation.

**Anything else we need to know?**: No.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.9
- Cloud provider or hardware configuration: Dedicated machine
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`): -
- Install tools: Rancher Kubernetes Engine
- Others:

**Comment by jennybuckley** [comment]
Are there any logs for the garbage collector in the controller manager log?

**Comment by Overv** [comment]
Invalid bug report, this was caused by duplicate containers of kubernetes services running in my cluster.
