### ISSUE TITLE
Removing Docker k8s images from local machine

### ISSUE THREAD

**Issue by marcinlesek** [kubernetes/kubernetes#61173]
/sig scalability

Hello, 

I had a problem, maybe easy but I couldn't handle this. How to remove all k8s containers and images from local machine?

```
gcr.io/google_containers/k8s-dns-sidecar-amd64         Up 36 minutes       k8s_sidecar_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_116
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64   Up 36 minutes       k8s_dnsmasq_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_116
gcr.io/google_containers/k8s-dns-kube-dns-amd64        Up 36 minutes       k8s_kubedns_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_116
gcr.io/google_containers/kubernetes-dashboard-amd64    Up 36 minutes       k8s_kubernetes-dashboard_kubernetes-dashboard-xpg2v_kube-system_fd403866-c63c-11e7-b3c8-28d24484a79b_222
gcr.io/google-containers/kube-addon-manager            Up 36 minutes       k8s_kube-addon-manager_kube-addon-manager-lenovo-e540_kube-system_9831e93c3188555873fdb49f43198eef_186
gcr.io/google_containers/pause-amd64:3.0               Up 36 minutes       k8s_POD_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_116
gcr.io/google_containers/pause-amd64:3.0               Up 36 minutes       k8s_POD_kube-addon-manager-lenovo-e540_kube-system_9831e93c3188555873fdb49f43198eef_186
gcr.io/google_containers/pause-amd64:3.0               Up 36 minutes       k8s_POD_kubernetes-dashboard-xpg2v_kube-system_fd403866-c63c-11e7-b3c8-28d24484a79b_186
```
It's unpossible to stop them (they restart always), also to remove them by `rm` and `rmi`. I was looking for it in documentations, stack etc. but with no effect.

Best regards,
Marcin

**Comment by dims** [comment]
@marcinlesek check if kubelet is running, if it is stop that first and then cleanup the containers and images.

**Comment by marcinlesek** [comment]
@dims Could you elaborate more about how to check/stop it?

**Comment by dims** [comment]
@marcinlesek are you on ubuntu? how did you install kubelet? (did you use `apt-get` to install kubelet for example, if so then `systemctl stop kubelet` would stop kubelet). do a `ps -ef | grep kubelet` to see if it is running first.

**Comment by marcinlesek** [comment]
Yes, on Ubuntu 16.04. Hmm, let check:
```
$ ps ax | grep kubelet
17234 pts/18   S+     0:00 grep --color=auto kubelet

$ kill -KILL 17234
bash: kill: (17234) - No such process

systemctl stop kubelet
Failed to stop kubelet.service: Unit kubelet.service not loaded.
```

But know still I'm couldn't to stop this cointainers and remove all. Any ideas?

**Comment by dims** [comment]
try this a few times ...

```
docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -q -a)
```

**Comment by marcinlesek** [comment]
This commands will remove all containers and images. I run this:
```
$ docker rm -f $(docker ps -a -q --filter "name=k8s")
```
and here what we have now:
```
IMAGE                                                  STATUS              NAMES
gcr.io/google_containers/k8s-dns-sidecar-amd64         Up 37 seconds       k8s_sidecar_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_0
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64   Up 37 seconds       k8s_dnsmasq_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_0
gcr.io/google_containers/kubernetes-dashboard-amd64    Up 38 seconds       k8s_kubernetes-dashboard_kubernetes-dashboard-xpg2v_kube-system_fd403866-c63c-11e7-b3c8-28d24484a79b_0
gcr.io/google_containers/k8s-dns-kube-dns-amd64        Up 38 seconds       k8s_kubedns_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_0
gcr.io/google-containers/kube-addon-manager            Up 39 seconds       k8s_kube-addon-manager_kube-addon-manager-lenovo-e540_kube-system_9831e93c3188555873fdb49f43198eef_0
gcr.io/google_containers/pause-amd64:3.0               Up 39 seconds       k8s_POD_kube-addon-manager-lenovo-e540_kube-system_9831e93c3188555873fdb49f43198eef_0
gcr.io/google_containers/pause-amd64:3.0               Up 39 seconds       k8s_POD_kube-dns-6fc954457d-mwgvb_kube-system_fd5ebaed-c63c-11e7-b3c8-28d24484a79b_0
gcr.io/google_containers/pause-amd64:3.0               Up 39 seconds       k8s_POD_kubernetes-dashboard-xpg2v_kube-system_fd403866-c63c-11e7-b3c8-28d24484a79b_0
```
Containers restarted itselfs. I said it before, that it's not as easy as normal container. :sweat_smile: I'm trapped with them now.

**Comment by mlmhl** [comment]
@marcinlesek 
Maybe you should remove according pods first, use `kubectl get po -n=kube-system` to find all pods, and then use `kubectl delete po <pod-name> -n=kube-system` to delete them.

**Comment by marcinlesek** [comment]
@mlmhl Thanks for the response. As background, I want to underline that I was checking kubernetes half year ago and I didn't remember everything from this tools.

```
$ kubectl get po -n=kube-system
Unable to connect to the server: dial tcp 192.168.99.100:8443: getsockopt: network is unreachable
```
Some advice how to start these pods?

**Comment by marcinlesek** [comment]
/kind bug

and a little kind update. :)

**Comment by marcinlesek** [comment]
**Solved here** https://stackoverflow.com/a/49371453/9484660

You need to stop and disable localkube service:

```
$ systemctl disable localkube.service
$ systemctl stop localkube.service
```
After that you're able to stop and remove containers. 

If you will get

`Error response from daemon: No such image: gcr.io/...` 

after using `docker rmi`, you should use

`$ docker system prune -a` 

instead, to additionally remove any stopped containers and all unused images (not just dangling images).

Best,
M.

**Comment by francoj22** [comment]
found the soluction on windows by going to the docker icon and then in kubernetes options 
click on stop local cluster and then execute "docker rmi -f $(docker images -a -q)"

**Comment by charlchad** [comment]
You need to:
1. In Docker Desktop for Mac - Kubernetes **Disable local cluster ** 
2. ```docker rm -f $(docker ps -a -q)```
3. ```docker rmi -f $(docker images -q -a)```

**Comment by kyopark2014** [comment]
I have a same situation in ubuntu since the process related to k8s is getting restart once it is stopped by "docker kill" manually.
Try this. 
It worked in my case.
1) stop kubelet
 $ systemctl stop kubelet
2) docker kill [containers]
3) docker rmi [images]

**Comment by sourav1985** [comment]
Please suggest any solution to be used on windows system
