### ISSUE TITLE
Kubernetes fails obscurely with two network interfaces

### ISSUE THREAD

**Issue by egrimley** [kubernetes/kubernetes#61170]
/kind bug
/sig Node bugs

I would probably have reopened #44702 if that were an option.

If I create a two-node cluster in which each node has two network interfaces and the nodes communicate via their second network interface then everything seems to work until I try `kubectl logs`. Eventually I realised that `kubectl get pods --all-namespaces -o wide` is showing the wrong IP addresses, as described under #44702, though in my case both nodes are getting the wrong IP address.

There is a work-around, but it's tedious. On Ubuntu, on each node:

* Edit `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` and add the line `KUBELET_EXTRA_ARGS=--node-ip=...` replacing `...` with the IP address that should be used for connecting to that node from another node.

* `systemctl daemon-reload`

* `systemctl restart kubelet`

I told the master which IP address it should use by running`"kubeadm init --apiserver-advertise-address=...`. That information should be propagated to `kubelet`.

The worker should presumably take its IP address from the connection it opened to the master. (I cannot think of a good reason why it would need its IP address before it connects. If for some not-so-good reason it does then perhaps an additional command-line argument to `kubeadm join` would be required to let the user override the silly take-the-first-non-loopback-interface heuristic.)

If for some reason it is really not possible to make Kubernetes work correctly unless communication between nodes always goes via the first non-loopback interface (a somewhat embarrassing limitation to have to document) then there should at least be a clear error message when this condition is not satisfied rather than an obscure failure when certain features are used for the first time.

I have been testing versions 1.9.1, 1.9.2 and 1.9.3 with several different network configurations.

**Comment by AmedeeBulle** [comment]
Note that if your host name properly resolves to the IP address you want to use, kubelet will use it and everything will work as expected.

**Comment by juan-vg** [comment]
Same behavior in v1.10.3

I agree with @egrimley: that info should be propagated to kubelet **including those on the slave nodes** when joining the cluster

On the other hand @AmedeeBulle, my hostname properly resolves to my public address, which is different from my host-network/service-network address. I don't believe that behavior is the expected. Not for me at least

**Comment by lanoxx** [comment]
I have the same issue on my cluster.

I have two adapters `vEthernet (nat)` (first) and `Ethernet 3` (second). Kubelet picks the first adapter and thus uses the wrong IP.

**Comment by ArtemAlagizov** [comment]
that should be reopen, i believe.
or anybody has a solution?
