### ISSUE TITLE
[e2e] test invalid with CoreDNS - DNS Horizontal scaling 

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#61176]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
e2e test "gci-gce" is running in 2 versions:
* with kube-dns as DNS Service : https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce
* with CoreDNS as DNS Service : https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-coredns

In CoreDNS use case the test is failing

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:53
Expected error:
    <*errors.errorString | 0xc420eb17e0>: {
        s: "expected 1 DNS deployment, got 0",
    }
    expected 1 DNS deployment, got 0
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:63
```
				
**What you expected to happen**:
This e2e tests should not depend on what DNS service is running as default in K8s.

CoreDNS is currently BETA, will move to GA soon (after v1.10 though)
See : https://github.com/kubernetes/features/issues/427

**How to reproduce it (as minimally and precisely as possible)**:
look at logs of dashboard : https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-coredns

`go run hack/e2e.go -v --test --test_args='--ginkgo.focus=\[sig\-autoscaling\]\sDNS\shorizontal\sautoscaling\s\[DisabledForLargeClusters\]\skube\-dns\-autoscaler\sshould\sscale\skube\-dns\spods\sin\sboth\snonfaulty\sand\sfaulty\sscenarios$'
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): branch master
- Cloud provider or hardware configuration: GCE
- Install tools: deployment intra-test
- Others: see https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-coredns

**Comment by superawesome** [comment]
Looks like the test is searching specifically for a deployment named "kube-dns". There are several references to "kube-dns" scattered around it, actually.

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/dns_autoscaling.go#L40

**Comment by fturib** [comment]
Right now the tool "dns-horizontal-autoscaller" seems dedicated for kube-dns.

This tools is deployed as "add-on" hen enabled by this ENV variable : ENABLE_DNS_HORIZONTAL_AUTOSCALER

I guess we should have the definition of another dns-horizontal-autoscaller, dedicated to coredns (unless we generate the yaml file).

and the choice of deployment is based on the ENV variable CLUSTER_DNS_CORE_DNS.

see cluster/addons/dns-horizontal-autoscaler

**Comment by fturib** [comment]
Currently, the translation of the deployment of "dns-horizontal-autoscaller" for CoreDNS is in progress by @rajansandeep 

It is expected that the corresponding e2e test will work as is (as the artifacts are selected by labels, which are the same for CroeDNS and kube-dns).
