### ISSUE TITLE
etcd healtchecks always hit the same member

### ISSUE THREAD

**Issue by jpiper** [kubernetes/kubernetes#61180]
/kind bug

**What happened**:
Every time a health check is called on the APIServer via the `/healthz` endpoint, an etcd healthcheck is performed. 

However, as this just starts at the first server in the `--etcd-servers=` list passed to the apiserver binary all the healthchecks generate read load on a single etcd member.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/preflight/checks.go#L61

**What you expected to happen**:

The first server that is checked should either increment (and wrap around) each time or be randomised to spread load around the cluster

**Comment by hzxuzhonghu** [comment]
I think a random check is ok.
