### ISSUE TITLE
Fluentd-scaler causing fluentd pod deletions and messes with ds-controller

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#61190]
Forking from https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-373121164:

To summarize, here's what we observed:
1. PATCH daemonset calls coming every minute from both fluentd-scaler and addon-manager (verified this by individually turning them on/off). Things we need to understand here:
  - Is the daemonset object continuously toggling b/w 2 states? (we know here that it's RV is increasing continuously)
  - If yes, what field(s) in the object are changing? IIRC value of some label/annotation (I think 'UpdatedPodsScheduled') is changing (probably related to 2 below)
  - Also, why/should the fluentd-scaler send any api request if the resources are already set to the right value?
2. Fluentd pods are getting deleted and recreated by daemonset-controller when the scaler is enabled (as was also seen in https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-373001797). Why this is happening? One thing to note here - all those delete calls are preceded by `PUT pod-status` calls from respective kubelets (but maybe that's expected).

cc @kubernetes/sig-instrumentation-bugs @crassirostris @liggitt 
/priority critical-urgent
/assign @x13n

**Comment by shyamjvs** [comment]
Marked this as release-blocker as at least some part of it seems like a correctness issue (i.e fluentd pods dying and getting recreated).
Note also that this is causing increased mem-usage with daemonset-controller (depicted here - https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-372442191)

**Comment by x13n** [comment]
Thanks for filing this!

> - Is the daemonset object continuously toggling b/w 2 states? (we know here that it's RV is increasing continuously)
> - If yes, what field(s) in the object are changing? IIRC value of some label/annotation (I think 'UpdatedPodsScheduled') is changing (probably related to 2 below)

The only thing that was changing (apart from ds/fluentd-gcp status) was the resource version.

**Comment by x13n** [comment]
I modified fluentd scaler to use --dry-run in `kubectl set resources` to check whether there would be a change, but this still keeps on updating, even though there is no change. Apparently, the logic inside kubectl is broken...

**Comment by x13n** [comment]
Btw, addon manager sends tons of PATCH requests for all resources every minute anyway, so even though I will fix fluent-scaler not to send them, it won't solve everything.

**Comment by jberkus** [comment]
Should this issue actually be closed?  It was auto-closed by the bot, but nobody has confirmed that the actual issue is fixed.

**Comment by krzyzacy** [comment]
I'll let @shyamjvs to confirm (looks like he'll be back on Monday)

**Comment by shyamjvs** [comment]
Yes, we should keep this issue open until we fully understand what's going wrong and fix the root-cause.
I believe much of the discussion wrt this is happening under related issue https://github.com/kubernetes/kubernetes/issues/61189.

**Comment by jdumars** [comment]
ACK.  In progress
ETA: 20/03/2018
Risks: May delay the release if not satisfactorily resolved

**Comment by jdumars** [comment]
Need a number of successive green runs, then close.

**Comment by shyamjvs** [comment]
So I took a look and seems like the fluentd-scaler version bump (which was supposed to fix) was merged b/w runs 11683 and 11684 of our [100-node job](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce). However, I don't see any visible improvement in controller-manager memory usage around that time:

![yo](https://user-images.githubusercontent.com/4333971/37614535-426860b6-2bab-11e8-9de4-5804ec778fa8.png)

**Comment by shyamjvs** [comment]
Also, I'm noticing such lines occasionally (once every 5-10 secs in the start and once every ~1min later on) from [controller-manager logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11785/artifacts/e2e-big-master/kube-controller-manager.log) of latest run:

```
E0319 16:54:45.732764       1 daemon_controller.go:266] kube-system/fluentd-gcp-v3.0.0 failed with : error storing status for daemon set &v1.DaemonSet{.....}: Operation cannot be fulfilled on daemonsets.apps "fluentd-gcp-v3.0.0": the object has been modified; please apply your changes to the latest version and try again 
```

And back when the fluentd-scaler wasn't doing anything useful (i.e before https://github.com/kubernetes/kubernetes/pull/59921), the [controller-manager logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/10865/artifacts/e2e-big-master/kube-controller-manager.log) had such lines only sparingly.

**Comment by x13n** [comment]
Now it isn't even sending requests (other than GET) to the apiserver.

@shyamjvs How do you generate that graph? Is it 99th percentile of memory usage over time? Or what exactly? One difference after introducing fluentd-gcp-scaler is that now there is a change occurring on the DaemonSet (once, but still). Also, what test is failing because of this? I'd like to take a look into the logs.

**Comment by shyamjvs** [comment]
Answering your questions:

> How do you generate that graph?

I fetched the ResourceUsageSummaries for density test from historical runs (e.g https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11809/artifacts/ResourceUsageSummary_density_2018-03-20T11:46:02Z.json) and then plotted 99% mem-usage for controller-manager against runs.

> Is it 99th percentile of memory usage over time? Or what exactly?

Yes. More precisely, we're collecting mem-usage from controller-manager once every 1 min (or sth like that) and then taking 99th %ile of the resulting sample.

> Also, what test is failing because of this?

Density and load tests. Where we're checking that mem usage of controller-manager is less than the given threshold (i.e 500MB). Ref: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scalability/density.go#L171
The tests are occasionally failing due to just crossing the threshold. Overall, the mem-usage had seen an increase back during the scaler change (see graph above).

> I'd like to take a look into the logs.

The job is this - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce
Inside `artifacts/`, you'll find all necessary logs (also a file named `ResourceUsageSummary_density_*` which has the resource-usage data).

**Comment by shyamjvs** [comment]
The fluentd-scaler update eliminated fluentd restarts problem. Verified from controller-manager logs that we no longer see such logs that we were [earlier seeing](https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-373001797):

```
I0215 17:38:32.683798       1 controller_utils.go:590] Controller fluentd-gcp-v2.0.14 deleting pod kube-system/fluentd-gcp-v2.0.14-qkbsq
I0215 17:38:32.684117       1 controller_utils.go:590] Controller fluentd-gcp-v2.0.14 deleting pod kube-system/fluentd-gcp-v2.0.14-p4t52
I0215 17:38:32.684277       1 controller_utils.go:590] Controller fluentd-gcp-v2.0.14 deleting pod kube-system/fluentd-gcp-v2.0.14-gs956
```

This is great, and I believe that moves this out of release-blocker as we no longer face problems I mentioned in https://github.com/kubernetes/kubernetes/issues/61189#issuecomment-374191116.

**Comment by shyamjvs** [comment]
That said, @x13n and me will continue looking into increase in mem-usage (which is not that serious). We'll start by verifying that turning the scaler off improves mem-usage.

**Comment by shyamjvs** [comment]
@wojtek-t @jdumars Feel free to override me if you have a good reason :)

**Comment by wojtek-t** [comment]
I agree that this doesn't sounds to be release-blocker. But I would like to see follow-ups at least for issues like:
1. where does this memory increase come from?
2. why what was claimed to be "no-op" changes for daemon set were causing problems [is that issues in kubectl, apiserver, somewhere else?] Something like that may hit us again in the (near?) future if we won't understand it now. The current solution is really volatile [if there is a bug somewhere we shouldn't workaround it on our side, but instead have this fixed]
3. race at the cluster start (maybe it's fine to leave as is, but I would like to see a discussion of that and a conscious decision being made here)

**Comment by shyamjvs** [comment]
Definitely agree those are questions we need to answer.

**Comment by x13n** [comment]
Yup.
1) is tested in #61472.
2) I believe apiserver sends watch events even when only resource version changes, which causes the daemonset controller to recreate the pods. So either:
- resource version shouldn't change when there is no change anywhere else in the resource
- apiserver shouldn't send watch events when only resource version is changing
- daemonset should check whether watch event it got is actually changing anything
3) Isn't that an inherent part of the way addon manager works? It creates all sorts of resources, some dependent on the other (e.g. cluster roles and cluster role bindings), all at once. If some dependency is not satisfied, it will get fixed during the next run.

**Comment by wojtek-t** [comment]
> I believe apiserver sends watch events even when only resource version changes, which causes the daemonset controller to recreate the pods. So either:

This is the code that is supposed to protect us from situation that something must change when we write object to etcd (resource version is not stored in etcd):
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L325

So there should never be a situation that only resource version is changing. If it is, there is bug and need to be fixed. @liggitt - FYI

> Isn't that an inherent part of the way addon manager works?

Reconciliation is a different thing that creating something in one state only to change that to a different state by a different component. I'm not saying this is for sure wrong approach. But I would like to see a conscious decision process discussing pros-and-cons of that.

**Comment by shyamjvs** [comment]
> resource version shouldn't change when there is no change anywhere else in the resource

That's what I'd expect as well.

> apiserver shouldn't send watch events when only resource version is changing

This I'm not sure if should be correct behaviour as IIUC watchers need to receive every RV update for correctness reasons (@wojtek-t )

> daemonset should check whether watch event it got is actually changing anything

Maybe. But are we sure if RV is just increasing without any object change?

> Isn't that an inherent part of the way addon manager works?

For creation of addons, yes (that race will likely last only for starting few seconds).
But this is wrt addon changing cluster resources, which can potentially create race at arbitrary time after cluster start (though your fix may have gotten rid of this).

**Comment by shyamjvs** [comment]
Ok.. Seems like I missed Wojtek's comment above.

**Comment by shyamjvs** [comment]
So I just checked the ds-controller code and it seems like we're updating the ds status only if this condition is being violated:

https://github.com/kubernetes/kubernetes/blob/622ad3567791d30edced3b32821a4a2b26d5448d/pkg/controller/daemon/daemon_controller.go#L1011-L1021

Which means one of those fields is probably mismatching. I'll try to add some logs and run the test at --v=4 to get more info.

**Comment by liggitt** [comment]
> This is the code that is supposed to protect us from situation that something must change when we write object to etcd (resource version is not stored in etcd):
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L325
> 
> So there should never be a situation that only resource version is changing. If it is, there is bug and need to be fixed. @liggitt - FYI

anything is possible, but we do have tests ensuring this works properly (no-op updates do not actually result in an update+resourceVersion bump in etcd): https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go#L674-L728

**Comment by shyamjvs** [comment]
So I ran some 100-node experiments against https://github.com/kubernetes/kubernetes/pull/61472 with more debug logs and I think I now understand the reason for this. The controller-manager logs [with the scaler](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/61472/pull-kubernetes-e2e-gce-100-performance/11/artifacts/e2e-11-master/kube-controller-manager.log) and [without the scaler](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/61472/pull-kubernetes-e2e-gce-100-performance/13/artifacts/e2e-13-master/kube-controller-manager.log) mainly show the following difference:

```
I0321 14:26:34.315600       1 daemon_controller.go:986] Pods to delete for daemon set fluentd-gcp-v3.0.0: [fluentd-gcp-v3.0.0-j5vvh], deleting 1
I0321 14:27:26.218875       1 daemon_controller.go:986] Pods to delete for daemon set fluentd-gcp-v3.0.0: [fluentd-gcp-v3.0.0-jl74c], deleting 1
I0321 14:28:26.005293       1 daemon_controller.go:986] Pods to delete for daemon set fluentd-gcp-v3.0.0: [fluentd-gcp-v3.0.0-89dvm], deleting 1
I0321 14:29:24.596255       1 daemon_controller.go:986] Pods to delete for daemon set fluentd-gcp-v3.0.0: [fluentd-gcp-v3.0.0-l4qtp], deleting 1
```

This logs show-up when the scaler is active. And these pod deletions are happening as part of rolling-upgrade of daemonset to newer version (the one having resources set). You can see they're getting deleted one-by-one, which also explains why it takes so long (and so are happening even 30 mins after the cluster creation). And the reason why they're deleted one-by-one is because ds-controller has a rolling-upgrade strategy where `maxUnavailable=1` by default. Proof:

```
I0321 15:29:42.284073       1 update.go:431]  DaemonSet kube-system/fluentd-gcp-v3.0.0, maxUnavailable: 1, numUnavailable: 0
I0321 15:29:43.490056       1 update.go:431]  DaemonSet kube-system/fluentd-gcp-v3.0.0, maxUnavailable: 1, numUnavailable: 1
```

And the increased mem-usage FMU is because of the rolling-upgrade performed by ds-controller (over the prolonged period) - as it's the only difference I observe from logs
Further, the reason why the RV was increasing was because of few fields 'NumUnavailable', 'NumAvailable', etc fluctuating while the rolling-upgrade

**Comment by shyamjvs** [comment]
I spoke offline with @x13n and suggested that we should increase maxUnavailable for the fluentd daemonset to a large enough value so that we're not bottlenecked by it. My reasoning is:
- fluentd is not some user workload which will have some service downtime in case there are many unavailable at once
- fluentds on nodes are independent of each other (i.e one fluentd shouldn't need to wait for another node's fluentd to come up)
- we should try to make the scaling happen as fast as possible - otherwise it may be too late before they cope-up with increased log-load in the cluster

I'm going to make that change and test it against my PR (thanks @x13n for pointing that we can change maxUnavailable directly in ds config).

**Comment by shyamjvs** [comment]
So increasing maxUnavailable indeed seems to help (ref: [c-m logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/61472/pull-kubernetes-e2e-gce-100-performance/15/artifacts/e2e-15-master/kube-controller-manager.log)):

```
I0322 12:18:37.297447       1 daemon_controller.go:986] Pods to delete for daemon set fluentd-gcp-v3.0.0: [fluentd-gcp-v3.0.0-6hvnl ... fluentd-gcp-v3.0.0-fcpwz], deleting 101
```

All the 101 replicas were deleted at once instead of one-by-one and happened pretty much within 2 mins of the original fluentd-ds seen by the controller:

```
I0322 12:16:49.538882       1 daemon_controller.go:164] Adding daemon set fluentd-gcp-v3.0.0
```

We should get that PR into 1.10.

**Comment by x13n** [comment]
Thanks for confirming this! Did increasing maxUnavailable also reduce c-m memory usage?

**Comment by x13n** [comment]
@shyamjvs Is there anything else to do here or should this be closed now?

**Comment by shyamjvs** [comment]
Let's close it once we're sure there are no more such failures. We may also
need to bump the threshold.

**Comment by shyamjvs** [comment]
So bumping maxUnavailable for fluentd rolling-upgrade in https://github.com/kubernetes/kubernetes/pull/61472 is causing couple of issues:

- Our latest 5k-node performance [run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/129) failed as part of BeforeSuite where we're checking that ~all kube-system pods are running or ready. The reason is because quite some fluentd pods were killed as part of the rolling-upgrade and we timed out before all those pods could come up
- Our 100-node performance runs [are flaking](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability?before=11998) due to high CPU/mem-usage of c-m observed during density test, in cases when the fluentd upgrade happens during the test - which is kind of expected

So at this point, we might want to choose among one of the 2 options:
- Rollback https://github.com/kubernetes/kubernetes/pull/61472, which comes at the cost of tradeoffs I explained in https://github.com/kubernetes/kubernetes/pull/61472#issuecomment-375374363
- Increase our CPU/mem thresholds to eliminate those flakes in 100-node job and increase the "max-allowed-not-ready-pods" in kube-system ns to a higher value, so that our 5k-node test doesn't fail in BeforeSuite

Thoughts?

**Comment by wojtek-t** [comment]
TBH, I don't know why it was merged without waiting for opinions...

I really vote for reverting that.

> Increase our CPU/mem thresholds to eliminate those flakes in 100-node job and increase the "max-allowed-not-ready-pods" in kube-system ns to a higher value, so that our 5k-node test doesn't fail in BeforeSuite

We don't want this - this may mean making cluster "not fully usable" from user perspective.Which is not really what we want to test.

**Comment by shyamjvs** [comment]
SGTM. Let's revert it and increase our thresholds for the time-being. The discussion about changing fluentd rolling-upgrades can continue to happen in the background.

**Comment by shyamjvs** [comment]
This issue is now fixed after my above PRs. We're having continuous green runs for the job - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability?before=12069
