### ISSUE TITLE
kubernetes的master连接2个nodes出现异常

### ISSUE THREAD

**Issue by heqiuwen** [kubernetes/kubernetes#61208]
**Is this a FEATURE REQUEST?**:

**What happened**:
[root@pqcgh077v01 kube-proxy]# cat kube-proxy.pqcgh077v01.unknownuser.log.WARNING.20180314-174840.1312
Log file created at: 2018/03/14 17:48:40
Running on machine: pqcgh077v01
Binary: Built with gc go1.6.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0314 17:48:40.470511    1312 reflector.go:330] pkg/proxy/config/api.go:30: watch of *api.Service ended with: too old resource version: 91407156 (91407873)
E0314 17:57:17.206096    1312 proxier.go:712] conntrack return with error: Error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH

[root@pqcgh077v01 kube-apiserver]# tail -200f kube-apiserver.pqcgh077v01.unknownuser.log.ERROR.20180314-174817.1313
Log file created at: 2018/03/14 17:48:17
Running on machine: pqcgh077v01
Binary: Built with gc go1.6.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0314 17:48:17.316037    1313 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured

![image](https://user-images.githubusercontent.com/37389591/37440438-a7f82820-2837-11e8-8699-79d8c95b9e27.png)

**Environment**: 
- Kubernetes version (use `kubectl version`): kubernetes-server-v1.4.5-linux-amd64
- OS (e.g. from /etc/os-release):centos 7.1

**Comment by zhangxiaoyu-zidif** [comment]
could you update your kubernetes to 1.8 above. =)

**Comment by heqiuwen** [comment]
why?

**Comment by gogeof** [comment]
@heqiuwen 因为 1.8 版本之后更加稳定一些，在老的版本上纠结没有意义

**Comment by heqiuwen** [comment]
好的，谢谢

**Comment by gogeof** [comment]
你是用kubeadm安装的吗 如果是的话我它有提供升级的 你看下它的帮助文档就知道 简单的话就是重装 使用新的van ben

**Comment by dims** [comment]
/close

please let us know if you see  problem with newer version
