### ISSUE TITLE
Application in one pod not able to connect to mongodb on another pod.

### ISSUE THREAD

**Issue by ahilmathew** [kubernetes/kubernetes#61207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**: I checked the logs of the application I am using and it says : 
Caused by: java.net.UnknownHostException: mongodb: 
Inside the application config file I have used the host name as mongodb and i have created a service for the mongo deployment with the service name as  : mongodb.

**What you expected to happen**: 
My understanding is that we can use the service names so that application can connect to each other. Help is much appreciated. Thanks.

**Anything else we need to know?**:
mongo.yaml
--------------

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    run: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
spec:
  selector:
    run: mongodb
  ports:
    - name: port1
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
----------------------------
application.yaml
---------------------------
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
  labels:
    run: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: application
    spec:
      containers:
      - name: application
        image: localhost:5000/application
        ports:
        - containerPort: 8085
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: application
spec:
  selector:
    run: application
  ports:
    - name: port1
      protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort
---------------------------------

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
- Kernel (e.g. `uname -a`): 
Linux k8s-master 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
@kubernetes/sig-aws-bugs
@kubernetes/sig-network

**Comment by ahilmathew** [comment]
@kubernetes/sig-aws-bugs

**Comment by kam2001** [comment]
kubectl describe pod mongo
connect to mongo on this IP from your app

**Comment by ahilmathew** [comment]
Ok here is the update. The issue is that I am able to connect if the pods are on different nodes.
If I have service A (pod a1 - spring boot app) on one node and Service B(pod b1 - mongodb) on another node. In this scenario service A and service B is able to communicate using the service name. But when these two services are in the same node, they are not able to resolve each other using the service names.
Any idea why?

**Comment by kam2001** [comment]
Are you using a service to expose mongo pod ?
Are you using a mongo host url in spring (in application.yml or application.properties) or spring is defaulting to localhost by default.
1. if you put both containers (mongo and spring app) in same pod, spring will pick mongo as localhost and it should work.
2. for example if your service exposing mongo pod is labeled db than just typing 'kubectl db' will give you the address for mongo to connect and you can use this address in application.properties in spring.

If your pods are not working under same node i wonder if you are specifically defining which node to be used for the pods.

**Comment by ahilmathew** [comment]
I'm using a service to expose mongo db. Service Name : mongodb
1. Yes using the same pod for both containers work. Using localhost in application.properties file will help to connect to mongodb.
2. In my case I'm using different pods for application and mongodb. 'kubectl mongodb' doesn't give anything. My understanding was that using the service name (mongodb) inside application.properties would help the app in connecting to mongodb. But this doesn't work either.
But if I assign mongodb pod to run on another node. Then the application pod is able to connect to the mongodb.

**Comment by kam2001** [comment]
> _My understanding was that using the service name (mongodb) inside application.properties would help the app in connecting to mongodb. But this doesn't work either._
Instead of using service name(mongodb) in application.properties (springboot) try to ' kubectl exec -it application /bin/bash' and than type 'env' to see all environment variables your application has. And if you try to 'ping mongodb' you will get an address which will look something like 'mongodb.default.svc.cluster.local' - try using this address in application.properties (springboot)

**Comment by ahilmathew** [comment]
Yes. I have tried using both 'mongodb' and 'mongodb.default.svc.cluster.local' , but the application doesn't connect (when both are on the same node). 
Also the ping from application doesn't work. If i ping mongodb or mongodb.default.svc.cluster.local, it doesn't resolve at all. Now if the application and mongodb are in different nodes, then ping resolves both mongodb and mongodb.default.svc.cluster.local

**Comment by reddybhavaniprasad** [comment]
I have deployed 3 mongo pods (1 Primary & 2 secondary) in openshift and they are up and running successfully.

I am able to connect to this mongo from outside the cluster though NodePort.
> mongo 167.254.204.170:32204 (successful)

Also able to connect from within the cluster using both Pod IP and dns (mongo-node-1.database.svc).

> mongo 10.130.1.70 (successful)
> mongo mongo-node-1.database.svc (successful)

When a springboot application tries to connect to mongodb it fails with 

>  {type=UNKNOWN, servers=[{address=mongo-node-1.database.svc:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=mongo-node-2.database.svc:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}, {address=mongo-node-3.database.svc:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect.

I created a dummy pod and tried to connect "mongodb" using "mongo-node-1.database" inside the pod and this is also successful.

> mongo mongo-node-1.database (successful)

Please let me know what is that causing the connection error from the springboot app pod.

**Comment by shakthi-manai** [comment]
I have a similar issue. I am able to access mongo db from the browser but inside the Kubernetes cluster my springboot application pod is not able to connect to the mongodb pod

**Comment by dosti-tee** [comment]
I ran into this problem for this last 2 days as well. Still trying to find a way through but no luck yet.

In case, anyone does find something, please kindly share.

**Comment by MidoAhmed** [comment]
Hello,
i have the same issue, my nodejs app pod can't reach mongodb pod,
`Connection error:  MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: getaddrinfo EAI_AGAIN mongo
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]`

but when I target the mongo service Ip [10.244.2.26:27017] then it works 

`Trying to connect to 10.244.2.26/my-db-name MongoDB database
(node:174) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:174) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
db connection open`

so i think there is a problem with dns i can't figure it out :(

**Comment by JuanValencia** [comment]
Same.  nslookup 
```
> nslookup mongo
...
Name:	mongo.default.svc.cluster.local
Address: 10.43.154.217
```
Then on connection:
```
MongoNetworkError: failed to connect to server [mongo.default.svc.cluster.local:27017] on first connect [Error: getaddrinfo ENOTFOUND mongo.default.svc.cluster.local
...
```

Providing the IP directly works fine, so definitely a DNS issue.  Was able to create using a simple k3d setup.

**Comment by calebespinoza** [comment]
@JuanValencia 
Where did you run the commando nslookup? I've run it in all my nodes but all of them showed me the same output
`nslookup mongodb
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find mongodb:   ##SERVFAIL`

**Comment by sudddy** [comment]
Any solution for this issue? I'm currently facing this issue. Any help is appreciated. 🙏
