### ISSUE TITLE
Singular "endpoint" not supported in kubectl 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#61200]
`Endpoint` is the only resource that cannot be specified in singular form in kubectl. 
```console
$ kubectl get endpoint 
error: the server doesn't have a resource type "endpoint"
```
https://github.com/kubernetes/kubernetes/blob/02611149c181f7fd9ab116c40d7ee32fb5934b7c/pkg/kubectl/kubectl.go#L156-L164

Is it intended? If so, why?

@kubernetes/sig-cli-maintainers

**Comment by liggitt** [comment]
because the type itself is plural: `type Endpoints struct`
