### ISSUE TITLE
Deployment "MinimumReplicasAvailable" is True when "unavailableReplicas" > 0

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#61205]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Deployment condition doesn't indicate that its replicas are not being ready

**What you expected to happen**:

Condition to reflect that replicas are not ready

**How to reproduce it (as minimally and precisely as possible)**:

* Create a deployment with invalid image; used `kubectl run test --image=nginx123`
* Pod gets stuck in ImagePullBackOff loop
* Deployment status is controversial - status.Conditions[MinimumReplicasAvailable]=true while "unavailableReplicas": 1

```
 "status": {
        "conditions": [
            {
                "lastTransitionTime": "2018-03-14T22:59:11Z",
                "lastUpdateTime": "2018-03-14T22:59:11Z",
                "message": "Deployment has minimum availability.",
                "reason": "MinimumReplicasAvailable",
                "status": "True",
                "type": "Available"
            }
        ],
        "observedGeneration": 1,
        "replicas": 1,
        "unavailableReplicas": 1,
        "updatedReplicas": 1
    }
```

**Anything else we need to know?**:

We do a lot of integration work with k8s, and rely on conditions to reflect the object state, in somewhat generic manner. It doesn't work for this particular use case as the condition says the deployment is ready, while it is not quite true.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2-gke.1
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig apps

**Comment by ShualLiu** [comment]
I think there is something wrong in subtraction.<br> https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync.go#L606
It should be availableReplicas **>** (deployment.Spec.Replicas)-deploymentutil.MaxUnavailable(*deployment) other than **>=**

**Comment by xialonglee** [comment]
@ShualLiu 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync.go#L606
These code use in rolling update scenery too
I think when in a `Deployment recreate` or `RollingUpdate` situation, it allowed  `availableReplicas` equals to zero.(when deployment.Spec.Replicas=1, deploymentutil.MaxUnavailable(*deployment)=1 with surge=0%)
but not allowed  `availableReplicas` equals to zero in deployment init creating or deployment scale normally situation.
The function `calculateStatus` doesn't distinguish those scenes.

**Comment by ayushpateria** [comment]
This is because the the default value of `maxUnavailable ` for deployments in `extensions/v1beta1` is 1 ([https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/defaults.go#L104]). And kubectl uses `extensions/v1beta1` by default for deployments. A fix would be to change 1 to 25% (like in `apps/v1beta1`). I'd like to take this up if the proposed solution looks fine.

**Comment by liggitt** [comment]
> kubectl uses extensions/v1beta1 by default for deployments

kubectl uses whatever version is defined in the manifest used to create the deployment

**Comment by ayushpateria** [comment]
I was a bit unsure if that'd be a breaking change, thanks for clarifying. 

> kubectl uses whatever version 
I meant in this case when the user is executing `kubectl run test --image=nginx123`, the generated manifest uses `extensions/v1beta1`

**Comment by liggitt** [comment]
> I meant in this case when the user is executing kubectl run test --image=nginx123, the generated manifest uses extensions/v1beta1

Yes, that would be worth adding an apps/v1 generator for

**Comment by krmayankk** [comment]
so it sounds like there is nothing to fix here because of the change in the defaults

**Comment by ayushpateria** [comment]
@krmayankk Yes, the defaults are changed in the newer API version (apps/v1), and this issue shouldn't occur with it.
@alena1108 `kubectl run` is being deprecated so it'd be better if you move to `kubectl create` and explicitly define the newer API version in the manifest. Or you could wait for #61288 to get merged, after which you can replace `kubectl run` with `kubectl create deployment`
