### ISSUE TITLE
Not able to compile the code with this package kubernetes/plugin/pkg/scheduler/api

### ISSUE THREAD

**Issue by divya25d** [kubernetes/kubernetes#61215]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

> Uncomment only one, leave it on its own line: 
>
> /kind bug
downloading the package k8s.io/kubernetes with version 1.8.0 with subpackages plugin/pkg/scheduler/api using glide pacakge management tool.
When I am trying to build my code compilation is failing because of below file. kubernetes/plugin/pkg/scheduler/api/zz_generated.deepcopy.go
When I remove the file from the path I am able to build my code.

> /kind feature

**What happened**:
Below is the error because of compilation is failing.
[ERROR] vendor/k8s.io/kubernetes/plugin/pkg/scheduler/api/zz_generated.deepcopy.go:114:9: (*in).DeepCopyInto undefined (vendor/k8s.io/api/core/v1".Pod has no field or method DeepCopyInto)

**What you expected to happen**:
Let me know how to resolve this issue or else provide me commit in which the issue is already fixed.

**How to reproduce it (as minimally and precisely as possible)**:
download the package using glide and try to compile the code.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux  4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubeadm
@kubernetes/sig-apimachinery-bugs
![k8s io_kubernetes_deepcopy](https://user-images.githubusercontent.com/18500941/37448933-6835ede6-284e-11e8-8e12-5bb611eefc13.PNG)

- Others:

**Comment by liggitt** [comment]
make sure you get matching levels of `k8s.io/api`
