### ISSUE TITLE
Persistent Volume Claim Protection

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#61214]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
/kind bug

**What happened**:
I test the pvc Protection in k8sv1.9,the pvc not by one pod used,and I delete the pvc ,the pvc status become Terminating but not remove,and never delete it always exist!

[root@k8s-jlx:/home/ubuntu/yaml]$ ps -aux |grep kube-api
kube     11982  2.6  2.4 380612 197592 ?       Ssl  14:45   0:20 /usr/bin/kube-apiserver --v=0 --etcd-servers=http://192.165.1.73:2379 --insecure-bind-address=0.0.0.0 --secure-port=6443 --insecure-port=8080 --service-cluster-ip-range=10.254.0.0/16 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass,PVCProtection --tls-cert-file=/etc/kubernetes/certs/server.crt --tls-private-key-file=/etc/kubernetes/certs/server.key --client-ca-file=/etc/kubernetes/certs/ca.crt --token-auth-file=/etc/kubernetes/tokens/known_tokens.csv --basic-auth-file=/etc/kubernetes/basic_auth/auth.csv --service-account-key-file=/etc/kubernetes/certs/server.crt --bind-address=0.0.0.0 --apiserver-count=1 --log-dir=/root/info/logs/k8s --logtostderr=false --allow-privileged=true --feature-gates=PVCProtection=true

[root@k8s-jlx:/home/ubuntu/yaml]$ kubectl describe pvc cinder-claim-sc
Name:          cinder-claim-sc
Namespace:     default
StorageClass:  gold
Status:        Terminating (since Thu, 15 Mar 2018 14:47:07 +0800)
Volume:        pvc-994bb480-281c-11e8-bfd4-fa163e4e3a84
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/cinder
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  12m   persistentvolume-controller  Successfully provisioned volume pvc-994bb480-281c-11e8-bfd4-fa163e4e3a84 using kubernetes.io/cinder

[root@k8s-jlx:/home/ubuntu/yaml]$ kubectl delete pvc cinder-claim-sc
persistentvolumeclaim "cinder-claim-sc" deleted
[root@k8s-jlx:/home/ubuntu/yaml]$ kubectl get pvc
NAME              STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cinder-claim-sc   Terminating   pvc-994bb480-281c-11e8-bfd4-fa163e4e3a84   1Gi        RWO            gold           36s

**What you expected to happen**:
when the pvc not used by one pod,delete the pvc and remove successully!
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jberkus** [comment]
I believe this is a known issue with PVC protection in 1.9?  You need to remove the finalizer manually.

**Comment by mlmhl** [comment]
I test this in the latest version and the PVC can be deleted. Any messages in controller's log?

**Comment by jianglingxia** [comment]
I use the1.9version
![image](https://user-images.githubusercontent.com/25783555/37501044-7d6afaee-2907-11e8-966a-846d6531331e.png)
![image](https://user-images.githubusercontent.com/25783555/37501062-952f6a66-2907-11e8-8dc7-f1956db79f6b.png)
the controller log 
![image](https://user-images.githubusercontent.com/25783555/37501119-d015a294-2907-11e8-8e20-d6e3fd989827.png)
thanks！

**Comment by liggitt** [comment]
did you also set that feature gate in the controller manager?

**Comment by jianglingxia** [comment]
sorry，I only config apiserver，I will later test it again thanks

**Comment by liggitt** [comment]
thanks

/close
