### ISSUE TITLE
Service type ExtenalName is not filling Host header.

### ISSUE THREAD

**Issue by vrubiella** [kubernetes/kubernetes#61226]
/kind feature

**What happened**:
Defining a service with ExternalName is useless for HTTP services because requests not includes Host header.

**What you expected to happen**:
Use ExternalName value in "Host" header by default.
Optionally, add anothe extra headers.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: gcloud

/sig network

**Comment by dejan9393** [comment]
Did you ever get an answer for your question? I'm running into the same issue

**Comment by loomsen** [comment]
me too.

/reopen
