### ISSUE TITLE
RBAC issue : Error from server (Forbidden): pods is forbidden: User "root" cannot list pods in the namespace "shopping"

### ISSUE THREAD

**Issue by irfanjs** [kubernetes/kubernetes#61222]
hello,
I am getting following error : 

> [root@centos-master ~]# kubectl --context=root-context get pods --namespace=shopping
> Error from server (Forbidden): pods is forbidden: User "root" cannot list pods in the namespace "shopping"
> [root@centos-master ~]#
> 
> 
I have created role and role-binding as follows :

> [root@centos-master ~]# cat deployment.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: shopping
  rules:
    -
      apiGroups:
        - ""
        - extensions
        - apps
      resources:
        - deployments
        - replicasets
        - pods
      verbs:
        - "*"
```

and rolebinding is as follows : 

> [root@centos-master ~]# cat rolebinding-deployment.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: shopping
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-manager
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: root
```

using following command I have created the resources 

> kubectl create -f rolebinding-deployment.yaml
> kubectl create --validate=false -f deployment.yaml

here the kubectl config 

> [root@centos-master ~]# kubectl config view
> apiVersion: v1
> clusters:
> - cluster:
>     certificate-authority-data: REDACTED
>     server: https://10.0.7.6:6443
>   name: kubernetes
> contexts:
> - context:
>     cluster: kubernetes
>     user: kubernetes-admin
>   name: kubernetes-admin@kubernetes
> - context:
>     cluster: kubernetes
>     namespace: shopping
>     user: root
>   name: root-context
> current-context: kubernetes-admin@kubernetes
> kind: Config
> preferences: {}
> users:
> - name: kubernetes-admin
>   user:
>     client-certificate-data: REDACTED
>     client-key-data: REDACTED
> - name: root
>   user:
>     client-certificate: /etc/kubernetes/pki/root.crt
>     client-key: /etc/kubernetes/pki/root.key
> [root@centos-master ~]#
> 

my understanding is , using above role permission , u should be able to list and deploy pods ... not getting why the error though....
do I need to create the clusterole as well .... I think , its not required as I am not doing anything on cluster level ... I just need permission on namespace level and this configuration is enough I guess ....

please suggest , how could I resolve this error ...
Thanks

**Comment by liggitt** [comment]
why did you have to add `--validate=false` when creating the role? if you retrieve the loaded role and role binding from the API (using `kubelet get`) do they match your local files?

**Comment by liggitt** [comment]
it looks like you nested `rules` under `metadata` in your Role, which is invalid (and probably what validation was warning you about), and has the result of creating an empty Role with no rules. Make `rules` be a top-level field.

/close

**Comment by irfanjs** [comment]
thanks much .... its resolved .....
the role itself was not created ... :)

**Comment by irfanjs** [comment]
hello,
after having proper role creation and rolebinding, now still I am not able to deploy the pods 
I have gone through the docs : https://kubernetes.io/docs/admin/authorization/rbac/

here is the error I am getting 

> Error from server (Forbidden): deployments.extensions is forbidden: User "root" cannot create deployments.extensions in the namespace "shopping"

**Comment by liggitt** [comment]
can you provide the role/rolebinding as retrieved from the apiserver with `kubectl get -o yaml`?

that role/rolebinding are in the `shopping` namespace, not the `xyz` namespace

**Comment by irfanjs** [comment]
sorry ... it was not xyz ... it is a "shopping" only ....

here are the command:

> 
> [root@centos-master ~]# kubectl get rolebindings -o yaml
> apiVersion: v1
> items:
> - apiVersion: rbac.authorization.k8s.io/v1
>   kind: RoleBinding
>   metadata:
>     creationTimestamp: 2018-03-14T08:46:07Z
>     name: deployment-manager-binding
>     namespace: default
>     resourceVersion: "294382"
>     selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/deployment-manager-binding
>     uid: 2330f3e9-2764-11e8-802d-000d3ab7b12a
>   roleRef:
>     apiGroup: rbac.authorization.k8s.io
>     kind: Role
>     name: deployment-manager
>   subjects:
>   - apiGroup: rbac.authorization.k8s.io
>     kind: User
>     name: root
> kind: List
> metadata:
>   resourceVersion: ""
>   selfLink: ""
> [root@centos-master ~]#
>

**Comment by liggitt** [comment]
to grant permission in the `shopping` namespace, you have to create the role and rolebinding in the shopping namespace. the rolebinding you listed is in the `default` namespace

**Comment by irfanjs** [comment]
true. but if you see the role and rolebinding yaml file in very first post , it has namespace as **shopping** and not default

**Comment by liggitt** [comment]
>  I have created role and rolebinding in shopping name space only

Apparently not :)

Delete the role and rolebinding from the default namespace, create them in the shopping namespace, and provide the output of:
```
kubectl get roles,rolebindings -n shopping -o yaml 
```

**Comment by irfanjs** [comment]
ok.. I recreated role and rolebindings in shopping namespace. output as below : 

> [root@centos-master ~]# kubectl get roles,rolebindings -n shopping
> NAME                       AGE
> roles/deployment-manager   46s
> 
> NAME                                      AGE
> rolebindings/deployment-manager-binding   34s
> [root@centos-master ~]# kubectl get roles,rolebindings -n shopping -o yaml
> apiVersion: v1
> items:
> - apiVersion: rbac.authorization.k8s.io/v1
>   kind: Role
>   metadata:
>     creationTimestamp: 2018-03-16T16:23:40Z
>     name: deployment-manager
>     namespace: shopping
>     resourceVersion: "536022"
>     selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/shopping/roles/deployment-manager
>     uid: 635ea1a0-2936-11e8-865d-000d3ab7b12a
>   rules:
>   - apiGroups:
>     - ""
>     resources:
>     - deployments
>     - replicasets
>     - pods
>     verbs:
>     - '*'
> - apiVersion: rbac.authorization.k8s.io/v1
>   kind: RoleBinding
>   metadata:
>     creationTimestamp: 2018-03-16T16:23:52Z
>     name: deployment-manager-binding
>     namespace: shopping
>     resourceVersion: "536037"
>     selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/shopping/rolebindings/deployment-manager-binding
>     uid: 6a85858d-2936-11e8-865d-000d3ab7b12a
>   roleRef:
>     apiGroup: rbac.authorization.k8s.io
>     kind: Role
>     name: deployment-manager
>   subjects:
>   - apiGroup: rbac.authorization.k8s.io
>     kind: User
>     name: root
> kind: List
> metadata:
>   resourceVersion: ""
>   selfLink: ""
> [root@centos-master ~]#
> 
is this ok now ? Thanks ...

**Comment by liggitt** [comment]
Your role is missing apiGroups extensions and apps

**Comment by irfanjs** [comment]
I created the role after referring : https://kubernetes.io/docs/admin/authorization/rbac/. I thought by putting apiGroups as [""] will refer to core API and wud be sufficient. I will change it to : **rbac.authorization.k8s.io**

**Comment by irfanjs** [comment]
please suggest ...

**Comment by liggitt** [comment]
you are trying to grant access to deployments in the extensions and apps API groups. that requires you to specify the extensions and apps api group in your role rules:

```
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
```
