### ISSUE TITLE
pull-kubernetes-e2e-gce flakes: Stackdriver Logging sink: googleapi: Error 400: There is a maximum of 90 sinks allowed, failedPrecondition

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#61230]
pull-kubernetes-e2e-gce tests are failing very frequently with stackdriver related errors: "failed to create Stackdriver Logging sink: googleapi: Error 400: There is a maximum of 90 sinks allowed, failedPrecondition"

For example: https://k8s-gubernator.appspot.com/pr/61196

/sig testing

**Comment by crassirostris** [comment]
Related to https://github.com/kubernetes/test-infra/issues/7295

I fixed the bleeding temporarily, @krzyzacy will add sinks to the list of cleaned projects, this should solve the problem

**Comment by krzyzacy** [comment]
/sig instrumentation
cc @piosz @brancz

so there's no timeout between the green/red runs today, something triggered this and I cannot tell, someone might want to figure out the cause of leaking

**Comment by liggitt** [comment]
immediate issue is fixed, lowering urgency, will leave open until root caused

**Comment by krzyzacy** [comment]
```
senlu@senlu:/google/src/cloud/senlu/double-list/google3$ gcloud logging sinks describe e2e-tests-sd-logging-tvwpl --project=k8s-jkns-pr-gce-etcd3
destination: pubsub.googleapis.com/projects/k8s-jkns-pr-gce-etcd3/topics/e2e-tests-sd-logging-tvwpl
filter: resource.type="container" AND resource.labels.namespace_id="e2e-tests-sd-logging-tvwpl"
name: e2e-tests-sd-logging-tvwpl
outputVersionFormat: V2
writerIdentity: serviceAccount:cloud-logs@system.gserviceaccount.com
```

hummm, looks like it's not feasible let janitor clean sinks since the sinks does not have a `createTimeStamp` - this definitely needs to be added

**Comment by x13n** [comment]
/priority critical-urgent
This is happening again.

**Comment by krzyzacy** [comment]
@x13n so my question is, why log sink is leaking?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/pull/61306 should give a better signal whenever a sink leaked

**Comment by liggitt** [comment]
mitigations appear to be holding
/close

**Comment by krzyzacy** [comment]
forgot to update, we migrated pull-gce job to boskos so each run can have a separated project and we wipes out all logging sinks after each e2e run, this issue is fine now, but we probably still want to improve from the api side.
