### ISSUE TITLE
HTTP 200 from API without correct key 

### ISSUE THREAD

**Issue by robotron-sr** [kubernetes/kubernetes#61278]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
We have a master node on a cloud provider, secured with certificates. We see a lot of status 200 respones from the master to different IPs, which are not our owns.
Anonymous login was off!

**What you expected to happen**:
Every client without the correct certificate should get HTTP status 401. 

**Anything else we need to know?**:
Is there any possibility to receive a 200 without a valid key / certificate.

**Environment**:
Kubernetes 1.5.3
- Cloud provider or hardware configuration: Azure

**Comment by liggitt** [comment]
/sig auth
/sig azure

can you provide your apiserver startup flags? are you running with `--insecure-port=0` to disable it?

**Comment by hzxuzhonghu** [comment]
Or you may set authz AlwaysAllow?

**Comment by liggitt** [comment]
Closing for lack of information

/close
