### ISSUE TITLE
deploy on a preemptive node pool  , the pods have wrong age

### ISSUE THREAD

**Issue by redliu312** [kubernetes/kubernetes#61286]
**What happened**:
I know I have a deployment scheduled in a preemptive node pool . At the time when the node is terminated and created, I saw the pod destroyed and created on the node which met my expect.
The node age is around 15 minutes and the pods are around 14 minutes.
6 hour later,  I check the node and pods age again, the pod age is elder than the node,
like the pods themselves have never been deleted.
  
- the node age

```
mem-4a962b8d-s6m6      Ready     <none>    6h        
```
- the pod age

```
vc-6f6995dbd7-kzpgx   2/2       Running   0          1d        
```

- the pod  description

```
Name:           vc-6f6995dbd7-kzpgx
Namespace:      default
Node:           mem-4a962b8d-s6m6/10.240.0.28
Start Time:     Thu, 15 Mar 2018 12:30:36 +0800
Labels:         app=vc
                pod-template-hash=2925518683
...
```
as you can see, the pod **vc-6f6995dbd7-kzpgx**  is elder than the pod "mem-4a962b8d-s6m6".
Is this a bug or I misunderstand the concepts?
@kubernetes/sig-cluster-lifecycle-bugs
/sig cluster-lifecycle
/kind bug

**Comment by liggitt** [comment]
An unschedulable pod will persist until a node shows up that can run it. That can result in a 1 day old pod getting scheduled to a 6 hour old node

/close
