### ISSUE TITLE
Subpath volumes don't receive set-GID flag

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#61283]
**Fix status:**
- [x] fixed in master in https://github.com/kubernetes/kubernetes/pull/61284, will be in 1.10.0
- [x] fixed in release-1.9 branch in https://github.com/kubernetes/kubernetes/pull/61308, will be in 1.9.7
- [x] fixed in release-1.8 branch in https://github.com/kubernetes/kubernetes/pull/61309, will be in 1.8.11
- [x] fixed in release-1.7 branch in https://github.com/kubernetes/kubernetes/pull/61310, will be in 1.7.16

Subpaths of volumes with fsGroup may be mounted into a container without SGID bit on themselves:

```sh
$ kubectl create -f - <<EOF                                                                                                                kind: Pod
apiVersion: v1
metadata: { name: "subpath" }
spec:
  volumes:
    - { name: "direct",  emptyDir: {}}
    - { name: "subpath", emptyDir: {}}
  securityContext:
    fsGroup: 100
    runAsUser: 35
  containers:
    - image: aosqe/hello-openshift
      name: show
      volumeMounts:
        - name: "direct"
          mountPath: "/mnt/direct"
        - name: "subpath"
          mountPath: "/mnt/subpath"
          subPath: "a"
EOF

$ kubectl exec -ti subpath -- ls /mnt -la
drwxrwsrwx    2 root     users            6 Mar 16 15:13 direct
drwxrwxrwx    2 root     users            6 Mar 16 15:13 subpath
```

The mode of `subpath` should be `drwxrwsrwx` instead of `drwxrwxrwx`.

Reason for this is `fchmod` at https://github.com/kubernetes/kubernetes/blob/5110db5087513801fc5946abcbd73c44e692b2c8/pkg/util/mount/mount_linux.go#L1035:

```go
	if err = syscall.Fchmod(parentFD, uint32(perm)&uint32(os.ModePerm)); err != nil {
		return fmt.Errorf("chmod %q failed: %s", currentPath, err)
	}
```

1. it should not filter out sgid/suid/sticky flags with `&os.ModePerm`
2. `Fchmod()` int32 argument expects suid/sgid/sticky flags on different bits than `os.FileMode`.

/kind bug
/sig storage
@liggitt

**Comment by liggitt** [comment]
reopening to track fixed in to 1.7, 1.8, 1.9 branches

**Comment by liggitt** [comment]
/milestone clear

 No longer blocking 1.10. See https://github.com/kubernetes/kubernetes/issues/61283#comment-373875304

**Comment by jsafrane** [comment]
Should this issue be closed? Fixes have been merged into all maintained branches.
