### ISSUE TITLE
Audit logging spam in apiserver logs

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#61280]
Currently when apiserver is overloaded and the buffer in the buffered backend starts to overflow, apiserver starts to generate a lot of messages like this:

```
EXXXX XX:XX:XX.XXXXXX       1 metrics.go:86] Error in audit plugin 'webhook' affecting 1 audit events: audit webhook queue blocked
```

These messages should be somehow collapsed/filtered. For example, write this message only once in a minute or once in 5 minutes.

/cc @kubernetes/sig-auth-bugs

**Comment by hzxuzhonghu** [comment]
How many audit webhook servers in this case? And what's the qps they can handle?

Much like the bottleneck is in webhook server end.

**Comment by crassirostris** [comment]
Limiting audit logging backend and dropping audit events in case buffer is overflown is an expected behavior, so it should work

Currently it doesn't work well, that's the problem, not the audit backend configuration that limits the throughput :)
