### ISSUE TITLE
Proxied Watches are Not Load-Balanced Among Aggregated API-Servers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#61296]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I modified the sample api-server (https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/sample-apiserver) to run multiple aggregated api-servers, all behind the same Service.  See https://github.com/MikeSpreitzer/kubernetes/tree/sample-apiserver-hax-60065-metrics-dual/staging/src/k8s.io/sample-apiserver/artifacts/example for the modified version.  I scaled the wardle-server RC to three replicas.  I ran a bunch of controllers that watch Flunder objects (see https://github.com/MikeSpreitzer/k8api-scaletest/tree/master/flunder-logger).

I found that the main api-server opened two (not three) connections, and they were to the wardle api Service address rather than wardle server pod addresses.  Here are the wardle Service addresses:
```
root@k8s2ctrl:~# kubectl get Service -n wardle
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
api       ClusterIP   10.233.35.2     <none>        443/TCP    13d
etcd      ClusterIP   10.233.36.190   <none>        2379/TCP   1d
```

Here is the main api-server:
```
root@k8s2ctrl:~# ps l -p 21705
F   UID    PID   PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
4     0  21705  21686  20   0 1449380 617508 futex_ Ssl ?       187:09 /hyperkube apiserver --max-mutating-requests-inflight=500 --
```
... and here are its TCP connections with the cluster:
```
root@k8s2ctrl:~# lsof -nP -p 21705 | fgrep 10.233.
hyperkube 21705 root   71u     IPv4 13067402       0t0      TCP 10.10.21.1:58358->10.233.35.2:443 (ESTABLISHED)
hyperkube 21705 root   74u     IPv4 13066510       0t0      TCP 10.10.21.1:58368->10.233.35.2:443 (ESTABLISHED)
hyperkube 21705 root  314u     IPv6 13064670       0t0      TCP 10.10.21.1:6443->10.233.65.68:35302 (ESTABLISHED)
```

Looking carefully on the server side, we can see that these two connections actually attach to two different wardle server pods.  Here is the list of those processes on their host:
```
root@k8s2comp69:~# ps axl | grep server | grep -v grep
4     0  54375  54357  20   0  45680 30892 futex_ Ssl  ?          1:42 /kube-sample-apiserver --etcd-servers=http://etcd.wardle.svc.cluster.local:2379 --default-watch-cache-size=1000 -v=5
4     0 237571 237554  20   0  47792 31924 futex_ Ssl  ?          2:31 /kube-sample-apiserver --etcd-servers=http://etcd.wardle.svc.cluster.local:2379 --default-watch-cache-size=1000 -v=5
4     0 237598 237578  20   0  49104 29752 futex_ Ssl  ?          2:34 /kube-sample-apiserver --etcd-servers=http://etcd.wardle.svc.cluster.local:2379 --default-watch-cache-size=1000 -v=5
```

Look at the connections of the first:
```
root@k8s2comp69:~# nsenter -t 54375 -n netstat -nt | grep -w 443
tcp        0      0 10.233.98.167:36984     10.233.0.1:443          ESTABLISHED
tcp6       0      0 10.233.98.167:443       10.233.65.64:58368      ESTABLISHED
root@k8s2comp69:~# 
```
Now the second:
```
root@k8s2comp69:~# nsenter -t 237571 -n netstat -nt | grep -w 443
tcp        0      0 10.233.98.165:57352     10.233.0.1:443          ESTABLISHED
tcp6       0      0 10.233.98.165:443       10.233.65.64:58358      ESTABLISHED
root@k8s2comp69:~# 
```
And finally the third:
```
root@k8s2comp69:~# nsenter -t 237598 -n netstat -nt | grep -w 443
root@k8s2comp69:~# 
```

Also, _all_ the watches are being served by just one of the three aggregated api-servers.  Here it is:
```
root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-d7rbz | grep 'Starting watch' | tail -2
I0316 19:10:35.530538       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=5m26s
I0316 19:10:38.168988       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=9m10s
```
Earlier, when I ran the main api-server from release 1.9, all the watches went to a different server:
```
root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-7rtlv | grep 'Starting watch' | tail -2
I0315 22:27:00.569918       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=2 labels= fields= timeout=6m17s
I0315 22:27:03.117814       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=2 labels= fields= timeout=6m44s
```
And earlier still, when I ran the main api-server from release 1.8, all the watches went to the other server:
```
root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-wslkd | grep 'Starting watch' | tail -2
I0315 06:01:38.157283       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=2 labels= fields= timeout=5m53s
I0315 06:02:10.111224       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/fischers, rv=1 labels= fields= timeout=7m3s
```

**What you expected to happen**:
I expected that the watches would somehow be load-balanced across the three sample-apiservers.

**How to reproduce it (as minimally and precisely as possible)**:
I think I showed a pretty direct demonstration.

**Anything else we need to know?**:
I tried this with three different releases of the main api-server.  First, I tried it with release 1.8.7.  In that case, it was even worse --- there was only a single connection open from the main api-server to the wardle api service address.  Then I tried release 1.9.4.  That got me multiple connections, but no load balancing of the watches.  Finally I build what I found on the release-1.10 branch yesterday.  That is what I used to produce the evidence shown above.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
root@k8s2ctrl:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.4.13+f61f3ac6a699b2", GitCommit:"f61f3ac6a699b22fb2e403c3479d28c66d5539f8", GitTreeState:"clean", BuildDate:"2018-03-15T15:27:53Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: local VMs
- OS (e.g. from /etc/os-release): Ubuntu 16.04.1
- Kernel (e.g. `uname -a`): Linux k8s2ctrl 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubespray
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by hzxuzhonghu** [comment]
Actually you access wardle servers via clusterip, so this can exclude aggregator bug.  What network are you using iptables or ipvs, does is set any affinity or something?

**Comment by hzxuzhonghu** [comment]
Maybe related to    service ` sessionAffinity: ClientIP`

**Comment by MikeSpreitzer** [comment]
Yes, I realize that the wardle api Service's address is also called a cluster IP.  The bug here is that the load is not being balanced.  The main api-server _could_ connect to the cluster IP addresses in the Endpoints of the wardle api Service.  I am not saying that is _necessary_; in the situation I reported, the kube-proxy is doing an adequate job of distributing the connections that are opened by the main api-server.

In the system I reported above, kube-proxy is operating in iptables mode.

**Comment by hzxuzhonghu** [comment]
Aggregator default proxy request by clusterIP. And oddly, why are there only two watch connections?

**Comment by lavalamp** [comment]
Can you `kubectl get Endpoints -n wardle -o yaml`? And `kubectl get Service -n wardle -o yaml`?

The only way this makes sense to me is if there is both
a) a bug in apiserver:
- that e.g. only reads & manually endpoints if ssh tunnels are on
- that e.g. distributes randomly to all but the first/last endpoint
b) AND the service has client affinity turned on.

**Comment by MikeSpreitzer** [comment]
```
root@k8s2ctrl:~# kubectl get Endpoints -n wardle -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2018-03-02T20:40:51Z
    name: api
    namespace: wardle
    resourceVersion: "9858849"
    selfLink: /api/v1/namespaces/wardle/endpoints/api
    uid: feefe5f6-1e59-11e8-9931-525400101501
  subsets:
  - addresses:
    - ip: 10.233.98.165
      nodeName: k8s2comp69
      targetRef:
        kind: Pod
        name: wardle-server-wslkd
        namespace: wardle
        resourceVersion: "9348467"
        uid: f8c853f2-2811-11e8-9294-525400101501
    - ip: 10.233.98.166
      nodeName: k8s2comp69
      targetRef:
        kind: Pod
        name: wardle-server-7rtlv
        namespace: wardle
        resourceVersion: "9348465"
        uid: f8ce7991-2811-11e8-9294-525400101501
    - ip: 10.233.98.167
      nodeName: k8s2comp69
      targetRef:
        kind: Pod
        name: wardle-server-d7rbz
        namespace: wardle
        resourceVersion: "9800305"
        uid: 0ef404fe-2890-11e8-b1b0-525400101501
    ports:
    - port: 443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2018-03-15T04:44:27Z
    name: etcd
    namespace: wardle
    resourceVersion: "9366096"
    selfLink: /api/v1/namespaces/wardle/endpoints/etcd
    uid: 8a9d7696-280b-11e8-9294-525400101501
  subsets:
  - addresses:
    - ip: 10.233.98.162
      nodeName: k8s2comp69
      targetRef:
        kind: Pod
        name: etcd-c46pp
        namespace: wardle
        resourceVersion: "9346671"
        uid: 7df2bf80-2811-11e8-9294-525400101501
    ports:
    - port: 2379
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by MikeSpreitzer** [comment]
```
root@k8s2ctrl:~# kubectl get Service -n wardle -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-03-02T20:40:51Z
    name: api
    namespace: wardle
    resourceVersion: "352388"
    selfLink: /api/v1/namespaces/wardle/services/api
    uid: fed6c06a-1e59-11e8-9931-525400101501
  spec:
    clusterIP: 10.233.35.2
    ports:
    - port: 443
      protocol: TCP
      targetPort: 443
    selector:
      apiserver: "true"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-03-15T04:44:26Z
    name: etcd
    namespace: wardle
    resourceVersion: "9324769"
    selfLink: /api/v1/namespaces/wardle/services/etcd
    uid: 8a99d416-280b-11e8-9294-525400101501
  spec:
    clusterIP: 10.233.36.190
    ports:
    - port: 2379
      protocol: TCP
      targetPort: 2379
    selector:
      etcdserver: "true"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by MikeSpreitzer** [comment]
I am not using SSH tunnels.  I am using the networking set up by kubespray, which seems to include Calico using its ip-in-ip mode.

**Comment by MikeSpreitzer** [comment]
This does not look like a networking issue to me.  The problem is that the main api-server is opening only 2 connections, not number(Endpoints), and is sending all the watches over just one of the connections.

**Comment by hzxuzhonghu** [comment]
But aggregator access endpoint by clusterip, which belongs to network.

**Comment by MikeSpreitzer** [comment]
The network is doing what the api-server asked of it, as far as I can tell.

**Comment by lavalamp** [comment]
Aggregator should not be accessing by cluster IP, it should be accessing by
endpoint IP. Likely we haven't noticed this because we *do* run with the
SSH tunnels.

**Comment by hzxuzhonghu** [comment]
@lavalamp I got  clusterip access by https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L478 What do I miss?

**Comment by lavalamp** [comment]
Yeah, I guess we did make that mode use the network fabric rather than look
up the endpoints. That technically is a layer violation, although I don't
want to relitigate it right now.

This seems like a bad interaction between HTTP2 and load balancers when a
client wants multiple connections to be distributed among backends.

Mike, can you flip on the --enable-aggregator-routing flag and see if it
behaves more like you expect? I think you can turn that on and still leave
the ssh tunnels off.

I'm going to be OOO for a few days, will check back on Friday.

**Comment by MikeSpreitzer** [comment]
Yes, that did the trick!
```
root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-7rtlv | grep 'Starting watch' | tail -2
I0320 15:26:28.962111       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=2 labels= fields= timeout=8m5s
I0320 15:26:57.873986       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=6m10s

root@k8s2ctrl:~# date
Tue Mar 20 15:27:53 UTC 2018

root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-d7rbz | grep 'Starting watch' | tail -2
I0320 15:27:46.781412       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=8m1s
I0320 15:27:54.779908       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=2 labels= fields= timeout=8m49s

root@k8s2ctrl:~# kubectl logs -n wardle wardle-server-wslkd | grep 'Starting watch' | tail -2
I0320 15:28:10.779907       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=7m58s
I0320 15:28:11.871235       1 rest.go:362] Starting watch for /apis/wardle.k8s.io/v1alpha1/flunders, rv=182 labels= fields= timeout=6m2s
```
