### ISSUE TITLE
Delete dashboard [signal SIGSEGV: segmentation violation]

### ISSUE THREAD

**Issue by piyushkv1** [kubernetes/kubernetes#61320]
##### Environment

Creating same issue here in core repo since it is found in kubectl
https://github.com/kubernetes/dashboard/issues/2900
```
Dashboard version: latest
Kubernetes version: 1.9
Operating system: 16.04.3 LTS
Node.js version: v4.2.6
Go version: go1.9.2
```

##### Steps to reproduce
kubectl delete  -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result
root@sc-rdops-vm04-dhcp-114-244:~# kubectl delete  -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
secret "kubernetes-dashboard-certs" deleted
serviceaccount "kubernetes-dashboard" deleted
role "kubernetes-dashboard-minimal" deleted
rolebinding "kubernetes-dashboard-minimal" deleted
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x627db6]

goroutine 1 [running]:
panic(0x1bcc980, 0xc4200100a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/kubectl.ReaperFor(0xc420b9a210, 0x4, 0xc420b9a260, 0xa, 0x0, 0x0, 0x1c03940, 0xc420b9bf10, 0xc420beb338, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/stop.go:95 +0xf26
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc420330840, 0xc42038c3f0, 0x40f9b5, 0xc420b95680, 0xc420beb350, 0x5d86b3)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:290 +0x151
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*factory).Reaper(0xc4206855f0, 0xc42038c3f0, 0x1da1e80, 0xc4200b4370, 0xc420beb4a8, 0x57c3e2)
	<autogenerated>:92 +0x54
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult.func1(0xc4200d3e80, 0x0, 0x0, 0x9, 0x650801)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:252 +0xdb
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc4200d3e80, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:348 +0x153
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc4200d3e80, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:324 +0xe5
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4200d3e80, 0x0, 0x0, 0xc420beb658, 0x442dd5)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:389 +0x57c
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit.func1(0xc4200d3e80, 0x0, 0x0, 0x480, 0xc4201dde30)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:207 +0x153
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc4205ef500, 0xc4208618e0, 0xc42075a1c0, 0x7fe0db51be88)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:552 +0x308
k8s.io/kubernetes/pkg/kubectl/resource.(*URLVisitor).Visit(0xc420861780, 0xc4208618e0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:243 +0x12c
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc420351400, 0x1, 0x1, 0xc420852660, 0x1, 0xc420852660)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:211 +0xf4
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc420861820, 0xc420852660, 0x0, 0x1edd5aa)
	<autogenerated>:122 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2a1dac0, 0xc420861820, 0xc4205ef4c0, 0xc4205ef540, 0xc420861801, 0xc4205ef540)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:417 +0x94
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420861840, 0xc4205ef540, 0x18, 0x18)
	<autogenerated>:138 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2a1db40, 0xc420861840, 0xc420351410, 0x2, 0x2, 0xc4208618a0, 0xc420351401, 0xc4208618a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:325 +0xd6
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc420852630, 0xc4208618a0, 0x1c4d160, 0xc41fff1107)
	<autogenerated>:158 +0x78
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x2a1da40, 0xc420852630, 0xc4201ddf10, 0x7fe0db5a54b0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:352 +0xf1
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc420351420, 0xc4201ddf10, 0x40ee98, 0x70)
	<autogenerated>:153 +0x65
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc4201ddea0, 0xc4201ddf10, 0x2ade0a8, 0x2a1da40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:96 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult(0xc4201ddea0, 0x2a3ff80, 0xc4206855f0, 0x2a1cc40, 0xc420020010, 0x2a20001, 0x0, 0xffffffffffffffff, 0x2a30000, 0x2a37cc0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:277 +0x16f
k8s.io/kubernetes/pkg/kubectl/cmd.(*DeleteOptions).RunDelete(0xc4209c0160, 0x2a3ff80, 0xc4206855f0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:237 +0xc5
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDelete.func1(0xc420309d40, 0xc4203dc660, 0x0, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:143 +0x17c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420309d40, 0xc4203dc200, 0x2, 0x2, 0xc420309d40, 0xc4203dc200)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203698c0, 0xc420459fd0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203698c0, 0xc4206855f0, 0x2a1cc00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
root@sc-rdops-vm04-dhcp-114-244:~#

**Comment by mountkin** [comment]
Please upgrade your `kubectl` to a newer version and try again.
The `pkg/kubectl/stop.go` was deleted since v1.8
