### ISSUE TITLE
kubect logs doe not work when switch container runtime from docker to cri-containerd

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#61327]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I started a cluster using docker as the container runtime, and run several pods. I then change the kubelet configuration to use cri-containerd as the container runtime, and restart the kubelet. The pods
are running, however running ```kubectl logs``` returns error.

**What you expected to happen**:
```kubectl logs``` should return container logs.

**How to reproduce it (as minimally and precisely as possible)**:
Run some pods in kubernetes, change kubelet configuration to use cri, and check the container logs.

**Anything else we need to know?**:
It seems that the pod still has a symlink to the previous logs file from docker container. If I delete the pod and let them restart, I can get the logs with ```kubectl logs```

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by Random-Liu** [comment]
@qiujian16 I don't think live upgrade from docker to a CRI container runtime such as containerd is supported.

After you restart kubelet, kubelet won't see previous running containers from Docker, although they are still running. And kubelet will start new containers in containerd. This will cause many problems.

So I think you'd better drain you node first before upgrade from docker to containerd. :)

**Comment by qiujian16** [comment]
@Random-Liu got it, thanks for confirmation :)
