### ISSUE TITLE
kubectl should return more information on failure

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6132]
After making a `kubectl create` call with bad JSON, kubectl would read-back the master's understanding of what I wrote and show me a diff.  Something like that

**Comment by bgrant0607** [comment]
Have you tried --validate, which reads the swagger?

diff and dry-run are already in cli-roadmap.md.

**Comment by bgrant0607** [comment]
See also #5889 and #6284.

**Comment by bgrant0607** [comment]
Another case where more info is desired on failure is update failure. Somewhere we discussed returning the whole object on conflict, for instance. A related discussion is https://github.com/GoogleCloudPlatform/kubernetes/pull/9569#discussion_r32160088
cc @smarterclayton @lavalamp

**Comment by bgrant0607** [comment]
Related: #8668

**Comment by smarterclayton** [comment]
I would prefer to have this behavior by default for our error object if we
can - it's a big performance win and reduces client annoyance.

On Jul 1, 2015, at 5:30 PM, Brian Grant <notifications@github.com> wrote:

Another case where more info is desired on failure is update failure.
Somewhere we discussed returning the whole object on conflict, for
instance. A related discussion is #9569 (comment)
<https://github.com/GoogleCloudPlatform/kubernetes/pull/9569#discussion_r32160088>
cc @smarterclayton <https://github.com/smarterclayton> @lavalamp
<https://github.com/lavalamp>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/6132#issuecomment-117830649>
.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by brianpursley** [comment]
Hi @thockin, @smarterclayton, @bgrant0607 
This issue has been open for a while, so I'm just checking to see if it is still an issue or not in the latest version.

It looks like there currently are some useful error messages given when there are problems with the json.  Do you think these are sufficient or is something more detailed needed?

Here is what I tried, using kubectl v1.18.0:

---
**Test 1: Invalid json** (removed " before metadata)
```
kubectl create -f - << EOF
{
    "kind": "Pod",
    "apiVersion": "v1",
    metadata": {
        "name": "nginx"
    },
    "spec": {
        "containers": [
            {
                "name": "nginx",
                "image": "nginx"
            }
        ],
        "restartPolicy": "Never"
    }
}
EOF
```
```
error: error parsing STDIN: json: line 3: invalid character 'm' looking for beginning of object key string
```

**Test 2: Json is valid but does not conform** (changed spec to xspec)
```
kubectl create -f - << EOF
{
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
        "name": "nginx"
    },
    "xspec": {
        "containers": [
            {
                "name": "nginx",
                "image": "nginx"
            }
        ],
        "restartPolicy": "Never"
    }
}
EOF
```
```
error: error validating "STDIN": error validating data: ValidationError(Pod): unknown field "xspec" in io.k8s.api.core.v1.Pod; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by bgrant0607** [comment]
Thanks. I think we can close this.
/close
