### ISSUE TITLE
Make pods/exec websocket channel 3 content easier to parse exit code

### ISSUE THREAD

**Issue by rjeberhard** [kubernetes/kubernetes#61346]
/kind feature

**What happened**:

As part of kubernetes-client/java, I'm looking at the websocket calls for pods/exec.  When the exec'd process exits with a non-zero code, we would like to provide this exit code value to the caller.

Exec status information is provided through websocket channel 3; however, this content is presently unstructured.  For instance, the following content was returned:

command terminated with non-zero exit code: Error executing in Docker Container: 1

**What you expected to happen**:

I'd like to see the status returned as a JSON object with an exitCode attribute.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Pod that has a script that returns a non-zero exit code.
2. kubectl exec this Pod and script and watch the traffic on channel 3.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rjeberhard** [comment]
@kubernetes/sig-api-machinery

Per robot request, looping in sig-api-machinery.

**Comment by rjeberhard** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by jennybuckley** [comment]
@ncdc do you know who owns this now?

**Comment by ncdc** [comment]
@jennybuckley in terms of an actual human? 😄 I don't know. @smarterclayton did the bulk of the websocket exec/attach/portforward implementation originally. I believe @sttts added error code return value support to the SPDY implementation.

**Comment by smarterclayton** [comment]
There were two plans:

1. update web socket protocol for both port forward and exec to be a bit easier to use (port forward doesn't work with web sockets well)
2. create a new REST sub resource on pods that allows you to POST json and get back JSON

Your request sounds like a change that we could maybe roll into 1, I just don't have a timeframe where that will happen.

**Comment by rjeberhard** [comment]
Thanks, @smarterclayton.  In the meantime, can you or a delegate confirm if the following is true?:

1) When the web socket communication is closed with status code 1000 and no data messages have been delivered to channel 3, then the pod/exec process exited with status code 0.

2) Similar to above, but a single data message was delivered on channel 3 then that message will have UTF-8 bytes matching the following pattern allowing the parsing of <exit code>:

command terminated with non-zero exit code: Error executing in Docker Container: <exit code>

3) Any other use case, we would properly assume that the exit code is unknown.

Looping in @brendandburns

**Comment by brendandburns** [comment]
I don't think we can rely on that string, though it is probably true for now. My guess is that's an error straight from the container runtime, and different runtimes will print different things.

We should really standardize this.

--brendan

________________________________

**Comment by sttts** [comment]
In SPDY we have 4 channels, one of them is an error channel that gets a `meta/v1.Status` object at the end. It includes the error code. Compare https://github.com/kubernetes/kubernetes/blob/8574bc564f4c54aa964d6c0c7ccec3202d9e2f1b/staging/src/k8s.io/client-go/tools/remotecommand/v4.go#L61.

Looks like we need the same in the websocket protocol if we don't have that yet.

**Comment by smarterclayton** [comment]
It would require a new protocol version, which is a nontrivial, but I agree
that we should return structured and CONSISTENT errors from the container
runtime layer back to the apiserver so that you can actually work with
this.  Relying on the string won't be safe.

**Comment by smarterclayton** [comment]
There should be a websocket 4 exec protocol... if not that's a problem.

**Comment by rjeberhard** [comment]
In the meantime, can I at least rely on the fact that no message on the status channel means that the exit code is 0?

**Comment by rjeberhard** [comment]
@smarterclayton What k8s server versions support websocket 4 exec protocol?  I see that the client code we are working with includes "v4.channel.k8s.io" in the "X-Stream-Protocol-Version" header.

**Comment by brendandburns** [comment]
Can't we argue that since the string was unstructured and couldn't be relied on that this isn't a breaking change?

Do we know if any code (other than this Java code which is new) that relies on this string?

--brendan

________________________________

**Comment by rjeberhard** [comment]
Based on the code that @sttts shared, it looks like protocol version 4 already returns a structured response.  If that's the case, I'd be happy to just support exit code 0 or not on older protocol versions (not parse the unstructured string).  But, I'd like to understand the mapping from k8s server version to exec protocol version 4.

**Comment by ncdc** [comment]
Added in v1.4.0

**Comment by rjeberhard** [comment]
So, this appears to be not a bug.  

One final question here though...  The existing code we were working with (kubernetes-client/java project) was trying to select the protocol version by setting and then reading the header: "X-Stream-Protocol-Version".  However, I saw from the earlier code shared that the correct header is: "Sec-WebSocket-Protocol".

@brendandburns, if I adjust io.kubernetes.client.util.WebSockets to use "Sec-WebSocket-Protocol", then I see "v4.channel.k8s.io" selected and the message delivered to the status channel looks like this:

`{"metadata":{},"status":"Failure","message":"command terminated with non-zero exit code: Error executing in Docker Container: 1","reason":"NonZeroExitCode","details":{"causes":[{"reason":"ExitCode","message":"1"}]}}`
