### ISSUE TITLE
PV protection mechanism does not protect existing PVs in cluster

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#61364]
The PV projection mechanism introduced in 1.10 does not protect existing PVs in cluster. After upgrade to 1.10 users can still delete bound PVs from cluster.

cc @NickrenREN @pospispa 

/sig storage

**Comment by NickrenREN** [comment]
yeah, the protection controller will add finalizers for them if they are updated first.  But if we delete them at first, they are not protected unfortunately
A `populator` may be added if needed.

**Comment by liggitt** [comment]
Doesn't the PV controller add finalizers on Add events? It receives an Add event for every existing PV at startup.

**Comment by liggitt** [comment]
Pretty sure this can be closed

**Comment by NickrenREN** [comment]
> It receives an Add event for every existing PV at startup.

If Add events are triggered at startup, the finalizers will be added by protection controller

**Comment by gnufied** [comment]
yeah I was wrong about Add event trigger on informer startup. closing

/close
