### ISSUE TITLE
`kubectl delete --force` doesn't work as expected

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#61374]
IMO it's surprising that `kubectl delete foo --force` does not force delete a resource. `--force` only takes effect when `--grace-period=0`. 

https://github.com/kubernetes/kubernetes/blob/7bcfbcd58515421d9756fc9bf89371c4e5257b2b/pkg/kubectl/cmd/delete.go#L211-L221

The description of `--force` reads this: `Immediate deletion of some resources may result in inconsistency or data loss and requires confirmation.`

We should make it more clear what `--force` does and even print warnings when `--force` is specified without `--grace-period=0`. 

@kubernetes/sig-cli-maintainers @smarterclayton

**Comment by smarterclayton** [comment]
Changing the meaning of force to actually break cluster consistency be default could lead to data loss, which is why we haven’t changed it so far.

agree we should print more info and clarfiy
