### ISSUE TITLE
No "Terminating" indication in kubectl get --output=json

### ISSUE THREAD

**Issue by calder** [kubernetes/kubernetes#61376]
/kind feature

`kubectl get` and `kubectl describe` both distinguish Terminating and Running pods. However,
```sh
kubectl get --output=json
```
shows `status.phase` as `Running` right up until the pod dies.

This also makes it impossible to use `--field-selector=...=Terminating` to select only Terminating pods, and means Terminating pods show up in `kubectl get --field-selector=status.phase.Running`. Example:

```sh
➤ kubectl get pods --field-selector=status.phase=Running
NAME                       READY     STATUS        RESTARTS   AGE
example-6c9b8f46d8-7dnrw   1/1       Terminating   0          2m
example-6c9b8f46d8-lt86m   1/1       Terminating   0          2m
example-7c588cf698-c99tb   1/1       Running       0          7s
example-7c588cf698-nqd8d   1/1       Running       0          4s
```

If this is the desired behavior for `status.phase`, it would be great to add a new field that *does* distinguish between Terminating and Running pods.

**Comment by calder** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
terminating comes from a non-nil metadata.deletionTimestamp
