### ISSUE TITLE
controller-manager startup with `--secure-port=xxxx` but no certificate provided should not be running

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#61381]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

when startup kube-controller-manager with the following flags
`controller-manager --v=3 --vmodule= --service-account-private-key-file=/tmp/kube-serviceaccount.key --root-ca-file=/var/run/kubernetes/server-ca.crt --cluster-signing-cert-file=/var/run/kubernetes/server-ca.crt --cluster-signing-key-file=/var/run/kubernetes/server-ca.key --enable-hostpath-provisioner=false --pvclaimbinder-sync-period=15s --feature-gates=AllAlpha=false --cloud-provider= --cloud-config= --kubeconfig /var/run/kubernetes/controller.kubeconfig --use-service-account-credentials --controllers=* --master=https://localhost:6443 --secure-port=10257`

It is running but with this log frequently.
`http: TLS handshake error from 127.0.0.1:42079: tls: no certificates configured`

**What you expected to happen**:

I expect controller-manager fails to startup without valid tls flags.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by 372046933** [comment]
What's the default value of --secure-port?

**Comment by hzxuzhonghu** [comment]
@372046933  0, which means not startup secure serving.

**Comment by 372046933** [comment]
controller-manager starts up but warning message is generated, I think that is expected behavior

**Comment by dims** [comment]
@hzxuzhonghu do you have a patch for this problem? (asking since you are active contributor :)
