### ISSUE TITLE
Complete ipvs proxier ut

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#61390]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**What happened**:
In ipvs proxy mode, most service functions like "nodeport/loadbalance" is realized by the association of iptables/ipset/ipvs, yet most ipvs proxier ut only verified ipvs rules, which can't ensure service is functional.

**What you expected to happen**:
Check both ipvs rules and iptables chains/rules, ipset entries in ipvsproxier ut.

**Comment by Lion-Wei** [comment]
https://github.com/kubernetes/kubernetes/issues/59662

**Comment by Lion-Wei** [comment]
@islinwb

**Comment by m1093782566** [comment]
What's the current UT coverage number?

**Comment by Lion-Wei** [comment]
Current is 50.2%.

**Comment by m1093782566** [comment]
So, can we achieve 70%?

**Comment by Lion-Wei** [comment]
Yeah, we can do that, and that's definitely necessary.
