### ISSUE TITLE
k8s doesn't pull the image

### ISSUE THREAD

**Issue by M-Ayman** [kubernetes/kubernetes#61398]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I build an image using commit it "git rev-parse --short HEAD". if the output doesn't contain any character "like 1315693", the deployment doesn't pull the image"InvalidImageName"

**What you expected to happen**:
when I change the build tag which contains alphabet it works. I need to pass a short commit id even though it contains an alphabet or not

**Comment by dims** [comment]
@M-Ayman can you please add logs from kubelet? 

/sig node
