### ISSUE TITLE
Regular expressions not working in json-path

### ISSUE THREAD

**Issue by rochdev** [kubernetes/kubernetes#61406]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Trying to use the following json-path expression:

```
kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^test$/)].metadata.name}'
```

resulted in the following error:

```
error: error parsing jsonpath {.items[?(@.metadata.name=~/^test$/)].metadata.name}, unrecognized character in action: U+007E '~'
```

**What you expected to happen**:

Getting the list of secret names that match the regular expression.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
kubectl get secrets -o jsonpath='{.items[?(@.metadata.name=~/^default-/)]}'
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6 (client) / 1.7.12-gke.1 (server)
- Cloud provider or hardware configuration: MacBook Pro
- OS (e.g. from /etc/os-release): MacOS 10.13
- Kernel (e.g. `uname -a`): Darwin MacBook-Pro-3.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by kalote** [comment]
Same issue: I'm trying to get a list of environment variable that have "password" / "credentials" in it for audit purpose but cannot do it with jsonpath.

Any plan on having this feature?

**Comment by parsoFish** [comment]
running into the same problem need a way to find a pod that contains a substring in the name and this functionality seems the right way to do it

**Comment by kalote** [comment]
@parsoFish i've been able to find a solution for my issue (finding password in dc) by using `oc get dc/mydc -o jsonpath='{range .spec.template.spec.containers[*].env[*]}{.name}: {.value}{"\n"}{end}'` and piping the result to `egrep -i \"pass(word)?\"`.

AS the jsonpath output doesn't provide the regex capability, you can just use another tool that does.

**Comment by hognala** [comment]
This is still an issue. Can you fix it? I can't reopen it

**Comment by val1715** [comment]
Get the same issue - Windows 10 + Powershell:
```
PS C:\windows\system32> kubectl get po -n monitoring -o jsonpath="{range .items[*]}{.metadata.name}{`"\n`"}{end}"
error: error parsing jsonpath {range .items[*]}{.metadata.name}{\n}{end}, unrecognized character in action: U+005C '\'
PS C:\windows\system32> kubectl get po -n monitoring -o jsonpath="{range .items[*]}{.metadata.name}{\"\n\"}{end}"
error: error parsing jsonpath {range .items[*]}{.metadata.name}{\\n\}{end}, unrecognized character in action: U+005C '\'
```
use MINGW64 bash for win as trick to avoid this problem. 
Both variants below work fine for me:
`$ kubectl get po -n monitoring -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'`

`$ kubectl get po -n monitoring -o jsonpath="{range .items[*]}{.metadata.name}{\"\n\"}{end}"`

**Comment by jknap** [comment]
Any plans on tackling this one?

**Comment by abritabroad** [comment]
> running into the same problem need a way to find a pod that contains a substring in the name and this functionality seems the right way to do it

considering kubectl jsonpath does not currently support regex, this is a sample script I created to get the logs from a pod:

`serviceName="<your service name>"

podName=$(kubectl get pods -o=jsonpath="{.items[*].metadata.name}" | grep -oP "${serviceName}.*?\s")

kubectl logs ${podName}


`

**Comment by webmutation** [comment]
Are RegEx really not supported?
I am trying to find all deployment that contain a specific string but I am getting an error

```
$ kubectl get deployments -o=jsonpath="{..items[?(@.metadata.name =~ 'prometheus')].metadata.name}"
error: error parsing jsonpath {..items[?(@.metadata.name =~ 'prometheus')].metadata.name}, unrecognized character in action: U+007E '~'
```

**Comment by MatrixManAtYrService** [comment]
As far as I can tell, this is still an issue.

/remove-lifecycle stale

**Comment by mckirk** [comment]
> `error: error parsing jsonpath {range .items[*]}{.metadata.name}{\n}{end}, unrecognized character in action: U+005C '\'`

In case anybody else runs into this problem, the solution for me was to use double quotes around the jsonpath expression and single quotes around the `'\n',` which is also mentioned on the [JSONPath Support](https://kubernetes.io/docs/reference/kubectl/jsonpath/) page:
> On Windows, you must double quote any JSONPath template that contains spaces (not single quote as shown above for bash). This in turn means that you must use a single quote or escaped double quote around any literals in the template.

**Comment by 5Gdreamer** [comment]
> > `error: error parsing jsonpath {range .items[*]}{.metadata.name}{\n}{end}, unrecognized character in action: U+005C '\'`
> 
> In case anybody else runs into this problem and ends up here, the solution for me was to use double quotes around the jsonpath expression and single quotes around the `'\n',` which is also mentioned on the [JSONPath Support](https://kubernetes.io/docs/reference/kubectl/jsonpath/) page (though in a different context):
> 
> > On Windows, you must double quote any JSONPath template that contains spaces (not single quote as shown above for bash). This in turn means that you must use a single quote or escaped double quote around any literals in the template.
> 
> (That solution is also mentioned in the issue linked just above my comment, I just realized.)

Bump, now that is great and helped me out!
