### ISSUE TITLE
DaemonSet scheduling conflates hostname and nodename

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#61410]
/kind bug
/sig scheduling
related to #59194

When the ScheduleDaemonSetPods alpha feature is enabled, the daemonset controller creates pods with affinity terms that depend on the `kubernetes.io/hostname` label on a Node being equal to the node name.

That is *not* a valid assumption. Node name and hostname are distinct and are definitively known to be different in some clusters.

If the DaemonSet wants to use scheduling to assign pods to nodes, it must do so with a scheduling predicate that deterministically resolves to the desired node and only the desired node (e.g. not a label that could match nodes other than the desired node)

**Comment by jberkus** [comment]
Added all the 1.10 labels.

**Comment by liggitt** [comment]
/milestone clear

not 1.10 blocking

**Comment by liggitt** [comment]
> Does this mean that our documentation is not accurate and should be updated?

Nowhere in that documentation does it state the value of that label matches the node name.

> Documentation aside, many users may rely on the node affinity/anti-affinity or node selector features for scheduling. Does this issue imply that none of those features are reliable?

If they are trying to match the hostname label to the node name object, they will be disappointed in many environments.

**Comment by bsalamat** [comment]
> Nowhere in that documentation does it state the value of that label matches the node name.

I think the document should be updated and explicitly state that the value is not necessarily the node name. I would guess that zone, etc. are not reliable either. If so, we should state that as well.

> If they are trying to match the hostname label to the node name object, they will be disappointed in many environments.

This is unfortunate. Something that surprises us, will definitely surprise our user. It causes bad UX. We should update the doc.

**Comment by k82cn** [comment]
Thanks very much, learned 👍 

If so, maybe we can introduce a new label, named `kubernetes.io/nodename`; the label will be updated by kubelet to `.spec.NodeName`.

**Comment by liggitt** [comment]
> maybe we can introduce a new label, named kubernetes.io/nodename; the label will be updated by kubelet to .spec.NodeName.

that seems like a mistake. It can't be trusted (since the kubelet sets it), and there is potential for overlap (two node objects having the same label)

**Comment by liggitt** [comment]
> All node info are set by kubelet, we can trust it

That is not accurate, and is actively being restricted/tightened (see https://github.com/kubernetes/community/pull/911)

Currently, the DaemonSet controller directly assigns pods to nodes. With the Node authorization mode and NodeRestriction admission plugin in place (as they are in many default deployments), that means there is no way for a node other than the assigned node to get access to the secrets/configmaps/volumes referenced by a DaemonSet pod intended for another node. 

If you move to using the scheduler to assign daemonset pods to nodes, the attributes/predicates used by the scheduler must not regress that guarantee. 

Using a label set by a node to determine the identity of a node opens us up to node A claiming it is node B and getting pods intended for node B scheduled to it.

**Comment by liggitt** [comment]
The bigger question is why the scheduler is being asked to pick a node when there is only one correct answer. The hoops we’re having to jump through to use affinity rules to try to pin to a particular node are a symptom of coupling priority enforcement to the node-selection/scheduling step.

**Comment by davidopp** [comment]
> The bigger question is why the scheduler is being asked to pick a node when there is only one correct answer. The hoops we’re having to jump through to use affinity rules to try to pin to a particular node are a symptom of coupling priority enforcement to the node-selection/scheduling step.

There was a long long debate about this (originally we decided not to do it (#42002) but then decided to do it (#59194). There are docs and whatnot mentioned in the latter issue that explain the rationale. In my mind the high-level reason is that DaemonSet is not simply "one instance of this pod on every node" but rather "one instance of this pod on every node that meets the constraints, possibly after preemption." Even without preemption, you start duplicating a lot of logic into the DaemonSet controller, and then with preemption that duplicated logic grows. Having the default scheduler schedule the pods also makes the behavior of DaemonSet scheduling more obvious, e.g. if you want DaemonSets to schedule on nodes that have certain conditions or problems, you represent that with an explicit toleration rather than just baking it into the DaemonSet controller logic. [When DaemonSet was originally being considered, I argued we should not even have a separate API object and controller, we should just have a special replicas=-1 value in ReplicaSet that gives you the per-node behavior, but that's another story.]

So I think we need to find a way to make this work. Unfortunately I forgot how NodeName works. You can set it in the PodSpec (as the API server does when the scheduler requests a binding), but how do you know the NodeName of a node? It does not appear to be in the NodeSpec or NodeStatus, as far as I can tell, and we already established that it is not a label on the Node.

**Comment by liggitt** [comment]
> how do you know the NodeName of a node

It's the metadata.name

**Comment by davidopp** [comment]
Oh, regarding my last paragraph, I guess it is just the metadata.name of the Node object itself?

Can we have the API server (maybe an admission controller) populate the hypothesized kubernetes.io/nodename label when the node is created?

**Comment by liggitt** [comment]
if we want a way to indicate affinity to a specific named node, we should actually enable that, not overload a special label on one object

**Comment by davidopp** [comment]
Like a new RequestedNodeName field in the PodSpec? That's conceivable but seems kind heavyweight. What's the objection to using a label, as long as the master sets it?

**Comment by liggitt** [comment]
> What's the objection to using a label, as long as the master sets it?

That's the objection. It's overloading unstructured labels as an API because they're convenient.

**Comment by k82cn** [comment]
There's is the [motivation](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/schedule-DS-pod-by-scheduler.md#motivation) for this feature.

An API seems heavy: not only a new API field, but also predicates (or others) enhancement for it. And it can not be re-used, e.g. both node selector, NodeAffinity can use labels.

> That is not accurate, and self-reported node info is actively being restricted/tightened in 1.11 (see kubernetes/community#911)

Oh, yes, some taints are also updated by NodeController. IMO, some node info must be updated by `kubelet` instead of other component, e.g. hostname, nodename, conditions.

**Comment by mtaufen** [comment]
This is tangentially related: https://github.com/kubernetes/kubernetes/pull/61042

**Comment by k82cn** [comment]
> If we require guaranteed assignment to a particular node  ...

`predicates` will guarantee that. If there's only one candidate for nodeSelector/NodeAffinity, kube-scheduler will bind pod to it (if also passing other predicates). This's a valid case for nodeSelector/NodeAffinity :)

Also thinking the new field solution recently, it's just a different way of description to me: `.RequestedNodeName` vs. `NodeAffinity{ hostname in target}`; the other logic are similar, so prefer to use NodeAffinity + NodeName label :)

For such kind of labels, it should be: 1. reserved for k8s, 2. only updated by special components

> the kubelet doesn't get to choose or update its node name, it just gets permissions to create/update status for a node with a particular name, based on its credentials

Who will create Node object in api server?

**Comment by liggitt** [comment]
> predicates will guarantee that

A label selector predicate doesn't select a single node, it selects a set of nodes. Hoping multiple nodes don't match that label isn't a guarantee. 

> For such kind of labels, it should be: 1. reserved for k8s, 2. only updated by special components

That approach:
* duplicates the node name (immutable) into a label (mutable and uncontrolled)
* does not use the existing selection mechanism that *can* select by name (field selector on metadata.name)
* requires enforcing this label's value be unique or DaemonSets break
* requires preventing any component from setting a different value for that label or DaemonSets break

> Who will create Node object in api server?

The kubelet currently does, but is only authorized to create the node whose name matches its credential

**Comment by smarterclayton** [comment]
Labels are not names and vice versa.  The real gap here seems to be that we are trying to elicit a scheduling side effect (preemption) from a monolithic scheduler by emulating a scheduling decision.  An affinity predicate seems much more appropriate than abusing labels.

**Comment by smarterclayton** [comment]
We have repeatedly that labels cannot map arbitrary data - a predicate can, so it’s not clear to me why you don’t add one?

**Comment by smarterclayton** [comment]
By predicate I meant “affinity rule”

**Comment by smarterclayton** [comment]
```
nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchField:
          - key: metadata.name
            operator: In
            values:
            - nodename
```

**Comment by smarterclayton** [comment]
Could be “nodeFieldTerms” or similar

**Comment by smarterclayton** [comment]
(As I’m thinking about this more)

Resources are a constraint to the scheduler but we don’t model them as labels, same for tolerations, same for host ports and pvcs.  From an API perspective:

1. this is a pretty specific use case
2. We shouldn’t abuse labels to represent things that aren’t labels
3. Labels are arbitrary topology
4. Node affinity defines general purpose constraints on topology
5. We don’t take other fields and turn them into labels

I see no reason why we can’t add a node affinity constraint for node name or other fields in the future that are of limited scope but valuable use.  Schedulers aren’t required to honor constraints, so a scheduler could decide it doesn’t like your tolerations as much as it could decide to ignore your node affinity.

**Comment by k82cn** [comment]
`node affinity constraint` seems better than a new field `.RequestedNodeName` in `PodSpec` :).

 @bsalamat , does this make sense to you?

/cc @davidopp

**Comment by bsalamat** [comment]
I agree with @liggitt and @smarterclayton's points.
Similar to what @smarterclayton [suggested](https://github.com/kubernetes/kubernetes/issues/61410#issuecomment-377092833) we can add a new field to [NodeSelectorTerm](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2274) to match against node name. I would not make this field matchable against any field in the Node object though. More specifically, I would avoid adding a selector that requires reflections to find the field in the Node object. It would be an overkill and a performance killer with very limited use-cases.

**Comment by smarterclayton** [comment]
We don’t actually use reflection on the others, we just use a general purpose api design.  Ie downward api and others are consistent with that.  However, having a specific oneof style matches for nodeName works just as well.  I might advise to consider letting it be an array for future extension, but that’s only if we envision a use case for it.

**Comment by bsalamat** [comment]
> We don’t actually use reflection on the others, we just use a general purpose api design. Ie downward api and others are consistent with that.

Could you elaborate on this? I thought 'metadata.name' which is provided in front of 'key' in [your comment](https://github.com/kubernetes/kubernetes/issues/61410#issuecomment-377092833) was just a string that could match any field of the Node object.

**Comment by k82cn** [comment]
Such kind of map is enough for us:

```go
fieldKey := map[string] func(*v1.Pod)string {
 "spec.nodeName": func(pod *v1.Pod) string {return pod.Spec.NodeName},
}
```

**Comment by bsalamat** [comment]
> Unless you anticipate other fields on pod being relevant just having a
specific term for `nodeName` or `nodeNames` is probably simpler.

Yes. If we want to follow the same switch statement model, the selector can match only the hardcoded fields as opposed to a reflection model that could match any field, including those that are added in the future. Since we do not want to use reflection, I agree that we should use `nodeNames` for now.

**Comment by davidopp** [comment]
Sounds reasonable to me.

**Comment by k82cn** [comment]
/close

All related PRs were merged :)
