### ISSUE TITLE
Promote encryption at rest with static configs to beta

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#61420]
Ref https://github.com/kubernetes/features/issues/460
Ref https://groups.google.com/d/msg/kubernetes-sig-api-machinery/J8vW9m8A-t4/JJ9BRFVUCQAJ

> > The static config encryption will also alpha in 1.10 since I don't believe its versioned separately from the other KMS options. Maybe someone else here can speak to that part of the feature? I haven't seen much discussion about what it would take to bring the static key encryption out of alpha.
>
> Probably just sufficient feedback that static config is working for people.  I know of a few shops running with this for quite a while, so probably it's time to push it over the edge.

ref https://github.com/kubernetes/features/issues/92

/sig auth
/kind feature
/milestone v1.11
/priority important-longterm
/status approved-for-milestone

cc @php-coder

**Comment by php-coder** [comment]
What's need to be done here? I can think only about renaming `--experimental-encryption-provider-config` to `--encryption-provider-config` and updating the docs. What else?

**Comment by php-coder** [comment]
> What's need to be done here? I can think only about renaming --experimental-encryption-provider-config to --encryption-provider-config and updating the docs. What else?

@liggitt @smarterclayton What's required to promote encryption at rest with static configs to beta?

**Comment by ericchiang** [comment]
@php-coder an example of promoting flags is here: https://github.com/kubernetes/kubernetes/pull/51198

If there's a feature gate, we're going to want to enable it by default too.

**Comment by php-coder** [comment]
@marrrvin submitted PRs for that: https://github.com/kubernetes/kubernetes/pull/61592 and https://github.com/kubernetes/website/pull/7823

**Comment by mayakacz** [comment]
Will this make it to Beta in 1.12?
From sig-auth on 7/11, it sounded like this was missing a release shepherd. Is anyone owning pushing this forward?

**Comment by php-coder** [comment]
@stlaz

**Comment by stlaz** [comment]
@mayakacz I'll do my best to push this.

**Comment by mayakacz** [comment]
Ack - that's what I was wondering (with the feature freeze).
Thanks @stlaz

**Comment by yastij** [comment]
@php-coder @stlaz - Is this making it to the 1.12 ?

**Comment by stlaz** [comment]
@yastij The current plan is 1.13
