### ISSUE TITLE
kubernetes web ui: Unable to access the dashboard 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes/kubernetes#61426]
Hi,
I have deployed the kubernetes multimode cluster on the centos 7 boxes. one master and another worker. 
all the services are running fine .. 

> [root@centos-master ~]# kubectl cluster-info
> Kubernetes master is running at https://10.0.7.6:6443
> KubeDNS is running at https://10.0.7.6:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
> 
> To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
> [root@centos-master ~]#
> 

now the issue is with UI dashboard. I did following steps to configure the UI using doc : https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above

> [root@centos-master ~]# kubectl -n kube-system get service kubernetes-dashboard
> NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
> kubernetes-dashboard   NodePort   10.100.231.57   <none>        443:32322/TCP   4d
> [root@centos-master ~]#

from another machine which is windows box, I tried accessing following URLs

> http://<<master_server_ip >>:32322/ui
> http://<<master_server_ip >>:32322
> https://<<master_ip>>:<apiserver_port>/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
> http://<<master_server_ip>>:8001/ui

but none of them are working ... I am not getting what is missing configuration ...
the version of the kubernetes is : 1.9.3 
Can you please give me some pointers , how to troubleshoot and debug further ?
Thanks ....

**Comment by irfanjs** [comment]
please suggest ....

**Comment by irfanjs** [comment]
i tried reading docs from different sites .. however not able to resolve the issue. can someone please give some pointers / direction please ?...

**Comment by jfpucheu** [comment]
Which network pluggin are you using?
 I have the same type of pb with calico but works with Flannel.

Jeff
