### ISSUE TITLE
Migrate kubectl to use apps/v1 instead of extensions/v1beta1

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#61430]
In 1.9, `apps/v1` is introduced, and `extensions/v1beta1`, `apps/v1beta1` and `apps/v1beta2` are deprecated. 

We need to migrate kubectl to use `apps/v1` by default. This includes (but isn't limited to):

### client-side change
- [x] `kubectl create deployment` (#61288)
- [x] `kubectl run` (#61288)
- [x] `kubectl rollout` (#61419)

### server-side change
These commands use the server-preferred order, which will prefer the `extensions` API group for compatibility until `extensions` is removed.
- [ ] `kubectl get`
- [ ] `kubectl explain` 

@kubernetes/sig-cli-maintainers @kubernetes/sig-apps-misc

**Comment by liggitt** [comment]
`get` and `create` use whatever manifest is provided

**Comment by scriptonist** [comment]
Is this a beginner friendly issue? If so can I try to do this?

**Comment by soltysh** [comment]
> not sure about rollout (I think it is hard-coded and should be updated)

From what I've checked in the code, it's also using the resource builder, so that means it'll work similarly to get. 

> run can create a new generator that produces apps/v1 objects (and prefer that if running against a server with apps/v1 available) - in progress in #61288

:+1: 

What about `kubectl create deployment`?

**Comment by janetkuo** [comment]
> What about `kubectl create deployment`?

Yeah, I wasn't clear before. I meant `kubectl create deployment`, not `kubectl create -f`.

**Comment by janetkuo** [comment]
@scriptonist thanks! You could start from adding a apps/v1 Deployment generator, that would benefit both `kubectl create deployment` and `kubectl run`. 

Ref previous PR for adding apps/v1beta1 Deployment generator: #42362 (see the 2nd commit `Introduce new generator for apps/v1beta1 deployments`). The change should be pretty similar. 

Feel free to tag me or @soltysh if you have questions!

**Comment by janetkuo** [comment]
@scriptonist I just realized someone is already working on adding apps/v1 Deployment generator: #61288

**Comment by ayushpateria** [comment]
@janetkuo @soltysh [#61288](https://github.com/kubernetes/kubernetes/pull/61288) takes care of `kubectl create deployment` as well.

**Comment by janetkuo** [comment]
Thanks! #61419 takes care of `kubectl rollout`

**Comment by liggitt** [comment]
there's actually no kubectl work remaining for this item. remaining items are tracked in https://github.com/kubernetes/kubernetes/issues/43214

**Comment by liggitt** [comment]
kubectl work on this is complete, green CI with the extensions/v1beta1 resources disabled [required no kubectl changes](https://github.com/kubernetes/kubernetes/pull/70672)

/close
