### ISSUE TITLE
Warn about deletion of cluster wide resources with namespace flag

### ISSUE THREAD

**Issue by Fattouche** [kubernetes/kubernetes#61431]
/kind feature
/sig cli

**What happened**:
Executing `kubectl delete crd <mycrd> -n <some-namespace>` proceeds to delete the crd even though the docs say `CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces.` 

**What you expected to happen**:
I would expect some warning or error which says something like `crd are non-namespaced, remove namespace flag to proceed`

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl delete crd <test-crd> -n <test-namespace>`

@kubernetes/sig-cli-feature-requests

**Comment by liggitt** [comment]
the namespace flag is a global flag, is used when working with namespaced resources, and is ignored when working with cluster-scoped resources. this behavior must be preserved for backwards compatibility.

notably, you can also mix namespaced and non-namespaced resources in a single command: `kubectl get nodes,pods -n kube-system`... the namespace is used for getting the pods, and not used for getting the nodes.

/close
