### ISSUE TITLE
GETting pod logs through API with Accept: application/json returns text which is invalid json; text/plain not allowed.

### ISSUE THREAD

**Issue by NickPollard** [kubernetes/kubernetes#61450]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When trying to get pod logs through the api with `Accept: application/json`, the returned value is not valid JSON. The value should be a string, which in JSON needs to be quoted. The returned value is not quoted, which means it cannot be parsed as JSON.

This means, for example, that the Haskell Bindings in https://github.com/kubernetes-client/haskell which I was using cannot access logs, as they will always result in a parse error.

Moreover, the result - which looks like simple text - cannot be pulled as `text/plain` as the Kubernetes cluster responds that only `application/json`, `application/yaml` and `application/vnd.kubernetes.protobuf` are allowed.

**What you expected to happen**:
I expect that when `GET`ting with `Accept: application/json` for pod logs, the result should be valid JSON. Also, when returning just text, `text/plain` should be an allowed content type.

**How to reproduce it (as minimally and precisely as possible)**:
To see invalid JSON:
`curl [host:port]/api/v1/namespaces/[namespace]/pods/[pod]/log -H "Accept: application/json"`
To see text/plain disallowed:
`curl [host:port]/api/v1/namespaces/[namespace]/pods/[pod]/log -H "Accept: text/plain"`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
minikube version: v0.25.0

**Comment by lavalamp** [comment]
/sig node

Sounds like it should be one or the other. Adding the node SIG also, it's not clear if this is a defect in the machinery or the API.

**Comment by yliaog** [comment]
logs handling is done in kubelet, kube-apiserver just returns whatever is returned from kubelet.

below is the link to the code in kubelet regarding logs:
https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=GetKubeletContainerLogs&type=

https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=GetContainerLogs&type=

In one case, it just asks docker to return the logs for the container (https://github.com/kubernetes/kubernetes/blob/317853c90c674920bfbbdac54fe66092ddc9f15f/pkg/kubelet/dockershim/docker_legacy_service.go#L83)

Even though docker stores the log as json on disk, it returns plain text when calling docker logs <container id>
$ sudo cat /var/lib/docker/containers/d0d4f10eaf4888421618cd3fbabe2d11e76aa3e95c37a86dbab7d1fe95508062/d0d4f10eaf4888421618cd3fbabe2d11e76aa3e95c37a86dbab7d1fe955>
{"log":"10.4.0.1 - - [29/Mar/2018:17:42:00 +0000] \"GET / HTTP/1.1\" 200 612 \"-\" \"curl/7.38.0\" \"-\"\n","stream":"stdout","time":"2018-03-29T17:42:00.959147799Z"}

$ docker logs d0d4f10eaf48
10.4.0.1 - - [29/Mar/2018:17:42:00 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.38.0" "
