### ISSUE TITLE
REST api - why PodTemplate isn't required to have metadata?

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#6145]
PodTemplate (currently part of replication controller) has metadata as omitempty. 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L778

The metadata itself has important fields such as uid/name, etc, that can be used to distinguish one object from another, but if they are not present, then the client needs to sometimes extract name from labels (if present there at all), and it makes the whole work with pod template more complicated and error prone.

What is the reason for omitempty on metadata (being able not to have mandatory fields), and why is it set like this on pod template?

**Comment by davidopp** [comment]
@bgrant0607 can you clarify how we're using "omitempty" in pkg/api/types.go? It seems that nearly every field in the API is omitempty. The comment in pkg/client/clientcmd/api/types.go says `Top level config objects and all values required for proper functioning are not "omitempty".  Any truly optional piece of config is allowed to be omitted.` But it's not obvious to me that "omitempty" means "semantically optional" in pkg/api/types.go. For example, PodSpec in Pod is omitempty, but a pod is meaningless without a spec.

**Comment by abonas** [comment]
@bgrant0607 ?

**Comment by bgrant0607** [comment]
omitempty should imply optional, but the types may be used in more than one context, and I could also believe that it isn't used correctly in many places. Though a number of fields may be filled in automatically, I can't think of a good reason for metadata to be completely absent from a top-level object. Either name or generateName needs to be provided.

Don't look at pkg/api/types.go. That shouldn't even have json tags at all.

I didn't review pkg/client/clientcmd/api/types.go. At minimum, it's incorrectly serializing an unversioned representation.

BTW, I get ~300 emails a day from github. Try IRC if you have a quick question.

**Comment by abonas** [comment]
> Don't look at pkg/api/types.go. That shouldn't even have json tags at all.
> 

@bgrant0607 
So where should one look when inconsistent/unclear things come up with the api?

> I didn't review pkg/client/clientcmd/api/types.go. At minimum, it's incorrectly serializing an unversioned representation.

My original question though still stands :) - why isn't pod template required to have metadata (its on uid and name?) Is it a bug?

**Comment by kargakis** [comment]
I don't think it's a bug. Currently all of the instances of a PodTemplate can be found inlined into resources such as ReplicaSets, Deployments, StatefulSets, etc. and we cannot require from users to set object meta because most of them are going to be generated in master (api server, controller manager) at the creation time of owned Pods.
