### ISSUE TITLE
hostPath volume with subPath volume mount does not work with containerized kubelets

### ISSUE THREAD

**Issue by karataliu** [kubernetes/kubernetes#61456]
**Fix status:**
- [ ] Fix development in progress for master branch
- [ ] Fix for release-1.10 branch pending completion of master branch fix
- [ ] Fix for release-1.9 branch pending completion of master branch fix
- [ ] Fix for release-1.8 branch pending completion of master branch fix
- [ ] Fix for release-1.7 branch pending completion of master branch fix

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
With following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: hp
spec:
  containers:
  - image: nginx
    name: hp1
    volumeMounts:
    - mountPath: /test-pd
      subPath: m1
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp
```
With k8s v1.10.0-beta.0, it will create '/tmp/m1' on host agent, and mount to the pod container. Inside the container, if creating a file under '/test-pd', the file will appear in /tmp/m1 of host agent. This looks good.

With k8s v1.10.0-beta.4, no dir will be created under '/tmp' on host agent. And if create some file under '/test-pd', the file will appear in '/var/lib/docker/overlay2/{id}/diff/tmp/m1'.

The mount output for two versions:

- v1.10.0-beta.0
Inside container:
```
# mount |grep test-pd
/dev/sda1 on /test-pd type ext4 (rw,relatime,discard,data=ordered)
```

- v1.10.0-beta.4
Inside container:
```
# mount |grep test-pd
overlay on /test-pd type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/CWJ5CIKPXWKFO3IUAXUUSKBYKW:/var/lib/docker/overlay2/l/JU4V2IT3H2PDJH2UZH6GT3QMNQ:/var/lib/docker/overlay2/l/3PAY56CXYE6E2XJ6F54DZGYN2J:/var/lib/docker/overlay2/l/LZXQK45MQSY3JXCYS4TGR5C3ZN:/var/lib/docker/overlay2/l/TKPK6O3B4JA7DFE7E56B256KNS:/var/lib/docker/overlay2/l/NQLMB3ZLZ2XKPGKWG75T54UUXP:/var/lib/docker/overlay2/l/KOZYE6745J23T5T6ZOHZPUXXHL:/var/lib/docker/overlay2/l/SBWQYRHZ57TZMSH4HJ3EVYJVR2:/var/lib/docker/overlay2/l/CHXJUW26W2TRZ4DCWGS64GN4CN,upperdir=/var/lib/docker/overlay2/96acfb05025b8aa34fb28f33ae9dc684b4cbb09f670507e2b8d176feea66a5de/diff,workdir=/var/lib/docker/overlay2/96acfb05025b8aa34fb28f33ae9dc684b4cbb09f670507e2b8d176feea66a5de/work)
```

**What you expected to happen**:
The subpath to be created under volume root.

**How to reproduce it (as minimally and precisely as possible)**:
Create the pod with given spec.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.4", GitCommit:"a2dacb6f846e9d64d02c5dc5ab3972287d337405", GitTreeState:"clean", BuildDate:"2018-03-14T05:45:34Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by karataliu** [comment]
Verified this also fails on v1.10.0-beta.3 and v1.10.0-rc.1

**Comment by andyzhangx** [comment]
if you attach to the agent kubelet, you will find actually mkdir actually happens in kubelet container, while since there is no volume mapping in kubelet, so the mkdir operation does not work in hostpath.

**Comment by andyzhangx** [comment]
kubelet on Azure would run as a continer, and this issue should be related to ["bind mount" code](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L799-L803), so I don't use "bind mount", use original code, it works well.

**Comment by andyzhangx** [comment]
I think I got the root cause why subPath in hostPath volume does not work, this issue should only happen for **containerized kubelet**, 
 [SafeMakeDir](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L230) in kubelet would make subpath directories, if `kubelet` is running directly in host, it would work, while for **containerized kubelet**, SafeMakeDir only makes directories in kubelet container, it's useless. 
Before this subpath security fix, actually docker will make subpath directories itself, while with this subpath security fix, in Linux, the subPath dir will be "bind mount" to dir like `/var/lib/kubelet/pods/...`, so finally docker will create subPath dir in `/var/lib/kubelet/pods/...` other than `/tmp` in the above example.

In one word, this subpath security fix has broken subPath functionality in hostPath volume for **containerized kubelet**

**Comment by msau42** [comment]
Is it a safe assumption to make that in all containerized kubelet environments, the host's "/" is mounted into the kubelet container under "/rootfs"?

**Comment by msau42** [comment]
I see that nsenter code is assuming that, so the fix will probably have to do something similar.

**Comment by msau42** [comment]
@karataliu can you explain why you need to use subPath with a hostPath volume?  Can you just pass in the entire path "/tmp/m1" path as a hostPath?

**Comment by karataliu** [comment]
@msau42 No specific reason, I was trying e2e case `HostPath should support subPath` and found this.

**Comment by andyzhangx** [comment]
@msau42 If we don't use subPath in hostPath volume in containerized kubelet, it works. 

Below is containerized kubelet config on Azure, the host's "/" is not mounted into kubelet container:

```
ExecStart=/usr/bin/docker run \
  --net=host \
  --pid=host \
  --privileged \
  --rm \
  --volume=/dev:/dev \
  --volume=/sys:/sys:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/var/lib/cni/:/var/lib/cni:rw \
  --volume=/sbin/d/:/sbin/d:rw \
  --volume=/var/lib/docker/:/var/lib/docker:rw \
  --volume=/var/lib/containers/:/var/lib/containers:rw \
  --volume=/var/lib/kubelet/:/var/lib/kubelet:shared \
  --volume=/var/log:/var/log:rw \
  --volume=/etc/kubernetes/:/etc/kubernetes:ro \
  --volume=/srv/kubernetes/:/srv/kubernetes:ro $DOCKER_OPTS \
  --volume=/var/lib/waagent/ManagedIdentity-Settings:/var/lib/waagent/ManagedIdentity-Settings:ro \
  --volume=/etc/kubernetes/volumeplugins:/etc/kubernetes/volumeplugins:rw \
    ${KUBELET_IMAGE} \
      /hyperkube kubelet \
        --enable-server \
        --node-labels="${KUBELET_NODE_LABELS}" \
        --v=2 \
        --non-masquerade-cidr=${KUBELET_NON_MASQUERADE_CIDR} \
        --volume-plugin-dir=/etc/kubernetes/volumeplugins \
        $KUBELET_CONFIG $KUBELET_OPTS \
        ${KUBELET_REGISTER_NODE} ${KUBELET_REGISTER_WITH_TAINTS}
```

**Comment by andyzhangx** [comment]
@msau42 also   `--volume=/:/rootfs` shoud not work, since `/rootfs/tmp` and `/tmp` are not identical in kubelet container, while we cannot specify like this `--volume=/:/`, it's not supported.

**Comment by rootfs** [comment]
@andyzhangx we need `-v /:/rootfs`.  nsenter uses host mount namespace (i.e. `/rootfs/proc/1/ns/mount`) to use resolve the directory on the host.

**Comment by andyzhangx** [comment]
@rootfs I mean `--volume=/:/rootfs` does not work in this case which is for containerized kubelet, in the example hostPath is `/tmp`, in a containerized kubelet, we cannot mkdir on `/tmp` on host. Let hostPath to use "bind mount" to "/var/lib/kubelet" would work.

**Comment by msau42** [comment]
While I think changing hostpath to bind mount to /var/lib/kubelet is the right solution, I think it is too risky to do for patch releases because it impacts more than just the subpath feature.  So, I would prefer to look into that change for 1.11, and do a targeted patch for this specific issue using the "unsafe bind mount and validate fstat afterwards" approach.

**Comment by feiskyer** [comment]
The hostPath+subPath is actually also not working for previous versions (e.g. all v1.9.x). e.g. replacing above examples with any hostPath not existing inside kubelet container. In such case, kubelet is validating the hostPath inside its running container (fail since it doesn't exist), while the expected hostPath is on the node.

**Comment by andyzhangx** [comment]
@feiskyer it's not correct, hostPath+subPath is working on v1.9.3, I just tried. kubelet will only check whether subPath exists, if not, mkdir subPath in kubelet, related code is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L222-L242). Without the security path, finally docker will mkdir full subPath in host for containerized kubelet.

**Comment by andyzhangx** [comment]
@msau42 just loop me in for this PR, thanks.

**Comment by feiskyer** [comment]
@andyzhangx hostPath is validated first (this is in container for containerized kubelet), see https://github.com/kubernetes/kubernetes/blob/d2835416544f298c919e2ead3be3d0864b52323b/pkg/kubelet/kubelet_pods.go#L207-L210

**Comment by andyzhangx** [comment]
@feiskyer You are right, we happened to use same dir, e.g. /tmp, /mnt which exists on both kubelet container and host, if I use hostPath like `/andy`, we will get error like following:
```
Events:
  Type     Reason                 Age               From                               Message
  ----     ------                 ----              ----                               -------
  Normal   Scheduled              57s               default-scheduler                  Successfully assigned nginx-subpath to k8s-agentpool-39280284-0
  Normal   SuccessfulMountVolume  57s               kubelet, k8s-agentpool-39280284-0  MountVolume.SetUp succeeded for volume "test-volume"
  Normal   SuccessfulMountVolume  57s               kubelet, k8s-agentpool-39280284-0  MountVolume.SetUp succeeded for volume "default-token-ts2ts"
  Normal   SandboxChanged         52s               kubelet, k8s-agentpool-39280284-0  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                8s (x6 over 56s)  kubelet, k8s-agentpool-39280284-0  pulling image "nginx"
  Normal   Pulled                 6s (x6 over 53s)  kubelet, k8s-agentpool-39280284-0  Successfully pulled image "nginx"
  Warning  Failed                 6s (x6 over 53s)  kubelet, k8s-agentpool-39280284-0  Error: lstat /andy: no such file or directory
```

So with contianerized kubelet, only following hostPath+subPath are supported before security path, it's quite tricky:
```
root@k8s-agentpool-39280284-0:/# ls -lt
total 245212
drwxr-xr-x  29 root root      1360 Mar 23 12:12 run
drwx------   1 root root      4096 Mar 23 12:11 root
dr-xr-xr-x  12 root root         0 Mar 23 12:11 sys
drwxr-xr-x   1 root root      4096 Mar 23 10:47 mnt
drwxr-xr-x  15 root root      3940 Mar 14 01:32 dev
drwxr-x---   3 root root      4096 Mar  9 13:46 tmpblobfuse
drwxr-xr-x   1 root root      4096 Mar  8 03:56 etc
drwxr-xr-x   1 root root      4096 Mar  8 03:56 sbin
drwxr-xr-x   1 root root      4096 Mar  8 03:56 srv
dr-xr-xr-x 218 root root         0 Mar  8 03:53 proc
lrwxrwxrwx   1 root root        10 Feb  7 13:04 aggerator -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 apiserver -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 controller-manager -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 kubectl -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 kubelet -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 proxy -> /hyperkube
lrwxrwxrwx   1 root root        10 Feb  7 13:04 scheduler -> /hyperkube
-rwxr-xr-x   1 root root 251020864 Feb  7 13:04 hyperkube
drwxr-xr-x   1 root root      4096 Nov 29 00:58 opt
drwxrwxrwt   1 root root      4096 Nov 29 00:58 tmp
drwxr-xr-x   1 root root      4096 Nov 29 00:58 bin
drwxr-xr-x   1 root root      4096 Nov 29 00:58 lib
drwxr-xr-x   1 root root      4096 Nov 29 00:58 usr
drwxr-xr-x   1 root root      4096 Nov 29 00:58 var
drwxr-xr-x   2 root root      4096 Oct  9 00:00 lib64
drwxr-xr-x   2 root root      4096 Oct  9 00:00 media
drwxr-xr-x   2 root root      4096 Jul 13  2017 boot
drwxr-xr-x   2 root root      4096 Jul 13  2017 home
```

It's more like a hostPath+subPath issue for containerized kubelet, this security patch just expose this issue more obviously. Anyway, I aggree with @msau42 **changing hostpath to bind mount to /var/lib/kubelet is the right solution**

**Comment by jaskirat8** [comment]
as per @andyzhangx comment, the listed paths work with subpath but only with parent directories matching.
we cannot have 

      volumes:
      - name: postgres-data
        hostPath: 
          path: /mnt/datafiles/

and use 

      containers:
      - name: postgres
        image: postgres:9.6.13
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data/"
          name: postgres-data
          subPath: postgresdata

As we still gets same error when in containerized kublets.

Since subPaths do not work with nesting hence having it like this

      volumes:
      - name: postgres-data
        hostPath: 
          path: /mnt/

and in container like this

      containers:
      - name: postgres
        image: postgres:9.6.13
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data/"
          name: postgres-data
          subPath: datafiles/postgresdata

causes kublet to allocate new space under /var/lib/kublet/
