### ISSUE TITLE
why do we want to refactor the plumbing to provide the information in the APIGroupInfo?

### ISSUE THREAD

**Issue by lcfang** [kubernetes/kubernetes#61469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

As I saw so many TODO like this:
[https://github.com/kubernetes/kubernetes/blob/a7d788d91f60d676c3a88ab90bca0b3e90f70d53/pkg/registry/autoscaling/rest/storage_autoscaling.go#L36-L47](https://github.com/kubernetes/kubernetes/blob/a7d788d91f60d676c3a88ab90bca0b3e90f70d53/pkg/registry/autoscaling/rest/storage_autoscaling.go#L36-L47)

I wonder why we want to refactor it, too redundancy? And I also hope to know the effect we want.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by deads2k** [comment]
> I wonder why we want to refactor it, too redundancy? And I also hope to know the effect we want.

The information we want is about priorities.  Which versions have priority over which other versions.  That knowledge is held by the same person modifying the `NewRESTStorage` method.  It would be good find a way to formalize it without causing weird dependencies.

**Comment by deads2k** [comment]
On the other hand, it probably matters less if we're willing to prevent new groups from being added to the  kube-apiserver.

**Comment by lcfang** [comment]
Hi @deads2k , Thanks for your attention. 
Do you have any idea about the priority? Shouldn't the `v1` has more priority than others?

**Comment by deads2k** [comment]
> Hi @deads2k , Thanks for your attention.
> Do you have any idea about the priority? Shouldn't the v1 has more priority than others?

Yes.  You can see a general pattern emerging here.  https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/aggregator.go#L213-L246
