### ISSUE TITLE
[job failed][1.10] ci-kubernetes-e2e-kubeadm-gce-1-9-on-1-10

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/kubernetes#61483]
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gce-kubeadm-1.9-on-1.10

/kind bug
/sig cluster-lifecycle
/milestone v1.10
/priority failing-test

cc @jdumars @tpepper @jberkus 

also cc @luxas @BenTheElder @jessicaochen @timothysc 
should this even be in 1.10 blocking dashboard?

**Comment by krzyzacy** [comment]
/priority critical-urgent

(who owns this?)

**Comment by krzyzacy** [comment]
(also https://k8s-testgrid.appspot.com/sig-release-1.10-all#gce-kubeadm-upgrade-1.9-1.10)

**Comment by BenTheElder** [comment]
It looks like it's failing to up the cluster, I don't remember what the previous status of this job was, I thought all kubeadm 1.10 jobs were running previously...

**Comment by timothysc** [comment]
The reason this failed was the cross CI job was failing to push the images that are used by that job. 

/cc @dims

**Comment by dims** [comment]
the latest cross build for 1.9 is as following
```
[dims@dims-mac 18:48] ~/Downloads ⟩ gsutil cat gs://kubernetes-release-dev/ci-cross/latest-1.9.txt
v1.9.0-alpha.3.142+a82460d772b94e
```

We seem to have only one job that does cross builds on master : 
https://k8s-code.appspot.com/?q=ci.*kubernetes.*cross.*build&i=nope&files=&repos=test-infra

So the job fails ( for example in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-9-on-1-10/242/artifacts/e2e-242-b2110-master/serial-1.log )

```
May  5 20:07:25 e2e-242-b2110-master startup-script: INFO startup-script: Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-preflight-errors=all
May  5 20:07:25 e2e-242-b2110-master startup-script: INFO startup-script: this version of kubeadm only supports deploying clusters with the control plane version >= 1.9.0. Current version: v1.9.0-alpha.3.142+a82460d772b94e
```
