### ISSUE TITLE
Large clusters failing to come up due to NetworkUnavailable for nodes

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#61481]
Just noticed that the latest runs of our 5k-node correctness (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/88) and performance (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/127) jobs failed during cluster creation due to many nodes being unready.

Those nodes seems unready due to `NetworkUnavailable` condition and from one such node's [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/127/artifacts/gce-scale-cluster-minion-group-10nx/kubelet.log), I'm seeing such errors continuously:

```
E0321 08:19:47.409080    1615 kubelet.go:2134] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
E0321 08:19:52.411336    1615 kubelet.go:2134] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```

FMU the cidr allocation is not happening properly for some reason (note that we're using IP-aliases for those clusters, so cloud-cidr-allocator is the one incharge for allocating them).

Let me dig up deeper.
/assign

cc @kubernetes/sig-network-bugs @kubernetes/sig-scalability-misc @wojtek-t @bowei

**Comment by shyamjvs** [comment]
We might wait for one more run to ensure it wasn't a flake, but my strong feeling is that it's a regression.
Also I quickly swept through the diff (https://github.com/kubernetes/kubernetes/compare/ebae09e74...025439988) and find the following PR most suspicious:

check taints when allocating CIDR for the cloud #59208

**Comment by shyamjvs** [comment]
cc @gmarek @bowei 

I'm not sure IIUC, but it smells like that PR introduces a correctness bug.
That change seems to modify behaviour of the allocator in the case when "node has PodCIDR set, but 'NetworkReady' node-condition was not set".
We would never ever process such a node because the taint exists, and the taint would continue to exist because we never ever process the node.

Notice the comment right above that code which says:

```
// Even if PodCIDR is assigned, but NetworkUnavailable condition is
// set to true, we need to process the node to set the condition.
```

So IIUC we should enter that "if" condition even when the taint exists. Because only then would we be able to update the networkReady condition.

**Comment by shyamjvs** [comment]
In case it wasn't clear earlier:
- Assume a node was assigned podCIDR, but it failed to update the NetworkUnavailable condition
- Next when we trigger the Update() handler for shared informer for that node, we find that the 'NetworkUnavailable' taint exists and hence don't call `AllocateOrOccupyCIDR`
- So the node doesn't get put in the `nodeUpdateChannel` and consequently doesn't get a chance to get its condition updated
- So the node remains with NetworkUnavailable condition, and IIUC that means that the taint also doesn't get removed (by whoever is responsible for removing it)

The above will keep the node unready forever (if it failed to update NodeCondition right after assigning podCIDR).

**Comment by jberkus** [comment]
@shyamjvs is this resolved now?

**Comment by shyamjvs** [comment]
Yes, at least I observe our 2k-node cluster came up successfully in [this run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/72) from yesterday. Should've likely fixed 5k too. If not, we can reopen this.
