### ISSUE TITLE
e2e dns tests fail with cluster-domain other than cluster.local

### ISSUE THREAD

**Issue by mattlandis** [kubernetes/kubernetes#61488]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When running e2e tests on a cluster with the --cluster-domain set the dns tests fail. 
```
[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance] 
```

The test are performing look ups on cluster.local instead of the specified cluster domain.
```
getent hosts dns-querier-1.dns-test-service.e2e-tests-dns-8zhjr.svc.cluster.local
dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A
dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A
podARec=10-0-62-224.e2e-tests-dns-8zhjr.pod.cluster.local
dig +notcp +noall +answer +search ${podARec} A
dig +tcp +noall +answer +search ${podARec} A
```

The tests have hard coded cluster.local in them.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns.go#L56

**What you expected to happen**:
The DNS tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster.  Run kube dns and setup your kubelets to use the dns specifying a cluster domain that is not cluster.local.

Run the e2e tests:
`KUBECONFIG=/path/to/kubeconfig KUBERNETES_CONFORMANCE_TEST=y go run hack/e2e.go -- - --test --deployment none --test_args="--ginkgo.focus=should\sprovide\sDNS\sfor\sthe\scluster\s|should\sprovide\sDNS\sfor\sservices"`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v.1.9.2
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): Amazon Linux 2
- Kernel (e.g. `uname -a`): Linux ip-10-0-181-107.us-west-2.compute.internal 4.9.81-44.57.amzn2.x86_64 #1 SMP Mon Feb 19 17:51:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by raoofm** [comment]
same issue here

**Comment by fturib** [comment]
Hum.. I did not notice this issue so far.
FYI - @rajansandeep , @chrisohaver 
@rajansandeep : could you have a look and adapt the code ?
