### ISSUE TITLE
[pr:pull-kubernetes-e2e-gce] Kubectl client [k8s.io] Update Demo should create and stop a replication controller  [Conformance] flaked 53 times in the past week

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#61484]
### Flaky Job: pr:pull-kubernetes-e2e-gce
[Consistency: 88.5%](http://storage.googleapis.com/k8s-metrics/flakes-daily-latest.json)

### Flakiest test : [sig-cli] Kubectl client [k8s.io] Update Demo should create and stop a replication controller  [Conformance]
[Flakes in the past week: 53](http://storage.googleapis.com/k8s-metrics/flakes-latest.json)

/priority failing-test
/priority important-soon
/sig cli
/kind flake

@kubernetes/sig-cli-test-failures

**Comment by AishSundar** [comment]
Here's the TestGrid view to dig into the flakes and get more detailed logs

https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Update%20Demo%20should%20create%20and%20stop%20a%20replication%20contr

**Comment by Liujingfang1** [comment]
The failure is that after the replication controller is cleaned up, the pods are not terminated.

I investigated the failure. It is from function `AssertCleanup` after `kubectl delete`. `AssertCleanup` does two things: make sure the resource is deleted and make sure the pods are deleted. 
If the pods haven't started termination during the `AssertCleanup` running, we will see this failure. The solution is to add several retry, give the pods more time to start termination.

**Comment by AishSundar** [comment]
Liujingfang1@ I see you have a PR out for the fix, thanks. Any ETA on when this will be merged? I can monitor test status once its in before pinging you to close the issue.

**Comment by mengqiy** [comment]
ETA is this week. Maybe tomorrow :)

**Comment by soltysh** [comment]
> @Liujingfang1 can we plz reopen this issue and close it once we see the flake is actually fixed? Thanks

@AishSundar what's wrong with having it closed and re-open if the flake hits back?

**Comment by soltysh** [comment]
sgtm as long as you'll don't forget to close it when confirmed :wink: The reason I usually close them is so that I don't have to remember.

**Comment by AishSundar** [comment]
I will definitely keep an eye out and close it :) I usually check on these before my weekly flake report.

**Comment by AishSundar** [comment]
@Liujingfang1 I do see a few flakes with this test still

https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Update%20Demo%20should%20create%20and%20stop%20a%20replication%20contr

Both failures are the same:

test/e2e/kubectl/kubectl.go:314
Apr  2 21:35:55.396: Pods left unterminated after stop:
update-demo-nautilus-dggjz
update-demo-nautilus-zb8pv

test/e2e/framework/util.go:2019

Gubernator results:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61723/pull-kubernetes-e2e-gce/28792
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61928/pull-kubernetes-e2e-gce/28884

**Comment by soltysh** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/62155 and increased the timeout to 1 minute similarly to the time GC tests are waiting for cleanups. @Liujingfang1 @mengqiy ptal

**Comment by soltysh** [comment]
@AishSundar it looks like the last linked PR fixed the problem and from looking at the testgrid it hasn't appeared, mind closing?

**Comment by AishSundar** [comment]
Thanks @soltysh for the fix. The test seems to pass fine in the GCE job.

However I do see a couple fo flakes in the GKE job.

https://k8s-testgrid.appspot.com/google-gke#gci-gke&include-filter-by-regex=%5EOverall%24%7C%5C%5Bsig%5C-cli%5C%5D%5C%20Kubectl%5C%20client%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Update%5C%20Demo%5C%20should%5C%20create%5C%20and%5C%20stop%5C%20a%5C%20replication%5C%20controller%5C%20%5C%20%5C%5BConformance%5C%5D

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.9-gci-master-upgrade-cluster-parallel&include-filter-by-regex=%5EOverall%24%7C%5C%5Bsig%5C-cli%5C%5D%5C%20Kubectl%5C%20client%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20Update%5C%20Demo%5C%20should%5C%20create%5C%20and%5C%20stop%5C%20a%5C%20replication%5C%20controller%5C%20%5C%20%5C%5BConformance%5C%5D

Let me know if this needs a different fix/investigation. If so I am happy to close this and open a new issue.

**Comment by mengqiy** [comment]
There are only 2 test failure happened from 03/27 to 04/10. And these 2 failures are high likely to be related to some cross-cutting infra failure, e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/24436.

I believe we can close this issue.

**Comment by AishSundar** [comment]
Sounds good. I am closing this issue now. Will reopen if it surfaces as top flake again. Thanks for your efforts here.
