### ISSUE TITLE
RFC: dep support

### ISSUE THREAD

**Issue by sigma** [kubernetes/kubernetes#61490]
So I have been working on a way to make dep (or something dep-compatible) friendlier towards the kubernetes main repository.

It differs from #57795 in that:
- it doesn't leave dep entirely as-is (instead, it tries to teach it to handle mono-repositories better)
- it doesn't introduce a runtime construct

After talking with @sttts I opened golang/dep#1764 which explores *one* of the possibilities, namely merging some of the logic into dep (certainly not as-is though).
I also have a version that's a standalone tool vendoring dep, in case upstreaming is not an option.
Realistically some of the logic *might* make it, while the rest would probably have to be handled in a k8s-specific tool.
The design details are entirely shared between the two options, so I'll leave golang/dep#1764 as the source of truth for now.

I'm opening this particular issue to
  * make sure I'm talking to both communities in a consistent way
  * collect kubernetes-specific feedback on the viability of the approach

@thockin @jessfraz @mattfarina @sttts (and whoever else might be interested), I'd love to get your thoughts !

thanks!

**Comment by sigma** [comment]
@kubernetes/sig-testing-proposals

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
#64731
