### ISSUE TITLE
Job - Target existing Pod and Container to carry out command execution. 

### ISSUE THREAD

**Issue by davissp14** [kubernetes/kubernetes#61497]
/kind feature
/sig api-machinery

We are hosting various databases within our stack that are spread across various Pods.  Within each Pod, we have two containers, the DB instance and a side-car container containing various DB specific mgmt scripts.  These scripts serve various purposes and some are long-lived and some are single quick on-demand queries that return data.

We have been considering using Jobs to communicate with the DB instance vs. having a permanent side-car container, however, the overhead of spinning up a completely new Pod with each execution seems like overkill.    

Has any consideration been given to provide Jobs more flexibility around where the actual execution should take place?  

Example:  Instead of building out a completely new Pod to execute a simple one-liner, I'd love to be able to target a specific pod and container to carry out a given task. 

Thoughts?

**Comment by kow3ns** [comment]
My initial thought it that this would too closely couple the lifecycle of the a Job and another Pod to be implemented as you are describing.

Why do not want to continue using side cars?

**Comment by davissp14** [comment]
Jobs give us nice built-in control over parallelism, timeouts, retries, etc.  Cron via CronJobs is also quite nice.  Utilizing Jobs seems like it would allow us to not have to reinvent all of these features and would also provide a consistent execution method for both our on-demand and scheduled operations.

**Comment by davissp14** [comment]
Seems like it could be beneficial to decouple this logic from the Pod lifecycle.  It would be pretty interesting to be able to wrap a Job around a K8 Exec call, for example.
