### ISSUE TITLE
Clean up fake mounters

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#61502]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
/kind cleanup

**What happened**:
There are too many FakeMounter implementations in the codebase.  It's annoying to have to update all of them whenever we have to change the Mounter interface.  They should all be consolidated to use the FakeMounter implementation in pkg/util/mount/fake.go.

**Comment by scriptonist** [comment]
Is this a beginner friendly issue? If so I will be happy to work on this

**Comment by msau42** [comment]
Yes totally!

**Comment by yue9944882** [comment]
@msau42 I don't find any other `FakeMounter` in the repo. To which r u referring plz? (facepalm

**Comment by msau42** [comment]
Sorry I wasn't being specific.  If you look at #61489, you can see all the places we need to change whenever we add a new function to the Mounter interface.  Many of these are fake implementations for unit tests, so there may be some opportunity for consolidation there.
