### ISSUE TITLE
TestRollingUpdateDaemonSetExistingPodAdoption is flaking

### ISSUE THREAD

**Issue by mindprince** [kubernetes/kubernetes#61513]
/kind flake
/area test
/sig apps
/sig testing

Examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61498/pull-kubernetes-integration/2922/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/2927
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60793/pull-kubernetes-integration/2941

It's the second most flaky test among all integration tests: https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration

/assign @crimsonfaith91
/cc @kubernetes/sig-apps-test-failures

**Comment by crimsonfaith91** [comment]
I suspected the flakiness might be due to turning on of garbage collector within the test. I will investigate it tonight, but feel free to revert the codes if needed.

**Comment by crimsonfaith91** [comment]
@mindprince The test has been removed and to be converted into an e2e test. The flakiness was due to a GC race condition. This issue can be closed.
