### ISSUE TITLE
how to Associate the  kubelet client User   and  psp service account ?

### ISSUE THREAD

**Issue by AnberLu** [kubernetes/kubernetes#61516]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
if my kubectl client is bound to service account (ceph) and namespace (ceph) , I need to specify service account (ceph) in my deployment. If I don't specify service account (ceph) in my deployment , the default service account of my deployment is still default. Is there any way to make the default service account with the client-bound service account (ceph)?

my kubectl config file:

apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/ceph/.kube/cert/ca.crt
    server: https://master-ip:port
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: ceph
    user: ceph
    ServiceAccount: ceph
  name: ceph@kubernetes
current-context: ceph@kubernetes
kind: Config
preferences: {}
users:
- name: ceph
  user:
    as-user-extra: {}
    client-certificate: /home/ceph/.kube/cert/ceph.crt
    client-key: /home/ceph/.kube/cert/ceph.key

**What you expected to happen**:
Associate the  kubelet client User   and  psp service account .

**Comment by CaoShuFeng** [comment]
Looks like "default" is hard coded.
https://github.com/kubernetes/kubernetes/blob/1365ce341924fb705d25704d4802f8aec5582b38/plugin/pkg/admission/serviceaccount/admission.go#L44

Is this a reasonable feature request @liggitt ?

**Comment by AnberLu** [comment]
thank you  @CaoShuFeng  and @liggitt  .  the "default" service account is hard  code.  

1）
If I want to use the "default" service account, then I need to bind the PSP with  “default” service account and authenticated user.
2）
When there are multiple users accessing k8s cluster, the permissions of the "default" service account under a namespace will exceed the access capability of single user. In this case, the "default" service account of a single user can actually  beyond his psp access control. If we allow the the service account set on the client is the default service account at first, then we can achieve the corresponding psp access function in the deployment without specifying the service account.

**Comment by liggitt** [comment]
Propagation of the user making the API call to create the pod into the serviceAccountName field of the pod is not something we should do. 

First, it would only be possible if the user creating the pod happened to be a service account in the same namespace as the pod. 

Second, having pod creation behave differently in that way depending on who made the API call to create the pod makes for an unpredictable API

/close
