### ISSUE TITLE
Kubemark Test-How to point to Master cluster 

### ISSUE THREAD

**Issue by K7king** [kubernetes/kubernetes#61538]
/kind flake
/area test
/sig scheduling
/sig testing
/kind question
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind question

**What happened**:
I deployed a cluster on AWS. I want to run [Kubemark test ](https://github.com/kubernetes/kubernetes/tree/master/test/kubemark) . By pre-existing they state to give configurations like this 
_CLOUD_PROVIDER="pre-existing"
KUBEMARK_IMAGE_MAKE_TARGET="push"
CONTAINER_REGISTRY=docker.io
PROJECT="rthallisey"
MASTER_IP="192.168.121.29:6443"_

Here what is the Master IP pointing to ?
 
**What you expected to happen**:
I want Kubemark test to be performed on the same cluster deployed on AWS.

**Environment**: AWS

**Comment by cy-zheng** [comment]
Same issue... I think the document about kubemark pre-existing cluster deployment should be refined.
