### ISSUE TITLE
Resoucequote admission will update resourcequota in apiserver even though pod created failed.

### ISSUE THREAD

**Issue by malc0lm** [kubernetes/kubernetes#61530]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
There is a resourcequota named testquota in namespace, I create a pod with "kubectl create -f pod.yaml", it will success and testquota will be updated. When I use "kubectl create -f pod.yaml" again, the pod creating failed and apiserver will return "Error from server (AlreadyExists): error when creating "pod.yaml": pods "get-date" already exists"(That's just as it should be).  But the testquota still be updated in apiserver.

Of cource resourcequotaController which is in kube-controller-manager will  repair testquota when some resource related testquota be updated(create, delete or update).  But I think there is a potential problem, if someone use "kubectl create -f pod.yaml" in a loop, others can't use any resource which limited by resourcequota in same namespace.
**What you expected to happen**:
Resourcequota can be updated until pod be created success.
**How to reproduce it (as minimally and precisely as possible)**:
above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-26T08:16:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-03-22T08:48:13Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):4.13.0-36-generic
- Install tools:
- Others:

**Comment by malc0lm** [comment]
@kubernetes/sig-api-machinery

**Comment by liggitt** [comment]
That is correct. Quota is updated during admission, pre-persistence. That is working as designed, as there is no two-phase transaction available within kube. 

A background controller periodically checks for over reporting quota objects and corrects them. 

/close
