### ISSUE TITLE
kubernetes call ceph luminous failed

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#61532]
I install ceph luminous, and create rbd pool. When I configure kubernetes to use ceph by storageclass, the pvc is pending. I have install ceph-common and modprobe rbd on kubernetes node（version:v1.8.3）.
The config of ceph-secret and ceph-storageclass is like this:
apiVersion: v1
kind: Secret
metadata:
name: ceph-secret
namespace: default
type: "kubernetes.io/rbd"
data:
key: QVFBckViSmFuVDdvSXhBQXgwNXFNZGVNMzhSM012dG1ISzFqMWc9PQ==

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: ceph-iop
provisioner: kubernetes.io/rbd
parameters:
monitors: 10.110.25.71:6789,10.110.25.72:6789,10.110.25.73:6789
adminId: admin
adminSecretName: ceph-secret
adminSecretNamespace: default
pool: rbd
userId: admin
userSecretName: ceph-secret
imageFormat: "1"

I found some error in kube-control-manager log is like this:
2018-03-22 07:30:32.039740 7f6e50267700 0 -- 10.110.22.81:0/1000234 >> 10.110.25.73:6789/0 pipe(0x7f6e3c001c30 sd=3 :39474 s=1 pgs=0 cs=0 l=1 c=0x7f6e3c005e10).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
2018-03-22 07:30:33.532998 7f6e568b8780 0 monclient(hunting): authenticate timed out after 300
2018-03-22 07:30:33.554389 7f6e568b8780 0 librados: client.admin authentication error (110) Connection timed out
rbd: couldn't connect to the cluster!
I0322 07:30:33.818456 1 pv_controller.go:1317] failed to provision volume for claim "default/pvc" with StorageClass "ceph-iop": failed to create rbd image: exit status 1, command output: 2018-03-22 07:25:33.379161 7f6e568b8780 -1 did not load config file, using default settings.

**Comment by wufenglinux** [comment]
我也是这个问题，但是我尝试过无数种方法。
我发现了一个让人很生气的问题
我修改了storageclass中的配置参数，这个参数
parameters:
monitors: 这个参数即使乱写 storage依然可以创建出来，并且provisioner也是报 StorageClass "rbd": missing Ceph monitors

这个错误真的很误导人，其实并不是没有ceph monitor
我到现在还没有解决这个问题。
这个问题误导了我快1个月了
