### ISSUE TITLE
Ceph RBD provisionner "timeout expired waiting for volumes to attach/mount for pod"

### ISSUE THREAD

**Issue by pandatk** [kubernetes/kubernetes#61543]
/kind bug

**What happened**:

The RBD storageClass and PVC are working as expected (bound together, pvc provisionned, can see the created images on the ceph pool). When i try to use the volumes in a  statefulset i get the following error 
```
    Warning  FailedMount            14s (x3 over 4m)  kubelet, node2     Unable to mount volumes for pod "mysql-0_default(2c4858f6-2dd1-11e8-9506-00505695ceef)": timeout expired waiting for volumes to attach/mount for pod "default"/"mysql-0". list of unattached/unmounted volumes=[db]
```
The error is a catch all so kubelet logs are included below

**What you expected to happen**:

For the pod to mount its volume properly.

**How to reproduce it (as minimally and precisely as possible)**:
I use the following yaml files to deploy ressources  
StorageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: cephrbd
  annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
    monitors: 172.29.1.138:6789, 172.29.1.139:6789, 172.29.1.140:6789
    adminId: admin
    adminSecretName: ceph-secret
    pool: kube
    fsType: ext4
    userId: kube
    userSecretName: ceph-user-secret

```
first PVC (2 others similar)
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: db-mysql-0
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
```
StatefulSet
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql  
spec:
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        name: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: perconalab/percona-xtradb-cluster:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: k8spassword
          - name: DISCOVERY_SERVICE
            value: etcd:2379
          - name: XTRABACKUP_PASSWORD
            value: k8spassword
          - name: CLUSTER_NAME
            value: percona
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql 
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

**Anything else we need to know?**:
Looking in the kubelet logs i get the following lines : 
```
Mar 22 14:01:29 node2 kubelet[2046]: I0322 14:01:29.115165    2046 reconciler.go:262] operationExecutor.MountVolume started for volume "pvc-52ea13b0-2dd9-11e8-9506-00505695ceef" (UniqueName: "kubernetes.io/rbd/[172.29.1.138:6789  172.29.1.139:6789  172.29.1.140:6789]:kubernetes-dynamic-pvc-52ecfdb3-2dd9-11e8-86c8-00505695ceef") pod "mysql-0" (UID: "58b6eaae-2dd9-11e8-9506-00505695ceef")
Mar 22 14:01:29 node2 kubelet[2046]: I0322 14:01:29.115825    2046 operation_generator.go:446] MountVolume.WaitForAttach entering for volume "pvc-52ea13b0-2dd9-11e8-9506-00505695ceef" (UniqueName: "kubernetes.io/rbd/[172.29.1.138:6789  172.29.1.139:6789  172.29.1.140:6789]:kubernetes-dynamic-pvc-52ecfdb3-2dd9-11e8-86c8-00505695ceef") pod "mysql-0" (UID: "58b6eaae-2dd9-11e8-9506-00505695ceef") DevicePath ""
Mar 22 14:01:29 node2 kubelet[2046]: E0322 14:01:29.402591    2046 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/rbd/[172.29.1.138:6789  172.29.1.139:6789  172.29.1.140:6789]:kubernetes-dynamic-pvc-52ecfdb3-2dd9-11e8-86c8-00505695ceef\"" failed. No retries permitted until 2018-03-22 14:02:33.402150246 +0000 UTC m=+245312.690283744 (durationBeforeRetry 1m4s). Error: "MountVolume.WaitForAttach failed for volume \"pvc-52ea13b0-2dd9-11e8-9506-00505695ceef\" (UniqueName: \"kubernetes.io/rbd/[172.29.1.138:6789  172.29.1.139:6789  172.29.1.140:6789]:kubernetes-dynamic-pvc-52ecfdb3-2dd9-11e8-86c8-00505695ceef\") pod \"mysql-0\" (UID: \"58b6eaae-2dd9-11e8-9506-00505695ceef\") : error: exit status 1, rbd output: 2018-03-22 14:01:29.382939 7f0c5e8a1100 -1 did not load config file, using default settings.\nrbd: error opening image kubernetes-dynamic-pvc-52ecfdb3-2dd9-11e8-86c8-00505695ceef: (1) Operation not permitted\n2018-03-22 14:01:29.398427 7f0c2ffff700 -1 librbd::image::OpenRequest: failed to retrieve image id: (1) Operation not permitted\n2018-03-22 14:01:29.398483 7f0c2f7fe700 -1 librbd::ImageState: 0x55825945e0c0 failed to open image: (1) Operation not permitted\n"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux node2 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
Installed the cluster using kubespray on Vsphere virtual machines
- Others:

**Comment by dunv-viosoft** [comment]
I has same issue

**Comment by zolij** [comment]
me too

additional information:

- pv created automatically from pvc
- i can see the new volume on ceph side so it's created successful, only pod mount fails.

**Comment by xigang** [comment]
I has same issue:(

**Comment by zhaosg** [comment]
I has same issue

**Comment by ectsue** [comment]
I experienced a very similar issue on k8s version 1.10. However, it wasn't isolated to stateful sets. I was unable to mount any rbd persistent volumes. I downgraded to 1.9.2 and everything worked again.

**Comment by wuzhihui1123** [comment]
I has same issue when i upgrade to 1.9.6 from 1.8.7 
k8s version : 1.9.6
os: centos 7.3.1611
kernel:  3.10.0-514.6.2

==> it will be ok when k8s rollback to 1.8.7

**Comment by gageorsburn** [comment]
Same issue on 1.9.5. Downgrading to 1.9.2 like ectsue and seeing what happens!

**Comment by zchunhai** [comment]
I has same issue:
K8s: 1.9.0
Ceph: jewel

**Comment by xiaoxubeii** [comment]
I will check 1.9.2

**Comment by shuraa** [comment]
The same issue:

```
K8S: 1.9.7 (@Bare Metal)
OS: Ubuntu 16.04
Ceph: luminous
```

**Comment by hubpanda** [comment]
Tried out to reinstall in multiple 1.9 versions (1.9.1, 1.9.2, 1.9.7) without any luck.
I then tried it out with v1.10.2 and got something unexpected 
`  Warning  FailedMount  1m  kubelet, node5  MountVolume.WaitForAttach failed for volume "pvc-811e8229-4fab-11e8-b18f-0050569571c1" : fail to check rbd image status with: (exit status 1), rbd output: (2018-05-04 15:45:23.481062 7ffb7aa6b100 -1 did not load config file, using default settings.
2018-05-04 15:45:23.489107 7ffb7aa6b100  0 librados: client.kube authentication error (1) Operation not permitted
rbd: couldn't connect to the cluster!
`
I could correct this by changing the rights of my ceph client, but it doesnt make sense to me.
Rights of the kube client looked like this before : 
`	caps: [mds] allow *
	caps: [mon] allow *
	caps: [osd] allow *
`
Now look like this : 
`	caps: [mds] allow *
	caps: [mgr] allow *
	caps: [mon] allow *
	caps: [osd] allow *
`
What i dont get is how adding mgr rights can change anything to rbd failing to connect ?
So maybe my issue was more ceph related and not kube after all. What kube failed to do was accurately displaying what the problem was..

**Comment by mr-yaky** [comment]
I downgraded k8s cluster to 1.9.2 version:

```
$ kubectl version | grep -i server
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

But still get the same error when statefulset is creating :(

**Comment by mr-yaky** [comment]
Some investigations.
Tried manual formating for rbd image:
```
# rbd map kube/kubernetes-dynamic-pvc-4ef16e04-5208-11e8-9d85-ba19f676b59c --name client.admin -m 192.168.2.10
# mount -o ro /dev/rbd0 /mnt/
mount: unknown filesystem type '(null)'

# mkfs.ext4 /dev/rbd0
# mount -o ro /dev/rbd0 /mnt/
# umount /mnt
# rbd unmap /dev/rbd0
```

And after I re-created statefulset but got previous error:
```
  Warning  FailedMount            22s (x6 over 11m)  kubelet, k8s-node01  Unable to mount volumes for pod "chat-mongodb-mongodb replicaset-0_default(846d4189-5209-11e8-9eac-005056001f0f)": timeout expired waiting for volumes to attach/mount for pod "default"/"chat-mongodb-mongodb-replicaset-0". list of unattached/unmounted volumes=[datadir]
```

**Comment by hubpanda** [comment]
are you using client.admin as userId for the storageclass? 

maybe you should try upgrading to 1.10.x as well since they seem to have imroved the error messages, that might give you the root cause.

**Comment by mr-yaky** [comment]
I tried mount rbd image from one of ceph nodes not from rbd-provisioner container.

>maybe you should try upgrading to 1.10.x as well since they seem to have imroved the error messages, that might give you the root cause.

Unfortunately kubespray is not support 1.10.x yet so there will still be some risk.

Maybe some one know how we can debug and investigate on 1.9.x version ?

**Comment by wuzhihui1123** [comment]
i have upgraded to 1.10.4 , the error still . 
i only upgrade kubernetes node ,
==== my env:
kube-api:  1.8.7 
kubelet:   1.10.4
docker: 18.03.1-ce
ceph: 12.0.3
=======

**Comment by wuzhihui1123** [comment]
my current k8s version is 1.8.7 。 when  i only upgrade k8s-node to 1.9.x or 1.10.x , this problem will occur. but when i upgrade k8s-master  to the same version as k8s-node.  The problem does not exist， anything is ok。  
I want people who have problems to know this：）

**Comment by gun1x** [comment]
I am having the same issue. 
k8s: v1.9.5
ceph: 12.2.5 luminous
platform: ubuntu 16.04

**Comment by saurfangg** [comment]
Seeing this issue with Pods trying to attach volumes when trying to deploy prometheus.

**Comment by alexander-kasper** [comment]
We located our problem. There was a wrong IP in the monmap as we added storage interfaces later. We changed the config but in the monmap there was the old IP.

**Comment by radut** [comment]
I had same problem timeout for mounting volume. In my case the issue was fixed by setting "ceph osd crush tunnables legacy"
