### ISSUE TITLE
GKE Dashboard tests are failing because it's not started by default

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#61559]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
GKE tests are failing. They are trying to check that the dashboard is alive, but the dashboard is disabled by default in GKE in Kubernetes 1.10.

**What you expected to happen**:
The test should either not run, or start the dashboard. Ideally, it would start the dashboard so we could see that it works, for now we'll just disable the test.

**How to reproduce it (as minimally and precisely as possible)**:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-regional/5810

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @mml @konryd

**Comment by apelisse** [comment]
/priority critical-urgent

That's probably not true, but please change it to appropriate.

**Comment by jberkus** [comment]
Is this different from #60767?

**Comment by krzyzacy** [comment]
@jberkus we have enabled the plugin from all the blocking jobs so it's not a blocker, but in the long run this need to be in it's own feature.
