### ISSUE TITLE
kubectl: Unexpected error when reading response body

### ISSUE THREAD

**Issue by dbt** [kubernetes/kubernetes#61551]
/kind bug

**What happened**:
> % kubectl get pods
> E0322 10:22:01.816738   26395 request.go:784] Unexpected error when reading response body: &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc420976000), Addr:(*net.TCPAddr)(0xc420976030), Err:(*os.SyscallError)(0xc4206c6b20)}
> Unexpected error &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc420976000), Addr:(*net.TCPAddr)(0xc420976030), Err:(*os.SyscallError)(0xc4206c6b20)} when reading response body. Please retry.

**What you expected to happen**:

Kubectl to display a list of pods. Immediately re-running the command succeeds.

**How to reproduce it (as minimally and precisely as possible)**:

Wait a few minutes since accessing cluster. Run simple kubectl command.

It seems similar to the bug report in #54859

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
> % kubectl version
> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux $hostname 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: apt-get from packages.cloud.google.com
- Others: Was happening on 1.9.4 as well, but just updated to 1.9.6 and could repro.

**Comment by willemodendaal** [comment]
Pity this bug rotted... got the same issue now :,(

**Comment by icann-itops** [comment]
Indeed, me too

**Comment by ArgonV** [comment]
I have the same bug too, running v2.1.6 of Rancher single server with a Custom cluster using per-provisioned Oracle Linux VMs.

**Comment by drewboswell** [comment]
I have the same problem on v. 2.1.6, this is a serious problem as any proxy kubectl access is now impossible.

**Comment by ArgonV** [comment]
I believe this bug is also causing my Rancher Server to eat a huge amount of memory. I only have 2 clusters with a total of 17 nodes. I've had to up my Rancher server to 4 cores and 16GB of memory, otherwise it will hang docker and eventually crash the VM...

**Comment by saravana-code** [comment]
i have the same problem in 
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-ee8ff", GitCommit:"ee8ffc99be2f6c6caab3cfe890227151b37faf8d", GitTreeState:"clean", BuildDate:"2019-09-24T21:49:34Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
