### ISSUE TITLE
kubelet won't start - /etc/kubernetes/pki/ca.crt: no such file or directory

### ISSUE THREAD

**Issue by qq9338745** [kubernetes/kubernetes#61577]
bug

What happened:
Performed a clean install on Oracle Linux release 7.3 and started kubelet
yum install -y kubelet kubeadm kubectl systemctl enable kubelet && systemctl start kubelet
`
systemctl status kubelet
tail -100f /var/log/messages | grep kubelet

kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`

What you expected to happen:
kubelet starts successfully

How to reproduce it (as minimally and precisely as possible):
yum install -y kubelet kubeadm kubectl systemctl enable kubelet && systemctl start kubelet

systemctl status kubelet tail -100f /var/log/messages | grep kubelet
Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version): 1.9.6
1.9.6

[root@infbjvm555 yum.repos.d]# rpm -qa|grep kub
kubernetes-cni-0.6.0-2.0.1.el7.x86_64
kubernetes-cni-plugins-0.6.0-2.0.1.el7.x86_64
kubelet-1.9.6-0.x86_64
kubectl-1.9.6-0.x86_64
kubeadm-1.9.6-0.x86_64

Mar 23 11:15:54 infbjvm555 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 23 11:15:54 infbjvm555 systemd: Unit kubelet.service entered failed state.
Mar 23 11:15:54 infbjvm555 systemd: kubelet.service failed.
Mar 23 11:16:04 infbjvm555 systemd: kubelet.service holdoff time over, scheduling restart.
Mar 23 11:16:04 infbjvm555 systemd: Started kubelet: The Kubernetes Node Agent.
Mar 23 11:16:04 infbjvm555 systemd: Starting kubelet: The Kubernetes Node Agent...
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033441    6392 feature_gate.go:226] feature gates: &{{} map[]}
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033601    6392 controller.go:114] kubelet config controller: starting controller
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033612    6392 controller.go:118] kubelet config controller: validating combination of defaults and flags
Mar 23 11:16:05 infbjvm555 kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Mar 23 11:16:05 infbjvm555 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 23 11:16:05 infbjvm555 systemd: Unit kubelet.service entered failed state.
Mar 23 11:16:05 infbjvm555 systemd: kubelet.service failed.

[root@infbjvm555 log]# cd /etc/kubernetes/
[root@infbjvm555 kubernetes]# ls -rlt
total 0
drwxr-xr-x 2 root root 6 Mar 22 03:30 manifests
[root@infbjvm555 kubernetes]# 

actually, there is no /etc/kubernetes/pki/ dir and files.

BTW, i can use "kubeadm init " to solve it ( the related files will be created after run  kubeadm init) , but after that ,when i run "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 " , it failed again.

**Comment by zjj2wry** [comment]
/kind support
```
Mar 23 11:16:05 infbjvm555 kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
```
@qq9338745 
The kubelet's ca file does not exist. Are you adding nodes or restarting? or use kubeadm join?

**Comment by qq9338745** [comment]
no, i  haven't done adding nodes or restarting operation. this is a new environment.
does kub 1.9.6 support docker   17.06.2-ol ?

**Comment by zjj2wry** [comment]
The log says your ca file does not exist, please check it

**Comment by qq9338745** [comment]
yes, i have mentioned that, there is no such dir or file . i don't know the root cause.

********************************************************************************************
[root@infbjvm555 log]# cd /etc/kubernetes/
[root@infbjvm555 kubernetes]# ls -rlt
total 0
drwxr-xr-x 2 root root 6 Mar 22 03:30 manifests
[root@infbjvm555 kubernetes]#

actually, there is no /etc/kubernetes/pki/ dir and files.
********************************************************************************************

**Comment by liggitt** [comment]
simply installing the kubelet package does not configure it or join it to a cluster

see https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#instructions for instructions on joining a node to a cluster

> The kubelet is now restarting every few seconds, as it waits in a crashloop for kubeadm to tell it what to do. This crashloop is expected and normal, please proceed with the next step and the kubelet will start running normally.
