### ISSUE TITLE
DNS servers and search domains are not set for Windows Pods

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#61579]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Kubelet is depending on docker container's ResolvConfPath (e.g. `/var/lib/docker/containers/439efe31d70fc17485fb6810730679404bb5a6d721b10035c3784157966c7e17/resolv.conf`) to setup dns servers and search domains. While this is ok for Linux containers, ResolvConfPath is always an empty string for windows containers. So that the DNS setting for windows containers are always not set.

For kubernetes clusters deployed by acs-engine, the Pod's DNS is always set to kube-dns service's clusterIP. This is done via the network plugin (e.g. l2bridge or azure-cni). It makes windows containers only work with ClusterFirst dns policy. 

To follow kubernetes dns policies, Kubelet should pass the expected DNS settings directly to windows containers (instead of set it in CNI plugins).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
Let me fix this in v1.11

**Comment by PatrickLang** [comment]
This may have been fixed in https://github.com/Microsoft/SDN/issues/150

**Comment by feiskyer** [comment]
@PatrickLang Not same.  

> For kubernetes clusters deployed by acs-engine, the Pod's DNS is always set to kube-dns service's clusterIP. This is done via the network plugin (e.g. l2bridge or azure-cni). It makes windows containers only work with ClusterFirst dns policy.

This is what https://github.com/Microsoft/SDN/issues/150 has done, but it doesn't follow kubernetes dns policies.

**Comment by tpepper** [comment]
@feiskyer status check...still intended for 1.11?

**Comment by feiskyer** [comment]
@tpepper Yep.
