### ISSUE TITLE
protobuf optional lists are not textproto marshalable

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#61578]
/bug
/sig api-machinery

**Comment by mikedanese** [comment]
Failing test
```diff
---
 .../pkg/apis/meta/v1/textproto_test.go        | 19 +++++++++++++++++++
 1 file changed, 19 insertions(+)
 create mode 100644 staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/textproto_test.go

diff --git a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/textproto_test.go b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/textproto_test.go
new file mode 100644
index 00000000000..7bac5734a13
--- /dev/null
+++ b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/textproto_test.go
@@ -0,0 +1,19 @@
+package v1
+
+import (
+       "testing"
+
+       gogo "github.com/gogo/protobuf/proto"
+       "github.com/golang/protobuf/proto"
+)
+
+func TestHelloWorld(t *testing.T) {
+       proto.MarshalTextString(&APIResource{
+               Name:  "foo",
+               Verbs: Verbs{"bar"},
+       })
+       gogo.MarshalTextString(&APIResource{
+               Name:  "foo",
+               Verbs: Verbs{"bar"},
+       })
+}
--
```

**Comment by lavalamp** [comment]
cc @yliaog 

(we don't understand this, will let Yu figure it out for us :) )

**Comment by yliaog** [comment]
The panic happened when trying to serialize Verbs, which is defined as []string. 

But as clearly documented only byte slice is accepted, []string is not expected. So to properly marshal / unmarshal the go structs, the Marshal/UnMarshal defined in .pb.go has to be used. The generic Marshal/Unmarshal functions in golang/protobuf or gogo/protobuf won't work.

 (https://github.com/gogo/protobuf/blob/49944b4a4b085da44c43d4b233ea40787396371f/proto/text.go#L581)
	// We don't attempt to serialise every possible value type; only those
	// that can occur in protocol buffers.
	// Should only be a []byte; repeated fields are handled in writeStruct.

--- FAIL: TestHelloWorld (0.00s)
panic: reflect.Value.Bytes of non-byte slice [recovered]
        panic: reflect.Value.Bytes of non-byte slice

goroutine 61 [running]:
testing.tRunner.func1(0xc4202934a0)
        /usr/lib/google-golang/src/testing/testing.go:742 +0x29d
panic(0x9eff20, 0xb1f880)
        /usr/lib/google-golang/src/runtime/panic.go:505 +0x229
reflect.Value.Bytes(0xa42b20, 0xc4201ceb98, 0x197, 0xa42b20, 0xc4201ceb98, 0x197)
        /usr/lib/google-golang/src/reflect/value.go:262 +0xad
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0xe721b4, 0xc420416660, 0xa42b20, 0xc4201ceb98, 0x197, 0xc420218420, 0xb2e9e0, 0xa42b20)
        /usr/local/google/home/yliao/prj/k8sclientgo60/src/github.com/gogo/protobuf/proto/text.go:575 +0x592
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0xe721b4, 0xc420416660, 0xa96a20, 0xc4201ceb40, 0x199, 0x199, 0x0)
        /usr/local/google/home/yliao/prj/k8sclientgo60/src/github.com/gogo/protobuf/proto/text.go:461 +0x878
github.com/gogo/protobuf/proto.(*TextMarshaler).Marshal(0xe721b4, 0xb20560, 0xc4202dd960, 0xb26640, 0xc4201ceb40, 0xc42017dea0, 0x5d7407)
        /usr/local/google/home/yliao/prj/k8sclientgo60/src/github.com/gogo/protobuf/proto/text.go:894 +0x330
github.com/gogo/protobuf/proto.(*TextMarshaler).Text(0xe721b4, 0xb26640, 0xc4201ceb40, 0x0, 0x0)
        /usr/local/google/home/yliao/prj/k8sclientgo60/src/github.com/gogo/protobuf/proto/text.go:906 +0x6e
github.com/gogo/protobuf/proto.MarshalTextString(0xb26640, 0xc4201ceb40, 0x1, 0x75)
        /usr/local/google/home/yliao/prj/k8sclientgo60/src/github.com/gogo/protobuf/proto/text.go:922 +0x41
k8s.io/apimachinery/pkg/apis/meta/v1.TestHelloWorld(0xc4202934a0)

**Comment by apelisse** [comment]
Yeah, that's definitely the same error.
