### ISSUE TITLE
Remove use of REDACTED in config output for public CA

### ISSUE THREAD

**Issue by sethvargo** [kubernetes/kubernetes#61573]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:

`kubectl config view` shows:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
# ...
```

The use of "REDACTED" for a CA here is misleading, since it's a public certificate that is not a secret.

**What you expected to happen**:

I expected to see the full CA in pem format (like when you cat `~/.kube/config`) or something like "SUPPRESSED" or "TRUNCATED"

**How to reproduce it (as minimally and precisely as possible)**:

1. Run `kubectl config view`

**Anything else we need to know?**:

Nope

**Environment**:
- Kubernetes version (use `kubectl version`):
    
    ```
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", 
    GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", 
    BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Cloud provider or hardware configuration:

    ```
    GKE, but applies to CLI
    ```

- OS (e.g. from /etc/os-release):

    ```
    Mac OS X
    ```

- Kernel (e.g. `uname -a`):

    ```
    Darwin X 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
    ```

**Comment by sethvargo** [comment]
@kubernetes/sig-cli-bugs @kubernetes/sig-security-bugs (for thoughts)

**Comment by zjj2wry** [comment]
@sethvargo use `kubectl config view --raw` you can see the complete certificate authority data

**Comment by sethvargo** [comment]
Hey @zjj2wry 

Thank you - I have [another issue](https://github.com/kubernetes/kubernetes/issues/61572) tracking that 😄. 

The point of this issue is that at best it's a bad UX; at worst it's a miseducation on pki. "REDACTED" isn't the right word here

**Comment by zjj2wry** [comment]
@sethvargo If there are multiple clusters displaying certificates, the configuration will be too long, so this switch is turned off by default. But we can add an example to help use. thanks

**Comment by sethvargo** [comment]
Hey @zjj2wry 

I don't personally view truncation the responsibility of the CLI... users can pipe things to a pager if they really care. That being said, I'm not concerned about the length. The issue is purely about the word choice of "REDACTED". 

The term [redact](https://www.google.com/search?q=redact) means:

> censor or obscure (part of a text) for legal or security purposes.

The use of the term "REDACTED" in the output implies that a CA public key is remove for security when (as you've pointed out) it is removed for truncation. Truncation and redaction are fundamentally different things, and k8s is misusing the word redacted for this use case.

**Comment by cblecker** [comment]
Not quite a bug, but I think you're right @sethvargo a better term could be used there as it is a public key, not a private key.

@kubernetes/sig-auth-feature-requests 
/remove-kind bug

**Comment by mikedanese** [comment]
We are waiting for someone to fix this.

**Comment by cblecker** [comment]
/remove-help good-first-issue

@mikedanese I don't think this fits our definition of a `good first issue`: https://git.k8s.io/community/contributors/devel/help-wanted.md#good-first-issue

**Comment by cblecker** [comment]
/remove-good-first-issue

@mikedanese I don't think this fits our definition of a `good first issue`: https://git.k8s.io/community/contributors/devel/help-wanted.md#good-first-issue

**Comment by sethvargo** [comment]
So I have to keep replying to the comment bot every 30 days so it doesn't get auto-closed? That feels... odd

**Comment by mikedanese** [comment]
@cblecker thanks for the education :)

@sethvargo unfortunately other issues are higher priority and no one has stepped up to fix this. The autocloser is a form of bug bankruptcy that keeps our issue load in check. The contribex special interest group is definitely open to feedback on the bot.

**Comment by ibrasho** [comment]
@sethvargo The biggest hurdle in this is that Kubernetes is using some base64 trickery to display the string `REDACTED` (basically setting the certificate data to the decoded bytes from `REDACTED`).

We can change this to `TRUNCATE` or `TRUNCATEDCRT` but not `TRUNCATED` (it has to be a valid base64 encoded string). I tried exploring multiple options for the text, but I couldn't find a suitable one.

Given that we already print the user tokens and other credentials this is a bit weird. Should we redact those too? Is it okay if we print the CA certificate instead of truncating it?

**Comment by sethvargo** [comment]
@ibrasho I can't help but laugh at:

> but not `TRUNCATED` (it has to be a valid base64 encoded string)

I'm not wed to any particular name. I also have no problem displaying the entire certificate. The crux of the issue is that a CA **public key** is not secret or sensitive. It's a public key 😄

**Comment by ibrasho** [comment]
I agree. The issue is with how this is implemented currently. 😂

I tried to come up with a suitable string (given the constraint) and couldn't find anything acceptable...

I personally prefer to print the CA certificate since we are already printing user tokens and client certs that are *actual* secrets.

**Comment by sethvargo** [comment]
I agree. Who do we need to get in agreement that printing the full CA is the best path forward?

**Comment by liggitt** [comment]
the data is not omitted for security purposes, but to make the output more readable. see https://github.com/kubernetes/kubernetes/pull/7007

REDACTED is misleading... it should probably be "elided" or "..."

**Comment by liggitt** [comment]
you can add --raw to view full content

**Comment by sethvargo** [comment]
@liggitt that's the crux of this issue - REDACTED is misleading. However, @ibrasho pointed out that other "long" fields are still completely printed in plain text such as client certs, so I think we need to revisit the "readability" argument. What do you think?

**Comment by liggitt** [comment]
> other "long" fields are still completely printed in plain text such as client certs

they are not... client cert/key are elided in the same way for the same reason:

https://github.com/kubernetes/kubernetes/blob/5232ad4a00ec93942d0b2c6359ee6cd1201b46bc/staging/src/k8s.io/client-go/tools/clientcmd/api/helpers.go#L90-L95

```
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://localhost:6443/
  name: local-up-cluster
contexts:
- context:
    cluster: local-up-cluster
    user: local-up-cluster
  name: local-up-cluster
current-context: local-up-cluster
kind: Config
preferences: {}
users:
- name: local-up-cluster
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

something like "++data+omitted++" could be better

> I think we need to revisit the "readability" argument. What do you think?

If the intent of config view without --raw specified is to be readable (which it currently is), printing many extremely long fields isn't great

**Comment by sethvargo** [comment]
Hmm what about:

```go
cluster.CertificateAuthorityData[0..8] + " (TRUNCATED)"
```

I'm pretty sure that would give us a valid b64 string (8+12=20%4=0) and it would subtly hint that the data isn't a secret.

**Comment by ibrasho** [comment]
Only valid characters are `A-Za-z0-9+/=`. And adding a prefix from the certificate only complicates things.

`DATA+OMITTED` is a suitable usable option. I'll submit a PR to continue the discussion there.
