### ISSUE TITLE
batch  cronjobs , matches multiple kinds

### ISSUE THREAD

**Issue by sekaiga** [kubernetes/kubernetes#61586]
**this is a BUG REPORT**:
/kind bug
/sig api-machinery
**What happened**:
kubectl get all -n kube-system
error: {batch  cronjobs} matches multiple kinds [batch/v1beta1, Kind=CronJob batch/v2alpha1, Kind=CronJob]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
im not sure,
i start dashboard,heapster by k8s it happened.then i kubeadm reset.
i start dashboard,heapster by k8s again it happened again.then i kubeadm reset.
i only start dashboard,its ok. the next day it happened. i havent do anything.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux tensorflow1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubernetes v1.9.0
docker：17.03.2-ce
kubeadm:v1.9.0

googlecontainer/heapster                                 v1.5.1              c41e77c31c91        6 weeks ago         75.3 MB
nfs:5000/tensorflow/tensorflow                           nightly-gpu         be934a248847        7 weeks ago         2.95 GB
nfs:5000/tensorflow/tensorflow                           nightly             9124d6961a0e        2 months ago        1.25 GB
gcr.io/google_containers/kube-proxy-amd64                v1.9.0              f6f363e6e98e        3 months ago        109 MB
gcr.io/google_containers/kube-apiserver-amd64            v1.9.0              7bff5aa286d7        3 months ago        210 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.9.0              3bb172f9452c        3 months ago        138 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.9.0              5ceb21996307        3 months ago        62.7 MB
gcr.io/google_containers/kubernetes-dashboard-amd64      v1.8.1              e94d2f21bc0c        3 months ago        121 MB
quay.io/coreos/flannel                                   v0.9.1-amd64        2b736d06ca4c        4 months ago        51.3 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.7              db76ee297b85        5 months ago        42 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.7              5d049a8c4eec        5 months ago        50.3 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.7              5feec37454f4        5 months ago        40.9 MB
gcr.io/google_containers/etcd-amd64                      3.1.10              1406502a6459        6 months ago        193 MB
ibmcom/heapster                                          v1.4.0              749531a6d2cf        8 months ago        73.4 MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        22 months ago       747 kB
kubernetes/heapster                                      latest              d2d2bfdfb48f        2 years ago         34.5 MB
dockerinaction/hello_world                               latest              a1a9a5ed65e9        2 years ago         2.43 MB
kubernetes/heapster_grafana                              latest              b2951ae24ffe        3 years ago         250 MB
kubernetes/heapster_influxdb                             latest              10eaf557026e        3 years ago         275 MB

- Others:

**Comment by sekaiga** [comment]
i found the reason.
the KUBECONFIG=/etc/kubernetes/admin.conf in the ~/.bash_profile had been removed.
add this config back,it works.
i don't know why had been removed.
i think the error message is not very clearly.

**Comment by kusha** [comment]
@simbo1905 
Hi, I had the same problem. Upgrade to [origins-client v3.9.0](https://github.com/openshift/origin/releases) solved the issue for me.

**Comment by f-z** [comment]
I had the same cronjob matches multiple kinds error message and turns out it was just the authentication that had expired.

Reauthenticated by issuing new certs for the cluster (as a .yaml file in the .kube/configs/ folder) and that resolved it.

**Comment by ahipe101** [comment]
I got this error!

root@ubuntu-xenial:~# kubectl get all -n --all-namespaces
error: {batch  cronjobs} matches multiple kinds [batch/v1beta1, Kind=CronJob batch/v2alpha1, Kind=CronJob]
