### ISSUE TITLE
Design: Handle time skew in the cluster.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#6159]
This is an umbrella issue for handling time skew in Kubernetes.

**Comment by davidopp** [comment]
@davidopp

**Comment by davidopp** [comment]
See also #1651 which Dawn pointed me to.

**Comment by davidopp** [comment]
A few observations from our meeting
* @dchen1107 pointed out that the client is generating some local timestamps, which is bad
* we should make ntpd or something like it part of the node spec (required for using k8s)
* NodeController should mark nodes with bad clocks as NodeReady=Unknown (or something like that); we can do that now thanks to #6217 

@gmarek @davidopp

**Comment by bprashanth** [comment]
For the nodecontroller case maybe we can just use the clock on the etcd master? i.e always allow etcd to set the time and compute the ttl, sending us a watch event on expiration.

**Comment by davidopp** [comment]
That's an interesting idea, using etcd TTL expiration event as a poor-man's asynchronous alarm service. My concerns would be:
1) does etcd make any kind of guarantee about the accuracy of TTL expiration and associated watch event, or is it just best-effort
2) is there some way to figure out the amount of time remaining on such an alarm, or is the only interface "notify me when the TTL expires"

A related idea we discussed (and have used in other systems) is to just have each component use the "last updated time" from the object it most recently read from the store, as its "now" time. As long as the store is being updated reasonably often, this can work.

I'm not sure any of this is necessary though. Probably just synchronizing the clocks on the machines and saying code needs to be resilient to up to X amount of clock skew (e.g. make sure all timeout values are a reasonably large multiple of X) is sufficient.

**Comment by davidopp** [comment]
I discussed this with @erictune and others, and we decided to just add comments to the Getting Started guides saying you need to be running ntpd on all of your nodes. I'll do this.

**Comment by justinsb** [comment]
Should we close?  It sounds like we've decided that we don't want to do anything more than ntp, and it is generally well understood that you should be running something like ntp.

**Comment by justinsb** [comment]
The "asking for permission" approach did not yield a no, though it didn't yield a yes either, so going to try the "begging forgiveness" approach :-)

Closing; our recommendation is to run NTP.

Please comment if I should reopen.
