### ISSUE TITLE
Unable to authenticate user using x509 certs

### ISSUE THREAD

**Issue by arunjohn** [kubernetes/kubernetes#61594]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Unable to Authenticate using x509 certs as per documentation.
Currently using a script that would automate creating user certs, and creating necessary csr and getting it approved as shown below:

```
#!/bin/bash

cluster=test-operations-k8
namespace=demo
username=tesla


openssl genrsa -out $username.pem 2048


openssl req -new -key $username.pem -out $username.csr -subj "/CN=$username"



cat <<EOF | kubectl create -n $namespace -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user-request-$username
spec:
  groups:
  - system:authenticated
  request: $(cat $username.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF



kubectl certificate approve user-request-$username


kubectl get csr user-request-$username -o jsonpath='{.status.certificate}' | base64 -d > $username.crt

kubectl --kubeconfig ~/.kube/config-$username config set-cluster $cluster --insecure-skip-tls-verify=true --server=https://$cluster.eastus.cloudapp.azure.com
kubectl --kubeconfig ~/.kube/config-$username config set-credentials $username --client-certificate=$username.crt --client-key=$username.pem --embed-certs=true
kubectl --kubeconfig ~/.kube/config-$username config set-context $cluster --cluster=$cluster --user=$username
kubectl --kubeconfig ~/.kube/config-$username config use-context $cluster

echo "Config file for $username has been created successfully !"
```

The error I usually get while using this script is as shown below:

```
# kubectl --kubeconfig ~/.kube/config-tesla get deployments -n demo
error: You must be logged in to the server (Unauthorized)
```

**What you expected to happen**:

I would expect the above mentioned command to list the nodes in the demo namespace

**How to reproduce it (as minimally and precisely as possible)**:

Please try to use this script, and create appropriate roles and rolebindings for the user to access the pods in the namespace.

**Anything else we need to know?**:

I had used the kubeconfig from the master server.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Azure
- OS (e.g. from /etc/os-release):
Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig sig-auth-bugs

**Comment by liggitt** [comment]
a client certificate must request `client auth` key usage, not `server auth`
