### ISSUE TITLE
Update lv-provisioner image in e2e tests for k8s 1.10

### ISSUE THREAD

**Issue by ianchakeres** [kubernetes/kubernetes#61596]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We need to update local volume provisioner used in local PV e2e tests for k8s 1.10, by leveraging a new provisioner image (v2.1.0).

**Environment**:
- Kubernetes version: v1.10

**Comment by jdumars** [comment]
@ianchakeres @saad-ali  @msau42 should this block the 1.10 release in your opinion?

**Comment by msau42** [comment]
No not a blocker
