### ISSUE TITLE
new nodes in cluster become very slow

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#61607]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When there are no enough resourse in my cluster,I need to add some new nodes in it (not many).Then all schedule come to new nodes.Soon the new nodes cannot hold the pressure and docker on this nodes become very slow.This make this nodes cannot work at that time.

**What you expected to happen**:

Why kube-scheduler do not have a algorithums to avoid it?It seems users have to develop themselves

**How to reproduce it (as minimally and precisely as possible)**:

Add a few nodes to a  rapidly growing cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.6.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ravisantoshgudimetla** [comment]
It would be helpful if you could provide more information. An example would be number of pods that have gone to new node, along with pod descriptions that have gone there. This would help us to debug further.
