### ISSUE TITLE
why kubelet was not started   /etc/kubernetes/pki/ca.crt: no such file or directory ?

### ISSUE THREAD

**Issue by qq9338745** [kubernetes/kubernetes#61629]
i just filed the bug #61577 but it was closed as configuration issue.  i just paste my step and ask for help what's wrong with my step:

i have just want to enable the one node(infbjvm555) kubernetes master.
here is my step :

Preparation :
  os is Oracle Linux release 7.3  or redhat7.1
1）swapoff -a to close swap .
2) disable selinux.
3) #vi   /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

installation:
1) Installed the docker and configured the cgroup to systemd. restart docker. 
    docker version can be 17.03 or 17.06.
2) install kubeadm, kubelet和kubectl 
  yum install -y kubelet kubeadm kubectl
     
[root@infbjvm555 yum.repos.d]# rpm -qa|grep kub
kubernetes-cni-0.6.0-2.0.1.el7.x86_64
kubernetes-cni-plugins-0.6.0-2.0.1.el7.x86_64
kubelet-1.9.6-0.x86_64
kubectl-1.9.6-0.x86_64
kubeadm-1.9.6-0.x86_64
     
  systemctl enable kubelet ;    
  systemctl start kubelet  ;  
  at this moment, the error was reported:
  .............................................
  Mar 23 11:15:54 infbjvm555 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 23 11:15:54 infbjvm555 systemd: Unit kubelet.service entered failed state.
Mar 23 11:15:54 infbjvm555 systemd: kubelet.service failed.
Mar 23 11:16:04 infbjvm555 systemd: kubelet.service holdoff time over, scheduling restart.
Mar 23 11:16:04 infbjvm555 systemd: Started kubelet: The Kubernetes Node Agent.
Mar 23 11:16:04 infbjvm555 systemd: Starting kubelet: The Kubernetes Node Agent...
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033441 6392 feature_gate.go:226] feature gates: &{{} map[]}
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033601 6392 controller.go:114] kubelet config controller: starting controller
Mar 23 11:16:05 infbjvm555 kubelet: I0323 11:16:05.033612 6392 controller.go:118] kubelet config controller: validating combination of defaults and flags
Mar 23 11:16:05 infbjvm555 kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Mar 23 11:16:05 infbjvm555 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 23 11:16:05 infbjvm555 systemd: Unit kubelet.service entered failed state.
Mar 23 11:16:05 infbjvm555 systemd: kubelet.service failed.

[root@infbjvm555 log]# cd /etc/kubernetes/
[root@infbjvm555 kubernetes]# ls -rlt
total 0
drwxr-xr-x 2 root root 6 Mar 22 03:30 manifests

actually, there is no /etc/kubernetes/pki/ dir and files.

the question is :
1) after we issue " systemctl start kubelet "; do we need  "kubelet.service" are running properly ? 
  currently , the kubelet service can't be started because this issue.   
  if we run "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 " when the kubelet service was not started, the kubeadm init will be failed.

2) i can use "kubeadm init " to solve it ( the required  files ( /etc/kubernetes/pki/ca.crt) will be created after run " kubeadm init") , but after that ,when i run "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 " , it failed again.

**Comment by liggitt** [comment]
> after we issue " systemctl start kubelet "; do we need "kubelet.service" are running properly ? currently , the kubelet service can't be started because this issue.

No, it is expected the kubelet service will continuously restart until ‘kubeadm init‘ on a master or ‘kubeadm join‘ on a node. 

> if we run "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 " when the kubelet service was not started, the kubeadm init will be failed.

On a clean machine, that should work. cc @kubernetes/sig-cluster-lifecycle-bugs 

> i can use "kubeadm init " to solve it ( the required files ( /etc/kubernetes/pki/ca.crt) will be created after run " kubeadm init") , but after that ,when i run "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 " , it failed again.

Before running init again on an already setup machine, you probably need to ‘kubeadm reset‘

**Comment by qq9338745** [comment]
thanks  for  @liggitt  reply.
can we summerize the configuration step for **one node master**  and point out what's wrong for my step ?

**Preparation:**
1）swapoff -a to close swap .
2) disable selinux.
3) #vi /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

**installation:**

1) Installed the docker and configured the cgroup to systemd. restart docker.
   docker version can be 17.03 or 17.06.
2) install kubeadm, kubelet和kubectl
   yum install -y kubelet kubeadm kubectl
   systemctl enable kubelet;
   systemctl start  kubelet;
   
   at this point, kubelet will be not started properly and /etc/kubernetes/pki/ca.crt was not created. ( this was expected as confirmed by you).
    
   
3)  next,  **_what  should  i do next to initialize my master ?_** i was following [](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/), but it doesn't work, can you point what's run with my operation ?

   if i run " kubeadm init " :
   
   [root@infbjvm555 kubernetes]# kubeadm init
[init] Using Kubernetes version: v1.9.6
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
      [WARNING FileExisting-crictl]: crictl not found in system path
      [WARNING HTTPProxy]: Connection to "https://localhost_ip:6443" uses proxy "http://cn-proxy.test.com:80". If that is not intended, adjust your proxy settings
      [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://cn-proxy.test.com:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [infbjvm387.cn.oracle.com kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 localhost_ip]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
        - There is no internet connection, so the kubelet cannot pull the following control plane images:
                - gcr.io/google_containers/kube-apiserver-amd64:v1.9.6
                - gcr.io/google_containers/kube-controller-manager-amd64:v1.9.6
                - gcr.io/google_containers/kube-scheduler-amd64:v1.9.6

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'
couldn't initialize a Kubernetes cluster

 otherwise, if i run  "kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16 ",
 then i will get error "
 Mar 23 11:09:56 infbjvm555 kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory "

**Comment by kad** [comment]
After this `kubeadm init` failure, which files do you have in `/etc/kubernetes/` ?

Also, can you show output of 'systemctl status kubelet' ?

Another thing, regarding warnings from `kubeadm init`:
```
[WARNING HTTPProxy]: Connection to "https://localhost_ip:6443" uses proxy "http://cn-proxy.test.com:80". If that is not intended, adjust your proxy settings
[WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://cn-proxy.test.com:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
```
please, make sure that NO_PROXY environment variable before running `kubeadm init` is set  something like `NO_PROXY=10.96.0.0/12,192.168.0.0/16`  (e.g. if your $localhost_ip is from 192.168.0.0/16 range).

**Comment by qq9338745** [comment]
before to run  "kubeadm init",  
there is only manifest dir (and files)  and empty  pki dir .
after  run  "kubeadm init":

[root@infbjvm555 kubernetes]# ls -rlt
total 36
drwxr-xr-x 2 root root  109 Mar 26 10:40 manifests
drwxr-xr-x 2 root root 4096 Mar 26 10:40 pki
-rw------- 1 root root 5450 Mar 26 10:40 admin.conf
-rw------- 1 root root 5562 Mar 26 10:40 kubelet.conf
-rw------- 1 root root 5486 Mar 26 10:40 controller-manager.conf
-rw------- 1 root root 5434 Mar 26 10:40 scheduler.conf

[root@infbjvm555 kubernetes]# systemctl status kubelet -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Mon 2018-03-26 10:40:50 CST; 5h 18min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 10106 (kubelet)
   Memory: 43.5M
   CGroup: /system.slice/kubelet.service
           └─10106 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0 --cgroup-driver=systemd --rotate-certificates=true --cert-dir=/var/lib/kubelet/pki

Mar 26 15:59:11 infbjvm555.cn.oracle.com kubelet[10106]: W0326 15:59:11.275064   10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:11 infbjvm555.cn.oracle.com kubelet[10106]: E0326 15:59:11.275292   10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 26 15:59:16 infbjvm555.cn.oracle.com kubelet[10106]: W0326 15:59:16.276954   10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:16 infbjvm555.cn.oracle.com kubelet[10106]: E0326 15:59:16.277233   10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 26 15:59:21 infbjvm555.cn.oracle.com kubelet[10106]: W0326 15:59:21.278736   10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:21 infbjvm555.cn.oracle.com kubelet[10106]: E0326 15:59:21.279056   10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 26 15:59:26 infbjvm555.cn.oracle.com kubelet[10106]: W0326 15:59:26.280505   10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:26 infbjvm555.cn.oracle.com kubelet[10106]: E0326 15:59:26.280742   10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Mar 26 15:59:31 infbjvm555.cn.oracle.com kubelet[10106]: W0326 15:59:31.282295   10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:31 infbjvm555.cn.oracle.com kubelet[10106]: E0326 15:59:31.283431   10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

sorry , i will modify this  "NO_PROXY" issue on this node and rerun, but this issue remains even i set  it on another node.

i will  run " kubeadm reset "  to reinitialise kubeadm

**Comment by kad** [comment]
@qq9338745 according to your latest logs and provided information, kubeadm successfully created ca.crt and being able to launch kubelet correctly. Error messages from kubelet like 
```
Mar 26 15:59:11 infbjvm555.test.com kubelet[10106]: W0326 15:59:11.275064 10106 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 26 15:59:11 infbjvm555.test.com kubelet[10106]: E0326 15:59:11.275292 10106 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
are normal, until the moment then you'll install CNI plugins based on your wish (see Network plugin installation section in Kubeadm docs).

Next thing, docker proxies: according to your logs, it is good that you updated NO_PROXY variable for docker, it helps for docker to fetch images properly.

Last thing, proxy settings for kubeadm itself. With working docker and initialized kubelet properly, you're still getting warnings from kubeadm and eventually failure while init from kubeadm. Reason for that is that proxy variables are not properly set while running kubeadm. In that case kubeadm is not able to communicate with launched kubelet, and then fails with timeout. You should have session inside your console something like that:
```console
# kubeadm reset
# export HTTP_PROXY=http://cn-proxy.test.com:80/
# export HTTPS_PROXY=http://cn-proxy.test.com:80/
# export NO_PROXY=localhost,172.16.0.0/16,127.0.0.1,10.244.0.0/16,test.com
# kubeadm init --kubernetes-version=v1.9.6 --pod-network-cidr=10.244.0.0/16
```
this last call for `kubeadm init` should now return successfully (and not complaining on HTTPProxy or HTTPProxyCIDR checks), and then you will be able to proceed with `(3/4) Installing a pod network` step of the documentation.

**Comment by qq9338745** [comment]
@kad 

**_follow your guide, there is still warning,_**

[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.06.2-ol. Max validated version: 17.03
        [WARNING FileExisting-crictl]: crictl not found in system path
        [WARNING HTTPProxy]: Connection to "**_https://infbjvm555_ip:6443_**" uses proxy "http://cn-proxy.test.com:80". If that is not intended, adjust your proxy settings
        [WARNING HTTPProxyCIDR]: connection to "**_10.96.0.0/12_**" uses proxy "http://cn-proxy.test.com:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
    
    so  i  have to add the  realy ip address of infbjvm555 and 10.96.0.0/12 to NO_proxy, kubeadm init succeed.
  **_my question is :_**  : 
   from my test, it seems localhost or 127.0.0.1 don't work, it need add the  realy ip address of kubelet master  to no_proxy, **_is it expected or a bug ?_**

**Comment by qq9338745** [comment]
thanks @kad  suggestion, i followed your guide but there is still warning.

[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.06.2-ol. Max validated version: 17.03
        [WARNING FileExisting-crictl]: crictl not found in system path
        [WARNING HTTPProxy]: Connection to "https://infbjvm555_ip:6443" uses proxy "http://cn-proxy.test.com:80". If that is not intended, adjust your proxy settings
        [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://cn-proxy.test.com:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
 
so **_i have to add real ip address of infbjvm555 and 10.96.0.0/12 to no_proxy_**, it finally works.

my question is :
 it seems **_localhost or 127.0.0.1 does not work  for this issue_** (and i also should **add   10.96.0.0/12** to no_proxy) , is it a bug or by design ?

**Comment by kad** [comment]
`localhost` or `127.0.0.1` are not considered as good endpoints for API server and other k8s control plane services. So, control plane uses the real node IP address. So, in NO_PROXY (or no_proxy) variable user should have all ranges that covers node IP addresses (in your case, network from where infbjvm555 and other your nodes) and all the ranges that are used in cluster (pod CIDR, and services CIDR), in your case it is 10.96.0.0/12. In example above that I've wrote earlier, my lab uses 172.20.0.0/24 range for the nodes, so I'm adding whole 172.16.0.0/12 range to the NO_PROXY.

In general, it is good to have inside NO_PROXY all the ranges defined in RFC1918 (10/8, 172.16/12, 192.168/16). This way there is low chance of conflicts between internal corporate networks and proxies.

**Comment by kad** [comment]
@qq9338745 so, if after adjusting your environment kubeadm installs the cluster, can we close this issue ?

**Comment by timothysc** [comment]
So I'm going to close this issue, as it's not actually a bug or problem.  

The validated stack elements are their associated configs are well defined.  If you have further support-esk questions I recommend joining the sig-cluster-lifecycle and kubeadm slack channels.
