### ISSUE TITLE
AWS Feature: Services should be able to use an existing ELB

### ISSUE THREAD

**Issue by rdrgmnzs** [kubernetes/kubernetes#61625]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

Separation of responsibility some times means that the operator for a k8s cluster may not have the permissions to create an ELB. Being able to attach and existing one would be extremely helpful.

**What you expected to happen**:
I would like the ability to specify an existing AWS ELB (internal-myelb-12345.us-west-1.elb.amazonaws.com) instead of having the aws provider create one.

**Comment by tanelso2** [comment]
I agree this would be very useful

**Comment by tabossert** [comment]
Lots of ELB's get expensive, this feature would simplify and save people lots of money.

**Comment by enleur** [comment]
Still actual

/reopen

**Comment by yunfeizuo** [comment]
This k8s-ci-robot should be disabled. It doesn't make sense to close active issues without any conclusion.

**Comment by tsmgeek** [comment]
This would be a useful function especially when using NLBs.

A hacky solution may be to have a separate service that has the LoadBalancer and points to NodePorts that have been opened up by other Services, it says that if you do not specify a selector then it does not route data but may trigger the LB to point to all the K8s nodes on the indicated nodeports.

https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by kistora** [comment]
Still waiting for a solution.

**Comment by drewhemm** [comment]
Am also hitting this issue. Creating multiple load balancers is inefficient and in many cases defeats the intended use-case benefits, for all types of AWS load balancer.

As long as we are not creating port collisions, a load balancer should be reused where possible as it is more cost-effective and entails fewer resources to manage.
