### ISSUE TITLE
Replace goamz with official go AWS SDK

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#6162]
Does anyone have any reason not to replace the goamz AWS client binding with the official AWS client binding, now that it has reached feature-complete:
https://aws.amazon.com/blogs/aws/preview-the-latest-updates-in-the-master-branch-aws-sdk-for-go/

The goamz binding we're using:
1) is incomplete - for example, there is no way to page through EC2 instances, so fails if you have more than 50 (I think that's the default page size)
2) has been forked all over the web but never re-integrated - there is no real "goamz" library.
3) is likely dead now that there is an official AWS library

Obviously the new library may have bugs, but I personally would rather deal with those than continue to invest in goamz.

**Comment by a-robinson** [comment]
Sounds good to me.

**Comment by jsdir** [comment]
I'm working on this. Some features from `goamz` are [still being merged into `aws-sdk-go`](https://github.com/awslabs/aws-sdk-go/pull/182).

**Comment by justinsb** [comment]
@jsdir : it's great that you are working on this.  Metadata retrieval is a big one to leave out.  My guess is that it's because there isn't a schema for it (maybe!)

How are you working on the port & how is it going?  Are you building a second implementation of the EC2 interface?  (That is what I had in mind when putting so many methods into EC2/goamzEC2).  Is your code visible on a branch somewhere?

**Comment by jsdir** [comment]
@justinsb The initial port is at my [`6162-aws-sdk-go` branch](https://github.com/jsdir/kubernetes/tree/6162-aws-sdk-go). Although some parts of the interface were still bound to the `goamz` implementation, `aws-sdk-go`'s Instance struct is very similar to that of `goamz`.

**Comment by jsdir** [comment]
Waiting for the following:
- [ ] `GetMetadata` https://github.com/awslabs/aws-sdk-go/pull/192
- [ ] `IsRegionValid` https://github.com/awslabs/aws-sdk-go/issues/108

**Comment by justinsb** [comment]
@jsdir: I wonder if we should just pull in your code for GetMetadata and implement something similar for IsRegionValid, until something is put into the official aws-sdk-go.

I'm going to be (re)implementing ELB soonish, which brings in a whole new set of API calls, so I'd much rather be using aws-sdk-go than creating more porting work...

Thoughts?

**Comment by jsdir** [comment]
@justinsb: I agree, the development at `aws-sdk-go` is not as punctual as I had hoped. I'll add `GetMetadata` and `IsRegionValid` to the AWS cloudprovider for now.

**Comment by jsdir** [comment]
@justinsb: You can continue porting the cloudprovider to `aws-sdk-go`. There have been many additions since my last changes and you would probably be more familiar with their use.

**Comment by iterion** [comment]
@justinsb I've got some free time today, I can try to pick up the implementation of this if you want?

As it stands @jsdir's PRs are still not merged into `aws-sdk-go` so I'll just reimplement in kubernetes.

**Comment by justinsb** [comment]
@iterion That would be awesome - thank you!

**Comment by josegonzalez** [comment]
This should be closed as of #8297, no?

**Comment by iterion** [comment]
Yeah, this should be closed now.
