### ISSUE TITLE
Persistent Volume size vs nfs

### ISSUE THREAD

**Issue by zolij** [kubernetes/kubernetes#61641]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig storage

**What happened**:
I created a nfs persistent volume with 1 Gi size, then I created persistent volume claim and pod with that claim attached. After that inside the pod I write ~2G data with dd (from /dev/urandom). If I check nfs data from other location, the whole data is there.

**What you expected to happen**:
Say no more space or terminate pod

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f nfs-pv.yaml.txt
kubectl create -f nfs-pvc.yaml.txt
kubectl create -f nfs-pod.txt

Exec shell into pod and overcommit the 1 Gi persistent volume size (it's mounted under /mnt).

**Anything else we need to know?**:
I tried with the static method and with dynamic proviser too (from external storage repo), it's the same result.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6+coreos.0
- Cloud provider or hardware configuration: bare metal (on top of vmware)
- OS (e.g. from /etc/os-release): Container Linux by CoreOS
- Kernel (e.g. `uname -a`):  4.14.19-coreos
- Install tools: kubespray
- Others: yaml files attached

[nfs-pod.yaml.txt](https://github.com/kubernetes/kubernetes/files/1845584/nfs-pod.yaml.txt)
[nfs-pv.yaml.txt](https://github.com/kubernetes/kubernetes/files/1845585/nfs-pv.yaml.txt)
[nfs-pvc.yaml.txt](https://github.com/kubernetes/kubernetes/files/1845586/nfs-pvc.yaml.txt)

**Comment by msau42** [comment]
Kubernetes does not do capacity enforcement of PVs.  It is up to the underlying storage backend to enforce capacity.  So you may need to configure your nfs server to use quota.
