### ISSUE TITLE
Provide a solution for instance-specific Kubelet configuration

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61647]
Certain flags, like `--hostname-override` are instance-specific, and thus won't play nice with shared configmaps under dynamic Kubelet config.

We should still have a solution to expose these parameters via a versioned Kubelet config API, rather than command-line flags.

A simple solution could be:
- Add a `KubeletInstanceConfiguration` object to `kubelet.config.k8s.io/v1beta1`.
- Like `KubeletConfiguration`/`--config`, serialize to a file and provide via `--instance-config`.
- This object is not configurable via dynamic Kubelet config, as it contains parameters that should be deployed with the node.

It strikes me that `KubeletInstanceConfiguration` could also be a natural place for any fields that describe local topology maintained by the Kubelet, e.g. `--dynamic-config-dir` and `--root-dir`. Importantly, these are places the Kubelet should *manage* stuff on the node, *not* places the Kubelet should *get* stuff; the latter should be dynamically configurable so that the *stuff the Kubelet gets* (e.g. `kc.StaticPodPath`) is also deploy-able via dynamic config in the future, if we so desire.

**Comment by mtaufen** [comment]
Also things like `--runonce`.

**Comment by mtaufen** [comment]
`kustomize` should do the merge, since it's a k8s-style API.
Unique identifiers comprise only a few parameters, I agree. But however we plumb this info, I don't want to relegate it to an unversioned API.
The best world is where these things are automatically discovered by the Kubelet, so we don't have to parameterize them in the config.

The other item in the issue description is basically whether paths the Kubelet creates should be in per-instance, but I think that is really more a topic of how we handle paths in config; we'd generally expect homogeneous nodes to have homogeneous paths, and the blocking issue is figuring out what to do with  fields that can never be homogeneous across nodes.

**Comment by errordeveloper** [comment]
I think that `--register-with-taints` and `--node-labels` would be two candidates to solve first. These are commonly used for identifying groups of nodes (like InstanceGroups in kops, or NodeGroups in eksctl, and (I guess) GKE node pools).

Labels as well as taints can be set on individual nodes via the API, but one needs to know what nodes they want to apply these two. It's hard to determine with certainty when a group of nodes is concerned, and much of the time one probably wants to set labels and/or taints before node even registers itself.
I believe labels and taints should be added to `KubeletConfiguration` to start with. We may wish to provide a way to override these for individual nodes, however that it's probably fine to suggest that one should use the API for that.
I also think that on restart any labels that were removed from the node object and are still present in the config file should be reinstated, i.e. config file should be authoritative.

Having said that, I am not entirely familiar with how the config API works and if we have per-node configs or a global config. If it's global, then I take my suggestion back, unless there is a plan to evolve the API.

**Comment by SergeyKanzhelev** [comment]
@mtaufen as DynamicKubeletConfig is deprecated and will be removed (KEP: https://github.com/kubernetes/enhancements/issues/281), this is no longer needed, correct? All configuration will be instance specific

/close
