### ISSUE TITLE
Determine whether we should continue to require UID in node config source reference

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61643]
#### Reposted from https://github.com/kubernetes/kubernetes/pull/60100#discussion_r176604265:

This has been a requirement of dynamic Kubelet config since the original proposal, to require users to be completely explicit (time and space) about which ConfigMap to use. If the UID in the config source doesn't match the UID of the ConfigMap, the Kubelet currently rejects it.

IIRC there were concerns along the lines of ConfigMaps being deleted and recreated with the same name but different content... though this is less of an issue today now that we have the --append-hash option in kubectl (obviously the potential for in-place ConfigMap mutation still exists, but if users are using --append-hash I wouldn't expect them to mutate the ConfigMap after creation).

The Kubelet also checkpoints by UID, so it was convenient to already have this specified in the object ref, though I guess if we relaxed this requirement it could just resolve the UID and stick it in the local copy of the config source when it first downloads the ConfigMap.

I can't remember other reasons to require UID, if any.

---

A massive downside of requiring the UID is that you cannot fully-statically-specify the configuration of a cluster; the UID is assigned by the API server at creation time.

This *must* be resolved before dynamic Kubelet config (https://github.com/kubernetes/features/issues/281) goes beta.

**Comment by tianshapjq** [comment]
Without uid, can dynamic config be watching for the changes of a configmap (that is, if the content of a configmap changes, kubelet will restart and apply the configurations automatically.)? Or delete the old configmap and recreate a new one would do?

**Comment by mtaufen** [comment]
Dynamic Kubelet config never responds to ConfigMap mutations. This is a
safety feature that encourages incremental rollout (you must create a new
ConfigMap, and update each config source reference).

**Comment by liggitt** [comment]
> Dynamic Kubelet config never responds to ConfigMap mutations.

I'd leave that up to the thing driving the kubelet. It is quite counter-intuitive for a restarted kubelet to not use the config in the referenced configmap *sometimes*

**Comment by mtaufen** [comment]
Which is why I initially wanted [Verifiable ConfigMaps](https://docs.google.com/document/d/1yYmyYJu2mVqgOBPCSd2c_IPnGWItirbcN_5qbJaWZN0/edit#heading=h.p9zm9o7oiea0), to warn in cases of mutation. The argument that killed Verifiable ConfigMaps was that people could just use RBAC to restrict mutators to a few responsible individuals...

**Comment by mtaufen** [comment]
I don't like opening the door to the "oops I updated the configmap in place and hosed all my nodes" footgun, either.

**Comment by mtaufen** [comment]
@deads2k

**Comment by mtaufen** [comment]
Conversation diverged to slack, reposting here for record-keeping:

mtaufen [9:59 AM]
how do you pin something to a resource version?

liggitt [9:59 AM]
put resourceVersion in the object reference
and have the kubelet refuse to use it if the config map's resourceVersion doesn't match
that's the behavior you say you want, but you're depending on the kubelet having a local previously retrieved version of the configmap to make that actually effective
if you want to lock to a particular version of a configmap, make it explicit

mtaufen [11:01 AM]
Yes, that's an option. ObjectReference has ResourceVersion already, we'd just have to respect it.
Does ResourceVersion reset if you delete and recreate an object?

liggitt [11:03 AM]
it does not today, but I wouldn't make assumptions about its behavior forever

mtaufen [11:03 AM]
Since a (naïve) expectation would be that if a ConfigMap were deleted by accident, you could just create it again to "repair" the cluster - but if this changes ResourceVersion there's an unintuitive step (update the Node too).

liggitt [11:03 AM]
namespace+name+uid+resourceVersion is totally unique
namespace+name == location
uid == instance
resourceVersion == specific version
recreating already changes uid

mtaufen [11:03 AM]
right

mtaufen [11:09 AM]
The API we're talking about is "specify more stuff to make it more safe," but I'd prefer "safe with minimal specification"... (as you correctly pointed out, today it's "safe-ish with confusing potential skew if a configmap updates", which shouldn't be our endgame).
If we had immutable objects...

liggitt [11:11 AM]
I really dislike limiting power in order to try to guarantee we ignore data in the config map in some circumstances, but a late-starting kubelet or a kubelet whose local state is wiped won't actually live up to those promises
I do want node status to indicate the version of the config it is using
should be able to look at a Node object, and see what config name/namespace/uid/resourceVersion it is running (edited)

mtaufen [11:14 AM]
I agree with "should be able to look at a Node object, and see what config name/namespace/uid/resourceVersion it is running" in node status; I think I'd actually like a structured status with a subset isomorphic to the configSource, and an additional message, for error reporting
I understand how this can look like "limiting power" when you compare it to something like configmap volume source...

liggitt [11:15 AM]
@deads2k is in the process of building out dynamic config for our apiserver... would be good to ask him how he would use this to drive the kubelet
he's thought through the "thing drives dynamic config of components" a bit more than me recently

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/issues/56896 wrt structured status

**Comment by deads2k** [comment]
I plan to solve this in openshift using a single configmap and an external orchestrator that can track a separate, long-term state and have a simple consumer process that takes only the config file.  This gives me a layered separation of concerns that permits the config handling to changed at a different cadence than the thing it is managing so that skew management between components is easier.

If you choose to try to manage coordination of configuration updates inside of the thing you're managing, you end up facing problems of permissions, history tracking, update cadence, version skew, and "what if the process I'm managing is failing" that you don't have to face if you manage the configuration externally.

In the simple consumer process case, you simply have the consumer use whatever is provided and the config orchestrator can decide how track history however they wish (status in a different resource, a separate configmap, on disk in ansible).

Trying to create that history synthetically in a single process, I'm not sure how you'll maintain the required state.  Pinning a configmap with a resource version is a starting point, but I suspect there are many edges to deal with.

**Comment by mtaufen** [comment]
>If you choose to try to manage coordination of configuration updates inside of the thing you're managing, you end up facing problems of permissions, history tracking, update cadence, version skew, and "what if the process I'm managing is failing" that you don't have to face if you manage the configuration externally.

I'm not sure you actually avoid these problems... don't you just have to solve them (from scratch, ignoring work that has already happened in core k8s) for your new layer of infrastructure?

>Trying to create that history synthetically in a single process, I'm not sure how you'll maintain the required state.

I don't think we're talking about tracking a full history of config *in* the Kubelet. That's fine to leave up to an orchestrator. 

In fact, a major point of Dynamic Kubelet Config is to enable orchestrators by giving them an API to build on, so they don't have to directly munge files on the node. For example, the Machines API can consume DKC.

**Comment by deads2k** [comment]
> If you choose to try to manage coordination of configuration updates inside of the thing you're managing, you end up facing problems of permissions, history tracking, update cadence, version skew, and "what if the process I'm managing is failing" that you don't have to face if you manage the configuration externally.
> 
> I'm not sure you actually avoid these problems... don't you just have to solve them (from scratch, ignoring work that has already happened in core k8s) for your new layer of infrastructure?

By creating a separate component that uses an existing configapi with our normal API guarantees, then a single version of the orchestrating process can easily manage multiple skewed levels of the base process.  This allows us to update the orchestration process out of band and only have a single level of the orchestration process so that you don't have to keep multiple API behaviors between three levels of the base process in sync.  In addition, the maintenance of the orchestration process is easy since its uptime needs are comparatively low and it operates at low scale (it's only managing a few thousand things at most).  It also means that the permissions of the orchestration piece can be broad enough to manage things like history using objects that that the base process can't access.

So separating the processes breaks the problem into smaller chunks that avoid many of the problems that combining processes introduces. 

I'm not trying to force the kubelet config any which way, just pointing out how we're planning solving it for every component we develop and if you look at something like the operator pattern, it does works on exactly the same principle.

**Comment by mtaufen** [comment]
>By creating a separate component that uses an existing configapi with our normal API guarantees, then a single version of the orchestrating process can easily manage multiple skewed levels of the base process. 

Can you clarify what you mean by "multiple skewed levels of the base process?"

>so that you don't have to keep multiple API behaviors between three levels of the base process in sync.

What are the three levels?

>In addition, the maintenance of the orchestration process is easy since its uptime needs are comparatively low and it operates at low scale (it's only managing a few thousand things at most). It also means that the permissions of the orchestration piece can be broad enough to manage things like history using objects that that the base process can't access.

I wasn't really sure what context to wrap this with. Are you building this in Kubernetes or outside of Kubernetes? How does it interact with each node?

>I'm not trying to force the kubelet config any which way

Ok, sg. 

Regarding all the orchestration pieces; I think we're in general agreement that a controller needs to make higher-level decisions than the base process, including assigning a config. In my mind, wrt Kubelet config, that's the Machines API's responsibility (via e.g. MachineSet), which it can accomplish by consuming the dynamic Kubelet config feature. 

If such a controller can operate at the Kubernetes API level, without having to delve into node internals, that sounds like an advantage to me, but I guess IDK what your spectrum of needs looks like - it kind of sounds like you have a need to configure several processes other than the Kubelet, and don't have a way to do something simple like use a ConfigMap volume source. Is that the case?

**Comment by mtaufen** [comment]
Coming back to the original issue:

>A massive downside of requiring the UID is that you cannot fully-statically-specify the configuration of a cluster; the UID is assigned by the API server at creation time.

There's a caveat to this, which is that Node objects are dynamic in the first place. They are unlikely to appear in a static specification of a cluster; whereas Machine objects (from the Cluster API effort) would. If the machines controller can take care of filling out the details, perhaps we can simply require a fully-explicit (namespace, name, uid, and resource version) specification on the Node. I don't necessarily want to push an unsolved problem up a layer, so here are some other options:

- Simply require `(namespace, name)`, and respond to all ConfigMap updates. 
  - This lets you shoot yourself in the foot if you choose to do so, but doesn't prevent you from following a more conservative deployment strategy.
- Allow progressive pinning, where we respond to updates corresponding to the remaining degree of freedom. For example:
  1. `(namespace, name)` chooses latest `(uid, resourceVersion)`
  2. `(namespace, name, uid)` chooses latest `(resourceVersion)`, which causes new uids (delete/recreate ConfigMap) to be rejected by Kubelet with an error status, but not new resourceVersions (update, patch).
      - I'm not sure this set is very useful. You probably want to treat the ConfigMap as completely mutable or immutable, not halfway between.
  3. `(namespace, name, uid, resourceVersion)` is completely explicit, and all mutations are rejected by Kubelet with an error status.
- Kubelet "auto-pins" to the fully-explicit specification of the ConfigMap version it sees when NodeConfigSource is updated.
  - If a ConfigMap mutation races with assignment across a fleet, config will skew but Kubelets that saw pre-mutation config should reject the new version with an error status.

**Comment by mtaufen** [comment]
I'm leaning towards just `(namespace, name)`, with no pinning (Kubelet respects ConfigMap updates). In many ways this is easier to reason about, and leaves less room for silent skew scenarios:
- ConfigMap does not exist: Kubelet reports error status due to missing source
- ConfigMap is created: Kubelet starts using it
- ConfigMap is updated: Kubelet respects the update (but we discourage this pattern, in favor of rolling out new ConfigMaps)
- ConfigMap is deleted: Kubelet keeps using the config (non-disruptive), but reports error status due to missing source
- ConfigMap is recreated: Kubelet respects any updates (but, again, we discourage this pattern)

**Comment by liggitt** [comment]
> I'm leaning towards just (namespace, name), with no pinning (Kubelet respects ConfigMap updates). In many ways this is easier to reason about, and leaves less room for silent skew scenarios:
> 
> * ConfigMap does not exist: Kubelet reports error status due to missing source
> * ConfigMap is created: Kubelet starts using it
> * ConfigMap is updated: Kubelet respects the update (but we discourage this pattern, in favor of rolling out new ConfigMaps)
> * ConfigMap is deleted: Kubelet keeps using the config (non-disruptive), but reports error status due to missing source
> * ConfigMap is recreated: Kubelet respects any updates (but, again, we discourage this pattern)
> 
> This makes dynamic Kubelet config similar to ConfigMap volume source.

that seems like a reasonable starting point to me
