### ISSUE TITLE
kube-proxy --insecure_skip_tls_verify=true: Unauthorized: Unauthorized

### ISSUE THREAD

**Issue by cnaize** [kubernetes/kubernetes#6164]
Trying to up `kube-proxy`, have the output:
```none
kube-proxy --master="https://master:6443" --insecure_skip_tls_verify=true
I0330 17:43:03.909633    2993 proxier.go:327] Setting Proxy IP to master
I0330 17:43:03.909685    2993 proxier.go:332] Initializing iptables
I0330 17:43:03.922840    2993 server.go:95] Using API calls to get config https://master:6443
E0330 17:43:03.937838    2993 api.go:107] Unable to load services: request [&{Method:GET URL:https://master:6443/api/v1beta1/services?namespace= Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:master:6443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (401) 401 Unauthorized: Unauthorized
E0330 17:43:03.938078    2993 api.go:179] Unable to load endpoints: request [&{Method:GET URL:https://master:6443/api/v1beta1/endpoints?namespace= Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:master:6443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil>}] failed (401) 401 Unauthorized: Unauthorized
```

**Comment by erictune** [comment]
Right now, proxy-server doesn't support using port 6443.  Issue #5917 tracks fixing that.  Until that is closed, you should use --master="http://master:7080.

**Comment by erictune** [comment]
The problem is that a client needs a token to authenticate to the apiserver on 6443, but there is not way to pass a token to kube-proxy.

This could maybe be made to work with the current code with client certs, but I have not tried yet.

**Comment by markllama** [comment]
It appears that this is affecting the Vagrant/Virtualbox cluster as well.

Merely starting up the cluster, looking at the kube-proxy logs on the minions:

Apr 30 19:03:42 kubernetes-minion-1 kube-proxy[3307]: I0430 19:03:42.225044    3307 proxier.go:341] Initializing iptables
Apr 30 19:03:42 kubernetes-minion-1 kube-proxy[3307]: E0430 19:03:42.304586    3307 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
Apr 30 19:03:42 kubernetes-minion-1 kube-proxy[3307]: E0430 19:03:42.305248    3307 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)

**Comment by aveshagarwal** [comment]
I am not able to reproduce this issue as kube-proxy can talk to apiserver at port 6443, and also --insecure_skip_tls_verify is not a valid option for kube-proxy. Seems like this issue does not exist anymore?
