### ISSUE TITLE
Migrate Kubelet --volume-plugin-dir to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61650]
Flag name: `volume-plugin-dir`

Help text:

The full path of the directory in which to search for additional third party volume plugins

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--volume-plugin-dir` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--volume-plugin-dir` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by tianshapjq** [comment]
file an issue to trace all the migrations would be better? too many issues about the migration at present.

**Comment by mtaufen** [comment]
No, each flag is it's own discussion.

**Comment by mtaufen** [comment]
@saad-ali @msau42 is this flag still considered experimental, or can I migrate it without worrying about adding a feature gate?

**Comment by msau42** [comment]
This flag denotes the flex volume directory, which we still support and is GA.

**Comment by gnufied** [comment]
Yeah this is definitely not Alpha feature. Moreover on immutable hosts the current defaults are unworkable (`/usr/libexec` is unwritable), so this needs to be fixed.

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
