### ISSUE TITLE
Migrate Kubelet --runonce to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61652]
Flag name: `runonce`

Help text:

If true, exit after spawning pods from static pod files or remote urls. Exclusive with --enable-server

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--runonce` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by mtaufen** [comment]
This one, specifically, may be appropriate to #61647, because it should never be dynamically-configurable.

**Comment by n4j** [comment]
Possible duplicate of https://github.com/kubernetes/kubernetes/issues/86843

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
