### ISSUE TITLE
Migrate Kubelet --register-node to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61656]
Flag name: `register-node`

Help text:

Register the node with the apiserver. If --kubeconfig is not provided, this flag is irrelevant, as the Kubelet won't have an apiserver to register with. Default=true.

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--register-node` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by mtaufen** [comment]
>If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: #61647.

wrt this shouldn't be configured dynamically

**Comment by liggitt** [comment]
> @liggitt @mikedanese since this flag already depends on a kubeconfig file being present, is there a reason we wouldn't just try to register any time we get a kubeconfig file?

I can't think of a good reason for this degree of freedom... would defer to sig-node on deprecating and removing it

**Comment by n4j** [comment]
Possible duplicate of https://github.com/kubernetes/kubernetes/issues/86843
/remove-priority important-soon
/priority backlog

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
