### ISSUE TITLE
Migrate Kubelet --experimental-qos-reserved to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61665]
Flag name: `experimental-qos-reserved`

Help text:

A set of ResourceName=Percentage (e.g. memory=50%) pairs that describe how pod resource requests are reserved at the QoS level. Currently only memory is supported. [default=none]

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--experimental-qos-reserved` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--experimental-qos-reserved` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by zhangxiaoyu-zidif** [comment]
Does this mean cpu and local ephemeral storage will be supported?

**Comment by derekwaynecarr** [comment]
fyi @sjenning
