### ISSUE TITLE
Migrate Kubelet --image-service-endpoint to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61663]
Flag name: `image-service-endpoint`

Help text:

[Experimental] The endpoint of remote image service. If not specified, it will be the same with container-runtime-endpoint by default. Currently unix socket is supported on Linux, and tcp is supported on windows.  Examples:'unix:///var/run/dockershim.sock', 'tcp://localhost:3735'

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--image-service-endpoint` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--image-service-endpoint` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by cynepco3hahue** [comment]
@mtaufen Does this issue is still relevant?

**Comment by mtaufen** [comment]
If it's not migrated yet, technically yes... but maybe worth closing these and focusing it down to one issue with a checklist.

@SergeyKanzhelev @knabben  @kubernetes/sig-node-bugs Do you know if anyone is actively working on moving this forward for Kubelet (I haven't been working on it lately/WGCS hasn't met in some time)?

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
