### ISSUE TITLE
Migrate Kubelet --experimental-mounter-path to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61666]
Flag name: `experimental-mounter-path`

Help text:

[Experimental] Path of mounter binary. Leave empty to use the default mount.

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--experimental-mounter-path` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--experimental-mounter-path` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by pacoxu** [comment]
Update the status:
- (DEPRECATED: will be removed in 1.23. in favor of using CSI.) Similar to #61668
- #91373 deprecated Kubelet mount related flags in 1.19

/assign

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
