### ISSUE TITLE
Migrate Kubelet --experimental-check-node-capabilities-before-mount to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61668]
Flag name: `experimental-check-node-capabilities-before-mount`

Help text:

[Experimental] if set true, the kubelet will check the underlying node for required components (binaries, etc.) before performing the mount

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--experimental-check-node-capabilities-before-mount` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--experimental-check-node-capabilities-before-mount` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by pacoxu** [comment]
Update the status:
- (DEPRECATED: will be removed in 1.23. in favor of using CSI.)

/assign
I will take care of it in the next release cycle.

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in https://github.com/kubernetes/kubernetes/issues/86843. We will list each issue here that we're closing and the associated flag.

/close
