### ISSUE TITLE
Migrate Kubelet --experimental-kernel-memcg-notification to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61667]
Flag name: `experimental-kernel-memcg-notification`

Help text:

If enabled, the kubelet will integrate with the kernel memcg notification to determine if memory eviction thresholds are crossed rather than polling.

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--experimental-kernel-memcg-notification` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--experimental-kernel-memcg-notification` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by mtaufen** [comment]
This flag was a hack because we saw instability when using this feature. Best route is stabilize and remove the flag, not elevate to versioned config.

**Comment by dashpole** [comment]
To be clear, you are saying we need to add a feature gate, and remove the flag, right?

**Comment by mtaufen** [comment]
You need to add a feature gate and move it to the config API group OR
remove the flag.

**Comment by alexeldeib** [comment]
@mtaufen @dashpole any news about this? I know some large providers use this in production, is there any work in progress to map this to kubelet config? Is there anything blocking simply moving the flag to component config?

I'm interested in using this feature but also want to convert to component config, this was one of the standouts still missing.

**Comment by mtaufen** [comment]
It was just moved: https://github.com/kubernetes/kubernetes/pull/91863

**Comment by SergeyKanzhelev** [comment]
/close

since it is done already
