### ISSUE TITLE
Document API return values in swagger

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#6167]
Swagger supports documentation of HTTP status codes and payload returned, though I'm not sure how to represent different types for different status codes (e.g., status object vs. resource type).

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by bgrant0607** [comment]
Believed to be blocking swagger codegen.

**Comment by brendandburns** [comment]
Started to do this in https://github.com/GoogleCloudPlatform/kubernetes/pull/6613

**Comment by bgrant0607** [comment]
go-restful builds a map of status code to response type:
```
func (b *RouteBuilder) Returns(code int, message string, model interface{}) *RouteBuilder {
	err := ResponseError{
		Code:    code,
		Message: message,
		Model:   model,
	}
	// lazy init because there is no NewRouteBuilder (yet)
	if b.errorMap == nil {
		b.errorMap = map[int]ResponseError{}
	}
	b.errorMap[code] = err
	return b
}
```
Behavior is documented here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api-conventions.md#http-status-codes

**Comment by bgrant0607** [comment]
Still need to add documentation for error cases.

**Comment by nikhiljindal** [comment]
We now document the 200 status and return type in success case for most APIs: https://github.com/kubernetes/kubernetes/blob/3111985564f4bfc769111c5708a01d9d711edf70/pkg/apiserver/api_installer.go#L495.

Need to add all possible statuses and return types there.

**Comment by smarterclayton** [comment]
Since we've improved this and the umbrella issue references it, closing.
