### ISSUE TITLE
Migrate Kubelet --exit-on-lock-contention to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61671]
Flag name: `exit-on-lock-contention`

Help text:

Whether kubelet should exit upon lock-file contention.

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--exit-on-lock-contention` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

As `--exit-on-lock-contention` is an alpha/experimental flag, the feature it configures must either be
feature-gated, or graduated from alpha/experimental status prior to the migration.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by mtaufen** [comment]
This could be appropriate to `--instance-config` (#61647) due to the relationship with `--lock-file` (#61661).

**Comment by ehashman** [comment]
SIG Node Bug Scrub has decided to close the 23 individual flag tracking issues in favour of using the unified tracker in #86843. We will list each issue here that we're closing and the associated flag.

/close
