### ISSUE TITLE
Migrate Kubelet --dynamic-config-dir to kubelet.config.k8s.io or remove the flag

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#61673]
Flag name: `dynamic-config-dir`

Help text:

The Kubelet will use this directory for checkpointing downloaded configurations and tracking configuration health. The Kubelet will create this directory if it does not already exist. The path may be absolute or relative; relative paths start at the Kubelet's current working directory. Providing this flag enables dynamic Kubelet configuration. Presently, you must also enable the DynamicKubeletConfig feature gate to pass this flag.

---

This is part of migrating the Kubelet command-line to a Kubernetes-style API.

The `--dynamic-config-dir` flag should either be migrated to the Kubelet's `kubelet.config.k8s.io`
API group, or simply removed from the Kubelet.

If this could be considered an instance-specific flag, or a descriptor of local topology
managed by the Kubelet, see: https://github.com/kubernetes/kubernetes/issues/61647.

If this flag is only registered in os-specific builds, see: https://github.com/kubernetes/kubernetes/issues/61649.

@sig-node-pr-reviews @sig-node-api-reviews

/assign @mtaufen
/sig node
/kind feature
/priority important-soon
/milestone v1.11
/status approved-for-milestone

**Comment by mtaufen** [comment]
Local, kubelet-managed topology.

**Comment by SergeyKanzhelev** [comment]
Since the feature is scheduled for deprecation, closing the issue.

KEP: kubernetes/enhancements#281

/close
