### ISSUE TITLE
Resources are not checked before scheduling pod with nodeName specified

### ISSUE THREAD

**Issue by arkadyark** [kubernetes/kubernetes#61695]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

> /kind bug

**What happened**: Pod fails with status OutOfCpu

**What you expected to happen**: Pod to remain in 'Pending' until resources were available

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a node with X cpu resources
2. Create a pod with resource requests and limits, specifying in the spec nodeName=[node from step 1]
3. Create a second instance of this pod, pod should stay pending but instead it fails

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.6
- Cloud provider or hardware configuration: Google Kubernetes Engine

**Comment by liggitt** [comment]
a pod with nodeName specified does not get scheduled, it is already assigned to the node. The scheduler only looks at pods which have not yet been assigned to a node.

/close

**Comment by arkadyark** [comment]
I see, would there be a way to use nodeName and still have resources be checked? I can re-work my use case to use a nodeSelector, but isn't this a bit of a limitation in what can be done with nodeName?

**Comment by k82cn** [comment]
`nodeSelector` is the solution; if `nodeName` is set, kube-scheduler will ignore it :)
