### ISSUE TITLE
Create Deployment with DNS records for FQDNs of the pods

### ISSUE THREAD

**Issue by jdanekrh** [kubernetes/kubernetes#61701]
/kind feature

I'd like to combine Deployments feature with the pod DNS records feature as described in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-hostname-and-subdomain-fields.

My goal is that every pod in the deployments needs to have (arbitrary) DNS-resolvable FQDN, because my application depends on it (slave sends its FQDN to the master and then the master sends REST requests to that FQDN, weird but that's how it works)

The problem is, I am not allowed to set a different hostname or name on each of the pods created in the deployment, so I cannot currently get the FQDN working.

**Comment by jdanekrh** [comment]
@kubernetes/sig-network-feature-requests

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps-feature-requests

This looks more like something you would use a stateful set for.

**Comment by jdanekrh** [comment]
I looked at stateful set documentation and it seems it would work for what I need. There is only one minor mismatch regarding pod startup: I would prefer to start them all at once, not one-at-a-time. But that is something I can live with just fine. Thanks.
