### ISSUE TITLE
Pods stuck in terminating state on Windows nodes

### ISSUE THREAD

**Issue by andreyshamray** [kubernetes/kubernetes#61716]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
 /kind bug

**What happened**:
Pods stuck in terminating state on Windows node after deleting it

**What you expected to happen**:
Pods get terminated and should disappear from kubectl

**How to reproduce it (as minimally and precisely as possible)**:
Run a pod with windows container
Delete it
Pods are still terminating

**Anything else we need to know?**:
Could you pls help to resolve this issue. K8s pods stuck as Terminating after getting deleted on windows node with windows container(IIS). Docker ps -a not showing this container, so it is completely deleted, but in kubectl it is marked as Terminating.  For networking we using OVN.
kubectl logs:
```
$kubectl logs windows-IIS-container1 
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF

```
kubelet logs:

```
Line 11214: W0323 15:19:52.550689    1592 docker_sandbox.go:340] failed to read pod IP from plugin/docker: Couldn't find network status for default/windows-IIS-container1 through plugin: invalid network status for
	Line 11258: E0323 15:21:54.711806    1592 kubelet.go:1629] Unable to mount volumes for pod "windows-IIS-container1_default(57827f1c-2ea4-11e8-b7b6-00155d00680b)": timeout expired waiting for volumes to attach/mount for pod "default"/"windows-IIS-container1". list of unattached/unmounted volumes=[default-token-mpzlg]; skipping pod
	Line 11258: E0323 15:21:54.711806    1592 kubelet.go:1629] Unable to mount volumes for pod "windows-IIS-container1_default(57827f1c-2ea4-11e8-b7b6-00155d00680b)": timeout expired waiting for volumes to attach/mount for pod "default"/"windows-IIS-container1". list of unattached/unmounted volumes=[default-token-mpzlg]; skipping pod
	Line 11259: E0323 15:21:54.711806    1592 pod_workers.go:186] Error syncing pod 57827f1c-2ea4-11e8-b7b6-00155d00680b ("windows-IIS-container1_default(57827f1c-2ea4-11e8-b7b6-00155d00680b)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"windows-IIS-container1". list of unattached/unmounted volumes=[default-token-mpzlg]
	
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:11:08Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}


```
- Cloud provider or hardware configuration:
Hyper-V VMs

- OS (e.g. from /etc/os-release):
Windows Node:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

```
Master Node:
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux esd-kbrnts-lnx-1 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
OVN 2.7 on windows 
OVN 2.7.2 on linux

- Others:
Docker Version on Windows node:
Server Version: 17.06.2-ee-6

@kubernetes/sig-windows-bugs @kubernetes/sig-scheduling

**Comment by feiskyer** [comment]
@andreyshamray It needs sometime for kubelet to remove the pod. Could you wait a while and check whether the Pod removed?

**Comment by andreyshamray** [comment]
Hi @feiskyer  actually I have waited for 1 day, and it is not deleting. Can delete it only using --grace-period=0 --force.  But  I don't want to use this manual approach). Could you pls give some advice on this?
Thanks in advance!

**Comment by feiskyer** [comment]
[here](https://github.com/feiskyer/kubernetes-handbook/blob/master/en/troubleshooting/pod.md#pod-stuck-in-terminating-or-unknown) is a reference to this issue. Checking kubelet logs will always help to troubleshoot such problem.

**Comment by andreyshamray** [comment]
Actually, I have attached kubelet log in the ticket and think the main reason is `failed to read pod IP from plugin/docker: Couldn't find network status for default/windows-IIS-container` 
Also as there any option for kubelet to automatically force delete Terminating pods after some period?
And --containerized is also not solving my issue. 
Thanks!

**Comment by feiskyer** [comment]
Kubelet won't delete the pod from apiserver. Since it is already not exist on the node, you could force delete it by kubectl.

**Comment by andreyshamray** [comment]
It is clear, so how we can resolve this error: `docker_sandbox.go:340] failed to read pod IP from plugin/docker: Couldn't find network status for default/name-of-container through plugin: invalid network status for` ? I think this is the core item of our issue. 
Thanks.

**Comment by feiskyer** [comment]
I'm not using OVN. @michmike Have you met this problem when using OVN?

**Comment by michmike** [comment]
adding Bob to comment on this. i have seen this issue before, but it has been quite a while.
@bsteciuk

**Comment by andreyshamray** [comment]
Hi, Guys will be very grateful if you will provide some solution for it.
We have tried to add  `automountServiceAccountToken: false` to deployment spec but it doesn't help.

Thanks.

**Comment by feiskyer** [comment]
@andreyshamray  The error message of `failed to read pod IP from plugin/docker` is actually a warning message. It shouldn't block the removal of pods. Could you recheck the following things:

1. On the node, check whether the pod is still existing, e.g. by `docker ps`
2. If the pod exists, check if there are other error or warning message in kubelet logs; or else, the pod could be force removed safely from apiserver

**Comment by andreyshamray** [comment]
Hi, I had posted this info in the ticket description.
`docker ps -a ` not showing this container, so it is completely deleted, but in kubectl it is displayed as Terminating.

**Comment by michmike** [comment]
@andreyshamray i think you may get more support and faster responses in our slack channel for sig-windows.

**Comment by feiskyer** [comment]
@andreyshamray So it could be safely force removed from API.

And agreed with @michmike, slack is a more faster way to such troubleshooting issues.

**Comment by martinivanov** [comment]
The issue seems to be related to [this line](https://github.com/kubernetes/kubernetes/blob/d1b38b21ef450971ab3d7507506f4d824a623aa3/pkg/kubelet/kubelet_pods.go#L914). The only platform specific implementation for PodContainerManager is the one for [Linux](https://github.com/kubernetes/kubernetes/blob/d1b38b21ef450971ab3d7507506f4d824a623aa3/pkg/kubelet/cm/pod_container_manager_linux.go#L67). There is a default implementation ([pod_container_manager_stub.go](https://github.com/kubernetes/kubernetes/blob/d1b38b21ef450971ab3d7507506f4d824a623aa3/pkg/kubelet/cm/pod_container_manager_stub.go)), that always returns true in the Exists call. Disabling the CgroupsPerQOS option on the Windows nodes resolves the issue.

**Comment by feiskyer** [comment]
@martinivanov Windows doesn't support cgroups. You should always disable it.

**Comment by andreyshamray** [comment]
@feiskyer it is clear enough that Windows does not support cgroups). Unfortunately, it's not specified in the documentation.
So to disable CgroupsPerQOS you should need to add this flags to kubelet:
`--cgroups-per-qos=false --enforce-node-allocatable=""`
Maybe it will help someone...

Thank you all for discussion!
