### ISSUE TITLE
Kubectl create secret/configMap using --from-file option is failing

### ISSUE THREAD

**Issue by Anumita** [kubernetes/kubernetes#61710]
I am trying to create a configmap from a file using the
"kubectl create configmap myconfigmap --from-file=game.properties"

The game.properties consists of the following key value pairs
enemies.name=aliens
lives.count=3
enemies.cheat=true
enemies.cheat=noGoodRotten
secret.code=UUDDLRLRBABAS
secret.code=true
secret.code=30

The command is failing with the error 

"game.properties" is not a valid key name for a ConfigMap: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

Also, with the same file (game.properties), i tried creating the configmap using 
"kubectl create configmap myconfigmap --from-file=game-properties-key=game.properties" and the configMap is getting created successfully.

I tried creating a secret using the example given in kubernetes documentation ie
kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt
I am getting the same error for secrets as well

This command was working a few weeks ago. I haven't changed my kubectl version since then. 
Kubectl version: 1.9.0
I also tried the same command with 1.7, 1.6 and 1.4 version and am getting the same error.

/sig cli
/kind bug

**Comment by liggitt** [comment]
what server version do you have (output of `kubectl version`)? dots are allowed in 1.4.x+

**Comment by Anumita** [comment]
Kubectl version:

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Evanthx** [comment]
I'm having the same issue trying to add yaml files. I've tried several files and get the same error on all of them? I'm on a mac and just did a new install of kubctl with homebrew, which was v1.8.0.

**Comment by Anumita** [comment]
Is there any update on this? The same file is not working with a 1.4.6 version as well. Is there some specific way in which we need to specify the key value pairs in a config map using the file method?

**Comment by Anumita** [comment]
I finally got what is wrong. When i specify the file path, i get the error specified. If the file is in the same location from where i am running the command the command executes successfully.
eg: >kubectl create configmap myconfigmap1 --from-file="C:\Users\ansheno\Desktop\password.txt" gives me the error

error: "C:\\Users\\ansheno\\Desktop\\password.txt" is not a valid key name for a ConfigMap: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

**Comment by liggitt** [comment]
ah, great. https://github.com/kubernetes/kubernetes/pull/63439 will fix that.

in the meantime, you can do `--from-file=password.txt="C:\Users\ansheno\Desktop\password.txt"`

**Comment by Anumita** [comment]
Thanks a lot!. One more observation was that the command works if you specify the path to the directory which contains the file instead of the path to the file itself.

**Comment by Anumita** [comment]
Hi, what would be eta of this fix? Also, will it be available in all the versions of kubectl?

**Comment by liggitt** [comment]
it will be in 1.11, targeted for end of june (https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release-1.11.md)
