### ISSUE TITLE
test-cmd flake: error: could not fetch the scale for replicasets

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#61748]
Start seeing flake in test-cmd deployment tests since 3/26 https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration

The failure seems related to `scale` subresource?
```
test-cmd run_deployment_tests 26s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=test\-cmd\srun\_deployment\_tests$'
[...]
error: could not fetch the scale for replicasets.extensions nginx-deployment-747f8b5dd: replicasets/scale.extensions "nginx-deployment-747f8b5dd" not found
!!! [0327 00:27:29] Call tree:
!!! [0327 00:27:29]  1: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:47 run_deployment_tests(...)
!!! [0327 00:27:29]  2: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0327 00:27:29]  3: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:107 juLog(...)
!!! [0327 00:27:29]  4: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:5076 record_command(...)
!!! [0327 00:27:29]  5: hack/make-rules/test-cmd.sh:105 runTests(...)
```
Could #60455 be related?

cc @p0lyn0mial @kubernetes/sig-cli-bugs

**Comment by deads2k** [comment]
It looks like `k8s.io/kubernetes/test/integration/deployment.TestDeploymentLabelAdopted` started failing at the same time.  That doesn't use the scaler right?

**Comment by deads2k** [comment]
What do the SHAs in https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration point to now?  I can't find those SHAs in the kube commit history.

**Comment by janetkuo** [comment]
> What do the SHAs in https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration point to now? I can't find those SHAs in the kube commit history.

@krzyzacy any idea what the SHAs point to?

**Comment by krzyzacy** [comment]
I replied on slack https://kubernetes.slack.com/archives/C09QZ4DQB/p1522175481000795

**Comment by janetkuo** [comment]
I verified that `test-cmd.run_deployment_tests` is green again after the fix got merged. Thanks @deads2k!
