### ISSUE TITLE
fsgroup check in local volume plugin doesn't work for containerized kubelet

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#61741]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
While triaging #61456, I also took a look at local.go and believe that [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/local/local.go#L288) will also have a similar issue, because it does an `os.Stat` on the `m.globalPath`, which may not be exposed at the same path in a containerized kubelet.

**What you expected to happen**:
The fix probably needs to use nsenter.Mounter to get the rootfs path in a containerized kubelet environment.

**Comment by cofyc** [comment]
I'm going to work on this.
