### ISSUE TITLE
kubectl cp is very buggy

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubernetes#61761]
`kubectl cp import/mysql/ resize-deployment-5545544bc9-56b6f:/var/lib/`

If I have a `mysql` directory within `import/mysql` directory it copies the contents of `import/mysql/mysql` INSTEAD???

In addition:

kubectl cp ../media nfs-server-72p8m:/exports returns success - but the files are not transferred...

If I add the trailing slash though it works... kubectl cp ../media nfs-server-72p8m:/exports/

**Comment by chrissound** [comment]
kubectl cp import/mysqlold/ resize-deployment-5545544bc9-56b6f:/var/lib/mysql/
error: stat import/mysqlold/mysqlold: no such file or directory

/sig cli

**Comment by WanLinghao** [comment]
track

**Comment by cdrage** [comment]
@chrissound maybe I'm having a brain-fart, just use / remove the trailing slash? `kubectl cp import/mysql resize-deployment-5545544bc9-56b6f:/var/lib/`
