### ISSUE TITLE
POD is in PENDING STATE

### ISSUE THREAD

**Issue by neliel123** [kubernetes/kubernetes#61768]
I have an init container which runs a java process...it runs in a loop and exits gracefully when all my required preprocessing events are met.
I just noticed that even if my java process completes and the thread is exited... my containers are not booting up and it is still in the PENDING state.

It seems that it is waiting for something from my initcontainer.
Are init containers not capable of running a java process?

**Comment by tanshanshan** [comment]
Can you paste 

> kubectl describe po

 result?

**Comment by dims** [comment]
/close

please reopen with additional info requested
