### ISSUE TITLE
kubelet v.1.10.0 missing from yum repo

### ISSUE THREAD

**Issue by albamoro** [kubernetes/kubernetes#61763]
/sig release
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Upgraded kubernetes cluster from 1.9.5 to 1.10.0 successfully, however kubelets can only be updated to 1.9.6 as this is the latest version available in the yum repos.

**What you expected to happen**:
Cluster and kubelets would be in step version-wise

**How to reproduce it (as minimally and precisely as possible)**:
`yum --showduplicates list kubelet` shows 1.9.6 as the latest version available

**Anything else we need to know?**:
Running kubeadm upgrade plan stalls after promoting cluster to 1.10.0 and kubelets to 1.9.6

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): **RHEL 7.4**
- Kernel (e.g. `uname -a`):
- Install tools: **kubeadm**
- Others:

**Comment by calebamiles** [comment]
should be fixed now, @albamoro 

**cc: @jdumars, @kubernetes/kubernetes-release-managers**

**Comment by albamoro** [comment]
Thanks @calebamiles, I need to be spoon-fed as you can see ;)

**Comment by Nodraak** [comment]
I confirm kubelet 1.10.0 is available through yum (on centos 7.4).

I believe this issue can be closed
