### ISSUE TITLE
isolated advanced audit for multi tenants in kubernetes cluster

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#61766]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

The advanced audit feature has become v1beta1 version now. It's a reasonable feature request for a cluster admin to distribute audit events to tenants.

I have implement a [add-on](https://github.com/CaoShuFeng/k8s-audit-collector) to support this feature. But the community has  expressed some disagreement because it exposes the service account to the third party.
ref:
https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#heading=h.5ejmrg6cqbd3

This issue is addressed to ask for some good suggestions from community.

/cc @crassirostris @tallclair @hzxuzhonghu @sttts @soltysh @ericchiang

**Comment by tallclair** [comment]
This feature has some overlap with https://github.com/kubernetes/kubernetes/issues/53455, which could build in support for filtering (and authorizing) the event stream by namespace.
