### ISSUE TITLE
make clean_generated doesn't remove all generated files

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#61770]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig api-machinery

**What happened**:
[It turned out by the hard way](https://github.com/kubernetes/kubernetes/pull/61608#issuecomment-376208064) that `make clean_generated` doesn't remove all generated files but only those that have `zz_generated` prefix. This is counter intuitive :(

In fact, **there is no way to clean all generated files**, including clientsets, listers, and informers (maybe something else).

**What you expected to happen**:
There should be a command that really cleans all generated files. It can be a new command or existing command can be changed to take care about  clientsets/listers/informers.

**Comment by wenjiaswe** [comment]
cc @roycaihw

**Comment by nikhita** [comment]
/remove-lifecycle stale

PR is still open.
