### ISSUE TITLE
CSI E2E test failing on GKE

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#61781]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

The test ` [sig-storage] CSI Volumes [Flaky] Sanity CSI plugin test using hostPath CSI driver should provision storage with a hostPath CSI driver` is consistently failing in https://k8s-testgrid.appspot.com/sig-storage#gke-flaky

The issue is that GKE does not permit E2E framework to create new role, so the creation of role [required by the CSI E2E test](https://github.com/kubernetes/kubernetes/blob/90c09c75d67831/test/e2e/storage/csi_volumes.go#L84-L120) fails with: `csi-cluster-role cluster role: clusterroles.rbac.authorization.k8s.io "csi-cluster-role" is forbidden: attempt to grant extra privileges`.

**What you expected to happen**:

The test should not be creating a role. Kubernetes already defines a set of pre-defined role, see https://github.com/kubernetes/kubernetes/blob/90c09c75d67831ad46cc0c9abb954b6936ca86b3/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L448

We should cosnider adding three new pre-defined kubernetes role: 1) `csi-provisioner`, 2) `csi-attacher`, and 3) `csi-mounter`. These should be used by the CSI external-provisioner, external-attacher, and driver-registrar.

**How to reproduce it (as minimally and precisely as possible)**:
Run the failing E2E test on GKE.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gnufied** [comment]
Is role binding enough? Does GKE allows creation of service accounts and cluster roles? It does not make sense to create a role binding without corresponding service accounts and cluster roles. So, we are going to need those too right?

If yes - we will have to decide on a service account that will be shared by all CSI plugins?

**Comment by msau42** [comment]
Nit: The issue is not the creation of rolebindings.  It's the creation of roles that doesn't work in GKE at the moment.  The local pv and external provisioner e2e tests are already creating rolebindings.

**Comment by davidz627** [comment]
Looks like cluster role creation is failing. The good news is that this is the cluster role required for the Kubernetes CSI External Components (attacher and provisioner) which share this cluster role. These are standard components and are shared among all existing deployments for CSI Drivers.

Therefore we should be able to add a predefined cluster-role for these components. We will remove the creation of the cluster-role at test time, and instead just create a service account to use and the role-binding required.

**Comment by saad-ali** [comment]
> Nit: The issue is not the creation of rolebindings. It's the creation of roles that doesn't work in GKE at the moment. The local pv and external provisioner e2e tests are already creating rolebindings (and service accounts).

Ah yes, fixed.

**Comment by davidz627** [comment]
We can only add bootstrapped roles for the provisioner and attacher for now. After talking to @liggitt some more we've determined that giving each node permissions to update any other node through driver registrar permissions is too big of a security hole. Therefore, the fix for this test is to skip it if it is running on GKE until #62213 resolved.
