### ISSUE TITLE
kubectl from cronjob example usage is incorrect

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#61787]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli
/area kubectl

**What happened**:

```
$ kubectl create job --help
...

Usage:
  kubectl create job NAME [--from-cronjob=CRONJOB] [flags] [options]

...
```

If you try to use `--from-cronjob` though you get an error. 

```
Use "kubectl options" for a list of global command-line options (applies to all commands).

unknown flag: --from-cronjob
```

**What you expected to happen**:

The correct usage is `--from=cronjob/<name>` which is actually used in the example that's output in `--help`

```
Examples:
  # Create a job from a CronJob named "a-cronjob"
  kubectl create job --from=cronjob/a-cronjob
```

**How to reproduce it (as minimally and precisely as possible)**:

Try using `--from-cronjob` flag when running `kubectl create job`

**Anything else we need to know?**:

Version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
```

The release notes are incorrect as well for 1.10. 

cc @soltysh

**Comment by CaoShuFeng** [comment]
/close
closed by https://github.com/kubernetes/kubernetes/pull/61219
