### ISSUE TITLE
Cannot update cronjob from within pod (NotAcceptable 406 error)

### ISSUE THREAD

**Issue by alexef** [kubernetes/kubernetes#61805]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When calling `kubectl apply -f cronjob.yml` from within a pod (even with the admin service account attached to it), I get back a 406 NotAcceptable:

```bash
0328 01:54:42.361974     431 merged_client_builder.go:123] Using in-cluster configuration
I0328 01:54:42.382441     431 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "unknown",
  "reason": "NotAcceptable",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "unknown"
      }
    ]
  },
  "code": 406
}]
F0328 01:54:42.382471     431 helpers.go:119] Error from server (NotAcceptable): unknown
```

**What you expected to happen**:

I would expect the cronjob to be created/updated. Running kubectl apply manually, on my local machine, with the same manifest and the same role, works.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod + a service account that allows cronjob create/update/delete and try to use `kubectl apply` within the pod. 

**Anything else we need to know?**:

Other resources like deployments or services are successfully applied.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): Linux dss-554577754d-kc6sf 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by CaoShuFeng** [comment]
I can't reproduce this.

Can you provide content of the `cronjob.yml`?

**Comment by alexef** [comment]
Any content, for instance:

```apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    owner: subscriber
  name: mycronjob
  namespace: default
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            type: job
        spec:
          containers:
          - name: myjob
            image: busybox
            command:
            - echo
            - ok
  schedule: 0 1 * * *```

**Comment by CaoShuFeng** [comment]
Will it work after adding apiversion to it?
```
kind: CronJob
apiVersion: batch/v1beta1
```

**Comment by alexef** [comment]
@CaoShuFeng sorry, wrong formatting (I updated my previous comment now), apiVersion is already there, it makes no difference.

**Comment by alexef** [comment]
Also adding service account and clusterrole:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"dss-service-account","namespace":"gygops"}}
  creationTimestamp: 2018-03-28T01:38:56Z
  name: dss-service-account
  namespace: gygops
  resourceVersion: "35527066"
  selfLink: /api/v1/namespaces/gygops/serviceaccounts/dss-service-account
  uid: c77992cc-3228-11e8-9a81-02f971c0cb1c
secrets:
- name: dss-service-account-token-gzxqh
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"dss-service-role","namespace":""},"rules":[{"apiGroups":["*"],"resources":["deployments","services","configmaps","secrets"],"verbs":["get","list","watch","create","update","patch"]},{"apiGroups":["batch","extensions"],"resources":["jobs","cronjobs"],"verbs":["get","list","watch","create","update","patch","delete"]}]}
  creationTimestamp: 2018-03-28T01:38:56Z
  name: dss-service-role
  resourceVersion: "35527070"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/dss-service-role
  uid: c7937cc7-3228-11e8-9a81-02f971c0cb1c
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - services
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

**Comment by CaoShuFeng** [comment]
Hi, can your service account access some nonResourceURLs like `swagger-2.0.0.pb-v1` and `openapi/v2` ?

We can use "kubectl apply -f xxx.yml -v=9" to see the debug info

**Comment by CaoShuFeng** [comment]
*Maybe* related to this patch:

https://github.com/kubernetes/kubernetes/pull/59293

**Comment by CaoShuFeng** [comment]
This change just fix the error message:
https://github.com/kubernetes/kubernetes/pull/61835

**Comment by Overv** [comment]
@CaoShuFeng That error message does not appear to be relevant to this issue. The patch you refer to, however, does seem to be related.

**Comment by CaoShuFeng** [comment]
This happens because the new version kubectl requires a  Content-Type of `application/com.github.proto-openapi.spec.v2@v1.0+protobuf`. But the old version of kube-apiserver doesn't support this Content-Type.

@alexef 
The kubectl version is `v1.10.0`, but the kube-apiserver version is `go1.8.3`

**Comment by CaoShuFeng** [comment]
Not sure the 1.10 kubeclt should support the 1.8 kube-apiserver.

@liggitt 
Do I need to make a pull request to 1.10 branch?

**Comment by liggitt** [comment]
> Not sure the 1.10 kubeclt should support the 1.8 kube-apiserver.

kubectl supports one version of skew between it and the apiserver, though having it tolerate a missing openapi doc better would have been preferable
