### ISSUE TITLE
It's time to remove ObjectMeta and *Options in core api

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#61807]
https://github.com/kubernetes/kubernetes/pull/39709 has moved ObjectMeta  to meta/v1 and mark it deprecated in core api.
https://github.com/kubernetes/kubernetes/pull/40344 has moved ListOptions DeleteOptions to meta/v1 and mark it deprecated in core api.

So should remove it from core api group.

/sig api-machinery

**Comment by hzxuzhonghu** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
heapster has consistently been a black sheep.  Can you search their repo to make sure they've stopped using it?

**Comment by deads2k** [comment]
@smarterclayton ready for this?

**Comment by smarterclayton** [comment]
I have been waiting for this my entire Kubernetes life.

**Comment by hzxuzhonghu** [comment]
>heapster has consistently been a black sheep. Can you search their repo to make sure they've stopped using it?

It is still using it, I will open a pr to change that.

**Comment by hzxuzhonghu** [comment]
Open a pr in https://github.com/kubernetes/heapster/pull/1998

**Comment by hzxuzhonghu** [comment]
@deads2k There is already a pr does this. So heapster is not a blocker.

https://github.com/kubernetes/heapster/pull/1998#issuecomment-377102195

**Comment by deads2k** [comment]
> @deads2k There is already a pr does this. So heapster is not a blocker.
> 
> kubernetes/heapster#1998 (comment)

Great.  Then I think we're ready.

**Comment by wenjiaswe** [comment]
cc @yliaog
