### ISSUE TITLE
After ‘kubeadm init’ successfully a little while, images be cleaned up and the service stop

### ISSUE THREAD

**Issue by myqq0000** [kubernetes/kubernetes#61815]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After ‘kubeadm init’ a little while, images disappear (And I found it be free by kubelet...)
**What you expected to happen**:
kubernetes init successfully
**How to reproduce it (as minimally and precisely as possible)**:
`kubeadm init --pod-network-cidr=192.168.0.0/16`

**Anything else we need to know?**:
After 'kubeadm init' successfully, there are 5 images of kubernetes as below:

> REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-scheduler-amd64            v1.10.0             704ba848e69a        36 hours ago        50.4 MB
k8s.gcr.io/kube-controller-manager-amd64   v1.10.0             ad86dbed1555        36 hours ago        148 MB
k8s.gcr.io/kube-apiserver-amd64            v1.10.0             af20925d51a3        36 hours ago        225 MB
k8s.gcr.io/etcd-amd64                      3.1.12              52920ad46f5b        2 weeks ago         193 MB
k8s.gcr.io/pause-amd64                     3.1                 da86e6ba6ca1        3 months ago        742 kB

But a little while later, when I try `docker images` again ,they are disappeared.
And when I try to use `kubectl apply` to install a pod network, it returns:

> The connection to the server 10.4.20.252:6443 was refused - did you specify the right host or port?

I think it because of the images disappearance. But I don't know how to solve it...

And today I read the logs of kubelet carefully. I found after the node registered successfully, there are some wrong come out. And then it began to clean up images and pods... How to stop it and why?
The logs are below:

> 3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.166811   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/daf4ae2370716908643234b98eb0dab8-kubeconfig") pod "kube-scheduler-ultron-pcn" (UID: "daf4ae2370716908643234b98eb0dab8")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.166866   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/01ea87c3be5c15a6f1b4d4a3004e63b7-k8s-certs") pod "kube-apiserver-ultron-pcn" (UID: "01ea87c3be5c15a6f1b4d4a3004e63b7")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.166932   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs-etc-pki" (UniqueName: "kubernetes.io/host-path/01ea87c3be5c15a6f1b4d4a3004e63b7-ca-certs-etc-pki") pod "kube-apiserver-ultron-pcn" (UID: "01ea87c3be5c15a6f1b4d4a3004e63b7")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.167011   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/af2c38ba6bfc178ab7393e4bb5bbd81f-k8s-certs") pod "kube-controller-manager-ultron-pcn" (UID: "af2c38ba6bfc178ab7393e4bb5bbd81f")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.167048   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/af2c38ba6bfc178ab7393e4bb5bbd81f-ca-certs") pod "kube-controller-manager-ultron-pcn" (UID: "af2c38ba6bfc178ab7393e4bb5bbd81f")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.167088   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/af2c38ba6bfc178ab7393e4bb5bbd81f-flexvolume-dir") pod "kube-controller-manager-ultron-pcn" (UID: "af2c38ba6bfc178ab7393e4bb5bbd81f")
3月 29 11:26:59 ultron-PCN kubelet[20894]: I0329 11:26:59.167174   20894 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/01ea87c3be5c15a6f1b4d4a3004e63b7-ca-certs") pod "kube-apiserver-ultron-pcn" (UID: "01ea87c3be5c15a6f1b4d4a3004e63b7")
3月 29 11:26:59 ultron-PCN kubelet[20894]: E0329 11:26:59.925331   20894 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.4.20.252:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dultron-pcn&limit=500&resourceVersion=0: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:26:59 ultron-PCN kubelet[20894]: E0329 11:26:59.926244   20894 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://10.4.20.252:6443/api/v1/nodes?fieldSelector=metadata.name%3Dultron-pcn&limit=500&resourceVersion=0: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:26:59 ultron-PCN kubelet[20894]: E0329 11:26:59.928165   20894 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://10.4.20.252:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:27:00 ultron-PCN kubelet[20894]: I0329 11:26:59.999796   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:00 ultron-PCN kubelet[20894]: W0329 11:27:00.002170   20894 status_manager.go:459] Failed to get status for pod "etcd-ultron-pcn_kube-system(408851a572c13f8177557fdb9151111c)": Get https://10.4.20.252:6443/api/v1/namespaces/kube-system/pods/etcd-ultron-pcn: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:27:00 ultron-PCN kubelet[20894]: I0329 11:27:00.005422   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:00 ultron-PCN kubelet[20894]: W0329 11:27:00.007571   20894 status_manager.go:459] Failed to get status for pod "kube-apiserver-ultron-pcn_kube-system(01ea87c3be5c15a6f1b4d4a3004e63b7)": Get https://10.4.20.252:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-ultron-pcn: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:27:00 ultron-PCN kubelet[20894]: I0329 11:27:00.009047   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:00 ultron-PCN kubelet[20894]: W0329 11:27:00.010945   20894 status_manager.go:459] Failed to get status for pod "kube-controller-manager-ultron-pcn_kube-system(af2c38ba6bfc178ab7393e4bb5bbd81f)": Get https://10.4.20.252:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-ultron-pcn: dial tcp 10.4.20.252:6443: getsockopt: connection refused
3月 29 11:27:00 ultron-PCN kubelet[20894]: I0329 11:27:00.285535   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:00 ultron-PCN kubelet[20894]: I0329 11:27:00.287985   20894 kubelet_node_status.go:82] Attempting to register node ultron-pcn
3月 29 11:27:01 ultron-PCN kubelet[20894]: I0329 11:27:01.011772   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:01 ultron-PCN kubelet[20894]: I0329 11:27:01.011810   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:01 ultron-PCN kubelet[20894]: I0329 11:27:01.011773   20894 kubelet_node_status.go:273] Setting node annotation to enable volume controller attach/detach
3月 29 11:27:01 ultron-PCN kubelet[20894]: W0329 11:27:01.131758   20894 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 11:27:01 ultron-PCN kubelet[20894]: E0329 11:27:01.131932   20894 kubelet.go:2105] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 11:27:06 ultron-PCN kubelet[20894]: E0329 11:27:06.130849   20894 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node "ultron-pcn" not found
3月 29 11:27:06 ultron-PCN kubelet[20894]: W0329 11:27:06.133020   20894 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 11:27:06 ultron-PCN kubelet[20894]: E0329 11:27:06.133207   20894 kubelet.go:2105] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 11:27:07 ultron-PCN kubelet[20894]: I0329 11:27:07.130397   20894 kubelet_node_status.go:85] Successfully registered node ultron-pcn
3月 29 11:27:11 ultron-PCN kubelet[20894]: W0329 11:27:11.134410   20894 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 11:27:11 ultron-PCN kubelet[20894]: E0329 11:27:11.134596   20894 kubelet.go:2105] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.135008   20894 conversion.go:110] Could not get instant cpu stats: different number of cpus
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.135576   20894 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 11:27:16 ultron-PCN kubelet[20894]: E0329 11:27:16.135768   20894 kubelet.go:2105] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.146505   20894 conversion.go:110] Could not get instant cpu stats: different number of cpus
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.149256   20894 conversion.go:110] Could not get instant cpu stats: different number of cpus
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.150439   20894 eviction_manager.go:332] eviction manager: attempting to reclaim imagefs
3月 29 11:27:16 ultron-PCN kubelet[20894]: I0329 11:27:16.150470   20894 helpers.go:1070] eviction manager: attempting to delete unused containers
3月 29 11:27:16 ultron-PCN kubelet[20894]: I0329 11:27:16.154892   20894 helpers.go:1080] eviction manager: attempting to delete unused images
3月 29 11:27:16 ultron-PCN kubelet[20894]: I0329 11:27:16.159711   20894 image_gc_manager.go:350] [imageGCManager]: Removing image "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2" to free 746888 bytes
3月 29 11:27:16 ultron-PCN kubelet[20894]: E0329 11:27:16.162099   20894 remote_image.go:130] RemoveImage "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2" from image service failed: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 59c259683f4b
3月 29 11:27:16 ultron-PCN kubelet[20894]: E0329 11:27:16.162154   20894 kuberuntime_image.go:126] Remove image "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2" failed: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 59c259683f4b
3月 29 11:27:16 ultron-PCN kubelet[20894]: W0329 11:27:16.162176   20894 eviction_manager.go:435] eviction manager: unexpected error when attempting to reduce imagefs pressure: wanted to free 9223372036854775807 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 59c259683f4b
3月 29 11:27:16 ultron-PCN kubelet[20894]: I0329 11:27:16.162186   20894 eviction_manager.go:346] eviction manager: must evict pod(s) to reclaim imagefs

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):Linux ultron-PCN 4.13.0-37-generic
- Install tools:Kubeadm
- Others:

**Comment by myqq0000** [comment]
I notice these in the logs:

> 3月 29 18:04:53 ultron-PCN kubelet[17742]: I0329 18:04:53.064856   17742 kubelet_node_status.go:85] Successfully registered node ultron-pcn
3月 29 18:04:54 ultron-PCN kubelet[17742]: W0329 18:04:54.579094   17742 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 18:04:54 ultron-PCN kubelet[17742]: E0329 18:04:54.579313   17742 kubelet.go:2125] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 18:04:59 ultron-PCN kubelet[17742]: W0329 18:04:59.574943   17742 eviction_manager.go:343] eviction manager: attempting to reclaim imagefs
3月 29 18:04:59 ultron-PCN kubelet[17742]: I0329 18:04:59.574977   17742 container_gc.go:85] **attempting to delete unused containers**
3月 29 18:04:59 ultron-PCN kubelet[17742]: W0329 18:04:59.580189   17742 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
3月 29 18:04:59 ultron-PCN kubelet[17742]: I0329 18:04:59.580192   17742 image_gc_manager.go:317] **attempting to delete unused images**
3月 29 18:04:59 ultron-PCN kubelet[17742]: E0329 18:04:59.580325   17742 kubelet.go:2125] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
3月 29 18:04:59 ultron-PCN kubelet[17742]: I0329 18:04:59.590657   17742 eviction_manager.go:357] eviction manager: must evict pod(s) to reclaim imagefs
3月 29 18:04:59 ultron-PCN kubelet[17742]: I0329 18:04:59.590717   17742 eviction_manager.go:375] eviction manager: pods ranked for eviction: kube-apiserver-ultron-pcn_kube-system(657c3da07ea9dea5d98ed4aea1931d02), kube-controller-manager-ultron-pcn_kube-system(e835569691118f5dbfa2c5023ca8da4e), kube-scheduler-ultron-pcn_kube-system(31cf0ccbee286239d451edb6fb511513), etcd-ultron-pcn_kube-system(784fbec01823ea47db51c3a5af2b2b8f)

But why it happened? Anyone can give me some advice to solve it? THANKS!

**Comment by dashpole** [comment]
I see two possible issues here:

1. CNI is not configured correctly: `network plugin is not ready: cni config uninitialized`
2. The kubelet may be getting disk pressure when it should not be: `eviction manager: attempting to reclaim imagefs`.  To confirm this, please provide the flags used to start the kubelet, as well as the location of the kubelet's root directory (`/var/lib/kubelet` by default I think).  We should also confirm that the node didn't actually run out of disk space, so any metrics you have during startup would be useful.

**Comment by myqq0000** [comment]
@dashpole Thank you for your advice.
I have solved this problem. It because that my root directory is not enough. 
It's "imagefs.available<20%" in the default set of eviction policy. But my root directory only have 12%...
But I think it should not evict itself. Or it need some warning if there's not enough storage.
It may be improved in the future?

THANKS~

**Comment by dashpole** [comment]
@myqq0000 The kubelet would generally rather evict a pod than run out of disk space, as it may not be able to recover from that, since lots of things (e.g. ssh) require disk space to do.  The "warning" the kubelet provided in this case is the DiskPressure event.  I will grant that the behavior is somewhat strange if the kubelet is not the only thing on the node (what is using the remaining 88% of disk?).  I would recommend moving docker and the kubelet to their own partition if you are storing other things on the node, so the kubelet can manage it entirely.
