### ISSUE TITLE
Cluster setup: getting started guides rely on directories/scripts not included in kubernetes.tar.gz

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#6181]
User report: "I was unable to use the walkthroughs provided (as READMEs on github) to get a cluster up and running on CentOS, CoreOS, or even Google Compute Engine.  I eventually determined that there are directories/scripts present in the git repo that are not in the kubernetes.tar.gz tarball that the documentation says to use."

We should include release validation tests (or process steps?) that convince us our supported getting started guides continue to work.  (#6180 tracks updating our docs).

**Comment by quinton-hoole** [comment]
@alex-mohr Do we still consider this to be a v1.0 blocker?

**Comment by alex-mohr** [comment]
I think we need some process post-v1.0 to make sure our officially supported set of getting started guides continues to work -- bad docs in getting started is one of the worst product experiences.  Perhaps we do that by significantly pruning our set of docs?  But how much do we care if e.g. our AWS getting started guide stops working?  That'd be sad.

**Comment by quinton-hoole** [comment]
Agreed.  Dropping v1.0 tag.

**Comment by ihmccreery** [comment]
cc @bgrant0607 Is your docs work covering this kind of thing?

**Comment by bgrant0607** [comment]
@ihmccreery No. IMO, this isn't mainly a documentation problem. 

We have version-specific documentation, though I consider it to be a problem that we even need the so-called getting-started guides.

We don't bundle the installation machinery with the release. We assume users have pulled the git repo. 

We also don't ensure that most setups are up to date and working.

**Comment by ihmccreery** [comment]
Bumping this to P1 as an important UX problem, as @alex-mohr said.

**Comment by bgrant0607** [comment]
This is obsolete
