### ISSUE TITLE
kubernetes apiserver is not running

### ISSUE THREAD

**Issue by macroxmu** [kubernetes/kubernetes#61812]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind support

**What happened**:
after i init the cluster, and create rc successfully, while i create service, the kubernetes would fail
**What you expected to happen**:
create service successfully
**How to reproduce it (as minimally and precisely as possible)**:
`[root@localhost ~]# kubectl create -f ~/kuber/mysql-svc.yaml

Unable to connect to the server: net/http: TLS handshake timeout`

**Anything else we need to know?**:
the  full operate log:
`[root@localhost ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

[root@localhost ~]# kubectl get rc

NAME      DESIRED   CURRENT   READY     AGE

mysql     1         1         1         39m

**BEFORE CREATE SERVICE, EVERYTHING IS OK, BUT WHILE I CREATE SERVICE:**

[root@localhost ~]# kubectl create -f ~/kuber/mysql-svc.yaml

Unable to connect to the server: net/http: TLS handshake timeout

[root@localhost ~]# kubectl get rc

Unable to connect to the server: net/http: TLS handshake timeout

[root@localhost ~]# kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**Unable to connect to the server: net/http: TLS handshake timeout**`

the yaml file like this:
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

**Environment**:
- Kubernetes version (use `kubectl version`):
client:1.9.5
server:1.9.6

- Cloud provider or hardware configuration:
vmware, centos, 1GB ram

- OS (e.g. from /etc/os-release):
CentOS Linux 7 

- Kernel (e.g. `uname -a`):
Linux  3.10.0-693.el7.x86_64

- Install tools:
- Others:

**Comment by CaoShuFeng** [comment]
Can you provide the output of these two command:
$ kubectl get rc -v=9
$ kubectl create -f ~/kuber/mysql-svc.yaml -v=9

**Comment by macroxmu** [comment]
[root@localhost ~]# kubectl get rc -v=9
I0328 14:15:56.499055   10213 loader.go:357] Config loaded from file /etc/kubernetes/admin.conf
I0328 14:15:58.549731   10213 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf" https://192.168.88.129:6443/api
I0328 14:16:09.366800   10213 round_trippers.go:436] GET https://192.168.88.129:6443/api  in 10443 milliseconds
I0328 14:16:09.556203   10213 round_trippers.go:442] Response Headers:
I0328 14:16:09.936687   10213 cached_discovery.go:124] skipped caching discovery info due to Get https://192.168.88.129:6443/api: net/http: TLS handshake timeout
I0328 14:16:10.424179   10213 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf" https://192.168.88.129:6443/api
I0328 14:16:21.389946   10213 round_trippers.go:436] GET https://192.168.88.129:6443/api  in 10647 milliseconds
I0328 14:16:21.473248   10213 round_trippers.go:442] Response Headers:
I0328 14:16:21.727705   10213 cached_discovery.go:124] skipped caching discovery info due to Get https://192.168.88.129:6443/api: net/http: TLS handshake timeout
I0328 14:16:23.061345   10213 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf" https://192.168.88.129:6443/api
I0328 14:16:33.462022   10213 round_trippers.go:436] GET https://192.168.88.129:6443/api  in 10331 milliseconds
I0328 14:16:33.465846   10213 round_trippers.go:442] Response Headers:
I0328 14:16:33.559911   10213 cached_discovery.go:124] skipped caching discovery info due to Get https://192.168.88.129:6443/api: net/http: TLS handshake timeout
I0328 14:16:33.559978   10213 factory_object_mapping.go:93] Unable to retrieve API resources, falling back to hardcoded types: Get https://192.168.88.129:6443/api: net/http: TLS handshake timeout
F0328 14:16:33.687357   10213 helpers.go:119] the server doesn't have a resource type "rc"





[root@localhost kuber]# kubectl create -f ~/kuber/mysql-svc.yaml -v=9
I0328 14:14:47.150442   10172 loader.go:357] Config loaded from file /etc/kubernetes/admin.conf
I0328 14:14:50.779229   10172 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "If-None-Match: \"195E62F99CE52D3610720304639F175F4FA3B741925804F0DAD6E2DDE9A16515C5B506345C2F9A72801106D005AAD8DF13E0BEB8A93438346426E7B82EED88D0\"" -H "If-Modified-Since: Wed, 28 Mar 2018 00:44:46 GMT" -H "User-Agent: kubectl/v1.9.5 (linux/amd64) kubernetes/f01a2bf" https://192.168.88.129:6443/swagger-2.0.0.pb-v1
I0328 14:15:02.236802   10172 round_trippers.go:436] GET https://192.168.88.129:6443/swagger-2.0.0.pb-v1  in 11069 milliseconds
I0328 14:15:02.516186   10172 round_trippers.go:442] Response Headers:
I0328 14:15:03.371567   10172 helpers.go:219] Connection error: Get https://192.168.88.129:6443/swagger-2.0.0.pb-v1: net/http: TLS handshake timeout
F0328 14:15:03.618098   10172 helpers.go:119] Unable to connect to the server: net/http: TLS handshake timeout

**Comment by macroxmu** [comment]
the api server seems crash, how can I find the log of api server?
That may can find the reason.

**Comment by CaoShuFeng** [comment]
> the api server seems crash, how can I find the log of api server?

That depends on how the cluster is deployed.
Maybe `journalctl -u kube-apiserver`
