### ISSUE TITLE
Add raw block device support for azure disk

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#61821]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/raw-block-pv.md
https://github.com/kubernetes/features/issues/351

**What you expected to happen**:
I will try to implement this feature for azure disk in v1.11
@jdumars @khenidak 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by andyzhangx** [comment]
Actually there would be a new task for Windows support for Raw device, I will investigate that later.

**Comment by khenidak** [comment]
Yes let us split the work into two specific OS work stream. (btw i am not sure if windows supports raw disks) -- @JiangtianLi can maybe share some thoughts

**Comment by andyzhangx** [comment]
update:
Main code and unit test is already done:
https://github.com/andyzhangx/kubernetes/commit/53c8b88144997ae5df400144305547c42217f720

I am going to do e2e test next.
