### ISSUE TITLE
/configz doesn't work in 1.10

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#61826]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
according to the [Reconfigure a Node's Kubelet in a Live Cluster](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/) page, we can use /configz to fetch the whole config of kubelet. The question is, this API just reports 404 in 1.10 release which works fine in 1.8 in my setup.

**What you expected to happen**:
Is it not supported any more in the 1.10 release? Or just something wrong with my setup?

**How to reproduce it (as minimally and precisely as possible)**:
try this command in this page:
curl -sSL http://localhost:8001/api/v1/proxy/nodes/${NODE_NAME}/configz
and it returns as follow:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {

  },
  "code": 404
}

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by tianshapjq** [comment]
appreciate if anyone can try the /configz API and feedback :)

**Comment by phsiao** [comment]
Can you verify if the feature gate is enabled?

**Comment by tianshapjq** [comment]
@phsiao yes, still not working with the DynamicKubeletConfig on.

**Comment by CaoShuFeng** [comment]
This url works find for me:
https://<kebe-apiserver>:443/api/v1/nodes/<my-node>/proxy/configz

Ps:
I found a related issue when research this:
https://github.com/kubernetes/kubernetes/pull/61883

**Comment by CaoShuFeng** [comment]
/api/v1/proxy/nodes/${NODE_NAME}/configz/ is deprecated in 1.10.
Please use /api/v1/nodes/<my-node>/proxy/configz instead.

/close

**Comment by CaoShuFeng** [comment]
ref:
https://github.com/kubernetes/kubernetes/pull/59884

**Comment by CaoShuFeng** [comment]
/reopen

Reopen this issue because we have to update the document.
