### ISSUE TITLE
Liveness probe http-get URL redirection(302) does not work

### ISSUE THREAD

**Issue by abhijeetab07** [kubernetes/kubernetes#61831]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
>/kind feature

**What happened**:  The liveness probe configured doesn't support redirection of URL, error says "failed after 10 redirects" and restarts the container, when hit manually the same URL works fine i.e. first 302 then 200 status code. Although the documentation says status code 200 to 400 is supported. Is there a provision or a configurable parameter through which we can do this ? 

**What you expected to happen**: Liveness probe to bypass the redirection and not restart the pod

**How to reproduce it (as minimally and precisely as possible)**: Configure liveness probe where a URL is redirected to some other URL

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Running on a Virtual Machine
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`):
Linux vm4-173 3.10.0-693.21.1.el7.x86_64
- Install tools:
- Others:

**Comment by yue9944882** [comment]
> The liveness probe configured doesn't support redirection of URL, error says "failed after 10 redirects"

I believe HTTP probe supports redirection and it uses `http.Client`'s default redirection policy.

> // If CheckRedirect is nil, the Client uses its default policy,
	// which is to stop after 10 consecutive requests.
	CheckRedirect func(req *Request, via []*Request) error

What location are u actually redirection pointing at? Is it cyclic or sth?

**Comment by abhijeetab07** [comment]
When I hit URL-A it redirects me to URL-B, for now I am trying with URL-A to URL-B and it doesn't work. But, when I configure URL-B in the probe, it goes like this  URL-B ---> URL-A ---> URL-B, still redirects. This makes it cyclic in a way.

If redirection is supported, then what exactly do we need to configure in the probe ?
