### ISSUE TITLE
 E2E tests: Adding examples/ tests.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#6183]
The examples/ are largely untested, and provide great e2e validations examples of *kubernetes in the wild*.

We can now generically begin adding e2e tests for them by leveraging the hooks in utils.go in the test/e2e/ package.  

Lets
- create an examples/ directory, where we can add new tests for each example over time with
- at least one examples/ test.  

Something like this...
```
test/e2e/examples/ 
  k8petstore.go
  spark.go
```
and so on.

**Comment by jayunit100** [comment]
ping @roberthbailey  any thoughts on this before i tackle it

**Comment by roberthbailey** [comment]
/cc @quinton-hoole 

I'd suggest you start by moving the guestbook test (which is currently our only test of an example) into the new subdirectory and make sure that you get the e2e framework configured correctly. Then add tests for the other examples one at a time. 

It would be great if there was a general purpose mechanism to launch each example application that could be reused across all tests reducing each test file (`k8spetstore.go`, `spark.go`, etc) to contain only the logic necessary for validating that the example is properly running.

**Comment by jayunit100** [comment]
hi robert, thats exactly what the last patch was right? the new `validateController` gives a declarative way to validate pods without worrying  about  client creation and making the right API calls to get pods by name that are running and so on

**Comment by roberthbailey** [comment]
`validateController` is used in the update example but not in the guestbook example. It's possible that `kubectl create -f <example-dir>` is sufficient here but I'm worried that some examples will require ordering during creation.

**Comment by jayunit100** [comment]
Lets make sure to synergize with #6222 above

**Comment by jayunit100** [comment]
ill be adding these, finally this wk.  sorry about the delay on this.   Currently fixing the `--namespace` option.  i'll have an examples/ e2e test PR  by wednesday or eariler most likely... assuming the ns patch goes in shortly.

**Comment by ihmccreery** [comment]
@jayunit100 What is the status of this?

**Comment by jayunit100** [comment]
Lets close. In the e2es we now have individual soak tests as well as a large unit test for the examples
