### ISSUE TITLE
On master-node partition failure happens, statefulset's constituent pods cause data corruption

### ISSUE THREAD

**Issue by orainxiong** [kubernetes/kubernetes#61832]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
Statefulset Controller can’t ensure pod replicas during master-node partition failure and causes data corruption.

The general sequence of events as below :

- Master-Node partition failure happens(maybe network failure);
- NodeLifecycleController is able to detect the unreachable node and evict the pods(just update API) for the node that is unreachable after podEvictionTimeout seconds;
- StatefulSetController will recreate the pods that are evicted previously to an available node to preserve set.spec.replicas;
- Two pods access the same PVC simultaneously, cause data corruption;

**What you expected to happen**:
For that, there should have a policy to execute “hard” fencing to protect pod against data corruption. 

By leveraging existing components, the rough sequence of implementation would be:

- A controller, named FenceController which is written with operator pattern, watch node status just like NodeLifecycleController;
- On node partition failure happens, Node Controller update the node status to “UNKNOWN” after nodeMonitorGracePeriod seconds;
- FenceController is empowered to use IPMI to reboot the unreachable node after podEvictionTimeout - N seconds, the value of N depends on application;
- StatefulSetController will recreates the pods that are evicted previously to available node to preserve set.spec.replicas;

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The diagram depicts the scenario:
[https://docs.google.com/document/d/1qHAUMq7eMMUeOti3CkaXSHs6xkTyepT-pPg5FQOzmoo/edit?usp=sharing](url)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by orainxiong** [comment]
assign sig/apps
assign sig/storage

**Comment by msau42** [comment]
In step 3, the recreated pod cannot be created until the original pod is fully deleted (not just terminated).  And in normal cases, the pod won't be fully terminated until the volume is unmounted from the node.  Are you seeing different behavior?

**Comment by orainxiong** [comment]
Yes, _Statefulset_ is able to guarantee at-most-one pod in normal cases, but not in **Master-Node Partitioning** scenario. 

**Master-Node Partitioning** occurs when a network or network interface failure isolates API server from a node. There is an easy way to simulate this scenario by _iptables_.

NodeLifecycleController is capable of detecting the unreachable node.
the doEvictionPass function is called to evict the original pod in the unreachable node after _podEvictionTimeout_ seconds.

```
remaining, err := nodeutil.DeletePods(nc.kubeClient, nc.recorder, value.Value, nodeUID, nc.daemonSetStore)
```
It works well in the normal case but in **Master-Node Partitioning** scenario.

Because of the network isolation, Kubelet in the unreachable node can't receive the delete event from API Server, the original pod will continue to live and access the volume. At the same time, a new pod will be recreated by StatefulSetController and be scheduled to an available node by the scheduler.

The diagram depicts the scenario:
https://docs.google.com/document/d/1qHAUMq7eMMUeOti3CkaXSHs6xkTyepT-pPg5FQOzmoo/edit?usp=sharing

the MySQL instance error logs like : 

```
2017-12-01 10:19:47 5669 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2017-12-01 10:19:47 5669 [Note] InnoDB: Waiting for purge to start
2017-12-01 10:19:47 0x7fcb08928700  InnoDB: Assertion failure in thread 140509998909184 in file trx0purge.cc line 168
InnoDB: Failing assertion: purge_sys->iter.trx_no <= purge_sys->rseg->last_trx_no
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
10:19:47 5669 - mysqld got signal 6 ;  -- because of data corruption

```

**Comment by msau42** [comment]
cc @verult 

He found that on GCE environments, this is not the case.  So it seems like there could be some difference in node failure handling depending on cloud provider.  #46442 may also be related.

**Comment by verult** [comment]
@yujuhong

**Comment by orainxiong** [comment]
@msau42 Yes, AttachDetach controller is responsible for attaching and detaching all volumes across the cluster and prevents multiple attach on the same volumes in the normal case.

But, AttachDetach controller can't guarantee at-most-one attach when the original Node is unreachable.

The operation Detach would take an unpredictable time, so there is a parameter _ReconcilerMaxWaitForUnmountDuration_ to define the maximum amount of time which the AttachDetach controller will wait for an volume is safely unmounted from the original node. 

Once this time has expired, the controller will assume the node or kubelet are unresponsive and will detach the volume anyway.

There already exists  [logic](https://github.com/kubernetes/kubernetes/blob/317853c90c674920bfbbdac54fe66092ddc9f15f/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L226) to do an unsafety detaching operation.
