### ISSUE TITLE
Pod on K8S V1.9 with PV/PVC (NFS) can override storage limit request

### ISSUE THREAD

**Issue by praparn** [kubernetes/kubernetes#61839]
According to initial NFS share storage map with Persistence Volume (PV) and Persistence Volume Claim (PVC). We found that we can override storage limit that specific on PVC to use entire space on NFS

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG Report
/kind bug

**Environment Information***
NAME           ZONE          MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP       STATUS
kubernetes-1   asia-east1-a  n1-standard-1                          192.168.99.201    RUNNING
kubernetes-2   asia-east1-a  n1-standard-1                         192.168.99.202   RUNNING
kubernetes-ms  asia-east1-a  n1-standard-1                        192.168.99.200  RUNNING

kubectl get nodes:
NAME            STATUS    ROLES     AGE       VERSION
kubernetes-1    Ready     <none>    57m       v1.9.2
kubernetes-2    Ready     <none>    57m       v1.9.2
kubernetes-ms   Ready     master    1h        v1.9.2

NFS information:
praparn@kubernetes-ms:~$ more /etc/exports 
/var/nfsshare    192.168.99.0/24(rw,sync,no_subtree_check,no_root_squash)

praparn@kubernetes-ms:~$ df -kh
Filesystem                    Size  Used Avail Use% Mounted on
udev                          1.8G     0  1.8G   0% /dev
tmpfs                         370M  5.9M  365M   2% /run
/dev/sda1                     9.7G  3.1G  6.6G  32% /
tmpfs                         1.9G     0  1.9G   0% /dev/shm
tmpfs                         5.0M     0  5.0M   0% /run/lock
tmpfs                         1.9G     0  1.9G   0% /sys/fs/cgroup
192.168.99.200:/var/nfsshare  9.7G  3.1G  6.6G  32% /mnt/nfs_share
tmpfs                         370M     0  370M   0% /run/user/1003

**What happened**:

1. Reference to NFS file share we create PV and PVC as below:
**PV:**
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv
  labels:
    name: nfs-share-pv
    owner: Praparn_L
    version: "1.0"
    module: PV
    environment: development
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.99.200
    path: "/var/nfsshare"

**PVC:**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-pvc
  labels:
    name: nfs-share-pvc
    owner: Praparn_L
    version: "1.0"
    module: PVC
    environment: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  **resources:
    requests:
      storage: 500Mi
    limits:
      storage: 1Gi**
  selector:
    matchLabels:
      name: nfs-share-pv
      owner: Praparn_L
      version: "1.0"
      module: PV
      environment: development

2. We create deployment by claim storage from PVC as below:
**Deployment**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
  labels:
    name: web
    owner: Praparn_L
    version: "1.0"
    module: WebServer
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web
      owner: "Praparn_L"
      version: "1.0"
      module: WebServer
      environment: development
  template:
    metadata:
      labels:
        name: web
        owner: Praparn_L
        version: "1.0"
        module: WebServer
        environment: development
    spec:
      containers:
        - name: webtest
          image: labdocker/cluster:webservicelite_v1
          ports:
          - containerPort: 5000
            protocol: TCP
          volumeMounts:
            - name: nfs-share-pvc
              ***mountPath: "/usr/src/app"***
      volumes:
      - name: nfs-share-pvc
        persistentVolumeClaim:
          claimName: nfs-share-pvc

3. After all deployment alive. We try to access some pods and check disk get from PVC with result below:

praparn@kubernetes-ms:~$ kubectl get pods
NAME                      READY     STATUS    RESTARTS   AGE
webtest-ccf88d74b-5dw5k   1/1       Running   0          16m
webtest-ccf88d74b-fbwt2   1/1       Running   0          16m
webtest-ccf88d74b-r6dgt   1/1       Running   0          16m

praparn@kubernetes-ms:~$ kubectl exec -it webtest-ccf88d74b-5dw5k sh
/usr/src/app # df -kh
Filesystem                Size      Used Available Use% Mounted on
overlay                   9.6G      2.1G      7.5G  22% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.8G         0      1.8G   0% /sys/fs/cgroup
/dev/sda1                 9.6G      2.1G      7.5G  22% /dev/termination-log
/dev/sda1                 9.6G      2.1G      7.5G  22% /etc/resolv.conf
/dev/sda1                 9.6G      2.1G      7.5G  22% /etc/hostname
/dev/sda1                 9.6G      2.1G      7.5G  22% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
192.168.99.200:/var/nfsshare                          9.6G      3.0G      6.6G  32% /usr/src/app
tmpfs                     1.8G     12.0K      1.8G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/timer_stats
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     1.8G         0      1.8G   0% /proc/scsi
tmpfs                     1.8G         0      1.8G   0% /sys/firmware

4. We are test to download some huge ISO (1.5 GB) that over limit of PVC define limit 1Gi and got that it can download and storage file over limit request of PVC

/usr/src/app # wget http://releases.ubuntu.com/16.04/ubuntu-16.04.4-desktop-amd64.iso
Connecting to releases.ubuntu.com (91.189.88.166:80)
ubuntu-16.04.4-deskt 100% |*******************************|  1548M  0:00:00 ETA

/usr/src/app # df . -kh
Filesystem                Size      Used Available Use% Mounted on
192.168.99.200:/var/nfsshare                          9.6G      4.5G      5.1G  47% /usr/src/app

/usr/src/app # 

**What you expected to happen**:
Storage limit on PVC should be protect pods's consume space over limit of PVC

**How to reproduce it (as minimally and precisely as possible)**:
1. Initial NFS Share (Ex: 10 GB)
2. Create PV for Mount with NFS Share (Ex: Capacity 1 GB)
3. Create PVC to Reference PV with Limit storage (Ex: Limit 1 GB)
4. Access to inside pods and try to download file bigger than PVC (On specific path)

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes 1.9.2
- Cloud provider or hardware configuration: Google Cloud (IAAS)
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux kubernetes-ms 4.8.0-56-generic #61~16.04.1-Ubuntu SMP Wed Jun 14 11:58:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

/sig storage

**Comment by liggitt** [comment]
reporting a size in a PV does not add enforcement to the underlying filesystem

see https://github.com/kubernetes/kubernetes/issues/36710#issuecomment-320379770

when matching a PVC to a pre-existing PV, the system will choose the smallest PV that satisfies the PVC's request/limit. that pod is then allowed to use whatever the filesystem backing that PV permits.

/close
