### ISSUE TITLE
Implementing own volume plugin

### ISSUE THREAD

**Issue by cnaize** [kubernetes/kubernetes#6184]
I'm using 0.12 version.
I've created my own `volume` `plugin` for `v1beta3` based on existent and registered it in `cmd/kubelet/app/plugins.go`.
Next I've ran `apiserver` with `v1beta3`.
Next I've created `pod` with modified config based on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/gce-pd/v1beta3/testpd.yaml, `pod` was created successfully, but where are no logs from my `volume` `plugin`.

Can you tell me about steps in implementing own `volume` `plugin`'s?

**Comment by erictune** [comment]
if you get back the pod object that you POSTed does it have what you created?

**Comment by thockin** [comment]
Did you update the kubelets on your nodes?  That is where volume plugins
actually live.  You should see a log at startup time indicating your plugin
was loaded.

**Comment by erictune** [comment]
If you don't update the apiserver and kubectl, they may silently drop the new fields on your pod (e.g. myNewVolumeSource)

**Comment by cnaize** [comment]
@thockin 
Yes, I've updated kubeletes, but I don't see plugin loading in log.
Maybe I have to add some lines of code to `conversion.go`? But I can't find the file for `v1beta3`.

**Comment by thockin** [comment]
Can you share your patch with us?  It would make this easier.  If you want
to reduce it to the simplest possible form that fails and does nothing
else, we can probably have a better shot at a fix.

**Comment by cnaize** [comment]
@thockin 
Here is test plugin https://github.com/cnaize/kubernetes/tree/scriptable_pd

**Comment by cnaize** [comment]
Solved.
The problem was where is no `conversion.go` file for `v1beta3`.
Added to `v1beta1` and everything works.

**Comment by thockin** [comment]
great!
