### ISSUE TITLE
Flaky Tests : [sig-storage] Volumes PD should be mountable with ext3 and [sig-storage] Volumes PD should be mountable with ext3

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#61845]
### pr:pull-kubernetes-e2e-gce
Consistency: 86.6%

## Flakiest tests: 
* [sig-storage] Volumes PD should be mountable with ext3 
Flakes in the past week: 14

* [sig-storage] Volumes PD should be mountable with ext4
Flakes in the past week: 22

This issue has resurfaced again and is one of the top flake currently. Here's the TestGrid link which will lead to Gubernator for detailed logs

https://k8s-testgrid.appspot.com/sig-storage#gce&include-filter-by-regex=Volumes%20PD%20should%20be%20mountable%20with

Please work on finding a fix for the flakes

/priority failing-test
/priority important-soon
/sig storage
/kind flake

**Comment by saad-ali** [comment]
Looks like it became flaky between 3/15 and 3/16

**Comment by gnufied** [comment]
The most likely reason of this flake is - https://github.com/kubernetes/kubernetes/pull/61071 since it contains a change which will prevent deletion of pods, if volume was not unmounted. 

It is likely that - volume unmount issue was always there and we just had it masked because pod was getting deleted anyways. We need to find out, why volume is not getting unmounted.

**Comment by jingxu97** [comment]
From the log, I think the issue is https://github.com/kubernetes/kubernetes/issues/61248. I have a PR to fix this https://github.com/kubernetes/kubernetes/pull/61549

**Comment by AishSundar** [comment]
@jingxu97 The tests are still flaky. Any ETA on getting [#61549](https://github.com/kubernetes/kubernetes/pull/61549) merged? thanks

**Comment by AishSundar** [comment]
@jingxu97 I still see [Volumes PD should be mountable with ext3](https://k8s-testgrid.appspot.com/sig-storage#gce&include-filter-by-regex=Volumes%20PD%20should%20be%20mountable%20with) failing despite [#61549](https://github.com/kubernetes/kubernetes/pull/61549) being merged. 

Are you still investigating a fix or is this part of a bigger issue? Thanks.

**Comment by jingxu97** [comment]
I think the tests no longer flaky. Could we close this? @AishSundar

**Comment by AishSundar** [comment]
Thanks a lot @jingxu97. Closed

/close

**Comment by davidz627** [comment]
The tests are still flaky in 1.10. Any way we can get this cherry-picked back? @jingxu97
