### ISSUE TITLE
Flaky Test: [sig-api-machinery] Watchers should observe add, update, and delete events on pods

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#61846]
### pr:pull-kubernetes-e2e-gce
[Consistency: 86.6%](http://storage.googleapis.com/k8s-metrics/flakes-daily-latest.json)

### [sig-api-machinery] Watchers should observe add, update, and delete events on pods
[Flakes in the past week: 12](http://storage.googleapis.com/k8s-metrics/flakes-latest.json)

### TestGrid link which will lead to Gubernator for detailed logs

https://k8s-testgrid.appspot.com/sig-api-machinery#gce&include-filter-by-regex=Watchers%20should%20observe%20add%2C%20update%2C%20and%20delete%20events%20on%20pods

Please work on finding a fix for the flake.

/priority failing-test
/priority important-soon
/sig api-machinery
/kind flake

**Comment by jennybuckley** [comment]
I think this was fixed by #61494

**Comment by jennybuckley** [comment]
@AishSundar 
Hmm that is different, and I will look into the reason.

**Comment by jennybuckley** [comment]
There hasn't been a failure since 3/28,
So while the test might have flakes it is definitely less flaky than 12 failures per week now

**Comment by AishSundar** [comment]
Yes the latest runs look good. Please close the issue
