### ISSUE TITLE
Flaky tests: k8s.io/kubernetes/test/integration/ipamperf TestPerformance/RangeAllocator-KubeQPS10-Nodes10 

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#61854]
The new test (introduced by #61143) seems to be quite flaky.

Example failures:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61432/pull-kubernetes-integration/4240/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61848/pull-kubernetes-integration/4250/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61042/pull-kubernetes-integration/4234/

Should a "performance" test even be run in the pre-submit PR runs?

/cc @satyasm @bowei

**Comment by satyasm** [comment]
It does connect to etcd and does a fair amount of node additions and
deletions. Most of the times I've looked at the error, it seems to be at
the startup when connecting to etcd. Is there a way to retain this
capability so we  can continue to check on demand but not necessarily run
every time?

**Comment by satyasm** [comment]
The error in 60142 has already been fixed, if you notice https://github.com/kubernetes/kubernetes/blob/master/test/integration/ipamperf/cloud.go#L135, we now have a lock and it should not be happening now.

For the rest, the error is in the startup itself, namely, https://github.com/kubernetes/kubernetes/blob/master/test/integration/ipamperf/main_test.go#L31, which is starting the framework connecting to etcd. Any idea's on why this should be causing flakiness?

This was the same pattern used in scheduler_perf - https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/main_test.go#L26

**Comment by filbranden** [comment]
Can we please disable this test for the moment? It's causing significant flakiness and blocking other PRs from being merged...

**Comment by yujuhong** [comment]
@satyasm I'd suggest disable the tests first to stop the bleeding, and debug the issue at your own pace. It's probably not a good idea to run performance tests in this environment anyway since the tests are run in parallel (IIRC). Maybe you can set up a separate post-submit test job for these special-purpose tests.

**Comment by satyasm** [comment]
@yujuhong can you take a look at PR https://github.com/kubernetes/kubernetes/pull/61863 ? It's add skip for short tests, which should avoid running this for very PR?

**Comment by satyasm** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61863/pull-kubernetes-integration/4296/ shows that ipamperf tests are now skipped during integration testing.

All checks have passed and @bowei has given /lgtm. Waiting for auto-merge.

@yujuhong can you close this issue once verified? thanks!

**Comment by yujuhong** [comment]
@satyasm the bot will do that automatically since your PR description says it fixes this issue.
