### ISSUE TITLE
Kubernetes apiserver should throw errors if it's CA files don't match `extension-apiserver-authentication`

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#61879]
In a multi-master Kubernetes setup, the ca data in `extension-apiserver-authentication` configmap must match the ca flags for each kube-apiserver pod. Currently there is no such validation done. This causes difficult to debug bugs. For example, I just debugged a scenario where an aggregate api server was seeing intermittent authentication errors. The root cause turned out to be that the CA files on each master was not same. 

So, does it make sense for a kube-apiserver to ensure that it's CA flags match data in `extension-apiserver-authentication` configmap if it's pod ip is an endpoint for `kubernetes` svc?

/sig api-machinery

**Comment by deads2k** [comment]
> So, does it make sense for a kube-apiserver to ensure that it's CA flags match data in extension-apiserver-authentication configmap if it's pod ip is an endpoint for kubernetes svc?

I don't think so.  You have to choose a source for the information and that configmap is *not* the source.  That configmap is the "status" of the value and kube-apiservers are the source.

I would expect the deployment mechanism like kubeadm, openshift-ansible, tectonic operators, whatever gke does, to determine consistent values and provide the apiservers with correct values.

**Comment by tamalsaha** [comment]
> You have to choose a source for the information and that configmap is not the source

Fair point. But how about at least logging an warning in the kube-apiserver logs so that someone is trying to debug this, it is at least easier to find,

**Comment by liggitt** [comment]
> how about at least logging an warning in the kube-apiserver logs so that someone is trying to debug this, it is at least easier to find

the apiserver can log when it updates, but it wouldn't be a warning... updating that would be indistinguishable from a normal "startup after rotation" scenario

**Comment by joshuacox** [comment]
Just noting that when finding this issue on my setup, I had used [kubash](http://kubash.org/), which internall y follows this [google doc](https://docs.google.com/document/d/1rEMFuHo3rBJfFapKBInjCqm2d7xGkXzh0FpFO0cRuqg/edit) for multi-master initialization.  Poking around it is not me that initialized those particular CAs but it looks like kubeadm creates them:  https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certs.go
What is the fix?  To manually copy the certs from the primary master to the other masters?  Or should a bug be filed on kubeadm getting them to correct the issue?

**Comment by liggitt** [comment]
> Or should a bug be filed on kubeadm getting them to correct the issue?

Yes, the install/setup component owns distribution of updates to that config

**Comment by joshuacox** [comment]
@liggitt @tamalsaha is it the case that the certs should indeed be the same?  Is this actually a bug in kubeadm?   I do have scenarios where voyager is able to communicate just fine with the api server (despite all three masters having different `front-proxy-ca.crt`).

Can anyone verify for me that, indeed, on a multimaster setup these certs should be replicated and not generated individually?

**Comment by liggitt** [comment]
> is it the case that the certs should indeed be the same?

yes, the masters should agree on client-ca and front-proxy-ca

> I do have scenarios where voyager is able to communicate just fine with the api server (despite all three masters having different front-proxy-ca.crt).

you likely are not exercising the front-proxy capability in that case.

**Comment by joshuacox** [comment]
Fixing in kubash, @tamalsaha you can close here, unless you think there might be some way of illuminating this sort of condition by some error reporting/detection.

**Comment by tamalsaha** [comment]
This is not a Kubeadm bug. Kubeadm will auto generate the certs if the ca files are not provided. This helps in single master setup. In Multi-master setup the ca crt/key files should be generated outside and set in the /etc/kubernetes/pki/* folder so that Kubeadm can issue the server cert and client certs using the ca files.

Voyager uses aggregate api server to implement Webhooks. So, Voyager will work without this. Given aggregate api server  became GA in 1.10, webhook will be considered required feature to run Voyager at some point in future.

Regarding this bug, my point what that kube-apiserver somehow logs that its ca files don't match the ca data in the configmap. That can help find these types of issues easier.

**Comment by joshuacox** [comment]
yep, as I said earlier, I fixed in kubash and will be merging those fixes in soon.  Kubeadm is doing exactly what it is supposed to do.

I agree, this was obscure and any help on debugging such a condition would be welcome.

**Comment by tamalsaha** [comment]
I have written a tool that can detect this sort of issues https://appsco.de/2HZ8t1k . 
`onessl doctor --v=10`

This will collect various info for apiserver pods and check. https://github.com/appscode/kutil/tree/master/tools/doctor . If you have any question / find bugs, please file a pr in our repos.

**Comment by tamalsaha** [comment]
@liggitt / @deads2k , do you think `kube-apiserver` can at least add annotation to the `extension-apiserver-authentication` so that it is easy to tell if there is mis-match across apiservers?

```
annotations:
  synced/<kube-apiserver-pod-name>: "true"
  synced/<kube-apiserver-pod-name>: "false"
```

I see people tripping up on this issue and having hard time figuring out where the problem is.
