### ISSUE TITLE
How to handle multiple environment variables in yaml file

### ISSUE THREAD

**Issue by rrajadevops** [kubernetes/kubernetes#61896]
Hi Team,

I am having nearly 25 environment variables which I should use in my pod creation yaml file. But, If i configure all 25 env variables my YAML looks like huge in size. Is there any alternate method to get the defined secrets inside the pod.

Regards,
Raja

**Comment by rrajadevops** [comment]
@mountkin .. thanks for your input..
Actually my scenario is i have some list of values which i need to use securely. But if we want to use that value we need to define that environment variable in our YAML file, in that case it is like big size of file also it is keep on repeating ENV values how to avoid this. Hope we can use this as volume, but i am running PHP application, I know how to read that environment variable value in my code(using getenv('HOST_DB'). is there any way hoe to use that volume values inside php configuration files like db_config.php or settings.php??

**Comment by mountkin** [comment]
1. Put your environment variables in a file. For example:

    env.txt:
    ```
    db_password=secret
    api_key=xxxxxxxxx
    ```
2. Create a secret with `kubectl create secret generic my-credentials --from-env-file=env.txt`
3. Configure your pod spec to reference the secret to create environment variables:

    ```
    ...
      containers:
      - name: xxx
        envFrom:
        - secretRef:
            name: my-credentials
    ...
    ```

**Comment by rrajadevops** [comment]
@mountkin i am getting the below error while using envFrom:
error: error validating "python-api.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].envFrom): invalid type for io.k8s.api.core.v1.Container.envFrom: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false

Regards,
Raja

**Comment by mountkin** [comment]
@rrajadevops The error message is quite clear. You should double check the yaml to make sure the `enrFrom` field is an array. Pay attention to the dash and spaces around the `secretRef` field.

**Comment by rrajadevops** [comment]
Thanks @mountkin  it is working after restart my kubernets cluster. thanks for your help.
