### ISSUE TITLE
Passing topology info to StatefulSet pods

### ISSUE THREAD

**Issue by rkarthik007** [kubernetes/kubernetes#61906]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I have setup a regional cluster across 3 zones in us-west1, say the zones are a, b, c. I have a StatefulSet deployed across these zones. As background, I am trying to setup YugaByte DB - a transactional, high-performance DB which can run on multiple clouds/regions/zones in GKE using StatefulSets. YugaByte DB can run across clouds/regions/zones by configuring each of the slaves (called tablet-servers) with the fault domain they are running in, this is passed in as a part of the startup command.

I want to pass the region/zone info to the pod on startup as a part of the command (other options that are easy to make work are a gflag file or an env variable).

**What you expected to happen**:
How can I discover the region/zone from inside the pod?

So far the ways I have come up with need the end user to "know" the values for the various regions/zones ahead of time or to use helm charts to make these variables, and externally bring up a subset of pods in each region/zone. But this is pretty complicated for the end-user experience as well.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a regional cluster in GKE
* Deploy YugaByte DB across this cluster using:
```
kubectl apply -f https://raw.githubusercontent.com/YugaByte/yugabyte-db/master/cloud/kubernetes/yugabyte-statefulset-local-ssd-gke.yaml
```
* The node labels have the topology info in properties such as `failure-domain.beta.kubernetes.io/region=XXX` and `failure-domain.beta.kubernetes.io/zone=YYY`

There is no easy way to query this from within the pod. The downward API does not seem to expose this.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Running on GKE.

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux gke-karthik 4.13.0-1011-gcp #15-Ubuntu SMP Mon Feb 12 16:29:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rkarthik007** [comment]
cc @wojtek-t @thockin

**Comment by davidopp** [comment]
Mailing list discussion:
https://groups.google.com/d/msg/kubernetes-dev/jsZLWZCgGwc/fLLVPYmNBgAJ

**Comment by thockin** [comment]
Recap from the mailing list discussion:

For now you can use kube clients to read your node's metadata.labels and extract the labels you want.

We could codify that into downward API, but it's kind of ugly to reach across objects like that.

We could copy topological labels into your pod, but then we have to know exactly which labels are topological, and deal with conflicts on the pod's labels.

We could "promote" topological labels from node `metadata.labels` to a real field (still a map), and then when a pod is created, copy that info down into pod.status, and then expose that via downward API.

I am not sure this last is warranted, but I am not sure it is not.  It has implications for things that already deal with topology labels (e.g. storage, @msau42) and scheduling (@bsalamat).  Since labels are pretty generic, it's hard to know exactly who would be impacted.

**Comment by rkarthik007** [comment]
> We could copy topological labels into your pod, but then we have to know exactly which labels are topological, and deal with conflicts on the pod's labels.

Agree... especially across different cloud provider managed services.

> We could codify that into downward API, but it's kind of ugly to reach across objects like that.

This would be great if possible. But I am not aware of the internal architecture,  so not sure about the internal tradeoffs involved. But even this way, the burden of "interpreting" the topological labels exists across different cloud providers. Not sure there is a clean solution for that other than having a spec.
