### ISSUE TITLE
Authentication failed messages do not show what client failed to authenticate

### ISSUE THREAD

**Issue by XANi** [kubernetes/kubernetes#61900]
E0329 13:35:11.111234       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
    E0329 13:35:33.402009       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
    E0329 13:38:23.346687       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]

There is no information about which pod or IP tried to do that which makes looking for it very "fun" experience.

I wanted to make pull request, then I've read what is involved and decided it is not worth fucking around with CLA for a string of text, here is code if you want it 

https://github.com/efigence/kubernetes/commit/1d56a7fd377482f7c6307cc1525856fa6aec59c5

**Comment by tallclair** [comment]
This feels like something that's better left to audit logging. What is the reason for needing the IP here? I think we generally try to avoid logging IPs in debug logs, since they can be considered PII.

**Comment by XANi** [comment]
To know which pod failed to authenticate with the apiserver. It is much easier to just look at apiserver logs instead of trying to guess which one of tens/hundreds/thousands pods did it.

> I think we generally try to avoid logging IPs in debug logs, since they can be considered PII.

But pods are not people ? And logs shouldn't be visible to anyone but cluster admins anyway ?

**Comment by XANi** [comment]
Aside from that, IPs are logged anyway:

    I0403 08:24:54.988117       1 logs.go:41] http: TLS handshake error from 172.16.124.198:63088: read tcp 172.16.124.198:6443->172.16.124.198:63088: read: connection reset by peer
    I0403 08:24:54.988239       1 logs.go:41] http: TLS handshake error from 172.16.124.198:63090: read tcp 172.16.124.198:6443->172.16.124.198:63090: read: connection reset by peer
