### ISSUE TITLE
node not schedulable after delete and add back

### ISSUE THREAD

**Issue by chenww** [kubernetes/kubernetes#61903]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
pod can not be scheduled on a node in ready state

**What you expected to happen**:
pod should be able to schedule on deleted/add back node; otherwise node should not be shown "Ready"

**How to reproduce it (as minimally and precisely as possible)**:
1. cordon a node in k8s cluster
2. delete the node
3. add back the same node by restarting the kubelet
4. kubelet shows the node is back and in Ready state
5. However, no pod can be scheduled on this node

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wgliang** [comment]
It would be helpful if you could provide more information. Or you can try to reproduce the problem in another environment.

And /sig testing
