### ISSUE TITLE
Kubelet unable to send status updates(heartbeats) to APIServer 

### ISSUE THREAD

**Issue by jatan28** [kubernetes/kubernetes#61917]
We are investigating an issue where we see kubelet unable to send node status updates (heartbeats) to the API server for 15 consecutive minutes.  We are seeking guidance and inspiration.  We see this in multiple clusters, all in AWS, and we’re running short of suspects to interrogate.  Here’s some details on the  configuration of our environments:
**Kubernetes Version**: `1.7.8 and 1.9.3`
**CNI versions**: `Calico/node:v1.2.1` and `Calico/node:v2.6.7`, respectively (per versions listed above)
- Node mesh enabled
- Iptables in use
Small and medium clusters (ranging from 5 nodes to 50)
**Host OS**:
```Linux ip-172-21-189-23 4.4.0-1047-aws #56-Ubuntu SMP Sat Jan 6 19:39:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

**Docker info**:
```
Containers: 23
 Running: 20
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 1.12.6-cs13
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 128
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1030-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.94 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Kubelet Flags**:
```
--allow-privileged=true \
--cluster-dns=${cluster_dns } \
--cluster-domain=${cluster_domain} \
--cloud-provider=aws \
--cni-conf-dir=/etc/kubernetes/cni/net.d \
--cni-bin-dir=/opt/cni/bin \
--container-runtime=docker \
--eviction-hard=memory.available<200Mi \
--kubeconfig=/etc/kubernetes/kubeconfig.yaml \
--kube-reserved-cgroup=root \
--kube-reserved=cpu=1,memory=2Gi \
--network-plugin=cni \
--node-labels=${kubelet_node_labels} \
--pod-manifest-path=/etc/kubernetes/manifests \
--register-node=true \
--serialize-image-pulls=false \
--tls-cert-file=cert.pem \
--tls-private-key-file=key.pem \
${kubelet_node_taints}
```

Please help! :)

**Comment by dashpole** [comment]
Do you see any errors in the kubelet logs?  Specifically, any conflicting PATCH requests?

**Comment by slongstreet** [comment]
@dashpole We see the following sequence of error lines repeated for 15 consecutive minutes in the kubelet logs on affected machines:

```
Mar 29 21:55:52 <hostname> kubelet[1957]: E0329 21:55:52.007910    1957 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "<hostname>": Get https://<api-server-url>/api/v1/nodes/<hostname>?resourceVersion=0: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Mar 29 21:56:02 <hostname> kubelet[1957]: E0329 21:56:02.008269    1957 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "<hostname>": Get https://<api-server-url>/api/v1/nodes/<hostname>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Mar 29 21:56:12 <hostname> kubelet[1957]: E0329 21:56:12.008678    1957 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "<hostname>": Get https://<api-server-url>/api/v1/nodes/<hostname>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Mar 29 21:56:22 <hostname> kubelet[1957]: E0329 21:56:22.008993    1957 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "<hostname>": Get https://<api-server-url>/api/v1/nodes/<hostname>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Mar 29 21:56:32 <hostname> kubelet[1957]: E0329 21:56:32.009346    1957 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "<hostname>": Get https://<api-server-url>/api/v1/nodes/<hostname>: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Mar 29 21:56:32 <hostname> kubelet[1957]: E0329 21:56:32.009381    1957 kubelet_node_status.go:375] Unable to update node status: update node status exceeds retry count
```

**Comment by dashpole** [comment]
Do you have network connectivity between the node and the master?

**Comment by jatan28** [comment]
Yes, we have network connectivity between the nodes and the master. We don't know what exactly happens  during that 15 mins window. But after that the connectivity seems just fine , similar to what it was before that window.

**Comment by stephbu** [comment]
I work with @jatan28.  We've explored Control-plane side in Node Controller and replication set logs - that all looked healthy and doing the right thing.  Kubelet side, we read thru DMESG/JournalCtlD etc. At the time of recovery we noted in all circumstances that the net-link was being bounced at almost exactly the time of recovery - pointing the finger at whatever was touching the network.  

We considered it could be something like IPTables updates hanging resulting in Felix bouncing the link.  Last night we experimented with increasing node grace period from 135s to 16mins.  This morning 6 nodes in that 50 node cluster experienced the timeouts again, The kubelet recovered at the 15min mark as before, eviction was not triggered, nor was net-link reset.  None of the workloads lost network connectivity barring APIServer.

That points squarely back to Kubelet/Kube-client connection being the close to root cause.
On the AWS NLB we do notice periodic TCP connection resets - seems like USE1 is the worst/noisiest offender.

Sounds really close to these issues:
https://github.com/kubernetes/kubernetes/issues/41185
https://github.com/kubernetes/kubernetes/issues/41916

**Comment by jfoy** [comment]
@stephbu Do your NLB metrics show any suspicious events ~10s or less before the first logged "Client.Timeout exceeded while awaiting headers" message?

**Comment by stephbu** [comment]
Yes, we've see AWS NLB Metrics showing TCP reset spikes above normal levels in both client and/or target stats.

**Comment by johanneswuerbach** [comment]
I started seeing something similar when rolling API masters. Each master shutdown is taking a random number of nodes unhealthy all with the "Error updating node status" message. Restarting the kubelet immediately resolve the issue, but also waiting a couple of minutes eventually resolves this.

I'm running Kubernetes 1.8.10 and haven't seen this in 1.7.12 (what was running before).

Some additional details https://github.com/kubernetes/kops/issues/4946

**Comment by bgrant0607** [comment]
Ref #43516

**Comment by liggitt** [comment]
consolidating reports of this issue under https://github.com/kubernetes/kubernetes/issues/48638
