### ISSUE TITLE
no flexvol 'attach' call sent out (with --enable-controller-attach-detach=true)

### ISSUE THREAD

**Issue by sun7927** [kubernetes/kubernetes#61927]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
I have deployed a kubernetes cluster with 3 nodes, 1 for master and 2 for slave, and with --enable-controller-attach-detach=true. And then, I have installed my own flexvolume plugin on each node. 
When kubelet of each node started, it probed the plugin and called 'init' with following response:
```
Mar 30 03:33:32 k8s-test-9e3205ee82-0 myflex[19098]: time="2018-03-30T03:33:32Z" level=info msg="Starting up with args.." args="[/usr/libexec/kubernetes/kubelet-plugins/volume/exec/my~flex/.my-flex
Mar 30 03:33:32 k8s-test-9e3205ee82-0 myflex[19098]: time="2018-03-30T03:33:32Z" level=info msg="FLEX API: init"
Mar 30 03:33:32 k8s-test-9e3205ee82-0 myflex[19098]: time="2018-03-30T03:33:32Z" level=info msg="FLEX API Response to init" response="{\"status\":\"Success\",\"capabilities\":{\"attach\":true}}"
```

On the master node, the plugin has been loaded successfully with following log:
```
Mar 30 03:33:32 k8s-test-9e3205ee82-0 kubelet[18953]: I0330 03:33:32.730942   18953 plugins.go:436] Loaded volume plugin "flexvolume-my/flex"
```

And then, I have successfully created a PVC/PV of pvc-c233d80d-33cb-11e8-a4c7-aa00c725b885 through myflex plugin, and the PV has the correct flexVolume.drive set as below:
```
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
   flexVolume:
      driver: my/flex
      fsType: ext4
      options:
        volumeName: pvc-c233d80d-33cb-11e8-a4c7-aa00c725b885
``` 

Then, I have created a pod which would mount the above PVC. The pod has been assigned to one of slave node of k8s-test-9e3205ee82-1 where I could find the 'getvolumename' call was successful as below:
```
Mar 30 03:23:13 k8s-test-9e3205ee82-1 myflex[5333]: time="2018-03-30T03:23:13Z" level=info msg="FLEX API: getvolumename" args="[{\"kubernetes.io/fsType\":\"ext4\",\"kubernetes.io/pvOrVolumeName\":\"pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885\",\"kubernetes.io/readwrite\":\"rw\",\"volumeName\":\"pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885\"}]"
Mar 30 03:23:13 k8s-test-9e3205ee82-1 myflex[5333]: time="2018-03-30T03:23:13Z" level=info msg="FLEX API Response to getvolumename" response="{\"status\":\"Success\",\"volumeName\":\"pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885\"}" 
```
However, I couldn't find any log for the following 'attach' call from myflex plugin on any node including master and slaves. It supposed to be executed on the master node. So, the pod run into the status of ContainerCreating. And I found the following logs from the node hosting the pod:
```
Mar 30 03:25:03 k8s-test-9e3205ee82-1 kubelet[1980]: E0330 03:25:03.656085    1980 nestedpendingoperations.go:264] Operation for "\"flexvolume-my/flex/pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885\"" failed. No retries permitted until 2018-03-30 03:27:05.656061618 +0000 UTC (durationBeforeRetry 2m2s). Error: Volume not attached according to node status for volume "pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885" (UniqueName: "flexvolume-my/flex/pvc-d93343c7-33c3-11e8-a4c7-aa00c725b885") pod "nginx" (UID: "ec3aef0e-33c3-11e8-a4c7-aa00c725b885")
```

**What you expected to happen**:
1. According to my understanding, after 'getvolumename' call succeeded on the slave node assigned to the pod, it is expected the 'attach' call should be executed on the master node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
1. With kubernetes v1.8.10, is it still required to set '--enable-controller-attach-detach=true' to enable it?
2. Where is the code for triggering 'attach/detach' calls from master node?

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.10", GitCommit:"044cd262c40234014f01b40ed7b9d09adbafe9b1", GitTreeState:"clean", BuildDate:"2018-03-19T17:44:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Deployment:
```
Cluster: 3 nodes (Master: 1; Slave: 2)
```
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux k8s-test-9e3205ee82-0 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
apt-get install -y kubectl=1.8* kubelet=1.8* kubeadm=1.8*
```
- Others:

**Comment by sungjunyoung** [comment]
I have same issue too 😞 attach call-out is never executed..
