### ISSUE TITLE
Fix batching log audit backend

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/kubernetes#61932]
Buffered audit backend was extracted from webhook audit backend initially, so its behavior is better suited for this case. In case of log audit backend, some parameters don't make sense and the default configuration should be adjusted. There are two possible approaches to make buffered backend work better with log backend:

- Started by @tallclair in https://github.com/kubernetes/kubernetes/pull/61217, adding an option to send batches to the delegate backend synchronously, to avoid write contention
- Started by @hzxuzhonghu in https://github.com/kubernetes/kubernetes/pull/61027, adding a limit on the number of goroutines

The first approach seems more preferable to fix the original issue, however, the latter setting can be then used in other backends also, to limit the memory consumption. Maybe both should be implemented

/assign @loburm 
/cc @tallclair @sttts @hzxuzhonghu @CaoShuFeng

**Comment by tallclair** [comment]
This mostly just needs to clean up https://github.com/kubernetes/kubernetes/pull/61217. I might be able to tackle it next week.

**Comment by x13n** [comment]
I may be missing some context, but what's the point of having a synchronous buffer? Why is it better than having no buffer at all?

**Comment by tallclair** [comment]
The buffer is still async, but calling the delagate backend can be synchronous for the buffer worker. More specifically, this is the old behavior, with each line being a separate go-routine

1. request handler: queue audit event in buffer
2. buffer worker: unqueue audit events, batch them, pass batch to delegate go-routine
3. delegate go-routine: process batched events

This makes sense for the webhook backend with a different routine to handle each audit request, but it doesn't make sense for the log backend where the different writing routines just create lock contention. With the new PR & `AsyncDelegate = false`, you get:

1. request handler: queue audit event in buffer
2. buffer worker: unqueue audit events, batch them, call delegate to process the events (in the same routine)

Make sense?
