### ISSUE TITLE
kubeadm init fails if resolv.conf contains 3 or more domains

### ISSUE THREAD

**Issue by natipo** [kubernetes/kubernetes#61934]
/kind bug

**What happened**:
If `/etc/resolv.conf` file contains 3 or more domains then kubeadm init fails.

**What you expected to happen**:
Kubernetes master should be initialized successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add 3 domains to `/etc/resolv.conf` file.
2. Run kubeadm init to initialize kubernetes master `sudo kubeadm init --pod-network-cidr=10.244.0.0/16`
3. See that it hangs on `[init] This might take a minute or longer if the control plane images have to be                                      pulled`.
4. See that initialization fails after some time `Unfortunately, an error has occurred: timed out waiting for the condition`.

**Anything else we need to know?**:

- I tried initializing master within a single domain. After successful initialization I added more domains. However after machine restart the Kubernetes master does not start. I cannot find workaround.
- My resolv.conf file contains 7 domains inside.

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux ECSB00101B7F 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by natipo** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/issues/9229

**Comment by neolit123** [comment]
@natipo hi, please re-open if this fails for you in 1.11.1 or 1.10.6.

/close
