### ISSUE TITLE
kube-dns crashloopbackoff after flannel Install

### ISSUE THREAD

**Issue by rtayalla** [kubernetes/kubernetes#61944]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
kubeadm init --kubernetes-version=v1.9.0 --pod-network-cidr=10.244.0.0/16
kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl get pod --all-namespaces
NAMESPACE     NAME                                  READY          STATUS                  RESTARTS          AGE
kube-system   kube-dns-6f4fd4bdf-ws2xx      2/3           CrashLoopBackOff          9                 13m

**What you expected to happen**:
Kube-dns should be working fine without any errors or crashloopbackoff

**How to reproduce it (as minimally and precisely as possible)**:
On Centos 7.2. Execute Below
$ sudo kubeadm reset
$ sudo systemctl restart kubelet.service
$ sudo kubeadm init --pod-network-cidr=10.244.0.0/16
$ kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
$ kubectl get pod --all-namespaces

**Anything else we need to know?**:
swapoff
selinux disabled
Docker version 17.03
Docker and kubernetes have same cgroup driver : cgroupfs

**Additional Information**:
ps -ef | grep kube-prox[y]:  
root  11423 11406  0 15:55 ? 00:00:05 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf
******************************************************
ps -ef | grep docker[d]:  
root 28523 1  1 Mar29 ?  00:29:33 /usr/bin/dockerd
*******************************************************
Route -n From the HOST
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.28.142.1    0.0.0.0         UG    100    0        0 eth0
10.32.0.0       0.0.0.0         255.240.0.0     U     0      0        0 weave
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 cni0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.28.142.0    0.0.0.0         255.255.255.128 U     100    0        0 eth0
***************************************
Route from BusyBox:
/ #  route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.244.0.1      0.0.0.0         UG    0      0        0 eth0
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.244.0.0      10.244.0.1      255.255.0.0     UG    0      0        0 eth0
********************************
Iptables-save:

# Generated by iptables-save v1.4.21 on Fri Mar 30 16:46:18 2018
*nat
:PREROUTING ACCEPT [1:334]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [3:180]
:POSTROUTING ACCEPT [3:180]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-EUWKL2M77WKLSOPN - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:WEAVE - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTI                                                                                                         NG
-A POSTROUTING -s 10.244.0.14/32 -p udp -m udp --dport 53 -j MASQUERADE
-A POSTROUTING -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
-A POSTROUTING -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.244.0.0/16 -d 10.244.0.0/24 -j RETURN
-A POSTROUTING ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
-A POSTROUTING -j WEAVE
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT"                                                                                                          -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-EUWKL2M77WKLSOPN -s 172.28.142.85/32 -m comment --comment "default/kuber                                                                                                         netes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-EUWKL2M77WKLSOPN -p tcp -m comment --comment "default/kubernetes:https"                                                                                                          -m recent --set --name KUBE-SEP-EUWKL2M77WKLSOPN --mask 255.255.255.255 --rsource -m                                                                                                          tcp -j DNAT --to-destination 172.28.142.85:6443
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p udp -m comment --comment "ku                                                                                                         be-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:                                                                                                         dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.10/32 -p tcp -m comment --comment "ku                                                                                                         be-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:                                                                                                         dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.96.0.1/32 -p tcp -m comment --comment "def                                                                                                         ault/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:htt                                                                                                         ps cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must                                                                                                          be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m rece                                                                                                         nt --rcheck --seconds 10800 --reap --name KUBE-SEP-EUWKL2M77WKLSOPN --mask 255.255.2                                                                                                         55.255 --rsource -j KUBE-SEP-EUWKL2M77WKLSOPN
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE                                                                                                         -SEP-EUWKL2M77WKLSOPN
-A WEAVE -s 10.32.0.0/12 -d 224.0.0.0/4 -j RETURN
-A WEAVE ! -s 10.32.0.0/12 -d 10.32.0.0/12 -j MASQUERADE
-A WEAVE -s 10.32.0.0/12 ! -d 10.32.0.0/12 -j MASQUERADE
COMMIT
# Completed on Fri Mar 30 16:46:18 2018
# Generated by iptables-save v1.4.21 on Fri Mar 30 16:46:18 2018
*filter
:INPUT DROP [3:1002]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-SERVICES - [0:0]
:WEAVE-NPC - [0:0]
:WEAVE-NPC-DEFAULT - [0:0]
:WEAVE-NPC-INGRESS - [0:0]
-A INPUT -j KUBE-FIREWALL
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -i lo -j ACCEPT
-A INPUT -s 127.0.0.0/8 -j DROP
-A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
-A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
-A INPUT -p icmp -m state --state ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m state --state NEW -j ACCEPT
-A INPUT -s 127.0.0.0/8 -p tcp -m tcp --dport 25 -m state --state NEW -j ACCEPT
-A FORWARD -o weave -m comment --comment "NOTE: this must go before \'-j KUBE-FORWAR                                                                                                         D\'" -j WEAVE-NPC
-A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
-A FORWARD -o weave -j DROP
-A FORWARD -i weave ! -o weave -j ACCEPT
-A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
-A FORWARD -s 10.244.0.0/16 -j ACCEPT
-A FORWARD -d 10.244.0.0/16 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -s 127.0.0.0/8 -p tcp -m tcp --sport 25 -m state --state ESTABLISHED -j AC                                                                                                         CEPT
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packe                                                                                                         ts" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x                                                                                                         4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 10.244.0.0/16 -m comment --comment "kubernetes forwarding conntra                                                                                                         ck pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.244.0.0/16 -m comment --comment "kubernetes forwarding conntra                                                                                                         ck pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:                                                                                                         dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachabl                                                                                                         e
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:                                                                                                         dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreac                                                                                                         hable
-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-E.1.0W^NGSp]0_t5WwH/]gX@L dst -m comme                                                                                                         nt --comment "DefaultAllow isolation for namespace: default" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-?b%zl9GIe0AET1(QI^7NWe*fO dst -m comme                                                                                                         nt --comment "DefaultAllow isolation for namespace: kube-system" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-0EHD/vdN#O4]V?o4Tx7kS;APH dst -m comme                                                                                                         nt --comment "DefaultAllow isolation for namespace: kube-public" -j ACCEPT
COMMIT
*****************************************************
**Kubedns Logs**:

kubectl logs -n kube-system  kube-dns-6f4fd4bdf-ws2xx -c kubedns
I0330 17:00:09.694382       1 dns.go:48] version: 1.14.6-3-gc36cb11
I0330 17:00:09.695524       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0330 17:00:09.695593       1 server.go:112] FLAG: --alsologtostderr="false"
I0330 17:00:09.695610       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
I0330 17:00:09.695618       1 server.go:112] FLAG: --config-map=""
I0330 17:00:09.695622       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I0330 17:00:09.695633       1 server.go:112] FLAG: --config-period="10s"
I0330 17:00:09.695639       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I0330 17:00:09.695644       1 server.go:112] FLAG: --dns-port="10053"
I0330 17:00:09.695658       1 server.go:112] FLAG: --domain="cluster.local."
I0330 17:00:09.695675       1 server.go:112] FLAG: --federations=""
I0330 17:00:09.695680       1 server.go:112] FLAG: --healthz-port="8081"
I0330 17:00:09.695685       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I0330 17:00:09.695689       1 server.go:112] FLAG: --kube-master-url=""
I0330 17:00:09.695696       1 server.go:112] FLAG: --kubecfg-file=""
I0330 17:00:09.695700       1 server.go:112] FLAG: --log-backtrace-at=":0"
I0330 17:00:09.695711       1 server.go:112] FLAG: --log-dir=""
I0330 17:00:09.695716       1 server.go:112] FLAG: --log-flush-frequency="5s"
I0330 17:00:09.695720       1 server.go:112] FLAG: --logtostderr="true"
I0330 17:00:09.695724       1 server.go:112] FLAG: --nameservers=""
I0330 17:00:09.695728       1 server.go:112] FLAG: --stderrthreshold="2"
I0330 17:00:09.695743       1 server.go:112] FLAG: --v="2"
I0330 17:00:09.695747       1 server.go:112] FLAG: --version="false"
I0330 17:00:09.695753       1 server.go:112] FLAG: --vmodule=""
I0330 17:00:09.695959       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
I0330 17:00:09.696919       1 server.go:213] Skydns metrics enabled (/metrics:10055)
I0330 17:00:09.696962       1 dns.go:146] Starting endpointsController
I0330 17:00:09.696975       1 dns.go:149] Starting serviceController
I0330 17:00:09.697163       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0330 17:00:09.697201       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0330 17:00:10.197461       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:10.697424       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:11.197435       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:11.697446       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:12.197455       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:12.697439       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:13.197408       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:13.697415       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:14.197524       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:14.697364       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:15.197388       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:15.697398       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:16.197408       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:16.697409       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:17.197456       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:17.697479       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:18.197468       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:18.697431       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:19.197483       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:19.697476       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:20.197419       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:20.697406       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:21.197391       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:21.697443       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:22.197407       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:22.697480       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:23.197429       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:23.697486       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:24.197471       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:24.697644       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:25.197458       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:25.697460       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:26.197406       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:26.697440       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:27.197441       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:27.697454       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:28.197469       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:28.697439       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:29.197481       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:29.697343       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:30.197410       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:30.697454       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:31.197436       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:31.697457       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:32.197420       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:32.697426       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:33.197418       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:33.697463       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:34.197443       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:34.697432       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:35.197470       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:35.697462       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:36.197479       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:36.697409       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:37.197427       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:37.697449       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:38.197356       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:38.697465       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:39.197467       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:39.697353       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E0330 17:00:39.699611       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E0330 17:00:39.699611       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0330 17:00:40.197460       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:40.697467       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:41.197435       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:41.697456       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:42.197422       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:42.697482       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:43.197442       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:43.697515       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:44.197431       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:44.697376       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:45.197442       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:45.697399       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:46.197463       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:46.697472       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:47.197469       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:47.697455       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:48.197415       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:48.697441       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:49.197452       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:49.697322       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:50.197447       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:50.697436       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:51.197406       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:51.697455       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:52.197463       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:52.697540       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:53.197416       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:53.697387       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:54.197500       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:54.697372       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:55.197440       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:55.697495       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:56.197516       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:56.697526       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:57.197459       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:57.697424       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:58.197409       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:58.697498       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:59.197438       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:00:59.697272       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:00.197391       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:00.697402       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:01.197372       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:01.697432       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:02.197412       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:02.697426       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:03.197458       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:03.697382       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:04.197443       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:04.697466       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:05.197385       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:05.697440       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:06.197436       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:06.697424       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:07.197392       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:07.697424       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:08.197442       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:08.697525       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0330 17:01:09.197498       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
F0330 17:01:09.697442       1 dns.go:167] Timeout waiting for initialization
*********************************************************************
**Environment**:
- Kubernetes version (use `kubectl version`):  kubectl/kubeadm version 1.9
- Cloud provider or hardware configuration: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
- OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- Install tools:
- Others:

**Comment by rtayalla** [comment]
needs-sig

**Comment by rtayalla** [comment]
sig/network

**Comment by daxzhuo** [comment]
Make sure node can access api-server with clusterIP `kubectl describe service kubernetes`.
If not you could try install conntrack `yum install conntrack` and restart `kube-proxy`.
Let me know if it work.

**Comment by rtayalla** [comment]
Connection refused when I did CURL with the clusterIP. Installed Conntrack and restarted the kube-proxy but i did not work. 

** Details**:

kubectl describe service kubernetes


Type:              ClusterIP
IP:                10.96.0.1
Port:              https  443/TCP

******************************************************
From the busy box :

kubectl run -it --rm --restart=Never busybox --image=radial/busyboxplus sh
If you don't see a command prompt, try pressing enter.
/ # curl -v 10.96.0.1:443
* Failed to connect to 10.96.0.1 port 443: Connection timed out
curl: (7) Failed to connect to 10.96.0.1 port 443: Connection timed out
**********************************************************
Conntrack Install:

sudo yum install conntrack
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package conntrack-tools-1.4.4-3.el7_3.x86_64 already installed and latest version
****************************************************************************************
Kube-proxy restart:

kubectl delete pod kube-proxy-zt4td  --namespace=kube-system
********************************************************************************************
kubectl get pods --all-namespaces: 

kube-system   kube-dns-6f4fd4bdf-rhngp         1/3       CrashLoopBackOff   19         34m
kube-system   kube-flannel-ds-zp7cf                 1/1             Running               0          3d
kube-system   kube-proxy-48dkc                        1/1              Running             0         
***********************************************************************************************

**Comment by rtayalla** [comment]
The kube-dns is working fine once i stoppped the Iptables services after deleting the kube-dns pod. But I could not able to figure out why the kube-dns is going crashloopbackoff once i restart the iptables. 
As soon as i delete a pod while the iptables are running kube-dns is going to crashloopbackoff. Can anyone help me to get it work with Iptables ?

**Comment by rtayalla** [comment]
Closing this ticket: 

Issue resolved : Changed the DROP rules to ACCEPT in the /etc/sysconfig/iptables.
Deleted the DNS pod and recreated the pod and its running.

Thanks

**Comment by anjuls** [comment]
I have the same problem, It didn't work for me even after doing following

```
systemctl stop kubelet
systemctl stop docker
iptables --flush
iptables -tnat --flush
iptables -P FORWARD ACCEPT
systemctl start docker
systemctl start kubelet
kubectl delete pods -n kube-system -l k8s-app=kube-dns 
```

Is anyone else facing this issue?

**Comment by ekcheu** [comment]
With the weave network, the above solution of iptables -P FORWARD ACCEPT worked.. However, when I used kube-router as a network, I simply had to turn off iptables in order for kubernetes to stop crashing the kube-dns pod containers.  
With all the iptable firewall rules and other configuration that I had to haggle with, docker swarm mode seems so much easier on a local install for redhat than kubernetes even though it may not be for everyone and may not be as supported with certain applications.
