### ISSUE TITLE
Normalisation of command line arguments (underscore to hyphen) for kube-apiserver no longer occurs 

### ISSUE THREAD

**Issue by Alex-II** [kubernetes/kubernetes#61952]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kube-apiserver exited with an error when started with the --admission_control flag
The error was that "admission_control" is not a valid flag

**What you expected to happen**:
Expected "admission_control" to be a valid flag and for kube-apiserver to start normally.

**How to reproduce it (as minimally and precisely as possible)**:
In /etc/kubernetes/apiserver, set this line as so:
KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota"

**Anything else we need to know?**:
"admission_control" worked as a flag on Kubernetes v1.9.6
In Kubernetes 1.10 , "admission-control" does work though (hyphen instead of underscore) so it seems some flag normalisation no longer occurs in 1.10 that used to occur in 1.9.6.

Looking at https://github.com/kubernetes/kubernetes/blob/7ba00fc08b81bcf2df6bb15fe1f6224b49d42760/cmd/kube-apiserver/apiserver.go#L45 in version 1.10, it seems the normalisation doesn't occur despite `pflag.CommandLine.SetNormalizeFunc(utilflag.WordSepNormalizeFunc)` being called. We suspect it's because any attempt at normalisation has already occurred a few lines back, at `command := app.NewAPIServerCommand()`.

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes v1.10.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Atomic Host 7.4
- Kernel (e.g. `uname -a`): Linux 3.10.0-693.1.1.el7.x86_64 #1 SMP Thu Aug 3 08:15:31 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

@kubernetes/sig-cli-bugs

**Comment by Alex-II** [comment]
@kubernetes/sig-cli-bugs

**Comment by terinjokes** [comment]
@Alex-II Cobra creates an instance of the `FlagSet`, so I think the correct code should have been `command.Flags().SetNormalizeFunc(utilflag.WordSepNormalizeFunc)`
