### ISSUE TITLE
Providing incorrect oidc-client-id to apiserver causes apiserver to become unresponsive

### ISSUE THREAD

**Issue by groner** [kubernetes/kubernetes#61961]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
I redeployed k8s v1.8.10 using kube-aws v0.9.9 adding oidc to the configuration, having the right issuer-url, but the wrong client-id.

After the controller node and api-server were up, kubectl certificate authenticated requests would timeout until about 20 minutes after the server started.  Also, curl requests with certificate and key configured would timeout.

Unauthenticated requests were handled promptly.  Requests to the insecure port were also handled.

After redeploying with the correct oidc client-id the apiserver was responsive again.

**What you expected to happen**:

Certificate authenticated requests would be handled promptly regardless of oidc misconfiguration.

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a minimal recipe prepared, but I believe the only effective change in this deployment was the addition of oidc arguments to the kube-apiserver pod.
```
    - --oidc-issuer-url=https://accounts.google.com
    - --oidc-client-id=[SOMETHING-WRONG]
    - --oidc-username-claim=email
    - '--oidc-username-prefix=oidc:'
    - --oidc-groups-claim=groups
    - '--oidc-groups-prefix=oidc:'
```

I'm happy to provide more details of our deployment if that would help.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.10+coreos.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1688.4.0 (Rhyolite)
- Kernel (e.g. `uname -a`):
- Install tools: kube-aws v0.9.9
- Others:

**Comment by groner** [comment]
I guess this is relevant to api-machinery sig or auth sig.

/sig api-machinery

**Comment by ericchiang** [comment]
Do you have any logs from your API server? Just from reasoning about the codebase I don't understand why the wrong client ID would impact TLS client auth.

**Comment by groner** [comment]
@ericchiang Here are the apiserver logs from one run.  
https://gist.github.com/groner/18f071a7880cf763c5c8fbfff3875036

There is a considerable amount of spam from some clients failing to authenticate 6 times per second, for the entire time the server is running (even when I'm experiencing these timeouts).  I think this is unrelated, because the server is responsive now even though these failed attempts persist 6 times per second.

Anway, the logs may be clearer without that noise, so I've included a trimmed copy of the log in addition to the full log.

**Comment by jimangel** [comment]
I think this issue is still valid - does anyone know if there's been a fix implemented?

/remove-lifecycle rotten

**Comment by liggitt** [comment]
I've tried to recreate the issue and have been unable to. OIDC auth fails (obviously), but other auth methods (like x509 certs and other token auth) remain responsive.

**Comment by jimangel** [comment]
@liggitt how are you testing this? I saw the same issues with vSphere VMs (kubeadm). I believe the issue was with names containing underscores. I will test and verify once I hear back how you are testing.

**Comment by liggitt** [comment]
I added the arguments in the issue description (valid issuer url, invalid client id, etc), then attempted to make API requests with x509 authn, service account bearer tokens, and oidc bearer tokens.

**Comment by jimangel** [comment]
I guess this can be closed since it's been open so long and can't be recreated. I might have ran into a different issue where kubeadm didn't like adding "groups" to the OIDC api server params. It would kill the pod until that field was removed (v1.9.6).

**Comment by liggitt** [comment]
> I guess this can be closed since it's been open so long and can't be recreated.

Sorry we couldn't reproduce it. Definitely let us know if you find out more info to help reproduce it.

> I might have ran into a different issue where kubeadm didn't like adding "groups" to the OIDC api server params. It would kill the pod until that field was removed (v1.9.6).

Sounds like an invalid flag name or value. We you able to resolve that issue?
