### ISSUE TITLE
Group ID in image config is ignored.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#61967]
Today, kubelet gets User ID from image config.  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L986

Passes that user ID to container runtime when create container as `run_as_user` or `run_as_username` https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L558.

Dockershim passes the user id / user name to docker. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L84

Docker uses the passed in `user` to overwrite the `user` specified in image config. https://github.com/moby/moby/blob/master/daemon/commit.go#L23

The problem is that, if the User in image config also contains GID, e.g. `1234:adm`, the GID won't be applied, because `1234` passed by dockershim will overwrite `1234:adm`.

In this case, Docker will try to find `1234` in `/etc/passwd`. If it is found, Docker will use the corresponding GID https://github.com/moby/moby/blob/master/vendor/github.com/opencontainers/runc/libcontainer/user/user.go#L293; If not, Docker will use default GID https://github.com/moby/moby/blob/master/vendor/github.com/opencontainers/runc/libcontainer/user/user.go#L246.

But in any way, it will not be `adm`.

To fix this, there are 2 options:
* Option 1: Kubelet handles both user and group. Let container runtime return `GID` and `GroupName` from `ImageStatus`; and then let kubelet pass both user and group to container runtime.
* Option 2: Kubelet doesn't handle image default user. Kubelet doesn't apply user or group unless `RunAsUser` or `RunAsGroup` are explicitly specified. And CRI enforces container runtime to apply the default user / group defined in the image config if no user is specified in CRI.

Related to https://github.com/kubernetes/features/issues/213, https://github.com/kubernetes/kubernetes/issues/30039#issuecomment-377588733

@kubernetes/sig-node-bugs @yujuhong @feiskyer @krmayankk

**Comment by bubba0823** [comment]
Fix

**Comment by krmayankk** [comment]
thanks @Random-Liu  i am already fixing this
