### ISSUE TITLE
should support passing stop channel to control controller-manager gracefully exit

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#61975]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

There is no way to control controller-manager to exit gracefully when I kill its process directly(e.g. upgrade). In such case, there maybe kinds of disadvantages.

1.  Exit just after loadbalancer service deletion triggered (service controller have no enough time to process this service deletion),   it may cause many resources leak on LoadBalancer side. 

2.  I think pv may have similar issue if it is dynamic provisioned.

3. Whatever I want to do with resource deletion in other controllers, I have no way to process such case gracefully.

I do suggest making use of `staging/src/k8s.io/apiserver/pkg/server/signal.go`

**Comment by hzxuzhonghu** [comment]
/sig api-mahinery
client-go leaderelection should provide a mechanism to pass a stop channel to it for running Callbacks.OnStartedLeading.

**Comment by lavalamp** [comment]
cc @cheftako
