### ISSUE TITLE
Statefulset pods sometimes continually rolling

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#61998]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Statefulsets are sometimes continually rolling pods and I don't know why
statefulset created: 
statefulset.yml:
https://gist.github.com/ryanmcnamara/9e81c2bd2c6ac22fe8c12bc2a68a8aad
storageclass referenced:
https://gist.github.com/ryanmcnamara/cdf8ade20d3a853d5ed2d80b60ead79f
kubectl describe statefulset statefulset-test: 
https://gist.github.com/ryanmcnamara/e2bf74a8d7a4f0cbaa19f98ca57b4348

As you can see from the above describe, the pod in the statefulset has been restarted a lot of times. Observing the created pod, 
1) The pod comes up ready 
2) immediately transitions to terminating 
3) Is terminated
4) A new pod is created
5) Go back to (1) (repeats forever)

Despite no updates to the statefulset spec ocurring.

Making a change to the statefulset template (for example a trivial change adding a nonsense annotation) stops the rolling and fixes the issue

When this statefulset was created, there was a mutating webhook enabled. After the observed pod rolling. I disabled this by making its configuration invalid and making it non required, and the rolling persisted.

The status of the statefulset: `kubectl get statefulset statefulset-test -o yaml`:
https://gist.github.com/ryanmcnamara/1cbd58c4e9b7843f9443ee4010d41ffb

You can see that there is a discrepency between currentRevision and updateRevision.
  currentRevision: statefulset-test-8696d5779b
  updateRevision: statefulset-test-8696d5778f
A short while later the status is changed to contain
  currentRevision: statefulset-test-d8b584c9f
  updateRevision: statefulset-test-d8b584c9b
This change happened at Sun Apr  1 19:48:48 2018
Presumably after the rollout of statefulset-test-8696d5778f is complete.

Here are all the controllerrevisions from above:
kubectl get controllerrevision statefulset-test-8696d5779b -o yaml
https://gist.github.com/ryanmcnamara/ee54d1d5941cfde857a5589a8347c9a5
kubectl get controllerrevision statefulset-test-8696d5778f -o yaml:
https://gist.github.com/ryanmcnamara/4bf24bafa00c8e2434ae5d4287ed728a
kubectl get controllerrevision statefulset-test-d8b584c9b -o yaml:
https://gist.github.com/ryanmcnamara/4b49a0504653ba2d92585fb4015897c2

The differences between the above controllerrevisions are insignificant (the hash, the creation timestamp, the name, the resource version, the uid, the self link)

Interestingly all these controllerrevisions were created very close together in time shortly after I created the statefulset
The current controllerrevisions are
```
[rmcnamara@ip-10-0-112-31 ~]$ kubectl get controllerrevisions
NAME                          CONTROLLER                     REVISION   AGE
statefulset-test-8696d57789   StatefulSet/statefulset-test   1          13h
statefulset-test-8696d5778b   StatefulSet/statefulset-test   1          13h
statefulset-test-8696d5778f   StatefulSet/statefulset-test   1          13h
statefulset-test-8696d5779b   StatefulSet/statefulset-test   1          13h
statefulset-test-cf9d4cdf6    StatefulSet/statefulset-test   1          13h
statefulset-test-cf9d4cdfc    StatefulSet/statefulset-test   1          13h
statefulset-test-cf9d4cdfd    StatefulSet/statefulset-test   1          13h
statefulset-test-cf9d4cf44    StatefulSet/statefulset-test   1          13h
statefulset-test-cf9d4cf45    StatefulSet/statefulset-test   1          13h
statefulset-test-d8b584c9b    StatefulSet/statefulset-test   1          13h
statefulset-test-d8b584c9f    StatefulSet/statefulset-test   1          13h
```
After watching the state change for a while, it actually seems like the statefulset is just cycling through the updateRevision being one of the above 10 controllerrevisions

Leaders during this time
```
[rmcnamara@ip-10-0-112-31 ~]$ kubectl get endpoints kube-controller-manager -n kube-system -o yaml | grep alpha
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ip-10-0-100-151","leaseDurationSeconds":15,"acquireTime":"2018-04-01T05:50:03Z","renewTime":"2018-04-01T20:13:58Z","leaderTransitions":7}'
[rmcnamara@ip-10-0-112-31 ~]$ kubectl get endpoints kube-scheduler -n kube-system -o yaml | grep alpha
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ip-10-0-100-151","leaseDurationSeconds":15,"acquireTime":"2018-04-01T05:50:01Z","renewTime":"2018-04-01T20:14:06Z","leaderTransitions":8}'
```

From kube-controller-manager logs during this time, here is one excerpt:
```
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.344768    1565 stateful_set.go:455] Syncing StatefulSet default/statefulset-test with 1 pods
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.344653    1565 disruption.go:403] No PodDisruptionBudgets found for pod statefulset-test-0, PodDisruptionBudget controller will avoid syncing.
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.344861    1565 disruption.go:343] No matching pdb for pod "statefulset-test-0"
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.346127    1565 stateful_set_control.go:502] StatefulSet default/statefulset-test terminating Pod statefulset-test-0 for update
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.353804    1565 disruption.go:340] updatePod called on pod "statefulset-test-0"
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.353766    1565 stateful_set.go:226] Pod statefulset-test-0 updated, objectMeta {Name:statefulset-test-0 GenerateName:statefulset-test- Namespace:default SelfLink:/api/v1/namespaces/default/pods/statefulset-test-0 UID:aa09a5de-35e5-11e8-93f3-0e0de0418f44 ResourceVersion:957880 Generation:0 CreationTimestamp:2018-04-01 19:48:35 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[controller-revision-hash:statefulset-test-cf9d4cdfd deployment-test: statefulset.kubernetes.io/pod-name:statefulset-test-0] Annotations:map[] OwnerReferences:[{APIVersion:apps/v1beta1 Kind:StatefulSet Name:statefulset-test UID:fc4a62e6-3579-11e8-93f3-0e0de0418f44 Controller:0xc423c291f6 BlockOwnerDeletion:0xc423c291f7}] Initializers:nil Finalizers:[] ClusterName:} -> {Name:statefulset-test-0 GenerateName:statefulset-test- Namespace:default SelfLink:/api/v1/namespaces/default/pods/statefulset-test-0 UID:aa09a5de-35e5-11e8-93f3-0e0de0418f44 ResourceVersion:957882 Generation:0 CreationTimestamp:2018-04-01 19:48:35 +0000 UTC DeletionTimestamp:2018-04-01 19:49:16 +0000 UTC DeletionGracePeriodSeconds:0xc42233dde0 Labels:map[controller-revision-hash:statefulset-test-cf9d4cdfd deployment-test: statefulset.kubernetes.io/pod-name:statefulset-test-0] Annotations:map[] OwnerReferences:[{APIVersion:apps/v1beta1 Kind:StatefulSet Name:statefulset-test UID:fc4a62e6-3579-11e8-93f3-0e0de0418f44 Controller:0xc42233dde8 BlockOwnerDeletion:0xc42233dde9}] Initializers:nil Finalizers:[] ClusterName:}.
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.353829    1565 disruption.go:403] No PodDisruptionBudgets found for pod statefulset-test-0, PodDisruptionBudget controller will avoid syncing.
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.353854    1565 disruption.go:343] No matching pdb for pod "statefulset-test-0"
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.354030    1565 event.go:218] Event(v1.ObjectReference{Kind:"StatefulSet", Namespace:"default", Name:"statefulset-test", UID:"fc4a62e6-3579-11e8-93f3-0e0de0418f44", APIVersion:"apps", ResourceVersion:"957843", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' delete Pod statefulset-test-0 in StatefulSet statefulset-test successful
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.354836    1565 attach_detach_controller.go:493] processVolumesInUse for node "ip-10-0-107-133.ec2.internal"
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.354883    1565 actual_state_of_world.go:350] SetVolumeMountedByNode volume kubernetes.io/aws-ebs/aws://us-east-1a/vol-0d5396c605c0a817f to the node "ip-10-0-107-133.ec2.internal" mounted true
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.354900    1565 actual_state_of_world.go:350] SetVolumeMountedByNode volume kubernetes.io/aws-ebs/aws://us-east-1a/vol-079810a7d16ba3e53 to the node "ip-10-0-107-133.ec2.internal" mounted true
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.355413    1565 stateful_set.go:417] Finished syncing statefulset "default/statefulset-test" (10.728123ms)
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: E0401 19:48:46.355436    1565 stateful_set.go:399] Error syncing StatefulSet default/statefulset-test, requeuing: StatefulSet.apps "statefulset-test" is invalid: status.currentReplicas: Invalid value: -1: must be greater than or equal to 0
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.355514    1565 stateful_set.go:455] Syncing StatefulSet default/statefulset-test with 1 pods
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.356747    1565 stateful_set_control.go:351] StatefulSet default/statefulset-test has 1 unhealthy Pods starting with statefulset-test-0
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.356765    1565 stateful_set_control.go:412] StatefulSet default/statefulset-test is waiting for Pod statefulset-test-0 to Terminate
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.362906    1565 stateful_set_control.go:99] StatefulSet default/statefulset-test pod status replicas=1 ready=1 current=0 updated=0
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.362917    1565 stateful_set_control.go:107] StatefulSet default/statefulset-test revisions current=statefulset-test-d8b584c9f update=statefulset-test-8696d5778b
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.362925    1565 stateful_set.go:460] Successfully synced StatefulSet default/statefulset-test successful
Apr 01 19:48:46 ip-10-0-100-151 kube-controller-manager[1565]: I0401 19:48:46.362930    1565 stateful_set.go:417] Finished syncing statefulset "default/statefulset-test" (7.47279ms)
```

The error sync in there is suspicous, and as you can see the controllerrevisions are changing in the logs

I have the full logs from a 5 minute window on either side of the above if necessary.

The reason I'm inclined to think this is a kubernetes bug is that any update to the statefulset template fixes the problem.

**How to reproduce it (as minimally and precisely as possible)**:

Not really sure. Worth just trying to create the above statefulset (requires creating the 
I tried deleting and recreating the above statefulset and it didn't happen, so something flaky is going on

**Anything else we need to know?**:
kubernetes 1.9.3 (client and server)
cloud provider: aws

**Comment by ryanmcnamara** [comment]
I realize this will probably need some further debugging, happy to get some direction

**Comment by ryanmcnamara** [comment]
Consistent repro: 
Create a statefulset that creates a controllerrevision whose hash is between max int32 and max uint32 (this shouldn't be that hard to do, possibly a 50/50 chance of this). Manually create a controllerrevision identical to the first (same revision), incrementing both the name and hash by one. See that the statefulset controller will continually switch which controller revision should be the target of the statefulset.

**Comment by ryanmcnamara** [comment]
Due to the issue fixed here: https://github.com/kubernetes/kubernetes/pull/63282, under some circumstances controllerrevisions whose revision is the same were being considered equal. This ends up causing this bug to manifest as follows:

* ListRevisions finds many controllerrevisions with the same revision (unclear how this state happens, but it can happen)
* The sort here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L191 randomly sorts them
* Due to the linked bug https://github.com/kubernetes/kubernetes/pull/63282, FindEqualRevisions https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L207 incorrectly finds that all these controller revisions are equal to the proposed udpate.
* The updateRevision selects the last revision found here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L212

Therefore, updateRevision, is *randomly selected* and causes the bug. This fixes the immediate issue, but the sort should probably be made stable (i.e not just look at the revision number, perhaps just consider the hash for tie breakers)

**Comment by ryanmcnamara** [comment]
As an update, fixing the equality check will not be sufficient because it is possible for multiple controller revisions to be created that are *actually equal*, including the same hash, that have the same revision number.

I believe the fix will need to be 
1. Prevent equal controllerrevisions with the same revision number from being created
2. Stably sort the controllerrevisions so that the controllerrevision that is the target of the statefulset is stable

**Comment by wangxiaoq** [comment]
ping @ryanmcnamara

I use the K8S which version is 1.11.4 and encounter the same problem.  I want to reproduce the problem and find your way:

>Manually create a controllerrevision identical to the first (same revision), incrementing both the name and hash by one. 

Could you tell me how to mannually create a same controllerrevision  identical to the first? Thanks in anvance.
