### ISSUE TITLE
What's the best way to remove admission-control flag on v1.7.9?

### ISSUE THREAD

**Issue by bailantaotao** [kubernetes/kubernetes#61997]
**Is this a BUG REPORT or FEATURE REQUEST?**:
NO

**What happened**:
I have deployed more resources on my kubernetes cluster. But i cannot declare SecurityContext on my pod. Because i added the flag `SecurityContextDeny` on admission-control when deploy kubernetes.

I trying to remove them by following step:

1. ssh enter to master node.
2. vim /etc/kubernetes/manifests/kube-apiserver.yaml.
3. remove the SecurityContextDeny flag on `admission-control`
4. `kubectl get pod` is not working, it display timeout error.
5. `docker ps`, kube controller and scheduler is restarting, but kubelet is do nothing, api server is dead.
6. sudo system restart kubelet
7. wait a moment
8. Everything back

Is that a best way to remove the configuration?
I think that is too crazy.
Expected behavior is api-server reload configuration, instead of kube-apiserver dead, or restart kubelet, right?

I have tried other methods, like `kubelet edit pod kube-apiserver`,
But it always return `error: there was a problem with the editor "vi"`

The kubernetes official document doesn't show how to turn off, only turn on... 
https://v1-7.docs.kubernetes.io/docs/admin/admission-controllers/#how-do-i-turn-on-an-admission-control-plug-in

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:06Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
Azure cloud provider
```
- Kernel (e.g. `uname -a`): 
```
Darwin Edwinde-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
```

**Comment by hzxuzhonghu** [comment]
I think there is no way except kube-apiserver restart. But no need to restart kubelet, move the kube-apiserver.yaml out and back.

**Comment by lavalamp** [comment]
I think at step 4 you should have waited for kubelet to restart apiserver. You can hasten this by `kill`ing it.
