### ISSUE TITLE
Enable customize horizontal-pod-autoscaler-tolerance

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#62013]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Controller manager support autoscaling based on customer metrics now, and the controller manger has a parameter named as `--horizontal-pod-autoscaler-tolerance` which is used to define the minimum change in the desired-to-actual metrics ratio for the horizontal pod autoscaler to consider scaling with a default value as 0.1.

The problem is that with customized metrics auto scaling, the end user want to make the value of `--horizontal-pod-autoscaler-tolerance` to be fine-grained, such as define it based on application level but not cluster level, this can give the customer more options for auto scaling with different applications.

/sig autoscaling
/area controller-manager

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by arjenvanderende** [comment]
/reopen

This feature makes sense for us. For one of our applications we have a large number of pods running (> 500) that accept websocket connections. We scale based on the total number of websocket connections. Because of the default threshold of 10%  the HPA refuses to add dozens of pods. For just this application we'd prefer to lower the threshold considerably.

**Comment by wuyafang** [comment]
This feature makes sense for us. And maybe we need different tolerance for different metrics.

**Comment by kong62** [comment]
horizontal-pod-autoscaler-tolerance=0.1, [-10% + 10% ] , means 20% deviation, this deviation attitude is big
```
[#] kubectl  get hpa -n sentry 
sentry-worker                 Deployment/sentry-worker                 40%/50%   8         40        16         91d
```
