### ISSUE TITLE
Windows 1709 kube-proxy kernelspace 

### ISSUE THREAD

**Issue by chocolat2000** [kubernetes/kubernetes#62029]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Cannot use the kernelspace mode of kube-proxy 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
start kube-proxy
c:\k\kube-proxy.exe --v=4 --proxy-mode=kernelspace --hostname-override=$(hostname) --kubeconfig=c:\k\config

**Anything else we need to know?**:
Flannel is used for pods networking
**Environment**:
- Kubernetes version (use `kubectl version`):
{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
- Cloud provider or hardware configuration: on premise
- OS (e.g. from /etc/os-release): windows servercore 1709
- Kernel (e.g. `uname -a`): 10.0.16299.125
- Install tools: [Microsoft SDN](https://github.com/Microsoft/SDN/tree/master/Kubernetes/flannel/l2bridge)
- Others:
Each service creation logs this : 
`E0402 14:16:04.344271    5968 proxier.go:997] Remote endpoint creation failed: HNS failed with error : The switch-port was not found.`
`I0402 14:16:04.345266    5968 proxier.go:1010] Associated endpoints [([]hcsshim.HNSEndpoint) <nil>
] for service [kube-system/heapster:]`

**Comment by chocolat2000** [comment]
@kubernetes/sig-windows-bugs

**Comment by michmike** [comment]
@madhanrm can you please take a look?

**Comment by chocolat2000** [comment]
Probably unrelated, in userspace mode services are not accessibles from within pods.
No problem from host.

Not sure though which interface services ip should be bound to.
I've  tried:
$env:INTERFACE_TO_ADD_SERVICE_IP="vEthernet (Ethernet0)"
and
$env:INTERFACE_TO_ADD_SERVICE_IP="vEthernet (cbr0_ep)"

**Comment by chocolat2000** [comment]
Hi.

Upgraded to Windows insider Build 17650 and it works fine now.

**Comment by chocolat2000** [comment]
Works fine on windows semi-annual update 1803 too.

So I guest we can close this issue.

**Comment by feiskyer** [comment]
Let's close the issue since it has been resolved.

/close
