### ISSUE TITLE
The cloud provider for azure does not work

### ISSUE THREAD

**Issue by DmitriyProkhorov** [kubernetes/kubernetes#62022]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The cloud provider for azure does not work. Kube-apiserver does not start.
The error repeated from docker logs on api-server container:

E0402 09:37:33.504889 1 azure_backoff.go:141] backoff: failure, will retry,err=azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxx-xxxx-xxx-xxxx-xxxxx/resourceGroups/RG-k8s-lab/providers/Microsoft.Compute/virtualMachines/k8s-master1-lab?%24expand=instanceView&api-version=2017-03-30: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/xxx-xxxx-xxx-xxx-xxxxxxx/oauth2/token?api-version=1.0: x509: failed to load system roots and no roots provided'
I0402 09:37:33.504899 1 azure_instances.go:35] NodeAddresses(k8s-master1-lab) abort backoff
error setting the external host value: failed to get external host address from "azure" cloud provider: timed out waiting for the condition

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I will install the cluster using KET Tools. There also started a detailed ticket, but I think the problem is in Azure itself or in the code kubernetes
https://github.com/apprenda/kismatic/issues/1183

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CentOS 7.3
- Kernel (e.g. `uname -a`):
- Install tools: KET https://github.com/apprenda/kismatic
- Others:

**Comment by dims** [comment]
@DmitriyProkhorov - see a couple of work arounds in https://github.com/kubernetes/cloud-provider-openstack/issues/74

**Comment by DmitriyProkhorov** [comment]
Thank you! On Ubuntu Server it all worked. But for some reason the way to clean the / etc / ssl folder did not help

**Comment by feiskyer** [comment]
@DmitriyProkhorov Same with https://github.com/apprenda/kismatic/issues/1200. I'm not familiar with KET tools. Could you share the manifests for apiserver pod?
