### ISSUE TITLE
hpa  cannot get metrics

### ISSUE THREAD

**Issue by gaogaoSpark** [kubernetes/kubernetes#62053]
> Warning  FailedGetResourceMetric       2m (x38 over 42m)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: failed to get pod resource metrics: an error on the server ("Error: 'dial tcp 172.17.59.2:8082: getsockopt: no route to host'\nTrying to reach: 'http://172.17.59.2:8082/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=app%3Dhpa%2Cname%3Dhpa-test-app-deploy%2Cversion%3Dv0.0.1'") has prevented the request from succeeding (get services http:heapster:)

hpa  unable to get metrics for resource cpu

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6
- Cloud provider or hardware configuration: vm
- OS (e.g. from /etc/os-release):centos7
- Kernel (e.g. `uname -a`):3.10.0-229.el7.x86_64
- Install tools: 
- Others:

**Comment by gaogaoSpark** [comment]
sig/autoscaling

**Comment by lfaoro** [comment]
What's the update on this issue? I'm experiencing something similar.

![image](https://user-images.githubusercontent.com/3834345/38416385-d59f0622-3994-11e8-85b3-69bcea74e5eb.png)

heapster log: 
```
E0406 09:46:12.477143       1 manager.go:101] Error in scraping containers from kubelet_summary:10.88.0.10:10255: Get http://10.88.0.10:10255/stats/summary/: dial tcp 10.88.0.10:10255: getsockopt: connection timed out
```

GCP Nodes
```
                    "OSImage": "Container-Optimized OS from Google",
                    "ContainerRuntimeVersion": "docker://17.3.2",
                    "KubeletVersion": "v1.9.6-gke.0",
                    "KubeProxyVersion": "v1.9.6-gke.0",
                    "OperatingSystem": "linux",
                    "Architecture": "amd64"
```

Maybe the heapster is lacking some privileges?

**Comment by ChetanaCU** [comment]
Hello @gaogaoSpark,
Please make sure the metrics server is up and valid CPU resource parameters are specified in the yaml file.

Hello @lfaoro,
Could you please share the steps to replicate the below error or could you please explain the scenario when you are facing this issue -
Error in scraping containers from kubelet
