### ISSUE TITLE
Priority Scheduling w/o Preemption

### ISSUE THREAD

**Issue by salilgupta1** [kubernetes/kubernetes#62068]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
We are looking to use our Kubernetes cluster as a workload processing system for our clients. We want to use the priority functionality in 1.9. However, we have a hard requirement where we cannot preempt a clients job for another job. Is there any way to disable preemption but maintain priority? We only need priority to order the scheduling of workloads going onto the cluster. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@jennac

**Comment by k82cn** [comment]
for now, priority & preemption are enabled/disabled together; but that's a reasonable request to sort Pod by priority only.

/cc @bsalamat

**Comment by k82cn** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by salilgupta1** [comment]
@resouer At least from the documentation it seems like PodPriority is tightly bound to preemption
> Pods in Kubernetes 1.8 and later can have priority. Priority indicates the importance of a Pod relative to other Pods. When a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible. In Kubernetes 1.9 and later, Priority also affects scheduling order of Pods and out-of-resource eviction ordering on the Node.

Our use case: Clients run a variety of jobs on our platform. We want to run these jobs on K8s. The issue is a client (let's say Client A) could flood the job queue with hundreds of jobs that take up all the available resources on our cluster thus blocking other clients from running jobs. If we could set a priority on the job such that Client A's jobs get de-prioritized in comparison to other client jobs we would have a way of protecting the queue from being flooded by a single client. We want to use K8s podPriority feature but we cannot preempt already running jobs.

**Comment by bsalamat** [comment]
> Our use case: Clients run a variety of jobs on our platform. We want to run these jobs on K8s. The issue is a client (let's say Client A) could flood the job queue with hundreds of jobs that take up all the available resources on our cluster thus blocking other clients from running jobs. If we could set a priority on the job such that Client A's jobs get de-prioritized in comparison to other client jobs we would have a way of protecting the queue from being flooded by a single client. We want to use K8s podPriority feature but we cannot preempt already running jobs.

As you have noticed, priority and preemption are enabled together. We can separate them, but first let me understand the problem better.
This is the scenario from your example: Client A runs hundreds of jobs and fills up all the available resources in the cluster and still has quite a few more jobs in the scheduling queue. Another client, Client B, with higher priority arrives and creates a few pods and get in front of the Client A's jobs in the scheduling queue. Client B's jobs won't schedule when preemption is disabled. So, what's the point of getting in front of Client A in the queue?

**Comment by aveshagarwal** [comment]
One use case of priority without preemption could be: 1) lets say a node (or a set of nodes or could be whole cluster) is drained and restarted after upgrade or node issues, and now just priority makes sure that higher priority pods in the scheduling get scheduled first.

**Comment by bsalamat** [comment]
> One use case of priority without preemption could be: 1) lets say a node (or a set of nodes or could be whole cluster) is drained and restarted after upgrade or node issues, and now just priority makes sure that higher priority pods in the scheduling queue get scheduled first.

Makes sense. I am fine with adding a separate feature gate for preemption.

**Comment by resouer** [comment]
Good to see the use case is clear, let me take care of this change if no one has picked it up.

/assign

**Comment by k82cn** [comment]
> Client B's jobs won't schedule when preemption is disabled. So, what's the point of getting in front of Client A in the queue?

IMO, it's a kind of run-to-complete pods, maybe @salilgupta1 can give more info :)

As comment above, that's reasonable request to me.

**Comment by salilgupta1** [comment]
> Another client, Client B, with higher priority arrives and creates a few pods and get in front of the Client A's jobs in the scheduling queue. Client B's jobs won't schedule when preemption is disabled. So, what's the point of getting in front of Client A in the queue?

Hopefully, a single Client isn't using all the resources at any given time, but yes it could happen. If that is the case, we definitely want the next available resources (when any of Client A's jobs finish) to go to someone else, which is why it seems advantageous to bump Client B further up in the queue. 

We're hoping to give users a fairer chance at future available resources.

And @k82cn these are not long-lived services.

**Comment by resouer** [comment]
@salilgupta1 FYI, now you can use a config of scheduler to say you want to disable preemption or not.

I will also update https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ in a following PR to reflect this change.

**Comment by byndcivilization** [comment]
Hi we're trying to enable this and running into issues with the componentconfig/v1alpha1 api endpoint in k8s 1.11? Is there a trick here?

**Comment by liquanstan** [comment]
@byndcivilization 
I also encountered the same problem in k8s 1.11.5. Did you solve it?
