### ISSUE TITLE
Kube-proxy cleanup not work if cluster have pod with hostport

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubernetes#62090]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
If you have a pod with hostport, then kubenet will create `KUBE-HOSTPORTS` iptables chain, if so, the iptables nat table will be like:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
KUBE-HOSTPORTS  all  --  0.0.0.0/0            0.0.0.0/0            /* kube hostport portals */ ADDRTYPE match dst-type LOCAL

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
KUBE-HOSTPORTS  all  --  0.0.0.0/0            0.0.0.0/0            /* kube hostport portals */ ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  127.0.0.0/8          0.0.0.0/0            /* SNAT for localhost access to hostports */    

Chain KUBE-HOSTPORTS (2 references)
target     prot opt source               destination         
KUBE-HP-2MUE7BXTV56FM567  tcp  --  0.0.0.0/0            0.0.0.0/0            /* whoami-fhdmg_default hostport 3000 */ tcp dpt:3000

Chain KUBE-HP-2MUE7BXTV56FM567 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.64.2.24           0.0.0.0/0            /* whoami-fhdmg_default hostport 3000 */
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            /* whoami-fhdmg_default hostport 3000 */ tcp to:10.64.2.24:3000
```

The hostport related chains and rules should be maintained by kubenet, but they are using `KUBE-MARK-MASQ` rule, which created and maintained by kube-proxy. 

And if kube-proxy need cleanup iptables rules, will have this error, and left all iptables rules:
```
I0403 11:26:57.863345       1 server_others.go:209] Tearing down inactive rules.
E0403 11:26:57.898779       1 proxier.go:423] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 34 failed
)
```

**What you expected to happen**:
If we decide `KUBE-MARK-MASQ` is a public chain which all k8s packages can use, then kube-proxy should not clean this this chain.

If we decide `KUBE-MARK-MASQ` is a private chain, then kubenet need  to have another chain do this work.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pod with container port like:
```
      containers:
      - name: xxxxx
        image: xxxx
        ports:
        - containerPort: 3000
          hostPort: 3000
```
2. Wait `KUBE-HOSTPORTS` iptables chain created.
3. Use `kube-proxy --cleanup`, return err. then check iptables rules.

**Comment by Lion-Wei** [comment]
I thinks this issue is because the iptables chain `KUBE-MARK-MASQ` is used by both kube-proxy and kubenet. We need to decide whether kubenet can use this chain.
@m1093782566 @rramkumar1 @thockin PTAL

**Comment by m1093782566** [comment]
@Lion-Wei I believe kube-proxy --cleanup should only clean up rules created by it self.

CNI host-port plugin use an `externalSetMarkChain`, xref: https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap

**Comment by Lion-Wei** [comment]
Unfortunally, it fail to clean up all rules. : (
I think it's because kubenet host-port workaround is using `KUBE-MARK-MASQ`, then kube-proxy try to restore this chain failed.
