### ISSUE TITLE
kube-apiserver swagger ui no response

### ISSUE THREAD

**Issue by inetkiller** [kubernetes/kubernetes#62098]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
kube-apiserver enable swagger ui , local brower can visit swagger ui ,but the swagger ui page will sticking and no response.

**What you expected to happen**:
Show detail info when i click an api interface.

**How to reproduce it (as minimally and precisely as possible)**:
enable swagger ui ,and visit it .

**Anything else we need to know?**:
configed cluster use kubeadm 1.9.5.
visit swagger ui use chrome.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: baremeta
- OS (e.g. from /etc/os-release):centos7
- Kernel (e.g. `uname -a`):3.10.0-693
- Install tools:
- Others:

**Comment by wenjiaswe** [comment]
cc @mbohlool

**Comment by mbohlool** [comment]
swagger 1.2 and all related features (e.g. swagger-ui) is deprecated and will be removed in 1.11. Do you have strong reason to use swagger-ui? I suggest you download Openapi spec (from $API_SERVER/openapi/v2) and use an official swagger-ui to parse it.

**Comment by inetkiller** [comment]
@mbohlool get it. thx
