### ISSUE TITLE
Taints not working as expected

### ISSUE THREAD

**Issue by Sarga** [kubernetes/kubernetes#62100]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

/kind bug

**What happened**:
I need several dedicated nodes to run the cronjobs on them
I've added taint to the worker node
```
kubectl taint nodes 10.40.161.83 dedicated=cron:NoSchedule
```
Also I've checked that the taint exists
```
kubectl describe nodes 10.40.161.83 | grep Taints
Taints:             dedicated=cron:NoSchedule
```
But when I scale pods, they run on this node with taint
Where I'am wrong?

**What you expected to happen**:
I expect that the pods will not be run on the node with taint, if they don't have tolerations

**How to reproduce it (as minimally and precisely as possible)**:
kubectl taint nodes node_name dedicated=cron:NoSchedule
And try to scale up your deployment

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.10
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release): Debian 8 (jessie)
- Kernel (e.g. `uname -a`): Debian 4.9.30-2+deb9u2~bpo8+1 (2017-06-27) x86_64 GNU/Linux
- Install tools: -
- Others: -

**Comment by redbaron** [comment]
Do you run scheduler with custom policy config?

**Comment by Sarga** [comment]
I've run it with config

`{
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
        {"name" : "PodFitsPorts"},
        {"name" : "PodFitsResources"},
        {"name" : "NoDiskConflict"},
        {"name" : "MatchNodeSelector"},
        {"name" : "HostName"}
    ],
    "priorities" : [
        {"name" : "LeastRequestedPriority", "weight" : 1},
        {"name" : "BalancedResourceAllocation", "weight" : 5},
        {"name" : "SelectorSpreadPriority", "weight" : 10},
        {"name" : "EqualPriority", "weight" : 1}
    ]
}`

**Comment by Sarga** [comment]
I've found option 
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L70

with such config it is working well
```json
{
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
        {"name" : "PodFitsPorts"},
        {"name" : "PodFitsResources"},
        {"name" : "NoDiskConflict"},
        {"name" : "PodToleratesNodeTaints"},
        {"name" : "MatchNodeSelector"},
        {"name" : "HostName"}
    ],
    "priorities" : [
        {"name" : "LeastRequestedPriority", "weight" : 1},
        {"name" : "BalancedResourceAllocation", "weight" : 5},
        {"name" : "SelectorSpreadPriority", "weight" : 10},
        {"name" : "TaintTolerationPriority", "weight" : 1},
        {"name" : "EqualPriority", "weight" : 1}
    ]
}
```

Thanks a million @redbaron
