### ISSUE TITLE
Workflow of Same ebs volume attached to multiple PV

### ISSUE THREAD

**Issue by HasnainRaza14** [kubernetes/kubernetes#62107]
Hi everyone, this is just for the sake of knowledge. If anyone knows please guide in this regard.

I am trying to create a PV like: 

_kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws-volume-id
    fsType: ext4_

**it gets created and we can use this to PV for claiming and there is no issue. If I create more PV's with different names but same volume ID in the same node, how it's managed with Kubernetes. If original volume was of size 50 GB, and we make 5 PV's of 10gb Capacity, does this mean that kubernetes will assign distinct memory block of 10Gi to each to PV and we won't have shared memory between PV's?**@ncdc

**Comment by gnufied** [comment]
The disk space available to all PVs that use same EBS volume-id will be same. Kubernetes does not create device paritions or anything of that sort out of box for sharing large disks between n number of PVs.

Closing this. If you need further help, please open something on Stackoverflow or drop by on our slack channel. 

/close
