### ISSUE TITLE
Feature: exitContainers analogous to initContainers

### ISSUE THREAD

**Issue by lukasheinrich** [kubernetes/kubernetes#62117]
> /kind feature

Kubernetes provides the useful feature of initContainers, that allow us to run containers other than the main workload to e.g. setup data, configuration etc, using tools that might not be available, or are unrelated to the main application code running as the main workload.

It would be very useful for Kubernetes to add an analogous feature at the other end of the lifecycle, e.g. `exitContainers`.  The main use-case I see are workloads generated by the `Job` API objects. A typical setup might be

* initContainer: copy data from object storage into a local, fast I/O disk attached as a a dynamically provisioned volume
* main Container: a `FROM scratch` container consisting only of a binary that an operate on the local data via POSIX, without having to have support / or knowledge / credentials to the object store from which the data originated
* exitContainer: a container that takes output files written to the local disk by the main container and uploads it back to object storage

This will allow us to separate concerns between teams that are responsible for data management and teams responsible for developing the main workloads running on local data. My personal use-case is running a batch-job like queue for scientific workloads at CERN, in which the data management is handled centrally, while the main workloads for data analysis are developed by the scientists.

**Comment by k82cn** [comment]
Does this proposal (https://github.com/kubernetes/community/pull/483) meet your requirement? I think the major concern is the error handling of 'exitContainers'.

**Comment by lukasheinrich** [comment]
Thanks @k82cn, that looks like exactly the feature I am looking for -- so I think this can be marked as a duplicate and closed.
