### ISSUE TITLE
Mounting pvc takes a really long time

### ISSUE THREAD

**Issue by chmielas** [kubernetes/kubernetes#62119]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
Mounting pvc takes a really long time

**What you expected to happen**:
Mounting pvc should works faster

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with attached pvc (AWS EBS based )

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
4"}

- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
 CoreOS 
- Kernel (e.g. `uname -a`):
 4.14.19-coreos
- Install tools:
- Others:

/sig storage
Mounting pvc (AWS EBS)  takes a really long time. I notice that mounting pvc can take around 15 seconds (In a example bellow 17 sec). Is a way to speed up mounting ?

```
Events:
  Type    Reason                 Age   From                                                     Message
  ----    ------                 ----  ----                                                     -------
  Normal  Scheduled              39s   default-scheduler                                        Successfully assigned k8s-e2e-backend-sdk4r-pspth to node
  Normal  SuccessfulMountVolume  39s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "workspace-volume"
  Normal  SuccessfulMountVolume  39s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "volume-1"
  Normal  SuccessfulMountVolume  39s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "volume-0"
  Normal  SuccessfulMountVolume  39s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "default-token-k4b26"
  Normal  SuccessfulMountVolume  22s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "pvc-7a70f893-37ea-11e8-944e-02f92438ff7e"
  Normal  Pulled                 21s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  Container image "docker.myregistry/jnlp-slave:1.0.2-47" already present on machine
  Normal  Created                21s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  Created container
  Normal  Started                21s   kubelet, ip-172-21-251-27.eu-central-1.compute.internal  Started container

```

**Comment by zetaab** [comment]
15 seconds is not a really long time. I would say long time is 10 minutes.

**Comment by gnufied** [comment]
Yeah mounting itself should be quick. You can actually get a breakdown of these timings via metrics.  Try "curl http://localhost:10255/metrics" and if you grep for "storage" then you will see metrics for mount/unmount operations.

Likely the delay for EBS is in - attach part. With 1.10 - we have tried to make it faster - https://github.com/kubernetes/kubernetes/pull/56974 perhaps worth giving 1.10 a try and see if you notice a difference.

I am closing this. Since I do not see a bug here that is worth fixing. 

/close

**Comment by chmielas** [comment]
@gnufied  What is expexted mount time after installation 1.10 ?

**Comment by zetaab** [comment]
@chmielas could you please open the PR it is there in first post.

Like release notes says
`AWS: Make attach/detach operations faster. from 10-12s to 2-6s`
