### ISSUE TITLE
Leader Election: ceding leadership, leading on renew callback

### ISSUE THREAD

**Issue by karlhungus** [kubernetes/kubernetes#62120]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature
/sig api-machinery

#### Abstract

 1. cede leader ship from [`LeaderElector`](https://github.com/kubernetes/kubernetes/blob/2bf111a619087d46c03018ae458f822f3fc13708/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go) without Panicing
 2. callback from [`LeaderElector>>renew()`](https://github.com/kubernetes/kubernetes/blob/2bf111a619087d46c03018ae458f822f3fc13708/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L190)

If these suggestions seem reasonable, I'd be happy to contribute them.

#### Description

1. ceding leadership

We currently use this tool in a sidecar container to elect a leader for our high availability prometheus. We've had a few cases where the container we care about doesn't start, but the pod still has leadership, currently we handle this by panic-ing in the sidecar. It'd be nice to cede leadership in this case without panic. Maybe something like: 

```go
// StopLeading cedes leadership.
func (le *LeaderElector) StopLeading() bool {
  close(le.stopCh)
}
```

One negative of this approach would be that the elector would have to retain the stopChannel.

2. leading on renew callback

Currently we follow a pattern of [`OnStartedLeading `](https://github.com/kubernetes/kubernetes/blob/2bf111a619087d46c03018ae458f822f3fc13708/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L112):

```go
func lead(stop <-chan struct{}) {
	for {
		select {
		case <-stop:
			stopLeading()
		case <-time.After(e.opts.interval):
			if err := acquire(); err != nil {
				stopLeading()
				panic(err)
			}
		}
	}
}
```

This seems a tad wasteful when `renew` already provides this interval with jitter etc. If renew always called back this extra go func's would not be necessary i.e.: in [`LeaderCallbacks`](https://github.com/kubernetes/kubernetes/blob/2bf111a619087d46c03018ae458f822f3fc13708/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L110:6)

```go
type LeaderCallbacks struct {
       ...
       // OnLeaderRenew is called for every attempt at renewal at interval RetryPeriod
       OnLeaderRenew func()
}
```

**Comment by wenjiaswe** [comment]
cc @mikedanese

**Comment by karlhungus** [comment]
Seems like this is at least partially fixed by: https://github.com/kubernetes/kubernetes/pull/57932

**Comment by karlhungus** [comment]
Going to close this as fixed by cancellable leader election
