### ISSUE TITLE
[Flaky test] [pr:pull-kubernetes-integration] test-cmd run_deployment_tests flaked 33 times in the past week

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62128]
### Failures in TestGrid: 
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=%5EOverall%24%7Ctest%5C-cmd%5C%20run%5C_deployment%5C_tests

### Gubernator Logs:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60201/pull-kubernetes-integration/5263
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60201/pull-kubernetes-integration/5268#test-cmd-run_deployment_tests

@nikhiljindal - When investigating the history of the code in GH, I found the failing lines in the script (/go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:5086) were last modified as part of you [PR](https://github.com/kubernetes/kubernetes/commit/5424d50c03f293ef564fff23965c19bb659b0db2). 
* Can you please look into this issue and/or triage it accordingly. 
* Also please assign the appropriate sig to this issue.

/priority failing-test
/priority important-soon
/kind flake
/assign @nikhiljindal 

@kubernetes/sig-cli-test-failures

**Comment by nikhiljindal** [comment]
umm that PR was more than a year ago. Am not aware of recent kubectl changes.

The relevant error seems to be:
```
I0404 15:37:35.681] service "redis-master" selector updated
I0404 15:37:35.787] Waiting for Get services redis-master {{range.spec.selector}}{{.}}:{{end}} : expected: padawan:, got: redis:padawan:backend:
I0404 15:37:35.788] 
I0404 15:37:35.792] test-cmd-util.sh:2566: FAIL!
```

Anyone from @kubernetes/sig-cli-bugs has more idea?

**Comment by soltysh** [comment]
It doesn't look like the test from the title is failing that many times. I've modified the regexp and looking at https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=run_deployment_tests the only time `run_deployment_tests` fails is at a single PR (https://github.com/kubernetes/kubernetes/pull/60201). I see `k8s.io/kubernetes/test/integration/auth.TestAuthModeAlwaysAllow` and `k8s.io/kubernetes/test/integration/auth.TestAliceNotForbiddenOrUnauthorized` failing very frequently looking at https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration but I don't see issues opened for those
