### ISSUE TITLE
Support EnvFromSource FieldRef

### ISSUE THREAD

**Issue by Arslanbekov** [kubernetes/kubernetes#62123]
/kind bug

**What happened**:
Object `EnvFromSource` does not contain fields for extraction `FieldFrom`. Therefore, it is not possible to extract and display data on Dashboard: 

https://github.com/kubernetes/dashboard/blob/9c9b2a3aa18dcc029f9899d08ab3bfd1f995d101/src/app/frontend/pod/detail/containerinfo_component.js#L58

EnvVarSource (include FieldRef).
https://github.com/kubernetes/kubernetes/blob/817869e78af9d3250a36fce845336535dd29d0e4/staging/src/k8s.io/api/core/v1/types.go#L1876

EnvFromSource (not include FieldRef).
https://github.com/kubernetes/kubernetes/blob/817869e78af9d3250a36fce845336535dd29d0e4/staging/src/k8s.io/api/core/v1/types.go#L1937

Reference issue from Kubernetes dashboard: https://github.com/kubernetes/dashboard/issues/2936

**What you expected to happen**:
EnvFromSource include FieldRef

**Comment by liggitt** [comment]
EnvFromSource directs the kubelet to extract all values from the referenced configmap or secret and create environment variables from them. This is done at container run time, not reflected in the API.

EnvVarSource lets you specify a particular key in a secret or configmap to inject.

/close
