### ISSUE TITLE
Add webhook e2e test ensuring that Mutating Webhooks are not called for Webhook Configuration object requests.

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#62130]
We have an e2e test for "AdmissionWebhooks Should not be able to prevent deleting validating-webhook-configurations or mutating-webhook-configurations" which verifies that ValidatingWebhooks are not called on validating-webhook-configurations and mutating-webhook-configurations, but we do not have such a test for MutatingWebhooks.

In https://github.com/kubernetes/kubernetes/pull/58381#discussion_r179234928 we just happened to catch the regression because it was in the validating case, but if a change were to be made breaking the mutating case we wouldn't catch it at the moment.

This issue is to remind myself to add that test case.

/assign
/sig api-machinery

**Comment by wenjiaswe** [comment]
cc @cheftako

**Comment by jennybuckley** [comment]
/remove-lifecycle stale
This still needs to be tested, it should stay open until #62143 merges.
