### ISSUE TITLE
DNS stops working during controller election

### ISSUE THREAD

**Issue by spdeshpande** [kubernetes/kubernetes#62140]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
We have a 3 node k8s 1.7.3 cluster (all masters) with control plane (apiserver, controller, scheduler, etcd) and dns server, all scaled out to 3. What we have observed is that when one of the nodes that had the kube-controller-manager running as master goes down, the dns stops servicing requests for a while, probably till the time the new controller leader is elected. This sends some of our HA services like postgres (statefulset) for a toss as it cannot connect to any peers using the dns names.  

**What you expected to happen**:
DNS should not get interrupted because of one node going down out of 3. 

**How to reproduce it (as minimally and precisely as possible)**:
A 3 node k8s 1.7.3 cluster with control plane and dns server scaled out to 3. Bring the node with leader controller down and simultaneously check if DNS works from the other 2 nodes. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v.1.7.3
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`): Linux Ubuntu x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm 1.7.3
- Others:

**Comment by spdeshpande** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by alexa-infra** [comment]
I have the same issue with `v1.9.2` (installed via `kubeadm`). Also it is easy to reproduce with a small cluster (1 master, 3 workers): just shut down master node and DNS stops working *completely* inside all worker's pods.

**Comment by spdeshpande** [comment]
I have multi masters as all 3 nodes are masters. So there should ideally be high scalability for DNS and ETCD to get the names resolved. But still for some reason it takes quite a while for DNS to stabilize.
