### ISSUE TITLE
Global inter-namespace cluster secrets - Secrets that work across namespaces

### ISSUE THREAD

**Issue by feluxe** [kubernetes/kubernetes#62153]
/kind feature
/sig api-machinery
/sig architecture
/sig auth

I'm currently setting up a docker-image registry for multiple clusters with multiple namespaces. In order to make this work for every namespace in every cluster, I have to create a secret for each single namespace.

I have no idea about the implications, but from a user's perspective it would be handy to have something like *global* secrets available that work across namespaces.

I'm sorry if this was already asked, I couldn't find anything related.

**Comment by prateek2408** [comment]
Is there any progress on this ?

**Comment by rgargadobe** [comment]
This is a genuine need, why is it not worked on?

**Comment by ysaakpr** [comment]
Yeah, this is a genuine need, We have many situations where we have to copy secrets between namespaces and which adds extra management care. Which is very crucial for secrets availability across namespaces. Our major blocker is on syncing cert-manager certificates and across namespaces. Its always beneficial to manage "ClusterSecrets" and manage them at Cluster level, though i am not very sure about the impact and possibilities.

**Comment by ysaakpr** [comment]
https://github.com/kubernetes/kubernetes/issues/70147

**Comment by TomaszKlosinski** [comment]
Any new on this?

**Comment by ryancastle** [comment]
This would be very good, but hard to imagine how it would work.

**Comment by TomaszKlosinski** [comment]
> hard to imagine how it would work

Why? There are many cluster-wide resources in K8s.

**Comment by zakkg3** [comment]
Here you have the solution: An operator that introduces ClusterSecret object: 
> Global inter-namespace cluster secrets - Secrets that work across namespaces

https://github.com/zakkg3/ClusterSecret

PR /  bugs reports  / feature request are welcome.
