### ISSUE TITLE
Empty PodCidr in kubelet logs when pod CIDR allocation is not used

### ISSUE THREAD

**Issue by codepainters** [kubernetes/kubernetes#62164]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In my test setup I allocate POD CIDRs manually, `cbr0` bridge is configured before `kubelet` starts. 
Important settings:
- on example node: `kubelet --pod-cidr=10.10.2.129/25 --network-plugin=kubenet`
- on master: `kube-controller-manager --allocate-node-cidrs=false` 

Then I see confusing entries in `kubelet` logs (`grep -i cidr`):
```
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.123040   15115 kuberuntime_manager.go:917] updating runtime config through cri with podcidr 10.10.2.129/25
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.123172   15115 docker_service.go:340] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:10.10.2.129/25,},}
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.123380   15115 kubelet_network.go:196] Setting Pod CIDR:  -> 10.10.2.129/25
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.247311   15115 kuberuntime_manager.go:917] updating runtime config through cri with podcidr
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.247492   15115 docker_service.go:340] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:,},}
Apr 05 12:23:01 node-2 kubelet[15115]: I0405 12:23:01.247571   15115 kubelet_network.go:196] Setting Pod CIDR: 10.10.2.129/25 ->
```
Fortunately everything keeps working, thanks to this condition:
https://github.com/kubernetes/kubernetes/blob/915798d229b7be076d8e53d6aa1573adabd470d2/pkg/kubelet/dockershim/docker_service.go#L341 , i.e. it is not propagated to CNI plugin. 

It appears that this very line tries to set the CIDR to whatever the master returns during node status update: https://github.com/kubernetes/kubernetes/blob/915798d229b7be076d8e53d6aa1573adabd470d2/pkg/kubelet/kubelet_node_status.go#L405

**What you expected to happen**:
- `kubelet`/`kubenet` use the pod CIDR given at command line and never mess with it

Actually I'm a bit confused if manual per-node pod CIDR assignment is supported at all, and if I'm doing it correctly. I'm aware it's unusual thing to do in production environment, yet for testing it seems perfectly legitimate.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): `Linux master 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm 1.10.0`

**Comment by feiskyer** [comment]
Kubelet need to make a check of CIDR before `kl.updatePodCIDR()`
