### ISSUE TITLE
Serial / Flaky / Slow tests should not be marked [Conformance]

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#62161]
We have a new ci/pull job that runs conformance tests with a single node started using hack/local-up-cluster.sh.  Comparing runs of `pull-kubernetes-e2e-gce` and `ci-kubernetes-local-e2e` there are a few tests that we do not run on the GCE job because they are marked as `[Serial]` / `[Flaky]` / `[Slow]`.  

Questions:
- Are these tests actually needed? 
- Do we need a blocking pre-submit job that runs the full suite? (given that it takes time > 1 hour to run)

```
[dims@dims-mac 20:19] ~/Downloads ⟩ diff -Bbwu e2e-gce-2.txt e2e-local-2.txt
--- e2e-gce-2.txt	2018-04-04 20:19:18.000000000 -0400
+++ e2e-local-2.txt	2018-04-04 20:19:31.000000000 -0400
@@ -12,12 +11,14 @@
 [k8s.io] Probing container should *not* be restarted with a exec "cat /tmp/health" liveness probe [Conformance]
 [k8s.io] Probing container should be restarted with a /healthz http liveness probe [Conformance]
 [k8s.io] Probing container should be restarted with a exec "cat /tmp/health" liveness probe [Conformance]
+[k8s.io] Probing container should have monotonically increasing restart count [Slow] [Conformance]
 [k8s.io] Probing container with readiness probe should not be ready before initial delay and never restart [Conformance]
 [k8s.io] Probing container with readiness probe that fails should never be ready and never restart [Conformance]
 [k8s.io] Variable Expansion should allow composing env vars into new env vars [Conformance]
 [k8s.io] Variable Expansion should allow substituting values in a container's args [Conformance]
 [k8s.io] Variable Expansion should allow substituting values in a container's command [Conformance]
 [k8s.io] [sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]
+[k8s.io] [sig-node] Pods Extended [k8s.io] Delete Grace Period should be submitted and removed [Flaky] [Conformance]
 [k8s.io] [sig-node] Pods Extended [k8s.io] Pods Set QOS Class should be submitted and removed [Conformance]
 [k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance]
 [sig-api-machinery] ConfigMap should be consumable via environment variable [Conformance]
@@ -37,6 +38,10 @@
 [sig-api-machinery] Garbage collector should orphan pods created by rc if delete options say so [Conformance]
 [sig-api-machinery] Secrets should be consumable from pods in env vars [Conformance]
 [sig-api-machinery] Secrets should be consumable via the environment [Conformance]
+[sig-apps] Daemon set [Serial] should retry creating failed daemon pods [Conformance]
+[sig-apps] Daemon set [Serial] should run and stop complex daemon [Conformance]
+[sig-apps] Daemon set [Serial] should run and stop simple daemon [Conformance]
+[sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]
 [sig-apps] ReplicaSet should serve a basic image on each replica with a public image [Conformance]
 [sig-apps] ReplicationController should serve a basic image on each replica with a public image [Conformance]
 [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Burst scaling should run to completion even with unhealthy pods [Conformance]
@@ -81,6 +86,9 @@
 [sig-network] Services should provide secure master service [Conformance]
 [sig-network] Services should serve a basic endpoint from pods [Conformance]
 [sig-network] Services should serve multiport endpoints from pods [Conformance]
+[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]
+[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching [Conformance]
+[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]
 [sig-storage] ConfigMap optional updates should be reflected in volume [Conformance]
 [sig-storage] ConfigMap should be consumable from pods in volume [Conformance]
 [sig-storage] ConfigMap should be consumable from pods in volume as non-root [Conformance]
```

**Comment by bgrant0607** [comment]
Serial and slow is fine. Flaky tests shouldn't be part of conformance

**Comment by spiffxp** [comment]
/assign @mgdevstack 
Can you see if there are any existing `[Conformance]` tests marked as `[Slow]`, `[Serial]` or `[Flaky]`?

**Comment by spiffxp** [comment]
ok, nevermind, it was quicker than I thought to list these out... instead @mgdevstack I'm curious what the impact of these tests are... how slow are they really, and do they really need to be serial?

Using junit.xml from a recent run of ci-kubernetes-gce-conformance. It will list fully expanded test names for all e2e tests, skipped or not.  Then, I swear I tried to be nice and use `xpath string(//testcase/@name)` but my copy of xpath wasn't having it.  So grep/sed it is.
```
$ wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance/822/artifacts/junit_01.xml
$ for tag in Flaky Slow Serial; do \
  echo --$tag--; cat junit_01.xml | grep name= | sed -e 's/.* name="\([^"]*\)".*/\1/' | \
  grep '\[Conformance\]' | sort | grep "\[$tag\]"; done
--Flaky--
--Slow--
[k8s.io] Probing container should have monotonically increasing restart count [Slow][NodeConformance] [Conformance]
[sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]
--Serial--
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance]
[sig-api-machinery] Namespaces [Serial] should ensure that all services are removed when a namespace is deleted [Conformance]
[sig-apps] Daemon set [Serial] should retry creating failed daemon pods [Conformance]
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
[sig-apps] Daemon set [Serial] should run and stop complex daemon [Conformance]
[sig-apps] Daemon set [Serial] should run and stop simple daemon [Conformance]
[sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run  [Conformance]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching  [Conformance]
[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching  [Conformance]
[sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]
```

**Comment by janetkuo** [comment]
DaemonSet tests aren't too slow. They're tagged serial because they modify node labels which will disrupt other tests. However, probably not all DaemonSet tests need to modify node labels. We can revisit and remove `[Serial]` tags of some DaemonSet tests.

**Comment by mgdevstack** [comment]
>--Slow--
1. [k8s.io] Probing container should have monotonically increasing restart count [Slow][NodeConformance] [Conformance]
2. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]

These tests are taking ~3 min of time. Tests should be tagged [Slow] if they are taking more than 5min ([reference](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#kinds-of-tests)). So it make sense to remove [Slow] tag for these 2 tests._

>--Serial--

>1. [sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance]
>2. [sig-api-machinery] Namespaces [Serial] should ensure that all services are removed when a namespace is deleted [Conformance]

Based on [code comment](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/namespace.go#L238-L265), Namespaces based tests should run in [Serial] mode due to performance overhead on namespace deletion.

>3. sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run  [Conformance]
>4. [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if matching  [Conformance]
>5. [sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching  [Conformance]

Above tests can not be run in parallel due to resource constraint requirement like CPU, and runs in destructive mode too. [deletes other namespaces]

>6. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]

Above test needs to be [Serial] as inducing race condition with Configmap Volumes and Pod replica but it should not consider as [Slow] because average test execution time is ~3 min.

>7. [sig-apps] Daemon set [Serial] should run and stop simple daemon [Conformance]
>8. [sig-apps] Daemon set [Serial] should retry creating failed daemon pods [Conformance]
>9. [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
>10. [sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]

Above DaemonSet tests are not modifying node labels and seems good to remove [Serial] label for them.

>11. [sig-apps] Daemon set [Serial] should run and stop complex daemon [Conformance]
>12. [sig-apps] Daemon set [Serial] should run and stop complex daemon with node affinity

Above tests should remain tagged as [Serial] as changing node labels.

**Comment by mgdevstack** [comment]
Does the above comment make sense? If Yes, I can proceed to update appropriate labels on them.
**Highlight: (Expected changes might be)**
> --Slow tests--
- [Slow] tag would be removed for tests taking < 5min to finish. (below 3 tests to be changed)
i.e.
```
1. [k8s.io] Probing container should have monotonically increasing restart count [Slow][NodeConformance] [Conformance]
2. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]
6. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]
```

> --Serial tests--

[Serial] tag would be NOT be removed from tests which are dealing with node labels modification(destructive mode), race conditions, Performance overhead, resource constraint requirement. So 
- [Serial] tag would be removed for following 4 tests-
```
7. [sig-apps] Daemon set [Serial] should run and stop simple daemon [Conformance]
8. [sig-apps] Daemon set [Serial] should retry creating failed daemon pods [Conformance]
9. [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
10. [sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]
```

**Comment by youngqqcn** [comment]
0

At 2018-12-17 15:21:06, "Mayank Gaikwad" <notifications@github.com> wrote:


Does the above comment make sense? If Yes, I can proceed to update appropriate labels on them.
Highlight: (Expected changes might be)

--Slow tests--

[Slow] tag would be removed for tests taking < 5min to finish. (below 3 tests to be changed)
i.e.
1. [k8s.io] Probing container should have monotonically increasing restart count [Slow][NodeConformance] [Conformance]
2. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]
6. [sig-storage] EmptyDir wrapper volumes should not cause race condition when used for configmaps [Serial] [Slow] [Conformance]


--Serial tests--

[Serial] tag would be NOT be removed from tests which are dealing with node labels modification(destructive mode), race conditions, Performance overhead, resource constraint requirement. So

[Serial] tag would be removed for following 4 tests-
7. [sig-apps] Daemon set [Serial] should run and stop simple daemon [Conformance]
8. [sig-apps] Daemon set [Serial] should retry creating failed daemon pods [Conformance]
9. [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
10. [sig-apps] Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]

**Comment by dims** [comment]
thanks @mgdevstack 

/close

**Comment by spiffxp** [comment]
/reopen
We should be catching this in our conformance walker

**Comment by spiffxp** [comment]
By that I mean I'd like us to update https://github.com/kubernetes/kubernetes/blob/master/test/conformance/walk.go

I think it should reject tests that have `[Flaky]` or `[Slow]` or `[Feature:.*]` tags

I would code this in such a way as to anticipate more tags down the line, and warn/inform on tags that we may consider blocking on in the future but not today (eg: `[Privileged]`, `[Serial]`, etc)

**Comment by mkumatag** [comment]
I see the following test failed at least 2 times after adding into the conformance on ppc64le:

`[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]`

https://k8s-testgrid.appspot.com/sig-node-ppc64le#conformance

**Comment by BenTheElder** [comment]
That looks to be because the test is running on a single node but multiple
are required. It would have been skipped incorrectly previously.

**Comment by mkumatag** [comment]
> That looks to be because the test is running on a single node but multiple are required. It would have been skipped incorrectly previously.

@BenTheElder yes, that is right - we have a single node cluster for the conformance tests and was running fine till now. Is there a new requirement of having multiple nodes for the conformance tests? Is there a requirement doc where anyone can follow before running the conformance like the number of nodes, config etc..

**Comment by BenTheElder** [comment]
That is a really good question, I don't know. I do know that removing the
skip merged very recently. I believe you need two nodes on which workloads
can be scheduled and for now I'm supplying --num-nodes=2 to the tests. I
have suspicion this may be a problem for sonobuoy but I haven't had a
chance to test yet.

**Comment by BenTheElder** [comment]
er to be clear `--num-nodes` is a flag on the _tests_, not the cluster. I'm [not using a flag either](https://github.com/kubernetes-sigs/kind/commit/44c7055635eae4fd2e6733f9a44c334fd187ce8b), though it is also using kubeadm :-)

**Comment by smarterclayton** [comment]
I just realized why 

```
[sig-api-machinery] Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance]
```

is so flaky.  The node sees the pod and starts trying to get its service account secret, but then the pod and the namespace and the secret all get deleted, so it goes into a loop and just waits.... and waits...

Will follow up with an issue, that one needs to stay in conformance.

**Comment by timothysc** [comment]
We've decided to close this issue due to overlapping issues of Serial+Flaky+Slow and open specific issues on Serial & Slow, and Flaky should be fixed.
