### ISSUE TITLE
clients: port exec-based client auth provider to non go-lang clients

### ISSUE THREAD

**Issue by dbenhur** [kubernetes/kubernetes#62185]
With 1.10, this exec-based client auth credential provider alpha feature was introduced  [kubernetes/features#541](https://github.com/kubernetes/features/issues/541) for client-go.  Kubernetes project also [officially supports](https://kubernetes.io/docs/reference/client-libraries/) [Java](https://github.com/kubernetes-client/java/), [Python](https://github.com/kubernetes-client/python), [dotnet](https://github.com/kubernetes-client/csharp), and [Javascript](https://github.com/kubernetes-client/javascript) clients. Exec-based auth plugin should be supported by these client libraries in addition to client-go.

/kind feature
/sig api-machinery

**Comment by wenjiaswe** [comment]
cc @mbohlool

**Comment by mbohlool** [comment]
Thanks for reporting this, would you please file issues in the client repos. You can keep this issue as an umbrella issue if you like.

Also client libraries are under-staffed thus we welcome any contribution (small ones to owning client libraries).

**Comment by dbenhur** [comment]
@mbohlool Thanks for your suggestion; I've opened issues on each of the four official client repos.

Knowing the client work is understaffed is useful -- Amazon EKS team is working with [Heptio's AWS Authenticator](https://github.com/heptio/authenticator) using this new feature to enable more seamless AWS IAM auth experience with K8s, so we have an interest in seeing the client auth plugin feature generally available for the client libraries our customers may use to automate against EKS Kubernetes.  I'll see what we can do to marshal client contributions from our organization.

cc: @mattlandis @nckturner

**Comment by mbohlool** [comment]
That would be great. Thanks Devin.

**Comment by roycaihw** [comment]
The support has been added to Java, Python and Javascript clients. Support in other client libraries can be tracked in individual issues in corresponding repos. 

/close
