### ISSUE TITLE
Openstack cloud provider broken: `failed to get external ID from cloud provider: instance not found`

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#62223]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Since 1.10 the kubelet does not start anymore. Identical config as for 1.9.6.

Error is: `"23:23:44.967761    7342 kubelet.go:1349] Kubelet failed to get node info: failed to get external ID from cloud provider: instance not found`

**What you expected to happen**:

Kubelet starting

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This is caused by eaac0f5489de823f9e5805c53855560ae1a64156 which changed the Openstack cloud provider to not use the `name` metadata attribute but the `hostname` metadata attribute as the instance name to look for in the Openstack API.

However Openstack constructs the metadata.Hostname attribute by appending a dhcp domain to the name - This obviously means there will never be an instance with that name in the api, thus the Kubelet fails.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@alvaroaleman i've proposed a cherry pick, we have fixed this in master

https://github.com/kubernetes/kubernetes/pull/62224

**Comment by alvaroaleman** [comment]
@dims That only fixes the issue of the instance name does not contain dots

**Comment by dims** [comment]
and this one https://github.com/kubernetes/kubernetes/pull/61890

**Comment by alvaroaleman** [comment]
Will hopefully find a proper solution within https://github.com/kubernetes/kubernetes/issues/62295, closing this.
