### ISSUE TITLE
Node affinity not validated against label value format

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#62221]
/kind bug

Each term in NodeAffinity's NodeSelector is validated against the label name format, but not the label value format:
https://github.com/kubernetes/kubernetes/blob/8d28c5102be9159104839c2848b9889a7c8870b7/pkg/apis/core/validation/validation.go#L3003

whereas both label names and label values are validated for the `Label` and `spec.NodeSelector`, among other things, using this function:
https://github.com/kubernetes/kubernetes/blob/1e767ddf606f07c11dd66363eac299369b5ac3b6/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go#L65

/sig scheduling

/cc @bsalamat @msau42

**Comment by liggitt** [comment]
tightening validation isn't generally backwards compatible, especially since it can cause problems with already-persisted data.

if you use an invalid label value in this field, what are the consequences? if it simply means you don't get a match, that doesn't seem that bad.

**Comment by k82cn** [comment]
xref https://github.com/kubernetes/kubernetes/pull/46952
