### ISSUE TITLE
Volume with Block Mode should also be able to be mounted in pods

### ISSUE THREAD

**Issue by abel-von** [kubernetes/kubernetes#62238]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**: Huawei provides a new container runtime called "secure container" based on "runv", it supports passing a block device file name in `/dev` to it and mount it to a path in container, e.g. `docker run -v /dev/sda:/mnt`, it will mount the sda to the /mnt in the container. this is for the io performance and stability promotion, as runv is based on hypervisor, if we pass the block device directly to qemu, and qemu add this device to the VM with virtio-blk,  it will be much better passing the directory to qemu and qemu add it to VM through virtio-9p. 
In k8s 1.9, the volume can be "Block Mode", but as I know, this "Block Mode" volume can only be a volumeDevice in pod, kubernetes do not support defining a volumeMount with a volume of "Block Mode". If the block volume can not be defined in the volumeMount, then the secure container can not mount a block device, and that promotion can not take effect.

**What you expected to happen**: The "Block Mode" volume can be defined in volumeMounts in pod, and the block device file name can be passed to docker runtime in the "HostPath" of "Mount" of a container manifests. 

**How to reproduce it (as minimally and precisely as possible)**: Always

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`):  1.9.0
- Cloud provider or hardware configuration: Bare metal machines with k8s installed manually.
- OS (e.g. from /etc/os-release):  EulerOS 2.0 (SP2)
- Kernel (e.g. `uname -a`): 3.10.0-327.59.59.46.h27.x86_64
- Install tools: 
- Others:

**Comment by wenlxie** [comment]
Not sure I get what you mean.
But I suppose you wants the feature like:
1. Define a pod with Hostpath volume source
2. The hostpath volume path is a Block device
3. Define the mapped volume path at `VolumeMounts`

1. Hostpath not do mount/unount at the host
2. It pass the dev to container via `-v` option

I think Docker had support  "docker run -v /dev/sda:/mnt" already.

**Comment by abel-von** [comment]
@wenlxie  The volume source may be any volume that has has is block mode. docker do support `docker run --device=/dev/sda:/dev/xxx`, which pass the block device file directly to the container, but will not do the mount for the container.

**Comment by abel-von** [comment]
@wenlxie What I want is a volume which is a block mode can be defined in volumeMount in pod, our container runtime has implemented the logic that if we pass a block file to it in the Mount of a container, it will do the normal mount but not the bind mount.

**Comment by msau42** [comment]
Why can't the secure container runtime look at volumeDevices?

**Comment by abel-von** [comment]
@jsafrane  actually it's not the bind mount who degrades the performance, it's the "mount to host and pass through the directory to vm by virtio-9p" which degrades the performance. if we pass the the block device to the vm, the io in the vm can take effect directly to the block device, not the file system in the host.

**Comment by abel-von** [comment]
@msau42 Yes wen can define a volumeDevice in the pod, and this way still works fine. but then the user of our public cloud should do the mount by themselves in their startup command of container, this should be too  unconvenient for the user, because most of the time the volume should be mounted in the container.  we need to define the volume as block because we don't want to mount the volume on host, but we still wish to let the volume mounted directly to the file system in the container.

**Comment by msau42** [comment]
The global fs mount is used to serialize fs operations when multiple pods use the same volume, such as fs creation and resize. 

By bypassing this logic, the container runtime would have to reimplement this.

In addition, by adding a block mode field in volume mounts, that means the user has to understand which container runtime it's going to be running in, and you lose portability.

**Comment by abel-von** [comment]
@msau42 Thanks for reply, what we want to do is not add a block mode field in the volume mounts, we just want the volume with block mode  can be defined in the volumeMounts of pod. Please look at the example below:
First we can create a pv:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi 
```

then the pv can be defined in the volumeMounts in pods:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-db
spec:
    containers:
    - name: mysql
      image: mysql
      volumeMounts: 
      - name: my-db-data
        mountPath: /mnt
    volumes:
    - name: my-db-data
      persistentVolumeClaim:
	claimName: myclaim
```

We don't change the the API of the pv or pvc or pod. It's just the block mode volume didn't support volumeMounts before and with a little change in the kubelet, the k8s will  support to define a volumeMount by a block mode volume.

The change of code is mainly in here:
https://github.com/kubernetes/kubernetes/blob/dcc6d78ac02672f8afe14aee7679d0e5fc570980/pkg/kubelet/kubelet_pods.go#L147  


```
-               if !ok || vol.Mounter == nil {
-                       glog.Errorf("Mount cannot be satisfied for container %q, because the volume is missing or the volume mounter is nil: %+v", container.Name, mount)
+               if !ok {
+                       glog.Errorf("Mount cannot be satisfied for container %q, because the volume is missing", container.Name)
                        return nil, fmt.Errorf("cannot find volume %q to mount into container %q", mount.Name, container.Name)
                }

                relabelVolume := false
-               // If the volume supports SELinux and it has not been
-               // relabeled already and it is not a read-only volume,
-               // relabel it and mark it as labeled
-               if vol.Mounter.GetAttributes().Managed && vol.Mounter.GetAttributes().SupportsSELinux && !vol.SELinuxLabeled {
-                       vol.SELinuxLabeled = true
-                       relabelVolume = true
-               }
-               hostPath, err := volume.GetPath(vol.Mounter)
-               if err != nil {
-                       return nil, err
+               var hostPath string
+               if vol.Mounter != nil {
+                       // If the volume supports SELinux and it has not been
+                       // relabeled already and it is not a read-only volume,
+                       // relabel it and mark it as labeled
+                       if vol.Mounter.GetAttributes().Managed && vol.Mounter.GetAttributes().SupportsSELinux && !vol.SELinuxLabeled {
+                               vol.SELinuxLabeled = true
+                               relabelVolume = true
+                       }
+                       var err error
+                       hostPath, err = volume.GetPath(vol.Mounter)
+                       if err != nil {
+                               return nil, err
+                       }
+               } else if vol.BlockVolumeMapper != nil {
+                       dir, volNmae := vol.BlockVolumeMapper.GetPodDeviceMapPath()
+                       hostPath = dir + volNmae
+               } else {
+                       return nil, fmt.Errorf("volume is neither mounted nor mapped to host, can not mount into container %q", mount.Name)
                }
+
+
```

Yes, Can this volume be mounted to container depends on the container runtime, but I don't think the kubelet should make the restriction that block mode volume can not be mounted to container.

**Comment by msau42** [comment]
Sorry I was not clear.  My main concern is that this mode will be bypassing important filesystem operations that kubelet/volume plugins currently do, like filesystem create and resize.  Those would have to be reimplemented by the container runtime in order to support these Kubernetes features, which also means we would need to add in new extensions into the CRI to account for these scenarios.

**Comment by abel-von** [comment]
Yes，it's exactly what we want to do, to skip the filesystem operations of the volumes by kubelet, because in the runv, the pods are running in a light weight VM, if we mount the block device to host and pass the filesystem directory to the vm, the io performance will degrade a lot in the host VFS layer. 

our container runtime in Huawei has implemented this feature, that when we pass the mounts with host path points to a block device file, it will automatically mount this as a device but not bind mount. 

We do not force the container runtime to implement this, but if a user has a runtime with this function, k8s should support to use this feature of container runtime, I think.

and the CRI spec will not be changed, because the hostpath of mount is already defined and we just extend the meaning of it(not a dir on host anymore, but can be a block device).

```
// Mount specifies a host volume to mount into a container.
type Mount struct {
	// Path of the mount within the container.
	ContainerPath string `protobuf:"bytes,1,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	// Path of the mount on the host.
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// If set, the mount is read-only.
	Readonly bool `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	// If set, the mount needs SELinux relabeling.
	SelinuxRelabel bool `protobuf:"varint,4,opt,name=selinux_relabel,json=selinuxRelabel,proto3" json:"selinux_relabel,omitempty"`
	// Requested propagation mode.
	Propagation MountPropagation `protobuf:"varint,5,opt,name=propagation,proto3,enum=runtime.MountPropagation" json:"propagation,omitempty"`
}
```

**Comment by msau42** [comment]
Sorry I still am not being clear.  In Kubernetes, we support the following features:
- format the block device the first time it's being mounted
- resize the filesystem if it was requested by PVC

These two operations require going through the global mount routine.  But since your container runtime would skip this step, that means it would have to be reimplemented in the container runtime.

**Comment by abel-von** [comment]
@msau42  Yes, our container runtime has implemented  it, it will do the format and mount if we define a block device file(like /dev/sda) in HostPath of the Mounts in the request to docker. we just have to let k8s to support defining a block mode pv(or pvc)  in volumeMounts  of pod, and pass the device file path to docker if the volume is a block mode volume, instead of reporting an error, which is what k8s do now.

**Comment by msau42** [comment]
The main downside I can see with specifying a block PVC in volumeMounts is that the user needs to understand the specific behavior of which container runtime they are running on.  I think we can improve on this by adding new interfaces at the lower level, instead of at the user level.

One way I think we could do this is if we explicitly support a FS on block volumes capability.  Today this is all implicitly implemented inside volume plugins.  To explicitly support this, we would need:

* Volume plugin interface for fs-on-block
* Volume binding mode to allow filesystem PVC to bind to block PV, if the volume plugin supports it.  I don't see a good way for external provisioners to report this capability though.
* New CRI interface/option for FS on block, so that kubelet volume manager can bypass FS handling if the runtime supports it

Current features like fs creation and fs resize would be impacted, and the design would have to handle supporting these.

**Comment by msau42** [comment]
Another downside of the runtime performing the mount is also that only standard Linux block devices would be supported.

If you wanted to support any arbitrary volume, then it would be worth looking into some mechanism to run CSI drivers inside the runtime, which is definitely a huge change.
/cc @saad-ali

**Comment by saad-ali** [comment]
@tallclair and I discussed doing mounts inside of a pod for secure containers. Running CSI inside the pod with some "volume manager" like component seems plausible for file volumes. The file on block case, like @msau42 could be more challenging unless we make it explicit in the API.
