### ISSUE TITLE
iptables rule: -A POSTROUTING -s x.x.x./cidr -j FLANNEL missing #971

### ISSUE THREAD

**Issue by lth2015** [kubernetes/kubernetes#62246]
Pods on Some nodes in k8s cluster(production) can not communicate with other pods and nodes. 
After debugging, I find some rules are missing, compared with a good one(on other node) there is the difference:

![3efd8c17982e975c89be5cc0b1840020](https://user-images.githubusercontent.com/12841814/38293318-97a790c2-3819-11e8-9876-9ad3fb05f01f.png)

Additionally, I find some "error log" in kube-proxy: 
```
Failed to execute iptables-restore: exit status 1 (iptables-restore: line 3868 failed)
```

The problem looks like: 
* [Flannel and kube-proxy race for postrouting chain](https://github.com/kubernetes/kubernetes/issues/20391)
* [--ip-masq should also add masquerade from outer net to flannel net](https://github.com/coreos/flannel/issues/318)
* [A pod can't direct traffic to itself via a service ](https://github.com/kubernetes/kubernetes/issues/20475)

I start `flanneld` with `--ip-masq` option.
```
# cat /etc/default/flanneld
FLANNEL_OPTS="--etcd-endpoints=http://127.0.0.1:4001  --ip-masq  --iface=x.x.x.x"
```

runtime:
```
# cat /var/run/flannel/subnet.env
FLANNEL_NETWORK=10.135.0.0/16
FLANNEL_SUBNET=10.135.26.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
## 

My Environment

* Flannel version: 0.5.5
* Backend used (e.g. vxlan or udp):
* Etcd version: 2.2.1
* Kubernetes version (if used): 1.4.9
* Operating System and version:  Ubuntu 14.04 3.19.0-25-generic x86_64

**Comment by buptliuwei** [comment]
hi,are you solved this problem? I have a similar problem [Failed to execute iptables-restore: exit status 1 in kube-proxy #784](https://github.com/kubernetes/kubeadm/issues/784)
