### ISSUE TITLE
Bash completion does not work for initContainers

### ISSUE THREAD

**Issue by nak3** [kubernetes/kubernetes#62255]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Following command does not complete initContainers' name.

~~~
kubectl logs POD_NAME -c <TAB>
~~~

**What you expected to happen**:

`kubectl logs POD_NAME -c <TAB>` completes initContainers' name.

**How to reproduce it (as minimally and precisely as possible)**:

After deploy pod with initContainers, then:

~~~
kubectl logs POD_NAME -c <TAB>
~~~

**Anything else we need to know?**:

Proposal patch: https://github.com/kubernetes/kubernetes/pull/61638

**Comment by nak3** [comment]
@kubernetes/sig-cli-bugs

**Comment by superbrothers** [comment]
This issue was already fixed by https://github.com/kubernetes/kubernetes/pull/63914.

/close
