### ISSUE TITLE
apply Flannel with backend vxlan to k8s, so lag, the netword capacity slow down %20.

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#62263]
I was integrating a the flannel (whose backend is vxlan) as a overlay forwarding netowrk upon k8s in product cluster. I found that the network performance has been slow down about 20% when dockers communicating across hosts. But it was noraml when dockers hosting one machine communicating. I dont down what is the root-cause. Any CNI flaw remaining in current  k8s mainline?  

Is there any work around or bug-fix for the issue now?
/sig network
@kubernetes/sig-network

**Comment by cizixs** [comment]
flannel vxlan is supposed to cause network performance loss, same host pods communicate directly without vxlan encapsulation.

It is not a kubernetes/cni issue or bug.
