### ISSUE TITLE
Old LocalVolumeSource documentation 

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#62278]
**What happened**:
Documentation of LocalVolumeSource says:

```
type LocalVolumeSource struct {
  		// The full path to the volume on the node
		// For alpha, this path must be a directory
		// Once block as a source is supported, then this path can point to a block device
		Path string
}
```

**What you expected to happen**:
Local block volumes are implemented in 1.10 and it's in Beta now. It should be documented in API together with its consequences e.g. that a block device is supported now and such device must be used in volumes with `VolumeMode=Block`.

@dhirajh @ianchakeres, PTAL

**Comment by saad-ali** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/62523
