### ISSUE TITLE
kubefed init error: no configuration has been provided

### ISSUE THREAD

**Issue by thefragmenter** [kubernetes/kubernetes#62299]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kubefed init failed with an error:

```
Creating federation component deployments...Error from server (Forbidden): roles.rbac.authorization.k8s.io "federation-system:federation-controller-manager" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]}] user=&{user@example.com  [system:authenticated] map[authenticator:[GKE]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```
**What you expected to happen**:
succeed
**How to reproduce it (as minimally and precisely as possible)**:
 kubefed init kfed --host-cluster-context=west-coast --dns-zone-name="echo.example.com" --dns-provider="google-clouddns"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.8.6
- Cloud provider or hardware configuration:GCE
- OS (e.g. from /etc/os-release):Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`):Linux cs-6000-devshell-vm-8ed70339-1446-4d65-9d2b-e940e9cc9e9a 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
- Install tools:
- Others: Cloud Shell

@kubernetes/sig-api-machinery-bugs

**Comment by wenjiaswe** [comment]
cc @cheftako

**Comment by paulorobles** [comment]
I have this same issue building the 1.10.0-alpha.0
