### ISSUE TITLE
Presubmit e2e's run for OWNERS / OWNERS_ALIASES changes

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#62290]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
For PR's that make change to an OWNERS or OWNERS_ALIASES file, all the presubmit e2e tests ran. 

**What you expected to happen**:
We should not have to run all the test for changes to OWNERS or OWNERS_ALIASES. It seems like a waste of resources.

/assign @kubernetes/sig-contributor-experience-bugs

**Comment by nikhita** [comment]
> For PR's that make change to an OWNERS 

It's true for `OWNER_ALIASES` now but doesn't run presubmit tests for `OWNERS` files.

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/test-infra/issues/8275

**Comment by nikhita** [comment]
This has been fixed in https://github.com/kubernetes/test-infra/pull/8482. Closing.

/close
