### ISSUE TITLE
Generate valid openapi spec for intstr.IntOrString

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#62329]
Currently openapi-gen generated spec for `intstr.IntOrString` only allows `string` types. https://github.com/kubernetes/apimachinery/blob/5d4f0da8e5fde7cbadf8ab3ce5cfb76f86dd854e/pkg/util/intstr/intstr.go#L124 . This is incorrect and causes problem when used to generate CRD validation schema. I generate  CRD schema validation using a pipeline like below:
```
types.go ---(openapi-gen) ---> openapi_generated.go ---(crd-validation)---> crd.yaml
```

One fix suggested by @sttts is to use schema like 
```
{
  "oneOf": [
    { "type": "string" },
    { "type": "number" }
  ]
}
```
But `anyOf` is not defined in v2 spec so can't be be returned from `IntOrString.OpenAPIDefinition()` method. But when CRD schema is generated one can update the auto generated schema for `IntOrStr` to fix this issue.  For example: https://github.com/appscode/kutil/pull/133/files

[1] crd-validation: https://github.com/ant31/crd-validation

**Comment by tamalsaha** [comment]
An alternative solution will be to implement  custom validator for `int-or-string` format following https://github.com/go-openapi/strfmt . It seems to me that it will work with both openapi v2 and v3.

**Comment by tamalsaha** [comment]
This issue has been reported before by @garethr https://groups.google.com/forum/#!topic/kubernetes-sig-apps/RGRCIHmb4gU .

**Comment by sttts** [comment]
> An alternative solution will be to implement custom validator for int-or-string format following https://github.com/go-openapi/strfmt

But even with a format and `type: "string"` we do not allow `foo: 42`, although it is an integer and should be accepted by a `IntOrString` field.

**Comment by tamalsaha** [comment]
> But even with a format and type: "string" we do not allow foo: 42, although it is an integer and should be accepted by a IntOrString field.

Yeah, I agree the alternative will work. Seems like there is no good solution until everything switches to v3 .

**Comment by mbohlool** [comment]
We can start by adding support for some of OpenAPI v3 features in kube-openapi definition generator. These features should be flag protected (or there should be a backward compatible way to convert them back to v2). Would you please file an issue with kube-openapi repo?

**Comment by sttts** [comment]
> We can start by adding support for some of OpenAPI v3 features in kube-openapi definition generator.

Do we have an versioned openapi endpoint?

**Comment by nikhita** [comment]
> We can start by adding support for some of OpenAPI v3 features in kube-openapi definition generator.

There is also the issue that go-openapi for openapi v3 is not maintained: https://github.com/kubernetes/kubernetes/issues/62326.
