### ISSUE TITLE
go-openapi/spec3 is not maintained

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#62326]
Kubernetes depends on openapi v3 spec. But it seems that the official repo is not maintained https://github.com/go-openapi/spec3/commits/master . The repository readme says `This repository is not usable at this moment, the implementation is incomplete` .

The primary contributor of the library @casualjim has mentioned [here](https://github.com/go-swagger/go-swagger/issues/1122#issuecomment-356086493):

`there are a lot more issues with 3.0. it has expressions, a vastly different syntax and so on.
Somebody else is more than welcome to step up but I don't have time to implement and mantain such a large specification as main contributor.`

This seems like something to look into for Kubernetes.

**Comment by sttts** [comment]
> The only place we use v3 spec is in CRDs validation schema

I think @tamalsaha's point is that we might have problems to move forward to newer spec versions with go-openapi if the maintenance situation does not change.

**Comment by mbohlool** [comment]
I think this still needs to be resolved for GA.

/remove-lifecycle rotten
/reopen

**Comment by liggitt** [comment]
go-openapi/spec3 is not used by kubernetes

/close
