### ISSUE TITLE
plugin.host.GetPodByName return value always  is `nil`

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes/kubernetes#62321]
/kind bug
/sig network
**What happened**:
```diff
--- a/pkg/kubelet/network/kubenet/kubenet_linux.go
+++ b/pkg/kubelet/network/kubenet/kubenet_linux.go
@@ -550,6 +550,11 @@ func (plugin *kubenetNetworkPlugin) SetUpPod(namespace string, name string, id k

+                       v1Pod, ok := plugin.host.GetPodByName(namespace, name)
+
+                       if ok && v1Pod != nil {
+                               glog.Infof("%v\n", v1Pod.ObjectMeta.Annotations)
+                       }

```

**What you expected to happen**:

I want get annotations by call `plugin.host.GetPodByName(namespace, name)`.

*v1.8.7:*
`v1pod` awalys is `nil` so that I can't get Annotations .

*v1.4.6:*
I can get the  annotations of pod from call `plugin.host.GetPodByName(namespace, name)`

I want to update pod annotations when pod creating.

**Comment by dixudx** [comment]
@Sn0rt Are you using remote runtime ?

**Comment by Sn0rt** [comment]
@dixudx 
no, In fact, I don't know what's is remote runtime .
