### ISSUE TITLE
openapi-gen lacks support for enum

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#62325]
Currently I generate  CRD schema validation using a pipeline like below:
```
types.go ---(openapi-gen) ---> openapi_generated.go ---(crd-validation)---> crd.yaml
```
While this works, openapi-gen does not generate spec information for [enums](https://spacetelescope.github.io/understanding-json-schema/reference/generic.html#enumerated-values) . We would like to see this supported.

[1] crd-validation: https://github.com/ant31/crd-validation

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/apiextensions-apiserver/issues/28

**Comment by mbohlool** [comment]
Looked through your demo briefly. Looks reasonable. Can you add this to kube-openapi? (also an issue in that repo would be nice).

**Comment by tamalsaha** [comment]
Thanks @mbohlool . I don't have the bandwidth necessary to push it through the Kubernetes review process. Anyone interested in this is welcome to take it from here.

Thanks @nikhita for filing opening issue in kube-openapi repo.

**Comment by anubhakushwaha** [comment]
@tamalsaha @nikhita @sttts I would like to research and work on it.

**Comment by fabiand** [comment]
Any progress on this matter?

**Comment by sttts** [comment]
Elsewhere @bgrant0607 had a comment that enums are an API anti-pattern because we cannot extend the set without breaking clients (which will be unprepared for new values).

Technically, we can express enums via `AnyOf` + regexes in OpenAPI v3. But adding it to openapi-gen promotes the idea of enums in the API.

Here are some pointers: 
- https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties

> Some resources in the v1 API contain fields called phase, and associated message, reason, and other status fields. The pattern of using phase is deprecated. Newer API types should use conditions instead. Phase was essentially a state-machine enumeration field, that contradicted system-design principles and hampered evolution, since adding new enum values breaks backward compatibility. Rather than encouraging clients to infer implicit properties from phases, we intend to explicitly expose the conditions that clients need to monitor. Conditions also have the benefit that it is possible to create some conditions with uniform meaning across all resource types, while still exposing others that are unique to specific resource types. See #7856 for more details and discussion.

- https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#backward-compatibility-gotchas

> Enumerated values cause similar challenges. Adding a new value to an enumerated set is not a compatible change. Clients which assume they know how to handle all possible values of a given field will not be able to handle the new values. However, removing a value from an enumerated set can be a compatible change, if handled properly (treat the removed value as deprecated but allowed). For enumeration-like fields that expect to add new values in the future, such as reason fields, please document that expectation clearly in the API field descriptions. Clients should treat such sets of values as potentially open-ended.

**Comment by nikhita** [comment]
> Elsewhere @bgrant0607 had a comment that enums are an API anti-pattern because we cannot extend the set without breaking clients (which will be unprepared for new values).

https://github.com/kubernetes/apiextensions-apiserver/issues/28#issuecomment-372751580

Like mentioned in @sttts's and @bgrant0607's comment, I don't think we will support enums. Closing this, but please feel free to reopen if needed.
/close
