### ISSUE TITLE
Cannot create pods with volumes with projected Secret keys to nested paths on Windows nodes

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#62338]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig windows

**What happened**:

Creating pods containing volumes with projected Secret keys to nested paths fails on Kubernetes using Windows nodes, they get stuck in the ``ContainerCreating`` state. Additionally, this causes the Kubelet service on the Windows node to fully utilize a CPU indefinitely (even after the pod was deleted). Creating multiple pods will eventually cause the node to be inaccessible.

This issue does not occur with simple paths.

**What you expected to happen**:

The pod should end up in ``Running`` / ``Completed`` state.

**How to reproduce it (as minimally and precisely as possible)**:

    echo "apiVersion: v1
    kind: Secret
    metadata:
      name: my-special-secret
    type: Opaque
    data:
      data-1: aGVsbG8gdGhlcmUh
    " > my-secret.yaml

    echo "apiVersion: v1
    kind: Pod
    metadata:
      name: test-projected-volume
    spec:
      containers:
      - name: test-projected-volume
        image: atuvenie/mounttest:1.0
        args: ["--file_content=/projected-volume/new/path/data-1"]
        volumeMounts:
        - name: all-in-one
          mountPath: "/projected-volume"
          readOnly: true
      volumes:
      - name: all-in-one
        projected:
          sources:
          - secret:
              name: my-special-secret
              items:
                - key: "data-1"
                  path: "new/path/data-1"
    " > test-projected-volume-bad.yaml

    kubectl create -f ./my-secret.yaml
    kubectl create -f ./test-projected-volume-bad.yaml
    kubectl get --watch pod test-projected-volume

Replacing ``new/path/data-1`` with ``new-path-data-1`` will result in creating a pod in ``Running`` / ``Completed`` State.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version:
  Client Version: v1.9.3
  Server Version: v1.8.4
  Windows Kubelet Version: v1.8.4-20+75463ace30b8ff
- Cloud provider or hardware configuration: Azure Container Service
- OS (e.g. from /etc/os-release): Microsoft Windows Server Datacenter 10.0.16299 N/A Build 16299

**Comment by PatrickLang** [comment]
@feiskyer is this an area you might be able to help with?

**Comment by liggitt** [comment]
@kubernetes/sig-storage-bugs

**Comment by feiskyer** [comment]
@bclau There is something wrong when setting up nested paths. Let me file a PR to fix this

**Comment by feiskyer** [comment]
@bclau @PatrickLang  Filed #62375 to fix this issue. Please note that symlink is used and it is only available on Windows 10 Insider & Windows Server Insider builds 17074+ (refer [here](https://github.com/moby/moby/issues/28401#issuecomment-360648343)).

**Comment by PatrickLang** [comment]
@feiskyer will this help https://github.com/kubernetes/kubernetes/issues/52419 as well?

**Comment by feiskyer** [comment]
@PatrickLang #52419 is the symlink issues, which requires Windows next release.
