### ISSUE TITLE
kubernetes v1.10 can not get capacity of GPU

### ISSUE THREAD

**Issue by kinglion811** [kubernetes/kubernetes#62332]
I deploy kubernetes v1.10 with kubeadm,the cluster can run cpu tasks,but when I run GPU tasks they can not run,when I describe the nodes,I can't find the GPU Capacity,
![image](https://user-images.githubusercontent.com/6119243/38553423-d2e706d6-3cf1-11e8-9857-9febc56ecdc0.png)
Environment
 the docker version is docker-ce-17.03.2
the cuda is
![image](https://user-images.githubusercontent.com/6119243/38553503-130c5f36-3cf2-11e8-9a44-d8216177d8fe.png)
I can run GPU test by nvidia-docker runtime
![image](https://user-images.githubusercontent.com/6119243/38553596-522f08e4-3cf2-11e8-90a0-8c415e960163.png)
I want to know,how to config the kubelet  or othe way to find the GPU resource

**Comment by pineking** [comment]
read the docs first, https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
