### ISSUE TITLE
Support containerized kubelet in CI

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#62342]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 
@kubernetes/sig-testing-feature-requests 

**What happened**:
We are seeing many issues in containerized kubelet environments due to e2es not be automatically run in CI against that environment.

**Comment by dims** [comment]
https://github.com/kubernetes/test-infra/pull/7631

**Comment by kargakis** [comment]
Unclear why this is a sig-testing feature request.

**Comment by msau42** [comment]
I am unfamiliar with all the pieces that are required to do this, so just including sig-testing for consultation.

**Comment by gnufied** [comment]
@derekwaynecarr  pointed out that , we do have Conformance tests running inside containarized kubelet at least. https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-containerized-conformance-aws-e2e-rhel 

It runs every 2 hours and is not blocking. I think we can extend the existing suite to include all tests and make it blocking.

**Comment by fejta** [comment]
/assign @Q-Lee 

This seems relevant to your dind work here?

**Comment by Q-Lee** [comment]
@fejta initially I tried to run the kubelet as a containerized process. Unfortunately, I found it to be very unstable, probably because it wasn't strongly tested in CI.

**Comment by fejta** [comment]
Isn't the dind whole cluster in a container, thus also kubelet?

**Comment by Q-Lee** [comment]
Yes, but within the container the kubelet appears as, more or less, a bare process. The containerized flag has slightly different behavior.

@dchen1107 what's the status of the containerized kubelet, and who should I talk to?

**Comment by dims** [comment]
So i have something working - it's a CI job that uses local-up-cluster.sh with `DOCKERIZE_KUBELET=y`. please see https://github.com/kubernetes/kubernetes/pull/62508
