### ISSUE TITLE
Kubelet not support memory hot add/remove

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes/kubernetes#62355]
Kubelet scan host total memory only on startup and later for detect memory capacity
changes, kubelet must be restarted.

I think kubelet works as designed,
but in cases when host total ram can change:
 - Server ram hot-add/remove
 - Vm hot-add/remove
 - KVM Balloon

Kubelet fail to detect changes and use old capacity numbers.

I think if kubelet will update capacity information, when it check host for free ram (while scheduling),
that situation will handled correctly.

Thanks.

/kind feature
/sig scheduling

- Kubernetes version: 1.8.9
- OS: Ubuntu 16.04
- Kernel: 4.14.32

**Comment by mvernimmen** [comment]
/remove-lifecycle stale

Experienced the same with
kubernetes version: 1.10.5
OS: CentOS Linux release 7.5.1804 (Core)
kernel: 3.10.0-862.6.3.el7.x86_64

**Comment by namreg** [comment]
Faced with the same issue
