### ISSUE TITLE
tests failing with "Invalid choice: 'configure-docker'."

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#62356]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
A PR that used to pass tests is now failing some, with a complaint that looks like it is from broken testing infrastructure.  See https://k8s-gubernator.appspot.com/pr/60685 and #60685 .  The recent failures have the following in their build logs:
```
I0410 19:59:22.743] push-build.sh::common::set_cloud_binaries(): /google-cloud-sdk/bin/gcloud --quiet auth configure-docker
I0410 19:59:30.539] ERROR: (gcloud.auth) Invalid choice: 'configure-docker'.
```

**What you expected to happen**:
Tests that passed in the past to pass again today.

**How to reproduce it (as minimally and precisely as possible)**:
Run a test today, against release-1.9.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): release-1.9
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): whatever those tests use
- Kernel (e.g. `uname -a`): whatever those tests use
- Install tools: whatever those tests use
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing-bugs

**Comment by rmmh** [comment]
This is probably caused by kubernetes/release#515

@david-mcmahon

**Comment by sjenning** [comment]
@rmmh merge time matches when when the test started failing about 1:15PM CDT today
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-device-plugin-gpu

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/issues/7633

**Comment by BenTheElder** [comment]
updating here that the offending PR in k/release was rolled back temporarily, we're upgrading gcloud in test-infra which *should* unblock reverting the revert without issues.

**Comment by BenTheElder** [comment]
for more context: https://github.com/kubernetes/release/pull/548#discussion_r180634885

the new images with latest gcloud were not enough, next version should have a patch hopefully, but in the meantime @david-mcmahon is working on a patch to use `gcloud docker` again

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/pull/549

**Comment by BenTheElder** [comment]
this looks to be fixed for the moment.
/close
