### ISSUE TITLE
kube-GC delete Initcontainers of running pod 

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#62362]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig node
> /kind feature

**What happened**:
if the nums of initcontainers greaters than the --maxmum-dead-containers, the initcontainers will be deleted by Garbage Collector.  like below:
 i set the GC args : 
--maximum-dead-containers=2 --maximum-dead-containers-per-container=1 
then create 3 pod with initcontainer on the node
```
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS                     PORTS               NAMES
214d1bc85175        6b60a9253836                                      "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds                                   k8s_nginx_nginx-spfcw_default_23e939db-3d69-11e8-b372-002dc92800b3_0
9b8db298ca4d        6b60a9253836                                      "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds                                   k8s_nginx_nginx-rbcmd_default_23e92d65-3d69-11e8-b372-002dc92800b3_0
2060dba8ce1a        6b60a9253836                                      "nginx -g 'daemon off"   4 seconds ago       Up 3 seconds                                   k8s_nginx_nginx-k8rrf_default_23e07345-3d69-11e8-b372-002dc92800b3_0
ceb187901cca        6b60a9253836                                      "/bin/sh -c 'echo hel"   4 seconds ago       Exited (0) 3 seconds ago                       k8s_init-nginx_nginx-rbcmd_default_23e92d65-3d69-11e8-b372-002dc92800b3_0
c1cc836642b8        6b60a9253836                                      "/bin/sh -c 'echo hel"   4 seconds ago       Exited (0) 3 seconds ago                       k8s_init-nginx_nginx-spfcw_default_23e939db-3d69-11e8-b372-002dc92800b3_0
8ad1676f2d71        6b60a9253836                                      "/bin/sh -c 'echo hel"   5 seconds ago       Exited (0) 4 seconds ago                       k8s_init-nginx_nginx-k8rrf_default_23e07345-3d69-11e8-b372-002dc92800b3_0

```
you will seeing the kube-gc keep deleteing the init containers
`Apr 11 17:27:28 hpa-vm kubelet[20828]: E0411 17:27:28.961442   20828 kuberuntime_gc.go:128] ====removed container "8ad1676f2d71b24bb10c5bbd9e017074b18a822eb877cc20b078c20039117f7d" ====
Apr 11 17:28:29 hpa-vm kubelet[20828]: E0411 17:28:29.011071   20828 kuberuntime_gc.go:128] ====removed container "c1cc836642b8e16d548abfdddf6a046ca3ac9db6eadd672fdab786f608e29f05" ====

 `

**What you expected to happen**:
initcontainers of running pod will not be deleted
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.428+5d144152e4d07f", GitCommit:"5d144152e4d07f3752c05ec24e31d840adcd90a2", GitTreeState:"clean", BuildDate:"2018-02-26T02:37:04Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.428+5d144152e4d07f", GitCommit:"5d144152e4d07f3752c05ec24e31d840adcd90a2", GitTreeState:"clean", BuildDate:"2018-02-26T02:37:04Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Pingan2017** [comment]
cc @zhangxiaoyu-zidif  @Random-Liu @yujuhong

**Comment by zhangxiaoyu-zidif** [comment]
in this case, if we set a small value (e.g. n) for maximum-dead-containers, and it will easy to trigger the gc to delete dead init container, and the running pod will be affected. if we have n+1 pods with init containers, there must be at least one pod stay `init`

**Comment by warmchang** [comment]
The inicontainer run and Completed, this means that the life cycle of inicontainer is over.

```
Init Containers:
  wait:
    Container ID:  docker://28dc733fe517ae343e811be2d17c3a1d7a4d22fdf417800280d59097ae214851
    Image:         busybox:latest
    Image ID:      docker-pullable://busybox@sha256:2107a35b58593c58ec5f4e8f2c4a70d195321078aebfadfbfb223a2ff4a4ed21
    Port:          <none>
    Command:
      sh
      -c
      echo The wait app is running! && sleep 30
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Apr 2018 01:42:56 +0800
      Finished:     Thu, 12 Apr 2018 01:43:27 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7tchh (ro)
```

And the inicontainer will not affect the following non-initcontainers, so deleting it should not trigger a POD restart.

But the point is that when the dead container has been deleted (kube gc or docker rm), we can find that the pod will restart:
```
[root@k8s-master-controller:~]$ kubectl get pod -w
NAME                                   READY     STATUS     RESTARTS   AGE
hello-pod                              0/1       Init:0/1   0          5m
```

**Comment by zhangxiaoyu-zidif** [comment]
is that necessary to restart a init container when a pod status is running?

**Comment by wenlxie** [comment]
If the node restart or kubelet restart , then pod's initContainer will run again?

**Comment by zhangxiaoyu-zidif** [comment]
correct @wenlxie

**Comment by niuqg** [comment]
If initContainer restart failed, pod's status will become "Init: CrashLoopBackOff".

**Comment by anapsix** [comment]
this is still an issue, when initContainer is removed by `docker container prune`, or `docker rm`, it respawns, but main Pod's container(s) continue to run..

Depending on initContainer action, it might not be able to complete successfully, while main container is running, causing `Init:CrashLoopBackOff`.

In some cases, initContainer's actions are not compatible with running main container(s), causing other failures.
For example: init container moves application code into tmpfs, (or PV), while main container's `entrypoint.sh` updates config values from external source, causing application config to reset to defaults, breaking application (since main container did not restart, and `entrypoint.sh` was not executed)
