### ISSUE TITLE
Kubernetes Federation Error: User "client" cannot create namespaces at the cluster scope: Unknown user "client"

### ISSUE THREAD

**Issue by thefragmenter** [kubernetes/kubernetes#62361]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Error trying to setup Kubernetes Federation:

**Creating a namespace federation-system for federation system components...Error from server (Forbidden): namespaces is forbidden: User "client" cannot create namespaces at the cluster scope: Unknown user "client".**

**What you expected to happen**:
No error

**How to reproduce it (as minimally and precisely as possible)**:
```
# Set the project and domain name
export PROJECT=abc-9102-1sf
export DNS_ZONE=echo.examplefed.com.

# Create the clusters
gcloud container clusters create west-cluster --zone us-west1-c --scopes "cloud-platform,storage-ro,logging-write,monitoring-write,service-control,service-management,https://www.googleapis.com/auth/ndev.clouddns.readwrite" --preemptible &
gcloud container clusters create east-cluster --zone us-east1-b --scopes "cloud-platform,storage-ro,logging-write,monitoring-write,service-control,service-management,https://www.googleapis.com/auth/ndev.clouddns.readwrite" --preemptible &

# Workaround for RBAC error
# https://github.com/kubernetes/kubernetes/issues/42559
gcloud config set container/use_client_certificate True
export CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True

# Get credentials
gcloud container clusters get-credentials west-cluster --zone=us-west1-c
gcloud container clusters get-credentials east-cluster --zone=us-east1-b

# Aliases
kubectl config set-context east --cluster=gke_${PROJECT}_us-east1-b_east-cluster --user=gke_${PROJECT}_us-east1-b_east-cluster
kubectl config set-context west --cluster=gke_${PROJECT}_us-west1-c_west-cluster --user=gke_${PROJECT}_us-west1-c_west-cluster

# Initiate Federation. After this step I get the error.
kubefed init kfed  --host-cluster-context=east  --dns-zone-name=${DNS_ZONE}  --dns-provider=google-clouddns
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.8
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Debian

@kubernetes/sig-multicluster-bugs

**Comment by koolhandluke** [comment]
I am seeing the same too ..

**Comment by jetpak** [comment]
try enabling "Legacy Authorization" for your cluster in the GKE Web Console
https://stackoverflow.com/questions/49075723/what-does-unknown-user-client-mean

**Comment by ensonic** [comment]
I got a similar error:
```
Error: error installing: deployments.extensions is forbidden: User "system:serviceaccount:default:helm" cannot create deployments.extensions in the namespace "kube-system": Unknown user "system:serviceaccount:default:helm"
```
The error message is confusing
1) is the user (service acct.) missing or is the user lacking permissions
2) what are the components in the fully-qualified user name? Looks like
   ???:<account-type>:<namespace>:<name>, is this documented anywhere? Ideally 'kubectl describe serviceaccount helm' would show the fully qualified name to aid debugging. Will file extra bug reports.
