### ISSUE TITLE
Cloud provider can not support dynamic update configuration

### ISSUE THREAD

**Issue by sunny-hw** [kubernetes/kubernetes#62376]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**: 
Since the configuration of the provider is imported during the initialization phase, if some of the configuration of the provider is updated, such as when the password is updated, then the cloud-provider will fail to use the original password. The configuration file must be updated and the controller must be restarted to use the new password. Re-certify.

**What you expected to happen**:
Why does cloud-provider not support dynamic update configuration, especially passwords, or if there is a plan or proposal for this requirement?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-api-machinery-feature-requests
@kubernetes/sig-openstack-feature-requests
/sig api-machinery
/sig openstack
/area cloudprovider

**Comment by wenjiaswe** [comment]
cc @cheftako

**Comment by FengyunPan2** [comment]
cc @dims

**Comment by dims** [comment]
@sunny-hw when you move to external cloud provider, there will be more options. because of the way code is structured for the existing in-tree + kube-controller-manager/api-server, there is not much room for adding a dynamic update method. 

https://github.com/kubernetes/cloud-provider-openstack
