### ISSUE TITLE
issue with a bug in docs of configure-multiple-schedulers

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#62386]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://v1-6.docs.kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
the document says we need to setup

```
--leader-elect=true
--lock-object-namespace=lock-object-namespace
--lock-object-name=lock-object-name
```

to use mulitiple scheduler with leader election enabled.But I cannot find these args in kube-scheduler v1.6.6.These args seems to be bringing in at v1.7.0

The docs confused me

**Proposed Solution:**

Maybe we need to clarify that v1.6 does  not support these args

**Page to Update:**
https://kubernetes.io/...

**Comment by wgliang** [comment]
maybe you can submit a issue on [website](https://github.com/kubernetes/website).
