### ISSUE TITLE
pod-infra-container-image flag on kubelet does not work when using cri-containerd

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/kubernetes#62388]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
pod-infra-container-image flag of kubelet does not work when using cri-* as container runtime. Both cri-o and cri-containerd has its own configuration to setup sandbox image.

**What you expected to happen**:
either cri-* uses this flag for sandbox image configuration or we need to update the description of this flag.

**How to reproduce it (as minimally and precisely as possible)**:
Run cri-o or cri-containerd and set pod-infra-container-image flag on kubelet with another image.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
Dup of #55676.

See [my comment](https://github.com/kubernetes/kubernetes/issues/55676#issuecomment-371084007).

* For `cri-o`, you can override the sandbox image by `--pause-image=[value]`.
* For `containerd`, you can override it in [`/etc/containerd/config.toml`](https://github.com/containerd/cri/blob/master/docs/config.md).

/close

**Comment by andrecp** [comment]
Just in case someone else ends up in this issue... the containerd config toml has two versions  -- 1 and 2

If you're using version 1 it should look something like

```
  [plugins.cri]
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    enable_selinux = false
    sandbox_image = "YOUR.PRIVATE.REGISTRY/kubernetes/pause:3.2"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      no_pivot = false
      [plugins.cri.containerd.runtimes.runc]
        [plugins.cri.containerd.runtimes.runc.options]
          SystemdCgroup = true
```

Note that it uses `cri` instead of the `plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc` namespace..

Then you need to `systemctl restart containerd` or the equivalent... hopefully this will save a couple of hours of someone.. or my future self...
