### ISSUE TITLE
run all pods on a selected hots leads to "Deployment does not have minimum availability"

### ISSUE THREAD

**Issue by gabx** [kubernetes/kubernetes#62387]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

kind bug
Impossible to select a specific node to deploy the application onto.

**What happened**:
On Rancher GUI:
workloads > deploy > Name: mynginx; docker image: nginx:latest; Scalable deployment of 1 pod; namespace: default; Port > every node : 80.
Then Node scheduling >  Run all pods for this workload on a specific node > select in the menu one of my node
Launch
deployement halts with this message:  Deployment does not have minimum availability. Debugging with 
 `# kubectl describe deployment mynginx` returns 

```
Conditions:
Type           Status  Reason
   ----           ------  ------
 Available      False   MinimumReplicasUnavailable
Progressing    False   ProgressDeadlineExceeded
```

**What you expected to happen**:
nginx application running on my node

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Version:"go1.9.3
- Cloud provider or hardware configuration: custom
- OS (e.g. from /etc/os-release): Linux amd64
- Kernel (e.g. `uname -a`): 4.15.6-300.fc27.x86_64
- Install tools:
- Others:

**Comment by joshross12** [comment]
@gabx what was the resolution?
