### ISSUE TITLE
node is NotReady, pod is NodeLost

### ISSUE THREAD

**Issue by xinjt** [kubernetes/kubernetes#62389]
here is my situation:
[root@k8s-master kube]# kubectl get nodes 
NAME         STATUS     ROLES     AGE       VERSION
k8s-master   Ready      master    2h        v1.10.0
k8s-node1    Ready      <none>    2h        v1.10.0
k8s-node2    NotReady   <none>    2h        v1.10.0
my k8s-node2 status is NotReady   ,and i run 
[root@k8s-master ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                 READY     STATUS     RESTARTS   AGE       IP             NODE
kube-system   etcd-k8s-master                      1/1       Running    0          2h        192.168.1.6    k8s-master
kube-system   kube-apiserver-k8s-master            1/1       Running    0          2h        192.168.1.6    k8s-master
kube-system   kube-controller-manager-k8s-master   1/1       Running    0          2h        192.168.1.6    k8s-master
kube-system   kube-dns-86f4d74b45-j479k            3/3       Running    0          2h        10.244.0.8     k8s-master
kube-system   kube-flannel-ds-f4vpb                1/1       Running    0          2h        192.168.1.17   k8s-node1
kube-system   kube-flannel-ds-h9dcc                1/1       NodeLost   0          2h        192.168.1.14   k8s-node2
kube-system   kube-flannel-ds-xh2d5                1/1       Running    0          2h        192.168.1.6    k8s-master
kube-system   kube-proxy-l5x8n                     1/1       Running    0          2h        192.168.1.6    k8s-master
kube-system   kube-proxy-mr5sj                     1/1       Running    0          2h        192.168.1.17   k8s-node1
kube-system   kube-proxy-x44g4                     1/1       NodeLost   0          2h        192.168.1.14   k8s-node2
kube-system   kube-scheduler-k8s-master            1/1       Running    0          2h        192.168.1.6    k8s-master

and then,
[root@k8s-master ~]# kubectl describe po kube-proxy-x44g4 -n kube-system
Name:           kube-proxy-x44g4
Namespace:      kube-system
Node:           k8s-node2/192.168.1.14
Start Time:     Wed, 11 Apr 2018 09:48:20 +0800
Labels:         controller-revision-hash=1193416634
                k8s-app=kube-proxy
                pod-template-generation=1
Annotations:    <none>
Status:         Running
Reason:         NodeLost
Message:        Node k8s-node2 which was running pod kube-proxy-x44g4 is unresponsive
IP:             192.168.1.14
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  docker://3116c0c558d87a2b0bad309177549f55214c75f174626d5de2c1a8ffd2cb8173
    Image:         k8s.gcr.io/kube-proxy-amd64:v1.10.0
    Image ID:      docker://sha256:bfc21aadc7d3e20e34cec769d697f93543938e9151c653591861ec5f2429676b
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
    State:          Running
      Started:      Wed, 11 Apr 2018 09:48:22 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-proxy-token-7dgw5 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-proxy-token-7dgw5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-proxy-token-7dgw5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:          <none>

and then,
[root@k8s-master ~]# kubectl logs kube-proxy-x44g4 -n kube-system
Error from server (NotFound): the server could not find the requested resource ( pods/log kube-proxy-x44g4)

what is my problem?

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hmarcelodn** [comment]
https://github.com/kubernetes/kubernetes/issues/64108 could be related too.
