### ISSUE TITLE
[sig-instrumentation] "Cluster level logging implemented by Stackdriver should ingest events" fails for GCE and GKE Multizone Clusters

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62399]
## Failures in TestGrid
This test consistently fails for GCE and GKE Multizone Clusters:
https://k8s-testgrid.appspot.com/google-gke#gci-gke-multizone
https://k8s-testgrid.appspot.com/google-gce#gce-multizone

Also fails intermittently in e2e-gce job
https://k8s-testgrid.appspot.com/sig-instrumentation#gce&include-filter-by-regex=Cluster%20level%20logging%20implemented%20by%20Stackdriver%20should%20ingest%20events

## Triage link
More nuanced logs and details can be found at https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Cluster%20level%20logging%20implemented%20by%20Stackdriver%20should%20ingest%20events

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdrvier/basic.go:141
Expected error:
    <*errors.errorString | 0xc4214ae9a0>: {
        s: "timed out waiting for ingestion, still not ingested: ",
    }
    timed out waiting for ingestion, still not ingested: 
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdrvier/basic.go:171

/priority failing-test
/priority important-soon
/kind flake
/sig-instrumentation

@piosz @crassirostris - can you please triage? I saw a [similar issue #60882](https://github.com/kubernetes/kubernetes/issues/60882) closed sometime back.

**Comment by serathius** [comment]
cc @qingling128 @bmoyles0117

**Comment by AishSundar** [comment]
kind/flake

**Comment by serathius** [comment]
Fix is available here https://github.com/kubernetes/kubernetes/pull/62905
