### ISSUE TITLE
test-update-storage-objects.sh: don't pass deprecared options to apiserver

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#62408]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enchancement
/sig api-machinery

**What happened**:
When I run `hack/test-update-storage-objects.sh` I see that it complains about deprecated options:
```console
$ ./hack/test-update-storage-objects.sh 
...
Flag --insecure-bind-address has been deprecated, This flag will be removed in a future version.
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
...
```

**What you expected to happen**:
The script shouldn't use deprecated options and there shouldn't be such warnings.

**How to reproduce it (as minimally and precisely as possible)**:
```shell
$ ./hack/test-update-storage-objects.sh
```

**Comment by wenjiaswe** [comment]
cc @jpbetz
