### ISSUE TITLE
GCE Tests failing with "`mode` has been removed. Please use `subnet-mode` instead"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#62405]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Some of the GCE-based tests (pull-kubernetes-e2e-gce, pull-kubernetes-e2e-gce-device-plugin-gpu, pull-kubernetes-kubemark-e2e-gce, and pull-kubernetes-kubemark-e2e-gce-big) of PR #60685, which is aimed at release-1.9, are failing with the following in their build-log.txt:
```
I0411 14:14:06.590] Creating new custom network: e2e-30237-a8a12f
W0411 14:14:07.072] ERROR: (gcloud.compute.networks.create) `mode` has been removed. Please use `subnet-mode` instead.
W0411 14:14:07.073] Usage: gcloud compute networks create NAME [optional flags]
W0411 14:14:07.074]   optional flags may be  --bgp-routing-mode | --description | --help | --mode |
W0411 14:14:07.074]                          --range | --subnet-mode
```

You can find the test history of that PR at https://k8s-gubernator.appspot.com/pr/60685 .

**What you expected to happen**:
I expected the testing infrastructure to not fail.

**How to reproduce it (as minimally and precisely as possible)**:
Test a PR against release-1.9 now.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): release-1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing-bugs

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/issues/7646

cherrypick PRs to fix are in flight

**Comment by BenTheElder** [comment]
this should be fixed in all supported branches
