### ISSUE TITLE
ValidatingAdmissionWebhook Inconsistently Honors Promoted APIs

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#62402]
/kind bug

**What happened**: ValidatingAdmissionWebhook was configured to listen to creates and updates on extensions/v1beta1 Deployments. A submitted apps/v1 Deployment was not passed through to the web hook, but subsequent attempts to edit or patch the Deployment were.

**What you expected to happen**: I expect AdmissionControl to behave consistently.

**How to reproduce it (as minimally and precisely as possible)**:

Create a ValidatingAdmissionWebhook with the following rule:

```
  rules:
  - apiGroups:
    - extensions
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
```

Use `kubectl create -f` to create a Deployment with `apiVersion: apps/v1` specified. This will succeed (this is expected). Subsequent attempts to `kubectl edit` or `kubectl patch` the object, however, will result in the object going back through AdmissionControl as an `extensions/v1beta1` object.

**Anything else we need to know?**:

For backwards compatibility, it appears that the API Server will transform the final `apiVersion` value (in this case, `apps/v1`) to the legacy value (`extensions/v1beta1`), but it does so only after it has already passed through AdmissionControl filters. This results in a scenario where API requests are evaluated inconsistently between their first and subsequent interactions.

**Environment**:
- 1.9.x
- bare metal
- CentOS 7

**Comment by liggitt** [comment]
`kubectl edit deployment foo` Is ambiguous about which API group you want, and selects the extensions/v1beta1 api, since that is the preferred version listed in discovery for compatibility purposes. 

If you want to edit via the apps/v1 API, Do `kubectl edit deployment.v1.apps foo`

**Comment by liggitt** [comment]
If you add --v=6 to the edit or patch calls, you can see kubectl retrieving and writing via the extensions endpoints. API resources like deployments are accessible from multiple versions and API groups. To ensure you intercept them, you must register for and handle all the versions supported by the server.
