### ISSUE TITLE
CRD resources with names ending in `List` aren't able to be created

### ISSUE THREAD

**Issue by sofuture** [kubernetes/kubernetes#62410]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I've created a CRD with the name `ThingList`. There is no validation specified on the CRD object. Creating the CRD itself succeeds, but attempting to create CRD resources with `kubectl create/apply` of that type fails with a validation error.

**What you expected to happen**:

I expect to be able to create CRD resources of type `ThingList` without a validation error.

**How to reproduce it (as minimally and precisely as possible)**:

A normal working CRD example, `working.yaml`:

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: things.digitalocean.com
spec:
  group: digitalocean.com
  names:
    kind: Thing
    listKind: ThingList
    singular: thing
    plural: things
  scope: Cluster
  version: v1
---
apiVersion: digitalocean.com/v1
kind: Thing
metadata:
  name: fake
spec:
  foo: bar
```

Applying this succeeds as expected:

```
$ kubectl apply -f works.yaml 
customresourcedefinition.apiextensions.k8s.io "things.digitalocean.com" created
thing.digitalocean.com "fake" created
```

Simply changing the name of the CRD kind to `ThingList` breaks however, `broken.yaml`:

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: thinglists.digitalocean.com
spec:
  group: digitalocean.com
  names:
    kind: ThingList
    listKind: ThingListList # this also fails if named `ThingCollection` or other
    singular: thinglist
    plural: thinglists
  scope: Cluster
  version: v1
---
apiVersion: digitalocean.com/v1
kind: ThingList
metadata:
  name: fake
spec:
  foo: bar
```

CRD creates, but the actual resource fails validation:

```
$ kubectl apply -f broken.yaml 
customresourcedefinition.apiextensions.k8s.io "thinglists.digitalocean.com" created
error: error validating "broken.yaml": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```

If you supply `--validate=false` the object does create correctly.

```
$ kubectl apply -f broken.yaml --validate=false
customresourcedefinition.apiextensions.k8s.io "thinglists.digitalocean.com" created
thinglist.digitalocean.com "fake" created
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Digitalocean VM cluster
- OS (e.g. from /etc/os-release): Server (Ubuntu 14.04.5) Client (Ubuntu 16.04.4)
- Kernel (e.g. `uname -a`): Server (4.4.0-111-generic) Client (4.13.0-38-generic)
- Install tools:
- Others:

**Comment by dixudx** [comment]
@sofuture `List` is a special suffix for `Kind` name.

When you create a object using `ThingList`, which will be render as `[]Thing` instead of plain `ThingList`. That's why error `invalid object to validate` occurs due to missing item list.

**Comment by wenjiaswe** [comment]
cc @jennybuckley

**Comment by wenjiaswe** [comment]
cc @mbohlool

**Comment by dixudx** [comment]
@sofuture PTAL #62512. It is a kubectl bug.

**Comment by sofuture** [comment]
@dixudx Thanks! Fix works for me
