### ISSUE TITLE
Add support for building a Kubernetes ConfigMap from a directory recursively

### ISSUE THREAD

**Issue by chirangaalwis** [kubernetes/kubernetes#62421]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Currently, it isn't possible to build a Kubernetes ConfigMap from a directory, recursively [1].

```
conf/
└── integrator
    └── conf
        ├── axis2
        │   └── axis2.xml
        ├── carbon.xml
        ├── datasources
        │   └── master-datasources.xml
        ├── registry.xml
        └── user-mgt.xml
```

Elaborating on how this works currently, using the above directory tree structure,

- if we are to make a ConfigMap from the `conf` folder, first it is required to build a ConfigMap from the `conf` folder which will include only regular files. This will ignore sub directories such as, `axis2` and `datasources`.

- it is required to separately build ConfigMaps for sub directories `axis2` and `datasources`, as described in point 1.

[1]: [Creating a configmap from a folder recursively](https://groups.google.com/forum/#!topic/kubernetes-users/h_FRSr5wW00)

**Comment by thockin** [comment]
To do this, we'd need to allow `/` in CM keys which is not allowed today.  I don't see a good reason not to expand that way if the use case is real.

**Comment by dims** [comment]
@chirangaalwis if you are looking for a way to do this right now ... we have support in 1.10 for binary data in config maps, so you can specify a zip file to be mounted to the pod and add the code running in the pod to unzip or use fuse-zip to access the files. (say hi to paul!)

**Comment by chirangaalwis** [comment]
@dims +1, IMO, this could be adapted as a temporary solution for this use case. Just to note, I managed to successfully try out the support binary data in ConfigMaps.

Yet IMO, requesting users to zip the configuration files which they need to pass on to the containers (in order to preserve the folder structure) is not an ideal solution.
For example, it would force us to add an extra step or two which users need to perform prior to deploying the Kubernetes resources whereas, our effort is to try and minimize the number of steps that need to be performed prior to deployment, as much as possible.

Hence, I think building a ConfigMap from a directory recursively, is an essential feature that should be part of Kubernetes ConfigMaps.

**Comment by dims** [comment]
@chirangaalwis cool. if you can prototype the changes ... that will help push things along.

**Comment by liggitt** [comment]
> I believe building configmap from a directory is a kubectl feature, but I could be mistaken

It involves kubelet changes for unpacking the configmap, API changes to validation, and kubectl changes for creation

**Comment by thockin** [comment]
So I think everyone is saying this is a reasonable change, but someone has to sign up to do it.  This should not be very hard.  Probably broken into a couple PRs:

* allow '/' in CM and secret keys, fix validation, fix projection
* add support to kubectl for building a CM/secret from a directory

**Comment by zhouhaibing089** [comment]
I would like to take this. :)

**Comment by smarterclayton** [comment]
This really needs a proposal, the implications are fairly significant.  This is not a pure backwards compatible change from a consumer perspective (people reading secrets) and could lead to broken applications or broken security tooling.

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/pull/63362#issuecomment-386631005 for the types of things that need to be thought through in the proposal

**Comment by nikhita** [comment]
/remove-lifecycle stale

I'm going to remove the help wanted label because this is something which needs a proposal and hence is not suitable for a new contributor.

/remove-help

**Comment by 0asp0** [comment]
I cannot contribute code (my coding is too bad ;-) but I'd love to see this feature. I want to use it to configuration of logstash pipelines configuration. I have about 30 pipelines per logstash. Each pipeline has it's own directory below pipelines directory.

**Comment by chrono2002** [comment]
+1

**Comment by bingoku** [comment]
+1  Humans need too much

**Comment by Code2Life** [comment]
+1

**Comment by liggitt** [comment]
Thanks for the feature request, but this is unlikely to make progress as an issue. This has no owner or and has not had any meaningful activity for 2+ years. A proposal that works through the design along with the implications of such a change (e.g. https://github.com/kubernetes/kubernetes/pull/63362#issuecomment-386631005) can be opened as a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps).

/close
