### ISSUE TITLE
path with "~" user's home directory doesn't work (kubectl)

### ISSUE THREAD

**Issue by ffd2subroutine** [kubernetes/kubernetes#62452]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cli

**What happened**:
```
kubectl --kubeconfig ~/path/to/the/kubeconfig config set-cluster clustername \
--server=[REDACTED] \
--certificate-authority=~/path/to/the/cluster/ca.crt \
--embed-certs=true
```
returns
```
error: could not read certificate-authority data from ~/path/to/the/cluster/ca.crt: open ~/path/to/the/cluster/ca.crt: no such file or directory
```
**What you expected to happen**:
To successfully create a kubeconfig file and set up cluster related stuff in it

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl --kubeconfig ~/path/to/the/kubeconfig config set-cluster clustername \
--server=[REDACTED] \
--certificate-authority=~/path/to/the/cluster/ca.crt \
--embed-certs=true
```
**Anything else we need to know?**:
But if I use an absolute path like:
```
kubectl --kubeconfig /Users/username/path/to/the/kubeconfig config set-cluster clustername \
--server=[REDACTED] \
--certificate-authority=/Users/username/path/to/the/cluster/ca.crt \
--embed-certs=true
```
Then it works.

Also, if I do:
```
cd ~/some/other/path
```
and then:
```
kubectl --kubeconfig ~/path/to/the/kubeconfig config set-cluster clustername \
--server=[REDACTED] \
--certificate-authority=~/path/to/the/cluster/ca.crt \
```
without **--embed-certs=true** it creates the kubeconfig file but the path to the cluser's ca.crt ends up being like **"/Users/username/some/other/path~/path/to/the/cluster/ca.crt"** in that kubeconfig

**Environment**:
- Kubernetes version: 1.9.3
- Cloud provider: Azure
- kubectl version: 1.9.3 on macOS High Sierra

**Comment by ffd2subroutine** [comment]
hi @zjj2wry 
Thank you for your explanation

**Comment by karataliu** [comment]
'~' is interpreted by your shell, and it works well on bash 4.4

Can this issue be closed?

**Comment by zjj2wry** [comment]
@ffd2subroutine 
I think it should be closed. If there is a problem, you can turn it back on. thanks
/close
