### ISSUE TITLE
Hard to debug scalability tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#62468]
Merging https://github.com/kubernetes/kubernetes/pull/40933 will significantly affect our debugging ability (at least in the context of performance tests, where we can't really run tests on higher verbosity, since the amount of logs there is overloading apiserver).

So I think we may consider reverting it, and making verbosity for those logs a flag (I'm fine with having a default still at 3, but I would like to be able to modify that for the purpose of scalability tests).

**Comment by liggitt** [comment]
Can you use vmodule to increase verbosity for just that component?

**Comment by wojtek-t** [comment]
The problem is (maybe that changed in the meantime, but it was like that in the past), that increasing verbosity above 2 in apiserver (which is what we would need) was basically making it unusable (it was producing too much logs to keep up with load) as well as the amount of logs was insane and not even easily greppable with that...

**Comment by liggitt** [comment]
vmodule lets you control verbosity per file… level 3 on httplog should be pretty targeted

**Comment by ncdc** [comment]
Wouldn't `-vmodule=httplog=3` do the trick? This is the only `httplog.go` file in the entire code base.

**Comment by wojtek-t** [comment]
Aah - I didn't know that.
Yes - that sounds like something that would solve our problem (assuming we don't have other (spammy) files with httplog name :) [but I hope we don't]

Thanks for pointers.

**Comment by shyamjvs** [comment]
IMO the goal here is not just to have it working wrt our scalability tests. We need to ensure that we have these logs even in production where we may need to debug some performance/scalability (or potentially other) issues. I can think of at least a couple of times where I much needed these logs to understand some scalability issue on a real production cluster. 

I believe we should make this `vmodule` change production default (though one that can be opted out by choice). That said, there may be a disagreement here.

**Comment by wojtek-t** [comment]
In theory, you should be able to get all that information from audit logs. They are just harder to use in my opinion, so using them for all performance-related debugging would significantly slow us down.

So maybe the solutions actually should be:" if you don't have audit logs, then do that."

Or, thinking a bit more about that, actually, we may not be audit-log read-only operations, which are also pretty crucial. So actually, maybe that indeed should be default...

**Comment by shyamjvs** [comment]
For one, I'm not sure if audit logs have all the information (for e.g latency of the API call) and I'm also not sure if all information is meant to be part of audit logs.
Secondly, not all calls may be audited. You pointed out about read-only ones, but there can be other cases too. For e.g
- some lost audit events (though this shouldn't ideally happen with audit logs)
- preferentially neglecting some high-volume low-risk audit logs (even for write operations) - can't remember exactly but I think there's should be an issue for this somewhere (@liggitt may know better)

In general, I'm not convinced that we should be mixing the goals of 'auditing' and 'debugging' (as each's requirements may change independently in time).

**Comment by wojtek-t** [comment]
> some lost audit events (though this shouldn't ideally happen with audit logs)

we may also lose debug logs - at least in theory audit logs should have higher SLO

> preferentially neglecting some high-volume low-risk audit logs (even for write operations) - can't remember exactly but I think there's should be an issue for this somewhere (@liggitt may know better)

That was my point about read-only requests (in most cases, probably reading secrets should be audited too).

> In general, I'm not convinced that we should be mixing the goals of 'auditing' and 'debugging' (as each's requirements may change independently in time).

We should change goals of auditing to facilitate debugging. But if they solve the problem, we should do the same thing twice.
The main question is whether they solve (which it seems it may not be the case).

**Comment by wojtek-t** [comment]
Anyway - I think that we should start with changing configs for our tests to avoid loosing our ability for debugging tests, and we can discuss config for prod clusters in the meantime.

**Comment by shyamjvs** [comment]
I think we can close this issue as we've fixed this for our scalability tests and no active production-related concerns have been raised for more than a release now. Reopen if needed.

/remove-lifecycle stale
/close
