### ISSUE TITLE
Conflict validation on kubeproxyconfig.HealthzBindAddress/MetricsBindAddress and flags

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#62479]
**What happened**:
From https://github.com/kubernetes/kubernetes/issues/53754#issuecomment-371092964.

We used to allow using `ip` or `ip:port` in `--healthz-bind-address` and `--metrics-bind-address`. Now the validation on kubeproxyconfig disallow that (it only allows `ip:port`):
https://github.com/kubernetes/kubernetes/blob/dbcb2c9b27c16da8bd35e0f0898af552bb5ba9fd/pkg/proxy/apis/kubeproxyconfig/validation/validation.go#L192-L212. This seems to break backward compatibility for those two flags.

Please comment if I'm missing something.
cc @xiangpengzhao @Avanpourm 

**How to reproduce it (as minimally and precisely as possible)**:
Try `--metrics-bind-address=0.0.0.0` with kube-proxy.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.1688+c2f67c9459499d-dirty", GitCommit:"c2f67c9459499d3ae5d03f6d54ecc4cb05df3e22", GitTreeState:"dirty", BuildDate:"2018-03-26T23:45:13Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xiangpengzhao** [comment]
Tried `--metrics-bind-address=0.0.0.0`, the error is:
`error: KubeProxyConfiguration.MetricsBindAddress: Invalid value: "0.0.0.0": must be IP:port`

and `--metrics-bind-address=0.0.0.0:10249`, the error is:
`error: invalid argument "0.0.0.0:10249" for "--metrics-bind-address" flag: "0.0.0.0:10249" is not a valid IP address`

@MrHohn So maybe we need to loosen `kubernetes/pkg/proxy/apis/kubeproxyconfig/validation/validation.go` and revert #54191 ?

**Comment by MrHohn** [comment]
> So maybe we need to loosen kubernetes/pkg/proxy/apis/kubeproxyconfig/validation/validation.go and revert #54191 ?

Loosen the validation sounds good. #54191 was meant for loosen the validation as well (allowing not just ip, but also ip:port), but for some reason it doesn't work as intended. Would be great to fix that instead of revert :)

**Comment by xiangpengzhao** [comment]
@MrHohn find the root cause of #54191 not working as expected. https://github.com/kubernetes/kubernetes/pull/57672 introduced the regression:
```
-	fs.Var(componentconfig.IPPortVar{Val: &options.config.HealthzBindAddress}, "healthz-bind-address", "The IP address and port for the health check server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
-	fs.Var(componentconfig.IPPortVar{Val: &options.config.MetricsBindAddress}, "metrics-bind-address", "The IP address and port for the metrics server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
+	fs.Var(componentconfig.IPVar{Val: &o.config.HealthzBindAddress}, "healthz-bind-address", "The IP address and port for the health check server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
+	fs.Var(componentconfig.IPVar{Val: &o.config.MetricsBindAddress}, "metrics-bind-address", "The IP address and port for the metrics server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
```

I send a PR https://github.com/kubernetes/kubernetes/pull/62582 to fix the two issues we mentioned in this thread.

**Comment by josdotso** [comment]
I agree @MrHohn:

There's also the issue of IPv6-only:

```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:51:21Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables"
healthzBindAddress: "::"
metricsBindAddress: "::1"
```
Results in:

```
[KubeProxyConfiguration.HealthzBindAddress: Invalid value: "::": must be IP:port, KubeProxyConfiguration.MetricsBindAddress: Invalid value: "::1": must be IP:port]
```

**Comment by MrHohn** [comment]
@josdotso Thanks for your report. Do you mind opening a new issue regarding IPv6 since the original issue was fixed? Thanks.

**Comment by josdotso** [comment]
Sure. Thanks @MrHohn

**Comment by josdotso** [comment]
@MrHohn  Please see: https://github.com/kubernetes/kubernetes/issues/76289
