### ISSUE TITLE
Missing resources in kubectl get/describe--help

### ISSUE THREAD

**Issue by alexxa** [kubernetes/kubernetes#62477]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
1) `kubectl get --help` doesn't list `vms, vmrs and ovms` as resources. But it lists `pods`, for example. Why so? 
2) `vms, vmrs, and ovms` are not listed in `kubectl describe --help` too.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get --help
kubectl describe --help

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Checked for two versions:
1)  Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-01-17T20:11:54Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
2) Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-29T16:29:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
OpenStack instance
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alexxa** [comment]
@kubernetes/sig-cli-bugs
@kubernetes/sig-docs-bugs

**Comment by janetkuo** [comment]
What are `vms`, `vmrs`, and `ovms`? I believe they're not Kubernetes resources.

**Comment by wuhanlin007** [comment]
are vms, vmrs, and ovms kubernetes resources？？ i don't think so

**Comment by alexxa** [comment]
@janetkuo VirtualMachine (vms), Offline VirtualMachine (ovms) and VirtualMachine ReplicaSet (vmrs).

Hm, sorry guys. Those belong to KubeVirt. I will move the issue.
