### ISSUE TITLE
Privilige escalation issue with Service account token

### ISSUE THREAD

**Issue by lonial** [kubernetes/kubernetes#62488]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig auth
> /kind feature

What happened: Tiller (installation entity) User is requesting k8s API to create pod but that pod's chart refers to service account token of tiller (installation entity) itself in its chart. When I am reviewing the code of below file when we are reading service account token in this method getServiceAccount and we are not checking that service account requested by user in chart is the service account token of tiller user itself. We can argue that this issue is tiller issue but I think we should check in admission plugin that User which is requesting installation of pod cannot refer to its service account token. 

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/serviceaccount/admission.go 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
> I think we should check in admission plugin that User which is requesting installation of pod cannot refer to its service account token

Service accounts are not treated as special users... they can be given permissions to make API requests just like any other user. 

If you don't want tiller users to be able to request pod creation in the tiller namespace, or using the tiller serviceaccount, that needs to be enforced within tiller itself.

There are broader issues with enforcing permissions and avoiding escalation issues with Helm and Tiller that are discussed in https://github.com/kubernetes/helm/issues/1918 and I think are planned to be addressed in helm 3 (see https://github.com/kubernetes/helm/issues/1918#issuecomment-378700824 and https://github.com/kubernetes-helm/community/blob/master/helm-v3/007-security.md)

/close
