### ISSUE TITLE
DNS configMap tests are failing in serial CI

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#62490]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind e2e-test-failure 
/priority failing-test 
/sig network

**What happened**:
From http://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-serial&width=20,  DNS configMap tests are failing since https://github.com/kubernetes/kubernetes/pull/62042 was merged with below error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_configmap.go:38
You may only call BeforeEach from within a Describe or Context
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:141
```

@grayluck

**Comment by grayluck** [comment]
Working on it.

**Comment by MrHohn** [comment]
https://k8s-testgrid.appspot.com/sig-network-gke#gci-gke-serial&width=20
Seems like it is now passing on gce but failing on gke :/
/reopen

**Comment by MrHohn** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/62698.
