### ISSUE TITLE
`kubectl get --all-namespaces` doesn't show namespace 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#62507]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Running a local cluster (`hack/local-up-cluster.sh`) from HEAD (daca510a4818e31f8e3678185a4f7af7c9b8319e) (both kubectl and server are from HEAD):

```console
$ kubectl get pods --all-namespaces 
NAMESPACE   NAME                       READY     STATUS    RESTARTS   AGE
            kube-dns-ffd85c78c-6frzd   3/3       Running   0          5m
```

**What you expected to happen**:

Namespace should be shown like this:

```console
$ kubectl get pods --all-namespaces 
NAMESPACE       NAME                       READY     STATUS    RESTARTS   AGE
kube-system     kube-dns-ffd85c78c-6frzd   3/3       Running   0          5m
```

/sig cli

**Comment by dims** [comment]
kubectl from 1.10 seems to work fine. So we regressed after 1.10.0 got released

**Comment by nikhita** [comment]
Dupe of https://github.com/kubernetes/kubernetes/issues/62059.

**Comment by nikhita** [comment]
Closing in favour of https://github.com/kubernetes/kubernetes/issues/62059.
/close
