### ISSUE TITLE
In a local cluster running HEAD, `kubectl version` shows 1.10 instead of 1.11

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#62506]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Using a local cluster (`hack/local-up-cluster.sh`) from HEAD, `kubectl version` showed `1.10+`.

```console
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0.2431+daca510a4818e3-dirty", GitCommit:"daca510a4818e31f8e3678185a4f7af7c9b8319e", GitTreeState:"dirty", BuildDate:"2018-04-13T01:19:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.0.2431+daca510a4818e3-dirty", GitCommit:"daca510a4818e31f8e3678185a4f7af7c9b8319e", GitTreeState:"dirty", BuildDate:"2018-04-13T01:19:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**What you expected to happen**: 

It should show `1.11+`.

**Comment by janetkuo** [comment]
I don't think it's a cli bug, because `kubectl version` just grab information from `/version` endpoint. Not sure where "version" is populated from, though.

**Comment by dims** [comment]
@janetkuo the build harness figures out the version from git info. looks like something has not yet been updated

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ hack/print-workspace-status.sh
STABLE_BUILD_GIT_COMMIT 06c5afe275869de3f4630592b54cc16066081084
STABLE_BUILD_SCM_STATUS clean
STABLE_BUILD_SCM_REVISION v1.10.0-beta.0.2448+06c5afe275869d
STABLE_BUILD_MAJOR_VERSION 1
STABLE_BUILD_MINOR_VERSION 10+
STABLE_DOCKER_TAG v1.10.0-beta.0.2448_06c5afe275869d
gitCommit 06c5afe275869de3f4630592b54cc16066081084
gitTreeState clean
gitVersion v1.10.0-beta.0.2448+06c5afe275869d
gitMajor 1
gitMinor 10+
buildDate 2018-04-13T13:00:50Z
```

**Comment by david-mcmahon** [comment]
@janetkuo Can you repro this in a clean/new git clone of the repo?

**Comment by david-mcmahon** [comment]
Thanks.  I suspect this was due to having an older copy of the repo.  There were some tagging issues around 1.10/1.11 that got resolved, but its possible a repo that was synced prior to the trouble could still have tags on the wrong commits.
