### ISSUE TITLE
Constructor for Unstructured[List]

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#62500]
Follow up on https://github.com/kubernetes/kubernetes/pull/62063 - add a constructor that optionally validates that the contents of unstructured are only valid JSON types. See https://github.com/kubernetes/kubernetes/pull/62063#issuecomment-378430512.

/kind feature
/sig api-machinery
/assign

FYI @sttts

**Comment by sttts** [comment]
Wished we had a language with a type system powerful enough to express the types, e.g. via union types.
