### ISSUE TITLE
Error from server: error dialing backend: dial tcp 192.168.1.14:10250: getsockopt: no route to host

### ISSUE THREAD

**Issue by xinjt** [kubernetes/kubernetes#62511]
here is my situation,
[root@k8s-master kube]# kubectl get pod nginx-6bcd55cfd6-5n5rf -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP           NODE
nginx-6bcd55cfd6-5n5rf   1/1       Running   0          46m       10.244.7.7   k8s-node2
[root@k8s-master kube]# kubectl exec -it nginx-6bcd55cfd6-5n5rf /bin/bash
Error from server: error dialing backend: dial tcp 192.168.1.14:10250: getsockopt: no route to host
[root@k8s-master kube]# kubectl logs nginx-6bcd55cfd6-5n5rf 
Error from server: Get https://192.168.1.14:10250/containerLogs/default/nginx-6bcd55cfd6-5n5rf/nginx: dial tcp 192.168.1.14:10250: getsockopt: no route to host

what is wrong?

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wuhanlin007** [comment]
it is error of your docker

**Comment by dims** [comment]
/close

Please post your question to stackoverflow (https://stackoverflow.com/questions/tagged/kubernetes)

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.

**Comment by Khaja514** [comment]
I am also facing same issue when i am trying to connect my pod using eks kubectl.

$ kubectl exec -it delegate-portal-5f669855f9-82drh bash
Error from server: error dialing backend: dial tcp XXXXXXX:10250: getsockopt: connection refused

$kubectl logs delegate-portal-5f669855f9-82drh
Error from server: Get https://1XXXXXX:10250/containerLogs/default/delegate-portal-5f669855f9-82drh/delegate-portal: dial tcp 1XXXXXX:10250: getsockopt: connection refused

**Comment by qgicup** [comment]
Any solution so far? Experiecing the same problem here

**Comment by Khaja514** [comment]
It got rectified to me after many attempts
but trying to figure it out how it got rectified.

Downgraded some network level plugin image in eks service

**Comment by james-knott** [comment]
@Khaja514 Can you share how you resolved the problem?

**Comment by stopsopa** [comment]
Any help?
