### ISSUE TITLE
Ask kubelet authentication certificate deadline problem?

### ISSUE THREAD

**Issue by chenfanlinux** [kubernetes/kubernetes#62533]
Hello,everybody!
Encounter the following problem, kubelet generated two certificates, one certificate kubelet.crt certificate for a period of one year, how do you configure, modify the certificate period。

**Comment by liggitt** [comment]
The period of the self-generated certificate is not configurable. 

If you are using the self-generated certificates, you can simply delete them and they will be regenerated on next start.

 If you are using client cert rotation, the kubelet will re-request new CSRs prior to expiration. 

If your cluster setup created the certificates, it is responsible for updating/refreshing them

/kind support
/close
