### ISSUE TITLE
A question about the automatic update of deployment with kubernetes 1.9

### ISSUE THREAD

**Issue by kirsazlid** [kubernetes/kubernetes#62532]
**What happened**:
Two servers, one master, one node. I get a deployment or pod named 'system' running on the node, whose image comes from my personnal docker repository and name is  '192.168.10.1:10001/microservice/test/system'. The default tag of this image is 'latest', if the repository has a newer version of image and I pull it into the node, then the former image's tag becomes '<none>' and the newer's tag is 'latest'.
I set 'imagePullPolicy' to 'Always' in yaml file on master, creating the deployment, the node will automatically pull the image and run the pod, the image's tag is 'latest', now I get a newer version of image in my repository and I want to control the master to update the deployment with the newer image. 
What's the best way to update the deployment? I've tried 'kubectl replace, kubectl set image and etc', useless, the node won't pull the newer image. Now I just delete the deployment and recreate it, it works, but I don't think this is the best updating way. 
Thanks for attention~

**What you expected to happen**:
Updating the deployment directly instead of deleting it and recreate it

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
CentOS 7.3

**Comment by Davidrjx** [comment]
@kirsazlid , as k8s's deployment rolling update, set image should be invalid. if useless, an cause may be lie in two images'tag setup where one is none and the other is latest in your case. you can make a try to assign individual tag respectively, then set image

**Comment by Davidrjx** [comment]
@kirsazlid , as k8s's deployment rolling update, set image should be valid. if useless, an cause may be lie in two images'tag setup where one is none and the other is latest in your case. you can make a try to assign individual tag respectively, then set image
