### ISSUE TITLE
read-only RBD images can't be mounted multiple times

### ISSUE THREAD

**Issue by pavel-citymaps** [kubernetes/kubernetes#62564]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I created a deployment with 2 replicas mounting an rbd backed PVC. The PVC was ReadOnlyMany with proper "readOnly: true" settings specified. Only 1 pod in the deployment ran. The other received a "timeout expired waiting for volumes to attach/mount" message.
**What you expected to happen**:
I expect the rbd volume to be mounted read-only multiple times and the all replicas to be available.
**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment with 2 replicas that mounts an rbd volume readOnly.

**Anything else we need to know?**:
I've looked through the code a bit and it looks like kubelet is always checking rbdStatus to see if the volume is already mounted. There should be an exception to this when readOnly option is specified.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):
Centos 7
- Kernel (e.g. `uname -a`):
4.14.15
- Install tools:
- Others:

**Comment by nikhita** [comment]
/remove-lifecycle stale

@xiaoxubeii does https://github.com/kubernetes/kubernetes/pull/63424 fix this issue as well? is this safe to be closed?

**Comment by xiaoxubeii** [comment]
@nikhita Yes, it is already fixed. I will close it.
