### ISSUE TITLE
Feature request: Support adding HostAliases from ConfigMap

### ISSUE THREAD

**Issue by tangblue** [kubernetes/kubernetes#62579]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
According to the following kubernetes document, the host entries can be added to Pod /etc/hosts with HostAliases. 
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

With ConfigMap, the configuration artifacts can be decoupled from image content. But the HostAliases can not  be set by ConfigMap. It makes the custom host entries can be only set in the image content.

**What you expected to happen**:
Add new field(e.g. hostAliasesFrom) in PodSpec and the custom host entries can be added by the Pod's .spec.hostAliasesFrom which is a reference of a ConfigMap key.

**Comment by smarterclayton** [comment]
Can’t you mount a configmap at /etc/hosts with a subpath?  That’s more in line with the customization to control this that I would expect.

**Comment by tangblue** [comment]
/etc/hosts is created by kubernetes runtime. It seems like mounting ConfigMap at /etc/hosts is not a safe way.

**Comment by Prussia** [comment]
What is the final solution for it?
