### ISSUE TITLE
Move the network setup back into kubelet using a gRPC-style interface

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/kubernetes#62574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

CNI APIs are understood by a kubelet built-in module,  the Kubernetes network driver, which is is linked, compiled, built, and shipped with kubelet. Third party network plugins have to provide executable CNI plugin binaries and a network configuration file. This is undesirable for many reasons:

* CNI is coupled with Kubernetes and Kubernetes needs to bump its version once CNI releases a new version.
* Users may want extensibility beyond just CNI.

* Added bunch of CNI and network related flags to kubelet: cni-bin-dir, cni-conf-dir, hairpin-mode, network-plugin-mtu etc.

* Network plugins require write access to the root filesystem of the nodes in order to provide CNI plugin binary and network configuration file.

* Some third-party CNI plugins are oneshots and do not necessarily run as daemon processes, it is difficult for them to cleanly manage network configuration state, e.g. hostports.
* Kube-proxy as a service driver is keeping doing so many low-level things, e.g. handle nodes with iptables FORWARD DROP which is configured by docker in recent versions. It would be better if CNI plugins can handle it and make the network driver and service "driver" be closer to each other.

**What you expected to happen**:

We propose to migrate CNI driver out of kubelet and run as a daemon, which can translate kubelet’s network RPC calls to CNI APIs. The primary motivation is to decouple CNI from Kubernetes.

By doing this, we can

- Use kube-specific mechanisms to manage plugins (consistent with most other plugins).
- Move some more net configurations out of kubelet.
- Move the kubernetes network driver codes out of tree.
- Move portmap from kubenet to CNI driver, which is one of sub-tasks of kubenet deprecation.
- Make Kube-proxy focus on service proxy and keep it simple.
- Vector to move network plugins and service configurators (kube-proxy) closer together for more optimal setup. For example, there are places where kube-proxy could do better configuration if it had access to information that only the CNI drivers know, e.g. the name that veth interfaces are given or the correct CIDRs for pods on that node.

We propose to abstract a explicit layer of network driver and run it as a gRPC server since it puts less responsibility on network plugin writers to make something that is "kubernetes specific".

**Design Overview**:

A new network driver will be introduced within Kubernetes, say `kni`. It is a daemon running in background and is responsible for capturing all the RPCs from kubelet and handle it or call CNI plugin binaries. Specifically, the API calls from the new `kni` network driver will be converted to corresponding gRPCs via a unix domain socket on each node, which means we can deploy the `kni` network driver as DaemonSet.

When the new network driver becomes mature, we can mark the `cni` network driver deprecated.

**gRPC interface**

We just need to convert the functions in `NetworkPlugin` [interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/plugins.go#L47-L76) to network plugins for the kubelet to gPRCs. The gRPC service might look like,

```
service CNIService {
    // SupportVersion to check version support or not
    // return true or false
    rpc SupportVersion(SupportVersionRequest) returns (SupportVersionResponse){}
    // Status to check cniDriver status, config synced/plugin capabilities
    rpc Status(StatusRequest) returns (StatusResponse) {}
    rpc SetUpPod(SetUpPodRequest) returns (SetUpPodResponse) {}
    rpc TearDownPod(TearDownPodRequest) returns (TearDownPodResponse) {}
    ...
}
```

/sig network
/sig node

@thockin @dchen1107 @dcbw @caseydavenport @squeed  @freehan @yujuhong @bowei @jingax10 @Lion-Wei

**Comment by dims** [comment]
@m1093782566 this is clearly a lot of work cutting across at least 2 sigs. probably better to start in the features repo i think ( cc @idvoretskyi @justaugustus )

**Comment by m1093782566** [comment]
@dims 

It's a big feature and I think we should discuss it a bit before starting it in the feature repo.

**Comment by idvoretskyi** [comment]
@dims definitely! Please, negotiate the discussion and if you are planning this feature to land in 1.11 release, don't forget about the features freeze coming on April 24th https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release-1.11.md

**Comment by yujuhong** [comment]
I'd like to clarify a few things. The built-in network plugin code, though technically is compiled as pat of kubelet, belongs to the sub-package "dockershim" (I recently cleaned up the code to make it clear in #62212). Dockershim is just one CRI implementation, and we keep it in tree for backward compatibility reasons. With CRI, kubelet does *not* interact with network plugins at all -- these are all handled by the container runtime now.

Therefore, the gRPC interface proposed here will need to be adopted by the container runtimes (not kubelet). Is this the goal or the proposal actually aims at moving the networking setup from the runtime back to kubelet?

**Comment by m1093782566** [comment]
@yujuhong 

Thanks for your clarification.

> The built-in network plugin code, though technically is compiled as part of kubelet, belongs to the sub-package "dockershim" (I recently cleaned up the code to make it clear in #62212). 

My opinion is that we should discuss whether network should be in kubelet or in CRI implementation(e.g. dockershim) although the network plugin codes live in dockershim now.

Because network is remote, pluggable and more opaque, it might be possible to move the network setup back into kubelet using a gRPC-style interface, which would make ALL runtimes easier and decouple the CRI implementation and the network setup.
