### ISSUE TITLE
kubeadm init v1.10.0 hangs dial tcp 192.168.0.7:6443: getsockopt: connection refused

### ISSUE THREAD

**Issue by lizcly** [kubernetes/kubernetes#62575]
Apr 14 13:24:01 k8scluster-master kubelet[21772]: E0414 13:24:01.019782   21772 certificate_manager.go:231] Reached backoff limit, still unable to rotate certs: timed out waiting for the condition
Apr 14 13:24:01 k8scluster-master kubelet[21772]: E0414 13:24:01.022122   21772 event.go:209] Unable to write event: 'Post https://192.168.0.7:6443/api/v1/namespaces/default/events: dial tcp 192.168.0.7:6443: getsockopt: connection refused' (may retry after sleeping)
Apr 14 13:24:01 k8scluster-master kubelet[21772]: E0414 13:24:01.354405   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:01 k8scluster-master kubelet[21772]: E0414 13:24:01.357143   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:01 k8scluster-master kubelet[21772]: E0414 13:24:01.367286   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:02 k8scluster-master kubelet[21772]: E0414 13:24:02.355395   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:02 k8scluster-master kubelet[21772]: E0414 13:24:02.357866   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:02 k8scluster-master kubelet[21772]: E0414 13:24:02.368047   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:02 k8scluster-master kubelet[21772]: E0414 13:24:02.752444   21772 eviction_manager.go:246] eviction manager: failed to get get summary stats: failed to get node info: node "k8scluster-master" not found
Apr 14 13:24:02 k8scluster-master kubelet[21772]: W0414 13:24:02.762681   21772 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 14 13:24:02 k8scluster-master kubelet[21772]: E0414 13:24:02.763708   21772 kubelet.go:2125] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Apr 14 13:24:03 k8scluster-master kubelet[21772]: E0414 13:24:03.356284   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:03 k8scluster-master kubelet[21772]: E0414 13:24:03.358437   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:03 k8scluster-master kubelet[21772]: E0414 13:24:03.368704   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:04 k8scluster-master kubelet[21772]: I0414 13:24:04.128930   21772 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
Apr 14 13:24:04 k8scluster-master kubelet[21772]: I0414 13:24:04.131404   21772 kubelet_node_status.go:82] Attempting to register node k8scluster-master
Apr 14 13:24:04 k8scluster-master kubelet[21772]: E0414 13:24:04.132007   21772 kubelet_node_status.go:106] Unable to register node "k8scluster-master" with API server: Post https://192.168.0.7:6443/api/v1/nodes: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:04 k8scluster-master kubelet[21772]: E0414 13:24:04.356859   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:04 k8scluster-master kubelet[21772]: E0414 13:24:04.359008   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:04 k8scluster-master kubelet[21772]: E0414 13:24:04.369175   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:05 k8scluster-master kubelet[21772]: E0414 13:24:05.357404   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:05 k8scluster-master kubelet[21772]: E0414 13:24:05.359571   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:05 k8scluster-master kubelet[21772]: E0414 13:24:05.369739   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:06 k8scluster-master kubelet[21772]: E0414 13:24:06.358179   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.0.7:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:06 k8scluster-master kubelet[21772]: E0414 13:24:06.360054   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.0.7:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
Apr 14 13:24:06 k8scluster-master kubelet[21772]: E0414 13:24:06.370273   21772 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.0.7:6443/api/v1/nodes?fieldSelector=metadata.name%3Dk8scluster-master&limit=500&resourceVersion=0: dial tcp 192.168.0.7:6443: getsockopt: connection refused
^C

**Comment by dims** [comment]
Can you please move this issue to https://github.com/kubernetes/kubeadm/issues?

/close
