### ISSUE TITLE
_output/bin/deepcopy-gen: Permission denied

### ISSUE THREAD

**Issue by chenyangguang** [kubernetes/kubernetes#62577]
1. I follow the readme.md  method like this

(1) $ go get -d k8s.io/kubernetes
(2) $ cd $GOPATH/src/k8s.io/kubernetes
(3) $ make 

2. But third step appear wrong like:

  ```➜  kubernetes git:(master) make
./hack/run-in-gopath.sh: line 33: _output/bin/deepcopy-gen: Permission denied
make[1]: *** [Makefile.generated_files:246: gen_deepcopy] Error 1
make: *** [Makefile:483: generated_files] Error 2
```

3. My env  is  in the latest docker archlinux image.

(1) sys: 
`
Linux 88295ee782e0 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 GNU/Linux`

(2)  docker version

```➜  kubernetes git:(master) docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.10
 Git commit:	0520e24302
 Built:	Fri Mar 23 01:47:41 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?```

(3) go env

```➜  kubernetes git:(master) go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build168012375=/tmp/go-build -gno-record-gcc-switches"```

**Comment by chenyangguang** [comment]
it was because Permission, I have fix it by add permission. i will close this issue.

**Comment by chenyangguang** [comment]
I had fix it by 

```
chomd +x  $GOPATH/src/k8s.io/kubernetes/_output/bin/deepcopy-gen

**Comment by idealhack** [comment]
I run into the same problem on Arch Linux and I think this can be fixed in script.

/assign

**Comment by ifosch** [comment]
I am a new contributor and I am having this same issue. I got the following output when running `make test` on master:
```
+++ [1013 01:03:00] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
find: ‘rsync’: No such file or directory
find: ‘rsync’: No such file or directory
find: ‘rsync’: No such file or directory
find: ‘rsync’: No such file or directory
./hack/run-in-gopath.sh: line 33: _output/bin/deepcopy-gen: Permission denied
Makefile.generated_files:152: recipe for target 'gen_deepcopy' failed
make[1]: *** [gen_deepcopy] Error 1
Makefile:521: recipe for target 'generated_files' failed
make: *** [generated_files] Error 2
```
When I `chmod +x` the file, which is empty, and run `make test` again fails to run another empty file. This happens a few times.
I think I am not missing any build tool required.
I might look into this if needed.
@idealhack any advance on fixing the scripts?

**Comment by ifosch** [comment]
Apparently I needed to install rsync, so the `No such file or directory` errors vanished, but I still get the `Permission denied` ones.

**Comment by idealhack** [comment]
@ifosch I haven’t got time to fix it. Feel free to give it a try and discuss about it here :)

**Comment by ifosch** [comment]
I might find the solution today, but I'm uncertain, since I can't reproduce it anymore:
1. I ensured rsync was installed in my system (`apt-get install -y rsync`)
2. I ran `make clean` and `make clean_generated`
3. `make test` started working

Please, @idealhack and @chenyangguang, can you check if this works for you?

**Comment by idealhack** [comment]
It seems I only encountered these kinds of issues on Arch, not Ubuntu.

I’ll try it again on fresh systems for both.

**Comment by ifosch** [comment]
I am using Debian, which doesn't bring rsync by default; I am not sure about Ubuntu.
About the tests, it seems to be working, except for I got errors on the tests on master.
Running `make` works without errors and, apparently, well, though I'm unsure on how to check its results.

**Comment by ifosch** [comment]
I did a mistake in my last commit... this issue should not be closed, at least, until it's not validated
