### ISSUE TITLE
Unable to delete ContainerCreating pod?

### ISSUE THREAD

**Issue by xikunyang** [kubernetes/kubernetes#62580]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

Unable to delete ContainerCreating pod

**What you expected to happen**:

Delete ContainerCreating pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

CentOS 7

- Kernel (e.g. `uname -a`):

3.10.0-693.21.1.el7.x86_64

- Install tools:
- Others:

![1523713792372](https://user-images.githubusercontent.com/36947547/38768980-11c5afda-402e-11e8-898d-ef38c04a3058.jpg)

**Comment by wenlxie** [comment]
The namespace not specificed?
`kubectl delete pod **** -n kube-system` ?

**Comment by dims** [comment]
yep specifying the namespace should work. please reopen if it does not

/close

**Comment by xikunyang** [comment]
Thanks for quickly reply.
I can delete the pod with namespace. But the pod will auto restart immediately. How can I stop it?
