### ISSUE TITLE
A question about customresourcedefinition.Generation in k8s v1.9.2

### ISSUE THREAD

**Issue by occia** [kubernetes/kubernetes#62595]
**What happened**:
I'm using k8s v1.9.2 and trying to develop a CustomResourceDefinition Controller. And I found that the crd's Generation field, which is defined in CRD.ObjectMeta.Generation, consistently be 0 regardless of the changes of CRD.Spec.SOMEFIELD.

**What you expected to happen**:
When CRD.Spec.SOMEFIELD changed, the CRD.Generation should be incremented.

**Anything else we need to know?**:
Is this a normal behavior or means sth maybe wrongly configured in my k8s?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- OS (e.g. from /etc/os-release): centos 7
- Install tools: kubeadm

**Comment by nikhita** [comment]
> I'm using k8s v1.9.2 and trying to develop a CustomResourceDefinition Controller. And I found that the crd's Generation field, which is defined in CRD.ObjectMeta.Generation, consistently be 0 regardless of the changes of CRD.Spec.SOMEFIELD.

Do you mean the CRD here or the instance of the CRD i.e. custom resource here?

The `metadata.generation` for the CRD is incremented as the spec changes.

For 1.9.2, the `metadata.generation` for the custom resource will _not_ change as the spec changes. It is available only from 1.10.

See https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#subresources on how to enable the subresource feature. `metadata.generation` will increment as expected if you enable the status subresource.

**Comment by occia** [comment]
Well, your answer really helps me, thanks :)
