### ISSUE TITLE
[Umbrella issue] Improve compute resource APIs

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#62598]
This issue is meant to track all feature requests that fall into the category of improving existing compute resource APIs.
Some of the initial reasons for improving compute APIs are:
1. Providing per-device quota while not-compromising workload portability across compatible devices.
2. Enabling per-device billing while not-compromising workload portability across compatible devices.
3. Enabling compute resource consumption via metadata of resources like "minimum CPU version", "minimum GPU memory", etc.

[This doc](https://docs.google.com/document/d/1Lpuw-tjm252W4oGqBvcFAFUZkwFlpZ2i0EgpCwialN0/edit?usp=sharing) provides more use cases for improving compute APIs.

This was discussed in the most recent [Resource Management Working Group meeting](https://docs.google.com/document/d/1Df6uGCzGleAhRQYZ20v55U1YCBLfxV4PJh0CIWcMHkk/edit#heading=h.2ltjzba8ef5v).

The most promising design as of now is that of introducing separate API objects one to represent a concrete compute resource and the other to represent policy/grouping around concrete objects (similar to Storage classes). This design is yet to be fully spec'd out.

Design docs: 

* [Resource Class Proposal](https://docs.google.com/document/d/1qKiIVs9AMh2Ua5thhtvWqOqW0MSle_RV3lfriO1Aj6U) 
* [Alternate Resource Class Proposal](https://docs.google.com/document/d/1666PPUs4Lz56TqKygcy6mXkNazde-vwA7q4e5H92sUc)

There are other features that could in theory be a part of the Resource APIs design:
1. Cluster level resources - This could be a separate type of concrete compute resource that is different from Node level concrete compute resources. https://github.com/kubernetes/community/pull/1400 attempts to tackle cluster level resources differently. This feature is yet to be fully understood. 
2. Network Resources - Kubernetes is currently attempting to introduce support for additional networks via the [Network plumbing WG](https://groups.google.com/forum/#!topic/kubernetes-sig-network/ANAjTyqVosw). Certain use cases for networking have node level devices (Infiniband) along with scheduling restrictions which could possibly be represented via the new resource APIs. This is a very early idea lacking rigorous thinking.
 
As of now the priority is to focus on the initial use cases of quota, chargeback and developer productivity as mentioned in the [use cases doc](https://docs.google.com/document/d/1Lpuw-tjm252W4oGqBvcFAFUZkwFlpZ2i0EgpCwialN0/edit?usp=sharing). 

cc @kubernetes/sig-node-feature-requests @kubernetes/sig-scheduling-feature-requests

**Comment by vishh** [comment]
https://github.com/kubernetes/kubernetes/pull/61775 is another use case that could in theory be satisfied by compute resources. If a vendor wants to pass additional metadata to device plugins, they could do that by adding annotations to concrete compute resources which the plugins can have access to. Cluster admins can restrict who can update concrete compute resources via RBAC (assuming concrete resources are separate API objects and not embedded into the node object).

**Comment by vikaschoudhary16** [comment]
annotations on compute resources might be helpful for FPGA cases(@kad or @bart0sh can confirm), but unfortunately it is not useful for network device plugin case.
