### ISSUE TITLE
kube-controller-manager address flag deprecated but defaults still being applied

### ISSUE THREAD

**Issue by AshleyByeUK** [kubernetes/kubernetes#62599]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`kube-controller-manager.service` fails to start due to an address already being bound to port 10252.
`--address` and `--port` flags not being used as shown as deprecated, using `--bind-address` and `--secure-port` flags. However, it is binding to `0.0.0.0:10252` - terminal copy of `journalctl -xe`:

```
0415 18:34:26.848200    3062 flags.go:27] FLAG: --address="0.0.0.0"
0415 18:34:26.848303    3062 flags.go:27] FLAG: --allocate-node-cidrs="false"
0415 18:34:26.848326    3062 flags.go:27] FLAG: --allow-untagged-cloud="false"
0415 18:34:26.848342    3062 flags.go:27] FLAG: --allow-verification-with-non-compliant-keys="false"
0415 18:34:26.848361    3062 flags.go:27] FLAG: --alsologtostderr="false"
0415 18:34:26.848379    3062 flags.go:27] FLAG: --attach-detach-reconcile-sync-period="1m0s"
0415 18:34:26.848399    3062 flags.go:27] FLAG: --bind-address="10.240.0.11"
```

**What you expected to happen**:
Expected behaviour of deprecated `--address` flag to not bind service to `0.0.0.0` but for IP given in `--bind-address` to be used instead.

**How to reproduce it (as minimally and precisely as possible)**:
```
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-controller-manager \
  --bind-address={{ hostvars[inventory_hostname]['ansible_host'] }} \
  --cluster-cidr={{ cluster_ip }}/{{ cluster_cidr }} \
  --cluster-name=kubernetes \
  --cluster-signing-cert-file=/var/lib/kubernetes/ca.pem \
  --cluster-signing-key-file=/var/lib/kubernetes/ca-key.pem \
  --leader-elect=true \
  --master=http://{{ hostvars[inventory_hostname]['ansible_host'] }}:8080 \
  --root-ca-file=/var/lib/kubernetes/ca.pem \
  --secure-port=10252 \
  --service-account-private-key-file=/var/lib/kubernetes/ca-key.pem \
  --service-cluster-ip-range={{ service_cluster_ip }}/{{ service_cluster_cidr }} \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-116-generic
- Install tools:
- Others:

**Comment by opsnull** [comment]
same problem here.
