### ISSUE TITLE
Kubernetes federation - unable to init the federation control plane

### ISSUE THREAD

**Issue by mmeliani** [kubernetes/kubernetes#62596]
I am working on creating a federation with three clusters. The host cluster spin up but I am not able to init the federation successfully.

```
kubefed init Inkubefed --host-cluster-context=default-context --dns-provider="coredns" --dns-zone-name="example.com." --dns-provider-config="/root/coredns-provider.conf"
Creating a namespace federation-system for federation system components... done
Creating federation control plane service...............................................................................
....................................................................... 
```
The "creating federation control place service step takes a lot of time and didn't stop loading unless i forced it"

The host cluster has 3 controllers and 2 workers and some egdes;

I'm using coredns as DNS provider : I followed exactly the instructions available here : https://kubernetes.io/docs/tasks/federation/set-up-coredns-provider-federation/ ; coredns and etcd operator are up and running ! NB : i have also a kubedns service running on my cluster
```
cat coredns-provider.conf 
[Global]
etcd-endpoints = http://etcd-cluster.my-namespace:2379
zones = example.com.
coredns-endpoints = 172.16.1.12:30630
```

Kubernetes version : 1.9.2 kubefed version : v1.9.0-alpha.3 Any hints please where am I going wrong ?

**Comment by quinton-hoole** [comment]
@mmeliani Best to post these kinds of questions on StackOverflow, the multicluster mailing list, or slack.
