### ISSUE TITLE
WaitForAttach may fail for aws_ebs

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#62613]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When I am fixing [WaitForAttach failure](https://github.com/kubernetes/kubernetes/pull/62612) in azure_dd, I also find there could be same issue for aws_ebs, below are the context:
From v1.10, `devicePath` will be updated due to following code change:
https://github.com/kubernetes/kubernetes/blob/568afb4ecca99bc3b54fddc20927b3713369d357/pkg/volume/util/operationexecutor/operation_generator.go#L517-L518

The GCE disk won't have this issue since `devicePath` is not used in [WaitForAttach func](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/attacher.go#L133), while aws disk is also using `devicePath`  in [WaitForAttach func](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/aws_ebs/attacher.go#L145), I think there is potentical issue for aws_ebs

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig aws

**Comment by jingxu97** [comment]
@gnufied I think aws should be ok since it verify devicePath. But there is some confusion about the devicePath, maybe we should add more comments about it.

**Comment by andyzhangx** [comment]
Paste my code analysis here:
@jingxu97 @gnufied 
 - In the beginning, `devicePath` is a LUN number(e.g. 0, 1, 2...) returned by azure_dd.Attach func, then `WaitForAttach` will use `findDiskByLun` to return real device path(e.g. in Linux, it could be `/dev/disk/azure/scsi1/lun0`):
https://github.com/kubernetes/kubernetes/blob/bf3cda66c3664dd874c8f2e41a99cbab96e74b89/pkg/volume/azure_dd/attacher.go#L182
 - Then `devicePath`(`/dev/disk/azure/scsi1/lun0`) will be updated by `actualStateOfWorld.MarkDeviceAsMounted`:
https://github.com/kubernetes/kubernetes/blob/568afb4ecca99bc3b54fddc20927b3713369d357/pkg/volume/util/operationexecutor/operation_generator.go#L517-L518
so in the second time of `WaitForAttach` func invocation, `devicePath` becomes `/dev/disk/azure/scsi1/lun0` in Linux node now, then we will get error in azure_dd

I think same logic would happens in aws_ebs.WaitForAttach func, although it uses `verifyDevicePath(devicePaths)` since in the first and second time invocation of `WaitForAttach` func, `devicePath` value has been changed.
