### ISSUE TITLE
List CRDs in `kubectl --help`

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#62626]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**: `kubectl --help` does not list crds.
But OTOH `kubectl get $CRD` works

**What you expected to happen**: `kubectl --help` includes a list of crds and eventuall descriptive informations.

**How to reproduce it (as minimally and precisely as possible)**:
Call `kubectl --help`

**Comment by liggitt** [comment]
--help output does not require an active server connection

`kubectl api-resources` will contact the server and display all available resources

/close
