### ISSUE TITLE
How to get kubelet_volume* metrics working?

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#62644]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

/kind bug

**What happened**: I am trying to get `kubelet_volume_*` metrics working. According this https://github.com/google/cadvisor/issues/1702#issuecomment-344324219 there should be support after 1.8 kube. However, I am now using kube 1.10.1 and still I cannot see anything in `/metrics`? Should these be there or not?

``` 
[root@kube-dev-node-1-1 log]# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 192.168.18.9  netmask 255.255.255.0  broadcast 192.168.18.255
        inet6 fe80::f816:3eff:fe4f:a183  prefixlen 64  scopeid 0x20<link>
        ether fa:16:3e:4f:a1:83  txqueuelen 1000  (Ethernet)
        RX packets 9409  bytes 4087711 (3.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8731  bytes 4873482 (4.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@kube-dev-node-1-1 log]# curl -s https://192.168.18.9:10250/metrics -k|grep kubelet_volume|wc -L
0
[root@kube-dev-node-1-1 log]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/vda1                 11G  1.9G  8.1G  19% /
devtmpfs                 1.9G     0  1.9G   0% /dev
tmpfs                    1.9G     0  1.9G   0% /dev/shm
tmpfs                    1.9G  9.7M  1.9G   1% /run
tmpfs                    1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mapper/misc-docker   15G   47M   14G   1% /var/lib/docker
tmpfs                    1.9G   12K  1.9G   1% /var/lib/kubelet/pods/b79edabb-416a-11e8-9f3d-fa163e02c5d3/volumes/kubernetes.io~secret/default-token-hvf4r
tmpfs                    1.9G   12K  1.9G   1% /var/lib/kubelet/pods/c074683f-416a-11e8-9f3d-fa163e02c5d3/volumes/kubernetes.io~secret/weave-net-token-npm5t
tmpfs                    1.9G   12K  1.9G   1% /var/lib/kubelet/pods/b79dbbb3-416a-11e8-9f3d-fa163e02c5d3/volumes/kubernetes.io~secret/default-token-hvf4r
tmpfs                    1.9G   12K  1.9G   1% /var/lib/kubelet/pods/fbfe4b47-416a-11e8-9f3d-fa163e02c5d3/volumes/kubernetes.io~secret/default-token-jbbs6
/dev/vdb                 7.8G   36M  7.3G   1% /var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/8810cc18-525b-42bb-a894-4c5eb1620305
tmpfs                    380M     0  380M   0% /run/user/1000
```

**What you expected to happen**: I except that kubelet should expose prometheus metrics to /metrics path as well. Then it is easy to read with prometheus.

**How to reproduce it (as minimally and precisely as possible)**: Create new cinder volume, attach it to pod and try to query result from `/metrics` in kubelet

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.1
- Cloud provider or hardware configuration: openstack
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gnufied** [comment]
Prometheus metrics should be available on default port of Kubelet. Can you try `curl http://localhost:10255/metrics` ? If you are on a RBAC enabled cluster (such as openshift) you may have to use token or key to authenticate for fetching metrics.

**Comment by zetaab** [comment]
```

**Comment by gnufied** [comment]
It appears that Cinder volume plugin does not implement metric interface necessary for getting those stat metrics - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder.go#L306

This seems like an oversight and is fairly easy to fix. I can help getting the PR merged if you can open it.

**Comment by LynnWonder** [comment]
Kubernetes v1.19.16 
there is no kubelet_volume* metrics in /10250/metrics
how to fix it???
