### ISSUE TITLE
[cli]some deprecated flags disappeared from help message

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#62645]
After the merge of this [pull request](https://github.com/kubernetes/kubernetes/pull/62505)

Some deprecated flags are hidden from help message.  
This issue is addressed to trace what options should we take back.

One related change to kube-apiserver:  https://github.com/kubernetes/kubernetes/pull/62621

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

/sig cli

/assign

**Comment by liggitt** [comment]
no, we do not want to show those
