### ISSUE TITLE
Feature request: Customize prefix for LB provisioned in cloud infrastructure

### ISSUE THREAD

**Issue by minherz** [kubernetes/kubernetes#62640]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When Kubernetes provisioning Load Balancer (LB) instance in one of supported Cloud infrastructures, it generates name for LB using [hardcoded template](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/cloud.go#L67). Sometimes it is required to limit scope of permissions for LB related actions. For example, AWS permissions `elasticloadbalancing::*` can be limited to a subset of LB resources instead of `*`. Currently, there is no way to customize LB name, hence the requirement for LB related permissions require access to all LB resources.

**What you expected to happen**:
To define an annotation that will allow to define a prefix for the LB name. The prefix will replace one-letter prefix (`a` ) that is being used by now. The prefix length can be limited (e.g. 8 symbols) and conditioned to start with letter. Then the prefix can be used when defining permissions to cluster's master node.

**Comment by minherz** [comment]
@kubernetes/sig-Cloud Provider-feature-requests

**Comment by minherz** [comment]
@kubernetes/sig-cluster-ops-feature-requests

**Comment by justinsb** [comment]
So this is a good idea; the caveat is that it'll be tricky for existing LoadBalancers because we identify them by name.

We really want ELBs to support something like ec2:ResourceTag, so we could scope the IAM permissions to ELBs tagged with a cluster specific tag, IMO:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-supported-iam-actions-resources.html

I'm not opposed, but it's very tricky, and I suspect by the time we figure out how to make this work, AWS will have added IAM filtering by tags...

**Comment by justinsb** [comment]
See also https://github.com/kubernetes/kubernetes/issues/29789 for some of the issues around changing the "template" for a service of type LoadBalancer.

**Comment by minherz** [comment]
thank you @justinsb, although #29789 address only AWS the mentioned issues around changing annotation indeed will create orphaned LB instances. i need to look into a code to see how the LB instances are cleaned out in order to apply similar handling for annotation change.

**Comment by minherz** [comment]
@justinsb can you advise where i can find a code that handle changes in annotation values of the service?

**Comment by minherz** [comment]
closed it by mistake
