### ISSUE TITLE
Improve ubuntu-cluster setup scripts

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#6266]
I used the ubuntu-cluster setup scripts to build a mini testing environment. The first time I inputted a wrong config and when I reconfigured the environment by running the scripts again an error occured.  I looked into the code and found the scripts hadn't deal with old configs. And `MASTER_IP` of kube-proxy configs are not replaced.

**Comment by roberthbailey** [comment]
Looks like this was fixed by #6275.
