### ISSUE TITLE
Bad interaction between finalizer, limit range and mutating web-hook prevents pod termination

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#62666]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: Pod stuck in terminating state.

**What you expected to happen**: Pod successfully cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up a LimitRange. (Say "limits:
    - defaultRequest:
        cpu: 100m
      type: Container")
2. Install a mutating webhook on pod which creates an additional container on the pod (Eg. https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection) without the limit range.
3. Create a Pod with foreground deletion finalizer.
4. Notice that you have a Pod with 2 containers. The 1 you created which now has a limit and the istio container which does not.
5. Try to delete the Pod.
6. The garbage collector tries to update the pod to remove the finalizer, however this triggers the limit range admission control to add the limit to the istio container. This then causes the API server to get the error "invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations`"
7. Notice the pod is now stuck in terminating.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6

/sig api-machinery

**Comment by nikhita** [comment]
/remove-lifecycle stale

PR open
