### ISSUE TITLE
Failing Test: [sig-network] DNS configMap nameserver Forward PTR lookup should forward PTR records lookup to upstream nameserver [Slow][Serial]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62698]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&sig=network&test=DNS%20configMap%20nameserver%20Forward%20PTR%20lookup%20should%20forward%20PTR%20records%20looku

Has been failing consistently since 4/13.

/kind bug
/priority failing-test
/priority important-soon
/sig network
/milestone 1.11
@kubernetes/sig-network-bugs  

cc @jberkus @tpepper 

/assign @dcbw

**Comment by AishSundar** [comment]
The same test also fails as part of 
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new

## Triage
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&sig=network&job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new&test=DNS%20configMap%20nameserver%20Forward%20PTR%20lookup%20should%20forward%20PTR%20records%20looku

**Comment by MrHohn** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/62490. @grayluck and I are looking into this.

/assign
/unassign @dcbw

**Comment by grayluck** [comment]
Working on it.

**Comment by grayluck** [comment]
It can't be reproduced from prod gke manually. ptr lookup successfully forwarded after kube-dns image updated.

Still digging for root cause for the failing e2e test.

**Comment by MrHohn** [comment]
> It can't be reproduced from prod gke manually. ptr lookup successfully forwarded after kube-dns image updated.
>
> Still digging for root cause for the failing e2e test.

Discussed offline, turned out we need to fix something on the GKE side. Will update here once fix is in place. cc @rramkumar1

**Comment by MrHohn** [comment]
Fix rolled out on GKE. This test is no longer failing.
/close
