### ISSUE TITLE
Failing test : [sig-testing] verify.godeps failing in sig-release-master-blocking

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62696]
### https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=verify%20godeps

This seems to have started failing since 1pm 4/16. [Commit changes](https://github.com/kubernetes/kubernetes/compare/2bdca2b75...1d94baad0)

@BenTheElder Is this a Sig-testing issue? If not please triage to the appropriate SIG / Owner.

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone 1.11
@kubernetes/sig-testing-bugs 

/cc @jberkus @tpepper 

/assign @BenTheElder

**Comment by AishSundar** [comment]
@jberkus @tpepper as FYI.

**Comment by AishSundar** [comment]
cc @jberkus @tpepper

**Comment by cblecker** [comment]
/assign
This was caused by #58784. Created fix in #62736.

**Comment by ixdy** [comment]
hm, does this mean our logic for detecting when to run `verify-godeps.sh` is incorrect? Currently we only run this on PRs when something touches `Godeps/` or `vendor/`.

**Comment by cblecker** [comment]
Yeah, it's not an exact science.

- If someone adds an import, but doesn't add it to Godeps, the build will fail.
- If someone adds/removes an import, and does update Godeps, the job will run.
- If someone removes an import, but leaves the dep hanging, the job won't run in pre-submit, but will in the ci-kubernetes-master post-submit
