### ISSUE TITLE
Failing Test : [sig-network] Upgrade [Feature:Upgrade] master upgrade should maintain a functioning cluster [Feature:MasterUpgrade]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62702]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%3AUpgrade%5C%5D%5C%20master%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%3AMasterUpgrade%5C%5D

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @timothysc  can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
/milestone 1.11
@kubernetes/sig-cluster-lifecycle-bugs 

cc @jberkus @tpepper 

/assign @timothysc

**Comment by AishSundar** [comment]
This test also fails in 
[sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster)

**Comment by MrHohn** [comment]
cc @rramkumar1

**Comment by AishSundar** [comment]
/close

I dont see this repro any more
