### ISSUE TITLE
Failing Test : [sig-apps] Deployment RollingUpdateDeployment should delete old pods and create new ones

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62703]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=apps&test=%5C%5Bsig%5C-apps%5C%5D%5C%20Deployment%5C%20RollingUpdateDeployment%5C%20should%5C%20delete%5C%20old%5C%20pods%5C%20and%5C%20create%5C%20new%5C%20ones

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @mattfarina   can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig apps
@kubernetes/sig-apps-bugs 

cc @jberkus @tpepper 

/assign @mattfarina

**Comment by AishSundar** [comment]
/status approved-for-milestone

Since this is a test issue, I am applying label status/approved-for-milestone to avoid this issue from being removed from the milestone.

**Comment by AishSundar** [comment]
@mattfarina  is there an ETA on fixing this test failure? This is currently on of the few tests failing our sig-release upgrade blocking suite. If this is not fixed we will have to delay beta for 1.11.

@tpepper @jberkus as FYI

**Comment by janetkuo** [comment]
I think it's likely due to the removal of hash labels in deployments.

**Comment by AishSundar** [comment]
cc @kow3ns @janetkuo can one of you please triage and assign a owner to fix the issue? This is currently on of the few tests failing our sig-release upgrade blocking suite. If this is not fixed we will have to delay beta cut for 1.11 which is currently on 5/15.

**Comment by AishSundar** [comment]
Followed with @kow3ns offline. He is testing a fix locally. He'll cut a PR against 1.10 today. need to modify the tests in that branch and then we need to get the release shepherd to merge the CP

**Comment by kow3ns** [comment]
@janetkuo is correct in her comment above. Issued #63674. Needs cherry pick into release 1.10.

**Comment by AishSundar** [comment]
@MaciekPytel who is 1.10 patch manager to help CP [#63674](https://github.com/kubernetes/kubernetes/pull/63674) into 1.10 after its merged

**Comment by kow3ns** [comment]
@AishSundar @MaciekPytel the PR is against 1.10. We don't want to pull the entire PR that modifies the test into release-1.10, just this small patch.

**Comment by AishSundar** [comment]
@kow3ns which is the small patch we want CP'ed into release-1.10?

**Comment by kow3ns** [comment]
#63674 needs to be merged into 1.10

**Comment by MaciekPytel** [comment]
I've added cherrypick-approved. I don't really have the context here, so I'd rather leave doing the actual review (and lgtm-ing) to someone more competent.

**Comment by AishSundar** [comment]
@kow3ns any ETA on merging #63674 ? its CP approved

**Comment by tpepper** [comment]
@kubernetes/sig-apps-api-reviews this needs your lgtm

**Comment by AishSundar** [comment]
Things seem to be clearing up now in a few jobs. Closing this issue now
