### ISSUE TITLE
Failing Test : [sig-testing] ci-kubernetes-e2e-gci-gce-alpha-features:BeforeSuite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62700]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&job=ci-kubernetes-e2e-gci-gce-alpha-features&test=BeforeSuite

## Failure
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:137
Apr  9 22:20:23.493: Error waiting for all pods to be running and ready: 1 / 3 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                                    NODE                            PHASE   GRACE CONDITIONS
event-exporter-v0.1.9-75857bbfd5-4kgp5 bootstrap-e2e-minion-group-8r2v Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-09 22:03:51 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-09 22:10:40 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [event-exporter prometheus-to-sd-exporter]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-09 22:03:51 +0000 UTC Reason: Message:}]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:190

This test seems to have been failing for a very long time (since mid of March). @BenTheElder can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone 1.11
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper 

/assign @BenTheElder

**Comment by MrHohn** [comment]
@rramkumar1 and I are looking into this. We found a regression (possibly introduced by https://github.com/kubernetes/kubernetes/pull/60020) in alpha cluster that `kube-proxy-ds-ready` label is not attached to node anymore, which causes kube-proxy not being scheduled to any node.

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/pull/62352 should address at least one of the alpha cluster bring up failures.  Unsure if there's more issues

**Comment by MrHohn** [comment]
> in alpha cluster that kube-proxy-ds-ready label is not attached to node anymore

Ref https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/20689/artifacts/bootstrap-e2e-minion-group-58sn/kubelet.log.

In fact, from the kubelet log I can see the node labels were properly passed into kubelet:
```
I0417 19:18:43.703630    1005 flags.go:27] FLAG: --node-labels="beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/kube-proxy-ds-ready=true,beta.kubernetes.io/metadata-proxy-ready=true"
```
Will do more investigation.

**Comment by MrHohn** [comment]
> in alpha cluster that kube-proxy-ds-ready label is not attached to node anymore

Confirmed this only happens on [gke-alpha-features](https://k8s-testgrid.appspot.com/google-gke#gci-gke-alpha-features), not gce-alpha-feature:
```
I0417 22:06:51.154242    1010 flags.go:27] FLAG: --node-labels="beta.kubernetes.io/fluentd-ds-ready=true,cloud.google.com/gke-nodepool=default-pool"
```
Sorry for the noise. Will file a separate issue.

/unassign @rramkumar1  @mrhohn
/sig auth

**Comment by BenTheElder** [comment]
@MrHohn can you punt to someone from sig-auth? :-)

**Comment by MrHohn** [comment]
@BenTheElder Sure, assigning to the owner of #62352 :)
/assign @mikedanese

**Comment by AishSundar** [comment]
status/approved-for-milestone

**Comment by Random-Liu** [comment]
The issue is that master kubelet can even start:
```
I0418 16:54:26.448079    1702 kubelet.go:1695] Starting kubelet main sync loop.
I0418 16:54:26.448097    1702 kubelet.go:1712] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0418 16:54:26.448265    1702 server.go:131] Starting to listen on 0.0.0.0:10250
F0418 16:54:26.450080    1702 server.go:143] open : no such file or directory
```

The error is from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L143.

It seems that there is no cert file or something on master.

**Comment by mikedanese** [comment]
That's not the error anymore. Look at the recent runs. https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-alpha-features

**Comment by Random-Liu** [comment]
@mikedanese Yeah, https://github.com/kubernetes/kubernetes/pull/62766 fixed https://github.com/kubernetes/kubernetes/issues/62700#issuecomment-382535068. Now it is the kube-proxy issue.

**Comment by mikedanese** [comment]
@Random-Liu is that tracked elsewhere? Is anyone looking into it?

**Comment by mikedanese** [comment]
Ahh, folding into: https://github.com/kubernetes/kubernetes/issues/62757

**Comment by MrHohn** [comment]
> Yeah, #62766 fixed #62700 (comment). Now it is the kube-proxy issue.

To clarify, the kube-proxy issue tracked on #62757 is GKE specific and is unrelated to this thread. Now it seems this gce-alpha-features is failing on a different error. Took a quick look and found some pod priority relevant errors (`no PriorityClass with name system-node-critical was found`) in kube-controller-manage logs:
```
...
E0418 22:53:24.989048       1 daemon_controller.go:992] pods "fluentd-gcp-v3.0.0-" is forbidden: no PriorityClass with name system-node-critical was found
I0418 22:53:24.989064       1 daemon_controller.go:1000] Slow-start failure. Skipping creation of 3 pods, decrementing expectations for set "kube-system"/"fluentd-gcp-v3.0.0"
I0418 22:53:24.989105       1 daemon_controller.go:1010] Pods to delete for daemon set fluentd-gcp-v3.0.0: [], deleting 0
I0418 22:53:24.989116       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/fluentd-gcp-v3.0.0" (9.775367ms)
E0418 22:53:24.989128       1 daemon_controller.go:265] kube-system/fluentd-gcp-v3.0.0 failed with : pods "fluentd-gcp-v3.0.0-" is forbidden: no PriorityClass with name system-node-critical was found
I0418 22:53:24.991615       1 daemon_controller.go:1315] DaemonSet Predicates failed on node bootstrap-e2e-master for ds 'kube-system/kube-proxy' for reason: node(s) didn't match node selector
I0418 22:53:24.991663       1 daemon_controller.go:937] Nodes needing daemon pods for daemon set kube-proxy: [bootstrap-e2e-minion-group-6htn bootstrap-e2e-minion-group-72ds bootstrap-e2e-minion-group-d4bz], creating 3
I0418 22:53:24.994007       1 daemon_controller.go:989] Failed creation, decrementing expectations for set "kube-system"/"kube-proxy"
E0418 22:53:24.994038       1 daemon_controller.go:992] pods "kube-proxy-" is forbidden: no PriorityClass with name system-node-critical was found
I0418 22:53:24.994050       1 daemon_controller.go:1000] Slow-start failure. Skipping creation of 2 pods, decrementing expectations for set "kube-system"/"kube-proxy"
I0418 22:53:24.994095       1 daemon_controller.go:1010] Pods to delete for daemon set kube-proxy: [], deleting 0
I0418 22:53:24.994106       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/kube-proxy" (3.453914ms)
E0418 22:53:24.994117       1 daemon_controller.go:265] kube-system/kube-proxy failed with : pods "kube-proxy-" is forbidden: no PriorityClass with name system-node-critical was found
I0418 22:53:24.994138       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"kube-proxy", UID:"d69c9a20-4359-11e8-9d5b-42010a800002", APIVersion:"apps", ResourceVersion:"451", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "kube-proxy-" is forbidden: no PriorityClass with name system-node-critical was found
I0418 22:53:25.001038       1 daemon_controller.go:989] Failed creation, decrementing expectations for set "kube-system"/"metadata-proxy-v0.1"
E0418 22:53:25.001076       1 daemon_controller.go:992] pods "metadata-proxy-v0.1-" is forbidden: no PriorityClass with name system-node-critical was found
...
```
@bsalamat could you help triaging? Thanks!
/assign @bsalamat  
/reopen

**Comment by AishSundar** [comment]
status/approved-for-milestone

**Comment by BenTheElder** [comment]
@mikedanese I suspect other alpha features jobs need that magical env too. do we have a doc somewhere with the set of env we should be setting?

EG
https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gci-gce-alpha-features.env 
has some other feature gates..

**Comment by AishSundar** [comment]
@mikedanese any update on fixing this test ? its currently failing in sig-release master-blocking suite

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-alpha-features

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&job=ci-kubernetes-e2e-gci-gce-alpha-features&test=BeforeSuite

@BenTheElder, @tpepper and @jberkus as FYI

**Comment by mikedanese** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by mikedanese** [comment]
Can someone from sig-scheduling on the resolution? Please see: https://github.com/kubernetes/kubernetes/issues/62700#issuecomment-382562402

**Comment by k82cn** [comment]
let me check it this week.

**Comment by k82cn** [comment]
In `pkg/registry/scheduling/rest/storage_scheduling.go`, `AddSystemPriorityClasses` will create system PriorityClasses.

There're error logs in apiserver.log as follow:

```
E0417 03:56:58.9183681 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:129: Failed to list *scheduling.PriorityClass: the server could not find the requested resource (get priorityclasses.scheduling.k8s.io)
```

**Comment by msau42** [comment]
I opened PR https://github.com/kubernetes/test-infra/pull/7989 that will hopefully allow alpha clusters to come up more.

**Comment by msau42** [comment]
Looks like gce alpha is passing now. 

But gke alpha is failing again, probably a new issue should be open for gke

**Comment by AishSundar** [comment]
Thanks @msau42 for the fix. Where do you see the gke dashboard? Its not on the sig-release dashboard.

**Comment by msau42** [comment]
Here's gke alpha testgrid:
https://k8s-testgrid.appspot.com/google-gke#gci-gke-alpha-features
