### ISSUE TITLE
Failing Test: [sig-testing] kubeadm-gce and kubeadm-gce-selfhosting jobs failing to Up the cluster

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62701]
### [ci-kubernetes-e2e-kubeadm-gce-selfhosting](https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=testing&job=ci-kubernetes-e2e-kubeadm-gce-selfhosting&test=Up)

This test seems to have consistently failing since 4/12. Here are the [commit changes](https://github.com/kubernetes/kubernetes/compare/dacb9ad69...cce6a95ce). @BenTheElder can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone 1.11
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper 

/assign @BenTheElder

**Comment by BenTheElder** [comment]
looks like etcd versions changed everywhere in that timeframe, that *may* be related (?)

/sig cluster-lifecycle

**Comment by dims** [comment]
@BenTheElder @AishSundar looks like the etcd image is missing

```
Apr 12 19:13:57 e2e-10122-d0b691-master dockerd[3636]: time="2018-04-12T19:13:57.249074063Z" level=error msg="Handler for GET /v1.24/images/k8s.gcr.io/etcd-amd64:3.2.18/json returned error: No such image: k8s.gcr.io/etcd-amd64:3.2.18"
```

**Comment by dims** [comment]
your guess was correct @BenTheElder

**Comment by ixdy** [comment]
cc @jpbetz

**Comment by jpbetz** [comment]
Fixing

**Comment by jpbetz** [comment]
Resolved.

As part of https://github.com/kubernetes/kubernetes/pull/61241 we changed the etcd image docker tag from a format like `k8s.gcr.io/etcd-amd64:<etcd-version>` to `k8s.gcr.io/etcd-amd64:<etcd-version>-<image-revision>`, e.g. `k8s.gcr.io/etcd-amd64:3.2.18-0`. To mitigate the problem in the short term we've tagged the `k8s.gcr.io/etcd-amd64:3.2.18-0` docker image with `k8s.gcr.io/etcd-amd64:3.2.18`. For the long term, I've filed https://github.com/kubernetes/kubernetes/issues/62831 against myself to fix the tests to use the new etcd image version scheme.

**Comment by jpbetz** [comment]
Fix verified: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/

**Comment by BenTheElder** [comment]
Thanks @jpbetz :+1:

**Comment by AishSundar** [comment]
/reopen

@jpbetz @dims This issue seemed to have resurfaced again. Canyou please take a look? This could potentially block Beta cut for v1.11 which is slated for 5/15

**Comment by jpbetz** [comment]
Per @dims - "i see failures with `No such image: gcr.io/kubernetes-ci-images/kube-controller-manager-amd64:v1.11.0-alpha.2.293_321201f6723a5d"` example - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/10445/artifacts/e2e-10445-31d72-master/serial-1.log".

We'll need someone familiar with `kube-controller-manager-amd64` publication to help out here.

**Comment by AishSundar** [comment]
As per @jpbetz comment above, closing this issue and opening a new one
