### ISSUE TITLE
Failing Tests : Timeout and UpgradeTest in gce-1.10-master-upgrade-cluster, gce-1.10-master-upgrade-cluster-new and gce-1.10-master-upgrade-cluster-parallel

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#62713]
### [ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new&test=Timeout)

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @BenTheElder can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig testing
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper 

/assign @BenTheElder

**Comment by krzyzacy** [comment]
cc @krousey ^^

assume that's somewhere inside the upgrade framework

**Comment by BenTheElder** [comment]
/assign @krousey 
/unassign
Unlikely I will have the time or expertise to patch these, discussed out of band with @krzyzacy and these appear to be something in the upgrade or cluster-up code, not kubetest etc..

**Comment by krousey** [comment]
Debugged one of the jobs. The node upgrade is stalling out. There's logic in the node upgrade to wait for the new GCE vm to register with the k8s API. It does this by checking the node status's external ID and seeing if it matches the instance ID from the GCE vm. That logic is here: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L345-L363

It looks like the kubelet is now registering the GCE VM's resource path and not its ID as the node's externalID.

```console
I0417 19:42:11.088] == Waiting for new node to be added to k8s.  ==
I0417 19:43:09.510] ...................................................Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:09.510]   (Will retry.)
I0417 19:43:10.653] Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:10.653]   (Will retry.)
I0417 19:43:11.791] Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:11.791]   (Will retry.)
I0417 19:43:12.930] Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:12.930]   (Will retry.)
I0417 19:43:14.070] Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:14.071]   (Will retry.)
I0417 19:43:15.211] Unexpected external_id 'k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q' matches neither old ('8548676601506428815') nor new ('7494738717089460478').
I0417 19:43:15.212]   (Will retry.)
```

from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3132?log#log

Can I get input on this from @kubernetes/sig-node-bugs ? Is this an intended change? If so, what is a good way to detect that the new node has registered with kubernetes?

**Comment by krzyzacy** [comment]
cc @dchen1107 @yujuhong @dashpole  ^^ :-)

**Comment by yujuhong** [comment]
ExternalID was apparently deprecated before kubernetes V1 API, but was never removed properly. PR #60692 was merged recently to remove the use of ExternalID
Can we use the instance ID instead?

**Comment by krousey** [comment]
@yujuhong No. Instance ID is returning information like "k8s-jkns-e2e-gce-slow/us-central1-f/bootstrap-e2e-minion-group-0s1q". During a node upgrade, this ID is shared between the old and new VM. We need a way to distinguish them to make sure the new VM has come up, registered with the API server, and is healthy. Without a distinguishing ID, we could be reading the health status of the old node before we deleted it.

**Comment by yujuhong** [comment]
`Node.Status.NodeInfo.MachineID` or `Node.Status.NodeInfo.SystemUUID`
https://github.com/kubernetes/kubernetes/blob/v1.11.0-alpha.0/staging/src/k8s.io/api/core/v1/types.go#L3811-L3819

**Comment by krousey** [comment]
Sorry, I should have been more specific. Where do those come from? Because I can't find that anywhere in `gcloud instances describe <instance name>`

**Comment by krousey** [comment]
Oh I see. OK I'll see if I can work with that.

**Comment by yujuhong** [comment]
> @yujuhong It doesn't work. The machine ID is the same before and after the instance recreate. Even confirmed by looking at /etc/machine-id directly. SystemUUID seems to have the same value as machine ID.

Urghh...recreating an instance actually keeps the machineID.  I don't have a good solution. One idea is to check if the bootID changed.

**Comment by AishSundar** [comment]
status/approved-for-milestone

**Comment by AishSundar** [comment]
/reopen

@krousey I still see the Upgrade test failing in the jobs below.

* [sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)
* [sig-release-master-upgrade#gce-1.10-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster)
* [sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new]((https://k8s-testgrid.appspot.com/[sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new)

**Comment by AishSundar** [comment]
@krousey I still see  UpgradeTest and Timeout failing in the jobs below. Are you actively investigating these or should I re-triage?

* [sig-release-master-upgrade#gce-1.10-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster)
* [sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new)

**Comment by krousey** [comment]
@AishSundar These failures seem similar to my comment in https://github.com/kubernetes/kubernetes/issues/63506#issuecomment-387464373. I'm would appreciate help in looping in the node team on why that is happening.

**Comment by AishSundar** [comment]
cc @dchen1107 @derekwaynecarr

**Comment by dchen1107** [comment]
I updated the issue at https://github.com/kubernetes/kubernetes/issues/63506#issuecomment-387819838, which might explain some of the failures here.

**Comment by AishSundar** [comment]
I see the tests passing now. Thanks @krousey and @dchen1107 for all your help.
