### ISSUE TITLE
Use correct API group when fetching and deleting resources

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#62739]
Currently, when fetching `deployments` (either through `kubectl get` or `kubectl delete`), a GET request is made to the /extensions/ api group. We should be fetching deployments from the newer /apps/ group.

cc @soltysh

**Comment by liggitt** [comment]
the extensions API group is listed first in discovery for backwards compatibility (scripts written against `kubectl get deployments -o jsonpath=...` should present extensions/v1beta1 output as long as that API group is published)

the discovery order is honored by the CLI

if you want to override the order listed in discovery, specify the group you want (e.g. `kubectl get deployments.apps`)

/close
