### ISSUE TITLE
Kubelet test is failing on release 1.9 branch

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/kubernetes#62737]
This tests are failing on release 1.9 branch blocking next patch release that is scheduled for tomorrow:

- [k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 100 pods per node
- [k8s.io] [sig-node] Kubelet [Serial] [Slow] [k8s.io] [sig-node] regular resource usage tracking resource tracking for 0 pods per node

An example failure:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-stable2/352

**Comment by dims** [comment]
i see some green runs - https://k8s-testgrid.appspot.com/sig-release-1.9-all#soak-gci-gce-1.9

**Comment by nikhita** [comment]
@mbohlool @dims looks like this can be closed now?
