### ISSUE TITLE
--pod-infra-container-image not work?

### ISSUE THREAD

**Issue by yangxikun** [kubernetes/kubernetes#62732]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig kubelet

**What happened**:

`failed to pull image \"k8s.gcr.io/pause:3.1\"`

```
Error syncing pod cbc9323f-4200-11e8-87a9-fa163ef77358 ("kube-dns-96bc87b87-x8wcl_kube-system(cbc9323f-4200-11e8-87a9-fa163ef77358)"), skipping: failed to "CreatePodSandbox" for "kube-dns-96bc87b87-x8wcl_kube-system(cbc9323f-4200-11e8-87a9-fa163ef77358)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-96bc87b87-x8wcl_kube-system(cbc9323f-4200-11e8-87a9-fa163ef77358)\" failed: rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to resolve image \"k8s.gcr.io/pause:3.1\": failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 108.177.97.82:443: i/o timeout"
```

**What you expected to happen**:

`pull registry.hub.docker.com/yangxikun/pause-amd64:3.1`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/3364160/38878069-b4fca38c-4292-11e8-8047-dd976f73eb07.png">

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

CentOS 7

- Kernel (e.g. `uname -a`):

3.10.0-693.21.1.el7.x86_64

- Install tools:
- Others:

**Comment by dixudx** [comment]
Dup of #55676.

See [my comment](https://github.com/kubernetes/kubernetes/issues/55676#issuecomment-371084007).

* For `cri-o`, you can override the sandbox image by `--pause-image=[value]`.
* For `containerd`, you can override it in [/etc/containerd/config.toml](https://github.com/containerd/cri/blob/master/docs/config.md).

/close
