### ISSUE TITLE
[Failing Test] Node e2e Checkpoint tests failing

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#62738]
/kind bug
[Some checkpointing tests](https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e&include-filter-by-regex=checkpoint) are failing.  #56040 seems like the likely cause.

cc @kubernetes/sig-node-test-failures 
/assign @vikaschoudhary16

**Comment by dashpole** [comment]
ping @vikaschoudhary16

**Comment by vikaschoudhary16** [comment]
seems one test still failing.
/open
