### ISSUE TITLE
 minikube start --vm-driver=kvm showing error

### ISSUE THREAD

**Issue by harsh244** [kubernetes/kubernetes#62741]
trying to run minikube using kvm. When I type the above command.
 **minikube start --vm-driver=kvm** 
The following error is shown .

_Error starting host: Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue._

**Comment by dims** [comment]
please open in https://github.com/kubernetes/minikube/issues/

/close
