### ISSUE TITLE
Scheduler cache uses PDB name as the key to store PDB objects. It could cause conflicts.

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#62750]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

[Scheduler cache uses PDB names as key to store PDB objects in a map](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedulercache/cache.go#L435). Using the name could cause a conflict if an object with the same name is created in a different namespace. We should use UID of PDB objects as the key to the map.

/sig scheduling

**Comment by resouer** [comment]
Close as #62765 is in
