### ISSUE TITLE
Job run twice

### ISSUE THREAD

**Issue by aisk** [kubernetes/kubernetes#62772]
/kind bug
/sig scheduling

**What happened**:

Job run twice randomly with another pod after first pod was exited. The job's `restartPolicy` is `Never`, `parallelism` and `completions ` is 1.

**What you expected to happen**:

Only one pod was scheduled for a job.

**How to reproduce it (as minimally and precisely as possible)**:

This happens randomly on our two k8s cluster, have no idea how to reproduce it.

**Anything else we need to know?**:

I found this on [job document](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#handling-pod-and-container-failures):

> Note that even if you specify .spec.parallelism = 1 and .spec.completions = 1 and .spec.template.spec.restartPolicy = "Never", the same program may sometimes be started twice.

Did I got the issue the document described? And if it is, is this a bug, or a by design?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.4.0
- Install tools:
- Others:

**Comment by wgliang** [comment]
/sig testing
cc @bsalamat

**Comment by aisk** [comment]
The `backoffLimit` is  set to 1 also.

**Comment by bsalamat** [comment]
My understanding is that this is expected that such a job could occasionally be executed twice. Anyway, scheduler is not involved in creating new pods (instances of the job). It is the job controller that creates these instances.

**Comment by yue9944882** [comment]
> The job's restartPolicy is Never, parallelism and completions is 1.

@aisk Sounds like a date-racing issue. IMO, basically job controller will only try to create the job pod twice in your case is when the number of `active` pods is 0. As you described, it happens randomly. I guess maybe you are updating the job resource after the creation at once? Successive job events (e.g. updates after creation) to job controller might possibly cause this issue.

@soltysh If you could shed some light on this? 🤔

**Comment by aisk** [comment]
@yue9944882 Sorry for the late reply, but in this case, we were not updating the job after any time point. Another information is as the total job count growth, this problem happens more times than before.

**Comment by ricky1993** [comment]
@yue9944882 We have used pod gc controller, if the gc succeed pod before job controller consume the succeed event, when consuming it, job controller can't found the succeed pod, so it will recreate one. I'm not sure whether it is a bug or by design.

**Comment by soltysh** [comment]
@aisk if you could provide smallest possible reproducer then it'll be easier for me to do any judgment. There are too many variables at this point in time.

**Comment by ricky1993** [comment]
@soltysh I have debug with @aisk and provided what situation we met. Could u have a judgement?

**Comment by rahulgautam** [comment]
@soltysh, @ricky1993  can you please take a look at this too - https://stackoverflow.com/questions/52119955/kubernetes-does-not-track-pods-success-count-for-job-completion

For me, Job is never completing when I use higher `parallelism` number like 1600 or so.
I have enough CPU + memory resources available and pods are running fine and exit with proper success status.

**Comment by dobesv** [comment]
I see a similar issue.  I see logs from controller-manager:

```
I1016 20:30:02.183093       1 event.go:281] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"formative", Name:"job-xxx", UID:"33ac928e-2104-11ea-a439-0e9b9d35598c", APIVersion:"batch/v1beta1", ResourceVersion:"255213399", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created job job-xxx-1602880200
I1016 20:30:02.187624       1 event.go:281] Event(v1.ObjectReference{Kind:"Job", Namespace:"formative", Name:"job-xxx-1602880200", UID:"44f7bd7a-064e-45db-b7ca-f497f4b39267", APIVersion:"batch/v1", ResourceVersion:"255445649", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: job-xxx-1602880200-xgkmh
```

the some time later:

```
I1016 20:32:01.645311       1 event.go:281] Event(v1.ObjectReference{Kind:"Job", Namespace:"formative", Name:"job-xxx-1602880200", UID:"44f7bd7a-064e-45db-b7ca-f497f4b39267", APIVersion:"batch/v1", ResourceVersion:"255445651", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: sync-users-to-bigquery-1602880200-r59kk
```

it actually seems to launch the second pod before the first one is finished, because the second one fails because it cannot acquire a lock held by the first one.

This is the job that was created by the cron job:

```
kind: Job
apiVersion: batch/v1
metadata:
  name: job-xxx-1602880200
  namespace: formative
  selfLink: /apis/batch/v1/namespaces/xxx/jobs/job-xxx-1602880200
  uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
  resourceVersion: '255447945'
  creationTimestamp: '2020-10-16T20:30:02Z'
  labels:
    controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
    job-name: job-xxx-1602880200
  ownerReferences:
    - apiVersion: batch/v1beta1
      kind: CronJob
      name: sync-users-to-bigquery
      uid: 33ac928e-2104-11ea-a439-0e9b9d35598c
      controller: true
      blockOwnerDeletion: true
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  selector:
    matchLabels:
      controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
        job-name: sync-users-to-bigquery-1602880200
    spec:
      volumes:
        - name: google-application-credentials
          secret:
            secretName: google-application-credentials
            defaultMode: 420
      containers:
        - name: sync-to-bigquery
          image: >-
            555337501170.dkr.ecr.us-east-1.amazonaws.com/formative-node-app:production-2020-10-16-647-f7
          args:
            - node
            - '-r'
            - ./dist/server/startup/server/startElasticApm
            - dist/server/api/import/bigquery/syncUsersToBigQuery.js
            - '--dataset'
            - formative
          envFrom:
            - secretRef:
                name: settings
                optional: true
            - configMapRef:
                name: settings
                optional: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: >-
                /mnt/google-application-credentials/google-application-credentials.json
          resources:
            limits:
              cpu: '1'
              memory: 500Mi
          volumeMounts:
            - name: google-application-credentials
              mountPath: /mnt/google-application-credentials
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  conditions:
    - type: Failed
      status: 'True'
      lastProbeTime: '2020-10-16T20:32:08Z'
      lastTransitionTime: '2020-10-16T20:32:08Z'
      reason: BackoffLimitExceeded
      message: Job has reached the specified backoff limit
  startTime: '2020-10-16T20:30:02Z'
  failed: 1
```

I can see that the ResourceVersion of the job did actually change, so perhaps something did in fact modify the Job.

The only suspicious thing I can see around that time is that our CI did update the cronjob.  It should have been a no-op since we didn't really make any changes, but that script is just running kustomize and applying all files even though they haven't changed.  Perhaps there's some glitch with kubectl apply that is bumping the resource version on the cronjob, which causes the job to have its resource version bumped, which causes the pod to be restarted.

I think it would be better if the job would NOT start a new pod if one were already running if it gets updated.  Or it could perhaps gracefully terminate the existing pod before starting a new one.  Or make this behavior configurable.

**Comment by mau21mau** [comment]
> I see a similar issue. I see logs from controller-manager:
> 
> ```
> I1016 20:30:02.183093       1 event.go:281] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"xxx", Name:"job-xxx", UID:"33ac928e-2104-11ea-a439-0e9b9d35598c", APIVersion:"batch/v1beta1", ResourceVersion:"255213399", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created job job-xxx-1602880200
> I1016 20:30:02.187624       1 event.go:281] Event(v1.ObjectReference{Kind:"Job", Namespace:"xxx", Name:"job-xxx-1602880200", UID:"44f7bd7a-064e-45db-b7ca-f497f4b39267", APIVersion:"batch/v1", ResourceVersion:"255445649", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: job-xxx-1602880200-xgkmh
> ```
> 
> the some time later:
> 
> ```
> I1016 20:32:01.645311       1 event.go:281] Event(v1.ObjectReference{Kind:"Job", Namespace:"xxx", Name:"job-xxx-1602880200", UID:"44f7bd7a-064e-45db-b7ca-f497f4b39267", APIVersion:"batch/v1", ResourceVersion:"255445651", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: job-xxx-1602880200-r59kk
> ```
> 
> it actually seems to launch the second pod before the first one is finished, because the second one fails because it cannot acquire a lock held by the first one.
> 
> This is the job that was created by the cron job:
> 
> ```
> kind: Job
> apiVersion: batch/v1
> metadata:
>   name: job-xxx-1602880200
>   namespace: xxx
>   selfLink: /apis/batch/v1/namespaces/xxx/jobs/job-xxx-1602880200
>   uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
>   resourceVersion: '255447945'
>   creationTimestamp: '2020-10-16T20:30:02Z'
>   labels:
>     controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
>     job-name: job-xxx-1602880200
>   ownerReferences:
>     - apiVersion: batch/v1beta1
>       kind: CronJob
>       name: job-xxx
>       uid: 33ac928e-2104-11ea-a439-0e9b9d35598c
>       controller: true
>       blockOwnerDeletion: true
> spec:
>   parallelism: 1
>   completions: 1
>   backoffLimit: 0
>   selector:
>     matchLabels:
>       controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
>   template:
>     metadata:
>       creationTimestamp: null
>       labels:
>         controller-uid: 44f7bd7a-064e-45db-b7ca-f497f4b39267
>         job-name: job-xxx-1602880200
>     spec:
>       containers:
>         - name: job-xxx
> 		  # ... snip ...
>           terminationMessagePath: /dev/termination-log
>           terminationMessagePolicy: File
>           imagePullPolicy: IfNotPresent
>       restartPolicy: Never
>       terminationGracePeriodSeconds: 30
>       dnsPolicy: ClusterFirst
>       securityContext: {}
>       schedulerName: default-scheduler
> status:
>   conditions:
>     - type: Failed
>       status: 'True'
>       lastProbeTime: '2020-10-16T20:32:08Z'
>       lastTransitionTime: '2020-10-16T20:32:08Z'
>       reason: BackoffLimitExceeded
>       message: Job has reached the specified backoff limit
>   startTime: '2020-10-16T20:30:02Z'
>   failed: 1
> ```
> 
> I can see that the ResourceVersion of the job did actually change, so perhaps something did in fact modify the Job.
> 
> The only suspicious thing I can see around that time is that our CI did update the cronjob. It should have been a no-op since we didn't really make any changes, but that script is just running kustomize and applying all files even though they haven't changed. Perhaps there's some glitch with kubectl apply that is bumping the resource version on the cronjob, which causes the job to have its resource version bumped, which causes the pod to be restarted.
> 
> I think it would be better if the job would NOT start a new pod if one were already running if it gets updated. Or it could perhaps gracefully terminate the existing pod before starting a new one. Or make this behavior configurable.

Have you found any solution to the problem.

**Comment by dobesv** [comment]
> Have you found any solution to the problem.

I have not.

**Comment by dobesv** [comment]
The workaround is to avoid updating cron job configurations while jobs are running I guess.

**Comment by mpucholblasco** [comment]
Not sure if this could be your case, but we had the same problem, and, in our case, was [Cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) doing its job:
```
I0316 04:57:53.391259       1 scale_down.go:930] Scale-down: removing node ip-10-0-102-7.eu-west-1.compute.internal, utilization: {0.3022959183673469 0.42156662498521164 0 memory 0.42156662498521164}, pods to reschedule: prod/podname
```
In our case, it has been a bad configuration, as we could prevent this behaviour by adding the following annotation to pods (according to https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node):
```
"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
```

**Comment by monofone** [comment]
> The `backoffLimit` is set to 1 also.

should be set to 0 and will then not take a second try to finish this job successfully
