### ISSUE TITLE
[deviceplugin] allocatable resource remains 0 after device-plugin restart

### ISSUE THREAD

**Issue by ikaven1024** [kubernetes/kubernetes#62773]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig node

**What happened**:
i register device by my deviceplugin. It works good. Then i stopmy plugin, k8s mark resources Unhealthy as expect. But when i restart plugin. The resource does not recover, remain allocatable  0.

**What you expected to happen**:
Resource turns healthy when plugin restart.

**How to reproduce it (as minimally and precisely as possible)**:
1. start k8s
2. start device plugin
3. stop device plugin
4. restart device plugin

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ikaven1024** [comment]
https://github.com/kubernetes/kubernetes/blob/5514a1f4dd60b35b4b9d4915744ec65aab40938f/pkg/kubelet/cm/devicemanager/manager.go#L389-L400

devicemanger set devices unhealthy when socket closed. But devices in endpoint, devices remain health, and will not call callback function when watched new device request (due to same health), and devicemanger' devices will never recover.
https://github.com/kubernetes/kubernetes/blob/5514a1f4dd60b35b4b9d4915744ec65aab40938f/pkg/kubelet/cm/devicemanager/manager.go#L335-L344

**Comment by bart0sh** [comment]
@ikaven1024 I was able to reproduce this.

@RenaudWasTaken would this be a proper fix or we need something more sophisticated?

```
diff --git a/pkg/kubelet/cm/devicemanager/manager.go b/pkg/kubelet/cm/devicemanager/manager.go
index f415181dff..afa004ec71 100644
--- a/pkg/kubelet/cm/devicemanager/manager.go
+++ b/pkg/kubelet/cm/devicemanager/manager.go
@@ -375,6 +375,7 @@ func (m *ManagerImpl) addEndpoint(r *pluginapi.RegisterRequest) {
                m.mutex.Lock()
                if old, ok := m.endpoints[r.ResourceName]; ok && old == e {
                        m.markResourceUnhealthy(r.ResourceName)
+                       delete(m.endpoints, r.ResourceName)
                }
                glog.V(2).Infof("Unregistered endpoint %v", e)
                m.mutex.Unlock()
```

**Comment by jiayingz** [comment]
I thought when the new device plugin re-registers, we would create a new endpoint.

**Comment by jiayingz** [comment]
Ah @bart0sh I think I see your point. The fix you proposed in https://github.com/kubernetes/kubernetes/issues/62773#issuecomment-383686100 sounds reasonable, but we may need to expose a function from endpoint.go with proper locking.

**Comment by jiayingz** [comment]
Btw, when we are fixing this, I think we should extend the existing test/e2e_node/[gpu_]device_plugin.go to verify the fix by restarting the device plugin and waiting for resource allocatable change. We once had that test coverage in test/e2e/scheduling/nvidia-gpus.go but somehow lost it through some code changes.

**Comment by vishh** [comment]
[Posting offline question] Why is state stored both in endpoints and device manager?

**Comment by jiayingz** [comment]
I have a vague memory that we had some similar discussion before and am trying to remember the reason why the code was structured this way. I think one reason is perhaps that we want to prevent a single buggy device plugin from DOS device manager with flooding ListAndWatch updates by having its endpoint filter out unnecessary updates.

@RenaudWasTaken do you remember any other reasons?

**Comment by RenaudWasTaken** [comment]
Endpoints stores device state whereas manager stores "API server" state.
These two states are very similar but different.

One always has the latest device state. The other is in charge of reporting what devices changed to an unhealthy state and to delete the resource after a certain set of time.

So we're not really storing the state twice :)

**Comment by vishh** [comment]
It might be simpler to make endpoints lean and store all state within the
device manager to avoid synchronisation issues.

**Comment by vikaschoudhary16** [comment]
I doubt that any of the fix that @bart0sh mentioned will work. Problem is this -- devices are being copied with health as "Healthy" from old endpoint to new endpoint, https://github.com/kubernetes/kubernetes/blame/5514a1f4dd60b35b4b9d4915744ec65aab40938f/pkg/kubelet/cm/devicemanager/manager.go#L348

And then marking those devices unhealthy in device manager. So what @jiayingz was saying is correct that we create a new endpoint and in the fix , we should update devices health in new endpoint. @bart0sh is suggesting to update health of devices in old endpoint and that will not help.

I will post a fix soon today.

**Comment by vikaschoudhary16** [comment]
@jiayingz will handle e2e in a separate PR shortly.

**Comment by vikaschoudhary16** [comment]
> It might be simpler to make endpoints lean and store all state within the
device manager to avoid synchronisation issues.

then grpc calls will have to be protected with mutex.

**Comment by bart0sh** [comment]
@vikaschoudhary16 

> I would prefer option 1 because in option2 there could be a race if device health gets updated to "unhealthy" after ListAndWatch() got invoked in e.run().

Your fix looks quite implicit in my opinion. It sets device health to Unhealthy in addEndPoint, which is called from Register. This might look confusing. It looks like we make new endpoint unhealthy when we register new resource.

My fix synchronises device manager and endpoint health exactly when resource is set to unhealthy state. The code is covered by mutex, so I don't see why it would race. Even if it would I'd argue that your fix could cause future confusions and should be reworked/

@jiayingz thanks for the suggestion to move this functionality into endpoint.go. I agree with this. Also calling it from markResourceUnhealthy may look better than my sketchy proposal.

Thoughts?

**Comment by bart0sh** [comment]
@vikaschoudhary16
> I doubt that any of the fix that @bart0sh mentioned will work. Problem is this -- devices are being copied with health as "Healthy" from old endpoint to new endpoint

I tested my fix before posting here. It worked.

As for your comment - devices are copied from old to new endpoint with the old state: https://github.com/kubernetes/kubernetes/blame/5514a1f4dd60b35b4b9d4915744ec65aab40938f/pkg/kubelet/cm/devicemanager/manager.go#L341 and then passed to newEndpointImpl as existingDevs variable.

**Comment by vikaschoudhary16** [comment]
> I tested my fix before posting here. It worked.

My guess is that you might not have hit the race condition in your local testing. If devices are marked unhealthy from within goroutine, like you suggested, this will race against the thread which will invoke `ListAndWatch` for the new endpoint. And if first thread got late in marking devices unhealthy, callback from the endpoint.go will not be invoked.

**Comment by RenaudWasTaken** [comment]
@vikaschoudhary16 See my comment son your PR #63118 :

> Sorry I didn't have a lot of time to look at this issue in detail.

> Looking a bit more at the code it seems to me like the "device state" and "API server state" are not really separated which leads in this case to working on the "device state" to fix an "API server state" issue.

> "device state" = devices stored in the endpoint
> "API server state" = devices stored in the manager which will be fed to the API server in Capacity and Allocatable

> What do you think if we fixed the issue as following:
> - When creating an endpoint use the devices from the "API server state" (devices will necessarily be in 
 Unhealthy state if the endpoint was lost)
> - Move the "stop time" to the "API server state"
> - Make the endpoint's lifetime be as short as the gRPC connection

**Comment by fabiand** [comment]
Is this fixed in 1.10 and/or 1.11?

**Comment by RenaudWasTaken** [comment]
I believe 1.9.5, 1.9.6, 1.10.0 1.10.1, 1.10.2 are the only releases affected by this bug.

**Comment by fabiand** [comment]
Thanks @RenaudWasTaken
