### ISSUE TITLE
fluentd-es cannot connect to api server on kubernetes 1.9.6

### ISSUE THREAD

**Issue by Hubery2757** [kubernetes/kubernetes#62770]
> /kind bug

I used kubeadm init to deploy kubernetes 1.9.6, then
I deploy EFK on kubernetes 1.9.6, but fluentd-es cannot connect to api server, the logs as below:

2018-04-18 07:49:06 +0000 [error]: config error file="/etc/fluent/fluent.conf" error="Invalid Kubernetes API v1 endpoint https://10.96.0.1:443/api: Timed out connecting to server"

fluentd-es-configmap.yaml:
https://github.com/kubernetes/kubernetes/blob/release-1.9/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml

fluentd-es-ds.yaml:
https://github.com/kubernetes/kubernetes/blob/release-1.9/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml

api-server config:

- command:
    - kube-apiserver
    - --requestheader-username-headers=X-Remote-User
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --secure-port=6443
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --insecure-port=8080
    - --insecure-bind-address=0.0.0.0
    - --requestheader-group-headers=X-Remote-Group
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --allow-privileged=true
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --advertise-address=192.168.61.32
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
    - --enable-bootstrap-token-auth=true
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --requestheader-allowed-names=front-proxy-client
    - --authorization-mode=AlwaysAllow,Node,RBAC
    - --etcd-servers=http://127.0.0.1:2379
    - --basic-auth-file=/etc/kubernetes/pki/basic_auth.csv
    - --anonymous-auth=false
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.9.6

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration: 3 openstack vm:1 master, 2 worker
- OS (e.g. from /etc/os-release): centos 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools:
- Others:

**Comment by phagunbaya** [comment]
Experiencing the same. Any help?
