### ISSUE TITLE
Prompt “node has joined the cluster“”，but by "kubectl get nodes" still not query this node 

### ISSUE THREAD

**Issue by justmine66** [kubernetes/kubernetes#62776]
![image](https://user-images.githubusercontent.com/23122801/38926048-eeb3a962-4333-11e8-9f85-c5afde5f581c.png)
![image](https://user-images.githubusercontent.com/23122801/38926052-f2ff5c8c-4333-11e8-82bb-cb2a1ef2cc79.png)

why? Have anyone ever met this problem ? thank you very much indeed。

**Comment by dims** [comment]
please open in https://github.com/kubernetes/kubeadm/issues

/close

**Comment by justmine66** [comment]
The problem has been solved，Tokon expired
Regenerate a token: `kubeadm token create`, then 'kubeadm join'

Hoping kubernetes to improve 'kubeadm join' decription information and increase `the expired description of the token` tips.This will Improve the efficiency of work，tks !!!
