### ISSUE TITLE
Promote CustomResourceSubresources to beta in 1.11

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#62786]
Subresources for custom resources was added as an alpha feature `CustomResourceSubresources` in v1.10 in https://github.com/kubernetes/kubernetes/pull/55168.

We can move this feature to beta in 1.11. I don't think we have any blockers for promoting it to beta now. If you think of any, please comment below.

/cc @sttts @deads2k @liggitt @lavalamp @enisoc 

/sig api-machinery
/area custom-resources

**Comment by sttts** [comment]
lgtm.

**Comment by lavalamp** [comment]
cc @mbohlool

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/63359

**Comment by deads2k** [comment]
This seems like a good idea to me. 

Tidy up that referenced issue first though.

**Comment by nikhita** [comment]
Changes to be made before going to beta:

- [ ] Disallow update to _all_ fields (not just spec and metadata) during `/status` updates - https://github.com/kubernetes/kubernetes/pull/63385, https://github.com/kubernetes/kubernetes/issues/63359
- [ ] Allow `required` to be used in the CRD OpenAPI validation schema when the `/status` subresource is enabled - https://github.com/kubernetes/kubernetes/pull/63533

**Comment by guineveresaenger** [comment]
Minor housekeeping request - 

Could we tag this and https://github.com/kubernetes/kubernetes/pull/63598 with the 1.11 milestone, for tracking purposes for 1.11 release?
