### ISSUE TITLE
Lack of documentation for ImagePullBackOff timing

### ISSUE THREAD

**Issue by alexpirine** [kubernetes/kubernetes#62788]
Hello,

I might have missed it, but I am unable to find documentation about ImagePullBackOff timing.

Specifically: how long does it take for a retry to take place after ImagePullBackOff error occured?

Is this something that can be configured? In the deployment or cluster scope?

**Comment by jethrogb** [comment]
Another fantastic Kubernetes issue closed without resolution

**Comment by alexpirine** [comment]
Who can be assigned to this?

**Comment by wulftone** [comment]
I would love an answer to this question.  Someone must know!

**Comment by emalamisura-c2m** [comment]
https://github.com/kubernetes/kubernetes/blob/d24fe8a801748953a5c34fd34faa8005c6ad1770/pkg/kubelet/kubelet.go

Its 300 seconds.

**Comment by elucidsoft** [comment]
https://github.com/kubernetes/kubernetes/blob/d24fe8a801748953a5c34fd34faa8005c6ad1770/pkg/kubelet/kubelet.go

Its 300 seconds.

**Comment by elucidsoft** [comment]
Are we still talking about GitHub or the fridge?

**Comment by matthyx** [comment]
assigned to @tech-geek29 (not org member)

**Comment by adisky** [comment]
I think this document can be updated on this issue

**Comment by adisky** [comment]
and the related code could be find here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L589
