### ISSUE TITLE
UnmountVolume.TearDown fails for AzureFile volume, locks up node

### ISSUE THREAD

**Issue by j03wang** [kubernetes/kubernetes#62824]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Once every so often, (I'm guessing when there's a connection issue with Azure Files), the unmount as part of deleting a pod will fail:

`nestedpendingoperations.go:263] Operation for "\"kubernetes.io/azure-file/cc5c86cd-422a-11e8-91d7-000d3a03ee84-myvolume\" (\"cc5c86cd-422a-11e8-91d7-000d3a03ee84\")" failed. No retries permitted until 2018-04-17 10:35:40.240272223 +0000 UTC m=+1185722.391925424 (durationBeforeRetry 500ms). Error: "UnmountVolume.TearDown failed for volume \"myvolume\" (UniqueName: \"kubernetes.io/azure-file/cc5c86cd-422a-11e8-91d7-000d3a03ee84-myvolume\") pod \"cc5c86cd-422a-11e8-91d7-000d3a03ee84\" (UID: \"cc5c86cd-422a-11e8-91d7-000d3a03ee84\") : Error checking if path exists: stat /var/lib/kubelet/pods/cc5c86cd-422a-11e8-91d7-000d3a03ee84/volumes/kubernetes.io~azure-file/myvolume: resource temporarily unavailable`

When this happens, all subsequent pods scheduled on this node that try to mount the same volume will fail to do so. The following message then beings to repeat:

`kubelet_volumes.go:128] Orphaned pod "380b02f3-422b-11e8-91d7-000d3a03ee84" found, but volume paths are still present on disk`

and the CPU iowait spikes and processing on the node slows to a crawl.

![cpu](https://user-images.githubusercontent.com/1124207/38967517-407cbfec-433c-11e8-800c-88f738f4d630.png)

**What you expected to happen**:

The volume should successfully unmount at some point and there should be no orphaned pod.

**How to reproduce it (as minimally and precisely as possible)**:

I'm encountering this kind of behavior on a set of nodes running Spark batch jobs, where there are driver and executor pods constantly being created and torn down. These pods are configured to mount an AzureFile volume for reading configuration and data. To reproduce something like this would probably just be to setup a job that stresses pod creating/deletion with an AzureFile mount, though I'm guessing the right network conditions need to exist in order for the CIFS path to result in "resource temporarily unavailable"

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4
- Kernel (e.g. `uname -a`): 4.13.0-1012-azure
- Install tools: acs-engine 0.14.2
- Others:

**Comment by andyzhangx** [comment]
@j03wang could you attach the whole kubelet logs on that agent node? And also do you have a simple config to repro this issue easily?

**Comment by andyzhangx** [comment]
@j03wang This issue is fixed by https://github.com/kubernetes/kubernetes/pull/52324, fixed in v1.8.8, v1.9.7 and v1.10.0. The repro is easy:
 - create a pod with azure file mount
 - regenerate the account key of the storage account
 - delete the pod, and the pod will never be deleted due to UnmountVolume.TearDown error

**Comment by j03wang** [comment]
Thanks for the rca! Guess it's too bad that 1.9.7 hasn't been released yet.

**Comment by andyzhangx** [comment]
I will close this issue since it's been fixed, just let me know if you any other question.
/close
