### ISSUE TITLE
Strategic merge patch sort causes confusion

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#62830]
**What happened**:
While working on a kubelet node status update bug, I noticed that 2 way strategic merge patch does sorting of elements in the slice. This was causing problems when items are appended to original slice in unsorted fashion as part of request sent to patch. For example while setting node addresses with following values

```
node.Status.Addresses = 
 append(
          []v1.NodeAddress{
		{
			Address: "132.143.154.163",
			Type:    v1.NodeExternalIP,
		},
		{
			Address: "127.0.0.1",
			Type:    v1.NodeInternalIP,
		},
           }, 
          v1.NodeAddress{ 
                        Address: "127.0.0.1", 
                        Type: v1.NodeExternalIP,
                   },
          v1.NodeAddress{
                        Address: "132.143.154.163", 
                        Type: v1.NodeInternalIP
  })
```
, I am noticing the following error:
```
[map[address:127.0.0.1 type:ExternalIP] map[address:132.143.154.163 type:ExternalIP] map[address:127.0.0.1 type:InternalIP] map[address:132.143.154.163 type:InternalIP]]
                                                                            
 doesn't match $setElementOrder list:                                                         

[map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP] map[type:Hostname]]
```

On further debugging, I noticed that 

Original slice sorted:
```[map[address:132.143.154.163 type:ExternalIP] map[type:InternalIP address:127.0.0.1]]```

Modified Slice unsorted:
```
[map[type:ExternalIP address:132.143.154.163] map[type:InternalIP address:127.0.0.1] map[type:ExternalIP address:127.0.0.1] map[type:InternalIP address:132.143.154.163]]
```
Modified Slice sorted:
```
[map[type:ExternalIP address:127.0.0.1] map[type:ExternalIP address:132.143.154.163] map[type:InternalIP address:127.0.0.1] map[type:InternalIP address:132.143.154.163]]
```

We are using Modified slice sorted for patching which causes patch operation to fail with above error.

In case I give sorted order based on type where ExternalID comes first for example: 

```
node.Status.Addresses = 
 append(
          []v1.NodeAddress{
		{
			Address: "132.143.154.163",
			Type:    v1.NodeExternalIP,
		},
		{
			Address: "127.0.0.1",
			Type:    v1.NodeExternalIP,
		},
           }, 
          v1.NodeAddress{ 
                        Address: "127.0.0.1", 
                        Type: v1.NodeInternalIP,
                   },
          v1.NodeAddress{
                        Address: "132.143.154.163", 
                        Type: v1.NodeInternalIP
  })
```

 we don't get that error. IIUC, the line https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L725 is causing strategic merge to sort in this case by type field. I believe the sorting is there for a reason but is the failure expected?

/sig api-machinery
/sig node

**Comment by mengqiy** [comment]
The bug is not really caused by the `$setElementOrder` stuff.
The bug is that `NodeAddress` is [`Type` as mergeKey](https://github.com/kubernetes/kubernetes/blob/18f6d75fcffeb0e7dc1787ce40d3e5a1dd46a8d3/staging/src/k8s.io/api/core/v1/types.go#L3725) can't uniquely identify a `NodeAddress` entry. 
If you have more than one entries with the same mergeKey value, you will get unexpected behavior. Because strategic merge patch (SMP) only supports 1 mergeKey.

In your case,
```
{
  Address: "132.143.154.163",
  Type:    v1.NodeExternalIP,
}
```
and
```
{
  Address: "127.0.0.1",
  Type:    v1.NodeExternalIP,
}
```
are using the same mergeKey `Type: v1.NodeExternalIP`, SMP can't distinguish them and will do something wrong.

`Port` has the same issue: https://github.com/kubernetes/kubernetes/issues/39188

**Comment by mengqiy** [comment]
The title is misleading. It should be changed to `v1.NodeAddress need more than one mergeKey for strategic merge patch to identify`

**Comment by RobertKrawitz** [comment]
Allowing multiple keys alone won't solve this -- there needs to be a stable sort (relative to the order in the patch) in the case of IP addresses, since IP addresses don't have a meaningful sort order.

**Comment by NeilW** [comment]
Getting similar issues on the cloud controller if you have multiple external IPs

The error is

```
E0821 10:47:34.158656       1 node_controller.go:188] Error patching node with cloud ip addresses = [failed to patch status "{\"status\":{\"$setElementOrder/addresses\":[{\"type\":\"Hostname\"},{\"type\":\"InternalDNS\"},{\"type\":\"InternalIP\"},{\"type\":\"InternalIP\"},{\"type\":\"ExternalIP\"},{\"type\":\"ExternalDNS\"},{\"type\":\"ExternalIP\"},{\"type\":\"ExternalDNS\"}],\"addresses\":[{\"address\":\"109.107.37.240\",\"type\":\"ExternalIP\"},{\"address\":\"109.107.35.7\",\"type\":\"ExternalIP\"},{\"address\":\"cip-8fp4v.gb1.brightbox.com\",\"type\":\"ExternalDNS\"},{\"address\":\"cip-2mse0.gb1.brightbox.com\",\"type\":\"ExternalDNS\"}]}}" for node "srv-tryop": The order in patch list:
[map[address:109.107.37.240 type:ExternalIP] map[address:109.107.35.7 type:ExternalIP] map[address:cip-8fp4v.gb1.brightbox.com type:ExternalDNS] map[address:cip-2mse0.gb1.brightbox.com type:ExternalDNS]]
 doesn't match $setElementOrder list:
[map[type:Hostname] map[type:InternalDNS] map[type:InternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:ExternalDNS] map[type:ExternalIP] map[type:ExternalDNS]]
]
```

**Comment by RobertKrawitz** [comment]
@NeilW see https://github.com/kubernetes/kubernetes/pull/79391 and https://github.com/kubernetes/kubernetes/pull/80747.

@danwinship note
