### ISSUE TITLE
kubectl diff command

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#6284]
It'd be great if user could diff current configuration with the one in a file. I imagine output to be a regular smart diff of JSON files (ignoring version, status etc).

**Comment by kbeecher** [comment]
I take it you mean something like this?

`$ kubectl diff service my-service my-service.json`

And that would output, for example:

```
{
   "kind":"Service",
   "apiVersion":"v1beta3",
   "metadata":{
      "name":"redis-master",
      "labels":{
         "name":"redis-master"
      }
   },
   "spec":{
      "ports": [
        {
-          "port":6379,
+          "port":6380
        }
      ],
      "selector":{
         "name":"redis-master"
      }
   }
}
```

Of course, this should work with YAML too.

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by bgrant0607** [comment]
diff is a building block needed for configuration reconciliation (#1702), so I'd like to get this in.

**Comment by mikedanese** [comment]
Assigning to @jlowdermilk as he has the PR assigned to him.

**Comment by krmayankk** [comment]
What is the status of this , is this still a priority ?

**Comment by bgrant0607** [comment]
@krmayankk Yes, we would like this to be implemented.

kubectl apply performs a diff and generates a patch. The code is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go

Possibly one way to start would be to add --dry-run to kubectl apply so that it would print the patches it generated.

**Comment by krmayankk** [comment]
@bgrant0607 does this diff take into account the default values and ignores them in the diff ? Many fields in the local file are not populated and get default values, are they flagged as diffs ?

**Comment by bgrant0607** [comment]
@krmayankk 

The patch generated should not contain the defaults. Think of it as a 3-way merge. It's not just defaults, but all fields set during/after creation.

For more info, see:

#15894
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#defaulting
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#late-initialization
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#strategic-merge-patch

**Comment by arashbina** [comment]
I like to contribute and looking for a task to start. Not sure if @krmayankk is working on this but if no one has taken this on I can work on it.

**Comment by janetkuo** [comment]
@fraenkel has a PR #31892 addressing this with `kubectl apply --dry-run`, instead of `kubectl diff`.

**Comment by janetkuo** [comment]
> I like to contribute and looking for a task to start. 

@arashbina Not sure if you already know about this -- we have the kubectl roadmap here: https://github.com/kubernetes/community/wiki/Roadmap:-kubectl

**Comment by arashbina** [comment]
@janetkuo I didn't know about the roadmap. Thanks. I'll check it out.

**Comment by neelance** [comment]
@janetkuo Is this still planned? I would like to see if a `kubectl apply` would actually change something or not, to determine if the cluster state is actually in sync with the files describing the resources.

As far as I can see, #31892 would have added that feature, but it got superseded by #31892 which also adds `--dry-run`, but without the "diff" functionality.

**Comment by kargakis** [comment]
@neelance https://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-cli/kubectl_apply_getsetdiff_last_applied_config.md should handle your case.

**Comment by fgrzadkowski** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by shiywang** [comment]
I'm work on a new command `kubectl apply diff-last-applied` here https://github.com/kubernetes/kubernetes/pull/46560, I think part of the code could be reuse, if there any one already taken this yet ? if not, I would like to do that

**Comment by janetkuo** [comment]
`kubectl diff` has been implemented as an alpha release in 1.9. Feature tracking issue: https://github.com/kubernetes/features/issues/491

**Comment by cmrust** [comment]
@gjcarneiro I agree that this behavior should be documented (and tested if it isn't already), but I'd like to point out that this is how the linux `diff` cli tool works as well and I imagine this was implemented this way purposefully and is likely safe to rely upon.

**Comment by apelisse** [comment]
> @gjcarneiro I agree that this behavior should be documented (and tested if it isn't already), but I'd like to point out that this is how the linux diff cli tool works as well and I imagine this was implemented this way purposefully and is likely safe to rely upon.

Correct, but we still should document that none-the-less. Thanks for the interest.

**Comment by praseodym** [comment]
https://github.com/kubernetes/kubectl/issues/707 was created to improve the exit code behaviour, hopefully this will result in some documentation as well.
