### ISSUE TITLE
e2e network/config-map - adapt the ConfigMap change depending the kind of DNS Server running.

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#62865]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
the 3 existing e2e test  in the file : test/e2e/network/dns_configmap.go
are testing the capability of changing configuration parameters for kube-dns. (federations, upstreamNameservers and stubDomains)

it is specific to kube-dns DNS Server.

As we plan to move to CoreDNS DNS Server as default, we need to ensure that these tests are updating the Configmap corresponding to the DNS server running in k8s.

**What you expected to happen**:

The preparation of the test should depend of the DNS Server running:
- check the name of the DNS pode (containing "kube-dns" or "coredns")
- the ConfigMap is selected the same way for both servers (k8s-app=kubedns)
- the value and change to apply to the ConfigMap depends of the server
- the DIG test and expectation should be the same whatever the server.

**Also verify/transform in order to make it IPv6 compatible**

**Comment by fturib** [comment]
@MrHohn @bowei : do you agree with this change for config-map e2e tests ?

**Comment by MrHohn** [comment]
> As we plan to move to CoreDNS DNS Server as default, we need to ensure that these tests are triggered only of kube-dns is activated on the cluster.

At the first glance at the KEP PR (https://github.com/kubernetes/community/pull/1956) it sounds like coredns is going to have an equivalent configmap (in Corefile format?) that user can tweak. Are we planing to reuse the tests as the behavior will be similar, or writng brand new tests?

**Comment by fturib** [comment]
@MrHohn : you may be right. Although we have similar UT, it is maybe better to verify we can do the same behavior with our own config-map in k8s.

@rajansandeep volunteered to take care of that issue. I will change the title.
