### ISSUE TITLE
GCE: ILB's backend service isn't updated with new instance group links

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#62878]
/kind bug

**What happened**:
1. Create an ILB by adding the correct annotation to a Service with type LoadBalancer.
2. Add nodes to the cluster from a new zone
3. Observe that the ILB's backend service did not get updated 

**Mediation**:
Modifying the service spec (can add an annotation) will cause a full sync and update the backend service correctly. 

/assign
/sig gcp

**Comment by Stono** [comment]
Hey, 
Any change we could confirm a GKE release date for this fix.  It has resulted in a service outage for us twice now.

The workaround for others struggling with this pain is to trigger a node pool resize, which in turn reconfigures the backend-service correctly.
