### ISSUE TITLE
"Kubernetes Dashboard should check that the kubernetes-dashboard instance is alive" test is broken on 1.10 GKE

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/kubernetes#62875]
This test is consistently failing and it's a blocking test for 1.10 patch releases. 
 
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gci-gke-1.10&include-filter-by-regex=Dashboard

/king bug

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/62558 ?

**Comment by MaciekPytel** [comment]
Right, missed that, sorry.
/close
