### ISSUE TITLE
initContainer exit Code is not same as the exit code of its internal process

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kubernetes#62899]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

**What happened**:
I am using initContainer to initialize my pod. The process (node.js script) inside the initContianer exits with some exitCode based on some logic. But I have noticed that the Exit Code of InitContianer is not the same which I returned from the internal process. I exited the initContianer internal process with exit code 302 but the Exit Code shown at kubectl describe is 46. 

**What you expected to happen**:
The exit code of initContainer should be 302.

**How to reproduce it (as minimally and precisely as possible)**:
Run some program inside initcontainer and return differnet exit codes each time and check if the Exit Code of initContainer is same or not.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Minikube
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
@mfaizanse 0-255 can be set as a return code in linux, and 302-256=46

**Comment by mfaizanse** [comment]
got it . thanks
