### ISSUE TITLE
Error: unknown flag: --basic_auth_file "kube-apiserver version v1.10.1”

### ISSUE THREAD

**Issue by Jacky2** [kubernetes/kubernetes#62891]
**What happened**:
 sig: @kubernetes/sig-kube-apiserver

Why do I use kubernetes version v1.10.1 kube-apiserver to use parameter --basic_auth_file?

Prompt：
Error: unknown flag: --basic_auth_file

But in kube-apiserver version v1.9.3, it can run.

**Comment by Jacky2** [comment]
@hanxiaoshuai  Thank you so much,It did solve the problem.

**Comment by CaoShuFeng** [comment]
@Jacky2 
mind close this issue?
