### ISSUE TITLE
failed to "StartContainer" for "etcd" with CrashLoopBackOff Ubuntu:17.10

### ISSUE THREAD

**Issue by haddada** [kubernetes/kubernetes#62904]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>/kind bug
> /kind feature

**What happened**:
`kubectl get pods
`
`Unable to connect to the server: http2: server sent GOAWAY and closed the connection; LastStreamID=9, ErrCode=NO_ERROR, debug=""
`

**What you expected to happen**:
list pods

**How to reproduce it (as minimally and precisely as possible)**:

- update history 
`Commandline: aptdaemon role='role-commit-packages' sender=':1.23281'
Install: pigz:amd64 (2.3.4-1, automatic), nvidia-container-runtime-hook:amd64 (1.3.0-1, automatic)
Upgrade: nvidia-docker2:amd64 (2.0.2+docker17.12.0-1, 2.0.3+docker18.03.0-1), kubelet:amd64 (1.9.3-00, 1.10.0-00), friendly-recovery:amd64 (0.2.36, 0.2.36ubuntu1), libnvidia-container-tools:amd64 (1.0.0~alpha.3-1, 1.0.0~beta.1-1), nvidia-container-runtime:amd64 (1.1.1+docker17.12.0-1, 2.0.0+docker18.03.0-1), grub-common:amd64 (2.02~beta3-4ubuntu7.1, 2.02~beta3-4ubuntu7.3), libavahi-glib1:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), python3-aptdaemon.gtk3widgets:amd64 (1.1.1+bzr982-0ubuntu17, 1.1.1+bzr982-0ubuntu17.1), lshw:amd64 (02.18-0.1ubuntu4, 02.18-0.1ubuntu4.1), libavahi-common-data:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), slack-desktop:amd64 (3.0.5, 3.1.1), libavahi-common3:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), google-chrome-stable:amd64 (64.0.3282.186-1, 66.0.3359.117-1), plymouth-label:amd64 (0.9.2-3ubuntu17, 0.9.2-3ubuntu19), grub2-common:amd64 (2.02~beta3-4ubuntu7.1, 2.02~beta3-4ubuntu7.3), plymouth-theme-ubuntu-text:amd64 (0.9.2-3ubuntu17, 0.9.2-3ubuntu19), isc-dhcp-common:amd64 (4.3.5-3ubuntu2.2, 4.3.5-3ubuntu2.3), initramfs-tools-bin:amd64 (0.125ubuntu12, 0.125ubuntu12.1), libplymouth4:amd64 (0.9.2-3ubuntu17, 0.9.2-3ubuntu19), libavahi-ui-gtk3-0:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), libnvidia-container1:amd64 (1.0.0~alpha.3-1, 1.0.0~beta.1-1), grub-efi-amd64-bin:amd64 (2.02~beta3-4ubuntu7.1, 2.02~beta3-4ubuntu7.3), avahi-daemon:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), libavahi-core7:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), grub-efi-amd64:amd64 (2.02~beta3-4ubuntu7.1, 2.02~beta3-4ubuntu7.3), aptdaemon-data:amd64 (1.1.1+bzr982-0ubuntu17, 1.1.1+bzr982-0ubuntu17.1), avahi-autoipd:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), plymouth:amd64 (0.9.2-3ubuntu17, 0.9.2-3ubuntu19), python3-aptdaemon:amd64 (1.1.1+bzr982-0ubuntu17, 1.1.1+bzr982-0ubuntu17.1), grub-efi-amd64-signed:amd64 (1.85.1+2.02~beta3-4ubuntu7.1, 1.85.3+2.02~beta3-4ubuntu7.3), avahi-utils:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), kubeadm:amd64 (1.9.3-00, 1.10.0-00), aptdaemon:amd64 (1.1.1+bzr982-0ubuntu17, 1.1.1+bzr982-0ubuntu17.1), plymouth-theme-ubuntu-logo:amd64 (0.9.2-3ubuntu17, 0.9.2-3ubuntu19), kubectl:amd64 (1.9.3-00, 1.10.0-00), libavahi-client3:amd64 (0.6.32-1ubuntu1, 0.6.32-1ubuntu1.1), isc-dhcp-client:amd64 (4.3.5-3ubuntu2.2, 4.3.5-3ubuntu2.3), initramfs-tools-core:amd64 (0.125ubuntu12, 0.125ubuntu12.1), initramfs-tools:amd64 (0.125ubuntu12, 0.125ubuntu12.1), docker-ce:amd64 (17.12.0~ce-0~ubuntu, 18.03.0~ce-0~ubuntu), hdparm:amd64 (9.51+ds-1, 9.51+ds-1ubuntu0.1)
End-Date: 2018-04-20  09:51:23
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
`NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
`
- Kernel (e.g. `uname -a`):

`Linux sh-Hyrican-PC 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
`kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`
- Others:
`journalctl -fu kubelet`
`Error syncing pod 17c801f54fe8bd173a9f4810b4242bbb ("etcd-sh-hyrican-pc_kube-system(17c801f54fe8bd173a9f4810b4242bbb)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=etcd pod=etcd-sh-hyrican-pc_kube-system(17c801f54fe8bd173a9f4810b4242bbb)"
`

**Comment by shubheksha** [comment]
sig/cli
