### ISSUE TITLE
Cover Read and Write API endpoints for `/v1alpha1/priorityclasses/` in e2e tests

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#62906]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
Most of READ and WRITE operations are not covered for `/v1alpha1/priorityclasses/` API endpoints in e2e tests.

**What you expected to happen**:
Expecting to cover all READ and Write operations for PriorityClasses in e2e tests so that these would be ready to be considered for conformance tests.

API groups are -

HTTP Verbs | URLs
-- | --
DELETE | /apis/scheduling.k8s.io/v1alpha1/priorityclasses/{name}
GET | /apis/scheduling.k8s.io/v1alpha1/priorityclasses/{name}
PATCH | /apis/scheduling.k8s.io/v1alpha1/priorityclasses/{name}
PUT | /apis/scheduling.k8s.io/v1alpha1/priorityclasses/{name}
DELETE | /apis/scheduling.k8s.io/v1alpha1/priorityclasses
GET | /apis/scheduling.k8s.io/v1alpha1/priorityclasses
POST | /apis/scheduling.k8s.io/v1alpha1/priorityclasses

**How to reproduce it (as minimally and precisely as possible)**:

Needs to enable feature-gate for alpha features and pass below api-server flags while setting up cluster
-  `--feature-gate=AllAlpha=true,PodPriority=true`
pass runtime-config and admission-control flags to api-server
- `--runtime-config=scheduling.k8s.io/v1alpha1=true`
- `--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mgdevstack** [comment]
Issued PR : #62895

**Comment by spiffxp** [comment]
/close
I'm closing this under the auspices that under the effort to improve coverage of tests for conformance, we shouldn't be writing tests for alpha endpoints
