### ISSUE TITLE
[Question]Does kubelet can GC the dead docker containers?

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#62907]
I use the k8s 1.9.1 and create a statefulset to make my workload running on 3 separate nodes, after running about 4 weeks, one pods status change to `Terminating` and the docker container status was `dead`, and it seems kubelet did not recreate the new container and remove the `dead` one to recover the workload.

Does there need any configuration to GC the `dead` container?

**Comment by shubheksha** [comment]
kind/support

**Comment by wanghaoran1988** [comment]
@hchenxa FYI https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

**Comment by hchenxa** [comment]
@wanghaoran1988 , yes, I know that the k8s have gc which can delete the Exited docker container, but I am not sure if the docker container with status `dead` can be deleted or not.
