### ISSUE TITLE
Cover all API operations for `/v1/**/deployments/**` in e2e tests

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#62908]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Some of Deployment operations are not covered for `/v1/**/deployments/**` API endpoints in e2e tests.

**What you expected to happen**:
Expecting to cover all READ, Write, Status and Misc Deployment operations in e2e tests so that these would be ready to be considered for conformance tests.

[Operations Reference:-](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#deployment-v1-apps)

API Groups :

HTTP Verbs | URLs
-- | --
GET | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale
PATCH | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale
PUT | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/scale
GET | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/status
PATCH | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/status
PUT | /apis/apps/v1/namespaces/{namespace}/deployments/{name}/status
DELETE | /apis/apps/v1/namespaces/{namespace}/deployments/{name}
GET | /apis/apps/v1/namespaces/{namespace}/deployments/{name}
PATCH | /apis/apps/v1/namespaces/{namespace}/deployments/{name}
PUT | /apis/apps/v1/namespaces/{namespace}/deployments/{name}
DELETE | /apis/apps/v1/namespaces/{namespace}/deployments
GET | /apis/apps/v1/namespaces/{namespace}/deployments
POST | /apis/apps/v1/namespaces/{namespace}/deployments

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/remove-sig cli
/sig apps
this is part of ensuring we have sufficient coverage of all v1 workload api's in conformance tests, which would fall under aopps

**Comment by spiffxp** [comment]
/remove-sig testing
/area conformance
/priority important-longterm
Lower priority because conformance should be focused more on pod behavior less on workload api behavior
