### ISSUE TITLE
Two pod ips are same, one is controlled by deployment and the other by statefulset

### ISSUE THREAD

**Issue by ruanchen** [kubernetes/kubernetes#62935]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
When I restart kube master, i found there are two pods ips are same, one is controlled by deployment, and the other by statefulsets, which pod status was completed.
**What you expected to happen**:
Pods ip should be different.
**How to reproduce it (as minimally and precisely as possible)**:
Restart master node.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux k8s-test-bk-1 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
flanneld:v0.9.1

**Comment by ruanchen** [comment]
@kubernetes/sig-<scheduling>

**Comment by xiaoxubeii** [comment]
By default, flannel would use host-local ipam to allocate ips. Can you view /run/flannel/subnet.env for further information?

**Comment by ruanchen** [comment]
@xiaoxubeii Pod ips have been allocated by flannel's subnet, the question is the ips are same. Maybe the etcd or apiserver lead to the result, i need to  recurrent it.

**Comment by ruanchen** [comment]
I've found the reason, it's not a bug, when a pod's status is completed, another pod ip can be same with the completed pod it's normal.
