### ISSUE TITLE
3 Conformance test failed with Kubernetes 1.10.0

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#62944]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

 /kind bug

> /kind feature

**What happened**:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0+icp-ee", GitCommit:"9cb64de4ca4d039c35f4a29721aa5cf787648a15", GitTreeState:"clean", BuildDate:"2018-04-13T06:10:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0+icp-ee", GitCommit:"9cb64de4ca4d039c35f4a29721aa5cf787648a15", GitTreeState:"clean", BuildDate:"2018-04-13T06:10:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

e2e.log
[e2e.log](https://github.com/kubernetes/kubernetes/files/1935280/e2e.log)

/area conformance
/sig testing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyliu513** [comment]
/sig network

```
Summarizing 3 Failures:

[Fail] [sig-network] Proxy version v1 [It] should proxy through a service and a pod  [Conformance]
/workspace/anago-v1.9.4-beta.0.53+bee2d1505c4fe8/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:303

[Fail] [sig-network] Proxy version v1 [It] should proxy logs on node  [Conformance]
/workspace/anago-v1.9.4-beta.0.53+bee2d1505c4fe8/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:358

[Fail] [sig-network] Proxy version v1 [It] should proxy logs on node with explicit kubelet port  [Conformance]
/workspace/anago-v1.9.4-beta.0.53+bee2d1505c4fe8/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:358

Ran 125 of 782 Specs in 2767.260 seconds
FAIL! -- 122 Passed | 3 Failed | 0 Pending | 657 Skipped --- FAIL: TestE2E (2767.34s)
FAIL
```

**Comment by liggitt** [comment]
Ensure you are running the latest 1.9.x tests. 

Those tests were testing deprecated endpoints removed in 1.10

/close

**Comment by gyliu513** [comment]
@liggitt I was using Kubernetes 1.10.0 for the conformance test and also following steps here https://github.com/cncf/k8s-conformance/blob/master/instructions.md#running , I think all of the test should pass.

What do you mean `Ensure you are running the latest 1.9.x tests.`?

/open

**Comment by liggitt** [comment]
I see this in the tests: workspace/anago-v1.9.4

Those three specific tests were made conditional in v1.9.5 and no longer run against an apiserver >= 1.10.0

See https://github.com/kubernetes/kubernetes/compare/v1.9.4...v1.9.5#diff-e4236fde991a93836f485ce2d85ef8aa

**Comment by gyliu513** [comment]
@liggitt thanks, but the link you show me is empty

![image](https://user-images.githubusercontent.com/4461983/39103534-da33f0c0-46dd-11e8-82f5-e396a17176de.png)

Also I was using Kubernetes 1.10.0, why the conformance test still check the three specific test cases?

**Comment by liggitt** [comment]
The paths in your test output indicate you are running 1.9.4-level tests

Ensure you have these changes: https://github.com/kubernetes/kubernetes/pull/61135

**Comment by liggitt** [comment]
Actually, 1.9.4-beta.0, which is essentially 1.9.3

**Comment by liggitt** [comment]
Is it possible the gcr.io/heptio-images/kube-conformance:v1.9 hasn't been updated?

**Comment by gyliu513** [comment]
Let me try, I think the conformance image need to update to `gcr.io/heptio-images/kube-conformance:v1.9`

Thanks @liggitt

**Comment by gyliu513** [comment]
Fixed in https://github.com/cncf/k8s-conformance/pull/194
