### ISSUE TITLE
Option to enable net.ipv4.ip_forward for containers

### ISSUE THREAD

**Issue by calder** [kubernetes/kubernetes#62942]
/kind feature

Unprivileged containers mount `/proc` read-only, which prevents them from enabling `net.ipv4.ip_forward` in their own network namespace. Having the ability to enable `net.ipv4.ip_forward` for specific containers (without running them in `privileged` mode) would be useful for containers that implement routing functionality.

I tested that enabling `net.ipv4.ip_forward` in the container's namespace works as expected. To try it out, run the following on the kubelet:

```sh
sudo nsenter -t \
    $(docker inspect --format '{{.State.Pid}}' $CONTAINER_NAME) \
    -n sysctl -w net.ipv4.ip_forward=1
```

**Comment by calder** [comment]
@kubernetes/sig-network

**Comment by calder** [comment]
@kubernetes/sig-network-feature-requests

**Comment by faraazkhan** [comment]
@calder you can already do this via an annotation, however since this is  considered an unsafe sysctl, the cluster admin will have to whitelist it kubelet. See: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

**Comment by calder** [comment]
@faraazkhan: That's exactly what I was looking for, thanks!

**Comment by neyz** [comment]
I'm reopening this because even if I add --allowed-unsafe-sysctls net.ipv4.ip_forward to the kubelet arguments and this to my pod description it still starts with net.ipv4.ip_forward=0

"securityContext": {
                    "sysctls": [
                        {
                            "name": "net.ipv4.ip_forward",
                            "value": "1"
                        }
                    ]
                },

If I use nsenter on the node I can change the option.

I followed this documentation : https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

Running on coreOS and k8 1.11.2

Am I missing something ?

thanks !

**Comment by ggaurav10** [comment]
Hi,
I have been trying to enable `net.ipv4.ip_forward` in a statefulset by setting right values in securityPolicy of the podSpec part. I have created psp, clusterrole and the required clusterrolebinding to allow this. When I create the statefulset, evrything goes smoothly. However, when i check the value of `net.ipv4.ip_forward` after exec-ing into the container, I still see the value as 0.

The init container and the main container in the statefulset run as non-privileged.
Am I missing something here?

**Comment by ggaurav10** [comment]
Found out that if I run the pod in the host's network namespace, I can see the value if the flag `net.ipv4.ip_forward` value same as set in the host.
