### ISSUE TITLE
deficiencies of kubernetes for PaaS

### ISSUE THREAD

**Issue by behzadnm99** [kubernetes/kubernetes#62949]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

@kubernetes/sig scalability
in the documents of kube mentioned that , kube is not for PaaS.
here: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/#what-kubernetes-is-not

I want to know why the kube is not suitable for the pass?
And I want to know what are the things for paas kube doesnt have ? 
and what your Think about setting up a platform as a service using openshift origin ??

**Comment by xiaoxubeii** [comment]
As above doc said, Kubernetes is a container based resource management and schedule system, it more like a underlying infrastructure. You can build PaaS services on Kubernetes.

**Comment by jayunit100** [comment]
For a PAAS that provides the entire platform under the hood, try openshift, heroku, ...  we should close this most likely, unless your suggesting a specific README improvement?
