### ISSUE TITLE
why cann't ping svc,the kubernetes svc can ping access,others cannot

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#62986]
sh-4.2$ ping alpaca-pxc.default.svc.cluster.local    
PING alpaca-pxc.default.svc.cluster.local (10.233.37.69) 56(84) bytes of data.
^C
--- alpaca-pxc.default.svc.cluster.local ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms

sh-4.2$ ping kubernetes.default.svc.cluster.local     
PING kubernetes.default.svc.cluster.local (10.233.0.1) 56(84) bytes of data.
64 bytes from kubernetes.default.svc.cluster.local (10.233.0.1): icmp_seq=1 ttl=244 time=4.73 ms
64 bytes from kubernetes.default.svc.cluster.local (10.233.0.1): icmp_seq=2 ttl=244 time=4.55 ms
64 bytes from kubernetes.default.svc.cluster.local (10.233.0.1): icmp_seq=3 ttl=244 time=4.64 ms
64 bytes from kubernetes.default.svc.cluster.local (10.233.0.1): icmp_seq=4 ttl=244 time=4.33 ms
^C
--- kubernetes.default.svc.cluster.local ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 4.338/4.567/4.730/0.154 ms

**Comment by CaoShuFeng** [comment]
Is there any document said that we can ping a service?

**Comment by hzxuzhonghu** [comment]
service can be resolved as a clusterip, which can not ping.  
What's this `10.233.37.69`? The host ip?

**Comment by xiaoxubeii** [comment]
As @hzxuzhonghu said, kubernetes service is exposed by DNAT default, it cannot ping.
