### ISSUE TITLE
Conformance test should also cover RBAC

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#62988]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

The current conformance test do not cover RBAC part in Kubernetes, this should also be included.

/area conformance
/sig security

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
A cluster should probably not be required to use RBAC authorization to be considered conformant, though it's a good choice for most clusters. 

@kubernetes/sig-architecture-proposals is there any concept of "conformance profiles" yet?

**Comment by bgrant0607** [comment]
Profiles are still in the proposal stage AFAIK.

Yes, RBAC can't be required.

**Comment by spiffxp** [comment]
/remove-lifecycle stale

/remove-kind design
/remove-kind feature
/kind cleanup
This isn't about a new design or a new feature, but paying off tech (test) debt.

/remove-area conformance
For ease of triage, I'm removing the area/conformance label.  Reserving it for issues involving GA/non-optional/non-deprecated features until we have the concept of profiles in place.

**Comment by liggitt** [comment]
since RBAC is an optional feature, it isn't eligible for inclusion in conformance yet (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements)

once some concept of profiles are enabled, this can be revisited

/close
