### ISSUE TITLE
kubectl get nodes          Unable to connect to the server: net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by jiuchongxiao** [kubernetes/kubernetes#62997]
kubectl get nodes 
Unable to connect to the server: net/http: TLS handshake timeout    or      The connection to the server 192.168.0.17:6443 was refused - did you specify the right host or port?   once in a while 
why is it,who can help me  thanks?
 @kubernetes/sig-contributor-experience-test-failures
 @kubernetes/sig-contributor-experience-bugs
kubectl version     v1.10.1

**Comment by hzxuzhonghu** [comment]
192.168.0.17 not listen on 6443

**Comment by shubheksha** [comment]
@jiuchongxiao - can you please update your issue to follow the issue template? That'll make it easier to resolve it. Thanks!
