### ISSUE TITLE
Scheduler must watch all pods of the cluster, not just those that it is responsible for

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#63002]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Scheduler's pod informer has a selector that [watches only pods whose spec.schedulerName is equal to the name of the scheduler](https://github.com/kubernetes/kubernetes/blob/9b7439d77d0b29878ec3246271206050e22a3c7a/pkg/scheduler/factory/factory.go#L1275). This is incorrect. Scheduler must watch all the pods of the cluster, including those scheduled by other schedulers in order to update its cache of the state of the cluster. Otherwise, it will miss important events and the amount of available resources, pods on nodes, ... which are needed for scheduler to work correctly, will not be updated properly.

/sig scheduling
/assign

**Comment by bsalamat** [comment]
cc\ @jpbetz @cheftako

**Comment by aveshagarwal** [comment]
> This is incorrect. Scheduler must watch all the pods of the cluster, including those scheduled by other schedulers (including our own DaemonSet controller) in order to update its cache of the state of the cluster. 

For updating it cache, shouldn't the default scheduler rely on node info/status?

> Otherwise, it will miss important events and the amount of available resources, pods on nodes, ... which are needed for scheduler to work correctly, will not be updated properly.

Also its not very clear, what information the default scheduler needs from other pods (not to be scheduled by it) that it makes decision on?
 
Just trying to understand the issue more clearly.

**Comment by aveshagarwal** [comment]
> Scheduler must know what pods are placed on what nodes. For example, in order to check inter-pod affinity/anti-affinity it needs to know the placement of all the pods, including those scheduled by other schedulers.

But this information is present here: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedulercache/node_info.go#L40

**Comment by aveshagarwal** [comment]
So when I check the history, I see it was added here: https://github.com/kubernetes/kubernetes/pull/52479

**Comment by aveshagarwal** [comment]
@bsalamat have we seen any specific issues due to this change (like between default scheduler and DS controller)?

**Comment by bsalamat** [comment]
> But this information is present here: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedulercache/node_info.go#L40

Yes, but scheduler relies on its pod informers to keep this location up to date. That's exactly why it is important for the scheduler to receive updates for all the pods in the cluster.

> So when I check the history, I see it was added here: #52479

Yes. We missed the problem at the time.

> @bsalamat have we seen any specific issues due to this change (like between default scheduler and DS controller)?

This is problematic only in clusters that use multiple schedulers. I initially thought that DS controller could cause issues as well, but DS controller does not set `podSpec.schedulerName`, so it must not cause an issue.
We have seen instances of scheduler's missing certain events in cluster and as a result scheduler's cache getting stale, but I doubt if it is related to this particular issue. This only affects clusters with more than one scheduler. If you run the test that I have written in #63003 with the head, it will fail. That tests simulate a multi-scheduler scenario.
