### ISSUE TITLE
Create node labels from EC2 Tags

### ISSUE THREAD

**Issue by bchav** [kubernetes/kubernetes#63022]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What you expected to happen**:

[EC2 Tags](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) are useful for identifying types of compute resources for billing purposes, identifying ownership within your organization, segregating workloads, and more. Node labels are used for similar purposes, so it feels natural to expose Ec2 Tags (or a subset of them, perhaps based on a certain key prefix) to Kubernetes via Node Labels. 

Would love a discussion of how this behavior should be exposed. 

**Environment**:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): any 

/sig aws

**Comment by liggitt** [comment]
Is this something the cloud node controller could look up and add?

**Comment by xiaoxubeii** [comment]
Agree. And aws provider already had a implementation of tags: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/tags.go.

**Comment by gacopl** [comment]
and is there anyway to make AWS autoscale group place node labels ?

**Comment by denis111** [comment]
+1 here. We would like to have different autoscaling groups for dev and prod environments and use some labels for node affinity or node selector or taints to make production pods only run in production nodes. For now the only way to differentiate these nodes seems to use, for example, different instance type and use beta.kubernetes.io/instance-type label...

**Comment by gacopl** [comment]
I found solution. In Launch configuration, in user data you can add kubelet arguments (provided your flavour of AMI has proper bootstrap.sh) just add --node-labels=role=prod for example. It worked for me on EKS flavour ami

**Comment by liggitt** [comment]
> just add --node-labels=role=prod

be aware that that is an alpha feature currently in the process of being scoped down. see https://github.com/kubernetes/community/pull/911

**Comment by denis111** [comment]
@liggitt But reading the proposal https://github.com/mikedanese/community/blob/limit-node/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md I guess if I use, for example --node-labels=kubelet.kubernetes.io/role=prod then it would work?
If not then I think this proposal must not be merged until there's an alternative or workaround.

**Comment by liggitt** [comment]
> if I use, for example --node-labels=kubelet.kubernetes.io/role=prod then it would work

yes.

**Comment by woqer** [comment]
Any update on this? Is there anyway to use EC2 tags on Kubernetes nodes? let's say to filter them out on operations or just to show them up as a column on `kubectl get nodes`

**Comment by SaltedEggIndomee** [comment]
Autoscaler does not add label to newly added Node. Which makes it pretty much unusable in most scenarios, which uses nodeSelector

New Nodes DO NOT have label so HPA can't schedule Pods on the new Nodes. It will get stuck.

**Comment by abeer91** [comment]
@bchav Could you please reopen this issue?

**Comment by insider89** [comment]
It's really nice to have feature. It would be great to have it.

**Comment by Erokos** [comment]
Hi, any progress on this? I'm a bit confused looking at the correspondence, did I understand correctly that by adding something like
`--node-labels=role=prod` 
to my user data looking like this:

`/etc/eks/bootstrap.sh --use-max-pods true --b64-cluster-ca {aws_eks_cluster.eks_cluster.certificate_authority.0.data} \
  --apiserver-endpoint ${aws_eks_cluster.eks_cluster.endpoint} ${var.eks_cluster_name}`

end result:

`/etc/eks/bootstrap.sh --use-max-pods true --b64-cluster-ca {aws_eks_cluster.eks_cluster.certificate_authority.0.data} \
  --apiserver-endpoint ${aws_eks_cluster.eks_cluster.endpoint} ${var.eks_cluster_name} --node-labels=role=prod`

that this would work?

**Comment by Erokos** [comment]
By looking at the bootstrap.sh script, I'm not sure that it accepts node label settings. When specifying and trying out:
`/etc/eks/bootstrap.sh --use-max-pods true --b64-cluster-ca {aws_eks_cluster.eks_cluster.certificate_authority.0.data} \ --apiserver-endpoint ${aws_eks_cluster.eks_cluster.endpoint} ${var.eks_cluster_name} --kubelet-extra-args --node-labels=node.kubernetes.io/role=prod` 

or when specifying the kubelet.kubernetes.io/role label, neither one works.

**Comment by Erokos** [comment]
Sorry I was being inprecise, the labeling works, what I wantd was to create node roles. Once again sorry, my mistake.

**Comment by Luxbit** [comment]
+1
This would be really handy to create multiple node pools of the same instance type

**Comment by yardensachs** [comment]
So, looks like a solution is to use for now, is on your userdata content, you can add `kubelet-extra-args`.

Example:
```sh
/etc/eks/bootstrap.sh \
  ...
  --kubelet-extra-args '--node-labels=kevin-experiment-3=ok,kevin-experiment-4=ok'
  ...
```

**Comment by gacopl** [comment]
@yardensachs that one was around since ages, this is about making aws provider do things it should do since beginning

**Comment by yardensachs** [comment]
@gacopl Yea makes since, just ended up here after a google search.

**Comment by jafferaws** [comment]
Could any one of you give a solution to this issue I'm facing in labelling role to nodes duringAWS ASG scale-in for Kubernetes cluster.

https://github.com/kubernetes/kubernetes/issues/91664[Issue](https://github.com/kubernetes/kubernetes/issues/91664)
