### ISSUE TITLE
[sig-network] DNS configMap nameserver Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63028]
## Failing Job
[sig-release-master-blocking: gci-gke-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial)

## Failing Test
[[sig-network] DNS configMap nameserver Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/5640)

## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network&job=ci-kubernetes-e2e-gci-gke-serial&test=DNS%20configMap%20nameserver%20Forward%20external%20name%20lookup%20should%20forward%20externalname%20lookup%20to%20upstream%20nameserver

Has been failing consistently since 4/20. 

/kind bug
/priority failing-test
/priority important-soon
/sig network
/milestone v1.11
@kubernetes/sig-network-bugs 

cc @jberkus @tpepper

/assign @dcbw for triage

**Comment by MrHohn** [comment]
Fix rolled out on GKE. This test is no longer failing.
/close
