### ISSUE TITLE
Failing Test : [sig-testing] ci-kubernetes-e2e-gce-scale-correctness: BeforeSuite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63029]
## Failing Job
[sig-release-master-blocking#gce-scale-correctness](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness)

Failing Test
[[sig-testing] ci-kubernetes-e2e-gce-scale-correctness: BeforeSuite](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/102)

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-scale-correctness&test=BeforeSuite

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone v1.11
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper @shyamjvs 

/assign @BenTheElder  for triage

**Comment by cblecker** [comment]
Odd that this test is listed as a sig-testing owned test in the triage tool.. I'd think it would be scaleability.

**Comment by shyamjvs** [comment]
This issue has already been taken care of in https://github.com/kubernetes/kubernetes/issues/63006.

**Comment by shyamjvs** [comment]
This has now been fixed. See latest green run - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/104
