### ISSUE TITLE
GKE scalability jobs failing during Teardown

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#63026]
Our GKE scalability jobs (https://k8s-testgrid.appspot.com/sig-scalability-gke) are failing in the cluster teardown step (even though the e2e tests themselves passed). E.g failures:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-scale-correctness/10
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-scale-correctness/11

Seems like it's caused by some leaked network-related resources:

```
error deleting network: error during gcloud compute networks delete -q gke-scale-cluster --project=kubernetes-scale: exit status 1
```

/assign @krzysied 
Krzysiek - Could you PTAL into this when you find time? It'll be great to have our GKE suite back to green.

cc @kubernetes/sig-scalability-bugs @wojtek-t

**Comment by shyamjvs** [comment]
I think this is related to an earlier bug we've seen (similar one for GCE): https://github.com/kubernetes/kubernetes/issues/52347

Basically service-controller is creating some cloud resources (like firewalls) for lb-type services which are not brought down properly (due to lack of time?) when the k8s cluster is brought down.

**Comment by shyamjvs** [comment]
Also another related issue - https://github.com/kubernetes/kubernetes/issues/4630
There should also be an internal bug for this somewhere. IMO we should be able to fix this in test-infra (without waiting for proper long-term fix on gke side).

**Comment by krzysied** [comment]
https://github.com/kubernetes/test-infra/pull/7894
I am adding clean-up method. This way all of the firewall rules will be cleaned up after tests.
If this method has to remove any firewall rule, the teardown phase will return exception.

It's not a fix for the bug - it only allows us to easy isolate tests leaking firewall rules.

**Comment by krzysied** [comment]
Tests:
* should have session affinity work for LoadBalancer service with ESIPP on
* should be able to switch session affinity for LoadBalancer service with ESIPP on
* should have session affinity work for LoadBalancer service with ESIPP off
* should be able to switch session affinity for LoadBalancer service with ESIPP off
leak resources related to the LoadBalancer. PR #63489 will fix this.
