### ISSUE TITLE
kubectl allows editing/patching static manifest pods though changes are not applied (mostly)

### ISSUE THREAD

**Issue by losipiuk** [kubernetes/kubernetes#63035]
/kind bug

**What happened**:
`kubectl` does not report error when it is used to edit or patch pod which is statically defined via entry in `/etc/kubernetes/manifests`.
Subsequent calls to `kubectl describe` show edits thought they are not in effect.
Up to my understanding using `kubectl edit/patch` is unsupported for statically defined pods and should return an error.

**What you expected to happen**:

I would expect `kubectl` to return error when used for editing/patching statically defined pod.
Also `kubectl get` should not show any changes after failed call to `kubectl edit/patch`.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl edit pod -n kube-system cluster-autoscaler-kubernetes-master
<do some edits e.g. change image>

pod "cluster-autoscaler-kubernetes-master" edited
```

Now
```
kubectl describe pod -n kube-system cluster-autoscaler-kubernetes-master |grep Image:
```
shows image after modification although the change is not in effect.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.1.88+f0b207df2dd297", GitCommit:"f0b207df2dd297b0b54920c46978083dd8a081e9", GitTreeState:"clean", BuildDate:"2018-04-23T14:34:18Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release):
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

sig: @kubernetes/sig-cli-bugs ?

**Comment by losipiuk** [comment]
cc @kubernetes/sig-cli-bugs (not sure if this is right group though).

**Comment by liggitt** [comment]
It is neither an error nor a bug. The API manifestations of static pods behave as any other API object (the apiserver doesn't generally treat them specially). The difference is that the kubelet treats the manifests as the authoritative source, not the API. 

On a subsequent reconciliation loop, the kubelet will likely overwrite the changes made to the pod.

**Comment by gayatri-sa** [comment]
In case someone has the same question and reaches this page
When you execute kubectl edit/path for a static object only the spec of the mirror object changes. The actual static pod is not affected. If you execute _docker ps_ and check the actual container you will notice that nothing has changed.

Of course, the discrepancy is confusing but, at least the integrity of the static pod is maintained.
