### ISSUE TITLE
PodSecurityPolicy: defaults are 

### ISSUE THREAD

**Issue by Quentin-M** [kubernetes/kubernetes#63038]
**Is this a BUG REPORT or FEATURE REQUEST?**:

One may say it's a bug, the other will say it's a feature.

/kind bug

**What happened**:

- A PodSecurityPolicy is defined with the following (excludes root and all existing Container Linux users), and bound to the default service accounts / authenticated users:
```
runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 252
      - min: 254
        max: 499
      - min: 501
        max: 997
      - min: 999
        max: 65535
```
- Try to run a simply nginx image as root in a deployment: the container starts and fails on file permissions. Inspecting the docker container tells us that the container ran with `-u 1`, which is the first value of the first range of allowed users (as documented apparently, never seen it before). Neither the deployment/replicaset/pod indicates about the uid that was used.
- Add a new PodSecurityPolicy that allows `uid=0` and allow the new service account to use it.
- Try to run the nginx deployment again: the container also starts with `-u 1` and fails.
- Explicitly add a `securityContext` with `runAsUser: 0` to the deployment.
- Try to run the nginx deployment again: it works.
 
**What you expected to happen**:

- Because there is no way for anyone besides the cluster administrator to notice anywhere that the container was started an user that is different than the image's default (`uid=1`, rather than the image's default `uid=0`), it may become hard to debug for the users. It is really unintuitive for the container to start with an unexpected user. In my opinion, the pod should go in `Blocked` state rather than trying to start with a bizarre default, that will never basically _never_ work (defaults are supposed to be sensitive).
- Once the deployment got a service account assigned to it, that has the permission to use another `PodSecurityPolicy` that allows `uid=0`, Kubernetes should then stick to the image default (`uid=0`) and run it. The fact that regardless, `uid=1` (Kubernetes' default for one of the PSP that can be used for the pod) was used is abnormal, rather than the actual user that is default of the image and that's allowed.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- API Server is started with: ```PodSecurityPolicy```
- Controller Manager is started with: ```- --use-service-account-credentials=true```

**Comment by liggitt** [comment]
If you want to allow any uid (including unspecified uids in the podspec), use the RunAsAny option in the PSP

See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups for more info on defaulting behavior

/close
