### ISSUE TITLE
rpm building broken in bazel 0.12+

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#63108]
Bazel 0.12 introduced some unintentional backwards-incompatible changes to `pkg_rpm` (https://github.com/bazelbuild/bazel/issues/5049). Additionally, some helper functionality (to resolve files to their new locations) didn't land in 0.12 and are slated for 0.13 instead.

There's no good way to fix this, but options to mitigate include
* tagging all of our `pkg_rpm` rules `manual` - I don't think anything depends on them anyway
* forking `bazelbuild/bazel` and using `pkg_rpm` from that repo (giving us control over what version of the rule we're using)
* waiting for bazel 0.13, then
  * updating the rpm specs to use the substitution helper
  * pinning the master branch to bazel >= 0.13
  * pinning all release branches to bazel <= 0.11

Currently this hasn't affected CI, since we're still running bazel 0.11 everywhere.

cc @BenTheElder @sigma

**Comment by nikhita** [comment]
@ixdy looks like this can be closed now?
