### ISSUE TITLE
Can kubectl diff only check the things provided in the yaml file?

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes/kubernetes#63113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

When applying an yaml file to the cluster, often we only specify a subset of things. And sometimes the API server will add new key-value pairs. As a result, we have more things stored on the cluster. Use ```dummy.yaml``` below as an example:
```
kind: Pod
apiVersion: v1
metadata:
  name: dummy-pod
spec:
  containers:
    - name: dummy-pod
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Always
```

So we can run ```kubectl apply -f dummy.yaml``` to run the pod on the cluster.

Now if I run ```kubectl alpha diff -f dummy.yaml```, I expect that it shows that nothing is changed. But instead it showes:
```
diff -u -N /tmp/LOCAL-294395991/dummy-pod /tmp/LIVE-710688202/dummy-pod
--- /tmp/LOCAL-294395991/dummy-pod	2018-04-24 17:14:46.795282534 -0700
+++ /tmp/LIVE-710688202/dummy-pod	2018-04-24 17:14:46.795282534 -0700
@@ -1,8 +1,15 @@
 apiVersion: v1
 kind: Pod
 metadata:
+  annotations:
+    kubectl.kubernetes.io/last-applied-configuration: |
+      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"dummy-pod","namespace":"default"},"spec":{"containers":[{"command":["/bin/bash","-ec","while :; do echo '.'; sleep 5 ; done"],"image":"ubuntu","name":"dummy-pod"}],"restartPolicy":"Always"}}
+  creationTimestamp: 2018-04-24T18:07:28Z
   name: dummy-pod
   namespace: default
+  resourceVersion: "3498"
+  selfLink: /api/v1/namespaces/default/pods/dummy-pod
+  uid: 5964d3e1-47ea-11e8-af47-42010a800002
 spec:
   containers:
   - command:
@@ -10,5 +17,64 @@
     - -ec
     - while :; do echo '.'; sleep 5 ; done
     image: ubuntu
+    imagePullPolicy: Always
     name: dummy-pod
+    resources: {}
+    terminationMessagePath: /dev/termination-log
+    terminationMessagePolicy: File
+    volumeMounts:
+    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
+      name: default-token-8bn8d
+      readOnly: true
+  dnsPolicy: ClusterFirst
+  nodeName: gce-node-l9j55
   restartPolicy: Always
+  schedulerName: default-scheduler
+  securityContext: {}
+  serviceAccount: default
+  serviceAccountName: default
+  terminationGracePeriodSeconds: 30
+  tolerations:
+  - effect: NoExecute
+    key: node.alpha.kubernetes.io/notReady
+    operator: Exists
+    tolerationSeconds: 300
+  - effect: NoExecute
+    key: node.alpha.kubernetes.io/unreachable
+    operator: Exists
+    tolerationSeconds: 300
+  volumes:
+  - name: default-token-8bn8d
+    secret:
+      defaultMode: 420
+      secretName: default-token-8bn8d
+status:
+  conditions:
+  - lastProbeTime: null
+    lastTransitionTime: 2018-04-24T18:07:28Z
+    status: "True"
+    type: Initialized
+  - lastProbeTime: null
+    lastTransitionTime: 2018-04-24T18:07:38Z
+    status: "True"
+    type: Ready
+  - lastProbeTime: null
+    lastTransitionTime: 2018-04-24T18:07:28Z
+    status: "True"
+    type: PodScheduled
+  containerStatuses:
+  - containerID: docker://dce4cea45c1119693f73198919c0fd0fee1d070b65e18a49d3bc80e84496df3d
+    image: ubuntu:latest
+    imageID: docker-pullable://ubuntu@sha256:9ee3b83bcaa383e5e3b657f042f4034c92cdd50c03f73166c145c9ceaea9ba7c
+    lastState: {}
+    name: dummy-pod
+    ready: true
+    restartCount: 0
+    state:
+      running:
+        startedAt: 2018-04-24T18:07:37Z
+  hostIP: 10.128.0.3
+  phase: Running
+  podIP: 10.44.0.1
+  qosClass: BestEffort
+  startTime: 2018-04-24T18:07:28Z
```
Notice those ```+``` signs. These lines are things added by the cluster. Some of them are not particularly helpful, e.g., the ```status```. Some may be useful, e.g., ```imagePullPolicy``` and ```dnsPolicy```, because it is good to know the default values.

Since there are so many of those, it is hard for me to check if any line in my original ```dummy.yaml``` is changed. It would be nice if we can add some flag to ``kubectl diff`` so that we only compare things provided in the yaml file and ignore things added by the cluster.

**Comment by wangzhen127** [comment]
/kind feature
/sig cli
/area kubectl
@apelisse

**Comment by apelisse** [comment]
Yeah, you can compare to see what changed in your yaml since the last time you applied, that is:
```
kubectl alpha diff LAST LOCAL -f dummy.yaml
```

That means that you want the different between `LAST` (the last thing you applied) and `LOCAL` (what you currently have). Try it and tell me if that works for you!

**Comment by wangzhen127** [comment]
Clearly I didn't really understand what LAST LOCAL mean before... This works! Thanks!

**Comment by apelisse** [comment]
@wangzhen127 Would you mind looking at the help one more time and tell me what could have been improved? Thanks!

**Comment by wangzhen127** [comment]
Probably include definitions of the versions. I didn't understand what those versions mean before, so I ignored those... Then I found https://goo.gl/UVsM6A and realize those versions are pretty important. The 2nd paragraph in that doc that explains different versions are very useful.

**Comment by apelisse** [comment]
Cool thanks, I appreciate the feedback. There is a ton of things to do wrt doc. I'll try to take some time to address that!
