### ISSUE TITLE
Make `StorageClass` of provisioned `PersistentVolume` mutable

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#63112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

`StorageClass` is used to specify the performance characteristic of volumes to provision. Once a volume is provisioned using a specific `StorageClass` there is no way to change it. The volume is forever stuck with the performance characteristics it was provisioned with.

**What you expected to happen**:
Some storage systems allow the performance characteristics of a volume to be changed dynamically on the fly. We should consider supporting such behavior by allowing cluster admins to change the `StorageClass` of already provisioned `PersistentVolume` objects.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
Isn't this problematic if that changes the associated provisioner or parameters and makes the volume undeletable?

**Comment by jayunit100** [comment]
ISnt the whole point of the storage class to support dynamic provisioning, so that the volumes are created smartly on demand?  If so, reusing an old volume seems counterintuitive, it would be easier to just provision a new volume, w new class metadata, and copy the contents between the old -> new one.?

**Comment by saad-ali** [comment]
> If so, reusing an old volume seems counterintuitive,b/c old volumes are already instantly bound on demand and working, .... so modifying the metadata wont really help the scheduler in anyway... also, the myriad uses for storage classes probably would get super hard to accomodate if you start mutating their labels after creation.

That was my initial reaction. But the argument is that there are storage systems that allow tweaking performance characteristics of a volume after it is provisioned. Requiring the creation of a brand new volume for such systems is painful.

> also, the myriad uses for storage classes probably would get super hard to accomodate if you start mutating their labels after creation.

I'm sure there are a number of assumptions in the existing implementation that would break and would need to be addressed if we were ever to do this.

> Isn't this problematic if that changes the associated provisioner or parameters and makes the volume undeletable?

Yep good point.
