### ISSUE TITLE
kube-proxy only work on tcp6 not tcp 

### ISSUE THREAD

**Issue by kinglion811** [kubernetes/kubernetes#63124]
I deploy kubernetes on centos7.3 kernel 3.10,and the kubernetes version is 1.10,when I deploy dashboard or other service,the type is NodePort,but the server is:
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0            :::30002                                 :::*                    LISTEN      34279/kube-proxy
tcp6       0      0              :::30697                               :::*                    LISTEN      34279/kube-proxy
how can I change them to 
tcp        0      0 {ip}:2380       0.0.0.0:*              
or
tcp        0      0  0.0.0.0:2380       0.0.0.0:*  
the kube-proxy --bind-address= config is 0.0.0.0 or {IP} don't work

/sig apply

**Comment by thockin** [comment]
Linux will show the IPV6 line even when it is listening on IPv4.  It's weird but I see the same on my very functional v4 cluster on machines that have v6 enabled.

**Comment by ritu2593** [comment]
I am facing this issue and im using azure RHEL vm
tcp6       1      0 :::32544                :::*                    LISTEN      2956/kube-proxy
I want to access this on browser. Please help.

**Comment by WestFarmer** [comment]
it's not true, when only listen on tcp6, you can't access with ipv4 address.
At least, I can't access kubernetes-dashboard, when the kube-proxy only listen on tcp6.
