### ISSUE TITLE
support file mount on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#63121]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Currently only directory mount is supported on Windows, e.g. azuredisk, azurefile, file mount on Windows should also be supported.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/assign
FYI @PatrickLang

**Comment by andyzhangx** [comment]
related to https://github.com/moby/moby/issues/37120

**Comment by PatrickLang** [comment]
This will need a bugfix (Windows internal # 14681096) which is tracked for next release and should be available in Windows Server Insider builds around 1.12 timeframe

**Comment by andyzhangx** [comment]
@PatrickLang now file volume mapping on windows container is not supported according to https://github.com/moby/moby/issues/37120, so someone is working on that? If so, I will also do corresponding code change on k8s.

**Comment by PatrickLang** [comment]
This fix will require Windows Server 2019, along with an upcoming build of containerd and cri-containerd that uses a new version of the Windows HCS API. Unfortunately there's no way to fix it in the moby/moby codebase without containerd.

**Comment by jingxu97** [comment]
@andyzhangx could you please update what is the status of this issue? Thanks!

**Comment by andyzhangx** [comment]
> @andyzhangx could you please update what is the status of this issue? Thanks!

@jingxu97 no new update now, this feature depends on windows to use containerd. Any new feature/scenario depends on this now?

**Comment by PatrickLang** [comment]
/remove-lifecycle rotten
/reopen

Currently tracked in https://github.com/containerd/containerd/issues/3897 plus an internal MS bug

**Comment by PatrickLang** [comment]
This is done in ContainerD, minus this corner case: https://github.com/containerd/containerd/issues/3897

**Comment by marosset** [comment]
/close
As Patrick mentioned this now works in ContainerD and we have a separate issue tracking the a known corner case (#70189) which requires a Windows OS fix.
We have no plans to support this functionality with docker.
