### ISSUE TITLE
Validate/correct documentation for reserving compute resources and eviction policy

### ISSUE THREAD

**Issue by embano1** [kubernetes/kubernetes#63132]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
As a user I want to reserve resources on my node (kubelet) for critical system components, e.g. kubelet, container runtime, system daemons, etc. This can be achieved with `--kube-reserved` and/or `--system-reserved` flags as described here: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/.

However, the documentation seems to be wrong or misleading when it comes to eviction thresholds. The example given in the documentation (https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#example-scenario) states:

> Here is an example to illustrate Node Allocatable computation:
>
> - Node has 32Gi of memory, 16 CPUs and 100Gi of Storage
> - --kube-reserved is set to cpu=1,memory=2Gi,ephemeral-storage=1Gi
> - --system-reserved is set to cpu=500m,memory=1Gi,ephemeral-storage=1Gi
> - --eviction-hard is set to memory.available<500Mi,nodefs.available<10%
>
> Under this scenario, Allocatable will be 14.5 CPUs, 28.5Gi of memory and 98Gi of local storage. Scheduler ensures that the total memory requests across all pods on this node does not exceed 28.5Gi and storage doesn’t exceed 88Gi. Kubelet evicts pods whenever the overall memory usage across pods exceeds 28.5Gi, or if overall disk usage exceeds 88Gi If all processes on the node consume as much CPU as they can, pods together cannot consume more than 14.5 CPUs.

This makes sense (e.g. start eviction at 28.5GB mem usage). The documentation continues with:

> If kube-reserved and/or system-reserved is ***not enforced*** and system daemons exceed their reservation, kubelet evicts pods whenever the overall node memory usage is higher than 31.5Gi or storage is greater than 90Gi

Either I am not correctly understanding eviction behavior or the `31.5GB` value in the example is wrong. Even without enforcing kube/system-reserved, shouldn't eviction start at `allocatable + eviction-hard`, i.e. 28.5GB? Or does `not enforced` mean kube/system-reserved are not specified? I read `enforced` as setting `--enforce-node-allocatable` to include kube/system-reserved on the kubelet.

The OpenShift documentation seems to support this fact: https://docs.openshift.com/container-platform/3.9/admin_guide/allocating_node_resources.html#eviction-thresholds-1

**What you expected to happen**:
Pod eviction should start at `28.5GB` memory pressure as per the example even without setting `--enforce-node-allocatable` to include kube/system-reserved.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shubheksha** [comment]
/kind support 
@embano1, Kubernetes docs live in this repo: https://github.com/kubernetes/website
Since this seems to be a clarification regarding docs, could you file this bug [there ](https://github.com/kubernetes/website/issues/new)instead?

**Comment by embano1** [comment]
Makes sense, sorry.
