### ISSUE TITLE
Almost all GCE jobs failing on CI!

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#63134]
Since yesterday evening PST, most of our GCE jobs are broken (@krzysied noticed this for our scalability jobs):
See - https://k8s-testgrid.appspot.com/google-gce (almost entire GCE suite)

The problem seems to be that "cluster up" is failing and the apiserver does not even seem to be starting from the [master logs](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/24582/artifacts/bootstrap-e2e-master/).

/priority critical-urgent

cc @kubernetes/sig-testing-bugs @kubernetes/sig-cluster-lifecycle-bugs

**Comment by shyamjvs** [comment]
It seems to be broken across the following diff:

- https://github.com/kubernetes/kubernetes/compare/b2ab90123...5b0df3656 (k8s)
- https://github.com/kubernetes/test-infra/compare/384aa2cda...fbe5016e0 (test-infra)

The test-infra one change seems very unlikely to break. From the k8s ones, I suspect it may be this one - https://github.com/kubernetes/kubernetes/pull/63015 (though I don't have a strong reasoning for it).

**Comment by shyamjvs** [comment]
Thanks to @dims for pointing that the problem is with this line - https://github.com/kubernetes/kubernetes/commit/ae73bed1d0b9a299b06fc762d513b9b734ea4ce7#diff-6e3b476b9225d1213dc6ad13e453fc16R1326
As that's causing the master configuration script to fail with:

```
Apr 25 01:44:45.756252 bootstrap-e2e-master configure-helper.sh[874]: Start etcd pods
Apr 25 01:44:46.555605 bootstrap-e2e-master configure-helper.sh[874]: cp: cannot stat '/home/kubernetes/kube-manifests/kubernetes/gci-trusty/etcd-empty-dir-cleanup.yaml': No such file or directory
Apr 25 01:44:46.556413 bootstrap-e2e-master systemd[1]: kube-master-configuration.service: Main process exited, code=exited, status=1/FAILURE
```

Without looking deeper, I'm going to revert the PR and let @mikedanese fix it.
Also I'm surprised why our gce presubmit didn't catch this? (cc @kubernetes/test-infra-maintainers )

**Comment by mikedanese** [comment]
Thanks!
