### ISSUE TITLE
Cronjobs fail to execute if their name is too long

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#63171]
/kind bug

**What happened**:

Cronjobs were created with no errors. However, they failed to execute, with no clue in the logs. Experimentation discovered that this occurs if their name is too long -- specifically, there's a 52-character limit, since Kubernetes takes the cron name and appends `-` plus 10 auto-generated characters = 63 total = `const DNS1123LabelMaxLength int = 63` ([source code](https://github.com/kubernetes/kubernetes/blob/8d7d7a5e0d4d7e75f5a860574346944b8cc0fc43/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L109)).

**What you expected to happen**:

One or more of:
a) Error upon `kubectl create` with a cronjob that has a name that is too long.
b) Error log upon processing said cronjob and determining that the resulting pod name length is too long.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cronjob with name `cron-billing-report-for-end-of-month-abcdefghijklmnop` (53 chars) that runs every minute -- see that there's no error upon creation, yet it never executes, and the name never appears in the logs.

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  labels:
    name: cron-billing-report-for-end-of-month-abcdefghijklmnop
  name: cron-billing-report-for-end-of-month-abcdefghijklmnop
  namespace: web
```
```
23:03 integ highland@tuk5m1control2:~$ kubectl.sh --namespace=web get cronjobs | awk 'NR==1 || /klmn/'
Command: kubectl --kubeconfig=/highland/config/kube_auth/config --namespace=web get cronjobs
NAME                                                     SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
cron-billing-report-for-end-of-month-abcdefghijklmn      * * * * *     False     0         Wed, 25 Apr 2018 23:03:00 +0000
cron-billing-report-for-end-of-month-abcdefghijklmno     * * * * *     False     0         Wed, 25 Apr 2018 23:03:00 +0000
cron-billing-report-for-end-of-month-abcdefghijklmnop    * * * * *     False     0         <none>
cron-billing-report-for-end-of-month-abcdefghijklmnopq   * * * * *     False     0         <none>
```

Then create a cronjob with name `cron-billing-report-for-end-of-month-abcdefghijklmno` (52 chars) that runs every minute -- this will perform properly.

**Anything else we need to know?**:

As an aside, there's an argument to be made that the max length should be longer than 63 characters -- per https://tools.ietf.org/html/rfc1123#section-2:
```
    2.1  Host Names and Numbers

      ...

      Host software MUST handle host names of up to 63 characters and
      SHOULD handle host names of up to 255 characters.
```
...although, the fundamental bug would still remain, just at a much-harder-to-hit length.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:12:08Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): `16.04.1 LTS (Xenial Xerus)`
- Kernel (e.g. `uname -a`): `4.4.0-116-generic #140-Ubuntu`
- Install tools: N/A
- Others: N/A

**Comment by Joseph-Irving** [comment]
yeah I've had a few developers hit this issue and if you're not very familiar with Kube it can be very confusing to debug. I think it would make sense to error when you attempt to create the cronjob as your job is never going to schedule.

**Comment by Joseph-Irving** [comment]
it looks like this has been fixed actually https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/validation/validation.go#L169. This was 8 months ago. You're using an unsupported version of kube so you'll need to update to get the fix.

**Comment by DreadPirateShawn** [comment]
In fact, I filed a dupe -- see #50850 for original tracking.
