### ISSUE TITLE
apiserver panic when running integration test

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#63188]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Integration failed, the apiserver panic :(

It seems race condition case for `clusterroles` as follow; refer to the attachment for the detail, 

```
2132 I0426 17:17:14.653388   20580 trace.go:76] Trace[1009546348]: "List /apis/rbac.authorization.k8s.io/v1/clusterroles" (started: 2018-     04-26 17:16:14.653009585 +0800 CST m=+153.540700977) (total time: 1m0.000345077s):
2133 Trace[1009546348]: [1m0.000345077s] [1m0.00034003s] END
2134 E0426 17:17:14.653566   20580 runtime.go:66] Observed a panic: &errors.errorString{s:"killing connection/stream because serving requ     est timed out and response had been started"} (killing connection/stream because serving request timed out and response had been sta     rted)
2135 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.g     o:72
2136 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.g     o:65
2137 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.g     o:51
2138 /usr/local/go/src/runtime/asm_amd64.s:573
2139 /usr/local/go/src/runtime/panic.go:502
2140 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go     :221
2141 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go     :105
2142 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.     go:45
2143 /usr/local/go/src/net/http/server.go:1947
2144 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/request     info.go:39
2145 /usr/local/go/src/net/http/server.go:1947
2146 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
2147 /usr/local/go/src/net/http/server.go:1947
2148 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189
2149 /home/k82cn/go_ws/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/util.go:100
2150 /usr/local/go/src/net/http/server.go:1947
2151 /usr/local/go/src/net/http/server.go:2694
2152 /usr/local/go/src/net/http/server.go:1830
2153 /usr/local/go/src/runtime/asm_amd64.s:2361
2154 2018/04/26 17:17:14 http: multiple response.WriteHeader calls      <=========== race condition for http server.
2155 E0426 17:17:14.653839   20580 wrap.go:34] apiserver panic'd on GET /apis/rbac.authorization.k8s.io/v1/clusterroles: killing connecti     on/stream because serving request timed out and response had been started
```

[test.log](https://github.com/kubernetes/kubernetes/files/1950519/test.log)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

`make test-integration WHAT=k8s.io/kubernetes/test/integration/scheduler`

**Environment**:
- Kubernetes version (use `kubectl version`): master branch
- Cloud provider or hardware configuration: none
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux wgl-ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: none
- Others: Can not reproduced every time :(

**Comment by hzxuzhonghu** [comment]
It's a timeout . Because the default timeout for non-long running connection request is 60s.
>2132 I0426 17:17:14.653388   20580 trace.go:76] Trace[1009546348]: "List /apis/rbac.authorization.k8s.io/v1/clusterroles" (started: 2018-     04-26 17:16:14.653009585 +0800 CST m=+153.540700977) (total time: 1m0.000345077s):
2133 Trace[1009546348]: [1m0.000345077s] [1m0.00034003s] END

**Comment by hzxuzhonghu** [comment]
panic called in staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L221

**Comment by liggitt** [comment]
normally that means the test etcd instance did not come up successfully...

**Comment by k82cn** [comment]
> normally that means the test etcd instance did not come up successfully...

I checked those daemons: etcd is there, no apiserver; but I'm not sure whether etcd start up after apiserver crash :(.

**Comment by hzxuzhonghu** [comment]
> I checked those daemons: etcd is there, no apiserver; but I'm not sure whether etcd start up after apiserver crash :(.

Integration test failed the process exited, not crash.
The timeout panic is recovered by apiserver and printed an error message
`2155 E0426 17:17:14.653839   20580 wrap.go:34] apiserver panic'd on GET /apis/rbac.authorization.k8s.io/v1/clusterroles: killing connecti     on/stream because serving request timed out and response had been started
`

**Comment by k82cn** [comment]
Did not trigger this issue again, close this for now.
