### ISSUE TITLE
Taints and Tolerations not respected

### ISSUE THREAD

**Issue by Miouge1** [kubernetes/kubernetes#63197]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Some pods are getting schedules on nodes even though there is a NoSchedule Taint

**What you expected to happen**:

I expect pods to not be scheduled on that node unless they have the matching toleration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.3 LTS (Xenial Xerus)`
- Kernel (e.g. `uname -a`): `Linux kube-master-1 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Kubespray
- Others:
```
$ kubectl describe node kube-master-1
Name:               kube-master-1
Roles:              master
Taints:             node-role.kubernetes.io/master:NoSchedule
System Info:
 Kubelet Version:            v1.9.5
 Kube-Proxy Version:         v1.9.5
```
```
$ kubectl describe pod mypod
Node:           kube-master-1/10.x.y.z
Node-Selectors:  <none>
Tolerations:     <none>
```

/sig scheduling

**Comment by redbaron** [comment]
Do you run with custom scheduler config?

**Comment by redbaron** [comment]
Another possibility is that taint was added AFTER pod was scheduler to a node, so it remains there.

**Comment by Miouge1** [comment]
The taint was added before the Pod was created, no custom scheduler config.

This happens regularly for new Pods created in that cluster.

**Comment by liggitt** [comment]
can you provide the full yaml of the pod and node as retrieved from the API? 

```
kubectl get -o yaml node kube-master-1
kubectl get -o yaml pod mypod
```

is the pod being created directly or via a deployment/replicaset, etc? if directly, can you provide the manifest it is being created from? if from a deployment/replicaset, can you provide the full yaml of the deployment or replicaset?

**Comment by Miouge1** [comment]
Sure.
- [kube-master-1](https://pastebin.com/2dB0Lh7V)
- [example of pod](https://pastebin.com/1giNTLj3)

This is happening on all master nodes.

**Comment by liggitt** [comment]
can you check if kubespray is setting up a custom scheduler policy in the kube-scheduler manifest:

https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubernetes/master/templates/manifests/kube-scheduler.manifest.j2#L31-L34

if it is, it appears the policy it is using is woefully out of date:

https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubernetes/master/templates/kube-scheduler-policy.yaml.j2

specifically, that policy does not include the "PodToleratesNodeTaints" predicate, which means the scheduler wouldn't pay any attention to taints/tolerations at all

**Comment by Miouge1** [comment]
Aha! indeed I have `volume_cross_zone_attachment: true` so it will pass this scheduler flag. DO you know where I can find the latest default scheduler policy?

**Comment by Miouge1** [comment]
Thanks @liggitt I've opened a PR in kubespray to get the default updated. I'll close this issue since this is a kubespray problem.

**Comment by drekle** [comment]
@Miouge1 can you provide a link to your kubespray PR?

**Comment by Miouge1** [comment]
@drekle here are the relavnt Kubespray PRs:
https://github.com/kubernetes/kubernetes/pull/60007
And https://github.com/kubernetes-incubator/kubespray/pull/2946
