### ISSUE TITLE
Health and readiness checks uses https on port 80, even though http is defined as scheme.

### ISSUE THREAD

**Issue by woopstar** [kubernetes/kubernetes#63192]
/kind bug

**What happened**:
Health and readiness checks uses https on port 80.

Describing the deployment gives me:

```
Liveness:   http-get http://:80/healthz delay=10s timeout=5s period=15s #success=1 #failure=3
Readiness:  http-get http://:80/readiness delay=10s timeout=5s period=15s #success=1 #failure=3

....

Warning  Unhealthy              10s (x2 over 25s)  kubelet, odn1-kube-cluster01-worker01  Liveness probe failed: Get https://10.241.0.6/healthz: dial tcp 10.241.0.6:443: getsockopt: connection refused
Warning  Unhealthy              2s (x3 over 32s)   kubelet, odn1-kube-cluster01-worker01  Readiness probe failed: Get https://10.241.0.6/readiness: dial tcp 10.241.0.6:443: getsockopt: connection refused
```

Health check is defined as:

```
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 80
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
```

As seen above, the check fails because it uses `https`. If we simply just change the port to something non 80, like 8080, then it starts using http as protocol.

**What you expected to happen**:

Use the http protocol on port 80 if explicit defined.

**How to reproduce it (as minimally and precisely as possible)**:

Define the liveness probe as above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Tried on both 1.9.5 and 1.10

- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
```
Linux odn1-kube-cluster01-worker01 4.14.11-coreos #1 SMP Fri Jan 5 11:00:14 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz GenuineIntel GNU/Linux
```

**Comment by dims** [comment]
@woopstar can you search for `HTTP-Probe Host` in your kubelet logs? they will look like this. check error messages that come after this line

```
I0426 10:32:44.213085   25783 prober.go:165] HTTP-Probe Host: http://172.17.0.2, Port: 80, Path: /healthz
```

**Comment by woopstar** [comment]
Closing issue. Issue is not kubernetes. Apparently the pod had a nginx running where it redirects http to https.
