### ISSUE TITLE
error: v1alpha1.KubeProxyConfiguration: NodePortAddresses: 

### ISSUE THREAD

**Issue by dober** [kubernetes/kubernetes#63196]
/kind bug

**What happened**:
After editing cm kube-proxy and replacing **nodePortAddresses: null** to **nodePortAddresses: 127.0.0.0/8** got result kube-proxy error

**How to reproduce it (as minimally and precisely as possible)**:
kubectl -n kube-system edit cm kube-proxy,  change null value and recreate pods with label k8s-apps=kube-proxy

**Anything else we need to know?**:
log:
`error: v1alpha1.KubeProxyConfiguration: NodePortAddresses: []string: ReadArrayCB: expect [ or n, but found ", error found in #10 byte of ...|dresses":"127.0.0.0/|..., bigger context ...|:"127.0.0.1:10249","mode":"","nodePortAddresses":"127.0.0.0/8","oomScoreAdj":-999,"portRange":"","re|...`

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- OS GNU/Debian 9

**Comment by liggitt** [comment]
nodePortAddresses is a list, so you need `nodePortAddresses: ["127.0.0.0/8"]`

**Comment by dober** [comment]
@liggitt thank you

it should should be documented as primer

**Comment by zerthimon** [comment]
@liggitt How do I specify more than one cidr block ?
`nodePortAddresses: ["127.0.0.0/8", "10.255.121/24", "192.168.255.1/32" ]` - doesn't work.

**Comment by zerthimon** [comment]
nm, I see the problem, "10.255.121/24" is an incorrect cidr
