### ISSUE TITLE
pod status is Completed but not Succeeded as the document said

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes/kubernetes#63195]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

**What happened**:
```java
# kubectl get pods -n cv --show-all  |  grep single
single-ee7f20b3bcb047f893481e1999decba9-single-0    0/1       Completed   0          33m


# kubectl describe pod single-ee7f20b3bcb047f893481e1999decba9-single-0 -n c
......
 State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 26 Apr 2018 19:44:35 +0800
      Finished:     Thu, 26 Apr 2018 19:49:32 +0800
......
```
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
I wonder the document the docs above say as follow:

Pod is running and has one Container. Container exits with success.
Log completion event.
If restartPolicy is:
Always: Restart Container; Pod phase stays Running.
OnFailure: Pod phase becomes Succeeded.
Never: Pod phase becomes Succeede

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```java
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shubheksha** [comment]
@tingweiwu, since this seems to be related to docs, could you file it in the [docs repo](https://github.com/kubernetes/website/issues/new)?

**Comment by tingweiwu** [comment]
@shubheksha ok, I have filed this in the docs repo  and close this issue,Thanks

**Comment by neolit123** [comment]
> Reason:       Completed

hm, BTW `Completed` is not an official `v1` status. it's matches this condition `Failed || Succeeded`, so i don't think it should be documented unless it has to be made an official one.

but then looking at the above log it has `exit 0` for the single container in the pod, so not sure why the status is not `Succeeded` in the first place.

is that a UX bug?

/cc @kubernetes/sig-cli-bugs
