### ISSUE TITLE
hpa wont work on k8s 1.10.1

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#63210]
/kind bug
/sig autoscaling

**What happened**:
`Warning  FailedComputeMetricsReplicas  17m (x13 over 23m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)`

`Warning  FailedGetResourceMetric       3m (x41 over 23m)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
`
**What you expected to happen**:
working hpa

**How to reproduce it (as minimally and precisely as possible)**:
kubectl describe hpa -n qa pod

**Environment**:
- Kubernetes version - v1.10.1
- Cloud provider or hardware configuration: vmware
- OS CentOS Linux release 7.4.1708 
- Kernel 3.10.0-693.21.1

**Comment by redbaron** [comment]
do you have metrics server  / heapster running?

**Comment by gabrielfsousa** [comment]
yes i have.

**Comment by redbaron** [comment]
does `kubectl top` work?

**Comment by gabrielfsousa** [comment]
yes

Display Resource (CPU/Memory/Storage) usage.

The top command allows you to see the resource consumption for nodes or pods.

This command requires Heapster to be correctly configured and working on the server.

Available Commands:
  node        Display Resource (CPU/Memory/Storage) usage of nodes
  pod         Display Resource (CPU/Memory/Storage) usage of pods

Usage:
  kubectl top [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
[root@APP197 ~]$ kubectl top pod
[root@APP197 ~]$ kubectl top noce
error: unknown command "noce"
See 'kubectl top -h' for help and examples.
[root@APP197 ~]$ kubectl top node
NAME      CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
app197    229m         11%       4618Mi          58%
app198    159m         7%        3426Mi          43%
app199    191m         9%        3188Mi          40%
[root@APP197 ~]$ kubectl top pod --all-namespaces
NAMESPACE     NAME                                         CPU(cores)   MEMORY(bytes)
kube-system   heapster-676cc864c6-t2jks                    1m           38Mi
kube-system   kube-apiserver-app197                        15m          262Mi
kube-system   kube-apiserver-app198                        11m          229Mi
kube-system   kube-apiserver-app199                        14m          232Mi
kube-system   kube-controller-manager-app197               24m          80Mi
kube-system   kube-controller-manager-app198               0m           17Mi
kube-system   kube-controller-manager-app199               0m           15Mi
kube-system   kube-dns-86f4d74b45-nv7nj                    0m           33Mi
kube-system   kube-flannel-ds-7967b                        3m           16Mi
kube-system   kube-flannel-ds-99sl4                        3m           15Mi
kube-system   kube-flannel-ds-9nn5m                        3m           16Mi
kube-system   kube-proxy-8bnsj                             2m           15Mi
kube-system   kube-proxy-bgp49                             1m           14Mi
kube-system   kube-proxy-bz5k4                             1m           15Mi
kube-system   kube-scheduler-app197                        5m           17Mi
kube-system   kube-scheduler-app198                        3m           14Mi
kube-system   kube-scheduler-app199                        3m           13Mi
kube-system   kubernetes-dashboard-7d5dcdb6d9-qwlmd        0m           42Mi
kube-system   monitoring-grafana-69df66f668-xf6sz          0m           11Mi
kube-system   monitoring-influxdb-78d4c6f5b6-j5qrw         1m           155Mi
qa            traefik-ingress-controller-66c6d449b-87654   0m           14Mi
qa            traefik-ingress-controller-66c6d449b-htj7x   0m           16Mi
qa            traefik-ingress-controller-66c6d449b-tpbqz   1m           17Mi
qa            vccrm-7778dcf9c4-65t7k                       4m           900Mi
qa            vccrm-7778dcf9c4-68ltq                       1m           899Mi
qa            vccrm-7778dcf9c4-84tft                       4m           688Mi
qa            vccrm-7778dcf9c4-j4d8n                       2m           490Mi
qa            vccrm-7778dcf9c4-lhzwk                       2m           985Mi
qa            vccrm-7778dcf9c4-n2hlv                       2m           995Mi
qa            vccrm-7778dcf9c4-rxpqf                       2m           949Mi
qa            vccrm-7778dcf9c4-x458f                       10m          375Mi

**Comment by FilipNikolovski** [comment]
Experiencing the same issue on a 1.9.3 cluster. `kubectl top` working, but hpa shows exact same error.

**Comment by gabrielfsousa** [comment]
do we need kubernetes-incubator/metrics-server ?

**Comment by gabrielfsousa** [comment]
after installed kubernetes-incubator/metrics-server hpa is now working.

but now it gave me other problem, since i have a HA with 3 masters, kubectl top only work on one master,

on other 2 i have this error

`[root@APP198 log]$ kubectl top pod --all-namespaces
error: You must be logged in to the server (Unauthorized)
`
