### ISSUE TITLE
Unable to understand terminating namespace on GKE

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#63217]
Hey, 
Very much like [this issue](https://github.com/kubernetes/kubernetes/issues/19317) I have a namespace stuck in terminating on GKE 1.9.6-gke.1, and it's been like that for a good week.

```
❯ k get ns heptio-ark -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"heptio-ark\",\"namespace\":\"\"}}\n"
        },
        "creationTimestamp": "2018-04-11T07:16:41Z",
        "deletionTimestamp": "2018-04-11T07:24:43Z",
        "name": "heptio-ark",
        "resourceVersion": "1170742",
        "selfLink": "/api/v1/namespaces/heptio-ark",
        "uid": "481f3445-3d58-11e8-a994-42010a840077"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
```

There's definitely nothing in that ns:
```
❯ k --namespace=heptio-ark get all
No resources found.
```

I've tried removing the finalizer, like others have suggested in other issues with this problem but to no avail and I don't know what else to try.

**Comment by Stono** [comment]
Looks like this is actually an ark problem, see: https://github.com/heptio/ark/blob/master/docs/debugging-deletes.md

**Comment by Stono** [comment]
Actually i'm going to re-open this, and change the scope from a bug to a feature.
I think we should be able to investigate what is blocking the namespace deletion.

**Comment by liggitt** [comment]
`all` doesn't mean all :-(

you do still have resources in that namespace.

something like https://github.com/kubernetes/kubernetes/pull/63254 would let you discover all resources types in your cluster and list which ones still existed in your namespace:

```
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -o name -n foo
```
