### ISSUE TITLE
Azure MSI is moving to instance metadata

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#63228]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

[Azure MSI](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) is moving to instance metadata (the new endpoint is `http://169.254.169.254/metadata/identity/oauth2/token`). 

Azure cloud provider is reading MSI endpoint from `/var/lib/waagent/ManagedIdentity-Settings` (which is called VM extension endpoint). Its content is always `http://localhost:50342` and won't be updated to metadata endpoint even after VM extension endpoint deprecated. We need to figure out how to patch kubernetes releases for it:

- Master branch: Azure Go SDK need to update first and then update kubernetes vendors
- Old releases (e.g. 1.10, 1.9 and 1.8):  Unfortunately, those releases are using a beta version of Azure Go SDK and it will not release new patches. We need to figure out other ways to fix it

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
@karataliu raised another potential issue: any containers would be able to get Azure identity via metadata. This is because `169.254.169.254` could also be accessed from any containers.

While there are applications already depending on instance metadata, disabling container's access (e.g. by iptables) to `169.254.169.254` is not our preferred way. We need to dig more for possible solutions.

**Comment by khenidak** [comment]
Pod identity takes care of that (regulating access to this endpoint). However you have a point. Other than that it should be bootstrapping tools that block the access via iptables or others. Keep in mind that pods may still use MSI without pod-identity.

CC @jackfrancis

**Comment by khenidak** [comment]
Is this still a valid issue even with this?
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/auth/azure_auth.go#L59

**Comment by feiskyer** [comment]
v1.11.x and master have switched to instance metadata, while older releases won't get patches.

The remaining issue is any containers would be able to get Azure identity via metadata. @khenidak @jackfrancis Any ideas to solve this?

**Comment by khenidak** [comment]
That has always been the case. Pod identity project or network security policies may help. In all cases. Let us close this issue and discuss the other one separately.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by feiskyer** [comment]
OK, let me close the issue then.

/close
