### ISSUE TITLE
Is it dangerous to change /sys/fs/cgroup/pids/kubepods/pids.max

### ISSUE THREAD

**Issue by forbxy** [kubernetes/kubernetes#63237]
we have to deal fork boom,but config pidMax of pod is not stable now.
I try change /sys/fs/cgroup/pids/kubepods/pids.max, it work.
Is there some trouble while change it ?
thanks

**Comment by dims** [comment]
There is a new alpha feature `SupportPodPidsLimit` (https://kubernetes.io/docs/reference/feature-gates/) once you enable that using `--feature-gates`, you will be able to specify  `--pod-max-pids` in kubelet command line

See some information here : https://blog.jetstack.io/blog/hidden-gems-1.10/

thanks,
Dims

/close
