### ISSUE TITLE
kubectl patch - bad error message when JSON Patch is invalid JSON

### ISSUE THREAD

**Issue by marco-jantke** [kubernetes/kubernetes#63247]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Using `kubectl patch` with the JSON Patch type produces a  confusing error message when you miss the leading double quote at the beginning of the path value.

```
kubectl patch --type json --local --filename deployment.yml --patch "$(cat patch.json)" --output yaml 
error: jsonpatch replace operation does not apply: doc is missing key: /spec/template/spec/containers/0/image"
```

**What you expected to happen**:
A proper error message that the provided JSON Patch is not valid JSON.

**How to reproduce it (as minimally and precisely as possible)**:
```
➜  cat deployment.yml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.8
        ports:
        - containerPort: 80

➜ cat patch.json 
[
  {
    "op": "replace",
    "path": /spec/template/spec/containers/0/image",
    "value": "nginx:1.7.9"
  }
]

➜  kubectl patch --type json --local --filename deployment.yml --patch "$(cat patch.json)" --output yaml
error: jsonpatch replace operation does not apply: doc is missing key: /spec/template/spec/containers/0/image"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.0", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-03-21T19:01:20Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brendandburns** [comment]
@marco-jantke it's tricky to know what the right thing to do here is...

The patch you specified parses as:

```json
[{
  "op":"replace",
  "path":"/spec/template/spec/containers/0/image\"",
  "value":"nginx:1.7.9"
}]
```
Note the extra `"` in that path.

We could try to detect "unusual" characters or some-such and print a better message, but I worry that introduces other problems.

From what I see this error message is correct (if hard to understand) perhaps if we put quotes around the bad path it would make it more clear, since at least then the quotes would be visually doubled...

**Comment by brendandburns** [comment]
This error actually comes out of the json patch library:

https://github.com/evanphx/json-patch/blob/master/patch.go#L477

So we need to make a fix there and then re-vendor.

**Comment by marco-jantke** [comment]
Thanks for picking up the issue @brendanburns!

I'm really not into the details but given the patch is "parsed" as JSON, it just shouldn't get parsed as it's invalid JSON and therefore provide an error. IMO producing an error as early as possible, when providing invalid JSON to a JSON patch, is the most reasonable behavior. But I sense things might not be that easy. So making the error messages more clear is a nice improvement!

**Comment by stealthybox** [comment]
> I'm really not into the details but given the patch is "parsed" as JSON, it just shouldn't get parsed as it's invalid JSON and therefore provide an error. IMO producing an error as early as possible, when providing invalid JSON to a JSON patch, is the most reasonable behavior.

None of the documentation or flag names would suggest this, but the patch "JSON" is actually parsed as YAML:

This would be an equivalent "`patch.json`":
```yaml
- op: replace
  path: /spec/template/spec/containers/0/image
  value: nginx:1.7.9
```

JSON works, because it's a valid YAML subset.
If you have invalid JSON, though, it may still be valid YAML such as with your case of the single trailing dquote.

We should probably update the flags and docs to make this more clear that we are parsing YAML into structs that are compatible with `evanphx/json-patch`.

**Comment by liggitt** [comment]
> We should probably update the flags and docs to make this more clear that we are parsing YAML into structs that are compatible with evanphx/json-patch.

That certainly isn't the intent… the content type for the patch document indicates it is a form of json… I'd expect it to be parsed as JSON, not YAML

**Comment by liggitt** [comment]
> By content type, are you referring to the --type flag?

No, the actual content-type header sent to the server. If you add -v=9, what body content is sent to the server when you provide a yaml patch?

**Comment by stealthybox** [comment]
```bash
kubectl patch deploy api-assets --type json -p '
- op: replace
  path: /spec/template/spec/containers/0/lifecycle/preStop/exec/command
  value: [sleep, "10"]
' -v9 |& grep Content-Type
I0909 22:52:25.574577   94070 round_trippers.go:414]     Content-Type: application/json
I0909 22:52:25.577746   94070 round_trippers.go:386] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: application/json-patch+json" -H "User-Agent: kubectl/v1.11.1 (darwin/amd64) kubernetes/b1b2997" 'https://<redacted>/apis/extensions/v1beta1/namespaces/default/deployments/api-assets'
I0909 22:52:25.643455   94070 round_trippers.go:414]     Content-Type: application/json
```
_________________
eh... `application/json-patch+json` ?

yeah, that doesn't look right.

**Comment by liggitt** [comment]
`application/json-patch+json`

That is right. Does the yaml get converted to json form client-side before being sent to the server?

**Comment by stealthybox** [comment]
yes:
```
kubectl patch deploy api-assets --type json -p '
- op: replace
  path: /spec/template/spec/containers/0/lifecycle/preStop/exec/command
  value: [sleep, "10"]
' -v9 |& grep 'Request Body'
I0909 23:02:42.677410   94754 request.go:897] Request Body: [{"op":"replace","path":"/spec/template/spec/containers/0/lifecycle/preStop/exec/command","value":["sleep","10"]}]
```
