### ISSUE TITLE
Test performance against etcd versions

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#63245]
Off-shoot of what I was suggesting in https://github.com/kubernetes/kubernetes/issues/62064#issuecomment-384355538.
Let's keep this as an umbrella for results of performance testing (specifically density test) against changing etcd versions.
Hopefully this will finally help us understand what's really happening with those.

Based on [history](https://github.com/kubernetes/kubernetes/commits/master/build/build-image/cross/Dockerfile) of our build dockerfile, I think it makes most sense to test the following (let me know if you suggest sth else):

- 3.2.18
- 3.1.12
- 3.1.11 ?
- ...?

cc @kubernetes/sig-scalability-misc @wojtek-t @jpbetz @gyuho @xiang90

**Comment by shyamjvs** [comment]
I'll start by running density test against these versions on head. Also since 'performance' in general can mean many things, I think the focus here should be on 'api call latencies' which is where we're mostly observing regressions. Let me know if you think there is some other characteristic that's needed to be measured.

**Comment by shyamjvs** [comment]
@krzysied Could you please paste the results of your runs with different etcd versions here? I think the 'Top latency metrics' and 'etcd CPU/mem usage' would be useful metrics to have a record of.

**Comment by krzysied** [comment]
Here's the top latency for 3.2.18:
Run 1:
``
{Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:2.582612s Perc90:5.692709s Perc99:6.321931s Perc100:0s} Count:8328}
{Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:555.988ms Perc90:2.109917s Perc99:4.495199s Perc100:0s} Count:2387}
{Resource:pods Subresource: Verb:LIST Scope:namespace Latency:{Perc50:51.435ms Perc90:201.004ms Perc99:2.185633s Perc100:0s} Count:10600}
{Resource:replicationcontrollers Subresource: Verb:POST Scope:namespace Latency:{Perc50:4.884ms Perc90:774.59ms Perc99:1.581569s Perc100:0s} Count:5050}
{Resource:replicationcontrollers Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:4.145ms Perc90:809.59ms Perc99:1.578297s Perc100:0s} Count:5050}
``

Run2:
``
{Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:2.294345s Perc90:5.272882s Perc99:5.801913s Perc100:0s} Count:8732}
{Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:582.433ms Perc90:1.981002s Perc99:4.400313s Perc100:0s} Count:2300}
{Resource:pods Subresource: Verb:LIST Scope:namespace Latency:{Perc50:48.371ms Perc90:177.822ms Perc99:2.056579s Perc100:0s} Count:10583}
{Resource:replicationcontrollers Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:3.001ms Perc90:683.71ms Perc99:1.704709s Perc100:0s} Count:5050}
{Resource:replicationcontrollers Subresource: Verb:POST Scope:namespace Latency:{Perc50:4.064ms Perc90:703.64ms Perc99:1.154235s Perc100:0s} Count:5050}
``

Run3:
``
{Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:410.369ms Perc90:2.197624s Perc99:4.608374s Perc100:0s} Count:2270}
{Resource:pods Subresource: Verb:LIST Scope:namespace Latency:{Perc50:55.156ms Perc90:86.017ms Perc99:1.705538s Perc100:0s} Count:10576}
{Resource:pods Subresource: Verb:POST Scope:namespace Latency:{Perc50:1.85ms Perc90:9.825ms Perc99:393.166ms Perc100:0s} Count:155029}
{Resource:pods Subresource: Verb:LIST Scope:cluster Latency:{Perc50:122.766ms Perc90:197.985ms Perc99:355.225ms Perc100:0s} Count:961}
{Resource:pods Subresource:binding Verb:POST Scope:namespace Latency:{Perc50:1.549ms Perc90:4.41ms Perc99:120.597ms Perc100:0s} Count:155000}
``

Those runs were made one after another. As you can see the result of 3rd run differs from 1st and 2nd.

**Comment by wojtek-t** [comment]
@krzysied - do you still have apiserver logs from there runs?

In the last run there is no  "List all pods" calls at all. In the first two there are O(8k+) of them.
That makes me wonder what was calling those "List all pods" in the first two cases (or what wasn't in the last run) and why.

If you could grep the logs of the first or second run for the "List all pods" calls and see what was sending those, why (I guess there were some broken watches) we may be able to debug that.
I think this is exactly the problem that we see at head with every second run having very high RC-related latencies.

**Comment by krzysied** [comment]
Unfortunately, I have only build logs.

**Comment by wojtek-t** [comment]
I think the results above seem to be inlined with what I described in https://github.com/kubernetes/kubernetes/issues/63030#issuecomment-392690351

I also don't think that we now suspect etcd in any of our current problems.
So I think that we may actually close this issue now. @shyamjvs - thoughts?

**Comment by shyamjvs** [comment]
Yeah.. that sgtm. We can reopen it later if we find evidence otherwise.
/close
