### ISSUE TITLE
etcd memory usage is not stable

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#63243]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

**What happened**:
1) Deployed a 1000 nodes Kubernetes 1.9.1 cluster with 3 masters and 3 etcd server with version 3.2.14.
2) Submit 20000 liberty pods with 10 times, each time submit 1000 pods in 1 deployment.
3) My pods was submitted and running at 15:00.
4) From 15:00, the etcd memory usage is not stable, it keeps going up and down from 15:00 to 17:00

![image](https://user-images.githubusercontent.com/4461983/39355998-70dccc66-4a41-11e8-918d-61213ec55da5.png)

Based on my understanding, once all of the workloads are submitted, the etcd memory usage should become stable. Any reason the etcd memory keeps going up and down?

Another 1000 nodes cluster etcd also have same issue after running for 8 hours, there are two etcd memory not stable.

![image](https://user-images.githubusercontent.com/4461983/39356195-f4a98584-4a41-11e8-9d83-302db82227ee.png)

/sig scalability

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
> once all of the workloads are submitted, the etcd memory usage should become stable. Any reason the etcd memory keeps going up and down?

There is a constant write load from nodes heart beating, and as pod status changes

Etcd retains events in-memory for a time window (default of five minutes, I think), then compacts those events. If the interval of those peaks is ~5 minutes (graphs weren't labeled), then the fact that there are peaks is expected. 

I'm not sure if the peaks are expected to be that high or not.

**Comment by liggitt** [comment]
Cc @gyuho

**Comment by gyuho** [comment]
c.f. https://github.com/coreos/etcd/issues/9647

**Comment by gyliu513** [comment]
@gyuho This is my etcd configuration. I was configuring `--snapshot-count=10000`.

```
root@master2:/etc/cfc/pods# cat etcd.json
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "k8s-etcd",
        "namespace": "kube-system",
        "annotations": {
            "scheduler.alpha.kubernetes.io/critical-pod": ""
        }
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "etcd",
                    "--name=etcd0",
                    "--data-dir=/var/lib/etcd",
                    "--initial-advertise-peer-urls=https://10.29.104.2:2380",
                    "--listen-peer-urls=https://0.0.0.0:2380",
                    "--listen-client-urls=https://0.0.0.0:4001",
                    "--advertise-client-urls=https://10.29.104.2:4001",
                    "--cert-file=/etc/cfc/conf/etcd/server.pem",
                    "--key-file=/etc/cfc/conf/etcd/server-key.pem",
                    "--client-cert-auth",
                    "--peer-auto-tls",
                    "--trusted-ca-file=/etc/cfc/conf/etcd/ca.pem",
                    "--initial-cluster-token=etcd-cluster-1",
                    "--initial-cluster=etcd0=https://10.29.104.2:2380,etcd1=https://10.29.104.3:2380,etcd2=https://10.29.104.4:2380",
                    "--grpc-keepalive-timeout=0",
                    "--grpc-keepalive-interval=0",
                    "--snapshot-count=10000",
                    "--initial-cluster-state=new"
                ],
                "image": "10.29.104.1/ibmcom/etcd:v3.2.14",
                "imagePullPolicy": "IfNotPresent",
                "name": "etcd",
                "volumeMounts": [
                    {
                        "mountPath": "/var/lib/etcd",
                        "name": "data"
                    },
                    {
                        "mountPath": "/etc/cfc/conf/etcd",
                        "name": "etcd-certs"
                    }
                ]
            }
        ],
        "hostNetwork": true,
        "volumes": [
            {
                "hostPath": {
                    "path": "/var/lib/etcd"
                },
                "name": "data"
            },
            {
                "hostPath": {
                    "path": "/etc/cfc/conf/etcd"
                },
                "name": "etcd-certs"
            }
        ]
    }
}
```

**Comment by gyliu513** [comment]
> Etcd retains events in-memory for a time window (default of five minutes, I think), then compacts those events. If the interval of those peaks is ~5 minutes (graphs weren't labeled), then the fact that there are peaks is expected.

@liggitt Currently, the default value of `event-ttl` is `1hr`, so think that kubernetes will clear event per hour, and the memory usage should not change so frequently in one hour.

![image](https://user-images.githubusercontent.com/4461983/39393977-50d962fe-4afe-11e8-9001-9c147b86c250.png)
