### ISSUE TITLE
IPVS proxy does not SNAT service IPs

### ISSUE THREAD

**Issue by rtreffer** [kubernetes/kubernetes#63241]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When using IPVS and not natting (no cluster-cidr specified) requests from the host to service IPs are send with the service ip as the source ip.

Let `10.120.0.1` be the kubernetes API IP. Kubeproxy will set up `kube-ipvs0` with `10.120.0.1/32`. This means that traffic from the host (which sees the `kube-ipvs0`) will originate from `10.120.0.1` (best matching ip/network).

**What you expected to happen**:

The source ip should be natted to the host ip.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use a ipvs based cluster
1. Remove any cluster-cidr from kube-proxy
1. Send traffic to a service ip (e.g. http to the kubernetes api server) from the node / host network pod
1. tcpdump the outgoing interface looking for the service ip (`tcpdump .... host 10.120.0.1`)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- Kernel (e.g. `uname -a`): `4.15.3+soundcloud2` (based on the Ubuntu 18.04 kernel)
- Install tools: custom repackaging of kubernetes release tarballs
- Others:

/sig network

**Comment by murali-reddy** [comment]
We have a similar issue in kube-router https://github.com/cloudnativelabs/kube-router/issues/376

FWIW resolution is included in the issue

**Comment by rtreffer** [comment]
Ah nice, I reproduced the source IP selection on my local Ubuntu 18.04
without any kubernetes installed (use ip link add / ip addr add and then
ping the new dummy IP / tcpdump lo). Might be related to the kernel version
(4.15) as you couldn't reproduce it....

Changing the routing table would avoid an extra NAT rule. That sounds
interesting but not doable without changing the kubernetes sources

Murali Reddy <notifications@github.com> schrieb am Fr., 27. Apr. 2018,
14:06:

**Comment by murali-reddy** [comment]
@rtreffer let me try with `Ubuntu 18.04` to reproduce. but its no brainer, this issue must be fixed.

**Comment by rtreffer** [comment]
getting closer...

1. KUBE-CLUSTER-IP is only populated _if_ masquerade-all or cluster-cidr is used: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L858
2. There is no OUTPUT masquerading for service IPs if cluster-cidr is not specified (no branch matches): https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1184

With cluster-cidr enabled I've saved the ipset....
```
# ipset save KUBE-CLUSTER-IP > kube-cluster-ip
```

I've disabled cluster-cidr and rebooted (to reset all iptables/ipset/...).

```
# curl -k https://10.120.0.1
curl: (7) Failed to connect to 10.120.0.1 port 443: Connection timed out
# cat > test << _EOF_
ipset destroy KUBE-CLUSTER-IP
cat kube-cluster-ip| ipset restore
iptables -t nat -I KUBE-SERVICES -m set --match-set KUBE-CLUSTER-IP src,dst -j KUBE-MARK-MASQ
curl -k https://10.120.0.1
_EOF_
# chmod +x test
# ./test 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\": No policy matched.",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

I think the code should:
- Always populate `KUBE-CLUSTER-IP`
- Set a masquerade rule for service IPs (src == service IP should not happen on OUTPUT)

**Comment by rtreffer** [comment]
How to test this with a local cluster....

1. Prepare the node (install `ipvsadm`, `ipset` & modprobe the modules `ip_vs`, `ip_vs_rr`, `ip_vs_wrr`, `ip_vs_sh`).
1. `export KUBE_PROXY_MODE=ipvs ; ./hack/local-up-cluster.sh`
1. In a new shell: define a service with manual external endpoints
```
cat > ext-svc.yaml << _EOF_
kind: "Service"
apiVersion: "v1"
metadata:
  name: "google-dns"
spec:
  ports:
    - name: "https"
      protocol: "TCP"
      port: 443
      targetPort: 443
      nodePort: 0
  selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "google-dns"
subsets:
    -
      addresses:
      - ip: "8.8.8.8"
      - ip: "8.8.4.4"
      ports:
        -
          port: 443 
          name: "https"
_EOF_

./cluster/kubectl.sh apply -f ext-svc.yaml
service "google-dns" created
endpoints "google-dns" created

./cluster/kubectl.sh get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE       SELECTOR
google-dns   ClusterIP   10.0.0.220   <none>        443/TCP   14s       <none>
```
4. Run tcpdump on the outgoing interface of the node
```
tcpdump -n -v -i eth0 host 10.0.0.220
```
5. Curl the service ip
```
curl https://10.0.0.220
curl: (7) Failed to connect to 10.0.0.220 port 443: Connection timed out
```
6. Check the tcpdump, it will show outgoing traffic _from_ the service IP:
```
    10.0.0.220.54200 > 8.8.4.4.443: Flags [S], cksum 0x1716 (incorrect -> 0x54e8), seq 1043528396, win 43690, options [mss 65495,sackOK,TS val 1924445752 ecr 0,nop,wscale 9], length 0
```

**Comment by m1093782566** [comment]
I assume this issue is related to some specific kernel versions? I just neither can't reproduce it nor can't see the failures in our test grid.

**Comment by m1093782566** [comment]
I was aware of there is a PR(#63319) in flight, my team will evaluate the effects of that PR. But, @rtreffer please rebase the PR first, thanks!
