### ISSUE TITLE
kubectl apply init container out of order. 

### ISSUE THREAD

**Issue by manhof** [kubernetes/kubernetes#63257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: running kubectl apply to update and add an additional init container to deployment (running second), however sometimes init containers will run out of order

**What you expected to happen**: when running kubectl apply the init containers should run in the correct order

**How to reproduce it (as minimally and precisely as possible)**: create a deployment with an init container, then run kubectl apply to update with an additional init container ( which should run second).

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.9.4
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
do you have your first and second deployment manifest as an example?

**Comment by dims** [comment]
/close

please reopen with additional info requested
