### ISSUE TITLE
scheduler: Update tests to use subtest

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#63267]
Go 1.7 added the [subtest feature](https://golang.org/doc/go1.7#testing) which can make table-driven tests much easier to run and debug. Many table-driven tests in `pkg/scheduler` and `test/integration/scheduler` are not using this feature.

As an example, https://github.com/kubernetes/kubernetes/pull/56940 converts some tests to use a sub-benchmark.

Further reading: [Using Subtests and Sub-benchmarks](https://blog.golang.org/subtests)

/kind cleanup
/sig scheduling

**Comment by k82cn** [comment]
@misterikkit , @xchapter7x  I approve the open issues, so we can get them merged when it LGTM for misterikkit@ :)

**Comment by eloyekunle** [comment]
@misterikkit Mind if I take a crack at this one?

**Comment by lledru** [comment]
Hi team, It seems some work remains here, is there some refacto works still to do ? I'd glad to help close this.

**Comment by idealhack** [comment]
@lledru Hi, feel free to take a look at the remaining tasks and work on :)

/lifecycle frozen

**Comment by eloyekunle** [comment]
I'll like to take a stab at some packages here.

**Comment by kerthcet** [comment]
Just wondering whether refactor work remaining here? 🧐

**Comment by kerthcet** [comment]
Just wondering whether refactor work remaining here? 🧐

**Comment by ycjiang50** [comment]
I scanned through all the tests in pkg/scheduler and test/integration/scheduler and seems like they've all been updated to use subtest and sub-benchmark. This issue can probably be closed.

**Comment by kerthcet** [comment]
Thanks @ycjiang50 for the feedback, I'd like to close this issue since most tests are migrated.
/close
