### ISSUE TITLE
The scheduler cache generation number could cause use of stale information if a node is deleted and added back with the same name.

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#63262]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The scheduler cache has a generation number for node info that is incremented every time a change is made to the node, for example, when node's resources change, pods assigned to the node, etc. This generation number starts from zero for a node when the node is added to the scheduler cache. The scheduler uses this generation number to update its snapshot of the cache. When generation numbers of the snapshot and the cached nodes are the same, scheduler knows that its snapshot is up to date. The problem is that if a node is deleted and then added back with the same name, there is a potential collision of the generation number that existed in the scheduler's snapshot and that of the newly added node. If such collision happens, the scheduler believes that its snapshot is up to date and keeps using it until the generation number changes. This can cause scheduler to use stale data from its stale snapshot. Although the probability of such collision is low, it occurred consistently in one of our tests and took me a very long time to find what the root-cause was.

/sig scheduling
/assign

**Comment by ravisantoshgudimetla** [comment]
> Although the probability of such collision is low, it occurred consistently in one of our tests and took me a very long time to find what the root-cause was.

Is this the same bug that you mentioned in sig-scheduling call sometime ago and we assumed it could be an issue with API server providing stale information? In any case, this is awesome debugging :)
