### ISSUE TITLE
Hidden performance problem inside volumeManager

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#63274]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Currently `Kubelet` synchronizes each pod periodically, inside each loop `VolumeManager` reprocesses each pod's volumes. If a volume refers to a PVC, it will fetch the latest PV/PVC object from apiserver, see [here](https://github.com/kubernetes/kubernetes/blob/6b64c07bafd13f7a2f4396526f60a189d407e363/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L439) and [here](https://github.com/kubernetes/kubernetes/blob/2f13ffb056488dd34c92a0e0e1c57bef0a45f27d/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L485). So it will increase the load on apiserver/etcd if cluster scale becomes large.

 A possible solution is introducing a PV/PVC cache with TTL, like what ConfigMap and Secret do.

**Comment by mlmhl** [comment]
cc @gnufied  @saad-ali

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests 

We need to carefully consider how this will impact the storage protection feature because the design requires kubelet live lookup for correctness. cc @pospispa @tsmetana
