### ISSUE TITLE
fix kubectl get can't print namespace correctly

### ISSUE THREAD

**Issue by hanxiaoshuai** [kubernetes/kubernetes#63277]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
fix kubectl get can't print namespace correctly
kubectl get po --all-namespaces
```
NAMESPACE   NAME                        READY     STATUS    RESTARTS   AGE
            kube-dns-659bc9899c-jr2nk   2/3       Running   0          42s
```
**What you expected to happen**:
```
kubectl get po --all-namespaces
NAMESPACE     NAME                        READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-659bc9899c-lxs9b   2/3       Running   0          10s
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hanxiaoshuai** [comment]
cc @juanvallejo

**Comment by CaoShuFeng** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/62059
