### ISSUE TITLE
IPVS: rr: TCP 10.254.159.251:9004 - no destination available

### ISSUE THREAD

**Issue by Jacky2** [kubernetes/kubernetes#63279]
**What happened**:
Why I use kube-router in kubernetes,

After running 20 web, kubernetes found that kubernetes node could not connect.

Open the host to find the following error information.
![20180428163023](https://user-images.githubusercontent.com/23411395/39395182-0f3819ac-4b0e-11e8-9ad8-512480c26d0d.png)

/sig network

- Kubernetes version (use `kubectl version`):
  v1.9.7

**Comment by Jacky2** [comment]
@m1093782566   Yes

**Comment by m1093782566** [comment]
So, if you have some troubles in using kube-router, you can create an issue in https://github.com/cloudnativelabs/kube-router and ping the project owner.

I am going to close this issue since your problems have nothing to do with kube-proxy.

**Comment by m1093782566** [comment]
/close

Please feel free do create a new issue if you have problems on kube-proxy.
