### ISSUE TITLE
Fetching CRDs by FQDN should be better documented

### ISSUE THREAD

**Issue by danderson** [kubernetes/kubernetes#63286]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig cli

**What happened**:

I have two custom resources in my cluster called Cluster, and couldn't figure out how to ask for one or the other. `kubectl help get` was of no help, and various Google searches for things like "kubectl apigroup" or "kubectl crd" revealed nothing of use. Worse, some bugs that came up like https://github.com/kubernetes/kubernetes/issues/13929 suggested that the syntax was `apigroup.version.name`, which produced entirely incorrect output (e.g. `kubectl get crd.projectcalico.org.v1.ippool` results in `error: the server doesn't have a resource type "crd"`.

Eventually, I stumbled by accident on the correct way to do it, which is to do `kubectl get crd` and then `kubectl get <fqdn>`, where `fqdn` is the name of the custom resource exactly as listed in the output of `kubectl get crd`.

I still don't know how to request a specific API version using this syntax, if that is even possible.

**What you expected to happen**:

I expected `kubectl help get` to document how to query custom resources, given that they're increasingly central to running production quality clusters with various operators. Failing that, I expected the k8s website to have documentation on querying custom resources that is discoverable via Google search.

**How to reproduce it (as minimally and precisely as possible)**:

Install something that uses custom resources (e.g. Calico in k8s datastore mode, Rook), and try to `kubectl get` one of the custom resources by precise name (e.g. assume that there are multiple `ippools` objects defined by different CRDs, so you can't just `kubectl get ippools`, you have to be more precise).

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2 client+cserver

**Comment by liggitt** [comment]
Opened #63299 with examples
