### ISSUE TITLE
InfluxDB - Error Add-on

### ISSUE THREAD

**Issue by ErickWendel** [kubernetes/kubernetes#63288]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**: Error on front end

**What you expected to happen**: show dashboard

**How to reproduce it (as minimally and precisely as possible)**:

img: https://imgur.com/a/UdBtb8J

**Environment**:
- Client Version: v1.10.1
Server Version: v1.8.11

@k8s-sig-onprem-bugs 
sig/influxdb

**Comment by dims** [comment]
Please use stackoverflow or slack (kubernetes-users) for support questions
/close
