### ISSUE TITLE
Add API to get pod DNS

### ISSUE THREAD

**Issue by antonlisovenko** [kubernetes/kubernetes#63296]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> feature

Currently there is no API to find the DNS name of existing pod. The example scenario when this can be needed is when some statefulset is created programmatically using API and then the pod hostnames are used for some requests inside the cluster. Currently seems there is no other way to get hostnames except for building them manually through string  concatenation which seems quite error-prone (though works in practice). Ideally as Kubernetes has the knowledge about DNS entries, services  and the way they are built and supported - it could have API for returning the full internal DNS name for the specified pod. May be it should be the endpoint for `Service` object.

**Comment by thockin** [comment]
Pods either don't have hostnames, or their hostname was set explicitly and is therefor available through `hostname -f`
