### ISSUE TITLE
TestVolumeBindingStress flakes

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#63302]
Seeing flakes in the TestVolumeBindingStress test:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58474/pull-kubernetes-integration/9177/

The recent changes to this test in https://github.com/kubernetes/kubernetes/pull/62929 assume events are a reliable message bus, which they are not.

**Comment by msau42** [comment]
Considering that events are unreliable, then I think the best course of action is to revert #62929

**Comment by liggitt** [comment]
Agreed. Opened #63307
