### ISSUE TITLE
Cant access load balance/kubernetes dashboard 

### ISSUE THREAD

**Issue by ser-shant** [kubernetes/kubernetes#63301]
/kind bug
/sig network

**What happened**:
I have deployed two LoadBalancers on kubernetes and cant access it from external network.
service/nginx-ingress           LoadBalancer   10.101.106.224   <pending>     80:31028/TCP,443:31016/TCP   12m
service/node-hello              LoadBalancer   10.98.249.19     <pending>     8080:30004/TCP               3s
Both have external-ip <pending>
I am trying to access it using serverip:30004 from the browser, but getting This site can’t be reached: ERR_CONNECTION_REFUSED 

--2018-04-30 17:04:35--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... failed: Connection refused.

And also when I am trying to run "kubectl proxy" it stuck like this:
kubectl proxy
Starting to serve on 127.0.0.1:8001

Is it a problem with server not allow to expose the port or configuration missing? 

**What you expected to happen**:
Get response from the service, access kubernetes dashboard using server host name/ip address

**How to reproduce it (as minimally and precisely as possible)**:
as described in "What happened"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"

- Kernel (e.g. `uname -a`):
4.15.0-19-generic
- Install tools:
- Others:

**Comment by thockin** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/
