### ISSUE TITLE
Dynamic provisioning e2e tests failing

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#63306]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
/assign @humblec 

**What happened**:
After https://github.com/kubernetes/kubernetes/pull/59879 merged, dynamic provisioning tests started to panic.

Testgrid: http://k8s-testgrid.appspot.com/sig-storage#gce-slow
Logs: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/16656

**Comment by humblec** [comment]
need to check where exactly its happening, however my initial analysis is that this PR https://github.com/kubernetes/kubernetes/pull/63338 is going to fix it. @msau42 @jeffvance can you please review this PR ?

**Comment by jeffvance** [comment]
panic occur in L102. Class is nil but is referenced. 
This pr should fix the panic.

**Comment by copejon** [comment]
The panic occurs because [testDynamicProvisioning()](https://github.com/kubernetes/kubernetes/blob/f4b2452654967a44dd0821a48d8833aa839916c0/test/e2e/storage/volume_provisioning.go#L67) is passed a nil pointer on [Line 725](https://github.com/kubernetes/kubernetes/blob/f4b2452654967a44dd0821a48d8833aa839916c0/test/e2e/storage/volume_provisioning.go#L725).  `testDynamicProvisioning` does not catch `nil` class pointers, so when it accesses `class.Provisioner`  on line L102, it panics.

**Comment by msau42** [comment]
What I don't understanding is that if it's nil, it creates the class [here](https://github.com/kubernetes/kubernetes/blob/f4b2452654967a44dd0821a48d8833aa839916c0/test/e2e/storage/volume_provisioning.go#L71)

**Comment by copejon** [comment]
It's actually the opposite:
```
	if class != nil {
		By("creating a StorageClass " + class.Name)
		class, err = client.StorageV1().StorageClasses().Create(class)
```
It only creates it if the pointer isn't nil. Otherwise, it makes to line 102 unchecked.

**Comment by humblec** [comment]
May be a general improvement is required in these functions to catch nil class as start of the function. I will work on a general fix later .

**Comment by AishSundar** [comment]
I see these tests are failing multiple jobs in sig-release master-blocking suite as well. Opened an issue to track those failures - 

https://github.com/kubernetes/kubernetes/issues/63497

Feel free to triage as you see fit.

**Comment by humblec** [comment]
@AishSundar the fix PR is merged. Idealy the tests should not fail hereonwards.. Atleast from some time now. Can you please verify it from your end ?

**Comment by AishSundar** [comment]
Waiting for new run to verify

**Comment by msau42** [comment]
tests are passing now
/close
