### ISSUE TITLE
apiserver -> etcd healthcheck does not complete TLS handshake, etcd logs warning

### ISSUE THREAD

**Issue by jhoch-palantir** [kubernetes/kubernetes#63316]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When configuring kubernetes apiserver to communicate with an SSL-enabled etcd cluster, the etcd health check does not provide TLS headers, so the connection succeeds, but the TLS handshake succeeds.  Nothing looks wrong from kubernetes's perspective, and nothing is logged.  However, the etcd cluster logs the handshake failure.

**What you expected to happen**:
I would expect, in the case that kubernetes apiserver is configured to communicate with etcd using TLS, for the health check to do the same, without error.

**How to reproduce it (as minimally and precisely as possible)**:
Run apiserver 1.9.6, configured to communicate with etcd 3.3+ over SSL.

[This code](https://github.com/kubernetes/apiserver/blob/kubernetes-1.10.2/pkg/storage/etcd3/preflight/checks.go#L44) looks like the problem.

**Anything else we need to know?**:
We could disable this logging in etcd, but we would prefer not to.

**Environment**:
- Kubernetes version: 1.9.6
- etcd version: 3.3+
- Enviroment: Bare metal
- OS: CoreOS
- Kernel: 4.16.3

**Comment by jhoch-palantir** [comment]
@kubernetes/sig-api-machinery-bugs

(please excuse me if this is the wrong sig, I'm still becoming familiar with the project)

**Comment by wenjiaswe** [comment]
@jhoch-palantir So sorry for the late reply. I think this PR #65027 might have fixed the issue. It's in release-1.12. Please let me know. If it's still an issue I will get back and work on it. Thanks!
