### ISSUE TITLE
PV for regional PD should not allow attaching of regular PDs

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#63317]
/kind bug

If a PV's zone annotation format indicates that it's a regional PD, but pdName corresponds to a regular PD, currently the GCE PD plugin allows attach to succeed. It should fail, because the mismatch is often caused by user error.

/sig gcp
/sig storage
/assign

**Comment by msau42** [comment]
Can we have an admission controller that checks for this user error?

**Comment by liggitt** [comment]
> Can we have an admission controller that checks for this user error?

how would an out of tree volume plugin enforce this restriction? Shouldn't we try to model surfacing the error using the flows available to CSI plugins, since the in-tree plugins are planned to migrate to that?

**Comment by verult** [comment]
Today the PVLabel admission controller already overwrites the user-specified label with the correct label, but it's important to have a secondary check in the plugin.

Consider this scenario: both a regional and a regular disk exist with name `disk-1`, and the user's PV has the zone label matching the regional disk. The admission controller then retains the user specified label since it's valid. Next, the user deletes the regional disk, and the PV is left unchanged. When a pod is created with this PV, the regular disk will be attached, even though the attach should fail.

As for CSI, yeah it looks like we could use `ValidateVolumeCapabilities` as the call is designed for verifying pre-provisioned volumes. And I agree, if there are cloud-specific admission controllers in the future, it'd be good to include this check there instead. When CSI begins to support topology, ideally `ValidateVolumeCapabilities` should also have a topology field. Synced with @saad-ali offline.
