### ISSUE TITLE
NetWorking policies examples not working

### ISSUE THREAD

**Issue by ErickWendel** [kubernetes/kubernetes#63327]
/kind bug
/sig network
/sig documentation

**What happened**:
Example from https://v1-10.docs.kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/# isn't working. When I call services before change networking policies, no changes happen

**What you expected to happen**:
Timeout inside pod before changes 
**How to reproduce it (as minimally and precisely as possible)**:

Following this docs https://v1-10.docs.kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/#

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.10.1
Server Version: v1.8.11

- Cloud provider or hardware configuration:
Azure - AKS
- OS (e.g. from /etc/os-release):
Linux 
- Kernel (e.g. `uname -a`):
- Install tools: aks
- Others:

**Comment by saiyan86** [comment]
It seems you don't have network plugin running.
Could you please deploy the following yaml and try again? 
This is the first version of Azure Network Policy Manager(network policy plugin).

https://github.com/saiyan86/acs-engine/blob/6ac0bca2ad9a22727a5e66e57ba57a1d2369b654/parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml

**Comment by cmluciano** [comment]
this feels stale now, please reopen if needed

/close
