### ISSUE TITLE
EncryptionConfig - no matches for kind "EncryptionConfig" in version "v1"

### ISSUE THREAD

**Issue by ErickWendel** [kubernetes/kubernetes#63325]
/kind bug
/sig security
**What happened**:
Documentation for [Encryption](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) is incorrect 
**What you expected to happen**:
Model definition correct

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.10.1
Server Version: v1.8.11
- Cloud provider or hardware configuration:
AKS - Azure
- OS (e.g. from /etc/os-release):
Linux 
- Kernel (e.g. `uname -a`): 
running from MacOS (Darwin Ericks-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64)
- Install tools: aks

@k8s-sig-onprem-api-reviews 
/sig security

**Comment by mikebryant** [comment]
Are you trying to use `kubectl apply/create`?

According to https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data this isn't an API resource, but the specification for a file you pass to `kube-apiserver` using the `--experimental-encryption-provider-config` flag.

**Comment by shubheksha** [comment]
@ErickWendel, this seems like an issue related to docs. Could you please file it in the [docs repo](https://github.com/kubernetes/website/issues/new)?

**Comment by dims** [comment]
yes please move this as @shubheksha mentioned.

/close

**Comment by ErickWendel** [comment]
thank you guys, is about `kube-apiserver` isn't flags :D
