### ISSUE TITLE
Image locality (scheduler priority function) inflates scheduling latency

### ISSUE THREAD

**Issue by depsched** [kubernetes/kubernetes#63345]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

When nodes store more images, each scheduleOne() will check every node's image list, and rebuild a image to image size map. This process can inflate the scheduling latency (the node scoring portion) by as much as 30% according to our measurements.

**What you expected to happen**:

Ideally we should build a map once every time the node status is updated, and reuse the map across serving all pod requests before the next update.

**How to reproduce it (as minimally and precisely as possible)**:

First, enable the image_locality policy in algorithmprovider/defaults/defaults.go. We ran about 50 nodes with each node storing about 100 images.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g. from /etc/os-release): debian jessie
- Kernel (e.g. `uname -a`): 4.4.1
- Install tools: kops
- Others:

**Comment by tossmilestone** [comment]
We could use `NodeInfo` in `schedulercache` to cache the image size result, if no one is working on this issue, I could take it if there is a conclusion.

**Comment by depsched** [comment]
@tossmilestone We actually did this fix and are submitting a PR by tomorrow :)

**Comment by tossmilestone** [comment]
@depsched that's all right

**Comment by resouer** [comment]
@depsched Please ping me (the original author of that priority) to review the patch.
