### ISSUE TITLE
Where to find the list of docker tags associated with k8s versions?

### ISSUE THREAD

**Issue by Strandedpirate** [kubernetes/kubernetes#63342]
I have an Azure ACS deployment of k8s. When upgrading between versions like 1.7.7 to 1.8.1 I read that I'm supposed to update various .yaml files on disk on the master and the nodes.

Where can I find the definitive list of docker tags that are associated to an overall k8s release?

e.g.
kubernetes 1.8.1 =

/etc/kubernetes/addons/kube-tiller-deployment.yaml: image: gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.1
/etc/kubernetes/addons/kubernetes-dashboard-deployment.yaml: image: gcrio.azureedge.net/google_containers/kubernetes-dashboard-amd64:v1.8.3
/etc/kubernetes/addons/kube-dns-deployment.yaml: image: gcrio.azureedge.net/google_containers/k8s-dns-kube-dns-amd64:1.14.8
/etc/kubernetes/addons/kube-dns-deployment.yaml: image: gcrio.azureedge.net/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.8
/etc/kubernetes/addons/kube-dns-deployment.yaml: image: gcrio.azureedge.net/google_containers/exechealthz-amd64:1.2
/etc/kubernetes/addons/kube-proxy-daemonset.yaml: image: "gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.8.1"
/etc/kubernetes/addons/kube-heapster-deployment.yaml: - image: gcrio.azureedge.net/google_containers/heapster-amd64:v1.4.2
/etc/kubernetes/addons/kube-heapster-deployment.yaml: - image: gcrio.azureedge.net/google_containers/addon-resizer:1.8.1
/etc/kubernetes/manifests/kube-controller-manager.yaml: image: "gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.8.1"
/etc/kubernetes/manifests/kube-scheduler.yaml: image: "gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.8.1"
/etc/kubernetes/manifests/kube-addon-manager.yaml: image: gcrio.azureedge.net/google_containers/kube-addon-manager-amd64:v6.4-beta.2
/etc/kubernetes/manifests/kube-apiserver.yaml: image: "gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.8.1"

/etc/default/kubelet: KUBELET_IMAGE=gcrio.azureedge.net/google_containers/hyperkube-amd64:v1.8.1

**Comment by dims** [comment]
@Strandedpirate gcrio.azureedge.net is not maintained in the community, can you please ask on https://github.com/Azure/acs-engine probably?

Thanks,
Dims

/close
