### ISSUE TITLE
Move from docker/docker to moby/moby

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#63343]
Why are we still using the old github repo?

We probably need to update cadvisor before we can switch over i guess.

**Comment by ceshihao** [comment]
I do NOT think it is doable now.

Because you can easily find old repo import everwhere in `moby/moby`, it can not get rid of the old repo.

e.g.
https://github.com/moby/moby/blob/master/api/types/client.go#L8
https://github.com/moby/moby/blob/master/api/types/configs.go#L4

**Comment by dims** [comment]
Yikes! @ceshihao
