### ISSUE TITLE
[CustomResourceSubresources] document and codes are not the same

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#63359]
the [doc](https://github.com/kubernetes/kubernetes/blob/ed9b25c90241b2b8a1fa10b96381c57f99ca952a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L168) said:
```
PUT requests to the /status subresource take a custom resource object and ignore changes to anything except the status stanza.
```

However the [codes](https://github.com/kubernetes/kubernetes/blob/ed9b25c90241b2b8a1fa10b96381c57f99ca952a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go#L42) are different, it does not allow to set spec and metadata, but other changes are not ignored. And updates to other parts are *not* validated.

**Comment by CaoShuFeng** [comment]
Made a pull request:
https://github.com/kubernetes/kubernetes/pull/63385

**Comment by sttts** [comment]
Is the documentation wrong or the implementation? I think there was a longer discussion about the correct behaviour in the PR, but haven't found it yet.

**Comment by CaoShuFeng** [comment]
> Is the documentation wrong or the implementation? 

It strange that other parts rather than metadata and spec can be modified and they are *not validated*.
So I think the implementation is wrong, at least.

**Comment by CaoShuFeng** [comment]
We should follow the design doc, I think.
https://github.com/kubernetes/community/blame/master/contributors/design-proposals/api-machinery/customresources-subresources.md#L153

**Comment by sttts** [comment]
@CaoShuFeng I agree the current behaviour is wrong. Added some comments to https://github.com/kubernetes/kubernetes/pull/63385.

Especially, https://github.com/kubernetes/kubernetes/pull/63385/files#r186384984 worries me whether we really have to right /status behaviour. Not really related to the given issue. But as we are touching the /status behaviour, we should clarify that as well.
