### ISSUE TITLE
e2e-image-puller doesn't work anymore.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#63355]
The docker binary we use in COS and most images is dynamically linked.
```
$ file docker 
docker: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=45a7a62f39ddabd51f5eaad2f561df08fe048371, with debug_info, not stripped
```

It won't work if we directly mount it into busybox, which is what we are doing in e2e-image-puller https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/e2e-image-puller.manifest#L105.

Here is the e2e image puller log:
```
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/alpine-with-bash:1.0
06:33:34 pulling k8s.gcr.io/apparmor-loader:0.1
06:33:34 pulling k8s.gcr.io/busybox:1.24
06:33:34 pulling k8s.gcr.io/dnsutils:e2e
/bin/sh: docker: not found
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/e2e-net-amd64:1.0
06:33:34 pulling k8s.gcr.io/echoserver:1.6
/bin/sh: docker: not found
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/eptest:0.1
06:33:34 pulling k8s.gcr.io/fakegitserver:0.1
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/galera-install:0.1
06:33:34 pulling k8s.gcr.io/invalid-image:invalid-tag
/bin/sh: docker: not found
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/iperf:e2e
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
06:33:34 pulling k8s.gcr.io/jessie-dnsutils:e2e
06:33:34 pulling k8s.gcr.io/k8s-dns-dnsmasq-amd64:1.14.5
06:33:34 pulling k8s.gcr.io/liveness:e2e
06:33:34 pulling k8s.gcr.io/logs-generator:v0.1.0
06:33:34 pulling k8s.gcr.io/mounttest:0.8
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
/bin/sh: docker: not found
...
```

I believe this has been broken for a long time. Given that the e2e test works fine till now without it, should we just remove it?

@yujuhong @kubernetes/sig-node-bugs @kubernetes/sig-testing-bugs

**Comment by Random-Liu** [comment]
Another option is to make `crictl` statically built, and use `crictl` instead.

**Comment by BenTheElder** [comment]
Any update here?

**Comment by yujuhong** [comment]
> Any update here?

Nope. We can just `crictl` to pre-pull the images as @Random-Liu said.
We added the image prepulling as a workaround due to the overwhelming amount of flake caused by pulling during the tests. Pulling seems to be more reliable than before. 

Will bump the priority if this becomes an issue again. In the meantime, if anyone wants to help with the change, feel free to go ahead.
