### ISSUE TITLE
Image locality (scheduler priority function) misses untagged image

### ISSUE THREAD

**Issue by depsched** [kubernetes/kubernetes#63354]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

The default behavior of docker is when someone runs "docker pull" an image, when the tag is not specified (e.g., nginx), the latest build tag (":latest") is assumed and appended to the image (e.g., nginx:latest). In k8s, the node only reports the image name with the ":latest" tag appended, and hence when users do not specify image tag (when expecting the ":latest" as in docker), the image locality function won't be able to spot a match even where there are matches.

**What you expected to happen**:

- Either banking on users always specifying a versioned tag (or the latest tag) with the images, or:
- Preserving the same semantics of untagged image by appending when matching images.

**How to reproduce it (as minimally and precisely as possible)**:

Repeat what described above and log to see whether there is image match misses.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): debian jessie
- Kernel (e.g. `uname -a`): 4.4.1
- Install tools: kops
- Others:

**Comment by resouer** [comment]
/assign

There's known inconsistency after CRI is enabled by default, will take a look at it.

**Comment by silveryfu** [comment]
@resouer Adding a check (whether there is ":tag" or not) upon updates of ImageSizes in schedulercache seems to be a reasonable fix? The node's reporting the ":latest" tag by default is reasonable.

**Comment by resouer** [comment]
kubelet always `applyDefaultImageTag` for image pull, so @silveryfu you should be fine to append `:latest` tag if it's not specified. 

Would you like to send a PR or busy now?
