### ISSUE TITLE
Flaky IPVS Test: [sig-network] Services should have session affinity work for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/kubernetes#63351]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The test is flaky with the error something like:

`Could not reach HTTP service through [IP] after 15m0s: <nil>`

**What you expected to happen**:
Test should pass

/assign @Lion-Wei

**Comment by Lion-Wei** [comment]
Cases are green now. :tada:
