### ISSUE TITLE
Review HPA v2 Metrics Spec Merge Patch Strategy

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#63365]
Looks like we don't have a mergeStrategy tag set on the HPA `metrics` field, meaning we get the default replace behavior.  We should probably have the merge behavior instead, so that you can easily add metrics to the list.

cc @kubernetes/sig-autoscaling-feature-requests

**Comment by liggitt** [comment]
changing the strategy to `merge` means new clients will send partial results to an n-1 server which would then replace the entire list, dropping all items that weren't sent

**Comment by DirectXMan12** [comment]
We can do it in the new beta that we'll need for our other revisions.

**Comment by DirectXMan12** [comment]
probably not -- I don't think there's anything we can use as a merge key.
