### ISSUE TITLE
DNS tests may pass if DNS not configured or unreachable

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#63366]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig testing

**What happened**:

Tests checking DNS responses can have false positives, such as "should provide DNS for services".

The tests rely on dig-ing certain domain names [1]:

     test -n "$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK > /results/wheezy_udp@kubernetes.default

The problems could be that, if a host / container doesn't have any entries in their ``resolv.conf`` file or the configured DNS servers are not reachable, dig will output this into ``stdout``:
     
    ubuntu@ubuntu:~$ dig +notcp +noall +answer +search kubernetes.default A
    ;; connection timed out; no servers could be reached
     
, causing the test to pass and to write "OK" into the results file.

     
[1] https://github.com/kubernetes/kubernetes/blob/dcc6d78ac02672f8afe14aee7679d0e5fc570980/test/e2e/network/dns_common.go#L410

**What you expected to happen**:

The tests shouldn't be able to pass if dig failed.

**How to reproduce it (as minimally and precisely as possible)**:

Comment all nameservers or configure a bogus DNS server in ``/etc/resolv.conf``, and run:

    test -n "$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): "Ubuntu 16.04.3 LTS"
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-87-generic

**Comment by fturib** [comment]
@bclau : But one of the purpose of the test is to ensure that the DNS of the cluster is replying. In other words, if it does not reply then we EXPECT this test to fail.

If you are not using DNS then isn't it better to SKIP the test ?

**Comment by chrisohaver** [comment]
I believe @bclau means to say "false negatives" ... meaning that in some situations, the test will errantly pass, when it should fail.

**Comment by fturib** [comment]
oops . Looks like I misread the description, and agree that the dig should work.
