### ISSUE TITLE
Updating a cronjob causes jobs to be scheduled retroactively

### ISSUE THREAD

**Issue by ozzieba** [kubernetes/kubernetes#63371]
/kind bug

**What happened**:
When updating a cronjob, the schedule takes effect retroactively, meaning "missed" jobs from before the update are started
**What you expected to happen**:
The new schedule only takes effect from the time of the update
**How to reproduce it (as minimally and precisely as possible)**:
```
$ TZ=UTC date
Wed May  2 16:32:01 UTC 2018
$ kubectl run test --image=alpine --schedule='33 16 * * *' --restart=Never echo hi
cronjob "test" created
$ kubectl get cronjob
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST SCHEDULE   AGE
test      33 16 * * *   False     1         Wed, 02 May 2018 12:33:00 -0400
$ TZ=UTC date
Wed May  2 16:34:08 UTC 2018
$ kubectl get -o yaml cronjob test|sed 's/33 16/34 16/g'|kubectl replace -f -
cronjob "test" replaced
$ kubectl get cronjob
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST SCHEDULE   AGE
test      34 16 * * *   False     2         Wed, 02 May 2018 12:34:00 -0400
```

**Anything else we need to know?**:
Looks like the culprit is at https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/utils.go#L113, where the earliestTime to consider scheduling a job is set to the cronjob's creationTimestamp, without taking the updateTimestamp into account
**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE

@soltysh

**Comment by janetkuo** [comment]
> Looks like the culprit is at https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/utils.go#L113, where the earliestTime to consider scheduling a job is set to the cronjob's creationTimestamp, without taking the updateTimestamp into account

It should be this, because earliestTime is set to a cronjob's creationTimestamp only when its LastScheduleTime is empty, which is not the case in your example:
```console
$ kubectl get cronjob
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST SCHEDULE   AGE
test      33 16 * * *   False     1         Wed, 02 May 2018 12:33:00 -0400
```

CronJob does not keep track of the last time it's updated; moreover, user isn't the only one who will update a CronJob, CronJob controller also keeps updating CronJob (e.g. its status).  

CronJob controller keeps looking for the latest "missed schedule" time and then create a job for that time.  This is probably what happened. 

To get the behavior you want, you'd probably want to delete old CronJob and create a new one. I start thinking that it may make sense to make CronJob spec immutable.

**Comment by ceshihao** [comment]
The same problem #65457

**Comment by ceshihao** [comment]
> To get the behavior you want, you'd probably want to delete old CronJob and create a new one. I start thinking that it may make sense to make CronJob spec immutable.

I think maybe it can be resolved by making CronJobSpec.Schedule immutable at lease. Since CronJob does not keep the last update time.

**Comment by soltysh** [comment]
Making the schedule immutable is not practical, imho.

**Comment by DaneGardner** [comment]
Is there a workaround for this?  Is manually deleting and recreating the cronjob the current best method?  Triggering jobs immediately on edit makes this unsafe for some uses.

**Comment by soltysh** [comment]
This is still a problem.
/remove-lifecycle rotten

**Comment by soapergem** [comment]
I ran into this issue today as well, and it makes the CronJob object in Kubernetes basically unusable. It's a common workflow for us to effectively suspend Cron tasks in reaction to certain conditions (whether those are Kubernetes jobs or external tasks running on a schedule). But if we suspend it for too long in K8S, the CronJob may never start again? That's disastrous. This object honestly isn't ready for production use until this bug gets fixed.

**Comment by dims** [comment]
long-term-issue (note to self)

**Comment by chenbr** [comment]
I just ran into this now.. when we can expect a fix?

**Comment by teng1** [comment]
Please, can this be addressed? This happened today:

Usecase:
Advising a local dev team that they can edit the schedule of a CronJob to later and prevent it running at the previously specified time;  in this case it runs a job to shut down AWS infrastructure overnight in a non production environment.

Outcome:
Infrastructure needed to be kept up for longer is immediately terminated!!!

**Comment by inaz2** [comment]
I think we should assign this bug with the higher priority because this bug cause the unintended job execution with destructive change such as data modification, deletion or some kinds of notificaiton to **users**.
Some may think the jobs should be idempotent, however cronjobs are generally used for repetitive small tasks and making all of such tasks idempotent is the excessive requirement.

I suggest to clear `lastScheduleTime` of the cronjob status with logging the proper message.

**Comment by GuyCarmy** [comment]
Also ran into this just now, caused an unintentional trigger.
changed a cronjob with the purpose of delaying it and caused an immediate execution.

just a +1 for this issue.

**Comment by wontheone1** [comment]
+1 for this issue.

**Comment by FishkinsDC** [comment]
I also just encountered this

**Comment by ivnilv** [comment]
Just bumped into this as well... Was wondering why my cronjob is not executed in the past days, even though the schedule clearly says it should have ... It happens when you edit existing cron jobs and change the schedule... Hoping for a fix soon :pray: :bug:

**Comment by aksharj** [comment]
I encountered this too, would deleting the job and creating a new one every time we want to update the schedule be the suggested workaround till the issue is fixed?

**Comment by andrewsav-datacom** [comment]
We've just had a case of a job triggered from cronjob on apply, even when cronjob schedule has not changed.

**Comment by maikelvl** [comment]
We also encountered this. 😒

**Comment by JnMik** [comment]
Still an issue

**Comment by jwldk** [comment]
Well, we had a fun morning with this issue. Was meaning to push a cronjob forward for later, but we sent out 1000 emails before we could kill it. Not what you would expect for a simple change og schedule.

**Comment by seh** [comment]
We too ran into this problem this week, several times before we caught on to what was going on.

**Comment by CyberHippo** [comment]
Also encountered this issue and I can't find a way to clear the `lastScheduleTime` except by deleting the CronJob..

**Comment by carmelid** [comment]
Fortunately I ran into this issue in dev, so I did not send any notifications to users or 3rd parties in production. As @inaz2 said
>I think we should assign this bug with the higher priority because this bug causes the unintended job execution with destructive change such as data modification, deletion or some kinds of notification to users.

Please assign proper resources to take a look at this issue 🙏

**Comment by GuyCarmy** [comment]
another +1 for more resources on this issue, 
last year I commented here when we had this happen with a not so important cronjob that cleans tests data from staging env.
a few weeks ago we had it with a cronjob that trigger customer emails!

**Comment by creatica-soft** [comment]
same here, jobs are triggered when a schedule is updated, even though it does not meet the schedule

**Comment by shahrukh330** [comment]
+1 for a fix for this issue. Ran into this issue on prod.

**Comment by sarahhenkens** [comment]
Since it seems that this bug is ignored, are there any alternatives we can use that would manage and control job execution?

**Comment by maikelvl** [comment]
@sarahhenkens Yes. Like [@janetkuo suggested](#issuecomment-399286277) first deleting the cronjob and then apply the new cronjob prevents this behaviour.

**Comment by tavin** [comment]
It seems that changing `suspend: true` to `suspend: false` also causes immediate job execution. So you have to wait until just after the scheduled time to safely unsuspend.

**Comment by lentzi90** [comment]
Does setting `startingDeadlineSeconds` mitigate this issue ([docs](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#starting-deadline))? I.e. if the starting deadline is tight enough...

For example, I would normally set the `startingDeadlineSeconds` to something like a few minutes since I don't want my CronJobs to run at some random time later if they fail to start. In this case I would expect a change in the schedule to trigger a new Job *only if* a new Job was supposed to happen somewhere between `startingDeadlineSeconds` before and now (when I change the schedule).

**Comment by jekakm** [comment]
I'm also having this issue on 1.18.9.
I just change schedule from 9 UTC to to 10 UTC at 10:50 UTC and gets job execution, that caused some mess in my application. I think this should not happens by default.

**Comment by dims** [comment]
Please see the new controller being worked on here - https://github.com/kubernetes/kubernetes/pull/93370

**Comment by thuandt** [comment]
I'm running EKS 1.21 with CronJob Controller v2 and still have similar issue.

My CronJob was auto-triggered by kube-controller-manager after ArgoCD update schedule and spec (container image).

Platform: AWS EKS
Kubernetes version: 1.21
Platform version: eks.6

**Comment by mimmus** [comment]
Can I ask if this (serious) issue is solved in some Kubernetes release?
I'm running 1.21.6 and this issue just disrupted an important workload.

**Comment by tavin** [comment]
Afaics this is by design and won't be "fixed" -- hence `startingDeadlineSeconds` is the best answer... if you don't want a job to be triggered retroactively, you need to make sure this value is less than the age of the most recent "schedule miss"

**Comment by tsuna** [comment]
This bug just cost us thousands of dollars 😓
