### ISSUE TITLE
verify-openapi-spec.sh frequently hanging in CI

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#63378]
Many PRs have been failing due to the `pull-kubernetes-verify` job timing out.

It looks like both PR and CI jobs are affected:
http://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-verify&width=5&graph-metrics=test-duration-minutes
http://k8s-testgrid.appspot.com/sig-release-master-blocking#verify&width=20&graph-metrics=test-duration-minutes

The failures aren't consistent, but there appears to be a clear uptick starting around 13:00 PDT on Monday, April 30. 

There aren't any notable test-infra changes from that time.

For suspicious kubernetes changes, nothing immediately leaps out.
The only two PRs I find suspicious:
* https://github.com/kubernetes/kubernetes/pull/58474, since it affects apiserver (which we run in update-openapi-spec.sh) and appears to have had several similar timeouts in verify-openapi-spec.sh before it merged. 
* https://github.com/kubernetes/kubernetes/pull/60034, since it affects startup/shutdown logic, but in kubelet/device manager, so I don't think it'd affect this change.

I've been `set -x` debugging the verify scripts, and the last lines printed before hanging are
```
W0502 20:36:35.746] + echo '/go/src/k8s.io/kubernetes/api/openapi-spec up to date.'
W0502 20:36:35.746] + cp -a /go/src/k8s.io/kubernetes/_tmp/openapi-spec /go/src/k8s.io/kubernetes/api/openapi-spec/..
W0502 20:36:35.746] + rm -rf /go/src/k8s.io/kubernetes/_tmp
W0502 20:36:35.746] + echo 0
W0502 20:36:35.746] + tr -d '\n'
```

which corresponds to 
https://github.com/kubernetes/kubernetes/blob/0d43bdec2b8598ff542a1afdee876d417b4e7668/third_party/forked/shell2junit/sh2ju.sh#L48-L49
and
https://github.com/kubernetes/kubernetes/blob/0d43bdec2b8598ff542a1afdee876d417b4e7668/third_party/forked/shell2junit/sh2ju.sh#L110-L112

so there might be some weird pipe/buffering nonsense going on causing everything to get stuck.
(I'm still not sure what would cause this to start failing, though.)

cc @cblecker @BenTheElder

**Comment by ixdy** [comment]
ok, this is suspicious: I added a `ps ax` to the end of `hack/verify-openapi-spec.sh`, and it shows a kube-apiserver still running:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-verify/89061/?log#log
```
I0502 22:03:26.053]   PID TTY      STAT   TIME COMMAND
I0502 22:03:26.053]     1 ?        Ss     0:00 /bin/bash ./hack/jenkins/verify-dockerized.sh
I0502 22:03:26.053]     7 ?        S      0:00 make verify
I0502 22:03:26.054]  4180 ?        Rl     0:09 /go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/kube-apiserver --insecure-bind-address=127.0.0.1 --bind-address=127.0.0.1 --insecure-port=8050 --etcd-servers=http://127.0.0.1:2379 --advertise-address=10.10.10.10 --cert-dir=/tmp/update-openapi-spec.SZ4G/certs --runtime-config=api/all=true --token-auth-file=/tmp/update-openapi-spec.SZ4G/tokenauth.csv --logtostderr --v=2 --service-cluster-ip-range=10.0.0.0/24
I0502 22:03:26.054]  4250 ?        R      0:00 ps ax
I0502 22:03:26.054] 19038 ?        S      0:00 /bin/bash hack/make-rules/verify.sh
I0502 22:03:26.055] 28688 ?        S      0:00 /bin/bash hack/make-rules/verify.sh
I0502 22:03:26.055] 28689 ?        S      0:00 /bin/bash hack/make-rules/verify.sh
I0502 22:03:26.055] 28690 ?        S      0:00 tee /var/tmp/ju19038-err.txt
I0502 22:03:26.055] 28691 ?        S      0:00 /bin/bash hack/make-rules/verify.sh
I0502 22:03:26.055] 28692 ?        S      0:00 tee -a /var/tmp/ju19038.txt
I0502 22:03:26.056] 28693 ?        S      0:00 /bin/bash hack/make-rules/verify.sh
I0502 22:03:26.056] 28694 ?        S      0:00 bash hack/make-rules/../../hack/verify-openapi-spec.sh
```

This is despite `update-openapi-spec.sh` theoretically killing the apiserver:
https://github.com/kubernetes/kubernetes/blob/0d43bdec2b8598ff542a1afdee876d417b4e7668/hack/update-openapi-spec.sh#L32-L39

**Comment by ixdy** [comment]
maybe we're missing some flags in 
https://github.com/kubernetes/kubernetes/blob/0d43bdec2b8598ff542a1afdee876d417b4e7668/hack/update-openapi-spec.sh#L58-L70
?

**Comment by rphillips** [comment]
I'll look into it tonight.

**Comment by ixdy** [comment]
per discussion on slack, I think we want to revert #58474 to attempt to get CI healthy again: https://github.com/kubernetes/kubernetes/pull/63380

**Comment by rphillips** [comment]
https://github.com/rphillips/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/signal.go#L36-L39

Does the stop channel need to be propagated to the lease reconciler? On a TERM, the shutdown is blocking on the second channel read.

**Comment by liggitt** [comment]
figured out the issue.

after the signal-driven stop channel is closed, the apiserver runs pre-shutdown tasks before exiting (and waits for them to complete):

https://github.com/kubernetes/kubernetes/blob/4558e419bc3f084c0f5106180f14fb4831c8f153/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L260-L265

one of those tasks is a blocking task to call the active reconciler's StopReconciling() method:

https://github.com/kubernetes/kubernetes/blob/03eb9f687f3a44de58c4e06887349ff0dcaf2109/pkg/master/master.go#L380

https://github.com/kubernetes/kubernetes/blob/03eb9f687f3a44de58c4e06887349ff0dcaf2109/pkg/master/controller.go#L117-L120

https://github.com/kubernetes/kubernetes/blob/4558e419bc3f084c0f5106180f14fb4831c8f153/pkg/master/controller.go#L150-L156

comparing the master-count and lease implementations of StopReconciling(), the lease reconciler makes more etcd calls (it deletes the lease, lists other leases, fetches and updates endpoints; the master-count reconciler did a single get/put of endpoints).

the verify script sends SIGINT to the apiserver, doesn't wait for the apiserver to actually exit, then terminates etcd so the lease reconciler had a better shot of getting etcd ripped out from under it while still trying to talk to etcd, and the etcd client doesn't react well to etcd disappearing mid-request.

I'll open a PR reverting the revert, and put a reasonable timeout on the apiserver shutdown service unregister (both the mastercount and lease were vulnerable to this, the lease one just hit it more)

**Comment by ixdy** [comment]
> doesn't wait for the apiserver to actually exit,

Would a better fix be to update the script to wait for the apiserver to exit?

**Comment by liggitt** [comment]
we can do both, but if circumstances beyond our control mean etcd is dead, the apiserver should still be well-behaved

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/63383

**Comment by liggitt** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/63380
