### ISSUE TITLE
Can't compile kubectl with master branch

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#63384]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig cli
> /kind feature

**What happened**:
Can't compile kubectl with master branch, I think it was because generated bindata was deleted, so compiling failed
```
➜  kubernetes git:(master) go build cmd/kubectl/kubectl.go 
# k8s.io/kubernetes/pkg/kubectl/util/i18n
pkg/kubectl/util/i18n/i18n.go:106:16: undefined: generated.Asset
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zjj2wry** [comment]
https://github.com/kubernetes/kubernetes/pull/62432

**Comment by liggitt** [comment]
Use ‘make WHAT=cmd/kubectl‘ to ensure prerequisite generated files are built
