### ISSUE TITLE
How to remove PodCIDR of node?

### ISSUE THREAD

**Issue by mdianjun** [kubernetes/kubernetes#63390]
Is there any way to remove PodCIDR of a node except deleting the node and rejoining it to the cluster? I had changed --allocate-node-cidrs from true to false in kube-controller-manager.yaml, but some nodes had been assigned PodCIDR.

```
[root@KC-BCC-POD24-10-196-108-10 ~]# kubectl get node kc-bcc-pod24-10-196-108-10.hadoop.jd.local -oyaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2018-03-01T12:42:45Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: KC
    failure-domain.beta.kubernetes.io/zone: KC-POD24
    kubernetes.io/hostname: kc-bcc-pod24-10-196-108-10.hadoop.jd.local
    node-role.kubernetes.io/master: ""
  name: kc-bcc-pod24-10-196-108-10.hadoop.jd.local
  resourceVersion: "16834139"
  selfLink: /api/v1/nodes/kc-bcc-pod24-10-196-108-10.hadoop.jd.local
  uid: 0a8b9684-1d4e-11e8-b22b-3cfdfe5f325c
spec:
  externalID: kc-bcc-pod24-10-196-108-10.hadoop.jd.local
  podCIDR: 10.163.120.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    timeAdded: null
status:
```
/kind feature

sig/node

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
@mdianjun You can try to `kubectl edit node kc-bcc-pod24-10-196-108-10.hadoop.jd.local` and manually remove that attribute.

**Comment by mdianjun** [comment]
@dixudx  It's forbidden.

```
# nodes "kc-bcc-pod24-10-196-108-11.hadoop.jd.local" was not valid:
# * spec.podCIDR: Forbidden: node updates may not change podCIDR except from "" to valid
# * []: Forbidden: node updates may only change labels, taints, or capacity (or configSource, if the DynamicKubeletConfig feature gate is enabled)
```

**Comment by kvaps** [comment]
Agree same problem:
```
kubectl patch node mynode -p '{"spec":{"podCIDR":""}}'
The Node "mynode" is invalid: 
* spec.podCIDR: Forbidden: node updates may not change podCIDR except from "" to valid
* []: Forbidden: node updates may only change labels, taints, or capacity (or configSource, if the DynamicKubeletConfig feature gate is enabled)
```

**Comment by cokabug** [comment]
same here

**Comment by kvaps** [comment]
Hi, I found the way:
```bash
NODE=node1
kubectl get node $NODE -o json | jq 'del(.spec.podCIDR)' |(kubectl delete node $NODE && kubectl create -f -)
```
In this case, all pods won't be removed, but better to clear node from all the pods.
Please make sure that you have `jq` installed before.

**Comment by ylhyh** [comment]
@kvaps, it's not work
Example:
node001 joined to k8s first time, and got assigned pod cidr 10.112.11.0/24 from k8s, then I removed it from k8s cluster by some reason.  Is it posible to keep the original cidr 10.112.11.0/24?  Actually it is always create a new cidr, such as: 10.112.12.0/24, 10.112.13.0/24, 10.112.14.0/24 ...

**Comment by kvaps** [comment]
@ylhyh you can specify `.spec.podCIDR` during creation new node, example:
```yaml
apiVersion: v1
kind: Node
metadata:
  name: newnode
spec:
  podCIDR: 192.168.0.0/24
```
In case if you want to change`.spec.podCIDR` for existing node, you need to delete and create it again, example:
```
kubectl get node mynode -o yaml > /tmp/mynode.yaml
```
Open `/tmp/mynode.yaml` and edit `.spec.podCIDR` there, then recreate:
```
kubectl delete node mynode
kubectl create node /tmp/mynode.yaml
```
Of course your node shouldn't have any workload.
