### ISSUE TITLE
Emit Events when Pod Status changes

### ISSUE THREAD

**Issue by salilgupta1** [kubernetes/kubernetes#63440]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
When a Pod's status changes K8s doesn't emit an event. It would be really helpful if K8s could emit an event mentioning that the Pod's status change. I currently have to listen to the events stream to grab events regarding image pulls etc ... AND the pod stream to grab the status of a pod. 

**What you expected to happen**:
Explained above

**How to reproduce it (as minimally and precisely as possible)**:
Start a pod and listen to the event stream. If the container in the pod fails the pod status changes to Failed but no event is emitted referring to this change.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.11
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
events aren't really considered a reliable message bus... they are best effort, and are highly rate-limited on the client side. not sure replicating changes from various objects into events is desired

**Comment by salilgupta1** [comment]
So is the recommended way to watch for state changes to a Pod or any object just watch the relevant object endpoint?

**Comment by salilgupta1** [comment]
Also, are there any negative effects to generating these events besides setting the precedence for a potentially undesirable paradigm?

**Comment by liggitt** [comment]
> So is the recommended way to watch for state changes to a Pod or any object just watch the relevant object endpoint?

it depends what information you want... detailed state changes for a pod are best observed by watching the pod API

> Also, are there any negative effects to generating these events besides setting the precedence for a potentially undesirable paradigm?

write multiplication is always a concern for core APIs like this

**Comment by salilgupta1** [comment]
Ahh makes sense. Thanks for the quick responses, @liggitt
