### ISSUE TITLE
Setting individual hostname for every pod in ReplicationController or Deployment?

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#63462]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
Now k8s does not support setting hostname for every pod in rc or deployment.

**What you expected to happen**:
Why not support it?Just like cni and ipam,the feature setting hostname by self should be useful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by khenidak** [comment]
are you referring to `host: nnn` in spec? 
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

**Comment by mjaow** [comment]
@khenidak I need to make all pods in rc have its own hostname.`host:nnn` cannot make it

**Comment by AlanCarl** [comment]
How can you fix this?  
In our project. we have no need for name consistency, persistent data or anything else - just valid DNS. 
Same issue can be found in #60789, but it's still unsolved.

**Comment by jmarcos-cano** [comment]
To anyone stepping by with this problem you should be able to fix it by adding:

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

```
spec:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
```

**Comment by gmcruz** [comment]
I could really use this as I have a need to set a different Hostname for each of my replicas. As they register onto zookeeper they each need a different hostname. Without this, they all have the same hostname and Zookeeper only registers one of them. Help, please. StatefulSet is not needed here as my app only registers on Zookeeper but no State is needed or wanted. They are simply workers.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyrexdeployment
  labels:
    app: gyrex
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gyrex
  template:
    metadata:
      labels:
        app: gyrex
    spec:
      hostname: gyrexone <--- really bad need each replica to have its own hostname.
