### ISSUE TITLE
Support container resource limit updates

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#6347]
There is an [outstanding Docker PR](https://github.com/docker/docker/pull/11442) to update container resource limits. Once this feature gets into docker, Kubernetes should support dynamically scaling container resource limits.

**Comment by resouer** [comment]
The original PR (from my friend actually) is closed? What about the progress of this issue ...

**Comment by bgrant0607** [comment]
Closing in favor of #5774
