### ISSUE TITLE
Pods stuck on terminating (Terminated: ExitCode)

### ISSUE THREAD

**Issue by mouradmourafiq** [kubernetes/kubernetes#63470]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:

Running the helm command `helm del --purge releaseName` sometimes deletes volumes before pods, which results in pods stuck in `Terminated: ExitCode`.

**What you expected to happen**:

I expect the pods to be delete as well without having to manually delete them with `--grace-period=0 --force` options.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
`Digital Ocean`
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@mouradmourafiq can you please post this to https://github.com/kubernetes/helm/issues/ ?

/close
