### ISSUE TITLE
kubeadm upgrade plan wont work on HA ( 3 masters / HA etcd cluster )

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#63487]
/kind bug
/sig architecture
/sig cluster-lifecycle

**What happened**:
error executing **_kubeadm upgrade plan_**

**What you expected to happen**:
to view COMPONENT versions

**How to reproduce it (as minimally and precisely as possible)**:
```
[root@APP197 gabriel]$ /tmp/kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
could not read manifests from: /etc/kubernetes/manifests, error: failed to check if etcd pod implements TLS: failed to read manifest for "/etc/kubernetes/manifests/etcd.yaml": open /etc/kubernetes/manifests/etcd.yaml: no such file or directory
```

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.10.0**
- Cloud provider or hardware configuration: **vmware**
- OS (e.g. from /etc/os-release): **centos 7.4**
- Kernel (e.g. `uname -a`): **3.10.0-693.21.1.el7**

**Comment by gabrielfsousa** [comment]
```
/tmp/kubeadm upgrade apply v<YOUR-CHOSEN-VERSION-HERE>
```
works, but i dont know if the k8s is compatible with my etcd server/cluster. 

in my case i think it is, my etcd version is 3.1.12 and everything is working with 1.10.2

**Comment by dims** [comment]
Can you please move this to https://github.com/kubernetes/kubeadm/issues/ ?

/close
