### ISSUE TITLE
Update fedora installation docs 

### ISSUE THREAD

**Issue by BlueShells** [kubernetes/kubernetes#6348]
First thing I used https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/fedora/fedora_manual_config.md 

when I run "kubectl create -f node.json"

I get this
"F0402 13:41:04.433489   16900 create.go:50] Error: Node "fed-node" is invalid: [status.Capacity: required value, spec.ExternalID: required value]"

I think there something changed in the 
{
  "id": "fed-node",
  "kind": "Minion",
  "apiVersion": "v1beta1",
  "labels": {
    "name": "fed-node-label"
  }
}
and when I run  "kubectl get nodes"
I got this message:
"F0402 13:43:32.101082   17080 get.go:70] Error: Get http://fed-master:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 192.168.0.133:4001: connection refused"

the IP is right ,the very ip of this machine,and the fefd-master is in the hosts file,So I tired to get the 4001
"netstat -an | grep 4001"
and I got the output:
"tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN"
and the output of "curl -L http://127.0.0.1:4001/version" is 

"{"releaseVersion":"2.0.3","internalVersion":"2"}"

it seems that the etcd only listen the 127.0.0.1 not the 192.168.0.133 ,I do not know why,please help out of this ,thanks

**Comment by mattf** [comment]
it looks like the fedora docs are stale in a few places.

re node is invalid - some parameters are missing from the json, but this step shouldn't be necessary. instead KUBELET_ADDRESSES=--machines=... should be added to the controller-manager config.

re etcd - it's config needs to be changed. /etc/etcd/etcd.conf needs ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001". alternatively on fed-master you can change /etc/hosts to map fed-master to 127.0.0.1

**Comment by bprashanth** [comment]
@BlueShells please report back if @mattf s recommendation solves your problem

**Comment by BlueShells** [comment]
@mattf @bprashanth  thanks ,I changed the /etc/etcd/etcd.conf and have no errors now,I will move forward to ,thanks

**Comment by mattf** [comment]
some changes to the doc to address this are in pr  #6402

**Comment by BlueShells** [comment]
@mattf ,I see a lot of errors appear on both master and node 

master:
"Apr  3 17:14:52 fedora kubelet: E0403 17:14:52.851929   25198 kubelet.go:1729] error updating node status, will retry: error getting node "127.0.0.1": minion "127.0.0.1" not found
Apr  3 17:14:52 fedora kubelet: E0403 17:14:52.853322   25198 kubelet.go:1729] error updating node status, will retry: error getting node "127.0.0.1": minion "127.0.0.1" not found
Apr  3 17:14:52 fedora kubelet: E0403 17:14:52.854731   25198 kubelet.go:1729] error updating node status, will retry: error getting node "127.0.0.1": minion "127.0.0.1" not found
"

node:
"Apr  3 17:15:05 fedora kubelet: E0403 17:15:05.601839    8046 kubelet.go:1729] error updating node status, will retry: error getting node "fed-node": minion "fed-node" not found
Apr  3 17:15:05 fedora kubelet: E0403 17:15:05.603080    8046 kubelet.go:1729] error updating node status, will retry: error getting node "fed-node": minion "fed-node" not found
Apr  3 17:15:05 fedora kubelet: E0403 17:15:05.604470    8046 kubelet.go:1729] error updating node status, will retry: error getting node "fed-node": minion "fed-node" not found"

does I did something wrong?

**Comment by eparis** [comment]
So the first problem 'should' be fixed:
https://github.com/GoogleCloudPlatform/kubernetes/pull/6325
Although it doesn't seem we have that build in Fedora yet.

The second problem (127.0.0.1:4001 vs fed-master:4001) does need fixed in the docs.  Sorry.

**Comment by mattf** [comment]
@BlueShells pls start from scratch. it may be that your setup has gotten into a bad state, esp if you're seeing things about node/minion 127.0.0.1

**Comment by goltermann** [comment]
@eparis bringing to your attention

**Comment by wkevils** [comment]
It seems that the first proble, which is resolved, is not yet in the Fedora updates repo:
https://github.com/GoogleCloudPlatform/kubernetes/pull/6325

Because under:
http://mirror.netcologne.de/fedora/linux/updates/testing/21/x86_64/k/
I see only two kubernetes rpm files, from 27 of March 2015, which is before the fix was done.

So currently we cannot work according to the Getting started on Fedora page:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/fedora/fedora_manual_config.md

Any advice/workaround ? when is this fix expected to be merged into fedora testing update ?

**Comment by eparis** [comment]
i'll work on the doc today.

**Comment by BlueShells** [comment]
@eparis I tried the doc again today ,here is the thing I run into 

1(master):Unable to listen for secure (open /var/run/kubernetes/apiserver.crt: no such file or directory); will try again.

I tired "/usr/bin/mkdir /var/run/kubernetes" and "/usr/bin/chown -R kube:kube /var/run/kubernetes/" 

2(node):Apr 15 17:17:45 fedora kubelet: E0415 17:17:45.683276    8629 kubelet.go:1729] error updating node status, will retry: error getting node "fed-node": minion "fed-node" not found

I checked everything ,but can't figure it out 

my system is fedora21

thanks

**Comment by eparis** [comment]
1) I don't have any idea. systemd will create that directory before it starts... 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/init/systemd/tmpfiles.d/kubernetes.conf

2) do oyu have mismatched versions between your master and nodes? can you show me the kubectl get node from the master and the journalctl -b -u kubelet ?

**Comment by mattf** [comment]
fyi, (1) is a red herring

**Comment by bgrant0607** [comment]
Obsolete
