### ISSUE TITLE
HA with 3 masters kubectl top wont work after Custom Metrics API

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#63486]
/kind bug
/sig autoscaling
/sig scalability

**What happened**:
**_kubectl top_** only work on one master  ( HA with 3 masters )
```
[root@APP198 log]$ kubectl top pod --all-namespaces
error: You must be logged in to the server (Unauthorized)
```

**What you expected to happen**:
**_kubectl top_** to work on all masters like before ( on 3 masters )

**How to reproduce it (as minimally and precisely as possible)**:
after installed (Custom Metrics API) kubernetes-incubator/metrics-server **_kubectl top_** only works on one master

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.10.0**
- Cloud provider or hardware configuration: **vmware**
- OS (e.g. from /etc/os-release): **centos 7.4**
- Kernel (e.g. `uname -a`): **3.10.0-693.21.1.el7**

**Comment by DirectXMan12** [comment]
I seem to vaguely recall from last time that this came up that this wasn't a problem with any of our code -- whatever was doing the deployment was provisioning different proxy certs per master, which is the wrong thing to do.

What's your deployment tool?
