### ISSUE TITLE
Scheduler metrics not captured properly in density test

### ISSUE THREAD

**Issue by mdianjun** [kubernetes/kubernetes#63493]
File:  test/e2e/scalability/density.go

When running e2e performance test, the density test output scheduling latency as follows:
```
May  8 00:55:23.397: INFO: Printing summary: SchedulingLatency
May  8 00:55:23.397: INFO: SchedulingLatency JSON
{
  "scheduling": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  },
  "binding": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  },
  "total": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  }
}
```

Why are these values zero? Is it because of not reseting scheduler metrics? 
The codes:
```
		// Verify scheduler metrics.
		// TODO: Reset metrics at the beginning of the test.
		// We should do something similar to how we do it for APIserver.
		latency, err := framework.VerifySchedulerLatency(c)
		framework.ExpectNoError(err)
		if err == nil {
			summaries = append(summaries, latency)
		}
		summaries = append(summaries, testPhaseDurations)
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shyamjvs** [comment]
Yeah, we're not really collecting those scheduler metrics properly. It's a long-standing bug.

@krzysied - Would you be able to take a look into this?

**Comment by shyamjvs** [comment]
I was proposing that we add the summary metric alongside - I remember doing sth similar in the past with apiserver metrics.
IIRC we noted in that discussion that summary metric is low on server-side cost compared to histograms when computing quantiles.
I'm also in favour of getting rid of the histogram ones - unless we have a good reason to keep them?

cc @kubernetes/sig-scheduling-misc @bsalamat
