### ISSUE TITLE
[Failing tests] : hpa-upgrade, ingress-upgrade failing in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63500]
## Failing Jobs
* [gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)
* [gce-1.10-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster)
* [gce-1.10-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new)
* [gke-gci-1.10-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-master)

## Gubernator Logs from recent runs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3339

## Triage results
* [hpa-upgrade](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel&test=hpa-upgrade)
* [ingress-upgrade](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel&test=ingress-upgrade)

This test is currently failing in sig-release master-upgrade suite. This could potentially block Beta cut which is on 5/15. 

@timothysc and @MrHohn can you please triage these failures and see if it belongs to cluster-lifecycle or networking?

/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
/sig network
@kubernetes/sig-cluster-lifecycle-bugs
@kubernetes/sig-network-bugs 

cc @jberkus @tpepper

/assign @timothysc @MrHohn 
/milestone v1.11

**Comment by timothysc** [comment]
PR's in flight on upgrade tests -

https://github.com/kubernetes/kubernetes/pull/63596 
https://github.com/kubernetes/kubernetes/pull/63595 

closing this issue, please reopen is issue persists 24 hours from this comment. 
/cc @dims
