### ISSUE TITLE
SkewTest failing gce-1.10-master-upgrade-cluster-new job in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63506]
## Failing Job
[gce-1.10-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new)

## Gubernator logs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1422

## Triage 
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new&test=SkewTest

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone v1.11
@kubernetes/sig-testing-bugs

cc @jberkus @tpepper

/assign @BenTheElder for triage

**Comment by BenTheElder** [comment]
I don't think this is sig-testing. Looks like `[sig-cluster-lifecycle]` , `[sig-autoscaling]`, `[sig-storage]`

/unassign
/remove-sig testing

**Comment by AishSundar** [comment]
/sig cluster-lifecycle
/assign @timothysc 

@timothysc can you see if this is a cluster lifecycle issue please?

**Comment by krousey** [comment]
Chiming in for cluster-lifecycle, this is weird. Somehow the nodes are being put back into a cordoned state after the upgrade. The upgrade checks that after a node is upgraded, it becomes both ready and schedulable. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh#L347-L360

Here's an example from the linked failure:

```console
I0505 21:53:28.217] == Recreating instance bootstrap-e2e-minion-group-srfd. ==
I0505 21:53:29.848] == Waiting for new node to be added to k8s.  ==
I0505 21:55:56.502] ..............................................................................................................................== Waiting for bootstrap-e2e-minion-group-srfd to become ready. ==
I0505 21:55:56.502] Node bootstrap-e2e-minion-group-srfd recreated.
I0505 21:55:56.789] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:55:58.067] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:55:59.371] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:56:00.670] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:56:01.964] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:56:03.272] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:56:04.582] Node bootstrap-e2e-minion-group-srfd is still not ready: Ready=False
I0505 21:56:05.886] Node bootstrap-e2e-minion-group-srfd Ready=True
```

But just a few lines below that, we can see the the cluster validation after the upgrade shows that 2 nodes are still unschedulable. 

```console
I0505 21:56:13.446] == Finished upgrading nodes to v1.11.0-alpha.2.110+8fcaa19dd06f19. ==
I0505 21:56:13.447] == Validating cluster post-upgrade ==
I0505 21:56:13.489] Validating gce cluster, MULTIZONE=
I0505 21:56:13.490] Project: k8s-jkns-gce-slow-1-4
I0505 21:56:13.490] Network Project: k8s-jkns-gce-slow-1-4
I0505 21:56:13.490] Zone: us-central1-f
I0505 21:56:14.846] Found 4 node(s).
I0505 21:56:15.005] NAME                              STATUS                     ROLES     AGE       VERSION
I0505 21:56:15.006] bootstrap-e2e-master              Ready,SchedulingDisabled   <none>    27m       v1.11.0-alpha.2.110+8fcaa19dd06f19
I0505 21:56:15.006] bootstrap-e2e-minion-group-l1rn   Ready                      <none>    8m        v1.11.0-alpha.2.110+8fcaa19dd06f19
I0505 21:56:15.006] bootstrap-e2e-minion-group-ls61   Ready,SchedulingDisabled   <none>    27m       v1.11.0-alpha.2.110+8fcaa19dd06f19
I0505 21:56:15.006] bootstrap-e2e-minion-group-srfd   Ready,SchedulingDisabled   <none>    26m       v1.11.0-alpha.2.110+8fcaa19dd06f19
I0505 21:56:15.168] Validate output:
I0505 21:56:15.314] NAME                 STATUS    MESSAGE              ERROR
I0505 21:56:15.314] etcd-1               Healthy   {"health": "true"}   
I0505 21:56:15.314] etcd-0               Healthy   {"health": "true"}   
I0505 21:56:15.314] scheduler            Healthy   ok                   
I0505 21:56:15.314] controller-manager   Healthy   ok                   
I0505 21:56:15.316] Cluster validation succeeded
I0505 21:56:15.317] == Post-Upgrade Node OS and Kubelet Versions ==
I0505 21:56:15.487] name: "bootstrap-e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.11.0-alpha.2.110+8fcaa19dd06f19"
I0505 21:56:15.487] name: "bootstrap-e2e-minion-group-l1rn", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.11.0-alpha.2.110+8fcaa19dd06f19"
I0505 21:56:15.488] name: "bootstrap-e2e-minion-group-ls61", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.11.0-alpha.2.110+8fcaa19dd06f19"
I0505 21:56:15.488] name: "bootstrap-e2e-minion-group-srfd", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.11.0-alpha.2.110+8fcaa19dd06f19"
I0505 21:56:15.493] May  5 21:56:15.492: INFO: Waiting up to 5m0s for all nodes to be ready after the upgrade
I0505 21:56:15.499] May  5 21:56:15.499: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:56:35.503] May  5 21:56:35.503: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:56:55.507] May  5 21:56:55.507: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:57:15.511] May  5 21:57:15.511: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:57:35.516] May  5 21:57:35.516: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:57:55.520] May  5 21:57:55.520: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:58:15.524] May  5 21:58:15.524: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:58:35.529] May  5 21:58:35.529: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:58:55.533] May  5 21:58:55.533: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:59:15.538] May  5 21:59:15.538: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:59:35.542] May  5 21:59:35.542: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 21:59:55.547] May  5 21:59:55.547: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 22:00:15.551] May  5 22:00:15.551: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 22:00:35.556] May  5 22:00:35.555: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 22:00:55.560] May  5 22:00:55.560: INFO: Waiting for ready nodes 3, current ready 1, not ready nodes 0
I0505 22:01:15.563] May  5 22:01:15.561: INFO: Unexpected error occurred: timeout waiting 5m0s for number of ready nodes to be 3
```

Does someone from the node team know why this might be happening? Is it a race condition? It worked for one node, but not two in this case. In other runs, I see it working for two nodes and only leaving one unschedulable.

cc @kubernetes/sig-node-bugs

**Comment by AishSundar** [comment]
cc @dchen1107 @derekwaynecarr

**Comment by jiayingz** [comment]
/cc @jiayingz @Random-Liu 

I am also running into this issue when trying to add a new upgrade test. First, I think the reason that the test log said the node was ready is because the code is looking at a wrong field for SchedulingDisabled. The unschedulable field is a field in node.spec not a node status condition, so I think we should instead use:
local cordoned=$("${KUBE_ROOT}/cluster/kubectl.sh" get node "${instance}" --output='jsonpath=="{.spec.unschedulable}"'

I am also puzzled on why recreating instance just rebooted the node. According to 'gcloud instance-groups managed recreate-instances' doc, that command should delete the instance first and create a new one. For the passed cluster upgrade test, that seems the case, but for the failed ones, I saw node was just rebooted and so still got the old unschedulable state from the API server.

While trying to figure out why recreating instance just rebooted node sometimes, would it make sense we explicitly use 'gcloud instance-groups managed delete-instances' and  'gcloud instance-groups managed create-instances' ?

**Comment by dchen1107** [comment]
I think @krousey's theory at :https://github.com/kubernetes/kubernetes/issues/63506#issuecomment-387802096 is right. After #60692 was merged, .spec.externalID is mapping to spec.instanceID which wouldn't be unique after recreate. In this case, Kubelet won't delete old node object and recreate new one. I think this is what we want: we want to stop the node to delete and create itself, we want to stop the node to mess up its taints and labels. Instead, we want the controller(s) to explicitly set the taints and labels to a node. 

@krousey also updated upgrade script to use boot id to detect the new boot or recreation: https://github.com/kubernetes/kubernetes/pull/62922

In this very case, we should update upgrade script to explicitly clear the unschedulable field once new boot id was detected.

**Comment by krousey** [comment]
@dchen1107 Thanks, I'll work on a PR and send it out today.

**Comment by jiayingz** [comment]
From my manual run, I ssh-ed into the unschedulable node after the test and saw the kubelet log contains multiple restarts and logged the event that the node was previously registered and then later changed to NodeNotSchedulable based on the spec got from the API server:

1754: May 08 18:03:18 e2e-test-jiayingz-minion-group-ssbv kubelet[1073]: I0508 18:03:18.587210    1073 kubelet_node_status.go:126] Node e2e-test-jiayingz-minion-group-ssbv was previously registered
1755: May 08 18:03:18 e2e-test-jiayingz-minion-group-ssbv kubelet[1073]: I0508 18:03:18.587238    1073 kubelet_node_status.go:85] Successfully registered node e2e-test-jiayingz-minion-group-ssbv
...
1789: May 08 18:03:18 e2e-test-jiayingz-minion-group-ssbv kubelet[1073]: I0508 18:03:18.602719    1073 server.go:442] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"e2e-test-jiayingz-minion-group-ssbv", UID:"e2e-test-jiayingz-minion-group-ssbv", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotSchedulable' Node e2e-test-jiayingz-minion-group-ssbv status is now: NodeNotSchedulable

**Comment by krousey** [comment]
@jiayingz That fits with the current theory. The instance is being recreated, but the kubelet is no longer re-registering itself since the externalID is the same.

**Comment by krousey** [comment]
Note that this bug is flaky. It doesn't happen 100% of the time. Looks like we got 100% pass in the latest run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1431

Here's an upgrade test that's hitting this flake: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3384

**Comment by jingxu97** [comment]
@dchen1107 @jiayingz 
cc @mikedanese 
Please see my comments at for the change https://github.com/kubernetes/kubernetes/pull/61877/files#diff-6b0808bd1afb15f9f77986f4459601c2L147
https://github.com/kubernetes/kubernetes/pull/61877#commitcomment-28935670
Before the change, when instance is recreated, kubelet will delete the node object and a new one will be created. Now, kubelet will not delete the old one if the node name is the same, I think. This might give some trouble for volumes because the old node will contain the outdated volumesAreAttached information. But we do sync up with the cloud provider and update this information eventually. I am not sure whether this old object might cause other problems or not.

**Comment by AishSundar** [comment]
@krousey I see the test failing in the last few runs. Is it a different issue plaguing the test now?

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new

**Comment by AishSundar** [comment]
Here are the [Commit changes](https://github.com/kubernetes/kubernetes/compare/444881d0d...c29aa3d25) since the last failure.

**Comment by AishSundar** [comment]
Spoke to @krousey offline and SkewTest is a overall for the second half of the suite. So if the other tests in the job pass, this one should turn the corner. so closing this bug for now.
