### ISSUE TITLE
[Failing Tests] : BeforeSuite,Up and Upgrade tests failing on multiple Downgrade cluster jobs in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63505]
## Failing Jobs
* [gce-master-1.10-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.10-downgrade-cluster)
* [gce-master-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.10-downgrade-cluster-parallel)
* [gke-gci-master-gci-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel)

## Gubernator Logs from recent runs
* [ci-kubernetes-e2e-gce-master-new-downgrade-cluster](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/598)
* [ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/2642)
* [ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/2828)

This test is currently failing in sig-release master-upgrade suite. This could potentially block Beta cut which is on 5/15.  @BenTheElder you please triage this issue and assign to the rightful owner.

/kind bug
/priority failing-test
/priority important-soon
/sig testing
/milestone v1.11
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper @timothysc 

/assign @BenTheElder

**Comment by BenTheElder** [comment]
Looks like the downgrades are not successful. cluster-lifecycle owns these `[sig-cluster-lifecycle] cluster-downgrade`

/sig cluster-lifecycle
/assign @timothysc 
/remove-sig testing
/unassign

**Comment by timothysc** [comment]
/assign @roberthbailey 

re: downgrades, that's a google-ism.

**Comment by krousey** [comment]
/assign @krousey

The nodes aren't downgrading properly. I will either look into this or find someone to do it.

**Comment by krousey** [comment]
I was able to reproduce this locally. After a node is downgraded, the kubelet tried to delete the old Node API object, but it cannot.

```
May 10 21:54:05 kubernetes-minion-group-1c1x kubelet[1300]: I0510 21:54:05.990928    1300 kubelet_node_status.go:82] Attempting to register node kubernetes-minion-group-1c1x
May 10 21:54:05 kubernetes-minion-group-1c1x kubelet[1300]: E0510 21:54:05.997440    1300 kubelet_node_status.go:144] Previously node "kubernetes-minion-group-1c1x" had externalID "5476657464438489132"; now it is ""; will delete and recreate.
May 10 21:54:05 kubernetes-minion-group-1c1x kubelet[1300]: E0510 21:54:05.999424    1300 kubelet_node_status.go:148] Unable to register node "kubernetes-minion-group-1c1x" with API server: error deleting old node: nodes "kubernetes-minion-group-1c1x" is forbidden: User "system:node:kubernetes-minion-group-1c1x" cannot delete nodes at the cluster scope
```

Maybe something has changed with the cluster role binding logic?

**Comment by krousey** [comment]
cc @kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
> After a node is downgraded, the kubelet tried to delete the old Node API object, but it cannot.

cc @mikedanese

**Comment by krousey** [comment]
I think this change broke it: https://github.com/kubernetes/kubernetes/pull/62818

**Comment by krousey** [comment]
/assign @mikedanese 

Give that 1.10 nodes still issue deletes for this, I don't think we can remove that permission until 1.13 since we allow the node to lag the master by 2 minor releases.

**Comment by liggitt** [comment]
The analysis was that the external ID changes that triggered deletion did not occur any more (and had not since early 1.x releases)

**Comment by krousey** [comment]
@liggitt I can say a bit about this for GCE. In 1.10 and prior, `ExternalID` was tied to the actual gcloud compute instance ID. And this did change on node upgrades (`gcloud compute instance-groups managed recreate-instances` would cause this value to change). https://github.com/kubernetes/kubernetes/pull/60692 changed it so that `ExternalID` is now the VM name and not it's ID. So for 1.11 and on, it won't change. That led to this fix that I've already made for 1.10 to 1.11 upgrades: https://github.com/kubernetes/kubernetes/pull/62922

But now we're going in the reverse direction, the `ExternalID` will be different, and it will trigger the branch of code in a 1.10 kubelet that will try to delete the node.

**Comment by liggitt** [comment]
opened revert in https://github.com/kubernetes/kubernetes/pull/63712

**Comment by mikedanese** [comment]
Sorry about that. I tested this against a MIG rolling update, which I guess we haven't used for GCE upgrades in a while.

**Comment by krousey** [comment]
This suite is passing now. I think we can close it.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/2684
