### ISSUE TITLE
Kubeadm doesn't give an intermediate version option

### ISSUE THREAD

**Issue by nelsonfassis** [kubernetes/kubernetes#63513]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Trying to upgrade from Kubernetes 1.8.x to 1.9.x according to documentation, however, it only gives me the option to upgrade to the latest 1.8.12 or 1.10.2, skipping 1.9.x completely. 
**What you expected to happen**:
To be given the option for v1.9

**How to reproduce it (as minimally and precisely as possible)**:
1 - Have a working Kubernetes 1.8.x cluster
2 - Start the upgrade procedure, export VERSION=v1.9.7 and export ARCH=amd64
3 - Download desired Kubeadm version 
```  curl -sSL https://dl.k8s.io/release/${VERSION}/bin/linux/${ARCH}/kubeadm > /usr/bin/kubeadm ```
4 - Grant permissions to the new kubeadm 
``` chmod a+rx /usr/bin/kubeadm ```
5 - Check upgrade options:
``` kubeadm upgrade plan ```
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.8.4
[upgrade/versions] kubeadm version: v1.9.7
[upgrade/versions] Latest stable version: v1.10.2
[upgrade/versions] Latest version in the v1.8 series: v1.8.12

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT      AVAILABLE
Kubelet     8 x v1.8.6   v1.8.12

Upgrade to the latest version in the v1.8 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.8.4    v1.8.12
Controller Manager   v1.8.4    v1.8.12
Scheduler            v1.8.4    v1.8.12
Kube Proxy           v1.8.4    v1.8.12
Kube DNS             1.14.5    1.14.5
Etcd                 3.0.17    3.0.17

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.8.12

_____________________________________________________________________

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT      AVAILABLE
Kubelet     8 x v1.8.6   v1.10.2

Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.8.4    v1.10.2
Controller Manager   v1.8.4    v1.10.2
Scheduler            v1.8.4    v1.10.2
Kube Proxy           v1.8.4    v1.10.2
Kube DNS             1.14.5    1.14.7
Etcd                 3.0.17    3.1.11

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.10.2

Note: Before you can perform this upgrade, you have to update kubeadm to v1.10.2.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Described above
- Cloud provider or hardware configuration: On-premise cluster, 
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nelsonfassis** [comment]
I tried running kubeadm upgrade apply 1.9.7 and it failed.
Running ``` kubeadm upgrade apply v1.9.7 ``` worked. It failed a bunch of times due to timeout, couldn't find a flag to increase timeout but after several tries, it eventually worked. 
Not optimal but so far, seems to work.

Feel free to close this bug, but not showing the version of my kubeadm for upgrade, seems like a bug that should be fixed.

**Comment by dims** [comment]
@nelsonfassis can you please move this to https://github.com/kubernetes/kubeadm/issues/ ?

/close
