### ISSUE TITLE
Pod Lifetime 

### ISSUE THREAD

**Issue by subbu05** [kubernetes/kubernetes#63523]
Hi,

**Feature Request**
Due to several reasons we want to re-create Pods. In K8S POD life cycle there is no option for settings POD lifetime. Example: if POD is running with some certificate whose expiry is x days. We want to have an option K8S automatically delete POD after x days running and re-create new POD.

**Comment by subbu05** [comment]
Example: Pod.json (POD will be created automatically after 2days, old PODs will be deleted).
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "demo"
  },
  "spec": {
    "containers": [
      {
        "name": "demo",
        "lifetime": 2d,
        "image": "demoimage",
        "ports": [
          {
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ]
      }

**Comment by wgliang** [comment]
/kind feature
/sig node

If it is feasible, I can write this proposal.

**Comment by wgliang** [comment]
Can you enumerate the usage scenarios of this feature?

**Comment by liggitt** [comment]
doesn't the spec.activeDeadlineSeconds meet this requirement?

**Comment by spearsem** [comment]
Is this feature still being considered? I also have an open use case that would benefit from this.

**Comment by GabrielLasso** [comment]
Is this feasible in 1.18? I have some Deployments that would benefit from this (now I have a cronjob that restart the deployments)
