### ISSUE TITLE
kubelet 1.10.2 ignores --cni-bin-dir parameter

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#63542]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I am trying to use a custom directory for cni plugins, but kubelet ignores --cni-bin-dir parameter and tries to find plugins in the default one.

`FailedCreatePodSandBox  2s    kubelet, test-stg-k8s-master-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3e98cec42d687001e6718b8291c19e8fef37ec8b0c5a8fb0abe5e39e32f1c885": failed to find plugin "loopback" in path [/opt/cni/bin]`

**What you expected to happen**:
Kubelet finds plugins in the custom directory
**How to reproduce it (as minimally and precisely as possible)**:
--cni-bin-dir=/opt/bin

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
/sig network

**Comment by dixudx** [comment]
@IvanovOleg I did not reproduce this.

What's your exact running params for kubelet? Please make sure your params are not override by some drop-ins if you are using `systemd`.

**Comment by IvanovOleg** [comment]
@dixudx 
kubelet.service:

```
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://kubernetes.io/docs/concepts/overview/components/#kubelet https://kubernetes.io/docs/reference/generated/kubelet/
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory={{ kubelet_directory }}
EnvironmentFile=-/etc/default/config
EnvironmentFile=-/etc/default/kubelet
ExecStart=/opt/bin/kubelet \
  $KUBE_LOGTOSTDERR \
  $KUBE_LOG_LEVEL \
  $KUBELET_API_SERVER \
  $KUBELET_ADDRESS \
  $KUBELET_PORT \
  $KUBELET_HOSTNAME \
  $KUBE_ALLOW_PRIV \
  $KUBELET_ARGS
Restart=on-failure
KillMode=process

[Install]
WantedBy=multi-user.target
```
config:
```
###
# kubernetes system config
#
# The following values are used to configure various aspects of all
# kubernetes services, including
#
#   kube-apiserver.service
#   kube-controller-manager.service
#   kube-scheduler.service
#   kubelet.service
#   kube-proxy.service
# logging to stderr means we get it in the systemd journal
KUBE_LOGTOSTDERR="--logtostderr=true"

# journal message level, 0 is debug
KUBE_LOG_LEVEL="--v=0"

# Should this cluster be allowed to run privileged docker containers
KUBE_ALLOW_PRIV=""

# How the controller-manager, scheduler, and proxy find the apiserver
KUBE_MASTER="--master=https://{{ k8s_master }}:{{ kube_apiserver_port }}
```
kubelet:
```
###
# kubernetes kubelet (minion) config

# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS=""

# The port for the info server to serve on
# KUBELET_PORT="--port=10250"

# You may leave this blank to use the actual hostname
KUBELET_HOSTNAME=""

# Add your own!
KUBELET_ARGS="--cloud-provider=azure --cloud-config={{ kubernetes_directory }}/azure.json --container-runtime=remote --container-runtime-endpoint=unix:///run/docker/libcontainerd/docker-containerd.sock --image-pull-progress-deadline=2m --kubeconfig={{ kubelet_directory }}/{{ inventory_hostname }}.kubeconfig --network-plugin=cni --cni-bin-dir=/opt/bin --volume-plugin-dir={{ kubernetes_directory }}/volume-plugins --cluster-dns=10.240.0.10"
```

**Comment by dixudx** [comment]
> --container-runtime=remote

@IvanovOleg For those docker-specific flags, like `--cni-bin-dir`,  only work when container-runtime is set to docker. However you're using `remote` container runtime. That's why it does not work as you expected.

We've added warnings for this in #62982.

**Comment by IvanovOleg** [comment]
@dixudx 
I use the pre-installed containerd runtime in the CoreOS as a remote runtime. It looks like I have to change this parameter somewhere in the containerd configuration. How can I let kubelet know about this directory?

**Comment by dixudx** [comment]
@IvanovOleg For `containerd`, you can override it in [/etc/containerd/config.toml](https://github.com/containerd/cri/blob/master/docs/config.md).

```
# "plugins.cri.cni" contains config related to cni
[plugins.cri.cni]
  # bin_dir is the directory in which the binaries for the plugin is kept.
  bin_dir = "/opt/cni/bin"
```

**Comment by dims** [comment]
we do have warning in the `kubelet --help`
```
      --cni-bin-dir string                                                                                        <Warning: Alpha feature> A comma-separated list of full paths of directories in which to search for CNI plugin binaries. Default: /opt/cni/bin. This docker-specific flag only works when container-runtime is set to docker.
      --cni-conf-dir string                                                                                       <Warning: Alpha feature> The full path of the directory in which to search for CNI config files. Default: /etc/cni/net.d. This docker-specific flag only works when container-runtime is set to docker.
```

**Comment by IvanovOleg** [comment]
@dixudx  Thanks a lot!
