### ISSUE TITLE
[Failing Test] Node-E2E: Validate Node Allocatable set's up the node and runs the test

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#63549]
/kind failing-test
/sig node
[testgrid history](https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e&include-filter-by-regex=Validate%20Node%20Allocatable%20set's%20up%20the%20node%20and%20runs%20the%20test),  [commit diff](https://github.com/kubernetes/kubernetes/compare/398ced1dc...592c39bcc), [example failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/4190)
Failure:
```
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_container_manager_test.go:60
Test Panicked
/usr/local/go/src/runtime/panic.go:502
```

https://github.com/kubernetes/kubernetes/pull/62541 is the likely culprit.
/assign @filbranden 
cc @Random-Liu @yujuhong @derekwaynecarr

**Comment by filbranden** [comment]
I'll take a look... Thanks!
