### ISSUE TITLE
Make NodePort allocation optional for Service.Type == LoadBalancer

### ISSUE THREAD

**Issue by bowei** [kubernetes/kubernetes#63552]
/kind feature

Add an option to the `Service` configuration to avoid allocating NodePorts for `Service.Type: LoadBalancer`.

It is part of the Kubernetes API definition that creating an external load balancer in Kubernetes implies allocation of a nodeport for the service. This is unnecessary for some clouds and uses up the nodeport range.

**Comment by dohnto** [comment]
This would be beneficial.

What is the motivation for every Service of type `LoadBalancer` have `NodePort` anyway?

**Comment by thockin** [comment]
move discussion to https://github.com/kubernetes/kubernetes/issues/69845
