### ISSUE TITLE
Create dry-run query parameter on CREATE/UPDATE/PATCH/DELETE handlers

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#63559]
Discussed this morning as part of the wg-apply with @liggitt @lavalamp @seans3 

Since we're planning on adding a dry-run mechanism to apply, we would like to have that mechanism in place as early as possible in the server (even if just rejecting with an error), so that future clients don't get their dry-run requests accepted and performed while running against older servers.

I'm suggesting that we add a "dry-run" query parameter whose content wouldn't matter on each modifying end-points (create, update, patch, delete).

Like the following ```end/points?dry-run```. The value of dry-run will be ignored, so `dry-run=false` would still apply the dry-run (I think it's safer to consider requests as dry-run proactively).

I've started a pull-request to implement this behavior (#63557)

@kubernetes/sig-api-machinery-api-reviews

**Comment by lavalamp** [comment]
It's a little weird that dry-run=false would trigger dry-run behavior.

**Comment by liggitt** [comment]
> It's a little weird that dry-run=false would trigger dry-run behavior.

Agree. I'd expect behavior consistent with other booleans like the watch param

**Comment by apelisse** [comment]
> Agree. I'd expect behavior consistent with other booleans like the watch param

That's a great point, I'll look at this pattern.

**Comment by lavalamp** [comment]
I'm not sure how to make this work for aggregated apiservers. We could make the aggregator do this check, but then we'd need to provide (in the future) some way for the aggregator to understand whether the downstream apiservers support it. Also, this would be the first such thing checked by the aggregator, which is a little odd. This is a case where #51830 might help us out, depending on how it was done.

@mbohlool do query parameters show up in OpenAPI? Maybe we can examine them to decide.

**Comment by lavalamp** [comment]
@deads2k How hard will it be to convince you that it makes sense for the
aggregator to interpret this query parameter?

**Comment by apelisse** [comment]
I think we can call this done. Closing.
