### ISSUE TITLE
AWS cloudprovider: MTU discovery security group rule cannot be scoped. Hardcoded to 0.0.0.0/0

### ISSUE THREAD

**Issue by haz-mat** [kubernetes/kubernetes#63564]
/kind feature

**What happened**:
When an ELB is provisioned as a LoadBalancer, the client traffic's security group rule can be scoped to specific ranges but the MTU discovery rule cannot.

**What you expected to happen**:
The MTU discovery security group rule source range is configurable or matches the values of `spec.loadBalancerSourceRanges`

**Anything else we need to know?**:
The `0.0.0.0/0` value appears to be [hardcoded here](https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/cloudprovider/providers/aws/aws.go#L3530).

I operate in an environment where `0.0.0.0/0` as a source range is generally disallowed.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.1
- Cloud provider or hardware configuration: AWS
- Others: ELB, not using ALB in this case

**Comment by frank-bee** [comment]
is there any plans to fix this issue in the near future?

**Comment by haz-mat** [comment]
@frank-bee yep, PR being worked on over here https://github.com/kubernetes/kubernetes/pull/63572

**Comment by newalp** [comment]
I can see the fixed merged in to Kubernetes 1.12
