### ISSUE TITLE
How to parse yaml files

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/kubernetes#63568]
**What happened**:
When I configure a k8s object, such as ingres, I can only look at the sample of ingress through some documentation, and then refer to the sample to configure the yaml file.

**What you expected to happen**:
I want to know where the K8s parse the yaml file. By looking at the parse code, I know what the parameters of each k8s version of the supported ingress object are, and what capabilities are supported

**Environment**:
- Kubernetes version (use `kubectl version`):1.8.2
- OS (e.g. from /etc/os-release):centos7.4

**Comment by liggitt** [comment]
the kubernetes API types are parsed into structs defined in https://github.com/kubernetes/api

YAML is converted to JSON and then parsed into structs.

For example, the Ingress structs are defined here:
https://github.com/kubernetes/api/blob/b7d77fa220f5130ec63c2ca7167dd9653449c64d/extensions/v1beta1/types.go#L564-L584

**Comment by liggitt** [comment]
You can also see the API documentation at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#ingress-v1beta1-extensions

/close

**Comment by shigy123456** [comment]
ok，thanks，I get it.
