### ISSUE TITLE
iperf3 couldn't work with iptables mode tcp service

### ISSUE THREAD

**Issue by MIBc** [kubernetes/kubernetes#63567]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a tcp service with 3 iperf-server members. A iperf-client pod connected the cluster ip. The connection could established but there were no data output on stout and the process hang.

**What you expected to happen**:
The iperf stream can communicate using iptables mode service.
**How to reproduce it (as minimally and precisely as possible)**:
(1) create iperf-server deployment
```
# cat iperf-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  labels:
    deployment: iperf-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: iperf-server
  template:
    metadata:
      labels:
        run: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: networkstatic/iperf3
        command:
            - sleep
            - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
# kubectl create -f iperf-server.yaml
```
(2)cerate iperf-client using the similar yaml file 
(3)create a service
```
# kubectl expose deployment iperf-server --port=11111 --target-port=5201
```
(4) execute iperf command in server in every server pod:
```
# kubectl exec -it iperf-server-xxxxxxx -- iperf3 -s
```
(5)execute iperf command in client pod:
```
# kubectl exec -it iperf-client-xxxxxxx -- iperf3 -c cluster-ip -p 11111
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3
- Cloud provider or hardware configuration: vm in vcenter
- OS (e.g. from /etc/os-release): centos 7.1
- Kernel (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- Install tools: none
- Others: none

**Comment by thockin** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by MIBc** [comment]
Iperf creates two tcp connections when run tcp case. May be it is not a suitable way to use k8s iptables mode service.

**Comment by thockin** [comment]
Should be fine if they are the same port or both ports are in the Service.
