### ISSUE TITLE
Unit kubelet.service entered failed state - Setup on RHEL 7 -  area/kubelet 

### ISSUE THREAD

**Issue by raman36127** [kubernetes/kubernetes#63571]
[root@k8-master-node tmp]# systemctl start kubelet

May  9 05:10:28 k8-master-node systemd: kubelet.service holdoff time over, scheduling restart.
May  9 05:10:28 k8-master-node systemd: Started kubelet: The Kubernetes Node Agent.
May  9 05:10:28 k8-master-node systemd: Starting kubelet: The Kubernetes Node Agent...
May  9 05:10:28 k8-master-node kubelet: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: Flag --allow-privileged has been deprecated, will be removed in a future version
May  9 05:10:28 k8-master-node kubelet: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the            -config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by t           s --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified            let's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by t           s --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadviso            be removed entirely in 1.13
May  9 05:10:28 k8-master-node kubelet: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by th            --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May  9 05:10:28 k8-master-node kubelet: I0509 05:10:28.513398    1641 feature_gate.go:226] feature gates: &{{} map[]}
May  9 05:10:28 k8-master-node kubelet: F0509 05:10:28.513507    1641 server.go:218] unable to load client CA file /etc/kubernetes/pki/ca.crt: ope           rnetes/pki/ca.crt: no such file or directory
May  9 05:10:28 k8-master-node systemd: kubelet.service: main process exited, code=exited, status=255/n/a
May  9 05:10:28 k8-master-node systemd: Unit kubelet.service entered failed state.
May  9 05:10:28 k8-master-node systemd: kubelet.service failed.

**Trying to Setup on RHEL 7** 

[root@k8-master-node ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

[root@k8-master-node ~]# uname -a
Linux k8-master-node 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Steps which i used.** 

1)Firewall off

2)Selinux disable

3)Create repo for pkg installation.
[root@k8-master-node yum.repos.d]# cat kubernetes.repo
[kubernetes]
name=Kubernetes
sslverify=0
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

4) [root@k8-master-node yum.repos.d]# export http_proxy=http://myofficeproxy:8080
[root@k8-master-node yum.repos.d]# export https_proxy=http://myofficeproxy:8080

5)[root@k8-master-node yum.repos.d]# yum install kubeadm docker

Installed:
  docker.x86_64 2:1.13.1-53.git774336d.el7

Dependency Installed:
  PyYAML.x86_64 0:3.10-11.el7                                              atomic-registries.x86_64 1:1.22.1-1.gitd36c015.el7
  container-selinux.noarch 2:2.42-1.gitad8f0f7.el7                         container-storage-setup.noarch 0:0.8.0-3.git1d27ecf.el7
  docker-client.x86_64 2:1.13.1-53.git774336d.el7                          docker-common.x86_64 2:1.13.1-53.git774336d.el7
  docker-rhel-push-plugin.x86_64 2:1.13.1-53.git774336d.el7                oci-register-machine.x86_64 1:0-6.git2b44233.el7
  oci-systemd-hook.x86_64 1:0.1.15-2.gitc04483d.el7                        oci-umount.x86_64 2:2.3.3-3.gite3c9055.el7
  python-pytoml.noarch 0:0.1.14-1.git7dea353.el7                           skopeo-containers.x86_64 1:0.1.28-1.git0270e56.el7

Complete!

6)[root@k8-master-node yum.repos.d]# yum install kubeadm -y

Installed:
  kubeadm.x86_64 0:1.10.2-0

Dependency Installed:
  kubectl.x86_64 0:1.10.2-0           kubelet.x86_64 0:1.10.2-0           kubernetes-cni.x86_64 0:0.6.0-0           socat.x86_64 0:1.7.3.2-2.el7

Complete!

7) Enable Service at boot. 
[root@k8-master-node tmp]# systemctl enable docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
[root@k8-master-node tmp]# systemctl enable kubelet
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /etc/systemd/system/kubelet.service.

8) Start Service 

[root@k8-master-node tmp]# systemctl start docker
[root@k8-master-node tmp]# systemctl start kubelet

9) [root@k8-master-node tmp]# vim /etc/sysctl.d/k8s.conf
[root@k8-master-node tmp]# cat /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

[root@k8-master-node tmp]# sysctl --system

10) Docker Service up but kubelet failed.

[root@k8-master-node tmp]# systemctl start kubelet

**Comment by vfreex** [comment]
Note this line of error message:
```
May 9 05:10:28 k8-master-node kubelet: F0509 05:10:28.513507 1641 server.go:218] unable to load client CA file /etc/kubernetes/pki/ca.crt: ope rnetes/pki/ca.crt: no such file or directory
```
You must prepare the required CA file for starting kubelet.
Please following a guide to set up kubernetes.

**Comment by raman36127** [comment]
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/    
Work for me. 
Thanks
