### ISSUE TITLE
vSphere cloud provider did not detach volume when shutdown node

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#63577]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

1. Set up Kubernetes v1.10 cluster with vsphere cloud provider enabled.
2. Create a deployment nginx using some vsphere persistent volume.
3. Shutdown node where nginx pod is running. The nginx pod will be scheduled to another ready node.
4. Try to start above node was shutting off. The node cannot be started because attached vmdk volume.
5. After manually removed the vmdk volume from the node, the node can be started.

**What you expected to happen**:

After node was shut down, vsphere volume plugin should be able to detach volume from the node when pod was removed.

**How to reproduce it (as minimally and precisely as possible)**:

See above steps.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

**Comment by w-leads** [comment]
Hi, I've faced the same kind of issue, and raised a pull request which is under review phase now.
I'm not sure if this is exactly the same as your case, also if this pr will be merged though... but just let me share it here.
#63413 
Thank you
