### ISSUE TITLE
Limit the range of token expiration

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#63575]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind feature

A new API TokenRequest has been implemented.It improves current serviceaccount model from many ways.https://github.com/kubernetes/kubernetes/issues/58790
I think we need some kind measure to limit the range of token expiration.
Try to imagine two cases:
1. User requests a token with extreme short-expiration, say 1s. Then token rotation will be triggered every second which is unacceptable
2. User requests a token with extreme long-expiration, say 100 years. It is almost  permanent．

So I think we need some kind of mechanism to limit the range of token expiration time.
From my point of view,  I can think tow ways to implement.
1. Add a option to api-server, it controls the range of all token request through the cluster.
2. Add an attribute to serviceaccount object, it controls only its own token request.

**Comment by WanLinghao** [comment]
@liggitt @mikedanese WDYT

**Comment by mikedanese** [comment]
👍 I'd like a lower bound of 10 minutes. I'd also like an upper bound to be configurable from the command line. The upper bound interacts with signing key rotation. For instance a key should not sign a token to expiry after the key is no longer valid.

**Comment by WanLinghao** [comment]
So only upper bound is configurable by user, and lower bound tend to be a fix value?
> I'd like a lower bound of 10 minutes. I'd also like an upper bound to be configurable from the command line.

**Comment by WanLinghao** [comment]
@mikedanese 
Take a example to make sure if I got what you mean correctly.
Start a k8s cluster with  serviceaccout-signing-key KEY-1, and set its expiry time to be 30 days. 
After 20 days running, the KEY-1 would be invalid after 10 days. At this time, a user launches a TokenRequest with 15 days expiration time. Since the KEY-1 itself would become invalid after 10 days, so we shall not let this request through.

> The upper bound interacts with signing key rotation. For instance a key should not sign a token to expiry after the key is no longer valid.

**Comment by jqmichael** [comment]
`User requests a token with extreme long-expiration, say 100 years. It is almost permanent.`
Isn't kubelet refreshing the token at least every 24 hours?

https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/kubelet/token/token_manager.go#L143

**Comment by liggitt** [comment]
The user request is constrained by the upper bound set by the apiserver. If the cluster admins says 24 hours or 1 week is the max, no tokens longer than that will be issued. 

The kubelet refreshes at an interval that is a percentage of the issued token lifetime, not the requested lifetime.

**Comment by jqmichael** [comment]
Sorry for the confusion. 

What I meant was, before we introduce this change (cluster admin can set an upper bound of token lifetime), event if client requires a token with 100 years, kubelet will still refresh the token at least every 24 hours. So even though the token is still valid for another 100 years, it will be removed from the pod after 24 hours. 

I guess user can keep the token in another place and still use it to auth against the api server, and api server will happily accept it. I was just saying it won't happen from the pod directly.
