### ISSUE TITLE
staging: figure out vgo (versioned go) publishing strategy

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#63607]
We should really figure out our strategy for vgo: https://github.com/golang/go/issues/24301.

The most obviously disruptive changes are:
* We're supposed to have a e.g. v6 in the import path when the major digit of the library's semver is 6.
* We're supposed to increment that every time we break backwards compatibility.

In exchange for making the needed adjustments, we'll get to throw Godep/* in the trash.

Since the packages now will get "published" (put in a zip file and placed somewhere for consumption), we could make a really drastic change and keep the staging directory but get rid of the repos we publish to. I'm not recommending that, just trying to give a sense for the maximum amount of change this could lead to.

**Comment by sttts** [comment]
And there are nested go.mod files, i.e. staging like submodules. So we might even get rid of the ugly vendor/ -> staging symlinks.

**Comment by lavalamp** [comment]
Yes, apparently there's built in support for overrides, e.g. "get this module from this directory over here instead of pulling from the remote source", so we'll have a better way to do that.

**Comment by sdboyer** [comment]
Yeah, there are some cool possibilities here. The way that k8s handles staging has been front of mind for me while analyzing vgo; the staging/ structure used today can be handled pretty much straight up as-is with a `replace` statement - at least, i think, i haven't tried it. 

There are other issues k8s is likely to have with vgo, but this one gets easier.

**Comment by marwan-at-work** [comment]
I use k8s.io/client-go pretty frequently, and it's one of the many packages in the community that are tagged >=2 but obviously before Semantic Import Versioning was a thing.

So I'm just posting a [tool](https://github.com/marwan-at-work/mod)) that I wrote to help with this transition as a reference. Hopefully it will be of help once you figure out the strategy of using Go Modules with Kuberenetes as a whole. 

As an example you can look at this commit generated by running `mod -t=8 upgrade` inside of the client-go repo: https://github.com/marwan-at-work/client-go/commit/47880e79b47d26f3f4f9b619946d9e7b84787982

**Comment by sgnn7** [comment]
> Yes, apparently there's built in support for overrides, e.g. "get this module from this directory over here instead of pulling from the remote source", so we'll have a better way to do that.

Indeed! This isn't documented well upstream right now but there is `replace` `go.mod` directive I've been using to work with my current module-based code. Just to show what this looks like for code-gen where you're hacking on the underlying `gengo`:
```
module k8s.io/code-generator

require (
	<snip>
	k8s.io/gengo v0.0.0-20180702041517-fdcf9f9480fd
	<snip>
)

replace k8s.io/gengo => ../../../../../gengo
```

This directive remaps the source of the module named on the left side with the path on the right side which in this case is a sibling checkout of `kubernetes/gengo` on my local machine of `kubernetes/kubernetes` repo but you can obviously build the hierarchy in any way you want. This would be very useful in tying all the local `staging/src/k8s` dependencies together for tests.

**Comment by ixdy** [comment]
cc @sigma

**Comment by sigma** [comment]
I concur, the replace operator is a fairly straightforward way to handle our staging repositories. There are still rough edges around having a single `vendor/` directory to serve them all though. This is tracked in #68577 amongst other things

**Comment by liggitt** [comment]
addressed in https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md and https://github.com/kubernetes/kubernetes/pull/74877

/close
