### ISSUE TITLE
Failing Test : [sig-network] All Networking Granular Checks are failing in sig-release-master-blocking gci-gce-alpha-features job

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63611]
## Failing Job
[gci-gce-alpha-features](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-alpha-features)

## Gubernator Logs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/21594

## Error
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:203
May  9 15:57:39.163: Unexpected no endpoints return
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:213

## Triage
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-alpha-features&test=Networking%20Granular%20Checks

This test is currently failing in sig-release master-blocking suite. This could potentially block Beta cut for v1.11 slated for 5/15 . @dcbw or @caseydavenport  can either you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig network
@kubernetes/sig-network-bugs 
/assign @dcbw
cc @jberkus @tpepper 
/milestone v1.11

**Comment by mohammedzee1000** [comment]
cc @dcbw @thockin action required guys

**Comment by AishSundar** [comment]
The tests seem to be passing now. So will close the issue and re-open if needed
