### ISSUE TITLE
HPA not able to find CPU, looking at unrelated pod

### ISSUE THREAD

**Issue by rdzimmer** [kubernetes/kubernetes#63615]
**What happened**:
I created HPAs for several Deployments using the helm yaml below:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: {{template "fullname" . }}
  namespace: default
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: {{template "fullname" . }}
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 100
```
It works fine except for on my pod "metric" that has 3 containers in it.  All containers have kubernetes resource requests and limits for CPU and memory.  The problem is the HPA reports it cannot find the CPU usage.  
```
kubectl get -o json hpa release-metric
{
    "apiVersion": "autoscaling/v1",
    "kind": "HorizontalPodAutoscaler",
    "metadata": {
        "annotations": {
            "autoscaling.alpha.kubernetes.io/conditions": "[{\"type\":\"AbleToScale\",\"status\":\"True\",\"lastTransitionTime\":\"2018-05-09T15:17:51Z\",\"reason\":\"SucceededGetScale\",\"message\":\"the HPA controller was able to get the target's current scale\"},{\"type\":\"ScalingActive\",\"status\":\"False\",\"lastTransitionTime\":\"2018-05-09T15:17:51Z\",\"reason\":\"FailedGetResourceMetric\",\"message\":\"the HPA was unable to compute the replica count: missing request for cpu on container release-event in pod default/release-event-5486b6976c-q2btv\"}]"
        },
        "creationTimestamp": "2018-05-09T15:17:21Z",
        "name": "release-metric",
        "namespace": "default",
        "resourceVersion": "16249",
        "selfLink": "/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/release-metric",
        "uid": "11bee95f-539c-11e8-a15c-005056b43c41"
    },
    "spec": {
        "maxReplicas": 5,
        "minReplicas": 1,
        "scaleTargetRef": {
            "apiVersion": "extensions/v1beta1",
            "kind": "Deployment",
            "name": "release-metric"
        },
        "targetCPUUtilizationPercentage": 100
    },
    "status": {
        "currentReplicas": 1,
        "desiredReplicas": 0
    }
}
```
The odd thing is the "event" pod is completely unrelated to the "metric" pod.  In another environment, it's looking at another different pod "applications" that again has nothing to do with the Deployment "metric".  It seems to be getting confused on what pod to look for when there are multiple containers in the Deployment.  
I created another HPA against another pod with 2 containers, and again the HPA is looking for CPU for unrelated pods.  

**What you expected to happen**:
CPU is correctly monitored for the pod and horizontally scaled.  

**How to reproduce it (as minimally and precisely as possible)**:
Create a "deployment" HPA for a pod with 2 or more containers.  

**Anything else we need to know?**:
I tried creating an HPA against the ReplicaSet for my "metric" service and this works okay.  The problem is, I'm not sure how to get the "ReplicaSet" name into the helm yaml to replace `name: {{template "fullname" . }}` since in my helm charts it's turning into <release>-metric-<hash>.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.1+icp
- Cloud provider or hardware configuration: vmware
- OS (e.g. from /etc/os-release): rhel 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.21.1.el7.x86_64

/kind bug
/sig autoscaling
/sig scalability

**Comment by rdzimmer** [comment]
I've experimented with different apiVersions, but it hasn't made a difference.  For some reason the apiVersion got changed from the yaml to the actual definition.  I created it with `apps/v1` but it became `extensions/v1beta1`.

**Comment by rdzimmer** [comment]
I've hit this now with a Deployment with just 1 container per pod, so we can throw out my theory of it only being the 2+ container deployments.  Again, it's reporting it wasn't able to get the CPU for a pod that isn't related to the HPA.

**Comment by ImamHyderAli** [comment]
You will have to add a line **--horizontal-pod-autoscaler-use-rest-clients=false** in the manifest file: kube-controller-manager.yaml which is located at:  /etc/kubernetes/manifests.

Preview of Edited **kube-controller-manager.yaml** :

![kube-controller-manager yaml](https://user-images.githubusercontent.com/29298783/40293630-7c44d72c-5cef-11e8-9c99-46e03b379b4a.png)

* delete the old hpa
       $ kubectl delete hpa (hpa name)
* and the autoscale the Deployment.
       $ kubectl autoscale deployment **Deployment_Name** --cpu-percent=100 --min=1 --max=5

**Comment by rdzimmer** [comment]
@ImamHyderAli Thank you for the suggestion.  Unfortunately, have already benn running with the `--horizontal-pod-autoscaler-use-rest-clients=false` flag on my controller-manager.  I'm in the process of getting kubernetes 1.10 today and will let you know if that resolves the issue.  
```
ps -ef | grep controller-manager
root      44213  44197  2 May17 ?        02:27:36 /hyperkube controller-manager --master=https://127.0.0.1:8001 --service-account-private-key-file=/etc/cfc/conf/server.key --feature-gates=TaintBasedEvictions=true,PersistentLocalVolumes=true,VolumeScheduling=true --root-ca-file=/etc/cfc/conf/ca.crt --min-resync-period=3m --cluster-cidr=10.1.0.0/16 --cluster-signing-cert-file=/etc/cfc/conf/ca.crt --cluster-signing-key-file=/etc/cfc/conf/ca.key --use-service-account-credentials=true --kubeconfig=/etc/cfc/conf/kube-controller-manager-config.yaml --pv-recycler-pod-template-filepath-hostpath=/etc/cfc/conf/recycler.yaml --pv-recycler-pod-template-filepath-nfs=/etc/cfc/conf/recycler.yaml --v=2 --leader-elect=true --horizontal-pod-autoscaler-use-rest-clients=false
```

**Comment by huxiaoliang** [comment]
It is better to porting hpa from `autoscaling/v1` to `autoscaling/v2beta1`, refer to [here ], (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)for details, I saw somewhere before that `targetCPUUtilizationPercentage`  will be deleted from k8s in feature (or next release).

Notice that the targetCPUUtilizationPercentage field has been replaced with an array called metrics. The CPU utilization metric is a resource metric, since it is represented as a percentage of a resource specified on pod containers. Notice that you can specify other resource metrics besides CPU. By default, the only other supported resource metric is memory.

**Comment by yadavkkumar** [comment]
@rdzimmer  You need to specify 
resources:
          requests:
            cpu: 200m
in your deployment yaml file
![screenshot from 2018-05-24 15-09-14](https://user-images.githubusercontent.com/29199141/40477711-bf53fc06-5f64-11e8-96f2-88e554e87e10.png)

After this, metric server or Heapster fill fetch the CPU resources.

**Comment by rdzimmer** [comment]
Based on the last comment I am not using `horizontal-pod-autoscaler-use-rest-clients=false` anymore. 
Some HPAs work, but most do not.  I do have non-zero CPU and memory requests and limits for all of the containers.   
Here is the HPA json:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: metric-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metric
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
```
Results in this:
```
kubectl get -o json hpa metric-hpa
{
    "apiVersion": "autoscaling/v1",
    "kind": "HorizontalPodAutoscaler",
    "metadata": {
        "annotations": {
            "autoscaling.alpha.kubernetes.io/conditions": "[{\"type\":\"AbleToScale\",\"status\":\"True\",\"lastTransitionTime\":\"2018-05-24T12:23:16Z\",\"reason\":\"SucceededGetScale\",\"message\":\"the HPA controller was able to get the target's current scale\"},{\"type\":\"ScalingActive\",\"status\":\"False\",\"lastTransitionTime\":\"2018-05-24T12:23:16Z\",\"reason\":\"FailedGetResourceMetric\",\"message\":\"the HPA was unable to compute the replica count: missing request for cpu on container event-observer in pod default/event-observer-66f6879df-nqs5z\"}]"
        },
        "creationTimestamp": "2018-05-24T12:22:46Z",
        "name": "metric-hpa",
        "namespace": "default",
        "resourceVersion": "186187",
        "selfLink": "/apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/metric-hpa",
        "uid": "2a398998-5f4d-11e8-b961-005056b460d7"
    },
    "spec": {
        "maxReplicas": 10,
        "minReplicas": 1,
        "scaleTargetRef": {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "name": "metric"
        },
        "targetCPUUtilizationPercentage": 50
    },
    "status": {
        "currentReplicas": 1,
        "desiredReplicas": 0
    }
}
```

The odd thing was that I have `apiVersion: apps/v1` in the metric yaml file, but it turns into `"apiVersion": "extensions/v1beta1",` in the `kubectl get -o json deployment metric`.  I'm looking into why and if that's a common thing between the ones that do not work.  

[metric_deployment.json.txt](https://github.com/kubernetes/kubernetes/files/2035592/metric_deployment.json.txt)

**Comment by rdzimmer** [comment]
[metric_deployment.json.txt](https://github.com/kubernetes/kubernetes/files/2035676/metric_deployment.json.txt)

**Comment by ImamHyderAli** [comment]
@rdzimmer can you please provide the pods (all namespaces) that have been running in your cluster, and specify the current version of kubernetes.

**Comment by yadavkkumar** [comment]
@rdzimmer You Need to specify that resource requests and limits in your deployment. In Kubernetes 1.10, the metric server has memory resource metric by default and all other resource type like CPU we need to specify them manually.
I think they have designed in this way only and gave the functionality to the user to specify the amount of CPU resource they require.
You can also go through the [HPA Documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics)

**Comment by pawel-furmaniak** [comment]
@rdzimmer I think your deployment `selector` was matching the `labels` of containers from other deployments in your namespace. In such case you also need to add cpu limits to those containers for the autoscaler to work.

**Comment by elranr** [comment]
> @rdzimmer I think your deployment `selector` was matching the `labels` of containers from other deployments in your namespace. In such case you also need to add cpu limits to those containers for the autoscaler to work.

How can I implement this?

**Comment by dzzmaster** [comment]
I also have this issue . 
but  my issue is :  
HPA's   deployment  's selector app=nginx **selector math another deployment 's  pod set** 
 also that  pod **do not have resources 's requests set** 
after set it , all work fine (actually maybe delete that deployment /change selector much better)
