### ISSUE TITLE
Readjust QPS defaults for c-m after moving GC to new dynamic client

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#63610]
Based on discussion on slack with @deads2k ,

Earlier, we were using the c-m qps wrongly in GC. The qps limit was enforced per resource type as opposed to globally for the GC.
So with the old behavior, if you set 10 QPS and had 30 resources, you'd actually have 300 qps.  if you had added more CRDs and aggregated APIs to 80 resources, the same config would then potentially have 800 qps.  With the new code, the QPS stays constant instead of scaling out based on unrelated values.

This change which was made in https://github.com/kubernetes/kubernetes/pull/63444 broke our scale tests as all of a sudden the GC feels starved of qps.
We need to:

- tune the defaults to have similar behaviour as earlier
- think about other consequences of increasing this qps (e.g on other controllers, etc)

cc @kubernetes/sig-api-machinery-bugs @kubernetes/sig-scalability-misc @deads2k @lavalamp @liggitt

**Comment by wojtek-t** [comment]
@jberkus FYI

**Comment by shyamjvs** [comment]
That's a good catch. Seems like we're now selectively giving the GC a qps of (c-m qps flag value)*20 because of the change.
In that case, @deads2k any reason why you've asked me to bump up the qps (as it already seems to have been bumped 20x)?
Is there some kind of an assumption that there will be ~20 resource types on avg in the cluster?

**Comment by shyamjvs** [comment]
I've sent a fix for this issue in #63657 explaining the rationale (with a release-note added by @deads2k).

**Comment by shyamjvs** [comment]
FYI - we're back to green https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/13478
