### ISSUE TITLE
Failing Test : [sig-cluster-lifecycle] All Reboot [Disruptive] [Feature:Reboot] tests are failing in sig-release-master-blocking gci-gke-reboot job

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63612]
## Failing Job
[gci-gke-reboot](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-reboot)

Gubernator Logs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/14474

Error
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:116
May  9 15:49:21.688: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:168

Triage
https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gke-reboot

## Commit Changes
https://github.com/kubernetes/kubernetes/compare/c59393e9f...af70337f8

This test is currently failing in sig-release master-blocking suite. This could potentially block Beta cut for v1.11 slated for 5/15 . @timothysc can you you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
@kubernetes/sig-cluster-lifecycle-bugs 
/assign @timothysc 
cc @jberkus @tpepper
/milestone v1.11

**Comment by timothysc** [comment]
This is either a node or a instrumentation error.  On restart there are a bunch of overlay2 errors 

``` rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument,} Running:nil Terminated:nil}```

/cc @kubernetes/sig-node-bugs @kubernetes/sig-instrumentation-bugs

**Comment by timothysc** [comment]
@AishSundar need to find a new owner re comments above. 

/assign @AishSundar

**Comment by AishSundar** [comment]
/sig node
/sig instrumentation
@kubernetes/sig-node-bugs 
@kubernetes/sig-instrumentation-bugs 

@dchen1107 @dims can one of you please help triage this issue. Its failing the sig-release-master-blocking suite.

**Comment by dims** [comment]
@AishSundar seems to have turned a corner https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-reboot

/unassign @dims

**Comment by brancz** [comment]
sig-instrumentation is investigating this, but at first glance I don't think it's actually instrumentation related as there are also non-instrumentation containers with the same errors docker overlay errors, so I think @kubernetes/sig-node-bugs should also have a deeper look.

**Comment by AishSundar** [comment]
@dims, @dchen1107 and @krousey can one of you please take a look at this issue along with sig-instrumentation. FWIW the tests seem to be flaky and have failed a couple of weeks in the past with the same failure stack.

Can one of you at the least comment if its a test issue or a real bug so we can decide on blocking v1.11 beta on this?

**Comment by dims** [comment]
@AishSundar this needs someone who is familiar with the GKE's docker setup etc. (`readlink /var/lib/docker/overlay2` error above in docker and kubelet logs). probably best to ping an internal team who works on this stuff? 

Also, we should not block v1.11 on an issue we see in GKE only (if that's so)

**Comment by maisem** [comment]
This doesn't look specific to GKE. It seems to also be happening on GCE

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/23826#sig-cluster-lifecycle-reboot-disruptive-featurereboot-each-node-by-dropping-all-outbound-packets-for-a-while-and-ensure-they-function-afterwards

https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=at%5C%20least%5C%20one%5C%20node%5C%20failed%5C%20to%5C%20reboot%5C%20in%5C%20the%5C%20time%5C%20given%5C.#9a3f59da96d25e83df6e

**Comment by dims** [comment]
`Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument` ( from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/23826/artifacts/err-e2e-minion-group-gpgb/kubelet.log )

So probably still related to google infrastructure (container image + docker?)

**Comment by AishSundar** [comment]
All reboot tests are passing now. definitely a case of flaky test that needs investigation. Will take it up offline. Closing this issue.

**Comment by AishSundar** [comment]
/reopen

these tests are flaky again, against both [master-blocking](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-reboot&show-stale-tests=) and [release-1.11-blocking](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-reboot-1.11&show-stale-tests=)

With 1.11 branch cut this Tuesday 6/19, its critical to assess if there's a real product issue vs a flaky test.

/assign @jszczepkowski since you de-flaked these tests last as per GH history ^ 

/cc @krousey @mengqiy for further investigation from GKE end.

/cc @jberkus @tpepper @dims as FYI

/priority critical-urgent

**Comment by k4leung4** [comment]
I took a look at the issue and as previously noted, the test is indeed flaky.
Eyeballing the history from the test dashboard, it passes around 50%.

The error we are seeing is "readlink /var/lib/docker/overlay2: invalid argument,"
which seems to imply some data were corrupted.
This has been reports with Docker since Mar 2017 and people are still encountering it as recently 2 days ago.
https://github.com/docker/for-mac/issues/1396
Users have reported seeing this on Linux and Windows in addition to Mac.

The workaround is to blow away /var/lib/docker

**Comment by AishSundar** [comment]
Thanks @k4leung4 for looking into this. So its safe to assume its a docker only issue and is not a product issue we should worry about in 1.11? Also in the release meeting today, we got some questions about if we have history of this in containerd as well or is it just a Docker issue. Any insights? 

I will keep this issue open to track a resolution for this test issue.

**Comment by tpepper** [comment]
@k4leung4 do you have links to the docker reports you were reviewing?

If this is a docker or is an overlay2 issue it should be expected more broadly than just the GCP/GKE context.  I'm suspicious this is a problem in the Google hosting platforms having changed something for OS deps, and/or in the test case not actively managing some OS deps upon which the test has specific requirements.

**Comment by k4leung4** [comment]
@tpepper linked are some of the top issues that I found
https://github.com/moby/moby/issues/35747
https://github.com/moby/moby/issues/10294
https://github.com/docker/for-mac/issues/1667
https://github.com/docker/for-win/issues/1766

The historical data only shows up to 05/22/2018, https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-05-22
and have been flaky since then.
Due to the lack of data before 05/22/2018, it is difficult to properly gauge if the issue was introduced prior to that or not.

I tried to reproduce the issue running the test from my machine and have failed reproduce the failure.
I have ran the test ~10 times, running all the failed reboot tests.

**Comment by AishSundar** [comment]
This seem to have been around since April of last year - https://github.com/kubernetes/kubernetes/issues/45146

**Comment by k4leung4** [comment]
I found part of the reason why it is flaky, and it is due to the ordering of the tests.
Looking at the last 20 runs, 11 passes, 9 failures, of the 9 failures, the first test is either "unclean reboot" or "kernel panic". None of the successful runs start with either of those tests.
To confirm the ordering is part of the cause of the failures, I was able to reproduce the failure by running the "kernel panic" reboot test by itself.

As for why the ordering matters, I am still investigating that.

**Comment by AishSundar** [comment]
FWIW, the reboot job and specifically the cluster-lifecycle tests have been failing for the same reason even before 1.10 RC cut timeframe

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-03-19&job=ci-kubernetes-e2e-gci-gke-reboot&test=%5C%5Bsig%5C-cluster%5C-lifecycle%5C%5D%5C%20Reboot%5C%20%5C%5BDisruptive%5C%5D%5C%20%5C%5BFeature%3AReboot%5C%5D

**Comment by dims** [comment]
@k4leung4 Kenny,

The GCE test seems to be way more stable than the GKE one (please see https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/)

So can you please compare the OS images used in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/25158 and https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/15405?

`cos-stable-66-10452-101-0` seems to be in the GKE which has the reboot issues. `cos-stable-65-10323-64-0` in GCE job seems to work better.

Note that neither of these images are controlled by configuration in the test-infra repo. `cos-stable-65-10323-64-0` is the default in the scripts ( https://cs.k8s.io/?q=cos-stable-65-10323-64-0&i=nope&files=&repos=kubernetes )

**Comment by roberthbailey** [comment]
@abgworrall - @dims points out in the above comment that different COS versions seem to affect our test flakiness. Could you see if anyone from the node team could look in to why that might be the case?

**Comment by k4leung4** [comment]
@dims 
At your suggestion, I ran the same test that previously failed for me with the node image "gke-1810-gke0-cos-beta-65-10323-12-0-p-v180322-pre", and it passes.

I had to run the test without the --extract flag, which uses a prebuilt k8s. Trying to determine how is the node image is determined when running with deployment=gke

Failing test command
go run hack/e2e.go --up --down --test --check-leaked-resources --gcp-project=$PROJECT_ID --cluster=kleung-flaky-e2e --gcp-network=kleung-flaky-e2e --deployment=gke --extract=ci/latest --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging --gcp-node-image=gci --gcp-zone=us-central1-f --gke-environment=test --provider=gke --test_args='--ginkgo.focus=\[sig\-cluster\-lifecycle\]\sReboot\s\[Disruptive\]\s\[Feature\:Reboot\]\seach\snode\sby\striggering\skernel\spanic\sand\sensure\sthey\sfunction\supon\srestart$ --minStartupPods=8' --timeout=180m

Passing test command:
go run hack/e2e.go --up --down --test --check-leaked-resources --gcp-project=$PROJECT_ID --cluster=kleung-flaky-e2e --gcp-network=kleung-flaky-e2e --deployment=gke --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging --gcp-node-image=gci --gcp-zone=us-central1-f --gke-environment=test --provider=gke --test_args='--ginkgo.focus=\[sig\-cluster\-lifecycle\]\sReboot\s\[Disruptive\]\s\[Feature\:Reboot\]\seach\snode\sby\striggering\skernel\spanic\sand\sensure\sthey\sfunction\supon\srestart$ --minStartupPods=8' --timeout=180m

**Comment by AishSundar** [comment]
@BenTheElder can probably help shed some light on how the node image is determined when running e2e tests with deployment=gke

**Comment by krzyzacy** [comment]
@yguo0905 ^^

**Comment by BenTheElder** [comment]
@yguo0905 would be the one for node images here I think, but basically it's just using the default COS when `--gcp-node-image=gci ` is used. (GCI is an old name).

**Comment by BenTheElder** [comment]
Dims also [has a good comment](https://github.com/kubernetes/kubernetes/issues/63612#issuecomment-398491216) on this above (sorry I missed that).

**Comment by k4leung4** [comment]
Like others have mentioned, `cos-stable-66-10452-101-0` is the default image used by the GKE with 1.10 kubernetes.

**Comment by dims** [comment]
@k4leung4 you mean the node image has to be `cos-stable-66-10452-101-0`? we don't care about the master image, just the node image if we can try the older one in the CI job.

**Comment by AishSundar** [comment]
I see test runs pass and fail with the same node image cos-stable-66-10452-101-0 

Passing run : https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/15409
Failing run : https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/15407

So may be its a flaky node image or may be the image is not the issue?

**Comment by k4leung4** [comment]
@dims the mapping is configured on the server side (GKE). There are flags with kubetest that will allow us to test with a specific cos image. I will be trying to verify with that.

@AishSundar like I mentioned before, I believe the flakiness is due to the ordering of the reboot tests when running with the cos image `cos-stable-66-10452-101-0`

**Comment by yujuhong** [comment]
This is not a new issue and has been there ever since we switched to overlay2 in GKE. The reboot tests does some pretty aggressive things -- triggering kernel panic, etc. This gets the overlay filesystem to be in a bad state sometimes, requiring nuking `/var/lib/docker`.

The same test flakes in 1.9, 1.10, and 1.11. I don't think this should block the release.

**Comment by dims** [comment]
@k4leung4 gotcha, thanks for confirming that there's no way to test the theory out.

@yujuhong so, you mean cos 66 has the overlay2 and can't deal with the same tests as cos 65?  that's fair. the only other thing we talked about in the call was trying to use `sync` in the reboot tests. not sure if that will help or not.

Anyway thanks for confirming that we don't have to worry about this. we should probably add remarks in the testgrid so folks down the line don't go hunting for the same issues we just did.

**Comment by dims** [comment]
@jberkus @AishSundar we should clear the milestone, priority etc per last comments from @yujuhong and @k4leung4

**Comment by AishSundar** [comment]
@dims thats so much for guiding the investigation and staying on top of this. As part of closing out this release, I will document the tests that have historically been failing, so future RTs are aware of them, and open any followup AI and assign sig's/ownership (i) de-flaking tests, (ii) removing them from release-blocking dashboard, (iii) updating logic etc

**Comment by guineveresaenger** [comment]
for tracking purposes:
/priority failing-test

**Comment by yujuhong** [comment]
> @yujuhong so, you mean cos 66 has the overlay2 and can't deal with the same tests as cos 65? that's fair. the only other thing we talked about in the call was trying to use sync in the reboot tests. not sure if that will help or not.

No, I have never seen GKE reboot tests been not flaky for a long time. We've seen the same issue when testing m63 with overlay2 in GKE and GCE. See https://k8s-testgrid.appspot.com/sig-release-1.10-all#gci-gce-reboot-1.10 as an example (m63). That's why I said this issue should not be release-blocking.

On the other hand, I have no idea why the 1.11 gce-reboot test has been so green.

**Comment by AishSundar** [comment]
"On the other hand, I have no idea why the 1.11 gce-reboot test has been so green."
@yujuhong do you suspect something else must be exacerbating the issue on GKE? or we should look into what made gce tests stable and do the same for GKE. Either way do you still feel its not release blocking?

**Comment by yujuhong** [comment]
@AishSundar I don't think the GKE tests have become worse (i.e., not a regression), so there is no need to block the release. Let me know if my understanding is wrong.

I don't know why the GCE tests have become stable. As for the difference between the two COS images (GCE vs GKE), maybe @filbranden can shed some light.

**Comment by jberkus** [comment]
gci-gke-reboot is passing for master, 1.12, 1.11.  Can we close this?

**Comment by krzyzacy** [comment]
this one is pretty stale...
/close

**Comment by jberkus** [comment]
And, spoke 24 hours too soon.

We're failing again, and for what looks like the same reason:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/18153

**Comment by krzyzacy** [comment]
🙃 
/shrug

**Comment by yujuhong** [comment]
The reason is most likely going to look the same (since they are reboot tests after all...), but they are not caused by the same issue if you look closely.  
These tests are not flaky, just outright failing for every build. I checked two tests, and none of the nodes can reach the network after the reboot consistently. I'm not convinced that this is known "flake". I'd suggest someone investigate the root cause.

**Comment by AishSundar** [comment]
Thanks for the input @yujuhong. Assigning to @msau42 as the GKE Dev on-call

/assign @msau42

**Comment by jberkus** [comment]
@yujuhong hmmm, should I open a new issue for this failure then?

**Comment by jberkus** [comment]
Closing this in favor of #69786 per discussion.

/close

**Comment by msau42** [comment]
Looking at one recent test run:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/18231/build-log.txt

The test failed because kubelet never became "not ready":
```
I1015 19:33:01.392] Oct 15 19:33:01.390: INFO: Waiting up to 2m0s for node gke-e2e-18231-344e3-default-pool-2b8d22c7-njwh condition Ready to be false
I1015 19:33:01.393] Oct 15 19:33:01.393: INFO: Condition Ready of node gke-e2e-18231-344e3-default-pool-2b8d22c7-njwh is true instead of false. Reason: KubeletReady, message: kubelet is posting ready status. AppArmor enabled
...
I1015 19:34:59.825] Oct 15 19:34:59.825: INFO: Condition Ready of node gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr is true instead of false. Reason: KubeletReady, message: kubelet is posting ready status. AppArmor enabled
I1015 19:34:59.826] Oct 15 19:34:59.825: INFO: Condition Ready of node gke-e2e-18231-344e3-default-pool-2b8d22c7-q5g8 is true instead of false. Reason: KubeletReady, message: kubelet is posting ready status. AppArmor enabled
I1015 19:34:59.826] Oct 15 19:34:59.825: INFO: Condition Ready of node gke-e2e-18231-344e3-default-pool-2b8d22c7-njwh is true instead of false. Reason: KubeletReady, message: kubelet is posting ready status. AppArmor enabled
I1015 19:35:01.825] Oct 15 19:35:01.825: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr didn't reach desired Ready condition status (false) within 2m0s
I1015 19:35:01.826] Oct 15 19:35:01.825: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-q5g8 didn't reach desired Ready condition status (false) within 2m0s
I1015 19:35:01.830] Oct 15 19:35:01.826: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-njwh didn't reach desired Ready condition status (false) within 2m0s
I1015 19:35:01.830] Oct 15 19:35:01.826: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr failed reboot test.
I1015 19:35:01.830] Oct 15 19:35:01.826: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-njwh failed reboot test.
I1015 19:35:01.830] Oct 15 19:35:01.826: INFO: Node gke-e2e-18231-344e3-default-pool-2b8d22c7-q5g8 failed reboot test.
```

When looking at one of the kubelet logs, I do see that kubelet had problems making Node updates to the api server:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/18231/artifacts/gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr/kubelet.log
```
E1015 19:33:26.150380    1303 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr": Get https://35.202.63.115/api/v1/nodes/gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr?resourceVersion=0&timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I1015 19:33:29.552319    1303 cloud_request_manager.go:113] Node addresses from cloud provider for node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr" not collected
E1015 19:33:36.150912    1303 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr": Get https://35.202.63.115/api/v1/nodes/gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I1015 19:33:41.553161    1303 cloud_request_manager.go:113] Node addresses from cloud provider for node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr" not collected
E1015 19:33:46.152035    1303 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr": Get https://35.202.63.115/api/v1/nodes/gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I1015 19:33:53.554253    1303 cloud_request_manager.go:113] Node addresses from cloud provider for node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr" not collected
E1015 19:33:56.152555    1303 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr": Get https://35.202.63.115/api/v1/nodes/gke-e2e-18231-344e3-default-pool-2b8d22c7-01rr?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Errors continue until kubelet is restarted 8 minutes later (the test times out at 2 minutes):
```
Stopping Kubernetes kubelet...
Stopped Kubernetes kubelet.
Started Kubernetes kubelet.
Flag --allow-privileged has been deprecated, will be removed in a future version
Flag --max-pods has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I1015 19:41:30.505574    1169 flags.go:33] FLAG: --address="0.0.0.0"
```
