### ISSUE TITLE
kubelet: eviction log size accounting is wrong

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#63620]
When using json-file logging, docker stores logs in `/var/lib/docker/containers/<containerid>/<containerid>-json.log`.  This is in the imagefs.  However in the eviction code, we account log size as part of the nodefs.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L1012-L1017

This results in wrongful evictions in the case that the size of the logs approaches nodefs capacity, which is a different filesystem.

In fact, we can get *negative* values for available:
```
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: -1566644639, capacity: 4086Mi
```

@derekwaynecarr @dashpole

**Comment by sjenning** [comment]
More complete log
```
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: 3854847994, capacity: 4085Mi
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: 3318239226, capacity: 4085Mi
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: 2781368314, capacity: 4085Mi
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: 1707626490, capacity: 4085Mi
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: -439857158, capacity: 4085Mi
helpers.go:833] eviction manager: thresholds - ignoring grace period: threshold [signal=allocatableNodeFs.available, quantity=0] observed -439857158
helpers.go:833] eviction manager: thresholds - reclaim not satisfied: threshold [signal=allocatableNodeFs.available, quantity=0] observed -439857158
helpers.go:833] eviction manager: thresholds - updated stats: threshold [signal=allocatableNodeFs.available, quantity=0] observed -439857158
helpers.go:833] eviction manager: thresholds - grace periods satisified: threshold [signal=allocatableNodeFs.available, quantity=0] observed -439857158
helpers.go:819] eviction manager: observations: signal=allocatableNodeFs.available, available: 3855089658, capacity: 4085Mi
```

**Comment by dashpole** [comment]
This must running version 1.8, right?  I [removed allocatableNodeFs evictions](https://github.com/kubernetes/kubernetes/pull/55338) in 1.9.

**Comment by sjenning** [comment]
Ah yes.  This is 1.7.  Everytime I visit the eviction code I have to relearn it all.
Even in the 1.7 code, I could not find out how logs where being accounted in nodefs though :-/

**Comment by dashpole** [comment]
This is the code that does this accounting in the 1.7.13 release: https://github.com/kubernetes/kubernetes/blob/7e4c2dfb27000d69cd43d3a78ece76d5564687be/pkg/kubelet/eviction/helpers.go#L739.
