### ISSUE TITLE
PROPOSAL: Include image labels in ContainerStatus

### ISSUE THREAD

**Issue by glb** [kubernetes/kubernetes#63629]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

Currently the [ContainerStatus](https://github.com/kubernetes/api/blob/8ab7c6a2fbd1724a52514855629cec31a8f86929/core/v1/types.go#L2183) API object reports the image and image ID, for example:
```
Image:         gcr.io/google_containers/kube-proxy-amd64:v1.9.6
Image ID:      docker-pullable://gcr.io/google_containers/kube-proxy-amd64@sha256:dd647b619b75882f217a21a6e2c473deb77cba1cfb20461da0084ed78d951af1
```

It's a not-uncommon practice for folks to include labels in their image metadata, for example vendor information or version control references that help link the image back to its source. I'd love to be able to get this information out of Kubernetes in a single step without having to resort to scripting multiple tools (for example `kubectl get pod` to get the image ID and then `docker inspect` to get the labels out of the image config). I believe that this is a common concept across container formats, for example this seems to be analogous to [annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md) in the open containers spec.

As it turns out, the image label information is available in the Docker API responses that are used to populate the `ContainerStatus` in `pkg/kubelet/dockershim/convert.go`. I don't know if the same is true for other runtimes.

I'd like to make an attempt at plumbing this data all the way up the stack so that it could eventually be exposed in `kubectl describe pod` or in some mystical future the k8s dashboard, but I'd need some help with what seems like pretty basic questions, like:

1. Do folks agree that this is a potentially-worthwhile activity that they'd be willing to support? Who could / should I ask questions of?
2. Where would I start looking for documentation on how to extend the API? Is it as simple as "edit [core/v1/types.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go), run <something that calls `go-to-protobuf`>, $$$?" or is there more involved?
3. Assuming I get something that seems like it could work, where should I go to learn how to write some integration tests, or if I wanted to see the smoke come out where would I go to learn how to build a cluster that uses the code from a local build?

ps: I know that Kubernetes assigns some labels to the container that represent the k8s labels and annotations and I'll need to filter those out somehow so they're not double-reported.

pps: I expect that this would need to be broken up into a series of PRs in order to be considered and reviewed efficiently. At the moment I'd be up for doing the support for Docker, but I don't have any experience with other runtimes (yet) so I'd be pretty hesitant to go there. Maybe someone with more experience will see this and get inspired?

**Comment by glb** [comment]
Thanks @xiaoxubeii for the sig annotation -- I really wasn't sure what SIG to send this to.

I can confirm that `ContainerStatus` doesn't have that information today, I'm proposing that it be added to the struct, perhaps something like this:

```
staging/src/k8s.io/api/core/v1/types.go
@@ -2405,6 +2405,9 @@ type ContainerStatus struct {
 	// Container's ID in the format 'docker://<container_id>'.
 	// +optional
 	ContainerID string `json:"containerID,omitempty" protobuf:"bytes,8,opt,name=containerID"`
+	// Image labels
+	// +optional
+	ImageLabels map[string]string `json:"imageLabels,omitempty" protobuf:"bytes,9,rep,name=imageLabels"`
 }
```

**Comment by lavalamp** [comment]
/sig node
/remove-sig api-machinery

SIG Node owns this API. We don't own individual APIs (with a few exceptions).

**Comment by glb** [comment]
Thanks for the redirect @lavalamp, hopefully SIG Node folks have an opinion on whether they would accept this.

Do you happen to have any pointers as to where I might learn the steps I'd need to go through in order to update the API properly? I've looked in a few likely places for a README but no luck so far.

**Comment by glb** [comment]
Update: did an install following [Kubernetes The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way) but using the built binaries from my build, but they didn't seem to do anything particularly different.

Next step will be to attempt to work through the various components that are involved a bit more systematically and see whether I can figure out what I missed.

**Comment by glb** [comment]
Similar request by @boosh in this comment: https://github.com/kubernetes/kubernetes/issues/47368#issuecomment-344993237

**Comment by andye2004** [comment]
@glb Whatever happened to this?

**Comment by glb** [comment]
@andye2004 I wasn't able to figure out the changes I needed to make end-to-end, didn't get any engagement here from the SIG, and didn't know at the time that raising the idea in Slack might help. Personally I still think it would be really helpful to have the ability to see image labels in pod status, but I don't have the cycles to figure it out at the moment.

**Comment by andye2004** [comment]
@glb, thanks for the feedback. I guess what's really frustrating about this is that the data is already there. Oh well, maybe later.....

**Comment by XenGi** [comment]
I would love to see the image labels via k8s api.
