### ISSUE TITLE
Adds a device plugin upgrade test under test/e2e/upgrades/

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#63630]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
Ideally we would like to have master/cluster upgrade test that exercises kubelet device plugin support based on a stub device plugin. Given that the stub device plugin based e2e test is not available yet, we may start with an upgrade test that is based on the existing gpu device plugin.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vikaschoudhary16** [comment]
> stub device plugin based e2e test is not available yet

@jiayingz 
I thought we have a [stub device plugin based e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin.go#L61). Or you meant something else by stub device plugin?

**Comment by jiayingz** [comment]
@vikaschoudhary16 the above one is a e2e_node test. To test master upgrade and cluster upgrade, we need a cluster level upgrade test. For reference, I am adding an upgrade test based on gpu device plugin: https://github.com/kubernetes/kubernetes/pull/63631. It would be nice if we can add one based on stub device plugin, which I guess will depend on the availability of stub device plugin based e2e test.

/cc @ScorpioCPH

**Comment by vikaschoudhary16** [comment]
@jiayingz That makes sense. I thought you were saying there is no stub device plugin. Thanks!
