### ISSUE TITLE
glusterfs coredump when kubelet mount a gfs pvc.

### ISSUE THREAD

**Issue by wangxinxu411** [kubernetes/kubernetes#63637]
1.BASE IMAGE of hypecube
gcr.io/google-containers/debian-hyperkube-base-amd64:0.10

2.the glusterfs version
root@node3:/# glusterfs --version                                                                                                                                                             
glusterfs 3.8.8 built on Jan 11 2017 14:07:11

3.the glusterfs log
root@node3:/# cat /var/lib/kubelet/plugins/kubernetes.io/glusterfs/pvc-1bcde16a-5363-11e8-9fdb-001a4a180029/gfstest-0-glusterfs.log  | more
pending frames:
patchset: git://git.gluster.com/glusterfs.git
signal received: 11
time of crash: 
2018-05-09 08:30:26
configuration details:
argp 1
backtrace 1
dlfcn 1
libpthread 1
llistxattr 1
setfsid 1
spinlock 1
epoll.h 1
xattr.h 1
st_atim.tv_nsec 1
package-string: glusterfs 3.8.8
/usr/lib/x86_64-linux-gnu/libglusterfs.so.0(_gf_msg_backtrace_nomem+0x7e)[0x7f244d53a37e]
/usr/lib/x86_64-linux-gnu/libglusterfs.so.0(gf_print_trace+0x334)[0x7f244d543ac4]
/lib/x86_64-linux-gnu/libc.so.6(+0x33060)[0x7f244bb90060]
12a]    /x86_64-linux-gnu/libglusterfs.so.0(gf_ports_reserved+0x13a)[0x7f244d544--More--
/usr/lib/x86_64-linux-gnu/libglusterfs.so.0(gf_process_reserved_ports+0x8e)[0x7f244d54435e]
/usr/lib/x86_64-linux-gnu/glusterfs/3.8.8/rpc-transport/socket.so(+0xc09b)[0x7f244806809b]
/usr/lib/x86_64-linux-gnu/glusterfs/3.8.8/rpc-transport/socket.so(client_bind+0x9d)[0x7f244806848d]
/usr/lib/x86_64-linux-gnu/glusterfs/3.8.8/rpc-transport/socket.so(+0x98d3)[0x7f24480658d3]
/usr/lib/x86_64-linux-gnu/libgfrpc.so.0(rpc_clnt_reconnect+0xc9)[0x7f244d3050f9]/usr/lib/x86_64-linux-gnu/libgfrpc.so.0(rpc_clnt_start+0x39)[0x7f244d3051c9]
/usr/sbin/glusterfs(glusterfs_mgmt_init+0x159)[0x558ba2423f79]
/usr/sbin/glusterfs(glusterfs_volumes_init+0x44)[0x558ba241ee94]
/usr/sbin/glusterfs(main+0x811)[0x558ba241b4b1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f244bb7d2e1]
/usr/sbin/glusterfs(_start+0x2a)[0x558ba241b5ea]

4.the heketi version
[root@localhost ~]# heketi --version
Heketi 4.0.0
[root@localhost ~]# heketi-cli --version
heketi-cli 4.0.0

5.the glusterfs server version
[root@localhost ~]# glusterfs --version
glusterfs 3.12.9
Repository revision: git://git.gluster.org/glusterfs.git

6.the storageclass of gfs
[root@master1 ~]# kubectl get storageclass gfssss -o yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storage_secret: "null"
    storage_status: ok
    storage_type: gfs
  creationTimestamp: 2018-05-09T08:28:07Z
  labels:
    storage_type: gfs
  name: gfssss
  resourceVersion: "725649"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gfssss
  uid: e69f189c-5362-11e8-9fdb-001a4a180029
parameters:
  clusterid: c8875b7703e6653395b4ade178c5839f
  restauthenabled: "false"
  resturl: http://192.168.30.50:8080
  volumetype: none
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete

**Comment by chenguoquan** [comment]
I have the same problem

**Comment by lyj7890** [comment]
@wangxinxu411 I have the same problem, Is there a final solution, thx
