### ISSUE TITLE
A DaemonSet pod was not upgraded correctly from a master upgrade test

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#63634]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I am trying to add a GPUMasterUpgrade test. When running the test from a 1.9.7 release to a recent k8s version built from head that updated the nvidia-gpu-device-plugin DaemonSet to a new image version, I found the nvidia-gpu-device-plugin DaemonSet pod running on the GPU node was not correctly updated to the new image version, even though the pod running on the master and the DaemonSet itself were both upgraded correctly.

Here is what I saw in the controller-manager log:
I0509 18:50:24.359732       1 daemon_controller.go:169] Updating daemon set nvidia-gpu-device-plugin
I0509 18:50:24.371411       1 daemon_controller.go:350] ControllerRevision nvidia-gpu-device-plugin-c4d8578bd added.
I0509 18:50:24.372311       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee8ed32e5903, ext:60613876775, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.372653       1 daemon_controller.go:841] Found failed daemon pod kube-system/nvidia-gpu-device-plugin-9hkgb on node e2e-test-jiayingz-master, will try to kill it
I0509 18:50:24.372695       1 controller_utils.go:216] Setting expectations &controller.ControlleeExpectations{add:0, del:1, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1636d57d, ext:113664764591, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.372714       1 daemon_controller.go:937] Nodes needing daemon pods for daemon set nvidia-gpu-device-plugin: [], creating 0
I0509 18:50:24.372763       1 daemon_controller.go:1010] Pods to delete for daemon set nvidia-gpu-device-plugin: [nvidia-gpu-device-plugin-9hkgb], deleting 1
I0509 18:50:24.372785       1 controller_utils.go:596] Controller nvidia-gpu-device-plugin deleting pod kube-system/nvidia-gpu-device-plugin-9hkgb
I0509 18:50:24.373106       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"nvidia-gpu-device-plugin", UID:"a531d6b6-53a5-11e8-bc10-42010a8a0002", APIVersion:"apps", ResourceVersion:"11527", FieldPath:""}): type: 'Warning' reason: 'FailedDaemonPod' Found failed daemon pod kube-system/nvidia-gpu-device-plugin-9hkgb on node e2e-test-jiayingz-master, will try to kill it
I0509 18:50:24.381899       1 pvc_protection_controller.go:284] Got event on pod kube-system/nvidia-gpu-device-plugin-9hkgb
I0509 18:50:24.381938       1 disruption.go:340] updatePod called on pod "nvidia-gpu-device-plugin-9hkgb"
I0509 18:50:24.381970       1 disruption.go:403] No PodDisruptionBudgets found for pod nvidia-gpu-device-plugin-9hkgb, PodDisruptionBudget controller will avoid syncing.
I0509 18:50:24.381976       1 disruption.go:343] No matching pdb for pod "nvidia-gpu-device-plugin-9hkgb"
I0509 18:50:24.382010       1 daemon_controller.go:517] Pod nvidia-gpu-device-plugin-9hkgb updated.
I0509 18:50:24.392665       1 resource_quota_monitor.go:352] QuotaMonitor process object: /v1, Resource=pods, namespace kube-system, name nvidia-gpu-device-plugin-9hkgb, uid bac02f23-53a5-11e8-bc10-42010a8a0002, event type delete
I0509 18:50:24.392776       1 pvc_protection_controller.go:284] Got event on pod kube-system/nvidia-gpu-device-plugin-9hkgb
I0509 18:50:24.392790       1 disruption.go:369] deletePod called on pod "nvidia-gpu-device-plugin-9hkgb"
I0509 18:50:24.392835       1 disruption.go:403] No PodDisruptionBudgets found for pod nvidia-gpu-device-plugin-9hkgb, PodDisruptionBudget controller will avoid syncing.
I0509 18:50:24.392842       1 disruption.go:372] No matching pdb for pod "nvidia-gpu-device-plugin-9hkgb"
I0509 18:50:24.392860       1 daemon_controller.go:646] Pod nvidia-gpu-device-plugin-9hkgb deleted.
I0509 18:50:24.392871       1 controller_utils.go:233] Lowered expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1636d57d, ext:113664764591, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.394425       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/nvidia-gpu-device-plugin" (34.654872ms)
E0509 18:50:24.394464       1 daemon_controller.go:265] kube-system/nvidia-gpu-device-plugin failed with : deleted 1 failed pods of DaemonSet kube-system/nvidia-gpu-device-plugin
I0509 18:50:24.395272       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1636d57d, ext:113664764591, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.395612       1 controller_utils.go:216] Setting expectations &controller.ControlleeExpectations{add:1, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c17943575, ext:113687661236, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.395632       1 daemon_controller.go:937] Nodes needing daemon pods for daemon set nvidia-gpu-device-plugin: [e2e-test-jiayingz-master], creating 1
I0509 18:50:24.397003       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"nvidia-gpu-device-plugin", UID:"a531d6b6-53a5-11e8-bc10-42010a8a0002", APIVersion:"apps", ResourceVersion:"11527", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: nvidia-gpu-device-plugin-9hkgb
I0509 18:50:24.413193       1 controller_utils.go:585] Controller nvidia-gpu-device-plugin created pod nvidia-gpu-device-plugin-4db46
I0509 18:50:24.413243       1 daemon_controller.go:1010] Pods to delete for daemon set nvidia-gpu-device-plugin: [], deleting 0
I0509 18:50:24.413270       1 controller_utils.go:188] Controller still waiting on expectations &controller.ControlleeExpectations{add:1, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c17943575, ext:113687661236, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.413399       1 daemon_controller.go:1075] Updating daemon set status
I0509 18:50:24.416299       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"nvidia-gpu-device-plugin", UID:"a531d6b6-53a5-11e8-bc10-42010a8a0002", APIVersion:"apps", ResourceVersion:"11527", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: nvidia-gpu-device-plugin-4db46
I0509 18:50:24.416490       1 disruption.go:328] addPod called on pod "nvidia-gpu-device-plugin-4db46"
I0509 18:50:24.416547       1 disruption.go:403] No PodDisruptionBudgets found for pod nvidia-gpu-device-plugin-4db46, PodDisruptionBudget controller will avoid syncing.
I0509 18:50:24.416555       1 disruption.go:331] No matching pdb for pod "nvidia-gpu-device-plugin-4db46"
I0509 18:50:24.416575       1 daemon_controller.go:469] Pod nvidia-gpu-device-plugin-4db46 added.
I0509 18:50:24.416599       1 controller_utils.go:233] Lowered expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c17943575, ext:113687661236, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.419742       1 taint_manager.go:344] Noticed pod update: types.NamespacedName{Namespace:"kube-system", Name:"nvidia-gpu-device-plugin-4db46"}
I0509 18:50:24.432022       1 daemon_controller.go:169] Updating daemon set nvidia-gpu-device-plugin
I0509 18:50:24.436718       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/nvidia-gpu-device-plugin" (42.21978ms)
I0509 18:50:24.437531       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c17943575, ext:113687661236, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.438391       1 controller_utils.go:216] Setting expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1a213733, ext:113730456688, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.438414       1 daemon_controller.go:937] Nodes needing daemon pods for daemon set nvidia-gpu-device-plugin: [], creating 0
I0509 18:50:24.438459       1 daemon_controller.go:1010] Pods to delete for daemon set nvidia-gpu-device-plugin: [], deleting 0
I0509 18:50:24.438469       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1a213733, ext:113730456688, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.438535       1 daemon_controller.go:1075] Updating daemon set status
I0509 18:50:24.455236       1 disruption.go:340] updatePod called on pod "nvidia-gpu-device-plugin-4db46"
I0509 18:50:24.455286       1 disruption.go:403] No PodDisruptionBudgets found for pod nvidia-gpu-device-plugin-4db46, PodDisruptionBudget controller will avoid syncing.
I0509 18:50:24.455294       1 disruption.go:343] No matching pdb for pod "nvidia-gpu-device-plugin-4db46"
I0509 18:50:24.455315       1 daemon_controller.go:517] Pod nvidia-gpu-device-plugin-4db46 updated.
I0509 18:50:24.460857       1 daemon_controller.go:169] Updating daemon set nvidia-gpu-device-plugin
I0509 18:50:24.464010       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/nvidia-gpu-device-plugin" (27.233756ms)
I0509 18:50:24.465274       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1a213733, ext:113730456688, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.465651       1 controller_utils.go:216] Setting expectations &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1bc133c9, ext:113757718781, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.465688       1 daemon_controller.go:937] Nodes needing daemon pods for daemon set nvidia-gpu-device-plugin: [], creating 0
I0509 18:50:24.465726       1 daemon_controller.go:1010] Pods to delete for daemon set nvidia-gpu-device-plugin: [], deleting 0
I0509 18:50:24.465735       1 controller_utils.go:182] Controller expectations fulfilled &controller.ControlleeExpectations{add:0, del:0, key:"kube-system/nvidia-gpu-device-plugin", timestamp:time.Time{wall:0xbeb4ee9c1bc133c9, ext:113757718781, loc:(*time.Location)(0x5433720)}}
I0509 18:50:24.466597       1 daemon_controller.go:1075] Updating daemon set status
I0509 18:50:24.466860       1 daemon_controller.go:1138] Finished syncing daemon set "kube-system/nvidia-gpu-device-plugin" (2.799303ms)
...

Ken and I debugged this a bit. We found if we manually deleted the pod running with the wrong version, a new pod was created with the right version. So this could be some race condition issue caused by failed daemonset pod during the first update.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
In k8s 1.9 branch
$ go run hack/e2e.go --build
$ export NODE_ACCELERATORS=type=nvidia-tesla-k80,count=2; export KUBE_NODE_OS_DISTRIBUTION=gci; export KUBE_GCE_ZONE=us-west1-b; export NUM_NODES=1; go run hack/e2e.go --up
Then switch to a test branch with PR https://github.com/kubernetes/kubernetes/pull/63631 pulled
$ go run hack/e2e.go --build
$ go run ./hack/e2e.go -v --test --test_args="--ginkgo.focus=\[Feature:GPUMasterUpgrade\]"

The test should actually pass but if we check the image IDs of the nvidia-gpu-device-plugin DaemonSet pods, we will see that the pod running on the gpu node has a different image from the one running on the master. The one running on the master has the correct image matching what we have in the upgraded master vidia-gpu-device-plugin addon DaemonSet setting.
$ kubectl -n kube-system describe pod nvidia-gpu-device-plugin | grep "Image ID"
    Image ID:		docker-pullable://k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e
    Image ID:		docker-pullable://k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0e79da6998a61257585e0d3fb5848240129f0fa5b4ad972dfed4049448093c33

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jiayingz** [comment]
/assign @janetkuo @kow3ns 
Janet or Ken, can you help take a look at this issue. I am hitting it consistently on my PR to add the GPU upgrade test. Thanks!

**Comment by janetkuo** [comment]
The DaemonSet manifest doesn't specify `.spec.maxUnavailable` so the default value `1` is used. The rollout will be paused when the threshold is hit. 

It's likely that sp,e old DaemonSet pods are crash looping during a rollout and therefore pause the rollout.

**Comment by janetkuo** [comment]
> It's likely that some old DaemonSet pods are crash looping during a rollout and therefore pause the rollout.

Actually, it's not this. DaemonSet controller can handled this case too -- DaemonSet controller will try to kill unhealthy old pods first to prevent the previous bad rollout from blocking new rollouts. 

Looking at the [DaemonSet manifest](https://github.com/kubernetes/kubernetes/blob/972a74e23805d3d75bc68ddf5bf9c409e8f9b294/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml) again, it's using `extensions/v1beta1` DaemonSet without specifying an update strategy, and the default behavior for `extensions/v1beta1` is `OnDelete` (basically mean no rolling update) for backward compatibility.
