### ISSUE TITLE
Revisit Creating CustomResourceDefinitions from apiextensions-apiserver integration tests

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#63656]
Currently, the logic behind creating CustomResourceDefinitions in `apiextensions-apiserver` integration tests is ugly and could be improved. The [`CreateNewCustomResourceDefinition`](https://github.com/kubernetes/kubernetes/blob/ca76734126fe68bb6ec4fa55be1854c49d2d21d5/staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go#L181) function creates CRD and then polls to make sure REST and cache storages are fully-initialized (there could be a race between initializing storages, check out [this comment](https://github.com/kubernetes/kubernetes/blob/ca76734126fe68bb6ec4fa55be1854c49d2d21d5/staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go#L187)).

The polling is done by trying to perform each supported operation (list/watch/create/delete), and if there's no error, it's safe to say CRD is created and initialized.

As this is complicated, we want to try to replace it by utilizing `EstablishingController`, which is being implemented in #63068.

I would like to give a try on fixing this issue once #63068 is merged. 

/kind feature
/sig api-machinery
/area custom-resources
/cc @sttts

**Comment by sttts** [comment]
/cc @nikhita @deads2k 

@deads2k you remember this storage cache issue. Wouldn't it be good if we fix it on the server?

**Comment by lavalamp** [comment]
We need a general mechanism for apiservers (in HA) to coordinate on flipping the status to the correct state at the correct time, and not just for CRDs...
