### ISSUE TITLE
Worker hung Installing kube-proxy snap

### ISSUE THREAD

**Issue by ernestmartinez** [kubernetes/kubernetes#63678]
MAAS deploy of kubernetes-worker as part of CDK bundle on MAAS node with Nvidia K10 GPU is hung in juju status with:  Installing kube-proxy snap, syslog shows:

May 10 16:59:14 gpu cdk-service-kicker[2354]: snap.kube-proxy.daemon: not active, restarting
May 10 16:59:14 gpu cdk-service-kicker[2354]: Failed to restart snap.kube-proxy.daemon.service: Unit snap.kube-proxy.daemon.service not found.
May 10 16:59:24 gpu cdk-service-kicker[2354]: snap.kubelet.daemon: checking
May 10 16:59:24 gpu cdk-service-kicker[2354]: inactive
May 10 16:59:24 gpu cdk-service-kicker[2354]: snap.kubelet.daemon: not active, restarting
May 10 16:59:24 gpu cdk-service-kicker[2354]: Failed to restart snap.kubelet.daemon.service: Unit snap.kubelet.daemon.service not found.
May 10 16:59:24 gpu cdk-service-kicker[2354]: snap.kube-proxy.daemon: checking

Node in question is an HP DL580G7 which has had has a strange issue where the node would go down during the docker install, and required a power-cycle in order for the install to complete. This has been an ongoing issue but the power-cycle got me past the issue. Same thing occurred today, and got beyond the nvidia-docker install but then hung on this current issue.

Eventually showed "hook failed install", then restarted with "Installing docker-engine from Nvidia PPA" again. 

As I have been writing this the install eventually completed and the worker is up and running according to juju status.

CDK-field-agent output attached.
[results-2018-05-10-13-10-51.tar.gz](https://github.com/kubernetes/kubernetes/files/1992562/results-2018-05-10-13-10-51.tar.gz)

@kubernetes/sig-bug

**Comment by dims** [comment]
please file a bug here? https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/

/close
