### ISSUE TITLE
header key validation stricter than user.Info.Extra key validation

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#63682]
user.Info.Extra keys can have '/' in them ( we actually advertise this in the [doc](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authentication/user/user.go#L35)) but header keys cannot. This is problematic because we transport those keys embeded in header keys when we use the requestheader authenticator. We have a couple options that I can think of. We can either:

1) Encode extra info differently.
2) Tighten extra info key validation.

Go validation here:
https://github.com/golang/go/blob/1c69384da4fb4a1323e011941c101189247fea67/src/net/textproto/reader.go#L593-L602

@yliaog @seans3 @deads2k @liggitt

**Comment by ericchiang** [comment]
Maybe modify the authenticator to accept percent encoded headers?

```
User-Extra-kubernetes.io%2Fpod.uid: ( value )
```

**Comment by dekkagaijin** [comment]
A few proposals we came up with:

1. Detect illegal characters, `%`-encode the offending characters, then either:
   1. Use the existing `X-Remote-Extra-` header prefix, blindly URLDecoding on the API server.
        * This breaks keys that look URLEncoded.
   1. Prefix encoded keys with `X-Remote-Extra-Encoded-` (for example), `X-Remote-Extra-` otherwise.
        * This would involve adding an extra encoded header here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L57
        * Alternatively, add an implicit `Encoded-` suffix to the specified prefixes.
1. Require users to adhere to the [RFC 7230 spec header characters](https://tools.ietf.org/html/rfc7230#section-3.2.6).
    * https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/authentication/user/user.go#L35

**Comment by mikedanese** [comment]
No matter what, we are making an incompatible change to fix this. We will need an action required release note.

2 is out of the question in my opinion. I am in favor of (1. i.) because I don't like the idea of dropping ExtraInfo that might be attenuating the AuthContext.

**Comment by dekkagaijin** [comment]
SGTM

**Comment by liggitt** [comment]
> I don't like the idea of dropping ExtraInfo that might be attenuating the AuthContext

I agree, though a version-skewed extension API server that misinterprets an encoded value from a new aggregator is a form of dropping the info, if the authorizer that acts on the attenuation isn't expecting two variants of the extra info.

For example, say your authenticator returns extra data of "acme.com/scopes=[userinfo]"

An old aggregator would encode that into a header an old extension server would fail to decode.

A new aggregator would encode that into a header of "X-Remote-Extra-acme.com%2Fscopes: ...". An old extension server would read that into a userinfo as "acme.com%2Fscopes=[userinfo]". If your authorizer was looking specifically for the `acme.com/scopes` key, it would not be attenuated properly.

**Comment by dekkagaijin** [comment]
@liggitt to clarify, my proposal is that only strings with offending characters (your 3rd example) would be base64-encoded in 1.ii., non-offending strings would be unaltered and backwards-compatible with existing api servers (the new header would be ignored). If a new client encodes offending strings and sends them under an explicitly coded header, we'd avoid the risk of misinterpreting the wire formats:

String Contents | Old Client, Old API server | New Client, Old API server | New Client, New API server
------------ | ------------- | ------------ | -------------
valid charset | OK | OK | OK
invalid charset | **request fails** | **new headers silently dropped** | OK

**Comment by liggitt** [comment]
> @liggitt to clarify, my proposal is that only strings with offending characters (your 3rd example) would be base64-encoded in 1.ii.

that doesn't work, for a couple reasons:
* how does a backend server know whether a given header should be base64-decoded? Would `X-Remote-Extra-enp6` represent the extra key `enp6` or `zzz`?
* go header parsing normalizes header case, which destroys information required by base64 encoding (https://github.com/golang/go/blob/1c69384da4fb4a1323e011941c101189247fea67/src/net/textproto/reader.go#L506)

**Comment by dekkagaijin** [comment]
> how does a backend server know whether a given header should be base64-decoded?

We'd add a separate set of headers (specified in a separate set of flags) which unambiguously designate encoded keys.

> go header parsing normalizes header case, which destroys information required by base64 encoding

Then we can encode it in hex? That way, abnormal charsets would still be preserved.

**Comment by dekkagaijin** [comment]
@liggitt tl;dr Newest proposal:

Normal `key`:  "X-Remote-Extra-`key`"
`key` with illegal char(s): "X-Remote-Encoded-Extra-`hex(key)`"

**Comment by liggitt** [comment]
I think it is better for an old extension API server to have an encoded and uninterpreted extra key values in its userinfo than for it to drop it completely. That keeps the info available for an authorizer to make use of if it wants to, keeps the data in audit logs, etc.

A new set of header prefixes has a lot of ripples for proxies and config, and once we're out of the skew window, I don't think we gain any benefit from having two sets of header prefixes.

**Comment by dekkagaijin** [comment]
So is the proposal to encode, use the existing header, skip decoding? If so, what encoding?

**Comment by mikedanese** [comment]
> @liggitt So is the proposal to encode, use the existing header, skip decoding? Or is that just for older API servers?

I think the proposal is to do (1.i.)ish. Encode using percent encoding in new front proxies and decode in new downstream backends. Use the same header. If old downsteams get jumbled (percent encoded) extra info keys, at least it will be available to the authorization (often delegated) and audit layer. This is better than using a new header because:

1. Old backends would ignore the new header. This is painful if the ExtraInfo was attenuating the auth context. It also causes data loss in the audit.
1. New headers are cruft and as @liggitt said, there isn't a path to removing it. I would prefer to avoid them if at all possible. Using a new header doesn't offer sufficient value IMO because of 1.

> For newer API servers, is it better to misinterpret unencoded strings (i.e. mistakenly decode strings whose plaintext looks encoded), or to skip decoding entirely?

I vote that new backends should always attempt to percent decode ExtraInfo keys and we slap a big "RELEASE NOTE ACTION REQUIRED" on the change.

**Comment by dekkagaijin** [comment]
SGTM, I'll put together a PR
