### ISSUE TITLE
Pod Deletion Independent of Container Deletion

### ISSUE THREAD

**Issue by salilgupta1** [kubernetes/kubernetes#63687]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
When we delete a pod via the API the container(s) within that pod are terminated gracefully and all. However, the pod is removed immediately after all the containers are terminated. This is an issue b/c our Fluentd DaemonSet doesn't have enough time to pick up the remaining logs associated with the container before they are removed with the pod going away. 

Is there a world where we could either provide a setting that staggers the removal of the pod after the containers are terminated on a pod deletion or just delete the containers associated with the pod but not the pod itself?
 
**What you expected to happen**:
I expect to be able to access logs for a pod for some period of time after deleting a pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lavalamp** [comment]
There is an option (-p) to read logs of deleted pods? https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_logs/

If that doesn't work, here's your options, in the order you should consider using them:

1) Stop needing to do this: make your pod publish the desired artifact somewhere more permanent. I strongly recommend this one if you can make it work.
2) Attach a finalizer to hold the object until you're all done.
3) Wait for us to implement lookup by UID + saving "tombstones" for old objects.

**Comment by salilgupta1** [comment]
@lavalamp thanks for the response. We can't make the container publish the desired artifacts to somewhere more permanent. Our clients own the containers and are expecting to see their logs show up without additional configuration on their end.

The finalizer option sounds the most appealing for us. I'd also be curious to see how option 3 pans out.

**Comment by lavalamp** [comment]
Option 3 isn't coming for quite a while (no generally agreed-on plan), so
don't hold your breath!

**Comment by salilgupta1** [comment]
hahah, sounds good!

**Comment by mikesaelim** [comment]
Hi @lavalamp, I work on the same project with @salilgupta1.  Thanks for your help so far.  I was testing out Option 2 on Minikube, and while the pod was kept alive by the finalizer, it seems like the container's logs were removed.

I had created a pod in Minikube that specified a finalizer like so:
```
apiVersion: v1
kind: Pod
metadata:
  finalizers:
    - finalizer.stable.example.com/bar
  <other stuff>
```
This pod contained one container, and there weren't any controllers configured to do anything with the finalizer.  When I issued the call to delete the pod, the running container went through its default termination grace period before terminating.  When the container terminated, the pod was kept around (in the terminating state), but after a couple seconds the logs were deleted from the node.  

I also noticed that some of the container metadata seemed to be deleted around the same time?  Specifically around the exit code and start and finish times.

Do you know what process automatically deletes the container logs despite the finalizer on the pod, and is there a way to configure it to wait?

**Comment by lavalamp** [comment]
/sig node

That's a question for either the container runtime or kubelet.
