### ISSUE TITLE
Support for service sessionaffinity when using an AWS ELB

### ISSUE THREAD

**Issue by stonefury** [kubernetes/kubernetes#63688]
I've seen some discussion on this, but no clear solution or commit, maybe I'm wrong?

I want to use the AWS ELB for incoming websocket connections.  The proxy protocol will preserve the client IP, but my understanding is the k8s service sessionAffinity will not work because the header is not right.  One solution is to put nginx in between to fix the header.  Would be cool if k8s could do 

/sig AWS

**Comment by xiaoxubeii** [comment]
I think it is very difficult to achieve, because we must peek into the TCP stream to get the real client ip by resolving proxy protocol.
