### ISSUE TITLE
Failing Test: [sig-network] DNS configMap nameserver should be able to change stubDomain configuration [Slow][Serial]

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63680]
## Failing Job
* [sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster&include-filter-by-regex=DNS%20configMap%20nameserver%20should%20be%20able%20to%20change%20stubDomain%20configuratio)

## Failing Test
[DNS configMap nameserver should be able to change stubDomain configuration [Slow][Serial]]
(https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/2115)

Has been failing consistently since 5/8

/kind bug
/priority failing-test
/priority important-soon
/sig network
/milestone v1.11
@kubernetes/sig-network-bugs
/assign @MrHohn 
cc @jberkus @tpepper

@MrHohn @grayluck can eiother of you please look into this? This is currently failing in sig-release-master-upgrade suite and will potentially block Beta cut for v1.11 which is slated for 5/15.

**Comment by grayluck** [comment]
I am looking into it.

**Comment by grayluck** [comment]
The root cause is that dns-server failed to start. It's due to failure of image inspect for "k8s.gcr.io/k8s-dns-dnsmasq-amd64:1.14.5".

Critical parts extracted from build-log.txt
```
I0510 05:27:05.234] May 10 05:27:05.232: INFO: At 2018-05-10 05:22:06 +0000 UTC - event for e2e-dns-configmap-dns-server-wf7h9: {kubelet gke-bootstrap-e2e-default-pool-8ddc707c-rm9b} InspectFailed: Failed to inspect image "k8s.gcr.io/k8s-dns-dnsmasq-amd64:1.14.5": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
I0510 05:27:05.234] May 10 05:27:05.232: INFO: At 2018-05-10 05:22:06 +0000 UTC - event for e2e-dns-configmap-dns-server-wf7h9: {kubelet gke-bootstrap-e2e-default-pool-8ddc707c-rm9b} Failed: Error: ImageInspectError
I0510 05:27:05.286] May 10 05:27:05.286: INFO: POD                                                      NODE                                          PHASE    GRACE  CONDITIONS
I0510 05:27:05.287] May 10 05:27:05.286: INFO: e2e-dns-configmap-dns-server-wf7h9                       gke-bootstrap-e2e-default-pool-8ddc707c-rm9b  Pending         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-05-10 05:22:05 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2018-05-10 05:22:05 +0000 UTC ContainersNotReady containers with unready status: [dns]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-05-10 05:22:05 +0000 UTC  }]
```

**Comment by grayluck** [comment]
The test turns green without any change. 
Should be docker daemon's problem. Should be solved when docker is restarted and image is re-pulled.
We may close the issue now.

**Comment by AishSundar** [comment]
@grayluck this looks like a flaky test and seems to have been flaring once in a while in the past

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-05-01&sig=network&job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster&test=DNS%20configMap%20nameserver%20should%20be%20able%20to%20change%20stubDomain%20configuration

Is there anything we can do to make the test more robust? probably try pulling the image again when the test hits this issue?

**Comment by AishSundar** [comment]
Sounds good. I will close this one for now.
