### ISSUE TITLE
v4.channel.k8s.io attach (WebSockets) status is always "Successful" even if the container fails

### ISSUE THREAD

**Issue by mewa** [kubernetes/kubernetes#63694]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
I'm not sure if it's intended behaviour, but when an `attach` session closes (i.e. attached process exits) it always returns
```json
{"metadata":{},"status":"Success"}}
```
on error channel, regardless of the process exit code.

**What you expected to happen**:
I would expect to receive a message containing the exit code of that process (especially if it's non-zero).
Especially since the container which exits with non-zero code will be listed as failed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Attach to a pod container using WebSocket connecion and `v4.channel.k8s.io` subprotocol.
2. Execute a command exiting with non-zero code (e.g. `exit 1`)
3. Observe `"status":"Success"` on error channel (4)

**Anything else we need to know?**:
I believe this issue is linked to [these lines](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/attach.go#L55-L57)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GCP (GKE)

**Comment by wgliang** [comment]
Please pull #63697 down to see if it can solve your problem, if it can please ping me.
