### ISSUE TITLE
Enable content trust for k8s.gcr.io

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [kubernetes/kubernetes#63704]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
Docker images at `k8s.gcr.io` are not signed.

**What you expected to happen**:
The images should be signed.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
$ DOCKER_CONTENT_TRUST=1 docker run --rm k8s.gcr.io/fluentd-elasticsearch:v2.0.4
docker: Error: remote trust data does not exist for k8s.gcr.io/fluentd-elasticsearch: k8s.gcr.io does not have trust data for k8s.gcr.io/fluentd-elasticsearch.
See 'docker run --help'
```

**Anything else we need to know?**:
Please push your Docker images with [content trust](https://docs.docker.com/engine/security/trust/content_trust/) so that clients can verify that the images are actually built by you.

@kubernetes/sig-container-identity-feature-requests

**Comment by dims** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/30603

**Comment by dims** [comment]
cc @justaugustus
