### ISSUE TITLE
kubectl exec return error: unable to upgrade connection: pod does not exist /sig-contributor-experience-bugs

### ISSUE THREAD

**Issue by CrisMon-01** [kubernetes/kubernetes#63702]
If everyone else is running a cluster with kubeadm on virtual machine i think [this](https://medium.com/@joatmon08/playing-with-kubeadm-in-vagrant-machines-part-2-bac431095706) lectures is a must have because i have spend same days to solve this error: 
`error: unable to upgrade connection: pod does not exist`
or this
 kubectl logs
`Error from server (NotFound): the server could not find the requested resource`
and i haven't find samethink about it on the kubernetes guide or on the kubeadm issue traker.
If you are running same virtualmachine you had to do on the Master add this at the kubeadm init:
`--apiserver-advertise-address=<ip-address>`
and on the other nodes in the config file: `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`
you had to add this other ambient variables:
`Environment="KUBELET_EXTRA_ARGS=--node-ip=<worker IP address>"`
so restart the kubelet services and that had permit ot me to connect to pod schedule on other nodes that are virtual machine and are not exposed to the internet but are linked to the real machine where they are running.
This is a little tips from my experience working with kubernetes

`@kubernetes/sig-contributor-experience-bugs`

**Comment by dims** [comment]
cc @joatmon08

**Comment by abassanini** [comment]
In ubuntu/debian family, use the `/etc/default/kubelet` file, to append the IP of the node/worker

```
cat /etc/default/kubelet
KUBELET_EXTRA_ARGS="--node-ip=192.168.56.XX"
```

**Comment by kirankumarhm** [comment]
Thanks I have the same configuration Vagrant + Virtualbox for setting up a K8s cluster. On all worker node I did edit for  corresponding IP address  and got resolved. thank you so much

**Comment by aliakkas006** [comment]
follow these steps:

You should apply the --node-ip configuration on both the master and worker nodes, but with their respective IPs:

**Master Node (192.168.56.100):**

Edit /etc/default/kubelet:
sudo vi /etc/default/kubelet
Set the master's IP:
KUBELET_EXTRA_ARGS="--node-ip=192.168.56.100"
Restart kubelet:
sudo systemctl daemon-reload
sudo systemctl restart kubelet


**Worker Node (192.168.56.102):**
Edit /etc/default/kubelet:
sudo vi /etc/default/kubelet
Set the worker's IP:
KUBELET_EXTRA_ARGS="--node-ip=192.168.56.102"
Restart kubelet:
sudo systemctl daemon-reload
sudo systemctl restart kubelet

**Why?**
Master Node (192.168.56.100)
Needs its correct IP for:
kube-apiserver communication (--advertise-address=192.168.56.100)
kubelet registration with the control plane
Worker Node (192.168.56.102)
Needs its own IP for:

Joining the cluster correctly
Pod networking and node-to-node communication

**Verification:**
Run on each node to confirm the correct IP is set:

ps aux | grep kubelet | grep node-ip
Expected output:

Master: --node-ip=192.168.56.100
Worker: --node-ip=192.168.56.102
Check cluster node IPs:

kubectl get nodes -o wide
Should show:

NAME      STATUS   INTERNAL-IP      ...
master    Ready    192.168.56.100   ...
worker    Ready    192.168.56.102   ...
Troubleshooting
If the worker node fails to join:

**Check logs:**
sudo journalctl -u kubelet -n 50 --no-pager

**Verify network connectivity:**
ping 192.168.56.100  # From worker to master
ping 192.168.56.102  # From master to worker
