### ISSUE TITLE
Phabricator example images in README.md doesn't match the json files

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#6371]
A couple of places in the README refer to images prefixed with kubernetes, but they're actually prefixed with fgrzadkowski. Maybe create the kubernetes ones? Or change the README.

kubernetes/example-php-phabricator -> fgrzadowski/example-php-phabricator
kubernetes/example-cloudsql-authenticator -> fgrzadowski/example-cloudsql-authenticator

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
