### ISSUE TITLE
Priority support in service selector

### ISSUE THREAD

**Issue by mradmila** [kubernetes/kubernetes#63729]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

I would like to see if it is possible to create tiered/priority selector. Here's the scenario: I have a base deployment of pods that do an OK job, and start up quickly. I also have super-awesome pods that are highly customized but take longer to set up. I would like selector to "prefer" super-awesome ones, if they are there, and fallback to base ones if there are no customized ones. Note that multiple services could fallback to the same base ones, and would differ only in customized entries. It would be great if this selection could all be done within a single service, with slightly more complex selector query. I know iptables/ipvs don't leave too much room to improvise, but I just wanted to check if anyone else thought of this, and if there is another way to do it (perhaps through Istio or some higher level routing).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mradmila** [comment]
@kubernetes/sig-network-feature-requests

**Comment by chrishiestand** [comment]
Could this be accomplishd using the ipvs "shortest expected delay" algorithm?

**Comment by thockin** [comment]
The only way we could MAYBE do something like this would be statically.  E.g. if you want the service to use pods labelled `app=myapp` before using `app=emergency-backup`, the iptables rules at any given point in time would EITHER send all traffic to `app=myapp` OR send all traffic to `app=emergency-backup`.  The trigger for the decision would be whether the set of pods labelled `app=myapp` was empty or not.

This would not handle "they are too slow" or "too overloaded".  Only "not present".

As such, it doesn't strike me as a particularly useful feature - can you explain why?

**Comment by mradmila** [comment]
You are correct, this will not handle fully dynamic cases and won't be adaptive. But consider this: I have an expensive user adapted service which I will deploy when conditions are met (paid subscription, enough usage, etc.) and in the mean time I would like to have a generic service work for all users. So I always route there first, and then when adapted service is ready I would like it to win. Similarly, any hiccups in adapted service updates or any instabilities should be amortized by generic one. Does this make sense? Yes, a fully dynamic switch would be probably better but this static one would also work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
