### ISSUE TITLE
Enable kubectl to have a flag to adjust TCP keep-alives...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#63727]
Right now you can not adjust TCP settings from the command line. This is useful for long-running commands (e.g. `kubectl proxy`) which may be inactive and time out from time to time.

@kubernetes/sig-cli-feature-requests

**Comment by IanMoroney** [comment]
This affects us also and starts to get worse when you leverage additional tools on top of kubectl such as the  `az aks browse` functionality in the Azure Kubernetes Service CLI.
Being able to adjust the TCP settings would be very useful.
