### ISSUE TITLE
When edit PodDisruptionBudget, improper message was produced and cannot updated labels due to required disruptedPods field

### ISSUE THREAD

**Issue by nak3** [kubernetes/kubernetes#63756]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- PodDisruptionBudget provides inappropriate message and cannot be updated as `disruptedPods` is required filed.

**What you expected to happen**:

- `kubectl edit pdb <PDB_NAME>` works fine for editing labels under `metatdata`. Also, produce correct error message when edit `spec` field.

**How to reproduce it (as minimally and precisely as possible)**:

#### 1. create pdb

~~~
# kubectl create pdb my-pdb --selector=app=nginx --min-available=50%
~~~

#### 2. Edit the pdb

~~~
# kubectl edit pdb my-pdb
// e.g Update label under metadata
  labels:
    foo: bar
  name: my-pdb
~~~

Then, we will get following error after step-2.

~~~
# poddisruptionbudgets.policy "my-pdb" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(PodDisruptionBudget.status): missing required field "disruptedPods" in io.k8s.api.policy.v1beta1.PodDisruptionBudgetStatus
~~~

#### Expected:

- When edit `spec`, it should provide correct message as `updates to poddisruptionbudget spec are forbidden.`.

~~~
# poddisruptionbudgets.policy "my-pdb" was not valid:
# * spec: Forbidden: updates to poddisruptionbudget spec are forbidden.
~~~

- When edit `metadata` especially labels under metadata, they should be updated without error.

**Anything else we need to know?**:

According to the code comment, `disruptedPods: null` is valid.

https://github.com/kubernetes/kubernetes/blob/feeee5036321db39fbbf1132c2fc6e31491058a9/pkg/apis/policy/types.go#L71-L73

**Environment**:
- Kubernetes version (use `kubectl version`): build on feeee5036321db39fbbf1132c2fc6e31491058a9

**Comment by nikhita** [comment]
/remove-lifecycle stale

there is a PR open
