### ISSUE TITLE
Sub-optimal sizing of buckets exposed in the apiserver_request_latencies metrics

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes/kubernetes#63750]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Currently the buckets defined for the API server latency metric: `apiserver_request_latencies` are defined like this: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L64-L65 meaning the smallest bucket is 125ms.

If you want to estimate the percentiles based on this then it only makes sense if the actual latency of your API server is around 125ms or higher otherwise you get quite skewed numbers.

In our case we are running more than 80 clusters on AWS on different instance types and out of those 80 clusters only 3 has a latency higher than 125ms (for verb="GET") as reported clientside in the `apiserver_request_latencies_summary` metric. The rest has a latency below 100ms and most of them even a latency under 10ms (Looking at GET p99).

However, because of the bucket sizes all latencies are reported to be close to or higher than 125ms if we try to estimate it with a query like this:

```
histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket[5m])) by (le, verb))
```

![p99](https://user-images.githubusercontent.com/128566/39957809-4b28b548-55f9-11e8-9f8e-5592468a5470.png)

It's clear that the estimated values are much higher than what is reported clientside in the `apiserver_request_latencies_summary` metric.

Looking at the aggregated estimations thus gives the wrong impression of how the service is performing.

**What you expected to happen**:

I realize that it's impossible to pick bucket sizes that will be a perfect fit for everyone since the latency ofc. will heavily depend on the load of the clusters and the backing hardward. However, I think it would be more sensible to pick buckets that start below 125ms.

The prometheus library provides some default bucket sizes: https://github.com/prometheus/client_golang/blob/master/prometheus/histogram.go#L59

> The default buckets are tailored to broadly measure the response time (in seconds) of a network service.

These buckets are in the range from 5ms to 10s which seems much more sensible to cover a wide range of Kubernetes deployments.

I tried to change the buckets used and this is what I saw:

Query: 

```
histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket[5m])) by (le, verb))
```

Result with the current buckets:

```
{verb="DELETE"}	123750
{verb="GET"}	123750
{verb="LIST"}	123875.25303643724
{verb="PATCH"}	123750
{verb="POST"}	123750.00000000001
{verb="PUT"}	123750
{verb="WATCH"}	8000000
```

Result with the default prometheus bucket sizes:

```
{verb="DELETE"}	NaN
{verb="GET"}	4985.64
{verb="LIST"}	23381.395348837177
{verb="PATCH"}	19100.000000000007
{verb="POST"}	4950
{verb="PUT"}	9892.028985507248
{verb="WATCH"}	10000000
```

Values are in microseconds.

Based on this I suggest we change the buckets defined for the metric to be more useful. I'm happy to provide a PR if you agree with this.

**How to reproduce it (as minimally and precisely as possible)**:

Scrape the kube-apiserver prometheus metrics and query them like this:

```
histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket[5m])) by (le, verb))
```

**Anything else we need to know?**:

**Environment**: Not relevant.
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig instrumentation

**Comment by justaugustus** [comment]
Hey guys, can you take a look at this when you have a chance?
/assign @brancz @piosz 
/help

**Comment by brancz** [comment]
Sorry for not seeing this earlier, yes we should absolutely do the change you proposed. As we would already make semantic changes to the metric we should also make sure the result adheres to the [instrumentation guideline](https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md) (as it currently does not). This would mean making the unit seconds and reflecting that in the metric name. This is fine to do as we have no stability guarantees for metrics, however we should still add a changelog entry that we did change this.

Would you like to take care of this @mikkeloscar? I'd be more than happy to review the pull request. (for future reference, for anything about metrics just tag sig-instrumentation :slightly_smiling_face: )

**Comment by ehashman** [comment]
This is also affecting us. I'll see if I can drag this into the metric overhaul KEP.

**Comment by jrake-revelant** [comment]
Very interested in seeing this fixed.

**Comment by brancz** [comment]
I believe this is addressed with https://github.com/kubernetes/kubernetes/pull/73638

**Comment by ehashman** [comment]
With #73638 merged, this can be closed.

/close

**Comment by bboreham** [comment]
I don't understand how, given the problem "most of them even a latency under 10ms", this was fixed by changing to buckets starting at 50ms and mostly between 125ms and 2000ms.

@mikkeloscar is it working better for you now?

**Comment by mikkeloscar** [comment]
I haven't looked deeply into this for a while. a quick look at our dashboards suggest we are still landing in a 125 bucket.

![api-latency](https://user-images.githubusercontent.com/128566/67158302-d2af5400-f336-11e9-93b0-0023f643419a.png)

We are currently running `v1.14.8`
