### ISSUE TITLE
Failing test : [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow] failing in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63768]
## Failing Job
* [gce-1.10-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster)
* [gke-gci-1.10-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-master)

## Failing Test
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2133

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=scheduling

This test is currently failing in sig-release master-upgrade suite. This could potentially block Beta v1.11 which is due to be cut Tuesday,5/15. @k82cn will this be addressed by the fix for [Issue #62704](https://github.com/kubernetes/kubernetes/issues/62704)

/kind bug
/priority failing-test
/priority important-soon
/sig scheduling
@kubernetes/sig-scheduling-bugs 
/milestone v1.11

cc @jberkus @tpepper

/assign @k82cn

**Comment by k82cn** [comment]
> will this be addressed by the fix for Issue #62704

@AishSundar , just check the log/code; #62704 is helpful. Did not found other issues right now, and the test is green now. 

I'd like to close this one for now; if red again, please feel free to re-open it :)
