### ISSUE TITLE
Should not rely on checking event message `Successfully assigned ...` in e2e test

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#63766]
**What happened**:

Copied from: https://github.com/kubernetes/kubernetes/pull/63647#discussion_r187507372

**What you expected to happen**:

We should not rely on checking event message string `Successfully assigned ...` in scheduling e2e test, because the string itself is not reliable, any unconscious change of this string will cause e2e test fail (this already happened for 2x times), and debugging those issues tend to be time consuming.

I would suggest create a specific `Successful assigned` event type or similar approach to fix it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
> I would suggest create a specific Successful assigned event type or similar approach to fix it.

We have have `Type` and `Reason`; what we need to do is to retrieve pod and node info :)
