### ISSUE TITLE
kubectl log indicates pod doesn't exist when it is actually pending

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#6376]
kubectl log will state that the pod doesn't exist while the pod is in pending state. I think it would be better to indicate that there are no logs and that the pod is in pending state.

./cluster/kubectl.sh log authenticator-controller-boqdp
Running: ./cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl log authenticator-controller-boqdp
Pod "authenticator-controller-boqdp" does not exist

./cluster/kubectl.sh get pods -l name=authenticator  
Running: ./cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl get pods -l name=authenticator
POD                              IP        CONTAINER(S)    IMAGE(S)                                      HOST                                                            LABELS               STATUS    CREATED
authenticator-controller-boqdp             authenticator   fgrzadkowski/example-cloudsql-authenticator   kubernetes-minion-db1v.c.krousey-kubernetes-starter.internal/   name=authenticator   Pending   2 minutes

**Comment by reiz** [comment]
I have the same issue. My pod is in `Running` state and still `kubectl logs <pod>` doesn't work. Only returns `Pod "example-vs1d1" does not exist`. But `kubectl logs  example-vs1d1` works and outputs: 

```
Name:				example-vs1d1
Namespace:			default
Image(s):			nginx
Node:				k8s0001-dev.gb-lon1.kubernetes.versioneye.com/10.31.226.75
Start Time:			Mon, 30 Nov 2015 12:17:14 +0000
Labels:				run=example
Status:				Running
Reason:
Message:
IP:				10.1.63.24
Replication Controllers:	example (1/1 replicas created)
Containers:
  example:
    Container ID:	docker://7409f8a0da62ab82d4a500f5b95b7e83f75f6d0e382db69a0b3abc2b720c090d
    Image:		nginx
    Image ID:		docker://198a73cfd6864ec3d349cf8f146382cca9584a56c3b80f28b7318c9895fb0ae3
    State:		Running
      Started:		Mon, 30 Nov 2015 12:17:31 +0000
    Ready:		True
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	True
Volumes:
  default-token-kx5ue:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-kx5ue
No events.
```

**Comment by reiz** [comment]
By the way. I'm running Kubernetes 1.1.2 on CoreOS beta with Docker 1.8.3.

**Comment by kargakis** [comment]
@krousey @reiz is this still an issue?

**Comment by kargakis** [comment]
Closing due to age. Reopen if this is still an issue
