### ISSUE TITLE
why my dnsmsq server not effective

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#63765]
```
[root@node1 app]# kubectl get configmap kube-dns -n kube-system -o yaml
apiVersion: v1
data:
  stubDomains: |
    {"taobao.com": ["10.104.205.80"]}
  upstreamNameservers: |
    ["8.8.8.8", "8.8.4.4"]
kind: ConfigMap
metadata:
  creationTimestamp: 2018-05-07T10:56:47Z
  name: kube-dns
  namespace: kube-system
  resourceVersion: "1809556"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-dns
  uid: 565237db-51e5-11e8-8c57-002197403677
```

```
[root@node1 app]# kubectl describe svc dnsmasq -n dns
Name:              dnsmasq
Namespace:         dns
Labels:            app=dnsmasq
Annotations:       <none>
Selector:          app=dnsmasq
Type:              ClusterIP
IP:                10.104.205.80
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         10.244.4.70:53
Port:              dns-udp  53/UDP
TargetPort:        53/UDP
Endpoints:         10.244.4.70:53
Session Affinity:  None
Events:            <none>
```

/ # cat kube-dns-config/
..2018_05_14_00_55_40.441330605/  ..data/                           stubDomains                       upstreamNameservers
/ # cat kube-dns-config/stubDomains 
{"taobao.com": ["10.104.205.80"]}

**Comment by xiaoxubeii** [comment]
Please follow the instruction:



**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature


**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:


**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
