### ISSUE TITLE
updating/editing resource quota using kubectl commandline flags

### ISSUE THREAD

**Issue by Kailashcj** [kubernetes/kubernetes#63771]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> 
> /kind feature

**What happened**:
I wish to change below listed quota hard limit from 08 to 10. couldn't find a kubectl flag to update existing quota. I was able to update the same via quota manifest file. what is the recommended way to modify/update resourcequota's?

kubectl describe resourcequota foobar
Name: foobar
Namespace: default
Resource     Used     Hard
--------         ----         ----
pods             7             8 

**What you expected to happen**:
something like,
kubectl edit quota foobar --hard pods=10

if command line update of quota is not supported, update this information in webpage https://kubernetes.io/docs/concepts/policy/resource-quotas/

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create resourcequota qspidey --hard pods=5

Next, try to increase the number of pods to 10

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux kube-head 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by Kailashcj** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by dixudx** [comment]
@Kailashcj Please try to use `kubectl edit resourcequota foobar`.
