### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by maryxu** [kubernetes/kubernetes#63778]
I'm using rancher 1.6 to deploy kubernetes and the website is going well. But when I use kubectl to manage the k8s, it reminds me that:
[root@##### .kube]# kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority
How should I check on this? I'm using the config file which is generated from Kubernetes CLI. Thanks!

**Comment by dims** [comment]
Please ask on stackoverflow, Discuss ( https://discuss.kubernetes.io/ ), on kubernetes-users slack channel.

/close
