### ISSUE TITLE
HPAs not working on GKE 1.9.7

### ISSUE THREAD

**Issue by IvanAlegre** [kubernetes/kubernetes#63786]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
After creating the horizontal pod autoscaler, it doesn't get the metrics to autoscale. `kubectl top pods` actually gets correctly the amount of cpu in use. Old hpa created with previous kubernetes versions works fine, they currently are being autoscaled right now.

```
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedComputeMetricsReplicas  49m (x13 over 55m)   horizontal-pod-autoscaler  failed to get cpu utilization: no metrics returned matched known pods
  Warning  FailedGetResourceMetric       49s (x111 over 55m)  horizontal-pod-autoscaler  no metrics returned matched known pods
```

I've tried deleting all deployment/service/autoscaler and recreate it, but no luck. I've also tested to create a new autoscaler for an old deployment and same problem apperars (no metrics returned matched known pods).

**What you expected to happen**:
That new horizontal pod autoscalers get cpu usage and actually work.

**How to reproduce it (as minimally and precisely as possible)**:
Have a GKE cluster with Kubernetes 1.9.7.gke.0 running and create an autoscaler for a deployment to check if it works.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: 1.9.7-gke.0
- OS (e.g. from /etc/os-release):
```
BUILD_ID=10323.75.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=58f1195f1c24ee272ffc7b913c268b781483fff1
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`): Linux gke-cluster-1-main-pool-e9155b8a-14xj 4.4.111+ #1 SMP Thu Apr 19 11:45:40 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
- Install tools:
- Others:
heapster-v.1.5.2
metrics-server-v0.2.1

**Comment by vikash** [comment]
I have the exactly same issue.

**Comment by IvanAlegre** [comment]
Solved by setting in the associated Deployment: `spec.template.spec.containers[0].resources.requests:cpu` to something different than 0.

@yadavkkumar said it in https://github.com/kubernetes/kubernetes/issues/63615#issuecomment-391654404
