### ISSUE TITLE
 When enable the equivalence cache feature which makes the pod scheduling performance decline

### ISSUE THREAD

**Issue by godliness** [kubernetes/kubernetes#63784]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:

 When enable the equivalence cache feature which make the pod scheduling performance decline.

**What you expected to happen**:

What i think is that when i enable the cache, it should enhance the performance of kube-scheduler.

**How to reproduce it (as minimally and precisely as possible)**:

- Got a physical machine which is 32 CPUs  and 64 GB Memory

- Enable equivalence cache feature

- Schedule 3000 Pods On 3000 Nodes

- Use schduler_perf to run an integration test

**Anything else we need to know?**:

Enable cache: 60+/s
Disable cache: 100+/s

Defaults predicates do not cost too much time than ecache.Get right now.

PodFitsOnNodes which is a hot spot function, we use mutex.Lock in the this function will make it slow, especially parallel processing. 

What's the plan of equivalence cache feature? At least now，if we enable ecache which is really make the performance decline.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3
- Cloud provider or hardware configuration: linux 32cpus and 64gb mem 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Linux dev 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/sig scheduling

/assign @bsalamat 
/assign @resouer 
/assign @misterikkit

**Comment by misterikkit** [comment]
Thanks for filing this report. Could you clarify a bit about this? When you say "open" and "close" I take it you mean "enabled" and "disabled"? How are you scheduling 3000 pods - is this an integration test?

Lock contention is something we discussed recently, but clearly needs a closer examination. Our plan for equivalence cache is that it should have a positive impact on scheduling performance so we can move it to beta.

**Comment by godliness** [comment]
@misterikkit  sorry about the misundertanding，yes, it means enabled the cache and it is an integration test which is named schedule_perf and it is located in test/integration/ directory.

60+/s is based on version 1.9.3, the latest version which is in master branch only 15+/s.
The key point is when get result from cache 1.9.3 used Rlock and latest version used Lock and its range is bigger。

And i also do some cpu profile test, the lock contention is the bottleneck of cache feature。

Any help else i can do？or do you have any ideas about this？I’m just a little bit eager to know.😊

**Comment by resouer** [comment]
@godliness Unfortunately, extra locks have to be introduced recently to fix some known races in scheduler. We are having discussion on this but you can try to start with lock optimization or even remove the locks to eliminate those impacts on default scheduler.

**Comment by godliness** [comment]
@misterikkit thanks for the detail description.
Ok, I will do this and then send a pr for this.

**Comment by misterikkit** [comment]
> Ok, I will do this and then send a pr for this.

Sounds good. As @ravisantoshgudimetla mentioned, it would be good to include before and after performance details in the PR.

**Comment by resouer** [comment]
@godliness I set up two VMs on GCE with different sizes but can not re-produce this issue. Here's my test results:

```
32-Core VM on GCE

Perf:

Enable

I0519 00:46:08.409916   20978 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0519 00:46:08.410298   20978 factory.go:1066] Created equivalence class cache
0s	rate: 794	total: 794 (qps frequency: map[794:1])
1s	rate: 999	total: 1793 (qps frequency: map[794:1 999:1])
Scheduled 3000 Pods in 2 seconds (1500 per second on average). min QPS was 794
I0519 00:46:11.724452   20978 util.go:83] destroying scheduler
I0519 00:46:11.724481   20978 util.go:87] destroyed scheduler
I0519 00:46:11.724491   20978 util.go:51] destroying API server
I0519 00:46:11.727953   20978 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 794
PASS
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	6.780s

Disable

I0519 00:31:06.983558    4048 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
0s	rate: 318	total: 318 (qps frequency: map[318:1])
1s	rate: 490	total: 808 (qps frequency: map[318:1 490:1])
2s	rate: 559	total: 1367 (qps frequency: map[318:1 490:1 559:1])
3s	rate: 630	total: 1997 (qps frequency: map[490:1 559:1 630:1 318:1])
4s	rate: 617	total: 2614 (qps frequency: map[318:1 490:1 559:1 630:1 617:1])
Scheduled 3000 Pods in 5 seconds (600 per second on average). min QPS was 318
I0519 00:31:13.190942    4048 util.go:83] destroying scheduler
I0519 00:31:13.190969    4048 util.go:87] destroyed scheduler
I0519 00:31:13.190974    4048 util.go:51] destroying API server
I0519 00:31:13.193185    4048 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 318
PASS
E0519 00:31:13.193485    4048 event.go:209] Unable to write event: 'Post http://127.0.0.1:36141/api/v1/namespaces/sample/events: dial tcp 127.0.0.1:36141: connect: connection refused' (may retry after sleeping)
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	9.717s

Benchmark:

Enable

BenchmarkScheduling/1000Nodes/1000Pods-32        	     100	  50702524 ns/op	 3912885 B/op	   85740 allocs/op
BenchmarkSchedulingAntiAffinity/500Nodes/5000Pods-32        	     250	  18336367 ns/op	 2707880 B/op	   54136 allocs/op
BenchmarkScheduling/1000Nodes/0Pods-32           	     100	  54861638 ns/op	 3224870 B/op	   72515 allocs/op

Disable

BenchmarkScheduling/1000Nodes/1000Pods-32        	     100	  41608092 ns/op	 3126769 B/op	   47306 allocs/op
BenchmarkSchedulingAntiAffinity/500Nodes/5000Pods-32        	     250	  23386403 ns/op	 2634866 B/op	   40474 allocs/op
BenchmarkScheduling/1000Nodes/0Pods-32           	     100	  49283997 ns/op	 2638111 B/op	   38371 allocs/op

```

The test data shows throughput is doubled when ecache enabled, also, the op time of BenchmarkSchedulingAntiAffinity is decreased (since this predicate is complicated). And for normal BenchmarkScheduling, no notable decrease is observed (I will expect some minor decrease as we introduced a relative more complex hash function in scheduling path) , but the throughput should be the key.

Could you please share out your test methods and configure (e.g. how to enable/disable ecache) as well? I would like to re-pro it on my GCE cluster.

**Comment by godliness** [comment]
**Code base: master branch**
**Commit ID: a481f4bbe828d7fdec95782c02df3743c1020820**

**32 Core cpus** 
**64 Gb mem**
**Physical machine**

How to enable and disable the feature?
Change it to control the switch https://github.com/kubernetes/kubernetes/blob/master/test/integration/util/util.go#L98

I also changed this https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_test.go#L265

When we use Node affinity feature which is really cost time when schedule pods, because the node selector fn will calculate the match regular expression every time, so we could only move it to the metadata, let it only calculate once for all nodes. so i think this is also another performance problem for scheduler, i have fixed it base on version 1.9.3, but didn’t submit a pr yet. 

So all the above results i provided is base on NodeAffinityCount=1.

**Perf:**

**Enable**

**NodeAffinityCount=10**

```
I0519 12:21:04.537827   54442 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0519 12:21:04.538501   54442 factory.go:1066] Created equivalence class cache
0s    rate: 830    total: 830 (qps frequency: map[830:1])
1s    rate: 571    total: 1401 (qps frequency: map[830:1 571:1])
2s    rate: 485    total: 1886 (qps frequency: map[830:1 571:1 485:1])
3s    rate: 458    total: 2344 (qps frequency: map[458:1 830:1 571:1 485:1])
4s    rate: 485    total: 2829 (qps frequency: map[830:1 571:1 485:2 458:1])
Scheduled 3000 Pods in 5 seconds (600 per second on average). min QPS was 458
I0519 12:21:12.704663   54442 util.go:83] destroying scheduler
I0519 12:21:12.704705   54442 util.go:87] destroyed scheduler
I0519 12:21:12.704721   54442 util.go:51] destroying API server
I0519 12:21:12.711063   54442 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 458
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    11.656s
+++ [0519 12:21:12] ...density tests finished
/export/workspace/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0519 12:21:12] performance test cleanup complete
```

**NodeAffinityCount=1**

```
I0519 13:47:25.703168   94696 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0519 13:47:25.703784   94696 factory.go:1066] Created equivalence class cache
0s    rate: 919    total: 919 (qps frequency: map[919:1])
1s    rate: 627    total: 1546 (qps frequency: map[919:1 627:1])
2s    rate: 514    total: 2060 (qps frequency: map[919:1 627:1 514:1])
3s    rate: 459    total: 2519 (qps frequency: map[514:1 459:1 919:1 627:1])
Scheduled 3000 Pods in 4 seconds (750 per second on average). min QPS was 459
I0519 13:47:32.898686   94696 util.go:83] destroying scheduler
I0519 13:47:32.898728   94696 util.go:87] destroyed scheduler
I0519 13:47:32.898744   94696 util.go:51] destroying API server
I0519 13:47:32.903976   94696 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 459
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    11.130s
+++ [0519 13:47:32] ...density tests finished
/export/workspace/src/k8s.io/kubernetes_github_mine/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0519 13:47:33] performance test cleanup complete

```
**Disable**

**NodeAffinityCount=10**

```
I0519 13:07:45.962997   65060 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
0s    rate: 763    total: 763 (qps frequency: map[763:1])
1s    rate: 635    total: 1398 (qps frequency: map[763:1 635:1])
2s    rate: 624    total: 2022 (qps frequency: map[763:1 635:1 624:1])
3s    rate: 637    total: 2659 (qps frequency: map[637:1 763:1 635:1 624:1])
Scheduled 3000 Pods in 4 seconds (750 per second on average). min QPS was 624
I0519 13:07:53.153165   65060 util.go:83] destroying scheduler
I0519 13:07:53.153193   65060 util.go:87] destroyed scheduler
I0519 13:07:53.153266   65060 util.go:51] destroying API server
I0519 13:07:53.175787   65060 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 624
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    11.119s
+++ [0519 13:07:53] ...density tests finished
/export/workspace/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0519 13:07:53] performance test cleanup complete
```

**NodeAffinityCount=1**

```
I0519 13:20:02.165461   92711 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
0s    rate: 2348    total: 2348 (qps frequency: map[2348:1])
Scheduled 3000 Pods in 1 seconds (3000 per second on average). min QPS was 2348
I0519 13:20:06.268803   92711 util.go:83] destroying scheduler
I0519 13:20:06.268852   92711 util.go:87] destroyed scheduler
I0519 13:20:06.268869   92711 util.go:51] destroying API server
I0519 13:20:06.273953   92711 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 2348
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    8.244s
+++ [0519 13:20:06] ...density tests finished
/export/workspace/src/k8s.io/kubernetes_github_mine/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0519 13:20:06] performance test cleanup complete
```

**Comment by resouer** [comment]
> Edit: From your benchmark test the op is quicker when disable the ecache, but the rate is quicker which is 1500/s, is this schedule 3000 pods on 100 nodes? if the nodes count is lower then the rate is quicker.

It's across comparison and this test result has been re-produced on 100, 1k and 3k nodes. 

> NodeAffinityCount=10

Sorry, I am not quite understand what you are referring to here ... do you mean `LabelCount` of node affinity in test? 

Before we can move on, it's important that we have the same baseline in this discussion :-)

**Comment by resouer** [comment]
If it's the `LabelCount ` case, we should know that equivalence class cache is designed to improve throughput when certain predicates are expensive, for example, if 100 affinity labels are present on a node (it's common in a real world deployment):

```
Enabled: 

I0519 21:27:12.983564   14792 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0519 21:27:12.983892   14792 factory.go:1066] Created equivalence class cache
I0519 21:27:13.637408   14792 trace.go:76] Trace[1316009554]: "Scheduling sample/sched-perf-pod-jgsgg" (started: 2018-05-19 21:27:13.398641514 +0000 UTC m=+3.842087
377) (total time: 238.729364ms):
Trace[1316009554]: [238.359527ms] [236.318451ms] Prioritizing
0s      rate: 103       total: 103 (qps frequency: map[103:1])
1s      rate: 426       total: 529 (qps frequency: map[103:1 426:1])
2s      rate: 368       total: 897 (qps frequency: map[103:1 426:1 368:1])
...
Scheduled 3000 Pods in 8 seconds (375 per second on average). min QPS was 103

Disabled:

I0519 21:21:03.185838   11767 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
0s      rate: 37        total: 37 (qps frequency: map[37:1])
1s      rate: 83        total: 120 (qps frequency: map[37:1 83:1])
2s      rate: 52        total: 172 (qps frequency: map[37:1 83:1 52:1])
...
Scheduled 3000 Pods in 58 seconds (51 per second on average). min QPS was 37
Warning: pod scheduling throughput for 3k pods was slow for an interval... Saw a interval with very low (37) scheduling rate!PASS
```
This also applies to machines which are compact (e.g. 8 core VM).

So the lesson is: maybe we can bypass ecache in some edge cases? cc @misterikkit . Related discussion: https://github.com/kubernetes/kubernetes/issues/58507#issuecomment-359330135

We should also add more tests in `scheduler_perf` for various test cases.

**Comment by godliness** [comment]
@resouer 

Really thanks about the professional analysis. This is very useful to me, also learnt some.

Yes it means LabelCount, When i set it as 1, this is an edge case and all the default predicates does not cost time. In our case when use scheduler we only use the default predicates without node affinity feature or with minor LabelCount. So i make this edge test case which i should say it in this issue at first.

I  did not re-produced your rest result(with default predicates) when enable the ecache.
Maybe as you said, this is depends on the machine. 
I can provide my machine info, hope this can provide some useful information:

[info.txt](https://github.com/kubernetes/kubernetes/files/2019943/info.txt)

**Comment by godliness** [comment]
Tested in my local mac:

GoVersion: go1.10.2

Cpu: 8 cores

Mem: 16GB

Enable

Node Affinity Label Count = 10
```
I0520 20:42:10.845118   52665 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0520 20:42:10.845475   52665 factory.go:1066] Created equivalence class cache
0s    rate: 311    total: 311 (qps frequency: map[311:1])
1s    rate: 746    total: 1057 (qps frequency: map[311:1 746:1])
2s    rate: 729    total: 1786 (qps frequency: map[311:1 746:1 729:1])
3s    rate: 739    total: 2525 (qps frequency: map[311:1 746:1 729:1 739:1])
Scheduled 3000 Pods in 4 seconds (750 per second on average). min QPS was 311
I0520 20:42:16.557619   52665 util.go:83] destroying scheduler
I0520 20:42:16.557641   52665 util.go:87] destroyed scheduler
I0520 20:42:16.557648   52665 util.go:51] destroying API server
I0520 20:42:16.559211   52665 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 311
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    9.132s
+++ [0520 20:42:16] ...density tests finished
~/Projects/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0520 20:42:16] performance test cleanup complete
```

Node Affinity Label Count = 1

```
I0520 20:47:50.043671   54050 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:true]
I0520 20:47:50.044013   54050 factory.go:1066] Created equivalence class cache
0s    rate: 286    total: 286 (qps frequency: map[286:1])
1s    rate: 775    total: 1061 (qps frequency: map[286:1 775:1])
2s    rate: 758    total: 1819 (qps frequency: map[775:1 758:1 286:1])
3s    rate: 785    total: 2604 (qps frequency: map[286:1 775:1 758:1 785:1])
Scheduled 3000 Pods in 4 seconds (750 per second on average). min QPS was 286
I0520 20:47:55.440341   54050 util.go:83] destroying scheduler
I0520 20:47:55.440365   54050 util.go:87] destroyed scheduler
I0520 20:47:55.440375   54050 util.go:51] destroying API server
I0520 20:47:55.441491   54050 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 286
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    8.817s
+++ [0520 20:47:55] ...density tests finished
~/Projects/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0520 20:47:55] performance test cleanup complete
```

Disable

Node Affinity Label Count = 10
```
I0520 20:43:55.619889   53062 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
W0520 20:43:56.488612   53062 watcher.go:235] Fast watcher, slow processing. Number of buffered events: 100.Probably caused by slow dispatching events to watchers
0s    rate: 146    total: 146 (qps frequency: map[146:1])
1s    rate: 520    total: 666 (qps frequency: map[146:1 520:1])
2s    rate: 543    total: 1209 (qps frequency: map[146:1 520:1 543:1])
3s    rate: 542    total: 1751 (qps frequency: map[146:1 520:1 543:1 542:1])
4s    rate: 535    total: 2286 (qps frequency: map[146:1 520:1 543:1 542:1 535:1])
5s    rate: 526    total: 2812 (qps frequency: map[542:1 535:1 526:1 146:1 520:1 543:1])
Scheduled 3000 Pods in 6 seconds (500 per second on average). min QPS was 146
I0520 20:44:03.181282   53062 util.go:83] destroying scheduler
I0520 20:44:03.181311   53062 util.go:87] destroyed scheduler
I0520 20:44:03.181322   53062 util.go:51] destroying API server
I0520 20:44:03.184132   53062 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 146
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    10.984s
+++ [0520 20:44:03] ...density tests finished
~/Projects/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0520 20:44:03] performance test cleanup complete
```

Node Affinity Label Count = 1

```
I0520 20:46:06.524906   53631 feature_gate.go:190] feature gates: map[EnableEquivalenceClassCache:false]
0s    rate: 390    total: 390 (qps frequency: map[390:1])
1s    rate: 1392    total: 1782 (qps frequency: map[1392:1 390:1])
Scheduled 3000 Pods in 2 seconds (1500 per second on average). min QPS was 390
I0520 20:46:09.982991   53631 util.go:83] destroying scheduler
I0520 20:46:09.983014   53631 util.go:87] destroyed scheduler
I0520 20:46:09.983020   53631 util.go:51] destroying API server
I0520 20:46:09.987019   53631 util.go:53] destroyed API server
Minimal observed throughput for 3k pod test: 390
PASS
ok      k8s.io/kubernetes/test/integration/scheduler_perf    6.871s
+++ [0520 20:46:10] ...density tests finished
~/Projects/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_perf
+++ [0520 20:46:10] performance test cleanup complete
```

**Comment by ravisantoshgudimetla** [comment]
The data I provided is not of benchmark but for scheduler_perf without node affinity(default predicates). So, if this is expected performance degradation as we discussed at https://github.com/kubernetes/kubernetes/issues/63784#issuecomment-39043495, are we ok with that?

**Comment by resouer** [comment]
Thanks, I think the issue is clear to me. I will propose some change to make ecache perform consistent for both simple or complicated predicates by measure performance before cache in runtime.

**Comment by bsalamat** [comment]
Today, I ran scheduler benchmarks with the HEAD and I also noticed significant performance degradation when eCache is enabled. It looks like a lot of our threads are stuck at looking up eCache. Since we run predicates in 16 parallel threads and eCache has single global lock, this may be expected.
I tried running the benchmarks with 5000 nodes and 10000 pods. In order to do, I had to change [here](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_bench_test.go#L38) and use the following command:

```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_ARGS="-run=xxx -bench=.*BenchmarkScheduling.* -cpuprofile cpu-5000n-10000p.out"
```

@resouer and @misterikkit, it would be great if you guys could take a look.

**Comment by resouer** [comment]
Thanks @bsalamat , Yes, I also noticed the lock in ecache should be the concern. We are still actively on this issue.

**Comment by resouer** [comment]
@godliness If you are still interested in this issue, would be great if you can try with the HEAD to see how  #65714 is doing.

**Comment by godliness** [comment]
@resouer ok, i will try it! thx!!
