### ISSUE TITLE
deployment roll update : can't pull images  wrong!

### ISSUE THREAD

**Issue by chenxushuo** [kubernetes/kubernetes#63781]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
today,wen i roll update my deployment,one pod had some wrong to pull new images; and then kubernetes  didn't  start a new pod for roll update;deployment skip this wrong pod and go on update old pod ; when all old pod rolled update,the wrong pod also in deployment.
I think：
deployment  should care the pod health when roll update;and must take off  all wrong pod and choose health node start new pod；
Isn't It？

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
Please ask on stackoverflow, Discuss ( https://discuss.kubernetes.io/ ), on kubernetes-users slack channel.

/close

**Comment by chenxushuo** [comment]
OK ， thank you everyone！
