### ISSUE TITLE
kubeadm init fails

### ISSUE THREAD

**Issue by andreimoraru** [kubernetes/kubernetes#63796]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
`kubeadm init --pod-network-cidr=10.244.0.0/16`    fails with message:

`Unfortunately, an error has occurred:
timed out waiting for the condition
`

**What you expected to happen**:
cluster to be initialized
**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init --pod-network-cidr=10.244.0.0/16

**Anything else we need to know?**:

Swap is off

docker version
`root@amoraru6:/home/user# docker info | grep -i version
Server Version: 17.03.2-ce
`
**Environment**:
- Kubernetes version (use `kubectl version`):
`root@amoraru6:/home/user# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?`
- Cloud provider or hardware configuration:
EC2
- OS (e.g. from /etc/os-release):
`root@amoraru6:/home/user# cat /etc/debian_version
9.4`
- Kernel (e.g. `uname -a`):
`root@amoraru6:/home/user# uname -a
Linux amoraru6.mylabserver.com 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`
- Install tools:
Installed docker-ce, kubeadm, kubectl and kubelet according to https://kubernetes.io/docs/setup/independent/install-kubeadm/
- Others:
I noticed that API server container is re-created once in a minute and here are the logs from it:

`root@amoraru6:/home/user# docker logs -f k8s_kube-apiserver_kube-apiserver-amoraru6.mylabserver.com_kube-system_b5277ba610b6b6a77e70d61371dc2fee_15
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
I0514 12:47:17.471884       1 server.go:135] Version: v1.10.2
I0514 12:47:17.472153       1 server.go:724] external host was not specified, using 172.31.114.153
I0514 12:47:28.117443       1 plugins.go:149] Loaded 9 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota.
I0514 12:47:28.118334       1 plugins.go:149] Loaded 9 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota.
I0514 12:47:28.322988       1 master.go:228] Using reconciler: master-count
W0514 12:47:29.836173       1 genericapiserver.go:342] Skipping API batch/v2alpha1 because it has no resources.
W0514 12:47:30.124451       1 genericapiserver.go:342] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W0514 12:47:30.163180       1 genericapiserver.go:342] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W0514 12:47:30.284665       1 genericapiserver.go:342] Skipping API admissionregistration.k8s.io/v1alpha1 because it has no resources.
[restful] 2018/05/14 12:47:30 log.go:33: [restful/swagger] listing is available at https://172.31.114.153:6443/swaggerapi
[restful] 2018/05/14 12:47:30 log.go:33: [restful/swagger] https://172.31.114.153:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/05/14 12:47:56 log.go:33: [restful/swagger] listing is available at https://172.31.114.153:6443/swaggerapi
[restful] 2018/05/14 12:47:56 log.go:33: [restful/swagger] https://172.31.114.153:6443/swaggerui/ is mapped to folder /swagger-ui/
I0514 12:47:56.719085       1 plugins.go:149] Loaded 9 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota.
I0514 12:48:51.759876       1 serve.go:96] Serving securely on [::]:6443
I0514 12:48:51.802499       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48366: EOF
I0514 12:48:51.802808       1 crd_finalizer.go:242] Starting CRDFinalizer
I0514 12:48:51.802842       1 crd_finalizer.go:246] Shutting down CRDFinalizer
I0514 12:48:51.803379       1 apiservice_controller.go:90] Starting APIServiceRegistrationController
I0514 12:48:51.803424       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
E0514 12:48:51.803452       1 cache.go:35] Unable to sync caches for APIServiceRegistrationController controller
I0514 12:48:51.803472       1 apiservice_controller.go:94] Shutting down APIServiceRegistrationController
I0514 12:48:51.840493       1 available_controller.go:262] Starting AvailableConditionController
I0514 12:48:51.840589       1 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
E0514 12:48:51.840626       1 cache.go:35] Unable to sync caches for AvailableConditionController controller
I0514 12:48:51.840649       1 available_controller.go:266] Shutting down AvailableConditionController
I0514 12:48:51.840677       1 controller.go:84] Starting OpenAPI AggregationController
I0514 12:48:51.840697       1 controller.go:90] Shutting down OpenAPI AggregationController
I0514 12:48:51.925208       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45394: EOF
I0514 12:48:51.965542       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45396: EOF
I0514 12:48:52.088308       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45400: EOF
I0514 12:48:52.128881       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45402: EOF
I0514 12:48:52.170112       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45404: EOF
I0514 12:48:52.211356       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45406: EOF
I0514 12:48:52.331668       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45410: EOF
I0514 12:48:52.374543       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45412: EOF
I0514 12:48:52.415167       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45414: EOF
I0514 12:48:52.459770       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45416: EOF
I0514 12:48:52.578449       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45420: EOF
I0514 12:48:52.619325       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45424: EOF
I0514 12:48:52.660479       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45426: EOF
I0514 12:48:52.701227       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45428: EOF
I0514 12:48:52.741936       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45450: EOF
I0514 12:48:52.783212       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45452: EOF
I0514 12:48:52.823939       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45454: EOF
I0514 12:48:52.868551       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45462: EOF
I0514 12:48:52.951329       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45478: EOF
I0514 12:48:52.991779       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45480: EOF
I0514 12:48:53.032400       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45508: EOF
I0514 12:48:53.113587       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45512: EOF
I0514 12:48:53.198639       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45528: EOF
I0514 12:48:53.279832       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45618: EOF
I0514 12:48:53.320181       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45856: EOF
I0514 12:48:53.360792       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45950: EOF
I0514 12:48:53.401485       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45952: EOF
I0514 12:48:53.524633       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45956: EOF
I0514 12:48:53.565246       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45960: EOF
I0514 12:48:53.606294       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45962: EOF
I0514 12:48:53.647206       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45964: EOF
I0514 12:48:53.687886       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45966: EOF
I0514 12:48:53.733850       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45968: EOF
I0514 12:48:53.815004       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45970: EOF
I0514 12:48:53.896877       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45974: EOF
I0514 12:48:53.978338       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45980: EOF
I0514 12:48:54.018450       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46100: EOF
I0514 12:48:54.063137       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46132: EOF
I0514 12:48:54.182200       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46354: EOF
I0514 12:48:54.222905       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46356: EOF
I0514 12:48:54.264161       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46382: EOF
I0514 12:48:54.304718       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46384: EOF
I0514 12:48:54.345503       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46386: EOF
I0514 12:48:54.386207       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46388: EOF
I0514 12:48:54.431889       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46390: EOF
I0514 12:48:54.472544       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46406: EOF
I0514 12:48:54.513341       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46408: EOF
I0514 12:48:54.632720       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46412: EOF
I0514 12:48:54.636434       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46468: EOF
I0514 12:48:54.714653       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46470: EOF
I0514 12:48:54.755592       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46500: EOF
I0514 12:48:54.800952       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46712: EOF
I0514 12:48:54.841702       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46748: EOF
I0514 12:48:54.882133       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46750: EOF
I0514 12:48:54.922749       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46878: EOF
I0514 12:48:55.044222       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46882: EOF
I0514 12:48:55.085607       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46884: EOF
I0514 12:48:55.126622       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46886: EOF
I0514 12:48:55.171503       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46888: EOF
I0514 12:48:55.212054       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46890: EOF
I0514 12:48:55.252557       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46892: EOF
I0514 12:48:55.293746       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46894: EOF
I0514 12:48:55.334390       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46896: EOF
I0514 12:48:55.374968       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46898: EOF
I0514 12:48:55.415572       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46900: EOF
I0514 12:48:55.456106       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46902: EOF
I0514 12:48:55.501086       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46908: EOF
I0514 12:48:55.537663       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47156: EOF
I0514 12:48:55.582024       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47318: EOF
I0514 12:48:55.622940       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47320: EOF
I0514 12:48:55.664495       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47324: EOF
I0514 12:48:55.704778       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47326: EOF
I0514 12:48:55.745635       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47328: EOF
I0514 12:48:55.864138       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47332: EOF
I0514 12:48:55.904929       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47334: EOF
I0514 12:48:55.950348       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47350: EOF
I0514 12:48:55.990885       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47352: EOF
I0514 12:48:56.034130       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47368: EOF
I0514 12:48:56.115455       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47392: EOF
I0514 12:48:56.156434       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47396: EOF
I0514 12:48:56.196797       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47440: EOF
I0514 12:48:56.237749       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47570: EOF
I0514 12:48:56.277908       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47742: EOF
I0514 12:48:56.363443       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47822: EOF
I0514 12:48:56.403952       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47824: EOF
I0514 12:48:56.444335       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47826: EOF
I0514 12:48:56.485547       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47828: EOF
I0514 12:48:56.526175       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47830: EOF
I0514 12:48:56.567028       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47832: EOF
I0514 12:48:56.607440       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47834: EOF
I0514 12:48:56.688406       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47836: EOF
I0514 12:48:56.774087       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47842: EOF
I0514 12:48:56.814780       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47858: EOF
I0514 12:48:56.855478       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47860: EOF
I0514 12:48:56.896186       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47880: EOF
I0514 12:48:56.936906       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47974: EOF
I0514 12:48:57.014982       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48010: EOF
I0514 12:48:57.058456       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48154: EOF
I0514 12:48:57.182485       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48268: EOF
I0514 12:48:57.223125       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48270: EOF
I0514 12:48:57.263902       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48272: EOF
I0514 12:48:57.304548       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48274: EOF
I0514 12:48:57.346258       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48290: EOF
I0514 12:48:57.391595       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48292: EOF
I0514 12:48:57.432529       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48294: EOF
I0514 12:48:57.473041       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48296: EOF
I0514 12:48:57.514015       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48298: EOF
I0514 12:48:57.554376       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48300: EOF
I0514 12:48:57.594958       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48328: EOF
I0514 12:48:57.632501       1 serve.go:136] Stopped listening on [::]:6443
I0514 12:48:57.675202       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48434: EOF
I0514 12:48:57.675287       1 customresource_discovery_controller.go:174] Starting DiscoveryController
E0514 12:48:57.675327       1 customresource_discovery_controller.go:177] timed out waiting for caches to sync
I0514 12:48:57.675349       1 customresource_discovery_controller.go:178] Shutting down DiscoveryController
I0514 12:48:57.675401       1 naming_controller.go:276] Starting NamingConditionController
I0514 12:48:57.675427       1 naming_controller.go:280] Shutting down NamingConditionController
I0514 12:48:57.715991       1 crdregistration_controller.go:110] Starting crd-autoregister controller
I0514 12:48:57.716071       1 controller_utils.go:1019] Waiting for caches to sync for crd-autoregister controller
E0514 12:48:57.716103       1 controller_utils.go:1022] Unable to sync caches for crd-autoregister controller
I0514 12:48:57.716126       1 crdregistration_controller.go:115] Shutting down crd-autoregister controller
I0514 12:48:57.760011       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45392: EOF
I0514 12:48:57.799061       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45398: EOF
I0514 12:48:57.799485       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45408: EOF
I0514 12:48:57.800333       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45418: EOF
I0514 12:48:57.839634       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45476: EOF
I0514 12:48:57.840497       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45510: EOF
I0514 12:48:57.842307       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45526: EOF
I0514 12:48:57.842465       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45558: EOF
I0514 12:48:57.881119       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45954: EOF
I0514 12:48:57.883945       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45972: EOF
I0514 12:48:57.922982       1 logs.go:49] http: TLS handshake error from 172.31.114.153:45976: EOF
I0514 12:48:57.923755       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46316: EOF
I0514 12:48:57.961526       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46410: EOF
I0514 12:48:57.962384       1 logs.go:49] http: TLS handshake error from 172.31.114.153:46880: EOF
I0514 12:48:57.962728       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47330: EOF
I0514 12:48:57.963213       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47370: EOF
I0514 12:48:57.964257       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47820: EOF
I0514 12:48:58.004206       1 logs.go:49] http: TLS handshake error from 172.31.114.153:47838: EOF
I0514 12:48:58.004674       1 logs.go:49] http: TLS handshake error from 172.31.114.153:48266: EOF
E0514 12:48:58.086989       1 storage_rbac.go:157] unable to initialize clusterroles: Get https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/clusterroles: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0514 12:48:58.129283       1 client_ca_hook.go:78] Post https://127.0.0.1:6443/api/v1/namespaces: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0514 12:48:58.129524       1 storage_rbac.go:157] unable to initialize clusterroles: Get https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/clusterroles: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0514 12:48:58.868302       1 storage_rbac.go:157] unable to initialize clusterroles: Get https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/clusterroles: dial tcp 127.0.0.1:6443: getsockopt: connection refused
E0514 12:48:58.868674       1 client_ca_hook.go:78] Post https://127.0.0.1:6443/api/v1/namespaces: dial tcp 127.0.0.1:6443: getsockopt: connection refused
`

**Comment by dims** [comment]
@andreimoraru needs to be in https://github.com/kubernetes/kubeadm/issues please

/close
