### ISSUE TITLE
kubectl auth can-i return "yes" and exit code 0 querying non-existent resources

### ISSUE THREAD

**Issue by fbac** [kubernetes/kubernetes#63791]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kubectl auth can-i return yes and exit code 0 when querying about  non-existent resources.

> ./kubectl auth can-i get foo
Warning: the server doesn't have a resource type 'foo'
yes

> echo $?
0

**What you expected to happen**:
kubectl auth can-i should return the warning message and exit code 1.

**How to reproduce it (as minimally and precisely as possible)**:
- Login in kubernetes.
- Run kubectl auth can-i get foo

**Environment**:
kubernetes v1.9.1+a0ce1bc657
kubectl v1.11.0-alpha.2.329+9fa269a5e5e8ce
Most probably, reproducible in all versions.

**Comment by rajatjindal** [comment]
looks like it was intentional 

https://github.com/kubernetes/kubernetes/pull/42144

**Comment by liggitt** [comment]
yes, the authorization layer is agnostic to verbs and resources... it treats them as opaque tokens it checks against the configured authorizers

/close
