### ISSUE TITLE
Downward API metadata.uid does not work

### ISSUE THREAD

**Issue by karolz-ms** [kubernetes/kubernetes#63809]
/kind bug

**What happened**:
Attempted to inject pod UID as environment variable into one of the containers in my pod. I see the following in the `env` section of the container inside the running pod (viewing in K8s dashboard) 

```json
         {
            "name": "POD_ID",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.uid"
              }
            }
          }
```
but the environment variable is empty (this is the output of `kubectl describe pod`:
  
  POD_ID:                  (v1:metadata.uid)

**What you expected to happen**:
The POD_ID variable should be set to the pod UID

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a deployment that deploys 1 instance of a container with an environment variable set as above
2. Check the value of the POD_ID environment variable in the deployed container

**Anything else we need to know?**:
The pod UID is visible using `kubectl get pod pod-name -o yaml`
 
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure/AKS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by karolz-ms** [comment]
@kubernetes/sig-apps-bugs please take a look--thx!

**Comment by karolz-ms** [comment]
Interestingly when I exec into the container, the environment variable seems to be set correctly with pod UID. So it seems to be the K8s dashboard/kubectl problem.

**Comment by liggitt** [comment]
the downward API does not update the API object, it only populates the environment variable inside the running container

/close
