### ISSUE TITLE
Failed to get system container stats for "/system.slice/kubelet.service"

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/kubernetes#63804]
/kind bug

**What happened**:
The nodes seems died with bunch of error logs below
```
May 11 19:25:35 ip-xx-xxx-xx-xxx kubelet[2583]: E0511 19:25:35.523245    2583 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
May 11 19:25:35 ip-xx-xxx-xx-xxx kubelet[2583]: E0511 19:25:35.523270    2583 summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
May 11 19:25:45 ip-xx-xxx-xx-xxx kubelet[2583]: E0511 19:25:45.531212    2583 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
May 11 19:25:45 ip-xx-xxx-xx-xxx kubelet[2583]: E0511 19:25:45.531237    2583 summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
May 11 19:25:45 ip-xx-xxx-xx-xxx systemd[1]: Starting Run docker-healthcheck once...
May 11 19:25:45 ip-xx-xxx-xx-xxx docker-healthcheck[25460]: docker healthy
```
That caused the node with error message as `container runtime is down,PLEG is not healthy: pleg was last seen active 2h15m25.650316157s ago; threshold is 3m0s`

On the apps side, we have seen, `java.lang.OutOfMemoryError: unable to create new native thread`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian Jessie
- Kernel (e.g. `uname -a`): 4.4.115-k8s
- Install tools: kops 1.9.0
- CNI: Weave (weaveworks/weave-kube:2.3.0)

**Comment by qiyongxiao** [comment]
hello, I get the same issues on k8s-1.10.3 and docker-1.13.1
`May 31 14:39:56 kubernetes-master03v.azurecnn.juejin.id kubelet[15447]: E0531 14:39:56.969090   15447 summary.go:102] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"`

**Comment by prashantabkari** [comment]
+1 Same issue.

**Comment by imranrazakhan** [comment]
E0730 17:01:15.217272    1555 summary.go:92] Failed to get system container stats for "/user.slice/user-1000.slice/session-1.scope": failed to get cgroup stats for "/user.slice/user-1000.slice/session
-1.scope": failed to get container info for "/user.slice/user-1000.slice/session-1.scope": unknown container "/user.slice/user-1000.slice/session-1.scope"
E0730 17:01:15.217298    1555 summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get conta
iner info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
