### ISSUE TITLE
Kube-proxy ipvs support does not work when ipvs compiled into kernel rather than modules

### ISSUE THREAD

**Issue by detiber** [kubernetes/kubernetes#63801]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Deploying kube-proxy with mode ipvs on a system with the required ipvs support compiled into the kernel rather than as modules causes the kube-proxy deployment to fall back to using iptables.

```sh
# kubectl logs -n kube-system `kubectl get pods -n kube-system -l "k8s-app=kube-proxy" -o name`
I0514 13:55:14.505765       1 feature_gate.go:226] feature gates: &{{} map[]}
E0514 13:55:16.139837       1 server_others.go:304] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_sh nf_conntrack_ipv4 ip_vs ip_vs_rr ip_vs_wrr]
I0514 13:55:16.524562       1 server_others.go:140] Using iptables Proxier.
I0514 13:55:16.625142       1 server_others.go:174] Tearing down inactive rules.
I0514 13:55:17.838932       1 server.go:444] Version: v1.10.2
```

tryIPVSProxy is only checking for the presence of kernel modules and not if the running kernel has the required support compiled in.

**What you expected to happen**:

tryIPVSProxy should succeed if either the required modules are found or support is compiled into the running kernel.

**How to reproduce it (as minimally and precisely as possible)**:

- Boot a system using a kernel with ipvs support compiled in rather than as a module (such as the kernel used by [LinuxKit](https://github.com/linuxkit/linuxkit) and a host without iptables installed
- Add --config=/etc/kubernetes/kubelet-config.yaml to the kubelet arguments using the following kubelet-config.yaml contents:
  ```sh
  kind: KubeletConfiguration
  apiVersion: kubelet.config.k8s.io/v1beta1
  staticPodPath: /etc/kubernetes/manifests
  clusterDomain: cluster.local
  clusterDNS:
    - 10.96.0.10
  makeIPTablesUtilChains: false
  ```
- Install using kubeadm with the following config:
  ```sh
  apiVersion: kubeadm.k8s.io/v1alpha1
  kind: MasterConfiguration
  kubeProxy:
    config:
      mode: ipvs
  ```
- Check the output of the kube-proxy pod: 
  ```
  kubectl logs -n kube-system `kubectl get pods -n kube-system -l "k8s-app=kube-proxy" -o name`
  ```

**Anything else we need to know?**:

From https://superuser.com/a/729474, it should be possible to check for the existence of modules.builtin and if present use that in addition to using modprobe and the contents of /proc/modules.

```
# grep -e ipvs -e nf_conntrack_ipv4 /lib/modules/$(uname -r)/modules.builtin
kernel/net/ipv4/netfilter/nf_conntrack_ipv4.ko
kernel/net/netfilter/xt_ipvs.ko
kernel/net/netfilter/ipvs/ip_vs.ko
kernel/net/netfilter/ipvs/ip_vs_rr.ko
kernel/net/netfilter/ipvs/ip_vs_wrr.ko
kernel/net/netfilter/ipvs/ip_vs_lc.ko
kernel/net/netfilter/ipvs/ip_vs_wlc.ko
kernel/net/netfilter/ipvs/ip_vs_fo.ko
kernel/net/netfilter/ipvs/ip_vs_ovf.ko
kernel/net/netfilter/ipvs/ip_vs_lblc.ko
kernel/net/netfilter/ipvs/ip_vs_lblcr.ko
kernel/net/netfilter/ipvs/ip_vs_dh.ko
kernel/net/netfilter/ipvs/ip_vs_sh.ko
kernel/net/netfilter/ipvs/ip_vs_sed.ko
kernel/net/netfilter/ipvs/ip_vs_nq.ko
kernel/net/netfilter/ipvs/ip_vs_ftp.ko
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration: local kvm host
- OS (e.g. from /etc/os-release): custom linuxkit build
- Kernel (e.g. `uname -a`): Linux linuxkit-b67dc0805fa9 4.14.40-linuxkit #1 SMP Thu May 10 10:06:57 UTC 2018 x86_64 Linux
- Install tools: kubeadm

**Comment by dims** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
cc @islinwb, please take a look.
