### ISSUE TITLE
kubelet's calculation of whether a container has changed can cause cluster-wide outages

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#63814]
Updated 2020-11-09 by @liggitt:

In 1.16+, the kubelet hashes the serialized container spec:

1. API server sends data
    * Defaults for added fields will modify this data
    * If an alpha field that is not defaulted graduates to adding a default in beta, an API server upgrade from alpha->beta will modify this data
    * https://github.com/kubernetes/kubernetes/blob/5f1e5cafd33a8863c5dfe9f36c9cba836f0e981b/pkg/apis/core/v1/defaults_test.go#L165-L167
2. Kubelet decodes that data into its v1.Container struct
    * If the kubelet is older than the API server, this means it will drop fields added in newer API server versions
3. Kubelet encodes that v1.Container struct to JSON and hashes that data
    * https://github.com/kubernetes/kubernetes/blob/5f1e5cafd33a8863c5dfe9f36c9cba836f0e981b/pkg/kubelet/container/helpers.go#L98-L108

This mechanism is used by the kubelet in `containerChanged` and `getStableKey`, which means an API server upgrade that starts defaulting a container field graduating from alpha will instantly modify the computed hash and trigger a container restart. This results in simultaneous restart of all containers across all pods of a replicaset and can cause outages.

The kubelet should limit the fields it considers in the container hash to the ones it expects to be able to change in ways that would affect the running container (currently just `image`, I think). The pod uid is already included in `getStableKey` so a delete/recreate of the entire pod would already compute a different key.

Changing this mechanism on a minor version boundary (to improve the interactions with the API server changes in 1) is acceptable, because pods are expected to be drained as part of that upgrade (xref https://github.com/kubernetes/website/issues/12326#issuecomment-704469840)

-----------

Original description:

Kubelet hashes the container spec and store it with the container so that it can detect whether the container meets the current spec. If the hashes do not match, kubelet would kill the container and create a new one. The most notable side effect of this mechanism is that if a new field is added to the container spec in the 1.x kubernetes version, and kubelet is upgraded to 1.x from 1.x-1 version, all containers created by the 1.x-1 version kubelet will be killed.

This issue has come up quiet a few time before (see #53644), and discussed extensively in #23104. It was punted a few times because 1) in-place upgrade of kubelet was not officially supported, and 2) upgrading docker used to require restarting all the containers too. Now that upgrade is managed by the installers (https://github.com/kubernetes/kubernetes/issues/6099#issuecomment-359331190) and docker supports live-restore, we should consider fixing this in kubelet.

There are related discussions/suggestions the #57741 PR already. Creating this issue as a centralized place for discussions and suggestions.

/cc @kubernetes/sig-node-feature-requests 
/cc a couple of folks who have expressed interests in this issue: @dixudx @kevin-wangzefeng @wackxu

**Comment by lichuqiang** [comment]
As @lavalamp suggested in #23104, instead of hash the whole container spec, can we maintain a list of container fields of different releases that should be taken into consideration during hash, and identify the hash values with release prefix?
The field list may looks like:
```
release1: {field1, field2...fieldN}
release2: {field1, field2...fieldN, fieldN+1}
```
and imagine the kubelet has been upgraded to release2 (new container field `fieldN+1`  added), when walking through the pods, if it found a container has a hash with a prefix of "release1", then it knows the container should be hashed with the fields of release1, thus, the result hash would not change.

And if the users have an update on a pod or its deployment, then the pod is expected to be recreated, thus, the fields of new release begin to take effect.

The only downside I can think of is that we might need to maintain the field list manually (e.g deprecate the field of old releases).

**Comment by dixudx** [comment]
> can we maintain a list of container fields of different releases that should be taken into consideration during hash

That means we have to hard code this. I don't like this way.

As I mentioned in [#57741](https://github.com/kubernetes/kubernetes/pull/57741#issuecomment-356196638), how about a new label, like `containerSerializedSpecLabel `, with backwards compatibility supported as well.

**Comment by kevin-wangzefeng** [comment]
> As I mentioned in #57741, how about adding a new label, like `containerSerializedSpecLabel`, with backwards compatibility supported as well.

We don't have field level versioning for kubernetes api today, so it won't help (kubelet itself has no idea which version a field is introduced or changed).

If we have to go with the field label approach, adding a version indicator might help:
For example 

```go
type Container struct {
    foo string `containerSerializedSpecLabel:"since v1.9"`
    bar string `containerSerializedSpecLabel:"since v1.10"`
}
```
Then, `foo` will be included for checking container hash like "v1.9-xxxxxxxx" 
`foo` and `bar` will be included for checking container hash like "v1.10-xxxxxxxx"

TBO, I don't see many benefits than having a container fields list const some where in pkg/kubelet,(e.g. in `pkg/kubelet/container/helpers.go`)

**Comment by bgrant0607** [comment]
Another problem with comparing hashes across versions is changes to the hash function.

Similar issues have come up in workload controllers, where they are used for collision avoidance only, for these types of reasons. 

Persisted hashes shouldn't be used as the sole determination of equality, since there are multiple reasons why they may change across releases.

If a hash comparison fails, one needs to fall back to actually comparing properties that matter. 

cc @janetkuo @kow3ns

**Comment by lavalamp** [comment]
You can solve it with hashes, but you need to hash whitelisted fields (NOT
the encoded object), store every iteration of the hash function, and
understand a vector of hashes (i.e., one label per iteration of the hash
function) instead of a single hash.

**Comment by cuericlee** [comment]
In order to fix this issue, I suppose PR #57741 help to omit nil/empty filed from now on, even new filed was added in the future. I will prevent restarting container continues. we need to make decision to close this kind of issue since 1.8.x -> 1.9.x, 1.11.x -> 1.12.x and so on.
It does not help for migration immediately to omit nil/empty filed, but if it go into 1.16.x from now on, it will help on future upgrade from 1.16.x -> 1.17.x and so on.

**Comment by Crazykev** [comment]
Is this a proper time to re-consider this issue, find a one-time fix? 

We still struggle from container restart when trying to upgrade our 1.15.x cluster, backport #57741 won't help since itself would bring a hash change.
And #57741 can't deal with new added filed with default value(and maybe delete desperated field in the furture).  Nil default proposed in https://github.com/kubernetes/community/pull/4571 may help fix this issue forever with #57741, but it seems discussion moved to another approach(use generation or server side apply), which can't apply in this situation.

`containerSerializedSpecLabel` approach @liggitt @dixudx proposed in https://github.com/kubernetes/kubernetes/pull/57741#issuecomment-356196638 make sense to me. Backwards compatibility can be done with serialize the current container spec and deserialize into a legacy container spec which we previously stored for compatibility. This will guarantee a smooth upgrade.

cc @thockin who may help with some input.

**Comment by liggitt** [comment]
Changing the kubelet mechanism on a minor version boundary is acceptable, because pods are expected to be drained on kubelet minor version upgrade.

**Comment by liggitt** [comment]
Updated the title and description to clarify the impact of the current logic and why it should be changed

**Comment by liggitt** [comment]
my naive recommendation would be to limit the container hash to specific fields that are known to be immutable or are expected to be able to change (maybe just name and image?)

**Comment by lavalamp** [comment]
> limit the container hash to specific fields that are known to be immutable or are expected to be able to change

✅  💯 

If kubelet doesn't know how to react to a field change, it must not be included in the hash.

In-place upgrades add some restrictions:
* The hash must be versioned so that a future kubelet which knows how to react to additional field changes doesn't do an unnecessary restart. (it has to be able to reproduce the hashes of the old kubelet.)
* A new hash version must not be used until there's no chance of rolling back to an old kubelet version which doesn't understand it.

(the above goes for controllers that perform this operation, too)

> maybe just name and image

And resource limits, if those would require a restart.

**Comment by liggitt** [comment]
> In-place upgrades add some restrictions:
> 
> * The hash must be versioned so that a future kubelet which knows how to react to additional field changes doesn't do an unnecessary restart. (it has to be able to reproduce the hashes of the old kubelet.)
> * A new hash version must not be used until there's no chance of rolling back to an old kubelet version which doesn't understand it.

Specifically for kubelets, if the change is made on a minor version boundary, I don't think we need those protections, given sig-node's position that in-place kubelet upgrades without draining is not supported.

> (the above goes for controllers that perform this operation, too)

Yes, for controllers, which have to deal with persisted ControllerRevisions and annotations on API objects made by earlier versions of the controller, they definitely have to consider the approach taken by previous versions of the controller. I plan to spawn similar issues to track resolving this for controllers

**Comment by lavalamp** [comment]
> in-place kubelet upgrades without draining is not supported.

Oh, I did not know this. What is the point of in-place upgrades then?

**Comment by liggitt** [comment]
Expanded my previous comment... in place *minor version* upgrades are not supported. I think in place patch version upgrades are.

**Comment by lavalamp** [comment]
Ah, OK, I can see why you call it optional, but I think it's bad karma unless we have some system that guarantees we don't make a mistake over a patch version change. Perhaps we could resolve that with e.g. a golden data test.

**Comment by kow3ns** [comment]
> Yes, for controllers, which have to deal with persisted ControllerRevisions and annotations on API objects made by earlier versions of the controller, they definitely have to consider the approach taken by previous versions of the controller. I plan to spawn similar issues to track resolving this for controllers

Is there a particular problem that impacts the user wrt to how we do this today? Definitely the controllers can't change the way they compute the hash function between versions (currently fnv). We can add support for that if we think that we will have a need to change the hash computation in the future. The controllers only track `Spec.Template` for the purposes of history, so the place where we aren't resilient is modifying the defaults in the PodTemplateSpec for the Workloads API resources, but I thought we had agreed that defaults that would apply to Pods should be added to the Pod resource and not workload API resources?

**Comment by liggitt** [comment]
> Is there a particular problem that impacts the user wrt to how we do this today?

Yes, see https://github.com/kubernetes/kubernetes/issues/95587#issuecomment-731497172

> API server upgrade triggers new rollout of a workload with no changes/writes to the workload object, due to a delta between the read object and the snapshotted controller revision. An example was the procMount defaulting which caused a daemonset or deployment to replace all its pods on API upgrade.

I'd recommend taking the controller discussion back to there and keep this issue focused on the kubelet.

**Comment by thockin** [comment]
Just to be clear on the implications of this - we're blocking API changes that could trigger this, so the project overall is being impacted.

**Comment by derekwaynecarr** [comment]
@liggitt I tend to think that all maintenance of the kubelet should warrant a drain (major/minor/patch).  I guess a cluster that is a single node is the potential outlier, need to reflect on that a little bit though.  @thockin what changes have we blocked?  I was not aware of the impact this was having across the project as the general concept of drain, update kubelet was basically the primary path I had seen everywhere for o(years).

**Comment by derekwaynecarr** [comment]
caught up with @liggitt separately and now properly understand this.  the kubelet should hash on fields that it understands as mutable for the life of the container.  basically anything today that is editable in validate pod update.

**Comment by garyhuang123** [comment]
To cut off the container spec field version mantenance effort, how about adding a container label hashVersion valued with the current kubelet version, if the hashVersion read from existent container is null or not matched with current kubelet version, just skip the change detection? The container would be recreated with new hash method by future pod updates. If any risks are concerned, kubelet should provide a configuration parameter switch to let user evaluate whether to turn it on or not during k8s upgrade.
@derekwaynecarr

**Comment by liggitt** [comment]
> To cut off the container spec field version mantenance effort, how about adding a container label hashVersion valued with the current kubelet version, if the hashVersion read from existent container is null or not matched with current kubelet version, just skip the change detection?

The current issue is not related to the kubelet version, but changes to the API server version. I think the kubelet hashing on container fields it knows can change and expects to handle is the right approach (currently just image name, I think; in the future, container resources as well)

**Comment by garyhuang123** [comment]
@liggitt yeah, the difference comes from changes of Container spec. If adding a new label to identify spec changes, 2 choices are in place,
1. Maintain Container spec versioning, then choose matched Container spec to hash by the value of label.
2. Or quit Container spec versioning maintenance, and skip the old container hashing if version is not matched, but add an additional configuration parameter able to switch the skip behavior on/off so as to escalate the risk evaluation to user itself at least to avoid cluster-wide outage.

Seems option 1 is risk free. Any idea or real progress on this?

**Comment by garyhuang123** [comment]
@liggitt i see, basically the image name is enough to identify changes on container. Is this approach on progress now?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/63814#issuecomment-767775821 seems like agreement from sig-node representative:

> the kubelet should hash on fields that it understands as mutable for the life of the container. basically anything today that is editable in validate pod update.

But I don't see an assignee or any work in progress here. Marked this as needs-triage to bubble it up to the sig issue review process.

**Comment by garyhuang123** [comment]
So under this pattern, if new API Container adds new field with default value, the restart is unavoidable, right? @liggitt

**Comment by liggitt** [comment]
this would have to be a container field that 1) the API server defaults, 2) the kubelet expects to be mutable and explicitly includes in its container hash

Because the kubelet has to be aware of the field, it would be reasonable for it to use the default value in the hash if the field was unpopulated.

**Comment by ehashman** [comment]
/remove-priority critical-urgent
as we don't have anyone assigned and this didn't block the last release

/triage accepted
/help

**Comment by liggitt** [comment]
it looks like the VPA change expanded the surface area of this issue in f2bd94a0de9c353d90d5cfc06d009a1ba56f8be8 by adding a second hash that is tracked now - [HashWithoutResources](https://github.com/kubernetes/kubernetes/commit/f2bd94a0de9c353d90d5cfc06d009a1ba56f8be8#diff-7148304d62e8edbda6c71962ceb474cb73f31fe53d3ec327698749cb34d6e451R303)

I had hoped handling mutable resources would prompt fixing this issue :-/

**Comment by liggitt** [comment]
cc @smarterclayton @vinaykul for visibility to the problems with detecting container changes using hashes of API content

**Comment by thockin** [comment]
Revisiting this as we look at more and more Pod fields which cannot add default values.  This forces us to treat `nil` as the default value, which means all code that consumes these fields has to know about this.  It's frankly awful.

This is not unique to kubelet, it's just particularly acute.

We could convert this to a list of specific fields to hash, but that still feels brittle.  Shouldn't the API server have a way to help with this?  Either `managedFields` should have a way to say "this was defaulted" or we should have a way to request the object without defaulted fields or we should have a way to know what the default values are and strip them out or something.

@jpbetz @deads2k 

/sig api-machinery
/triage accepted

**Comment by liggitt** [comment]
> We could convert this to a list of specific fields to hash, but that still feels brittle

The kubelet has to do stuff to set up containers correctly, it has to know which fields could change and how much it has to do to correctly handle the changes. Hashing the immutable fields that assert identity (name,namespace,uid,containerName) and the effective values of the fields that it handles mutations to seems correct to me.

**Comment by thockin** [comment]
Sure, but it's just another place that needs to be touched if any other field becomes mutable, which could be forgotten.  I'm not saying not to fix this with urgency, just that I want to consider paths towards less open-coded lists of things to hash.

**Comment by HirazawaUi** [comment]
After PR #124220 is merged, I think this issue should be closed. If there are still any problems, we can reopen this issue.
/close

**Comment by vinaykul** [comment]
> After PR #124220 is merged, I think this issue should be closed. If there are still any problems, we can reopen this issue. /close

@HirazawaUi If you have bandwidth, please run a manual upgrade test if this is not covered in CI somewhere. This change is important but also feels a bit risky.

**Comment by HirazawaUi** [comment]
> > After PR #124220 is merged, I think this issue should be closed. If there are still any problems, we can reopen this issue. /close
> 
> @HirazawaUi If you have bandwidth, please run a manual upgrade test if this is not covered in CI somewhere. This change is important but also feels a bit risky.

I'll try to do this in my spare time :)
