### ISSUE TITLE
kube-dns disregards stubDomains option while resolving externalName service

### ISSUE THREAD

**Issue by driusha** [kubernetes/kubernetes#63821]
/kind bug

**What happened**:
I have:
* internal DNS "10.2.2.10" with zone "example.com" on it,
* stubDomains: {"example.com": ["10.2.2.10"]}
* externalName service "foo" which points to domain "foo.example.com"

When i try to resolve name "foo", i get NXDOMAIN.
If i try to create externalName (ex. mail -> mail.google.com) without stubDomains, everything works.

**Environment**:
- Kubernetes version v1.8.5
- kube-dns version 1.14.5

**Comment by thockin** [comment]
Can you please
