### ISSUE TITLE
Question: HugePages require cpu or memory

### ISSUE THREAD

**Issue by lubinsz** [kubernetes/kubernetes#63838]
In 'pkg/apis/core/validation/validation.go', there is a limitation: if we deploy hugepage volume in pod.yaml, it will report the issue: 'HugePages require cpu or memory', and the deployment will be failed.
My application is DPDK. And for a typical DPDK application, it only needs hugepages volume and cpu isolation.
So can I remove the limitation of 'HugePages require cpu or memory' in pkg/apis/core/validation/validation.go ?

Also, if I follow the document of 'https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/', the deployment will be failed. It will report 'HugePages require cpu or memory'.
If I add the cpu & memory resources for it, and it will be pass.

/sig apps

**Comment by lubinsz** [comment]
@derekwaynecarr 
Can you help it?

**Comment by zvonkok** [comment]
cc @jeremyeder
