### ISSUE TITLE
intermittent external connectivity for various pods/applications - resolv.conf permissions

### ISSUE THREAD

**Issue by el-diablo-rojo** [kubernetes/kubernetes#63867]
/kind bug

**What happened**:
During an upgrade to kubernetes 1.10.x our working deployments began to fail.

**What you expected to happen**:
Our bespoke php service could not contact a required redis deployment (bitnami/redis:4.0.8-r7) or a customised rabbitmq installation (rabbitmq:3.6-alpine), these were previously tested and working with k8s-1.8.0.

**How to reproduce it (as minimally and precisely as possible)**:
Any new deployments installed in k8s 1.10.x should not be able to update via the package manager (independent of image) and also have flaky connectivity to externally addressed services.

**Anything else we need to know?**:
Because the permissions set basically only allows the root user to access/modify the resolv.conf file running dns diagnostics from an affected deployments shell will appear to work correctly, causing much confusion.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration: Maas

**Comment by thockin** [comment]
Can you say what the problem actually is?  The only hint here is "Because the permissions set basically only allows the root user to access/modify the resolv.conf file" but that's not true in general.

```
 kubectl run -ti --rm $RANDOM --image=ubuntu
If you don't see a command prompt, try pressing enter.

root@22862-7d69855cdc-zmjzb:/# cat /etc/resolv.conf 
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local c.thockin-dev.internal google.internal
options ndots:5

root@22862-7d69855cdc-zmjzb:/# ls -l /etc/resolv.conf
-rw-r--r-- 1 root root 141 Jun  6 23:59 /etc/resolv.conf
```
