### ISSUE TITLE
ImagePullBackOff error

### ISSUE THREAD

**Issue by buzai** [kubernetes/kubernetes#63874]
/kind bug

**What happened**:
ImagePullBackOff
**What you expected to happen**:
runing
**How to reproduce it (as minimally and precisely as possible)**:
just init k8s

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.2

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
centos7

**Comment by buzai** [comment]
```
  Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "xtables-lock"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "lib-modules"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "kube-proxy-token-zvktx"
  Normal   SuccessfulMountVolume  44m                 kubelet, k8s-node3  MountVolume.SetUp succeeded for volume "kube-proxy"
  Normal   BackOff                42m (x4 over 43m)   kubelet, k8s-node3  Back-off pulling image "k8s.gcr.io/kube-proxy-amd64:v1.10.2"
  Normal   Pulling                41m (x4 over 44m)   kubelet, k8s-node3  pulling image "k8s.gcr.io/kube-proxy-amd64:v1.10.2"
  Warning  Failed                 41m (x4 over 43m)   kubelet, k8s-node3  Failed to pull image "k8s.gcr.io/kube-proxy-amd64:v1.10.2": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed                 41m (x4 over 43m)   kubelet, k8s-node3  Error: ErrImagePull
  Warning  Failed                 3m (x158 over 43m)  kubelet, k8s-node3  Error: ImagePullBackOff
```

**Comment by buzai** [comment]
```
[root@k8s-node1 ~]# docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-apiserver-amd64            v1.10.2             e774f647e259        2 weeks ago         225MB
k8s.gcr.io/kube-scheduler-amd64            v1.10.2             0dcb3dea0db1        2 weeks ago         50.4MB
k8s.gcr.io/kube-proxy-amd64                v1.10.2             77019aa0531a        2 weeks ago         97.1MB
k8s.gcr.io/kube-controller-manager-amd64   v1.10.2             f3fcd0775c4e        2 weeks ago         148MB
quay.io/calico/node                        v3.1.1              d94b64ac210d        3 weeks ago         248MB
quay.io/calico/cni                         v3.1.1              482f47df27e2        3 weeks ago         68.8MB
quay.io/calico/kube-controllers            v3.1.1              0375d4dda09e        3 weeks ago         55MB
k8s.gcr.io/etcd-amd64                      3.1.12              52920ad46f5b        2 months ago        193MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64     1.14.8              c2ce1ffb51ed        4 months ago        41MB
k8s.gcr.io/k8s-dns-sidecar-amd64           1.14.8              6f7f2dc7fab5        4 months ago        42.2MB
k8s.gcr.io/k8s-dns-kube-dns-amd64          1.14.8              80cc5ea4b547        4 months ago        50.5MB
k8s.gcr.io/pause-amd64                     3.1                 da86e6ba6ca1        4 months ago        742kB
quay.io/coreos/etcd                        v3.1.10             47bb9dd99916        10 months ago       34.6MB

```
but docker has it

**Comment by buzai** [comment]
also i set docker a ss proxy . it can pull images.

**Comment by buzai** [comment]
@dims how can i set a proxy for gcr.io?  is k8s will send a request to gcr.io to ensuer the image is not old. 
in my system i had set a proxy for docker

**Comment by will-code-for-pizza** [comment]
Same issue here.

  Normal   Pulling                1m                 kubelet, cloudbox0001  pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8"
  Warning  Failed                 27s                kubelet, cloudbox0001  Failed to pull image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v1/_ping: dial tcp 64.233.167.82:443: i/o timeout
  Warning  Failed                 27s                kubelet, cloudbox0001  Error: ErrImagePull
  Normal   Pulling                27s                kubelet, cloudbox0001  pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8"
  Warning  Failed                 5s                 kubelet, cloudbox0001  Failed to pull image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8": rpc error: code = Unknown desc = unauthorized: authentication required
  Warning  Failed                 5s                 kubelet, cloudbox0001  Error: ErrImagePull

**Comment by Deepak3994** [comment]
I was trying to implement the same on kubernetes cluster locally. I found the same error,

![imagepullbackoff](https://user-images.githubusercontent.com/20994657/43705054-2ac1ff8e-997f-11e8-9dd6-ed530a1ae656.png)

The below image is a screenshot taken from the kubernetes UI,

![screenshot_2018-08-06 overview - kubernetes dashboard](https://user-images.githubusercontent.com/20994657/43705091-44bcc130-997f-11e8-9119-ddb3af446aae.png)

I am kind of stuck with this error. Kindly let me know the possible cause for these kinds of errors.

**Comment by buzai** [comment]
@Deepak3994 rm all docker image, pull the latest image

**Comment by buzai** [comment]
it is a bug , can fix it by update the latest version

**Comment by simonfontana** [comment]
@buzai Do you know what version this was fixed in? I'm running v. 1.11.2 and have similar issue.

**Comment by buzai** [comment]
@simonfontana  

I am not sure which version, but the latest is no problem, I have already run, and you should pay attention to your network environment, whether the virtual machine network is linked to each other.
