### ISSUE TITLE
Api server proxy does not handle redirect headers

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#6387]
Accessing `https://<master-ip>/api/v1beta1/proxy/services/monitoring-heapster/` redirects to `https://<master-ip>/validate/` instead of ` `https://<master-ip>/api/v1beta1/proxy/services/monitoring-heapster/validate`

Here is a snapshot of the request and response headers:

```
Remote Address:104.197.10.177:443
Request URL:https://104.197.10.177/api/v1beta1/proxy/services/monitoring-heapster/
Request Method:GET
Status Code:307 Temporary Redirect
Request Headersview source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Basic YWRtaW46SXMwQkV0RDFrTmVRTENEcw==
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:104.197.10.177
Pragma:no-cache
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

Response Headers
Connection:keep-alive
Content-Length:46
Content-Type:text/html; charset=utf-8
Date:Thu, 02 Apr 2015 21:21:32 GMT
Location:/validate/
Server:nginx/1.2.1
```

**Comment by vishh** [comment]
cc @nikhiljindal @lavalamp

**Comment by lavalamp** [comment]
Would someone like to write an integration test to verify this redirection activity? I can show you where to put it.

**Comment by smarterclayton** [comment]
@liggitt since he was the last person in here.

**Comment by liggitt** [comment]
Just so I understand, the redirect to `/validate/` is coming from the service being proxied to, and you're expecting the proxy to rewrite the header to prepend the `https://104.197.10.177/api/v1beta1/proxy/services/monitoring-heapster/` bit?

**Comment by vishh** [comment]
Yes

**Comment by lavalamp** [comment]
Oh-- the proxied thing sent a redirection? Yeah, I am not sure if the proxy code follows redirects correctly. That definitely isn't tested. Has this ever worked?

**Comment by liggitt** [comment]
I don't see evidence of it ever working. Not sure you'd want the proxy to follow the redirect.

**Comment by lavalamp** [comment]
Hm-- in that case, we'd need to transform the redirect into a form that the downstream client can actually follow before we send it on.
