### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by awalmsley** [kubernetes/kubernetes#63883]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Getting TLS handshake timeouts when using Kubectl to retrieve pods, and all other commands.

**What you expected to happen**:
Kubectl should return pod details.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```
**Anything else we need to know?**:
This is a sporadic failure on all Kubectl commands. Will work briefly and then fail consistently for minutes. Have tried creating a new cluster, still see failures.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release)
Ubuntu 16.04.3 LTS (Xenial Xerus)

- Kernel (e.g. `uname -a`):
Linux nutz 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by awalmsley** [comment]
@kubernetes/sig-cli-bugs

**Comment by awalmsley** [comment]
This was an issue with the firewall rules defined by the AWS EC2/AMI. Not a Kubernetes problem, closing the issue.

**Comment by lpgc** [comment]
@awalmsley so what were the f/w issues?

**Comment by thecloudgeek** [comment]
curious to understand what the f/w issue was too

**Comment by pickfire** [comment]
I kept getting this issue too in minikube.

**Comment by mmphego** [comment]
I keep getting this issue with my Vagrant and k3s setup.
