### ISSUE TITLE
Race condition when applying the unschedulable taint

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#63897]
The test job that runs regular e2e tests when all alpha features are enabled have been failing: https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-enabled-default 

One thing I noticed is that many "kube-system" pods are scheduled onto the master node, causing the node to be overcommitted. The pods include, e.g., heapster, kube-dns, etc, even though the master was tained/marked as unschedulable. I took a closer look at the logs and this seemed to be caused by the new alpha feature to switch to using taints for unschedulable (#61161) -- The pods were scheduled to the master node *before* the controller manager tainted the node properly.

kube-controller-manager.log:
```
I0515 23:04:32.799346       1 controller_utils.go:248] Added [&Taint{Key:node.kubernetes.io/network-unavailable,Value:,Effect:NoSchedule,TimeAdded:2018-05-15 23:04:32.01059287 +0000 UTC m=+44.916948242,} &Taint{Key:node.kubernetes.io/unschedulable,Value:,Effect:NoSchedule,TimeAdded:2018-05-15 23:04:32.010593023 +0000 UTC m=+44.916948519,}] Taint to Node bootstrap-e2e-master
```

kube-scheduler.log
```
I0515 23:04:31.999793       1 factory.go:1392] Attempting to bind monitoring-influxdb-grafana-v4-5c64865875-klq9m to bootstrap-e2e-master
I0515 23:04:32.019916       1 factory.go:1392] Attempting to bind metrics-server-v0.2.1-7c6c844f97-wm9l2 to bootstrap-e2e-master
I0515 23:04:32.031312       1 factory.go:1392] Attempting to bind kube-dns-694c887f5f-4f6kj to bootstrap-e2e-master
I0515 23:04:32.041949       1 factory.go:1392] Attempting to bind heapster-v1.5.3-6f6f4c647f-866qv to bootstrap-e2e-master
I0515 23:04:32.061453       1 factory.go:1392] Attempting to bind l7-default-backend-5d5b9874d5-ltsq9 to bootstrap-e2e-master
I0515 23:04:32.081330       1 factory.go:1392] Attempting to bind event-exporter-v0.1.9-75857bbfd5-sgxdv to bootstrap-e2e-master
I0515 23:04:32.090780       1 factory.go:1392] Attempting to bind fluentd-gcp-scaler-7f76fb89d7-r8sr5 to bootstrap-e2e-master
```

/cc @bsalamat, @k82cn

**Comment by yujuhong** [comment]
Can we update kubelet to register itself with the unscheduable taint?

**Comment by k82cn** [comment]
Yes, updating taint by node-controller has such race condition :(.
I'm thinking to move those taints from node-controller to kubelet; node-controller only taints unreachable.

/cc @gmarek @bowei 

/sig node

**Comment by yujuhong** [comment]
Since this is based on a kubelet flag, I think it makes sense to let kubelet register the taint itself. Also, there shouldn't be security concern since kubelet would be essentially steering the workload away from itself :-)

**Comment by mikedanese** [comment]
This could also be solved by registering a node initializer managed by nodelifecyclecontroller.

@liggitt

**Comment by k82cn** [comment]
Opened #63955 for this.

> This could also be solved by registering a node initializer managed by nodelifecyclecontroller.

I'm also thinking to replace condition with taint, so enhance kubelet directly for this issue :).

**Comment by liggitt** [comment]
the change proposed by https://github.com/kubernetes/kubernetes/pull/63955 would still be allowed... taints are allowed at creation time, they just can't be modified post-create currently.

**Comment by tallclair** [comment]
Got it, I missunderstood the motivation for that #63955
