### ISSUE TITLE
Autogenerated container port name conflicts with multiple hostports

### ISSUE THREAD

**Issue by jethrogb** [kubernetes/kubernetes#63906]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

A container ports spec such as:
```
        ports:
        - containerPort: 4443
          hostPort: 443
        - containerPort: 4443
          hostPort: 4443
```
Results in this error:
```
kubelet[11270]: W0515 17:44:41.623947   11270 helpers.go:352] Port name conflicted, "cntr-TCP:4443" is defined more than once
```
From https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/helpers.go#L321 . Because of this, the port mappings are not setup correctly on the host when using a CNI-compliant portmap solution.

**What you expected to happen**:
Auto-generated port names should never result in duplicates

**How to reproduce it (as minimally and precisely as possible)**:
[d2.yml.txt](https://github.com/kubernetes/kubernetes/files/1897012/d2.yml.txt)

**Anything else we need to know?**:

/sig node

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: VirtualBox
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): Linux node2 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by zouyee** [comment]
As the code comment, it's protected against exposing the same protocol-port more than once in a container.

**Comment by aojea** [comment]
I see that the problem is legit, but is this setup frequently used?
why not using services instead of hostports?

**Comment by vzburke** [comment]
Why is this still an issue?
