### ISSUE TITLE
Failing Test : [sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow] failing in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63923]
We are seeing multiple tests (for various volume types) failing to umount gracefully.

## Failing Jobs
* [sig-release-master-upgrade#gce-1.10-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-master)
* [sig-release-master-upgrade#gce-master-1.10-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.10-downgrade-cluster)

## Failing Tests
* [[sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1439#sig-storage-subpath-volume-type-emptydir-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)
* [[sig-storage] Subpath [Volume type: nfsPVC] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/617#sig-storage-subpath-volume-type-nfspvc-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)
* [[sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/617#sig-storage-subpath-volume-type-emptydir-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)

## Triage results
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage&job=ci-kubernetes-e2e-gce-master-new-downgrade-cluster

/kind bug
/priority failing-test
/priority important-soon
/sig storage
/milestone v1.11
@kubernetes/sig-storage-bugs 

cc @jberkus @tpepper

/assign @saad-ali 

@saad-ali @msau42 we are seeing a couple of storage e2e tests failing in sig-release-master-upgrade jobs. Beta v1.11 cut is today. Can you please triage this as priority and let us know if we can resolve it as soon as possible?

**Comment by msau42** [comment]
@AishSundar I had cherry picked https://github.com/kubernetes/kubernetes/pull/63037 into 1.10 a while ago.  I see that the downgrade test is using:
```
e2e test version: v1.10.3-beta.0.26+3533e8c0fac5e5
```

Is there a way I can tell if these e2e test version includes my commit?

**Comment by msau42** [comment]
Hm I think it does include my commit.  I found commit 3533e8c0fac5e5 which was from 2 days ago.

**Comment by msau42** [comment]
Discussed with @jingxu97 and @dashpole.  I think the issue is the test is incorrectly waiting until PodTermination.  But it should be waiting for PodDeletion.  During the pod termination phase, the volumes may not have been unmounted yet.

**Comment by msau42** [comment]
This should not block beta.  @jingxu97 confirmed from the test logs that the volume actually did get unmounted, it's just the e2e test checked too early.

**Comment by msau42** [comment]
The failures manifested as flakes, so I think #64039 needs to merge to fully fix the issue.

**Comment by AishSundar** [comment]
The tests are all passing now. Closing this issue.
