### ISSUE TITLE
[Flaky test]: k8s.io/kubernetes/test/integration/scheduler.TestVolumeBindingStress failing in Presubmits and CI jobs

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#63938]
## Flaky Jobs: 
* [presubmits-kubernetes-blocking#pull-kubernetes-integration](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration)
* [sig-release-master-blocking#integration](https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration)

## Flakiest test : 
* [k8s.io/kubernetes/test/integration/scheduler.TestVolumeBindingStress](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63890/pull-kubernetes-integration/11678)

## Flakes in the past week: [36](http://storage.googleapis.com/k8s-metrics/flakes-latest.json)

Triage link
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fscheduler.TestVolumeBindingStress

/priority failing-test
/priority important-soon
/kind flake
/sig-storage
/sig testing
/assign @msau42 
@kubernetes/sig-storage-bugs 

@msau42 I assigned this issue to you since I see that you added the [integration test](https://github.com/kubernetes/kubernetes/commit/f5ec326e7a34bbfff2e83621aa93928d0361848c). Please triage as you see fit. This is currently our #1 flake and repros in both Presubmits and Release blocking jobs

**Comment by msau42** [comment]
This is a dup of https://github.com/kubernetes/kubernetes/issues/63467
/close
