### ISSUE TITLE
gke-kinflate flake: fork/exec ../cmd/kustomize/test/main.sh: no such file or directory

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#63939]
Last seen failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kinflate-periodic-default-gke/736

/kind flake
/sig cli

**Comment by mengqiy** [comment]
I guess we can shut those tests down.

**Comment by mengqiy** [comment]
Just found that this test has already be shutdown. Last run was at 05/16.

Its replacement is https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kustomize-periodic-default-gke/

/close
