### ISSUE TITLE
Make service-node-port-range configurable in kube-up

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#63948]
https://github.com/kubernetes/kubernetes/blob/release-1.9/cmd/kube-apiserver/app/options/options.go#L187

The `service-node-port-range` is currently not configurable by bootstrap parameters. Would be useful to expose a knob for that. 

/kind feature
/kind sig-network

**Comment by thockin** [comment]
kube-up is effectively deprecated.  Do we really need this?
