### ISSUE TITLE
Node Failures handling via the Job API

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#63954]
As a consumer of the Jobs API, I'd like to set up my job such that it is not restarted on code (application running inside a container) failure, but is restarted on node (or infrastructure) failure. That seems to be not possible today where the best I can do as a user is set the backoff policy to be `1` which would mean my buggy job would be run twice at minimum. This is not ideal whenever the jobs are long running and/or consuming expensive resources like hardware accelerators. 
IIUC, this is a fundamental limitation of the Jobs API/Controller. I'm filing this issue to see if there are any other workarounds and to understand if this is a common problem for other k8s users. 

@kubernetes/sig-apps-bugs @kow3ns @janetkuo

**Comment by simplytunde** [comment]
can you give a further clarification on what you mean by "code failure"?

**Comment by vishh** [comment]
@simplytunde clarified my original issue comment.
