### ISSUE TITLE
Kubeadm init followed by containers disappearing due to apiserver failure

### ISSUE THREAD

**Issue by johnpm12** [kubernetes/kubernetes#63983]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Kubectl get pods --all-namespaces fails with "The connection to the server X.X.X.X:6443 was refused-did you specify the right host or port?"
"docker ps" command initially shows all the container daemons(etcd, apiserver, scheduler,controller,..) after few seconds everything disappears. Unable to create flannel pod networks.
**What you expected to happen**:
All the container daemons up and running. kubectl displays all the components. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

- Tried adding cgroupfs in kube config file.
- Swap has been disabled.
- init supplied with --apiserver-advertise-address and --pod-network-cidr
- iptables flushed
- all required ports are open and active
-Restarting kubectl service brings back few of the containers for few seconds after which they disappear again.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2, 1.9, 1.8
- Cloud provider or hardware configuration: Baremetal with 8GB RAM and 8 cores
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux 4.13.0-41-generic #46~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Docker version: 1.13.1
- Others:

**Comment by johnpm12** [comment]
@k8s-sig-onprem-bugs

**Comment by XtinaJ** [comment]
+1 same issue here apiserver logs show timeout error and` dial tcp 10.0.0.190:6443: getsockopt: connection refused`
Tried with Docker versions 1.12 also. Still facing the same issue..
