### ISSUE TITLE
kubectl apply keeps old container in spec on occasion

### ISSUE THREAD

**Issue by Joeskyyy** [kubernetes/kubernetes#63982]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We've occasionally seen kubernetes keep the container from deployment from the previous revision along with an applied revision.

For example, given the following revision history:

```
26        JenkinsBuildNumber: 149
27        JenkinsBuildNumber: 145
28        JenkinsBuildNumber: 151
```

Revision 28 was applied with the following manifest (some things have been obfuscated just for CYA sake):

```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: my-service
  annotations:
    kubernetes.io/change-cause: "JenkinsBuildNumber: 151"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service-151
        image: someimage:151
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "10"]
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
          - containerPort: 8080
        envFrom:
        - secretRef:
            name:some-secret1
        - secretRef:
            name: some-secret2
        - configMapRef:
            name: my-service
      imagePullSecrets:
      - name: nexus-docker
```

But the resulting deployment object in kubernetes was the following (from `kubectl get deployment -o yaml`:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "28"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":"JenkinsBuildNumber: 151"},"name":"my-service","namespace":"mes"},"spec":{"replicas":1,"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"my-service"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"somesecret1"}},{"secretRef":{"name":"some-secret2"}},{"configMapRef":{"name":"my-service"}}],"image":"someimage:151","lifecycle":{"preStop":{"exec":{"command":["sleep","10"]}}},"livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":120,"periodSeconds":10,"timeoutSeconds":1},"name":"my-service-151","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":0,"periodSeconds":1,"timeoutSeconds":1}}],"imagePullSecrets":[{"name":"nexus-docker"}]}}}}
    kubernetes.io/change-cause: 'JenkinsBuildNumber: 151'
  creationTimestamp: 2017-10-20T18:37:28Z
  generation: 36
  labels:
    app: my-service
  name: my-service
  namespace: mes
  resourceVersion: "89827250"
  selfLink: /apis/extensions/v1beta1/namespaces/mes/deployments/my-service
  uid: b98745a3-b5c5-11e7-b67a-02dc572fb994
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-service
    spec:
      containers:
      - envFrom:
        - secretRef:
            name:some-secret1
        - secretRef:
            name: some-secret2
        - configMapRef:
            name: my-service
        image: someimage:151
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: my-service-151
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - envFrom:
        - secretRef:
            name:some-secret1
        - secretRef:
            name: some-secret2
        - configMapRef:
            name: my-service
        image: someimage:145
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: my-service-145
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-05-17T15:56:27Z
    lastUpdateTime: 2018-05-17T15:56:27Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 36
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

Which is spotted first by looking at the pod statuses:

```
my-service-d55758b6d-ltnzb                       1/2       CrashLoopBackOff   7          14m
```

It's curious that the last applied configuration doesn't match the actual configuration.

**What you expected to happen**:
`kubectl apply` should apply the specific config and do a proper rollout

**How to reproduce it (as minimally and precisely as possible)**:
It's been interesting because this doesn't happen consistently. But our deployment is done the exact same way every time, thanks to Jenkins. But here's our steps:

1. Generate the docker image with maven
2. Generate the new deployment manifest with maven (Just does some variable substitution for us)
3. `kubectl apply -f manifest.yml`

**Anything else we need to know?**:
One similar symptom I've been from this happening appears to be when we do a rollback of a deployment, and then promote a new version after. For example, in our revision history you can see:

```
26        JenkinsBuildNumber: 149
27        JenkinsBuildNumber: 145
28        JenkinsBuildNumber: 151
```

We rolled back the result from build #149 to build #145. Then, this morning, we deployed build #151

I've yet to be able to confirm if that's actually the issue or not, since this doesn't happen consistently... To me, this seems like something weird happening with the apply logic itself.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-rancher1", GitCommit:"66aaf7681d4a74778ffae722d1f0f0f42c80a984", GitTreeState:"clean", BuildDate:"2018-03-20T16:02:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Running on vSphere VMs
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `4.4.0-93-generic`
- Install tools: Rancher
- Others: N/A

**Comment by liggitt** [comment]
I can recreate this with the following steps:

1. `kubectl apply` a deployment with a single container named "a"
2. remove the `kubectl.kubernetes.io/last-applied-configuration` annotation from the live API object 
3. `kubectl apply` a deployment with a single container named "b"

step 3 tries to apply a patch representing the delta from your last applied list of containers (which is the empty list because the last applied annotation is gone) to the current list (`[b]`). that patch gets merged with the current state, resulting in `[b,a]`

there are a variety of things that could remove the last-applied-configuration annotation, like using `kubectl replace`.

another possibility is that something is updating the deployment, changing the container, but not using apply, and is leaving an outdated last applied annotation in place.

are all of the writers to this deployment using `kubectl apply`?

**Comment by Joeskyyy** [comment]
@liggitt In this case, all the writes are using `kubectl apply` indeed. We in no way we editing the last-applied-configuration, but our manifests of course don't have that inside of them when the apply happens. I figured it was something fishy with that...

**Comment by lavalamp** [comment]
@Joeskyyy we need to see the pre-apply object. Maybe you can start saving that before you push, so next time it goes wrong you'll have it?

**Comment by darkrasid** [comment]
/reopen

Same issue :(
Is there any news?

**Comment by darkrasid** [comment]
Same issue :(
Is there any news?

**Comment by lavalamp** [comment]
@darkrasid See [Jordan's comment](https://github.com/kubernetes/kubernetes/issues/63982#issuecomment-391500112) above.

Essentially, there are many ways to cause this that we would consider "user error": anything that causes the last-applied-state annotation to stop corresponding to the last version of your config file and the rest of the object as stored in the cluster could cause this.

It's possible that there are non-user-error ways of causing this, but to show us what, we need to see the object before apply happens.

**Comment by lavalamp** [comment]
Serverside apply (alpha now, hopefully beta in 1.15) will make it more difficult for things to get out of sync like this.

Serverside dry run--already available--can and should be used before using apply "for real" if you want to detect this before it happens.

**Comment by darkrasid** [comment]
@lavalamp 
Thank you for your comment.

Actually I use `helm upgrade --install` command to deploy k8s objects. 
And helm doesn't create ` last-applied-state annotation`. I guess it uses something like `kubectl create or replace`

I always run same deploy script via pipelines and always run `helm upgrade --install`. 
However sometimes (actually barely) k8s deployment keeps old container.

Even when I ran same configuration, pipeline and helm chart, the situation was happened. 
That's why I think it is a kind of bugs. 

It doesn't happen most of the time so I cannot share configuration this time .
However when it happens, I will share k8s deployment yaml, chart and something other infomation.
