### ISSUE TITLE
Azure internal Load Balancer reserves same IP multiple times 

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#63994]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

We'v seen that when we are creating services with the annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` the same IP address get's sometimes assigned multiple times to different services. Here is an example:

```bash
NAMESPACE             NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                         AGE
team-3                ms-1                      LoadBalancer   10.10.84.112    10.10.16.6        443:31911/TCP                   5h
team-2                ms-2                      LoadBalancer   10.10.80.167    10.10.16.6        1115:30200/TCP,2113:31924/TCP   28d
team-1                ms-3                      LoadBalancer   10.10.94.122    10.10.16.6        443:30476/TCP                   11d
```
Here are 3 different services that have the same external-ip. If we use `curl` to make requests to the Load Balancer IP it will load balance traffic between `ms-1` and `ms-3` since both are listening on port 443. `ms-2` doesn't receive any traffic.

**What you expected to happen**:

That each service get's an unique IP address without any overlap.

**How to reproduce it (as minimally and precisely as possible)**:

Create an cluster an Azure with acs-engine and create some services with the annoation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` (after some time there will appear services with the same internal Load Balancer IP)

**Anything else we need to know?**:

I found out that there are some correct Azure Load Balancing rules for the services and some missing frontend ips e.g.:

We have 9 services with the according annotation for internal load balancing:
```bash
kubectl get  svc --sort-by '.status.loadBalancer.ingress[].ip' --all-namespaces -o json | jq '.items[] | select(.metadata.annotations."service.beta.kubernetes.io/azure-load-balancer-internal" != null) | .metadata.name' | wc -l
9
```
But we only have 7 frontend-ips:

```bash
az network lb frontend-ip list --lb-name dev1-internal -g rg -o tsv | wc -l
7
```

so we are missing at least 2 IP addresses. We also found that there some mismatching rules in the Azure Portal which aren't fitting the actual behavior e.g. I found a rule for `ms-3` (listening on NodePort `30476`):

<img width="581" alt="screen shot 2018-05-17 at 20 57 02" src="https://user-images.githubusercontent.com/9477533/40197848-f119c0c2-5a14-11e8-8089-b333d1b6b561.png">

As you can see the frontend IP doesn't match the actual external IP (from Kubernetes perspective) also if I run a `curl` against this IP address the another service responds (that received `10.10.16.10`) and `ms-3` is available under `10.10.16.6`  (obviously not always since the IP address is shared with another services).

For `ms-2`I found the following rule configured:

<img width="565" alt="screen shot 2018-05-17 at 21 06 43" src="https://user-images.githubusercontent.com/9477533/40198280-40d80ce4-5a16-11e8-8458-d74ad8e1c7d2.png">

Even the IP address is not known by Kubernetes (everything is configured from the perspective of Azure) I'm not able to call this service:

```bash
$ curl --connect-timeout 2 http://10.10.16.5:2113
curl: (28) Connection timed out after 2004 milliseconds

$ curl --connect-timeout 2 http://10.10.16.6:2113
curl: (28) Connection timed out after 2004 milliseconds
```

I assume this is the case because the iptables rules are not configured correctly by `kube-proxy` (since the external load-balancer IP is wrong). Also I assume that `ms-1` and `ms-2` get load balanced by the `kube-proxy`.

I will take some further time to dig into this issue and hopefully come with a fix in the next days. I appreciate any hints where to look :).

**Environment**:
- Kubernetes version (use `kubectl version`):

```bash
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Azure

- OS (e.g. from /etc/os-release):

Ubuntu 16.04.4 LTS

- Kernel (e.g. `uname -a`):
- Install tools:
acs-engine
- Others:

**Comment by yastij** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@johscheuer Thanks for reporting the issue. Could you share the logs of kube-controller-manager? e.g. by running `kubectl -n kube-system logs <kube-controller-manager-pod-name>`

**Comment by johscheuer** [comment]
@feiskyer I could send you the logs of the controller manager privately (or send you an link to Google Drive or something else).

**Comment by feiskyer** [comment]
@johscheuer Could you elaborate the detailed steps to reproduce the issue? thanks

**Comment by johscheuer** [comment]
This is our acs-engine template:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "${k8s_version}",
      "kubernetesConfig": {
        "enableDataEncryptionAtRest": false,
        "useManagedIdentity": true,
        "enableRbac": true,
        "networkPolicy": "calico",
        "privateCluster": {
            "enabled": true
        },
        "dnsServiceIP": "${network_dns_ip}",
        "serviceCidr": "${network_service_cidr}",
        "clusterSubnet": "${network_cluster_subnet_cidr}",
        "etcdDiskSizeGB": "256",
        "dockerEngineVersion": "17.05.*"
      }
    },
    "aadProfile": {
      "serverAppID": "${server_app_id}",
      "clientAppID": "${client_app_id}",
      "tenantID": "${tenant_id}",
      "adminGroupID": "${infrastructure_group_id}"
    },
    "masterProfile": {
      "count": ${master_count},
      "dnsPrefix": "${dns_prefix}",
      "vmSize": "${master_vm_size}",
      "vnetSubnetId": "/subscriptions/${subscription_id}/resourceGroups/${rg_name}/providers/Microsoft.Network/virtualNetworks/${vnet_name}/subnets/${master_subnet_name}",
      "firstConsecutiveStaticIP": "${first_consecutive_static_ip}",
      "vnetCidr": "${network_cidr}"
    },
    "agentPoolProfiles": [
      {
        "name": "agent",
        "count": ${worker_count},
        "vmSize": "${worker_vm_size}",
        "vnetSubnetId": "/subscriptions/${subscription_id}/resourceGroups/${rg_name}/providers/Microsoft.Network/virtualNetworks/${vnet_name}/subnets/${worker_subnet_name}",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "${public_ssh_key}"
          }
        ]
      }
    }
  }
}
```

**Comment by khenidak** [comment]
@johscheuer yes please send controller manager logs (note they will include your RG and sub id) to khnidk at microsoft dot com

**Comment by feiskyer** [comment]
@khenidak Johannes has sent me the logs privately. There's nothing abnormal from logs, and the issue is hard to reproduce since then. We suspect it's a temporary issue from Azure, but no evidence for that.

Let's keep the issue open and watch for more clusters if there's any chance to reproduce it. More verbose logs are also added to v1.11 for easy troubleshooting those issues in the future.

**Comment by johscheuer** [comment]
I close this issue since it didn't occurred since then (probably an Azure hickup)
