### ISSUE TITLE
adds support for hierarchical fs namespace for probe based kubelet plugin discovery

### ISSUE THREAD

**Issue by figo** [kubernetes/kubernetes#64003]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
as a probe based kubelet plugin discovery mechanism been introduced at 
https://github.com/kubernetes/kubernetes/pull/63328 , the initial implementation  
support flat plugin socket directory, this is assuming all socket file names are unique.  

as number of plugin grows in the future, it is harder to coordinate socket names cross all vendors.  
we can support hierarchical filesystem namespaces to solve this problem.  

**How to name the namespaces**:
the namespace name could be
```
     1:1 map to vendor name,  
     or plugin type name (CSI, DevicePlugin),
     or combine both plugin type and vendor name.
```
then socket names only need be unique within one namespace, it will
be much easier to coordinate naming within the namespace.  

**What you expected to happen**:
the plugin socket directory looks like this:  

```
 plugin socket directory  
    |  
    ----> namespace 1 
                   |  
                   ----->  socket1,  socket2 ...  
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
this already been mentioned as TODO in https://github.com/kubernetes/kubernetes/pull/63328

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node
/area hw-accelerators
/cc @jiayingz @RenaudWasTaken @vishh @ScorpioCPH @sjenning @derekwaynecarr @jeremyeder @lichuqiang @tengqm @saad-ali @chakri-nelluri @ConnorDoyle @vladimirvivien

**Comment by tallclair** [comment]
Does the file name matter? If not, could we just require plugins to choose a dynamic name (e.g. append a random ID). Or does it need to be stable across restarts (could use hash of binary, etc.)?

**Comment by figo** [comment]
@tallclair good question, Tim, i don't think plugin watcher is looking for any particular socket file name,  the same in restart case,  the downside of using random name is maybe: it will make debugging harder if two or more socket files using same prefix (plus random ID), thanks

**Comment by tallclair** [comment]
If the random ID is long enough, you can all but guarantee you won't have a collision.

**Comment by figo** [comment]
@tallclair random ID should work if we have a proper way to enforce plugin name, i just have some concern about debug-ability, if two plugins using same prefix, for example
```
gpu_2yAOwjUiHs.sock
gpu_tUssaB0pih.sock
```
it certainly hard to understand which plugin it map to by just looking at names.
Thanks
