### ISSUE TITLE
Create configmap from a URL causes error

### ISSUE THREAD

**Issue by weiwarren** [kubernetes/kubernetes#64007]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
When I run the following command from the terminal
```
kubectl create configmap game-config-3 --from-file=game-special-key=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl/game.properties
```
I receive 

> error: error reading https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl/game.properties: no such file or directory
> 

**How to reproduce it (as minimally and precisely as possible)**:
1. minikube start
2. kubectl create configmap game-config-3 --from-file=game-special-key=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl/game.properties

**What you expected to happen**:
From the 1.10 documentation, this should create a configmap from the remote game.properties file

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release):  OSX 10.10.5
- Kernel (e.g. `uname -a`): Darwin MacBook-Pro-2.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

**Comment by dixudx** [comment]
This is not a bug, since kubectl never supports creating configmaps using urls.

This is an error on doc, which was introduced by a wrong change. Already filed kubernetes/website#8611 to address this.

> kubectl create configmap game-config-3 --from-file=game-special-key=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl/game.properties

@weiwarren That doc is misleading. You should try to specify a file path/directory when creating configmap using `--from-file`.
