### ISSUE TITLE
delete namespace  stuck on Terminating status

### ISSUE THREAD

**Issue by valdemarpavesi** [kubernetes/kubernetes#64002]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**: delete namespace stuck on status Terminating

**What you expected to happen**: delete namespace

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
@kubernetes/sig-API Machinery-bugs

[root@node1 tmp]# kubectl get namespace
NAME           STATUS        AGE
default        Active        2d
istio-system   Active        2d
kube-public    Active        2d
kube-system    Active        2d
rook           Terminating   7h

[root@node1 tmp]#  curl -H "Content-Type: application/json" -X PGET --data-binary @ns.json http://135.121.241.75:8001/api/v1/namespaces/rook/finalize -v
* About to connect() to 135.121.241.75 port 8001 (#0)
*   Trying 135.121.241.75...
* Connected to 135.121.241.75 (135.121.241.75) port 8001 (#0)
> PGET /api/v1/namespaces/rook/finalize HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 135.121.241.75:8001
> Accept: */*
> Content-Type: application/json
> Content-Length: 479
>
* upload completely sent off: 479 out of 479 bytes
< HTTP/1.1 405 Method Not Allowed
< Content-Length: 245
< Content-Type: application/json
< Date: Thu, 17 May 2018 21:56:44 GMT
<
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {

  },
  "code": 405
* Connection #0 to host 135.121.241.75 left intact
}[root@node1 tmp]#

[root@node1 tmp]# kubectl get namespace rook -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "creationTimestamp": "2018-05-17T14:13:51Z",
        "deletionTimestamp": "2018-05-17T20:07:51Z",
        "name": "rook",
        "resourceVersion": "305082",
        "selfLink": "/api/v1/namespaces/rook",
        "uid": "8687bbb1-59dc-11e8-95d0-8cdcd4b71238"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
[root@node1 tmp]#

**Environment**:
- Kubernetes version (use `kubectl version`):kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
[root@node1 tmp]#

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): more /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

- Kernel (e.g. `uname -a`): Linux node1 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubespray
- Others: helm/rook/istio

**Comment by valdemarpavesi** [comment]
[root@node1 tmp]# kubectl delete namespace rook  --grace-period=0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
Error from server (Conflict): Operation cannot be fulfilled on namespaces "rook": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
[root@node1 tmp]#

@kubernetes/sig-API Machinery-bugs

**Comment by lavalamp** [comment]
cc @jpbetz

**Comment by jpbetz** [comment]
@valdemarpavesi two questions:
- In the curl request in this issue's description, instead of `PGET`, did you mean to do `POST`?
- The error reports "The system is ensuring all content is removed from this namespace. Upon completion, this namespace will automatically be purged by the system.". Have you validated that the namespace is empty? e.g. `kubectl --namespace=rook get all` ?

**Comment by deas** [comment]
@jpbetz Saw the same issue here a few days ago. Checked the namespace and it was empty. Not quite sure whether the system exposing it still exists at this time.

**Comment by valdemarpavesi** [comment]
Hello @jpbetz 

it was typo , I did the correct curl with POST.  but , same result.

I could not wait any longer.  I did new cluster installation.


regards!
Valdemar

**Comment by valdemarpavesi** [comment]
I will re-open if get it again.

**Comment by hd-deman** [comment]
same problem with istio 1.0.2

**Comment by emmekappa** [comment]
got same problem

**Comment by jpbetz** [comment]
Anyone able to construct steps to reproduce the issue?  Details will be a huge help here.

**Comment by iarechagaMM** [comment]
We are suffering the very same issue. Some namespaces are 130d old and their are completely stuck in Terminating state

**Comment by lavalamp** [comment]
There's almost certainly an object in the namespace that can't be deleted for some reason, likely a stray finalizer. We can't help without knowing what exactly is blocking the deletion.

**Comment by jimmiebtlr** [comment]
How do we find what's blocking the deletion?

**Comment by Amos-85** [comment]
It's not a k8s issue,
rook ceph project use this mechanism in order to save the cluster state.
for cleaning the cluster,
follow there article about cleaning up a cluster:
[https://rook.io/docs/rook/v0.8/ceph-teardown.html](url)

Anyway,
If you still struggle with the rook namespace deletion,

Check what resources is stuck in rook namespace.
`kubectl --namespace=<rook-namespace>  get all` ,

then read carefully how to deal with deletion of StatefulSet Pods (**DON'T USE THIS IN PRODUCTION** Unless you are really know the side effects of those commands)
[https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#delete-pods](url)

Follow the steps in the article for deleting the terminated pod in the rook namespace.
after deleting the terminated pod in rook namespace,
run:
`kubectl edit ns <rook-namespace>`
delete the - kubernetes value under finalizers section and save the file.
 
after those steps rook namespace will be deleted.

**Comment by lavalamp** [comment]
It should be easier to figure out what's going wrong-- I filed #70916

**Comment by Amos-85** [comment]
Agree @lavalamp ,
I have also spent many time about figure out what's going wrong when facing terminating issue.

**Comment by tyagiamreesh** [comment]
I am also not able to delete namespace, even after editing `kubectl edit ns <my-namespace>`. When I run edit command again, kubernetes value under finalizers appers again.

**Comment by cooboos** [comment]
I also got the same problem, and there is no pod in <rook-namespace>.

**Comment by avtarsingh12015** [comment]
I am also facing the same issue. 
![image](https://user-images.githubusercontent.com/20569900/49686513-aa05dd80-fb1b-11e8-8d1f-9b96d32ba293.png)

![image](https://user-images.githubusercontent.com/20569900/49686525-c43fbb80-fb1b-11e8-966d-141f4553166d.png)

**Comment by Amos-85** [comment]
@avtarsingh12015  ,
try to follow their rook documentation to clean the ceph-cluster:
[https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md](url) 

seems there is still resources in the rook-ceph namespace and that's why is it stuck on terminating status.

**Comment by malizz** [comment]
Same problem with istio-1.0.4. 
I have deleted all the resources, secrets, configmaps, ServiceAccounts related to istio. 
Neither `delete --force` nor editing the namespace work.

**Comment by sporkmonger** [comment]
I was able to determine that the issue @malizz mentioned above was ultimately caused by an admission webhook config:

`unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request`

Once the offending config was removed, the namespace eventually got deleted.

**Comment by emolmar** [comment]
I was able to solve this same problem (or an apparently similar one) by patching a crd that turned out to be the cause of the problem.

First I identified the offending crd with the command
`kubectl get crd
NAME                                          CREATED AT
bgpconfigurations.crd.projectcalico.org       2018-10-24T14:06:47Z
clusterinformations.crd.projectcalico.org     2018-10-24T14:06:47Z
**clusters.rook.io**                              2019-02-05T08:36:08Z
felixconfigurations.crd.projectcalico.org     2018-10-24T14:06:47Z
globalnetworkpolicies.crd.projectcalico.org   2018-10-24T14:06:47Z
globalnetworksets.crd.projectcalico.org       2018-10-24T14:06:47Z
hostendpoints.crd.projectcalico.org           2018-10-24T14:06:47Z
ippools.crd.projectcalico.org                 2018-10-24T14:06:47Z
networkpolicies.crd.projectcalico.org         2018-10-24T14:06:47Z
`

Then I issued the following command:
`$ kubectl patch crd clusters.rook.io -p '{"metadata":{"finalizers": []}}' --type=merge`

At this point, the crd and the namespace, that I had previously, unsuccessfully, tried to delete, were automatically removed.

**Comment by hobbytp** [comment]
I met the same problem and use the same solution form @emolmar , and the issue gone.  thanks,

**Comment by narg95** [comment]
I had the same issue due to a CRD that was created while the namespace was in the terminating face.

It worked for what @emolmar mentioned plus I had to remove the `finalizer` from the problematics `CRD`

**Comment by mrrandrade** [comment]
I know the issue is closed, but I'm guessing random people might get here with the same problems.

Our situation was similar to the one reported by **sporkmonger**, but caused by a faulty metrics server instalation instead of certmanager:

```
E0418 19:34:02.835197       1 memcache.go:135] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
After removing the metricserver apiservice namespace eventually went away.

**Comment by lavalamp** [comment]
Please take future reports of this to: #70916

**Comment by F5veRings** [comment]
I tried using @Amos-85 's  method but for some reason it's not actually editing the namespace file at all, so my problem still persists

**Comment by vinit-saini** [comment]
I faced the same issue and had to remove the resources being used by the namespace manually from my openstack enviornment. From kubectl, didn't find any way to cleanup namespace mess..

**Comment by sameergn** [comment]
> I was able to solve this same problem (or an apparently similar one) by patching a crd that turned out to be the cause of the problem.
> 
> First I identified the offending crd with the command
> $ kubectl get crd
> NAME CREATED AT
> bgpconfigurations.crd.projectcalico.org 2018-10-24T14:06:47Z
> clusterinformations.crd.projectcalico.org 2018-10-24T14:06:47Z
> **clusters.rook.io** 2019-02-05T08:36:08Z
> felixconfigurations.crd.projectcalico.org 2018-10-24T14:06:47Z
> globalnetworkpolicies.crd.projectcalico.org 2018-10-24T14:06:47Z
> globalnetworksets.crd.projectcalico.org 2018-10-24T14:06:47Z
> hostendpoints.crd.projectcalico.org 2018-10-24T14:06:47Z
> ippools.crd.projectcalico.org 2018-10-24T14:06:47Z
> networkpolicies.crd.projectcalico.org 2018-10-24T14:06:47Z
> 
> Then I issued the following command:
> $ kubectl patch crd clusters.rook.io -p '{"metadata":{"finalizers": []}}' --type=merge
> 
> At this point, the crd and the namespace, that I had previously, unsuccessfully, tried to delete, were automatically removed.

in our case, had to edit stuck istio crd istiooperators.install.istio.io instead of patching and removed finalizer section manually.

**Comment by dable-mj111** [comment]
FYI, this document explained well how to manually delete stuck namespace.
https://www.ibm.com/support/knowledgecenter/SSBS6K_3.2.0/troubleshoot/ns_terminating.html

**Comment by sharma-raj** [comment]
I am unable to delete ns, still showing in terminating state, there's no filed where mentioned the finalizer option. can some please help to resolve the problem?

cat fleet-system.json
{
"apiVersion": "v1",
"kind": "Namespace",
"metadata": {
"annotations": {
"cattle.io/status": "{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-01-08T09:14:26Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2021-01-08T09:14:31Z"}]}",
"field.cattle.io/projectId": "c-s8hs9:p-5bk2c",
"kubectl.kubernetes.io/last-applied-configuration": "{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"fleet-system"},"spec":{"finalizers":[]}}\n",
"lifecycle.cattle.io/create.namespace-auth": "true",
"objectset.rio.cattle.io/applied": "{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"objectset.rio.cattle.io/id":"fleet-agent-bootstrap"},"labels":{"objectset.rio.cattle.io/hash":"f399d0b310fbfb28e9667312fdc7a33954e2b8c8"},"name":"fleet-system"}}",
"objectset.rio.cattle.io/id": "fleet-agent-bootstrap"
},
"creationTimestamp": "2021-01-08T09:14:25Z",
"deletionGracePeriodSeconds": 0,
"deletionTimestamp": "2021-01-11T08:41:43Z",
"finalizers": [
"controller.cattle.io/namespace-auth"
],
"labels": {
"field.cattle.io/projectId": "p-5bk2c",
"objectset.rio.cattle.io/hash": "f399d0b310fbfb28e9667312fdc7a33954e2b8c8"
},
"managedFields": [
{
"apiVersion": "v1",
"fieldsType": "FieldsV1",
"fieldsV1": {
"f:metadata": {
"f:labels": {
"f:field.cattle.io/projectId": {}
}
}
},
"manager": "agent",
"operation": "Update",
"time": "2021-01-08T09:14:25Z"
},
{
"apiVersion": "v1",
"fieldsType": "FieldsV1",
"fieldsV1": {
"f:metadata": {
"f:annotations": {
".": {},
"f:objectset.rio.cattle.io/applied": {},
"f:objectset.rio.cattle.io/id": {}
},
"f:labels": {
".": {},
"f:objectset.rio.cattle.io/hash": {}
}
}
},
"manager": "fleetcontroller",
"operation": "Update",
"time": "2021-01-08T09:14:25Z"
},
{
"apiVersion": "v1",
"fieldsType": "FieldsV1",
"fieldsV1": {
"f:metadata": {
"f:annotations": {
"f:cattle.io/status": {},
"f:field.cattle.io/projectId": {},
"f:lifecycle.cattle.io/create.namespace-auth": {}
},
"f:finalizers": {
".": {},
"v:"controller.cattle.io/namespace-auth"": {}
}
}
},
"manager": "rancher",
"operation": "Update",
"time": "2021-01-08T09:14:30Z"
},
{
"apiVersion": "v1",
"fieldsType": "FieldsV1",
"fieldsV1": {
"f:status": {
"f:phase": {}
}
},
"manager": "kube-controller-manager",
"operation": "Update",
"time": "2021-01-11T08:42:10Z"
},
{
"apiVersion": "v1",
"fieldsType": "FieldsV1",
"fieldsV1": {
"f:metadata": {
"f:annotations": {
"f:kubectl.kubernetes.io/last-applied-configuration": {}
}
}
},
"manager": "kubectl",
"operation": "Update",
"time": "2021-01-11T10:56:28Z"
}
],
"name": "fleet-system",
"resourceVersion": "88004811",
"selfLink": "/api/v1/namespaces/fleet-system",
"uid": "af190fda-969c-4fbc-b233-81fa52449411"
},
"spec": {},
"status": {
"conditions": [
{
"lastTransitionTime": "2021-01-11T08:41:48Z",
"message": "All resources successfully discovered",
"reason": "ResourcesDiscovered",
"status": "False",
"type": "NamespaceDeletionDiscoveryFailure"
},
{
"lastTransitionTime": "2021-01-11T08:41:48Z",
"message": "All legacy kube types successfully parsed",
"reason": "ParsedGroupVersions",
"status": "False",
"type": "NamespaceDeletionGroupVersionParsingFailure"
},
{
"lastTransitionTime": "2021-01-11T08:41:48Z",
"message": "All content successfully deleted, may be waiting on finalization",
"reason": "ContentDeleted",
"status": "False",
"type": "NamespaceDeletionContentFailure"
},
{
"lastTransitionTime": "2021-01-11T08:42:09Z",
"message": "All content successfully removed",
"reason": "ContentRemoved",
"status": "False",
"type": "NamespaceContentRemaining"
},
{
"lastTransitionTime": "2021-01-11T08:41:48Z",
"message": "All content-preserving finalizers finished",
"reason": "ContentHasNoFinalizers",
"status": "False",
"type": "NamespaceFinalizersRemaining"
}
],
"phase": "Terminating"
}
}
