### ISSUE TITLE
debian: kubernetes-cni.deb does not create required directories

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubernetes#64018]
/kind bug

**What happened**:

If you start with a minimal Debian image and attempt to install kubernetes-cni.deb as an artifact
from a Bazel build, it will fail with:

```
dpkg: error processing archive kubernetes-cni.deb (--install):
 error creating directory '/opt/cni/bin': No such file or directory
```

This has been a known issue in the past, and there are workarounds for CI in place, but it's
still unexpected behaviour (https://github.com/kubernetes/kubernetes/issues/59762#issuecomment-366400634)

**What you expected to happen**:

kubernetes-ci.deb installs.

**How to reproduce it (as minimally and precisely as possible)**:

``` shell
docker run -it -v <path to debs>:/mnt debian /bin/sh -c 'dpkg -i /mnt/kubernetes-cni.deb'
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): debian
- Kernel (e.g. `uname -a`): n/a
- Install tools: `dpkg`
- Others:

/sig cluster-lifecycle

**Comment by ixdy** [comment]
hm, this might be a bug in our "fast" tar builder (https://github.com/kubernetes/repo-infra/tree/master/tools/build_tar).

if I revert to the bazel-supplied version:
```diff
-load("@io_kubernetes_build//defs:pkg.bzl", "pkg_tar")
+load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")
```

then the tarball looks more like we'd expect:
```console
$ tar tvf bazel-bin/build/debs/kubernetes-cni-data.tar
drwxr-xr-x 0/0               0 1969-12-31 16:00 ./
drwxr-xr-x 0/0               0 1969-12-31 16:00 ./opt/
drwxr-xr-x 0/0               0 1969-12-31 16:00 ./opt/cni/
drwxr-xr-x 0/0               0 1969-12-31 16:00 ./opt/cni/bin/
-rwxr-xr-x 0/0         2814104 1969-12-31 16:00 ./opt/cni/bin/flannel
-rwxr-xr-x 0/0         3877986 1969-12-31 16:00 ./opt/cni/bin/ptp
-rwxr-xr-x 0/0         2991965 1969-12-31 16:00 ./opt/cni/bin/host-local
-rwxr-xr-x 0/0         3470464 1969-12-31 16:00 ./opt/cni/bin/portmap
-rwxr-xr-x 0/0         2808402 1969-12-31 16:00 ./opt/cni/bin/tuning
-rwxr-xr-x 0/0         3475750 1969-12-31 16:00 ./opt/cni/bin/vlan
-rwxr-xr-x 0/0         2605279 1969-12-31 16:00 ./opt/cni/bin/sample
-rwxr-xr-x 0/0         9921982 1969-12-31 16:00 ./opt/cni/bin/dhcp
-rwxr-xr-x 0/0         3475802 1969-12-31 16:00 ./opt/cni/bin/ipvlan
-rwxr-xr-x 0/0         3520724 1969-12-31 16:00 ./opt/cni/bin/macvlan
-rwxr-xr-x 0/0         3026388 1969-12-31 16:00 ./opt/cni/bin/loopback
-rwxr-xr-x 0/0         3890407 1969-12-31 16:00 ./opt/cni/bin/bridge
```

**Comment by randomvariable** [comment]
I'll dig a bit more. I started with the assumption that this was a Bazel bug needing a workaround.

**Comment by ixdy** [comment]
/remove-lifecycle stale
/assign

This should probably still be fixed.

**Comment by randomvariable** [comment]
Once https://github.com/kubernetes/repo-infra/pull/84 is ok & merged,
referenced io_kubernetes_build will need updating in
https://github.com/kubernetes/kubernetes/blob/master/build/root/WORKSPACE

**Comment by randomvariable** [comment]
Oops. Didn't realise this issue was getting spammed by my bazel testing.

**Comment by neolit123** [comment]
@randomvariable yep, better not include references in commits.

is this resolved?

**Comment by randomvariable** [comment]
Yes, https://github.com/kubernetes/repo-infra/pull/88 fixed this.

**Comment by ixdy** [comment]
we still need to bump the kubernetes/repo-infra dependency in WORKSPACE though. I'll open a PR to do that for kubernetes/kubernetes.
