### ISSUE TITLE
Docs: 404 link in docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by Freeaqingme** [kubernetes/kubernetes#64025]
Page: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

Contains this command:
```
kubectl create configmap game-config --from-file=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl
```

However, executing that command results in:
```
$ kubectl create configmap game-config --from-file=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl
error: error reading https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl: no such file or directory
```

**Comment by Freeaqingme** [comment]
cc @kubernetes/sig-docs-bugs

**Comment by shubheksha** [comment]
Kubernetes docs live in a separate repo. Can you please file this [there](https://github.com/kubernetes/website/issues/new)? Thanks!

**Comment by dixudx** [comment]
Dup of #64007.

I've filed kubernetes/website#8611 to address this.

This is a doc error, not a bug.

**Comment by Freeaqingme** [comment]
Thanks for the replies. I couldn't find a separate documentation repo, and given that this project also contains a 'docs 'directory I figured this was the place to be.  Guess I was wrong :)

=> Closed
