### ISSUE TITLE
Start collecting etcd metrics in our performance tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#64030]
This is a discussion that came up few times already in the past. It'll be really helpful to have those in light of recent regressions we'd seen due to etcd changes, like:

- https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-371171837
- https://github.com/kubernetes/kubernetes/issues/62064#issuecomment-384355538
- Also to help with https://github.com/kubernetes/kubernetes/issues/63245

Etcd exposes a [bunch of metrics](https://coreos.com/etcd/docs/latest/metrics.html), out of which few that're most interesting to us IMO are:

- backend_commit_duration_seconds
- snapshot_save_total_duration_seconds
- peer_round_trip_time_seconds (probably not so important for our scalability tests that're all single-node etcd setups, except [gke-regional-performance](https://k8s-testgrid.appspot.com/sig-scalability-gke#gke-large-performance-regional) one)
- sth else?

We should:

- [x] collect those metrics through our test framework (similar to how we're doing for apiserver)
- [x] plot those metrics on our performance dashboard

cc @kubernetes/sig-scalability-misc @kubernetes/sig-api-machinery-misc @wojtek-t @jpbetz @jberkus

**Comment by shyamjvs** [comment]
/assign @krzysied 
Who seemed interested in taking this up.

**Comment by jberkus** [comment]
Other metrics I'd like to track:

* wal_fsync_duration_seconds: if at some scalability level disk contention is a factor, it would be nice to see it in the graphs.
* proposals_committed_total: we really need a count of the number of writes being done to Etcd.
* proposals_pending: we also want to see if etcd requests start queueing up.

I don't see any etcd metric for average size of a change.  I think this is possibly significant; I can definitely imagine some recent patches that make object definitions longer on average could affect overall latency.  Bytes are bytes.  I'll see if I can track down an etcd engineer around this.

**Comment by jberkus** [comment]
Ah, here we go:

* client_grpc_sent_bytes_total
* client_grpc_received_bytes_total

Those give us request size information.

**Comment by jpbetz** [comment]
etcd 3.1+ emits https://github.com/grpc-ecosystem/go-grpc-prometheus metrics when the `--metrics extensive` flag is set, `grpc_server_started_total` and similar might be helpful for answering questions about load (in conjunction with the `client_grpc_*_bytes_total` metrics @jberkus already mentioned above).

**Comment by shyamjvs** [comment]
Thanks @jberkus and @jpbetz - we'll keep those points in mind.

So one question that popped up while @krzysied was looking into it is - how do we reset the etcd metrics (so that our e2e tests are independently measured)?
And it seems to me like we have a few options here:

- Restart etcd in b/w the tests (which will automatically reset the metrics)
- Measure the values of metrics after test-1 and subtract it from the values after test-2 (this should work with the metrics mostly being histograms and counters)
- Change upstream etcd to allow DELETE operation on the metrics handler
- Not care about resetting at all

I'm inclined towards 1 or 3, but maybe someone has different ideas/concerns?

**Comment by wojtek-t** [comment]
There is significant drawback of "restarting etcd" approach. Which is: it's hard to do in managed environments (such as GKE) [though arguably, neither 1 nor 3 may be possible there...]

**Comment by wojtek-t** [comment]
> I agree with your comment @wojtek-t . However, I think for testing purpose it might be ok to restart it (we just want to measure etcd performance in our tests). Wdyt?

I think I wasn't clear - I'm not opposed to restarting etcd itself.
I was just trying to say, that in managed solutions (like GKE) you may not be able (have enough permissions) to restart etcd. Which means that you won't be able to run those tests the same way on GKE (and other managed solutions).

**Comment by shyamjvs** [comment]
Yeah, that's a good point that this won't work on managed solutions. That said, FMU we have even bigger problem there of even collecting the metrics (as neither can we proxy to the pod because master isn't registered, nor can we SSH to the master) - it's possible that we may not even be able to access those from user space.

**Comment by wojtek-t** [comment]
Yes - that's why I wrote " [though arguably, neither 1 nor 3 may be possible there...]" above :)

**Comment by shyamjvs** [comment]
Well.. then also 2, no? :)

**Comment by krzysied** [comment]
As you can see above, I've created PR for etcd metrics. However, I think we should discuss about which metrics we really want to collect. Currently I've added support only for etcd_disk_backend_commit_duration_seconds, etcd_debugging_snap_save_total_duration_seconds, etcd_disk_wal_fsync_duration_seconds, peer_round_trip_time_seconds.

- Do we need all of those metrics?
- Is there any other metric we want to collect?

**Comment by shyamjvs** [comment]
@krzysied Your PR https://github.com/kubernetes/kubernetes/pull/64695 is merged but it seems like we're still not collecting the etcd metrics (i.e I don't see an EtcdMetrics file in [artifacts](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/15381/artifacts/)). Could you PTAL and make sure it works?

**Comment by krzysied** [comment]
I see there is a problem. I'm working on it.
I'll write back as soon as I find the cause.

**Comment by krzysied** [comment]
I've found out why there is no etcd metrics collected. All of our executed runs don't contain my PR. I verified that etcd metrics are collected during presubmit checks, thus it should work for out normal test runs.

The issue here is that for some reason all of recent test runs are using kubernetes commit 7bf40d2c6 (which at this point is 2 days old). We should investigate why the newest one aren't used.

**Comment by shyamjvs** [comment]
The commit seems to be stationary for our [gce-100 job](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce) for a long time. @krzyzacy @BenTheElder Any idea what's happening?

**Comment by krzysied** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by BenTheElder** [comment]
The build job is failing, so it's getting the last good build. No idea why we didn't get an alert yet, investigating. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/41170/

**Comment by ixdy** [comment]
fix for the build job in #66076.

**Comment by BenTheElder** [comment]
fix is merged, next run (very soon) should pick it up and put up a new build
I'm also following up on getting a sig testing alerts group and expanding our alerting.

**Comment by krzysied** [comment]
@ixdy @BenTheElder Thanks for the fix!

@shyamjvs Etcd metrics are available in [artifacts](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/15414/artifacts/) directory now.

**Comment by shyamjvs** [comment]
Thanks everyone for looking into it.

@krzysied - The [values](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/15414/artifacts/EtcdMetrics_density_2018-07-12T07:08:11Z.json) seem to be rounded to integers and a bit crude. Is it possible to make it more accurate, for e.g by using smaller units or sth?

**Comment by krzysied** [comment]
@shyamjvs  I'm afraid that is impossible without making changes to the etcd. The problem is that we are using histograms as metrics. We have number of samples in a group but not samples distribution. We can only calculate in which buckets x'th percentile is.
Also, those histogram buckets start from 1ms and grow exponentially, so 1ms is our lower limit.

**Comment by krzysied** [comment]
> We may try to improve it a bit using linear approximations 

The result will look better (every number with . looks more reliable), but I don't think it will give as more information about actual distribution.

 > We can try graphing 'fraction of count in each bucket' instead on perf-dash

This one sounds really good. Especially the "fraction of count" part. Plotting this graphs on perf-dash is doable.

**Comment by shyamjvs** [comment]
Alright then, let's proceed that way. Btw - this approach in general would unlock a whole new class of metrics to be plottable on perf-dash.

**Comment by krzysied** [comment]
PR for perfdash changes: https://github.com/kubernetes/perf-tests/pull/160

**Comment by krzysied** [comment]
I've just updated [perf-dash](http://perf-dash.k8s.io/). It looks like it works fine.
![image](https://user-images.githubusercontent.com/25119199/42831323-53284ab4-89ee-11e8-97db-c3d354016b3d.png)

**Comment by stevekuznetsov** [comment]
Why is that using an interpolated spline for the data? That's implying there are valid values for the metrics between test runs and that the values are continuous and somehow related run-to-run, but neither of those is true, right?

**Comment by fejta** [comment]
What wwwww

**Comment by stevekuznetsov** [comment]
Not sure I understand the comment @fejta

**Comment by shyamjvs** [comment]
Closing this issue with both action items done. Etcd metrics are now available on http://perf-dash.k8s.io . Thanks!
/close
