### ISSUE TITLE
Env var expansion guidelines

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#64045]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-node-feature-requests 

**What happened**:
Before moving https://github.com/kubernetes/features/issues/559 to beta, we should have some further discussions about env expansion in general.  Specifically:
* Are there better ways to implement this?  Right now, each case of env expansion is handled independently at different points, and revalidation is considered specifically for each case.   Is a general/common solution feasible? 
* If not, can we identify some standard/criteria for what fields should be allowed for expansion, and how they should handle revalidation.

**Comment by msau42** [comment]
cc @kevtaylor

**Comment by thockin** [comment]
I don't think there is a general solution to revalidation, and there isn't a generic "do expansions" hook in the lifecycle.  Can you be more concrete in what you're proposing?  I'd love to be more rigourous here, if we can...

**Comment by msau42** [comment]
I wasn't proposing anything, just wanted to explore if there was a more general way we could do field expansion and not special-case each field.  After the last few discussions, I've come to the conclusion that a general in-place expansion mechanism is not feasible due to:

1. Breaking API compatibility
2. Timing challenges of revalidation of the fields after expansion
