### ISSUE TITLE
Flaky test: [sig-storage] Volume plugin streaming [Slow] GlusterFS should write files of various sizes, verify size, validate content

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#64047]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
[Test grid](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-slow&include-filter-by-regex=%5EOverall%24%7C%5C%5Bsig%5C-storage%5C%5D%5C%20Volume%5C%20plugin%5C%20streaming%5C%20%5C%5BSlow%5C%5D%5C%20GlusterFS%5C%20should%5C%20write%5C%20files%5C%20of%5C%20various%5C%20sizes%5C%2C%5C%20verify%5C%20size%5C%2C%5C%20validate%5C%20content)
Test logs: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/17143

**Comment by msau42** [comment]
cc @jeffvance would you be able to take a look?

**Comment by jarrpa** [comment]
@msau42 Exiting with 137 means a process was sent SIGKILL, I believe, and since there's no obvious sender for the signal I'd suspect oomkiller is killing dd. It wouldn't surprise me if this was a fluke. Has this happened more than once?

**Comment by msau42** [comment]
This test flakes maybe once a day if you take a look at the test grid.

There was an issue in the past where the grep command was crafted in such a way that it used up too much memory and got killed by kubelet.  Maybe something similar is happening here. See [this](https://github.com/kubernetes/kubernetes/issues/51717#issuecomment-326432956) for some background on how the old issue was triaged.

**Comment by jarrpa** [comment]
Ah, okay! Sorry, I wasn't sure how to read the test grid. I think I have a handle on it now. I'll follow the grep thread.

**Comment by jarrpa** [comment]
Digging through the logs of the current failure has not yielded anything similar to the issue you just linked. It could be that I'm just not looking in the right place. I'll set this down for now and see if I can get someone to look over it with me next week.

**Comment by jeffvance** [comment]
@jarrpa 's comments seem reasonable to me. @msau42 is there a different e2e env we should be using to `dd` larger files? Currently this test requires gci: `SkipUnlessNodeOSDistroIs("gci")`.

**Comment by msau42** [comment]
Were you able to find any kubelet logs indicating that we hit memory limits and containers had to be killed?

**Comment by jeffvance** [comment]
In kubelet log file _https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/17143/artifacts/bootstrap-e2e-minion-group-x0q9/kubelet.log_ I see exitcode 137 for nfs-io-client.

**Comment by msau42** [comment]
/remove-lifecycle stale

test is still flaking.  @humblec could you help take a look? It seems to be flaky most for gluster compared to other volume plugins

**Comment by humblec** [comment]
@msau42 missed this ping.  I am on it.
