### ISSUE TITLE
Phabricator example does not set proper minion scopes on GCE

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#6406]
As a result cloudsql_authenticator reports the following error:

ERROR: (gcloud.sql.instances.patch) Insufficient Permission

**Comment by fgrzadkowski** [comment]
To fix this user should set:

MINION_SCOPES=("storage-ro" "compute-rw" "https://www.googleapis.com/auth/monitoring", "sql-admin")

**Comment by thockin** [comment]
This solution needs more detail.  Is the only way to make this work to set that scope at cluster birth time?  The example needs to say that very clearly.  Is there a runtime fix?  This issue is months old - issues are not docs.
