### ISSUE TITLE
Failing test : [sig-instrumentation] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster is failing in sig-release-master-upgrade

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64075]
## Failing Job
* [gce-1.10-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-master)
* [gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)

## Failing Test
[[sig-instrumentation] Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster is failing in sig-release-master-upgrade](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1547)

## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=instrumentation&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel
This test has been consistently failing since  5/16 and here are the [commit changes](https://github.com/kubernetes/kubernetes/compare/dc3b127c1...9dee8190d)

/kind bug
/priority failing-test
/priority important-soon
/sig instrumentation
/milestone v1.11
@kubernetes/sig-instrumentation-bugs 

cc @jberkus @tpepper

/assign @DirectXMan12 

@DirectXMan12 @brancz  we are seeing consistent e2e tests failing in sig-release-master-upgrade jobs. Can you please triage this as priority and let us know if we can resolve it by Code flush (5/29)?

**Comment by serathius** [comment]
I think it's related to https://github.com/kubernetes/kubernetes/pull/62328 
Influx is no longer deployed by default and now has it's own test suite. I will check if it's possible to move this test to that suite

**Comment by AishSundar** [comment]
@serathius we will be entering Code flush for v1.11 next tuesday. Will it be possible to move this test out by then plz.

**Comment by serathius** [comment]
It should not be a problem.
