### ISSUE TITLE
High I/O K8S 1.6.13 / Nodes got NotReady State

### ISSUE THREAD

**Issue by hmarcelodn** [kubernetes/kubernetes#64108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

I have a kubernetes cluster created with acs-engine in Azure and I am getting down my nodes with "NotReady" state so the PODS are Terminating. I notice that this happened when the I/O disk is too high (I only see Read operations 100%) so I cannot even ssh into the VMs.

**What you expected to happen**:

I need to understand how to fix this. If it this increasing IOPS or running the nodes under some RAID solution.

**How to reproduce it (as minimally and precisely as possible)**:

I have created a 3 masters/3 nodes cluster using acs-engine tool for MS Azure.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

-Kuberntes: 1.6.13
-Cloud Provider: MS Azure
-OS: Ubuntu
-Kernel: Linux k8s-agentpool1-15972647-1 4.13.0-1016-azure #19-Ubuntu SMP Thu May 3 17:29:51 UTC 2018 x86_64 x86_64 GNU/Linux
Install Tool: ACS-Engine https://github.com/Azure/acs-engine

**Comment by hmarcelodn** [comment]
Hey can we get any answer on this? This is a very critical one... Any suggestion @islinwb ? Please refer to my issue https://stackoverflow.com/questions/50479212/kubernetes-nodelost-notready-high-io-disks?noredirect=1#comment87974672_50479212

**Comment by amritb** [comment]
Same here - happening for a couple of months now. We also created a support ticket **118021917667610**. But the support engg never got reply from backend devs.

> Hello,
> First, I want to apologize for the delay in getting back to you.
> I requested assistance on this issue from the back end team and this one seems to have fallen through the cracks.
> I have requested an update.
> --
> Dale Weiss
> Sr Support Escal Eng
> Azure Technical Support
> Customer Services and Support
