### ISSUE TITLE
APIService should support URL

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#64109]
/kind feature

The configuration Specs for APIServices and the Admission Webhook Configurations are very similar, but APIServices don't support specifying URL:

[APIServiceSpec](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go#L41):
```
type APIServiceSpec struct {
	// Service is a reference to the service for this API server.  It must communicate
	// on port 443
	// If the Service is nil, that means the handling for the API groupversion is handled locally on this server.
	// The call will simply delegate to the normal handler chain to be fulfilled.
	Service *ServiceReference `json:"service" protobuf:"bytes,1,opt,name=service"`
...
	// InsecureSkipTLSVerify disables TLS certificate verification when communicating with this server.
	// This is strongly discouraged.  You should use the CABundle instead.
	InsecureSkipTLSVerify bool `json:"insecureSkipTLSVerify,omitempty" protobuf:"varint,4,opt,name=insecureSkipTLSVerify"`
	// CABundle is a PEM encoded CA bundle which will be used to validate an API server's serving certificate.
	// +optional
	CABundle []byte `json:"caBundle,omitempty" protobuf:"bytes,5,opt,name=caBundle"`
...
}
```

[WebhookClientConfig](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L222) (from Validating/MutatingWebhookConfiguration):
```
type WebhookClientConfig struct {
	// `url` gives the location of the webhook, in standard URL form
	// (`[scheme://]host:port/path`). Exactly one of `url` or `service`
	// must be specified.
	//
	// The `host` should not refer to a service running in the cluster; use
	// the `service` field instead. The host might be resolved via external
	// DNS in some apiservers (e.g., `kube-apiserver` cannot resolve
	// in-cluster DNS as that would be a layering violation). `host` may
	// also be an IP address.
	//
	// Please note that using `localhost` or `127.0.0.1` as a `host` is
	// risky unless you take great care to run this webhook on all hosts
	// which run an apiserver which might need to make calls to this
	// webhook. Such installs are likely to be non-portable, i.e., not easy
	// to turn up in a new cluster.
	//
	// The scheme must be "https"; the URL must begin with "https://".
	//
	// A path is optional, and if present may be any string permissible in
	// a URL. You may use the path to pass an arbitrary string to the
	// webhook, for example, a cluster identifier.
	//
	// Attempting to use a user or basic auth e.g. "user:password@" is not
	// allowed. Fragments ("#...") and query parameters ("?...") are not
	// allowed, either.
	//
	// +optional
	URL *string `json:"url,omitempty" protobuf:"bytes,3,opt,name=url"`

	// `service` is a reference to the service for this webhook. Either
	// `service` or `url` must be specified.
	//
	// If the webhook is running within the cluster, then you should use `service`.
	//
	// Port 443 will be used if it is open, otherwise it is an error.
	//
	// +optional
	Service *ServiceReference `json:"service" protobuf:"bytes,1,opt,name=service"`

	// `caBundle` is a PEM encoded CA bundle which will be used to validate
	// the webhook's server certificate.
	// Required.
	CABundle []byte `json:"caBundle" protobuf:"bytes,2,opt,name=caBundle"`
}
```

The lack of a URL config in APIService can be worked around by creating a selector-less service and populating it with the URL you want, but this shouldn't be necessary.

**Comment by cjcullen** [comment]
@mikedanese @lavalamp @cheftako

**Comment by lavalamp** [comment]
Also @deads2k.

One technical reason this is harder is that the webhook can have an arbitrary path, but the aggregated apiserver can't really. So if you are operating this as a service, you need some other way of identifying the cluster the request is coming from.

**Comment by deads2k** [comment]
> The lack of a URL config in APIService can be worked around by creating a selector-less service and populating it with the URL you want, but this shouldn't be necessary.

The original pull had only a URL to proxy to, but @lavalamp [requested a service instead](https://github.com/kubernetes/kubernetes/pull/37561#discussion_r90325158) (some sort of analysis thing I think).  I don't think I object to a change, but it's not a priority for me either.

**Comment by lavalamp** [comment]
I think past me is right that if you're talking to a service installed in
the cluster, a URL is very lossy, and a service reference gives a lot more
information to anyone trying to do an automated dependency analysis on a
cluster.

I think past me wasn't thinking about the case where you want to run a
multitenant API-as-a-service thingy in some external place. But is there a
reason the workaround is insufficient? Otherwise it's not a priority for
me, either.
