### ISSUE TITLE
Flaky 1.8 sig-cli conformance test

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#64110]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: `[sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance]` sometimes fails testing on GCE / Kubernetes v1.8

**What you expected to happen**: I would expect this test case to pass consistently, it is the only flaking test case.

**How to reproduce it (as minimally and precisely as possible)**: Run the 1.8 conformance suite repeatedly.

**Anything else we need to know?**: Example results here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-1-8/129

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.14-beta.0 (Sorry, this is the tag not `kubectl version`)
- Cloud provider or hardware configuration: GCE cluster up (with kubetest provider GCE)
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by BenTheElder** [comment]
Actually looking back through the logs more, it's more broadly `kubectl` tests that flake:
 - `[sig-cli] Kubectl client [k8s.io] Kubectl run rc should create an rc from an image [Conformance]`
 - `[sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance]`

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-1-8/

**Comment by yue9944882** [comment]
@BenTheElder These flakes are all caused by network connection, and we could do nothing but retry when it happens. 
Should these test explicitly handle the network problem caused by test environment? OTOH maybe we could try to fix the network.

**Comment by BenTheElder** [comment]
Are you saying that the inter cluster networking is flaking or do these
rely on the broader internet?

I'm not sure what the best change would be, but the rest of the conformance
suite is not flaky in the slightest, which is why I question the
reliability of these tests. It's also possible that GCE 1.8 clusters are
flaky but given that the rest of the tests pass flawlessly many many times
I'd guess we just need to improve these tests...

**Comment by fturib** [comment]
@BenTheElder, @yue9944882 : we can see in the [test dashboard of "sig-sluster-lifecycle"](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce) or the [test dashboard of sig-network-gce](http://k8s-testgrid.appspot.com/sig-network-gce), that this serie of test "sig-cli" is falking when it is a deployment with kubeadm in gce. 
But looks like it does not depend the type of network used (default, ipvs, calico, flannel - although obviously calico has more issues).

and when the test fail, the error is always the same:
`could not convert scale update to external Scale: scheme.Scale is not suitable for converting to \"v1\"`

These same tests are not flaking, when the deployment is usual kube-up with gce. see here : http://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-coredns

Does it tilt a light for one of you ?

**Comment by BenTheElder** [comment]
@fturib I think that warrants its own, higher priority issue. these flake with low regularity in the oldest supported release. 

Also as a note, I am setting up GCE conformance tests for the ongoing release today (separate from master) and next week I plan to raise the question of blocking releases on a conformance suite.

**Comment by fturib** [comment]
I created an issue #64450 for these flaky sig-cli tests related to kubeadm/gce.

**Comment by BenTheElder** [comment]
thanks!
