### ISSUE TITLE
Enable support for swapless Kernels

### ISSUE THREAD

**Issue by ibadmin909** [kubernetes/kubernetes#64117]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**: Kubelet fails to start due to missing /proc/swaps file

**What you expected to happen**: The code must check if support for swap is enabled in the Kernel before attempting to open /proc/swaps

**How to reproduce it (as minimally and precisely as possible)**: Remove CONFIG_SWAP or CONFIG_SWAP=n in the Kernel config

**Anything else we need to know?**: No

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): Custom 4.14.40
- Install tools:
- Others:

**Comment by warmchang** [comment]
Add the "--fail-swap-on=false" para to enable kubelet run when the swap is enabled on the node.
