### ISSUE TITLE
Follow-ups for CRD versioning

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#64136]
Everything that must be done after https://github.com/kubernetes/kubernetes/pull/63830:

- missing tests:
  - [x] a test that actually checked what got persisted in etcd matched the storage version https://github.com/kubernetes/kubernetes/pull/63830/files#r189712166
  - [x] a test that set up a CRD, persisted some data, changed the version, and made sure the previously persisted data could be read https://github.com/kubernetes/kubernetes/pull/63830/files#r189712166
  - [x] a test that verified discovery docs tracked the CRD through creation, version addition, version removal, and deletion https://github.com/kubernetes/kubernetes/pull/63830/files#r189712166
  - [x] a test that tests that `spec.served` is respected https://github.com/kubernetes/kubernetes/pull/63830/files#r189712166
- [x] ~~@liggitt fix possibly flaking watches: https://github.com/kubernetes/kubernetes/pull/63830/files#r189710254~~ #64796 #65288
- [x] ~~@sttts: split `nopConverter` into orthogonal wrappers~~
  - ~~deep list converter calling an inner delegate~~
  - ~~special CRD `ConvertFieldLabel`~~
  - ~~the actual unstructured conversion~~ PR https://github.com/kubernetes/kubernetes/pull/64208
- [x] ~~@sttts: reuse the old NewVersionedNoxuInstance, instantiateVersionedCustomResource, testSimpleVersionedCRUD (and extend it with the version string) https://github.com/kubernetes/kubernetes/pull/63830/files#r189814105~~ PR https://github.com/kubernetes/kubernetes/pull/64204
- [x] @sttts: Define GA in API documentation of both APIServices and CRD Versions https://github.com/kubernetes/kubernetes/pull/63830/files#r189812365 – PR: #64215
- [x] ~~@sttts: Better logging for `removeDeadStorage` https://github.com/kubernetes/kubernetes/pull/63830/files#r189808872~~ PR: https://github.com/kubernetes/kubernetes/pull/64202

**Comment by mbohlool** [comment]
I don't think `split customresource_handler.go. This is far too big. Maybe we should create a CR scheme.~ falls into a follow up on #63830. It deserve its own issue. I think we must track things we missed/postponed to follow up in #63830 here.

**Comment by mbohlool** [comment]
@liggitt The link to the comment on flaky watch tests are not working. If you have the related issue/pr link handy, can you please put it here?

**Comment by sttts** [comment]
@mbohlool agree about "split customresource_handler.go". I want to approach that after 1.11 is out. But this has not too much to do with versioning.

**Comment by nilebox** [comment]
@sttts @mbohlool CRD versioning is still no-op (no webhook support) AFAIK? Should this issue be un-rotten?

**Comment by jpbetz** [comment]
I'll follow up on the missing tests. My basic plan is to add integration testing of conversion webhooks based on how we integration admission webhooks in test/integration/apiserver/admissionwebhook/admission_test.go. That way we'd have the conversion webhook handler in the integration test code (not as a published docker image like we use for e2e), once that's in place it should be relatively straightfoward to add the test cases described in this issue description. Feedback welcome!
