### ISSUE TITLE
ResourceVersion is not returned from LIST requests with fieldSelector

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#64147]
Reproduced at head:
```
wojtekt@e2e-test-wojtekt-master ~ $ curl localhost:8080/api/v1/namespaces/foo/pods
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/foo/pods",
    "resourceVersion": "3243"
  },
  "items": []
}
```

vs

```
wojtekt@e2e-test-wojtekt-master ~ $ curl localhost:8080/api/v1/namespaces/kube-system/pods?fieldSelector=metadata.name=foo
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/kube-system/pods"
  },
  "items": []
}
```

[The items part is correct, but there is no "resourceVersion" field set.]

@kubernetes/sig-api-machinery-bugs

**Comment by wojtek-t** [comment]
To clarify - the problem seems to appear only when there is no such underlying object.

**Comment by deads2k** [comment]
> To clarify - the problem seems to appear only when there is no such underlying object.

watch cache on or off?

**Comment by wojtek-t** [comment]
This seems to be the problematic line:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L398

[It's possible that something is wrong also in the cacher - so may be more than one bug actually.]

**Comment by wojtek-t** [comment]
I think that cacher is actually correct in this case :)

**Comment by wojtek-t** [comment]
It seems that switching this line:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L398

with:
```
return s.versioner.UpdateList(listObj, uint64(getResp.Header.Revision), "")
```

solves the problem

**Comment by wojtek-t** [comment]
though, it's not safe in general - I will send out a PR for it soon

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/64150 is out for review
