### ISSUE TITLE
Failing Test: [sig-network] Proxy version v1 should proxy to cadvisor using proxy subresource failing in sig-release-master-upgrade suite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64158]
## Failing Job
* [gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)
* [gke-gci-1.10-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel)

##Failing Test
[[sig-network] Proxy version v1 should proxy to cadvisor using proxy subresource failing in sig-release-master-upgrade suite](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3515#sig-network-proxy-version-v1-should-proxy-to-cadvisor-using-proxy-subresource)

## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=network&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel

This test started failing consistently in the upgrade jobs since 5/21 evening.

/kind bug
/priority failing-test
/priority important-soon
/sig network
/milestone v1.11
@kubernetes/sig-network-bugs 

cc @jberkus @tpepper

/assign @bjhaid 

@foxie @bjhaid  we are seeing consistent network e2e tests failing in sig-release-master-upgrade jobs. Can you please triage this as priority and let us know if we can resolve it by Code flush (5/29)?

**Comment by MrHohn** [comment]
Commit diff: https://github.com/kubernetes/kubernetes/compare/af69af2d3335803ceda21e33aac78b62d036062f...9eb0c3566808bb02de5ae6f43fa79da49718c864

Seems https://github.com/kubernetes/kubernetes/pull/63881 disabled the public cadvisor port by default. Guessing that is the cause?
@luxas

**Comment by AishSundar** [comment]
@luxas should this failing test also be handled as part of your change?

**Comment by luxas** [comment]
The "fix" here is to just not run this e2e test against a v1.11-upgraded cluster. How do we disable running that against v1.11 infra in the GCE test-infra? cc @krousey 

@AishSundar this is not a regression in terms of functionality, it's a test which is running although it shouldn't.

**Comment by BenTheElder** [comment]
@luxas which suites run are in the job args, https://github.com/kubernetes/test-infra/blob/038ec489c8dfb0e5c57cfc667a22002cb8c8876f/jobs/config.json#L6214

**Comment by luxas** [comment]
@BenTheElder and just making ginkgo skip that e2e for these upgrade suites sounds plausible to you?

**Comment by BenTheElder** [comment]
@luxas, yeah ginkgo flags should be controlling which testcases actually run, and I think we've done this before. @krzyzacy should be able to confirm.

**Comment by krzyzacy** [comment]
hummm, sounds like we should just remove this test?

**Comment by luxas** [comment]
@krzyzacy The e2e test in question was removed in v1.11, but it's still running apparently in v1.10-skewed upgraded clusters, which is the problem.

**Comment by krzyzacy** [comment]
@liggitt I forgot how did we handle this in 1.10? I thought we also disabled the test in the past release to work around, instead of use ginkgo skip, maybe you can confirm.

**Comment by liggitt** [comment]
like this: https://github.com/kubernetes/kubernetes/pull/61135/files#diff-e4236fde991a93836f485ce2d85ef8aa

**Comment by krzyzacy** [comment]
ah, great, thanks!

**Comment by AishSundar** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3599?log#log

**Comment by krzyzacy** [comment]
hummmm... @liggitt I'm a bit confused why #64184 doesn't work

**Comment by AishSundar** [comment]
As per @liggitt [this CL](https://github.com/kubernetes/kubernetes/pull/61289 ) shows the right method for skipping. @krzyzacy we should probably make the same change for this issue as well.

**Comment by AishSundar** [comment]
Tests are passing now !
