### ISSUE TITLE
csi in pod volume

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#64157]
/kind feature

**What happened**:
I could not use a csi driver from a pod directly, but have to use a pv.

**What you expected to happen**:
I was expecting to be able to use a csi driver directly in a pod

**Anything else we need to know?**:
The use case I'm trying to implement is: https://github.com/kubernetes-csi/drivers/issues/85

I have the driver working from the csi perspective. But when I went to hook it into Kubernetes, I ran into an issue. For the use case, the pod writer should be able to specify the image to use directly, rather then having an administrator need to create a pv with the image specified.

@saad-ali @lpabon

**Comment by kfox1111** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by jingxu97** [comment]
@kfox1111 , could you give some more details about how you want to deploy the driver? Normally system admin who has the root access can deploy the driver by running it in privileged containers.

**Comment by msau42** [comment]
This should be covered by https://github.com/kubernetes/enhancements/issues/596

**Comment by kfox1111** [comment]
I think this is far enough along now that I can close it. The ephemeral pod inline support in 1.14 covers the use case.
