### ISSUE TITLE
how to implement  ColumnDefinitions for CustomResource

### ISSUE THREAD

**Issue by m3ngyang** [kubernetes/kubernetes#64152]
I have implemented a crd source, and when I use `kubectl get`, only three columns are printed.
```
NAMESPACE                              NAME                   AGE
c0a1f165-6279-5320-b9e7-e0218c7a87f5   crd-xxxxxxxxxxxxxxxx   27d
c0a1f165-6279-5320-b9e7-e0218c7a87f5   crd-yyyyyyyyyyyyyyyy   27d
```
Printed columns of default Kubernetes types  are managed by xxxColumnDefinitions. I want to add columns to indicate some important indices and how to implement ColumnDefinitions for CRD resource ?

**Comment by swapnilgm** [comment]
You can use openapi annotations over resource type definition
`+k8s:openapi-gen=x-kubernetes-print-columns:custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,FIELD1:.spec.field1,STATUS:.status.Phase`
And use openapi code-generator to generate open api specification.

**Comment by liggitt** [comment]
> You can use openapi annotations over resource type definition

That is not applicable to CRD objects. Custom printing is on the roadmap (https://github.com/kubernetes/kubernetes/issues/58682) but not implemented yet. 

/close

**Comment by swapnilgm** [comment]
Oh. Thanks you @liggitt  for correcting me. I thought it was applicable to CRD as well.
