### ISSUE TITLE
Wire ConfigFlags as RESTClientGetter across commands

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#64164]
Now that most of the functionality provided to commands via the cmdutil.Factory has been decoupled from it via https://github.com/kubernetes/kubernetes/issues/64106, commands should no longer depend on the factory.

- Commands should mimic the pattern established by [NewCmdWait](https://github.com/kubernetes/kubernetes/pull/64034/files#diff-6b69c44761e2a603e92ab44a6bc16d4fR67), receiving a `genericclioptions.RESTClientGetter` in place of the `cmdutil.Factory`.

- Commands should also make use of the "CmdFlags" struct pattern ([as demonstrated here](https://github.com/kubernetes/kubernetes/pull/64034/files#diff-6b69c44761e2a603e92ab44a6bc16d4fR42) in order to bind their own flags, and provide a way to retrieve [an options struct from them](https://github.com/kubernetes/kubernetes/pull/64034/files#diff-6b69c44761e2a603e92ab44a6bc16d4fR98)).

- Further, commands should no longer make use of the `f.NewBuilder` method in order to retrieve a resource builer. Rather, they should make use of the new [ResourceBuilderFlags#ToBuilder](https://github.com/kubernetes/kubernetes/pull/64034/files#diff-6b69c44761e2a603e92ab44a6bc16d4fR103) method.

If a command requires the use of a REST client, they should no longer use the factory to retrieve one, but rather the methods provided by the `RESTClientGetter` [as seen here](https://github.com/kubernetes/kubernetes/pull/64034/files#diff-6b69c44761e2a603e92ab44a6bc16d4fR108).

cc @soltysh 

/sig cli

**Comment by ellenkorbes** [comment]
Quick update, I did take a good look over the related code during the weekend, but haven't managed to put together a contribution yet. I'll hit you guys up on Slack tomorrow with a few questions :)

**Comment by dims** [comment]
@soltysh @juanvallejo do we clear this milestone?

**Comment by soltysh** [comment]
@dims yes

**Comment by nikopen** [comment]
@juanvallejo @ellenkorbes ping, is this on track for 1.13? any related PR?

**Comment by soltysh** [comment]
Yes, this is still open and in-progress, but not something that we will actually finish for 1.13, it'll take us some more time.

**Comment by nikopen** [comment]
thanks! 
/milestone v1.14

**Comment by nikopen** [comment]
not there yet,

/milestone clear

**Comment by krmayankk** [comment]
Hello from  Bug Triage Shadow .  I'd like to remind that code freeze is coming in 3 days (Friday, 8th March). ❄️ 🏔 Is this still planned  to be fixed for 1.14?

**Comment by nikopen** [comment]
/milestone clear

we're in code freeze, doesn't look important. let me know if otherwise.
