### ISSUE TITLE
Flaking presubmits: abort in e2e-down.sh

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#64160]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**: Some presubmits are flaking, due to abort in e2e-down.sh

```
error during ./hack/e2e-internal/e2e-down.sh (interrupted): signal: aborted (core dumped)
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=core%20dump#b207af75a24889805b20

**What you expected to happen**: I would expect e2e-down.sh to exit cleanly and not cause an otherwise passing 1hr+ test (kubemark) to fail repeatedly.

**How to reproduce it (as minimally and precisely as possible)**: happens periodically in presubmits that use the cluster/* scripts.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by BenTheElder** [comment]
I'm going to hazard that cluster-lifecycle owns the cluster/* scripts
/sig cluster-lifecycle
/cc @AishSundar 
Initially this issue was aimed at the kubemark failures, but [looking at the triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=core%20dump#b207af75a24889805b20) it seems to be more widespread.

**Comment by AishSundar** [comment]
@kubernetes/sig-cluster-lifecycle-bugs 
/assign @timothysc 
/cc @dims

**Comment by BenTheElder** [comment]
/remove-sig cluster-lifecycle
/unassign @timothysc 
looks like we're timing, out, something must be taking longer (haven't had time to look more):
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63887/pull-kubernetes-kubemark-e2e-gce/91852/?log#log
cc @luxas

**Comment by BenTheElder** [comment]
hopefully we can close this after https://github.com/kubernetes/test-infra/pull/8112
