### ISSUE TITLE
kubelet reports wrong PVC metrics

### ISSUE THREAD

**Issue by dmitrievav** [kubernetes/kubernetes#64166]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
kubelet reports wrong PVC metrics for PVC which does not exist in the cluster any more.

curl -ks https://127.0.0.01:10250/metrics | grep es-persistent-storage-elasticsearch-logging-0
kubelet_volume_stats_available_bytes{namespace="kube-logging",persistentvolumeclaim="es-persistent-storage-elasticsearch-logging-0"} 5.8956210176e+10

**What you expected to happen**:

curl -ks https://127.0.0.01:10250/metrics | grep es-persistent-storage-elasticsearch-logging-0 | wc -l
0

**How to reproduce it (as minimally and precisely as possible)**:

did not test it yet. but try to create a pod which use PVC and then delete it.

**Anything else we need to know?**:

restarting kubelet solve the issue

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
```

- Kernel (e.g. `uname -a`):
Linux ip-10-8-202-28 4.4.111-k8s #1 SMP Sun Jan 14 19:32:08 UTC 2018 x86_64 GNU/Linux

- Install tools: KOPS
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
This seems to be dup of https://github.com/kubernetes/kubernetes/issues/57686. Please re-test with 1.8.8 or newer.

**Comment by dmitrievav** [comment]
Thank you and sorry as I tried but could not find it myself.

**Comment by jsafrane** [comment]
No problem, please report any issues you find in 1.8.8 or newer. 

/close
