### ISSUE TITLE
kubeadm join preflight errors should not be errors

### ISSUE THREAD

**Issue by cncook001** [kubernetes/kubernetes#64171]
/kind bug

**What happened**:
```
root@kube-test:~# kubeadm join 10.37.249.120:6443 --token <my token> --discovery-token-ca-cert-hash sha256<sha token>
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR DirAvailable--etc-kubernetes-manifests]: /etc/kubernetes/manifests is not empty
	[ERROR FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists
	[ERROR FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

**What you expected to happen**:
Only show errors when they really are errors

**How to reproduce it (as minimally and precisely as possible)**:
as root
```
kubeadm init --apiserver-advertise-address=10.37.249.120 --pod-network-cidr=192.168.0.0/16 
```
as a regular user
```
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml
kubectl taint nodes --all node-role.kubernetes.io/master-
```
as root user
```
kubeadm join 10.37.249.120:6443 --token <my token> --discovery-token-ca-cert-hash sha256:<sha token>
```

**Anything else we need to know?**:
Work around (note the ignore All errors)
```
kubeadm join 10.37.249.120:6443 --token <my token> --discovery-token-ca-cert-hash sha256:<sha token> --ignore-preflight-errors=All
```
When you see the error about 
```
/etc/kubernetes/pki/ca.crt already exists
```
and you delete that file, it leads to this error
```
[discovery] Failed to request cluster info, will try again: [Get https://10.37.249.120:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.37.249.120:6443: getsockopt: connection refused]
```
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Virtual Machine

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux kube-test 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
@kubernetes/sig-cluster-lifecycle

**Comment by cncook001** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by dims** [comment]
Please move this to https://github.com/kubernetes/kubeadm/issues/

/close
