### ISSUE TITLE
Add a new check to PodFitsResources to guarantee the pod limits must be less than the selected node's allocatable resource

### ISSUE THREAD

**Issue by ailusazh** [kubernetes/kubernetes#64185]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

 /kind feature

**What happened**:
When we create a burstable type pod, the pod requests may be much more smaller than the pod limits. If the other predicate conditions satisfied and the pod limits exceed the node's allocatable resource, currently the scheduler predicates can also pass. 

**What you expected to happen**:
I think the limit is the largest resource the pod expected. And the scheduler should meet the expectation of the pod.

**How to reproduce it (as minimally and precisely as possible)**:
For example, if my pod request is 6Cpu 6GB and limit is 10Cpu 10GB. And the node with 6Cpu 8GB may be selected as the node of my pod. But in fact, if my pod is scheduled to that node, and the pod can not get max resource 10Cpu 10GB as expected.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
Can you share your log? I tested it locally, it works with following limits.

@kubernetes/sig-node-bugs , any ideas on the behaviour when limits is bigger than capability of node? 

```shell
      limits:
        cpu: 10E
        memory: 2500000Gi
```

Refer to the following output for the detail:

```shell
# kc get pods nginx-76495ccfbc-75x6z
NAME                     READY     STATUS    RESTARTS   AGE
nginx-76495ccfbc-75x6z   1/1       Running   0          1m
```

```shell
# kc get pods nginx-76495ccfbc-75x6z -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-05-23T09:10:32Z
  generateName: nginx-76495ccfbc-
  labels:
    pod-template-hash: "3205177967"
    run: nginx
  name: nginx-76495ccfbc-75x6z
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-76495ccfbc
    uid: 257b5926-5e69-11e8-be7a-fc4dd4389306
  resourceVersion: "5574"
  selfLink: /api/v1/namespaces/default/pods/nginx-76495ccfbc-75x6z
  uid: 258986ff-5e69-11e8-be7a-fc4dd4389306
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        cpu: 10E
        memory: 2500000Gi
      requests:
        cpu: "1"
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-8xxv8
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 127.0.0.1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-8xxv8
    secret:
      defaultMode: 420
      secretName: default-token-8xxv8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-05-23T09:10:33Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-05-23T09:11:00Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-05-23T09:10:32Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c2b97baa3798246c503d4257b3f55581be692d4cc69130ecdadb082200235b68
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0fb320e2a1b1620b4905facb3447e3d84ad36da0b2c8aa8fe3a5a81d1187b884
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-05-23T09:10:59Z
  hostIP: 127.0.0.1
  phase: Running
  podIP: 172.17.0.9
  qosClass: Burstable
  startTime: 2018-05-23T09:10:33Z
```


**OS**: `Linux wgl-ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
**k8s version**:
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.1.439+535426bf736a31-dirty", GitCommit:"535426bf736a31edeb76cf64f3b6d90e6996e49a", GitTreeState:"dirty", BuildDate:"2018-05-01T07:14:55Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.2.117+57529e4acec69f-dirty", GitCommit:"57529e4acec69ff62cf7d619759274ee278d9910", GitTreeState:"dirty", BuildDate:"2018-05-23T08:01:16Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
**Docker version** :
```
# docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by k82cn** [comment]
PS: not sure whether that's a bug, seems no sig-node-misc group :)

**Comment by ailusazh** [comment]
Yeah, I noticed that too. For the community versions, it works fine.
 In our environment, we made customizations and limited the cpu subsystem of cgroup of kubepod to the node allocatable value.  Then cause the error in the case that settting a cpu.cfs_quota_fs value which is bigger than the node allocatable value  to container level cgroup. 
So I don't think this is a bug, but we still hope the community can add this feature. Because in our opinion, limit should be the largest resource users can use. And it's our commitment to our user that should allow the user use the resources within the limit they expected.

**Comment by k82cn** [comment]
In this case, I'd suggest to customize scheduler or use scheduler extender (maybe) for your environment; instead of a patch to upstream.

Your case seems reasonable; but we need to make scheduler and node/agent align.

**Comment by ailusazh** [comment]
OK, thank you for your attention :)

**Comment by zionwu** [comment]
I noticed this recently and I also think it is more reasonable to have resources limit less than node allocatable resources.

@k82cn @resouer, could you please help to explain why it is designed in the way that resources limit can exceed allocatable resources?
