### ISSUE TITLE
kube-dns sidecar ERROR

### ISSUE THREAD

**Issue by lurenjia528** [kubernetes/kubernetes#64197]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/kind request
/sig network

why  kubedns's parameter "--domain"(I0523 09:27:18.970487       1 server.go:113] FLAG: --domain="cluster.local.") not use my kube-dns.yml 's parameter "--domain" 
cluster.local     the last add a "."?

when I enter a container ,cat /etc/resolv.conf 
nameserver 8.8.8.8
nameserver 8.8.4.4

don't have "search default.svc.cluster.local svc.cluster.local cluster.local"?

the file /etc/resolv.conf modify by which service ?

**kubedns**
root@master1:~# kubectl logs -n kube-system kube-dns-6d7c49b69b-v4jqw kubedns
I0523 09:27:18.666957       1 dns.go:48] version: 1.14.5
I0523 09:27:18.970265       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0523 09:27:18.970360       1 server.go:113] FLAG: --alsologtostderr="false"
I0523 09:27:18.970387       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0523 09:27:18.970408       1 server.go:113] FLAG: --config-map=""
I0523 09:27:18.970423       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0523 09:27:18.970437       1 server.go:113] FLAG: --config-period="10s"
I0523 09:27:18.970454       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0523 09:27:18.970465       1 server.go:113] FLAG: --dns-port="10053"
I0523 09:27:18.970487       1 server.go:113] FLAG: --domain="cluster.local."
I0523 09:27:18.970504       1 server.go:113] FLAG: --federations=""
I0523 09:27:18.970520       1 server.go:113] FLAG: --healthz-port="8081"
I0523 09:27:18.970535       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0523 09:27:18.970547       1 server.go:113] FLAG: --kube-master-url=""
I0523 09:27:18.970565       1 server.go:113] FLAG: --kubecfg-file=""
I0523 09:27:18.970577       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0523 09:27:18.970609       1 server.go:113] FLAG: --log-dir=""
I0523 09:27:18.970622       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0523 09:27:18.970637       1 server.go:113] FLAG: --logtostderr="true"
I0523 09:27:18.970648       1 server.go:113] FLAG: --nameservers=""
I0523 09:27:18.970659       1 server.go:113] FLAG: --stderrthreshold="2"
I0523 09:27:18.970674       1 server.go:113] FLAG: --v="2"
I0523 09:27:18.970688       1 server.go:113] FLAG: --version="false"
I0523 09:27:18.970707       1 server.go:113] FLAG: --vmodule=""
I0523 09:27:18.970815       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0523 09:27:18.986716       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I0523 09:27:18.986753       1 dns.go:147] Starting endpointsController
I0523 09:27:18.986768       1 dns.go:150] Starting serviceController
I0523 09:27:18.986877       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0523 09:27:18.986916       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0523 09:27:19.487049       1 dns.go:171] Initialized services and endpoints from apiserver
I0523 09:27:19.487085       1 server.go:129] Setting up Healthz Handler (/readiness)
I0523 09:27:19.487104       1 server.go:134] Setting up cache handler (/cache)
I0523 09:27:19.487123       1 server.go:120] Status HTTP port 8081

**dnsmasq**
root@master1:~# kubectl logs -n kube-system kube-dns-6d7c49b69b-v4jqw dnsmasq
I0523 09:27:18.770868       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0523 09:27:18.941673       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0523 09:27:19.778031       1 nanny.go:108] dnsmasq[26]: started, version 2.78-security-prerelease cachesize 1000
I0523 09:27:19.778108       1 nanny.go:108] dnsmasq[26]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0523 09:27:19.778128       1 nanny.go:108] dnsmasq[26]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0523 09:27:19.778157       1 nanny.go:108] dnsmasq[26]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0523 09:27:19.778024       1 nanny.go:111] 
W0523 09:27:19.778238       1 nanny.go:112] Got EOF from stdout
I0523 09:27:19.778192       1 nanny.go:108] dnsmasq[26]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0523 09:27:19.778329       1 nanny.go:108] dnsmasq[26]: no servers found in /etc/resolv.conf, will retry
I0523 09:27:19.778431       1 nanny.go:108] dnsmasq[26]: read /etc/hosts - 7 addresses

**sidecar**
root@master1:~# kubectl logs -n kube-system kube-dns-6d7c49b69b-v4jqw sidecar
ERROR: logging before flag.Parse: I0523 09:27:19.750812       1 main.go:48] Version v1.14.5
ERROR: logging before flag.Parse: I0523 09:27:19.751000       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
ERROR: logging before flag.Parse: I0523 09:27:19.751081       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
ERROR: logging before flag.Parse: I0523 09:27:19.751221       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}

**kube-dns.yml**

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.96.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: Default
      serviceAccountName: kube-dns
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: kube-dns-config
        configMap:
          name: kube-dns
          optional: true
      containers:
      - name: kubedns
        image: kylincloud2.hub/k8s-dns-kube-dns-arm64:1.14.5   
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          httpGet:
            path: /healthcheck/kubedns
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 5
        args:
        - --domain=cluster.local
        - --dns-port=10053
        - --v=2
        - --config-dir=/kube-dns-config
        env:
        - name: PROMETHEUS_PORT
          value: "10055"
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
        - containerPort: 10055
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: kube-dns-config
          mountPath: /kube-dns-config
      - name: dnsmasq
        image: kylincloud2.hub/k8s-dns-dnsmasq-nanny-arm64:1.14.5
        livenessProbe:
          httpGet:
            path: /healthcheck/dnsmasq
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - "-v=2"
        - "-logtostderr"
        - "-configDir=/etc/k8s/dns/dnsmasq-nanny"
        - "-restartDnsmasq=true"
        - "--"
        - "-k"
        - "--cache-size=1000"
        - "--log-facility=-"
        - "--server=/cluster.local/127.0.0.1#10053"
        - "--server=/in-addr.arpa/127.0.0.1#10053"
        - "--server=/ip6.arpa/127.0.0.1#10053"
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 20Mi
        volumeMounts:
        - name: kube-dns-config
          mountPath: /etc/k8s/dns/dnsmasq-nanny
      - name: sidecar
        image: kylincloud2.hub/k8s-dns-sidecar-arm64:1.14.5  
        livenessProbe:
          httpGet:
            path: /metrics
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - "--v=2"
        - "--logtostderr"
        - "--probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A"
        - "--probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A"
        ports:
        - containerPort: 10054
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: 20Mi
            cpu: 10m

**Environment**:
k8s version:1.9.4
arm64 ubuntu16.04

**Comment by thockin** [comment]
The trailing dot is the canonicalized form of the domain and is strictly correct.

The fact that your resolv.conf doesn't work is something else entirely.  Are you passing DNS flags to kubelet?
