### ISSUE TITLE
`kubectl cp --as=root` does not act as root

### ISSUE THREAD

**Issue by OndraZizka** [kubernetes/kubernetes#64195]
/kind bug
/sig apps

**What happened**:
--as=root seems not to have any effect:
```
+ rm -rf ./gatlingResults
+ mkdir -p ./gatlingResults
+ kubectl cp --as=root h3046-gatling-test:/tmp/testResults ./gatlingResults
tar: removing leading '/' from member names
tar: /tmp/testResults/lost+found: Permission denied
tar: error exit delayed from previous errors
+ ls ./gatlingResults/
lost+found
```

**What you expected to happen**:
As per the [documentation](https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_cp.md), --as=root should make root the "Username to impersonate for the operation".
Instead, it runs as non-root.
 
**How to reproduce it (as minimally and precisely as possible)**:
Create a pod.
Create a directory in it. In my case, it was a mounted PVC in AWS EKS. That could be important.
Run `kubectl cp <pod>:/<dir> ./foo`
Due to another bug, it will try to copy `/lost+found` which is owned by `root`. This bug will make that fail because it's not impersonating root.
 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS EKS

- OS (e.g. from /etc/os-release): Alpine Linux
- Kernel (e.g. `uname -a`): Current latest
- Install tools: Helm

**Comment by liggitt** [comment]
`--as` controls the username used to make the API request. it has no bearing on the uid processes are run as inside the container.

/close
