### ISSUE TITLE
Link to `kubernetes cp` docs dead

### ISSUE THREAD

**Issue by OndraZizka** [kubernetes/kubernetes#64194]
kind/bug

https://kubernetes.io/docs/reference/kubectl/kubectl/
leads to
https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_cp.md
which is 404.

**Comment by shubheksha** [comment]
@OndraZizka, kubernetes docs live in a separate repo. Can you please file this [there](https://github.com/kubernetes/website/issues/new)?

**Comment by CaoShuFeng** [comment]
/close

https://github.com/kubernetes/website/pull/8651
