### ISSUE TITLE
kube-proxy iptables-restore conntrack ERROR

### ISSUE THREAD

**Issue by lurenjia528** [kubernetes/kubernetes#64193]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/kind request
/sig network

arm64 ubuntu 
**What happened**:
E0523 18:32:14.075223       1 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed)

Failed to delete stale service IP 10.96.0.10 connections, error: error deleting connection tracking state for UDP service IP: 10.96.0.10, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH

![image](https://user-images.githubusercontent.com/37833630/40421411-6a927914-5ebe-11e8-8b02-61f8027a02a1.png)
![image](https://user-images.githubusercontent.com/37833630/40421463-9f3003f8-5ebe-11e8-9eb3-906b25bfed33.png)
![image](https://user-images.githubusercontent.com/37833630/40421505-bbb3d3d8-5ebe-11e8-8bf9-4085aceab8b8.png)

I had install conntrack(apt-get install conntrack),but kube-proxy still (Failed ...conntrack...)

**Environment**:
![image](https://user-images.githubusercontent.com/37833630/40421351-366d43d0-5ebe-11e8-9d2a-5cb8735096e1.png)
![image](https://user-images.githubusercontent.com/37833630/40421779-95980ab0-5ebf-11e8-9fab-753c196c06d4.png)

![image](https://user-images.githubusercontent.com/37833630/40421324-1c59e21e-5ebe-11e8-90bd-2e018a41bde1.png)

how can i fix it

**Comment by islinwb** [comment]
cc @Lion-Wei

**Comment by thockin** [comment]
Try running kube-proxy with `--v=4` and it will dump the full command it is executing

**Comment by opsnull** [comment]
same issue here

**Comment by thockin** [comment]
same request: Try running kube-proxy with --v=4 and it will dump the full command it is executing

**Comment by thockin** [comment]
same request: Try running kube-proxy with --v=4 and it will dump the full command it is executing

**Comment by martynd** [comment]
Having also got the ```Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)``` error I figured id give providing some useful info a whirl @thockin 

Its worth noting that I didnt get the later conntrack error at all, but I dont believe that is of direct relevance here since the reporter still got the iptables-restore error after resolving the conntrack one

This is also kube-proxy 1.9.x, specifically 1.9.10

The command ran was
```iptables-restore -T nat --noflush --counters```

Assuming the previous commands (```iptables-save -t nat```) stdout goes directly to stdin for the second, line 7 would be:
```:DOCKER - [0:0]```

I didnt notice anything in the code, but in case any stripping goes on, the top 20 lines from a manual execution of the iptables-save command (from inside the kube-proxy container) is as follows:
```# Generated by iptables-save v1.6.0 on Sun Aug  5 22:41:56 2018
*nat
:PREROUTING ACCEPT [249:20801]
:INPUT ACCEPT [94:11291]
:OUTPUT ACCEPT [75:15275]
:POSTROUTING ACCEPT [139:19285]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-223C5RHMC32OQIJT - [0:0]
:KUBE-SEP-243TDJ7432ZJMW3Y - [0:0]
:KUBE-SEP-2AQPUFCTD6D35A4N - [0:0]
:KUBE-SEP-3IAY7U5KE6BOCNLQ - [0:0]
:KUBE-SEP-3NNTLEUZ6H3YWGDY - [0:0]
:KUBE-SEP-3Q446XHIPIIIZXEJ - [0:0]
:KUBE-SEP-464OEKW73JEEFJY5 - [0:0]
:KUBE-SEP-47CXPTOUUKYVQSYQ - [0:0]
:KUBE-SEP-4KGRSRXAM7IGI4ZH - [0:0]```

Hope that helps!

Thank you

**Comment by opsnull** [comment]
#68447

**Comment by opsnull** [comment]
@thockin 

> 9月 10 22:36:49 m7-power-k8s01 kube-proxy[18759]: I0910 22:36:49.034674   18759 iptables.go:315] running iptables-save [-t nat]
> 9月 10 22:36:49 m7-power-k8s01 kube-proxy[18759]: I0910 22:36:49.077471   18759 iptables.go:374] running iptables-restore [--wait=2 -T nat --noflush --counters]
> 9月 10 22:36:49 m7-power-k8s01 kube-proxy[18759]: E0910 22:36:49.090220   18759 proxier.go:699] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
> 9月 10 22:36:49 m7-power-k8s01 kube-proxy[18759]: )

```
$ iptables-restore --version
iptables-restore v1.4.21
```

**Comment by fenixshadow2005** [comment]
Still met the same error, any workaround or solution for it?
