### ISSUE TITLE
`kubectl cp <pod>:/foo/bar ...` does not copy the directory but `/` instead

### ISSUE THREAD

**Issue by OndraZizka** [kubernetes/kubernetes#64199]
/kind bug
/sig apps

**What happened**:
`kubectl cp <pod>:/foo/bar ./bar does not copy the directory but `/` instead:
```
+ rm -rf ./gatlingResults
+ mkdir -p ./gatlingResults
+ kubectl cp --as=root h3046-gatling-test:/tmp/testResults ./gatlingResults
tar: removing leading '/' from member names
tar: /tmp/testResults/lost+found: Permission denied
tar: error exit delayed from previous errors
```

**What you expected to happen**:
As per the documentation, this should copy the `/foo/bar` directory to local filesystem.
Instead, it tries to copy files from `/` (root dir). Together with issue #64195, this makes it a critical issue because it's not possible to copy the content at all. One needs to install zip, zip whats needed, move it, and `kubectl cp` from there.
It's not possible to use a path without `/` because that copies from the WORKDIR (IIRC).
 
**How to reproduce it (as minimally and precisely as possible)**:
Create a pod e.g. from alpine/openjdk:8.
Create a directory in it. In my case, it was a mounted PVC in AWS EKS. That could be important.
Run `kubectl cp <pod>:/<dir> ./foo`
It will try to copy `/lost+found` which is located in `/`. So it's clearly not copying the specified directory.
 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS EKS

- OS (e.g. from /etc/os-release): Alpine Linux
- Kernel (e.g. `uname -a`): Current latest
- Install tools: Helm

**Comment by brendandburns** [comment]
I don't think this is a real issue.

You are trying to copy from 

`/tmp/testResults`

The error message is saying:

Can't read from `/tmp/testResults/lost+found` inside the container.

Which is consistent with the directory you tried to copy from.

So you need to adjust the permissions on `/tmp/testResults/lost+found` to make this work correctly

I tried to reproduce this locally, and I can't.
