### ISSUE TITLE
kube-apiserver failed to start after adding oidc parameters

### ISSUE THREAD

**Issue by fengpinghu** [kubernetes/kubernetes#64206]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
after adding the oidc parameters, the kube-apiserver pod remains  failing to start.
kube-apiserver starts ok after those lines are removed.
**What you expected to happen**:
kube-apiserver start with the oidc parameters added
**How to reproduce it (as minimally and precisely as possible)**:
added following lines to kube-apiserver.yaml and then copy the file to /etc/kubernetes/manifests
    - --oidc-issuer-url=https://xxx.xxx.xxx.xxx:32000/dex
    - --oidc-client-id=loginapp
    - --oidc-ca-file=/etc/kubernetes/ssl/ca.pem
    - --oidc-username-claim=name

**Anything else we need to know?**:

logs:

May 22 23:39:18 xxx.xxx.xxx.xxx kubelet[6787]: E0522 23:39:18.521099    6787 file_linux.go:114] Can't process manifest file "/etc/kubernetes/man
ifests/4913": open /etc/kubernetes/manifests/4913: no such file or directory
May 22 23:39:18 xxx.xxx.xxx.xxx kubelet[6787]: E0522 23:39:18.524226    6787 kubelet.go:1617] Failed creating a mirror pod for "kube-apiserver-xxx.xxx.xxx.xxx_kube-system(3b16588fbf7a62b042080cc974eecc97)": Post https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/kube-system/pods: dial tcp xxx.xxx.xxx:6443: getsockopt: connection refused

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux xx.xx.xxx.xx 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm
- Others:
/sig oidc

**Comment by liggitt** [comment]
is `/etc/kubernetes/ssl/ca.pem` available within your apiserver pod?

does `curl --cacert /etc/kubernetes/ssl/ca.pem https://xxx.xxx.xxx.xxx:32000/dex` successfully connect?

**Comment by ericchiang** [comment]
```
May 22 23:39:18 xxx.xxx.xxx.xxx kubelet[6787]: E0522 23:39:18.521099 6787 file_linux.go:114] Can't process manifest file "/etc/kubernetes/man
ifests/4913": open /etc/kubernetes/manifests/4913: no such file or directory
May 22 23:39:18 xxx.xxx.xxx.xxx kubelet[6787]: E0522 23:39:18.524226 6787 kubelet.go:1617] Failed creating a mirror pod for "kube-apiserver-xxx.xxx.xxx.xxx_kube-system(3b16588fbf7a62b042080cc974eecc97)": Post https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/kube-system/pods: dial tcp xxx.xxx.xxx:6443: getsockopt: connection refused
```

This seems like an issue with static pods, possibly https://github.com/kubernetes/kubernetes/issues/48219

Does your API server start? Do you have logs from that? Did you modify your static manifest in place? If so what happens when you just start the API with the flags instead of modifying an existing static manifest?

**Comment by ericchiang** [comment]
ref https://github.com/kubernetes/kubernetes/pull/63910

It seems like you've got a numeric file created by vim

```
ifests/4913": open /etc/kubernetes/manifests/4913: no such file or directory
```

**Comment by fengpinghu** [comment]
Hi Jordan,

Thanks for the quick reply. You are right. I am new to the kubernetes world
and somehow assumed the pod can see the file on the host.
I just got that mounted and everything is good now.

As a side note the error msg seems is a little off in this case otherwise
it could be a more straightforward problem for a normal user.

Thanks,
Fengping

**Comment by fengpinghu** [comment]
Thanks Eric, at one point I thought that was the problem too but my
manifest directory is clean.
as I replied to Jordan, the only complain from me is the error msgs seems
off.

in this case, /etc/kubernetes/ssl/ca.pem file is not accessible because I
didn't mount the volume, but the error msg somehow is complaining about
/etc/kubernetes/manifests/4913 file not accessible.

Thanks,
Fengping

**Comment by ericchiang** [comment]
Awesome. I'm going to close this in favor of #48219 and #63910 which are opened to address this issue.

/close
