### ISSUE TITLE
ip-masq-agent does not set the rules correctly

### ISSUE THREAD

**Issue by kavehmz** [kubernetes/kubernetes#64212]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I have a GKE cluster which master and nodes are both at `1.10.2-gke.1`.

I wanted to set ip-masq based on the following document:

https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/

This is something I have done in older version of kubernetes with no issue.

After setting my config as: 

```
nonMasqueradeCIDRs:
  - 172.17.0.0/16
  - 10.32.0.0/16
  - 192.168.0.0/24
resyncInterval: 60s
```

I see in the nodes my settings are applied but there is another set of rules too which stay with no change!

```
$ iptables-save |grep -i IP-MASQ
:IP-MASQ - [0:0]
:IP-MASQ-AGENT - [0:0]
-A POSTROUTING -m comment --comment "ip-masq: ensure nat POSTROUTING directs all non-LOCAL destination traffic to our custom IP-MASQ chain" -m addrtype ! --dst-type LOCAL -j IP-MASQ
-A POSTROUTING -m comment --comment "ip-masq-agent: ensure nat POSTROUTING directs all non-LOCAL destination traffic to our custom IP-MASQ-AGENT chain" -m addrtype ! --dst-type LOCAL -j IP-MASQ-AGENT
-A IP-MASQ -d 169.254.0.0/16 -m comment --comment "ip-masq: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ -d 10.0.0.0/8 -m comment --comment "ip-masq: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ -d 172.16.0.0/12 -m comment --comment "ip-masq: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ -d 192.168.0.0/16 -m comment --comment "ip-masq: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ -m comment --comment "ip-masq: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE
-A IP-MASQ-AGENT -d 169.254.0.0/16 -m comment --comment "ip-masq-agent: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ-AGENT -d 172.17.0.0/16 -m comment --comment "ip-masq-agent: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ-AGENT -d 10.32.0.0/16 -m comment --comment "ip-masq-agent: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ-AGENT -d 192.168.0.0/24 -m comment --comment "ip-masq-agent: local traffic is not subject to MASQUERADE" -j RETURN
-A IP-MASQ-AGENT -m comment --comment "ip-masq-agent: outbound traffic is subject to MASQUERADE (must be last in chain)" -j MASQUERADE
```

There seems to be two sets of rule `IP-MASQ-AGENT ` and `IP-MASQ`. and `IP-MASQ` stays with no change.

What I have is an standard GKE setup.

**What you expected to happen**:

I was expecting to see my `nonMasqueradeCIDRs` settings in iptable rules as usual. But I have no idea where the second set of rule are coming from (`IP-MASQ`) which are not changing and are as default.

**How to reproduce it (as minimally and precisely as possible)**:

Create a GKE cluster in  a Google project with standard `ip-masq-agent` installed.

Create a file named config with the content I mentioned

```
nonMasqueradeCIDRs:
  - 172.17.0.0/16
  - 10.32.0.0/16
  - 192.168.0.0/24
resyncInterval: 60s
```

then create the configmap:

```
 kubectl create configmap ip-masq-agent --from-file=config --namespace=kube-system
```

**Anything else we need to know?**:

In my setup I set the `container address range` to `172.170.0/16`

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.1", GitCommit:"75d2af854b1df023c7ce10a8795b85d3dd1f8d37", GitTreeState:"clean", BuildDate:"2018-05-10T17:23:18Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Google
- OS (e.g. from /etc/os-release): - 
- Kernel (e.g. `uname -a`): -
- Install tools: - 
- Others: -

**Comment by venub-234105** [comment]
Hi, I'm seeing the same issue. Was there anything specific that needs to be done to resolve this issue? Please let me know. Thanks!
