### ISSUE TITLE
kubeadm fails after v1.12.0-alpha.0 tag was added to the repository

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#64241]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

When [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) is trying to run `kubeadm join` on a node, it fails with the following error:
```
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.12" ConfigMap in the kube-system namespace
configmaps "kubelet-config-1.12" is forbidden: User "system:bootstrap:rs98sv" cannot get configmaps in the namespace "kube-system
```

**What you expected to happen**:
`kubeadm join` works

**How to reproduce it (as minimally and precisely as possible)**:
Use [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) or just kubeadm (unchecked, but likely will behave similarly) with current Kubernetes master (tried with 420071d86e0e1b9ea06c9be31cfcd5489d7c29c7 for example)

**Anything else we need to know?**:
This happened because after `v1.12.0-alpha.0` tag was added, kubeadm decided to start using dynamic kubelet config:
https://github.com/kubernetes/kubernetes/blob/b5cd7d81bdb4e7bf9298a618fce06afa70eebc83/cmd/kubeadm/app/constants/constants.go#L299
https://github.com/kubernetes/kubernetes/blob/HEAD/cmd/kubeadm/app/phases/kubelet/config.go#L64

But apparently it's not working yet.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.12.0-alpha.0.281+420071d86e0e1b-dirty (one of the checked versions)
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3, CircleCI environment
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ivan4th** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by dixudx** [comment]
This was introduced in #63887.

@luxas RBAC role bindings are not bound to bootstrap tokens, right?

**Comment by luxas** [comment]
First now noticed that this is in the k/k repo, not the kubeadm one. Please reopen in kubeadm so we can track. Bootstrap Tokens should be able to access the configmap yes, but we're in an in-between state of PRs to make that happen end to end. If you have time to make that change @dixudx and test end to end it'd be very helpful

**Comment by dixudx** [comment]
@luxas I will have a e2e test on this. Will fix it if it is really a bug.

**Comment by speneker** [comment]
Where is the fix for this?

[discovery] Trying to connect to API Server "172.17.15.14:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://172.17.15.14:6443"
[discovery] Requesting info from "https://172.17.15.14:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "172.17.15.14:6443"
[discovery] Successfully established connection with API Server "172.17.15.14:6443"
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.12" ConfigMap in the kube-system namespace
configmaps "kubelet-config-1.12" is forbidden: User "system:bootstrap:egbfak" cannot get configmaps in the namespace "kube-system"

**Comment by neolit123** [comment]
this can happen if the kubeadm version of a node that tries to join a cluster is lower than the kubelet version of the master node.

please, try having both kubelet and kubeadm to be version 1.12 on all nodes!

**Comment by speneker** [comment]
[root@bmmaster1 ~]# kubectl get nodes
NAME                   STATUS   ROLES    AGE   VERSION
bm2.seibels.bm         Ready    <none>   1d    v1.12.0
bm3.seibels.bm         Ready    <none>   1d    v1.12.0
bmmaster1.seibels.bm   Ready    master   1d    v1.12.0
[root@bmmaster1 ~]#

**Comment by speneker** [comment]
bm1 is at latest version v1.12.0 and fails join

**Comment by neolit123** [comment]
does the failing node have kubeadm 1.12 and kubelet 1.12?

**Comment by neolit123** [comment]
if yes, please log an issue in the `kubernetes/kubeadm` repository and explain your setup in detail.
