### ISSUE TITLE
ErrorToAPIStatus could be more informative about unexpected errors

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#64244]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
I am suffering from mysterious timeouts.  See https://github.com/kubernetes/kubernetes/issues/63608#issuecomment-391497458 for the evidence from my latest investigation.  It includes this line

```
E0523 18:59:53.086835       1 status.go:64] apiserver received an error that is not an metav1.Status: timeout
```

from the `ErrorToAPIStatus` function in `staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go`.   The relevant line is this:

```
	runtime.HandleError(fmt.Errorf("apiserver received an error that is not an metav1.Status: %v", err))
```

I still do not know the type of the error in question or where it is coming from.  It would be helpful if the log message included the type of the error object --- such as with `fmt.Sprintf("%T", err)` or, if that does not include the type's package name, perhaps something that would really nail the type.

**What you expected to happen**:
I would expect more information about an unexpected type of error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by hzxuzhonghu** [comment]
@MikeSpreitzer I think this timeout is from resourcequota admission. Did you enable `ResourceQuota` admission plugin? 

will create a pr to make ResourceQuota return `StatusError` err.

**Comment by MikeSpreitzer** [comment]
@hzxuzhonghu thanks for the suggestion, I will respond in the original issue.

**Comment by MikeSpreitzer** [comment]
I appreciate @hzxuzhonghu removing a source of errors of unexpected type, _this_ issue is about what to do whenever an unexpected type of error _does_ arrive.  I suggest formatting it with `%#+v` instead of `%v`.

**Comment by MikeSpreitzer** [comment]
/reopen
That PR did not really fix _this_ issue.
