### ISSUE TITLE
AWS Changing from External ELB to Internal ELB doesn't work

### ISSUE THREAD

**Issue by bizzelicious** [kubernetes/kubernetes#64251]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig aws

**What happened**:
Adding annotation `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` to an existing, external elastic load balancer doesn't recreate the load balancer as an internal one. The load balancer will stay as an External load balancer.

**What you expected to happen**:
The external ELB to be removed and then an internal ELB to be created.

**How to reproduce it (as minimally and precisely as possible)**:
Create an External ELB, when it's up and running. Try changing it to an Internal one using annotation `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`

**Anything else we need to know?**:
Deleting the service and recreating it with the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` works as expected since the external ELB gets removed with the service deletion.

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release):
`Debian GNU/Linux 8 (jessie)`

- Kernel (e.g. `uname -a`):
`Linux ip-10-198-9-249 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux`

- Install tools:

- Others:
Kops 1.8.7

**Comment by Bizzelicious** [comment]
Might be the same issue as: #60393

**Comment by ludat** [comment]
This is still happening
