### ISSUE TITLE
Generating kubernetes secret from result of a script/command

### ISSUE THREAD

**Issue by aggarwalShivani** [kubernetes/kubernetes#64256]
I have a scenario where I need to run a command (basically a curl command) and the output of that has to be stored as a kubernetes secret which can be used later by other kubernetes resources.

Is this possible currently??

**What happened**:
This is the secret.yaml used >

     1 apiVersion: v1
     2 kind: Secret
     3 metadata:
     4   name: token-secret-1
     5 type: Opaque
     6 data:
     7    password: $(hostname | base64)

When i tried to create a k8s secret with this file, i got the following **error**:

Error from server (BadRequest): error when creating "secret.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret: ObjectMeta: v1.ObjectMeta: TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, parsing 66 ...| base64)"... at {"apiVersion":"v1","data":{"password":"$(hostname | base64)"},"kind":"Secret","metadata":{"name":"token-secret","namespace":"default"},"type":"Opaque"}

**What you expected to happen**:
I expected the command  i.e. $hostname in line 7 (secret.yaml) to get executed and its output encoded with base64 and stored as a secret.

**How to reproduce it (as minimally and precisely as possible)**:
 kubectl create -f secret.yaml
(with the file contents as shown above)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- OS (e.g. from /etc/os-release): RHEL 7.4

**Comment by whereisaaron** [comment]
YAML files are declarative, they don run anything or do shell substitutions.

You can do what you want in a script using a here-doc, e.g.
```
#!/bin/bash

kubectl apply -f - <<END
apiVersion: v1
kind: Secret
metadata:
  name: token-secret-1
type: Opaque
data:
   password: $(hostname | base64)
END
```

**Comment by liggitt** [comment]
Or `kubectl create secret my-secret --from-literal "password=$(hostname)"`

**Comment by bkalai321** [comment]
#!/bin/bash
set -e

regex="docker login -u (.+) -p (.+) -e (.+) (.+)"
if [[ $(python -m awscli  ecr get-login) =~ $regex ]]
then
  login=$(echo "${BASH_REMATCH[1]}:${BASH_REMATCH[2]}" | base64)
  echo "Configuring registry ${BASH_REMATCH[4]:8}..."
  dockerconfig="{\"auths\":{\"${BASH_REMATCH[4]:8}\":{\"auth\": \"${login}\"}}}"
  dockerconfigjson=$(echo ${dockerconfig} | base64)
  secret="apiVersion: v1\nkind: Secret\nmetadata:\n  name: aws-ecr-credentials\ndata:\n  .dockerconfigjson: ${dockerconfigjson}\ntype: kubernetes.io/dockerconfigjson"
  echo -e ${secret} | kubectl replace -f - --force
  cat <<EOF

**Comment by bluephone** [comment]
Have you tried to use the `stringData` field. It allows you to put a non-base64 encoded string into a Secret.

```
1 apiVersion: v1
2 kind: Secret
3 metadata:
4   name: token-secret-1
5 type: Opaque
6 stringData:
7   password: $(hostname)
```
