### ISSUE TITLE
multi container pods stuck "Terminating"  after deleting deployment 

### ISSUE THREAD

**Issue by bilalyasar** [kubernetes/kubernetes#64268]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**: i have multi container pods, 1 main container and 4 alpine container to tail log files. when i delete deployment it stays "Terminating" state always

**What you expected to happen**: pods should be terminated and removed from the list

**How to reproduce it (as minimally and precisely as possible)**: use k8s 1.8.13, create multicontainer pod, 1 tomcat container + 4 alpine container for the tailing logs. and deploy --> delete it

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.13
- Cloud provider or hardware configuration: kops - aws
- OS (e.g. from /etc/os-release): default kops settings
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

i also see following logs:
```
rpc error: code = Unknown desc = Error: No such container: xxxxxxxxxxxxxxxx%
```
// @kubernetes/sig-node-bugs

**Comment by yadavkkumar** [comment]
@bilalyasar can u provide the yaml file which you are using.
