### ISSUE TITLE
Serviceaccount - access through api

### ISSUE THREAD

**Issue by proseti** [kubernetes/kubernetes#64273]
I created namespace 'xxx', role for this namespace with get pods, services, etc; created serviceaccount 'yyy'; created rolebinding 'yyy' to role in namespace 'xxx'.
When I try to check smth through API with secret token , for example:
curl -kD - -H "Authorization: Bearer $TOKEN https://localhost:6443/api/v1/namespaces/xxx/pods
I get 403 forbidden error.
So I make clusterrolebind my serviceaccount 'yyy' to clusterrole 'view', and after that of course user can see pods of my namespace, but can see other pods from other namespaces too.
How can I make to allow serviceaccount 'yyy' see pods,services,etc. only from specific namespace?
I will be really appreciate if you help me guys.
Thanks

**Comment by liggitt** [comment]
Closing in favor of the stackoverflow question - https://stackoverflow.com/questions/50514536/service-account-access-through-api/50515599#50515599
