### ISSUE TITLE
Kubelet running on the master should be accessible

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#6428]
As of now the kubelet on the master cannot be discovered since the master is not part of the list of nodes returned by the apiserver. @lavalamp and @bgrant0607 suggested adding the master as a node, after marking it as [unschedulable](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1beta3/types.go#L1001) in the NodeSpec. 

This is required for enabling monitoring on the master and providing access to logs of master components.

**Comment by roberthbailey** [comment]
Depending on how soon you want/need this, you could wait for #6087 to land.

**Comment by brendandburns** [comment]
I'm kicking this out of the v1.0 milestone.

**Comment by vishh** [comment]
This will be necessary for monitoring the master services. I think this
should be part of v1.0.

**Comment by dchen1107** [comment]
cc/ me

**Comment by dchen1107** [comment]
Without this, monitoring won't work for master service, but fluentd-es is enabled on node already, logging works. 

Also kubectl get pods does have information of those available master pods. I think we are ok without this for v1.0.

**Comment by davidopp** [comment]
@brendandburns felt that we shouldn't do this for 1.0, and instead if we need stats from cAdvisor for monitoring, we should run a special instance of heapster on the master node (unless I misunderstood).

But the recent update from @a-robinson on #1625 seems to imply that we may get the stats we need for free from Prometheus anyway.

**Comment by vishh** [comment]
Running a separate heapster on the master is a good idea for now. But, using prometheus metrics instead of heapster might not work for the following reasons:
* Not all containers in the master export prometheus metrics.
* The metrics exported by prometheus is likely not as accurate as the cgroup ones.
* Prometheus metrics are currently not stored anywhere.

So the shortest path forward to enable basic master monitoring will be to run a static heapster pod on the master. 
On the other hand, why do we not want to register the master kubelet as a unschedulable node?

**Comment by bgrant0607** [comment]
I believe this is done.

**Comment by dchen1107** [comment]
Yes, this is done since 1.1 release for open source k8s.

**Comment by bprashanth** [comment]
> This is required for enabling monitoring on the master and providing access to logs of master components.

@kubernetes/sig-node what's the trick to do that? 

```console
beeps@bitrot$ kk get po -o wide | grep l7-lb
l7-lb-controller-v0.6.0-kubernetes-master      1/1       Running   0          37m       10.240.0.2   kubernetes-master

beeps@bitrot$ kk logs l7-lb-controller-v0.6.0-kubernetes-master
Error from server: the server could not find the requested resource ( pods/log l7-lb-controller-v0.6.0-kubernetes-master)

beeps@bitrot$ ssh kubernetes-master.us-central1-a.bitrot-3233 sudo docker logs -f bb799c946b21
I0523 01:07:24.112978       1 main.go:171] Starting GLBC image: glbc_uber_uid:0.6.3, cluster name 
I0523 01:07:59.126143       1 configmaps.go:92] Successfully stored uid 14cac1e44dfc1df8 in config map kube-system/ingress-uid
I0523 01:07:59.126280       1 cluster_manager.go:239] Reading config from path /etc/gce.conf
I0523 01:07:59.128208       1 gce.go:243] Using GCE provider config {Global:{TokenURL: TokenBody: ProjectID: NetworkName: NodeTags:[kubernetes-minion] Multizone:true}}
I0523 01:07:59.128256       1 gce.go:282] Using existing Token Source &oauth2.reuseTokenSource{new:google.computeSource{account:""}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
I0523 01:07:59.233211       1 gce.go:311] managing multiple zones: [us-central1-a us-central1-c us-central1-f us-central1-b]

```

**Comment by yujuhong** [comment]
We don't provide logs for the master components as @bprashanth pointed out. The master components currently dump logs to /var/log/ directly.

**Comment by bprashanth** [comment]
so re-open or WAI? Dumping to /var/log makes runtime debugging and log aggregation harder.

**Comment by bprashanth** [comment]
I'm moving a cluster addon to a static pod on master (the loadbalancer controller), so I'm asking because this would be a "regression" is usability

**Comment by roberthbailey** [comment]
We turned off the /exec and /attach endpoints on the master due to security concerns. I'm not sure that the /logs handler is as dangerous or if it can be enabled while keeping the other two turned off.
