### ISSUE TITLE
Feature: Fractional GPU support / shared GPUs

### ISSUE THREAD

**Issue by ericxnelson** [kubernetes/kubernetes#64284]
/kind feature

Hi,
Just wondering if there's any existing initiatives to enable fractional GPU support for pods? We are a ML shop and run our own framework for this but would rather have our classifiers in mesos or kubernetes should this become an option. Most of our classifiers don't need whole gpus to run and in some cases run fine on cpus.

**Comment by flx42** [comment]
@ericxnelson would having all the containers in the same pod sharing the GPU(s) resources solve your problem?

There is a discussion on this topic here:
https://github.com/kubernetes/kubernetes/issues/52757

**Comment by dims** [comment]
@ericxnelson let's use the one @flx42 pointed out. please add any more feedback there.

/close
