### ISSUE TITLE
kube-dns log parameter --domain

### ISSUE THREAD

**Issue by lurenjia528** [kubernetes/kubernetes#64299]
/kind bug
/sig kube-dns

in my kube-dns.yml the args (--domain)
       args:
        - "--domain=cluster.local"
        - --dns-port=10053
        - --v=2

in the container kube-dns 

 ps -ef | grep kube
    1 root       0:01 /kube-dns --domain=cluster.local --dns-port=10053 --v=2

but when I kubectl logs -n kube-system kube-dns-64b66858cd-rw6gh kubedns
the parameter --domain  is different 

Is this a bug?

![image](https://user-images.githubusercontent.com/37833630/40528135-52c505b2-6022-11e8-81c3-317b43c0ac04.png)
![image](https://user-images.githubusercontent.com/37833630/40528181-887faf5e-6022-11e8-9f43-06314366798b.png)

**Comment by thockin** [comment]
Not a bug - the flag is being canonicalized.  You can see this:

```
# /kube-dns --domain=foo.bar --dns-port=10053 --v=2
I0606 23:47:14.376099      26 dns.go:48] version: 1.14.10
...
I0606 23:47:14.378762      26 server.go:121] FLAG: --domain="foo.bar."
```
