### ISSUE TITLE
Audit Default Admission Controllers for Storage

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#64295]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
PR https://github.com/kubernetes/kubernetes/pull/58684 adds a set of Admission Controllers that are on by default.

**What you expected to happen**:
We should make sure that list of controllers makes sense for storage.

Storage controllers include:
* persistentvolumelabel
* defaultstorageclass
* storageprotection
* volumeresize

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
> We should make sure that list of controllers makes sense for storage.

What do you mean by this?

**Comment by saad-ali** [comment]
Basically ensure that the correct set of storage admission controllers are enabled.
