### ISSUE TITLE
Feature: Provide meaningful metrics to controller developers using API Server

### ISSUE THREAD

**Issue by venezia** [kubernetes/kubernetes#64290]
As Custom Resources and the controllers using the Kubernetes API becomes more commonplace, we need to be able to provide metrics and tools that can help developers of said controllers make informed decisions.  Without such information, well intentioned developers could cause clusters API Servers to deterioriate in performance without understanding why and how to fix the problem.

Right now, as a developer of a controller leveraging the Kubernetes API Server I can obtain some knowledge of things like:
 * How many queries per second am I requesting from the API Server
 * How much bandwidth is being consumed by my controller
 * How many persistent connections (if any) are being used

But I'm relatively unaware of the following:
 * How much cpu and memory my controller is tasking the API Server
 * How much cpu and memory my custom resources / controller tasking the etcd cluster
 * How much storage are my custom resources (if any) are consuming

It would be great if there were some ways to effectively profile a controller and understand min/max/median, 1%/5%/95%/99% intervals of these metrics over a period of time.  

None of this is easily provided to a developer unless they know to install something like [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) and even then it may not be intuitive for someone who doesn't know where to look for such information.  And even then, it does not provide all of this information.

Providing such information could help developers make decisions like:
 * Should my Custom Resource really live on its own api server through api aggregation
 * If a worker queue is being used, how many parallel workers are too many workers for the API Server

Rough metrics such as queries may not fully tell the tale.  Some queries (with field selectors, etc.) may be more expensive for the API Server to process than others.  Even the same query might be much more difficult for the API Server if there are 10k resources to evaluate vs 25.  None of this is presented to the user/developer.  

I personally thought label selectors were somehow more efficient than seemingly arbitrary field selectors, but this in fact not true.  Other people probably are unaware as well.

When some _core_ api resources are created, updated or removed, they trigger other actions beyond the resource directly being acted on.  This may be unaware to the developer.

Some suggestions / observations:
 * Is this a good use of opentracing?
 * Should/Could very granular metrics be pushed into prometheus?
 * Could we ever create alerts/graphs when a specific consumer (controller) is becoming a "bad" user?
 * Would it ever make sense to have istio-ish rate limiting for controllers access the API Server?
 * What may be nice is to see information similar to how redis explains [complexity of its methods](https://redis.io/commands/zpopmax)
 * Publishing an official guide on how to move from a CR to API Aggregation

In many ways, the API Server is a database or a message bus for controllers.  Database systems often provide information about the complexity of any operation, ability to profile the usage based on account, enforce quotas.  We might not be able to do all of this, but perhaps we can start to provide some of this tooling.

/kind feature

**Comment by lavalamp** [comment]
Also relevant to:

/sig scalability

I think this is definitely something we should keep in mind. I can even see eventually wanting to have output suitable for driving a billing system.

**Comment by venezia** [comment]
@nikhita is this worth keeping open, or should i close it?

**Comment by nikhita** [comment]
> @nikhita is this worth keeping open, or should i close it?

Sorry, missed this! Looks worth keeping open to me :+1:

/remove-lifecycle rotten
