### ISSUE TITLE
`pull-kubernetes-kubemark-e2e-gce-big` always fails

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#64303]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`pull-kubernetes-kubemark-e2e-gce-big` always fails

All error info like:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63901/pull-kubernetes-kubemark-e2e-gce-big/8390/

**Comment by cblecker** [comment]
https://k8s-testgrid.appspot.com/presubmits-kubernetes-scalability#pull-kubernetes-kubemark-e2e-gce-big

cc @ixdy @BenTheElder @cjwagner @krzyzacy

**Comment by cblecker** [comment]
more recently it's still failing, but with different errors

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-kubemark-e2e-gce-big/9164?log#log

**Comment by krzyzacy** [comment]
cc @shyamjvs 
`Timeout waiting for all hollow-nodes to become Running.`

**Comment by cblecker** [comment]
Yeah, the hollow nodes look to be throwing errors (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-kubemark-e2e-gce-big/9164/artifacts/e2e-batch-9164-ac87c-minion-group-b2hg/kubelet-hollow-node-26mfd.log):
```
E0530 17:05:21.878485      11 kubelet_network.go:102] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": executable file not found in $PATH: 
E0530 17:05:21.902981      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0530 17:05:31.903141      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0530 17:05:41.903292      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0530 17:05:51.903467      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0530 17:06:01.903629      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
E0530 17:06:11.903796      11 eviction_manager.go:271] eviction manager: failed to get get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
```

**Comment by shyamjvs** [comment]
I took a look into this and it's a regression which started causing failures in our kubemark jobs. E.g https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-500
The diff https://github.com/kubernetes/kubernetes/compare/15cd35528...6b2172741 has a handful of PRs and https://github.com/kubernetes/kubernetes/pull/63328 is the cause (as it's the only one on which kubemark-500 presubmit failed).

We can revert it to fix the issue for now and have it back in once it's fixed. Or if the fix is easy and can be done asap - we can wait.
@vikaschoudhary16 @kubernetes/sig-node-bugs - need you to weigh in.

**Comment by vikaschoudhary16** [comment]
@shyamjvs I spent some time but could not find how #63328 is making it fail.
Anyways, once https://github.com/kubernetes/kubernetes/pull/64605, is merged, #63328 will not impact any CI job.

**Comment by shyamjvs** [comment]
@vikaschoudhary16 Thanks for response. That PR seems to be hiding the real issue by feature-gating it off. That works to fix the failure, but it still means we have the issue present.
I'm ok with merging #64605, but we do need to ensure that it's fixed (as it'll anyway come up later when you move to beta).

**Comment by vikaschoudhary16** [comment]
```
I0530 16:39:21.872530      11 plugin_watcher.go:167] Plugin Watcher Start at /tmp/hollow-kubelet.149007168/plugins
I0530 16:39:21.872561      11 server.go:130] Starting to listen on 0.0.0.0:10250
I0530 16:39:21.872623      11 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0530 16:39:21.872644      11 status_manager.go:140] Starting to sync pod status with apiserver
I0530 16:39:21.872659      11 kubelet.go:1733] Starting kubelet main sync loop.
I0530 16:39:21.872681      11 kubelet.go:1750] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0530 16:39:21.873128      11 volume_manager.go:245] The desired_state_of_world populator starts
I0530 16:39:21.873142      11 volume_manager.go:247] Starting Kubelet Volume Manager
I0530 16:39:21.873178      11 desired_state_of_world_populator.go:129] Desired state populator starts to run
I0530 16:39:21.873263      11 server.go:983] Started kubelet
```

Based on these logs, i can say that #63328 is not the cause. feature gate is only protecting the start of plugin watcher but from logs it is clear that plugin watcher started fine and kubelet givinf some errors which looks unrelated to plugin watcher.

At least by merging feature gate, we will gate to know if this job passes now. I will look more deeper in plugin watcher PR then bby creating a test PR enabling feature gate.

**Comment by vikaschoudhary16** [comment]
@shyamjvs 
Initially i thought that may be plugin watcher server is getting stuck and blocking kubelet start but from logs i can see that this is not the case. I am almost certain that #63328 is not the culprit. :)

**Comment by shyamjvs** [comment]
> At least by merging feature gate, we will gate to know if this job passes now. I will look more deeper in plugin watcher PR then bby creating a test PR enabling feature gate.

That strategy sgtm.

> Based on these logs, i can say that #63328 is not the cause.

It's a clear regression if you look at this job https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-500. And among the diff of 5 PRs, yours was the only one which failed the kubemark-500 presubmit (explained in https://github.com/kubernetes/kubernetes/issues/64303#issuecomment-393814632). So I'm not sure about that :)

Btw, could you please provide the source for those logs?

**Comment by vikaschoudhary16** [comment]
@shyamjvs  (https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-kubemark-e2e-gce-big/9164/artifacts/e2e-batch-9164-ac87c-minion-group-b2hg/kubelet-hollow-node-26mfd.log) its the same that @cblecker shared above.

May be i am missing something, will go through the code again.

**Comment by wojtek-t** [comment]
To clarify - the problem we have is the following:

```
F0530 16:59:16.877788       7 kubelet.go:1339] failed to start Plugin Watcher. err: failed to start plugin watcher, err: too many open files
```

**Comment by wojtek-t** [comment]
And i actually think that the logs @cblecker pasted may be a red-herring and the issue seem to be what I mentioned above...

**Comment by shyamjvs** [comment]
> And i actually think that the logs Christoph Blecker pasted may be a red-herring and the issue seem to be what I mentioned above...

That's right and also what I've conveyed to @vikaschoudhary16 on the slack channel.

**Comment by vikaschoudhary16** [comment]
On some of the hollow nodes, following error is found in the logs:
>kubelet.go:1354] failed to start Plugin Watcher. err: failed to start plugin watcher, err: too many open files

So it is indeed the plugin watcher on some of the nodes that is making kubelet fail. For now,  #64605 is the stop gap fix to get job running.
This is the issue for tracking this https://github.com/kubernetes/kubernetes/issues/64614 before graduating plugin watcher to beta.

**Comment by shyamjvs** [comment]
Thanks @vikaschoudhary16!
/close

**Comment by cblecker** [comment]
Thank you both, @vikaschoudhary16 @shyamjvs!

**Comment by RenaudWasTaken** [comment]
I'm seeing [an error (line 8)](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-kubemark-e2e-gce-big/9164/artifacts/e2e-batch-9164-ac87c-minion-group-l416/kubelet-hollow-node-zv5kz.log) much more early in the process that seems related:
```
E0530 16:39:48.380138      10 file_linux.go:61] Unable to read config path "/tmp/hollow-kubelet.850040081/static-pods428572988": unable to create inotify: inotify_init: too many open files
```

Are the kubelet ran on the same node?

Given that fsnotify needs to keep at least one file opened for each path / file it watches if the 500 node test runs multiple kubelets on the same machine it would seem reasonable that we are hitting that limit much earlier than before.

A simple fix would be to raise that limit or have less kubelet per node.

**Comment by wojtek-t** [comment]
> Are the kubelet ran on the same node?
> Given that fsnotify needs to keep at least one file opened for each path / file it watches if the 500 node test runs multiple kubelets on the same machine it would seem reasonable that we are hitting that limit much earlier than before.

We run mutliple "hollow-kubelets" on the same node - yes.A simple fix would be to raise that limit or have less kubelet per node.nb

> A simple fix would be to raise that limit or have less kubelet per node.

Less kubelets per node is not an option - we do ran many of them to reduce costs. 
Raising a limit might be a good fix.
