### ISSUE TITLE
Malformed toleration produces unhelpful validation error

### ISSUE THREAD

**Issue by danderson** [kubernetes/kubernetes#64301]
/kind bug

**What happened**:

I incorrectly specified a pod toleration with `effect=CriticalAddonsOnly` instead of `key=CriticalAddonsOnly`, and the resulting validation error was nonsensical.

The full incorrect set of tolerations is:

```yaml
- effect: CriticalAddonsOnly
  operator: Exists
- effect: NoExecute
  operator: Exists
```

When I submit this pod to Kubernetes I get the following validation error:

```
DaemonSet.apps "calico-node" is invalid: spec.template.spec.tolerations[0].effect: Unsupported value: "NoExecute": supported values: "NoSchedule", "PreferNoSchedule", "NoExecute"
```

Note that it correctly identifies the first toleration as incorrect, but says that `NoExecute` is both invalid and one of the supported values, even though `NoExecute` appears nowhere in that toleration.

This appears to happen only when there is a `NoExecute` toleration following the malformed toleration. If I remove the second toleration from this pod, the validation fails with the correct error:

```
DaemonSet.apps "calico-node" is invalid: spec.template.spec.tolerations[0].effect: Unsupported value: "CriticalAddonsOnly": supported values: "NoSchedule", "PreferNoSchedule", "NoExecute"
```

This smells a lot like accidentally using an iteration value in a for loop without copying it first, such that just traversing the `NoExecute` toleration ends up corrupting the error for the first toleration.

**What you expected to happen**:

The validation error should make sense.

**How to reproduce it (as minimally and precisely as possible)**:

Submit a pod to Kubernetes with the above tolerations set.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Debian Testing
- Kernel (e.g. `uname -a`): 4.16.5
- Install tools: kubeadm

**Comment by danderson** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by hzxuzhonghu** [comment]
will fix it
