### ISSUE TITLE
Kubernetes 1.10 hugepage discovery issue

### ISSUE THREAD

**Issue by subrnath** [kubernetes/kubernetes#64309]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> /kind feature

**What happened**:
I would like to use this feature in Kubernetes 1.10. Host OS is Ubuntu 16.04.4. In the worker node, i have reserved huge pages

$ cat /proc/meminfo | grep -i huge
AnonHugePages: 235520 kB
HugePages_Total: 4096
HugePages_Free: 4096
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 kB

$ cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/free_hugepages
2048
$ cat /sys/devices/system/node/node1/hugepages/hugepages-2048kB/free_hugepages
2048

$ cat /proc/mounts | grep -i huge
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0

**What you expected to happen**:

"kubectl describe nodes" showing as -
Capacity:
cpu: 48
ephemeral-storage: 960317832Ki
hugepages-1Gi: 0
hugepages-2Mi: 0
memory: 264110532Ki
pods: 110
Allocatable:
cpu: 48
ephemeral-storage: 885028912506
hugepages-1Gi: 0
hugepages-2Mi: 0
memory: 264008132Ki
pods: 110

Why "hugepages-2Mi: 0" ? it should show as 8192 Mi as for the both the NUMA -0 and NUMA-1, 4096 2MB huge huge pages are allocated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

admin1@Worker3:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Stepping:              2
CPU MHz:               1230.371
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              4989.88
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts

- OS (e.g. from /etc/os-release):
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):

Linux Master0 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Others:

**Comment by subrnath** [comment]
we got the issue. Hugepage allocation to be done before doing "kudeadm join". Closing the issue.

**Comment by nandiabhishek1** [comment]
@subrnath, Can you please tell me how did you allocate huge page to nodes before doing "kudeadm join". I am also having the same problem -

->  I have created single node K8s setup where both master and client are running on host machine. Below is the output of the node - 

Capacity:
 cpu:                16
 ephemeral-storage:  486210936Ki
 **hugepages-1Gi:      0
 hugepages-2Mi:      0**
 memory:             131761440Ki
 pods:               110
Allocatable:
 cpu:                16
 ephemeral-storage:  448091997876
 **hugepages-1Gi:      0
 hugepages-2Mi:      0**
 memory:             131659040Ki
 pods:               110

**Comment by subrnath** [comment]
Hi,

Before kubeadm join, please reserve the hugepage with the following command
-
echo 4096 >
/sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages.

Please note, we find problem if there is two NUMA in the server and we do
reserve in both the NUMAs. In that case, it's not guaranteed during Pod
startup which NUMA the hugepage is taken. For the DPDK like application,
it's a problem as we might be using the NIC from NUMA-0 whereas Hugepage is
given to the Pod is from NUMA-1 from this reserve by K8s. So till K8s 1.12,
we find this feature is not NUMA aware. Hence if we know that the DPDK
application will take the NIC from NUMA-0, better to run the above command
to reserve the Hugepage from NUMA-0 only.  So that we can be sure that K8s
is going to allocate the Huge page from NUMA-0 only to the Pod.

Regards,
Subrata
