### ISSUE TITLE
Create dynamic informers and listers

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#64319]
From @deads2k's comments in https://github.com/kubernetes/kubernetes/pull/64310#issuecomment-392076699:

> I think this is highlighting the need to have a dynamic shared informer factory. If I've reading this code correctly, we've just doubled the number of times we're caching resources and not created the capital to make this easy in general.

> With a dynamic shared informer factory, it becomes possible wire the "get informer for resource" to delegate across multiple candidates as we do in openshift. All that helps the general cause and avoids unnecessary duplication. 

Controllers like the GC controller and resource quota controller use informers and listers. Currently, we only have support for static, generic informers and listers.

To work with custom resources, the GC controller creates a new informer each time it comes across an unknown resource.

https://github.com/kubernetes/kubernetes/blob/23a9136d4e91e6af7369573805ffb7803785ec1b/pkg/controller/garbagecollector/graph_builder.go#L190-L197

If we try to do something similar for the RQ controller as well (creating a new informer and lister, see https://github.com/kubernetes/kubernetes/pull/64201), we end up increasing the number of times we cache resources. This also does not make it easy if we want to add a similar behaviour in the future. 

To avoid this, we can tackle the problem by creating dynamic informers, then dynamic listers, then shared dynamic informers, then "reactive" shared dynamic informers (ones where it can figure out that the resource has been removed and recreated).

/sig api-machinery
/kind feature
/cc @deads2k @sttts @liggitt @lavalamp @mbohlool

**Comment by carolynvs** [comment]
This would let us completely redo how service catalog works, and make the UX really rock. I'd love to help make it happen or test it out with a prototype as soon as you've got it! 💯

**Comment by nikhita** [comment]
I'm working on this and just discussed it with @sttts today. @enisoc already added something similar in metacontroller https://github.com/GoogleCloudPlatform/metacontroller/tree/master/dynamic/informer to make our lives easy developing it for kube. :)

**Comment by enisoc** [comment]
I've been appropriately shamed by @deads2k for not doing that work upstream in the first place. In my defense, at the time the dynamic client hadn't seen much attention in a while; I thought I was the only one using it. :)

I look forward to rebasing on an official upstream library. Let me know if I can help with reviews or anything.

**Comment by caesarxuchao** [comment]
cc @janetkuo I remember your original new GC design depends on this feature.

**Comment by carolynvs** [comment]
@nikhita Do you know if work has been begun on this already? If not, perhaps I could help implement it?

**Comment by nikhita** [comment]
@p0lyn0mial has been working on it :)

**Comment by p0lyn0mial** [comment]
yeah, I almost have it :)

/assign @p0lyn0mial

**Comment by p0lyn0mial** [comment]
dynamic lister already merged, see: https://github.com/kubernetes/kubernetes/pull/68748

**Comment by p0lyn0mial** [comment]
dynamic informer factory has just been merged https://github.com/kubernetes/kubernetes/pull/69308
Is there anything else we would like to implement or can we close this issue ?

**Comment by nikhita** [comment]
>  Is there anything else we would like to implement or can we close this issue ?

I think we can close this. Thanks, @p0lyn0mial! :tada: 

Closing the issue. Please reopen if needed.

/close

**Comment by carolynvs** [comment]
O.M.G I can't wait to try it out! 🏃‍♀️ 💨

**Comment by krmayankk** [comment]
I know there is no requirement for documentation on internal enhancements, but if there is a scope for that , please add a blob about how to use it , for both core and controller writers . I have been looking for an internal deep dive on informers but haven’t found one and it keeps improving :-) @nikitha @p0lyn0mial
