### ISSUE TITLE
Following container logs can leave processes running and open inotify watches

### ISSUE THREAD

**Issue by chazsconi** [kubernetes/kubernetes#64315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig node

**What happened**:
If a container log is followed using kubectl or other API client, when the client disconnects, the process watching for changes in the logs does not die.

The process only dies when a new log line is received from the container (which may not happen) and the log process tries to send it to the client and then fails.  Furthermore, a inotify watch is also left open, which can potentially cause the OS to run out of watches and eventually results in `failed to create fsnotify watcher: too many open files` when the next container log is followed.

**What you expected to happen**:
When the client disconnects, the process watching the logs should die within a short time, and the inotify watch should be closed.

**Anything else we need to know?**:

**How to reproduce it (as minimally and precisely as possible)**:
This is simplest to reproduce using a single node instance of K8S e.g. minikube
Steps:

1. Create a pod that does not constantly produce log output e.g.
```
kubectl run log-test --image ubuntu:xenial --command sh -- -c 'date; sleep infinity'
```
2. With `kubectl` watch the pod logs (for the pod just created) and leave running:
```
kubectl logs log-test-78ddcd7d6f-7p7hr  -f
```
3. On the node that has the pod check the number of inotify watches from kubelet
```
 sudo lsof -p `pidof kubelet`  2> /dev/null | grep inotify | wc -l
```
4. Press ctrl-c to kill the `kubectl` watch started in (2)
5. Check the number of inotify watchers again by repeating (3).  The number has not decreased, and will never decrease until either the kubelet is restarted, a log line is received from the pod or the pod terminates.

**Anything else we need to know?**:
I believe the problem lies in how the `ReadLogs` function works here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L269
Unfortunately this has no way of knowing if the client has disconnected until it tries to send a new log line via the `writer`, which will then fail, close the inotify watcher (via the `defer`) and exit.

A container producing no log output will therefore leave the process running.

**Environment**:
- Kubernetes version: both 1.9.7 and 1.10.3
- Cloud provider or hardware configuration: VMWare
- OS (e.g. from /etc/os-release): Ubuntu Xenial
- Kernel (e.g. `uname -a`): 4.4.0-122-generic

**Comment by dims** [comment]
@kubernetes/sig-node-bugs

**Comment by yue9944882** [comment]
It seems difficult to know when the disconnection happen. But we could add an additional option for `watch` API like `watchTimeout` which indicates how long can a `watch` endure. This option should be default to `inifinite` so that `watch`'s default behavior is compatible with current logic. For the case in this issue, we could explicitly set the the `watchTimeout` to ~5 min. WDYT?

**Comment by chazsconi** [comment]
@yue9944882 Yes, I think this is a good approach.  However, when the timeout occurs, the server should respond with a specific HTTP status code (e.g. 408 timeout).  This will allow the client to differentiate between a timeout and the watch finishing because the pod terminated.

**Comment by 2rs2ts** [comment]
>Furthermore, a inotify watch is also left open, which can potentially cause the OS to run out of watches and eventually results in failed to create fsnotify watcher: too many open files when the next container log is followed.

Uh, isn't this like, a huge problem? Shouldn't this be a high priority issue?

**Comment by Random-Liu** [comment]
@yujuhong just finds that we can get context from the http.Request wrapped by `go-restful`. https://golang.org/pkg/net/http/#Request.Context

We should be able to fix this issue with that. And this should also fix potential resource leakage in other streaming calls, e.g. exec, attach etc.

**Comment by guineveresaenger** [comment]
@yujuhong was this issue closed intentionally? #67285 is a partial fix but automation may not have picked up on the partialness. 

Please confirm :)

**Comment by yujuhong** [comment]
> @yujuhong was this issue closed intentionally? #67285 is a partial fix but automation may not have picked up on the partialness.

Yep. It only looked for the keywork "fixes" :-\

**Comment by yujuhong** [comment]
The second PR #67357 should actually fix this issue.

**Comment by patrickleet** [comment]
Seeing this in Kube 1.18 on EKS

**Comment by aelbarkani** [comment]
I'm seeing the same in GKE 1.16

**Comment by patrickleet** [comment]
I fixed with changing inotify settings. 

It was EKS and via terraform for a worker group launch template:


additional_userdata  = "sudo sysctl -w fs.inotify.max_user_watches=1048576;sudo sysctl -w fs.inotify.max_user_instances=512;sudo sysctl -w vm.max_map_count=524288;"

**Comment by metasim** [comment]
I'm still seeing this in EKS 1.18

**Comment by patrickleet** [comment]
it's also ubuntu image for eks which is an entirely separate AMI, and plenty of other distributions as well. Change your inotify settings.

**Comment by patrickleet** [comment]
This went away for awhile, had to bump `max_user_instances` again. I chose 8192, based on someone else doing it here:
https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/hardening.conf#L4

For reference, to see what your settings are, you can run the following:

First, start a debug pod:
```
kubectl run -i --tty --rm debug --image=alpine --restart=Never -- sh
```

Which will drop you into the shell for that new `debug` pod. In there, run:

```
sysctl -a
```

To see all the sysctl settings - specifically you'll want to check `inotify` settings:

```
sysctl -a | grep inotify
```

and `max_map_count` (I don't remember why I set this one - copied from some answer elsewhere:

```
sysctl -a | grep max_map_count
```

These are the settings I'm using via `terraform-aws-modules/eks/aws` module

```
worker_groups_launch_template = [
    for subnet in module.company-eks-0-vpc.public_subnets :
    {
      additional_userdata                  = "sudo sysctl -w fs.inotify.max_user_watches=1048576;sudo sysctl -w fs.inotify.max_user_instances=8192;sudo sysctl -w vm.max_map_count=524288;"
```
