### ISSUE TITLE
[kubeadm init]  marking master: timed out waiting for the condition

### ISSUE THREAD

**Issue by tangle329** [kubernetes/kubernetes#64312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
kubeadm init --pod-network-cidr=172.29.0.0/16 --kubernetes-version=v1.10.3
......
[markmaster] Will mark node st1-tkube-4.prod.yiran.com as master by adding a label and a taint
error marking master: timed out waiting for the condition

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Add --hostname-override=<node ip> to kubelet and then run kubeadm init above the issue could be observed.

Once the --hostname-override flag is removed fro kubelet, the issue disappeard and the cluster setup could be complete.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.10.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tangle329** [comment]
Resolved by add --node-name=<ip address> to kubeadm init .

**Comment by 372046933** [comment]
I tried  adding `--node-name=` to kubeadm, but it doesn't work.

**Comment by Itfly** [comment]
@372046933  Hi, did you fix the issue?

**Comment by 372046933** [comment]
@Itfly Resolved. I remember that I changed the policy of forward chain of iptables to ACCEPT
