### ISSUE TITLE
make quick-release is highly flaky on master

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#64329]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**: Spurious `make quick-release` failures on master: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/30861/

**What you expected to happen**: the build should be reliable and reproducible

**How to reproduce it (as minimally and precisely as possible)**: `make quick-release` on master repeatedly

**Anything else we need to know?**: it looks like it's related to a change in https://hub.docker.com/r/multiarch/qemu-user-static/ which we use here:
https://github.com/kubernetes/kubernetes/blob/880dbd339b89fd7951fd2c12ded79fef112960a2/cluster/images/hyperkube/Makefile#L43

/sig release

Jeff and Christoph have tracked it down this far, thanks!
/cc @ixdy @cblecker

**Comment by cblecker** [comment]
To update what I said in #testing-ops: did a quick-release on darwin, and it completed without issue.

**Comment by ixdy** [comment]
This appears to be a recurrence of https://github.com/multiarch/qemu-user-static/issues/27. I have https://github.com/multiarch/qemu-user-static/issues/40 out to fix, though we probably need a better long-term solution for this, since this isn't the first time it's broken.

**Comment by ixdy** [comment]
One possibility is that we can build our own version of the [qemu-user-static Docker image](https://github.com/multiarch/qemu-user-static/blob/master/register/Dockerfile) and host it in our own gcr.io repo. Then we wouldn't be affected by upstream changes.

**Comment by cblecker** [comment]
Honestly, it's not the worst idea.. it is a binary that we're running privileged.

**Comment by ixdy** [comment]
would `gcr.io/k8s-testimages` be the right place to put this? `gcr.io/google-containers` is where kube-cross lives, but I really don't want to add more things there.

**Comment by BenTheElder** [comment]
Agree.
I'm also looking into mitigating any such binmft_misc issues in CI by
adding this to the list of things we clean up for docker in docker jobs.

**Comment by ixdy** [comment]
looks like the fix has already been published to dockerhub, so build failures should start subsiding.

**Comment by cblecker** [comment]
Thing is, it's part of the build.. I'm not sure `gcr.io/k8s-testimages` is the best place either. Not exactly a test image.

**Comment by ixdy** [comment]
yeah, we don't really have a place for build images besides `gcr.io/google-containers`, I think.

**Comment by BenTheElder** [comment]
this was fixed upstream, but I'm still enacting defensive mitigations in test-infra against any future issues for kubernetes or otherwise.
