### ISSUE TITLE
Transparent Huge Pages (THP) support

### ISSUE THREAD

**Issue by florianflock** [kubernetes/kubernetes#64330]
/kind feature
/sig gcp

**What happened**:
I get this issue by running the official redis container on a Kubernetes system:
`1:S 18 May 20:07:13.473 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
`

Did anybody solve this by initContainers or something else?

**Comment by florianflock** [comment]
@kubernetes/sig-gcp
@kubernetes/

**Comment by danielsetreus** [comment]
I'm gettings this issue today. Anyone have a solution for it?

**Comment by ncarr031** [comment]
@danielsetreus This helped me. Bonus points for defining it on a deployment instead of a pod.
https://itnext.io/simple-redis-cache-on-kubernetes-with-prometheus-metrics-8667baceab6b

**Comment by cwhsu1984** [comment]
> @danielsetreus This helped me. Bonus points for defining it on a deployment instead of a pod.
> https://itnext.io/simple-redis-cache-on-kubernetes-with-prometheus-metrics-8667baceab6b

this does solve the issue, but the link's solution change the cluster node's setting instead of container if I understand it correctly.
