### ISSUE TITLE
 Failing Test: Multiple [sig-cli] Kubectl client [k8s.io] tests failing in sig-release-master-upgrade suite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64362]
## Failing Job
* [gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)
* [gke-gci-1.10-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel)

## Failing Test
* [[sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-kubectl-run---rm-job-should-create-a-job-from-an-image-then-delete-the-job-conformance)
* [[sig-cli] Kubectl client [k8s.io] Update Demo should create and stop a replication controller [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-update-demo-should-create-and-stop-a-replication-controller-conformance)
* [[sig-cli] Kubectl client [k8s.io] Update Demo should scale a replication controller [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-update-demo-should-scale-a-replication-controller-conformance)

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=cli&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel&test=Kubectl%20client

This test started failing consistently in the upgrade jobs since 5/21 evening.

/kind bug
/priority failing-test
/priority important-soon
/sig cli
/milestone v1.11
@kubernetes/sig-cli-bugs 

cc @jberkus @tpepper

/assign @liggitt 

@liggitt we are seeing consistent Kubectl failures in sig-release-master-upgrade jobs. Can you please triage this as priority and let us know if we can resolve it by Code freeze (6/5)?

**Comment by soltysh** [comment]
Looking at it...

**Comment by soltysh** [comment]
status/approved-for-milestone

**Comment by soltysh** [comment]
Possible cause is the too short timeout in the test while waiting for removed resources.

**Comment by soltysh** [comment]
The job was fixed in https://github.com/kubernetes/kubernetes/pull/64399. The other two problems are related to fixes that were applied in https://github.com/kubernetes/kubernetes/pull/61565 and https://github.com/kubernetes/kubernetes/pull/62155 on master. I'll open a cherry-pick of these two against 1.10 branch, since these tests are invoking those versions which fail due to lack of wait.

**Comment by soltysh** [comment]
All the PRs are merged, closing.

**Comment by soltysh** [comment]
It looks like `[sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance]` is still an issue, re-opening.

**Comment by soltysh** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/64439 to fix the code in 1.10 branch which is being tested in [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew/7980).

**Comment by soltysh** [comment]
I'll monitor the test-grid now that https://github.com/kubernetes/kubernetes/pull/64439 merged.

**Comment by soltysh** [comment]
@AishSundar it looks like #64439 fixed the problem from looking at the test grid. Feel free to close this issue, since I remember you're tracking all of that.

**Comment by AishSundar** [comment]
Closing the issue now !
