### ISSUE TITLE
kube-dns should support DNS-SD

### ISSUE THREAD

**Issue by alml** [kubernetes/kubernetes#6437]
Use case:
Prometheus uses DNS-SD for instance discovery (http://prometheus.io/docs/operating/configuration/). To allow its use with Kubernetes, all Pods should be exposed in DNS.

Current state:
Currently kube2sky exposes only IP:port pairs of the services.

Desired state:
Additional flag should allow kube2sky to expose the pods in the similar way:

$ host -t srv someservice.pod.kubernetes.local
someservice.default.pod.kubernetes.local has SRV record 10 100 80 9gvmk.someservice.default.pod.kubernetes.local.
someservice.default.pod.kubernetes.local has SRV record 10 100 80 akhj2.someservice.default.pod.kubernetes.local.
someservice.default.pod.kubernetes.local has SRV record 10 100 80 8sh3j.someservice.default.pod.kubernetes.local.

**Comment by thockin** [comment]
I don't know a ton about DNSSD, but everything I know is about SRV.  What
service type are you looking for and how do I know if a pod actually
supports it (and on what port)?  We could, hypothetically, add a way to
declare RFC compatible service types on each port.

Am I misunderstanding?  Where can I read a good overview of dnssd?

We were thinking instead of this, maybe we have a bridge from kubernetes
native API to Prometheus, so we could use the pod events and watch protocol
we already have...

@vishh

**Comment by alml** [comment]
DNS-SD is defined here: http://www.ietf.org/rfc/rfc6763.txt
This is the same SRV as kube2sky implements.
I've implemented support for Pods discovery with Pod Watch API method. This doesn't work well although, because changes in the PodStatus are not watchable. So for now I do both - Watch and regular poll. Later polling could be easily removed.

**Comment by thockin** [comment]
I would not call the RFC a "good overview" :)

**Comment by alml** [comment]
Well, okay. Let's not stick to "DNS-SD" name. The simplest example is shown in the issue description. This is enough to run Prometheus.

**Comment by thockin-cc** [comment]
I am looking for some high level understanding of how it is used without
reading RFCs.  Is there anything special about the records in DNS?  What
srv service type would you want?  What TTL to use for known-transient
records?  Do clients poll DNS?  With what query?

**Comment by alml** [comment]
Prometheus configuration file defines which service you want to monitor. Example:
job {
    name: "test-frontend"
    scrape_interval: "5s"
    sd_name: "test-frontend.default.pod.kubernetes.local"
    metrics_path: "/metrics"
}
sd_name points to service you want to monitor.

Every 5 seconds Prometheus queries this domain name with SRV request type. It expects to get list of TXT records in DNS-SD format. Each record corresponds to a host:ip pair to scrape.
Example of response:
test-frontend.default.pod.kubernetes.local has SRV record 10 33 3000 test-frontend-oh43e.og-test-frontend.default.pod.kubernetes.local.
test-frontend.default.pod.kubernetes.local has SRV record 10 33 3000 test-frontend-gziey.og-test-frontend.default.pod.kubernetes.local.
test-frontend.default.pod.kubernetes.local has SRV record 10 33 3000 test-frontend-fplln.og-test-frontend.default.pod.kubernetes.local.

TTL here is a tradeoff between how fast Prometheus will detect started/stopped Pods, and load on the DNS system. TTL is hardcoded to 30 seconds (old kube2sky uses this value as well).

And finally Prometheus queries http://host:ip/metrics to get a text document with key=value or key=map format suitable for recording and analysis.

Have I answered your questions?

**Comment by alml** [comment]
Ah, sorry. Second type of DNS query involved is an A-query when hostname is resolved. Example of response:
test-frontend-oh43e.test-frontend.default.pod.kubernetes.local has address 10.13.98.3

**Comment by alml** [comment]
DNS names of the pods have format: <podname>.<servicename>.<namespace>.<domain>
In case of named ports (recently added feature in Kubernetes): <podname>.<portname>.<servicename>.<namespace>.<domain>.

**Comment by alml** [comment]
Relevant Prometheus code: https://github.com/prometheus/prometheus/blob/master/retrieval/target_provider.go#L96

**Comment by thockin** [comment]
Thanks, that helps.  Do you see this service name as something hardcoded in
kubernetes, or as something we determine from a pod spec?

We have a slight problem in namespacing.  Its legit in kubernetes to have
pods and services with the same name.  I will have to think more on this
when I get back early this coming week.

**Comment by alml** [comment]
Service names are just names of the Kubernetes services. For example, if you create service "foo", and you have a pod "bar" which matches service selector of "foo", then you will have DNS name:
bar.foo.default.kubernetes.local. So service names never conflict with pod names. They are subdomains of each other. This allows you to query foo.default.kubernetes.local, and get all matching pods. This is the core idea.

Have a good weekend :)

**Comment by thockin** [comment]
How does Prometheus get the list of services to query?

**Comment by alml** [comment]
It's manually configured by the user. See a config snippet above. Users
explicitly list services to monitor.

**Comment by thockin-cc** [comment]
Ahh, I see.  That is somewhat unsatisfying.  I want to turn prometheus on
for the whole cluster and have it find ALL pods, not just pods under
services and not just some services.  How do we get there?

Still, DNS-SD might not be so bad for services.  Will need to take a look
at your PR - it is a significant change.

Also, note that pods can slave to multiple services - I am not sure that
collecting stats twice is what you want..

**Comment by alml** [comment]
Now if you ask Prometheus to scrape whole kubernetes.local domain, it will
scrape everything. But you are right - some pods may be scraped multiple
times.

For this use case I would provide one more flag to export all pods in a
separate subdomain.

With new architecture it's a very easy change.

**Comment by thockin-cc** [comment]
What would all pods in a new subdomain do for this?  This will run afoul of
the 64K limit in TXT records before long.

And how do you scrape a whole subdomain - axfr queries?

**Comment by alml** [comment]
SkyDNS returns all entries for a subdomain automatically. I don't need to
do anything special on the kube2sky side.

**Comment by alml** [comment]
It's a regular SRV query that does it.

**Comment by thockin** [comment]
I have been discussin g with miekg how to get an A record for foo.bar.local
AND get SRV and A records for x.foo.bar.local with skyDNS - have you solved
that part?

**Comment by alml** [comment]
I'm using two separate subdomains for services and pods. Look at the
README.md in my PR.

**Comment by juliusv** [comment]
@thockin @alml Prometheus author here. Just an update: Prometheus 0.14.0 now has a more generic service discovery framework, and also supports Consul and a file-watch-based interface now: http://prometheus.io/blog/2015/06/01/advanced-service-discovery/. We plan on supporting just a few more "native" SD implementations in the future, while users can plug in any other custom SD mechanism via the file-watch interface.

What would be the best service discovery mechanism for Kubernetes? Perhaps it is one that we can add to Prometheus proper.

/cc @fabxc

**Comment by fabxc** [comment]
The API seems to have everything we need form a quick look at the [Go client package](https://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/client).

The easiest option would be an external contribution by someone using Kubernetes. The implementations on Prometheus's side are usually done within 300 LOC - knowing the other system is more important.

I'm happy to do it myself at some point but cannot give an ETA.

**Comment by thockin** [comment]
Frankly, I'd be happy to support DNSSD properly.  We now have very basic
SRV support, but not the PTR and TXT support needed by DNSSD, it seems.

**Comment by thockin** [comment]
In fact I am going to re-title this issue

**Comment by thockin** [comment]
I have re-titled this again.  I'm still open to supporting DNS-SD but we could sure use help from anyone who really wants it :)

**Comment by boxsmiley** [comment]
I guess gravitational is now hosting the main github repo for kube2sky?  

Does anyone have any information on PTR support?  

I am running a standalone kubernetes cluster with skydns and kube2sky and DNS is extremely slow the reverse lookup is lost in space (~6secs).  tcpdump reveals that the PTR record is the holdup.  I add the PTR record to skydns by hand like this:  

curl -XPUT http://127.0.0.1:4001/v2/keys/skydns/arpa/in-addr/10/0/1/125 \
    -d value='{"host":"service1.example.com}'

and the nslookups are instantaneous.  Any info is greatly appreciated.  Been looking at this for a couple days now.

**Comment by thockin-cc** [comment]
kube2sky is EOL.  kube-dns is an integrated DNS server and it includes some
PTR support.

https://github.com/kubernetes/kubernetes/tree/master/cmd/kube-dns

```
root@kubernetes-minion-group-in0t:~# dig @10.0.0.10 +noall +answer
kubernetes.default.svc.cluster.local
kubernetes.default.svc.cluster.local. 14 IN A 10.0.0.1

root@kubernetes-minion-group-in0t:~# dig @10.0.0.10 +noall +answer
kube-dns.kube-system.svc.cluster.local
kube-dns.kube-system.svc.cluster.local. 30 IN A 10.0.0.10

root@kubernetes-minion-group-in0t:~# dig @10.0.0.10 +noall +answer -x
10.0.0.10
10.0.0.10.in-addr.arpa. 30 IN PTR kube-dns.kube-system.svc.cluster.local.
```

we do not have reverse lookups for pods yet.

**Comment by boxsmiley** [comment]
thank you for your quick response and helpful pointer.
