### ISSUE TITLE
e2e conformance tests failing when using DenyEscalatingExec admission controller

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#64387]
When using the `DenyEscalatingExec` admission controller, e2e tends to break, especially these:

```
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [Conformance]
[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: http [Conformance]
[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: udp [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: http [Conformance]
[k8s.io] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [Conformance]
```

This is especially confusing for users, as they think that their cluster isn't conformant.

/sig testing
/priority important-soon

**Comment by yastij** [comment]
cc @timothysc - errors only while trying to exec on privileged containers (for example containers using host network).

**Comment by yastij** [comment]
@timothysc - this is happening on any distro that enables denyEscalatingExec, I think we need a solution on the kubernetes conformance side.

**Comment by liggitt** [comment]
this isn't really a bug, enabling non-default policy/admission restrictions (especially ones like DenyEscalatingExec that uniformly deny all requests without regard for the permissions of the caller) can break conformance assumptions.

**Comment by liggitt** [comment]
xref #65408

**Comment by dims** [comment]
kinda related - https://github.com/kubernetes/kubernetes/issues/65408

**Comment by liggitt** [comment]
There are many configurations you can enable that prevent conformance tests from running, especially ones that limit permissions of normal namespaced users or pods.

This is not specific to this admission plugin, but is a general statement about the current state of conformance tests. See https://github.com/kubernetes/community/blob/master/contributors/devel/conformance-tests.md#conformance-testing-in-kubernetes:

> There are currently conformance tests that violate some of the requirements (e.g., require privileged access), we will be categorizing these tests and deciding what to do once we have a better understanding of the situation
