### ISSUE TITLE
`pull-kubernetes-e2e-gce-device-plugin-gpu` test always fail

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#64384]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

We can see all related with `pull-kubernetes-e2e-gce-device-plugin-gpu` test failed.  #64366 #64364 #64339 #63839 and so on.
 I think it maybe relate with PR #63979 and #64340.

**What happened**:
Always fails.
**What you expected to happen**:
Pass all.

**Comment by wgliang** [comment]
/cc @soltysh @jiayingz 
PTAL. Thanks.

**Comment by wgliang** [comment]
Why did the #64340 not pass the `pull-kubernetes-e2e-gce-device-plugin-gpu` test but was still merged?

**Comment by neolit123** [comment]
@kubernetes/sig-testing-pr-reviews

**Comment by neolit123** [comment]
@kubernetes/sig-testing-bugs

**Comment by cblecker** [comment]
Looks like the fix is in https://github.com/kubernetes/kubernetes/pull/64404

**Comment by neolit123** [comment]
@BenTheElder 
> pull-kubernetes-e2e-gce-device-plugin-gpu is not a blocking / required test (for merge) currently IIRC, 

i think this is true, as confirmed by the current state of this PR:
https://github.com/kubernetes/kubernetes/pull/64380#partial-pull-merging
it fails the `-gpu` test, but the CI says `Pending — PR does not have lgtm label.` instead of `Required Github CI test is not green...`

> kubernetes/kubernetes uses the "submit-queue" which will only pay attention to some tests.

is there are way to see which tests would cause a `Required Github CI test is not green...`?

**Comment by BenTheElder** [comment]
off the top of my head the definitive way is this list:
https://github.com/kubernetes/test-infra/blob/467523b3e497400b6df069a9ddc4571963aadc11/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L15-L25

but note that @cjwagner is working on moving us to `tide` in the nearish future, and every other kubernetes repo besides this one is either not using merge automation or is using `tide`, which behaves differently and has seperate config integrated with the rest of test-infra. https://github.com/kubernetes/test-infra/tree/master/prow/cmd/tide#tide

**Comment by neolit123** [comment]
thanks for the details! :+1:
