### ISSUE TITLE
`kubectl get` without namespace should return all resources

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#64381]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

Now `kubectl get` without namespace will return resources under default namespace, an ideal way would be `kubectl get` without namespace should return all resources under different namespaces.

Istio already doing it as follows:

```
root@gyliu-icp-6:~/scratch/istio/meshexpansion/bookinfo# istioctl get destinationrules
NAME		KIND						NAMESPACE
details		DestinationRule.networking.istio.io.v1alpha3	bookinfo
productpage	DestinationRule.networking.istio.io.v1alpha3	bookinfo
ratings		DestinationRule.networking.istio.io.v1alpha3	bookinfo
reviews		DestinationRule.networking.istio.io.v1alpha3	bookinfo
details		DestinationRule.networking.istio.io.v1alpha3	default
productpage	DestinationRule.networking.istio.io.v1alpha3	default
ratings		DestinationRule.networking.istio.io.v1alpha3	default
reviews		DestinationRule.networking.istio.io.v1alpha3	default
```

You may see there is a column named as `NAMESPACE`, and we should also enhance `kubectl` to support this as well.

/sig cli

**Comment by yue9944882** [comment]
@gyliu513 Seems `--all-namespaces` option might do the job. Am I missing sth?

**Comment by gyliu513** [comment]
My bad, let me close this one, thanks @yue9944882
