### ISSUE TITLE
dockershim (and other runtimes): take advantage of new CNI capabilities

### ISSUE THREAD

**Issue by squeed** [kubernetes/kubernetes#64393]
/kind feature

The CNI "capability arguments" parameter - currently used to pass port mappings - has a few new capabilities: bandwidth limiting and network address management. The dockershim's networking driver should use them.

The network address is just passing the PodCIDR dynamically to the plugin, so it no longer has to retrieve it from the APIServer.

Bandwidth limiting is already implemented in Kubenet. It is configured via annotations.

There is no upgrade risk in providing these values; non-compliant plugins will simply ignore them. Administrators need to explicitly enable each capability individually in their CNI configuration file.

To avoid skew between runtimes, the other runtimes should also be upgraded to pass these. We may also wish to look in to a way to add this more directly to the CRI, so we don't have this skew problem, but that's a different issue.

**Comment by squeed** [comment]
@dcbw fyi.

**Comment by BenTheElder** [comment]
Looks like this was never done for CRI?

**Comment by BenTheElder** [comment]
cc @aojea
