### ISSUE TITLE
Pod deleted about a minute after creation by system:serviceaccount:kube-system:pod-garbage-collector?

### ISSUE THREAD

**Issue by kevincvlam** [kubernetes/kubernetes#64412]
/kind bug

**What happened**:
A pod in the Pending state, which we expected to go from Pending to Running was instead deleted by the Kubernetes Garbage Collector. 

We believe that the pod went from Pending to Deleted:
- GKE StackDriver logs were missing any from the pod, usually if the pod was created there would be an entry
- We can see in our audit logs of our GKE cluster that the pod was created, and about under a minute later was deleted by the garbage collector, 'system:serviceaccount:kube-system:pod-garbage-collector' 

**What you expected to happen**:
The pod to be scheduled onto a node and enter the Running state.

**How to reproduce it (as minimally and precisely as possible)**:
Seems to happen sporadically. Will update this issue if we find a way to consistently reproduce.

**Anything else we need to know?**:
Our GKE cluster has several nodepools with autoscaling enabled, in addition some of these nodepools have GPUs. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2-gke.1
- Cloud provider or hardware configuration: Google Kubernetes Engine

Hopefully someone has also seen this or has some idea of how to resolve the issue. Thanks in advance!

**Comment by kevincvlam** [comment]
@kubernetes/sig-api-machinery-bugs
@kubernetes/sig-autoscaling-bugs
@kubernetes/sig-gcp-bugs

**Comment by lavalamp** [comment]
The pod garbage collector is not the general GC.

In particular, it deletes Terminated pods when you have more than N terminated pods sitting around (IIRC N=12500 by default, settable by flag on controller manager).

What this means is that your pod was already terminated and the GC is not the culprit. It also means that you have a bunch of terminated pods sitting around: if you delete these, the next one should sit around long enough for you to figure out what really caused it to exit.

**Comment by lavalamp** [comment]
(And please reopen if that doesn't solve the problem :) )
