### ISSUE TITLE
Azure CloudProvider need config option for EnableFloatingIP

### ISSUE THREAD

**Issue by slpcat** [kubernetes/kubernetes#64435]
https://github.com/kubernetes/kubernetes/blob/5d8f6ed4524abac65357e0095395c25634f83cea/pkg/cloudprovider/providers/azure/azure_loadbalancer.go

FloatingIP **should**  disabled when front port is deffrent from backend port

**Comment by karataliu** [comment]
Could you please point out the source for 'FloatingIP should disabled when front port is deffrent from backend port' ?

Besides, backend and frontend port are always same here:
https://github.com/kubernetes/kubernetes/blob/5d8f6ed4524abac65357e0095395c25634f83cea/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L647-L648

Floating IP is required here for enabling both public and internal loadbalancer.

**Comment by slpcat** [comment]
when kubernetes cluster network   is using  flannel ， not from cloudprovider which is azure virtual net
