### ISSUE TITLE
Error from server (Forbidden): 

### ISSUE THREAD

**Issue by NimalanNR** [kubernetes/kubernetes#64437]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
Error from server (Forbidden): serviceaccounts "weave-net" is forbidden: User "system:node:devnode2" cannot get serviceaccounts in the namespace "kube-system": disabled by feature gate TokenRequest
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-net" is forbidden: User "system:node:devnode2" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io "weave-net" is forbidden: User "system:node:devnode2" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): roles.rbac.authorization.k8s.io "weave-net" is forbidden: User "system:node:devnode2" cannot get roles.rbac.authorization.k8s.io in the namespace "kube-system"
Error from server (Forbidden): rolebindings.rbac.authorization.k8s.io "weave-net" is forbidden: User "system:node:devnode2" cannot get rolebindings.rbac.authorization.k8s.io in the namespace "kube-system"
Error from server (Forbidden): daemonsets.extensions "weave-net" is forbidden: User "system:node:devnode2" cannot get daemonsets.extensions in the namespace "kube-system"

**What you expected to happen**:
 pod has to be installed sucessfully
**How to reproduce it (as minimally and precisely as possible)**:
Error from the server

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):Ubuntu
- Kernel (e.g. `uname -a`):Linux devNode2 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by NimalanNR** [comment]
@kubernetes/sig-azure-bugs

**Comment by KrzysztofKarol** [comment]
@NimalanNR I had same problem when I tried to run it as a root.
Works for "normal" user.
