### ISSUE TITLE
dns resolution failing for all pods in kube cluster

### ISSUE THREAD

**Issue by vikramhansawat** [kubernetes/kubernetes#64448]
DNS resolution is failing for internal kubernetes service and all the other external hostnames.

**What happened**:
# nslookup kubernetes is failing
# kubectl run -i --tty ubuntu --image=ubuntu --restart=Never -- sh
# apt-get update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                  
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease        
  Temporary failure resolving 'security.ubuntu.com'

# kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
/ # nslookup kubernetes
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'kubernetes'
/ #

**What you expected to happen**:
DNS resolution have to done successfully.

**How to reproduce it **:
Following commands for both the worker and master node:
apt update
apt-get install apt-transport-https -y
apt install docker.io -y
systemctl start docker
systemctl enable docker
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
apt-get  update
apt-get install -y kubelet kubeadm kubectl kubernetes-cni
cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

Master Node:
kubeadm init --pod-network-cidr 10.244.0.0/16
kubectl get pods --all-namespaces
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/k8s-manifests/kube-flannel-rbac.yml

Worker Node:
kubeadm join command

root@ip-30-0-20-221:~# kubectl get pod --all-namespaces -o=wide
NAMESPACE     NAME                                     READY     STATUS    RESTARTS   AGE       IP            NODE
default       busybox                                  0/1       Error     0          8m        10.244.1.3    ip-30-0-20-74
default       nginx-5c94b9544b-dh4lw                   1/1       Running   0          8m        10.244.1.2    ip-30-0-20-74
default       ubuntu                                   0/1       Error     0          5m        10.244.1.5    ip-30-0-20-74
kube-system   etcd-ip-30-0-20-221                      1/1       Running   0          11m       30.0.20.221   ip-30-0-20-221
kube-system   kube-apiserver-ip-30-0-20-221            1/1       Running   0          11m       30.0.20.221   ip-30-0-20-221
kube-system   kube-controller-manager-ip-30-0-20-221   1/1       Running   0          12m       30.0.20.221   ip-30-0-20-221
kube-system   kube-dns-86f4d74b45-2whl8                3/3       Running   0          12m       10.244.0.2    ip-30-0-20-221
kube-system   kube-flannel-ds-8mscq                    1/1       Running   0          9m        30.0.20.74    ip-30-0-20-74
kube-system   kube-flannel-ds-mmtmk                    1/1       Running   0          12m       30.0.20.221   ip-30-0-20-221
kube-system   kube-proxy-5ln97                         1/1       Running   0          12m       30.0.20.221   ip-30-0-20-221
kube-system   kube-proxy-mwr8f                         1/1       Running   0          9m        30.0.20.74    ip-30-0-20-74
kube-system   kube-scheduler-ip-30-0-20-221            1/1       Running   0          12m       30.0.20.221   ip-30-0-20-221

root@ip-30-0-20-221:~# kubectl get service --all-namespaces -o=wide
NAMESPACE     NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE       SELECTOR
default       kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP          13m       <none>
default       nginx        NodePort    10.103.72.188   <none>        4000:30400/TCP   8m        app=nginx,env=qa
kube-system   kube-dns     ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP    13m       k8s-app=kube-dns

**Anything else we need to know?**:

**Environment**:
- Kubernetes version :
root@ip-30-0-20-221:~#  kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
- OS :
root@ip-30-0-20-221:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel :
root@ip-30-0-20-221:~# uname -a
Linux ip-30-0-20-221 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thockin** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

This is not a generic network problem since thousands of clusters are running just fine.

**Comment by amitvashist7** [comment]
I think it becomes a generic problem now because I've setup cluster couple of time but all the time same issue.  

root@master:~# kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
master     Ready     master    1h        v1.10.4
worker01   Ready     <none>    1h        v1.10.4
worker02   Ready     <none>    1h        v1.10.4
root@master:~#

**Comment by thockin** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by amitvashist7** [comment]
Thank you very much for update @thockin

Kubernetes: v1.10.4

I manage to fix the problem by replacing fannel with calico.   

kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

Thank you.

**Comment by neolit123** [comment]
issue seems resolved as indicated by user comments.

/close
