### ISSUE TITLE
kube-dns failed to start

### ISSUE THREAD

**Issue by 372046933** [kubernetes/kubernetes#64455]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After `kubectl create -f kube-dns.yaml`, kube-dns failed to start

**What you expected to happen**:
kube-dns works
**How to reproduce it (as minimally and precisely as possible)**:
I can confirm that services which have type NodePort can be accessed By Node:Port, but kube-dns addon does not work. I appllied kube-dns.yaml after a fresh installation of Kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
 No cloud provider, hardware :Thinpad X1
- OS (e.g. from /etc/os-release):
 Arch Linux
- Kernel (e.g. `uname -a`):
 Linux arch 4.16.11-1-ARCH #1 SMP PREEMPT Tue May 22 21:40:27 UTC 2018 x86_64 GNU/Linux
- Install tools:
 AUR, the same official binary.
- Others:
 I have logs of each container in Pod kube-dns:

`kubectl logs --namespace kube-system kube-dns-7c7877989-nw764 dnsmasq 
failed to open log file "/var/log/pods/c2a8c2a5-6355-11e8-ab9a-34415d30919d/dnsmasq/1.log": open /var/log/pods/c2a8c2a5-6355-11e8-ab9a-34415d30919d/dnsmasq/1.log: no such file or directory`

`kubectl logs --namespace kube-system kube-dns-7c7877989-nw764 kubedns 
failed to open log file "/var/log/pods/c2a8c2a5-6355-11e8-ab9a-34415d30919d/kubedns/2.log": open /var/log/pods/c2a8c2a5-6355-11e8-ab9a-34415d30919d/kubedns/2.log: no such file or directory`

`kubectl logs --namespace kube-system kube-dns-7c7877989-nw764 sidecar 
I0529 15:34:23.965534       1 main.go:51] Version v1.14.8.3
I0529 15:34:23.965594       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0529 15:34:23.965634       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0529 15:34:23.965664       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
W0529 15:34:23.965864       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:57498->127.0.0.1:53: read: connection refused`

**Comment by thockin** [comment]
@372046933 can you please open this against github.com/kubernetes/dns instead?
