### ISSUE TITLE
kubeadm / dns - GetDNSVersion does not depend of the version

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#64454]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

I raised as a bug, but may be resolved as WAD ... 

**What happened**:

From that Review : #64258 

in this piece of code : https://github.com/kubernetes/kubernetes/pull/64258/files/8d8b47596e6e71ae705ed2fd1e946e32a98a42f0#diff-6f6577e723201d3cf7ff85de45a73068

```
const (
	kubeDNSVersion = "1.14.10"
	coreDNSVersion = "1.1.3"
)

// GetDNSVersion returns the right kube-dns version for a specific k8s version
func GetDNSVersion(kubeVersion *version.Version, dns string) string {
	// v1.9.0+ uses kube-dns 1.14.10, if feature gate "CoreDNS" is disabled.
	// v1.9.0+ uses CoreDNS  1.1.3.

	// In the future when the version is bumped at HEAD; add conditional logic to return the right versions
	// Also, the version might be bumped for different k8s releases on the same branch
	switch dns {
	case kubeadmconstants.CoreDNS:
		// return the CoreDNS version
		return coreDNSVersion
	default:
		return kubeDNSVersion
	}
}

```

**there is a comment:**
> 	// In the future when the version is bumped at HEAD; add conditional logic to return the right versions
> 	// Also, the version might be bumped for different k8s releases on the same branch

Obviously, there is no implementation of logic to return the DNS version that as pushed for one version of Kubernetes. (neither for kube-dns, neither for CoreDNS)

for instance:
  CoreDNS 1.0.0 was pushed in the release k8s v1.9.0
  CoreDNS 1.0.6 was pushed in the release k8s v1.10.0
  CoreDNS 1.1.3 is now pushed in the coming release k8s v1.11.0

However, the last version CoreDNS 1.1.3 is compatible with all versions of k8s (1.9 and highers).

**What you expected to happen**:
- A better description on **what logic should be encoded in this function**. Based on example of above, should that GetDNSVersion function return always 1.1.3 , or check k8s version and return 1.0.0 or 1.0.6 or 1.1.3 ?

- Maybe explanation on when this function will not be called with the version of k8s it is released on.

**Environment**:
- Kubernetes version (use `kubectl version`): last one - master for 1.11
- Install tools: kubeadm

**Comment by luxas** [comment]
@fturib Please reopen this in the dedicated kubernetes/kubeadm repository we use for tracking issue.
