### ISSUE TITLE
Flaky sig-cli conformance test

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#64450]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Some of the sig-cli Conformance tests are flaky (since several weeks) on those test suites:
- kubeadm deployment on GCE
- whatever the network defined (flannel, ipvs, etc ...)
(see [sig-network-gce test grid](http://k8s-testgrid.appspot.com/sig-network-gce#kubeadm-gce-ipvs))

these tests are also flaking (but with much lower rate) on version 1.10 and not seems stable on 1.9 (see [sig-cluster-lifecycle-all test grid](http://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-1.10))

The flay tests are:
- [sig-cli] Kubectl client [k8s.io] Update Demo should scale a replication controller [Conformance] 30s
- [sig-cli] Kubectl client [k8s.io] Kubectl run rc should create an rc from an image [Conformance]
- [sig-cli] Kubectl client [k8s.io] Kubectl rolling-update should support rolling-update to same image [Conformance]
- [sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance] 18s

the error reported, is always this one:

`Scaling the resource failed with: could not convert scale update to external Scale: scheme.Scale is not suitable for converting to \"v1\"
`

**What you expected to happen**:
These tests should either be fixed, either flagged as "flaky" (and unflagged as "Conformance") 

**How to reproduce it (as minimally and precisely as possible)**:
Look into corresponding test grid results.

**Environment:
I am looking at the Grid tests, as of today : Mon May 29th 2018.

**Comment by fturib** [comment]
Adding also Lifecycle as the flakyness seems related to kubadm deployment.

/sig cluster-lifecycle

**Comment by fturib** [comment]
pinging @soltysh, @pwittrock, @AdoHe, @luxas to be sure you are aware of this issue in the e2e for sig-cli conformance, in env kubeadm + gce.

**Comment by AishSundar** [comment]
There was one more instance of this test failing 1.8 GCE Conformance tests.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-stable-1-8/188

The expectation for the conformance suite is to be flake free. @soltysh, @pwittrock, @adohe, @luxas is there a fix being investigated or worked on? Thanks.

**Comment by liggitt** [comment]
this test appears to be failing *only* in the kubeadm e2e... do we know what version of kubectl is running in that test?

**Comment by adohe** [comment]
as what Jordan commented, please help provide the version info, we don't find any problem in Kubernetes conformance test.

**Comment by luxas** [comment]
> error: failed to discover supported resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: an error on the server

This ^ is interesting, from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-stable-1-8/188
Seems unrelated to `Scaling the resource failed with: could not convert scale update to external Scale: scheme.Scale is not suitable for converting to \"v1\"`, but suggests some of these tests might flake when API aggregation discovery suffers from intermittent connectivity problems (?). Also that test is v1.8...

Regarding 

> Scaling the resource failed with: could not convert scale update to external Scale: scheme.Scale is not suitable for converting to \"v1\"

Here are two links to follow for debugging (from the latest v1.11 branch)
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-11/89
 - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-11/97

First thing I see is:

> Command \"rolling-update\" is deprecated, use \"rollout\" instead

Which suggests we're conformance testing stuff that's deprecated :thinking:. I don't have lots of context on this yet, just started digging.

> could not convert scale update to external Scale: scheme.Scale is not suitable for converting to "v1"

At least I've traced the message to come from here I think: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/scale/client.go#L181.
I _guess_ this may be due to that `kubectl rolling-update` tries to scale an internal version of a v1 ReplicationController vs an external client-go API object (?): https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L404.

Maybe something here? https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L777?

**Comment by luxas** [comment]
cc @kubernetes/sig-api-machinery-bugs

**Comment by AishSundar** [comment]
cc @fedebongio to assign to appropriate owners within api-machinery

**Comment by liggitt** [comment]
>> error: failed to discover supported resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: an error on the server
> 
> This ^ is interesting, from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-stable-1-8/188
> Seems unrelated to Scaling the resource failed with: could not convert scale update to external Scale: scheme.Scale is not suitable for converting to \"v1\", but suggests some of these tests might flake when API aggregation discovery suffers from intermittent connectivity problems (?).

Determination of scale resources happens here:

https://github.com/kubernetes/kubernetes/blob/67e7d4c68ff8bcc3ce357e03ef3ddf2c688e417c/staging/src/k8s.io/client-go/scale/util.go#L62-L87

That only depends on the particular group/version being scaled, not full discovery. Additionally, a discovery error there would return an error, not return an incorrect scale group/version

**Comment by liggitt** [comment]
I'm only able to reproduce the error message by running a kubectl built from master against a 1.7-level API server:

```
$ kubectl-1.12 version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1504+67e7d4c68ff8bc", GitCommit:"67e7d4c68ff8bcc3ce357e03ef3ddf2c688e417c", GitTreeState:"clean", BuildDate:"2018-06-25T17:15:26Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.17-beta.0.1+347f652944cc23", GitCommit:"347f652944cc2348d59b1c815007e21e062fe597", GitTreeState:"clean", BuildDate:"2018-06-25T22:55:27Z", GoVersion:"go1.8.7", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl-1.12 create -f hack/testdata/frontend-controller.yaml
replicationcontroller "frontend" created

$ kubectl-1.12 scale rc/frontend --replicas=2
error: could not convert scale update to external Scale: scheme.Scale is not suitable for converting to "v1"
```

How does the kubeadm job set up its test environment? Can it have pre-1.8 discovery docs cached in its $HOME/.kube dir with recent timestamps (within the last 10 minutes)? If so, it could encounter this error.

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-11/89

currently we have this semi-secret artifact with the h̶o̶r̶r̶i̶b̶l̶e̶ fun test-infra bootstrap.py you can use to see *exactly* how it ran. the pod-utils don't have this yet:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-11/89/artifacts/prow_podspec.yaml

I don't think `$HOME/.kube` is being persisted. `HOME=/workspace` in that image which doesn't have .kube empty, and it's not a volume mount.

**Comment by liggitt** [comment]
added debugging to capture the current state of cached discovery docs for this test in https://github.com/kubernetes/kubernetes/pull/65462

**Comment by jberkus** [comment]
Adding priority:

/priority important-longterm

this issue is not a blocker for 1.13

**Comment by jberkus** [comment]
Hey, now that there is debugging, is anyone looking at deflaking this test?

**Comment by neolit123** [comment]
these tests were nuked with agreement between sig-cluster-lifecycle and sig-network a month ago or so.
this issue is out of date.

/close
