### ISSUE TITLE
kubelet: Expose CRI socket information

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#64460]
/kind feature

**What happened**:
It would be great if the kubelet would expose what CRI socket it's talking to in `.Status.NodeInfo` for example. CRISocket isn't exposed in the kubelet `ComponentConfiguration`, so there is no actionable way to query the kubelet for what CRI endpoint it's talking to.

In my specific use case, I want to know the CRI endpoint at the time of e.g. `kubeadm upgrade`
, while the value was only known and set as a flag at `kubeadm init` / `kubeadm join` time.

I see three easy-ish possible solutions, to expose the CRI endpoint in:
 - `Node.Status.SystemInfo.CRISocket`
 - `Node.Status.SystemInfo.CRISocket`
 - `KubeletConfiguration.CRISocket` / `KubeletConfiguration.CRI.Endpoint` / `KubeletConfiguration.CRI.Socket`

We talked about this in today's SIG Node meeting.

**Pros:**
 - The endpoint would become discoverable today

**Cons:**
 - We don't know exactly how all of the CRI work will fit together end to end yet, e.g. are we gonna support multiple CRI endpoints, different RuntimeClasses/Sandboxes etc?

**What you expected to happen**:

e.g. this field to be added and reconciled by the kubelet.
```go
// NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
type NodeSystemInfo struct {
	// MachineID reported by the node. For unique machine identification
	// in the cluster this field is preferred. Learn more from man(5)
	// machine-id: http://man7.org/linux/man-pages/man5/machine-id.5.html
	MachineID string `json:"machineID" protobuf:"bytes,1,opt,name=machineID"`
	// SystemUUID reported by the node. For unique machine identification
	// MachineID is preferred. This field is specific to Red Hat hosts
	// https://access.redhat.com/documentation/en-US/Red_Hat_Subscription_Management/1/html/RHSM/getting-system-uuid.html
	SystemUUID string `json:"systemUUID" protobuf:"bytes,2,opt,name=systemUUID"`
	// Boot ID reported by the node.
	BootID string `json:"bootID" protobuf:"bytes,3,opt,name=bootID"`
	// Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64).
	KernelVersion string `json:"kernelVersion" protobuf:"bytes,4,opt,name=kernelVersion"`
	// OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy)).
	OSImage string `json:"osImage" protobuf:"bytes,5,opt,name=osImage"`
	// ContainerRuntime Version reported by the node through runtime remote API (e.g. docker://1.5.0).
	ContainerRuntimeVersion string `json:"containerRuntimeVersion" protobuf:"bytes,6,opt,name=containerRuntimeVersion"`
	// Kubelet Version reported by the node.
	KubeletVersion string `json:"kubeletVersion" protobuf:"bytes,7,opt,name=kubeletVersion"`
	// KubeProxy Version reported by the node.
	KubeProxyVersion string `json:"kubeProxyVersion" protobuf:"bytes,8,opt,name=kubeProxyVersion"`
	// The Operating System reported by the node
	OperatingSystem string `json:"operatingSystem" protobuf:"bytes,9,opt,name=operatingSystem"`
	// The Architecture reported by the node
	Architecture string `json:"architecture" protobuf:"bytes,10,opt,name=architecture"`
+        // The CRI socket the kubelet is talking to
+        CRISocket string `json:"criSocket" protobuf:"bytes,11,opt,name=criSocket"`
}
```
@kubernetes/sig-node-proposals

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-proposals

**Comment by mtaufen** [comment]
We had held off putting the CRI config in the KubeletConfiguration object thus far, because we weren't sure if that was the appropriate place. Nobody's had time to give that a lot of thought yet. I'm likewise not really sure what's appropriate to expose in the Node object regarding CRI. If you could sketch out arguments for/against and use cases that would actually help a lot.

**Comment by luxas** [comment]
@steven-sheehy that's why we added `--cri-socket` to `kubeadm upgrade`, but it's not nice :/
