### ISSUE TITLE
E2E Tests: highly concurrent pod/service creation

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#6450]
TL;DR : I think this can be done in the **density tests**, we just need to vary them so that there are **collisions** (dupe pods) being submitted.

... In a real kube system, there is a likliehood that 10 or 20 RC's might be created simultaneously.  

We should ensure that the if we submit, say 100 concurrent pod creation requests, 
- (consistency) The systems state is consistent such that _duplicate_ pods aren't created, and at least some requests are _rejected_.
- (availability) every unique submission is eventually created.

**Comment by quinton-hoole** [comment]
Yes, we actually plan to run all e2e tests in parallel in the near future to cut down on elapsed time, and this will have the side effect of achieving both of your goals to some extent. But a dedicated e2e to test concurrent creation seems useful too.
