### ISSUE TITLE
kubelet's enable-debugging-handlers command line flag should default to false(?)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#64514]
"/run/", "/exec/", "/attach/", "/portForward/", "/containerLogs/", "/runningpods/" etc are installed at:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L306

These are supposed to be used ONLY for debugging, however they are always on by default. Can we please default `enable-debugging-handler` to false, so these are not installed by mistake?

**Comment by derekwaynecarr** [comment]
`/runningpods` is used for debugging and should only be used for testing, but the others are core function.

**Comment by dims** [comment]
@derekwaynecarr is there a need to switch off those core functions? ( looks like at least one use case is to switch off these in a master - https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L714 )
