### ISSUE TITLE
Kubernetes should support a grace periode for pod termination and SIGTERM/lifecycle

### ISSUE THREAD

**Issue by rtreffer** [kubernetes/kubernetes#64510]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

When a pod is `terminating` and has not lifecycle shutdown hooks `SIGTERM` is send to PID 1. Roughly at the same time others stop sending traffic to the pod.

This can lead to situations where the pod software is already shut down but other entities are still trying to reach the pod.

This behavior leads to errors and service disruptions.

**Workaround**

We added a `/bin/sh -c "sleep 15"` lifecycle hook to all pod containers that didn't specify a lifecycle hook. The results are promising: we see way less errors during deploys.

However there are 2 issues with this approach:
- Containers aren't guaranteed to have `/bin/sh`
- We've seen problems if the container / pod got corrupted (`/bin/sh` won't start)

**What you expected to happen**:

Kubernetes should respect the fact that it takes a moment to drain a pod. The exact timing depends on various factors (e.g. DNS TTL) and should be configurable.

There are various possible ways to solve this:
- A sleep or delay lifecycle hook
- Another grace periode that can be specified as part of the pod
- A kubelet flag

A similar solution was proposed with containers that execute on shutdown. However those solutions have a larger scope and won't solve the stability issues we were seeing with executing e.g. `/bin/sh` (docker and container can sometimes break) 

**How to reproduce it (as minimally and precisely as possible)**:

These exact timeline is well documented in the official documentation: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

The biggest offenders are (usually) nginx (SIGTERM == non-graceful shutdown) and a dns chache + headless services on the client side (IP stays active for the TTL duration).

**Anything else we need to know?**:

I have tried to implement a simple sleep lifecycle hook and it looks pretty straight forward.

**Environment**:
- Kubernetes version (use `kubectl version`): `version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): `debian jessie`
- Kernel (e.g. `uname -a`): `Linux 4.15.3+soundcloud2`
- Install tools: custom provisioning/installation based on release tarballs
- Others:

**Comment by schweikert** [comment]
Thank you for this!

I was surprised on how Kubernetes handles this, and I would actually have expected even a default wait time between removing the pod from the list of pods that should receive traffic, and the sending of the TERM signal. I think that the vast majority of containerized applications don't handle well the current behavior (especially considering that even after the TERM you might still get a few requests).

**Comment by rtreffer** [comment]
/remove-lifecycle stale
PR open/in progress...

**Comment by rtreffer** [comment]
@JorritSalverda the endpoint won't get removed, implementations (e.g. CoreDNS or Traefik) verify that the Pod is not in the terminating state. This is how the draining usually works.

**Comment by nvanheuverzwijn** [comment]
This issue is still a problem and is well documented in this blog post : https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/

SIGTERM is received by pod before endpoint deregister the pod. POD shuts down before iptables is changed. This is problematic and most operators won't think about this problem.

Adding a preStop lifecycle hook to all pods for a 5 second delay feels like a bad solution although, it fixes the issue.

Maybe the SIGTERM signal shouldn't be sent at the same time as the endpoint deregisteration ?
