### ISSUE TITLE
kubectl guestbook e2e test is flakey - needs to clean it's room after play dates, and get a namespace

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#6451]
kubectl guestbook should create and stop a working application

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:108
Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce/workspace/kubernetes/hack/../platforms/linux/amd64/kubectl [kubectl --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.kube/.kubeconfig create -f examples/guestbook] []  <nil> replicationControllers/frontend-controller
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave
Error: The resource 'projects/kubernetes-jenkins/regions/us-central1/targetPools/e2e-test-jenkins-default-frontend' already exists
[] <nil> 0xc2081b1280 exit status 1 <nil> true [0xc2080a6090 0xc2080a60b8 0xc2080a60e0] [0xc2080a6090 0xc2080a60b8 0xc2080a60e0] [0xc2080a60b0 0xc2080a60d8] [0x61e060 0x61e060] 0xc20812f5c0}:
Command stdout:
replicationControllers/frontend-controller
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave

stderr:
Error: The resource 'projects/kubernetes-jenkins/regions/us-central1/targetPools/e2e-test-jenkins-default-frontend' already exists

**Comment by quinton-hoole** [comment]
To fix this specific error I've deleted the offending GCE resource ("targetPools/e2e-test-jenkins-default-frontend") that was left undeleted after a previous test run.
The full solution is to:

1. retry a few times on failed resource deletes on e2e test completion.
2. run each e2e test instance in a unique namespaces, so if the above fails repeatedly, at least all tests after it won't fail.
3. at the end of each test run, blindly delete the entire namespace for that test run.

Q

**Comment by roberthbailey** [comment]
We've discussed this a few times before. @brendandburns suggested that rather than the third thing you propose, we write an e2e that cleans up anything that could be left behind during a test run. It could bookend each jenkins run -- if it finds anything at the beginning it just cleans it up without failing but if it finds anything at the end it fails to indicate a resource leak.

**Comment by quinton-hoole** [comment]
Yes, that's a good idea.  I'm not sure how easy/feasible it is to have one test run before/after all others within the Ginkgo test framework (currently it randomizes order, by design).  There is the concept of test suites (as in most other test frameworks), and suite initialization/teardown.  That might work.  I'll look into it.

**Comment by jayunit100** [comment]
regarding namespaces and e2e's maybe this could leverage  #6553 ?

**Comment by quinton-hoole** [comment]
Yes, agreed.  Further comments in #6553.

**Comment by wojtek-t** [comment]
This issue is more than half-year old without any update (guestbook e2e test has significantly changes since then).

I'm closing this one - we should open another one if we observe guestbook flakes.
