### ISSUE TITLE
Node soak tests should catch node daemon crashes

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#64523]
Yes.. It took me a while to "soak" that :p

An e.g of a serious bug we failed to catch because of that is https://github.com/kubernetes/kubernetes/issues/62808#issuecomment-392869993

cc @kubernetes/sig-node-bugs @yujuhong @dashpole

**Comment by shyamjvs** [comment]
/assign @yujuhong 
(hoping you'd triage)

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind cleanup

kind cleanup works better here

**Comment by aojea** [comment]
I want to share something that was useful to me in the past to catch issues related to leaks on long running environment.

The job was very simple (adapted to kubernetes):
1. Deploy a cluster
2. Snapshot and dump whatever you are interested to check for leaks (etcd, heap, ...)
3. Keep the cluster running for a long time (several days, one week, ... ), and start a loop (or multiple loops) that creates and delete whatever you are interested in, i.e.
```
 while true; do kubectl create pod && kubectl delete pod; done
```
4. Before destroying the cluster do another snapshot and dump, like in 2
5. Whatever is in the diff from point 4 and 2 should be a leak

**Comment by SergeyKanzhelev** [comment]
So we can run test like this: https://github.com/kubernetes/kubernetes/blob/91200bac44f0090a57702d214aa6ca1325a837c5/test/e2e/node/pods.go#L65, or even more simplified one, and run it in the loop for a while. 

I'm thinking what would be the best way to observe failures and measure things. Maybe use NPD instead of creating anything custom?

**Comment by SergeyKanzhelev** [comment]
/unassign @yujuhong 

/assign @mmiranda96 

Mike, can you check if the existing soak tests will cover this?

**Comment by AnishShah** [comment]
sig-node CI meeting:

Since we do not have any soak tests anymore, we are closing this issue.

/close

Ideally, we would like to have soak tests in future.
