### ISSUE TITLE
Add e2es for hostpath type field

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#64522]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
This feature is lacking coverage, especially for containerized kubelet environments.

**Comment by dixudx** [comment]
/assign

since I'm the owner of this feature.

**Comment by dixudx** [comment]
And #62159 just fixes a bug for containerized kubelet when the mount file is an empty file.

**Comment by dixudx** [comment]
@msau42 @jsafrane Are we going to enable these tests in v1.11? We're getting code freeze soon.

**Comment by msau42** [comment]
There is a local containerized cluster pull and CI job that we can probably leverage.  Right now it only runs conformance tests, we may be able to add new suites to enable other tests. Cc @childsb who is the owner for the containerized testing effort?

**Comment by dims** [comment]
yes, seems to be holding up pretty well - https://k8s-testgrid.appspot.com/conformance-providerless#local-up-cluster-containerized,%20master%20(dev)

**Comment by jsafrane** [comment]
In https://github.com/kubernetes/test-infra/pull/8199 I made pull-kubernetes-local-e2e-containerized to run also all test with `[ContainerizedKubelet]` string. I'm enabling some tests (subpath!) in https://github.com/kubernetes/kubernetes/pull/64687, feel free to suggest more tests.

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/64711#issue-329171077

**Comment by Random-Liu** [comment]
@dixudx IIUC, the default host path type is `HostPathUnset`. And when host path type is `HostPathUnset`, we expect container runtime to create the host path if it doesn't exist (docker is doing that today).

Is that true? If it is, we should revert part of https://github.com/kubernetes/kubernetes/pull/61460

**Comment by dixudx** [comment]
> IIUC, the default host path type is HostPathUnset. And when host path type is HostPathUnset, we expect container runtime to create the host path if it doesn't exist (docker is doing that today).

@Random-Liu Correct. This is mainly for backwards compatibility.

**Comment by Random-Liu** [comment]
@dixudx I see. If so, I'll change CRI definition. :) Thanks

**Comment by dixudx** [comment]
@Random-Liu SGTM. Refer to [my comments in #61460](https://github.com/kubernetes/kubernetes/pull/61460#discussion_r176016174).
