### ISSUE TITLE
Feature request: support annotation columns in "kubectl get"

### ISSUE THREAD

**Issue by danvk** [kubernetes/kubernetes#64529]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

There's an (extremely helpful) option to add a column based on a particular label to the outpout of `kubectl get`:

```
$ kubectl help get | grep -- '-L'
  -L, --label-columns=[]: Accepts a comma separated list of labels that are going to be presented as columns. Names are case-sensitive. You can also use multiple flag options like -L label1 -L label2...
```

It'd be great if there were a similar option for annotations (`-A` / `--annotation-columns`?)

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.1", GitCommit:"75d2af854b1df023c7ce10a8795b85d3dd1f8d37", GitTreeState:"clean", BuildDate:"2018-05-10T17:23:18Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): macOS
- Kernel (e.g. `uname -a`): `Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
- Install tools:
- Others:

cc @jamadeo

**Comment by blurpy** [comment]
I'd like that option too! Reopen?

**Comment by goto100** [comment]
It's useful when indicate the local-pv which node bound to
