### ISSUE TITLE
minimumGracePeriodInSeconds from eviction config can increase the grace period

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#64530]
/kind bug
/sig node
cc @mtaufen 

We use the gracePeriodOverride from the eviction manager (which is set to m.config.MaxPodGracePeriodSeconds for soft evictions) as the gracePeriodOverride that we pass to `killPod()`
This is consumed here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L568
Where it overrides whatever the pod's DeletionGracePeriodSeconds and Spec.TerminationGracePeriodSeconds.  Either the name is misleading, or it isn't actually a maximum, but rather is just "the" grace period for soft evictions.

**Comment by mtaufen** [comment]
@dashpole have you had time to work on this?

**Comment by dashpole** [comment]
I haven't worked on it.

**Comment by dixudx** [comment]
@dashpole I can pick it up if you are not available.

**Comment by dashpole** [comment]
@dixudx Sure, I am actually not sure if we rely on the broken behavior (it has been present since ~1.3), which is before my time.  Let me check with @vishh

**Comment by guineveresaenger** [comment]
@mtaufen @dashpole @dixudx - any updates on this?

**Comment by guineveresaenger** [comment]
@dashpole @mtaufen @dixudx Code Freeze is today. For this issue to remain in the 1.12 milestone, it needs to be of `priority/critical-urgent`. Please decide if you want to keep it in the milestone and are able to fix it before end of release.

cc @dchen1107 @derekwaynecarr

**Comment by derekwaynecarr** [comment]
removing from the milestone, we can do this update after 1.12.

**Comment by bboreham** [comment]
/reopen

The [docs](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#soft-eviction-thresholds) say "If specified, the kubelet uses the lesser value among the pod.Spec.TerminationGracePeriodSeconds and the max allowed grace period. If not specified, the kubelet kills Pods immediately with no graceful termination", which is grotesquely different from what the code does.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten
/triage accepted

@bobbypage seems to be related to the Pod termination. Can you please comment?

**Comment by bboreham** [comment]
@HirazawaUi and @tzneal : you seem to have worked in this area within the last year; can you comment on whether this is still an issue?

This comment is in current main: https://github.com/kubernetes/kubelet/blob/53d4f97c9149703abdd22c16d7cc5d9752dda2e4/config/v1beta1/types.go#L524-L526
```
	// Note: Due to issue #64530, the behavior has a bug where this value currently just
	// overrides the grace period during soft eviction, which can increase the grace
	// period from what is set on the Pod. This bug will be fixed in a future release.
```

**Comment by HirazawaUi** [comment]
let me take a look.
/assign

**Comment by HirazawaUi** [comment]
This issue still exists, `m.config.MaxPodGracePeriodSeconds` will still overwrite the value of `TerminationGracePeriodSeconds`.
ref: https://github.com/kubernetes/kubernetes/blob/418ae605ec1b788d43bff7ac44af66d8b669b833/pkg/kubelet/pod_workers.go#L1647-L1655

I'll try to fix it and check if changing it will cause breaking changes for other callers.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

PR is very close to be accepted
