### ISSUE TITLE
Port Forward fails on windows pod

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#64531]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Ran `kubectl port-forward win-pod-id :80` on windows pod and received the error message:

```
E0524 07:17:58.290956    3416 portforward.go:331] an error occurred forwarding 51886 -> 80: error forwarding port 80 to pod cf624f214b97021d604e4d65572098067b8958848629752477630a652135020f, uid : unable to do port forwarding: socat not found.
```
**What you expected to happen**:
The port be available on my localhost

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run windows-whoami -image=stefanscherer/whoami:windows-amd64-1.6.1-1803 
kubectl port-forward <pod-id> :8080
```

**Anything else we need to know?**:
socat is not available on windows nodes

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server version: 1.10.2

- Cloud provider or hardware configuration: Azure - acs-engine
- OS (e.g. from /etc/os-release): Windows Server 1803
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

**Comment by daschott** [comment]
I can confirm this on 1803:
```
Forwarding from 127.0.0.1:56768 -> 8080
Handling connection for 56768
E0829 16:31:14.584698    8712 portforward.go:331] an error occurred forwarding 56768 -> 8080: error forwarding port 8080 to pod d9482649a8b8293e0a88d0c84931c90fcccbe11233b9cb75a2d11acbde4e1c31, uid : unable to do port forwarding: socat not found
```

**Comment by jsturtevant** [comment]
What would be the approach to fixing this?  If connecting to a windows machine use a different tool other than socat?  Are there any tools that are used in the windows world for port-forwarding?

If I got some guidance on tools to use I could take a try at a PR for this.

**Comment by PatrickLang** [comment]
The problem is that the portForward streaming operation invokes `nsenter` and `socat` on the node. Those aren't available (or required) on Windows.

https://github.com/kubernetes/kubernetes/blob/a0c2788249ae1582d10089e7a34bb54fc6b3879d/pkg/kubelet/dockershim/docker_streaming.go#L204

**Comment by yujuhong** [comment]
> @jsturtevant I looked into this, I think that it could in theory work, the hard part about trying to use `netsh` is that it needs the IP address, whereas in this method all you have is the PID and `podSandboxID`

This function implemented by the CRI shim, which is capable of finding out the IP address by `podSandboxID`.

> It has the disadvantage of being less secure than the Linux side, which only exposes access to the stream to the Kubelet process instead of all processes, but I'm not sure that's a big security concern.

/cc @tallclair

**Comment by tallclair** [comment]
> It has the disadvantage of being less secure than the Linux side, which only exposes access to the stream to the Kubelet process instead of all processes, but I'm not sure that's a big security concern.

I'm a bit ignorant of all things windows. Does "all processes" really mean everything, including unprivileged containers, or do you just mean all processes in the host network namespace (or whatever the windows equivalent is)?

**Comment by benmoss** [comment]
It would have been just the host network namespace. This approach didn't really pan out though. @astrieanna is investigating another approach that more closely matches the way it works on Linux.
