### ISSUE TITLE
kubelet should not import schedulercache

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#64533]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind cleanup

pkg/kubelet uses the `NodeInfo` and `Resource` types defined in the scheduler cache implementation. From my read of the code, this is only used for tracking allocatable resources, but NodeInfo has a bunch of other state and functionality that is not needed.

If possible, I would like to remove this dependency.

If we decide that kubelet and scheduler need to share code, then I would like to extract the minimum amount of functionality into a better location.

/sig node
/sig scheduling

**Comment by misterikkit** [comment]
I just noticed that kubelet also depends on `"k8s.io/kubernetes/pkg/scheduler/algorithm/predicates".NodeInfo` which is a single method interface.

**Comment by k82cn** [comment]
@misterikkit , I think that because kubelet also use scheduler's predicate for admit; and in scheduler's admit, it need NodeInfo :). I think this is a requirement to scheduler to make `algorithm` to be a lib for other components :)

**Comment by misterikkit** [comment]
> @misterikkit , I think that because kubelet also use scheduler's predicate for admit; and in scheduler's predicate, it need NodeInfo :). I think this is a requirement to scheduler to make algorithm to be a lib for other components :)

You make a good point. This goes back to the question I raised a while back about the scheduler's go interface. I would love to export the needed parts without exporting our cache implementation.

**Comment by misterikkit** [comment]
I feel like this is sufficiently addressed by the work in  #68951 (combination of pending and completed work)

/close
