### ISSUE TITLE
CSR requested extensions ignored

### ISSUE THREAD

**Issue by james-callahan** [kubernetes/kubernetes#64547]
/kind feature

**What happened**:

Emitted certificate did not contain expected extensions

**What you expected to happen**:

Extensions from "requested extensions" should be in emitted cert.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat > my.csr << EOF
-----BEGIN CERTIFICATE REQUEST-----
MIICeTCCAWECAQAwADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK23
Lfm6ZnvLApyS+LA+gI9pAbSozUE6aF7mgZNko1B6LeLoB2Q0ej1oDoz3Boj5UavE
qQuGnHdN37e26i3oEeSlukT2EBv43QmugfFImD3HyooFiEy/4R8ghsLpaj8Pnu+u
Aovf2aWwQ0gOnPmXNbPn63IyRVDqOW0v/g/7f+3P81KgcC8c6OdwRE3IhcwmhLhw
IMxXQ2RTgBWnb9S2K1nByVWTkMVFkMiDFgsHKip7UP9XKauI0q92nvmiVtO/41X6
WVdb0eq2mgJye7iM5cnd0r9Ur/cs/3wNPcDYmFsG+a+m237GeGtO9ZhZXAFFH/yP
5SyclGyLukM5S3I/tPcCAwEAAaA0MDIGCSqGSIb3DQEJDjElMCMwIQYLKwYBBAGD
lCQFBQUEEhYQFg50aGlzIGlzIGEgdGVzdDANBgkqhkiG9w0BAQsFAAOCAQEAFAGp
efMdUm/hMhW2sHvFIz6FnGxKjp7KPzgNjlJA3+DPvVfI4w+SKAo/tmpE9totC1e3
pBqX25Ose8+VNiF/zYV2p+PJX0O2gM//Yu9ZAf6FgW3gM2xEMwrjxIKHpyh768v2
sqGGM+wx5/v/d9XssYBh5BILOSht81fH5hgZZ9UULEregr4kL2ZFZlCuDVt3Dw6N
Vw/AFr/qu0EIRDdB6gWiu3IfwZCtMNJLhv0A4i12zxbRdbIwaaDj2x26WOZrmkb3
P9DOEnPwOEeBeqLsNBJWe8FGbSx2q1/B3UXh5nS7YgLhNTr0FMREohNqQux9bQ+a
saH6NrUvTiVG+3DXjg==
-----END CERTIFICATE REQUEST-----
EOF
$ cat << EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: mycerttest
spec:
  groups:
  - system:authenticated
  request: $(cat my.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
$ kubectl certificate approve mycerttest
```

Observe that the input CSR contains a requested extension:

```
$ openssl req -noout -text -in my.csr | grep -A 2 Requested
        Requested Extensions:
            1.3.6.1.4.1.51748.5.5.5: 
                ....this is a test
```

Observe that the output cert does not contain the extension:

```
$ kubectl get csr mycerttest -o jsonpath='{.status.certificate}' | base64 -d | openssl x509 -noout -text |  grep -A 9 ext
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                34:45:E0:2A:C2:49:8D:11:AE:54:38:2B:D2:0E:AE:4C:C3:39:CE:8B
    Signature Algorithm: sha256WithRSAEncryption
         17:0b:ae:5b:30:60:13:e6:6c:fc:03:f5:cc:cf:f6:54:ed:0a:
```

**Anything else we need to know?**:

Marking the `critical` bit on the extension doesn't cause it to fail.

Here is a CSR with the critical bit set for the same requested extension:
```
-----BEGIN CERTIFICATE REQUEST-----
MIICfDCCAWQCAQAwADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANuf
CWLZVbTSNFUXCMeNrJZ6IckUbC/YovN6XUo61n7N+TO28oN7eiibaUAvIxxtLJRE
HauPDM/JNrsWipjUti2i0Xdukrl0E+jIbiYl08r8FO51Z7ITVa4L8uD7+kKuc5c+
+bLPh3zPVtvyvJHNqwc7LF4/EgxhU4Yc4GbVk7bMhdo8qWK6R2FSiqNzoipXSaK7
Kri+EelaoSR33oXHQBkQBZg1x2O3Df9CK8iReVkFI3D/sU8u2rL3ny2u757p64HG
5tlwhWZsZFm1WmClbMiZZsk81eJwrTA++qLe0Xi1WHhaY5yTKuZiz46e/Ne0WRMw
Z80cVpekW3IzCqdQBAcCAwEAAaA3MDUGCSqGSIb3DQEJDjEoMCYwJAYLKwYBBAGD
lCQFBQUBAf8EEhYQFg50aGlzIGlzIGEgdGVzdDANBgkqhkiG9w0BAQsFAAOCAQEA
K4lTI06KE+OWBeyiA+UiLNlfC/g5nbhysufu0GIgdg3r/aNOTAwSVhuXa0QVRwwZ
DeZYTvQqLDfBvqz4+6WFUKSkiT8EnJ7jQm1kTwRqlx1R24X5hUxVZUDJkOSD7txb
oq2KTlJIn8Of73JahQFYKqS4AhPBiKIiy1DGj3ifwtxbM7clukqvKtQ4eFWW38sE
trn3XBibYsosz9i5DfmVsuoV4w1RctEPfMD4Ar4nzc5cWrI7DJanih+GYdWguVzX
UC7NJNkAgGjbI24OlVkOb/FJ2F9M5Gqsoq4SBEDHdB5U3fQbmfdDERS+8jl0W6u3
R5aNnitcG6/s15JbyxLx+w==
-----END CERTIFICATE REQUEST-----
```

**Environment**:
- Kubernetes version (use `kubectl version`):
    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: minikube v0.27.0

**Comment by james-callahan** [comment]
CC @kubernetes/sig-cluster-lifecycle-bugs

This doesn't feel like it belongs with cluster-lifecycle, but from my searching they are the only SIG that touches the certificate code?
Marking as a bug as ignoring a 'critical' extension should be considered a bug.

**Comment by dims** [comment]
/sig auth

cc @mikedanese

**Comment by mikedanese** [comment]
The approvers should be responsible for validating the extension requests? That seems like an easy thing to forget to do, which would lead to unvalidated data signed into the certificate by the root CA.

> Marking as a bug as ignoring a 'critical' extension should be considered a bug.

Critical is an attribute of the extension not the extensions request.

**Comment by daurnimator** [comment]
> The approvers should be responsible for validating the extension requests? 

Yes!

> That seems like an easy thing to forget to do, which would lead to unvalidated data signed into the certificate by the root CA.

Indeed. So you might want to error for a request containing such extra extensions. Or prompt the user with an "are you sure". Or require the approved to specify the extensions allowed at some sort of configuration time.
What's not good is silently ignoring them...

> Critical is an attribute of the extension not the extensions request.

Good point!
However, the extensions request *is* paid attention to (e.g. a SAN request goes in there).
Is it okay to only half use it?

**Comment by james-callahan** [comment]
> The approvers should be responsible for validating the extension requests? 

Yes!

> That seems like an easy thing to forget to do, which would lead to unvalidated data signed into the certificate by the root CA.

Indeed. So you might want to error for a request containing such extra extensions. Or prompt the user with an "are you sure". Or require the approved to specify the extensions allowed at some sort of configuration time.
What's not good is silently ignoring them...

> Critical is an attribute of the extension not the extensions request.

Good point!
However, the extensions request *is* paid attention to (e.g. a SAN request goes in there).
Is it okay to only half use it?

**Comment by liggitt** [comment]
folded into CSR v1 tracking issue https://github.com/kubernetes/kubernetes/issues/69836

/close
