### ISSUE TITLE
v1.10.3 with vagrant 

### ISSUE THREAD

**Issue by duke66** [kubernetes/kubernetes#64561]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I am try to install kubernetes in vagrant local at macbook:
download https://github.com/kubernetes/kubernetes/releases/tag/v1.10.3 this and try to run:
KUBERNETES_PROVIDER=vagrant kubernetes/cluster/kube-up.sh

i got error with verify-kube-binaries:
"... Starting cluster using provider: vagrant
... calling verify-prereqs
Skeleton Provider: verify-prereqs not implemented
... calling verify-kube-binaries
./cluster/kube-up.sh: line 65: verify-kube-binaries: command not found"

Also i got this problem with run:
"export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash"

After that i`m try run v1.9.8 and got success with same command.

**What you expected to happen**:
Run k8s local in vagrant

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.10.3
- Cloud provider or hardware configuration:
MacBook pro
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by abdennour** [comment]
I have the same environment and I am facing the same issue. 

BTW, I go to vagrant and I left minikube because its connection keeps losing since the last upgrade ( 1.10)/

**Comment by abdennour** [comment]
Ok, so seems I  caught the issue. I moved the folder (kubernetes) after running `curl -sS https://get.k8s.io | bash`. This move broke the **symbolic link** `./client/bin` which a link of `/Path/Before/Move/kubernetes/platforms/darwin/amd64`. And since I moved the folder, `/Path/Before/Move/kubernetes/platforms/darwin/amd64` is no more exist. 

## solution: 
- Check the symbolic link of `./client/bin` and fix it. 

```
ls -l ./client/bin
```
- Export the path 

```
export PATH=$PATH:./client/bin
```

**Comment by abdennour** [comment]
After a deep dive into the code of this repository, I realized that `verify-kube-binaries` is missing function which currently exists in `./cluster/common.sh`.

## solution:

```sh
# combine two scripts in one
cat cluster/common.sh cluster/kube-up.sh > cluster/kube-up-fixed.sh

# grant exec permission for the user owner
chmod u+x ./cluster/kube-up-fixed.sh

#Enjoy
chmod +x ./cluster/kube-up-fixed.sh
```

**Comment by dims** [comment]
@abdennour thanks. Looks like we removed support for vagrant in 1.10, so closing this issue.

https://github.com/kubernetes/kubernetes/pull/58118

/close
