### ISSUE TITLE
SkewTest failing Kubectl client [k8s.io] Kubectl apply should apply a new configuration to an existing RC

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#64581]
Failing Job
--------------
[skew-cluster-latest-kubectl-stable1-gke](https://k8s-testgrid.appspot.com/sig-cli-master#skew-cluster-latest-kubectl-stable1-gke)

Gubernator logs
---------------------
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-master-new-gci-kubectl-skew/9015

Triage
--------
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=testing&job=ci-kubernetes-e2e-gke-master-new-gci-kubectl-skew&test=SkewTest

/kind bug
/priority failing-test
/sig testing

cc @soltysh @justinsb

**Comment by soltysh** [comment]
It looks like that was related to something else, since this hasn't happened since than.
