### ISSUE TITLE
Kube-DNS Name does not resolve. 

### ISSUE THREAD

**Issue by parvez84** [kubernetes/kubernetes#64586]
kind bug

**What happened**:

DNS lookup from within the pod fails. When using name to resolve. 

If you don't see a command prompt, try pressing enter.
[ root@curl-775f9567b5-ktcf5:/ ]$ nslookup 10.96.0.1
Server:    10.96.0.10
Address 1: 10.96.0.10

Name:      10.96.0.1
Address 1: 10.96.0.1

-- Returns just the IP. 

[ root@curl-775f9567b5-ktcf5:/ ]$ nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10

**nslookup: can't resolve 'kubernetes.default'**

[ root@curl-775f9567b5-ktcf5:/ ]$ curl google.com
curl: (6) Couldn't resolve host 'google.com'

**What you expected to happen**:

[ root@e457aa352100:/ ]$ curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>

The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

**How to reproduce it (as minimally and precisely as possible)**:

setup k8 using kubeadm
Tried both Flannel and Calico network. 

**Anything else we need to know?**:

kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns
I0531 22:06:48.850820       1 dns.go:48] version: 1.14.8
I0531 22:06:48.851676       1 server.go:71] Using configuration read from directory: /kube-dns-config with period 10s
I0531 22:06:48.851715       1 server.go:119] FLAG: --alsologtostderr="false"
I0531 22:06:48.851722       1 server.go:119] FLAG: --config-dir="/kube-dns-config"
I0531 22:06:48.851726       1 server.go:119] FLAG: --config-map=""
I0531 22:06:48.851730       1 server.go:119] FLAG: --config-map-namespace="kube-system"
I0531 22:06:48.851733       1 server.go:119] FLAG: --config-period="10s"
I0531 22:06:48.851737       1 server.go:119] FLAG: --dns-bind-address="0.0.0.0"
I0531 22:06:48.851740       1 server.go:119] FLAG: --dns-port="10053"
I0531 22:06:48.851745       1 server.go:119] FLAG: --domain="cluster.local."
I0531 22:06:48.851750       1 server.go:119] FLAG: --federations=""
I0531 22:06:48.851754       1 server.go:119] FLAG: --healthz-port="8081"
I0531 22:06:48.851757       1 server.go:119] FLAG: --initial-sync-timeout="1m0s"
I0531 22:06:48.851761       1 server.go:119] FLAG: --kube-master-url=""
I0531 22:06:48.851765       1 server.go:119] FLAG: --kubecfg-file=""
I0531 22:06:48.851768       1 server.go:119] FLAG: --log-backtrace-at=":0"
I0531 22:06:48.851773       1 server.go:119] FLAG: --log-dir=""
I0531 22:06:48.851777       1 server.go:119] FLAG: --log-flush-frequency="5s"
I0531 22:06:48.851780       1 server.go:119] FLAG: --logtostderr="true"
I0531 22:06:48.851783       1 server.go:119] FLAG: --nameservers=""
I0531 22:06:48.851786       1 server.go:119] FLAG: --stderrthreshold="2"
I0531 22:06:48.851789       1 server.go:119] FLAG: --v="2"
I0531 22:06:48.851793       1 server.go:119] FLAG: --version="false"
I0531 22:06:48.851802       1 server.go:119] FLAG: --vmodule=""
I0531 22:06:48.851834       1 server.go:201] Starting SkyDNS server (0.0.0.0:10053)
I0531 22:06:48.852022       1 server.go:220] Skydns metrics enabled (/metrics:10055)
I0531 22:06:48.852030       1 dns.go:146] Starting endpointsController
I0531 22:06:48.852033       1 dns.go:149] Starting serviceController
I0531 22:06:48.852279       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0531 22:06:48.852289       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0531 22:06:49.352319       1 dns.go:170] Initialized services and endpoints from apiserver
I0531 22:06:49.352343       1 server.go:135] Setting up Healthz Handler (/readiness)
I0531 22:06:49.352366       1 server.go:140] Setting up cache handler (/cache)
I0531 22:06:49.352373       1 server.go:126] Status HTTP port 8081
I0531 22:46:08.860229       1 sync.go:177] Updated upstreamNameservers to [172.24.162.201 172.24.162.191]
I0531 22:46:08.860257       1 dns.go:197] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[172.24.162.201 172.24.162.191]}
I0531 23:06:18.860249       1 sync.go:177] Updated upstreamNameservers to [8.8.8.8 8.8.4.4]
I0531 23:06:18.860278       1 dns.go:197] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[8.8.8.8 8.8.4.4]}
I0531 23:40:08.860190       1 dns.go:197] Configuration updated: {TypeMeta:{Kind: APIVersion:} Federations:map[] StubDomains:map[] UpstreamNameservers:[]}

**Environment**:

- Kubernetes version

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS 

NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by islinwb** [comment]
/sig network
@parvez84 What's the content of `/etc/resolv.conf`?

**Comment by parvez84** [comment]
Inside the busybox pod:

[ root@curl-775f9567b5-ktcf5:/ ]$ cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local np.costco.com corp.costco.com costco.com
options ndots:5

on the host:


[root@Master]# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4h
[root@Master]# kubectl get svc -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   4h

**Comment by krmayankk** [comment]
can you give more details, are you trying to do a reverse lookup for a pod ip ? See if things mentioned here would help https://github.com/kubernetes/dns/pull/232

**Comment by thockin** [comment]
Can you prove it is hitting DNS and getting a response?  e.g. can you tcpdump a DNS query?

**Comment by khenidak** [comment]
Can we try the following

1. Test if service selector are working
`
kubectl get endpoints kube-dns
`
> if this fails, i would look if service controller/controller manager are running correctly on the cluster. You should find (usually 2) endpoints, do they match your DNS pod ips?

2. does the pod actually work?
`
kubectl exec --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns -- nslookup google.com 127.0.0.1

kubectl exec --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns -- nslookup kubernetes 127.0.0.1
`
> Success on the first call means that dns can connect to your upstream dns server. success on the second means DNS itself is working and it is a network path to DNS server. if 1st failed check network path to upstream, if second failed then you should get health prop failures (do you get them?)

2. Test if your DNS pod is reachable from nodes (1 node + the node that has `curl-775f9567b5-ktcf5` pod)
`
nslookup google.com 10.96.0.10
`
> if not successful then your service (kube-proxy working? not hung?) or pod network routing is not working as expected. To test pod network try deploying nginx and curl it from node and/or a pod (using IP).

**Comment by parvez84** [comment]
Thank you all for your response,

I have part of it working ( 2/3 ) nodes. " *iptables -P FORWARD ACCEPT* "
looks to have fixed it on the working nodes . But the third node still has
issues.



Exec into the pod running on the broken node and running a traceroute.
Looks to me something is still broken on the host network.

From a working Host Pod can connect to the host network.

kubectl exec -it tcpdump-849c67847-jrw52 /bin/sh
/ # traceroute 10.96.0.10
traceroute to 10.96.0.10 (10.96.0.10), 30 hops max, 46 byte packets
 1  lawk8-no1315e.np.costco.com (10.209.29.105)  0.008 ms  0.005 ms  0.004
ms
 2^C
/ # nslookup kubernetes
nslookup: can't resolve '(null)': Name does not resolve

Name:      kubernetes
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
/ # nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.6.46 sfo03s08-in-f14.1e100.net
Address 2: 2607:f8b0:4005:809::200e sfo03s08-in-x0e.1e100.net
/ # nslookup 10.96.0.10
nslookup: can't resolve '(null)': Name does not resolve

Name:      10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
/ #

Broken Node:

kubectl exec -it tcpdump-849c67847-zshnj /bin/sh
/ # traceroute 10.96.0.10
traceroute to 10.96.0.10 (10.96.0.10), 30 hops max, 46 byte packets
 1  10.209.29.106 (10.209.29.106)  0.010 ms  0.016 ms  0.005 ms
 2^C
/ # nslookup kubernetes
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kubernetes': Try again
/ # nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'google.com': Try again
/ # nslookup 10.96.0.10
nslookup: can't resolve '(null)': Name does not resolve

Name:      10.96.0.10
Address 1: 10.96.0.10

**Comment by davidkarlsen** [comment]
I believe this is due to ndots:5 - try removing that

**Comment by cjbottaro** [comment]
> does the pod actually work?
```
kubectl exec --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns -- nslookup google.com 127.0.0.1

kubectl exec --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns -- nslookup kubernetes 127.0.0.1
```

> Success on the first call means that dns can connect to your upstream dns server. success on the second means DNS itself is working and it is a network path to DNS server. if 1st failed check network path to upstream, if second failed then you should get health prop failures (do you get them?)

@khenidak The second command fails for me. Here's the output of both:
```
$ kubectl exec -n kube-system kube-dns-6b4f4b544c-kkbt4 -c kubedns -- nslookup google.com 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      google.com
Address 1: 172.217.8.14 iad23s59-in-f14.1e100.net
Address 2: 2607:f8b0:4004:803::200e iad23s59-in-x0e.1e100.net
```

```
$ kubectl exec -n kube-system kube-dns-6b4f4b544c-7jhgr -c kubedns -- nslookup kubernetes 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes': Name does not resolve
command terminated with exit code 1
```

The logs don't show any errors, only one warning:
```
$ kubectl logs -n kube-system kube-dns-6b4f4b544c-kkbt4 dnsmasq
I0824 20:51:43.676865       1 main.go:74] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --dns-forward-max=150 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/in6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0824 20:51:43.677016       1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --dns-forward-max=150 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/in6.arpa/127.0.0.1#10053]
I0824 20:51:43.917534       1 nanny.go:119]
W0824 20:51:43.917557       1 nanny.go:120] Got EOF from stdout
I0824 20:51:43.917572       1 nanny.go:116] dnsmasq[13]: started, version 2.78 cachesize 1000
I0824 20:51:43.917597       1 nanny.go:116] dnsmasq[13]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0824 20:51:43.917606       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in6.arpa
I0824 20:51:43.917609       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0824 20:51:43.917612       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0824 20:51:43.917616       1 nanny.go:116] dnsmasq[13]: reading /etc/resolv.conf
I0824 20:51:43.917618       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in6.arpa
I0824 20:51:43.917623       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0824 20:51:43.917626       1 nanny.go:116] dnsmasq[13]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0824 20:51:43.917629       1 nanny.go:116] dnsmasq[13]: using nameserver 10.3.9.31#53
I0824 20:51:43.917633       1 nanny.go:116] dnsmasq[13]: read /etc/hosts - 7 addresses
```

Any help? I have no idea what to do and my cluster is borked now. Thanks!

**Comment by cjbottaro** [comment]
More info...
```
$ kubectl exec elasticsearch-master-0 -- nslookup google.com

nslookup: can't resolve '(null)': Name does not resolve
Name:      google.com
Address 1: 172.217.15.78 iad23s63-in-f14.1e100.net
Address 2: 2607:f8b0:4004:80c::200e iad23s42-in-x200e.1e100.net

$ kubectl exec etcd-web-7f6766f557-qjzhk -- nslookup google.com

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'google.com': Try again
command terminated with exit code 1
```
What's weird is that those pods are on the name node...
```
$ kubectl get pods -o wide | egrep "(elasticsearch-master-0|etcd-web-7f6766f557-qjzhk)"
elasticsearch-master-0                  1/1       Running            0          1d        10.3.5.147   ip-10-3-5-79.ec2.internal   <none>
etcd-web-7f6766f557-qjzhk               0/1       Running            27         3h        10.3.5.207   ip-10-3-5-79.ec2.internal   <none>
```

And they have the same `resolv.conf`:
```
$ kubectl exec etcd-web-7f6766f557-qjzhk -- cat /etc/resolv.conf
nameserver 10.3.0.10
search default.svc.cluster.local svc.cluster.local cluster.local edge.aworks.us
options ndots:5

$ kubectl exec elasticsearch-master-0 -- cat /etc/resolv.conf
nameserver 10.3.0.10
search default.svc.cluster.local svc.cluster.local cluster.local edge.aworks.us
options ndots:5
```

Thanks again.

**Comment by displays-resed** [comment]
@cjbottaro , may I ask how you resolved this, sir?

**Comment by sbeckwithiii** [comment]
@cjbottaro , may I ask how you resolved this, sir?

**Comment by vinodhbasavani** [comment]
I am also getting ```Name or service not known ``` logs inside my application pods when the pods are trying to connect to backends like databases(RDS,Elastic Cache Redis,Ec2 Mongo), I increased the number of pods of kube-dns thinking may be because of load. but no luck. Still seeing those errors in huge number.
Created a cluster using kops running with 1.8.8 version

**Comment by thockin** [comment]
Do you have a repro script?  This seems to hit some people very hard and
others not at all...

**Comment by sbeckwithiii** [comment]
After digging with the Google Cloud Support team and the GKE devs into our encounter with this issue, we learned that we were overloading our kube-dns with queries. So now we are aggressive in our configuration of kube-dns replica scaling and forward googleapis.com to 8.8.8.8 & 8.8.4.4.

Our name resolution issues have been mitigated by the following configuration changes deployed to each of our small clusters.

Create a kube-dns replica per node in our cluster, or 16 cores in cluster, whichever produces more replicas:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
data:
  linear: '{"coresPerReplica":16,"min":2,"nodesPerReplica":1,"preventSinglePointFailure":true}'
```

Forward googleapis.com name resolution requests to Google's public name servers:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "googleapis.com": ["8.8.8.8", "8.8.4.4"]
    }
  upstreamNameservers: |
    ["169.254.169.254"]
```

We are still investigating how we may improve our use of dns inside the cluster. Another change that was suggested, and we are in process implementing, was to use the fully qualified domain name of the kubernetes services rather than just their short name; and, this is important, we should end the name with a period in our use of it which tells the name server not to append anything to the domain name in an effort to match (resolve) it.

For example, if we have a service called "rabbitmq", instead of using "rabbitmq" in our app code we instead would use "rabbitmq.NAMESPACE.svc.cluster.local." If we want to communicate with a DB server by the name of "gce-my-db-server" that is a VM on the same network, then we reference it as "gce-my-db-server.c.PROJECT-ID.internal." (remember to end with a period).

**Comment by cjbottaro** [comment]
> @cjbottaro & @parvez84, may I ask did y'all resolve this?

Sorry, email notification for that question got lost in my email pit...

Anyway, I think all my issues were tied to using `amazon-vpc-cni`. I have no idea why, but _after a while_ my dns pods (which I switched to coredns) would stop being able to reach the Koob api, and thus not work.

I find it really strange that it takes 20-30 mins for the dns pods to start generating errors about reaching the api.

After switching to kube-router for networking, no problems at all.

My current cluster is for our pre-staging environment, so barely any load at all; nothing to warrant scaling DNS pods  and optimizing DNS queries like you're talking about.

**Comment by vinodhbasavani** [comment]
@sbeckwithiii 

```apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
data:
  linear: '{"coresPerReplica":2,"min":2,"nodesPerReplica":1,"preventSinglePointFailure":true}'```

I tried with this configuration thinking kube-dns pod may be overloaded with the dns queries. so it results in around 40+ dns pods. still getting the same errors in huge number.

**Comment by sbeckwithiii** [comment]
Update: I find that the errors are continuing. Increasing the kube-dns replica count did not resolve the issue. Why it was abated for some days is unknown to me at this time. We are currently investigating and looking for the least common denominator or some sort of pattern beyond, "every pod on a given node begins failing to communicate across the network."

**Comment by franck102** [comment]
Has anyone any further troubleshooting steps for this?
My DNS pod is healthy and other pods reach it fine, I can resolved external names but nothing under svc.cluster.local.
The 2nd command mentioned above fails for me:

```
... nslookup kubernetes 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes': Name does not resolve
command terminated with exit code 1

```
This only happens intermittently, typically after restarting minikube. Restarting the kube-dns pod doesn't help.

**Comment by franck102** [comment]
Solved... my pods were pointing at the DNS server running on the Minikube VM, not at kube-dns, so this is a minikube problem on restart.

As a side note in case that helps someone, changing the "-v=2" arguments in the kube-dns deployment spec is all it takes to see kube-dns actually creating its records as it detects services and pods.

**Comment by sbeckwithiii** [comment]
Update on our story. It seems we were partially overload Kube-DNS plus there was a bug in the GKE provided DNS server. So updating our Kube-DNS configmap alleviated the issue, then the GKE team supplied a new DNS configuration for their managed services which likely would resolve the issue for us without making the kube-dns changes.

However, I realize this is the Kubernetes repo and anyone who is not on GKE may still benefit from the final, settled kube-dns config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "internal": [ "169.254.169.254" ]
    }
  upstreamNameservers: |
    [ "8.8.8.8", "8.8.4.4" ]
```

What does this config do? As I understand it after reading the docs and hearing from GKE support, this has *only* internal names resolve to the internal DNS server `169.254.169.254` (this IP may be different for you if you are not on GKE); everything else resolves to the upstream name servers which are in this case Google's public name servers. What does this accomplish? It allows kube-dns to quickly determine if the lookup request is internal, and if it is not then send the request upstream. Our company's code base running in k8s makes a great many DNS queries on a regular basis so this change did help us a lot before GKE team even applied their internal DNS fix.

**Comment by canthefason** [comment]
as far as I can tell, internal is a TLD used by GCP as a part of their [internal DNS](https://cloud.google.com/compute/docs/internal-dns). 

On the other hand, the IP address belongs to the metadata server, which is also responsible for resolving internal domain names.

**Comment by boisde** [comment]
same issue. changed to coredns. and resovled.

**Comment by freehan** [comment]
reopen if needed

**Comment by itsecforu** [comment]
@boiside how u resolve it with coredns?

**Comment by trungphungduc** [comment]
> I believe this is due to ndots:5 - try removing that

I got the same issue.
I exec into the pod and then remove ndots: 5 or modify to ndots:1 (of file /etc/resolv.conf)
=> its working, but i don't know why ?
pls someone tell me how to solve this problem (without exec into pod) ?
