### ISSUE TITLE
kubectl config view --minify does not work with --context

### ISSUE THREAD

**Issue by tanelso2** [kubernetes/kubernetes#64583]
/kind bug

**What happened**:
Current context was set to cluster1.
Ran `kubectl config view --minify --context=cluster2` and got back information about cluster1 instead.

**What you expected to happen**:
I expected the output to be the cluster2 information

**How to reproduce it (as minimally and precisely as possible)**:
Have two contexts in your kube config, A and B
Run `kubectl config use-context A` to set A as current context
Run `kubectl config view --minify --context=B`

**Anything else we need to know?**:
I'd like to help contribute, so if this is an easy fix, someone point me in the right direction and I'll try to get it done.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- OS (e.g. from /etc/os-release): MacOS 10.11.6
- Install tools: kubectl was installed via brew

**Comment by tanelso2** [comment]
@kubernetes/sig-cli-bugs

**Comment by dixudx** [comment]
/assign

Filed #64608
