### ISSUE TITLE
Improve usability of CSI operation metrics

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#64590]
The operation metrics emitted by k8s usually contain plugin name as a dimension. The plugin name is typically obtained by calling `GetPluginName` interface function. But for CSI plugins, this is hardcoded to return "kubernetes.io/csi" and whenever a user is running multiple CSI plugins - he won't be able to distinguish between metrics emitted for CSI volumes.

/sig storage

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by cofyc** [comment]
I suggest to add a utility function to get driver name of volume spec, e.g.

```
func GetDriverName(spec *volume.Spec) string {
    if spec.PersistentVolume != nil && spec.PersistentVolume.Spec.CSI != nil {
        return spec.PersistentVolume.Spec.CSI.Driver
    } else {
        return ""
    }
}
```

Example metrics output:

```
storage_count_attachable_volumes_in_use{node="127.0.0.1",volume_plugin="kubernetes.io/csi",driver="csi-hostpath"} 1
storage_count_attachable_volumes_in_use{node="127.0.0.1",volume_plugin="kubernetes.io/rbd",driver=""} 1
```

What do you think?

`flexvolume` plugin has `driver` too and use `driver` as part of plugin name. Do we have any plan to register each CSI driver as a separate volume plugin dynamically, like [flexvolume](https://github.com/kubernetes/kubernetes/blob/v1.13.0-alpha.3/pkg/volume/flexvolume/probe.go#L38)?

**Comment by msau42** [comment]
Instead of adding a new driver field, can we put the driver name as part of volume name?  So something like "kubernetes.io/csi:csi-hostpath"

**Comment by cofyc** [comment]
I'm fine to put the driver name as part of volume name.
