### ISSUE TITLE
x509: certificate is valid for hcp-kubernetes, kubernetes, ..., but not kuberetes.default

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#64594]
```
Get https://kubernetes.default/apis/prow.k8s.io/v1/namespaces/default/prowjobs?labelSelector=: x509: certificate is valid for hcp-kubernetes, kubernetes, kubernetes.default.svc, kubernetes.default.svc.cluster.local, hcp-kubernetes.5ae8e942048c2a0001097578.svc.cluster.local, acse-test-infrastructure-ci-bot-61041a9a.hcp.eastus.azmk8s.io, not kubernetes.default
```
@kubernetes/sig-azure-misc how can that happen?

cc @Cecilerobertmichon

**Comment by feiskyer** [comment]
@kargakis How the cluster managed? is it a AKS or acs-engine cluster? 

Looks same with https://github.com/Azure/AKS/issues/399 and it's been fixed in newer versions.

**Comment by kargakis** [comment]
I think it's AKS but @CecileRobertMichon can confirm.

**Comment by feiskyer** [comment]
@kargakis Are there still such issues? If not, let's close it.
