### ISSUE TITLE
Need documentation of containerized kubelet

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#64603]
/kind bug
/sig storage

We need some document that would capture design of containerized kubelet.

* How kubelet  + `pkg/util/mounter` + `pkg/util/nsenter` come together.
* What's expected to be set in the container that runs kubelet.
  * It needs `-v /:/rootfs:ro`
  * It needs `-v /var/lib/kubelet:/var/lib:kubelet:rw:rslave`
  * It must be privileged.
  * Anything else?
* How is it tested in e2e.
* How can it be tested with local-up-cluster.sh.

When it's done, we should remove "kubelet" from `pkg/util/mounter/*`,  `util` is generic to all Kubernetes components.

cc: @msau42 @cofyc @thockin

**Comment by wongma7** [comment]
Do we need also `-v /dev:/dev:rslave`? We have it in openshift, I believe it was added in case kubelet does Attach. Regardless, I think we do need to keep it for block device symlinking.
