### ISSUE TITLE
Plugin watcher server failing sometimes with err: too many open files

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes/kubernetes#64614]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
pull-kubernetes-kubemark-e2e-gce-big was failing consistently after #63328 merge. On looking through logs found that kubelet is failing to start on some of the nodes because plugin watcher server failed to start with:
> kubelet.go:1354] failed to start Plugin Watcher. err: failed to start plugin watcher, err: too many open files
 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/14430/artifacts/kubemark-500-minion-group-9k9v/kubelet-hollow-node-5twz7.log

**What you expected to happen**:
Plugin watcher not to fail to start

**How to reproduce it (as minimally and precisely as possible)**:
Add a test PR with plugin watcher feature gate enabled 

**Anything else we need to know?**:
related #64303

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig node

**Comment by RenaudWasTaken** [comment]
I'm seeing an error (line 8) much more early in the process that seems related:

E0530 16:39:48.380138      10 file_linux.go:61] Unable to read config path "/tmp/hollow-kubelet.850040081/static-pods428572988": unable to create inotify: inotify_init: too many open files
Are the kubelet ran on the same node?

Given that fsnotify needs to keep at least one file opened for each path / file it watches if the 500 node test runs multiple kubelets on the same machine it would seem reasonable that we are hitting that limit much earlier than before.

A simple fix would be to raise that limit or have less kubelet per node.

**Comment by vikaschoudhary16** [comment]
@RenaudWasTaken similar was my guess on underlying host limits. Will verify with test PR.

**Comment by RenaudWasTaken** [comment]
Any update on this?

**Comment by figo** [comment]
@RenaudWasTaken @vikaschoudhary16 
this definitely looks like hitting the node open file limit.

i looked at latest run, they are all passing, i saw configure `--gcp-nodes=7` in test log, basically means each node run about 71 kubelets

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/16223?log#log

we probably can close this issue now.

**Comment by figo** [comment]
@vikaschoudhary16 thanks for the explanation, please cc me in your fix, thanks
