### ISSUE TITLE
[Failing Test] : gce-ingress-1.11 job failing on Kubetest timeout in 1.11-release-blocking

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64619]
## Failing Job

* [sig-release-1.11-blocking#gce-ingress-1.11](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-ingress-1.11)

## Error
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/2747#timeout

## Build Log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/2747?log#log

/kind bug
/priority failing-test
/priority critical-urgent
/sig testing
/milestone v1.11
@kubernetes/sig-testing-bugs 

cc @jberkus @tpepper

/assign @BenTheElder to investigate

**Comment by rramkumar1** [comment]
@AishSundar Hmm, I'm not seeing anything related to leaked resources anymore unless I'm completely missing something. Is it possible that this test just needs a larger timeout?

**Comment by AishSundar** [comment]
@rramkumar1 I see this in the [build log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/2778?log#log) 

 Error while deleting the ingress e2e-tests-ingress-q86mp/pre-shared-cert with class : ingresses.extensions "pre-shared-cert" not found

W0604 05:13:24.245] 2018/06/04 05:13:24 main.go:309: Something went wrong: encountered 2 errors: [error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:Ingress\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true (interrupted): signal: aborted (core dumped) Error: 2 leaked resources

**Comment by rramkumar1** [comment]
@AishSundar Can we first try increasing the timeout and see what happens? I suspect that maybe the timeout is causing some resource leaks but I'm not sure.

**Comment by AishSundar** [comment]
The only concern with increasing the timeout straight away is that the same job passes consistently on all other branches (master, 1.9, 1.10). So does this point to a legit 1.11 issue? Is this a global timeout we will be increasing for the job in all places? 

@BenTheElder @krzyzacy thoughts on increasing the timeout as the first step?

**Comment by krzyzacy** [comment]
sure

**Comment by rramkumar1** [comment]
FWIW, we aren't having any failures in our ingress-gce jobs:


https://k8s-testgrid.appspot.com/sig-network-ingress-gce-e2e#ingress-gce-e2e-release-1.1 (Ignore the failure to acquire project errors)

The release-1.1 job tests v1.1.1 of GLBC which is used in k8s 1.11. Note that this test in on GCE not GKE.

**Comment by BenTheElder** [comment]
from a [recent job](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/2785/?log#log):

```
W0604 18:28:50.445] 2018/06/04 18:28:50 main.go:309: Something went wrong: encountered 2 errors: [error during ./hack/e2e-internal/e2e-down.sh (interrupted): signal: aborted (core dumped) Error: 31 leaked resources
W0604 18:28:50.445] +NAME                    ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
W0604 18:28:50.445] +test-6724261826-master  us-central1-f  n1-standard-1               10.128.0.2   35.224.67.131  STOPPING
W0604 18:28:50.446] +NAME                       ZONE           SIZE_GB  TYPE         STATUS
W0604 18:28:50.446] +test-6724261826-master     us-central1-f  20       pd-standard  FAILED
W0604 18:28:50.446] +test-6724261826-master-pd  us-central1-f  20       pd-ssd       FAILED
```
That is a resource leak, not a timeout. Above in the log you can see the e2es pass and ginkgo exits cleanly then kubetest calls e2e-down.sh, which is erroring with the error pasted above.

**Comment by rramkumar1** [comment]
@BenTheElder  Just based on the snippet, it seems like disks are being leaked too? This might be a larger problem than just ingress if that is true.

**Comment by BenTheElder** [comment]
@rramkumar1 yeah that's my thought, but it almost definitely won't be fixed by bumping the timeout and I don't think infra changes will fix it, smells like a bug in k8s tests / up-down. @krzyzacy any ideas there?

**Comment by krzyzacy** [comment]
I mean, we aborted in middle of kube-down, that's not a good state.. 

If the test indeed takes more time now I think bump timeout should help.

**Comment by rramkumar1** [comment]
Looks like increasing the timeout worked?

See latest run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-ingress/2788

**Comment by AishSundar** [comment]
@rramkumar1 yes indeed. Thanks all closing the issue.
