### ISSUE TITLE
Consider logrus for better logs

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#6461]
It looks nice, retails log fields rather than just strings.

https://github.com/Sirupsen/logrus

**Comment by erictune** [comment]
Structured logging is nice.
We should consider as an alternative to events post-v1.
Comparison:
  - events has api versioning, how to do with logrus?
  - with events, hard to compact events with similar but slightly different Reason string.  If those strings are structured like logrs, easier to compact.
  - with events 
  - with events, we can select which logs we want to persist to API and which we don't.  How to do with logrus?

**Comment by timothysc** [comment]
There are now multiple areas all saying similar things.  About time to resurrect?

**Comment by thockin** [comment]
There are a bunch of log libraries that look attractive.  I have some notes
somewhere, but I am about to get on a plane.  Are you offering up sopme of
your own time? :)  Let's talk...

On Thu, Apr 28, 2016 at 2:01 PM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment]
Yup, so long as there is an agreed upon path.

**Comment by timothysc** [comment]
@thockin thoughts? 

/cc @timstclair

**Comment by thockin** [comment]
I'm swamped today - can we maybe do a hangout or something to discuss
options, which will force me to gather my notes...  later this week or
early next?

On Tue, May 10, 2016 at 9:30 AM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment]
sgtm.

**Comment by timstclair** [comment]
Please include me as well.

**Comment by timothysc** [comment]
![image](https://cloud.githubusercontent.com/assets/169553/15160765/f590cff4-16c0-11e6-9839-717f26988725.png)

sorry, just had to it.

**Comment by thockin** [comment]
This fell off everyone's plate.  Maybe it's something we can spec for
community cleanups in 1.5?  If we spec it and do some examples I have faith
that more will get done...

**Comment by kdomanski** [comment]
@thockin Consider resurrecting this issue.

**Comment by tallclair** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/25521
