### ISSUE TITLE
[Failing Test] : gke-ingress-1.11 job failing to checkout Boskos project 1.11-release-blocking

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64620]
## Failing Job
* [sig-release-1.11-blocking#gke-ingress-1.11](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-ingress-1.11)

## Error
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-ingress/2836

Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resource not found

/kind bug
/priority failing-test
/priority critical-urgent
/sig testing
/milestone v1.11
@kubernetes/sig-testing-bugs

cc @jberkus @tpepper

/assign @BenTheElder to investigate

**Comment by AishSundar** [comment]
From offline discussion with @krzyzacy looks like there is a resource leak with a new NIG in place. @rramkumar1 can you PTAL

/assign @rramkumar1 
/sig network
@kubernetes/sig-network-bugs

**Comment by BenTheElder** [comment]
adding that this leak affects on the ingress job GCP project pool so while this will block those jobs it shouldn't affect other testing in the meantime

**Comment by rramkumar1** [comment]
@freehan has a script to clean up the leaked NEG resources. Hopefully things should clear up after we run it.

**Comment by rramkumar1** [comment]
It looks like stuff has been cleaned up in all ingress projects. @krzyzacy Can you confirm?

**Comment by krzyzacy** [comment]
Yup it looks fine now. We probably should add the script in janitor itself?

**Comment by AishSundar** [comment]
test is passing now https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-1.11
