### ISSUE TITLE
TestVolumeBinding flakes

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#64626]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
/assign

**What happened**:
Here's some failures
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64447/pull-kubernetes-integration/14448/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64478/pull-kubernetes-integration/13886

**Comment by cofyc** [comment]
More recent failures from https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestVolumeBinding&include-filter-by-regex=TestVolumeBinding%24:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65886/pull-kubernetes-integration/18493
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65837/pull-kubernetes-integration/18352
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63707/pull-kubernetes-integration/18269

**Comment by cofyc** [comment]
@msau42 I submitted a PR to fix recent PVAssumeCache.Assume out-of-sync failures: https://github.com/kubernetes/kubernetes/pull/66106.

**Comment by msau42** [comment]
I wonder if this could be the same issue as https://github.com/kubernetes/kubernetes/issues/64239

**Comment by cofyc** [comment]
@msau42 Not sure yet, but there are some other flakes:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65616/pull-kubernetes-integration/19472
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65616/pull-kubernetes-integration/19468

I'll keep tracking this issue.

/reopen

**Comment by cofyc** [comment]
Oh, my mistake, these are failures tests of https://github.com/kubernetes/kubernetes/pull/65616 when PR is not completed.

/close
