### ISSUE TITLE
Run job on each node once to help with setup

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes/kubernetes#64623]
Hello, 

I am looking to see if it is possible to have a job run on each node in the cluster once. Right now our cluster is dynamically provisioned and scaled and was looking to use the kubernetes job and cronjob feature to run things to setup the node once it is provisioned or have a cron make sure something is cleaned up on each node.

**Comment by CaoShuFeng** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by mitchellmaler** [comment]
@CaoShuFeng I guess a daemonset would work but I was looking more towards the job/cron-job api to have something scheduled from the kubernetes side. I guess I could create a container with a cronjob which is ran from a daemonset.

**Comment by CaoShuFeng** [comment]
> I guess I could create a container with a cronjob which is ran from a daemonset.

:+1:

**Comment by mitchellmaler** [comment]
Currently we got around this by using a third party tool to run automation on the nodes. It would be useful if jobs (daemon jobs) could be ran once on each node and even if based on node selector.

**Comment by luisdavim** [comment]
I've seen this being requested many times and I think that `DaemonSet`s should allow for a `RestartPolicy` of `OnFailure` and jobs should allow using that to execute tasks on all nodes once.

**Comment by draveness** [comment]
Hi @luisdavim, do we still need to support this feature? Maybe I could submit a PR to add `OnFailure` policy to `DeamonSet`.

**Comment by luisdavim** [comment]
Sure, for now I've a workaround using metacontroller and a CRD but having this being supported natively would be great.

**Comment by draveness** [comment]
@luisdavim  OK. Is it necessary to open a proposal for this change? And if it is, where should I raise it. :)

**Comment by draveness** [comment]
I found out there are multiple issues which discussed the support of run a once off task with daemonset. 

https://github.com/kubernetes/kubernetes/issues/36601
https://github.com/kubernetes/kubernetes/issues/50689
https://github.com/kubernetes/kubernetes/issues/69001

Support `OnFailure` policy in daemonset policy seems quite reasonable. It could support run once job to some extent, though it cannot ensure the task run precisely once on each node.

@kubernetes/sig-apps-feature-requests

**Comment by IAXES** [comment]
This would be a helpful feature. In my use case, I use a CLI tool that extracts various parameters from the node in order to generate a (large) set of taints on all the nodes/masters in the cluster. The taints are applied via a simple Python microservice that imports the `kubernetes` package, and basically iterates over all nodes/masters and applying the equivalent of `kubectl taint...`. The service also has to keep track of new nodes as they are added to the cluster.

It would be preferable if we could instead schedule a short-lived job on each node that runs before any other pods/deployments can be scheduled on the node.

**Comment by luisdavim** [comment]
This implements a type of job that runs to completion on every node:
https://github.com/AmitKumarDas/metac/tree/master/examples/daemonjob
@IAXES for your use case, have you looked into static pods?

**Comment by IAXES** [comment]
@luisdavim Thanks for the link. Also, yes, I had considered using static pods, but I'm aiming to go with a long-term solution (ideally part of K8S itself so it gets ample test/use coverage) that operates in a one-shot manner (i.e. in the case of static pods, when they're done, there's no need for them to be running anymore, even if they're just idling in a sleep-loop).

**Comment by SimonHeimberg** [comment]
Workaround patterns I found while reading about this feature:
### run once on each node:
 * metacontroller and CRD, like https://github.com/kubernetes/kubernetes/issues/64623#issuecomment-575130863
 * daemonset with pod having wait forever at end (or maybe job as init container and rancher/pause as app container)
    runs 1x at start (node or daemonset) + 1x after each reboot
  
### periodic job
 * daemonset with pod having a loop around job and sleep
 * daemonset with pod running cron

**Comment by pigletfly** [comment]
We can use BroadcastJob in https://github.com/openkruise/kruise now.It's a job that runs Pods to completion across all the nodes in the cluster.

**Comment by IAXES** [comment]
@pigletfly Is there a long-term plan to have some/all of these features in OpenKruise be merged upstream into mainline K8S?

Also, thank you: the `BroadcastJob` seems to fit the use case I was raising.

**Comment by Dysproz** [comment]
Based on solution that I've came up for [contrail-operator](https://github.com/Juniper/contrail-operator) project, I've created separate project with custom resource DaemonJob that should cover that problem: [DaemonJob](https://github.com/Dysproz/DaemonJob)

**Comment by james-callahan** [comment]
One major drawback of working around this with a daemonset is that you need to use a `pause` pod to keep the pod "alive" and hence not get continuously restarted. This burns up a pod ip, which are quite precious in e.g. AWS CNI, where certain instance types can only have 4 pods per node.

**Comment by zwpaper** [comment]
I will try to look into this 
/remove-lifecycle stale

**Comment by zwpaper** [comment]
after dive into the source code, the main stopper for a daemonSet to run `OnFailure` pods is the API validation here, https://github.com/kubernetes/kubernetes/blob/51ff4bb814a394aa5753b559e87fcdf3fc775d9f/pkg/apis/apps/validation/validation.go#L347, both daemonset and pod controller could work as expected in some simple scenarios, but it is not easy to cover all the cases caused by the change.

@soltysh explains [here](https://kubernetes.slack.com/archives/C18NZM5K9/p1630924750021800)

> ALL workloads controllers (daemonset, deployment, statefulset, etc) are enforcing policy to Always is coming from the desire of those application to always run

A 3rd party controller is recommended for this feature.

/close

**Comment by pigletfly** [comment]
> @pigletfly Is there a long-term plan to have some/all of these features in OpenKruise be merged upstream into mainline K8S?
> 
> Also, thank you: the `BroadcastJob` seems to fit the use case I was raising.

I don't think so.Now OpenKruise is a CNCF sandbox project.

**Comment by janetat** [comment]
2022, If there is any native solutions?

**Comment by sarav-ks** [comment]
+1 for a native solution to support **OnFailure** for daemonSet

**Comment by smlx** [comment]
I found a fairly elegant solution to this issue using DaemonSet pods which label the node they are running on. I wrote it up [here](https://www.sl.id.au/posts/kubernetes-run-pod-once-per-node/).

**Comment by kerthcet** [comment]
Maybe this is a more high-level demand than job API, I suppose can we add a policy to Job named like `runInDaemon`, than we'll inject a podAntiAffinity to job to achieve similar behaviors. cc @alculquicondor

**Comment by alculquicondor** [comment]
https://www.sl.id.au/posts/kubernetes-run-pod-once-per-node/

This solution might conflict with cluster-autoscaler. It makes it hard to predict what labels new nodes will have (with or without). A similar thing happens with taints/tolerations.

cc @x13n

**Comment by kerthcet** [comment]
Since this issue is still opened, so I think people in this thread would show some interests with the progress. I just drafted a google doc here to support this feature, hope to hear your voices. Thanks a lot. https://docs.google.com/document/d/1QnAre0Eh8yaDxAnm_3ZrOhbE3d0J-BuieLa25_jzMOE/edit#heading=h.xgjl2srtytjt

**Comment by alculquicondor** [comment]
Let's close this in favor of #115716
