### ISSUE TITLE
Find a new home for bootstrap tokens consts & utilities 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#64627]
**This is a CLEANUP/ REFACTOR **:
During 1.11 release, as part of https://github.com/kubernetes/kubernetes/pull/64408/commits/33f59e438e93b824492caff5d39fd143b43eac9a there were concerns raised by @lavalamp regarding whether the aforementioned code belongs there, or in a different location. 

from slack: 
```
Yeah, an "api" that's ONLY in the *go* client, under a random tools directory, is not really acceptable. Doesn't work for other languages, and it can't be enforced correctly, etc. If it's just a convention then some combination of: it shouldn't be called an api (?), should be documented such that you can repeat from other languages, should be implemented in a control plane component and not a client, should be promoted to an actual api.
And if it's specific to kubeadm, which it appears to be (?), then it shouldn't be in the general go client.
Also I'm very nervous about a security-critical feature being non obviously buried here
```

The purpose of this issue is to find that home in the 1.12 cycle. 

/kind cleanup 
/cc @kubernetes/sig-cluster-lifecycle-misc @kubernetes/sig-api-machinery-misc

**Comment by yliaog** [comment]
https://github.com/kubernetes/client-go/issues/114 is the PR that put the bootstrap tokens under client-go, it seems there were some discussions about where to put them, and there were concerns raised about putting them under client-go.

The requirement is it needs to be accessible from under the following three directories:
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/pkg/controller/bootstrap
k8s.io/kubernetes/apiserver/plugin/pkg/authenticator/token/bootstrap

May I suggest to create another staging directory for them, something like:
staging/src/k8s.io/kubeadm/bootstrap/token/

**Comment by liggitt** [comment]
kubeadm uses the bootstrap token authentication mechanism, but it does not belong to kubeadm. in particular, k8s.io/kubernetes/apiserver will not have kubeadm as a dependency.

of those locations, I would probably move them under `k8s.io/kubernetes/apiserver/plugin/pkg/authenticator/token`

**Comment by lavalamp** [comment]
Clients shouldn't need to depend on apiserver.

Can we just make a k8s.io/bootstrap repo? What about putting something the
kubernetes-sigs org? `kubernetes-sigs/bootstrap-auth`?

**Comment by luxas** [comment]
@lavalamp `k8s.io/bootstrap` SGTM. I think it needs to be in the "core" organization as stuff in core will depend on it (e.g. the apiserver)

**Comment by sttts** [comment]
k8s.io/bootstrap or k8s.io/bootstrap-auth both sound fine, maybe the later. Do we expect non-auth content?

**Comment by luxas** [comment]
@sttts the bootstrap tokens are used for both JWS validation and auth.

**Comment by luxas** [comment]
> @luxas sounds good. I guess the code will depend on k8s.io/apimachinery+code-generator and we will depend on it in kube? This means it must become a staging repo.

Yep, I think that is the best option we have here.

> How about creating a PR moving the code into staging/src/k8s.io/bootstrap?

:+1:
@liztio will look into this and help out as well. Right now she's OOO AFAIK, though.
We'll discuss the exact implementation plans we have in SIG Cluster Lifecycle and (hopefully) be able
to create a short proposal for how to proceed in more detail.
/assign @liztio

**Comment by yliaog** [comment]
staging/src/k8s.io/bootstrap looks good.

**Comment by luxas** [comment]
@yliaog do you want to help with this? I can guide you how to get started and we'll do this teamwork everyone together :smile:?

**Comment by yliaog** [comment]
Sure, I can help work on it.

**Comment by cblecker** [comment]
When you're ready for the new repo to be created, you can submit a request here:
https://github.com/kubernetes/org/issues/new?template=repo-create.md

**Comment by guineveresaenger** [comment]
@timothysc in order for this to qualify for 1.12 release, it and all related PRs need the label `priority/critical-urgent`. Can you consider and triage?

**Comment by yliaog** [comment]
@timothysc @luxas could you help add the label  priority/critical-urgent to the PR (https://github.com/kubernetes/kubernetes/pull/67356), so it can merge?

**Comment by liggitt** [comment]
Why is it critical? What is broken or blocked if it merges at the beginning of 1.13 instead of now?

**Comment by guineveresaenger** [comment]
@lavalamp, @liggit - since it's currently code freeze, I'm suggesting holding off until master reopens in a couple weeks. I know it's frustrating. :(

**Comment by guineveresaenger** [comment]
Actually: it looks like the PR is ready and only missing critical/urgent label. Again, since _technically_ it's not urgent, I leave the decision up to you.

**Comment by dims** [comment]
/milestone clear

(to match the fact that the PR was moved out of 1.12)
