### ISSUE TITLE
pluginwatcher there is no de-register method

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#64637]
Right now the driver registration only registers drivers, not clear how to de-register a driver when the driver is terminated.

**Comment by saad-ali** [comment]
If a plugin is removed, we have no way to deregister it. If a plugin is uninstalled, should the kubelet be alerted so it can do some cleanup? Probably not a blocker for 1.11, but let's think about it.

CC @jiayingz @vikaschoudhary16 @vishh @vladimirvivien @sbezverk @RenaudWasTaken

**Comment by vikaschoudhary16** [comment]
@saad-ali we discussed it already in the first meeting. If plugin uninstalls, grpc will pick that up and kubelet component can unregister it. later when the plugin will reapear, watcher will pick it up and send a register request to kubelet component.
/cc @jiayingz

**Comment by RenaudWasTaken** [comment]
I've added a few comments to make this more explicit in PR#64621

**Comment by sbezverk** [comment]
@vikaschoudhary16 how pluginswatcher informs in-tree part of driver that the socket is gone and the driver needs to be de-registered?

**Comment by RenaudWasTaken** [comment]
[From @saad-ali:](https://github.com/kubernetes/kubernetes/pull/64660#issuecomment-398941617)
> > Unregistration is expected to be handled by the consumers using gRPC (i.e:when the connection closes).

> gRPC connection close does not (and should not) signal plugin uninstallation/unregsitration. The CSI implementation, for example, closes the connection after every operation. Connection could also drop for a number of reasons.

> So we do need to think about the socket deletion case (as a signal of plugin uninstallation), but I agree that does not need to be addressed in this PR. Please open another issue to track that and we can handle that separately.


> Connection could also drop for a number of reasons.

The connection here is on a unix socket backed by the gRPC retry mechanism. At least in the device plugin case it is usually pretty safe to adequate a gRPC close to an un-registration.

Though I do agree that removing the socket is a more explicit and consistent signal for un-registration. And we could also consider gRPC connection closing as a crashed / unhealthy device plugin.

That would allow to have a saner model that clearly makes the distinction between crash and unregistered. And thus have different behavior.

**Comment by vikaschoudhary16** [comment]
Will it be ok to assume that socket removal is always done by plugin intentionally and is not result of some unexpected action?

**Comment by saad-ali** [comment]
For CSI we intend to have two sockets, one that is used for registering and a second one to actually talk to the driver. As part of the registration process the path of the second socket is returned to Kubelet. After initial registration handshake the connection to the first socket is closed. Then for each operation kubelet opens a connection to the second CSI socket and closes it after that operation is complete. So the state of the socket (open or closed) is not a good signal for either "registration status" of plugin for CSI or for "plugin health". The existence of the socket would be a much better signal, so I support adding logic to monitor for socket removal and use that to trigger a "unregistration" callback.

> Will it be ok to assume that socket removal is always done by plugin intentionally and is not result of some unexpected action? But agree that it is more explicit than gRPC disconnection.

Yes, that makes sense to me.

**Comment by RenaudWasTaken** [comment]
I believe this was fixed by kubernetes/pull/64621

**Comment by vladimirvivien** [comment]
So this was implemented.  Should this be closed?

**Comment by RenaudWasTaken** [comment]
/close 
Is this the right command?
