### ISSUE TITLE
In-Tree Storage Plugin to CSI Migration Framework

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#64635]
/kind feature
/sig storage
/assign
/cc @saad-ali @jsafrane 

See design: https://github.com/kubernetes/community/pull/2199
[TODO: Update to actual file when PR Merged]

This issue is to track work being done on the migration.

**Comment by ddebroy** [comment]
tracked through https://github.com/kubernetes/enhancements/issues/625

**Comment by dims** [comment]
/close

since we have a KEP to track this
