### ISSUE TITLE
Cloudprovider interface needs more consistency and encapsulation

### ISSUE THREAD

**Issue by mikeorzel2** [kubernetes/kubernetes#6464]
Hi Kubernetes Team,

I am looking to contribute to the kubernetes project and want to start with cleaning up the cloudprovider interface and implementations to make them more consistent (functions in interface order, commented correctly), clean up some usage of the cloud provider interfaces (gce volumes calling functions directly on the gce cloud provider) as well as generalise the interface to the cloud volume providers. The goal here is to make the code more readable and maintainable into the future.

My plan is to do this in a number of stages (2 pull requests) covering the interface cleanup as well as the generalisation and cleanup of the gce volume interface.

Is this something the project is interested in and is the approach above a reasonable one? It may involve moving the code around in terms of order which wont necessarily be git friendly.

Happy to hear your thoughts and views on this and looking forward to helping out on such a great project.

**Comment by thockin** [comment]
In general cleanup is great.  Please differentiate cleanups from
generalizations, though.  I acknowledge that cloud-provider is not the
nicest interface right now :)

**Comment by bgrant0607** [comment]
Closing in favor of #2770
