### ISSUE TITLE
need a multi-arch kube-proxy image to allow a single daemonset to support multiple-arch nodes

### ISSUE THREAD

**Issue by paulbsch** [kubernetes/kubernetes#64647]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
After joining a new ppc64le node to the k8s cluster, the kube-proxy DaemonSet fails on the new node.  

**What you expected to happen**:
It was expected that the kube-proxy DS would "just work" as it does when adding an amd64 node to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Set up an amd64 based k8s cluster, then join a ppc64le node (or any non-amd64 arch) to the cluster.  See the pod fail via 'kubectl -n kube-system get pods' because it's pulling the amd64 kube-proxy docker image instead of the ppc64le image.

**Anything else we need to know?**:
The yaml for the DaemonSet specifies the image: gcr.io/google_containers/kube-proxy-amd64:<version>
It would be preferable to have a manifest so that the image in the DS could be specified as gcr.io/google_containers/kube-proxy:<version> and could "just work" on any platform.

See: https://github.com/estesp/manifest-tool

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.10.3

- Cloud provider or hardware configuration:
self - cluster installed via kubeadm

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
N/A
- Install tools:
N/A
- Others:
N/A

**Comment by liggitt** [comment]
daemonsets can specify a node selector to limit their arch-specific image to run on matching nodes

**Comment by paulbsch** [comment]
I am well aware that a node selector can be used.  That is what we are doing now.  But it is a hack.  The default should "just work".

Adding a new non-amd64 node should not result in kube-proxy immediately failing on it because the default daemon set is amd64 arch specific.  If kube-proxy is meant to "just work" clusterwide, a node selector should not be needed.  Please use the manifest-tool so that the default "just works".

Please see the weave-net plugin.  They are using the manifest-tool and it "just works" on amd64 and ppc64le.  Their daemon set does not require/use a nodeSelector.

**Comment by paulbsch** [comment]
The current kube-proxy daemon set  implementation is not properly architected, IMHO.  Please re-open this @kubernetes/sig-architecture-bugs

**Comment by liggitt** [comment]
ah, this was a comment about the kube-proxy image, not the daemonset functionality
/reopen

**Comment by liggitt** [comment]
the kube-proxy addon daemonset is probably @kubernetes/sig-cluster-lifecycle-feature-requests 

the multi-arch kube-proxy image to support that daemonset might be @kubernetes/sig-release-feature-requests

**Comment by dims** [comment]
Looks like it's coming from here:

https://github.com/dims/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L75

/assign @luxas 
/sig cluster-lifecycle

Lucas,
Do we want to avoid the `{{ .Arch }}` references?

**Comment by dixudx** [comment]
@paulbsch A dirty workaround for this is to pull `gcr.io/google_containers/kube-proxy-ppc64le:v1.10.3` and rename to `gcr.io/google_containers/kube-proxy-amd64:v1.10.3`.

The kube-proxy is running as daemonset, created during `kubeadm init`. That means the kube-proxy image arch keeps consistent with your master node. Currently we don't have a multi-arch kube-proxy image yet. We have to explicitly specify the right name, like `gcr.io/google_containers/kube-proxy-ppc64le`.

**Comment by paulbsch** [comment]
Hi @dixudx ..  Yes, that is what we are doing now.  But it's a bit of a hack.  That is why I opened this ticket looking for a multi-arch image.  Thanks!

**Comment by bgrant0607** [comment]
I don't know that mixed-ISA clusters are supported.

cc @kubernetes/sig-scheduling-feature-requests

**Comment by k82cn** [comment]
The requirement is: only use "gcr.io/google_containers/kube-proxy" in DaemonSet yaml file, and the kubelet will download the correct image according to the ARCH info. It's more about image registry's feature; and it seems some registries had supported that: https://github.com/estesp/manifest-tool#known-supporting-registries .

**Comment by dixudx** [comment]
@k82cn Yeah, gcr.io has already supported multi-arch. But actually all the images now are architecture specific, like `hyperkube-amd64` and `hyperkube-ppc64le`. We've not built any multi-arch images right now.

**Comment by mkumatag** [comment]
I have pending PR in releases project for creating manifest for those - https://github.com/kubernetes/release/pull/516

**Comment by detiber** [comment]
@luxas The manifest images created in kubernetes/release#516 should work for future released versions, but will they be created during CI testing?

**Comment by dims** [comment]
@detiber if you see one of the jobs that pushes images say https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-cross-build/6899/build-log.txt

you can grep for `push-build.sh::release::docker::release()` that's basically from the same files that got changed in https://github.com/kubernetes/release/pull/516 so i fully expect the images pushed to CI will reflect the changes made in 516.

**Comment by dims** [comment]
@mkumatag please confirm that i am reading this right ^ :)

**Comment by luxas** [comment]
@detiber please open an issue about pushing manifests in CI as well
