### ISSUE TITLE
[Feature Request] Pod can be scheduled with specified scheduler extenders instead of all.

### ISSUE THREAD

**Issue by houz42** [kubernetes/kubernetes#64667]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig scheduling

**What happened**:

Currently, if scheduler extenders are declared in scheduler policy config file, all extenders will be invoked for all pods when scheduling, which may be not necessary all the time.

When I needed a subset of my pods be scheduled with default polices and my own policy, while others be not, I had to add my filter and prioritize code into internal scheduler and run it along size with the internal one, and specified `spec.schedulerName: my-scheduler` in the pods' yaml file.
But this approach failed when we migrate to a new cluster with a higher version. As api changed for some fields in the pod specification, but my scheduler was written based on older code. I have to update my scheduler. And I am worried about if I have to rewrite the same code every time we upgrade to a newer cluster.

Scheduler extender seems like a better approach facing cluster upgrading, but pods can not be specified for particular extender(s), which makes this approach unusable for me right now.

**What you expected to happen**:

1. Assign a unique name for a user implemented scheduler extender, 
along with a property `invokePolicy: [Always|WhenSpecified]` in scheduler policy config file.
Older extenders or ones missed this property could be considered `invokePolicy == Always` 
to be compatible with current behaviors
1. Add a field of list in pod yaml file: `spec.schedulerExtenders: [my-extender-a, my-extender-b]`
2. During scheduling, following extenders will be considered for a pod:
    1. extender with `invokePolicy == Always`
    2. extender with `invokePolicy == WhenSpecified` && its name is in pod's spec.schedulerExtenders

**Anything else we need to know?**:

This feature may conflict with https://github.com/kubernetes/kubernetes/pull/61445, pod specified extenders should be always invoked **for this pod**. It is better to set the pod pendingScheduling if specified extender is unavailable, while other pods could be still scheduled because they do not need it.

**Comment by houz42** [comment]
@resouer, @ravisantoshgudimetla  can you kindly review this request and tell if it is doable. And if it does, I want to try it. But I am not sure if I am capable for this,  I have not dived deep enough into the internal scheduler code.

**Comment by houz42** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment]
@houz42 One thing I am not clear is, why don't use default scheduler + one scheduler extender? You have many extenders for different pods to use?

**Comment by houz42** [comment]
@resouer 
> You have many extenders for different pods to use?

No, only one.

> why don't use default scheduler + one scheduler extender?

Only a subset of my pods need to be scheduled by this extender, others need not.

**Comment by resouer** [comment]
If the request is about: allow pod to choose specific extender by name, it is a valid request. 

Actually I recalled discussed this with someone on some existing issue ...

**Comment by houz42** [comment]
> If the request is about: allow pod to choose specific extender by name, it is a valid request.

Yes, that's what I mean. 

By the way, can you tell if there is too much work to do , or maybe, less than 200 lines of code.

**Comment by wgliang** [comment]
@resouer 
Yes, maybe this issue related #59555 I had submit.

**Comment by houz42** [comment]
@k82cn 
Resource type of GPU in pod specification has changed from `alpha.kubernetes.io/nvidia-gpu` to `nvidia.com/gpu` on 1.8. Our old scheduler is written based on 1.7. When we deploy all our apps and jobs on a new cluster running 1.9, we have updated our pod specs (`alpha.kubernetes.io/nvidia-gpu` to `nvidia.com/gpu`), but forgotten to update our scheduler at the first time. Our scheduler could not find `alpha.kubernetes.io/nvidia-gpu`, and scheduled pods requesting GPU to CPU nodes.

**Comment by houz42** [comment]
@k82cn 
Resource type of GPU in pod specification has changed from `alpha.kubernetes.io/nvidia-gpu` to `nvidia.com/gpu` on 1.8. Our old scheduler is written based on 1.7. When we deploy all our apps and jobs on a new cluster running 1.9, we have updated our pod specs (`alpha.kubernetes.io/nvidia-gpu` to `nvidia.com/gpu`), but forgotten to update our scheduler at the first time. Our scheduler could not find `alpha.kubernetes.io/nvidia-gpu`, and scheduled pods requesting GPU to CPU nodes.

**Comment by k82cn** [comment]
@houz42 , if the customized extender/scheduler uses `gpu` info, it still need to update :) In default scheduler, it's handled by a general scalar resource; that may not enough for some case.

**Comment by houz42** [comment]
@k82cn yes, my extender would need to update, or it may return wrong priority score. But at least, pods requesting gpu would never been scheduled to a machine without gpu, cause these nodes would be filtered out before my extender been called.

**Comment by k82cn** [comment]
> Scheduler extender seems like a better approach facing cluster upgrading, 

@houz42 , if my understanding is right, you expect http extender can reduce such kind of "compatibility" issue; but I think the issue is still here if you use `gpu` (or such kind of resource) in your customized scheduler/extender :) I'm not sure the complexity of your scheduler, and the effort changing from a customized scheduler to extender.

And a kindly reminder, we did not provide version control for HTTP extender :)

**Comment by houz42** [comment]
> and the effort changing from a customized scheduler to extender.

@k82cn, you are right. I propose this request as extender is much smaller than a scheduler and easier to debug or upgrade. I am prefer to maintain a custom extender rather than a scheduler if I have to.

**Comment by k82cn** [comment]
That makes sense to me, thanks :)

**Comment by resouer** [comment]
@houz42 One thing I want to add is, the current scheduler extender has a `IsInterested()` interface. Do you think it's enough to solve your problem? e.g. you can basically use labels or annotations to choose what extender to match.

**Comment by chenchun** [comment]
> you can basically use labels or annotations to choose what extender to match.

It's been replaced by configuring interested resource instead of labels or annotations.
See the discussion in https://github.com/kubernetes/kubernetes/pull/58851.
I think this issue can be closed.

**Comment by houz42** [comment]
@chenchun, thank you, it sounds good for my case. And sorry for the late reply.

**Comment by houz42** [comment]
@resouer, it sounds good, i will try it and another approach proposed by @chenchun. Than you
