### ISSUE TITLE
Kubernetes not terminating old pods in deployment

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubernetes#64689]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

It seems a deployment has gotten stuck. How can I diagnose this further? 

    kubectl rollout status deployment/wordpress
    Waiting for rollout to finish: 2 out of 3 new replicas have been updated...

It's stuck on that for ages already. It is not terminating the two older pods: 

    kubectl get pods                   
    NAME                         READY     STATUS    RESTARTS   AGE
    nfs-server-r6g6w             1/1       Running   0          2h
    redis-679c597dd-67rgw        1/1       Running   0          2h
    wordpress-64c944d9bd-dvnwh   4/4       Running   3          3h
    wordpress-64c944d9bd-vmrdd   4/4       Running   3          3h
    wordpress-f59c459fd-qkfrt    0/4       Pending   0          22m
    wordpress-f59c459fd-w8c65    0/4       Pending   0          22m
And the events:

    kubectl get events --all-namespaces
    NAMESPACE   LAST SEEN   FIRST SEEN   COUNT     NAME                                          KIND         SUBOBJECT   TYPE      REASON              SOURCE                    MESSAGE
    default     25m         2h           333       wordpress-686ccd47b4-4pbfk.153408cdba627f50   Pod                      Warning   FailedScheduling    default-scheduler         No nodes are available that match all of the predicates: Insufficient cpu (1), Insufficient memory (2), MatchInterPodAffinity (1).
    default     25m         2h           337       wordpress-686ccd47b4-vv9dk.153408cc8661c49d   Pod                      Warning   FailedScheduling    default-scheduler         No nodes are available that match all of the predicates: Insufficient cpu (1), Insufficient memory (2), MatchInterPodAffinity (1).
    default     22m         22m          1         wordpress-686ccd47b4.15340e5036ef7d1c         ReplicaSet               Normal    SuccessfulDelete    replicaset-controller     Deleted pod: wordpress-686ccd47b4-4pbfk
    default     22m         22m          1         wordpress-686ccd47b4.15340e5036f2fec1         ReplicaSet               Normal    SuccessfulDelete    replicaset-controller     Deleted pod: wordpress-686ccd47b4-vv9dk
    default     2m          22m          72        wordpress-f59c459fd-qkfrt.15340e503bd4988c    Pod                      Warning   FailedScheduling    default-scheduler         No nodes are available that match all of the predicates: Insufficient cpu (1), Insufficient memory (2), MatchInterPodAffinity (1).
    default     2m          22m          72        wordpress-f59c459fd-w8c65.15340e50399a8a5a    Pod                      Warning   FailedScheduling    default-scheduler         No nodes are available that match all of the predicates: Insufficient cpu (1), Insufficient memory (2), MatchInterPodAffinity (1).
    default     22m         22m          1         wordpress-f59c459fd.15340e5039d6c622          ReplicaSet               Normal    SuccessfulCreate    replicaset-controller     Created pod: wordpress-f59c459fd-w8c65
    default     22m         22m          1         wordpress-f59c459fd.15340e503bf844db          ReplicaSet               Normal    SuccessfulCreate    replicaset-controller     Created pod: wordpress-f59c459fd-qkfrt
    default     3m          23h          177       wordpress.1533c22c7bf657bd                    Ingress                  Normal    Service             loadbalancer-controller   no user specified default backend, using system default
    default     22m         22m          1         wordpress.15340e50356eaa6a                    Deployment               Normal    ScalingReplicaSet   deployment-controller     Scaled down replica set wordpress-686ccd47b4 to 0
    default     22m         22m          1         wordpress.15340e5037c04da6                    Deployment               Normal    ScalingReplicaSet   deployment-controller     Scaled up replica set wordpress-f59c459fd to 2

----------

   

The newer pods are not being scheduled and there is insufficient memory for them.

**Environment**:
- Cloud provider or hardware configuration: Google Cloud

**Comment by chrissound** [comment]
Figured it out. It's because I set the replica count to high. It seems it terminate the old pods unless all the new pods (replicas) will be able to fit. 

I don't think this behavior is desirable, surely it should just deploy as many new pods as it can?

**Comment by kow3ns** [comment]
You can control the behavior by setting replicas, maxSurge, and minUnavaiable appropriately. 
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
/close

**Comment by imsrgadich** [comment]
@chrissound Hi, what is the solution for this issue?

And also, what do you mean by `able to fit`?

> Figured it out. It's because I set the replica count to high. It seems it terminate the old pods unless all the new pods (replicas) will be able to fit.

**Comment by komoo1** [comment]
"able to fit" implies that if you set number of replicas as 5 and only 3 replicas are achievable, then the deployment should proceed. Also, see @kow3ns comment above
