### ISSUE TITLE
Need to clear the sandbox if it fails to create

### ISSUE THREAD

**Issue by DeliangFan** [kubernetes/kubernetes#64699]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:

Create a Pod, if ds.client.CreateContainer returns error(such as "runContainer: operation timeout: context deadline exceeded") during SyncPod, the network will not be setup while the sandbox remains success in docker. As a result, during the next SyncPod, the because the sandbox pod is created, the network will never be setup.  

**What you expected to happen**:

The pod network should be setup finally.

**How to reproduce it (as minimally and precisely as possible)**:

Docker return “operation timeout: context deadline exceeded” when create sandbox container while the container remain success.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

local kvm machine

- OS (e.g. from /etc/os-release):

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
```

- Kernel (e.g. `uname -a`):

```
Linux centos-linux-7.shared 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:

**Comment by DeliangFan** [comment]
Close this please

**Comment by goatmale** [comment]
> Close this please

Can you please share your resolution?
