### ISSUE TITLE
limitrange api can not work with  decimal

### ISSUE THREAD

**Issue by loveai88** [kubernetes/kubernetes#64694]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I want to set default memory limit in a namespace,and I use the api like this 
`http://localhost:8080/api/v1/namespaces/default/limitranges`
with
```
{
	"apiVersion":"v1",
	"kind":"LimitRange",
	"spec":{
		"limits":[
			{
				"default":{"memory":"2.0Gi"},
				"defaultRequest":{"memory":"0.6Gi"},
				"type":"Container"
			}
				]
	}
}
```

However it return the value like this
```
{
    "kind": "LimitRange",
    "apiVersion": "v1",
    "metadata": {
        "name": "dc845b1f-67ef-11e8-90c9-000c2932c1fe",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/limitranges/dc845b1f-67ef-11e8-90c9-000c2932c1fe",
        "uid": "dc845b7d-67ef-11e8-90c9-000c2932c1fe",
        "resourceVersion": "9557261",
        "creationTimestamp": "2018-06-04T12:07:32Z"
    },
    "spec": {
        "limits": [
            {
                "type": "Container",
                "default": {
                    "memory": "2Gi"
                },
                "defaultRequest": {
                    "memory": "644245094400m"
                }
            }
        ]
    }
}
```

the value of defaultRequest memory is not 0.6Gi.

I try some different value 0.3Gi,0.8Gi,1.1Gi,1.5Gi,only 0.5Gi and 1.5Gi work well.
```
{
    "kind": "LimitRange",
    "apiVersion": "v1",
    "metadata": {
        "name": "8f0e28f9-67f0-11e8-90c9-000c2932c1fe",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/limitranges/8f0e28f9-67f0-11e8-90c9-000c2932c1fe",
        "uid": "8f0e2958-67f0-11e8-90c9-000c2932c1fe",
        "resourceVersion": "9557896",
        "creationTimestamp": "2018-06-04T12:12:32Z"
    },
    "spec": {
        "limits": [
            {
                "type": "Container",
                "default": {
                    "memory": "2Gi"
                },
                "defaultRequest": {
                    "memory": "512Mi"
                }
            }
        ]
    }
}
```

**What you expected to happen**:
it works well with any value.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (1.8.5):
- Cloud provider or hardware configuration:
- OS (centos7):
- Kernel (3.10.0-514.el7.x86_64):
- Install tools:
- Others:

**Comment by essamhassan** [comment]
@loveai88 just to make sure I understood this correctly. 

I can see `"defaultRequest":{"memory":"0.6Gi"},` failed to parse 0.6 to 600mi is that correct?

**Comment by loveai88** [comment]
@essamhassan yes,`0.5Gi` can parse to `512Mi `,why `0.6Gi` not parse to `614Mi` ,and what is `644245094400m ` means?

**Comment by yue9944882** [comment]
`m` means the quantity is shown with the scale of `10^-3` for a minimum precision loss. So `644245094400m ` is the same as `644245094400 * 10^-3`. I agree that it looks weird THO, but current expression is not arithmetically wrong.

**Comment by loveai88** [comment]
so the 644245094400m use byte unit?
