### ISSUE TITLE
Success to pull docker imge using docker pull command but still getting error in kubectl describe - rpc error: code = Unknown desc = Error response from daemon:

### ISSUE THREAD

**Issue by tutaidalal** [kubernetes/kubernetes#64702]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tutaidalal** [comment]
I have a private docker hub and from there I am able to pull docker image using docker pull command. But when I am using helm chart and starting the pod its showing the below error - 


Events:
  Type     Reason                 Age                From                     Message
  ----     ------                 ----               ----                     -------
  Normal   Scheduled              1m                 default-scheduler        Successfully assigned patsexecutor-56bf85dfb-k9929 to k8s-worker-166
  Normal   SuccessfulMountVolume  1m                 kubelet, k8s-worker-166  MountVolume.SetUp succeeded for volume "patsjobs"
  Normal   SuccessfulMountVolume  1m                 kubelet, k8s-worker-166  MountVolume.SetUp succeeded for volume "default-token-5kbcv"
  Normal   SandboxChanged         48s (x4 over 55s)  kubelet, k8s-worker-166  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                 42s (x2 over 56s)  kubelet, k8s-worker-166  Failed to pull image "patsexecutor": rpc error: code = Unknown desc = Error response from daemon: repository patsexecutor not found: does not exist or no pull access
  Warning  Failed                 42s (x2 over 56s)  kubelet, k8s-worker-166  Error: ErrImagePull
  Normal   BackOff                27s (x6 over 54s)  kubelet, k8s-worker-166  Back-off pulling image "patsexecutor"
  Warning  Failed                 27s (x6 over 54s)  kubelet, k8s-worker-166  Error: ImagePullBackOff
  Normal   Pulling                14s (x3 over 59s)  kubelet, k8s-worker-166  pulling image "patsexecutor"

**Comment by tutaidalal** [comment]
Specially could not identify the meaning of - "rpc error: code = Unknown desc"

**Comment by dims** [comment]
/sig node

is there any clue in the docker daemon logs?

**Comment by tutaidalal** [comment]
issue resolved .. there was an issue in registry .. After configuring the global registry properly it is running

**Comment by priya2511** [comment]
I am facing the same issue in Openshift online. Could you please explain how did you resolve this ?
