### ISSUE TITLE
pluginswatcher validation of returned driver endpoint

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#64710]
During the registration process, CSI registration side car returns the endpoint of CSI driver. PluginsWatcher should validate passed the endpoint and fail the registration if the endpoint points to a non-existing path.
/kind bug
/sig storage

**Comment by saad-ali** [comment]
CC @jiayingz @vikaschoudhary16 @vishh @vladimirvivien @sbezverk @RenaudWasTaken

**Comment by vikaschoudhary16** [comment]
Not every watcher consumer will expect this additional endpoint to be non-empty. Validation should happen at CSI component, IMO. For example, for device plugins, empty endpoint is not an issue.
