### ISSUE TITLE
Node shutdown & deployment with replicas

### ISSUE THREAD

**Issue by vishiy** [kubernetes/kubernetes#64720]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
We have a deployment with replicas: 1
We deploy it in a 3 agent node K8S cluster (k8s 1.8.13) and it gets deployed to a node (say agent node-0). When I shutdown node-0, the rs does not get rescheduled (its been more than an hour now).
I have checked that the selector labels are correct and we have plenty of capacity in the cluster (and also we don’t specify resource requests). Also I checked that our node selectors are just checking for agent nodes and there are 2 other agent nodes available.
Is there any special treatments around this shutdown scenario that k8s does ?

**What you expected to happen**:
Replica-set rescheduled in another node when the node (node-0 in this case) goes down.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig Scheduling

**Comment by Huang-Wei** [comment]
Should be fixed by #56622. Could you try on 1.9+ cluster?
