### ISSUE TITLE
Remove rescheduler once scheduling DS pods by default scheduler moves to beta.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#64725]
/kind feature

Plan to remove rescheduler

For pods generated by DS controller, if we use default-scheduler for scheduling, since priority and preemption is going to beta in 1.11, we except the preemption to happen but as of now, the `scheduling DS pods by default scheduler` is still in alpha and we need to rely on rescheduler to make enough space for pods scheduled by DS controller. Once it moves to beta, we should remove rescheduler. 

xref: https://github.com/kubernetes/kubernetes/issues/57471

**Comment by Lion-Wei** [comment]
I think I can help if needed. 
/assign

**Comment by Lion-Wei** [comment]
Sure, thanks. Will be done soon.
