### ISSUE TITLE
Provide a way to enable etcdv3 client logging. 

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/kubernetes#64730]
/kind feature

Can we provide a way to enable etcd clientv3 logging at the apiserver side ? 
The etcd.clientv3 interface is instantiated [here](https://github.com/ahakanbaba/kubernetes/blob/4f1489edf0675718bb4a5ac754677e2450215d17/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L44) and it does not set a Logger. 

Without a logger object, etcd.clientv3 object discards the [logs](https://github.com/ahakanbaba/kubernetes/blob/4f1489edf0675718bb4a5ac754677e2450215d17/vendor/github.com/coreos/etcd/clientv3/client.go#L275)

It would be nice to have a command line argument, config/environment variable to enable logging in the etcd clientv3 interface. 

Could the glog functions be wrapped inside an object that implements the grpclog.Logger interface.

**Comment by ahakanbaba** [comment]
@kubernetes/sig-instrumentation-feature-requests

/sig Instrumentation

Adding instrumentation SIG because the descriptions says

> 
Covers best practices for cluster observability through metrics, logging, and events across all Kubernetes components

**Comment by ahakanbaba** [comment]
Since this is regarding the API server, maybe the API machinery SIG is also relevant. I do not know about the etiquette about adding multiple SIGs to an issue. Please add them is you think is appropriate.

**Comment by dims** [comment]
@ahakanbaba this patch seems to work against master - http://paste.openstack.org/show/722687/ - want to play with it and propose a PR?

**Comment by hzxuzhonghu** [comment]
I can do that.

**Comment by jingyih** [comment]
This issue is obsolete. By default, etcd client now enables logging:
https://github.com/etcd-io/etcd/blob/facd0c946025f07ed8c1ba7d2bb2d80baa17c194/clientv3/client.go#L433-L438
