### ISSUE TITLE
API proposal for subject locator

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#64734]
/kind feature
I noticed  that currently we lacks a way to locate subject, for example, a admin want to know who can perform pod deletion in namespace "default". Currently it may be a little difficult to achieve this , since the admin must get all the clusterrolebinding/clusterrole, rolebinding/rolebinding in namespace default and then traverse by some sort of hand-writing script.
I think we need some kind of API to list subjects who have the power to perform specific actions. Patch https://github.com/kubernetes/kubernetes/pull/35300 has completed part of this goal.

**Comment by liggitt** [comment]
This is the ResourceAccessReview API proposed in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/enhance-pluggable-policy.md#resourceaccessreview, but not yet implemented. 

Implementing such an API on top of multiple authorizers, especially when those authorizers are combined with earlier authorizers denying preemptively, raises some interesting questions about precedence, similar to those raised in #53922

**Comment by liggitt** [comment]
> since the admin must get all the clusterrolebinding/clusterrole, rolebinding/rolebinding in namespace default and then traverse by some sort of hand-writing script

We would want this as a general authorization API, like subjectaccessreview, not an RBAC-specific API

**Comment by WanLinghao** [comment]
Currently, the union authorizer process authorizer chain like this:
When it hits a DecisionNoOpion, it just continues to next authorizer
When it hits a DecisionDeny, it forbid this request directly without querying next authorizer.
When it hits a DecisionAllow, it allow this request directly without querying next authorizer.
Base on this behaviours, I think it implies a priority: The front authorizer has a higher priority than the latter one.
So, maybe we can do like this:
Each authorizer implements a LocateSubject function which returns tow lists: Black Users and White Users. Black list means the users the authorizer would deny, White list means the users the authorizer would allow.  A union locator would handle these lists the same way as union authorizer. The front authorizer's result would cover latter one. Since the union locator shares the same sequence of authorizers with union authorizer,   we can guarantee the result is correct.
WDYT @liggitt

**Comment by liggitt** [comment]
> Each authorizer implements a LocateSubject function which returns tow lists: Black Users and White Users. Black list means the users the authorizer would deny, White list means the users the authorizer would allow.

How would you express "deny all users except `user1`"?

**Comment by WanLinghao** [comment]
I think it equals:  we treat some users as special case and treat other users as default case.
So maybe we can do like this, the list contains  allowList, denyList, noOpinionList and a default behavior.
For your example,  the result would be:
allowList: []
denyList: [user1]
noOpinionList: []
default: noOpinion

**Comment by WanLinghao** [comment]
@liggitt  friendly ping
