### ISSUE TITLE
Provide a way to enable etcdv3 client prometheus metics

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/kubernetes#64740]
/kind feature

Can we provide a way to enable etcd clientv3 prometheus metrics at the apiserver side ?
The etcd.clientv3 interface is instantiated [here](https://github.com/ahakanbaba/kubernetes/blob/4f1489edf0675718bb4a5ac754677e2450215d17/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L44) and it does not enable metrics. 

In example_metrics_test.go file in coreos/etcd, one can see the [options](https://github.com/coreos/etcd/blob/438e6750ee4dd3861c83514e405adf2f3e437e4c/clientv3/example_metrics_test.go#L36) to pass to enable metrics. 

It would be great if the apiserver has a command line parameter, config/environment variable to enable etcd.clientv3 metrics.

**Comment by ahakanbaba** [comment]
@kubernetes/sig-instrumentation-feature-requests

**Comment by ahakanbaba** [comment]
This issue is quite similar to #64730

**Comment by brancz** [comment]
Yes, this is a good idea, in fact we just released a new version of the [grpc-go-prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus/releases/tag/v1.2.0) package required for this.

**Comment by wgliang** [comment]
I can do it.

**Comment by wgliang** [comment]
oh, maybe I should use the new features to implement, I will continue to modify it.

**Comment by brancz** [comment]
@wgliang are you referring to injecting the registry to use? Yes I would very much appreciate that, even if we (for now) inject the `prometheus.DefaultRegisterer`, that will allow us to modify that more easily in the future.
