### ISSUE TITLE
Azure Resource Manager limits hit when creating LB services with 1.10.3

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#64759]
/kind bug
/sig azure

**What happened**:
I have upgraded a small 15 node cluster from version 1.9.7 to 1.10.3 that runs ~50 pods and 4 services of type `LoadBalancer`. The upgrade went smooth. When creating a new service of type `LoadBalancer` then the new LB is pending and is not getting created because the ARM limits are hit:
```
I0605 06:12:18.805985       1 service_controller.go:300] Ensuring LB for service default/test-lb-svc
I0605 06:12:18.806074       1 azure_loadbalancer.go:444] reconcileLoadBalancer(default/test-lb-svc) - wantLb(false): started
E0605 06:12:18.806097       1 azure_backoff.go:176] LoadBalancerClient.List(my-resource-group) - backoff: failure, will retry,err=azure - ARM rate limited(read) for operation:LBList
E0605 06:12:18.806127       1 service_controller.go:219] error processing service default/test-lb-svc (will retry): failed to ensure load balancer for service default/test-lb-svc: azure - ARM rate limited(read) for operation:LBList
I0605 06:12:18.806179       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"test-lb-svc", UID:"5022906c-4f22-11e8-9741-0a580a3006f6", APIVersion:"v1", ResourceVersion:"7709447", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): failed to ensure load balancer for service default/test-lb-svc: azure - ARM rate limited(read) for operation:LBList
I0605 06:12:18.806287       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"test-lb-svc", UID:"5022906c-4f22-11e8-9741-0a580a3006f6", APIVersion:"v1", ResourceVersion:"7709447", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
E0605 06:12:18.807065       1 azure_backoff.go:176] LoadBalancerClient.List(my-resource-group) - backoff: failure, will retry,err=azure - ARM rate limited(read) for operation:LBList
E0605 06:12:18.807175       1 service_controller.go:219] error processing service default/kubernetes (will retry): error getting LB for service default/kubernetes: azure - ARM rate limited(read) for operation:LBList
```
The are other applications which do calls with the same user to the Azure API as well, but very less and very infrequently. The 15.000 reads/hour limit will definitely not be filled up by them.

**What you expected to happen**:
The ARM limits are not exceeded as the cluster is very small.

**How to reproduce it (as minimally and precisely as possible)**:
As describe above; create a cluster with version 1.9, create a few LB services, upgrade to 1.10.3 and create another LB service.

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CoreOS 1745.4.0

**Comment by rfranzke** [comment]
I did the following exercise: I tried creating a LB in the 1.10.3 cluster, it didn't work. Then I downgraded the cluster to 1.9.8, and after that the LB was immediately created.

After that I was trying the same in another cluster and another subscription, however, this cluster is 1.10.3 with 10 nodes and only 2 existing LBs. Creating a new LB failed as well due to ARM rate limit (in this subscription it is really impossible that they were hit, nothing happened there the last days/weeks). After downgrading this cluster as well to 1.9.8 the LB was immediately created.

Maybe the Azure client is doing something wrong with the rate limiting headers in 1.10?

PS: The kube-controller-manager runs outside the subscription it acts on.

**Comment by feiskyer** [comment]
> PS: The kube-controller-manager runs outside the subscription it acts on.

I suspect this is related to rate limiting, but need more dive to identify which limits are hit.

**Comment by khenidak** [comment]
version 1.10 strictly apply rate limiting (vs the old behavior which would queue your call until you go under limits). Admittedly the error message is wrong it says "Azure - arm " instead of "cloud provider -" 

The default values (if you used the defaults in acs-engine) are a too little/aggressive. A max of 10 requests refilled at 3 per sec. Increase that limit to bucket size of `100` filled at `10` per sec (in file `/etc/kubernetes/azure.json`). The exact values depends on how big your cluster and how many clusters in the same subscription. 

Also please note v1.10 implements separate Write QPS and bucket sizes. This to allow you to provide different values for read requests and write requests the flags are in the same file with the following names:
```
"cloudProviderRateLimitQPSWrite": nn
"cloudProviderRateLimitBucketWrite": nn
``` 

if you only have one cluster in this subscription then you can disable rate limiting all together by setting `cloudProviderRateLimit` to `false`

**Comment by feiskyer** [comment]
I think this issue could be closed now based on above comments https://github.com/kubernetes/kubernetes/issues/64759#issuecomment-395909117.

@rfranzke Feel free to reopen if there're still issue.

/close
