### ISSUE TITLE
Issue on downloading OS dependent etcd binary if etcd soft link points to non-relevant pre-existing binary 

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#64754]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
During k8s cluster launch, `etcd-v${ETCD_VERSION}-*` is checked and if any etcd binary is found regardless of current OS Distribution, expected etcd binary is not downloaded and etcd soft link is not updated to point desired etcd binary, so cluster creation fails.

**What you expected to happen**:
Along with expected etcd version, OS Distribution should also be checked for successfully and efficiently installing etcd during setting up local cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Checkout k8s codbase on MacOS and launch cluster.
2. map working k8s codebase under virtual machine to launch cluster in VM.
(Cluster creation would fail, prompting error that etcd needs to be installed and update in $PATH. "${KUBE_ROOT}/third_party/etcd-v${ETCD_VERSION}-darwin-* exists but failed to download etcd-v${ETCD_VERSION}-linux-*

**Anything else we need to know?**:
It's an optimization on managing third_party etcd binary for local cluster setup.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.759+4c13f5fdf5e638-dirty", GitCommit:"4c13f5fdf5e6387f128a1780fc635bb7ad8f99b5", GitTreeState:"dirty", BuildDate:"2018-06-04T08:38:38Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.759+4c13f5fdf5e638-dirty", GitCommit:"4c13f5fdf5e6387f128a1780fc635bb7ad8f99b5", GitTreeState:"dirty", BuildDate:"2018-06-04T08:38:38Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@mgdevstack do you have a patch that you are working on? we don't really support local-up-cluster on macos yet. 

/sig testing

**Comment by mgdevstack** [comment]
@dims, #64782 is fixing this issue. Though I use Mac as my workstation but sometimes need local-cluster to test codebase so I mapped (softlinked) my GOPATH in virtual machine keeping separate bin directory. Everything is running perfectly fine after making changes mentioned in this PR.

So thought to submit small optimization on etcd installation logic.
