### ISSUE TITLE
Feature request. Trigger pod deletion if CPU resource threshold reached/exceeded

### ISSUE THREAD

**Issue by JamesTGrant** [kubernetes/kubernetes#64753]
Is this a BUG REPORT or FEATURE REQUEST?:

    Uncomment only one, leave it on its own line:

/kind feature

I have CPU requests and limits. I'd like another setting: kill off pod if definedd  CPU limit is reached. This way, if an application goes awry and hits the CPU limit K8s can terminate the pod.
I don't mind if this is instantaneous or the threshold must be reached for a period (in my application, as soon as limit reached would be totally fine)
For example, in the YML snippit below, if CPU utilisation reaches 1500m then kill it!

        resources:
          limits:
            cpu: 1500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi

**Comment by yastij** [comment]
@dims - can you assign me on this ?
