### ISSUE TITLE
kubernet 1.10 kubeadm tools usage promber

### ISSUE THREAD

**Issue by kedizhou** [kubernetes/kubernetes#64762]
i use kubenetes 1.10 biray package,when i use （cause i thought specify image mirror address）:
kubeadm init --config init.yaml
block on stage with "init ........",my question is:
1.this stage is downing images?
2.kubeadm init kit will auto boot/start docker  kubenetns manage images?

**Comment by dims** [comment]
Can you please request this in the kubeadm repo? https://github.com/kubernetes/kubeadm/issues/

/close
