### ISSUE TITLE
kubernet 1.10 kubeadm tools usage promber

### ISSUE THREAD

**Issue by kedizhou** [kubernetes/kubernetes#64763]
i use kubenetes 1.10 binary package,when i use （cause i thought specify image mirror address）:
kubeadm init --config init.yaml
block on stage with 
"""
[init] This might take a minute or longer if the control plane images have to be pulled.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
"""

my question is:
1.this stage is downing images?
2.kubeadm init kit will auto boot/start docker  kubenetns manage images?

**Comment by dims** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/64762

/close
