### ISSUE TITLE
tests: Secrets related tests fail to create running pods

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#64765]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig testing

**What happened**:

The following tests fail to pass:

    Secrets should be consumable from pods in volume with mappings [NodeConformance] [Conformance]
    Projected should be consumable from pods in volume with mappings [NodeConformance] [Conformance]
    Secrets should be consumable from pods in volume with mappings and Item Mode set [NodeConformance] [Conformance]
    Projected should be consumable from pods in volume with mappings and Item Mode set [NodeConformance] [Conformance]

The projected tests above are projecting secrets.

Inspecting the created pod's events, it can be seen that the pod fails to spawn because a volume was not found [1]. The kubelet's logs show similar errors [2]. But inspecting the secrets in the test's namespace reveals the fact that the secret does exist.

These tests used to pass in the past. Additionally, these tests do not have this issue:

    ConfigMap should be consumable from pods in volume with mappings [NodeConformance] [Conformance]
    Projected should be consumable from pods in volume with mappings [NodeConformance] [Conformance]
    ConfigMap should be consumable from pods in volume with mappings and Item mode set [NodeConformance] [Conformance]
    Projected should be consumable from pods in volume with mappings and Item mode set [NodeConformance] [Conformance]

The projected tests above are projecting configmaps. Even though they share the same name, they are **not** the same tests.

The issue seems to be caused by the secret's item mapping itself:

    volumes:
    - name: projected-secret-volume
    projected:
        defaultMode: 420
        sources:
        - secret:
            items:
            - key: data-1
              path: new-path-data-1
            name: projected-secret-test-map-7126025d-6889-11e8-bce5-000c29738e2c

As it can be seen, the item key is "data-1", but inspecting the secret itself:

    Name:         projected-secret-test-map-7126025d-6889-11e8-bce5-000c29738e2c
    Namespace:    e2e-tests-projected-ghshw
    Labels:       <none>
    Annotations:  <none>

    Type:  Opaque

    Data
    ====
    DATA_3:  8 bytes
    DATA_1:  8 bytes
    DATA_2:  8 bytes

The secret's data is actually "DATA_1", and because of this mismatch, the volume fails to setup.

[1] https://paste.ubuntu.com/p/GZ33gmpSG8/
[2] https://paste.ubuntu.com/p/G46zrNvrkB/

**What you expected to happen**:

The tests to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run the mentioned e2e tests.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 
    - client: 1.9.3
    - server: 1.10.3
- OS (e.g. from /etc/os-release): Windows Server 2016 (version: 10.0.17134 N/A Build 17134)
- Install tools: N/A

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs
