### ISSUE TITLE
Kubelet does not start on Linux Kernel without SWAP Support

### ISSUE THREAD

**Issue by Deccoy** [kubernetes/kubernetes#64776]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**What happened:**

The following check at the startup of kubelet always fails if the Linux kernel is compiled without swap support (-> /proc/swaps does not exist).

(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go)
```
// Check whether swap is enabled. The Kubelet does not support running with swap enabled.
swapData, err := ioutil.ReadFile("/proc/swaps")
if err != nil {
	return nil, err
}
```
The following code change may be possible here:

```
// Check whether swap is enabled. The Kubelet does not support running with swap enabled.
swapData, err := ioutil.ReadFile("/proc/swaps")
if failSwapOn && err != nil {
	return nil, err
}
```

**Comment by dims** [comment]
Fixed in https://github.com/kubernetes/kubernetes/commit/32c265f60c175cedbd685f30e389c95fb1e66ee3 i believe

/close
