### ISSUE TITLE
Scheduling daemonset on busy cluster doesn't rebalance pods

### ISSUE THREAD

**Issue by jgrobbel** [kubernetes/kubernetes#64771]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

We have busy 4 node clusters which we deploy to many times a day. Of interest is that we run 3  Daemonsets which are infrequently updated. However when they are updated and redeployed I often see that the scheduler has filled the node with other pods, such that now the daemonset pod won't fit on this particular node. I have set resource requests so that there is enough headroom in the cluster to shift pods around.

**What you expected to happen**:

I expect the scheduler to evict some pods or do some rebalancing of the cluster so the deamonset can fit on all nodes. (enough capacity assumed)

**How to reproduce it (as minimally and precisely as possible)**:
Schedule a Daemonset that requests more memory than is available on one of the nodes.
Running "kubectl rollout status ds/${ds_set}" never succeeds.

**Anything else we need to know?**:
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
^^^ This appears to do what I want, but only applies to the kube-system namespace.

Manually killing a pod will rebalance the system (as a workaround)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.12
- Cloud provider or hardware configuration:  GKE
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`): 4.4.111+
- Install tools: gcloud
- Others:

**Comment by aveshagarwal** [comment]
@jgrobbel priority and preemption feature in 1.11 and "scheduler DS pods by default scheduler" (https://github.com/kubernetes/kubernetes/pull/63223) should address this once DS pods are created with a high priority.

**Comment by jgrobbel** [comment]
@aveshagarwal 
Thanks for the link. I didn't realise DS pods weren't being scheduled by the same thing as other pods (default scheduler). 

Though I am a bit curious about the design here. It seems to suggest daemonsets are best effort, and if you really want to ensure they run on all nodes you will need to raise their priority. In my case the daemonsets typically monitor the application (like Datadog agents). So I don't consider them to be more important than my application, as in when a node fails say I would be ok with them being evicted. But I do want them to run most of the time - when there is capacity overall to run the whole system?

**Comment by aveshagarwal** [comment]
> So I don't consider them to be more important than my application, as in when a node fails say I would be ok with them being evicted. But I do want them to run most of the time - when there is capacity overall to run the whole system?

Then I'd say its a different problem where cluster is not balanced as desired. For issues like this, you could look into something like https://github.com/kubernetes-incubator/descheduler .

**Comment by jgrobbel** [comment]
@aveshagarwal 
Yes looks like the behaviour `descheduler` gives is what I expected from the "default scheduler". Though sadly it's not yet production ready.

Anyway great, thanks for the info. I can now make a plan.
