### ISSUE TITLE
New e2e testsuites for DNS scale fail to setup the cluster

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubernetes#64774]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

For these 2 test suites visible in the testgrid at network-gce :
http://k8s-testgrid.appspot.com/sig-network-gce#gce-coredns-performance
http://k8s-testgrid.appspot.com/sig-network-gce#gce-kubedns-performance

the testsuite cannot setup correctly the cluster, due to a firewall issue (I think)
See part of the build log below:

```
I0605 12:39:36.975] NAME                                        STATUS                     ROLES     AGE       VERSION
I0605 12:39:36.976] gce-coredns-performance-master              Ready,SchedulingDisabled   <none>    27s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-377q   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-6w50   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:36.976] gce-coredns-performance-minion-group-vf6h   Ready                      <none>    25s       v1.12.0-alpha.0.838+def5179c661df6
I0605 12:39:37.308] Validate output:
I0605 12:39:37.645] NAME                 STATUS    MESSAGE              ERROR
I0605 12:39:37.646] etcd-1               Healthy   {"health": "true"}   
I0605 12:39:37.646] controller-manager   Healthy   ok                   
I0605 12:39:37.646] scheduler            Healthy   ok                   
I0605 12:39:37.647] etcd-0               Healthy   {"health": "true"}   
I0605 12:39:37.652] Cluster validation succeeded
W0605 12:39:37.752] Done, listing cluster services:
W0605 12:39:37.752] 
I0605 12:39:37.853] Kubernetes master is running at https://35.231.139.160
I0605 12:39:37.955] GLBCDefaultBackend is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
I0605 12:39:37.955] Heapster is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/heapster/proxy
I0605 12:39:37.956] CoreDNS is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
I0605 12:39:37.956] kubernetes-dashboard is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy
I0605 12:39:37.956] Metrics-server is running at https://35.231.139.160/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
I0605 12:39:37.956] 
I0605 12:39:37.957] To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
I0605 12:39:37.958] 
I0605 12:40:00.832] NAME                                                             NETWORK                  DIRECTION  PRIORITY  ALLOW            DENY
I0605 12:40:00.832] gce-coredns-performance-minion-gce-coredns-performance-http-alt  gce-coredns-performance  INGRESS    1000      tcp:80,tcp:8080
I0605 12:40:01.785] allowed:
I0605 12:40:01.785] - IPProtocol: tcp
I0605 12:40:01.785]   ports:
I0605 12:40:01.786]   - '80'
I0605 12:40:01.786] - IPProtocol: tcp
I0605 12:40:01.786]   ports:
I0605 12:40:01.786]   - '8080'
I0605 12:40:01.786] creationTimestamp: '2018-06-05T05:39:39.559-07:00'
I0605 12:40:01.786] description: ''
I0605 12:40:01.786] direction: INGRESS
I0605 12:40:01.787] id: '4755345594321156708'
I0605 12:40:01.787] kind: compute#firewall
I0605 12:40:01.787] name: gce-coredns-performance-minion-gce-coredns-performance-http-alt
I0605 12:40:01.787] network: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-prl-flaky/global/networks/gce-coredns-performance
I0605 12:40:01.787] priority: 1000
I0605 12:40:01.787] selfLink: https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-prl-flaky/global/firewalls/gce-coredns-performance-minion-gce-coredns-performance-http-alt
I0605 12:40:01.788] sourceRanges:
I0605 12:40:01.788] - 0.0.0.0/0
I0605 12:40:01.788] targetTags:
I0605 12:40:01.788] - gce-coredns-performance-minion
=======
W0605 13:00:04.876] Failed to create firewall gce-coredns-performance-minion-gce-coredns-performance-nodeports in k8s-jkns-e2e-gce-prl-flaky
=======
W0605 13:00:04.878] 2018/06/05 13:00:04 process.go:152: Step './hack/e2e-internal/e2e-up.sh' finished in 26m29.118690007s
W0605 13:00:04.879] 2018/06/05 13:00:04 e2e.go:523: Dumping logs from nodes to GCS directly at path: gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-coredns-performance/4/artifacts
W0605 13:00:04.879] 2018/06/05 13:00:04 process.go:150: Running: ./cluster/log-dump/log-dump.sh /workspace/_artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-coredns-performance/4/artifacts
W0605 13:00:04.924] Trying to find master named 'gce-coredns-performance-master'
W0605 13:00:04.924] Looking for address 'gce-coredns-performance-master-ip'
I0605 13:00:05.025] Checking for custom logdump instances, if any
I0605 13:00:05.025] Sourcing kube-util.sh
I0605 13:00:05.025] Detecting project
I0605 13:00:05.026] Project: k8s-jkns-e2e-gce-prl-flaky
I0605 13:00:05.026] Network Project: k8s-jkns-e2e-gce-prl-flaky
I0605 13:00:05.026] Zone: us-east1-b
I0605 13:00:05.026] Dumping logs from master locally to '/workspace/_artifacts'
W0605 13:00:05.833] Using master: gce-coredns-performance-master (external IP: 35.231.139.160)
I0605 13:00:33.644] Changing logfiles to be world-readable for download
I0605 13:00:36.930] Copying 'kube-apiserver kube-apiserver-audit kube-scheduler rescheduler kube-controller-manager etcd etcd-events glbc cluster-autoscaler kube-addon-manager fluentd startupscript' from gce-coredns-performance-master
W0605 13:00:38.107] 
W0605 13:00:38.108] Specify --start=42264 in the next get-serial-port-output invocation to get only the new output starting from here.
W0605 13:00:41.259] scp: /var/log/cluster-autoscaler.log*: No such file or directory
W0605 13:00:41.333] scp: /var/log/fluentd.log*: No such file or directory
W0605 13:00:41.333] scp: /var/log/startupscript.log*: No such file or directory
W0605 13:00:41.337] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

**What you expected to happen**:
I would think that setup the cluster is part of the process of the test-infra job, not the e2e test itself.

Any missing flag or option on the job definition (see below) ?
Need guidance on how to find the root cause of this error.

**How to reproduce it (as minimally and precisely as possible)**:

Just look at the testgrid, it happen every 6 hours.
http://k8s-testgrid.appspot.com/sig-network-gce#gce-coredns-performance
http://k8s-testgrid.appspot.com/sig-network-gce#gce-kubedns-performance

**Anything else we need to know?**:

job definition is:

```
  "ci-kubernetes-e2e-gce-coredns-performance": {
    "args": [
      "--cluster=gce-coredns-performance",
      "--env=CLUSTER_DNS_CORE_DNS=true",
      "--extract=ci/latest",
      "--gcp-master-image=gci",
      "--gcp-node-image=gci",
      "--gcp-nodes=3",
      "--gcp-zone=us-east1-b",
      "--provider=gce",
      "--test_args=--ginkgo.focus=\\[Feature:PerformanceDNS\\]",
      "--timeout=60m",
      "--use-logexporter"
    ],
    "scenario": "kubernetes_e2e",
    "sigOwners": [
      "sig-network"
    ]
  },

```

NOTE: this job definition was copied from another one that seems working fine:

```
  "ci-kubernetes-e2e-gci-gce-coredns": {
    "args": [
      "--check-leaked-resources",
      "--cluster=",
      "--env=CLUSTER_DNS_CORE_DNS=true",
      "--extract=ci/latest",
      "--gcp-zone=us-central1-f",
      "--ginkgo-parallel=30",
      "--provider=gce",
      "--test_args=--ginkgo.skip=\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8",
      "--timeout=150m"
    ],
    "scenario": "kubernetes_e2e",
    "sigOwners": [
      "sig-network"
    ]
  },
```

**Environment**:
- Kubernetes version (use `kubectl version`): current (branch master)
- Cloud provider or hardware configuration: gce

**Comment by fturib** [comment]
@chrisohaver : I finally create this issue to get help.

@shyamjvs , @wojtek-t : any idea on why the firewall rules cannot be set ? 
Could you indicate how to investigate this issue ? 
Thanks..

**Comment by shyamjvs** [comment]
I think it's because the name is too long. There's a limit of 64 chars or sth for resource names on GCP. Try changing the --cluster arg to `gce-coredns-perf` or sth.

**Comment by fturib** [comment]
@chrisohaver proposed a fix here : https://github.com/kubernetes/test-infra/pull/8127
it is now merge. Need to verify the next run of these testsuites 
within 0 to 6 hours from now.

@shyamjvs : Thanks for your advise !

**Comment by fturib** [comment]
After updating the name of the cluster (shorter). The Cluster is now setup correctly.
The PerformanceDNS test itself is failing - unable to create he 10k services.

We believe that is an issue on the number of 10k services that k8s cannot support with this configuration of cluster.

Next step is to decrease the number of services to 5k - a number we tested locally and know that k8s support.

**Comment by shyamjvs** [comment]
Can you tell the reason why it's unable to create so many services?

**Comment by chrisohaver** [comment]
I _suspect_ that the cluster cannot operate correctly with that many services.  It _can_ create the services.  But the cluster acts undesirably after they are created.
In my local tests on a single node cluster when I ramped up the number of services to 10K, I saw the same mode of failure. With 10K services, the cluster is unable to spin up the "util" pod.  The "util" pod is required in the test to query the DNS from the context of a pod - if it's not running then the test cannot proceed.

**Comment by wojtek-t** [comment]
But do you know what exactly is happening?
What do you mean by "cluster is unable to spin up the "util" pod"?
Is the pod not even being created? Or maybe is it scheduled, but kubelet is not starting it?

Having more insight would help debugging it (maybe it's just size of master machine that is too small).

**Comment by chrisohaver** [comment]
> But do you know what exactly is happening?

I dont for sure. But...

According to the logs, I think the pod is successfully created.  But when we try to run DNS queries, it's the _container_ in the pod named "util" that cannot be found - not necessarily the pod itself.  So, it seems the pod may be still starting up at the time - perhaps slowed by the number of services present.

Maybe if I create the pod before creating the services it will help.

**Comment by shyamjvs** [comment]
Let's try to understand this better. If it's that creating services is
limiting us on the api qps, then starting the pod may potentially be slowed
down (due to shortage of qps).
Your idea sounds good, or you might alternatively try to slow down the rate
of service creation.

In general, I believe it shouldn't be a problem to create so many empty
services in the cluster.

**Comment by wojtek-t** [comment]
Please paste link to logs from that cluster (run from testgrid) - so that others can take a look into it.

**Comment by chrisohaver** [comment]
OK, these are logs of the failure when pod is created after services...

```
[It] Should answer DNS query for maximum number of services per cluster
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_scale_records.go:52
Jun  6 06:46:21.819: INFO: Creating 10000 test services
```
creates services OK I believe (this step takes just under 10 minutes).
Then it creates the client pod...
```
Jun  6 06:54:41.174: INFO: Created pod &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:e2e-dns-scale-records-rxlp8,GenerateName:e2e-dns-scale-records-,Namespace:e2e-tests-performancedns-crzfq,SelfLink:/api/v1/namespaces/e2e-tests-performancedns-crzfq/pods/e2e-dns-scale-records-rxlp8,UID:7c76e093-6956-11e8-a8ca-42010a8e0002,ResourceVersion:21901,Generation:0,CreationTimestamp:2018-06-06 06:54:41 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: e2e-dns-scale-records,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[{default-token-rglvd {nil nil nil nil nil SecretVolumeSource{SecretName:default-token-rglvd,Items:[],DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{util gcr.io/kubernetes-e2e-test-images/dnsutils-amd64:1.0 [sleep 10000] []  [{ 0 10101 TCP }] [] [] {map[] map[]} [{default-token-rglvd true /var/run/secrets/kubernetes.io/serviceaccount  <nil>}] [] nil nil nil /dev/termination-log File IfNotPresent nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:default,DeprecatedServiceAccount:default,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,},ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[{node.kubernetes.io/not-ready Exists  NoExecute 0xc42271fb40} {node.kubernetes.io/unreachable Exists  NoExecute 0xc42271fb60}],HostAliases:[],PriorityClassName:,Priority:*0,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],},Status:PodStatus{Phase:Pending,Conditions:[],Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[],QOSClass:BestEffort,InitContainerStatuses:[],NominatedNodeName:,},}
Jun  6 06:54:57.310: INFO: Created service &Service{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:e2e-dns-scale-records,GenerateName:,Namespace:e2e-tests-performancedns-crzfq,SelfLink:/api/v1/namespaces/e2e-tests-performancedns-crzfq/services/e2e-dns-scale-records,UID:8614576c-6956-11e8-a8ca-42010a8e0002,ResourceVersion:21932,Generation:0,CreationTimestamp:2018-06-06 06:54:57 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:ServiceSpec{Ports:[{ TCP 10101 {0 10101 } 0}],Selector:map[string]string{app: e2e-dns-scale-records,},ClusterIP:10.0.134.158,Type:ClusterIP,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[],},},}
```

Looks OK?  - client pod is created... So we start querying DNS...
```
Jun  6 06:54:57.310: INFO: Querying 5% of service records
Jun  6 06:54:57.349: INFO: Querying svc-0.e2e-tests-performancedns-crzfq.svc.cluster.local expecting 10.0.67.213
Jun  6 06:54:57.349: INFO: ExecWithOptions {Command:[/usr/bin/dig +short svc-0.e2e-tests-performancedns-crzfq.svc.cluster.local] Namespace:e2e-tests-performancedns-crzfq PodName:e2e-dns-scale-records-rxlp8 ContainerName:util Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
Jun  6 06:54:57.349: INFO: >>> kubeConfig: /workspace/.kube/config
Jun  6 06:54:57.556: INFO: Running dig: [/usr/bin/dig +short svc-0.e2e-tests-performancedns-crzfq.svc.cluster.local], stdout: "", stderr: "", err: unable to upgrade connection: container not found ("util")

```

But the "util" container is not found, possibly because the pod is not ready yet.  Perhaps the helper func that I am using doesn't wait for the pod to be ready.

**Comment by wojtek-t** [comment]
I looked into kubelet logs - pods was succesfully started but then dies (crashed?) - something seems to be wrong on your side.

Logs from here:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-kubedns-performance/8/artifacts/gce-kubedns-perf-minion-group-d83x/

```
I0606 12:55:20.752577    1720 server.go:460] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-performancedns-dbc7k", Name:"e2e-dns-scale-records-hrdpb", UID:"ddc4c33d-6988-11e8-9e9a-42010a8e0002", APIVersion:"v1", ResourceVersion:"21942", FieldPath:"spec.containers{util}"}): type: 'Normal' reason: 'Created' Created container
...
I0606 12:55:34.725034    1720 server.go:460] Event(v1.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-performancedns-dbc7k", Name:"e2e-dns-scale-records-hrdpb", UID:"ddc4c33d-6988-11e8-9e9a-42010a8e0002", APIVersion:"v1", ResourceVersion:"21942", FieldPath:"spec.containers{util}"}): type: 'Normal' reason: 'Started' Started container
...
I0606 12:55:34.755477    1720 kubelet.go:1883] SyncLoop (PLEG): "e2e-dns-scale-records-hrdpb_e2e-tests-performancedns-dbc7k(ddc4c33d-6988-11e8-9e9a-42010a8e0002)", event: &pleg.PodLifecycleEvent{ID:"ddc4c33d-6988-11e8-9e9a-42010a8e0002", Type:"ContainerDied", Data:"7e72a683491e031f3662d22ce5ca67264a640a3427cd1359b4acb9a7b6f80940"}
```

**Comment by wojtek-t** [comment]
> But the "util" container is not found, possibly because the pod is not ready yet. Perhaps the helper func that I am using doesn't wait for the pod to be ready.

It waits for it to be ready, but it dies after that.

**Comment by chrisohaver** [comment]
> something seems to be wrong on your side.

OK, thanks but this isnt a pod I have invented for this test.  It is already used for testing DNS in other existing tests.  So I was expecting it to work.  And it does work fine if i reduce the number of services - which I'll go ahead and do.

**Comment by wojtek-t** [comment]
Let's not down the number of service without understanding why it fails. We need to understand that.

**Comment by chrisohaver** [comment]
Does anyone know if the 10K limit on services is a hard/enforced limit?  I didnt think it was (but thats just an assumption) - but if it is enforced somewhere, and exceeding it causes silent failures, then i'll need to reduce the number of services by a "few" to account for the other already existing services (e.g. the cluster dns service, api, etc...)

**Comment by wojtek-t** [comment]
It's not a hard limit.

**Comment by chrisohaver** [comment]
I managed to get this tested locally with 10K services on a single node.... where I create the pod _before_ the services, and it passes.

OK if I submit a PR with that change?  Or do we want to first try to understand why creating the client pod _after_ services causes a failure?

**Comment by wojtek-t** [comment]
> OK if I submit a PR with that change? Or do we want to first try to understand why creating the client pod after services causes a failure?

If you can explain why this works now and didn't work before, I'm fine - otherwise there is a risk that it may e.g. be flaky. We should understand it before blindly changing that.

**Comment by wojtek-t** [comment]
OK - so I've run it and catched that pod for you.
The reason why it is crashlooping is the following log:
```
standard_init_linux.go:178: exec user process caused "argument list too long"
```

It just can't initialize itself due to too long argument list.

@chrisohaver - So I think that the fix should be different.
Apparently we are not able to have that many services in a single namespace, because env vars that we provide for all pods (with services from that namespace) are too long in total.

So I think what we should do is to:
- uncover how many services we are able to have in a single namespace (so binary search on number of those should do the job)
- split those 10k service over multiple namespaces

Does that make sense to you?

@shyamjvs - it's the limitation that recently poped up in our conversations ^^

**Comment by shyamjvs** [comment]
Thanks Wojtek!

And that is why I said we should make use of the experiments dns folks are
already doing, to catch that limitation (and we indeed seem to have caught
it) :)

**Comment by shyamjvs** [comment]
I'll update that discussion once the value is figured out. Btw - thanks for
digging.

**Comment by chrisohaver** [comment]
But I got it to work with 10k services in one namespace... by creating the client pod before creating the services.

On Jun 7, 2018, at 5:47 AM, Wojciech Tyczynski <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI - I just run test with 5000 services and it seemed to work fine (I did just a simple thing to reduce number of services, not split them across namespaces).
So I think having 2 namespaces should be fine.

**Comment by shyamjvs** [comment]
@chrisohaver - IIUC that's because you created the pod even before creating the services (so it wasn't passed those service env vars while creation).

**Comment by chrisohaver** [comment]
OK cool.  Seems  like the limit would need to be added here ... https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md.

Several of the entries are "per ns"  but there isnt one for services.  

As an unrelated side note: I just noticed that the limit on the number of _deployments_ per ns in the thresholds doc lists 20K, with a long term goal of 10K.  Is that a typo? Or is the long term goal to reduce the limit?

**Comment by shyamjvs** [comment]
> Seems like the limit would need to be added here

Filed https://github.com/kubernetes/community/pull/2225 for it.

> Is that a typo?

Seems so to me (should've probably been 10^5?). cc @wojtek-t

**Comment by wojtek-t** [comment]
> Seems so to me (should've probably been 10^5?). cc @wojtek-t

Yeah - I think two values are incorrect wrt it:
- pods/namespace - I think we've never run 15k
- deployments/namespace - it doesn't make much sense to support more deployments than pods
Will send out a PR for it.
