### ISSUE TITLE
Pod stuck into terminating and kubectl delete does not return

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes/kubernetes#64779]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
1. Create a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-deployment
  labels:
    app: bbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbl
  template:
    metadata:
      labels:
        app: bbl
    spec:
      containers:
      - name: nginx
        image: nginx
```
2. deployment works fine and the pod is creating correctly as shown here:

```
$ _output/bin/kubectl get deployment
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
bb-deployment   1         1         1            1           3s
$  _output/bin/kubectl get pod
NAME                            READY     STATUS    RESTARTS   AGE
bb-deployment-659cdb7c4-9c89g   1/1       Running   0          9s
$  _output/bin/kubectl get rs
NAME                      DESIRED   CURRENT   READY     AGE
bb-deployment-659cdb7c4   1         1         1         12s
```
3. Edit the deployment with an non-existence (erroneous) volume as follows:
```
$ _output/bin/kubectl edit deployment
```
add following (non-existent and erroneous volume) to the pod spec:

```
  volumes:
  - name: dockersecrets
    secret:
      defaultMode: 420
      secretName: badsecret
```
add following to the container spec:

```
    volumeMounts:
    - mountPath: /etc/registryconfig
      name: dockersecrets
```

4. Notice that a new pod gets stuck in ContainerCreating:

```
$  _output/bin/kubectl get pod
NAME                             READY     STATUS              RESTARTS   AGE
bb-deployment-659cdb7c4-9c89g    1/1       Running             0          5m
bb-deployment-6bcf47cd64-srzl6   0/1       ContainerCreating   0          3s
```

5. Now edit the deployment again and remove the stanzas added in step 3.

6. Notice the new pod gets stuck into Terminating:

```
$  _output/bin/kubectl get pod
NAME                             READY     STATUS        RESTARTS   AGE
bb-deployment-659cdb7c4-9c89g    1/1       Running       0          7m
bb-deployment-6bcf47cd64-srzl6   0/1       Terminating   0          1m
```
7. Now try to delete the pod stuck into Terminating and its RS, the delete command does not return:

```
_output/bin/kubectl delete pods bb-deployment-6bcf47cd64-srzl6
pod "bb-deployment-6bcf47cd64-srzl6" deleted

```
The delete command does not return and the pod is not removed. Same happens when the pod's associated RS is deleted but again the delete command does not return and the RS is not removed. 

```
$  _output/bin/kubectl get rs
NAME                       DESIRED   CURRENT   READY     AGE
bb-deployment-659cdb7c4    1         1         1         8m
bb-deployment-6bcf47cd64   0         0         0         3m
$  _output/bin/kubectl delete rs bb-deployment-6bcf47cd64
replicaset.extensions "bb-deployment-6bcf47cd64" deleted

$  _output/bin/kubectl get rs
NAME                       DESIRED   CURRENT   READY     AGE
bb-deployment-659cdb7c4    1         1         1         10m
bb-deployment-6bcf47cd64   0         0         0         4m
$  _output/bin/kubectl get pod
NAME                             READY     STATUS        RESTARTS   AGE
bb-deployment-659cdb7c4-9c89g    1/1       Running       0          10m
bb-deployment-6bcf47cd64-srzl6   0/1       Terminating   0          4m

```
8. Now try deleting the deployment and the again the delete command does not return:
```
$ _output/bin/kubectl delete deployment bb-deployment
deployment.apps "bb-deployment" deleted
^C
$ _output/bin/kubectl get deployment
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
bb-deployment   1         0         0            0           12m
$ _output/bin/kubectl get pods
NAME                             READY     STATUS        RESTARTS   AGE
bb-deployment-6bcf47cd64-srzl6   0/1       Terminating   0          7m
$ _output/bin/kubectl get rs
NAME                       DESIRED   CURRENT   READY     AGE
bb-deployment-6bcf47cd64   0         0         0         7m
```
So notice that the running pod and its RS are deleted but the deployment still remains and the delete command does not return. 

**What you expected to happen**:
When deleting anything (deployment, pod, RS), they are deleted without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
see steps above.

**Anything else we need to know?**:
This is tested on latest kube master branch as of now.

**Environment**:
- Kubernetes version (use `kubectl version`): latest master kube branch.
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): fedora
- Kernel (e.g. `uname -a`):
- Install tools: hack/local-cluster-up.sh
- Others:

**Comment by aveshagarwal** [comment]
Please note the flag keep-terminated-pod-volumes is set to false in kubelet.

**Comment by gnufied** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/64855
