### ISSUE TITLE
Set user-agent per test in e2e framework

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#64790]
In order to identify which e2e test is hitting a specific API endpoint

Given an e2e test using [e2e/framework/utils](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2019-L2034)
When the user agent is set via [client-go config](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L86-L87)
Then we will be able to [log which e2e test called a specific API](https://github.com/kubernetes/kubernetes/issues/64791)

Prior discussion: https://groups.google.com/d/msg/kubernetes-sig-api-machinery/R-z_NjiLzmg/q1kWg9jSAQAJ

/kind feature
/cc @kubernetes/api-reviewers @kubernetes/sig-testing-feature-requests @liggitt @lavalamp @bgrant0607

**Comment by hh** [comment]
Related: [Add user-agent to audit-logging](#64791)

**Comment by hzxuzhonghu** [comment]
If we want to only set User-Agent in a common place, 　I think add `	config.UserAgent = f.BaseName
` here can work well.

https://github.com/kubernetes/kubernetes/blob/fd044d152ee13a6cb812e4c3e7504ee8e24b5b8c/test/e2e/framework/framework.go#L154-L157

**Comment by hzxuzhonghu** [comment]
cc @sttts @tallclair @CaoShuFeng

**Comment by sttts** [comment]
@hzxuzhonghu had the same thought.

**Comment by rohfle** [comment]
Since User-Agent is a HTTP header itself, would it be better to create descriptive headers specifically and then log all headers in audit logs?

Something like:
```
GET / HTTP/1.1
Host: kubernetes.master
User-Agent: curl/7.58.0
Accept: */*
Kubetest-Name: "[storage] storage related tests"
Kubetest-Description: "should do the thing"
Kubetest-File: "path/to/test.go:43"
...
HTTP/1.1 200 OK
```

**Comment by tallclair** [comment]
For the sake of argument, alternative approaches that wouldn't require changes to auditing:

- Append a custom query string, which would generally be ignored but show up in the audit log URL field
- Act as a per-test service account. Requires creating the account & RBAC bindings.

However, since we want to [add user-agent to the audit logs anyway](https://github.com/kubernetes/kubernetes/pull/64812), I agree that's the preferred approach.

**Comment by hh** [comment]
What about generically add support in [kubernetes/client-go](https://github.com/kubernetes/client-go) to set user-agent to the calling src code file and line using  [runtime.Caller](https://golang.org/pkg/runtime/#Caller).

An off-by-default option, having this level of insight for any k8s application seems like an easy win. Generating an index of test data that includes links to github for all calling/called functions.

I'm exploring this idea a bit further: https://github.com/cncf/apisnoop/issues/23
