### ISSUE TITLE
Add user-agent to audit-logging

### ISSUE THREAD

**Issue by hh** [kubernetes/kubernetes#64791]
In order to identify which e2e test (or other client) is hitting a specific API endpoint

Given an API call with [user agent set](https://github.com/kubernetes/kubernetes/issues/64790)
When the event is written to the audit-logging faciliites
Then the log will include the user-agent

Prior discussion: https://groups.google.com/d/msg/kubernetes-sig-api-machinery/R-z_NjiLzmg/q1kWg9jSAQAJ

/kind feature
/cc @kubernetes/api-reviewers @kubernetes/sig-testing-feature-requests @liggitt @lavalamp @bgrant0607

**Comment by hh** [comment]
Related: [Set user-agent per test in e2e framework](#64790)

**Comment by hzxuzhonghu** [comment]
If no one is working on this, I can pick it up.

**Comment by mikedanese** [comment]
While I'm not necessarily opposed to adding user-agent to the audit log, I'm not convinced by the motivating example. Why not run each e2e test with a different service account?

**Comment by tallclair** [comment]
Would it make sense to add the user agent to the UserInfo.Extra values? https://github.com/kubernetes/kubernetes/blob/c2e3d0526d788ae3792626bbc165101b8f5ada8e/staging/src/k8s.io/api/authentication/v1/types.go#L98

Where ever it is, we should make it clear that it's for debugging only, and not secure (trivial to spoof)

**Comment by liggitt** [comment]
> Would it make sense to add the user agent to the UserInfo.Extra values?

I don't think a user-controlled value belongs in that data. In the audit event in some way makes sense to me

**Comment by lavalamp** [comment]
I think it would be good to include User-Agent in some way; I've found user
agent to be invaluable in tracking down the source of requests. It used to
be printed in api logs by default, but we booted those to V(3) and now it's
not findable anywhere--even if we have audit logs.

It's definitely trivial to spoof, but in the common case it is immediately
enlightening.

**Comment by lavalamp** [comment]
We could list it as "claimedUserAgent" or something to make it clear it's
not been scrutinized.

**Comment by tallclair** [comment]
OK, I'm convinced. I think documenting that the field is spoofable is sufficient.

**Comment by hh** [comment]
One interesting use case would be to generically add support in [kubernetes/client-go](https://github.com/kubernetes/client-go) to set the user-agent to the calling src code file and line using  [runtime.Caller](https://golang.org/pkg/runtime/#Caller). This would probably be an off-by-default option, but would provide very interesting data.

**Comment by hh** [comment]
I'm exploring logging all k8s client-go usage src+line using runtime.Caller a bit further:
https://github.com/cncf/apisnoop/issues/23
