### ISSUE TITLE
v1.11 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/kubernetes#64806]
Please link to this issue or comment on this issue with known errata for the 1.11.x release. This follows what we have done for prior releases.

We will be populating the "Known Issues" section of 1.11.0 and above release notes based on this issue

**cc: @jberkus, @nickchase, @marpaia, @kubernetes/kubernetes-release-managers**

**Comment by jberkus** [comment]
There's a known issue where the Vertical Pod Autoscaler will radically change implementation in 1.12, so users of VPA (alpha) in 1.11 are warned that they will not be able to automatically migrate their VPA configs from 1.11 to 1.12.

**Comment by jberkus** [comment]
THis change:

https://github.com/kubernetes/kubernetes/pull/64988

May cause users to see some new error messages during bootstrap

**Comment by luxas** [comment]
@jberkus I think it's the other way. #64988 makes the user _not_ see those warning messages. Depending on how critical the bug fix is, we might wanna backport it to v1.10, but it's gonna be fixed in v1.11 we think.
cc @timothysc @detiber

**Comment by luxas** [comment]
FWIW, https://github.com/kubernetes/kubeadm/issues/857 is a known issue in `kube-proxy`. It's not new, has been here all releases so far, but we want to highlight it to users this release at least as we've been talking about this.

**Comment by guineveresaenger** [comment]
/milestone needs-attention

(Not sure why the label got removed.)

**Comment by tpepper** [comment]
Feels like the bot incorrectly stopped caring about this issue, and only the bot can add that label?  It's not listed in https://prow.k8s.io/command-help

**Comment by luxas** [comment]
The /milestone command only works for the actual milestone, which can only be `v1.11` or similar: `/milestone v1.11`.
I don't think it's a problem with this issue not having `milestone/needs-attention`. In fact, I think it's a good sign that this label isn't applied, means (AFAIU) everything's good for now.

**Comment by tpepper** [comment]
Yes on the /milestone command args based on prow docs.

But from a sig-release perspective I believe the needs-attention label was, and remains desirable here as a reminder to sig-release and the release team heading in to the release.  The release hasn't yet happened just because the branch is created and master is thawed, so the release team needs to continue checking whether any cherry picks now also require info in the FAQ.  Especially in this last phase the surprise issues that come up are liable to lead to FAQ or release note additions.

**Comment by Lion-Wei** [comment]
https://github.com/kubernetes/kubernetes/issues/57841

**Comment by tpepper** [comment]
@nickchase possible ^^^ rel note add

**Comment by tpepper** [comment]
I'm for closing this now and using PRs against the CHANGELOG-1.11 file in master.
