### ISSUE TITLE
Kubectl Get All Does Not Show Persistent Volume Claims

### ISSUE THREAD

**Issue by Noah-Huppert** [kubernetes/kubernetes#64814]
> /kind bug

**What happened**:
When I run `kubectl get all` Persistent Volume Claims are not listed.  

Instead I must run `kubectl get pvc`.

```
$ kubectl -n factorio get all
NAME                TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
svc/kube-lego-gce   NodePort   XX.XX.XXX.XXX   <none>        8080:32133/TCP   1d

$ kubectl -n factorio get pvc
NAME             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
factorio-saves   Bound     pvc-XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX   2G         RWO            standard       10m
```

**What you expected to happen**:

I expected `kubectl get all` to list all resources.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Persistent Volume Claim  
2. Run `kubectl get all`

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.1", GitCommit:"75d2af854b1df023c7ce10a8795b85d3dd1f8d37", GitTreeState:"clean", BuildDate:"2018-05-10T17:23:18Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Arch Linux  
- Kernel (e.g. `uname -a`):
```
Linux katla 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux
```
- Install tools:
```
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
- Others:

**Comment by liggitt** [comment]
Unfortunately, the guidelines around the `all` alias that make it hard to delete unrecoverable data also exclude listing PVCs this way. See https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

/close

**Comment by liggitt** [comment]
The reference to "all" has actually been removed from the help text in 1.11 because of how misleading it is, and replaced with a reference to the command `kubectl api-resources` which tells you the resource types actually available on your cluster
