### ISSUE TITLE
Randomly one of my node becomes "NodeNotReady", and its pods fail

### ISSUE THREAD

**Issue by sneko** [kubernetes/kubernetes#64819]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
@kubernetes/sig-node-bugs
/sig node

**What happened**:

Hi! Each time, after a few hours, one of my node (randomly) goes in the status "NodeNotReady"... Without doing anything! Moreover the pods of this node either go in PENDING state or they have errors like (depending of the tool):

"Liveness probe failed: Get http://100.96.11.54:9090/-/healthy: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

"Readiness probe failed: rpc error: code = 13 desc = transport is closing"

"Readiness probe failed: Error: fail on inspecting path /health: file /health is too old"

That's recurrent... 2 times per day I think.

**What you expected to happen**:

That my cluster works correctly since nodes are not overloaded. I have the cluster-autoscaler to be sure of that... and I do not make any settings change 😄 

**How to reproduce it (as minimally and precisely as possible)**:

Sincerely, I don't know...

**Anything else we need to know?**:

Here is the 2 events that Kubernetes relates to the failing node:

![image](https://user-images.githubusercontent.com/8195958/41026367-3858fb9c-6929-11e8-91d2-6f0c8a283021.png)

And about consumption:
```
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----                 ------    -----------------                 ------------------                ------                     -------
  NetworkUnavailable   False     Sun, 03 Jun 2018 01:39:30 -0700   Sun, 03 Jun 2018 01:39:30 -0700   RouteCreated               RouteController created a route
  OutOfDisk            False     Wed, 06 Jun 2018 00:42:03 -0700   Sun, 03 Jun 2018 01:39:20 -0700   KubeletHasSufficientDisk   kubelet has sufficient disk space available
  MemoryPressure       Unknown   Wed, 06 Jun 2018 00:42:03 -0700   Wed, 06 Jun 2018 00:42:55 -0700   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure         Unknown   Wed, 06 Jun 2018 00:42:05 -0700   Wed, 06 Jun 2018 00:42:55 -0700   NodeStatusUnknown          Kubelet stopped posting node status.
  Ready                Unknown   Wed, 06 Jun 2018 00:42:05 -0700   Wed, 06 Jun 2018 00:42:55 -0700   NodeStatusUnknown          Kubelet stopped posting node status.
```

Your help would be really valuable for me 👍 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GCE

**Comment by igoratencompass** [comment]
I can confirm the same issue, was seeing nodes go `NotReady` and stay in that state and other flapping between `Ready` and `NotReady`.  I had exactly the same output from `describe node` with `Kubelet stopped posting node status` as the OP. This is on k8s v1.8.7

**Comment by sneko** [comment]
Hi @igoratencompass , you talk about it in the past. How did you manage this issue?

**Comment by sneko** [comment]
Loosing my mind 😞 ... sometimes it breaks 3 nodes within 6 hours. Anyone could help please?

**Comment by igoratencompass** [comment]
@sneko no resolution, I have to terminate that worker and let Kops launch a new one. In the latest incident, I have now upgraded from 1.8.7 to 1.8.13, I got something different though the node shows as Ready but all pods on that node are screwed:

```
$ kc get pods -o wide --all-namespaces | grep -vi running
NAMESPACE       NAME                                                                READY     STATUS              RESTARTS   AGE       IP                NODE
cert-manager    cert-manager-5886f49b8c-qv5mh                                       0/2       ContainerCreating   0          2d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
default         mongo-0                                                             0/2       ContainerCreating   0          3d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
default         nginx-gluster-2959091722-kdzq5                                      0/1       ContainerCreating   0          2d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
default         nodejs-app-deployment-67c7495948-47c2j                              0/1       ContainerCreating   0          2d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
default         php-apache-3815965786-ttbpr                                         0/1       ContainerCreating   0          2d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
encompass       corenlp-67465d8745-njgjh                                            0/1       ContainerCreating   0          10h       <none>            ip-10-99-6-219.eu-west-1.compute.internal
kube-system     calico-node-5rz26                                                   0/2       Error               0          5d        10.99.6.219       ip-10-99-6-219.eu-west-1.compute.internal
kube-system     filebeat-q8t82                                                      0/2       Error               0          5d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
kube-system     kube-proxy-ip-10-99-6-219.eu-west-1.compute.internal                0/1       Error               0          1d        10.99.6.219       ip-10-99-6-219.eu-west-1.compute.internal
kube-system     s3fs-24wcg                                                          0/1       ContainerCreating   0          2d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
monitoring      kube-state-metrics-6cccb7f95f-7v4n5                                 0/4       ContainerCreating   0          3d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
monitoring      node-exporter-fp7cp                                                 0/2       Error               0          5d        10.99.6.219       ip-10-99-6-219.eu-west-1.compute.internal
monitoring      prometheus-k8s-0                                                    0/2       ContainerCreating   0          3d        <none>            ip-10-99-6-219.eu-west-1.compute.internal
```
I see lots of these in the kubelet logs on that node when this happens:

```
Jun 12 00:02:37 ip-10-99-6-219 kubelet[29130]: I0612 00:02:37.766039   29130 kubelet.go:1871] SyncLoop (PLEG): "node-exporter-fp7cp_monitoring(9b75d760-6951-11e8-9b7b-061cd03b3fe6)", event: &pleg.PodLifecycleEvent{ID:"9b75d760-6951-11e8-9b7b-061cd03b3fe6", Type:"ContainerDied", Data:"9485865f56187334694dae461b6af741184cb82f31d3de2f7659378e31e06c1d"}
Jun 12 00:02:37 ip-10-99-6-219 kubelet[29130]: W0612 00:02:37.772652   29130 pod_container_deletor.go:77] Container "9485865f56187334694dae461b6af741184cb82f31d3de2f7659378e31e06c1d" not found in pod's containers
Jun 12 00:02:38 ip-10-99-6-219 kubelet[29130]: I0612 00:02:38.069837   29130 kuberuntime_manager.go:392] No ready sandbox for pod "node-exporter-fp7cp_monitoring(9b75d760-6951-11e8-9b7b-061cd03b3fe6)" can be found. Need to start a new one
```
I also see lots of:
```
Jun 12 00:08:43 ip-10-99-6-219 kubelet[3901]: E0612 00:08:43.663800    3901 fs.go:418] Stat fs failed. Error: no such file or directory
Jun 12 00:08:44 ip-10-99-6-219 kubelet[3901]: E0612 00:08:44.709540    3901 kubelet_volumes.go:129] Orphaned pod "54c72112-6996-11e8-9b7b-061cd03b3fe6" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
Jun 12 00:08:46 ip-10-99-6-219 kubelet[3901]: E0612 00:08:46.715091    3901 kubelet_volumes.go:129] Orphaned pod "54c72112-6996-11e8-9b7b-061cd03b3fe6" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```
and:
```
Jun 12 00:06:31 ip-10-99-6-219 kubelet[3901]: E0612 00:06:31.235899    3901 generic.go:271] PLEG: pod filebeat-q8t82/kube-system failed reinspection: rpc error: code = Unknown desc = Error: No such container: 602820431ea8911188d32e7ba233dc1f4465d61858bc0f06b46a9945a3032056
```
Only workaround I found is logging to that node and restarting *both* docker and kubelet service which brought most of the pods into running state but `node-exporter` is still in `CrashLoopBackOff` state.

**Comment by igoratencompass** [comment]
Additional info, after deleting the stuck `node-exporter` pod:
```
$ kc delete pods node-exporter-fp7cp -n monitoring --force --grace-period=0
```
the new one that launched was successful. Note that this only worked *after* the above mentioned service restart and had no effect before, the new pods were ending up in the same state as the previous one.

**Comment by sneko** [comment]
@igoratencompass I succeed in solving my issue 👍 

One of my pod was logging too much information so the logs collector (Fluentd) and the logs storage (ElasticSearch) were overloaded after few hours of handling that.

I noticed that because I set up Prometheus and Grafana to see detailed metrics of my nodes/pods. At the time my nodes were crashing the CPU was at 100% of usage. I think after few seconds at the maximum CPU usage the node kills whatever it can or reboot.

I can't promise you that's a resources issue in your case, but you should investigate since without enough resources kubelet is not can't answer to the master requests so the master try to drain the node...

I hope it will help you. I lost several days because of that... 😁
