### ISSUE TITLE
WEB SITE ISSUE - kubernetes.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#64826]
/kind bug

**What happened**:
Missing information on documentation 

**What you expected to happen**:
Content of config.yaml

**How to reproduce it (as minimally and precisely as possible)**:

https://kubernetes.io/docs/setup/independent/high-availability/

/sig docs

**Comment by liggitt** [comment]
thanks for the report. please open issues for the kubernetes.io website at https://github.com/kubernetes/website/issues

/close
