### ISSUE TITLE
GKE: error creating cluster: error during gcloud container clusters create

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#64833]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

There are 3 tests that are currently failing since 10.30 yesterday: 

1. https://k8s-testgrid.appspot.com/sig-cli-master#gke (sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-sig-cli/2681)
2. https://k8s-testgrid.appspot.com/sig-cli-master#gke-serial (sample failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-serial-sig-cli/3582)
3. https://k8s-testgrid.appspot.com/sig-cli-master#skew-cluster-latest-kubectl-stable1-gke (sample failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-master-new-gci-kubectl-skew/9130)

They all suffer from GKE problems: 

```
error creating cluster: error during gcloud container clusters create --quiet --project=k8s-gke-upg-g1-4-g1-6-up-clu-n --zone=us-central1-c --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --network=bootstrap-e2e --cluster-version=1.12.0-alpha.0.846+c178c7fd65fd16 bootstrap-e2e: exit status 1
```

**Comment by soltysh** [comment]
@kubernetes/goog-gke ptal

**Comment by BenTheElder** [comment]
I'm seeing one or two weird flakes there now, but largely green runs and nothing that looks like a persistent issue.

**Comment by mengqiy** [comment]
I believe this one can be closed due to obsolete.
/close
