### ISSUE TITLE
[Failing Test] : [k8s.io] Sysctls tests failing release-upgrade test suite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64845]
## Failing Jobs
* [gce-1.10-master-upgrade-cluster-parallel)](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)

This job tests upgrading master and node, in gce(gci), from 1.10 to master, run parallel tests only.

## Error Logs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3694

/kind bug
/priority failing-test
/priority critical-urgent
/milestone v1.11
/assign @sjenning 
cc @jberkus @tpepper

Possible breaking change https://github.com/kubernetes/kubernetes/pull/63717

**Comment by sjenning** [comment]
It seems the old tests are running against the new code.  Line number align with `test/e2e/common/sysctl.go` *before* the PR.

**Comment by liggitt** [comment]
@ingvagabund can you open a PR against release-1.10 gating the tests using the alpha annotations from running on 1.11.0-alpha.0 or newer?

**Comment by ingvagabund** [comment]
> This job tests upgrading master and node, in gce(gci), from 1.10 to master, run parallel tests only.

Once again, what is the purpose of the test?

**Comment by jberkus** [comment]
It's an upgrade test.  Not sure what else you need to know?

**Comment by liggitt** [comment]
in general, the upgrade tests ensure function as exercised in the previous release doesn't regress. the falls apart when the function being tested is explicitly deprecated/dropped in the next version (like these alpha-level annotations). in those cases, we have to fix the previous release branch's tests with magic knowledge from the future.

**Comment by AishSundar** [comment]
@ingvagabund may be this helps - https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#version-skewed-and-upgrade-testing

As part of upgrade testing we ensure (among other things) "A newer version of the whole cluster with older tests (e.g. that a cluster upgraded---master and nodes---to v1.3 still passes v1.2 tests)."

So if I am reading this correctly, "gce-1.10-master-upgrade-cluster-parallel" jobs upgrade the entire cluster from 1.10 -> master and then runs 1.10 tests on it. so if the feature is deprecated in 1.11 then the tests will fail.  @krzyzacy @BenTheElder to add if I missed / misquoted something

**Comment by krzyzacy** [comment]
I mean if a feature is deprecated, it should handle the deprecation in tests as well. Aka what's the intended behavior if you have feature foo enabled in 1.10 and that's deprecated on 1.11?

**Comment by liggitt** [comment]
> what's the intended behavior if you have feature foo enabled in 1.10 and that's deprecated on 1.11?

at some point, deprecated function gets dropped. for example, root proxy paths deprecated in 1.2 and dropped in 1.10 required back-patching 1.9 tests that were gamely ensuring the deprecated function kept working

in this case, the thing that got dropped was an alpha annotation, which can be dropped without a deprecation period. in my opinion, tests exercising alpha features shouldn't be part of upgrade tests

**Comment by dims** [comment]
@krzyzacy the tests in 1.10 branch is running against master. the master changed sysctl stuff from annotations to master, so it will fail.

**Comment by BenTheElder** [comment]
> in my opinion, tests exercising alpha features shouldn't be part of upgrade tests?

yes, please 👍

**Comment by ingvagabund** [comment]
@liggitt @AishSundar thanks for the explanation.

**Comment by dims** [comment]
we have a green run! https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/3709

**Comment by liggitt** [comment]
Sounds good

/close
