### ISSUE TITLE
`schedulerName` of DaemonSet pods should not be default-scheduler 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#64857]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Create a DaemonSet. It'll create pods with schedulerName=default-scheduler. However, the DaemonSet pods aren't actually scheduled by default-scheduler but DaemonSet controller. 

@k82cn

**Comment by k82cn** [comment]
If the "schedulerName" is empty, apiserver will set the default value to "default-scheduler". To avoid the confusion, I think we can let DaemonSet set this field (for example 'ds-controller') when creating the DaemonSet pods, WDYT?

**Comment by janetkuo** [comment]
What's "schdulerName" for? Is it just for telling the users who scheduled this pod, or is this information used by other resources in the system?

Also, I'd expect this field to be set by schedulers. Why is it not set by default scheduler, but apiserver? How does apiserver know which scheduler does the work, if there are more than one?

Letting DaemonSet controller set this field sounds reasonable, as DaemonSet controller is the "scheduler".

**Comment by k82cn** [comment]
> What's "schdulerName" for? Is it just for telling the users who scheduled this pod, or is this information used by other resources in the system?

`schedulerName` is introduced by multi-scheduler; a common case is to set it by user in `yaml`: it means this Pod should be scheduled by specific scheduler. In each scheduler (including the default scheduler), it will check whether it's responsible for the pending Pod. The default value is default scheduler :)

> Letting DaemonSet controller set this field sounds reasonable, as DaemonSet controller is the "scheduler".

Sure, I'll open a PR for this :)

**Comment by liggitt** [comment]
Isn't scheduler name ignored when spec.nodeName is set?

**Comment by k82cn** [comment]
> Isn't scheduler name ignored when spec.nodeName is set?

no, right now; that makes sense to, I'll also include this in PR :)
