### ISSUE TITLE
Windows dns is broken

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#64861]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

PR #64189 tries to reduce CNI calls for sandboxed containers: 

> Windows supports both sandbox and non-sandbox cases. The non-sandbox
case is for Windows Server 2016 and for Windows Server version greater
than 1709 which use Hyper-V containers. Currently, the CNI on Windows fetches the IP from the containers within the pods regardless of the mode. This should be done only
in the non-sandbox mode where the IP of the actual container
will be different than the IP of the sandbox container.
> In the case where the sandbox container is supported, all the containers
from the same pod will share the network details of the sandbox container.
> This patch updates the CNI to fetch the IP from the sandbox container
when this mode is supported.

However, for Windows 1709 and 1803 we didnt have the Namespace support in Windows which we are bringing in RS5. So we need this second call to replicate the DNS registry key to the Workload container. This is a platform requirement and removing this will break DNS for the workload containers. IP/Gateway/MAC is set separately than DNS. (Refer https://github.com/kubernetes/kubernetes/pull/64189#issuecomment-395248704)

In Rs5 once we move the namespace model, we will update CRI and CNI to add endpoints and add it to the namespace. 

So the PR breaks dns for windows containers. We should revert it.

/sig windows
/kind bug

**Comment by tpepper** [comment]
Since #64189 is headed for 1.11, this issue should be similarly milestone 1.11 labeled and approved.

/milestone v1.11
/status approved-for-milestone

**Comment by feiskyer** [comment]
@tpepper PR #64862 has been reviewed by @michmike but still waiting for sig-node's approval
