### ISSUE TITLE
CSI: volume plugin can't recover from Pod deleted before un-mounting devices for it.

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#64875]
**What happened**:
Kubelet has elaborate security mechanism that prevents it from accessing PersistentVolumes that are not referenced by a running pod on the node.

So, when a pod is (forcefully) deleted, kubelet starts unmounting all CSI PVs that the pod used. `csi_plugin.TearDown` succeeds, because it stored all relevant info in a json file. On the other hand, `csi_plugin.UnmountDevice` fails, because it reads PersistentVolume:

```
csi_attacher.go:471] kubernetes.io/csi: attacher.UnmountDevice failed to get driver and volume name from device mount path: persistentvolumes "kubernetes-dynamic-pv-b2f4b7ad6a4511e8" is forbidden:  User "system:node:qe-juzhao-310-qeos-2-nrr-1" cannot get persistentvolumes at the cluster scope: no path found to object
```

https://github.com/kubernetes/kubernetes/blob/63c90bb47ec99247cbf29542edfc443ffda7298b/pkg/volume/csi/csi_attacher.go#L549-L552

**What you expected to happen**:
UnmountDevice() should not read the PV. It can use the same json hack as `SetUp`/`TearDown`.

**How to reproduce it (as minimally and precisely as possible)**:
It's tricky, we found it when we tested a faulty CSI Cinder driver and we tried to clean things up with some force.

/kind bug
/sig storage
@vladimirvivien @saad-ali @sbezverk

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/63827?

**Comment by jsafrane** [comment]
Yes, i'm sorry for the noise.

/close
