### ISSUE TITLE
k8s's autocompletion of image url nullifies Docker configuration

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#64878]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
if you block `docker.io` in Docker config, e2e conformance tests fail as Docker cannot pull `busybox`, which Kubernetes autocompletes to `docker.io/library/busybox:latest`.  

**What you expected to happen**:
Kubernetes should leave resolving default registry to Docker, and not perform "autocompletion" automatically (ie. `busybox` -> `docker.io/library/busybox:latest`). 

Using RHEL's Docker you can configure some other default registry than `docker.io`, and block `docker.io`. From command line you can do `docker pull busybox` and it'll do the correct autocompletion per configuration and succeed in pulling, but in Kubernetes it resolves always to `docker.io/library/busybox` before passing it to Docker and pull fails.

**How to reproduce it (as minimally and precisely as possible)**:
Block `docker.io` in Docker's `registries.conf` and add your own registry as default, and try run conformance tests.

**Anything else we need to know?:**
Also opened a feature request to Sonobuoy to allow specifying which image to use for conformance testing: https://github.com/heptio/sonobuoy/issues/439 but imho Kubernetes is being too "helpful" here, and it should be fixed, or at least made configurable.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration: doesn't matter
- OS (e.g. from /etc/os-release): RHEL 7.5 Maipo
- Kernel (e.g. `uname -a`): 3.10.0-862.2.3
- Install tools: e2e conformance tests with Sonobuoy 1.10

**Comment by derekwaynecarr** [comment]
@tuminoid

Red Hat is aware of this issue and are trying to determine an appropriate course of action in our OpenShift distribution of Kubernetes.  The challenge is that the client library (used in the kubelet dockershim) is manipulating the name before sending it to the docker daemon which is nullifying your `registries.conf` configuration on that local node.

For reference, if you use the `cri-o` runtime , no manipulation of the user input occurs, and the default search registries are used per the cri-o daemon configuration here:
https://github.com/kubernetes-incubator/cri-o/blob/7b3dab8ceeb9a9111302ed4470c50cec12294537/cmd/crio/config.go#L200

/cc @sjenning @mrunalp

**Comment by tuminoid** [comment]
@derekwaynecarr Thanks for the update. I based my title on this comment: https://github.com/kubernetes/kubernetes/issues/52110#issuecomment-332427139 instead of looking at the actual code, so I wrongly assumed it was kubelet/k8s itself being too helpful.

Any idea of the RH ticket number and if this will be fixed in Docker(shim) and not just OpenShift?

Also, for completeness sake, error message as requested by @dims:
```
  Normal   Pulling                3m (x3 over 4m)  kubelet, kubesingle  pulling image "busybox"
  Warning  Failed                 3m (x3 over 4m)  kubelet, kubesingle  Failed to pull image "busybox": rpc error: code = Unknown desc = no such image: "docker.io/library/busybox:latest"
```

**Comment by sjenning** [comment]
>  so I wrongly assumed it was kubelet/k8s itself being too helpful

It isn't wrong as the dockershim/docker client are part of the kubelet albeit a vendored part in the case of the client.
 
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/docker/docker/client/image_pull.go#L23

It is `ParseNormalizedNamed()`, which calls `splitDockerDomain()`, that ends up appending docker.io[/library] to unqualified image paths.  Then `FamiliarName()` just below that ends up stripping the just added prefix of the image path.  :confused: 

**However, I don't think this is your problem.**  Even if you block `docker.io` and add `myreg.com` as the only registry dockerd should pull from, dockerd will resolve it to `myreg.com/busybox` which is not valid as image paths, excepting `docker.io/library/busybox` vs `docker.io/busybox`, require a repo component like `myreg.com/myrepo/busybox`.  Thus the e2e specs as-is will not work if `docker.io` is blocked.

**Comment by tuminoid** [comment]
Why wouldn't `myreg.com/busybox` be legit image path? Docker is capable of adding the default tag if its missing, and it is not required anywhere that `/library/` or `/myrepo` should be in the url.

```
$ docker pull busybox
Using default tag: latest
Trying to pull repository registry:5000/busybox ... 
latest: Pulling from registry:5000/busybox
4387fd0ebc3e: Pull complete 
```
Letting Docker handle the pull with as-is image name gets the correct image pulled just fine, and e2e gets the requested image `busybox` just fine. What I'm missing here, @sjenning ?

**Comment by sjenning** [comment]
So you are saying if you push to `registry:5000/busybox` and set the image path to `busybox` in the pod spec it does not work, right?

I wonder you pushed to `registry:5000/library/busybox` and set the image path to `library/busybox` if it would work?

I also wonder you pushed to `registry:5000/myrepo/busybox` and set the image path to `myrepo/busybox` if it would work?

The docker client does weird things with unqualified names...

**Comment by tuminoid** [comment]
Yes, that is the issue. `e2e` tests pull `busybox`, which gets autocompleted to `docker.io/library/busybox:latest` instead of getting passed as-is to Docker, which would handle it correctly and would pull it from `registry:5000/busybox:latest` as shown in my previous comment.

We never use any additional paths for our images and unfortunately I just begun my summer vacation today and don't have access to RHEL's Docker at home, so I cannot test what k8s would do with `library/busybox` or `myrepo/busybox` in manifest, but the original bug report is specifically for `busybox`, as that is the one `e2e` tests try to pull.

**Comment by dims** [comment]
/remove-lifecycle stale

@derekwaynecarr @tuminoid is this still an issue?

**Comment by dixudx** [comment]
> /remove-lifecycle stale
> 
> @derekwaynecarr @tuminoid is this still an issue?

Not an issue any more. It is docker library that does the autocompletion, not Kubernetes. So if we really want to fix this up, some code changes should be made there.

**Comment by tuminoid** [comment]
Using k8s 1.13.5 and RHEL's Docker 1.13.1, the issue is fixed. K8s now manages to pull the correct image from private registry and does not go for docker.io as expected.

/close
