### ISSUE TITLE
[Failing test] kubeadm-gce and kubeadm-gce-selfhosting are failing on release-master-blocking suite

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64887]
## Failing Jobs
* [kubeadm-gce](https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce&show-stale-tests=)
* [kubeadm-gce-selfhosting](https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-selfhosting&show-stale-tests=)

Error Logs

/kind bug
/priority failing-test
/priority critical-urgent
/milestone v1.11
/assign @luxas 
cc @jberkus @tpepper @timothysc 

Possible breaking change https://github.com/kubernetes/kubernetes/pull/64624 as per offline discussions.

**Comment by timothysc** [comment]
@luxas - Timeline of breakage aligns with merge of https://github.com/kubernetes/kubernetes/pull/64624 , nothing else was in flight to cause it.

**Comment by dims** [comment]
could this be the problem? 

```
Jun  7 04:50:52 e2e-367-f2b95-node-mkwj startup-script: INFO startup-script: [discovery] Successfully established connection with API Server "10.128.0.2:443"
Jun  7 04:50:52 e2e-367-f2b95-node-mkwj startup-script: INFO startup-script: [kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.12" ConfigMap in the kube-system namespace
Jun  7 04:50:52 e2e-367-f2b95-node-mkwj startup-script: INFO startup-script: [kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
Jun  7 04:50:52 e2e-367-f2b95-node-mkwj startup-script: INFO startup-script: failed to write kubelet configuration to the file "/var/lib/kubelet/config.yaml": open /var/lib/kubelet/config.yaml: no such file or directory
Jun  7 04:50:52 e2e-367-f2b95-node-mkwj startup-script: INFO startup-script: Return code 1.
```

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/10758/artifacts/e2e-10758-31d72-node-5t29/serial-1.log
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-selfhosting/367/artifacts/e2e-367-f2b95-node-mkwj/serial-1.log

**Comment by dims** [comment]
Is that's the problem, may be this will help https://github.com/kubernetes/kubernetes/pull/64889

**Comment by dims** [comment]
/reopen

let's wait for a green run and then close this

**Comment by dims** [comment]
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce&show-stale-tests=
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-selfhosting&show-stale-tests=

both jobs are better now (past the failure where they keeled over before the test suite started). But both seem to have some test failures

**Comment by dims** [comment]
we have one green run on each, so let's close this out.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/10773
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-selfhosting/372

/close
