### ISSUE TITLE
etcd healthcheck is too simple

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#64909]
currently, the etcd healthcheck is too simple. It only checks tcp connection https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/preflight/checks.go#L65. 

I think we can enhance it the way etcdctl does. 
etcdV2:  Get(url + "/health")
https://github.com/coreos/etcd/blob/6e39a39e3a0fb4258ed65e781e5d65849ee25d48/etcdctl/ctlv2/command/cluster_health.go#L83

etcdv3: cli.Get(ctx, "health")
https://github.com/coreos/etcd/blob/ff455e3567d6465717d3ced6dc889d4eec9ed890/etcdctl/ctlv3/command/ep_command.go#L121

/sig api-machinery

**Comment by liggitt** [comment]
also, since the health check does a dial every time, it is vulnerable to things like slow dns lookups that might not be affecting the actual established clients. I think switching it to an actual client and doing a health check would be better.
