### ISSUE TITLE
HorizontalPodAutoscaler not respecting PodDisruptionBudget

### ISSUE THREAD

**Issue by matthewfaw** [kubernetes/kubernetes#64917]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I have a Deployment (apps/v1beta1) that is associated with:
1) a PodDisruptionBudget (policy/v1beta1) that specifies maxUnavaliable: 1
2) a HorizontalPodAutoscaler (autoscaling/v2beta1) that specifies minReplicas: 5 and maxReplicas: 5
3) Each pod in the Deployment has terminationGracePeriodSeconds: 60

When performing a rolling upgrade of my Deployment, the PodDisruptionBudget is respected, with only one pod in the deployment being taken offline at any given time.

However, if I apply a change to the HorizontalPodAutoscaler such that minReplicas: 3 and maxReplicas: 3, I observe two pods in the deployment being terminated simultaneously.

**What you expected to happen**:

I would expect that modifying the HorizontalPodAutoscaler in this way would:
1) Wait 60 seconds
2) Terminate 1 pod in the Deployment
3) Wait another 60 seconds
3) Terminate the 2nd pod in the Deployment

**How to reproduce it (as minimally and precisely as possible)**:

Create a Deployment, HPA, and PDB meeting the above specifications, then edit your HPA yaml to specify minRepicas: 3 and maxReplicas: 3, and run `kubectl apply -f <your hpa yaml>.yaml`.  After about 1 minute, you should observe 2 pods in the Deployment being terminated simultaneously (I normally monitor this from the k8s dashboard).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
- Kernel (e.g. `uname -a`):
uname -a
Linux solr-core-deployment-7558c65c8f-cmk72 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 Linux
- Install tools:
`kubectl apply`
- Others:
I'm using the `solr:7.3.1-alpine` Docker image in my Deployment

/sig autoscaling

**Comment by yue9944882** [comment]
@matthewfaw If you want to scale down your deployment by 1 each time, setting `deployment.Spec.Strategy.RollingUpdate.MaxUnavailable` to 1 will do the job. `PodDisruptionBudget ` is basically used during scheduling which is not involved in the process of autoscaling (down).

**Comment by yue9944882** [comment]
But the idea that deployment/rs/rc controller should respect pdb looks really reasonable to me. Maybe I could raise a PR prevent the controllers from scaling down when the actual scale is violated with pdb's expectation. 

@deads2k Could u shed some light this idea? Should deployment/rs/rc controllers respect pdb when scaling down instances? Thx :)

**Comment by ctrom** [comment]
I am also experiencing this issue. I tried to set `deployment.Spec.Strategy.RollingUpdate.MaxUnavailable` to 1 as suggested by @yue9944882, but that didn't seem to have an impact.
