### ISSUE TITLE
Pod startup periodically slow

### ISSUE THREAD

**Issue by omadawn** [kubernetes/kubernetes#64926]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Pods periodically spend a longer than normal time in pending before transitioning to Ready. The container on the pod will actually be running but the pod will still show a status of pending. When this occurs the pod never shows a status of ContainerCreating.

I have a container built from scratch with only a < 20m go binary running. Typically it starts up in < 10s but periodically it will take over 1m to start even on nodes which already have the image cached.

**What you expected to happen**:
Small pods to start up in < 60 seconds assuming no issues downloading or starting the container.
Pods to transition from Pending to ContainterCreating to Ready.

**How to reproduce it (as minimally and precisely as possible)**:
Start up pods and time their startup process.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS (on EC2 not EKS)

- OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.2.0
VERSION_ID=1745.2.0
BUILD_ID=2018-05-09-0053
PRETTY_NAME="Container Linux by CoreOS 1745.2.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux ip-###-###-###-### 4.14.39-coreos #1 SMP Tue May 8 23:19:40 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

- Install tools:
bootkube/custom

- Others:

**Comment by realAndyLuo** [comment]
@omadawn have you by any chance found the cause and solution? I have been experiencing similar issues

**Comment by omadawn** [comment]
I haven't measured it in a while. We've upgraded several times since this was opened and I haven't heard any of my customers complaining of it.
