### ISSUE TITLE
hack/verify-bazel.sh always fails on release-1.10

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#64925]
/kind bug
/sig testing
/sig release
/priority critical-urgent

```
I0608 15:49:50.952] +++ Running case: verify.bazel 
I0608 15:49:50.954] +++ working dir: /go/src/k8s.io/kubernetes
I0608 15:49:50.956] +++ command: bash "hack/make-rules/../../hack/verify-bazel.sh"
W0608 15:49:59.974] ../../internal/repos/remote.go:29:2: cannot find package "golang.org/x/tools/go/vcs" in any of:
W0608 15:49:59.975] 	/tmp/tmp.QZAPzQQRF1/go/src/github.com/bazelbuild/bazel-gazelle/vendor/golang.org/x/tools/go/vcs (vendor tree)
W0608 15:49:59.975] 	/usr/local/go/src/golang.org/x/tools/go/vcs (from $GOROOT)
W0608 15:49:59.975] 	/tmp/tmp.QZAPzQQRF1/go/src/golang.org/x/tools/go/vcs (from $GOPATH)
W0608 15:49:59.981] !!! [0608 15:49:59] Call tree:
W0608 15:49:59.983] !!! [0608 15:49:59]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
W0608 15:49:59.988] !!! [0608 15:49:59] Call tree:
W0608 15:49:59.990] !!! [0608 15:49:59]  1: ./hack/update-bazel.sh:34 kube::util::go_install_from_commit(...)
I0608 15:50:01.032] +++ exit code: 1
I0608 15:50:01.038] +++ error: 1
I0608 15:50:01.065] FAILED   verify-bazel.sh	11s
```

No PRs can be merged into release-1.10. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64848/pull-kubernetes-verify/94899/?log#log

Similar issue: https://github.com/kubernetes/kubernetes/issues/60730

/cc @ixdy

**Comment by yguo0905** [comment]
Should we cherry pick https://github.com/kubernetes/kubernetes/pull/57600 into 1.10 or just update gazelle dependency to include https://github.com/bazelbuild/bazel-gazelle/pull/228?

**Comment by BenTheElder** [comment]
@yguo0905 we've been discussing in #testing-ops on slack. @ixdy has a hack inbound for the moment.

**Comment by ixdy** [comment]
#57600 is a better long-term fix, but I'm not sure how hairy it'd be to cherry-pick into 1.10. I also don't have bandwidth to tackle that right now.

I'm working on a hacky fix, PR incoming.

**Comment by ixdy** [comment]
fortunately, release-1.9 isn't affected, since it uses a different version of gazelle (from the bazelbuild/rules_go package).

**Comment by ixdy** [comment]
hm, cherry-picking #57600 was actually less work, who would've guessed?

https://github.com/kubernetes/kubernetes/pull/64929 for that option.

**Comment by ixdy** [comment]
all fixed, and hopefully for the last time!
/close
