### ISSUE TITLE
kubeadm alpha phase certs etcd-ca fails without Internet access

### ISSUE THREAD

**Issue by mbert** [kubernetes/kubernetes#64920]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

On a system that has no Internet access, run `kubeadm alpha phase certs etcd-ca`
After a while the following error message is displayed:
```
unable to get URL "https://dl.k8s.io/release/stable-1.10.txt": Get https://dl.k8s.io/release/stable-1.10.txt: dial tcp 23.236.58.218:443: getsockopt: connection timed out
```

**What you expected to happen**:

The certificates get created

**How to reproduce it (as minimally and precisely as possible)**:

Run the command on a machine without Internet access. 

**Anything else we need to know?**:

It would probably be a good idea to introduce a global flag for setting a Kubernetes version from the command line, so that the above query can be skipped. Some kubeadm commands already provide this. 

**Environment**:
- kubeadm version 1.10.4-0

**Comment by luxas** [comment]
Hi, thanks for taking time to create this issue :wave:!
Please reopen this issue in https://github.com/kubernetes/kubeadm/issues.
Thank you!

**Comment by mbert** [comment]
Filed [new issue #960](https://github.com/kubernetes/kubeadm/issues/960)
