### ISSUE TITLE
Eviction API ignores pod UIDs

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/kubernetes#64923]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

There's no way to properly evict a specific instance of a statefulset pod when draining a node, because the pod names stay the same and eviction API only uses the pod names. For example, if I want to safely drain a node `node1` that runs an a statefulset pod `foo-0`, I'll get the current pod state and then send an eviction request to `/pods/foo-0/eviction`. However, this *always* evict any pod named `foo-0`, not necessarily the specific instance running on node `node1`, and there's a possible race if the pod was rescheduled on a different node in the mean time. Specifying the pod's `uid` in the `Eviction` metadata doesn't help.

**What you expected to happen**:

Specifying the pod's `uid` in the `Eviction` object metadata results in an error when trying to evict (409?), since the pod I'm trying to evict doesn't exist anymore.

**How to reproduce it (as minimally and precisely as possible)**:

* Deploy a statefulset `foo` to the cluster
* Fetch the `uid` of the `foo-0` pod
* Delete the pod and wait until it's rescheduled on a different node (might require tainting the node in the process)
* Try to evict the pod:

      curl -v -H "content-type: application/json" https://.../api/v1/namespaces/default/pods/foo-0/eviction -d  {
        "apiVersion": "policy/v1beta1",
        "kind": "Eviction",
        "metadata": {
          "name": "foo-0",
          "namespace": "default",
          "uid": "<old pod uid>"
        }
      }
* Observe that the pod is being deleted and rescheduled.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2

**Comment by liggitt** [comment]
the eviction object includes `deleteOptions` field, which allows specifying a uid deletion precondition:

```yaml
kind: Eviction
apiVersion: policy/v1beta1
metadata:
  name: mypod
deleteOptions:
  preconditions:
    uid: mypoduid
```
