### ISSUE TITLE
Summary API test is flaky

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#64933]
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet

It become too flaky recently since 6/5/2018.

@kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
@dashpole has been looking at the failures AFAIK

**Comment by Random-Liu** [comment]
Suspicious change https://github.com/kubernetes/kubernetes/compare/ad9722c45...bceb90cda

The cadvisor update looks especially suspicious.

**Comment by dashpole** [comment]
yes, I am testing to see if that is the cause
/assign

**Comment by BenTheElder** [comment]
FYI @jberkus @AishSundar

**Comment by dashpole** [comment]
Opened a PR for the revert.  I can look into the exact failure on monday, but if we want to unblock everyone a revert is probably best

**Comment by dims** [comment]
/priority critical-urgent

@Random-Liu @dashpole please change priority if it is not appropriate

**Comment by dashpole** [comment]
the plan is to revert the offending cadvisor PR, cut a new release, and vendor that new release.

**Comment by dashpole** [comment]
revert PR: https://github.com/google/cadvisor/pull/1959

**Comment by dashpole** [comment]
changelog for new release: https://github.com/google/cadvisor/pull/1960

**Comment by dashpole** [comment]
cadvisor version bump: https://github.com/kubernetes/kubernetes/pull/64987

**Comment by dashpole** [comment]
Just to confirm: Summary API test is no longer flaky!

**Comment by BenTheElder** [comment]
Thanks!
