### ISSUE TITLE
Mutating annotations via webhook does not work with kubectl

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#64944]
I wrote a mutating webhook that adds annotations to workloads. Adding annotations works correctly. But for deleting annotations via `kubectl apply` to work, I have to modify the last-applied-configuration annotation to apply my patch inside the mutation webhook. This seems necessary given how delete patch is generated by `kubectl apply -f`. But it will be nice/desired if this was done on server side automatically.

Also, does the serverside apply address this issue?

/sig api-machinery
/sig cli

**Comment by tamalsaha** [comment]
cc: @lavalamp @apelisse

**Comment by apelisse** [comment]
Lavalamp and I discussed about that, I don't think there is a good way to declaratively delete an element that you haven't created. I can't think of a good way to fix that, even with server-side apply.

Two ways to do it (not with apply):
- PUT: `kubectl edit` the configuration and remove it from the list,
- PATCH: `kubectl patch` to send a delete instruction on the element. I don't know how I'd do that of the top of my mind, but there must be a way to make this work :-)

**Comment by lavalamp** [comment]
It's a good question. If you find yourself needing to modify the lastAppliedAnnotation, that's a good sign you should stop and think :) Who is managing the field/annotation? You should not make things that a controller adds and then a human must remove via apply. The KRM encourages multiple editors of *objects* but not multiple editors of single fields.

So, to repeat: You can't generally use apply for removing an annotation that something else added, you'll have to use `kubectl edit` or some other mechanism.

@apelisse above is talking about us offering the feature to controllers to delete things they didn't add. This is not something you'd mix in with a normal use of apply that carries the last version of your intended state. So it doesn't help, if I understand the use case.

**Comment by tamalsaha** [comment]
> So, to repeat: You can't generally use apply for removing an annotation that something else added, you'll have to use kubectl edit or some other mechanism.

If that is the intent of apply command, it probably needs to clearly communicated. I had no idea that it is supported to be so.

**Comment by lavalamp** [comment]
Yup, we should make this clearer. Apply is intended to help you manage only
the fields you care about, by leaving other fields blank. That means it's
hard to tell the server you want to keep a field nil/empty.
