### ISSUE TITLE
Change/Remove Idle Timeout For Kubectl Eec

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#64949]
/kind feature

Kubectl exec seems to have an idle timeout which can cause issues for long-running, non-verbose apps (like silent uploads/downloads, or compression)

**What happened**:
While uploading a large file onto a server from within the container (e.g. curl -X POST localhost), there is a significant delay while my server processes the upload. It returns `100 continue` making curl wait, but during this time, kubectl exec cuts the connection

e.g.

```
time kubectl exec -itn staging staging-master 59787b9f4d-dsjjg -- tail -f /usr/local/bin/log
Working....
Done
Creating connector
HTTP/1.1 100 

HTTP/1.1 204 
Content-Language: en
Date: Sun, 10 Jun 2018 09:56:05 GMT

{"acknowledged":true}{"acknowledged":true}
Importing content
HTTP/1.1 100 

[connection cuts here]
real	5m2.578s
user	0m0.200s
sys	0m0.044s

```

**What you expected to happen**:
Be able to change the (idle?) timeout of kubectl or remove it completely

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an empty file on a container which has bash or similar shell
2. Run kubectl exec -it pod-name -- bash tail -f /path/to/file #(or possibly a long-running archiving command)
3. Wait for around 5 minutes
4. Kubectl cuts the connection

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release):
Ubuntu Artful

- Kernel (e.g. `uname -a`):
Linux ubuntu-mac 4.13.0-43-generic #48-Ubuntu SMP Wed May 16 12:18:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kops

- Others:

**Comment by liggitt** [comment]
Are you running through a load balancer? Frequently those will impose a timeout as well

**Comment by huang-jy** [comment]
Is this the api loadbalancer we are referring to?

**Comment by liggitt** [comment]
Yes, the api loadbalancer

**Comment by huang-jy** [comment]
Right, that does have an idle timeut of 5secs. I'll change that and see if that makes a difference. Thanks :)
