### ISSUE TITLE
no limit job will  led to the collapse of cluster

### ISSUE THREAD

**Issue by luzhzhsoft** [kubernetes/kubernetes#64966]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
When I create a job that will fail all the time. It will continue to create pod. Finally, it led to the collapse of my cluster when pods count is 65535.
It's horrible
**What you expected to happen**:
there need default limit to job 
**How to reproduce it (as minimally and precisely as possible)**:
 create a job that will fail all the time.and it will create new pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by wgliang** [comment]
@luzhzhsoft 
maybe you can set `BackoffLimit` do it.

**Comment by luzhzhsoft** [comment]
@wgliang 
i know it .but it's a new feature which can not run in low version kubernetes like 1.7 . i mean job need some default configuration  in case  it  make cluster crash

**Comment by jhorwit2** [comment]
@luzhzhsoft Please take a look at [this stackoverflow](https://stackoverflow.com/questions/36384873/kubernetes-job-cleanup) post covering this topic. Do the suggestions there satisfy your needs?
