### ISSUE TITLE
Kube-apiserver uses blocking /dev/random during start instead of non-blocking /dev/urandom

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#64960]
/kind bug

**What happened**:

After upgrade from linux-4.16.2 to the linux-4.17 kernel the `kube-apiserver` hanged in early start for ~3-4 minutes on node-reboot. Sub-sequent re-starts of `kube-apiserver` on the node did not hang.

After trouble-shooting (with a fair amount of guessing) I come to the conclusion that the `kube-apiserver` continued it's startup when the `/dev/random` was unblocked. I added a [virtual rng device](https://wiki.qemu.org/Features/VirtIORNG) and the problem disappeared.

But to use `/dev/random` is [not the recommended way](https://www.2uo.de/myths-about-urandom/) and it causes these kind of hangings that are unexpected and hard to understand for end users. This can well be the cause for unexplained delays at other places. A simple google search shows plenty of cases where `/dev/random` is used and why `/dev/urandom` should be used instead and is equally secure.

**What you expected to happen**:

The `kube-apiserver` would start without blocking by using `/dev/urandom`.

**How to reproduce it (as minimally and precisely as possible)**:

- Use kvm/qemu VMs with kernel linux-4.17
- Install Kubernetes on the VMs
- Make sure [virtual rng device](https://wiki.qemu.org/Features/VirtIORNG) is **not** used
- Reboot all nodes
- Monitor the kube-apiserver startup

**Anything else we need to know?**:

I could not configure the [virtual rng device](https://wiki.qemu.org/Features/VirtIORNG) to use `/dev/random` on my host because starting 6 VMs quickly drained the "entropy" on the host and I got hangings during startup still (but shorter). The trick was to bind the virtual device to `/dev/urandom` on my host.

Params to kvm/qemu;

```
-object rng-random,filename=/dev/urandom,id=rng0"
-device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000"
```

And of course the guest kernel must be configured with support for the virtual device at;

```
Character devices >
  Hardware Random Number Generator Core support >
    VirtIO Random Number Generator support 
```

I have re-built kubernetes v1.10.3 locally on Ubuntu 16.04.4 LTS to add the fix for the [ipvs-bug](https://github.com/kubernetes/kubernetes/issues/59976). Hence the `-dirty` in the version below.

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-dirty", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"dirty", BuildDate:"2018-05-31T11:08:53Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Kvm on Ubuntu 16.04.4 LTS

- OS (e.g. from /etc/os-release):
Own BusyBox test system

- Kernel (e.g. `uname -a`):
Linux vm-003 4.17.0 #2 SMP Sun Jun 10 14:58:19 CEST 2018 x86_64 GNU/Linux

- Install tools:
None

- Others:

**Comment by dims** [comment]
@uablrek would this work too? https://simpleit.us/2017/05/01/add-extra-entropy-for-ubuntu-and-debian/ (from https://github.com/kubernetes/kubernetes/issues/60751)

**Comment by uablrek** [comment]
@dims I think that is the "real thing", i.e random in HW, but I am not an expert at all on these things. But if it is HW then it is probably a good idea to use this on the host and use the virtual rng I mentioned to get it usable inside the VMs. But as many articles on the net says, /dev/urandom is sufficient in almost all cases and is not blocking.

**Comment by uablrek** [comment]
@dims Reading a bit more it seems "HAVEGE principle" uses things present on a headless VM to get entropy and, if so; Yes, it should fix the problem. (but I havn't tried).

**Comment by uablrek** [comment]
/dev/random seems to be updated in the kernel and has now caused start-up problems in [snapd](https://forum.snapcraft.io/t/snapd-service-delays-startup-in-ubuntu-18-04-with-4-15-0-24/6205). The "fix" seems to be backported to earlier kernels. I think this will cause more problem in the near future, and not only on small VMs.

**Comment by uablrek** [comment]
Numerous bug reports indicates that this is a kernel change which make /dev/urandom block for a long time. In that case the slogan of this bug report is misleading, but the problem remains and the solution. For Ubuntu "havege" is the proposed work-around.

**Comment by klausenbusk** [comment]
> Numerous bug reports indicates that this is a kernel change which make /dev/urandom block for a long time.

https://fedoraproject.org/wiki/Common_F28_bugs#boot-random-block explain it quite well.

**Comment by klausenbusk** [comment]
> But to use /dev/random is not the recommended way and it causes these kind of hangings that are unexpected and hard to understand for end users.

I assume `kube-apiserver`use the Go [`GetRandom`](https://golang.org/pkg/internal/syscall/unix/#GetRandom) function, which use the [`getrandom`](http://man7.org/linux/man-pages/man2/getrandom.2.html) syscall.

[`getrandom`](http://man7.org/linux/man-pages/man2/getrandom.2.html) can block:
> If the urandom source has not yet been initialized, then getrandom()
> will block, unless GRND_NONBLOCK is specified in flags.

**Comment by uablrek** [comment]
This seems to be a new handling of /dev/random and urandom in the Linux Kernel.
