### ISSUE TITLE
SandboxChanged events occurring for very simple jobs

### ISSUE THREAD

**Issue by PickleChops** [kubernetes/kubernetes#64978]
/kind bug

**What happened**:

SandboxChanged events occurring very often for jobs, even very simple jobs. See below.

Looks similar to #58201 but that issue died.

**What you expected to happen**:

No (or very few) SandboxChangedEvents to be raised.

**How to reproduce it (as minimally and precisely as possible)**:

Apply this in a new namespace.

```apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: jobs
  name: test-sandbox-event
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-sandbox-event
            image: busybox
            command: ["date"]
          restartPolicy: Never
```

And then watch the events. SandboxChanged occurs most job runs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):

Debian GNU/Linux 9 (stretch)

- Kernel (e.g. `uname -a`):

`Linux ip-172-20-61-35 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`

- Install tools:

KOPS 1.9.1

- Others:

Flannel v0.9.1

**Comment by filipmnowak** [comment]
Looks like flakiness related to time Job runs.

For 5 simple Jobs running true command every minute, within an hour I've got around 30 occurrences of SandboxChanged and FailedCreatePodSandBox.

For 5 simple Jobs running sleep 30, none of those Events occurred within an hour.

I tested it on k8s v1.9.1+coreos.0, deployed using Kubespray.

It appears that task finishes before k8s will consider Job Pod's SandBox container ready?
