### ISSUE TITLE
Kube-proxy in ipvs mode initiates nodeIP to 127.0.0.1 on an ipv6 cluster and crashes

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#64985]
/kind bug
/area ipv6
/sig network

**What happened**:

Even though `kube-proxy` assumes IPv6 operation it initiates the nodeIP to the ipv4 localhost address 127.0.0.1 and crashes shortly after;

```
I0611 16:36:27.921958     216 server_others.go:80] IPv6 bind address (::1), assume IPv6 operation
I0611 16:36:28.730111     216 server_others.go:183] Using ipvs Proxier.
W0611 16:36:28.773484     216 server.go:601] Failed to retrieve node info: Get http://[2000::1]:8080/api/v1/nodes/vm-003: dial tcp [2000::1]:8080: connect: connection refused
W0611 16:36:28.793311     216 proxier.go:289] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
error: unable to create proxier: clusterCIDR fd00:3000::/104 has incorrect IP version: expect isIPv6=false
```

**What you expected to happen**:

Initialize nodeIP with an ipv6 address and continue.

**How to reproduce it (as minimally and precisely as possible)**:

Start `kube-proxy` on a ipv6-only cluster before the `kube-apiserver` is ready.

**Anything else we need to know?**:

In proxy-mode=iptables it works because the initialization [differs](https://github.com/kubernetes/kubernetes/blob/e6f64d0a79243c834babda494151fc5d66582240/cmd/kube-proxy/app/server_others.go#L141-L144)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-dirty", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"dirty", BuildDate:"2018-05-31T11:08:53Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  kvm/qemu on Ubuntu 16.04.4 LTS
- OS (e.g. from /etc/os-release):
  Own BusyBox system
- Kernel (e.g. `uname -a`):
  Linux vm-003 4.16.2 #2 SMP Mon Jun 11 16:02:46 CEST 2018 x86_64 GNU/Linux
- Install tools:
  None
- Others:

**Comment by dims** [comment]
cc @leblancd
