### ISSUE TITLE
kube-controller-manager fails to start if API discovery for extended API servers fails

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#65005]
/area controller-manager
/area extensibility
/kind bug
/sig apimachinery

**What happened**:
The kube-controller-manager is unable to start when it cannot discover the APIs of API server extensions. Precisely, the `APIService` object indicated availability although the extended API server was not running anymore. Restarting the kube-controller-manager failed for the mentioned reason.

**What you expected to happen**:
The `APIService` object should not indicate availability if the respective API server is not running. Not sure if the kube-controller-manager could ignore APIs it cannot discover, what does it actually need to do with them? Actually, the only way to make the kube-controller-manager start again is to temporarily de-register the extended API, start it, and register it again.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a Kubernetes cluster, register an aggregated API server, wait for the `APIService` status to indicate availability, then delete the aggregated API server pod and restart the kube-controller-manager. It will 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.4

**Comment by liggitt** [comment]
Which control loops refused to start? Do you have the exit message handy?

**Comment by rfranzke** [comment]
Sorry, I don't have the exact message right now or know which exact controller loop didn't start. As far as I remember it was something like `Error from server (ServiceUnavailable): the server is currently unable to handle the request (get serviceclasses.servicecatalog.k8s.io)` and then it terminated.
If that's not enough information to debug that please feel free to close the issue; i'll re-open it with more details as soon as I encounter the problem again.

**Comment by nivedhan-murugavel** [comment]
@rfranzke Did you find solution for the above issue?

**Comment by rfranzke** [comment]
@nivedhan-murugavel One way to fix this was to temporarily delete the `APIService` object registering the service-catalog extension, restart the kube-controller-manager, and then re-create the `APIService` object.

**Comment by liqlin2015** [comment]
Got the same issue with kubernetes 1.11.1.

```
E0801 11:14:13.999135       1 controllermanager.go:461] Error starting "resourcequota"
F0801 11:14:13.999155       1 controllermanager.go:174] error starting controllers: failed to discover resources: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
```

Also see issue https://github.com/kubernetes/kubernetes/issues/59826. In my case, resource quota controller should ignore error when try to discover quotalable resources.
