### ISSUE TITLE
If a cronjob fails, the corresponding pod isn't deleted. It repeats for every new pod. 

### ISSUE THREAD

**Issue by vineetchawla** [kubernetes/kubernetes#65010]
/kind bug
/sig bugs

**What happened**:
I created a cronjob using an example to echo "Hello world" every minute. Works perfectly.
If instead I replace the function to be called to wget with an unreachable website, the new pods keep being created and the older ones aren't deleted. 
<img width="1329" alt="screen shot 2018-06-12 at 10 32 19" src="https://user-images.githubusercontent.com/1390884/41279141-f3a47c08-6e2b-11e8-8939-38b7faaeb0c7.png">

**What you expected to happen**:
I expected that once the pod for the job fails it should be deleted. 

**How to reproduce it (as minimally and precisely as possible)**:
kubectl run hello --schedule="*/1 * * * *" --restart OnFailure --image busybox -- /bin/wget www.asdf.asdf

**Anything else we need to know?**:
I just used the wrong website as an example to create cronjob failure. Any other command that fails results in the same issue

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.6
- Cloud provider or hardware configuration: minikube 1.9
- OS (e.g. from /etc/os-release): Mac high sierra
- Kernel (e.g. `uname -a`): darwin kernel 17.3.0
- Install tools:
- Others:

**Comment by CaoShuFeng** [comment]
> I expected that once the pod for the job fails it should be deleted.

Maybe try `--restart=Never`

**Comment by CaoShuFeng** [comment]
FYI:

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-termination-and-cleanup

The doc said:
> When a Job completes, no more Pods are created, but the Pods are not deleted either. Keeping them around allows you to still view the logs of completed pods to check for errors, warnings, or other diagnostic output.

**Comment by jhorwit2** [comment]
/sig apps
/kind bug

@vineetchawla can you please paste the output of `kubectl get cronjob hello -oyaml`. I'm going to take a guess you're not using the version of cronjobs that defaults the history limit, thus it's keeping an infinite amount.

**Comment by vineetchawla** [comment]
![screen shot 2018-06-12 at 13 01 43](https://user-images.githubusercontent.com/1390884/41286764-eb8d0bec-6e40-11e8-929f-4ece0361189a.png)
@jhorwit2 Here is the output
@caesarxuchao I tried the restart policy onFailure as well as never. Behaviour stays the same.

**Comment by caesarxuchao** [comment]
I see the `failedJobsHistoryLimit` is set to 1. It seems to be wrong that the failed jobs were not cleaned up. Not sure if it's a known bug in 1.8.6. @janetkuo might have more context.

**Comment by janetkuo** [comment]
A Job can only become `Failed` when it has `.spec.backoffLimit` set and has hit the limit. 
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

My theory is that you probably don't have this field set in your Job, so it never actually failed. 

To further confirm, you can do something like this: 
```
$ kubectl get jobs <job-name> -o json | jq '.status.conditions'
```

A failed job should return something like this:
```
[
  {
    "lastProbeTime": "2018-10-10T18:35:58Z",
    "lastTransitionTime": "2018-10-10T18:35:58Z",
    "message": "Job has reached the specified backoff limit",
    "reason": "BackoffLimitExceeded",
    "status": "True",
    "type": "Failed"
  }
]
```

**Comment by janetkuo** [comment]
Closing as this is expected behavior because the Jobs never `Failed` (its Pods terminated with error doesn't mean the Jobs has `Failed`), see https://github.com/kubernetes/kubernetes/issues/65010#issuecomment-428685223.
