### ISSUE TITLE
Minikube with Mysql persistent volume tutorial fails 

### ISSUE THREAD

**Issue by ishaibin** [kubernetes/kubernetes#65017]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig docs
> /kind feature

**What happened**:
I ran the tutorial of running local mysql with minikube 
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
With its own persistent volume , when trying to create the persistent volume with 
kubectl create -f https://k8s.io/docs/tasks/run-application/mysql-pv.yaml
It fails and says :
```
minikube start --vm-driver=virtualbox
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

kubectl config use-context minikube
Switched to context "minikube"

kubectl create -f https://k8s.io/docs/tasks/run-application/mysql-pv.yaml
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
**What you expected to happen**:
The tutorial should succeed end to end with minikube and mysql with persistent volume attached to it 
up and running .
**How to reproduce it (as minimally and precisely as possible)**:
Please try to run the mysql with persistent volume tutorial 
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
On Linux Mint 18.3 , latest K8s - 1.10 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.10.3
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): 
AME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"

- Kernel (e.g. `uname -a`):
4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by CorentinDy** [comment]
Maybe this can help [#63128](https://github.com/kubernetes/kubernetes/issues/63128)?
