### ISSUE TITLE
SharedInformer documentation is missing or hard to find

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#65036]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I cannot find documentation on the correct way to use informers & shared informers. Without guidance, I ended up writing code that called `"k8s.io/client-go/informers/core/v1".NewPersistentVolumeInformer` (and some others). Although I read the docstring of that method, it was only through conversation with a more experienced contributor that I learned I should instead be calling `"k8s.io/client-go/informers".(*sharedInformerFactory).Core().V1().PersistentVolumes().Informer()`

I also had difficulty understanding whether I needed to call `Run()` on each informer, or on the informer factory. The correct answer turns out to be
`"k8s.io/client-go/informers".(*sharedInformerFactory).Start()`
but that was not apparent from the godoc as `Start()` comes from an embedded interface which I didn't notice.

EDIT: Calling `Start()` before creating informers in the factory results in those informers never generating events. I suppose this means that one should never call `Start()` until all informers have been created? Not sure.

**What you expected to happen**:
There should be a doc somewhere that says, "To use a shared informer, make a factory and call `Start()` on it." and that doc should be easy to find.

/sig api-machinery

**Comment by misterikkit** [comment]
Hi, it also seems like there is no documentation on how to use https://godoc.org/k8s.io/client-go/testing#Fake. (What is a reactor and what is an action?) Should I file a separate issue?

**Comment by nikhita** [comment]
> Should I file a separate issue?

Yes, please create a separate issue for now. :+1: 

Though in the future, we should probably create an umbrella issue for all such client-go topics which are in dire need of docs. :)

**Comment by misterikkit** [comment]
/remove-lifecycle stale

This is still on my list of things to look at.

**Comment by misterikkit** [comment]
/remove-lifecycle stale

I will die on this hill.

**Comment by codeblooded** [comment]
😭 -- is there any way we could reopen this? I struggled to find documentation on the informer factories. I learned how to use them from some blog posts on Medium.

**Comment by misterikkit** [comment]
/reopen

I agree, we don't have adequate docs on how to properly use informers. Proper testing of code that relies on informers is even trickier, and has less documentation.

**Comment by pohly** [comment]
@misterikkit do my changes in https://github.com/kubernetes/kubernetes/pull/112200 address your concerns regarding the documentation?

**Comment by misterikkit** [comment]
> @misterikkit do my changes in #112200 address your concerns regarding the documentation?

OMG very yes. <3 I'd say it's fair to close this.
