### ISSUE TITLE
Enable customize root CA

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#65048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
Currently, we are using easyrsa to generate root CA for kubernetes at https://github.com/kubernetes/kubernetes/blob/master/cluster/centos/make-ca-cert.sh#L69 , it is suggested that we should enable customer use their own root CA.

/sig security

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
all of the certificates used by kubernetes are able to be overridden and provided via trust bundles. was this issue related to a specific deployment method?

**Comment by gyliu513** [comment]
@liggitt

We are now using https://github.com/kubernetes/kubernetes/blob/master/cluster/centos/make-ca-cert.sh#L69  , but this script currently do not support generating server.key and server.cert based on customized ROOT CA.

Shall we make some enhancement to this script to support this? Or does Kubernetes has some build-in script that I can use?

**Comment by liggitt** [comment]
> Shall we make some enhancement to this script to support this? Or does Kubernetes has some build-in script that I can use?

I see. I wouldn't anticipate adding support for arbitrary root CAs to kube deployment scripts. The intersection of users with existing root CAs they care about who are also willing to hand over signing material for that CA to a kube deployment script is vanishingly small

/close
