### ISSUE TITLE
Failed to attach volume after upgrading from 1.9.3 to 1.9.6

### ISSUE THREAD

**Issue by ysaakpr** [kubernetes/kubernetes#65047]
/kind bug

**What happened**:
Deployment failed with error as below, where i verified the existence of pv and pvc as required. This was working all fine till i migrate kubelet v to 1.9.6 from 1.9.3. And i tried the downgrading kube version back 1.9.3 but error still exists.

> Unable to mount volumes for pod "jenkins-x-nexus-57866468c9-w6gf8_jx(81e2d10a-6ed6-11e8-9b4e-0209db2ce386)": timeout expired waiting for volumes to attach/mount for pod "jx"/"jenkins-x-nexus-57866468c9-w6gf8". list of unattached/unmounted volumes=[nexus-data-volume]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: kube controller manager log. Which is releasing the attachment entry..i believe the issue is because of that.

> June 13th 2018, 12:31:58.170 | kube-controller-manager | Releasing in-process attachment entry: bk -> volume vol-016290ac6df275357
> -- | -- | --
> 
>   | June 13th 2018, 12:31:58.170 | kube-controller-manager | AttachVolume.Attach succeeded for volume "pvc-22b72bf7-6007-11e8-b31a-024d3ab43642" (UniqueName: "kubernetes.io/aws-ebs/aws://ap-south-1b/vol-016290ac6df275357") from node "ip-172-20-82-78.ap-south-1.compute.internal"
> 
>   | June 13th 2018, 12:31:47.982 | kube-controller-manager | Waiting for volume "vol-016290ac6df275357" state: actual=attaching, desired=attached
> 
>   | June 13th 2018, 12:31:47.874 | kube-controller-manager | AttachVolume volume="vol-016290ac6df275357" instance="i-0ec9961c7747720f5" request returned {   AttachTime: 2018-06-13 07:01:47.877 +0000 UTC,   Device: "/dev/xvdbk",   InstanceId: "i-0ec9961c7747720f5",   State: "attaching",   VolumeId: "vol-016290ac6df275357" }
> 
>   | June 13th 2018, 12:31:47.582 | kube-controller-manager | Assigned mount device bk -> volume vol-016290ac6df275357
> 
> 

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kops, Version 1.9.0 (git-cccd71e67)
- Others:

**Comment by dims** [comment]
/close 

since #49926 is still open, let's track any discussion there
