### ISSUE TITLE
What file system can be mount into windows container?

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#65060]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
All my vms are deployed on **Azure**. and I create a nfs server , as well as pv and pvc based on that. I am sure above step works. However, when I try to mount this nfs into a  pod who contains windows container, it occurs an error:
`azureMount: only cifs mount is supported now`
Then I check the code in https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_windows.go
and found this words have been hard-coded.

I know maybe it's not a bug but a block way, but just want to ask:
1.If this behavior only happens on Azure vm?
2. If not, what fie system(s) is supported to mount into windows container till now? Actually I didn't found any doc which can clarify this question
 3. If above question hard to answer, just want to double-check : Can Azure Disk or Azure File be mounted into Windows container?
4. Any further planning to support this?
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Any time you mount a nfs into windows container via pv/pvc (on Azure)
 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):  K8S Master/Nfs server : CentOS7.3, Windows Container: winservercore1709 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Cherishty** [comment]
@kubernetes/sig-Windows-bugs
@kubernetes/sig-Storage-bugs
/sig volume-mount

**Comment by ddebroy** [comment]
@Cherishty you should be able to use Azure FileStorage from Windows containers on Azure. You need to make sure the access key for accessing the Azure Storage Account (backing the Azure FileStorage objects) is properly configured as a secret in Kubernetes. If you want to do basic/static storage provisioning you should be able to just create the FileStorage objects in the Storage Account, create corresponding PVs (and PVCs) for them of type AzureFile and get the storage mounted over SMB to the Windows pods. If you want dynamic provisioning using a storage class, you need to make sure a proper azure.json is provided to the Azure cloud provider with your SP details for management operations on Azure.

**Comment by andyzhangx** [comment]
k8s on windows now only supports smb mount(azure file) and disk mount, nfs mount is not supported, you could find details about why nfs mount is not supported on windows here: https://github.com/kubernetes/kubernetes/issues/56188

**Comment by andyzhangx** [comment]
You could find azure file & azure disk mount examples here: 
https://github.com/andyzhangx/demo/tree/master/windows
Just let me know if you have any question.

**Comment by Cherishty** [comment]
I will try , great thanks for your contribution and kindly help! 👍
