### ISSUE TITLE
Latter gofmt behaviors changed, and will influence the whole repo

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/kubernetes#65079]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
I am using devel go, and my formatter formats the files I edited, I found the latest gofmt changed it's behavior, which will influence the whole repo's formatting.
**What you expected to happen**:
After the k8s builder upgrade go, format the whole repo.
**How to reproduce it (as minimally and precisely as possible)**:
Using latest go version gofmt.

**Anything else we need to know?**:
I tried to format the whole repo, it influence `vendor` packages, maybe pipeline need to skip vendor dir format checking.
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
the version of gofmt used by the go version being used to build (currently 1.10.1, I think) is verified by CI. gofmt is rerun as part of updating go versions. see https://github.com/kubernetes/kubernetes/pull/60599

/close
