### ISSUE TITLE
fully qualified account names are undocumented

### ISSUE THREAD

**Issue by ensonic** [kubernetes/kubernetes#65085]
/kind bug

**What happened**:
See #62361

**What you expected to happen**:
If using fully qualified account names in messages such as
```
Error: error when upgrading: deployments.extensions "tiller-deploy" is forbidden: User "system:serviceaccount:default:helm" cannot get deployments.extensions in the namespace "kube-system": Unknown user "system:serviceaccount:default:helm"
```
document somehwere what each component means, e.g. `???:<account-type>:<namespace>:<name>`.

**How to reproduce it (as minimally and precisely as possible)**:
I am trying to make helm work with rbac (according to https://github.com/kubernetes/helm/blob/master/docs/rbac.md).

**Anything else we need to know?**:
Ideally kubectl could show the qualified name too. If the user would actually be unknown, why can I do:
``` shell
$ kubectl describe serviceaccount helm
Name:         helm
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"helm","namespace":"default"}}

...
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE

**Comment by liggitt** [comment]
That string is actually at the user name as seen by the authorization layer. Service accounts happen to follow a particular format, but external authentication sources can put arbitrary content in that user name string

**Comment by liggitt** [comment]
The unknown user message is coming from GKE's authorizer, which authorizes based on IAM permissions and isn't aware of kubernetes service accounts. 

Improving the forbidden message when multiple authorizers are configured is tracked in https://github.com/kubernetes/kubernetes/issues/52279

/close
