### ISSUE TITLE
Kubernetes is not yet tested with Docker 17.12.1 (default in Ubuntu 18.04 LTS "Bionic")

### ISSUE THREAD

**Issue by MarkusTeufelberger** [kubernetes/kubernetes#65089]
/kind feature

**What happened**:

Kubernetes is not tested with current Docker versions, specifically the one in Ubuntu 18.04 LTS (17.12.1, see https://packages.ubuntu.com/bionic/docker.io)

**What you expected to happen**:

e2e tests being run for Docker 17.12.1 at least, ideally also for 18.03

**How to reproduce it (as minimally and precisely as possible)**:

Check https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/docker_validator_test.go for the versions that are tested.

**Anything else we need to know?**:

See https://github.com/kubernetes/kubernetes/pull/52666 for an example of a previous PR that added a new Docker version to e2e tests.

See https://docs.docker.com/release-notes/docker-ce/ for a list of current stable releases.

**Comment by MarkusTeufelberger** [comment]
I'm not 100% sure which sig this should go to (node? testing?), so I'm letting someone else tag this...

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/53221

**Comment by MarkusTeufelberger** [comment]
https://github.com/kubernetes/kubernetes/pull/68495 seems related too.

**Comment by CalvinHartwell** [comment]
Hi @sebastiansirch, @MarkusTeufelberger, @dims @haraldschilly, 

I've just noticed this is an issue and I've let our developers know (I work for Canonical), though they may already be aware of this. @tvansteenburgh @kwmonroe @ktsakalozos. 

Cheers,

- Calvin

**Comment by MarkusTeufelberger** [comment]
The location of the docker version checks have changed since this bug was filed btw. - but it might be as "simple" as adding a few lines or editing a regex in the test suites. I'm not deep enough into k8s internals and testing procedures to know for sure, but I hope that someone who is will update the versions of Docker that k8s is being run and tested against.

**Comment by MarkusTeufelberger** [comment]
According to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md

> The list of validated docker versions remain unchanged at 1.11.1, 1.12.1, 1.13.1, 17.03, 17.06, 17.09, 18.06 since Kubernetes 1.12. (#68495)

This means that newer and older Docker versions than 17.12 are being tested, but not the one in Bionic. Bionic-updates (18.06) however should work, so there's that...

I'd still like to see Kubernetes being tested with Docker 17.12 though.

**Comment by MarkusTeufelberger** [comment]
Meanwhile Ubuntu Bionic installs Docker 18.06 by default (https://packages.ubuntu.com/bionic/docker.io)

/close
