### ISSUE TITLE
An option to exclude kube-proxy for kubeadm init

### ISSUE THREAD

**Issue by yamt** [kubernetes/kubernetes#65086]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
Our network backend (https://github.com/midonet/midonet-kubernetes) has a replacement
of kube-proxy. After "kubeadm init", we need to disable kube-proxy and clean up its iptables rules manually.  See step 3. and 4. in https://github.com/midonet/midonet-kubernetes/tree/7f0ef03a2b1bcedd4a3e760a6f4beafe25e0da5d#how-to-deploy

**What you expected to happen**:
I want to see an option for kubeadm not to set up kube-proxy. It would make our deployment steps with kubeadm more straightforward.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
OpenStack VM
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux k 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Others:

**Comment by yamt** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by dixudx** [comment]
@luxas Are we going to support this?

**Comment by detiber** [comment]
@dixudx @luxas I think it is a valid feature request

**Comment by luxas** [comment]
Yes, it's a valid feature request and I think we should do it, but the issue is in the wrong repo.
Please reopen in kubernetes/kubeadm, thanks!

**Comment by yamt** [comment]
@luxas filed on the repo. thank you.
https://github.com/kubernetes/kubeadm/issues/919
