### ISSUE TITLE
HorizontalPodAutoscaler: Possible to limit scale down?

### ISSUE THREAD

**Issue by frankh** [kubernetes/kubernetes#65097]
HPA seems to have a pretty big problem with spiky loads. In my case, I want to use it for a service which has large bursts of traffic in quick succession. The problem is that after it scales up (correctly), it will scale down to the minimum if there's low load for just 5 minutes.

I want to control it to only scale down by a maximum of 1 or 2 containers every scale event, is that possible?

**Comment by hongshibao** [comment]
Looking into the code, I think it is not supported now. I also need this feature in my application usage. @DirectXMan12 Can we have this feature added?

**Comment by hongshibao** [comment]
@mwielgus

**Comment by frankh** [comment]
I've made a very hacky workaround, I have a cronjob that runs every 3 minutes, and sets the minimum replicas on an HPA to `$currentReplicas - $downscaleLimit`. If anyone feels like using it it's here: https://gist.github.com/frankh/050943c72273cf639886b43e98bc3caa (but I wouldn't trust it in production)

**Comment by hongshibao** [comment]
@frankh I think this feature is useful, especially when it is expensive to scale up pods (e.g. initialzation of a pod takes much CPU resource). For such case, I perfer not to scale down pods so aggressively.

**Comment by ericjee** [comment]
hey guys, any update on this user case?

**Comment by DirectXMan12** [comment]
we merged a change to the scale down process that should leave it slightly less prone to spike-y ness.  Has that helped at all?

**Comment by frankh** [comment]
@DirectXMan12 could you link to the specific change?

**Comment by DirectXMan12** [comment]
it's the sliding window change.  The commit is 958cba1c82e39dbbd25600128b9041660f80afc8, and has a link to a doc with more info as well

**Comment by gliush** [comment]
@frankh: I'm working on the RFC to add some configuration parameters into the HPA. will the following RFC fix your issue?
https://docs.google.com/document/d/1Su2tzHEtjc7_orTVbKZEhSFGWiHk16JqA4Z7zJU2oNs/edit

**Comment by DirectXMan12** [comment]
cc @mwielgus ^

**Comment by frankh** [comment]
@gliush yeah that would be great

**Comment by max-rocket-internet** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/39090
