### ISSUE TITLE
Upgrade GlusterFS client to 4.0 in hypercube

### ISSUE THREAD

**Issue by mweichert** [kubernetes/kubernetes#65093]
I cannot mount volumes from a Gluster server running the latest stable release of Gluster, 4.0 as I get the following error:

`Server is operating at an op-version which is not supported`

It appears that glusterfs-client and glusterfs-common are out-of-date by 5 minor versions, and one major version in hypercube.

**Kubernetes version** (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Environment:**

-  **Cloud provider:** GKE
-  **OS**: Ubuntu 16.04.4 LTS
-  **Kernel:** gke-imagely-hosting-default-pool-1fdf6b0c-353m 4.13.0-1015-gcp

**Anything else we need to know:**

For now I'm manually upgrading by logging into each node and executing:

`cd /home/kubernetes/containerized_mounter/`
`sudo chroot rootfs /bin/bash`
`apt-get update`
`apt-get install software-properties-common`
`add-apt-repository ppa:gluster/glusterfs-4.0`
`apt-get update`
`apt-get install glusterfs-client`

Please consider upgrading these tools for interoperability with newer Gluster volumes.

**Comment by mweichert** [comment]
Related: #43069

**Comment by mweichert** [comment]
Any other info I can provide?

**Comment by warmchang** [comment]
/sig-storage-misc

@mweichert , Need to discuss the following points:

- GlusterFS 4x is the latest version, but not stable, is all the interfaces compatible with 3.x?
- With the GA of CSI (now is beta), is it still necessary to continue to update/maintain the storage plugin's hard-codes in K8S?

What's your opinion? @saad-ali

**Comment by mweichert** [comment]
@warmchang, 

Gluster 4.1 is now considered the only stable release of Gluster. Please see here: https://www.gluster.org/release-schedule/

The gluster client tools (which is what we are talking about here) ARE compatible with gluster 3x volumes. That is, gluster 4x client can mount Gluster 3x volumes.

**Comment by warmchang** [comment]
@mweichert 

According to the description of [this page](https://www.gluster.org/install/), the 4.x is not stable version.

But anyway, the new version (4.x) is the future trend, and if this fix does not lead to compatibility issues, I have no opinion.
