### ISSUE TITLE
kubeadm : Pods on new cluster nodes are not able to communicate any external ip or port

### ISSUE THREAD

**Issue by anupam4881** [kubernetes/kubernetes#65096]
**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  Intel 
- OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`): Linux TPSERVER102 3.10.0-327.4.4.el7.centos.plus.x86_64 #1 SMP Wed Jan 6 00:35:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 

--------------------------------------------------------------------------------------

We installed & configure kubeadm ,Kubernetes latest version cluster.

Centos version: 7.5.1804
Kubeadm version:  kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3",

Initial Setup: Initial we setup two node system one master & one node, it  works perfectly, able to create pod & service which can  communicate to all external ip & port 

Issue:        Now add new nodes in existing cluster with new token  (create fresh token as old one was 
              expired)  and create pods service.  Now no pods is routing traffic outside all telnet are getting timeout ...................and this is happening every time with every new nodes. 

From Node-B: I am not able to telnet any ip /external URL.
From Node-A: I am able to telnet any ip

Node-A: working from all pods 
[jboss@alt-mobile-6c4c448446-545fq jboss]$ telnet  10.225.241.184 1433
Trying 10.225.241.184...
Connected to 10.225.241.184.
Escape character is '^]'.
^]

[jboss@alt-mobile-6c4c448446-545fq jboss]$ traceroute 10.225.241.184
traceroute to 10.225.241.184 (10.225.241.184), 30 hops max, 60 byte packets
 1  gateway (10.43.224.1)  0.101 ms  0.024 ms  0.021 ms
 2  tpserver149.psnet.com (10.225.241.184)  0.413 ms * *

Node-B :   Nothing work ( new nodes join with new token) 
 
[jboss@al-mobile-6c4c448446-j65jq ~]$ traceroute 10.225.241.184
Trying 13.126.198.64...

[jboss@al-mobile-6c4c448446-j65jq ~]$ traceroute 10.225.241.184
traceroute to 10.225.241.184 (10.225.241.184), 30 hops max, 60 byte packets
 1  * * *

Kindly help to find this kubernetes pod routing issue.

Regards
Anupam Narayan

**Comment by anupam4881** [comment]
Kindly let me know if some information or commond output  is required from my end.

Regards
Anupam Narayan

**Comment by anupam4881** [comment]
is there any update ?

**Comment by anupam4881** [comment]
Issue resolved , this is happening with machines which was previously updated via yum update. 

when below error comes than only pods on below nodes did n't work 
[preflight] Some fatal errors occurred:
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1

even after set value to 1 , there is no impact. 

Thanks 
Anupam

**Comment by nomaed** [comment]
@anupam4881 so how did you resolve this on machines that had this issue?
