### ISSUE TITLE
Dynamic Auth Webhook

### ISSUE THREAD

**Issue by thephred** [kubernetes/kubernetes#65109]
/kind feature
/sig auth
/sig api-machinery

# Overview
The kubernetes authentication and authorization webhooks rely on a config file for which a path is passed to the apiserver as a flag on startup. I would like the ability to dynamically configure authentication and authorization webhooks by creating, updating and deleting kubernetes resources through the kubernetes API.

With this a privileged cluster admin could configure authentication and authorization webhooks conveniently and dynamically without having to interact with files on a filesystem and rebooting the api server. Another scenario enabled would be being able to configure authentication and authorization on hosted kubernetes environments like GKE or EKS where without being able to configure dynamically one is unable to configure them at all.

# Suggested API
A user with proper rights (RBAC `system:auth-delegator` maybe) is able to list/get/create/update/delete two new resources `AuthenticationWebhook` and `AuthorizationWebhook` which both provide the same info that the current webhook config file as well as an order for ordering evaluation of the dynamic webhooks.

The existing webhooks from the arguments to the api-server will not be in this system and will be considered independent (although they may share the same code to execute the webhooks).

```kind: AuthenticationWebhook
apiVersion: ...
metadata:
  name: my-custom-authn
spec:
    order: 5 # A number used to sort the webhooks into an order used for evaluation
    certificateAuthority: … # Contains the base64 encoded certificate authority of the server
    server: https://authn.example.com/authenticate
    clientCert: … # Contains the base64 encoded client certificate
    clientKey: secret-name # The name of a secret that contains the client key.
```

```kind: AuthorizationWebhook
apiVersion: ...
metadata:
  name: my-custom-authz
spec:
    order: 3 # A number used to sort the webhooks into an order used for evaluation
    certificateAuthority: … # Contains the base64 encoded certificate authority of the server
    server: https://authn.example.com/authenticate
    clientCert: … # Contains the base64 encoded client certificate
    clientKey: secret-name # The name of a secret that contains the client key.
```

# Goal
I would like to get feedback and aim to contribute the code to enable this feature targeting release in kuberenetes 1.12

**Comment by liggitt** [comment]
xref #52511 https://github.com/kubernetes/community/pull/1458

@kubernetes/sig-auth-feature-requests 

I think the use case for dynamic admission is much clearer than for this. In many hosted environments, control over authn/authz is reserved for the cluster operator

**Comment by bassam** [comment]
Thanks for the cross reference -- we did not see it previously.

> I think the use case for dynamic admission is much clearer than for this.
We'd be happy to share use cases as part of the design proposal.

>  In many hosted environments, control over authn/authz is reserved for the cluster operator
Are you that if dynamic authn/authz existed today, cluster operators would generally want to disable it?

**Comment by liggitt** [comment]
> Are you that if dynamic authn/authz existed today, cluster operators would generally want to disable it?
 
Specifically with respect to "being able to configure authentication and authorization on hosted kubernetes environments like GKE or EKS where without being able to configure dynamically one is unable to configure them at all", yes, I would not expect most providers to allow/enable this

**Comment by bassam** [comment]
> I would not expect most providers to allow/enable this

Can you please elaborate as to why? Is there a technical/security concern here, lack of interest from customers in the feature, does it conflict with business model for GKE/EKS, or something else?

**Comment by yliaog** [comment]
it is mostly security reason, i think.

**Comment by filmil** [comment]
tl;dr: @liggitt is right, please reread until you understand his words. :)

Hi folks.  Since I was in this boat some months ago, I feel obliged to put in a word, hopefully before you sink too much time into this. See https://github.com/kubernetes/community/pull/1458 for details.

What we discovered is that there is a very deep well of issues to be fixed with authorizers in particular for this to be a tenable proposal. Dynamic authz is deceptively similar to a dynamic admission controller which is already implemented, so I get that you'd wonder why there is pushback.

But if you dig a a bit, they are very different.  Root cause is I think that authorizers are very powerful. An "always admit" admission controller as the worst case of a "buggy" admitter will do no harm; but an "always admit" authorizer opens up gates of hell. This means cluster operators will be reluctant to deploy your authZ, limiting the reach of whatever you are trying to build.

So before you sink time into this, consider alternative approaches.

**Comment by liggitt** [comment]
> This is logically equivalent to, say, GKE exposing the ability to set an authz webhook via their proprietary api.

Not quite. Being able to control the authentication layer via the API undermines auditability that is based on the authentication layer being authoritative and trustable. With dynamic authorizer config, you would still know *who* was performing actions on your cluster. With dynamic authenticator config, you wouldn't.

Unioning multiple remote authentication methods behind the scenes also leads either to:
* potentially exposing presented user credentials to multiple remote authenticators incorrectly (c.f. https://github.com/kubernetes/kubernetes/issues/12316)
* bleeding the authentication configuration out to end users so they can indicate what backend provider their credential should be presented to

> The use case for us is wanting to use GitHub (or other OIDC) credentials across GKE/EKS/AKS and other managed Kubernetes clusters in a uniform way. We're working with the assumption that the customer should decide what authz approach to use and not the cloud provider.

In my experience, this is usually a collaboration between the host and the customer, done in a way that preserves the host's ability to maintain cluster integrity, stability, and auditability. I'd be interested to hear the perspective of some of the providers you mentioned on the prospect of their managed clusterrs having a mix of trusted and unknown self-service authentication providers.

**Comment by bassam** [comment]
@liggit sorry for the confusion, I meant authn in the following:

> This is logically equivalent to, say, GKE exposing the ability to set an authn webhook via their proprietary api.

In other words setting an authn webhook dynamically vs. via an api-server config are logically equivalent. Do you agree?

I agree completely with your points about vulnerabilities exposed by setting a bad/malicious authn webhook. This is why enabling this requires cluster_admin privs.

> In my experience, this is usually a collaboration between the host and the customer, done in a way that preserves the host's ability to maintain cluster integrity, stability, and auditability.

I would assume that this feature would be behind a feature gate.

>  I'd be interested to hear the perspective of some of the providers you mentioned on the prospect of their managed clusters having a mix of trusted and unknown self-service authentication providers.

Agree. It's best to not speculate.

**Comment by infinitecompute** [comment]
@liggitt Curious as to hear your thoughts on the Bassam's last post?

**Comment by liggitt** [comment]
I think it is probably lowest on the list of dynamic extension point APIs we would consider (admission, audit, and authorization all seem more likely to be used broadly).

If a hosted provider wanted to allow dynamic registration of authentication providers, they could do so today with a `apiserver -> delegating webhook authenticator -> n webhook authenticators` setup, driven via a custom resource registration API. Experimenting with this feature using the existing extension mechanisms would be my recommendation to begin with.

**Comment by mattmoyer** [comment]
@liggitt Prototyping this out of tree sounds like a great plan. It would let us iron out the API and better understand the performance, reliability, and security implications.

I think a lot of the long term value, though, comes from having a standard way of doing this across clusters, which feels like something that eventually belongs in-tree. Would you agree?

**Comment by erikwilson** [comment]
I have been running into similar issues with trying to figure out how to setup custom authentication to GKE/EKS/AKS clusters, but since these providers are likely using webhook authentication themselves to provide normal user access there is no way for me effectively do the same. I doubt they have little incentive to provide a delegating webhook service since they want you to use their own auth providers, but if there was a safe and effective way built in I don't think they would disable it either.

Having said that why is there no way to authenticate normal users using resources on the cluster, similar to how service accounts are managed? I wrote my own authentication service which accesses custom resources on the cluster for user data (username/groups etc) and hashed auth tokens, and runs in the cluster to provide authentication, with a separate service to sync auth changes to the cluster, however of course this won't work on most managed Kubernetes solutions.

If we were able to effectively namespace tokens to an appropriate authentication webhook that might work too, helping avoid the problem of trying many services and exposing credentials to things we shouldn't.
(also see https://github.com/kubernetes/kubernetes/issues/65874)

**Comment by liggitt** [comment]
> I have been running into similar issues with trying to figure out how to setup custom authentication to GKE/EKS/AKS clusters, but since these providers are likely using webhook authentication themselves to provide normal user access there is no way for me effectively do the same. I doubt they have little incentive to provide a delegating webhook service since they want you to use their own auth providers, but if there was a safe and effective way built in I don't think they would disable it either.

I would not expect managed environments like those to be willing to give up reliable identity for the reasons described in https://github.com/kubernetes/kubernetes/issues/65109#issuecomment-400902647

**Comment by erikwilson** [comment]
> I would not expect managed environments like those to be willing to give up reliable identity for the reasons described in [#65109 (comment)](https://github.com/kubernetes/kubernetes/issues/65109#issuecomment-400902647)

I am not entirely sure what you mean by reliable identity, I would imagine storing identity information in the cluster to be fairly reliable and auditable, and namespacing tokens to webhook auth could prevent information leakage and also provide an auditable log.

The managed clusters should exist to make deploying and using Kubernetes easier, when the management system necessarily limits customer accessibility then the provider or customer are forced to come up with weird work-arounds.
