### ISSUE TITLE
Deleting a Namespaced Job returns different response types depending on the options in the request

### ISSUE THREAD

**Issue by benperez** [kubernetes/kubernetes#65121]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I submitted a `DELETE` request for a namespaced job resource to the kubernetes API. It returned a response of `"kind": "Job"`

**What you expected to happen**:
I expected a `"kind":"Status"` response per the [API docs for the delete resource](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#delete-41)
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a namespaced job.
2. Delete the job. Do not include the `orphanDependents` field in the request body.

**Anything else we need to know?**:
For some reason, including the `orphanDependents` field of `V1DeleteOptions` in the request body causes the API to return the the correct type `Status`. The incorrect type (`Job`) seems to be returned otherwise.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):  
```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-20-32-203 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by benperez** [comment]
One more piece of info:

specifying `orphanDependents: True` causes the `Job` to be returned, specifying `orphanDependants: False` causes the `Status` to be returned.

**Comment by roycaihw** [comment]
This is a known issue caused by lacking of `OneOf` support for types that set `ReturnDeletedObject: true` in their storage configuration. We cannot specify multiple schema for returned object in our spec until we support OpenAPI v3. Ref https://github.com/kubernetes/kubernetes/issues/60937. Closing

/close
