### ISSUE TITLE
Ambiguity to find pod specific watch api endpoints in e2e test suite

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#65133]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
1. In order to watch individual changes to a list of Pod, [Kubernetes api reference v1.10](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#watch-list-65) says that HTTP request should be made to endpoint `GET /api/v1/watch/namespaces/{namespace}/pods` but while executing e2e tests it is found that **Watch Function** on Pod is hitting api-endpoint `GET /api/v1/namespaces/{namespace}/pods`

2. While executing e2e test suit `GET /api/v1/watch/namespaces/{namespace}/pods` endpoint is never observed.

**What you expected to happen**:
Watch function should make request to `/api/v1/watch/namespaces/{namespace}/pods` endpoint with `GET` HTTP verb to watch individual changes to a list of Pod. (based on API reference documentation) or Documentation needs correction based on observed endpoint `/api/v1/namespaces/{namespace}/pods`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Some references of Pod specific API endpoints hit during e2e test execution are -
1. https://github.com/cncf/k8s-conformance/issues/220#issuecomment-393344061
2. https://github.com/cncf/apisnoop/issues/17#issuecomment-394866106

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @wangzhen127 @rohfle @AishSundar

**Comment by liggitt** [comment]
the /watch prefix is marked deprecated in code, but I don't see that documented/announced:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L385-L386

passing a `watch` query parameter to the list operation is the preferred way to establish a watch:

from https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#list-62:
> watch: Watch for changes to the described resources and return them as a  stream of add, update, and remove notifications. Specify resourceVersion.

**Comment by liggitt** [comment]
all client uses were switched to the ?watch parameter in https://github.com/kubernetes/kubernetes/pull/41722

I'll open a pull to update the docs and get a deprecation notice for the /watch prefix in the release notes for 1.11

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/65147

**Comment by AishSundar** [comment]
Thanks for catching this @mgdevstack and thanks @liggitt for the explanation and the PR to fix documentation ^
