### ISSUE TITLE
Generic error message when POSTing invalid custom resource with DoRaw()

### ISSUE THREAD

**Issue by drigz** [kubernetes/kubernetes#65136]
/kind bug
/sig api-machinery

**What happened**:

Using client-go, I tried to create a custom resource, but got a generic error:

```
an error on the server ("unknown") has prevented the request from succeeding (post myresources.mygroup.com)
```

**What you expected to happen**:

I would expect a more specific error, eg:

```
an error on the server ("Object 'Kind' is missing in '{}'") has prevented the request from succeeding (post myresources.mygroup.com)
```

**How to reproduce it (as minimally and precisely as possible)**:

Apply this CRD with `kubectl apply -f `

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myresources.mygroup.com
spec:
  group: mygroup.com
  version: v1alpha1
  names:
    kind: Goal
    plural: myresources
    singular: myresource
  scope: Namespaced
```

Then start `kubectl proxy -p 8080` and run the code below:

```
package main

import (
	"log"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
)

func main() {
	client, err := rest.RESTClientFor(&rest.Config{
		Host:    "localhost:8080",
		APIPath: "/apis",
		ContentConfig: rest.ContentConfig{
			GroupVersion: &schema.GroupVersion{
				Group:   "mygroup.com",
				Version: "v1alpha1",
			},
			NegotiatedSerializer: serializer.DirectCodecFactory{CodecFactory: scheme.Codecs},
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	r := client.Post().Namespace("default").Resource("myresources").Body([]byte("{}"))
	log.Println(r.URL())
	_, err = r.DoRaw()
	log.Println("err:", err)
}
```

**Anything else we need to know?**:

I did some spelunking and saw that [transformUnstructuredResponseError](https://github.com/kubernetes/kubernetes/blob/3abba25160590921fec61236ba012a8bbd757d6c/staging/src/k8s.io/client-go/rest/request.go#L905) doesn't do what it says. The comment claims it assumes "the server sends you something sane - JSON + well defined error objects + proper codes". However, it appears to ignore the body unless the Content-Type starts with `text/`. In this case, the body contains the following JSON:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Object 'Kind' is missing in 'object has no kind field '","code":500}
```

which explains the cause much better (although admittedly `"code": 500` and `is missing in 'object has no kind field'` aren't ideal).

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by liggitt** [comment]
posting an empty object on master now returns this error:

errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"WishIHadChosenNoxu in version \"v1beta1\" cannot be handled as a WishIHadChosenNoxu: unmarshalerDecoder: Object 'Kind' is missing in '{}', error found in #2 byte of ...|{}\n|..., bigger context ...|{}\n|...", Reason:"BadRequest", Details:(*v1.StatusDetails)(nil), Code:400}}

/close
