### ISSUE TITLE
Failed to authenticate using azure ad rbac

### ISSUE THREAD

**Issue by richardjharding** [kubernetes/kubernetes#65141]
kind bug

**What happened**:

I folllowed the guidance to create a new aks cluster configured for advanced networking (existing vnet) and rabc with Azure AD integration I was able to fetch the admin credentials and create the cluster role binding , query the cluster via kubectl , browse the dashboard etc

But when I fetch the normal credentials I am unable to run any commands - I get the prompt to authenticate via devicelogin page but once authenticated I see the following

```
error: You must be logged in to the server (Unauthorized)
```

I have previously built a cluster using azure ad with ACS engine so am happy that the ad settings are correct 

**What you expected to happen**:

The cluster is created and I was able to create a cluster role binding and use kubeclt to list nodes after authenticating via azure ad

**How to reproduce it (as minimally and precisely as possible)**:

Follow the instructions here passing in known good azure ad app details - https://docs.microsoft.com/en-us/azure/aks/aad-integration#access-cluster-with-azure-ad

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): windows 10
- Kernel (e.g. `uname -a`):
- Install tools: az cli v 2.0.37
- Others:

**Comment by richardjharding** [comment]
wrong repo!

**Comment by lavanyaanbu001** [comment]
Hi,

I need to do health check of multiple AKS cluster in our environment. I created a cronjob and authenticate to azure using Serviceprinciple and use the config file to login to kuberenetes cluster.

When i run the cronjob, the job stuck in device login line and failed to proceed. I want my script to run without device login page.

Environment:

Kubernetes version (use kubectl version): 1.13.9
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): windows 10
Kernel (e.g. uname -a):
Install tools: az cli v 2.0.37
Others:
