### ISSUE TITLE
Vshere cloud provider on the controller-manager fails to start on non-vmware hosts

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#65145]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:

Currently the vsphere cloud provider blocks the controller-manager from running if its running on a non-vmware host, because it reads `/sys/class/dmi/id/product_serial` and checks if its content starts with `VMWARE-`.

**What you expected to happen**:

The controller manager to start

**How to reproduce it (as minimally and precisely as possible)**:

Start a `controller-manager` on a non-vmware environment with the `--cloud-provider vsphere --cloud-config /my/cloud/conf` flags set

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by prashima** [comment]
@alvaroaleman can you please share some more context- Why do you want vSphere cloud provider to work with non-vmware host (I believe you mean ESXi)? Where is this requirement coming from.

**Comment by alvaroaleman** [comment]
@prashima We are building a Kubernetes cluster management solution which does Kubernetes in Kubernetes and works by creating the control planes in one cluster, then creating worker instances on one of the supported platforms, among them vsphere.

Currently the cluster hosting the control planes (We call it seed cluster) has to run on ESXi, otherwise the controller-manager crashes.

Having the check in place for the Kubelets is completely fine and definitely makes sense, but for the controller-manager it should IMHO not be required.
