### ISSUE TITLE
kubeadm reset leaves kubelet in failing state

### ISSUE THREAD

**Issue by mlushpenko** [kubernetes/kubernetes#65165]
/kind bug

**What happened**:
kubelet fails after `kubeadm reset`

**What you expected to happen**:
I expect to be able to run `kubeadm init` again after `kubeadm reset`, but got failing kubelet healthcheck during `kubeadm init` 

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubeadm init`, then `kubectl drain master0 --delete-local-data=true --force --ignore-daemonsets`, then `kubeadm reset` and then `kubectl status kubelet`. 

If I simply restart kubelet service, it goes back to starting state like it should be after first installation of kubelet if I undesrtand correctly. I think it's an easy fix, just to add `kubectl restart kubelet` to the end of `kubeadm reset` logic

**Comment by stewart-yu** [comment]
Could you paste errors/output more detail? I think you should clean some generated file after `ubeadm reset`.
/area kubeadm
/sig cluster-lifecycle

**Comment by neolit123** [comment]
/cc @kubernetes/sig-cluster-lifecycle-bugs 
/cc @kubernetes/sig-node-bugs 

let's decide if this has to be moved in the `k/kubeadm` repo. thanks!

**Comment by timothysc** [comment]
closing due to stale feedback. 

If you still have an issue, please reopen in https://github.com/kubernetes/kubeadm
