### ISSUE TITLE
iSCSI disk does not appear as Block Device inside the pod

### ISSUE THREAD

**Issue by psaini79** [kubernetes/kubernetes#65166]
I am using volumeMode: Block to access iscsi block device inside the pod but it is throwing following error:

Jun 17 06:53:35 k8worker1 kubelet: E0617 06:53:35.041066   11617 reconciler.go:258] operationExecutor.MountVolume failed (controllerAttachDetachEnabled true) for volume "block-pv" (UniqueName: "kubernetes.io/iscsi/192.168.16.3:3260:iqn.2015-12.com.oracleiaas:bf104865-8dba-4f99-b63e-2c701b0735b5:1") pod "ol76" (UID: "0afac5a4-71fb-11e8-a8bb-000017010f24") : MapVolume.FindMapperPluginBySpec failed to find BlockVolumeMapper plugin. Volume plugin is nil. for volume "block-pv" (UniqueName: "kubernetes.io/iscsi/192.168.16.3:3260:iqn.2015-12.com.oracleiaas:bf104865-8dba-4f99-b63e-2c701b0735b5:1") pod "ol76" (UID: "0afac5a4-71fb-11e8-a8bb-000017010f24")

Following are the steps to reproduce the same:
block-pv.yaml
===========
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  iscsi:
     targetPortal: 192.168.16.3:3260
     portals: ['192.168.16.3.3:3260']
     iqn: iqn.2015-12.com.oracleiaas:bf104865-8dba-4f99-b63e-2c701b0735b5
     lun: 1
     readOnly: false

Block-pvc.yaml
===========
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 80Gi

bash-4.2# kubectl describe pv block-pv
Name:            block-pv
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller=yes
StorageClass:
Status:          Bound
Claim:           default/block-pvc
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Block
Capacity:        100Gi
Message:
Source:
    Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
    TargetPortal:       192.168.16.3:3260
    IQN:                iqn.2015-12.com.oracleiaas:bf104865-8dba-4f99-b63e-2c701b0735b5
    Lun:                1
    ISCSIInterface      default
    FSType:
    ReadOnly:           false
    Portals:            [192.168.16.3:3260]
    DiscoveryCHAPAuth:  false
    SessionCHAPAuth:    false
    SecretRef:          <nil>
    InitiatorName:      <none>
Events:                 <none>

bash-4.2# kubectl describe pvc block-pvc
Name:          block-pvc
Namespace:     default
StorageClass:
Status:        Bound
Volume:        block-pv
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
Finalizers:    []
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Block
Events:        <none>

POD Specification file : ol76.yaml
========================
apiVersion: v1
kind: Pod
metadata:
  name: ol76
  labels:
    name: ol76
spec:
  hostname: ol76
  volumes:
      - name: data
      persistentVolumeClaim:
        claimName: block-pvc
  containers:
    - name: ol76
      image: oraclelinux:latest
      resources:
       limits:
         memory: "200Mi"
         cpu: "1.5"
       requests:
         memory: "200Mi"
         cpu: "1.5"
      securityContext:
       capabilities:
         add: ["NET_ADMIN", "SYS_NICE", "SYS_RESOURCE"]
       volumeDevices:
        - name: data
          devicePath: /dev/xvda

**Comment by psaini79** [comment]
I followed the steps given under following link:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support

**Comment by psaini79** [comment]
@kubernetes/sig-storage-bugs

**Comment by jsafrane** [comment]
@psaini79, what Kubernetes version do you use?

**Comment by psaini79** [comment]
bash-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+2.1.5.el7", GitCommit:"ea4c95b07dd46d5563e4f6851ede13157bf04266", GitTreeState:"archive", BuildDate:"2018-03-23T02:54:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+2.1.5.el7", GitCommit:"ea4c95b07dd46d5563e4f6851ede13157bf04266", GitTreeState:"archive", BuildDate:"2018-03-23T02:54:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jsafrane** [comment]
AFAIK iSCSI in 1.9 does not support block volumes, only FC was supported at that time. It should be much better in 1.10.
