### ISSUE TITLE
[Candidate for Conformance] discussion for [sig-apps] DisruptionController evictions

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#65173]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
After analyzing conformance and non-conformance e2e tests execution, it is observed that -
1. Pod specific evict API endpoints are covered by non-conformance e2e tests and have no coverage under conformance test.

Pod Evict e2e tests (non-conformance)| GitHub Links
-- | --
[sig-apps] DisruptionController evictions: enough pods, absolute => should allow an eviction | [e2e/apps/disruption.go#L147](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/disruption.go#L147)
[sig-apps] DisruptionController evictions: too few pods, absolute => should not allow an eviction
[sig-apps] DisruptionController evictions: maxUnavailable deny evictions, integer => should not allow an eviction
[sig-apps] DisruptionController evictions: no PDB => should allow an eviction
[sig-apps] DisruptionController evictions: maxUnavailable allow single eviction, percentage => should allow an eviction
[sig-apps] DisruptionController evictions: enough pods, replicaSet, percentage => should allow an eviction
[sig-apps] DisruptionController evictions: too few pods, replicaSet, percentage => should not allow an eviction

2. [Different eviction cases](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/disruption.go#L77) are effectively getting covered by non-conformance e2e test wrt. **Pod Disruption Budgets**

**What you expected to happen**:
Which different approaches should we consider to promote Pod Eviction for conformance? e.g.
1. Are these e2e test cases, efficient enough to be considered as Candidate for Conformance and promotion?
2. Incase, eligible for Conformance, should we consider every eviction cases seperately for conformance (replace It() with ConformanceIt()) [or alternatively](https://gist.github.com/mgdevstack/d0cf9635eee47c7bcfca7f7528deb2f3) should we include all these cases under different By() statements and enclose them as single conformance test?
3. Apart from PDB cases, which more Eviction scenarios can be included to create new e2e test?
  e.g.
  - kubectl drain : interaction with eviction api
  - Which more k8s workflows and scenarios can be drafted which uses eviction in background during pods management.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

cc @dchen1107 @AishSundar

**Comment by AishSundar** [comment]
/sig node
/cc @wangzhen127 @selfmanagingresource @hh @rohfle 

@wangzhen127 would it be possible to guide Mayank with the questions above, esp around
* If any of the existing eviction e2e tests can be promoted to Conformance
* Do you think there is a need to update/write new tests which cover the PodSpec better?

**Comment by wangzhen127** [comment]
/cc @yujuhong 
Yu-Ju, are you familiar with the evict API and tests? Can you provide some guidance?

**Comment by yujuhong** [comment]
Evict is part of the policy v1beta API, maintained by sig-apps. @kubernetes/sig-apps-api-reviews @davidopp

**Comment by AishSundar** [comment]
@WilliamDenniss more candidates for beta conformance.

**Comment by spiffxp** [comment]
/close
I'm closing this under the auspices that under the effort to improve coverage of tests for conformance, we shouldn't be writing or promoting tests for beta features (PodDisruptionBudget doesn't appear to be going stable anytime soon, ref: https://github.com/kubernetes/features/issues/85)
