### ISSUE TITLE
fluentd-elastichsearch: unexpected error error_class=TypeError error="no implicit conversion of Symbol into Integer"

### ISSUE THREAD

**Issue by lvicentesanchez** [kubernetes/kubernetes#65175]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**: One of the fluentd pods keeps crashing with `unexpected error error_class=TypeError error="no implicit conversion of Symbol into Integer"`

**What you expected to happen**: The pod should start normally.

**How to reproduce it (as minimally and precisely as possible)**: I'm not sure how to easily reproduce it but this is an upstream bug, https://github.com/fluent/fluentd/issues/1894, that seems to have been solved in fluentd 1.1.1, https://github.com/fluent/fluentd/issues/1760.

**Comment by coffeepac** [comment]
fluentd plugin is now at [v1.2.2](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile#L3).  currently need to manually build the image but when image is available I believe this issue should be resolved.
