### ISSUE TITLE
Make `kubectl describe psp` describe the new `sysctl` field

### ISSUE THREAD

**Issue by stlaz** [kubernetes/kubernetes#65181]
/kind bug

**What happened**:
`kubectl describe psp` does not show the description for the new `sysctl` field added in https://github.com/kubernetes/kubernetes/pull/63717

**What you expected to happen**:
`kubectl describe psp` should describe the new field.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl describe psp`

**Environment**:
- Kubernetes version (use `kubectl version`): master

**Comment by fanzhangio** [comment]
If nobody has started yet, I wanna to pick it up.

**Comment by php-coder** [comment]
@fanzhangio @stlaz was working on it AFAIR.

**Comment by stlaz** [comment]
Indeed. @fanzhangio if you don't mind, I'd take over.
