### ISSUE TITLE
fsGroup field for volumeMounts

### ISSUE THREAD

**Issue by matinats** [kubernetes/kubernetes#65184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
There is no way to specify the ownership of the mounted volumes per volume. There is only the PodSecurityContext filed fsGroup, however this is applied to all the containers and volume mounts of the pod. 

**What you expected to happen**:
It would be nice to have a more fine grained solution for the volume mounts. Thanks!

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"archive", BuildDate:"2018-01-26T12:40:31Z", GoVersion:"go1.8.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
OpenStack

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

- Kernel (e.g. `uname -a`):
Linux vm-2 4.4.89-1.el7.elrepo.x86_64 #1 SMP Wed Sep 27 06:45:38 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by krmayankk** [comment]
i guess the sig will also need to know what use case you have for this feature request ? That will help prioritize this.
