### ISSUE TITLE
Failing Test : gce-1.10-master-upgrade-cluster-new jobs failing in Release blocking tests

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#65190]
## Failing Job
* [gce-1.10-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-new&show-stale-tests=)

Gubernator Logs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1502#beforesuite

From initial investigation with @bsalamat and @krousey it looks like kube-dns didn't come back after upgrade, and the rest of the tests didn't run because they failed on the the precondition check. The recommendation was to followup with someone from Sig-network.

@MrHohn @rramkumar1 @grayluck with 1.11 release branch due to be cut tomorrow evening, can one of you plz help investigate this as a priority to see if there is a Product issue here?

/kind bug
/priority failing-test
/priority critical-urgent
/sig cluster-lifecycle
/sig network
@kubernetes/sig-network-bugs 
/assign @MrHohn 
cc @rramkumar1 @grayluck @jberkus @tpepper
/milestone v1.11

**Comment by MrHohn** [comment]
I'm on the master on the current running jobs (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1503). Didn't see any unready kube-dns yet:
```
$ kubectl get pods -n kube-system
NAME                                               READY     STATUS      RESTARTS   AGE
e2e-image-puller-bootstrap-e2e-minion-group-d5vz   0/2       Completed   0          2h
e2e-image-puller-bootstrap-e2e-minion-group-rvqm   1/2       Running     0          48s
e2e-image-puller-bootstrap-e2e-minion-group-sc2s   0/2       Completed   0          2h
etcd-empty-dir-cleanup-bootstrap-e2e-master        1/1       Running     0          2h
etcd-server-bootstrap-e2e-master                   1/1       Running     0          2h
etcd-server-events-bootstrap-e2e-master            1/1       Running     0          2h
event-exporter-v0.2.1-7c9486678b-wfpqz             2/2       Running     0          2h
fluentd-gcp-scaler-5d85d4b48b-7vpn6                1/1       Running     0          2h
fluentd-gcp-v3.0.0-46cvq                           2/2       Running     0          1m
fluentd-gcp-v3.0.0-mmdkm                           2/2       Running     0          2h
fluentd-gcp-v3.0.0-mq6fm                           2/2       Running     0          2h
fluentd-gcp-v3.0.0-vqdrd                           2/2       Running     0          2h
heapster-v1.5.3-5d976b745f-l7zgq                   2/2       Running     0          3m
kube-addon-manager-bootstrap-e2e-master            1/1       Running     0          2h
kube-apiserver-bootstrap-e2e-master                1/1       Running     2          2h
kube-controller-manager-bootstrap-e2e-master       1/1       Running     3          2h
kube-dns-7b479ccbc6-w59fm                          3/3       Running     0          3m
kube-dns-7b479ccbc6-zjpsx                          3/3       Running     0          2h
kube-dns-autoscaler-67c97c87fb-pfh6j               1/1       Running     0          2h
kube-proxy-bootstrap-e2e-minion-group-d5vz         1/1       Running     0          2h
kube-proxy-bootstrap-e2e-minion-group-rvqm         1/1       Running     0          46s
kube-proxy-bootstrap-e2e-minion-group-sc2s         1/1       Running     0          2h
kube-scheduler-bootstrap-e2e-master                1/1       Running     1          2h
kubernetes-dashboard-db894757f-k9gxv               1/1       Running     0          2h
l7-default-backend-5bc54cfb57-gcgcg                1/1       Running     0          3m
l7-lb-controller-v1.1.1-bootstrap-e2e-master       1/1       Running     2          2h
metadata-proxy-v0.1-5mv76                          2/2       Running     0          2h
metadata-proxy-v0.1-bv5c5                          2/2       Running     0          2h
metadata-proxy-v0.1-lwffw                          2/2       Running     0          2h
metadata-proxy-v0.1-xch4c                          2/2       Running     0          1m
metrics-server-v0.2.1-fd596d746-rcnwz              2/2       Running     0          3m
rescheduler-v0.3.1-bootstrap-e2e-master            1/1       Running     0          2h
```

**Comment by MrHohn** [comment]
A quick update, the same symptom (kube-dns didn't come back after upgrade) doesn't occur on the latest run (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1503, which hasn't finished yet).

I will see if I can reproduce the issue locally.

**Comment by MrHohn** [comment]
Turned out for that particular run where kube-dns failed to come back after upgrade (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1503). It was because kube-proxy failed to run on that specific node, hence the communication between pods and apiserver's service IP just didn't work.
```
Jun 18 14:05:52.012: Error waiting for all pods to be running and ready: 4 / 32 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                                        NODE                            PHASE   GRACE CONDITIONS
kube-dns-7b479ccbc6-kkbvz                  bootstrap-e2e-minion-group-5x5s Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason: Message:}]
kube-dns-7b479ccbc6-ld59m                  bootstrap-e2e-minion-group-5x5s Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [kubedns dnsmasq]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-06-18 13:23:13 +0000 UTC Reason: Message:}]
kube-proxy-bootstrap-e2e-minion-group-5x5s bootstrap-e2e-minion-group-5x5s Failed        []
```

Found some relevant error messages from kubelet logs (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1502/artifacts/bootstrap-e2e-minion-group-5x5s/kubelet.log).
```
W0618 13:24:06.648784    1382 predicate.go:107] Failed to admit pod kube-proxy-bootstrap-e2e-minion-group-5x5s_kube-system(2a65e05820fc978c561c388164379ab4) - Unexpected error while attempting to recover from admission failure: preemption: pod e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(93d7b4be667c4075fa6435c572f1a387) failed to evict timeout waiting to kill pod
I0618 13:24:06.648916    1382 kubelet.go:1852] SyncLoop (DELETE, "api"): "e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(25ee9909-72f8-11e8-9157-42010a800002)"
I0618 13:24:06.648988    1382 kubelet.go:1846] SyncLoop (REMOVE, "api"): "e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(25ee9909-72f8-11e8-9157-42010a800002)"
I0618 13:24:06.649031    1382 kubelet.go:1923] SyncLoop (housekeeping)
I0618 13:24:06.651779    1382 server.go:460] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"e2e-image-puller-bootstrap-e2e-minion-group-5x5s", UID:"93d7b4be667c4075fa6435c572f1a387", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'ExceededGracePeriod' Container runtime did not kill the pod within specified grace period.
I0618 13:24:06.651830    1382 server.go:460] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-proxy-bootstrap-e2e-minion-group-5x5s", UID:"2a65e05820fc978c561c388164379ab4", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'UnexpectedAdmissionError' Unexpected error while attempting to recover from admission failure: preemption: pod e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(93d7b4be667c4075fa6435c572f1a387) failed to evict timeout waiting to kill pod
I0618 13:24:06.784796    1382 config.go:303] Setting pods for source api
I0618 13:24:06.789306    1382 status_manager.go:496] Patch status for pod "kube-proxy-bootstrap-e2e-minion-group-5x5s_kube-system(25efac11-72f8-11e8-9157-42010a800002)" with "{\"status\":{\"conditions\":null,\"containerStatuses\":null,\"hostIP\":null,\"message\":\"Pod Unexpected error while attempting to recover from admission failure: preemption: pod e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(93d7b4be667c4075fa6435c572f1a387) failed to evict timeout waiting to kill pod\",\"phase\":\"Failed\",\"podIP\":null,\"qosClass\":null,\"reason\":\"UnexpectedAdmissionError\"}}"
I0618 13:24:06.789387    1382 status_manager.go:503] Status for pod "kube-proxy-bootstrap-e2e-minion-group-5x5s_kube-system(25efac11-72f8-11e8-9157-42010a800002)" updated successfully: (1, {Phase:Failed Conditions:[] Message:Pod Unexpected error while attempting to recover from admission failure: preemption: pod e2e-image-puller-bootstrap-e2e-minion-group-5x5s_kube-system(93d7b4be667c4075fa6435c572f1a387) failed to evict timeout waiting to kill pod Reason:UnexpectedAdmissionError NominatedNodeName: HostIP: PodIP: StartTime:2018-06-18 13:04:34 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass:})
I0618 13:24:06.834623    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-lib-modules") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
I0618 13:24:06.834689    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "varlog" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-varlog") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
I0618 13:24:06.834727    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-kubeconfig") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
I0618 13:24:06.834759    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "etc-ssl-certs" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-etc-ssl-certs") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
I0618 13:24:06.834792    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "usr-ca-certs" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-usr-ca-certs") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
I0618 13:24:06.834820    1382 desired_state_of_world_populator.go:267] Removing volume from desired state for volume "iptableslock" (UniqueName: "kubernetes.io/host-path/2a65e05820fc978c561c388164379ab4-iptableslock") pod "kube-proxy-bootstrap-e2e-minion-group-5x5s" (UID: "2a65e05820fc978c561c388164379ab4")
```

Seems like kube-proxy failed to be admitted and after the failure kubelet never restart it. Would this be a pod preemption bug? @bsalamat 
Might need insights from @kubernetes/sig-node-test-failures as well.

**Comment by AishSundar** [comment]
First instance of this kind of failure started happening since 4/26/2018

https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-05-01&job=e2e-gce-new-master-upgrade-cluster-new&test=BeforeSuite

The failures are few and far between, but seems to be introduced only this release cycle. So this seems to be a critical issue to evaluate for 1.11 RC cut tomorrow

**Comment by bsalamat** [comment]
Thanks, @MrHohn for investigating the issue. The kubelet preemption is unrelated to the scheduler preemption. Scheduler is out of the loop for these preemptions. We have tried to call it kubelet "eviction" instead of "preemption" to remove the confusion, but not all of our logs are updated.
Anyway SIG node (@kubernetes/sig-node-test-failures) folks can tell us how serious this problem is, but from the look of it, I would say this was a transient issue.

**Comment by AishSundar** [comment]
@abgworrall can someone from Node team help looking into this failure to assess if this could be potentially release blocking?

**Comment by dashpole** [comment]
Yeah, this is related to kubelet preemption, which allows critical pods to remove other pods from the node in order to schedule them.  Without kubelet preemption, the kube-proxy pod would simply be rejected.  In this case, the kubelet tried to remove a pod in order to run kube-proxy, but failed to evict it. 
 So the underlying issue is that there are more pods scheduled to the node than the kubelet can accept, which does seem odd.  Is it possible to figure out which pods were assigned to the node at that time?  I doubt this is a release blocker...

**Comment by dashpole** [comment]
These are all the pods on the node.
fluentd-gcp-v3.0.0-n529z
fluentd-gcp-v3.0.0-xlfbl
kubernetes-dashboard-db894757f-4mvkj
kube-dns-autoscaler-67c97c87fb-z2bc8
kube-dns-7b479ccbc6-kkbvz
res-cons-upgrade-5m9rn
foo-86jjr
kube-dns-7b479ccbc6-ld59m
fluentd-gcp-scaler-5d85d4b48b-p2mfp
service-test-lk7j7
res-cons-upgrade-nlqnl
event-exporter-v0.2.1-7c9486678b-vfmns
foo-74rnh
echoheaders-https-759k4
ss-1
e2e-image-puller-bootstrap-e2e-minion-group-5x5s
kube-proxy-bootstrap-e2e-minion-group-5x5s

**Comment by AishSundar** [comment]
"Is it possible to figure out which pods were assigned to the node at that time?"

@krzyzacy @BenTheElder is there any way we can find how each of those remanent pods got scheduled on the node?

@dashpole the reason you think this is NOT a release blocker is because this seems like a test setup issue? and/or you are unable to repro this manually?

**Comment by krzyzacy** [comment]
what are those foo-* pods...

@dashpole so sounds like the node is not expect to run that many things at the same time? Which means the testing deployment logic need to be improved, or we need to use larger nodes?

**Comment by AishSundar** [comment]
@BenTheElder incase he has some thoughts

**Comment by BenTheElder** [comment]
@AishSundar most of our jobs create and throw away entire clusters for every run, so individual runs should not be affected by other runs.

**Comment by AishSundar** [comment]
hmm thought so, thanks @BenTheElder for clarifying. So looks like once in a while too many pods are being scheduled by the exact same test deployment?

**Comment by dashpole** [comment]
Normally, kubelet preemption should work, and kick another pod off the node to schedule kube-proxy.  Evictions can fail occasionally.  The underlying issue though is that there are too many pods.

**Comment by dashpole** [comment]
It looks like all of the other pods for the run are scheduled before kube-proxy is read from a file, which may be why the scheduler still places them on the node.

**Comment by AishSundar** [comment]
Will it be useful to look at the logs of a successfull run to see if even those schedule so many pods (and in that order) on the node?

**Comment by jberkus** [comment]
Is this still an issue for current upgrade tests?

**Comment by MrHohn** [comment]
Took a quick look and seems like the previous symptom is gone. This issue is likely obsolete at the moment.

/close

**Comment by AishSundar** [comment]
@jberkus here's link to the current failure for this job - https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new

We are seeing the job Timeout consistently now, not sure on what though. Looking at the [triage dahsboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-08-30&job=gce-new-master-upgrade-cluster-new&test=Timeout), the timeouts were happening earlier as well, but became consistent from mid August.

/cc @roberthbailey @zmerlynn 
@zmerlynn would you be able to help shed some light on how to debug what this is timing out on further?

**Comment by AishSundar** [comment]
@jberkus may be we should open a new issue with the info in my comment above and assign it to @zml for initial triage? the [gke counterpart upgrade job](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new) is also timing out.
