### ISSUE TITLE
volume stats no metrics

### ISSUE THREAD

**Issue by zhangjianweibj** [kubernetes/kubernetes#65208]
hello!
Kubernetes version :1.9.5

I used prometheus to monitor kubernetes cluster.Finding no metric about volume.Then i checked the k8s project,finding VolumeStats not used.why?and how to monitor pv&pvc resource usage.very thanks

![image](https://user-images.githubusercontent.com/18585129/41586766-230ee384-73e0-11e8-865f-61de58e8879a.png)

**Comment by zhangjianweibj** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by wgliang** [comment]
> Volumes on each node changes, we should not only add PVC metrics into
gauge vector. It's better use a collector to collector metrics from internal
stats.

You can see #59170.
