### ISSUE TITLE
Wrong requested CPU count when node has finished jobs

### ISSUE THREAD

**Issue by pmoncadaisla** [kubernetes/kubernetes#65207]
/kind bug

**What happened**:
In nodes where there are only 2 CPU I can see requested values higher than 2.
It seems to be because of successful jobs that are kept (jobs managed by a cronjob).
This is making autoscaler scale more and more nodes, as those where job have been scheduled remain "full".

This is happening in GKE, but its likely to happen in any k8s cluster:

![image](https://user-images.githubusercontent.com/1449482/41584976-ff537a40-73a8-11e8-9652-b5fbf1a62416.png)

![image](https://user-images.githubusercontent.com/1449482/41584982-03621b28-73a9-11e8-868a-5f6d98207474.png)

You can see that the SUM of all POD CPU requested matches the node CPU request.

**What you expected to happen**:
When a job is successful it shouldn't count agains the requested cpu count.

**How to reproduce it (as minimally and precisely as possible)**:
Ejecute a CronJob and wait until it finishes. Wait for more executions.

**Anything else we need to know?**:
As a workaround, it is possible to set the CronJob `.spec.successfulJobsHistoryLimit` to 0, so successful jobs are not kept.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.7
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): v1.9.6-gke.1 (COS)
- Kernel (e.g. `uname -a`): v1.9.6-gke.1 (COS)

**Comment by pmoncadaisla** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by yastij** [comment]
cc @soltysh

**Comment by lanchongyizu** [comment]
```
$kubectl describe node

Non-terminated Pods:         (3 in total)
  Namespace                  Name                              CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                              ------------  ----------  ---------------  -------------
  default                    hello-1531463580-9vmwd            500m (6%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-dns-7b479ccbc6-wxqrw         260m (3%)     0 (0%)      110Mi (0%)       170Mi (1%)
  kube-system                metrics-server-7967d6d65-st7z6    0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests    Limits
  --------  --------    ------
  cpu       760m (9%)   0 (0%)
  memory    110Mi (0%)  170Mi (1%)

$kubectl get pods

NAME                     READY     STATUS      RESTARTS   AGE
hello-1531463400-92rcl   0/1       Completed   0          3m
hello-1531463460-z8hs9   0/1       Completed   0          2m
hello-1531463520-6kpsj   0/1       Completed   0          1m
hello-1531463580-9vmwd   0/1       Completed   0          9s

```

Hi @pmoncadaisla, I triage it in local cluster with the master code, but couldn't reproduce the issue. We can find that the CPU resources requested by successful history jobs have been released.

In addition, in your case above, if the successful history job doesn't release the requested CPU/Mem resource, thus the node would fail other pods that request more CPU/Mem resource than the node's remaining resources. 

Is it possible that it's caused by the UI code that updates the dashboard above?

**Comment by pmoncadaisla** [comment]
Hi @lanchongyizu , it didn't seem to be a problem with the UI, because it happened that more and more nodes there added because of the cluster auto scaler, and no containers were running in many nodes.

Is there anything you want me to check?

**Comment by lanchongyizu** [comment]
Hi @pmoncadaisla Could you try `kubectl describe node` when the issue happens? And I will triage `Kubernetes version (use kubectl version): v1.9.7` later when I got time.
