### ISSUE TITLE
spammy output from kubectl get resource --watch

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#6521]
Reported by amyu@:

"I'm curious about the kubectl watch flag as applied to 'get pods'.
After a short pause, it just seems to rotate through listing the information for each pod, one at a time with heartbeat regularity, but nothing evident has changed with any of the pods.

Is this 'works as intended'?  I had assumed it would only output changes. The uptime for a given pod will have of course changed (by a few seconds) every time it checks-- is it detecting that?"

My response on this: "I Just observed the same thing this morning with v 0.14. No, this is not intention."

This is side effect from kubelet post status directly. For podStatus, Kubelet post status on change every 10seconds. But I noticed that kube-dns is popup every 10seconds, why it keep changing? 

cc/ @lavalamp

**Comment by lavalamp** [comment]
I just tried this, it appears to not be an issue any more.
