### ISSUE TITLE
kubectl get namespace inconsistent error messages

### ISSUE THREAD

**Issue by kevtaylor** [kubernetes/kubernetes#65212]
/kind bug

**What happened**:

Using kubectl without supplying a valid KUBECONFIG for a namespace gives inconsistent 
error conditions when using short form and long form

**What you expected to happen**:
Consistent messages

**How to reproduce it (as minimally and precisely as possible)**:
```
/root/kubernetes/hyperkube kubectl get ns -n kube-system
error: the server doesn't have a resource type "ns"
```
```
/root/kubernetes/hyperkube kubectl get namespace -n kube-system
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Anything else we need to know?**:
tried on 1.9.3 / 1.10.0 and 1.10.1 and all appear to behave same way
**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS 1745.7.0 
- Kernel (e.g. `uname -a`):  4.14.48-coreos-r2
- Install tools: kube-aws 
- Others:

**Comment by liggitt** [comment]
thanks for the report. this is resolved in master and will be fixed in 1.11:

```
$ kubectl get namespace
The connection to the server localhost:8080 was refused - did you specify the right host or port?
$ kubectl get ns
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

/close
