### ISSUE TITLE
Delete stale UDP conntrack entries with external ip usage

### ISSUE THREAD

**Issue by hiep-huynh** [kubernetes/kubernetes#65228]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Fix #59286 doesn't remove the stale udp conntrack session when an external ip is involved. The stale session lingers and continues to misdirect traffic to endpoints that are removed and it prevents sessions to new endpoints from being created.

**What you expected to happen**:
Fix #59286 removes stale udp conntrack sessions by cluster ip as its solution but if using external ip (ex. vip) the stale udp conntrack session can't be matched by cluster ip so it doesn't get removed. In this scenario, the stale session's fields contain the external ip, endpoint ip and port but not cluster ip.

**How to reproduce it (as minimally and precisely as possible)**:
With all inbound traffic routed through a vip, the following sflow-app has its traffic forwarded from an external ip 10.0.22.190 to its endpoint 10.32.0.83:6343:

NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
sflow-app                ClusterIP   10.105.23.70     10.0.22.190   6343/UDP                      6d

NAME                      ENDPOINTS                                          AGE
sflow-app                10.32.0.83:6343                                    6d

The conntrack session for the above service looks like this (notice the cluster ip of 10.105.23.70 is not part of the session):
udp      17 29 src=10.0.22.3 dst=10.0.22.190 sport=50401 dport=6343 [UNREPLIED] src=10.32.0.83 dst=10.32.0.1 sport=6343 dport=50401 mark=0 use=1

When the pod/endpoint is removed or it gets a new ip address, the conntrack session doesn't get removed by external ip or endpoints so it just lingers.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`):
Linux firescope1 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/sig network

**Comment by hiep-huynh** [comment]
I've written a script to periodically clear out stale udp conntrack sessions: [clear_stale_udp_sessions.sh](https://gist.github.com/hiep-huynh/792070c91b746c79fd7912d4db428167)

It gathers ports exposed via your services and removes conntrack sessions to these ports upon these conditions:
- if they're not currently in use (iptables rules don't exist for the ports so conntrack sessions for it shouldn't exist either)
- if the iptables rules exist for the port but the ip address is different from the conntrack session's ip address (this means a prior session has become stale and was not properly removed previously)

**Comment by moskvin** [comment]
Seems we got the same issue on our cluster.
@hiep-huynh Thank you for your script, Can you advise me how I can integrate it? It uses conntrack tools and I should install it in my OS inside my kube, right?

**Comment by hiep-huynh** [comment]
I use systemd's timer to run the script every 30s at the node OS-level.  The conntrack command requires root privileges so the script will need to be run with root privileges too. It's configured to run on each node since they each have their own conntrack sessions that can go stale.
