### ISSUE TITLE
create shortname for --serviceaccount when creating rolebindings

### ISSUE THREAD

**Issue by RickNEP** [kubernetes/kubernetes#65224]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
kind feature

Currently we can only create rolebindings with the full name --serviceaccount, as I'm lazy I'd like to use --sa.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
a long flag named "sa" isn't very descriptive. autocompletion is your friend :)

`--servi<tab>`

/close
