### ISSUE TITLE
Display which Pods have the PVC in use.

### ISSUE THREAD

**Issue by dsalamancaMS** [kubernetes/kubernetes#65233]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I need to know to which Pod(s) a PVC is being mounted to, without having to go through each Pod one by one checking the Volume mounts and the PersistentVolumeClaim.
The kubectl describe pvc and get pvc, only tell you to which Persistent Volume the PVC is bound to, but not if is being used by a Pod(s)

**What you expected to happen**:
Add a new field in the describe or get that lists the pods that are using the PVC as a volume mount

**How to reproduce it (as minimally and precisely as possible)**:
Have a  PV/PVC bound and create a pod using a volume mount

**Anything else we need to know?**:

Not sure if this is only for Azure Disk, which is the Storage Class I am using.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.7

- Cloud provider or hardware configuration:
Azure

- OS (e.g. from /etc/os-release):
Ubuntu 16.04

- Kernel (e.g. `uname -a`):
4.4
- Install tools:
Azure Kubernetes Services
- Others:
-n/a

**Comment by krmayankk** [comment]
I think the kubectl describe can just construct this on the fly. Another angle is should we add this information to PVC object itself

**Comment by dsalamancaMS** [comment]
That will be great, as right now the only way to correlate a PVC to a Pod is via a "describe" on the Pod.

**Comment by clandry94** [comment]
I can work on this! 

/assign

**Comment by feiskyer** [comment]
+1 for the feature.

cc @kubernetes/sig-cli-feature-requests

**Comment by pradeep-kaloori** [comment]
How to find "what pods are using particular PVC  through command line"

**Comment by azzaka** [comment]
+1 for the feature.

**Comment by clandry94** [comment]
@azzaka this feature will be in Kubernetes 1.12

**Comment by porrascarlos802018** [comment]
ok kubernetes 1.12 released, how to? which command?

**Comment by amanjain08** [comment]
Can someone point to the documentation or paste command to get the pods which have the PVC in use

**Comment by Moshem123** [comment]
Workaround for the meantime:
```kubectl get pods --all-namespaces -o=json | jq -c \
'.items[] | {name: .metadata.name, namespace: .metadata.namespace, claimName:.spec.volumes[] | select( has ("persistentVolumeClaim") ).persistentVolumeClaim.claimName }'```

**Comment by silenceshell** [comment]
Thanks @Moshem123 , this workaround is great for those people who still use old kubernetes version.

However it will meet an error if the pod have no volumes, so I improves it by adding a `has` to check whether the volumes exists or not.

```text
kubectl get pods --all-namespaces -o=json | jq -c '.items[] | {name: .metadata.name, namespace: .metadata.namespace, claimName: .spec |  select( has ("volumes") ).volumes[] | select( has ("persistentVolumeClaim") ).persistentVolumeClaim.claimName }'
```

**Comment by zakkg3** [comment]
python script to list pods with pvc in namespace(s):
https://gist.github.com/zakkg3/8c4f6b5e015d1229bf0643156b30ecdc
Is a part of a cli to set pods with velero/restic annotations.
Hope it helps someone :)

**Comment by DanTulovsky** [comment]
For posterity... There is a *Used By: * field in the output of describe.

```
% k describe -n staging pvc grafana-hi9f 
Name:          grafana-hi9f
Namespace:     staging
StorageClass:  standard
Status:        Bound
Volume:        pvc-041c1e08-bee7-4b2d-bbc1-5dda4496d09d
Labels:        app.kubernetes.io/instance=grafana-hi9f
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=grafana
               app.kubernetes.io/version=8.0.5
               helm.sh/chart=grafana-6.13.10
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       grafana-hi9f-5f7d8b94d5-6tvsm
Events:        <none>
```

**Comment by lajiao117** [comment]
client-go didn't give this api...

**Comment by mhkarimi1383** [comment]
> Thanks @Moshem123 , this workaround is great for those people who still use old kubernetes version.
> 
> However it will meet an error if the pod have no volumes, so I improves it by adding a `has` to check whether the volumes exists or not.
> 
> ```
> kubectl get pods --all-namespaces -o=json | jq -c '.items[] | {name: .metadata.name, namespace: .metadata.namespace, claimName: .spec |  select( has ("volumes") ).volumes[] | select( has ("persistentVolumeClaim") ).persistentVolumeClaim.claimName }'
> ```

Hi thanks worked for me ;)
but I want to make it reverse my workarounds with adding `not` after `has` didn't worked 
do you have any ideas

```bash
kubectl get pods --all-namespaces -o=json | jq -c '.items[] | {name: .metadata.name, namespace: .metadata.namespace, claimName: .spec | select( has ( "volumes" ) ).volumes[] | select( has ( "persistentVolumeClaim" ) | not ).persistentVolumeClaim.claimName}'
```

**Comment by jeromeza** [comment]
$ kubectl describe pvc -A | grep -E "Name|StorageClass|Used"

Name:          ocs-deviceset-lso-volumeset-0-data-1b45dn
Namespace:     openshift-storage
StorageClass:  lso-volumeset
Used By:       rook-ceph-osd-1-6c8c74dcd5-8fwpd

Also useful ^

**Comment by jstewart612** [comment]
@mhkarimi1383 the reason it didn't work is because each return does, in point of fact, have a key defined for claimName.  That key is just set to null value.

So, what you'd actually want to do is test for nulls.

As nice as @jeromeza's answer is, it's a PITA to parse unstructured human-readable command output, as opposed to command output in a markup language that well known shell parsers like jq and yq can work with.

Towards that end, because I had use of this, I came up with the following:

```
kubectl get pods --all-namespaces -o=json | jq -c '.items[] | {name: .metadata.name, namespace: .metadata.namespace, claimName: .spec | select(has("volumes")).volumes[] | select(has("persistentVolumeClaim")).persistentVolumeClaim.claimName} | select(.claimName != null)'
```
