### ISSUE TITLE
"kubectl get pods -o name" shows evicted pods

### ISSUE THREAD

**Issue by samolds** [kubernetes/kubernetes#65245]
/kind bug
/sig cli

**What happened**:
I use the `kubectl get pods -o name` command in a number of scripts to get the names of my active pods. Recently I noticed that it started failing sometimes. Upon further investigation, I noticed that the `-o name` output format will include pods that have been evicted. But `kubectl get pods` and even `kubectl get pods -o wide` do not include these pods. This seems like inconsistent behavior.

**What you expected to happen**:
I would expect `kubectl get pods -o name` to only return the name of actively running pods, like `kubectl get pods` does.

**How to reproduce it (as minimally and precisely as possible)**:
Spin up a pod.
Spin down the same pod.

```
kubectl get pods
kubectl get pods -o wide
```

See no pods

```
kubectl get pods -o name
```

See one pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.1", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-05-11T17:16:56Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GCE

- OS (e.g. from /etc/os-release): OSX 10.11.6

- Kernel (e.g. `uname -a`):

```
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Wed May  2 21:04:22 PDT 2018; root:xnu-3248.73.10~1/RELEASE_X86_64 x86_64
```

- Install tools:

- Others:

**Comment by liggitt** [comment]
completed pods were previously filtered from the human-readable printer view, but as part of making kubectl more agnostic to the contents of the API objects it fetches/prints, that special-case was removed in https://github.com/kubernetes/kubernetes/pull/60793

as of 1.11, `kubectl get pods` will show all pods.

/close

**Comment by pjanuario** [comment]
@liggitt I also upgrade kubectl and got surprise about this and even by looking in to changelog didnt seem to see any thing related, at least for me is more common to just want to get all running pods than all of them, of course I can create custom alias on my shell to filter them out, but that seems not very pleasent to ask users to do that. Is there any plan of a flag or something that would allows easily to use previous behaviour?

**Comment by liggitt** [comment]
> Is there any plan of a flag or something that would allows easily to use previous behaviour?

not currently. if filtering is reintroduced, it will be done in a way that works with resources generically, not specific to pods.
