### ISSUE TITLE
Fix openapi spec for CRD validation schema constructs

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#65243]
The CRD validation schema constructs have some structs without json tags: https://github.com/kubernetes/kubernetes/pull/65234. These structs are exposed in the openapi schema:

```json
"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray": {
    "description": "JSONSchemaPropsOrArray represents a value that can either be a JSONSchemaProps or an array of JSONSchemaProps. Mainly here for serialization purposes.",
    "required": [
     "Schema",
     "JSONSchemas"
    ],
    "properties": {
     "JSONSchemas": {
      "type": "array",
      "items": {
       "$ref": "#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }
     },
     "Schema": {
      "$ref": "#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
     }
    }
   },
```

With this schema:
- the fields are exposed with uppercase names
- they are marked as required

This should be fixed to mark them as optional.

Maybe relevant, we could do something like:

https://github.com/kubernetes/kubernetes/blob/3994829cb07e702956834d293510fa504ea2a5d6/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go#L28

```
// OpenAPISchemaType is used by the kube-openapi generator when constructing
// the OpenAPI spec of this type.
//
// See: https://github.com/kubernetes/kube-openapi/tree/master/pkg/generators
func (_ Time) OpenAPISchemaType() []string { return []string{"string"} }

// OpenAPISchemaFormat is used by the kube-openapi generator when constructing
// the OpenAPI spec of this type.
func (_ Time) OpenAPISchemaFormat() string { return "date-time" }
```

/sig api-machinery
/kind bug

/cc @sttts @liggitt @caesarxuchao @lavalamp @mbohlool

**Comment by liggitt** [comment]
> the problem still exists in the openapi spec related to these types. Opened #65243 for it. This is present in 1.10 and 1.9 as well, so this is not crucial to be fixed for 1.11.

the openapi schema was wrong in 1.10 and 1.9, but in 1.11 https://github.com/kubernetes/kubernetes/pull/64174 fixed the association with group-version-kind, so kubectl actually uses it in 1.11.

**Comment by liggitt** [comment]
> With this schema:
> 
>     the fields are exposed with uppercase names
>     they are marked as required
> 
> This should be fixed to mark them as optional.

actually, if those JSON fields never appear in JSON output, they shouldn't be included in the schema at all.

adding to the milestone for triage since `kubectl create -f ...` will complain about files that are actually valid and previously worked.

/milestone v1.11

**Comment by lavalamp** [comment]
It sounds like we urgently need to explain to the OpenAPI generation
process when fields are serialized in a non-standard way. I am pretty sure
Mehdy included a way to do that, look at how IntOrString is handled.

**Comment by liggitt** [comment]
yeah, just like this

```
// OpenAPISchemaType is used by the kube-openapi generator when constructing
// the OpenAPI spec of this type.
//
// See: https://github.com/kubernetes/kube-openapi/tree/master/pkg/generators
func (_ IntOrString) OpenAPISchemaType() []string { return []string{"string"} }

// OpenAPISchemaFormat is used by the kube-openapi generator when constructing
// the OpenAPI spec of this type.
func (_ IntOrString) OpenAPISchemaFormat() string { return "int-or-string" }
```

thing is, it's not actually accurate... int-or-string can also be an int. not sure how kubectl validation is skipping that type... might be special-cased

**Comment by nikhita** [comment]
/priority critical-urgent

will need to be cherry-picked to 1.11 now that code freeze is lifted.

**Comment by tpepper** [comment]
As the PR #65256 is already so marked, noting here in the issue that it is:

/status approved-for-milestone

**Comment by liggitt** [comment]
Keeping open to track until the 1.11 pick merges

**Comment by liggitt** [comment]
cherrypick to 1.11 merged
/close
