### ISSUE TITLE
Add a JSON tag linter for API types

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#65244]
We should add a linter to make sure that API types contain json tags, and with the correct case, etc.

See https://github.com/kubernetes/kubernetes/pull/65234#discussion_r196556344 for more context.

/sig api-machinery
/kind feature

/cc @liggitt @sttts @caesarxuchao @lavalamp @roycaihw

**Comment by roycaihw** [comment]
Added code in API linter WIP PR to make sure we catch missing JSON tag https://github.com/kubernetes/kube-openapi/pull/83
