### ISSUE TITLE
Node Performance Testing.

### ISSUE THREAD

**Issue by balajismaniam** [kubernetes/kubernetes#65249]
# Background
1. We have some low level node performance optimization features already implemented in the Kubelet (e.g., CPU manager).
2. We don't have a way to objectively measure how well certain performance-sensitive applications run on k8s across versions.
3. We don’t have performance data on how performance-sensitive applications benefit from the already implemented features.
4. We don't have a way to measure the effect of further performance features on the classes of performance sensitive applications that our users care about. This leads to making decisions based on speculative analysis of performance impact, or inability to make decisions.
5. In March 2018 at the latest resource management working group face-to-face meeting, we agreed to prioritize building a node performance testing framework and suite over some of the performance optimization proposals. This way we can make better decisions based on objective data.

# Goals
1. Detect performance regressions.
2. Provide objective data to guide node performance optimization features.

# Proposal Document
https://docs.google.com/document/d/14SfsL1Bs5jEniNaYN7kgRan9m5ZhuyLPBPvTrZ1mK94/edit#

# Phase 1 Action/Exploration Items
1. Node e2e test driver.
2. Determine initial set of workloads.
3. Add workload container images for node performance testing.
4. Documentation.
5. Periodically run the node perf testing suite with initial set of workloads. 
6. Represent node performance test results in one of the test dashboards.
    1. Choose either https://k8s-testgrid.appspot.com/ or http://node-perf-dash.k8s.io. 
    2. Initial result will be FAILED or PASSED. 
        1. Use some simple stats (e.g., the test failed if performance of workload X falls outside of -5% performance from the average performance of the last 10 runs of the workload).
    3. Resources
        1. Node-perf-dash: https://github.com/kubernetes/contrib/tree/master/node-perf-dash
        2. Testgrid: https://github.com/kubernetes/test-infra/tree/master/testgrid
        3. Compare between two test runs: https://github.com/kubernetes/perf-tests/tree/master/compare. 
        4. How PASSED or FAILED is posted now: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/gubernator.sh#L152-L157
        5. Do we need to use NodePerfData type: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/perftype/perftype.go#L38-L45

# Pull Requests
1. Adding docker images for workloads: https://github.com/kubernetes/kubernetes/pull/65251.
2. The node performance testing framework: https://github.com/kubernetes/kubernetes/pull/65250.

/assign @balajismaniam @ConnorDoyle. 
CC @vishh @derekwaynecarr

**Comment by tpepper** [comment]
Will this target the 1.12 milestone?

**Comment by balajismaniam** [comment]
#65251 is one of the steps. 
/reopen
