### ISSUE TITLE
Antiaffinity pods scheduled to the same node during scheduler leader-election

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#65257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Two pods with AntiAffinity label are scheduled to the same node.

**What you expected to happen**:
Two pods with AntiAffinity label are scheduled to different nodes.

**How to reproduce it (as minimally and precisely as possible)**:
na

**Anything else we need to know?**:
The bug is caused by scheduler during leader switch.
Here is what happened:
Suppose there are two schedulers, **SA(active), SB(standby)**. Two pods with antifinity **PA, PB**. Two nodes **NA, NB**. 
1. SA failed to renew the lease.
2. SB became active scheduler.
3. SA's main thread didn't quit ontime, it scheduled PA to NA and then quited. 
4. SB scheduled PB to NA because it didn't know PA has already been scheduled.
5. The final state is that PA and PB were both on node NA.

Here is the log of SA:
SA: tw-node2221, SB: tw-node2222.
SA lost election at **16:03:35** but continued to schedule pods until found conflicts in cache and then quited.
![image](https://user-images.githubusercontent.com/10572401/41635898-de6abf84-747d-11e8-8125-20796db8551a.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.5.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
4.4.64-1.el7.elrepo.x86_64
- Install tools:
- Others:

**Comment by DylanBLE** [comment]
I would like to add Antifinity Predict to Kubelet Admit to fix this issue.

**Comment by hzxuzhonghu** [comment]
This can happen when the original leader takes too long(eg. longer than `LeaseDuration` ) to `tryAcquireOrRenew`, but in the meantime the  leadership has been acquired by another candidate.

**Comment by hzxuzhonghu** [comment]
#65094 This can reduce this probability at some degree. But can not eliminate more than one schedulers working concurrently during some transition time.

**Comment by hzxuzhonghu** [comment]
To solve this completely, we have to prevent overlap of two leaders: 

1.  add a filed in `LeaderElector` to record the renew time of leader. 

1. candidate does not call [Create](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L237) until at least LeaseDuration time have passed since last renew time.

1. limit `tryAcquireOrRenew` not takes more than `LeaseDuration` - `RetryPeriod` time

**Comment by hzxuzhonghu** [comment]
cc @k8s-mirror-api-machinery-bugs

**Comment by DylanBLE** [comment]
@hzxuzhonghu  Thanks for the information.
I'm wondering if I can add scheduler's antiaffinity predict to kubelet's Admit function.
It will evict the pod with existing antiaffinity.

**Comment by k82cn** [comment]
> I'm wondering if I can add scheduler's antiaffinity predict to kubelet's Admit function.

We can not do that; AntiAffinity also supports "zone/topologyKey", but kubelet should not knows the status of other nodes. That's why we did not include Pod Affinity/Anti-Affinity in kubelet admit.
