### ISSUE TITLE
kube-proxy IPVS: wrongly unbind addr when update a multi-port service

### ISSUE THREAD

**Issue by xujieasd** [kubernetes/kubernetes#65263]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In kube-proxy IPVS mode, for every round of sync, kube-proxy will clean legacy service, and unbind legacy address from kube-ipvs0.  
But if there is a multi-port service, e.g
```
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE       SELECTOR
nginx        10.103.82.170   <nodes>       443:30393/TCP,80:30515/TCP   31m       app=nginx

```
and we update this service to a single-port service, e.g
```
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
nginx        10.103.82.170   <nodes>       80:30515/TCP   6s        app=nginx

```

we will see address `10.103.82.170` unbind from kube-ipvs0, because in function `cleanLegacyService`, we delete service `nginx:443:TCP` and unbind service ip `10.103.82.170` at the same time.  
This is unexpected!

**What you expected to happen**:

should not unbind service address when update a multi-port service

**How to reproduce it (as minimally and precisely as possible)**:

To effectively reproduce it, we need to set two kube-proxy flags as an appropriate number. e.g
```
--ipvs-min-sync-period=2m
--ipvs-sync-period=5m
```
because kube-proxy could resync very quickly (30s by default),  service address could bind in the next round of sync

1. create a service with multi-port
```
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE       SELECTOR
nginx        10.103.82.170   <nodes>       443:30393/TCP,80:30515/TCP   31m       app=nginx

```
2. check ipvs and ip addr status
```
$ ipvsadm -ln | grep 10.103.82.170
TCP  10.103.82.170:80 rr
TCP  10.103.82.170:443 rr

$ ip addr show kube-ipvs0 | grep 10.103.82.170
    inet 10.103.82.170/32 brd 10.103.82.170 scope global kube-ipvs0

```
3. update service to single-port
```
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
nginx        10.103.82.170   <nodes>       80:30515/TCP   6s        app=nginx
```

4. check ipvs and ip addr status, will see service `nginx:443:TCP` deleted from ipvs, but address `10.103.82.170` also unbound
```
$ ipvsadm -ln | grep 10.103.82.170
TCP  10.103.82.170:80 rr

$ ip addr show kube-ipvs0 | grep 10.103.82.170
```

**Anything else we need to know?**:

The point of the issue is: if a service has two ports, ipvs will think there are two services. But they share the same clusterIP.  
So, we could not directly unbind clusterIP after clean legacy ipvs service.  
A fix solution is like `cleanLegacyService`, we use an `activeBindAddrs` map and a `currentBindAddr` map. And unbind address which is in `currentBindAddr` map but not active

**Environment**:
- Kubernetes version (use `kubectl version`): newest
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`): 4.4.0-62-generic
- Install tools:
- Others:

/sig network
/area kube-proxy

**Comment by xujieasd** [comment]
I've submitted a PR #65264 to fix the issue

**Comment by tpepper** [comment]
This looks like a relatively minor bug, but @Lion-Wei do you think it is a candidate for 1.11 milestone inclusion (ie: cherrypick)?  If so, can you update the labels and milestone?

**Comment by Lion-Wei** [comment]
@tpepper Thanks for reminding. As you said, this is a minor bug, I don't think this have to be in 1.11.
