### ISSUE TITLE
kubectl apply with blank clusterIP leads to "spec.clusterIP: Invalid value: "": field is immutable" error

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#65272]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

/kind bug

**What happened**:

`kubectl apply -f svc,yml` when it is of type `clusterIP` but clusterIP isn't set can lead to an error of 

```
spec.clusterIP: Invalid value: "": field is immutable
```

I cannot fully reproduce, but it appears that when setting a (default) `clusterIP` type service, sometimes the `last-applied-configuration` annotation, rather than having no `clusterIP` setting, has `clusterIP: ""`.

This, in turn, causes `kubectl apply` to try and set it to `null`, which causes the above error.

**What you expected to happen**:
`kubectl apply` for a service should recognize that if the service has `type: clusterIP` (default), and the `clusterIP` value is set to `""`, then it should accept that is functionally equivalent to `null` and not try to patch it.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set the annotation `kubectl.kubernetes.io/last-applied-configuration` to include `clusterIP: ""`
2. `kubectl apply -f svc.yml` where `clusterIP` is not set
3. Fail

**Anything else we need to know?**:
I do not know why and when it set `clusterIP: ""` in the annotation, but it did.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client: 1.9.5, Server: 1.9.2

**Comment by deitch** [comment]
@kubernetes/sig-cli-bugs

**Comment by code-sleuth** [comment]
This is a duplicate of issue no. [#68369](https://github.com/kubernetes/kubernetes/issues/68369) and it was resolved.

cc: @liggitt 
/close

**Comment by thockin** [comment]
Because this came up again - `kubectl replace` (HTTP "PUT") is probably the wrong verb to be using.  `kubectl apply` should be better in most ways (acknowledging the issues around changing ambiguous ports, which may require a read-modify-replace cycle)
