### ISSUE TITLE
Azure cluster failing conformance tests due to DenyEscalatingExec Admission Controller

### ISSUE THREAD

**Issue by krisdock** [kubernetes/kubernetes#65271]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Sonobuoy results (run via scanner.heptio.com) show 5 failed tests:

[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: udp [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: http [Conformance]
[sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [Conformance]
[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: http [Conformance]
[k8s.io] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [Conformance]

Each had the same error listed:

> forbidden: cannot exec into or attach to a container using host network

This was due to the [DenyEscalatingExec](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#denyescalatingexec) Admission Controller being enabled.

**What you expected to happen**:

Not sure, but this is expected behavior when that Admission Controller is enabled. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an Azure cluster (v1.10.4) via acs-engine
2. Run a scan via scanner.heptio.com

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.4
- Cloud provider or hardware configuration: Azure
- Install tools: acs-engine

**Comment by timothysc** [comment]
Hey folks, this is part of the conformance suite, so I'm not certain what folks want todo here. 

/cc @brendanburns @kubernetes/sig-azure-misc @kubernetes/sig-architecture-bugs

**Comment by dims** [comment]
well, this is a similar situation to the `--privileged` flag. you cannot switch that off if you want to be conformant https://github.com/kubernetes/kubernetes/issues/59978

**Comment by yastij** [comment]
this is a dup of #64387

**Comment by khenidak** [comment]
+1 on @feiskyer 

@yastij has raised #64387 specifically for that.

**Comment by lachie83** [comment]
@krisdock We've removed the DenyEscalatingExec admission controller and I'm running the conformance tests across all versions. Let me know if this has resolved the issue.

**Comment by lachie83** [comment]
Here are the AKS 1.10 conformance results - https://github.com/cncf/k8s-conformance/pull/271

**Comment by lachie83** [comment]
Also ACS-Engine - https://github.com/cncf/k8s-conformance/pull/274

**Comment by lachie83** [comment]
@krisdock I believe this can be closed.

**Comment by yastij** [comment]
I think this has to remain open, as this has a wider impact than Azure. Any provider/distribution that enables DenyEscalatingExec fails e2e conformance tests.

**Comment by liggitt** [comment]
There are many configurations you can enable that prevent conformance tests from running, especially ones that limit permissions of normal namespaced users or pods.

This is not specific to this admission plugin, but is a general statement about the current state of conformance tests. See https://github.com/kubernetes/community/blob/master/contributors/devel/conformance-tests.md#conformance-testing-in-kubernetes:

> There are currently conformance tests that violate some of the requirements (e.g., require privileged access), we will be categorizing these tests and deciding what to do once we have a better understanding of the situation

/close
