### ISSUE TITLE
Time clock issue when deployed the new services

### ISSUE THREAD

**Issue by zhucebuliaolongchuan** [kubernetes/kubernetes#65278]
@kubernetes/sig-network-bugs

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
 

**What happened**:
It is a time clock issue. I used helm to deploy the kubernetes services. Once I deployed it, the age of the newly deployed services said my services have been deployed 15 mins ago.

**What you expected to happen**:
The age of them should be in a few seconds for newly deployed services.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. It randomly happens. It might because my laptop ran out of power for a few minutes.

**Anything else we need to know?**:
My laptop runs out of battery for 15 mins before I deployed those services. It might because the kubernetes get the current time from the os kernel which is not a real current time. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
local minikube setup: minikube start --kubernetes-version v1.8.0 --memory 6144 --cpus 2 --disk-size 60g
```
- OS (e.g. from /etc/os-release):
`macOS high Sierra Version 10.13.4`
- Kernel (e.g. `uname -a`):
- Install tools:
`homebrew`
- Others:
`Use helm to deploy the services`

**Comment by dims** [comment]
Can you please try https://github.com/kubernetes/minikube folks first?

/close
