### ISSUE TITLE
Change Azure ARM Rate limiting error message

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#65284]
/kind bug

**What happened**:
Kubernetes v1.10 introduced a better rate limiting (when calling ARM), however the error message here: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_client.go#L41 is misleading. The error is not `ARM` but `cloud provider` rate limiter.   

**What you expected to happen**:
Correct error message that clearly states `cloud provider`

**Comment by khenidak** [comment]
@jdumars I am a member of `kubernetes` yet i unable to `assign` -- Is this something you can help with?

**Comment by wgliang** [comment]
If there was no one working on this, I can help fix it.
/assign

**Comment by feiskyer** [comment]
> @jdumars I am a member of kubernetes yet i unable to assign -- Is this something you can help with?

This is because kkmsft is not a member.

**Comment by khenidak** [comment]
Oh ok - thanks.

Let kk take care of it. We are trying on ramp more folks on upstream

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kkmsft** [comment]
@wgliang I am working on this...,
