### ISSUE TITLE
Strange behavior running kubectl create with --template and --dry-run flags

### ISSUE THREAD

**Issue by mikejoh** [kubernetes/kubernetes#65282]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

_Possible bug!_

**What happened**:
When running some simple `kubectl create deployment` tests with the `--template` and `--dry-run` flags i've seen some strange behavior. I ran the following commands:
```
Run 1:
$> kubectl create deployment my-dep --image nginx --template='foo' --dry-run
deployment.extensions "my-dep" created (dry run)

Run 2:
$> kubectl create deployment my-dep --image nginx --template='' --dry-run
deployment.extensions "my-dep" created (dry run)

Run 3:
$> kubectl create deployment my-dep --image nginx --template= --dry-run
deployment.extensions "my-dep" created (dry run)

Run 4:
$> kubectl create deployment my-dep --image nginx --template --dry-run
deployment.extensions "my-dep" created

Run 5:
$> kubectl create deployment my-dep --image nginx --dry-run --template
Error: flag needs an argument: --template

Run 6:
$> kubectl create deployment my-dep --image nginx --dry-run --template=''
deployment.extensions "my-dep" created (dry run)
```

In the fourth attempt, the deployment gets created although the usage of the `--template` flag is wrong (no argument) _and_ the `--dry-run` flag are set. I've seen the same behavior as above but with the `--sort-by` flag when it's set without any arguments. 

The order of the flags seems to be important, when the `--dry-run` flag are set before the `--template` and `--sort-by` flags kubectl exits with an error. See the fifth run above.

I looked through the issues and tried to find any mentioning anything similar to this but without any luck.

**What you expected to happen**:
Running `kubectl create` as below should result in a `Error: flag needs an argument: --template` message and the deployment should not be created as shown above.

```
$> kubectl create deployment my-dep --image nginx --template --dry-run 
```

**How to reproduce it (as minimally and precisely as possible)**:
Basically by running the commands mentioned above in the **What happened**-section, i tested this on a VM based cluster in GCE and minikube (`v0.27.0`) locally on my laptop.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
`Mac OSX 10.13.5`
- Kernel (e.g. `uname -a`): 
`Darwin Kernel Version 17.6.0`
- Install tools:
- Others:

**Comment by mikejoh** [comment]
@kubernetes/sig-cli-bugs

**Comment by liggitt** [comment]
```
$> kubectl create deployment my-dep --image nginx --template --dry-run
deployment.extensions "my-dep" created
```

in that invocation, you specified `--template`, which requires a value. you can either specify a value with `--template=<value>` or `--template <value>`. Your invocation was interpreted as: "create the deployment, and set --template to "--dry-run", but don't actually make use of that template because my output type is not set to -o=go-template"

**Comment by mikejoh** [comment]
Thanks for the clarification, i was on this track from the beginning but assumed things like if there's a `--dry-run` flag then the command would exit with appropriate message(s) but in this case `kubectl` would just pick that up as a argument to a specific flag. Also i was using the flag in a incorrect way from the beginning while testing random combinations.
