### ISSUE TITLE
OpenStack Cloud Provider doesn't support special characters in password

### ISSUE THREAD

**Issue by Kanshiroron** [kubernetes/kubernetes#65304]
Kubernetes: v10.0.4

I had an issue trying to configure Kubernetes with the OpenStack cloud provider, the controller-manager continue crashing saying that Keystone rejected authentication (403). I finally got it fixed when I changed my password. So I'm wondering whether Kubernetes doesn't have an issue with special characters in password.

In my cloud provider configuration file I had:
```
[Global]
auth-url=https://url
username=username
password=[842}4q;cx3B
region=RegionOne
tenant-id=123456
```
I tried to surround the password with quotes (`password="[842}4q;cx3B"`) but that didn't solve the issue. Also I didn't make further investigations to know which character causes the issue (`[`, `}`, or the `;`)

Best,

**Comment by skeetwu** [comment]
Got same issue.
`< > * \ / `
characters can be allowed by OpenStack API, but kubelet can't start up when them exist in password.
