### ISSUE TITLE
eviction manager ignore pods created by daemonset, kubelet manifest and statefulset.

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#65300]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

kind feature

**What happened**:
For pods created by daemonset, kubelet manifest and statefulset, if they are evicted due to node resource pressure, they will scheduled back  which leaves a lot of "dead pod bodies",

**What you expected to happen**:
Eviction manager ignore these kinds of pods.

**How to reproduce it (as minimally and precisely as possible)**:
Create a daemonset, make the node under MemoryPressure, you will see a lot of pods with "evicted" status. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  v1.9.6
- Docker version
  17.12.1-ce
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
  3.10.0-862.3.2.el7.x86_64
- Install tools:
- Others:

**Comment by yastij** [comment]
cc @k82cn @janetkuo

**Comment by DylanBLE** [comment]
@k82cn Thanks for your information, it's very helpful.

**Comment by DylanBLE** [comment]
FYI: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-nodes-by-condition
