### ISSUE TITLE
Google oidc issuer mismatch: https://accounts.google.com and accounts.google.com

### ISSUE THREAD

**Issue by cainelli** [kubernetes/kubernetes#65317]
/kind bug

**What happened**:

kube-apiserver does not accept Google id tokens with issuer `accounts.google.com` after upgrading from 1.8.5 to 1.10.4.

**What you expected to happen**:

kube-apiserver should accept both issuers `https://accounts.google.com` and `accounts.google.com` since not all clients support setting oidc-issuer-url. This used to work on previous versions (1.8.5 at least) and is a special case [also handled](https://github.com/coreos/go-oidc/pull/132) by go-oidc library.

**How to reproduce it**:

Enabling oidc on kube-apiserver for Google adding the following flags:

```
        - --oidc-issuer-url=https://accounts.google.com
        - --oidc-username-claim=email
        - --oidc-client-id=xxxxx.apps.googleusercontent.com
```

Request an id token using [Google Platform Library](https://developers.google.com/identity/sign-in/web/sign-in)

```javascript
googleUser.getAuthResponse().id_token
```

Decoding it we will get something like:

```json
{
  "azp": "xxx.apps.googleusercontent.com",
  "aud": "xxx.apps.googleusercontent.com",
  "sub": "0000000000000000000",
  "hd": "getyourguide.com",
  "email": "fernando.cainelli@getyourguide.com",
  "email_verified": true,
  "at_hash": "xxxx",
  "exp": 0000000000,
  "iss": "accounts.google.com",
  "jti": "00000000000000000000fffffffffffffffffffffffffffff",
  "iat": 000000000,
  "name": "Fernando Cainelli",
  "picture": "https://lh4.googleusercontent.com/-EM4cnHQGQFU/AAAAAAAAAAI/AAAAAAAAABQ/uh-Ss3jtc4M/s96-c/photo.jpg",
  "given_name": "Fernando",
  "family_name": "Cainelli",
  "locale": "en"
}
```

Use the generated id token on the `Authorization` header to authenticate against kube-apiserver.

``` bash
$ curl https://api.testing1.domain.com:443/apis --insecure -H "Authorization: $TOKEN"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}%
```

Doing the same thing but using an id token requested by using [go-oidc](https://github.com/coreos/go-oidc) works. It generates something like:

```json
{
  "azp": "xxx.apps.googleusercontent.com",
  "aud": "xxx.apps.googleusercontent.com",
  "sub": "0000000000000000000",
  "hd": "getyourguide.com",
  "email": "fernando.cainelli@getyourguide.com",
  "email_verified": true,
  "at_hash": "xxxx",
  "exp": 0000000000,
  "iss": "https://accounts.google.com",
  "iat": 000000000,
  "name": "Fernando Cainelli",
  "picture": "https://lh4.googleusercontent.com/-EM4cnHQGQFU/AAAAAAAAAAI/AAAAAAAAABQ/uh-Ss3jtc4M/s96-c/photo.jpg",
  "given_name": "Fernando",
  "family_name": "Cainelli",
  "locale": "en"
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS - m4.2xlarge

- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
```
Linux master2.sandbox1.gygkube.com 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```

- Install tools:
Terraform + bootkube

**Comment by mikedanese** [comment]
It's also handled by the spec for historic reasons:

http://openid.net/specs/openid-connect-core-1_0.html#GoogleIss

However I thought that we moved off old token endpoints. I'm not sure why this is happening for you. This change was discussed here: https://github.com/kubernetes/kubernetes/pull/58544#discussion_r164279467

**Comment by mikedanese** [comment]
Also the current config shows the correct issuer:

```json
{
 "issuer": "https://accounts.google.com",
 "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
 "token_endpoint": "https://www.googleapis.com/oauth2/v4/token",
 "userinfo_endpoint": "https://www.googleapis.com/oauth2/v3/userinfo",
 "revocation_endpoint": "https://accounts.google.com/o/oauth2/revoke",
 "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs",
 "response_types_supported": [
  "code",
  "token",
  "id_token",
  "code token",
  "code id_token",
  "token id_token",
  "code token id_token",
  "none"
 ],
 "subject_types_supported": [
  "public"
 ],
 "id_token_signing_alg_values_supported": [
  "RS256"
 ],
 "scopes_supported": [
  "openid",
  "email",
  "profile"
 ],
 "token_endpoint_auth_methods_supported": [
  "client_secret_post",
  "client_secret_basic"
 ],
 "claims_supported": [
  "aud",
  "email",
  "email_verified",
  "exp",
  "family_name",
  "given_name",
  "iat",
  "iss",
  "locale",
  "name",
  "picture",
  "sub"
 ],
 "code_challenge_methods_supported": [
  "plain",
  "S256"
 ]
}
```

**Comment by cainelli** [comment]
Thanks for getting into this @mikedanese. Apparently there are still client libraries, including maintained by Google that still uses the old API to generate id tokens. I agree that handling vendor-specific exceptions is not a good fit long term but that is indeed a breaking change.

**Comment by cainelli** [comment]
And according to Google's [documentation](https://developers.google.com/identity/sign-in/web/backend-auth), a token still may contain both values.

>The value of iss in the ID token is equal to accounts.google.com or https://accounts.google.com.

**Comment by jtolsma** [comment]
Just tried to upgrade a cluster from 1.9.8 to 1.10.5 and had the same issue where Bearer tokens for OIDC clients are receiving 401's.  I have the same configuration as described in initial post.  Are there workarounds or fixed in other versions?

**Comment by ericchiang** [comment]
We changed this because the https://accounts.google.com/.well-known/openid-configuration was supposed to return the correct token endpoint to use.

@jtolsma can you switch to that token endpoint? It sounds like that solved the issue for @cainelli

**Comment by cainelli** [comment]
I was using [google's javascript library](https://developers.google.com/identity/sign-in/web/sign-in) to auth proxy kubernetes dashboard.

[This](https://gist.github.com/cainelli/7ea47fa68609ca61283f4478b4880834) still produces an id token issued as `accounts.google.com` instead of `https://accounts.google.com`.

I had to stop to use the JS library and moved to a patched version of [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy) because I couldn't get the same behavior as our original solution out of the box. This is way more complex and https://github.com/kubernetes/kubernetes/pull/68850 would totally help us.

**Comment by mikedanese** [comment]
If people are still using the old token endpoint, I'm not sure we can just drop support for it. The number of :+1: s on this issue indicates that old auth and token endpoints are still in use.

**Comment by jtolsma** [comment]
Yes, we have switched to the new endpoint and it is working now.
