### ISSUE TITLE
Bubble up the reason for killing a container

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#6532]
The kubelet restarts containers when a liveness probe fails, but the events don't show this. This makes it hard to debug cases with bad liveness probes because it will appear like the container is crashing, docker logs won't show anything really wrong with the container, but the kubelet will keep restarting it. 

My events from a pod with a bad liveness probe:
```
  Tue, 07 Apr 2015 12:08:30 -0700	Tue, 07 Apr 2015 12:08:30 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			killing		Killing 0b7743acd1a5f54aeccf4fe16c8cfbaa5e935a541c2fca59150cc250f7035d4e
  Tue, 07 Apr 2015 12:08:31 -0700	Tue, 07 Apr 2015 12:08:31 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			created		Created with docker id 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:08:31 -0700	Tue, 07 Apr 2015 12:08:31 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			started		Started with docker id 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			killing		Killing 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			created		Created with docker id 9b2a0596d1c9a0badf0ac07e5a2d4d74e71e2654177be26217e5a376a8062ca4
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			started		Started with docker id 9b2a0596d1c9a0badf0ac07e5a2d4d74e71e2654177be26217e5a376a8062ca4

```

I would find it easier if there was a reason in there like: the probe on ip:port/url failed

**Comment by bgrant0607** [comment]
Yes, the probe failure is logged, which doesn't help users very much.
https://github.com/kubernetes/kubernetes/blob/84f8f01d45f0decc33ad338f3eb8b8a28ce1e3d9/pkg/kubelet/dockertools/manager.go#L1727

Would you be interested in taking a look @jiangyaoguo?

**Comment by jiangyaoguo** [comment]
@bgrant0607  OK. We are on a vacation recently. Tomorrow we'll back to work and track what we've missed.
