### ISSUE TITLE
NoExecuteTaintManager queue consumes large amounts of memory

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#65325]
We're seeing an issue with large memory growth in NoExecuteTaintManager when pods with tolerations are rapidly created/deleted.

The item added to the workqueue contains the full pod objects received from the informer:
https://github.com/kubernetes/kubernetes/blob/23b4690d00670102fb319c0546262ebd083cf110/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L301-L307

That means those pod objects are retained until they are processed. Additionally, it looks like the processing loop never removed the keys from the workqueue when it was done.

It also means that multiple updates for the same pod result in multiple items in the workqueue, rather than enqueuing the pod to be processed once, like other controllers do.

Simplifying this controller to enqueue pod updates only by name/namespace, and operate on the latest pod obtained from the store (like other controllers do) would speed up the processing and relieve the memory burden of the workqueue.

/sig scheduling
/cc @mfojtik @wojtek-t

**Comment by wojtek-t** [comment]
Thanks for finding this Jordan - looking into your fixes.

**Comment by liggitt** [comment]
the memory issue was fixed by https://github.com/kubernetes/kubernetes/pull/65339

/close
