### ISSUE TITLE
Stats summary endpoint listing two containers with same name

### ISSUE THREAD

**Issue by Typositoire** [kubernetes/kubernetes#65332]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: When creating a pod with `securityContext.privileged: true`, Stats summary endpoint list 2 container with the same name for the pod. One with CPU 0 and MEMORY 0, and the other one with good values.

(PS: they are from the same podRef)
```console
curl -s http://172.20.74.96:10255/stats/summary | grep concourse-worker -A 6
     "name": "concourse-worker-1",
     "namespace": "sre-concourse",
     "uid": "ab46c728-757d-11e8-ab9a-0e41f808ae3c"
    },
    "startTime": "2018-06-21T18:05:24Z",
    "containers": [
     {
      "name": "concourse-worker",
      "startTime": "2018-06-21T18:05:25Z",
      "cpu": {
       "time": "2018-06-21T18:23:37Z",
       "usageNanoCores": 0,
       "usageCoreNanoSeconds": 0
      },
--
      "name": "concourse-worker",
      "startTime": "2018-06-21T18:05:24Z",
      "cpu": {
       "time": "2018-06-21T18:23:36Z",
       "usageNanoCores": 203241463,
       "usageCoreNanoSeconds": 194938403350
      },
```

**What you expected to happen**: I expected to see only one container for my pod.

**How to reproduce it (as minimally and precisely as possible)**: Create a deployment with `securityContext.privileged: true`.

**Anything else we need to know?**: It screws with metrics-server & HPA, that how I stumbled upon this.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Whatever comes with Kops Version 1.9.0 (git-cccd71e67)
- Kernel (e.g. `uname -a`): Whatever comes with Kops Version 1.9.0 (git-cccd71e67)
- Install tools: Kops
- Others: Nothing.

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-node-bugs @kubernetes/sig-instrumentation-bugs

**Comment by DirectXMan12** [comment]
For further reference, the last time I saw something like this, it was because cadvisor's cgroup-guessing logic was confused by something (there's a long fixed bug involving the systemd cgroup driver, for instance), and was seeing two cgroup paths for the same container, and treating them as two separate containers.

**Comment by loburm** [comment]
@DirectXMan12 I think this is an issue: https://github.com/kubernetes/kubernetes/issues/47853

Probably heuristic that was added in the fix is not working in some cases.

**Comment by Typositoire** [comment]
Any updates on this ?
