### ISSUE TITLE
client-go: using a fake client is difficult and undocumented

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#65333]
/kind documentation
/sig api-machinery

I tried to write a test that injected a fake client into my component, and found that the existing fake tools are rather difficult to use.

- There is a large API surface (exported types and functions), but I think most of it should not be touched by users like me.
  e.g. is playing with Actions and Reactors something that test writers need access to?
- There is no clear entry point. I believe the correct answer is [fake.Clientset](https://godoc.org/k8s.io/client-go/kubernetes/fake#Clientset) but that is only after reading a lot of the code.
- When my informers received no events, I wasn't sure if it was a bug in the library or if I was using it incorrectly. (It turned out it was a bug fixed by https://github.com/kubernetes/kubernetes/pull/57504)

/ref https://github.com/kubernetes/kubernetes/issues/65036

**Comment by misterikkit** [comment]
I made a start on this by writing some example code in https://github.com/kubernetes/kubernetes/pull/65291.

I'm sure the example could be fleshed out for more use-cases, and there is still no documentation on how the fake client is meant to be used.

**Comment by misterikkit** [comment]
/remove-lifecycle stale

This is still on my list of things to look at.

**Comment by misterikkit** [comment]
/remove-lifecycle stale

This and https://github.com/kubernetes/kubernetes/issues/65036 are worth pursuing.

**Comment by davidxia** [comment]
Hope people don't mind me removing the stale label from this. I'd find this useful too.

/remove-lifecycle stale
