### ISSUE TITLE
Remove Cloud Controller Manager deb from Kubernetes Releases

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#65337]
**Is this a BUG REPORT or FEATURE REQUEST?**
We should stop including the deb for CCM https://github.com/kubernetes/kubernetes/blob/master/build/debs/BUILD#L16 as part of Kubernetes releases. Given we almost always see cloud controller manager run within a container (as recommended). This is consistent with other controllers. 

/kind bug

/sig release
/sig cluster-lifecycle
/sig cloud-provider

cc @luxas

**Comment by luxas** [comment]
Resolved in https://github.com/kubernetes/kubernetes/pull/65338 :tada:
