### ISSUE TITLE
Proto format: Use standard wrapper mechanisms

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#65344]
Some standard mechanisms for making fields optional in proto are here:

https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto

We should use them for indicating optional fields when we rev our proto generator, if we ever do that.

/sig api-machinery
/priority important-longterm

cc @smarterclayton

**Comment by smarterclayton** [comment]
I'm not even sure we can update to proto3 and keep a compatible format (I can't remember).
