### ISSUE TITLE
 K8s.gcr.io/fluentd-elasticsearch:v2.2.0 does not exist.

### ISSUE THREAD

**Issue by DevOps-Alvin** [kubernetes/kubernetes#65355]
I discovered that the k8s.gcr.io/fluentd-elasticsearch:v2.2.0 image does not exist when I use the discovery cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml template in the deployment EFK.

![20180622153331](https://user-images.githubusercontent.com/26085539/41763799-c6f4fada-7631-11e8-8c04-f63a3f34b43f.png)

/kind bug
/sig scheduling

**Comment by jeevanjoseph** [comment]
I got the same. I am now trying to build the docker image myself and change the `fluentd-es-ds.yaml` to point to my image...

**Comment by jeevanjoseph** [comment]
Not sure if I'm looking at the right place, but 

[gcr.io](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch?gcrImageListsize=50&gcrImageListsort=-uploaded)

seems to have 2.1.0 as the most recent tag. I haven't tried it pulling it yet...

**Comment by jeevanjoseph** [comment]
yep downgrading to v2.1.0 works.

**Comment by stewart-yu** [comment]
seems has been reverted
/assign

**Comment by monotek** [comment]
This is the template for the image which has to be build manually by some googler...

**Comment by stewart-yu** [comment]
I know it is a template, but i want to know why change `k8s.gcr.io/fluentd-elasticsearch` image'tag from `v2.1.0` to `v2.2.0`? seems no this image in `GCR` hub now, so strange? @monotek

**Comment by monotek** [comment]
The image has to be build from the template so the template has to be there before the image.

**Comment by DevOps-Alvin** [comment]
I temporarily use v2.1.0, later need to replace or replace k8s.gcr.io repository v2.2.0

**Comment by coffeepac** [comment]
probably should be /sig instrumentation  I'll go ask some people.

**Comment by coffeepac** [comment]
is this causing a failure anywhere in the e2e tests?  if it is, we can roll back to 2.1.0 until the new image is built.

**Comment by DevOps-Alvin** [comment]
I have no problems using v2.10 in a test environment

**Comment by coffeepac** [comment]
elasticsearch image 2.2.0 now exists.  apologies for the delay.
