### ISSUE TITLE
IPVS does not work with kubenet when no masquerading options are set

### ISSUE THREAD

**Issue by lbernail** [kubernetes/kubernetes#65358]
/kind bug
/sig network
/area ipvs

**What happened**:
When accessing a service from a pod, traffic to pods on the same host is dropped when using:
- IPVS
- kubenet
- kube-proxy without masquerade-all or cluster-cidr

**What you expected to happen**:
Accessing pods (through service IP) on the same node should work

**How to reproduce it (as minimally and precisely as possible)**:
- Use kube-proxy with `--proxy-mode=ipvs` and no masquerading option, configure kubelet with `--network-plugin=kubenet`
- create a service and matching deployment with a single pod
- create a pod on the host where the pod from the deployment has been scheduled
- access the service from this new pod
- connection will fail

**Anything else we need to know?**:
This is related to the following ebtables rules:
```
sudo ebtables -L
Bridge table: filter
Bridge chain: OUTPUT, entries: 1, policy: ACCEPT
-j KUBE-DEDUP

Bridge chain: KUBE-DEDUP, entries: 2, policy: ACCEPT
-p IPv4 -s 56:fa:49:18:9e:ff -o veth+ --ip-src 10.1.243.1 -j ACCEPT
-p IPv4 -s 56:fa:49:18:9e:ff -o veth+ --ip-src 10.1.243.0/24 -j DROP
```
Traffic from the bridge (cbr0) mac address (here `56:fa:49:18:9e:ff`) and from the local pod CIDR (here `10.1.243.0/24` except the bridge (here `10.1.243.1`) will be dropped.

Traffic exiting the pod will have:
- src IP: source pod IP
- src MAC: source pod MAC
- dst IP: service IP
- dst MAC: cbr0 mac address

After IPVS:
- src IP: src pod IP (not changed)
- src MAC: cbr0 mac address
- dst IP: dst pod IP
- dst MAC:  dst pod MAC

And traffic will be dropped by the ebtables rule

In iptables mode, traffic exiting the pod look the same, but after hitting the PREROUTING chain we have the following:
- src IP: src pod IP (not changed)
- src MAC: **src pod MAC (not changed)**
- dst IP: dst pod IP
- dst MAC:  dst pod MAC

Since the source MAC address is not cbr0 traffic will not be dropped by the ebtables rule. (I don't really understand what this DEDUP chain is for)

My understanding is that since iptables modifies the destination in the PREROUTING chain, packets are not routed but simply bridged and keep their source MAC address.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.10.3`
- Cloud provider or hardware configuration: `GCE`
- OS (e.g. from /etc/os-release): `ubuntu 1804`
- Kernel (e.g. `uname -a`): `4.15.0-1008-gcp`

**Comment by m1093782566** [comment]
/cc @Lion-Wei 

Please take a look.

**Comment by Lion-Wei** [comment]
As this issue mentioned, I think change hairpin-mode to `hairpin-veth` can fix this problem. 
https://github.com/kubernetes/kubernetes/issues/60257

**Comment by lbernail** [comment]
I confirm it works by changing the hairpin-mode
(restarting kubelet is not enough because it does not clear the ebtables chain)

The issue that remains is that if you switch kube-proxy to ipvs with kubenet in default hairpin-node without doing anything it will break a working setup.

Probably not a big deal since kubenet should be deprecated in the future (but maybe worth a note in the release note when ipvs becomes the default)

**Comment by lbernail** [comment]
Sorry if it was unclear: if someone has a kubernetes installation running with kubenet and kube-proxy in iptables mode and simply decide to change to ipvs it will break.

In our case for instance we run kube-proxy has a daemonset and just modified the `proxy-mode` flag to test ipvs

**Comment by Lion-Wei** [comment]
That' true. But as you mentioned kubenet should be deprecated in the future, so should not be a big deal. : )

**Comment by Lion-Wei** [comment]
Can we close this issue for now?

**Comment by lbernail** [comment]
@Lion-Wei sure. I created this issue after a quick discussion on the Kubernetes slack, mostly to document it

**Comment by shufanhao** [comment]
I also hit this issue, just want to know why kube-proxy enable masquerade, can fix this issue ? if enable masquerade,  it can not match ebtables rule, like below: 
```
-p IPv4 -s a:58:ac:1c:1:1 -o veth+ --ip-src 172.28.1.0/24 -j DROP
```
