### ISSUE TITLE
`system-node-critical` is not handled in kubelet

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#65372]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

Found the issue when investigate https://github.com/kubernetes/kubernetes/issues/65192 :

In scheduler, it found `fluentd-gcp-v3.0.0-kwbqj` can not be scheduled because of insufficient cpu and trigger preemption (node-critical > cluster-critical); but in kubelet, it'll not preempt any 'critical' pods, refer to the following logs for the detail. 

scheduler log:

```
I0620 20:48:16.832423       1 factory.go:1416] Updating pod condition for kube-system/fluentd-gcp-v3.0.0-kwbqj to (PodScheduled==False)
I0620 20:48:16.871162       1 generic_scheduler.go:1002] Node bootstrap-e2e-master is a potential node for preemption.
I0620 20:48:16.900337       1 factory.go:1181] About to try and schedule pod fluentd-gcp-v3.0.0-kwbqj
I0620 20:48:16.900385       1 scheduler.go:447] Attempting to schedule pod: kube-system/fluentd-gcp-v3.0.0-kwbqj
I0620 20:48:16.900799       1 scheduler.go:194] Failed to schedule pod: kube-system/fluentd-gcp-v3.0.0-kwbqj
I0620 20:48:16.900835       1 factory.go:1303] Unable to schedule kube-system fluentd-gcp-v3.0.0-kwbqj: no fit: 0/4 nodes are available: 1 Insufficient cpu, 3 node(s) didn't match node selector.; waiting
I0620 20:48:16.900887       1 factory.go:1416] Updating pod condition for kube-system/fluentd-gcp-v3.0.0-kwbqj to (PodScheduled==False)
I0620 20:48:17.761558       1 factory.go:1181] About to try and schedule pod fluentd-gcp-v3.0.0-kwbqj
I0620 20:48:17.761618       1 scheduler.go:447] Attempting to schedule pod: kube-system/fluentd-gcp-v3.0.0-kwbqj
I0620 20:48:17.769339       1 scheduler_binder.go:194] AssumePodVolumes for pod "kube-system/fluentd-gcp-v3.0.0-kwbqj", node "bootstrap-e2e-master"
I0620 20:48:17.769422       1 scheduler_binder.go:197] AssumePodVolumes for pod "kube-system/fluentd-gcp-v3.0.0-kwbqj", node "bootstrap-e2e-master": all PVCs bound and nothing to do
I0620 20:48:17.769507       1 factory.go:1407] Attempting to bind fluentd-gcp-v3.0.0-kwbqj to bootstrap-e2e-master
```

kubelet log:

```
W0620 20:48:17.949156    1506 predicate.go:107] Failed to admit pod fluentd-gcp-v3.0.0-kwbqj_kube-system(41eec71a-74cb-11e8-854a-42010a800002) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: cpu, q: 37), ]
```

/sig scheduling
/sig node

**Comment by bsalamat** [comment]
I think this is WAI.
@dashpole can give more details.

**Comment by k82cn** [comment]
oh, here's more details in kubelet:

In `IsCriticalPod`, it only check pod's priority is bigger than `scheduling.SystemCriticalPriority`; that makes `sortPodsByQOS` skipped `cluster critical` pods for `node critical` pods.

`IsCriticalPod`:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/pod_update.go#L166

And `sortPodsByQOS`:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/preemption/preemption.go#L231

**Comment by dashpole** [comment]
The "kubelet preemption" feature was introduced before priority + preemption, and thus only relies on whether we deem the pod critical or not.  It looks like the actual problem here is that the node doesn't have enough room for the fluentd pod?

**Comment by k82cn** [comment]
@dashpole , scheduler compares priority: the bigger one can preempt smaller one; and `NodeCritical` is `CriticalPriority + 1000`. So `sortPodsByQOS` should check critical annotation (for compatibility) and compare pod's priority (instead of checking whether the preemptee pod's priority is bigger/equal than `critical-priority`) if priority/preemption enabled.

I'm thinking that may contribute  #65192: the cluster-critical occupied the resource, which can be re-scheduled to the other node (fluented pod is node-critical according to the [yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml)). But no log to prove that :(
