### ISSUE TITLE
flag help for --watch-cache-sizes is wrong about group being optional

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#65393]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I wanted to set the watch cache size for some Kinds, and realized I was unsure of the syntax.  After investigation and prompting, the flag help was updated to describe the syntax.  But the description has an error.  The flag help (https://github.com/kubernetes/kubernetes/blob/5e9a5659b751bd1d765758548273198fe8e40642/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L141) says the group is optional.  But the code makes it clear that the group is NOT optional.  See how https://github.com/kubernetes/kubernetes/blob/5e9a5659b751bd1d765758548273198fe8e40642/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L289 invokes schema.ParseGroupResource, which does _not_ do any normalization --- the group appears in the result if and only if the user supplied the group in the string on the command line.  See how https://github.com/kubernetes/kubernetes/blob/5e9a5659b751bd1d765758548273198fe8e40642/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L228 and https://github.com/kubernetes/kubernetes/blob/5e9a5659b751bd1d765758548273198fe8e40642/staging/src/k8s.io/apiserver/pkg/server/options/etcd.go#L261 index the map by the canonical `schema.GroupResource` and only that.  So if the user supplies the group and the canonical `schema.GroupResource` elides the group, or if the user elided the group and the canonical `schema.GroupResource` includes the group, the user's entry in the map will not be found.

**What you expected to happen**:
I expected the command line flag help to be accurate.

**How to reproduce it (as minimally and precisely as possible)**:
I think the code inspection is easier than a demo in this case.  If you want a demo, run an apiserver with `-v=5 --watch-cache-sizes=pods.core#1701,jobs#1071` and look at the debug messages about the watch cache sizes used for pods and jobs.

**Anything else we need to know?**:
no

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by yliaog** [comment]
lgtm'ed on the pr #65397
