### ISSUE TITLE
godep-save remove all  "BUILD" file

### ISSUE THREAD

**Issue by eisig** [kubernetes/kubernetes#65403]
I am trying  to update  aws-sdk-go dep version, following the guide in
https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

I checkout to the master branch, and I use these commands:
```
hack/run-in-gopath.sh hack/godep-restore.sh -v
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/aws/aws-sdk-go'
hack/run-in-gopath.sh go get -d github.com/aws/aws-sdk-go
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/aws/aws-sdk-go checkout v1.14.10'
hack/run-in-gopath.sh hack/godep-save.sh
```
But all the "BUILD" files in the "vendor" folder are deleted.
```
vendor/k8s.io/utils/clock/BUILD"
vendor/ks.io/utils/exec/BUILD
vendor/k8s.io/utils/exec/testing/BUILD
...
```
What did i do wrong？What are the right steps?

When I use the same commands in the "release-1.9" branch,  all these files are not changed.

**Comment by nikhita** [comment]
I came across this recently as well.

> When I use the same commands in the "release-1.9" branch, all these files are not changed.

same for me.

/kind bug

**Comment by nikhita** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/61575 is the culprit?

/cc @cblecker @ixdy

**Comment by nikhita** [comment]
> What did i do wrong?

@eisig you didn't do anything wrong. :)

> What are the right steps?

Updating bazel files again will solve the problem for now:

```
hack/run-in-gopath.sh hack/update-bazel.sh
```

But we should either fix the script or update the instructions.

**Comment by cblecker** [comment]
This should run already as a part of godep-save.sh:
https://github.com/kubernetes/kubernetes/blob/ec37c0f643014727173c7cfbb3a389133a284ba1/hack/godep-save.sh#L85-L91

Is that step producing any errors?

**Comment by eisig** [comment]
There are not any error message.
Here is the output:
```
+++ [0625 02:13:34] Ensuring prereqs
+++ [0625 02:13:34] Running godep save - this might take a while
+++ [0625 02:23:00] Updating BUILD files
wrote "vendor/BUILD"
+++ [0625 02:23:07] Updating LICENSES file
+++ [0625 02:23:20] Creating OWNERS file
```

**Comment by ixdy** [comment]
yeah, I can reproduce this - running `hack/run-in-gopath.sh hack/godep-save.sh` yields lots of missing `BUILD` files.

still investigating, but I'm guessing the `BUILD` files are being generated in the generated gopath (from `hack/run-in-gopath.sh`, rather than the repo root.

**Comment by ixdy** [comment]
... though that shouldn't matter, since it's just a symlink. hm.

**Comment by cblecker** [comment]
I think I found it.. I think it has to do with the fact that the init script uses `pwd -P` to strip out symlinks, which doesn't play nice with `run-in-gopath.sh`.

https://github.com/kubernetes/kubernetes/blob/759f3e21da9192649a7e30ac22ed8d0eb0ee50b3/hack/lib/init.sh#L25-L26

I'm testing a fix locally.. if it works, I'll push a PR. I don't know if removing the `-P` flag will break other things tho.

**Comment by cblecker** [comment]
Nope. That didn't work. Next test I'm running is a revert of #64122.

**Comment by ixdy** [comment]
after running `hack/run-in-gopath.sh hack/godep-save.sh`, if I then run `hack/run-in-gopath.sh hack/update-bazel.sh`, it still doesn't regenerate the `BUILD` files, which makes me think `gazelle` doesn't like running in the artificial gopath.

**Comment by ixdy** [comment]
`gazelle` seems to need to run from the real `$KUBE_ROOT` (or at least a subdir of the real `$KUBE_ROOT`).

`kazel` seems to need to run from a valid `$GOPATH`.

If I `cd` to the real `$KUBE_ROOT` in `hack/update-bazel.sh`, `gazelle` works properly, but `kazel` then explodes.

**Comment by cblecker** [comment]
Just a straight revert of that last change didn't work either. I wonder how long this has been broken for..

**Comment by jayconrod** [comment]
@ixdy When Gazelle starts, it locates the repository root (if `-repo_root` is not given, it's the nearest parent directory containing a file named `WORKSPACE`), then evaluates symlinks in that path.

When Gazelle walks the directory tree, it only follows symlinks to directories that point outside the  repository. It checks that by evaluating symlinks, then checking whether the resolved path has the resolved repository root as a prefix. This is all in service of avoiding symlink cycles and preventing the same directory from being visited on more than one path (which would cause incorrect or inconsistent `importpath` attributes).

**Comment by ixdy** [comment]
@cblecker I'd guess since #51766.

**Comment by jayconrod** [comment]
So I think passing `-repo_root <dir>` to Gazelle would fix it. Then it won't go looking outside the GOPATH for the WORKSPACE file.

**Comment by ixdy** [comment]
`-repo_root` alone doesn't seem to be helping, at least not if I set it to the real repo root.

```console
$ hack/run-in-gopath.sh hack/update-bazel.sh
...
+ pwd
[HOME]/code/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
+ echo GOPATH=[HOME]/code/kubernetes/src/k8s.io/kubernetes/_output/local/go
GOPATH=[HOME]/code/kubernetes/src/k8s.io/kubernetes/_output/local/go
+ echo KUBE_ROOT=[HOME]/code/kubernetes/src/k8s.io/kubernetes
KUBE_ROOT=[HOME]/code/kubernetes/src/k8s.io/kubernetes
+ gazelle fix -build_file_name=BUILD,BUILD.bazel -external=vendored -mode=fix -repo_root=[HOME]/code/kubernetes/src/k8s.io/kubernetes
...
```

and the `BUILD` files under `vendor/` are still missing.

What does seem to help is if I `cd` to the real repo root before calling `gazelle`.

**Comment by ixdy** [comment]
note also that it seems that gazelle isn't walking any of the tree when run under `hack/run-in-gopath.sh`; it's not just `vendor/` that's affected.

**Comment by ixdy** [comment]
Easiest way to reproduce:
1. check out kubernetes/kubernetes
2. `rm` some `BUILD` file in the tree (e.g. `pkg/watch/json/BUILD`)
3. run `hack/run-in-gopath.sh hack/update-bazel.sh`
4. note that the `BUILD` file you removed wasn't regenerated
5. run `hack/update-bazel.sh`
6. note that the `BUILD` file was now regenerated

**Comment by jayconrod** [comment]
Copying my comment from slack:

> I think I know what the issue is, but I don't know update-godep.sh well enough to know the fix. Gazelle takes optional positional arguments, a list of directories to update. Other directories in the repo are indexed but not updated. If no arguments are given, it updates ".". So when it's run in the gopath, it will look up to $KUBE_ROOT to find WORKSPACE, then it will only attempt to update directories inside the gopath, which will be nothing because it ignores those symlinks (they point to subdirectories of $KUBE_ROOT).
> So I think gazelle -repo_root=dir dir would work. Kind of clunky though.

**Comment by cblecker** [comment]
@eisig Please try again with a fresh master. Fix was merged in last night.

**Comment by eisig** [comment]
It's ok now!  👍
