### ISSUE TITLE
kubectl edit pod ip doesn't work

### ISSUE THREAD

**Issue by emacsliu** [kubernetes/kubernetes#65405]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug
> /kind feature

**What happened**:
When I use kubectl edit command to change podip field, it say I have edited. But nothing happened. 
**What you expected to happen**:
Either change the podip, or say I should not be changed.
**How to reproduce it (as minimally and precisely as possible)**:
kubectl edit pod xxx, look for podip, and give it a new internal ip address,they :wq exit.

**Anything else we need to know?**:
No
**Environment**:
- Kubernetes version (use `kubectl version`):1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos
- Kernel (e.g. `uname -a`):Linux master1 4.4.98-1.el7.elrepo.x86_64 #1 SMP Wed Nov 15 12:29:46 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by jiaxuanzhou** [comment]
this parameter should be allowed to be modified i think

**Comment by CaoShuFeng** [comment]
> kubectl edit pod ip doesn't work

Looks like pod ip should not modified manually. It's set by kubelet, I think.

**Comment by CaoShuFeng** [comment]
When run `kubectl edit`, modification to `pod.status` are silently ignored.
https://github.com/kubernetes/kubernetes/blob/67e7d4c68ff8bcc3ce357e03ef3ddf2c688e417c/pkg/registry/core/pod/strategy.go#L82
