### ISSUE TITLE
add a resource to see what authz are linked to which subject

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#65406]
Currently there are no easy way to list all the authorization for specific subject. This makes our security audits harder on large clusters. 
This issue is created to discuss the possibility of introducing a `SubjectRulesReview` to ease the work of security teams. For a given subject a `SubjectRulesReview` would be associated and would contains the projection of cluster-wide authorizations .

/assign
/kind feature

cc @tallclair @liggitt

**Comment by yastij** [comment]
also cc @ericchiang

**Comment by WanLinghao** [comment]
@liggitt

**Comment by liggitt** [comment]
A few considerations come to mind:
* not all authorizors support enumerating authorization rules for a subject (see the “incomplete” indicator in the SelfSubjectRulesReview type). That can be acceptable for a best effort, non-authoritative, advisory rule listing (which is what SelfSubjectRulesReview is) but doesn’t seem good for audit purposes. 
* a rules review returns rules for a single scope (either cluster-wide permissions, or permissions within a single namespace). an exhaustive enumeration would require evaluation for each subject for each namespace, which becomes prohibitively expensive

**Comment by yastij** [comment]
/close

Closing this as per our discussions with @liggitt
