### ISSUE TITLE
run hack/update-bazel.sh conflict with rules

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#65409]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

This may related with #64122. If you run hack/update-bazel.sh all imported packages always start with `//vendor` but not `//staging/src`

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
The code that caused the conflict cannot be resolved(#64741). 

**What you expected to happen**:
import path in staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/BUILD is start with `//staging/src`.

/cc @ixdy
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ixdy** [comment]
Right, things have changed a bit after #64122. Whereas previously everything under `staging/src/k8s.io` was referred to using its `vendor/k8s.io/` symlink, now in `BUILD` files, we use the real `//staging/src/k8s.io/...` path for everything under `staging`, while real vendored dependencies under `vendor/` still use `//vendor/...`. 

If you didn't make any human changes to the `BUILD` files (which I doubt you did), you should be able to revert your changes, run `hack/update-bazel.sh`, and have everything back to a working state. Apologies for the merge conflicts.

**Comment by wgliang** [comment]
@ixdy 
Thanks for your reply, I have solved it.
I will close this issue.
