### ISSUE TITLE
Deprecate DenyEscalatingExec

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/kubernetes#65408]
Look, here is the thing, this is only useful IF you are _only_ exposing the kube api to the end user. AND even then if you do not prevent mounting the host into containers via a PodSecurityPolicy then you could just exec in by combining the file descriptors....

Like this window dressing of a feature is kinda un-useful and people are enabling it under circumstances where it is just plain stupid.... there is literally no point to this feature if you do not also have a pod security policy in place preventing people from mounting shit in to literally exec. Or if users have access to the nodes in the first place it makes literally no sense.

**Comment by dims** [comment]
/sig node

cc @derekwaynecarr @liggitt

**Comment by tallclair** [comment]
Agreed. I would much prefer to see this done with a combination of RBAC, namespaces, and PodSecurityPolicy. For example:

- Allow privileged pods in the "privileged" namespace (PodSecurityPolicy), do not allow exec in that namespace (RBAC)
- Forbid privileged pods in the "unprivileged" namespace (PSP), allow exec in that namespace

PSP actually covers enough ground to properly prevent escalating exec (privileged, capabilities, host paths, etc.).

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/72737 to mark as deprecated

**Comment by dims** [comment]
Thanks @liggitt
