### ISSUE TITLE
Scheduler extender broken by JSON decoder update

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/kubernetes#65413]
/kind bug
/sig api-machinery
/sig scheduling
/cc @caesarxuchao 
/cc @MaciekPytel

The scheduler extender configuration element `BindVerb` does not have a JSON tag. The scheduler extender configuration must be in JSON format, IIRC.
https://github.com/kubernetes/kubernetes/blob/d2b954eaf83afefad8ff2d80ea27bf86b056b80b/pkg/scheduler/api/v1/types.go#L150-L153

And no custom marshallers exists for this field. I think this is a bug that should be fixed.

In addition, https://github.com/kubernetes/kubernetes/pull/65157 was merged into release-1.10 and released with 1.10.5. This PR seems (?) to change the decoder to ignore the fields that do not have JSON tags, causing the scheduler extender mechanism to be broken.

**Comment by nikhita** [comment]
I'll create a PR to add the tag.

But this would be a breaking change.

**Comment by nikhita** [comment]
Also: this file does not have any proto tags - is that expected?

**Comment by yguo0905** [comment]
> Also: this file does not have any proto tags - is that expected?

I'm not sure about this :)

**Comment by yguo0905** [comment]
Can you please confirm that the decoder update now requires the JSON tag to be set?

**Comment by nikhita** [comment]
> Can you please confirm that the decoder update now requires the JSON tag to be set?

Well, yes, the decoder update required the JSON tag to be set -- if the API is exposed in the openapi schema.

Checking further, it looks like this API is not exposed at all, so it won't make a difference even if we add the tag here. :thinking: 

If it's not exposed, it also doesn't make sense to add proto tags here.

**Comment by yguo0905** [comment]
> Checking further, it looks like this API is not exposed at all, so it won't make a difference even if we add the tag here.

I thought if we want to add the tag, it would be `bindVerb`, so that the example in https://github.com/kubernetes/examples/blob/master/staging/scheduler-policy-config-with-extender.json#L8 is still valid.

@liggitt, I didn't try but I think `BindVerb` should work. But this inconsistency seems to be a bug: `filterVerb`, `prioritizeVerb` but `BindVerb`. Maybe we can fix this in the 1.12.

The decoder update is a backward compatible change, which I feel should be avoided in patch releases if we could.

**Comment by liggitt** [comment]
>  But this inconsistency seems to be a bug: filterVerb, prioritizeVerb but BindVerb. Maybe we can fix this in the 1.12.

There are many problems with the ExtenderConfig API type. Tracking those in https://github.com/kubernetes/kubernetes/issues/65414

Returning the REST API to a case-sensitive state was very important to maintain interoperability between kubernetes releases (see discussion in https://github.com/kubernetes/kubernetes/pull/65298#issuecomment-399582819)

Opened #65415 to continue decoding this particular config struct in a case-insensitive way until @kubernetes/sig-scheduling-bugs determines how they want to proceed fixing the issues with that type.

**Comment by yguo0905** [comment]
@liggitt, sounds great. Thanks!

@caesarxuchao and @MaciekPytel, the decoder change should probably be one of `Action Required` items in the release note. We probably want to say something since 1.10.5 that has the problem has already been released.

**Comment by caesarxuchao** [comment]
I updated to release notes of #65034 to warn people about the known breaking config.

**Comment by liggitt** [comment]
> I updated to release notes of #65034 to warn people about the known breaking config.

The BindVerb issue will be limited to 1.10.5, and would best be indicated as a known issue in the CHANGELOG-1.10.md file, not in a 1.11 release note. Also, I think 1.11 release notes have already been extracted from PR descriptions and are being edited by sig-docs

**Comment by nikhita** [comment]
Just mentioning the related PRs here for easier tracking:

- https://github.com/kubernetes/kubernetes/pull/65424: PR to master (1.12)
- https://github.com/kubernetes/kubernetes/pull/65416: cherry-pick to 1.11
- https://github.com/kubernetes/kubernetes/pull/65417: cherry-pick to 1.10
- https://github.com/kubernetes/kubernetes/pull/65418: cherry-pick to 1.9
- https://github.com/kubernetes/kubernetes/pull/65419: cherry-pick to 1.8

**Comment by nikhita** [comment]
Btw, thanks for reporting this @yguo0905! :+1: :+1: :+1: 

It would have been really bad if we caught this even later..

**Comment by liggitt** [comment]
1.11 PRs are merged, moving to 1.10 milestone

**Comment by liggitt** [comment]
1.10 PR is merged as well: https://github.com/kubernetes/kubernetes/pull/65417

/close

**Comment by nikhita** [comment]
1.9 cherry-pick is still open: https://github.com/kubernetes/kubernetes/pull/65418 (needs cherry-pick approval)
