### ISSUE TITLE
[Candidate for Conformance] discussion to promote "[sig-api-machinery] Garbage collector should delete jobs and pods created by cronjob" e2e test

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#65428]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
**e2e test:**  [sig-api-machinery] Garbage collector should delete jobs and pods created by cronjob

With respect to the [discussion](https://github.com/cncf/k8s-conformance/issues/221#issuecomment-397375358) to promote e2e tests for conformance, while going through codebase, It is observed that this e2e test case is using **_[cronjob resource](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/garbage_collector.go#L1109) which is under v1beta1_**. So we may not promote it to conformance as it is not meeting the [conformance guidelines](https://github.com/brahmaroutu/community/blob/4bd34702de0f138610e8e27e9484efe9fb770d46/contributors/devel/conformance-guidelines.md#conformance-test-guidelines).

**What you expected to happen**:
1. Should not promote for conforamnce at this point in time
2. Thoughts on migrating cronjob resource from beta to stable release.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Any suggestion or feedback is expected in order to promote this e2e test.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
cc @fedebongio, @AishSundar
/area conformance
@kubernetes/sig-architecture-feature-requests

**Comment by deantejones** [comment]
I love this website thanks you guys for helping me

**Comment by AishSundar** [comment]
@fedebongio, do we know when this feature is likely go to GA?
@WilliamDenniss should we talk about Beta conformance tag with this test? If so can you point me to any documentation and we can  bring this up in next Conformance WG meeting?

**Comment by spiffxp** [comment]
/close
I'm closing this under the auspices that under the effort to improve coverage of tests for conformance, we shouldn't be writing or promoting tests for beta features (cronjob doesn't appear to be going stable anytime soon, ref: https://github.com/kubernetes/features/issues/19)
