### ISSUE TITLE
[Candidate for Conformance] discussion to promote "[sig-api-machinery] Garbage collector should orphan pods created by rc if deleteOptions.OrphanDependents is nil" e2e test

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#65427]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
With respect to the [discussion](https://github.com/cncf/k8s-conformance/issues/221#issuecomment-397375358) to promote e2e tests for conformance, while going through codebase, It is observed that this e2e test case is using deprecated (in 1.7) [deleteOptions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#deleteoptions-v1-meta) (OrphanDependents=nil). So we may not promote it to conformance as it is not meeting the [conformance guidelines](https://github.com/brahmaroutu/community/blob/4bd34702de0f138610e8e27e9484efe9fb770d46/contributors/devel/conformance-guidelines.md#conformance-test-guidelines).

**What you expected to happen**:
1. Do not promote this e2e tests for conformance.
2. Create another e2e test with deleteOptions parameters as **propagationPolicy="Orphan"** to achieve same behaviour.

**Anything else we need to know?**:
Any suggestion or feedback is expected in order to promote this e2e test.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1047+3abba251605909-dirty", GitCommit:"3abba25160590921fec61236ba012a8bbd757d6c", GitTreeState:"dirty", BuildDate:"2018-06-18T07:29:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc  @fedebongio, @AishSundar 
/area conformance
@kubernetes/sig-architecture-feature-requests

**Comment by AishSundar** [comment]
@fedebongio your guidance on this will be helpful. Should we consider rewriting the e2e test and then promote it?

**Comment by AishSundar** [comment]
So @mgdevstack as per your observation here there's already a conformance test for deleteOptions? Ref: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.txt#L3

@caesarxuchao and @fedebongio let us know if the test referenced above tests the functionality fully or you need it updated.

**Comment by mgdevstack** [comment]
Yes @AishSundar, mentioned conformance test is verifying GC behavior with Orphan propagation.

**Comment by spiffxp** [comment]
@mgdevstack based on discussion offline, it sounds like we don't want to bother promoting to conformance because `deleteOptions.OrphanDependents` is deprecated, let's document this next to the test to close this out, so we don't lose track and try promoting this in the future
