### ISSUE TITLE
kubectl working with --dry-run but failing without it

### ISSUE THREAD

**Issue by ctodea** [kubernetes/kubernetes#65435]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Creating a ReplicaSet I've forgot to create a label in the Pod for using it on the selector of the RS to specify which Pods are to be managed by this RS.

rs.yaml **without the label and selector** which are commented:
```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: rs-redis
spec:
  replicas: 2
#  selector:
#    matchLabels:
#      app: redis
  template:
    metadata:
      name: redis
#      labels:
#        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
```
So, running `kubectl apply -f rs.yaml --dry-run`
returns:

> replicaset.extensions "rs-redis" created (dry run)

And running `kubectl apply -f rs.yaml` returns an error indicating what is missing, which is good:

> The ReplicaSet "rs-redis" is invalid: 
> * spec.selector: Required value
> * spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
> 

and obviously, after changing the YAML and uncommenting the fields everything works.

The behaviour is the same using `kubectl create` instead of `kubectl apply`

**What you expected to happen**:
Shouldn't the` kubectl apply --dry-run` fail if the command without `--dry-run` won't work?

**How to reproduce it (as minimally and precisely as possible)**:
Create a ReplicaSet using the YAML above and run:
`kubectl apply -f rs.yaml --dry-run` 
and later:
`kubectl apply -f rs.yaml` (without the dry-run)

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
> 

- Cloud provider or hardware configuration:

**I don't think the bug is related to the installation method.**

I'm using Kubespray to deploy 3 nodes on my laptop with Vagrant. So I've just cloned:
https://github.com/kubernetes-incubator/kubespray
and changed the memory of the VMs from 2GB to ~1.6GB (to prevent my laptop from swapping) in the Vagrantfile. 

> $vm_memory = 1600

The default conf creates 2 master nodes and 1 worker, all 3 nodes run etcd.
After clonning kubespray, and adjusting the memory move to the dir and run`vagrant up`.

- OS (e.g. from /etc/os-release):

OS of the VMs deployed using Vagrant:

`cat /etc/os-release `
> NAME="Ubuntu"
> VERSION="16.04.4 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.4 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

OS of my laptop:

`cat /etc/os-release `
> NAME="Ubuntu"
> VERSION="18.04 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):

Kernel version of the VMs deployed using Vagrant:
> Linux TPL450 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Kernel version of my laptop:

> Linux TPL450 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nikhita** [comment]
/cc @apelisse 
since this talks about apply and dry run

**Comment by apelisse** [comment]
@ctodea This is a well-known issue that we're trying to address right now: https://github.com/kubernetes/community/pull/2301

Thanks!

**Comment by ctodea** [comment]
@apellise So, should I close this issue?
