### ISSUE TITLE
Create aggregated ClusterRole for API Servers to allow getting Namespaces and Admission Webhooks

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#65442]
I'm moving discussion from https://github.com/kubernetes/kubernetes/pull/65206#discussion_r197764862 to this issue.

We think it would be a good idea to provide the aggregated ClusterRole, allowing the aggregated API servers to `get`, `list` and `watch` Namespaces and Admission Webhooks. This role is generic for all API servers, and we're already using this pattern for the auth delegator.

In this case, the API server operator would only have to create the appropriate ClusterRoleBinding, such as [this one (example from `sample-apiserver`)](https://github.com/kubernetes/sample-apiserver/blob/115301f3b9e6c1811750e329a0d852d16bc0b8d6/artifacts/example/auth-delegator.yaml), compared to creating both the ClusterRole and the ClusterRoleBinding.

In #65206, we have added [an example manifest to the `sample-apiserver` repo](https://github.com/xmudrii/kubernetes/blob/33d31e4a558597d0135caec73f600b8fbe5dfe6b/staging/src/k8s.io/sample-apiserver/artifacts/example/rbac.yaml), but as described above and as this is a generic role for all API servers, maybe we can make Kubernetes handle it.

Without that role, the API server fails to start with the permissions errors (see #65206 for details).

I would like to take on this issue if this sounds okay.

/cc @deads2k @sttts @kubernetes/sig-auth-misc
/sig api-machinery
/sig auth
/kind feature

**Comment by sttts** [comment]
+1 we should do that. Otherwise, aggregated API server builders will ship those roles. Not sure we want that from a security point of view.
