### ISSUE TITLE
kubelet cannot read config file with Kind: KubeletConfiguration not valid for api version v1beta1

### ISSUE THREAD

**Issue by Proteles** [kubernetes/kubernetes#65455]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
While following instructions for config file located here - https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

received error
Error loading config file "/etc/kubernetes/kubelet.conf": no kind "KubeletConfiguration" is registered for version "kubelet.config.k8s.io/v1beta1"

kubelet service file

```
# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_NETWORK_ARGS $KUBELET_CERTIFICATE_ARGS
```

kubelet config file from document

```
# cat kubelet.conf 
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
    memory.available:  "200Mi"
```

systemctl daemon-reload
systemctl start kubelet

```
# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Mon 2018-06-25 20:50:17 EDT; 2s ago
     Docs: http://kubernetes.io/docs/
  Process: 12826 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_NETWORK_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_LOG_ARGS (code=exited, status=255)
 Main PID: 12826 (code=exited, status=255)

Jun 25 20:50:17 systemd[1]: Unit kubelet.service entered failed state.
Jun 25 20:50:17 systemd[1]: kubelet.service failed.
```

journalctl -xeu kubelet

```
# journalctl -xeu kubelet
Jun 25 20:50:17 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.
Jun 25 20:50:17 kubelet[12826]: I0625 20:50:17.239349   12826 feature_gate.go:226] feature gates: &{{} map[]}
Jun 25 20:50:17 kubelet[12826]: W0625 20:50:17.247369   12826 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Jun 25 20:50:17 kubelet[12826]: I0625 20:50:17.254185   12826 server.go:376] Version: v1.10.5
Jun 25 20:50:17 kubelet[12826]: I0625 20:50:17.254265   12826 feature_gate.go:226] feature gates: &{{} map[]}
Jun 25 20:50:17 kubelet[12826]: I0625 20:50:17.254442   12826 plugins.go:89] No cloud provider specified.
Jun 25 20:50:17 kubelet[12826]: F0625 20:50:17.254971   12826 server.go:233] failed to run Kubelet: invalid kubeconfig: Error loading config file "/etc/kubernetes/kubelet.conf": no kind "KubeletConfiguration" is registered for version "kubelet.config.k8s.io/v1beta1"
Jun 25 20:50:17 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 25 20:50:17 systemd[1]: Unit kubelet.service entered failed state.
Jun 25 20:50:17 systemd[1]: kubelet.service failed.
```

**What you expected to happen**:
expected kubelet to run

**How to reproduce it (as minimally and precisely as possible)**:
install:
  yum install kubelet kubeadm kubectl

create service:
  systemctl enable kubelet

modify service file:
   /etc/systemd/system/kubelet.service.d/10-kubeadm.conf to point to /etc/kubernetes/kubelet.conf

start service with config file:
  systemctl daemon-reload
  systemctl start kubelet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.5
- Cloud provider or hardware configuration: none
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: yum
- Others:

**Comment by Proteles** [comment]
it appears that --kubeconfig flag is not for configuring kubelet? nor is boot
you need to use --config flag instead 

which begs the question, what exactly are bootstrap-kubeconfig and kubeconfig flags for? they are not created by kubeadm, and any config file format fails.  Documentation should be more explicit.

**Comment by mtaufen** [comment]
The `--kubeconfig` file typically contains the address and credentials for communicating with the API server. 

You can provide a `--bootstrap-kubeconfig` path and a desired `--kubeconfig` path (latter file does not exist yet), and the Kubelet will use the `--bootstrap-kubeconfig` credentials to request a client cert from the API server, then write a new `--kubeconfig` that uses this cert, and use these new credentials for subsequent communication.

**Comment by mtaufen** [comment]
>any config file format fails

IIRC it's the same file format as `kubectl`'s `--kubeconfig`

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
