### ISSUE TITLE
Error: unknown command "upgrade" for "kubeadm"

### ISSUE THREAD

**Issue by adepuravikrishna** [kubernetes/kubernetes#65451]
BUG REPORT:

/kind bug

 
@k8s-sig-onprem-bugs   Kubeadm upgrade plan command is not working in the version v1.7.5. We are planning to upgrade the cluster v1.75 to v1.9.x. Could you please advise me the kubeadm command available in v1.7.5?

**Is this a BUG REPORT **:

[root@machienname]# **kubeadm version**
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@machinename]# **kubeadm upgrade apply v1.9.6**
Error: unknown command "upgrade" for "kubeadm"
Run 'kubeadm --help' for usage.
[root@machinename]# **uname -a**
Linux machinenmae 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@machinename]# **kubectl version**
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[

**Environment**:
- Kubernetes version (use `kubectl version`):v1.7.5
- Cloud provider or hardware configuration: on-premise
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
- Kernel (e.g. `uname -a`):Linux machinename 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 
- Install tools:
- Others:
/sig cli

**Comment by timothysc** [comment]
Upgrades that skip versions is not supported and documented.  
v1.75 to v1.9.x is unsupported -> closing.
