### ISSUE TITLE
ipvs broken because ipset on centos does not support comment extension

### ISSUE THREAD

**Issue by honkiko** [kubernetes/kubernetes#65461]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig network
/area kube-proxy
/area ipvs
/assign @honkiko
I'll send a fixing pull request tomorrow.

**What happened**:
On centos 7.2 with ipset 6.29,  kube-proxy in ipvs mode failed to create ipset sets.
```
Jun 25 20:50:00 VM_3_4_centos kube-proxy[3828]: E0625 20:50:00.312569    3828 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOOP-BACK hash:ip,port,ip inet 1024 65536 0-65535 Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose} map[] 0xc42073e1d0} exist, error: error creating ipset KUBE-LOOP-BACK, error: exit status 2
```

After some dig, it turns out to be problem of ipset on centos/rh. See https://bugzilla.redhat.com/show_bug.cgi?id=1496859

I tried ipset 6.29 on ubuntu, it's OK. But when I tried ipset 6.29 on centos, I got errors:
```
[root@VM_3_4_centos ~]# ipset create foo hash:ip comment
ipset v6.29: Unknown argument: `comment'
Try `ipset help' for more information.
```

**What you expected to happen**:
Since the problematic ipset versions have very large installation base, we could remove ipset commet, or remove ipset commet with problematic ipset version. 

The problematic ipset also says it support comment by --help. The problem could be detected by a test run of "ipset create foo hash:ip comment".

**How to reproduce it (as minimally and precisely as possible)**:
Create some service in kubernetes, run kube-proxy with ipvs mode on Centos 7.x node. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): commit 67e7d4c (actually all commits after 10664ee8c6c)
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- Kernel (e.g. `uname -a`): Linux VM_3_4_centos 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others: ipset v6.29, protocol version: 6

**Comment by stewart-yu** [comment]
could you test it before commit [10664ee](https://github.com/kubernetes/kubernetes/commit/10664ee8c6c76ea22b265d1cdddee71f3941803c), that's ok? @honkiko

**Comment by honkiko** [comment]
@stewart-yu , yes, I did. It's OK. But I think the we don't need to revert the iptables comments.

**Comment by Davidrjx** [comment]
if ipset package not installed, will set module or match-set option in rule  be weird and now seems not.
