### ISSUE TITLE
how to remove "node-role.kubernetes.io/master=<no value>:NoSchedule" taint

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#65473]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

> /kind feature

**What happened**:
I want to schedule onto master node, so i try to remove taint in master node.

I list taint first:
```
[root@dx-app ~]# cat nodes-taints.tmpl 
{{printf "%-50s %-12s\n" "Node" "Taint"}}
{{- range .items}}
    {{- if $taint := (index .spec "taints") }}
        {{- .metadata.name }}{{ "\t" }}
        {{- range $taint }}
            {{- .key }}={{ .value }}:{{ .effect }}{{ "\t" }}
        {{- end }}
        {{- "\n" }}
    {{- end}}
{{- end}}
[root@dx-app ~]# kubectl get nodes -o go-template-file="./nodes-taints.tmpl"
Node                                               Taint       
dx-app.localdomain	node-role.kubernetes.io/master=<no value>:NoSchedule	
```
Then i call restapi:
```
[root@dx-app ~]# kubectl taint nodes $(hostname) node-role.kubernetes.io/master=<no value>:NoSchedule-
-bash: no: No such file or directory
[root@dx-app ~]# kubectl taint nodes $(hostname) "node-role.kubernetes.io/master=<no value>:NoSchedule-"
error: invalid taint spec: node-role.kubernetes.io/master=<no value>:NoSchedule-, a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
See 'kubectl taint -h' for help and examples.
[root@dx-app ~]# kubectl taint nodes dx-app.novalocal node-role.kubernetes.io/master=\<no\ value\>:NoSchedule-
error: invalid taint spec: node-role.kubernetes.io/master=<no value>:NoSchedule-, a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
See 'kubectl taint -h' for help and examples.
[root@dx-app ~]# kubectl taint nodes dx-app.novalocal node-role.kubernetes.io/master=:NoSchedule-
error: invalid taint effect: NoSchedule-, unsupported taint effect
See 'kubectl taint -h' for help and examples.
```

**What you expected to happen**:
What does the `<no value>` mean?

I google  a workaround which can remove all taint:
```
kubectl patch nodes $(hostname) -p '{"spec":{"taints":[]}}'
```

How can i remove only this taint?

**How to reproduce it (as minimally and precisely as possible)**:
use image to install and use default config(only change host ip)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3 commit:dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools: yum
- Others:
/sig api-machinery

**Comment by dkoshkin** [comment]
You don't want to remove the taint and probably shouldn't really schedule anything on the master either. Read the taints and tolerations [docs](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/).

If you really do want to schedule something on the master the deployment would looks something like:
```
apiVersion: extensions/v1beta1
kind: Deployment
...
  spec:
...
    spec:
...
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
          operator: "Exists"
```

**Comment by daixiang0** [comment]
I just want master node as whole cluster entry, and start nginx pod in master node.
Thanks for your help.
By the way, what does the `<no value>` mean?
If someone set a net taint without value and display like it, how can i remove it?

**Comment by daixiang0** [comment]
I find below cmd can work:
```
kubectl taint nodes $(hostname) node-role.kubernetes.io/master:NoSchedule-
```

**Comment by dkoshkin** [comment]
Yes the command you shared will remove the taint since you have `-` at the end. 
Like I mentioned earlier, it is highly advisable not to run any workloads on the master nodes, its fine for testing and playing around with Kubernetes but a bad idea in any real cluster.

The `<no-value>` just means that no value was set for the key, when specifying tolerations you can also leave off the `value` and it will tolerate based on the `key` and `effect`.

**Comment by daixiang0** [comment]
If my real cluster entry ip is 192.168.50.100, and i want deployment bind 80 port as a web service so that  visit 192.168.50.100 can get web service, without schedule onto master node, is there any idea?

**Comment by dkoshkin** [comment]
Yes take a look at an [ingress controller](https://github.com/kubernetes/ingress-nginx/blob/master/README.md), you can add the tolerations on that deployment and a nodeSelector to always schedule onto the master and then bind to ports 443 and 80, or have some load balancer in front of the node(s) where the ingress controller is running.

**Comment by daixiang0** [comment]
Thanks very much.
