### ISSUE TITLE
Make `KUBE_MAX_PD_VOLS` configurable for all environments

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#65471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind bug
/kind feature

**What happened**:

The scheduler offers the option to configure max volumes per Kubelet/node. This may be required for arbitrary reasons. Currently, that code gets only called when one runs on AWS, GCE or Azure:

https://github.com/kubernetes/kubernetes/blob/1f4f0123edc973d06ceb15d517eb4c555b944427/pkg/scheduler/algorithmprovider/defaults/defaults.go#L123-L139
https://github.com/kubernetes/kubernetes/blob/1f4f0123edc973d06ceb15d517eb4c555b944427/pkg/scheduler/algorithm/predicates/predicates.go#L317-L353

https://github.com/kubernetes/kubernetes/blob/1f4f0123edc973d06ceb15d517eb4c555b944427/pkg/scheduler/algorithm/predicates/predicates.go#L356-L368

It would be awesome if it was possible to set that option no matter what provider one runs on.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig scheduling

**Comment by gnufied** [comment]
We recently added support for dynamic volume count in https://github.com/kubernetes/website/pull/8871 for 1.11

This change will make volume count a property of node object.  In 1.12 we are going to add support for CSI and hence the attach limit feature will be available to more providers.

**Comment by alvaroaleman** [comment]
Hey @gnufied thanks for your response.

> We recently added support for dynamic volume count in kubernetes/website#8871 for 1.11

> This change will make volume count a property of node object. In 1.12 we are going to add support for > CSI and hence the attach limit feature will be available to more providers.

As I understand it in your kubernetes/website#887 pull, that is about adding dynamic limits based on node type but just for AWS EBS or GCP Persistent disks.

The issue here is not about being able to add a limit per node (which would be a new feature) but being able to set `KUBE_MAX_PD_VOLS` on the scheduler for _all_ nodes when _not_ running on AWS/GCP/Azure.

The reason for wanting this is that we hit a hard limit of max attachable disks per instance in an Openstack cloud and would like to prevent such situations in the future. 

This hard limit most does not apply to all Openstack clouds, hence it does not make sense (IMHO) to have a default for this in the provider.

**Comment by thequailman** [comment]
Is this issue still being worked on?
