### ISSUE TITLE
Pod will not start because of Unexpected end of JSON input

### ISSUE THREAD

**Issue by no-stupid-questions** [kubernetes/kubernetes#65498]
/kind bug
/sig azure

**What happened**:
I can successfully create and remove pods 30 times (not concurrent), but when trying to deploy a kubernetes pod around that threshold, I receive this error:

Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "windows-jnlp-rzbbp_jx" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

**What you expected to happen**:
to create a pod like normal onto my azure windows vm

**How to reproduce it (as minimally and precisely as possible)**:
deploy acs-engine's kubernetes-hybrid.json file in azure, install jx onto the linux nodes, then use kubernetes plugin to spin up pods on windows nodes. created and remove about 30 builds, the error should pop up

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
my computer is windows 10, using azure with linux pool agents and windows 10 v1803 server vm's with virtualization
- OS (e.g. from /etc/os-release):
windows 10 v1709 for my computer, the nodes with the pods are trying to run on are windows 10 v1803
- Kernel version: 10.0.17134.112
- Install tools: acs-engine, jx,docker for windows, azure cli for powershell, kubernetes cli

**Comment by PatrickLang** [comment]
/sig windows

This is actually a bug in the Azure CNI code, tracked at https://github.com/Azure/azure-container-networking/issues/195

**Comment by tamilmani1989** [comment]
@PatrickLang  The reason for pod creation error is different here. It's not due to unparseable error. The one you referenced will just fix the error message returned by azure CNI should be parseable by containernetworking/cni.

**Comment by feiskyer** [comment]
I think the issue has been fixed in the latest acs-engine. @no-stupid-questions Do you still have the issue?
