### ISSUE TITLE
Determine if resource.NewHelper calls are superseded by dynamic client

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#65494]
Determine if all instances of `resource.NewHelper` can be replaced with calls that use the DynamicClient instead.

Since resource.NewHelper is mostly (entirely?) used for patching, determine if all calls to it can be replaced with `dynamicClient.Resource(resource).Namespace(namespace).Patch(asUnstructured)
`

cc @soltysh

**Comment by dims** [comment]
@juanvallejo @soltysh Do we clear the v1.12 milestone?

**Comment by soltysh** [comment]
@dims yeah, let's move it to the next milestone.

**Comment by dims** [comment]
oops

/milestone v1.13

**Comment by nikopen** [comment]
@juanvallejo @soltysh ping, is this WIP for 1.13? any related PR?

**Comment by soltysh** [comment]
Yes, this is still open and in-progress, but not something that we will actually finish for 1.13, it'll take us some more time.

**Comment by ibrasho** [comment]
Hey!

Gentle reminder that code freeze for 1.14 is this Thursday.

Since this is part of the 1.14 milestone, is it going to be resolved soon? If not, let's clear the milestone.

**Comment by soltysh** [comment]
@ibrasho hey, sorry, this is not targeted at 1.14 but more of a long term goal. Lemme clear the milestone.

/milestone clear
/remove-lifecycle rotten
