### ISSUE TITLE
etcd lease auto-renewal can extend event TTL indefinitely

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#65497]
Per the [etcd ops guide](https://coreos.com/etcd/docs/latest/op-guide/failures.html#majority-failure): "Once a majority of members works, the etcd cluster elects a new leader automatically and returns to a healthy state. The new leader extends timeouts automatically for all leases. This mechanism ensures no lease expires due to server side unavailability."

For events, if leader elections occur more often than the event-ttl (which defaults to 1hr), event leases will be renewed indefinitely and the number of events stored in etcd (and the number of open leases) will grow until either the etcd storage space limit is exceeded or some other limit is hit (e.g. lease count results in excessively expensive revoke operations).

1. Add an option to etcd lease creation to disable auto-renewal, and use this option to disable auto-renewal of event leases created by k8s
2. Add a remediation routine (in kube-apiserver?) to remove old events (feels like an ugly hack)
3. Transition to a different approach of expiring events in k8s (GC?)

We're currently considering (1) as a short term fix for this issue.

@gyuho, @xiang90 Do you have data or intuition about how often leader elections typically occur? Or is this too dependent on the environment to say?

cc @wenjiaswe @wojtek-t @mborsz

**Comment by xiang90** [comment]
> Do you have data or intuition about how often leader elections typically occur? Or is this too dependent on the environment to say?

It should happen less than once per week in a stable environment. Should not happen multiple times a day at least.

> Add an option to etcd lease creation to disable auto-renewal, and use this option to disable auto-renewal of event leases created by k8s

We do not persist the remaining lease duration for performance consideration. We actually can persist the lease remaining duration lazily for long term leases. For example, we can persist an one hour lease remaining duration every 10 minutes. The overhead should be minimal. 

We probably should move this discussion to etcd repo.

**Comment by gyuho** [comment]
c.f. https://github.com/coreos/etcd/pull/9526.

**Comment by jpbetz** [comment]
Created https://github.com/coreos/etcd/issues/9888 to track this on the etcd repo.

**Comment by jpbetz** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/64539

**Comment by mborsz** [comment]
@jpbetz Could you elaborate how #64539 fixes this issue?

**Comment by bgrant0607** [comment]
cc @janetkuo @kow3ns since we had discussed a controller-based TTL GC

**Comment by jpbetz** [comment]
@mborsz The root cause fix is https://github.com/coreos/etcd/pull/9924, but it seems likely that #64539 helps to mitigate this issue for k8s for cases where event load high since without #64539 the lease revoke operations become expensive in etcd and can cause leader election churn.

**Comment by wojtek-t** [comment]
@jpbetz - can we close it now?

**Comment by jpbetz** [comment]
Yes, this is resolved.
