### ISSUE TITLE
Empty namespace

### ISSUE THREAD

**Issue by jeusdi** [kubernetes/kubernetes#65525]
I need to get access to current namespace. I've look up `KUBERNETES_NAMESPACE` and `OPENSHIFT_NAMESPACE` but they are unset.

    $ oc rsh wsec-15-t6xj4
     $ env | grep KUBERNETES
    KUBERNETES_SERVICE_PORT=443
    KUBERNETES_PORT=tcp://172.30.0.1:443
    KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1
    KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1
    KUBERNETES_PORT_53_TCP_PORT=53
    KUBERNETES_PORT_53_TCP_PROTO=tcp
    KUBERNETES_PORT_53_UDP_PORT=53
    KUBERNETES_SERVICE_PORT_DNS=53
    KUBERNETES_PORT_53_UDP_PROTO=udp
    KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1
    KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53
    KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53
    KUBERNETES_PORT_443_TCP_PORT=443
    KUBERNETES_PORT_443_TCP_PROTO=tcp
    KUBERNETES_SERVICE_PORT_DNS_TCP=53
    KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443
    KUBERNETES_SERVICE_PORT_HTTPS=443
    KUBERNETES_SERVICE_HOST=172.30.0.1

Also the content of `/var/run/secrets/kubernetes.io/namespace` is empty.

Any ideas?

**Comment by nikhita** [comment]
@jeusdi this looks like an issue for openshift?

**Comment by liggitt** [comment]
those environment variables are not automatically set

the path for the auto-injected namespace is `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

/close
