### ISSUE TITLE
E2E tests: Should not run if ginko testContext is unavailable.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#6552]
@zmerlynn  @quinton-hoole @wojtek-t 

Looks like when you run tests via ginko, from source, the parameters are not injected... 

```
 go run ./cmd/e2e/e2e.go --provider=local --namespace=default --host=http://127.0.0.1:8081 -t "Networking" --auth_config=/opt/kube-creds  
```

Maybe its only valid to run using some kind of `ginko ...` invocation, or else via binarys? 

Given that this variability exists, it would be good to validate that the parameters are indeed injected before running tests.

To be honest, im not even sure how `textContext` is populated...

**Comment by quinton-hoole** [comment]
Agreed, this stuff seems busted.  We have a plan to get rid of the custom wrapper around our e2e tests and replace it with the standard Ginkgo runner real soon now. Lets handle this one in the context of that.  I'll find (or open) an issue for the former, and touch base with zmerlynn@ and ixdy@ today to get this moving.  Are you interested in contributing jayunit100@

**Comment by ixdy** [comment]
Right now I think the preferred way to run e2e tests is using `go run hack/e2e.go --test`, which itself calls `hack/ginkgo-e2e.sh`, which actually does the work of setting all of the necessary arguments to pass to `cmd/e2e/e2e.go`.

We should probably get rid of these intermediate steps (which is the goal of #5670), though each of these scripts and wrappers does provide some necessary functionality currently.

**Comment by quinton-hoole** [comment]
Reassigning to ixdy@ as part of #5670

**Comment by mbforbes** [comment]
I'm running into this as well. I'm running with `go run hack/e2e.go --test` (and some other stuff) and my tests are panicking when they try to access `testContext.Provider`. I thought I was crazy because I couldn't see how it was populated. (Well, my tests are still panicking, so maybe I am crazy.)

**Comment by mbforbes** [comment]
Update: protip: only try to touch `testContext` while within an `It(...)` block; it will even panic other tests you haven't touched if you do this. That was a fun afternoon.

**Comment by ixdy** [comment]
You can also use `testContext` from a `BeforeEach`. It seems that using it inside a `Describe` is not safe, however, as these blocks are evaluated before flags are evaluated. In my work to get rid of cmd/e2e I've found several places that use `testContext.RepoRoot` before it's initialized as well.

**Comment by jayunit100** [comment]
Arg ! got burnt by this again :) ^.  hope we can come up with a smarter way to avoid running into this issue.

**Comment by fejta** [comment]
Please use go run hack/e2e.go as per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md

**Comment by jayunit100** [comment]
Yeah It's closed. Also the binary itself works fine.
