### ISSUE TITLE
Failed to create Sandbox CNI when creating AWS EKS Cluster via Terraform

### ISSUE THREAD

**Issue by akhilyendluri** [kubernetes/kubernetes#65544]
Hi,
@kubernetes/sig-contributor-experience-test-failures
I am facing a similar issue. 

I created a cluster in aws eks using terraform script given in https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html#guide-overview

After this I was deploying the guestbook application as given in  https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html 

Once my pods got created I noticed that they where not ready. I saw this in my
` kubectl describe pods`

``` 
Name:           redis-master-8rqtb
Namespace:      default
Node:           ip-10-0-0-232.ec2.internal/10.0.0.232
Start Time:     Tue, 26 Jun 2018 13:18:22 -0400
Labels:         app=redis
                role=master
Annotations:    <none>
Status:         Pending
IP:
Controlled By:  ReplicationController/redis-master
Containers:
  redis-master:
    Container ID:
    Image:          redis:2.8.23
    Image ID:
    Port:           6379/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4xr62 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-4xr62:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4xr62
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s

 Events:
 Type                       Reason                  Age                  From                                        Message

 Warning  FailedCreatePodSandBox     32m       kubelet, ip-10-0-0-232.ec2.internal   Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "redis-master-8rqtb_default" network: rpc error: code = Unavailable desc = grpc: the connection is unavailable
 Normal   SandboxChanged          2m (x2994 over 1h)   kubelet, ip-10-0-0-232.ec2.internal  Pod sandbox changed, it will be killed and re-created.
```

I tried adding flannel using `kubectl apply -f kube-flannel.yml` 

Even then I was not getting the issue.

I tried to use `journalctl -u kubelet` to get the kubelet logs. But the logs where empty.

`akhil@ubuntu:~$ kubectl version --short
`

```
Client Version: v1.10.3
Server Version: v1.10.3
```

`akhil@ubuntu:~$ uname -a`

```
Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

`akhil@ubuntu:~$ kubectl get pods --all-namespaces`

```
NAMESPACE     NAME                        READY     STATUS              RESTARTS   AGE
default       redis-master-8rqtb          0/1       ContainerCreating   0          1h
kube-system   aws-node-28gkv              0/1       CrashLoopBackOff    18         1h
kube-system   aws-node-bfvf2              0/1       CrashLoopBackOff    18         1h
kube-system   aws-node-kn759              0/1       CrashLoopBackOff    18         1h
kube-system   kube-dns-64b69465b4-b8p84   0/3       ContainerCreating   0          2h
kube-system   kube-proxy-5686g            1/1       Running             0          1h
kube-system   kube-proxy-hwd29            1/1       Running             0          1h
kube-system   kube-proxy-m5854            1/1       Running             0          1h
```

When I tried getting the logs

`akhil@ubuntu:~$ journalctl -u kubelet`

I got

```
-- No entries --
```

Also running `kubectl logs aws-node-bfvf2 -n kube-system`
```
=====Starting installing AWS-CNI =========
=====Starting amazon-k8s-agent ===========
ERROR: logging before flag.Parse: W0626 19:18:29.099664      14 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

```

**Comment by akhilyendluri** [comment]
Fixed it. The issue was in the terraform script. Please close this.

**Comment by sanjitsaluja** [comment]
@akhilyendluri Can you please explain how you resolved this issue with a terraform script fix. I'm working on a terraform project and seeing a similar issue.

**Comment by akhilyendluri** [comment]
I had a issue in the terraform worker nodes. It was related to the name mappings between the policies and the worker node itself.

**Comment by lambertpan** [comment]
@akhilyendluri is it possible for you to share the fix?

**Comment by lambertpan** [comment]
It is working for me now. I used t2.small so I updated the MAX_POD to '8'. It seems 'calico' is a choice for not limiting the pod counts [refer](https://aws.amazon.com/blogs/opensource/networking-foundation-eks-aws-cni-calico/) .

**Comment by utsav2307** [comment]
Was this issue resolved for anyone else without using calico? I am facing the exactly same error after launching the cluster via terraform

**Comment by akhilyendluri** [comment]
The issue for me was due to incorrect name mappings in aws_security_group_rule.

resource "aws_security_group_rule" "eks-node-ingress-self" {
  description              = "${var.aws_security_group_rule_ingress_description}"
  from_port                = 0
  protocol                 = "-1"
  security_group_id        = "${aws_security_group.eks-node.id}"
  source_security_group_id = "${aws_security_group.eks-node.id}"
  to_port                  = 65535
  type                     = "ingress"
}

I had incorrect name mappings for the security_group_id and source_security_group_id. 

I am not sure if this is the only cause for this error to occur.

**Comment by delgod** [comment]
`t3.xxxxx` doesn't work - https://github.com/awslabs/amazon-eks-ami/issues/27.
but it logs looks very similar.

**Comment by apetal1** [comment]
Just a quick heads up on the way we worked around a similar issue (using AWS EKS).

Seems related to **ENI and number of IPs** allowed for each instance type. 

Apparently we were using **t2.micro** instances for our tests that allowed only 4 IPs per worker node (check **AWS doc** [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html)).
Issue fixed by switching to **t2.medium** instances for our EKS workers which allows for 6 IPv4 Addresses per Network interface.

Not sure if related to all cases above, but hope it will help some avoid spending hours troubleshooting AWK EKS installations

**Comment by rohansingh** [comment]
I had the same issue, and just like @akhilyendluri, the cause turned out to be security groups.

Specifically, I messed up [the group allowing ingress from nodes to the master](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html#worker-node-access-to-eks-master-cluster). I had the `security_group_id` and `source_security_group_id` flipped.

Dumb mistake on my part, but make sure to double- and triple-check your security groups.
