### ISSUE TITLE
When an object is created on an update request, the admission controllers see it as an update

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/kubernetes#65553]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig api-machinery

**What happened**:

The [static admission attributes](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go#L97) that we use to make a create validation function is given admission.Update as its operation field. In the create validation we then use the provided operation (admission.Update) [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L175-L178), when we call the admission controllers, even though a new object is being created.

A similar thing is happening with the mutating admission.

This means that when an objects is created on update, the admission controllers will see this as an update request. Meaning there could be an objects in storage which never passed create admission validation and were never modified by create admission mutation. I think this is a bug.

**What you expected to happen**:
Admission controllers would handle a create-on-update exactly the same as a normal create

**Comment by jennybuckley** [comment]
I think the solution to this would be to separate the static admission attributes into one for create and one for validate.

Also, the function which performs the mutating admission needs to determine whether or not it is an actual update or if the old object doesn't exist (probably by checking uid) and then call the mutating admission correctly based on which operation is being performed.

**Comment by CaoShuFeng** [comment]
> when an objects is created on update,

How to reproduce this bug?
