### ISSUE TITLE
PVC Protection doesn't wait until Pod volumes have been unmounted

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#65552]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
PVC protection controller only waits for the Pod to be in terminated phase before proceeding.  This means volumes could still be in the process of unmounting but not finished unmounting.  In the case of PVs like NFS, if the NFS share is deleted before a client Pod finishes unmounting it, then the Pod deletion will hang forever along with a stale mount.

**What you expected to happen**:
PVC finalizer should not be removed until Pods have fully unmounted the volumes (Pod object is deleted).

**Comment by jsafrane** [comment]
PVC protection does not wait until the PV is detached, which happens after the pod is deleted. So yes, waiting for pod deletion would help, but it's only partial fix.

**Comment by msau42** [comment]
Are there any attachable plugins where delete volume will succeed if it's still attached?

**Comment by gnufied** [comment]
Not that I am aware of. I think waiting for pod to be deleted makes sense.

**Comment by jsafrane** [comment]
No, only to PV

**Comment by msau42** [comment]
I think it's still worth fixing this to wait for unmount.  Non-attachable plugins like NFS will benefit from this extra protection.

Attachable plugins like PD and EBS have deletion protection built in.  They won't delete if the volume is still attached.  And I think a solution for waiting for detach will require a new finalizer with possible coordination with the attach/detach controller, so it could be done independently of this.

**Comment by msau42** [comment]
@verult found an issue in the flex volume test where waiting for detach before deleting the PVC could help.

**Comment by NickrenREN** [comment]
What if the node(kubelet) is down, and pods in it will never be deleted, which means Pod volumes will never be unmounted. 
I think PVC finalizer should be removed too in this condition.

**Comment by msau42** [comment]
Hmm is there a way we can detect this condition?

**Comment by NickrenREN** [comment]
We do this check for node lost in pods quota evaluating too.  https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/pods.go#L402
