### ISSUE TITLE
kubectl 1.11.0 defaults --use-openapi-print-columns to false

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#65578]
/kind bug
/sig cli

**What happened**:
kubectl 1.11.0 defaults `--use-openapi-print-columns` to `false` which is very impractical when working with aggregated API servers. It was defaulted to `true` with prior versions (<= 1.10.5):

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl get -h
[..]
      --use-openapi-print-columns=true: If true, use x-kubernetes-print-column metadata (if present) from the OpenAPI
schema for displaying a resource
[..]
```

and

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl get -h
[..]
      --use-openapi-print-columns=false: If true, use x-kubernetes-print-column metadata (if present) from the OpenAPI
schema for displaying a resource.
[..]
```

**What you expected to happen**:
The flag defaults to `true` so that you do not need to specify it for each and every `kubectl get` request to resources managed by an aggregated API server.

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
```
- Kernel (e.g. `uname -a`): MacOS
- Install tools: Brew

**Comment by juanvallejo** [comment]
The decision to make this flag opt-in was made in https://github.com/kubernetes/kubernetes/pull/62584.
We enabled server-side printing in kubectl 1.11 which handles CRDs and extension API servers, provided that your server knows to return the correct response to the client.

What is your server version?

**Comment by liggitt** [comment]
server-side printing is supported in 1.10 and up and is the preferred approach for kubectl, since it avoids downloading/parsing/interpreting very large schemas client-side on every get request (https://github.com/kubernetes/kubectl/issues/306), avoids extracting expensive data extraction from API objects client-side, and allows API servers (including extension API servers) to return printable columns that cannot be derived from literal object values.

I agree that https://github.com/kubernetes/kubernetes/issues/65579 is a bug that should be fixed

/close
