### ISSUE TITLE
Figure out the most reliable way to identify a node

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#6557]
- Hostname, but dns can flake
- ip, not very user friendly, _might_ change on cloud providers when a vm restarts (internal ip can't though?)
- Machine id was brought up on https://github.com/GoogleCloudPlatform/kubernetes/issues/6499, though we still need something over the network.

We currently identify nodes by hostname and they're used pretty much everywhere (kubectl, pod.host, curl healthz, static podnames). One option is to split the concept of a node id from a kubelet name, the latter being a globally unique kubernetes name that doesn't even have to resolve, another is to just give up when dns fails (though machine generated dns names aren't very user friendly either).

@thockin

**Comment by bgrant0607** [comment]
Internally we resolve DNS, store the IP address, and require the node to be removed and re-added to the cluster if the IP address or hostname changes. 

For systems using DHCP, it would make sense to lookup the MAC address via DHCP.

If we were to use machine ID, that would imply a way to use it to look up the IP address, such as via a cloudprovider or database, or even via a local file periodically pushed to the node controller.

We'll likely need to make node discovery pluggable, along with network plugins.

**Comment by thockin** [comment]
This is over a year old.  Close or is there still something we hope to get done here?

**Comment by bprashanth** [comment]
I don't know, @kubernetes/goog-node what happens today if DNS is down? will we still be able to create a node object and schedule pods onto it, or will we keep trying to figure out hostname and bring the cluster down? do we care?
