### ISSUE TITLE
PV still contains ClaimRef to a PVC even after it's deleted as part of the namespace

### ISSUE THREAD

**Issue by enchantner** [kubernetes/kubernetes#65581]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I have several Local PersistentVolumes with Retain policy which I want to claim on demand from different namespaces. PVs are not bound to any namespace, but PVCs always are. So, when I delete a namespace together with PVCs in it, there is still a ClaimRef inside a PV pointing to a deleted resource in a deleted namespace, which seems totally wrong.

**What you expected to happen**:
ClaimRef in PV should be deleted together with the Claim that was bound with this PV. Actually, if I delete it manually from the PV resource using _kubectl edit_ - PV becomes "Available" again and I can re-claim it without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PV, create a namespaced PVC, claim the namespace from a Pod in that namespace, delete that namespace together with everything in it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by enchantner** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
A reclaim policy of retain means that the system should not automatically release the PV and make it available.  It indicates that there may be user action required to copy or purge the data from the disk.  So it is up to the user to clear the ClaimRef from the PV when they are ready to make the disk available again.

If you want the system to automatically clean and make the local disks availabile again, you can use the local volume static provisioner with Delete reclaim policy.

**Comment by enchantner** [comment]
@msau42 I think I understand how retain works, but I don't want to delete PV itself together with the claim. 

The idea is, I create all those PVs together with creating partitions by an external tool, and they have NodeAffinity (and local path) related to an exact node. So, to create PV again, i'll need to specify an exact node each time I create a Deployment. This is really ugly.

Also, I know there is no important data left on those partitions when I delete claims. I thought Recycle policy will do what I want (clean partitions and make them "Available" again), but it doesn't work. Isn't there a way to actually do it automatically without any need to manually delete ClaimRef every time?

**Comment by msau42** [comment]
If your external tool can mount all these PVs all under one directory, then you can run the local static provisioner which runs as a DaemonSet and automatically creates the PVs with the correct path and NodeAffinity.  And when the PVC is deleted, it will clean up the data on it, delete the PV, and then recreate the PV again with the correct information.  This is how you can get recycling behavior with local PVs.

**Comment by enchantner** [comment]
This looks like what I want, thanks! Is there any source, like article, where I can read more about this? An example, maybe?

**Comment by msau42** [comment]
Check out the user guide here: https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume

**Comment by zhangxiaoyu-zidif** [comment]
> A reclaim policy of retain means that the system should not automatically release the PV and make it available. It indicates that there may be user action required to copy or purge the data from the disk. So it is up to the user to clear the ClaimRef from the PV when they are ready to make the disk available again.
> 
> If you want the system to automatically clean and make the local disks availabile again, you can use the local volume static provisioner with Delete reclaim policy.

could we add one more reclaim policy, e.g.: reuse. This policy could set PV's phase to available and clean claimRef to nil after deleting the bounded PVC.  
As this case:
When we use statefulset and PVC template, we may delete/ scale down statefulset and delete unMounted PVC. but the PV may be reused later, so we want to remain it and clear its claimRef.

**Comment by ginigangadharan** [comment]
Facing same, any update ?

oc version
oc v3.6.173.0.129
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://lbint-example.com:443
openshift v3.6.173.0.129
kubernetes v1.6.1+5115d708d7

**Comment by Iridescens** [comment]
I second @zhangxiaoyu-zidif 's proposal. I also need this as we often need to recreate whole releases with Helm with different options without deleting data.

**Comment by jsafrane** [comment]
> could we add one more reclaim policy, e.g.: reuse. This policy could set PV's phase to available and clean claimRef to nil after deleting the bounded PVC.

No, the released PV may contain sensitive data (e.g. credit card numbers) and we don't want a random PVC to bind to such PV. Also, the semantics is that PVs are bound empty (unless admin manually creates a pre-populated PV). We tried to wipe volumes with policy `Recycle`, but it was slow, clumsy and not really safe. Local storage provisioner fixed most of the issues by using custom cleaners.

**Comment by jingxu97** [comment]
The "reuse" scenario  mentioned by @zhangxiaoyu-zidif seems quite useful in some use cases. Thinking the way of PVC/PV is designed, PV is non-namespaced and could be bound to a PVC if the it is in "available" state (claimRef is nil). So I understand adding this "reuse" policy is considered dangerous if storage has data on it. But it seems also a limitation of this PVC/PV by design to not able to support this use case. If we could add a fields to limit what namespaces are allowed to access this PV (e.g, allowedAccessNamespaces"), will it help to support this "resue" case?

**Comment by Forbzy** [comment]
I also require the functionality mentioned by @zhangxiaoyu-zidif . Its been over a year have we found a work around?
