### ISSUE TITLE
code-generator: generate register.go

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#65612]
There have been several questions asking if `register.go` is generated in the #sig-api-machinery channel on slack. I think it would be nice if we generate the `register.go` file as well.

We probably need to add tags for identifying the `runtime.Object` types to be registered in the scheme.

And if someone wants to modify the register.go file, they can modify it manually later on.

/kind feature
/sig api-machinery
/cc @sttts

**Comment by deads2k** [comment]
Is anyone working on this already?

@p0lyn0mial this could be a way to ease into the generator space.  Generators like this can be really helpful when trying to create typed resources.

**Comment by deads2k** [comment]
Here is a good example of the register.go that includes a non-package matching group name: https://github.com/kubernetes/api/blob/master/rbac/v1/register.go

**Comment by sttts** [comment]
/cc @pwittrock 

For inspiration also take a look at https://github.com/kubernetes-sigs/kubebuilder/blob/master/samples/full/controller/src/samplecontroller/pkg/apis/samplecontroller/v1alpha1/zz_generated.kubebuilder.go.

**Comment by nikhita** [comment]
@p0lyn0mial Isn't this done? Can this be closed?
