### ISSUE TITLE
Add Pod IP target support to AWS NLB services

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#65613]
/kind feature
/sig aws

I want to be able to use an AWS NLB service and target Pod IP's as a backend instead of nodes.

The [AWS CNI provider](https://github.com/aws/amazon-vpc-cni-k8s) uses ENI's in the same network as Nodes, and [NLB's support IP's as a target type](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html?shortFooter=true#target-type). The [`cloudprovider.LoadBalancer`](https://github.com/kubernetes/kubernetes/blob/3988331/pkg/cloudprovider/cloud.go#L91-L118) interface only calls [`UpdateLoadBalancer()`](https://github.com/kubernetes/kubernetes/blob/3988331/pkg/cloudprovider/cloud.go#L104-L108) on node change, so this may require an out-of tree controller that can watch for changes to the Endpoints for a particular service.

I'm thinking we could use the existing annotation key `service.beta.kubernetes.io/aws-load-balancer-type` with a new value, maybe something like `nlb-eip-endpoints`. (Totally open to a better name)

**Environment**:
- Cloud provider: AWS
- Others: Would only work with [aws/amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s) or any CNI provider that uses ENIs or non-overlay pod IP's

**Comment by jhorwit2** [comment]
@micahhausler Sadly, this change would require a lot more changes to support. I'm going to add sig/network instead since this would be a change to the service controller / cloud provider interface. The load balancer logic actually has no idea about the pods themselves and only receives nodes & the service object. 

/sig network
/remove-sig aws

**Comment by jhorwit2** [comment]
The reason i removed sig aws is this feature could/does apply to multiple clouds. AFAIK most, if not all major clouds, support some number of custom routes which enable pod ip routing on any host in the cloud network. This feature would apply to all those as well.

**Comment by PaulFurtado** [comment]
/remove-lifecycle rotten

Has there been any additional discussion on this in other issues/proposals? We're also resorting to implementing this out of tree in our load balancer management code, but we'd really love to see this built into Kubernetes.

CC: @ssalinas

**Comment by thockin** [comment]
This has to be implemented in a cloud-specific way.  You can no-op the standard controller and write your own, as long as you can handle the various features like port remapping and so forth.

**Comment by sppwf** [comment]
Hi Guys,

Is here progress to add this feature?

Thanks
Sergiu Plotnicu

**Comment by kishorj** [comment]
With kubernetes 1.20 (also backported to EKS 1.18) and the new [AWS Load Balancer controller] (https://github.com/kubernetes-sigs/aws-load-balancer-controller), it IP targets can configured for NLB.
