### ISSUE TITLE
Workload controllers should support templating of custom resources

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#65622]
Today workload controllers usually contain templates for pods.

The [application survey showed](https://docs.google.com/presentation/d/1utT0K-u1nl2apXRo29GaBvRV1x7mFLeQSgpw8mI_nGM/edit#slide=id.g3882d9116d_2_146) on slide 9 that multiple parties are interested to allow the controllers to support custom resource templating as well.

/kind feature

In our use case - KubeVirt - this would allow us to stamp out VMs.
Obviously these VMs would be treated by the workload controller like pods - which would be fine.

**Comment by fabiand** [comment]
@kubernetes/sig-apps

**Comment by fabiand** [comment]
@mattfarina maybe you are aware if there is already a similar issue or if it's tracked elsewhere?

**Comment by liggitt** [comment]
It's unclear what this is asking for. Are you suggesting that an existing kube controller should start creating a new type of custom resource based on another custom resource? I would expect each pair of owner/child resources to be managed by its own controller, both for least privilege reasons,  and because each pairing is likely to have domain specific edge cases that are cleaner to deal with in isolation

**Comment by fabiand** [comment]
> It's unclear what this is asking for. Are you suggesting that an existing kube controller should start creating a new type of custom resource based on another custom resource? 

Yes.

> I would expect each pair of owner/child resources to be managed by its own controller, both for least privilege reasons, and because each pairing is likely to have domain specific edge cases that are cleaner to deal with in isolation

I see your point and I agree. If you want to correct treatment (semantically for a given resource) then you will need a custom controller. However, we could turn this around and say: If you are fine getting your resource being treated like a pod - including in the edge cases. Then it should be fine to reuse an existing controller.

**Comment by liggitt** [comment]
> However, we could turn this around and say: If you are fine getting your resource being treated like a pod - including in the edge cases. Then it should be fine to reuse an existing controller.

We should not expand the scope of existing controllers to do that. The more unknown dependents a controller has, the less ability it has to make changes in the future. A controller that can reason about how changes would affect a `replicaset<->pod` relationship would have no idea what that would mean for a `customcontrollertype <-> customleaftype` relationship.

cc @kubernetes/sig-apps-feature-requests

**Comment by fabiand** [comment]
I understand this approach. However, I still wanted to raise it, as it seems that this appeared more often in the survey.

**Comment by liggitt** [comment]
> One of the original design goals was to make it easy to write custom workload controllers.

I am very much in favor of tools to make it simple to write best-practice controllers, over extending existing controllers' responsibilities

**Comment by fabiand** [comment]
Hm. I understand.

**Comment by kow3ns** [comment]
The work with extension mechanisms and tools like kubebuilder are their to provide users with the ability to extend the API server and add controller for custom resources. I second @liggitt's notion above.
/close
