### ISSUE TITLE
k8s service ClusterIP:Port can not be accessed when the pod is in the same node   

### ISSUE THREAD

**Issue by Hugh-ifly** [kubernetes/kubernetes#65625]
@kubernetes/sig-cluster-ops-bugs
@kubernetes/sig-contributor-experience-bugs

**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I deployed a service nginx, but if I try to request this service via ClusterIP:Port in the node which is the same one that the service pod resides in, the request can not access service. Howerver, if I change to another node that the service pod does not reside in, the request is served ok.

**What you expected to happen**:
When request the service via ClusterIP:Port in the node which is the same one that the service pod resides in, the request can be served correctly.

**How to reproduce it (as minimally and precisely as possible)**:
the service nginx.yaml
```nginx.yaml
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
```
kubectrl get nodes:
```
NAME             STATUS    AGE       VERSION
10.1.86.22       Ready     56d       v1.10.0
192.168.86.171   Ready     56d       v1.10.0
```
kubectl get svc:
```
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kubernetes   172.22.0.1       <none>        443/TCP   1d
nginx        172.22.179.156   <none>        80/TCP    18s
```
kubectl get po -o wide:
```
NAME          READY     STATUS    RESTARTS   AGE       IP            NODE
nginx-bhwtm   1/1       Running   0          7s        172.22.14.2   192.168.86.171
```
In node 10.1.86.22: (which is not the one the pod nginx-bhwtm resides in, the request will be served correctly)
`curl 172.22.179.156:80`
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
However, in node 192.168.86.171: (which is right the one the pod nginx-bhwtm resides in, the request won't be served.)
`curl -sv 172.22.179.156:80`
```
* Rebuilt URL to: 172.22.179.156:80/
* Hostname was NOT found in DNS cache
*   Trying 172.22.179.156...
```
and hanged util timed out.

**Anything else we need to know?**:
If I set nginx replicas to 2, then in any node, `curl $ClusterIP:$port` will fail with 50% probabilty because of the load balance (assume round-robin policy and each pod resides in each node). Similarly, If I set replicas to N, and in the node there is M (M<=N) pods reside, `curl  $ClusterIP:$port` will fail with M/N probabilty.
Additional info:
`curl $POD_IP:$port` in every node will all get the correct response.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:29:21Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare metal, and using flannel vxlan
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="14.04, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Kernel (e.g. `uname -a`):
`Linux ubuntu 3.13.0-145-generic #194-Ubuntu SMP Thu Apr 5 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:
`iptables v1.4.21`

**Comment by jhorwit2** [comment]
@Hugh-ifly  You should open this issue up under flannel's project as it's related to your networking configuration/setup. You'll get better support / way faster support by doing so. 

/close
