### ISSUE TITLE
Kubernetes large and scale tests are sometimes failing to start

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#65626]
This is the result of migrating some tests from us-east1-a to us-east1-b.

Now we have some tests running in one zone, some in the other, but all clusters are still named: "gce-scale-cluster".

So when cluster fails to be deleted in previous run, the next one (if running in a different zones), fails to delete that, because:
- it does list nodes (beause they are in different zone, it doesn't seem them)
- but e.g. it fails to delete instance-template, because it's global, but still referenced by those nodes

Given that our goal was to delete everything before starting a next run, they had to same the same name, but also run in the same zone. That is no longer true, so we need to figure out how to avoid those problems.

@kubernetes/sig-scalability-bugs 

/assign @shyamjvs

**Comment by shyamjvs** [comment]
I have an idea for short-term fixing this problem - let's name 2k-node job clusters and 5k-node job clusters differently for now.
The long-term fix would be to move all the jobs to us-east1-b (then we can revert the short-term fix). I'll send a PR.
