### ISSUE TITLE
I don't have admin.conf,. when I trust to create this file and add a model to admin.conf ,but error again.

### ISSUE THREAD

**Issue by lincoohe** [kubernetes/kubernetes#65623]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
@lincoohe I'm closing this as the issue template is not filled out thus we can't help diagnose any problems. Please recreate the issue with the template filled out if you still need help and think there is a bug in core kubernetes. If this is a support question please use stackoverflow. 

/close
