### ISSUE TITLE
[GKE] Pound symbol in master auth password causes kube-apiserver component to become unhealthy

### ISSUE THREAD

**Issue by CommanderJax** [kubernetes/kubernetes#65633]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

/sig gcp

**What happened**:

If you include a pound symbol (£) into the master auth password during cluster creation, the cluster will never be completely provisioned and will remain unhealthy with the following error being displayed after ~10 minutes:

> All cluster resources were brought up, but the cluster API is reporting that component "kube-apiserver" from endpoint "gke-003c022fd35314af3c85-df99" is unhealthy.

**What you expected to happen**:

An error should be returned if password contains invalid or unexpected characters or it should just work.

**How to reproduce it (as minimally and precisely as possible)**:

Set the master auth password to something that contains a pound symbol, e.g. : ASJPRJffusdj9£H
or just execute the following:

> gcloud container clusters create example-cluster --zone europe-west1-b  --username=admin --password=ASJPRJffusdj9£H

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`):
Tested on 1.9.6-gke.1 and 1.10.4-gke.2
- Cloud provider or hardware configuration:
GKE
- OS (e.g. from /etc/os-release):
GKE default
- Kernel (e.g. `uname -a`):
GKE default
- Install tools:
terraform & gcloud
- Others:
---

**Comment by perriea** [comment]
The same problem with Terraform ...
