### ISSUE TITLE
Problem with kubectl apply `-o jsonpath` or `-o go-template` flags

### ISSUE THREAD

**Issue by brecode** [kubernetes/kubernetes#65647]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind** ***bug***

**What happened**: 
I have a test suite that uses the output of `kubectl apply` with `-o jsonpath` flag set. It has been working fine in 1.10.5 and below but not in 1.11. 

Issuing the following command, results in the following error: 
```
kubectl apply -f /tmp/pod.yaml -o=jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'
error: unable to match a printer suitable for the output format "jsonpath={.kind }{.metadata.namespace} {.metadata.name}", allowed formats are: json,name,yaml
```
I get similar error if I use go-templates

**What you expected to happen**:
In previous version I would get this: 
```
kubectl apply -f /tmp/pod.yaml -o=jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'
Pod default apiserver-f6ayla
```

**How to reproduce it (as minimally and precisely as possible)**:
Problem is not found in `kubectl get` but so far only in `kubectl apply`. 
To reproduce issue a `kubectl apply` with `-o =jsonpath='{.kind} {.metadata.namespace} {.metadata.name}'` flags set or similar.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):

> NAME="Ubuntu"
> VERSION="16.04 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by brecode** [comment]
@kubernetes-cli-bugs

**Comment by liggitt** [comment]
@juanvallejo @soltysh

**Comment by juanvallejo** [comment]
@deads2k looks like we need to special-case printflags for apply. Will open PR

**Comment by liggitt** [comment]
> looks like we need to special-case printflags for apply

Did providing a template change the default output to go-template generally?

**Comment by juanvallejo** [comment]
> Did providing a template change the default output to go-template generally?

Yes, for commands that originally supported --template, the default was go-template as far as I recall

**Comment by soltysh** [comment]
Cherry-picked into 1.11 in https://github.com/kubernetes/kubernetes/pull/65873.

**Comment by nikhita** [comment]
This has been fixed in https://github.com/kubernetes/kubernetes/pull/65979. Closing.

/close
