### ISSUE TITLE
kubelet restart seems getting slower recently

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#65661]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
We noticed this as the test/e2e_node/gpu_device_plugin.go has been failing recently due to timeout on waiting for gpu resource to show up after kubelet start/restart. From running the gpu_device_plugin e2e_node test on GCE, I saw it took ~37 seconds for kubelet to start CM DeviceManager after it restarts, and then took ~12 seconds for the gpu device plugin to re-register. As the result, the gpu_device_plugin e2e_node test fails because the current 10 sec waiting time is too small. Restarting a container also seems to get slower that it sometimes exceeds the current 2 min waiting time in ensurePodContainerRestart().

I am filing this issue to see whether this is expected.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/pull/65541
