### ISSUE TITLE
docker pull k8s.gcr.io/fluentd-elasticsearch:v2.2.0 failed with authentication required

### ISSUE THREAD

**Issue by tubzby** [kubernetes/kubernetes#65663]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

deploy EFK with  cluster/addons/fluentd-elasticsearch/, find out deploy failed with Error: ImagePullBackOff.

after doing a docker pull on one node I find out the registry server is requiring Authentication.

```console
root@server4:~# docker pull k8s.gcr.io/fluentd-elasticsearch:v2.2.0
Pulling repository k8s.gcr.io/fluentd-elasticsearch
unauthorized: authentication required
root@server4:~# 
```

**What you expected to happen**:

fluentd images can pull from k8s.gcr.io

**How to reproduce it (as minimally and precisely as possible)**:
1. cd cluster/addons/fluentd-elasticsearch
2. kubectl deploy -f .

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
liuzhipingdeMacBook-Air:src liuzhiping$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
liuzhipingdeMacBook-Air:src liuzhiping$ 

- Cloud provider or hardware configuration:
2 node dev machines
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux server4 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by IvanovOleg** [comment]
I have the same issue

**Comment by thockin** [comment]
This works for me from an unauthenticated machine.  Is it still happening or transient?

**Comment by tubzby** [comment]
It's ok now.
