### ISSUE TITLE
Timeout: request did not complete within allowed duration

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/kubernetes#65671]
kind bug

**What happened**:
when i create a deploy,it can not be create,it show "timeout"

**What you expected to happen**:
i want to create the deploy normally,and i want to know the reason that can not be created

**How to reproduce it (as minimally and precisely as possible)**:
yaml:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: registry.iot.com:5000/library/iop/nginx:1.11.4-alpine
          ports:
            - containerPort: 80
command: kubectl create -f nginx-deployment.yaml
result: Error from server (Timeout): error when creating "nginx-deployment.yaml": Timeout: request did not complete within allowed duration

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.5
- OS (e.g. from /etc/os-release):centos 7.2.1511

**Comment by shigy123456** [comment]
@kubernetes/sig-NODE-node

**Comment by hzxuzhonghu** [comment]
I think you should check whether your etcd cluster is healthy.

**Comment by shigy123456** [comment]
thanks for your  advice，i have checked etcd and i restart the etcd,it work normally.

**Comment by shigy123456** [comment]
but the problem still exists.

**Comment by shigy123456** [comment]
@dchen1107

**Comment by hzxuzhonghu** [comment]
@shigy123456 You should give more details, otherwise no one knows how to help you.

**Comment by shigy123456** [comment]
ok,i have reloaded my k8s environment,the problem is gone.but i do not know the reason of timeout.but ths for paying attention to my problem.

**Comment by a1exus** [comment]
Hello,

I'm having same issue(

https://discuss.elastic.co/t/error-from-server-notfound-services-quickstart-es-http-not-found/193658/8
