### ISSUE TITLE
`kubectl create priorityclass` failure

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#65685]
/kind bug
> /kind feature

**What happened**:
When I try to create a priorityclass object like:
`kubectl create priorityclass default-priority --value=1000 --description="high priority"`
It fails with `error: no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1alpha1"`
And when I try create it with yaml file like:
```
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```
It works.

**What you expected to happen**:
Create a priorityclass object with kubectl.

**Comment by CaoShuFeng** [comment]
Do you have --runtime-config=scheduling.k8s.io/v1alpha1=true set in kube-apiserver?

**Comment by WanLinghao** [comment]
@CaoShuFeng  No, if set this, it works.

**Comment by CaoShuFeng** [comment]
Agree this is a bug. v1beta1 should be preferred.
