### ISSUE TITLE
Turn on profiling in tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#65698]
Currently, in our tests, we have an ability to profile kube-apiserver (profiling enabled by default) and scheduler (we switch it on in scalability tests).

However, we need an ability to profile other components too, in particular:
- controller-manager
- kube-proxy
[for those it's a matter of enabling it in our tests]
- kubelet
[which doesn't export /profile handler]

@kubernetes/sig-scalability-feature-requests

**Comment by wojtek-t** [comment]
controller-manager and kube-proxy has been enabled (it requires some cleanup in job configs in test-infra though, but it's happening independently)

for kubelet - I will take a look.

**Comment by shyamjvs** [comment]
Did you intend to just turn on profiling for the components or you also want to capture them in our tests (because the latter needs more changes)?

**Comment by wojtek-t** [comment]
I just wanted the former. The latter we can do if needed - for now I just wanted to be able to grab them on running tests, which wasn't possible so far.

**Comment by wojtek-t** [comment]
Actually kubelet also exposes profiling handlers - I just failed to find them initially.
https://github.com/kubernetes/test-infra/pull/8576 is fixing that
