### ISSUE TITLE
Kubelet can't unmount glusterfs volumes

### ISSUE THREAD

**Issue by ateleshev** [kubernetes/kubernetes#65703]
/kind bug

**What happened:**
The node#1 in the cluster lost network connection with the node#2 which contains GlusterFS node with some distributed volume. At the same time node#2 received request to delete this volume (delete workload: Pod + PVC). 
After some time connection was restored between node#1 and node#2. 
Kubelet tries remove Pod and can't complete this opperation becouse pvc and volume in glusterfs is already removed.

```
cannot access '/var/lib/kubelet/pods/41e1014f-7a38-11e8-abcc-0cc47abc36e8/volume-subpaths/pvc-320bf89f-7a38-11e8-a7db-00259097cf2c/test-volumes-mounted-3-wordpress/0': Transport endpoint is not connected
```

```
root@node1:/# mount | grep 41e1014f-7a38-11e8-abcc-0cc47abc36e8
10.0.0.4:vol_17bc1a7e5a80f706dd03da2bfd02e973 on /var/lib/kubelet/pods/41e1014f-7a38-11e8-abcc-0cc47abc36e8/volumes/kubernetes.io~glusterfs/pvc-320bf89f-7a38-11e8-a7db-00259097cf2c type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
10.0.0.4:vol_17bc1a7e5a80f706dd03da2bfd02e973 on /var/lib/kubelet/pods/41e1014f-7a38-11e8-abcc-0cc47abc36e8/volume-subpaths/pvc-320bf89f-7a38-11e8-a7db-00259097cf2c/test-volumes-mounted-3-wordpress/0 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
10.0.0.4:vol_17bc1a7e5a80f706dd03da2bfd02e973 on /var/lib/kubelet/pods/41e1014f-7a38-11e8-abcc-0cc47abc36e8/volume-subpaths/pvc-320bf89f-7a38-11e8-a7db-00259097cf2c/test-volumes-mounted-3-wordpress/1 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
10.0.0.4:vol_17bc1a7e5a80f706dd03da2bfd02e973 on /var/lib/kubelet/pods/41e1014f-7a38-11e8-abcc-0cc47abc36e8/volume-subpaths/pvc-320bf89f-7a38-11e8-a7db-00259097cf2c/test-volumes-mounted-3-wordpress/2 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
```

When kubelet reads sub-paths: 

> subPaths, err := ioutil.ReadDir(fullContainerDirPath)

an error occurs: Transport endpoint is not connected
And the pod remain in the Terminating status and never will be deleted.

https://github.com/kubernetes/kubernetes/blob/v1.10.4/pkg/util/mount/mount_linux.go#L854
```
    // scan /var/lib/kubelet/pods/<uid>/volume-subpaths/<volume>/<container name>/*
    fullContainerDirPath := filepath.Join(subPathDir, containerDir.Name())
    subPaths, err := ioutil.ReadDir(fullContainerDirPath)
    if err != nil {
      return fmt.Errorf("error reading %s: %s", fullContainerDirPath, err)
    }
```

**Environment**:
- Kubernetes version: v1.10.4
- OS: Container Linux by CoreOS 1745.7.0 (Rhyolite)
- Kernel: Linux node1 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz GenuineIntel GNU/Linux

**Comment by ateleshev** [comment]
@jianzi123 We wrote additional component to solve this problem, and I think it will be fixed in github.com/humblec/gluster-csi-driver

**Comment by jianzi123** [comment]
@ateleshev Thanks. Could you tell this problem in details.

**Comment by humblec** [comment]
@ateleshev Can you please share more details about 

> @jianzi123 We wrote additional component to solve this problem, and I think it will be fixed in https://github.com/gluster/gluster-csi-driver>

Also which version of glusterfs is in use here ?

**Comment by ateleshev** [comment]
In gluster container we use:
```
# gluster --version
glusterfs 4.1.1
```
In kubelet container we use:
```
# glusterfs --version
glusterfs 4.1.4
```
And for kubernetes provisioner we use Heketi: 7.0.0
