### ISSUE TITLE
kubectl 1.10 prints header after a chunk, instead of only once

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#65727]
In kubectl 1.10, when I fetch enough pods to cause a ranged page (>500), the headers get printed twice:

```
$ kubectl get pods -o wide --all-namespaces
NAMESPACE                           NAME                                              READY     STATUS              RESTARTS   AGE       IP              NODE
acs-engine-build                    acs-engine-web-16-t6prn                           1/1       Running             0          2d        172.16.13.124   origin-ci-ig-n-hs69
...
ci                                  tot-0                                             1/1       Running             0          12h       172.16.13.175   origin-ci-ig-n-hs69
NAMESPACE                           NAME                                              READY     STATUS              RESTARTS   AGE       IP              NODE
ci                                  tracer-14-4jw7f                                   2/2       Running             0          3d        172.16.13.55    origin-ci-ig-n-hs69
...
```

The headers should only be printed once.  This is a bug in chunk printing.

@kubernetes/sig-cli-bugs

**Comment by smarterclayton** [comment]
@juanvallejo

**Comment by liggitt** [comment]
I'm pretty sure this is working as intended. The column spacing is computed given a set of specific data. For a new chunk, the column spacing can be different, and we want headers aligned with content

**Comment by soltysh** [comment]
Hmmm... I'm guessing this might be related with the chunk size, which results in each data package to contain its own headers, which then gets printed. We could maybe omit the headers given that we're working with a single resource type here.

**Comment by liggitt** [comment]
> We could maybe omit the headers given that we're working with a single resource type here.

that will result in misaligned headers
