### ISSUE TITLE
Conformance: Add subpath tests for atomic volumes

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#65721]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 

**What happened**:
In test/e2e/storage/subpath.go, the tests with context "Atomic writer volumes" are candidates to be added to the conformance suite.

**Comment by mkurylec** [comment]
# https://github.com/kubernetes/kubernetes/pull/65793

**Comment by msau42** [comment]
Added in https://github.com/kubernetes/kubernetes/pull/66871
/close
