### ISSUE TITLE
open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory 

### ISSUE THREAD

**Issue by bigV0616** [kubernetes/kubernetes#65734]
system: centos7 kernel:3.10  
i use kubectl get pod fount status is ContainerCreating, 
![image](https://user-images.githubusercontent.com/26765206/42192790-9d4e5b08-7e9d-11e8-8c36-086c5d7dc7c3.png)
how resolve this question? tks

**Comment by dims** [comment]
/close

looks like a docker problem on centos, please ask your OS vendor
