### ISSUE TITLE
Unbounded kube-apiserver memory growth

### ISSUE THREAD

**Issue by brianmartin** [kubernetes/kubernetes#65732]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

One of our static kube-apiserver pods will climb in memory usage by ~200 MB per minute until it fills up the 32 GB of memory on the instance. When it crashes or is manually restarted, another kube-apiserver (possibly the replacement, possibly one from another master) will begin to exhibit the same runaway memory usage nearly immediately.

**What you expected to happen**:

Stable memory usage, which scales with load (both up and down).

**How to reproduce it (as minimally and precisely as possible)**:

We have not been able to reproduce. The behavior is intermittent but ongoing. We are able to collect more debugging information.

My team has attempted toggling services which might be causing load to the apiserver (no change), profiling the kube-apiserver with pprof (the memory is somewhere in etcd code, but it’s not clear why), and profiling the instances themselves (not seeing unusual disk/networking/etc. usage).

At this point, we’re looking for ideas, pointers for how to dig deeper and investigate. The issue does come and go. When the memory is actively climbing we’re looking at a kube-apiserver restart every ~2 hours.

**Anything else we need to know?**:

We’ve taken some pprof PDFs which indicate etcd/json as having the vast majority of the memory footprint:

- Mem
  - [apiserver-mem-06-29-2018-03-11p.pdf](https://github.com/kubernetes/kubernetes/files/2157148/apiserver-mem-06-29-2018-03-11p.pdf)
  - [apiserver-mem-06-29-2018-03-23p.pdf](https://github.com/kubernetes/kubernetes/files/2157149/apiserver-mem-06-29-2018-03-23p.pdf)
- Cpu
  - [apiserver-cpu-06-29-2018-03-15p.pdf](https://github.com/kubernetes/kubernetes/files/2157150/apiserver-cpu-06-29-2018-03-15p.pdf)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
  - AWS
- OS (e.g. from /etc/os-release):
```    
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
...
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ip-10-79-158-202 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
```
- Install tools:
  - kops 1.9.1
- Others:

**Comment by brianmartin** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Is this reproducible with etcd3?

**Comment by yue9944882** [comment]
@brianmartin Could you show us your configuration options of your apiserver? `target-ram-mb` or `watch-cache` related options of etcd.

**Comment by brianmartin** [comment]
@yue9944882 Here's a full [gist of our apiserver invocation](https://gist.github.com/brianmartin/b879da3e03e387fd9c49ddd23514dd42). In particular, we do not explicitly specify `watch-cache`, `target-ram-mb`, or `max-requests-inflight`. Our cluster currently has ~75 nodes with ~1750 pods total.

@liggitt We have not been able to reproduce this issue outside of our production cluster, which is using etcd 2.2.1. We've stuck with etcd 2 in anticipation of in-progress kops work to make the upgrade easier for existing clusters (https://github.com/kubernetes/kops/issues/4463; I see you in the comments there!).

(@yue9944882 @liggitt Thanks both of you for the questions!)

**Comment by brianmartin** [comment]
@liggitt We've done a bit more digging and are now upgrading from 1.9.8 to 1.9.9. In particular, your change here https://github.com/kubernetes/kubernetes/pull/65339 may be relevant for us, as we cycle through many pods which utilize tolerations. I'll provide an update here once we're upgraded.

**Comment by brianmartin** [comment]
Ah, disregard my last comment. (duh) We're observing a leak in the kube-apiserver, where that fix is for the kube-controller-manager.

**Comment by yue9944882** [comment]
@liggitt @brianmartin I was worrying about the leak before. It could possibly caused by dead/inactive go routine produced from `Watch` call of etcd storage (also for etcd3).

[https://github.com/kubernetes/kubernetes/blob/df1826c9d7d0f9a7651170a9629dd1cec0d4c3b0/staging/src/k8s.io/apiserver/pkg/storage/etcd/etcd_helper.go#L240](https://github.com/kubernetes/kubernetes/blob/df1826c9d7d0f9a7651170a9629dd1cec0d4c3b0/staging/src/k8s.io/apiserver/pkg/storage/etcd/etcd_helper.go#L240)

IIRC, the go routine here would never be destroy unless the context is terminated. And before #62810 the context would be stored in a global map and deleted from the request is finished/aborted, then the context would be evicting together with the KV datas in it. Not really sure but it must be a problem. 🤓#65087 Seems also related.

**Comment by liggitt** [comment]
I don't think that is the issue. Watch requests have timeouts associated with them, and do get closed, at which point the context object is removed. We also haven't seen this sort of memory growth in all servers, and I think something that fundamental like that would appear more consistently.

**Comment by brianmartin** [comment]
Here's a visual for `docker.mem.rss` for our kube-apiserver containers over the last week. The y-axis is in GB, where our request limit is set to 18GB starting Fri 8pm.

There are definitely periods of non-growing memory usage.

![screenshot 2018-07-05 10 45 20](https://user-images.githubusercontent.com/130559/42339073-c213a96c-8040-11e8-9e8c-ee6c2739051d.png)

**Comment by liggitt** [comment]
Do you have audit logs for the growth periods to narrow down what types of activity correspond to growth?

**Comment by wendorf** [comment]
I'm on @brianmartin's team, so can help answer.

I believe there's correlation with times of moderately heavy pod creation. We have a custom Spark job launcher that can create on the order of ~1000 pods every hour or so. We haven't proved that this is the cause, but our intuition is leading us in that direction. They're pods with tolerations in order to be scheduled on a group of nodes dedicated to those Spark jobs.

**Comment by wendorf** [comment]
To provide an update:

We've since created a second cluster for all of our Spark jobs, and have fully migrated them to the new cluster. Our original cluster no longer shows this memory problem, and the problem has migrated to the new cluster along with the Spark jobs, so it does look like our original hunch is correct. _Why_ that's correct is still elusive.

**Comment by hameno** [comment]
I'm seeing this too with 1.11.1 and etcd 3.2 - completely breaks my cluster

**Comment by dims** [comment]
@liggitt we need to worry about this for 1.12 right?

**Comment by liggitt** [comment]
> @liggitt we need to worry about this for 1.12 right?

it didn't block 1.9, 1.10, or 1.11 releases, so I don't anticipate it blocking 1.12, though we would certainly want to fix it if we were able to narrow down the cause.

@brianmartin @wendorf are you seeing this issue with --storage-backend etcd3? the etcd2 backend has known performance issues and will be removed after 1.12.

@hameno do you have more details about your apiserver invocation, specific etcd version, usage patterns (what is going on in your cluster when this occurs) and memory growth?

**Comment by salilgupta1** [comment]
Are there any updates on this issue? We are seeing a similar issue with our cluster during load testing. 

**Cluster Configuration**
K8s version: 1.11
etcd: 2.2.1 (2 clusters, 1 for events, 1 general)
Masters Node config: 3, AWS m4.4xlarge (64 GIB,  16 cores)
Kops: 1.9.2
API Config: Standard defaults, we aren't setting any of the flags mentioned in the thread above.

We also haven't tried etcd3 b/c we are waiting for Kops to support the migration from 2 -> 3.

**Cluster Usage Behavior**
Our cluster is used as a job system. At any point we could receive a large surge of jobs, which translates into an increase in Pod and Node creation. We really don't have 

The nodes themselves run a couple of daemonsets that may be of interest:
kube2iam which has a watch on pods filtered by node
canal which has a watch on endpoints

**Metrics**
etcd memory usage
<img width="1188" alt="screen shot 2018-09-09 at 11 03 44 pm" src="https://user-images.githubusercontent.com/5280219/45275851-a8793a80-b484-11e8-8618-351e6851868a.png">

etcd cpu usage
<img width="1184" alt="screen shot 2018-09-09 at 11 04 32 pm" src="https://user-images.githubusercontent.com/5280219/45275874-c34baf00-b484-11e8-8bb5-8a08c98f427e.png">

API Server Memory
<img width="1187" alt="screen shot 2018-09-09 at 11 06 32 pm" src="https://user-images.githubusercontent.com/5280219/45275901-086fe100-b485-11e8-814f-e1e356621eb4.png">

API CPU Usage
<img width="1173" alt="screen shot 2018-09-09 at 11 07 29 pm" src="https://user-images.githubusercontent.com/5280219/45275952-453bd800-b485-11e8-8c05-993d269e904f.png">

Pods, Containers, and Nodes in Cluster
<img width="1196" alt="screen shot 2018-09-09 at 11 08 49 pm" src="https://user-images.githubusercontent.com/5280219/45275971-5f75b600-b485-11e8-8ad8-29f8be8fa1fa.png">

The most concerning is the sudden spike in memory usage for both the api and etcd containers on two of the master nodes. However, we didn't add a huge amount of nodes or pods/containers onto the cluster when we see the spike.

**Comment by wendorf** [comment]
Finally have an update! We upgraded to etcd 3.2 and have seen a huge improvement. On etcd 2, we used to hit ~18 GB on an API server every hour or so and have to terminate it. Very spikey memory usage. On etcd3, our memory usage has so far totally smoothed out. Now all three of our API servers are running consistently at ~ 0.75 GB, and have done that for 16 hours. I'm ready to declare success here.

**Comment by McSlow** [comment]
Same here, etcd 3.2.18, k8s 1.11.3. We also see those huge memory increases during heavy pod creation ( there's a gitlab kubernetes executor running which spins up quite a lot of pods during peak times).
Memlimit for the apiserver currently 2GB, takes 2-10 hours till oomkiller kicks in, depending on the amount of CI jobs.

**Comment by krmayankk** [comment]
We just witnessed this with a large number of pods ~16K in 1.9.7 and etcd 2. What mitigations are being planned in the core apiserver code to handler this ?

**Comment by sevensees** [comment]
We met this with with 30 concurrent rolling update against deployments (5 * 1000 replicas and 25 * 75 replicas) in 1.13.4 kubernetes (5000 nodes cluster) and 3.3.11 etcd. The memory will increase extremely from 20+ GB to 110+ GB and eat up all system memory. Then OOM occurs or the system has no response for several minutes. This is reproducible in our cluster.

**Comment by krmayankk** [comment]
/close
 this was resolved with etcd3, so closing, please reopen if necessary
