### ISSUE TITLE
Cannot update service from another type to ExternalName because of clusterIP and port

### ISSUE THREAD

**Issue by CathySha** [kubernetes/kubernetes#65740]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Cannot update service from another type to ExternalName using io.fabric8.kubernetes.client.dsl.internal.ServiceOperationsImpl.replace(Service item).
The Request Body is:
 {
        "name": "sha1",
        "namespace": "sha",
        "uid": "xxx",
        "labels": [{
            "xxx": "xxx"
        }],
        "selector": null,
        "clusterIP": null,
        "externalIPs": [],
        "ports": [
            {
                "protocol": "TCP"
            }
        ],
        "ingress": [],
        "type": "ExternalName",
        "createdOn": null,
        "createdBy": null,
        "age": null,
        "links": [
            "x.x.x.x:x"
        ],
        "ennIngress": null,
        "externalName": "a.b.c.d"
    }
The error message is:
Service sha-service-1 is invalid: 
[spec.clusterIP: Invalid value: x.x.x.x: must be empty for ExternalName services, spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive]. 

(1) the problem of clusterIP:
I tried to change this line
"clusterIP": null
to 
"clusterIP": "None"
or to
"clusterIP": ""
or even delete this line, but it didn't work, the error message was the same.
I also tried to set null value in the java program to the clusterIP of the service, but it didn't work.
It always get the clusterIP of the service, and tell me the error.

(2) the problem of port:
I tried to change this part
"ports": [
            {
                "protocol": "TCP"
            }
        ],
to 
"ports": [],
or to 
"ports": [
            {
                "port": 2000
            }
        ],
Then the error "spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive" will not appear.
i.e. I must give it a port number or give nothing. If I give something incomplete, it cannot work.

**What you expected to happen**:
No matter how I write the clusterIP and ports parts in the request body, It should update successfully.
Because according to the documentation, for service type ExternalName, clusterIP and port should be both ignored.

**How to reproduce it (as minimally and precisely as possible)**:
Using
io.fabric8.kubernetes.client.dsl.internal.ServiceOperationsImpl.replace(Service item)
to update a service from any other type to ExternalName type, and use the following request body
 {
        "name": "sha1",
        "namespace": "sha",
        "uid": "xxx",
        "labels": [{
            "xxx": "xxx"
        }],
        "selector": null,
        "clusterIP": null,
        "externalIPs": [],
        "ports": [
            {
                "protocol": "TCP"
            }
        ],
        "ingress": [],
        "type": "ExternalName",
        "createdOn": null,
        "createdBy": null,
        "age": null,
        "links": [
            "x.x.x.x:x"
        ],
        "ennIngress": null,
        "externalName": "a.b.c.d"
    }

**Anything else we need to know?**:
If it is not a bug, how can I solve this problem?
Did I use the right function?
How can I update the service type to ExternalName without validating the clusterIP and port?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2(server)

**Comment by CathySha** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Some type transitions are not allowed. You can delete and recreate a service with a different type

**Comment by CathySha** [comment]
Thank you for the answer.
I tried to delete and recreate a service with a different type, but a problem always occurred: deletion can always success, but sometimes recreation fails...
I tried to get the origin service from cluster firstly, and then tried to delete the old service and create the new service, if deletion succeeded and recreation failed, then recreated the origin service, but it gives me the error:

resourceVersion should not be set on objects to be created. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=resourceVersion should not be set on objects to be created, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={})."

According to the error message, resourceVersion=null, but recreation fails.
Do you have any suggestions about this problem?
Thank you very much!

**Comment by CathySha** [comment]
Thank you @liggitt .
And I also have a question: Can I rename a service? If yes, how to rename the service?

**Comment by liggitt** [comment]
> Can I rename a service? If yes, how to rename the service?

No, name and namespace are immutable. You can delete and recreate an object with a different name
