### ISSUE TITLE
Spark job dynamic resource allocation with Kubernetes

### ISSUE THREAD

**Issue by DatPhanTien** [kubernetes/kubernetes#65746]
Dear,

We are interesting in running Spark jobs on Kubernetes.
There are two types of Spark jobs in our cluster.

- Batch jobs that have high workload but do not require fast response.
- Interactive jobs, that are triggered from user side, which have strict response time requirement (order of seconds or less).

Expectation:
1) We would like to know whether it is possible to put priority for such jobs, so that the interactive jobs have higher priority? Once the interactive jobs are triggered, batch jobs are supposed to quickly free resources (e.g., by getting killed) so that the interactive jobs can have the maximum resources allocated in order to meet the response time requirement.
2) It would be perfect if Kubernetes support dynamic resource allocation. By "dynamic resource allocation", we mean that the resource requirement for a job MUST NOT be fixed. For instance, instead of giving a job 3 CPU and 5GB mem, it would be better to set the job that can take 50% of the available resource (and 50% of course a configuration parameter that users can define as their will).

So far, we could not find any documentation about Kubernetes that mentions this.
Could you please enlighten us.

Best

**Comment by k82cn** [comment]
/sig scheduling

For case 1: [priority/preemption feature](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) will make sure the pod with higher priority to run (preempt lower priority pod if necessary).

For case 2: [kube-arbitrator](https://github.com/kubernetes-incubator/kube-arbitrator) support share resource between jobs by DRF, DRF with weight and Proportion is on going.

BTW, is the cluster dedicated for Spark job? How does you run Spark on kubernetes, by Spark On Kubernetes integration?

**Comment by DatPhanTien** [comment]
Dear 

Thanks for your fast answer.
Our cluster runs other long-running services also (HDFS, HBase, ...).
We deploy Spark via a Spark docker image that we built. 

Best
