### ISSUE TITLE
smb mount security issue

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#65750]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
user PowerShell Environment Variables to store user input string to prevent command line injection, the env var in PowerShell would be taken as literal values and not as executable vulnerable code, this kind of fix is common for command line injection issue (called: parameterized way)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows
/sig storage
/assign

**Comment by jingxu97** [comment]
@andyzhangx, do you still plan to work on this issue? Thanks!

**Comment by andyzhangx** [comment]
@jingxu97 which issue? the original issue is fixed by https://github.com/kubernetes/kubernetes/pull/65751

**Comment by jingxu97** [comment]
oh, sorry I missed that.

**Comment by PushkarJ** [comment]
/label official-cve-feed

(Related to kubernetes/sig-security#1)
