### ISSUE TITLE
kubectl on macosx doesn't list pods

### ISSUE THREAD

**Issue by ars05** [kubernetes/kubernetes#65765]
**this a BUG REPORT**
/kind-bug

**What happened**:
kubctl v0.11.0 is not responding to get pods command, on mac osx Darwin  17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**What you expected to happen**:
get a list of running pods

**How to reproduce it (as minimally and precisely as possible)**:
install v1.11.0 run kubectl get pods --kubeconfig and the output will be:
No resources found 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Darwin  17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
- Kernel (e.g. `uname -a`):
Darwin  17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by liggitt** [comment]
can you include trace information to see what is coming back from the server by passing `--v=9`? be sure to remove any credential headers before pasting
