### ISSUE TITLE
Can not force delete pod in Unknown state

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#65766]
**BUG REPORT**:

/kind bug

**What happened**:

Cannot force delete pods in `Unknown` state, after upgrade to `1.11`.
```
kubectl get pod mypod-0 -o wide                 
NAME         READY     STATUS    RESTARTS   AGE       IP             NODE
mypod-0      1/1       Unknown   0          19d       10.112.7.248   node1
```
```
kubectl delete pod mypod-0 --grace-period=0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "mypod-0" force deleted
```
But nothing happend, pod is still there

**What you expected to happen**:

Pod successful removed.

**How to reproduce it (as minimally and precisely as possible)**:

* Run pod on some node
* Force shutdown the node
* Try to remove the pod

**Anything else we need to know?**:

Pod is still there even if you remove the node from kubernetes cluster.
Simmilar issue for old k8s version: https://github.com/kubernetes/kubernetes/issues/51333

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.11.0`
- Cloud provider or hardware configuration: `bare-metal`
- OS (e.g. from /etc/os-release): `Ubuntu 16.04.4 LTS`
- Kernel (e.g. `uname -a`): `4.13.0-37-generic`
- Install tools: `kubeadm`
- Others:

**Comment by liggitt** [comment]
If you fetch the pod yaml from the API, what finalizers are listed on the pod?

**Comment by kvaps** [comment]
Hi, here is
```
metadata:
  deletionGracePeriodSeconds: 0
  finalizers:
  - foregroundDeletion
```
those pods was created by DaemonSet and StatefulSet 

After removing finalizer field, pods successfully disappear. So no bug?

**Comment by kvaps** [comment]
OK, this steps solved my problem:
```
PODS=$(kubectl get pod | grep Unknown | cut -d' ' -f1)

kubectl delete pods $PODS --grace-period=0 --force --wait=false
kubectl patch pods $PODS -p '{"metadata":{"finalizers":null}}'
```

**Comment by valer-cara** [comment]
Perfection! I've been going through the garbage collector code, apiserver registry stuff to try to figure out what's going on when deleting a pod and why's it getting stuck...
... it was the `finalizer` for me as well

**Comment by enzian** [comment]
hey, I have the same problem but `kubectl patch pod mypod-0 -p '{"metadata":{"finalizers":null}}'` throws me an error:
```
The Pod "kafka-0" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```
My cluster is at `v1.8.10`! Could it be that patching finalizers is only allowed in newer cluster versions?

**Comment by valer-cara** [comment]
@enzian I've been patching finalizers to an empty array instead of null and it worked for me.

**Comment by enzian** [comment]
We'll update our cluster and I'll check back in with you guys once I succeed!
