### ISSUE TITLE
Allow the pluginwatcher lifecycle to do zero downtime upgrade

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#65772]
Hello!

/sig node
/cc @jiayingz @vikaschoudhary16 @vishh @vladimirvivien @sbezverk @saad-ali 

Currently the lifecycle of a plugin going through the pluginwatcher process is the following:

![current](https://user-images.githubusercontent.com/2519571/42231914-2e5331e2-7eed-11e8-9cca-efb86f4c5e91.PNG)

This is an issue as it doesn't allow pluginwatcher consumers to implement zero downtime upgrade. Paired with the re-registration issue #65770 I suggest we change the pluginwatcher lifecycle to make it clear that a plugin watcher consumer (device Plugin, CSI) can and should be doing Initialization during it's callback.

I've create an example lifecycle that shows how this would apply to the Device Plugin and allow for zero downtime upgrade:

![new](https://user-images.githubusercontent.com/2519571/42232120-c7c4df88-7eed-11e8-86c6-c105e24115eb.PNG)

**Comment by vishh** [comment]
@RenaudWasTaken can you elaborate more on how/why the current lifecycle hinders upgrades?

**Comment by RenaudWasTaken** [comment]
Hello @vishh 

> @RenaudWasTaken can you elaborate more on how/why the current lifecycle hinders upgrades?

The current lifecycle does not hinder upgrades. I've opened this issue as part of the pluginwatcher work tracker umbrella issue in order to discuss the registration mechanism with the community.

The goal is to discuss whether the registration mechanism of the pluginwatcher should be designed for 0 downtime upgrades. This is currently not the case in the device manager mechanism (We set the devices as unhealthy until the `ListWatch` call returns the list of devices) and the current implementation doesn't allow for that.

IMHO, It seems reasonable to have this feature as a beta requirement given that it might change the internal and external API and behavior.

**Comment by vishh** [comment]
Thanks for explaining. Sounds reasonable to me to include this in Beta.
Having a simpler lifecycle is always preferable.

**Comment by figo** [comment]
@RenaudWasTaken  thanks for write this up, i think this is a valid issue, what i observed on a GPU cluster, there is a delay between GPU device plugin deployment success and GPU capacity (capacity and allocatable) shows up in node info, which i believe it is similar to upgrade downtime.
although i have not measured the exact delay, but it more than 1 or 2 seconds.

/cc myself.

**Comment by RenaudWasTaken** [comment]
Fixed by kubernetes/kubernetes/pull/64621
