### ISSUE TITLE
Flexvolume test fails on ubuntu

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#65777]
* https://k8s-testgrid.appspot.com/sig-node-containerd#e2e-ubuntu
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-e2e-ubuntu

It passes on COS.

@kubernetes/sig-node-bugs @kubernetes/sig-storage-bugs 
/cc @yguo0905 @verult

**Comment by gnufied** [comment]
I can look into this, since likely this was introduced because of latest changes I made.

**Comment by verult** [comment]
That's strange, the dummy driver just sets up a tmpfs so it should be fairly quick. I wonder if there's something else blocking pod creation?

**Comment by wongma7** [comment]
the driver is not being installed on kubelet
```
E0709 17:27:18.300844    2874 desired_state_of_world_populator.go:311] Failed to add volume "flex-volume-0" (specName: "flex-volume-0") for pod "542525a3-839d-11e8-9973-42010a800002" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "flex-volume-0" err=no volume plugin matched
I0709 17:27:18.301252    2874 kubelet.go:1930] SyncLoop (housekeeping)
```
I am doing some more investigating, have my own cluster up.

**Comment by wongma7** [comment]
On ubuntu, we set the flexvolume install dir to --volume-plugin-dir=/home/kubernetes/fl
exvolume
Small oversight, I'll make a PR shortly

**Comment by wongma7** [comment]
They are still failing, I am having another look
