### ISSUE TITLE
Support enabling BlockStorage but disabling LoadBalancer in cloud provider

### ISSUE THREAD

**Issue by splashx** [kubernetes/kubernetes#65775]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I use [Openstack Block Storage](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#openstack) but my cloud provider doesn't support Openstack LBaaS. Because of the latter I've been using MetalLB instead to get things going. However I keep getting warnings when deploying a `ServiceType: LoadBalancer` when there is no `[LoadBalancer]` configuration defined in `cloud.conf`.  [Reference](https://github.com/google/metallb/issues/269#issuecomment-400727870)

NOTE: `cloud.conf` has only a `[Global]` section - there is no mention no `[LoadBalancer]` section.

**What you expected to happen**:

`service-controller` should not print warning via Openstack LoadBalancer since it doesn't support/can't do anything with it.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure `cloud.conf`

```
[Global]
auth-url=<value>
username=<value>
password=<value>
region=<value>
tenant-name=<value>
tenant-id=<value>
```
- [Install MetalLB](https://metallb.universe.tf/installation/)
- Push a `layer2` [ConfigMap](https://metallb.universe.tf/tutorial/layer2/#configure-metallb)
- Create a [LoadBalancer](https://metallb.universe.tf/tutorial/layer2/#create-a-load-balanced-service)

**Anything else we need to know?**:

See this [issue](https://github.com/google/metallb/issues/269#issuecomment-400727870)

**Environment**:

See this [issue](https://github.com/google/metallb/issues/269#issuecomment-400727870)

**Comment by zetaab** [comment]
that error is coming from row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L744 but I am not 100% sure should we support metallb in openstack cloud provider integration. Metallb is not part of openstack. @dims any opinion?

**Comment by dims** [comment]
@zetaab if there is no LBaaS in the environment and or no `[LoadBalancer]`, we should not try to deploy one (and let metallb to do the work as it is supposed to). i think.

**Comment by zetaab** [comment]
@splashx when you start node, do you see this log print in logs? https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L599

**Comment by splashx** [comment]
@zetaab With the original config `Claiming to support LoadBalancer` doesnt show up the log files. The only reference for `openstack.go` in the logs is:

```
Jul  3 19:28:28 master03 kube-controller-manager[4466]: W0703 19:28:28.953757    4466 openstack.go:721] Error initialising Routes support: router-id not set in cloud provider config
Jul  3 19:28:28 master03 kube-controller-manager[4466]: W0703 19:28:28.953798    4466 core.go:158] configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
```

Now, if adding `notworking` as `lb-version` it yields:

```
Jul  3 19:34:43 master03 kube-controller-manager[5168]: W0703 19:34:43.099677    5168 openstack.go:598] Config error: currently only support LBaaS v2, unrecognised lb-version "notworking"
Jul  3 19:34:43 master03 kube-controller-manager[5168]: E0703 19:34:43.099864    5168 core.go:75] Failed to start service controller: the cloud provider does not support external load balancers
Jul  3 19:34:43 master03 kube-controller-manager[5168]: W0703 19:34:43.100107    5168 controllermanager.go:441] Skipping "service"
Jul  3 19:34:43 master03 kube-controller-manager[5168]: W0703 19:34:43.644042    5168 openstack.go:721] Error initialising Routes support: router-id not set in cloud provider config
```

And:

* ✅ The IP allocation via MetalLB works
* ✅ The service is remotely available
* ✅ The warning on `LoadBalancer` object disappears:

```
Events:
  Type    Reason       Age   From                Message
  ----    ------       ----  ----                -------
  Normal  IPAllocated  1m    metallb-controller  Assigned IP "100.127.184.12"

```

**Comment by zetaab** [comment]
weird, without this Loadbalancer thing it should end up to row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L601 and print "Claiming to support LoadBalancer". Now when you added that Loadbalancer section with random lb-version it ends up to row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L596 and it does not have support to external loadbalancer from openstack. When using metallb the init function in openstack should return false (no support from openstack) but I do not have now idea why it does not do that

**Comment by splashx** [comment]
@zetaab I take it back. my log level was too high. It does show up:

```
Jul  3 19:57:10 master03 kube-controller-manager[8065]: I0703 19:57:10.312516    8065 openstack.go:602] Claiming to support LoadBalancer
```

**Comment by zetaab** [comment]
cool, then we should have check in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L573 function as first thing which checks is LoadBalancer even defined in config - if no then return nil, false

**Comment by zetaab** [comment]
@dims (or someone else openstack guy) do you have time to run some test to fix this? I am on vacation and I do not have my test environment with me :)

I am thinking to add following to row https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L575 

```
	if os.lbOpts == (LoadBalancerOpts{}) {
		glog.V(4).Info("openstack.LoadBalancer() not defined in cloud-config")
		return nil, false
	}
```
So I am trying to check is lbOpts totally empty, if yes - then it does not initialize openstack lbaas at all
