### ISSUE TITLE
pluginwatcher: Handling re-registration 

### ISSUE THREAD

**Issue by RenaudWasTaken** [kubernetes/kubernetes#65770]
Hello!

/sig node
/cc @jiayingz @vikaschoudhary16 @vishh @vladimirvivien @sbezverk @saad-ali 

In other PRs, the issue of plugin registration and most importantly re-registration has surfaced. There's been some talks about implementing it in the CSI handler and the device plugin already has some sort of mechanism to handle it.

First we should agree on the definition of re-registration as this has and is still being discussed in the device plugin :)

There are two main scenarios:
1. Two plugins register (on two different sockets) with the same name at the same time and thus end up racing for the registration lock
2. A plugin registers with name "foo" after X seconds another registers with name X on a different socket

In terms of how realistic these are:
- 1's most likely cause is a test environment or a plugin re-starting after a crash
- 2's cause could be two device plugin with the same name (i.e: a user error)
- 2's legitimate cause could be trying a 0 downtime upgrade. Once the second plugin is registered it would stop the first plugin and remove it's socket.

I generally expect both scenarios to be handled in exactly the same way. Plugin registration should be a FIFO structure. The last fsnotify event we get should be the plugin that gets registered.

i.e: Regardless of which plugin started first, we process the plugins in the order fsnotify detects them and sends them through the channel.

**Comment by vladimirvivien** [comment]
One way to avoid all of these scenarios is to require Driver developers to use a namespaced dir structure for registration.  That should be doable now that pluginwatcher supports nested dir structure.

**Comment by RenaudWasTaken** [comment]
Hello Vladimir Vivien !

Can you highlight for this would resolve the use cases highlighted in my
first post?

Thanks!

**Comment by vladimirvivien** [comment]
@RenaudWasTaken 

> Two plugins register (on two different sockets) with the same name at the same time and thus end up racing for the registration lock

As I mentioned, I believe there is support for nested plugin registration dirs.  Maybe an adopted convention is to ask driver author to provide a name spaced directory to avoid collision, i.e.:
- `./<driver-type>/<vendor-org>.<driver-name>` 
- Examples: `./csi/k8s.nfs.sock`;  `./csi/aws.csi-driver.sock`; `./device/nvidia.gpu.sock`

That way there should not be any collision during registration since each driver is namespaced.

> A plugin registers with name "foo" after X seconds another registers with name X on a different socket

I am guessing this is saying two drivers registering with name "foo" X seconds apart.  If so, it should not happened if they are namespaced since that should guaranteed drivers have different names.

**Comment by RenaudWasTaken** [comment]
@vladimirvivien currently we don't require the socket name to be equal to the name advertised (i.e the name field in the gRPC API).

I don't believe we should adopt a convention on the full name either. As mentioned in the first post a legitimate use case for this discussion here is a plugin "upgrading" following a 0 downtime scheme.

To give a full example:
1. The NVIDIA device plugin 1.9.1 registers itself at `./device/nvidia/gpu-1.9.1.sock`
2. The device plugin runs for an indefinite amount of time until the cluster admins decides to upgrade it to 1.9.2
3. The NVIDIA device plugin 1.9.1 registers itself at `./device/nvidia/gpu-1.9.2.sock`
4. Once it is in a "running" state the cluster admin can remove the 1.9.1 device plugin

In any case the issue here is not the name collision at the FS level but how we handle the name collision at the gRPC level.

Should we decide to always accept the newest? Are there alternatives that makes sense?

**Comment by tianshapjq** [comment]
how about involving version into the plugin? i.e, adding pluginVersion into the pathInfo struct, and the version should follow the semantic version convension. 
If plugin registers without version, we will simply accept the newest incomming plugin without verifying which one is newer, and not responsible for the disordered registrations.
BTW, I do think version is needed for plugins sooner or later. As the device assignment issue is in progress, as a plugin developer, I would like to know the exact version being attached to containers.

**Comment by RenaudWasTaken** [comment]
@tianshapjq can you describe more what you have in mind? What happens when a plugin registers with a version?

**Comment by tianshapjq** [comment]
as the disordered incoming events of registration of plugin, we are not able to tell the newer plugin. such as the plugin with socketPaths in `./device/nvidia/gpu-1.9.1.sock` and `./device/nvidia/gpu-1.9.2.sock`, the registration of 1.9.1 may come in late after 1.9.2 if they all exist in the canonical path, which may happen when cluster admin forgets to delete the older plugin after upgrading.
So, if version of plugin itself is doable, we can ignore the registration of 1.9.1 even if coming in late.

**Comment by tianshapjq** [comment]
Imagine that if cluster admin deploys 1.9.2 long time after 1.9.1 deployed, and forgets to delete 1.9.1. Some time later kubelet restarts, and it would be possible to take 1.9.1 as the newest plugin. But this is not what the cluster admin wants of downgrade.

**Comment by RenaudWasTaken** [comment]
Hmm that sounds like an edge case we want to handle.

So to rephrase in a use case what you mentioned and merge with the conflicting se case:
- A cluster admin deploys a plugin 1.1 on his/her cluster
- Kubelet registers to plugin 1.1
- After some time he/she deploys plugin 1.2,
- Kubelet switches to plugin 1.2
- Kubelet restarts and kubelet gets event in reverse order (1.2 then 1.1)
- Kubelet registers plugin 1.2
- The cluster admin decides to downgrade to the version 1.0
- Kubelet switches to plugin 1.0

Would documenting and implementing a sensible and defined behavior in this case solve the issue?
For example what if we define the behavior at kubelet start to always process plugins in alphabetical order?

**Comment by tianshapjq** [comment]
yes, we can document to inform that registration would follow the alphabetical order, but  the plugin developer may not notice this, and the pugin name may act like `gpu1.1`, `gpu 1.2`, `gpu_1.3`, after several upgrading. That is, the developer may not strictly follow the alphabetical order in plugin names. So, why not separate the version from plugin name to make it looks more natural? And it would be helpful to cluster admin if there are some ways to find out the current version of plugin in use.
