### ISSUE TITLE
bash on mac os is too old so ﻿`hack/godep-save.sh` does not work

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes#65784]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
tried to update godeps on mac OSX
`hack/run-in-gopath.sh hack/godep-save.sh`

Eventual error out with 
```
+++ [0703 13:33:39] Updating LICENSES file
hack/update-godep-licenses.sh: line 152: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

osx bash is old and doesn't know what the `-A` flag is for declare.

**What you expected to happen**:
successfully finish running the scripts

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:

**Environment**:
- OS (e.g. from /etc/os-release): mac os 10.13.5

**Comment by cblecker** [comment]
What version of OSX and what version of bash are you using?

**Comment by thockin** [comment]
The licenses script is important but horrible.

**Comment by sttts** [comment]
`hack/godep-save.sh` worked last time I tried (some days ago, on 10.13.5.

**Comment by aojea** [comment]
Default bash version in OSX is pretty old, you can check your current version with 
```
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

The `declare -A` option is only available on version 4 or newer, so you have to install a new bash version `brew install bash`
The shebang line in the script `#!/usr/bin/env bash` will use the first bash in your PATH, which should be the new one.

**Comment by cblecker** [comment]
so this error is actually being thrown by `hack/update-godep-licenses.sh`. there's actually a version check in that script to ensure you're running bash >4 (https://github.com/kubernetes/kubernetes/commit/ae12275ec83247d3f21c4d146ec2e8e63a61a8be)

I'm curious though.. because you *have* declare, but just not the -A flag... but somehow you're passing the version check, which I know fails on bash 3 (just tested it). Seems weird.

**Comment by aojea** [comment]
@cblecker I think that the problem is that there is no exit inside the `if` sentence so it warns the user but it continues running.

**Comment by MHBauer** [comment]
huh, you're right. 

I do have bash 4. 
```
 bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
I think I have an incorrect root cause. I made assumptions. My apologies. I'll try and take another look at it next week.
