### ISSUE TITLE
Can't delete deployment, job doesn't complete

### ISSUE THREAD

**Issue by finndev** [kubernetes/kubernetes#65783]
**This a BUG REPORT 

/kind bug

**What happened**: Not possible to delete a deployment

**What you expected to happen**: Successfully delete the deployment

**How to reproduce it (as minimally and precisely as possible)**:

Have a deployment:

```
$ kubectl get deployments
my-deployment         2         0         0            0           1d
```

Trying to delete it:

```
kubectl delete deployment my-deployment
deployment.extensions "my-deployment" deleted
```

The command above takes years and doesn't complete. After exiting with CMD+C (left it 5+min running) the deployment is still there. It is impossible for me to delete it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: Dedicated server with OVH
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): Linux 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by liggitt** [comment]
/sig cli
/sig apps

What do you see if you fetch the deployment, replicaset, and pods from the API? Can you post the yaml output from the API for those objects?

**Comment by finndev** [comment]
A reboot of the master node fixed it
