### ISSUE TITLE
Add max retries when pod's restartPolicy is RestartPolicyOnFailure

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#65797]
If pod's `restartPolicy` is `RestartPolicyOnFailure`, its containers will be restarted constantly if they fail. However it might be meaningless if the failure is caused by system failure or some of user's program internal errors. It will fail even it retries a lot of time. At the same time, we could not recognize which cases to restart or not. I propose to add max retires for the policy `RestartPolicyOnFailure` to pod spec, pod will fail after max retries.

/kind feature
/sig apps

**Comment by hex108** [comment]
Finally I implemented it. I add `maxRetires` in PodSpec.

e.g.
```
$ cat pod_retry.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: "OnFailure"
  maxRetries: "3"                // Max retries is 3
  containers:
  - image: nginx:1.7.9
    name: test-pod
    command:
    - /bin/ls
    - hello
```
The above pod will retry 3 times, and failed finally. Without `maxRetries`, the pod will always retry, however it will not succeed and retries take a lot of time and resource. 

BTW: I implemented another version using annotation `kubernetes.io/maxRetriesForOnFailurePolicy`. Maybe we could use it for alpha feature?

```
$ cat pod_retry.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
      kubernetes.io/maxRetriesForOnFailurePolicy: "3"           // Max retries is 3
spec:
  restartPolicy: "OnFailure"
  maxRetries: "3"
  containers:
  - image: nginx:1.7.9
    name: test-pod
    command:
    - /bin/ls
    - hello
```

**Comment by filipre** [comment]
This issue shouldn't go stale before receiving at least some feedback. 
/remove-lifecycle stale

**Comment by filipre** [comment]
I'd be interested whether this feature would improve performance or reduce costs within the cluster. Sometimes we had services that restarted a thousand times before we noticed that there is something wrong.

**Comment by hex108** [comment]
hi @filipre, This feature just aims to solve problems similar to yours, the pod might fail because all kinds of errors, it is meaningless to always retry. This feature could reduce costs.

**Comment by filipre** [comment]
Thanks. Sounds like a good enough reason to leave it open then, doesn't it?
/remove-lifecycle rotten

**Comment by hex108** [comment]
Just sent a PR for it, implemented it using pod annotations.  cc @filipre

**Comment by srobinson** [comment]
What is the status of this feature/PR? This is something we are really interested in.

**Comment by lukeschlather** [comment]
I would really like this feature for deployments. Based on https://github.com/kubernetes/kubernetes/issues/24725 , this feature will not work with deployments?

Also, the way I would really like this to work is to have restartPolicy: never when deploying a new pod, but then allow have it be Always once the deployment is completed. (And if the deployment fails, the old pods from the previous successful deployment should obviously stick around with restartPolicy: always.)

This can be worked around by initially setting it to never, then running a patch to set it to always. However, this seems bad since it could leave the service with restartPolicy: never if something goes wrong.

**Comment by anirudhmurali** [comment]
+1 for this feature.

**Comment by zhengcanbin** [comment]
big +1 for this feature.

**Comment by PierreBeucher** [comment]
Was looking for such a feature and quite surprised to realize it did not exist yet.
+1 for this feature

**Comment by filipre** [comment]
I believe there is still the "Kubernetes Enhancement Proposals" missing, see [here](https://github.com/kubernetes/kubernetes/pull/79334#issuecomment-546733742)

**Comment by hex108** [comment]
Sorry all, I'll write a KEP for it.

**Comment by filipre** [comment]
/remove-lifecycle stale
Not on my watch

**Comment by utkarsh2811** [comment]
can anyone confirm if this feature has been implemented cuz I dont see any word regarding this on official documentation of kubernetes. If its not implemented then I request the owners to kindly look into implementing this.

**Comment by filipre** [comment]
I believe it is already implemented and all but the PR can't be merged because the KEP (?) is still missing?

**Comment by wenhuanglin** [comment]
can use `.spec.backoffLimit`
https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy

**Comment by techdragon** [comment]
@hex108 are you around to reopen this? 

Can we get some sort of admin/collaborator override and reopen this? 

This has an implementation and everything. Yet no one wrote up a KEP and were stuck writing stupid supervisor scripts for what should be built in functionality (and _already is_ in the case of K8S Jobs)

/reopen

**Comment by berlinsaint** [comment]
very need for this feature for k8s job. backofflimit is not useful for our case

**Comment by kerthcet** [comment]
> very need for this feature for k8s job. backofflimit is not useful for our case

could you please give a description about what's your scenario looks like?

**Comment by berlinsaint** [comment]
OK.
I am using the argoworkflow to manage our tf-operator tensorflow jobs.

In all reduce sync training  , if there are 2 workers training, no ps server.  the worker may failed beacuse of some reason:
such as these two types:
1、 K8s network problems sometime, or the little chance  DNS problem , with this type, we want worker pod can be restarted by Controller, now I should set pod policy to Always or Onfailure to implement this demand.
2、Some user side problems, such as code problem , or some reason not deal with the train data well, at this case, we don't want to restart pod beacuse it may be no use. So we want to set job podtemplate restar policy to Never. Please pay attention here, if set to be Never, when  the DNS problem suddenly occurs,  the job Failed and we want them restart exactly.

as you can see, they are conflict.

i know that  job support backofflimit and tfjob also support it too.
In tfjob, if i set them like this:
![image](https://user-images.githubusercontent.com/10629930/141448912-0b2e610d-5aae-4bbf-afe0-a38d51d7c17f.png)

when reaches backofflimit 3, the job marked be Failed. But !!!
i want to save error pod. so i set cleanPodplicy to None, i know that clean error pods ,running pods there can solve , bu we lose the error pod log, we don't want to other log system  to log the error info. 
so the controller doesn't clean a  restart policy pod , an it restarts infinitely and take up many resources..

if Max retries supported here , there are no problem

**Comment by berlinsaint** [comment]
> > very need for this feature for k8s job. backofflimit is not useful for our case
> 
> 
> 
> could you please give a description about what's your scenario looks like? 

Emmm.can you understand me？

**Comment by kerthcet** [comment]
Sorry for the delayed response, IIRC, if you set `cleanPodPolicy: None` and `backoffLimit: 3` at the same time, whatever the  result, pods are still there, and you can see the logs even if they are failed. 

What confused me is that you said `the controller doesn't clean a restart policy pod , an it restarts infinitely and take up many resources`, if we have configured the `backoffLimit`, why this job would restart infinitely. But yes, we will consume 3x resource allocations.

Besides, I also think it's reasonable to add this feature to workloads like deployment. But I think it was already achieved by backoffLimit in `Job`. WDYT? @berlinsaint

**Comment by berlinsaint** [comment]
> Sorry for the delayed response, IIRC, if you set `cleanPodPolicy: None` and `backoffLimit: 3` at the same time, whatever the result, pods are still there, and you can see the logs even if they are failed.
> 
> What confused me is that you said `the controller doesn't clean a restart policy pod , an it restarts infinitely and take up many resources`, if we have configured the `backoffLimit`, why this job would restart infinitely. But yes, we will consume 3x resource allocations.
> 
> Besides, I also think it's reasonable to add this feature to workloads like deployment. But I think it was already achieved by backoffLimit in `Job`. WDYT? @berlinsaint

i will take a look of Job backoffLimit implement. i have read the training-operator job implement , i find that the backoffLimit can't prevent the pod restart.

**Comment by berlinsaint** [comment]
> Sorry for the delayed response, IIRC, if you set `cleanPodPolicy: None` and `backoffLimit: 3` at the same time, whatever the result, pods are still there, and you can see the logs even if they are failed.
> 
> What confused me is that you said `the controller doesn't clean a restart policy pod , an it restarts infinitely and take up many resources`, if we have configured the `backoffLimit`, why this job would restart infinitely. But yes, we will consume 3x resource allocations.
> 
> Besides, I also think it's reasonable to add this feature to workloads like deployment. But I think it was already achieved by backoffLimit in `Job`. WDYT? @berlinsaint

as you can see, i just wan't we can preserve the error pods, meanwhile, don't consume resource allocations, just like a never restart pod..（now , the pod restart policy is immutable...）

**Comment by kerthcet** [comment]
I think it was a different feature you need comparing to the implementation of max retry times we discussed in this issue, right? 

If so, I'd like to open another issue and we can discuss about it there for I think it was a good improvement of resource ultilization, but I need to think about it seriously.

**Comment by zhx828** [comment]
@hex108 do you mind following up on this ticket? This feature seems wildly requested by the community and would be super useful for our project. Thanks in advance!

**Comment by aman-deep739** [comment]
Can this be re-opened please? 
and meanwhile can someone tell how to use backoffLimit with deployments?

**Comment by kerthcet** [comment]
> Can this be re-opened please? and meanwhile can someone tell how to use backoffLimit with deployments?

`backoffLimit` is limited to Job.

**Comment by kerthcet** [comment]
I'm glad to follow up with this feature, can someone tell me where are we now?

**Comment by hex108** [comment]
/reopen

I created a PR https://github.com/kubernetes/kubernetes/pull/79334 for it some time ago, but it needs a KEP. 

@kerthcet I would be grateful if you could follow up on it. And we could finish it togother if needed.

**Comment by kerthcet** [comment]
> /reopen
> 
> 
> 
> I created a PR https://github.com/kubernetes/kubernetes/pull/79334 for it some time ago, but it needs a KEP. 
> 
> 
> 
> @kerthcet I would be grateful if you could follow up on it. And we could finish it togother if needed.

I'm glad to work on a KEP then, thanks. Hope to finish it in release 1.25.

**Comment by kerthcet** [comment]
I'll write a KEP in this release, feel free to reopen this if you think necessary. @hex108

**Comment by hex108** [comment]
@kerthcet  Thanks. Reopen to track it.

**Comment by kerthcet** [comment]
> @hex108 do you mind following up on this ticket? This feature seems wildly requested by the community and would be super useful for our project. Thanks in advance!

Hi @zhx828 I have drafted a KEP here https://github.com/kubernetes/enhancements/pull/3339, but I was quite curious about your user stories, can you provide some more details? Thanks.

**Comment by kerthcet** [comment]
Hi folks who are interest with the feature, I have proposed a KEP here https://github.com/kubernetes/enhancements/pull/3339, don't be hesitate to give your advices/user stories, thanks all.

**Comment by TobiasJacob** [comment]
+1 for this feature!

**Comment by scbizu** [comment]
Should keep our discussion here or move to KEP ?

**Comment by kerthcet** [comment]
Let's move the discussion to the KEP plz.

**Comment by guettli** [comment]
For the first node of a new cluster we install the CNI, then CCM. 

We have seen that the ccm pod has somehow a broken network-setup. The container restarts again and again, but this does not help. I guess the pause-container has broken setup. A restart of the pod would help, but afaik there is no way (except a Job/Controller), so that the pod can terminate itself, so that the Deployment can start a new pod.

I hope this KEP will solve it: https://github.com/kubernetes/enhancements/pull/3339

**Comment by kerthcet** [comment]
Sorry, what do you mean ` A restart of the pod would help` , a recreate? Because the container is restarting. 

And usually CNI will add a taint to the node to prevent scheduling until network ready.

**Comment by guettli** [comment]
> Sorry, what do you mean ` A restart of the pod would help` , a recreate? Because the container is restarting.
> 
> And usually CNI will add a taint to the node to prevent scheduling until network ready.

We have it here from time to time with our ccm. A restart of the pod helps, but the continuous restart of the container does not help. I guess the ccm has a toleration for that taint. At the moment we restart the ccm pod by hand. We could create a work-around with a CronJob. But I would like to avoid that.
