### ISSUE TITLE
Need a "whoami" sub-command for kubectl

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#65798]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:

We might want to know informations about client's identity via "kubectl". Especially the name and the groups in `UserInfo`.😃

**What you expected to happen**:

```
$ kubectl whoami
USER           GROUPS        blah..
foo               bar,baz
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
@kubernetes/sig-cli-feature-requests 😃

**Comment by yue9944882** [comment]
Since that no one is interested to give it a try for now...
I'll raise a PR for this possibly

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/30784

/close

**Comment by ORESoftware** [comment]
duplicate of unresolved issue?

**Comment by ahmetb** [comment]
FWIW there's a kubectl plugin on [Krew](https://krew.dev) that does exactly this:

```
$ kubectl krew install whoami
$ kubectl whoami
foo@gmail.com
```

**Comment by Vaccano** [comment]
> FWIW there's a kubectl plugin on [Krew](https://krew.dev) that does exactly this:
> 
> ```
> $ kubectl krew install whoami
> $ kubectl whoami
> foo@gmail.com
> ```

Note that this particular Krew plugin does not work on a Windows machine.  It gives the following error:

> failed to install plugin "whoami": plugin "whoami" does not offer installation for this platform

**Comment by Bessonov** [comment]
@ahmetb Can you explain why did you down vote the post from @Vaccano further?

**Comment by infa-ddeore** [comment]
> FWIW there's a kubectl plugin on [Krew](https://krew.dev) that does exactly this:
> 
> ```
> $ kubectl krew install whoami
> $ kubectl whoami
> foo@gmail.com
> ```

this plugin now has `--all` flag to show groups info as well

```
$ k whoami --all
User:	someUser
Groups:
	system:masters
	system:authenticated
ARN:
	arn:aws:sts::123456789:assumed-role/someIAMrole/someUser
```

**Comment by ezk84** [comment]
> Note that this particular Krew plugin does not work on a Windows machine. It gives the following error:
> 
> > failed to install plugin "whoami": plugin "whoami" does not offer installation for this platform

You can install it manually if you have go installed:

```sh 
 go install github.com/rajatjindal/kubectl-whoami@latest
 cp $GOPATH/bin/kubectl-whoami.exe ~/.krew/bin/
 ```

Still, would be nice if Windows installation was made more easily available :) @rajatjindal
