### ISSUE TITLE
Truncating backend doesn't work with buffered backend for audit logging

### ISSUE THREAD

**Issue by loburm** [kubernetes/kubernetes#65819]
/kind bug

**What happened**:
Created cluster with truncating and buffered modes enabled for audit logging.

**What you expected to happen**:
Audit logs supposed to be written to the file or send via webhook.

**How to reproduce it (as minimally and precisely as possible)**:
Create clusters with next env variables set:
ENABLE_APISERVER_ADVANCED_AUDIT=true
ADVANCED_AUDIT_TRUNCATING_BACKEND=true
ADVANCED_AUDIT_LOG_MODE=batch
ADVANCED_AUDIT_BACKEND=log

**Environment**:
- Bug is present in all versions of kubernetes starting from 1.10

**Comment by loburm** [comment]
Most probably that's because we are not starting goroutine responsible for reading those events from the buffer:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/audit/truncate/truncate.go#L132

**Comment by CaoShuFeng** [comment]
We are trying to fix it here: https://github.com/kubernetes/kubernetes/pull/65823
