### ISSUE TITLE
controller-manager should acquire lock after checking configugration 

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#65816]
/kind feature
/sig cluster-lifecycle

**What happened**:

controller-manager acquires locks without checking configuration, which makes it not self-hosted friendly. Problem can happen, when some configuration options are incorrect, lets say certificate file doesn't match key, or file is missing completely, or credentials are not sufficient, controller-manager starts nevertheless and blocks on acquiring lock, without knowing that provided configuration data won't let it work when it gets the lock.

What can happen then, is that all previously configured controller-managers get killed and only new, incorrectly configured controller-managers are left, they succeed acquire lock just to fail immediately afterwards, but by that time there is no correctly configured controller-managers left so we end up with broken cluster.

**What you expected to happen**:

all input configuration is validated as much as possible, before attempting to acquire lock: files are loaded, informers stared, anything else to be sure that once lock is acquired, it wont fail on its face

**How to reproduce it (as minimally and precisely as possible)**:

In our case it was `--cluster-signing-key` file, which was missing, all new controllers successfully started and old controllers were killed, leaving cluster without any functional controller-manager

**Anything else we need to know?**:

controller-managers are running in a self-hosted environment and deployed using Deployment.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5

**Comment by liggitt** [comment]
I agree that static validation should be done before acquiring the lease

**Comment by redbaron** [comment]
> Doesn't the controller stop, release the lock, and another one start up after the leader lease period expires?

you mean leader periodically releases locks? maybe, but it can't prevent outage, because all correctly configured controller-managers going to be killed quite quickly.

> I agree that static validation should be done before acquiring the lease

maybe starting informers and stopping them? this would be most realistic check.

**Comment by liggitt** [comment]
>> I agree that static validation should be done before acquiring the lease
> 
> maybe starting informers and stopping them? this would be most realistic check.

I wouldn't recommend doing that, because of server and memory load. I meant validation of local file existence and parsing, valid config file, etc.

**Comment by redbaron** [comment]
Keep it open, still relevant

-------- Original Message --------

**Comment by tedyu** [comment]
Currently controllermanager registers controller starters, e.g.
```
	controllers["serviceaccount"] = startServiceAccountController
```
Each starter may return error:
```
func NewServiceAccountsController(saInformer coreinformers.ServiceAccountInformer, nsInformer coreinformers.NamespaceInformer, cl clientset.Interface, options ServiceAccountsControllerOptions) (*ServiceAccountsController, error) {
```
One solution along the lines of @liggitt comment is to extract the condition checking from each starter into separate (checker) func.
This would give us NewServiceAccountsChecker, etc.
In parallel to controllers map, we can have controllerCheckers map:
```
	controllerCheckers["serviceaccount"] = NewServiceAccountsChecker
```
Before starting controllers, we run through checkers and fail early if any checker returns error.
