### ISSUE TITLE
NO't get nodes 

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#65843]
root@k8smaster:~# kubectl get csr
NAME                                                   AGE       REQUESTOR                 CONDITION
node-csr-00NHp-Cdq0qUqXGYnIu81KB39_a56-llQKS5aGn_ecU   3h        system:bootstrap:zhqvxa   Pending
node-csr-0k4pYdZvY1zzt2OeL2wqqzeGKnVyymqMoSBh1kk2_as   18h       system:bootstrap:ut2yb5   Approved
node-csr-1Lei-DbgwPkdpefHR3Wq7viQOp7UYnlxYEwN4-L1h4E   11h       system:bootstrap:2fjd18   Pending
node-csr-1vJXD_dG_zz-FbLw6kSKfGyRmKgBR-SVQPrQqh2GUYk   15h       system:bootstrap:2fjd18   Pending
node-csr-390Mnv_kB3UmA1nFzG39U-Af_VIPB_fYM4rwNik00f8   10h       system:bootstrap:yinyv1   Pending
node-csr-5I_64E13uWCdCTvv1RnRxrfNyMa1zgqB-TV1_F02GcU   51m       system:bootstrap:cggb8o   Pending
node-csr-5_qpNQP8nifREkdMYpZmKYofn1u7bNu0fX3uaDzeG7Q   17h       system:bootstrap:2fjd18   Pending
node-csr-6Y9G2PFcV5jfdZJk21gN0-kA-tzdAK465QMBgQEV1rg   4h        system:bootstrap:cggb8o   Pending
node-csr-7DNP6sa52NKgG3mCmKlqwzuOeAenqVc4iytsiFzKz48   13h       system:bootstrap:yinyv1   Pending
node-csr-7YDX9_qXoHCsJ8Eo2gP--lXqEMVf62P_Lpn_ewo_u68   2h        system:bootstrap:cggb8o   Pending
node-csr-7egsNH9eh_0z7mzsiY_VjU-cAcqO95JyKt9fq5ZoFIU   10h       system:bootstrap:ut2yb5   Pending
node-csr-7lDOLwGdLZAAnYJXXoCHW4HEasISTnMlT2BwOeBCiD0   1h        system:bootstrap:cggb8o   Pending
node-csr-7uagdDDBw9nL_RSHq6UsTxrNAd_U-P_5vAf1DNMeiRg   4h        system:bootstrap:cggb8o   Pending
node-csr-8P5YOZjXGp8QoQN8NeU_7baxaMbphkz6TDJpJT0MDFw   18h       system:bootstrap:2fjd18   Approved
node-csr-9zpit4ifCE9ESU8NxnfX7mqiB7JAxBgVQvKjOP1Qy9Y   5h        system:bootstrap:zhqvxa   Pending
node-csr-ByLe0mxKkb_dGWFYAJ_8DAB6FwT40pvWJ9gXXCPeIcc   18h       system:bootstrap:yinyv1   Approved

root@k8smaster:~# kubectl get nodes
No resources found.

kubelet日志
kubelet log
I0705 13:07:12.080867   32911 feature_gate.go:226] feature gates: &{{} map[]}
W0705 13:07:12.102625   32911 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
I0705 13:07:12.111736   32911 server.go:376] Version: v1.10.4
I0705 13:07:12.111845   32911 feature_gate.go:226] feature gates: &{{} map[]}
I0705 13:07:12.112096   32911 plugins.go:89] No cloud provider specified.
W0705 13:07:12.112157   32911 server.go:517] standalone mode, no API client
W0705 13:07:12.145171   32911 server.go:433] No api server defined - no events will be sent to API server.
I0705 13:07:12.145208   32911 server.go:614] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
I0705 13:07:12.145601   32911 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
I0705 13:07:12.145634   32911 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true}
I0705 13:07:12.145743   32911 container_manager_linux.go:266] Creating device plugin manager: true
I0705 13:07:12.145765   32911 state_mem.go:36] [cpumanager] initializing new in-memory state store
I0705 13:07:12.145913   32911 state_mem.go:84] [cpumanager] updated default cpuset: ""
I0705 13:07:12.145925   32911 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
W0705 13:07:12.152909   32911 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0705 13:07:12.152970   32911 kubelet.go:558] Hairpin mode set to "hairpin-veth"
I0705 13:07:12.154838   32911 client.go:75] Connecting to docker on unix:///var/run/docker.sock
I0705 13:07:12.154883   32911 client.go:104] Start docker client with request timeout=2m0s
W0705 13:07:12.157330   32911 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
I0705 13:07:12.164090   32911 docker_service.go:244] Docker cri networking managed by kubernetes.io/no-op
I0705 13:07:12.179636   32911 docker_service.go:249] Docker Info: &{ID:WWRX:YTKC:EY3P:KOD5:GIIQ:ZIEV:XOJN:CQK6:UITT:ZFZI:Q756:2RM3 Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog]} MemoryLimit:true SwapLimit:false KernelMemory:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:20 OomKillDisable:true NGoroutines:33 SystemTime:2018-07-05T13:07:12.16705348+08:00 LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:4.4.0-116-generic OperatingSystem:Ubuntu 16.04.4 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc420aefe30 NCPU:4 MemTotal:4124872704 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:k8smaster Labels:[] ExperimentalBuild:false ServerVersion:18.03.1-ce ClusterStore: ClusterAdvertise: Runtimes:map[runc:{Path:docker-runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:773c489c9c1b21a6d78b5c538cd395416ec50f88 Expected:773c489c9c1b21a6d78b5c538cd395416ec50f88} RuncCommit:{ID:4fc53a81fb7c994640722ac585fa9ca548971871 Expected:4fc53a81fb7c994640722ac585fa9ca548971871} InitCommit:{ID:949e6fa Expected:949e6fa} SecurityOptions:[name=apparmor name=seccomp,profile=default]}
I0705 13:07:12.179744   32911 docker_service.go:262] Setting cgroupDriver to cgroupfs
I0705 13:07:12.200845   32911 remote_runtime.go:43] Connecting to runtime service unix:///var/run/dockershim.sock
I0705 13:07:12.230456   32911 kuberuntime_manager.go:186] Container runtime docker initialized, version: 18.03.1-ce, apiVersion: 1.37.0
I0705 13:07:12.231037   32911 csi_plugin.go:63] kubernetes.io/csi: plugin initializing...
I0705 13:07:12.251054   32911 server.go:129] Starting to listen on 0.0.0.0:10250
E0705 13:07:12.240275   32911 kubelet.go:1282] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data for container /
I0705 13:07:12.255069   32911 server.go:945] Started kubelet
W0705 13:07:12.255199   32911 kubelet.go:1375] No api server defined - no node status update will be sent.
I0705 13:07:12.263638   32911 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0705 13:07:12.265482   32911 status_manager.go:136] Kubernetes client is nil, not starting status manager.
I0705 13:07:12.266610   32911 volume_manager.go:247] Starting Kubelet Volume Manager
I0705 13:07:12.269444   32911 desired_state_of_world_populator.go:129] Desired state populator starts to run
I0705 13:07:12.269742   32911 kubelet.go:1782] Starting kubelet main sync loop.
I0705 13:07:12.269821   32911 kubelet.go:1799] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
I0705 13:07:12.280264   32911 server.go:299] Adding debug handlers to kubelet server.
I0705 13:07:12.370298   32911 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
I0705 13:07:12.468988   32911 reconciler.go:154] Reconciler: start to sync state
I0705 13:07:12.570927   32911 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
I0705 13:07:12.971887   32911 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
I0705 13:07:13.772840   32911 kubelet.go:1799] skipping pod synchronization - [container runtime is down]
I0705 13:07:14.576798   32911 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
I0705 13:07:14.582630   32911 cpu_manager.go:155] [cpumanager] starting with none policy
I0705 13:07:14.582662   32911 cpu_manager.go:156] [cpumanager] reconciling every 10s
I0705 13:07:14.582671   32911 policy_none.go:42] [cpumanager] none policy: Start
Starting Device Plugin manager
I0705 13:07:14.583631   32911 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
I0705 13:07:24.643300   32911 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
I0705 13:07:34.704633   32911 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach

环境
OS：ubuntu 16.04
kubernetes：v1.10.4

**Comment by jhorwit2** [comment]
/close

@gitplyx Please recreate this issue with the required information requested in the template.
