### ISSUE TITLE
Cant‘t up controller-manager

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#65842]
报错日志
root@k8smaster:~# kube-controller-manager log
W0705 12:38:45.362348   27430 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0705 12:38:45.362409   27430 client_config.go:538] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
invalid configuration: no configuration has been provided

root@k8smaster:~# kube-controller-manager log
W0705 12:38:45.362348   27430 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0705 12:38:45.362409   27430 client_config.go:538] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
invalid configuration: no configuration has been provided
root@k8smaster:~# journalctl -u kube-controller-manager
-- Logs begin at Thu 2018-07-05 12:28:11 CST, end at Thu 2018-07-05 12:40:01 CST. --
Jul 05 12:28:13 k8smaster systemd[1]: kube-controller-manager.service: Service hold-off time over, scheduling restart.
Jul 05 12:28:13 k8smaster systemd[1]: Stopped Kubernetes Controller Manager.
Jul 05 12:28:13 k8smaster systemd[1]: Started Kubernetes Controller Manager.
Jul 05 12:28:13 k8smaster kube-controller-manager[25447]: I0705 12:28:13.705873   25447 feature_gate.go:190] feature gates: map[RotateKubeletServerCertificate:true]
Jul 05 12:28:13 k8smaster kube-controller-manager[25447]: I0705 12:28:13.706079   25447 flags.go:27] FLAG: --address="0.0.0.0"
Jul 05 12:28:13 k8smaster systemd[1]: kube-controller-manager.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 12:28:13 k8smaster systemd[1]: kube-controller-manager.service: Unit entered failed state.
Jul 05 12:28:13 k8smaster systemd[1]: kube-controller-manager.service: Failed with result 'exit-code'.
Jul 05 12:28:18 k8smaster systemd[1]: kube-controller-manager.service: Service hold-off time over, scheduling restart.
Jul 05 12:28:18 k8smaster systemd[1]: Stopped Kubernetes Controller Manager

配置文件
[Unit]
Description=Kubernetes Controller Manager
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
[Service]
ExecStart=/opt/k8s/bin/kube-controller-manager \
--port=0 \
--secure-port=10252 \
--bind-address=127.0.0.1 \
--kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
--service-cluster-ip-range=10.254.0.0/16 \
--cluster-name=kubernetes \
--cluster-signing-cert-file=/etc/kubernetes/cert/ca.pem \
--cluster-signing-key-file=/etc/kubernetes/cert/ca-key.pem \
--experimental-cluster-signing-duration=8760h \
--root-ca-file=/etc/kubernetes/cert/ca.pem \
--service-account-private-key-file=/etc/kubernetes/cert/ca-key.pem \
--leader-elect=true \
--feature-gates=RotateKubeletServerCertificate=true \
--controllers=*,bootstrapsigner,tokencleaner \
--horizontal-pod-autoscaler-use-rest-clients=true \
--horizontal-pod-autoscaler-sync-period=10s \
--tls-cert-file=/etc/kubernetes/cert/kube-controller-manager.pem \
--tls-private-key-file=/etc/kubernetes/cert/kube-controller-manager-key.pem \
--use-service-account-credentials=true \
--v=2
Restart=on
Restart=on-failure
RestartSec=5
User=k8s
[Install]
WantedBy=multi-user.target

环境：
OS：ubantu 16.04 
kubernets：v1.10.4

controller-manager 为集群部署 ，三台机器全部报一样错误，无法启动

**Comment by jhorwit2** [comment]
/close 

@gitplyx Please recreate this issue and fill out the information requested in the template.
