### ISSUE TITLE
Pod pending for erver

### ISSUE THREAD

**Issue by XishengCai** [kubernetes/kubernetes#65855]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
When Pod pending , I delete all pods, but all pods still pending when I recreate only one pod. My all components run by docker container except kubelet. The log of kube-controller-manage report the pods that wanted gc cant't found.
**What you expected to happen**:
I hope that after pod pending, I cant create  the pod properly when I free up resources by deleting some of the pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos 7.4
- Kernel (e.g. `uname -a`):3.10.0-693.el7.x86_64
- Install tools: all up by docker except kubelet
- Others:

**Comment by krmayankk** [comment]
This bug doesnt have sufficient information. Can you do `kubectl describe <podname> -n <namespace>` and paste the output here

**Comment by dims** [comment]
/close

please reopen with requested info
