### ISSUE TITLE
can‘t create kubelet-apis

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#65851]
today i have a truble
configure ：
root@k8smaster:~/kubernetes/api-server# kubectl create clusterrolebinding kube-apiserver:kubelet-apis --clusterrole=system:kubelet-api-admin --user kubernetes
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

**Comment by liggitt** [comment]
That is a general connectivity issue between kubectl and your apiserver. Verify the kubeconfig file you are using is correct. You can view your current connection information with `kubectl config view`

/close
