### ISSUE TITLE
kuberentes pod get requests before the pod can resolve the other pods dns in the same cluster

### ISSUE THREAD

**Issue by softputer** [kubernetes/kubernetes#65853]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
When pod A is started, new requests to pod a is already accepted by pod A, but when   pod A wants to access pod B's service, I get the error message that pod A cannot resolve service B, hostname cannot be resolved.But after a while, pod A can resovle pod B's service.But pod A has lost many requests already.
**What you expected to happen**:
When a pod can accept request, then it should resolve other dns.
**How to reproduce it (as minimally and precisely as possible)**:
When u have 2 replicas already, then make it 3, but during this time ,u have to keep sending requests to the service, make sure the pods wants to access other services by service name , u will see the error message about hostname cannot be resovled.

**Anything else we need to know?**:

**Environment**:
- 1.7.5 (use `kubectl version`):
- Cloud Provider
- ubuntu
- 16.04

**Comment by krmayankk** [comment]
@softputer this needs a slightly more detailed description. I believe you can configure each pod behind a service and if the pod is not ready for whatever reason, it wont get added as an endpoint to its services and hence wont loose requests
