### ISSUE TITLE
external cloud-controller-manager listens insecurely by default

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#65869]
/kind bug

**What happened**:
When building a cloud-controller-manager using the pro-forma manifests, the cloud-controller ends up listening insecurely on port 10253 by default

**What you expected to happen**:

The documentation should explain what the cloud-controller-manager is doing on that port, and how to secure it - assuming it is required. 

I'd expect it wouldn't listen insecurely by default on all addresses 

**How to reproduce it (as minimally and precisely as possible)**:

All the manifests for the external cloud controllers detailed here 

https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

do nothing with --port or --secure-port

The one I'm writing

https://github.com/brightbox/brightbox-cloud-controller-manager

using the same sort of manifest ends up listening insecurely on 0.0.0.0 on port 10253 unless I use '--port 0' to stop it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-rc.1", GitCommit:"8745ea56e3f1f3ad20050c1762eb6ba6f7786675", GitTreeState:"clean", BuildDate:"2018-06-21T00:01:04Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-rc.1", GitCommit:"8745ea56e3f1f3ad20050c1762eb6ba6f7786675", GitTreeState:"clean", BuildDate:"2018-06-20T23:52:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.03 LTS
- Kernel (e.g. `uname -a`):
Linux srv-yywho 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Kubeadm/terraform
- Others:

**Comment by dims** [comment]
the behavior is the same with `kube-controller-manager` with port 10252. 

```
dims@bigbox:~$ sudo lsof -i :10252
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
hyperkube 16363 root    3u  IPv6 44097327      0t0  TCP *:10252 (LISTEN)
dims@bigbox:~$ cat /proc/16363/cmdline | tr \\0 ' '
/home/dims/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/hyperkube controller-manager --v=10 --vmodule= --service-account-private-key-file=/tmp/kube-serviceaccount.key --root-ca-file=/var/run/kubernetes/server-ca.crt --cluster-signing-cert-file=/var/run/kubernetes/server-ca.crt --cluster-signing-key-file=/var/run/kubernetes/server-ca.key --enable-hostpath-provisioner=true --pvclaimbinder-sync-period=15s --feature-gates=AllAlpha=false --cloud-provider= --cloud-config= --kubeconfig /var/run/kubernetes/controller.kubeconfig --use-service-account-credentials --controllers=* --master=https://localhost:6443
```

`curl -kvs http://localhost:10252/metrics` and `curl -kvs http://localhost:10252/healthz` are served on that port. so its probably the same with cloud-controller-manager.

**Comment by stewart-yu** [comment]
Don't worry, we will discard in securely ASAP , and using in securely port both in `kube-conreoller-manager` and `cloud-controller-manager`。 See [PR](https://github.com/kubernetes/kubernetes/pull/64149)
/cc @sttts

**Comment by sttts** [comment]
As @stewart-yu is writing, this is actively being worked on. We want secure ports with authn/authz for 1.12.

**Comment by andrewsykim** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/67069

**Comment by sttts** [comment]
We have not closed the insecure port yet (only deprecated it). I guess this means this issue must be reopenend.
