### ISSUE TITLE
Slightly reword "no registry" message from build

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#6587]
```
$ osc build-logs ruby-sample-build-3
2015-04-08T18:43:55.549604454Z F0408 18:43:55.548918       1 builder.go:46] Cannot determine an output image reference. Make sure a registry service is running.
```

is because no docker registry is installed.  I suspect two user types are going to hit this - brand new ops user (who may not know what a service is, or what an output image reference is) or an existing user due to some weird temporary ops bug (and can't do anything about it).  Would recommend the message be (similar to):

    No Docker registry has been configured in OpenShift, so the build cannot complete.

**Comment by roberthbailey** [comment]
@smarterclayton Is there something we should do here?

**Comment by smarterclayton** [comment]
Sigh, wrong repo. Closing.
