### ISSUE TITLE
multiple authentication-token-webhook's

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#65874]
/kind feature

**What happened**:
There is only one --authentication-token-webhook-config-file option so you can only have one authentication backend for token based auth.

**What you expected to happen**:

I would like to be able to specify a "default", and other named webhooks <name>. The user's kubeconfig file can specify the name and the name will be passed along with the token during token validation. kube-apiserver will route the token to the specified webhook.

This would allow, for example, a different authentication plugin to be used between gui and cli. Or cli on trusted clusters can use a different auth mechanism/plugin then untrusted desktop clis.

**Comment by liggitt** [comment]
One consideration is that this would currently expose token credentials to multiple remote webhooks (c.f. https://github.com/kubernetes/kubernetes/issues/12316)

**Comment by kfox1111** [comment]
+1. but could also be part of the solution of not passing tokens to backends that they aren't intended for as there would be more info on where to route the token.
