### ISSUE TITLE
Figure out what to do about go-bindata .

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#65871]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT 
**What happened**:

Source bug, not functional at all.   Gobindata is now 'gone'.

**What you expected to happen**:
 
Gobindata would be around forever.
 

We use gobindata in e2e (maybe other places) for embedding kubberentes components.  If we *ever* update it, it might be from a 3rd party GitHub user that we dont trust/know (see https://twitter.com/francesc/status/961249107020001280?lang=en): 

```
Francesc on Twitter
twitter.com
 📢 #GOLANG WARNINGgo-bindata creator deleted their @github account and someone else created a new account with the same name.There's no guarantees that the new user has good intentions, so if you're using the repository make sure you verify it first!https://t.co/bOhPYRnFvV— Francesc (@francesc)…
``` 

So, lets either internalize the functionality, or maybe even make a cncf/ fork of it since its a critical place where vulnerabilities can be injected if we dont trust it.

**Comment by jayunit100** [comment]
cc @kubernetes/sig-testing-misc

**Comment by dims** [comment]
cc @cblecker @thockin

**Comment by BenTheElder** [comment]
xref: https://github.com/jteeuwen/go-bindata/issues/5

**Comment by BenTheElder** [comment]
Specifically per https://github.com/jteeuwen/go-bindata/issues/5#issuecomment-370294693 go-bindata should now be [archived](https://help.github.com/articles/archiving-a-github-repository/) (readonly on GitHub), if we want a maintained copy we will definitely need to go elsewhere.

FWIW [thockin already commented that we vendor this](https://twitter.com/thockin/status/961313949491712001) in the meantime :-)

[Docker just switched tools](https://github.com/docker/cli/pull/874) to [mjibson/esc](https://github.com/mjibson/esc). Maybe we can pick something actively maintained and switch as well?

**Comment by cblecker** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/59491 up, but we didn't really take any action. It's vendored, so it's not really urgent. We can either migrate to something else, or we could fork it into `third_party/`.

/shrug

**Comment by liggitt** [comment]
Agree this is a duplicate of https://github.com/kubernetes/kubernetes/issues/59491

/close
