### ISSUE TITLE
Pods stuck in Terminating status (UnmountVolume.TearDown failed)

### ISSUE THREAD

**Issue by rgembalik** [kubernetes/kubernetes#65879]
/kind bug

**What happened**:
Many pods after deleting will stick infinitely in Terminating status, due to inability to unmount volumes (`UnmountVolume.TearDown failed`; mostly default secrets, but occasionally it would also include openebs volumes). It may be connected with `/var/lib/kubelet` symlinked into `/opt/kubelet`, but thats a guess based on hints in #65110. Unlike in the mentioned issue, my problem persisted after updating to 1.10.5.

**What you expected to happen**:
Pod gets removed and secret unmounted.

**How to reproduce it (as minimally and precisely as possible)**:
Remove some pods.

**Anything else we need to know?**:

Symptoms so far:
* `mount`, `cat /proc/mount` and `/etc/mtab` 
   all lists the volume as mounted - sometimes even multiple times! The entry for sample problem is:
  `tmpfs on /path-to-kubelet/pods/$POD_UID/volumes/kubernetes.io~secret/default-token-xxxxx  type tmpfs (rw,relatime)`
* `umount` on directory listed in `/proc/mount` 
   replies `umount: /path-to-kubelet/pods/$POD_UID/volumes/kubernetes.io~secret/default-token-xxxxx: not mounted`
* `rm -rf` 
   tells me that `Device or resource busy`
* `lsof | grep $POD_UID` 
   doesn't show any process using this path
* `docker ps -qa | xargs docker container inspect -f '{{ .Name }} {{ json .Mounts }}' | grep $POD_UID` 
   doesn't show any container using old pod path

Other stuff:
* Kubernetes 1.9.2, (updated to 1.10.5; issue persisted)
* Ubuntu 16.04.4 LTS
* uname -a: Linux 4.4.0-121-generic
* Docker 17.03.1-ce (updated to 17.03.2-ce; issue persisted)

**Comment by barnsnake351** [comment]
This issue is affecting our installations as well. Setting the kubelet flag `--root-dir`, as mentioned in #65110, to the value referenced by our symlink from /var/lib/kublet seems to resolve the issue.

We noticed this specifically on pods which use volume subPath mounts. The source was either a configMap or secret in most cases

Example recurring error in kubelet logs manifests as a `device or resource busy`
```
estedpendingoperations.go:267] Operation for "\"kubernetes.io/configmap/3a92a5bf-8422-11e8-830b-066c762652cc-configmap-XXXXX\" (\"3a92a5bf-8422-11e8-830b-066c762652cc\")" failed. No retries permitted until 2018-07-13 16:03:57.636104303 +0000 UTC m=+67.631270721 (durationBeforeRetry 32s). Error: "error cleaning subPath mounts for volume \"configmap-XXXXXX\" (UniqueName: \"kubernetes.io/configmap/3a92a5bf-8422-11e8-830b-066c762652cc-configmap-XXXXXX\") pod \"3a92a5bf-8422-11e8-830b-066c762652cc\" (UID: \"3a92a5bf-8422-11e8-830b-066c762652cc\") : error deleting /var/lib/kubelet/pods/3a92a5bf-8422-11e8-830b-066c762652cc/volume-subpaths/configmap-XXXXX/xxxxx/1: remove /var/lib/kubelet/pods/3a92a5bf-8422-11e8-830b-066c762652cc/volume-subpaths/configmap-XXXXX/xxxxxx/1: device or resource busy"
```

After changing the root-dir of kubelet, these entries appears once and then the volume is removed and the pod completes termination

Versions:
* Kubernetes 1.10.5
* Ubuntu 16.04.4 LTS
* uname -a: 4.4.0-1057-aws
* docker: 1.13.1

**Comment by chrischdi** [comment]
Hi there,
we encounter the same Problem. Side note: we are running the kubelet itself as docker container.

Versions:
* Kubernetes: 1.9.9
* CoreOS: 1745.7.0
* uname -r: 4.14.48-coreos-r2
* docker 18.03.1-ce

**Comment by rgembalik** [comment]
@chrischdi While it's not a perfect solution and requires a bit of sweating, I'd recommend you try upgrading to 1.10.5 at least and changing the `--root-dir` option of kubelet (see @barnsnake351 comment). While it's not a solution per se, it did reduce the scale of the problem greatly for us. 
As a side note: Another thing that helped during debugging was increasing `max_user_watches`  on the host systems, as the default `8192` caused massive choking whenever we had to restart kubelet, docker and/or host machine.

**Comment by chrischdi** [comment]
Hi @rgembalik we currently will stick with 1.9.9 but will update hopefully soon to a newer version.

I now have a try on using other mount options for the kubelet container/its `/var/lib/kubelet` mount:
```
diff --git a/kubelet.service b/kubelet.service
index 6b40141..03b2bfb 100644
--- a/kubelet.service
+++ b/kubelet.service
@@ -6,8 +6,6 @@ After=docker.service network-online.target
 
 [Service]
 ExecStartPre=/bin/mkdir -p /var/lib/kubelet
-ExecStartPre=/bin/mount --bind /var/lib/kubelet /var/lib/kubelet
-ExecStartPre=/bin/mount --make-shared /var/lib/kubelet
 ExecStart=/usr/bin/docker run \
         --net=host \
         --pid=host \
@@ -16,7 +14,7 @@ ExecStart=/usr/bin/docker run \
         -v /sys:/sys:ro \
         -v /var/run:/var/run:rw \
         -v /var/lib/docker/:/var/lib/docker:rw \
-        -v /var/lib/kubelet/:/var/lib/kubelet:shared \
+        --mount type=bind,src="/var/lib/kubelet/",dst="/var/lib/kubelet",bind-propagation=shared \
         -v /var/log:/var/log:shared \
         -v /srv/kubernetes:/srv/kubernetes:ro \
         -v /etc/kubernetes:/etc/kubernetes:ro \
```
Example file from: https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/vanilla/kubelet.service (hint we do not use exactly this file but the changed options are the same.

**Comment by alena1108** [comment]
We are observing this problem on k8s 1.11.3

**Comment by patelrit** [comment]
We are seeing the same problem with k8s v1.11.5 for certain pods. Kubelet runs in a container.
OS: Ubuntu 16.04.5 LTS
Docker Version: 17.06.0-ce

**Comment by domq** [comment]
Downgrading Kubelet from v1.13.0 to v1.11.0 today, solved the issue for us — Note that the cluster was in an inhomogenous state (a mix of Kube apiservers of both versions), which is not necessarily a good thing.

**Comment by PierrePIRONIN** [comment]
Hi guys, same issue here. Did you find a solution ?

**Comment by chrischdi** [comment]
We currently have it working on v1.9 to v1.12 using the following parameters:

```
ExecStart=/usr/bin/docker run --rm --name %n \
    --net=host --pid=host --privileged \
    -v /:/rootfs:ro \
    -v /etc/kubernetes:/etc/kubernetes:ro \
    -v /etc/kubernetes/ssl/kubelet:/etc/kubernetes/ssl/kubelet \
    -v /etc/cni:/etc/cni \
    -v /opt/cni/bin:/opt/cni/host-bin \
    -v /var/lib/cni:/var/lib/cni \
    --mount type=bind,src="/var/lib/kubelet/",dst="/var/lib/kubelet",bind-propagation=shared \
    -v /var/run:/var/run:rw \
    -v /dev:/dev \
    -v /sys:/sys:ro \
    -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
    -v /var/lib/docker/:/var/lib/docker:rw \
    -v /var/log:/var/log:shared \
    -v /etc/cloud.conf:/etc/cloud.conf:ro \
    -v /etc/ssl/certs/:/etc/ssl/certs/:ro \
    {{ $registry }}{{ $image }} \
...
```

**Comment by rgembalik** [comment]
@PierrePIRONIN Unfortunately I didn't. We had some updates, in the meantime, now sitting on kubernetes `1.11.2` and Docker `18.x`, so for me, the issue morphed a bit, as kubelet still complains about not being able to unmount the path, but I can manually umount those paths. The issue is still annoying as there are regularly config maps, that needs manual `umount`.

It might be closely connected to the other issue I reported (#75401), but I don't have enough under-the-hood knowledge, to really tell how can it be connected apart from touching the same subject (mount points for configmaps).

**Comment by PierrePIRONIN** [comment]
@rgembalik Ouch :( 

The same situation here but with Kubernetes 1.11.5 and Docker 17.03. We will try to update asap to Kubernetes 1.12.7 and Docker 18.06 (with @chrischdi configuration).

Do you plan to upgrade to Kubernetes 1.12 on your hand ?

**Comment by rgembalik** [comment]
@PierrePIRONIN We do, but it's more of a "We need to upgrade" sentence, rather than "We'll upgrade on <insert date here>". Mostly because upgrade requires node restart etc and to plan it is to schedule potentially a few hours of downtime, which we can rarely afford ;) But I think if we will, it'll jump through 1.12 and 1.13 to 1.14.

**Comment by PierrePIRONIN** [comment]
@rgembalik Yes I understand, same here. The problem occurred on our production cluster so we need to upgrade smoothly :)

**Comment by strowi** [comment]
We're running into the same issue running 1.13.5, would be interested in that hotfix command..
regards,
strowi

**Comment by rgembalik** [comment]
@strowi So far I am using two detection commands:
* ` mount | sort | uniq -c | sort -n` - to see which mounts are multiplied, and how many times.
* `tail -n 1000 /var/log/syslog -f | grep busy` to see which mount points require manual `umount`
I think both can be written in a prettier way. I don't have hotfixing cronjobs installed yet.
