### ISSUE TITLE
Make cluster name available in Downward API

### ISSUE THREAD

**Issue by ashi009** [kubernetes/kubernetes#65885]
/kind feature

**What happened**:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api doesn't support `metadata.cluster` or similar 

**What you expected to happen**:
Expose cluster info through downward API

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

As documented on `ObjectMeta.clusterName`, "This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request." But this info is very important on a multi cluster setup.

Also, despite the fact that GKE may access this info through metadata service, this info should come from the k8s, instead of externally.

**Comment by liggitt** [comment]
metadata.cluster is actively prevented from being populated:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L100-L101

I don't think it should be added to the downwardAPI until that changes

**Comment by ashi009** [comment]
@liggitt I can't tell if this is being actively prevented. It seems a feature got disabled after being committed to the codebase as the native multi-cluster feature is not yet work. 

As both 858e515f85dd6d8ba1cebaf82e882326dadbc118 and 7be20b0daca8755ddef9c4d9ce9090e9c50a53c8 don't have any description, could you point me the discussion on why the cluster name is ignored after being ignored?

**Comment by liggitt** [comment]
> @liggitt I can't tell if this is being actively prevented

the field was added to ObjectMeta with no intention for it to apply to pods (original PR was in https://github.com/kubernetes/kubernetes/pull/28921, and was only targeted at higher-level objects that could exist across clusters in a multi-cluster setup). It doesn't make sense to include such a field in the downward API if the API server responsible for the objects that populate the downward API (the kube-apiserver) prevents it from being set.

**Comment by ashi009** [comment]
>It doesn't make sense to include such a field in the downward API if the API server responsible for the objects that populate the downward API (the kube-apiserver) prevents it from being set.

It probably not makes sense to include it at this point, but the cluster name should be included in longterm. The cluster name can be used in at least the following ways:

- log entry labeling
- monitoring time series labeling
- cross-cluster service discovery

**Comment by redbaron** [comment]
I like current status quo,  that "cluster" concept  is not leaking into cluster itself, but stays within some levels above , like federation.
