### ISSUE TITLE
Deleting a Job do not cleanup the pods it created.

### ISSUE THREAD

**Issue by luzhzhsoft** [kubernetes/kubernetes#65889]
/kind bug

What happened:
when i delete a job ,the pods which created by job do not be deleted. 

What you expected to happen:
Deleting a Job will cleanup the pods it created.

How to reproduce it (as minimally and precisely as possible):
create a job which  have initcontainers and pod restart policy set OnFailure。use restapi to delete job

Environment:
Kubernetes version:v1.6.7
OS: center os

**Comment by liggitt** [comment]
is this still accurate on more recent versions? this should be something garbage collection is taking care of

**Comment by luzhzhsoft** [comment]
@liggitt  only in my old version. in the latest version ,it seems to work fine
