### ISSUE TITLE
/var/lib/kubelet/config.yaml is missing while installing

### ISSUE THREAD

**Issue by wssiqi** [kubernetes/kubernetes#65888]
/kind bug

I am trying to install kubernetes on Centos7.

After finished the below step:
https://kubernetes.io/docs/tasks/tools/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

i found kubelet is not started.
Below is the logs.
<pre>
Jul 06 14:56:04 localhost.localdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Jul 06 14:56:04 localhost.localdomain systemd[1]: Starting kubelet: The Kubernetes Node Agent...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.
Jul 06 14:56:05 localhost.localdomain kubelet[2478]: I0706 14:56:05.038689    2478 feature_gate.go:230] feature gates: &{map[]}
Jul 06 14:56:05 localhost.localdomain kubelet[2478]: F0706 14:56:05.038955    2478 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var
Jul 06 14:56:05 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jul 06 14:56:05 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
Jul 06 14:56:05 localhost.localdomain systemd[1]: kubelet.service failed.

</pre>

**Environment**:
<pre>
[root@localhost kubelet.service.d]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@localhost kubelet.service.d]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@localhost kubelet.service.d]# uname -a
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</pre>

**Comment by naarani** [comment]
no, kubeadm setup it

**Comment by naarani** [comment]
> why is this closed? how do you solve this?
> I assume kubeadm needs a running kubelet in order to work.

no, kubeadm setup it
