### ISSUE TITLE
Slightly relax secret data key names?

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#6589]
The keys for the secret's data are required to be DNS subdomain.  A common use case will be to make those filenames, which a subset are valid ("foo.cert").  However... a very common name for a secret file is going to be a dot-file ('.kubeconfig').  I think that there is value in relaxing the secret key name to allow a leading dot.

**Comment by thockin** [comment]
I'm fine with that, but need to make sure we filter "." and ".."

**Comment by pmorie** [comment]
I think we can close this now that #25285 will be in 1.3
