### ISSUE TITLE
make generated_files is not detecting codegen tag changes correctly

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#65928]
/kind bug

It seems like `make generated_files` doesn't always detect codegen tag changes correctly, for example, when someone adds or removes a `// +k8s:` codegen tag.

An easy way to reproduce this bug:
1. Run `make generated_files` and copy `pkg/generated/openapi/zz_generated.openapi.go` out of tree.
2. Find some package with a `// +k8s:openapi-gen=true` tag and remove it. For example,
```diff
diff --git a/staging/src/k8s.io/api/batch/v2alpha1/doc.go b/staging/src/k8s.io/api/batch/v2alpha1/doc.go
index f4ed01ad84..6c25b323f8 100644
--- a/staging/src/k8s.io/api/batch/v2alpha1/doc.go
+++ b/staging/src/k8s.io/api/batch/v2alpha1/doc.go
@@ -15,6 +15,5 @@ limitations under the License.
 */

 // +k8s:deepcopy-gen=package
-// +k8s:openapi-gen=true

 package v2alpha1 // import "k8s.io/api/batch/v2alpha1"
```
3. Run `make generated_files` again.
4. Diff `pkg/generated/openapi/zz_generated.openapi.go` with the version generated in step 1. Notice that there's no diff.
5. Run `make clean` followed by `make generated_files` again.
6. Diff `pkg/generated/openapi/zz_generated.openapi.go` with the version generated in step 1. This time there's a diff.

I noticed this behavior while reviewing #65440.

At first I thought #54372 may be suspect, but it seems like the error is probably around https://github.com/kubernetes/kubernetes/blob/5114d4e0b040d2f00417e0fd3e11204afd30f63c/build/root/Makefile.generated_files#L104-L107 and that PR didn't touch it.

/assign @thockin @ixdy

**Comment by ixdy** [comment]
OK, it's a bit more subtle than I first thought.

It seems like it might only do the wrong thing when you delete a tag; added tags seem to be detected properly.

**Comment by thockin** [comment]
This is one of those cases that kills perf in build systems.  E.g. Go fails or used to in the same way - if you remove a file it doesn't see that any file has a timestamp newer than the result, so it clearly doesn't need to rebuild.  We get around that for Go files by checking the timestamp of the directory itself, as long as we are considering the directory at all.

The key is that last statement.  In this case, we don't even consider the directory in question because the `grep` did not find the tag.  To correctly scrub orphaned gnerated files, we need to find all files that match the name pattern in directories that used to have the tag.  We don't really know who used to have the tag, so we'd have to find across the whole tree each file with the right name, then diff that with the list we expect to have and delete outliers.  That MIGHT be doable for generators that have one result per package.

In this case it is even harder.  There's no artifact left in the directory to indicate that it should be considered (it is indistinguishable from 4000 other directories).  To solve this one, we'd need to keep more metadata on which directories we considered for this build, and then diff that.

**Comment by thockin** [comment]
also curious - when I remove the openapi definition from staging/src/k8s.io/api/batch/v2alpha1/doc.go, I get a new change to pkg/apis/batch/v2alpha1/zz_generated.conversion.go:

```
diff --git a/pkg/apis/batch/v2alpha1/zz_generated.conversion.go b/pkg/apis/batch/v2alpha1/zz_generated.conversion.go
index 1c5509b349..aeddea43c3 100644
--- a/pkg/apis/batch/v2alpha1/zz_generated.conversion.go
+++ b/pkg/apis/batch/v2alpha1/zz_generated.conversion.go
@@ -29,7 +29,6 @@ import (
        conversion "k8s.io/apimachinery/pkg/conversion"
        runtime "k8s.io/apimachinery/pkg/runtime"
        batch "k8s.io/kubernetes/pkg/apis/batch"
-       batch_v1 "k8s.io/kubernetes/pkg/apis/batch/v1"
        core "k8s.io/kubernetes/pkg/apis/core"
 )
 
@@ -216,7 +215,8 @@ func Convert_batch_JobTemplate_To_v2alpha1_JobTemplate(in *batch.JobTemplate, ou
 
 func autoConvert_v2alpha1_JobTemplateSpec_To_batch_JobTemplateSpec(in *v2alpha1.JobTemplateSpec, out *batch.JobTemplateSpec, s conversion.Scope) error {
        out.ObjectMeta = in.ObjectMeta
-       if err := batch_v1.Convert_v1_JobSpec_To_batch_JobSpec(&in.Spec, &out.Spec, s); err != nil {
+       // TODO: Inefficient conversion - can we improve it?
+       if err := s.Convert(&in.Spec, &out.Spec, 0); err != nil {
                return err
        }
        return nil
@@ -229,7 +229,8 @@ func Convert_v2alpha1_JobTemplateSpec_To_batch_JobTemplateSpec(in *v2alpha1.JobT
 
 func autoConvert_batch_JobTemplateSpec_To_v2alpha1_JobTemplateSpec(in *batch.JobTemplateSpec, out *v2alpha1.JobTemplateSpec, s conversion.Scope) error {
        out.ObjectMeta = in.ObjectMeta
-       if err := batch_v1.Convert_batch_JobSpec_To_v1_JobSpec(&in.Spec, &out.Spec, s); err != nil {
+       // TODO: Inefficient conversion - can we improve it?
+       if err := s.Convert(&in.Spec, &out.Spec, 0); err != nil {
                return err
        }
        return nil
```


@sttts

**Comment by thockin** [comment]
something like this seems to work for openapi, need to recreate for otehrs...


```
iff --git a/build/root/Makefile.generated_files b/build/root/Makefile.generated_files
index b4d94fba72..f2c27456fb 100644
--- a/build/root/Makefile.generated_files
+++ b/build/root/Makefile.generated_files
@@ -418,6 +418,27 @@ OPENAPI_DIRS := $(shell                                             \
 
 OPENAPI_OUTFILE := $(OPENAPI_OUTPUT_PKG)/$(OPENAPI_FILENAME)
 
+OPENAPI_DIRS_FILE := $(META_DIR)/openapi.dirs
+
+# This baroque bit detects if a directory used to have be tagged for generation
+# but is not any more.  We do this in two steps.  The first is unilateral and
+# writes a temp file.  The second is done as a proper make rule so that it can
+# be instrumented for debug.  We could do this all in a $(shell) block, but
+# I can't figure how to print debug info to stdout.
+$(shell \
+    mkdir -p $$(dirname $(OPENAPI_DIRS_FILE));                           \
+    echo $(OPENAPI_DIRS) > $(OPENAPI_DIRS_FILE).new.tmp;                 \
+    if ! cmp -s $(OPENAPI_DIRS_FILE).new.tmp $(OPENAPI_DIRS_FILE); then  \
+        cat $(OPENAPI_DIRS_FILE).new.tmp > $(OPENAPI_DIRS_FILE).new;     \
+    fi;                                                                  \
+    rm -f $(OPENAPI_DIRS_FILE).new.tmp                                   \
+)
+$(OPENAPI_DIRS_FILE): $(OPENAPI_DIRS_FILE).new
+       if [[ "$(DBG_CODEGEN)" == 1 ]]; then  \
+           echo "DBG: $@ changed";           \
+       fi;                                   \
+       cat $< > $@
```

**Comment by thockin** [comment]
@sttts that other file is not related - it looks like it was not updated at some point, but should have been...

**Comment by BenTheElder** [comment]
seems like this is
/sig release
(builds)
or
/sig api-machinery
(generated API code)
/remove-sig testing

**Comment by BenTheElder** [comment]
lol! closed by https://github.com/kubernetes/kubernetes/pull/112819
