### ISSUE TITLE
Pod with dynamic volume stays in 'unknown' state if node powers off. Delete not possible

### ISSUE THREAD

**Issue by jomeier** [kubernetes/kubernetes#65936]
Hi,

we are using rook (ceph) as storage solution in our kubernetes cluster.

If we deploy the mysql demo from rook everything works as expected. But if we kill the node which hosts the mysql pod, the mysql pod gets this status, the newly spawned pod is stuck in ContainerCreating forever:

```NAMESPACE          NAME                                      READY     STATUS              RESTARTS   AGE       IP           NODE
default            wordpress-mysql-5f4b68789d-fsxhs          1/1       Unknown             0          10m       10.42.5.9    chmu007w001.rsint.net
default            wordpress-mysql-5f4b68789d-sqflx          0/1       ContainerCreating   0          54s       <none>       chmu004m002.rsint.net
```

Deletion of the pod with this method doesn't work:

```
kubectl delete pod wordpress-mysql-5f4b68789d-fsxhs --force --grace-period=0 --wait=false
```

The pod with the 'unknown' pod will be still there, the newly spawned pod is stuck in 'ContainerCreating'.

Shouldn't take Kubernetes take care about that we can delete also PODs which are on lost nodes?

Thanks and best regards, 

Josef

@kubernetes/sig-scheduling-bugs
@kubernetes/sig-storage-bugs
@kubernetes/sig-node-bugs

- Kubernetes version (use `kubectl version`): 1.10.3
- Cloud provider or hardware configuration: VM 
- OS (e.g. from /etc/os-release): CentOs 7.5 
- Kernel (e.g. `uname -a`): 3.10.0-862.2.3.el7.x86_64
- Install tools: Rancher RKE
- Others:

**Comment by jomeier** [comment]
This stackoverflow article sent me in the right direction and solved my problem:

https://stackoverflow.com/questions/35453792/pods-stuck-at-terminating-status

I had to type:

```
kubectl delete pod wordpress-mysql-5f4b68789d-fsxhs --force --grace-period=0 --wait=false
kubectl edit pod wordpress-mysql-5f4b68789d-fsxhs
```

An editor opens with the manifest for the pod. Remove these two lines:

```
  finalizers:
  - foregroundDeletion
```

Saved the file and leave the editor. The pod with the 'unknown' state will be killed immediately and the newly spawned pod will start as usual.

Shouldn't Kubernetes take care about that? 

I mean: 'force'  should tell kubernetes that I really really really want to kill a pod. Isn't it :-) ?

Josef

**Comment by krmayankk** [comment]
This could also be related to eviction feature not configured

**Comment by jomeier** [comment]
@krmayankk:
What exactly do you mean? 

How does this help in automatic termination of pods which have bound persistent volumes ? Is kubernetes currently able to handle that?

**Comment by bgrant0607** [comment]
cc @kow3ns @saad-ali

**Comment by jomeier** [comment]
Any help on how to properly take care about this situation is deeply appreciated.

**Comment by EamonKeane** [comment]
@jomeier 's solution (remove foreground finalizer) worked for me. The pod wasn't there when I ssh'd into the machine and I also reset the VM to no avail.

**Comment by zanhsieh** [comment]
@jomeier I have encountered similar issue during patching k8s 1.9.3 -> 1.9.6 (configmap formed volume become read only cause pods previously depend on it infinitely on terminating state). The workaround (you might already know) is to go to etcd (in master or container within master) and use etcdctl to clean it up.

Hope this help and sorry if my workaround doesn't help you.

**Comment by orainxiong** [comment]
Ah, I know a little bit about it. I hope it is helpful.

Normally, `kubernetes` is able to detect an unreachable node, and the existing `control-plane` will subsequently evict pods on the unreachable node, and then `kube-scheduler` will automatically reschedule evicted pods to another available node.

I think the root cause is most likely about garbage collection policy. there are 3 variants for the current garbage collection policy: `background`, `foreground`, `orphan`.

If configured foreground mode, root object can't be deleted until its dependents are deleted completely.

If possible you are better off finding the dependents which block deletion of a pod.

**Comment by jomeier** [comment]
Hi,

how can we set the garbage collection policy e.g. to background mode during the initial creation of the pods within the yml file?

Greetz,

Josef

**Comment by HolimaX** [comment]
This is sad of a valid bug to be closed due to inactivity. I still experience this.

**Comment by resker** [comment]
@HolimaX - seems the guidance for reopening it is:

/reopen

**Comment by resker** [comment]
Can confirm beyond the comments from @Holimx that this is still experienced w/ latest K8s.   Could the original reporter / a collaborator reopen?
