### ISSUE TITLE
con't in pod

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#65939]
root@kube-node1:# kubectl get pods
NAME READY STATUS RESTARTS AGE
my-nginx-86555897f9-ddjcg 1/1 Running 0 12m
my-nginx-86555897f9-xglkd 1/1 Running 0 12m
nginx 1/1 Running 0 8m
nginx-ds-7g6fp 1/1 Running 0 1h
nginx-ds-9cjjv 1/1 Running 0 1h
nginx-ds-jrzqs 1/1 Running 0 1h
root@kube-node1:# kubectl exec -it nginx bash
error: unable to upgrade connection: Forbidden (user=kubernetes, verb=create, resource=nodes, subresource=proxy)

无法进入pod内部

**Comment by liggitt** [comment]
Your apiserver is using a client certificate with CN=kubernetes to connect to kubelets. That user is not currently authorized to use the kubelet API. 

The `system:kubelet-api-admin` default cluster role defines the permissions required to access that API. You can grant that permission to your apiserver kubelet client user with `kubectl create clusterrolebinding apiserver-kubelet-api-admin --clusterrole system:kubelet-api-admin --user kubernetes`

/close
