### ISSUE TITLE
unable to mount: special device(EBS)  worker node 

### ISSUE THREAD

**Issue by BKS1989** [kubernetes/kubernetes#65942]
**What happened**:
in aws console it`s showing ebs volume is created and attached to worker node  but  i am getting  this error on kubelet that unable to mount volume

**Mounting command: systemd-run
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/20b9d9a7-81d0-11e8-b81b-02de2bc48464/volumes/kubernetes.io~aws-ebs/pvc-20b904eb-81d0-11e8-b81b-02de2bc48464 --scope -- mount -o bind /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-1b/vol-0
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: Output: Running scope as unit run-15015.scope.
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-1b/vol-0b3723c759569d671 does not exist
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: E0707 11:08:53.168094    1839 aws_ebs.go:419] Mount of disk /var/lib/kubelet/pods/20b9d9a7-81d0-11e8-b81b-02de2bc48464/volumes/kubernetes.io~aws-ebs/pvc-20b904eb-81d0-11e8-b81b-02de2bc48464 failed: mount failed: exit status 32
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: Mounting command: systemd-run
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/20b9d9a7-81d0-11e8-b81b-02de2bc48464/volumes/kubernetes.io~aws-ebs/pvc-20b904eb-81d0-11e8-b81b-02de2bc48464 --scope -- mount -o bind /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-1b/vol-0
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: Output: Running scope as unit run-15015.scope.
Jul 07 11:08:53 ip-172-31-14-233.ap-southeast-1.compute.internal kubelet[1839]: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/ap-southeast-1b/vol-0b3723c759569d671 does not exist
**

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
 kubectl create ns operator
$kubectl create -f https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/controller.yaml -n operator
kubectl create -n operator -f https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/example-es-cluster.yaml

**Anything else we need to know?**:
 i have configured kubernetes 1.11 using kubelet with ha , i just want to know 
**Environment**:
- Kubernetes version v1.11.0
- Cloud provider or hardware configuration: aws
- OS : NAME="CentOS Linux"
   VERSION="7 (Core)"

- Kernel:  3.10.0-862.3.2.el7.x86_64
- Install tools: kubeadm 1.11
- Others: elastic operator 
@kubernetes/sig-aws

**Comment by domcar** [comment]
Anyone working on this? I have the same issue with `vsphere` cloud provider

**Comment by soggiest** [comment]
I'm seeing the same thing on Kubeadm v1.11.3 HA on AWS with the `kubernetes.io/aws-ebs` storageClass

**Comment by hyunsik** [comment]
I also have the same issue with kubernetes.io/aws-ebs provisioner.

**Comment by soggiest** [comment]
I completely forgot to post the resolution to my issue: the pod that is trying to mount the volume created by the aws-ebs provisioner needs to be in the same AZ as the EBS volume. Volumes are not guaranteed to be scheduled in the same AZ as the pod that is trying to mount it. This is resolved in 12.2 with topology aware volume provisioning: https://kubernetes.io/blog/2018/10/11/topology-aware-volume-provisioning-in-kubernetes/
@hyunsik I hope this helps

**Comment by BKS1989** [comment]
I have switch to kubernetes 1.10.4 , it`s working
