### ISSUE TITLE
Support for custom tls cipher suites in kube-proxy

### ISSUE THREAD

**Issue by pashok2398** [kubernetes/kubernetes#65950]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
SSL Medium Strength Cipher Suites Supported

**What you expected to happen**:
Add `--tls-cipher-suites` option to `kube-proxy` as in `kube-apiserver`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
PR for api-server and kubelet https://github.com/kubernetes/kubernetes/pull/48859

**Environment**:
- Kubernetes version (use `kubectl version`): >= 1.10
- Cloud provider or hardware configuration: Any
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Any
- Install tools:
- Others:

**Comment by meeca1218** [comment]
Vulnerability Description:
Synopsis :

The remote service supports the use of medium strength SSL ciphers. 
The remote host supports the use of SSL ciphers that offer medium strength encryption. Nessus regards medium strength as any encryption that uses key lengths at least 64 bits and less than 112 bits, or else that uses the 3DES encryption suite.

Note that it is considerably easier to circumvent medium strength encryption if the attacker is on the same physical network. 

Port: 6443 Here is the list of medium strength SSL ciphers supported by the remote server :

Medium Strength Ciphers (> 64-bit and < 112-bit key, or 3DES) 
...........

Where should I fix the weak ciphers ?  I did it for apache and tomcat but does not know where to fix for kubernetes.  Thx.

**Comment by pashok2398** [comment]
@meeca1218 
6443 is the apiserver....
try to add `--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

**Comment by pashok2398** [comment]
I am closing this issue as i have no Vulnerabilities
set `--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` on `kube-apiserver` and `kubelet` solved the issue.
Thanks

**Comment by meeca1218** [comment]
Thx much.  Pavel.

    On Tuesday, July 31, 2018, 12:35:23 AM PDT, Pavel Druyan <notifications@github.com> wrote:  
 
 
@meeca1218
6443 is the apiserver....
try to add --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
