### ISSUE TITLE
artifactory :"unauthorized: The client does not have permission for manifest"

### ISSUE THREAD

**Issue by dc520** [kubernetes/kubernetes#65958]
**What happened**:
I use artifactory as the docker registry and create the corresponding secret based on the documentation, as follows:

- kubectl_ create secret docker-registry cn-artifactory --docker-server=<my-artifactory-website:5006> --docker-username=<myusername> --docker-password=<mypassword>--docker-email=xxx@xx.com -n public

Then I created a test YAML file with the following contents:

apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: public
spec:
  containers:
    - name: foo
      image: my-artifactory-website:5006/imagename:4 
  imagePullSecrets:
    - name: cn-artifactory

After I applied this pod, I got an error:
- Error: ErrImagePull
- "Failed to pull image "my-artifactory-website:5006/imagename:4": rpc error: code = Unknown desc = Error response from daemon: unauthorized: The client does not have permission for manifest"

But when I use docker login directly, the same username and password, normal login and pull image. The command line is as follows：
- docker login -u myusername -p mypassword my-artifactory-website:5006

There is another nexus docker registry in my namepace. The same create method is used. The nexus docker registry can be used normally, but artifactory can't.

**What you expected to happen**:
How can I make it pull images properly?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.0
- Cloud provider or hardware configuration:None
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-693.11.1.el7.x86_64
- Install tools: 
- Others: Artifactory Version 5.11.0, Docker Version 17.12.1-ce

**Comment by dc520** [comment]
1.9.0版本 的集群创建出来的secret type 是 kubernetes.io/dockercfg ，我把集群升级到1.9.6之后，创建的secret type变成了kubernetes.io/dockerconfigjson，这让我解决了我碰到的问题。

**Comment by dc520** [comment]
The secret type created by the 1.9.0 version of the cluster is kubernetes.io/dockercfg. After I upgraded the cluster to 1.9.6, the created secret type became kubernetes.io/dockerconfigjson, which solved the problem I encountered. problem.

**Comment by bverkron** [comment]
In our case UAC was enabled for the user on a new server build and that produced this same error when attempting to pull an image from Artifactory. After UAC was disabled it worked.
