### ISSUE TITLE
kube-controller-manager tries to find storage account instead of  key-vault

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#65953]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig Azure
> /kind feature

**What happened**:
kube-controller-manager failed to start with the next error:
`2018-07-08T14:42:28.82944156Z stderr F E0708 14:42:28.829339       1 tokens_controller.go:261] error synchronizing serviceaccount kube-system/cronjob-controller: Internal error occurred: rpc error: code = Unknown desc = failed to create key, error: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/my-akv' under resource group 'my-rg' was not found."`
**What you expected to happen**:
kube-controller-manager starts fine
**How to reproduce it (as minimally and precisely as possible)**:
Run kubernetes with Azure Key Vault

**Anything else we need to know?**:
It worked fine, but I've recreated an environment and it stopped. Now it is trying to get a storage account with the name of the AzureKeyVault instead of the key-vault service.
**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
Do you have link about how to "Run kubernetes with Azure Key Vault"? It looks like we need to specify an external resource group for key vault feature.

**Comment by IvanovOleg** [comment]
> Hi
> 
>  @IvanovOleg, thanks for reporting this. yes we have changed our design to include a storage account to handle key creation racing condition. Please refer to this PR: #23.
> 
> To fix this issue, you need to create a storage account in the same resource group as the keyvault instance. But you cannot have - in the name.
Got a response from developers.

**Comment by andyzhangx** [comment]
Do you have link about how to "Run kubernetes with Azure Key Vault"? What's your k8s version?

**Comment by IvanovOleg** [comment]
https://github.com/Azure/kubernetes-kms/blob/master/manual-install.md
v1.11.0

**Comment by andyzhangx** [comment]
cc @ritazh

**Comment by ritazh** [comment]
Ah yes...this was also reported here: https://github.com/Azure/kubernetes-kms/issues/25 will update the manual-install doc to include the creation of the storage account in addition to the key vault.
