### ISSUE TITLE
Failed to mount configmap as volume in a Daemonset Pod if it's evicted before

### ISSUE THREAD

**Issue by vincentwu2011** [kubernetes/kubernetes#65965]
@kubernetes/sig-Apps-bug
**What happened**:
I have a pod is created by a daemonset. Because of the hard disk pressure, the pod is evicted. After I free the disk space and now there is enough free disk space. And the pod is going to start again. But it hangs on ContainerCreating status. From the log of kubelet, it failed to mount a configmap volume.
The error message in kubelet as below:
...
I0709 15:18:41.100558   21886 configmap.go:217] Received configMap core/logrotate-configmap containing (1) pieces of data, 230 total bytes
I0709 15:18:41.100558   21886 configmap.go:217] Received configMap core/logrotate-configmap containing (1) pieces of data, 230 total bytes
E0709 15:18:41.100601   21886 configmap.go:231] Error creating atomic writer: stat /mnt/var/kubelet/pods/b7aac80a-7e68-11e8-83ff-005056b3700f/volumes/kubernetes.io-configmap/config: no such file or directory
E0709 15:18:41.100768   21886 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/configmap/b7aac80a-7e68-11e8-83ff-005056b3700f-config\" (\"b7aac80a-7e68-11e8-83ff-005056b3700f\")" failed. No retries permitted until 2018-07-09 15:18:41.600704828 +0800 CST m=+20.647792372 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"config\" (UniqueName: \"kubernetes.io/configmap/b7aac80a-7e68-11e8-83ff-005056b3700f-config\") pod \"itom-logrotate-ppwnp\" (UID: \"b7aac80a-7e68-11e8-83ff-005056b3700f\") : stat /mnt/var/kubelet/pods/b7aac80a-7e68-11e8-83ff-005056b3700f/volumes/kubernetes.io~configmap/config: no such file or directory"
...

 If I delete the pod, a new pod would be created by daemonset and it would not have the volume mount issue.

Here is the output while describe this pod
[root@test01 kubelet]# kubectl describe pod itom-logrotate-ppwnp -n core
Name:           itom-logrotate-ppwnp
Namespace:      core
Node:           test01.mylab.net/16.187.190.203
Start Time:     Tue, 03 Jul 2018 10:47:01 +0800
Labels:         controller-revision-hash=3722429697
                pod-template-generation=1
                run=itom-logrotate
Annotations:    <none>
Status:         Running
IP:
Controlled By:  DaemonSet/itom-logrotate
Containers:
  itom-logrotate:
    Container ID:
    Image:          localhost:5000/itom-logrotate:3.14.0-001
    Image ID:
    Port:           <none>
    State:          Waiting
      Reason:       ContainerCreating
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 03 Jul 2018 10:47:19 +0800
      Finished:     Tue, 03 Jul 2018 12:57:44 +0800
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      SCRIPT_DELETE_LOG_DIR:       /logs/apiserver /logs/kubelet /logs/kube-proxy /logs/controller /logs/scheduler
      SCRIPT_DELETE_LOG_SURVIVAL:  -mtime +7
    Mounts:
      /cdf-deployments from cdf-deployments (rw)
      /config from config (rw)
      /logs from log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-89zwr (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      logrotate-configmap
    Optional:  false
  log:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kubernetes/log
    HostPathType:
  cdf-deployments:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/cdf-deployments
    HostPathType:
  default-token-89zwr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-89zwr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason       Age                From                                Message
  ----     ------       ----               ----                                -------
  Warning  FailedMount  20m (x27 over 1h)  kubelet, test01.mylab.net  Unable to mount volumes for pod "itom-logrotate-ppwnp_core(b7aac80a-7e68-11e8-83ff-005056b3700f)": timeout expired waiting for volumes to attach/mount for pod "core"/"itom-logrotate-ppwnp". list of unattached/unmounted volumes=[config]
  Warning  FailedMount  5m (x45 over 1h)   kubelet, test01.mylab.net  MountVolume.SetUp failed for volume "config" : stat /mnt/var/kubelet/pods/b7aac80a-7e68-11e8-83ff-005056b3700f/volumes/kubernetes.io~configmap/config: no such file or directory

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1 deploy a daemon set which mount a configmap as volume
2 evict a pod created by the daemon set
3 while a new pod is created, it would be hung on ContainerCreating status

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
   CentOS VM. 8 core CPU 16G Mem
- OS (e.g. from /etc/os-release):
   CentOS 7.2 with kernel 3.10.0-327.el7.x86_64 
- Kernel (e.g. `uname -a`):
  3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/sig Apps

**Comment by djsly** [comment]
/sig-node
I'm having the same issue but with a daemonset having the issue with the service account Token volume

In my case the daemonset is stuck in Terminating due to a missing Volume.

[kubelet.log.tgz.zip](https://github.com/kubernetes/kubernetes/files/2215894/kubelet.log.tgz.zip)

**Comment by ssoor** [comment]
/reopen
I'm having the same issue

**Comment by Kaijun** [comment]
Any updates on this?

i'm encountering the the same issue

**Comment by xial-thu** [comment]
encountering the same issue as well.
