### ISSUE TITLE
Kubelet is pointing to incorrect StorageOS volume location

### ISSUE THREAD

**Issue by cybersuv** [kubernetes/kubernetes#65969]
@kubernetes/sig-contributor-experience-storageos
BUG REPORT

**What happened**:

I have an in-house kubernetes cluster with 3 nodes (Cent OS 7). I have setup storageos as the persistent volume manager and all the services look good. But, when I am trying to create a volume claim and mount the same to a mysql pod, I am getting a weird error. 

`MountVolume.SetUp failed for volume "pvc-619daabb-835c-11e8-b4fd-fa163e32d538" : stat /var/lib/storageos/volumes/9f92e4e1-32ee-ab44-b701-0772071ffa6b: no such file or directory` 

I have checked the location "/var/lib/storageos/volumes" and really the mentioned file is not there. But, now when I investigated further it seems a bit clear that kubelet is trying to point to a directory by the name of the "id" field of the volume claim. 

`# storageos volume inspect
[
    {
        "id": "**9f92e4e1-32ee-ab44-b701-0772071ffa6b**",
        "inode": 200323,
        "name": "pvc-619daabb-835c-11e8-b4fd-fa163e32d538",
        "size": 2,
        "pool": "default",
        "fsType": "ext4",
        "description": "Kubernetes volume",
        "labels": {
            "heptio.com/example": "lamp"
        },
        "namespace": "default",
        "nodeSelector": "",
        "master": {
            "id": "0a977fb5-f1c9-70f5-c0aa-03fcf552d505",
            "inode": 100966,
            "node": "aa0733a1-b118-682a-608c-146328c9df2e",
            "nodeName": "kub-node02",
            "controller": "",
            "controllerName": "",
            "health": "healthy",
            "status": "active",
            "createdAt": "2018-07-09T09:41:45.006072132Z"
        },
        "mounted": false,
        "mountDevice": "",
        "mountpoint": "",
        "mountedAt": "0001-01-01T00:00:00Z",
        "replicas": [],
        "health": "",
        "status": "active",
        "statusMessage": "",
        "mkfsDone": false,
        "mkfsDoneAt": "0001-01-01T00:00:00Z",
        "createdAt": "2018-07-09T09:42:23.648730691Z",
        "createdBy": "storageos"
    }
]
`
But, when I browsed through "/var/lib/storageos/volumes" directory on the master node, I could see something familiar with the above values.

`# ls -lhrt /var/lib/storageos/volumes/
total 512M
-rw-rw---- 1 root disk  2.0G Jul  9 10:14 bst-200323
brw-rw---- 1 root disk 8, 96 Jul  9 10:14 **9f92e4e1-32ee-ab44-b701-0772071ffa6b**
-rw-rw---- 1 root disk  2.0G Jul  9 10:14 0a977fb5-f1c9-70f5-c0aa-03fcf552d505` 

But, this is not present at other nodes. Hence, pod running on node-2 is failing to resolve the path. Is there something I am missing here or seems like a bug ?

**What you expected to happen**:  Persistent volume should be accessible from pods anywhere in the cluster.

**How to reproduce it (as minimally and precisely as possible)**: Set up a kubernetes cluster with 3 nodes having 1 as master and other 2 as data nodes. Deploy mysql with the following yaml definition.

>  
> 
> apiVersion: v1
> kind: Secret
> metadata:
>   name: mysql-credentials
> type: Opaque
> data:
>   rootpw: dmFyTXlSb290UGFzcw==
>   user: dmFyTXlEQlVzZXI=
>   password: dmFyTXlEQlBhc3M=
> 
> ---
> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: database
>   annotations:
>     volume.beta.kubernetes.io/storage-class: fast
> spec:
>   accessModes:
>     - ReadWriteOnce
>   resources:
>     requests:
>       storage: 2Gi
> 
> ---
> 
> apiVersion: extensions/v1beta1
> kind: Deployment
> metadata:
>   name: mysql
> spec:
>   replicas: 1
>   revisionHistoryLimit: 5
>   selector:
>     matchLabels:
>       app: mysql
>   template:
>     metadata:
>       labels:
>         app: mysql
>     spec:
>       containers:
>       - image: mysql
>         name: mysql
>         resources:
>           requests:
>             cpu: 1
>             memory: 2Gi
>         env:
>           - name: MYSQL_ROOT_PASSWORD
>             valueFrom:
>               secretKeyRef:
>                 name: mysql-credentials
>                 key: rootpw
>           - name: MYSQL_USER
>             valueFrom:
>               secretKeyRef:
>                 name: mysql-credentials
>                 key: user
>           - name: MYSQL_PASSWORD
>             valueFrom:
>               secretKeyRef:
>                 name: mysql-credentials
>                 key: password
>           - name: MYSQL_DATABASE
>             value: sakila
>         livenessProbe:
>           tcpSocket:
>             port: 3306
>         ports:
>         - containerPort: 3306
>         volumeMounts:
>         - mountPath: /var/lib/mysql
>           subPath: data
>           name: database
>       volumes:
>       - name: database
>         persistentVolumeClaim:
>           claimName: database
> 
> ---
> 
> apiVersion: v1
> kind: Service
> metadata:
>   name: mysql
> spec:
>   type: ClusterIP
>   ports:
>   - port: 3306
>     protocol: TCP
>   selector:
>     app: mysql
> 
> 

Once this is created through kubectl create -f <filename.yaml> the error is to be shown as below.

`# kubectl describe pod mysql-56bc6f4ff5-k7g7f
Name:           mysql-56bc6f4ff5-k7g7f
Namespace:      default
Node:           kub-node02/10.2.0.5
Start Time:     Mon, 09 Jul 2018 09:41:46 +0000
Labels:         app=mysql
                pod-template-hash=1267290991
Annotations:    <none>
Status:         Pending
IP:
Controlled By:  ReplicaSet/mysql-56bc6f4ff5
Containers:
  mysql:
    Container ID:
    Image:          mysql
    Image ID:
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     1
      memory:  2Gi
    Liveness:  tcp-socket :3306 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MYSQL_ROOT_PASSWORD:  <set to the key 'rootpw' in secret 'mysql-credentials'>    Optional: false
      MYSQL_USER:           <set to the key 'user' in secret 'mysql-credentials'>      Optional: false
      MYSQL_PASSWORD:       <set to the key 'password' in secret 'mysql-credentials'>  Optional: false
      MYSQL_DATABASE:       sakila
    Mounts:
      /var/lib/mysql from database (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tf5hh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  database:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  database
    ReadOnly:   false
  default-token-tf5hh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tf5hh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                From                 Message
  ----     ------       ----               ----                 -------
  Warning  FailedMount  11m (x45 over 1h)  kubelet, kub-node02  MountVolume.SetUp failed for volume "pvc-619daabb-835c-11e8-b4fd-fa163e32d538" : stat /var/lib/storageos/volumes/9f92e4e1-32ee-ab44-b701-0772071ffa6b: no such file or directory
  Warning  FailedMount  1m (x38 over 1h)   kubelet, kub-node02  Unable to mount volumes for pod "mysql-56bc6f4ff5-k7g7f_default(61a8bd69-835c-11e8-b4fd-fa163e32d538)": timeout expired waiting for volumes to attach or mount for pod "default"/"mysql-56bc6f4ff5-k7g7f". list of unmounted volumes=[database]. list of unattached volumes=[database default-token-tf5hh]
`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: 4 vCPU, 8GB Memory, 200GB Disk.
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): 
Linux kub-master 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others:

**Comment by mkumatag** [comment]
what is this storage class pointing to - `volume.beta.kubernetes.io/storage-class: fast` can you describe this as well?

**Comment by cybersuv** [comment]
Can anyone help me here ?

**Comment by yrral86** [comment]
https://docs.storageos.com/docs/prerequisites/mountpropagation

**Comment by croomes** [comment]
This definitely looks like a mount propagation issue.  Please ping me directly if still an issue (sorry I missed this before)

**Comment by bpaskalev** [comment]
Hi I followed the doc for setting mountpropagation and still have similar issue.. the test command in above post runs successfully on both nodes:
[]# docker run -it --rm -v /mnt:/mnt:shared busybox sh -c /bin/date
Wed Nov 21 13:55:00 UTC 2018

**Comment by saintanger** [comment]
same issue here on kubernetes v11 + Rancher 2.1.4
pvc cannot be mounted...

**Comment by yrral86** [comment]
@saintanger Rancher disables mount propagation by default.
https://stackoverflow.com/questions/51336595/how-do-i-enable-mount-propagation-in-rancher-kubernetes-feature-gates
