### ISSUE TITLE
Kubernetes repository can't be vendored

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#65968]
We have written a cli tool that uses kubectl util libraries. Today I was trying to upgrade from Kubernetes 1.10 dependency to 1.11 . But I found that I can't compile code after I revendor to Kubernetes 1.11 . The problem is that  https://github.com/kubernetes/kubernetes/blob/v1.11.0/pkg/kubectl/util/i18n/i18n.go#L107 uses generated code from https://github.com/kubernetes/kubernetes/tree/v1.11.0/pkg/generated package. But the generated code is not committed to the repo. So, after vendoring I can't compile any more. I know committing generated code is not ideal but what other option do I have ? We don't use Bazel and will not use Bazel. 

Thanks. Looking forward to some solution.

/kind bug
/sig cli

**Comment by hoegaarden** [comment]
There is a discussion going on [over here](https://groups.google.com/d/msg/kubernetes-sig-release/GuP_hCI75pI/CYQfLq11CgAJ) about that.

**Comment by tamalsaha** [comment]
I have found a workaround. Run the `make` command which generated the files. I committed them in my fork and using that to vendor. This has unblocked me.

**Comment by ixdy** [comment]
/assign

I am sorry. I thought this would be safe, since we already had several generated files which were not checked into the repo, but this was wrong.

I will add `pkg/generated/bindata.go` back to master and release-1.11 while we figure out the plan.

x-ref #8830

**Comment by ixdy** [comment]
Fix should land in 1.11.1.
