### ISSUE TITLE
Deodorize ObjectReference and SelfLink

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#6596]
Currently, an object must have a `selfLink` in order to obtain an  `ObjectReference` for it unless the `ForTesting_ReferencesAllowBlankSelfLinks` flag is set in the api.

A couple smelly things about this:

1.  Some test code sets the `ForTesting_ReferencesAllowBlankSelfLinks`, some code doesn't
2.  There are some legitimate use-cases for which self links aren't available (ie, pod definitions that come from a json file on disk) -- to get around this there's a hard-coding in the internal API conversions to default a selfLink when converting a Pod that doesn't have one.

I think we should:

1.  Make a `selfLink` required for objects that should have one
2.  Have an officially sanctioned way to indicate that an object necessarily does not have a `selfLink` or to assign a dummy one -- possibly as a sibling to `testapi.SelfLink`
3.  Remove the `ForTesting_ReferencesAllowBlankSelfLinks` flag from the API package
4.  Make all tests set `selfLinks` correctly using `testapi.SelfLink`

Any thoughts?

@thockin @erictune @smarterclayton @bgrant0607 @derekwaynecarr @markturansky

**Comment by pmorie** [comment]
How could I forget @lavalamp

**Comment by markturansky** [comment]
Su desodorante es muy bueno.

**Comment by lavalamp** [comment]
SGTM

**Comment by bgrant0607** [comment]
Related: #2797, #1490, #4651, #4549

**Comment by bgrant0607** [comment]
I'm not sure there are any legitimate cases where selfLink should not be populated in the internal representation. File-based pods are now mirrored back to apiserver. Tests really shouldn't be creating half-baked objects that wouldn't pass validation. (#5121)

Defaulting is version-specific. We have plans to make validation version-specific, also. Clients (i.e., everything except apiserver+rest storage in master and kubelet) should be versioned (#4874, #3955). It's likely that tests will need to move to using versioned client structs.

**Comment by thockin** [comment]
For your (1) - what does it mean to be required in a context where we
legitimately don't have one (as you described - JSON from a file)?  I don't
follow what you're proposing.  I have never been a fan of SelfLink

**Comment by pmorie** [comment]
@thockin I guess my (2) was supposed to address that -- there should be a function that generates a special selfLink to use when you legitimately do not have one.  I need, though, to look into @bgrant0607's comment about file-based pods and the API server to see if that's still even applicable; that and http based pods (but not from the API) are the only cases I can think of where this case would apply.

**Comment by bgrant0607** [comment]
All pods from Kubelet should be sync'ed with the apiserver.

**Comment by bgrant0607** [comment]
cc @satnam6502

**Comment by satnam6502** [comment]
I am going to have a crack at this since I can't bear to look at:
```
$ kubectl get service -o json kibana-logging
{
    "kind": "Service",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "kibana-logging",
        "namespace": "default",
        "selfLink": "/api/v1beta1/services/kibana-logging?namespace=default",
        "uid": "89467924-e9f5-11e4-87f1-42010af087a9",
        "resourceVersion": "18",
        "creationTimestamp": "2015-04-23T20:15:50Z",
        "labels": {
            "kubernetes.io/cluster-service": "true",
            "name": "kibana-logging"
        }
    },
    "spec": {
        "ports": [
            {
                "name": "",
                "protocol": "TCP",
                "port": 5601,
                "targetPort": 80
            }
        ],
        "selector": {
            "name": "kibana-logging"
        },
        "portalIP": "10.0.2.238",
        "sessionAffinity": "None"
    },
    "status": {}
}
```
and the code that writes out cluster level services (now v1beta3) gives the wrong output since it uses `selfLink`:
```
elasticsearch-logging is running at https://104.154.78.159/api/v1beta1/proxy/services/elasticsearch-logging/ (note the trailing slash)
kibana-logging is running at https://104.154.78.159/api/v1beta1/proxy/services/kibana-logging/ (note the trailing slash)
kube-dns is running at https://104.154.78.159/api/v1beta1/proxy/services/kube-dns/ (note the trailing slash)
influxGrafana is running at https://104.154.78.159/api/v1beta1/proxy/services/monitoring-grafana/ (note the trailing slash)
heapster is running at https://104.154.78.159/api/v1beta1/proxy/services/monitoring-heapster/ (note the trailing slash)
```
but what we need to use now is the v1beta3 addresses e.g. `https://104.154.78.159/api/v1beta3/proxy/namespaces/default/services/kibana-logging/`

**Comment by pmorie** [comment]
Go for it @satnam6502

**Comment by bgrant0607** [comment]
@satnam6502 Does curl give you the same output?

**Comment by satnam6502** [comment]
Once I can create a cluster again I shall tell you :-)

**Comment by satnam6502** [comment]
@caesarxuchao has expressed interest in taking this on as a good getting started task. I suggest syncing with @bgrant0607 and @lavalamp

**Comment by caesarxuchao** [comment]
@satnam6502 @lavalamp @bgrant0607 As a beginner, I don't quite follow @pmorie's initial comments.  But at least I can first update the SelfLink format from v1beta1 to v1beta3, as described in #7260, which sounds straightforward. Any comments?

**Comment by smarterclayton** [comment]
This should also fix https://github.com/GoogleCloudPlatform/kubernetes/issues/7127

**Comment by smarterclayton** [comment]
We have to stop using static accessors in the code - taking meta.Interface is the correct way to get object version and kind

**Comment by satnam6502** [comment]
@bgrant0607 : the answer is that using curl to GET to service returns a v1beta3 selfLink.

```
$ curl --insecure -H "Authorization: Bearer kGbQPemgaNOTREALLY8tHyGwopsVxAp" https://104.197.26.147/api/v1beta3/namespaces/default/services/elasticsearch-logging
{
  "kind": "Service",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "elasticsearch-logging",
    "namespace": "default",
    "selfLink": "/api/v1beta3/namespaces/default/services/elasticsearch-logging",
    "uid": "929c124b-eaa1-11e4-8e9a-42010af07932",
    "resourceVersion": "47",
    "creationTimestamp": "2015-04-24T16:47:19Z",
    "labels": {
      "kubernetes.io/cluster-service": "true",
      "name": "elasticsearch-logging"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "",
        "protocol": "TCP",
        "port": 9200,
        "targetPort": "es-port"
      }
    ],
    "selector": {
      "name": "elasticsearch-logging"
    },
    "portalIP": "10.0.57.62",
    "sessionAffinity": "None"
  },
  "status": {}
}
```

**Comment by pmorie** [comment]
@caesarxuchao Are you still planning to work on this?  I'm rolling through my open issues and this still needs to be fixed.  If not, we can tag it help-wanted.

**Comment by caesarxuchao** [comment]
Hi @pmorie, sorry for the long delay. No, I'm not planning to work on this. Feel free to assign others.

**Comment by aveshagarwal** [comment]
if nobody is working on this, I would be happy to look into it.

**Comment by caesarxuchao** [comment]
I'm not working on this. Go for it @aveshagarwal!

**Comment by pmorie** [comment]
@aveshagarwal tag me in when you have a PR please

**Comment by aveshagarwal** [comment]
@pmorie sure.

**Comment by pmorie** [comment]
Resolved by #15510

**Comment by aveshagarwal** [comment]
@pmorie could you close it please?

**Comment by pmorie** [comment]
Yep, thanks @aveshagarwal!
