### ISSUE TITLE
CRD validation resource immutable

### ISSUE THREAD

**Issue by fudali113** [kubernetes/kubernetes#65973]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
/kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I want some of my fields to be immutable in CRD, can I do that?

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mkumatag** [comment]
what do you mean by immutable? do you want to have something you don't want to change after creating it?

**Comment by fudali113** [comment]
Yes，i want to some field can't be change。Is there any way? @mkumatag

**Comment by nikhita** [comment]
> Yes，i want to some field can't be change。Is there any way?

No, there is no way to mark fields as immutable right now.

OpenAPI schema does have a construct called `readOnly` (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-20) but we don't support that right now. Would need to investigate if we could indeed support it.

/area custom-resources
/cc @sttts

**Comment by Gimi** [comment]
Will this feature be considered to be implemented? This is quite useful, just like the native objects in kubernetes, not all fields are mutable after the object is created. For CRDs, there will be no different.

**Comment by mbohlool** [comment]
You can use admission webhooks to validate any change including making sure the field is not changed. We may consider dedicated validation webhook in future but for now Admission webhooks do the job.

**Comment by Gimi** [comment]
For sure webhook is an option here. But IMHO webhooks are heavy (compared to specifying a field in the CRD yaml file), and most likely for more complicated cases, like the validation might involves some external API calls to some other services. It makes more sense to me that simple validations like `readOnly` should be handled by CRD.

**Comment by BenWUKFast** [comment]
It would be fantastic to get this implemented as a none webhook based solution. The `read-only` could be used to allow initialization, then after the field becomes immutable.

**Comment by antonlisovenko** [comment]
I absolutely support this feature. Webhooks require long time to develop and support, but we meet the use case of immutable fields again and again, the easy way is to add the field into status and mark the CR as failed in case the spec field has diverged but putting the fields to status only to support contract is a quite ugly way

**Comment by dgoodwin** [comment]
:+1: I think this would be a very high value and logical feature to support. We've done the webhook path and indeed it was a big investment, and feels disproportionately heavy handed. All we've needed to use it for thus far was making fields immutable once set.

**Comment by sttts** [comment]
I agree this would be awesome. But for being able to do that we have to restrict the OpenAPI features in a sane way that read-only can be derived in a consistent way for every field. We are working on this.

**Comment by apelisse** [comment]
I'm working on a KEP right now. It will make it impossible to change immutable fields after creation. Will update this issue when the KEP is sent out.

**Comment by apelisse** [comment]
KEP: https://github.com/kubernetes/enhancements/pull/1099

**Comment by afirth** [comment]
KEP shipped in https://github.com/kubernetes/enhancements/pull/1265

still want :+1:

**Comment by afirth** [comment]
/remove-lifecycle-stale

Paging @apelisse :1st_place_medal:

**Comment by apelisse** [comment]
We're not forgetting about that, I'm hoping we can do that in 1.19!

**Comment by afirth** [comment]
amazing :100:  I messed up the command
/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by enxebre** [comment]
cross referencing wip for this is here
https://github.com/kubernetes/enhancements/blob/8b9b994136371f1bc938aabf012f4c45535d684c/keps/sig-api-machinery/20190603-immutable-fields.md
And https://github.com/kubernetes/kubernetes/pull/83743

**Comment by afirth** [comment]
I see work is still happening over in cluster API
/remove-lifecycle stale

**Comment by shrutiyer** [comment]
Will this feature be shipped in any upcoming releases?

**Comment by apelisse** [comment]
We're planning on doing that! @xiaobaitusi

**Comment by absynth76** [comment]
must have

**Comment by xiaobaitusi** [comment]
Hi, we are working on it with schema design iteration. Will update this thread when we have more information. Thanks!

**Comment by adevjoe** [comment]
Any progress or design doc on this?

**Comment by ChenLingPeng** [comment]
we need this feature

**Comment by zoroyihan** [comment]
Since this feature is not available now, anybody has an admission webhook implementation example?

**Comment by arkhipovds** [comment]
We need this feature

**Comment by sttts** [comment]
With [CEL](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language) you will be able to express immutability.

**Comment by jpbetz** [comment]
> With [CEL](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language) you will be able to express immutability. cc Joe Betz Cici Huang

We have some statements in the KEP about this:

> For immutability use case, validator will have access to the existing version of the object. This will be accessible to CEL via the old<propertyName> identifier. ...

But this won't be in the alpha for 1.23, and we need to revisit the design and look through the edge cases a lot more carefully before we commit to implementing.

cc @liggitt

**Comment by franpog859** [comment]
Hello, any news on this topic? It'd be great to have it!

**Comment by apelisse** [comment]
We're working on a kep, can you share what your goals are? Now is the best time to ask! ;-)

**Comment by franpog859** [comment]
@apelisse , I'm implementing an operator that uses a CR to obtain some information needed to create/ update/ delete other different resources. Some specs of these resources are not upgradeable. I think it'd be good to make these CR fields immutable so the user cannot trigger the operator with the changes that cannot be properly maintained anyway. An error while trying to edit an immutable field would solve the problem with inconsistency between the CR and the spec of the other resources and would make the validation in the operator much easier

**Comment by apelisse** [comment]
cc @alexzielenski

**Comment by jpbetz** [comment]
Since I don't think it's been mentioned on this issue yet, I wanted to point out that x-kubernetes-validations [transition rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#transition-rules) can be used to enforce CRD immutability.  The main caveat is that the feature is currently alpha. It is slated for beta in 1.25.

**Comment by apelisse** [comment]
We should be able to close this now, no? I'll pro-actively close, let me know in the comments if you disagree.

**Comment by alexzielenski** [comment]
Relevant blog post on this topic: https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/
