### ISSUE TITLE
Remove kubelet preemption logic

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#65990]
**What happened**:

Since, we have preemption logic in kube-scheduler to preempt pods while placing critical pods, the logic in kubelet for preemption could be removed. 

As of now, the edge case stopping this is:
(from offline discussion with Bobby)
- DS controller critical pods are directly bound to node without resource checking. As a result, we need some preemption logic in kubelet to ensure that pods have enough resources. 

Some potential solutions to above problem:
- We could rely on rescheduler and the plan is to move to descheduler in near future to make place for those DScontrolled critical pods.
- We could rely on 'Schedule DS pods by default scheduler' once it graduates to beta.

Note: If we don't remove this preemption logic in kubelet, there is a very good chance that some high priority pods are preempted from node since this kubelet is not priority aware.

/cc @bsalamat @dashpole @aveshagarwal @sjenning @derekwaynecarr 

/sig node 
/sig scheduling

**Comment by dashpole** [comment]
Another edge case we may want to consider is static pods.  If a new static pod is created, or if the kubelet restarts after a static pod had failed, it may be rejected without this feature.

I believe the kubelet is priority-aware.  It will not "preempt" a pod with node or system critical priority during kubelet admission, as it considers those pods to also be "critical".  It may preempt some "high priority" pods as long as they are not critical, though.  If needed, we could change the kubelet preemption algorithm to be priority aware.

But if the static pod case is not deemed important, and the other cases mentioned are addressed, I think removing the feature makes sense.

**Comment by ravisantoshgudimetla** [comment]
Thanks @dashpole.

> I believe the kubelet is priority-aware. 

You are right that kubelet is priority aware till system critical priorities. What I meant earlier is kubelet is not aware of "high priority" pods which are non-critical, which you already mentioned.

Coming to static pods, I don't know the historical background of static pods in kubernetes but the places, I have seen them being used are self-hosted clusters, which are anyways going to be system critical components. So, not caring about static pods might be a problem. 

I have one question in general though, 

Is it safe to assume static pods to be always system critical priority pods so that in kubelet preemption is limited to static pods and use priority based eviction mentioned here(https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#eviction-strategy)?

**Comment by dashpole** [comment]
Static pods are not always system critical.  There are (somewhere out there) users of standalone kubelet: kubelet with no apiserver who just run static pods.
I try to differentiate "kubelet preemption" which occurs at admission time when the requests of a new pod don't fit within the allocatable of a node, and "kubelet eviction" which occurs when node resources run low.  The eviction strategy document covers the latter, and this bug concerns the former.  They have no relation to eachother other than that both can remove pods from a node.

**Comment by dashpole** [comment]
Yes, This is what I mean above by `If needed, we could change the kubelet preemption algorithm to be priority aware.`

**Comment by krmayankk** [comment]
@kubernetes/sig-scheduling-feature-requests  @bsalamat  is this still relevant ?
