### ISSUE TITLE
error after install kubelet kubeadm kubectl

### ISSUE THREAD

**Issue by keko00** [kubernetes/kubernetes#65995]
after install fresh kubelet kubeadm kubectl i got that kubelet could not able to work as well it's stuck in loop try to start and its start for some Seconds and then it's stopped again as show in screen shots 
version of kubelet v1.11.0 
![screenshot from 2018-07-09 23-00-35](https://user-images.githubusercontent.com/24421498/42476042-e9ca8f9a-83cc-11e8-9c10-00eca42e02b5.png)
![screenshot from 2018-07-09 23-01-28](https://user-images.githubusercontent.com/24421498/42476055-f0cc0314-83cc-11e8-93c2-4566dce21bee.png)

**Comment by liggitt** [comment]
did you run through the kubeadm setup instructions? the kubelet installs in a state that leaves it looping, waiting for configuration.

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#instructions

**Comment by aojea** [comment]
@keko00 have you checked if kubelet and docker are using the same cgroup?

https://github.com/kubernetes/kubeadm/issues/103

**Comment by keko00** [comment]
Now after running kube init i couldn't continue initialization and got this error in kubelet status 
i uesd in installation kubernetes doc 
![screenshot from 2018-07-11 23-30-49](https://user-images.githubusercontent.com/24421498/42600526-f360ead0-8562-11e8-80d0-5ed4614fa8ad.png)

**Comment by keko00** [comment]
@aojea after i changed cgroup in kubeadm.conf to be like docker cgroup and trt again kube inite i got other error this time as showed 
![1](https://user-images.githubusercontent.com/24421498/42601399-c9e767e4-8565-11e8-8d8a-54eec56d6587.png)
![2](https://user-images.githubusercontent.com/24421498/42601411-d1dd2d26-8565-11e8-96d7-e67d51d5d58d.png)

**Comment by neolit123** [comment]
kubeadm since 1.11 sets automatically the cgroup driver for the kubelet.

i see a missing container reference in the second to last image, which suggests that you are getting a "running state", of sorts and this issue is no longer about installing kube* tools.

the report is incomplete and it is unclear, which:
- k8s version you are using
- OS you are running on.

**Comment by keko00** [comment]
@neolit123 
OS version: Centos 7.5
k8s version: v1.11.0

**Comment by timothysc** [comment]
closing this issue.  

If you are still seeing an issue please open in the kubeadm repo here - https://github.com/kubernetes/kubeadm
