### ISSUE TITLE
[AWS][CoreOS] - cloud formation template fails

### ISSUE THREAD

**Issue by roman-shuhov** [kubernetes/kubernetes#6599]
I'm trying to use your cloudformation template for CoreOS at amazon cloud (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloudformation-template.json) But i always get an error: 'Cannot create outputs: Attribute: PublicIp was not found for resource:...'

Let me know if you need more information...

**Comment by vishh** [comment]
cc @jmreicha
