### ISSUE TITLE
Unable to connect to  master node from worker node in kubernetes

### ISSUE THREAD

**Issue by hariprasadsly** [kubernetes/kubernetes#66013]
I am new to  Kubernetes . When I am running the kubectl get pod I am getting the following error.

[root@kubernetes-workernode1 ~]# kubectl get pod
E0710 10:04:07.577240   31002 round_trippers.go:169] CancelRequest not implemented
E0710 10:04:39.578067   31002 round_trippers.go:169] CancelRequest not implemented
E0710 10:05:11.578828   31002 round_trippers.go:169] CancelRequest not implemented
E0710 10:05:43.579544   31002 round_trippers.go:169] CancelRequest not implemented
E0710 10:06:15.580207   31002 round_trippers.go:169] CancelRequest not implemented
Unable to connect to the server: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

@smarterclayton

**Comment by PatrickLang** [comment]
This is very odd - I have a kubeconfig that:
- Works with kubectl v1.11.1 (from Canonical native on Ubuntu 18.04)
- Works with kubectl 1.11.0 for Windows-amd64
- Returns this error with the kubectl binary from https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#v1112 run under Windows Subsystem for Linux (Ubuntu 16.04 userland)

**Comment by alexsandro-xpt** [comment]
Same problem here, @hariprasadsly any progress?

**Comment by zhachaoy** [comment]
same problem here by client-keystone-auth

`[root@k8s-master2 ~]# kubectl get pods
Please enter Keystone Auth URL: http://172.16.135.105:5000
Please enter domain name: default
Please enter user name: admin
Please enter password: 
Please enter Keystone Auth URL: E0928 20:42:56.398663   19682 round_trippers.go:169] CancelRequest not implemented`

**Comment by zhachaoy** [comment]
the problem has disappeared
the reason is that each cluster master node configuration is different, must keep the configuration of apiserver consistent

**Comment by CaryJ** [comment]
If you're running under WSL (as @PatrickLang says he is), you're probably hitting this bug: https://github.com/Microsoft/WSL/issues/3399
A reboot will fix it until you have the proper fix installed.

**Comment by brabia** [comment]
If you are using any kind of proxy try to disable it, that was the solution for my case
