### ISSUE TITLE
Why do we have both cmd/kubernetes/ and cmd/hyperkube

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#6601]
This is silly, we should get rid of one. We shouldn't be maintaining two of these things.

**Comment by thockin** [comment]
+1 can we nuke cmd/kubernetes?

**Comment by kelseyhightower** [comment]
Now I know what the kubernetes binary is.

**Comment by luxas** [comment]
`cmd/kubernetes` was removed a long time ago.
