### ISSUE TITLE
Investigate higher latency of 'delete RC' calls

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#66026]
The recent 5k-performance run (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/177) failed due to high latency of delete RC calls:

```
WARNING Top latency metric: {Resource:replicationcontrollers Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:4.303ms Perc90:14.717ms Perc99:1.165474s Perc100:0s} Count:5050}
```

This might be a flake (we'll know that soon) or a regression. @wojtek-t suspects that it maybe related to change enabling advanced audit-logging in our tests (https://github.com/kubernetes/test-infra/pull/8604). But we need to investigate.

cc @kubernetes/sig-scalability-bugs @mborsz @krzysied

**Comment by shyamjvs** [comment]
On looking into the [apiserver logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/177/artifacts/gce-scale-cluster-master/kube-apiserver.log-20180709-1531141211.gz) , I've found that these increased latencies are observed for a time window of few tens of seconds:

```
11256219:I0709 10:00:25.137477       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-23-2vtdw/replicationcontrollers/density-latency-pod-4472: (1.116538758s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11256785:I0709 10:00:25.470742       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-24-kc75x/replicationcontrollers/density-latency-pod-4473: (1.005226841s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11257350:I0709 10:00:25.802813       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-27-nxpsz/replicationcontrollers/density-latency-pod-4476: (1.087845424s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11257356:I0709 10:00:25.803111       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-26-f4xjn/replicationcontrollers/density-latency-pod-4475: (1.087866217s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11261397:I0709 10:00:28.200497       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-31-cqwfj/replicationcontrollers/density-latency-pod-4480: (1.287839472s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
...
11349743:I0709 10:01:15.914223       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-39-6kbxk/replicationcontrollers/density-latency-pod-4638: (1.062615871s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11353082:I0709 10:01:17.712813       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-42-crj7s/replicationcontrollers/density-latency-pod-4641: (1.218974347s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11353527:I0709 10:01:18.019042       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-44-9c8rh/replicationcontrollers/density-latency-pod-4643: (1.046664759s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
11353588:I0709 10:01:18.084263       1 wrap.go:42] DELETE /api/v1/namespaces/e2e-tests-density-30-43-kqmhp/replicationcontrollers/density-latency-pod-4642: (1.110551858s) 200 [e2e.test/v1.12.0 (linux/amd64) kubernetes/4bb3a2a 35.188.161.128:42112]
```

**Comment by shyamjvs** [comment]
From the traces, almost all time of the operation seems to go into [etcd write operation](https://github.com/kubernetes/kubernetes/blob/029213748a27164b74335b71255ee6e77f0ab3bc/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L122-L132) iiuc:

```
I0709 10:00:35.102520       1 trace.go:76] Trace[853174958]: "Delete /api/v1/namespaces/e2e-tests-density-30-41-4w7pd/pods/density-latency-pod-4490-4t7wz" (started: 2018-07-09 10:00:34.089178396 +0000 UTC m=+6732.743738149) (total time: 1.013318755s):
Trace[853174958]: [1.01319899s] [1.013082311s] Object deleted from database
```

Since the [audit step](https://github.com/kubernetes/kubernetes/blob/029213748a27164b74335b71255ee6e77f0ab3bc/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L89-L91) already happens before this point, I'm doubtful if the slowness here is caused by that.

In general, there are many write calls around that time (specifically `PATCH nodes`) which I believe is slowing down etcd I/Ops. One experiment (as suggested by @wojtek-t) which I also believe is worth doing is to reduce RC deletion rate and see.

**Comment by shyamjvs** [comment]
Btw @mborsz - one thing we should try to confirm here is if this is a flaky issue.

**Comment by shyamjvs** [comment]
So the next run also failed similarly suggesting that this is likely not a flake - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/178

I took a look at CPU-usage of apiserver and it seems to have increased b/w runs 176 and 177 by more than 5 cores:

![api-cpu](https://user-images.githubusercontent.com/4333971/42624994-fd413c44-85c6-11e8-9c8a-f24551addb89.png)

There's also a rise in memory-usage of apiserver by few GBs (though the CPU being a scarcer resource is more concerning to me):

![api-mem](https://user-images.githubusercontent.com/4333971/42625072-29af8ae2-85c7-11e8-8e68-3764ac00d232.png)

**Comment by shyamjvs** [comment]
Interestingly, there's also some increase in CPU usage of etcd (which I wouldn't expect to be caused by audit-logging (at least in a direct way) unless I'm missing something):

![etcd-cpu](https://user-images.githubusercontent.com/4333971/42625429-0ed93d5c-85c8-11e8-8c59-7a5b6e41afa5.png)

**Comment by shyamjvs** [comment]
Looking at the k/k [diff](https://github.com/kubernetes/kubernetes/compare/86b9a5322...4bb3a2a55) - I can't find anything obviously bad.
From test-infra [diff](https://github.com/kubernetes/test-infra/compare/e66e2e5dd...4c0d1dff8), the only suspicious change is the audit-logging one - https://github.com/kubernetes/test-infra/pull/8604

I plan to proceed here as follows:

- Disable audit-logging to verify if that's the cause
  - If no, continue looking for other causes
  - If yes,
    - report this issue to Advanced auditing 1.12 umbrella bug - https://github.com/kubernetes/kubernetes/issues/65266
    - proceed with manually experimenting (to not affect our CI job) w/ audit-logging enabled, but at reduced RC deletion rate (as noted above) to see if it helps

**Comment by mborsz** [comment]
I believe that I found a next instance of similar issue in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/16314

From logs:
```
I0806 01:27:07.345] Aug  6 01:27:07.345: INFO: WARNING Top latency metric: {Resource:pods Subresource: Verb:POST Scope:namespace Latency:{Perc50:22.961ms Perc90:184.701ms Perc99:1.04967s Perc100:0s} Count:3502}
I0806 01:27:07.346] Aug  6 01:27:07.345: INFO: Top latency metric: {Resource:pods Subresource:binding Verb:POST Scope:namespace Latency:{Perc50:15.232ms Perc90:153.753ms Perc99:384.447ms Perc100:0s} Count:3500}
I0806 01:27:07.346] Aug  6 01:27:07.345: INFO: Top latency metric: {Resource:pods Subresource:status Verb:PATCH Scope:namespace Latency:{Perc50:5.893ms Perc90:35.988ms Perc99:201.951ms Perc100:0s} Count:18477}
I0806 01:27:07.346] Aug  6 01:27:07.345: INFO: Top latency metric: {Resource:pods Subresource: Verb:GET Scope:namespace Latency:{Perc50:2.984ms Perc90:31.211ms Perc99:161.106ms Perc100:0s} Count:25705}
I0806 01:27:07.346] Aug  6 01:27:07.345: INFO: Top latency metric: {Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:8.871ms Perc90:12.41ms Perc99:132.668ms Perc100:0s} Count:22}
```

In apiserver's logs I see:

```
I0806 01:21:05.578771       1 trace.go:76] Trace[1573127378]: "Create /api/v1/namespaces/e2e-tests-density-30-1-ndj4k/pods" (started: 2018-08-06 01:21:04.72996987 +0000 UTC m=+169.534898867) (total time: 534.841645ms):
Trace[1573127378]: [367.747795ms] [367.681553ms] About to store object in database
Trace[1573127378]: [533.855129ms] [166.107334ms] Object stored in database
I0806 01:21:05.725821       1 trace.go:76] Trace[1795892763]: "Create /api/v1/namespaces/e2e-tests-density-30-1-ndj4k/pods" (started: 2018-08-06 01:21:04.743827435 +0000 UTC m=+169.548756424) (total time: 737.264501ms):
Trace[1795892763]: [713.065102ms] [712.898198ms] About to store object in database
I0806 01:21:05.725914       1 wrap.go:42] POST /api/v1/namespaces/e2e-tests-density-30-1-ndj4k/pods: (1.092440478s) 201 [kube-controller-manager/v1.12.0 (linux/amd64) kubernetes/7dcbdbb/system:serviceaccount:kube-system:replication-controller [::1]:47492]
I0806 01:21:05.726226       1 wrap.go:42] POST /api/v1/namespaces/e2e-tests-density-30-1-ndj4k/pods: (1.093474929s) 201 [kube-controller-manager/v1.12.0 (linux/amd64) kubernetes/7dcbdbb/system:serviceaccount:kube-system:replication-controller [::1]:47492]
```

IIUC this means that step 'About to store object in database' took 367ms and 712ms respectively.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L113-L129 suggests that this step writes audit logs.

I suggest disabling audit-logging in ci-kubernetes-e2e-gci-gce-scalability as well and checking if it reduces number of high latency requests.

**Comment by shyamjvs** [comment]
So I confirmed that disabling advanced audit, indeed restored the `delete RC` latency back within the SLO in our 5k-node tests:

![audit](https://user-images.githubusercontent.com/4333971/43902569-b79f3b8e-9bea-11e8-8b59-c99d82b0d86c.png)

cc @liggitt @sttts @loburm - Could someone weigh in on this? It seems to affect even 100-node scalability tests (if @mborsz's suspicion above it right).

**Comment by liggitt** [comment]
is audit configured in batch or blocking mode?

**Comment by tallclair** [comment]
/cc @x13n 

The logs are configured for file logging in batch. Here's the audit configuration from the apiserver log:
```
I0806 01:18:15.355984       1 flags.go:27] FLAG: --audit-log-batch-buffer-size="10000"
I0806 01:18:15.355995       1 flags.go:27] FLAG: --audit-log-batch-max-size="400"
I0806 01:18:15.356006       1 flags.go:27] FLAG: --audit-log-batch-max-wait="30s"
I0806 01:18:15.356019       1 flags.go:27] FLAG: --audit-log-batch-throttle-burst="15"
I0806 01:18:15.356030       1 flags.go:27] FLAG: --audit-log-batch-throttle-enable="false"
I0806 01:18:15.356040       1 flags.go:27] FLAG: --audit-log-batch-throttle-qps="10"
I0806 01:18:15.356052       1 flags.go:27] FLAG: --audit-log-format="json"
I0806 01:18:15.356062       1 flags.go:27] FLAG: --audit-log-maxage="0"
I0806 01:18:15.356072       1 flags.go:27] FLAG: --audit-log-maxbackup="0"
I0806 01:18:15.356082       1 flags.go:27] FLAG: --audit-log-maxsize="2000000000"
I0806 01:18:15.356093       1 flags.go:27] FLAG: --audit-log-mode="batch"
I0806 01:18:15.356103       1 flags.go:27] FLAG: --audit-log-path="/var/log/kube-apiserver-audit.log"
I0806 01:18:15.356114       1 flags.go:27] FLAG: --audit-log-truncate-enabled="false"
I0806 01:18:15.356124       1 flags.go:27] FLAG: --audit-log-truncate-max-batch-size="10485760"
I0806 01:18:15.356137       1 flags.go:27] FLAG: --audit-log-truncate-max-event-size="102400"
I0806 01:18:15.356148       1 flags.go:27] FLAG: --audit-log-version="audit.k8s.io/v1beta1"
I0806 01:18:15.356159       1 flags.go:27] FLAG: --audit-policy-file="/etc/audit_policy.config"
I0806 01:18:15.356170       1 flags.go:27] FLAG: --audit-webhook-batch-buffer-size="10000"
I0806 01:18:15.356180       1 flags.go:27] FLAG: --audit-webhook-batch-initial-backoff="10s"
I0806 01:18:15.356191       1 flags.go:27] FLAG: --audit-webhook-batch-max-size="400"
I0806 01:18:15.356201       1 flags.go:27] FLAG: --audit-webhook-batch-max-wait="30s"
I0806 01:18:15.356211       1 flags.go:27] FLAG: --audit-webhook-batch-throttle-burst="15"
I0806 01:18:15.356220       1 flags.go:27] FLAG: --audit-webhook-batch-throttle-enable="true"
I0806 01:18:15.356230       1 flags.go:27] FLAG: --audit-webhook-batch-throttle-qps="10"
I0806 01:18:15.356241       1 flags.go:27] FLAG: --audit-webhook-config-file=""
I0806 01:18:15.356251       1 flags.go:27] FLAG: --audit-webhook-initial-backoff="10s"
I0806 01:18:15.356261       1 flags.go:27] FLAG: --audit-webhook-mode="batch"
I0806 01:18:15.356271       1 flags.go:27] FLAG: --audit-webhook-truncate-enabled="false"
I0806 01:18:15.356281       1 flags.go:27] FLAG: --audit-webhook-truncate-max-batch-size="10485760"
I0806 01:18:15.356292       1 flags.go:27] FLAG: --audit-webhook-truncate-max-event-size="102400"
I0806 01:18:15.356302       1 flags.go:27] FLAG: --audit-webhook-version="audit.k8s.io/v1beta1"
```

I suspect the problem is the large batch size. We shouldn't be batching writes to files, just buffering. I suspect setting `--audit-log-batch-max-size="1"` should fix this.

**Comment by liggitt** [comment]
what do the burst/qps numbers do for log writing?

**Comment by tallclair** [comment]
Throttle is disabled for logs (`--audit-log-batch-throttle-enable="false"`) so the burst & qps don't matter. If the throttle was enabled, it would limit the rate that batches could be written, but doesn't make much sense for the log backend.

**Comment by tallclair** [comment]
Hopefully https://github.com/kubernetes/kubernetes/pull/67223 fixes this.

**Comment by shyamjvs** [comment]
Thanks @tallclair @liggitt. Will try enabling back audit-logging and verify, once the above PR is merged.

**Comment by mborsz** [comment]
Next instance of this issue in 2k: https://github.com/kubernetes/kubernetes/issues/67701#issue-352931253, rather unrelated to audit logging ('Object deleted from database')

**Comment by shyamjvs** [comment]
/remove-lifecycle stale
:)

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@mborsz - is this one fixed already? Can this be close or there are still some things that needs to be investigated and/or fixed?

**Comment by wojtek-t** [comment]
This seems to be outdated.
