### ISSUE TITLE
Missing import apiextensionsfeatures in kube_features.go

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#66031]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
```
# k8s.io/kubernetes/pkg/features
..\..\go\src\k8s.io\kubernetes\pkg\features\kube_features.go:415:48: cannot use "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceValidation (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/feature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map key
..\..\go\src\k8s.io\kubernetes\pkg\features\kube_features.go:416:50: cannot use "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceSubresources (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/feature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map key
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.0
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
Closing because the master currently builds fine and this should be fixed if `k8s.io/apiserver` is in your gopath. Please feel free to reopen if you still come across an issue.

/close

**Comment by IvanovOleg** [comment]
`# k8s.io/kubernetes/pkg/features
..\..\go\src\k8s.io\kubernetes\pkg\features\kube_features.go:415:48: cannot use "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceValidation (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/feature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map key
..\..\go\src\k8s.io\kubernetes\pkg\features\kube_features.go:416:50: cannot use "k8s.io/apiextensions-apiserver/pkg/features".CustomResourceSubresources (type "k8s.io/apiextensions-apiserver/vendor/k8s.io/apiserver/pkg/util/feature".Feature) as type "k8s.io/apiserver/pkg/util/feature".Feature in map key`

**Comment by RunAtWorld** [comment]
I have the same error,how to fix?
