### ISSUE TITLE
Image garbage collection is always disabled in kubelet in 1.11

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#66046]
In the `StartGarbageCollection` function, there is a `defer close(stopChan)` that always runs and closes the channel when returning. This means that instead of running periodically, the image garbage collection will be terminated immediately when the function returns. 

https://github.com/kubernetes/kubernetes/blob/91e7b4fd31fcd3d5f436da26c980becec37ceefe/pkg/kubelet/kubelet.go#L1247-L1253

The bug was introduced by #51423 in 1.11

/cc @derekwaynecarr @jiaxuanzhou @kubernetes/sig-node-bugs @dashpole

**Comment by yujuhong** [comment]
BTW, when the threshold is set to 100% (the use case that the originally wanted to fix), the code tried sending to a closed channel and triggered a panic.

**Comment by thanasisk** [comment]
does this bug applies to v1.11.2 ? or v.1.11.2 includes the fix?
