### ISSUE TITLE
nlb on aws should filter instance types for target groups

### ISSUE THREAD

**Issue by dng-dev** [kubernetes/kubernetes#66044]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:
The Service with the annotation NLB produced an error 
`
  Warning  CreatingLoadBalancerFailed  3s (x6 over 25m)   service-controller  (combined from similar events): Error creating load balancer (will retry): failed to ensure load balancer for service monitoring/cluster-monitoring-nginx-ingress-controller: Error registering targets for load balancer: "InvalidTarget: Targets {i-0f505894b2aa7583a} are not supported\n\tstatus code: 400, request id: dd4c8ec9-848c-11e8-b50b-5f8d3df2fe11
**What you expected to happen**:

The m2 should be ignored during selection of the target groups or added by ip which is supported by aws nlb.

**How to reproduce it (as minimally and precisely as possible)**:

Simple create an nginx-ingress with nlb service anotation. Have 2 Nodes running one m2.xxxx and one c4.xxxx

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
aws eks
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Here a snipped from the aws documentation.

You cannot register instances by instance ID if they have the following instance types: C1, CC1, CC2, CG1, CG2, CR1, G1, G2, HI1, HS1, M1, M2, M3, and T1. You can register instances of these types by IP address.

**Comment by micahhausler** [comment]
This is something we debated earlier on https://github.com/kubernetes/kubernetes/issues/56700. I think the solution here is to add the label
```
alpha.service-controller.kubernetes.io/exclude-balancer: true
```
to nodes of older instance types. 

Can we close this issue out?

**Comment by dng-dev** [comment]
@micahhausler yes we can close it with a reference to the other ticket i would say. 

#57249 will cover this issue
