### ISSUE TITLE
Critical pods should be restricted to a set of configurable namespaces.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#66042]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

Critical pods should be restricted to a set of configurable namespaces instead of kube-system.

More info: https://github.com/kubernetes/kubernetes/issues/65557#issuecomment-400885001

/assign @aveshagarwal 

/cc @sjenning @derekwaynecarr @liggitt @bsalamat

**Comment by seh** [comment]
Does the use of [the "ResourceQuota" admission controller](https://kubernetes.io/docs/concepts/policy/#limit-priority-class-consumption-by-default) satisfy this request adequately? What prevents us from removing the "kube-system" namespace restriction added in #65593?

**Comment by lbernail** [comment]
We'd be very interested in a way to achieve that too. Our use case is the following:
- we run large clusters (1000+ nodes)
- we have a few system daemonsets (5+)
- having all these pods in the same namespace would create too many pods in the kube-system namespace

Using explicit white-listing or prefix white-listing would both work for us

@yastij I saw you commented on the PR, do you know why it was closed?

**Comment by yastij** [comment]
@lbernail - the PR was closed in favor of a more generic approach which is the schedulingPolicy ref kubernetes/enhancements#683 I'm kicking in this for 1.15, the proposal still need to be updated to reflect latest discussions.

**Comment by lbernail** [comment]
@yastij : thanks a lot. This means that for all releases between 1.12 and 1.15, `system-node-critical` and `system-cluster-critical` will be limited to kube-system, right?

**Comment by yastij** [comment]
@lbernail - yes

**Comment by hobbytp** [comment]
> @yastij : thanks a lot. This means that for all releases between 1.12 and 1.15, `system-node-critical` and `system-cluster-critical` will be limited to kube-system, right?


But from [Guaranteed Scheduling For Critical Add-On Pods
](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical), it says "Prior to v1.11, critical pod has to run in the kube-system namespace, this restriction was removed after v1.11 and pod in any namespace can be configed as a critical pod by the following either way:xxx", so the description is incorrect?

**Comment by Morriz** [comment]
Yes, the docs say otherwise indeed. Sad that we can't use the annotation and not place loads in other namespaces :(
Seems it's better to turn it off until 1.15 is GA
