### ISSUE TITLE
Fluentd kubernetes filtering logs based on log level

### ISSUE THREAD

**Issue by dlbarduzzi** [kubernetes/kubernetes#66050]
Hi guys...I'm new to fluentd and this may be a silly question, but I haven't found a solution so far. How can I filter kubernetes logs based on log level? For example, if I want to discard "DEBUG" logs from applications sending to Elastic Search.

**Comment by dbarduzzi** [comment]
This is not a bug, just help that I need and would like to know if anyone has implemented something like that. @kubernetes/sig-contributor-experience-bug

**Comment by CaoShuFeng** [comment]
The log line format is:
```
[IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
```

We can know whether this is a info, warning, error or fatal.

But we can't know the log level, currently.

**Comment by CaoShuFeng** [comment]
Agree this is reasonable feature request.

**Comment by zhouhaibing089** [comment]
Not sure whether this will help: https://docs.fluentd.org/v0.12/articles/filter_grep, you can add an `exclude` for DEBUG logs pattern.

**Comment by ceshihao** [comment]
A Fluentd filter plugin

https://github.com/Soluto/fluent-plugin-kubernetes-log-level

**Comment by dbarduzzi** [comment]
@zhouhaibing089 found that yesterday and implemented. It does not work with v0.12, but it does with v1.1 and newer. So, for now I will be filtering the logs using the "grep" config.

**Comment by dims** [comment]
/close

@dlbarduzzi please reopen if needed
