### ISSUE TITLE
Custom OwnerReference definitions to allow easy cleanup

### ISSUE THREAD

**Issue by YP28** [kubernetes/kubernetes#66068]
/kind feature

**What happened**:
We'd like to specify custom `ownerReferences` in our resources.

At this moment, we deploy every branch on our development cluster automatically. We just now tried doing the same for a new application, however, that application includes `ClusterRole`s and `ClusterRoleBinding`s. These are cluster scoped, and will not be automatically cleaned by our cleaner that just deletes the entire branch namespace.

We'd like to just specify on the `ClusterRole` and `ClusterRoleBinding` that the owner of those resources is the namespace, and have it cleaned together with the rest of the deployment. Right now, it is not possible due to the resources being cluster-scoped, and the ownerReference requiring a `uid`. 

**Anything else we need to know?**:
/

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration
Google Kubernetes Engine, `n1-standard-1` and `n1-standard-2` instances.
- OS (e.g. from /etc/os-release):
/
- Kernel (e.g. `uname -a`):
/
- Install tools:
/
- Others:
/

**Comment by YP28** [comment]
@liggitt do you see any way to work around this?

I assume it's not possible to make the apiserver dynamically retrieve the uid of the parent resource on-apply?

**Comment by caesarxuchao** [comment]
Requiring ownerRef.UID makes it impossible to describe ownerships in static config files. If we were going to re-implement the garbage collector from scratch, I would make ownerReference.UID optional.

**Comment by liggitt** [comment]
> If we were going to re-implement the garbage collector from scratch, I would make ownerReference.UID optional.

What would you want GC do without that data:
* leave uid empty and be vulnerable to delete/recreate scenarios?
* fill in missing uids with actual uids via GC controller on first observation?

**Comment by caesarxuchao** [comment]
> leave uid empty and be vulnerable to delete/recreate scenarios?

If the user expects the dependents to be deleted with the original owner, they'll have to use "foregroundDeletion".

If the user wants the recreated owner to adopt the dependents, then we can introduce "ttl after owner is deleted" concept, and as long as the user successfully recreates the new owner within TTL after when the old owner is deleted, the dependents will survive, and there will be no race.

Note that today to do adoption, ownerReferences need to be removed by GC, and then a controller needs to add ownerReferences pointing to the recreated owner.

> fill in missing uids with actual uids via GC controller on first observation? (still racy and vulnerable to delete/recreate)

Agree it's racy. And it doesn't support the delete/recreate adoption use case.

**Comment by YP28** [comment]
Thanks a lot for the effort guys.

We currently have a workaround that is alright for us. We deploy the namespace first (as we always do), then grep it's `uid` and just paste it in the dependants during deployment.

**Comment by YP28** [comment]
Since it's no longer an issue for what I'm working on, I'll close this for now. 

/close
