### ISSUE TITLE
Flakes in kubemark-scale with RC creation

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#66072]
It seems like load test is occasionally flaking in kubemark-5000 job due to errors like:

```
creating { ReplicationController} load-small-5509
Expected error:
    <*errors.errorString | 0xc42009b540>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

This happened twice in the last week:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1083
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1094

/assign @mborsz 
If you could take a look into it.

cc @kubernetes/sig-scalability-bugs

**Comment by mborsz** [comment]
Sure,
I see in logs
```
Created replication controller with name: load-small-5509, namespace: e2e-tests-load-30-nodepods-10-vhdqm, replica count: 5
```
but can't see anything like 
```
load-small-5509 Pods: 5 out of 5 created, 5 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
```

Which suggests that the issue happens somewhere  between them.

I think it's something with 'NewPodStore'
https://github.com/kubernetes/kubernetes/blob/dacb9ad6920a533d08711b7f7e06ba01f2851a08/test/utils/pod_store.go#L40-L66

Tomorrow will continue debugging.
