### ISSUE TITLE
kubeadm config image list: the image k8s.gcr.io/pause-amd64:3.1 should named k8s.gcr.io/pause:3.1

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#66101]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
when l use the kubeadm init cluster, first l use: kubeadm config image list to list the images of dependense. so l pulled those images by myself. notic: k8s.gcr.io/pause-amd64:3.1, but kubeadm init, l view the kubelet log, it's to pull k8s.gcr.io/pause:3.1. 
**What you expected to happen**:
kubeadm config image list: 
the image:  k8s.gcr.io/pause-amd64:3.1 should be k8s.gcr.io/pause:3.1
**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: hardware configuration
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:

**Comment by nikhita** [comment]
This is fixed in https://github.com/kubernetes/kubernetes/pull/65920 by @dims! :tada: 

Closing.
/close

**Comment by huangjiasingle** [comment]
@nikhita thank you !
