### ISSUE TITLE
IPVS is not working with hostport 

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#66103]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.11.0
- **Cloud provider or hardware configuration**: None
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 
- **Others**:

## What happened?

I'm trying to set up a kubernetes (v1.11.0) cluster. Here is the setting of the cluster:
1. Enable IPVS in kube-proxy
2. Use hostport for nginx ingress controller. Deloy nginx ingress controller on the same node as kubenetes core services.

Host port 443 and 80 of nginx ingress controller is conflict with kubernetes (kube-apiserver) service's port 443 and 80. Nginx ingress controller keeps crashloopback because failed to connect to kube-apiserver. I even cannot run ` telnet 10.0.0.1 443`.

Try to find the root cause. Here is the iptable rules generated
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
cali-PREROUTING  all  --  anywhere             anywhere             /* cali:6gwbT8clXdHdC1b1 */
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
cali-OUTPUT  all  --  anywhere             anywhere             /* cali:tVnHkvAo15HuiPy0 */
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
cali-POSTROUTING  all  --  anywhere             anywhere             /* cali:O3lYWMrLQYEMJtB5 */
CNI-HOSTPORT-SNAT  all  --  localhost           !localhost
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
MASQUERADE  all  --  172.17.0.0/16        anywhere
```

 The `CNI-HOSTPORT` related iptable rules are on top of `KUBE-SERVICES` rule.  As you seen the pre-routing rule

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
cali-PREROUTING  all  --  anywhere             anywhere             /* cali:6gwbT8clXdHdC1b1 */
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
```

Every time I call `https://10.0.0.1:443` it will match `CNI-HOSTPORT-DNAT` rule to redirect to nginx ingress service. That's why I got failure when calling kubernetes api with service ip.

## What you expected to happen?
Should always take `KUBE-SERVICES` rule first rather than `CNI-HOSTPORT-DNAT`. So the pre-routing rule should be like

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
cali-PREROUTING  all  --  anywhere             anywhere             /* cali:6gwbT8clXdHdC1b1 */
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
CNI-HOSTPORT-DNAT  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
```

## How to reproduce it (as minimally and precisely as possible)?
See above append.

## Anything else we need to know?

When I restarted kube-proxy, the iptable rules were generated correctly. Nginx ingress controller now started successfully.

**Comment by liqlin2015** [comment]
@m1093782566 @Lion-Wei @honkiko Have you guys get into this issue? Any comments?

**Comment by honkiko** [comment]
What is expected to reach by accessing 10.0.0.1 443 ?  Is 10.0.0.1 node IP or ClusterIP?

**Comment by liqlin2015** [comment]
10.0.0.1 is the clusterIP of kubernetes service.

```
# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   1h
```

**Comment by m1093782566** [comment]
cc @Lion-Wei

**Comment by Lion-Wei** [comment]
https://github.com/kubernetes/kubernetes/issues/61938
I think this is same issue, and should have been solved in 1.11. : )

**Comment by liqlin2015** [comment]
@Lion-Wei They are similar issues. And issue #61938 is fixed in Kubernetes 1.11.0.

You can see my append above. It's the sequence of PREROUTING of iptable rules. We cannot make sure `KUBE-SERVICES` rule is always ahead of `CNI-HOSTPORT-DNAT` rule. I think they are generated by different process. `KUBE-SERVICES` is generated by kube-proxy, and `CNI-HOSTPORT-DNAT` is generated by CNI plugin. You cannot make assumption kube-proxy is always started before cni plugin. However they do have conflict with each other.

**Comment by Lion-Wei** [comment]
That's right. Since `KUBE-SERVICES` and `CNI-HOSTPORT-DNAT` is generated by different process, we can't guarantee the order, even using `iptables -I`.
On kube-proxy side, clusterIP addresses have to be treated as local, so ipvs rules can work. On cni plugin side, match `dst-type=local` to do DNT for hostPort pod also very reasonable.
So, for now, the only way I have to solve this problem is make sure `KUBE-SERVICES` is in the top of `PREROUTING` chain. . .

**Comment by xujieasd** [comment]
emm... seems currently kube-proxy cannot guarantee that `KUBE-SERVICES` is always at the top.
Because kube-proxy only ensure that `KUBE-SERVICES` exists in  `PREROUTING` chain (or in other chain) for every round of sync even if `KUBE-SERVICES` is created by `iptables -I`.
So for these iptables rules really need to be `Prepended`, maybe we need a function to ensure the order (currently kube-proxy just use `EnsureRule`)

**Comment by liqlin2015** [comment]
Any idea to fix this issue in Kubernetes 1.11.1?

**Comment by liucimin** [comment]
I think dont use kube-proxy and use cni plugin to hold these iptables problem is a good way.

**Comment by Lion-Wei** [comment]
@liucimin Can you be more specific?

**Comment by m1093782566** [comment]
> So for these iptables rules really need to be Prepended, maybe we need a function to ensure the order (currently kube-proxy just use EnsureRule)

Make sense. I would love to see a Heuristic prototype :)

**Comment by Lion-Wei** [comment]
@liqlin2015 How can I reproduce this problem? Just build a cluster and use calico as cni plugin?

**Comment by Lion-Wei** [comment]
https://github.com/kubernetes/kubernetes/blob/cdf7f2dbf54aa6e2ec264baa61ace145e39ffe10/pkg/proxy/ipvs/proxier.go#L1397-L1402

**Comment by liucimin** [comment]
Don't you use Ipvs now? and the hostport configuration is configured by docker into iptables.‘
I dont think change the kube-proxy iptables can fix this problem.

**Comment by xujieasd** [comment]
@Lion-Wei , yes, you are right.  
kube-proxy can make sure that `KUBE-SERVICES` rule at the top only for the first time `KUBE-SERVICES` rule is created.  
maybe a simple fix solution is after `EnsureRule`, check the rules sequence, if `KUBE-SERVICES` rule is not at the top, delete the rule and re-prepend the rule

**Comment by liucimin** [comment]
@Lion-Wei 
Yes,Some cni plugin may think the service ip or host port should it self to generate a iptables chain and rule
to hold this problem.
If we just make the proxy's iptables rule on the top of preroute chain.We may fix this problem but maybe cause other problems.
In my opion,i want the @liqlin2015 to give us the  ingress  config .
And would do you like to give us the whole iptables rule to let me know the calico's rule.
And the ipset list, ipvs?
Let's to find out why the calico chain above the KUBE-SERVICES make ur service wrong.
In my env, i use contiv and ipvs dont have the problem.
Thx.

**Comment by liucimin** [comment]
@m1093782566 
Thx for your response.And i get it. Thx~

**Comment by Lion-Wei** [comment]
I think check rules sequence not gonna work. Normally prepend the rule is enough to make sure it is on the top, but kube-proxy have a period to sync rules, and beyond this period, we can't make sure what might happen.
> maybe a simple fix solution is after EnsureRule, check the rules sequence, if KUBE-SERVICES rule is not at the top, delete the rule and re-prepend the rule

And AFAIK, cni only sync nodeport related rules once on pod create, so even though calico prepend the `cali-PREROUTING` rule, kube-proxy should make `KUBE-SERVICE` on the top after next sync. 
@liqlin2015 Is this work happened?

**Comment by xujieasd** [comment]
@Lion-Wei 
> so even though calico prepend the cali-PREROUTING rule, kube-proxy should make KUBE-SERVICE on the top after next sync.

I don't think it's true, please check the implementation of `EnsureRule`
```
// EnsureRule checks if the specified rule is present and, if not, creates it.  If the rule existed, return true.
EnsureRule(position RulePosition, table Table, chain Chain, args ...string) (bool, error)
```
`EnsureRule` will first call `checkRule` to check whether rule exists, if exists, just return true.
so if calico prepend rule after kube-proxy. `KUBE-SERVICE` could not be on the top

**Comment by seanlei** [comment]
> basically, ipvs nat mode will not do snat - i know it is confused but that is true.
@m1093782566 how you find that nat mode will not do snat?  and why?

**Comment by gyliu513** [comment]
@m1093782566 any plan to fix this?

**Comment by m1093782566** [comment]
xref: #66590

**Comment by r7vme** [comment]
we affected by this issue too. usually restart of kube-proxy does the job.

**Comment by calvix** [comment]
+1

**Comment by dannyk81** [comment]
Hi @m1093782566,

After hitting this in a new cluster deployment (using ipvs and calico), I've been going over all the various linked issues/PRs/mailing lists discussions and seems like there's no obvious concensus on how to approach to fix this.

My understanding is that #66590 is not going to be accepted (also not clear if it will solve the issue).

Can you share if there are any news about this? we were following IPVS and been meaning to switch to it, once it became GA it seemed like a relatively safe way to go.

Unfortunately we rely on hostPort quite a bit and without fixing this IPVS is blocked 😞 

Hope you could share some good news 🙏

**Comment by calvix** [comment]
@dannyk81 We had a similar issue with ingress controller and hostPorts + ipvs, in the end, we resolved it with using `ServiceType: NodePort` with statically assigned ports for each service instead of hostPorts (as it can give quite similar functionality, service available on nodeIP + port).

Maybe you can find a workaround with `NodePort` for your problem too.

**Comment by dannyk81** [comment]
Thanks @calvix! indeed we've been discussing NodePort as a possible workaround.

I'm actually going to test this now to play around with, but there are few concerns here:

1) NodePort (even statically assigned ones) are only available from specific range (default 30000-32767), however we need to expose ports 80, 443, 3311, etc. since our external LB is transparently forwarding traffic to these ports.

I suppose, one way to work around this is to add 30000 to the port numbers (30080, 30443, 33311, etc..) and have our external LB manipulate incoming requests to port 80 to be forwarded to port 30080 (as an example).

2) NodePort is adding an additional LB hop that we would not have had with hostPort and would be kind of a shame to introduce this extra complexity.


Would like to hear how you're handling this and your experience.

**Comment by calvix** [comment]
> NodePort (even statically assigned ones) are only available from specific range (default 30000-32767), however we need to expose ports 80, 443, 3311, etc. since our external LB is transparently forwarding traffic to these ports.

We have LB config with proper port mapping ( port 80 -> 30010, port 443 -> 30011, and etc ..) And each service always uses the same LB port - NodePort combination and that works just fine for us.

> NodePort is adding an additional LB hop that we would not have had with hostPort and would be kind of a shame to introduce this extra complexity.

That is true, but the packet is just forwarded, it's not like having there some HTTP proxy. Anyway, we don't run latency sensitive workload so we can live with having some small delay because of the extra hop.

**Comment by sepich** [comment]
>NodePort is adding an additional LB hop that we would not have had with hostPort and would be kind of a shame to introduce this extra complexity.

Another way to avoid this hop, is to run nginx as
```
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```
This way it does not conflict with `kubernetes.deafult.svc.cluster.local:443` and still listening directly on Node:443.

**Comment by dannyk81** [comment]
thanks @sepich!

We did try switching to `hostNetwork` briefly and seem to have encountered the same/similar issue, tbh didn't investigate much but will try again 👍

**Comment by nickychow** [comment]
#3892

**Comment by thockin** [comment]
iptables rule sequencing should be fixed now in all active branches.

**Comment by dannyk81** [comment]
wow! great news @thockin

Can you perhaps point to the PR/Fix? do you know which versions will have this fix?

**Comment by dannyk81** [comment]
ping @thockin :pray:
