### ISSUE TITLE
Listing existing algorithm providers in scheduler

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#6612]
Currently kube-scheduler can not show/list existing algorithm providers. Although there is only one algorithm provider now, listing available algorithm providers will be necessary in future.

**Comment by jianzhangbjz** [comment]
Hi @HaiyangDING Seems based on the latest k8s version, using "kube-scheduler --help" command, still show the only "DefaultProvider" algorithm, not included others, as "ImageLocalityPriority", "NewNodeLabelPriority", etc... How can I add myself algorithm into the "--help" show list?
```
kube-scheduler --help
--algorithm-provider="DefaultProvider": The scheduling algorithm provider to use, one of: DefaultProvider
```

**Comment by HaiyangDING** [comment]
@jianzhangbjz 

Hi, a 'algorithm provider' is essentially a 'set' of scheduling rules (i.e. a set of predicates and prioritizers). Here are my thought based on my understanding of your question.

1. To include other predicates and/or priorities that already exist in the library, you need to add them as part of the default scheduler's scheduling policy, namely, edit `./plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go`. You can take the codes there as  an example of how to do this.

2. To have another `algorithm provider` other than `DefaultProvider`, you need to write a new algorithm scheduler package other than package `defaults`. But be ware, as far as I know, k8s does not support multiple scheduling policies yet, i.e. a pod can not specify which scheduling policy to follow even if you have defined another scheduling policy.

To see more about the modifying the scheduler, please see [scheduler](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/scheduler.md) and [scheduler\_algorithm](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/scheduler_algorithm.md)

I hope it helps.

**Comment by jianzhangbjz** [comment]
@HaiyangDING Thanks! I will have a try according to your advise.

**Comment by HaiyangDING** [comment]
BTW, I think it is OK to close it. Closing now.
