### ISSUE TITLE
Can't delete the 'Unknown' pod from dead node

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes/kubernetes#66125]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
When node becomes 'NotReady', the 'Unknown ' pod can't be deleted.

\# kubectl get pod kubernetes-dashboard-db4db8c77-4qqvm -n kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-db4db8c77-4qqvm   1/1       Unknown   0          3h
\# kubectl delete pod kubernetes-dashboard-db4db8c77-4qqvm -n kube-system 
pod "kubernetes-dashboard-db4db8c77-4qqvm" deleted
\# kubectl get pod kubernetes-dashboard-db4db8c77-4qqvm -n kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-db4db8c77-4qqvm   1/1       Unknown   0          3h
\# kubectl delete pod kubernetes-dashboard-db4db8c77-4qqvm --force --grace-period=0 -n kube-system 
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "kubernetes-dashboard-db4db8c77-4qqvm" deleted
\# kubectl get pod kubernetes-dashboard-db4db8c77-4qqvm -n kube-system
Error from server (NotFound): pods "kubernetes-dashboard-db4db8c77-4qqvm" not found

**What you expected to happen**:
node controller manager can delete pod from dead node.

**How to reproduce it (as minimally and precisely as possible)**:
when node's status become 'NotReady', it can be reprodeced

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: openstack
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/issues/35145#issuecomment-254917371 for why the node controller does not hard delete pods

if the user wants to give up pod safety and manually delete the pods, they can use `kubectl delete --force --grace-period=0 ...`

**Comment by smarterclayton** [comment]
Or they can delete the node object, which will cause the pods to be force deleted.
