### ISSUE TITLE
Conformance Discussion to promote e2e tests which validate initContainer PodSpec

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#66124]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Evaluating e2e tests based on available [PodSpecs](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2473) options which are covering important aspects with user scenarios and **_eligible to promote for conformance_**.

**What you expected to happen**:
These 4 e2e tests evaluate different [PodPhase](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2068) and [PodStatus](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2715) based on [InitContainerStatuses](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2750).

1. InitContainer [NodeConformance] should invoke init containers on a RestartNever pod
> - Looks for **PodPhase=Succeed** (all pods terminated with exit status 0)
> - Pod is initialized (means all init container started)

2. InitContainer [NodeConformance] should invoke init containers on a RestartAlways pod
> - Looks for **PodPhase=Running** (atleast 1 container is running)
> - Pod is initialized

3. InitContainer [NodeConformance] should not start app containers if init containers fail on a RestartAlways pod
> - Looks for **PodPhase=Pending**
> - Restarted Pod atleast 2 times

4. InitContainer [NodeConformance] should not start app containers and fail the pod if init containers fail on a RestartNever pod
> - Looks for **PodPhase=Failed**
> - One of container status is waiting

**Anything else we need to know?**:
1. Please comment, **_Are these tests good to promote for conformance_** or do we need to look on other aspects as well ?
2. Below are observed api endpoint hits during tests execution. (API coverage improvement) -

_InitContainer [NodeConformance] should invoke init containers on a RestartNever pod_
```
get /api/v1/namespaces/e2e-tests-init-container-4zdws/pods/pod-init-14227e97-687f-11e8-a0a8-7cd30ac64302
update /api/v1/namespaces/e2e-tests-init-container-4zdws/pods/pod-init-14227e97-687f-11e8-a0a8-7cd30ac64302/status
list /api/v1/namespaces/e2e-tests-init-container-4zdws/pods
watch /api/v1/namespaces/e2e-tests-init-container-4zdws/pods
create /api/v1/namespaces/e2e-tests-init-container-4zdws/pods
create /api/v1/namespaces/e2e-tests-init-container-4zdws/pods/pod-init-14227e97-687f-11e8-a0a8-7cd30ac64302/binding
deletecollection /api/v1/namespaces/e2e-tests-init-container-4zdws/pods
get /api/v1/namespaces/kube-system/pods/heapster-v1.5.3-7c79d479bb-xnp4h
get /api/v1/namespaces/kube-system/pods/metrics-server-v0.2.1-7486f5bd67-jt2d2
```

_InitContainer [NodeConformance] should invoke init containers on a RestartAlways pod_
```
get /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods/pod-init-70809153-6892-11e8-a0a8-7cd30ac64302
update /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods/pod-init-70809153-6892-11e8-a0a8-7cd30ac64302/status
list /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods
get /api/v1/namespaces/kube-system/pods/heapster-v1.5.3-7c79d479bb-xnp4h
deletecollection /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods
get /api/v1/namespaces/kube-system/pods/metrics-server-v0.2.1-7486f5bd67-jt2d2
watch /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods
create /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods
create /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods/pod-init-70809153-6892-11e8-a0a8-7cd30ac64302/binding
delete /api/v1/namespaces/e2e-tests-init-container-qgz9s/pods/pod-init-70809153-6892-11e8-a0a8-7cd30ac64302
```
_InitContainer [NodeConformance] should not start app containers if init containers fail on a RestartAlways pod_
```
get /api/v1/namespaces/e2e-tests-init-container-h9d8n/pods/pod-init-69f263f4-68cb-11e8-a0a8-7cd30ac64302
update /api/v1/namespaces/e2e-tests-init-container-h9d8n/pods/pod-init-69f263f4-68cb-11e8-a0a8-7cd30ac64302/status
get /api/v1/namespaces/kube-system/pods/metrics-server-v0.2.1-7486f5bd67-jt2d2
get /api/v1/namespaces/kube-system/pods/heapster-v1.5.3-7c79d479bb-xnp4h
create /api/v1/namespaces/e2e-tests-init-container-h9d8n/pods/pod-init-69f263f4-68cb-11e8-a0a8-7cd30ac64302/binding
delete /api/v1/namespaces/e2e-tests-init-container-h9d8n/pods/pod-init-69f263f4-68cb-11e8-a0a8-7cd30ac64302
```

_InitContainer [NodeConformance] should not start app containers and fail the pod if init containers fail on a RestartNever pod_
```
get /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods/pod-init-9de05f1c-6880-11e8-a0a8-7cd30ac64302
update /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods/pod-init-9de05f1c-6880-11e8-a0a8-7cd30ac64302/status
list /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods
get /api/v1/namespaces/kube-system/pods/metrics-server-v0.2.1-7486f5bd67-jt2d2
watch /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods
create /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods
create /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods/pod-init-9de05f1c-6880-11e8-a0a8-7cd30ac64302/binding
deletecollection /api/v1/namespaces/e2e-tests-init-container-bxcf6/pods
get /api/v1/namespaces/kube-system/pods/heapster-v1.5.3-7c79d479bb-xnp4h
```

/area conformance
cc @AishSundar @dchen1107

**Comment by mgdevstack** [comment]
@kubernetes/sig-node-feature-requests

**Comment by spiffxp** [comment]
@mgdevstack Go ahead and open a PR to ask this question.  Yes == PR is merged, no == PR is closed (or amended to doc the reason these tests can't be promoted)
