### ISSUE TITLE
Failing Test: [sig-aws] Kops aws tests are failing [BeforeSuite]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66132]
# Failing Jobs
[sig-release-master-blocking#aws](https://k8s-testgrid.appspot.com/sig-release-master-blocking#aws)

# Failing Tests
[pull-kubernetes-e2e-kops-aws](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws)

# Triage Results
[Kops BeforeSuite](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=kops&test=BeforeSuite)

The tests are currently failing in sig-release-master-blocking

/priority failing-test
/sig aws
/sig testing
/priority important-soon
/milestone v1.12
/cc @tpepper @AishSundar

**Comment by nckturner** [comment]
Who actually owns these tests/has access to the infrastructure/etc? I'd be happy to help out but I don't know where to start.

**Comment by mohammedzee1000** [comment]
Tests seem to have stabilised, closing for now
/close

**Comment by mohammedzee1000** [comment]
/reopen
These tests are failing again

**Comment by mohammedzee1000** [comment]
Tests are back to green, closing
/close
