### ISSUE TITLE
pkg/util/mount: Error when mount source in /proc/self/mountinfo is empty

### ISSUE THREAD

**Issue by mrostecki** [kubernetes/kubernetes#66134]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When `/proc/self/mountinfo` contains any line with empty mount source, kubelet fails with the following error:

```
F0712 12:18:16.047292    4663 server.go:260] failed to run Kubelet: Error found less than 3 fields post '-' in "269 68 0:108 / /tmp/bb rw,relatime shared:147 - tmpfs  rw"
```

**What you expected to happen**:

This error shouldn't occur and mountinfo lines with empty mount source should be parsed properly.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ mkdir /tmp/bb
$ sudo mount -t tmpfs "" /tmp/bb
$ ./hack/local-up-cluster.sh
[...]
W0712 12:18:17]: kubelet terminated unexpectedly, see /tmp/kubelet.log
```

**Anything else we need to know?**:

This error occurs in many tools which are parsing mountinfo, i.e. util-linux, runc. Links for patches and pull requests:

https://www.spinics.net/lists/linux-fsdevel/msg128896.html
https://github.com/opencontainers/runc/pull/1829
https://github.com/opencontainers/runtime-tools/pull/652

There is also an attempt to fix that issue properly on kernel side - to use `none` string when source is empty:

https://patchwork.kernel.org/patch/10349095/

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: none
- OS (e.g. from /etc/os-release): openSUSE Tumbleweed
- Kernel (e.g. `uname -a`): Linux latitude 4.17.2-1-default #1 SMP PREEMPT Sat Jun 16 10:58:03 UTC 2018 (ddde22d) x86_64 x86_64 x86_64 GNU/Linux
- Install tools: `./hack/local-up-cluster.sh`
- Others:

**Comment by dims** [comment]
@mrostecki what about one in moby? ( https://github.com/moby/moby/blob/master/pkg/mount/mountinfo_linux.go#L12-L107 ) i believe that's where the other ones originated from. Also see that the one in moby was updated. Guess we need to check if that still has the problem you are attempting to fix as well

https://github.com/moby/moby/commit/c611f18a7f16d8aa878a5a5c7537d23a0937c40a

**Comment by mrostecki** [comment]
The implementation of mountinfo parser which is working with empty sources is i.e. in Cilium:

https://github.com/cilium/cilium/blob/master/pkg/mountinfo/mountinfo.go

That's because `strings.Fields` trimps multiple spaces, using `strings.Split(s, " ")` splits by one space, which is more convenient for parsing mountinfo.

Since there is a lot of software written in Go which is using mountinfo and the `mountInfo` struct in Kubernetes is quite similar to the struct in Cilium, I was wondering whether it would make sense to create some mountinfo library which could be vendored in Kubernetes, Cilium and other projects.

@cofyc @jsafrane What do you think?

**Comment by mrostecki** [comment]
@dims The implementation in Moby looks good, they're using `strings.Split` and doing that in similar way as Cilium. I will check it manually later.

Although running container with Moby/Docker after creating a mount with empty source will fail, because runc is parsing mountinfo incorrectly.

**Comment by cofyc** [comment]
`/proc/<pid>/mounts` has same issue too.

`util-linux` has [libmount library](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.21/libmount-docs/) which contains mountinfo/mounts parsers, probably we can have a mount parser library in go for same purpose.

**Comment by mrostecki** [comment]
>`util-linux` has libmount library which contains mountinfo/mounts parsers, probably we can have a mount parser library in go for same purpose. I think it's a good idea.

I created a repo with mountinfo parser based on Cilium, Kubernetes and Moby: https://github.com/mrostecki/gomountinfo

Please take a look and let me know what do you think. I will try to take care of godocs and add `/proc/<pid>/mounts` support soon (for now it only handles `self`).
