### ISSUE TITLE
kubectl apply --dry-run --recursive  experiences a race condition when applied to a directory

### ISSUE THREAD

**Issue by Rachel-ResDiary** [kubernetes/kubernetes#66130]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

I ran `kubectl apply --recursive --dry-run -f .` in a directory with sub-folders. The order in which the yaml files were applied did not reflect their alphabetical order. Instead, longer running files could finish later than shorter running files whose filename was alphabetically later. e.g. : `aaa.my-k8s-file.yaml` might finish later than `zzz.my-k8s-file.yaml`. If `zzz.my-k8s-file.yaml` depends on objects created by `aaa.my-k8s-file.yaml`, this causes the dry-run to fail. When the equivalent `kubectl apply --recursive -f .` command would have succeeded.

**What you expected to happen**:

I expected the yaml files to be run in alphabetical order, and for each file to complete being dry-run applied before attempting to apply the next one. So that if some yaml files depended upon objects that are created by other yaml files, I could ensure that the dependent yaml files were run first by naming them appropriately. 

**How to reproduce it (as minimally and precisely as possible)**:

You need a directory containing yaml files that are intended to be run in order. But where files that are alphabetically first take longer to run than those that come alphabetically later. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (AKS cluster version): 1.9.6 
- Kubectl version: 1.10.2
- Cloud provider or hardware configuration: Azure Kubernetes Services
- OS (e.g. from /etc/os-release): Running kubectl command on Windows 10. Sorry, not sure what AKS is running.
- Kernel (e.g. `uname -a`): Sorry, I don't know. Internal to AKS.
- Install tools: chocolatey
- Others:

@kubernetes/sig-wg-apply-bugs

**Comment by Rachel-ResDiary** [comment]
@wg-apply

**Comment by ResDiaryLewis** [comment]
I'd just like to add, this happened because we were dry running CRDs and resources that depended on these CRDs. We're trying to validate our Kubernetes YAML.
You can replicate this by making a folder with a CRD yaml with `name=test_crd` and a resource with `Kind=test_crd`, then running `kubectl apply -f . -R --dry-run`. This succeeds in creating the resource *if* the CRD yaml file is created first. 
If the CRD yaml file is large, like the [AlertManager CRD](https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/alertmanager.crd.yaml), then it can take longer to create the CRD than the resource dependent upon it.
Please let me know:
- if there's a better way to validate Kubernetes YAML
- if my explanation needs more explaining

**Comment by liggitt** [comment]
doesn't `--dry-run` skip actually creating objects? what would you expect the dry run creation of a custom resource to do if the CRD doesn't actually exist on the server?

**Comment by Rachel-ResDiary** [comment]
I've tested doing a **dry-run** with two files, one of which creates a CRD, the other of which consumes it. That works, but only because the race condition lands in my favour in that limited scenario. An object created by one Yaml file is available to another within the same **dry-run**.

In answer to your question, I'd expect **dry-run** in combination with **recursive** to work sort-of-like a database transaction. i.e., a repeatable, all-or-nothing success or failure. Unlike applying **dry-run** on the files one at a time (which would obviously fail, as objects in one **dry-run** wouldn't be available to another.)

**Comment by liggitt** [comment]
> An object created by one Yaml file is available to another within the same dry-run (provided you also use recursive.)

That is not accurate. Dry run doesn't set up any inter-object relationships within the run, it simply skips all writes to the server. I expect this is only working for you in scenarios where the CRD was actually already created previously on the server.

> In answer to your question, I'd expect dry-run in combination with recursive to work sort-of-like a database transaction. i.e., a repeatable, all-or-nothing success or failure. Unlike applying dry-run on the files one at a time (which would obviously fail, as objects in one dry-run wouldn't be available to another.)

that is not what --dry-run does. it simply skips writes to the server. every individual object in every file is processed individually.

**Comment by ResDiaryLewis** [comment]
We tested this on a cluster that had never had the CRD applied to it before and you're correct. However, it succeeds sometimes on our cluster that has previously had the CRD on it. We then used `kubectl proxy` on that cluster and saw that a reference to `/apis/monitoring.coreos.com` still existed despite deleting all CRDs. Could this be related?

Thanks for helping. Rachel said she'd write this up in more detail soon.

**Comment by Rachel-ResDiary** [comment]
@liggitt You're right. I'm not sure why, but this appeared to work for me, because a cluster on which I had _previously_ applied then deleted a CRD still seemed to have it cached somewhere. This became apparently when I tried doing a similar `kubectl apply --recursive --dry-run -f .` on a completely new cluster on which the CRD had never been applied.

I'm not sure whether the fact that `dry-run` works differently on clusters with different create/delete histories is a bug in and of itself. But if so it is a separate bug. Looks like what I was trying to do with `dry-run` can't be done.

**Comment by liggitt** [comment]
> We then used kubectl proxy on that cluster and saw that a reference to /apis/monitoring.coreos.com still existed despite deleting all CRDs.

Deletion of a CRD blocks until garbage collection completes deleting all the custom instances. The CRD status should display that info in status. 

> I'm not sure why, but this appeared to work for me, because a cluster on which I had previously applied then deleted a CRD still seemed to have it cached somewhere.

discovery information is cached for a short period of time, so if you previously created and then deleted the CRDs, you might still have cached discovery information in ~/.kube/cache/discovery

> I'm not sure whether the fact that dry-run works differently on clusters with different create/delete histories is a bug in and of itself. But if so it is a separate bug.

Positive hits in the local discovery cache are not generally a problem. A failed hit triggers rediscovery.

**Comment by Rachel-ResDiary** [comment]
@liggitt Thanks very much for your help. 👍 Looks like we'll need to find another way to check whether our Yaml files with dependencies upon one another are valid as a collective. Maybe applying them to a fresh cluster overnight or something. Anyway, thanks.

**Comment by Rachel-ResDiary** [comment]
Closing: works as designed.

**Comment by apoorva11029** [comment]
Hi were you able to find a workaround to apply the dependent resources in the right order?
