### ISSUE TITLE
many orphan CLOSE_WAIT connections to kube-apiserver

### ISSUE THREAD

**Issue by mjaow** [kubernetes/kubernetes#66133]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I have a cluster with 400 nodes and 16,000 pods.Recently, I found many orphan CLOSE_WAIT connections to kube-apiserver and They block request of client. 
When I restart apiserver,everything works fine.But after several hours,orphan CLOSE_WAIT connections show and block request again.
After google,I realize that CLOSE_WAIT shows only when server donnot close connection properly.So I think it maybe it bug of kubeapiserver.

**What you expected to happen**:
I think kubeapiserver should close connection properly

**How to reproduce it (as minimally and precisely as possible)**:
In a big cluster and many connections to apiserver

**Anything else we need to know?**:
At first,There are some CLOSE_WAIT with timeout

![image](https://user-images.githubusercontent.com/8275883/42645150-e30ac07a-862f-11e8-9438-a925b6822da7.png)

.But after a while,all of them change to orphan CLOSE_WAIT

![image](https://user-images.githubusercontent.com/8275883/42644563-83899578-862e-11e8-8819-bf436a1a873f.png)

**Environment**:
- Kubernetes version (use `kubectl version`):v1.6.6
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):CentOS Linux release 7.1.1503 (Core)
- Kernel (e.g. `uname -a`):3.10.0-229.mt20171025.7.el7.x86_64
- Install tools:
- Others:

**Comment by mjaow** [comment]
Should I add apiserver (3->5)，or offline some server connected to apiserver?

**Comment by pires** [comment]
I'm seeing this more and more in busy clusters and more issues too, such as https://github.com/kubernetes/kubernetes/issues/67119 and https://github.com/kubernetes/kubernetes/issues/66820.

CLOSE_WAIT means the server is waiting on clients which have sent FIN packets to close the socket on their end. I'm wondering if this is a failure of the apiserver library or client-side, where client-go is, I believe, the most used library out there.

**Comment by mjaow** [comment]
@pires I don't think it is a failure of client-side, according to TCP/IP Illustrated v1,CLOSE_WAIT means server has got FIN from client and forget to reply ACK.
I check the code in apiserver ,it actual reply ack in normal condition.But when server is busy,it may has no time to ACK in time,so the CLOSE_WAIT shows.

**Comment by cheftako** [comment]
Wondering if https://github.com/kubernetes/kubernetes/pull/71412 fixes the problem.
