### ISSUE TITLE
Ability to use ECDSA CA key with `kubeadm init`

### ISSUE THREAD

**Issue by robodendron** [kubernetes/kubernetes#66142]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

`/etc/kubernetes/pki/ca.key` exists and is in ECDSA format:

```bash
kubeadm alpha phase certs apiserver
failure loading ca certificate authority: the private key file /etc/kubernetes/pki/ca.key isn't in RSA format
```

**What you expected to happen**:

`[certificates] Generated <key>.`

**Anything else we need to know?**:

[This](https://github.com/kubernetes/kubernetes/blob/v1.11.0/cmd/kubeadm/app/phases/certs/pkiutil/pki_helpers.go#L199-L206) seems to be the culprit.

**Environment**:
- Kubernetes version: `version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-dirty", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"dirty", BuildDate:"2018-07-12T20:19:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: QEMU VM
- OS: Fedora Atomic Host 28
- Kernel: 4.17.2-200.fc28.x86_64
- Install tools: kubeadm

**Comment by timothysc** [comment]
@robodendron - thank you for reporting - if you are still having an issue please feel free to log an issue in the kubeadm repo - https://github.com/kubernetes/kubeadm



xref: https://github.com/kubernetes/kubeadm/issues/984
