### ISSUE TITLE
Add more integration tests for volume related predicate invalidations

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#66148]
- [ ] CheckVolumeBinding predicate invalidation on PV update
  - Why we need to invalidate CheckVolumeBinding predicate cache on PV update: https://github.com/kubernetes/kubernetes/pull/66106
- [ ] invalidate CheckVolumeBindingPred/NoVolumeZoneConflictPred predicates cache when a WaitForFirstConsumer storage class is deleted
  - See https://github.com/kubernetes/kubernetes/pull/65616

Related issues:
- https://github.com/kubernetes/kubernetes/issues/56104
- https://github.com/kubernetes/kubernetes/pull/62226

**Comment by cofyc** [comment]
@kubernetes/sig-storage-feature-requests 
/assign

**Comment by dims** [comment]
@cofyc Is this for v1.12? (seems linked from https://github.com/kubernetes/kubernetes/issues/58222 which is marked 1.12)

**Comment by cofyc** [comment]
No, predicate invalidations has been added, this issue is to add integration tests for them.

**Comment by cofyc** [comment]
/close
Not needed anymore, in favor of new design https://github.com/kubernetes/kubernetes/issues/68720.
