### ISSUE TITLE
kubectl get svc streamwatcher.go:109] Unable to decode an event from the watch stream: stream error

### ISSUE THREAD

**Issue by jontis** [kubernetes/kubernetes#66153]
/kind bug

**What happened**:
Installed dask on EC2 kubernetes.
Then 
$ kubectl get svc --namespace default -w fantastic-hare-dask-jupyter
NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)        AGE
fantastic-hare-dask-jupyter   LoadBalancer   10.152.183.209   abe472d9e8676...   80:31526/TCP   21m
E0713 10:51:20.601473   22966 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 3; INTERNAL_ERROR

**What you expected to happen**:
Something that did not end in ERROR

**How to reproduce it (as minimally and precisely as possible)**:
$ helm install stable/dask
The helm installation ends with a row (that is probably different for your run, copy paste that):
for me:
You can watch the status by running 'kubectl get svc --namespace default -w fantastic-hare-dask-jupyter'
`kubectl get svc --namespace default -w fantastic-hare-dask-jupyter`

**Environment**:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

Amazon EC, conjure-up

**Comment by dberuben** [comment]
I have the same issue with my nginx-ingress-controller:

`kubectl logs nginx-nginx-ingress-controller-6d4b788f57-xfmz9`

> E0926 19:17:20.127981       9 streamwatcher.go:109] Unable to decode an event from the watch >stream: stream error: stream ID 1789; INTERNAL_ERROR
> E0926 19:18:05.888343       9 streamwatcher.go:109] Unable to decode an event from the watch >stream: stream error: stream ID 1819; INTERNAL_ERROR

**Comment by EamonKeane** [comment]
I have the same issue as @dberuben with `nginx-ingress-controller`.

**Comment by c-mccutcheon** [comment]
Same issue - Azure AKS (Kubernetes 1.10)

**Comment by EamonKeane** [comment]
FYI, last I heard (on slack) was that a fix is in testing.

**Comment by tlycken** [comment]
@EamonKeane Do you know where to go to follow the progress of that fix?

**Comment by c-mccutcheon** [comment]
What is the workaround in the interim? I cannot get nginx-ingress to work at all - it just seems to time out, seemingly due to the errors which are constantly spammed into the log.

Will it work on a previous version of Kubernetes still? Worked ok on 1.9 from what I recall.

**Comment by EamonKeane** [comment]
@tlycken @c-mccutcheon this was mentioned to me by one of the support guys on #sig-azure. Tbh, I've tried several times in the past 6 months to get AKS/acs-engine working sustainably, so my interim solution is to deploy kubeadm, metallb, and local-volume-provisioner, so no need for the azure cloud provider. I'll circle back in a month or two to see if stable. You can get a working kubeadm in a few clicks with (https://bitnami.com/stack/kubernetes-sandbox/cloud/azure) and crib from that.

**Comment by arocki7** [comment]
If you use AWS Application Load Balancer, you are likely to have this issue.
You can fix it by moving to Classic Load Balancer.
