### ISSUE TITLE
what is imagefs, how to increase imagefs?

### ISSUE THREAD

**Issue by GoodJoey** [kubernetes/kubernetes#66151]
Hi, on some nodes of my cluster, i get this error: The node is low on resource: imagefs.
I'm pretty sure there are still lots of spaces on the nodes.
So, is there any way to increase the imagefs of the nodes? Thanks very much.
my kuber version is 1.9.0

**Comment by nzoueidi** [comment]
You may look at: kubernetes/kubernetes#9518

**Comment by Nurza** [comment]
Same problem here.
Some pods on a node in my cluster (k8s 1.10.4) was evicted.

When I do a 'kubectl describe pod XXXXX':

```
Name:         xxxxxxxxxxxxxxxxxxxx
Namespace:    default
Node:         xxxxxxxxxxxxxxxxxxxx
Start Time:   Sat, 14 Jul 2018 09:11:20 +0000
Labels:       app=xxxxxxxxxxxxxxxxxxxx
Annotations:  <none>
Status:       Failed
Reason:       Evicted
Message:      The node was low on resource: imagefs.
```

**Comment by tanshanshan** [comment]
see
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy

**Comment by Nurza** [comment]
Thank you. Is this scenario possible : 

- k8s is running out of disk space in imagefs
- k8s evicts some pods to free a little disk space
- k8s do a random garbage collect to free a lot of disk space
- when I come back, there is plenty of imagefs disk space

If this is possible, it can explain my case.

Sorry if it's a stupid question, I am beginning with k8s.
