### ISSUE TITLE
Copy command no longer copies contents of folder

### ISSUE THREAD

**Issue by fspaniol** [kubernetes/kubernetes#66170]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
After upgrading to Kubectl v1.11 the `kubectl cp` command is copying the whole folder whereas, in previous versions, it would copy only its contents.

**What you expected to happen**:
To either copy the folder itself or its contents, but the behavior should not change.
I would think that copying the folder would be more intuitive, more `bash-like`.
If the option to go for is to copy the folder itself, enable an option where an user might use `/*`, like bash, to copy only its contents.

**How to reproduce it (as minimally and precisely as possible)**:
Previously:
`kubectl cp /folder/ <pod>:/` 
Where `example` has folders `1`, `2` and `3` leaves the `/` of the pod with folders `1`, `2` and `3`.

Now:
`kubectl cp /folder/ <pod>:/` 
Where `example` has folders `1`, `2` and `3` leaves the `/` of the pod with folder `example`.

**Anything else we need to know?**:
I've tried to look at ChangeLogs to check if this was documented somehow, but came up empty.
I've also tried with and without a trailing `/` on the folders name, but the behavior is unchanged, on both versions.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): RHEL

**Comment by bentito** [comment]
Can someone suggest a good workaround? For me, I prototype container handling with Docker and this has been made pretty different from the corresponding docker `cp` command, which seems like it would have been: `docker cp /tmp/sub_dir/. <docker_container_identifier>:/tmp/` which would have put all files and folders from sub_dir into /tmp on the container.

**Comment by jamstar** [comment]
i just hit this. its very annoying and took me a while to figure out what/why it broke.

**Comment by skakim** [comment]
I've hit this too. This is really annoying, and the proposed workaround looks weird (why can't we copy as we did before?). The fact that this breaking change isn't documented in the ChangeLogs is weird too.

**Comment by fspaniol** [comment]
Up
