### ISSUE TITLE
detach volumes from nodes when nodeShutdown is applied

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#66181]
As planned for 1.12 in kubernetes/features#551:

After #60009, the next step is to add the logic to the reconciler to detach the volumes when the nodeShutdown taint is applied.

/assign
/sig storage
/kind feature

looping @jingxu97

**Comment by shay-berman** [comment]
How do you know that node is Shutdown?
is it a planned shutdown or a unplanned shutdown?

**Comment by adampl** [comment]
@shay-berman AFAIK regardless of whether it's planned or not, it's detected by the cloud provider.

In case of bare-metal node it doesn't happen automatically, as there is no universal way to reliably determine if a node is powered off, so the node must be tainted as `nodeShutdown` by some external source.

**Comment by shay-berman** [comment]
@yastij   any update on this issue?

**Comment by jingxu97** [comment]
@shay-berman , I am currently working with sig-node team on handling node shut down. I will make a proposal and discuss in sig-node meeting next Tuesday. Will post the update soon.

**Comment by shay-berman** [comment]
@yastij  any update on this? is it going to be part of 1.15?

**Comment by xing-yang** [comment]
I think this can be closed now as we have non-graceful node shutdown.
