### ISSUE TITLE
Structural validation of AllowedTopologies field in StorageClass

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#66184]
/kind feature

The `AllowedTopologies` field essentially has the type `set( map(string, set[string]))`, but currently there is no validation for set and map semantics, i.e. unique elements / keys.

Having this validation at API level removes logic to validate at the volume plugin level.

~~In addition, validation will reject empty sets and empty maps.~~
edit: this check will not be added in cases where this makes it difficult to add other fields and make this field optional.

/sig api-machinery
/sig storage

**Comment by msau42** [comment]
Thanks for catching this.  Would you be able to implement this for this release?  We want to try to go beta if we can, and we won't be able to strengthen validation once that happens.

**Comment by verult** [comment]
Yes will do!
