### ISSUE TITLE
DNS resolution issue in the kube-system namespace

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes/kubernetes#66220]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig bugs
> /kind feature

**What happened**:
I have a statefulset configuration with 3 replicas. If I deploy it to the default namespace, pods can resolve each other DNS. If I deploy the same statefulset to the kube-system namespace, they can't.

**What you expected to happen**:
Pods can resolve each other in the same namespace regardless of it's name

**How to reproduce it (as minimally and precisely as possible)**:

Create a basic statefulset

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
What dns names are they attempting to resolve?

**Comment by IvanovOleg** [comment]
cassandra-*.cassandra.kube-system.svc.cluster.local

**Comment by IvanovOleg** [comment]
Sorry. It was my fault. Everything works fine.
