### ISSUE TITLE
shall we add a image gc white list that the kubelet imge gc will ignore?

### ISSUE THREAD

**Issue by zhangmingld** [kubernetes/kubernetes#66221]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
In some offline environment,we will load some images for furture use , so if the  disk usage exceeds the image-gc-high-threshold ,kubelet mya delete it, because of the offline, so the pod will never start

we use kubernetes as a basci platform, so we do not have a image registry

**What you expected to happen**:
Shall we add a function, that put the image in a whitelist ,so the image gc will ignore it ?
We had finished the code and test it ,if we need it ,we can do a pull request.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhangmingld** [comment]
Wow,the code above is not our code,i think i said clearly that we will do a pull request,please pay attention to the community rules @ceshihao

**Comment by zhangmingld** [comment]
@kubernetes/sig-node-feature-requests

**Comment by senthilrch** [comment]
#68930

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/enhancements/pull/1717
this will get a https://github.com/kubernetes/enhancements tracking issue soon, anyone interested should keep an eye out there.

generally features are done via enhancements now, with this issue tracker mostly used for bugs.
