### ISSUE TITLE
PODs are not visible with DNS name to other POD when they are in NotReady State

### ISSUE THREAD

**Issue by rawmu** [kubernetes/kubernetes#66234]
/kind bug
> /kind feature

**What happened**:
PODs are not visible with DNS name to other POD(s) when they are in Not Ready State
i have created PODs using statefullset and created headless service,when i ping/run nslookup with their DNS names before they are actually ready i got below output
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'xxxxx-server-1.xxxx-ms'

while they are visible with with DNS name after the POD is ready
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      xxxxx-server-0.xxxx-ms
Address 1: 192.168.200.116 xxxx-server-0.xxx-ms.exa-ns.svc.cluster.local

Note : for demo purpose i brought xxxxx-server-0 pod to ready state 
NAME                            READY     STATUS    RESTARTS   AGE
xxxxx-server-0                  1/1       Running   0                1d
xxxxx-server-1                  0/1       Running   0                 4h

**What you expected to happen**:
PODs should be visible with DNS name before they become Ready as statefulsets can not depend on POD IPs 
**How to reproduce it (as minimally and precisely as possible)**:
access or do nslookup of  statefulsets POD before they got ready using DNS name

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Oracle Linux Server"
VERSION="7.2"
ID="ol"
VERSION_ID="7.2"
- Kernel (e.g. `uname -a`):
Linux xxx.yyy.zzzz.com 4.1.12-112.14.15.el7uek.x86_64 #2 SMP Thu Feb 8 09:58:19 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
/sig network

**Comment by liggitt** [comment]
are you setting `publishNotReadyAddresses: true` on the service?

**Comment by rawmu** [comment]
no,is this on headless service ?
