### ISSUE TITLE
Failing Test: gke-gci-1.10-gci-master-upgrade-cluster

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/kubernetes#66240]
**Failing Jobs**

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster

**Comment by mohammedzee1000** [comment]
@surajnarwade can you also add links to the failing jobs?

**Comment by surajnarwade** [comment]
@mohammedzee1000 , link to failing job is: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/2288

**Comment by mohammedzee1000** [comment]
@surajnarwade thanks
/sig cluster-lifecycle

**Comment by neolit123** [comment]
>  link to failing job is: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/2288

after that it was fixed somehow and it started failing with this error consistently since the 18th:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/2298

> W0718 08:40:05.576] fatal: Not a git repository (or any of the parent directories): .git
> W0718 06:59:48.375]  zone: u'us-central1-c'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that: only 0 nodes out of 3 have registered; cluster may be unhealthy.

sadly, i cannot help much here.
the errors seem gcloud related...

**Comment by mohammedzee1000** [comment]
Tests seem to be fixed, closing for now, will reopen in case of regression.
/close
