### ISSUE TITLE
Failing Test: [sig-networking] Loadbalancing: L7 GCE [Slow] [Feature:NEG]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66243]
# Failing Jobs
[sig-release-master-blocking#gci-gce-ingress](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-ingress)

# Failing Tests
[rolling update backend pods should not cause service disruption](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/18796)
[should be able to switch between IG and NEG modes](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/18796)
[should conform to Ingress spec](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/18796)
[should sync endpoints to NEG](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/18796)

# Triage Results
[rolling update backend pods should not cause service disruption](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gci-gce-ingress&test=rolling%20update%20backend%20pods%20should%20not%20cause%20service%20disruption)
[should be able to switch between IG and NEG modes](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gci-gce-ingress&test=should%20be%20able%20to%20switch%20between%20IG%20and%20NEG%20modes)
[should conform to Ingress spec](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gci-gce-ingress&test=should%20conform%20to%20Ingress%20spec)
[should sync endpoints to NEG](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=gci-gce-ingress&test=should%20sync%20endpoints%20to%20NEG)

These tests are failing on sig master blocking

/cc @AishSundar @tpepper 
/kind bug
/sig networking
/priority failing-test
/priority important-soon
/milestone v1.12

**Comment by freehan** [comment]
This should be able to fix it
https://github.com/kubernetes/kubernetes/pull/65641

**Comment by mohammedzee1000** [comment]
Tests mentioned here appeared to be green. Will reopen in case of regression
/close

**Comment by mohammedzee1000** [comment]
/reopen tests failing again

Adding more failing tests:

[Loadbalancing: L7 GCE [Slow] [Feature:NEG] rolling update backend pods should not cause service disruption](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)
[Loadbalancing: L7 GCE [Slow] [Feature:NEG] should be able to create a ClusterIP service](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)
[Loadbalancing: L7 GCE [Slow] [Feature:NEG] should be able to switch between IG and NEG modes](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)
[Loadbalancing: L7 GCE [Slow] [Feature:NEG] should conform to Ingress spec](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)
[Loadbalancing: L7 GCE [Slow] [Feature:NEG] should sync endpoints for both Ingress-referenced NEG and standalone NEG](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)
[Loadbalancing: L7 GCE [Slow] [Feature:NEG] should sync endpoints to NEG](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/19198)

**Comment by tpepper** [comment]
/cc @freehan @bowei 
any idea why this would have seemingly regressed?

**Comment by bowei** [comment]
NEG API was disabled temporarily. @freehan  -- can we disable these until the API is back?

**Comment by tpepper** [comment]
@freehan @bowei test looks green again today in this area, but is notoriously flakey.  Can you confirm (ie: show repo/commitid) test was disabled or the NEG API is back?

**Comment by mohammedzee1000** [comment]
@freehan @bowei do we have any update on status of fixes?w

**Comment by AishSundar** [comment]
Spoke to @freehan who is looking into it. the underlying GCE APIs are broken and fix is bring rolled out. the fix is outside of k8s 1.12 code and hence we need not block on it. the tests will turn green as soon as the API is fixed, later this week.

**Comment by AishSundar** [comment]
Followed up internally - "fix is on the way to prod. We will restore the whitelist as soon as it's rolled out. ETA is end of week"

**Comment by guineveresaenger** [comment]
@AishSundar do we have an insider update?

**Comment by tpepper** [comment]
If this isn't being resolved, can we disable the test and open an issue for re-enabling if / when applicable in the future?

**Comment by AishSundar** [comment]
@freehan any update on the prod rollout of the API Fix?

**Comment by bowei** [comment]
@freehan will know definitely, but I think it's slowly being enabled again as we speak

**Comment by freehan** [comment]
It will be enabled by the end of this week.

**Comment by tpepper** [comment]
Modification appears to be in and test no longer failing.
