### ISSUE TITLE
Support InstanceShutdownByProviderID for Azure

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#66265]
Implement proposal #58635 for Azure

> We propose to taint the node with "Stopped" condition. When kubelet stops updating, node controller checks cloud provider and see whether the node is in "stopped" state (Note: different cloud provider might use different term to represent this state, e.g., terminated). When volume controller gets a node update/delete event, it can check the node taint spec and mark the volumes attached to that node are safe to detach (volumes can be be removed from the list of VolumeInUse (meaning the volumes are mounted). When detach is issued, the operation can be proceeded without delay.

We should implement `InstanceShutdownByProviderID()` interface in Azure cloud provider. `InstanceShutdownByProviderID()` returns true if the instance is in stopped state to detach volumes. But if instance is deleted we should not return error.

Related features: https://github.com/kubernetes/features/issues/551
Related proposal: https://github.com/kubernetes/kubernetes/issues/58635
Related PRs:
- https://github.com/kubernetes/kubernetes/pull/60009
- https://github.com/kubernetes/kubernetes/pull/66213

/kind feature
/sig azure

/cc @brendandburns @khenidak @andyzhangx

**Comment by yastij** [comment]
@feiskyer - can you assign me on this one ? I already have a PR in flight.

**Comment by andyzhangx** [comment]
That's great! 
/assign @yastij 
just loop in for this RP review, thanks.

**Comment by andyzhangx** [comment]
@yastij o, you are not a k8s member yet, anyway, you could send out the PR for this feature, related to this issue, thanks.

**Comment by feiskyer** [comment]
@yastij  Thanks, looking forward to your PR.
