### ISSUE TITLE
-i

### ISSUE THREAD

**Issue by Mr-Right2** [kubernetes/kubernetes#66274]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nikhita** [comment]
This is not a valid issue. Please reopen adding details asked in the template.

Closing.
/close

**Comment by Mr-Right2** [comment]
Whoopsie. I accidentally fell asleep on the keyboard without realizing I was opening an issue. Will try to solve my personal issues in private from now on :)
