### ISSUE TITLE
Scheduler and pv_controller info not sync caused volume reclaimed

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#66287]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
1. I create a pod with local volume
2. The scheduler start to do bind, it will make pv pv.spec.claimref.name = pvc.name
3. pv controller will call syncVolume to make pv bound , then syncClaim will make pvc bound.
But from the log, I find that after step 2, pv controller start to reclaim the pv  because pvc not in cache.
logs:

```
I0717 04:49:39.293155       1 pv_controller.go:542] volume "lv-4bfd1301-4ad0-4059-aedf-972b47cfda1d" is released and reclaim policy "Delete" will be executed
I0717 04:49:42.962430       1 pv_controller.go:754] volume "lv-4bfd1301-4ad0-4059-aedf-972b47cfda1d" entered phase "Released"
I0717 04:49:43.111046       1 pv_controller.go:1220] isVolumeReleased[lv-4bfd1301-4ad0-4059-aedf-972b47cfda1d]: volume is released
I0717 04:50:13.858894       1 pv_controller.go:754] volume "lv-4bfd1301-4ad0-4059-aedf-972b47cfda1d" entered phase "Available"

I0717 04:51:41.242761       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monstor-internal", Name:"largekeyspace2-32574-na-na-slc-59971-document-data-hidden-d27br0-data", UID:"ad721ff5-897c-11e8-bd69-3cfdfe54b0d8", APIVersion:"v1", ResourceVersion:"3639800376", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
I0717 04:51:52.088251       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monstor-internal", Name:"largekeyspace2-32574-na-na-slc-59971-document-data-hidden-d27br0-data", UID:"ad721ff5-897c-11e8-bd69-3cfdfe54b0d8", APIVersion:"v1", ResourceVersion:"3639800376", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
I0717 04:54:11.839976       1 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monstor-internal", Name:"largekeyspace2-32574-na-na-slc-59971-document-data-hidden-d27br0-data", UID:"ad721ff5-897c-11e8-bd69-3cfdfe54b0d8", APIVersion:"v1", ResourceVersion:"3639800376", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
```
We can see after pv reclaimed, then the logs related with pvc start to print out.

I know kube-scheduler will wait for the pvc to be bound, then it will be scheduled again in this situation. But  is there  a better way  to handle this situation  at pv_controller? 
@msau42 

**What you expected to happen**:
PV not reclaimed. 

**How to reproduce it (as minimally and precisely as possible)**:
Create pod and  local volume pvc in large scale

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
k8s 1.9

**Comment by msau42** [comment]
/sig storage

Maybe syncVolume could wait to make PV bound until PVC exists.  @jsafrane, wdyt?

**Comment by cofyc** [comment]
Another optimizing is that we can get PVC from apiserver only if PVC does not exist in cache. Double-check PVC from apiserver to make sure PV is not reclaimed on API sync delay.

**Comment by wenlxie** [comment]
@cofyc  We are doing the same way at our prod env.

**Comment by cofyc** [comment]
@msau42 Fix with the second optimizing is much simpler. I created a PR: https://github.com/kubernetes/kubernetes/pull/67062.

**Comment by cofyc** [comment]
@wenlxie Next time, you can submit a PR if you have a fix for issues you encountered ;-)
By the way, how many nodes in your large scale cluster?

**Comment by wenlxie** [comment]
@cofyc 
For this issue, I think there should be solution which no need to touch api-server to fix this issue.  That's why I didn't submit the PR.

Our cluster has more than 1k BM nodes, and we have more than 10K local volume PV. This issue happens when I create 1000 pods(which use local volume) with a for loop script. It is easy to reproduce.

**Comment by cofyc** [comment]
This issue happens when cache is out of sync (perhaps  heavy load on apiserver), that would be better if we can fix it without touching apiserver.

**Comment by jsafrane** [comment]
I am not sure I fully understand the issue. How is it possible that PV controller does not see the PVC in its cache? It must have been created before pod was created and scheduler bound it to a PV. That's IMO long enough for a pod to be in the cache, especially when PV got there quick enough.

**Comment by msau42** [comment]
The issue is syncing PVC/PV caches across scheduler and pv controller.  The PVs have been created long ago.  Now a bunch of PVCs and Pods are created with delayed binding.  Now, the scheduler will process the pod -> pvc, and then bind PV by setting PV.ClaimRef.

However, the PV controller could be slow to get API updates, and does not know about the new PVC object yet, but it got the PV update from the scheduler.  So it sees that PV is bound and pointing to a ClaimRef, but PVC doesn't exist, so it goes into Release state.
