### ISSUE TITLE
Deb packages for other distros

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubernetes#66300]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Debs are only built for xenial. We've had requests in the past to support other distros including [zesty](https://github.com/kubernetes/release/issues/378) and [bionic](https://kubernetes.slack.com/archives/C2C40FMNF/p1531505736000019?thread_ts=1531502997.000100&cid=C2C40FMNF).

/cc @timothysc

**Comment by timothysc** [comment]
/assign @ixdy 
/cc @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-testing-feature-requests @kubernetes/sig-release-feature-requests 

This should really be owned by sig-release but in reality, no one seems to own and manage this. 

@chuckha - I can't find the old issue.  ETOOMANYISSUES

**Comment by luxas** [comment]
Instead, we want to rename the deb repo. There's nothing xenial-specific in there, it's just named badly.
We do something generic atm and should name is as such when it's hosted under a CNCF umbrella.
cc @idvoretskyi

**Comment by idvoretskyi** [comment]
@luxas, thanks, I second this.

I can propose just the generic "kubernetes-deb" naming or similar.

**Comment by ixdy** [comment]
cc @mikedanese 

Do you have any thoughts on this?

**Comment by ixdy** [comment]
/assign @tpepper
(to find someone appropriate in sig-release to own this)

**Comment by tpepper** [comment]
In the big picture SIG-Release has an action here to better understand who's using which artifacts and insure that there are clear owning parties building and supporting the right things for the different personas across the userbase.  I write that deliberately ambiguously, as I'm not sure where the right line is.  Should the project build basic binaries and containers, plus installable packages for (which list of operating systems?)?  Or should vendors and k8s distros and OS distros build their native packages?  Or snaps or flatpak or?  And "us" or "them" or some intermediary community?  How much effort do we put into that at the k8s project level, if it ends up that a majority of users (unknown data here) actually build themselves what they run in production or they deploy a vendor's packaging?  It's important still for us to at least build and support for somebody to kick the tires and experiment, but there's a limit to what we can do for a support matrix then as a community.  And how to we insure there's proper integration at a packaging level with Provides/Requires metadata as the monolith splits and the control plane gets more complex and has more dependencies and connections to other projects.  I'm working on getting more discussion and definition in the SIG-Release meeting and would welcome additional voices (see: https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit).

All of that said...

Is the specific request here no more than the "xenial" name be removed from the generated deb's?

Or that we have deb packages built on top of multiple target Ubuntu generations?  And tested..I presume that's a desire too..including upgrades?

**Comment by neolit123** [comment]
i will take this opportunity to propose moving away for handling distro specifics.

i see a couple of options:

1) by introducing Snap or AppImage or <Similar> packaging.

https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

the recent [microk8s](https://microk8s.io/) (Snap based) introduction in a community meeting was frankly quite impressive, where the user only had to download a single package that supposedly runs across a range of supported distros and distro versions.

Windows and OSX do software packaging in a similar fashion.

2) Kubernetes is build using golang which means that one can pretty much copy paste binaries across distros and it should just work (tm). isn't that the case?

if that's the case, this renders option 1) redundant and the project can deprecate the distro specific package management and pretty write it's own install / uninstall tooling to handle installation.

the installation process here could end up being in the lines of:
```
curl install-kubernetes.sh
./install-kubernetes.sh --install 1.11.0
./install-kubernetes.sh --uninstall all
```

**Comment by idvoretskyi** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-release-feature-requests any progress on this?

**Comment by chuckha** [comment]
No progress. On the plus side, I've not seen any xenial specific parts of the build so I expect this will not be too hard as you mentioned.

**Comment by dawidmalina** [comment]
Where repository will be renamed to more generic name? It can be a bit wired for someone to mix repositories for Ubuntu xenial and bionic.

**Comment by danielsreichenbach** [comment]
> Is the specific request here no more than the "xenial" name be removed from the generated deb's apt repo target?
From the real world side of things: please keep repositories specific to supported OS releases. ´kubernetes-releasename´ gives a clear route to users.

> Or that we have deb packages built on top of multiple target Ubuntu generations? And tested..I presume that's a desire too..including upgrades?
Having a kubernetes-xenial and a kubernetes-bionic is the same as kubernetes-jessie plus kubernetes-stretch. While that _may_ have zero differences in terms of package content, it makes a clear statement as to:

- we have a clear upgrade path from release A to release B
- we probably also run infrastructure tests on this

This might look silly, but as one of the guys out there implementing Kubernetes with clients: this is what people look at, and the result usually is not "oh DEBs are all the same" but "Oh Kubernetes does not support release B".

The pragmatic approach is a single repository for all APT/DEB based systems.

**Comment by craigtracey** [comment]
Agree with @danielsreichenbach - there are optics issues here, but also impact on downstream configuration management tools.  Would it be possible to prioritize this in the current cycle?

**Comment by dims** [comment]
@danielsreichenbach @craigtracey i am looking for folks who can help with this effort. if you are interested ping @randomvariable and me. This is part of moving things to CNCF infrastructure and overlaps with SIG-release automation for building artifacts.

**Comment by danielsreichenbach** [comment]
@dims @randomvariable I would be available to resolve this. Technically all good, just need a bit of background info/context for final target.

**Comment by randomvariable** [comment]
Yup. I admit of being more in the RPM world where we're just expected to use a RH7 repo for
any systemd-based release of Fedora for most software.

**Comment by timothysc** [comment]
I'm volun-tolding @chuckha ;-)

**Comment by errordeveloper** [comment]
Do we support all Debian-derivatives now?

**Comment by magnetik** [comment]
/reopen

There are still no clear information about what repo to use.
Looks like #557 is a duplicate (as this one got a lot more traction).
