### ISSUE TITLE
AWS LoadBalancer doesn't handle updates correctly

### ISSUE THREAD

**Issue by selslack** [kubernetes/kubernetes#66306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After adding `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation to `LoadBalancer` service on AWS a new network load balancer gets provisioned, but the old one is not deleted and `status.loadBalancer.ingress` service field is not updated with the new address.

**What you expected to happen**:
Old load balancer is deleted.
`status.loadBalancer.ingress` field is updated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `LoadBalancer` on AWS without `service.beta.kubernetes.io/aws-load-balancer-type` annotation;
1. Add `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation to created service once it ensures load balancer.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Others: image `kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11`

**Comment by micahhausler** [comment]
Hmm this is an interesting edge-case. 

We don't re-create an ELB (or NLB) right now if you switch from internal to external (see #60393 and #64251), and this feels similar. We could probably manage this, but we'll bring it up at the next [SIG-AWS](https://github.com/kubernetes/community/tree/master/sig-aws) on Friday

**Comment by techdragon** [comment]
This does not yet appear to have an update. Also #60393 is has been closed by the robot without a proper resolution and I can 100% confirm that it is still an issue. I have run directly into this issue myself.

**Comment by jkinkead** [comment]
Thank you @Jeffwan , this is very surprising behavior. Adding the `service.beta.kubernetes.io/aws-load-balancer-internal` annotation makes services *look* private, but keeps them public, which is fairly sketchy (#64251, closed due to inactivity).

**Comment by Jeffwan** [comment]
@jkinkead, I notice some issues talking about external <--> internal. I think they are still not resolved yet. Let me confirm.

**Comment by metral** [comment]
I'm hitting this issue on EKS 1.11.

If I have a classic public ELB, and then change it to private by adding the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` it doesn't turn the public LB into a private one.

Conversely, having a private LB and then removing the annotation, does not turn it into a public LB.

This is certainly a bug in the AWS cloud provider

**Comment by Jeffwan** [comment]
@metral I am trying to get approver to merge this PR and cherry-pick to kubernetes 1.11. Should be done soon. @micahhausler

**Comment by shyamjvs** [comment]
/remove-lifecycle stale
/lifecycle frozen

/assign @Jeffwan 
As he has a potential fix for this in flight.

**Comment by bnutt** [comment]
Recently observed this on EKS 1.17, is there any movement to address this issue?

Steps to reproduce:

1. Create kubernetes service with annotations to create NLB and type internal(did not try to reproduce with public facing loadbalancer).
2. After loadbalancer is provisioned, remove annotations for NLB/type internal. ELB will be created at this point and the NLB will not be removed.
3. Add annotations back for NLB/type internal, no-op since the NLB exists, ELB isn't removed, so both loadbalancers exist at the same time.
4. User is now forced to delete the ELB by hand instead of using their SCM to control changes to the infrastructure.

**Comment by M00nF1sh** [comment]
@bnutt 
It's an unsupported behavior for now. `service.beta.kubernetes.io/aws-load-balancer-type` should be treated as immutable. If you need to change it, you should delete the service and recreate.

**Comment by kishorj** [comment]
The annotation `service.beta.kubernetes.io/aws-load-balancer-type` should be considered immutable and not modified after creating the service. In the short term we will document this behavior, and there will not be further changes to the kubernetes in-tree cloudprovider.

Further changes in this area should be handled in the [v2 cloudprovider](https://github.com/kubernetes/cloud-provider-aws), and the [AWS Load Balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller).

**Comment by kishorj** [comment]
Closing this issue since we will not add new features to the in-tree code.

/close
