### ISSUE TITLE
apiserver's etcd client can get into a non-operational state, all calls on that resource 504

### ISSUE THREAD

**Issue by mahmoudm** [kubernetes/kubernetes#66312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: The API server can get into a state where it's etcd client can no longer process connections, and therefore all calls to an endpoint that uses that client will 504 (timeout). I've observed this specially in this situation:

We turned on datadog-agent v6 which does a WATCH on the Events resource to collect events. Shortly afterwards, we noticed that the events API would stop processing requests and always 504. This is the offending code in datadog: https://github.com/DataDog/datadog-agent/blob/7820efa6b45722ce141e6af46cb0d4ef966e4e7d/pkg/util/kubernetes/apiserver/events.go

After spending sometime debugging this, I was able to reproduce the problem via a straightforward program that mimics the same behavior - see this gist: https://gist.github.com/mahmoudm/287824642c963011d49413fd3b9552da

Specifically, if you are doing WATCH calls, and then stopping the watch before the api-server got the chance to respond, you are leaking connections in the corresponding etcd client. Eventually, the client runs out of grpc streams and all calls get stuck waiting for new streams. See this thread dump of an api-server in that state: https://gist.github.com/mahmoudm/94ad32718b54f86f3ecfc1f9fe02bff2

Note the 287 goroutines stuck at k8s.io/kubernetes/vendor/google.golang.org/grpc/transport.wait, waiting for a stream. 

**What you expected to happen**:

I expect that terminating WATCHs in the pattern described above should not cause the API server to get into a state where the corresponding resource stops working entirely. 

**How to reproduce it (as minimally and precisely as possible)**:

1) Build and compile the go code in https://gist.github.com/mahmoudm/287824642c963011d49413fd3b9552da

2) Run the binary with values such that your WATCH call times out before it receives a response. In other words, there needs to be enough load on your etcd cluster that you don't receive a response before calling Stop() on the watcher. I am able to reproduce it with these values:

 ./watchs-spam ~/.kube/config 100ms 50ms
With a 2000 pod deployment, and 100 nodes on my cluster. 

3) Observe that after a few minutes, the events API will no longer respond and will consistently return 504s for any event call. If you look at the goroutines, you'll see that they are all stuck waiting for streams since they are no longer able to acquire any.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): I was able to repro on both 1.9.8 and 1.10.5
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gyuho** [comment]
Possibly related to https://github.com/coreos/etcd/issues/9212. And there is also a pending issue in watch stream multiplexing https://github.com/coreos/etcd/issues/9416.

**Comment by mahmoudm** [comment]
@gyuho https://github.com/coreos/etcd/issues/9212 does look like it could be the culprit here. Given that it's been open for a while, is there any change in prioritization given the impact/repro above, or is it blocked on finding a contributor?

Also slightly tangential to the issue above: when the API server is in that state, all connection stuck on the transport.wait never die (i.e while the finishRequest causes the http connection with the client to timeout, the internal goroutine doing the etcd connection is stuck until the process dies as per the thread dump above)

**Comment by gyuho** [comment]
@mahmoudm Haven't had a chance to look into https://github.com/coreos/etcd/issues/9212 yet. Since we are seeing this in production, this will be our high priorities. Will also look into the code that you provided.

**Comment by mahmoudm** [comment]
Thanks @gyuho. Let me know if you need any further information or help reproducing it.

**Comment by gyuho** [comment]
@mahmoudm The root cause of https://github.com/coreos/etcd/issues/9212 was kept-alive TCP connections. Once client-side keepalive is enabled, gRPC closes previous TCP connections on keepalive timeouts. I would try enable keep-alive parameters from API server(etcd client) to etcd server.

**Comment by mahmoudm** [comment]
Thanks for investigating @gyuho. I can try doing that this week and report back. If it resolves the issue, do you want a PR to merge upstream? Or is the plan to upgrade the etcd client instead given that it's not an issue on master as per https://github.com/coreos/etcd/issues/9212?

**Comment by gyuho** [comment]
@mahmoudm Latest api server already uses keep alives

https://github.com/kubernetes/kubernetes/blob/4797c8df8f2db6c0ed88f9d108c08ef61e1c25af/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L37-L40

Maybe keepalive parameters aren't short enough.

>  leaking connections in the corresponding etcd client.

If you still see leaky connections even with short keepalives, it could be some other issue.

Please let us know after you try it later.

**Comment by mahmoudm** [comment]
@gyuho I was able to reproduce this on v1.10.5, which has the keep-alive timeouts. After the etcd client got into the hung state, I waited 15 minutes without introducing any load and the endpoint never recovered (implying it doesn't matter how short the keep-alives are).

**Comment by arpitsardhana** [comment]
We are also facing this issue while doing Etcd negative test.
We brought down the Etcd leader node and ran "kubectl get pods --all-namespaces"

It was observed that it takes API server around 20 minutes to resume connection with next etcd.
It was verified that Etcd works fine, since i can see leader election happening properly.
So conclusion is connectivity between etcd and  API server takes too long time to retry.

On more experiment, it appears, etcd client in API server does not honor keep alive and connection takes like 15 tcp retries with exponential backoff before tearing down existing connection with Etcd.

By varying the no of retries, i can vary the time API server takes to reestablish connection with etcd.
"by setting tcp retries
 sysctl -w net.ipv4.tcp_retries2=1
sysctl -w net.ipv4.tcp_syn_retries=2 

I ran experiments to determine how no of retires affect connection reset b/w Etcd and APIserver:
when retries =1 , it is immediate, no delay in API connection to Etcd
when retires = 5 , it is in few seconds ~2-3 seconds
when retries = 10, it is ~ 5 minutes
when retries = 15, response time of k8 ~ 20 minutes"

Also same way by setting keepalive to 10 seconds and reducing time between keepalive probes at TCP level also enabled API server to talk to next available Etcd.

What is the update on issue? When can we expect this issue to be fixed

**Comment by dims** [comment]
cc @jpbetz

**Comment by gyuho** [comment]
@arpitsardhana  Which Kubernetes API server version are you running with?

**Comment by arpitsardhana** [comment]
@gyuho I am using 1.9.6
------------------------
kube-apiserver --version
Kubernetes v1.9.6+coreos.0
-------------------------

**Comment by gyuho** [comment]
@arpitsardhana Kubernetes v1.9.6 uses etcd `v3.1.11`, of which client does not implement proper failover, which may make API server stuck with one etcd node. Can you try with latest Kubernetes APIs server? With Kubernetes API server that has at least https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.2.md#v3210-2017-11-16.

**Comment by arpitsardhana** [comment]
@gyuho Is there any workaround suggested for production cluster running into same issue since it will take time for prod cluster to upgrade to different version of kubernetes API server which has latest etcd client?

**Comment by timothysc** [comment]
/assign @timothysc  

Closing this as the client was updated for more than 2 releases now.

**Comment by mahmoudm** [comment]
This is reproducible with the latest version.

**Comment by liggitt** [comment]
> This is reproducible with the latest version.

with what version of the etcd server?

**Comment by 2rs2ts** [comment]
We can repro this with k8s 1.13.2 and etcd 3.3.5 by just doing a xen shutdown on our etcd VMs. apiserver completely hangs on everything until the node is restored
