### ISSUE TITLE
kubeadm init failed to pull image

### ISSUE THREAD

**Issue by ary31415** [kubernetes/kubernetes#66320]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

In the process of running kubeadm init, kubernetes attempted to "pull images required for setting up a kubernetes cluster", and then failed to pull all 4 of the images required.

**What you expected to happen**:

I expected a new cluster to be created, with my VM as the master node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.4.0
- Install tools: apt
- Others:

**Screenshots**
![image](https://user-images.githubusercontent.com/16035054/42853527-daa7064a-89eb-11e8-8181-de59a07931d0.png)
_relevant syslog entries_
![image](https://user-images.githubusercontent.com/16035054/42853549-f3ee7728-89eb-11e8-85f7-1474f200a475.png)

**Comment by adilOo02** [comment]
i have the same issue :'(,someone help please

**Comment by vitorfhc** [comment]
I used --kubernetes-version=1.11.0 and it fixed for me, for some reason it was looking for images with version 1.11.1 and they are not available

**Comment by adilOo02** [comment]
vitorfhc thanks pale :)

**Comment by Newbrict** [comment]
Also having this problem
![capture](https://user-images.githubusercontent.com/1683041/42857063-2f5a816a-8a16-11e8-97ff-20d165f33fae.PNG)

**Comment by ProFfeSsoRr** [comment]
Is there any problems with k8s.gcr.io? Maybe another mirror for this images available?

**Comment by ricohomewood** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by ricohomewood** [comment]
indeed as @vitorfhc mentioned the v1.11.1 images don't exist on the k8s.gcr.io registry?

**Comment by hanscj1** [comment]
Ditto

**Comment by pursultani** [comment]
The image is missing from `k8s.gcr.io`. Perhaps haven't been pushed yet.

```
$ docker pull k8s.gcr.io/kube-apiserver-amd64:v1.11.1
Error response from daemon: manifest for k8s.gcr.io/kube-apiserver-amd64:v1.11.1 not found
```

@vitorfhc suggestion does the trick. 

```
$ kubeadm --kubernetes-version=1.11.0 config images list
k8s.gcr.io/kube-apiserver-amd64:v1.11.0
k8s.gcr.io/kube-controller-manager-amd64:v1.11.0
k8s.gcr.io/kube-scheduler-amd64:v1.11.0
k8s.gcr.io/kube-proxy-amd64:v1.11.0
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd-amd64:3.2.18
k8s.gcr.io/coredns:1.1.3
```

**Comment by neolit123** [comment]
closing as this was logged earlier:
https://github.com/kubernetes/kubeadm/issues/1000

/close
