### ISSUE TITLE
VMWare library dependency contributes roughly ~22M to total hyperkube binary size

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#66321]
As a follow up to #62576 I was investigating other large packages.  In Go 1.10 it looks like `github.com/vmware/govmomi/vim25/types` is the next largest - it was ~ 23M compiled (by itself) and defines roughly 6k structs, and also preserves very large maps of type information as well as individual init functions to create that map.  When compiling `hyperkube` with the vmware packages commented out, total binary size dropped by roughly 23M as well.  Link-time-optimization won't work against a package like this since all type info in the package is included in the map.  It looks like the init functions alone are 1.5M, while the hash functions and eq functions for each struct are roughly 200-300b

@kubernetes/vmware has this ever been reported or investigated in the client library?  I suspect breaking the package up into multiple imports (one per group of APIs) and then allowing those sub packages to be directly imported or aggregated would allow more selective usage, but it's possible that the Go compiler is missing opportunities to more efficiently handle this package.  If we know what the surface area of the calls are, could we be more selective in the imports?

**Comment by dougm** [comment]
We have been meaning to improve this situation with the govmomi generated code, @akutz and I will dig in soon.

**Comment by dougm** [comment]
I've started by adding some background and possible ways we can improve in vmware/govmomi#1186
I will follow up once we flesh out more detail and a plan on how to best move forward.

**Comment by dougm** [comment]
Have not started digging into this yet beyond research put into the gomvomi issue, but planning to early in the 1.13 cycle.

**Comment by dougm** [comment]
/remove-lifecycle stale

This issue is still valid as long as the vsphere cloud provider is in-tree.

The external provider is shaping up, but we can't remove the in-tree provider just yet: https://github.com/kubernetes/cloud-provider-vsphere#cloud-controller-manager-for-vsphere

**Comment by andrewsykim** [comment]
Work for removing the in-tree providers: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md 

Expect providers to be staged in v1.15. Doesn't reduce binary but it's our first milestone towards migrating things out

**Comment by liggitt** [comment]
looks like this package is now up to ~28MB

**Comment by andrewsykim** [comment]
@liggitt is that from the latest simulator update or was there another update recently?

**Comment by liggitt** [comment]
the size increase looks to be due to go versions:

go1.10: 23M
go1.11: 27M
go1.12: 27M

**Comment by liggitt** [comment]
https://github.com/golang/go/issues/27266 looks relevant

**Comment by komuw** [comment]
Watch out bot , dims is coming for you.

**Comment by dims** [comment]
/reopen

LOL @komuw

**Comment by cheftako** [comment]
/triage accepted
Are we waiting for cloud provider extraction to fix this?

**Comment by dims** [comment]
/close

all done and dusted!
