### ISSUE TITLE
Stat fs failed. Error: no such file or directory

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#66335]
/kind bug
/sig cluster-lifecycle

**What happened**:
When check kubelet.service with systemctl:
```
7月 18 20:56:03 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:03.180082  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:56:21 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:21.298349  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:56:34 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:34.858103  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:56:49 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:49.567516  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:57:09 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:09.003603  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:57:23 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:23.949284  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:57:35 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:35.187776  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:57:46 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:46.049174  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:58:00 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:58:00.863854  256093 fs.go:418] Stat fs failed. Error: no such file or directory
7月 18 20:58:18 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:58:18.846837  256093 fs.go:418] Stat fs failed. Error: no such file or directory

```
The kubelet.service is still in active running state.

I do not know how to debug or where is wrong.

**What you expected to happen**:
1. in fs.go file, print which file missing
2. If the missing error does no impact on kubelet service, maybe place log info somewhere else

**Environment**:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
You have new mail in /var/spool/mail/root

- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64

**Comment by daixiang0** [comment]
Seems like #35062, there is a solution in it but no any feedback

**Comment by neolit123** [comment]
1.9.x is outside of the supported versions and it no longer receives patches.
please consider upgrading to 1.12 or 1.13 in december.

if you have bug reports against 1.11+ please open new tickets. thanks.

/close

**Comment by one-two-my-gad** [comment]
> /kind bug
> /sig cluster-lifecycle
> 
> / kind bug / sig cluster-lifecycle
> 
> **What happened**:
> When check kubelet.service with systemctl:
> 
> 发生了什么: 当用 systemctl 检查 kubelet.service 时:
> 
> ```
> 7月 18 20:56:03 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:03.180082  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:56:21 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:21.298349  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:56:34 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:34.858103  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:56:49 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:56:49.567516  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:57:09 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:09.003603  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:57:23 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:23.949284  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:57:35 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:35.187776  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:57:46 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:57:46.049174  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:58:00 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:58:00.863854  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> 7月 18 20:58:18 skyaxe-app-0.localdomain kubelet[256093]: E0718 20:58:18.846837  256093 fs.go:418] Stat fs failed. Error: no such file or directory
> ```
> The kubelet.service is still in active running state.
> 
> 服务仍处于活动运行状态。
> 
> I do not know how to debug or where is wrong.
> 
> 我不知道如何调试或哪里是错误的。
> 
> **What you expected to happen**:
> 
> 你预期会发生什么:
> 
> 1. in fs.go file, print which file missing
> 2. If the missing error does no impact on kubelet service, maybe place log info somewhere else 如果丢失的错误对 kubelet 服务没有影响，可以将日志信息放在其他地方
> 
> **Environment**:
> 
> 环境:
> 
> * Kubernetes version:
>   Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
>   Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
>   You have new mail in /var/spool/mail/root库伯内特版本: 客户端版本: 版本。 信息{ Major:"1"，Minor:"9"，GitVersion:"v1.9.7"，GitCommit:"dd5e1a2978fd0b97d9b78e1564398aee7e7fe92"，GitTreeState:"clean"，BuildDate:"2018-04-19T00:05:56Z"，GoVersion:"go1.9.3"，Compiler:"gc"，Platform:"linux / amd64"}服务器版本: Version: Version: Version:。 信息{ Major:"1"，Minor:"9"，GitVersion:"v1.9.7"，GitCommit:"dd5e1a2978fd0b97d9b78e1564398aee7e7fe92"，GitTreeState:"clean"，BuildDate:"2018-04-18T23:58:35Z"，GoVersion:"go1.9.3","gc"，Platform:"linux / amd64"}你在 / var / spool / mail / root 中有了新的邮件
> * OS (e.g. from /etc/os-release): CentOS 7.4Os (例如 from / etc / OS-release) : CentOS 7.4
> * Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64内核(例如 uname-a) : 3.10.0-693。 El7.x8664

哈喽   我对kubelet.service 给予了权限  该报错不在发生   chmod 754  /etc/systemd/system/kubelet.service
