### ISSUE TITLE
Azure File fails to be mounted on CoreOS

### ISSUE THREAD

**Issue by r7vme** [kubernetes/kubernetes#66346]
/kind bug

**What happened**:

NOTE: I think this is a bug of CoreOS, but taking into account silence from 2016 in [CoreOS bug](https://github.com/coreos/bugs/issues/571), i did not expect it will be fixed there soon. So creating it here as it affects all people who are using Kubernetes with CoreOS on Azure.

Azure File (mount cifs) mount does not work on CoreOS. By default CoreOS does not provide `mount.cifs` binary. Despite the fact binary available inside `hyperkube`, mount still fails, because at the moment Kubernetes executes mounts with `systemd-run` command which will use `mount` available on the host system.

So Azure File mount fails with 
```
MountVolume.SetUp failed for volume "pvc-xxx" : exit status 32
```

Kubernetes can help wit fixing this issue by using `mount.cifs` instead of `mount -t cifs`, this will allow to put `mount.cifs` to `/opt/bin` on CoreOS which is read-write (`/sbin` is read-only)

**What you expected to happen**:
Pod with Azure File volume successfully started.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy CoreOS-based k8s cluster on Azure (e.g. you can use our [terraform](https://github.com/giantswarm/giantnetes-terraform)) with containerized kubelet.
2. Create Azure File Storage Class like described in [docs](https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-file)
3. Create pod and pvc (e.g. from this [gist](https://gist.github.com/r7vme/47caf64ca64a94a15583739acfcaa5e9))
4. Pod will stuck in `ContainerCreating`

**Anything else we need to know?**:

quick and dirty workaround that immediately fixes this problem (copy `mount.cifs` from hyperkube)
```
mkdir /sbin2
cp -a /sbin/* /sbin2
# remove symlink
rm -r /sbin
mv /sbin2 /sbin
# Copy mount.cifs binary from kubelet container
docker cp k8s-kubelet.service:/sbin/mount.cifs /sbin
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.4
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1745.7.0 (Rhyolite)
- Kernel (e.g. `uname -a`): 4.14.48-coreos-r2
- Install tools: https://github.com/giantswarm/azure-operator
- Others: -

**Comment by feiskyer** [comment]
@r7vme Thanks for reporting the issue. Would you like file a PR to fix that?

**Comment by r7vme** [comment]
I'll wait little bit for a proper fix from CoreOS i think. Trying to get attention about https://github.com/coreos/bugs/issues/571

**Comment by r7vme** [comment]
Fixed in CoreOS [1] and this is OS issue. So closing.

1 - https://github.com/coreos/bugs/issues/571
