### ISSUE TITLE
Pending pod scheduled onto master node when `ScheduleDaemonSetPods` is enabled

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#66348]
/kind bug

**What happened**:

To enforce daemonset pods scheduling is handled by default scheduler, instead of ds controller, I enabled `ScheduleDaemonSetPods` feature, and it looks almost fine except for a flaw: for a cluster spawned by kubeadm, the daemonset pod is still scheduled to master node with "pending" state.

```
$ k get node
NAME                           STATUS    ROLES     AGE       VERSION
wei-k8s-master.fyre.ibm.com    Ready     master    8d        v1.11.0
wei-k8s-worker1.fyre.ibm.com   Ready     <none>    8d        v1.11.0
wei-k8s-worker2.fyre.ibm.com   Ready     <none>    8d        v1.11.0
$ k get ds
NAME      DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
busybox   3         3         2         3            2           <none>          16m
$ k get pod -o wide
NAME            READY     STATUS    RESTARTS   AGE       IP             NODE
busybox-f8m45   1/1       Running   0          16m       192.168.2.20   wei-k8s-worker2.fyre.ibm.com
busybox-fkzq5   1/1       Running   0          16m       192.168.1.24   wei-k8s-worker1.fyre.ibm.com
busybox-zb8g9   0/1       Pending   0          16m       <none>         <none>
```

**What you expected to happen**:

The behavior should be consistent as before (ds handled by ds controller). That's to say, on a kubeadm cluster, there shouldn't be a "Pending" pod scheduled onto master node.

**How to reproduce it (as minimally and precisely as possible)**:

Spin up a kubeadm cluster, and deploy a sample daemonset yaml like this:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "3600"
```

**Anything else we need to know?**:

In a kubeadm cluster, master node has following spec:

```yaml
apiVersion: v1
kind: Node
metadata:
......
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: wei-k8s-master.fyre.ibm.com
    node-role.kubernetes.io/master: ""
    opt: in
  name: wei-k8s-master.fyre.ibm.com
spec:
  podCIDR: 192.168.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
......
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vm
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
```
Linux wei-k8s-master.fyre.ibm.com 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Others: none

**Comment by yastij** [comment]
cc @k82cn @janetkuo

**Comment by Huang-Wei** [comment]
btw: I can actively work on this.

/assign

**Comment by k82cn** [comment]
@Huang-Wei , with `ScheduleDaemonSetPods`, DaemonSet controller will create Pod based on nodes  ignored node's attributes, e.g. taint; the scheduler will help to handle it :) If we want to only create Pod for worker nodes, please add NodeSelector/NodeAffinity into it :)

**Comment by Huang-Wei** [comment]
@k82cn ok, that means it's sort of **as expected**, right? (in kubeadm cluster, the daemonset behavior changes a little bit after enabling `ScheduleDaemonSetPods` though.)

If we want to go promote `ScheduleDaemonSetPods` to beta in 1.12 and keep current logic, in my opinion, we need to at least document in `kubeadm` - telling kubeadm users they need to add NodeSelector/NodeAffinity, otherwise a "Pending" daemonset pod will showup.

**Comment by janetkuo** [comment]
This is a pretty big behavioral change. I didn't see it documented in https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ or release note https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md

We should communicate that better.

**Comment by k82cn** [comment]
oh, agree; I was thinking that was covered by doc, but it seems not according to the above link :)

@Huang-Wei , would you help on that?

**Comment by Huang-Wei** [comment]
@k82cn Sure, I can definitely help.

Let me also run more tests to be 100% sure that `ScheduleDaemonSetPods` doesn't respect taint. If it's the case, in an user's perspective, it's a behavioral change of "DS respect taint" versus "DS doesn't respect taint" - hugh change IMHO.

**Comment by Huang-Wei** [comment]
FYI: another data point:

- enabled `ScheduleDaemonSetPods=true,TaintNodesByCondition=true` on all components (apiserver, kubelet, controller-manager, scheduler)
- add a normal taint to worker1
    ```
    $ k taint node wei-k8s-worker1.fyre.ibm.com key1=value1:NoSchedule
    node/wei-k8s-worker1.fyre.ibm.com tainted
    ```
- deploy a daemonset app
- only worker1 has pod running; pods on tainted nodes show pending
    ```
    $ k get po -o wide
    NAME            READY     STATUS    RESTARTS   AGE       IP             NODE
    busybox-6jjhr   0/1       Pending   0          2m        <none>         <none>
    busybox-jwd9q   1/1       Running   0          2m        192.168.2.22   wei-k8s-worker2.fyre.ibm.com
    busybox-tcrdr   0/1       Pending   0          2m        <none>         <none>
    ```

**Comment by ravisantoshgudimetla** [comment]
Why do we want to break backward compatibility here? Isn't this similar to adding https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1470 to https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1430, without this any DS we create will need to have additional nodeaffinity in its spec not to match labels on master so that they are not created on master.

Is it just for ensuring we are not using lots of predicates from scheduler or am I missing something else?

/cc @bsalamat @aveshagarwal

**Comment by Huang-Wei** [comment]
As an user's perspective, "Pending" pod usually makes people panic - even scheduler gives a reasonable explanation there.

It also applies to this case.

So I'm more leaning to that for daemonset scheduling, as @ravisantoshgudimetla mentioned, to make the behavior consistent: open the boundary a little bit: from current [PodFitsHost, PodMatchNodeSelector] to [PodFitsHost, PodMatchNodeSelector, PodToleratesNodeTaints].

But correctness should still go first, we need to ensure no regression is brought in.

**Comment by bsalamat** [comment]
+1 to what @ravisantoshgudimetla proposed.

**Comment by k82cn** [comment]
There're two major usage of Taint/Toleration for now: 1.) kind of "selector" (not selected), e.g. this case to kubadm; 2.) represent node's condition, e.g. network unavailable.  +1 for case 1.

It's a bit complex for case 2; ideally, high priority pod can preempt low priority in "pressure condition" (if no other hosts/node); as DaemonSet controller does not handle priority, it will not create DaemonSet pods if added tolerate/taint predicates. Currently, scheduler did not handle the "ideally" case :(.

**Comment by ravisantoshgudimetla** [comment]
> It's a bit complex for case 2; ideally, high priority pod can preempt low priority in "pressure condition" (if no other hosts/node); as DaemonSet controller does not handle priority, it will not create DaemonSet pods if added tolerate/taint predicates.

IIUC, are you suggesting to make scheduler aware of resource crunch on node and evict pods to reduce pressure on the node? Isn't kubelet responsible for it? Even then, if you still think there is room to free up resource, shouldn't we let descheduler handle it?

**Comment by k82cn** [comment]
> evict pods to reduce pressure on the node

No; I means preemption between high priority pod and low priority pod. Does descheduler also aware pod's priority (including pending pods)?

**Comment by k82cn** [comment]
DaemonSet controller tolerates "pressure condition" itself; so no such requirements right now. I'm also thinking whether we should use `PreferNoSchedule` for "pressure condition" :)

BTW, @Huang-Wei , please also add PID pressure toleration and remove OutOfDisk according to the ndoes.

**Comment by Huang-Wei** [comment]
> please also add PID pressure toleration and remove OutOfDisk according to the ndoes.

@k82cn do you mean something like:

```diff
diff --git a/pkg/controller/daemon/daemon_controller.go b/pkg/controller/daemon/daemon_controller.go
index a66c99c7be..2947482737 100644
--- a/pkg/controller/daemon/daemon_controller.go
+++ b/pkg/controller/daemon/daemon_controller.go
@@ -1268,8 +1268,7 @@ func (dsc *DaemonSetsController) simulate(newPod *v1.Pod, node *v1.Node, ds *app
 	})
 
 	// According to TaintNodesByCondition, all DaemonSet pods should tolerate
-	// MemoryPressure and DisPressure taints, and the critical pods should tolerate
-	// OutOfDisk taint additional.
+	// MemoryPressure, DisPressure and PIDPressure taints
 	v1helper.AddOrUpdateTolerationInPod(newPod, &v1.Toleration{
 		Key:      algorithm.TaintNodeDiskPressure,
 		Operator: v1.TolerationOpExists,
@@ -1282,14 +1281,11 @@ func (dsc *DaemonSetsController) simulate(newPod *v1.Pod, node *v1.Node, ds *app
 		Effect:   v1.TaintEffectNoSchedule,
 	})
 
-	// TODO(#48843) OutOfDisk taints will be removed in 1.10
-	if kubelettypes.IsCriticalPod(newPod) {
-		v1helper.AddOrUpdateTolerationInPod(newPod, &v1.Toleration{
-			Key:      algorithm.TaintNodeOutOfDisk,
-			Operator: v1.TolerationOpExists,
-			Effect:   v1.TaintEffectNoSchedule,
-		})
-	}
+	v1helper.AddOrUpdateTolerationInPod(newPod, &v1.Toleration{
+		Key:      algorithm.TaintNodePIDPressure,
+		Operator: v1.TolerationOpExists,
+		Effect:   v1.TaintEffectNoSchedule,
+	})
 
 	objects, err := dsc.podNodeIndex.ByIndex("nodeName", node.Name)
 	if err != nil {
```

If so, I will create another PR and update related testcases.

**Comment by ravisantoshgudimetla** [comment]
> No; I means preemption between high priority pod and low priority pod.

Kubelet can do that as well. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/preemption/preemption.go but this will be run for critical pods.

>  Does descheduler also aware pod's priority (including pending pods)?

I just introduced another PR to make descheduler priority aware but it just looks at the pods that are not running on the node not pending pods. But the room for pending pods would have been made by kubelet preemption.

> high priority pod can preempt low priority in "pressure condition" (if no other hosts/node);

To be clear, we don't do this today in scheduler, right? I mean preempting some pods to make node come back from high pressure conditions.

**Comment by k82cn** [comment]
> preempting some pods to make node come back from high pressure conditions.

That's not scheduler's scope; scheduler do preemption for pending pod; kubelet and descheduler should only consider running pods.
It's wired that low priority running pod trigger pressure condition which block/delay high priority pending pod to be scheduled on the host.

**Comment by k82cn** [comment]
@Huang-Wei , the PID part is ok to me; I did not check the history of OutOfDisk, e.g. whether other codes need to update, would you help to check ?

**Comment by Huang-Wei** [comment]
@k82cn sounds good - I will do a thorough check and open another pr.

**Comment by janetkuo** [comment]
#61161 becomes invalid after DaemonSet starts respecting taints. @k82cn @Huang-Wei

**Comment by Huang-Wei** [comment]
@janetkuo my reading is that current behavior is consistent with what it used to be. Daemonset also respect taints in the before:

https://github.com/kubernetes/kubernetes/blob/c94ececccc66701494a4cb271c50342dd724b692/pkg/controller/daemon/daemon_controller.go#L1521

---

However, one behavior I noticed got changed is the `cordon` case: in 1.11, if a node is cordoned, DS pod is scheduled to that node. But right now, with `ScheduleDaemonsetPods=true` and `TaintNodesByCondition=true` (default in master), DS pod still can't be scheduled onto cordoned node:

```
I0821 22:37:08.614895       1 daemon_controller.go:1396] DaemonSet Predicates failed on node kube-node-2 for ds 'default/pause' for reason: node(s) had taints that the pod didn't tolerate
```

The message is pretty tricky. As (1) I do see DS pod (on other normal node) have "noschedulable" applied:

```yaml
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
```

And (2) `cordon`ing node applies a "noschedulable" taint:

```yaml
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: 2018-08-21T23:20:54Z
  unschedulable: true
```

So in theory it's a match. Maybe a timing issue - when `simulate()` is invoked, `AppendNoScheduleTolerationIfNotExist() isn't applied yet`. Let me dig more.

**Comment by Huang-Wei** [comment]
I can confirm it's `simulate()` used to calculate how many nodes needs to run daemonset pods first, and afterwards syncNodes() -> AppendNoScheduleTolerationIfNotExist() is invoked to apply "unschedulable" toleration to daemonset pods.

To workaround this issue, @k82cn @janetkuo is it appropriate to apply "unschedulable" toleration to `simulate()` - there are other memory/pid/disk pressure tolerations there as well?

**Comment by ravisantoshgudimetla** [comment]
Agree with @Huang-Wei on behaviour, we just changed this enabled this to ensure that DS controller is backwards compatible but not sure about replacing UnSchedulable field with TaintNodesByCondition as the semantics of taints allow pods to tolerate them. We cannot replace 'UnSchedulable' with a taint unless there is a special type of taint that cannot be tolerated at all.

**Comment by k82cn** [comment]
Yes, we should also add `Unschedulable` toleration in `simulation()`.
