### ISSUE TITLE
externalTrafficPolicy=Local makes it unable to reach externalIP from nodes without pods

### ISSUE THREAD

**Issue by yastij** [kubernetes/kubernetes#66354]
Currently when having `externalTrafficPolicy=Local` you cannot reach your service through the externalIP on a node without the targeted pods. is it an expected behaviour ? 

Kubernetes v1.10.1 running on Azure.

/kind bug
/sig network

**Comment by liucimin** [comment]
Yes，
If u use the flag externalTrafficPolicy=Local.Requests will only be proxied to local endpoints and will not be forwarded to other nodes. This preserves the original source IP address. If there are no local endpoints, the packets sent to this node will be discarded.
