### ISSUE TITLE
"Invalid Value" Error when attempting to modify ClusterRoleBinding roleRef

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/kubernetes#66353]
/kind bug

**What happened**:
I encounter an error when attempting to change the roleRef in a ClusterRoleBinding:

The ClusterRoleBinding "test-crb" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"view"}: cannot change roleRef

**What you expected to happen**:
I expected to be able to modify the roleRef field in a ClusterRoleBinding.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ kubectl apply -f - << EOF
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-crb
subjects:
- kind: User
  name: user@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
EOF
clusterrolebinding "test-crb" created

$ kubectl apply -f - << EOF
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-crb
subjects:
- kind: User
  name: user@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
EOF
The ClusterRoleBinding "test-crb" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"view"}: cannot change roleRef
```

**Anything else we need to know?**:
For some reason this appears to be intentional without any explanation of why.  I cannot seem to find any documentation indicating it is supposed to work this way, and the validation code does not indicate why this constraint is required and the user needs to perform delete / create instead of being allowed to modify. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/rbac/validation/validation.go#L160

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mikedanese** [comment]
Role bindings are immutable:

https://github.com/kubernetes/kubernetes/blob/1e3d23c5c3d23ea99b489e1a9d54098bc0b30b43/pkg/apis/rbac/validation/validation.go#L159-L161

**Comment by briantkennedy** [comment]
Yes, I linked to the same code you just posted in the original bug.  Is the rationale for this documented somewhere?  It seems strange that updating a role requires delete then create since no other kubernetes resources impose this constraint which seems to imply that this API might be violating the principle of least surprise.

**Comment by liggitt** [comment]
> It seems strange that updating a role requires delete then create since no other kubernetes resources impose this constraint

There are actually lots of resources that have immutable fields which require delete/create to change (services, pods, storage classes, persistent volumes, etc)

> @liggitt @deads2k is there any literature on why we originally made role references immutable?

There were a couple reasons I remember for this:
- a binding to a different role is a fundamentally different binding. requiring delete/recreate ensures the full list of subjects is intended to be given the new role (as opposed to enabling accidentally patching just the roleRef without knowledge/verification of what subjects are being given different permissions)
- making it immutable allows giving update permission on an existing rolebinding to a user to let them manage the list of subjects without them being able to change the role that is granted to those subjects

@deads2k might recall other reasons. I agree the constraint and rationale should be documented better. 

As an aside, you might consider using `kubectl auth reconcile` for upgrade-safe updating of RBAC objects. It lets you roll out additive-only updates to roles and rolebindings that only adds missing permissions and subjects. If a rolebinding is updated to a new roleRef, it handles a delete/recreate for you

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/website/pull/11254 to address this

/close
