### ISSUE TITLE
Startup of API server is CPU limited, mostly in GC due to OpenAPI

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#66368]
I profiled a moderately complex apiserver startup to see why over the last few releases (1.9 -> 1.11) its gone from 5s to 40s to fully initialize.

The CPU profiles were mostly memory and GC related - looking at the GC profiles revealed that in the first 50s of startup we allocated about 20 million objects, of which 19,900,000 of those allocations were in OpenAPI (serving, reading, or merging).  The next non-openapi related cumulative allocation source was around 100k (the 210th item or so in cumulative lines).  This is on an API server running several aggregated APIs and CRDs, but with no actual objects other than those initialized on startup.

I suspect the vast majority of the OpenAPI work is inefficient or could be memoized / simplified.  It was somewhat shocking to me that it was so high.  This needs to be investigated.

@kubernetes/sig-scalability-bugs @kubernetes/sig-api-machinery-bugs

**Comment by smarterclayton** [comment]
A middle chunk

```
         0     0% 0.054%   10113901 30.67%  k8s.io/kube-openapi/pkg/handler.(*OpenAPIService).UpdateSpec
       256 0.00078% 0.055%    9639491 29.24%  k8s.io/kube-openapi/pkg/handler.toProtoBinary
      2167 0.0066% 0.062%    9192391 27.88%  k8s.io/kube-openapi/pkg/builder.newOpenAPI
         0     0%  0.85%    8933964 27.10%  vendor/gopkg.in/yaml%2ev2.Unmarshal
         0     0%  0.85%    8933964 27.10%  vendor/gopkg.in/yaml%2ev2.unmarshal
         0     0%  0.85%    8285124 25.13%  k8s.io/kube-openapi/pkg/builder.BuildOpenAPIDefinitionsForResource
         0     0%  0.85%    7701471 23.36%  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroup
         0     0%  0.85%    6702002 20.33%  k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun
         0     0%  0.85%    6330278 19.20%  k8s.io/apiserver/pkg/server/routes.OpenAPI.Install
      9053 0.027%  0.87%    6275579 19.03%  vendor/gopkg.in/yaml%2ev2.(*parser).document
         0     0%  0.87%    6275579 19.03%  vendor/gopkg.in/yaml%2ev2.(*parser).parse
    422053  1.28%  2.15%    6257396 18.98%  vendor/gopkg.in/yaml%2ev2.(*parser).mapping
         0     0%  2.15%    5925015 17.97%  k8s.io/kubernetes/pkg/master.completedConfig.New
         0     0%  2.15%    5881226 17.84%  k8s.io/kube-aggregator/pkg/controllers/openapi.BuildAndRegisterAggregator
```

**Comment by liggitt** [comment]
likely this line, which runs per resource, per group:

https://github.com/kubernetes/kubernetes/blob/444e8ec267696030ec2ca8607bd3a3004f93cee2/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L501-L505

it is constructing and discarding the entire openapi schema internally each time in order to get the model for the resource in question.

a better approach could be to construct the schema once internally and reuse the relevant models, limiting the surface area used by the installer to something like:
```
openAPIDefinitions, err := a.group.OpenAPI.APIDefinitionsForResource(defaultVersionedObject)
```

it looks like that would require reworking the kube-openapi BuildOpenAPISpec/BuildOpenAPIDefinitionsForResource/BuildOpenAPIDefinitionsForResources helpers, which don't export the `newOpenApi` methods, and rely on side-effects of calling toSchema which might mean they cannot reuse the `openAPI` object.

**Comment by mbohlool** [comment]
look like `BuildOpenAPIDefinitionsForResource` is building the spec completely each time. The top level function creates a swagger spec and finalize it, not sure about relevance of the part you referenced.

/assign @jennybuckley

**Comment by jennybuckley** [comment]
@mbohlool The relevance is that (I think) it doesn't build the entire swagger spec, only the spec for the dependencies of the provided resource. It is still doing a lot of redundant work, since many of the resources may share dependencies, and it is being built multiple times for each handler, but I don't think it's building the complete openapi spec once per handler.

**Comment by jennybuckley** [comment]
@smarterclayton I'm in the process of verifying that the fix, #68576, actually improves the situation. Can you tell me what tool you used to generate the CPU profiles and GC profiles for the startup of the apiserver?

**Comment by smarterclayton** [comment]
You can start a cpu profile when Kube-apiserver main starts and have a
defer for exit or signal to write to a file.

Alternatively use perf in capture mode and have perf start the Kube
apiserver binary and trace until it exits, then generate a perf report from
it.

The former is easier


On Sep 19, 2018, at 10:22 PM, Jenny Buckley <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> I'm in the process of
verifying that the fix, #68576
<https://github.com/kubernetes/kubernetes/pull/68576>, actually improves
the situation. Can you tell me what tool you used to generate the CPU
profiles and GC profiles for the startup of the apiserver?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/66368#issuecomment-422945019>,
or mute the thread

**Comment by jennybuckley** [comment]
Re: https://github.com/kubernetes/kubernetes/pull/68576#issuecomment-423299076

> Ok, we can dig further after this.  Can you grab a top30 and add it to the
original issue so we know what’s next on the hitlist?  Thanks

```
File: kube-apiserver
Type: alloc_objects
Time: Sep 19, 2018 at 2:58pm (PDT)
Showing nodes accounting for 10857775, 90.37% of 12014928 total
Dropped 787 nodes (cum <= 60074)
      flat  flat%   sum%        cum   cum%
         0     0%     0%    6332343 52.70%  k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain
         0     0%     0%    6154823 51.23%  k8s.io/kubernetes/cmd/kube-apiserver/app.Run
         0     0%     0%    5834452 48.56%  k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1
         0     0%     0%    5631494 46.87%  k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
         0     0%     0%    5576641 46.41%  k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler.(*OpenAPIService).UpdateSpec
         0     0%     0%    5318267 44.26%  k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
         0     0%     0%    5301052 44.12%  k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler.toProtoBinary
         0     0%     0%    5085712 42.33%  k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
         0     0%     0%    4835898 40.25%  main.main
         0     0%     0%    4733475 39.40%  runtime.main
         0     0%     0%    3998954 33.28%  k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/openapi.BuildAndRegisterAggregator
         0     0%     0%    3706624 30.85%  k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.completedConfig.NewWithDelegate
         0     0%     0%    3671437 30.56%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.Unmarshal
         0     0%     0%    3671437 30.56%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.unmarshal
         0     0%     0%    3590911 29.89%  k8s.io/kubernetes/cmd/kube-apiserver/app.createAggregatorServer
    162026  1.35%  1.35%    3079946 25.63%  encoding/json.Unmarshal
    196612  1.64%  2.98%    3078126 25.62%  encoding/json.(*decodeState).object
         0     0%  2.98%    3078126 25.62%  encoding/json.(*decodeState).unmarshal
         0     0%  2.98%    3078126 25.62%  encoding/json.(*decodeState).value
         0     0%  2.98%    3005363 25.01%  k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler.RegisterOpenAPIVersionedService
         0     0%  2.98%    2527236 21.03%  k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler.RegisterOpenAPIService
         0     0%  2.98%    2510205 20.89%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*parser).document
         0     0%  2.98%    2510205 20.89%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*parser).parse
         0     0%  2.98%    2492423 20.74%  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun
    195241  1.62%  4.61%    2477437 20.62%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*parser).mapping
         0     0%  4.61%    2460040 20.47%  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install
    642819  5.35%  9.96%    2041897 16.99%  k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*parser).scalar
         0     0%  9.96%    1943609 16.18%  k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*PathItem).UnmarshalJSON
         0     0%  9.96%    1929989 16.06%  k8s.io/kubernetes/vendor/github.com/googleapis/gnostic/OpenAPIv2.NewDocument
    393253  3.27% 13.23%    1919082 15.97%  encoding/json.Marshal
```

**Comment by apelisse** [comment]
These lines account for a lot:
https://github.com/kubernetes/kube-openapi/blob/master/pkg/handler/handler.go#L162-L204:
> 46.41%  k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/handler.(*OpenAPIService).UpdateSpec


The dance is currently:
```
openapiSpec *spec.Swagger -> 
json.MarshalIndent(openapiSpec, " ", " ") -> 
yaml.Unmarshal(spec, &info) -> 
openapi_v2.NewDocument(info, compiler.NewContext("$root", nil)) -> 
proto.Marshal(document)
```

I'm wondering if we could create the "NewDocument" directly from the `openapiSpec` rather than re-parsing the json bytes ... But I remember it was not obvious.
