### ISSUE TITLE
secret coordinating with serviceaccount is not changed when serviceaccount bind a cluster

### ISSUE THREAD

**Issue by volume-ji** [kubernetes/kubernetes#66365]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
1. I created a serviceaccout named kube-system:kubernetes-dashboard and created a kubenetes-dashboard using the sa to access apiserver.
2. firstly, the sa "kube-system:kubenetes-dashboard" has no RBAC,  k8s can generate automatically a corresponding secret, which has a token including userid and tokenid. Then I used the token to access kubernetes-dashboard. Evidently, I had no RBAC to access apiserver to operate pods, deployments and services because of no binding clusterrole or role.
3. Then I binded ClusterRole “cluster-admin” to serviceaccount, but the secret corresponding with serviceaccount did not change and token of secret did't change either. I use this token to access dashboard, eventually, it did't work also.
4. I deleted deployment resource of kubernetes-dashboard and recreated it, then used this token, it worked.

**What you expected to happen**:
the same with User and Group, when I modify binding policy of serviceaccount, I hope secret corresponding serviceaccount can recreate automatically and the token of secret can work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): k8s v1.10.1
- Cloud provider or hardware configuration: no
- OS (e.g. from /etc/os-release): ubuntu 14.04
- Kernel (e.g. `uname -a`): Linux node208 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: k8s plugin: kubernetes-dashboard
- Others: no

**Comment by xiangpengzhao** [comment]
/sig auth

cc @liggitt :)

**Comment by liggitt** [comment]
A service account token is used for authentication. It identifies a service account to the cluster. 

Changing the authorization policy associated with a user does not modify the authentication credentials. 

It is likely that the dashboard deployment simply needed to be started with sufficient permissions. No regeneration of the token is required after granting RBAC permissions. 

/close

**Comment by volume-ji** [comment]
OK, I get it. you are right, token of the secret associated with ServiceAccount is just a authentication like Group and User, it never change unless restart it. Authorization of RBAC policy binding clusterrole/role is used to grant. It is necessary that I test again.

**Comment by xiangpengzhao** [comment]
@liggitt is it possible that new permissions can take effect immediately after a service account is granted by a rolebinding operation ? People may want to change the API access permissions of their applications without restart the deployment.

**Comment by liggitt** [comment]
> @liggitt is it possible that new permissions can take effect immediately after a service account is granted by a rolebinding operation ?

Yes, and they do take effect immediately. However, some applications must be restarted to make them reattempt initialization operations

**Comment by xiangpengzhao** [comment]
@liggitt Thanks!
