### ISSUE TITLE
How to implement a Vault CSI driver?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#66362]
I would like to use Vault as source of secret for my Kubernetes cluster. I have read this awesome post https://arslan.io/2018/06/21/how-to-write-a-container-storage-interface-csi-plugin/ post by @fatih . I understand the overall process. I would like to implement a `tmpfs` based volume like `Secrets` that provision secrets using Vault.

Few things that are not clear to me:

- How do I use the service account from the Pod where this Volume is mounted to issue the secret ? This will ensure authZ at Vault level.

- Vault secrets come with a ttl. So, we need to periodically refresh the secret. I would like to do this via Node plugin instead of a sidecar. I got too many side cars already and not enough room for real applications.

Is this something that will be possible as a CSI driver?

/kind feature
/sig storage

cc: @saad-ali

**Comment by jsafrane** [comment]
> How do I use the service account from the Pod where this Volume is mounted

Currently you can't. See #64984 for discussion

> We need to periodically refresh the secret

If I understand it correctly, CSI `NodePublish` call of your driver creates a tmpfs and puts the current secret value there. And you need a mechanism to refresh the content of this tmpf periodically, until `NodeUnpublish`. Here I would suggest to spawn a thread (goroutine, ...) that refreshes the tmpfs you mounted. You can update it as you want until Kubernetes calls `NodeUnpublish`.

**Comment by tamalsaha** [comment]
We have implemented the driver here: https://github.com/kubevault/csi-driver

It uses 1.12 to enforce authz using pods's s/a. We are going to cut a release in a few weeks.

/remove-lifecycle stale
