### ISSUE TITLE
ipvs SNAT when clientIP not in clusterCIRD

### ISSUE THREAD

**Issue by fanux** [kubernetes/kubernetes#66363]
```
		} else if len(proxier.clusterCIDR) > 0 {
			// This masquerades off-cluster traffic to a service VIP.  The idea
			// is that you can establish a static route for your Service range,
			// routing to any node, and that node will bridge into the Service
			// for you.  Since that might bounce off-node, we masquerade here.
			// If/when we support "Local" policy for VIPs, we should update this.
			writeLine(proxier.natRules, append(args, "dst,dst", "! -s", proxier.clusterCIDR, "-j", string(KubeMarkMasqChain))...)
		}
```
```
-A KUBE-SERVICES ! -s 192.168.0.0/16 -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
```

```           
client(out cluster)------router(if dstip is clusterip, route to node1,node2,node3)----node1,2,3
                            
```

> /kind feature

**What happened**:
We use ipvs mod, but it SNAT packages when a client not in the cluster, packages may route to the different node in the cluster, so the source IP is different after SNAT, cause MySQL connection failed.

**What you expected to happen**:
I don't want ipvs to SNAT package, can I change the code to : 
```
		} else if len(proxier.clusterCIDR) > 0 {
			// This masquerades off-cluster traffic to a service VIP.  The idea
			// is that you can establish a static route for your Service range,
			// routing to any node, and that node will bridge into the Service
			// for you.  Since that might bounce off-node, we masquerade here.
			// If/when we support "Local" policy for VIPs, we should update this.
			// writeLine(proxier.natRules, append(args, "dst,dst", "! -s", proxier.clusterCIDR, "-j", string(KubeMarkMasqChain))...)
		}
``` 

**How to reproduce it (as minimally and precisely as possible)**:
We expose clusterIP on the router, so  clients can access clusterip out of the cluster

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.10.0

**Comment by xiaoxubeii** [comment]
I think it is not a problem. If use ipvs and set `clusterCIDR`, the packet flow will be `client -> node -> svc -> pod`, your packet will masq as svc ip and then node ip. The response will be  pod -> node -> svc -> client.

**Comment by fanux** [comment]
@xiaoxubeii Mysql source address affinity will cause the issue.  One connection will route to the different node,
so the source IP is different for pod, if pod check the source IP, it will be failed because source IP changed

**Comment by xiaoxubeii** [comment]
Can kube-proxy ipvs [Client-IP based session affinity](https://kubernetes.io/docs/concepts/services-networking/service/) fix your problem? If kube-proxy don't set masq, the packet response cannot return.

**Comment by fanux** [comment]
No, session affinity can't solve this, the client is out of kubernetes cluster. We expose some node in the cluster as a network gateway.

We fixed this by configure router session affinity, using (sip dip:port) hash instead (sip:port dip:port)
