### ISSUE TITLE
kubernetes endpoint 不准确

### ISSUE THREAD

**Issue by l-yb** [kubernetes/kubernetes#66360]
enviroment:
dmidecode | grep "Product Name"
	Product Name: VMware Virtual Platform
	Product Name: 440BX Desktop Reference Platform

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

如图，endpoint不准确，导致请求service的域名地址，请求只有50%成功率：

![image](https://user-images.githubusercontent.com/17609890/42916797-80d61508-8b39-11e8-8500-923e98e82686.png)

**Comment by miaoshixuan** [comment]
you should check your service object 'spec.selector' and your pods label
