### ISSUE TITLE
Change Kubernetes documentation / Bug while editing Dynamic Node Config

### ISSUE THREAD

**Issue by ricklagerweij** [kubernetes/kubernetes#66377]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Editing a node when only the name and namespace is defined to add uid does result in an error.
error: unable to find api field in struct NodeConfigSource for the json field "configMapRef"

remove the name/namespace and add them again including uid does work however.

On the documentation the uid is refered to as kubeletConfigKey.

**What you expected to happen**:
Add uid if needed.

**How to reproduce it (as minimally and precisely as possible)**:
Edit a node and only add Name and Namespace, save configuration and edit again to add uid.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Virtual Machines 
- OS (e.g. from /etc/os-release):
CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):
4.15.13-1.el7.elrepo.x86_64
- Install tools:
Download binaries manual
- Others:

**Comment by RickNEP** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by fedebongio** [comment]
@RickNEP the steps to reproduce are not super clear, can you give us more details? Are you usuing kubectl, patch, post? if you provide more detailed steps we can take a look. Thanks!
