### ISSUE TITLE
[Bug Kubernetes GKE Service Loadbalancer] Sometimes need to rename a service for it to get load balancer

### ISSUE THREAD

**Issue by Krishna1408** [kubernetes/kubernetes#66380]
/kind bug

**What happened**:
I am working with Google Container Engine, sometimes when I delete a service of type Loadbalancer and recreate it, It doesn't get a External-Ip and status shows as `<pending>`. In the google load balancing page I see that a new load balancer for this service is not getting created. When I check the service in GKE UI, I see below:

`Error deleting load balancer (will retry): GCE 200 - RESOURCE_IN_USE_BY_ANOTHER_RESOURCE: The http_health_check resource 'projects/npa-staging/global/httpHealthChecks/k8s-ee7a9eb79312dec5-node' is already being used by 'projects/npa-staging/regions/europe-west1/targetPools/a89516e9a8b4a11e8920442010af0005`

The mentioned resource `a89516e9a8b4a11e8920442010af0005` is being used by service resource of nginx ingress controller. This service was  pointing to another nginx ingress controller service before I deleted it. I've deleted the ingress resources associated already.

But when i create service with another name, it works fine for some reason, a new load balancer is created. Below is my service yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: test-blog-kris
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: blog-port
    port: 2368
    protocol: TCP
    targetPort: blog-port
  selector:
    app: blog
  sessionAffinity: None
  type: LoadBalancer
```
This is what I get when I describe the service:

```
Name:                     test2-ghost
Namespace:                default
Labels:                   app=ghost
Annotations:              <none>
Selector:                 app=ghost
Type:                     LoadBalancer
IP:                       10.43.255.72
Port:                     ghost-port  2368/TCP
TargetPort:               ghost-port/TCP
NodePort:                 ghost-port  30487/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**What you expected to happen**:

The service should be created with same name. This is the response I get when I change the service name:

```
Name:                     test-ghost
Namespace:                default
Labels:                   app=ghost
Annotations:              <none>
Selector:                 app=ghost
Type:                     LoadBalancer
IP:                       10.43.252.109
LoadBalancer Ingress:     35.240.59.243
Port:                     ghost-port  2368/TCP
TargetPort:               ghost-port/TCP
NodePort:                 ghost-port  31777/TCP
Endpoints:                10.40.1.15:2368
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a GKE cluster and create a service and an app.
2. Associate the service with an nginx controller.
3. Delete the service and ingress resources. Delete the pods of app.
4. Create same service again and same app.
5. It may happen that the service will not get created.

**Anything else we need to know?**:
This does not happen always. But I've come accross it couple of times.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.5-gke.0

- Cloud provider or hardware configuration:
Google Container Engine
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
/sig bug 
/sig service

**Comment by bchelli** [comment]
👍

**Comment by vishen** [comment]
I believe this issue is caused because of #66399, and it being fixed by #66400

**Comment by Krishna1408** [comment]
Thanks vishen. I did some testing and it seems the issue is not happening. But on the other side it used to pop up randomly so  I would wait for few more days and see how it goes.

**Comment by jasonkeene** [comment]
Same issue here. We are running on GCP with CFCR.

**Comment by walterdolce** [comment]
I'm not sure I'm on the same boat here. But since I upgraded a cluster to `1.11.2-gke.15` in `europe-west1-b` (because for some reason Google tells me there's not enough resources to create a new cluster in `europe-west2-a`...), when I launch `kubectl` to create my service of type `LoadBalancer` with `loadBalancerIP` pointing to an External IP nothing happens in GCP. 

I get a service pointing to nowhere.

Is there anyone from Google that can explain why/how this suddenly broke?
