### ISSUE TITLE
Pod with NFS volume attached cannot be terminated

### ISSUE THREAD

**Issue by AlexMuresan** [kubernetes/kubernetes#66387]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When trying to delete a nfs-volume pod it gets stuck in "Terminating" state.

**What you expected to happen**:
The pod should be deleted

**How to reproduce it (as minimally and precisely as possible)**:
1. Create one namespace called:  e2e-tests-kubelet-bugtest1
2. Create a second namespace called: e2e-tests-kubelet-bugtest2
3. Create a new nfs-server pod using the nfs-server.yaml
4. Add the ip of the nfs-server pod to the pod-nfs-vol.yaml
5. Create a second pod using the pod-nfs-volume.yaml
6. Delete the nfs-server pod without stopping the server
7. Try to delete pod-nfs-volume pod.

**Anything else we need to know?**:
Recreating this using YAML files is easier (and possibly more accurate):

- nfs-server: https://paste.ubuntu.com/p/ZC2dj4SQbh/
- pod-nfs-volume: https://paste.ubuntu.com/p/YVd6Txc299/

**Environment**:
- Kubernetes version (use `kubectl version`):

    - Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

    - Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"} 

- Cloud provider or hardware configuration:
    - Windows server 1803 nodes

- OS (e.g. from /etc/os-release):
    - NAME="Ubuntu"
    - VERSION="16.04.3 LTS (Xenial Xerus)"
    - ID=ubuntu
    - ID_LIKE=debian
    - PRETTY_NAME="Ubuntu 16.04.4 LTS"
    - VERSION_ID="16.04"

- Kernel (e.g. `uname -a`): 
    - Linux k8s-master-28549959-0 4.15.0-1013-azure #13~16.04.2-Ubuntu SMP Wed May 30 01:39:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andyzhangx** [comment]
@AlexMuresan are you use nfs plugin on Windows? As I know, nfs mount is not supported on Windows

**Comment by AlexMuresan** [comment]
@andyzhangx  I was using [this](https://sourceforge.net/projects/winnfsd/) for nfs mount functionality.

**Comment by andyzhangx** [comment]
@AlexMuresan I mean how do you use the nfs client in k8s? The following mount logic in mount_windows.go is written by myself, now it only supports cifs protocol on Windows:

https://github.com/kubernetes/kubernetes/blob/2486d51eb9d9bb3b43fba23b2ac52d4a863e3973/pkg/util/mount/mount_windows.go#L81-L82

**Comment by andyzhangx** [comment]
@AlexMuresan this test could not run on Windows since NFS plugin on Windows is not implemented, eventually it will call:
https://github.com/kubernetes/kubernetes/blob/2486d51eb9d9bb3b43fba23b2ac52d4a863e3973/pkg/util/mount/mount_windows.go#L81-L82

**Comment by AlexMuresan** [comment]
@andyzhangx Even so, the test produced pods that could not be terminated. As I see it, regardless of whether or not the test passes, the pods should not be stuck in the `Terminating` state.

**Comment by msau42** [comment]
You need to delete the nfs-clients before you delete the nfs-server otherwise client unmount will hang.

**Comment by ondravondra** [comment]
This happens on linux too. At least on digitalocean.
