### ISSUE TITLE
Add restrictions on tolerations and nodeSelectors to PodSecurityPolicy

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#66416]
/kind feature

Sites may have reserved nodes such as masters where you do not want particular users to land workload on. You should be able to specify what nodeSelectors are allowed, and what tolerations are allowed.

**Comment by kfox1111** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by k82cn** [comment]
@kfox1111 , suppose this is part of PodSecurityPolicy proposal, would you help to create an issue to list sub-tasks? it's easier to trace the progress, e.g. how many PR/issues remain :)

**Comment by liggitt** [comment]
I don't think PSP would be the vehicle for that. Requests for the ability to control scheduling is already covered by existing issues/feature requests: #48041 https://github.com/kubernetes/kubernetes/issues/59366 https://github.com/kubernetes/community/pull/1937

/close

**Comment by liggitt** [comment]
in the meantime, the [PodTolerationRestriction](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtolerationrestriction) and [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector) admission plugins offer preliminary alpha-level controls over bounding what selectors and tolerations are permitted in given namespaces
