### ISSUE TITLE
kubeadm - list all components version command

### ISSUE THREAD

**Issue by magixyu** [kubernetes/kubernetes#66420]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
Need the components version for certain k8s release

**What you expected to happen**:
kubeadm list-versions
it will list all the components versions in current kubeadm, including:
coredns etc.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
this is already possible in 1.11 using the following command:
```
kubeadm config images list --kubernetes-version=x.xx.x
```
replacing x.xx.x would give you the list of all the control plane and addon images, including coredns.
if you are not happy with this functionality, please open an issue in the `kubernetes/kubeadm` repository and make a proposal.

thanks.
/close

**Comment by magixyu** [comment]
Thank you very much!

Tristan
