### ISSUE TITLE
fsHandler.go:121: failed to collect filesystem stats

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#66421]
/kind bug
/sig node

**What happened**:
I run kubelet at physical machine and find below logs with `systemctl status kubelet`:
```
kubelet[182959]: E0720 01:06:15.454048  182959 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff with output stdout: 4085180        /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff
kubelet[182959]: , stderr: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/rls2BZc3TEaxM0dufaYDRQ/0/index/_kbf.si’: No such file or directory
kubelet[182959]: - exit status 1, rootInodeErr: <nil>, extraDiskErr: <nil>
kubelet[182959]: E0720 01:27:19.828180  182959 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff with output stdout: 4160724        /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff
kubelet[182959]: , stderr: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/KhMTs8WhTwyahUoPEuHQHQ/0/index/_1gs7_Lucene50_0.tip’: No such file or directory
kubelet[182959]: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/KhMTs8WhTwyahUoPEuHQHQ/0/index/_1gs7.nvm’: No such file or directory
kubelet[182959]: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/KhMTs8WhTwyahUoPEuHQHQ/0/index/_1gs7.dim’: No such file or directory
kubelet[182959]: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/KhMTs8WhTwyahUoPEuHQHQ/0/index/_1gs7.fnm’: No such file or directory
kubelet[182959]: - exit status 1, rootInodeErr: <nil>, extraDiskErr: <nil>
kubelet[182959]: E0720 05:58:03.368413  182959 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff with output stdout: 4267452        /software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff
kubelet[182959]: , stderr: du: cannot access ‘/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff/usr/share/elasticsearch/data/nodes/0/indices/3qK3SN_zToGdmqJ5PdEkQA/3/index/_1efi.cfs’: No such file or directory
kubelet[182959]: - exit status 1, rootInodeErr: <nil>, extraDiskErr: <nil>
```
`/software/docker/overlay2/b9bb924fa49e4f1414894eba364c2c80f6e3924122bcc01d09b26a300ba559a9/diff` exists, but `.cfs`,`.dim`  files and so on do not exist.

But i check all my pods, they are all fine.

I really do not know should i ignore them or not.

I look some issues like above but do not get useful info.

I tired to restart kubelet service, the logs miss, but after a while, above logs occur again.

My environment is CentOS7.4, and k8s version is:
```
$ kubelet --version
Kubernetes v1.9.7
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by silenceper** [comment]
same problem

kubelet 1.9.1

**Comment by timothyliu** [comment]
same problem k8s v1.10.11

**Comment by m1schka** [comment]
same with k8s 1.11.7 on AWS with EBS root volume

**Comment by warmchang** [comment]
What is the status of the node in which these prints appear? Notready or Ready?

**Comment by daixiang0** [comment]
@warmchang the node of status is Ready, also all pod.

**Comment by Dionysusio** [comment]
same problem with k8s v1.14.2

**Comment by dpoison** [comment]
We are also facing the same issue with k8s v1.10.5 
kubenetes node is going down for a few minutes randomly on every alternate days. Node goes in NotReady state.  Meanwhile, all pods get restarted. below is the version details. 
Below 2 errors are found all the time when node goes not ready state. 

> Jun 26 20:30:31 node03 kubelet-wrapper[1086]: I0626 20:30:31.440854    1086 kubelet.go:1799] skipping pod synchronization - [PLEG is not healthy: pleg was last seen active 3m16.958147114s ago; threshold is 3m0s]

> Jun 26 20:23:21 node03 kubelet-wrapper[1086]: E0626 20:23:21.835422    1086 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: failed to exec du - fork/exec /usr/bin/nice: resource temporarily unavailable, rootInodeErr: failed to exec cmd [find /var/lib/docker/overlay2/cb5352074b6334c351eacbe8b79a7efa19851f46860d48e8bfa8a807cb191cd3/diff -xdev -printf .] - fork/exec /usr/bin/find: resource temporarily unavailable; stderr: , extraDiskErr: failed to exec du - fork/exec /usr/bin/nice: resource temporarily unavailable

Any help is highly appreciated.

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
update

**Comment by tedyu** [comment]
v1.10.5 was quite old.

I wonder if this is reproducible on 1.15+

**Comment by takakawa** [comment]
same problem with k8s v1.18.3
`
E0623 22:03:40.147960   35377 fsHandler.go:118] failed to collect filesystem stats - rootDiskErr: could not stat "/var/lib/docker/overlay2/ea530e7d335a9f8dcafead409294cf42476eb57d86c7b0b0e34d281a53393032/diff" to get inode usage: stat /var/lib/docker/overlay2/ea530e7d335a9f8dcafead409294cf42476eb57d86c7b0b0e34d281a53393032/diff: no such file or directory, extraDiskErr: could not stat "/var/lib/docker/containers/b256dd634c306c260e53eaa6ef42a4d7db0d376b66ea31141e98d0b9db4a7af8" to get inode usage: stat /var/lib/docker/containers/b256dd634c306c260e53eaa6ef42a4d7db0d376b66ea31141e98d0b9db4a7af8: no such file or directory
`

**Comment by zhangzhaorui** [comment]
same problem with k8s v1.18.16
kubelet: E0225 12:09:27.779754  304967 fsHandler.go:118] failed to collect filesystem stats - rootDiskErr: could not stat "/data/container/overlay2/33edc2fb9260631d61592a66e277afc245a03d9ae854dcba78efa60bd70d389c/diff" to get inode usage: stat /data/container/overlay2/33edc2fb9260631d61592a66e277afc245a03d9ae854dcba78efa60bd70d389c/diff: no such file or directory, extraDiskErr: could not stat "/data/container/containers/b62d4fc4a34579b4d0d8cea6b5da587884a269d14a322080bb804441c98cb18e" to get inode usage: stat /data/container/containers/b62d4fc4a34579b4d0d8cea6b5da587884a269d14a322080bb804441c98cb18e: no such file or directory

**Comment by zhangzhaorui** [comment]
@takakawa hi   if your problem is solved？

**Comment by ifelsefi** [comment]
`1.19.10`:

Repeating in `kubelet`:

```
2021-08-19T00:32:21.480634776Z E0819 00:32:21.480130    2627 fsHandler.go:114] failed to collect filesystem stats - rootDiskErr: could not stat "/var/lib/docker/overlay2/207abe37e2d701755018972836d849fefe3b11aceaee5bc6ea10a62af4ba4ab5/diff" to get inode usage: stat /
var/lib/docker/overlay2/207abe37e2d701755018972836d849fefe3b11aceaee5bc6ea10a62af4ba4ab5/diff: no such file or directory, extraDiskErr: could not stat "/var/lib/docker/containers/f2c0bf6ed87f031cbc04837075c6409e110824e61fe2f6c78bc0f2c5dd323f28" to get inode usage: st
at /var/lib/docker/containers/f2c0bf6ed87f031cbc04837075c6409e110824e61fe2f6c78bc0f2c5dd323f28: no such file or directory
```

**Comment by YanzhaoLi** [comment]
Hitting the same problem on k8s 1.12.2

**Comment by KeithTt** [comment]
Same problem on 1.16.6
