### ISSUE TITLE
Azure - ILB Frontend IP configuration does not change while updating service

### ISSUE THREAD

**Issue by rite2nikhil** [kubernetes/kubernetes#66424]
/kind bug

**What happened**:
ILB Frontend IP configuration does not change while updating service
**What you expected to happen**:
LB Frontend IP configuration should get updated
**How to reproduce it (as minimally and precisely as possible)**:
Source issue : https://github.com/Azure/AKS/issues/532
AKS service is created using .yaml manifest. ILB is described as it is shown in the documentation:

annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
  type: LoadBalancer
  loadBalancerIP: 10.240.200.2
ILB instance with the "kubernetes-internal" name is created with a correct private IP address pointing to the service described. If I change the "loadBalancerIP" to another internal IP address and re-deploy the service, the last is deployed with the correct new IP address, but "kubernetes-internal" ILB still has the old Frontend IP configuration.

**Environment**:
- Cloud provider or hardware configuration:
Azure

**Comment by feiskyer** [comment]
This also not works for public LB.

/cc @karataliu @fseldow Could you fix the bug and cherry pick to old versions?
