### ISSUE TITLE
pull-kubernetes-e2e-kops-aws - VpcLimitExceeded

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#66428]
Seeing sporadic failures of the kops aws e2e due to VpcLimitExceeded

```
W0720 04:43:38.961] W0720 04:43:38.960917    5836 executor.go:130] error running task "VPC/e2e-97882-dba53.test-cncf-aws.k8s.io" (9m58s remaining to succeed): error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/66426/pull-kubernetes-e2e-kops-aws/97882
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kops-aws

@kubernetes/sig-testing-misc @kubernetes/sig-aws-misc 
/assign @fejta 
(test-infra on-call)

**Comment by justinsb** [comment]
I'm looking at this now.  It appears that we have some test clusters that aren't shutting down (i.e. are more than one day old), and that these are using most of our capacity.
