### ISSUE TITLE
The `wait` command about condition name for use

### ISSUE THREAD

**Issue by xingxingxia** [kubernetes/kubernetes#66439]
Issue 1:
In the help info `kubectl help wait`, it mentions `condition=available`.
When I first time uses it for pod, it always timeout. **This confuses user**.
Finally I know it depends on resource type, user should check .status.conditions, pod uses `condition=ready`, pod controller uses `condition=available`.
It should clarify this in help info.

Issue 2:
For resource that does not have .status.conditions:
kubectl wait type/resource --for=condition=available
The output is:
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
The message `Failure is of the type string, expected map[string]interface{}` is not clear for end user.
Suggest improve the prompt.
Thanks!

**Comment by astrieanna** [comment]
I was confused by the same thing today. It would be helpful if the `--help` output could list the possible conditions to check for on different resource types.

**Comment by ensonic** [comment]
The docs really need to listen for can be given as condition.

**Comment by notjames** [comment]
/reopen

Would like to know what the proper condition value should be used when waiting for a service (specifically a loadbalanced service) is available. I've tried `ready`, `available`, `complete`, and like a few more. Nothing works. kthxbye! ;)

**Comment by Escape17** [comment]
> 
> 
> /reopen
> 
> Would like to know what the proper condition value should be used when waiting for a service (specifically a loadbalanced service) is available. I've tried `ready`, `available`, `complete`, and like a few more. Nothing works. kthxbye! ;)

We've been looking for this too.

What condition should be used to check the readiness of a service? 

Please can all valid conditions be listed somewhere i.e. -h ?

**Comment by astrieanna** [comment]
@Escape17 I think it might not be possible to use conditions to wait because `service.status` doesn't have a condition field. At least according to `kubectl explain`:
```
$ kubectl explain service.status
KIND:     Service
VERSION:  v1

RESOURCE: status <Object>

DESCRIPTION:
     Most recently observed status of the service. Populated by the system.
     Read-only. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status

     ServiceStatus represents the current status of a service.

FIELDS:
   loadBalancer	<Object>
     LoadBalancer contains the current status of the load-balancer, if one is
     present.
```

In contrast, pod has a `pod.status.conditions` field, and the explain for `pod.status.conditions.type` links to the strings that can be waited on.

```
$ kubectl explain pod.status.conditions
KIND:     Pod
VERSION:  v1

RESOURCE: conditions <[]Object>

DESCRIPTION:
     Current service state of pod. More info:
     https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions

     PodCondition contains details for the current condition of this pod.

FIELDS:
   lastProbeTime	<string>
     Last time we probed the condition.

   lastTransitionTime	<string>
     Last time the condition transitioned from one status to another.

   message	<string>
     Human-readable message indicating details about last transition.

   reason	<string>
     Unique, one-word, CamelCase reason for the condition's last transition.

   status	<string> -required-
     Status is the status of the condition. Can be True, False, Unknown. More
     info:
     https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions

   type	<string> -required-
     Type is the type of the condition. More info:
     https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
```

**Comment by notjames** [comment]
@astrieanna Hmm. So that's interesting! So `helm` is able to properly wait given the `--wait` with a good `--timeout` argument. I'm not [yet] sure how `helm` implements their wait, but it properly works for an entire package. Our use-case is that sometimes we'd like to apply native k8s manifests without relying on `helm`. There has to be a way to properly wait for a service even though `service` doesn't provide a `status`, which seems strange. Perhaps the problem is that `service` doesn't provide a status.
