### ISSUE TITLE
Implement mechanism for certificates rotation in aggregated API servers

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#66448]
### Problem outline

When we want to rotate certificates for aggregated API servers, we have to restart (kill) pods in order for API server to pick the new certificates. It would be very useful to implement some sort of self-awareness for the aggregated API servers, so they can pick-up new certificates when they're updated, without user interaction.

### Problem description

If we have certificate files in pods, that are provided by some volumeSource, that can be persistent storage or a Secret, when file gets changed on the volume, the kubelet updates file in the pod usually in matters of few seconds.

However, aggregated API servers are not self-aware of such change and users have to manually restart the pods. 

This brings additional complexity, especially if you want to automate the process.

The first problem is that you need to know what pods you need to restart. But the potentially biggest problem is that you need additional permissions to do so. That would include RBAC permissions for listing pods, listing deployments and for deleting pods. That can make a security issue in some setups. By making aggregated API servers sort of self-aware, this could be avoided.

### Problem solution

Create a health check somewhere in `k8s.io/apiserver`, that utilizes a file watcher to watch for certificates changes. When certificate is changed, fail a health check. Failing health check will restart the pod without user interaction.

This could be the most easiest and simplest solution to the problem.

#### Potential caveats

Such feature should/could be optional and guarded by a flag, let's name it `--restart-on-certs-change`.

Some delay could be required between restarting pods. We probably don't want to kill all pods in the same time. This is up to be discussed.

I would like to work on this issue, so feel free to assign it to me.

/kind feature
/sig api-machinery
/area apiserver
/cc @deads2k @sttts

**Comment by liggitt** [comment]
> Such feature should/could be optional and guarded by a flag, let's name it --restart-on-certs-change.

this could also be done by a purpose-built container that watched the same input files

**Comment by deads2k** [comment]
> Such feature should/could be optional and guarded by a flag, let's name it --restart-on-certs-change.
> 
> this could also be done by a purpose-built container that watched the same input files. as you point out, you likely would not want to restart all apiservers at once, which makes it unclear whether you'd want to build in the restart logic to the individual servers

That coordination would certainly work and be a valuable tool for someone to build to help manage rolling generic processes if we never get a pod restart.  However, being able to have a "usually won't all go down together" option built-in is easy to understand and will resolve the problem until then.

It isn't a stretch to say that if your process isn't fulfilling the current intent of the pod, it isn't healthy.  This gives us a thing between dynamic config reloading and nothing.

A container that can coordinate based on a service would be really cool, but I think that'd be a separate thing.
