### ISSUE TITLE
Kubelet won't start on Azure VMSS after upgrading to k8s v.1.11.0

### ISSUE THREAD

**Issue by helgifeiti** [kubernetes/kubernetes#66449]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Updated Kubernetes to v1.11 on my k8s cluster running on Azure VMSS and now, kubelet won't start reporting error:
` failed to run Kubelet: could not init cloud provider "azure": No credentials provided for AAD application.`

I have the azure.json file located under `/etc/kubernetes/`, where it was working fine in k8s v1.10.4 and it is in this format: 

    {
      "vmType": "vmss",
      "tenantId": "<tenant_id>",
      "aadTenantId": "<aad_tenant_id>",
      "aadClientId": "<aad_client_id>",
      "aadClientSecret": "<aad_client_secret>",
      "subscriptionId": "<subscription_id>",
      "resourceGroup": "kubitest1",
      "primaryScaleSetName":"kubitest1-node",
      "vnetName": "kubitest1",
      "vnetResourceGroup": "kubitest1",
      "subnetName": "kubitest1-master",
      "securityGroupName": "kubitest1",
      "location": "northeurope"
    }

**What you expected to happen**:

Kubelet should start without a problem. 

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade Kubernetes to v1.11 on a k8s cluster running on Azure VMSS and restart kubelet. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.11.0
- Cloud provider or hardware configuration: Azure VMSS
- OS: ubuntu
- Kernel: Linux kubitest1-master000000 4.15.0-1014-azure #14~16.04.1-Ubuntu SMP Thu Jun 14 15:42:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/sig azure
/area kubelet

**Comment by yastij** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@helgifeiti From the error log, AADClientSecret and AADClientID is empty. Could you check again whether `azure.json` and `kubelet --cloud-config` are configured correctly?

**Comment by feiskyer** [comment]
There is no aadTenantId option, only tenantId is used. Have you checked whether aadClientId and aadClientSecret are set? From the logs, both of them are empty.

**Comment by feiskyer** [comment]
The issue is not active for a long time. Let's close it.

@helgifeiti Feel free to reopen it if you still have issues.

/close
