### ISSUE TITLE
KUBE-PROXY: Failed to execute iptables-restore: exit status 2

### ISSUE THREAD

**Issue by bamb00** [kubernetes/kubernetes#66454]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
kube-proxy pod return error failed to execute iptables-restore exit status 2
**What you expected to happen**:
kube-proxy pod in running state
**How to reproduce it (as minimally and precisely as possible)**:

    # kubectl logs kube-proxy-t4x8x -n kube-system
	I0720 05:19:28.533050       1 feature_gate.go:190] feature gates: map[]
	time="2018-07-20T05:19:33Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: ERROR: could not insert 'ip_vs': Exec format error\ninsmod /lib/modules/3.10.0-862.9.1.el7.x86_64/kernel/net/netfilter/ipvs/ip_vs.ko.xz`, error: exit status 1"
	time="2018-07-20T05:19:33Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."
	W0720 05:19:33.061016       1 server_others.go:289] Flag proxy-mode="" unknown, assuming iptables proxy
	I0720 05:19:33.061964       1 server_others.go:138] Using iptables Proxier.
	W0720 05:19:33.067870       1 proxier.go:468] clusterCIDR not specified, unable to distinguish between internal and external traffic
	I0720 05:19:33.067975       1 server_others.go:171] Tearing down inactive rules.
	I0720 05:19:34.856307       1 server.go:426] Version: v1.9.5
	I0720 05:19:34.865582       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 524288
	I0720 05:19:34.865626       1 conntrack.go:52] Setting nf_conntrack_max to 524288
	I0720 05:19:34.869796       1 conntrack.go:83] Setting conntrack hashsize to 131072
	I0720 05:19:34.877312       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
	I0720 05:19:34.877355       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
	I0720 05:19:34.877526       1 config.go:102] Starting endpoints config controller
	I0720 05:19:34.877545       1 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
	I0720 05:19:34.877580       1 config.go:202] Starting service config controller
	I0720 05:19:34.877584       1 controller_utils.go:1019] Waiting for caches to sync for service config controller
	I0720 05:19:34.977687       1 controller_utils.go:1026] Caches are synced for service config controller
	I0720 05:19:34.977695       1 controller_utils.go:1026] Caches are synced for endpoints config controller
	E0720 05:19:35.934630       1 proxier.go:1667] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.6.0: invalid mask `128' specified
	Error occurred at line: 8
	Try `iptables-restore -h' or 'iptables-restore --help' for more information.
	)
	E0720 05:19:35.952002       1 proxier.go:1667] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.6.0: invalid mask `128' specified
	Error occurred at line: 12
	Try `iptables-restore -h' or 'iptables-restore --help' for more information.
	)
	E0720 05:20:05.226208       1 proxier.go:1667] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.6.0: invalid mask `128' specified
	Error occurred at line: 25
	Try `iptables-restore -h' or 'iptables-restore --help' for more information.
	)

**Anything else we need to know?**:

	kube-system   etcd-master-01                      1/1       Running             7          1d
	kube-system   kube-apiserver-master-01            1/1       Running             8          1d
	kube-system   kube-controller-manager-master-01   1/1       Running             7          1d
	kube-system   kube-dns-6f4fd4bdf-hpwjd                   0/3       ContainerCreating   0          19h
	kube-system   kube-proxy-t4x8x                           1/1       Running             0          17h
	kube-system   kube-scheduler-master-01            1/1       Running             6          1d
	kube-system   kubernetes-dashboard-68d7c968ff-hn9qf      0/1       ContainerCreating   0          1d
	kube-system   weave-net-5jpwj                            1/2       CrashLoopBackOff    150        12h

**Environment**:
- Kubernetes version (use `kubectl version`):  Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`):  3.10.0-862.9.1.el7.x86_64
- Install tools:
- Others:

**Comment by xiaoxubeii** [comment]
Can you output your iptables rule by `iptables-save`? It seems that you specify a wrong cidr.

**Comment by bamb00** [comment]
# iptables-save
	# Generated by iptables-save v1.4.21 on Fri Jul 20 14:56:04 2018
	*mangle
	:PREROUTING ACCEPT [4397728:1947643879]
	:INPUT ACCEPT [4357648:1946084295]
	:FORWARD ACCEPT [0:0]
	:OUTPUT ACCEPT [4354827:1937179934]
	:POSTROUTING ACCEPT [4355450:1937204034]
	-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
	COMMIT
	# Completed on Fri Jul 20 14:56:04 2018
	# Generated by iptables-save v1.4.21 on Fri Jul 20 14:56:04 2018
	*nat
	:PREROUTING ACCEPT [40783:1890698]
	:INPUT ACCEPT [1086:345485]
	:OUTPUT ACCEPT [160630:9640415]
	:POSTROUTING ACCEPT [160630:9640415]
	:DOCKER - [0:0]
	:KUBE-MARK-DROP - [0:0]
	:KUBE-MARK-MASQ - [0:0]
	:KUBE-POSTROUTING - [0:0]
	:KUBE-SERVICES - [0:0]
	-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
	-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
	-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
	-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
	-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
	-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
	-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
	-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
	-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
	-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
	-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
	-A DOCKER -i docker0 -j RETURN
	-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
	-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
	-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
	COMMIT
	# Completed on Fri Jul 20 14:56:04 2018
	# Generated by iptables-save v1.4.21 on Fri Jul 20 14:56:04 2018
	*filter
	:INPUT ACCEPT [2656726:1219584620]
	:FORWARD ACCEPT [0:0]
	:OUTPUT ACCEPT [2655184:1213839545]
	:DOCKER - [0:0]
	:DOCKER-ISOLATION - [0:0]
	:KUBE-FIREWALL - [0:0]
	:KUBE-FORWARD - [0:0]
	:KUBE-SERVICES - [0:0]
	:WEAVE-NPC - [0:0]
	:WEAVE-NPC-DEFAULT - [0:0]
	:WEAVE-NPC-INGRESS - [0:0]
	-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
	-A INPUT -j KUBE-FIREWALL
	-A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
	-A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
	-A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
	-A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
	-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
	-A FORWARD -j DOCKER-ISOLATION
	-A FORWARD -o docker0 -j DOCKER
	-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
	-A FORWARD -i docker0 -o docker0 -j ACCEPT
	-A FORWARD -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	-A FORWARD -s 192.168.122.0/24 -i virbr0 -j ACCEPT
	-A FORWARD -i virbr0 -o virbr0 -j ACCEPT
	-A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
	-A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
	-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
	-A OUTPUT -j KUBE-FIREWALL
	-A OUTPUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
	-A DOCKER-ISOLATION -j RETURN
	-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
	-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
	-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
	-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
	-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
	-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT
	COMMIT
	# Completed on Fri Jul 20 14:56:04 2018
