### ISSUE TITLE
Move coredns/coredns to k8s.gcr.io for 1.10 and 1.9

### ISSUE THREAD

**Issue by destijl** [kubernetes/kubernetes#66460]
Head is using k8s.gcr.io:
https://github.com/kubernetes/kubernetes/blob/90f681be107cf67aa610b836a6a45f99e0bf04f2/cluster/addons/dns/coredns/coredns.yaml.in#L109

It would be great if you could also update the 1.10 and 1.9 release branches to do the same so we can vulnerability scan those images.

```
gcastle@jnt:~/go/src/k8s.io/kubernetes$ git checkout --quiet upstream/release-1.10
gcastle@jnt:~/go/src/k8s.io/kubernetes$ g coredns/coredns
cluster/addons/dns/coredns.yaml.sed:        image: coredns/coredns:1.0.6
cluster/addons/dns/coredns.yaml.in:        image: coredns/coredns:1.0.6
cluster/addons/dns/coredns.yaml.base:        image: coredns/coredns:1.0.6
cmd/kubeadm/app/phases/addons/dns/manifests.go:        image: coredns/coredns:{{ .Version }}
gcastle@jnt:~/go/src/k8s.io/kubernetes$ git checkout --quiet upstream/release-1.9
gcastle@jnt:~/go/src/k8s.io/kubernetes$ g coredns/coredns
cluster/addons/dns/coredns.yaml.sed:        image: coredns/coredns:1.0.1
cluster/addons/dns/coredns.yaml.in:        image: coredns/coredns:1.0.1
cluster/addons/dns/coredns.yaml.base:        image: coredns/coredns:1.0.1
cmd/kubeadm/app/phases/addons/dns/manifests.go:        image: coredns/coredns:{{ .Version }}
```
/kind bug
/sig auth

@rajansandeep

**Comment by rajansandeep** [comment]
@destijl To clarify, we'll need gcr.io images for CoreDNS 1.0.1 and 1.0.6 for k8s v1.9 and v1.10 respectively?

**Comment by chrisohaver** [comment]
Can we move 1.10 and 1.9 to coredns version 1.1.3.

**Comment by fturib** [comment]
Pushing image of CoreDNS to gcr.io can be done, right now, only by @thockin .
He is out of office for 2 weeks from now.

Once the images are pushed, I guess we could update the manifest of CoreDNS to to point to the repository gcr.io in order to retrieve the images.
=> That would be for future releases of k8s 1.9 and  k8s 1.10

@destijl : is that what you expect ? Or you just need to have the 2 images in gcr.io for scan purpose  ?

**Comment by chrisohaver** [comment]
> => That would be for future releases of k8s 1.9 and k8s 1.10

Why not just move to coredns 1.1.3 at that time?  Why continue to use an old CoreDNS?

**Comment by chrisohaver** [comment]
1.0.x -> 1.1.X major version change, possible custom configuration incompatibilities?

**Comment by chrisohaver** [comment]
It would get validation in the e2e tests... however, I think the minor version change means that we introduced some backward incompatible changes between those versions.   Which means we could break deployments if people have customized their configurations to use a deprecated plugin/option.  So not a good idea to upgrade.

**Comment by ihmccreery** [comment]
Ping.  This is still causing pain for image vuln scanning.

**Comment by dims** [comment]
/assign @BenTheElder (as Ben is on call)

cc @ixdy

**Comment by BenTheElder** [comment]
we've been discussing this on slack and fighting with manifest tool and creds from https://github.com/kubernetes/kubernetes/issues/68020#issuecomment-417038769, I'm happy to make this happen but I can't get the tooling to work right, the manifest tool push 401s due to GCR and auth.

**Comment by BenTheElder** [comment]
images should be in now.

**Comment by BenTheElder** [comment]
1.0.1 [gcr.io/google-containers/coredns@sha256:f7d9856326079567968e19e18e1b067b137287ca7ffd9d57d01f2fbcdca5354a](https://gcr.io/google-containers/coredns@sha256:f7d9856326079567968e19e18e1b067b137287ca7ffd9d57d01f2fbcdca5354a)
1.0.6 [gcr.io/google-containers/coredns@sha256:ddcc984408e779e0baa92aab754b8988ba57d3ca3478837e186c90350624374b](https://gcr.io/google-containers/coredns@sha256:ddcc984408e779e0baa92aab754b8988ba57d3ca3478837e186c90350624374b)

**Comment by samdamana** [comment]
It looks like 1.9 and 1.10 are still using `coredns/coredns` which we cannot vuln scan. Any chance of someone changing those references in 1.9/10 to `k8s.gcr.io/coredns` as it appears in 1.11+?

**Comment by rajansandeep** [comment]
According to @BenTheElder and [this comment](https://github.com/kubernetes/kubernetes/pull/70369#issuecomment-444961117), 1.9 is no longer supported. CoreDNS image is available as gcr.io in release 1.10

This issue has been resolved.
/close
