### ISSUE TITLE
Improve unit tests of generic_scheduler 

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#66468]
**Is this a BUG REPORT or FEATURE REQUEST?**: clean-up

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

Unit tests of generic_scheduler.go includes [a hack](https://github.com/kubernetes/kubernetes/blob/b1e9e747fb777a49ecd204c5e97a5d00d9fcfea1/pkg/scheduler/core/generic_scheduler_test.go#L675) that should be removed. We should add a parameter to the test cases that indicates the expected score and then check if the returned value of the functions matches this expected value.

Below is the hack that we should clean up.

```go
if test.test == "test priority of larger pod with machine with zero-request pod" {
	if hp.Score == expectedPriority {
		t.Errorf("%s: expected non-%d for all priorities, got list %#v", test.test, expectedPriority, list)
	}
}
```

/sig scheduling

**Comment by islinwb** [comment]
I'll work on this.
/assign
