### ISSUE TITLE
Invalid openapi-spec being generated.

### ISSUE THREAD

**Issue by PhilipGough** [kubernetes/kubernetes#66474]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/assign cblecker

**What happened**:
While working on #58677 there was a repeated failing test in the verify job `make verify WHAT=openapi-spec` reporting an outdated `swagger.json` file. The test was passing locally. Running `hack/update-openapi-spec.sh` created no diff in the codebase.

Since this is a long running PR I thought we may have missed something so to test I checked out master, deleted the `swagger.json` file and ran `make clean` then `make update`.

This produced the exact same `swagger.json` file that was produced on the linked PR branch with an older version generated in the spec  `v1.11.0`.

To get the test to pass on PR I checked out that file from current master and committed it. Job succeeds.   

**What you expected to happen**:
The `swagger.json` file to be updated with the correct Kubernetes version and the verify openapi-spec test to pass.

**How to reproduce it (as minimally and precisely as possible)**:
I'm on OS X. Delete `swagger.json`, run `hack/update-openapi-spec.sh`, check the `git diff`. I also tried to delete the build images that I had locally. This didn't make a difference.

**Environment**:
- OS (e.g. from /etc/os-release): OS X 10.13.5

**Comment by dims** [comment]
Just tried this, don't see a problem. Can you please paste your `git diff`?

```
[dims@dims-mac 22:47] ~/go/src/k8s.io/kubernetes ⟩ rm ./api/openapi-spec/swagger.json
[dims@dims-mac 22:47] ~/go/src/k8s.io/kubernetes ⟩ hack/update-openapi-spec.sh
+++ [0721 22:47:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [0721 22:47:52] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0721 22:47:58] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0721 22:48:06] Building go targets for darwin/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
2018/07/21 22:48:14 Code for OpenAPI definitions generated
+++ [0721 22:48:15] Building go targets for darwin/amd64:
    ./vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0721 22:48:17] Building go targets for darwin/amd64:
    cmd/kube-apiserver
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /var/folders/wr/8hznwwy91lqbbt8b2k99hxtw0000gn/T/tmp.Ej1e5pH4 --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
+++ [0721 22:51:02] On try 1, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
+++ [0721 22:51:02] Starting kube-apiserver
+++ [0721 22:51:12] On try 11, apiserver: : ok
+++ [0721 22:51:12] Updating
    hack/../api/openapi-spec
+++ [0721 22:51:13] SUCCESS
+++ [0721 22:51:13] Clean up complete
[dims@dims-mac 22:51] ~/go/src/k8s.io/kubernetes ⟩ git diff
[dims@dims-mac 22:52] ~/go/src/k8s.io/kubernetes ⟩ uname -a
Darwin dims-mac.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
[dims@dims-mac 22:52] ~/go/src/k8s.io/kubernetes ⟩ go version
go version go1.10.2 darwin/amd64
```
