### ISSUE TITLE
kubectl delete pod --grace-period=0 --force intermittently hangs

### ISSUE THREAD

**Issue by StephanX** [kubernetes/kubernetes#66478]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Intermittently, after successfully deleting a pod with --force and --grace-period=0, the command never returns and must be CTRL+c exited.

machine: > kubectl delete pod --force --grace-period=0 some_pod
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "some_pod" force deleted
< much time passes >

**Anything else we need to know?**:
This seems to have started only in recent (past month) versions.  I've experienced it on four different machines and clusters. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
 AWS

- OS (e.g. from /etc/os-release):
Darwin/OSX (on both Apple hardware and, ah, hackintosh versions.)

- Kernel (e.g. `uname -a`):
Darwin xx.lan 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

- Install tools:
Homebrew

**Comment by liggitt** [comment]
You can avoid kubectl waiting for the pod object to be removed before returning by setting --wait=false

**Comment by StephanX** [comment]
Ah, thanks @liggitt I wasn't aware.

**Comment by dwgillies-bluescape** [comment]
What is it about --force and --grace-period 0 allows the pod to stay around, and allows the command to hang forever, as it just did for me right now.  In a few years will we be typing : 

delete pod $pod_name -n $namespace --grace-period 0 --force --wait=false --i-mean-it=true --no-really=yes --not-kidding=1 ??

i just experienced it a moment ago that the only way to delete a pod was with --wait=false.  setting --force and setting --grace-period 0 are dead to me, meaningless now.  

i feel there must be a bug in implementing --grace-period 0.  The command should not have hung for 5 minutes on finalizers if I set --grade-period 0.
