### ISSUE TITLE
Error in ./test/kubemark/start-kubemark.sh:340

### ISSUE THREAD

**Issue by leeivan** [kubernetes/kubernetes#66475]
/area conformance
/area test
/sig testing
/sig scalability

STARTING SETUP FOR HOLLOW-NODES
Configuring registry authentication
gcloud credential helpers already registered correctly.
Copying kubemark binary to /home/leeivan/gowork/src/k8s.io/kubernetes/cluster/images/kubemark
docker build --pull -t gcr.io/avid-equator-210902/kubemark:07fkvk .
Sending build context to Docker daemon  162.2MB
Step 1/2 : FROM debian:jessie
jessie: Pulling from library/debian
Digest: sha256:a64a7d8ff7ff87edb78004ef0b159661546d2ddbd82772128b344c90cf8422ab
Status: Image is up to date for debian:jessie
 ---> 79f4bda91989
Step 2/2 : COPY kubemark /kubemark
 ---> Using cache
 ---> a2711b3bbcf0
Successfully built a2711b3bbcf0
Successfully tagged gcr.io/avid-equator-210902/kubemark:07fkvk
docker push gcr.io/avid-equator-210902/kubemark:07fkvk
The push refers to repository [gcr.io/avid-equator-210902/kubemark]
ff23db81c1b2: Preparing
dd1eb1fd7e08: Preparing
dd1eb1fd7e08: Layer already exists
ff23db81c1b2: Pushed
07fkvk: digest: sha256:3f9cb09bf3766ad4752c59867446dae29a224b42158380a7818d37a58e239617 size: 741
Succeeded to make gcloudpush .
Created and uploaded the kubemark hollow-node image to docker registry.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
!!! [0721 08:43:57] Call tree:
!!! [0721 08:43:57]  1: ./test/kubemark/start-kubemark.sh:471 create-kube-hollow-node-resources(...)
!!! Error in ./test/kubemark/start-kubemark.sh:340
  Error in ./test/kubemark/start-kubemark.sh:340. '((i<3-1))' exited with status 1
Call stack:
  1: ./test/kubemark/start-kubemark.sh:340 create-kube-hollow-node-resources(...)
  2: ./test/kubemark/start-kubemark.sh:471 main(...)
Exiting with status 1
/sig-scalability-test-failures

**Comment by spiffxp** [comment]
/remove-area conformance
kubemark isn't part of conformance

**Comment by jingyih** [comment]
@leeivan 

> server localhost:8080

This suggests that kubectl is not configured correctly.  I think the error happens when the start-kubemark.sh script is creating hollow node resources using kubectl commands.  Can you check if the server info in `test/kubermark/resources/kubeconfig.kubemark` matches the kubemark master ip?

**Comment by dims** [comment]
/close

please reopen if you are still facing this problem or able to provide additional information
