### ISSUE TITLE
[GKE] LoadBalancer constantly restarting from service

### ISSUE THREAD

**Issue by tbronchain** [kubernetes/kubernetes#66490]
/kind bug

Hi team!

I hope it is appropriate to post it as I experience an issue that seem to be a bug. I have been following the procedure described here [https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/] to solve the problem, with no luck.
In addition, I didn't seem to experience the issue before updating my cluster/nodes.

**What happened**:
We are creating "temporary environments" on our cluster using namespaces. When created, namespace, pods and services are created. When deleted, pods, services and namespaces are deleted.

**What you expected to happen**:
Services are "LoadBalancers" type, and should be accessible from the outside. However, is seems no IP can be assigned, and the load balancers are restarting in loop.
However, I don't seem to have reached any limit from GCP, and I can assign IPs addresses to VMs or static ips.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the service:
```
kind: Service
apiVersion: v1
metadata:
  name: admin-frontend
spec:
  type: LoadBalancer
  ports:
  - name: webui-admin
    port: 80
    targetPort: 80
    protocol: TCP
  - name: webui-admins
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    role: frontend
    app: admin
```

Here is the event that keeps happening:
```
$ kubectl --namespace=staging get events | grep -i service
3m          1d           320       admin-frontend.154391133e0c4504                                 Service                                        Normal    DeletingLoadBalancer    service-controller                                   Deleting load balancer
2m          1d           324       enrollment-frontend.15439118dd22246e                            Service                                        Normal    DeletingLoadBalancer    service-controller                                   Deleting load balancer
2m          1d           320       timesheet-frontend.1543911e680daa4e                             Service                                        Normal    DeletingLoadBalancer    service-controller                                   Deleting load balancer
```
I've tried to delete the services and loadbalances, both manually from the GCP console and using kubectl, nothing changed.

**Anything else we need to know?**:
I have seen a few issues mentioning similar issues, but none of them is identical nor solves my problem. I've seen people having issues with minikube, AWS, or trying to assign static IPs, which is not what I'm trying to do here - i.e https://github.com/kubernetes/kubernetes/issues/44521

Also, pods are running and reachable. Other environments that are not temporary are working perfectly fine.

**Environment**:
- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.0", GitCommit:"f4c74e18e57148052c59cc0467bb7e99dcc46399", GitTreeState:"clean", BuildDate:"2018-06-21T14:11:26Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GCP

Thanks!

**Comment by vishen** [comment]
It is hard to tell from what you provided, but it sounds similar to #66399, and it was fixed in #66400. Basically, Kubernetes was unable to delete GCP load balancers, and when a load balancer is updated, it first tries to "clean up" the old load balancer, but it gets stuck because it currently isn't able to delete GCP load balancers.

**Comment by tbronchain** [comment]
@vishen it does seem very similar indeed. However, from what I see in the GCP interface, the load balancer do get deleted. At least, from what is shown in the console and when I try to access the associated load balancer, the resource doesn't exist.

Any additional information I could provide to help?

**Comment by tbronchain** [comment]
So it was related to this issue. After manually cleaning the load balancers, ips, and updating the cluster from 1.10.5-gke.0 to 1.10.5-gke.3, it seems to be back to normal.
Thanks!
