### ISSUE TITLE
Kubelet could not detect clock speed from output: ""

### ISSUE THREAD

**Issue by jcgleissner** [kubernetes/kubernetes#66502]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
When starting the kubelet binary it fails on
`server.go:233] failed to run Kubelet: could not detect clock speed from output: ""`
**What you expected to happen**:
kubelet to start up or produce an error I can use to debug.
**How to reproduce it (as minimally and precisely as possible)**:
I'm building a containerized Cluster on Alpine images.
I used kubernetes-the-hard-way as a baseline
The kubelet image is run privileged, has containerd running and uses this config:
```
/bin/kubelet \
--address 192.168.0.4 \
--allow-privileged true \
--anonymous-auth true \
--authorization-mode AlwaysAllow \
--cloud-provider ""\
--cni-bin-dir /opt/cni/bin \
--cni-conf-dir /etc/cni/net.d \
--containerized true \
--container-runtime remote \
--container-runtime-endpoint unix:///var/run/containerd/containerd.sock \
--image-pull-progress-deadline 2m \
--kubeconfig /var/lib/kubelet/kubeconfig \
--network-plugin cni \
--register-node true \
--root-dir /var/lib/kubelet \
--v 2
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration: Bare Metal / containerized
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: -
- Others:

**Comment by ffahri** [comment]
https://github.com/kubernetes/kubernetes/blob/4e0a60a44ce7e0f33d1c22d997338542cda63ab8/vendor/github.com/google/cadvisor/machine/machine.go#L71

so error coming from cadvisor on that line. its nice to start debugging there i guess

**Comment by jcgleissner** [comment]
Thank you, this pointed me to the correct direction. I had to add
`-v /cgroup:/sys/fs/cgroup:ro`
to my `docker run` to provide cAdvisor with the correct read permissions.
