### ISSUE TITLE
Is that possible to add a custom label without touching k8s code?

### ISSUE THREAD

**Issue by jiatongw** [kubernetes/kubernetes#66513]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig cloud-provider

**What you expected to happen**:
Currently k8s has `built-in-node-labels` (`topologyKey`, for example,`kubernetes.io/hostname`, `beta.kubernetes.io/instance-type`). And k8s provides interfaces for cloud providers to implement that . Question: If I want to **add a custom label** as a `topologyKey` that specific to the cloud provider I am using, is there a way to create the label without touching k8s code? (e.g. without adding a new interface in k8s code) It's better if I can do all the stuff inside the cloud provider code and k8s can still "know" that.

**Comment by jiatongw** [comment]
And nodes can come pre-populated with the custom topologyKey

**Comment by liggitt** [comment]
> And nodes can come pre-populated with the custom topologyKey

you can apply labels to nodes once they appear in the API using knowledge your cloud provider has
