### ISSUE TITLE
It should be possible to check configuration without starting the process

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#66517]
The upcoming dynamic configuration for Kubelet and also the transition to config files instead of flags increases the need for an administrator to be able to "test" or "check" that the configuration is valid before starting a process.  This is a common behavior for daemons with large or complex configuration (which the kubelet considers) - administrators often want to validate or verify their local action before starting the process.  In addition, scripting tools might use this before automatically updating components.

As a small, minimal increment to reduce the pain of transitioning from flags to config, we should add `--check` or `--test` (similar to Apache's `-t`) to the core binaries that checks the input configuration and returns exit code `0` if the configuration is valid or `1` if the configuration is invalid.

Worked example:

1. An administrator is converting their flags to kubelet configuration files
2. They leave their kubelet running and create the new config file
3. To verify their new config works, they pass `kubelet --config=... --check` as they iterate.

There have been requests like this before but I'm having trouble finding the issues.  This is a common operational headache that is fairly easy to add with minimal cost (we already invoke validation in most processes).

@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by smarterclayton** [comment]
@liggitt as discussed today

**Comment by smarterclayton** [comment]
Also, our various binary behaviors have drifted (with regards to how errors and usage info are printed) which needs to be fixed no matter what.

**Comment by smarterclayton** [comment]
While poking around at fixing this, I realized our help output and usage output is really painful.  Spawned #66572 for that, I think that's a prerequisite since most of the commands here are ugly.

**Comment by luxas** [comment]
Also related wrt standardizing componentconfig handling inside of the components: https://github.com/kubernetes/community/pull/2354
