### ISSUE TITLE
Old object of admission attributes is always nil on delete calls

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#66536]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind feature

**What happened**:

When admission controller receives attributes for delete operations,  the old object field is always nil😅

**What you expected to happen**:

The old object field is assigned the the status of the object to delete. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
This isn't a bug, it's working as designed. The old object is currently only set for update requests.

**Comment by yue9944882** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by yue9944882** [comment]
/reopen
#76346 is working on fixing the issue

**Comment by lavalamp** [comment]
Yeah, I think it is totally reasonable to expect that field to be set for deletes as well as updates.

**Comment by liggitt** [comment]
yes, this is on the list for webhook GA, being fixed in #76346
