### ISSUE TITLE
v1: CustomResourceColumnDefinition JSONPath should be serialized as "jsonPath"

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#66531]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

CustomResoruceColumnDefinition JSONPath is serialized as "JSONPath".
All fields I observed start with lower case letter, regardless they are abbreviated name (e.g., osImage, nfs).  JSONPath is inconsistent to the rest of the API object serialization.  Not sure there is a rule for this, or some exceptions.

**What you expected to happen**:

JSONPath should be serialized as "jsonPath".

**How to reproduce it (as minimally and precisely as possible)**:

https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1#CustomResourceColumnDefinition

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
this won't change in v1beta1, but can be corrected in v1

**Comment by sttts** [comment]
We had a discussion about that when introducing the types and decided for `JSONPath`. I don't feel strongly about either way. I believe to remember @smarterclayton wanted the upper case one.

**Comment by smarterclayton** [comment]
I did?  All api fields should start with lowercase and be camelCase, so if I said that it was wrong

**Comment by liggitt** [comment]
yeah, needs to be on the list for v1 fixup

**Comment by sttts** [comment]
@smarterclayton maybe I wrongly blame you and it was just a misunderstanding. v1 fixup sounds good.

**Comment by nikhita** [comment]
Going to add `lifecycle/frozen` because this won't be handled until v1.

/lifecycle frozen
