### ISSUE TITLE
I got an error when kubernetes use Ceph.

### ISSUE THREAD

**Issue by liyongzhezz** [kubernetes/kubernetes#66532]
sig/ceph

this is my rbd.yaml:
`
apiVersion: v1
kind: Pod
metadata:
  name: rbd1
spec:
  containers:
    - image: kubernetes/pause
      name: rbd-rw
      volumeMounts:
      - name: rbdpd
        mountPath: /mnt/rbd
  volumes:
    - name: rbdpd
      rbd:
        monitors:
        - '10.10.97.32:6789'
        - '10.10.97.33:6789'
        - '10.10.97.34:6789'
        pool: rbd
        image: foo
        fsType: btrfs
        readOnly: true
        user: admin
        keyring: /etc/ceph/ceph.client.admin.keyring
        imageformat: "2"
        imagefeatures: "layering"
`

when i use `kubectl create -f rbd.yaml`, i got an error:

`error: error validating "rbd.yaml": error validating data: [ValidationError(Pod.spec.volumes[0].rbd): unknown field "imagefeatures" in io.k8s.api.core.v1.RBDVolumeSource, ValidationError(Pod.spec.volumes[0].rbd): unknown field "imageformat" in io.k8s.api.core.v1.RBDVolumeSource]; if you choose to ignore these errors, turn validation off with --validate=false`

who can help me to fix this problem? thx.

**Comment by hannius** [comment]
不是这个问题吧，实测不行。

**Comment by hannius** [comment]
--validate=false 直接忽略验证

**Comment by gaotuan** [comment]
@liyongzhezz  怎么关闭特性？

**Comment by liyongzhezz** [comment]
> @liyongzhezz 怎么关闭特性？

上边有写哦
