### ISSUE TITLE
Allow Minimum (or Maximum) Pods per failure zone

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes/kubernetes#66533]
Hello, 

I am trying to figure out a way to tell the scheduler to at least schedule one pod per failure zone but then allow others to be filled/moved as needed.

I can setup anti-affinity using the topologyKey zone but I am only able to get one pod per zone.

**Comment by eloyekunle** [comment]
I would like to work on this issue.

/assign

**Comment by warmchang** [comment]
FYI: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
