### ISSUE TITLE
Add error handling if preempting victims failed

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#66549]
**Description**:

`Scheduler.preempt` will delete victims after set nominatedNodeName; if only part of victims are deleted, the preemptor will pending here: `podEligibleToPreemptOthers` will return false, as part of victims are deleted. 

/kind enhancement
/sig scheduling

**Comment by k82cn** [comment]
@bsalamat , correct me if any misunderstand.

**Comment by tossmilestone** [comment]
@k82cn can I work on this?

**Comment by k82cn** [comment]
Sure, please go ahead. BTW, I just found this "issue" by code review, please help to verify it before creating PR.

**Comment by tossmilestone** [comment]
@k82cn OK, I will check it.

**Comment by bsalamat** [comment]
> Scheduler.preempt will delete victims after set nominatedNodeName; if only part of victims are deleted, the preemptor will pending here: podEligibleToPreemptOthers will return false, as part of victims are deleted.

It is true that podEligibleToPreemptOthers returns false in such case, but it should return false. What is the issue?

**Comment by tossmilestone** [comment]
>  if only part of victims are deleted

@k82cn does it mean some of the victims is terminating, and the other is still running? From the code, `podEligibleToPreemptOthers` will return false only if the nominated node has terminating pods with lower priority, so if part of victims are terminated, the preemptor can preempt again to delete the remaining victims.

**Comment by k82cn** [comment]
> so if part of victims are terminated, the preemptor can preempt again to delete the remaining victims and won't be always pending.

That's right; I'm ok with current behaviour: preempt other pods again if err after terminating pod done.

**Comment by tossmilestone** [comment]
@k82cn alright, then nothing will changed.

**Comment by k82cn** [comment]
/assign tossmilestone
/close

Thanks for your contribution :)
