### ISSUE TITLE
Kubernetes can't recreate pods with PVC if Node goes into "NotReady" state

### ISSUE THREAD

**Issue by ssfilatov** [kubernetes/kubernetes#66545]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**: persistentvolumes are not moved to another node if node goes into NotReady state

1. Node goes into NotReady state
```
NAME          STATUS                     ROLES     AGE       VERSION
master-0   Ready,SchedulingDisabled   <none>    2d        v1.9.8
minion-0   NotReady                   <none>    19h       v1.9.8
minion-1   Ready                      <none>    19h       v1.9.8
```

2. The old pod goes into UNNOWN state and RS creates a new one on a healthy node:
```
NAME                                READY     STATUS              RESTARTS   AGE
nginx-deployment-7dc8dddf6d-2k7fg   1/1       Unknown             0          19h
nginx-deployment-7dc8dddf6d-qzkl8   0/1       ContainerCreating   0          17h
```

The new one can't be created since the volume is not detached from the old pod.

**What you expected to happen**:

AttachDetach controller should have handled the case when unmount have not happened with force detach, the new pod should have started on a healthy node.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod with PVC
2. Kill kubelet on one of the worker nodes

**Anything else we need to know?**:
This issue is related to one of the issues mentioned in #57643

**Comment by darkworon** [comment]
Very important thing for critical pods, using PVC. Maybe possible any workaround?
