### ISSUE TITLE
Failing Test: [sig-cluster-lifecycle][sig-network] Cluster Downgrade Parallel, ingress upgrade

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66544]
# Failing Jobs
[sig-release-master-upgrade#gce-master-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.10-downgrade-cluster-parallel)

# Failing Tests

## Cluster Lifecycle
[Downgrade [Feature:Downgrade] cluster downgrade should maintain a functioning cluster [Feature:ClusterDowngrade]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/3558)
## Network
[ingress-upgrade](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/3558)

# Triage Results
[cluster downgrade should maintain a functioning cluster](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel&test=cluster%20downgrade%20should%20maintain%20a%20functioning%20cluster)

Tests Failing on sig-release-master-upgrade
/kind bug
/priority failing-test
/priority important-soon
/sig cluster-lifecycle
/sig network
/milestone v1.12
/cc @tpepper @AishSundar

**Comment by neolit123** [comment]
the tests broke after this change:
https://github.com/kubernetes/kubernetes/pull/65641
the change is  authored by @freehan and approved by @bowei

@kubernetes/ingress-gce-maintainers 
/sig gcp

**Comment by neolit123** [comment]
the compared error strings here are identical:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/3496

except the expected error strings has escaped double quotes `\"`.
this might be the problem...investigating further.

**Comment by neolit123** [comment]
/assign @rramkumar1
(the test author)

i did some more investigation and added some notes in the comment above.
sadly, i cannot help further as this is in GCP land.

**Comment by neolit123** [comment]
@mohammedzee1000 
cherry pick PR to fix this against the 1.10 branch was sent :tada: 
thanks to @rramkumar1

**Comment by mohammedzee1000** [comment]
Tests in this are green, closing
/close
