### ISSUE TITLE
Failing Test [sig-apps] hpa upgrade, replicaset upgrade gke-gci-master-gci-1.10-downgrade-cluster-parallel

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66555]
# Failing Jobs
[sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel)

# Failing Tests
## Sig Apps
[[sig-apps] replicaset-upgrade](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/3737)

## HPA
[hpa-upgrade](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/3737)

# Triage Results
[Replicaset Upgrade](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel&test=replicaset-upgrade)

Tests failing on sig-release-master-upgrade
/kind bug
/priority failing-test
/priority important-soon
/sig apps
/milestone v1.12
/cc @AishSundar @tpepper

**Comment by crimsonfaith91** [comment]
@mohammedzee1000 It seemed that the newest test runs were passing. Is there any specific aspect that you want us to look at?

**Comment by mohammedzee1000** [comment]
@crimsonfaith91 thanks for pointing that out. Closing issue, will reopen if i see regression

/close
