### ISSUE TITLE
[Feature Request] Add a "Job Status" feature similar to "Rollout Status"

### ISSUE THREAD

**Issue by philicious** [kubernetes/kubernetes#66563]
/kind feature
/sig api-machinery

As I cannot reopen #58742 , I duplicate it

**Proposed feature**
Where the command will exit when all Pods in the Job are terminated but not before, and return an exit code of 0 if all Pods were successful, or appropriate exit code if some Pods did not succeed.

This would allow actions to be performed after the Job has run - without polling - dependent on the Jobs overall "Success".

For e.g. Running performance tests from Parallel pods using a Job, and performing post-processing when all pods are completed.

**Comment by lukeschlather** [comment]
Seems like there ought to be a way to get the expected behavior with kubectl wait (although it seems like something built in to Job would make sense.)
