### ISSUE TITLE
Adding operators in k8s affinity rules... 

### ISSUE THREAD

**Issue by mcortinas** [kubernetes/kubernetes#66560]
Hi,

 I'm a newbie in k8s and I have some experience working in mesos/marathon environments. 
 I'm very comfortable with a orchestration rule in order to spread equitably the number of pods of one deployment inside a pool of minions or physical machines or whatever you can call it... 

https://mesosphere.github.io/marathon/docs/constraints.html
I think is very usefull distribute tasks evenly across racks or datacenters increasing high availability. 
Marathon allow us do this with constraints rules with operator GROUP BY, indicating how many distinct values can be expected for the given fieldName, p.e.: 

- hostname:GROUP_BY # try to distribute 3 task in at least in each hostname
- "rack_id",GROUP_BY", "3" # try to distribute at least in 3 different rack_id field

Other interesting operator is MAX_PER
- "rack_id", "MAX_PER", "2": # MAX 2 tasks per rack_id

After read this documentation, https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
Maybe in k8s we can add these operators (GROUP_BY and MAX_PER) as a feature inside nodeAffinity.

**Comment by k82cn** [comment]
/kind feature

Similar requirements with https://github.com/kubernetes/kubernetes/issues/40358 

/cc @kevin-wangzefeng , someone may also interest in this feature :)

**Comment by adampl** [comment]
+1

**Comment by zhangxiaoyu-zidif** [comment]
+1

**Comment by adampl** [comment]
:(

**Comment by mcortinas** [comment]
Any news?

**Comment by adampl** [comment]
Please someone refresh the lifecycle...
