### ISSUE TITLE
Pod stuck Terminating will not deregister from API

### ISSUE THREAD

**Issue by danbondd** [kubernetes/kubernetes#66574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Pod stuck in terminating state.
1. `kubectl delete pod <pod>` did nothing.
2. `kubectl delete pod <pod> --now` did nothing.
3. `kubectl delete pod <pod> --grace-period=0 --force` did nothing.
4. SSH onto node and `docker ps` shows running container.
5. `sudo docker kill <container id>` did nothing.
6. `sudo service docker restart` succeeded and container no longer running.
7. `kubectl get pods` still shows pod terminating.
8. Restarted kubelet on node `sudo service kubelet restart`.
9. `kubectl get pods` still shows pod terminating.
10. Repeating steps 1,2,3 did nothing.
11. `kubectl delete node <node id>` successful.
12. `kubectl get pods` still shows pod terminating.

**What you expected to happen**:

I expected the pod to be deleted during one of the above stages.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `AWS`
- OS (e.g. from /etc/os-release): 
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-24-88-12 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
```
- Install tools: `kops`
- Docker:
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by liggitt** [comment]
do you have the content of the pod yaml as retrieved from the API post-deletion?

**Comment by liggitt** [comment]
the presence of a persistent foregroundDeletion finalizer means that the garbage collector controller is not processing the object correctly. a potential deadlock in gc was resolved in 1.11 in https://github.com/kubernetes/kubernetes/pull/64235

additionally, kubectl 1.11.1 changed to not force objects into a foreground deletion path to avoid putting the garbage collector in the interactive delete path unnecessarily.

**Comment by danbondd** [comment]
Logs from kube-controller-manager have this 100+ times:

```I0724 15:55:06.003236       1 gc_controller.go:162] Found orphaned Pod requestd-66ffc94ccc-6c8b9 assigned to the Node ip-172-24-76-64.ap-southeast-1.compute.internal. Deleting.
I0724 15:55:06.003260       1 gc_controller.go:62] PodGC is force deleting Pod: default:requestd-66ffc94ccc-6c8b9
I0724 15:55:06.033307       1 gc_controller.go:166] Forced deletion of orphaned Pod requestd-66ffc94ccc-6c8b9 succeeded
```

**Comment by danbondd** [comment]
@liggitt what is the best way to restart `kube-controller-manager`? I see it has a pod in kube-system or should I restart the service on the master node?

**Comment by danbondd** [comment]
I successfully ran `sudo systemctl restart kubelet` on the master node. However, the terminating pod is still there.

**Comment by liggitt** [comment]
restarting the kubelet doesn't restart the controller manager. how you restart it depends on your deployment. I'm not sure what method kops uses for controller-manager setup.

**Comment by KielChan** [comment]
I came up with this problem several days ago,
kubelet print that, Pod XXXXX fully terminated and removed from etcd, but it is still in etcd,
the phase in kubelet log is running, statuses are terminated not nil.

What i would like to know is that:

who display the terminating state from cmd kubectl get pod ?

terminated from etcd is just after go-client delete pod(in code ), why pod was still there and no panic raise? and no log present in kube-apiserver?

ref:
```golang
	if m.canBeDeleted(pod, status.status) {
		deleteOptions := metav1.NewDeleteOptions(0)
		// Use the pod UID as the precondition for deletion to prevent deleting a newly created pod with the same name and namespace.
		deleteOptions.Preconditions = metav1.NewUIDPreconditions(string(pod.UID))
		err = m.kubeClient.CoreV1().Pods(pod.Namespace).Delete(pod.Name, deleteOptions)
		if err != nil {
			glog.Warningf("Failed to delete status for pod %q: %v", format.Pod(pod), err)
			return
		}
		glog.V(3).Infof("Pod %q fully terminated and removed from etcd", format.Pod(pod))
		m.deletePodStatus(uid)
	}
```
