### ISSUE TITLE
Create ConfigMap only if not exists

### ISSUE THREAD

**Issue by venkatmandavilli** [kubernetes/kubernetes#66578]
**Feature Request**:
/kind feature
/sig cli
Hello, is there a way to create config map only if it does not exist?

**What happened**:
I need to create config map only if does not exist

**What you expected to happen**:
Create Config map only if not exists

**Comment by interma** [comment]
As I know, no single command can do this.
But there are some walkarounds:
- `kubectl get configmaps xxx-config && kubectl create xxx-config ...`
- write a simple tools via client-go: https://github.com/kubernetes/client-go

**Comment by liggitt** [comment]
`kubectl apply` will update-or-create
