### ISSUE TITLE
Allow overriding CoreDNS image tag in kubeadm configuration

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#66573]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**: Unable to override the CoreDNS image tag for a kubeadm installation in the kubeadm config file

**What you expected to happen**: Be able to override the CoreDNS image tag for a kubeadm installation in the kubeadm config file

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The CoreDNS image tag is hard-coded as a constant and referenced at https://github.com/kubernetes/kubernetes/blob/0ffee495ad173fc75c01031cd3e90798de7fb9c0/cmd/kubeadm/app/images/images.go#L85 when installing CoreDNS.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by timothysc** [comment]
closing - please reopen here - https://github.com/kubernetes/kubeadm
