### ISSUE TITLE
Any field with a default value must have default values in all API versions

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#66582]
The issue was first reported in #66135. 

Open this as an umbrella issue for all existing violations. 
What we need to fix:
- [x] Document defaulting rule (PR https://github.com/kubernetes/community/pull/2411)
- [x] `extensions/v1beta1` Deployment `.spec.progressDeadlineSeconds` (PR #66581)
- [x] `extensions/v1beta1` Deployment `.spec.revisionHistoryLimit` (PR #66605)
- [ ] `batch/v2alpha1` `CronJob` `.spec.SuccessfulJobHistroyLimit`
- [ ] ... (other violations?)

Ref [API changes guidelines]( https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md). 

@kubernetes/sig-apps-bugs ~@kubernetes/sig-instrumentation-bugs~

**Comment by DirectXMan12** [comment]
@kubernetes/sig-autoscaling-bugs (not sig-instrumentation)

**Comment by islinwb** [comment]
@janetkuo Hi! I've submitted PR #66605 and #66606 for the 3rd and 5th item in the list. Would you take a look at them when you are availbale? Thanks!
