### ISSUE TITLE
Add attachdetach timer config parameters to kube-controller-manager options

### ISSUE THREAD

**Issue by ssfilatov** [kubernetes/kubernetes#66603]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

I'd like to be able to tweak attachdetach controller timer options, especially ReconcilerMaxWaitForUnmountDuration(which 6 minutes by default).

What do you think about adding TimerConfig options to controller-manager?
options:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L57

**Comment by lelvisl** [comment]
I have same need
