### ISSUE TITLE
Publish multi-arch images for Dockerfiles under test/images/

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#66618]
- [X] "goproxy" to "gcr.io/kubernetes-e2e-test-images"
- [X] "jessie-dnsutils" to "gcr.io/kubernetes-e2e-test-images"
- [X] "redis" to "gcr.io/kubernetes-e2e-test-images"
- [X] "serve-hostname" to "gcr.io/k8s-authenticated-test"

**Comment by dims** [comment]
tip for uploading `server-hostname` is here - https://github.com/kubernetes/kubernetes/pull/63453#issuecomment-407798138

**Comment by cjwagner** [comment]
`server-hostname` should be published to gcr.io/k8s-authenticated-test now.
I'm rerunning `make all-push` for the other 3 images.

**Comment by cjwagner** [comment]
I think the `goproxy` and `redis` images were published successfully this time.

`jessie-dnsutils`:
```
W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/InRelease  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get -q update &&     apt-get install -y dnsutils &&     apt-get clean' returned a non-zero code: 100
make: *** [all-container] Error 100
```

**Comment by dims** [comment]
@cjwagner can you please try https://github.com/kubernetes/kubernetes/pull/66624 ?

**Comment by cjwagner** [comment]
`jessie-dnsutils` should now be published too thanks to @dims PR.

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/38067
