### ISSUE TITLE
ResourceQuota for Services are misleading

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#66621]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
From the official docs: https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota it should be possible to set Quotas for different Service types e.g. `services.loadbalancers` and `services.nodeports` so in theory I can forbid to create a raw service of the type `NodePort` but allow to create services of the type `LoadBalancer` but in reality I get the following error:

```bash
$ kubectl --namespace=quota-object-example expose deployment nginx --port=80 --type=LoadBalancer
Error from server (Forbidden): services "nginx" is forbidden: exceeded quota: object-quota-demo, requested: services.nodeports=1, used: services.nodeports=0, limited: services.nodeports=0
```
My Quotas (I used the example from https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object):
```bash
kubectl get resourcequota object-quota-demo --namespace=quota-object-example --output=yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2018-07-25T18:34:07Z
  name: object-quota-demo
  namespace: quota-object-example
  resourceVersion: "497"
  selfLink: /api/v1/namespaces/quota-object-example/resourcequotas/object-quota-demo
  uid: 50c4024c-9039-11e8-8721-08002731898f
spec:
  hard:
    persistentvolumeclaims: "1"
    services.loadbalancers: "2"
    services.nodeports: "0"
status:
  hard:
    persistentvolumeclaims: "1"
    services.loadbalancers: "2"
    services.nodeports: "0"
  used:
    persistentvolumeclaims: "1"
    services.loadbalancers: "0"
    services.nodeports: "0"
```

**What you expected to happen**:
I would expect that a user can create 1 service of the type `LoadBalancer` but no services of the type `NodePort`.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ minikube start
...
$ kubectl create namespace quota-object-example
$ kubectl create -f https://k8s.io/examples/admin/resource/quota-objects.yaml --namespace=quota-object-example
$ kubectl run --image=nginx nginx --port=80
$ kubectl --namespace=quota-object-example expose deployment nginx --port=80 --type=LoadBalancer
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```bash
minikube version
minikube version: v0.28.2
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
minikube
- Others:
We also see this happen on clusters created with kops / kubeadm for AWS / OpenStack

**Comment by neolit123** [comment]
/sig cli
(please, delegate if needed)

**Comment by johscheuer** [comment]
I found the according code: https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/services.go#L126-L134 

So a service of type `LoadBalancer` will increase the used quotas for services of the type `LoadBalancer` and `NodePort`. I understand the idea behind this because each service of the type `LoadBalancer` will require at least one NodePort. But then the documentation it really misleading:

```bash
services.loadbalancers: The total number of services of type load balancer that can exist in the namespace.
```
and
```bash
services.nodeports: The total number of services of type node port that can exist in the namespace.
```

also for the services of type `NodePort` the documentation (or calculation) is wrong -> currently the count of opened nodeports will be evaluated not the count of services of the type `NodePort`.

**Comment by tanshanshan** [comment]
https://github.com/kubernetes/kubernetes/blob/85b8a23f197c39136f4a17ea59fffa4c4e8de225/pkg/quota/evaluator/core/services.go#L130-L134

I think the codes designed this.

**Comment by johscheuer** [comment]
@tanshanshan thanks for your replay that exactly the same code snippet I posted above :) The main question here is (at least for me): "Is the documentation wrong or is the calculation wrong".
