### ISSUE TITLE
dns service discovery fails on 1.11 with coredns (new default)

### ISSUE THREAD

**Issue by f3flight** [kubernetes/kubernetes#66629]
/kind bug

**What happened**:
DNS service discovery doesn't work:
```
user@server1:~$ kubectl exec pbox -- nslookup kubernetes
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find kubernetes: NXDOMAIN

*** Can't find kubernetes: No answer

user@server1:~$ kubectl exec -n kube-system coredns-78fcdf6894-hsqsk -- nslookup kubernetes
Server:		172.31.0.2
Address:	172.31.0.2#53

** server can't find kubernetes: NXDOMAIN

command terminated with exit code 1
user@server1:~$ kubectl exec -n kube-system coredns-78fcdf6894-hsqsk -- cat /etc/resolv.conf 
nameserver 172.31.0.2
search mylabserver.com
user@dsutyagin1:~$ kubectl exec -n kube-system coredns-78fcdf6894-hsqsk -- nslookup kubernetes.default.svc.cluster.local
Server:		172.31.0.2
Address:	172.31.0.2#53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN

command terminated with exit code 1
user@server1:~$ kubectl exec -n kube-system coredns-78fcdf6894-hsqsk -- nslookup kubernetes.default.svc.cluster.local.
Server:		172.31.0.2
Address:	172.31.0.2#53

** server can't find kubernetes.default.svc.cluster.local: NXDOMAIN

command terminated with exit code 1
```

**What you expected to happen**:
DNS service discovery works

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, I've started back my Ubuntu-based Kubernetes lab on Linux Academy to go through DNS exercise and found that DNS discovery doesn't work; DNS in general works.

**Anything else we need to know?**:
I have recently updated the lab using kubeadm from 1.10 to 1.11, and kube-dns was replaced with coredns.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Linux Academy VM
- OS (e.g. from /etc/os-release):
Clean Ubuntu Xenial with manually installed Kubernetes
- Kernel (e.g. `uname -a`):
4.4.0-1062-aws
- Install tools:
kubeadm

**Comment by f3flight** [comment]
@kubernetes/sig-apps-bugs

**Comment by f3flight** [comment]
@kubernetes/sig-network
/remove-sig apps

**Comment by f3flight** [comment]
@kubernetes/sig-network-bugs

**Comment by rajansandeep** [comment]
@f3flight 
You need to specify the IP of the CoreDNS pod

example
```
nslookup kubernetes.default.svc.cluster.local <coredns-pod-ip>
```
Or you can check by doing a `dig` command instead of `nslookup`

example:
```
dig @<coredns-pod-ip> kubernetes.default.svc.cluster.local
```

**Comment by f3flight** [comment]
@fturib the logs are clean and mostly empty. See below. @rajansandeep thank you for the hint. Nslookup still doesn't work, but it seems to be a problem with **nslookup** itself (I used "busybox" image) rather than k8s; dig via another container works fine, and from busybox I can see that resolution works if I do ping instead:
```
user@server1:~$ kubectl logs -n kube-system coredns-78fcdf6894-z28k5
.:53
2018/07/26 00:12:02 [INFO] CoreDNS-1.1.3
2018/07/26 00:12:02 [INFO] linux/amd64, go1.10.1, b0fd575c
2018/07/26 00:12:02 [INFO] plugin/reload: Running configuration MD5 = 2a066f12ec80aeb2b92740dd74c17138
CoreDNS-1.1.3
linux/amd64, go1.10.1, b0fd575c
user@dsutyagin1:~$ kubectl logs -n kube-system coredns-78fcdf6894-hsqsk
.:53
CoreDNS-1.1.3
linux/amd64, go1.10.1, b0fd575c
2018/07/26 00:12:00 [INFO] CoreDNS-1.1.3
2018/07/26 00:12:00 [INFO] linux/amd64, go1.10.1, b0fd575c
2018/07/26 00:12:00 [INFO] plugin/reload: Running configuration MD5 = 2a066f12ec80aeb2b92740dd74c17138
user@server1:~$ kubectl exec pbox -- ping -c1 -W1 kubernetes
PING kubernetes (10.96.0.1): 56 data bytes

--- kubernetes ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
command terminated with exit code 1
```
Closing, thanks again for the help.

**Comment by chrisohaver** [comment]
> You need to specify the IP of the CoreDNS pod

Just an FYI, that is not correct. You do not need to specify the CoreDNS pod IP to get a lookup to work.  Pods will, by default, point to the cluster dns service IP (e.g. 10.96.0.10).  For example, you can see that happening in the output of nslookup in this issue description.

**Comment by deepanvermag3** [comment]
@f3flight Did that work for you?

**Comment by f3flight** [comment]
@deepanvermag3 as you can read from my prev. post, I did not make any changes ahd just used a different image to test DNS which worked ok. The problem seems to have been with nslookup command embedded in default busybox image, so I just stopped trying to use it.
