### ISSUE TITLE
Publish multi-arch images for e2e tests (Dockerfile not in test/images)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#66626]
- [ ] "k8s-sample-admission-webhook" (to "gcr.io/kubernetes-e2e-test-images") 
       - fixing build for this image [here](https://github.com/kubernetes/kubernetes/pull/66665) (MERGED)
       - need to publish from directory `test/images/webhook`
- [ ] "k8s-aggregator-sample-apiserver" (to "gcr.io/kubernetes-e2e-test-images") 
       - Really old image build from k/k 1.7 branch, about to be [promoted to conformance](https://github.com/kubernetes/kubernetes/pull/63947). 
       - adding a new image [here](https://github.com/kubernetes/kubernetes/pull/66686) (APPROVED - In submit queue)
       - need to publish from directory `test/images/sample-apiserver`
- [ ] "k8s-dns-dnsmasq" (to "k8s.gcr.io") 
       - All we need is `dnsmasq`, so adding that to `dnsutils` image [here](https://github.com/kubernetes/kubernetes/pull/66695) (MERGED)
       - need to publish from directory `test/images/dnsutils`
- [ ] "gb-frontend" (to "gcr.io/google-samples" repo) 
       - looks like fixed up in https://github.com/kubernetes/examples/commit/5f484579b5cc04900591c61cf87ece00fe8426d7
       - we need https://github.com/kubernetes/examples/pull/255 merge too! (MERGED)
       - need to publish from `k8s.io/examples/guestbook/php-redis`
- [ ] "gb-redisslave" (to "gcr.io/google-samples" repo) 
       - looks like fixed up in https://github.com/kubernetes/examples/commit/5f484579b5cc04900591c61cf87ece00fe8426d7  (MERGED)
       - need to publish from `k8s.io/examples/guestbook/redis-slave`
- [ ] "nginx-slim" 
       - being fixed in https://github.com/kubernetes/kubernetes/pull/66055/ (REVIEW)

**Comment by dims** [comment]
looking at the images in http://gcr.io/google_containers

**Comment by dims** [comment]
/assign @mkumatag 
cc @cjwagner

**Comment by ixdy** [comment]
`e2e-net` comes from https://github.com/kubernetes/kubernetes/tree/master/test/images/net; I think it's just `gcr.io/kubernetes-e2e-test-images/net` now.
`gb-frontend` seems to be https://github.com/kubernetes/examples/blob/master/guestbook/php-redis.
Similarly, `gb-redisslave` seems to be https://github.com/kubernetes/examples/tree/master/guestbook/redis-slave.

**Comment by ixdy** [comment]
(I found the gb- images using cs.k8s.io, btw - https://cs.k8s.io/?q=gb-frontend&i=nope&files=Makefile&repos=)

**Comment by ixdy** [comment]
`k8s-dns-dnsmasq` sounds like https://github.com/kubernetes/dns.

**Comment by ixdy** [comment]
`git blame` on the k8s-aggregator-sample-apiserver image usage leads me to https://github.com/kubernetes/kubernetes/pull/50347 and then ultimately to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-apiserver/hack/build-image.sh.

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/38067

**Comment by dims** [comment]
@cjwagner Can you please publish a few images when you get a chance? ( cc @mkumatag )
 
1) from k8s.io/kubernetes/test/images/webhook run "make all-container WHAT=webhook"
2) from k8s.io/kubernetes/test/images/sample-apiserver run "make all-container WHAT=sample-apiserver"
   (Need https://github.com/kubernetes/kubernetes/pull/66686 to merge)
3) from k8s.io/kubernetes/test/images/dnsutils run "make all-container WHAT=dnsutils"
4) from k8s.io/examples/guestbook/php-redis run "make all-push"
5) from k8s.io/examples/guestbook/redis-slave run "make all-push"

**Comment by cjwagner** [comment]
The images under `k8s.io/kubernetes/test/images` should be published now, but I don't have permission to publish the images under `k8s.io/examples/guestbook`.
