### ISSUE TITLE
Call to pods sometimes slow : it takes either 0, 10, 20, 30 ... seconds

### ISSUE THREAD

**Issue by raphaeljoie** [kubernetes/kubernetes#66622]
/kind bug

**Context**:
I have an infrastructure deployed on AWS using Terraform. Two Spring (Java) apps are deployed using Terraform, via Kubernetes using a `kubernetes_replication_controller` and a `kubernetes_service`.

Using a simple infra, I experienced sometimes realy slow response when calling a pod from an other pod *and* when calling from the outside.

**What you expected to happen**:
Response time should be stable and reduced

**What happened**:
Communication is ok *but* after some measures, I noticed that requests always takes either 0, 10, 20, 30, ... seconds (see graph)
![graph](https://user-images.githubusercontent.com/9681129/43222748-54940d3e-9051-11e8-96d3-ef9ce6dd6d60.png)
110 tests in this graph, calls between two pods

it really looks like a timeout and retry story, with a 10 seconds timeout. Following this logic, a 20 delays can be seen as 2 failures before succeeding. If I follow this logic, since this graphs depicts a total of 126*10 seconds delay, this graph underlies 126 failures in the 110 tests (= 110 successes) => I have a success rate of about 50%

The same has been observed when calling from the outside

# Test standardisation
To exclude any failure from my side, I deployed an [echo server](https://github.com/hashicorp/http-echo) on the same infrastructure and started doing some tests using the hostname of the 
```
time wget http://LB_ID.REGION.elb.amazonaws.com/
```

I did 4 tests on 3 nodes : 1 pod, 2 pods, 3 pods and 4 pods:
![1_3_a](https://user-images.githubusercontent.com/9681129/43259755-a026db88-90d7-11e8-8c69-21f053147fb1.png)
![2_3_a](https://user-images.githubusercontent.com/9681129/43259756-a03c43c4-90d7-11e8-92b4-678fc0951a33.png)
![3_3_a](https://user-images.githubusercontent.com/9681129/43259757-a052ea98-90d7-11e8-8d27-d6f9f1eb10e6.png)
![4_3](https://user-images.githubusercontent.com/9681129/43259628-26fb5fd6-90d7-11e8-9a78-1726dfe94599.png)

This pushed me to do the test with one single pod
- 1 pod over 3 nodes : 100% success, no delay
- 2 pods over 3 nodes : 50% success
- 3 pods over 3 nodes : 33% success
- 4 pods over 3 nodes : 33% success ... but bigger variance
NB : according to the log of the pods, the requests are all handled in milliseconds when received *and* the traffic is well balanced between pods

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS

/sig network
/sig aws

**Comment by raphaeljoie** [comment]
Update : 

## Test over nodes
Got the suggestion to test also over the number of nodes and the Availability zones. Got some interesting results
**2 nodes drained (`kubectl drain`), 1 up (same subnet and AS as master)**

- 4 pods over same unique node : 100% success, no delay
- 5 pods over same unique node : 100% success, no delay

**1 node drained, 2 ups (same and different subnet+AZ as master)**

- 4 pods over same unique node (same as master) : 100% success, no delay
- 3 pods over node on master subnet, 1 node in other subnet : delays (no stat yet) but traffic well balanced between pods

**2 nodes drained, 1 up (different subnet and AZ as master)**
- 4 pods over same unique node : 100% success, no delay and traffic well balanced
- (no other test yet)

**1 node drained, 2 ups (both different subnet and AZ as master)**

- 4 pods over same unique node (one node empty) : 100% success, no delay and traffic well balanced
- (no other test yet)


**1 node drained, 2 ups (both different subnet and AZ as master)**
- 3 pods over first node, 1 on the second  : delays (no stat yet) but traffic well balanced between pods
- (no other test yet)

**Comment by vivek-jain-mt** [comment]
Hi @raphaeljoie,  were you able to identify the issue? I also have been facing the same issue with delays in multiples of 5.

**Comment by betterphp** [comment]
:(
