### ISSUE TITLE
kube-apiserver crash-loops when cloudprovider enabled and --advertise-address=0.0.0.0

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes/kubernetes#66637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: 
Launching a cluster with cloudprovider (AWS) enabled and `--advertise-address=0.0.0.0`, kube-apiserver would run for a minute or two and then exit with:

```
Current master IPs listed in storage are []
o master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
```

When I changed the `--advertise-address=` value to the public IP of the node kube-apiserver ran normally. The message `Current master IPs listed in storage are [...]` was then populated with master IP addresses.

**What you expected to happen**: 
kube-apiserver would detect the public IP and use that as the master IP.

**How to reproduce it (as minimally and precisely as possible)**:
Provision a cluster with `--cloud-provider=aws` and `--cloud-config=` set on kubelet, kube-apiserver and kube-controller-manager. Set `--advertise-address=0.0.0.0` on the kube-apiserver components.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): `Linux ip-10-205-233-116.ec2.internal 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: custom
- Others:

**Comment by andrewmyhre** [comment]
Hi guys. Looks like this issue was caused by incorrect proxy configuration.

**Comment by neolit123** [comment]
thanks for the update.

/close

**Comment by Shadowraze228** [comment]
@andrewmyhre have the same issue, how did you troubleshoot it?

**Comment by robermorales** [comment]
same here, ideas? tia
