### ISSUE TITLE
Deleting replica and deployment does not delete the pod

### ISSUE THREAD

**Issue by Mahla1990** [kubernetes/kubernetes#66636]
**BUG REPORT**:

/sig cli
/kind bug

**What happened**:
When I deleted the deployment and replicas via Ruby client, the replica and deployment are gone but the pods is till there.

```
kubectl get replicaset | grep ***
kubectl get deploy | grep ***
kubectl get pod | grep ***
***   1/1       Running     0          2d
```

`replica sets [#<Kubeclient::ReplicaSet metadata={:name=>"***", :namespace=>"default", :selfLink=>"/apis/extensions/v1beta1/namespaces/default/replicasets/***", :uid=>"36209078-7bc3-11e8-a201-fa163e1a7ce3", :resourceVersion=>"46810657", :generation=>1, :creationTimestamp=>"2018-06-29T17:38:19Z", :labels=>{:app=>"***", :app_type=>"sc", :**=>"***", :"pod-template-hash"=>"1607406036"}, :annotations=>{:"deployment.kubernetes.io/desired-replicas"=>"1", :"deployment.kubernetes.io/max-replicas"=>"2", :"deployment.kubernetes.io/revision"=>"1"}}, spec={:replicas=>1, :selector=>{:matchLabels=>{:app=>"***", :app_type=>"sc", :**=>"***", :"pod-template-hash"=>"1607406036"}}, :template=>{:metadata=>{:creationTimestamp=>nil, : .... restartPolicy=>"Always", :terminationGracePeriodSeconds=>30, :dnsPolicy=>"ClusterFirst", :securityContext=>{}, :imagePullSecrets=>[{:name=>"internalpull"}], :schedulerName=>"default-scheduler"}}}, status={:replicas=>1, :fullyLabeledReplicas=>1, :readyReplicas=>1, :availableReplicas=>1, :observedGeneration=>1}>]`

**What you expected to happen**:
In Kubernetes 1.10, I was expecting that even without setting cascade deletion, pods will be deleted during garbage collection.
**How to reproduce it (as minimally and precisely as possible)**:
create a deployment and replica, delete them and the pod will remain there sometimes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (v1.10.5): Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel: 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liggitt** [comment]
The behavior of the extensions/v1beta APIs will not change for backwards compatibility

Deleting via the apps/v1 API cascades by default

/close
