### ISSUE TITLE
Kubelet should not treat PodStatus.HostIP as an optional field

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#6664]
Relevant code [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/629d94657e539407d4b4d8b674c029c182e2147b/pkg/kubelet/kubelet.go#L1992)

The [API](https://github.com/GoogleCloudPlatform/kubernetes/blob/629d94657e539407d4b4d8b674c029c182e2147b/pkg/api/v1beta3/types.go#L765) does not indicate that the HostIP field is optional.

**Comment by xiang90** [comment]
@vishh 

I am confused by looking at the API you referred.

The API docs does say HostIP is optional
```
// Optional: What host IP to bind the external port to.
HostIP string `json:"hostIP,omitempty" description:"host IP to bind the port to"`
```

**Comment by bprashanth** [comment]
Check https://github.com/GoogleCloudPlatform/kubernetes/issues/6558 for more context

**Comment by vishh** [comment]
@xiang90: Good catch! I updated the link to point to PodStatus.HostIP.

**Comment by yujuhong** [comment]
I believe this is obsolete. Closing.
