### ISSUE TITLE
cephfs volume doesn't support client quota

### ISSUE THREAD

**Issue by francotseng** [kubernetes/kubernetes#66664]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Cephfs volume with ceph-fuse of ```jewel``` and earlier version does not support capicity quota, which means that the pod using the cephfs volume can use as many space as the cephfs provides, instead of the quota's limitation.

**What you expected to happen**:
Pods mounting cephfs volumes should be rejected to write any more when a quota limit is reached. To be exactly, kubelet should use ```--client-quota``` option when mounting cephfs volume to pod with ceph-fuse of ```jewel``` and earlier version.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cephfs volume of 100MiB capacity by pvc, then mount the volume to a pod on a kubelet node with ceph-fuse of ```jewel``` and earlier version, run df in the container, the 'Available size' will not be 100MiB, but the total capicity of cephfs.

**Anything else we need to know?**:
ceph-fuse of ```luminous``` and later version does not support ```--client-quota``` option, as far as I know. The quota takes effect automaticlly. So we have to be careful not to add ```--client-quota``` option on ceph-fuse who does not recognize it.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core) 
- Kernel (e.g. `uname -a`): Linux 4.17.0-1.el7.elrepo.x86_64
- Install tools: kubespray
- Others: ceph-fuse 10.2.5

**Comment by francotseng** [comment]
#dibs

**Comment by silenceshell** [comment]
@francotseng I have commit a PR #64044 , however it has gone rotten and is closed.
With pleasure if you want to use my code :)
