### ISSUE TITLE
Creating a pod fails if default service account does not exist with the default service account enabled.

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#66689]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Occasionally when creating a namespace and then creating a pod this happens
```
[rmcnamara@ip-10-0-2-7 ~]$ cat pod.yml
apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: pod-test
  namespace: foo
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      sleep 10000000
    image: busybox
    name: sleeper

[rmcnamara@ip-10-0-2-7 ~]$ kubectl create ns foo
namespace "foo" created
[rmcnamara@ip-10-0-2-7 ~]$ kubectl apply -f pod.yml
Error from server (Forbidden): error when creating "pod.yml": pods "pod-test" is forbidden: error looking up service account foo/default: serviceaccount "default" not found
```

The reason for this is that between the namespace `foo` creation and the pod creation, the kube-controller-manager had not yet created the `default` service account in the `foo` namespace. So [this line](https://github.com/kubernetes/kubernetes/blob/c178c7fd65fd1633d7a2580dbc2de7f3e86a23b4/plugin/pkg/admission/serviceaccount/admission.go#L165) errors as it is asserting the `default` serviceaccount exists. This is a race, but you can make it happen by stopping the kube-controller-manager leader (something that routinely happens in HA to roll the instance the kube-controller-manager leader is on) before creating the namespace.

Is this the correct behavior? It's somewhat confusing. One way to possibly mitigate this would be retrying the search for the serviceaccount, or perhaps allowing the pod to be created if the service account does not yet exist. I'm not sure what implications this would have though.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.7
- Cloud provider or hardware configuration: aws
ServiceAccount admission plugin is enabled

**Comment by liggitt** [comment]
Yes, it is working as intended. There is already a retry for the default service account. Pods are immutable after creation, so allowing a pod to be created without the service account available would break any application depending on service account credentials

/close

**Comment by liggitt** [comment]
> So I don't believe that the race condition is fixed

the delay/retry in admission is only a mitigation. fundamentally, the race condition is in the pod creator, which needs to retry or wait until the requisite service account has been created :)

**Comment by jorhett** [comment]
@liggitt so that means N projects have to hack in their own workarounds, where N is a non-trivial number (at least 3 if not 4 digits). I feel that providing a standardized way to do this test, request this delay, whatever would be beneficial.

**Comment by mitar** [comment]
I use the following hack to assure service account is ready:

```bash
n=0; until ((n >= 60)); do kubectl -n default get serviceaccount default -o name && break; n=$((n + 1)); sleep 1; done; ((n < 60))
```

**Comment by jorhett** [comment]
I do a similar hack. They we all must hack is the problem...
