### ISSUE TITLE
Container migration

### ISSUE THREAD

**Issue by UmaprasadBisen** [kubernetes/kubernetes#66715]
Any idea how to migrate the container from one cloud to another with their volumes? 
Thanks in advance.
 @kubernetes/sig-api-machinery
@k8s-merge-robot

**Comment by neolit123** [comment]
hi, you are going to get a better response if you ask on http://slack.k8s.io/.
you can try the following channels:
#sig-cloud-provider
#kubernetes-users

this tracker is better suited for bug reports and feature requests.
/close
