### ISSUE TITLE
Minimize the dependency of scheduler algorithm

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#66714]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig scheduling

**Description**:

When replacing NodeSelector with NodeAffinity predicates, it import 400+ files ... ; it's better to minimized the dependency of scheduler algorithm which we'd like to be used by other project.

xref: https://github.com/kubernetes-incubator/kube-arbitrator/pull/310

**Comment by essamhassan** [comment]
I'd like to look into this and work on it

**Comment by k82cn** [comment]
That's great :)

/assign essamhassan
