### ISSUE TITLE
Namespace keeps Terminating after deleted

### ISSUE THREAD

**Issue by kaybinwong** [kubernetes/kubernetes#66735]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
using kubectl delete ns xxxx, but its status keeps Terminating

**What you expected to happen**:
destroy and can recreate

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create ns xxx

// do some other job

kubect delete ns xxx --now=true

**Anything else we need to know?**:
nothing else

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@passport-dev rancher]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
hardware
- OS (e.g. from /etc/os-release):
```
[root@passport-dev rancher]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
[root@passport-dev rancher]# uname -a
Linux passport-dev 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
kubespray
- Others:
nothing

**Comment by kaybinwong** [comment]
sig/cluster-ops bugs or some i had done wrongly?

**Comment by liggitt** [comment]
Typically this means the namespace controller is unable to discover/delete all resources in the namespace, and will not remove the namespace until it has done so. What is in the controller manager log?

**Comment by dims** [comment]
/sig api-machinery

Is that the right sig @liggitt ?

**Comment by kaybinwong** [comment]
@liggitt sorry, the logs had gone.

**Comment by antoineco** [comment]
I'm facing the same issue in Kubernetes 1.10.9 with a fresh namespace.

```
❯ kubectl -n kube-system get ns
NAME          STATUS        AGE
default       Active        27d
kube-public   Active        27d
kube-system   Active        27d
myns          Terminating   3m
```

Few minutes after the deletion, the controller-manager shows absolutely nothing (`-v=2`).

Some objects are apparently still around:
```
❯ kubectl -n myns delete --all all,sa,cm,secret,pvc
serviceaccount "default" deleted
secret "default-token-dckr7" deleted
```

As suggested elsewhere, the only way to delete my namespaces is to send the following payload to `https://apiserver:port/api/v1/namespaces/myns/finalize` (**notice the empty finalizers array**):
```json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "creationTimestamp": "2018-10-25T19:01:48Z",
        "deletionTimestamp": "2018-10-25T19:02:08Z",
        "name": "myns",
        "resourceVersion": "5023281",
        "selfLink": "/api/v1/namespaces/myns",
        "uid": "6ccf5676-d888-11e8-a642-000d3ad0b3ea"
    },
    "spec": {
        "finalizers": []
    },
    "status": {
        "phase": "Terminating"
    }
}
```

Deleting finalizers with `kubectl` is not enough.

**Comment by qdrop17** [comment]
Hi everyone.

I face the same issue. But my `kubectl get apiservices v1beta1.metrics.k8s.io -o yaml` shows up no errors:

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiregistration.k8s.io/v1beta1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.metrics.k8s.io","namespace":""},"spec":{"group":"metrics.k8s.io","groupPriorityMinimum":100,"insecureSkipTLSVerify":true,"service":{"name":"metrics-server","namespace":"kube-system"},"version":"v1beta1","versionPriority":100}}
  creationTimestamp: 2018-08-29T12:16:09Z
  name: v1beta1.metrics.k8s.io
  resourceVersion: "7018363"
  selfLink: /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io
  uid: 4fbcbba3-ab85-11e8-a694-3a420f52ae39
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: 2018-10-26T07:45:36Z
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```

Yet I'm only able to remove the namespaces doing the following API-request (kubectl proxy):

`curl -k -H "Content-Type: application/json" -X PUT --data-binary @tmp.json 127.0.0.1:8001/k8s/clusters/c-ckzdb/api/v1/namespaces/non-deletable-namespace/finalize`

(removing the finalizer called "kubernetes" first from the json...)

Can I support you in any way to resolve this issue? We're running 2.1.1.

**Comment by antoineco** [comment]
@liggitt I blocked TCP traffic between the API server and the metrics server again via NetworkPolicies and can consistently reproduce the issue.

`kubectl api-resources` just returns:
```console
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

If I re-enable communications the namespace magically disappears.

**Comment by liggitt** [comment]
> @liggitt I blocked TCP traffic between the API server and the metrics server again via NetworkPolicies and can consistently reproduce the issue.
> 
> `kubectl api-resources` just returns:
> 
> ```
> error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
> ```
> 
> If I re-enable communications the namespace magically disappears.

That is what I would expect. when a namespace is removed, the namespace controller must ensure that all resources that exist within it are removed. To do that, it discovers all available resources, which requires being able to contact all extension apiservers. If one of them is unavailable, the namespace controller will wait and retry until it is available, but will not release the namespace in the meantime.

**Comment by antoineco** [comment]
Was the metrics server already a mandatory component in 1.10?

**Comment by qdrop17** [comment]
> To be clear, removing the finalizer does not actually resolve the issue that was blocking the namespace deletion, it just skips any remaining resource cleanup that needed to be done. That is not recommended, since it can leave orphaned resources associated with the now-removed namespace.
> 
> This command will show any resources associated with the namespace:
> 
> ```shell
> kubectl api-resources --verbs=list --namespaced -o name | \
>   xargs -n 1 kubectl get -o name -n $NAMESPACE
> ```
> 
> Does that reveal any remaining resources? If so, investigating why those are not being removed would be the next step.

Unfortunately I already delete the namespaces using the method I mentioned. In the meantime, I discovered some bug with the metrics-server's key and certificate deployment (see here: https://github.com/rancher/rke/issues/866#issuecomment-420019920) which I fixed. This removed the issue: We can now create and remove namespaces without any problems.

Yet I'm interested if there are any dangling / orphaned resources in our Kubernetes cluster. How can I find and remove those?

**Comment by liggitt** [comment]
> Yet I'm interested if there are any dangling / orphaned resources in our Kubernetes cluster. How can I find and remove those?

 You can check for dangling resources for a particular namespace with the command I showed earlier

**Comment by qdrop17** [comment]
> > Yet I'm interested if there are any dangling / orphaned resources in our Kubernetes cluster. How can I find and remove those?
> 
> You can check for dangling resources for a particular namespace with the command I showed earlier

Yeah, I did that. But how can I find those dangling ressources if the namespace is no longer existing?

**Comment by antoineco** [comment]
You can't. Please create another namespace and try to reproduce the issue.

**Comment by qdrop17** [comment]
Alright. I recreated the respective namespaces. After this I was able to find the dangling ressources. Deleting them also cleaned the dangling ressources properly. Everything fine now.

**Comment by lavalamp** [comment]
Please take future reports of this to: #70916
