### ISSUE TITLE
On CentOS 7.5, calling to "kubelet" produces error

### ISSUE THREAD

**Issue by motek80** [kubernetes/kubernetes#66747]
/kind bug

**What happened**:
On CentOS, calling "kubelet" displays the following error:

`F0729 13:50:44.278410    9196 server.go:262] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"`

**What you expected to happen**:
After calling "kubelet", no errors should be displayed

**How to reproduce it (as minimally and precisely as possible)**:
Followed [this guide](https://kubernetes.io/docs/setup/independent/install-kubeadm/), installed kubelet, kubeadm, kubectl (v 1.11.1) on CentOS 7 (AWS VM):

1. yum install -y docker
2. systemctl enable docker && systemctl start docker
3. cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF
4. setenforce 0
5. yum install -y kubelet kubeadm kubectl
6. systemctl enable kubelet && systemctl start kubelet
7. call "kubelet"

**Anything else we need to know?**:
On Ubuntu 16.04 this not happens

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS / t2.Medium

- OS (e.g. from /etc/os-release):
CentOS 7.5

- Kernel (e.g. `uname -a`):
Linux ip-xxxxxxxxxx.compute.internal 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment]
hello and thank you for the report!

> Follow this guide, installed kubelet, kubeadm and kubectl

the same guide already explains the cgroup driver issue:
https://kubernetes.io/docs/setup/independent/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-master-node

ATM the kubelet does not have auto-detection of the docker cgroup driver, but if your run kubeadm it should start a valid instance of the kubelet without the error, in the case of docker.

/sig cluster-lifecycle
/sig node
/close

please free to re-open if you are still having issues.

**Comment by motek80** [comment]
I tried everything explain in [this](https://kubernetes.io/docs/setup/independent/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-master-node) section, however kubelet continue to complain about cgroup driver incompatibility.

Is there any configuration example for CentOS? Everything I has been tried so far doesn't seem to work.

**Comment by motek80** [comment]
Tried to add [Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"] to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and then call

- systemctl daemon-reload
- systemctl restart kubelet

No effect, still issue exists

**Comment by neolit123** [comment]
> No effect, still issue exists

does that happen if you use `kubeadm init`?
the file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` only make sense for kubeadm.

if you want to start the kubelet without kubeadm move the folder `/etc/systemd/system/kubelet.service.d/` somewhere and add your flags in `/etc/systemd/system/kubelet.service`

also please share the output from:
`journalctl -xeu kubelet`
