### ISSUE TITLE
one pv bug - unable to find a keyring on /etc/ceph/ceph.client.admin.keyring

### ISSUE THREAD

**Issue by timyinshi** [kubernetes/kubernetes#66757]
/kind bug
/sig storage

**What happened**:
the ceph's keyring in secret,when creating pod ,kubelet will use the ceph's keyring to authentication ceph.
my problem is why must have a client keyring file in /etc/ceph.
i think it is a bug.

**What you expected to happen**:
i think the secret's keyring is the only thing we need to maintain.

**Anything else we need to know?**:
the error info:
Jul 30 10:36:50 slave7 kubelet: E0730 10:36:50.717778 1685028 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/rbd/[10.1.25.114:6789 10.1.25.113:6789 10.1.25.108:6789]:kubernetes-dynamic-pvc-f37d96c1-9230-11e8-b0ba-6c92bf744022\"" failed. No retries permitted until 2018-07-30 10:38:52.717696973 +0800 CST m=+1506876.720862690 (durationBeforeRetry 2m2s). Error: "MountVolume.WaitForAttach failed for volume \"pvc-f37b5b14-9230-11e8-8d18-6c92bf744022\" (UniqueName: \"kubernetes.io/rbd/[10.1.25.114:6789 10.1.25.113:6789 10.1.25.108:6789]:kubernetes-dynamic-pvc-f37d96c1-9230-11e8-b0ba-6c92bf744022\") pod \"trident-mongodb-mongodb3-0\" (UID: \"f37c2b19-9230-11e8-8d18-6c92bf744022\") : error: exit status 1, rbd output: 2018-07-30 10:36:50.712074 7f0ecd03ad40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory\n2018-07-30 10:36:50.714349 7f0ecd03ad40  0 librados: client.admin authentication error (1) Operation not permitted\nrbd: couldn't connect to the cluster!\n"

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.1
- OS (e.g. from /etc/os-release):cenos7.4
- Kernel (e.g. `uname -a`):
[root@slave7 system]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030579
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1030579
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by gucki** [comment]
@shigy123456 I can't reproduce this with kubernetes v1.11.3. The error only occurs if the secret stored in k8s is invalid, because it seems to fall back to a keyring on the server.

**Comment by gucki** [comment]
@shigy123456 See https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/volume/rbd/rbd_util.go#L223

**Comment by shubb30** [comment]
I am seeing this same problem in 1.12.0.

@gucki, what is the format of the Secret supposed to be?  I created the client key using the same command as the example from https://kubernetes.io/docs/concepts/storage/storage-classes/#ceph-rbd and I am getting the same error.  The pvc is getting created, so it looks like the admin secret is working, but the client bind does not work.

The pvc details

```
Name:          ceph-test
Namespace:     ceph-test
StorageClass:  ceph
Status:        Bound
Volume:        pvc-8c44097e-d647-11e8-9297-00505698393e
Labels:        cattle.io/creator=norman
Annotations:   field.cattle.io/creatorId=u-p422tciumo
               pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  17m   persistentvolume-controller  Successfully provisioned volume pvc-8c44097e-d647-11e8-9297-00505698393e using kubernetes.io/rbd
```

The pod details

```
Name:               ceph-test-d88979fcf-kslm6
Namespace:          ceph-test
Priority:           0
PriorityClassName:  <none>
Node:               10.2.45.11/10.2.45.11
Start Time:         Mon, 22 Oct 2018 15:12:22 -0700
Labels:             pod-template-hash=d88979fcf
                    workload.user.cattle.io/workloadselector=deployment-ceph-test-ceph-test
Annotations:        cattle.io/timestamp=2018-10-22T22:12:21Z
Status:             Pending
IP:
Controlled By:      ReplicaSet/ceph-test-d88979fcf
Containers:
  ceph-test:
    Container ID:
    Image:          ubuntu:xenial
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/ceph from ceph-test (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v7s6j (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ceph-test:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ceph-test
    ReadOnly:   false
  default-token-v7s6j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-v7s6j
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               17m   default-scheduler        Successfully assigned ceph-test/ceph-test-d88979fcf-kslm6 to 10.2.45.11
  Normal   SuccessfulAttachVolume  17m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8c44097e-d647-11e8-9297-00505698393e"
  Warning  FailedMount             16m   kubelet, 10.2.45.11   MountVolume.WaitForAttach failed for volume "pvc-8c44097e-d647-11e8-9297-00505698393e" : rbd: map failed exit status 110, rbd output: 2018-10-22 22:12:38.001480 7fd3fcc32100 -1 did not load config file, using default settings.
2018-10-22 22:12:38.004277 7fd3fcc32100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.k8s.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
rbd: sysfs write failed
2018-10-22 22:13:38.004336 7fd3fcc32100 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.k8s.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (110) Connection timed out
```

**Comment by gucki** [comment]
@shubb30 I assume the keyring and the username you specified don't match. And so ceph will try to load another keyring. What does your keyring and storageclass look like?

**Comment by shubb30** [comment]
CEPH client auth

```
$ ceph auth get client.kube
exported keyring for client.kube
[client.kube]
    key = AQFrRc9e06/zFRABi5ECdfJkAoVi64W1m/M+qA==
    caps mon = "allow r"
    caps osd = "allow rwx pool=kube"
```

Kubernetes secret

```
$ kubectl -n kube-system get secrets ceph-secret -o jsonpath={.data.key}|base64 -D
AQFrRc9e06/zFRABi5ECdfJkAoVi64W1m/M+qA==%
```

StorageClass

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph
parameters:
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  fsType: ext4
  imageFeatures: layering
  imageFormat: "2"
  monitors: 10.199.32.196:6789,10.199.32.197:6789,10.199.32.198:6789
  pool: kube
  userId: kube
  userSecretName: ceph-secret
  userSecretNamespace: kube-system
provisioner: kubernetes.io/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The Admin secret works fine because it can create the CEPH volumes.  It's just the client that is not working.

**Comment by inzem77** [comment]
It heps me
ceph osd crush tunables legacy
I found the decision to https://developer.ibm.com/recipes/tutorials/integrating-ceph-with-ibm-cloud-private-3-1/

**Comment by ArcticSnowman** [comment]
This still needs a resolution

**Comment by timyinshi** [comment]
i find that when the ceph server can not be connected,then the error will be found,so when have the problem ,then can check the ceph client's config whether it is right,or chech the ceph server whether can work normally.
