### ISSUE TITLE
Setting up authentication proxy using nginx

### ISSUE THREAD

**Issue by koyadume** [kubernetes/kubernetes#66754]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Kubernetes expects each group to be passed in a separate header with same names

**What you expected to happen**:
Kubernetes should allow passing all groups (comma or something else as separator) in a single header

**How to reproduce it (as minimally and precisely as possible)**:
https://stackoverflow.com/questions/50559736/nginx-as-authentication-proxy-for-kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: 
```
Ubuntu 16.04 running on a Softlayer VM
```
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux fe-k8s-08 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

I am trying to setup nginx as authentication proxy for kubernetes api. As mentioned on https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy page, it expects each group name to passed in a separate header with same names which IMO is very difficult to achieve with a proxy like nginx which, it seems, can't handle multiple headers with same names. Proposal is to allow specifying multiple groups in a single header which can be easily implemented in nginx (and probably other) proxies.

More details can be found here - https://stackoverflow.com/questions/50559736/nginx-as-authentication-proxy-for-kubernetes

P.S. - I would prefer not to replace nginx with something else to solve this problem unless it can't be achieved with nginx.

**Comment by CaoShuFeng** [comment]
If we support this, should we also support comma separated http headers in other places? For example [impersonation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go#L63)

**Comment by mikedanese** [comment]
I would prefer to fix the issue on the nginx side. Rather than building more and more complex sidechannel encodings of user info.

**Comment by liggitt** [comment]
> I would prefer to fix the issue on the nginx side rather than building more and more complex sidechannel encodings of user info.

Agree, delimiters would mean assuming those characters could never appear in group names (which is not a good assumption… ldap groups frequently contain commas)

/close
