### ISSUE TITLE
kubectl config view shows passwords by default

### ISSUE THREAD

**Issue by ms4720** [kubernetes/kubernetes#66753]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

 typed `kubectl config view` and the passwords for the following users were displayed:

- domain_name
- domain_name-basic-auth 

**What you expected to happen**:

display REDACTED

and to display them use: `kubectl config view --raw` 

**How to reproduce it (as minimally and precisely as possible)**:

kubectl config view

**Anything else we need to know?**:

I would like to make the patch to fix this, looks like a good first issue

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by m1kola** [comment]
Thanks for reporting. I can reproduce this.

As far as I'm aware, the data is not omitted for security reasons: it just to make output more readable for humans. Currently it only omits PEM-encoded data from a client cert and key files. Probably it's a desired behaviour.

I'm happy to work on it, if anyone from @kubernetes/sig-cli-bugs can confirm that they are happy to replace password (and, probably, username) with "REDACTED".

**Comment by ms4720** [comment]
I would like to do this, it looks like a good first issue thing, and I found it.

**Comment by ms4720** [comment]
I think user name/login is fine, think /etc/passwd vs /etc/shadow.

**Comment by m1kola** [comment]
Ok, feel free to pick this up.

I also just started learning the project's codebase, but, I think, I have an idea where to dig for this. So let me know, if you need any help/pointers.

**Comment by ms4720** [comment]
I will thanks, I think I found it.  I think getting everything set up right is going to take longer than the fix

**Comment by liggitt** [comment]
the intent of `REDACTED` was not to mask sensitive data, but to elide extremely long data. See discussion in https://github.com/kubernetes/kubernetes/issues/61573 and change in https://github.com/kubernetes/kubernetes/pull/66023

I think this is working as intended
