### ISSUE TITLE
The job status is still running after the related pod status changes to ImagePullBackOff 

### ISSUE THREAD

**Issue by Itfly** [kubernetes/kubernetes#66756]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I create a kubernetes job which would deploy a pod to run the task. The pod immediately changes its status to ImagePullBackOff because of the wrong image name(without the private docker registry name) while the job's status is still running after 2 days.

**What you expected to happen**:
The job status should change to failed.

**How to reproduce it (as minimally and precisely as possible)**:
Use a image that can not be pulled in the job spec.

**Environment**:
- Kubernetes version (use `kubectl version`): v10.0.0
- Cloud provider or hardware configuration: none
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux stcvm-linux165 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by charrywanganthony** [comment]
The job object also remains after so that you can view its status? It is up to you to delete old jobs.

**Comment by Itfly** [comment]
@charrywanganthony What are your talking? My issue is that the job's status is still running after its related pod's status have been changed to `ImagePullBackOff`

**Comment by Itfly** [comment]
There's a similar issue with ImagePullBackOff:
https://github.com/kubernetes/kubernetes/issues/66828
