### ISSUE TITLE
When deleting a cluster, kops ignores reclaim policy and deletes EBS volume disks even if reclaim policy is set to Retain

### ISSUE THREAD

**Issue by RomanKisilenko** [kubernetes/kubernetes#66750]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When EBS volumes are being created by kubernetes, reclaim policy is not included into AWS tags, thus kops is not able to figure out that you want to preserve the volumes when deleting a cluster.

**What you expected to happen**:
Kubernetes to tag volumes with reclaim policy.

**How to reproduce it (as minimally and precisely as possible)**:
1. Spin up a kops cluster
2. Create volumes with Retain reclaim policy

**Anything else we need to know?**:
See https://github.com/kubernetes/kops/issues/5526 for more details.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-12T22:24:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
A cluster on AWS

- Install tools: kops

**Comment by cjbottaro** [comment]
Please, PLEASE, yes. I lost a lot of data (albeit in testing/staging) due to this.

It's such a scary thought that we don't even allow `kops delete cluster` anymore, instead we force our admins to go through a shim which changes the labels prior to issuing the command.

Snapshots are not enough; data is still lost between the last snapshot and the loss of the volume.

We maintain a Cassandra cluster with complete change logs that we can rebuild data from, but... it uses volumes managed by Koob and kops.

**Comment by geekofalltrades** [comment]
Shouldn't this issue be on https://github.com/kubernetes/kops?

**Comment by RomanKisilenko** [comment]
@geekofalltrades Pls see the 
https://github.com/kubernetes/kops/issues/5526 for more information

**Comment by geekofalltrades** [comment]
Got it, thanks.

**Comment by isindir** [comment]
+1

**Comment by iskondi** [comment]
+1 This is a pain. Is there an accepted work around for stopping this?

**Comment by ChristopherHodge** [comment]
+1 This should definitely exist if it doesn't already.  I don't see any suggestion here?
