### ISSUE TITLE
kubeadm join fails if master takes too long to become ready

### ISSUE THREAD

**Issue by kir4h** [kubernetes/kubernetes#66768]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
(Given a scenario where the master and the node machines are created at the same time, and whenever the master takes too long to be created for any reason...)

When attempting to join a kubernetes node to a kubernetes cluster, the node reported that the token is invalid or has expired. But this is not true, a second kubeadm join later on with the same token succeeds.

**What you expected to happen**:

kubeadm join would succeed once the master is up and running

**How to reproduce it (as minimally and precisely as possible)**:

I found this while using kubicorn to deploy a cluster. But this should be reproducible by:

(pre-requirements: 2 ubuntu 16.04 machines up and running, namely "master" and "node")

1. Generate a bootstrap token (`kubeadm token generate`) and paste the generated token into the kubeadm configuration file

Example of _kubeadm-config-yaml_:

```apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: <token>
kubernetesVersion: 1.11.0
nodeName: master
api:
  advertiseAddress: <Master IP>
  bindPort: 443
apiServerCertSANs:
- <Master IP>
authorizationModes:
- Node
- RBAC
```

2. Perform a kubeadm join on the node, that should fail until master becomes ready (at this stage master is not even attempting to init the cluster)

`kubeadm join --node-name "node" --token "<token>" "<Master IP>" --discovery-token-unsafe-skip-ca-verification`

3. Wait for 5-10 minutes (in my latest test I simulated a 700 sleep before performing init on the master)

During this time, we should see that kubeadm join is reattempting until the master is ready
```[discovery] Failed to request cluster info, will try again: [Get https://10.132.143.109:443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.132.143.109:443: connect: connection refused]
....
[discovery] Failed to request cluster info, will try again: [Get https://10.132.143.109:443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.132.143.109:443: connect: connection refused]
```
4. Perform the init on the master

`kubeadm init --config kubeadm-config.yaml`

5. Once master is ready, an error is shown on the node stating that the token is invalid

``` 
[discovery] Failed to request cluster info, will try again: [Get https://10.132.143.109:443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.132.143.109:443: connect: connection refused]

[discovery] Failed to request cluster info, will try again: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get configmaps in the namespace "kube-public"]

[discovery] Failed to request cluster info, will try again: [configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get configmaps in the namespace "kube-public"]

[discovery] Failed to connect to API Server "10.132.143.109:443": token id "89df35" is invalid for this cluster or it has expired. Use "kubeadm token create" on the master node to creating a new valid token

couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
``` 
6. If we re-run the join command on the node, with the same token, it succeeds.

**Anything else we need to know?**:
I would say it's not very critical, given that the issue is only present when the master takes too long to init the cluster compared to the time when the node starts attempting the kubeadm join.
I am reporting it anyway because I guess that given kubeadm reattempts, philosophy is that once the master is ready kubeadm should succeed.

I suffered the issue 2-3 times because my master took too long to boot up (smaller machine, less resources and needs also to download images) in DigitalOcean, and was able to reproduce it later on by forcing a sleep of the master in the cloud-init bootstrap logic.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
``` 
- Cloud provider or hardware configuration:
`DigitalOcean`
- OS (e.g. from /etc/os-release):
``` 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux k8s-gpoc-master-0 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by neolit123** [comment]
> I would say it's not very critical, given that the issue is only present when the master takes too long to init the cluster compared to the time when the node starts attempting the kubeadm join.

i agree.

> I am reporting it anyway because I guess that given kubeadm reattempts, philosophy is that once the master is ready kubeadm should succeed.

in the k8s e2e tests we always wait for the master to be ready and we don't fail if it doesn't become ready until a certain timeout e.g. 5 minutes.

in kubeadm 1.13 we are adding a custom timeout for the control plane node's api server.
based on that expected timeout you can make your setup tolerate the delay.
this change cannot be backported to < 1.13.

for further kubeadm related issues please use the `kubernetes/kubeadm` issue tracker.

thanks
/close
