### ISSUE TITLE
Please tell me the conditions under which the workernode of the kubernetes Cluster is detached from the cluster.

### ISSUE THREAD

**Issue by mitsuaki0717** [kubernetes/kubernetes#66763]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
please re-open once you have details in the issue description.
thanks.

/close
