### ISSUE TITLE
Node doesn't have labels defined in --node-labels flag

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#66773]
Kubelet was started with the following flag:

```
$ sudo journalctl | grep node-labels
Jul 30 12:08:31 gke-scale-to-0-extra-pool-2-5c4c4233-xl7x kubelet[1540]: I0730 12:08:31.788159    1540 flags.go:27] FLAG: --node-labels="beta.kubernetes.io/fluentd-ds-ready=true,cloud.google.com/gke-nodepool=extra-pool-2"
```

But the node doesn't have the labels:

```
$ kubectl describe node gke-scale-to-0-extra-pool-2-5c4c4233-xl7x
Name:               gke-scale-to-0-extra-pool-2-5c4c4233-xl7x
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=n1-standard-4
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-central1
                    failure-domain.beta.kubernetes.io/zone=us-central1-c
                    kubernetes.io/hostname=gke-scale-to-0-extra-pool-2-5c4c4233-xl7x
Annotations:        container.googleapis.com/instance_id=5978818005557264751
                    node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
```

This is causing autoscaling tests to fail: [Should be able to scale a node group down to 0[Feature:ClusterSizeAutoscalingScaleDown]](https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gke-autoscaling) 

~~Tests and above replication come from GKE, but given that the flag is passed all the way to kubelet, I'd guess this isn't specific to that environment.~~

**Comment by aleksandra-malinowska** [comment]
cc @MaciekPytel

**Comment by liggitt** [comment]
labels are only added on initial registration of the Node object. if `--node-labels` was changed after that initial registration, the kubelet does not modify labels on start

**Comment by aleksandra-malinowska** [comment]
The labels were missing after initial node creation, but it looks like they could have been removed by another component just after node was registered.
