### ISSUE TITLE
the status of controller-manager is unhealthy

### ISSUE THREAD

**Issue by xujintao** [kubernetes/kubernetes#66777]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig api-machinery

**What happened**:
When i kubectl get componentstatuses
the status of controller-manager is Unhealthy and the message is:
> Get http://127.0.0.1:10252/healthz: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

and /var/log/kubernets/kube-controller-manager.INFO is:
> logs.go:49] http: TLS handshake error from 127.0.0.1:55434: tls: first record does not look like a TLS handshake

What i understand is apiserver should send https instead of http request to controller-manager while controller-manager binding secure address.

**What you expected to happen**:
I expect the status of controller-manager is healthy. 

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get componentstatuses
or curl http://127.0.0.1:10252/healthz

**Anything else we need to know?**:
1, kube-apiserver startup parameter is:
> [Service]
> ExecStart=/opt/k8s/bin/kube-apiserver \
>   --enable-admission-plugins=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
>   --anonymous-auth=false \
>   --experimental-encryption-provider-config=/etc/kubernetes/encryption-config.yaml \
>   --advertise-address=192.168.6.211 \
>   --bind-address=192.168.6.211 \
>   --insecure-port=0 \
>   --authorization-mode=Node,RBAC \
>   --runtime-config=api/all \
>   --enable-bootstrap-token-auth \
>   --service-cluster-ip-range=10.254.0.0/16 \
>   --service-node-port-range=8400-9000 \
>   --tls-cert-file=/etc/kubernetes/cert/kubernetes.pem \
>   --tls-private-key-file=/etc/kubernetes/cert/kubernetes-key.pem \
>   --client-ca-file=/etc/kubernetes/cert/ca.pem \
>   --kubelet-client-certificate=/etc/kubernetes/cert/kubernetes.pem \
>   --kubelet-client-key=/etc/kubernetes/cert/kubernetes-key.pem \
>   --service-account-key-file=/etc/kubernetes/cert/ca-key.pem \
>   --etcd-cafile=/etc/kubernetes/cert/ca.pem \
>   --etcd-certfile=/etc/kubernetes/cert/kubernetes.pem \
>   --etcd-keyfile=/etc/kubernetes/cert/kubernetes-key.pem \
>   --etcd-servers=https://192.168.6.211:2379,https://192.168.6.212:2379,https://192.168.6.213:2379 \
>   --enable-swagger-ui=true \
>   --allow-privileged=true \
>   --apiserver-count=3 \
>   --audit-log-maxage=30 \
>   --audit-log-maxbackup=3 \
>   --audit-log-maxsize=100 \
>   --audit-log-path=/var/log/kube-apiserver-audit.log \
>   --event-ttl=1h \
>   --alsologtostderr=true \
>   --logtostderr=false \
>   --log-dir=/var/log/kubernetes \
>   --v=2

2, kube-controller-manager startup parameter is:
> [Service]
> ExecStart=/opt/k8s/bin/kube-controller-manager \
>   --port=0 \
>   --secure-port=10252 \
>   --bind-address=127.0.0.1 \
>   --kubeconfig=/etc/kubernetes/kube-controller-manager.kubeconfig \
>   --service-cluster-ip-range=10.254.0.0/16 \
>   --cluster-name=kubernetes \
>   --cluster-signing-cert-file=/etc/kubernetes/cert/ca.pem \
>   --cluster-signing-key-file=/etc/kubernetes/cert/ca-key.pem \
>   --experimental-cluster-signing-duration=8760h \
>   --root-ca-file=/etc/kubernetes/cert/ca.pem \
>   --service-account-private-key-file=/etc/kubernetes/cert/ca-key.pem\
>   --leader-elect=true \
>   --feature-gates=RotateKubeletServerCertificate=true \
>   --controllers=*,bootstrapsigner,tokencleaner \
>   --horizontal-pod-autoscaler-use-rest-clients=true \
>   --horizontal-pod-autoscaler-sync-period=10s \
>   --tls-cert-file=/etc/kubernetes/cert/kube-controller-manager.pem \
>   --tls-private-key-file=/etc/kubernetes/cert/kube-controller-manager-key.pem \
>   --use-service-account-credentials=true \
>   --alsologtostderr=true \
>   --logtostderr=false \
>   --log-dir=/var/log/kubernetes \
>   --v=2

3, kube-scheduler startup parameter is:
> [Service]
> ExecStart=/opt/k8s/bin/kube-scheduler \
>   --address=127.0.0.1 \
>   --kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig \
>   --leader-elect=true \
>   --alsologtostderr=true \
>   --logtostderr=false \
>   --log-dir=/var/log/kubernetes \
>   --v=2
> Restart=on-failure
> RestartSec=5
> User=k8s

**Environment**: 
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
1 cpu, 1g memory

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux kube-master1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
etcd, keepalived, haproxy, kube-apiserver, kube-controller-manager, kube-scheduler

- Others:

**Comment by mritd** [comment]
@xujintao 

很抱歉的告诉你目前 `get cs` 命令仅仅会检测 http://127.0.0.1:10252 是否可以访问；你可以从[这里](https://github.com/kubernetes/kubernetes/blob/2da49321e62dfe8485282f691659e46a6d0c5aab/pkg/registry/core/rest/storage_core.go#L253)找到相关代码.

Sorry to tell you that the current `get cs` command will only detect if http://127.0.0.1:10252 is accessible; you can find the relevant code from [here](https://github.com/kubernetes/kubernetes/blob/2da49321e62dfe8485282f691659e46a6d0c5aab/pkg/registry/core/rest/storage_core.go#L253).

**Comment by xujintao** [comment]
@mritd 
Thanks. 
Now i have to use insecure port configuration to restart controller-manager.

**Comment by jmcmeek** [comment]
We (IBM Kubernetes Service) started seeing this issue in 1.12 when we explicitly disabled the insecure port for the controller-manager - and are doing the same for same for scheduler 1.13.  I don't use it myself, but some of our customers do.

The insecure port has been deprecated for both the scheduler (in 1.13) and controller-manager (in 1.12).  Should `get componentstatuses` be using HTTPS ports for both those?

Ports are configurable, should `get componentstatuses` be able to handle that?

It has other issues in a HA configuration (multiple schedulers and controller-managers - maybe report the leaders' health?).  

Its probably not the best best way to check health, but its there and some people use it.
