### ISSUE TITLE
the latency of api request was affected by compact when use etcd 3.3

### ISSUE THREAD

**Issue by yingnanzhang666** [kubernetes/kubernetes#66785]
**versions:**
kubernetes version: v1.9
etcd server version: v3.3.8
grpc client version: v1.7.5
etcd client version: v3.2.13

**cluster scale:**
167k pods, 5k nodes, 5 master nodes

**the api load on one master node:** 
DELETE pods: 56/s
PUT pods: 66/s
PATCH nodes: 158/s
LIST nodes (hit to etcd): 1/s
LIST all pods with fieldSelector(nodename) (hit to etcd): 1/s
![img_20180731_093953](https://user-images.githubusercontent.com/22782254/43433272-323524ec-94a9-11e8-9cea-02e237df2bbf.png)
<img width="1403" alt="screen shot 2018-07-30 at 11 55 40 pm" src="https://user-images.githubusercontent.com/22782254/43408505-2395be24-9454-11e8-9af3-232c6b00db8f.png">
From this dashboard, it shows spikes every five minutes. From the etcd logs, its the similar timestamp with etcd compact. And also the compact took a lot of time under this load, and compact about 330000 revision each time.
```
2018-07-30 15:51:51.565150 I | mvcc: finished scheduled compaction at 3189063539 (took 38.24535265s)
```
off that one LIST all pods load, the compact time is about 10+s.
Also found the db sync time is very large.
<img width="348" alt="screen shot 2018-07-31 at 12 03 03 am" src="https://user-images.githubusercontent.com/22782254/43408989-385d63ba-9455-11e8-86e0-1955483f796d.png">

Compared with using etcd 3.1.9, with the same load, compact time is only about 10+s, off that one LIST all pods load, the compact time is about 5~6s. meanwhile the db sync latency is only about 170ms.

**Comment by yingnanzhang666** [comment]
@wojtek-t @jpbetz @gyuho Do you have any idea about this?

**Comment by gyuho** [comment]
etcd storage compaction "does" block readers, writers, and APIs like hash check and snapshot. Requests may timeout during compaction. But we haven't checked the exact compact latencies between etcd versions.

**Comment by yingnanzhang666** [comment]
what about the db sync duration? under the same api load, when I switch to 3.1.9, the db sync duration is down to less than 200ms.

**Comment by jpbetz** [comment]
`--snapshot-count` changed from 10,000 to 100,000.in 3.2, and is known to have performance implications. But it looks like we're narrowed this one down specifically to the compaction operation so maybe we can rule that out?

**Comment by yingnanzhang666** [comment]
@jpbetz I see that change log, so actually, I have already specified `--snapshot-count=10000` in etcd parameter to have a try. The dashboard and result above were indeed test with snapshot-count 10000.

**Comment by wojtek-t** [comment]
@shyamjvs - FYI

**Comment by shyamjvs** [comment]
So I just checked an [earlier run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/192) of our 5k-node performance tests (where we're also creating 150k pods) with somewhat similar qps and the snapshot times look quite normal (~ 4-5s):

```
mvcc: finished scheduled compaction at 18018159 (took 5.122500743s)
mvcc: finished scheduled compaction at 18399484 (took 4.500646398s)
mvcc: finished scheduled compaction at 18782108 (took 4.956834392s)
```

(ref [etcd logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/192/artifacts/gce-scale-cluster-master/etcd.log))

However there are couple differences:

- it's etcd 3.2.18 (which is what we're using at k8s HEAD currently)
- it's a single node etcd (but I'm not sure if compaction time should be influenced by that)

**Comment by gyuho** [comment]
@yingnanzhang666 @shyamjvs 

> finished scheduled compaction

Compaction in etcd is a blocking operation on writes, so API server write throughput could be limited in such case. I will try more benchmarks with Kubernetes workloads.

**Comment by gyuho** [comment]
@jpbetz 

> the minimum changes to storage to update the oldest available revision (which would be a cheap operation) and then in the background

We already do that way, if I understand it correctly. Mark `"scheduledCompactRev"` in mvcc and schedule the actual compaction in the background but still requires the single writer lock in bolt DB.

> perform multiple small batch boltdb writes to clear our the data older than the revision such that they are performed concurrent to writes..

Currently, we batch compaction by 10000 entries. And bolt DB only allows a single write transaction, so not sure how concurrent write to mvcc would help :)
