### ISSUE TITLE
Consider renaming "pod_name" labels to "pod" and "container_name" labels to "container" for cAdvisor metrics

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#66790]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What's happening:**

Currently, the `container_*` metrics use the label "pod_name" to refer to the name of the pod in a timeseries and "container_name" to refer to container names within that pod.

kube-state-metrics, however, uses "pod" to refer to the names of pods and "container" to refer to names of containers. 

This difference makes it difficult to do joins on KSM metrics and cadvisor metrics, leading me to write queries like this one (which calculates the percentage of real utilization of quota per container -- namespace and podname templated in Grafana):

```
sum(irate(container_cpu_usage_seconds_total{namespace="$namespace",pod_name="$podname",container_name!="POD"}[1m])) by (container_name) / sum(label_join(kube_pod_container_resource_requests_cpu_cores{namespace="$namespace",pod="$podname"}, "container_name", "", "container")) by (container_name)
```

With normalized labels I could just write

```
sum(irate(container_cpu_usage_seconds_total{namespace="$namespace",pod="$podname",container!="POD"}[1m])) by (container) / sum(kube_pod_container_resource_requests_cpu_cores{namespace="$namespace",pod="$podname"}) by (container)
```

Hence, I propose renaming the "pod_name" labels to "pod" and "container_name" labels to "container" to normalize between the two data sources. I can attempt to write a patch for this.

**Why propose this here rather than telling KSM to match the cadvisor metrics?**

I reported this against KSM first: https://github.com/kubernetes/kube-state-metrics/issues/501

The [current Kubernetes instrumentation guidelines](https://github.com/kubernetes/community/blob/afcc37186a32cc92b24e99e27089d10ae48ed0cf/contributors/devel/instrumentation.md#resource-referencing) indicate the usage of "container" (vs. container_name), "pod" (vs. pod_name), etc.:

> An object is referenced by its unique name in a label named after the resource itself (i.e. `pod`/`deployment`/... and not `pod_name`/`deployment_name`) and the namespace it belongs to in the `namespace` label.

Fixing this would ensure the cadvisor metrics conform with the community guidelines.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.8.7-21 with internal patches 
- Kube-state-metrics image version: 1.2.0

**Comment by brancz** [comment]
I just added this to be discussed in the sig-instrumentation meeting, personally I'm all for it and we've discussed this a number of times. @DirectXMan12 we should figure out the timeline for node-metrics being reworked, if that is going to take a while then I think we should make these changes.

**Comment by DirectXMan12** [comment]
considering that now basically has a dependent change that has to go through first, I think that's ok
