### ISSUE TITLE
Using AWS NLB

### ISSUE THREAD

**Issue by patrickdk77** [kubernetes/kubernetes#66796]
/kind bug

**What happened**:
Connection timeout, packets go into the node and into the container, but no replies are seen

**What you expected to happen**:
A reply packet to my TCP sync request

**How to reproduce it (as minimally and precisely as possible)**:
Setup a service using an NLB, example:

apiVersion: v1
kind: Service
metadata:
  name: cas-test
  labels:
    app: cas-test
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      name: external
  selector:
    app: cas-test

Setup any https webserver as a cas-test container.

Connections from FROM another container on the same kubernetes node that is running the cas-test container will fail, connections coming from any other source will work as expected.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.8 (was 1.9.3 when first noticed)
- Cloud provider or hardware configuration: AWS, rf4.xlarge
- OS (e.g. from /etc/os-release): kops 1.9.0 debian packages
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
@kubernetes/sig-aws-misc

**Comment by micahhausler** [comment]
Hi thanks, this is a known limitation of internal NLB, it doesn’t support hairpinning. https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html

Possible mitigations for this would be to have Kubernetes support IP target type, or use ProxyProtocol. You could also run your client pods on separate nodes from the service that is behind the NLB
https://github.com/kubernetes/features/issues/423

/close

**Comment by patrickdk77** [comment]
> @patrickdk77 Not fully related to this. But did the `internal-` annotation actually work for you? Or is it a public facing NLB regardless of the `internal` annotation?

This had to have worked, as if it was external, it wouldn't have been a hairpinning issue. Since it would have gone out the nat address on one ip, and back in another ip for the nlb.

To work around the hairpinning issue, I just completely dropped the usage of everything, and just had all the pods use the cluster ip of the service instead.

**Comment by nrvmodi** [comment]
I am facing the same issue
