### ISSUE TITLE
Cpu average consumption

### ISSUE THREAD

**Issue by Alphapage** [kubernetes/kubernetes#66794]
Hello,

I have installed Kubernetes on my local windows PC using minikube or docker for windows without any container running.
In both cases, Kubernetes consumes approximatively 20 percents of the cpu (Intel 5Y10) constantly.

Is it the normal cpu usage to have Kubernetes managing the nodes ?
Do you plan to optimize and reduce Kubernetes resource utilization or is it a limitation ?
I can't find any info.

Thank you in advance for your answers. /sig cpu

**Comment by Alphapage** [comment]
I had a little time to test minikube on ubuntu 18.04 and virtualbox with the same PC and minikube is using approximatively 15 percents of the cpu.

I don't have a mac, so I don't know if minikube on ubuntu is eating cpu.

/sig ubuntu /sig linux

**Comment by PatrickLang** [comment]
/remove-sig windows

Minikube and Docker for Windows run Linux VMs with Kubernetes inside them. It would be best to follow up on those forums on troubleshooting around CPU usage for those VMs.

SIG-Windows is focused on building what's needed to add a Windows node to a Kubernetes cluster to run Windows apps.

**Comment by dims** [comment]
may be a better venue is to ask https://github.com/kubernetes/minikube folks?

/close
