### ISSUE TITLE
Handle fsnotify errors in pluginwatcher

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#66802]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
Currently pluginwatcher doesn't watch for fsnotify errors. However, we have seen issues in the past that fsnotify error could happen on some systems, e.g., when we have too many fsnotify registered. We would like to add this support in pluginwatcher. Basically, we need to select fsnotify.Errors event, and then see how we should handle such error event. We may start with log error at the beginning and explore whether more advanced handling is needed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by figo** [comment]
i will work on it if nobody already work on it, thanks
