### ISSUE TITLE
Cloud Provider experiences

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#66825]
/kind feature
/sig cloud-provider

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Brightbox

- OS (e.g. from /etc/os-release):
Ubuntu 18.04 LTS 

- Kernel (e.g. `uname -a`):
Linux srv-jidtj 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Others:

As requested in kubeadm #526

I've been implementing the Brightbox cloud provider over the last few weeks, and I thought it may be useful to note down what issues I came across building it and implementing it.

Therefore in no particular order of priority or impact:

- kubeadm support for cloud-provider is a bit hit and miss. The latest config now requires three entries on the master, and a configuration entry on the node to enable cloud-provider external. 

- kube-proxy daemon sets created by kubeadm are scheduled before the node is initialised by the cloud-provider. It seems to ignore the uninitialised taint set by kubelet. I've logged that at kubeadm initially (https://github.com/kubernetes/kubeadm/issues/1027), but problems like this seem to want to drop down the gap between sigs. 

- There seems to be some disagreement about whether a cloud-controller-manager should be run as a Deployment or a Daemonset - with the documented example being a daemonset limited to master nodes, but example providers (like DO) using a Deployment. Why choose one over the other? 

- The cluster role setup is documented here: https://kubernetes.io/docs/concepts/architecture/cloud-controller/ but then not used at all by the example daemonset here https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

- Similarly there is no documentation anywhere about how to set up the 'use-service-account-credentials' option.

- the cloud controller serves insecure by default. It wasn't clear what to do to turn that off.

- setting up the TLS system is somewhat challenging - as the controller appears to serve connections and create connections. Does this require two sets of certificates or will one do? How do you feed in the service account certificates to the controller? None of the examples explain how to connect securely, despite kubeadm setting everything else up with client certificates

- Copying the controller-manager out of tree breaks the magic kubernetes version system within the code, so the cloud-controller always displays v0.0.0. That version then ends up in log messages. 
```
$ ./brightbox-cloud-controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```
No doubt there is a magic ldflags incantation to sort it out somewhere. A Makefile pro-forma would be handy. 

- the usual Go version management hell, with all the fun of tracking the various moving parts as k8s moves from one version to the next. Just getting the cloud-provider to compile during the move from 1.10 to 1.11 was a challenge at times. How do we do dependencies and how should we maintain sync with the mainline code over time? 

- the cluster requirement is confusing. HasClusterID is required yet the clusters interface doesn't appear to be used by anything.

- How do we end to end test a new cloud provider implementation. Is there a common core within k8s we can leverage? 

Hope that is of some use and doesn't come across too badly. It's a big old system with lots of moving parts and, after all, I have managed to get the provider working!

**Comment by dims** [comment]
cc @andrewsykim @hogepodge @cheftako @jagosan

**Comment by andrewsykim** [comment]
This is really valuable feedback, thank you @NeilW! On the documentation front, we are working to standardize this across the board so we'll definitely take this into consideration!

**Comment by andrewsykim** [comment]
To answer some of the questions here:

> Copying the controller-manager out of tree breaks the magic kubernetes version system within the code, so the cloud-controller always displays v0.0.0. That version then ends up in log messages.

I agree versioning semantics is a bit conversion. We should document how to do versioning correctly. For the time being though, the CCM actually follows the same semantics as upstream but you're required to manage release versions, etc yourself. If you tag/version your releases the `--version` flag should work as expected (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/version/version.go#L26-L42)).  

> the cloud controller serves insecure by default. It wasn't clear what to do to turn that off.

This is a known issue and the kube-apiserver & kube-controller-manager face the same problem. I believe this is on apimachinery's radar though. 

> There seems to be some disagreement about whether a cloud-controller-manager should be run as a Deployment or a Daemonset - with the documented example being a daemonset limited to master nodes, but example providers (like DO) using a Deployment. Why choose one over the other?

There's really is no difference, you can use Deployment or Daemonset it all depends on your setup. Daemonset only works though if you have "registered" masters (i.e. kubelets running on master node, this is expected in kubeadm so with kubeadm installs maybe daemonset should be recommended).

> Similarly there is no documentation anywhere about how to set up the 'use-service-account-credentials' option.

In theory, this should not be any different from `--use-service-account-credentials` but I agreed there's benefits to document that. 

> setting up the TLS system is somewhat challenging - as the controller appears to serve connections and create connections. Does this require two sets of certificates or will one do? How do you feed in the service account certificates to the controller? None of the examples explain how to connect securely, despite kubeadm setting everything else up with client certificates

This should be done by default if you are using service accounts and CCM is running in-cluster.

> How do we end to end test a new cloud provider implementation. Is there a common core within k8s we can leverage?

See https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md. 

Hope this helps for now!

**Comment by hogepodge** [comment]
Yes, this is going to be useful.

@dims do you have production experience that has worked around some of the issues mentioned?
