### ISSUE TITLE
PersistentVolumeLabel  admission plugin is enabled by default but prints deprecation warning message

### ISSUE THREAD

**Issue by AlexDiamanti** [kubernetes/kubernetes#66829]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Wrong proxy-client-cert-file file causes apiserver to restart due to loading by default deprecated module PersistentVolumeLabel.

--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority,PodPreset

Jul 30 22:34:54 appserv9 kube-apiserver[19025]: I0730 22:34:54.420915   19025 plugins.go:149] Loaded 11 admission controller(s) successfully in the following order: NamespaceLifecycle,PodPreset,LimitRanger,ServiceAccount,Priority,DefaultTolerationSeconds,**PersistentVolumeLabel**,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota.
...
Jul 30 22:34:56 appserv9 kube-apiserver[19025]: W0730 22:34:56.370374   19025 admission.go:68] **PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.**

**What you expected to happen**:
No PersistentVolumeLabel loaded.

**How to reproduce it (as minimally and precisely as possible)**:

Add proxy-client-cert-file with non existing file (I had typo in extension cert instead of crt)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Diamanti D10

- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux appserv9 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by AlexDiamanti** [comment]
@kubernetes/sig-release-bugs

**Comment by liggitt** [comment]
the proxy client argument is not related to admission config. `--enable-admission-plugins` specifies plugins to enable *in addition to the default plugins*. It appears that despite printing a warning message about being deprecated, the "PersistentVolumeLabel" plugin is still enabled by default.

/sig storage
/remove-sig release

**Comment by liggitt** [comment]
also, the warning message you are seeing is non-fatal... it would not cause the apiserver to restart. specifying an invalid proxy file cert would prevent the apiserver from starting.

**Comment by liggitt** [comment]
@kubernetes/sig-storage-bugs the comment by the deprecation warning isn't very clear... do we have to wait until cloud-controller-manager is running before we should actually disable that admission plugin by default? if so, it probably shouldn't warn and ask people to remove it yet, right?

**Comment by msau42** [comment]
The pvlabel admission controller was [removed from apiserver default options](https://github.com/kubernetes/kubernetes/pull/64326), however deployment methods like kube-up may still be enabling it.

**Comment by msau42** [comment]
Also the pvlabel admission controller is only needed if you use aws, azure or gce volumes.

**Comment by liggitt** [comment]
> The pvlabel admission controller was [removed from apiserver default options](https://github.com/kubernetes/kubernetes/pull/64326), however deployment methods like kube-up may still be enabling it.

that pull request does the opposite of that... it enables it by default

**Comment by shrinandj** [comment]
I'm using `kops` to operate k8s cluster. I don't see the PersistentVolumeLabel admission controller in the kops config, nor in the api-server command line arguments. Yet, I see the api-server logs warning about the PersistentVolumeLabel admission controller. Where is the api-server getting it from? I'm using K8S version 1.10.7.

kops config:
```
    enableAdmissionPlugins:
    - PodTolerationRestriction
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - NodeRestriction
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
```

api-server args:
```
--enable-admission-plugins=PodTolerationRestriction,Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```

**Comment by liggitt** [comment]
--enable-admission-plugins specifies plugins to enable in addition to the default plugins. the persistent volume label admission plugin was in the "enabled by default" list [until 1.11](https://github.com/kubernetes/kubernetes/pull/64326/commits/4c3fa4f9baa79ab08a4d39e5d40fb66617af111d)

**Comment by shrinandj** [comment]
Oh.. ok. Thanks for the update!
