### ISSUE TITLE
Unable to install Kubernetes following the official installation guide on CentOS 7 on a VM

### ISSUE THREAD

**Issue by pcm1984** [kubernetes/kubernetes#66826]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug
/sig Release
/sig CLI

**What happened**:
When I execute the following commands (taken from the official installation guide for kubernetes),  the output is unexpected (shown below: )
Command (On CentOS 7): 
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF
setenforce 0
yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet

Output: 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.sonn.com
 * extras: mirror.sesp.northwestern.edu
 * updates: mirrors.cat.pdx.edu
kubernetes/signature                                                               |  454 B  00:00:00
kubernetes/signature                                                               | 1.4 kB  00:00:00 !!!
kubernetes/primary                                                                 |  33 kB  00:00:00
kubernetes                                                                                        237/237
**No package kubelet available.
No package kubeadm available.
No package kubectl available.**
Error: Nothing to do

**What you expected to happen**:
kubeadm, kubeclt and kubelet get installed and are enabled
**How to reproduce it (as minimally and precisely as possible)**:

Run the above mentioned commands on centos 7 (by following the guide at https://kubernetes.io/docs/setup/independent/install-kubeadm/)
**Anything else we need to know?**:
Docker version: Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Environment**:
- Kubernetes version (use `kubectl version`): Unable to install the latest version following the official guide.
- Cloud provider or hardware configuration: Vertual machine as per the guidelines on the official guide(2GB ram and 2 CPUs)
- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux k1 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by saravana1992** [comment]
Hi 

It sounds like packages not found by yum repo commands.
Do try yum repo clean & yum update & then try installing the packages.

**Comment by pcm1984** [comment]
I did that several times. but with no success.

**Comment by mkoderer** [comment]
The `exclude=kube*` will actually exclude all pkgs. Just remove it and it should work.

**Comment by pcm1984** [comment]
This was solved. There is a mistake in the docs. 

I can see there is a mistake in the docs.

Line containing exclude=kube* should be removed.

It should be as follows:

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet

Please refer SO issue at https://stackoverflow.com/questions/51615343/unable-to-install-kubernetes-latest-version-following-the-official-installation

**Comment by mkoderer** [comment]
Bug was introduced with:
https://github.com/kubernetes/website/commit/88569b1ddc9fb13790cfda8b9ba8edfdef491ee0

**Comment by mkoderer** [comment]
Addressed with: https://github.com/kubernetes/website/pull/9689

**Comment by pcm1984** [comment]
I can close the issue if everything else is okay.

**Comment by cliffbdf** [comment]
There also seems to be an issue with the "Install CNI plugins" section. I get errors when running the curl command: e.g., I get,
tar: ./ptp: Cannot open: File exists

If I run as root, I get,
gzip: stdin: not in gzip format

**Comment by rajesh-kanakabandi** [comment]
I am getting a transaction check error for the kubelet and kubectl binaries.

```
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.11.2-0 will be installed
--> Processing Dependency: kubernetes-cni >= 0.6.0 for package: kubeadm-1.11.2-0.x86_64
--> Processing Dependency: cri-tools >= 1.11.0 for package: kubeadm-1.11.2-0.x86_64
---> Package kubectl.x86_64 0:1.11.2-0 will be installed
---> Package kubelet.x86_64 0:1.11.2-0 will be installed
--> Running transaction check
---> Package cri-tools.x86_64 0:1.11.0-0 will be installed
---> Package kubernetes-cni.x86_64 0:0.6.0-0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================
 Package                             Arch                        Version                         Repository                       Size
=======================================================================================================================================
Installing:
 kubeadm                             x86_64                      1.11.2-0                        kubernetes                      7.5 M
 kubectl                             x86_64                      1.11.2-0                        kubernetes                      7.5 M
 kubelet                             x86_64                      1.11.2-0                        kubernetes                       18 M
Installing for dependencies:
 cri-tools                           x86_64                      1.11.0-0                        kubernetes                      4.2 M
 kubernetes-cni                      x86_64                      0.6.0-0                         kubernetes                      8.6 M

Transaction Summary
=======================================================================================================================================
Install  3 Packages (+2 Dependent packages)

Total size: 46 M
Installed size: 228 M
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /usr/bin/kubelet from install of kubelet-1.11.2-0.x86_64 conflicts with file from package kubernetes-node-1.5.2-0.7.git269f928.el7.x86_64
  file /usr/bin/kubectl from install of kubectl-1.11.2-0.x86_64 conflicts with file from package kubernetes-client-1.5.2-0.7.git269f928.el7.x86_64

Error Summary
-------------
```

**Comment by pcm1984** [comment]
Looks like you have older version of Kubernetes installed on your machine. or may be some files from your previous installation that did not get cleaned up?

**Comment by rajesh-kanakabandi** [comment]
@pcm1984 thanks for pointing it out. that is true. an older version of kubernetes was chefed in that i was not aware of.

**Comment by vbabak** [comment]
```
yum remove kubernetes-client 
yum remove kubernetes-node
yum clean packages
yum update
yum install -y kubelet kubeadm kubectl
systemctl enable kubelet && systemctl start kubelet
```

**Comment by timothysc** [comment]
Closing, please follow https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#14-installing-kubeadm-on-your-hosts for .rpm and .deb distros.  

If you have issues, please open them here - https://github.com/kubernetes/kubeadm

**Comment by satwikk** [comment]
This resolved the issue. Missing "EOF"

https://stackoverflow.com/a/51615990/4673027

**Comment by shattenjager** [comment]
> Hi
> 
> It sounds like packages not found by yum repo commands.
> Do try yum repo clean & yum update & then try installing the packages.

There is no such thing as "yum repo clean", maybe you meant "yum clean all"?

**Comment by davizucon** [comment]
Still error for me on CentOS 7.5 , worked after removed line:
exclude=kubelet kubeadm kubectl

**Comment by sbellan** [comment]
I think it is because of -- in the commands is being changed to – in the markdown rendering, causing copy paste to fail to run those commands successfully.

**Comment by nelsonspbr** [comment]
@davizucon I confirm that removing the `exclude=...` line was required to install Kubernetes on CentOS following the official instructions.

**Comment by integrii** [comment]
This issue was opened in 2018 and is still broken after being closed.  Installation is broken on Centos 8 right now if the kubeadm setup instructions are followed.

**Comment by kyohwang** [comment]
--disableexcludes=kubernetes  works for me.
Whereas it shows  –disableexcludes=kubernetes in the current official docs.

**Comment by initdude** [comment]
> This was solved. There is a mistake in the docs.
> 
> I can see there is a mistake in the docs.
> 
> Line containing exclude=kube* should be removed.
> 
> It should be as follows:
> 
> cat < /etc/yum.repos.d/kubernetes.repo [kubernetes] name=Kubernetes baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 enabled=1 gpgcheck=1 repo_gpgcheck=1 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg EOF setenforce 0 yum install -y kubelet kubeadm kubectl systemctl enable kubelet && systemctl start kubelet
> 
> Please refer SO issue at https://stackoverflow.com/questions/51615343/unable-to-install-kubernetes-latest-version-following-the-official-installation

thanks, worked for me :+1:
