### ISSUE TITLE
Mount cannot be satisfied for container

### ISSUE THREAD

**Issue by du2016** [kubernetes/kubernetes#66821]
kubelet_pods.go:180] Mount cannot be satisfied for container "xxx", because the volume is missing or the volume mounter is nil: {Name:default-token-ln85q ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}

**Comment by du2016** [comment]
@kubernetes/sig-node-bugs

**Comment by du2016** [comment]
kubelet: E0731 18:38:02.367543    1766 kuberuntime_manager.go:733] container start failed: CreateContainerConfigError: cannot find volume "default-token-ln85q" to mount into container "xxx"

**Comment by du2016** [comment]
i always have this error ,with lots of retry ,it create success

**Comment by WanLinghao** [comment]
Can you please show your pod config file

**Comment by du2016** [comment]
@WanLinghao this error is can't find the default token,i don't think it's some thing wrong about pod config file,because default token is auto mounted by kubelet,not config by myself

**Comment by AntonFriberg** [comment]
Perhaps you are mounting configMaps or secrets in `/run` or `/run/secrets`? Since 1.9.4 configMaps and secrets are always mounted as read-only filesystem causing pods to crash since kubernetes needs to place files in `/run/secrets/kubernetes.io`.

**Comment by du2016** [comment]
@AntonFriberg no i have not mount everying,pod only need mount the default token

**Comment by liqlin2015** [comment]
@AntonFriberg We got this issue too in kubernetes 1.10.0 cluster. Any other reason which may cause `cannot find volume \"default-token-...`? Some race condition issue?

**Comment by WanLinghao** [comment]
@liqlin2015 @du2016 debug is very hard without yaml file of pods

**Comment by du2016** [comment]
i have remove weave scope plugin,then this problem have  not occur

**Comment by tianchen92** [comment]
@du2016 Can you explain a little more how to resolve these problem? I met the same error and searched for a long time. Thanks!
