### ISSUE TITLE
CLOSE_WAIT connections on master node Not released when  WebSocket closed

### ISSUE THREAD

**Issue by liyongxian** [kubernetes/kubernetes#66820]
Hi
--kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
--- OS
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
- Kernel 
Linux rancher-server 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
**What happened:**
When App(WebSocket) was closed(status of client WebSocket was closed ),CLOSE_WAIT connections on master node were not released.
![1120180731180756](https://user-images.githubusercontent.com/18571576/43453532-f5390312-94ec-11e8-8f90-7c03174d4070.jpg)

**APP deployment:**
APP(WebSocket ) --> kube-proxy --> svc(NodePort)

**SVC:**

![20180731180527](https://user-images.githubusercontent.com/18571576/43453317-610bdc8c-94ec-11e8-938c-a621b7b55aec.jpg)
thanks.

**Comment by pires** [comment]
I'm seeing this more and more in busy clusters and more issues too, such as https://github.com/kubernetes/kubernetes/issues/67119 and https://github.com/kubernetes/kubernetes/issues/66133.

CLOSE_WAIT means the server is waiting on clients which have sent FIN packets to close the socket on their end. I'm wondering if this is a failure of the apiserver library or client-side, where client-go is, I believe, the most used library out there.
