### ISSUE TITLE
[1.12] potential impact on kubeadm after enabled `ScheduleDaemonSetPods`

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#66831]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Once upgraded to 1.12, Daemonset pod scheduling will be taken over by default scheduler instead of Daemonset controller. This changes behavior of daemonset a little bit - from "daemonet controller respects taint" to "default scheduler doesn't respect taint" - check more details on #66348.

In kubeadm's perspective, here are potential impacts:

- [x] ~~HOLD: all daemonsets launched **directly** by kubeadm would have "Pending" pod on master node - (as far as I can tell it's just `kube-proxy`) - I'm raising PR #66830 to fix this kind of inconsistency.~~ Unnecessary due to #66953
- [x] ~~HOLD: all **dependent** daemonsets of a fully-functional kubeadm cluster would also have "Pending" pod on master node - e.g. calico would have "calico-node" running on master node. So I would hope kubeadm sig can either notify the "dependency" team or make external PRs.~~ Unnecessary due to #66953
- [ ] in kubeadm's provision lifecycle, ensure kube-scheduler comes prior to deploying daemonsets.
- [ ] other impacts ...

BTW: to highlight again, only daemonset is effected. That's to say, {kube|core}dns which uses `Deployment` behaviors the same.

**Comment by ravisantoshgudimetla** [comment]
@Huang-Wei Can we close this issue? AFAIK, in kubeadm scheduler comes as static pod, so this should work after your fix https://github.com/kubernetes/kubernetes/pull/66953

**Comment by Huang-Wei** [comment]
@ravisantoshgudimetla yeap, let's close this. And reopen if there is any issue like daemonset was launched prior to scheduler pod.
