### ISSUE TITLE
Kubernetes kompose up

### ISSUE THREAD

**Issue by yadaraviteja** [kubernetes/kubernetes#66838]
**What happened**: I am using the AWS EKS for the Kubernetes my cluster and worker nodes are running perfect. I want to deploy the one website into EKS. I has "docker-compose-file" and I am trying to convert the compose-file into "Kompose-file" for deployment. 
**What you expected to happen**:
By using the command "kompose convert" docker-compose-file is converted into Kompose-file.
for deploying I use "kompose up" it is asking me the credentials which credential should I provide

**Environment**: EKS
- Kubernetes version (use `kubectl version`):Client Version: v1.10.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):centos
- Kernel (e.g. `uname -a`):
- Install tools:kompose
- Others:
docker compose-file:
version: "2"

services:
  redis-master:
    image: k8s.gcr.io/redis:e2e
    ports:
      - "6379"

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    ports:
      - "6379"
    environment:
      - GET_HOSTS_FROM=dns

  frontend:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "80:80"
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer

kubeconfig file:

apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"

NodeInstanceRole:

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

My-Output:

[root@ip-ip address sample-kompose]# kompose up
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead.

Please enter Username:

**Comment by dims** [comment]
Please file this issue in https://github.com/kubernetes/kompose

/close
