### ISSUE TITLE
HPA not work correctly

### ISSUE THREAD

**Issue by cpwujoewu** [kubernetes/kubernetes#66848]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

> /kind feature

**What happened**:
I configure a hpa from 1 pod to 10 pods, using CPU utilization 40%
It works fine when I increase loading by using jmeter,  but when I stop loading test, the pods only scales down from 10 to 3. I have checked the CPU utilization is 0%

**What you expected to happen**:
the pods should scale down from 10 to 1

**How to reproduce it (as minimally and precisely as possible)**:
reproduce step:
1. rebuild the application pod, set the default replica to 1
2. apply the hpa: 1~10 pods, CPU utilization 40%
3. start loading test using jmeter, and the pods will scale up from 1 to 10
4. stop jmeter. The pods will scale down from 10 to 3

**Anything else we need to know?**:
kubectl describe hpa gets : 
Normal  SuccessfulRescale  24m (x16 over 20d)  horizontal-pod-autoscaler  New size: 3; reason: All metrics below target

kubectl get hpa gets:
NAME              REFERENCE                    TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
database-hpa      Deployment/database-pod      0% / 40%   1         10        3          23d

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.4-gke.0
- Cloud provider or hardware configuration:
google cloud platform
- OS (e.g. from /etc/os-release):
Nodes OS: container-optimized-OS
container OS: centos 7
- Kernel (e.g. `uname -a`):
Linux database-pod-7587cc8bcd-khztw 4.14.22+ #1 SMP Wed May 30 13:49:27 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
![default](https://user-images.githubusercontent.com/1677194/43505498-bb916ee4-9599-11e8-8284-74eba8633f79.PNG)

**Comment by interma** [comment]
@cpwujoewu 

From the last rescaling, scale-down/up will wait for more minutes, so I think you should wait more time. e.g. 5min
Maybe your issue hits this condition.

Refer:

> Scale-down will wait for 5 minutes from the last rescaling.

From autoscaling-algorithm section of HPA doc:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/horizontal-pod-autoscaler.md#autoscaling-algorithm

**Comment by yue9944882** [comment]
/cc @DirectXMan12 @MaciekPytel @jbartosik 

report inconvenience 😢
autoscaling by multiple data point could help us from constant rescale cool-down limit

**Comment by jbartosik** [comment]
If this was caused by scale down forbidden window then I'm working on a change that will help. Now HPA waits for 5 minutes between scale downs (like @interma said). After my changes HPA will scale down to highest recommendation in last few minutes.

There are more details in [this doc](https://docs.google.com/document/d/1IdG3sqgCEaRV3urPLA29IDudCufD89RYCohfBPNeWIM/).

**Comment by DirectXMan12** [comment]
/remove-sig scalability
/sig autoscaling

/close
(as per the merging of @jbartosik's PR)
