### ISSUE TITLE
pod之间访问是正常，所有Pod也是正常，容器与自己主机ping也是正常，但是容器不能访问外网

### ISSUE THREAD

**Issue by ming19871211** [kubernetes/kubernetes#66852]
![image](https://user-images.githubusercontent.com/18570747/43510129-3a23959a-95a7-11e8-8a03-2dde9828fe23.png)

**Comment by ming19871211** [comment]
创建集群的方式是：kubeadm init --kubernetes-version=v1.10.3 --pod-network-cidr=10.224.0.0/16  --feature-gates CoreDNS=true

**Comment by yue9944882** [comment]
😃Magic portal: [https://translate.google.com/m/translate](https://translate.google.com/m/translate)

**Comment by vsxen** [comment]
run `iptables -t nat -L`  and show output

**Comment by ming19871211** [comment]
![image](https://user-images.githubusercontent.com/18570747/43588194-8c57e6fc-969e-11e8-99ae-4203965b4645.png)

**Comment by ming19871211** [comment]
![image](https://user-images.githubusercontent.com/18570747/43588301-c6d78fe4-969e-11e8-930b-1dd107272910.png)

**Comment by ming19871211** [comment]
![image](https://user-images.githubusercontent.com/18570747/43588565-561bcb8e-969f-11e8-9a72-e6c3367991a5.png)
![image](https://user-images.githubusercontent.com/18570747/43588590-6467f55a-969f-11e8-82f6-30854a6cfb84.png)

**Comment by timothysc** [comment]
You need to apply your CNI.  If you are still having issues when following these instructions - https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#14-installing-kubeadm-on-your-hosts

Please open an issue here - https://github.com/kubernetes/kubeadm

**Comment by BedivereZero** [comment]
same problem
the problem still exists after deploying a CNI(calico)

**Comment by readme2gh** [comment]
> 创建集群的方式是：kubeadm init --kubernetes-version=v1.10.3 --pod-network-cidr=10.224.0.0/16 --feature-gates CoreDNS=true

你解决了吗,我也是遇到这个问题,求帮助

**Comment by 54853315** [comment]
calico什么版本？3.8.*有bug，会显示1/1 ready，实际上要进入每一个describe pod calico-node-xxxxx 查看Events才知道是否成功部署。

**Comment by 54853315** [comment]
容器不能访问外网，一般是CoreDNS的问题：

https://segmentfault.com/q/1010000021184218
