### ISSUE TITLE
no matches for kind "KubeSchedulerConfiguration" in version "componentconfig/v1alpha1"

### ISSUE THREAD

**Issue by devinmcginty** [kubernetes/kubernetes#66874]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I am trying to disable preemption with pod priority enabled on a 1.11.0 cluster. I was following [these instructions](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#how-to-disable-preemption) from the official documentation, which says that this can be accomplished by turning off preemption via the `KubeSchedulerConfiguration` under the `componentconfig` API. Attempting this gives me an error saying `no matches for kind "KubeSchedulerConfiguration" in version "componentconfig/v1alpha1"`

I explicitly enabled `componentconfig/v1alpha1: "true"`. However, it is not showing up in the `kubectl api-versions` list, even after a rolling restart and manually cycling the master nodes. I also double checked that all of the nodes are on 1.11.0.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I have this file saved as `schedulertest.yaml`
```
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
algorithmSource:
  provider: DefaultProvider
disablePreemption: true
```
To reproduce
```
 $ kubectl apply -f schedulertest.yaml
error: unable to recognize "schedulertest.yaml": no matches for kind "KubeSchedulerConfiguration" in version "componentconfig/v1alpha1"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:34Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
`Debian GNU/Linux 8 (jessie)`
- Kernel (e.g. `uname -a`):
`Linux [...] #1 SMP Sat May 26 22:32:45 UTC 2018 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by devinmcginty** [comment]
@kubernetes/sig-scheduling-bugs
I apologize if this is the wrong group to tag. I wasn't sure if `scheduling` or `api-machinery` was more appropriate.

**Comment by resouer** [comment]
Is `kube-scheduler --write-config-to=temp.conf` works in your cluster? What's the api version inside the `temp.conf`?

**Comment by byndcivilization** [comment]
```algorithmSource:
  provider: DefaultProvider
apiVersion: componentconfig/v1alpha1
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: ""
  qps: 50
disablePreemption: false
enableContentionProfiling: false
enableProfiling: false
failureDomains: kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region
hardPodAffinitySymmetricWeight: 1
healthzBindAddress: 0.0.0.0:10251
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  lockObjectName: kube-scheduler
  lockObjectNamespace: kube-system
  renewDeadline: 10s
  resourceLock: endpoints
  retryPeriod: 2s
metricsBindAddress: 0.0.0.0:10251
schedulerName: default-scheduler```

**Comment by byndcivilization** [comment]
@bsalamat I think you were on the original PR that enabled this feature. Is there something special we should do to apply against the componentconfig/v1alpha1 endpoint?

**Comment by bsalamat** [comment]
cc/ @stts @ravisantoshgudimetla Could you guys please take a look at this issue?

**Comment by liggitt** [comment]
see https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/ (or `kube-scheduler --help`) for details on providing the config file to the scheduler

**Comment by byndcivilization** [comment]
@liggitt just to confirm if i update the kube-scheduler.manifest to point at a custom config file it should load those configs. When i cat the output of --write-config-to after doing this, its not reflecting any of these changes.

**Comment by Sakib37** [comment]
I am also facing the same issue in k8s 1.13.0. I used the following configuration file and systemd unit file to start kube-scheduler.

cat /k8s/config/kube-scheduler-configuration.yaml
`kind: KubeSchedulerConfiguration
apiVersion: componentconfig/v1alpha1
algorithmSource:
  provider: DefaultProvider
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: "/vagrant/conf/kubeconfig/k8s-server-1/k8s-server-1-kube-scheduler.kubeconfig"
  qps: 50
disablePreemption: false
enableContentionProfiling: false
enableProfiling: false
failureDomains: kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region
hardPodAffinitySymmetricWeight: 1
healthzBindAddress: 0.0.0.0:10251
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  lockObjectName: kube-scheduler
  lockObjectNamespace: kube-system
  renewDeadline: 10s
  resourceLock: endpoints
  retryPeriod: 2s
metricsBindAddress: 0.0.0.0:10251
schedulerName: default-scheduler`

Systemd file for kube-scheduler:
`[Unit]
Description=Kubernetes Scheduler
Documentation=https://github.com/kubernetes/kubernetes

[Service]
User=kubernetes
EnvironmentFile=/etc/default/kube-scheduler.conf
ExecStart=/usr/local/bin/kube-scheduler \
    --config=/k8s/config/kube-scheduler-configuration.yaml
    --v=2
Restart=on-failure
RestartSec=5
LimitNOFILE=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
`

Modified journalctl output for kube-scheduler

`Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.599023   16772 flags.go:33] FLAG: --address="0.0.0.0"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.601935   16772 flags.go:33] FLAG: --algorithm-provider=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602191   16772 flags.go:33] FLAG: --alsologtostderr="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602330   16772 flags.go:33] FLAG: --authentication-kubeconfig=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602434   16772 flags.go:33] FLAG: --authentication-skip-lookup="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602544   16772 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602645   16772 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602831   16772 flags.go:33] FLAG: --authorization-kubeconfig=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.602945   16772 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603059   16772 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603172   16772 flags.go:33] FLAG: --bind-address="0.0.0.0"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603296   16772 flags.go:33] FLAG: --cert-dir=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603399   16772 flags.go:33] FLAG: --client-ca-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603496   16772 flags.go:33] FLAG: --config="/var/lib/kubernetes/kube-scheduler-configuration.yaml"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603593   16772 flags.go:33] FLAG: --contention-profiling="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603698   16772 flags.go:33] FLAG: --failure-domains="kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603830   16772 flags.go:33] FLAG: --feature-gates=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.603937   16772 flags.go:33] FLAG: --hard-pod-affinity-symmetric-weight="1"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604036   16772 flags.go:33] FLAG: --help="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604132   16772 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604232   16772 flags.go:33] FLAG: --kube-api-burst="100"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604333   16772 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604440   16772 flags.go:33] FLAG: --kube-api-qps="50"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604541   16772 flags.go:33] FLAG: --kubeconfig=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604665   16772 flags.go:33] FLAG: --leader-elect="true"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604770   16772 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.604915   16772 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605026   16772 flags.go:33] FLAG: --leader-elect-resource-lock="endpoints"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605120   16772 flags.go:33] FLAG: --leader-elect-retry-period="2s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605212   16772 flags.go:33] FLAG: --lock-object-name="kube-scheduler"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605311   16772 flags.go:33] FLAG: --lock-object-namespace="kube-system"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605402   16772 flags.go:33] FLAG: --log-backtrace-at=":0"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605506   16772 flags.go:33] FLAG: --log-dir=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605599   16772 flags.go:33] FLAG: --log-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605690   16772 flags.go:33] FLAG: --log-flush-frequency="5s"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605861   16772 flags.go:33] FLAG: --logtostderr="true"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.605956   16772 flags.go:33] FLAG: --master=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606047   16772 flags.go:33] FLAG: --policy-config-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606137   16772 flags.go:33] FLAG: --policy-configmap=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606244   16772 flags.go:33] FLAG: --policy-configmap-namespace="kube-system"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606343   16772 flags.go:33] FLAG: --port="10251"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606436   16772 flags.go:33] FLAG: --profiling="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606538   16772 flags.go:33] FLAG: --requestheader-allowed-names="[]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606649   16772 flags.go:33] FLAG: --requestheader-client-ca-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606745   16772 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606844   16772 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.606938   16772 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607033   16772 flags.go:33] FLAG: --scheduler-name="default-scheduler"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607125   16772 flags.go:33] FLAG: --secure-port="10259"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607216   16772 flags.go:33] FLAG: --skip-headers="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607307   16772 flags.go:33] FLAG: --stderrthreshold="2"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607405   16772 flags.go:33] FLAG: --tls-cert-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607496   16772 flags.go:33] FLAG: --tls-cipher-suites="[]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607588   16772 flags.go:33] FLAG: --tls-min-version=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607685   16772 flags.go:33] FLAG: --tls-private-key-file=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607777   16772 flags.go:33] FLAG: --tls-sni-cert-key="[]"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607875   16772 flags.go:33] FLAG: --use-legacy-policy-config="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.607971   16772 flags.go:33] FLAG: --v="2"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.608067   16772 flags.go:33] FLAG: --version="false"
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.608194   16772 flags.go:33] FLAG: --vmodule=""
Dec 29 20:28:53 k8s-server-1 kube-scheduler[16772]: I1229 20:28:53.608309   16772 flags.go:33] FLAG: --write-config-to=""
Dec 29 20:28:54 k8s-server-1 kube-scheduler[16772]: I1229 20:28:54.251100   16772 serving.go:318] Generated self-signed cert in-memory
Dec 29 20:28:54 k8s-server-1 kube-scheduler[16772]: no kind "KubeSchedulerConfiguration" is registered for version "componentconfig/v1alpha1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:29"
Dec 29 20:28:54 k8s-server-1 systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 20:28:54 k8s-server-1 systemd[1]: kube-scheduler.service: Failed with result 'exit-code'.
`

**Comment by liggitt** [comment]
See the 1.13 release notes (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#urgent-upgrade-notes):

> kube-scheduler dropped support for configuration files with apiVersion componentconfig/v1alpha1. Ensure kube-scheduler is configured using command-line flags or a configuration file with apiVersion kubescheduler.config.k8s.io/v1alpha1 before upgrading to 1.13.

 and the message printed when starting the 1.12 scheduler with that file:

https://github.com/kubernetes/kubernetes/blob/207cf133e1ab4c9324ffbae610d6d2fe3b7d6e74/cmd/kube-scheduler/app/options/configfile.go#L66-L68

**Comment by Sakib37** [comment]
@liggitt  It worked. :+1:

**Comment by davidstack** [comment]
@Sakib37 i use this config,but  kube-scheduler start failed with this error "invalid configuration: no configuration has been provided",is there anything wrong with my config ?thanks

`apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
disablePreemption: true
leaderElection:
  leaderElect: true`

**Comment by MutedExclamation** [comment]
@davidstack I'm facing the same issue, got any luck on that?

@liggitt Has anything changed since this issue has been closed?
