### ISSUE TITLE
There are NodeConformance tests that may be eligible for promotion to Conformance

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#66875]
/kind cleanup
/area conformance
/area test
/sig node
/sig testing
/sig architecture

/assign @mgdevstack 
/assign @mkurylec 

We have a number of tests that only have the `[NodeConformance]` tag that may make sense as `[Conformance]` tests, we should identify whether these tests cases meet (or could meet) the [requirements to be promoted to conformance](https://github.com/kubernetes/community/blob/master/contributors/devel/conformance-tests.md#conformance-test-requirements). We should open PR's to promote these if so.

I would advise starting with the test/common cases

```
spiffxp@spiffxp-macbookpro:kubernetes (master %)$ sift "[^e]It\(.*NodeConformance" test
test/e2e_node/volume_manager_test.go:			It("should remove the volume from the node [NodeConformance]", func() {
test/e2e_node/runtime_conformance_test.go:				It(testCase.description+" [Conformance][NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should run the container with uid 65534 [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should run the container with uid 0 [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should run the container with readonly rootfs when readOnlyRootFilesystem=true [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should run the container with writable rootfs when readOnlyRootFilesystem=false [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should allow privilege escalation when not explicitly set and uid != 0 [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should not allow privilege escalation when false [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should allow privilege escalation when true [NodeConformance]", func() {
test/e2e_node/security_context_test.go:		It("should run the container as unprivileged when false [NodeConformance]", func() {
test/e2e_node/kubelet_test.go:		It("should have an error terminated reason [NodeConformance]", func() {
test/e2e_node/kubelet_test.go:		It("should be possible to delete [NodeConformance]", func() {
test/e2e_node/kubelet_test.go:		It("it should write entries to /etc/hosts [NodeConformance]", func() {
test/e2e_node/pods_container_manager_test.go:			It("Top level QoS containers should have been created [NodeConformance]", func() {
test/e2e/common/configmap_volume.go:	It("binary data should be reflected in volume [NodeConformance]", func() {
test/e2e/common/projected.go:	It("should be able to mount in a volume regardless of a different secret existing with same name in different namespace [NodeConformance]", func() {
test/e2e/common/secrets_volume.go:	It("should be able to mount in a volume regardless of a different secret existing with same name in different namespace [NodeConformance]", func() {
test/e2e/common/pods.go:	It("should support remote command execution over websockets [NodeConformance]", func() {
test/e2e/common/pods.go:	It("should support retrieving logs from the container over websockets [NodeConformance]", func() {
test/e2e/common/pods.go:	It("should have their auto-restart back-off timer reset on image update [Slow][NodeConformance]", func() {
test/e2e/common/pods.go:	It("should cap back-off at MaxContainerBackOff [Slow][NodeConformance]", func() {
test/e2e/common/host_path.go:	It("should support r/w [NodeConformance]", func() {
test/e2e/common/host_path.go:	It("should support subPath [NodeConformance]", func() {
```

**Comment by mkurylec** [comment]
regarding this testcase: [sig-storage] HostPath should support r/w [NodeConformance]:
It uses hostPath and privileged=true, to read/write from /tmp folder. Which would you suggest is the best orientation to overcome the privilege mode setting and allow its promotion? @msau42

**Comment by mkurylec** [comment]
Regarding [this testcase](https://github.com/kubernetes/kubernetes/blob/6bea053ee7e005230059e00c701ff349b296a459/test/e2e_node/pods_container_manager_test.go#L156),  the suite runs the test only if the kubelet configuration was required to have the QOS (cgroups-per-qos) enabled. This configuration for the kubelet is selected at the time the cluster is set up. 
Looking for where this might be configured found:
- [ci-kubernetes-node-kubelet-conformance](https://github.com/kubernetes/test-infra/blob/83dd9d04b9c9946b3bd03040eb9633e7dc52a4f9/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L161) where is set to true. For other settings it is also configured to true.
- [ci-docker-node-conformance configuration](https://github.com/kubernetes/test-infra/blob/83dd9d04b9c9946b3bd03040eb9633e7dc52a4f9/jobs/config.json#L37) where is set to true.
-  BUT also found [the configuration for containerized kubelets](https://github.com/kubernetes/test-infra/blob/master/docs/tests/node-e2e-ci.md#containerized-kubelet) where it is mentioned that the flag is no longer available.

Questions:
- would it be ok to promote this test to be conformance, even it can be skipped based on configuration of the cluster? And not supported in the containerized kubelet?

**Comment by spiffxp** [comment]
I would consider cgroups to be an implementation detail that Conformance shouldn't be verifying

**Comment by msau42** [comment]
> regarding this testcase: [sig-storage] HostPath should support r/w [NodeConformance]:
It uses hostPath and privileged=true, to read/write from /tmp folder. Which would you suggest is the best orientation to overcome the privilege mode setting and allow its promotion? Michelle Au

If my understanding is correct, on some platforms, writing to /tmp requires privileged.  I don't see a way to to remove that requirement.

**Comment by spiffxp** [comment]
>If my understanding is correct, on some platforms, writing to /tmp requires privileged. I don't see a way to to remove that requirement.

Yeah writing to host doesn't seem like a thing we can expect of conformance tests.  I wonder if it makes sense to tag this test with something to denote the requirement, ie: I see some tests in test/e2e_node use `[NodeFeature:HostAccess]`

**Comment by bgrant0607** [comment]
@msau42 That's /tmp on the host or in the container filesystem?

**Comment by spiffxp** [comment]
ping @mgdevstack what else remains to be done before we close this out?

I am guessing that we want to close https://github.com/kubernetes/kubernetes/issues/67607, is there anything beyond that?

**Comment by mgdevstack** [comment]
Once tests under #67607 and #68123 are promoted we are good to close this issue.

Short update for reference-
- None of [NodeConformance] tests from "test/e2e_node" seems eligible for [Conformance] promotion at this moment due to node level dependencies.
- Remaining [NodeConformance] tests from "test/e2e" has following status -

Waiting for #67607 to be closed and then below tests would be promoted to Conformance
```
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image from docker hub [NodeConformance]
[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull image from gcr.io [NodeConformance]
[k8s.io] Container Runtime blackbox test when running a container with a new image should not be able to pull from private registry without secret [NodeConformance]
[k8s.io] Container Runtime blackbox test when running a container with a new image should not be able to pull image from invalid registry [NodeConformance]
[k8s.io] Container Runtime blackbox test when running a container with a new image should not be able to pull non-existing image from gcr.io [NodeConformance]
[k8s.io] Container Runtime blackbox test when starting a container that exits should report termination message as empty when pod succeeds and TerminationMessagePolicy FallbackToLogOnError is set [NodeConformance]
[k8s.io] Container Runtime blackbox test when starting a container that exits should report termination message from file when pod succeeds and TerminationMessagePolicy FallbackToLogOnError is set [NodeConformance]
[k8s.io] Container Runtime blackbox test when starting a container that exits should report termination message from log output if TerminationMessagePolicy FallbackToLogOnError is set [NodeConformance]
[k8s.io] Container Runtime blackbox test when starting a container that exits should report termination message if TerminationMessagePath is set [NodeConformance]
[k8s.io] Container Runtime blackbox test when starting a container that exits should report termination message if TerminationMessagePath is set as non-root user and at a non-default path [NodeConformance]
```

Needs to be Promoted #68123
```
[k8s.io] Security Context When creating a container with runAsUser should run the container with uid 0 [NodeConformance]
[k8s.io] Security Context When creating a container with runAsUser should run the container with uid 65534 [NodeConformance]
[k8s.io] Security Context When creating a pod with privileged should run the container as unprivileged when false [NodeConformance]
[k8s.io] Security Context When creating a pod with readOnlyRootFilesystem should run the container with readonly rootfs when readOnlyRootFilesystem=true [NodeConformance]
[k8s.io] Security Context When creating a pod with readOnlyRootFilesystem should run the container with writable rootfs when readOnlyRootFilesystem=false [NodeConformance]
[k8s.io] Security Context when creating containers with AllowPrivilegeEscalation should allow privilege escalation when not explicitly set and uid != 0 [NodeConformance]
[k8s.io] Security Context when creating containers with AllowPrivilegeEscalation should allow privilege escalation when true [NodeConformance]
[k8s.io] Security Context when creating containers with AllowPrivilegeEscalation should not allow privilege escalation when false [NodeConformance]
```

Can not be promoted to Conformance as //Slow by design
```
[k8s.io] Pods should cap back-off at MaxContainerBackOff [Slow][NodeConformance]
[k8s.io] Pods should have their auto-restart back-off timer reset on image update [Slow][NodeConformance]
```

Can not be promoted due to Node level dependency
```
[sig-storage] HostPath should support r/w [NodeConformance]
[sig-storage] HostPath should support subPath [NodeConformance]
```
