### ISSUE TITLE
Unable to SSH to worker nodes when created using EKS

### ISSUE THREAD

**Issue by VinayVanama** [kubernetes/kubernetes#66904]
I have followed the AWS EKS documentation and created a cluster and attached worker nodes to that. I have launched a guestbook application and I can scale the pods and everything works fine. But I'm unable to SSH to the worker node using my key file. My Cluster is in Public network as of now.

**Comment by neolit123** [comment]
@VinayVanama please provide log outputs that outline the issue your are having better.
/sig aws
