### ISSUE TITLE
the meaning that flags of command 'kubectl run/create/apply' add '--force' and '--grace-period'

### ISSUE THREAD

**Issue by volume-ji** [kubernetes/kubernetes#66909]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
1. since kubernetes v1.11.1, kubectl command about 'kubectl run/apply/create' added two flags that is '--force' and '--grace-period', which are not exist in kubernetes v1.10.x.
2. I used ‘kubectl run busybox --image=busybox --grace-period=10 ’ to create a deployment busybox, the filed 'terminationGracePeriodSeconds' of corresponding podeSpec is still 30s, '--grace-period' not work.
3. actually, I want to know the meaning of the command 'kubectl run busybox --image=busybox --grace-period=10 --force=true'. suppose that ‘terminationGracePeriodSeconds’ stores value of flag '--grace-period', what does store the value of flag '--force'. I know these two flags are used to force to delete resource of k8s. If I use the two flags, will the corresponding resources be forced to delete ? It seemed not that.

**What you expected to happen**:
May be I  want to get the  manifest of pod when I use "--force=true --grace-period=0". and I set the flags, shoud it be forced to delete with no grace termination？
**How to reproduce it (as minimally and precisely as possible)**:
kubectl run busybox --image=busybox --grace-period=10 --force=true

**Anything else we need to know?**:
None
**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 4.2.0-27-generic
- Install tools: None
- Others: None

/sig cli

**Comment by xiangpengzhao** [comment]
cc @kubernetes/sig-cli-bugs
