### ISSUE TITLE
Broken link in Kubernetes 1.11 blog post

### ISSUE THREAD

**Issue by scottslowe** [kubernetes/kubernetes#66944]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I visited the Kubernetes 1.11 release blog post and clicked on the link to the article on resizing persistent volumes. The server returned a 404.

**What you expected to happen**:
I expected to navigate to the article on resizing persistent volumes in Kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:
Visit the release announcement blog post (https://kubernetes.io/blog/2018/06/27/kubernetes-1.11-release-announcement/), scroll down to the "4 Day Features Blog Series" section, and click on the link to the article on resizing persistent volumes.

**Anything else we need to know?**:
The link currently points to: https://kubernetes.io/blog/2018/07/11/resizing-persistent-volumes-using-kubernetes/
The correct link is: https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

@kubernetes/sig-docs-bugs

**Comment by charrywanganthony** [comment]
It should be reported to kubernetes/website, but doesn't matter.
