### ISSUE TITLE
stub device plugin based e2e test

### ISSUE THREAD

**Issue by jiayingz** [kubernetes/kubernetes#66952]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

**What you expected to happen**:
We need to have a cluster level stub device plugin based e2e test, which has been long pending task slip through several cycles. After we have that, we can configure it to run in different environments, like scale, soak, upgrade, and downgrade.

For simplicity, we can create a stub_device_plugin directory under test/images/ with a simple stub device plugin implementation in a .go file, and simple Makefile, Dockerfile, etc. The stub device plugin can start with defined behavior and just provide simple container runtime setting during Allocate call. For reference, pkg/kubelet/util/pluginwatcher/example_plugin.go is an example plugin we have used in pluginwatcher test. We can have a similar one for stub device plugin that implements the device plugin API.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vikaschoudhary16** [comment]
As per slack discussion with @ScorpioCPH, i will be working on this.

/assign
