### ISSUE TITLE
Nodes are not able to communicate with apiserver vip when vip is used as externalIP with ipvs

### ISSUE THREAD

**Issue by dawidmalina** [kubernetes/kubernetes#66966]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We have keepalived deployed on kubernetes master nodes together with haproxy which loadbalance to all apiservers. The same vip is used as externalIP for some other services like kube dashboard to expose this services out of kubernetes cluster.

It works perfectly fine with kube-proxy with iptables mode but when kube-proxy is reconfigured to use ipvs mode we are not able to connect to this vip.

The problem is that in this case vip is assigned to kube-ipvs0 interface and nodes are not able to commiunicate with api and are in NotReady state.

The only think i have in mind to mitigate this problem is to not mixed vip and externalIP with services but maybe we can do this differently.

**What you expected to happen**:
Should work quite same as kube-proxy with iptables mode

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiaoxubeii** [comment]
I think it cannot work in kube-proxy ipvs because kube-ipvs0 is a dummy interface, so it cannot be accessed from outside without masq. I think one possible approach is to use NodePort to expose your svc.

**Comment by dawidmalina** [comment]
Thx i will try to not use externalIP within cluster. Thank for help
