### ISSUE TITLE
Write a reflector benchmark

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#6697]
Throw load at etcd, limit it to a few cores, and open up some reflectors (pod+node hostname would mimic kubelet, pod with/without hostname would be scheduler). Measure latency of time a change hits etcd to when it shows up in the reflector. 

It should be capable of catching https://github.com/GoogleCloudPlatform/kubernetes/issues/6059 as well as cases where the field/label matching logic has suddenly regressed. 

Would be cool if it compared the overhead of a reflector with the raw etcd watch latency too, 2 benchmarks would achieve that, one with the raw etcd helper and another with the reflector. 

@lavalamp thoughts?

**Comment by derekwaynecarr** [comment]
I think this would be useful.

**Comment by wojtek-t** [comment]
cc @fgrzadkowski 

+10
I think it would be very useful (also I think that comparing the raw etcd with the whole reflector would be very useful).

Also note that we're going to setup continuous e2e tests on Jenkins to test scalability - see #6753

**Comment by lavalamp** [comment]
One of the scheduler benchmarks I added to the integration test suite is close to being this.

**Comment by timothysc** [comment]
Generally useful idea, but no progress in > year so I'm closing.  Please feel free to reopen if you think it's worth it.
