### ISSUE TITLE
kubeadm: Cannot use PodSecurityPolicy admission plugin when using self-hosted

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubernetes#66985]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When using `PodSecurityPolicy ` and `SelfHosting` together, the init process gets stuck on creating the mirror pods and never reaches the point of creating the self-hosted pods:
```
E0804 13:32:00.162451    1683 kubelet.go:1598] Failed creating a mirror pod for "kube-controller-manager-master-1_kube-system(371a6d70692e0437cf9024747fb3e6bd)": pods "kube-controller-manager-master-1" is forbidden: no providers available to validate pod request
E0804 13:32:00.169378    1683 kubelet.go:1598] Failed creating a mirror pod for "kube-scheduler-master-1_kube-system(9be5cfe219edcdecfb0f32cc1bbe7579)": pods "kube-scheduler-master-1" is forbidden: no providers available to validate pod request
E0804 13:32:00.176229    1683 kubelet.go:1598] Failed creating a mirror pod for "kube-apiserver-master-1_kube-system(161105bbdac63f4ffd51c371b7e74baf)": pods "kube-apiserver-master-1" is forbidden: no providers available to validate pod request
```
**What you expected to happen**:
To have an option to specify a PSP, or a sane default for the `kube-system` namespace that will allow the self-hosted control plane to come up (and the mirror pods without self-hosted).

**How to reproduce it (as minimally and precisely as possible)**:
`kubeadm init --config kubeadm.yaml`

 kubeadm.yaml:
```yaml
kind: MasterConfiguration
clusterName: example
bootstrapTokens:
- token: abcdef.0123456789abcdef
  ttl: 0s
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
unifiedControlPlaneImage: gcr.io/google_containers/hyperkube:v1.11.1
apiServerExtraArgs:
  enable-admission-plugins: PodSecurityPolicy
featureGates:
  SelfHosting: true
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig cluster-lifecycle

**Comment by timothysc** [comment]
Closing here.  

If desired, please reopen here: https://github.com/kubernetes/kubeadm
