### ISSUE TITLE
Support LIST starting from a key

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#66981]
/kind feature
/sig api-machinery

@lavalamp @deads2k do you think this feature request needs a KEP, or can we view it as completing https://github.com/kubernetes/community/pull/896?

## Motivation

Kubernetes supports API chunking on LIST requests. It allows a large LIST response to be broken into smaller, consistent partial responses. Consistency here means that all the partial responses is for a single resource version. However, apiservers instruct etcd to delete old versions every [5 minutes](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go#L31), so if a client cannot complete all the chunks in 5 minutes, the late requests will fail with “resource version too old” error.

As listed in the API chunking [proposal](https://github.com/kubernetes/community/pull/896/files), some clients care more about getting a lexically complete list than getting a consistent list. That is, when a “resource version too old” error happens, the client wants to continue the list from the next key (in kubernetes case, keys are lexically ordered), with the latest resource version. Such clients include `kubectl get` and migration style commands (e.g., those rewrite data in etcd from json to proto; or convert the Kubernetes API version of the data in etcd).

## Proposal
Adding a `BeginningName` and a `BeginningNamespace` to the ListOptions. They can be used with or without chunking.

```golang
ListOptions {
	…
	BeginningNamespace string
	BeginningName string
}
```

Let's walk through a few cases:
```
1. Path: /api/v1/pods

ListOptions {
	// Required, i.e., cannot be “”.
	BeginningNamespace: “staging”,
	// Required
	BeginningName: “a”,
}

Results: apiserver starts listing pods whose key in etcd is lexically greater than “staging/a”


2. Path: /api/v1/namespaces/{namespace}/pods

ListOptions {
	// Required, must match the namespace in the path.
	BeginningNamespace: “staging”,
	// Required
	BeginningName: “a”,
}

Results: apiserver starts listing pods whose key in etcd is prefixed with “staging/” and lexically greater than “staging/a”.

3. Path: /api/v1/nodes (nodes are cluster-scoped):

ListOptions {
	// Must be “”
	BeginningNamespace: “”,
	// Required
	BeginningName: “a”,
}

Results: apiserver starts listing nodes whose key in etcd is lexically greater than “a”

4. Path: N/A

ListOptions: {
	Limit: 50,
	Continue: “some_value”, 
	// Must be empty
	BeginningNamespace: “”,
	// Must be empty
	BeginningName: “”,
}

Results: apiserver behaves the same as it currently does, sending back results based on the continue token.

5. Path: N/A

ListOptions: {
	Limit: 50
	Continue: “”, 
	BeginningNamespace: “staging”,
	BeginningName: “a”,
}

Results: apiserver returns no more than 50 elements whose etcd key is lexically greater than “staging/a”. 
If there are more elements, apiserver sends back a continue token. To continue the consistent chunking, the client should continue with

ListOptions: {
	Limit: 50
	Continue: <token sent back by the apiserver>, 
	// Must be empty	
	BeginningNamespace: “”,
	// Must be empty
	BeginningName: “”,
}
```

## Security implications
Currently Kubernetes supports two kind of LIST access control:
1. Giving a user permissions to list a resource in all namespaces
2. Giving a user permissions to list a resource in specific namespaces

For 1, the user already has the highest possible permission.
For 2, because “BeginningNamespace” must match the namespace in path, the “list from a key” feature doesn’t break today’s security model.

**Comment by caesarxuchao** [comment]
cc @cheftako @jpbetz this is the feature we discussed for storage encoded version migration.

**Comment by liggitt** [comment]
rather than expose the startingName/startingNamespace options, would it make more sense to optionally augment the returned 410 error with a continue token the client can use to continue traversing without respect to resourceVersion? I like that for a few reasons:

* keeps the existing list/continue flow as-is
* signals in the error whether the server supports continuing from an arbitrary point (rather than sending new ListOptions we don't know if the server supports)
* avoids growing the surface area of ListOptions in ways that constrain storage implementations

**Comment by caesarxuchao** [comment]
Returning continue token with 410 error sounds good. The token can be `hash(next key, resourceVersion=0)`. It's sufficient for the `kubectl get` and migration use cases. @lavalamp wdyt?

**Comment by lavalamp** [comment]
>>in kubernetes case, keys are lexically ordered

>is that actually a guarantee of our API, or just an artifact of the current etcd impl? ...

It is definitely the latter, and we'd like to eventually store by UID (with name lookup supported via an index). It happens that @caesarxuchao's use case doesn't actually care what they're sorted by as long as it can start somewhere in the middle, but that's hard to express in an API.

So for that reason, I think issuing a new continue token when an old one hits an out-of-window error is a good idea.

**Comment by lavalamp** [comment]
Additional thought on the API proposed:

This is trying to encode a database query. It's not a standard or extensible approach (e.g. we wouldn't want to see 100 different queries done in the api like this). I also don't think we're ready to tackle a general query system. So, for these reasons, I'm not in favor of this API.

**Comment by caesarxuchao** [comment]
Thanks for the inputs. Issuing a continue token that doesn't care about resourceVersion is a small code change. I don't think that requires a KEP. I'll send a PR.

**Comment by lavalamp** [comment]
I'm not sure that's an accurate summary but we can work it out in the PR
either way. :)

**Comment by smarterclayton** [comment]
I'm ok with this.
