### ISSUE TITLE
kubelet fails to run on new install RHEL7

### ISSUE THREAD

**Issue by gzcwnk** [kubernetes/kubernetes#66999]
**Is this a BUG REPORT** yes

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

kubelet will not run while following docs,

https://kubernetes.io/docs/setup/independent/install-kubeadm/

**What you expected to happen**:

kubelet runs as per install instructions.

**How to reproduce it (as minimally and precisely as possible)**:

Following doc on 3 machines gives the same result, kubelet will not start on any of them.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
VMware instances
- OS (e.g. from /etc/os-release):
RHEL7.5
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gzcwnk** [comment]
[root@ipa-rhel7-local-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by gzcwnk** [comment]
[root@ipa-rhel7-local-01 ~]# more /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@ipa-rhel7-local-01 ~]# uname -r
3.10.0-862.9.1.el7.x86_64
[root@ipa-rhel7-local-01 ~]#

**Comment by gzcwnk** [comment]
[root@ipa-rhel7-local-01 ~]# rpm -q docker
docker-1.13.1-68.gitdded712.el7.x86_64
[root@ipa-rhel7-local-01 ~]# rpm -q kubectl
kubectl-1.11.1-0.x86_64
[root@ipa-rhel7-local-01 ~]# rpm -q kubeadm
kubeadm-1.11.1-0.x86_64
[root@ipa-rhel7-local-01 ~]# rpm -q kubelet
kubelet-1.11.1-0.x86_64
[root@ipa-rhel7-local-01 ~]#

**Comment by gzcwnk** [comment]
in /var/log/messages,

"Aug  6 15:24:32 ipa-rhel7-local-01 systemd: Started kubelet: The Kubernetes Node Agent.
Aug  6 15:24:32 ipa-rhel7-local-01 systemd: Starting kubelet: The Kubernetes Node Agent...
Aug  6 15:24:32 ipa-rhel7-local-01 kubelet: F0806 15:24:32.493160    5439 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug  6 15:24:32 ipa-rhel7-local-01 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Aug  6 15:24:32 ipa-rhel7-local-01 systemd: Unit kubelet.service entered failed state.
Aug  6 15:24:32 ipa-rhel7-local-01 systemd: kubelet.service failed.
[root@ipa-rhel7-local-01 log]# 
"

**Comment by neolit123** [comment]
@gzcwnk 
are you calling `kubeadm init` ?

**Comment by gzcwnk** [comment]
hmmm, no as I get this error.

**Comment by neolit123** [comment]
`kubeadm init` should create `/var/lib/kubelet/config.yaml`.

**Comment by gzcwnk** [comment]
thanks, seems Ok but onto missing kernel modules  on the nodes  :(
