### ISSUE TITLE
Clean up parameters in e2e tests

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#6699]
#5138 now uses the gce_zone parameter as the zone for AWS also.

We should figure out which parameters have genuine meaning across clouds and can be shared, and rename them (gce_zone -> cloud_zone or just zone)  This will likely break the scripts etc that set these flags though, so we have to be careful.

**Comment by lavalamp** [comment]
Yeah, it definitely feels pretty weird to use gce_zone both places.
