### ISSUE TITLE
Godeps and vendor owners are not known

### ISSUE THREAD

**Issue by jiatongw** [kubernetes/kubernetes#67001]
I have a pull request waited for Godeps and vendor owners to approve. But the approvers in `Godeps/OWNERS` and `vendor/OWNERS` are listed as below:

``` 
approvers:
- dep-approvers
```
I can not just @dep-approvers . So does anyone know how to contact them?

**Comment by dims** [comment]
check OWNERS_ALIASES - easy to search using the search tool - https://cs.k8s.io/?q=dep-approvers&i=nope&files=&repos=kubernetes

/close
