### ISSUE TITLE
What’s the mean? From Istio 1.0 sample, Init:Blocked , I install in stand-alone VM, CentOs 7.5

### ISSUE THREAD

**Issue by yangqinjiang** [kubernetes/kubernetes#67005]
# What’s the mean? From Istio 1.0 sample, Init:Blocked , I install in stand-alone VM, CentOs 7.5

![image](https://user-images.githubusercontent.com/1914373/43701279-28e93098-9988-11e8-85bf-78fc4c2454c4.png)

**Comment by neolit123** [comment]
@yangqinjiang 
your report is incomplete. please fill the template and re-open:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

/sig node
/close
