### ISSUE TITLE
If I hit an API that doesn't exist, the error message is not helpful.

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#6703]
Repro:
- Start a cluster v0.14.1
- Run the following command against this link (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/v1beta3/mysql.yaml) - 

```
kubectl create -f mysql.yml
```

Actual:
- See the following error message:

```
F0410 14:32:53.405437   21329 create.go:50] Client error processing command: replicationcontrollers "" not found
```

Expected:
- Error message explaining that v1beta3 API is not yet supported.

**Comment by lavalamp** [comment]
Yeah, that message is unfortunate. But v1beta3 is supported. I thought it was on by default, too, now.

Do you already have a mysql rep. controller? I know at one point we were misreporting a "already exists" as a "not found" error.

**Comment by aronchick** [comment]
No, I have nothing - this was a raw attempt to try to create the
wordpress example.

**Comment by nikinath** [comment]
I think this issue can be closed now.

When I run `sudo cluster/kubectl.sh create -f mysql.yaml` with apiVersion as `v1beta3` (which is deprecated), I get:

```
Error from server (BadRequest): error when creating "mysql.yaml": Pod in version "v1beta3" cannot be handled as a Pod: no kind "Pod" is registered for version "v1beta3"
```

This is a helpful error message. However, if any improvement is needed, I'd like to work on it!

Ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/error.go#L47
