### ISSUE TITLE
Scope LibreSSL check to cluster/ scripts that require easyrsa

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#67044]
Apparently local-up-cluster worked fine with LibreSSL, ref: https://github.com/kubernetes/kubernetes/pull/66690#issuecomment-410863925

I can't get to this now but I'm going to forget if this is left in a PR comment

/assign
/kind bug
/sig cluster-lifecycle
FYI @liggitt

**Comment by liggitt** [comment]
opened #67046
