### ISSUE TITLE
sample-apiserver API resource types don't have protobuf definitions, requests respond with errNotMarshalable

### ISSUE THREAD

**Issue by tristanburgess** [kubernetes/kubernetes#67047]
/kind bug

**What happened**:
Sent a request for an aggregated resource (sample-api wardle/flunders). Response was a 406 status code and an error message saying the response could not be given.

**What you expected to happen**:
A 200 status response containing marshaled protobuf data for the sample-apiserver API resource types.

**How to reproduce it (as minimally and precisely as possible)**:

    1. Set up sample-apiserver.
    2. `curl -k -v -H "Accept: application/vnd.kubernetes.protobuf" -H "Authorization: Bearer " http://localhost:8080/apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders`
    Response:
```
< HTTP/1.1 406 Not Acceptable
< Content-Length: 184
< Content-Type: application/vnd.kubernetes.protobuf
< Date: Mon, 06 Aug 2018 23:52:22 GMT
< 
k8s


v1Status�

* Connection #0 to host localhost left intact
NotAcceptable0�"object *v1alpha1.FlunderList does not implement the protobuf marshalling interface and cannot be encoded to a protobuf message"

```

**Anything else we need to know?**: The `406 Not Acceptable` status code depends on the fix for #50342. Without this fix, the response status code will be `200 OK`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-alpha.1.158+1ced858ddde1bb
- Cloud provider or hardware configuration: hack/local-up-cluster.sh (minikube)
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS (64 Bit)
- Kernel (e.g. `uname -a`): Linux 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by tristanburgess** [comment]
I will take this one as I already have a fix. I can't be assigned because I'm not a project member.

**Comment by tristanburgess** [comment]
Proof of new behavior:
```
curl -k -v  -H "Accept: application/vnd.kubernetes.protobuf" -H "Authorization: Bearer " http://localhost:8080/apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders/my-first-flunder --output -
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders/my-first-flunder HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: application/vnd.kubernetes.protobuf
> Authorization: Bearer 
> 
< HTTP/1.1 200 OK
< Content-Length: 236
< Content-Type: application/vnd.kubernetes.protobuf
< Date: Tue, 07 Aug 2018 00:08:40 GMT
< 
k8s
!
wardle.k8s.io/v1alpha1Flunder�
�
my-first-flunderdefault"I/apis/wardle.k8s.io/v1alpha1/namespaces/default/flunders/my-first-flunder*$059578c8-99d6-11e8-acdf-0242ac11000322�ƣ�Z

sample-labeltruez
```

**Comment by ialidzhikov** [comment]
I thinks this issue needs to reopened because sample-apiserver still does not support protobuf.
Can we reopen this issue instead of opening a new one?

Could you please put `/reopen`?
