### ISSUE TITLE
RHEL7 kubernetes cluster will not run  "notready" 

### ISSUE THREAD

**Issue by gzcwnk** [kubernetes/kubernetes#67043]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Kubernetes cluster will not run

**What you expected to happen**:

Cluster runs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

[root@ipa-rhel7-local-01 kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
[root@ipa-rhel7-local-01 kubernetes]#

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

[root@ipa-rhel7-local-01 kubernetes]# uname -r
3.10.0-862.9.1.el7.x86_64
[root@ipa-rhel7-local-01 kubernetes]# more /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

=====
[root@ipa-rhel7-local-01 kubernetes]# !291
kubectl get nodes
NAME                               STATUS     ROLES     AGE       VERSION
ipa-rhel7-local-01.ods.vuw.ac.nz   NotReady   master    2h        v1.11.1
ipa-rhel7-local-02.ods.vuw.ac.nz   NotReady   <none>    1h        v1.11.1
ipa-rhel7-local-03.ods.vuw.ac.nz   NotReady   <none>    1h        v1.11.1
[root@ipa-rhel7-local-01 kubernetes]# 
=====

from /var/log/messages,

=====
Aug  7 11:37:00 ipa-rhel7-local-01 kubelet: E0807 11:37:00.015507    3110 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Aug  7 11:37:01 ipa-rhel7-local-01 kubelet: W0807 11:37:01.555877    3110 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Aug  7 11:37:01 ipa-rhel7-local-01 kubelet: E0807 11:37:01.555987    3110 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
=====

systemctl status,

=====
[root@ipa-rhel7-local-01 kubernetes]# !299
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2018-08-07 08:59:07 NZST; 2h 49min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 3110 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─3110 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.y...

Aug 07 11:48:26 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: W0807 11:48:26.985344    3110 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 07 11:48:26 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:26.985444    3110 kubelet.go:2110] Container runtime network not ready: NetworkReady=fal...itialized
Aug 07 11:48:31 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:31.029774    3110 summary.go:102] Failed to get system container stats for "/system.slice/kubelet...
Aug 07 11:48:31 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: W0807 11:48:31.986490    3110 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 07 11:48:31 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:31.986584    3110 kubelet.go:2110] Container runtime network not ready: NetworkReady=fal...itialized
Aug 07 11:48:36 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: W0807 11:48:36.987964    3110 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 07 11:48:36 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:36.988061    3110 kubelet.go:2110] Container runtime network not ready: NetworkReady=fal...itialized
Aug 07 11:48:41 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:41.044534    3110 summary.go:102] Failed to get system container stats for "/system.slice/kubelet...
Aug 07 11:48:41 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: W0807 11:48:41.989379    3110 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 07 11:48:41 ipa-rhel7-local-01.ods.vuw.ac.nz kubelet[3110]: E0807 11:48:41.989475    3110 kubelet.go:2110] Container runtime network not ready: NetworkReady=fal...itialized
Hint: Some lines were ellipsized, use -l to show in full.
[root@ipa-rhel7-local-01 kubernetes]# 
======

Need documentation &help please.

**Comment by tanshanshan** [comment]
I think you have config -network-plugin=cni  in kubelet config ,but you have not a network cni plugin 
If you do not need  it , you can remove this option

**Comment by gzcwnk** [comment]
Why would I need it?

**Comment by gzcwnk** [comment]
I had a look in /etc/kubernetes/kubelet.conf and nothing saying cni=

**Comment by tanshanshan** [comment]
use 

> ps -ef | grep kubelet 

the error is not found cni network ,but config cni option in kubelet

**Comment by gzcwnk** [comment]
root@ipa-rhel7-local-01 kubernetes]# ps -ef |grep kubelet
root      3110     1  1 08:59 ?        00:03:41 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni

**Comment by tanshanshan** [comment]
so remove 

> --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni

and restart kubelet

**Comment by gzcwnk** [comment]
Thanks, I seem to have ready after editing /var/lib/kubelet/kubeadm-flags.env
