### ISSUE TITLE
While taint node with NotReady:NoSchedule，pod  cound not be scheduled to the node any more 

### ISSUE THREAD

**Issue by jjtestk8s** [kubernetes/kubernetes#67057]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
https://github.com/kubernetes/kubernetes/issues/63420 
https://github.com/kubernetes/kubernetes/pull/63471
According to #63420 and #63471，
We are now in release 1.9.7，including TaintNodesByCondition=true in the --feature-gates command line flag to the Kubernetes controller manager, such as --feature-gates=TaintBasedEvictions=true,TaintNodesByCondition=true，and taint node（e.g. node01）  with NotReady:NoSchedule ，then pod also can not be scheduled to  node01  even when node01 is healthy.

**What you expected to happen**:

The pod should be scheduled to node01 when it is healthy node and 
not be scheduled to node01 when it is not ready.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.7

**Comment by k82cn** [comment]
>  taint node（e.g. node01） with NotReady:NoSchedule

How did you do that? taint node by kubectl?

**Comment by jjtestk8s** [comment]
Yes，I tried  "kubectl taint nodes node01 node.kubernetes.io/NotReady=:NoSchedule",and also tried "kubectl taint nodes node01 node.kubernetes.io/not-ready=:NoSchedule"
