### ISSUE TITLE
`kubectl port-forward` remains active even after the pod being forwarded to is gone.

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes#67059]
**BUG REPORT**
/kind bug

**What happened**:
`kubectl port-forward` remains active even after the pod being forwarded to is gone.

**What you expected to happen**:
`kubectl port-forward` should exit when the backing pod is gone.

**How to reproduce it (as minimally and precisely as possible)**:
 - `kubectl run bb --image busybox --restart=Never -it --rm` start a pod and connect to it
 - `kubectl port-forward bb 8888:8888` port-forward to the created pod
 - exit from the busy box pod or `kubectl delete pod --now bb`
 - port-forward is still running
 - if you attempt to connect, even after creating a new bb pod to replace the original one, the port-forward fails as it looks up by UID.
```
    E0806 21:35:29.876087   20063 portforward.go:331] an error occurred forwarding 8888 -> 8888: error forwarding port 8888 to pod 3bdbf28f96012a3f944747eaa5c12c1cb9d5779831a5fe0a2350b6bb78f44a39, uid : Error: No such container: 3bdbf28f96012a3f944747eaa5c12c1cb9d5779831a5fe0a2350b6bb78f44a39
```

Look for the text `lost connection to pod` to find some code that I would consider handling the disconnect.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider: IKS & kubeadm-dind-cluster

**Comment by yue9944882** [comment]
IMHO, we don't have a connection management inside these REST connectors (not only for `pod/port-forward`) in server side, so the port-forward connection cannot be canceled unless we run a reconciler to cancel outdated requests in kubelet.

**Comment by MHBauer** [comment]
Where is the connection terminated? Kubectl isn't doing a query on pods after it finds the initial one. Does this indicate a connection being maintained from kubectl all the way through to the kubelet hanging open even if the pod doesn't exist?
Is there documentation somewhere describing what should be going on? The code comments are a bit sparse and the callbacks and interfaces are hard for me to follow.

**Comment by yue9944882** [comment]
> Does this indicate a connection being maintained from kubectl all the way through to the kubelet hanging open even if the pod doesn't exist?

i'm afraid so. we'll proxy a websocket connection kubectl->kubeapiserver->kubelet on port-forward. 

[https://github.com/kubernetes/kubernetes/blob/3c05d926db6ff8d544ec8e1514284889a84bccb1/pkg/registry/core/pod/rest/subresources.go#L191](https://github.com/kubernetes/kubernetes/blob/3c05d926db6ff8d544ec8e1514284889a84bccb1/pkg/registry/core/pod/rest/subresources.go#L191)

**Comment by jbtuck** [comment]
This issue is still reproducible.

**Comment by pramod3009** [comment]
I am not sure if it is kubernetes issue or the user is expected to clear their port forwarding after a respun. Following post on stackoverflow is a temporary solution : https://stackoverflow.com/questions/37288500/how-to-undo-a-kubectl-port-forward/53948474#:~:text=The%20port%20is%20only%20forwarded,port%2Dforward%20command%20is%20running.

**Comment by nicholasyin** [comment]
May I ask if there's still no way to remove a port forwarding, as of today 2022?
