### ISSUE TITLE
Kubernetes not returning endpoints Django Rest-Framework

### ISSUE THREAD

**Issue by keyloguer** [kubernetes/kubernetes#67082]
@kubernetes/sig-docs
Hey guys i have a django rest application and every time that i expose the deployment with service, my minikube doesn't expose the IP, anyone knows how to solved it? I wait 3 hours and my minikube doesn't show any IP.

Pod/container log:

    &lt;django.db.models.fields.related.ForeignKey&gt;
    &lt;django.db.models.fields.TextField&gt;
    &lt;django.db.models.fields.related.ForeignKey&gt;
    Operations to perform:
      Apply all migrations: admin, auth, authtoken, chat, contenttypes, notifications, sessions
    Running migrations:
      No migrations to apply.
    &lt;django.db.models.fields.related.ForeignKey&gt;
    &lt;django.db.models.fields.TextField&gt;
    &lt;django.db.models.fields.related.ForeignKey&gt;
    &lt;django.db.models.fields.related.ForeignKey&gt;
    &lt;django.db.models.fields.TextField&gt;
    &lt;django.db.models.fields.related.ForeignKey&gt;
    Performing system checks...
     System check identified no issues (0 silenced).
    August 06, 2018 - 19:14:37
    Django version 2.0.1, using settings 'chatire.settings'
    Starting development server at http://0.0.0.0:8000/
    Quit the server with CONTROL-C

backend-service:

    apiVersion: v1
    kind: Service
    metadata:
      name: backend-service
    spec:
      type: NodePort
      ports:
        - port: 8000
          nodePort: 30001
      selector:
        service: backend-pod

backend-deployment:

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: backend-deployment
    spec:
      template:
        metadata:
          labels:
           name: backend-pod
        spec:
          containers:
            - name: container-backend
              image: modalgr.azurecr.io/chatbot/backend:v1.1
              ports:
              - containerPort: 8000
              command: ["/bin/sh"]
              args: ["app.sh"]
          restartPolicy: Always
          imagePullSecrets:
          - name: azure-auth

Error log:

    C:\Users\Youssef\Documents\kubernetes>minikube service backend-service | findstr IP
    Waiting, endpoint for service is not ready yet...
    Waiting, endpoint for service is not ready yet...
    Waiting, endpoint for service is not ready yet...
    Waiting, endpoint for service is not ready yet...

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neolit123** [comment]
you should try the support channels like stackoverflow for questions:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

if you feel like this is a minikube bug you can try creating an issue here:
https://github.com/kubernetes/minikube

thanks
/close
