### ISSUE TITLE
Incomplete documentation for DeploymentSpec.selector

### ISSUE THREAD

**Issue by drigz** [kubernetes/kubernetes#67081]
/kind bug
@kubernetes/sig-docs-bugs

**What happened**:

I noticed that most (but not all) of our Deployment YAML definitions include both `spec.selector` and `spec.template.metadata.labels`. These were always the same, and I've had a report that if they differ then the deployment doesn't work. However, one definition was missing `spec.selector`, but it seemed to work.

I looked in [the docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deploymentspec-v1-apps), which say the following for `spec.selector`:

> Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment. **It must match the pod template's labels.**

I found [this comment](https://github.com/kubernetes/kubernetes/issues/28475#issuecomment-264952770), saying:

> You need to have specified either metadata.labels in the pod template or spec.selector (**the one that's missing will be defaulted to the other**) for the Deployment to work (create new pods and label them so they can be partitioned from other pods).

(emphasis mine)

If the comment is correct, this info should be in the docs.

**What you expected to happen**:

Instead of "It must match the pod template's labels", it should say something like:

> If present, it must match the pod template's labels. If omitted, it defaults to match the pod template's labels. If the pod template does not have defined labels, it is an error to omit this field.

**Comment by liggitt** [comment]
That comment is not correct. That defaulting existed in the extensions/v1beta1 version of Deployments, but was removed in the apps/v1 version because it caused problems during update.

/close
