### ISSUE TITLE
Proxy URL not working after upgrade from 1.9.3 to 1.9.8

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kubernetes#67095]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

After running
kubectl proxy --port=8001 --context <context>
this URL stopped working
8001/api/v1/namespaces/mgmt/services/https:m1-kubernetes-dashboard:443/proxy

For reference, this URL
http://localhost:8001/api/v1/namespaces/mgmt/services
shows (among other things)
    {
      "metadata": {
        "name": "m1-kubernetes-dashboard",
        "namespace": "mgmt",
        "selfLink": "/api/v1/namespaces/mgmt/services/m1-kubernetes-dashboard",
        "uid": "c195d6ec-8960-11e8-81b0-06bb5cfd9e24",
        "resourceVersion": "1356",
        "creationTimestamp": "2018-07-17T01:28:49Z",
        "labels": {
          "heritage": "Tiller",
          "kubernetes.io/cluster-service": "true",
          "release": "m1",
          "app": "kubernetes-dashboard",
          "chart": "kubernetes-dashboard-0.6.1"
        }
      },
      "spec": {
        "ports": [
          {
            "protocol": "TCP",
            "port": 443,
            "targetPort": "https"
          }
        ],
        "selector": {
          "app": "kubernetes-dashboard",
          "release": "m1"
        },
        "clusterIP": "<>",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {
          
        }
      }
    },

**What you expected to happen**:
I expected this URL to show the k8s dashboard

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux marcel-XPS-8930 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

/sig api-machinery

**Comment by liggitt** [comment]
what was the response from the proxy url? What is the content of the "m1-kubernetes-dashboard" endpoints object in that namespace?

**Comment by mkornacker** [comment]
This is the response:
Error: 'dial tcp 100.112.169.131:8443: getsockopt: connection timed out'
Trying to reach: 'https://100.112.169.131:8443/'

This is the spec of the same service running in a different cluster (1.9.3):
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "m1-kubernetes-dashboard",
    "namespace": "mgmt",
    "selfLink": "/apis/extensions/v1beta1/namespaces/mgmt/deployments/m1-kubernetes-dashboard",
    "uid": "636eda61-6d8d-11e8-815a-0ee84212285a",
    "resourceVersion": "1626",
    "generation": 1,
    "creationTimestamp": "2018-06-11T15:37:46Z",
    "labels": {
      "app": "kubernetes-dashboard",
      "chart": "kubernetes-dashboard-0.6.1",
      "heritage": "Tiller",
      "kubernetes.io/cluster-service": "true",
      "release": "m1"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "kubernetes-dashboard",
        "kubernetes.io/cluster-service": "true",
        "release": "m1"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "kubernetes-dashboard",
          "kubernetes.io/cluster-service": "true",
          "release": "m1"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "kubernetes-dashboard-certs",
            "secret": {
              "secretName": "m1-kubernetes-dashboard",
              "defaultMode": 420
            }
          },
          {
            "name": "tmp-volume",
            "emptyDir": {}
          }
        ],
        "containers": [
          {
            "name": "kubernetes-dashboard",
            "image": "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3",
            "args": [
              "--auto-generate-certificates"
            ],
            "ports": [
              {
                "name": "https",
                "containerPort": 8443,
                "protocol": "TCP"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "100m",
                "memory": "50Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "50Mi"
              }
            },
            "volumeMounts": [
              {
                "name": "kubernetes-dashboard-certs",
                "mountPath": "/certs"
              },
              {
                "name": "tmp-volume",
                "mountPath": "/tmp"
              }
            ],
            "livenessProbe": {
              "httpGet": {
                "path": "/",
                "port": 8443,
                "scheme": "HTTPS"
              },
              "initialDelaySeconds": 30,
              "timeoutSeconds": 30,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "m1-kubernetes-dashboard",
        "serviceAccount": "m1-kubernetes-dashboard",
        "securityContext": {},
        "schedulerName": "default-scheduler",
        "tolerations": [
          {
            "key": "dedicated",
            "operator": "Equal",
            "value": "mgmt",
            "effect": "NoSchedule"
          }
        ]
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 0
      }
    }
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-06-11T15:37:46Z",
        "lastTransitionTime": "2018-06-11T15:37:46Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}

**Comment by mkornacker** [comment]
By the way, this url works and returns the running services:
http://localhost:8001/api/v1/namespaces/mgmt/services
