### ISSUE TITLE
Open file descriptor usage increases steadily over time for kube-apiserver and kubelet with Heketi/glusterfs

### ISSUE THREAD

**Issue by thanethomson** [kubernetes/kubernetes#67119]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`kube-apiserver` and `kubelet` seem to continuously open new connections without closing them. When restarting these components, open file descriptors drop to low levels again (roughly 80 for `kube-apiserver` and `kubelet`), but then continue to climb steadily as before. During this time, only a handful of services were deployed/removed.

See [graphs over here](https://gist.github.com/thanethomson/d59a58d5a18ef84ceee55e0d38ad8b22).

When we restart `kubelet` only, the number of open file descriptors for both `kubelet` and `kube-apiserver` drop dramatically, implying that `kubelet` is somehow involved in the issue.

As described below, however, we're running [Heketi](https://github.com/heketi/heketi/) with glusterfs for our persistent storage. It appears as though the number of open file descriptors for the `kubelet` instances on the glusterfs hosts increase over time, whereas the number of open file descriptors for `kubelet` on the non-glusterfs hosts does not.

**What you expected to happen**:
I would expect the number of open file descriptors from these processes to remain relatively stable over time, as per the other K8s components (e.g. `kube-proxy`).

**How to reproduce it (as minimally and precisely as possible)**:
We built a 3-VM cluster, following [Kelsey Hightower's "Kubernetes the Hard Way"](https://github.com/kelseyhightower/kubernetes-the-hard-way). The primary differences between his setup and ours:

1. We're running on Azure
2. Each VM acts as both master and worker node (i.e. we have `kube-apiserver` and `kubelet` running on the same servers).
3. We configured flannel for direct access to etcd so it can manage our pod subnets.
4. We're running [Heketi](https://github.com/heketi/heketi/) in our cluster with Host 0 and Host 1 each having one glusterfs brick, but Host 2 not having any glusterfs bricks. The glusterfs daemonset thus runs on Host 0 and Host 1.

Our glusterfs storage class looks as follows:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-replica2
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://heketi.storage.svc.cluster.local:8080"
  clusterid: "<REDACTED>"
  restauthenabled: "false"
  volumetype: "replicate:2"
allowVolumeExpansion: true
```

We set up a cron job on each of the VMs to run the following commands an hourly basis to give us our graphs in the above-mentioned Gist:

```
0 * * * * /bin/bash -c "lsof -P -p `pidof kube-apiserver` | wc -l >> /var/log/kube-apiserver-fd.log"
0 * * * * /bin/bash -c "lsof -P -p `pidof kubelet` | wc -l >> /var/log/kubelet-fd.log"
0 * * * * /bin/bash -c "lsof -P -p `pidof kube-controller-manager` | wc -l >> /var/log/kube-controller-manager-fd.log"
0 * * * * /bin/bash -c "lsof -P -p `pidof kube-proxy` | wc -l >> /var/log/kube-proxy-fd.log"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux <hostname> 4.15.0-1018-azure #18-Ubuntu SMP Thu Jul 19 12:42:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: None/Manual
- Others:

**Comment by pires** [comment]
Can you check the number of TCP connections in state CLOSE_WAIT and overlap in the graph too?

Seems highly related to https://github.com/kubernetes/kubernetes/issues/66133 and https://github.com/kubernetes/kubernetes/issues/66820.

**Comment by thanethomson** [comment]
Will see if we can graph this over the next few days 👍

**Comment by thanethomson** [comment]
We're graphing this at the moment on an hourly basis, will post those charts soon, but in the meantime I thought I'd mention that at first glance there does seem to be a relationship between the number of open files and the number of connections in `CLOSE_WAIT`.

It appears as though all of those connections in `CLOSE_WAIT` are connections to port 10010 (containerd).

**Comment by pires** [comment]
@thanethomson are you using cri-containerd?

**Comment by thanethomson** [comment]
Yes that's what's strange to me. We've configured our `kubelet` to use the containerd socket. I also can't imagine why it'd be a containerd issue. See our `kubelet` config below:

```
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes

[Service]
LimitNOFILE=65535
EnvironmentFile=/run/flannel/subnet.env
ExecStart=/usr/local/bin/kubelet \
  --config=/var/lib/kubelet/kubelet-config.yml \
  --allow-privileged=true \
  --cluster-dns="10.32.0.10" \
  --cluster-domain=cluster.local \
  --container-runtime=remote \
  --image-pull-progress-deadline=10m \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --register-node=true \
  --pod-cidr=${FLANNEL_SUBNET} \
  --container-runtime-endpoint="unix:///var/run/containerd/containerd.sock" \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

Also, see the attached image for what it looks like when I do a `netstat | grep CLOSE_WAIT`.

![k8s close_wait fds](https://user-images.githubusercontent.com/212999/45031405-09e97580-b04f-11e8-9dda-ddd29ac728b6.png)

**Comment by thanethomson** [comment]
We're actively using containerd instead of Docker. I'd imagine that if we disabled containerd's CRI process, we'd be left without any CRI at all? I'm not familiar enough with containerd's internals to be able to make an informed decision on that.

**Comment by thanethomson** [comment]
This issue definitely somehow seems [GlusterFS/Heketi](https://github.com/heketi/heketi)-related. We experienced some instability last week with our GlusterFS setup where it crashed and we just couldn't recover it (I think running Gluster on top of K8s was a bad idea for us - would've probably been better as a system service). We rebuilt our cluster from scratch, minus Gluster (now just using an NFS share with a [dynamic host path provisioner](https://github.com/torchbox/k8s-hostpath-provisioner)), and it all works like a charm.

Plus, looking at the number of open file descriptors over the past few days, we see no additional increase over time. All 3 VMs are sitting at a comfortable (and relatively constant) 100 to 120 open file descriptors at any point in time.

**Comment by paphillon** [comment]
@thanethomson +1, Same experience. I was never able to stabilize Glusterfs pods, the memory consumption kept on increasing even though there were just 3 volumes with barely any data and will eventually get oom. Recovery was another problem. 

Moved Glusterfs as regular rpm install on the nodes and things are stable from past few months, but still not ready for prime time.
