### ISSUE TITLE
should scheduler take real-time resource usage into consideration?

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#67118]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
The prioritize functions are using request to calculate score. Why not considering the real-time resource usage on each node?

**What you expected to happen**:
the nodes with low resource request but high resource usage may get lower score.

**How to reproduce it (as minimally and precisely as possible)**:
na

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Huang-Wei** [comment]
This is also one of my concerns. I _guess_ it's complicated to use/sync realtime info like cAdvisor metrics/CNI info.

@bsalamat @k82cn @resouer should be able to answer this question with more background knowledge.

**Comment by k82cn** [comment]
something like that: https://github.com/kubernetes/kubernetes/pull/62422  ?

@DylanBLE , any case to share?

/cc @ravisantoshgudimetla

**Comment by tanshanshan** [comment]
maybe you can implement a "scheduler extender" process that the standard Kubernetes scheduler calls out to as a final pass when making scheduling decisions.

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md

**Comment by DylanBLE** [comment]
@tanshanshan  Thanks for commenting.  Of course we can do that by implementing mutil-schedulers. I am just wondering what's the community's concern on this :)

**Comment by timothysc** [comment]
The problem with loadavg is your sampling window needs to be defined and weighted against max load capacity.

**Comment by mossuchida** [comment]
Problem that I see here is that I am experimenting de-scheduler & it uses the same algorithm as scheduler.  Initially it is a good idea to use resource request to distribute pods, but when the pods are under heavy load, kubernetes should more intelligently analyze the resource utilization & deploy or de-schedule heavily used pods to unutilized ndoes.  Here is the github issue that I have created for de-scheduler (it would be preferable it is re-scheduler, but there is none right now, I am trying to use de-scheduler instead) : https://github.com/kubernetes-incubator/descheduler/issues/118#issuecomment-425250442

**Comment by fsunaval** [comment]
@DylanBLE Did you figure out a solution to your problem? I'm facing a similar challenge and trying to gather all available info.

**Comment by DylanBLE** [comment]
@fsunaval I am working on a realtime-scheduler-extender which gathers metrics info from[ metrics-server ](https://github.com/kubernetes-incubator/metrics-server)and[ promethues-adaptor](https://github.com/DirectXMan12/k8s-prometheus-adapter).

**Comment by Adirio** [comment]
This is being worked on
/remove-lifecycle rotten
