### ISSUE TITLE
Consider deprecate `Initializers` admission controller

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#67113]
As webhook admission has been beta, and we can implement all the function` Initializers` does by webhook admission. So I think it's time to deprecate `Initializers`, eventually remove it.

/cc @caesarxuchao @deads2k @liggitt @sttts

**Comment by fedebongio** [comment]
@hzxuzhonghu can you check if there is an previous issue already filled for this discussion?
thanks!

**Comment by deads2k** [comment]
We've spoken about it in the sig call, but I don't recall an issue dedicated to it.  We talked about fulfilling the namespace initialization as a special case before completing the removal.  Given it's an alpha feature, we don't have to give warning, but namespace initialization is an important thing to sort out to be sure.

**Comment by warmchang** [comment]
Hi, is there any plan to deprecate the Initializers?

**Comment by liggitt** [comment]
yes, opened https://github.com/kubernetes/kubernetes/pull/72972 and added to [sig-apimachinery meeting agenda](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.rcsstt379k5w) today
