### ISSUE TITLE
Events/alerts for force killed pods

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/kubernetes#67126]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

When you delete a pod, or it get's deleted due to a new version, sometimes containers don't shutdown properly, and just hang. Kubernetes will force kill those when this happens after a grace period. This will be done entirely silent, and the only way to find this out to (manually) watch a pod to see that it takes the full 30 seconds, or whatever is the grace period.

**What you expected to happen**:

There should be an event emitted which can be picked up, as it is useful information to know a pod is not terminating correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod which will ignore the TERM signal.

**Anything else we need to know?**:

This occurs in all versions of kubernetes. Original ticket, closed due to wrong repository: https://github.com/kubernetes/kube-state-metrics/issues/407

**Comment by pvanderlinden** [comment]
@kubernetes/sig-instrumentation-feature-requests

**Comment by pvanderlinden** [comment]
Would be good to have

**Comment by brancz** [comment]
/remove-lifecycle stale

I'm not sure an event is the right thing, but we need some sort of signal that can be processed to potentially notify people.
