### ISSUE TITLE
Kubemark-5000 flakes with namespace deletion

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#67120]
We have recently started seeing occasional failures, e.g:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1137
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1132
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1129
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1124
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1122

From the logs it seems like we're timing out while trying to delete some namespaces, with logs like this ([xref](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1132/build-log.txt)):

```
I0804 18:41:03.010] [1mSTEP[0m: Destroying namespace "e2e-tests-density-30-13-szlkd" for this suite.
I0804 19:41:03.190] Aug  4 19:41:03.190: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
I0804 19:41:03.618] Aug  4 19:41:03.618: INFO: namespace: e2e-tests-density-30-13-szlkd, resource: bindings, ignored listing per whitelist
I0804 19:41:03.734] Aug  4 19:41:03.734: INFO: namespace: e2e-tests-density-30-13-szlkd, resource: pods, items remaining: 1
I0804 19:41:04.620] Aug  4 19:41:04.620: INFO: namespace: e2e-tests-density-30-13-szlkd, DeletionTimetamp: 2018-08-04 18:41:03 +0000 UTC, Finalizers: [kubernetes], Phase: Terminating
I0804 19:41:04.660] Aug  4 19:41:04.659: INFO: namespace: e2e-tests-density-30-13-szlkd, total namespaces: 41, active: 40, terminating: 1
I0804 19:41:04.698] Aug  4 19:41:04.698: INFO: POD                                                          NODE               PHASE    GRACE  CONDITIONS
I0804 19:41:04.699] Aug  4 19:41:04.698: INFO: density150000-12-7ba341bf-9807-11e8-bd7b-0a580a3c2f0d-vb78t  hollow-node-d7crw  Running  1s     [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-08-04 17:25:38 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2018-08-04 17:25:40 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-08-04 17:25:38 +0000 UTC  }]
```

There are multiple such namespaces with pods that are eternally undeleted. Interestingly all those undeleted pods are on the same hollow-node (`hollow-node-d7crw` in this case). This quite likely means that the hollow-kubelet on that hollow-node crashed or became unresponsive and as a result, wasn't able to delete the pods. We need to investigate what went wrong with that hollow-node.

/cc @kubernetes/sig-scalability-bugs @mborsz

**Comment by shyamjvs** [comment]
Ok, so I found out the clusterIP of the hollow-node pod from the build-log:

```
16:57:35.280: INFO: Name: hollow-node-d7crw, clusterIP: 10.64.14.61, externalIP:
```

and then I searched for the node with podCIDR `10.64.14.0/24` in [nodes.yaml](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1132/artifacts/nodes.yaml) file and found that it's `kubemark-5000-minion-group-rshw`. I'll next take a look at that node's logs.

**Comment by shyamjvs** [comment]
I couldn't find anything much useful from the kubelet logs (besides regular creation/deletion logs of the hollow-node pod). I think we should try option-2.

**Comment by mborsz** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1137 -- in gce activity logs I see 'compute.instances.hostError' operation for kubemark-5000-minion-group-1zhg which was running some hollow-node pods that stopped posting node status.

**Comment by mborsz** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1132 -- this is something else
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1129 -- hostError as well
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1127 -- e2e-up.sh error
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1124 -- all broken hollow-nodes are running on kubemark-5000-minion-group-5sxp, but I can't see anything useful in logs.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1122 -- hostError of kubemark-5000-minion-group-jddg

**Comment by mborsz** [comment]
I took a closer look at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1137.
What I found suspicious is that hostError happened there 1-2 hours before log failed because 'hollow-node-b8fbn' is not ready.

The trick is that in case of hostError, rc/hollow-node deletes pods on broken VM and schedules new ones (with a different name).
After each test, test framework checks whether all nodes are ready and for some reason it waits for readiness of no longer existing 'hollow-node-b8fbn'.

It doesn't happen in normal tests, because nodes changes their names fairly rarely in most of the cases (expect when they run as pods in replicacontroller as here).

**Comment by shyamjvs** [comment]
So we discussed this last week and the test framework failing on unready nodes is just a consequence of the actual bug - which is that when hollow nodes go down (for e.g due to hostError on underlying VM), they may not really come back up again because:

- the VM didn't send heartbeat for few mins
- node-controller marks hollow-node pods as deleted
- VM comes up and kubelet sees pod is deleted, and so deletes it
- since hollow node went down, pods running on it are never deleted from kubemark cluster
- test times out deleting and fails

Few potential solutions:

- Increase base cluster's eviction timeout, so hollow-node pods aren't deleted when VM goes down. So they come back up again and delete whatever pods are running on them during test ns deletion phase.
- (As suggested by Maciej) Implement kubemark cloud-provider to delete node objects in case the hollow-node pods went down, which will then lead to pods running on it to get deleted by controller.
- Force delete pods at the end of our test (so we aren't affected by unresponsive nodes). However, this may potentially mask genuine problems with kubelet - so we're avoiding it.

I think we're going by the first option as it's simple and clean.
