### ISSUE TITLE
kubelet failing to collect filesystem states leads to node disk pressure

### ISSUE THREAD

**Issue by blueskyll** [kubernetes/kubernetes#67129]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
kubelet log indicates that cadvisor failed to collect filesystem with a lot of " No such file or directory" , and then eviction manager tells that evicting pod(s) to reclaim nodefs is needed while node disk usage is low.
**What you expected to happen**:
As known from other issues, cadvisor will du the whole overlay dir instead of the writable layer in Kubernetes 1.8, so the du command failed. But node comes to disk pressure state  and evict pods are not expected.
**How to reproduce it (as minimally and precisely as possible)**:
A image with dir which contains a lot of files(100w), and do some operation with the dir, like rm. The dir is in lower layer.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/7546095/43836174-1702d24c-9b47-11e8-9731-adeac4be4ed2.png)
...
...
![image](https://user-images.githubusercontent.com/7546095/43836197-2a3d865e-9b47-11e8-800b-902e741bd343.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Centos 7.2
- Kernel (e.g. `uname -a`): Linux yq01-ai2b-dev-online02.yq01 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Manual installation
- Others:
Docker info:
Server Version: 17.09.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true

**Comment by blueskyll** [comment]
sig/kubelet

**Comment by nladuguie** [comment]
Hi, Any news about how to resolve this issue ? We have the same problem after overuse of ephemeral storage which leads to disk pressure. The pods are evicted and the disk empty but the disk pressure flag persists.
