### ISSUE TITLE
MutatingWebHook unable to update volume sources

### ISSUE THREAD

**Issue by davidbalazs** [kubernetes/kubernetes#67134]
/kind bug

**What happened**:
I am using a MutatingWebHook to decorate incoming deployments with sidecars and volumes. The deployments are part of Helm charts.

When the MutatingWebHook is processing the deployment, there is a volume that is already declared in the volume list of the incoming deployment (and has the volumeSource set to emptyDir) and the mutatingWebHook tries to update the volume by setting a Secret as its volumeSource (instead of the emptyDir).

When installing the Helm chart with the deployment in case to the Kubernetes cluster, it fails with the following error:
` Error: release <HELM_CHART_NAME> failed: Deployment.apps "<DEPLOYMENT_NAME>" is invalid: [**spec.template.spec.volumes[4].secret: Forbidden: may not specify more than 1 volume type**, spec.template.spec.containers[0].volumeMounts[4].name: Not found: "secrets", spec.template.spec.containers[2].volumeMounts[3].name: Not found: "secrets", spec.template.spec.containers[3].volumeMounts[3].name: Not found: "secrets"]`

The patchOperation that the MutatingWebHook is creating for this single volume update is as follows:
```
{  
   "op":"replace",
   "path":"/spec/template/spec/volumes/4",
   "value":{  
      "name":"secrets",
      "secret":{  
         "secretName":"<SECRET_NAME>",
         "items":[  
            {  
               "key":"<SAMPLE_KEY>",
               "path":"<SAMPLE_PATH>"
            }
         ]
      }
   }
}
```

As it looks like, behind the scenes, Kubernetes tries to merge the existing volume declaration with the one that is provided the the mutatingWebHook, therefore I end up having a volume with two volume sources: emptyDir (from the original volume declaration) and Secret (from the new volume declaration), causing the volumeSource validation to fail with the above error.

Things that I have tried so far:
 
1. first tried to add a patchOperation to delete the existing volume, then add a new volume with the same name. Ended up having the same issue
2. created 2 patchOperations: one to delete all the list of volumes, and the other one to add the updated volumes (using a "create" operation). Ended up having the same issue
3. tried to use different versions of client-go and other Kubernetes dependencies for the mutatingWebHook project (written in GoLang). Still no luck :( 

**What you expected to happen**:
MutatingWebHook is able to update an existing volume on the incoming deployment, even if the new volume description has a new volumeSource (a Kubernetes Secret)

**How to reproduce it (as minimally and precisely as possible)**:
Using a MutatingWebHook, try to update a volume on the incoming deployment (submitted via create/patch operation) by changing its volume source (e.g. from EmptyDir to Kubernetes Secret or ConfigMap)

**Anything else we need to know?**:
I was trying to apply the exact same patch operations on a non decorated deployment using **Kubectl** and it worked just fine, the volume has been updated (using the new volumeSource):
`kubectl patch deployment <DEPLOYMENT_NAME> --type='json' -p="$(cat <file_containing_patch_operations>.json)"
`

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0"
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7"
- Others:
go deps version constraints used:
```
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"
[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"
[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"
```

**Comment by caesarxuchao** [comment]
@davidbalazs to debug, could you try creating the deployment without any admission webhook, then use kubectl to send the json merge patch you pasted and see if the deployment is properly updated? That would let us know if it's a admission webhook issue, or an patch library issue.

**Comment by davidbalazs** [comment]
hi @caesarxuchao  I have tried creating the deployment without webhook, then manually patch it with the same patch json that the webhook does, and it worked:
`kubectl patch deployment <DEPLOYMENT_NAME> --type='json' -p="$(cat <file_containing_patch_operations>.json)"`

**Comment by caesarxuchao** [comment]
Actually it works as expected, see my deployment at https://github.com/caesarxuchao/kubernetes/commit/7f7eb9b7721cd5fc0cb78dc246da12db2dbee378#diff-1c64c41d318df5671824f69f9455924dR35.

```
$ kubectl get deployments webhook-to-be-mutated -o yaml --namespace=$(kubectl get namespaces | awk 'FNR==3 {print $1}')
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-31T00:48:25Z
  generation: 1
  name: webhook-to-be-mutated
...
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      apps: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        apps: v1
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.1
        imagePullPolicy: IfNotPresent
        name: example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          items:
          - key: akey
            path: apath
          secretName: asceret
```

Note that my cluster is at the latest commit:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.737+6e81eff02afa7b-dirty", GitCommit:"6e81eff02afa7bbe63b4538ebedc19d02a20f8de", GitTreeState:"dirty", BuildDate:"2018-08-31T00:20:48Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.737+6e81eff02afa7b-dirty", GitCommit:"6e81eff02afa7bbe63b4538ebedc19d02a20f8de", GitTreeState:"dirty", BuildDate:"2018-08-31T00:20:48Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidbalazs** [comment]
thanks @caesarxuchao  for the time! :)

**Comment by caesarxuchao** [comment]
@davidbalazs did you find the root cause in your set up yet?

**Comment by caesarxuchao** [comment]
Please reopen if you still have trouble mutating the deployment.
