### ISSUE TITLE
Inject environment variables into Persistent Volume definition

### ISSUE THREAD

**Issue by jtravell** [kubernetes/kubernetes#67143]
>**_What specific changes need to be made to the code below in order to define environment variables, and then to inject those environment variables into a JSON definition of a Persistent Volume?_** 

Here is my first attempt of a json file in which environment variables would be injected into a definition of a Persistent volume:  

    {
        "apiVersion": "v1",
        "kind": "PersistentVolume",
        "metadata": {
            "name": "statefulset-pgdata-0",
            "labels": {
                "name": "statefulset-pgdata"
            }
        },
        "spec": {
            "capacity": {
                "storage": "$CCP_STORAGE_CAPACITY"
            },
            "accessModes": ["$CCP_STORAGE_MODE"],
            "nfs": {
                "path": "$CCP_STORAGE_PATH",
                "server": "$CCP_NFS_IP"
            },
            "persistentVolumeReclaimPolicy": "Retain",
            "envFrom": {
                "configMapRef": {
                    "name": "aws-auth"
                }
            }
        }
    }

    {
        "apiVersion": "v1",
        "kind": "PersistentVolume",
        "metadata": {
            "name": "statefulset-pgdata-1",
            "labels": {
                "name": "statefulset-pgdata"
            }
        },
        "spec": {
            "capacity": {
                "storage": "$CCP_STORAGE_CAPACITY"
            },
            "accessModes": ["$CCP_STORAGE_MODE"],
            "nfs": {
                "path": "$CCP_STORAGE_PATH",
                "server": "$CCP_NFS_IP"
            },
            "persistentVolumeReclaimPolicy": "Retain"
        }
    }

    {
        "apiVersion": "v1",
        "kind": "PersistentVolume",
        "metadata": {
            "name": "statefulset-pgdata-2",
            "labels": {
                "name": "statefulset-pgdata"
            }
        },
        "spec": {
            "capacity": {
                "storage": "$CCP_STORAGE_CAPACITY"
            },
            "accessModes": ["$CCP_STORAGE_MODE"],
            "nfs": {
                "path": "$CCP_STORAGE_PATH",
                "server": "$CCP_NFS_IP"
            },
            "persistentVolumeReclaimPolicy": "Retain"
        }
    }

But when I type `kubectl apply --filename=statefulset-pv-nfs.json`, I get:  
  
    error: error validating "statefulset-pv-nfs.json": error validating data:   
    ValidationError(PersistentVolume.spec): unknown field "envFrom" in     
    io.k8s.api.core.v1.PersistentVolumeSpec;
  
Also, for completeness, I am including the `ConfigMap` from which I am trying to import the above environment variables as follows:
  
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: aws-auth
      namespace: kube-system
    data:
      mapRoles: |
        - rolearn: arn:aws:iam::999999999/hjhjjhjhjhjhhj
          username: system:node:{{something}}
          groups:
            - system:bootstrappers
            - system:nodes
      CCP_STORAGE_CAPACITY: 400M
      CCP_STORAGE_MODE: ReadWriteMany
      CCP_STORAGE_PATH: /mnt/nfsfileshare
      CCP_NFS_IP: 10.0.0.190

@kubernetes/sig-Architecture 

/sig architecture
/sig apps
/sig cluster-ops
/sig cluster-lifecycle

**Comment by jtravell** [comment]
@k8s-ci-robot 
Do you mean like that?  I dont know what sig to choose.  I am guessing since it has to do with variables then maybe Architecture sig.

**Comment by neolit123** [comment]
/remove-sig architecture
/remove-sig cluster-ops
/remove-sig cluster-lifecycle
/remove-sig apps
/sig aws
/sig storage

the env variables apply to containers (in `Pod`s) not to volumes.
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
