### ISSUE TITLE
coredns fails to start with endless "ContainerCreating"

### ISSUE THREAD

**Issue by bladerunner512** [kubernetes/kubernetes#67141]
/kind bug

**What happened**:
coredns fails to start after deploying SDN

$ kubectl -n kube-system get pods
NAME                                        READY   STATUS              RESTARTS    AGE
calico-kube-controllers-b49d9b875-6lmqx     1/1     Running             0           15m
calico-node-895fq                           2/2     Running             0           15m
calico-node-xjqvk                           2/2     Running             0           15m
coredns-78fcdf6894-2ztj2                    0/1     ContainerCreating   0           1h
coredns-78fcdf6894-xp7nm                    0/1     ContainerCreating   0           1h
kube-apiserver-master001                    1/1     Running             0           42m
kube-controller-manager-master001           1/1     Running             0           42m
kube-proxy-h6lcr                            1/1     Running             0           1h
kube-scheduler-master001                    1/1     Running             0           42m

kubelet log indicates certificate error:
x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs

Aug 07 18:37:24 master002 kubelet[41596]: E0807 18:37:24.905037   41596 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to set up sandbox container "c66b2189f960390c6d699851526941bb9ae43cc14f43301a8f7b7741e09153b9" network for pod "coredns-78fcdf6894-2ztj2": NetworkPlugin cni failed to set up pod "coredns-78fcdf6894-2ztj2_kube-system" network: Get https://[10.96.0.1]:443/api/v1/namespaces/kube-system/pods/coredns-78fcdf6894-2ztj2: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs

Aug 07 18:37:24 master002 kubelet[41596]: E0807 18:37:24.905090   41596 kuberuntime_sandbox.go:56] CreatePodSandbox for pod "coredns-78fcdf6894-2ztj2_kube-system(c0ee3e75-9a87-11e8-82b5-00530c0067fa)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "c66b2189f960390c6d699851526941bb9ae43cc14f43301a8f7b7741e09153b9" network for pod "coredns-78fcdf6894-2ztj2": NetworkPlugin cni failed to set up pod "coredns-78fcdf6894-2ztj2_kube-system" network: Get https://[10.96.0.1]:443/api/v1/namespaces/kube-system/pods/coredns-78fcdf6894-2ztj2: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs

Aug 07 18:37:24 master002 kubelet[41596]: E0807 18:37:24.905106   41596 kuberuntime_manager.go:646] createPodSandbox for pod "coredns-78fcdf6894-2ztj2_kube-system(c0ee3e75-9a87-11e8-82b5-00530c0067fa)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "c66b2189f960390c6d699851526941bb9ae43cc14f43301a8f7b7741e09153b9" network for pod "coredns-78fcdf6894-2ztj2": NetworkPlugin cni failed to set up pod "coredns-78fcdf6894-2ztj2_kube-system" network: Get https://[10.96.0.1]:443/api/v1/namespaces/kube-system/pods/coredns-78fcdf6894-2ztj2: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs

Aug 07 18:37:24 master002 kubelet[41596]: E0807 18:37:24.905175   41596 pod_workers.go:186] Error syncing pod c0ee3e75-9a87-11e8-82b5-00530c0067fa ("coredns-78fcdf6894-2ztj2_kube-system(c0ee3e75-9a87-11e8-82b5-00530c0067fa)"), skipping: failed to "CreatePodSandbox" for "coredns-78fcdf6894-2ztj2_kube-system(c0ee3e75-9a87-11e8-82b5-00530c0067fa)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-78fcdf6894-2ztj2_kube-system(c0ee3e75-9a87-11e8-82b5-00530c0067fa)\" failed: rpc error: code = Unknown desc = failed to set up sandbox container \"c66b2189f960390c6d699851526941bb9ae43cc14f43301a8f7b7741e09153b9\" network for pod \"coredns-78fcdf6894-2ztj2\": NetworkPlugin cni failed to set up pod \"coredns-78fcdf6894-2ztj2_kube-system\" network: Get https://[10.96.0.1]:443/api/v1/namespaces/kube-system/pods/coredns-78fcdf6894-2ztj2: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs"

This appears to be a similar problem to issue:
https://github.com/kubernetes/kubernetes/issues/62939

Adding cert args to kubelet does not solve the problem:
--tls-cert-file=/etc/kubernetes/pki/apiserver.crt 
--tls-private-key-file=/etc/kubernetes/pki/apiserver.key

**What you expected to happen**:
coredns container should reach Ready status

**How to reproduce it (as minimally and precisely as possible)**:
1. create etcd cluster with tls
2. kubeadm init --config /etc/kubernetes/k8s_config.yaml (master001)
3. copy certs to master002 node
4. kubeadm init --config /etc/kubernetes/k8s_config.yaml (master002)
3. deploy Calico

**Anything else we need to know?**:

kubeadm config (fqdn :4242 is Nginx load balancer endpoint):
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
apiServerCertSANs:
- "fqdn"
api:
    controlPlaneEndpoint: "fqdn:4242"
etcd:
    external:
        endpoints:
        - https://xx.xxx.xxx.176:2379
        - https://xx.xxx.xxx.177:2379
        - https://xx.xxx.xxx.178:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
    podSubnet: 192.168.0.0/16

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by idevz** [comment]
@bladerunner512 have you fix this issue? or do you have any  idears? I have just meetting the same.
