### ISSUE TITLE
Running pod and CronJob pod with shared iSCSI PVC not scheduled on same node

### ISSUE THREAD

**Issue by GrantKlassy** [kubernetes/kubernetes#67142]
/kind bug

### **What happened**:

A pod created by a cronjob and an existing pod which shared the same iSCSI pvc did not get scheduled on the same worker node. Because iSCSI can only be mounted read/write to one worker node, the pod scheduled by the cronjob became stuck in ContainerCreating.

### **What you expected to happen**:

Because the two pods shared the same iSCSI pvc, the scheduler should have scheduled them on the same worker node to avoid conflicts. From [Oracle's documentation...](https://docs.oracle.com/cd/E52668_01/E88884/html/kubernetes-gsg-persistentvolume-iscsi.html)

> Note that with iSCSI, support for both read and write operations limit you to hosting all of your pods on a single node. **The scheduler automatically ensures that pods with the same PersistentVolumeClaim run on the same worker node.**

### **How to reproduce it (as minimally and precisely as possible)**:
>Before
```
$ kubectl get pods -n debian-mirror -o wide
NAME      READY     STATUS    RESTARTS   AGE       IP          NODE
web-pod   1/1       Running   0          12d       10.2.0.86   kwork1.<REDACTED>

$ kubectl get cronjobs -n debian-mirror
NAME                    SCHEDULE       SUSPEND   ACTIVE    LAST SCHEDULE   AGE
debian-mirror-updater   */15 * * * *   False     0         <none>          59s
```
>After (pods on different nodes, stuck in ContainerCreating)
```
$ kubectl get pods -n debian-mirror -o wide
NAME                                     READY     STATUS              RESTARTS   AGE       IP          NODE
debian-mirror-updater-1533744000-8qqj4   0/1       ContainerCreating   0          1m        <none>      kwork3.<REDACTED>
web-pod                                  1/1       Running             0          12d       10.2.0.86   kwork1.<REDACTED>
```
>Sharing the same pvc
```
$ kubectl describe pod/web-pod -n debian-mirror | grep Volumes -A 4
Volumes:
  debian-mirror-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  debian-mirror-pvc
    ReadOnly:   false
$ kubectl describe pod/debian-mirror-updater-1533744000-8qqj4 -n debian-mirror | grep Volumes -A 4
Volumes:
  debian-mirror-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  debian-mirror-pvc
    ReadOnly:   false
$ kubectl get pvc -n debian-mirror
NAME                STATUS    VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
debian-mirror-pvc   Bound     large-storage-2   1500Gi     RWO                           21d
```

### **Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
[Bare-metal Typhoon kubernetes](https://typhoon.psdn.io/cl/bare-metal/), 3 controller nodes and 4 worker nodes
```
$ kubectl get nodes
NAME           STATUS    ROLES               AGE       VERSION
<REDACTED>     Ready     controller,master   60d       v1.10.3
<REDACTED>     Ready     controller,master   60d       v1.10.3
<REDACTED>     Ready     controller,master   60d       v1.10.3
<REDACTED>     Ready     node                60d       v1.10.3
<REDACTED>     Ready     node                60d       v1.10.3
<REDACTED>     Ready     node                60d       v1.10.3
<REDACTED>     Ready     node                60d       v1.10.3
```
- Install tools:
[Typhoon bare-metal installation guide (terraform)](https://typhoon.psdn.io/cl/bare-metal/)

**Comment by ronakpandya7** [comment]
any update?

**Comment by GrantKlassy** [comment]
@ronakpandya7 No update on this issue from the Kubernetes Maintainers side. As far as I know the bug described in this GitHub issue is still around. An update from my side is that we've moved to managing our storage using Rook with CephFS. A storage management system like Rook adds additional complexity but not having to worry about manually matching up pods with PVCs was a worthy trade off.
