### ISSUE TITLE
kube-proxy to file events when it runs out of FDs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#6716]
Restarting might also be acceptable. It's a pretty painful user experience right now if this happens-- it fills the logs with this message.

**Comment by thockin** [comment]
Yes, it should just panic()

**Comment by lavalamp** [comment]
Yeah I guess if it's out of FDs it can't really open a network connection to file an event...

**Comment by erictune** [comment]
kube-proxy should send an event when it starts up, just like kubelet does with its `BirthCry()` method.  This works around the fact that you can't send an event when you are out of FDs, and it still provides a lot of debugging value.

**Comment by dchen1107** [comment]
Agreed with @erictune: 

1) kube-proxy should panic when hitting out of fd
2) restarted kube-proxy should pick up the crash reason like what we do for internal agent
3) crash reason should be propogated to upstream as an event.

**Comment by smarterclayton** [comment]
Moving to the right sig.

**Comment by jayunit100** [comment]
we're going to close this because, after 3 years or so ,  decreasing interest in the userspace proxy and nobody other then some openshift folks, are using the linux kube proxy ..

can reopen if necessary ping @aojea @dcbw :)
