### ISSUE TITLE
Liveness  and Readiness probe failed ,but under line examination is health

### ISSUE THREAD

**Issue by zhangxingdeppon** [kubernetes/kubernetes#67180]
Hi,I have meeted a problem.kubelet Liveness  and Readiness probe failed ,but under line examination is health.How should I deal with it?Because of this reason, cause the product service to be restarted

my readness and liveness configuration:
<pre><code>
             "initialDelaySeconds": 15,
              "timeoutSeconds": 3,
              "periodSeconds": 5,
              "successThreshold": 1,
              "failureThreshold": 2
</code></pre>

**What happened**:
Liveness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Readiness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

<pre><code>
Aug  9 06:39:44 localhost kubelet: I0809 06:39:44.340592   13117 prober.go:106] Liveness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Aug  9 06:39:45 localhost kubelet: I0809 06:39:45.139350   13117 server.go:779] GET /stats/summary/: (87.249558ms) 200 [[Go-http-client/1.1] 10.11.41.1:51260]
Aug  9 06:39:45 localhost kubelet: I0809 06:39:45.153174   13117 server.go:779] GET /stats/summary/: (53.0828ms) 200 [[Go-http-client/1.1] 10.11.32.4:33086]
Aug  9 06:39:45 localhost kubelet: I0809 06:39:45.758609   13117 prober.go:106] Readiness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Aug  9 06:39:47 localhost kubelet: I0809 06:39:47.494249   13117 kuberuntime_logs.go:158] Finish parsing log file "/var/log/pods/344ce7ef-9afc-11e8-bf1e-9457a56b2f81/basecore-iapi-xlobo-com_0.log"
Aug  9 06:39:47 localhost kubelet: I0809 06:39:47.494304   13117 server.go:779] GET /containerLogs/ymt-pro/basecore-iapi-xlobo-com-5b9ff9c65d-plj4d/basecore-iapi-xlobo-com?sinceSeconds=1800: (6.936313ms) 200 [[Go-http-client/1.1] 10.11.32.4:39298]
Aug  9 06:39:47 localhost kubelet: I0809 06:39:47.776612   13117 kuberuntime_logs.go:158] Finish parsing log file "/var/log/pods/344ce7ef-9afc-11e8-bf1e-9457a56b2f81/basecore-iapi-xlobo-com_0.log"
Aug  9 06:39:47 localhost kubelet: I0809 06:39:47.776673   13117 server.go:779] GET /containerLogs/ymt-pro/basecore-iapi-xlobo-com-5b9ff9c65d-plj4d/basecore-iapi-xlobo-com: (5.955832ms) 200 [[Go-http-client/1.1] 10.11.32.4:39298]
Aug  9 06:39:49 localhost kubelet: I0809 06:39:49.340688   13117 prober.go:106] Liveness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Aug  9 06:39:49 localhost kubelet: I0809 06:39:49.340831   13117 kubelet.go:1904] SyncLoop (container unhealthy): "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81)"
Aug  9 06:39:49 localhost kubelet: I0809 06:39:49.645022   13117 kuberuntime_manager.go:539] Container "basecore-iapi-xlobo-com" ({"docker" "8ff9c007edfa693b5856b84f71a2c6769e0469f41839ddb2af6a551311f58daf"}) of pod basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81): Container failed liveness probe.. Container will be killed and recreated.
Aug  9 06:39:49 localhost kubelet: I0809 06:39:49.645082   13117 kuberuntime_container.go:567] Killing container "docker://8ff9c007edfa693b5856b84f71a2c6769e0469f41839ddb2af6a551311f58daf" with 30 second grace period
Aug  9 06:39:50 localhost kubelet: I0809 06:39:50.758609   13117 prober.go:106] Readiness probe for "basecore-iapi-xlobo-com-5b9ff9c65d-plj4d_ymt-pro(344ce7ef-9afc-11e8-bf1e-9457a56b2f81):basecore-iapi-xlobo-com" failed (failure): Get http://10.200.109.68:6766/warmup: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Aug  9 06:39:51 localhost kubelet: I0809 06:39:51.346466   13117 kuberuntime_logs.go:158] Finish parsing log file "/var/log/pods/344ce7ef-9afc-11e8-bf1e-9457a56b2f81/basecore-iapi-xlobo-com_0.log"
Aug  9 06:39:51 localhost kubelet: I0809 06:39:51.346529   13117 server.go:779] GET /containerLogs/ymt-pro/basecore-iapi-xlobo-com-5b9ff9c65d-plj4d/basecore-iapi-xlobo-com?sinceSeconds=1800: (6.475269ms) 200 [[Go-http-client/1.1] 10.11.32.4:39298]
Aug  9 06:39:51 localhost kubelet: I0809 06:39:51.632637   13117 kuberuntime_logs.go:158] Finish parsing log file "/var/log/pods/344ce7ef-9afc-11e8-bf1e-9457a56b2f81/basecore-iapi-xlobo-com_0.log"
Aug  9 06:39:51 localhost kubelet: I0809 06:39:51.632692   13117 server.go:779] GET /containerLogs/ymt-pro/basecore-iapi-xlobo-com-5b9ff9c65d-plj4d/basecore-iapi-xlobo-com: (7.83152ms) 200 [[Go-http-client/1.1] 10.11.32.4:39298]
Aug  9 06:39:51 localhost kubelet: I0809 06:39:51.843851   13117 server.go:779] GET /metrics/cadvisor: (300.455414ms) 200 [[Prometheus/2.1.0] 10.11.31.4:50614]
Aug  9 06:39:55 localhost kubelet: I0809 06:39:55.219253   13117 server.go:779] GET /metrics: (35.814874ms) 200 [[Prometheus/2.1.0] 10.11.31.4:50658]
</code></pre>

but under line examination is health,I write a shell script to check,below:

my shell script:
 <pre><code>while true ;do sleep 3;for x in `kubectl get pod -o wide -n ymt-pro |grep basecore |awk '{print $6}'`;do echo -e `date` "http://$x:6766/warmup";echo "http status: "`curl -I -m 3  -o /dev/null -s -w %{http_code}::%{time_namelookup}::%{time_connect}::%{time_starttransfer}::%{time_total}"\n"  http://$x:6766/warmup`;done;done </code></pre>

and output log:
 <pre><code>
Thu Aug 9 06:39:14 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:14 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:18 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.022::0.022
Thu Aug 9 06:39:18 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:22 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:22 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:25 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:25 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.054::0.054
Thu Aug 9 06:39:29 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:29 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:33 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:33 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:37 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:37 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:40 CST 2018 http://10.200.109.68:6766/warmup
http status: 000::0.000::0.001::0.000::3.002
Thu Aug 9 06:39:43 CST 2018 http://10.200.254.204:6766/warmup
http status: 000::0.000::0.001::0.000::3.002
Thu Aug 9 06:39:50 CST 2018 http://10.200.109.68:6766/warmup
http status: 000::0.000::0.001::0.000::3.001
Thu Aug 9 06:39:53 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.340::0.340
Thu Aug 9 06:39:57 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:39:57 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:40:01 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:40:01 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:40:05 CST 2018 http://10.200.109.68:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:40:05 CST 2018 http://10.200.254.204:6766/warmup
http status: 200::0.000::0.001::0.002::0.002
Thu Aug 9 06:40:09 CST 2018 http://10.200.109.68:6766/warmup
 </code></pre>

**What you expected to happen**:
how can I resolve it ?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
 <pre><code>
[root@Linux-10-11-32-4 tmp]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
</code></pre>

**Comment by neolit123** [comment]
"v1.8.6" is no longer supported.
try updating to at least 1.10.0 because 1.12.0 is going to be released soon.

**Comment by zhangxingdeppon** [comment]
Thanks you for your answer,as a matter of fact,because it is now used in production, we can not immediately upgrade for the time being. Is there any other way?

**Comment by moagarw** [comment]
we are having the same issue on production today, though the probe api looks fine, but we are having the same error.

  Warning  Unhealthy              6s (x35 over 38m)     kubelet, k8s-agent-22e40dc-1  Readiness probe failed: Get http://10.244.1.53:5000/readyProbe?token=UuT6kEpdqp: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy              1s (x36 over 38m)     kubelet, k8s-agent-22e40dc-1  Liveness probe failed: Get http://10.244.1.53:5000/liveProbe?token=UuT6kEpdqp: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by jampsen** [comment]
I have the same issue now, kubelet version is GitVersion:"v1.10.0".
liveness or readiness is failed , but under line examination is health

**Comment by xiaoying0442** [comment]
we have the same issue now. How to fix it?

**Comment by HongkaiWen** [comment]
same issue now, why no solution and just closed.
