### ISSUE TITLE
GCE: Tag cloud resources with "tag:kubernetes.io/cluster/<clusterid>"

### ISSUE THREAD

**Issue by dlisin** [kubernetes/kubernetes#67191]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Currently cloud resources (disks, LBs and etc) created by GCE provider are not tagged with any label, so it is hard to determine which resources are related to particular cluster. 
**What you expected to happen**:
In AWS we use "tag:kubernetes.io/cluster/<clusterid>" to mark all cloud resources which are created by AWS cloud provider, so they can be easily filtered. 
It would be great if we can do the same for GCE cloud provider

**Comment by patricklecuyer** [comment]
If noone is on this, I'd like to tackle this as a first contribution.  I'd model it after #41695, which implements the same for AWS.

**Comment by dlisin** [comment]
@patricklecuyer thanks you!

**Comment by dlisin** [comment]
@patricklecuyer do you have any progress on this?
