### ISSUE TITLE
After kubernetes 1.11.2 upgrade pod's cant resolve endpoints via core-dns

### ISSUE THREAD

**Issue by merdincz** [kubernetes/kubernetes#67196]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug
> /kind feature

**What happened**:

I've just upgraded our cluster from 1.10.0 to 1.11.2 and my all end points can't resolve but i can reach via IP address. 

I have two endpoints on different namespaces with named gitlab and redis.

I tried to use dnstools for examine it;
```
dnstools# host kubernetes
kubernetes.default.svc.cluster.local has address 10.96.0.1
dnstools# host 10.105.20.72
72.20.105.10.in-addr.arpa domain name pointer gitlab.devops.svc.cluster.local.
dnstools# host 10.96.227.182
182.227.96.10.in-addr.arpa domain name pointer redis.logging.svc.cluster.local.
```

dnstools resolv.conf;

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
I am trying to reach that records via busybox with;

```
kubectl exec busybox -- nslookup redis.logging.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10:53


*** Can't find redis.logging.svc.cluster.local: No answer
```

Busybox using same resolv.conf as dnstool

```
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
I can reach services via IP address but can't fqdn.

Core-dns doesn't show any error or log about this.

```
.:53
2018/08/09 12:22:32 [INFO] CoreDNS-1.1.3
2018/08/09 12:22:32 [INFO] linux/amd64, go1.10.1, b0fd575c
2018/08/09 12:22:32 [INFO] plugin/reload: Running configuration MD5 = 2a066f12ec80aeb2b92740dd74c17138
CoreDNS-1.1.3
linux/amd64, go1.10.1, b0fd575c
```

**What you expected to happen**:

It have to resolve fqdn.

**How to reproduce it (as minimally and precisely as possible)**:
Install 1.10.0 with kube-dns after upgrade to 1.11.2 and use core-dns

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `v1.11.1`):
- OS (e.g. from /etc/os-release): centos-release-7-5.1804.1.el7.centos.x86_64
- Kernel (e.g. `uname -a`): Linux RMPH014 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisohaver** [comment]
What version of busy box?  There are some busy box releases with broken DNS...

https://github.com/kubernetes/kubernetes/issues/66924#issuecomment-411804435

**Comment by chrisohaver** [comment]
Replica of coredns/coredns#2026 (cross posted)

**Comment by chrisohaver** [comment]
looks like conversation is happening in the  coredns/coredns#2026 clone.

**Comment by merdincz** [comment]
Ok I'm closing this conversation.
