### ISSUE TITLE
serviceaccount validation is not working

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#67193]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
I created a pair of  **unrelated** keys and assigned them to apiserver and controller. Then I created a new namespace with default serviceaccount. To my surprise, deployments in this namespace could still use the token to create pods.

apiserver config
```
        - --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota,NodeRestriction,ServiceAccount,Initializers,PodPreset
        - --authorization-mode=Node,RBAC
        - --token-auth-file=/etc/kubernetes/ssl/token.csv
        - --service-cluster-ip-range=10.10.0.0/16
        - --client_ca_file=/etc/kubernetes/ssl/ca.pem
        - --service-account-key-file=/etc/kubernetes/ssl/test.pem
        - --service-account-lookup=true
```
controller-manager config
```
        - --feature-gates=RotateKubeletServerCertificate=true,SupportIPVSProxyMode=true,PodPriority=true
        - --v=4
        - --kubeconfig=/srv/kubernetes/kubeconfig
        - --leader-elect
        - --root-ca-file=/srv/kubernetes/ca.pem
        - --service-account-private-key-file=/srv/kubernetes/test-key.pem
        - --cluster-signing-cert-file=/srv/kubernetes/ca.pem
        - --cluster-signing-key-file=/srv/kubernetes/ca-key.pem
        - --controllers=*,tokencleaner,bootstrapsigner
        - --logtostderr=true
        - --log_dir=/var/log/kubernetes/
        - --allocate-node-cidrs=true
        - --cluster-cidr=10.11.0.0/16
```
**/etc/kubernetes/ssl/test.pem** and **/etc/kubernetes/ssl/test.pem** are generated **RANDOMLY**  and have no relationship at all.

**What you expected to happen**:
The invalid key pair would forbid deployment from creating pods. 
Like  #22351

**How to reproduce it (as minimally and precisely as possible)**:
Generate two pairs of keys from http://travistidwell.com/jsencrypt/demo/ and set pair1's public key to **apiserver service-account-key-file** and pair2's private key to **controller-manager service-account-private-key-file**.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  **v1.9.6**
docker version: 
  **17.12.1-ce**
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
  **3.10.0-862.3.2.el7.x86_64**
- Install tools:
- Others:

**Comment by yue9944882** [comment]
hi @DylanBLE , it's not a bug. `- --service-account-key-file=/etc/kubernetes/ssl/test.pem` is used to signing secrets into pod. it has nothing to do with authentication between apiserver and controller.

**Comment by yue9944882** [comment]
@kubernetes/sig-auth-bugs for conformance :)

**Comment by liggitt** [comment]
> deployments in this namespace could still use the token to create pods

can you clarify what you mean by that? the controller manager creates pods from deployments. tokens in your new namespace are injected into your new pods and could be used by processes in your pods to contact the API. I would expect those API requests from within your pods to fail authentication with 401 errors

**Comment by DylanBLE** [comment]
@liggitt @yue9944882  It seems to be my **misunderstanding**!
Using the token inside the pod will get 401 response and replicaset controller is not using service account.
Thanks for your reply.
