### ISSUE TITLE
Can't access the other pods' service

### ISSUE THREAD

**Issue by YacheLee** [kubernetes/kubernetes#67198]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

I've googled it for over two weeks. The bug still exists...

I really need someone to help me.

Architecture(1.8.10-gke.2)
HTTP Traffic => LoadBalancer => Service => nginx pods => WWW Service => WWW pods

I set up a service by nginx as a first level traffic load balancer, which has public ip by K8s service: LoadBalancer.

The nginx's job is very simple as the following:

1. SSL

2. Serve the http response by requested domain.

My problem is that the nginx in the Pod SOMETIMES can't access the other ClusterIP services.

I mean SOMETIMES...

I doubt it is the problem of the nginx environment, but when go into the other pods, I can't access too.

The error logs in my nginx pods are disappointment:

`2018/08/09 07:07:13 [error] 137#137: *19956 connect() failed (111: Connection refused) while connecting to upstream, client: 10.140.0.12, server: example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://10.7.255.126:80/favicon.ico", host: "example.com", referrer: "https://example.com/"`

However, the strange thing is that when I curl the WWW service in the WWW pods, it works...

Does anybody gives me some hints?

The reason why I don't use Ingress is for testing purposes. The bug exists too if I put Ingress as the first http traffic load loadbalancer

**Comment by Lion-Wei** [comment]
I'm little confused, can I have your pod and service information? And which pod can't access which service.

**Comment by YacheLee** [comment]
I solved this bug by myself. The bug shows up from time to time.

The reason is Kubernetes doesn't know how to make sure the pods I created are alive.

So its network mechanism SOMETIMES ignores the pods that is alive and well.

The solution is simple: add Readiness and Liveness.

This two Probes help K8s to understand our services provided by pods work well.
