### ISSUE TITLE
allowVolumeExpansion is not applied when creating a StorageClass via kubectl

### ISSUE THREAD

**Issue by devnulled** [kubernetes/kubernetes#67217]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I'm trying to create a StorageClass for AWS and set the parameter "allowVolumeExpansion" and it doesn't seem to get set.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Use this StorageClass YAML:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-blockstorage
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: "true"
```
apply that config using kubectl:

`kubectl apply -f my.yaml`

Then go look at what got set/created:

`kubectl describe storageclass kafka-blockstorage`

This is the result I'm seeing:

```
Name:            kafka-blockstorage
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"kafka-blockstorage","namespace":""},"parameters":{"encrypted":"true","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","reclaimPolicy":"Retain"}

Provisioner:           kubernetes.io/aws-ebs
Parameters:            encrypted=true,type=gp2
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>
```

**Anything else we need to know?**:
I also tried using `"true"` as the value for allowVolumeExpansion and that didn't work either.

**Environment**:
- Kubernetes version (use `kubectl version`):

```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS cluster created using kops

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tanshanshan** [comment]
Add 

> --feature-gates=ExpandPersistentVolumes=true

in apiserver ,and restart it.

> Name:            kafka-blockstorage
> IsDefaultClass:  No
> Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"kafka-blockstorage","namespace":""},"parameters":{"encrypted":"true","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","reclaimPolicy":"Retain"}
> 
> Provisioner:           kubernetes.io/aws-ebs
> Parameters:            encrypted=true,type=gp2
> AllowVolumeExpansion:  True
> MountOptions:          <none>
> ReclaimPolicy:         Retain
> VolumeBindingMode:     Immediate
> Events:                <none>

**Comment by devnulled** [comment]
Thanks @tanshanshan, I didn't realize it wasn't enabled by default.  Thanks for the help.
