### ISSUE TITLE
event of created container cannot be watched after pod running

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#67226]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
when there is no image presented in local, we can find warnings via `kubectl get event -w`.
after uploading image to local docker and pod become running, we can just ocassionally find the _created container_ and _started container_ via the event watcher, which would be quite often if imagepullpolicy=never.

**What you expected to happen**:
we should be able to watch the _created container_ and _started container_ event definitely.

**How to reproduce it (as minimally and precisely as possible)**:
1. create pods which images are not presented in local.
2. wait until the warning of images pull back-off event.
3. upload the images, wait until pod become running.
4. the events of _created container_ and _started container_ would never be watched.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
events are heavily throttled by the kubelet per pod and are not intended as a reliable message delivery bus. if you want to monitor the status of a container, watching the pod is the way to do to.

cc @derekwaynecarr

**Comment by tianshapjq** [comment]
@liggitt thanks for your feedback! would event be useless if it's not reliable? I tested in V1.6.9 and the events of created container and started container would come up definitely. Any changes happened to the event architecture?

**Comment by GaoRong** [comment]
@liggitt 

> events are heavily throttled by the kubelet per pod and are not intended as a reliable message delivery bus. if you want to monitor the status of a container, watching the pod is the way to do to.

would you please tell me where can I find the event's design proposal, I can't find it anywhere. We relay on events heavily, and want it be more reliable.
