### ISSUE TITLE
DaemonSet didn't create pod after node have enough resource

### ISSUE THREAD

**Issue by linyouchong** [kubernetes/kubernetes#67225]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
1. Start a cluster, And node1 with resource example.com.cn/foo:  1
2. Create DaemonSet, request  resource example.com.cn/foo:  4
```
        resources:
          limits:
             example.com.cn/foo: 4 
          requests:
             example.com.cn/foo: 4
```
run `kubectl get ds`, There is no pod created.
3. Add resource to the node:
```
curl --header "Content-Type: application/json-patch+json" \
--request PATCH \
--data '[{"op": "add", "path": "/status/capacity/example.com.cn~1foo", "value": "4"}]' \
http://10.46.178.168:8080/api/v1/nodes/10.46.178.168/status

curl --header "Content-Type: application/json-patch+json" \
--request PATCH \
--data '[{"op": "add", "path": "/status/allocatable/example.com.cn~1foo", "value": "4"}]' \
http://10.46.178.168:8080/api/v1/nodes/10.46.178.168/status
```
run `kubectl describe node 10.46.178.168` 
```
Capacity:
 cpu:                 3
 ephemeral-storage:   8662Mi
 example.com.cn/foo:  4
 hugepages-2Mi:       0
 memory:              3881908Ki
 pods:                110
Allocatable:
 cpu:                 2
 ephemeral-storage:   8174488768
 example.com.cn/foo:  4
 hugepages-2Mi:       0
 memory:              2755508Ki
 pods:                110
```
5. run `kubectl get ds`, There is still no pod created.

**What you expected to happen**:
In step 5, There is one pod created. 

**How to reproduce it (as minimally and precisely as possible)**:
see above description

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.10.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig app

**Comment by k82cn** [comment]
xref https://github.com/kubernetes/kubernetes/pull/58869

**Comment by linyouchong** [comment]
@k82cn Thanks!
#58869 is not work here! Because:
1. The DaemonSetsController didn't watch the changes.(we use `curl` to updateNode.)
2. If we restart kubelet, The DaemonSetsController watch the changes, but it seems that the  node info is not updated, and still failed to create pod: `Node didn't have enough resource: example.com/foo`

**Comment by linyouchong** [comment]
@k82cn 
I found it is a bug here, `updateNode` ignore the `Node.Status.Allocatable` changes.
I made a fix , PTAL! Thanks!
https://github.com/kubernetes/kubernetes/pull/67337

**Comment by kivagant-ba** [comment]
Any workarounds for old cluster versions?

**Comment by k82cn** [comment]
@kivagant-ba , which version of k8s are you using? If it's sunset, you have to merge the pr yourself :).

I think restart kubelet trigger delete/add to make sure it sync .

**Comment by kivagant-ba** [comment]
Sorry, I didn't say
```
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by k82cn** [comment]
I think we still support 1.12 for now :) let's cherry pick it if not and wait for next 1.12 release.
