### ISSUE TITLE
Getting dependcy error while creating kubernetes cluster offline .

### ISSUE THREAD

**Issue by ppnsingh** [kubernetes/kubernetes#67238]
while installing kubernetes node -kubernetes-node-1.8.1-1.el7.x86_64.rpm on one of server , we are getting depency error : root@hydkubedock01 kube_installers]#  yum install -y kubernetes-node-1.9.3-1.el7.x86_64.rpm
Loaded plugins: fastestmirror
Examining kubernetes-node-1.9.3-1.el7.x86_64.rpm: kubernetes-node-1.9.3-1.el7.x86_64
Marking kubernetes-node-1.9.3-1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package kubernetes-node.x86_64 0:1.9.3-1.el7 will be installed
--> Processing Dependency: conntrack-tools for package: kubernetes-node-1.9.3-1.el7.x86_64
Loading mirror speeds from cached hostfile
file:///mnt/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /mnt/iso/repodata/repomd.xml"
Trying other mirror.
--> Processing Dependency: docker for package: kubernetes-node-1.9.3-1.el7.x86_64
--> Processing Dependency: socat for package: kubernetes-node-1.9.3-1.el7.x86_64
--> Running transaction check
---> Package conntrack-tools.x86_64 0:1.4.4-3.el7_3 will be installed
---> Package kubernetes-node.x86_64 0:1.9.3-1.el7 will be installed
--> Processing Dependency: docker for package: kubernetes-node-1.9.3-1.el7.x86_64
---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: kubernetes-node-1.9.3-1.el7.x86_64 (/kubernetes-node-1.9.3-1.el7.x86_64)
           Requires: docker
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Note : We have already installed Docker version 18.03.1-ce, build 9ee9f40 .

Even we are getting below output  in 'docker info' command 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.639GiB
Name: hydkubedock01
ID: ZZBD:X6NG:MCCT:TRQ4:BDQA:JOVY:2GOZ:3HU6:L4I5:FFZR:A5HN:KEMM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by neolit123** [comment]
please try contacting the maintainers of the `kubernetes-node` package.
it is not maintained by the kubernetes github organization and we cannot help much about it.

/close
