### ISSUE TITLE
Scheduler still schedule pod to node which marked as SchedulingDisabled

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#67243]
> /kind bug

**What happened**:

When I mark a node as unschedulable,

```
# kubectl get nodes
NAME           STATUS                     ROLES                          AGE       VERSION
10.10.25.184   Ready                      worker                         6h        v1.11.1+icp-ee
10.10.25.185   Ready                      etcd,management,master,proxy   6h        v1.11.1+icp-ee
10.10.25.186   Ready,SchedulingDisabled   worker                         6h        v1.11.1+icp-ee
```

Pod (from Deployment) still is scheduled that unschedulable node.

```
# kubectl get pods -o wide
NAME                                                 READY     STATUS              RESTARTS   AGE
swift-sample-deployment-797c5bf856-qrvdr         1/1       Running             0          1h        10.1.143.89    10.10.25.186
```

**What you expected to happen**:
Scheduler should choose another node, respect the unschedulable label on node.

**How to reproduce it (as minimally and precisely as possible)**:

Predicate `CheckNodeUnschedulable` never enabled. 

See code https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/scheduler/algorithm/predicates/predicates.go#L1504

And I cannot enabled it via scheduling policy

```
    {
      "name": "CheckVolumeBinding"
    },
    {
      "name": "CheckNodeUnschedulable"
    }
```

Scheduler just show error

```
I0810 08:43:14.237681       1 factory.go:977] Registering predicate: CheckNodeUnschedulable
F0810 08:43:14.237733       1 plugins.go:229] Invalid configuration: Predicate type not found for CheckNodeUnschedulable
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liqlin2015** [comment]
sig/scheduling

**Comment by liqlin2015** [comment]
cc @k82cn

**Comment by liqlin2015** [comment]
I see the previous discussion https://github.com/kubernetes/kubernetes/issues/58648.

So will we can a separate predicate `CheckNodeUnschedulable` or just taint node when user try to put node in maintenance mode `kubectl cordon`.

By way `CheckNodeCondition` did not work. And I don't think predicates `CheckNodeUnschedulable` and `CheckNodeCondition` are work in the same way, do the same job.

**Comment by liqlin2015** [comment]
Close this ticket as it requires to enable alpha feature `TaintNodeByCondition`.

**Comment by jsilberm** [comment]
@liqlin2015 :  Please reach out to me.   I'm seeing the same thing on ICP with 1.10.0-icp-ee.
Easily reproducible.   Does not seem to require `TaintNodeByCondition`.
No idea why this bug is closed.
If you're on the ICP team, this really should be escalated.   Thanks.

**Comment by blackpiglet** [comment]
@jsilberm  Yeah, agreed. I am pretty shocked to see pod still running on the cordoned node.
