### ISSUE TITLE
1.11.2 RPMs are missing

### ISSUE THREAD

**Issue by dkirrane** [kubernetes/kubernetes#67244]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT
/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.11.2 RPM missing from https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

**Comment by tpepper** [comment]
If you add the yum repo and access via yum/dnf does it indicate there is no content or tell you about RPMs?  I think the content is "there".  For example:

If you look in the metadata of the yum repo the package files’ urls are listed there and do resolve, but it’s also in a location that’s not browsable at a file level.  Eg: yum metadata indicates for example https://packages.cloud.google.com/yum/pool/29e7806d1d54cc0eea2963f4ab276778526538816c88c963ece7d1a05fd80792-cri-tools-1.0.0_beta.1-0.x86_64.rpm is a thing and indeed it is.

But if you wanted to file browse or rsync https://packages.cloud.google.com/yum/pool/ or  https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 that’s clearly not going to work given how it's laid out.

**Comment by foxish** [comment]
Oops, this is missing. @jpbetz, can you help release this?

**Comment by mbohlool** [comment]
On it

**Comment by mbohlool** [comment]
Done
