### ISSUE TITLE
RBD tests fail with hostname: command not found\n/bootstrap.sh

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/kubernetes#67269]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
e2e tests which use RBD server image fail with ```hostname: command not found\n/bootstrap.sh```

**What you expected to happen**:
These tests succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Run e2e tests which use RBD server image.

**Anything else we need to know?**:
/sig storage

This issue is introduced by below commit:
https://github.com/kubernetes/kubernetes/commit/f4caccccfe49bc1075842d18c84385ebbab6a9c7#diff-e5d0ceccff9054af3c69ac1b4d5930d2R18

It change the base image from fedora 26 to fedora 28.
In fedora 26, hostname command is installed as a dependency for [```RUN yum install -y wget strace psmisc procps-ng ceph ceph-fuse && yum clean all```](https://github.com/kubernetes/kubernetes/blob/master/test/images/volume/rbd/Dockerfile#L23)
However, in fedora 28, it is not installed, as a result, this issue happens due to lack of hostname command.

**Environment**:
- Kubernetes version (use `kubectl version`): k8s 1.12 alpha

**Comment by mkimuram** [comment]
Please see the difference of the behaviour between fedora 26 and 28.

[Fedora26]
```
# docker run --rm -ti docker.io/fedora:26 bash
# yum install -y wget strace psmisc procps-ng ceph ceph-fuse
# which hostname
/usr/bin/hostname
```

[Fedora28]
```
# docker run --rm -ti docker.io/fedora:28 bash
# yum install -y wget strace psmisc procps-ng ceph ceph-fuse
# which hostname
which: no hostname in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
# yum install -y hostname
# which hostname
/usr/bin/hostname
```

**Comment by dims** [comment]
`make all-containers WHAT=volume/rbd` (or) `make all-containers WHAT=volume/push` 

Both need to be run from `test/images/` directory

**Comment by mkimuram** [comment]
@dims

Thank you for letting me know it.
It should be s/all-containers/all-container/, but it seems to work.

I will test with above patch and above build commands, then make a PR, once I confirm that it works well.

**Comment by dims** [comment]
sorry typing from memory :)

**Comment by mkimuram** [comment]
@dims 

I need to ask you two more things:
  - Do we need to increment the version for this image, like 1.0.1, even for this small change?
   (I guess that test/utils/image/manifest.go and test/images/volume/rbd/VERSION will need to be updated in this case.)
  - How the image push process will be? Does it pushed by CI, if there are a change in the code or docker file, or do someone who have permission will push it manually?

**Comment by mkimuram** [comment]
@dims 

```# make all-containers WHAT=volume/rbd``` creates below three docker images: 
- gcr.io/kubernetes-e2e-test-images/volume/rbd-ppc64le
- gcr.io/kubernetes-e2e-test-images/volume/rbd-arm64  
- gcr.io/kubernetes-e2e-test-images/volume/rbd-amd64

Is my understanding right that to make each test access to each arch image, test/utils/image/manifest.go needs to be modified like below?
(Without doing so, each test seems to keep trying to access to gcr.io/kubernetes-e2e-test-images/volume/rbd, without arch.)

```
- VolumeRBDServer     = ImageConfig{e2eRegistry, "volume/rbd", "1.0", false}
+ VolumeRBDServer     = ImageConfig{e2eRegistry, "volume/rbd", "1.0", true}
```

**Comment by mkimuram** [comment]
@rootfs @jsafrane 

For fedora28 image, just installing hostname doesn't seem to work well. Please see the log below and attached [rbd_with_fc28.txt](https://github.com/kubernetes/kubernetes/files/2279503/rbd_with_fc28.txt).
I guess that this is due to the difference of ceph version, which will be beyond my beyond my expertise.

So, could you help debugging this issue? Meanwhile, I will try testing with the image by using fedora26 for workaround. 

```
        Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
        monmaptool: set fsid to a3ef47d6-ee91-4419-9c3f-9ff050d36e79
        monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
        2018-08-10 21:06:44.910799 7f00f5638000 -1 WARNING: 'mon addr' config option 172.17.0.3:0/0 does not match monmap file
                 continuing with monmap configuration
        1
        /usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type
) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Asserti
on '__builtin_expect(__n < this->size(), true)' failed.
        *** Caught signal (Aborted) **
         in thread 7f09a38033c0 thread_name:crushtool
         ceph version 12.2.7 (3ec878d1e53e1aeb47a9f619c49d9e7c0aa384d5) luminous (stable)
         1: (()+0x1e9cc) [0x55e13d9289cc]
         2: (()+0x11fb0) [0x7f0999437fb0]
         3: (gsignal()+0x10b) [0x7f0997f25f4b]
         4: (abort()+0x12b) [0x7f0997f10591]
         5: (()+0x143b8) [0x55e13d91e3b8]
         6: (()+0x4b1cb3) [0x7f099ad65cb3]
```

**Comment by mkimuram** [comment]
> Meanwhile, I will try testing with the image by using fedora26 for workaround.

I confirmed that below commit, which change the base image back to fedora 26, fix this issue. Please see the log [rbd_with_fc26.txt](https://github.com/kubernetes/kubernetes/files/2279636/rbd_with_fc26.txt).

https://github.com/mkimuram/kubernetes/commit/9d67e3290c5430e87ed714145d572bf370ca1837

> Is my understanding right that to make each test access to each arch image, test/utils/image/manifest.go needs to be modified like below?
> (Without doing so, each test seems to keep trying to access to gcr.io/kubernetes-e2e-test-images/volume/rbd, without arch.)

After I checked the image-util.sh, I come to think that by pushing the image, each image will be able to be pulled without -arch, so I guess the last parameter for ImageConfig should be false. (I couldn't test it in my environment.)

I will fix the commit as so and make a PR once I confirm it. @dims 

Also, if it will easy to fix with Fedora 28, I will wait for the actual fix and quit making a PR for the workaround. @jsafrane @rootfs

**Comment by rootfs** [comment]
thanks @mkimuram 
yes, a quick fix is welcome, looking forward

**Comment by mkimuram** [comment]
@rootfs 

Thank you for your comment. I will continue with the workaround.

@dims

I saw a commit for deleting multi arch consideration. https://github.com/kubernetes/kubernetes/commit/789800d298d4723a295cb507cb603b7d091b5de2
I rebased the patch to the commit and made a PR. https://github.com/kubernetes/kubernetes/pull/67351
Please review it.
