### ISSUE TITLE
Human readable status from conditions for a CRD using additionalPrinterColumns

### ISSUE THREAD

**Issue by greghaynes** [kubernetes/kubernetes#67268]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
When a CRD contains status conditions in a pattern similar to PodCondition there is not a good way to produce human readable output of the current status in kubectl. AdditionalPrinterColumns is useful for improving kubectl UX for data which can be pulled directly from the CRD but status conditions are generally stored as a list which requires additional processing to be human readable.

**What you expected to happen**:
I'd like the ability to select a single status condition's value for printing in a column via additionalPrinterColumns.

**How to reproduce it (as minimally and precisely as possible)**:
I have a CRD which defines the following schema under the property "status":
```go
type FooConditionType string

type FooCondition struct {
    Type FooConditionType
    // k8s.io/api/core/v1 ConditionStatus
    Status corev1.ConditionStatus
}

type FooStatus struct {
    Conditions []FooCondition
}

```
I am unable to provide a 'status' column for kubectl get based on a condition value e.g. I'd like to show ConditionReady's value in a READY column.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1

**Comment by liggitt** [comment]
/sig api-machinery

CRD and server-side printing belong to api-machinery

**Comment by nikhita** [comment]
/area custom-resources

> When a CRD contains status conditions in a pattern similar to PodCondition

We do a lot of processing to print the pod right now:

https://github.com/kubernetes/kubernetes/blob/29232e3edc4202bb5e34c8c107bae4e8250cd883/pkg/printers/internalversion/printers.go#L546

Also, based on my discussion with @sttts, we are planning to support only simple json paths (no arrays) after this. (https://github.com/kubernetes/kubernetes/pull/67079) If you specified an array even now, it would print only the first element. 

However, given the complex nature of printing the status, I doubt that it would be possible with just json paths anyway. So it should _probably_ be safe to limit the json paths without making it bite us in the future...depending on how we intend to support such complex printing.

**Comment by munnerz** [comment]
+1, I'd love to see this implemented somehow.

I'm currently moving critical/useful information *out* of status conditions since the additional columns spec won't allow me to cleanly select a particular type of condition.

**Comment by rosskukulinski** [comment]
+1 as well.  As an example, we have a CRD for matching Ingress paths.  

```
  spec:
    routes:
    - match: /
      services:
      - name: kuard
        port: 80
    - match: /foobar
      services:
      - name: bar
        port: 80
    virtualhost:
      fqdn: mixed.local
```

It would be great to be able to output the `match` field for all routes.  Currently the simple JSONPath `.spec.routes[*].match` will only output the first field (as @nikhita mentioned).

**Comment by sttts** [comment]
I am not against non-simple JSON paths. It's just that we started with them in the API. @rosskukulinski's use-case would be solved by non-simple paths. But as @nikhita says: more complex condition logic would not.

**Comment by nikhita** [comment]
> I am not against non-simple JSON paths. It's just that we started with them in the API.

@sttts I think it should be ok to allow non-simple JSON paths now. Wdyt?

We don't really loose any validations with that because we don't validate the value in the specified json paths.

**Comment by sttts** [comment]
@nikhita it needs a small design about the semantics. It's an api change.
