### ISSUE TITLE
After kubernetes 1.11.2 upgrade pod's and master can't communicate across nodes

### ISSUE THREAD

**Issue by merdincz** [kubernetes/kubernetes#67278]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I've upgraded my kubernetes cluster from 1.10.0 to 1.11.2 after that my nodes can't communicate with each others. I have 1 master 3 nodes bare metal and i am using weave-net for network plugin.

For example i have a service named redis;

`logging         redis                NodePort    10.96.227.182    <none>        6379:30329/TCP`

It is working on node b;

`logging         pod/redis-55656c7dc9-x7954           1/1       Running             1          10h       172.17.0.11`

I can reach redis service with;

`curl 10.96.227.182:6379`

or

`curl 172.17.0.11:6379`

but i can't reach this service from master or other 2 nodes with service or pod ip addresses.

**What you expected to happen**:

I have to communicate service across the nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): "v1.11.1
- Cloud provider or hardware configuration: 2 Bare metal 2 VPS
- OS (e.g. from /etc/os-release): centos-release-7-5.1804.1.el7.centos.x86_64
- Kernel (e.g. `uname -a`): Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: kubeadm
- Others:
 /sig network

**Comment by ocofaigh** [comment]
Spent all day debugging this. Deployment blocker. Need a fix ASAP

**Comment by ocofaigh** [comment]
@merdincz Did you find any solution to this?

**Comment by merdincz** [comment]
@ocofaigh Nope, I'm still waiting help.

**Comment by kartojal** [comment]
Facing the same issue after upgrading from 1.10 to 1.11.2, similar bare-metal setup with Centos 7 and flannel. Any recommendation?

**Comment by merdincz** [comment]
@ocofaigh Thank you i just updated all images with;

`kubectl delete pod --all -n kube-system`

Also rebooted master and nodes but nothing changed. Which process did you followed for fresh deployment?

**Comment by ocofaigh** [comment]
I did a complete new deployment of the platform following these steps: https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by kartojal** [comment]
After downgrading to 1.11.1 and doing a  refresh of the NodePort service
that handles my ingress-nginx deployment  i am able to reach my cluster.

**Comment by manojgoyal04** [comment]
I also upgraded my cluster from 1.10 to 1.11.0 and facing the same issue. Services running on master node, not accessible from another nodes with in the cluster. I tried both with CoreDNS and kube-DNS.
If I kill DNS service+deploy running on master node, and  run it on another node, then services running on master node are accessible form that node only. Like this I have to keep killing DNS service+deploy on all the nodes. Then only it works.

**Comment by paravz** [comment]
found this looking for my centos upgrade difficulties, i needed to remove these packages added by update to keep kubernetes flannel networking working:

 `sudo rpm-ostree override remove firewalld-filesystem firewalld podman`

**Comment by ocofaigh** [comment]
Don't see this anymore. I think maybe I resolved it by following the steps here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

/close

**Comment by limbuu** [comment]
Having same issue while upgrading 1.11.4 to 1.11.12. The cluster keep showing upgrade but not upgraded yet.
