### ISSUE TITLE
kube-up doesn't report any errors when SSH fails

### ISSUE THREAD

**Issue by paddycarver** [kubernetes/kubernetes#6728]
When creating a cluster on GCE with kube-up (using kubernetes 0.14.2), there's no output to indicate that SSH failed, and ~/.kube/.kubeconfig never got created. This popped up because what I _thought_ was the password for my SSH key was not, in fact, the password for my SSH key. Whoops.

You can see the output I got here: https://gist.github.com/paddyforan/2a499a8140c3df742d1c

I assumed when I saw "cluster created", it meant that the cluster had successfully been stood up, and didn't notice anything was wrong.

In the event of an error, I expected to see "Error: SSH failed" or something similar, with a termination of the kube-up script.

**Comment by roberthbailey** [comment]
I think this is a problem with the output from our script. A successful run outputs quite a bit of info *after* "Kubernetes cluster created." (including instructions for how to reach your cluster). We should change the text part-way through the script so that it doesn't make you think that it is done when in fact it isn't.

**Comment by roberthbailey** [comment]
@juliaferraioli

**Comment by roberthbailey** [comment]
I bet this is still a point of friction with our shell scripts.

**Comment by justinsb** [comment]
I believe we've improved this.  But with kube-up in maintenance mode, should we close?

**Comment by roberthbailey** [comment]
Yes, this was "improved" in the sense that we no longer generate keys on the master and fetch them down via ssh; instead we generate them locally and push them up via the metadata server. As there is no longer a step to ssh into the master to fetch files I'm closing as obsolete.
