### ISSUE TITLE
Please add --dns-loop-detect option to dnsmasq run by kube-dns

### ISSUE THREAD

**Issue by hedayat** [kubernetes/kubernetes#67299]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
If hosts `/etc/resolv.conf` points to a local DNS server, or if it contains the cluster's DNS server (to enable looking up services from host), it'll cause DNS loop which can effectively disable kube-dns or make it very slow. 

**What you expected to happen**:
At least, kube-dns should detect localhost or cluster DNS server entries in resolv.conf and not send queries to them.

**How to reproduce it (as minimally and precisely as possible)**:
Use a system with local cashing DNS server, or add cluster's DNS server address to hosts resolv.conf.

**Anything else we need to know?**:
According to `dnsmasq` documentation, adding `--dns-loop-detect` should make dnsmasq detect that and disable the upstream DNS server which cause the loop. It should prevent DNS from becoming unresponsive in the first case (a better solution is to extract real upstream servers, which probably cannot be done for every configuration); and for the second case it should skip sending queries to itself and send to real upstream servers.

**Comment by prameshj** [comment]
@hedayat Could you describe the use-case more? If the host's /etc/resolv.conf contains cluster DNS server and some other upstream server - like 8.8.8.8, will services lookups work reliably from the host?
If the services lookup goes to the 8.8.8.8 server, it will return NXDOMAIN. If it hits the clusterDNS server, only then it would work, correct?

**Comment by MrHohn** [comment]
Also ref https://linux.die.net/man/5/resolv.conf:
> If there are multiple servers, the resolver library queries them in the order listed...(The algorithm used is to try a name server, and if the query times out, try the next, until out of name servers, then repeat trying all the name servers until a maximum number of retries are made.)

If the first server returns NXDOMAIN, the second server will not be tried. How do you make both cluster DNS name and non-cluster DNS name resolvable on the host?

**Comment by hedayat** [comment]
If cluster DNS server comes before a real DNS server, it works fine.
Also note that what resolv.conf man page says is the glibc (or libc) behavior, not other users (e.g. dnsmasq sends its queries to any one of them, but can be configured to query them in strict order (`--strict-order` flag), or to query all of them (`--all--servers`).

Anyway, consider when cluster DNS server comes before the real server:

1. For cluster DNS queries, the cluster DNS server responds with the IP of the cluster or pod.
2. For external names, the query is sent to cluster DNS server. It doesn't find the name, so it tries to send it to upstream DNS servers; which in my example are cluster DNS server itself and an external DNS server. 
If dnsmasq sends it to external DNS server, it'll receive the answer and can serve the query. If it sends it to itself, there is a loop and the same process happens again until dnsmasq decides to query the other server (which might not happen!). WIth `--dns-loop-detect` flag, when dnsmasq sends the query to itself, it'll recognize the loop and will remove its own address from the list of upstream DNS servers, so it'll always send external names to the external DNS server from now on.

**Comment by MrHohn** [comment]
@hedayat Thanks for the explanation. I believe it might work with explicit configuration. Though adding a flag to upstream for fulfilling a not quite common use case seems a bit odd to me.

Have you thought of configuring upstream DNS servers via kube-dns config [1] such that it will not send request to itself at all?

[1] - https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers

**Comment by hedayat** [comment]
Note that the flag has two use cases, the other one is prevent kube-dns breakage when upstream DNS server is a local one (e.g. If you deploy to Ubuntu, which has local caching DNS server by default (e.g. in 18.04, it is systemd-resolved and /etc/resolv.conf contains 127.0.0.53)). Actually I guess there are a number of DNS related issues which might be solved by this flag too.

So, while this flag will not make kubernetes magically find real upstream dns servers in such cases, it prevents kube-dns crash; which has caused frustration and some time for me to discover. So, either kubelet should error out and exit if the given resolv.conf contains a local address, or such flag should be used by kube-dns to prevent DNS loops.

And, IIRC, the only reason that cluster's DNS server is not added to host, at least by kubespray, is mentioned to be host specific in the docs. So, my use case seems to be an ideal one and it would be the default one if it was easy to setup for different platforms.

About using kube-dns config, no. We're going to provide automatic kubernetes deployment for many environments, and so we don't know the upstream DNS servers upfront, and we don't want to hard code it. We want it to be the DNS servers used in the target network. So, configuring a specific upstream DNS server is a no-go.
