### ISSUE TITLE
error creating ipset xxx, error: exit status 1

### ISSUE THREAD

**Issue by verwilst** [kubernetes/kubernetes#67292]
/kind bug

**What happened**:
Installed k8s 1.11.2 cluster with Kubespray, and selected ipvs instead of iptables as proxy mode. Results in crash loops for all kube-proxy containers:

kube-proxy-k8s-api01                       1/1       Running            72         6h
kube-proxy-k8s-api02                       1/1       Running            72         6h
kube-proxy-k8s-node01                      0/1       CrashLoopBackOff   74         6h
kube-proxy-k8s-node02                      0/1       CrashLoopBackOff   71         6h

Output of logs of proxies:

E0811 03:56:46.572470       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOAD-BALANCER-SOURCE-IP hash:ip,port,ip inet 1024 65536 0-65535 Kubernetes service load balancer ip + port + source IP for packet filter purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-LOAD-BALANCER-SOURCE-IP, error: exit status 1
E0811 03:56:51.709465       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOAD-BALANCER-SOURCE-IP hash:ip,port,ip inet 1024 65536 0-65535 Kubernetes service load balancer ip + port + source IP for packet filter purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-LOAD-BALANCER-SOURCE-IP, error: exit status 1
E0811 03:56:56.772034       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOAD-BALANCER-SOURCE-CIDR hash:ip,port,net inet 1024 65536 0-65535 Kubernetes service load balancer ip + port + source cidr for packet filter purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-LOAD-BALANCER-SOURCE-CIDR, error: exit status 1
E0811 03:57:01.913755       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-EXTERNAL-IP hash:ip,port inet 1024 65536 0-65535 Kubernetes service external ip + port for masquerade and filter purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-EXTERNAL-IP, error: exit status 1
E0811 03:57:06.971781       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOOP-BACK hash:ip,port,ip inet 1024 65536 0-65535 Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-LOOP-BACK, error: exit status 1
E0811 03:57:12.072673       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-LOOP-BACK hash:ip,port,ip inet 1024 65536 0-65535 Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-LOOP-BACK, error: exit status 1
E0811 03:57:17.277255       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-NODE-PORT-LOCAL-UDP bitmap:port inet 1024 65536 0-65535 Kubernetes nodeport UDP port with externalTrafficPolicy=local} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-NODE-PORT-LOCAL-UDP, error: exit status 1
E0811 03:57:22.372453       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-NODE-PORT-LOCAL-TCP bitmap:port inet 1024 65536 0-65535 Kubernetes nodeport TCP port with externalTrafficPolicy=local} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-NODE-PORT-LOCAL-TCP, error: exit status 1
E0811 03:57:27.475447       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-EXTERNAL-IP hash:ip,port inet 1024 65536 0-65535 Kubernetes service external ip + port for masquerade and filter purpose} map[] 0xc4209237b0} exist, error: error creating ipset KUBE-EXTERNAL-IP, error: exit status 1

**What you expected to happen**:

Stable kube-proxy containers.

kube-proxy-k8s-api01                       1/1       Running            0         6h
kube-proxy-k8s-api02                       1/1       Running            0         6h
kube-proxy-k8s-node01                      1/1       Running   0         6h
kube-proxy-k8s-node02                      1/1       Running   0         6h

**How to reproduce it (as minimally and precisely as possible)**:

Install kubernetes 1.11.x with kube_proxy_mode: ipvs

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): CoreOS stable (1800.6.0)
- Kernel (e.g. `uname -a`): Linux k8s-acc-api02 4.14.59-coreos-r2 #1 SMP Sat Aug 4 02:49:25 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz GenuineIntel GNU/Linux

- Install tools: Kubespray
- Others: Probably doesn't matter, but using 3 separate etcd nodes.

**Comment by verwilst** [comment]
@kubernetes/sig-network-bugs

**Comment by islinwb** [comment]
Does the command `ipset create` work?

**Comment by verwilst** [comment]
k8s-acc-api01 core # ipset create foo hash:ip comment
k8s-acc-api01 core # ipset list -n     
KUBE-LOAD-BALANCER-LOCAL
KUBE-LOAD-BALANCER-SOURCE-IP
KUBE-LOAD-BALANCER-SOURCE-CIDR
KUBE-NODE-PORT-LOCAL-TCP
KUBE-LOAD-BALANCER
KUBE-LOAD-BALANCER-FW
KUBE-EXTERNAL-IP
KUBE-NODE-PORT-TCP
KUBE-NODE-PORT-UDP
KUBE-NODE-PORT-LOCAL-UDP
KUBE-LOOP-BACK
KUBE-CLUSTER-IP
foo
cali40all-ipam-pools
cali40masq-ipam-pools
cali40this-host
cali40all-hosts

**Comment by islinwb** [comment]
@verwilst 
The errors were throwed at https://github.com/kubernetes/kubernetes/blob/v1.11.2/pkg/util/ipset/ipset.go#L307.
The exact commands should be (or you can print the `args`)
```
ipset create KUBE-NODE-PORT-LOCAL-TCP bitmap:port range 0-65535 -exist
ipset create KUBE-LOOP-BACK hash:ip,port,ip family inet hashsize 1024 maxelem 65536 -exist
...
```
Maybe try these manually?

**Comment by inish777** [comment]
@islinwb @verwilst I have the same issue with the same configuration during update from 1.11.0
When trying to run command manually I get something like 
```
ipset v6.30: Set cannot be created: set with the same name already exists
```
and 1 in $?
I suppose that during update new version of kube-proxy trying to create ipset with same name but different config, so ```-exist``` doesn't work.

**Comment by islinwb** [comment]
@inish777 Thanks! The `-exist` means
```
-!, -exist
Ignore errors when exactly the same set is to be created or already added entry is added or missing entry is deleted.
```
from http://ipset.netfilter.org/ipset.man.html.

I'll take a look at this problem.

**Comment by islinwb** [comment]
@inish777 For your case, the probelm should be caused by https://github.com/kubernetes/kubernetes/pull/63585 and https://github.com/kubernetes/kubernetes/pull/65741.  In Kubernetes v1.11.0, ipsets are with comments which are removed in v1.11.1 . Sorry for the trouble brought.
@verwilst Did you install v1.11.2 directly? I guess it's the same problem.

Manually deleting these ipsets can be a workaround.
Can we cherry-pick commit #65741 to the release v1.11.0? @m1093782566
/cc @thockin @Lion-Wei

**Comment by m1093782566** [comment]
Yes, I think so.

**Comment by islinwb** [comment]
@verwilst Could you take a look at the difference between the existing ipset and the one with the same name to be created?

**Comment by islinwb** [comment]
@m1093782566 I think we should delete the ipset with the same name if any before creating an ipset. Currently the creation fails if there is an ipset with the same name but the content is not exactly the same. 
https://github.com/kubernetes/kubernetes/blob/bb9ffb1654d4a729bb4cec18ff088eacc153c239/pkg/util/ipset/ipset.go#L306

**Comment by dawidmalina** [comment]
I have quite similar issue with kube-proxy configured with ipvs mode (kubernetes 1.11.1 deployed on ubuntu 16.04) with calico as network provider:
```
E0909 20:29:12.860025       1 ipset.go:146] Failed to add entry: 10.10.0.6,tcp:443,10.10.0.6 to ip set: KUBE-LOOP-BACK, error: error adding entry 10.10.0.6,tcp:443,10.10.0.6, error: exit status 1
E0909 20:29:12.862350       1 ipset.go:146] Failed to add entry: 192.168.128.2,tcp:9090,192.168.128.2 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.2,tcp:9090,192.168.128.2, error: exit status 1
E0909 20:29:12.863803       1 ipset.go:146] Failed to add entry: 192.168.128.5,tcp:53,192.168.128.5 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.5,tcp:53,192.168.128.5, error: exit status 1
E0909 20:29:12.865882       1 ipset.go:146] Failed to add entry: 192.168.128.5,udp:53,192.168.128.5 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.5,udp:53,192.168.128.5, error: exit status 1
E0909 20:29:12.867158       1 ipset.go:146] Failed to add entry: 192.168.128.6,tcp:8082,192.168.128.6 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.6,tcp:8082,192.168.128.6, error: exit status 1
E0909 20:29:12.868478       1 ipset.go:146] Failed to add entry: 192.168.128.7,tcp:53,192.168.128.7 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.7,tcp:53,192.168.128.7, error: exit status 1
E0909 20:29:12.869723       1 ipset.go:146] Failed to add entry: 192.168.128.7,udp:53,192.168.128.7 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.128.7,udp:53,192.168.128.7, error: exit status 1
E0909 20:29:12.870887       1 ipset.go:146] Failed to add entry: 192.168.129.2,tcp:9376,192.168.129.2 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.129.2,tcp:9376,192.168.129.2, error: exit status 1
E0909 20:29:12.872067       1 ipset.go:146] Failed to add entry: 192.168.129.3,tcp:9376,192.168.129.3 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.129.3,tcp:9376,192.168.129.3, error: exit status 1
E0909 20:29:12.873271       1 ipset.go:146] Failed to add entry: 192.168.130.2,tcp:9376,192.168.130.2 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.130.2,tcp:9376,192.168.130.2, error: exit status 1
E0909 20:29:12.874579       1 ipset.go:146] Failed to add entry: 192.168.130.3,tcp:9376,192.168.130.3 to ip set: KUBE-LOOP-BACK, error: error adding entry 192.168.130.3,tcp:9376,192.168.130.3, error: exit status 1
E0909 20:29:12.876800       1 ipset.go:146] Failed to add entry: 192.168.192.1,tcp:443 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.1,tcp:443, error: exit status 1
E0909 20:29:12.878023       1 ipset.go:146] Failed to add entry: 192.168.192.10,tcp:53 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.10,tcp:53, error: exit status 1
E0909 20:29:12.879187       1 ipset.go:146] Failed to add entry: 192.168.192.10,udp:53 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.10,udp:53, error: exit status 1
E0909 20:29:12.880311       1 ipset.go:146] Failed to add entry: 192.168.192.138,tcp:9090 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.138,tcp:9090, error: exit status 1
E0909 20:29:12.881451       1 ipset.go:146] Failed to add entry: 192.168.192.139,tcp:80 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.139,tcp:80, error: exit status 1
E0909 20:29:12.882453       1 ipset.go:146] Failed to add entry: 192.168.192.148,tcp:24224 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.148,tcp:24224, error: exit status 1
E0909 20:29:12.883466       1 ipset.go:146] Failed to add entry: 192.168.192.183,tcp:9376 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.192.183,tcp:9376, error: exit status 1
E0909 20:29:12.884917       1 ipset.go:146] Failed to add entry: 192.168.193.173,tcp:24224 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.193.173,tcp:24224, error: exit status 1
E0909 20:29:12.886067       1 ipset.go:146] Failed to add entry: 192.168.195.12,tcp:80 to ip set: KUBE-CLUSTER-IP, error: error adding entry 192.168.195.12,tcp:80, error: exit status 1
E0909 20:29:12.891029       1 ipset.go:146] Failed to add entry: 10.10.0.100,tcp:80 to ip set: KUBE-EXTERNAL-IP, error: error adding entry 10.10.0.100,tcp:80, error: exit status 1
```

**Comment by islinwb** [comment]
@dawidmalina Could you check the existing ipsets use `ipset list` to see if there are ipsets with the same names that were failed to create? And check the entries if any.

**Comment by dawidmalina** [comment]
@m1093782566 this was fresh setup on my local environment. Today i can try with 1.11.3.

@islinwb i will check the `ipset list` but it was fresh start just after bootstrap. I will try to modify entrypoint to execute this command before starting kube-proxy.

**Comment by islinwb** [comment]
@dawidmalina And you can try creating them manually to see the exact errors. (see https://github.com/kubernetes/kubernetes/issues/67292#issuecomment-412388013)

**Comment by islinwb** [comment]
@dawidmalina The issue you came cross seems different (`add` not `create`). And you can manually create these ipsets use `ipset add` to see the exact errors.

**Comment by dawidmalina** [comment]
I checked the output of such command:
```
ipset add KUBE-LOOP-BACK 10.10.0.6,tcp:443,10.10.0.6 -exist
ipset v6.29: Syntax error: 'tcp' is invalid as number
Syntax error: cannot parse 'tcp' as a protocol
```

Looks like it is somehow related with ipset version which is too old `v6.29` on Ubuntu 16.04.

I check the same command on new ubuntu 18.04 `v6.34` and it is working.

**Comment by m1093782566** [comment]
So, ipset version v6.34 is the current workable version?

@islinwb Can you send a PR to update the version check?

**Comment by cloudboss** [comment]
I experienced the same issue as @dawidmalina, but on 1.10.7 (new cluster). Running similar ipset commands to see the output gave the same error as well. Downgrading to 1.10.6 fixed it.

I'm running kube-proxy as a daemonset configured by kubeadm, using image `k8s.gcr.io/kube-proxy-amd64:v1.10.7`, and the version of ipset in the image is `v6.30`.

**Comment by cloudboss** [comment]
Correct, I watched the commands it was running by doing `wihle true; do ps -ef | grep [i]pset; done`, then tried running some of them, for example:

```
# ipset add KUBE-LOOP-BACK 10.0.0.2,tcp:8443,10.0.0.2 -exist
ipset v6.30: Syntax error: 'tcp' is invalid as number
Syntax error: cannot parse 'tcp' as a protocol
```

**Comment by dawidmalina** [comment]
What else i discover is somehow related to kube-proxy pod. When I run docker container manually even on ubuntu 16.04 with privileged mode all works. When I exec to kube-proxy with same base image it will not work.

**Comment by islinwb** [comment]
@dawidmalina  @cloudboss  Let's clarify it:  the error occured when you deploy kube-proxy as _daemonset pod_ not process? Did you try `ipset add` commands on the node and/or exec into the pod?

**Comment by Lion-Wei** [comment]
I think https://github.com/kubernetes/kubernetes/issues/68560 is related. 
Is this because ipset in debian-iptables v10.1 image might have some issue?

**Comment by dawidmalina** [comment]
Yes, we run kube-proxy as daemonset. I didn't try `ipset add` command on the node but all my test were made on the container via `docker exec`.

**Comment by cloudboss** [comment]
I'm also running kube-proxy as a daemonset and I ran all commands inside the container, not the node.

**Comment by islinwb** [comment]
Since this issue's for `ipset create` problem not `ipset add` and the causes are different, I'll create a new issuse.
