### ISSUE TITLE
Short name for describe

### ISSUE THREAD

**Issue by vikramkhatri** [kubernetes/kubernetes#67305]
Feature request:

Can you please provide short name for `describe` as `desc`? This will save 4 less letters to type in many `kubectl` commands? 

I already use alias `k` for `kubectl`, `kc` for `kubectl -n kube-system` and `ki` for `kubectl -n istio-system`. For people like me who type with 2 fingers, short names are very helpful.

Thank you.

**Comment by nikhita** [comment]
Closing this issue based on comments in https://github.com/kubernetes/kubernetes/pull/67336#discussion_r209601608. Please reopen if needed.

> Currently we don't use aliases for subcommands. We use aliases for resources instead.

> I agree with what was said before. I don't want to introduce additional layer of confusion as we refactor the code. So no aliases (for now).

If we decide to support aliases for subcommands later, IMO it should go in as a dedicated issue.

/close
