### ISSUE TITLE
The pod still be secheduled on NotReady pods after evicted

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#67300]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I was using k8s 1.11.1 with 1 master nodes and 2 worker nodes, and I create a deployment and the pods was deployed on one of master node, then I shutdown the worker node which have my workload which just deployed, after wait for about 5m, the pod will be evicted by taint_manager, but the new pod still scheduler on this off node.
```
I0811 13:56:30.660917       1 taint_manager.go:111] NoExecuteTaintManager is deleting Pod: default/nginx-64f497f8fd-46g9x
I0811 13:56:30.661192       1 event.go:221] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-64f497f8fd-46g9x", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'TaintManagerEviction' Marking for deletion Pod default/nginx-64f497f8fd-46g9x
I0811 13:56:30.670058       1 replica_set.go:477] Too few replicas for ReplicaSet default/nginx-64f497f8fd, need 1, creating 1
I0811 13:56:30.681793       1 event.go:221] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"nginx-64f497f8fd", UID:"6973f5c1-9d24-11e8-a443-fa163e191c71", APIVersion:"apps/v1", ResourceVersion:"73680", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: nginx-64f497f8fd-2qbth
```
from the log we can see that the pod was evicted by taint manager and will recreate the new one.

but the new one still schedule on the failure node like below:
```
root@hchenxa-2:~# kubectl  get pods -owide
NAME                     READY     STATUS        RESTARTS   AGE       IP           NODE
nginx-64f497f8fd-2qbth   0/1       Pending       0          4m        <none>       9.111.255.45
nginx-64f497f8fd-46g9x   1/1       Terminating   0          8h        10.1.104.3   9.111.255.45
```

The pod with `Terminating` status was just evicted, and we can see that the New pod still be scheduled.

**What you expected to happen**:
when the node was NotReady, after evict, the new pod should be created on other available node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
should be fixed by https://github.com/kubernetes/kubernetes/pull/63471

**Comment by liqlin2015** [comment]
The code here https://github.com/kubernetes/kubernetes/pull/63471/files#diff-43035107687eb30550696751ac1066e4R91 replies on node condition status. And we will try to match the condition status to decide whether add noschedule taint for node https://github.com/kubernetes/kubernetes/pull/63471/files#diff-43035107687eb30550696751ac1066e4R461

When I shutdown kubelet and docker service, the node did go to `NotReady` status, but only `NoExecute` taint created.

```
Taints:             node.kubernetes.io/unreachable:NoExecute
```

Also I noticed the node condition in this case is `Unknown`.

```
Taints:             node.kubernetes.io/unreachable:NoExecute
Unschedulable:      false
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                    Message
  ----             ------    -----------------                 ------------------                ------                    -------
  OutOfDisk        Unknown   Tue, 14 Aug 2018 00:12:20 -0700   Tue, 14 Aug 2018 00:13:03 -0700   NodeStatusUnknown         Kubelet stopped posting node status.
  MemoryPressure   Unknown   Tue, 14 Aug 2018 00:12:20 -0700   Tue, 14 Aug 2018 00:13:03 -0700   NodeStatusUnknown         Kubelet stopped posting node status.
  DiskPressure     Unknown   Tue, 14 Aug 2018 00:12:20 -0700   Tue, 14 Aug 2018 00:13:03 -0700   NodeStatusUnknown         Kubelet stopped posting node status.
  PIDPressure      False     Tue, 14 Aug 2018 00:12:20 -0700   Mon, 30 Jul 2018 02:07:51 -0700   KubeletHasSufficientPID   kubelet has sufficient PID available
  Ready            Unknown   Tue, 14 Aug 2018 00:12:20 -0700   Tue, 14 Aug 2018 00:13:03 -0700   NodeStatusUnknown         Kubelet stopped posting node status.
```

I think that's reason why `NoSchedule` taint was not there.

**Comment by liqlin2015** [comment]
cc @ceshihao

**Comment by ceshihao** [comment]
I think #63471 is only on 1.12+.

**Comment by ceshihao** [comment]
@liqlin2015 

For `Unknown` status which is described in comments.
> "ConditionUnknown" means kubernetes can't decide if a resource is in the condition or not.

In your case, it looks like kubernetes cannot decide whether the node is ready or not for some reason.

https://github.com/kubernetes/kubernetes/blob/c582a37cae02b4d1a850e6668ea8ea0a81dcd204/staging/src/k8s.io/api/core/v1/types.go#L2186-L2194

**Comment by liqlin2015** [comment]
Well as you seen from my above append, I just shut down docker and kubelet on my worker node to simulate the host was down. We should not let scheduler still schedule pod to such node.

As for node condition `ConditionUnknown`, we do triggered pod eviction. Why not mark the node as noschedulable?

By the way, in what condition the Node ready condition would be `ConditionFalse`.

**Comment by liqlin2015** [comment]
Found some discussion https://github.com/kubernetes/kubernetes/issues/58635 here.

**Comment by liqlin2015** [comment]
Just verified and checked the code. It seems we cannot have two taints with different effect on a node. For example, `node.kubernetes.io/not-ready:NoSchedule` and `node.kubernetes.io/not-ready:NoExecute`.

**Comment by Huang-Wei** [comment]
#67734 should be able to resolve this issue.
