### ISSUE TITLE
kubectl not able to pull the image from private repository

### ISSUE THREAD

**Issue by janwendt** [kubernetes/kubernetes#67304]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
kubectl not able to pull the image from private repository.

**What you expected to happen**:
kubectl pulls the image from my private repository .

**How to reproduce it (as minimally and precisely as possible)**:
Create a secret:
`kubectl create secret docker-registry my-secret --docker-server=192.168.99.100:5000 --docker-username=admin --docker-password=XXXX --docker-email=test@xyz.com`

pod.yaml:
`---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  volumes:
    - name: "datadir"
      hostPath:
        path: "/c/Data"
  containers:
    - name: test
      image: 192.168.99.100:5000/test
      ports:
        - containerPort: 80
      volumeMounts: 
        - mountPath: /root/Data
          name: "datadir"
  imagePullSecrets:
    - name: my-secret`

create "test" pod:
`kubectl create -f pod.yaml`

results in:
`Error from server (BadRequest): container "test" in pod "test" is waiting to start: trying and failing to pull image`
and `kubectl get pods` shows "ImagePullBackOff"

the image is definitely pushed to the private registry. I have checked it with:
`docker pull 192.168.99.100:5000/test` 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration: minikube (local)
- OS (e.g. from /etc/os-release): Windows 10 with boot2docker (Docker Toolbox)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by janwendt** [comment]
Forgot to start minikube with:  
`minikube start --vm-driver=virtualbox --insecure-registry="192.168.99.100:5000"`

**Comment by heenasejwal216** [comment]
what if my image is from ecr private registry? what host and port i can mention here. can anybody please help here
