### ISSUE TITLE
kubeadm set repo, kubelet still getting k8s.gcr.io/pause:3.1

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/kubernetes#67303]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
I set kubeadm init config with repo of my own container repo `imageRepository: xxx `, `kubeadm config images pull --config ./kubeadm-init.yaml` 
```
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
xxx/kube-proxy-amd64                v1.11.2             46a3cd725628        3 days ago          97.8 MB
xxx/kube-apiserver-amd64            v1.11.2             821507941e9c        3 days ago          187 MB
xxx/kube-controller-manager-amd64   v1.11.2             38521457c799        3 days ago          155 MB
xxx/kube-scheduler-amd64            v1.11.2             37a1403e6c1a        3 days ago          56.8 MB
xxx/coredns                         1.1.3               b3b94275d97c        2 months ago        45.6 MB
xxx/etcd-amd64                      3.2.18              b8df3b177be2        4 months ago        219 MB
xxx/pause                           3.1                 da86e6ba6ca1        7 months ago        742 kB
```
And I found kubelet was still getting k8s.gcr.io/pause:3.1

```
Aug 11 22:26:19 developing kubelet[69938]: I0811 22:26:19.735632   69938 server.go:460] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-developing", UID:"42276b81f46917e6c8b69150b4019aa3", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedCreatePodSandBox' Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": Error response from daemon: Get https://k8s.gcr.io/v1/_ping: dial tcp 108.177.97.82:443: i/o timeout
```

**What you expected to happen**:

I hope kubeadm could overwrite default kubelet sandbox container image (kubelet flag  --pod-infra-container-image)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig kubeadm

**Comment by neolit123** [comment]
dup of this:
https://github.com/kubernetes/kubernetes/pull/66219

PR is WIP:
https://github.com/kubernetes/kubernetes/pull/66798

/sig cluster-lifecycle
/close
