### ISSUE TITLE
Please add / create an official image of docker, which will contain Kubernetes kubectl client.

### ISSUE THREAD

**Issue by patsevanton** [kubernetes/kubernetes#67309]
Hello!
Please add / create an official image of docker, which will contain Kubernetes kubectl client.
Thanks!

**Comment by darshanime** [comment]
Not sure if this considered official official: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kubectl

**Comment by patsevanton** [comment]
@kubernetes/sig-apps-feature-requests
/sig apps

**Comment by jansmets** [comment]
There is Hyperkube
https://console.cloud.google.com/gcr/images/google-containers (search for hyperkube on top)

The only thing I'm personally missing is kubeadm so that this can be used to easily bootstrap a master node.
