### ISSUE TITLE
error: unable to upgrade: missing upgrade headers in request: 

### ISSUE THREAD

**Issue by chenqiangzhishen** [kubernetes/kubernetes#67329]
**What happened**:

I 'm in the progress of upgrading kubernetes from v1.9.3 to v1.11.1 in the current k8s cluster.

all k8s master components and kube-proxy run in docker container, kubelet runs in binary mode with systemd.

## upgrad steps:
- upgrade master  one by one with their components
- upgrade nodes one by one with their components
- etcd nodes keep unchanged

after upgrading k8s cluster in replace, I get nginx-hello pod running ok, but cannot run `kubectl exec` which complains with `error: unable to upgrade connection: unable to upgrade: missing upgrade headers in request: `

```bash
-[root@k8s-master-3 appuser]# kubectl -n cq-test get po -o wide
NAME                                      READY     STATUS    RESTARTS   AGE       IP               NODE
nginx-hello-deployment-5b476b8c7b-4zvph   1/1       Running   0          6m       172.12.137.117   10.130.14.67

-[root@k8s-master-3 appuser]# kubectl -n cq-test exec -it nginx-hello-deployment-5b476b8c7b-4zvph sh
error: unable to upgrade connection: unable to upgrade: missing upgrade headers in request: http.Header{"Connection":[]string{"close", "Upgrade", "close"}, "X-Forwarded-For":[]string{"10.130.14.63, 10.130.14.61, 10.130.14.61"}, "X-Stream-Protocol-Version":[]string{"v4.channel.k8s.io", "v3.channel.k8s.io", "v2.channel.k8s.io", "channel.k8s.io"}, "User-Agent":[]string{"kubectl/v1.11.1 (linux/amd64) kubernetes/b1b2997"}, "Content-Length":[]string{"0"}, "Upgrade":[]string{"SPDY/3.1"}}
```
**What you expected to happen**:

should run `kubectl exec` correctly and would login the pod.

**How to reproduce it (as minimally and precisely as possible)**:

run `kubectl exec`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```bash
-[root@k8s-master-3 appuser]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

private k8s cluster

- OS (e.g. from /etc/os-release):

```
-[root@k8s-master-3 appuser]# uname -a
Linux k8s-master-3.novalocal 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by chenqiangzhishen** [comment]
@kubernetes/sig-apiserver-bugs

**Comment by liggitt** [comment]
`"Connection":[]string{"close", "Upgrade", "close"}` is an odd connection header... are you running through a proxy?

**Comment by chenqiangzhishen** [comment]
everytime, I run `kubectl exec` it will pop up the following errors in kube-apiserver log.

```bash
E0816 10:31:20.524259       6 upgradeaware.go:310] Error proxying data from client to backend: read tcp 10.130.14.61:11070->10.13
0.14.61:54502: read: connection reset by peer
E0816 10:56:47.476514       6 upgradeaware.go:310] Error proxying data from client to backend: read tcp 10.130.14.61:11070->10.13
0.14.61:40576: read: connection reset by peer
```

maybe something else caused the issue, continue finding the root cause.

**Comment by chenqiangzhishen** [comment]
@caesarxuchao Do you have any suggestion about this issue? thx.

**Comment by peiqi-caicloud** [comment]
Hello, I got the same error: 
![screen shot 2018-08-21 at 4 28 43 pm](https://user-images.githubusercontent.com/5621794/44390214-561cbc00-a55f-11e8-9aad-4439907f7cdf.png)

I can use kubectl logs podName to see logs but can't logins using kubectl exec -it ...

**Comment by peiqi-caicloud** [comment]
@hustcat

**Comment by peiqi-caicloud** [comment]
note: I am using Haproxy and keepalived for master components.
