### ISSUE TITLE
apiserver can't talk to local etcd unless it is the leader

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#6734]
I am running Kubernetes 0.14.2 on CoreOS 607 cluster where three nodes run etcd and one of them is also a kubernetes master. In addition, I run a number of kubernetes minions that do not run etcd, but are configured to use the three etcd servers for, e.g., fleet.

When I bring up the cluster on AWS, the api-server cannot write to etcd (no /registry seen) and no minions are registered. Etcd otherwise works fine, as I can put keys and see them in the etcd cluster.

I noticed that the kubernetes master was not the etcd leader and therefore wanted to check whether making the kubernetes master the leader would help. I killed the current etcd leader and got the kubernetes master to become leader and, lo and behold, things suddenly worked.

**Comment by thockin** [comment]
Not sure who to assign this to.  @davidopp and master team FTW

**Comment by ArtfulCoder** [comment]
I made a change wherein kubernetes starts etcd with one instance only. this
etcd instance runs on the master. This one done because we want etcd
running only on localhost and we currently dont have another way of
securing etcd.
#6422

**Comment by ArtfulCoder** [comment]
#6559

**Comment by erimatnor** [comment]
Out of curiosity, why use a distributed and fault-tolerant key-value store like etcd if running only one instance on localhost? Also, making apiserver rely on a specific etcd setup seems to strongly tie Kubernetes to one specific way of setting up a cluster (i.e., with kubernetes kube-up.sh). This obviously makes things harder for those that run their own cluster configurations? Further, I don't understand why apiserver fails to make use of a distributed etcd cluster if instructed to, even if the default Kubernetes way is running a single instance on localhost? Currently, my cluster setup runs fine on Kubernetes 0.13.2, although that version suffers from a number of other shortcomings that 0.14.2 seems to solve (like having namespace-support for services' iptables rules).

**Comment by ArtfulCoder** [comment]
The first set of questions you asked around one instance of etcd are
discussed on #6559.
The other questions related to custom etcd cluster specification for
apiserver - that should have worked IIUC.

**Comment by erimatnor** [comment]
The other questions aside, it appears that something broke between 0.13.2 and 0.14.2 as the latter version doesn't work with multi-node etcd cluster.

**Comment by kelseyhightower** [comment]
@erimatnor I wonder if this has anything to do with the etcd version you are running. Based on your initial filing it seems your are running etcd 0.4.x, can you test with etcd 2.0.x? My guess is that you might be running into an issue with the version of go-etcd being used by k8s.

**Comment by yichengq** [comment]
This is because k8s is using go-etcd for etcd v2.0.(reference: https://github.com/coreos/go-etcd#usage) Because there is no need to do redirection for PUT requestse in etcd 2.0 cluster, go-etcd for etcd 2.0 doesn't do the redirection logic any more.

Here are two solutions:
1. suggest users always use etcd 2.0 for k8s
new user should use etcd 2.0 because etcd 2.0 runs better than etcd 0.4.
etcd 2.0 is actively developped and maintained.
2. use go-etcd for etcd 0.4
It is fine to support both 0.4 and 2.0
it has performance issues when running with etcd 2.0

Glad to send a PR if we go with option 2.

**Comment by davidopp** [comment]
I think it's fine to tell people they have to use 2.0. We probably don't want people using anything other than the latest etcd anyway (i.e. regardless of this particular issue).

**Comment by yichengq** [comment]
@erimatnor @ArtfulCoder any preference?

**Comment by mikedanese** [comment]
now that we support linearized reads, i don't think this is useful anymore.
