### ISSUE TITLE
device pugins should allow to set path uid

### ISSUE THREAD

**Issue by fabiand** [kubernetes/kubernetes#67340]
/kind bug

**What happened**:
Using a dp to bring a path into a container

**What you expected to happen**:
That I can controll what UID (user id) the ptah has inside the container

**How to reproduce it (as minimally and precisely as possible)**:
Take a path and bring it into a container using a dp

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
related to https://github.com/kubevirt/kubevirt/pull/1404

**Comment by rojkov** [comment]
Is this about setting UID on device nodes under `/dev`?

I guess this would require updating CRI because the current protocol doesn't know about UIDs
https://github.com/kubernetes/kubernetes/blob/v1.13.0-alpha.0/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L643

**Comment by fabiand** [comment]
Yep. This is about the UID of the device.

**Comment by fabiand** [comment]
This causes workarounds like
https://github.com/kubevirt/kubevirt/pull/1404/files#diff-b3ef56ef078f18d957e5de17857e8713R137
