### ISSUE TITLE
Kubenetes1.11  kubectl does not support csi  in Volume ?

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#67376]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

> /kind bug

**What happened**:
I create a pod like this:
`apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/www/html
         name: mydata
  volumes:
   - name: mydata
     csi:
       driver: "csi-xxxx"
       fsType: "ext4"
       volumeHandle: "xxxxxx`

**What you expected to happen**:
kubectl told me:

error: error validating "pod3.yaml": error validating data: ValidationError(Pod.spec.volumes[0]): unknown field "csi" in io.k8s.api.core.v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS 7.1
- Kernel (e.g. `uname -a`):4.1
- Install tools:
- Others:

@kubernetes/sig-storage-feature-requests @kubernetes/sig-storage-proposals

**Comment by wpf710** [comment]
it's not the attribute of volume,  you can create a pv/pvc with csi, and use it in pod

**Comment by kfox1111** [comment]
see https://github.com/kubernetes/community/pull/2273

**Comment by vladimirvivien** [comment]
Inline volume is being implemented for 1.13.  Please see https://github.com/kubernetes/kubernetes/pull/68232 to track progress.
