### ISSUE TITLE
kubernetes resources reservation(cpu hard limit) 

### ISSUE THREAD

**Issue by admssa** [kubernetes/kubernetes#67371]
/kind bug
I'm not sure this is a bug, but not one of the others
**What happened**:
 I  have ran kubelet with parameters:
```
--enforce-node-allocatable=pods \
--kube-reserved=cpu=6400m,memory=98358Mi,ephemeral-storage=5Gi
```
got limit for kubepods memmory: 
```
cat /sys/fs/cgroup/memory/kubepods/memory.limit_in_bytes
412547018752
```
got soft cpu limit:
```
cat /sys/fs/cgroup/cpu/kubepods/cpu.shares
58982
```
cfs quota haven't changed:
```
 cat /sys/fs/cgroup/cpu/kubepods/cpu.cfs_quota_us
-1
```
allocateble has changed:
```
Capacity:
 cpu:                64
 ephemeral-storage:  2064114848Ki
 memory:             503596540Ki
 pods:               500
Allocatable:
 cpu:                57600m
 ephemeral-storage:  1896919531648
 memory:             402775548Ki
 pods:               500
```
**What you expected to happen**:
I expectetd i will get cpu hard limit for kubepods cgroup

as it works for pods, for example:
```
cat /sys/fs/cgroup/cpu/kubepods/podb0085a01-9ed3-11e8-90bc-12642777bb76/cpu.cfs_quota_us
200000
```
Is it possible to use hard linit ? How exectly I can do this ?

**How to reproduce it (as minimally and precisely as possible)**:
  You can run kubelet with parameters above 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.8.5
- Cloud provider or hardware configuration:
AWS, but I'm not using cloud-provider flag
- OS (e.g. from /etc/os-release):
16.04.5 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`):
4.15.18-041518-generic #201804190330 SMP Thu Apr 19 07:34:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
ansible

**Comment by admssa** [comment]
I'm not sure this is a bug, but not one of any other
/sig bug

**Comment by tanshanshan** [comment]
IMO, if you use 

> --kube-reserved=cpu=6400m,memory=98358Mi,ephemeral-storage=5Gi

you also need config` kube-reserved` in 

> --enforce-node-allocatable=pods,kube-reserved

https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by admssa** [comment]
but I don't want to create some specific runtime for kube-reserved or limit it somehow.  I just want to limit kubepods. 

Anyway, it hasn't changed anything. I even tried with system-reserved and system cgroup. It changes cpu.shares only.

**Comment by admssa** [comment]
You can close the ticket, I have found out how does it work. 
It uses cpu.shares only
https://github.com/kubernetes/kubernetes/blob/b00b504f57c54af2610d97998fbc80acf971dbba/pkg/kubelet/cm/node_container_manager.go#L137
so I can't just limit 1 kubepods using kubelet, I will have to set some part of cpu to other cgroups. 
The best way to do this - set system-reserved and system-reserved-cgroup

**Comment by admssa** [comment]
/
