### ISSUE TITLE
Too many ESTABLISHED connection between kube-api and kubelet

### ISSUE THREAD

**Issue by soumypau1** [kubernetes/kubernetes#67382]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Too many ESTABLISHED connection to and from port no 10250
root@mil-dev-api-001:~# netstat -an | grep EST | grep 10250 | wc -l
30705
Eventually this is bringing down kubernetes

**What you expected to happen**:
Upto a few hundred connections

**How to reproduce it (as minimally and precisely as possible)**:

Install Kubernetes using kubeadm 
Remove the taint (Single server cluster)
helm init
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
install helm chart for ingress and registry

**Anything else we need to know?**:

**Environment**:  
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
VMWare VM with 12 vCPU and 28 GB RAM
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.5 LTS 
- Kernel (e.g. `uname -a`):
4.4.0-131-generic
- Install tools:
kubeadm
- Others:
[port-10250.txt](https://github.com/kubernetes/kubernetes/files/2286729/port-10250.txt)
[lsof-10250.txt](https://github.com/kubernetes/kubernetes/files/2286730/lsof-10250.txt)

**Comment by soumypau1** [comment]
@ChrisPhillips-cminion FYI

**Comment by neolit123** [comment]
/sig network
although, it's probably better to report at help first.

**Comment by soumypau1** [comment]
We have deployed the same set of applications on Kubernetes 1.10.6 and that seems to be working perfectly fine.

**Comment by grailsweb** [comment]
I am having same issue with v1.11.1 cluster. 3 master and 12 nodes. its restarting kube-apiserver pods

current connections on master node for port 10250:

master01: 10476
master02: 28041
master03: 10626

**Comment by timchenxiaoyu** [comment]
some problem . k8s v1.11.1

lsof  -P  -p  `pidof  kube-apiserver`  |    grep  k8s-253.215.xx.xx:10250  -c 
10199
