### ISSUE TITLE
Deleting jobs via the API leaves pods

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/kubernetes#67394]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Pods are being left behind after the job is deleted, with `propagationPolicy` set to `Foreground` or `Background`

**What you expected to happen**:

The pods should be deleted according to https://github.com/kubernetes/kubernetes/issues/20902

**How to reproduce it (as minimally and precisely as possible)**:

- create a job
- run the following python script with kubernetes-client installed (7.0.0b1 as this is the only client working with python 3)

```
import kubernetes
import pprint

kubernetes.config.load_kube_config()
pprint.pprint(api.delete_namespaced_job('test', 'default', {}, propagation_policy='Foreground'))
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pvanderlinden** [comment]
@kubernetes/sig-apps-bugs

**Comment by krmayankk** [comment]
@janetkuo has a proposal that might cover this /cc @caesarxuchao

**Comment by pvanderlinden** [comment]
Does this mean the feature in the original ticket never worked? How can I clean these pods currently, and are there other objects I need to cleanup (Is there some metadata I can look for which associate the pod with the job)?

**Comment by liggitt** [comment]
> @janetkuo has a proposal that might cover this

no, Janet's proposal is around collection of completed jobs

> Does this mean the feature in the original ticket never worked?

deletion of a job with `propagationPolicy=Foreground` is cleaning up the job's pods in my tests

**Comment by liggitt** [comment]
> That proposal sounds like I might be misusing jobs for what I'm doing at the moment, as this will break what I'm doing. 

It shouldn't change behavior by default. Deletion of completed jobs would likely be opt-in, and occur at a delayed interval after job completion, not instantly.

> That's strange, I tried several times to get this working, this might mean the python kubernetes client is not sending the right data?

Seems likely. Do you have the network trace of what the client is doing?

**Comment by pvanderlinden** [comment]
@liggitt How would I be able to get an usable network trace, the connection to the api server is SSL?

**Comment by pvanderlinden** [comment]
From just adding some logging, it looks like it does a DELETE request to the url `/apis/batch/v1/namespaces/default/jobs/test?propagationPolicy=Foreground` Which I think should be correct?

**Comment by liggitt** [comment]
are you sending a body? if the DELETE request has any body content, that is used instead of parameters (delete options can be submitted via query params or a serialized `DeleteOptions` object in the request body):

https://github.com/kubernetes/kubernetes/blob/4414ae3d7572ba85f36eb8661d2cb0e6171f6f57/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L67-L72

**Comment by pvanderlinden** [comment]
Thanks for the help! Turns out the python api makes it impossible (while providing the parameters), to use the query parameters, as it requires a valid JSON body. I will open a ticket for the client instead, if I send deleteOptions, everything works.
