### ISSUE TITLE
Kubelet uses ipv4 iptables in an ipv6-only cluster

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#67398]
/kind bug

**What happened**:

Kubelet uses "iptables" instead of "ip6tables" in an ipv6-only cluster. This causes failed traffic for `type: LoadBalancer` services (and probably a lot of other problems).

For instance the `KUBE-MARK-DROP` chain is created in `iptables` but is missing in `ip6tables`;

```
# ip6tables -t nat -S | grep KUBE-MARK-DROP
(nothing)
# iptables -t nat -S | grep KUBE-MARK-DROP
-N KUBE-MARK-DROP
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
```

When a `loadBalancerIP` is assigned the `kube-proxy` fails;
```
E0814 18:20:56.733818     227 proxier.go:1306] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.6.2: Couldn't load target `KUBE-MARK-DROP':No such file or directory
```

**What you expected to happen**:

All components should use `ip6tables` in a ipv6-only cluster.

`loadBalancerIP` should work in an ipv6-only cluster.

**How to reproduce it (as minimally and precisely as possible)**:

* Start a ipv6-only cluster
* Check iptables
* Optional; try a service type: LoadBalancer

**Anything else we need to know?**:

`ProtocolIpv4` is hard-coded in finc `NewMainKubelet` in "kubelet.go"

```
iptClient: utilipt.New(utilexec.New(), utildbus.New(), utilipt.ProtocolIpv4),
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-09T07:12:03Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-09T07:12:03Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
kvm VMs on Ubuntu 16.04
- OS (e.g. from /etc/os-release):
Own BusyBox system
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux vm-003 4.17.13 #1 SMP Thu Aug 9 09:27:42 CEST 2018 x86_64 GNU/Linux
```
- Install tools:
None
- Others:

**Comment by Lion-Wei** [comment]
Thanks for reporting this problem.

**Comment by uablrek** [comment]
[here](https://github.com/kubernetes/kubernetes/blob/cfb4a5e95afa2d3b79883cff816aff0f019069aa/pkg/kubelet/kubelet.go#L518) is a link to the code with the hard-coded ipv4 protocol.

**Comment by Lion-Wei** [comment]
@uablrek Thanks, I will send a pr to fix this issue.

**Comment by pmichali** [comment]
I see this issue too. Also there is some related discussion with issue #65006.

**Comment by pmichali** [comment]
@Lion-Wei I just pulled the latest from master, and gave a try with IPv6 cluster, but I still see the error, when using kube-proxy + IPVS:

E0829 16:51:56.224911       1 proxier.go:1136] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.4.21: The protocol family of set KUBE-LOOP-BACK is IPv4, which is not applicable.

Were you able to try this with kube-proxy+IPVS?

**Comment by Lion-Wei** [comment]
@pmichali Sorry, I didn't try ipv6 cluster with ipvs proxier. Those two issue are related, but not exactly the same issue. 
Seems we already have conclusion in https://github.com/kubernetes/kubernetes/issues/67799, nobody working on that?
