### ISSUE TITLE
Enable Flex Volume Drivers to support metrics

### ISSUE THREAD

**Issue by brahmaroutu** [kubernetes/kubernetes#67400]
kind feature

**What happened**:
Currently there is no mechanism to report metrics as the flex plugins are not enabled to collect metrics. All flex volumes lack this feature as compared to in-tree/built-in drivers even though it is possible to collect such metrics for most of the plugins.

**What you expected to happen**:
Depending on the availability of the metrics from the mounted FS, flex plugins should allow to report metrics for the FS.

**How to reproduce it (as minimally and precisely as possible)**:
The default behavior that can be proved easily by just running a command similar to the following command on a node that is running a flex volume. This will show that there are no metrics collected for flex volumes.
kubectl proxy  
$curl 127.0.0.1:8001/api/v1/nodes/<IP>/proxy/stats/summary**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: local x86
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux KubeStorage 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:
/sig storage

**Comment by sikhlaqu** [comment]
+1
Yes, it will be good, if flex volume can support atleast the default metrics( i.e pkg/volume/metrics_statfs.go), which most of the volume plugins support now. 
         Based upon flex plugin "capabilities" parameters, it can be decided, whether the plugin supports "default metrics" or "nil metrics".
