### ISSUE TITLE
How can k8s cluster use the etcd services when the two clusters in different machines.

### ISSUE THREAD

**Issue by zoux86** [kubernetes/kubernetes#67429]
Question:  i have a kubernetes cluster in four ubuntu machines, and have a etcd cluster in another three machines。i want the kubernetes cluster use etcd services, but it doesnot work。i google the question, but 
still have wrong。 is someone knows how to get it? sorry for my poor english.

**Comment by zoux86** [comment]
Thank you for your advice!  @tanshanshan 
in k8s cluster, i run the "kubectl get nodes" command, it works well.
and in etcd cluster, i run the "etcdctl member list " command, it also works well.

but when i run " systemctl start etcd" in k8s cluster。it goes wrong!
![image](https://user-images.githubusercontent.com/14087435/44182169-4c96ec80-a138-11e8-9a9b-a02c9b373cc0.png)

apiservice config:
###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The address on the local server to listen to.
KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"

# The port on the local server to listen on.
KUBE_API_PORT="--port=8080"

# Port minions listen on
KUBELET_PORT="--kubelet-port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://192.168.13.95:2379,http://192.168.13.101:2379,http://192.168.13.40:2379"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota"

# Add your own!
KUBE_API_ARGS=""
~                                                                                                                                     
~                               

my apiserver config is above!
 i had KUBE_ETCD_SERVERS  linked to etcd cluster. i am not sure there are other config i should modify?

**Comment by tanshanshan** [comment]
in your picture

see

> status=2/INVALIDARGUMENT 

maybe you can check whether your etcd config is correct.

**Comment by zoux86** [comment]
the k8s cluster in 4 machines, and the master machines has a wrong etcd config.
but in another three machines, i have a correct etcd cluster.
i want the k8s cluster use the correct etcd cluster。but it seems to not work.

**Comment by dims** [comment]
can you please try the etcd folks? https://github.com/coreos/etcd/issues

/close
