### ISSUE TITLE
Accounts with list but not get permission are able to retrieve secrets

### ISSUE THREAD

**Issue by dangoldin** [kubernetes/kubernetes#67420]
/kind bug

**What happened**:
Came across a security issue on the dashboard that looks to be a bug on the API side. The issue is that the list permission exposes the secrets even if the get permission is not set. The details were discovered by @ewok2030 here: https://github.com/kubernetes/dashboard/issues/2798#issuecomment-379052678

**What you expected to happen**:
When a user only has the list permission they should not be able to see the secrets.

**How to reproduce it (as minimally and precisely as possible)**:
Check out the curl requests in https://github.com/kubernetes/dashboard/issues/2798#issuecomment-379052678

**Anything else we need to know?**:
Not as far as I can tell.

**Environment**:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yue9944882** [comment]
hi @dangoldin i suppose you should revoke `list` permission too :)

**Comment by dangoldin** [comment]
@yue9944882 - yea the problem is that I want people to see the available secrets that the application needs so they can make sure to have them inside their docker compose but I don't want them to have access to the production secrets.

**Comment by Miouge1** [comment]
People don't need permissions to secrets to access the dashboard. From what I have tested it just throws a warning like `secrets is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list secrets in the namespace "default"` but things still work except for viewing and listing secrets.
