### ISSUE TITLE
psp/adminsioncontroller- take the intersection of user and serviceaccount for PodSecurityPolicy authorization 

### ISSUE THREAD

**Issue by lidajia** [kubernetes/kubernetes#67424]
I want to ask some questions about PodSecurityPolicy  authorization.
PodSecurityPolicy authorization uses the union of all policies available to the user creating the pod and the service account specified on the pod. When superuser was used, requests would bypass authentication and authorization modules, all PodSecurityPolicy objects would be allowed, and users would be able to create privileged containers. Is it possible to  take the intersection of user rights and serviceaccount rights for PodSecurityPolicy authorization. I also not understand why authorized user was adding to PodSecurityPolicy authorization?

/kind feature
@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
> PodSecurityPolicy authorization uses the union of all policies available to the user creating the pod and the service account specified on the pod. 

Correct

> When superuser was used, requests would bypass authentication and authorization modules, all PodSecurityPolicy objects would be allowed, and users would be able to create privileged containers.

This allows the superuser to create pods based on any PodSecurityPolicy, not other users. 

>  Is it possible to take the intersection of user rights and serviceaccount rights for PodSecurityPolicy authorization. 

That is not possible. 

> I also not understand why authorized user was adding to PodSecurityPolicy authorization?

To allow a privileged controller to create privileged pods in a namespace while restricting the ability of unprivileged users to create privileged pods.
