### ISSUE TITLE
Expose pod IPs and ports in DNS SRV records

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#6743]
I am running a frontend L7 request router / load balancer that maintains persistent TCP connections to replicated backend services (i.e., for each service the frontend has N connections to N instances of that service). The Kubernetes service abstraction doesn't seem to fit this scenario, since it relies on transparently balancing requests across backend replicas by exposing a single proxy IP. 

What I'd really like is a way to simply resolve the pod IPs of a service via, e.g., DNS SRV records. However,  the kube2sky bridge in the official DNS addon doesn't seem to be adding SRV records to DNS (although SRV is mentioned as supported in the docs). Is there some reason why kube2sky isn't populating DNS with Pod IPs (as SRV records) in addition to the DNS name for the portal IP?

**Comment by thockin-cc** [comment]
Please see #6666 for an emerging design.

**Comment by thockin** [comment]
Do you want the single portal IP at all?  This feels like you want a "headless" service and DNS for it that returns multiple A records.  What SRV query are your doing?  Are you asking for _something._tcp.your-service.namespace or something else?

**Comment by erimatnor** [comment]
Headless services would probably do for now, although proper SRV records (e.g., _something._tcp.your-service.namespace) would be preferable. SRV would be more powerful and allow better support for multiple protocols, ports, weights, etc. I guess one issue is where to get things like weights from? I imagine that one could optionally support that via some extended liveness check akin to what is already available in Kubernetes. For instance, the HTTP GET you specify in the pod resource could (optionally) return some standard format JSON that your service implements, containing stats that can be used for weights.

**Comment by thockin** [comment]
As of two weeks we have support for headless services DNS and as of last
week we have support for SRV. Try it out!

**Comment by erimatnor** [comment]
Great! Will do.

**Comment by bgrant0607** [comment]
Obsolete
