### ISSUE TITLE
Migrate ServiceAccountAdmissionController to token projection

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#67440]
This issue is mostly to gather my notes. We need to complete a set of tasks to phase out the old service account token secrets. We'll have to complete these tasks over the course of a multiple release timeline in order to comply with our deprecation policy.

Breaking changes:
1. service account token will need to be reloaded
1. service account secrets will no longer be created automatically

Tasks:
1. InClusterConfig and tokenfile config needs to reload credentials periodically.
1. ServiceAccountAdmissionController needs to use a ProjectedVolume instead of a SecretVolume.
1. We need to figure out what to do about the CA.crt. (???)
1. TokenController needs to be turned down.

/sig auth

@liggitt @smarterclayton

**Comment by mikedanese** [comment]
We have some other backwards incompatible changes to service accounts that we've considered. From memory:
1. move service accounts to authentication API group
1.Change automount to default to off

It might make sense to do some of these at the same time to batch turnover.

**Comment by WanLinghao** [comment]
@mikedanese  hello, do we have any new progress about this issue?

**Comment by mikedanese** [comment]
This is done, we just need to do the rollout.

**Comment by mhprowler** [comment]
Which k8s release will this be in? Thanks
