### ISSUE TITLE
one flexvolume bug: getvolumename is not used

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/kubernetes#67467]
/kind bug
/sig storage
@Saad Ali

**What happened**:
i will develop a flexvolume driver,when i implement the interface getvolumename,i found the volume name is not mine.so i find the code of kubelet,i find the kubelet has not use my volume name,this is a bug.

**What you expected to happen**:
i think kubelet should use the volume name like this sequence: 
1)use the user have implemeted.
2)if user do not implemeted the getvolumename,then use volume's name.

**How to reproduce it (as minimally and precisely as possible)**:
implement the flexvolume's interface getvolumename,then create pod,you will find the pod's volume name is not used.

**Anything else we need to know?**:
the kubelet code:

func (plugin *flexVolumePlugin) GetVolumeName(spec *volume.Spec) (string, error) {
	call := plugin.NewDriverCall(getVolumeNameCmd)
	call.AppendSpec(spec, plugin.host, nil)
        _, err := call.Run()        // do not use the user's volume name
	if isCmdNotSupportedErr(err) {
		return (*pluginDefaults)(plugin).GetVolumeName(spec)
	} else if err != nil {
		return "", err
	}
	name, err := (*pluginDefaults)(plugin).GetVolumeName(spec)
	if err != nil {
		return "", err
	}
	glog.Warning(logPrefix(plugin), "GetVolumeName is not supported yet. Defaulting to PV or volume name: ", name)
	return name, nil
}

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: no
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)

**Comment by xiaoxubeii** [comment]
```
// GetVolumeName returns the name/ID to uniquely identifying the actual
// backing device, directory, path, etc. referenced by the specified volume
// spec.
// For Attachable volumes, this value must be able to be passed back to
// volume Detach methods to identify the device to act on.
// If the plugin does not support the given spec, this returns an error.
GetVolumeName(spec *Spec) (string, error)
```
Reference the comment in volume/plugins.go, I think `GetVolumeName` is just used to identity actual backing volume for attach or detach, it is not used for pod volume name.

**Comment by shigy123456** [comment]
i know it is not used for pod volume name.
my problem is i defined my own name,the flexvolume is not used.

**Comment by wgliang** [comment]
@xiaoxubeii @shigy123456 I will submit a PR on the issue, you can checkout it.
/assign
