### ISSUE TITLE
Admission webhook doesn't allow service to use a port that is not 443

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#67468]
/kind bug

When the kubeapiserver constructs the client for talking to the admission webhook, it [always use port 443](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/config/client.go#L134-L142) when constructing from [ServiceRef](https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L269-L281)

/sig apimachinery

**Comment by mengqiy** [comment]
cc @caesarxuchao

**Comment by xiaoxubeii** [comment]
Indeed, it just support https.

**Comment by lavalamp** [comment]
/assign @caesarxuchao 

to find the bug this is a dup of

**Comment by caesarxuchao** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/61510.

The support for 443 is documented: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L257 (thanks to @jennybuckley for fixing the document).

Please reopen if there are other things we can fix.
