### ISSUE TITLE
Inconsistent docs on podAffinity empty namespace list

### ISSUE THREAD

**Issue by glasser** [kubernetes/kubernetes#67475]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I was reading the docs about pod affinity and wanted to understand how to ensure podAntiAffinity applies across namespaces.

The concepts docs at https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ says:
> In addition to labelSelector and topologyKey, you can optionally specify a list namespaces of namespaces which the labelSelector should match against (this goes at the same level of the definition as labelSelector and topologyKey). If omitted, it defaults to the namespace of the pod where the affinity/anti-affinity definition appears. If defined but empty, it means “all namespaces”.

The API reference under PodAffinityTerm at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podaffinityterm-v1-core says:
> namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means "this pod's namespace"

ie, the former says that the empty list means "all namespaces" and the latter says that the empty list means "this pod's namespace".

I am not yet sure which one is right, but surely only one of them can be.

**What you expected to happen**:

I expected the docs to be consistent with each other (and ideally with the implementation too, whatever that turns out to be :) )

**How to reproduce it (as minimally and precisely as possible)**:

Read the docs and see that they disagree with each other.  Or OK, set up a cluster with two pods in different namespaces with podAntiAffinity with `namespaces: []` and see if they can get scheduled on the same node or not. But I'm still just at the "docs are inconsistent" stage.

**Anything else we need to know?**:

No.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.6-gke.2 (but this applies to the current 1.10 docs, not my personal Kubernetes)
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Container-Optimized OS
- Kernel (e.g. `uname -a`): 4.4.111+
- Install tools:
- Others:

**Comment by glasser** [comment]
@kubernetes/sig-docs-bugs @kubernetes/sig-api-machinery-bugs @kubernetes/sig-scheduling-bugs

**Comment by davidopp** [comment]
I believe we got rid of "all namespaces" for performance/scalability reasons. @wojtek-t or @kevin-wangzefeng might remember. (I wasn't able to find the relevant PR in a quick search.)

**Comment by glasser** [comment]
Here's a docs PR: https://github.com/kubernetes/website/pull/9876

**Comment by glasser** [comment]
My doc PR was merged, so I should probably close this, even though it would still be nice to have the all-namespaces behavior accessible some way. But that's a feature request, not a bug.
