### ISSUE TITLE
kubectl delete pods hang

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#67479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I was trying to use `kubectl` to delete all pods from `kube-system` namespace with the command `kubectl delete pods -n kube-system --all`, after execute the commands, the command hang at the last pod delation.

**What you expected to happen**:

The command should be finished.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
delete waits for the objects to be removed. pod deletion is initiated by kubectl in this case, but waits for the node running the pod to kill the process and do the final delete via the API.

You can force deletion and short-circuit that by passing `--force --now`, or skip waiting with `--wait=false`

**Comment by liggitt** [comment]
this isn't related to cascading deletion, this is ensuring the object you deleted is actually removed before returning, so a subsequent `create` call in a script would not receive an `AlreadyExists` error

**Comment by leakingtapan** [comment]
I had similar experience on deleting a pv. The deletion just hangs till I delete the pvc from a separate console. This experience is kinda confusing to me.
