### ISSUE TITLE
Unable to mount volumes for pod on AWS

### ISSUE THREAD

**Issue by hyprnick** [kubernetes/kubernetes#67473]
/kind bug
/sig storage

**What happened**:
Kubernetes failing to mount volumes
```
Events:
  Type     Reason                  Age   From                                                 Message
  ----     ------                  ----  ----                                                 -------
  Normal   Scheduled               3m    default-scheduler                                    Successfully assigned default/zookeeper-0 to ip-10-128-36-71.us-east-2.compute.internal
  Normal   SuccessfulAttachVolume  3m    attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-d90ec1ac-9fdd-11e8-9588-02b31576b438"
  Warning  FailedMount             1m    kubelet, ip-10-128-36-71.us-east-2.compute.internal  Unable to mount volumes for pod "zookeeper-0_default(fd14c086-a105-11e8-b59a-02c1a2b7dfa6)": timeout expired waiting for volumes to attach or mount for pod "default"/"zookeeper-0". list of unmounted volumes=[data]. list of unattached volumes=[data default-token-cv4d4]
```

**What you expected to happen**:
Mounting to succeed.  

**How to reproduce it (as minimally and precisely as possible)**:
Start a stateful set on an AWS node c5d. Also using the gp2 EBS provisoner. 

**Anything else we need to know?**:
This may be related to the EBS volumes being exposed as an NVMe block device.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`AWS`

- OS (e.g. from /etc/os-release):
`Debian GNU/Linux 8 (jessie)`

- Kernel (e.g. `uname -a`):
`Linux ip-10-128-36-71 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux`

- Install tools:
`kops Version 1.10.0 (git-8b52ea6d1)`

**Comment by danilorsilva** [comment]
I have a problem on my k8s cluster using AWS `c5` family. We need to use stretch debian image as default to work with the disks and everything work perfectly. i don't know if will solve your problem, but you should try, because old debian images on k8s don't know how to work correctly with NVMe. Another option is a downgrade on your instace type to use AWS `4` family... (c4,m4,etc...)

**Comment by hyprnick** [comment]
@danilorsilva Thanks! This is an issue with the image.

**Comment by hyprnick** [comment]
For anyone else who finds this helpful - I found the following image to work on AWS for NVMe instance types (c5d, m5d, etc) along with the aws cni plugin:

`kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17`

**Comment by baltendo** [comment]
For k8s 1.10 I fixed the issue by using this images `kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-05-27`. It seems that there are newer images available but it did only work with this one.

**Comment by ObviousDWest** [comment]
For those considering upgrades, I did a little digging. As of today:
- "latest" kops version is 1.10.0, would upgrade k8s to 1.10.6, and uses the image:
    k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17 image (not stretch).
- kops 1.11.0-alpha.1 version upgrades k8s to 1.11.2 and uses the image:
    kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
