### ISSUE TITLE
Scalability: A test failure in one test suite can break tests in other tests

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#67488]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-performance-regional/132 failed to start leaving a 2k cluster running in kubernetes-scale project.

This has broken two 5k nodes attempts:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/194
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/193

/sig scalability
/cc @shyamjvs 
/assign

**Comment by shyamjvs** [comment]
This is happened few times in past as well and I was manually cleaning up the project in such cases. While there are few ways we can hack around this problem, I think the proper way to solve this is by splitting GCE and GKE tests to separate projects (as discussed in the capacity-planning doc I had earlier shared).

**Comment by shyamjvs** [comment]
/remove-lifecycle stale

Leaving open for any potential updates.
