### ISSUE TITLE
watch the kubectl changes will be exit after a while

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#67491]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I use `kubectl get pods -n kube-system -lapp=nginx -w` to watch the changes of pods, but the command will exited after run for a while(may be 5~10 minutes), from my point of view, the command should not be exited if I did not cancel my request.

**What you expected to happen**:
the command should not exited
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
> --min-request-timeout=1800: An optional field indicating the minimum number of seconds a handler must keep a request open before timing it out. Currently only honored by the watch request handler, which picks a randomized value above this number as the connection timeout, to spread out load.

it's designed.
/remove-kind bug
/triage support
