### ISSUE TITLE
User "system:kube-controller-manager" cannot patch nodes at the cluster scope

### ISSUE THREAD

**Issue by johanot** [kubernetes/kubernetes#67516]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig auth

**What happened**:

When I start kube-controller-manager in a newly created RBAC-enabled cluster, I get:

```
kube-controller-manager[744]: E0816 21:04:49.288384744 range_allocator.go:320] 
CIDR assignment for node machine1.my.zyx failed: failed to patch node CIDR: 
nodes "machine1.my.zyx" is forbidden: 
User "system:kube-controller-manager" cannot patch nodes at the cluster scope.
Releasing allocated CIDR
```

**What you expected to happen**:

I expect the clusterrole `kube-controller-manager` to have permissions to patch nodes? But apparently it never gets that as part of RBAC bootstrap?

**How to reproduce it (as minimally and precisely as possible)**:
* RBAC-enabled cluster
* kube-controller-manager and kube-apiserver as separate system units
* TLS-enabled communication between controller-manager and apiserver
* Enable the CIDR-allocator and fire up kube-controller-manager

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): *v1.10.5*
- Cloud provider or hardware configuration: Self-hosted
- OS (e.g. from /etc/os-release): NixOS 18.03
- Kernel (e.g. `uname -a`): Linux 4.14.62

**Comment by liggitt** [comment]
The controller manager only has sufficient permissions to launch the individual controller loops. Those are intended to be run with individual service accounts, each of which has an isolated role granted. 

To run in this mode, ensure the controller manager is started with `--use-service-account-credentials`

See https://kubernetes.io/docs/reference/access-authn-authz/rbac/#controller-roles for details

/close

**Comment by johanot** [comment]
TIL. Thanks!
