### ISSUE TITLE
Deployment is not completely removed

### ISSUE THREAD

**Issue by orsobruno** [kubernetes/kubernetes#67515]
/kind bug

**What happened**:
I've deployed **kube-state-metrics**, but I have only single node which is also used as master. The node has taint "node-role.kubernetes.io/master="":NoSchedule" and yaml file of deployment did not contain toleration. Accordingly, a pod created by ReplicaSet from the deployment could not start. Then i added toleration to the spec.template.spec and called "kubectl replace -f ...". It's the full config:

<pre>apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
    name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kube-state-metrics
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      containers:
      - args:
        - --secure-listen-address=:8443
        - --upstream=http://127.0.0.1:8081/
        image: quay.io/coreos/kube-rbac-proxy:v0.3.1
        name: kube-rbac-proxy-main
        ports:
        - containerPort: 8443
          name: https-main
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --secure-listen-address=:9443
        - --upstream=http://127.0.0.1:8082/
        image: quay.io/coreos/kube-rbac-proxy:v0.3.1
        name: kube-rbac-proxy-self
        ports:
        - containerPort: 9443
          name: https-self
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        image: quay.io/coreos/kube-state-metrics:v1.3.1
        name: kube-state-metrics
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=2m
        - --memory=150Mi
        - --extra-memory=30Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/coreos/addon-resizer:1.0
        name: addon-resizer
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-state-metrics</pre>

As a result, there were 2 replica sets, but new one did not start. Then i deleted the deployment and called "kubectl create -f ..." again.

<pre>$ kubectl get rs --all-namespaces
NAMESPACE       NAME                                 DESIRED   CURRENT   READY     AGE
monitoring      kube-state-metrics-79b8675776        1         1         1         9s
</pre>

<pre>$ kubectl rollout history deployment/kube-state-metrics -n monitoring
deployments "kube-state-metrics"
REVISION  CHANGE-CAUSE
1         kubectl create --filename=manifests/kube-state-metrics-deployment.yaml --record=true --save-config=true</pre>

Everything looked good, but then a couple of seconds later something goes strange.

<pre>$ kubectl get rs --all-namespaces
NAMESPACE       NAME                                 DESIRED   CURRENT   READY     AGE
monitoring      kube-state-metrics-54d774c995        1         1         0         8s
monitoring      kube-state-metrics-79b8675776        0         0         0         23s</pre>

One more replicaset was created and it has pod template from the first deleted deployment. And i got two revisions. The second was created implicitly automatic.

<pre>$ kubectl rollout history deployment/kube-state-metrics -n monitoring
deployments "kube-state-metrics"
REVISION  CHANGE-CAUSE
1         kubectl create --filename=manifests/kube-state-metrics-deployment.yaml --record=true --save-config=true
2         kubectl create --filename=manifests/kube-state-metrics-deployment.yaml --record=true --save-config=true</pre>

The pod could not start again.

<pre>$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                                         READY     STATUS    RESTARTS   AGE
monitoring      kube-state-metrics-54d774c995-dnpft                          0/4       Pending   0          1h</pre>

I tried to manually edit the pod config to finish deployment stage and then replace the deployment by new one with new pod template hash but it always creates old replicaset implicitly and this replica always wins.

<pre>$ kubectl get rs --all-namespaces
NAMESPACE       NAME                                 DESIRED   CURRENT   READY     AGE
monitoring      kube-state-metrics-54d774c995        1         1         0         14s
monitoring      kube-state-metrics-65bf5c56b6        0         0         0         45m
monitoring      kube-state-metrics-7bdd4976d9        0         0         0         46m</pre>

As i understand there is an internal queue or other structure which is not cleaned up after "kubectl delete deployment".

**What you expected to happen**:
The "kubectl delete" call must clear all the data associated with the deployment and return to the initial state.

**How to reproduce it (as minimally and precisely as possible)**:
I tried to describe all the steps above.

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- Install tools: kubeadm

**Comment by Huang-Wei** [comment]
@orsobruno by default kubeadm applies a **non-value taint** to master node:

```yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

So you should update your tolerations a little bit:

```yaml
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```

or

```yaml
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: 
        effect: NoSchedule
```

**Comment by mazengxie** [comment]
I meet the issue too

**Comment by Huang-Wei** [comment]
> it doesn't solve the problem with implicitly created deployment. It always creates two revisions.

@orsobruno do you mean after (1) correcting the tolerations in the yaml and (2) deleting the whole deployment, you still see 2 replicasets?

**Comment by orsobruno** [comment]
Yes. That's right.

**Comment by Huang-Wei** [comment]
Can't reproduce this issue. Would leave to sig/apps or sig/cli folks to take a deep look.

BTW: I noticed @orsobruno is using a mac kubectl running against a linux apiserver. @mazengxie are you also using a mac kubectl? Wha't your reproducing procedure and `kubectl version` info?

**Comment by mazengxie** [comment]
@Huang-Wei 
 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-beta.0.43+320c55e964f5e0", GitCommit:"320c55e964f5e01dae67899792ab2feb1efc8f98", GitTreeState:"clean", BuildDate:"2018-08-15T02:46:51Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

the problem can be reappearance as follow：
1. create a wrong yaml，and use kubeclt apply -f *yaml
egg.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testhealth3
  namespace: iot
  labels:
    name: testhealth3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: testhealth3
    spec:
      containers:
        - name: testhealth3
          image: "192.168.0.114:5000/chad:5"
          ports:
            - containerPort: 1013
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path:/index+wrong/                       // make a mistake designedly
              port: 1013
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1

2. correct mistakes， and use kubeclt apply -f *yaml
then you will see the leaving replicasets

**Comment by mazengxie** [comment]
the logs of kube-controller-manager-master：
I0821 06:41:50.142386       1 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"iot", Name:"testhealth3", UID:"38f2827d-a1d1-11e8-b1c4-000c29b57966", APIVersion:"extensions", ResourceVersion:"7784381", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set testhealth3-66cf7c4c4d to 1
I0821 06:41:50.148644       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"iot", Name:"testhealth3-66cf7c4c4d", UID:"4853a127-a50d-11e8-b8f2-000c29b57966", APIVersion:"extensions", ResourceVersion:"7784382", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: testhealth3-66cf7c4c4d-pctp5
I0821 06:42:00.653088       1 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"iot", Name:"testhealth3", UID:"38f2827d-a1d1-11e8-b1c4-000c29b57966", APIVersion:"extensions", ResourceVersion:"7784408", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set testhealth3-66cf7c4c4d to 0
I0821 06:42:00.657847       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"iot", Name:"testhealth3-66cf7c4c4d", UID:"4853a127-a50d-11e8-b8f2-000c29b57966", APIVersion:"extensions", ResourceVersion:"7784411", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: testhealth3-66cf7c4c4d-pctp5

From log，the error pod is be deleted, but relicasets nerver be deleted.

**Comment by rojkov** [comment]
I think I managed to reproduce the problem: the new recreated RS doesn't have tolerations and the new pods can't be placed to the master node as result.
Currently I have capacity to debug it. I'll take a closer look.

**Comment by rojkov** [comment]
So, it turned out the culprit is not in Kubernetes, but in the outdated container image `quay.io/coreos/addon-resizer:1.0` of your deployment.

It runs a client which updates the `kube-state-metrics` deployment. But the client uses outdated API which lacks `Tolerations` in `PodSpec`. As result the updated deployment looses tolerations in its pod template. The deployment controller recreates `ReplicaSet`. The pods controlled by the new `ReplicaSet` lack tolerations as well and fail to run on the tainted node.

**Comment by mazengxie** [comment]
@rojkov 
It is unreasonable to create new ReplicaSet about the deployment。
Delete pods, and delete ReplicaSet too.

**Comment by rojkov** [comment]
@mazengxie I'm afraid I don't fully understand you. I investigated the case reported by @orsobruno . His issue can be solved with a newer version of addon-resizer.

It's perfectly reasonable to create a new ReplicaSet when the Deployment gets updated. It doesn't contradicts the docs at least: a new ReplicaSet is always created with both strategies `Recreate` and `RollingUpdate`.

When the new ReplicaSet is up and running, the old one gets deleted. Not the other way around.

**Comment by mazengxie** [comment]
@rojkov 
I meet the same problem.
the new ReplicaSet is created, but the old one doesn't delete.
you can see my description from the above.

**Comment by mazengxie** [comment]
testhealth3-5799c8fdf    1         1         1         6d
testhealth3-57fd44658c   0         0         0         6d
testhealth3-66cf7c4c4d   0         0         0         2d

the problem can be reappearance as follow：

1. create a wrong yaml，and use kubeclt apply -f *yaml
egg.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
name: testhealth3
namespace: iot
labels:
name: testhealth3
spec:
replicas: 1
template:
metadata:
labels:
run: testhealth3
spec:
containers:
- name: testhealth3
image: "192.168.0.114:5000/chad:5"
ports:
- containerPort: 1013
resources:
requests:
memory: "250Mi"
cpu: "200m"
limits:
memory: "300Mi"
cpu: "500m"
readinessProbe:
httpGet:
path:/index+wrong/ // make a mistake designedly
port: 1013
initialDelaySeconds: 10
periodSeconds: 5
timeoutSeconds: 1

2. correct mistakes， and use kubeclt apply -f *yaml
3. then you will see the leaving replicasets

[root@master test]# kubectl get rs -n iot
NAME                     DESIRED   CURRENT   READY     AGE
testhealth3-5799c8fdf    1         1         1         6d
testhealth3-57fd44658c   0         0         0         6d
testhealth3-66cf7c4c4d   0         0         0         2d

**Comment by mazengxie** [comment]
the leaving rs:
[root@master test]# kubectl -n iot get rs testhealth3-57fd44658c -o json 
{
    "apiVersion": "extensions/v1beta1",
    "kind": "ReplicaSet",
    "metadata": {
        "annotations": {
            "deployment.kubernetes.io/desired-replicas": "1",
            "deployment.kubernetes.io/max-replicas": "2",
            "deployment.kubernetes.io/revision": "1"
        },
        "creationTimestamp": "2018-08-17T03:54:21Z",
        "generation": 2,
        "labels": {
            "pod-template-hash": "1398002147",
            "run": "testhealth3"
        },
        "name": "testhealth3-57fd44658c",
        "namespace": "iot",
        "ownerReferences": [
            {
                "apiVersion": "extensions/v1beta1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Deployment",
                "name": "testhealth3",
                "uid": "38f2827d-a1d1-11e8-b1c4-000c29b57966"
            }
        ],
        "resourceVersion": "7326258",
        "selfLink": "/apis/extensions/v1beta1/namespaces/iot/replicasets/testhealth3-57fd44658c",
        "uid": "38f35909-a1d1-11e8-b1c4-000c29b57966"
    },
    "spec": {
        "replicas": 0,
        "selector": {
            "matchLabels": {
                "pod-template-hash": "1398002147",
                "run": "testhealth3"
            }
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "pod-template-hash": "1398002147",
                    "run": "testhealth3"
                }
            },
            "spec": {
                "containers": [
                    {
                        "image": "192.168.0.114:5000/chad:5",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "testhealth3",
                        "ports": [
                            {
                                "containerPort": 1013,
                                "protocol": "TCP"
                            }
                        ],
                        "readinessProbe": {
                            "failureThreshold": 3,
                            "httpGet": {
                                "path": "/index11/",                              @rojkov I make a mistake, and correct it.
                                "port": 1013,
                                "scheme": "HTTP"
                            },
                            "initialDelaySeconds": 10,
                            "periodSeconds": 5,
                            "successThreshold": 1,
                            "timeoutSeconds": 1
                        },
                        "resources": {
                            "limits": {
                                "cpu": "500m",
                                "memory": "300Mi"
                            },
                            "requests": {
                                "cpu": "200m",
                                "memory": "250Mi"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "terminationGracePeriodSeconds": 30
            }
        }
    },
    "status": {
        "observedGeneration": 2,
        "replicas": 0
    }
}

**Comment by rojkov** [comment]
@mazengxie What I see is that there is a running ReplicaSet 6 days old (`testhealth3-5799c8fdf`) with one running pod.

Then you applied the second generation of the Deployment with a mistake in readinessProbe.
Since the strategy by default is `RollingUpdate` the first ReplicaSet wasn't drained, because this second generation ReplicaSet (`testhealth3-57fd44658c`) didn't reported it's running (and it couldn't).

Then a third generation of the Deployment with corrected readinessProbe setting was applied 2 days ago. This created `testhealth3-66cf7c4c4d` which didn't succeed neither for some reason.

I don't see any problem here still.

It would be a problem if `testhealth3-66cf7c4c4d` reported it's up and running and `testhealth3-57fd44658c` (and `testhealth3-5799c8fdf`) was not deleted after that.

**Comment by mazengxie** [comment]
@rojkov, 
Maybe I did not express clearly.
I create testhealth3-57fd44658c at first, then create testhealth3-5799c8fdf.

the correct rs:
[root@master test]# kubectl -n iot get rs testhealth3-5799c8fdf -o json
{
.....
"**creationTimestamp**": "2018-08-17T03:54:39Z",
.....

the leaving rs:
[root@master test]# kubectl -n iot get rs testhealth3-57fd44658c -o json
{
.......
"**creationTimestamp**": "2018-08-17T03:54:21Z",

I can provide my yaml and images and I reproduce again:

1. at first, the Deployment **with a mistake** create testhealth3-66cf7c4c4d
2. then , I corret it, and use "kubectl apply -f *.yaml",  then create testhealth3-5799c8fdf.

[root@master health]# kubectl -n iot get rs
NAME                     DESIRED   CURRENT   READY     AGE
testhealth3-5799c8fdf    1         1         1         28s
testhealth3-66cf7c4c4d   0         0         0         39s

**Comment by rojkov** [comment]
@mazengxie Ok, now I see the problem. It's not the same as @orsobruno 's though.

I managed to reproduce it by applying this YAML first
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app-container
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5

```

then by applying this corrected one
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app-container
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
```

And the current status is now
```
$ kubectl get rs 
NAME                         DESIRED   CURRENT   READY     AGE
test-deployment-5fc6d76fcf   0         0         0         13m
test-deployment-746759c86d   1         1         1         10m

```

I'll try to investigate what's going on here.

**Comment by rojkov** [comment]
@mazengxie Again it turned out to be not a bug, but feature.

Kubernetes "retains all but the latest N old replica sets where N=Deployment.Spec.RevisionHistoryLimit. Old replica sets are older versions of the podtemplate of a deployment kept around by default 1) for historical reasons and 2) for the ability to rollback a deployment."

If you want a deployment to delete all old replica sets then set its `Spec.RevisionHistoryLimit` to zero.

**Comment by orsobruno** [comment]
@rojkov Thanks, Dmitry. I thought that this could be the effect of external influence. Could you describe steps of your debugging please.

**Comment by rojkov** [comment]
Hm... I'm not sure I can remember the exact steps. My style of debugging is trial and error led by my intuition. But here is the scheme I usually use:

0. Reproduce the issue locally. Usually this is the most time consuming step.
1. Look into all available logs for anything weird or strange (nothing interesting here this time).
2. Try to build an older version of Kubernetes, as old as possible. And see if the issue is reproducible. Then in case it's not use `git bisect` to find the offending commit. Unfortunately the issue is reproducible even with K8s 1.8.0.
3. Examine the content of the objects in question (`ReplicaSet`s) using `kubectl describe ...`. How objects of the same type differ from each other. If some objects are mutable try to find out how their content gets updated (`Deployment`). Here I found out that the new replica set lacks tolerations and the deployment is not immutable.
4. Find the code which runs upon deployment updates and increase its log verbosity. It turned out the relevant code is the deployment controller of `kube-contoller-manager`. This environment variable increases log verbosity for the code `LOG_SPEC=deployment_controller*=5,replica_set*=5,sync*=5,recreate*=5`.
The only outcome on this step was the confirmation that the deployment gets updated.
5. Modify the sync handler for `Deployment` objects to log what exactly has changed (this lib can be used to do the diff https://github.com/d4l3k/messagediff). Here we see that the only change was the removal of the tolerations.
6. Look for code which actually does update `Deployment` through the API server with this command
   ```
   $ git grep Deployments| grep "Update("
   ```
   There is only a few places in Kubernetes where `Deployment`s get updated, but none look relevant. This leads to the hypothesis that the source of the update is somewhere outside of Kubernetes.
7. Take a closer look at the YAML files. They seem to be quite complex.
8. Try to make the setup as simple as possible where the issue is still reproducible. Here I found that small single changes in different YAML files lead to the issue being not reproducible - the setup is too fragile.
9. Then look through the YAMLs line by line in the hope to find something interesting. The interesting bit here is that the deployment operates on behalf of the `kube-state-metrics` service account which requests permission to do 'update' on `Deployment`s.
10. Drop this permission. This confirms that the Deployment doesn't change any more.
11. Look into the logs of the running pod. Bingo! In `addon-resizer`'s logs there is an error about inability to update the Deployment.
12. Try to find the sources of `addon-resizer:1.0`. This turned out to be not easy task, because the version 1.0 is _very_ old. Apparently the culprit is K8s API evolved too much since v1.0. Looking at `PodSpec` used in `addon-resizer:1.0` confirms it.

**Comment by orsobruno** [comment]
I thought there is a simpler and faster option. Great job. Thank you very much.
