### ISSUE TITLE
Allow range of ports for Network Policy

### ISSUE THREAD

**Issue by sawanoboly** [kubernetes/kubernetes#67526]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

For example, if you want to allow communication to an external FTP server with egress rules, you want to allow all Ephemeral ports to support PASV mode.

At this time, if it can not specify it like the following, the rule becomes very large.

```
  egress:
  - ports:
    - port: 21
      protocol: TCP
    - port: 990
      protocol: TCP
    - port: 32768:61000
      protocol: TCP
```

**What you expected to happen**:

```
$ kubectl apply -f allow-ftp.yaml 
The NetworkPolicy "allow-ftp" is invalid: 
* spec.egress[0].ports[8].port: Invalid value: "32768:61000": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-)
* spec.egress[0].ports[8].port: Invalid value: "32768:61000": must contain at least one letter or number (a-z, 0-9)
```

The iptables allows syntax `from:to` for dports by using multiport, but kubernetes doesn't allow it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server v1.10.3, Client v1.11.1
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g. from /etc/os-release): Amazon Linux 2
- Kernel (e.g. `uname -a`): Not disclosed
- Install tools: Amazon EKS
- Others:

/sig network

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests semi-related https://github.com/kubernetes/kubernetes/issues/23864

This probably would be a breaking change that would require a v2 bump to the API and buy-in from Network Policy providers.

cc @caseydavenport @danwinship

**Comment by caseydavenport** [comment]
I don't _think_ this would require a new v2 API bump since the old policies would still be valid. 

iptables supports this - do we have to worry about other implementations that might not? I suspect that pretty much any implementation can do this.

**Comment by danwinship** [comment]
OVS can't match on port ranges (though it can do bitmask matches, so in theory you could hack it up with a lot of pain).

I'm not sure you can really make that strong an argument that allowing access to "only" 43% of the port space counts as "security" :-}. Maybe there's an argument for "don't allow connections to ports < 1024"...

> For example, if you want to allow communication to an external FTP server with egress rules, you want to allow all Ephemeral ports to support PASV mode.

FWIW conntrack is able to recognize the PASV connection as `RELATED` to the parent FTP connection, so most plugins would be able to just make them work automatically, if they wanted to.

**Comment by sawanoboly** [comment]
@danwinship 

If you means the ip_conntrack_ftp module etc, I would like to use that on the FTP server side as well.
This time is the case when using FTP client from Pod.

Actually, if it is possible to block several ports with egress, in my case it is possible to replace.

**Comment by danwinship** [comment]
oh, does ip_conntrack_ftp only work on the server side? lame

**Comment by cmluciano** [comment]
> I don't think this would require a new v2 API bump since the old policies would still be valid.

My thinking was that this may force more parsing on the CNI plugin since we just [expect a string ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1/types.go#L147)

**Comment by caseydavenport** [comment]
> My thinking was that this may force more parsing on the CNI plugin since we just expect a string

Yes, I see. I suppose the suggested in the OP might require a version bump, but I can imagine ways to do this without one. e.g. add a new `endPort` field or something like that.

**Comment by cmluciano** [comment]
+1 to a new field if we want this. 

cc @bboreham @squeed @aanm @thockin for further feedback

**Comment by denhub** [comment]
+1

**Comment by maoge** [comment]
port range proposal using kubernetes annotations
annotation: portrange.alpha.kubernetes.io/port-end-xxxx
https://github.com/kubernetes/kubernetes/pull/26014/commits/2cf5af1f8cc33e2d22ed1968aca05e5323ef9a0b

**Comment by thockin** [comment]
I did a quicky prototype of Services with whole IPs.  It works, but it's clunky because the `ports` field carries  information (e.g. protocol) that I need even if I want all ports.  Also because it is required.  

While that is not done, maybe the right answer here is just to not specify ports and allow the whole IP?

IPVS is also not able to express ranges easily.

The idea of "all ports > 1024" is not terrible.  Would that actually be valuable?

**Comment by danwinship** [comment]
> While that is not done, maybe the right answer here is just to not specify ports and allow the whole IP?

Did you comment on the wrong issue? This one is "port ranges for NetworkPolicies", not "port ranges for Services". You can already "not specify ports and allow the whole IP" for NetworkPolicies, it's just that the OP didn't want to.

**Comment by curu** [comment]
+1.
my dev cluster requires strong network access control, and some pod need access to port range like 32000 to 33000. without port range support, we need to create 1000 iptables rule for one access rule. worstly, the total iptables rules sum up to more than 100,000,  and it took kube-router 10 minutes to sync all the rules.

**Comment by morriski** [comment]
+1

**Comment by prbsparx** [comment]
+1

**Comment by candidature** [comment]
I'm creating a network of pods and i don't know what all ports may come in. I would love to see range of ports as part of network policy Ingress and Egress. Sorry for my ignorance, please share details if this is already implemented.

**Comment by bboreham** [comment]
@candidature if you literally don’t know, then say nothing about ports: then every port will be allowed. 

(Also FYI Kubernetes defines the specification of NetworkPolicy; all current implementations are 3rd-party and may implement more or less than the spec)

**Comment by candidature** [comment]
@bboreham Thank you for the tip.

**Comment by rikatz** [comment]
@jayunit100 do you want this one to keep on track of our WG NetPol++?

**Comment by rikatz** [comment]
This is a subject of https://github.com/kubernetes/enhancements/pull/2090

**Comment by rikatz** [comment]
Implemented :D
