### ISSUE TITLE
daemonsets.extensions "fluentd-gcp-v3.0.0" not found

### ISSUE THREAD

**Issue by YacheLee** [kubernetes/kubernetes#67538]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

/kind bug

**What happened**:
On 1.10.6-gke.1, The version of fluentd-gcp is wrong. Fluentd-gcp-scaler keeps showing the logs: Error from server (NotFound): daemonsets.extensions "fluentd-gcp-v3.0.0" not found.
But the version of fluentd-gcp in my k8s is v3.1.0.

**What you expected to happen**:
Fluentd-gcp-scaler should use fluentd-gcp-v3.1.0.

**How to reproduce it (as minimally and precisely as possible)**:
Use GKE 1.10.6-gke.1.

**Comment by eli-z** [comment]
Same issue here, looking at gcp-scaler deployment 
kubectl get deployments -n kube-system fluentd-gcp-scaler -o yaml
results in: 
--ds-name=fluentd-gcp-v3.0.0
in command section of container spec. maybe this is the issue

**Comment by timothyliu** [comment]
After upgrading to 1.10.6-gke.2, it still has the same issue.

**Comment by martynbristow** [comment]
@eli-z This definitely seems to be the issue to me, I've tried updating it but something overrides my changes

**Comment by YacheLee** [comment]
Yes, I force to change the daemon for the correct version, but k8s keeps making the version back. It could not allow me to do so.

**Comment by x13n** [comment]
https://github.com/kubernetes/kubernetes/pull/67505 fixes this, there is a cherrypick to 1.10 and 1.11 in flight.

**Comment by marfenij** [comment]
1.10.7-gke.6  still have such issue, any workaround to fix that ?

**Comment by wyaeld** [comment]
@YacheLee @x13n Just upgraded master and nodes to 1.11.2-gke.9 today and this is still happening.  Does the GKE platform upgrade to new nodes when you upgrade a node pool, and should this problem go away?

**Comment by x13n** [comment]
The [cherrypick](http://go/gh/kubernetes/kubernetes/pull/67535) to 1.11 branch went in 1.11.3, 1.11.2-gke.9 doesn't have it.

Addon deployments/daemonsets are upgraded together with master upgrade, as long as they had any changes. When there are no changes, it's expected for them to stay untouched.

**Comment by marfenij** [comment]
> 1.10.7-gke.6 still have such issue, any workaround to fix that ?

1.10.9-gke.0  is available and does not contains this issue

**Comment by x13n** [comment]
I don't think we snapshot them in any docs, so the closest you can get to that is by running:
```$ kubectl get all -n kube-system -o yaml```.

**Comment by wyaeld** [comment]
Is it safe to just assume that GKE is always running the correct ones then?  If this isn't an issue I have to worry about then I'm fine with it, but normally I like to be able to compare what "should" be running with what is.

**Comment by x13n** [comment]
It's GKE responsibility to run the correct ones, so if for some reason this will not be true, it will be a bug that GKE needs to fix. Hence, it's best not to worry!

**Comment by wyaeld** [comment]
@x13n ok, that's clear, thanks.

**Comment by wyaeld** [comment]
@wminshew wouldn't expect it to, @x13n comment above indicates the fix comes in on v1.11.3

**Comment by wminshew** [comment]
Ah thank you for highlighting, you're absolutely right. Was confused by @marfenij comment about v1.10.9

**Comment by wminshew** [comment]
> The [cherrypick](http://go/gh/kubernetes/kubernetes/pull/67535) to 1.11 branch went in 1.11.3, 1.11.2-gke.9 doesn't have it.
> 
> Addon deployments/daemonsets are upgraded together with master upgrade, as long as they had any changes. When there are no changes, it's expected for them to stay untouched.

is this somehow related to the below post-upgrade logging (~1/min)?
```
error: info: daemonsets "fluentd-gcp-v3.1.0" was not changed
```

Tried restarting the ds. Doesn't seem to be upsetting anything so not sure it's worth opening a new issue on, but can't seem to find any related information in other issues / on stackoverflow / google

**Comment by manigandham** [comment]
This seems to have just created more issues. We now see these statements spammed in our logs in a 1.11.3 GKE cluster:

```
Error from server (NotFound): scalingpolicies.scalingpolicy.kope.io "fluentd-gcp-scaling-policy" not found
```
```
error: info: daemonsets "fluentd-gcp-v3.1.0" was not changed
```

The first seems to have been solved by adding the ScalingPolicy found at https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-gcp

Does this logging actually get tested on GKE?

**Comment by x13n** [comment]
@manigandham 
Both these errors are harmless (although I agree they can be confusing). The first one was already fixed in 1.11.4. The fix for the second one is here: http://go/gh/kubernetes/kubernetes/pull/72243

**Comment by manigandham** [comment]
@x13n Ok, thanks for the info.

Just for feedback: As users, we don't know that the errors are harmless and it is logged at ERROR level which isn't filtered out by regular log level filters. The large amount of logs also costs money and creates a lot of noise, especially when we have multiple clusters.

Maybe they should be logged at `verbose` or `debug` level if they have no impact on the cluster?

**Comment by x13n** [comment]
Thanks for the feedback! Yes, users shouldn't see errors in logs when there is no actual issue.

In this case, the first one shouldn't be logged at all (and isn't, anymore). The second one was caused by a problem in the logic, resulting in no-op apiserver calls. So although it didn't cause any end-user visible effects, it was indeed an error.

**Comment by huangheqing** [comment]
After all these conversations, what is the actual fix for issue:error: info: daemonsets "fluentd-gcp-v3.1.0" was not changed. We really don't want to see these harmless logs in the GCP logging console
