### ISSUE TITLE
TaintNodesByCondition causes pods to become NodeLost

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#67536]
In autoscaling tests, we verify that when a node suddenly disappears from the cluster, Cluster Autoscaler will add another one to replace it. With TaintNodesByCondition (enabled by default in #62111), this is now failing:

https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling

Every time a node disappears, a subset of pods become NodeLost and aren't rescheduled on a new node. 

/cc @k82cn @bsalamat  
/sig node

**Comment by Huang-Wei** [comment]
@k82cn I can work on this.

**Comment by Huang-Wei** [comment]
@aleksandra-malinowska latest autoscaling testing is green. I think we can close this issue.

**Comment by aleksandra-malinowska** [comment]
Thanks for fixing this!
