### ISSUE TITLE
does k8s support running simple shell command application on cluster nodes?

### ISSUE THREAD

**Issue by junneyang** [kubernetes/kubernetes#67534]
**does k8s support running simple shell command application on cluster nodes?
not just docker container on cluster nodes, but also shell command application on cluster nodes.**

reference: [mesos/marathon](http://mesosphere.github.io/marathon/docs/application-basics.html)

[1. shell command application](http://mesosphere.github.io/marathon/docs/application-basics.html#hello-marathon-an-inline-shell-script)
```
{
    "id": "basic-0", 
    "cmd": "while [ true ] ; do echo 'Hello Marathon' ; sleep 5 ; done",
    "cpus": 0.1,
    "mem": 10.0,
    "instances": 1
}
```

[2. docker based application](http://mesosphere.github.io/marathon/docs/application-basics.html#a-simple-docker-based-application)
```
{
  "id": "basic-3",
  "cmd": "python3 -m http.server 8080",
  "cpus": 0.5,
  "mem": 32.0,
  "networks": [ { "mode": "container/bridge" } ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "python:3"
    },
    "portMappings": [
      { "containerPort": 8080, "hostPort": 0 }
    ]
  }
}
```

**i think this feature is very useful for non docker applications,
how can i reach this goal by k8s like the mesos/marathon framework?
thanks for your help!**

**Comment by GaoRong** [comment]
you may need ansible or other automation tools, as k8s has been a big, complicated orchestration, we needn't improve more complexity as far as possible.

**Comment by junneyang** [comment]
@GaoRong 
no, i think both docker service and simple shell command service are long-running service, they should be managed by unified scheduler.
if k8s could be compatible with both of them like mesos/marathon,
it could be  very expected feature!
