### ISSUE TITLE
ConfiMap input file comments, ending with space storing value as quoted string instead of key/value pair

### ISSUE THREAD

**Issue by ansilh** [kubernetes/kubernetes#67563]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**: ConfigMap from input file creates quoted contents instead of key/value pair

**What you expected to happen**: ConfigMap should create with key/value pair 

**How to reproduce it (as minimally and precisely as possible)**:

Sample config file
The comment made were ending with a \<space\>\<newline\> ( removing space from the end of the comment will give desired output)
```
$ cat config.txt
# This is a sample config file that I might use to configure an application  
parameter1 = value1
parameter2 = value2
```
Create a config map with this file 
```
$ kubectl create configmap my-config --from-file=config.txt
```
Now we can see all the file contents were placed inside quotes instead of storing as key/value pair
```
$ kubectl get configmap/my-config -o yaml
apiVersion: v1
data:
  config.txt: "# This is a sample config file that I might use to configure an application
    \nparameter1 = value1\nparameter2 = value2\n"
kind: ConfigMap
metadata:
  creationTimestamp: 2018-08-18T15:08:43Z
  name: my-config
  namespace: default
  resourceVersion: "70812"
  selfLink: /api/v1/namespaces/default/configmaps/my-config
  uid: 9905430b-a2f8-11e8-a453-08002702a19b
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `VirtualBox VM ( one master + 4 minions )`
- OS (e.g. from /etc/os-release):  `Ubuntu 16.04.5 LTS (Xenial Xerus)`
- Kernel (e.g. `uname -a`): `Linux k8s-master01 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A

**Comment by liggitt** [comment]
this is working as designed. `--from-file` places the content of the file in a key matching the file's name. You might be looking for `--from-env-file`, which reads the content of the file and creates key/value pair from `key=value` lines in the file.

/close
