### ISSUE TITLE
Multiple same headers got wrong result on gcr.io/google-containers/echoserver:1.10

### ISSUE THREAD

**Issue by chanjarster** [kubernetes/kubernetes#67561]
/kind bug

Hello, actually this is a bug about `echoserver` not about k8s.

I use `gcr.io/google-containers/echoserver:1.10` to observe request headers and found if the request have multiple same headers echoserver will give a wrong result:

`curl -H 'x-foo:foo' -H 'x-foo:bar' http://echoserver:8080`

result:

```
...
Request Headers:
	x-foo=table: 0x41fadd70
...
```

Expected result:

```
...
Request Headers:
	x-foo=foo
	x-foo=bar
...
```

**Comment by dims** [comment]
@chanjarster any chance you know some lua? https://github.com/kubernetes/kubernetes/blob/master/test/images/echoserver/template.lua

**Comment by chanjarster** [comment]
@dims I never used lua before, but I'm willing to try to fix this issue.
