### ISSUE TITLE
Labelled node when offline.

### ISSUE THREAD

**Issue by saivarunr** [kubernetes/kubernetes#67579]
/kind bug

**One of the labelled nodes went offline, reason unkown**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Name:               ip-172-20-46-201.ec2.internal
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t2.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1a
                    kops.k8s.io/instancegroup=nodes
                    kubernetes.io/hostname=ip-172-20-46-201.ec2.internal
                    kubernetes.io/role=node
                    node-role.kubernetes.io/node=
                    worker_name=worker_1
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Thu, 31 May 2018 10:32:37 +0000
Taints:             <none>
Unschedulable:      false
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----                 ------    -----------------                 ------------------                ------                     -------
  NetworkUnavailable   False     Thu, 31 May 2018 10:32:47 +0000   Thu, 31 May 2018 10:32:47 +0000   RouteCreated               RouteController created a route
  OutOfDisk            False     Sat, 18 Aug 2018 18:43:12 +0000   Thu, 31 May 2018 10:32:37 +0000   KubeletHasSufficientDisk   kubelet has sufficient disk space available
  MemoryPressure       Unknown   Sat, 18 Aug 2018 18:43:12 +0000   Sat, 18 Aug 2018 18:43:53 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
  DiskPressure         Unknown   Sat, 18 Aug 2018 18:43:12 +0000   Sat, 18 Aug 2018 18:43:53 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
  Ready                Unknown   Sat, 18 Aug 2018 18:43:12 +0000   Sat, 18 Aug 2018 18:43:53 +0000   NodeStatusUnknown          Kubelet stopped posting node status.
Addresses:
  InternalIP:   172.20.46.201
  ExternalIP:   54.84.234.27
  InternalDNS:  ip-172-20-46-201.ec2.internal
  ExternalDNS:  ec2-54-84-234-27.compute-1.amazonaws.com
  Hostname:     ip-172-20-46-201.ec2.internal
Capacity:
 cpu:     4
 memory:  16435608Ki
 pods:    110
Allocatable:
 cpu:     4
 memory:  16333208Ki
 pods:    110
System Info:
 Machine ID:                 145420df8f2841f69168ef72830a837a
 System UUID:                EC26D05A-01C2-719A-C8F2-6E625C21C47E
 Boot ID:                    ff6b693b-f754-47b4-a8cd-f6a5b6068494
 Kernel Version:             4.4.115-k8s
 OS Image:                   Debian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://Unknown
 Kubelet Version:            v1.9.3
 Kube-Proxy Version:         v1.9.3
PodCIDR:                     100.96.4.0/24
ExternalID:                  i-01dff8e43d1c1d9a7
ProviderID:                  aws:///us-east-1a/i-01dff8e43d1c1d9a7
Non-terminated Pods:         (10 in total)
  Namespace                  Name                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                        ------------  ----------  ---------------  -------------
  default                    airflow-869fd66b49-w7fsh            200m (5%)     0 (0%)      0 (0%)           0 (0%)
  default                    couchdb-0                                   100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    drill-8656d7fdb5-vnb5t                      100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    hdfs-datanode-0                             100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    postgres-0                                  100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    redis-0                                     100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    spark-hdfs-deployment-5f84cd99c5-v7xp8      100m (2%)     0 (0%)      0 (0%)           0 (0%)
  default                    ui-74df487bbd-dhmc4                        200m (5%)     0 (0%)      0 (0%)           0 (0%)
  default                    zookeeper-545f955c6d-fc97k                  100m (2%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-ip-172-20-46-201.ec2.internal    100m (2%)     0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  1200m (30%)   0 (0%)      0 (0%)           0 (0%)
Events:         <none>

**Comment by neolit123** [comment]
please fill the issue template correctly:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by dims** [comment]
/close

please reopen with more info as @neolit123 requested
