### ISSUE TITLE
Probe back off settings

### ISSUE THREAD

**Issue by pweil-** [kubernetes/kubernetes#6758]
While using a liveness probe on a pod that must initialize itself with multiple configuration files we found that the liveness probe delay was not always sufficient without making it a large value.  https://github.com/openshift/origin/issues/1504#issuecomment-87824041

It seems likely that we may run in to a scenario where the initial delay is unpredictable but a probe is still desired.  The use cases I can think of are:
1.  An application that must perform N amount of work before initializing.  For example, an application that must read in configuration before starting the processes that will enable the probe to complete.  The configuration may be a single, variable sized file, multiple files, retrieving and writing data from master, etc.  
2.  At scale in a prod environment, resource jitter may delay what was a good probe initial delay setting in dev/test environments.

An initial delay with a back off for failures seems appropriate in these use cases in order to give an adequate amount of time between probes before killing and restarting the container.

**Comment by smarterclayton** [comment]
Another option suggested was to backoff the initial liveness probe on subsequent restarts

1. Attempt 1, 10s delay.  No response, kill container
2. Attempt 2, 20s delay (because the container has not started).  No response, kill container
3. Attempt 3, 30s delay (because the container has not started).  Responded, mark live
4. Attempt 4, 10s delay (normal). Responded, keep container.

**Comment by smarterclayton** [comment]
@pweil- does the absence of this feature make liveness probes unpredictable to end users in a way that makes them unusable? Or is it merely the cause of some flakiness?

**Comment by pweil-** [comment]
@smarterclayton - just flaky IMO.  The delay setting can be used to work around it for now.
