### ISSUE TITLE
no scheduler logs whether the pod scheduler successed or failed

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#67589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature
/sig scheduling

**What happened**:
whether the pod scheduler successed or failed， no logs can record it in scheduler.INFO.
**What you expected to happen**:
scheduler can print the result of pod scheduled like contorller-manager.INFO print the result of pod created.
**How to reproduce it (as minimally and precisely as possible)**:
deploy a pod

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
will there be too much logs?

**Comment by Pingan2017** [comment]
if schedule failed , th logs will be printed rolling

**Comment by Pingan2017** [comment]
in k8s 1.6.9 , scheduler will print events like other components, i don't know why we delete this.

**Comment by krmayankk** [comment]
An event seems fine, or may be log at higher debug level. What is the use case ? Do you need this for debugging a failed scheduling @Pingan2017  ?

**Comment by Pingan2017** [comment]
In a production environment，sometimes when we troubleshoot , the Pod is no longer existing. At this point, we need to know which node the Pod was scheduled to. 
i think the schedulering is the important process for deploying. the result should be printed like controller-manager printing the result of pod creating.

**Comment by misterikkit** [comment]
Sorry I didn't find this issue when I filed https://github.com/kubernetes/kubernetes/issues/71819. It looks like there are two PRs trying to improve scheduler logging right now.


https://github.com/kubernetes/kubernetes/pull/71926
https://github.com/kubernetes/kubernetes/pull/72011

Also, I think the scheduler today logs pods that cannot be scheduled.

**Comment by misterikkit** [comment]
since both the PRs I mentioned merged, I think we can consider this issue resolved.
/close
