### ISSUE TITLE
Failing Test: DNS configMap federations should be able to change federation configuration [Slow][Serial]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67603]
# Failing Jobs
[sig-release-master-blocking#gci-gce-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial)
# Failing Tests
[[sig-network] DNS configMap federations should be able to change federation configuration [Slow][Serial]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3980)
# Triage Results
[[sig-network] DNS configMap federations should be able to change federation configuration [Slow][Serial]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gci-gce-serial&test=DNS%20configMap%20federations%20should%20be%20able%20to%20change%20federation%20configuration)

/kind failing-test
/priority critical-urgent
/sig network
/milestone v1.12
/cc @tpepper @AishSundar

**Comment by mohammedzee1000** [comment]
ping @roberthbailey

**Comment by mohammedzee1000** [comment]
Recent failures https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial

**Comment by tpepper** [comment]
@kubernetes/sig-network-bugs assistance needed triaging

**Comment by tpepper** [comment]
Has been failing mostly in sync with "[HPA] Horizontal pod autoscaling", but not quite...and failing continuously, even when that passed at times, so ... probably distinct.

**Comment by rajansandeep** [comment]
I'm looking into the issue. The CoreDNS configmap is incorrectly configured and hence the test fails.
/assign

**Comment by tpepper** [comment]
Given ^^^ I'm going to close this as a dup of #67600 for simplicity.
