### ISSUE TITLE
Promote container-runtime e2e tests to Conformance Suite

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#67609]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
#67571 is Porting container-runtime tests from e2e_node to e2e. Now we need to promote these ported tests to Conformance.

During Promotion, we have the following challenges -

- [x] 1. Add effective comments to these promoting e2e which are in the nested block. Issue #67607 
- [ ] 2. e2e tests matching '[should report termination message](https://github.com/kubernetes/kubernetes/pull/67571/files#diff-0dc16dc0a015699e53bda03495adc49eR204)' test must have functionality to match the content of TerminationMessagePath with TerminationMessage to precisely verify TerminationMessagePolicy (File and FallbackToLogsOnError). [Reference](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L1853-L1859)
> - When TerminationMessagePolicy is TerminationMessageReadFile or not specified (default), TerminationMessagePath content MUST match with TerminationMessage.
> - When TerminationMessagePolicy is TerminationMessageFallbackToLogsOnError, TerminationMessagePath content MUST NOT has content.

- [x] 3. [Nested tests](https://github.com/kubernetes/kubernetes/pull/67571/files#diff-0dc16dc0a015699e53bda03495adc49eR204) are not getting updated in conformance golden lists by updating It() context with framework.ConformanceIt().

Suggestions are most welcome to overcome these challenges.

**Comment by mgdevstack** [comment]
/area conformance
@kubernetes/sig-node-feature-requests

**Comment by mgdevstack** [comment]
Remaining table-based [NodeConformance] tests would be promoted once #68339 is closed.

**Comment by mgdevstack** [comment]
Awaiting for the issue comment to get addressed https://github.com/kubernetes/kubernetes/pull/75631#issuecomment-492023076. Probably in near future, we can start promoting these e2e.

**Comment by timothysc** [comment]
closing.
