### ISSUE TITLE
Conclude strategy to add Conformance comment to e2e iterating over range

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#67607]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
 
/kind bug

**What happened**:
Few of e2e tests are [iterating over the range](https://github.com/kubernetes/kubernetes/pull/67571/files#diff-0dc16dc0a015699e53bda03495adc49eR204) of different options. So in order to promote them to conformance, we need to generate conformance comment block dynamically specifying appropriate Testname: and Description:. 

Is there any way to achieve such dynamic commenting?
```
/*
    Release : v1.12
    Testname: Container Runtime, Restart Policy, Pod Phases
    Description: If the restart policy is set to ‘Always’, Pod MUST be started when terminated, If restart policy is ‘OnFailure’, Pod MUST be started only if it is terminated with non-zero exit code. If the restart policy is ‘Never’, Pod MUST never be restarted. All these three test cases MUST verify the restart counts accordingly.
*/
```

**Anything else we need to know?**:
- I'm not sure, how do we have generated/updated conformance release doc [v1.11](https://github.com/cncf/k8s-conformance/blob/master/docs/KubeConformance-1.11.md), but inorder to achieve this documentation we need to have dynamic comment provisioning.

**Comment by mgdevstack** [comment]
/area conformance
@kubernetes/sig-node-bugs

**Comment by mgdevstack** [comment]
@kubernetes/sig-testing

**Comment by spiffxp** [comment]
/sig architecture
/assign brahmaroutu
As the originator of this comment spec

**Comment by mgdevstack** [comment]
As mentioned by @brahmaroutu, Conformance Docs cannot be generated at runtime. `ast` scanner is used to pick up comment block statically. 

In case needed to add Conformance Doc for table based e2e, we can use the following pattern -
```
/*
    Release : v1.12
    Testname-1: Container Runtime, test-1
    Description: Description 1
    Testname-2: Container Runtime, test-2
    Description: Description 2
*/
```
Please correct me @brahmaroutu, if I misinterpret about comment block.

**Comment by brahmaroutu** [comment]
@mgdevstack 
Currently only one Description and Testname will be picked by the parser. If you need such support we need to enhance the tool. There is a reason for grouping the tests, I would suggest that the test name should just simply state what the group is trying to achieve, ex:
`/*
    Release : v1.12
    Testname: Container Runtime, Test various container spec fields for ....
    Description: 
    Testname-1: Container Runtime, test-1
    Testname-2: Container Runtime, test-2
*/` 
    
Please let me know if this satisfy your need. I am just trying to see if one TestName and Description is good enough?

**Comment by mgdevstack** [comment]
Thank you @brahmaroutu, this is definitely a good available option to create Conformance docs for table based (cases based) e2e tests. In this case, one TestName and Description is sufficient.

Once #68339 is closed we can follow above Conformance doc pattern.

**Comment by mgdevstack** [comment]
Based on discussion following approaches are considerable -
https://github.com/kubernetes/kubernetes/issues/67607#issuecomment-418856861
https://github.com/kubernetes/kubernetes/issues/68339#issuecomment-423678023

So closing this issue.
