### ISSUE TITLE
Failing test: broad scheduling issues due to TaintNodesByCondition

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67606]
# Failing Jobs
 [sig-release-master-upgrade#gce-new-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)
[sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel)
[sig-release-master-upgrade#gce-new-master-upgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster)
[sig-release-master-upgrade#gce-new-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)
[sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master)

# Failing Tests
[gce-new-master-upgrade-cluster-new](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1612)
[gce-new-master-upgrade-cluster-parallel](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4575)
[gce-new-master-upgrade-cluster](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2400)
[gce-new-master-upgrade-cluster-new](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1612)
[gke-gci-new-gci-master-upgrade-master](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1412)

SIGS whose tests are failing (possibly because of the upgrade failures)

/sig apps
/sig cluster-lifecycle
/sig storage

/sig testing
/sig gcp

/kind failing-test
/priority critical-urgent
/milestone v1.12

**Comment by mohammedzee1000** [comment]
Affected tests also belong to 
/sig api-machinery

**Comment by mohammedzee1000** [comment]
I need to know if these tests are failing on upgrade only, or are they actual failures of individual tests.
It would be good if the sig members can chip in as well.

**Comment by janetkuo** [comment]
This is likely related to the `TaintNodesByCondition` feature, which adds unschedulable taint to unschedulable nodes. 

Error:
```
I0820 17:37:28.057] Aug 20 17:37:28.057: INFO: Node bootstrap-e2e-master not expected to have DaemonSet pod, has taints [{node.kubernetes.io/unschedulable  NoSchedule 2018-08-20 17:20:13 +0000 UTC}]
...
I0820 17:37:28.068] Aug 20 17:37:28.067: INFO: nodesToPodCount: map[bootstrap-e2e-minion-group-6p12:1 bootstrap-e2e-master:1 bootstrap-e2e-minion-group-fxh0:1 bootstrap-e2e-minion-group-59p7:1]
I0820 17:37:28.068] Aug 20 17:37:28.067: INFO: expected DaemonSet pod to be running on all nodes, it was not
```

The test expects tainted node (master) not to have DaemonSet pods scheduled, but the DaemonSet controller schedules a pod on the tainted node. DaemonSet controller won't respect taints when `ScheduleDaemonSetPods` feature is disabled. 

@k82cn

**Comment by neolit123** [comment]
^ @tpepper

**Comment by k82cn** [comment]
@mohammedzee1000 , i'll open an PR for this this week :)

**Comment by mohammedzee1000** [comment]
@k82cn thanks, keep us posted. 

Note if tests continue to fail, after these underlying issues are fixed, i will open tracker issues for the same.

Still it will be good if the respective sigs can take a look at their tests to be sure.

**Comment by mohammedzee1000** [comment]
Hey we still have upgrade tests failing here

**Comment by mohammedzee1000** [comment]
cc @janetkuo @neolit123 @k82cn @tpepper @AishSundar

**Comment by tpepper** [comment]
@k82cn any update?
/assign @k82cn

**Comment by k82cn** [comment]
@tpepper , addressing comments of #64954 ; closing to get lgtm from reviewer :)

**Comment by tpepper** [comment]
@k82cn we're not seeing an improvement in test results.  Please advise.

Is https://github.com/kubernetes/kubernetes/issues/61312 also required?  We need more urgency here.

**Comment by tpepper** [comment]
Latest merge around node taints appears to have regressed:
https://github.com/kubernetes/kubernetes/pull/64954#issuecomment-420056091

**Comment by tpepper** [comment]
FYI for anybody reading here, the @tossmilestone reference to this issue appears to be GitHub automation noting that our k/k issue #67606 is mentioned over in what is probably Alauda.io's productization of k8s, as they seem to be PR'ing in fixes from our master to their fork.  Ie: normal dev.  There's no additional fix known to be pending in some other repo which we need to track.

**Comment by tpepper** [comment]
Test automation at this point indicating issue resolved.
