### ISSUE TITLE
kubernetes.io is down?

### ISSUE THREAD

**Issue by bennettellis** [kubernetes/kubernetes#67613]
from where I sit, kubernetes.io is not ressponding, everything else is. Need documentation to be available.

**Comment by nikhita** [comment]
/sig docs

The docs team is looking into this right now.

**Comment by neolit123** [comment]
https://kubernetes.io/ is back for me.

**Comment by neolit123** [comment]
from sig-docs at slack:
```
chenopis [9:25 PM]
...and we're back up!
```

/close
