### ISSUE TITLE
Persistent Volume claim to Job pod doesn't get assigned

### ISSUE THREAD

**Issue by bennettellis** [kubernetes/kubernetes#67631]
> /kind bug

**What happened**: Assigned PVC to Pod in Job. According to the documentation this should work, but the job pods are not assigned their volume mounts.

**What you expected to happen**: Expected the PVC (and I tried a host mount as well) to be assigned to the pod

**How to reproduce it (as minimally and precisely as possible)**: 
Create a PV
Create a PVC
Assign the claim to the spec and mount it in a pod within a job spec.template.spec
Observe that the job pod has neither the volume mounted, nor the PVC associated to it. Seems to just fail silently or just get ignored.

**Anything else we need to know?**: 
I am using Minikube with vm-drive=none
I am using Terraform to create the PV and the PVC -- but I have other PVs that work fine form TF
I am using kubernetes-client npm package to create the jobs

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Running Kubernetes with Minikube on an AWS EC2 Ubuntu 18.04 instance. I am using vm-driver=none with minikube.

- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux ip-10-0-101-223 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: Terraform, kubernetes-client (npm)
- Others:

Here's the call that I'm using to create the Job in the API using POST:
```
  const created = await client.apis.batch.v1.namespaces('default').jobs.post({
    body: {
      "apiVersion": "batch/v1",
      "kind": "Job",
      "metadata": {
        "name": "myJobName"
      },
      "spec": {
        completions: 1,
        paralellism: 1,
        activeDeadlineSeconds: 10,
        "template": {
          "spec": {
            volume: {
              name: "var-task",
              persistentVolumeClaim: {
                claimName: "var-task-claim"
              }
            },
            "containers": [
              {
                "image": "lambci/lambda:java8", 
                "name": "docker-lambda",
                "env": env.concat([
                  { name: "AWS_LAMBDA_FUNCTION_HANDLER", value: "com.test.Handler"},
                  { name: "AWS_LAMBDA_EVENT_BODY", value:"somemesssage"}
                ]),
                volumeMount: {
                  name: "var-task",
                  mountPath: "/var/task"
                }
              }
            ],
            "restartPolicy": "Never",
          },
          "backOffLimit": 2
        }
      }
    }
  });
```

Seems pretty straightforward.

The PVs look like this:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: var-task-code
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/task/code
    type: ""
```
The claim (from kubectl -o yaml output; this one shows as bound, but the pod does not show it as bound to it):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"5d03cf3e-a296-11e8-b59f-0e248a0c9f68","leaseDurationSeconds":15,"acquireTime":"2018-08-21T04:09:03Z","renewTime":"2018-08-21T04:09:33Z","leaderTransitions":0}'
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: 2018-08-21T04:09:01Z
  finalizers:
  - kubernetes.io/pvc-protection
  name: waveform-processor-claim
  namespace: default
  resourceVersion: "1278499"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/var-task-claim
  uid: ef61c6e5-a4f7-11e8-9e7b-e267fa715d27
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: pvc-ef61c6e5-a4f7-11e8-9e7b-e267fa715d27
status:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  phase: Bound
```
Here's what the job definition looks like from kubectl:
```
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2018-08-21T04:22:25Z
  labels:
    controller-uid: ce9849e6-a4f9-11e8-9e7b-e267fa715d27
    job-name: myJobName
  name: myJobName
  namespace: default
  resourceVersion: "1279484"
  selfLink: /apis/batch/v1/namespaces/default/jobs/myJobName
  uid: ce9849e6-a4f9-11e8-9e7b-e267fa715d27
spec:
  activeDeadlineSeconds: 10
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: ce9849e6-a4f9-11e8-9e7b-e267fa715d27
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: ce9849e6-a4f9-11e8-9e7b-e267fa715d27
        job-name: lambda-61927164-2e0d-4f25-863e-5392fb8889ea
    spec:
      containers:
      - env:
        - name: AWS_LAMBDA_FUNCTION_HANDLER
          value: ...
        - name: AWS_LAMBDA_EVENT_BODY
          value: ...
        image: lambci/lambda:java8
        imagePullPolicy: IfNotPresent
        name: docker-lambda
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: 2018-08-21T04:22:26Z
  conditions:
  - lastProbeTime: 2018-08-21T04:22:26Z
    lastTransitionTime: 2018-08-21T04:22:26Z
    status: "True"
    type: Complete
  startTime: 2018-08-21T04:22:25Z
  succeeded: 1
```
Perhaps I'm missing something. Do all volumes get un-mounted when a Pod in a job is "complete"? What's strange is that during the pod's lifecycle, it does appear that the volume is NOT mounted because the docker-lambda container complains that it cannot find the lambda job handler code.

**Comment by bennettellis** [comment]
*Update*: this looks to be a problem with either:
a) the REST API that kubernetes-client is call is silently dropping the volume for some unknown reason
b) the kubernetes-client itself is somehow failing to send all of my JSON to the REST API (looking at how this code works internally, I can't see that being the case)

So the question is why does the REST API give me back a 201 HTTP response when it seems to have discarded part of my JSON payload?

**Comment by bennettellis** [comment]
Not needed for JSON in JS unless identifier violates JS identifier rules. When the object is sent down the wire it will be properly stringified, and quoted.  The first issue was that I was not putting the volume in a volumes array wrapper nor the volumeMounts in an array wrapper. But past that and the volumes, while they are actually part of the definition of the pod now don't actually have the data in them that they should when the volume is mounted in the host.  Always empty.

**Comment by msau42** [comment]
Typo in your json: volume => volumes

**Comment by msau42** [comment]
Although it's strange, validation should have failed [here](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/apis/core/validation/validation.go#L2253:1) because the volume reference in volumeMounts should have not been found in the volumes array (which is empty in this case due to the typo)

**Comment by Xtigyro** [comment]
@bennettellis Hey - was that fixed?

**Comment by bennettellis** [comment]
I believe typo and other format issues were combining to produce the issues I was seeing, so it's probably most user/operator error here.

**Comment by Xtigyro** [comment]
@bennettellis Thanks for the reply, appreciated!
