### ISSUE TITLE
Kube daemonset  misscheduled after cluster autoscaling

### ISSUE THREAD

**Issue by vidhy** [kubernetes/kubernetes#67636]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Deamonset missschduled happens after cluster autoscaling.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a cluster using KOPS. Enable cluster autoscaler. When the autoscaler scales up the node count, describe the daemonset. 

**Anything else we need to know?**:

After scaling up happened I have 9 nodes running. and the daemonset pod is running fine on all 9 nodes. When i describe the daemonset, the desired and current number of nodes remain 8. Because of this number of nodes missscheduled is 1. After some time the desired and current value changes to 9.

![daemonsetmissscheduled](https://user-images.githubusercontent.com/6989806/44385095-01b41500-a53c-11e8-9a12-cf81d4f18aa4.PNG)

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.6
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`):
Linux ip-10-0-72-200 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
- Install tools:
KOPS
- Others:

**Comment by vidhy** [comment]
@kubernetes/sig-autoscaling-bug

**Comment by vidhy** [comment]
https://github.com/kubernetes/kube-state-metrics/issues/511

**Comment by tianshapjq** [comment]
you mention that it would scale up to 9 nodes after some time, is it indicating that this feature works fine but just taking too long?

**Comment by vidhy** [comment]
@tianshapjq  yeah right. it is just taking too long.

**Comment by k82cn** [comment]
any log of controller manager?
