### ISSUE TITLE
Client-go leader election can potentially split brain

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#67651]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug

**What happened**:

i wrote this test case and ran it in my local environment:

(it runs 10k+ candidates at the same time, and makes them request for leadership concurrently. and the request receiver will record every leader term. finally we'll check if the leader terms have overlapping record which proves that more than one leaders can exist at the same time.)

[https://gist.github.com/yue9944882/033c34992794714e41167ef02498c4db](https://gist.github.com/yue9944882/033c34992794714e41167ef02498c4db)

it proves that at the extreme cases, the leaderelection pkg doesn't working correctly as expected. 

```
E0821 18:48:11.205615   67982 leaderelection.go:286] Failed to update lock: force leader noxu-4966 change

E0821 18:48:12.767307   67982 leaderelection.go:286] Failed to update lock: force leader noxu-96002 change

E0821 18:48:12.932715   67982 leaderelection.go:286] Failed to update lock: force leader noxu-96002 change

E0821 18:48:16.751750   67982 leaderelection.go:286] Failed to update lock: force leader noxu-96398 change

E0821 18:48:18.920938   67982 leaderelection.go:286] Failed to update lock: force leader noxu-13560 change

E0821 18:48:19.447660   67982 leaderelection.go:286] Failed to update lock: force leader noxu-13560 change
	leaderelection_test.go:418: total: 13
	leaderelection_test.go:424: 2018-08-21 18:47:49 +0800 CST(noxu-101) to 2018-08-21 18:47:51 +0800 CST(noxu-101)
	leaderelection_test.go:424: 2018-08-21 18:47:51 +0800 CST(noxu-500) to 2018-08-21 18:47:54 +0800 CST(noxu-500)
	leaderelection_test.go:424: 2018-08-21 18:47:54 +0800 CST(noxu-39971) to 2018-08-21 18:47:56 +0800 CST(noxu-39971)
	leaderelection_test.go:424: 2018-08-21 18:47:56 +0800 CST(noxu-37287) to 2018-08-21 18:47:58 +0800 CST(noxu-37287)
	leaderelection_test.go:424: 2018-08-21 18:47:58 +0800 CST(noxu-40795) to 2018-08-21 18:48:03 +0800 CST(noxu-40795)
	leaderelection_test.go:424: 2018-08-21 18:48:03 +0800 CST(noxu-47712) to 2018-08-21 18:48:05 +0800 CST(noxu-47712)
	leaderelection_test.go:421: [DIRTY RECORD]: 
	leaderelection_test.go:424: 2018-08-21 18:48:05 +0800 CST(noxu-45996) to 2018-08-21 18:48:05 +0800 CST(noxu-45996)
	leaderelection_test.go:424: 2018-08-21 18:48:05 +0800 CST(noxu-11900) to 2018-08-21 18:48:09 +0800 CST(noxu-11900)
	leaderelection_test.go:424: 2018-08-21 18:48:09 +0800 CST(noxu-4966) to 2018-08-21 18:48:11 +0800 CST(noxu-4966)
	leaderelection_test.go:424: 2018-08-21 18:48:11 +0800 CST(noxu-96002) to 2018-08-21 18:48:13 +0800 CST(noxu-96002)
	leaderelection_test.go:424: 2018-08-21 18:48:13 +0800 CST(noxu-19522) to 2018-08-21 18:48:15 +0800 CST(noxu-19522)
	leaderelection_test.go:424: 2018-08-21 18:48:15 +0800 CST(noxu-96398) to 2018-08-21 18:48:18 +0800 CST(noxu-96398)
FAIL
```

**What you expected to happen**:

it works safely.

**How to reproduce it (as minimally and precisely as possible)**:

run the case.

**Anything else we need to know?**:

my local environment (MBP) is 16Gb, Corei7. works pretty well.

**Comment by yue9944882** [comment]
it's initially written by #16830

**Comment by mikedanese** [comment]
Does your client allow updates where resource versions conflict? The leader election client relies on OCC of the underlying store.

**Comment by yue9944882** [comment]
thanks @mikedanese 
we found this problem when using a java client sdk ported from client-go. it could be the resource version incorrectly reset to "0". taking a further look. 😅 btw the test is not correct either. 🙃
