### ISSUE TITLE
kubectl delete doesn't wait for load balancer to be deleted

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#67665]
/kind bug
/sig cli

**What happened**:
`kubectl delete service/example-loadbalancer` returns `service "service/example-loadbalancer" deleted` immediately, even though the cloud controller hasn't yet deleted the loadbalancer from the cloud.

**What you expected to happen**:
kubectl delete with the default --wait=true setting should not return or remove the service entry until the 'Deleted Load Balancer' event has fired.

Because the service entry has disappeared `kubectl wait` is of no use. 

**How to reproduce it (as minimally and precisely as possible)**:

- Create a service using the 'Load Balancer' type on a cloud and wait for it to initialise fully
- watch the events queue `kubectl get events`,
- run `kubectl delete` on the service
- note that the command returns before the deleted load balancer event is fired

**Anything else we need to know?**:

Running using the Brightbox external cloud-provider

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`):
Linux srv-4351f 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Terraform & kubeadm 
- Others:

**Comment by liggitt** [comment]
If the service object was removed before it should be, this is a bug in the service api, not the cli


The Event API is not a reliable message bus, and is advisory, not intended to drive functional behavior. 

@jhorwit2 weren't you working on adding a finalizer in service objects to keep them from being deleted prior to LB cleanup?
