### ISSUE TITLE
Avoid thundering herd of relist

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#6770]
We currently relist for at least 2 reasons:
1. Correctness, aka recovering from random issues we can't explain
2. Etcd's watch window

This could lead to a thundering herd  because all our major watch clients open up connections at around the same time. A quick and dirty way to avoid this is to pick a random timeout server side (or  set the sever timeout to 10m and allow every reflector started without a relist period to pick a random number between 5-10).

Arguments for server side:
- It is easier to generate pseudo randomness from a single server process than n clients

Arguments for client side:
- We already have a relist timeout idiom on client, this needs to integration with the server setting
- It feels like the clients should control when they relist, and the server should control when the connection is dropped, but I'm willing to compromise on the SoC for the sake of simplicity.

@lavalamp

**Comment by lavalamp** [comment]
2 above is misleading-- etcd's watch window doesn't (shouldn't) expire on you if you managed to start a watch while still in the window. If a watch times out, then you'll probably be outside of the window. But this is because the watch timed out, not because of etcd's watch window. (caveat: etcd could ameliorate this by sending you periodic heartbeats with a more recent index to watch at, and they're planning on doing this last I heard.)

**Comment by bprashanth** [comment]
Ah, that's what I mean to say. if a client that never received an update forever breaks the connection because of a server timeout, we need to relist to ensure our resource version is in the window.

**Comment by fgrzadkowski** [comment]
I have observed the same result in density tests. Most very slow requests happen when kubelets are relisting pods.

**Comment by bprashanth** [comment]
I'm gathering some data to understand this better. That should point us in the right direction wrt how fancy we want to get trying to prevent this.

**Comment by davidopp** [comment]
As discussed in #4521 we should just increase the relist interval by a lot.

**Comment by bprashanth** [comment]
We've already randomized the watch timeouts, I'm also doing as @davidopp suggested but making sure we drop it low enough in our e2e tests

**Comment by lavalamp** [comment]
This has come up again with larger clusters--
* Do we drop watches when under heavy load?
* If yes, is it because we exceed the watch channel's limit? watchChannelHWM records this - https://github.com/kubernetes/kubernetes/blob/e95e3dec4249980b1737f5ff9e415f8a5ad7b2b0/pkg/storage/etcd/etcd_watcher.go#L218
* If we drop watches under load, do we drop a bunch of watches at the same time in a way that defeats our randomized timing?

Seems important to figure out if there's a problem.

@gmarek maybe you can keep your eyes open for answers to these questions?

**Comment by wojtek-t** [comment]
@lavalamp - I will try to figure it out next week. However, from numbers that @gmarek showed me, I'm not entirely sure it's the watch cause (in particular, the time between scheduling and starting it by Kubelet was pretty low - and it contains one watch (Kubelet is watching its pods)). So I'm not entirely sure what was happening there, but I think it's not watch in general - maybe some special case of watch? Or something completely different?

**Comment by gmarek** [comment]
@lavalamp - sure. I'll run some more experiments, but they take a lot of time - both wall time and CPU time if I'm to pay closer attention to what's happening.

**Comment by lavalamp** [comment]
Thanks-- to be clear, I believe we've solved this issue already, back when I added the queue and the HWM stuff. I just want to make sure it doesn't come back at bigger scales.

**Comment by timothysc** [comment]
@lavalamp @wojtek-t still an issue or is this another issue around the rate limited watches?

**Comment by lavalamp** [comment]
@timothysc I don't think anyone has investigated my questions above. https://github.com/kubernetes/kubernetes/issues/6770#issuecomment-161816109

**Comment by lavalamp** [comment]
I mean, I definitely do not believe this is a current issue. But it may be
worth a double check, which is why I've left the issue open.

On Tue, Feb 16, 2016 at 1:48 PM, Timothy St. Clair <notifications@github.com

**Comment by wojtek-t** [comment]
I agree with @lavalamp - we need to check it and probably add some integration test for it.
However, I'm decreasing the priority to P2 since ti doesn't seem to be a problem now.

**Comment by timothysc** [comment]
So we've done a ton of work to limit the relist behavior, and I'm fairly certain there still exist some conditions where the relists can be re-triggered, but not in a thundering herd fashion.   Given the age of the original issues, I think it makes more sense at this point to open specific issues on the sub-elements that may still need to be addressed.

**Comment by wojtek-t** [comment]
>Given the age of the original issues, I think it makes more sense at this point to open specific issues on the sub-elements that may still need to be addressed.

+1
