### ISSUE TITLE
How to use http to instead https 

### ISSUE THREAD

**Issue by wwyhy** [kubernetes/kubernetes#67710]
Hello,

I am trying to set up the log collection system by fluentd-elasticsearch under addons folder. 
when I deploy the fluentd-es-ds.yaml, I got below error (certificate verify failed). 
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml

So how can I use http to instead https(https://172.21.0.1:443/api)?  

--------------ERROR------------
$ kubectl -n kube-system logs -f fluentd-es-v2.2.0-4snfw
2018-08-22 13:53:15 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://172.21.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed"

Thanks!
Br, Wwyhy

**Comment by neolit123** [comment]
/sig scalability
for fluentd-es.

**Comment by grantstephens** [comment]
@wwyhy Did you figure this out? I run ran into the same problem.
