### ISSUE TITLE
Cloud providers should report node hostname address types

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#67714]
https://github.com/kubernetes/kubernetes/commit/7828e5d0f97c455de4ff93d43f11f953a7951916 made cloud providers authoritative for the addresses reported on Node objects, so that the addresses used by the node (and requested as SANs in serving certs) could be verified via cloud provider metadata.

This had the effect of no longer reporting addresses of type `Hostname` for Node objects for some cloud providers. Cloud providers that have the instance hostname available in metadata should add a `type: Hostname` address to node status.

This issue tracks the cloud providers updated to do so:
- [x] AWS - https://github.com/kubernetes/kubernetes/pull/67715
- [x] Azure - already reported Hostname address
- [x] Cloudstack - https://github.com/kubernetes/kubernetes/pull/67719
- [x] GCE - https://github.com/kubernetes/kubernetes/pull/63512
- [x] OpenStack - #67748
- [x] VSphere - #67922

**Comment by liggitt** [comment]
cc @mikedanese @awly

**Comment by FengyunPan2** [comment]
Get it, I will report it for openstack cloud provider.

**Comment by tpepper** [comment]
There have been a number of persistent failures in test grid for a few weeks (eg: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1423) where the failure signature is:
```
Error from server: error dialing backend: x509: cannot validate certificate for 10.128.0.2 because it doesn't contain any IP SANs
```

Related?

**Comment by liggitt** [comment]
No, those likely are set up with the kubelet self-signing it's serving certificate

**Comment by mikedanese** [comment]
I think that error is from CRI streaming. From @Random-Liu :

> Default config of containerd 1.1 doesn't work with Kubernetes 1.11+. We'll build another cos_containerd image for Kubernetes 1.11.
> 
> The problem is that:
> 1) In containerd 1.1, we enabled TLS on GCE for security.
> 2) In Kubernetes 1.11, we added the kubelet streaming proxy, and use it by default.
> 3) Kubelet streaming proxy doesn't use TLS, so it will get `x509: certificate signed by unknown authority` when talking with containerd 1.1.
> 4) In coming containerd 1.2, we've disabled TLS to work with Kubernetes 1.11.

**Comment by Random-Liu** [comment]
@mikedanese Those nodes are not running containerd. I think it should be a different issue. :)
