### ISSUE TITLE
watch conformance test: test more resources than just config map

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#67718]
It looks like the existing watch conformance test only tests configmaps.

We should generalize it. Given a list of valid objects of different kinds, we should be able to run the existing test (which tweak labels) generically.

/sig api-machinery

**Comment by lavalamp** [comment]
cc @jennybuckley

**Comment by hh** [comment]
/assign @timothysc

Is this similar enough to what you are looking for with regard to watch?

**Comment by rajibmitra** [comment]
@hh  can I assign it to myself ?

**Comment by spiffxp** [comment]
pinging for signs of life, has any progress been made here?
