### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [kubernetes/kubernetes#67726]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I visited https://kubernetes.io/docs/reference/kubectl/kubectl/

I clicked on the link "kubectl apply".

It said:

404 Page not found
Sorry, this page was not found. :(

**What you expected to happen**:

I expected it to show me documentation on the "kubectl apply" command.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

@kubernetes/sig-docs-bugs

**Comment by nikhita** [comment]
Thanks for reporting this, @Jacob-Burckhardt! There is an issue about this in the docs repo already: https://github.com/kubernetes/website/issues/9791.

Closing this in favor of https://github.com/kubernetes/website/issues/9791. 
/close
