### ISSUE TITLE
can not create cluster on NIC with internal IP address

### ISSUE THREAD

**Issue by FOSquare** [kubernetes/kubernetes#67725]
/kind bug

/network

**What happened**:

I have 16 servers with two interfaces, one 1Gb/s with external IP for remote connection. one 10Gb/s with internal IP for data communcation. I want to create K8s cluster on the NIC with private/internal IP address, but it always create the network on the NIC with external IP address.

**What you expected to happen**:

I expect to create the cluster on the 10Gb/s NIC with internal IP address

**How to reproduce it (as minimally and precisely as possible)**:

sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.0.151  --kubernetes-version=v1.11.2

It will shows:

.....
.....
You can now join any number of machines by running the following on each node
as root:

  kubeadm join 192.168.0.151:6443 --token csobw3.qs35fz0n6qlw1al4 --discovery-token-ca-cert-hash sha256:c9e6234a59b57e6ae92f719aed4a1c88c978427b2410d61505a9d0fe4ebc94c4

But when I use kubectl get nodes -o wide to check the nodes, it lists

NAME      STATUS     ROLES     AGE       VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aether    NotReady   master    3m        v1.11.2   131.155.34.*   <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0

It is on the 131.155.34.*, rather than 192.168.0.55.

**Anything else we need to know?**:
 I tried to use kubeadm reset, the resutls are the same.

**Environment**:
- Kubernetes version (use `kubectl version`):   "v1.11.2"
- Cloud provider or hardware configuration:   Dell Poweredge R230
- OS (e.g. from /etc/os-release):                      Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):                               4.13.0-36-generic                         
- Install tools:                                                 I use ansible to install kubeadm, kubelet and kubectl
- Others:

Thanks a lot.

**Comment by dixudx** [comment]
>  it always create the network on the NIC with external IP address.

This does not harm your cluster. The cluster can work as expected.
If you really want to modify this IP address, you can add `KUBELET_EXTRA_ARGS=
--node-ip=<your-desired-ip>` in `/etc/default/kubelet` (debian) or `/etc/sysconfig/kubelet` (rpm).

> NAME STATUS ROLES AGE VERSION INTERNAL-IP EXTERNAL-IP OS-IMAGE KERNEL-VERSION CONTAINER-RUNTIME
aether NotReady master 3m v1.11.2 131.155.34.* Ubuntu 16.04.4 LTS 4.13.0-36-generic docker://17.3.0

You should apply a [cni network](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network) for now.

**Comment by FOSquare** [comment]
Thanks a lot. I know that when I apply the flannel network, the status of the nodes in the cluster will be ready. No problem on this part. I have get success on the application deployment at 1Gb/s cluster.

When I did as what you told me :"add KUBELET_EXTRA_ARGS= --node-ip=192.168.0.151" I get the below results.

NAME      STATUS     ROLES     AGE       VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aether    NotReady   master    1m        v1.11.2   <none>        <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0
The INTERNAL-IP is none. 

When i try on another server with IP 192.168.0.51, your solution is fine. I could see 
NAME      STATUS     ROLES     AGE       VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
uranus    NotReady   master    2m        v1.11.2   192.168.0.51   <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0

Now, the INTERNAL-IP is 192.168.0.51. But when I use the generated command to join another node with IP 192.168.0.53. The cluster is not what I want to created at internal IP subnetwork.

First, in the worker node, I add the private IP 192.168.0.53 of the worker node in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
--node-ip=192.168.0.53

Then I use the command to join this worker node into the cluster. but when I check the "kubectl get nodes -o wide".  It shows 

nesoi1            Ready     <none>    3h        v1.11.2   131.155.35.*   <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0
uranus            Ready     master    3h        v1.11.2   192.168.0.51   <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0

The INTRENAL-IP of Nesoi is 131.155.35.*, is not 192.168.0.53 which I expect. 

I think maybe this does not harm my cluster, as you said. But when I run Spark example applications 
I can see traffic on the 1Gb/s port with external IP address. There is no traffic on the 10Gb/s port with internal IP address. So there must be something wrong.

Could you kindly help me to check with it. Thanks a lot.

**Comment by FOSquare** [comment]
Now my cluster are shown below. 

fyan@ananke:~$ kubectl get nodes -o wide
NAME              STATUS     ROLES     AGE       VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
ananke            Ready      master    20h       v1.11.2   192.168.0.101   <none>        Ubuntu 16.04.4 LTS   4.15.0-33-generic   docker://17.3.0
erebos            Ready      <none>    1h        v1.11.2   192.168.0.105   <none>        Ubuntu 16.04.4 LTS   4.15.0-33-generic   docker://17.3.0
fyan-hephaestus   Ready      <none>    17h       v1.11.2   192.168.0.55    <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0
phanes            Ready      <none>    24m       v1.11.2   192.168.0.107   <none>        Ubuntu 16.04.4 LTS   4.15.0-33-generic   docker://17.3.0
thalassa          Ready      <none>    24m       v1.11.2   192.168.0.103   <none>        Ubuntu 16.04.4 LTS   4.15.0-32-generic   docker://17.3.0
uranus            NotReady   <none>    17h       v1.11.2   192.168.0.51    <none>        Ubuntu 16.04.4 LTS   4.13.0-36-generic   docker://17.3.0


I think it is cluster now on the internal IP address. But the problem is that when I deploy applicaiton, I still not see traffic on this 10Gb/s port with internal IP address, it is very strange. But that is not the cluster creation problem. So I will close this issue, and open a new issue.

Thanks guys.
