### ISSUE TITLE
Conformance tests for ARM architecture

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#67720]
Similar to https://k8s-testgrid.appspot.com/sig-node-ppc64le#conformance we need to run tests against ARM based k8s installations

/cc @lubinsz @vielmetti

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/38067

/sig testing

**Comment by dims** [comment]
Please see https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#conformance-tests

**Comment by vielmetti** [comment]
Yes, @dims @lubinszARM we need to do tests on Arm.

The current Works on Arm cluster has a request, per https://github.com/WorksOnArm/cluster/issues/103 .

At the instant my inventory of arm64 equipment is very low, so I'm hoping that you have a deployment plan that can do spot market and automated setup/teardown. If you can do all of that, then resources are pretty easy.

**Comment by jeefy** [comment]
@vielmetti  Could we leverage the Packet/CNCF allocation? Seems like this would be beneficial to the ecosystem. 

This is something I could probably work on in the next month or two if no one else wants to tackle it (or can do it sooner)

**Comment by mrbobbytables** [comment]
My time is pretty blocked up at the moment, but I should be able to help @jeefy where its needed.

**Comment by vielmetti** [comment]
yes, this looks like a Packet/CNCF collaboration would be great. I am happy to direct but not to lead!

**Comment by mrhillsman** [comment]
thx @dims

@lubinszARM @vielmetti we can offer resources for CI via OpenLab - https://openlabtesting.org - we are moving to GitHub issues for resource requests but not yet so if you fill out the form on the site we can make it happen quite quickly in terms of the one ARMv8 node request

**Comment by lubinsz** [comment]
@dims 
@vielmetti 
After fixing PV issues, all conformance test cases can be passed on Arm platform.
----
Ran 166 of 996 Specs in 5458.376 seconds
SUCCESS! -- 166 Passed | 0 Failed | 0 Pending | 830 Skipped PASS
----
The next step should be to upload these logs to Google storage.
Is that right?

**Comment by dims** [comment]
@lubinsz the google storage thing is for automatically loading results from CI jobs. not test runs on developer style environments. We will have to find an envionment where we can run these on a daily basis

Please however do check the list of tests that run. compare with:
https://k8s-gubernator.appspot.com/build/ppc64le-kubernetes/logs/ci-conformance-kubernetes/1691
https://k8s-gubernator.appspot.com/build/k8s-conformance-openstack/periodic-logs/ci-cloud-provider-openstack-acceptance-test-e2e-conformance/1535214715

Thanks,
Dims

**Comment by lubinsz** [comment]
@dims 
Hi, I have reviewed the ci project 
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml#L11-L30

In the end of the 'post.yaml', it will upload the e2e logs into gs://${GCS_BUCKET}/...
In your case, the bucket is https://console.cloud.google.com/storage/browser/k8s-conformance-openstack

So, for me,  I need to do 3 things：
1, create a CI job in openlab, such as:
         run e2e confromance test in run.yaml.
          upload log in post.yaml
2, Create a GCS bucket of choice & Create a ServiceAccount for the uploader
           such as: 
           gcloud auth activate-service-account --key-file sa.json
            gsutil acl ch -u All:R gs://your-bucket-here
           In your case, the bucket is 'k8s-conformance-openstack'.
            For me, I need to buy a GCS bucket for arm-e2e-test.
3, deliver a patch into https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml
           such as: just like this pr
           https://github.com/kubernetes/test-infra/pull/3477/files

Is that right?

Thanks.

**Comment by dims** [comment]
@lubinsz Right on all counts. for #2, let's get @BenTheElder 's opinion there may be existing bucket that may be reused.

**Comment by BenTheElder** [comment]
Similar to https://github.com/kubernetes/community/issues/2594#issuecomment-416651779 would you mind waiting a bit longer? I expect to need to migrate this slightly soon, it'll be easier if we can start you off on the improved setup 🤞

**Comment by BenTheElder** [comment]
per discussion here https://github.com/kubernetes/community/issues/2594#issuecomment-419308994 going forward with the current route for now, we'll sort out migrating everyone soon.

`gs://k8s-conformance-arm` has been created, I've sent you an email with the service account key

**Comment by lubinsz** [comment]
@BenTheElder 
Got it. I have received the mail.
I will finished the e2e job for Arm as soon as possible.
Thank you.

**Comment by BenTheElder** [comment]
Great! `/assign` me when you [PR testgrid](https://github.com/kubernetes/test-infra/pull/8347) to display your job(s) (and please send a PR!) 😄

**Comment by dims** [comment]
@lubinsz what is the frequency of these CI tests? i don't see much data here https://k8s-testgrid.appspot.com/sig-node-arm64#conformance

Also, please see notes from @BenTheElder on better data capture - https://github.com/kubernetes/test-infra/pull/9399#issuecomment-421893660

**Comment by lubinsz** [comment]
@dims @BenTheElder 
Hi all,
Can you check the result? https://k8s-testgrid.appspot.com/sig-node-arm64#conformance

Currently, I ran the test script  in a virtual machine daily.
The k8s community publishes several new versions per day, I try to test each versions with my script.
And now, the result has been labeled as "PASSING".

**Comment by dims** [comment]
@lubinsz cross checking with https://gubernator.k8s.io/build/ppc64le-kubernetes/logs/ci-conformance-kubernetes/2041 looks good!

**Comment by lubinsz** [comment]
@dims 
Can we close this issue?
