### ISSUE TITLE
Unable use localhost:<nodeport> with IPVS

### ISSUE THREAD

**Issue by lbernail** [kubernetes/kubernetes#67730]
/kind bug
/sig network
/area ipvs

**What happened**:
Connecting to a service using a nodeport and the loopback address does not work

**What you expected to happen**:
Being able to connect to a nodeport using the loopback (it works with IPVS)

**How to reproduce it (as minimally and precisely as possible)**:
Create a nodeport service and try to connect to it using localhost:<nodeport>

**Anything else we need to know?**:
The IPVS configuration looked fine:
```
sudo ipvsadm -Ln -t 127.0.0.1:32116 --stats
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
TCP  127.0.0.1:32116                     1        2        0      120        0
  -> 10.x.0.99:5000                     0        0        0        0        0
  -> 10.x.0.115:5000                    1        2        0      120        0
  -> 10.x.0.130:5000                    0        0        0        0        0
```
The masquerading mark is applied properly
```
Chain KUBE-MARK-MASQ (3 references)
    pkts      bytes target     prot opt in     out     source               destination
       2      120 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-NODE-PORT (1 references)
    pkts      bytes target     prot opt in     out     source               destination
       2      120 KUBE-MARK-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain KUBE-SERVICES (2 references)
    pkts      bytes target     prot opt in     out     source               destination
       2      120 KUBE-NODE-PORT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Kubernetes nodeport TCP port for masquerade purpose */ match-set KUBE-NODE-PORT-TCP dst
```
However the MASQUERADE rule in the KUBE-POSTROUTING is not reached
```
Chain KUBE-POSTROUTING (1 references)
    pkts      bytes target     prot opt in     out     source               destination
       0        0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000
```

tcpdump does not show any traffic targeting port 5000. It looks like the kernel is dropping connections with source 127.0.0.1 and an external destination before reaching the POSTROUTING chain.

Changing the local route table fixed the issue:
```
sudo ip route change 127.0.0.1 dev lo proto  kernel scope host src <node ip> table local
```

**Environment**:
- kubelet version: `v1.10.5`
- kube-proxy version: `v1.11.1`
- OS (e.g. from /etc/os-release): `ubuntu 1804`
- Kernel: `4.15`

**Comment by m1093782566** [comment]
Nice catching @lbernail 

I seldom use loopback in my production environment, but glad to see this issue being fixed.

IIUC, the command you provide is trying to tell kernel that any traffic sending to 127.0.0.1 is "actually" from the NODE IP.

My question is what NODE_IP should we bind for loopback address? Does the fix has any side effect?

cc @Lion-Wei for testing.

**Comment by lbernail** [comment]
I'm not sure that changing the local route table is a great fix but it helps understand the issue.
I don't really understand why it works with iptables and not ipvs. Probably because IPVS load-balancing does not happen at the same moment in the network stack

**Comment by m1093782566** [comment]
> Probably because IPVS load-balancing does not happen at the same moment in the network stack

Yeah, it seems.

**Comment by chadswen** [comment]
Great find. We ran into this when testing our transition to IPVS since a few of our clients depend on localhost:nodeport.

Is there anyone that could comment that might know more conclusively if changing the local route table has side effects? We're itching to ditch iptables mode and this is the last issue we've found.

**Comment by lbernail** [comment]
I really meant to look into it but I don't have the bandwidth at the moment
I'd like to look in details at the ipvs data path to know why it works with iptables and not ipvs to see if we can find a lighter solution
This one should work fine in most cases but my guess is it could create hard to debug issues that will be application specific (it shouldn't matter much if the node is only running kubelet/runtime and containers)

**Comment by Lion-Wei** [comment]
@lbernail I think you can find part of the answer here. 
https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

I will give a full test, and I think our ipvs ci can also cover most use cases, so don't worry. : )

**Comment by miaoshixuan** [comment]
@lbernail I changed my local route, everything works well.  But when I restart kubelet, It will keep crash.
here is my kubelet config
```
kubelet --logtostderr=false --log-dir=/var/log/kubernetes/kubelet --v=2 \
--address=192.168.1.103 --node-ip=192.168.1.103 --hostname-override=192.168.1.103 --read-only-port=0 \
--allow-privileged=true --cgroup-driver=systemd \
--anonymous-auth=false --client-ca-file=/etc//ssl/ca.pem --tls-cert-file=/etc/ssl/kube/kubelet.pem --tls-private-key-file=/etc/ssl/kube/kubelet-key.pem 
--cluster-dns=192.168.0.100 \
--kubeconfig=/etc/kubernetes/kubelet.kubeconfig
```
log here
```
I1228 17:17:40.616552   31553 docker_service.go:271] Setting cgroupDriver to systemd
I1228 17:17:40.616729   31553 kubelet.go:682] Starting the GRPC server for the docker CRI shim.
I1228 17:17:40.616901   31553 docker_server.go:59] Start dockershim grpc server
F1228 17:17:40.618414   31553 docker_service.go:408] Streaming server stopped unexpectedly: listen tcp 127.0.0.1:0: bind: cannot assign requested address
goroutine 48 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc00000e001, 0xc000e2e000, 0x57c, 0x2710)
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xd4
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x6a6eaa0, 0xc000000003, 0xc000da0000, 0x65b8cb2, 0x11, 0x198, 0x0)
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:720 +0x18e
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x6a6eaa0, 0x3, 0x3c078e5, 0x29, 0xc00007ffb8, 0x1, 0x1)
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14b
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x3c078e5, 0x29, 0xc00007ffb8, 0x1, 0x1)
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).Start.func1(0xc00098e8c0)
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_service.go:408 +0x99
created by k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).Start
	/home/xh/k8scode/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_service.go:406 +0x7d
```


**Environment**:
- Kubernetes version: 1.11.2
- OS: centos7.4
- Kernel: 3.10.0-693.el7.x86_64

**Comment by lbernail** [comment]
@miaoshixuan Interesting, I never tested this fix in depth but just tried to find a way to make it work. Maybe changing the default route for 127.0.0.1 prevents binding on localhost? Sound suprising. I'll try and reproduce next week

**Comment by m1093782566** [comment]
@miaoshixuan 

We can work together on it if you really want to see the issue get fixed though I suspect few people will use localhost for nodeport in production environment.

**Comment by Deepak1100** [comment]
hi,
i am using dnsmasq which is running on each node and cluster-dns flag of kubelet is nodeIP. it was working until i switched proxyMode to IPVS and it stopped working now. if I put coredns service ip in pods resolve.conf then dns resolution is working.
i have tried to telnet to node ip from pods and it was reachable but curl and dns is failing

**Comment by lbernail** [comment]
@Deepak1100 this is surprising, if you can ping the nodeip from the pod you should be able to access dnsmasq. Does dnsmasq bind the nodeip? Can you try to connect to it directly using dig/nslookup?

**Comment by Deepak1100** [comment]
@lbernail i tried to do dig and i am getting empty A record.(i.e it does not resolve)
one more thing i tested that if in dnsmasq pods I change coredns serviceIP to PodIP then resolution is working.
I am able to reach to coredns service IP if i hit it from any pods directly. but if traffic goes from dnsmasq its not working.
traffic flow is like pod1(node1)-> node1-IP:53(pod2)->(snat/dnat)->pod3(node2).

**Comment by lbernail** [comment]
@Deepak1100 this seems to indicate that dnsmasq can't access the serviceIP. I assume dnsmasq is running on the host network with the coredns serviceIP as upstream?
If so, can you check that you can access the coredns serviceIP from the host?

Also, which version of kube-proxy are you running?

**Comment by Deepak1100** [comment]
@lbernail  i am running 1.12.1 kube-proxy
and yes i am running dnsmasq as you have mention. and i tried to do dig from inside dnsmasq pods using serviceIP of coredns and it was able to resolve fluentd-service
``` dig fluentd-service.logging.svc.cluster.local @100.64.0.10

; <<>> DiG 9.9.4-RedHat-9.9.4-72.el7 <<>> fluentd-service.logging.svc.cluster.local @100.64.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62133
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fluentd-service.logging.svc.cluster.local. IN A

;; ANSWER SECTION:
fluentd-service.logging.svc.cluster.local. 5 IN	A 100.69.115.87

;; Query time: 2 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Wed Jan 09 11:21:25 UTC 2019
;; MSG SIZE  rcvd: 127
```
that mean it is reachable

**Comment by freehan** [comment]
Ping

**Comment by lukaszo** [comment]
Issue still exists so reopening

**Comment by lukaszo** [comment]
@lbernail  @Lion-Wei any updates?

**Comment by chendotjs** [comment]
After a little dig into the kernel, failing to connect `localhost:<nodeport>` can be explained.

Assume we are visiting `http://127.0.0.1:<nodeport>`, every packet will first pass through [`ip_vs_nat_xmit`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L735-L820). Then after some check, it runs to https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L756. [`__ip_vs_get_out_rt`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L307-L414) is used to search for route to remote server, k8s pods in our case. Take a deeper look at [`__ip_vs_get_out_rt`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L307-L414), after validating route cache or finding route via `do_output_route4`, it comes to [`crosses_local_route_boundary`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L166-L204) to judge whether the searched route can pass cross-local-route-boundary check.

Copy the code of [`crosses_local_route_boundary`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L166-L204) here and go deeper.
```c
static inline bool crosses_local_route_boundary(int skb_af, struct sk_buff *skb,
						int rt_mode,
						bool new_rt_is_local)
{
	bool rt_mode_allow_local = !!(rt_mode & IP_VS_RT_MODE_LOCAL);
	bool rt_mode_allow_non_local = !!(rt_mode & IP_VS_RT_MODE_NON_LOCAL);
	bool rt_mode_allow_redirect = !!(rt_mode & IP_VS_RT_MODE_RDR);
	bool source_is_loopback;
	bool old_rt_is_local;

#ifdef CONFIG_IP_VS_IPV6
	/* omit ipv6 */
#endif
	{
		source_is_loopback = ipv4_is_loopback(ip_hdr(skb)->saddr);
		old_rt_is_local = skb_rtable(skb)->rt_flags & RTCF_LOCAL;
	}

	if (unlikely(new_rt_is_local)) {
		if (!rt_mode_allow_local)
			return true;
		if (!rt_mode_allow_redirect && !old_rt_is_local)
			return true;
	} else {
		if (!rt_mode_allow_non_local)
			return true;
		if (source_is_loopback)
			return true;
	}
	return false;
}

```

For nat mode of IPVS, `rt_mode` is assigned as `IP_VS_RT_MODE_LOCAL | IP_VS_RT_MODE_NON_LOCAL | IP_VS_RT_MODE_RDR` as https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L757-L759 indicates and `new_rt_is_local` is 0 due to https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L363.

`source_is_loopback` will be `true` because source address `ip_hdr(skb)->saddr` is `127.0.0.1`. The five booleans defined in [`crosses_local_route_boundary`](https://github.com/torvalds/linux/blob/v4.18/net/netfilter/ipvs/ip_vs_xmit.c#L166-L204) will all be `true` in this case. So we finally fall into here
```c
if (source_is_loopback)
	return true;
```
 and never pass the cross-local-route-boundary check.

This can also supports @lbernail 's trial by modifying local route table. The src of the generated packet is not `127.0.0.1` any more, so it can pass the cross-local-route-boundary check and get into pods.

**Comment by kong62** [comment]
can not access  127.0.0.1:NodePort
```
# kubectl version --short 
Client Version: v1.18.5
Server Version: v1.18.5
```

```
# kubectl get pod -o wide|grep kraken-agent
kraken-agent-cj4cn                   1/1     Running   2          107m   10.244.115.126   k8s05   <none>           <none>
kraken-agent-g4mqt                   1/1     Running   2          107m   10.244.149.229   k8s07   <none>           <none>
kraken-agent-krnkx                   1/1     Running   2          107m   10.244.77.30     k8s04   <none>           <none>
kraken-agent-l9mxb                   1/1     Running   2          107m   10.244.176.119   k8s08   <none>           <none>
kraken-agent-lsvps                   1/1     Running   2          107m   10.244.89.167    k8s06   <none>           <none>
kraken-agent-mlbg4                   1/1     Running   2          107m   10.244.23.14     k8s09   <none>           <none>

# kubectl get svc|grep kraken-agent           
kraken-agent         NodePort    10.96.89.215    <none>        80:30081/TCP   108m

# ip a|grep 192.168.
    inet 192.168.32.172/24 brd 192.168.32.255 scope global dynamic noprefixroute eth0

# ss -tnlp|grep 30081
LISTEN    0         65535               0.0.0.0:30081            0.0.0.0:*       users:(("kube-proxy",pid=2776,fd=11))                                          
```


test:
```
Pod IP ok：
# nc -nvz 10.244.115.126 8081
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 10.244.115.126:8081.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

Service IP  ok：
# nc -nvz 10.96.89.215 80
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 10.96.89.215:80.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

Node IP  ok：
# nc -nvz 192.168.32.172 30081
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.32.172:30081.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

ssh to node which pod on , 127.0.0.1 failed：
# nc -nvz 127.0.0.1 30081
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

**Comment by chengzhycn** [comment]
@lbernail I tried to add the routing entry, and it worked for flow visiting the `localhost:<nodeport>`. But the `ping 127.0.0.1` will be failed with this error output below:
```
ping: sendmsg: Operation not permitted
```

**Comment by uablrek** [comment]
Since support for ipv6 ([::1]:nodeport) will never work (not working for proxy-mode=iptables either) and support for 127.0.0.1:nodeport for proxy-mode=ipvs requires a kernel update that is not planned and likely will not be accepted I will close this issue.

If you _really_ must use 127.0.0.1:nodeport please use proxy-mode=iptables (and be aware of the security issues).

Please check https://github.com/kubernetes/kubernetes/issues/96879 for more details.

/close
