### ISSUE TITLE
An error occured when deleting a job and then creating a same one

### ISSUE THREAD

**Issue by 27149chen** [kubernetes/kubernetes#67751]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
An error occured when I delete a job and then create a same one, error is:
object is being deleted: jobs.batch "xxxx" already exists

**What you expected to happen**:
No error should happen

**How to reproduce it (as minimally and precisely as possible)**:
Delete a job, and then create a new one immediately. 
Does it mean the DELETE action is async?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tanshanshan** [comment]
I think it is not a bug , print deleted message  not means finishing delete 
Not just job, pod and other resouces also the same

**Comment by 27149chen** [comment]
@tanshanshan  Pod is a bit different since it will enter a terminating stage, but I was thinking that a job will be deleted immediately. So you mean that all resources deletion are async?
If so, when to create a same resource? by getting it again after deletion or some way else?
