### ISSUE TITLE
HPA metrics client assumes all resources are namespaced

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#67777]
/kind bug

The HPA controller's metrics client currently assumes all objects referenced in the `Object` metrics type are namespaced (unless it's namespaces themselves).  This is wrong -- we should be using a RESTMapper to figure out the scope.

When we do this, we need to make certain that we scope down the HPA's default permissions so that a normal user can't use the HPA to discover metrics that they otherwise shouldn't be able to (e.g. node metrics).

**Comment by DirectXMan12** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by DirectXMan12** [comment]
(I can take this one if need be, but it's also low-hanging fruit, so feel free to grab it if you're a new contributor and want something to get started with)

**Comment by bartekzurawski** [comment]
Can I try to working on this?

**Comment by DirectXMan12** [comment]
certainly
/assign bartekzurawski

You'll need to modify `NewRESTMetricsClient` to take a `RESTMapper`, then you can use the `RESTMapper` to get a `RESTMapping`, and you can use the `RESTMapping` to check if the `Scope` is namespaced or root.  If it's namespaced, you can do what we're doing currently, if it's root, you'll need to use the method for root-scoped metrics on the metrics client instead.

There should already be a restmapper lying around when the metrics client is actually initialized, since the horizontal pod autoscaler controller itself also uses one, so you should be able to pass that in when initializing the client.

You'll also need to make sure to change the default policy -- right now, it's `*`, but you'll need to make it only support namespaced resources.

**Comment by tak2siva** [comment]
@DirectXMan12 GetObject metric already does some check for Namespaced or Root.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/rest_metrics_client.go#L130-L137

Should it also have an another scope check using `RESTMapping` ? 
Can you help me understand the issue here  ?

**Comment by bartekzurawski** [comment]
@b-m-f I'm currently working on that. Tbh I'm almost done. Fixing unit test right now.

**Comment by palash25** [comment]
Hi :wave: the referenced PR seems to have been abandoned. Would it be okay if I take a crack at this? cc @DirectXMan12

**Comment by DirectXMan12** [comment]
go ahead

cc @mwielgus

**Comment by hprateek43** [comment]
@DirectXMan12 I would like to work on this issue. Is it still open?

**Comment by DirectXMan12** [comment]
/unassign @DirectXMan12 
/assign @mwielgus 

I'm no longer working on autoscaling stuff.  please check with the current autoscaling leads.

**Comment by hprateek43** [comment]
@mwielgus Is the issue still open or there is some PR corresponding to it? Should I take this up?

**Comment by akki** [comment]
@hprateek43 I think this PR is currently active: https://github.com/kubernetes/kubernetes/pull/68800

**Comment by Rajat-0** [comment]
@hprateek43 @akki  corresponding PR is inactive from a long time.
