### ISSUE TITLE
Restore `kubectl --wait flag` default behavior to false. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#67785]
**Is this a BUG REPORT**:
kind bug

**What happened**:
kubectl delete defaults to blocking behavior. 

**What you expected to happen**:
the default should be false, to maintain consistent behavior

**How to reproduce it (as minimally and precisely as possible)**:
Run a scale test, run delete, go bake 175,000 cakes... 

**Anything else we need to know?**:
Original PR stated to default to false. 

/assign @kubernetes/sig-cli-bugs @deads2k 
/cc @skriss

**Comment by dims** [comment]
cc @liggitt based on comments from https://github.com/kubernetes/kubernetes/issues/66110#issuecomment-413875974 and other issue(s)/pr(s)

**Comment by liggitt** [comment]
kubectl delete not returning until the object being deleted was actually gone was a prerequisite to maintaining scripting compatibility (such that a script could recreate immediately after delete returned) while moving to rely on server side GC.

**Comment by timothysc** [comment]
There is definitely a delta in behavior, we're seeing a number of reports from 1.11 versions, including 1.11.2

**Comment by liggitt** [comment]
prior to 1.11, `kubectl delete` waited for resource deletion by default for all workload and batch resources. 1.11 made that behavior consistent for other resources as well

**Comment by timothysc** [comment]
The UX is undesired from an operators perspective, and as mentioned before is a departure from original behavior.  

At the end of the day UX for operators should trump decisions on the CLI. 
/assign @pwittrock

**Comment by timothysc** [comment]
I would argue from an operators perspective all operations should be consistent and non-blocking by default.  This is congruent with other cluster managers.
