### ISSUE TITLE
APIServer target ram percent

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/kubernetes#67789]
**FEATURE REQUEST**:

/kind feature

**What happened**:

Using Kubernetes apiserver 1.10.7, the apiserver progressively uses the memory of the machine and get oom killed.

I noticed and tried the `--target-ram-mb` flag to restrict the usage of the memory.

I would like to be able to set a percentage of memory instead of a static amount of bytes.

**Comment by wenjiaswe** [comment]
cc @jpbetz

**Comment by lovejoy** [comment]
why not use a script to calc the flag's value when you want to set a percentage of memory  ?
