### ISSUE TITLE
Ipsets have family inet in an ipv6-only cluster for proxy-mode=ipvs

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#67799]
/kind bug
/area ipv6
/area ipvs
/sig network

**What happened**:

In an ipv6-only cluster the `kube-proxy` in `ipvs` mode creates a number of ipset's with `family inet`.

This causes problems and fault logs when they are used with ipv6 addresses.

**What you expected to happen**:

The ipset's should be created with `family inet6`.

**How to reproduce it (as minimally and precisely as possible)**:

* Start a ipv6-only cluster
* Execute; `ipset list` on any node and check the output

**Anything else we need to know?**:

The problem seems to be [here](https://github.com/kubernetes/kubernetes/blob/5b2a7c7347cf9ca86ef5dfaaea3e3aa4df3ae270/pkg/proxy/ipvs/proxier.go#L379-L384)

This code seems pretty weird to me. I mean why a `isIpv6` flag in the `ipsetInfo` structure at all? I ignored the `isIpv6` flag in the structure and just passed the `isIpv6` in the `NewProxy()` directly to `NewIPSet()` and it seem to work.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.0.381+b70f2bbc9fbf8d-dirty", GitCommit:"b70f2bbc9fbf8d5e1483d9f65da2c55abb1d1fa7", GitTreeState:"dirty", BuildDate:"2018-08-23T17:50:38Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.0.381+b70f2bbc9fbf8d-dirty", GitCommit:"b70f2bbc9fbf8d5e1483d9f65da2c55abb1d1fa7", GitTreeState:"dirty", BuildDate:"2018-08-23T17:50:38Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  Kvm on Ubuntu 16.04
- OS (e.g. from /etc/os-release):
  Own BusyBox system
- Kernel (e.g. `uname -a`):
`Linux vm-001 4.17.13 #1 SMP Thu Aug 9 09:27:42 CEST 2018 x86_64 GNU/Linux`
- Install tools:
  None
- Others:

**Comment by islinwb** [comment]
@uablrek 
>  I ignored the isIpv6 flag in the structure and just passed the isIpv6 in the NewProxy() directly to NewIPSet() and it seem to work.

Did you make changes like this
```
for _, is := range ipsetInfo {
		proxier.ipsetList[is.name] = NewIPSet(ipset, is.name, is.setType, isIPv6, is.comment)
	}
```

**Comment by uablrek** [comment]
Exactly.

I have no idea why any particular ipset would be ipv4 in an ipv6 cluster. But the flag is false for NodePort set's and there is another bug that NodePort addresses are ipv4 (and faulty). So there might have been some special handling of nodeports at some time. IMHO there shoudn't be.

FYI, I can't send a PR myself just yet but expect to be able to do that in September.

**Comment by pmichali** [comment]
There is clearly a bug in this code, as it forces IPV4:

https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L379-L384

Should have been an else clause, or just:

```
proxier.ipsetList[is.name] = NewIPSet(ipset, is.name, is.setType, is.isIPv6, is.comment)
```
Even with this, there area entries that are using IPv4. Mostly NodePort related entries. Also see iptables error still:

```
E0824 14:44:00.824361       1 proxier.go:1137] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.4.21: Couldn't load target `KUBE-MARK-DR
OP':No such file or directory
```

**Comment by m1093782566** [comment]
Looking forward to PRs @pmichali

**Comment by islinwb** [comment]
@uablrek @pmichali The following codes actually act the same because ` kubeNodePortSet*` are of type `bitmap:port`, which have only one argument `range` (no `family`: `inet` or `inet6`). 
```
for _, is := range ipsetInfo {
		if is.isIPv6 {
			proxier.ipsetList[is.name] = NewIPSet(ipset, is.name, is.setType, isIPv6, is.comment)
		}
		proxier.ipsetList[is.name] = NewIPSet(ipset, is.name, is.setType, false, is.comment)
	}
```
```
for _, is := range ipsetInfo {
		proxier.ipsetList[is.name] = NewIPSet(ipset, is.name, is.setType, isIPv6, is.comment)
	}
```
> I can confirm that, in Ipv6 only cluster, ipset list is reporting family inet for many of the entries (KUBE-LOOP-BACK, KUBE-CLUSTER-IP, KUBE-LOAD-BALANCER-FW...).

I think they are old ipsets. It may be caused by failing to create `inet6` entries.

**Comment by uablrek** [comment]
And I hope to send a PR for this in a few days.

**Comment by uablrek** [comment]
@islinwb They do work, I have tested. There are no old ipset's since the cluster is started fresh with an ipv6-only configuration. Do you upgrade your cluster from ipv4-only to ipv6-only without rebooting the nodes? That is a very complex upgrade and IMHO it should not be supported. When dual-stack comes I think it will be easier, like;

1. Upgrade to k8s with dual-stack support while still using ipv4-only
2. Configure/enable ipv6

**Comment by uablrek** [comment]
@islinwb I think I understand what you mean by "existing" sets now. Some sets are created twice since there are no `else` clause in the if-statement. The ipset command is called with `-exist` which I think causes the second "create" to actually become a "modify". And in that call the ipIpv6 flag is hard-coded to `false`.
I see no purpose for the isIpv6 flag in the structure and will remove it in my PR.
