### ISSUE TITLE
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).

### ISSUE THREAD

**Issue by 94010846** [kubernetes/kubernetes#67811]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
FAILED - RETRYING: 轮询等待flannel 运行，视下载镜像速度而定 (12 retries left).
**What you expected to happen**:
null
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
centor7.2
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
k8s集群的测试、开发环境--allinone部署
ansible-playbook 06.network.yml

**Comment by neolit123** [comment]
i'm sorry but the issues in the tracker should be in English.
please re-open once you modify the issue contents.
/close
