### ISSUE TITLE
Tainting nodes by conditions seems to visibly slow down cluster startup

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#67823]
After https://github.com/kubernetes/kubernetes/pull/62111 has been merged, our large tests started behaving a bit strange. In particular, when 5k node cluster was reported as up (with all nodes being ready), the test itself was only discovering 4k or even less nodes as schedulable.
Example is here:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/192/

There were a couple issues that were fixed in the meantime by @mborsz mostly he fixed validation: https://github.com/kubernetes/kubernetes/pull/67766

That said, that issue clearly shows that tainting nodes by conditions visibly slows down the startup, because now, once the condition are reported as "healthy" the node has to be processed by nodelifecycle controller to remove the corresponding taints.

I didn't yet take a look if the problem here is its throughput or is it related to the fact that there are so many nodes to process at once, but given my experience in the past, I suspect that it may be serialized processing with reporting that in a single thread...

@k82cn @bsalamat @kubernetes/sig-scalability-bugs 
@shyamjvs @mborsz

**Comment by yastij** [comment]
cc @kubernetes/sig-scheduling-misc

**Comment by k82cn** [comment]
>  I suspect that it may be serialized processing with reporting that in a single thread...

Yes; currently, we taint nodes in informer event handler :) I'm going to open PR to taints in multiple go routine to speed-up.

**Comment by wojtek-t** [comment]
/milestone 1.12
given that it is regression

**Comment by shyamjvs** [comment]
We need to fix this soon to get cluster startup time under control. 5k-node test clusters are timing out while trying to come up due to this. For now, I bumped the timeout in https://github.com/kubernetes/test-infra/pull/9196 - but this is really important.

**Comment by shyamjvs** [comment]
To add some more context, there were still 1620 (out of 5000) unschedulable nodes after the 30m timeout.

**Comment by guineveresaenger** [comment]
Do we have a priority on this? @shyamjvs @wojtek-t ? Thanks! 👍

**Comment by wojtek-t** [comment]
Added priority. The PR fixing that (https://github.com/kubernetes/kubernetes/pull/67864) is hopefully close to be done.

**Comment by shyamjvs** [comment]
Sorry missed Wojtek's comment above.. Not sure how to uncomment the label.

**Comment by wojtek-t** [comment]
I remove it manually :)

**Comment by shyamjvs** [comment]
It doesn't let me do that. You could do it probably because you created the issue?

**Comment by wojtek-t** [comment]
@k82cn - I took a look into the recent runs, and it seems that unfortunately the improvement didn't help much.

As an example in this run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/208
[it failed completely later, but that's unrelated to this issue]

it took additional 45 minutes to get rid of taints on all the nodes - that seems pretty bad.
I didn't yet have much time to look into that, but if someone could help with that would be great.

**Comment by wojtek-t** [comment]
To clarify - me estimation would be that we need to send a single api call for each node to remove the taints, that mean 5000 api calls (with 100qps limits, that should give order of minute).
If it would be 5 minutes, it's probably also fine.

But 45 minutes doesn't seem to be acceptable.

**Comment by wojtek-t** [comment]
One update - these are two api calls (GET + PATCH), so ~2minutes.

I also took a look into logs, and majority of requests finish within 3ms (there are some that takes 10ms+, but I didn't see any taking more than 50ms. 

I initially thought that because those api calls are send from synchrnously from workers, that may affect it. But it seems that they are fast...

**Comment by k82cn** [comment]
Got that; i'd like to continue the work here :)

**Comment by wojtek-t** [comment]
Actually, I started wondering that maybe the handler is not fast enough?

In 5000-node cluster, with each node reporting status every 10s, we have 500 node updates per second (on average).

With 8 workers, that gives ~60 updates to process per second.
That gives ~20ms per update in the ideal situation when the worker has cpu all the time.

I didn't have chance to confirm if we are or not cpu-starved around that time, but maybe we are actually too slow with processing those...

**Comment by wojtek-t** [comment]
The other thing that I'm wondering about (though we would need to check if that has changed with tainting by condition) is that between 08:20 (~when cluster was reported as up) to 09:00 (when tests started running), there are ~75k PATCH node status requests coming from nodelifecycle controllers.
That seems pretty high to me...

**Comment by k82cn** [comment]
> Actually, I started wondering that maybe the handler is not fast enough?

Maybe, I check conditions changes in #68408 : if no changes, did not check taints.

**Comment by k82cn** [comment]
> there are ~75k PATCH node status requests coming from nodelifecycle controllers

Will that trigger many update requests pending in the channel to taint ? workqueue did not replace the previous one.

**Comment by guineveresaenger** [comment]
This is critical as it relates to release blocking tests.

**Comment by dims** [comment]
cc @bsalamat

**Comment by guineveresaenger** [comment]
@wojtek-t - is this on track for 1.12 still?

**Comment by wojtek-t** [comment]
The current run (after the last PR being merged), seems to be fine:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/211

I would consider it as fixed.

**Comment by guineveresaenger** [comment]
@wojtek-t I may miss something but until I can actually see those tests passing, this issue is not done.

/reopen
/kind

**Comment by k82cn** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/211 is green now. @guineveresaenger , is it ok to close?

**Comment by wojtek-t** [comment]
copying from Slack:

@AishSundar @gsaenger - the last run of scale-performance is green, but it's NOT yet done
we have switched off part of the test to facilitate debugging
yesterday in the afternoon I realized that I believe that the changed fixing https://github.com/kubernetes/kubernetes/issues/67823 may have actually caused more issues then I thought and may have been reason off all failures [the memory usage of controller-manager could have growing indefinitely causing different stability issues that we observed]
we don't have fully confirmation of it, but that's the current hypothesis
@k82cn @liggitt ^^

**Comment by guineveresaenger** [comment]
@wojtek-t thanks for the update, I saw the most recent run not pass, will follow proceedings here and on Slack. 👍

**Comment by tpepper** [comment]
Status check @k82cn @wojtek-t

**Comment by guineveresaenger** [comment]
Last two scale runs were still red - any significance here?

**Comment by shyamjvs** [comment]
This is now fixed (i.e taint updates are not slow anymore) and verified. We can close this..
/close

**Comment by shyamjvs** [comment]
> Last two scale runs were still red - any significance here?

Those are unrelated. The last one was a minor flake (the performance test itself was fine) and the second last one was due to https://github.com/kubernetes/kubernetes/issues/68613 (which has now been fixed after reverting core-dns default).
