### ISSUE TITLE
How to default the FSType for block device volumes

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#67834]
We now default FSType to `ext4` for block device volumes if users do not set it.  But @thockin pointed out that In general Linux can auto-detect filesystems, we can make the default be best-effort auto-detect, and try to avoid encouraging people to make assumptions. Also we need to take Windows support into account.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Default to `ext4`

**What you expected to happen**:

Leaving the API for the user to specify it , but make the node determine which FS to use if not specified, or configure the default values somewhere(e.g. kubelet config params,  from admin...)

**Anything else we need to know?**:
Discussion in this PR:  https://github.com/kubernetes/kubernetes/pull/63011#discussion_r212397395

/sig storage
/sig windows

cc @thockin @msau42 @jsafrane @saad-ali

**Comment by thockin** [comment]
From the other thread:

The goal is not to spell "ext4" anywhere in Kubernetes.  Just as we want to
never spell "google" or "amazon" and move all of that out of core, we
should endeavour to reduce hard deps on linuxisms, especially ones that
change vogue over time or across sites.

E.g. `func (mounter *SafeFormatAndMount) formatAndMount` should not
hardcode ext4 and flags for it, but should either exec something from the
node itself, or should receive params (e.g. kubelet config params) that
specify which FS and flags to use by default, or maybe even more flexibly
which FSes are allowed, which FS is default, and a map of per-fs flags to
use for mkfs and mount.

Then we can delete hardcoded "ext4" stuff and move it to configs, where it
can be changed more readily.

**Comment by msau42** [comment]
One alternative to having the node report a default is to have a configurable option in a CSI Driver that an admin or provider can set.
