### ISSUE TITLE
Add ability to create binary versions of k8s/code-generator helpers

### ISSUE THREAD

**Issue by sgnn7** [kubernetes/kubernetes#67837]
Currently, given that there is no good option to run code generators in a [go modules](https://github.com/kubernetes/kubernetes/issues/67566) environment and given the need for some people to run the code generators in a minimal environment, some type of build script should be ideally available for this task to create portable binary runners.

Relevant go mod Issue: https://github.com/kubernetes/kubernetes/issues/67566
Related issue: (closed for age): https://github.com/kubernetes/code-generator/issues/15

I intend to have a PR open for this today

/kind feature
/sig api-machinery

**Comment by nikhita** [comment]
/remove-lifecycle rotten
/area code-generation

PR open: https://github.com/kubernetes/kubernetes/pull/67838
