### ISSUE TITLE
CRD: Consider changing schema language

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#67840]
Right now, CRDs accept a schema in the form OpenAPI v3 / json-schema.

While it is true that apiserver publishes OpenAPI (though v2) schema docs, I increasingly think that OpenAPI is not a good schema definition mechanism for CRDs or Kubernetes resources in general. Why? It allows mixing "type validation" and "value validation" in inseparable ways, which is impossible to faithfully adhere to in our deserialization stack. It allows expressing many objects which would not conform to the "Kubernetes Object Model" (for lack of a better phrase). Forbidding spec documents which won't work in our system is time consuming for us and will be confusing to users.

People today define their resources in our "Go IDL", or (I hear) some extension authors have used proto. No one writes OpenAPI by hand directly, as far as I can tell. So, I don't think users will care (apart from the churn).

We have a great opportunity to replace it with something new at the moment, as we're deprecating the singular `validation` field anyway to replace it with the version list.

Of course it's not obvious what to replace it with. Off the top of my head we have some choices:
1. A string that contains the go types? (Will be fun to validate / use, but definitely not impossible)
2. A targeted schema language that expresses our exact semantics? I have [started one](https://github.com/kubernetes/kubernetes/pull/67458/files) for apply, it can be expedited if it will be useful here.
3. proto w/ extension tags? non-k8s googlers often expect this.

**Comment by lavalamp** [comment]
Also @roycaihw

**Comment by sttts** [comment]
I had option 1 in my mind for quite some time, but didn't dare to propose that :-)

**Comment by sttts** [comment]
> We have a great opportunity to replace it with something new at the moment, as we're deprecating the singular validation field anyway to replace it with the version list.

What does this mean? We block versioning?

**Comment by lavalamp** [comment]
@sttts I suppose I'm a little late in the cycle to recommend blocking something. Maybe we can try and fix this for v1?

**Comment by mbohlool** [comment]
What about a more restricted OpenAPI spec? If we talk specifics, we can see if we can use a very restricted version of it and add special extensions to it. It would be very close to option 3 though but maybe a little easier to reason with community on that as the spec is still a standard.

**Comment by sttts** [comment]
> It allows mixing "type validation" and "value validation" in inseparable ways, which is impossible to faithfully adhere to in our deserialization stack

IMO this is wrong. The skeleton schema faithfully represents the "type validation" part of the full openapi validation schema.

Faithfully in the sense of: `s` validates an object `=>` `skel(s)` validates an object.

Moreover, `skel(s)` captures the JSON structure of the object, exactly what we would capture with a Golang type. 

Hence, we in fact have separated type and value validation.

> What about a more restricted OpenAPI spec? If we talk specifics, we can see if we can use a very restricted version of it and add special extensions to it. It would be very close to option 3 though but maybe a little easier to reason with community on that as the spec is still a standard.

+1000

Take another look at the skeleton schema in the KEP https://github.com/kubernetes/community/pull/2443/files#diff-013270d6b6dcb9a6d109498983601f0dR179. Such a schema consists of the following:

* `type`, 
* `items`,
* ~~additionalItems~~ (for forbid this, so forget about this construct)
* `properties`,
* ~~patternProperties~~ (we forbid this, so forget about this construct)
* `additionalProperties` (only allowed to express `map[string]type` like types; cannot be mixed with properties)

1. What is missing? What could be specified with Golang types and not with this language?
2. What is too much? What can be specified in a skeleton schema, but not in Golang types?

Before we throw away everything around CRD validation and forcing another half-baked language onto our users, we should be clear about these points IMO. I think we are not.

**Comment by mbohlool** [comment]
Adding one more detail to the idea, we can set the bar for restriction on OpenAPI schema using our own kube-openapi. Anything that kube-openapi cannot generate should not be allowed in the Schema of CRD. this will help us both develop kube-openapi to take care of all cases (structure and value validation in a separate way) and also make sure what we accept from users which may come from another source would be sound and not too much for api server's consumption.

**Comment by sttts** [comment]
> Anything that kube-openapi cannot generate should not be allowed in the Schema of CRD.

The more I think about it, I think we are mixing problems here and should be more precise what we want to change:

1. we have OpenAPI validation. **Restricting expressibity in validation is the wrong goal.** Proof: if we restrict validation expressivity, we force people into admission webhooks which are turing complete. We have even less control about what they do.
2. we have OpenAPI schema check in decoding. Schemata should follow and support our API conventions. I claim with my restriction to skeleton schemata, we have this. And all this covered by kube-openapi as well.

**The unanswered question is:** is the way the skeleton is derived from the validation (described in the KEP) sound? If not, why not.

Even if we have properties like regular expressions for fields in kube-openapi, we will not want to check those during decoding. In other words, these should not be part of the skeleton.

**Comment by sharebear** [comment]
> People today define their resources in our "Go IDL", or (I hear) some extension authors have used proto. No one writes OpenAPI by hand directly, as far as I can tell. So, I don't think users will care (apart from the churn).

What about people using CRDs in clients that aren't go (for example there are multiple "operator" type applications based upon the fabric8 java libraries), do they write OpenAPI by hand or do they also reverse engineer the schema from their language of choice?

**Comment by liggitt** [comment]
after discussion, we've decided to pursue a constrained openapi v3 schema for GA, rather than invent a new schema language

/close
