### ISSUE TITLE
Add generated vgo (go mo) definiton files to code-generator

### ISSUE THREAD

**Issue by sgnn7** [kubernetes/kubernetes#67843]
Currently, given that there is no good option to run code generators in a [go modules](https://github.com/kubernetes/kubernetes/issues/67566) environment and given the need for some people to run this code in a newer vgo (non-GOPATH-based env of Golang v1.11beta2+), adding these files will allow builds/execution of Go code in here. This still does not fix various other issues with the runner scripts but it gets the code closer to the point where it could be runnable and maintains the current functionality.

Files were simply generated on Golang v1.11beta2 with:
```
go mod -init
go mod -sync
```

Child of #67566 
Related issue:
- #63607

I intend to have a PR open for this today

/kind feature
/sig api-machinery

**Comment by cblecker** [comment]
@sgnn7 Sorry, we're not ready for this yet. We need to figure out our go module strategy for the whole project, and how we're going to keep these files updated and synchronized with each other.

Please follow #63607 for updates.

/close
