### ISSUE TITLE
Prometheus metrics is expensive in critical scheduling path

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#67857]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

We recently added several useful `metrics.EquivalenceCacheHits.Inc()` i[n critical path of scheduling](https://github.com/kubernetes/kubernetes/commit/b874d2789b11e21b3f91840a9ea0f6b0b90f54d5#diff-313f61688c4a7af6d12eb3e43a0ba89dR289), unfortunately, this operation seems to be expensive in the scheduling benchmark test result:

https://github.com/resouer/temp/blob/master/torch_per_node_getnodecache.5000.svg

**What you expected to happen**:

Honestly speaking, I don't think the metrics clinet is a secrious problem, we can just consider to add a control flag and disable it by default.

**How to reproduce it (as minimally and precisely as possible)**:

/sig scheduling

**Anything else we need to know?**:

cc @misterikkit 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by smarterclayton** [comment]
prometheus increments are usually cheap, so you are probably calling into this millions of times if you’re seeing a cost.  However, if this is a shared cache you should already be performing synchronization so it’s hard to understand how a second synchronization is going to make it that much worse.

A metric per operation might be more effective (cache ratio per operation)

**Comment by resouer** [comment]
I see, then we will need to re-define this metrics and move it to a high level caller - as you mentioned, per operation sounds reasonable.

**Comment by cofyc** [comment]
`metric.Inc()` needs synchronization mechanism. How about incrementing internal counts and using prometheus collector to collect stats on scraping? With this, overhead will be one incremental operation on integer for each call and a lock to return stats per scrape (interval depends on prometheus config, typically 1 minute).

**Comment by misterikkit** [comment]
> using prometheus collector to collect stats on scraping

That sounds like a good approach. I was looking for how to do this in prometheus, and I didn't know it's called a 'collector'.
