### ISSUE TITLE
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].

### ISSUE THREAD

**Issue by leeivan** [kubernetes/kubernetes#67858]
leeivan@kube-dev:~/gowork/src/k8s.io/kubernetes$ KUBE_GCE_NETWORK=default KUBEMARK_NUM_NODES=25 ./test/kubemark/start-kubemark.sh
STARTING SETUP FOR MASTER
Created the environment file for master.
Created [https://www.googleapis.com/compute/v1/projects/kube-e2e-mark/zones/us-central1-b/disks/kubernetes-kubemark-master-pd].
NAME                           ZONE           SIZE_GB  TYPE    STATUS
kubernetes-kubemark-master-pd  us-central1-b  20       pd-ssd  READY

New disks are unformatted. You must format and mount a disk before it
can be used. You can find instructions on how to do this at:

https://cloud.google.com/compute/docs/disks/add-persistent-disk#formatting

Succeeded to gcloud compute disks.
Created [https://www.googleapis.com/compute/v1/projects/kube-e2e-mark/regions/us-central1/addresses/kubernetes-kubemark-master-ip].
Succeeded to gcloud compute addresses.
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
Created [https://www.googleapis.com/compute/v1/projects/kube-e2e-mark/zones/us-central1-b/instances/kubernetes-kubemark-master].
WARNING: Some requests generated warnings:
 - The resource 'projects/cos-cloud/global/images/cos-stable-65-10323-64-0' is deprecated. A suggested replacement is 'projects/cos-cloud/global/images/cos-stable-65-10323-69-0'.

NAME                        ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
kubernetes-kubemark-master  us-central1-b  n1-standard-4               10.128.0.5   35.202.251.25  RUNNING
Succeeded to gcloud compute instances.
Updated [https://www.googleapis.com/compute/v1/projects/kube-e2e-mark/zones/us-central1-b/instances/kubernetes-kubemark-master].
Succeeded to gcloud compute instances.
Creating firewall...
...........Created [https://www.googleapis.com/compute/v1/projects/kube-e2e-mark/global/firewalls/kubernetes-kubemark-master-https].
done.
NAME                              NETWORK  DIRECTION  PRIORITY  ALLOW    DENY
kubernetes-kubemark-master-https  default  INGRESS    1000      tcp:443
Succeeded to gcloud compute firewall-rules.
Generating certs for alternate-names: IP:35.202.251.25,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes-kubemark-master
Generated PKI authentication data for kubemark.
Warning: Permanently added 'compute.5090239621903501962' (RSA) to the list of known hosts.
Succeeded to gcloud compute ssh.
Checked master reachability for remote command execution.
Succeeded to gcloud compute ssh.
Wrote PKI certs, keys, tokens and admin password to master.
Kubeconfig file for kubemark master written to /home/leeivan/gowork/src/k8s.io/kubernetes/test/kubemark/resources/kubeconfig.kubemark.
packet_write_wait: Connection to 35.202.251.25 port 22: Broken pipe
lost connection
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Attempt 1 failed to gcloud compute scp. Retrying.
packet_write_wait: Connection to 35.202.251.25 port 22: Broken pipe
lost connection
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Attempt 2 failed to gcloud compute scp. Retrying.
ERROR: (gcloud.compute.scp)
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
Attempt 3 failed to gcloud compute scp. Retrying.
Failed to gcloud compute scp.

/sig testing
/sig scalability

**Comment by kylefoley76** [comment]
So what is the solution to this problem.  

I am getting the following error message

`Admins-MacBook-Pro-4:downloads kylefoley$ gcloud compute scp lst_calc.txt instance-1:/home/kylefoley76/hey.txt
No zone specified. Using zone [us-central1-a] for instance: [instance-1].
Updating project ssh metadata...⠧Updated [https://www.googleapis.com/compute/v1/projects/zzz-zzz-250022].
Updating project ssh metadata...done.                                             
Waiting for SSH key to propagate.
Warning: Permanently added 'compute.1494876250178113937' (ECDSA) to the list of known hosts.
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
scp: /home/kylefoley76/hey.txt: Permission denied
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Admins-MacBook-Pro-4:downloads kylefoley$ gcloud compute scp lst_calc.txt root@instance-1:/home/kylefoley76/hey.txt
No zone specified. Using zone [us-central1-a] for instance: [instance-1].
Updating project ssh metadata...⠛Updated [https://www.googleapis.com/compute/v1/projects/atomic-drake-250022].
Updating project ssh metadata...done.                                             
Waiting for SSH key to propagate.
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
root@35.193.247.37: Permission denied (publickey).
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
root@35.193.247.37: Permission denied (publickey).
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
root@35.193.247.37: Permission denied (publickey).
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine': 
root@35.193.247.37: Permission denied (publickey).
Enter passphrase for key '/Users/kylefoley/.ssh/google_compute_engine':`
