### ISSUE TITLE
pvc  scalio  pending

### ISSUE THREAD

**Issue by yangtea** [kubernetes/kubernetes#67856]
**What happened**:
When i use scalio storageclass create persistent volume claim, it always in pending status, kubectl describe get follow event:
Events:
  Type     Reason              Age               From                         Message
Warning  ProvisioningFailed  2m (x68 over 2h)  persistentvolume-controller  Failed to provision volume with StorageClass "sio-small": Problem getting response from endpoint

The yaml of relative files are followed: 
##cat  secret.yaml
`apiVersion: v1`
apiVersion: v1
kind: Secret
metadata:
  name: sio-secret
type: kubernetes.io/scaleio
data:
  username: YWRtaW4=
  password: QVNjYWxlaW8xMjM=

## cat sc.yaml 

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sio-small
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://10.8.192.55:443/api
  system: scaleio
  protectionDomain: domain1
  storagePool: pool1
  secretRef: sio-secret
  fsType: xfs

## cat sc-pvc.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sio-small
spec:
  storageClassName: sio-small
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version : v1.8.0
- Cloud provider or hardware configuration:   Hardware
- OS: CentOS Linux release 7.5.1804 (Core)
- Kernel :  3.10.0-693.21.1.el7.x86_64
- Install tools:
- Others:
![image](https://user-images.githubusercontent.com/24996565/44614914-85357500-a860-11e8-921c-5e17e6006792.png)
![image](https://user-images.githubusercontent.com/24996565/44614958-5f5ca000-a861-11e8-873b-7cc7a1d13b7b.png)

**Comment by ddebroy** [comment]
@yangtea are you able to reach ScaleIO's gateway address `10.8.192.55:443` from the Kubernetes nodes (for example using ScaleIO's `scli` to the MDM IPs)?  `Problem getting response from endpoint` seems to indicate an underlying connectivity/authentication problem between the kubernetes binaries and ScaleIO.

**Comment by yangtea** [comment]
@ddebroy Hi! Yes, I'm able to reach Scalio's gateway 10.8.192.55:443 by scli. The result is following like this:
`#scli --query_all_volumes --mdm_ip 10.8.192.55
Query-all-volumes returned 3 volumes 
Protection Domain 9891eb0b00000000 Name: domain1
Storage Pool 7eaadc6500000000 Name: pool1
 Volume ID: 3567f18f00000000 Name: vol-0 Size: 56.0 GB (57344 MB) Unmapped Thick-provisioned 
 Volume ID: 3568189f00000001 Name: vol-1 Size: 8.0 GB (8192 MB) Unmapped Thick-provisioned 

But, why the pod doesn't map the volume, the event shows "Problem getting response from endpoint seems to ..." 
How can I take next step?
`
