### ISSUE TITLE
`kubectl --prune --dry-run` produces incorrect output

### ISSUE THREAD

**Issue by AndyBarron** [kubernetes/kubernetes#67863]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
`kubectl --context context-name apply -f config-dir/ --prune -l label=value --dry-run=true`
The dry run output listed all the resources that would be configured: deployments, HPAs, services, and an ingress:
`type/name configured (dry run)`
This was expected. However, it then listed all resources again (except for the HPAs) as being pruned:
`type/name pruned (dry run)`
The config was then applied with:
`kubectl --context context-name apply -f config-dir/ --prune -l label=value`
As expected, no resources were actually pruned.

**What you expected to happen**:
`kubectl --prune --dry-run` should actually display which resources are going to be pruned.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a `Deployment` YAML file to `config-dir` with `metadata.labels.label=value`
2. Deploy it: `kubectl apply -f config-dir/`
2. Dry run + prune: `kubectl apply -f config-dir/ --prune -l label=value --dry-run=true`
3. It should be listed as both configured and pruned
4. Deploy it again with pruning: `kubectl apply -f config-dir/ --prune -l label=value`
5. Observe that the deployment is configured but not pruned, even though the dry run said it would be.

**Anything else we need to know?**:
Was trying to write a devops script that gave a warning before any resources would be pruned.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.1", GitCommit:"ee18aa41359293b5c9c7e13a35697690491736c9", GitTreeState:"clean", BuildDate:"2018-08-08T18:09:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 
(Lubuntu 18.04)
```
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux [redacted] 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: `apt`
- Others: `gcloud`

**Comment by charrywanganthony** [comment]
I can reproduce it, and i will try to fix it.

**Comment by charrywanganthony** [comment]
```shell
[chaowang@master kubernetes]$ kubectl apply -f nginx.yaml --prune -l label=nginx-1 --dry-run=true
deployment.apps/my-nginx-deployment configured (dry run)
deployment.extensions/my-nginx-deployment pruned (dry run)
deployment.apps/my-nginx-deployment pruned (dry run)
[chaowang@master kubernetes]$ kubectl apply -f nginx.yaml --prune -l label=nginx-1
deployment.apps/my-nginx-deployment configured
```
