### ISSUE TITLE
Failing tests: all but two GKE jobs are failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#67862]
Every GKE job except two are failing, see https://k8s-testgrid.appspot.com/google-gke

This started sometime near 3:30pm PT 2018-08-22
- [Last good ci-kubernetes-e2e-gci-gke run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/30790) at 15:19
- [First bad ci-kubernetes-e2e-gci-gke-run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/30791) at 15:52

The failures look like the following example, [taken from the latest ci-kubernetes-e2e-gci-gke run as of time of filing this](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/30908)
```
W0825 17:38:49.474] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0825 17:38:49.475]  detail: u'Failed to create cluster'
W0825 17:38:49.475]  endTime: u'2018-08-25T17:38:46.38347351Z'
W0825 17:38:49.475]  name: u'operation-1535218718424-8da8d186'
W0825 17:38:49.475]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0825 17:38:49.475]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/647873874675/zones/us-central1-f/operations/operation-1535218718424-8da8d186'
W0825 17:38:49.475]  startTime: u'2018-08-25T17:38:38.424408917Z'
W0825 17:38:49.475]  status: StatusValueValuesEnum(DONE, 3)
W0825 17:38:49.475]  statusMessage: u'Failed to create cluster'
W0825 17:38:49.475]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/647873874675/zones/us-central1-f/clusters/e2e-30908-fbb42'
W0825 17:38:49.476]  zone: u'us-central1-f'>] finished with error: Failed to create cluster
```

These two jobs are passing:
- https://k8s-testgrid.appspot.com/google-gke#gke-device-plugin-gpu
- https://k8s-testgrid.appspot.com/google-gke#gke-device-plugin-gpu-p100

GKE jobs are on all release-blocking dashboards, so this is blocking all releases

/kind failing-testing
/priority critical-urgent
/sig gcp
/assign @amwat
per https://go.k8s.io/oncall, to assign to the relevant GKE staff fixing this issue
/assig @mohammedzee1000 
as CI signal, same thing

**Comment by foxish** [comment]
Might be related - COS related tests are failing http://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-cos-1.11-serial

**Comment by amwat** [comment]
https://github.com/kubernetes/test-infra/pull/9161 should mostly fix the issue.

**Comment by spiffxp** [comment]
The following GKE jobs are still failing:
- [google-gke#gci-gke](https://testgrid.k8s.io/google-gke#gci-gke)
- [google-gke#gci-gke-alpha-enabled-default](https://testgrid.k8s.io/google-gke#gci-gke-alpha-enabled-default)
- [google-gke#gci-gke-ingress-1.9](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.9)
- [google-gke#gci-gke-multizone](https://testgrid.k8s.io/google-gke#gci-gke-multizone)
- [google-gke#gci-gke-serial](https://testgrid.k8s.io/google-gke#gci-gke-serial)
- [google-gke#gci-gke-slow](https://testgrid.k8s.io/google-gke#gci-gke-slow)
- [google-gke#gke-canary](https://testgrid.k8s.io/google-gke#gke-canary)
- [google-gke#gke-cos-alpha-cluster-1.10](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-1.10)
- [google-gke#gke-cos-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-1.11)
- [google-gke#gke-cos-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-features-1.10)
- [google-gke#gke-cos-containerd-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster)
- [google-gke#gke-cos-containerd-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.10)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.11)
- [google-gke#gke-regional](https://testgrid.k8s.io/google-gke#gke-regional)
- [google-gke#gke-regional-serial](https://testgrid.k8s.io/google-gke#gke-regional-serial)
- [google-gke#gke-regional-slow](https://testgrid.k8s.io/google-gke#gke-regional-slow)

The following release-blocking GKE jobs are still failing:
- [sig-release-master-blocking#gci-gke](https://testgrid.k8s.io/sig-release-master-blocking#gci-gke)
- [sig-release-master-blocking#gci-gke-serial](https://testgrid.k8s.io/sig-release-master-blocking#gci-gke-serial)
- [sig-release-master-blocking#gci-gke-slow](https://testgrid.k8s.io/sig-release-master-blocking#gci-gke-slow)

**Comment by spiffxp** [comment]
The following tests are failing across google-gke, google-gke-staging, and google-gke-prod
- [google-gke#gci-gke](https://testgrid.k8s.io/google-gke#gci-gke)
- [google-gke#gci-gke-1.10](https://testgrid.k8s.io/google-gke#gci-gke-1.10)
- [google-gke#gci-gke-1.8](https://testgrid.k8s.io/google-gke#gci-gke-1.8)
- [google-gke#gci-gke-1.9](https://testgrid.k8s.io/google-gke#gci-gke-1.9)
- [google-gke#gci-gke-alpha-enabled-default](https://testgrid.k8s.io/google-gke#gci-gke-alpha-enabled-default)
- [google-gke#gci-gke-alpha-features](https://testgrid.k8s.io/google-gke#gci-gke-alpha-features)
- [google-gke#gci-gke-flaky](https://testgrid.k8s.io/google-gke#gci-gke-flaky)
- [google-gke#gci-gke-ingress](https://testgrid.k8s.io/google-gke#gci-gke-ingress)
- [google-gke#gci-gke-ingress-1.10](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.10)
- [google-gke#gci-gke-ingress-1.8](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.8)
- [google-gke#gci-gke-ingress-1.9](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.9)
- [google-gke#gci-gke-multizone](https://testgrid.k8s.io/google-gke#gci-gke-multizone)
- [google-gke#gci-gke-reboot](https://testgrid.k8s.io/google-gke#gci-gke-reboot)
- [google-gke#gci-gke-reboot-1.10](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.10)
- [google-gke#gci-gke-reboot-1.8](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.8)
- [google-gke#gci-gke-reboot-1.9](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.9)
- [google-gke#gci-gke-serial](https://testgrid.k8s.io/google-gke#gci-gke-serial)
- [google-gke#gci-gke-serial-1.10](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.10)
- [google-gke#gci-gke-serial-1.8](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.8)
- [google-gke#gci-gke-serial-1.9](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.9)
- [google-gke#gci-gke-slow](https://testgrid.k8s.io/google-gke#gci-gke-slow)
- [google-gke#gci-gke-slow-1.10](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.10)
- [google-gke#gci-gke-slow-1.8](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.8)
- [google-gke#gci-gke-slow-1.9](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.9)
- [google-gke#gci-gke-updown](https://testgrid.k8s.io/google-gke#gci-gke-updown)
- [google-gke#gke-canary](https://testgrid.k8s.io/google-gke#gke-canary)
- [google-gke#gke-cos-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-1.11)
- [google-gke#gke-cos-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-features-1.10)
- [google-gke#gke-cos-alpha-cluster-features-1.11](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-features-1.11)
- [google-gke#gke-cos-containerd-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster)
- [google-gke#gke-cos-containerd-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.10)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.11)
- [google-gke#gke-device-plugin-gpu](https://testgrid.k8s.io/google-gke#gke-device-plugin-gpu)
- [google-gke#gke-device-plugin-gpu-p100](https://testgrid.k8s.io/google-gke#gke-device-plugin-gpu-p100)
- [google-gke#gke-regional](https://testgrid.k8s.io/google-gke#gke-regional)
- [google-gke#gke-regional-serial](https://testgrid.k8s.io/google-gke#gke-regional-serial)
- [google-gke#gke-regional-slow](https://testgrid.k8s.io/google-gke#gke-regional-slow)
- [google-gke#gci-gke](https://testgrid.k8s.io/google-gke#gci-gke)
- [google-gke#gci-gke-1.10](https://testgrid.k8s.io/google-gke#gci-gke-1.10)
- [google-gke#gci-gke-1.8](https://testgrid.k8s.io/google-gke#gci-gke-1.8)
- [google-gke#gci-gke-1.9](https://testgrid.k8s.io/google-gke#gci-gke-1.9)
- [google-gke#gci-gke-alpha-enabled-default](https://testgrid.k8s.io/google-gke#gci-gke-alpha-enabled-default)
- [google-gke#gci-gke-alpha-features](https://testgrid.k8s.io/google-gke#gci-gke-alpha-features)
- [google-gke#gci-gke-flaky](https://testgrid.k8s.io/google-gke#gci-gke-flaky)
- [google-gke#gci-gke-ingress](https://testgrid.k8s.io/google-gke#gci-gke-ingress)
- [google-gke#gci-gke-ingress-1.10](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.10)
- [google-gke#gci-gke-ingress-1.8](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.8)
- [google-gke#gci-gke-ingress-1.9](https://testgrid.k8s.io/google-gke#gci-gke-ingress-1.9)
- [google-gke#gci-gke-multizone](https://testgrid.k8s.io/google-gke#gci-gke-multizone)
- [google-gke#gci-gke-reboot](https://testgrid.k8s.io/google-gke#gci-gke-reboot)
- [google-gke#gci-gke-reboot-1.10](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.10)
- [google-gke#gci-gke-reboot-1.8](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.8)
- [google-gke#gci-gke-reboot-1.9](https://testgrid.k8s.io/google-gke#gci-gke-reboot-1.9)
- [google-gke#gci-gke-serial](https://testgrid.k8s.io/google-gke#gci-gke-serial)
- [google-gke#gci-gke-serial-1.10](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.10)
- [google-gke#gci-gke-serial-1.8](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.8)
- [google-gke#gci-gke-serial-1.9](https://testgrid.k8s.io/google-gke#gci-gke-serial-1.9)
- [google-gke#gci-gke-slow](https://testgrid.k8s.io/google-gke#gci-gke-slow)
- [google-gke#gci-gke-slow-1.10](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.10)
- [google-gke#gci-gke-slow-1.8](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.8)
- [google-gke#gci-gke-slow-1.9](https://testgrid.k8s.io/google-gke#gci-gke-slow-1.9)
- [google-gke#gci-gke-updown](https://testgrid.k8s.io/google-gke#gci-gke-updown)
- [google-gke#gke-canary](https://testgrid.k8s.io/google-gke#gke-canary)
- [google-gke#gke-cos-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-1.11)
- [google-gke#gke-cos-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-features-1.10)
- [google-gke#gke-cos-alpha-cluster-features-1.11](https://testgrid.k8s.io/google-gke#gke-cos-alpha-cluster-features-1.11)
- [google-gke#gke-cos-containerd-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster)
- [google-gke#gke-cos-containerd-alpha-cluster-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-1.11)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.10](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.10)
- [google-gke#gke-cos-containerd-alpha-cluster-features-1.11](https://testgrid.k8s.io/google-gke#gke-cos-containerd-alpha-cluster-features-1.11)
- [google-gke#gke-device-plugin-gpu](https://testgrid.k8s.io/google-gke#gke-device-plugin-gpu)
- [google-gke#gke-device-plugin-gpu-p100](https://testgrid.k8s.io/google-gke#gke-device-plugin-gpu-p100)
- [google-gke#gke-regional](https://testgrid.k8s.io/google-gke#gke-regional)
- [google-gke#gke-regional-serial](https://testgrid.k8s.io/google-gke#gke-regional-serial)
- [google-gke#gke-regional-slow](https://testgrid.k8s.io/google-gke#gke-regional-slow)
- [google-gke-staging#gke-staging-1-10-1-11-upgrade-cluster-new](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-10-1-11-upgrade-cluster-new)
- [google-gke-staging#gke-staging-1-10-1-11-upgrade-regional-cluster](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-10-1-11-upgrade-regional-cluster)
- [google-gke-staging#gke-staging-1-9-1-10-upgrade-cluster](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-9-1-10-upgrade-cluster)
- [google-gke-staging#gke-staging-1-9-1-10-upgrade-cluster-new](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-9-1-10-upgrade-cluster-new)
- [google-gke-staging#gke-staging-1-9-1-10-upgrade-master](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-9-1-10-upgrade-master)
- [google-gke-staging#gke-staging-1-9-1-10-upgrade-regional-cluster](https://testgrid.k8s.io/google-gke-staging#gke-staging-1-9-1-10-upgrade-regional-cluster)
- [google-gke-staging#gke-staging-1.11-cos-containerd-serial](https://testgrid.k8s.io/google-gke-staging#gke-staging-1.11-cos-containerd-serial)
- [google-gke-staging#gke-staging-default-parallel](https://testgrid.k8s.io/google-gke-staging#gke-staging-default-parallel)

**Comment by spiffxp** [comment]
This is blocking all patch releases, but at the moment we only have an issue open for 1.11.x ref: https://github.com/kubernetes/kubernetes/issues/68220

**Comment by mohammedzee1000** [comment]
Thanks for raising this issue.

**Comment by spiffxp** [comment]
More meaningfully, there are the GKE failures that are blocking v1.12's release:
- [sig-release-master-blocking#gci-gke](https://testgrid.k8s.io/sig-release-master-blocking#gci-gke)
- [sig-release-master-blocking#gci-gke-serial](https://testgrid.k8s.io/sig-release-master-blocking#gci-gke-serial)
- [sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster)
- [sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new)
- [sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-parallel](https://testgrid.k8s.io/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-parallel)
- [sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master)
- [sig-release-1.12-blocking#gke-cos-1.12-default](https://testgrid.k8s.io/sig-release-1.12-blocking#gke-cos-1.12-default)
- [sig-release-1.12-blocking#gke-cos-1.12-serial](https://testgrid.k8s.io/sig-release-1.12-blocking#gke-cos-1.12-serial)

**Comment by dashpole** [comment]
Cluster creation should be working again.  Now we just have to track down the actual bugs, as it looks like the suites are still flaking on tests.

**Comment by spiffxp** [comment]
/close
OK I'm willing to close this out.  Do we have issues open for the individual test flakes and failures?

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/68313
