### ISSUE TITLE
StorageOS can't create a volume in 2-node on-premise Kubernetes cluster

### ISSUE THREAD

**Issue by zhukovsd** [kubernetes/kubernetes#67869]
Hello.

/kind bug

**What happened**:
1. Create a volume with `storageos volume create test-volume`
2. This volume fails to mount with `storageos volume mount test-volume /test`
3. Kubernetes also fails to mount with via PersistentVolume+PersistentVolume claim (I reproduced that by following "Pre-provisioned Persistent volumes" guide in StorageOS docs - https://docs.storageos.com/docs/install/kubernetes/preprovisioned)

**What you expected to happen**:
I anticipated that StorageOS volume would operate as expected or StorageOS CLI would report that's wrong.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure since the problem is probably caused either by hardware, my Kubernetes cluster or another external factor. Please see below for more details about the environment.

**Anything else we need to know?**:
I run 2-node on-premise Kubernetes cluster. The scheduler does not schedule any pods for the master node, so the only active node is a single worker node. Thus, StorageOS DaemonSet contains one pod:
```
NAME        DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
storageos   1         1         1         1            1           <none>          2d
```
Also, when I run `storageos version` on the master node, it fails with `Get http://storageos-cluster/version: failed to dial all known cluster members, (127.0.0.1:5705)` error because master node itself does not run StorageOS pod. So I run all `storageos` CLI commands from the worker node shell.

`storageos cluster health` does not display any issues:
```
root@node1 ~ # storageos cluster health
NODE   ADDRESS       CP_STATUS  DP_STATUS
node1  159.69.116.1  Healthy    Healthy
```

`storageos volume ls` displays volume status as active:
```
root@node1 ~ # storageos volume ls
NAMESPACE/NAME       SIZE  MOUNT  SELECTOR  STATUS  REPLICAS  LOCATION
default/test1        15GB                   active  0/0       node1 (healthy)
```

While playing with StorageOS interactive demos on kotacoda - http://play.storageos.com, I noted that StorageOS creates a folder in `/var/lib/storageos/volumes` for every created volume.

On my machine, this folder is empty. Note `drwxrwxrwx` permissions for `volumes` folder. I set it in order to validate that it is not the reason for StorageOS to not being able to create a volume.
```
root@node1 ~ # ls -la /var/lib/storageos/volumes/
total 8
drwxrwxrwx 2 root root 4096 Aug 24 00:20 .
drwxr-xr-x 8 root root 4096 Aug 24 19:49 ..
```

Also, I found that after calling `storageos volume create`, `/var/lib/storageos/logs/storageos.log` contains a number of logging entries, one of which with `level=error`:
```
time="2018-08-24T22:38:54Z" level=error msg="filesystem client: presentation create failed" action=create error="<nil>" module=statesync reason="Create refused by validator" volume_uuid=0a8f6232-c0f5-9ed1-a213-5669ed9533ae                                                                                      
time="2018-08-24T22:38:54Z" level=info msg="virtual bool FsConfig::PresentationEventSemantics::Validate(event_type): Not adding pr_filename '0a8f6232-c0f5-9ed1-a213-5669ed9533ae' for volume 238534 - already exists for volume 238534 category=fscfg level=warn" category=fscfg module=supervisor                 
time="2018-08-24T22:38:54Z" level=info msg="validator 'device_validator' rejected Event{type CREATE} category=libcfg level=warn" category=libcfg module=supervisor
```

I found a StackOverflow discussion which seems to be relevant - https://stackoverflow.com/questions/51292759/rancher-kubernetes-and-storageos-persistent-storage-volume-mount-issue
Although, this thread does not contain any solution.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
root@master ~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
On-premise cluster with 2 nodes, master (scheduler does not schedule any pods to run there), and worker. Mount propagation enabled both in Kubernetes (it's enabled by default in k8s 1.10+) and in Docker, validated with:
```
# A successful run is proof of mount propagation enabled
docker run -it --rm -v /mnt:/mnt:shared busybox sh -c /bin/date
```

- OS (e.g. from /etc/os-release):
`Debian GNU/Linux 9 (stretch)` on both nodes.

- Kernel (e.g. `uname -a`):
```
Linux master 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
```
```
Linux node1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
```

- Install tools:
Cluster installed with https://github.com/kubernetes-incubator/kubespray

Please let me know if any other details could be useful.
Thanks.

**Comment by luckyluke192** [comment]
Hi,
Have you try to set STORAGEOS_HOST env variable to the address of any of the node running storageos daemon pod?
`export  STORAGEOS_HOST=159.69.116.1`
in your case.

**Comment by zhukovsd** [comment]
Hi, @luckyluke192 

I did not try your suggestion exactly, but I changed k8s cluster so every node (include `master`) runs StorageOS pod. Thus, on every node we can call `storageos` CLI commands.

Although, the problem with `storageos volume create` failing to create a volume still persists.

I reported that issue to StorageOS devs - https://github.com/storageos/storageos.github.io/issues/196
It looks like they were able to reproduce the problem.

**Comment by zhukovsd** [comment]
The problem happens because Kubespray disables Kubernetes mount propagation by default.

In order to fix it, set `local_volume_provisioner_enabled: true` in `k8s-cluster.yml` and redeploy the cluster. Then, reinstall StorageOS.

More details here:
https://github.com/storageos/storageos.github.io/issues/196
