### ISSUE TITLE
service proxy for websocket is missing forwarded headers and query params

### ISSUE THREAD

**Issue by antmanler** [kubernetes/kubernetes#67878]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Build a service proxy URL to access a websocket service, the apiserver do not add `X-Forwarded-Uri`... headers in proxied request and missing query parameters in requested URL 

**What you expected to happen**:

The backend websocket server should read `X-Forwarded-Uri` in requested headers,
and can get query params properly

**How to reproduce it (as minimally and precisely as possible)**:

Try any websocket needs query params to work right

**Anything else we need to know?**:
I believe the missing of query params is due to [newThrottledUpgradeAwareProxyHandler](https://github.com/kubernetes/kubernetes/blob/733a381ec42ede15cd0499bc502a0cba6612f3ca/pkg/registry/core/service/proxy.go#L74) method that does not turn on the option `UseRequestLocation`

**Environment**:
- Kubernetes version (use `kubectl version`):
    > Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
    > Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wenjiaswe** [comment]
cc @caesarxuchao
