### ISSUE TITLE
Feature request: schedule pod to other kubelets if kubelet continuously rejects pod?

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#67874]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

We write a GPU virtualization device plugin. Under some cases, the device plugin could not allocate GPUs for pod, then kubelet will reject the pod. Scheduler will always schedule it to the same kubelet if the kubelet gets same highest score from scheduler as before. However kubelet will reject it continuously.

Not sure whether kubelet will reject pod continuously in other cases.

**What you expected to happen**:

Schedule pod to other kubelets if the kubelet continuously rejects pod.

Some thought:
* Add the kubelet to black list for some time if it continuously rejects pod.
* Give the kubelet lower score then scheduler will not schedule pod to it.

**Comment by hex108** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by tanshanshan** [comment]
use _nodeAffinity_ avoid scheduling pod to it , is it ok ?

**Comment by hex108** [comment]
We do not know which kubelet has the problem in advance, so it might not work well using `nodeAffinity`.

**Comment by k82cn** [comment]
That's reasonable; a prioritize to lowdown the score of node seems better. In our produce, we have blockhost feature that avoid scheduling task to the node:
https://www.ibm.com/support/knowledgecenter/en/SSZUMP_7.1.2/shared_files/host_blocking_featureref.html

> Under some cases, the device plugin could not allocate GPUs for pod,

@hex108 , I'm not sure whether this is a regular rejection or race condition; if it's a normal case,
it's better to have a customized scheduler (or extender) to work with your device plugin.

**Comment by hex108** [comment]
@k82cn Blockhost feature is great! Yes, it seems better to add a generic way to lowdown the score of node. If it could be added, we do not need to write a customized scheduler :) (For us, it is a normal case.)

Another thought, not sure whether it could be generic:
* Step 1. If the device plugin could not allocate GPUs for pod for X times in Y minutes, it adds a new NodeCondition type `FailedAllocateXXX`  to kubelet's node conditions.
* Step 2. Write a scheduler extender, it will give a lower score if it finds NodeCondition `FailedAllocateXXX` is true in kubelet's status.

**Comment by k82cn** [comment]
> For us, it is a normal case.

Honestly, prefer to make this as exception. As you known, reject and lowdown the score is a heavy operation which will impact the throughput/performance of cluster. So it's better to let scheduler
or customized scheduler made the right decision almost everytime, and use such feature to handle
exception.

**Comment by hex108** [comment]
@k82cn Thanks for the suggestion.

**Comment by resouer** [comment]
Just discussed offline. There're actually two problems been mixed here.

The root cause of this issue is actually Device Plugin fails to allocate a device for many times. My suggestion is, in this case, it make more sense to handle it in Device Plugin and remove this device after certain number of `Allocate()` failures.

The second problem is what if scheduler was wrongly (or on purposed?) configured with only a few predicates? Should we make `GeneralPredicates` as MUST in scheduler policy? Or define a MUST group instead? 

Open for discussion.

**Comment by hex108** [comment]
Open for some time. /remove-lifecycle rotten

**Comment by hex108** [comment]
Open for some time.

/remove-lifecycle rotten
