### ISSUE TITLE
Update to go1.11

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#67872]
Keeping 👀on this. Official [docker upstream image](https://hub.docker.com/r/library/golang/) isn't available yet, so I can't build kube-cross locally yet.

Will need gofmt changes for sure (and they aren't backwards compatible).

cc: @ixdy @luxas

**Comment by dims** [comment]
looks like waiting on https://github.com/docker-library/golang/pull/234 to merge

**Comment by ixdy** [comment]
I think we probably don't want to do this until k8s 1.13; it seems pretty late in the 1.12 release train to update.

**Comment by cblecker** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/69386
