### ISSUE TITLE
Kubeadm reset failed to list running pods using crictl: exit status 1.

### ISSUE THREAD

**Issue by FOSquare** [kubernetes/kubernetes#67879]
> /kind bug
/sig kubeadm
**What happened**:
When I try kubeadm reset, The results are 
"[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
[reset] removing kubernetes-managed containers
[reset] cleaning up running containers using crictl with socket /var/run/dockershim.sock
[reset] failed to list running pods using crictl: exit status 1. Trying to use docker instead[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]"

**What you expected to happen**:

I am not sure this is normal or not

**How to reproduce it (as minimally and precisely as possible)**:
Kubeadm reset

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):   version): "v1.11.2"
- Cloud provider or hardware configuration: Dell Poweredge R210
- OS (e.g. from /etc/os-release):  Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):  4.13.0-36-generic
- Install tools:  I use ansible to install kubeadm, kubelet and kubectl
- Others:

**Comment by FOSquare** [comment]
I tried sudo kubeadm config images pull. It works fine as below

[config/images] Pulled k8s.gcr.io/kube-apiserver-amd64:v1.11.2
[config/images] Pulled k8s.gcr.io/kube-controller-manager-amd64:v1.11.2
[config/images] Pulled k8s.gcr.io/kube-scheduler-amd64:v1.11.2
[config/images] Pulled k8s.gcr.io/kube-proxy-amd64:v1.11.2
[config/images] Pulled k8s.gcr.io/pause:3.1
[config/images] Pulled k8s.gcr.io/etcd-amd64:3.2.18
[config/images] Pulled k8s.gcr.io/coredns:1.1.3

And I chekc the status of kubelet. it seems also normal as shown below:
 systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since mar. 2018-08-28 11:24:07 CEST; 7min ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 30569 (kubelet)
    Tasks: 19
   Memory: 36.2M
      CPU: 17.718s
   CGroup: /system.slice/kubelet.service
           └─30569 /usr/bin/kubelet

août 28 11:30:32 erebos kubelet[30569]: I0828 11:30:32.180310   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:30:42 erebos kubelet[30569]: I0828 11:30:42.228904   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:30:52 erebos kubelet[30569]: I0828 11:30:52.278277   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:02 erebos kubelet[30569]: I0828 11:31:02.327142   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:12 erebos kubelet[30569]: I0828 11:31:12.377011   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:22 erebos kubelet[30569]: I0828 11:31:22.428807   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:32 erebos kubelet[30569]: I0828 11:31:32.478059   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:42 erebos kubelet[30569]: I0828 11:31:42.527221   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
août 28 11:31:52 erebos kubelet[30569]: I0828 11:31:52.576348   30569 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach

Anyone can help me? thanks a lot.

**Comment by FOSquare** [comment]
Anyone have the same problem?
I could cretae the cluster normally. So I am not sure whether this is a problem or not. Can someone answer me, thanks a lot.

**Comment by neolit123** [comment]
this is not a critical issue.
also the reset behavior was changed in 1.12 for docker vs other CRI.

/close
