### ISSUE TITLE
Error creating: No API token found for service account "weave-net", retry after the token is automatically created and added to the service account

### ISSUE THREAD

**Issue by misteruly** [kubernetes/kubernetes#67882]
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
      labels:
        name: weave-net
      namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: weave-net
      labels:
        name: weave-net
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
          - namespaces
          - nodes
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - 'networking.k8s.io'
        resources:
          - networkpolicies
        verbs:
          - get
          - list
          - watch
      - apiGroups:
        - ''
        resources:
        - nodes/status
        verbs:
        - patch
        - update
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: weave-net
      labels:
        name: weave-net
    roleRef:
      kind: ClusterRole
      name: weave-net
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: Role
    metadata:
      name: weave-net
      namespace: kube-system
      labels:
        name: weave-net
    rules:
      - apiGroups:
          - ''
        resources:
          - configmaps
        resourceNames:
          - weave-net
        verbs:
          - get
          - update
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - create
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: weave-net
      namespace: kube-system
      labels:
        name: weave-net
    roleRef:
      kind: Role
      name: weave-net
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: weave-net
      labels:
        name: weave-net
      namespace: kube-system
    spec:
      # Wait 5 seconds to let pod connect before rolling next pod
      minReadySeconds: 5
      template:
        metadata:
          labels:
            name: weave-net
        spec:
          containers:
            - name: weave
              command:
                - /home/weave/launch.sh
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: 'weaveworks/weave-kube:2.4.0'
              livenessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
                initialDelaySeconds: 30
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
                - name: xtables-lock
                  mountPath: /run/xtables.lock
                  readOnly: false
            - name: weave-npc
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: 'weaveworks/weave-npc:2.4.0'
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
              volumeMounts:
                - name: xtables-lock
                  mountPath: /run/xtables.lock
                  readOnly: false
          hostNetwork: true
          hostPID: true
          restartPolicy: Always
          securityContext:
            seLinuxOptions: {}
          serviceAccountName: weave-net
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: weavedb
              hostPath:
                path: /var/lib/weave
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
            - name: xtables-lock
              hostPath:
                path: /run/xtables.lock
      updateStrategy:
        type: RollingUpdate

kubectl apply -f  weave-daemonset-k8s-1.7.yaml

daemonset    report an error: Error creating: No API token found for service account "weave-net", retry after the token is automatically created and added to the service account

kubectl describe sa weave-net -n kube-system  

Name:           weave-net
Namespace:      kube-system
Labels:         name=weave-net
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"name":"weave-net"},"name":"weave-net","namespace":"kube-system"}}

Image pull secrets:     <none>

Mountable secrets:      <none>

Tokens:                 <none>

There are no token values,So how will token values be generated??

apiVersion: v1
kind: Secret
metadata:
  name: weave-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: weave-net
type: kubernetes.io/service-account-token
#data:
#  data-1: dmFsdWUtMQ0K
#  data-2: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-net
  labels:
  name: weave-net
  namespace: kube-system
secrets:
- name: weave-secret

I generated it manually

[root@master k8s_tomcat]# kubectl describe sa weave-net -n kube-system
Name:           weave-net
Namespace:      kube-system
Labels:         <none>
Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":null,"name":"weave-net","namespace":"kube-system"},"secrets":[{"name":...

Image pull secrets:     <none>

Mountable secrets:      weave-secret

Tokens:                 <none>

In this way, token is not generated,What the hell should I do???thinks!!

**Comment by liggitt** [comment]
The service account token controller generates tokens and adds them to the service account asynchronously. Ensure your kube controller manager is started with a service account token signing key.

**Comment by pohly** [comment]
I'm seeing the same error when setting up a CSI driver. In my case, the .yaml file is similar to https://github.com/kubernetes-csi/docs/blob/master/book/src/example/csi-setup.yaml (just the CSI driver is a bit different), and the command is `kubectl create -f csi-setup.yaml`.

This then fails sometimes (but not always) with a non-zero exit code from kubectl:
```
storageclass.storage.k8s.io/csi-xxx-sc created
serviceaccount/csi-service-account created
clusterrole.rbac.authorization.k8s.io/csi-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-role-binding created
Error from server (ServerTimeout): error when creating "STDIN": No API token found for service account "csi-service-account", retry after the token is automatically created and added to the service account
```

Is this approach for creating service account and entities using it flawed? It seems to suffer from a race condition.

As far as I can tell, the error can be safely ignored:
- all four entities were created successfully
- the csi-pod is up-and-running afterwards, without errors

The only problem is that it is hard to ignore this and only this error when invoking kubectl from a script or doing the same operations via the API.

**Comment by liggitt** [comment]
> It seems to suffer from a race condition.

Direct creation of pods must wait for the service account and token to be provisioned. 

Workload controllers will retry pod creation until success, insulating from this required wait. 

Work in progress is moving service account token generation to be just in time, which will remove the need for this wait. xref https://github.com/kubernetes/kubernetes/issues/67440

**Comment by pohly** [comment]
Indeed, I wasn't reading the output correctly. The pod isn't started when the failure occurs and then that part must be retried, but because it is part of a larger .yaml file, kubectl then fails with `already exists` errors.

So the bottom line is that the current CSI example .yaml file no longer works and must be split up into two files, with some suitable logic inbetween. What's a good `kubectl` command for checking that service account and token have been provisioned?

`kubectl get secrets | grep -q ^csi-service-account-token` seems close enough, I'm just wondering if there's something simple that doesn't rely on sub-string matching of the name.

I'm not sure whether this also needs to be fixed in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_volumes.go#L323 - as far as I can tell, it just creates account, role and pod without any intermediate waits. I don't know whether this has already failed in the Kubernetes CI, but at least when running a test based on that code locally I saw the same error.

**Comment by liggitt** [comment]
> the current CSI example .yaml file no longer works

Do you have a pointer to that file? Launching a pod directly in a manifest (as opposed to a workload object like a daemonset, replicaset, or job) isn't usually recommended, since it's not robust in the face of failures or errors.

**Comment by pohly** [comment]
Here's the file: https://github.com/kubernetes-csi/docs/blob/master/book/src/example/csi-setup.yaml

This was supposed to be as simple as possible. But for real deployments a daemonset is the recommended approach, so the example might as well just use that.

Same for the automated testing.

**Comment by pohly** [comment]
I should add that while I added that example to the docs, the same approach had already been used by other developers before without issues. The E2E test has done it like this since the beginning. Has everyone just been lucky so far or has something changed in Kubernetes >= 1.9 which makes it more likely for the timing to go wrong?

**Comment by liggitt** [comment]
Nothing has changed in this area since 1.0

Running in an underpowered environment can increase the lag if the controller manager takes longer to provision the dependent objects
