### ISSUE TITLE
show-all deprecation message unhelpful

### ISSUE THREAD

**Issue by rcorre** [kubernetes/kubernetes#67895]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

```
[rodencor@heredesk ~]$ kubectl get pods -a
Flag --show-all has been deprecated, will be removed in an upcoming release
```

Now I'm lost. What am I supposed to use instead of `-a`? Is `-a` the default now?

**What you expected to happen**:

```
[rodencor@heredesk ~]$ kubectl get pods -a
Flag --show-all has been deprecated, will be removed in an upcoming release. Use <some-flag> instead
```

... or ... 

```
[rodencor@heredesk ~]$ kubectl get pods -a
Flag --show-all has been deprecated, will be removed in an upcoming release. Pods of all states are shown by default now.
```

... or ... 

(whatever the real explanation is)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
Show all is the default now, -a is not required

**Comment by rcorre** [comment]
/remove-lifecycle stale

Still unclear that `-a` is default.

**Comment by Ghazgkull** [comment]
Just hit the same issue with this incomplete deprecation message and ended up here. Would be great if the message could include the remediation instructions ("-a is the default now, simply remove it").

**Comment by Hardy2015** [comment]
same for me

**Comment by liggitt** [comment]
the option is removed in 1.14 (https://github.com/kubernetes/kubernetes/pull/69255)
