### ISSUE TITLE
pull image from a cross-subscription azure container registry does not work by MSI

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#67892]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
PR(https://github.com/kubernetes/kubernetes/pull/66429) fixed pull image error from a cross-subscription azure container registry by **service principal**, while for MSI, this issue is not fixed. 
Need to find a way how to fix this issue for MSI, related code is here:
https://github.com/kubernetes/kubernetes/blob/3741f0262f2fa270e61cf175e573c69ff955f0ae/pkg/credentialprovider/azure/azure_credentials.go#L181-L197

Here the difficulty is `registryClient.List()` could not list all ACR since it's based on one subscriptionID:
```
registryClient := containerregistry.NewRegistriesClient(subscriptionID)
```
So if we could not get `loginServer` in a different subscription, how could we set the `DockerConfigEntry`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
error msg would be like following when pull a repository from an ACR in another subscription:
```
Events:
  Type     Reason     Age                From                               Message
  ----     ------     ----               ----                               -------
  Normal   Scheduled  31s                default-scheduler                  Successfully assigned default/nginx to k8s-agentpool-95620664-0
  Normal   Pulling    15s (x2 over 30s)  kubelet, k8s-agentpool-95620664-0  pulling image "andyacr.azurecr.io/nginx-server:1.0.0"
  Warning  Failed     14s (x2 over 28s)  kubelet, k8s-agentpool-95620664-0  Failed to pull image "xxx.azurecr.io/nginx-server:1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://xxx.azurecr.io/v2/nginx-server/manifests/1.0.0: unauthorized: authentication required
  Warning  Failed     14s (x2 over 28s)  kubelet, k8s-agentpool-95620664-0  Error: ErrImagePull
  Normal   BackOff    1s (x2 over 27s)   kubelet, k8s-agentpool-95620664-0  Back-off pulling image "andyacr.azurecr.io/nginx-server:1.0.0"
  Warning  Failed     1s (x2 over 27s)   kubelet, k8s-agentpool-95620664-0  Error: ImagePullBackOff
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v.9 - v1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by andyzhangx** [comment]
By further investigation, I think we should implement LazyProvider for azure acrProvider:
// DockerConfigProvider is the interface that registered extensions implement
// to materialize 'dockercfg' credentials.
type DockerConfigProvider interface {
	// Enabled returns true if the config provider is enabled.
	// Implementations can be blocking - e.g. metadata server unavailable.
	Enabled() bool
	// Provide returns docker configuration.
	// Implementations can be blocking - e.g. metadata server unavailable.
	Provide() DockerConfig
	// LazyProvide() gets called after URL matches have been performed, so the
	// location used as the key in DockerConfig would be redundant.
	LazyProvide() *DockerConfigEntry
}

Related code:
https://github.com/kubernetes/kubernetes/blob/3741f0262f2fa270e61cf175e573c69ff955f0ae/pkg/kubelet/dockershim/helpers.go#L345

https://github.com/kubernetes/kubernetes/blob/3741f0262f2fa270e61cf175e573c69ff955f0ae/pkg/credentialprovider/provider.go#L43-L48

**Comment by andyzhangx** [comment]
Update:
It's hard to fix this since in the beginning we cannot list ACR in another subscription, `registryClient.List(ctx)` will always list acr under current subscription, and without target loginServer address of ACR, we cannot get `registryRefreshToken`:
https://github.com/kubernetes/kubernetes/blob/3741f0262f2fa270e61cf175e573c69ff955f0ae/pkg/credentialprovider/azure/azure_credentials.go#L220

And in `LazyProvide` func, we cannot get target repo, it's not passed on

**Comment by justaugustus** [comment]
@andyzhangx -- is this still an issue? If not, let's `/close` it out.

**Comment by andyzhangx** [comment]
@justaugustus it's still an issue, and currently it should be low priority, let's keep it
