### ISSUE TITLE
Failure in Conformance test - Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#67903]
/kind bug

Don't think this is related to, but not sure  https://github.com/kubernetes/kubernetes/issues/60745 .

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
I'm thinking the `Daemon set [Serial] should update pod when spec was updated and update strategy is RollingUpdate [Conformance]` should be moved out of conformance... but not quite sure yet. 

## 
- Sonubuoy e2e results link:  https://scanner.heptio.com/519c1537b4a7fa4ad0855f621b2c678f/diagnostics/

- Another nice thing to fix: 

The fact that we upgrade from a serv-hostname to a redis image is kinda weird.  Why redis ?  From a security perspective, the smaller the dependent image the easier it is to confirm this test has a 'true positive' result set. 
```Aug 27 13:53:55.394: INFO: Wrong image for pod: daemon-set-26bm5. Expected: gcr.io/kubernetes-e2e-test-images/redis-amd64:1.0, got: gcr.io/kubernetes-e2e-test-images/serve-hostname-amd64:1.0.```

cc @kubernetes/sig-testing

**Comment by AishSundar** [comment]
/milestone v1.13
/priority important-soon
/kind failing-test

This test failure will block 1.13 beta. Is there someone looking into this from sig-apps?

/cc @jberkus @mortent

**Comment by mortent** [comment]
I will take a look at this tomorrow. I suspect this is the same issue as #69356, but I will verify.

/assign

**Comment by mortent** [comment]
This test fails in upgrade tests on the testgrid at the moment and that is due to the issue described in #69445.
This fails due to a timeout and was reported before the change that caused the other test failures was merged. So it seems to be a separate issue even if it is the same test that is failing.

**Comment by mariantalla** [comment]
Hey y'all, just checking in on this as it's blocking [master-upgrade](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster) tests.

It seems there is a PR open for an issue that's related. Is there more that needs to happen after that?

**Comment by AishSundar** [comment]
https://github.com/kubernetes/kubernetes/pull/69988 just merged and it claims to fix this issue,. lets watch for the next run

**Comment by nikopen** [comment]
DaemonSet tests passed on run 1842, seems to have been fixed: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

if it doesn't pop up again -

/close
