### ISSUE TITLE
kubernetes stateful sets etc/hosts 

### ISSUE THREAD

**Issue by viveksaiaws** [kubernetes/kubernetes#67906]
@kubernetes/sig-contributor-experience-feature-requests

**What happened**:
i have 3 pod cassandra stateful set on ubuntu / kube 1.9
`cassandra-0` `etc/hosts/` looks like 
`
172.30.243.180	cassandra-0.cassandra.gec-system.svc.cluster.local	cassandra-0
`

**What you expected to happen**:
i want like 
`
172.30.243.180	cassandra-0.cassandra.gec-system.svc.cluster.local	cassandra-0 '
 172.30.243.xxx	cassandra-1.cassandra.gec-system.svc.cluster.local	cassandra-1  '
 172.30.243.xxx	cassandra-2.cassandra.gec-system.svc.cluster.local	cassandra-2
`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: IBM blumix
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by xiaoxubeii** [comment]
You can use headless service and subdomain to add pod A record to kube-dns: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

**Comment by viveksaiaws** [comment]
can we work with helm post hook or init container to set up before up and running @xiaoxubeii
