### ISSUE TITLE
Expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'...

### ISSUE THREAD

**Issue by tech509201941** [kubernetes/kubernetes#67915]
If I want to execute the following command:

`cd .kube`
`KUBECONFIG=./config`

`kubectl exec -n cattle-system $(kubectl --kubeconfig $KUBECONFIG get pods -n cattle-system -o json | jq -r '.items[] | select(.spec.containers[].name=="cattle-server") | .metadata.name') -- reset-password`

it results in this error:

```
-bash: jq: command not found
error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
POD_NAME and COMMAND are required arguments for the exec command
See 'kubectl exec -h' for help and examples.
```

Can anyone think of a solution for this?

**Comment by Dani-D** [comment]
@kubernetes/sig-apps-misc

**Comment by kow3ns** [comment]
https://stackoverflow.com/questions/tagged/kubernetes is a better place to ask this question. Or the sig-apps channel on slack.

/close
