### ISSUE TITLE
Deprecation of maximum-dead-containers-per-container

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/kubernetes#67937]
/kind bug

**What happened**:

We're trying to migrate to the kubelet configuration file but there isn't any equivalent configuration entry for:
- `--minimum-container-ttl-duration`
- `--maximum-dead-containers-per-container`

I reviewed the kubelet [configuration types](https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/kubelet/apis/kubeletconfig/v1beta1/types.go) and I wasn't able to find these options.

These options are really useful for short lived tasks, this allows to any logging collection tools to be able to tail these files.

**Comment by neolit123** [comment]
hi, looking at branch / file you posted i'm assuming k8s version 1.11.

these two flags are deprecated and there is no equivalent in the kubelet configuration.
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#deprecation-of-existing-feature-flags-to-reclaim-disk

(similar flags switched to corresponding eviction functionality)

there shouldn't be any need to use these two flags as in 1.11 they are a NOP (no operation).

/sig node
/close

please re-open if you have further questions.
thanks.

**Comment by neolit123** [comment]
it would be best to get a response by sig-node on this one.
you can try slack #sig-node , their mailing list...but also stack-overflow is a good option that gets questions answered.

**Comment by sjmiller609** [comment]
I have found in practice that --minimum-container-ttl-duration is not no-operation as of at least 1.15. If you set this flag, you can see with 'docker ps -a' that containers remain "stopped" for at least the configured TTL before becoming "removed"
