### ISSUE TITLE
The results of 'kubectl version' command cannot display normaly in suse server 12 sp2.

### ISSUE THREAD

**Issue by lasshpanzer** [kubernetes/kubernetes#67932]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
1. Run command "ALLOW_PRIVILEGED=true FEATURE_GATES=CSIPersistentVolume=true,MountPropagation=true RUNTIME_CONFIG="storage.k8s.io/v1alpha1=true" LOG_LEVEL=5 hack/local-up-cluster.sh "
over k8s1.10 and k8sv1.12.0-alpha.1 through suse server 12 sp2；
2. Run command  'kubectl version', there are many empty strings in version info as below: 

k8sv1.12.0-alpha.1:
linux-i5hz:~ # kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"2018-08-27T09:51:29Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.1", GitCommit:"94c2c6c8423d722f436305cd67ef515a8800d723", GitTreeState:"archive", BuildDate:"2018-08-28T07:09:35Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

k8s1.10:
linux-i5hz:~# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"2018-08-27T09:51:29Z", G                      oVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"2018-08-27T09:51:29Z", G                      oVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

3.Run command 'kubectl create -f csi-provisioner.yaml ' and  'kubectl logs csi-provisioner', there is a bug report as below:

linux-i5hz:~# 'kubectl create -f csi-provisioner.yaml
NAME                      READY     STATUS              RESTARTS   AGE
csi-provisioner-0      2/3       CrashLoopBackOff    3             5m

linux-i5hz:~# kubectl logs csi-provisioner
I0828 06:56:07.465442       1 csi-provisioner.go:70] Building kube configs for running in cluster...
panic: could not parse pre-release/metadata (-master+$Format:%h$) in version "v0.0.0-master+$Format:%h$"

goroutine 1 [running]:
github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/kubernetes/pkg/util/version.MustParseSemantic(0xc42030a7e0, 0x19, 0x0)
        /root/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/kubernetes/pkg/util/version/version.go:119 +0x6c
github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.NewProvisionController(0x1ac45e0, 0xc4200aa0f0, 0x7fff3f685a9f, 0x11, 0x1aa42c0, 0xc42030c900, 0xc42030a7e0, 0x19, 0x0, 0x0, ...)
        /root/gopath/src/github.com/kubernetes-csi/external-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:346 +0x33e
main.init.0()
        /root/gopath/src/github.com/kubernetes-csi/external-provisioner/cmd/csi-provisioner/csi-provisioner.go:107 +0x6ef
main.init()
        <autogenerated>:1 +0x2f8

**What you expected to happen**:
Pod can run normally.

**Anything else we need to know?**:
K8s does not support SUSE?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-alpha.1 and v1.10:

- Cloud provider or hardware configuration: 8G memory 

- OS (e.g. from /etc/os-release): 
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

- Kernel (e.g. `uname -a`):

Linux linux-i5hz 4.4.21-69-default #1 SMP Tue Oct 25 10:58:20 UTC 2016 (9464f67) x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
docker-18.03.1-ce
etcd-v3.3.0
go1.9.2 and go1.10.2
- Others:
Rpm packages related to gcc tool and docker.
linux-glibc-devel-3.12-6.54.noarch.rpm
libasan0-4.8.5-24.1.x86_64.rpm 
libatomic1-5.2.1+r226025-4.1.x86_64.rpm
libgomp1-5.2.1+r226025-4.1.x86_64.rpm
libitm1-5.2.1+r226025-4.1.x86_64.rpm
libtsan0-5.2.1+r226025-4.1.x86_64.rpm
glibc-devel-2.19-31.9.x86_64.rpm
libstdc++48-devel-4.8.5-24.1.x86_64.rpm
gcc48-4.8.5-24.1.x86_64.rpm
gcc48-c++-4.8.5-24.1.x86_64.rpm
gcc-4.8-6.189.x86_64.rpm
gcc-c++-4.8-6.189.x86_64.rpm
libcgroup1-0.41.rc1-4.1.x86_64.rpm

@kubernetes/sig-contributor-experience-<bugs>

**Comment by islinwb** [comment]
@lasshpanzer  What's the version of `kubectl` (`make` from which version)? The code is from upstream without any change?

**Comment by lasshpanzer** [comment]
@islinwb I `make` base on the src code (version is 1.10 and v1.12.0-alpha.1) and```
 echo alias kubectl='$HOME/kubernetes/cluster/kubectl.sh' >> /etc/profile
source /etc/profile
``` 
 I did not change any code.

**Comment by dims** [comment]
@lasshpanzer the problem is in the code in `kubernetes-csi/external-provisioner` not in kubectl itself.  Looks like you already created an issue there - https://github.com/kubernetes-csi/external-provisioner/issues/128 - So let's close this one up.

/close

**Comment by dims** [comment]
I really don't see the need to reopen this bug, but @lasshpanzer insisted that this be reopened again. 

FWIW, the external-provisioner should be using `utilversion.ParseSemantic` if it wants to support scenarios where the kubernetes version may be a development workstation without proper semver. It currently uses `utilversion.MustParseSemantic` which throws a panic by design.

CC @xing-yang

**Comment by xing-yang** [comment]
Thanks @dims for the info.  The code that calls utilversion.MustParseSemantic is in kubernetes-incubator.  It checks the version and decides what feature is supported.  If we change that to utilversion.ParseSemantic, it can avoid throwing a panic but it still can't find the version and determine whether a feature is supported.

I am just wondering why "kubectl version" doesn't display version info on SUSE.  @lasshpanzer is running local cluster on his SUSE setup.  I'm also running local custer on my ubuntu 16.04.  "kubectl version" displays version info correctly on my setup.  Is SUSE not a supported environment by K8S or maybe local cluster does not work on SUSE and we should try to deploy it using a different method?

**Comment by neolit123** [comment]
> Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", 

hi all.
please take a look at this comment:
https://github.com/kubernetes/kubernetes/issues/67949#issuecomment-416620933

the version info can be missing if you the binary was built incorrectly.
if these binaries come from SUSE a report should be filed for the distro instead of here.

the **better** alternative is to always download the official k8s binaries.

**Comment by xing-yang** [comment]
Thanks @neolit123.  I think this can be closed now.

@lasshpanzer Please try to download the official k8s binaries and test them on SUSE.

**Comment by Bibop182** [comment]
I faced a similar problem.

This error occurs if, when building executable files, the release.sh script was not launched from the root directory of the git as a working directory. 
For correct compilation, environment variables must be filled in something like this:

```
KUBE_GIT_COMMIT=af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38
KUBE_GIT_MAJOR=1
KUBE_GIT_MINOR=20
KUBE_GIT_TREE_STATE=clean
KUBE_GIT_VERSION=v1.20.0
```

The `kube::build::verify_prereqs()` function in the `kubernetes/build/common.sh` script fills in these values if you call this function from the kubernetes root directory (root git directory).
You can do this

```
git clone --depth 1 --branch v1.20.0 --single-branch https://github.com/kubernetes/kubernetes
cd kubernetes
echo KUBE_GIT_VERSION=${KUBE_GIT_VERSION/+/_} # Empty value
source build/common.sh
set +o errexit
set +o nounset
kube::build::verify_prereqs false
echo KUBE_GIT_VERSION=${KUBE_GIT_VERSION/+/_} # v1.20.0
```

This will help to make sure that everything is filled in correctly, and only then start compilation.

```
kube::build::clean &&
kube::build::verify_prereqs &&
kube::build::build_image &&
kube::build::run_build_command make &&
kube::build::copy_output
```

or simply

```
. build/release.sh
```

If the KUBE_GIT_VERSION variable is still not filled in correctly, then try debug trace the function `kube::version::get_version_vars()` from the file `kubernetes/hack/lib/version.sh`

```
source ./hack/lib/version.sh
set -o functrace
set -x
kube::version::get_version_vars
set +x
set +o functrace
```
