### ISSUE TITLE
[Documentation] Add a nice search experience in the website

### ISSUE THREAD

**Issue by s-pace** [kubernetes/kubernetes#67940]
👋  kubernetes team,

As developers, we've all had some deployment issues. Your tool is great and we'll be forever grateful for how it changed this pain point. We are so eager to discover your documentation that we thought it deserves a nice learn-as-you-type experience.

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://docsearch-kubernetes.netlify.com/#) of what DocSearch on the kubernetes website could look like here. Feel free to try it and let us know what you think.

[![demo of DocSearch + kubernetes](https://cl.ly/659847f39326/Screen%20Recording%202018-08-28%20at%2012.54%20PM.gif)](https://docsearch-kubernetes.netlify.com/#)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'f2fb6f36ea10513ed12caca35ad986fa',
  indexName: 'kubernetes',
  inputSelector: '#search',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Feel free to update it if this one is not specific enough.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/kubernetes.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to analytics on the most searched terms or those with no results. All of this is of course entirely free.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by eranchetz** [comment]
+1

**Comment by s-pace** [comment]
👋 @wgliang 

Happy to provide any help to enhance the search experience. Let me know if you need a PR or if you have any feedback.

/remove-lifecycle stale

**Comment by s-pace** [comment]
/remove-lifecycle stale

Happy to help to integrate it.
