### ISSUE TITLE
kubelet does not have ClusterDNS IP configured and cannot create Pod 

### ISSUE THREAD

**Issue by VinayVanama** [kubernetes/kubernetes#67941]
Hi, I have created an EKS cluster and configured nodes for my cluster. Both my Cluster and Nodes are communicating. I'm trying to create a simple pod of my application and I'm getting the below error. 

kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
Back-off restarting failed container

Below is my Deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: analytics-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: analytics-server
    spec:
      containers:
      - name: analytics-server
        image: imagename
        volumeMounts:
        - name: hostvol
          mountPath: /opt/path-name
      volumes:
      - name: hostvol
        hostPath:
          path: /Users/path-name

Description of a pod:

Name:         analytics-server
Namespace:    default
Node:         ip-10-0-14-124.ec2.internal/10.0.9.68
Start Time:   Tue, 28 Aug 2018 16:09:58 +0530
Labels:       <none>
Annotations:  <none>
Status:       Running
IP:           10.0.10.80
Containers:
  analytics-server:
    Container ID:   docker://2d0f0cf43aff1a0d85252a36dbf09f6bebd15fffa6d0bafe3f5d21
    Image:          imagename
    Image ID:       docker-pullable://imagename@sha256:ebcc695cb0b0ca8945153c88f9c10d361384a5d66234a6f902d3b29
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 28 Aug 2018 16:31:10 +0530
      Finished:     Tue, 28 Aug 2018 16:31:10 +0530
    Ready:          False
    Restart Count:  9
    Environment:    <none>
    Mounts:
      /opt/path-name from hostvol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-d6xhh (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  hostvol:
    Type:          HostPath (bare host directory volume)
    Path:          /Users/path-name
    HostPathType:
  default-token-d6xhh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-d6xhh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From                                  Message
  ----     ------                 ----                ----                                  -------
  Normal   Scheduled              23m                 default-scheduler                     Successfully assigned analytics-server to ip-10-0-14-124.ec2.internal
  Normal   SuccessfulMountVolume  23m                 kubelet, ip-10-0-14-124.ec2.internal  MountVolume.SetUp succeeded for volume "hostvol"
  Normal   SuccessfulMountVolume  23m                 kubelet, ip-10-0-14-124.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-d6xhh"
  Normal   Pulled                 23m (x3 over 23m)   kubelet, ip-10-0-14-124.ec2.internal  Container image "imagename" already present on machine
  Normal   Created                23m (x3 over 23m)   kubelet, ip-10-0-14-124.ec2.internal  Created container
  Normal   Started                23m (x3 over 23m)   kubelet, ip-10-0-14-124.ec2.internal  Started container
  Warning  BackOff                8m (x68 over 23m)   kubelet, ip-10-0-14-124.ec2.internal  Back-off restarting failed container
  Warning  MissingClusterDNS      3m (x102 over 23m)  kubelet, ip-10-0-14-124.ec2.internal  pod: "analytics-server_default(b59bca0b-aaae-11e8-865d-12d947fdab32)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.

**Comment by SamolazovRoman** [comment]
i've this problem:
```
Events:
  Type     Reason                 Age                From                                                Message
  ----     ------                 ----               ----                                                -------
  Normal   Scheduled              34s                default-scheduler                                   Successfully assigned dev-karaoke-app-7b55dfb669-fkzcx to ip-10-0-101-51.eu-west-1.compute.internal
  Normal   SuccessfulMountVolume  33s                kubelet, ip-10-0-101-51.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "default-token-sz746"
  Normal   Pulled                 14s (x3 over 33s)  kubelet, ip-10-0-101-51.eu-west-1.compute.internal  Container image "XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/karaoke:0.9-130-ga181aad" already present on machine
  Normal   Created                14s (x3 over 33s)  kubelet, ip-10-0-101-51.eu-west-1.compute.internal  Created container
  Normal   Started                14s (x3 over 33s)  kubelet, ip-10-0-101-51.eu-west-1.compute.internal  Started container
  Warning  MissingClusterDNS      13s (x8 over 33s)  kubelet, ip-10-0-101-51.eu-west-1.compute.internal  pod: "dev-karaoke-app-7b55dfb669-fkzcx_karaoke(a2e2c415-c628-11e8-b1ee-021b6d6a3ca8)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
  Warning  BackOff                13s (x3 over 31s)  kubelet, ip-10-0-101-51.eu-west-1.compute.internal  Back-off restarting failed container
```

container with DB:

```
  Type     Reason                  Age                 From                                                 Message
  ----     ------                  ----                ----                                                 -------
  Normal   Scheduled               20m                 default-scheduler                                    Successfully assigned dev-karaoke-postgres-5d47bd87d8-llwzx to ip-10-0-103-249.eu-west-1.compute.internal
  Normal   SuccessfulMountVolume   20m                 kubelet, ip-10-0-103-249.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "default-token-sz746"
  Normal   SuccessfulAttachVolume  19m                 attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-b92ffaf8-c623-11e8-b1ee-021b6d6a3ca8"
  Normal   SuccessfulMountVolume   19m                 kubelet, ip-10-0-103-249.eu-west-1.compute.internal  MountVolume.SetUp succeeded for volume "pvc-b92ffaf8-c623-11e8-b1ee-021b6d6a3ca8"
  Normal   Pulled                  19m                 kubelet, ip-10-0-103-249.eu-west-1.compute.internal  Container image "postgres:alpine" already present on machine
  Normal   Created                 19m                 kubelet, ip-10-0-103-249.eu-west-1.compute.internal  Created container
  Normal   Started                 19m                 kubelet, ip-10-0-103-249.eu-west-1.compute.internal  Started container
  Warning  MissingClusterDNS       49s (x19 over 19m)  kubelet, ip-10-0-103-249.eu-west-1.compute.internal  pod: "dev-karaoke-postgres-5d47bd87d8-llwzx_karaoke(577072e1-c626-11e8-b1ee-021b6d6a3ca8)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
```

and what interesting:

i can run:
```
kubectl -n karaoke get po
```
output:
```
NAME                                    READY   STATUS             RESTARTS   AGE
dev-karaoke-app-7b55dfb669-fkzcx        0/1     CrashLoopBackOff   6          6m
dev-karaoke-postgres-5d47bd87d8-llwzx   1/1     Running            0          22m
```
i can't run:
```
kubectl -n karaoke exec -it  dev-karaoke-postgres-5d47bd87d8-llwzx sh
```
output:
```
Error from server: error dialing backend: dial tcp 10.0.103.233:10250: getsockopt: no route to host
```

**Comment by SamolazovRoman** [comment]
my problem is resolved after I recreate cluster EKS with user_data:
```
running script from this is link: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh
```

**Comment by luvpreetsingh** [comment]
This problem happened to us because initially when we launched the cluster, the Userdata was compatible with the Base AMI we were using for the worker nodes. But then, we updated our Base AMI in the cloudformation, but we did not update the Userdata.

Your userdata and AMI needs to be compatible

**Comment by joeyparis** [comment]
@luvpreetsingh What did you need to change in your `UserData`? I just updated my Base AMI and am running into this same issue.

**Comment by kyleian** [comment]
@joeyparis In a similar spot; any idea what compatibility issues there were?
