### ISSUE TITLE
Failing Tests : BeforeSuite gke-1.12-1.11-downgrade-cluster-parallel

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67953]
# Failing Jobs
[sig-release-1.12-all#gke-1.12-1.11-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-1.12-all#gke-1.12-1.11-downgrade-cluster-parallel)
# Failing Tests
[BeforeSuite](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-beta-stable1-downgrade-cluster-parallel/3425)
# Triage Results
[BeforeSuite](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-beta-stable1-downgrade-cluster-parallel&test=BeforeSuite)

Failing tests . Looks like its a testing failure.

/kind failing-test
/priority critical-urgent
/sig testing
/cc @tpepper @AishSundar

**Comment by guineveresaenger** [comment]
/close 
Tests show they've been passing for a while. Not sure of the reason, but will close for now.
