### ISSUE TITLE
CoreDNS does not resolve ExternalNames under cluser.local to A records

### ISSUE THREAD

**Issue by greghaynes** [kubernetes/kubernetes#67962]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:

When creating a service with an ExternalName of foo.namespace.svc.cluster.local I am unable to resolve that service from within the cluster. Using `dig` I see that a `CNAME` record is returned for my service but a corresponding `A` record for that `CNAME` is not also returned which results in no host found.

**What you expected to happen**:

When creating `myservice` service with an ExternalName of foo.namespace.svc.cluster.local I expect a `host myservice.namespace.svc.cluster.local` to resolve to the IP of `foo.namespace.svc.cluster.local`.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a cluster with CoreDNS enabled
- Define this service which should resolve to ClusterIP of the kubernetes service:
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  externalName: kubernetes.default.svc.cluster.local
  type: ExternalName
```
- Attempt to resolve `test.default.svc.cluster.local` from within k8s. e.g.:

`kubectl run my-shell --rm -i --tty --image ubuntu -- bash`
install dnsutils and `host test.default.svc.cluster.local`

**Anything else we need to know?**:

I verified that in a cluster with kube-dns this type of resolution does work.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2
- Cloud provider or hardware configuration: Local
- OS (e.g. from /etc/os-release): Ubuntu Bionic
- Kernel (e.g. `uname -a`): 4.15.0-29-generic
- Install tools:
- Others:

**Comment by chrisohaver** [comment]
Recently fix/merged/released in CoreDNS 1.2.1 ...  The fix properly resolve ExternalName services that point to cluster services. 

https://github.com/coredns/coredns/pull/2040

**Comment by greghaynes** [comment]
Looks like I'm one day behind pulling the fix - thanks!

**Comment by chrisohaver** [comment]
CoreDNS 1.2.1 isn't on the k8s docker image repo yet, still needs to be pushed there...

But it is on dockerhub repo... `coredns/coredns:1.2.1`

**Comment by dims** [comment]
@thockin Do you mind copying over the coredns image?

**Comment by fturib** [comment]
Image has been copied to staging-k8s.gcr.io, we need now to wait propagation to gcr.io. May take one day ...
