### ISSUE TITLE
RFE (e2e): allow registry override, and consistent labeling.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#67964]
**Is this a FEATURE REQUEST?**:
For air-gapped test runs it's a hard requirement to be able to pull the testing images from a private registry, and it's also a requirement to apply a unified label for cleaning.  

**What happened**:
Currently, neither of these is supported in overrides to the e2e-test-framework

**What you expected to happen**:
Optional overrides with sane defaults. 

/assign @timothysc 
/cc @dims @kubernetes/sig-testing 
/kind feature

**Comment by PatrickLang** [comment]
does this overlap with https://github.com/kubernetes/kubernetes/pull/60848?

**Comment by joshrosso** [comment]
ping @timothysc, wanted to verify this *does* overlap with https://github.com/kubernetes/kubernetes/pull/60848 ?
