### ISSUE TITLE
Failing Test: persistent-volume-upgrade [sig-storage]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#67976]
# Failing Jobs
[sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master)
# Failing Tests
[persistent-volume-upgrade [sig-storage]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master/1440)
# Triage Results
[persistent-volume-upgrade [sig-storage]](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-master&test=persistent-volume-upgrade)

/sig storage
/kind failing-test
/priority critical-urgent
/milestone v1.12
/cc @tpepper @AishSundar @kubernetes/sig-storage-test-failures

**Comment by msau42** [comment]
Many of the upgrade tests are failing with:
```
    failed to get logs from pvc-tester-4pgvj for write-pod: an error on the server ("unknown") has prevented the request from succeeding (get pods pvc-tester-4pgvj)
not to have occurred
```

This sounds like a bigger system failure.

**Comment by saad-ali** [comment]
@mohammedzee1000 Could you assign to test environment owner to investigate potential upgrade testing env issue.

**Comment by guineveresaenger** [comment]
This test is not currently failing. Closing this until further notice.
/close
