### ISSUE TITLE
Document kubectl syntax/usage/output conventions

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#6797]
I'm thinking of something like api-conventions.md, but for kubectl. It should at least cover the general command patterns, common arguments, and typical output.

Example topics to cover:
* Ways in which objects can be specified
* Commands are lowercase, w/ dashes for multiple words
* Resource kinds are all lowercase rather than camelcase, no hyphens
* The difference between get and describe
* Command-line flags corresponding to API fields should accept API enums exactly (e.g., --restart=Always)

If not too long, the overall kubectl.md could be a reasonable place to put the text.

cc @smarterclayton @jlowdermilk @ghodss

**Comment by nikhiljindal** [comment]
Another thing that we had discussed:
* Explicitly specify the api-version flag when using -o template, so that the command does not break when the default api version used by kubectl is updated.

**Comment by ghodss** [comment]
+1. In theory it could be expanded to cli-conventions.md, though I think kubectl operates quite differently than most of our other daemons. But it still may be wise for it to cover other command-line tools besides kubectl, like simplegen, podex, etc.

**Comment by bgrant0607** [comment]
VERB and VERB NOUN, not NOUN VERB. We may need to reconsider kubectl config.

**Comment by smarterclayton** [comment]
That being said, if you have sets of functionality that are distinct, sometimes it's nice to keep them separate (treat kubectl config like kubectl-config).

**Comment by bgrant0607** [comment]
Also output conventions: https://github.com/GoogleCloudPlatform/kubernetes/issues/7843#issuecomment-101365459

**Comment by bgrant0607** [comment]
More output conventions: https://github.com/GoogleCloudPlatform/kubernetes/issues/3894#issuecomment-77238672

**Comment by bgrant0607** [comment]
More output conventions: #8476

**Comment by bgrant0607** [comment]
Only use templates when writing reusable scripts. Human output formats may change.

**Comment by bgrant0607** [comment]
Errors output to stderr rather than (or in addition to) glog: #9357

**Comment by bgrant0607** [comment]
cc @JanetKuo

**Comment by bgrant0607** [comment]
More output conventions:
* the ability to specify labels as columns using `-L` #9876
* AGE of every object #10008
* `-o wide` for wide get output #10491
* human-understandable output from mutations (create/update/delete) by default: resource/name verbed #5906
* `-o name` for mutations to output just resource/name #5906

**Comment by bgrant0607** [comment]
We also want conventions for:
1. Showing what a mutation would do, without doing it, aka --dry-run
2. Showing what a mutation did, by automatically getting the current object
3. Printing or describing (#4471) a local object rather than one fetched from the server

All of these should be orthogonal to output format (default, wide, json, yaml, template).
