### ISSUE TITLE
CSI kubelet driver registration - Plugins Watcher GA considerations 

### ISSUE THREAD

**Issue by verult** [kubernetes/kubernetes#67972]
/kind feature

**Reconsider driver map locking after plugin unregistration is implemented**:
Depending on the implementation details of kubelet plugin unregistration (https://github.com/kubernetes/kubernetes/issues/64637), the current way of locking the registered driver map inside the plugin registration callback function [here](https://github.com/kubernetes/kubernetes/blob/a2f4f585afba0c57b432772c6358cb1b2727fb5f/pkg/volume/csi/csi_plugin.go#L89) may result in race conditions.

Investigate once unregistration is implemented.

**Initialization callback**:
Consider proposing to Plugins Watcher an initialization function, called on kubelet initialization. CSI driver registration can then scan for CSI registration sockets that are already available on the host machine and register them early. Without this feature, drivers that previously exist on the machine could be left undetected.

**Retry node info updates on error**:
Because of the plugins watcher design, driver detection is edge-triggered rather than level-triggered. In a level-triggered system, the controller would continuously reconcile with driver state to detect the correct state. In our edge-triggered system, we have to continuously retry the node info update if there's an error, to prevent a trigger signal being lost. Currently this behavior is missing.
One consequence is that if the `CSINodeInfo` CRD is not installed before driver installation, the `CSINodeInfo` object will *never* contain information for this particular driver, even if another driver gets installed after the CRD is created.

/sig storage
/assign

**Comment by davidz627** [comment]
@verult this issue is still very relevant, could you rework it to reference the new `CSINode` API Object instead. And reword the title so it references plugin watcher reconciliation (it's hard to tell what the issue is about from the title currently).

**Comment by verult** [comment]
All concerns are handled in the latest iteration of the plugin manager!

*Reconsider driver map locking after plugin unregistration is implemented:* Synchronization is now implemented in the CSI driver store abstraction with a RWLock, which resolves the concern. https://github.com/kubernetes/kubernetes/blob/d6b42f0049f8e4cf0ce3a726a4d48077bcc4715a/pkg/volume/csi/csi_drivers_store.go#L33

*Initialization callback:* Existing sockets are added into the plugin manager's desired state through the populator: https://github.com/kubernetes/kubernetes/blob/d6b42f0049f8e4cf0ce3a726a4d48077bcc4715a/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L147

*Retry node info updates on error:* Retry is implemented in plugin manager.
