### ISSUE TITLE
Pod & Container Lifecycle

### ISSUE THREAD

**Issue by dtornow** [kubernetes/kubernetes#67973]
Hello,

**Problem:**

Insufficient information about the pod lifecycle and how a pod's state maps to the pod's containers' states. Specifically the documentation states that "The phase of a Pod is a simple, high-level summary of where the Pod is in its lifecycle. The phase is not intended to be a comprehensive rollup of observations of Container or Pod state, nor is it intended to be a comprehensive state machine" [Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase)

**Proposed Solution:**

Specify the pod lifecycle and how a pod's state maps to the pod's containers' states, exit codes, and liveness probes.

**The following statements reflect my understanding of the pod's lifecycle, please do post comments and corrections as appropriate.** 

### Pod Lifecycle

![image](https://user-images.githubusercontent.com/580718/43996583-b2690758-9d7a-11e8-88ff-37695d64972d.png)

### Container Lifecycle

![image](https://user-images.githubusercontent.com/580718/44106187-c62d6dc6-9fa8-11e8-9914-4fafb6b5f4c6.png)

The Kubelet determines a pod's state exclusively based on the pod's 

- init containers'
  - state
  - exit code
- main containers'
  - state
  - exit code
  - liveness probe

### Pending

When a Pod is in the state Pending then 
- none of the Pod's Init Containers are in the state Terminated[Failure]
- all of the Pod's Main Containers are in the state Waiting

```
fact {
    all p : Pod | 
        p.status = Pending <=> {
            // Init Container
            no  c : p.init_containers | c.status = Terminated_Failure
            // Main Container
            all c : p.main_containers | c.status = Waiting
        }
}
```

### Running

When a Pod is in the state Running then
- all of the Pod's Init Containers are in the state Terminated[Success]
- at least one of the Pod's Main Containers is in the state Running
- none of the Pod's Main Containers are in the state Terminated[Failure]
- none of the Pod's Main Containers are dead

```
fact {
    all p : Pod | 
        p.status = Running <=> {
            // Init Containers
            all  c : p.init_containers | c.status = Terminated_Success 
            // Main Containers
            some c : p.main_containers | c.status = Running 
            no   c : p.main_containers | c.status = Terminated_Failure
            no   c : p.main_containers | isDead[c]			
        }
}
```

### Success

When a Pod is in the state Success then
- all of the Pod's Init Containers are in the state Terminated[Success] 
- all of the Pod's Main Containers are in the state Terminated[Success] 
- all of the Pod's Main Containers were live

```
fact {
    all p : Pod | 
        p.status = Success <=> {
            // Init Containers
            all c : p.init_containers | c.status = Terminated_Success 
            // Main Containers
            all c : p.main_containers | c.status = Terminated_Success 
            all c : p.main_containers | isLive[c]
        }
}
```

### Failure

When a Pod id in the state Failure then 
- all of the Pods Init Container are in the state Terminated
- all of the Pod's Main Containers are in the state Terminated
- and
    - at least one of the Pod's Init Containers is in the in the state Terminated[Failure] *or*
    - at least one of the Pod's Main Containers is in the in the state Terminated[Failure] *or*
    - at least one of the Pod's Main Containers was dead

```
fact {
    all p : Pod |
        p.status = Failure <=> {
            // Init Containers
            all c : p.init_containers | c.status = Terminated  
            // Main Containers
            all c : p.main_containers | c.status = Terminated
            // Init & Main Container
            (some c : p.init_containers | c.status = Terminated_Failure) or (some c : p.main_containers | c.status = Terminated_Failure) or (some c : p.main_containers | isDead[c]) 
        }
}
```

### Caveats

Note that the *current* state is trailing the *genuine* state, since Kubernetes in general and the Kubelet in special use polling.

![image](https://user-images.githubusercontent.com/580718/44106327-34611bf8-9fa9-11e8-8a88-fe44c4fe3413.png)

```
current state at t: Pending, genuine state at t: Running
```

Is this an accurate reflection of Kubernetes' behavior?

**Comment by neolit123** [comment]
@dtornow  thank you for your proposal for expanding the details on pod and container lifecycle.
ideally a PR should be filed against the `kubernetes/website` repository.

@kubernetes/sig-node-proposals 
/kind documentation
/sig node
