### ISSUE TITLE
Pod Level Security

### ISSUE THREAD

**Issue by viveknangal** [kubernetes/kubernetes#67993]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Information Request

**What happened**:
What to understand how do we achieve pod level security in K8S, e.g. I want only Pod A talks to Pod B but not to Pod C. What is the expectation on this ?

**Comment by CaoShuFeng** [comment]
Maybe network policy would help:
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by neolit123** [comment]
^ the above link is the correct documentation for this.

you can also read this tutorial.
https://docs.giantswarm.io/guides/limiting-pod-communication-with-network-policies/

/close
