### ISSUE TITLE
The glusterfs provisioner creates and deletes gluster volumes if the endpoint creation fails due to length restrictions

### ISSUE THREAD

**Issue by obnoxxx** [kubernetes/kubernetes#67999]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When the glusterfs provisioner is asked to create a PV with a name of more than 45 characters, the endpoint creation fails due to the overal length of the constructed endpoint name being more than 63 characters. See issues #53939 and #56379. This leads to the overall PVC request failing, but the provisioner has at this point already created a gluster volume in the backend, and the failure to create the endpoint leads to a rollback that deletes the volume. So the volume is not leaked, but it still takes time and energy to do this creation and deletion. Also, previously this volume churn would have side effects on gluster itself, which is now removed or at least reduced.

**What you expected to happen**:

Failure to create the endpoint should not create and delete a gluster volume. Ideally, the gluster volume should not have been created in the first place.

**How to reproduce it (as minimally and precisely as possible)**:

* Set up a storage class with the glusterfs provisioner
* try a pvc create with a volume name of more than 45 characters
* the PVC creation fails due to the endpoint, but a gluster volume has been created and deleted again as you can see from gluster logs

(See issue #56379 for more details).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (also recent released versions)
- Cloud provider or hardware configuration: any
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`): any
- Install tools: kubeadm, or others
- Others: -

**Comment by obnoxxx** [comment]
@humblec @jsafrane @childsb FYI

**Comment by obnoxxx** [comment]
@humblec if you agree with the statement of the issue and proposed solution, I can try to cut a first PR to fix it.

**Comment by humblec** [comment]
@obnoxxx unfrotunately I dont agree. Do we have proof that, there is a leak or dangling gluster volume in this workflow ? because if endpoint creation failed, provisioner delete the volume. More or less, https://bugzilla.redhat.com/show_bug.cgi?id=1622493#c0 says deletion is attempted.

**Comment by obnoxxx** [comment]
@humblec ah... I somehow missed the deleting part, thanks for pointing it out... Still the churn of creating and deleting the volume should be prevented, imho. So we could just fail early if the length of the endpoint name would be more than 63 characters. Do you agree to that part? If yes, I can modify the issue description.

**Comment by obnoxxx** [comment]
Somehow I also failed to spot the rollback code in the provisioner. Now I see it. Embarrassing. :-)

Still could we fail early to prevent all the time and effort (and possible side effects) of creating and deleting backend volumes?

**Comment by humblec** [comment]
@obnoxxx there were more than one solution or options comes to mind while I wrote https://bugzilla.redhat.com/show_bug.cgi?id=1622493#c6 or said, I will repush the disucssion or PR :). I will summarize the options or thoughts here: Give me some time :)

**Comment by obnoxxx** [comment]
@humblec I think the other issues at least were about allowing longer volume names. This issue is different in that it wants to prevent the creation (and deletion) of volumes if we can already know that we will need to roll back. So I think this is independent. Let's not club them together. I fully agree with the statement that the original PR was not the right solution, so imho no need to reopen that PR. The discussion for the other topic, sure!

**Comment by humblec** [comment]
JFR:  https://github.com/kubernetes/kubernetes/pull/56380

**Comment by humblec** [comment]
@obnoxxx @jsafrane I was thinking about a solution [1] to lift this limitation and to ensure backward compatibility of admin tools/utilities which filter these ep/svcs. The backward compatibility was one of the main reason for denying the attempts till now to enhance this .

afaict, the WIP solution [1] does address below:

*) It does not break the backward compatibility.
*) Allow admins to create PVCs of character length 63
*) Switch on/off custom ep/svc name.
*) It deny the unwanted creation/deletion chain early as mentioned in this issue description.


[1]
https://github.com/humblec/kubernetes/commit/91d1c3081071fe145004d2924982a046051095e5

Please share your thoughts if any.

**Comment by obnoxxx** [comment]
@humblec, let's not club two actually independent fixes together.

* One is avoiding the creation and deletion of volumes in gluster when we can already know the overall PVC creation would fail, e.g. because the PV name is longer then 45 chars. (this issue)
* The other is lifting the limit of 45 characters to higher numbers (#56379 and  #53939).

Let's fix separate issue separately. I volunteered to provide a fix for this issue in https://github.com/kubernetes/kubernetes/issues/67999#issuecomment-416904735 .

**Comment by obnoxxx** [comment]
I would also try to do the check for the length a little differently, so that we don't explicitly test against a 45, which is kind of arbitrary and bad. Will send a patch...

**Comment by humblec** [comment]
@obnoxxx well, eventhough my preference is for one solution, I dont want to stop you :). Go ahead with the first PR and assign to me .

**Comment by obnoxxx** [comment]
@humblec first cut a dedicated fix for this in PR#68343

**Comment by obnoxxx** [comment]
@humblec writes
> @obnoxxx well, eventhough my preference is for one solution, 

Please explain why you prefer one patch to solve two different problems if we can separate it into two changes (where the second one would build upon the first). I would like to understand. :-)

**Comment by JannikZed** [comment]
hey there, I came across this issue, as I'm facing exactly the described problem with the too long pvc name. Unfortunately, I don't get all the discussions in here and I don't know if and how this issue got solved. I'm using kubernetes 1.13 with rancher 2.2.4 with the following issue:
``` 
Failed to provision volume with StorageClass "glusterfs-storage": failed to create volume: failed to create endpoint/service cattle-prometheus/glusterfs-dynamic-81821b53-8a25-11e9-a567-960000278b4c: failed to create endpoint: Endpoints "glusterfs-dynamic-81821b53-8a25-11e9-a567-960000278b4c" is invalid: metadata.labels: Invalid value: "prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0": must be no more than 63 characters
```
