### ISSUE TITLE
sig-apps tests keep failing when run pull-kubernetes-e2e-gce test

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/kubernetes#68006]
Tests about ReplicaSet and StatefulSet keep failing today.
Link: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63011/pull-kubernetes-e2e-gce/50637/

/sig apps
/sig testing

**Comment by NickrenREN** [comment]
Hit it in this PR too: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67982/pull-kubernetes-e2e-gce/50655/

**Comment by mortent** [comment]
The tests seems to pass pretty consistently now. I suggest we close this one and revisit this if we see flakiness again.
