### ISSUE TITLE
HPA no longer works with adapters exposing Custom Metrics v1beta1 API

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/kubernetes#68011]
Merging https://github.com/kubernetes/kubernetes/pull/64097 has broken e2e tests: https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gci-gce-autoscaling-hpa. Based on the logs it seems that HPA can no longer retrieve custom metrics provided by adapter (it still works for external metrics though).

Quickly looking through the code it looks like #64097 updated https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/client/custom_metrics/client.go#L115 to use Custom Metrics v1beta2 API. Since v1beta2 is not backward compatible with v1beta1 and there is no fallback to old API, I suspect HPA will no longer work with any pre-existing adapter implementing v1beta1 API (like the stackdriver adapter we use in tests). 

If my suspicion is correct I think this would be a huge regression - all existing adapters will stop working in 1.12. As per https://kubernetes.io/docs/reference/using-api/deprecation-policy/ we can't just drop support for v1beta1 - we need to support it for 9 months / 3 releases after officially deprecating it.

/kind bug
/priority critical-urgent
/sig autoscaling

cc: @kubernetes/sig-autoscaling-bugs @mwielgus @DirectXMan12 @damemi @kawych @piosz

**Comment by DirectXMan12** [comment]
Yeah, I realized that yesterday.  Let's get fallback logic merged.

**Comment by DirectXMan12** [comment]
@damemi and I will get a fix up today

**Comment by DirectXMan12** [comment]
> If my suspicion is correct I think this would be a huge regression - all existing adapters will stop working in 1.12. As per https://kubernetes.io/docs/reference/using-api/deprecation-policy/ we can't just drop support for v1beta1 - we need to support it for 9 months / 3 releases after officially deprecating it.

Correct, I believe

**Comment by DirectXMan12** [comment]
Actually, we have conversions in place.  We just need to switch back to v1beta1.  No fallback need.

**Comment by losipiuk** [comment]
/reopen

It seems this issue is not fixed.
@krzysztof-jastrzebski  and I were debugging issue with HPA scaling based on custom-metrics, where metrics are exposed via v1beta1 api. 
It looks that conversion is not working properly. Here is what we are seeing.

* Pod (custom-metrics-adapter) is exposing metrics using v1beta1 API.
* Exposed metrics value is 200.
* HPA controller reads metrics and performs conversion but value is 0 after conversion.
* Therefore no scaling up occurs

While debugging we augmented `ConvertResultToVersion` method with logging:

```golang
func (c *MetricConverter) ConvertResultToVersion(res rest.Result, gv schema.GroupVersion) (runtime.Object, error) {
	glog.Infof("xxx  res = %v  gv = %v", res, gv)
	if err := res.Error(); err != nil {
		return nil, err
	}
 
	metricBytes, err := res.Raw()
	if err != nil {
		return nil, err
	}
	glog.Infof("xxx  metricBytes = %v", metricBytes)
	decoder := c.codecs.UniversalDecoder(MetricVersions...)
	rawMetricObj, err := runtime.Decode(decoder, metricBytes)
	glog.Infof("xxx  rawMetricObj = %v", rawMetricObj)
	if err != nil {
		return nil, err
	}
 
	metricObj, err := c.UnsafeConvertToVersionVia(rawMetricObj, gv)
	glog.Infof("xxx  metricObj = %v", metricObj)
	if err != nil {
		return nil, err
	}
	return metricObj, nil
```

Here is the logging output:
```
I0918 14:26:09.455318       1 converter.go:96] xxx  metricBytes = [107 56 115 0 10 48 10 29 99 117 115 116 111 109 46 109 101 116 114 105 99 115 46 107 56 115 46 105 111 47 118 49 98 101 116 97 49 18 15 77 101 116 114 105 99 86 97 108 117 101 76 105 115 116 18 154 1 10 78 10 72 47 97 112 105 115 47 99 117 115 116 111 109 46 109 101 116 114 105 99 115 46 107 56 115 46 105 111 47 118 49 98 101 116 97 49 47 110 97 109 101 115 112 97 99 101 115 47 102 97 115 116 45 115 99 97 108 105 110 103 47 112 111 100 115 47 37 50 65 47 81 80 83 18 0 26 0 18 72 10 48 10 3 80 111 100 18 12 102 97 115 116 45 115 99 97 108 105 110 103 26 8 114 99 45 122 102 120 122 108 34 0 42 11 47 95 95 105 110 116 101 114 110 97 108 50 0 58 0 18 3 81 80 83 26 8 8 129 150 132 221 5 16 0 42 5 10 3 50 48 48 26 0 34 0]
I0918 14:26:09.455434       1 converter.go:99] xxx  rawMetricObj = &MetricValueList{ListMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta{SelfLink:/apis/custom.metrics.k8s.io/v1beta1/namespaces/fast-scaling/pods/%2A/QPS,ResourceVersion:,Continue:,},Items:[{{ } {Pod fast-scaling rc-zfxzl  /__internal  } QPS 2018-09-18 14:26:09 +0000 UTC <nil> {{200 0} {<nil>} 200 DecimalSI} nil}],}
I0918 14:26:09.455534       1 converter.go:105] xxx  metricObj = &MetricValueList{ListMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta{SelfLink:/apis/custom.metrics.k8s.io/v1beta1/namespaces/fast-scaling/pods/%2A/QPS,ResourceVersion:,Continue:,},Items:[{{ } {      } {QPS nil} 0001-01-01 00:00:00 +0000 UTC <nil> {{0 0} {<nil>}  }}],}
I0918 14:26:14.453086       1 converter.go:87] xxx  res = {[107 56 115 0 10 48 10 29 99 117 115 116 111 109 46 109 101 116 114 105 99 115 46 107 56 115 46 105 111 47 118 49 98 101 116 97 49 18 15 77 101 116 114 105 99 86 97 108 117 101 76 105 115 116 18 154 1 10 78 10 72 47 97 112 105 115 47 99 117 115 116 111 109 46 109 101 116 114 105 99 115 46 107 56 115 46 105 111 47 118 49 98 101 116 97 49 47 110 97 109 101 115 112 97 99 101 115 47 102 97 115 116 45 115 99 97 108 105 110 103 47 112 111 100 115 47 37 50 65 47 81 80 83 18 0 26 0 18 72 10 48 10 3 80 111 100 18 12 102 97 115 116 45 115 99 97 108 105 110 103 26 8 114 99 45 122 102 120 122 108 34 0 42 11 47 95 95 105 110 116 101 114 110 97 108 50 0 58 0 18 3 81 80 83 26 8 8 134 150 132 221 5 16 0 42 5 10 3 50 48 48 26 0 34 0] application/vnd.kubernetes.protobuf <nil> 200 {0xc420522be0}}  gv = custom.metrics.k8s.io/v1beta2
```
Note that other fields are also set to default values for given type after conversion.

Even though we debugged using slightly different setup we are pretty sure that the same issue is reason for following test failures from https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gci-gke-autoscaling-hpa:
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) should scale down with Custom Metric of type Pod from Stackdriver [Feature:CustomMetricsAutoscaling]
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) should scale down with Custom Metric of type Pod from Stackdriver with Prometheus [Feature:CustomMetricsAutoscaling]
* [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) should scale up with two metrics of type Pod from Stackdriver [Feature:CustomMetricsAutoscaling]

**Comment by losipiuk** [comment]
assign @DirectXMan12

**Comment by damemi** [comment]
Could this be causing it? Looks like there were a number fields missed in the conversion functions: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/metrics/pkg/apis/custom_metrics/v1beta1/conversion.go#L38-L48

**Comment by losipiuk** [comment]
Looks promising. The `MetricValue.Metric` was converted correctly (at least `Name`, `Selector` is nil so hard to say). Other fields were not.
I don't know what is the proper way to mix auto-generated conversion code with hand written one. But maybe if you provide hand-written conversion function for `MetricValue` you have to handle all the fields.

**Comment by losipiuk** [comment]
Just a side note. If you will be fixing that could you add more verbose test coverage to `TestMetricConverter`? It would be nice to have different objects tested (v1beta1 <-> v1beta2) directly calling `UnsafeConvertToVersionVia` function.

**Comment by losipiuk** [comment]
I added one testcase which shows failing scenario:
```golang
			expected: &cmv1beta2.MetricValueList{
				Items: []cmv1beta2.MetricValue{
					{
						Value: resource.MustParse("200"),
					},
				},
			},
```

**Comment by losipiuk** [comment]
The first 2 pass. But the last one fails with `200` being converted to `0`

**Comment by damemi** [comment]
@losipiuk in your code it looks like the first 2 are converting `MetricListOptions` while the 3rd is converting `MetricValueList`. Would you mind modifying the first 2 to still check `internal -> versionXX` but with a `MetricValueList`?

**Comment by losipiuk** [comment]
I pasted it just for sake of showing the issue. It is not in commitable shape at all. As I mentioned earlier I think that we need more thorough coverage. And for sure more complete test objects. Not sure if we should test against internal API as it is somewhat implementation detail. But feel free to prove me wrong.

**Comment by damemi** [comment]
I've added these conversions in https://github.com/kubernetes/kubernetes/pull/68795

In testing locally using an HPA and custom adapter running v1beta1, I am able to see the metric value correctly parsed:
```
$ kubectl describe horizontalpodautoscaler.autoscaling/php-apache
Name:                  php-apache
Namespace:             default
Labels:                <none>
Annotations:           <none>
CreationTimestamp:     Tue, 18 Sep 2018 13:08:42 -0400
Reference:             Deployment/php-apache
Metrics:               ( current / target )
  "mymetric" on pods:  50 / 50
Min replicas:          1
Max replicas:          10
Deployment pods:       1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from pods metric mymetric
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>
```

(opposed to the current version, which parses to 0):
```
$ kubectl describe horizontalpodautoscaler.autoscaling/php-apache
Name:                  php-apache
Namespace:             default
Labels:                <none>
Annotations:           <none>
CreationTimestamp:     Tue, 18 Sep 2018 13:33:04 -0400
Reference:             Deployment/php-apache
Metrics:               ( current / target )
  "mymetric" on pods:  0 / 50
Min replicas:          1
Max replicas:          10
Deployment pods:       1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from pods metric mymetric
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>
```

While I am limited in my access to run the Stackdriver tests, we do have improvements to the custom metrics tests in the works (see https://github.com/kubernetes/kubernetes/pull/62351), which should allow blocking e2e tests using a generic custom adapter but is ultimately dependent on working out the bugs in HPA we've introduced first.

Please give my fix pr a review!
