### ISSUE TITLE
Fix golint failures

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#68026]
Anyone itching to understand the code and try fixing things in Kubernetes, please help fixing the lint failures

Step 1: Remove one or two packages (related packages) from the list in - https://github.com/kubernetes/kubernetes/blame/master/hack/.golint_failures (note: do not change generated files, the name of defaulting functions, or the name of conversion functions... packages failing linting due to issues in those files will need to be left alone)
Step 2: Run `hack/verify-golint.sh` and look at the logged errors
Step 3: Fix the code to ensure that `hack/verify-golint.sh` runs cleanly.
Step 4: Run `hack/update-bazel.sh` and `hack/update-gofmt.sh` to make sure we fix any problems with gofmt or bazel.
Step 5: File a PR with the change
Step 6: Go to step #1 :)

Please use the tracking spreadsheet [here](https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0) For everyone who is going to contribute, 
- please append the packages you picked at the end.
- For existing contributor, please make sure this list is update to date

**Comment by fengzixu** [comment]
@dims  Hey, I would like to resolve this issue. Could you assign it to me ?

**Comment by dims** [comment]
@fengzixu there are a lot of packages so there will be many people working on this. Also we cannot assign issue to folks who are not in the github org for kubernetes. please feel free to pick up a few packages like i mentioned and file a PR.

**Comment by fengzixu** [comment]
OK. I see. I will probably pick up some failures to fix.

**Comment by fengzixu** [comment]
Hi dims. @dims Should i submit my PR before i remove one or two packages (related packages) from the list in - https://github.com/kubernetes/kubernetes/blame/master/hack/.golint_failures ？ Or I first remove the package from list, then I fix the issue and submit a PR?

**Comment by dims** [comment]
@fengzixu in your PR, you will have both the fixes to packages and some lines removed from /.golint_failures

**Comment by dims** [comment]
@fengzixu 

- Say your GOPATH looks like this `GOPATH=/Users/dims/go` 
- Your kubernetes directory should be `/Users/dims/go/src/k8s.io/kubernetes` (`$GOPATH/src/k8s.io/kubernetes`)
- cd to `/Users/dims/go/src/k8s.io/kubernetes` and then run `hack/verify-golint.sh` from that directory.

**Comment by fengzixu** [comment]
@dims I revised some errors about golint. Request review

**Comment by mathspanda** [comment]
Is it necessary to obey all rules in golint? Rules in golint are set in stone. Maybe using gometalinter to ignore some specific errors is better? @dims

**Comment by fengzixu** [comment]
@dims I revise some erros about golint in some packages. Please review it. https://github.com/kubernetes/kubernetes/pull/68113

**Comment by dims** [comment]
@mathspanda which errors would you like to ignore? if you can open a new issue with the list of errors to ignore (and proposing gometalinter), we can get some opinions there from others in the community.

**Comment by sayanarijit** [comment]
Let me take the kubectl cmd part...

**Comment by sayanarijit** [comment]
Can someone please review and let me know if I am doing it right? [#68176](https://github.com/kubernetes/kubernetes/pull/68176)

**Comment by saravanan30erd** [comment]
I ll work on below packages,

cmd/hyperkube
cmd/kube-apiserver/app
cmd/kube-controller-manager/app
cmd/kube-proxy/app
cmd/kubeadm/app
cmd/kubeadm/app/apis/kubeadm/v1alpha2
cmd/kubeadm/app/apis/kubeadm/v1alpha3
cmd/kubeadm/app/util/config
cmd/kubeadm/app/util/system
cmd/kubelet/app
cmd/kubelet/app/options
cmd/kubemark

**Comment by yue9944882** [comment]
we get 800-ish pkgs left to fix. my concern is that if we the fix them package by package, then such pulls will be flooding the repo. can't we possibly make it in larger pulls? the larger the better?

**Comment by dims** [comment]
@yue9944882 +1 to slightly larger pulls with related packages. if allow too large then the reviewers will not be able to do a thorough review. we should spread the load among multiple reviewers. (if we allow a really large pull, we will end up with top level reviewers who will face the burden and the PR(s) will just stagnate)

**Comment by yue9944882** [comment]
> if we allow a really large pull, we will end up with top level reviewers who will face the burden and the PR(s) will just stagnate

oh good point. we could put one pkg's change into one commit, and merge all changes under one `OWNER` area into one pull so that it wont spread the load. wdyt? for each pull, we can have hundred-ish lines of change. but it will still be 30~50 pulls i guess? good news is that we can take our time to deal with it, at least before 1.12 😉

**Comment by dims** [comment]
@yue9944882 sounds great! please feel free to help make it happen :)

**Comment by jmsaucier** [comment]
@dims I'm looking at fixing pkg/proxy, and I think I see what @mathspanda was talking about ignoring some rules. 

proxy.ProxyProvider is being suggested because golint is saying that it stutters. In that example, I think it's okay renaming it to proxy.Provider, but I could see an example where you would want to keep the stutter if the package that it's declared in uses it heavily.

**Comment by dims** [comment]
@jmsaucier sure thing, feel free to propose a PR for switching to gometalinter independently of other patches. We can work through that there.

**Comment by leakingtapan** [comment]
@dims I sent the pull request to fix pkg/volume/aws_ebs

**Comment by tylerauerbeck** [comment]
I've fixed a few of these, but get the following error when I try to run `update-bazel.sh`:

```
unable to build vendorer: open /Users/tylerauerbeck/workspace/go/src/k8s.io/kubernetes/hack/.kazelcfg.json: no such file or directory
```

Are there any instructions on what I need to setup in order to resolve this?

**Comment by tanshanshan** [comment]
you can find this file in 
https://github.com/kubernetes/kubernetes/blob/master/build/root/.kazelcfg.json
@tylerauerbeck

**Comment by PrasadG193** [comment]
@dims I have raised a PR to fix golint errors in pkg/api

**Comment by Pingan2017** [comment]
@dims  I have fixed some pkgs under /pkg/kubelet
- pkg/kubelet/images
- pkg/kubelet/kuberuntime		
- pkg/kubelet/leaky
- pkg/kubelet/pleg

**Comment by sjgllghr** [comment]
@dims I submitted a pull request for golint errors in pkg/security/

**Comment by linyouchong** [comment]
@dims I will work on all the packages related to pkg/registry/*

**Comment by tanshanshan** [comment]
fix golint issues for staging/src/k8s.io/apimachinery and staging/src/k8s.io/apiserver in #68541 

thanks.

**Comment by bruceauyeung** [comment]
fix golint errors in package cmd/kubeadm/app, since the codes under cmd/kubeadm/app/apis/kubeadm/v1alpha2 and cmd/kubeadm/app/apis/kubeadm/v1alpha3 are auto-generated, i keep them untouched.
https://github.com/kubernetes/kubernetes/pull/68595

**Comment by tianshapjq** [comment]
I am working on some packages under pkg/kubelet, anyone interested in this plz leave messages for me :)
#68599

**Comment by tanshanshan** [comment]
fix golint for
pkg/util/dbus
pkg/util/labels
pkg/util/node
pkg/util/strings
pkg/util/workqueue/prometheus

 #68544

**Comment by jonfriesen** [comment]
PR #68582 fixes golint in pkg/probe

**Comment by leakingtapan** [comment]
@dims should we have a checklist as part of the issue summary saying what is in progress and what is done? Since this issue is getting long, this will make new contributors to pick up issues easier.

**Comment by leakingtapan** [comment]
@dims Created a [spreadsheet](https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit?usp=sharing) with all the package that have on going PRs. Maybe you can add this to the summary. 
* For everyone who is going to contribute, please append the packages you picked at the end. 
* For existing contributor, please make sure this list is update to date

**Comment by dims** [comment]
Thanks @leakingtapan updated the spread sheet

**Comment by PrasadG193** [comment]
Raised PR to fix golint issues in: 
- pkg/controller/clusterroleaggregation
- pkg/controller/cronjob
- pkg/controller/daemon
- pkg/controller/deployment
- pkg/controller/deployment/util
- pkg/controller/disruption
- pkg/controller/endpoint

**Comment by leakingtapan** [comment]
This issue is close in accident by #68113. @dims could you reopen it?

**Comment by ifosch** [comment]
I found a problem trying to fix golint messages for `cmd/cloud-controller-manager/app/apis/config/v1alpha1`.
Golint complaints on `defaults.go`'s `SetDefaults_CloudControllerManagerConfiguration` function because of the snake case. When I try to fix it, `make test` fails because it is being used in a code generated file. If I clean generated files, tests pass, but the generated file is not invoking it anymore.
I failed to find the generator definition using this so I could change the `SetDefaults_` hook to just `SetDefaults`. Also I'm not sure if this is wanted.
I also found other packages in `.golint_failures` also probably affected by this.
I read somewhere about replacing golint with gometalinter, which would allow to define directives in code to omit certain rules.
I would consider to have a second exclusion file for golint with these cases, to be updated if move to gometalinter is finally done. This would make this issue completion more feasible.
Meanwhile, I'll move onto fixing golint messages for other packages, until this discussion gets cleared.

**Comment by chrischdi** [comment]
I also found a problem fixing `pkg/utils/labels`.
A test fails because the directory is marked as readonly (see tests @ [PR #69761](https://github.com/kubernetes/kubernetes/pull/69761#issuecomment-429618839)

**Comment by jonfriesen** [comment]
@war-turtle the failures are still present in https://github.com/kubernetes/kubernetes/blame/master/hack/.golint_failures

there are details in the first message on how to claim + solve issues :)

**Comment by war-turtle** [comment]
Sorry I misunderstood the issue

**Comment by eloyekunle** [comment]
I'm working on this package: `staging/src/k8s.io/kube-aggregator`

**Comment by SataQiu** [comment]
#74505 

- pkg/apis/admission/v1beta1
- pkg/apis/authentication/v1beta1
- pkg/apis/authorization/v1beta1
- pkg/apis/coordination/v1
- pkg/apis/coordination/v1beta1
- pkg/apis/imagepolicy/v1alpha1
- pkg/apis/scheduling/v1alpha1
- pkg/apis/scheduling/v1beta1
- pkg/apis/settings/v1alpha1
- pkg/apis/storage/v1alpha1

**Comment by SataQiu** [comment]
#74510
* pkg/cloudprovider/providers/vsphere/vclib
* pkg/kubelet/apis/deviceplugin/v1alpha
* pkg/kubelet/apis/pluginregistration/v1alpha1
* pkg/kubelet/apis/pluginregistration/v1beta1

**Comment by SataQiu** [comment]
#74574 
```
* pkg/registry/apps/daemonset
* pkg/registry/apps/deployment
* pkg/registry/apps/statefulset
* pkg/registry/autoscaling/horizontalpodautoscaler
* pkg/registry/batch/cronjob
* pkg/registry/core/resourcequota
* pkg/registry/policy/poddisruptionbudget
```

**Comment by SataQiu** [comment]
#74582
```
* plugin/pkg/admission/eventratelimit/apis/eventratelimit
* plugin/pkg/admission/podtolerationrestriction/apis/podtolerationrestriction
* plugin/pkg/admission/security
```

**Comment by SataQiu** [comment]
#74642 

```
* test/integration/evictions
* test/integration/replicaset
* test/integration/replicationcontroller
```

**Comment by obitech** [comment]
#75303:

```
pkg/kubelet/pod
pkg/kubelet/metrics
pkg/kubelet/configmap
pkg/kubelet/config
```

**Comment by anuragprafulla** [comment]
I'm looking at the pkg/registry/*, all those which are left. I expect to give an update on what all is fixed in the next 24-48 hours.

**Comment by jonfriesen** [comment]
hi @anuragprafulla 

there is a google sheet that is a bit outdated, maybe you can update that? https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0

**Comment by anuragprafulla** [comment]
hi @jonfriesen
I seem to only have view access for the sheet. Can't edit.

**Comment by leakingtapan** [comment]
@anuragprafulla I fixed the permission. try it again

**Comment by SataQiu** [comment]
#75584 
    pkg/apis/auditregistration/v1alpha1
    pkg/apis/authentication
    pkg/apis/coordination

**Comment by jonfriesen** [comment]
hi @dims I think this issue was closed prematurely by #73255 (using fixes #issue in commit)

**Comment by jlucktay** [comment]
I'll put in a PR shortly for the `cmd/cloud-controller-manager/app/apis/config/v1alpha1` package

**Comment by jlucktay** [comment]
Looking at `cmd/kube-controller-manager/app` next

**Comment by jonfriesen** [comment]
hi @jlucktay thanks! there is a spreadsheet here that tracks the progress on fixing these issues, consider adding the packages you're work on there so we can keep everything organized :+1: 
https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0

**Comment by jlucktay** [comment]
Starting on `pkg/auth/authorizer/abac` now

**Comment by jlucktay** [comment]
> hi @jlucktay thanks! there is a spreadsheet here that tracks the progress on fixing these issues, consider adding the packages you're work on there so we can keep everything organized 👍
> https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0

I did indeed see the Google Sheet link (thank you @jonfriesen!) and [hacked something together](https://github.com/jlucktay/kube-golint-todo) to take it a little further 😬

**Comment by SataQiu** [comment]
#75710 
- test/e2e

**Comment by SataQiu** [comment]
#75713
- test/e2e_node/builder

**Comment by anuragprafulla** [comment]
[75716](https://github.com/kubernetes/kubernetes/pull/75716)

- pkg/registry/admissionregistration/mutatingwebhookconfiguration/storage
- pkg/registry/admissionregistration/rest
- pkg/registry/admissionregistration/validatingwebhookconfiguration/storage
- pkg/registry/apps/daemonset/storage

**Comment by baasbank** [comment]
@dims Hi. I opened a PR -> https://github.com/kubernetes/kubernetes/pull/76771

**Comment by daminisatya** [comment]
Working on 

```
pkg/controller/garbagecollector
pkg/controller/garbagecollector/config/v1alpha1
```
Will open a PR soon. 

@dims

**Comment by jlucktay** [comment]
Starting on `test/utils` and should have a PR soon

**Comment by guineveresaenger** [comment]
I keep getting this golint verify error on `master` and was wondering if others saw it:
```
hack/verify-golint.sh
installing golint from vendor
Errors from golint:
test/integration/apiserver/admissionwebhook/broken_webhook_test.go:153:20: should omit type admissionregistrationv1beta1.FailurePolicyType from declaration of var failurePolicy; it will be inferred from the right-hand side

Please review the above warnings. You can test via "golint" and commit the result.
If the above warnings do not make sense, you can exempt this package from golint
checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
```
But when I added that package to the golint failures in my PR, my reviewer said it isn't necessary? What does that mean? What did I miss? Should I use a different kind of verify?
cf: https://github.com/kubernetes/kubernetes/pull/77033#discussion_r278377666

**Comment by dims** [comment]
@guineveresaenger looks like the disconnect is because that problem does not show up in the version of `golint` we use in the CI.

please see https://github.com/kubernetes/kubernetes/blob/master/hack/verify-golint.sh#L33-L34

**Comment by guineveresaenger** [comment]
Still confused: is that not the golint version I ran? it installs from vendor and uses that I think?

**Comment by dims** [comment]
i installed from https://github.com/golang/lint and i still don't see the problem, can you please check what version of golint you have?

**Comment by guineveresaenger** [comment]
I'm confused why I wouldn't be using the vendored version? how would that get out of sync?

**Comment by guineveresaenger** [comment]
Note: I am reserving `pkg/apis/apps` for a KubeCon Contributor Workshop demonstration. It is noted in the spreadsheet.

**Comment by andrewsykim** [comment]
@guineveresaenger I think `pkg/apis/apps` may not be ideal cause there's a lot of generated files there. What do you think about reserving `test/*` for the KubeCON Contributor Workshop?

**Comment by SataQiu** [comment]
#77380 
    pkg/apis/scheduling
    pkg/apis/storage/util
    pkg/apis/storage/v1beta1/util
    pkg/apis/storage/v1/util

**Comment by salman-bhai** [comment]
Hi I am a new contributor here, I'd like to contribute and make changes to the following file/s. I have marked it as WIP in the Google Sheet. Can someone let me know if I have to do anything else before I start working on this PR?
```
cmd/kubeadm/app
```

**Comment by salman-bhai** [comment]
Umm so there's an issue where Golint tells that underscore shouldn't be allowed. Here's a log of the go-lint warnings:
```
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:25:1: exported function Convert_kubeadm_InitConfiguration_To_v1beta1_InitConfiguration should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:25:6: don't use underscores in Go names; func Convert_kubeadm_InitConfiguration_To_v1beta1_InitConfiguration should be ConvertKubeadmInitConfigurationToV1beta1InitConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:37:1: exported function Convert_kubeadm_JoinControlPlane_To_v1beta1_JoinControlPlane should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:37:6: don't use underscores in Go names; func Convert_kubeadm_JoinControlPlane_To_v1beta1_JoinControlPlane should be ConvertKubeadmJoinControlPlaneToV1beta1JoinControlPlane
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:49:1: exported function Convert_kubeadm_NodeRegistrationOptions_To_v1beta1_NodeRegistrationOptions should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:49:6: don't use underscores in Go names; func Convert_kubeadm_NodeRegistrationOptions_To_v1beta1_NodeRegistrationOptions should be ConvertKubeadmNodeRegistrationOptionsToV1beta1NodeRegistrationOptions
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:69:6: don't use underscores in Go names; func SetDefaults_InitConfiguration should be SetDefaultsInitConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:76:6: don't use underscores in Go names; func SetDefaults_ClusterConfiguration should be SetDefaultsClusterConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:107:6: don't use underscores in Go names; func SetDefaults_APIServer should be SetDefaultsAPIServer
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:116:6: don't use underscores in Go names; func SetDefaults_DNS should be SetDefaultsDNS
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:123:6: don't use underscores in Go names; func SetDefaults_Etcd should be SetDefaultsEtcd
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:135:6: don't use underscores in Go names; func SetDefaults_JoinConfiguration should be SetDefaultsJoinConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:144:1: exported function SetDefaults_JoinControlPlane should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:144:6: don't use underscores in Go names; func SetDefaults_JoinControlPlane should be SetDefaultsJoinControlPlane
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:151:6: don't use underscores in Go names; func SetDefaults_Discovery should be SetDefaultsDiscovery
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:168:6: don't use underscores in Go names; func SetDefaults_FileDiscovery should be SetDefaultsFileDiscovery
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:183:6: don't use underscores in Go names; func SetDefaults_BootstrapTokens should be SetDefaultsBootstrapTokens
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:195:6: don't use underscores in Go names; func SetDefaults_BootstrapToken should be SetDefaultsBootstrapToken
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:211:6: don't use underscores in Go names; func SetDefaults_APIEndpoint should be SetDefaultsAPIEndpoint
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults_unix.go:25:2: const DefaultUrlScheme should be DefaultURLScheme
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults_windows.go:25:2: const DefaultUrlScheme should be DefaultURLScheme
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/fields.go:29:17: should omit type metav1.Fields from declaration of var EmptyFields; it will be inferred from the right-hand side
```

**Comment by SataQiu** [comment]
Thanks @salman-bhai 
The following should not be modified, as they are designed like this for code generation.
```
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:25:1: exported function Convert_kubeadm_InitConfiguration_To_v1beta1_InitConfiguration should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:25:6: don't use underscores in Go names; func Convert_kubeadm_InitConfiguration_To_v1beta1_InitConfiguration should be ConvertKubeadmInitConfigurationToV1beta1InitConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:37:1: exported function Convert_kubeadm_JoinControlPlane_To_v1beta1_JoinControlPlane should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:37:6: don't use underscores in Go names; func Convert_kubeadm_JoinControlPlane_To_v1beta1_JoinControlPlane should be ConvertKubeadmJoinControlPlaneToV1beta1JoinControlPlane
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:49:1: exported function Convert_kubeadm_NodeRegistrationOptions_To_v1beta1_NodeRegistrationOptions should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/conversion.go:49:6: don't use underscores in Go names; func Convert_kubeadm_NodeRegistrationOptions_To_v1beta1_NodeRegistrationOptions should be ConvertKubeadmNodeRegistrationOptionsToV1beta1NodeRegistrationOptions
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:69:6: don't use underscores in Go names; func SetDefaults_InitConfiguration should be SetDefaultsInitConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:76:6: don't use underscores in Go names; func SetDefaults_ClusterConfiguration should be SetDefaultsClusterConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:107:6: don't use underscores in Go names; func SetDefaults_APIServer should be SetDefaultsAPIServer
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:116:6: don't use underscores in Go names; func SetDefaults_DNS should be SetDefaultsDNS
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:123:6: don't use underscores in Go names; func SetDefaults_Etcd should be SetDefaultsEtcd
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:135:6: don't use underscores in Go names; func SetDefaults_JoinConfiguration should be SetDefaultsJoinConfiguration
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:144:1: exported function SetDefaults_JoinControlPlane should have comment or be unexported
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:144:6: don't use underscores in Go names; func SetDefaults_JoinControlPlane should be SetDefaultsJoinControlPlane
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:151:6: don't use underscores in Go names; func SetDefaults_Discovery should be SetDefaultsDiscovery
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:168:6: don't use underscores in Go names; func SetDefaults_FileDiscovery should be SetDefaultsFileDiscovery
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:183:6: don't use underscores in Go names; func SetDefaults_BootstrapTokens should be SetDefaultsBootstrapTokens
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:195:6: don't use underscores in Go names; func SetDefaults_BootstrapToken should be SetDefaultsBootstrapToken
cmd/kubeadm/app/apis/kubeadm/v1beta1/defaults.go:211:6: don't use underscores in Go names; func SetDefaults_APIEndpoint should be SetDefaultsAPIEndpoint
```

**Comment by entro-pi** [comment]
I'd like to pick a package and do my first PR, is there a list of packages to be done? Or should I correlate with this issue thread?

Thanks in advance!

**Comment by dims** [comment]
@entro-pi please see step 1 (`hack/.golint_failures`) please scan other PRs linked to this issue as well just in case.

**Comment by entro-pi** [comment]
Will do. Thank you.

**Comment by PamelaKelly** [comment]
Hi there, I'm looking for a good first issue. I'll start taking a look at `staging/src/k8s.io/apimachinery/pkg/types` if that's ok? 
There doesn't seem to be anyone currently tracked as looking at it in the attached spreadsheet.

**Comment by entro-pi** [comment]
I've found a few others I'm actively looking at, you won't get any argument
from me.

**Comment by gkarthiks** [comment]
I am working on the iptables pkg. Updated in the google docs [here](https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0)

**Comment by Aresforchina** [comment]
@dims when I run `hack/verfiy-staticcheck` ,I found some errors as below:
`` IGNORE[*]: unbound variable ``
I have already set $GOPATH well

**Comment by Raman-Kumar** [comment]
I have problem running `hack/verify-golint.sh` in step 2
$ hack/verify-golint.sh

```
installing golint from vendor
can't load package: package k8s.io/kubernetes/vendor/golang.org/x/lint/golint: cannot find package "k8s.io/kubernetes/vendor/golang.org/x/lint/golint" in any of:
	/usr/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/lint/golint (from $GOROOT)
	/Users/ramankumar/go/src/k8s.io/kubernetes/vendor/golang.org/x/lint/golint (from $GOPATH)
!!! Error in hack/verify-golint.sh:38
  Error in hack/verify-golint.sh:38. 'go install k8s.io/kubernetes/vendor/golang.org/x/lint/golint' exited with status 1
Call stack:
  1: hack/verify-golint.sh:38 main(...)
Exiting with status 1
```

what should I do?

**Comment by shikanon** [comment]
> Anyone itching to understand the code and try fixing things in Kubernetes, please help fixing the lint failures
> 
> Step 1: Remove one or two packages (related packages) from the list in - https://github.com/kubernetes/kubernetes/blame/master/hack/.golint_failures
> Step 2: Run `hack/verify-golint.sh` and look at the logged errors
> Step 3: Fix the code to ensure that `hack/verify-golint.sh` runs cleanly.
> Step 4: Run `hack/update-bazel.sh` and `hack/update-gofmt.sh` to make sure we fix any problems with gofmt or bazel.
> Step 5: File a PR with the change
> Step 6: Go to step #1 :)
> 
> Please use the tracking spreadsheet [here](https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit#gid=0) For everyone who is going to contribute,
> 
> * please append the packages you picked at the end.
> * For existing contributor, please make sure this list is update to date

@dims  PTAL for my pr to this issue, thx
https://github.com/kubernetes/kubernetes/pull/88450

**Comment by agadelshin** [comment]
@Raman-Kumar you can move kubernetes directory to `/Users/ramankumar/go/src/k8s.io/` and re-run this script.

**Comment by agadelshin** [comment]
I'd like to take `pkg/apis/apps/*`

**Comment by knabben** [comment]
Besides the @agadelshin question about skipping zz_generated files, some other cleaning patterns found without some clear solution. 

1. A default pattern of Kubectl is the usage of [cmd]Options for initial options structs and it raises:

```
type name will be used as annotate.AnnotateOptions by other packages, and that stutters; consider calling this Options
``` 

2. pkg/apis/{custom_metrics,external_metrics} raises, It's probably not worth to break compatibility renaming these folder for lint error:

```
don't use an underscore in package name
```

Any advice on these?

**Comment by formanojhr** [comment]
I am sure this is all not fixed. Am I missing something? 
./hack/verify-golint.sh
installing golint from vendor
Congratulations!  All Go source files have been linted.

**Comment by agadelshin** [comment]
@formanojhr you need to remove package from https://github.com/kubernetes/kubernetes/blame/master/hack/.golint_failures first.

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG testing doesn't own code failing lints, we own the linter. :upside_down_face:

**Comment by Ajitesh13** [comment]
Hello, is this still a relevent issue ? I would like to work upon

**Comment by saintube** [comment]
@dims I have fixed `/pkg/controller/podgc` #68181

#93628 

```go
pkg/controller/podgc
```

**Comment by ScrapCodes** [comment]
Hi Folks,

Some of the golint fixes, require us to change the exposed function's name, in simple words, "change API". I was not sure, if that is welcomed and what is the process.

**Comment by suramrit** [comment]
A strange issue that Im seeing is after following the following steps as mentioned by @dims 
- Say your GOPATH looks like this GOPATH=/Users/dims/go
- Your kubernetes directory should be /Users/dims/go/src/k8s.io/kubernetes ($GOPATH/src/k8s.io/kubernetes)
- cd to /Users/dims/go/src/k8s.io/kubernetes and then run hack/verify-golint.sh from that directory.

I get the following output - 
installing golint
Congratulations!  All Go source files have been linted.

Im not really sure what I am doing wrong. Any help is appreciated!

**Comment by suramrit** [comment]
> Heres what Im getting after going over the following steps as mentioned by @dims
> 
> * Say your GOPATH looks like this GOPATH=/Users/dims/go
> * Your kubernetes directory should be /Users/dims/go/src/k8s.io/kubernetes ($GOPATH/src/k8s.io/kubernetes)
> * cd to /Users/dims/go/src/k8s.io/kubernetes and then run hack/verify-golint.sh from that directory.
> 
> I get the following output -
> installing golint
> Congratulations! All Go source files have been linted.
> 
> Im not really sure what I am doing wrong. Any help is appreciated!

I think I understand. I misunderstood the steps around .golint_failures. 

The first step is to remove the pkg that we are targeting from this file and then run the `hack/verify-golint.sh` 

My mistake was to assume that the packages in the file itself need to be removed after we are done cleaning the golint errors.

**Comment by geegeea** [comment]
Can someone please review and let me know if I've done this right? #97167

**Comment by liggitt** [comment]
After a couple years of seeing changes spawned from this issue, I don't think this is a good use of contributors' or reviewers' time. golint is very opinionated about
* exported type and function names, leading to PRs attempting to change exported things people use downstream
* missing documentation on interface implementation functions, which leads to not-very-useful copy/paste of interface godoc

the govet and staticcheck verify jobs are much more useful since they catch correctness issues, but I would recommend closing this issue and dropping the golint checks from CI

**Comment by neolit123** [comment]
i guess one can say gofmt is opinionated too, but something good about Golang is that it comes with an opinion and a set of standard tools.

for API documentation at least we found inconsistencies on how exported all API items are documented:
https://github.com/kubernetes/website/issues/23889

golint can help with that, but if there are no "pragmas" to avoid breaking changes and given we have codegen generating non-compliant names enabling golint on API packages is sort of blocked in Kubernetes.

for non-API, non-library, non-public code, i think being inconsistent is mostly OK.

> I would recommend closing this issue and dropping the golint checks from CI

no preference on my side. shrug

**Comment by liggitt** [comment]
> i guess one can say gofmt is opinionated too, but something good about Golang is that it comes with an opinion and a set of standard tools.

true, but code formatting has the benefits of mostly eliminating meaningless diffs in PRs due to code movement/whitespace/etc

> for API documentation at least we found inconsistencies on how most exported API items are documented

if there are specific packages (like API packages) we lack documentation on, adding checks specifically for that could make sense

> golint can help with that, but if there are no "pragmas" to avoid breaking changes and given we have codegen generating non-compliant names enabling golint on API packages is sort of blocked in Kubernetes.

exactly, I don't think golint is the right tool for making sure we have API docs

**Comment by BenTheElder** [comment]
> golint can help with that, but if there are no "pragmas" to avoid breaking changes and given we have codegen generating non-compliant names enabling golint on API packages is sort of blocked in Kubernetes.

golint itself doesn't have these and the go project is against this sort of comment AIUI, however golangci-lint does have them.

I think there are plenty of other static analysis lints we should use instead, beyond just staticcheck and vet there is e.g. `ineffassign`

**Comment by neolit123** [comment]
btw, if we remove golint can we see e.g. all-caps constants or functions with underscores dodging review?

perhaps we should add golangci-lint soon after:
https://github.com/kubernetes/kubernetes/issues/81518

**Comment by spiffxp** [comment]
Completely agree there are better places to spend review bandwidth.

I was curious to see what the effort looked like.

There have been 469 commits that touched `hack/.golint_failures` over the past 3+ years

![golint_failures linecount over time](https://user-images.githubusercontent.com/49258/104669500-23336f80-56a8-11eb-8c6e-2bbb1760ccef.png)

**Comment by krmayankk** [comment]
Overall agree on the bandwidth. Also note that it was a good first issue with very low bar to get them in the repo. May be we need to find a similar low bar, but high value good first issue. UT's come to mind, are there other things we curate for new contributors ?

**Comment by alculquicondor** [comment]
Do we have an alternative way of enforcing that new exported code (not necessarily API fields) has at least some minimum documentation?

As a reviewer, I ask contributors to add meaningful comments. But reality is that I sometimes stumble into old code that doesn't have documentation because we didn't have golint at some point.

I agree that fix-golint PRs just add burden to reviewers. But, before removing the lint check, can we wait and see if it's enough to discourage people from sending more PRs like this?
Additionally, we can encourage reviewers to just close PRs that only fix golint issues.

**Comment by lauchokyip** [comment]
+1 for adding burden to reviewers. 
However, as a new contributor, I think this a very good opportunity for new contributors to study the code base and submit their first PR. This issue would be able to attract more new contributors, get familiar with the code base, and get familiar with the git workflow.

**Comment by dims** [comment]
thanks everyone for getting us this far. We essentially gave up on the existing structure/system for golint:
https://github.com/kubernetes/kubernetes/pull/98063

At some point we can look at adding golangci-lint, there's a WIP in progress in https://github.com/kubernetes/kubernetes/pull/93656

/close
