### ISSUE TITLE
glusterfs log files may become very large if volumes mount failed

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#68050]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
when a pod start and need to mount a gluster volume, a log file will be created to record the errors in glusterfs mount. The log path is at 	/var/lib/kubelet/plugins/kubernetes.io/glusterfs/[volName]/[podName]-glusterfs.log

we encounter a scenario that pod mount glusterfs always failed since the glusterfs server is unreachable for a long time. Finally the log file become quite large,as bellow. 
![image](https://user-images.githubusercontent.com/25921749/44841299-9ffb5580-ac75-11e8-825e-306161cdbca4.png)

when could these log files be cleaned up without manual deletion?

**What you expected to happen**:

I consider if we should remove the log file after every mount whether mount failed or successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by houjun41544** [comment]
@kubernetes/sig-storage-bugs, can you have a look at this?

**Comment by houjun41544** [comment]
We would like to resolve this problem by  clearing gluster log file after read logs. #68814

**Comment by houjun41544** [comment]
@humblec If the log file is provided by user, they could archive and clear the logs by themselves. But if it is driver specific ,maybe users do not known the log file existed at all.

**Comment by warmchang** [comment]
> Clearing the log after each mount success/failure may not be good as admins want to track it later

@humblec 
The glusterfs log info will be read and stored in the kubelet log, the admins can track it from the kubelet's log file, so the glusterfs log is redundant and can be emptied.

```
	// Failed mount scenario.
	// Since glusterfs does not return error text
	// it all goes in a log file, we will read the log file
	logErr := readGlusterLog(log, b.pod.Name)
	if logErr != nil {
		return fmt.Errorf("mount failed: %v the following error information was pulled from the glusterfs log to help diagnose this issue: %v", errs, logErr)
	}
```

**Comment by houjun41544** [comment]
@humblec In addition, it seems that the log files will never be removed even if pods and volumes have been deleted.
Why not place the log file in the pod plugin dir rather than plugin dir?

**Comment by humblec** [comment]
> @humblec
The glusterfs log info will be read and stored in the kubelet log, the admins can track it from the kubelet's log file, so the glusterfs log is redundant and can be emptied.
>
@warmchang Its just last 2 lines are exposed to kubelet , most of the time these 2 lines can give clue, but at times the sequence of events need to be looked at for debugging the issue so the logfile can help.

**Comment by humblec** [comment]
>@humblec In addition, it seems that the log files will never be removed even if pods and volumes have been deleted.
>
It seems to me that, clearing/removing log file when pod is deleted would be better. 
@jsafrane Any  thoughts on this ?

**Comment by warmchang** [comment]
> It seems to me that, clearing/removing log file when pod is deleted would be better.

@humblec The result of this modification is the same. [As you described](https://github.com/kubernetes/kubernetes/issues/68050#issuecomment-423165972), when the volume mount failed, the admin will check log file to debug the issue. But unfortunately, the log does not existed because it has been cleaned/deleted when the POD dies.

**Comment by admoriarty** [comment]
Would love to see this issue resolved, it just caused us to starting losing a node intermittently due to a DiskPressure threshold being hit, because of months old logs of this type, the largest being 7G!

**Comment by warmchang** [comment]
@admoriarty That's why @houjun41544 submitted this issure, and the [PR #68814](https://github.com/kubernetes/kubernetes/pull/68814) try to solve it.

**Comment by dmoessne** [comment]
so, I think this is still an issue and do not get why it is abandoned. Are there at least any recommendations how to avoid that ?

**Comment by koep** [comment]
I agree with dmoessne that this issue should be addressed - at least in the form of documentation that recommends steps on how to mitigate the issue (e. g. logrotate). CC @humblec any thoughts?
