### ISSUE TITLE
FlexVolume (1.10.6): err=no volume plugin matched

### ISSUE THREAD

**Issue by rhugga** [kubernetes/kubernetes#68070]
/kind bug

**What happened**:
Flexvolume drive is not being found.

`2018-08-30T14:10:48.591755+00:00 pv41p01if-smds08022901 kubelet[11776]: E0830 14:10:48.591675   11776 desired_state_of_world_populator.go:293] Failed to add volume "test" (specName: "test") for pod "54381998-ac5e-11e8-b13f-0cc47a587b96" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched
2018-08-30T14:10:48.692045+00:00 pv41p01if-smds08022901 kubelet[11776]: E0830 14:10:48.691980   11776 desired_state_of_world_populator.go:293] Failed to add volume "test" (specName: "test") for pod "54381998-ac5e-11e8-b13f-0cc47a587b96" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched`

Here you can see I have explicitly set --flex-volume-plugin-dir for the controller manager even though I'm using the default:

`root      1238  0.0  0.0 103848 57452 ?        Ssl  14:06   0:00 /usr/bin/kube-controller-manager --leader-elect=true --leader-elect-lease-duration=30s --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem --root-ca-file=/etc/kubernetes/ssl/ca.pem --enable-hostpath-provisioner=false --node-monitor-grace-period=40s --node-monitor-period=5s --pod-eviction-timeout=3m0s --use-service-account-credentials --address=127.0.0.1 --kube-api-burst=50 --kube-api-qps=30 --terminated-pod-gc-threshold=1000 --large-cluster-size-threshold=20 --node-eviction-rate=0.01 --secondary-node-eviction-rate=0.005 --horizontal-pod-autoscaler-use-rest-clients=false --flex-volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec --kubeconfig=/etc/kubernetes/kube-controller-manager-kubeconfig.yaml --v=2`

Here you can see I've explicitly set --volume-plugin-dir for the kubelet config even though I'm using the default:

`root      1254  2.4  0.0 2363068 109552 ?      Ssl  Aug29  21:08 /usr/bin/kubelet --v=2 --address=17.143.248.100 --hostname-override=pv34p01if-smds04103601 --allow-privileged=true --pod-manifest-path=/etc/kubernetes/manifests --pod-infra-container-image=docker.apple.com/k8s/pause-amd64:3.1 --cadvisor-port=0 --read-only-port=0 --tls-cert-file=/etc/kubernetes/ssl/node-pv34p01if-smds04103601.pv.if.apple.com.pem --tls-private-key-file=/etc/kubernetes/ssl/node-pv34p01if-smds04103601.pv.if.apple.com-key.pem --client-ca-file=/etc/kubernetes/ssl/ca.pem --authentication-token-webhook=true --authorization-mode=Webhook --kube-reserved=cpu=500m,memory=512Mi --system-reserved=cpu=1000m,memory=5500Mi --max-pods=64 --image-pull-progress-deadline=30m --serialize-image-pulls=false --image-gc-low-threshold=60 --image-gc-high-threshold=75 --eviction-soft=imagefs.available<15%,nodefs.available<15%,nodefs.inodesFree<15%,imagefs.inodesFree<15% --eviction-soft-grace-period=imagefs.available=10m,nodefs.available=10m,nodefs.inodesFree=10m,imagefs.inodesFree=10m --eviction-hard=imagefs.available<5%,memory.available<200Mi,nodefs.available<5%,nodefs.inodesFree<5%,imagefs.inodesFree<5% --node-status-update-frequency=10s --cgroups-per-qos=True --feature-gates=LocalStorageCapacityIsolation=true --enforce-node-allocatable=pods --cluster-dns=17.143.248.100,172.31.0.3 --cluster-domain=dseqa1 --resolv-conf=/etc/resolv.conf --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --register-with-taints=node-role.kubernetes.io/master=:NoSchedule --node-labels=node-role.kubernetes.io/master=true,failure-domain.beta.kubernetes.io/region=pv,failure-domain.beta.kubernetes.io/zone=pv34-0410,apple.k8s.io/local-storage=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec`

Here is controller-managed-attach-detach showing as true:

kubectl describe nodes | grep  volume
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 
                    volumes.kubernetes.io/controller-managed-attach-detach=true . 

Here is my driver installed on all nodes including the masters:

`ls -lR /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/:
total 8
drwxr-xr-x 2 root root 4096 Aug 30 02:20 bithub~lvm

/usr/libexec/kubernetes/kubelet-plugins/volume/exec/bithub~lvm:
total 12
-rwxr-xr-x 1 root root 10127 Aug 30 02:20 lvm`

Here is my pod spec:
`apiVersion: v1
kind: Pod
metadata:
  name: flexvol-test
  namespace: default
spec:
  containers:
  - name: flexvol-test
    image: docker.example.com/myuser/mycontainer:1.0
    env:
    - name: SPIN
      value: "true"
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: bithub/lvm
      fsType: ext4
      options:
        volname: test-volume
        volsize: 10G
        volgroup: vg1
        volfstype: ext4
        volfsopts: ""
        mountpoint: /data
        mountopts: rm,noatime`

Kubernetes Version:

`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"archive", BuildDate:"2018-07-30T07:32:49Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"archive", BuildDate:"2018-07-30T07:32:49Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"linux/amd64"}`

Operating System:

`Linux myhost.example.com 4.1.12-124.16.4.el7uek.x86_64 #2 SMP Thu Jun 14 18:17:30 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

/sig bugs
/sig storage

**Comment by wpf710** [comment]
have you tried to restart the kubelet service?

**Comment by kobozo** [comment]
I had the same problem and restarting the kubelet was the solution. Thank you @wpf710

**Comment by kvaps** [comment]
Cleanup of whole `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/` directory was helped for me.

Then restart containers with your flexvolume driver, for reinstall it again.
