### ISSUE TITLE
kubectl enhanced to have --noproxy like parameter.

### ISSUE THREAD

**Issue by jeffbean** [kubernetes/kubernetes#6808]
With `kubectl` having the --server parameter should also allow a way to specify a noproxy address.

The reason being is the environment that I am working with needs a proxy server for everything. When trying to specify a --server with `kubectl` there is no way to specify when to use the proxy vs. not use the proxy on the command line.

As a workaround I have to add the address to NO_PROXY.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by liggitt** [comment]
NO_PROXY is a more standard way to counteract envvar based proxy settings
