### ISSUE TITLE
Stop using ginkgo.flakeAttempts

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#68091]
- Is this really useful? (fuzzer based tests?)
- Does this contribute to hiding flakiness in our test suites?
- Is it time to get rid of it?

(Do we really need ginkgo is the larger question i guess!)

**Comment by dims** [comment]
cc @spiffxp @BenTheElder @bgrant0607

**Comment by bgrant0607** [comment]
It would be good to measure what the impact of this is now. Maybe turn it off in the post-submit tests for a few days after code freeze so that we could observe the impact? Do we have a way to monitor failures in the pre-submit tests?

**Comment by spiffxp** [comment]
I was literally talking about this yesterday with @jdumars and @calebamiles, stop reading my mind.

I think we should turn this off selectively before turning it off globally.  I would welcome a job that runs the "normal" and "flaky" tests together, with this setting turned off, so that we could accumulate some data first, ref: https://github.com/kubernetes/test-infra/issues/9208

I don't have enough context yet to answer the broader question about ginko, but anecdotally I haven't heard a lot of love for it

**Comment by spiffxp** [comment]
We still don't have useful data because the job @dims created has been perpetually failing (due to timeout IIRC)

/remove-lifecycle rotten

/assign @dims @spiffxp 
because we worked on it

/assign @mariantalla 
has to do with deflaking, giving you a heads up this way until we have something better to cluster related issues (some combo of sig+king labels? area label? project board?)

**Comment by dims** [comment]
we have some good data now @mariantalla @spiffxp 

https://testgrid.k8s.io/google-gce#gci-gce-single-flake-attempt&width=20

**Comment by BenTheElder** [comment]
remove-lifecycle stale
someday...

**Comment by BenTheElder** [comment]
@spiffxp @mariantalla what next?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
What would be useful now would be to take a look at tests that are flaking (and their flake rate) and compare to the default that uses flakeAttempts

I would use a modified version of the query contained within this config https://github.com/kubernetes/test-infra/blob/master/metrics/configs/flakes-config.yaml and expand its range over more than `interval 7 day`

/help
This is something anyone with a free-tier GCP account can do as long as they stay under the monthly limit of 1TB of data queried.  My advice would be to prototype against `build.week` instead of `build.all`

**Comment by BenTheElder** [comment]
/remove-lifecycle rotten
cc @liggitt

**Comment by spiffxp** [comment]
I hacked up http://velodrome.k8s.io/dashboard/db/job-health-release-informing?orgId=1 to use 7d avgs and added the single flake attempt job to get this comparison of the two jobs over the last 6 months

<img width="1491" alt="single-flake-vs-multi-attempt" src="https://user-images.githubusercontent.com/49258/70337377-ce17ff80-17ff-11ea-9f13-865c5c725da4.png">

If you had asked me before November I would have said it's clear we should drop the retries based on difference in failure/flake rates.  I still lean in that direction now, since their similarity to me means we're not getting any additional value

Another thing we could do is see if the flakes discovered by each job differ appreciably

**Comment by spiffxp** [comment]
https://gist.github.com/spiffxp/ff38f6d32c657679b20a81a7a01b7415 - a look at the top 20 flakes caught by each job over the past 8 weeks

We could also try looking at the long tail of flakes caught by each, but I stopped after seeing they both caught at least 120 over the past week, and their rankings up top aren't appreciably different.

**Comment by spiffxp** [comment]
Sigh. So upon closer inspection, the ci-kubernetes-e2e-gci-gce job does not appear to actually use flakeAttempts. So we are essentially comparing the same apple to itself when we compare against the single-flake-attempt job.

To compare apples and oranges, we can look at the characteristics of the PR job vs. the CI job. The flake rate of the CI job is roughly double the flake rate of the PR job.

- http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?orgId=1&var-rjob=pr:pull-kubernetes-e2e-gce&from=now-6M&to=now
- http://velodrome.k8s.io/dashboard/db/job-health-release-informing?orgId=1&var-rjob=ci-kubernetes-e2e-gci-gce

I still feel like we should rip the bandaid off. Going to get a list of impacted jobs

**Comment by spiffxp** [comment]
The following jobs explicitly set flakeAttempts to 2:
- ci-cadvisor-e2e
- ci-cloud-provider-azure-conformance
- ci-cloud-provider-azure-conformance-vmss
- ci-cloud-provider-azure-multiple-zones
- ci-cloud-provider-azure-serial
- ci-cloud-provider-azure-slow
- ci-cloud-provider-azure-slow-vmss
- ci-containerd-node-e2e
- ci-containerd-node-e2e-1-2
- ci-containerd-node-e2e-1-3
- ci-containerd-node-e2e-features
- ci-containerd-node-e2e-features-1-2
- ci-containerd-node-e2e-features-1-3
- ci-cos-containerd-node-e2e
- ci-cos-containerd-node-e2e-features
- ci-cri-containerd-node-e2e
- ci-cri-containerd-node-e2e-features
- ci-kubernetes-e2e-aks-engine-azure-1-14-windows
- ci-kubernetes-e2e-aks-engine-azure-1-15-windows
- ci-kubernetes-e2e-aks-engine-azure-1-16-windows
- ci-kubernetes-e2e-aks-engine-azure-1-17-windows
- ci-kubernetes-e2e-aks-engine-azure-master-staging-windows
- ci-kubernetes-e2e-aks-engine-azure-master-windows
- ci-kubernetes-e2e-aws-eks-1-13-conformance
- ci-kubernetes-e2e-aws-eks-1-13-correctness
- ci-kubernetes-e2e-gce-private-cluster-correctness
- ci-kubernetes-e2e-gce-scale-correctness
- ci-kubernetes-e2e-kops-aws
- ci-kubernetes-e2e-kops-aws-beta
- ci-kubernetes-e2e-kops-aws-canary
- ci-kubernetes-e2e-kops-aws-channelalpha
- ci-kubernetes-e2e-kops-aws-ena-nvme
- ci-kubernetes-e2e-kops-aws-ha-uswest2
- ci-kubernetes-e2e-kops-aws-imagecentos7
- ci-kubernetes-e2e-kops-aws-imageubuntu1604
- ci-kubernetes-e2e-kops-aws-networking-kopeio-vxlan
- ci-kubernetes-e2e-kops-aws-newrunner
- ci-kubernetes-e2e-kops-aws-sig-cli
- ci-kubernetes-e2e-kops-aws-stable1
- ci-kubernetes-e2e-kops-aws-stable2
- ci-kubernetes-e2e-kops-aws-stable3
- ci-kubernetes-e2e-kops-aws-updown
- ci-kubernetes-e2e-kops-aws-vpc-cni
- ci-kubernetes-e2e-kops-aws-weave
- ci-kubernetes-e2e-kops-gce
- ci-kubernetes-e2e-kops-gce-canary
- ci-kubernetes-e2e-kops-gce-channelalpha
- ci-kubernetes-e2e-kops-gce-ha
- pull-cadvisor-e2e
- pull-cloud-provider-azure-e2e
- pull-cri-containerd-node-e2e
- pull-kops-e2e-kubernetes-aws
- pull-kops-e2e-kubernetes-aws-1-15
- pull-kops-e2e-kubernetes-aws-1-16
- pull-kubernetes-e2e-aks-engine-azure-windows
- pull-kubernetes-e2e-gke
- pull-kubernetes-e2e-kops-aws
- pull-kubernetes-node-e2e
- pull-kubernetes-node-e2e-alpha
- pull-kubernetes-node-e2e-containerd

The following jobs use GINKGO_TOLERATE_FLAKES which ends up setting flakeAttempts to 2:
- pull-kubernetes-e2e-containerd-gce
- pull-kubernetes-e2e-gce
- pull-kubernetes-e2e-gce-alpha-features
- pull-kubernetes-e2e-gce-csi-serial
- pull-kubernetes-e2e-gce-device-plugin-gpu
- pull-kubernetes-e2e-gce-iscsi
- pull-kubernetes-e2e-gce-iscsi-serial
- pull-kubernetes-e2e-gce-rbe
- pull-kubernetes-e2e-gce-storage-disruptive
- pull-kubernetes-e2e-gce-storage-slow
- pull-kubernetes-e2e-gce-storage-slow-rbe
- pull-kubernetes-e2e-gce-storage-snapshot
- pull-kubernetes-e2e-gci-gce-autoscaling
- pull-release-cluster-up

**Comment by spiffxp** [comment]
Options in order from least to most disruptive:
1. explicitly add flakeAttempts=2 to the ci-kubernetes-e2e-gci-gce job, and wait to see if the flake rate goes down appreciably, and whether this increases job duration.. if so, maybe we should keep it
2. explicitly remove the GINKGO_TOLERATE_FLAKES env var from pull-kubernetes-e2e-gce and see if the flake rate goes up appreciably, and whether this decreases job duration... this will tell us whether we expose more (or different) flakes on a high traffic job
3. just go ahead and remove it everywhere, and leave it to the community to quarantine and fix whatever flakes rise to the surface (for example, as of today, none of the jobs on release-master-blocking use it, and almost none of the jobs on release-master-informing use it)

The "rip the band aid off" option is 3, and that's what I'd prefer we do. This next month is typically a quiet period, and we would expose just how much flakiness we've been hiding, if any.

/assign @dims
I'm bringing you back in for your opinion here

**Comment by liggitt** [comment]
> 3\. just go ahead and remove it everywhere, and leave it to the community to quarantine and fix whatever flakes rise to the surface (for example, as of today, none of the jobs on release-master-blocking use it, and almost none of the jobs on release-master-informing use it)
> 
> The "rip the band aid off" option is 3, and that's what I'd prefer we do. This next month is typically a quiet period, and we would expose just how much flakiness we've been hiding, if any.

That would be my preference as well. To prepare for the cold dose of reality, I'd recommend:
* making sure we have good visibility to which tests are flaking (testgrid, http://storage.googleapis.com/k8s-metrics/flakes-latest.json, https://storage.googleapis.com/k8s-gubernator/triage/index.html, are working, etc)
* pre-announcing intent to kubernetes-dev and/or sig leads mailing lists
* thinking about what the recommended process/recommendation would be for tracking flaking tests (issue per test? per job? opened by whom? with what severity?)
* thinking about what the recommended process/recommendation would be for sigs to follow to resolve flaking tests (tag with `[Flaky]`? quarantine/remove?)

If/when the band-aid comes off, sending out a summary (maybe weekly?) of the top flaking tests, and the delta from the last report might help keep visibility on the problem and incentivize action.

**Comment by smarterclayton** [comment]
"rip the bandaid off" = Getting my poncho for the hot arterial blood about to go everywhere

**Comment by spiffxp** [comment]
I appreciate what @liggitt is asking for, but I have concerns that's blowing scope from "stop retrying flakes" to "put together better deflaking guides, policies, and tools than we have now" and is going to take a while.

I'd rather not have perfect be the prerequisite for this, but am willing to massage existing content into something more cohesive than what we have.

Looking for existing content on flakes:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md#helping-with-known-flakes
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md#troubleshooting-a-failure
- https://github.com/kubernetes/community/blob/master/contributors/design-proposals/testing/flakiness-sla.md - this was never implemented
- https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/README.md - covers CI signal's flake hygiene, and mentions CI signal for reporting on top issues

Existing dashboards:
- https://go.k8s.io/triage - drill down by failure text, test name, job name
- https://testgrid.k8s.io - tests for a given job, sort by flakiness
- http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?orgId=1 - flakiness per job, top two flakes over the past week per job

**Comment by liggitt** [comment]
Even just an email to sig leads and kubernetes-dev describing the intent, along with those topics/references, would be helpful.

**Comment by dims** [comment]
+100 to throw the lever after dropping an email heads up @liggitt @spiffxp

**Comment by spiffxp** [comment]
[kubernetes-dev@ thread](https://groups.google.com/d/msg/kubernetes-dev/NNmEGUsJObg/dmI2mVc_AAAJ), proposed merging by Friday the 13th.  _\[ makes spooky noises \]_

**Comment by BenTheElder** [comment]
`pull-kubernetes-e2e-kind` (NOT `.*kind.*conformance` jobs) was setting `GINKGO_TOLERATE_FLAKES=y` to follow `pull-kubernetes-e2e-gce`.

This was resolved over the weekend shortly after the main change merged. https://github.com/kubernetes-sigs/kind/pull/1171

This job will also be impacted.
