### ISSUE TITLE
Histogram metrics generating overwhelming number of prometheus metrics

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#68115]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

In Kubernetes 1.11.x, the controller-manager metrics are providing histogram records for every api endpoint ever called during namespace cleanup. For every namespace that is deleted since a controller has been the leader, 1000+ new lines of metrics are created / served indefinitely. When creating/deleting namespaces at a rate of 100/hour, that's 100,000+ new metrics lines being served for every request of controller-manager/metrics. 

@cduchesne spun up a 1.10 environment, and says it looks like the namespace names were replaced with {namespace}:
```
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.004"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.008"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.016"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.032"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.064"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.128"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.256"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="0.512"} 3
rest_client_request_latency_seconds_bucket{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE",le="+Inf"} 3
rest_client_request_latency_seconds_sum{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE"} 0.009903814
rest_client_request_latency_seconds_count{url="http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/configmaps",verb="DELETE"} 3
```

In 1.11 this has changed (short clip of 1 histogram):
```
rest_client_request_latency_seconds_count{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-zkjs4/configmaps?includeUninitialized=%7Bvalue%7D",verb="GET"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.004"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.008"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE"} 0.002813621
rest_client_request_latency_seconds_count{url="https://127.0.0.1:6443/api/v1/namespaces/e2e-tests-znspv/configmaps",verb="DELETE"} 1
```

**What you expected to happen**:
Don't generate so many metrics.

**How to reproduce it (as minimally and precisely as possible)**:

To replicate in 1.11.x, simply create and then delete a namespace and query the metrics endpoint of your controller-manager.

**Anything else we need to know?**:

Repro steps and bug reported by @cduchesne

/sig api-machinery

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saad-ali** [comment]
@cduchesne did some more debugging and believes that the root cause is https://github.com/kubernetes/kubernetes/pull/63444

He says that PR switched to the new dynamic client so when a request is made, this function is called:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L637

```Go
metrics.RequestLatency.Observe(r.verb, r.finalURLTemplate(), time.Since(start))
```

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L456-L477

```GO
// finalURLTemplate is similar to URL(), but will make all specific parameter values equal
// - instead of name or namespace, "{name}" and "{namespace}" will be used, and all query
// parameters will be reset. This creates a copy of the request so as not to change the
// underlying object.  This means some useful request info (like the types of field
// selectors in use) will be lost.
```

He explains that function in the old client checks if `request.namespace` is set, the following is an example call:
`gc.clientPool.ClientForGroupVersionKind(fqKind).Resource(resource, item.Namespace).Delete(item.Name, &deleteOptions)`

In the new client, the following is an example call: `dynamicClient.Resource(resource).Namespace(resourceDefaultNamespace(namespaced, item.Namespace)).Delete(item.Name, &deleteOptions)`

In this new dynamic client, the delete operation calls: 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/dynamic/simple.go#L192-L197

```GO
result := c.client.client.
        Delete().
        AbsPath(append(c.makeURLSegments(name), subresources...)...).
        Body(deleteOptionsByte).
        Do()
```

whereas in the old client, it ran: https://github.com/kubernetes/kubernetes/blob/release-1.10/staging/src/k8s.io/client-go/dynamic/client.go#L195-L203

```
func (rc *ResourceClient) Delete(name string, opts *metav1.DeleteOptions) error {
    return rc.cl.Delete().
        NamespaceIfScoped(rc.ns, rc.resource.Namespaced).
        Resource(rc.resource.Name).
        Name(name).
```

The `NamespaceIfScoped(rc.ns, rc.resource.Namespaced)`, he says, is the critical component, which sets the request client namespace field without namespace being set, when https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L637 is called then the metrics are populated without renaming the Namespace
to `{namespace}` which causes tons of unique metrics to be generated and cause metrics data grow very quickly.

This seems to be a pretty critical bug. Will mark it for v1.12. Please triage.

/milestone v1.12

CC @deads2k

**Comment by guineveresaenger** [comment]
@lavalamp @deads2k - friendly reminder that Code Freeze is next week; if this is critical enough for 1.12 it needs   to be triaged accordingly.

**Comment by deads2k** [comment]
@cduchesne This isn't a regression (1.11 had it), but it's a big enough bug that I'd take a fix for it in 1.12. 

I think that a fix should take the form of fixing the `finalURLTemplate()` to handle cases where the abspath is set.  That would fix it for all future callers instead of just a one off for this client.  That method is only called for metrics and our api paths follow a very fixed format.  I expect that it should be fairly easy to recognize and you only have to do the analysis if you have no hits for the namespace being set.

**Comment by nikopen** [comment]
@deads2k please apply a priority/critical-urgent label to keep track for 1.12

**Comment by lavalamp** [comment]
I applied the label.

We will have to un-apply it if a targeted fix doesn't show up very soon :)

**Comment by wenjiaswe** [comment]
If no one has started working on it, I am on this now. I will try fix it ASAP.

**Comment by guineveresaenger** [comment]
@wenjiaswe please do!

**Comment by guineveresaenger** [comment]
@vladimirvivien @wenjiaswe please update on a daily basis, as we're in Code Freeze. :)

**Comment by wenjiaswe** [comment]
I have reproduced the problem and also wrote a unit test case for confirmation. Basically with the current dynamic client implementation, the actually string of namespace is added in url here: https://github.com/kubernetes/kubernetes/blob/80b73d70a8f0926760818cc3aba8148ad0dfe419/staging/src/k8s.io/client-go/dynamic/simple.go#L316, so when finalURLTemplate function checks `r.namespaceSet && len(r.namespace) != 0` (https://github.com/kubernetes/kubernetes/blob/f85d39abedff729f660484d7e056426a1c3f3786/staging/src/k8s.io/client-go/rest/request.go#L466), it returns false and would not replace namespace with "{namespace}". I am working on fixing it by replacing the url segment after /namespaces/ by `"{namespaces}"`. 

**I should be able to submit the PR tomorrow if not today.**
