### ISSUE TITLE
GKE node preemption leaves pods unreachable

### ISSUE THREAD

**Issue by lkoba** [kubernetes/kubernetes#68142]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: 
When a GKE node is preempted, some pods are left with an unrouteable IP.

**What you expected to happen**:
When a GKE node is preempted, pods are restarted/recreated/rescheduled/etc and they continue working normally.

**How to reproduce it (as minimally and precisely as possible)**:
I have already reported this issue on Google's issue tracker and it has apparently been confirmed. There are detailed instructions to reproduce this problem with a test cluster:  https://issuetracker.google.com/issues/113499596

**Anything else we need to know?**:
Liveness probes don't fix this. The container will be restarted but the pod IP doesn't change.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.6-gke.1 (has been happening since 1.8 at least)
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`): 4.14.22+
- Install tools: N/A
- Others: N/A

**********************

Since it's an ETA-less fix I'm opening this issue because I'd like to know what would be a good workaround. Our current solution requires off cluster monitoring so I'd like to build something like a controller pod to detect and fix the broken pods but I'd like to check if there's a better way and listen for ideas on how to tackle this issue.

**Comment by BenTheElder** [comment]
@MrHohn 
/sig gcp

**Comment by freehan** [comment]
Fixed in GKE
