### ISSUE TITLE
flaky test: [sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#68148]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
The e2e test:
`[sig-scalability] Density [Feature:Performance] should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons`

flakes with slightly too much CPU usage, eg:
```
test/e2e/framework/framework.go:145
Expected error:
    <*errors.errorString | 0xc42439e150>: {
        s: "Container kube-scheduler-e2e-67971-95a39-master/kube-scheduler is using 0.424397825/0.4 CPU",
    }
    Container kube-scheduler-e2e-67971-95a39-master/kube-scheduler is using 0.424397825/0.4 CPU
not to have occurred
test/e2e/framework/framework.go:413
```

**What you expected to happen**: I expect PR blocking tests to not be flaking.

**How to reproduce it (as minimally and precisely as possible)**: `go run hack/e2e.go -v --test --test_args='--ginkgo.focus=\[sig\-scalability\]\sDensity\s\[Feature\:Performance\]\sshould\sallow\sstarting\s30\spods\sper\snode\susing\s\{\sReplicationController\}\swith\s0\ssecrets\,\s0\sconfigmaps\sand\s0\sdaemons$'`

**Anything else we need to know?**: Examples:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=CPU&test=Density%20%5C%5BFeature%3APerformance%5C%5D%20should%20allow%20starting%2030%20pods%20per%20node

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67971/pull-kubernetes-e2e-gce-100-performance/18830/

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/68096/pull-kubernetes-e2e-gce-100-performance/18664/#sig-scalability-density-featureperformance-should-allow-starting-30-pods-per-node-using-replicationcontroller-with-0-secrets-0-configmaps-and-0-daemons

**Environment**:
- Kubernetes version (use `kubectl version`): ci tests against master branch
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig scalability
/kind bug

**Comment by jberkus** [comment]
This is old, and we have new failures on that test now.  So, closing.

/close
