### ISSUE TITLE
Update client client guidelines to recommend reloading tokens

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#68164]
ref https://github.com/kubernetes/kubernetes/pull/67359#issuecomment-415463989

/sig auth

The minimum supported token lifetime for projected service account tokens is 10 minutes, and renewal occurs at ~80% of token lifetime, so reloading once per minute is sufficient to ensure a reload occurs between renewal and expiration.

If reload from file fails, the last-read token should be used to avoid breaking clients that make token files available on process start and then remove them to limit credential exposure.

**Comment by liggitt** [comment]
/sig api-machinery 
as well

**Comment by mikedanese** [comment]
- [ ] https://github.com/kubernetes-client/python/issues/616
- [ ] https://github.com/kubernetes-client/javascript/issues/317
- [ ] https://github.com/kubernetes-client/haskell/issues/54
- [ ] https://github.com/kubernetes-client/csharp/issues/293
- [ ] https://github.com/kubernetes-client/perl/issues/12
- [ ] https://github.com/kubernetes-client/ruby/issues/47

**Comment by jheiss** [comment]
Also kubernetes-client/java#652

**Comment by mikedanese** [comment]
cc @happinesstaker

**Comment by zshihang** [comment]
kubernetes-client/perl does not have incluster config yet, so it is not a blocker for GA.
