### ISSUE TITLE
Master nodes missing NoSchedule taint and pods are being scheduled on them

### ISSUE THREAD

**Issue by eroji** [kubernetes/kubernetes#68160]
I have a HA master cluster setup where it was initialized using kubeadm. It appears that the NoSchedule taint for them were removed and now there are pods being being scheduled on them which I don't want to run. Is there a way to retaint the nodes so that they serve as master only and not handle any workloads?

**Comment by Huang-Wei** [comment]
@eroji kube version? and any featuregate is enabled?

**Comment by eroji** [comment]
@Huang-Wei 1.10.5, no featuregates.
