### ISSUE TITLE
use KUBE_BUILD_WITH_COVERAGE directly in kube::golang::build_some_binaries

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#68163]
/kind cleanup
/sig testing
/priority important-longterm

This is a followup issue to address the "standard build globals" nit on https://github.com/kubernetes/kubernetes/pull/67971/files#r214488996

At the very least I think we shouldn't capture our custom env var.

Also think it'd be worth documenting the assumed variables in a list, similar to
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L352-L353

**Comment by BenTheElder** [comment]
cc @Katharine
