### ISSUE TITLE
Using Athens for Go deps

### ISSUE THREAD

**Issue by sahitpj** [kubernetes/kubernetes#68177]
**FEATURE REQUEST**:

Integrating Athens for go deps will allow for more reliability and stability. Will reduce go dependency related issues to a large extent

**Comment by BenTheElder** [comment]
/remove-sig scalability
/sig release
/sig testing
I don't think this is likely in the immediate future due to issues with kubernetes and go modules. CC @sigma

**Comment by sigma** [comment]
I just opened #68577 to clarify the path to go modules a bit.
