### ISSUE TITLE
apiserver panics "runtime error: index out of range"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#68172]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Colleagues made an extension server following the example.  I have a cluster that is partially broken.  I have not fully diagnosed all the issues.  But one of them is that the extension server is panicing.  Here is an example:
```
panic: runtime error: index out of range

goroutine 42 [running]:
k8s.io/apiserver/pkg/storage/etcd3.compact(0x1a23f80, 0xc4200d6400, 0xc420500f00, 0x19, 0x47, 0x19, 0x47, 0x0, 0x0)
	/myplace/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go:148 +0x89d
k8s.io/apiserver/pkg/storage/etcd3.compactor(0x1a23f80, 0xc4200d6400, 0xc420500f00, 0x45d964b800)
	/myplace/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go:122 +0x17b
created by k8s.io/apiserver/pkg/storage/etcd3.StartCompactor
	/myplace/src/k8s.io/apiserver/pkg/storage/etcd3/compact.go:63 +0x415
```

The that first line is https://github.com/kubernetes/apiserver/blob/8378ef881d4fa7d3ca5c5e7e5309592ec69b11e4/pkg/storage/etcd3/compact.go#L148 .  It reads the same in `master` now.

**What you expected to happen**:
I expected to get problems logged rather than panics.

**How to reproduce it (as minimally and precisely as possible)**:
I do not yet understand the problem well enough to produce a minimal demonstration.  But just looking at that line from a general golang perspective reveals two index operations, and there is no preceding code that tests their validity.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: local bare metal

- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS

- Kernel (e.g. `uname -a`): 4.4.0-133-generic

- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Can you provide the full invocation?

**Comment by liggitt** [comment]
There are a fair number of places that valid startup or construction arguments are assumed at runtime. It's possible we need to add more validation at startup. The invocation would help narrow down what input might be causing issues

**Comment by liggitt** [comment]
@jpbetz @gyuho can you comment on the expected responses from a compaction API call to etcd? the assumptions made by https://github.com/kubernetes/apiserver/blob/8378ef881d4fa7d3ca5c5e7e5309592ec69b11e4/pkg/storage/etcd3/compact.go#L148 are not valid in some cases

**Comment by gyuho** [comment]
@jpbetz @liggitt The compact logic looks correct.

> this panic is not at startup but rather some time later

Was there any restart or snapshot restore?

**Comment by liggitt** [comment]
> @jpbetz @liggitt The compact logic looks correct.

so all non-erroring compaction calls, successful or not, should return a response for which `resp.Responses[0].GetResponseRange().Kvs[0].Version` is valid?

**Comment by gyuho** [comment]
@liggitt 

> so all non-erroring compaction calls, successful or not, should return a response for which 

It's only valid, it `Succeeded` is false.

> if !resp.Succeeded {

That is, when `clientv3.Compare` condition is evaluated to false, we expect `clientv3.OpGet(compactRevKey),` to be run, so `len(resp.Responses[0].GetResponseRange().Kvs) > 0`.

**Comment by liggitt** [comment]
> It's only valid, it Succeeded is false.

ah, right. so that looks correct to you.

given that the panic *is* occurring, we should probably put range checks in and return an error if we don't see a non-zero length response, but it's concerning if we are seeing a response that should not be possible

**Comment by jpbetz** [comment]
The issue on the etcd side is https://github.com/etcd-io/etcd/pull/8813#issuecomment-344158430. This was fixed in etcd 3.1.11+ 3.2.10+ and 3.3.0+.

**Comment by liggitt** [comment]
Thanks. @MikeSpreitzer what version of etcd are you seeing this with?

**Comment by MikeSpreitzer** [comment]
The etcd image was quay.io/coreos/etcd:v3.0.17

There was no explicit etcd snapshot restore.  I am not sure how many meanings "restart" might have in this context.  I can not tell you whether the etcd container in the etcd pod was restarted.

**Comment by jpbetz** [comment]
@liggitt No, etcd community approved adding patch management support back to 3.1 but no further.
