### ISSUE TITLE
Minikube doesn't start on CentOS 7.5

### ISSUE THREAD

**Issue by blessedwithsins** [kubernetes/kubernetes#68175]
I am trying to run minikube on Windows 10 using VMware Workstation Pro via running a CentOS 7.5 VM. But when I try to start I get below error:

[root@kubernetesexam ~]# minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0902 09:58:43.471476    3224 start.go:305] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
[root@kubernetesexam ~]# 

**Environment**: Windows 10, VMware Workstation Pro, CentOS 7.5 VM
- Kubernetes version (use `kubectl version`): Kubernetes v1.10.0
- Cloud provider or hardware configuration: Windows 10 with 8GB RAM, 2.5 GB Dedicated to VM
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core) 
- Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64
- Install tools: 
- Others:

[minikube-error.txt](https://github.com/kubernetes/kubernetes/files/2342983/minikube-error.txt)

/sig minikube

**Comment by tao12345666333** [comment]
You can try:

```
minikube delete
minikube start
```

And try to add `--vm-driver` option to `minikube start`.

**Comment by blessedwithsins** [comment]
@tao12345666333 I have already tried that and it doesn't work. I tried to install using cloning Kubernetes repo but after i run command "make quick-release", it hung at "cluster/gce/gci/mounter".

**Comment by tao12345666333** [comment]
Can you try other vm-driver option? 

```
minikube start  --vm-driver="hyperv"
```

**Comment by blessedwithsins** [comment]
@tao12345666333 It's working now although i used VM driver as kvm2. Also, swapoff is required as it didn't start without doing so. Please close this issue.

**Comment by tao12345666333** [comment]
@blessedwithsins Congratulations.
