### ISSUE TITLE
normal events of statefulset blocked for long time by resynced events

### ISSUE THREAD

**Issue by YueHonghui** [kubernetes/kubernetes#68179]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
We have more than 10000 statefulsets in kubernetes. Every time statefulset controller resyncing, the normal events will be blocked to be processed for a long time(3~5min). After inspecting the metric and code of workqueue, I think the workqueue is filled with all the statefulsets sync event when informer resyncing. So, most of the normal events of statefulset or pods must wait for a long time. 
Maybe we can treat events triggered by resync(type `Sync`) as lower priority than normal events. To support this, event type should be passed down to `ResourceEventHandlerFuncs` and workqueue should support priority queues.

**What you expected to happen**:
The operation of statefulsets and normal events of pods should be processed immediately even when controller resyncing.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create large number of statefulsets
1. Delete pods when resyncing
1. Deleted pod will not be recreated for a long time

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7.3
- Kernel (e.g. `uname -a`): 4.10
- Install tools:
- Others:

**Comment by krmayankk** [comment]
statefulset resync period is 30sec which seems excessive https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set.go#L49

Deployment controller uses something in between 12hrs and 24 hrs as shown here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/apis/config/v1alpha1/defaults.go#L74 and https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L136

It seems we should modify the stateful to resync less often.  @kubernetes/sig-apps-bugs thoughts 

/assign @krmyankk

**Comment by YueHonghui** [comment]
@krmayankk We have updated the resync period to 24h. But this doesn't resolve the problem. Every time resync triggered, normal events will be blocked for a long time. This is a common problem related to resync implementation. One solution is to put events triggered by resync to a lower priority queue, but is seems a big change to current code base.

**Comment by krmayankk** [comment]
@YueHonghui i am also seeing the statefulset controller uses the default rate limiting queue which has limits for 10qps and bucket size of 100, can you try tweaking that and see if that helps ? Ideally we should make this configurable at command line ?

**Comment by YueHonghui** [comment]
@krmayankk Thank you for your help, I will inspect and analysis what role the rate limiting queue plays in this case. In the fork of our production version of k8s, we have exported many configuration to command line, the configurations are very useful. Back to the case, tuning configuration of rate limiting queue may not resolve the problem. To protect kube-apiserver, we must set a rate limit to the consumer side of queue. Normal events should be processed immediately but the events triggered by resync can be processed later. In current implementation, the two types of event share the same queue and even have no strategy of priority. Resyncing events will block the normal events regardless of what value the rate limit is, especially with a large num of statefulsets.

**Comment by ricky1993** [comment]
/reopen
We also have been troubled by this problem.
How about use a priority queue instead of a slice to implement https://github.com/kubernetes/kubernetes/blob/529255865d031b74a2f56e74a43dc29fd41361b1/staging/src/k8s.io/client-go/util/workqueue/queue.go#L26 ?
Then we can set resync event a low priority, and normal event can be processed immediately.
@lavalamp @liggitt

**Comment by YueHonghui** [comment]
@ricky1993 @liggitt @lavalamp  In master branch of statefulset controller, resync period is set to 0. It seems that resync is totally disabled. I don't know clearly whether resyncing strategy is safe to remove totally now.

**Comment by liggitt** [comment]
resyncing is not generally required. https://github.com/kubernetes/kubernetes/pull/79169 is open to allow multiple statefulset workers, which would also help throughput

**Comment by ricky1993** [comment]
> resyncing is not generally required. #79169 is open to allow multiple statefulset workers, which would also help throughput
It's ok to disable periodically resync. But think about another scenario.
When we restart controller, it will relist all the deployment, rs, etc. And it will hang for a while to processed all the objects (most of them didn't change at all), so the new event cannot be processed in time. We have about 20k rs in a cluster, every time we restart controller, the new request will delay for about 20mins. With priority queue, we can processed new event in high priority, or do you have any better suggestions? @liggitt

**Comment by ricky1993** [comment]
You can see the details #74397

**Comment by liggitt** [comment]
> With priority queue, we can processed new event in high priority, or do you have any better suggestions? @liggitt

Taking longer to warm up on restart for extremely large clusters is not unexpected.

The initial events on start are not considered resync events.

Prioritizing new events over all old events would allow starvation and potentially never processing some events, which is not desired.

**Comment by liggitt** [comment]
For very large clusters, I'd suggest increasing the number of parallel workers and the CPU/memory resources assigned to the controller manager. Long-term we will probably need to be able to shard controllers, but that effort has not started yet.

**Comment by ricky1993** [comment]
> For very large clusters, I'd suggest increasing the number of parallel workers and the CPU/memory resources assigned to the controller manager. Long-term we will probably need to be able to shard controllers, but that effort has not started yet.

Thanks for your suggestion, Jordon.
Now we have used a 64c 96g bare metal for the controller, and increase the worker for the controller. It still not work for me. I will try to seperate controller and deploy them to different machines.
I would be happy if long-term plan has any progress :)

**Comment by liggitt** [comment]
> Now we have used a 64c 96g bare metal for the controller, and increase the worker for the controller. It still not work for me.

https://github.com/kubernetes/kubernetes/pull/79169 will allow multiple workers for statefulsets... that is not available yet

**Comment by ricky1993** [comment]
> > Now we have used a 64c 96g bare metal for the controller, and increase the worker for the controller. It still not work for me.
> 
> #79169 will allow multiple workers for statefulsets... that is not available yet

I know, my case is replicasets and deployments, not statefulsets.
