### ISSUE TITLE
Unable to find k8s configuration file.

### ISSUE THREAD

**Issue by 1032231418** [kubernetes/kubernetes#68189]
Hello!
I developed it on Windows, but when I used the interface, I couldn't find the configuration file, and my path was good. Linux development is no problem.
![filenotfounderror](https://user-images.githubusercontent.com/5716348/44975589-7011c200-af95-11e8-8c63-c3c00ede18d3.png)

**Comment by 1032231418** [comment]
@charrywanganthony  have already been solved      https://github.com/papudatta/kubernetes_kubeadm

**Comment by benmoss** [comment]
I think this is not a Kubernetes issue, not sure what that repo you linked to is.
