### ISSUE TITLE
Conversion of Unstructured broken in apimachinery

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#68197]
Follow-up of https://github.com/kubernetes/kubernetes/issues/68035 which uncovered deep issues with Unstructured in apimachinery:

We have conversions to `__internal` in our handlers, e.g.

- create: https://github.com/kubernetes/kubernetes/blob/5f364a0b84669a2dc086a35292db088b912d1c3c/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go#L80
- update: https://github.com/kubernetes/kubernetes/blob/5f364a0b84669a2dc086a35292db088b912d1c3c/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go#L93

Still CustomResource no-op conversion works, somehow. Why?

One of the reasons (possibly among others) is that
- versioning decoders do not care much about GroupVersions, but mostly about type equality of target objects, compare https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L106
- passed GroupVersion in CR decoders is effectively ignored, compare 
  - for the handler scope serializer: https://github.com/kubernetes/kubernetes/blob/5b82745cafec1b8fb0d767fc33fa4609354d2cc0/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L614. Decoding a CR to `__internal` 
 should fail, but doesn't.

Maybe our main problem is that we don't have rigorous apimachinery tests using `Unstructured`, but many ad-hoc patches in many places to handle `Unstructured` in a good enough way to make it work with CustomResources.

**Comment by sttts** [comment]
The very same issue we found with UPDATE on scale subresources shows up in a simple GET: the object from storage is not converted. Hence, as soon as we switch to version specific validation, we validate the wrong object version against the schema.

**Comment by deads2k** [comment]
> The very same issue we found with UPDATE on scale subresources shows up in a simple GET: the object from storage is not converted. Hence, as soon as we switch to version specific validation, we validate the wrong object version against the schema.
> 
> In other words: all the code that claims to convert on read from storage seems to be broken.

That's a significant problem.  Adding @liggitt and @erictune in case they have ideas.

**Comment by mbohlool** [comment]
How does the test passes then? both Nop converter and webhook converter convert on read and write.

**Comment by mbohlool** [comment]
get test for nop converter: https://github.com/kubernetes/kubernetes/blob/d691748aa64376e4b90ae2c01aca14d1be2b442c/staging/src/k8s.io/apiextensions-apiserver/test/integration/basic_test.go#L163

I am not saying there is no problem, just saying conversion is happening during the life of request.

**Comment by liggitt** [comment]
> How does the test passes then?

One possibility is that conversion is happening on output to the rest response, not on input to the in-memory object the handler deals with. The in-memory version the handler has may be whatever version was read from storage (which isn't even necessarily the current storage version)

If that is the issue, that would cause problems for things like "patch", which expect the in-memory version the handler has and the user's patch to deal with the same schema and version.

**Comment by sttts** [comment]
> One possibility is that conversion is happening on output to the rest response

This ^^ happens.

And @liggitt mentions PATCH, @deads2k also just brought that up: if we start with webhook conversion, very probably this bug leads to broken CRUD for non-storage versions.

**Comment by liggitt** [comment]
If the crux of the issue is the in-memory version the handlers are dealing with, my first thought would be to make that part of the input to createHandler/updateHandler. The native handlers would indicate they wanted the in-memory object to be `schema.GroupVersion{Group: gv.Group, Version: runtime.APIVersionInternal}`, and the CRD handlers would indicate they wanted the in-memory object to be `schema.GroupVersion{Group: restGroup, Version: restVersion}`

**Comment by sttts** [comment]
> the convertor for each handler was constructed specifically for that handler

We are sure. We have distinc storage and handler scope objects even today. They are completely indepentently constructed (https://github.com/kubernetes/kubernetes/blob/5b82745cafec1b8fb0d767fc33fa4609354d2cc0/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L429)

> we'd need to reason through what an __internal unstructured object looks like (does it literally have apiVersion: <group>/__internal or does version info get stripped out and remain implicit in the convertor that deals with it?)

Both ways would work I expect. I don't have a strong opinion about either way, maybe tending slightly towards an empty version.

**Comment by guineveresaenger** [comment]
@sttts @liggitt since Code Freeze is _today_, this will need to be of `priority/critical-urgent` by tomorrow, or it will have to be dropped from the milestone. Please evaluate.

cc @lavalamp @deads2k

**Comment by lavalamp** [comment]
CRs have no hub (internal) type. Conversion can't happen without distinct source and dest versions.

If the code treats the "internal" type as being the storage version, then of course no conversion will happen on the etcd read.

I was kind of hoping we could find a solution for this without adding an "internal" type for CRs. (Because I would like to remove the internal type for builtins!)

E.g., what happens if we make the CR's "internal" version be the version to be served? Some other failure mode?

**Comment by sttts** [comment]
> If the code treats the "internal" type as being the storage version, then of course no conversion will happen on the etcd read.

No, it doesn't. Logically our code takes the handler scope version as internal, but does not call it `__internal` and keep using the real GVK.  We just have some duct-tape in place which was supposed to make this work, but it seems it never did (and we did not notice because the e2e tests showed the right version being returned by handlers.

> E.g., what happens if we make the CR's "internal" version [edit: by which I mean the in-memory version] be the version to be served? Some other failure mode?

IMO this is what we need to integrate cleanly with apimachinery. We should actually call it `__internal`, although actually it is the version being served (handler scope version). Compare discussion by @liggitt and me above.

**Comment by guineveresaenger** [comment]
/milestone clear
/priority important-soon
/remove-priority critical-urgent

This is related to [CRD webhook versioning feature](https://github.com/kubernetes/features/issues/598) which has been pushed back to v1.13.

**Comment by liggitt** [comment]
> IMO this is what we need to integrate cleanly with apimachinery. We should actually call it __internal, although actually it is the version being served (handler scope version). Compare discussion by @liggitt and me above.

This seems really odd once webhook conversion is introduced. Do you agree that the object sent to and received from the webhook convertor should not serialize `apiVersion: .../__internal`?

Would you envision the convertor for the v1beta1 handler asking the webhook to convert to version v1beta1, then stomping the apiVersion of the object the webhook returned to ".../__internal"? I'd rather identify the places the handlers are asking for conversion to __internal (appears to be ~3-4 places) and make that part of the request scope definition ("what version does this handler use internally?")

**Comment by deads2k** [comment]
> I'd rather identify the places the handlers are asking for conversion to __internal (appears to be ~3-4 places) and make that part of the request scope definition ("what version does this handler use internally?")

This seems like a good idea.
