### ISSUE TITLE
kubectl top pod is not working

### ISSUE THREAD

**Issue by splnanthakumar** [kubernetes/kubernetes#68193]
> /kind bug
@kubernetes/sig-contributor-experience-<group-suffix>
/sig scalability

i have tried "kubectl top pod" command in kubernetes cluster . but it gives the error as follows:

Error from server (ServiceUnavailable): the server is currently unable to handle the request (get services http:heapster:)

Kubernetes cluster info:
Kubernetes master is running at https://**********
Heapster is running at https://******:4**3/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://******:4**3/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

i have installed metric-server from this url "https://github.com/kubernetes-incubator/metrics-server"
used deploy/1.8

Please guide me to view my cpu and memory utilization of my pods using metric -server

Version:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3+coreos.0", GitCommit:"f1b890dbbf11abe58280b3ffe17d67749f5ae70e", GitTreeState:"clean", BuildDate:"2018-05-21T17:27:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"} 

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): core os 
- Kernel (e.g. `uname -a`):
$ uname -a
Linux ********** 4.9.24-coreos #1 SMP Tue ******* UTC 2017 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux
- Install tools:
- Others:

**Comment by Pingan2017** [comment]
you should install the heapster firstly
```
[root@hpa-vm:/home/yaml]$ kubectl top --help
Display Resource (CPU/Memory/Storage) usage.

The top command allows you to see the resource consumption for nodes or pods.

This command requires Heapster to be correctly configured and working on the server.
```

**Comment by wpf710** [comment]
I test it with my V1.10.5 ,since I don't have 1.10.3,   
it works

what's the output of `kubectl get po,svc -n kube-system`

**Comment by splnanthakumar** [comment]
kubectl get po, it gives the list of pods which are all running. 
svc - command not found

**Comment by wpf710** [comment]
![default](https://user-images.githubusercontent.com/265050/45088396-6d50d180-b13b-11e8-8bd9-af5fb04f61fe.png)

**Comment by wpf710** [comment]
`[root@node1 tmp]# kubectl get service -n kube-system
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
heapster               ClusterIP   10.103.27.106    <none>        80/TCP              1d
kube-dns               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP       7d
kubernetes-dashboard   ClusterIP   10.105.56.124    <none>        443/TCP             7d
monitoring-grafana     ClusterIP   10.99.103.252    <none>        80/TCP              1d
monitoring-influxdb    ClusterIP   10.105.134.105   <none>        8083/TCP,8086/TCP   1d
`

**Comment by splnanthakumar** [comment]
me@root-5795 ~ $ kubectl get po,svc -n kube-system
NAME                                        READY     STATUS             RESTARTS   AGE
pod/kube-apiserver-192.168.1.162            1/1       Running            1          54d
pod/kube-controller-manager-192.168.1.162   1/1       Running            3          54d
pod/kube-dns-c74b848d4-8qp94                3/3       Running            3          54d
pod/kube-dns-c74b848d4-b4bw6                3/3       Running            3          54d
pod/kube-proxy-192.168.1.162                1/1       Running            1          54d
pod/kube-scheduler-192.168.1.162            1/1       Running            1          54d
pod/metrics-server-55b6ff4cb7-5q6hb         0/1       CrashLoopBackOff   235        19h

NAME                     TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
service/heapster         ClusterIP   10.3.2.146   <none>        80/TCP          2d
service/kube-dns         ClusterIP   10.3.0.10    <none>        53/UDP,53/TCP   54d
service/metrics-server   ClusterIP   10.3.14.79   <none>        443/TCP         2d
