### ISSUE TITLE
Failed test operation in JSON Patch should return 4xx, not 500 Internal Server Error

### ISSUE THREAD

**Issue by felixfbecker** [kubernetes/kubernetes#68202]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Making a PATCH request to a resource (e.g. deployment) with an RFC6902 JSON Patch that contains a `test` operation that is false results in a 500 Internal Server Error with response body
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Testing value /resourceVersion failed",
    "code": 500
}
```

**What you expected to happen**:
The server should not apply the patch and return a 4xx status code so the client can react (e.g. update local state, retry). A `test` is commonly used as safe guard to ensure the resource is in the state it is expected to be when applying the patch (imagine updating an array index - if the resource changed in the meantime and the indexes were shifted the patch could have catastrophic consequences). Clients need to be able to react to this.

The most appropriate status code for this seems 409 Conflict, see  https://tools.ietf.org/html/rfc5789#section-2.2

>    Conflicting state:  Can be specified with a 409 (Conflict) status
>       code when the request cannot be applied given the state of the
>       resource.  For example, if the client attempted to apply a
>       structural modification and the structures assumed to exist did
>       not exist (with XML, a patch might specify changing element 'foo'
>       to element 'bar' but element 'foo' might not exist).

**How to reproduce it (as minimally and precisely as possible)**:
Make a PATCH request to a deployment with the content
```json
[{"op": "test", "path": "/metadata/resourceVersion", "value": "nottheresourceversion"}]
```
and Content-Type `application/json-patch+json`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.3
- Cloud provider or hardware configuration: Docker for desktop
- OS (e.g. from /etc/os-release): macOS
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

Related: https://github.com/kubernetes/kubernetes/issues/54423

**Comment by felixfbecker** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by CaoShuFeng** [comment]
replying: https://github.com/kubernetes/kubernetes/pull/68208#issuecomment-418381236

> #68202 was specifically about general JSON Patch test operations, not just against resourceVersion (I just used resourceVersion as an example).

Looks like https://github.com/kubernetes/kubernetes/pull/68208 doesn't fix this issue.
Do you have another example of this issue?

**Comment by felixfbecker** [comment]
Sure, just send a patch with
```json
[{"op": "test", "value": "notthename", "path": "/metadata/name"}]
```
any path reproduces the issue.

**Comment by CaoShuFeng** [comment]
I hope https://github.com/kubernetes/kubernetes/pull/68346 would be a fix.

**Comment by lavalamp** [comment]
These should probably return 409 conflict errors.
