### ISSUE TITLE
Upate import-boss restrictions 

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#68201]
`hack/verify-import-boss.sh` is a tool we use to reduce technical debt around rampant interdepencies between packages in the main k/k repository.

The tool uses a file `.import-restrictions` in some directories that verify-import-boss.sh then uses to check. The syntax for the file is here:
https://github.com/kubernetes/code-generator/blob/master/cmd/import-boss/main.go#L32-L52

We currently have the following `.import-restrictions` in the main k/k repository:
```
[dims@dims-mac 19:00] ~/go/src/k8s.io/kubernetes ⟩ find  . -name .import-res*
./cmd/kubeadm/.import-restrictions
./pkg/.import-restrictions
./pkg/api/testing/.import-restrictions
./pkg/client/clientset_generated/.import-restrictions
./pkg/controller/.import-restrictions
./pkg/kubectl/.import-restrictions
./pkg/kubemark/.import-restrictions
./pkg/printers/.import-restrictions
./pkg/printers/internalversion/.import-restrictions
./staging/src/k8s.io/apiserver/.import-restrictions
./staging/src/k8s.io/code-generator/cmd/lister-gen/.import-restrictions
```
What needs to be done?
- Open up the `.import-restrictions` file, check if `AllowedPrefixes` under different `Rules` are correct. 
  - The packages listed are still being used in the code under the pacakge
  - If there are outside packages that are used, but not listed under `AllowedPrefixes` then add those packages
- Possibly add new .import-restrictions for different directories under `/staging/src/k8s.io/` so we can be sure each directory under that is self-contained.
- If the .import-restrictions looks correct, then leave a comment in this issue so others don't duplicate the work. If you want to work on a specific file, leave a note so others don't spend their time on the same work.

Prior art (see how we did this in earlier PRs):
- https://github.com/kubernetes/kubernetes/pull/35148
- https://github.com/kubernetes/kubernetes/pull/53458
- https://github.com/kubernetes/kubernetes/pull/63740

/good-first-issue

**Comment by dims** [comment]
Also see longer discussion of how things can be split into multiple repos to gauge why this work is important:
https://github.com/kubernetes/kubernetes/issues/24343

**Comment by mkenigs** [comment]
I'll work on this

**Comment by dims** [comment]
@mkenigs please specify which files you are going to look at (or create), so others can pick up other work.

**Comment by saravanan30erd** [comment]
@dims @mkenigs  I ll take the below packages
```
./pkg/controller/.import-restrictions
./pkg/kubectl/.import-restrictions
```

**Comment by mkenigs** [comment]
./cmd/kubeadm/.import-restrictions
./pkg/.import-restrictions
./pkg/api/testing/.import-restrictions
./pkg/client/clientset_generated/.import-restrictions

**Comment by mrajashree** [comment]
@dims can I take up these ones since they don't seem to be taken up yet based on previous comments?
```
./pkg/kubemark/.import-restrictions
./pkg/printers/.import-restrictions
```

**Comment by mikedanese** [comment]
I don't understand the motivation of changes like these:

https://github.com/kubernetes/kubernetes/pull/68411

What does an import restriction like this solve? Import restrictions shouldn't be a per-package list. That defeats the purpose and will increase the churn in low level directories.

**Comment by mkenigs** [comment]
@mikedanese I think I included too many restrictions in #70406 and #70070, can you explain exactly which packages should be listed? It seems there are some packages not explicitly imported within a package that will cause ./hack/verify-import-boss.sh to fail.

**Comment by dims** [comment]
here's a script that helps identify stale prefixes

**Comment by mkenigs** [comment]
Where's the script?

**Comment by dims** [comment]
Whoops! https://gist.github.com/dims/384dea60754042f61d79233603034038
