### ISSUE TITLE
Horizontal Pod Autoscaler controller can process only 3 autoscalers per second.

### ISSUE THREAD

**Issue by krzysztof-jastrzebski** [kubernetes/kubernetes#68213]
BUG REPORT
/kind bug
**What happened**:
I created 800 Horizontal Pod Autoscaler and 800 Deployment.
**What you expected to happen**:
 HPA controller should update HPAs every 30 seconds but it updates HPAs every 250s
**How to reproduce it (as minimally and precisely as possible)**:
Create cluster with 800 HPAs and Deployments.

**Environment**:
- Head K8s version
- Cloud provider or hardware configuration:
- Cluster with 10 8-core nodes

**Comment by mwielgus** [comment]
Closing as not that informational. Will open a new one that clearly explains the problem.
