### ISSUE TITLE
modified subpath configmap mount fails when container restarts

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubernetes#68211]
/kind bug

**What happened**:
When a container uses a configmap which is mounted with the `subPath` option, the configmap is changed and then the container (but not the pod) restarts the mounting of the configmap fails:

```
# mount a single file into a folder with preexisting data
        volumeMounts:
        - name: extra-cfg
          mountPath: /etc/puppetlabs/puppetdb/conf.d/extra.ini
          subPath: extra.ini
```

    # change something in the configmap
    kubectl edit extra-cfg
    kubectl exec podname kill 1
    kubectl describe podname

>   Warning  Failed   5s                kubelet, kworker-be-intg-iz2-bap006  Error: failed to start container "puppetdb": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/b9ffd644-af98-11e8-a05e-246e96748774/volume-subpaths/extra-cfg/puppetdb/2\\\" to rootfs \\\"/var/lib/docker/overlay2/c8790b7f3f690c1ef7a582672e2d153062ff6b4ed1ee21aab1158897310fd3d1/merged\\\" at \\\"/var/lib/docker/overlay2/c8790b7f3f690c1ef7a582672e2d153062ff6b4ed1ee21aab1158897310fd3d1/merged/etc/puppetlabs/puppetdb/conf.d/extra.ini\\\" caused \\\"no such file or directory\\\"\"": unknown

(The pod this happens on consists of multiple containers, I have not tested yet if it also happens in a single container pod.)

One has to delete the pod to fix the problem.

**Environment**:
  Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

coreos 1800.7.0
docker 18.03.1

**Comment by juliantaylor** [comment]
minimal example:

```
---
apiVersion: v1
kind: Pod 
metadata:
  name: test-pod
spec:
  volumes:
  - configMap:
      name: extra-cfg
    name: extra-cfg
  containers:
  - name: test
    image: ubuntu:bionic
    command: ["sleep", "30"]
    resources:
      requests:
        cpu: 100m
    volumeMounts:
      - name: extra-cfg
        mountPath: /etc/extra.ini
        subPath: extra.ini
---
apiVersion: v1
data:
  extra.ini: |
    somedata
kind: ConfigMap
metadata:
  name: extra-cfg
```

deploy the pod, edit the configmap, wait for the 30 second sleep to complete and the container to restart, the restart will fail with the error above.

**Comment by inish777** [comment]
I have the same configuration and could reproduce this bug

**Comment by inish777** [comment]
Using findmnt on node with test-pod I can see
```
|-/var/lib/kubelet/pods/3dc49ca4-b046-11e8-978a-0e51a1d2416a/volume-subpaths/extra-cfg/test/0                                             /dev/xvda9[/var/lib/kubelet/pods/3dc49ca4-b046-11e8-978a-0e51a1d2416a/volumes/kubernetes.io~configmap/extra-cfg/..2018_09_04_13_27_17.387923275/extra.ini//deleted]
```
Updated configmap is actually placed at ```/var/lib/kubelet/pods/3dc49ca4-b046-11e8-978a-0e51a1d2416a/volumes/kubernetes.io~configmap/extra-cfg/..2018_09_04_13_31_59.038960565/extra.ini```

**Comment by nikopen** [comment]
Issue is reproducable. k8s 1.9.10, docker 17.12.1-ce

I have found another behaviour when using subPath:

in /var/lib/kubelet/pods/<pod-string>/, there are two places where the configmap file lives:
1. in `/volumes/kubernetes.io~configmap/<volumename>/<filename>
2. in `/volume-subpaths/<volumename>/<podname>/0

1. is the configmap object as is imported at pod creation time, 
and 2. is the file within the pod that *changes* if you change it within the pod.

So whether you edit the configmap object OR the file within the pod, and then restart the pod - the two files will be different. 

In my repro, I'm editing the file within the container and then kill it. This causes the pod to get stuck in a crashloopbackoff.

While this happens I'm tracking the following for the first occurrence:

overlay2 filesystem:

```
$ inotifywait -r -m overlay2

16:41:17 overlay2/21931d3d54082ac670e2915e4caad2e9a76ab55952459a240f0bd6f66f90ce15/diff/ CREATE trackmefile
```

this is the attempt to move the 'trackmefile' (configmap's file with data) to the new container, but here it's empty. it doesn't gets any content, and the directory is deleted after about 15 seconds, when the pod crashloops again.


docker daemon logs:

```
16:41:17 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:17+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e/shim.sock" debug=false module="containerd/tasks" pid=79610
16:41:17 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:17+02:00" level=info msg="shim reaped" id=867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e module="containerd/tasks"
16:41:17 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:17.993101301+02:00" level=error msg="stream copy error: reading from a closed fifo"
16:41:17 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:17.993182474+02:00" level=error msg="stream copy error: reading from a closed fifo"
16:41:18 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:18.080908749+02:00" level=error msg="867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e cleanup: failed to delete container from containerd: no such container"
16:41:18 node-4.kubernetes-misc.preview.ams1. dockerd[102444]: time="2018-10-01T16:41:18.080998550+02:00" level=error msg="Handler for POST /v1.31/containers/867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e/start returned error: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/lib/kubelet/pods/be21f5d6-c587-11e8-a5c1-005056b79850/volume-subpaths/trackmevolume/test4/0\\\\\\\" to rootfs \\\\\\\"/virtual/docker/overlay2/21931d3d54082ac670e2915e4caad2e9a76ab55952459a240f0bd6f66f90ce15/merged\\\\\\\" at \\\\\\\"/virtual/docker/overlay2/21931d3d54082ac670e2915e4caad2e9a76ab55952459a240f0bd6f66f90ce15/merged/trackmefile\\\\\\\" caused \\\\\\\"no such file or directory\\\\\\\"\\\"\": unknown"

```

It tries to mount the file from the `subpath` directory to `overlay2/<longstring>/merged`, but only an empty husk is located at `overlay2/<longstring>/diff` 



kubelet daemon logs:

```
16:41:18 node-4.kubernetes-misc.preview.ams1. kubelet[800]: E1001 16:41:18.083593     800 remote_runtime.go:209] StartContainer "867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e" from runtime service failed: rpc error: code = Unknown desc = failed to start container "867aa9738669c5c6f4763f8585d195abc6a753c8a43a36d5dd72822eb102151e": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/be21f5d6-c587-11e8-a5c1-005056b79850/volume-subpaths/trackmevolume/test4/0\\\" to rootfs \\\"/virtual/docker/overlay2/21931d3d54082ac670e2915e4caad2e9a76ab55952459a240f0bd6f66f90ce15/merged\\\" at \\\"/virtual/docker/overlay2/21931d3d54082ac670e2915e4caad2e9a76ab55952459a240f0bd6f66f90ce15/merged/trackmefile\\\" caused \\\"no such file or directory\\\"\"": unknown

```
same message is printed for kuberuntime_manager.go:734 , pod_workers.go:186,  kuberuntime_manager.go:514

kubelet/pods/<podid>/ filesystem:

```
$ inotifywait -r -m .

 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ OPEN,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ OPEN,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/ OPEN,ISDIR ..2018_10_01_14_39_04.003765758
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ OPEN,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ CLOSE_NOWRITE,CLOSE,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ CLOSE_NOWRITE,CLOSE,ISDIR 
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/ ACCESS,ISDIR ..2018_10_01_14_39_04.003765758
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ OPEN trackmefile
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/ ACCESS,ISDIR ..2018_10_01_14_39_04.003765758
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/ CLOSE_NOWRITE,CLOSE,ISDIR ..2018_10_01_14_39_04.003765758
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ CLOSE_NOWRITE,CLOSE,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS trackmefile
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ CLOSE_NOWRITE,CLOSE trackmefile
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ OPEN namespace
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ ACCESS namespace
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ CLOSE_NOWRITE,CLOSE namespace
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ OPEN token
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ CREATE,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ATTRIB,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ ACCESS token
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ CLOSE_NOWRITE,CLOSE token
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ OPEN ca.crt
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ ACCESS ca.crt
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ OPEN,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:15  ./volumes/kubernetes.io~secret/default-token-rghx6/..2018_10_01_14_39_04.003765758/ CLOSE_NOWRITE,CLOSE ca.crt
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ CREATE ..data_tmp
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ CLOSE_NOWRITE,CLOSE,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ MOVED_FROM ..data_tmp
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ MOVED_TO ..data
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ OPEN,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ OPEN,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ DELETE trackmefile
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ ACCESS,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ CLOSE_NOWRITE,CLOSE,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_39_03.227338331/ CLOSE_NOWRITE,CLOSE,ISDIR 
 16:41:15  ./volumes/kubernetes.io~configmap/trackmevolume/ DELETE,ISDIR ..2018_10_01_14_39_03.227338331
 16:41:16  ./containers/test4/ OPEN 1402258e
 16:41:16  ./containers/test4/ CLOSE_NOWRITE,CLOSE 1402258e
 16:41:17  ./ MODIFY etc-hosts
 16:41:17  ./ OPEN etc-hosts
 16:41:17  ./ MODIFY etc-hosts
 16:41:17  ./ CLOSE_WRITE,CLOSE etc-hosts
 16:41:17  ./containers/test4/ CREATE 5bc2fca2
 16:41:17  ./containers/test4/ OPEN 5bc2fca2
 16:41:17  ./containers/test4/ CLOSE_WRITE,CLOSE 5bc2fca2
 16:41:17  ./containers/test4/ ATTRIB 5bc2fca2
 16:41:18  ./containers/test4/ OPEN 5bc2fca2
 16:41:18  ./containers/test4/ CLOSE_NOWRITE,CLOSE 5bc2fca2
 16:41:18  ./containers/test4/ OPEN 1402258e
 16:41:18  ./containers/test4/ CLOSE_NOWRITE,CLOSE 1402258e
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/ OPEN,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ OPEN,ISDIR 
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ ACCESS,ISDIR 
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/ ACCESS,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ ACCESS,ISDIR 
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/ CLOSE_NOWRITE,CLOSE,ISDIR ..2018_10_01_14_41_15.703606290
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ CLOSE_NOWRITE,CLOSE,ISDIR 
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ OPEN trackmefile
 16:41:18  ./volumes/kubernetes.io~configmap/trackmevolume/..2018_10_01_14_41_15.703606290/ ACCESS trackmefile
```

**Comment by nikopen** [comment]
I can repro this on minikube v1.11.3 with cri-o. Not sure how reliable it is or what version of cri-o it runs, but it's the same symptom.

**Comment by bjhaid** [comment]
this seems related to:

https://github.com/moby/moby/issues/37083

**Comment by qiujian16** [comment]
We meet this error also when using secret subpath. We use kubernetes v1.11.0 and docker 18.03.

**Comment by lukemassa** [comment]
I saw this issue with kubernetes v1.12.4 and docker 18.09.0. (I opened kubernetes/kubernetes#72699 which I will now close as a dupe)

**Comment by Thoro** [comment]
Also have this issue with v1.12.2, haven't had it before with < 1.9 I believe

very annoying!

**Comment by Zero-2** [comment]
I have the same issue with docker 1.11.5 using AKS.
I found a workaround using **projected** key for volumes definition.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  namespace: test-cfg
data:
  common1.json: |
    {
      "logger": {
        "enabled": true,
        "level": "info",
        "extreme": false,
        "stream": "stdout"
      }
    }
  common2.json: |
    {
      "test": 4         
    }
---
apiVersion: v1
kind: Pod 
metadata:
  name: issue
  namespace: test-cfg
spec:
  volumes:
  - name: conf-volume
    configMap:
      name: test-configmap
  containers:
  - name: test
    image: ubuntu:bionic
    command: ["sleep", "30"]
    resources:
      requests:
        cpu: 100m
    volumeMounts:
      - name: conf-volume
        mountPath: /etc/common1.json
        subPath: common1.json
      - name: conf-volume
        mountPath: /etc/common2.json
        subPath: common2.json
---
apiVersion: v1
kind: Pod 
metadata:
  name: working
  namespace: test-cfg
spec:
  volumes:
  - name: conf-volume
    projected:
      sources:
      - configMap:
          name: test-configmap
          items:
            - key: common1.json
              path: common1.json
            - key: common2.json
              path: common2.json
  containers:
  - name: test-container
    image: ubuntu:bionic
    imagePullPolicy: "Always"
    resources:
      requests:
        cpu: 100m
    volumeMounts:
      - name: conf-volume
        mountPath: /test
    command: ["sleep", "30"]
```

With this configuration , Issue pod will not restart, instead working pod will work.
Steps are the same as described [here](https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-418259434)

**Comment by teijinyer** [comment]
> this seems related to:
> 
> [moby/moby#37083](https://github.com/moby/moby/issues/37083)

docker fixed this bug in the  18.06.03-ce , but  I also  saw this issue with kubernetes v1.13.2  and docker 18.06.03-ce

**Comment by yehaifeng** [comment]
I get the same issue in openshit 1.13, kubernetes 1.11.0
When pod restart and then mount fail.

Jul 01 18:45:48 paas-node010002.99bill.com origin-node[54267]: E0701 18:45:48.898167   54267 remote_runtime.go:209] StartContainer "c442998c576878395b30d2c831c3d42fbdbf75171b21a22ccde0e1141fdd3671" from runtime service failed: rpc error: code = Unknown desc = failed to start container "c442998c576878395b30d2c831c3d42fbdbf75171b21a22ccde0e1141fdd3671": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/origin/openshift.local.volumes/pods/41a4791b-5470-11e9-b356-005056b6696f/volume-subpaths/start/smsfinal-gzdlinfo-gateway/2\\\" to rootfs \\\"/var/lib/docker/overlay2/0f3564390916e039400e747e369c869db52cf32f4acb1aeb27e4f8ff961ab8a3/merged\\\" at \\\"/var/lib/docker/overlay2/0f3564390916e039400e747e369c869db52cf32f4acb1aeb27e4f8ff961ab8a3/merged/opt/oracle/start.sh\\\" caused \\\"no such file or directory\\\"\""

**Comment by gbraxton** [comment]
Issue seen on k8s 1.14.3, docker 18.06.3-ce, CoreOs Container Linux 2135.5.0 with subPath from secret in the same directory where another secret has a subPath

**Comment by JacobHenner** [comment]
/reopen
/remove-lifecycle rotten

Seeing this on:

```
 Kernel Version:             4.14.154-128.181.amzn2.x86_64
 OS Image:                   Amazon Linux 2
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.9
 Kubelet Version:            v1.14.7-eks-1861c5
```

**Comment by nagstaku** [comment]
Also getting this error -- deleting and redeploying fixed

geocoding.yml being a subpath mounted configmap:

Message:      OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/8e69d0fe-28ab-4c18-b1c3-1fbe26d5b71c/volume-subpaths/places-config/master/0\\\" to rootfs \\\"/var/lib/docker/overlay2/76a1cbe299736fb65a83ecc1e772f7bdf788f6a7d8f5accb1d88f14cb316355f/merged\\\" at \\\"/var/lib/docker/overlay2/76a1cbe299736fb65a83ecc1e772f7bdf788f6a7d8f5accb1d88f14cb316355f/merged/configs/geocoding.yml\\\" caused \\\"no such file or directory\\\"\"": unknown

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by djsly** [comment]
Can we get this issue reopened ?

**Comment by ottoyiu** [comment]
Can still replicate this with k8s 1.14.8 and Docker 19.03.1

**Comment by Alcatros** [comment]
Just had this in production, anyone knows how i can fix this ?

**Comment by juliantaylor** [comment]
To work around the problem ensure that your deployments recreate the pods when you configmaps change, for example by adding a checksum of the configmaps to the annotations of the deployment/statefulset pod template.

**Comment by DarthSlider** [comment]
We have exactly the same problem even without the modification of configmap.
If container fails (just kill PID 1 in the container) it can't start. 
Restarting whole pod works.

Removed subpath and mounted configmap to separate dir and the problem is gone.
k8s 1.16.2
docker 19.3.2

**Comment by micmax93** [comment]
We are also experiencing this issue (GKE with k8s 1.15 & 1.16).
As a workaround we have used slightly simpler version of workaround shown by @Zero-2 with items field for ConfigMapVolumeSource instead of using projected volume, for example:
```
volumes:
- name: app-config
  configMap:
    name: app-config
    items:
    - key:  config.json
      path: config.json
``` 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#configmapvolumesource-v1-core

**Comment by bavarianbidi** [comment]
Can reproduce the issue with the example from [above](https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-467032048) in three different environments.

* k8s `1.18.3` with `containerd://1.3.4`
* k8s `1.17.6` with `containerd://1.3.4`
* k8s `1.16.6` with `docker://19.3.3`

Steps to reproduce:
1. apply example from [above](https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-467032048)
1. edit content of the configmap (`kubectl edit cm test-configmap` or edit file and apply again)
1. watch the pods...

using `.spec.volumes.projected` works fine where `.spec.volumes.configMap` lead to this issue

**Comment by JasonRD** [comment]
any progress？

**Comment by nagstaku** [comment]
Happened for me again today with k8s 1.17

**Comment by k3a** [comment]
nagstaku:  Please read the task closing reason. It was fixed by #89629 and is part of k8s v1.19.0-rc.0 or newer. Until then, use #89629 workaround.

**Comment by cbf123** [comment]
has anyone confirmed whether the fix works when using containerd directly on current kubernetes?  It doesn't seem to work on 1.18.1.

**Comment by JasonRD** [comment]
I think you should check the latest release version.
在 2020年8月7日 +0800 06:08，Chris Friesen <notifications@github.com>，写道：

**Comment by qixiaobo** [comment]
> has anyone confirmed whether the fix works when using containerd directly on current kubernetes? It doesn't seem to work on 1.18.1.

We use 1.16 also meet this problem~

**Comment by teppokauppinen** [comment]
We had this issue in AWS EKS today

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hagel86** [comment]
Any reason this was closed? Looks like it's still an issue.

**Comment by cbf123** [comment]
> Any reason this was closed? Looks like it's still an issue.

It was closed because https://github.com/kubernetes/kubernetes/pull/89629 was submitted against the development branch.  But you're still going to see the problem on older versions unless a fix is backported.

And as I mentioned in https://github.com/kubernetes/kubernetes/issues/93691 I think the backport to 1.18.1 was buggy, which makes me wonder about other versions.

**Comment by fzu-huang** [comment]
Is there a better solution in versions before v1.19？

**Comment by silenceper** [comment]
same issue at k8s v1.20.2
