### ISSUE TITLE
kubectl cp does not accept wild cards

### ISSUE THREAD

**Issue by alfanse** [kubernetes/kubernetes#68222]
**FEATURE REQUEST**
/sig cli

As a paranoid admin,
I would like to take a manual backup of all /*.xml files in a folder (think Jenkins)
so that I can preserve a snapshot of the config

e.g. `kubectl cp <namespace>/$jenkins_master_pod:/var/jenkins_home/*.xml .`

**Environment**:
- Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"

Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AKS (Azure)
- OS (e.g. from /etc/os-release): Mac
- Kernel (e.g. `uname -a`):  Darwin Kernel Version 17.4.0

**Comment by bizzard4** [comment]
+1 As I would really like to use wildcard or regex with my copy command

**Comment by dixudx** [comment]
/assign

I have a handy fix for this, will submit it after fully testing.

**Comment by dixudx** [comment]
@alfanse  @bizzard4 Please help verified whether #72641 works.

**Comment by tuminoid** [comment]
This does not work. I'm on 1.14.2.

From container to host:
```
$ kubectl cp consul-5d98b69458-w4tzm:/entry*.sh .
tar: Removing leading `/' from member names
tar: /entry*.sh: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

From host to container (where * expands to 2 files at least):
```
$ kubectl cp * consul-5d98b69458-w4tzm:/
error: one of src or dest must be a remote file specification
```
