### ISSUE TITLE
kubectl --server using certificate-authority-data from wrong context

### ISSUE THREAD

**Issue by schweikert** [kubernetes/kubernetes#68221]
/kind bug

**What happened**:
I logged in to a gcloud GKE cluster, and then executed an unrelated kubectl command towards our on-premise cluster like this:

    kubectl --token=xxx --server=https://out-cluster.our-domain apply -f myresource.yaml 

**What you expected to happen**:

kubectl to work normally (instead of producing a x509 certificate error).

**How to reproduce it (as minimally and precisely as possible)**:

The kubectl command produced a certificate error:

    Unable to connect to the server: x509: certificate signed by unknown authority

The problem was that my .kube/config's current-context pointed to the gke cluster with a "certificate-authority-data" parameter set. Considering that I specified another --server, I wouldn't expect that certificate-authority-data specification to be effective.

**Anything else we need to know?**:

I think that kubectl should try to match the correct context, and not use the "current-context" when the --server parameter is given.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
  - GKE
  - OpenShift with a certificate signed by my company's internal CA

- OS (e.g. from /etc/os-release):

Red Hat Enterprise Linux 7.4

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
> Considering that I specified another --server, I wouldn't expect that certificate-authority-data specification to be effective.

That is the specified behavior. Setting --server overrides the url, but maintains the rest of the data read from the current context. If you want to use a different cluster definition, specify `--cluster`

/close

**Comment by schweikert** [comment]
@liggitt thanks for the tip and sorry for the noise. I guess I should have asked first on the slack channel or something.

**Comment by kvaps** [comment]
It would be nice to specify cluster using only server url, is there any trick for that?
