### ISSUE TITLE
GKE tests failing in release-1.11-blocking

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#68220]
Cluster creation failing in the following tests:
- gce-cos-1.11-alphafeatures
- gke-cos-1.11-default
- gke-cos-1.11-slow
- gke-cos-1.11-serial
- gke-cos-1.11-ingress
- gke-cos-1.11-reboot
- gke-device-plugin-gpu-1.11

This needs to be fixed in order to unblock releasing 1.11.3

cc @krzyzacy @BenTheElder @kubernetes/sig-gcp-test-failures @kubernetes/sig-testing

**Comment by spiffxp** [comment]
related: https://github.com/kubernetes/kubernetes/issues/67862

**Comment by krzyzacy** [comment]
hummm? `ERROR: (gcloud.container.clusters.create) ResponseError: code=503, message=The service is currently unavailable` looks like something's borked on Monday.

/assign @dashpole 
(assign to dev oncall to take a look here)

**Comment by dashpole** [comment]
ack.  I am taking a look.  Will post updates here

**Comment by dashpole** [comment]
The issue has been resolved.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-release-1.11-all#gke-cos-1.11-default looks they are back to normal, thanks @dashpole !

/close
