### ISSUE TITLE
API Server should return 4xx for JSON Patch operation that is not allowed instead of 200

### ISSUE THREAD

**Issue by felixfbecker** [kubernetes/kubernetes#68225]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
If you make an RFC6902 JSON Patch request to the server that contains an operation that is not allowed, for example adding an arbitrary property to a deployment.
The server returns the unchanged resource with a 200 OK.

**What you expected to happen**:

200 OK signals that all operations as stated by the client were applied successfully, which they were clearly not, as the returned object does not have the `arbitrary` property.

422 Unprocessible Entity seems the most appropriate here:

> Unprocessable request:  Can be specified with a 422 (Unprocessable
>       Entity) response ([RFC4918], Section 11.2) when the server
>       understands the patch document and the syntax of the patch
>       document appears to be valid, but the server is incapable of
>       processing the request.  This might include attempts to modify a
>       resource in a way that would cause the resource to become invalid;
>       for instance, a modification to a well-formed XML document that
>       would cause it to no longer be well-formed.  There may also be
>       more specific errors like "Conflicting State" that could be
>       signaled with this status code, but the more specific error would
>       generally be more helpful.

https://tools.ietf.org/html/rfc5789#section-2.2

**How to reproduce it (as minimally and precisely as possible)**:
PATCH a deployment with `ContentType: application/json-patch+json` and body
```json
[{"op": "add", "value": 123, "path": "/arbitrary"}]
```

**Anything else we need to know?**:

Related https://github.com/kubernetes/kubernetes/issues/68202, https://github.com/kubernetes/kubernetes/issues/68224, https://github.com/kubernetes/kubernetes/issues/54423, 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): macOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by felixfbecker** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Once you submit a semantically valid patch, the server response is identical in behavior to fetching the object, applying the patch yourself, then submitting the resulting JSON as an update. Unknown fields are dropped by the API server on update

/close
