### ISSUE TITLE
interactive CLI shell for kubectl

### ISSUE THREAD

**Issue by zenglian** [kubernetes/kubernetes#68226]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
Type `kubectl ...` commands in bash shell, there is no auto-complete.

**What you expected to happen**:
- type `kubectl` in a OS shell (e.g., bash), a shell opens (like spark-shell)
- `kubectl` is omitted for every command
- **auto-complete**   e.g., when you type a space, a dropdown list of `apply|create| delete|get...` etc is displayed; when you select `get`, it displays a dropdown of `pod|service|..` etc; when you select `pod`, it displays the pod names list. 
- immediate syntax checking.

**Comment by gtseres** [comment]
There is something similar to what you are describing that has been implemented [here](https://github.com/cloudnativelabs/kube-shell).

**Comment by zenglian** [comment]
awsome!

**Comment by obeyda** [comment]
this would be really useful, maybe something like [azure cli interactive mode](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest)

/reopen
/remove-lifecycle rotten
