### ISSUE TITLE
in-tree cloud provider README needs updated

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#68234]
The https://git.k8s.io/kubernetes/pkg/cloudprovider/README.md needs updating to be in line with community agreed trajectory for the movement of cloud provider code out of k/k.  For example the current statement:

```
Deprecation Notice: This directory has entered maintenance mode and will not be accepting new providers. Cloud Providers in this directory will continue to be actively developed or maintained and supported at their current level of support as a longer-term solution evolves.
```

This statement is approximately 16 months old and implies there is still ambiguity, where there is now a much more clear plan which should be clearly communicated to those who might waste their time investing work in modifying something in this directory.  The situation is one increasingly past maintenance mode, with out-of-tree implementations the goal in the 1.13 cycle followed by removal of in-tree provider code a few cycles later.

See also discussion on slack: https://kubernetes.slack.com/messages/C718BPBQ8/ 

/kind cleanup
/priority important-soon
/sig cloud-provider
/assign @andrewsykim

**Comment by andrewsykim** [comment]
Thanks for the reminder Tim, sorry this fell off my radar, will put together a PR today :)

**Comment by andrewsykim** [comment]
/remove-lifecycle rotten

Need to update the README again so link out to the enhancement issues per cloud provider.

**Comment by andrewsykim** [comment]
@tpepper PTAL https://github.com/kubernetes/kubernetes/pull/72562 :)

**Comment by tpepper** [comment]
awesome
