### ISSUE TITLE
update doc.go in staging/ repositories

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#68231]
- Look at one of the directories under staging/src/k8s.io/ (Please don't pick more than one directory for one PR as it will cause issues for reviewers)
- Find all the files named `doc.go` (example find staging/src/k8s.io/client-go/ -name doc.go)
- See the following link it has a `// import "k8s.io/client-go/tools/remotecommand"` this tells tools how this package needs to be imported. So we should ensure that each doc.go has an import
   https://github.com/kubernetes/kubernetes/blob/1fc36a5743bc02d62ddaac6cd41b71f0ef191ce2/staging/src/k8s.io/client-go/tools/remotecommand/doc.go#L20
- Add a description appropriate to the package (similar to the one below)
   https://github.com/kubernetes/kubernetes/blob/1fc36a5743bc02d62ddaac6cd41b71f0ef191ce2/staging/src/k8s.io/client-go/tools/remotecommand/doc.go#L17-L19
- Look through sub directories and see if there are any other important directories that are likely to be used by outside users and add a doc.go

Why are we doing this?
- We perfer to use vanity urls instead of directly using github.com to refer to code, so this helps ensure that tools honor our wish. See https://golang.org/doc/go1.4#canonicalimports
- It would be good to have some package level documentation since these directories under staging/ are meant to be for use by folks outside of kubernetes github org.

/good-first-issue

**Comment by noqcks** [comment]
currently working my through `staging/src/client-go/` 

Not going to use / assign since there could be a number of PRs for this issue.

**Comment by wilstam** [comment]
May I try on staging/src/k8s.io//sample-apiserver?

**Comment by nikhita** [comment]
IIUC this means that there needs to be a `doc.go` even at the root of the repo? Then how does `go get k8s.io/client-go/...` work? :thinking:

**Comment by palash25** [comment]
Hi, can I make a PR for this directory https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/csi-api/pkg/client/clientset/versioned/doc.go  ?

**Comment by nikhita** [comment]
I guess this is still not done, https://github.com/kubernetes/kubernetes/pull/76481 was supposed to partially fix this issue.

/reopen
