### ISSUE TITLE
master/staging/README.md is out of date

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#68235]
List of directories in:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io

does not match the list here:
https://github.com/kubernetes/kubernetes/tree/master/staging

/good-first-issue

**Comment by stantonxu** [comment]
@dims , if nobody has been working on it, can I take this one?

**Comment by stantonxu** [comment]
One quick question, @dims 

While working on it, I find that there are not corresponding repos for the following staging areas. Where should we point them to?

`cli-runtime`
`kube-controller-manager`
`kube-proxy`
`kube-scheduler`
`kubelet`
`sample-cli-plugin`

**Comment by neolit123** [comment]
/sig architecture
?

**Comment by neolit123** [comment]
@stantonxu that's actually a bit of a problem, because some of the components don't have repos yet.
i think what can be done for now is to list all the components but don't have links on some of them.

the alternative is to wait for the new resos, which might take a while.

**Comment by stantonxu** [comment]
@neolit123 , thank you for your reply. I will leave those don't have repos as plain text, and link those which have repos.

**Comment by luxas** [comment]
We're planning to create the repos in a matter of days: https://github.com/kubernetes/org/issues/56.
We might just let the PR wait for those. We're in code freeze more so the PR wouldn't merge in about a month in any case.
