### ISSUE TITLE
`--dry-run` did not catch cannot capture "targetAverageUtilization and targetAverageValue cannot co-exist issue"

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/kubernetes#68240]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When deploy `HorizontalPodAutoscaler` object, I have met this error:
```
The HorizontalPodAutoscaler "indexer" is invalid: spec.metrics[0].resource.targetAverageValue: Forbidden: may not set both a target raw value and a target utilization
make: *** [__deploy-only] Error 1
Script failed with status 2
```

But the validation seems working fine:
```
$ kubectl apply --dry-run --validate=true -f infra/indexer-hpa.yaml
horizontalpodautoscaler.autoscaling "indexer" configured (dry run)
```

**What you expected to happen**:
Expecting the validation throws the same error

**How to reproduce it (as minimally and precisely as possible)**:
Create a `HorizontalPodAutoscaler` yaml file with both `targetAverageValue` and `targetAverageUtilization` in the ResourceMetrics.

**Anything else we need to know?**:
The validation lines are in here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/validation/validation.go#L246-L252

```
if src.Target.AverageUtilization == nil && src.Target.AverageValue == nil {
  allErrs = append(allErrs, field.Required(fldPath.Child("target").Child("averageUtilization"), "must set either a target raw value or a target utilization"))
}

if src.Target.AverageUtilization != nil && src.Target.AverageValue != nil {
  allErrs = append(allErrs, field.Forbidden(fldPath.Child("target").Child("averageValue"), "may not set both a target raw value and a target utilization"))
}
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:29:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): macOS Sierra 10.12.6

**Comment by liggitt** [comment]
client side dry run does not (and can not) run server-side validations. 

ability to run server-side dry-run is in progress, but will likely require a different flag 

cc @apelisse

**Comment by chenrui333** [comment]
I see, that makes sense.

**Comment by apelisse** [comment]
Orthogonal-ly, is that a "oneof" problem?

**Comment by roycaihw** [comment]
cc @jennybuckley

**Comment by apelisse** [comment]
I suspect we can close this one now that `apply --server-dry-run` is beta. Also the one-of thing was just a side note.
