### ISSUE TITLE
The openapi generation should be distinct from API type violation checking?

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#68243]
Right now, if you want to get a k8s type checked for API violations (right now only checking that the struct field name in `CapitalCase` matches the json name in `camelCase`), you must register the API types for openapi generation with the `// +k8s:openapi-gen=true` tag in a `doc.go` file. For the use case of ComponentConfig types (ref: kubernetes/community#2354), that aren't served by an API server, we don't need openapi generation per se, but want the api rules checking for tracking violations in a central place (with dedicated reviewers). Should we somehow decouple these?

cc @kubernetes/sig-api-machinery-misc @thockin @stewart-yu 
/kind cleanup

**Comment by roycaihw** [comment]
cc @roycaihw
