### ISSUE TITLE
Testing plan for ComponentConfig types

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#68244]
/kind cleanup

As part of kubernetes/community#2354, it is stated that we need a set of tests for each set of types. Some high-level examples:
 - Roundtrip testing with fuzzing (testing conversions)
 - Defaulting unit tests
 - Validation unit tests
 - Standardized naming and API group setup testing (unit tests for the ComponentConfig conventions)
 - API group naming (`*.k8s.io`), type field naming (field name should match JSON name with lowercased first letter), and that internal types shouldn't have JSON tags

/assign @luxas @stewart-yu 
cc @kubernetes/sig-api-machinery-feature-requests @thockin @jbeda @dims 
/milestone v1.13

**Comment by stewart-yu** [comment]
Add `kube-controller manager` API round trip test done:https://github.com/kubernetes/kubernetes/pull/68461[https://github.com/kubernetes/kubernetes/pull/68461](https://github.com/kubernetes/kubernetes/pull/68461)

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by stewart-yu** [comment]
Yeah, on the plan, will finish ASAP
Thanks

**Comment by nikopen** [comment]
Code slush is today, and this is a cleanup item thus not so important for the release itself

@stewart-yu what's the status on it? It can be pushed for the future, no problem.

**Comment by nikopen** [comment]
Moving this to v1.14 as PRs seem a bit big and we're near code freeze

/milestone v1.14

**Comment by luxas** [comment]
@nikopen Yes, v1.14 is correct for this one

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will this be implemented in the following week??

**Comment by soggiest** [comment]
Hello @luxas we're in code freeze for 1.14. There are a couple of PRs that are referencing this issue that are open. Can we move this issue and the PRs to 1.15?

**Comment by stewart-yu** [comment]
move to 1.15 please, thanks  for your reminder @soggiest

**Comment by dims** [comment]
/milestone v1.16

same situation as before we kicked it from 1.14->1.15 ...

**Comment by xmudrii** [comment]
@luxas Hello! I'm bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by neolit123** [comment]
cc @mtaufen @stealthybox

**Comment by mtaufen** [comment]
@tahsinrahman recently started working on this, not sure if we'll merge code by the deadline or not

**Comment by josiahbjorgaard** [comment]
@mtaufen Code freeze is nearly here... will you be finished by Thursday EOD Pacific time, or should we bump this to v1.18?

**Comment by annajung** [comment]
Hello @mtaufen  👋 I'm one of the Bug Triage shadows for the 1.18 release. Since this issue is tagged for 1.18, I'd like to check its status. Is this issue intended for milestone 1.18?

Friendly reminder: Code freeze is scheduled for March 5th.

**Comment by mtaufen** [comment]
I cleared it from the milestone. This is a long-term testing improvement that can be tracked independently from releases.

As far as status, @tahsinrahman merged the core test helpers and some initial tests, and is continuing to expand coverage to additional components.

**Comment by mtaufen** [comment]
@tahsinrahman what's the latest status on this?

/remove-lifecycle stale

**Comment by tahsinrahman** [comment]
hi @mtaufen, the core package for testing componentconfig types was added, and tests for kubeproxyconfig was added https://github.com/kubernetes/kubernetes/pull/86144

after that tests for kubeletconfig was added, but it didn't get any feedback from respective owners, so its just hanging there https://github.com/kubernetes/kubernetes/pull/86034

i'll resolve the conflict and try to get a review from the owners and once its merged work on adding the tests for other components.
