### ISSUE TITLE
kubernetes api server fails to make tls connection to the dex server:certificate signed by unknown authority

### ISSUE THREAD

**Issue by fengpinghu** [kubernetes/kubernetes#68248]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
kurbernetes is setup with oidc for for authentication. the id provider is CoreOS dex. 
I am able to use the token to access the api before the token expired.However the token failed to renew because the kuber api server fails to make tls connection to the dex server. 
this is the error:
~$ kubectl  --kubeconfig=.kube/config.user cluster-info dump
Unable to connect to the server: Get https://k8s-dex.its.unc.edu:32000/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority

Both curl or openssl command can successfully make the tls connection:

[openssl.connect.txt](https://github.com/kubernetes/kubernetes/files/2350403/openssl.connect.txt)

**What you expected to happen**:

kubernetes api server can succefully make tls connection to the dex server and renew the token and thus users will be able to access the api server with the token.

**How to reproduce it (as minimally and precisely as possible)**:

1)get token with loginapp and dex
2) access the api with the token successfully with this command " kubectl  --kubeconfig=.kube/config.user cluster-info" 
3) After token expires in one day, the same command fails with: "x509: certificate signed by unknown authority"

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
$ cat /etc/issue.net 
Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`):
Linux ****** 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
/sig auth

**Comment by fengpinghu** [comment]
sig/ auth

**Comment by yue9944882** [comment]
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: minikube
```
set `insecure-skip-tls-verify` in ur kubeconfig

**Comment by fengpinghu** [comment]
Tried that it's the same result.
I want to clarify that this tls connection is not between kubectl command
and the apiserver but it's between the apiserver and dex server.
I've also verified the that the tls connection can be made with the rootca
cert and the host certs with  a test go program. The test program is
attached.
 $go run tlsclient.go
tlsclient.go:133: tls ok
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

The question is down to why the apiserver can't use the rootca certs to
connect the dex server

Thanks,
Fengping

**Comment by liggitt** [comment]
> What you expected to happen:
> kubernetes api server can succefully make tls connection to the dex server and renew the token

The apiserver does not renew the token, kubectl does.

**Comment by fengpinghu** [comment]
Hi  Jordan,

I guess I can rephrase and change apiserver to kubectl. But the problem is
still it's failing to make tls connection to dex server.
I've login to the apiserver pod and verified the ca file(--oidc-ca-file) is
mounted at the specified path. I've also verified with openssl command as
well as a go program that tls connection can be made with that ca and
hostcert/keys.
Somehow the kubectl command fails with certificate signed by unknown
authority error.  My CA certs does have the CA flag set to TRUE and also
I've even verified the TLS connection with a GoLang's program. So it seems
there's some catch in addition to the note found on
https://kubernetes.io/docs/reference/access-authn-authz/authentication/:
"A note about requirement #3 above, requiring a CA signed certificate. If
you deploy your own identity provider (as opposed to one of the cloud
providers like Google or Microsoft) you MUST have your identity provider’s
web server certificate signed by a certificate with the CA flag set to TRUE,
even if it is self signed. This is due to GoLang’s TLS client
implementation being very strict to the standards around certificate
validation. "

Thanks,
Fengping

**Comment by liggitt** [comment]
if the token works successfully against the apiserver before it expires, then the apiserver's TLS connection to dex (as verified by the --oidc-ca-file passed to the apiserver) is working

the issue for renewal is kubectl's connection to dex. does `kubectl config view` show a `idp-certificate-authority` parameter pointing to a CA file that validates the dex serving cert?

**Comment by fengpinghu** [comment]
Thanks Jordan,

That explained it. I now got what you meant when you said it's the kubectl
that make this tls connection in this case.
idp-certificate-authority is indeed not in my kubeconfig file. I will get
that added and verify tomorrow if an expired token can be renewed
successfully.

Thanks a lot,
Fenpging

**Comment by fengpinghu** [comment]
And certainly it can. So this can be closed. Thanks!

**Comment by liggitt** [comment]
Great, glad it got resolved

/close
