### ISSUE TITLE
Unable to kill pods

### ISSUE THREAD

**Issue by mabushey** [kubernetes/kubernetes#68250]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Used `helm delete istio` to remove istio.

**What you expected to happen**:
Remove all istio resources.

**How to reproduce it (as minimally and precisely as possible)**:
$ kubectl get pods -n istio-system
NAME                                     READY     STATUS        RESTARTS   AGE
istio-galley-6c799667d4-6k568            0/1       Terminating   0          4d
istio-sidecar-injector-c8c4c568b-qn5t9   0/1       Terminating   0          4d
$ kubectl delete pod/istio-galley-6c799667d4-6k568 --now
Error from server (NotFound): pods "istio-galley-6c799667d4-6k568" not found
$ kubectl delete pod istio-sidecar-injector-c8c4c568b-qn5t9 --now
Error from server (NotFound): pods "istio-sidecar-injector-c8c4c568b-qn5t9" not found
$ kubectl get pods -n istio-system
NAME                                     READY     STATUS        RESTARTS   AGE
istio-galley-6c799667d4-6k568            0/1       Terminating   0          4d
istio-sidecar-injector-c8c4c568b-qn5t9   0/1       Terminating   0          4d

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS via kops
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1
- Kernel (e.g. `uname -a`): 4.15.0-24-generic
- Install tools: kops 1.10.0
- Others:

**Comment by mabushey** [comment]
What the #$%@# is a sig label? I feel dumber after clicking on Details and trying to comprehend the garbage echoed
@kubernetes/sig-bug-bugs

**Comment by neolit123** [comment]
commented here about SIGs:
https://github.com/kubernetes/kubernetes/issues/68252

i think you can delete all pods in the istio namespace like so:
```
kubectl -n istio-system delete po --all   
```

ref:
https://kubernetes.io/docs/reference/kubectl/cheatsheet

**Comment by neolit123** [comment]
please close the issue if the above solves your problem.

/sig cli
