### ISSUE TITLE
kubectl create job should support passing labels to the pod spec

### ISSUE THREAD

**Issue by gtseres** [kubernetes/kubernetes#68251]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**: `kubectl create job` does not have a `--labels` flag.

**What you expected to happen**: `kubectl create job` should support a `--labels` flag, so that labels to the pod(s) can be passed. This can be really handy when we have defined a PodPreset and want the pod(s) created by the Job to use the PodPreset. In order to do that, we need to assign the correct labels to the pod(s). A use case for that is for example running a rake task for a deployed application that we want to share the same environment variables as the running pods of that application.

**How to reproduce it (as minimally and precisely as possible)**: `kubectl create job --help`

**Anything else we need to know?**: N/A

**Environment**: 
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.3", GitCommit:"0c7a3f0c13482839b352c5d2ab813f5049df76df", GitTreeState:"clean", BuildDate:"2018-08-16T22:10:44Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): MacOS 10.13.3
- Kernel (e.g. `uname -a`): Darwin Kernel Version 17.4.0
- Install tools: `kubectl` installed through brew
- Others: N/A

**Comment by TomaszKlosinski** [comment]
Any news on this?

**Comment by ultrafez** [comment]
As far as I can see, it doesn't seem possible to assign custom labels to pods created by Jobs when they're defined in YAML either.

**Comment by RomainPhil** [comment]
still no progress ?
