### ISSUE TITLE
Attach Detach Controller Install CRD does not specify validation schema

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#68260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

The CRD installation in https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L671 does not specify validation.

```GO
func (adc *attachDetachController) installCRDs() error {
	crd := &apiextensionsv1beta1.CustomResourceDefinition{
		ObjectMeta: metav1.ObjectMeta{
			Name: csiapiv1alpha1.CsiDriverResourcePlural + "." + csiapiv1alpha1.GroupName,
		},
		Spec: apiextensionsv1beta1.CustomResourceDefinitionSpec{
			Group:   csiapiv1alpha1.GroupName,
			Version: csiapiv1alpha1.SchemeGroupVersion.Version,
			Scope:   apiextensionsv1beta1.ClusterScoped,
			Names: apiextensionsv1beta1.CustomResourceDefinitionNames{
				Plural: csiapiv1alpha1.CsiDriverResourcePlural,
				Kind:   reflect.TypeOf(csiapiv1alpha1.CSIDriver{}).Name(),
			},
		},
	}
```

@liggitt pointed out lack of validation may cause issues with watchers and listers. So we validation should be added.

/milestone v1.12

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hoegaarden** [comment]
Hello @saad-ali  and @neolit123 - would it be ok for me and @mariantalla to pick this up?

We were thinking of the following approach:
1. Add a validation field to `crd `, of type `JSONSchemaProps `
1. The validation spec will cover each and every field on the `csiapiv1alpha1.CSIDriver`/`csiapiv1alpha1.CSINodeInfo` struct

Is this the correct approach or is there something else between the CRD and the API type we need to keep in mind?

**Comment by neolit123** [comment]
certainly, 
i would defer to @saad-ali for comments on the proposed solution. :)

**Comment by guineveresaenger** [comment]
Since this is related to another issue:

/priority critical-urgent

**Comment by saad-ali** [comment]
Fix for this will be part of PR https://github.com/kubernetes/kubernetes/pull/68579

**Comment by guineveresaenger** [comment]
Since #68579 merged, is this fixed as well?

**Comment by tpepper** [comment]
@saad-ali that PR #68579 is in and has seen at least some testing that's all green, eg:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce
had run 29963 all green.

Is this ready to close?

**Comment by msau42** [comment]
It turns out that by moving the test to [Serial], it stopped getting run in the alpha-enabled suite, so we stopped getting signal on that specific test case.

**Comment by guineveresaenger** [comment]
/close

Thanks everyone!
