### ISSUE TITLE
CPU Metrics between hpa and top pod

### ISSUE THREAD

**Issue by junpark12** [kubernetes/kubernetes#68276]
Hi I'm confused when i read cpu usage using HPA result and top pod.
When i run top pod, i see the following result. 
There are 3 pod which i configured hpa.

NAME                                                              CPU(cores)   MEMORY(bytes)
......
webapp-5699d546d9-2rk2k                                           3m           119Mi
webapp-5699d546d9-5sw67                                           63m          154Mi
webapp-5699d546d9-h499j                                           3m           125Mi

Then when i run following command, I see current utilization is 46%.
kubectl.exe get hpa
NAME      REFERENCE           TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
webapp    Deployment/webapp   46% / 10%   1         3         3          46m

Why these two results are different? 
please show me the way.
Thanks.

**Comment by neolit123** [comment]
@hacktastic 
please re-open when you provide more details about your setup.
thanks!
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

/close
