### ISSUE TITLE
k8s service creation gets struck in pending state forever

### ISSUE THREAD

**Issue by shausy** [kubernetes/kubernetes#68284]
Service gets struck in pending state forever when a user request for the creation of service with type load-balancer and the container network plugin was already exhausted the maximum limit of LB IP's

Actual Behaviour:
Service creation get struck when max limit of lb is reached

Expected Behaviour:
Service creation should be mark as failed as CNP clearly reports it cant created any further LB IP's

CNP Log
++++++++++
67071ab8', u'02f59f81-0d8f-4dbd-80ee-9c493c40421b', u'b0e0a528-09a8-4dd3-ab53-2e99196683c0']: Unexpected error from backend manager (['sfo01w01nsx01.sfo01.rainpole.local']) for PUT api/v1/loadbalancer/services/e7024138-fec8-4f37-9dee-ee2783ceb1c1 : Found errors in the request. Please refer to the relatedErrors for details. relatedErrors: Exceed maximum number of virtual servers on the Load balancer service. The maximum size of virtual servers for SMALL load balancer service form factor is 10, current size of virtual servers is 11
++++++++++++

+++++++++
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
web03     LoadBalancer   10.100.200.47   <pending>     80:30388/TCP   14m
++++++++++

**Comment by neolit123** [comment]
@shausy
please provide more details about your setup as described here:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

/sig network
/kind bug

**Comment by shausy** [comment]
Type: bug 

Environment: vSphere deployment.. Master and worker on VM

Kubernetes version (use kubectl version):
+++++++++++
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}


Cloud provider or hardware configuration: vSphere

OS (e.g. from /etc/os-release): 
+++++++++++
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"



Kernel (e.g. uname -a):
+++++++++++
master/f47ab5b5-d642-4d77-b7ad-42c6269c4ada:~$ uname -a
Linux 9ed76dd2-0f17-4fc1-856c-e954bbc7cbe9 4.4.0-130-generic #156~14.04.1-Ubuntu SMP Thu Jun 14 13:51:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
master/f47ab5b5-d642-4d77-b7ad-42c6269c4ada:~$
