### ISSUE TITLE
the path in API includes '/apis' while sometimes '/api'

### ISSUE THREAD

**Issue by xuil** [kubernetes/kubernetes#68285]
for example,

POST /api/v1/namespaces/{namespace}/pods

POST /apis/batch/v1/namespaces/{namespace}/jobs

why not to use the same?

 @kubernetes/sig-api-machinery-proposals

**Comment by yue9944882** [comment]
hi @xuil , for `/api`, it is legacy path. also, for a backward-compatibility.

/triage support
/close
