### ISSUE TITLE
Node termination reason isn't giving helpful information

### ISSUE THREAD

**Issue by nbosscher** [kubernetes/kubernetes#68286]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
One of my nodes ran out of disk space last night and Kubernetes managed to recover. The output from `kubectl describe pods` gives a "Last State" object which I would expect to give details on why the pod was terminated. 

```
Containers:
  static:
    Container ID:   <my-container-id>
    Image:          localhost:5000/static:v1
    Image ID:       <my-image-id>
    Port:           80/TCP
    State:          Running
      Started:      Tue, 04 Sep 2018 22:04:01 +0000
    Last State:     Terminated
      Reason:       Error                             <<<<<<< This message
      Exit Code:    2
      Started:      Wed, 20 Dec 2017 20:07:22 +0000
      Finished:     Tue, 04 Sep 2018 21:25:16 +0000
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
       ...
```

**What you expected to happen**:
I'd expect to get "Reason" that said something about node running out of disk space.

**How to reproduce it (as minimally and precisely as possible)**:
Sorry I can't be more specific. 
- Create a cluster with one or more nodes
- Deploy one ore more pods on the cluster, so that at least one pod is on each node
- Cause one of the nodes to run out of disk space
- Run a `kubectl describe pods` and note the `Last State -> Error Code` field for any pod that was on the node that was terminated.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS - using [KOPS](https://github.com/kubernetes/kops) default configuration

- OS (e.g. from /etc/os-release):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@ip-172-30-1-61 centos]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux ip-172-30-1-61.ec2.internal 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by nbosscher** [comment]
@kubernetes/sig-cluster-ops

**Comment by slevinson** [comment]
+1
More info on exit reason would be very helpful

**Comment by dataviruset** [comment]
Any clue about why the process exits with exit code 2 in this case? I'm having a similar issue running InfluxDB in Kubernetes, and it crashes in the startup process. Runs fine outside of Kubernetes (with ```docker run```).
