### ISSUE TITLE
Support the --all flag with `kubectl wait`

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#68298]
We should consider updating the `kubectl wait` command to wait on all resources for a given kind. For example:

```bash
$ kubectl wait --for=delete pods --all
```

would wait for every pod in the current namespace to be deleted.

/sig cli

cc @soltysh @deads2k

**Comment by straydata** [comment]
Interestingly, the error text implies that this is already supported:

```
$ kubectl wait --for condition=ready pod
error: resource(s) were provided, but no name, label selector, or --all flag specified
```

Yet when you try to use it, it declares `unknown flag: --all`

Would really like the wait functionality given some much needed TLC. Still no way to determine what conditions are supported for various resources (eg. I can say `--for condition=potato` and it just waits for the timeout like that resource might actually potato at some point).

**Comment by rctl** [comment]
I'm looking into adding the --all flag to wait, sounds like a nice feature to have :)
