### ISSUE TITLE
Failing Tests : [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68294]
# Failing Jobs
[sig-release-1.12-blocking#gce-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial)
# Failing tests
[ci-kubernetes-e2e-gce-cos-k8sbeta-serial](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-serial/1158)
# Triage results
[[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-cos-k8sbeta-serial&test=ReplicationController%20Should%20scale%20from%201%20pod%20to%203%20pods%20and%20from%203%20to%205%20and%20verify%20decision%20stability)

/kind failing-test
/sig autoscaling
/priority critical-urgent
/cc @tpepper @AishSundar @kubernetes/sig-autoscaling-test-failures

**Comment by DirectXMan12** [comment]
Looking at: https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=autoscaling&job=ci-kubernetes-e2e-gce-cos-k8sbeta-serial

It doesn't look like our fault: 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/horizontal_pod_autoscaling.go:53
Expected error:
    <*errors.errorString | 0xc4261e61c0>: {
        s: "Only 0 pods started out of 5",
    }
    Only 0 pods started out of 5
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:473
```

**Comment by tpepper** [comment]
Symptoms here look similar to #67603 and #67600

**Comment by guineveresaenger** [comment]
I am closing this in favor of #67600.
/close
