### ISSUE TITLE
e2e.test not found by hack/ginkgo-e2e.sh when built with bazel

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#68306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**: the test binary is not found when running e2e.go / kubetest / ginkgo-e2e.sh

**What you expected to happen**: the binary should be found

**How to reproduce it (as minimally and precisely as possible)**: `bazel build //cmd/kubectl //test/e2e:e2e.test //vendor/github.com/onsi/ginkgo/ginkgo` then run the e2e's

**Anything else we need to know?**:
This happens because ginkgo-e2e.sh looks for binaries with `kube::util::find-binary` which looks for binaries in paths that include the platform. e2e.test is not built into such a location. We don't see this failure in CI because we build a release tarball then extract it, which places _everything_ into a path with platform in it.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig testing
/sig release
/assign @ixdy

**Comment by BenTheElder** [comment]
Discussed offline, I think we can basically upstream https://github.com/kubernetes/test-infra/pull/9276/files at the point that PATH is exported in ginkgo-e2e.sh will look into this soon.

/assign

**Comment by BenTheElder** [comment]
that change is insufficient, and the sufficient work around is uglier. we'll have to think about this more...

**Comment by ixdy** [comment]
I think this was fixed in #69548.
/close
