### ISSUE TITLE
Kubernetes communicate with an app using service Nodeport and not Container IP

### ISSUE THREAD

**Issue by daovallec** [kubernetes/kubernetes#68303]
I have an Spring discover (Eureka) in a Server X

I have an docker with an APP. (This APP create an authentication with my discover in the server X).

I Create the Pod, and after the service:

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: deploym
>   labels:
>     name: deploym
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       name: test-server
>   template:
>     metadata:
>       labels:
>         name: deploym
>     spec:
>       containers:
>       - name: deploym
>         image: imaget:latest
>       hostAliases:
>       - ip: xxx.xx.xx.xxx
>         hostnames:
>         - discover
>       - ip: xxx.xx.xx.xxx
>         hostnames:
>         - discover.2
>       imagePullSecrets:
>       - name: regcre

At the moment that I create the POD. My APP create the registration with my discover server using the container IP.

Later I create my service:

> apiVersion: v1
> kind: Service
> metadata:
>   name: deploym
>   labels:
>     name: deploym
> spec:
>   type: NodePort
>   ports:
>     - port: 8080
>       targetPort: 8080
>       nodePort: 30120
>       name: http
>     - port: 443
>       targetPort: 443
>       nodePort: 31121
>       name: https
>   externalIPs:
>     - 'xxx.xx.x.xx'
>   selector:
>     name: deploym

But the problem is that my app is actually registered with my container IP.

I need register in my discover using the NodePort and my Node IP (because my eureka not find the app, because is seaching the Container IP and Port, and it IP and port are private in the container).

I am using Calico.

The problem is that, I can see my NodePort from external servers (I test it with a curl), is not a problem. But I have a discover service that take the IP and port. Now the IP and port that my discovery takes is the container IP. Not my Host and node Port. The auth with the discover server is doing when I create the POD not with my service IP. I need change the sign of my container service. Because when my discover server try to find the container service, (search with the container IP, and said it does not exist, not with my cluster and NodePort IP). I need a Way to out with my NodePort, for find from my discover the container.

How can i do it?

**Comment by shubheksha** [comment]
/triage support
/sig network
@daovallec , you might want to try asking in the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed.
