### ISSUE TITLE
k8s-merge-robot does not have a cool avatar

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68309]
@k8s-merge-robot does not have a cool avatar like @k8s-ci-robot does.

/kind feature
/sig contributor-experience

**What happened**:
I didn't see a cool avatar.

**What you expected to happen**:
A cool avatar.

**How to reproduce it (as minimally and precisely as possible)**:
1. View a merged PR
2. Feel disappointment

**Comment by BenTheElder** [comment]
k8s-merge-robot is backed by a legacy tool that has been retired except for k/k. It will be retired for k/k as well very soon, at which point we will probably retire this account in favor of the one with the avatar 🙃

**Comment by nikhita** [comment]
k/k has since then moved to Tide and @k8s-ci-robot (the one with the cool avatar) does the merging today. \o/

@k8s-merge-robot is not being used anywhere afaik. Closing. :)

/close
