### ISSUE TITLE
CoreDNS never deploys in ARM HA cluster

### ISSUE THREAD

**Issue by fberglin** [kubernetes/kubernetes#68304]
/kind bug

**What happened**:
I tried to follow the instructions on https://kubernetes.io/docs/setup/independent/high-availability/ in order to setup a cluster with three stacked masters using Raspberry 3 hardware. Whenever I include the controlPlaneEndpoint attribute in the kubeadm-config, the CoreDNS deployment never activates.

It seems to be hanging.

**What you expected to happen**:
CoreDNS to become 'Pending', then 'Running' after installing CNI plugin. The plan was to use Weave for networking.

**How to reproduce it (as minimally and precisely as possible)**:
Follow instructions on https://kubernetes.io/docs/setup/independent/high-availability/ using a Raspberry 3.

**Anything else we need to know?**:

**Environment**:
```
root@master-1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm"}

root@master-1:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

root@master-1:~# uname -a
Linux master-1 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux

root@master-1:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE
kube-system   etcd-master-1                      1/1       Running   0          1m
kube-system   kube-apiserver-master-1            1/1       Running   0          1m
kube-system   kube-controller-manager-master-1   1/1       Running   0          25s
kube-system   kube-scheduler-master-1            1/1       Running   0          1m

root@master-1:~# kubectl get deployments --all-namespaces
NAMESPACE     NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   coredns   2         0         0            0           1m

root@master-1:~# kubectl get nodes --all-namespaces
NAME       STATUS     ROLES     AGE       VERSION
master-1   NotReady   master    1m        v1.11.2

root@master-1:~# cat kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.1
apiServerCertSANs:
  - master
  - 192.168.8.150
api:
  controlPlaneEndpoint: "master:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.8.151:2379"
      advertise-client-urls: "https://192.168.8.151:2379"
      listen-peer-urls: "https://192.168.8.151:2380"
      initial-advertise-peer-urls: "https://192.168.8.151:2380"
      initial-cluster: "master-1=https://192.168.8.151:2380"
    serverCertSANs:
      - master-1
      - 192.168.8.151
    peerCertSANs:
      - master-1
      - 192.168.8.151
networking:
  # This CIDR is a Calico default. Substitute or remove for your CNI provider.
  # podSubnet: "10.224.0.0/16"
```

Other: Currently, to remove the external load-balancer, 'master' resolves to an additional IP on the 'master-1' node. There is no difference in behaviour if 'master' resolves to 'master-1' IP or 'load-balancer' IP. The IP is the same in both cases.

I have trawled the net for information, tried to get it working with Flannel as well and tried a lot of permutations to the kubeadmin file in order to get it to work. From what I can see, adding the controlPlaneEndpoint attribute breaks CoreDNS. What can I do to troubleshhot this issue? I couldn't find a deb package for docker 17.03. The oldest I found was 17.09 but the behaviour is the same.

Thanks,
// Fredrik

/sig network

**Comment by chrisohaver** [comment]
With no ready nodes available, I believe a Deployment cannot get its pods scheduled.

**Comment by fberglin** [comment]
Thanks for replying.

Does the controlPlaneEndpoint also imply that the node is tainted for deployment because without it, the CoreDNS POD's are deployed and become 'Pending' as expected.

I'm running into problems when I try to join a worker node, I don't know if it's related:

```
root@master-1:~# kubeadm token list
TOKEN                     TTL       EXPIRES                USAGES                   DESCRIPTION   EXTRA GROUPS
szpv67.x2cucbsmr19lyp4e   2h        2018-09-06T19:29:29Z   authentication,signing   <none>        system:bootstrappers:kubeadm:default-node-token
y72so9.r7y0xre45gmq6x3f   23h       2018-09-07T17:03:24Z   authentication,signing   <none>    system:bootstrappers:kubeadm:default-node-token

root@master-1:~# date
tor  6 sep 2018 17:13:36 UTC
```

```
root@worker-1:~# kubeadm reset
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
[reset] removing kubernetes-managed containers
[reset] cleaning up running containers using crictl with socket /var/run/dockershim.sock
[reset] failed to list running pods using crictl: exit status 1. Trying to use docker instead[reset] no etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd
[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

root@worker-1:~# kubeadm join master:6443 --token y72so9.r7y0xre45gmq6x3f --discovery-token-ca-cert-hash sha256:468fbad5d7271...
[preflight] running pre-flight checks
I0906 17:03:37.319153   24518 kernel_validator.go:81] Validating kernel version
I0906 17:03:37.320683   24518 kernel_validator.go:96] Validating kernel config
        [WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.06.1-ce. Max validated version: 17.03
[discovery] Trying to connect to API Server "master:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://master:6443"
[discovery] Failed to connect to API Server "master:6443": token id "y72so9" is invalid for this cluster or it has expired. Use "kubeadm token create" on the master node to creating a new valid token

[ ... repeats ... ]

root@worker-1:~# date
tor  6 sep 2018 17:13:38 UTC
```

Thanks,
// Fredrik

**Comment by fberglin** [comment]
Hi again,

The join problems seems to be related. If I remove the controlPlaneEndpoint directive from kubeadmin-config.yaml I can join worker nodes as expected and as soon as I deploy weave.net as CNI everything comes up as expected.

I'm really at my limits here when it comes to troubleshooting and the usually vast and bottomless fountain of wisdom that is the internet is coming up blank.

Thank you,
// Fredrik

**Comment by fberglin** [comment]
Ok, but that only makes a difference when there's no controlPlaneEndpoint defined. When I have that defined, I cannot join any workers. See above.

And also, when there's no explicit endpoint configured, coredns is deployed on the master, hence my question regarding taint. To me, this is a clear and very visible difference between the results from the configurations that only depends on if controlPointEndpoint is set or not.

Thanks, 
/ Fredrik

**Comment by chrisohaver** [comment]
OK, but without a network plugin installed, deployments wont schedule pods.

**Comment by fberglin** [comment]
If I don't have the attribute and do 'kubectl get pods' it's deployed with status 'Pending' until I install CNI. But if controlPlaneEndpoint is defined it does not even become 'Pending'.

There's something strange going on. Or I'm missing something. 

Thanks, 
/ Fredrik

**Comment by chrisohaver** [comment]
Yes thats right, I misspoke in my prior comment.
If no "schedulable" nodes are available, the it the pod wont deploy at all.
If there is a "schedulable" node available, but there is no network plugin, then the pod will deploy, but it will be stuck in Pending (waiting for network to be set up).

**Comment by chrisohaver** [comment]
Perhaps @fabriziopandini can help here.  It seems the core issue is that nodes are unable to join an HA cluster via the controlPlaneEndpoint.

**Comment by chrisohaver** [comment]
Dont know if this may help: https://stackoverflow.com/questions/47126779/join-cluster-after-init-token-expired

**Comment by fberglin** [comment]
Thanks,

To me, the biggest indication that something is amiss is that the coredns services doesn't even become pending whenever controlPlaneEndpoint is defined in kubeadm-config.yaml.

But it might somehow be connected to the problems with joining over the address defined. Is there any information I could provide that could help with troubleshooting?

Thanks, 
/ Fredrik

**Comment by chrisohaver** [comment]
My understanding of the flow of events in this case...

1. Set up a single node cluster (1 HA master), with no addtl nodes joined yet.  Master taint not removed.
2. Note that Deployments cannot schedule pods, due to the default master taint. Which is normal/expected.
3. Try to join a node to the cluster (via controlPlaneEndpoint), but fails with "invalid/expired token" error
4. Remove controlPlaneEndpoint 
5. Try to join a node: success.
6. Deployments begin to schedule pods, because the a cluster now contains an untainted node.

So, IIUC, the fact that a pod doesn't schedule when there is only one node in the cluster, and the master taint is still present, is expected behavior.  And that pods begin to get scheduled once an untainted node is joined to the cluster is also normal.

The questionable behavior is the inability to join a node to a cluster via the controlPlaneEndpoint.

**Comment by fberglin** [comment]
Great summary! Almost 100%.

Step 4 in my case is to reset the node and recreate the cluster with a modified configuration file. But from a logical point of view it's is the same. 

One thing I don't understand is why the deployment of coredns behaves differently depending on whether controlPlaneEndpoint is set or not. In one case it deploys and becomes 'Pending', in the other it does not.

Could the inability to join workers be connected to the absence of CoreDns in a HA cluster?

Is there some way I could reduce the environment to pinpoint the problem?

Thanks, 
/ Fredrik

**Comment by fabriziopandini** [comment]
@chrisohaver @fberglin 
I'm not sure I get all the gotchas of this thread, but let's focus on "Try to join a node to the cluster (via controlPlaneEndpoint)" step initially. 
1) Please check if the node is capable to resolve `master` address to IP. In similar setups on Ubuntu I use an additional line in `/etc/hosts` on all machines. Eventually you can test this with a `curl -k https://masters:6443/apis` from the node.
1) Please make sure tu use a valid token for the cluster when joining (each time you reset/init a new token is created). You can use `kubeadm token` command in case you need a new token

**Comment by fberglin** [comment]
Hi,

Thanks for looking into this.

```
root@worker-1:~# host master
master.eadu.k8s has address 192.168.8.150

root@worker-1:~# ping -c 1 master
PING master.eadu.k8s (192.168.8.150) 56(84) bytes of data.
64 bytes from master.eadu.k8s (192.168.8.150): icmp_seq=1 ttl=64 time=0.598 ms

--- master.eadu.k8s ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.598/0.598/0.598/0.000 ms

root@worker-1:~# curl -k https://master:6443/apis
{
  "kind": "APIGroupList",
  "apiVersion": "v1",
  "groups": [
    {
      "name": "apiregistration.k8s.io",
      "versions": [
```
There is some information further up in the thread regarding the tokens. The token is valid, but kubeadm rejects it.

Thanks,
/ Fredrik

**Comment by fabriziopandini** [comment]
Ok. The new step is to check if controller manager works properly.
Controller manager add a jet to tokens; but in this case it seems missing (invalid token)

**Comment by fabriziopandini** [comment]
/close due to lack of updates
Feel free to reopen if necessary
