### ISSUE TITLE
get-kube-binaries.sh: fails when there's space in path

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#68305]
/kind bug

**What happened**:

Tried to download v1.12.0-beta.1 via `cluster/get-kube-binaries.sh`.

Failed with error:

```

Extracting /Users/ahmetb/Downloads/kubernetes 2/client/kubernetes-client-darwin-amd64.tar.gz into /Users/ahmetb/Downloads/kubernetes 2/platforms/darwin/amd64
ln: failed to create symbolic link '/Users/ahmetb/Downloads'$'\n''2/client/bin': No such file or directory
```

**What you expected to happen**: Work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Extract release kubernetes.tar.gz to a path with space in it, like `/Users/ahmetb/Downloads/kubernetes 2`

```
cd /Users/ahmetb/Downloads/kubernetes\ 2
yes | cluster/get-kube-binaries.sh
```

**Anything else we need to know?**:

Doesn't reproduce if I extract tar to a directory without spaces in name.

**Environment**:
- Kubernetes version (use `kubectl version`): not applicable
- Cloud provider or hardware configuration: not applicable
- OS (e.g. from /etc/os-release): macOS, `/usr/bin/env bash` pointing to GNU bash4.4.23
- Kernel (e.g. `uname -a`): not applicable

**Comment by ahmetb** [comment]
I'm trying to just download a kubectl binary of the release and I could not find it anywhere but `cluster/get-kube-binaries.sh` to download it. What's the recommended way?

**Comment by BenTheElder** [comment]
This is probably the best one: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl (that page also has lots of other options for stable releases)

It's also in the client binaries from the release notes:
https://kubernetes.io/docs/setup/release/notes/  or https://github.com/kubernetes/kubernetes/releases -> https://groups.google.com/forum/#!forum/kubernetes-announce posts here will contain links for `kubernetes-client-$PLATFORM.tar.gz` downloads

**Comment by ahmetb** [comment]
Yeah I suppose they're actually linked as 

> Additional binary downloads are linked in the [CHANGELOG-1.12.md](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#downloads-for-v1120-beta1).

which I missed initially. Feel free to close this, I'm aware spaces in paths can easily mess up a lot of bash scripts. :)

**Comment by BenTheElder** [comment]
I'd still like to take a stab at fixing it :-)

I really doubt these scripts go anywhere anytime soon (ever?), and I didn't realize you just wanted `kubectl`. My thinking was that if you'd been using `get-kube-binaries.sh` with the other `cluster/` scripts we'd have to fix some of those too.

**Comment by BenTheElder** [comment]
The bug here is simple, but would have been caught by a `shellcheck` lint, I'm going to see if we can start incrementally fixing these throughout the codebase https://github.com/kubernetes/kubernetes/pull/68438 ref https://github.com/kubernetes/kubernetes/issues/24614

**Comment by BenTheElder** [comment]
I also have a fix [here](https://github.com/BenTheElder/kubernetes/tree/slightly-less-bash-fire), but I'm focusing on getting the shellcheck PR sorted first to prevent regressions before getting this in.

**Comment by BenTheElder** [comment]
This should actually be fixed now 🙃
