### ISSUE TITLE
Failing Tests : Up (multiple)

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68313]
# Failing Jobs
[sig-release-1.12-blocking#gce-cos-1.12-alphafeatures](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-alphafeatures)
[sig-release-1.12-blocking#gke-cos-1.12-default](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-default)
[sig-release-1.12-blocking#gke-cos-1.12-reboot](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-reboot)
[sig-release-1.12-blocking#gke-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-serial)
[sig-release-1.12-blocking#gke-cos-1.12-slow](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-slow)
[sig-release-1.12-blocking#gke-cos-1.12-ingress](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-ingress)
[sig-release-1.12-blocking#gke-device-plugin-gpu-1.12](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-device-plugin-gpu-1.12)
[sig-release-1.12-blocking#gke-device-plugin-gpu-p100-1.12](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-device-plugin-gpu-p100-1.12)
# Failing Tests
[ci-kubernetes-e2e-gce-cos-k8sbeta-alphafeatures](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-alphafeatures/5222)
[ci-kubernetes-e2e-gke-cos-k8sbeta-default](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/5374)
[ci-kubernetes-e2e-gke-cos-k8sbeta-reboot](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-reboot/4851)
[ci-kubernetes-e2e-gke-cos-k8sbeta-serial](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-serial/1299)
[ci-kubernetes-e2e-gke-cos-k8sbeta-slow](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-slow/5381)
[ci-kubernetes-e2e-gke-cos-k8sbeta-ingress](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-ingress/4232)
[ci-kubernetes-e2e-gke-device-plugin-gpu-beta](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu-beta/2850)
[ci-kubernetes-e2e-gke-device-plugin-gpu-p100-beta](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-device-plugin-gpu-p100-beta/479)

/cc @tpepper @AishSundar @kubernetes/sig-gcp-test-failures @kubernetes/sig-cluster-lifecycle 
/kind failing-test
/priority critical-urgent
/sig gcp
/sig cluster-lifecycle
/milestone v1.12

**Comment by tpepper** [comment]
/assign @barney-s 
could you take a look at these?

**Comment by mohammedzee1000** [comment]
cc @barney-s

**Comment by tpepper** [comment]
based on the implicated issues and associated pulls above, suspect should be fixed as of approx 8:30pm Pacific Sept 6

need confirmation

**Comment by timothysc** [comment]
This isn't sig-cluster-lifecycle as much as it's definitely google.  
/cc @roberthbailey 
for routing.

**Comment by AishSundar** [comment]
Looks like we can close this umbrella bug since the individual failures have been addressed by separate bugs. @guineveresaenger @mohammedzee1000
