### ISSUE TITLE
nil Context

### ISSUE THREAD

**Issue by 360CodeSafe** [kubernetes/kubernetes#68326]
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/util/iptables/iptables.go#L426

Do not pass a nil Context, even if a function permits it. Pass context.TODO if you are unsure about which Context to use.
via https://golang.org/pkg/context/

/sig release
/kind bug

**Comment by tanshanshan** [comment]
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/util/iptables/iptables.go#L429-L436

maybe use nil for run L434

**Comment by 360CodeSafe** [comment]
@tanshanshan 
Yes, you are right, I just want to say: 
Do not pass a nil Context, **even if a function permits it**

Not a big problem.
