### ISSUE TITLE
Wrong usage of `break`

### ISSUE THREAD

**Issue by 360CodeSafe** [kubernetes/kubernetes#68332]
/kind bug
/sig release
`break` switch or `break` loop
`switch` do not need `break`
Sometimes we expect to break `for loop`.

Such as:
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/cluster/images/etcd-version-monitor/etcd-version-monitor.go#L252

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/volume/flocker/flocker.go#L398

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/scheduler/core/generic_scheduler.go#L1063

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/kubectl/cmd/set/helper.go#L103

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/util/mount/mount.go#L304

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/util/mount/mount.go#L306

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/kubelet/types/pod_update.go#L95

https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/kubelet/types/pod_update.go#L97

**Comment by xiaoxubeii** [comment]
In https://golang.org/ref/spec#Break_statements: 

> A "break" statement terminates execution of the innermost "for", "switch", or "select" statement within the same function.

So although Go's switch statements break implicitly, but it is not a big problem.

**Comment by 360CodeSafe** [comment]
@xiaoxubeii 
You can found that all of the `break` above are in for loops, so maybe sometimes coders want to break for loop.

**Comment by tanshanshan** [comment]
so you mean that all of the break above use in switch ,but coder maybe want to break for loop @360CodeSafe

**Comment by 360CodeSafe** [comment]
Just maybe. @tanshanshan
