### ISSUE TITLE
The ipset KUBE-LOAD-BALANCER-SOURCE-CIDR is not recogized as a hash set

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#68338]
/kind bug
/area ipvs
/sig network

**What happened**:

Then the ipset `KUBE-LOAD-BALANCER-SOURCE-CIDR` is created it is not recognized as a hash set and the arguments family,maxelem,hashsize are not given.

**What you expected to happen**:

The `KUBE-LOAD-BALANCER-SOURCE-CIDR` should be created with the arguments mentioned above.

**How to reproduce it (as minimally and precisely as possible)**:

Since the ipset default valuses are also used by the `kube-proxy` you can not see this bug in an ipv4 cluster. But in an ipv6-only cluster the ignored `family` arguments causes the set to be created as ipv4 (`family inet`).

Unfortunately this bug is hidden by the much-larger bug in https://github.com/kubernetes/kubernetes/issues/67799 which causes **all** ipset's to become ipv4 in an ipv6-only cluster.

**Anything else we need to know?**:

I am working with the issue #67799 above but want to keep this separated since it is affecting both ipv4 and ipv6 and should be simple to review. I plan to do my first PR to kubernetes with this issue and want a trivial one to test the procedure.

The problem is [here](https://github.com/kubernetes/kubernetes/blob/8e329f1c3cbb1354c27b6135990c5544f14d2a17/pkg/util/ipset/ipset.go#L289). The condition should be the same as [here](https://github.com/kubernetes/kubernetes/blob/8e329f1c3cbb1354c27b6135990c5544f14d2a17/pkg/util/ipset/ipset.go#L97).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.954+b8e97d3451afb9", GitCommit:"b8e97d3451afb9bee7f9c213f4a0957855837171", GitTreeState:"clean", BuildDate:"2018-09-02T16:11:08Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.954+b8e97d3451afb9", GitCommit:"b8e97d3451afb9bee7f9c213f4a0957855837171", GitTreeState:"clean", BuildDate:"2018-09-02T16:10:14Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  Kvm on Ubuntu 18.04.1 LTS
- OS (e.g. from /etc/os-release):
  Own BusyBos based system
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux vm-001 4.18.5 #1 SMP Sat Sep 1 09:25:58 CEST 2018 x86_64 GNU/Linux
```
- Install tools:
  None
- Others:

**Comment by m1093782566** [comment]
cc @islinwb
