### ISSUE TITLE
Failure to promote non-string-literal e2e tests to Conformance

### ISSUE THREAD

**Issue by mgdevstack** [kubernetes/kubernetes#68339]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Table-based e2e tests are not getting updated to [golden conformance list](https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.txt) leading to the following error- ( mentioned in https://github.com/kubernetes/kubernetes/pull/67612#issuecomment-418616392)
```
INFO: From Listing all conformance tests. //test/conformance:list_conformance_tests:
ERROR at test/e2e/common/runtime.go:232:29: framework.ConformanceIt() called with non-literal argument
ERROR: non-literal argument &{0xc42038d2e0 9790 [0xc42038d300 0xc42038d360] 0 9858} at test/e2e/common/runtime.go:232:29
ERROR at test/e2e/common/runtime.go:355:29: framework.ConformanceIt() called with non-literal argument
ERROR: non-literal argument &{0xc42038b7a0 17397 + 0xc42038b7c0} at test/e2e/common/runtime.go:355:29
Target //test/conformance:list_conformance_tests up-to-date:
  bazel-genfiles/test/conformance/conformance.txt
INFO: Elapsed time: 11.206s, Critical Path: 10.55s
```
framework.ConformanceIt() requires the first parameter to be `string literal` and [table based e2e tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L204) are associated with `string formation` at runtime based on different cases/test-scenarios.

**What you expected to happen**:
Either disapprove the use of table-based e2e tests or suggestion on an alternative approach to add such tests to Conformance.

**How to reproduce it (as minimally and precisely as possible):**
1. Add framework.ConformanceIt() to [table-based e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/runtime.go#L204).
2. Run ```bazel build //test/conformance:list_conformance_tests```

/area conformance
@kubernetes/sig-testing
cc @brahmaroutu

**Comment by spiffxp** [comment]
Approaches to work around this:
- wrap the whole table based test in a ConformanceIt block
- refactor to a more boilerplate approach that has a ConformanceIt block for each table entry
- update the conformance test walker to detect table based tests that use a well known field?

**Comment by mgdevstack** [comment]
Thanks @spiffxp, I am evaluating these approaches especially on "conformance test walker" to retrieve well-known fields like `fmt.Sprintf()` and variables used inside `framework.ConformanceIt()`.

**Comment by spiffxp** [comment]
@mgdevstack Does this close if #70492 closes or are there other tests that need to transition?

**Comment by mgdevstack** [comment]
/close
Closing as per other fruitful approach https://github.com/kubernetes/kubernetes/issues/68339#issuecomment-423678023 and efforts would be taken to refactor table-based tests into individual tests wherever needed.
