### ISSUE TITLE
Infinite recursive call

### ISSUE THREAD

**Issue by 360CodeSafe** [kubernetes/kubernetes#68337]
/kind bug
/sig release

Such as:
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/cloudprovider/providers/cloudstack/cloudstack_loadbalancer.go#L242
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/client/chaosclient/chaosclient.go#L66

**Comment by wgliang** [comment]
Cool issue.
/assign

**Comment by wgliang** [comment]
@smarterclayton
I see the code in `kubernetes/pkg/client/chaosclient/chaosclient.go` was pushed by you. I don't understand what Intercept() does. Do you think there is an Infinite recursive call?

**Comment by wgliang** [comment]
@smarterclayton But there are also one place using it.

https://github.com/kubernetes/kubernetes/blob/361746266a490c3adbfb391cdf56c24acee8c0b8/cmd/kubelet/app/server.go#L898

**Comment by smarterclayton** [comment]
Has never been anything other than experimental and was not used in practice.  We can remove it and it’s flag from kubelet as it was experimental.  @liggitt are we deprecating experimental flags for one release or can we just remove?
