### ISSUE TITLE
`defer` in infinite loop

### ISSUE THREAD

**Issue by 360CodeSafe** [kubernetes/kubernetes#68336]
/kind bug
/sig release

`defer` call will never be execute.
https://github.com/kubernetes/kubernetes/blob/8e329f1c3cbb1354c27b6135990c5544f14d2a17/pkg/cloudprovider/providers/vsphere/vsphere_util.go#L301

**Comment by wgliang** [comment]
@BaluDontu 
Maybe just cleanUpDummyVMLock.Lock()  is you want? The `defer` is  in infinite loop, and will never execute. I hope to get your reply to help fix it.

**Comment by divyenpatel** [comment]
@wgliang yes we need to correct this as below in the `cleanUpDummyVMs` routine.

```
// A write lock is acquired to make sure the cleanUp routine doesn't delete any VM's created by ongoing PVC requests.
cleanUpDummyVMLock.Lock()
err = diskmanagers.CleanUpDummyVMs(ctx, vmFolder, dc)
cleanUpDummyVMLock.Unlock()
```
