### ISSUE TITLE
Controller-manager crashloop in 5k-node load test

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#68355]
In the latest run of gce-scale-performance (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/208), load test failed. The following happened:

- at 10:24:05 (~1.5h after the start), pods stopped being created:

```
I0905 10:24:14.770] I0905 10:24:14.769750    7590 runners.go:180] load-small-2141 Pods: 0 out of 5 created, 0 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0905 10:24:14.962] I0905 10:24:14.962672    7590 runners.go:180] load-small-4857 Pods: 0 out of 5 created, 0 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0905 10:24:15.325] I0905 10:24:15.324996    7590 runners.go:180] load-small-10532 Pods: 0 out of 5 created, 0 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
```

- from the [c-m logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/208/artifacts/gce-scale-cluster-master/kube-controller-manager.log-20180906-1536192002.gz) there seemed to be a restart just around that time, caused due to losing leaderelection:

```
I0905 10:24:05.645220       1 leaderelection.go:231] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
F0905 10:24:09.534153       1 controllermanager.go:238] leaderelection lost
```

but it's fine to restart after losing election (we even observed this in past). However it failed to come up after restart and was continuously crashing, with the following error:

```
I0905 10:24:12.929848       1 serving.go:293] Generated self-signed cert (/var/run/kubernetes/kube-controller-manager.crt, /var/run/kubernetes/kube-controller-manager.key)
failed to get delegated authentication kubeconfig: failed to get delegated authentication kubeconfig: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

- The file `/var/run/secrets/kubernetes.io/serviceaccount/token` is the default path where ServiceAccountToken secrets are automounted to, which is needed to communicate with the apiserver. However, the file doesn't seem to exist there and creating it is the duty of kubelet iiuc.

We need to dig further, and understand why this happened.

cc @wojtek-t @krzysied

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
kubelet logs from that run seem to be necessary to debug it (I mean kubelet from master VM)

**Comment by shyamjvs** [comment]
So I did check [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/208/artifacts/gce-scale-cluster-master/kubelet.log) and I see a lot of ContainerStarting failures in a row for c-m, but not sure if I find anything much useful there. Let me look fruther.

**Comment by shyamjvs** [comment]
Thanks @liggitt !
Closing this one..
