### ISSUE TITLE
Failing Test: Beforesuite gce-scale-correctness

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68359]
# Failing Jobs
[sig-release-master-blocking#gce-scale-correctness](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness)
# Failing Tests
[Beforesuite](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/160)
# Triage Results
[Beforesuite](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-e2e-gce-scale-correctness&test=Beforesuite)

/kind failing-test
/priority critical-urgent
/sig gcp
/sig testing
/milestone v1.12
cc @tpepper @AishSundar @kubernetes/sig-gcp-test-failures @kubernetes/sig-testing

**Comment by AishSundar** [comment]
Assigning to SIG scalability folks
/assign @shyamjvs @wojtek-t 
/unassign @roberthbailey

**Comment by AishSundar** [comment]
Looks like https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness is now clearing up ! However https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance is still a bit flaky.

@shyamjvs @wojtek-t can you plz take a look to see if this flake is masking any real issue? You assessment will help us ascertain the release blocking nature of this failure.

**Comment by wojtek-t** [comment]
This one shoudl be fixed - the last failure was an issue with leaked resources from a different test.

Given last two green runs, I'm closing this one. Feel free to reopen if you need anything else.

**Comment by AishSundar** [comment]
@wojtek-t what about the failures in  https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance ? do you expect even that to clear up in a new run (considering the last run was on very early on 9/10)?

**Comment by shyamjvs** [comment]
@AishSundar We're tackling that currently by running some manual bisection tests and also simultaneously debugging Ci runs - but it may take a while for it. More details under this issue - https://github.com/kubernetes/kubernetes/issues/67670#issuecomment-419480424.

**Comment by wojtek-t** [comment]
gce-scale-performance is a different issue. @shyamjvs and @krzysied are trying to debug it

**Comment by mohammedzee1000** [comment]
/reopen
sorry seems to have closed somehow
@wojtek-t @AishSundar fyi

**Comment by shyamjvs** [comment]
@mohammedzee1000 Sorry, could you clarify? I see the last 2 runs of this job passed - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness

**Comment by mohammedzee1000** [comment]
@shyamjvs sorry misworded. Meant to say might fail. Want to watch 1-2 more stabe runs before closing

**Comment by wojtek-t** [comment]
This is running once per week now - you really want to wait two more weeks?

We know what the problem was and we know it is now fixed (also based on other runs).
This really can be closed.

**Comment by wojtek-t** [comment]
> We know what the problem was and we know it is now fixed (also based on other runs).

What I'm saying is that those are scalability tests - we have a number of suites and the problem appeared in others. And it is fixed into those others too.
There is no need to keep it open.

**Comment by shyamjvs** [comment]
+1
I too think there's not much point keeping this open even after couple of green runs, given the nature of this job.

**Comment by mohammedzee1000** [comment]
ok, if we are in agreement then, closing
/close
