### ISSUE TITLE
Possible race condition in creating network connections in ingress controller namespace instead end up orphaned in the root namespace on a kubernetes node

### ISSUE THREAD

**Issue by blerko** [kubernetes/kubernetes#68358]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
A network connection intended to be made in the namespace of kubernetes ingress controller was instead orphaned an left in the root namespace on a kubernetes node

**What you expected to happen**:
That the connection was made in the namespace of the ingress controller.

**How to reproduce it (as minimally and precisely as possible)**:

You need a system making a regular connection via an ingress controller and the ingress gets restarted repeatedly.

**Anything else we need to know?**:

The connection appears like this in the root namespace:

```
 # netstat -np | grep 30011
tcp6  2577936      0 10.33.225.36:30011      10.33.40.18:32808       ESTABLISHED - 
```

We think the race condition happens between kube proxy listening on the port,  a connection being opened and the kube-proxy setting up the iptables rules on a node running the ingress controller pod

We think the problem is somewhere in this code:

https://github.com/kubernetes/kubernetes/blob/e41d9f15530d5c5bd116c90a988c8245f0be7974/pkg/proxy/iptables/proxier.go#L1391

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.8.7+coreos.0
- Cloud provider or hardware configuration:
Node provisioned from an openstack cluster 
- OS (e.g. from /etc/os-release):
Container Linux by CoreOS 1632.2.1
- Kernel (e.g. `uname -a`):
4.14.16-coreos

**Comment by blerko** [comment]
@kubernetes/sig-network-bugs

**Comment by blerko** [comment]
Can I bump this?

**Comment by blerko** [comment]
Another bump on this one

**Comment by thockin** [comment]
We fixed a bug in 1.14 and 1.13 that sends an ICMP reject rather than letting traffic flow down to the host, when there are no endpoints.  If you can reproduce against fairly recent versions, please reopen.

**Comment by thockin** [comment]
(specifically a bug that would have caused exactly this)

**Comment by mikebryant** [comment]
Thanks for the info. We'll check again when we've upgraded. :)
