### ISSUE TITLE
Bring Batch Capability into Kubernetes

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#68357]
During the implementation of [kube-batch](https://github.com/kubernetes-incubator/kube-batch) and the discussion of [Coscheduling](https://github.com/kubernetes/features/issues/583), there're several topics/requirements to support batch workload. I list them here; some items already has related discussion, e.g. Topology, some items are not. I'd like to open related issues (by specific use case) one by one for discussion and review, e.g. Coscheduling. If anyone want to contribute (based on the cases) or have other case about batch workload, please feel free to comments :)

1. Scheduling/Placement 
    - Coscheduling (https://github.com/kubernetes/features/issues/583)
    - Resource sharing between "Job" (e.g. proportion for streaming/elastic job) 
    - "Job" level priority/preemption (https://github.com/kubernetes/kubernetes/issues/65746)
    - Task/Pod priority within "Job" (Spark executor/worker)
    - Backfill for Coscheduling
    - ...
1. Topology aware (related)
    - Scheduling (N/A)
    - Node (https://github.com/kubernetes/kubernetes/issues/49964)
1. "Queue"
    - Multi-tenant WG: it's better to make "Queue" and "tenant" align (for resource sharing), but we do not have conclusion on tenant righ now :(
    - Hierarchical "Queue"
    - ...
1. Lifecycle Management
    - Admission for PodGroup
    - lifecycle management for PodGroup as default
    - Indexed Job (e.g. MPI) (https://github.com/kubernetes/kubernetes/issues/14188)
    - ...
1. "batch scheduler + default scheduler" or "support batch (job) by default scheduler"
    - Scheduling Framework (https://github.com/kubernetes/community/pull/2281)
    - algorithm/policy lib (https://github.com/kubernetes/kubernetes/issues/62092)
    - ...
1. Others
    - "master/driver" addressing (e.g MPI)
    - Scalability
    - Throughput for batch job
    - ...

/cc @vishh @bsalamat 
/cc @kubernetes/sig-architecture-feature-requests

**Comment by krmayankk** [comment]
@k82cn are you working on this entire thing. Can this be broken down into mutiple issues. I am interested in working on this. Please let me know

**Comment by tanshanshan** [comment]
I am interested in it , and I want to contribute for it.

**Comment by k82cn** [comment]
> are you working on this entire thing. 

hm... NO and YES :) some items are handled by others e.g. topology, I'd like to contribute for batch; I'm working on some items, e.g. Coscheduling; and some items are still in pending list, e.g. "Queue" (maybe not reasonable). This umbrella is to trace related issues; and prefer to prioritize by scenario or use case, for example, to support MPI, coscheduling and IndexJob are required.

also /cc @bgrant0607 @davidopp @timothysc @liyinan926 @ConnorDoyle who may also interest :)

**Comment by krmayankk** [comment]
i am interested in 2nd and 5th. @k82cn is this being discussed in sig-scheduling meetings ?

**Comment by denkensk** [comment]
I am interested in it, can I do something for it?

**Comment by ahmad-diaa** [comment]
interested.

**Comment by dims** [comment]
@k82cn This Issue does not cover the rename of kube-batch or the proposal for a new name or scope. Was there any other public discussion?

**Comment by bgrant0607** [comment]
Shouldn't this just be a KEP?

**Comment by k82cn** [comment]
@bgrant0607 , hm... I can draft a KEP about the motivation and the overall scope of this proposal; as you known, each item, even the sub-items, deserves a KEP on the function detail, e.g. fair-share, indexed job.

Some background here for your reference: we used to have a long long discusion about this (at ~2017); as a result, we incubate kube-arbitrator for it. We renamed kube-arbitrator to kube-batch to focus on batch scheduling; but we found that a batch scheduler is not enough for that, e.g. queue/job management, admission contrtoller are also necessary. That's why I propose to extend kube-batch's scope for that, or do that in upstream; personally, this's a fundamental proposal to k8s/core.

**Comment by krmayankk** [comment]
@k82cn  has the list of tasks be decided ? I would love to drive the implementation of certain parts of it

**Comment by k82cn** [comment]
> @k82cn has the list of tasks be decided ? I would love to drive the implementation of certain parts of it

@krmayankk , as Brian suggested, I'll draft a KEP for this, we'll know the scope and the list of task if everything smooth :)

**Comment by dims** [comment]
@k82cn Klaus, with the stuff already in kube-batch and the new volcano project, do we really need to keep this issue open?

**Comment by k82cn** [comment]
> Shouldn't this just be a KEP?

@bgrant0607 , open a google doc as an umbrella of KEP: https://docs.google.com/document/d/1jgXiLNZUh7Voz-MHeggrC227tQogEVA4wbtlPIKzZPI/edit?usp=sharing (also forward to k/dev), thanks in advance for your comments and suggestions :)

**Comment by k82cn** [comment]
/close

> @k82cn Klaus, with the stuff already in kube-batch and the new volcano project, do we really need to keep this issue open?

I'm going to close this issue as we're going to build those features in [Volcano](http://github.com/volcano-sh/volcano), and we'll raise necessary enhancements to upstream if any :)
