### ISSUE TITLE
Deprecate and remove debugging logging handler on apiserver

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#68366]
Audit logging replaced a majority of valid uses of this endpoint. It provides an easy escalation and is a security concern.

/sig api-machinery

@liggitt @cjcullen

**Comment by CaoShuFeng** [comment]
I guess debugging logging handler is this:

curl http://127.0.0.1:8080/logs/

**Comment by bruceauyeung** [comment]
I have pushed a PR for this, would you mind take a look ?
@mikedanese @liggitt @cjcullen

**Comment by mikedanese** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
Is there any difference between the security risk of this endpoint and the pprof endpoint or the exec endpoint, which all offer trivial root escalation?

**Comment by smarterclayton** [comment]
Logs is super useful for cluster admin - audit doesn’t even begin to approach the value logs has for triage.

**Comment by mikedanese** [comment]
A major difference between the pprof endpoint is that the pprof endpoint is not enabled by default. I don't think exec endpoint is a reasonable comparison, since we have reasonable assurances around and policy to restrict what a user can do (e.g. PSP, RBAC, not registering the master kubelet). Can we at least turn the handler off by default?
