### ISSUE TITLE
WS2016 pods running with Hyper-V are not accessible via service IP on Windows Server version 1803 nodes

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#68375]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I scheduled a pod based on Windows Server 2016 on a Windows Server version 1803 node with the alpha Hyper-V support enabled. The pod starts, but does not get an IP. The service gets an external IP through load balancer, but its not accessible.

```bash
$ kubectl get pod -o wide
NAME                          READY     STATUS              RESTARTS   AGE       IP            NODE
iis-2016-66c5dc745f-r29mf     1/1       Running             0          51s       <none>        48797k8s9001
iis-2016-66c5dc745f-t42m6     0/1       ContainerCreating   0          2m        <none>        48797k8s9000
whoami-1709-7bc765bdd-w26tg   1/1       Running             0          1h        10.240.0.85   48797k8s9000

$ kubectl get svc
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
iis               LoadBalancer   10.0.255.126   13.77.153.27    80:31069/TCP   1h
kubernetes        ClusterIP      10.0.0.1       <none>          443/TCP        1h
whoami-1709-svc   LoadBalancer   10.0.127.69    13.66.159.189   80:32435/TCP   1h

$ curl http://10.0.255.126
curl: (7) Failed to connect to 10.0.255.126 port 80: Connection refused
$ curl http://13.77.153.27

```

**What you expected to happen**:

Pod should be accessible via pod IP or load balancer IP

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy K8s v1.10.6 cluster with Windows nodes. Use acs-engine with this [apimodel](https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes-hyperv.json)
2. `kubectl create -f https://raw.githubusercontent.com/PatrickLang/Windows-K8s-Samples/master/HyperVExamples/iis-2016.yaml`

**Anything else we need to know?**:

/sig windows
cc @feiskyer @daschott

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Windows Server version 1803 (on nodes) 
- Kernel (e.g. `uname -a`):10.0.17134.228

**Comment by daschott** [comment]
I am tracking this and will investigate once other high-priority investigations have concluded.

**Comment by feiskyer** [comment]
Are there same issues on Kubernetes v1.11 and master banch?

**Comment by PatrickLang** [comment]
Yes, I have also seen it on v1.11.2. I haven't tried master or v1.12beta yet

**Comment by PatrickLang** [comment]
I've been discussing with Pengfei over email - here's some errors we're seeing in kubelet

```none
{"level":"debug","msg":"Result: {\"Error\":-1070137077,\"ErrorMessage\":\"An unknown internal message was received by the Hyper-V Compute Service.\",\"ErrorEvents\":[{\"Message\":\"Message Type 269486593 unknown (1206 byte)\",\"Provider\":\"00000000-0000-0000-0000-000000000000\",\"EventId\":0}]}","time":"2018-09-12T00:39:08Z"}
{"level":"debug","msg":"HCSShim::Container::Close id=a089ada8a4ffc3022a6b1817d3bae347e9cbca9d1ddb275f23245d7037851d1c","time":"2018-09-12T00:39:08Z"}
{"level":"debug","msg":"HCSShim::Container::Close succeeded id=a089ada8a4ffc3022a6b1817d3bae347e9cbca9d1ddb275f23245d7037851d1c","time":"2018-09-12T00:39:08Z"}
{"level":"error","msg":"[cni-net] Failed to HotAdd endpoint 4b79a4b1-bdb1-4163-847c-f421c15a3641, err:unsupported platform request.","time":"2018-09-12T00:39:08Z"}
{"level":"debug","msg":"[DELETE]=\u003e[/endpoints/4b79a4b1-bdb1-4163-847c-f421c15a3641] Request : ","time":"2018-09-12T00:39:08Z"}
```

**Comment by dineshgovindasamy** [comment]
@PatrickLang we don't support hot adding an endpoint to Hyper-V Container. This is a feature work. we are currently working on enabling it through ContainerD.

**Comment by dineshgovindasamy** [comment]
@PatrickLang Can we close this issue and track it as a Feature work item?

**Comment by PatrickLang** [comment]
This would need networking functionality from WS2019 backported to WS2016 container images from Microsoft. There's no plan to do that. That means we can't fix this.

/close
