### ISSUE TITLE
what happend? when i execute kubectl get pos -n kube-system

### ISSUE THREAD

**Issue by wanghonglei5181** [kubernetes/kubernetes#68389]
0> kubectl get pods -n kube-system
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/printers.PrintTable(0xc420e8ed00, 0x1893a00, 0xc420952000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/humanreadable.go:366 +0x5d6
k8s.io/kubernetes/pkg/printers.(*HumanReadablePrinter).PrintObj(0xc420131d40, 0x189d3a0, 0xc420e8ed00, 0x1893a00, 0xc420952000, 0x0, 0x0)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/humanreadable.go:286 +0x7ca
k8s.io/kubernetes/pkg/printers.(ResourcePrinter).PrintObj-fm(0x189d3a0, 0xc420e8ed00, 0x1893a00, 0xc420952000, 0x1892b00, 0xc4209050e0)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:252 +0x57
k8s.io/kubernetes/pkg/printers.ResourcePrinterFunc.PrintObj(0xc420e32020, 0x189d3a0, 0xc420e8ed00, 0x1893a00, 0xc420952000, 0x0, 0x0)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/interface.go:38 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc420324380, 0x18c6dc0, 0xc420881770, 0xc42072e280, 0xc420356a20, 0x1, 0x3, 0x0, 0x0)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:444 +0xae9
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc42072e280, 0xc420356a20, 0x1, 0x3)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:159 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42072e280, 0xc420356960, 0x3, 0x3, 0xc42072e280, 0xc420356960)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201b6000, 0xc4205caff0, 0x12a05f200, 0xc420a91ee8)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201b6000, 0x17ea8b0, 0x23ff060)
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**Environment**:
- Kubernetes version 
    1.11.1
- OS (e.g. from /etc/os-release):
   centos7.3   
- Kernel 
   4.16.7-1.el7.elrepo.x86_64
- Install tools:
   kubeadm
- Others:

**Comment by wgliang** [comment]
This issue had been fixed.
FYI #66379

**Comment by neolit123** [comment]
thanks @wgliang for the info!

@wanghonglei5181 your are going to have to update to 1.12 so that this works for you.
1.12 will be released on the 25th of October.

thank you
/close

**Comment by wanghonglei5181** [comment]
thanks @neolit123   @wgliang
