### ISSUE TITLE
HPA test is flaky

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#68383]
This started after https://github.com/kubernetes/kubernetes/pull/68077 was merged. @DirectXMan12 

The HPA test started being very flaky since then: https://k8s-testgrid.appspot.com/google-gce#gci-gce&width=5

The HPA test in containerd e2e become even more flaky since then with the same failure pattern: https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-e2e-gci&width=5

**Comment by tpepper** [comment]
I think this is probably
/priority critical-urgent

Release team hasn't looked close enough at this issue as we've been trying to clear other issues in front of it.  If we crack those and this is unrelated root cause, then this one's going to be a release blocker.

**Comment by DirectXMan12** [comment]
It's going to be supremely hard to debug this unless we have logs from metrics-server and/or snapshots of the HPA over time.  I'm trying to reproduce on a local cluster, but so far, the test passes consistently.

@kubernetes/sig-autoscaling-bugs 

@Random-Liu did you manage to reproduce locally?

**Comment by DirectXMan12** [comment]
@kubernetes/test-infra-maintainers is there any way to grab logs of pods from a testing cluster?

**Comment by krzyzacy** [comment]
you probably want to save it as part of the artifacts?

**Comment by DirectXMan12** [comment]
@krzyzacy yeah, what's the process for that?

**Comment by krzyzacy** [comment]
@DirectXMan12 somewhere along https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L40-L53

**Comment by DirectXMan12** [comment]
See #68566 for an attempt at debugging this.

**Comment by pires** [comment]
@bmcstdio can we provide the data @DirectXMan12 is looking for?

@DirectXMan12 we're seeing this quite often.

**Comment by DirectXMan12** [comment]
ack, more logs would be helpful.  Currently trying to get usable logs off the CI with the aforementioned PR, but I keep making minor mistakes in the log collection script :-/.  It seems to repro every few runs though, so with any luck I'll see it again soon.

**Comment by DirectXMan12** [comment]
Got a WIP fix up: https://github.com/kubernetes-incubator/metrics-server/pull/138.  Need to do one more tweak before merge.

**Comment by DirectXMan12** [comment]
Re-running tests with the above PR, if they succeed I'll merge and get someone to do a build when the people capable of running builds are on next.

**Comment by tpepper** [comment]
@DirectXMan12 status check?  I'm worried this is a 1.12 blocker and need to make a call by end of day today regarding delaying the release.

**Comment by pires** [comment]
According to our testing, metrics-server 0.3.1 seems to have fixed it - thank you @DirectXMan12.
