### ISSUE TITLE
Sample apiserver does not allow actual use of its admission plugin

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#68395]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I made an extension apiserver based on the sample.  My extension apiserver adds an admission plugin, as does the sample.  But if that admission plugin is enabled from the command line then validation fails.

There are two problems.  For the first, note that https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L70 invokes validation before https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L73 --- which is where the additional admission plugin gets added (see how https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L128 leads to https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L98 which is what gets to https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/sample-apiserver/pkg/admission/plugin/banflunder/admission.go#L35).

I fixed that inversion by promoting some code from `Config()` to `Complete()` in my extension server.  That exposed the other problem, which comes from https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/staging/src/k8s.io/apiserver/pkg/server/options/admission.go#L196 .  The sample apiserver does not add its admission plugin to `RecommendedPluginOrder`, so this check trips.

**What you expected to happen**:
I expected to be able to use my admission plugin.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by yue9944882** [comment]
@MikeSpreitzer actually, we're facing the same problem in kube-apiserver. but currently we walkaround by explicitly registering all known builtin plugins.
  [https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/pkg/kubeapiserver/options/plugins.go#L101](https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/pkg/kubeapiserver/options/plugins.go#L101)

**Comment by yue9944882** [comment]
we're already working on simplifying the launch-flow for servers (including plugin initialization), but it'll take some time. maybe we can a better solution for this issue after that.

**Comment by MikeSpreitzer** [comment]
You can see how I solved it, in https://github.com/MikeSpreitzer/kube-examples/blob/cc90dae1c518d51532eafed7739b0e98d8e98efc/staging/kos/pkg/cmd/server/start.go#L94-L110 .  At first those lines were in `func (o *NetworkServerOptions) Config()`.

**Comment by yue9944882** [comment]
no, u don't have to walkaround like that. just registering all the built-in plugins on instantiating the option struct will be fine.

[https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/pkg/kubeapiserver/options/admission.go#L52-L64](https://github.com/kubernetes/kubernetes/blob/5c8ef7eb3b737f869d1b04a5b3837d4400b561a7/pkg/kubeapiserver/options/admission.go#L52-L64)

**Comment by MikeSpreitzer** [comment]
What in sample-apiserver corresponds to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/admission.go ?

**Comment by yue9944882** [comment]
the `kube-apiserver` is the existing & possibly correct way to build a server, isn't it? the `sample-apiserver` is just a generic demo, and it doesn't reveal how to extend or make use of advanced features like admission plugin.

**Comment by MikeSpreitzer** [comment]
sample-apiserver _does_ aim to illustrate how to implement admission plugins.  My complaint here is that the illustration is broken.

In the kubernetes ecosystem there is a distinction between the main apiserver and extension apiservers.  kubeapiserver is the one and only main apiserver; sample-apiserver is meant to be an example of an extension apiserver.  Extension apiservers are intended to support their own admission plugins.

**Comment by MikeSpreitzer** [comment]
Actually, I do not know why my network apiserver works; it should crash because the `SharedInformerFactory` field is set in the wrong copy of the `NetworkServerOptions`.  Moving one fewer statement from `Config()` to `Complete()` fixes that.
