### ISSUE TITLE
Encryption at REST for Kubernetes 1.9.1 is not working

### ISSUE THREAD

**Issue by tashirj** [kubernetes/kubernetes#68407]
/sig api-machinery
 I am trying to enable this feature of Encryption at REST using ETCD in Kubernetes 1.9.1 by providing the "**--experimental-encryption-provider-config=/etc/kubernetes/enc-conf.yaml"** in the kube-apiserver.yaml and restarting the docker and kubelet system services using 
systemctl restart docker && systemctl restart kubelet. 

After doing this, kube-apiserver docker container is not coming up giving the errors as
   **"I0907 11:07:50.034358       1 server.go:121] Version: v1.9.1
error opening encryption provider configuration file "/etc/kubernetes/enc-conf.yaml": open /etc/kubernetes/enc-conf.yaml: no such file or directory"**

Can someone please help me getting this working in Kubernetes 1.9.1?
Any help would be appreciated :) 
Thanks in advance.

**Comment by tashirj** [comment]
Added the sig: /sig api-machinery

**Comment by liggitt** [comment]
How are you providing the file to the apiserver? If it is running inside a container, is that path and file available inside the container?

**Comment by tashirj** [comment]
The files are not available in the container. Is it required to be mounted explicitly inside container?
Since the image it using is of "gcr.io/google_containers/kube-apiserver", I am not modifying any of it's content explicitly.
Would you please suggest?

**Comment by liggitt** [comment]
Yes, it's a config file read by the apiserver process. It must be readable by that process. 

/close

**Comment by tashirj** [comment]
Why this file is not picked even if it is provided to be read by the process? I have given full permissions too.

**Comment by jeunii** [comment]
I ran into this issue on a `1.13.2` cluster.

The kubernetes official documentation makes no mention of adding this as a configMap though. https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
