### ISSUE TITLE
Issues for supporting block volume with CSI RBD driver 

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/kubernetes#68424]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
CSI RBD driver that implements block volume feature doesn't work well

**What you expected to happen**:
CSI RBD driver that implements block volume feature works well

**How to reproduce it (as minimally and precisely as possible)**:
Deploy [csi rbd](https://github.com/mkimuram/ceph-csi/commit/7f0af394bd5b32374477b05a1682978ebe33b449) driver that implement block volume feature, and attach block volume to pod.

**Anything else we need to know?**:
/sig storage

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.1173+a6eb49f0dc9a6d", GitCommit:"a6eb49f0dc9a6d9fecf7ff4a8edeaa382b55ac50", GitTreeState:"clean", BuildDate:"2018-09-07T20:53:12Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.1173+a6eb49f0dc9a6d", GitCommit:"a6eb49f0dc9a6d9fecf7ff4a8edeaa382b55ac50", GitTreeState:"clean", BuildDate:"2018-09-07T20:53:12Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mkimuram** [comment]
@vladimirvivien 

To make csi rbd driver work with block volume feature, there are three issues below.

Note that it could be worked around with a bit of changes in the kubernetes side:
[Code]
  - [kuberenetes](https://github.com/mkimuram/kubernetes/commit/83a84d2af1e381d1fec4bd224acc207dee37b665)
  - [csi rbd](https://github.com/mkimuram/ceph-csi/commit/7f0af394bd5b32374477b05a1682978ebe33b449)

So, I would like to discuss whether this fix is OK or we need to find better way.

[Issues]
1. symlinkPath used in ```MapDevice``` doesn't match to the one ```makeBlockVolumes``` expects
 
   As [```makeBlockVolumes```](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L112) expects symlinkpath to be the filename provided by ```GetPodDeviceMapPath```. ```MapDevice``` should pass the provided filename, [instead of "file"](https://github.com/mkimuram/kubernetes/commit/83a84d2af1e381d1fec4bd224acc207dee37b665#diff-ed824558531f8d1f616bc2f976266b64L205).


2. No need to create file in neither targetBlockFilePath nor globalMapPathBlockFile

   CSi driver will create symlink there either in ```NodeStageVolume``` or ```NodePublishVolume```, so kubelet won't need to create file there.


3. ```EvalHostSymlinksdevice``` fails for csi drivers that don't implement ```NodeStageVolume```
In current code, [```EvalHostSymlinksdevice```](https://github.com/mkimuram/kubernetes/commit/83a84d2af1e381d1fec4bd224acc207dee37b665#diff-450e811a4953f760ff1594ede8b2037eL895) tries to resolve symlink ```devicePath```, just after calling ```SetUpDevice``` and before calling ```MapDevice```. In CSI, ```SetUpDevice``` calls ```NodeStageVolume``` with expecting that it attaches the device and return symlink to it. However, for csi drivers that don't implement ```NodeStageVolume```, attaching device is done by ```NodePublishVolume``` which will be called from ```MapDevice```. So, in this case, ```EvalHostSymlinksdevice``` fails that there is no device in ```devicePath``` until ```MapDevice``` is called. Below change will workaround this issue:
  - Make ```SetUpDevice``` create ```globalMapPath``` directory and return ```globalMapPathBlockFile``` even when csi driver doesn't support ```NodeStageVolume```,
  - Move calling ```EvalHostSymlinksdevice``` after ```MapDevice```
  - Make ```NodePublishVolume``` create symlink to ```globalMapPathBlockFile```

**Comment by mkimuram** [comment]
@wongma7 @jsafrane 

3 above is related to containerized kubelet, so I need your comment for it.

**Comment by vladimirvivien** [comment]
@mkimuram thank you for pointing this out.

Let me investigate these issues and will reply here.  

You can also reach out on slack on #wg-csi channel for further questions.

**Comment by wongma7** [comment]
> Move calling EvalHostSymlinksdevice after MapDevice

I am okay with this in theory, but I will need to test it in containerized kubelet environment to be sure. There is no need for devicePath to exist for MapDevice/symlink create to work.

I don't understand the other solutions too well but returning an empty devicePath sounds weird to me. What if we just checked if devicePath is empty before we bother to call EvalHostSymlinksdevice

**Comment by mkimuram** [comment]
@wongma7 

> I am okay with this in theory, but I will need to test it in containerized kubelet environment to be sure. There is no need for devicePath to exist for MapDevice/symlink create to work.

Thank you for your confirmation. That's the exact point that I would like to confirm and I agree that we should test before this change.


> I don't understand the other solutions too well but returning an empty devicePath sounds weird to me. What if we just checked if devicePath is empty before we bother to call EvalHostSymlinksdevice

Actually, empty check for devicePath is already done just before it. However, it seems that the fact that devicePath isn't empty doesn't always mean that the actual device exists from the historical background.

**Comment by mkimuram** [comment]
@wongma7  @vladimirvivien 

I create PR #68635 . PTAL

Note that I separate the commit into three to make it easier to review.

Also, for issue 3, I changed the logic a little bit in order not to violate the csi's semantics.
This PR doesn't require ```NodePublishVolume``` to create symlink to staging path, instead ```GenerateMapVolumeFunc``` get ```devicePath``` by using information from ```GetPodDeviceMapPath``` after ```MapDevice``` and pass the ```devicePath``` to ```AttachFileDevice```.

By doing so, ```NodePublishVolume``` doesn't need to change its behaviour and ```devicePath``` for ```AttachFileDevice``` can always be resolved correctly.

**Comment by AishSundar** [comment]
/milestone v1.13
/priority important-soon

@nikopen 

This is important for 1.13 as mentioned in  #68635
