### ISSUE TITLE
Node goes Not Ready because of cri-containerd and containerd issues

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#68434]
Hi All,

i am running with a very very strange issue since 2 weeks ago.
let me describe in details what happened:

1. k8s node status Ready.
2. After few time (maybe 1 or 2 days maximum) node Status will be Not Ready with the following description:
[kubectl describe node.txt](https://github.com/containerd/cri/files/2363245/kubectl.describe.node.txt)

3. when i tried to open kubelet log i found the below:

[kubelet.log](https://github.com/containerd/cri/files/2363251/kubelet.log)

4. same thing i got logs for cri-containerd and containerd services

[cri-containerd.log](https://github.com/containerd/cri/files/2363254/cri-containerd.log)

[containerd.log](https://github.com/containerd/cri/files/2363256/containerd.log)

At this stage when i try to list sandboxes, using `sudo crictl sandboxes` and hangs for long time without giving any result.
Some kubernetes issues was commenting the `PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s` issue is that this is due to huge number of images in node. i was not running with such case but i cleaned up all images but unfortunately the issue appear after few time.

I am getting also the bellow issue from containerd which i do not know what it means:
`INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1`
`INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1`
`WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd`
`INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1`
`INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1`
`WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"`

my kubernetes cluster is running with the bellow info:

OS master and nodes: ubuntu 16.04
k8s version: 1.9.6
cri-containerd: 1.0.0-beta.1
containerd: `containerd github.com/containerd/containerd v1.0.0-6-g6c7abf7 6c7abf7c76c1973d4fb4b0bad51691de84869a51`

The only fix which i have now is to restart the node and it becomes directly Ready.
Also, yesterday i tried to delete all pods and sandboxes in the failed node using the `ctr` command,  the containers were deleted directly but the sandboxes where not fully deleted. the `ctr` command hangs so i stopped the containerd.service and tried to remove them manually from `/var/lib/cri-containerd/sandboxes` directory. it returms me `directory or device busy`. 
After advanced investigation i found out even the containerd.service stopped but there are processes running in the background related to it still running so i force delete them and restarted both cri-containerd and containerd services. So the node become Ready Again.

Please i need to fix this ASAP because it is a show stopper issue.
Any contribution to resolve this issue will be very appreciated.

**Comment by Random-Liu** [comment]
Close this one. let's carry on discussion in https://github.com/containerd/cri/issues/899.
