### ISSUE TITLE
The Pod cannot connect to the load balancer tied to the it.

### ISSUE THREAD

**Issue by asakapab0i** [kubernetes/kubernetes#68433]
/kind bug

**What happened**:
The pod cannot curl to the load balancer tied to it.

**What you expected to happen**:
It should connect and curl the load balancer ip address.

**How to reproduce it (as minimally and precisely as possible)**:
`bash-4.4# curl 
curl: try 'curl --help' or 'curl --manual' for more information
bash-4.4# curl 47.91.36.59 -v
* Rebuilt URL to: 47.91.36.59/
*   Trying 47.91.36.59...
* TCP_NODELAY set
^C
bash-4.4# ping 47.91.36.59 -v
PING 47.91.36.59 (47.91.36.59): 56 data bytes
64 bytes from 47.91.36.59: seq=0 ttl=100 time=0.305 ms
64 bytes from 47.91.36.59: seq=1 ttl=100 time=0.300 ms
64 bytes from 47.91.36.59: seq=2 ttl=100 time=0.296 ms
64 bytes from 47.91.36.59: seq=3 ttl=100 time=0.271 ms
^C
--- 47.91.36.59 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.271/0.293/0.305 ms
bash-4.4# `

**Anything else we need to know?**:
No

/sig pod-bug-cannot-connect

**Comment by jhorwit2** [comment]
/sig network

I think this has to do with a couple things. 

1. kube-proxy redirects traffic destined for external lb ips to the cluster ip. 
2. Misconfigured CNI results in pods being unable to curl the service the pod itself belongs to. You can read about that here and how to fix it. https://github.com/kubernetes/kubernetes/issues/20475
