### ISSUE TITLE
Added Shutdown/Close to SchedulingQueue

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#68453]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup
/sig scheduling

**Description**:

The `Pop` of `SchedulingQueue` will `cond.Wait` for new events; if `stopCh` is closed, the goroutine which uses `Pop` will not cleanup . It's better to add Shutdown/Close to SchedulingQueue to clean it up gracefully :)

**Comment by Huang-Wei** [comment]
I can help to cleanup.

/assign

**Comment by denkensk** [comment]
@Huang-Wei   Have you began to do it?  If not, Can I take it for my first-contribute? thx

**Comment by Huang-Wei** [comment]
@denkensk I'm working on it :)
