### ISSUE TITLE
Unlike "docker stop containerID", "docker pause containerID" doesn't trigger the creation of a new container

### ISSUE THREAD

**Issue by josephmansour** [kubernetes/kubernetes#68458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
I deployed a service (an HTML page that shows the Hostname of the webserver), with 2 replicas.  
Every time the command "curl <i>someIP</i>" is executed it displays the name of one of the 2 pods belonging to the service.
"docker ps " shows which containers that belong to the pods (e.g. b252372f72b4, 7c687bc2c157) . If I run "docker pause b252372f72b4" the command "curl <i>someIP</i>" hangs and doesn't display anything until i execute "docker unpause b252372f72b4". It seems that Kubernetes is not aware that the container's status is Pause and that it can't handle requests.
**What you expected to happen**:
Kubernetes reacts to "docker pause <i>containerID</i>" as it does to "docker stop <i>containerID</i>"

**How to reproduce it (as minimally and precisely as possible)**:

Run  "docker pause <i>containerID</i>"  where <i>containerID</i> belongs to one of the services
You'll notice that the service doesn't run properly. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by josephmansour** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by cblecker** [comment]
@kubernetes/sig-node-bugs 

/remove-sig contributor-experience
