### ISSUE TITLE
Support for ReadOnlyMany Access mode in openebs-iSCSI provisioner

### ISSUE THREAD

**Issue by ronakpandya7** [kubernetes/kubernetes#68467]
Hello,

We are using openebs(version 0.6) with provisioner iSCSI and deployed it in kubernetes version 1.10.5.

We created one pvc with access mode "ReadWriteOnce", and it is working fine.
Now we want to read data from the same PVC that we created earlier, so we come to know under this link from the table of content, that iSCSI is supporting "ReadOnlyMany" access mode.

But when we trien to apply it on our another pod it gives the following error:

<invalid> (x12 over <invalid>) openebs.io/provisioner-iscsi openebs-provisioner-5569654c96-4rlsn 760ae66d-9ebc-11e8-97d4-823996605407 Failed to provision volume with StorageClass "openebs-standard": Invalid Access Modes: [ReadOnlyMany], Supported Access Modes: [ReadWriteOnce]

So after googling this error we came across this issue.

So when will we expect support for ReadOnlyMany access mode?

Thanks.
Ronak

**Comment by wojtek-t** [comment]
@kubernetes/sig-storage-feature-requests
