### ISSUE TITLE
why dont support api for deleting collection of service?

### ISSUE THREAD

**Issue by chenyangxueHDU** [kubernetes/kubernetes#68468]
**What happened**:
I find some apis for for deleting collection of workloads, such as job, pod, but no api for svc. I want to know why?
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version 1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
the service api does special things on deletion (like tear down of associated loadbalancers, releasing allocated clusterIP, etc). Doing that complex tear down across plural objects hasn't been implemented yet.

**Comment by chenyangxueHDU** [comment]
@liggitt , ok, I understand. Thank you very mush, plz close the issue
