### ISSUE TITLE
portforward test is flaky - fix it

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#6846]
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws	1.520s	coverage: 25.5% of statements
I0414 23:19:35.411491   17545 portforward.go:228] Forwarding from 5000 -> 5000
W0414 23:19:35.427217   17545 portforward.go:183] Unable to listen on port {5000 5000}: listen tcp 127.0.0.1:5000: bind: address already in use
I0414 23:19:35.427821   17545 portforward.go:228] Forwarding from 6000 -> 6000
I0414 23:19:35.435015   17545 portforward.go:265] Handling connection for 5000
--- FAIL: TestForwardPorts (0.22s)
	portforward_test.go:295: 2: expected to read '1234', got ''
FAIL
coverage: 83.3% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/client/portforward	0.677s

**Comment by quinton-hoole** [comment]
It looks like the crux is this:

portforward.go:183] Unable to listen on port {5000 5000}: listen tcp 127.0.0.1:5000: bind: address already in use

listen often needs a retry after a recent close, to account for TIME_WAIT state of the port.

http://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states

But that's pure speculation on my part.  We need to repro and fix.

**Comment by quinton-hoole** [comment]
http://hea-www.harvard.edu/~fine/Tech/addrinuse.html  is perhaps a better link.

**Comment by quinton-hoole** [comment]
I'll have a go at it in the next few days if nobody else picks it up before me.

**Comment by liggitt** [comment]
There were two issues... one was multiple test cases reusing the same port and deferring the close until the end of the function, not the end of the loop... that was fixed in #12162 

The other issue was with the fake stream returning an EOF on a Write(), fixed in #13107
