### ISSUE TITLE
I want to know how much risk “externalTrafficPolicy = local” for unbalanced traffic load balance

### ISSUE THREAD

**Issue by vvkkhjt** [kubernetes/kubernetes#68474]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind report

**What happened**:
When I need to get external real IP,I set up "service.spec.externalTrafficPolicy=local"

**What you expected to happen**:
I checked the official documents and found them:

service.spec.externalTrafficPolicy - denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. There are two available options: “Cluster” (default) and “Local”. “Cluster” obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading. “Local” preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type services, but risks potentially imbalanced traffic spreading.

**Anything else we need to know?**:
I currently have a game project ready to use k8s and need to get the user's real ip, but the document says that setting externalTrafficPolicy = local will affect the risk of load balancing imbalances, and I want to know how much of the risk is there?

**Comment by vvkkhjt** [comment]
> @vvkkhjt did you found any solution for this issue to preserve client IP?

what do you mean?preserve client IP?I just want get real IP and want know how risk of I set "externalTrafficPolicy = local",
but now I found when I set "externalTrafficPolicy = local",the traffic will flow to only one of these nodes,
Load balancing doesn't work

**Comment by vvkkhjt** [comment]
> > > @vvkkhjt did you found any solution for this issue to preserve client IP?
> > 
> > 
> > what do you mean?preserve client IP?I just want get real IP and want know how risk of I set "externalTrafficPolicy = local",
> > but now I found when I set "externalTrafficPolicy = local",the traffic will flow to only one of these nodes,
> > Load balancing doesn't work
> 
> By Preserving client IP I was referring to getting the real IP. Just wanted to check with you any workaround you found for the problem. I am also facing the same issue.

you can set "externalTrafficPolicy = local" in Service->spec->externalTrafficPolicy,change Cluster to Local,Note the capital letters,then you can get the real IP

**Comment by thockin** [comment]
The risk here is particularly when there are a lot replicas on some nodes and only a few repicas on other nodes.  Without knowing your app it's hard to say how it is structured.  If you have many replicas behind the LB, that is the danger.

**Comment by DanielYWoo** [comment]
>>Local” preserves the client source IP and avoids a second hop for LoadBalancer and NodePort type services
If the packet goes to a node without the pods, a second hop is still needed, right?

**Comment by thockin** [comment]
No, if you send such a packet to a node with no backends, it will be black-holed.

This is a way to build traffic systems, not an all-in-one solution.  Most cloud LBs, for example, are smart enough to health heck the nodes and deselect nodes with no backends.

Kube-proxy even offers a port per-service which will pass more information up.
