### ISSUE TITLE
gonum.org/v1/gonum module conflicts with use of golang.org/x/exp/inotify

### ISSUE THREAD

**Issue by sigma** [kubernetes/kubernetes#68478]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

the `gonum.org/v1/gonum` module as a whole depends on `golang.org/x/exp/rand`, which has been introduced after `golang.org/x/exp/inotify` (which we depend on) was retired.

We are currently "lucky" in the sense that the subset of `gonum.org/v1/gonum` we use actually doesn't depend on `golang.org/x/exp`, so that we get away with using an outdated version of golang.org/x/exp by virtue of the fact that godep doesn't track any of this.

Go modules are not that forgiving though, and the current situation is not a valid solution to the system of constraints they consider. Therefore this issue blocks a migration to go modules.

**What you expected to happen**:

The dependency graph should be more consistent

**Anything else we need to know?**:

`inotify` is a can of worms, and past migrations to the maintained `fsnotify` have been repeatedly reverted. It's unclear that there is an easy way out.
Arguably the path of least resistance would be to properly fork the old `inotify` codebase into a standalone package, that both `kubelet` and `cadvisor` can depend on without holding back other parts of the dependency graph. Then migration to `fsnotify` can proceed at its own pace.

**Comment by sigma** [comment]
@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
@yujuhong for inotify / node :-)

**Comment by dims** [comment]
@sigma now that we have `https://github.com/sigma/go-inotify` do we still need this issue open?

**Comment by sigma** [comment]
@dims we still use golang.org/x/exp/inotify in kubernetes. Let me open a PR to fix that, after which we should be good on that front
