### ISSUE TITLE
isDeviceOpened check for cinder could use invalid device path

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#68479]
We fixed invalid device path in bunch of places via - https://github.com/kubernetes/kubernetes/pull/33270 but `isDeviceOpen` call still could use invalid device path.

That check can sometimes use invalid path and hence can cause UnmountDevice operation to fails even though device has already been unmounted.

/sig storage
/sig openstack

/assign

**Comment by gnufied** [comment]
Actually this does not affect version 1.10 onwards. Not sure if 1.9 is still supported. I think I will close this for now.

/close

**Comment by gnufied** [comment]
I just noticed that 1.9 is still supported and hence it is probably worth fixing there for now.

**Comment by msau42** [comment]
How come the check can "sometimes" use invalid device path?

**Comment by gnufied** [comment]
@msau42 So on Cinder for example - `Attach` call would return something like `/dev/sdb` as attach device path. But if you see the linked PR(https://github.com/kubernetes/kubernetes/pull/33270), `WaitForAttach` will do a `/dev/disk/by-id` and use that device path for global mount.  In general it is always a good idea to use device path returned by `WaitForAttach` as single source of truth.

This applies to something like EBS with NVMe too where device is discovered via `WaitForAttach` call (but nvme disks aren't directly affected by this bug because returned device path on EBS is bogus).

**Comment by msau42** [comment]
You said the issue only happens "sometimes".  Can you clarify why it only happens occasionally?

**Comment by gnufied** [comment]
@msau42 doesn't the linked PR https://github.com/kubernetes/kubernetes/pull/33270 make it clear? 

> We can't rely on the device name provided by Cinder, and thus must perform
detection based on the drive serial number (aka It's cinder ID) on the
kubelet itself.

As for why - Cinder sometimes returns wrong device path on `AttachDevice` call, I don't know. But it happens and we have worked around it.

**Comment by gnufied** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/68674
