### ISSUE TITLE
Scheduler documents deprecated flags but does not provide its replacement

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#68488]
/kind bug

**What happened**:

The scheduler command line flag documentation notes that both "--address" and "--port" are deprecated flags and suggest alternatives ("--bind-address" and "--secure-port" respectively). Those alternatives are not listed and probably not implemented.

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

/cc @misterikkit

**Comment by misterikkit** [comment]
Does `MetricsBindAddress` expose what you need?

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/types.go#L67

**Comment by tossmilestone** [comment]
I think this is a doc issue, and should be fixed in at kubernetes/website

**Comment by misterikkit** [comment]
/remove-lifecycle stale
/close

I think this was fixed by https://github.com/kubernetes/kubernetes/pull/68497 and we can close the issue.
