### ISSUE TITLE
Consider to add an option for PodSecurityPolicy  to support a blacklist for hostpath

### ISSUE THREAD

**Issue by YuxiJin-tobeyjin** [kubernetes/kubernetes#68507]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature
@kubernetes/sig-auth-feature-requests

**What happened**:
We now have "allowedHostPath" as an option for PodSecurityPolicy，which is whitelist of hostpaths that pod can use. But under some scenarios when pod is  restricted to use only one or some specified paths，then a black list of hostpath may be much more useful. 
For example, if we want to forbid pod to use the hostpath "/root" and its subpath, we need to add all paths but "/root" in allowedHostPath, which is extremly inefficient, resulting poor user experience.
**What you expected to happen**:
Add an option for PodSecurityPolicy, such as "disallowedHostPath", including a blacklist of hostpaths that pod can not use.

**Comment by Pingan2017** [comment]
cc @liggitt

**Comment by liggitt** [comment]
> Add an option for PodSecurityPolicy, such as "disallowedHostPath", including a blacklist of hostpaths that pod can not use.

A blacklist for hostPath would not be effective. A container could create a symlink to any folder it wished inside a non-blacklisted hostPath, then mount that symlink directly in a second container, and obtain access to any path desired.

**Comment by liggitt** [comment]
Closing since this would not be practical to implement, and would not actually provide the expected protection. 

/close

**Comment by YuxiJin-tobeyjin** [comment]
@liggitt
 Yes，but even the currently implemented  white list has the same problem.
 I think for most cases this feature can be used to forbid pod to mount specified volumes explicitly during its creation, Symlink is some kind like a trick or a backdoor , if administrator really want to protect its system, he may delete the symlink at the first place. 
btw, I'm working on a PR to implement this feature.
Would you please take a reconsideration，many thanks.

**Comment by YuxiJin-tobeyjin** [comment]
/reopen 
cc @liggitt @deads2k

**Comment by liggitt** [comment]
> even the currently implemented white list has the same problem

if we'd been aware of the issue when the currently whitelist was added, it would have required an exact match, not just a prefix match (I'd like to see that capability added in the future). also, the currently implemented set of allowed paths can require the allowed hostpath volumes be mounted readonly, which prevents creation of symlinks.

> Symlink is some kind like a trick or a backdoor

a security policy that is trivially vulnerable to tricks and back doors isn't worth much.

> if administrator really want to protect its system, he may delete the symlink at the first place

that introduces a race between any symlink cleanup attempts, and any creation attempts. It's not a good idea to add features to a security policy that prevent it from being deterministically correct and enforceable

> btw, I'm working on a PR to implement this feature. Would you please take a reconsideration, many thanks.

I wouldn't be in favor of adding this unless the symlink issue is addressed

**Comment by YuxiJin-tobeyjin** [comment]
@liggitt 
Okay, I see，thanks a lot. 
/close
