### ISSUE TITLE
Failing Test : gck-gke up

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68509]
# Failing Jobs
[sig-release-master-blocking#gci-gke](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke)
# Failing Tests
[Up](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/31532)

/kind failing-test
/priority critical-urgent
/milestone v1.12
/sig gcp
/cc @tpepper @AishSundar @kubernetes/sig-gcp-test-failures

**Comment by AishSundar** [comment]
/assign @barney-s 
/cc @sebastienvas 

@barney-s and @sebastienvas we are seeing new buckets of Gci-gke jobs failing Up: Only [one commit in k/k](https://github.com/kubernetes/kubernetes/compare/c0953ed2d...36877dafe) yesterday Looks like hosting issue. Can you please take a look. Thanks

**Comment by yaseenhamdulay** [comment]
The gcloud create command has the cluster version set as 1.13. That's not right is it?

error creating cluster: error during gcloud container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard --project=gke-up-g1-3-g1-5-up-mas --zone=us-central1-f --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --network=e2e-31578-fbb42 --cluster-version=1.13.0-alpha.0.1226+426ef9d349bb3a e2e-31578-fbb42: exit status 1

**Comment by juanvallejo** [comment]
I am seeing this failure in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-sig-cli/3848 as well

**Comment by verult** [comment]
This is due to a storage bug caused by https://github.com/kubernetes/kubernetes/pull/68426/files#diff-f52821ec6236e86b02ca334533395c91R166.

Working on a fix

/assign
