### ISSUE TITLE
Should support graceful deletion for CR storage 

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#68508]
/kind bug
/sig api-machinery

another bug uncovered by #68405. in the extension server, we are removing old CR's storage when some significant changes (spec, some status) land in the corresponding CRD with the help of CRD informer. but when we're destroying the old CRD's storage, there are might be some remaining requests invoking etcd client from the old storage. so a racing happens when the CRD's informer trying to delete/close the old storage together with the old etcd client and the running handler trying to call REST interface via that client. as a result, the handler will fail with a `context canceled` or `grpc: the client connection is closing` which is the reason #68405 is flaky. 

in a word, __updating CRD will fail all processing CR requests__. 

@sttts proposes to make use of the [apimachinery WaitGroup](https://github.com/kubernetes/kubernetes/pull/54849) for the storage and we only delete a storage when the all the running handler's finished. but we might left some problem with that:

- do we count the `WaitGroup` only in the handler ignoring other etcd client references like compactor?  
- ~how will this impact server's performance?~
- does it have to be a `WaitGroup`?
- what about some long running handlers? `watch` has a timeout itself tho, what about infinite handlers like `proxyport`?

otoh, we can add a cooldown period (minute-ish?) for older cr storage to postpone the actual deletion for that storage. surely, it's not stable but a cooldown will at least keep most of short-running handler from failing.

@deads2k @stttts

**Comment by yue9944882** [comment]
additionally, it reveals another deeper problem: the watch connection will fail every time we update CRD and we miss some watch events due to switching CRD storage at that time. tho we don't update CRD's frequently, missing any event in the external controller relying on CRD is critical.

**Comment by liggitt** [comment]
> the watch connection will fail every time we update CRD

closing the watch connection is probably fine

> we miss some watch events due to switching CRD storage at that time

how are they missed? clients are expected to reestablish watches when they close

**Comment by yue9944882** [comment]
> closing the watch connection is probably fine

@liggitt hmm.. imho, that depends. for informer/reflector if the watch close, and we miss some event during the reestablishing, then the new watch will fail with a ResourceVersion confliction, right? and then in another round of `ListAndWatch`, we will roughly replace the items in the cache with the latest. if the controller doesn't care about the missing events and will reconcile correctly , it's okay to close the watch.

**Comment by liggitt** [comment]
> for informer/reflector if the watch close, and we miss some event during the reestablishing, then the new watch will fail with a ResourceVersion confliction, right? and then in another round of ListAndWatch, we will roughly replace the items in the cache with the latest.

Yes. That is normal operation for a list/watch-fed informer.

**Comment by liggitt** [comment]
closing as duplicate of https://github.com/kubernetes/kubernetes/issues/56567

/close

**Comment by liggitt** [comment]
oops, clicked on the wrong issue title. this is not talking about graceperiodseconds in deleteoptions

/reopen
