### ISSUE TITLE
kube-proxy pod do not initialize due to lack access to /proc/sys @kubernetes/sig-network

### ISSUE THREAD

**Issue by grzegorzpnk** [kubernetes/kubernetes#68504]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
After execute kubeadm init
during kube-proxy pod initialization there is CrashLoopBackOff error all the time

Logs from pod: 
[centos@server-k8s-clust-kubernetes-master-host-hkg9ht ~]$ kubectl logs kube-proxy-8gs45  -n kube-system

> W0911 10:29:19.932277       1 server_others.go:295] Flag proxy-mode="" unknown, assuming iptables proxy
> I0911 10:29:19.942554       1 server_others.go:148] Using iptables Proxier.
> F0911 10:29:19.942577       1 server.go:361] unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system

**What you expected to happen**:
kube-proxy pod run properly

**How to reproduce it (as minimally and precisely as possible)**:
1. First follow instruction: https://kubernetes.io/docs/setup/independent/install-kubeadm/

2. Next try to execute: `sudo kubeadm init --kubernetes-version=1.12.0-beta.1`

**Environment**:
- Kubernetes version (use `kubectl version`):

> Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.1", GitCommit:"553515b823634919e731774556fae554c95a6a5f", GitTreeState:"clean", BuildDate:"2018-09-05T03:30:08Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

> OpenStack

- OS (e.g. from /etc/os-release):

> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

> Linux server-k8s-clust-kubernetes-master-host-hkg9ht.openstacklocal 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

> Docker 18.06.0-ce

- Others:

**Comment by adhipati-blambangan** [comment]
I have exactly the same problem with the 1.12.0-beta.1. Does kube-proxy really need access to /proc/sys/* in this case?

**Comment by aanm** [comment]
Same problem with Ubuntu `18.04.1`

**Comment by liqlin2015** [comment]
Does that mean kube-proxy can only be run outside of container?

**Comment by dims** [comment]
/priority critical-urgent
/milestone v1.12

Sorry the activity and urgency is reflected in the PR :)

**Comment by guineveresaenger** [comment]
@dims welp! sorry about that!

**Comment by liqlin2015** [comment]
@dims I still get this issue with latest master branch code. 

```
I0919 04:42:35.663086       1 server_others.go:148] Using iptables Proxier.
F0919 04:42:35.663139       1 server.go:360] unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system
```

**Comment by timothysc** [comment]
@dims I'm still seeing this on RC1, did this land before the release was cut?

https://paste.fedoraproject.org/paste/KvdsUOR-IrnWmHRA2LJlSQ  

/cc @tpepper  @kubernetes/sig-cluster-lifecycle

**Comment by dims** [comment]
update from @dougm : `PR 68803 missed RC.1:`

```
% git branch -r --contains 02489f89
  upstream/master
  upstream/release-1.12
% git tag --contains 02489f89
```

**Comment by timothysc** [comment]
I just verified on release-1.12 branch and it's good.
