### ISSUE TITLE
Failing Test: Verify 1.12

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68510]
#Failing Jobs
[sig-release-1.12-all#verify-1.12](https://k8s-testgrid.appspot.com/sig-release-1.12-all#verify-1.12)
# Failing Tests
[verify godeps, verify staging-godeps](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-beta/2327)

/kind failing-test
/priority critical-urgent
/milestone v1.12
/cc @tpepper @AishSundar 
/sig release

**Comment by AishSundar** [comment]
/cc @dims @dougm @BenTheElder 

This job started failing since yesterday, 9/10 night.

**Comment by dims** [comment]
@AishSundar looks like something wrong in gopkg.in service itself. if i hit https://gopkg.in/gcfg.v1 on your browser i get

```
Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-gcfg/gcfg.git/info/refs?service=git-upload-pack: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

and a simple `go get` does not work either

```
[dims@dims-mac 08:35] ~/go/src/k8s.io ⟩ go get gopkg.in/yaml.v1
package gopkg.in/yaml.v1: unrecognized import path "gopkg.in/yaml.v1" (parse https://gopkg.in/yaml.v1?go-get=1: no go-import meta tags ())
```

**Comment by dims** [comment]
being worked on here - https://github.com/niemeyer/gopkg/issues/63

**Comment by dougm** [comment]
Note that this shouldn't block the beta.2 build, since the issue is only hit during `verify-godeps`.  CI runs that step, but release builds does not afaict.  Though would prefer to have the gopkg.in issue resolved prior to the beta build of course.
