### ISSUE TITLE
Add more e2es for topology aware dynamic provisioning

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#68517]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 

**What happened**:
Some more test cases to run in a multizone environment:
- Deployment that requests multiple pvcs
- Statefulset using nodeSelector on two specific zones (out of 3), and multiple pvcs
- Nodes in specific zones get tainted

**Comment by msau42** [comment]
cc @ddebroy is this something you can help with?

**Comment by ddebroy** [comment]
Yes certainly. On my radar as we discussed.
