### ISSUE TITLE
kubernetes node goes to not-ready state

### ISSUE THREAD

**Issue by Deepak3994** [kubernetes/kubernetes#68542]
I was trying to setup a kubernetes cluster. After I have joined the nodes, I checked for the status and the following ouputs are as follows:

**$ kubectl get nodes**
NAME       STATUS     ROLES     AGE       VERSION
deepak     NotReady   <none>    20m       v1.11.3
hamid123   Ready      master    31m       v1.11.3

**$ kubectl describe nodes**
Name:               deepak
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=deepak
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket=/var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Wed, 12 Sep 2018 02:33:32 -0400
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:33:32 -0400   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:33:32 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     True    Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:33:42 -0400   KubeletHasDiskPressure       kubelet has disk pressure
  PIDPressure      False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:33:32 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:33:32 -0400   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:  10.184.10.165
  Hostname:    deepak
Capacity:
 cpu:                28
 ephemeral-storage:  1837643084Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             130632812Ki
 pods:               110
Allocatable:
 cpu:                28
 ephemeral-storage:  1693571863411
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             130530412Ki
 pods:               110
System Info:
 Machine ID:                 810f44a76135411c9bbbfa0c252bfd1e
 System UUID:                4C4C4544-005A-4810-8036-C4C04F394E32
 Boot ID:                    21becf92-a352-4923-84cb-341a26e0c3d5
 Kernel Version:             4.15.0-34-generic
 OS Image:                   Ubuntu 16.04.5 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.11.2
 Kube-Proxy Version:         v1.11.2
PodCIDR:                     192.168.1.0/24
Non-terminated Pods:         (2 in total)
  Namespace                  Name                 CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                 ------------  ----------  ---------------  -------------
  kube-system                calico-node-pzftf    250m (0%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-2drxr     0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests   Limits
  --------  --------   ------
  cpu       250m (0%)  0 (0%)
  memory    0 (0%)     0 (0%)
Events:
  Type     Reason                   Age                 From             Message
  ----     ------                   ----                ----             -------
  Normal   Starting                 15m                 kubelet, deepak  Starting kubelet.
  Normal   NodeHasSufficientDisk    15m                 kubelet, deepak  Node deepak status is now: NodeHasSufficientDisk
  Normal   NodeHasSufficientMemory  15m                 kubelet, deepak  Node deepak status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    15m                 kubelet, deepak  Node deepak status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     15m                 kubelet, deepak  Node deepak status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  15m                 kubelet, deepak  Updated Node Allocatable limit across pods
  Normal   NodeHasDiskPressure      14m                 kubelet, deepak  Node deepak status is now: NodeHasDiskPressure
  Warning  EvictionThresholdMet     12m (x18 over 15m)  kubelet, deepak  Attempting to reclaim ephemeral-storage
  Warning  ImageGCFailed            10m                 kubelet, deepak  wanted to free 214231040819 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 2cb0d9787c4d (must be forced) - image is being used by stopped container a8ffd42f3f6f
  Warning  ImageGCFailed            5m                  kubelet, deepak  wanted to free 214231692083 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 2cb0d9787c4d (must be forced) - image is being used by stopped container 92afc5ca9c0c
  Warning  ImageGCFailed            9s                  kubelet, deepak  wanted to free 214232314675 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 2cb0d9787c4d (must be forced) - image is being used by stopped container 92afc5ca9c0c

Name:               hamid123
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=hamid123
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket=/var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Wed, 12 Sep 2018 02:22:31 -0400
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:22:29 -0400   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:22:29 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:22:29 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:22:29 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 12 Sep 2018 02:48:33 -0400   Wed, 12 Sep 2018 02:28:52 -0400   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.184.10.179
  Hostname:    hamid123
Capacity:
 cpu:                28
 ephemeral-storage:  1837643084Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             130632820Ki
 pods:               110
Allocatable:
 cpu:                28
 ephemeral-storage:  1693571863411
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             130530420Ki
 pods:               110
System Info:
 Machine ID:                 810f44a76135411c9bbbfa0c252bfd1e
 System UUID:                4C4C4544-005A-4810-8037-C4C04F394E32
 Boot ID:                    9bc55e59-f5e3-4cb9-836f-df4c9dd4b088
 Kernel Version:             4.15.0-33-generic
 OS Image:                   Ubuntu 16.04.5 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.6.1
 Kubelet Version:            v1.11.3
 Kube-Proxy Version:         v1.11.3
PodCIDR:                     192.168.0.0/24
Non-terminated Pods:         (11 in total)
  Namespace                  Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                       ------------  ----------  ---------------  -------------
  kube-system                calico-etcd-5sr92                          0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                calico-kube-controllers-cd589c58b-9cktk    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                calico-node-dzvh2                          250m (0%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                coredns-78fcdf6894-7fdwv                   100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)
  kube-system                coredns-78fcdf6894-xwmql                   100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)
  kube-system                etcd-hamid123                              0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-apiserver-hamid123                    250m (0%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-controller-manager-hamid123           200m (0%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-jl9p2                           0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-scheduler-hamid123                    100m (0%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                kubernetes-dashboard-767dc7d4d-xfgrj       0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests    Limits
  --------  --------    ------
  cpu       1 (3%)      0 (0%)
  memory    140Mi (0%)  340Mi (0%)
Events:
  Type    Reason                   Age                From                  Message
  ----    ------                   ----               ----                  -------
  Normal  Starting                 26m                kubelet, hamid123     Starting kubelet.
  Normal  NodeAllocatableEnforced  26m                kubelet, hamid123     Updated Node Allocatable limit across pods
  Normal  NodeHasSufficientPID     26m (x5 over 26m)  kubelet, hamid123     Node hamid123 status is now: NodeHasSufficientPID
  Normal  NodeHasSufficientDisk    26m (x6 over 26m)  kubelet, hamid123     Node hamid123 status is now: NodeHasSufficientDisk
  Normal  NodeHasSufficientMemory  26m (x6 over 26m)  kubelet, hamid123     Node hamid123 status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    26m (x6 over 26m)  kubelet, hamid123     Node hamid123 status is now: NodeHasNoDiskPressure
  Normal  Starting                 25m                kube-proxy, hamid123  Starting kube-proxy.
  Normal  NodeReady                19m                kubelet, hamid123     Node hamid123 status is now: NodeReady

As i see its showing "DiskPressure" as true. So, can anyone suggest me how to solve this issue.

**Comment by tanshanshan** [comment]
does your node  have enough disk space , try to clean some unused file?
use `df -h`  to look

**Comment by tianshapjq** [comment]
looks like your node doesn't have a cni plugin available, you can try flannel or anthing else that works on your another node.

**Comment by Deepak3994** [comment]
> does your node have enough disk space , try to clean some unused file?
> use `df -h` to look


I did  **$ df -h** on the system where node is present.

**Filesystem**      **Size**  **Used** **Avail** **Use%** **Mounted on**
udev                  63G     0         63G   0% /dev
tmpfs            13G   90M   13G   1% /run
**/dev/nvme0n1p2**  1.8T  1.5T  151G  **91%** /
tmpfs            63G  608K   63G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/nvme0n1p1  511M  3.5M  508M   1% /boot/efi
tmpfs            13G   88K   13G   1% /run/user/1000
/dev/sdc2       3.7T  939G  2.8T  26% /media/administrator/Seagate Backup Plus Drive

I have highlighted in the above output. It showed the usage percentage as 91%. Is it because of this?

**Comment by Deepak3994** [comment]
> looks like your node doesn't have a cni plugin available, you can try flannel or anthing else that works on your another node.

I have installed "calico" that would be fine, ryt ?

**Comment by neolit123** [comment]
@Deepak3994 

as suggested, please provide the kubelet logs `journalctl -xeu kubelet` also check the state of the callico pods via `kubectl get pods --all-namespaces`

also your report is missing some detail, please take a look at this:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md
`Environment:......`

**Comment by Deepak3994** [comment]
Hi,

I think the error is related to "required kernel modules". When i treied to join another node/ system to the kubernete master, I got the follwoing error.

[preflight] running pre-flight checks
	[WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh] or no builtin kernel ipvs support: map[ip_vs_wrr:{} ip_vs_sh:{} nf_conntrack_ipv4:{} ip_vs:{} ip_vs_rr:{}]
you can solve this problem with following methods:
 1. Run 'modprobe -- ' to load missing kernel modules;
2. Provide the missing builtin kernel ipvs support

So, anyone can suggest how to solve this or how to use the "modeprobe --" which is mentioned above.

**Comment by Deepak3994** [comment]
> @Deepak3994
> 
> as suggested, please provide the kubelet logs `journalctl -xeu kubelet` also check the state of the callico pods via `kubectl get pods --all-namespaces`
> 
> also your report is missing some detail, please take a look at this:
> https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md
> `Environment:...`

Output of "kubectl get pods --all-namespaces"

NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-pxmkt                         1/1       Running   0          9m
kube-system   calico-kube-controllers-cd589c58b-s7h8c   1/1       Running   0          9m
**kube-system   calico-node-fwbkh                         0/2       Pending   0          1s**
kube-system   calico-node-rst6t                         2/2       Running   0          9m
kube-system   coredns-78fcdf6894-jskp5                  1/1       Running   0          13m
kube-system   coredns-78fcdf6894-snp6w                  1/1       Running   0          13m
kube-system   etcd-hamid123                             1/1       Running   0          12m
kube-system   kube-apiserver-hamid123                   1/1       Running   0          12m
kube-system   kube-controller-manager-hamid123          1/1       Running   0          12m
kube-system   kube-proxy-mdqkf                          0/1       Pending   0          0s
kube-system   kube-proxy-rvwvg                          1/1       Running   0          13m
kube-system   kube-scheduler-hamid123                   1/1       Running   0          12m
kube-system   kubernetes-dashboard-767dc7d4d-prh84      1/1       Running   0          9m

**The Calico-node is always in pending state. May I know why?**

Output of " journalctl -xeu kubelet "

Sep 18 05:11:26 hamid123 kubelet[27075]: unAsNonRoot:nil,ReadOnlyRootFilesystem:*true,AllowPrivilegeEscalation:*false,} false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDea
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.099 [INFO][3974] utils.go 327: Configured environment: [CNI_COMMAND=ADD CNI_CONTAINERID=0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b
Sep 18 05:11:27 hamid123 kubelet[27075]: Calico CNI IPAM request count IPv4=1 IPv6=0
Sep 18 05:11:27 hamid123 kubelet[27075]: Calico CNI IPAM handle=k8s-pod-network.0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.100 [INFO][3974] calico-ipam.go 186: Auto assigning IP ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5" HandleID=
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.100 [INFO][3974] ipam.go 69: Auto-assign 1 ipv4, 0 ipv6 addrs for host 'hamid123'
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.101 [INFO][3974] ipam.go 250: Looking up existing affinities for host handle="k8s-pod-network.0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.102 [INFO][3974] ipam.go 271: Trying affinity for 192.168.21.192/26 handle="k8s-pod-network.0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.102 [INFO][3974] ipam.go 117: Attempting to load block cidr=192.168.21.192/26 host="hamid123"
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.102 [INFO][3974] ipam.go 194: Affinity is confirmed and block has been loaded cidr=192.168.21.192/26 host="hamid123"
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.102 [INFO][3974] ipam.go 668: Attempting to assign 1 addresses from block block=192.168.21.192/26 handle="k8s-pod-network.0cf2bbe19458ec3ceb490
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.103 [INFO][3974] ipam.go 1093: Creating new handle: k8s-pod-network.0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.103 [INFO][3974] ipam.go 691: Writing block in order to claim IPs block=192.168.21.192/26 handle="k8s-pod-network.0cf2bbe19458ec3ceb490628843f6
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.105 [INFO][3974] ipam.go 701: Successfully claimed IPs: [192.168.21.218] block=192.168.21.192/26 handle="k8s-pod-network.0cf2bbe19458ec3ceb4906
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.105 [INFO][3974] ipam.go 303: Block '192.168.21.192/26' provided addresses: [192.168.21.218] handle="k8s-pod-network.0cf2bbe19458ec3ceb49062884
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.110 [INFO][3974] ipam.go 458: Auto-assigned 1 out of 1 IPv4s: [192.168.21.218] handle="k8s-pod-network.0cf2bbe19458ec3ceb490628843f6060451072ba
Sep 18 05:11:27 hamid123 kubelet[27075]: Calico CNI IPAM assigned addresses IPv4=[192.168.21.218] IPv6=[]
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.110 [INFO][3974] calico-ipam.go 214: IPAM Result ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5" HandleID="k8s-p
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.115 [INFO][3905] k8s.go 267: Populated endpoint ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5" Namespace="kube-
Sep 18 05:11:27 hamid123 kubelet[27075]: Calico CNI using IPs: [192.168.21.218/32]
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.115 [INFO][3905] network.go 31: Setting the host side veth name to calic0c250472a7 ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7be
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.116 [INFO][3905] network.go 326: Disabling IPv4 forwarding ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5" Names
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.166 [INFO][3905] k8s.go 294: Added Mac, interface name, and active container ID to endpoint ContainerID="0cf2bbe19458ec3ceb490628843f6060451072
Sep 18 05:11:27 hamid123 kubelet[27075]: 2018-09-18 05:11:27.181 [INFO][3905] k8s.go 302: Wrote updated endpoint to datastore ContainerID="0cf2bbe19458ec3ceb490628843f6060451072ba6b7e7bed0a3645b7e163f3b5"
Sep 18 05:11:32 hamid123 kubelet[27075]: I0918 05:11:32.294724   27075 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp-volume" (UniqueName: "kubernetes.io/empty
Sep 18 05:11:32 hamid123 kubelet[27075]: I0918 05:11:32.294786   27075 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubernetes-dashboard-token-dnfkt" (UniqueName
Sep 18 05:11:32 hamid123 kubelet[27075]: I0918 05:11:32.294890   27075 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubernetes-dashboard-certs" (UniqueName: "kub
Sep 18 05:11:33 hamid123 kubelet[27075]: W0918 05:11:33.604920   27075 pod_container_deletor.go:75] Container "3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" not found in pod's containe
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.695 [INFO][4449] calico.go 68: Extracted identifiers EndpointIDs=&utils.WEPIdentifiers{Namespace:"kube-system", WEPName:"", WorkloadEndpointIde
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.695 [INFO][4449] calico.go 69: Loaded CNI NetConf NetConfg=types.NetConf{CNIVersion:"0.3.0", Name:"k8s-pod-network", Type:"calico", IPAM:struct
Sep 18 05:11:33 hamid123 kubelet[27075]: netes:types.Kubernetes{K8sAPIRoot:"", Kubeconfig:"/etc/cni/net.d/calico-kubeconfig", NodeName:""}, EtcdScheme:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCaCertFile:"
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.695 [INFO][4449] utils.go 327: Configured environment: [CNI_COMMAND=ADD CNI_CONTAINERID=3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.698 [INFO][4449] k8s.go 60: Extracted identifiers for CmdAddK8s ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" 
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.768 [INFO][4449] k8s.go 660: pod info &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kubernetes-dashboard-767dc7d4d-prh84
Sep 18 05:11:33 hamid123 kubelet[27075]: nt nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{}
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.863 [INFO][4485] utils.go 327: Configured environment: [CNI_COMMAND=ADD CNI_CONTAINERID=3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b
Sep 18 05:11:33 hamid123 kubelet[27075]: Calico CNI IPAM request count IPv4=1 IPv6=0
Sep 18 05:11:33 hamid123 kubelet[27075]: Calico CNI IPAM handle=k8s-pod-network.3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.865 [INFO][4485] calico-ipam.go 186: Auto assigning IP ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" HandleID=
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.865 [INFO][4485] ipam.go 69: Auto-assign 1 ipv4, 0 ipv6 addrs for host 'hamid123'
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.866 [INFO][4485] ipam.go 250: Looking up existing affinities for host handle="k8s-pod-network.3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e3846
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.866 [INFO][4485] ipam.go 271: Trying affinity for 192.168.21.192/26 handle="k8s-pod-network.3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463d
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.867 [INFO][4485] ipam.go 117: Attempting to load block cidr=192.168.21.192/26 host="hamid123"
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.867 [INFO][4485] ipam.go 194: Affinity is confirmed and block has been loaded cidr=192.168.21.192/26 host="hamid123"
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.867 [INFO][4485] ipam.go 668: Attempting to assign 1 addresses from block block=192.168.21.192/26 handle="k8s-pod-network.3e6d114aa8e5c5a348791
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.868 [INFO][4485] ipam.go 1093: Creating new handle: k8s-pod-network.3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.869 [INFO][4485] ipam.go 691: Writing block in order to claim IPs block=192.168.21.192/26 handle="k8s-pod-network.3e6d114aa8e5c5a3487913efd7000
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.884 [INFO][4485] ipam.go 701: Successfully claimed IPs: [192.168.21.219] block=192.168.21.192/26 handle="k8s-pod-network.3e6d114aa8e5c5a3487913
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.884 [INFO][4485] ipam.go 303: Block '192.168.21.192/26' provided addresses: [192.168.21.219] handle="k8s-pod-network.3e6d114aa8e5c5a3487913efd7
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.889 [INFO][4485] ipam.go 458: Auto-assigned 1 out of 1 IPv4s: [192.168.21.219] handle="k8s-pod-network.3e6d114aa8e5c5a3487913efd70001a565875c7d
Sep 18 05:11:33 hamid123 kubelet[27075]: Calico CNI IPAM assigned addresses IPv4=[192.168.21.219] IPv6=[]
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.889 [INFO][4485] calico-ipam.go 214: IPAM Result ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" HandleID="k8s-p
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.891 [INFO][4449] k8s.go 267: Populated endpoint ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" Namespace="kube-
Sep 18 05:11:33 hamid123 kubelet[27075]: Calico CNI using IPs: [192.168.21.219/32]
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.892 [INFO][4449] network.go 31: Setting the host side veth name to cali0ed1c7c6876 ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.894 [INFO][4449] network.go 326: Disabling IPv4 forwarding ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2" Names
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.934 [INFO][4449] k8s.go 294: Added Mac, interface name, and active container ID to endpoint ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c
Sep 18 05:11:33 hamid123 kubelet[27075]: 2018-09-18 05:11:33.940 [INFO][4449] k8s.go 302: Wrote updated endpoint to datastore ContainerID="3e6d114aa8e5c5a3487913efd70001a565875c7d90a3e38463df58b4d2ef18c2"
Sep 18 05:20:46 hamid123 kubelet[27075]: W0918 05:20:46.961108   27075 reflector.go:341] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: watch of *v1.Pod ended with: too old resource version: 855 (3

**Enviornment:**

    **_Kubernetes version:_** 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

    **_OS:_** 
Ubuntu-16.04
   
    **_Kernel:_**

Linux hamid123 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Deepak3994** [comment]
Hi,

I get the below error..

![screenshot_2018-09-19 deepak - kubernetes dashboard](https://user-images.githubusercontent.com/20994657/45750477-ce44d300-bc2c-11e8-9827-f3cd15cb23e4.png)

The above error occurs only after joining the node to the master. Kindly let me how to overcome this problem.

**Comment by atomiccc** [comment]
I had flannel in a similar bunk state after installing it. Since this is a brand new master I just rebooted the entire server and everything came up cleanly.

**Comment by kpkaur2015** [comment]
I forgot to disable my selinux on client nodes , which gave me same issue of client not ready.
Once port setting and Selinux fixed , issue got resolved.

Before fixing 

[root@kubemaster ~]# kubectl get nodes
NAME                      STATUS     ROLES    AGE   VERSION
kubeclient1.localdomain   NotReady   <none>   16s   v1.17.3
kubeclient2.localdomain   NotReady   <none>   36s   v1.17.3
kubemaster.localdomain    Ready      master   25m   v1.17.3
[root@kubemaster ~]# 


After fixing 

[root@kubemaster ~]# kubectl get nodes
NAME                      STATUS   ROLES    AGE   VERSION
kubeclient1.localdomain   Ready    <none>   51m   v1.17.3
kubeclient2.localdomain   Ready    <none>   51m   v1.17.3
kubemaster.localdomain    Ready    master   76m   v1.17.3
[root@kubemaster ~]#

**Comment by ashish1586** [comment]
Hi,

i have created kubernetes cluster using ansible  scripts.  my cluster is ready and when i run the below command it says the status is not ready. Can anybody tell me the reason.

kubectl get nodes -o wide.


When i run kubectl get pods --all-namespaces, it says that my core dns pods are not running.

NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-h4pjf             0/1     Pending   0          34m
kube-system   coredns-66bff467f8-rt6cp             0/1     Pending   0          34m
kube-system   etcd-instance-4                      1/1     Running   0          34m
kube-system   kube-apiserver-instance-4            1/1     Running   0          34m
kube-system   kube-controller-manager-instance-4   1/1     Running   0          34m
kube-system   kube-proxy-bnh7z                     1/1     Running   0          28m
kube-system   kube-proxy-gvmzr                     1/1     Running   0          34m
kube-system   kube-proxy-m57kt                     1/1     Running   0          28m
kube-system   kube-scheduler-instance-4            1/1     Running   0          34m

**Comment by neolit123** [comment]
> When i run kubectl get pods --all-namespaces, it says that my core dns pods are not running.

make sure you install a CNI plugin:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

**Comment by ashish1586** [comment]
I ran this command and got below error-

root@instance-4:/home/devops/.kube# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

**Comment by neolit123** [comment]
try `sudo kubectl --kubeconfig /etc/kubernetes/admin..conf ....`
also try WeaveNet instead of flannel.

**Comment by ashish1586** [comment]
with sudo also giving same error
