### ISSUE TITLE
Is it possible to use the master as worker node?

### ISSUE THREAD

**Issue by asispatra** [kubernetes/kubernetes#68553]
Currently I am finding that out of two nodes, one node is acting as master and the other one is acting as worker node. Only in the worker node all the pods are getting scheduled.

Is there a way to use the master node as a worker node?

**Comment by asispatra** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by asispatra** [comment]
@kubernetes/sig-cluster-lifecycle
/sig-cluster

**Comment by neolit123** [comment]
@asispatra it is possible, but it depends on how you are creating the cluster.

please fill the whole issue template and re-open the issue. :)
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

/close
