### ISSUE TITLE
kubectl certificate deny

### ISSUE THREAD

**Issue by kernelsky** [kubernetes/kubernetes#68558]
View node status：kubectl get csr
```
[root@kube1 ~]# kubectl get csr
NAME                                                   AGE    REQUESTOR                 CONDITION
node-csr--jJF_sRckTdhoqAOYB4fEaA06Juwv32d1RFwzcbbE0c   150m   system:bootstrap:gn5vla   Pending
node-csr-KMkTDLPqhj52YxZFS8vEOiqMt1NXVEcYvmvUJAhxhwg   150m   system:bootstrap:xay6t6   Pending
node-csr-bv18tH4pK-xq7Ekwv0IuzD4CcBuvKjjdonBjpKqHuPQ   150m   system:bootstrap:v1g4p2   Pending
```
Perform a refusal：
`kubectl get csr | grep Pending| awk '{print $1}' | xargs kubectl certificate deny`
View node status again：kubectl get csr
```
[root@kube1 ~]# kubectl get csr
NAME                                                   AGE    REQUESTOR                 CONDITION
node-csr--jJF_sRckTdhoqAOYB4fEaA06Juwv32d1RFwzcbbE0c   150m   system:bootstrap:gn5vla   Denied
node-csr-KMkTDLPqhj52YxZFS8vEOiqMt1NXVEcYvmvUJAhxhwg   150m   system:bootstrap:xay6t6   Denied
node-csr-bv18tH4pK-xq7Ekwv0IuzD4CcBuvKjjdonBjpKqHuPQ   150m   system:bootstrap:v1g4p2   Denied
```
Now I want to change the Denied state to the Approved state.
`kubectl get csr | grep Denied| awk '{print $1}' | xargs kubectl certificate approve`

No matter how many times it is executed, the status is still Denied.
```
[root@kube1 ~]# kubectl get csr
NAME                                                   AGE    REQUESTOR                 CONDITION
node-csr--jJF_sRckTdhoqAOYB4fEaA06Juwv32d1RFwzcbbE0c   150m   system:bootstrap:gn5vla   Denied
node-csr-KMkTDLPqhj52YxZFS8vEOiqMt1NXVEcYvmvUJAhxhwg   150m   system:bootstrap:xay6t6   Denied
node-csr-bv18tH4pK-xq7Ekwv0IuzD4CcBuvKjjdonBjpKqHuPQ   150m   system:bootstrap:v1g4p2   Denied
```

I want to ask how can I change the Denied status to Approved.
Thank you！

OS：centos7.5
[root@kube1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.2", GitCommit:"0cafd04160ff4e5c16bb38d0e4ecae805c84d41c", GitTreeState:"clean", BuildDate:"2018-09-11T23:02:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.2", GitCommit:"0cafd04160ff4e5c16bb38d0e4ecae805c84d41c", GitTreeState:"clean", BuildDate:"2018-09-11T22:52:11Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
the kubectl commands aren't intended to remove the denial condition, only to add approved or denied to a CSR that hasn't been acted on yet

What's the use case for denying, then approving a CSR?

**Comment by kernelsky** [comment]
How can I do this to approve a CSR in the Denied state?

**Comment by kernelsky** [comment]
How can I do this to approve a CSR in the Denied state? @liggitt

**Comment by kernelsky** [comment]
I have deleted and re-approved, thank you for your help.
`kubectl delete csr <csr-name>`
