### ISSUE TITLE
kubelet csi plugin uses hard-coded address to connect over grpc

### ISSUE THREAD

**Issue by darxkies** [kubernetes/kubernetes#68574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The csi plugin ignores --root-dir and it uses the hard-coded "/var/lib/kubelet/plugins/%v/csi.sock" defined here https://github.com/kubernetes/kubernetes/blob/36877dafe40495cb43994464e2427355f99042c7/pkg/volume/csi/csi_plugin.go#L55

**What you expected to happen**:

csi plugin should use the "plugins" subdirectory relative to the value defined using --root-dir.

**How to reproduce it (as minimally and precisely as possible)**:

Set --root-dir to something else than /var/lib/kubelet and configure the csi driver to use the plugins subdirectory relative to the --root-dir directory. Kubelet will fail with the following message:

MountVolume.MountDevice failed for volume "pvc-06f117e0b68c11e8" : rpc error: code = Unavailable desc = grpc: the connection is unavailable

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): Linux single-node 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: k8s-tew

**Comment by darxkies** [comment]
@kubernetes/sig-storage-bugs

**Comment by linyouchong** [comment]
@darxkies @vladimirvivien I have tried to fix it, PTAL
https://github.com/kubernetes/kubernetes/pull/68597

**Comment by vladimirvivien** [comment]
Hi, as of version 1.11, the CSI plugin uses the Kubelet Registration Mechanism for CSI driver discovery.  You can take a look here to see how the kubelet path is resolved - https://github.com/kubernetes/kubernetes/blob/36877dafe40495cb43994464e2427355f99042c7/pkg/volume/csi/csi_client.go#L293

That variable, `csiAddrTemplate` is not used and needs to be removed.

**Comment by darxkies** [comment]
When is the KubeletPluginWatcher feature going to be promoted to beta?

**Comment by vladimirvivien** [comment]
@darxkies it will be beta next release.  So it will be on by default.

**Comment by darxkies** [comment]
Wonderful. I will take a closer look at it next week.
