### ISSUE TITLE
JSON Patch: Don't allow negative indices

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#68578]
Bump evanphx/json-patch to pick up: https://github.com/evanphx/json-patch/commit/fcd53eccb4f88d7e54b742358017d72c9b34ae44, and enable [edit: disable] the new flag, in order to be compliant with the json patch spec (see: https://github.com/evanphx/json-patch/issues/65#issue-359587607).

This will at a minimum require an action-needed release note. We don't know if anyone is using this feature today.

**Comment by sahitpj** [comment]
If I am understanding this right, it means adding a release-note ( to docs  ) about the patch which has been added to the JSON file about negative indices right?

May I work on this issue  if it hasn't been assigned yet?

**Comment by lavalamp** [comment]
@sahitpj Please, go ahead. :)

I think it means:
1. update the vendored package
2. in the same PR, modify the usage of the json-patch object to enable the new setting
3. in that PR's description, put an action-required release note-- this will get automatically placed into the right documents when releases are built that include the change.

**Comment by Pothulapati** [comment]
@lavalamp The ````SupportNegativeIndices```` setting defaults to true as per the [PR](https://github.com/evanphx/json-patch/commit/fcd53eccb4f88d7e54b742358017d72c9b34ae44#diff-65c563bba473be9d94ce4d033f74810eL16). So,Why is there a need to enable the new setting? :)

To disable the setting would be a breaking change as negative indices were being allowed previously!

I'm willing to take this issue if @sahitpj hasn't started working on this.

**Comment by sahitpj** [comment]
Yeah sure @Pothulapati go ahead

**Comment by lavalamp** [comment]
@Pothulapati In that case, I mean disable--edited.

Right, this is removing a "feature", but--

1. We are allowed to fix bugs
2. As api machinery becomes a more established platform it's becoming more important to standardize, for interoperability reasons. There's lots of non-standard stuff in apiserver but we can at least stick to standards when we claim to.

But yes, action-required release note is necessary.

I added an item to the next api machinery sig meeting agenda just so there's no surprises.

**Comment by fharding1** [comment]
It looks like there still hasn't been any progress on this yet. @Pothulapati are you taking this on? If not, I'd be happy to.

**Comment by fharding1** [comment]
You could probably just do it in the `init()` of all the packages that use `jsonpatch`.

```
func init() {
	jsonpatch.SupportNegativeIndices = false
}
```

**Comment by rajathagasthya** [comment]
Mind if I take this?

**Comment by ojizero** [comment]
@rajathagasthya any updates in this? I'm willing to take a shot at it case you're unable to complete it 😬

**Comment by draveness** [comment]
It seems like this issue needs to be closed, it was already solved in https://github.com/kubernetes/kubernetes/pull/73713

**Comment by ojizero** [comment]
@draveness I saw that PR before and as far as I can tell it didn't address this particular issue, correct me if I'm wrong but it only seems to have updated the dependencies as well as adding logic regarding `JSONPatchMaxCopyBytes`, but negative indices are still allowed (as they are enabled by default in [json-patch](https://github.com/evanphx/json-patch/blob/master/patch.go#L21)) 🤔

Its preceding PR #73553 had the `jsonpatch.SupportNegativeIndices` set in some places, but non are found in the newer PR #73713.

**Comment by draveness** [comment]
@ojizero maybe we need @caesarxuchao to help us clarify why #73713 superceded #73553

**Comment by mumoshu** [comment]
I'm working on this based on the following list of sources that potentially need the fix:

```
$ git grep evanphx/json-patch | grep -v 'vendor\|go.sum\|go.mod\|.import-restrictions'
pkg/controller/testutil/test_utils.go:	jsonpatch "github.com/evanphx/json-patch"
pkg/kubectl/cmd/annotate/annotate.go:	jsonpatch "github.com/evanphx/json-patch"
pkg/kubectl/cmd/label/label.go:	jsonpatch "github.com/evanphx/json-patch"
pkg/kubectl/cmd/patch/patch.go:	jsonpatch "github.com/evanphx/json-patch"
pkg/kubectl/cmd/util/editor/editoptions.go:	"github.com/evanphx/json-patch"
pkg/kubectl/cmd/util/helpers.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch_test.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:// evanphx/json-patch and openshift/origin.
staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go:	jsonpatch "github.com/evanphx/json-patch"
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:	jsonpatch "github.com/evanphx/json-patch"
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go:	jsonpatch "github.com/evanphx/json-patch"
staging/src/k8s.io/apiserver/pkg/server/config.go:	jsonpatch "github.com/evanphx/json-patch"
staging/src/k8s.io/cli-runtime/pkg/genericclioptions/record_flags.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer/patch/patch.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer/patch/patchconflictdetector.go:	"github.com/evanphx/json-patch"
staging/src/k8s.io/client-go/testing/fixture.go:	jsonpatch "github.com/evanphx/json-patch"
test/e2e/auth/audit.go:	jsonpatch "github.com/evanphx/json-patch"
test/images/agnhost/webhook/addlabel_test.go:	jsonpatch "github.com/evanphx/json-patch"
test/images/agnhost/webhook/patch_test.go:	jsonpatch "github.com/evanphx/json-patch"
test/integration/master/audit_test.go:	"github.com/evanphx/json-patch"
```

The following sources has direct invocations on `MergePatch` directly call `MergePatch` which deserves the fix:

- `pkg/kubectl/cmd/patch/patch.go`
- `staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go` 
- `staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go`
- `staging/src/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer/patch/patch.go`

The following source has direct invocation on `jsonpatch.MergeMergePatches` which also deserve the fix:

- `staging/src/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer/patch/patchconflictdetector.go`

`pkg/kubectl/cmd/util/helpers.go` also deserve the fix, as it defines the `Merge` function that calls `MergePatch` under the hood, which is called from:

```
$ git grep cmdutil.Merge
pkg/kubectl/cmd/expose/expose.go:                       object, err = cmdutil.Merge(codec, object, inline)
pkg/kubectl/cmd/run/run.go:             obj, err = cmdutil.Merge(codec, obj, overrides)
```

`staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go` 

In other sources we only use `CreateMergePatch`s and `DecodePatch` which work equivalently regardless of the `SupportNegativeIndices` flag.

**Comment by agadelshin** [comment]
/assign

I'd like to continue

**Comment by liggitt** [comment]
I'm not convinced we can/should start disallowing negative indices.

> As api machinery becomes a more established platform it's becoming more important to standardize, for interoperability reasons. There's lots of non-standard stuff in apiserver but we can at least stick to standards when we claim to.

If we were generating negative-index patches, I would definitely agree we should stop. If we have accepted them for O(years), what is the reason to stop now?

**Comment by lavalamp** [comment]
Yeah I thought you might feel that way.

We may have missed our window to turn this off :( :( :(

**Comment by liggitt** [comment]
Dropping `good first issue` since the compatibility implications are unclear. At this point, I think we should probably continue accepting what we previously accepted.

**Comment by liggitt** [comment]
I don't think we would stop accepting these at this point.

Closing this issue to avoid misleading people into helping by implementing a breaking change.

/close
