### ISSUE TITLE
Bootstraped with Kubeadm does not report cpu correctly 

### ISSUE THREAD

**Issue by DMEvanCT** [kubernetes/kubernetes#68580]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
My worker nodes went to 100% CPU and the kubernetes master showed 12%. This causes issues with load balancing between nodes

**What you expected to happen**:
I expect the kubernetes cluster to report back CPU so things will balance evenly 

**How to reproduce it (as minimally and precisely as possible)**:
Install kubeadm run pods and look at the balancing 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

kubectl version 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Kubeadm version
[root@ord-kube-master-01 Nginx]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

OS
RHEL 7.5

Kernel 
3.10.0-862.9.1.el7.x86_64 #1 SMP Wed Jun 27 04:30:39 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment]
/sig node

there seems to be another issue at play here.
are pods of the worker nodes healthy ? are the worker nodes staying at 100% cpu all the time?

> I expect the kubernetes cluster to report back CPU so things will balance evenly

what do you expect it to "report" and what is an even balance?
my assumption here is that you don't want the worker nodes to be stuck at 100%.

1.10 is soon going outside of the support skew.
please try the latest version.

**Comment by neolit123** [comment]
/close
no further report was received.
