### ISSUE TITLE
Improve human-readable output of Deployments and StatefulSets

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#68623]
The column output for `Deployments`, `StatefulSets`, and `DaemonSets` are not as helpful as the human-readable output for Pods (for example).

We need to reduce the number of columns that we use to inform about the current amount of replicas (for example) that are desired and have been fulfilled for these resources, and add a new column or two that give the user more information about the current state of a Deployment or StatefulSet, and the reason behind that state.

For example:

**Before**
```
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment1     1         1         1            0           4s
```

**After**
```
NAME            READY   STATUS             UP-TO-DATE   AVAILABLE  RESTARTS   AGE
deployment1     1/1     CrashLoopBackOff   1            0          2          4s 
```

What is expected:

Improve the human-readable output in `kubectl get` for the following resources:

- DaemonSets
- StatefulSets
- Deployments

cc @soltysh @smarterclayton

**Comment by juanvallejo** [comment]
@sahitpj Sure, feel free to put together a pull for this. Please reach out on slack if you have any questions

**Comment by Pingan2017** [comment]
@juanvallejo How do we get its status and restarts?  other controller, like rc , rs, donot has these  columns.
through the struct of statefulset like below, there is not fileds can represent status and restarts

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2018-11-02T18:39:19Z"
  generation: 1
  name: web
  namespace: default
  resourceVersion: "22279324"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/web
  uid: 9bb3bedf-dece-11e8-9de2-002dc92800b3
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nginx1
  serviceName: nginx1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx1
    spec:
      containers:
      - image: index.tenxcloud.com/docker_library/nginx:1.9.0
        imagePullPolicy: Never
        name: nginx1
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jjj
          name: hostpath
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/333
          type: ""
        name: hostpath
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: web-86955bcf98
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: web-86955bcf98
  updatedReplicas: 3
```

**Comment by juanvallejo** [comment]
@Pingan2017 
> How do we get its status and restarts? other controller, like rc , rs, donot has these columns.
through the struct of statefulset like below, there is not fileds can represent status and restarts

No need to show those if the controller does not support them. It's fine to just merge the `DESIRED` and `CURRENT` into a single `READY` column

**Comment by janetkuo** [comment]
This is done.
