### ISSUE TITLE
AWS ELB drops node out of service after a deploy

### ISSUE THREAD

**Issue by ricktbaker** [kubernetes/kubernetes#68631]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Have a service of type loadbalancer in AWS, all installed via helm.   Everything works as it should, pod comes up as in service on the ELB as expected.   Periodically when I do a helm upgrade a new pod is created and it goes out of service.   I can watch tcpdump and see the ICMP healthcheck request going to the pod, but it is never returned, so the pod is set to outofservice on the ELB.   If I kill the pod and a new one is created it will then start responding to the healthcheck ICMP request and comes up

**What you expected to happen**:

I would expect the replacement pod to respond to healthchecks and keep the pod in service on the ELB.  The readiness check is working as expected, I can watch the logs in the pod and see the readiness check come in and execute as expected, so the pod is working, it's just not responding to the healtchecks from the ELB.

**How to reproduce it (as minimally and precisely as possible)**:

- Create AWS EKS cluster
- Deploy a pod and service of type load balancer with helm
- Watch pod come up as in service on ELB
- Change something so the pod gets recreated when a helm upgrade is applied
- Watch pod go out of service on the ELB
- Kill pod, let it be recreated by the deployment, and watch pod come back into service on the ELB.

**Anything else we need to know?**:

**Environment**: Latest AWS EKS

**Comment by tndhl** [comment]
+1

**Comment by vorozhko** [comment]
I have similar issue. In my case issue was with ELB itself. It's AZs list has 2 subnets out of 3. So, when pod migrated to subnet which is not covered by ELB then ELB go out of service.
My setup is EKS within 3 private subnets and internal ELB provisioned by ingress.

**Comment by UmanShahzad** [comment]
Had the same issue, was able to replicate repeatedly. No helm.
