### ISSUE TITLE
proposal to expose deviceplugin info

### ISSUE THREAD

**Issue by u2takey** [kubernetes/kubernetes#68650]
As a user, sometimes i want to know gpuids allocated for a container. This information can be found as a container variable inside container, but it can not be achieved by inspect pod yaml.
So i propose to expose allocated deviceplugin information as prometheus metrics.
Now we can `device_plugin_registration_count` and `device_plugin_alloc_latency_microseconds`  at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go#L52

Maybe we can add a metrics called `device_plugin_alloc_resources`, which expose data just like data saved in checkpoint: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L88

| Metric name| Metric type | Labels/tags | 
| ---------- | ----------- | ----------- | 
| device_plugin_alloc_resources | Gauge | `pod`=&lt;pod-name&gt; <br> `container`=&lt;container-name&gt;  <br> `resource`=&lt;resource-name&gt;<br> `deviceids`=&lt;deviceids&gt;<br>  |

**Comment by tianshapjq** [comment]
this may refer to [Compute Device Assignment](https://github.com/kubernetes/community/pull/2454)
