### ISSUE TITLE
Failed to start kube-proxy with --metrics-bind-address flags

### ISSUE THREAD

**Issue by Chenditang** [kubernetes/kubernetes#68669]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Start kube-proxy with "--metrics-bind-address=0.0.0.0:10249" return: 
Error: invalid argument "0.0.0.0:10249" for "--metrics-bind-address" flag: "0.0.0.0:10249" is not a valid IP address
and with "--metrics-bind-address=0.0.0.0" return:
server.go:358] failed validate: KubeProxyConfiguration.MetricsBindAddress: Invalid value: "0.0.0.0": must be IP:port

**What you expected to happen**:

The default metrics-bind-address is "127.0.0.1:10249", I expected to change it with "--metrics-bind-address=0.0.0.0:10249"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lurenjia528** [comment]
```  bash
cat kube-proxy.config.yaml

apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  kubeconfig: /run/kube-proxy.conf
clusterCIDR: 
kind: KubeProxyConfiguration
metricsBindAddress: 0.0.0.0:10249
```

``` bash
    spec:
      serviceAccountName: kube-proxy
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: kylincloud2.hub/kube-proxy-arm64:v1.10.0
        command:
        - kube-proxy
        - --v=2
        - --logtostderr=true
        - --kubeconfig=/run/kube-proxy.conf
        - --cluster-cidr=10.244.0.0/16
        - --proxy-mode=iptables
        - --config=/run/kube-proxy.config.yaml
#        - --metrics-bind-address=0.0.0.0:10249
        imagePullPolicy: IfNotPresent

```

the port 10249 now can use the ip 192.168.xx

![image](https://user-images.githubusercontent.com/37833630/50218943-90408200-03c8-11e9-82a5-be25472ed333.png)

**Comment by MrHohn** [comment]
I recalled a couple of related bug fixes were merged recently, specifically https://github.com/kubernetes/kubernetes/pull/72682 added a `--metrics-port` flag that should allow user to configure metrics server address. It was cherrypicked into 1.11+.

Feel free to reopen if you still see the issue.
/close

**Comment by WoodProgrammer** [comment]
some of old kubernetes version that you need to set it without port. I just set metric parameter like that `--metrics-bind-address=0.0.0.0` without port and it works.

Kubernetes version: `v1.11.10`

**Comment by k4korea** [comment]
apiVersion: v1
data:
  config: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    ...
    kind: KubeProxyConfiguration
    # Change 127.0.0.1:10247 -> 0.0.0.0:10249
    metricsBindAddress: 0.0.0.0:10249
    ...
kind: ConfigMap
metadata:

kubectl delete po kube-proxy-xxxx -n kube-system
