### ISSUE TITLE
performance issue during k8s starting a pod container

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kubernetes#68672]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG 

/kind bug

**What happened**:
When I start a simple nginx pod by kubectl create, k8s always spend _10 second_ to "Created" a container after "SuccessfulMountVolume", how can it be **SO** slow ? What happen during this period?
**What you expected to happen**:
Start a pod in 5 second after mounted successfully
**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f nginx.yaml (a quite simple pod with nginx)
kubectl describe pods nginx

**Anything else we need to know?**:
This issue can be easily repro on centos 7 + kubelet 1.9.5/1.10.x + docker 1.12/1.13 
However on **docker 18.06** it only spends _1-2 second_ to start a pod ! **unbelievable !**
**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
CentOS 7.3
- Kernel (e.g. `uname -a`):
Linux stcvl-115 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
**docker info:**
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
**docker version**: 
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-68.gitdded712.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      dded712/1.13.1
 Built:           Tue Jul 17 18:34:48 2018
 OS/Arch:         linux/amd64
 Experimental:    false
**cat /etc/docker/daemon.json**
{
    "insecure-registries": [],
    "storage-driver": "overlay2",
    "exec-opts": ["native.cgroupdriver=systemd"],
    "graph": "/var/lib/docker"
}

**Comment by k82cn** [comment]
@qzyse2017  Can you help to show Pod's status? It will give some guidance on which phase consume most .

**Comment by Cherishty** [comment]
@k82cn  
finally we replace the network plugin from flannel to weave, and start a pod only spends **2** second 

Thanks for your assistance!
