### ISSUE TITLE
ipset add entries failed inside kube-proxy-amd64:v1.10.7

### ISSUE THREAD

**Issue by islinwb** [kubernetes/kubernetes#68703]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
failed to use `ipset add` to add entries inside kube-proxy-amd64:v1.10.7 (as @cloudboss described: https://github.com/kubernetes/kubernetes/issues/67292#issuecomment-421223703) 
```
ipset v6.30: Syntax error: 'tcp' is invalid as number
Syntax error: cannot parse 'tcp' as a protocol
```
Tested on 1.10.* and 1.11.*.
original threads: https://github.com/kubernetes/kubernetes/issues/67292#issuecomment-419744979 and comments after

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
docker run -ti --privileged k8s.gcr.io/kube-proxy-amd64:v1.10.7 sh -c "ipset version; ipset create TEST hash:ip,port,ip family inet hashsize 1024 maxelem 65536 -exist; ipset add TEST 10.0.0.2,tcp:8443,10.0.0.2 -exist
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@dawidmalina what's the image of kube-proxy you used? kube-proxy-amd64:v1.11.1?(it works fine in my side)
> I have quite similar issue with kube-proxy configured with ipvs mode (kubernetes 1.11.1 deployed on ubuntu 16.04) with calico as network provider:

/cc @cloudboss @dawidmalina

/sig network
/area kube-proxy

**Comment by dawidmalina** [comment]
This works for me 👍

**Comment by mrrandrade** [comment]
IT's also happening to me on version 1.10.8:

```
# Container: hyperkube:v1.10.8 /hyperkube proxy --config=/etc/kubernetes/kube-proxy.yaml
...
# ipset add KUBE-LOOP-BACK 192.168.223.59,tcp:80,192.168.223.59 -exist
ipset v6.30: Syntax error: 'tcp' is invalid as number
Syntax error: cannot parse 'tcp' as a protocol
```

**Comment by islinwb** [comment]
@mrrandrade Yes, now it fails on v1.10.8. (I remember I've test it when I created this issue and it's ok then.)

**Comment by ixdy** [comment]
I'm still waiting for #68799 to be approved. :(

**Comment by pidanzheng** [comment]
ipset need to mount file  /etc/services and  /etc/protocols,  you can try.

**Comment by Lion-Wei** [comment]
@islinwb Hi, since #68799 is approved, this issue already solved?

**Comment by m1093782566** [comment]
I assume it's already fixed?

**Comment by ixdy** [comment]
/close

This should be fixed in the next 1.10 release (v1.10.9).

**Comment by m1093782566** [comment]
@caseydavenport FYI!

**Comment by MountainAndSea** [comment]
> ipset need to mount file /etc/services and /etc/protocols, you can try.

it works to me.
install ipset and kube-proxy not add /etc/services and /etc/protocols
