### ISSUE TITLE
API docs for job status should clearly explain what fields indicate success or failure

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#68712]
The API docs for jobs are unclear as to what fields a caller would use to determine job success or failure in 1.11 (and we haven't updated them in a while)

```
  status:
    conditions:
    - lastProbeTime: 2018-09-15T19:51:27Z
      lastTransitionTime: 2018-09-15T19:51:27Z
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 6
    startTime: 2018-09-15T19:46:13Z
```

```
$ kubectl explain jobs.status
KIND:     Job
VERSION:  batch/v1

RESOURCE: status <Object>

DESCRIPTION:
     Current status of a job. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status

     JobStatus represents the current state of a Job.

FIELDS:
   active	<integer>
     The number of actively running pods.

   completionTime	<string>
     Represents time when the job was completed. It is not guaranteed to be set
     in happens-before order across separate operations. It is represented in
     RFC3339 form and is in UTC.

   conditions	<[]Object>
     The latest available observations of an object's current state. More info:
     https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

   failed	<integer>
     The number of pods which reached phase Failed.

   startTime	<string>
     Represents time when the job was acknowledged by the job controller. It is
     not guaranteed to be set in happens-before order across separate
     operations. It is represented in RFC3339 form and is in UTC.

   succeeded	<integer>
     The number of pods which reached phase Succeeded.
```

A casual reader would infer that completionTime is set when the job fails (but it isn't).  Linking out to the docs is ok, but I shouldn't have to click through the links to understand how to use the Job object.  The Job description and the job status fields should *clearly* indicate what fields are set in completion states on the job, because that's 100% of the point of docs.  Taking a summary of the jobs-run-to-completion link and putting it in job.status.conditions, job.status, and job would improve the actual utility of our API doc.

We should also do a pass on other objects and make the actual in server docs more useful.

@kubernetes/sig-apps-bugs

**Comment by smarterclayton** [comment]
@soltysh as a consumer of the API, I had to read way too much to know how to use jobs correctly and how to write an API client that properly handled the conditions.

Also, we should consider either setting completionTime on failures, or adding failedTime (the former may not be forwards compatible), because reading the conditions is too complex for a fundamental use case like this.  This matches our decision w.r.t. conditions vs. fields - conditions are useful for extension and extra data, but status should have fields that allow an API consumer to easily understand state.

**Comment by smarterclayton** [comment]
Also... our docs don't actually explain how to determine the job is complete via the API, so there's arguably no place this is captured.

**Comment by adinaclaudia** [comment]
I have the same problem right now, of correctly identifying a finished job, when it does not complete successfully and after reading the documentation and the reference and all the examples I could find, it's still not clear how I can check the conditions and make sure the job is finished when I do so: `status.conditions[].status: true/false/unknown` -> what does each mean? can I rely on `status.conditions[].type: failed`, is that set only when the job finishes, whether via `BackoffLimitExceeded` or `DeadlineExceeded`? what other reasons are possible? 

It would definitely help to have `completionTime` specified on failure as well, and the differentiation to be made via the presence of  `status.succeeded`.

**Comment by stojan-jovic** [comment]
Completely agree with previous comments! Even I found the way how to detect completed/failed jobs, still not sure am I covered all use cases. This part definitely needs clarifications/improvements/better documentation.

**Comment by andrewsav-datacom** [comment]
With regards to:
```
 conditions	<[]Object>
     The latest available observations of an object's current state. More info:
     https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
```

If you actually follow this link and then search on that page for "conditions" you will get exactly zero hits. This is extremely unhelpful.

**Comment by Eronarn** [comment]
This documentation really, really needs work. (So does the API, for that matter.)

**Comment by andrewmchen** [comment]
So what is the correct way to determine if a job is finished and whether it completed successfully?

**Comment by janetkuo** [comment]
> So what is the correct way to determine if a job is finished and whether it completed successfully?

When a Job completes (finished successfully), its `.status.completionTime` will be set, and Job conditions will have one with `type==Complete`. 

When a Job fails, Job conditions will have one with `type==Failed`.

**Comment by c2c-engg-20181012** [comment]
@smarterclayton @janetkuo 
Hi, if nobody has been working on it, can I take this one?
I have gone through the issue which is mentioned here and I would like to work on this. Can you please help me to get started as I am beginner to the project.

**Comment by jekohk** [comment]
> Also, we should consider either setting completionTime on failures, or adding failedTime (the former may not be forwards compatible), because reading the conditions is too complex for a fundamental use case like this. This matches our decision w.r.t. conditions vs. fields - conditions are useful for extension and extra data, but status should have fields that allow an API consumer to easily understand state.

I totally agree with this- currently the only way to get the full picture of a Job is to read its conditions along with status fields which is error prone and a lot of extra work. I think a good start would be to add a new field `status.failedTime` as suggested by @smarterclayton so as to not break compatibility for users already depending on `status.completionTime`

**Comment by rezmont** [comment]
> > So what is the correct way to determine if a job is finished and whether it completed successfully?
> 
> When a Job completes (finished successfully), its `.status.completionTime` will be set, and Job conditions will have one with `type==Complete`.
> 
> When a Job fails, Job conditions will have one with `type==Failed`.

This sound reasonable.

I'm still unclear when `status.conditions` can contain more than one element. Also what does a `status.conditions[0].status` `Unknown` or `False` mean?

**Comment by rkc007** [comment]
Still, open -- anyone actively working on this? I would like to attempt if not. :)

**Comment by avhvr** [comment]
@rkc007 Are you still working on this?

**Comment by brona90** [comment]
bump

**Comment by ms-lolo** [comment]
> > So what is the correct way to determine if a job is finished and whether it completed successfully?
> 
> When a Job completes (finished successfully), its `.status.completionTime` will be set, and Job conditions will have one with `type==Complete`.
> 
> When a Job fails, Job conditions will have one with `type==Failed`.

This does not match what I just witnessed in my cluster… digging deeper to see if I need to file a bug but I have a Job with a single Pod that was executed. The Pod failed but the Job was marked as complete.

This is the one (and only) pod that executed as my job:
```yaml
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 29 May 2020 10:33:58 -0700
      Finished:     Fri, 29 May 2020 10:46:56 -0700
```
And this is the job that owns it (from kubectl describe):
```yaml
Pods Statuses:  1 Running / 1 Succeeded / 0 Failed
```
This is the job status object:
```json
{'active': 1,
 'completion_time': datetime.datetime(2020, 5, 29, 17, 34, 28, tzinfo=tzutc()),
 'conditions': [{'last_probe_time': datetime.datetime(2020, 5, 29, 17, 34, 28, tzinfo=tzutc()),
                 'last_transition_time': datetime.datetime(2020, 5, 29, 17, 34, 28, tzinfo=tzutc()),
                 'message': None,
                 'reason': None,
                 'status': 'True',
                 'type': 'Complete'}],
 'failed': None,
 'start_time': datetime.datetime(2020, 5, 29, 17, 26, 13, tzinfo=tzutc()),
 'succeeded': 1}
```
on v1.16.7 but not finding any similar reports. just found this page as my only relevant search result.

**Comment by pvanderlinden** [comment]
I think it no only needs documentation, but also a change:
It would be good to have 2 fields (probably needs better names), this way it's easy and clear when a job is finished and if it failed or not and when (someone can look at failed, succeeded and conditions for details):
- finished_time: only set when the job finished (either completely failed or completely finished)
- finish_type: 'failed or completed'
