### ISSUE TITLE
Garbage files cannot be completely pruned after running local-up-cluster.sh

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#68716]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

After running `local-up-cluster.sh` (on master branch), a new file named `kube-dns.yaml-e` left as a surprise. and the file is not matched by git ignore so it's tracked by git which is really disturbing. I tried to find out where it's created but failed. Any one has a context w/ it?

```
On branch foo-branch
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        kube-dns.yaml-e
```

**Environment**:

- OS (e.g. from /etc/os-release): Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by dims** [comment]
@yue9944882 the only piece of code in local-up-cluster that touches the file is https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L885-L895

**Comment by nikhita** [comment]
@yue9944882 can't reproduce this. Two questions:

- Can you see this everytime?
- What is the SHA of the commit on master when you tried this? Can check with that too.

**Comment by yue9944882** [comment]
@dims @nikhita finally i realize that the cause is `sed` command is built receiving different flags between Linux and OSX. on Linux, you'll find that for linux sed the `-i` is explained as:

> '-i[SUFFIX]'
'--in-place[=SUFFIX]'
     This option specifies that files are to be edited in-place.  GNU
     'sed' does this by creating a temporary file and sending output to
     this file rather than to the standard output.(1).

but for OSX, it is:

> -i extension
             Edit files in-place, saving backups with the specified extension.  If a zero-length extension is given, no backup will be saved.  It is not recommended to give a zero-
             length extension when in-place editing files, as you risk corruption or partial content in situations where disk space is exhausted, etc.

or rather, the difference is that on OSX `-i` flag is required a variable `extension`, so when we're using `sed` on OSX in the script:
[https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L887-888](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L887-888)

the `-e` will be taken as a suffix for the backup file. then the `kube-dns.yaml-e` magic happened.🙂will raise a fix for this.

/assign

**Comment by yue9944882** [comment]
linking the difference between `bsd sed` and `gnu sed`

https://unix.stackexchange.com/a/401928
