### ISSUE TITLE
kubectl logs - failed to get parse function: unsupported log format: "\n"

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#68721]
/kind bug

Hello,

**What happened**:

When I show the logs of my pods, since I updated to v1.10.6 (and now moved to 1.10.8), the result hang for a while or show `failed to get parse function: unsupported log format: "\n"%` error message : 

```
  ➜  ValShuttle ~  ~$ k -n nginx-ingress logs -f nginx-ingress-03-86669d77d4-vs4wk                                                                                                                    
failed to get parse function: unsupported log format: "\n"% 

  ➜  ValShuttle ~  ~$ k -n nginx-ingress logs -f nginx-ingress-03-86669d77d4-vs4wk     -v=100                                                                                                              
I0917 15:17:43.388834   15066 round_trippers.go:387] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.7 (linux/amd64) kubernetes/0c38c36" https://K8S-APIc/api/v1/namespaces/nginx-ingress/pods/nginx-ingress-03-86669d77d4-vs4wk/log?follow=true
I0917 15:17:43.417411   15066 round_trippers.go:406] GET https://K8S-API/api/v1/namespaces/nginx-ingress/pods/nginx-ingress-03-86669d77d4-vs4wk/log?follow=true 200 OK in 26 milliseconds               
I0917 15:17:43.417444   15066 round_trippers.go:412] Response Headers:
I0917 15:17:43.417455   15066 round_trippers.go:415]     Content-Type: text/plain
I0917 15:17:43.417463   15066 round_trippers.go:415]     Date: Mon, 17 Sep 2018 04:17:43 GMT
failed to get parse function: unsupported log format: "\n"%      
```
Kubelet logs on the pod's node : 

```
Sep 17 15:24:10 ares.k8s.domain.tld kubelet[8116]: I0917 15:24:10.559316    8116 <autogenerated>:1] http: multiple response.WriteHeader calls                                                                 
Sep 17 15:24:10 ares.k8s.domain.tld kubelet[8116]: I0917 15:24:10.559378    8116 server.go:796] GET /containerLogs/kube-system/calico-node-wrnvh/calico-node?follow=true: (7.89581ms) 400 [[Go-http-client/1.1] [1404:ef40::105]:40214] 
```
If I kill the pod, the logs come back with the new one, but it come after. 

Sometime the logs stuck without any messages : 

```
I0917 16:06:18.016791   11945 round_trippers.go:387] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.10.7 (linux/amd64) kubernetes/0c38c36" https://K8S-API/api/v1/namespaces/dev-api-account/pods/api-account-redis-77f7fb65bb-2hwl4/log?follow=true

.... nothings after

```
If I do the curl manually and add the Bearer token, the logs come directly. 

**What you expected to happen**:

Doesn't get issue to fetch logs, like does in past releases. 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.8
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release): Debian stretch
- Kernel (e.g. `uname -a`): 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 
- Install tools: Calico / IPv6 
- Others:

**Comment by nikhita** [comment]
This comes from here:

https://github.com/kubernetes/kubernetes/blob/259a59d93618f0266151a50018f3b3f3cbcfc0e4/pkg/kubelet/kuberuntime/logs/logs.go#L189-L197

and then

https://github.com/kubernetes/kubernetes/blob/259a59d93618f0266151a50018f3b3f3cbcfc0e4/pkg/kubelet/kuberuntime/logs/logs.go#L333-L339

and after that it's essentially:

```go
f, err := os.Open(path)
r := bufio.NewReader(f)
l, err := r.ReadBytes(eol[0])
```

Looks like something is wrong with the LogPath.

**Comment by valentin2105** [comment]
I continue to get the issue on 1.13.3 / Docker 18.06.1 

Any idea ?

**Comment by valentin2105** [comment]
For example : 

`kubectl -v=10 -n kube-system logs -f cert-manager-cert-manager-8586455ff9-cwpvk cert-manager `

Report nothing.

`curl -sSk -H "Authorization: Bearer $TOKEN" https://k8s-api.olympe.noc.nc/api/v1/namespaces/kube-system/pods/cert-manager-cert-manager-8586455ff9-cwpvk/log\?container\=cert-manager\&follow\=true -k` 

Show the log directly, without any issue.
