### ISSUE TITLE
expose nodeport in Specific Nodes

### ISSUE THREAD

**Issue by denkensk** [kubernetes/kubernetes#68734]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
NodePort will Exposes the service on each Node’s IP at a static port.  Can I Exposes the Node's Port through the label of Node Instead of each Node in cluster？

**What you expected to happen**:
I can  Exposes the Node's Port through the label of Node

**Comment by shenshouer** [comment]
?

**Comment by gun1x** [comment]
Why was this closed? This would be extremely useful.

**Comment by jansony1** [comment]
its very useful

**Comment by fjcloud** [comment]
Very useful feature if you don't want to expose ports on all nodes.

**Comment by denkensk** [comment]
@fjcloud @jansony1 @g00nix 
Thanks for your comments. We choose to use service + ingress to expose our application now.
Maybe you can provide more use cases.

**Comment by fjcloud** [comment]
Hello,

For example you want to use 3 specifics nodes for accessing non-http services through nodePort. For security reason, you don't want to expose your service on all nodes of your cluster. 2 or 3 nodes is enough for load balancing and availability in most of cases.

**Comment by JarenZhan** [comment]
resolved?

**Comment by MrNocTV** [comment]
Please open it again.
The issue happens when installing Nginx Ingress Controller.
It will create a NodePort Service, but I as an Admin of the cluster don't want it to be accessible via all of nodes IPs.
It is because I have create a set of servers behind an LB, the Ingress Pods are configured to run on those nodes only.
