### ISSUE TITLE
Persistent Volume capacity limitation does not work

### ISSUE THREAD

**Issue by yinwenqin** [kubernetes/kubernetes#68736]
**Env**: Centos 7.4
**Version**: kube v1.9
**Storage**: Cephfs

**What happened:**
I make the pv/pvc with 1GiB capacity, then I bound with a pod,In the pod mount path,I wrote data that was far beyond the pv capacity limit.In the cephfs,the pod path actually has been successfully mounted.So is this a bug of kubernetes with cephfs,or  something else I need to do? 

```
root@yksp009027:~/ceph# kubectl get pvc
NAME         STATUS    VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound     cephfs-pv   1Gi        RWX                           2d
root@yksp009027:~/ceph# kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                STORAGECLASS   REASON    AGE
cephfs-pv   1Gi        RWX            Delete           Bound     default/cephfs-pvc                            2d

# 

root@testpod1-5c567b79cc-2nkfp:/var/www# ll -h
total 3.3G
drwxr-xr-x  1 www-data www-data 3.3G Sep 17 16:24 ./
drwxr-xr-x 39 root     root     4.0K Sep 16 11:51 ../
-rw-r--r--  1 root     root     1.1G Sep 17 14:13 test
-rw-r--r--  1 root     root     1.1G Sep 17 14:13 test2
-rw-r--r--  1 root     root     1.1G Sep 17 16:24 test3
```

```
[root@yksp020112 testpod1]# pwd
/mnt/cephfs/testpod1
[root@yksp020112 testpod1]# ll -h
total 3.3G
-rw-r--r-- 1 root root 1.1G Sep 17 14:13 test
-rw-r--r-- 1 root root 1.1G Sep 17 14:13 test2
-rw-r--r-- 1 root root 1.1G Sep 17 16:24 test3
```
/sig storage

**Comment by liggitt** [comment]
The capacity limit is not enforcing, it is informative. It is up to the underlying storage implementation to quota/enforce storage amounts.

**Comment by yinwenqin** [comment]
@liggitt
Thank you so much!
But is there anyway to limit the unequal capacity for each pod?

**Comment by Devying** [comment]
But is there anyway to limit the unequal capacity for each pod? @yinwenqin I have the same question

**Comment by wyq984700527** [comment]
> @liggitt
> Thank you so much!
> But is there anyway to limit the unequal capacity for each pod?

hello, how to limit the capacity?
