### ISSUE TITLE
CRD: ListOptions Limit option not working

### ISSUE THREAD

**Issue by iawia002** [kubernetes/kubernetes#68743]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm using List API with the `Limit` option, but no matter what my `Limit` is set, it returns all the data.

```go
client.SomeResourceV1beta1().StorageServices().List(metav1.ListOptions{
	Limit: 1,
})
```

but internal resources, like Secrets works fine.

I don't know if our CRD or clientset needs special configure.

**What you expected to happen**:

It returns limited data

**How to reproduce it (as minimally and precisely as possible)**:

try with any CRD

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
yes, CR paging is not yet support. 

@sttts is it intended? assuming we enabled paging, when the CRD's updated, the CR storage will be cleaned then the listing will be broken, amiright? back to #68508, do we consider the paging for the graceful deletion?

/area custom-resource

**Comment by liggitt** [comment]
Fixed by 
https://github.com/kubernetes/kubernetes/pull/67861

/close

**Comment by yue9944882** [comment]
hmm.. sadly we dont pick features back to release branches

**Comment by mbohlool** [comment]
Is this really a feature? Or just a bug as in we did not respect part of ListOptions.

**Comment by liggitt** [comment]
I'd call it a low severity bug

**Comment by lavalamp** [comment]
I'd also call this a bug that we could back port if there's a strong demand for it.
