### ISSUE TITLE
E2E tests using SSH are inconsistent in IP requirements

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#68747]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I'm running e2e tests via sonobuoy and had a number of tests skipped due to lack of an SSH key on the node. I then have created a secret, mounted it, set env vars to point to the key and set the SSH user. However, some tests explicitly require an external IP address () while others fallback to using an internal IP address since that may be reachable (which it is if running the tests through sonobuoy).

**What you expected to happen**:
I expected the external->internal fallback to be used more consistently in the tests. To emphasize, this is just in the test code and not in the 

**How to reproduce it (as minimally and precisely as possible)**:
Run sonobuoy tests with the e2e focus set to one of the tests below. You have to use `sonobuoy gen` to generate the yaml and modify a few things so that you get the secret in the right namespace and it gets mounted appropriately though.

I've not run the e2e tests manually from my own machine, but if you were doing that then it should be even easier as long as you have a cluster up where the nodes do not have external IPs set.

**Anything else we need to know?**:
This test can pass in my current setup: https://github.com/kubernetes/kubernetes/blob/733a381ec42ede15cd0499bc502a0cba6612f3ca/test/e2e/node/mount_propagation.go#L81
Since this function has the fallback logic: https://github.com/kubernetes/kubernetes/blob/5de3896d0d18f072664650b94a8f6089be420cc0/test/e2e/framework/service_util.go#L332

This test fails: https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/test/e2e/node/ssh.go#L43
Because this function does not have the fallback logic: https://github.com/kubernetes/kubernetes/blob/690179b1220ce8eba6d7b5e295b88fbe7772c18f/test/e2e/framework/util.go#L3271

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:21Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"", BuildDate:"2018-06-27T08:25:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
`Linux box-1 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by johnSchnake** [comment]
@kubernetes/sig-testing

**Comment by johnSchnake** [comment]
I also have another related ticket https://github.com/kubernetes/kubernetes/issues/68687 I'm happy to address these myself if someone from the sig concurs with my assessment of the issues/solutions.

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by johnSchnake** [comment]
The ci-robot incorrectly marked as fixed by the wrong PR; this needs https://github.com/kubernetes/kubernetes/pull/68792 to merge and I need the `approved` label, already has LGTM. `pull-kubernetes-godeps` seems to be a new requirement that hasnt been met either; not sure how to run/get that label.
