### ISSUE TITLE
Unwanted mount option in glusterfs fuse mount options.

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#68772]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

If user has submitted log file mount option via SC,  glusterfs plugin also add an additional `log-file` mount option without a value set. This cause the glusterfs fuse mount  to override user supplied log-file option with a null value which is not intended.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create an SC with `log-file` mount option.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Master
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Additional info # https://github.com/kubernetes/kubernetes/pull/68435/ fixes it.

**Comment by humblec** [comment]
@kubernets/sig-storage

**Comment by idealhack** [comment]
PR merged.

/close
