### ISSUE TITLE
systemd restart kube*

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/kubernetes#68782]
centos7  kube 1.6.3

systemd restart kube*

Sep 18 18:10:28 k8s-253 systemd: Stopping Kubernetes Kube-Proxy Server...
Sep 18 18:10:28 k8s-253 systemd: Stopping Kubernetes Kubelet Server...
Sep 18 18:10:28 k8s-253 systemd: Stopping Kubernetes API Service...
Sep 18 18:10:28 k8s-253 systemd: Stopping Kubernetes Scheduler Plugin...
Sep 18 18:10:28 k8s-253 systemd: Stopping Kubernetes Controller Manager...
Sep 18 18:10:28 k8s-253 systemd: Stopped Kubernetes Scheduler Plugin.
Sep 18 18:10:28 k8s-253 systemd: Stopped Kubernetes Kube-Proxy Server.
Sep 18 18:10:28 k8s-253 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Sep 18 18:10:28 k8s-253 systemd: Stopped Kubernetes Kubelet Server.
Sep 18 18:10:28 k8s-253 systemd: Unit kubelet.service entered failed state.
Sep 18 18:10:28 k8s-253 systemd: kubelet.service failed.
Sep 18 18:10:28 k8s-253 systemd: Stopped Kubernetes Controller Manager.
Sep 18 18:10:28 k8s-253 systemd: Stopped Kubernetes API Service.
Sep 18 18:11:01 k8s-253 systemd: Started Session 1369 of user root.
Sep 18 18:11:01 k8s-253 systemd: Starting Session 1369 of user root.
Sep 18 18:11:16 k8s-253 systemd: Starting Kubernetes API Service...

**Comment by zetaab** [comment]
could you please add some more information, like what is excepted behaviour or what you mean with this log thing? What we should change?

**Comment by timchenxiaoyu** [comment]
sorry，our operator run health check script lead to。
