### ISSUE TITLE
Integration test TestRequestExecuteRemoteCommand is flaky - fix it

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#6878]
https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/58489351

--- FAIL: TestRequestExecuteRemoteCommand (0.01s)
	remotecommand_test.go:207: 1: expected true, got false: <nil>
FAIL
coverage: 81.6% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/client/remotecommand	0.173s

**Comment by liggitt** [comment]
I think this was fixed by #9119

**Comment by brendandburns** [comment]
Closing as fixed since we haven't seen it in a while.
