### ISSUE TITLE
Windows Kubelet does not mount the /dev/termination-file file into containers

### ISSUE THREAD

**Issue by bclau** [kubernetes/kubernetes#68791]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

/sig windows

**What happened**:

When creating a Kubernetes pod [0], you can specify the ``terminationMessagePath`` field, which is a file in which a container can write in, and its content will be included in the Pod's status [1], in the ``status.containerStatuses.state.terminated.message`` field. However, this does not work as intended with Windows Containers, causing a few Conformance tests to fail, like:

    [k8s.io] Container Runtime blackbox test when starting a container that exits  should report termination message as empty when pod succeeds and TerminationMessagePolicy FallbackToLogOnError is set [NodeConformance]

When comparing the ``docker inspect`` results from a Kubernetes pod with a Linux Container [2] with the ones from a Kubernetes pod with a Windows Container [3], it can be seen that the Linux container has a few extra items in the ``HostConfig.Binds`` list:

            "HostConfig": {
            "Binds": [
                "/var/lib/kubelet/pods/b4a24db4-b816-11e8-a756-000d3a4d73b6/volumes/kubernetes.io~secret/default-t                                                                                                                           oken-fnq6g:/var/run/secrets/kubernetes.io/serviceaccount:ro",
                "/var/lib/kubelet/pods/b4a24db4-b816-11e8-a756-000d3a4d73b6/etc-hosts:/etc/hosts",
                "/var/lib/kubelet/pods/b4a24db4-b816-11e8-a756-000d3a4d73b6/containers/termination-message-contain                                                                                                                           er/f1f48263:/dev/termination-log"
            ],

Which means that the Windows Kubelet is not creating those mounts. However, on Windows Docker, you cannot mount individual files at the moment (although mounting a folder to ``/dev`` instead could solve this issue).

[0] https://paste.ubuntu.com/p/pBp3SKHm9J/
[1] https://paste.ubuntu.com/p/Fh5Fb6qvp4/
[2] https://paste.ubuntu.com/p/v9sRkQqWfw/
[3] https://paste.ubuntu.com/p/8zPnRwWzHd/

**What you expected to happen**:

The given pod's ``terminationMessagePath`` file should exist in the containers, and the containers should be able to write messages in it, messages which will be included in the container's ``terminated`` status.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy the Kubernetes pod [0]: ``kubectl create -f pod.yaml``
2. Check that the container finised and that it has no termination status: ``kubectl get -o yaml po/termination-message-pod``
3. Additionally, log into the Windows node and execute ``docker inspect`` on the Kubernetes pod's container, and check that the ``HostConfig.Binds`` does not contain the ``/dev/termination-file`` mount.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-beta.1
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Windows Server 1803
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others:

**Comment by andyzhangx** [comment]
Update:
This feature is disabled on windows, it depends on file mount on windows.
https://github.com/kubernetes/kubernetes/blob/76518f154b717c977b1bfb506aeb7cd4b176fde0/pkg/kubelet/kubelet_pods.go#L468-L470

I think in the time we are waiting for windows 2019 which supports file mount, I would try to enable it on v1.13 first, make sure there is no break with current 1803 build(k8s v1.13 should work on both 1803 and 2019), and when 2019 comes out, it works perfectly.

FYI @PatrickLang

**Comment by bclau** [comment]
@andyzhangx yeah, I know that file mount is not supported yet, but it will be at one point.

Regarding the pod.yaml file, I should have mentioned it, but it is [1] in the bug report:  https://paste.ubuntu.com/p/pBp3SKHm9J/

**Comment by andyzhangx** [comment]
@bclau you could skip this test now since the feature is not implemented on Windows.

**Comment by PatrickLang** [comment]
does this impact conformance tests?
