### ISSUE TITLE
Investigate speeding up sig-storage tests

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#68809]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
As part of the sig storage e2e refactor, we added a lot of new test cases.  We should make sure these test cases are not taking up too much time and look into ways of shortening them.

One common area that can be looked into first is pod termination time: https://github.com/kubernetes/kubernetes/pull/64015

**Comment by taragu** [comment]
@msau42 i'd like to take a stab at this 
/assign

**Comment by msau42** [comment]
Thanks! Feel free to post your progress and any questions here
