### ISSUE TITLE
Inject api-server certificate into serviceaccount token projected volume

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#68811]
Currently, the serviceaccount token projected volume wouldn't  create ca.crt and namespace.crt file as old serviceaccount model does.  It could cause no available certificate problem. 
I think we need to mount ca.crt and namesapce.crt file automatically as current serviceaccount token controller does. I propose a model like this:
1. Add a serviceaccount-cert-file option to api-server which provides certificate file.  When api-server starts, if TokenRequest feature enabled, it will create a secret contains the certificate in kube-system namespace.
2. When a pod with token projected volume launches to kubelet, the volume manager will request the certificate secret in kube-system and injects data into the token projected volume.
3. We also need a way to make sure the secret does exist in kube-system, if not, recreate it.

**Comment by liggitt** [comment]
The proposal for this feature separated the injection of the namespace and the CA using existing downward API and configmap mount. 

The service account admission plugin would set up three projection sources to inject the token, namespace, and CA

/cc @mikedanese

**Comment by liggitt** [comment]
xref 
https://github.com/kubernetes/kubernetes/issues/67440
