### ISSUE TITLE
Hello, everyone, I want to kown that how to get pods with a label? This not appear in code...

### ISSUE THREAD

**Issue by zhang2kai** [kubernetes/kubernetes#68828]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shubheksha** [comment]
/triage support
@zhang2kai, you can find info regarding this in the [docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
/close
