### ISSUE TITLE
Shippable tests are flaky - make them awesomer

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#6882]
Issue to consolidate everything related to flaky tests in Shippable, and get it fixed.

**Comment by quinton-hoole** [comment]
In the past 24 hours, more than 50% of shippable builds failed.

**Comment by quinton-hoole** [comment]
#4626 seems to be one cause.

**Comment by quinton-hoole** [comment]
https://app.shippable.com/builds/552ee2ae16a6430b0044ef03

E0415 22:24:06.123334    5072 factory.go:276] Error scheduling default phantom.baz: failed to find fit for pod: {{ } {phantom.baz  default /api/v1beta1/pods/phantom.baz?namespace=default 16036e61-e3be-11e4-ae96-0242ac111909 303 2015-04-15 22:23:48 +0000 UTC <nil> map[] map[]} {[] [{c1 kubernetes/pause [] []  [{ 9999 1234 TCP }] [] {map[] map[]} [] <nil> <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] Always ClusterFirst map[]  false} {Pending []    []}}Node localhost: PodFitsPortsNode 127.0.0.1: PodFitsPorts; retrying
F0415 22:24:18.070945    5072 integration.go:939] FAILED: (Scheduler probably didn't process deletion of 'phantom.bar') Pod never started running: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:47
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1" --maxConcurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:47 runTests(...)
  2: ./hack/test-integration.sh:61 main(...)
Exiting with status 1
+++ [0415 22:24:18] Integration test cleanup complete

**Comment by quinton-hoole** [comment]
Of course Shippable rebuilds every time a PR in GitHub is updated (including comments, not just commits), so many of the failed Shippable build failures are entirely valid.

**Comment by quinton-hoole** [comment]
--- FAIL: TestAliceNotForbiddenOrUnauthorized (0.47s)
	auth_test.go:648: case {OPTIONS /api/v1beta1/pods  map[405:true]}
	auth_test.go:649: Expected status one of map[405:true], but got 200
	auth_test.go:650: Body: {
		  "kind": "Status",
		  "apiVersion": "v1beta3",
		  "metadata": {},
		  "status": "Failure",
		  "message": "the server does not allow this method on the requested resource",
		  "reason": "MethodNotAllowed",
		  "details": {},
		  "code": 405
		}

**Comment by quinton-hoole** [comment]
https://app.shippable.com/builds/552ed79616a6430b0044ee33

W0415 22:18:35.553867   22480 config.go:367] Pod[1] (foo.<empty-namespace>) from test failed validation, ignoring: metadata.namespace: required value
E0415 22:18:35.582210   22480 event.go:240] Could not construct reference to: '&api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"foo", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"kubernetes.io/config.source":""}}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container{api.Container{Name:"ctr", Image:"image", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]api.ContainerPort(nil), Env:[]api.EnvVar(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList(nil), Requests:api.ResourceList(nil)}, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.Probe)(nil), ReadinessProbe:(*api.Probe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"", Privileged:false, ImagePullPolicy:"IfNotPresent", Capabilities:api.Capabilities{Add:[]api.CapabilityType(nil), Drop:[]api.CapabilityType(nil)}}}, RestartPolicy:"Always", DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", HostIP:"", PodIP:"", ContainerStatuses:[]api.ContainerStatus(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'failedValidation' 'Error validating pod foo.<empty-namespace> from test, ignoring: metadata.namespace: required value'
W0415 22:18:35.697034   22480 config.go:367] Pod[1] (foo.<empty-namespace>) from test failed validation, ignoring: [metadata.namespace: required value, spec.containers: required value, spec.restartPolicy: required value, spec.dnsPolicy: required value]
E0415 22:18:35.708250   22480 event.go:240] Could not construct reference to: '&api.Pod{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*util.Time)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"", DNSPolicy:"", NodeSelector:map[string]string(nil), Host:"", HostNetwork:false}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", HostIP:"", PodIP:"", ContainerStatuses:[]api.ContainerStatus(nil)}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'failedValidation' 'Error validating pod foo.<empty-namespace> from test, ignoring: [metadata.namespace: required value, spec.containers: required value, spec.restartPolicy: required value, spec.dnsPolicy: required value]'
E0415 22:18:35.821738   22480 file.go:42] Unable to read config path "random_non_existent_path": path does not exist, ignoring
--- FAIL: TestReadFromFile (1.83s)
	file_test.go:275: Pod v1beta3: Expected update, timeout instead
E0415 22:18:37.934366   22480 http.go:43] Failed to read URL: Get http://localhost:49575/_not_found_: dial tcp 127.0.0.1:49575: connection refused

**Comment by quinton-hoole** [comment]
E0415 22:12:47.287433    5023 kubelet.go:1309] Failed creating a mirror pod "static-pod-from-spec-localhost_default": pods "static-pod-from-spec-localhost" already exists

**Comment by erictune** [comment]
I don't understand how the TestAliceNotForbiddenOrUnauthorized could give that answer.

**Comment by bgrant0607** [comment]
Is this issue still relevant?

**Comment by quinton-hoole** [comment]
Well, shippable remains flaky, so lets leave this open until that's resolved.

**Comment by bgrant0607** [comment]
Got the phantom.bar flake again: https://app.shippable.com/builds/560c7bdd354b7c0c00dfd1dd

**Comment by davidopp** [comment]
And again
https://app.shippable.com/builds/56102cdad798e60d0027ba5b

**Comment by karlkfi** [comment]
More `phantom.bar` pod failure.

Really hard to read these logs, but the line number `integration.go:926` indicates `runSchedulerNoPhantomPodsTest` polling for pods `phantom.bar` to come up.

https://app.shippable.com/builds/561835601e13d90c008e5bad

```
I1009 22:16:41.101652   16743 manager.go:171] Ignoring same status for pod "phantom.foo_default", status: {Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2015-10-09 22:11:40.866175671 +0000 UTC Reason: Message:}] Message: Reason: HostIP:127.0.0.1 PodIP:1.2.3.4 StartTime:2015-10-09 22:11:40.842585509 +0000 UTC ContainerStatuses:[{Name:c1 State:{Waiting: Running:0xc2091c3dc0 Terminated:} LastTerminationState:{Waiting: Running: Terminated:} Ready:true RestartCount:0 Image:testimage ImageID:docker:// ContainerID:docker:///k8s_c1.df54fadd_phantom.foo_default_b79200b4-6ed2-11e5-a88b-0242ac11263c_8430b7d6}]}
F1009 22:16:41.828468   16743 integration.go:926] FAILED: pod never started running timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:60
  'KUBE_API_VERSIONS="v1,experimental/v1alpha1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:60 runTests(...)
  2: ./hack/test-integration.sh:74 main(...)
Exiting with status 1
+++ [1009 22:16:41] Integration test cleanup complete
```

**Comment by wojtek-t** [comment]
Since we are no longer using Shippable - can we just close it?

**Comment by quinton-hoole** [comment]
Yes, closing.
