### ISSUE TITLE
Kubelet pod max PIDs not being inherited by Pod containers

### ISSUE THREAD

**Issue by krcroft** [kubernetes/kubernetes#68835]
**Is this a BUG REPORT or FEATURE REQUEST?**:
* **Bug Report**

/kind bug

**What happened**:
When applied to kubelet 1.11.3, the pod max PID limit (`--pod-max-pids=2048 --feature-gates=SupportPodPidsLimit=true`) is not inherited by pod containers:

`docker ps --quiet --all | xargs docker inspect --format '{{ .Name }}: PidsLimit={{ .HostConfig.PidsLimit }}'| grep PidsLimit=0`

> /k8s_proc-dg-backing_proc-dg-backing-6f5f85fd95-24wwj_kwiebegs_4f33a978-bc19-11e8-8e28-005056acdbbd_0: **PidsLimit=0**
> /k8s_procdg-postgres_procdg-postgres-66954db76-b6zsf_kwiebegs_4f2662bc-bc19-11e8-8e28-005056acdbbd_0: **PidsLimit=0**
> /k8s_POD_proc-dg-backing-6f5f85fd95-24wwj_kwiebegs_4f33a978-bc19-11e8-8e28-005056acdbbd_0: **PidsLimit=0**

**What you expected to happen**:
All pod containers started by kubelet should be limited to, and report, the same number of PIDs as passed to kubelet (2048 in the above example, `--pod-max-pids=2048`)

**How to reproduce it (as minimally and precisely as possible)**:
1. [Cordon and drain](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-nodes-and-cluster) the target worker node
1. Shutdown kubelet and docker
1. Add `--pod-max-pids=2048 --feature-gates=SupportPodPidsLimit=true`  to kubelet's startup service flags 
1. Restart kubelet and docker
1. Confirm the PID limit flags are active: `ps -ef | grep kubelet`
1. [Uncorden](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-nodes-and-cluster) the node
1. Query the PidsLimit of all containers on the node and visually inspect those containers started by Kubelet  `docker ps --quiet --all | xargs docker inspect --format '{{ .Name }}: PidsLimit={{ .HostConfig.PidsLimit }}'| grep PidsLimit=0`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: On-premise ESXi/VMWare platform 
- OS (e.g. from /etc/os-release): OpenSuSE Leap 15.1
- Kernel (e.g. `uname -a`): 4.18.7
- Install tools: kubeadm
- Others:

**Comment by yujuhong** [comment]
The pid limits are enforced at the pod level, not at the container level if I remember correctly. It's normal to not see them in the container cgroups limits.

**Comment by dims** [comment]
@yujuhong you are right.

@krcroft please use `systemd-cgtop` or `ctop` (from https://pypi.org/project/ctop/) to look at the counts. Also see https://github.com/kubernetes/kubernetes/pull/57973 for the detailed discussion

/close
