### ISSUE TITLE
1.12 release notes: known issues bucket

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#68840]
This issue is a bucket place holder for "known issues" additions into the 1.12 release notes.

**Comment by tpepper** [comment]
Possible "known issue" around reason for dropping https://github.com/kubernetes/features/issues/566 from v1.12 milestone.   Discussions ongoing https://groups.google.com/d/topic/kubernetes-milestone-burndown/D-CP8ZAJxuI/discussion

**Comment by tpepper** [comment]
Here's the final agreed text for the CoreDNS feature #566 dropping from the v1.12 milestone:

Feature #566 enabling CoreDNS as the default for kube-up deployments was dropped from the release due to a scalability memory resource consumption issue observed.  The root cause in CoreDNS remains unclear, but CoreDNS folks are investigating.  If a cluster operator is considering using CoreDNS on a cluster greater than 1000 nodes, it may be necessary to give more consideration to CoreDNS pod memory resource limits and experimentally measure that memory usage versus cluster resource availability.

**Comment by dghubble** [comment]
Known issue draft for https://github.com/kubernetes/kubernetes/issues/68973

kube-controller-manager currently needs a writable `--cert-dir` (default is `/var/run/kubernetes`) for generating self-signed certificates, when no `--tls-cert-file` or `--tls-private-key-file` are provided.

**Comment by dghubble** [comment]
Known issue draft for https://github.com/kubernetes/kubernetes/issues/68986

The `system:kube-controller-manager` ClusterRole lacks permission to `get` the `configmap` extension-apiserver-authentication. kube-controller-manager errors if run with a service account bound to the clusterrole.

**Comment by tpepper** [comment]
Known issue text should be coming for PR https://github.com/kubernetes/kubernetes/pull/69033 which looks to be slipping to 1.12.1.

**Comment by feiskyer** [comment]
Known issue for #69033:

Runtime handler and Windows npipe protocol are not supported yet in crictl v1.11.x. Those features will be supported in crictl [v1.12.0](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.12.0), togather with Kubernetes v1.12.1.

**Comment by dims** [comment]
time to close this since we already released 1.12.1

/close
