### ISSUE TITLE
Failing Test : [sig-apps] daemonset-upgrade

### ISSUE THREAD

**Issue by tpepper** [kubernetes/kubernetes#68857]
### Failing Job
---
[sig-release-master-upgrade multiple upgrade/downgrade tests](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#Summary)

### Gubernator Logs
---
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1776
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4923
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2477
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/944
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/4244
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1661

### Error
---
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:203
May 9 15:57:39.163: Unexpected no endpoints return
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:213

### Triage
---
This feels similar to issues resolved in master over the past weeks by SIG Autoscaling around HPA and metrics server.  Could it be that something needs backported, perhaps the use of the new metrics server image?  Or is there a latent and genuine incompatibility here?

It wasn't pursued aggressively previously as the symptom overlapped with multiple other ones being worked in master.  Now that they're resolved and this issue has persisted, this is likely a release blocker.

/kind bug
/priority failing-test
/priority critical-urgent
/sig apps
@kubernetes/sig-apps-bugs 
@kubernetes/sig-autoscaling-bugs 
/assign @mattfarina 
/cc @prydonius @kow3ns 
/milestone v1.12

**Comment by tpepper** [comment]
@k82cn is there any chance this is related to your taint nodes by condition work?

**Comment by k82cn** [comment]
/assign

not sure, let me check it anyway :)

**Comment by k82cn** [comment]
Open #68881 to handle that. In DaemonSet upgrade e2e test, it check whether a node is schedulable  by `len(taint)` which is not enough. Open the PR to check it by `Predicates`, similar to DaemonSet e2e test.

**Comment by janetkuo** [comment]
The fix was just merged. Let's keep this open until tests start passing.

**Comment by tpepper** [comment]
I believe these two:
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster-parallel   (run 4267)
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel (run 4946)
are likely to be our next ones that give an idea of health on this topic.

**Comment by tpepper** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4946?log#log still failed, but on a different test. I'm not seeing a reason the newly failing test would be related to the original symptom here.  Also not seeing why it would suddenly have flaked. :(

**Comment by janetkuo** [comment]
> https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4946?log#log still failed, but on a different test. I'm not seeing a reason the newly failing test would be related to the original symptom here.  Also not seeing why it would suddenly have flaked. :(

The pod failed because its container cannot run:
```
Reason:ContainerCannotRun,Message:linux runtime spec devices: lstat /dev/sdb: no such file or directory
```

The failure doesn't seem to related to https://github.com/kubernetes/kubernetes/pull/68881 or DaemonSet in general.

**Comment by janetkuo** [comment]
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-parallel starts passing. 

https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-new-downgrade-cluster-parallel isn't passing. However, it doesn't seem to be running the updated upgrade test, given that the debug log removed in #68881 still exists: `Node bootstrap-e2e-master not expected to have DaemonSet pod, has taints [{node.kubernetes.io/unschedulable  NoSchedule <nil>}]`.

**Comment by k82cn** [comment]
should we cherrypick? can not open the link because gfw right now.

**Comment by tpepper** [comment]
I suppose cherry picking this back to 1.11 branch would allow us to at least clear up the CI signal in testgrid for things that are related.  Since we have at least one other up/downgrade issue it seems still, having less noise in CI would be useful.  Can you submit a PR @k82cn ?

**Comment by k82cn** [comment]
sure, opened #68976 for 1.11.

**Comment by nikopen** [comment]
As I can see this has been passing since then.

/close




sidenote - 

daemonset-upgrade is currently only failing on
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster

since yesterday, together with
```
[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]
[sig-cluster-lifecycle] cluster-upgrade
[sig-apps] replicaset-upgrade
[sig-apps] daemonset-upgrade
[sig-apps] deployment-upgrade
[sig-apps] job-upgrade
[sig-apps] statefulset-upgrade
[sig-storage] [sig-api-machinery] configmap-upgrade
[sig-storage] [sig-api-machinery] secret-upgrade
[sig-storage] persistent-volume-upgrade
ingress-upgrade
```

but it seems that it's a different issue:

```
Expected error:
    <*url.Error | 0xc0013f8750>: {
        Op: "Get",
        URL: "https://35.184.23.149/api/v1/nodes",
        Err: {
            Op: "dial",
            Net: "tcp",
            Source: nil,
            Addr: {
                IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 35, 184, 23, 149],
                Port: 443,
                Zone: "",
            },
            Err: {Syscall: "connect", Err: 0x6f},
        },
    }
    Get https://35.184.23.149/api/v1/nodes: dial tcp 35.184.23.149:443: connect: connection refused
not to have occurred

k8s.io/kubernetes/test/e2e/upgrades/apps.(*DaemonSetUpgradeTest).validateRunningDaemonSet(0x78efa20, 0xc0004e98c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go:107 +0xb7
k8s.io/kubernetes/test/e2e/upgrades/apps.(*DaemonSetUpgradeTest).Test(0x78efa20, 0xc0004e98c0, 0xc0019c2060, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go:96 +0xa4
k8s.io/kubernetes/test/e2e/lifecycle.(*chaosMonkeyAdapter).Test(0xc00187f040, 0xc001a2dd60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/cluster_upgrade.go:453 +0x1ef
k8s.io/kubernetes/test/e2e/lifecycle.(*chaosMonkeyAdapter).Test-fm(0xc001a2dd60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/cluster_upgrade.go:522 +0x34
k8s.io/kubernetes/test/e2e/chaosmonkey.(*chaosmonkey).Do.func1(0xc001a2dd60, 0xc000b9e930)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/chaosmonkey/chaosmonkey.go:89 +0x76
created by k8s.io/kubernetes/test/e2e/chaosmonkey.(*chaosmonkey).Do
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/chaosmonkey/chaosmonkey.go:86 +0xa7
```
