### ISSUE TITLE
Pod sandbox changed, it will be killed and re-created.

### ISSUE THREAD

**Issue by FOSquare** [kubernetes/kubernetes#68885]
/sig Pod

Is this a BUG REPORT or FEATURE REQUEST?:

Uncomment only one, leave it on its own line:

/kind bug
**What happened**:

When I use deployment file to deploy an applicaiton. sometimes it works good. But sometimes it have problme shown below.

Normal   Scheduled       4m               default-scheduler  Successfully assigned default/streaming-client0-67d59b9969-8g9nb to thalassa
  Warning  Failed          2m               kubelet, thalassa  Error: context deadline exceeded
  Normal   SandboxChanged  2m               kubelet, thalassa  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         1m (x2 over 4m)  kubelet, thalassa  pulling image "cloudsuite/media-streaming:dataset"
  Normal   Pulled          1m (x2 over 4m)  kubelet, thalassa  Successfully pulled image "cloudsuite/media-streaming:dataset"

**What you expected to happen**:

I expect to see the container is normally created like below in another node:
  Normal  Pulling  <invalid> (x56 over 22h)  kubelet, erebos  pulling image "cloudsuite/media-streaming:client"
  Normal  Pulled   <invalid> (x56 over 22h)  kubelet, erebos  Successfully pulled image "cloudsuite/media-streaming:client"
  Normal  Created  <invalid> (x56 over 22h)  kubelet, erebos  Created container
  Normal  Started  <invalid> (x56 over 22h)  kubelet, erebos  Started container

**How to reproduce it (as minimally and precisely as possible):**

deployment the application

**Anything else we need to know?:**

I use the cloudsuite applicaiton Media-streaming.

Environment:

Kubernetes version (use kubectl version): v1.11.2
Cloud provider or hardware configuration: Dell poweredge R210 with interl NIC
OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS
Kernel (e.g. uname -a): 4.15.0-33-generic
Install tools: Ansible
Others:

Thanks a lot.

**Comment by FOSquare** [comment]
**The kubelet logs are shown below：**
-- Logs begin at mer. 2018-09-19 08:42:51 CEST. --
sept. 20 16:41:05 erebos kubelet[8665]: E0920 16:41:05.744437    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:41:06 erebos kubelet[8665]: W0920 16:41:06.384947    8665 pod_container_deletor.go:75] Container "f9186829b2bbde3ac1745cdc32d5fd61b9df5cb1ea046675ad34852135f04067" not found in pod's containers
sept. 20 16:42:06 erebos kubelet[8665]: W0920 16:42:06.808631    8665 pod_container_deletor.go:75] Container "9e08ba78d1e60a2ef8389518e9d95b100baea5880be04336bb4c8db3e35f7d0f" not found in pod's containers
sept. 20 16:42:55 erebos kubelet[8665]: W0920 16:42:55.926688    8665 pod_container_deletor.go:75] Container "71b0eae0bec1cc1937097679c658e20f0cb7e87c781c29218bc245ad5b792c7b" not found in pod's containers
sept. 20 16:43:05 erebos kubelet[8665]: E0920 16:43:05.653088    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
sept. 20 16:43:06 erebos kubelet[8665]: E0920 16:43:06.299706    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: context deadline exceeded
sept. 20 16:43:06 erebos kubelet[8665]: E0920 16:43:06.299808    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "context deadline exceeded"
sept. 20 16:43:12 erebos kubelet[8665]: W0920 16:43:12.511851    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:43:12 erebos kubelet[8665]: E0920 16:43:12.639179    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:43:41 erebos kubelet[8665]: W0920 16:43:41.305792    8665 pod_container_deletor.go:75] Container "763828a95ed4eb1cd456c38c214aaf5e94182022ea888b0707c5df488a591649" not found in pod's containers
sept. 20 16:45:13 erebos kubelet[8665]: E0920 16:45:12.673197    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
sept. 20 16:45:13 erebos kubelet[8665]: E0920 16:45:13.519769    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: context deadline exceeded
sept. 20 16:45:13 erebos kubelet[8665]: E0920 16:45:13.519897    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "context deadline exceeded"
sept. 20 16:45:21 erebos kubelet[8665]: W0920 16:45:21.122983    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:45:21 erebos kubelet[8665]: E0920 16:45:21.123906    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:47:21 erebos kubelet[8665]: E0920 16:47:21.214605    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
sept. 20 16:47:21 erebos kubelet[8665]: E0920 16:47:21.215374    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: operation timeout: context deadline exceeded
sept. 20 16:47:21 erebos kubelet[8665]: E0920 16:47:21.215434    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "operation timeout: context deadline exceeded"
sept. 20 16:47:31 erebos kubelet[8665]: W0920 16:47:31.650581    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:47:31 erebos kubelet[8665]: E0920 16:47:31.670058    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:48:05 erebos kubelet[8665]: W0920 16:48:05.379142    8665 pod_container_deletor.go:75] Container "30c10b0536c9c374e56f5a342fc1ef12f0905b2226b33b3b7adfd4c10f603422" not found in pod's containers
sept. 20 16:49:19 erebos kubelet[8665]: W0920 16:49:19.761156    8665 pod_container_deletor.go:75] Container "915f7ebe5461f3755a5ef1eed9554a0fb53379d0e30e6e3b0ded869f1cd14d5e" not found in pod's containers
sept. 20 16:49:28 erebos kubelet[8665]: E0920 16:49:28.687652    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
sept. 20 16:49:29 erebos kubelet[8665]: E0920 16:49:29.093065    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: context deadline exceeded
sept. 20 16:49:29 erebos kubelet[8665]: E0920 16:49:29.093166    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "context deadline exceeded"
sept. 20 16:49:36 erebos kubelet[8665]: W0920 16:49:36.137402    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:49:36 erebos kubelet[8665]: E0920 16:49:36.216358    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:51:36 erebos kubelet[8665]: E0920 16:51:36.104616    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
sept. 20 16:51:36 erebos kubelet[8665]: E0920 16:51:36.721455    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: context deadline exceeded
sept. 20 16:51:36 erebos kubelet[8665]: E0920 16:51:36.721558    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "context deadline exceeded"
sept. 20 16:51:41 erebos kubelet[8665]: W0920 16:51:41.922878    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:51:41 erebos kubelet[8665]: E0920 16:51:41.947416    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b
sept. 20 16:53:42 erebos kubelet[8665]: E0920 16:53:42.066391    8665 remote_runtime.go:187] CreateContainer in sandbox "f09ac71b68bbe331c74f50786f22e164818997d0169d664188be130da3d40c06" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
sept. 20 16:53:43 erebos kubelet[8665]: E0920 16:53:43.058195    8665 kuberuntime_manager.go:703] init container start failed: CreateContainerError: context deadline exceeded
sept. 20 16:53:43 erebos kubelet[8665]: E0920 16:53:43.058311    8665 pod_workers.go:186] Error syncing pod 324f1077-bcd5-11e8-9974-0026b97567f5 ("streaming-server11-b8458ff7c-25zrv_default(324f1077-bcd5-11e8-9974-0026b97567f5)"), skipping: failed to "StartContainer" for "streaming-dataset" with CreateContainerError: "context deadline exceeded"
sept. 20 16:53:48 erebos kubelet[8665]: W0920 16:53:48.158973    8665 helpers.go:284] Unable to create pod sandbox due to conflict. Attempting to remove sandbox "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b"
sept. 20 16:53:48 erebos kubelet[8665]: E0920 16:53:48.272499    8665 helpers.go:289] Failed to remove the conflicting container "3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b": Error response from daemon: No such container: 3766a2d46a3d49391718d0f8ff919d1beec53f2179aa9101abf3177d5199773b

**Comment by tossmilestone** [comment]
@FOSquare It seems kubelet call your container runtime failed through rpc, you should check logs of your container runtime(e.g. docker) to see what happened.

**Comment by FOSquare** [comment]
Thanks very much for you reply. I went to check the logs of the container at the node where the pod located. 
But when I type 
sudo docker logs 0eefbae6d297 
Nothing is shown. I tried to see logs of other pods that are in the status of "Init:CreateContainerError".
All with no logs. what will be your suggestions? Thanks again.

**Comment by FOSquare** [comment]
Thanks guys, I think I know the reason after dozens of tries. 

The reason is that I write a script to deployment mulitple applications at the same time. If more than two pods need to be initilized at the same physical node. This will casue the above problem. i guess the reason is that the physical node can not response the resource request at the same time. when one pod is initilized, I sleep for 5min , then deploy the next pod. this is fine.

**Comment by tossmilestone** [comment]
But what you described should not be a normal behavior of k8s, does your pod has special spec?

**Comment by FOSquare** [comment]
The pod has a initcontainer dataset with dataset.

below is the deployment file of the server (The applicaiton is media-streaming from cloudsuite  http://cloudsuite.ch/pages/download/). It works under docker swarm, and I change it into K8s now.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server0
spec:
  selector:
    matchLabels:
      app: streaming-server0
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: streaming-server0
    spec: 
      volumes:
      - name: data-set
        emptyDir: {}
      containers:
      - name: streaming-server0
        image: cloudsuite/media-streaming:server
        imagePullPolicy: Always # Never   #
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-set
          mountPath: /videos
      initContainers:
      - name: streaming-dataset
        image: cloudsuite/media-streaming:dataset
        imagePullPolicy: Always #Never #
        volumeMounts:
        - name: data-set
          mountPath: /videosshare
        command: [bash, -c]
        args: ["cp -r /videos/. /videosshare/"]

Thanks very much for your kind reply.
