### ISSUE TITLE
k8s.gcr.io/elasticsearch:v6.3.2 does not exist

### ISSUE THREAD

**Issue by xnike** [kubernetes/kubernetes#68891]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
Unable to deploy Kibana 6.3.2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rongshen** [comment]
I'm wondering if it is the same image as docker.elastic.co/elasticsearch/elasticsearch:6.3.2
