### ISSUE TITLE
consider setting ginkgo slow test threshold

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#68907]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**: since we use `ginkgo` to run our end to end tests despite nominally being a unit test framework, all tests are "slow test" in the log output due to being greater than the current threshold (default appears to be 5 seconds).

**What you expected to happen**: We should set the threshold to something we consider to be reasonable for an end to end test. What that is might need some thought.

/sig testing

brought up by @msau42

**Comment by BenTheElder** [comment]
ginkgo does have a `--slowSpecThreshold=TIME_IN_SECONDS`

@kubernetes/test-infra-maintainers we could try setting this in a job and see how it works out before we try to recommend one more generally.

@kubernetes/sig-testing WDYT?

**Comment by fejta** [comment]
This could be as simple as editing: 
https://github.com/kubernetes/kubernetes/blob/fbc7114734da7e15e2dc4c476d2546b333a93bc2/hack/ginkgo-e2e.sh#L143-L171

**Comment by pradeepmurugesan** [comment]
@fejta I can make the change..
