### ISSUE TITLE
Azure Cloud Provider: Wrong implementation of `InstanceShutdownByProviderID`

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#68916]
/kind bug

**What happened**:
Azure cloud provider uses `VM.ProvisioningState` to determine if the VM is running. Which never returns true even if the VM is not running (ref: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_vmss.go#L137). The provider should uses (and parse) InstanceView.Statuses array -- specifically `PowerState/running` status. This currently impacts taints (i.e this taint `node.cloudprovider.kubernetes.io/shutdown:NoSchedule` is never added to the node as it goes down)

Fix: 
1. Add new functioning example `GetVMPowerStatus` returns true/false
2. replace https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_instances.go#L145 logic to call this new function

@feiskyer

**Comment by khenidak** [comment]
@kubernetes/sig-azure

**Comment by feiskyer** [comment]
Oops, thanks @khenidak. This is critical, it should be fixed before v1.12 release. 

/priority critical-urgent
/milestone v1.12

**Comment by justaugustus** [comment]
@feiskyer @andyzhangx -- how quickly could we have a fix for this? We're basically out of time for this release cycle.

**Comment by feiskyer** [comment]
@justaugustus The code is ready, I'm validating now. Please wait a moment.

**Comment by justaugustus** [comment]
@feiskyer -- sounds good. Keep me posted.

**Comment by feiskyer** [comment]
@justaugustus Filed #68921.
