### ISSUE TITLE
Kubernetes rest_client_* metrics within controller-manager explode in cardinality when deleting many uniquely named namespaces

### ISSUE THREAD

**Issue by mwhittington21** [kubernetes/kubernetes#68918]
/kind bug

**What happened**:

When creating and deleting a large number of uniquely named namespaces the controller-manager does a lot of GET/LIST/DELETE operations on objects within those namespaces. This is fine and expected. However, the amount of metrics stored balloons because each separate URL for each resource within each uniquely named namespace is stored once for each resource/namespace name combo, multiplied by the number of buckets in the histogram, multiplied by the different type of request (e.g. GET/LIST/DELETE/etc).

This causes the metrics to take up more and more memory, take longer and longer to get scraped by prometheus, prometheus takes more and more memory to even perform the scrape, prometheus OOMs more often, and the controller-manager in question eventually OOMs too.

I actually OOMed a controller-manager instance trying to get a set of metrics to show the cardinality. (ip-addresses are obfuscated)

```
ip-x-x-x-x ~ # curl localhost:10252/metrics > cm_metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
curl: (52) Empty reply from server
```

When I tried on a different instance I got back this many metrics (although we've seen 5x more than this before):

```
ip-x-x-x-x ~ # curl localhost:10252/metrics > cm_metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48.9M  100 48.9M    0     0  75.3M      0 --:--:-- --:--:-- --:--:-- 75.3M
ip-x-x-x-x ~ # wc -l cm_metrics
270122 cm_metrics
```

Most of the metrics are just histograms of the different URLs, for example:

```
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.001"} 0
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.002"} 0
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.004"} 0
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.008"} 0
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.016"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.032"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.064"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.128"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.256"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="0.512"} 1
rest_client_request_latency_seconds_bucket{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE",le="+Inf"} 1
rest_client_request_latency_seconds_sum{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE"} 0.00884545
rest_client_request_latency_seconds_count{url="https://localhost:443/apis/rbac.authorization.k8s.io/v1/namespaces/fc57b140-8e9b-4c50-82ba-d3f12b0c54bb/rolebindings",verb="DELETE"} 1
```

**What you expected to happen**:

That the controller-manager does not OOM just by performing it's job garbage collecting things within a deleted namespace while also being scraped for metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Create and delete thousands of namespaces with unique names while also scraping the `/metrics` endpoint of the controller-manager at a regular (30s) interval. The controller-manager will OOM at some point, and if using prometheus to do the scraping prometheus will also OOM.

**Anything else we need to know?**:

This kind of cardinality explosion is because the labels are unbounded. In our case we don't even look at the particular metrics which are exploding in cardinality, we just scrape controller-manager for other things like memory usage. We have had to stop scraping at all to reduce the symptoms of this problem.

It would be nice if we could turn off the registration of the `rest_client_*` metrics with an environment variable or command line flag.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1800.7.0
VERSION_ID=1800.7.0
BUILD_ID=2018-08-15-2254
PRETTY_NAME="Container Linux by CoreOS 1800.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-155-66-77.ec2.internal 4.14.63-coreos #1 SMP Wed Aug 15 22:26:16 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
- controller-manager version: v1.11.1
- prometheus version: v2.2.1

**Comment by mwhittington21** [comment]
@kubernetes/sig-instrumentation-bugs

**Comment by mwhittington21** [comment]
Not totally sure it's instrumentations problem since the offending code is how the instrumentation is used in controller-manager, but I figure this can get pointed to the right place from there.

**Comment by brancz** [comment]
Thanks for reporting! Indeed this metric simply should not have the "url" label at all. Instead, it should just have a "resource" label (in the concretely shown example with the value "rolebindings") and not surface the namespace at all.
