### ISSUE TITLE
How to import the other servers log to EFK? Have any APIs?

### ISSUE THREAD

**Issue by sdnmw** [kubernetes/kubernetes#68926]
**How to import the other servers log to EFK?Have any APIs?**:

> Need to collect the server logs which are not a kubernetes node
>There is a kubernetes cluster with a master and a minion node with EFK and promethues 
> Have any programming interface to export server logs to EFK(Fluentd)?

**Environment**:
- Kubernetes version (use `v1.10.1`):
- OS (e.g. from /etc/os-release):CentOS 7.5
- Kernel (e.g. `uname -a`):x86_64 GNU/Linux
- Install tools: Kubeadm
- Others:
kubernetes could run EFK and promethues successfully.

**Comment by shubheksha** [comment]
/triage support
@sdnmw, you might want to try asking this in the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed

**Comment by shubheksha** [comment]
No response hence closing this.
/close
