### ISSUE TITLE
Kubelet default argument inconsistency between flags and config file

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubernetes#68939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I tried to start a kubelet in standalone mode but got an error
`failed to run Kubelet: no client provided, cannot use webhook authentication`

**What you expected to happen**:
I expected the kubelet to start up without needing a client because `kubelet --help` says:

```
      --authorization-mode string                                                                                 Authorization mode for Kubelet server. Valid options are AlwaysAllow or Webhook. Webhook mode uses the SubjectAccessReview API to determine authorization. (default "AlwaysAllow") (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
```
However looking at the code I see:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L75

(defaults to webhook). Since I'm using a config file and the help tells me to do as much, it should either tell me the *flag* has a default of alwaysallow and the config has a default of webhook, OR the defaults should be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubelet, maybe with a config file

**Anything else we need to know?**:
kubelet systemd file:

```
[Service]
# Uncomment if you are using containerd
Environment="KUBELET_CRI_ENDPOINT=--container-runtime-endpoint=unix:///var/run/containerd/container.sock"
ExecStart=
ExecStart=/usr/bin/kubelet --config /var/lib/kubelet/config.yaml --allow-privileged $KUBELET_CRI_ENDPOINT
Restart=always
```

kubelet  config file
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 127.0.0.1
staticPodPath: /etc/kubernetes/manifests
```

**Environment**:
a recent version of kubelet
```
root@ip-10-0-0-8:~# kubelet --version
Kubernetes v1.13.0-alpha.0.1353+d1111a57d9243c
```

**Comment by Pingan2017** [comment]
see #59666 
should disable webhook when using --config

**Comment by mtaufen** [comment]
The defaults are intentionally different, since the transition from flags to config provided the opportunity to fix some insecure flag defaults. 

Agree that the help should do a better job of telling folks what the defaults are in each case.

**Comment by tmlbl** [comment]
I am running into this trying to run kubelet in standalone mode on `v1.12.8` and it is quite confusing. I can start with:
```
kubelet --cgroup-driver=systemd --pod-manifest-path /etc/kubelet.d
```
But the ostensibly equivalent config file:
```yaml
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 127.0.0.1
cgroupDriver: systemd
staticPodPath: /etc/kubelet.d
authorization:
  mode: AlwaysAllow
```
gives the following error:
```
# kubelet --config kubelet.yaml 
I0509 18:57:23.797635   25011 server.go:408] Version: v1.12.8
I0509 18:57:23.797789   25011 plugins.go:99] No cloud provider specified.
W0509 18:57:23.797825   25011 server.go:553] standalone mode, no API client
F0509 18:57:23.797841   25011 server.go:262] failed to run Kubelet: no client provided, cannot use webhook authentication
```

**Comment by mtaufen** [comment]
Standalone mode isn't the mode we configure defaults to target, so it's expected that users may have to reconfigure the auth settings, or others, to fit that mode of operation if they opt into it. 

Users didn't have to do this with flags because the defaults for server mode were insecure. We fixed this in the config file, which represents a new version of the config API.

That defaults may differ is intentional, and documented here: https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file

If someone wants to fix the help, I'm happy to review the PR...

**Comment by mwhahaha** [comment]
For the next person who hits this, I figured out the expected values. So when you --config, authentication is defaulted to webook where as via the cli it's set to anonymous by default.  

```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 127.0.0.1
cgroupDriver: systemd
staticPodPath: /etc/kubelet.d
authentication:
  anonymous:
    enabled: true
  webook:
    enabled: false
authorization:
  mode: AlwaysAllow
```


NOTE: it would be awesome to generated default configs in the actual yaml/json structure somewhere rather than having to work backwards in go (which I am not that familiar with).

**Comment by furkanmustafa** [comment]
```
authorization:
  mode: AlwaysAllow
```

even with this :point_up: it doesn't work for me.

```
W0913 17:03:04.201922    4165 server.go:557] standalone mode, no API client
F0913 17:03:04.202053    4165 server.go:266] failed to run Kubelet: no client provided, cannot use webhook authentication
```

It recognizes it very well though;
```
I0913 17:03:04.183668    4165 flags.go:33] FLAG: --authorization-mode="AlwaysAllow"
```

**Comment by furkanmustafa** [comment]
DAMN. It was a [typo](https://github.com/kubernetes/kubernetes/issues/68939#issuecomment-530135242). ( webook )

```
authentication:
  anonymous:
    enabled: true
  webook:
    enabled: false
```
