### ISSUE TITLE
Selective Image garbage collection in kubelet

### ISSUE THREAD

**Issue by senthilrch** [kubernetes/kubernetes#68930]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Kubelet has a Image GC loop that removes unused images when the disk usage exceeds a max threshold. It is possible to turn off image GC completely.

However there are use cases where users require the time duration between Pod scheduling and Pod ready status to be the least. Since kubelet GC will clean-up unused images, kubelet needs to re-pull the container image when starting up new Pods.

**What you expected to happen**:
I should be able to mark certain container images or repositories which will not be affected by kubelet's GC. Either by means of a flag or configuration file (json). Kubelet should not remove those images even when it is unused. The onus of using this feature judiciously is with the administrator to apply this feature only to a very few container images that require such high performance.

**How to reproduce it (as minimally and precisely as possible)**:
This is a new feature request.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by senthilrch** [comment]
https://github.com/kubernetes/kubernetes/issues/66221

**Comment by bhack** [comment]
https://github.com/kubernetes/minikube/issues/2705
