### ISSUE TITLE
ControllerClientBuilder and related items should be broken into a separate utility.

### ISSUE THREAD

**Issue by cheftako** [kubernetes/kubernetes#68947]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
The ControllerClientBuilder interface is being depended on by items which are being moved out core K8s/K8s.
As such they should be moved into staging/their own repo for controller based utilities.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by justinsb** [comment]
Do we have a suitable repo in mind, or would this be a new one?  controller-runtime or client-go maybe?

**Comment by cheftako** [comment]
I was thinking a new one but could be convinced otherwise. Largely this is a reflection of the cloud provider interface needing to depend on the ControllerClientBuilder interface. As we want to move that to staging (https://github.com/kubernetes/kubernetes/pull/68310) then the interface also needs to be in staging. I wanted to tackle that in pieces. So I filed this bug to make sure that happened.

**Comment by stewart-yu** [comment]
Now that `ControllerClientBuilder` in `pkg/controller` packages, why not move it to `pkg/controller-runtime` directory (we should new the directory) in `k8s.io/kube-controller-manager` repo? @cheftako @justinsb

**Comment by andrewsykim** [comment]
Do we need a controllers util repo for this? Can that just go into client-go?

**Comment by andrewsykim** [comment]
/remove-lifecycle stale

We still need a better home for ControllerClient, it's been duplicated in a few places already
