### ISSUE TITLE
DNS Problem on new namespace

### ISSUE THREAD

**Issue by danilorsilva** [kubernetes/kubernetes#68941]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
After create a new namespace, all deployments inside this new namespace don't have connection with the external world. 

**What you expected to happen**:
Deployement can access internet, name resolution, etc...

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create namespace teste and deploy a basic nginx deployment

**Anything else we need to know?**:
Kubernete 1.10.3 with Kops

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.3 
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by danilorsilva** [comment]
Issue resolved.

A problem with calico-kube-controller.

Thanks!

**Comment by Moshem123** [comment]
> Issue resolved.
> 
> A problem with calico-kube-controller.
> 
> Thanks!

Amazing. Wasted 3 hours investigating this. Turns out  calico-kube-controller didn't have any pods running.
