### ISSUE TITLE
hack/local-up-cluster.sh always download cfssl even when on PATH

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#68946]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When running ./hack/local-up-cluster.sh, it always download `cfssl` even when the tool is found on the system $PATH.

First validate cfssl is installed:
```bash
$> which cfssl
/usr/bin/cfssl

$> cfssl
No command is given.
Usage:
Available commands:
	certinfo
	serve
	revoke
	bundle
	ocspdump
...
```

Next run local-up-cluster.sh script

```bash
LOG_LEVEL=4 ALLOW_PRIVILEGED=true FEATURE_GATES="KubeletPluginsWatcher=true" ./hack/local-up-cluster.sh
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap.
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory '/home/user/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/user/go/src/k8s.io/kubernetes'
make[1]: Leaving directory '/home/user/go/src/k8s.io/kubernetes'
+++ [0921 16:19:25] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
make: Leaving directory '/home/user/go/src/k8s.io/kubernetes'
WARNING: No swap limit support
Kubelet cgroup driver defaulted to use: cgroupfs
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Unable to successfully run 'cfssl' from /home/user/go/src/k8s.io/kubernetes/_output/bin:/home/user/go/bin:/home/user/go/src/k8s.io/kubernetes/third_party/etcd:/home/user/go/src/k8s.io/kubernetes/_output/bin:/home/user/go/bin:/home/user/go/src/k8s.io/kubernetes/third_party/etcd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/local/go/bin; downloading instead...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0  6021k      0  0:00:01  0:00:01 --:--:-- 6021k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2224k  100 2224k    0     0  2249k      0 --:--:-- --:--:-- --:--:-- 2246k
```
 
**What you expected to happen**:
Expecting that the script would skip download and find cfssl on the path.

**How to reproduce it (as minimally and precisely as possible)**:
The following is what I ran, the env variables not necessary to reproduce.
```bash
LOG_LEVEL=4 ALLOW_PRIVILEGED=true FEATURE_GATES="KubeletPluginsWatcher=true" ./hack/local-up-cluster.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.0.1353+d1111a57d9243c", GitCommit:"d1111a57d9243c55e02e0e66af55c2ddb36f3767", GitTreeState:"clean", BuildDate:"2018-09-21T20:19:25Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release):
```bash
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by vladimirvivien** [comment]
Not sure which sig handles script....

/sig release ? Maybe ?

**Comment by BenTheElder** [comment]
cluster/ is
/sig cluster-lifecycle
/remove-sig release

Previously we tried to use CFSSL installed from vendor to fix this, but we ran into some problems when the script is run from a tarball rather than a git checkout.

**Comment by nikhita** [comment]
> Previously we tried to use CFSSL installed from vendor to fix this, but we ran into some problems when the script is run from a tarball rather than a git checkout.

:+1: IIRC that was for when CFSSL was not on $PATH and it was getting downloaded each time the script was run on each execution (https://github.com/kubernetes/kubernetes/issues/60070).

In this case, it looks like CFSSL in in the $PATH, so it would work seamlessly... :thinking:

**Comment by BenTheElder** [comment]
We depend somewhat on the version though, so there was some concern about
trivially falling back to $PATH. We need to check versions for cfssl and
cfssljson and probably add installing newer ones in the test images

**Comment by BenTheElder** [comment]
/hel

This issue is not completely trivial, but also doable. Fixing it will require:
Follow up on https://github.com/kubernetes/kubernetes/pull/67178, we've already vendored a reasonable version, but we need to update the script to do:
- attempt to install from vendor, if succesful return these
- check if cfssl / cfssljson in $PATH meet minium requirements, if so return these
- otherwise rror

The images in [kubernetes/test-infra](https://github.com/kubernetes/test-infra) /images (namely images/kubekins-e2e) will need an update to install this version, this is slightly tricky as currently they also depend on the upstream binary releases, which stopped being published for new versions a while back..

@cblecker and I discussed this but decided to just unbreak the CI for now and haven't had time to circle back on this. I'm happy to help review PRs to fix this and might get to it myself at some point.

**Comment by PrasadG193** [comment]
I will work on this. Can you please assign it to me?

**Comment by nikhita** [comment]
> I will work on this. Can you please assign it to me?

@PrasadG193 Only @kubernetes org members can be assigned, but consider yourself assigned and feel free to work on this issue. :)

**Comment by PrasadG193** [comment]
@vladimirvivien I am not able to reproduce this on ubuntu 18.04 with k8s on master branch. 
```
$ LOG_LEVEL=4 ALLOW_PRIVILEGED=true FEATURE_GATES="KubeletPluginsWatcher=true" ./hack/local-up-c$
uster.sh
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap.
WARNING : This script MAY be run as root for docker socket / iptables functionality; if failures occur, retry as root.
make: Entering directory '/home/prasad/go-ws/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/prasad/go-ws/src/k8s.io/kubernetes'
make[1]: Leaving directory '/home/prasad/go-ws/src/k8s.io/kubernetes'
+++ [1005 21:24:04] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/hyperkube
make: Leaving directory '/home/prasad/go-ws/src/k8s.io/kubernetes'
WARNING: No swap limit support
Kubelet cgroup driver defaulted to use: cgroupfs
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Detected host and ready to start services.  Doing some housekeeping first...
Using GO_OUT /home/prasad/go-ws/src/k8s.io/kubernetes/_output/local/bin/linux/amd64
Starting services now!
Starting etcd
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.dURTmzy3kk --listen-client-urls http://127.0.0.1:2379 --debug > "/tmp/etcd.log"
 2>/dev/null
Waiting for etcd to come up.
+++ [1005 21:26:28] On try 2, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
Generating a 2048 bit RSA private key
..........................+++
....+++
writing new private key to '/var/run/kubernetes/server-ca.key'
```
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by neolit123** [comment]
any updates here?

**Comment by PrasadG193** [comment]
Hi @neolit123, I am not able to reproduce this issue on master branch. I think it's already fixed

**Comment by neolit123** [comment]
@PrasadG193 thanks for testing.
hm, it's either that or setup specific.

@vladimirvivien does the latest master work for you?

**Comment by b1zzu** [comment]
Hi @vladimirvivien, can you also check if *cfssljson* is in *PATH*: `which cfssljson`?

If *cfssljson* is missing than is enough to update the error massage to: `Unable to successfully run 'cfssl' and 'cfssljson' from $PATH; downloading instead...`
