### ISSUE TITLE
[scheduler cleanup phase 1]: Move `NodeInfo` utils into pkg/scheduler/cache

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68958]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

There are utility functions for use with the `NodeInfo` type in `k8s.io/kubernetes/pkg/scheduler/util`. These should be moved into `k8s.io/kubernetes/pkg/scheduler/cache` because that is where the `NodeInfo` type is defined.

/ref https://github.com/kubernetes/kubernetes/issues/68961
/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by wgliang** [comment]
Because it is related to the cache, I will fix this issue together.
/remove-help
/assign

**Comment by misterikkit** [comment]
Will this PR be ready for review soon? If you don't have time for it, we can find someone to help.
