### ISSUE TITLE
[scheduler cleanup phase 1]: Create a new Scheduler constructor

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68954]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

Constructing a `Scheduler` object requires a lot of boilerplate, as evidenced by the code in `cmd/kube-scheduler`. It requires calls to `NewConfigFactory` followed by `CreateFromConfig` or `CreateFromProvider` and finally a call to `NewFromConfig`.

We should create a function `New` in the main scheduler package `k8s.io/kubernetes/pkg/scheduler` that combines all the arguments from the existing, multi-step process. ~~This constructor should take a `SharedInformerFactory` arg instead of individual informers.~~ This constructor will take each informer and lister as a separate arg, so that the types we care about are implicitly documented. For optional arguments, we should use the [“functional options” pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis).

To start, the new constructor can be implemented by calling the existing ones. Shuffling the code around and deleting old constructors will come later.

See also: https://github.com/kubernetes/kubernetes/issues/68955

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by denkensk** [comment]
I want to take it @misterikkit

**Comment by denkensk** [comment]
I want to take it，Can you help me to contribute to it？

**Comment by misterikkit** [comment]
I got some feedback from @smarterclayton and @bsalamat on this, and it is preferred for the constructor to take each informer and lister as a separate argument. Sorry to change the requirement on you. Could you update your code based on that?

**Comment by nikhita** [comment]
@misterikkit based on the conversation on Slack, I'm guessing you no longer want the help wanted labels here? Removing it now, please add it back later if they should be here. :)

/remove-help

**Comment by misterikkit** [comment]
After some discussion with @denkensk, creating the new constructor creates an import loop unless we do some extra work. The current plan is to take the plunge and remove the old constructors in this PR, migrating users to the new one.

The alternative involves adding a bunch of temporary complexity (i.e. a new package) during the migration.

This will likely cause conflicts with https://github.com/kubernetes/kubernetes/issues/68955 so may be good to discuss with @krmayankk.
