### ISSUE TITLE
[scheduler cleanup phase 1]: Move informer event handlers to pkg/scheduler

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68955]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

A lot of the behavior of `genericScheduler` is captured inside the informer event handlers in `pkg/scheduler/factory/factory.go`. Our code will be easier to maintain if the behavior of `genericScheduler` is not spread across different packages, so we should move all informer event handlers to be methods of `genericScheduler`.

When these functions move, we should also fix their names to be consistent. Most of them are named like `onPvAdd` and there are a few that need to be updated to match this pattern.

See also: https://github.com/kubernetes/kubernetes/issues/68954

/sig scheduling
/kind cleanup
/help

**UPDATE:**
After discussion, we decided that it is better to move the event handlers into the `k8s.io/kubernetes/pkg/scheduler` package.

**Comment by misterikkit** [comment]
Be sure to reach out if you get stuck. I think this might be one of the trickier tasks.

**Comment by krmayankk** [comment]
Sounds good , should have a pr by Friday @misterikkit and will discuss on slack

**Comment by misterikkit** [comment]
@krmayankk Will the PR be ready for review soon?

**Comment by misterikkit** [comment]
@bsalamat I think the last time we discussed this, you had a reason that event handlers shouldn't all go inside the `core` package. It centered around how the cache code is organized relative to `core`.

**Comment by bsalamat** [comment]
@misterikkit Yes, the scheduler cache and its event handlers are owned by the external layer of the scheduler which lives in pkg/scheduler/scheduler.go. The cache is passed by the external component to the internal part of the scheduler. I believe the external part is responsible for updating the cache and the event handler should stay there.

**Comment by misterikkit** [comment]
So after some discussion, it seems like our informer event handlers do three things.
1. update our cache
2. update our equivalence cache
3. update our scheduling queue

I think that these should be split into separate event handlers, such that all cache-updating handlers are part of the `cache` package, and all queue-updating handlers are part of the `queue` package.

This should also rebase on top of https://github.com/kubernetes/kubernetes/pull/71399 because that deletes the equivalence cache code. While the eCache still exists, it is very tricky to split the event handlers. That is because we rely on specific ordering of cache and eCache updates.

WDYT?

**Comment by misterikkit** [comment]
Forgot to mention: Splitting the handlers should not incur a substantial performance penalty. We use `SharedInformerFactory`, so the API calls and informer cache are shared by all event handlers.

**Comment by krmayankk** [comment]
@misterikkit  are you talking about scheduler/internal/cache or scheduler/cache ? ( i think the former)

We have the following Queue and Caches being manipulated by the event handlers.

podQueue internalqueue.SchedulingQueue
schedulerCache schedulerinternalcache.Cache
equivalencePodCache *equivalence.Cache
 Is moving both the caches to internal/cache ok ? I think they should be in different packages
If we separate the handlers, location, we still need to pass the informers all the way from cmd/kube-scheduler to scheduler.go New()
 Is the approach in the PR still looks good ?

**Comment by misterikkit** [comment]
@krmayankk Yes, I meant `scheduler/internal/cache`. `equivalenceCache` is being removed (and redesigned) starting with https://github.com/kubernetes/kubernetes/pull/71399, so those event handlers will go away (along with the requirement to sequence cache vs eCache updates).



> * Is moving both the caches to internal/cache ok ?

I agree with you that cache and eCache belong in separate packages.



> * we still need to pass the informers all the way

I think the informers should be passed into `cache.New` and `queue.NewSchedulingQueue`.

> * Is the approach in the PR still looks good ?

It looks like the PR moves event handlers into `pkg/scheduler/scheduler.go`. The move looks fine except for the destination. If you rebase on #71399 (or wait for it to merge) then you can split the event handlers and move them into the packages I mention above.

**Comment by krmayankk** [comment]
@misterikkit 

>  I think that these should be split into separate event handlers, such that all cache-updating handlers are part of the cache package, and all queue-updating handlers are part of the queue package.

I dont think the above separation is being strictly followed. For e.g. in addNodeToCache 
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory/factory.go#L971  updates the schedulerCache and https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory/factory.go#L975 updates the SchedulingQueue.

**Comment by misterikkit** [comment]
> I dont think the above separation is being strictly followed.

You are correct. I would like that to be resolved as part of this issue. I think that we could accomplish this by passing the various informers into the constructor for both cache and queue. The two modules might add event handlers for the same event, but that is OK. Since our informers come from a `SharedInformerFactory`, the overhead will be small.

**Comment by krmayankk** [comment]
currently in discussion on sig-scheduling mailing list
