### ISSUE TITLE
Inject `FeatureGate` instead of checking global variable

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68957]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The scheduler has various feature gates that enable/disable specific behaviors. E.g.

```golang
if utilfeature.DefaultFeatureGate.Enabled(features.VolumeScheduling) {
	// Setup volume binder
}
```

And in tests, we often see things like the following.
```golang
defer utilfeaturetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.AttachVolumeLimit, true)()
```
```golang
utilfeature.DefaultFeatureGate.Set(fmt.Sprintf("%s=true", features.BalanceAttachedNodeVolumes))
```

A lot of this boilerplate is needed because `DefaultFeatureGate` is a global variable. Searching through scheduler unit and integration tests, we don't always reset values at the end of tests. To get around this, we should copy `DefaultFeatureGate` at initialization time, and inject that into the scheduler. Then we can remove a bunch of complexity from our tests and also guarantee that state won't leak between tests.

We should also delete `func PodPriorityEnabled()` from `pkg/scheduler/utils`.

Note: Previously, this issue suggested that we should create a new package in scheduler for managing features. Discussion showed this idea to be unnecessary.

/sig scheduling
/kind cleanup

**Comment by PrasadG193** [comment]
I would like to work on this.
@misterikkit Just to confirm, in new feature pkg, we need to add support for `featuregate.Enabled()` and `featuregate.AddFlag()`, right?

**Comment by misterikkit** [comment]
@PrasadG193 I think that's basically it. There are a handful of examples throughout the scheduler code similar to my code snippet above. Today they are inconsistent, so it would be great to have a consistent way to check features.

More importantly, though, I want us to have a type (struct or whatever) that holds the state of the features we care about. We could initialize it from the global state in `feature.DefaultFeatureGate` and then pass it around, or we could inject a fake one for tests.

**Comment by misterikkit** [comment]
@PrasadG193 Let me know if you want to work on this.

**Comment by PrasadG193** [comment]
@misterikkit I'll work on this, can you please assign it to me?

**Comment by misterikkit** [comment]
Hey, just so we're on the same page, it doesn't matter that the bot won't let me assign the issue to you. Let me know if you get stuck on this.

**Comment by PrasadG193** [comment]
@misterikkit would copying `staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go` to `pkg/scheduler/feature/feature_gate.go` and replacing import `utilfeature "k8s.io/apiserver/pkg/util/feature"` with `utilfeature "k8s.io/pkg/scheduler/feature"` across scheduler code work? Also trying to understand, exactly what kind of inconsistency you were mentioning? Because I see the way we are checking feature is uniform accross scheduler code i.e 
```
if utilfeature.DefaultFeatureGate.Enabled(somefeature) {
	// some code
}
```

**Comment by misterikkit** [comment]
> what kind of inconsistency you were mentioning?

Sometimes we access `feature.DefaultFeatureGate` directly, and sometimes we [use a helper](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/util/utils.go#L158). Sometimes we `import "k8s.io/apiserver/pkg/util/feature"` and sometimes we `import utilfeature "k8s.io/apiserver/pkg/util/feature"`. Those are actually pretty minor inconsistencies.

Also, we get the feature keys from `k8s.io/kubernetes/pkg/features` and have to do the lookup in `k8s.io/apiserver/pkg/util/feature`. That just bugs me. :disappointed: 

I think the real problem that should be addressed, however, is that `DefaultFeatureGate` is a global variable. In particular, this makes some of our tests difficult to maintain. (for example, see [`SetDefaultFeatureGateDuringTest`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go#L107). Looking through our tests, we often don't reset the values when we are done. And when we do, it's a lot of boilerplate.)

> would copying `staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go` ... work?

I don't think we should copy this. As a minimum, we could use `DefaultFeatureGate.DeepCopy()` when we initialize scheduler. Then we could pass in constructed `FeatureGate`s in tests.

As a piece of side commentary, I see a lot of `feature.DefaultFeatureGate.Set(fmt.Sprintf("%s=true", features.MyFeatureName))` in tests, and I just think this API has the wrong shape.


Anyway, after writing this, it's apparent that we don't need a brand new package. I will update the issue description. Thanks for your input!

**Comment by misterikkit** [comment]
I just realized that this issue will conflict with @denkensk's work in #68954. Best to coordinate with them.

**Comment by misterikkit** [comment]
Please read the comments on https://github.com/kubernetes/kubernetes/pull/69298

**Comment by PrasadG193** [comment]
I liked the idea of making a copy of DefaultFeature date and passing it around. Also not clearly understood what was the intention behind creating a Readonly interface

**Comment by misterikkit** [comment]
> not clearly understood what was the intention behind creating a Readonly interface

It would be an added benefit, once we make the copy, to provide some promise that the set of feature gates is immutable. The most important thing is making the copy and injecting it through constructors though.

**Comment by misterikkit** [comment]
Hey, how is this project going? Feel free to reach out if you need help.

**Comment by PrasadG193** [comment]
I was waiting for https://github.com/kubernetes/kubernetes/pull/69057 to get merged. Will rebase it with my changes and test it

**Comment by misterikkit** [comment]
@PrasadG193 From our last conversation, it sounded like some of the consumers of `FeatureGate` are stateless, so injecting an object would require more refactoring. Can you list those here?

**Comment by PrasadG193** [comment]
Hi @misterikkit,
We need to find a way to pass FeatureGate (from scheduler) to ResourceAllocationPriority{} struct (https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/priorities/balanced_resource_allocation.go#L29) since it is called when the package is imported. Rest of the changes are done and can be seen at https://github.com/PrasadG193/kubernetes/commit/4abbf63d31e25820b720e0952f16f6eda636b5bc. Also please let me know how we are planning to update tests.

**Comment by misterikkit** [comment]
Hey, I'm sorry I haven't gotten back to this in such a long time. I think we should switch to injected `FeatureGate` all at once, so we need all priority functions to be updated in the same PR.

So it seems that before we can continue with this, priority functions need to be refactored. That refactor will touch a lot of areas since we need to inject args all the way down. However, we are already planning on such a refactor after the [scheduling framework](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduling-framework.md) is in place.

How do you feel about postponing this change until that point?

**Comment by PrasadG193** [comment]
Sounds good to me. Thanks.

**Comment by misterikkit** [comment]
/remove-lifecycle stale

We hit some blockers, but it's still worth pursuing this when those blockers go away. Currently, our plan is that when we migrate predicates & priorities to the scheduling framework, we will be able to remove references to global variables.

**Comment by Huang-Wei** [comment]
> To get around this, we should copy DefaultFeatureGate at initialization time, and inject that into the scheduler. Then we can remove a bunch of complexity from our tests and also guarantee that state won't leak between tests.

Aha, #80144 happen to implement using the exact same idea.
