### ISSUE TITLE
[scheduler cleanup phase 1]: Refactor scheduler_test.go to use a fake k8s client

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68962]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The tests in `pkg/scheduler/scheduler_test.go` depend on mocking REST/HTTP with the utils in `pkg/scheduler/testing`. It would be much simpler to use `k8s.io/client-go/kubernetes/fake.Clientset` instead. None of the behavior under test depends on how the REST and HTTP stuff behaves.

/ref https://github.com/kubernetes/kubernetes/issues/68963
/sig scheduling
/kind cleanup
/help

**Comment by shubheksha** [comment]
I'm working on a very similar fix for service-catalog, so I can pick this up as well!

**Comment by shubheksha** [comment]
Ref https://github.com/kubernetes-incubator/service-catalog/issues/2358

**Comment by shubheksha** [comment]
I'll pick this up.
/assign

**Comment by misterikkit** [comment]
How is this cleanup going?
/remove-help

**Comment by tossmilestone** [comment]
@misterikkit I could also help to work on this, it's similar to #68963.

**Comment by misterikkit** [comment]
@tossmilestone You should check with @shubheksha since she was working on this.

**Comment by misterikkit** [comment]
@shubheksha have you had time to work on this?

**Comment by shubheksha** [comment]
@misterikkit, unfortunately no, as I'm on the move for a bit. @tossmilestone, feel free to pick this up!
/unassign

**Comment by misterikkit** [comment]
@shubheksha Don't worry about it. Hope things settle down for you. Phase 2 is coming.

**Comment by tossmilestone** [comment]
@misterikkit After inspect the `pkg/scheduler/scheduler_test.go`, I found that no mocking HTTP is used in the file. Could you help to verify if I missed something?

**Comment by misterikkit** [comment]
If you delete the `SelfLink` line here, the test breaks (hangs). That
should only happen if we are mocking the HTTP interactions directly.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler_test.go#L89

Also, the `Fake*Lister` types from `pkg/scheduler/testing` could be
replaced using a fake Clientset with real informers/listers. That might
cause slightly more boilerplate in these tests, but it eliminates our
custom testing utils. Less magic, fewer things to learn when trying to work
on scheduler.

**Comment by tossmilestone** [comment]
@misterikkit Got it, thanks!
