### ISSUE TITLE
[scheduler cleanup phase 1]: Move scheduler cache interface and implementation to pkg/scheduler/internal/cache

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68961]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The scheduler’s cache implementation is not meant to be exported as a golang library outside of the scheduler. It should be moved from `k8s.io/kubernetes/pkg/scheduler/cache` to `k8s.io/kubernetes/pkg/scheduler/internal/cache`.

There are some types in the current `cache` package, namely `NodeInfo`, which should remain where they are. These are actually used outside of the scheduler, and need to be decoupled from the cache implementation.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by wgliang** [comment]
I can help dot it.
/remove help
/assign
