### ISSUE TITLE
[scheduler cleanup phase 1]: Refactor factory_test.go to use a fake k8s client

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68963]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

The tests in `pkg/scheduler/factory/factory_test.go` depend on mocking REST/HTTP with the utils in `pkg/scheduler/testing`. It would be much simpler to use `k8s.io/client-go/kubernetes/fake.Clientset` instead. None of the behavior under test depends on how the REST and HTTP stuff behaves.

/ref https://github.com/kubernetes/kubernetes/issues/68962
/sig scheduling
/kind cleanup
/help

**Comment by shubheksha** [comment]
I'm working on a very similar fix for service-catalog, so I can pick this up as well!

**Comment by shubheksha** [comment]
Ref https://github.com/kubernetes-incubator/service-catalog/issues/2358

**Comment by shubheksha** [comment]
@tossmilestone, are you interested in working on this issue?

**Comment by tossmilestone** [comment]
@shubheksha yes, if you are not working on it, I will have a try. Thanks!

**Comment by misterikkit** [comment]
@tossmilestone Have you started this? How is it going?
/assign @tossmilestone 
/remove-help

**Comment by tossmilestone** [comment]
@misterikkit, I am now working on it. It will be done later.

**Comment by tossmilestone** [comment]
@misterikkit This Issue has been done, PTAL. See #69412.
