### ISSUE TITLE
[scheduler cleanup phase 1]: Simplify kube-scheduler’s server.go `run`

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/kubernetes#68964]
**PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE.** We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: https://github.com/kubernetes/kubernetes/issues/68951

In `cmd/kube-scheduler/app/server.go` the `NewSchedulerCommand()` function creates a `cobra.Command` object and populates the `Run` field with an anonymous function. At the end of that function, `Run()` is called, which contains the rest of our startup logic.

Rather than split this across two functions, we should put all the startup logic in one named function called `run` (not `Run`) so that constructing the `cobra.Command` object is much more plain.

/sig scheduling
/kind cleanup
/help
/good-first-issue

**Comment by denkensk** [comment]
I want to take it, can you help me? @misterikkit

**Comment by shubheksha** [comment]
I'll pick this up!
/assign
