### ISSUE TITLE
kube-controller-manager: error creating self-signed certificates, permission denied on v1.12.0-rc.2

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kubernetes#68973]
**BUG REPORT**:

/kind bug

**What happened**:

Kubernetes distro testing v1.12.0-rc.2 shows in setups with self-hosted control planes (i.e. apiserver, controller-manager, scheduler run as pods) that previously worked on v1.11.3 and prior, the kube-controller-manager now crash loops.

```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   kube-apiserver-2t77v                       1/1       Running            2          8m
kube-system   kube-controller-manager-6d6cf5968c-r4jzv   0/1       CrashLoopBackOff   6          9m
kube-system   kube-controller-manager-6d6cf5968c-szd6z   0/1       CrashLoopBackOff   6          9m
...
```

```
$ kubectl logs kube-controller-manager-6d6cf5968c-r4jzv -n kube-system
error creating self-signed certificates: mkdir /var/run/kubernetes: permission denied
```

Notably, the kube-controller-manager is run with:

```
     securityContext:
        runAsNonRoot: true
        runAsUser: 65534
```

which has been fine through to v1.11.3. Full [kube-controller-manager.yaml](https://github.com/poseidon/terraform-render-bootkube/blob/master/resources/manifests/kube-controller-manager.yaml).

**What you expected to happen**:

Controller manager may not assume it has root. Or should clarify if an additional mount is now required.

May have been introduced in https://github.com/kubernetes/kubernetes/pull/65867 cc @sttts

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-rc.2
- Cloud provider or hardware configuration: GCE, DigitalOcean, AWS
- OS (e.g. from /etc/os-release): Container Linux 1855.4.0
- Kernel (e.g. `uname -a`): 4.14.67-coreos
- Install tools: Typhoon

**Comment by dghubble** [comment]
Seems like distros like Typhoon, Tectonic, and Tectonic/Openshift may work around this explicitly passing some other path to kube-controller-manager's `--cert-dir string Default: "/var/run/kubernetes"`.

Appears this was also noticed by juju in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/645

**Comment by dims** [comment]
cc @sttts

**Comment by dims** [comment]
@tpepper WDYT? Can we get folks to write a note to cover this problem in known issues? https://github.com/kubernetes/kubernetes/issues/68840

**Comment by dghubble** [comment]
I've added an `emptyDir` mount to address that crashloop, which seems to work preliminary. kube-controller-manager was able to proceed with self-signed cert creation and hit a new bug I've filed separately https://github.com/kubernetes/kubernetes/issues/68986

Perhaps a suitable release note for this change is:

```
kube-controller-manager now requires a writable `--cert-dir` when self-signed certificates are generated
```

**Comment by liggitt** [comment]
the cert should not need to be persisted to disk. I don't think adding a writeable directory requirement is a very good idea

/assign @sttts

**Comment by liggitt** [comment]
Possible fixes

1. not enable by default if no cert is provided, rather than self-signing
2. do the self-sign cert in memory only, no disk persistence needed
3. don't enable by default at all

2 would be ideal but is likely too big a change at this point. 3 would be unfortunate. 1 could be a good compromise if the code change is contained.

**Comment by tpepper** [comment]
It's up to the SIG if this is a 1.12.0 blocker, or a Known Issue and 1.12.1 material.  I'm inclined to think the latter.

**Comment by dghubble** [comment]
@liggitt thanks for the clarifications. I would prefer to avoid my current workaround of giving it a writeable location so those all sound fine to me.

@sttts is there a full story around these controller-manager changes somewhere? I could mint actual certs, mount from a secret, update clients. If there's merit. Like, how big of a deal is it that this is now always enabled vs before? I'll probably read through the various diffs after vacation.

**Comment by tpepper** [comment]
If this is going to get some text in release notes Known Issues (seems like it should), somebody needs to draft the text and make a suggestion of it in #68840 ASAP.

**Comment by dims** [comment]
@lavalamp @deads2k Do we want to fix this for 1.12.1 (on friday)?

**Comment by lavalamp** [comment]
Self signing in memory means you get a different cert each time it starts. It's probably better than nothing but it's not how things are supposed to work (it's too inconvenient to manually verify the cert out of band in places users should trust it).

OTOH if you want to do that, maybe you'll provide a writable directory in the first place, or even a real cert. So I guess in-memory is probably OK.

**Comment by lavalamp** [comment]
Second thought: `/var/run/kubernetes` is a terrible default for the cert path.

It should have the word "certs" in the path somewhere.

If folks (inadvisably) run apiserver and controller manager on the same system, they should at least not both try to use certs from the same place, or worse, write them there.

I suggest `/var/run/kubernetes/controller-manager/certs` as the default.

**Comment by dghubble** [comment]
@sttts What components are now verifying these certs or supposed to be? I'd expect something to be failing since random certs are generated each time the pod restarts, but don't see any impact (implying this isn't yet improving security). Seems like controller-manager just added an HTTPS endpoint, but the HTTP one is still what's used right?

**Comment by dghubble** [comment]
I guess that aligns with the comment

> "not automatically wired yet, but 3rdparties could wire it"

**Comment by dghubble** [comment]
The autogenerated certs only have SANs for localhost and 127.0.0.1.

```
X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:localhost, IP Address:127.0.0.1
```

**Comment by liggitt** [comment]
> The autogenerated certs only have SANs for localhost and 127.0.0.1.

The auto generated certs are self signed, right? If so, and callers won't be able to validate the signer, which SANs they have don't really matter.

**Comment by dghubble** [comment]
Yeah, they're self-signed. So looks like the 1.12 controller-manager serves on HTTP/10252 (always on) and HTTPS/10257 (unless --secure-port=0). I guess the point of the original change was so some client could now choose to use the HTTPS endpoint with insecureSkipVerify. Main reason I was interested in the SAN is to get some clue about how a client would be expected to access these controller-manager pods (for contrast, apiserver SAN has DNS:kubernetes and an internal record that always resolves to a kube-apiserve pod).

**Comment by okeddie** [comment]
is this updated for the openstack cloud provider too?

**Comment by dghubble** [comment]
This issue wasn't related to any particular cloud provider. The cloud provider / hardware config field is just a typical part of filing an issue in case it had been related.

**Comment by dpmattos** [comment]
I have a writeable `/var/run/kubernetes` (I've tried other writeable directories too.)
I'm encountering this:
```
$ kube-apiserver
Error: error creating self-signed certificates: open /var/run/kubernetes/apiserver.crt: permission denied
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 192.168.99.101:8443 was refused - did you specify the right host or port?
```
```
$ minikube status
host: Running
kubelet: Running
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.101
``` 
Should I post elsewhere, or continue here?
