### ISSUE TITLE
centos7 use ipvs

### ISSUE THREAD

**Issue by ljhmily** [kubernetes/kubernetes#68975]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig network
/area kube-proxy
/area ipvs

**What happened**:
I0922 09:00:53.538133       1 feature_gate.go:230] feature gates: &{map[SupportIPVSProxyMode:true]}
I0922 09:00:53.565801       1 server_others.go:183] Using ipvs Proxier.
I0922 09:00:54.134194       1 server_others.go:210] Tearing down inactive rules.
I0922 09:00:54.151017       1 server.go:448] Version: v1.11.0
I0922 09:00:54.154370       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 262144
I0922 09:00:54.154415       1 conntrack.go:52] Setting nf_conntrack_max to 262144
I0922 09:00:54.154452       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0922 09:00:54.154484       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0922 09:00:54.154922       1 config.go:102] Starting endpoints config controller
I0922 09:00:54.154939       1 controller_utils.go:1025] Waiting for caches to sync for endpoints config controller
I0922 09:00:54.154964       1 config.go:202] Starting service config controller
I0922 09:00:54.154974       1 controller_utils.go:1025] Waiting for caches to sync for service config controller
I0922 09:00:54.255087       1 controller_utils.go:1032] Caches are synced for endpoints config controller
I0922 09:00:54.255087       1 controller_utils.go:1032] Caches are synced for service config controller
E0922 09:00:54.280910       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-NODE-PORT-TCP bitmap:port inet 1024 65536 0-65535 Kubernetes nodeport TCP port for masquerade purpose} map[] 0xc420029910} exist, error: error creating ipset KUBE-NODE-PORT-TCP, error: exit status 2
E0922 09:01:24.169450       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-EXTERNAL-IP hash:ip,port inet 1024 65536 0-65535 Kubernetes service external ip + port for masquerade and filter purpose} map[] 0xc420029910} exist, error: error creating ipset KUBE-EXTERNAL-IP, error: exit status 2
E0922 09:01:54.180358       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-EXTERNAL-IP hash:ip,port inet 1024 65536 0-65535 Kubernetes service external ip + port for masquerade and filter purpose} map[] 0xc420029910} exist, error: error creating ipset KUBE-EXTERNAL-IP, error: exit status 2

**What you expected to happen**:
Kube-proxy working in ipvs mode in centos 7.
E0922 09:01:54.180358       1 ipset.go:156] Failed to make sure ip set: &{{KUBE-EXTERNAL-IP hash:ip,port inet 1024 65536 0-65535 Kubernetes service external ip + port for masquerade and filter purpose} map[] 0xc420029910} exist, error: error creating ipset KUBE-EXTERNAL-IP, error: exit status 2

**How to reproduce it (as minimally and precisely as possible)**:
Initialize Kubernetes using full manual.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Kubernetes v1.11.3
- Cloud provider or hardware configuration:
openstack based virtual machine
- OS (e.g. from /etc/os-release):
centos7..3
- Kernel (e.g. `uname -a`):
3.10.0-514.el7.x86_64
- Install tools:
ipset v6.29, protocol version: 6
- Others:

**Comment by ljhmily** [comment]
this is ./pkg/proxy/ipvs/ipset.go bug, not ./pkg/util/ipset/ipset.go

**Comment by dims** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/68974 ?

**Comment by dims** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
the fix is merged in 1.11.1
发件人：Davanum Srinivas
收件人：kubernetes/kubernetes,
抄 送：dujun (D),Mention,
时间：2018-09-23 21:31:17
主 题：Re: [kubernetes/kubernetes] centos7 use ipvs (#68975)


cc @m1093782566<https://github.com/m1093782566>

**Comment by m1093782566** [comment]
I am going to close this issue as it's already fixed.
