### ISSUE TITLE
Apiextensions discovery is broken without kube-aggragator

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#68971]
/kind bug
/sig api-machinery
/area custom-resources

i am deploying aggregator dedicatedly in my local environment,  and the legacy server and the extension server is deployed in one via delegation. (is it supported yet? now there is a launch script for only aggregator).

then when i request the discovery to the legacy/extension server (skipping aggregator), it doesn't return any api group info about the extension server, neither crd's group (apiextensions.k8s.io) nor any cr's group. which is, the extension server's discovery is broken without aggregator now. 

after debugging into the code, i figured out that the discovery manager in the legacy server and the extension server is pointed to different instances. so all the api group info in the extension server is added to a "wild" discovery manager which will never be referenced for a read. 

/cc @sttts @nikhita

**Comment by liggitt** [comment]
the legacy server and the extension server are two distinct servers... aggregation is the mechanism by which they both contribute API groups to discovery. I would not expect either the legacy or the extension server to know about or return API group info about the other

/cc @dead

**Comment by yue9944882** [comment]
> the legacy server and the extension server are two distinct servers... aggregation is the mechanism by which they both contribute API groups to discovery.

@liggitt if we're handling all the group discovery in the aggregator, why not just completely remove the group discovery from the other two servers? i see for the extension server, the `/apis` is disabled and the `/apis/<group>` is still serving. for the legacy server, even both `/apis` and `/apis/<group>` is dry serving and no requests will ever reach these handlers. 😢

[https://github.com/kubernetes/kubernetes/blob/7ffaa2f7131238db4cfdb034e260f6ad576cd70d/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go#L112](https://github.com/kubernetes/kubernetes/blob/7ffaa2f7131238db4cfdb034e260f6ad576cd70d/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go#L112)

**Comment by liggitt** [comment]
> @liggitt if we're handling all the group discovery in the aggregator, why not just completely remove the group discovery from the other two servers?

Aggregation serves `/apis and /apis/group`

Individual servers serve `/apis/<group>/<version>` (aggregation doesn't have details about the resources contained in the API group/version)
