### ISSUE TITLE
ClusterRole system:kube-controller-manager cannot get configmaps in v1.12.0-rc's

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kubernetes#68986]
**BUG REPORT**:

/kind bug
/sig auth

**What happened**:

Kubernetes distro testing v1.12.0-rc.2 shows in setups with self-hosted control planes (i.e. apiserver, controller-manager, scheduler run as pods) that previously worked on v1.11.3 and prior, the kube-controller-manager now crash loops with:

```
kubectl logs kube-controller-manager-66d694fd76-nj5sf -n kube-system
W0923 04:05:46.836870       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.                                                            
W0923 04:05:47.537843       1 authentication.go:246] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=exten
sion-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:kube-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

The kube-controller-manager is run with a [service account](https://github.com/poseidon/terraform-render-bootkube/blob/master/resources/manifests/kube-controller-manager.yaml#L74) with a [ClusterRoleBinding](https://github.com/poseidon/terraform-render-bootkube/blob/master/resources/manifests/kube-controller-manager-role-binding.yaml#L8) to the default system ClusterRole `system:kube-controller-manager`, which seems to be defined at https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L400

Editing the ClusterRole manually to add `get` for `configmaps` was sufficient to fix the crash loop.

```
$ kubectl edit clusterrole system:kube-controller-manager
...
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - secrets
  - configmaps        <-- add me
  - serviceaccounts
  verbs:
  - get
```

**What you expected to happen**:

I suspect a change between v1.11.3 and v1.12.0 release candidates altered kube-controller-manager to begin looking for configmap `extension-apiserver-authentication`, but didn't update the ClusterRoles. 

**How to reproduce it (as minimally and precisely as possible)**:

Release candidate testing is happening in https://github.com/poseidon/typhoon/pull/301

**Anything else we need to know?**:
**Environment**:

* Kubernetes version (use kubectl version): v1.12.0-rc.2
* Cloud provider or hardware configuration: GCE, DigitalOcean, AWS
* OS (e.g. from /etc/os-release): Container Linux 1855.4.0
* Kernel (e.g. uname -a): 4.14.67-coreos
* Install tools: Typhoon

**Comment by liggitt** [comment]
/sig cluster-lifecycle
/area kubeadm
/remove-sig auth

This permission is not a default permission. If it is required for a kubeadm setup, then it must be granted by kubeadm

**Comment by dims** [comment]
@dghubble can you please try if `--authentication-skip-lookup` works to skip that lookup?

**Comment by sttts** [comment]
@liggitt we can make this non-fatal, compare https://github.com/kubernetes/kubernetes/pull/67836/files#diff-59f09be65a7ae1feb263f6bce1d856b1R246.

**Comment by dghubble** [comment]
@dims adding that flag to the controller-manager does also work to skip the lookup, without me manually editing the ClusterRole.

Although if controller-manager defaults to looking up the configmap, I'd imagine the `system:kube-controller-manager` clusterrole should default to allowing configmap get's, no?

**Comment by tpepper** [comment]
This seems like it should get a Known Issue comment in the release notes for 1.12.  Can somebody please draft test and drop it in the known issues bucket issue #68840?
