### ISSUE TITLE
CRD API Group naming stricter than for aggregated apiservers 

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#68985]
While experimenting with "can we use CRDs for everything" I hit this gotcha:

`The CustomResourceDefinition "clusters.kops" is invalid: spec.group: Invalid value: "kops": should be a domain with at least one dot`

Our older API groups were single names - e.g. `autoscaling`, `kops`, etc.

I didn't see any particular reason to require a dot in the name - it looks like it might only be to nudge people towards the new-style names (?).

Is there a trick to serving a CRD with a "bare" API group name?

Or alternatively, is there a path whereby we can rename API types into a different API Group without breaking anyone?

I guess the final alternative would just be to switch off the validation check, so that we can use CRDs everywhere.  Any reason not to / objections?

cc @kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
> Any reason not to / objections?

All new API groups (even new in-tree ones) are supposed to use qualified names. Additionally, the api guidelines state "the Kubernetes project reserves use of the empty group, all single word names ("extensions", "apps"), and any group name ending in "*.k8s.io" for its sole use". Disallowing single-segment groups via CRDs is done to ensure new single segment names aren't introduced via CRD. 

For your particular use case, I assume you would need to migrate existing data? If so, I think mixing CRD and non-CRD backed APIs in a single group is a bad idea.  Even if you manage to isolate the differently-backed types into their own versions, that will tie your hands in evolving those types into versions containing one of the differently-backed types.
