### ISSUE TITLE
HPA Current utilization Unknown and Unable to fetch Metrics

### ISSUE THREAD

**Issue by yakuza-m** [kubernetes/kubernetes#68997]
/sig Autoscaling

kind bug

**What happened**:When i do kubectl describe hpa  iam getting 
 no metrics returned from resource metrics API

**How to reproduce it (as minimally and precisely as possible)**:
Install kubectl kubeadm kubelet kubernetes-cni and do a kubeadm init on Ubunt 16.04 x64
and 
Follow the steps in the link
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):NAME="Ubuntu"
                                                                 VERSION="16.04 LTS (Xenial Xerus)"

- Kernel (e.g. `uname -a`): Linux master 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ricky1993** [comment]
Have you checked your metrics server or heapster run as expected?

**Comment by yakuza-m** [comment]
> Have you checked your metrics server or heapster run as expected?

No, Can u tell me how to do that

**Comment by ricky1993** [comment]
Query your metrics server directly to see if the data return correctly.

**Comment by yakuza-m** [comment]
> Query your metrics server directly to see if the data return correctly.

when I do kubectl top node I'm getting
error: metrics not available yet

also 
the output of 

kubectl get deployment -n kube-system metrics-server -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-01T08:07:33Z
  generation: 1
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
  resourceVersion: "9507"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/metrics-server
  uid: 0d00d390-c551-11e8-990b-005056b604df
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
      name: metrics-server
    spec:
      containers:
      - image: k8s.gcr.io/metrics-server-amd64:v0.3.0
        imagePullPolicy: Always
        name: metrics-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-dir
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-01T08:07:33Z
    lastUpdateTime: 2018-10-01T08:07:33Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
