### ISSUE TITLE
misleading PLEG error on kubelet start "last seen active 2562047h47m..."

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#69007]
When the kubelet first starts the folllowing error is emitted to the logs
```
skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047h47m16.854775807s ago; threshold is 3m0s]
```
This is because the relist has not yet run which results in a duration that is just the time since the zero time instant (https://golang.org/pkg/time/#Time.IsZero)

xref https://bugzilla.redhat.com/show_bug.cgi?id=1632430

/sig node

**Comment by derekwaynecarr** [comment]
help if i approve the pr and not the issue ;-)
