### ISSUE TITLE
trouble with kubernetes-1.12.0-rc.2 tag in the bot sync'ed k8s.io/api repo

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69000]
See the following
- https://github.com/kubernetes/api/commits/kubernetes-1.12.0-rc.2/core/v1/types.go
- https://github.com/kubernetes/api/commits/master/core/v1/types.go

272a6c8a3a35653d4d011cbaf60a17c692f85e01 and b1d28a94fbfc5e0f03194884bfc2cb75c6695e1e are in master but not in kubernetes-1.12.0-rc.2

Though, to be clear, the master of k/api repo seems to be ok, just the tag in kubernetes-1.12.0-rc.2 is in the wrong spot

**Comment by dims** [comment]
cc @sttts

**Comment by nikhita** [comment]
Quick update here: The publishing bot is having problems with tagging across all repos right now (it misses a few commits). Tagging has been disabled to avoid wrong commits until the root cause is nailed down.

**Comment by tpepper** [comment]
Do we have an owner here working this in the hours @nikhita is not?

**Comment by nikhita** [comment]
> Do we have an owner here working this in the hours @nikhita is not?

@sttts :)

Pasting @sttts's reply from slack:
 
We still don't know why the tag was wrong. Unfortunately, the logs we had do not show enough information. The publishing-bot is now extended to log the information (https://github.com/kubernetes/publishing-bot/pull/114)  used to derive the right tag hashes. So next time we will be in a better position. 

In addition, removing the tag in the production publishing bot and recreating it leads to the correct commit now.

The incorrect tags are renamed as `<tag>-invalid` and `kubernetes-1.12.0-beta.2`, `kubernetes-1.12.0-rc.1`, `kubernetes-1.12.0-rc.2` have been tagged correctly.

We'll watch out for new tags and verify that they are correct. Thanks for catching this, @dims!

/close
