### ISSUE TITLE
Errors not Included in OpenAPI

### ISSUE THREAD

**Issue by lswith** [kubernetes/kubernetes#69014]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I am using the swagger api and it doesn't include the possible errors that can be returned from the api. I am generating a client, so the possible errors are necessary.

**What you expected to happen**:
Swagger allows all possible return codes to be used. These should be included in the swagger api.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by lswith** [comment]
@roycaihw @mbohlool

**Comment by roycaihw** [comment]
Hi Luke, could you be more specific on which APIs are having the problem and what errors are you expecting?

To my knowledge there was a documentation bug that our openapi spec didn't reflect the 202 path in API server delete handler. The bug was fixed in 1.12 https://github.com/kubernetes/kubernetes/pull/63418

There is also a known issue that our openapi v2 spec cannot express `OneOf` concept for our API that may return different object for same path (e.g. API server may respond with the delete object or Status on a DELETE 200 https://github.com/kubernetes/kubernetes/issues/59501)

And I'm assuming you're using the [openapi spec](https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec). The [swagger 1.2 specs](https://github.com/kubernetes/kubernetes/tree/master/api/swagger-spec) are deprecated and meant to be removed

**Comment by lswith** [comment]
I think the convention here: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#response-status-kind

> Kubernetes will always return the Status kind from any API endpoint when an error occurs.

Should be coded into the openapi spec. This is so that it can be consumed programmatically.

**Comment by roycaihw** [comment]
I see. There is a TODO in apiserver installer about adding errors to the route documentation https://github.com/kubernetes/kubernetes/blob/c4b4025ca4a29b38f5ac0baf2c2f0f241800a619/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L462-L476

Note that currently the openapi spec has the 401 Unauthorized path documented (no response schema), which is added in `OpenAPIConfig.CommonResponses`: https://github.com/kubernetes/kubernetes/blob/c4b4025ca4a29b38f5ac0baf2c2f0f241800a619/staging/src/k8s.io/apiserver/pkg/server/config.go#L382-L388

I'd like to work on the TODO. One concern is although I think it's right to document the possible paths, this change will increase the size of the openapi spec by a fair amount. Do we have any scalability/performance concern around that? @mbohlool (We may also check if CI gives any signal when a PR is submitted)

/assign

**Comment by roycaihw** [comment]
Also the api convention doc didn't reflect the 202 Accepted code that apiserver may response with. I will try update the doc when I get a chance: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#http-status-codes

**Comment by adamnovak** [comment]
I think this still needs doing.

/remove-lifecycle stale

**Comment by adamnovak** [comment]
I think this still needs doing.

/remove-lifecycle stale

**Comment by adamnovak** [comment]
Er, maybe it's:

/remove-lifecycle rotten

**Comment by adamnovak** [comment]
I don't believe that this has been fixed.

/remove-lifecycle stale

**Comment by adamnovak** [comment]
I'm tired of fighting the bot. I think this is "wontfix".

On 10/18/20, fejta-bot <notifications@github.com> wrote:
> Issues go stale after 90d of inactivity.
> Mark the issue as fresh with `/remove-lifecycle stale`.
> Stale issues rot after an additional 30d of inactivity and eventually
> close.
>
> If this issue is safe to close now please do so with `/close`.
>
> Send feedback to sig-testing, kubernetes/test-infra and/or
> [fejta](https://github.com/fejta).
> /lifecycle stale
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/69014#issuecomment-711292040


-- 
Adam Novak (He/Him)
Senior Software Engineer
Computational Genomics Lab
UC Santa Cruz Genomics Institute
"Revealing life’s code."

Personal Feedback: https://forms.gle/UXZhZc123knF65Dw5
