### ISSUE TITLE
Use http.Error() instead of writing responses directly

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#69011]
There are several places where we return errors from an HTTP server by writing the error code and message directly. We should standardize on using [http.Error ](https://golang.org/pkg/net/http/?#Error)everywhere to pick up the "text/plain" and "nosniff" content type headers.

Here's a [cs.k8s.io query](https://cs.k8s.io/?q=%5C.WriteHeader%5C\(http%5C.Status%5B%5EO%5D&i=nope&files=%5E\(pkg%7Ccmd%7Cstaging\)&repos=kubernetes/kubernetes) @tallclair gave me that probably catches most of the places where we are doing this.

The unit test ones would be nice to fix too, but the more important ones are the non-test code:
- [ ] pkg/controller/garbagecollector/dump.go
- [ ] pkg/kubectl/proxy/proxy_server.go
- [ ] pkg/kubelet/server/remotecommand/httpstream.go
- [ ] pkg/proxy/healthcheck/healthcheck.go
- [ ] staging/src/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
- [ ] staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
- [ ] staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
- [ ] staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
- [ ] staging/src/k8s.io/apiserver/pkg/server/filters/cors.go
- [ ] staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go
- [ ] staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go

**Comment by ibrasho** [comment]
Not all of these are errors. Some of them are redirects or even 1xx or 2xx codes.

**Comment by murarisumit** [comment]
Can I try working on this?

I'm contributing for the first time.

**Comment by dczombera** [comment]
I'd like to work on this if possible :)
