### ISSUE TITLE
Deprecate Node.Spec.Unschedulable when TaintNodeByCondition is GA'ed

### ISSUE THREAD

**Issue by bsalamat** [kubernetes/kubernetes#69010]
TaintNodeByCondition has replaced the existing node condition. With this feature node conditions that affect feasibility of nodes are reflected as taints on nodes. This feature is promoted to Beta in 1.12. We should deprecate node conditions once the feature is GA'ed in future releases.

- [ ] Announce deprecation of Node.Spec.Unschedulable
- [ ] Mark Node.Spec.Unschedulable as deprecated in our API
- [ ] Update our documents to note that Node.Spec.Unschedulable is deprecated

/sig scheduling
/sig node

**Comment by tianshapjq** [comment]
hi~ I am interested in this job, and commit a pr to give it a try. Would you please take a look to check if I do it right? :)

**Comment by bsalamat** [comment]
@tianshapjq Thanks for the PR, but as it is mentioned in the issue, we should deprecate Node.Spec.Unschedulable only when TaintNodeByCondition is GA. TaintNodeByCondition is beta in 1.12 and will probably not be in GA in 1.13. So, there will be some time before we can deprecate Node.Spec.Unschedulable.

**Comment by draveness** [comment]
We can't deprecate the Unschedulable field unless we have v2 node API, per discussion in https://github.com/kubernetes/kubernetes/pull/84266#issuecomment-545951881. We'll revisit this issue after that

/lifecycle frozen

**Comment by draveness** [comment]
/close

feel free to reopen this
