### ISSUE TITLE
Logs are mangled - all non-Latin characters are replaced with Unicode REPLACEMENT CHARACTER

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/kubernetes#69028]
/kind bug

**What happened**:
I want to get pod logs that should contain characters with codes above 127. Docker has no problem with them.
I try:
* `kubectl logs`
* `kubectl run --attach=true`
* curl http://localhost:8001/api/v1/namespaces/default/pods/test-binary-logs-b98b8/log/

In all cases the characters with codes above 127 are replaced with the [Unicode Replacement Character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) in UTF-8 form (\xEF \xBF \xBD)

**What you expected to happen**:
I expect the characters to be uncorrupted.

**How to reproduce it (as minimally and precisely as possible)**:

Docker works correctly:
```
$ docker run alpine sh -c 'echo -e -n \\xD4' | xxd
0000000: d4                                       .
```

Kubectl corrupts logs:
```
$ kubectl run test1 --image=alpine --restart=Never --attach=true --command -- sh -c 'echo -e -n \\xD4' | xxd
0000000: efbf bd                                  ...
```

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
local machine
- OS (e.g. from /etc/os-release):
Windows 10
- Install tools:
Docker for Windows (with Kubernetes option selected at install time)

**Comment by shanemcd** [comment]
@Ark-kun Did you ever find a workaround? If not, can you reopen?
