### ISSUE TITLE
Excess of inter node communication (pod to coredns in other node) in case of pod to external traffic

### ISSUE THREAD

**Issue by sudhiragarwal** [kubernetes/kubernetes#69025]
If the matter is security related, please disclose it privately via https://kubernetes.io/security/.
-->

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> kind bug
> /kind feature

**What happened**:
I have 3 node setup, one master node and 2 worker nodes with calico network plugin.
There are 2 coredns pods running, one in the master node and other in the worker-node-1
When i am trying to curl google.com from one of the pods in worker-node-1 (this node contains a local coredns pod), the DNS requests goes to both of the coredns pods (in master and worker-node-1) randomly. This increases the traffic flow at other interfaces like tunl0 of worker-node-1 and master node, eth0 interface of worker-node-1 and master node, etc.
Instead of this, since there is local coredns pod running in the worker-node-1, the DNS requests should go only to this coredns pod and those requests should get resolved. But, the DNS requests goes randomly to both of the coredns pods which causes unnecessary traffic flow between interfaces.

**What you expected to happen**:
The DNS requests should go only to the local coredns pod and it should be able to resolve those DNS queries.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a kubernetes setup (both the coredns pods should be in different nodes).
2) create any pod and try to curl google.com from inside of the pod.
3) collect tcpdump data at the interfaces like caliXXX interface of the pod, tunl0 interface of the worker-nodes having coredns pods, eth0 interface of the nodes having coredns pods, caliXXX interface of both the coredns pods.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: Linux
- OS (e.g. from /etc/os-release): Redhat 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools: kubeadm init
- Others:

**Comment by sudhiragarwal619** [comment]
area/dns

**Comment by sudhiragarwal619** [comment]
area/dns
