### ISSUE TITLE
Huge syscall overhead when host-image OS miss match

### ISSUE THREAD

**Issue by dskarlatos** [kubernetes/kubernetes#69034]
**What happened**:
Huge syscall performance overhead when host OS and image OS mismatch.

**What you expected to happen**:
Performance should be similar to native even if OS of image is different from host OS.

**Detailed description and benchmark**:
I'm benchmarking syscall performance inside containers on a kubernetes cluster. I wrote a simple getpid benchmark that iterates over the syscall. When the image and the host OS are similar e.g host ubuntu 16.04 and image is ubuntu 16.04 I get similar performance inside the container and on native.
Although, if I'm running the same experiment on the same host ubuntu 16.04 but with an image based on ubuntu 18.04 the performance inside the container gets a huge hit. I did some perf analysis and most of overhead comes from entry_SYSCALL_64_after_swapgs which does not show up on the when the OS of the image matches the host.

My understanding is that due to OS miss match syscalls get routed differently but I'm not sure where this is handled. Any pointers on why this is happening and how to go about fixing it, would be greatly appreciated!

I have also opened a ticket on Moby as well: [37902](https://github.com/moby/moby/issues/37902)

/kind bug
@kubernetes/sig-node-bugs

Measurements:
Native: 0.000328s
Kuberntes (host==image): 0.000350s
Kubernetes (host != image): 0.024452s

System:
Docker: 17.06.1-ce
Kubernetes: v1.11.3
OS: Ubuntu 16:04, 4.4.0-109
CPU: Intel(R) Xeon(R) CPU E5-2660 v3

Benchmark Code:

```
#define COUNT   100000
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include <unistd.h>

int main( int argc, const char* argv[] ){
    int rc;
    int i;
    int count;
    clock_t begin, end;
    count = COUNT;
    begin = clock();

    for ( i = 0; i < count; i++) {
        rc = getpid();
    }

    end = clock();
    printf("rc %d\n",rc);
    double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
    printf("Time %lf \n", time_spent);
}
```

Dockerfile:
```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y vim && apt-get install build-essential -y

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN gcc -O3 -Og -ggdb -g3 -fno-omit-frame-pointer bench.c -o myapp
ENTRYPOINT ["./myapp"]
```

Cheers,
Dimitrios

**Comment by dskarlatos** [comment]
@kubernetes/sig-node-bugs

**Comment by thaJeztah** [comment]
Looks like this is not a bug; the moby ticket was closed; copying the comment from there for easier discoverability; https://github.com/moby/moby/issues/37902#issuecomment-424804113

> Between Ubuntu 16.04 and 18.04, Glibc changed the behaviour of `getpid`. In older versions, Glibc maintained a pid cache, so it would not actually perform the syscall at all after the first time. They removed this cache as it would break some use cases, eg with the `clone` syscall. (See Linus's complaint https://yarchive.net/comp/linux/getpid_caching.html for example). So if you compile a container for Ubuntu 16.04 it only calls the `getpid` syscall once, versus every time in 18.04.

**Comment by ms4720** [comment]
@thaJeztah that was a fun read, re getpid/Linus
