### ISSUE TITLE
k8s: 1.11.3 - HPA: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: Unauthorized

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/kubernetes#69038]
/kind bug
/sig autoscaling

**What happened**:
horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: Unauthorized
```
NAME             REFERENCE                   TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
app01-1400-uat   Deployment/app01-1400-uat   <unknown>/85%   3         3         3          26m

```
**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl describe hpa app001-1400-uat -n=uat
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: **v1.11.3**
- Cloud provider or hardware configuration: **hardware**
- OS (e.g. from /etc/os-release): **CentOS Linux release 7.5**
- Kernel (e.g. `uname -a`): **4.1.12-124.17.2.el7uek.x86_64**

**Comment by bhavin192** [comment]
Hey @gabrielfsousa are you able to see the CPU utilization with `kubectl top pods`
