### ISSUE TITLE
kubectl wait fails for jobs with metadata.generateName

### ISSUE THREAD

**Issue by markusheiden** [kubernetes/kubernetes#69039]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I created a job with metadata.generateName twice and waited for completion, but got:

    panic: interface conversion: runtime.Object is *unstructured.UnstructuredList, not *unstructured.Unstructured

**What you expected to happen**:

kubectl to wait for the last job to complete.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl create -f job.yaml
    kubectl create -f job.yaml
    kubectl wait --for=condition=complete -f job.yaml

job.yaml (shortened):

    apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: my-job-

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by markusheiden** [comment]
@kubernetes/sig-scheduling-bugs I have to choose a sig, but I am not sure which one is right...

**Comment by CaoShuFeng** [comment]
kubectl get -f job.yaml also doesn't work as expected.
