### ISSUE TITLE
Published k8s.io/client-go modules give `checksum mismatch` when downloaded in different GOOS

### ISSUE THREAD

**Issue by sgnn7** [kubernetes/kubernetes#69040]
Published k8s.io Go modules have mismatching between `darwin` and `linux` GOOS. **As far as I can tell (though I could be wrong), this is not a Golang issue**.

### Version of Go:
Host: `go version go1.11 darwin/amd64`
Container: `go version go1.11 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Host:
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

Container:
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

### What did you do?
On Host (darwin):
```bash
$ # Create a blank project with client-go as a dependency

$ mkdir /tmp/foo && cd /tmp/foo
$ go mod init foo.com
go: creating new go.mod: module foo.com
$ go mod get k8s.io/client-go@kubernetes-1.11.3                                                                                                                                                                                        
go: finding k8s.io/client-go kubernetes-1.11.3
```

Edit `main.go` and replace it with:
```go
package main

import (
        "fmt"
        "k8s.io/client-go/kubernetes"
)

func main() {
        fmt.Println("kubernetes")
}
```

Build this code in a clean container:
```bash
$ docker run -it --rm -v $(pwd):/foo golang:1.11-stretch bash -c 'cd /foo && go mod download'
go: finding k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible
go: verifying k8s.io/client-go@v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible: checksum mismatch
        downloaded: h1:OtFD+1WyykBlQ980RTvPQCDP2xMmKWL9h+onvblGVR0=
        go.sum:     h1:QLQHmQOEaw8l7ejFP28erp2Tt8upF1zPLrh4cQNatuE=
```

### What did you expect to see?
No checksum errors

### What did you see instead?
`checksum mismatch` error

### Additional info
It's possible this is an issue in Go itself but here looks more likely. I've narrowed this down to a mismatch in built module's version string. The darwin version of shorthash is 8 characters and the linux one is 7 characters. When I compared the two downloaded versions, this was the only difference:
```diff
root@79d169a9ec19:/tmp/client-go# git diff
diff --git a/pkg/version/base.go b/pkg/version/base.go
index 6ac679b..2071a37 100644
--- a/pkg/version/base.go
+++ b/pkg/version/base.go
@@ -55,7 +55,7 @@ var (
        // NOTE: The $Format strings are replaced during 'git archive' thanks to the
        // companion .gitattributes file containing 'export-subst' in this same
        // directory.  See also https://git-scm.com/docs/gitattributes
-       gitVersion   string = "v0.0.0-master+2cefa64f"
+       gitVersion   string = "v0.0.0-master+2cefa64"
        gitCommit    string = "2cefa64ff137e128daeddbd1775cd775708a05bf" // sha1 from git, output of $(git rev-parse HEAD)
        gitTreeState string = ""            // state of git tree, either "clean" or "dirty"
```

The code that makes this happen is at https://github.com/kubernetes/client-go/blob/03bfb9bdcfe5482795b999f39ca3ed9ad42ce5bb/pkg/version/base.go#L58
```golang
	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
	// companion .gitattributes file containing 'export-subst' in this same
	// directory.  See also https://git-scm.com/docs/gitattributes
	gitVersion   string = "v0.0.0-master+$Format:%h$"
```

My best guess it's that it is some code in this file that's not evaluating the same on these platforms: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh

/kind bug
/sig api-machinery

**Comment by dims** [comment]
Looks like git behavior - https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892

and other folks are running into it too https://github.com/warner/python-versioneer/issues/156

**Comment by jharshman** [comment]
I'm getting this behavior on the same GOOS jumping from my work laptop to my personal.
https://github.com/golang/go/issues/27925

**Comment by rjosephwright** [comment]
This happened for me using the `golang:1.11` image. Seems to have happened after `1.11` switched from `1.11.1` to `1.11.2`. Pinning my image to `golang:1.11.1` solved it.

**Comment by glyn** [comment]
Hit the same problem in Windows running go 1.11.2 but the problem persisted when I backed off to go 1.11. The project in question was originally built on darwin.

`go clean -modcache` failed with the same checksum mismatch.

**Comment by igmor** [comment]
Folks, anecdotally we were able to fix a similar issue with using  a particular GO version: golang:1.11.1

**Comment by nezorflame** [comment]
Can this be related to https://github.com/golang/go/issues/29278?

**Comment by sgnn7** [comment]
Just as a heads up, the newest Golang (v1.11.4) [generates different checksums](https://github.com/golang/go/issues/29278) from older versions (`<=v1.11.3`) which may make it seem like other packages have this issue but this particular bug is independent of that (afaict).

`go get k8s.io/client-go@kubernetes-1.11.3` on darwin with `v1.11.4`:
```
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible h1:QLQHmQOEaw8l7ejFP28erp2Tt8upF1zPLrh4cQNatuE=
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible/go.mod h1:7vJpHMYJwNQCWgzmNV+VYUl1zCObLyodBc8nIyt8L5s=
```

`go get k8s.io/client-go@kubernetes-1.11.3` on linux with `v1.11.4`:
```
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible h1:Ch3wIkSY4QNrqRAJqgQIIpwqaCi7bbiIP23BAV9Qq/U=
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible/go.mod h1:7vJpHMYJwNQCWgzmNV+VYUl1zCObLyodBc8nIyt8L5s=
```

**Comment by sgnn7** [comment]
Actually, it seems that after cleaning the darwin cache, the checksum is correct!!

🎉 

**After running `go clean -modcache`**

`go get k8s.io/client-go@kubernetes-1.11.3` on darwin with `v1.11.4`:
```
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible h1:Ch3wIkSY4QNrqRAJqgQIIpwqaCi7bbiIP23BAV9Qq/U=
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible/go.mod h1:7vJpHMYJwNQCWgzmNV+VYUl1zCObLyodBc8nIyt8L5s=
k8s.io/client-go v10.0.0+incompatible h1:F1IqCqw7oMBzDkqlcBymRq1450wD0eNqLE9jzUrIi34=
```

`go get k8s.io/client-go@kubernetes-1.11.3` on linux with `v1.11.4`:
```
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible h1:Ch3wIkSY4QNrqRAJqgQIIpwqaCi7bbiIP23BAV9Qq/U=
k8s.io/client-go v2.0.0-alpha.0.0.20180910083459-2cefa64ff137+incompatible/go.mod h1:7vJpHMYJwNQCWgzmNV+VYUl1zCObLyodBc8nIyt8L5s=
k8s.io/client-go v10.0.0+incompatible h1:F1IqCqw7oMBzDkqlcBymRq1450wD0eNqLE9jzUrIi34=
```
```

**Comment by liggitt** [comment]
/close

resolved in golang
