### ISSUE TITLE
Is there a way to validate the container's "env" section matches the image requirements?

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#6904]
Each container definition in a pod might have an "env" section for env variables.
Is there some way to validate on pod creation that the env variables defined are actually the ones required by that image?
there might be a typo, or a missing env which can cause the image to fail starting.

related to:
https://github.com/openshift/origin/pull/1761

**Comment by erictune** [comment]
I didn't think the list of vars in a Dockerfile ENV section was meant to be an exhaustive list of env vars supported by the programs in the image.

**Comment by abonas** [comment]
@erictune it is at least partially related according to my understanding.
there could be of course vars that are requested directly in the code...

**Comment by mnagy** [comment]
Maybe we could specify required env variables as metadata (using LABEL)?

**Comment by molszanski** [comment]
It looks more like a bootstrap / setup phase need. 
I think that ENV like metadata should come up in a some sort of CLI output / WebUI. 
And that might cover many missed env variables scenarios. 

And even if find a mismatch / typo what should be an expected outcome? CLI warning?

**Comment by smarterclayton** [comment]
I think it's unlikely we will ever adding anything like this, given our current direction.  Closing as the remit of higher level tools.
