### ISSUE TITLE
Give master/node specific IP address

### ISSUE THREAD

**Issue by huawenli** [kubernetes/kubernetes#69048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
I have two VMs, VM1 will act as master and VM2 as node. Each VM has two interfaces, enp0s3 as NAT and DHCP with 10.0.2.15/24 by system for both VMs, enp0s8 as host-only adapter static with 192.168.56.110 and 192.168.56.117 for VM1 and VM2, 
at the time 'kubeadm init', 'kubeadm init --kubernetes-version=192.168.56.110 --pod-network-cidr=192.168.0.0/16 --kubernetes-version=1.11.1' is run, kubelet uses default settings without any change. No error reported here.
network plugin installation was smooth also.
In node running 'kubeadm join' command with the token, no error happened.
by now everything seemed good.

Issue came now,
There are two calico-node pods, one run on master and one on node, showed below, The one in node always failed due to connection refused to readiness port.
The root cause seems both master and node taking IP address from first available interface, enp0s3 in my environment and those pods get the address from host.

[root@centos7b2 ~]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE       IP              NODE
...
kube-system   calico-node-7jlgj                          2/2       Running            6          20h       10.0.2.15       centos7b2
kube-system   calico-node-plc4j                          1/2       CrashLoopBackOff   62         20h       10.0.2.15       centos7g2

[root@centos7b2 ~]# kubectl describe pod -n kube-system calico-node-plc4j
  Warning  Unhealthy         3m (x2 over 3m)      kubelet, centos7g2  Readiness probe failed: Get http://10.0.2.15:9099/readiness: dial tcp 10.0.2.15:9099: connect: connection refused
  Warning  BackOff           3m (x3 over 3m)      kubelet, centos7g2  Back-off restarting failed container
  Warning  DNSConfigForming  3m (x10 over 3m)     kubelet, centos7g2  Nameserver limits were exceeded, some nameservers have been omitte

[root@centos7b2 ~]# kubectl describe nodes centos7b2
Name:               centos7b2
Roles:              master
...
Addresses:
  InternalIP:  10.0.2.15
  Hostname:    centos7b2

[root@centos7b2 ~]# kubectl describe nodes centos7g2
Name:               centos7g2
Roles:              node
...
Addresses:
  InternalIP:  10.0.2.15
  Hostname:    centos7g2

**What you expected to happen**:
Give master and node correct IP address, in this case it should be 192.168.56.110 and 192.168.56.117 from VMs' host-only adapter.

**How to reproduce it (as minimally and precisely as possible)**:
any settings have two interfaces or more can reproduce it with kubeadm init and kubelet with default settings.

**Anything else we need to know?**:
I have tried suggestion to add 'Environment="KUBELET_EXTRA_ARGS=--hostname-override=10.0.0.20 --node-ip=192.168.56.110"' to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf, which is suggested by several issue reports, then running systemctl daemon-reload and systemctl restart kubelet, but without luck to make it works.
Similar issue reported by https://github.com/kubernetes/kubernetes/issues/33618, suggestion was tried without luck.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: VMs
- OS (e.g. from /etc/os-release): CentOS7
- Kernel (e.g. `uname -a`): Linux centos7b2 3.10.0-862.11.6.el7.x86_64
- Install tools: kubeadm
- Others:

**Comment by HaveFun83** [comment]
We see the same issue:
Node IP is 10.6.10.5 from eth2 but the liveness and readiness probes use the ip from eth1 10.5.10.5 which can not reach the pod ip
k8s 1.10.2 with calico as network plugin
