### ISSUE TITLE
PortForwarder.GetPorts does not return correct port number when local port omitted or set to zero.

### ISSUE THREAD

**Issue by mtaylor91** [kubernetes/kubernetes#69052]
/kind bug

Hey guys,

I came across the new code on master to return the list of forwarded ports (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L349).

After doing some testing, I discovered that this function does not return the correct port if the local port is specified as '0' or left unspecified.

This seems to be because the port reference passed in to portforwarder.listenOnPort is a copy of the ForwardedPort struct, and not the actual ForwardedPort owned by the PortForwarder (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L155).

Environment:
- Kubernetes version (use `kubectl version`): git master
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): client-go running on Darwin
- Kernel (e.g. `uname -a`): Darwin aarora-w10vm.internal.synopsys.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- Install tools: n/a
- Others: n/a

**Comment by mtaylor91** [comment]
/sig cli
(I think - the issue is in the go client, not so much the CLI; but there is no client SIG, so... ¯\_(ツ)_/¯)

**Comment by atavakoli** [comment]
This is due to the value in ranges being copies rather than references.

I was able to fix this locally by changing the 3 lines starting at [client-go/tools/portforward/portforward.go#200](https://github.com/kubernetes/kubernetes/blob/409bfc4337f34ed119e66cb6cdd8f95e5deea5a1/staging/src/k8s.io/client-go/tools/portforward/portforward.go#L200) from:

```go
    for _, port := range pf.ports {
        err = pf.listenOnPort(&port)
```

to

```go
    for i, _ := range pf.ports {
        port := &pf.ports[i]
        err = pf.listenOnPort(port)
```

I'm happy to submit a PR.

**Comment by atavakoli** [comment]
It looks like @mtaylor91 already did this, but it was closed before being accepted because of CLA issues.

**Comment by wfernandes** [comment]
So has this issue been addressed in a different fix?

**Comment by atavakoliyext** [comment]
@wfernandes [It appears so](https://github.com/kubernetes/client-go/commit/e70639fd33a0e7d16a1f1c82379061ef7aa375b3).
