### ISSUE TITLE
New github labels

### ISSUE THREAD

**Issue by alpe** [kubernetes/kubernetes#6905]
Levels like beginner, advanced, expert, etc would make it easier to pick the right issues to contribute. This would work well with the `status/help-wanted` label.

**Comment by erictune** [comment]
For the most part, issues with status/help-wanted should be more to the beginner side of things.  

If you see a status/help-wanted issue, or any issue, that looks interesting, feel free to comment on it and one of the core contributors would be happy to give an assessment of difficulty, and pointers, if you want. 

The other thing we suggest for new contributors is to just start reading code and you will probably find something that can be improved within a few hours.
