### ISSUE TITLE
Better handle container in unknown state in kubelet.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#69060]
Container runtime sometimes return [unknown state](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L779) for containers in bad state, e.g. https://github.com/containerd/cri/pull/924 containerd returns `unknown` state if an error occurs when loading container state during restart.

However, this doesn't necessarily mean that the container is stopped. If kubelet blindly starts the new container in that case, it may break the node if the container can only have one instance on the node, e.g. kube-proxy.

To make it safe, kubelet should try to stop the container in unknown state. Based on CRI definition, [container stop should be idempotent](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L51), so:
* If the container is running, kubelet can stop it;
* If the container is not running, the stop won't return error;
* If the container is running, but can't be stopped for some reason, returning error and failing loudly is still better than silently start the new container and keep the old one running.

/cc @yujuhong @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
Note: docker sometimes report "dead" containers. We may need to handle this differently in dockershim, e.g., simply translate those to exited.

**Comment by feiskyer** [comment]
+1 to stop the unknown container first before creating a new one.

**Comment by Random-Liu** [comment]
Mark this 1.14. We plan to address this bug in 1.14.
