### ISSUE TITLE
Controller-Manager uses in-cluster token when `--kubeconfig` is specified in  v1.12.0-rc.2 

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#69093]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

We run Kubernetes in Kubernetes, AKA the control plane components run as pods, having their apiserver address and auth specified via `--kubeconfig kubeconfigfile`.

Testing this with ` v1.12.0-rc.2` results in the controller-manager crashlooping with a

```
"system:serviceaccount:cluster-fc2kf4899r:default" cannot get configmaps in the namespace "kube-system": Unknown user "system:serviceaccount:cluster-fc2kf4899r:default"
```

error. That user however stems from the token of the default service account mounted in the pod. The apiservers address and cacert seem to be right, as otherwise the account would exist/cacert verification would fail.

Disabling the token mount by setting `automountServiceAccountToken` to false on the default service account token fixes the issue.

**What you expected to happen**:

The controller manager not trying to use the in-cluster `ServiceAccountToken` when it gets passed a `--kubeconfig` arg pointing to a valid kubeconfig containing client cert and key

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

* This only happens for the controller-manager, e.G. scheduler works fine

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
@alvaroaleman please see https://github.com/kubernetes/kubernetes/pull/69062 and https://github.com/kubernetes/kubernetes/issues/68986 

could this be a duplicate of that issue/pr in progress? (if so, please try `--authentication-skip-lookup`)

**Comment by alvaroaleman** [comment]
@dims Yes, adding `--authentication-skip-lookup` fixes the issue, seems like the controller-manager falls back to using the token if it gets an access denied before.

Thanks for the hint, i'll watch the linked issue!
