### ISSUE TITLE
Multi-architecture fat manifest for kubernetes ecosystem

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#69098]
This issue is for pushing multi-architecture fat manifest images for kubernetes ecosystem

- [ ] [kubernetes/dashboard](https://github.com/kubernetes/dashboard)
- [ ] [kubernetes/node-problem-detector](https://github.com/kubernetes/node-problem-detector)
- [ ] [kubernetes-incubator/metrics-server](https://github.com/kubernetes-incubator/metrics-server)
- [ ] [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx)
- [ ] [k8s.gcr.io/kube-addon-manager](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager)

**Comment by chrisohaver** [comment]
@fabriziopandini , CoreDNS images are already multi-arch.

**Comment by chrisohaver** [comment]
> @fabriziopandini , CoreDNS images are already multi-arch.

Ah, excluding Windows ...

**Comment by neolit123** [comment]
multi-arch != multi-platform

**Comment by chrisohaver** [comment]
OK, CoreDNS image manifests lists currently include amd64, arm, arm64, ppc64le, and s390x.

**Comment by chrisohaver** [comment]
cc @daschott

**Comment by mkumatag** [comment]
Adding `k8s.gcr.io/kube-addon-manager`
