### ISSUE TITLE
kube-controller-manager cannot start with authentication

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [kubernetes/kubernetes#69096]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
I tried to use https secure connections with authentication for kube-controller-manager but no luck. Connection is secured but without authentication, in logs i get 
```
W0926 13:07:03.339290      44 authentication.go:55] Authentication is disabled
```
Not sure how i can enable authentication, maybe i miss something

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
static pod manifest for kubecontroller manager have this commands for container
```
  - command:
    - kube-controller-manager
    - --bind-address=0.0.0.0
    - --horizontal-pod-autoscaler-sync-period=10s
    - --horizontal-pod-autoscaler-use-rest-clients=true
    - --node-monitor-grace-period=20s
    - --port=0
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --secure-port=10352
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --use-service-account-credentials=true
    - --address=127.0.0.1
    - --allocate-node-cidrs=true
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: Digital Ocean
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux dlukyanhcikov-upgradek8s-dev-01 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: ansible
- Others: static pods are generated thru kubeadm using masterconfiguration config file

**Comment by cheftako** [comment]
"authentication.go:55] Authentication is disabled" is emitted when the AuthenticationInfo.Authenticator is nil. However there are many things which can cause the authenticator to be nil. Can you bump up log verbosity (--v=4) and see if any errors appear? I'm guessing it will be something like "failed to generate self-signed certificate". I was able to get the KCM to come up and listen on the secure port with the flags you used, so I'm guessing its an environment specific issue.
