### ISSUE TITLE
RFE: E2Es: UID Label all things

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#69107]
**Is this a FEATURE REQUEST?**:
Add the ability to auto label all the sub-resources to have a global cleanup mechanism using label selectors. 

**What happened**:
Sub-resources can sometimes be stuck in terminating at the end of an e2e conformance run. 

**What you expected to happen**:
Cleanup all the things. 

**How to reproduce it (as minimally and precisely as possible)**:
Re-run tests or terminate mid run until you get resource leaks, or failed cleanup

/cc @kubernetes/sig-testing @kubernetes/cncf-conformance-wg 
/kind feature

**Comment by timothysc** [comment]
xref: https://github.com/heptio/sonobuoy/issues/531

**Comment by dims** [comment]
@brahmaroutu @duglin @bradtopol - Is there someone who can help with this task?

**Comment by brahmaroutu** [comment]
@timothysc Can you provide more details on how to solve the issue, I would like to help.
