### ISSUE TITLE
k8s does not work after renewing cloud provider aadClientSecret

### ISSUE THREAD

**Issue by ITler** [kubernetes/kubernetes#69100]
**Is this a BUG REPORT or FEATURE REQUEST?**: not sure, maybe a help request or feature request for providing documentation for specific use-case

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
My cloud provider's (Azure) service principal's credentials were expired, so k8s is not able to perform actions anymore (e.g. binding persistent volumes).
What I did already:

1. Renew credentials for service principal... verified working
2. Put new password aka. `aadClientSecret` to /etc/kubernetes/azure.json which is referenced for `--cloud-config` parameter
3. Restarted kubelet service on masters and agents
4. Manually deleted in namespace `kube-system`: 
- secret `default-token`
- pod kube-apiserver
- pod kube-controller
- pod kube-scheduler
- pod kube-proxy
5. Deleted and reapplied persistent volume claim

This does **not** work. Still showing `401`, :

```
Failed to provision volume with StorageClass "elastic-storage": azure.BearerAuthorizer#WithAuthorization: 
Failed to refresh the Token for request to https://management.microsoftazure.de/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/REDACTED/providers/Microsoft.Compute/disks/REDACTED1-dynamic-pv00000000-0000-0000-0000-000000000000-0017fa102acb?api-version=2016-04-30-preview: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 00000000-0000-0000-0000-000000000000\r\nCorrelation ID: 00000000-0000-0000-0000-000000000000\r\nTimestamp: 2018-09-26 14:01:21Z","error_codes":[70002,50012],"timestamp":"2018-09-26 14:01:21Z","trace_id":"00000000-0000-0000-0000-000000000000","correlation_id":"00000000-0000-0000-0000-000000000000"}
```

My question to be (urgently) answered, is:
***What is the procedure to make kubernetes use the newly provided credentials for accessing cloud provider?*** I didn't find a documentation. 

**What you expected to happen**:
Kubernetes should be able to utilise cloud platform features again

**How to reproduce it (as minimally and precisely as possible)**:
Invalidate cloud providers credentials and try to deploy a persistent volume

**Anything else we need to know?**:
There were no further configuration changes to kubernetes cluster and it worked before. The only change was expiring credentials

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: Azure Germancloud
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
- Install tools: `acs-engine`
- Others:

**Comment by ITler** [comment]
@kubernetes/sig-auth-misc

**Comment by ITler** [comment]
After some more digging through the internet, I found out by accident:

```
on master node:
docker restart $(docker ps  -q)
```

This solved it form me.

**Comment by andyzhangx** [comment]
and also you should restart kubelet on agent nodes:
```
sudo systemctl restart kubelet
```
