### ISSUE TITLE
`system:csi-external-provisioner` role missing secret fetch access

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#69122]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

Kubernetes defines a set of pre-defined roles that some external components use. For example, it defines the `ClusterRole` `system:csi-external-provisioner` used by https://github.com/kubernetes-csi/external-provisioner

Although `csi-external-provisioner` and `csi-external-attacher` are now capable of fetching secrets (on behalf of CSI drivers), but the predefined `ClusterRoles` `system:csi-external-provisioner` and `system:csi-external-attacher` have not been updated to reflect that, so users encounter errors like:

```
Failed to provision volume for claim "default/csi-vlsdisk-test-pvc-101" with StorageClass "sc1": error getting secret sc1 in namespace default: secrets "sc1" is forbidden: User "system:serviceaccount:default:csi-controller-sa" cannot get secrets in the namespace "default": Unknown user "system:serviceaccount:default:csi-controller-sa"
```

**What you expected to happen**:
The pre-defined roles should include secret permissions.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig storage
/milestone v1.13

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by saad-ali** [comment]
> The pre-defined roles should include secret permissions.

Not all CSI drivers require permission to secrets, so modifying the default to allow secret read access may not be desirable. 

There is also an effort underway (see https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-423636593) to remove the pre-defined roles for external components and move them to manifest files hosted in the external component's external repo. The fix for this will depend on that.

**Comment by shubheksha** [comment]
ping @saad-ali - is this on track for 1.13? Is anyone working on it?

**Comment by AishSundar** [comment]
@saad-ali is this still in scope for 1.13? I dont see any associated PR(s) here. Can you please give an appropriate priority/ label for this issue 

We are nearing code slush for 1.13 next Friday 11/9 and Code freeze in 2 weeks. If you think this issue isn't critical for 1.13 and work might extend beyond code slush please work with Niko Pen to move this out. thanks

**Comment by msau42** [comment]
I think we should address this after https://github.com/kubernetes/kubernetes/issues/69379 (and it can be done out of tree)

**Comment by AishSundar** [comment]
@msau42 can you give it an appropriate priority/ please. thanks

**Comment by msau42** [comment]
Since I think the work for this will be done out of tree, we should not need to track it with kubernetes core.  I've opened up these issues for out of tree:
https://github.com/kubernetes-csi/external-attacher/issues/88
https://github.com/kubernetes-csi/external-provisioner/issues/164

/close
