### ISSUE TITLE
Build fails with development version of go

### ISSUE THREAD

**Issue by rjammala** [kubernetes/kubernetes#6913]
kubernetes]$ make
hack/build-go.sh 

Detected go version: go version devel +122384e Wed Mar 4 20:55:55 2015 +0000 linux/amd64.Kubernetes requires go version 1.2 or greater.Please install Go version 1.2 or later.

!!! Error in /home/rjammalamadaka/kubernetes/hack/lib/golang.sh:359
  'kube::golang::build_binaries "$@"' exited with status 2
Call stack:
  1: /home/rjammalamadaka/kubernetes/hack/lib/golang.sh:359 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
make: *** [all] Error 1

**Comment by jcajka** [comment]
Hello, it would be really nice feature to have and it seems easy to fix/implement. Are there any plans on fixing the build?
