### ISSUE TITLE
Move pkg/scheduler/algorithm/well_known_labels.go out

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#69138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind cleanup
/sig scheduling

**Description**:

It's better to move `pkg/scheduler/algorithm/well_known_labels.go` to `pkg/scheduler/api/` to avoid dependency cycle.  for example, `pkg/scheduler/algorithm/types.go` includes `schedulercache` which may also dependent on other pkgs.

Should be part of #68951 .

**Comment by tanshanshan** [comment]
Could you assign it to me?
