### ISSUE TITLE
Panic in `kubectl status`

### ISSUE THREAD

**Issue by praveensripati** [kubernetes/kubernetes#69144]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Running k8s on VirtualBox. Installation was done using kubeadm.

1) Created a deployment
k run nginx --image=nginx -r=2 --restart=Always

2) Ran `kubecl rollout undo` and there was a panic.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x132f4ba]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.(*UndoOptions).RunUndo(0xc4200e6240, 0xc420833c40, 0x0)
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_undo.go:137 +0x2a
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.NewCmdRolloutUndo.func1(0xc420863400, 0x24f04f8, 0x0, 0x0)
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_undo.go:92 +0xb6
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420863400, 0x24f04f8, 0x0, 0x0, 0xc420863400, 0x24f04f8)
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203cc780, 0xc420038bd0, 0x12a05f200, 0xc420833ee8)
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203cc780, 0x186ad10, 0x24d1ae0)
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /workspace/anago-v1.12.0-beta.2.73+3e4aee86dfaf93/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```
**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment and do a `kubectl rollout undo` to get the panic.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
 
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux praveen-ubuntu 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by Pingan2017** [comment]
@praveensripati see `kubectl rollout undo -h`
