### ISSUE TITLE
Unable to decode an event from the watch stream: stream error

### ISSUE THREAD

**Issue by garethmorris78** [kubernetes/kubernetes#69147]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:

Getting the following errors for cert-manager and nginx-ingress controller containers. 

```
E0927 10:40:02.235878       8 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 561; INTERNAL_ERROR
E0927 10:40:02.235979       8 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 559; INTERNAL_ERROR
E0927 10:45:46.946117       8 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 757; INTERNAL_ERROR
E0927 10:50:03.071794       8 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 905; INTERNAL_ERROR
E0927 10:50:03.751127       8 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 907; INTERNAL_ERROR
```
Error message  is flooding the logs but cert-manager and ngnix appear to be operating normally. 

No other errors in the log before or after the above. No errors in kubelet logs either for the node hosting the containers. 

**What you expected to happen**:
No errors in the log

**How to reproduce it (as minimally and precisely as possible)**:
Install latest cert-manager and nginx ingress releases via stable helm charts.

**Anything else we need to know?**:
nginx ingress, cert-manager and external-dns all installed in the same namespace.  Recreating pods does not fix this issue. 

RBAC is enabled on the cluster 

**Environment**:
- Kubernetes version (use `kubectl version`):1.11.2
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dberuben** [comment]
#66153

**Comment by garethmorris78** [comment]
known issue with AKS 
#https://github.com/Azure/AKS/issues/676
