### ISSUE TITLE
[Mac OS/docker-machine] Could not connect to rsync container. See build/README.md for setting up remote Docker engine

### ISSUE THREAD

**Issue by lovejoy** [kubernetes/kubernetes#69142]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I found 
https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L678,L684
This code try to rsync files  to 127.0.0.1 mapped_port or container_ip  KUBE_CONTAINER_RSYNC_PORT but this two port can't be access from local mac environment when we use docker-machine : the mapped_port is bind to inside docker-machine eth0 (can't access outside docker-machine ,my code is on my mac,not inside the docker-machine), and the container_ip also can't be access directly outside docker-machine.
So I do a hack like this
```
diff --git a/build/common.sh b/build/common.sh
index 6ace6a06a5..fc73d771be 100755
--- a/build/common.sh
+++ b/build/common.sh
@@ -657,8 +657,8 @@ function kube::build::start_rsyncd_container() {
   kube::build::stop_rsyncd_container
   V=3 kube::log::status "Starting rsyncd container"
   kube::build::run_build_command_ex \
-    "${KUBE_RSYNC_CONTAINER_NAME}" -p 127.0.0.1:${KUBE_RSYNC_PORT}:${KUBE_CONTAINER_RSYNC_PORT} -d \
-    -e ALLOW_HOST="$(${IPTOOL} | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')" \
+    "${KUBE_RSYNC_CONTAINER_NAME}" -p 0.0.0.0:${KUBE_RSYNC_PORT}:${KUBE_CONTAINER_RSYNC_PORT} -d \
+    -e ALLOW_HOST="$(${IPTOOL} | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | tr '\n' ' ')  " \
     -- /rsyncd.sh >/dev/null
 
   local mapped_port
@@ -675,8 +675,8 @@ function kube::build::start_rsyncd_container() {
   # machines) we have to talk directly to the container IP.  There is no one
   # strategy that works in all cases so we test to figure out which situation we
   # are in.
-  if kube::build::rsync_probe 127.0.0.1 ${mapped_port}; then
-    KUBE_RSYNC_ADDR="127.0.0.1:${mapped_port}"
+  if kube::build::rsync_probe $(docker-machine ip) ${mapped_port}; then
+    KUBE_RSYNC_ADDR="$(docker-machine ip):${mapped_port}"
     return 0
   elif kube::build::rsync_probe "${container_ip}" ${KUBE_CONTAINER_RSYNC_PORT}; then
     KUBE_RSYNC_ADDR="${container_ip}:${KUBE_CONTAINER_RSYNC_PORT}"
```

Note need `tr '\n' ' '` to ALLOW_HOST as `ifconfig | grep xxx ` product two ip : Mac's ip and docker-machine's ip

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by psweetma** [comment]
Hi @lovejoy , I've just experience this same issue but I see this issue was closed. Did you, by any chance, find another solution to the problem, one that doesn't involve the patching `build/common.sh`?
