### ISSUE TITLE
Pod sandbox creation appears to be unstable under Windows in 1.11.3.

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#69165]
/kind bug
/sig Azure
/sig Network

**What happened**:

During Pod creation, this happens frequently:

Events:
  Type     Reason                  Age               From                   Message
  ----     ------                  ----              ----                   -------
  Normal   Scheduled               2m                default-scheduler      Successfully assigned default/powerflowserver-f8d7887f9-9rsf4 to 26207k8s9000
  Warning  FailedCreatePodSandBox  2m                kubelet, 26207k8s9000  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "5cc13c9870216921b5060acf6d37283ee2dd411d44fe3e618c5bbee27c7b5c50" network for pod "powerflowserver-f8d7887f9-9rsf4": NetworkPlugin cni failed to set up pod "powerflowserver-f8d7887f9-9rsf4_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "5cc13c9870216921b5060acf6d37283ee2dd411d44fe3e618c5bbee27c7b5c50" network for pod "powerflowserver-f8d7887f9-9rsf4": NetworkPlugin cni failed to teardown pod "powerflowserver-f8d7887f9-9rsf4_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]
  Normal   SandboxChanged          4s (x10 over 2m)  kubelet, 26207k8s9000  Pod sandbox changed, it will be killed and re-created.

**What you expected to happen**:

Clean, reliable Pod production.

**How to reproduce it (as minimally and precisely as possible)**:

As far as I can tell, this is as simple as trying to allocate a trivial Windows container 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
PS D:\git\PowerFlow\scripts\tmp> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Azure Container Engine

- OS (e.g. from /etc/os-release):

NAME                    STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION   CONTAINER-RUNTIME
26207k8s9000            Ready     agent     16h       v1.11.3   <none>        Windows Server Datacenter   10.0.17134.285
                        docker://17.6.2
26207k8s9001            Ready     agent     16h       v1.11.3   <none>    Windows Server Datacenter   10.0.17134.285
                        docker://17.6.2

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

PS D:\git\PowerFlow\scripts\tmp> kubectl describe node/26207k8s9000
Name:               26207k8s9000
Roles:              agent
Labels:             agentpool=windowspool2
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=westus2
                    failure-domain.beta.kubernetes.io/zone=1
                    kubernetes.azure.com/cluster=ClarityOrDie15RG
                    kubernetes.io/hostname=26207k8s9000
                    kubernetes.io/role=agent
                    storageprofile=managed
                    storagetier=Standard_LRS
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp:  Wed, 26 Sep 2018 18:53:50 -0700
Taints:             <none>
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Thu, 27 Sep 2018 11:06:16 -0700   Thu, 27 Sep 2018 10:54:54 -0700   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Thu, 27 Sep 2018 11:06:16 -0700   Thu, 27 Sep 2018 10:54:54 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 27 Sep 2018 11:06:16 -0700   Thu, 27 Sep 2018 10:54:54 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 27 Sep 2018 11:06:16 -0700   Wed, 26 Sep 2018 18:53:50 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 27 Sep 2018 11:06:16 -0700   Thu, 27 Sep 2018 10:54:54 -0700   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.240.0.4
  Hostname:    26207k8s9000
Capacity:
 cpu:                2
 ephemeral-storage:  0
 memory:             8388148Ki
 pods:               30
Allocatable:
 cpu:                2
 ephemeral-storage:  0
 memory:             8388148Ki
 pods:               30
System Info:
 Machine ID:      26207k8s9000
 System UUID:
 Boot ID:
 Kernel Version:  10.0.17134.285

 OS Image:                   Windows Server Datacenter
 Operating System:           windows
 Architecture:               amd64
 Container Runtime Version:  docker://17.6.2
 Kubelet Version:            v1.11.3
 Kube-Proxy Version:         v1.11.3
ExternalID:                  26207k8s9000
ProviderID:                  azure:///subscriptions/ac60e4d8-966a-42ed-bad4-2bc5bf6ece8f/resourceGroups/ClarityOrDie15RG/providers/Microsoft.Compute/virtualMachines/26207k8s9000
Non-terminated Pods:         (1 in total)
  Namespace                  Name                               CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                               ------------  ----------  ---------------  -------------
  default                    powerflowserver-f8d7887f9-9rsf4    0 (0%)        0 (0%)      0 (0%)           0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  0 (0%)        0 (0%)      0 (0%)           0 (0%)
Events:
  Type    Reason                   Age                From                      Message
  ----    ------                   ----               ----                      -------
  Normal  Starting                 21m                kube-proxy, 26207k8s9000  Starting kube-proxy.
  Normal  Starting                 12m                kube-proxy, 26207k8s9000  Starting kube-proxy.
  Normal  Starting                 11m                kubelet, 26207k8s9000     Starting kubelet.
  Normal  NodeHasSufficientMemory  11m (x2 over 11m)  kubelet, 26207k8s9000     Node 26207k8s9000 status is now: NodeHasNoDiskPressure
  Normal  NodeReady                11m                kubelet, 26207k8s9000     Node 26207k8s9000 status is now: NodeReady

**Comment by andyzhangx** [comment]
try to delete azure-vnet-ipam.json, azure-vnet-ipam.json.lock, azure-vnet.json, azure-vnet.json.lock & restart Kubelet service

**Comment by MarcPow** [comment]
Is there a known root cause here?

**Comment by MarcPow** [comment]
Closing out as non-actionable.  
1) There have been so many fixes here in newer versions of the CNI that it's not worth tracking this here.
2) Any issues at this layer should be tracked against the relevant CNI, not this project.
