### ISSUE TITLE
kubelet crash on journald restart

### ISSUE THREAD

**Issue by lobeck** [kubernetes/kubernetes#69161]
/kind bug

**What happened**:

Kubelet crash caused by SIGPIPE when restarting journald

    [pid  4370] +++ killed by SIGPIPE +++
    [pid  8965] <... mprotect resumed> )    = 0
    [pid  3909] +++ killed by SIGPIPE +++
    mprotect(0x7f076abeb000, 16384, PROT_READ) = 0
    --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=1, si_uid=0} ---
    +++ killed by SIGTERM +++`

**What you expected to happen**:

nothing, kubelet needs to keep running and logging continue

**How to reproduce it (as minimally and precisely as possible)**:

kill -9 the journald process, it will cause kubelet to exit

**Anything else we need to know?**:

Noticed this while debugging issues we've seen which seem to be caused by crashes of journald.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): VERSION="16.04.5 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):4.4.0-1065-aws / systemd 229-4ubuntu21.4

**Comment by GaoRong** [comment]
FYI, this behavior is common in systemd managed process,  as meationed in influxdata/influxdb#7040,  add `RestartForceExitStatus=SIGPIPE` or `Restart=always` to sysytemd config file will fix.
