### ISSUE TITLE
Disable SELinux support for Portworx Volumes.

### ISSUE THREAD

**Issue by adityadani** [kubernetes/kubernetes#69183]
**What happened**:
Unable to use Portworx ReadWriteMany volumes when SELinux is enabled.

Currently Portworx volumes have the following attributes set
https://github.com/kubernetes/kubernetes/blob/e5964b3fcc60e81b0fa90321933ac959ecb3771d/pkg/volume/portworx/portworx.go#L275

As *SupportsSELinux* is set kubelet adds a `-Z` flag to the mountpoint. This causes the shared volume to be inaccessible inside the application pod.

The correct setting should be similar to the NFS volume plugin as seen here 

https://github.com/kubernetes/kubernetes/blob/e5964b3fcc60e81b0fa90321933ac959ecb3771d/pkg/volume/nfs/nfs.go#L223-L229

**What you expected to happen**:
A pod should be able to use Portworx ReadWriteMany volumes when SELinux is enabled.

**Anything else we need to know?**:

I have opened a PR to flip the SupportsSELinux flag - https://github.com/kubernetes/kubernetes/pull/58646

/kind bug
/sig storage
/assign

**Comment by gnufied** [comment]
close fixed by https://github.com/kubernetes/kubernetes/pull/58646

**Comment by vasudev-anet** [comment]
When flash array direct access (FADA) volumes are used, is SELinux set to false? We are seeing that re-labeling is indeed happening and causing delays for the container to become ready (50 minutes to 1 hour after pod startup). For FADA volumes we use the portworx CSI provisioner. Previously for the same application, we did not see this issue when using non-FADA  volume and non-CSI portworx provisioner.
