### ISSUE TITLE
some control plane images lack /etc/nsswitch.conf and will not respect /etc/hosts

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#69195]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**: My [local docker cluster setup](https://sigs.k8s.io/kind) broke after https://github.com/kubernetes/kubernetes/pull/68890, after much debugging we discovered that the API server could not reach itself on `localhost`, further debugging showed that DNS lookups for localhost were occuring. Long story short, while we have `/etc/hosts` entries for localhost, the api server was not respecting them.

**What you expected to happen**: our standard control plane deployments should not lookup localhost via dns. they should respect /etc/hosts

**How to reproduce it (as minimally and precisely as possible)**: create a cluster and monitor network traffic. then try again after adding a minimal `/etc/nsswitch.conf` to the api server pod.

**Anything else we need to know?**: Prior art: https://github.com/gliderlabs/docker-alpine/issues/367#issuecomment-424546457

This happens because we build with go's build in DNS resolution, which respects glibc's nsswitch.conf, but we build images based on busybox for some components (like the apiserver) which does not ship with one.

**Environment**: kubernetes using [kind](https://sigs.k8s.io/kind)
- Kubernetes version (use `kubectl version`): `v1.13.0-alpha.0.1636+e9fe3f77e9b181`

/sig release

**Comment by BenTheElder** [comment]
/assign
cc @ixdy 

Thanks a million to @MrHohn @neolit123 @justinsb and @liggitt for looking into this with me! this was tricky to resolve.

**Comment by BenTheElder** [comment]
We should be able to fix this by just adding a minimal nsswitch.conf to the images make go's resolver happy.

alternatively we can standardize on eg `debian-base` which already ships one

**Comment by BenTheElder** [comment]
I have a PR under way, will file after lunch!

**Comment by BenTheElder** [comment]
For now adding the nsswitch.conf, but discussing with @ixdy and @Random-Liu, it sounds like switching to debian-base everywhere is the best long term answer. It will actually save a mb or so on each node :sweat_smile: ... and give a more consistent base for component images to build on.

**Comment by kfox1111** [comment]
I just got bit by this.

**Comment by kfox1111** [comment]
This issue will bite anyone deploying a statically linked go binary, not just the api server.

Can we get kubelet to slide in a default nsswitch.conf that is sane so it wont keep biting people? Similar to resolv.conf.

**Comment by BenTheElder** [comment]
We'd need a feature request to sig-node and probably sig-network.

I do like this idea, but, nsswitch.conf is used for things other than networking so injecting one might be slightly problematic. In this case it was fine because we control the images and the binaries.

People deploying go images need to make sure they have a sane nsswitch.conf for now, or not deploy staticly linked binaries, unfortunately.

**Comment by dims** [comment]
For 1.13, we should just document the problem

**Comment by kfox1111** [comment]
would it be difficult to add the file only if it doesn't exist in the image?

**Comment by BenTheElder** [comment]
Yeah that work around [will work](https://github.com/kubernetes-sigs/kind/pull/45) for now, I'm not sure how difficult / expensive it would be for the kubelet to conditionally add this, and it might be a surprising behavior change for arbitrary containers / pods.

**Comment by kfox1111** [comment]
it may be surprising, but its very surprising now too, that dns takes precident to hosts file unexpectedly. :(
I'd rather it be secure by default and surprise them that its safe. I didn't even know glibc had this backwards behavior when nsswitch.conf was missing. I haven't run up against a glibc based system that didn't have an nsswitch file. All distro's add one.

**Comment by kfox1111** [comment]
hmm... etcd is crashing too.... I hope there is an equiv of etcdExtraVolumes....

**Comment by kfox1111** [comment]
never mind on the etcd thing that was something else. The above yaml tweaks did solve the issue.

**Comment by nickperry** [comment]
We have just wasted a TON of time on this when a misconfigured Samsung TV on the other side of the world, plus lack of rigor or our DDNS policy broke our Kube 1.12 clusters.

I really don't like that these control plane images are hitting DNS for every lookup of localhost. I am very keen to see #71082 implemented.

**Comment by BenTheElder** [comment]
The control plane images in future releases already contain nsswitch.conf,
which could be cherry picked back. Doing this in an automated fashion like
that issue would require bringing a feature to sig-network and sig-node for
discussion. I suspect supplying a file only if it doesn't exist in the
image would be somewhat expensive compared to what we do currently, and
it's definitely a breaking change.

In the meantime, if you're containerizing go and not using CGO for
networking, you need to add this to your own images.

**Comment by kfox1111** [comment]
@BenTheElder I would argue, that 1.12 was a broken release. 1.11 and below did not have the issue. As K8S is maturing, some of us, especially in more enterprise like environments, are not upgrading as fast, so the issues are being found slower. I think backporting the nsswitch.conf fix for the control plane images is appropriate to resolve the regression until a more universal fix can be put in place.

**Comment by dims** [comment]
@nickperry that sounds like a great WHODUNIT war story :)

**Comment by neolit123** [comment]
> IMO, kubeadm setting ClusterFirstWithHostNet on control plane pods was certainly broken, which I questioned, but not just for this reason, and that change was eventually reverted IIRC. 

yes the change was reverted.
it also spawned a little bit of a discussion here for a rather complicated workaround:
https://github.com/kubernetes/kubernetes/pull/71010#issuecomment-438475912

given this affects images that are already deployed at GCR, it's unlikely that it can be cherry picked. the images do support revisions, but this would also mean porting changes to all the bundled tools that use them as hardcoded tags. also this means revisions for all patch release images.

overall i see this as something that will not be approved by sig-network and the GCR maintainers.

**Comment by kfox1111** [comment]
I guess to prevent a future regression, we probably need a test that inserts a localhost.example.com <some other address> record somewhere during the test.
