### ISSUE TITLE
The latest version described in the CHANGELOG-1.12.md is still v1.12.0-rc.2

### ISSUE THREAD

**Issue by warmchang** [kubernetes/kubernetes#69200]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**: 
The latest version described in the CHANGELOG-1.12.md is still v1.12.0-rc.2, should be upgrade to GA version info.

**What you expected to happen**:
It should be upgrade as the release-1.12 and master branch.

**How to reproduce it (as minimally and precisely as possible)**:
Just check the https://github.com/kubernetes/kubernetes/blob/v1.12.0/CHANGELOG-1.12.md

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tossmilestone** [comment]
@warmchang I think this is not an issue, because there is v1.12-rc2 before tagging v1.12.

**Comment by warmchang** [comment]
@tossmilestone 
The version obtained by the tag, the changlog describes the previous RC version, this is a bit strange.
But historically, all versions are like this, so keep it by convention. :confused: 
/close
