### ISSUE TITLE
Kubernetes conf issue

### ISSUE THREAD

**Issue by ChaitanyaVSH** [kubernetes/kubernetes#69217]
Can anyone tell me the api version for v1.12 , below is for v1.11  

apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
controllerManagerExtraArgs:
  pod-eviction-timeout: 10s

when i had reset with "kubeadm reset" and i have run "kubeadm init kubeadm_conf.yaml" command (above are the contents of "kubeadm_conf.yaml" file) , i was said "You are using an old api , update it to new api blah blah...!!".

**Comment by ulm0** [comment]
`v1alpha3` see: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#sig-cluster-lifecycle

**Comment by neolit123** [comment]
here is an example of how to use v1alpha3.
also the config is passed like this `kubeadm init --config=<filename>`.

thanks.
/close
