### ISSUE TITLE
External dependencies in 1.12 Changelog are a bit stale

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69216]
Looking at https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies

- etcd should be 3.2.24 ( https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+etcd+3.2.24+is%3Amerged ) 
- docker should be 18.06 ( https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+docker+18.06+is%3Amerged )

We should checkout the rest of them as well.

**Comment by dims** [comment]
/sig release

cc @tpepper @nickchase @AishSundar

**Comment by AishSundar** [comment]
I assume this will go in 1.12.1? or can release notes be pushed independently ?

**Comment by jimangel** [comment]
@AishSundar I opened a PR for a typo nit on the release notes and would think as long as it's not a new feature change but a correction on the 1.12.0 release, it should be ok to push independently. Hopefully someone will chime in if I'm wrong.

**Comment by leetskil** [comment]
waiting for this to be release, hopefully it would be fix.

**Comment by dims** [comment]
/close

this should have been fixed in 1.12.1
