### ISSUE TITLE
RFC: Real time readiness probe

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#69226]
In order to minimize the amount of requests that are sent to unready pods before the readiness probe detects the un-readiness of said pods, I was wondering if we could think about a new sort of probe that, instead of polling at a regular interval, would connect to a port, mark the pod ready upon success and only **mark the pod unready if the socket were to be closed** by the pod.

/kind feature
/sig api-machinery

**Comment by lavalamp** [comment]
/remove-sig api-machinery
/sig network

API Machinery wouldn't be implementing this. I'll give it to sig network, but I'm suspicious that the proposed mechanism won't actually function well in all cases. (No guarantee the OS instantly closes the socket, for example)
