### ISSUE TITLE
1.12 Running in-cluster e2es no longer respects service account RBAC rules. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#69234]
**Is this a BUG REPORT**:
Sonobuoy runs the kubernetes e2e's differently then test-infra.  It constructs an in-cluster config vs. being handed a kubeconfig from the infra.  

In 1.12 something has broken this behavior, I'm still digging into the details. 

**What happened**:
Run tests from within the cluster error occurs - 
https://paste.fedoraproject.org/paste/D559nyX6SlGhA3tLPtWt5A

**What you expected to happen**:
Works fine, just like it had in 1.11 

**How to reproduce it (as minimally and precisely as possible)**:
Run tests from within the cluster given proper RBAC rules. 

**Anything else we need to know?**:
Discovered when updating sonobuoy for 1.12.

/sig testing
/kind bug 
/cc @kubernetes/sig-cluster-lifecycle @dims @BenTheElder @kubernetes/cncf-conformance-wg

**Comment by dims** [comment]
One data point, the  in-cluster-client-configuration example seems to work (but was missing RBAC step):
https://github.com/kubernetes/kubernetes/pull/69232

**Comment by neolit123** [comment]
is there a known time when it last worked?

**Comment by timothysc** [comment]
> is there a known time when it last worked? 

1.11 worked fine 

> One data point, the in-cluster-client-configuration example seems to work (but was missing RBAC step):
#69232 

Sonobuoy's legacy in-cluster config work as well.  

The e2e test suite relies on a single utility wrapper that seems to not be tested. 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2051

**Comment by neolit123** [comment]
> 1.11 worked fine

needs a binary search bisect between 1.11 and 1.12. :\

**Comment by akutz** [comment]
I'm definitely interested in this as VMware runs e2e tests in cluster. We're still handing the tests a kubeconfig from the outside, but the plan is to move to the same model as used by Sonobuoy.

**Comment by darxkies** [comment]
The token field in /tmp/kubeconfig-xxx is missing. BearerToken in client-go is apparently empty. Probably caused by this: https://github.com/kubernetes/kubernetes/pull/67359

**Comment by darxkies** [comment]
FYI, the following command can trick sonobuoy/e2e 0.12 into running the tests but beware it is a hack:

kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous

**Comment by dims** [comment]
@timothysc i don't have proof, but looking through swathes of stuff, this one stood out - https://github.com/kubernetes/kubernetes/pull/66684 wanna try a local test in your environment with that removed?

**Comment by neolit123** [comment]
@liztio shared a possible solution in the sig-cluster-life chat, @timothysc can confirm if that was a fix for the same thing or perhaps something else.

**Comment by dims** [comment]
i'll take back my comment about #66684. trying to recreate the scenario i was able to print out the tmp file with the in-cluster config info.

1.11 - https://paste.fedoraproject.org/paste/8vHwWGJhgzrUkSlccBmVMg/raw
1.12 - https://paste.fedoraproject.org/paste/83My3KRhnny8kvSV9CWslQ/raw

Looks like the `token` information is missing in 1.12 exactly as @darxkies mentioned. So i support the darxkies's theory that #67359 is causing it.

**Comment by timothysc** [comment]
Thanks @darxkies I verified that https://github.com/kubernetes/kubernetes/pull/69272 does fix.

**Comment by stealthybox** [comment]
@timothysc @chuckha What should we do with Sonobuoy now that this is merged and cherry-picked?
Do we need to wait for 1.12.1 to drop before we can use that test suite?
Will we use that test suite for 1.12.0 clusters?

**Comment by liggitt** [comment]
/close
per https://github.com/kubernetes/kubernetes/issues/69234#issuecomment-426656582
