### ISSUE TITLE
kubectl patch command not working for modifying an object in replication controller

### ISSUE THREAD

**Issue by kamesh2229** [kubernetes/kubernetes#69240]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

I have kubernetes 1.0.3 version installed and there is a master and 5 minion nodes available.
In the minion nodes Elastic search cluster is deployed.I wanted to scale a new minion node and start ES container which i am doing by scaling the replication controller.

The ES service is deployed with a cluster IP and RC for the ES data node is pointing to the cluster IP.
The cluster IP mentioned in the RC for ES data node is wrong and pointing to a ES client service rather than data storage service.
With this somehow ES cluster is formed and now when i am scaling the RC the container is started with the wrong cluster IP and the new node is not joining the cluster.

I am trying to modify the cluster IP in RC using kubectl patch but it is not happening can you please let me know if something wrong or we can't modify it run time in this version ?

-bash-4.2# kubectl patch replicationcontroller rta-ds-data-rc -p '{"spec":{"containers":{"env":[{"name":"CLUSTER_IP","value":"10.254.1.11"}]}}}

**What you expected to happen**:
The cluster IP is changed as required

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.0.3
- Cloud provider or hardware configuration:
Kubernetes running on baremetal
- OS (e.g. from /etc/os-release):
Red Hat Atomic OS CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liggitt** [comment]
containers is an array, not an object. you need to specify which item in the containers list you want to patch

/close
