### ISSUE TITLE
should return error when rollback deployment to a nonexistent revision

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#69248]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig cli
> /kind feature

**What happened**:
when rollback to a nonexistent revision , like below, the output shows the deloyment and i assume it was successful:
```
[root@hpa-vm:/home/yaml]$ kubectl rollout undo deploy/nginx-deployment --to-revision=3
deployment.extensions/nginx-deployment
```
Actually, the rollback does not occur
it should return error like:  no specified revision found
we should add a validation for the revision before rollback
https://github.com/kubernetes/kubernetes/blob/b1e15b4d98f55d6c1cbb5da58244790c0a80a8a4/pkg/kubectl/rollback.go#L107-L124

**What you expected to happen**:
```
[root@hpa-vm:/home/yaml]$ kubectl rollout undo deploy/nginx-deployment 
error: no rollout history found for deployment "nginx-deployment"
```

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy a deployment
2. rollback to a nonexistent revision

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Pingan2017** [comment]
ping @soltysh ,  take a look ?

**Comment by soltysh** [comment]
The bug description seems legit, @Pingan2017 you're planning to work on it?

**Comment by Pingan2017** [comment]
@soltysh  Yeah , I'll work on it

**Comment by Pingan2017** [comment]
it seems  fixed in master 
```
[root@hpa-vm:/opt/kubernetes/1.4.5]$ kubectl rollout undo deploy/nginx-deployment --to-revision=3
deployment.extensions/nginx-deployment skipped rollback (DeploymentRollbackRevisionNotFound: Unable to find the revision to rollback to.)
```
