### ISSUE TITLE
GetAzureDiskLun sometimes costs 1 min which is too long time

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#69262]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
There is a drawback after PR: https://github.com/kubernetes/kubernetes/pull/62612
following `getDiskController` code will fetch vmCache may lead to below error and the vmCache refresh time period would be 1 min, and `MountVolume.WaitForAttach` may cost 1 min which is too long time
https://github.com/kubernetes/kubernetes/blob/ba66014fec87274322fc08190ec405cfb704a7d5/pkg/volume/azure_dd/attacher.go#L162

```
MountVolume.WaitForAttach failed for volume "pvc-12b458f4-c23f-11e8-8d27-46799c22b7c6" : Cannot find Lun for disk kubernetes-dynamic-pvc-12b458f4-c23f-11e8-8d27-46799c22b7c6
```

**How to fix this**
At least in Linux, we may still use `devicePath` parameter to get LUN, which is almost zero time.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by antoineco** [comment]
k8s 1.10.4, Azure (deployed via ACS-engine)

This is hitting us quite hard.

---

`kubelet` logs:
```
09:48:43 reconciler.go:252] operationExecutor.MountVolume started for volume "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") pod "solr-0" (UID: "ea31d4b3-d144-11e8-89ee-000d3ad2008d")

09:48:43 operation_generator.go:486] MountVolume.WaitForAttach entering for volume "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") pod "solr-0" (UID: "ea31d4b3-d144-11e8-89ee-000d3ad2008d") DevicePath "7"

09:48:44 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\"" failed. No retries permitted until 2018-10-17 09:50:46.795652809 +0000 UTC m=+3917654.999679399 (durationBeforeRetry 2m2s). Error: "MountVolume.WaitForAttach failed for volume \"pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\") pod \"solr-0\" (UID: \"ea31d4b3-d144-11e8-89ee-000d3ad2008d\") : Cannot find Lun for disk mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105"

09:48:54 kubelet.go:1640] Unable to mount volumes for pod "solr-0_default(ea31d4b3-d144-11e8-89ee-000d3ad2008d)": timeout expired waiting for volumes to attach or mount for pod "default"/"solr-0". list of unmounted volumes=[solrhome]. list of unattached volumes=[solrhome]; skipping pod
pod_workers.go:186] Error syncing pod ea31d4b3-d144-11e8-89ee-000d3ad2008d ("solr-0_default(ea31d4b3-d144-11e8-89ee-000d3ad2008d)"), skipping: timeout expired waiting for volumes to attach or mount for pod "default"/"solr-0". list of unmounted volumes=[solrhome]. list of unattached volumes=[solrhome]
```

---

`kube-controller-manager` logs:

```
09:48:19 attacher.go:145] azureDisk - VolumesAreAttached: check volume "mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (specName: "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") is no longer attached

09:48:19 operation_generator.go:193] VerifyVolumesAreAttached determined volume "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (spec.Name: "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") is no longer attached to node "k8s-caybp6bcjsev-35913815-vmss000000", therefore it was marked as detached.

09:48:19 reconciler.go:285] attacherDetacher.AttachVolume started for volume "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") from node "k8s-caybp6bcjsev-35913815-vmss000000"

09:48:20 attacher.go:104] Attach volume "/subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" to instance "/subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-caybp6bcjsev-35913815-vmss/virtualMachines/0" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> Code="AttachDiskWhileBeingDetached" Message="Cannot attach data disk 'bcff1cba-d78f-49c2-8b85-1d56c51852cc' to VM 'k8s-caybp6bcjsev-35913815-vmss_0' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again."

09:48:20 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\"" failed. No retries permitted until 2018-10-17 09:48:20.74273507 +0000 UTC m=+3202481.533547869 (durationBeforeRetry 500ms). Error: "AttachVolume.Attach failed for volume \"pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\" (UniqueName: \"kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\") from node \"k8s-caybp6bcjsev-35913815-vmss000000\" : Attach volume \"mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105\" to instance \"/subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-caybp6bcjsev-35913815-vmss/virtualMachines/0\" failed with compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> Code=\"AttachDiskWhileBeingDetached\" Message=\"Cannot attach data disk 'bcff1cba-d78f-49c2-8b85-1d56c51852cc' to VM 'k8s-caybp6bcjsev-35913815-vmss_0' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again.\""

09:48:20 reconciler.go:285] attacherDetacher.AttachVolume started for volume "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") from node "k8s-caybp6bcjsev-35913815-vmss000000"

09:48:20 operation_generator.go:332] AttachVolume.Attach succeeded for volume "pvc-34bc8020-b0cf-11e8-9196-000d3ad20105" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<redacted>/resourceGroups/caybp6bc-jsev3-s1/providers/Microsoft.Compute/disks/mycluster-kub-dyn-pvc-34bc8020-b0cf-11e8-9196-000d3ad20105") from node "k8s-caybp6bcjsev-35913815-vmss000000"
```

The last Attach operation reports success, yet we enter the same error loop over and over again.

**Comment by andyzhangx** [comment]
@antoineco thanks for reporting, I am fixing this issue, code should be ready in this week.

**Comment by Bryji** [comment]
We have seen what looks like this issue - possible regression? It took 11m for the volume to attach. 

>   Normal   SuccessfulAttachVolume  11m                   attachdetach-controller                    AttachVolume.Attach succeeded for volume "pvc-55248bc6-fa4a-11e9-8cce-000d3a7d14ec"
>   Warning  FailedMount             3m37s (x12 over 11m)  kubelet, k8s-pci2pool-21580528-vmss000001  MountVolume.WaitForAttach failed for volume "pvc-55248bc6-fa4a-11e9-8cce-000d3a7d14ec" : Cannot find Lun for disk api-k8s-dev-azure-aspect-cloud-dyn-pvc-55248bc6-fa4a-11e9-8cce-000d3a7d14ec
>   Warning  FailedMount             3m15s (x4 over 10m)   kubelet, k8s-pci2pool-21580528-vmss000001  Unable to mount volumes for pod "kafka-1_development-us-azure-2(5526fd52-fa4a-11e9-8cce-000d3a7d14ec)": timeout expired waiting for volumes to attach or mount for pod "development-us-azure-2"/"kafka-1". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-8rgjd]
>   Normal   Pulling                 90s                   kubelet, k8s-pci2pool-21580528-vmss000001  pulling image "acrdeveastus2.azurecr.io/platops/cp-kafka:8634c29"
>   Normal   Pulled                  81s                   kubelet, k8s-pci2pool-21580528-vmss000001  Successfully pulled image "acrdeveastus2.azurecr.io/platops/cp-kafka:8634c29"
>   Normal   Created                 74s                   kubelet, k8s-pci2pool-21580528-vmss000001  Created container
>   Normal   Started                 74s                   kubelet, k8s-pci2pool-21580528-vmss000001  Started container

**Comment by andyzhangx** [comment]
@Bryji it's more likely that disk could not be detected under `/dev/disk/` dir inside vmss instance, is it a transient issue?

**Comment by Bryji** [comment]
Seems to happen consistently on the 2nd pod of a new deploy. We have seen 3-4 times in a row deleting and re-deploying this project. Doesn't seem to be an issue for the kafka-0 and kafka-2 pods, just kafka-1.

**Comment by bzuelke** [comment]
The version we’re running is k8s 1.13.12 in useast2. And right this is on vmss.

**Comment by giggio** [comment]
I'm having a similar issue, but I'm on 1.14.8. I don't know if https://github.com/Azure/AKS/issues/1278 is related, but these disk attachments seem to not be working properly on aks with vmms.

**Comment by Tenseiga** [comment]
confirm volume attach with vmss is failing bad..

**Comment by andyzhangx** [comment]
> confirm volume attach with vmss is failing bad..

@Tenseiga pls open a separate issue, provide detailed error info, e.g. k8s version, pod error description, etc. thanks.

**Comment by hmz** [comment]
@andyzhangx 
This took too long
AKS - kubernetes version -> 1.14.8
location -> west europe

```
Events:
  Type     Reason                  Age                 From                                        Message
  ----     ------                  ----                ----                                        -------
  Warning  FailedScheduling        29m (x4 over 30m)   default-scheduler                           pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled               29m                 default-scheduler                           Successfully assigned authentication/authentication-mssql-statefulset-0 to aks-nodepool1-29122124-vmss000004
  Normal   SuccessfulAttachVolume  28m                 attachdetach-controller                     AttachVolume.Attach succeeded for volume "pvc-8d9f0ade-1825-11ea-83a0-22ced17d4a3d"
  Warning  FailedMount             23m (x10 over 27m)  kubelet, aks-nodepool1-29122124-vmss000004  MountVolume.WaitForAttach failed for volume "pvc-8d9f0ade-1825-11ea-83a0-22ced17d4a3d" : **Cannot find Lun for disk kubernetes-dynamic-pvc**-8d9f0ade-1825-11ea-83a0-22ced17d4a3d
  Warning  FailedMount             23m (x3 over 27m)   kubelet, aks-nodepool1-29122124-vmss000004  Unable to mount volumes for pod "authentication-mssql-statefulset-0_authentication(8df467e7-1825-11ea-83a0-22ced17d4a3d)": timeout expired waiting for volumes to attach or mount for pod "authentication"/"authentication-mssql-statefulset-0". list of unmounted volumes=[authentication-mssql-persistent-data-storage]. list of unattached volumes=[authentication-mssql-persistent-data-storage default-token-b7spv]
  Normal   Pulled                  21m                 kubelet, aks-nodepool1-29122124-vmss000004  Container image "mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu" already present on machine
  Normal   Created                 21m                 kubelet, aks-nodepool1-29122124-vmss000004  Created container authentication-mssql
  Normal   Started                 21m                 kubelet, aks-nodepool1-29122124-vmss000004  Started container authentication-mssql
```

**Comment by andyzhangx** [comment]
thanks for the reporting, I could confirm that the `WaitForAttach ... Cannot find Lun for disk` is due to PR: https://github.com/kubernetes/kubernetes/pull/83102, which is going to mitigate vmss API throttling issue, in that PR, it enlarge the getVMSS TTL from 1min to 10min.
Fortunately, from k8s 1.15.0, won't have this issue, since we have refactored the disk detect logic, it won't depend on getVMSS operation to get the disk LUN.

In brief, pls upgrade to latest version 1.15.5 to fix this issue, thanks.
@hmz @giggio

**Comment by andyzhangx** [comment]
cherry-pick PR: https://github.com/kubernetes/kubernetes/pull/86006 to fix this issue on 1.14

**Comment by bzuelke** [comment]
You mention a 1.14 cherry pick but I'm also seeing https://github.com/kubernetes/kubernetes/pull/78441
Is this correct to assume 1.13 will have this fix as well @andyzhangx ?

**Comment by andyzhangx** [comment]
> You mention a 1.14 cherry pick but I'm also seeing #78441
> Is this correct to assume 1.13 will have this fix as well @andyzhangx ?

@bzuelke 1.13 don't accept any cherry-pick, so only 1.14 could be cherry-picked now, target fixed version is 1.14.10

**Comment by kosta709** [comment]
the delay is still can be very big
this is because azure api call for disk attach returns after at  35s-2min and kubelet goes to its exp. backoff retries so it can reach 2min timeout
adding attached recording:
called 3 disk simultaneous attach with interval ~2s and saw `watch tree /dev/disk/azure/scsi1` and `az vmss list-instances ...`
So actual attachment takes ~10s (device appears in /dev/disk/azure/scsi1) , but due to azure api we can loop on it

**Comment by zffocussss** [comment]
> I'm having a similar issue, but I'm on 1.14.8. I don't know if [Azure/AKS#1278](https://github.com/Azure/AKS/issues/1278) is related, but these disk attachments seem to not be working properly on aks with vmms.

same here

**Comment by zffocussss** [comment]
> the delay still can be very big
> this is because azure api call for disk attach returns after at 35s-2min and kubelet goes to its exp. backoff retries so it can reach 2min timeout
> adding attached recording: https://www.youtube.com/watch?v=aklhaC2926Q&feature=youtu.be
> 
> called 3 disk simultaneous attach with interval ~2s and saw `watch tree /dev/disk/azure/scsi1` and `az vmss list-instances ...`
> So actual attachment takes ~10-30s (device appears in /dev/disk/azure/scsi1) , but due to azure api we can loop on it
> 
> I saw also that disk attach timing is unstable and somtemes it can take 2.5min
> 
> @andyzhangx , what do you think about logic like below?
> 
> * azure_controller_vmss.go is not waiting for attach_disk to return, instead it calls GET until it returns lun id (we saw it takes few seconds after attach_disk).
> * after GET returns lun id , it updates node's disks with lunId and kubelet can continue with mount after waiting for /dev/disk/azure/scsi1/lun*

It takes about 10 minutes to recover from the FailedMount messages.

**Comment by andyzhangx** [comment]
@zffocussss what's your k8s version?

**Comment by andyzhangx** [comment]
there is a new vhd disk feature based on azure file which could attach/detach disk < 1s, consider that as an option if you have concern about disk attach/detach time cost: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/disk

**Comment by zffocussss** [comment]
> @zffocussss what's your k8s version?

AKS v1.14.8

**Comment by andyzhangx** [comment]
@zffocussss for this specific issue,  aks 1.15.x won't have this issue.

**Comment by zffocussss** [comment]
> thanks for the reporting, I could confirm that the `WaitForAttach ... Cannot find Lun for disk` is due to PR: #83102, which is going to mitigate vmss API throttling issue, in that PR, it enlarge the getVMSS TTL from 1min to 10min.
> Fortunately, from k8s 1.15.0, won't have this issue, since we have refactored the disk detect logic, it won't depend on getVMSS operation to get the disk LUN.
> 
> In brief, pls upgrade to latest version 1.15.5, 1.15.x won't have this issue, thanks.
> @hmz @giggio

hi @andyzhangx ,I am not dare to upgrade.because my stateful rabbitmq with pvc can not started because of failmount of PVC!

**Comment by andyzhangx** [comment]
> > thanks for the reporting, I could confirm that the `WaitForAttach ... Cannot find Lun for disk` is due to PR: #83102, which is going to mitigate vmss API throttling issue, in that PR, it enlarge the getVMSS TTL from 1min to 10min.
> > Fortunately, from k8s 1.15.0, won't have this issue, since we have refactored the disk detect logic, it won't depend on getVMSS operation to get the disk LUN.
> > In brief, pls upgrade to latest version 1.15.5, 1.15.x won't have this issue, thanks.
> > @hmz @giggio
> 
> hi @andyzhangx ,I am not dare to upgrade.because my stateful rabbitmq with pvc can not started because of failmount of PVC!

@zffocussss  you could scale your statefulset to 0 replica, and pvc disk would be detached. After upgrade, scale back to original count.

**Comment by zffocussss** [comment]
> > > thanks for the reporting, I could confirm that the `WaitForAttach ... Cannot find Lun for disk` is due to PR: #83102, which is going to mitigate vmss API throttling issue, in that PR, it enlarge the getVMSS TTL from 1min to 10min.
> > > Fortunately, from k8s 1.15.0, won't have this issue, since we have refactored the disk detect logic, it won't depend on getVMSS operation to get the disk LUN.
> > > In brief, pls upgrade to latest version 1.15.5, 1.15.x won't have this issue, thanks.
> > > @hmz @giggio
> > 
> > 
> > hi @andyzhangx ,I am not dare to upgrade.because my stateful rabbitmq with pvc can not started because of failmount of PVC!
> 
> @zffocussss you could scale your statefulset to 0 replica, and pvc disk would be detached. After upgrade, scale back to original count.

okay,let me have a try.

**Comment by zffocussss** [comment]
> > > > thanks for the reporting, I could confirm that the `WaitForAttach ... Cannot find Lun for disk` is due to PR: #83102, which is going to mitigate vmss API throttling issue, in that PR, it enlarge the getVMSS TTL from 1min to 10min.
> > > > Fortunately, from k8s 1.15.0, won't have this issue, since we have refactored the disk detect logic, it won't depend on getVMSS operation to get the disk LUN.
> > > > In brief, pls upgrade to latest version 1.15.5, 1.15.x won't have this issue, thanks.
> > > > @hmz @giggio
> > > 
> > > 
> > > hi @andyzhangx ,I am not dare to upgrade.because my stateful rabbitmq with pvc can not started because of failmount of PVC!
> > 
> > 
> > @zffocussss you could scale your statefulset to 0 replica, and pvc disk would be detached. After upgrade, scale back to original count.
> 
> okay,let me have a try.

I use helm to deploy.how can I restore to two replicas after upgrading k8s version?

**Comment by andyzhangx** [comment]
`kubectl scale statefulest xx --replicas=x ...`

**Comment by zffocussss** [comment]
> `kubectl scale statefulest xx --replicas=x ...`

it works
