### ISSUE TITLE
It is impossible to deploy identical NLB backed service in two different K8S clusters in same AWS region

### ISSUE THREAD

**Issue by merlineus** [kubernetes/kubernetes#69264]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I've tried to switch two Istio ingressgateways in different K8S clusters (in the same AWS region) to NLB loadbalancers, but receive error:

> error processing service istio-system/istio-ingressgateway (will retry): failed to ensure load balancer for service istio-system/istio-ingressgateway: Error creating load balancer target group: "DuplicateTargetGroupName: A target group with the same name 'k8s-tg-9ff6919e87f45-80-31380' exists, but with different settings

**What you expected to happen**:
Second loadbalancer's targetgroups created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create two K8S clusters in the same AWS region. Create in each cluster service backed by NLB loadbalancer with the same namespace/servicename and ports combination.

**Anything else we need to know?**:
Problem is related to target group name calculation in function createTargetName:
https://github.com/kubernetes/kubernetes/blob/bcc23dfdc1620a2bbe840d62b739bcd1bda260b7/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L330-L333
Names for same combination of namespace/servicename (istio-system/istio-ingressgateway) and ports in different clusters in same region will generate identical names for target groups. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: AWS
- Install tools: kops

**Comment by merlineus** [comment]
@kubernetes/sig-aws-bugs

**Comment by keyosk** [comment]
Is anyone actively working on a patch for this? It should be fairly straightforward to add another trimmed hash of the cluster name into the target group name. There's a 32 character limit on the target group name that we'll need to stay under.

**Comment by sdake** [comment]
@keyosk cluster names are not always unique, however, the calling function has an ARN which could replace the namespace used in this 4 line function...

**Comment by sdake** [comment]
@M00nF1sh the cluster name is not always unique either (e.g. a kubeadm deployed cluster on AWS).  I have taken a look at this - and the backward compatibility is an issue.  One option is to try deletions with hashing calculation function - if that fails - try with another and always create using the new mechanism.  This approach is a little rudimentary though and could present problems.

Thoughts?

Cheers
-steve

**Comment by M00nF1sh** [comment]
> @M00nF1sh the cluster name is not always unique either (e.g. a kubeadm deployed cluster on AWS). I have taken a look at this - and the backward compatibility is an issue. One option is to try deletions with hashing calculation function - if that fails - try with another and always create using the new mechanism. This approach is a little rudimentary though and could present problems in the unlikely event of a hash collision.
> 
> Thoughts?
> 
> Cheers
> -steve

@sdake 
Do you mean the clusterName can change via kubeadm? I haven't try that out yet, will take a look.

For backward copabitility, i think silently deleting old ELB causes service outage(not sure whether it's enough to call it out in release notes).
Another approach might be support both modes. e.g. If we detected a ELB with old name, we'll use it and attach an warning event to that service(that ask user to delete and create service manually). And deprecate this logic after maybe 2~3 releases.

**Comment by sdake** [comment]
@M00nF1sh hadn't considered the condition of a restarting cloud.  Indeed that would create an outage.  Your solutions sound good.  The kubeadm tool always names clusters `kubernetes` although I think in later versions there is a way to customize the name.  Not everyone usees kubeadm either (their is kops and atleast 50 different tools in the CNCF ecosystem that have been published for installing Kubernetes.  I don't think the cluster name is sufficient as a unique identifier.

Cheers
-steve

**Comment by M00nF1sh** [comment]
@sdake I think we are using clusterName as a unique identifier everywhere(e.g. k8s.io/cluster/${clusterName}:owned tags). Since cluster admins can have control over clusterName when launching clusters, i think it ok to assume `clusters in same region cannot have same name`.
Also, clusterName is an unique identifier under kubernetes federation 😄

**Comment by sdake** [comment]
@M00nF1sh,

Ya, that seems fair (re cluster names).  I hadn't realized the cluster name was used throughout the cloud provider as a unique identifier.

The first choice seems to have a limitation that if a cluster is deployed in a region, no new cluster can be deployed in that region using the same name/namesapce of the service.  The second choice doesn't have this limitation, but seems more complex.  I think I'd prefer to not require operators to delete their clusters (as required in option A) to obtain the new naming convention so choice B seems more natural.

Thoughts?  What do others think on this issue?

Cheers
-steve

**Comment by VinceMD** [comment]
is there a workaround for this to work? Like editing manually

**Comment by yogeek** [comment]
As already discussed on Slack, this does not seem to be fixed in my side :
https://github.com/kubernetes/kubernetes/pull/74910#issuecomment-545583386

Can someone confirm this please ?

**Comment by AceHack** [comment]
Is this fixed in EKS 1.15?

**Comment by M00nF1sh** [comment]
@AceHack yes

**Comment by AceHack** [comment]
So is NLB still an alpha feature of EKS or is it now more supported?

**Comment by M00nF1sh** [comment]
@AceHack it's considered beta on 1.15+

**Comment by anton-yurchenko** [comment]
Working on EKS 1.16, every target group has a unique suffix, for example: `k8s-istiosys-ingressg-5db8dac7c3`
