### ISSUE TITLE
Kubelet error

### ISSUE THREAD

**Issue by ChaitanyaVSH** [kubernetes/kubernetes#69261]
I'm getting the below error on master node....Any solution?

[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] this might take a minute or longer if the control plane images have to be pulled

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
couldn't initialize a Kubernetes cluster

**Comment by neolit123** [comment]
please fill the issue template correctly and re-open the issue:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

needed are OS version, kubectl version and the rest of the details.
thanks.
/close
