### ISSUE TITLE
GPU Topology Aware Scheduling

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#69276]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig scheduling
/sig node

**Description**:

Currently, we support GPU as external resource in scheduler; and allocate device round-robin in kubelet. We'd like to enhance that to support GPU's topology, e.g. nvlink. Here're some sub-tasks in my mind: 1.) report device usage by kubelet 2.) a priority in scheduler to find a "better" node 3.) find better device instead of round-robin in kubelet.

xref https://github.com/kubernetes-sigs/kube-batch/issues/236

@kubernetes/sig-node-feature-requests 
@kubernetes/sig-scheduling-feature-requests 

/cc @suleisl2000 @tizhou86

**Comment by k82cn** [comment]
BTW, do we have a common struct for topology of device?

**Comment by ConnorDoyle** [comment]
xref https://github.com/kubernetes/community/pull/1680

**Comment by k82cn** [comment]
/reopen

I'd like to continue this work in upstream :)

**Comment by k82cn** [comment]
xref https://github.com/volcano-sh/volcano/issues/623

**Comment by k82cn** [comment]
We have several discussions at ML-WG meeting on this topic, and we'd like to find a suggested solution for that. I'd like to trace related discussion/enhancement in this issue :)

**Comment by fenghejingchi** [comment]
any update on this topic?

**Comment by xial-thu** [comment]
any update on this issue?

I've seen the topology manager in k8s >=v1.18 enabled by default. But seems only CPU affinity is supported by now

**Comment by tizhou86** [comment]
> any update on this issue?
> 
> I've seen the topology manager in k8s >=v1.18 enabled by default. But seems only CPU affinity is supported by now

yeah, cpu topology mainly focusing on the numa and cpu core affinity, gpu is more complicated since it's related to the specific nvidia gpu card, will plan to do it if real needs come out.
