### ISSUE TITLE
Implements node-specific Volume Limits for OpenStack

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubernetes/kubernetes#69280]
Kubernetes implements node-specific Volume Limits for Amazon, Google and Azure but not for OpenStack: https://kubernetes.io/docs/concepts/storage/storage-limits/

Because of Libvirt, OpenStack has a limit of 26 attached volume: https://specs.openstack.org/openstack/nova-specs/specs/stein/approved/conf-max-attach-volumes.html

The Kubernetes scheduler should take that limit into account.

**Comment by jsafrane** [comment]
dup of https://github.com/kubernetes/kubernetes/issues/65471 ?

**Comment by sebastien-prudhomme** [comment]
Not really a dup.

Sure if  KUBE_MAX_PD_VOLS is available for any node, i could fix it to 26.

But i would prefer that Kubernetes knows that OpenStack has a limit of 26 by default, the same way it knows  Amazon, Google and Azure have some limits.

**Comment by jsafrane** [comment]
> But i would prefer that Kubernetes knows that OpenStack has a limit of 26 by default, the same way it knows Amazon, Google and Azure have some limits.

Can it break existing clusters? So far they're running without any limits and suddenly they will accept only 26 volumes per node. @kubernetes/sig-openstack-feature-requests, please approve.

**Comment by dims** [comment]
let's please not do this for now ... for one thing, that's just a spec and there is no code in openstack that enforces the limit (even in master) 

https://review.openstack.org/#/q/topic:bp/nova-improvement-of-maximum-attach-volumes-more-than-26-vols

Thanks,
Dims

**Comment by sebastien-prudhomme** [comment]
Ok, as you want. Will try using the CSI driver if KUBE_MAX_PD_VOLS is working in Kubernetes 1.12

**Comment by deshui123** [comment]
@sebastien-prudhomme 
Hi, what dose "try using the CSI driver if KUBE_MAX_PD_VOLS is working in Kubernetes 1.12" mean?
I tried Kubernetes 1.12 in _**Openstack**_ ENV,  my CSI driver is **cinder**, when i set KUBE_MAX_PD_VOLS = 5 to kube-scheduler, i can also create more than 5 pods attached volumes.
==============
------   kube-scheduler.yml   -----
   env:
  - name: KUBE_MAX_PD_VOLS
    value: "5"
------cinder-storage-class.yml------
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cinder-fast-storage 
provisioner: com.example.team/csi-driver 
parameters:
  availability: nova
  type: pd-ssd
-------- statefulset.yml-----------
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 ...
spec:
  serviceName: "cinfo-cinder"
  replicas: 6
  podManagementPolicy: Parallel
 ...
  volumeClaimTemplates:
  - metadata:
      name: cinderpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: cinder-az-nova 
      resources:
        requests:
          storage: 1Gi
--------
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
