### ISSUE TITLE
metrics server deployment yaml uses undocumented variables

### ISSUE THREAD

**Issue by hyperbolic2346** [kubernetes/kubernetes#69292]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
/kind bug

**What happened**:
Metrics server deployment [yaml](https://github.com/kubernetes/kubernetes/blob/860d3cb32c2b52836e1acbacb564698cbaeaacb4/cluster/addons/metrics-server/metrics-server-deployment.yaml#L88) has undocumented variables inside it. After some digging, I found a [Google-specific setup script](https://github.com/kubernetes/kubernetes/blob/8bd0a306b599bc8511a238c8c69c03c729767350/cluster/gce/gci/configure-helper.sh#L2402) that defines these variables. Further, some of the variables define the unit and some of them have the unit outside of the variable.
**What you expected to happen**:
Documentation with some best-practices as far as defining the variables in the file.

As an aside, can we move this [Google-specific work-around](https://github.com/kubernetes/kubernetes/blob/860d3cb32c2b52836e1acbacb564698cbaeaacb4/cluster/addons/metrics-server/metrics-server-deployment.yaml#L56) to that configure-helper google script?

**Comment by shubheksha** [comment]
Maybe it would make more sense to file this in the [docs](https://github.com/kubernetes/website/issues/new) repo since it looks related to that?

**Comment by neolit123** [comment]
^ +1
please file an issue in `kubernetes/website` and tag a SIG with `/sig instrumentation`.
also PRs for the website are welcome!

thanks.
/close
