### ISSUE TITLE
Use better cloud provider LB names

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#69293]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

With https://github.com/kubernetes/kubernetes/pull/66589 merged, each cloud provider can set their own loadbalancer names. We should be careful about how to handle existing LBs with the old name though. I think we can leave it up to each provider to figure out what that will look like as each provider has different requirements for LB names.

Checklist of Providers that support LBs:
- [ ] AWS
- [ ] Azure
- [ ] CloudStack
- [ ] GCE
- [ ] OpenStack

This is in-tree checklist, each out-of-tree provider should do the same :) 

/sig network
/sig cloud-provider

**Comment by andrewsykim** [comment]
related thread for AWS ELB: https://github.com/kubernetes/kubernetes/issues/69293

**Comment by andrewsykim** [comment]
cc @kubernetes/sig-cloud-provider @cheftako @dims @d-nishi @frapposelli @hogepodge @justaugustus @khenidak @mcrute (anyone know contacts for cloudstack?)

**Comment by KIVagant** [comment]
I believe K8s should **not** change ELBs that were already created.

**Comment by andrewsykim** [comment]
/remove-lifecycle stale

@KIVagant generally I agree, I would trust each provider to make the right call based on how the API handles naming. I think most providers are going to require users to recreate their LBs if they want better naming.

**Comment by andrewsykim** [comment]
This seems like it needs a KEP given there are a lot of things to consider here. @thockin @bowei would you be willing to review/approve a KEP for this?

**Comment by bowei** [comment]
Yes

/lifecycle frozen

**Comment by mrobinson513** [comment]
+1, add DigitalOcean to the list of providers supporting LBs. DO is also one of the few that supports changing LB names with no real impact to LB operations, as the name itself is treated like the `Name` tag in other providers (except AWS which ties `Name` to a DNS endpoint)

**Comment by yves-vogl** [comment]
+1

**Comment by phanama** [comment]
+1000 on this

**Comment by shweta-sah** [comment]
+1

**Comment by hasheddan** [comment]
Happy to take this! Will begin with drafting a KEP.

**Comment by MorrisLaw** [comment]
Hey @hasheddan @andrewsykim, have you started the draft for this KEP yet? https://github.com/kubernetes/kubernetes/issues/69293

If not, I am willing to draft the KEP for this and help get this going. Just don't want to start something if you've already done it.

**Comment by hasheddan** [comment]
@MorrisLaw thanks for following up here! I unfortunately did not get around to working on this and would be happy for you to take over. Let me know if I can be of help in any way!

**Comment by MorrisLaw** [comment]
Awesome and I appreciate you taking a look at it. If you have any input or notes on this, that is definitely welcome! Hope to compile a draft soon so we can progress this further 👍

**Comment by MorrisLaw** [comment]
We're holding off on this a bit. I'm not sure it will be needed based on prior discussions with @andrewsykim @bowei 

The issue is that this is highly provider dependent. Due to provider centricity, might not make sense to pursue this too heavily. I'm open to discussion and other suggestions though.

**Comment by cheftako** [comment]
@MorrisLaw Are you working on this?
