### ISSUE TITLE
dry-run: openapi spec missing dryRun query parameter for POST/PUT/PATCH operations

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#69304]
In 1.12 we added support for `dryRun` query parameter in apiserver POST/PUT/PATCH/DELETE handlers https://github.com/kubernetes/kubernetes/pull/65105. However our [openapi spec](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json) wasn't properly updated to reflect the parameter in POST/PUT/PATCH operations. 

The openapi-generated clients (python, java, etc.) will be unaware of the parameter. We may want to cherrypick the spec fix to 1.12, to make the clients support dry-run.

cc @apelisse @mbohlool 
/sig api-machinery

**Comment by apelisse** [comment]
Thanks @roycaihw. I suspect it's a bug in the generation, since I would have expected the verify script to find a difference and/or to have generated what needed to be generated. Or alternatively, it can be a missing flag somewhere that I missed (it's actually more likely ;-)).

**Comment by roycaihw** [comment]
/assign

I'll take a look tomorrow if not today to see why the parameters weren't generated.

**Comment by roycaihw** [comment]
I suppose the `metav1.DeleteOptions` gets parsed and added to go-restful Param() definitions during endpoint installation:
https://github.com/kubernetes/kubernetes/blob/2d67d782de1b90aa45c682bcdefccaae0aec841c/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L722-L724
The PUT/PATCH/POST operations didn't have `addObjectParams(ws, route, versionedXXXXOptions)` invoked because we didn't have `CreateOptions` and `UpdateOptions` before. I will send a PR to add the missed `addObjectParams` function calls.
