### ISSUE TITLE
Allow a jobs to be stopped rather than deleted

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubernetes#69311]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig scheduling

**What happened**:

Kubernetes jobs stop after they are finished.

**What you expected to happen**:

What if want to stop the job before it's finished.  I would like to keep the pods hanging around for debugging. If I do `kubectl delete job <job-id>` the pod is deleted, together with its container and lobs are not retained.

**How to reproduce it (as minimally and precisely as possible)**:

Run any job. You can't do anything like `kubectl stop job <job-id>` or `kubectl job stop <job-id>`

**Anything else we need to know?**:

There may have already discussions about this.
Adding `kubectl stop <object>` could open a can of worms.
Some background [here](https://stackoverflow.com/questions/52597335/is-it-possible-to-stop-a-job-in-kubernetes-without-deleting-it)

**Environment**:
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: all
- OS (e.g. from /etc/os-release): all
- Kernel (e.g. `uname -a`): all
- Install tools: N/A
- Others: N/A

**Comment by skwidy** [comment]
Did you implement a workaround ?
For my use case, I'm thinking about killing the pod, but I'm not sure that's really ideal ... knowing that I have set `restartPolicy: OnFailure`and `backoffLimit: 4`

**Comment by zhengcanbin** [comment]
Is there any progress on this issue?

**Comment by bmehta** [comment]
I would love this feature as well. Any update?

**Comment by jgiangrande-applause** [comment]
We would love this feature as well.

**Comment by rm3l** [comment]
Hi there! +1 for this feature request, which I think would be very useful. Thanks.

**Comment by thomas-riccardi** [comment]
`kubectl patch job the-job-to-pause -p '{"spec":{"parallelism":0}}'` seems to work.

> Specifies the maximum desired number of pods the job should run at any given time. 

```
  Normal  SuccessfulCreate  27s    job-controller  Created pod: test-job-pause-drnxx
  Normal  SuccessfulDelete  21s    job-controller  Deleted pod: test-job-pause-drnxx
  Normal  SuccessfulCreate  17s    job-controller  Created pod: test-job-pause-46z5b
  Normal  SuccessfulDelete  5s     job-controller  Deleted pod: test-job-pause-46z5b
```

It may do strange things around failed pods count (I see a temporary status.failed: 1 which disappears after some seconds...) and backoffLimit is thus never applied (I could get successively 7 pods with the default backoffLimit).

**Comment by adtac** [comment]
Closing in favour of https://github.com/kubernetes/enhancements/issues/2232 - this feature is being added.

cc @ahg-g @alculquicondor
/close
