### ISSUE TITLE
k8s.io/client-go/tools/cache/index.go confuses keys with values

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#69319]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I wrote some client code based on the usage of the word "key" in index.go, and my code was buggy.  Then I looked more closely at index.go, and realized that it has a dichotomy but botches the naming and discussion of it.  The dichotomy is between what that file sometimes calls "values" and some of what it calls "keys".  An `IndexFunc` maps an object to a set of "values".  The `IndexKeys` method of an `Indexer` maps `(a, b)` to a slice of keys and an error, where `a` names an index and `b` is a "value".  Specifically, the resulting slice of keys are those whose corresponding object is mapped by the named `IndexFunc` to a set of "values" that includes `b`.  But the name used for this second parameter (which I have called `b` here) is `indexKey`.  Instead it should be something more like `indexValue`.  The `ByIndex` method has the same parameter naming problem.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): all of them
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by logicalhan** [comment]
@MikeSpreitzer, thanks for reporting the issue. I've opened a pull request to address some of your main concerns, though I did not rename the argument from keys to values (I have reasons which I have hopefully managed to convey in my PR) but we should definitely discuss it further if you feel strongly about it.

**Comment by MikeSpreitzer** [comment]
/remove-lifecycle rotten
Still not fixed.
