### ISSUE TITLE
Missing rewrite-tag-filter plugin in fluentd-elasticsearch image

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes#69343]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Container "gcr.io/google-containers/fluentd-elasticsearch" is missing the following fluentd plugin: fluent-plugin-rewrite-tag-filter

**What you expected to happen**:
To find the plugin inside the image

**How to reproduce it (as minimally and precisely as possible)**:
```
# docker run -it --rm gcr.io/google-containers/fluentd-elasticsearch:v2.3.1 bash -c "gem list" | grep fluent-plugin
fluent-plugin-detect-exceptions (0.0.11)
fluent-plugin-elasticsearch (2.11.5)
fluent-plugin-kubernetes_metadata_filter (2.0.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.0.1)
fluent-plugin-systemd (1.0.1)
```

**Comment by mapdegree** [comment]
Would be great to include, an essential plugin
