### ISSUE TITLE
Rename services controller to loadbalancers controller

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kubernetes#69341]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

It seems like [services controller](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/service) was built with the intent that it would be a generic controller for all things related to services. Today (and for the last 2 years) its only purpose has been to manage Services of `type: LoadBalancer` using a cloud provider interface. To avoid confusion we should rename services controller to something more specific that better represents what it does. I propose something like loadbalancers controller. 

/sig network
/sig cloud-provider

**Comment by andrewsykim** [comment]
cc @bowei @thockin for any sig-network inputs here

**Comment by bowei** [comment]
sgtm (for me)

**Comment by cmluciano** [comment]
+1

**Comment by andrewsykim** [comment]
Thanks for the feedback everyone, @d-nishi has started work on this :)

**Comment by d-nishi** [comment]
ack.

**Comment by andrewsykim** [comment]
/assign @aoxn  

(already discussed with Nishi about assigning this to someone else)

**Comment by andrewsykim** [comment]
/close 

In https://github.com/kubernetes/kubernetes/pull/70109 we agreed that trying to change the service account name was not worth the benefit of renaming the controller. I would like to revalidate doing this in the future though.
