### ISSUE TITLE
Pause image is still using manifest-tool

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69358]
We need to remove the manifest-tool usage from k/k

https://github.com/kubernetes/kubernetes/search?q=manifest-tool&unscoped_q=manifest-tool

cc @mkumatag

**Comment by AnitaNayak** [comment]
Created one PR https://github.com/kubernetes/kubernetes/pull/85393. Please review @mkumatag .

**Comment by tanjunchen** [comment]
@dims 
see https://github.com/kubernetes/kubernetes/pull/88139
