### ISSUE TITLE
[sig-apps] Daemon set [Serial] should not update pod when spec was updated and update strategy is OnDelete

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#69356]
DaemonSet upgrades and downgrades have been failing since 9/25.  

Dashboard: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

Sample Failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1803

This test failure will block 1.13 beta, so please let's fix it before then.  Thanks!

/sig apps
/kind failing-test
/priority important-soon

**Comment by mortent** [comment]
I'm investigating this.
It is related to the change here: #68754. Still figuring out the actual impact and how to fix it.

**Comment by jberkus** [comment]
cc

@bradhoekstra

@thockin 

@bboreham

**Comment by AishSundar** [comment]
FWIW there's one more related test failure - https://github.com/kubernetes/kubernetes/issues/67903

**Comment by bradhoekstra** [comment]
This is also being discussed in this issue: #69445

**Comment by bradhoekstra** [comment]
Any opinions on whether the suggestion by @kow3ns [here](https://github.com/kubernetes/kubernetes/issues/69445#issuecomment-430840508) is the correct approach for fixing this?

**Comment by jberkus** [comment]
I'm escalating this issue to critical-urgent.  

At this point, not resolving this is keeping us from verifying the upgrade tests.  Because the Daemonsets have been failing for weeks, at this point we don't know what other upgrade test job failures that may be masking, and whether any of the other test flakes are related to the Daemonset failure.  This needs to be resolved, ASAP.

/priority critical-urgent

**Comment by AishSundar** [comment]
@jberkus https://github.com/kubernetes/kubernetes/pull/69988 which just merged claims to fix this issue. lets watch for the next run.

**Comment by nikopen** [comment]
DaemonSet tests passed on run 1842, seems to have been fixed: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master

if it doesn't pop up again -

/close
