### ISSUE TITLE
CSI: races in CSISkipAttach tests

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#69367]
This is somewhat related to #68261.

[CSISkipAttach tests](https://github.com/kubernetes/kubernetes/blob/860d3cb32c2b52836e1acbacb564698cbaeaacb4/test/e2e/storage/csi_volumes.go#L124) do these things:

1.
    1. Create CSIDriver CRD (in BeforeEach).
    2. (Optionally) create CSIDriver instance.
    3. Create a pod and check that VolumeAttachment was (not) created.
2. 
    1. Delete pod
    2. Delete CSIDriver instance
    3. Delete CSIDriver CRD (!!!)

What happens in A/D controller (and in kubelet too):

a. Kubelet and A/D controller create informer on CSIDriver. When the CRD does not exists, it tries periodically every second until the CRD is created.
b. When creating a pod, A/D controller looks into the informer cache if it has CSIDriver for that volume. If not, it creates VolumeAttachment.

Thing is that A/D controller (and kubelet) informer does **not** react to CSIDriver CRD deletion. It keeps watching the old CSIDriver CRD and it won't get events when new CRD and its CRs are created. So A/D controller still sees the CSIDriver created by the first test.

**How to reproduce it (as minimally and precisely as possible)**:
With #69331 merger, run the cluster:

```
RUNTIME_CONFIG= ALLOW_PRIVILEGED=1 FEATURE_GATES="BlockVolume=true,MountPropagation=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true"  hack/local-up-cluster.sh -O
```

Run e2e tests:
```
go run hack/e2e.go -- --provider=local --test --test_args="--ginkgo.focus=CSI.attach.test.using.HostPath.driver"
```

In addition, the test does not give kubelet/A/DController enough time to get a newly created CSIDriver, so it's racy even if CSIDriver CRD was installed only once.

**Comment by jsafrane** [comment]
/sig storage
/kind bug

@davidz627 @pohly @saad-ali @msau42 @lpabon @vladimirvivien 
(this tagging gets annoying, can we get @kubernetes/sig-storage-csi group?)

**Comment by jsafrane** [comment]
One simple way out of this in 1.12 (and 1.12 only) would be to remove CSIDriver informer from CSI volume plugin. The plugin would GET CSIDriver instance from API server every time it needs it. This way, it has always fresh value, regardless if the CRD was deleted in the meantime or not. It will solve #68261 too.

For 1.13, I would suggest that CSIDriver CRD **must** be installed by something when the cluster starts. It can't be removed, otherwise the CSI volume plugin stops working, like we observe now in this issue. 
The volume plugin will create the informer as it is now, i.e. in `plugin.Init`. Any CSI volume plugin operation that needs the informer (i.e. CSIDriver instances) will **fail** if the informer has not been synced (i.e. CRD does not exists). We expect that the "CRD installer" will deploy the CRD quickly enough so kubelet and A/D controller will fail only for a short time. Note that only CSI volume plugin will fail, all other volume plugins will work fine.

**Comment by msau42** [comment]
For 1.13, I think the plan is to install CRD via a controller.  But will that controller be able to run and install before all the other components come up?

**Comment by davidz627** [comment]
Does this help fix the issue https://github.com/kubernetes/kubernetes/pull/69349?

Removed deletion of CRD so all tests will use the same one, presumably.

**Comment by msau42** [comment]
@saad-ali @davidz627 and I had a discussion. To summarize, there are multiple issues going on:

1. Test deletes the CRD definition, but the informer is getting the old object.
    * We should investigate further if there could be a bug in CRD informer that doesn't handle CRD definition deletion, or is it just a race condition with the test?
    * #69349 might workaround this in the e2e test by not deleting the CRD definition.  However I still think there is an issue:
    * Assuming that informer does the right thing, there could still be a race condition in the test because the DriverName is the same for all test cases, and CSI CRD objects are not namespaced.  How can we guarantee that when the next test case runs, AD controller and kubelet informers have deleted the old driver objects from their cache?  I think for the purposes of our tests, and to be able to run tests in parallel, we should either:
        * Create the driver once at the beginning of the suite instead of once per test case
        * Create the driver with unique names for every test case.  This may interfere eventually with some plugin-level validation like attach limits
2. This is a core CRD, so we should require that the CRD is installed before we try to use it. https://github.com/kubernetes/features/issues/615 is tracking that effort
    * We should properly detect static kubelet configuration, so we can move informer initialization back to plugin Init()
    * We should wait for HasSynced in the init as well, re #68261   
        * This has the consequence of failing kubelet initialization and AD controller initialization until the CRD is installed
        * If we don't want the above failure, then we need to check for HasSynced every time we access the informer

**Comment by jsafrane** [comment]
> Does this help fix the issue #69349?

YES!

> Test deletes the CRD definition, but the informer is getting the old object.
We should investigate further if there could be a bug in CRD informer that doesn't handle CRD definition deletion, or is it just a race condition with the test?

It's both, sort of.
* CSIDriver informer won't catch up when CRD is deleted and created again. This is fixed by #69349.
* Even with #69349, the test does not wait until kubelet / A/D controller gets newly created CSIDriver from its informer. The test creates CSIDriver, then it creates roles and bindings and runs the driver itself. Only only after that it runs a pod that needs the CSIDriver instance synced in CSI volume plugin informer in A/D controller. That gives the informer enough time to get the event that CSIDriver was created, at least in my local-up-cluster environment. I'm afraid it's inevitably flaky when A/D controller gets busy from some reason.

Now we fixed the test. Won't users have the same problem? I hope they won't delete CRDs.

>  I think for the purposes of our tests, and to be able to run tests in parallel, we should either:
> * Create the driver once at the beginning of the suite instead of once per test case
> * Create the driver with unique names for every test case. This may interfere eventually with some plugin-level validation like attach limits

I like the second bullet. Each SkipAttach test run hostpath driver with a different (or missing) CSIDriver instances. Now they must run with [Serial]. If the driver name was configurable / random, it could run the tests in parallel.

Which reminds me, I still need a CSI driver to test that kubelet passes pod information in NodePublish. We don't have e2e test for that yet. This driver could be more configurable than GCE or hostpath.

**Comment by jsafrane** [comment]
>  We should wait for HasSynced in the init as well, re #68261
> * This has the consequence of failing kubelet initialization and AD controller initialization until the CRD is installed
> * If we don't want the above failure, then we need to check for HasSynced every time we access the informer

I think the volume plugin should work somehow (just without CSI volume plugin?) when the CSIDriver is missing during startup. It should recover when CSIDriver CRD is created. Expectation is that it's created quickly enough so users won't notice. And this can be relatively easily achieved by checking informer.HasSynced().

**Comment by msau42** [comment]
I'm more in favor of only starting the driver once at the beginning of the test suite.  In most circumstances, a driver is not going to be dynamically changing it's capabilities.  It's only these skip attach tests which are using the hostpath driver as a mock (feels more like integration tests than e2e tests), and it would be better for the skip attach test to use a unique driver name for each test case.

**Comment by msau42** [comment]
> CSIDriver informer won't catch up when CRD is deleted and created again

Can @kubernetes/sig-api-machinery-bugs help investigate this and see if there's an issue in the informer logic or is this intended behavior?

**Comment by liggitt** [comment]
>> CSIDriver informer won't catch up when CRD is deleted and created again
>
> Can @kubernetes/sig-api-machinery-bugs help investigate this and see if there's an issue in the informer logic or is this intended behavior?

cc @sttts 

I expected deletion of a CRD to:
* trigger deletion of all instances (which should propagate delete events for those instances)
* once instances are deleted and the CRD is removed, the handler would also be removed, dropping any watchers

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:
> I'm more in favor of only starting the driver once at the beginning of
> the test suite.

But then the driver would also get started when the E2E test suite gets
invoked in a way that never runs the tests that need the driver. The
alternative would be to start the driver on demand, but that becomes
harder to synchronize because ginkgo might run the tests which need the
driver in different processes in parallel (unless we restrict the test
to running serially).

**Comment by msau42** [comment]
Another alternative: don't do driver setup as part of the e2e test.  Expect the csi driver to be installed as part of cluster/environment bringup.  Each CSI plugin vendor can import these test cases as a library, but they need to handle the environment setup in their own repo.

In the core e2e tests, we can still keep testing mock drivers like hostpath, but it needs to generate a unique plugin name (and everything else that depends on the plugin name like socket path, etc) for every test case.

**Comment by jsafrane** [comment]
I filled PR for CSI mock driver to have configurable name, so each test can have its own csi driver not colliding with any other test. This will help to parallelize skip attach tests. It won't help with GCE, where I agree that the driver could be installed once per test run.

**Comment by jsafrane** [comment]
Here's the PR: https://github.com/kubernetes-csi/csi-test/pull/122

**Comment by jsafrane** [comment]
And I tested that it really helps, at least in SkipAttach tests: https://github.com/kubernetes/kubernetes/pull/69459 (it does not work, because kubernetes-csi/csi-test#122 was not merged yet).

**Comment by pohly** [comment]
@jsafrane A different implementation for making SkipAttach parallel is in https://github.com/kubernetes/kubernetes/pull/69868 - the main focus there was on deployment on drivers from manifests, but because it does that with renaming, the SkipAttach tests no longer has to run sequentially without changing anything in the test itself.

**Comment by jsafrane** [comment]
@pohly, thanks for for heads up. Indeed, #69868 seems to help. I hope it gets merged soon.

/hold
In favor of #69868

**Comment by jsafrane** [comment]
/close

#69868 looks fine.
