### ISSUE TITLE
Kubectl top nodes/pods not working(I am new to K8's)

### ISSUE THREAD

**Issue by yakuza-m** [kubernetes/kubernetes#69360]
I have installed the latest version of kubectl(1.12) kubeadm kubernetes-cni kubelet
@kubernetes/sig-contributor-experience-
/sig Autoscaling
/sig api-machinery 
/sig autoscaling
 /sig cluster-lifecycle 
 /sig instrumentation 
/sig scalability
also, my machine is Ubuntu 16.04

when I do kubectl top node I'm getting
error: metrics not available yet

also
the output of

kubectl get deployment -n kube-system metrics-server -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "1"
creationTimestamp: 2018-10-01T08:07:33Z
generation: 1
labels:
k8s-app: metrics-server
name: metrics-server
namespace: kube-system
resourceVersion: "9507"
selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/metrics-server
uid: 0d00d390-c551-11e8-990b-005056b604df
spec:
progressDeadlineSeconds: 2147483647
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
k8s-app: metrics-server
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
type: RollingUpdate
template:
metadata:
creationTimestamp: null
labels:
k8s-app: metrics-server
name: metrics-server
spec:
containers:
- image: k8s.gcr.io/metrics-server-amd64:v0.3.0
imagePullPolicy: Always
name: metrics-server
resources: {}
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
- mountPath: /tmp
name: tmp-dir
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
serviceAccount: metrics-server
serviceAccountName: metrics-server
terminationGracePeriodSeconds: 30
volumes:
- emptyDir: {}
name: tmp-dir
status:
availableReplicas: 1
conditions:

lastTransitionTime: 2018-10-01T08:07:33Z
lastUpdateTime: 2018-10-01T08:07:33Z
message: Deployment has minimum availability.
reason: MinimumReplicasAvailable
status: "True"
type: Available
observedGeneration: 1
readyReplicas: 1
replicas: 1
updatedReplicas: 1

**Comment by lavalamp** [comment]
Sorry, but this isn't a general support forum. I'd try slack, stackoverflow, users mailing lists.

I suspect something is not right with the networking connectivity between apiserver and the metrics apiserver, but it's hard to say more than that.
