### ISSUE TITLE
Move CSI RBAC Role definitions from kubernetes/kubernetes to external repos

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#69379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
RBAC Roles for external CSI components (external-provisioner, external-attacher, etc.) are defined in https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L462 and pre-installed on k8s

**What you expected to happen**:
https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-423636593:

> 1. We should use manifest yamls instead of bootstrapped roles or roles in code (1) (3) (https://github.com/kubernetes/kubernetes/pull/68821#issuecomment-423252660)
> 2. We should deprecate the bootstrapped cluster roles ASAP (3) (1) (https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-422834929)
> 2. Cluster Role names should be unique, potentially even tagging UUID's onto the end of the names when creating from manifests (2) (1)
> 3. Ideally some sort of sync/import of the manifests between the external repo (source of truth) and the test manifest (4)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by msau42** [comment]
@pohly can you update the latest status on this, and also reference any prs already merged or in-flight?

**Comment by pohly** [comment]
The builtin rules are still there, but are going to be declared as "deprecated" in the 1.13 release notes and instead external RBAC definitions are getting used (see https://github.com/kubernetes/kubernetes/pull/69868).

Updating all those external RBAC definitions is in progress. Some upstream repos have them already, some don't (external-snapshotter). I also found (a bit late unfortunately) that the existing rules don't pass kubectl validation. I now have the following PRs pending:
- https://github.com/kubernetes-csi/external-snapshotter/pull/53
- https://github.com/kubernetes-csi/external-attacher/pull/87
- https://github.com/kubernetes-csi/external-provisioner/pull/163

This blocks updating the kubernetes-csi/docs.

**Comment by AishSundar** [comment]
@marpaia for the appropriate Release notes updates for this change.

@pohly we are nearing Code slush (11/9) and Code freeze (11/16) pretty rapidly. Do you think all the 3 pending PRs and Docs can be wrangled by then? Also if you want this to be in 1.13, plz update the priority to important-soon for it to be mergeable once in code slush.

**Comment by msau42** [comment]
@AishSundar the remaining tasks are being done outside kubernetes core. All kubernetes core work has been completed.

**Comment by nikopen** [comment]
@AishSundar The three PRs mentioned above have been merged outside k/k, so this has been done for tracking purposes. Closing this.

/close

@pohly I suppose kubernetes-csi/docs can be updated now ^^

@marpaia re:release notes, see above post and https://github.com/kubernetes/kubernetes/pull/69868 just to be sure
