### ISSUE TITLE
CSI volume plugin test improvements

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/kubernetes#69374]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

While working on #69371 we found a couple of issues in the tests of the CSI volume plugin:

- [ ] The `RegistrationHandler.RegisterPlugin` seems to be untested
- [ ] The `csiPlugin.Init` seems to be untested
- [ ] Implementation pollutes global state ([CSI drivers store](https://github.com/kubernetes/kubernetes/blob/c1ad6e961a3083e109e35da1f60c85adfbbe70ce/pkg/volume/csi/csi_plugin.go#L100) and [node info manager](https://github.com/kubernetes/kubernetes/blob/c1ad6e961a3083e109e35da1f60c85adfbbe70ce/pkg/volume/csi/csi_plugin.go#L102), for example) - which prevents tests from running in isolation/in parallel. This is not 100% a test improvement (i.e. it's change in the source), but we're noting it here as part of backfilling tests/ improving test coverage.
- [ ] `csiDriverClient.NodeGetCapabilities` seems to be untested
- [ ] Maybe move the `fakeCsiDriverClient` into the `fake` package
  - [ ] Check if we can/want to use something like counterfeiter to generate the fakes
  - [ ] make the fakes `go generatable` (might mean, we need to introduce the counterfeiter binary as a test dependency)

What are your thoughts / opinions?

/cc @davidz627 
/cc @saad-ali 
/cc @vladimirvivien
/cc @mariantalla 
/cc @flangewad
/sig storage
/area test

**Comment by msau42** [comment]
I think it is a good idea to refactor into a struct, get rid of the global PluginHandler, and make initialization of structs more explicit. See https://github.com/kubernetes/kubernetes/pull/68597/files#r218978749 for one possible issue of having this global.

**Comment by hoegaarden** [comment]
@msau42 

We had a go on removing the global state [over here](https://github.com/kubernetes/kubernetes/pull/69462/commits/e4be764a1495e3d24e94f94964a8dbbb66947f5b). Two things we are a bit worried about:
- The `CSIPlugin` needs to be exported
- In [kubelet.go](https://github.com/kubernetes/kubernetes/pull/69462/commits/e4be764a1495e3d24e94f94964a8dbbb66947f5b#diff-bf28da68f62a8df6e99e447c4351122dR1383) we need this type assertion

Do you have any input on how we could make that better?

**Comment by benmoss** [comment]
I think he meant to link to [this commit](https://github.com/pivotal-k8s/kubernetes/commit/4383737cf072266720d97a34d2cab5bdb259bbcd)

**Comment by hoegaarden** [comment]
Thanks, Ben. I updated the links in the [comment above](https://github.com/kubernetes/kubernetes/issues/69374#issuecomment-430301632).

**Comment by verult** [comment]
One idea to improve the abstraction and get rid of the type assertion in kubelet.go is to have a PluginHandler interface shared between the CSI and device plugin handlers, something like this:

```go
type PluginHandlerInterface interface {
    HandleRegistration(...) // matches type pluginwatcher.PluginHandler
}
```

then have `csiPlugin` implement this method, and also include a factory method:

```go
func NewCSIPluginHandler(volumePluginMgr) PluginHandlerInterface {
    return volumePluginMgr.FindPluginByName(csi.PluginName)
}
```

and add something equivalent to the device plugin handler.

**Comment by hoegaarden** [comment]
/remove-lifecycle stale

xref: https://github.com/kubernetes/kubernetes/pull/74966
