### ISSUE TITLE
Staging update bot appears to be borked for k8s.io/metrics

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#69390]
If you look at the releases for k8s.io/metrics, there's a release https://github.com/kubernetes/metrics/releases/tag/kubernetes-1.12.0-invalid, which doesn't seem to actually correspond to the state of the deps as of 1.12 (there appear to be commits missing that are presenting in the staging dir of the actual k8s 1.12 release).

@kubernetes/sig-api-machinery-misc are you the ones that maintain this?
@nikhita @sttts this seems like it may be vaguely related to #69214

**Comment by nikhita** [comment]
@DirectXMan12 it's the same problem as #69214. @sttts and I are looking into this. :+1: 

This is
/sig release
/area release-infra

/remove-sig api-machinery

**Comment by nikhita** [comment]
Going to close this in favour of #69214 since it's the same underlying issue.

/close
