### ISSUE TITLE
Node doesn't get deleted after being terminated in AWS (1.12 only)

### ISSUE THREAD

**Issue by dadux** [kubernetes/kubernetes#69409]
/kind bug

**What happened**:
After upgrading 1.11.1 -> 1.12.0 , when a node gets terminated in AWS, the controller-manager doesn't delete the node in the API. 
This has lead to several side effect for us : 
* pods don't get GC
* Prometheus alerts firing because 100 of nodes are in the NotReady state for a long period

**What you expected to happen**:
kube-controller-manager deletes the node when it stops reporting, after checking with the cloud provider.

**How to reproduce it (as minimally and precisely as possible)**:
Looking at the code, I believe this is what introduced the behaviour change : 
https://github.com/kubernetes/kubernetes/issues/58635 - https://github.com/kubernetes/kubernetes/pull/60009

The node gets tainted with `node.cloudprovider.kubernetes.io/shutdown:NoSchedule` because it's in a Terminated state. But it doesn't get removed because it still "exists" in the cloud provider.

The behaviour is probably correct for a shutdown node, but in AWS a terminated node can't be restarted so there's no good reason to keep it there ?

**Environment**:
- Kubernetes version : 1.2.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS

(sorry for the all the sigs, not sure who it belongs to)
/sig aws
/sig cloud-provider
/sig cluster-lifecycle

**Comment by zetaab** [comment]
as I see it should delete node if instance is in terminated state

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L1364

**Comment by dadux** [comment]
I might be wrong, but I think that part of the code never gets executed once the node is tainted : 
https://github.com/kubernetes/kubernetes/blob/0ed33881dc4355495f623c6f22e7dd0b7632b7c0/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L774

**Comment by zetaab** [comment]
@dadux good finding. So https://github.com/kubernetes/kubernetes/blob/v1.12.0/pkg/cloudprovider/providers/aws/aws.go#L1398 we should remove terminated state from this row. Then it does not add shutdown taint if node is terminated - instead it will delete node.

**Comment by leakingtapan** [comment]
I had the same issue. After I scale down my worker node instance number from 3 to 1. One node is stuck in `NotReady` status and never got deleted. However, one interesting thing is one of the other node is removed successfully. @dadux do you see similar behavior too?

**Comment by dadux** [comment]
@zetaab - can we make sure this gets cherry picked for 1.12 releases ? I think we already missed the cut for 1.12.2

**Comment by zetaab** [comment]
@dadux https://github.com/kubernetes/kubernetes/pull/70166
