### ISSUE TITLE
Kubernetes bug with Statefulsets

### ISSUE THREAD

**Issue by VChug** [kubernetes/kubernetes#69400]
**Is this a BUG REPORT or FEATURE REQUEST?**:
yes

**What happened**:
https://github.com/kubernetes/kubernetes/issues/58347
This issue still exist on kubernetes 1.9.7

The app with statefulsets on restart creates multiple controllerrevisions on kubernetes, which doesn't let the app restart again and gives an error or attaching the volume to its pvc.

Although the workaround is 👍 

```
kubectl get controllerrevisions
```

You will see number of revisions created by kubernetes, delete them all

```
kubectl delete controllerrevisions <name_of_controlrevisions>
```

The pod for the statefulsets will automatically restarts and comes onto the running state.

**Comment by VChug** [comment]
@gerred

**Comment by foxish** [comment]
@kubernetes/sig-apps-bugs

**Comment by mortent** [comment]
Have you tried to see if this is still a problem on the latest version? And would you be able to provide a minimal example that reproduces the behavior?
