### ISSUE TITLE
Sample network policy is very unstable

### ISSUE THREAD

**Issue by marcin-kasinski** [kubernetes/kubernetes#69455]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network

**What happened**:

Based on article https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/
I've created small test:

	while true
	do
	 wget --spider --timeout=1 nginx
	 sleep 1
	done

When running without netpol and --labels="access=true" I'm getting pure output:

```
...
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
...
```

With netpol and --labels="access=true" I get:

```
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
wget: download timed out
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
Connecting to nginx (10.96.250.126:80)
wget: download timed out


```

**What you expected to happen**:

I was expected to see the same output with and without netpol.
I wasn't expected to see so many timeouts.

**How to reproduce it (as minimally and precisely as possible)**:

Test with script above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:

Baremetal and vagrant

- OS (e.g. from /etc/os-release):

Ubuntu 16.04.5 LTS

- Kernel (e.g. `uname -a`):

`Linux k8smaster 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:

vagrant and manual installation.

- Others:

Networking:
`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
`

**Comment by danwinship** [comment]
NetworkPolicy implementation is controlled entirely by your network plugin, not by Kubernetes itself. If you are still having problems, you should file a bug against the network plugin you are using.
/close
