### ISSUE TITLE
MutatingWebHook injecting initContainers results in a malformed deployment

### ISSUE THREAD

**Issue by davidbalazs** [kubernetes/kubernetes#69467]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I am using a MutatingWebHook to decorate incoming deployments and statefulSets with containers, initContainers and volumes. The deployments and statefulSets are part of Helm charts.

I have a specific constraint in that one of the initContainers, let's call it init-container-injected that my mutatingWebHook is injecting must be the first one in the list, so that it is the first one that runs. This means that if the original deployment has some initContainers in the list (let's assume it has init-container-1), the mutatingWebHook has to replace the whole list of initContainers with a new one that has the following order: 

1. init-container-injected
2. init-container-1

However, everything works fine, except when init-container-1 has custom commands and args, but init-container-injected does not have a custom command or args defined. In this situation after the mutatingWebhook does its job, I am seeing a weird resulting list of containers: the command and args from init-container-1 are merged with init-container-injected, so that now init-container-injected has the command and args of init-container-1 as follows:

1. init-container-injected (with command and args from init-container-1)
2. init-container-1 (with the right command and args)

Example of  init-container-injected that has to be injected by the mutatingWebHook:
```     
            - name: init-container-injected
              image: "<path-to-image>"
```

Example of  init-container-1 that is present on the deployment and has a custom command and args:
```      
            - name: init-container-1
              image: "<path-to-image>"
              command: ["printenv"]
              args: ["HOSTNAME", "KUBERNETES_PORT"]
```

After my deployment is installed in the Kubernetes cluster (and the mutatingWebhook intercepted it), its initContainers looks like follows:
```    
            - name: init-container-injected #this is inserted by the mutatingWebHook and it needs to be the first one in the list
              image: "<path-to-image>
              command: ["printenv"] # this is the command from init-container-1 and it shouldn't be here
              args: ["HOSTNAME", "KUBERNETES_PORT"] # these are the args from init-container-1 and it shouldn't be here
            - name: init-container-1
              image: "<path-to-image>"
              command: ["printenv"]
              args: ["HOSTNAME", "KUBERNETES_PORT"]
```

**What you expected to happen**:
I would expect that my initContainers list would have the following format:

1. init-container-injected (with no command or args)
2. init-container-1 (with the right command and args)

More explicit list of initContainers that I expect on my deployment:
```    
            - name: init-container-injected
              image: "<path-to-image>
            - name: init-container-1
              image: "<path-to-image>"
              command: ["printenv"]
              args: ["HOSTNAME", "KUBERNETES_PORT"]
```

**How to reproduce it (as minimally and precisely as possible)**:
Using a MutatingWebHook that intercepts deployments and statefulSets and decorates them with a initContainer that needs to be the first one in the list and it has no command or args defined, try to deploy a deployment or a statefulSet that has one init container with a custom command and some args.  

**Anything else we need to know?**:
It was reproducible in kubernetes 1.9.11, 1.9.10, but it was working as expected in 1.9.7 and 1.9.8
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by caesarxuchao** [comment]
Can you try the patch on a deployment directly, does that work?
Can you try it on a 1.10 or 1.11 server?

**Comment by liggitt** [comment]
can you also provide the patch you are returning from your webhook?

**Comment by liggitt** [comment]
closing due to lack of information. feel free to reopen with reproducer information

/close
