### ISSUE TITLE
Application communication is failing due to DNS services are getting restarted within Kubernetes cluster

### ISSUE THREAD

**Issue by sandeshs1987** [kubernetes/kubernetes#69468]
Hello ,
Its a new Project and in Deployment Phase. We are using ACS Azure Service, while checking we observed that, PODs are not able to communicating with each other over the overlay network. 
We tried to create service and try to access the service application, but still we able to access the application.
Requesting you help us to address the issue asap.

Thanks
Sandesh S
9967917419
Email : sandesh.sonavane@ril.com

**Comment by shubheksha** [comment]
@sandeshs1987, you might have better luck asking in one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures). 
/triage support

**Comment by justaugustus** [comment]
As Shubheksha mentioned, this should be a MSFT support issue.
/close
