### ISSUE TITLE
Tracking Issue: Two consistently failing upgrade tests: fix or remove?

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#69475]
Master-upgrade tests are supposed to be blocking for the release.  However, two of the upgrade tests have been consistently failing for at least the last 3 weeks.  At this point, we need to decide whether these are going to get fixed, or removed from the sig-release-master-upgrade dashboard as non-blocking.  Possibly we should just stop running them.

Those tests are:

* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new

Have these tests *ever* passed? 

/kind failing-test
/sig test-infrastructure
/sig release
/priority important-soon

cc:

@cjwagner 
@AishSundar 
@mohammedzee1000

**Comment by jberkus** [comment]
Yeah, it kind of looks like the 2nd test used to pass reasonably regularly, but that goes back to the beginning of our history.

**Comment by jberkus** [comment]
These tests appear to belong to sig-gcp, so cc'ing them here. I've already asked cluster-lifecycle and these aren't the upgrade tests they maintain.

/sig gcp

**Comment by jberkus** [comment]
These tests are still failing, increasing the timeout appears not to have helped at all.

See https://github.com/kubernetes/test-infra/issues/9802

What now?

**Comment by justinsb** [comment]
We've got signal :-)

Splitting into parallel tests & serial/disruptive tests gives us signal on each:

---
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new-parallel

That's broadly green except for the occasional flake on `[sig-network] Services should have session affinity work for LoadBalancer service with ESIPP on [Slow] [DisabledForLargeClusters]`

---
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new

This one takes longer, so we only have two runs so far, both of which flaked but on different tests :tada: 

`[sig-scheduling] SchedulerPriorities [Serial] Pod should be preferably scheduled to nodes which satisfy its limits`
`[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability`

**Comment by AishSundar** [comment]
This is cool. thanks @justinsb. May be we should split the tests out similarly for the [gce-new-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new) as well?

**Comment by AishSundar** [comment]
Ah I jus saw relevant discussion in https://github.com/kubernetes/test-infra/issues/9802#issuecomment-431111574

**Comment by justinsb** [comment]
Yes - thanks @AishSundar - splitting gce-new-master-upgrade-cluster-new also in https://github.com/kubernetes/test-infra/pull/9864  (I thought there were more, but haven't found one yet)

Generally looking into why particular tests are failing.  A lot of them seem to be failing because of the daemonset issue, being tracked in #69356

**Comment by AishSundar** [comment]
Thanks so much @justinsb for following through on this.

**Comment by AishSundar** [comment]
After all the splitting I see [gce-new-master-upgrade-cluster-new-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel), which runs slow tests in parallel, timeout similar to before after 15hrs. The others are all failing on misc tests as @jberkus indicated

**Comment by jberkus** [comment]
OK, we're down to a couple known issues causing these tests to fail, so there's no real value in a tracking issue.  

/close
