### ISSUE TITLE
Need peer-finder binary to be built for s390x.

### ISSUE THREAD

**Issue by Bindiy** [kubernetes/kubernetes#69472]
Hello,

Need peer-finder binary to be built for s390x arch. Please let me know if I can get the peer-finder binary for s390x or I have to build it, if yes then please provide the repo and instructions for the same.

**Comment by dims** [comment]
code is here:
https://github.com/kubernetes/kubernetes/tree/master/test/images/pets/peer-finder

I believe you can run `make all WHAT=pets/peer-finder` from `test/images` directory.

cc @mkumatag 

/close
