### ISSUE TITLE
AWS NLB TargetGroups suddenly fail healthcheck

### ISSUE THREAD

**Issue by chmking** [kubernetes/kubernetes#69476]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

This morning at 3PM UTC two NLBs simultaneously flagged member nodes of their TargetGroups as unhealthy and have not recovered. Both NLBs were targeting the same nodes on different ports.

- When creating a ELB pointing at the same node port health checks and requests are successful.
- When creating a new NLB with a new TG pointing at the same node ports also fails health checks.

**What you expected to happen**:

It is expected that NLBs would maintain health checks against all nodes in TG.
It is expected that failures would eventually recover.

**How to reproduce it (as minimally and precisely as possible)**:

This has not been reproduced locally.

**Anything else we need to know?**:

The NLBs were up for less than 24 hours before failing. During that time individual node health checks were failing periodically.

![screen shot 2018-10-05 at 1 26 15 pm](https://user-images.githubusercontent.com/1039324/46555973-63d59900-c8a2-11e8-82d9-9c025ae1119d.png)

**Environment**:
- Kubernetes version (use `kubectl version`):  1.10.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.4.121-k8s
- Install tools: kops 1.10.0
- Others:

**Comment by chmking** [comment]
@kubernetes/sig-aws-misc-bugs

**Comment by texmachina** [comment]
Same for me. If you check the ENI's tied to your NLB, I bet you don't have any Security Groups attached? That is what I am seeing. This is a problem I was thinking/hoping had been fixed, but no dice it seems.

https://github.com/kubernetes/kubernetes/issues/64148

**Comment by chmking** [comment]
Closing this as a duplication of issue: #64148
