### ISSUE TITLE
Kubelet generates a new CSR on start even if it has a valid certificate on disk

### ISSUE THREAD

**Issue by agunnerson-ibm** [kubernetes/kubernetes#69471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm testing the new `--rotate-server-certificates` option in kubernetes 1.12 and it seems that kubelet always requests the signing of a new CSR and tries to rotate the certificates when it is started. This is happening even though there's a valid (brand new) certificate on disk issued by kube-controller-manager.

From what I can tell, this is happening because kubelet implements `getTemplate` and `lastRequest` is set after a successful certificate rotation, but is never persisted to disk. If kubelet is restarted, then the last requested CSR is nil.

https://github.com/kubernetes/client-go/blob/9c81604894197dbfe4424c19193068dc5211db9d/util/certificate/certificate_manager.go#L274-L283

**What you expected to happen**:

Ideally, kubelet should only request the signing of a new CSR if it doesn't already have a serving certificate or it's about to expire.

**How to reproduce it (as minimally and precisely as possible)**:

* Restart a kubelet instance that had it's serving certificate issued by kube-controller-manager
* Check `kubectl get csr` and see that it requested the signing of a new CSR

**Anything else we need to know?**:

kubelet is being run with `--rotate-server-certificates`. `--cert-dir`, `--tls-cert-file`, and `--tls-private-key-file` are all omitted to use the default values.

The TLS bootstrapping for client certificates is currently not being used--just the bootstrapping for serving certificates.

**Environment**:
- Kubernetes version: v1.12.0 - built from source at the `v1.12.0` tag (0ed33881dc4355495f623c6f22e7dd0b7632b7c0)
- Cloud provider or hardware configuration: Bare metal
- OS: CentOS 7.5.1804
- Kernel: `3.10.0-862.14.4.el7.x86_64`
- Install tools: Custom RPMs built from this git repo with no additional patches
- Others: `docker-1.13.1-75.git8633870.el7.centos.x86_64`

**Comment by agunnerson-ibm** [comment]
Not sure if this is the ideal fix, but I've patched it so that it compares the current CSR template to the last requested template only if it doesn't already match the current cert.

https://gist.github.com/agunnerson-ibm/20339f05709e3e5d6ff52e8f340f556c

**Comment by liggitt** [comment]
@kubernetes/sig-auth-bugs

**Comment by liggitt** [comment]
cc @awly

**Comment by awly** [comment]
@agunnerson-ibm thanks for the proposed fix. I think it looks good. Could you send a PR?
We should also remove `lastRequest` entirely and only look at current cert and template. @liggitt does that sound reasonable?

**Comment by agunnerson-ibm** [comment]
@awly Sure thing, I'd be happy to do that.

**Comment by liggitt** [comment]
> We should also remove lastRequest entirely and only look at current cert and template. @liggitt does that sound reasonable?

I think that's probably ok, as long as it checks everything we include in the template *and* we consider a certificate missing anything we request to be cause for re-requesting another cert (an issuer couldn't choose to issue a cert that drops some SANs and us not request another cert)

left some comments in https://github.com/agunnerson-ibm/kubernetes/commit/7828edab3140d754367422df5bb9699b17df3bc8

**Comment by mikedanese** [comment]
This regression is a frequent flyer. I'd love to see an integration that would catch this (but that shouldn't block a fix).

**Comment by agunnerson-ibm** [comment]
@liggitt Thanks for the comments! Now that I have the CLA signed, I'll address those and submit a PR.

**Comment by agunnerson-ibm** [comment]
Just submitted the PR: https://github.com/kubernetes/kubernetes/pull/69991
