### ISSUE TITLE
typecheck should be a standalone utility

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69474]
typecheck currently lives here:
https://github.com/kubernetes/kubernetes/tree/master/test/typecheck

It would be great to move it out of the main k/k repository and use it as a command line tool for any repository. I've tried with cloud-provider-openstack and it seems to work well.

**Comment by nikhita** [comment]
> It would be great to move it out of the main k/k repository and use it as a command line tool for any repository. 

Maybe a good place for this would be https://github.com/kubernetes/repo-infra

/remove-lifecycle stale

**Comment by dims** [comment]
@rmmh do we want to do this?
