### ISSUE TITLE
Labeling SecretVolumeSource

### ISSUE THREAD

**Issue by Kuunniku** [kubernetes/kubernetes#69479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Secrets created as part of deployments(SecretVolumeSource) cannot be labeled.

**What you expected to happen**:
Labeling the deployment should have labeled all the associated objects that it created. Or deleting the deployment should have removed the objects that it created.

**How to reproduce it (as minimally and precisely as possible)**:
Including the secret attribute in volumes in deployment creates a secret, which does not get labeled with the deployment label. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Linux 16.04 LTS
- Kernel (e.g. `uname -a`): 
Linux ubuntu 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by Kuunniku** [comment]
@kubernetes/sig-Architecture-bug

**Comment by liggitt** [comment]
> Including the secret attribute in volumes in deployment creates a secret

This isn't accurate. A deployment can reference a Secret object and indicate it should be mounted into the pods created from the deployment, but it does not create the secret object in the API. 

Labeling a deployment does not propagate labels to referenced resources (secrets, configmaps, pvcs, etc)

/close
