### ISSUE TITLE
rbac default permission for oidc users

### ISSUE THREAD

**Issue by navi86** [kubernetes/kubernetes#69483]
Hello,
I have created dashboard and granted dashboard service accountant permissions to list all namespaces without access permissions in namespaces. Then I granted AD user permissions to manage some namespaces.

@kubernetes/sig-auth-bugs
@kubernetes/sig-auth-feature-requests
**What happened**:
User has only his permissions in dashboard.
**What you expected to happen**:
I expected that user would have his own permissions with dashboard service account permissions 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: bare metal

**Comment by liggitt** [comment]
can you provide more details about the following:
* what command or manifest did you use to grant permission to list namespaces?
* what command or manifest did you use to grant AD user permission?
* was the dashboard configured to use service account credentials or user credentials to access the API?
* how did you log into the dashboard

**Comment by navi86** [comment]
_what command or manifest did you use to grant permission to list namespaces?_
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-list-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

_role for AD user to access namespace:_
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
#  namespace: mynamespace
  name: namespace-editor
rules:
- apiGroups: [""]
  resources: ["pods","pods/attach","pods/exec","pods/portforward","pods/proxy"]
  verbs: ["create","delete","update","get","watch","list","patch","deletecollection"]
- apiGroups: [""]
  resources: ["configmaps","endpoints","persistentvolumeclaims","secrets","serviceaccounts","services","services/proxy"]
  verbs: ["create","delete","update","get","watch","list","patch","deletecollection"]
- apiGroups: [""]
  resources: ["bindings","events","limitranges","namespaces/status","pods/log","pods/status","replicationcontrollers/status","resourcequotas","resourcequotas/status"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments","deployments/rollback","deployments/scale","replicasets","replicasets/scale","statefulsets"]
  verbs: ["create","delete","update","get","watch","list","patch","deletecollection"]
- apiGroups: ["extensions"]
  resources: ["daemonsets","deployments","deployments/rollback","deployments/scale","ingresses","replicasets","replicasets/scale","replicationcontrollers/scale"]
  verbs: ["create","delete","update","get","watch","list","patch","deletecollection"]
 
_what command or manifest did you use to grant AD user permission?_
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-testers-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: username@domain.com

_how did you log into the dashboard_
Using keycloak proxy

**Comment by liggitt** [comment]
> User has only his permissions in dashboard

sorry, just read the description in more detail. this is working as intended. logging into the dashboard lets you access the API with your own permissions, not get the dashboard service account's permissions.

/close
