### ISSUE TITLE
Unclear Network Policy's "policyTypes" definition in spec documentation

### ISSUE THREAD

**Issue by walterdolce** [kubernetes/kubernetes#69490]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug report
/kind bug

**What happened**: I was reading the documentation for `NetworkPolicy` as defined [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#networkpolicyspec-v1-networking-k8s-io)

**What you expected to happen**: To have clear documentation

**How to reproduce it (as minimally and precisely as possible)**: Read the following, as seen in the 1.12 docs:
> `policyTypes ` List of rule types that the NetworkPolicy relates to. Valid options are Ingress, Egress, or Ingress,Egress. [...]

**Anything else we need to know?**: Nope

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by walterdolce** [comment]
@kubernetes/sig-docs-bugs

**Comment by walterdolce** [comment]
Is it a case whereby only `- Ingress` can be specified as `policyTypes`, or only `- Egress`, or *both* `- Ingress\n-Egress` (note the `\n`) ?
If that's the case, do you think the following would make it clearer?
> Valid options are Ingress (only one array item), Egress (only one array item), or both Ingress and Egress (two individual array items).

**Comment by matthewfischer** [comment]
It is confusing to have commas used for English grammar and array element delineation in the same sentence. What about simply this?

> Valid options are "Ingress", "Egress", or "Ingress,Egress".

**Comment by mattjmcnaughton** [comment]
@matthewfischer sounds like a great fix! Putting out a quick pr with this change now :)
