### ISSUE TITLE
Investigate to support local storage capacity reporting with the "Volume attach limits" feature

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#69502]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

For dynamic provisioning of local storage, we'll need a place to report available capacity of each nodes, so that scheduler can be aware of that, and tell if a node is available to provision local volumes of a pod.

We've got an internal draft of the design. It is considered a general one, storages can report capacity per storageclass per topology dimension (e.g. per AZ, per region, and for local storage per node).
But on the another hand, we're concerned if it's overengineering, as in fact we don't have a strong use case of capacity reporting for other storage types.

Recently, we are looking into a new feature for max attachable capacity per node(an extension on existing Volume attach limits feature).
This is meant for cloud volumes types that restrict total attachable capacity, we'd like to see if local storage could piggy back on it. I think the behavior (of reporting capacity in node status) has a natural affinity with local storage.

**Anything else we need to know?**:

One concern with this approach is that it will only work for local storage. If in the future we end up needing to support others, then it will need to be a completely different solution.
Personally I think it acceptable,  as we mainly make use of an existing feature, rather than introduce a new feature that only works on local storage.

/sig storage

**Comment by lichuqiang** [comment]
The main pain point is that currently the "max volume limits" feature is designed to count volumes across storageclasses, but for capacity reporting, we need to support multiple storage classes.

An approach I can think of is to extend the scheduler to take both the limit key with & without storageclass into account:
i.e. "prefix-dirvername-storageclass" and "prefix-dirvername".
And it depends on the driver side to decide which to limit: for storages like gce, we'll only see limitation with the key of "prefix-dirvername" in node status; and for local storage it would be "prefix-dirvername-storageclass".
The other with no limitation reported would be considered unlimited in predicates.
This way,  we can support the "max volume limits" in two modes: per storageclass/per storage type

/cc @msau42 @saad-ali @jsafrane @gnufied for thoughts

**Comment by gnufied** [comment]
So as I understand - same driver running on same node can have different total capacity depending on storageclass? So, we want total capacity on node and storage class granularity. I think, there is a desire to make capacity reporting (including volume limits) more fluid rather than string based API of key/value that exists today. 

I think, we need to talk to scheduler folks about as well about how such a limit can be expressed. cc @bsalamat

**Comment by mlmhl** [comment]
Are these capacities (including volume limits) still reported by kubelet? If so, I think we also need to talk to sig-node folks to determine the exactly format of these capacities.
