### ISSUE TITLE
Vagrant : how to tell kubernetes cluster to pick specific network interface while initializing 

### ISSUE THREAD

**Issue by irfanjs** [kubernetes/kubernetes#69509]
Hello,
I have setup vagrant and the virtualbox hyper-visor. deployed 2 Linux boxes . one for kubernetes master and other kubernetes worker. 
using vagrantfile, setup the boxes and all network interfaces along with docker and kubeadm 

kubernetes cluster initialized successfully. 
however, IP address assignment is not working properly. in vagrantfile, i have used the "private network" and "dhcp"
the IP address gets assigned properly ...  but both the nodes have same IP address for enp0s3 interface. please see below for worker node.

> enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
>         inet6 fe80::a00:27ff:fe3a:75b  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:3a:07:5b  txqueuelen 1000  (Ethernet)
>         RX packets 133  bytes 12062 (11.7 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 146  bytes 12396 (12.1 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 172.28.128.4  netmask 255.255.255.0  broadcast 172.28.128.255
>         inet6 fe80::a00:27ff:fe7d:c6cc  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:7d:c6:cc  txqueuelen 1000  (Ethernet)
>         RX packets 397  bytes 46572 (45.4 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 246  bytes 38039 (37.1 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 

please see below for master node 

> enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
>         inet6 fe80::a00:27ff:fe3a:75b  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:3a:07:5b  txqueuelen 1000  (Ethernet)
>         RX packets 160  bytes 22695 (22.1 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 183  bytes 15610 (15.2 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 172.28.128.3  netmask 255.255.255.0  broadcast 172.28.128.255
>         inet6 fe80::a00:27ff:fe46:44fa  prefixlen 64  scopeid 0x20<link>
>         ether 08:00:27:46:44:fa  txqueuelen 1000  (Ethernet)
>         RX packets 629  bytes 61210 (59.7 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 370  bytes 81189 (79.2 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 

now while registering the worker node, it is taking 10.0.2.15 IP address and not the one starts from 172.

how i tell kubernetes cluster to use 172 IP address range and register on that instead of 10 IP address range ??
I am using weave for the POD network 

Please suggest

**Comment by shubheksha** [comment]
@irfanjs, GitHub is not the right place for support requests unfortunately. Please try asking in one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures).
/triage support

**Comment by neolit123** [comment]
^ +1

/close

**Comment by irfanjs** [comment]
no. i think lets not close the issue . i have seen certain google posts and see that kubernetes well works with vagrant. however, i checked on the slack kubernetes channel and did some modifications in the script. still it is failing 
here is the command : 

`kubeadm init --apiserver-cert-extra-sans=$IPADDR  --node-name $NODENAME --pod-network-cidr 172.28.0.0/12`

please suggest 

/open
