### ISSUE TITLE
Error message: "failed to get azure cloud in GetVolumeLimits" in bare-metal setup after upgrade to 1.12.1

### ISSUE THREAD

**Issue by turchanov** [kubernetes/kubernetes#69503]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
After upgrade of Kubernetes 1.11.3 to 1.12.1 via kubeadm in bare-metal setup I see these errors in kubelet logs:

> Oct  8 12:27:50 node2 kubelet: E1008 12:27:50.766520   21094 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: node2.mydomain
> Oct  8 12:28:00 node2 kubelet: E1008 12:28:00.790762   21094 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: node2.mydomain
> etc...

**What you expected to happen**:
Since this is a bare-metal setup I expect no messages concerning Azure cloud

**How to reproduce it (as minimally and precisely as possible)**:
Do an upgrade from 1.11.3 to 1.12.1

**Anything else we need to know?**:
kubelet-1.12.1-2.x86_64.rpm was downloaded from https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
bare-metal
- OS (e.g. from /etc/os-release):
Oracle Linux Server 7.4
- Kernel (e.g. `uname -a`):
4.9.62
- Install tools:
- Others:

**Comment by turchanov** [comment]
Lines from kubelet log which say that no cloud provider were specified (that is a bare-metal setup):
> Oct  8 12:22:19 node2 kubelet: I1008 12:22:19.737225   21094 server.go:408] Version: v1.12.1
> Oct  8 12:22:19 node2 kubelet: I1008 12:22:19.737419   21094 plugins.go:99] No cloud provider specified.
..
> Oct  8 12:22:19 node2 kubelet: E1008 12:22:19.997668   21094 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: node2.mydomain

**Comment by aleks-mariusz** [comment]
have the same issue related to the azure.. also a bare-metal cluster.. 

these messages are flooding my centralized logging elasticsearch (though they aren't really problematic more than being an annoyance).  

i also upgraded from 1.11.3 to 1.12.1 on a 3-master HA set up.  

i also noted (perhaps worthy of a separate issue) that the two of my three control-planes that are showing the azure error also previously had been having cert authority errors from the api-server container, when having used kubeadm upgrade.. 

(on the second two control plane systems, with the issue)
```
E1008 14:04:33.464628       1 memcache.go:125] couldn't get current server API group list; will keep using cached value. (Get https://10.12.100.131:6443/api?timeout=32s: x509: certificate signed by unknown authority)
E1008 14:04:33.466195       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.ClusterRoleBinding: Get https://10.12.100.131:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E1008 14:04:33.468747       1 reflector.go:134] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:130: Failed to list *storage.StorageClass: Get https://10.12.100.131:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E1008 14:04:33.469702       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Role: Get https://10.12.100.131:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E1008 14:04:33.471513       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Namespace: Get https://10.12.100.131:6443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
E1008 14:04:33.472066       1 reflector.go:134] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:130: Failed to list *core.ResourceQuota: Get https://10.12.100.131:6443/api/v1/resourcequotas?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
F1008 14:04:33.474640       1 controller.go:148] Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://10.12.100.131:6443/api/v1/services: x509: certificate signed by unknown authority
```

(and on the first control without the issue)
```
I1008 14:07:29.856362       1 log.go:172] http: TLS handshake error from 10.12.100.132:57406: read tcp 10.12.100.131:6443->10.12.100.132:57406: read: connection reset by peer
I1008 14:08:01.045550       1 log.go:172] http: TLS handshake error from 10.12.100.133:60006: remote error: tls: bad certificate
```
(and i needed to kubeadm reset and then kubeadm init all over again with 1.12.1 on the 2nd two control-plane nodes).. 

the first control-plane node that didn't need to do a reset/init didn't have the azure errors (nor the cert errors).  so i kind of suspect it might not be an kubeadm upgrade issue but a general issue going from 1.11.3 to 1.12.1 ?

**Comment by suquant** [comment]
Same problems +1

**Comment by MarkDeckert** [comment]
Same problem on brand new bm cluster built with kubeadm and latest 1alpha3 config based off of customized kubeadm config print-default example

**Comment by jicki** [comment]
Same problems +1

**Comment by jicki** [comment]
Oct  9 11:11:32 localhost kubelet: E1009 11:11:32.966179    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:11:42 localhost kubelet: E1009 11:11:42.976961    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:11:52 localhost kubelet: E1009 11:11:52.983544    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:02 localhost kubelet: E1009 11:12:02.989690    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:12 localhost kubelet: E1009 11:12:12.995558    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:23 localhost kubelet: E1009 11:12:23.001558    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:33 localhost kubelet: E1009 11:12:33.009515    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:43 localhost kubelet: E1009 11:12:43.016327    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:12:53 localhost kubelet: E1009 11:12:53.022558    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1
Oct  9 11:13:03 localhost kubelet: E1009 11:13:03.028967    3342 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: kubernetes-1

**Comment by andyzhangx** [comment]
@turchanov how often did you hit this error log:
```
azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: node2.mydomain
```
I am planning to make this log as `glog.V(3).Infof`, is that ok for you? Usually V(2) is the default info(see [example here](https://github.com/andyzhangx/demo/blob/master/acs-engine/deployment/etc/systemd/system/kubelet.service#L23)) log for k8s on azure
https://github.com/kubernetes/kubernetes/blob/a34123d9c3e933b662bf0a3cb2c427f774154b01/pkg/volume/azure_dd/azure_dd.go#L147

I am not sure what the default info log by kubeadmin installation.

**Comment by turchanov** [comment]
> @turchanov how often did you hit this error log:

It is logged every 10 seconds. 

> I am planning to make this log as `glog.V(3).Infof`, is that ok for you? Usually V(2) is the default info(see example here) log for k8s on azure.

I disagree. At least previous incarnation of GetVolumeLimits in version 1.11.3 :
https://github.com/kubernetes/kubernetes/blob/a4529464e4629c21224b3d52edfe0ea91b072862/pkg/volume/azure_dd/azure_dd.go#L119~L138

would have logged an error "No cloudprovider present". Which I didn't see in kubelet log. In fact, I didn't see any message in kubelet logs with 'azure' substring at all. I think it means that AzureDataDisk plugin was not instantiated at all in 1.11.3. 

So the question is: why azuredd is instantiated now in 1.12.1 in bare-metal setup (that is without cloud provider)? Do you mind checking this idea?

(Besides your method of lowering message priority won't work as I said this is a bare-metal setup where kubelet systemd unit file has no --v option at all
https://github.com/kubernetes/kubernetes/blob/4ed3216f3ec431b140b1d899130a69fc671678f4/build/rpms/10-kubeadm.conf#L11
)

**Comment by andyzhangx** [comment]
@turchanov That's because [Dynamic volume limits](https://kubernetes.io/docs/concepts/storage/storage-limits/) feature reaches beta in v1.12, in v1.11.3, even the code is there, it won't be invoked since `Dynamic volume limits` feature is still alpha in v1.11

**Comment by andyzhangx** [comment]
And in v1.12, aws, gce, and azure disk plugins are all loaded, take aws ebs for example, it will return error directly:
https://github.com/kubernetes/kubernetes/blob/f9acfd8e384488d2216b18196152dcb7b3cc92d8/pkg/volume/awsebs/aws_ebs.go#L111

And logging as V(4):
https://github.com/kubernetes/kubernetes/blob/f9acfd8e384488d2216b18196152dcb7b3cc92d8/pkg/kubelet/nodestatus/setters.go#L775

I suppose V(4) logs won't display in logs. Let me make the same change as aws and gce.

**Comment by bertinatto** [comment]
https://github.com/kubernetes/kubernetes/pull/69302 also tries to address this error.

**Comment by D-PENG** [comment]
The same mistake, I also encountered

> [root@kube-master cert]#  kubectl get nodes -owide
NAME           STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
172.16.16.13   Ready    <none>   5m27s   v1.12.1   172.16.16.13   <none>        CentOS Linux 7 (Core)   4.18.12-1.el7.elrepo.x86_64   docker://18.6.0



> failed to get azure cloud in GetVolumeLimits, plugin.host: 172.16.16.13
failed to get azure cloud in GetVolumeLimits, plugin.host: 172.16.16.13
failed to get azure cloud in GetVolumeLimits, plugin.host: 172.16.16.13
failed to get azure cloud in GetVolumeLimits, plugin.host: 172.16.16.13

**Comment by andyzhangx** [comment]
@D-PENG I have cherry picked the fix to v1.12

**Comment by cedricroijakkers** [comment]
I understand that the feature Node-specific Volume Limits has now reached beta in 1.12, but for those of us running Kubernetes on-premises, this log error is pretty useless. In fact, I would even want to disable this plugin alltogether, since it will never be used on-prem. Is there a way to stop the plugin from loading, or in the very least make sure the log does not appear? Right now, it is polluting the system log file quite a lot.

**Comment by turchanov** [comment]
I second that. That was the key message of my bug report. That is we must not even instantiate cloud-specific plugins if no cloud provider is configured.

**Comment by marciopuga** [comment]
I'm having exactly the same problem, doing an installation from scratch on DigitalOcean

`kubelet[14662]: E1019 05:38:51.569290   14662 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host: 9master`

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jodok** [comment]
+1

**Comment by lostz** [comment]
+1

**Comment by bragonznx** [comment]
Hi
I have the same issue.
It would be really nice to know how to disable this error message that floods the logs for no reason.

**Comment by andyzhangx** [comment]
disable `AttachVolumeLimit` in controller plane should work:
"--feature-gates=AttachVolumeLimit=false"

**Comment by stpabhi** [comment]
@andyzhangx I have tried "--feature-gates=AttachVolumeLimit=false" and it's not working. I still see messages 

kubelet[39526]: E1024 22:51:02.459065   39526 azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host:

**Comment by rlljorge** [comment]
I have the same problem here..,  azure_dd.go:147] failed to get azure cloud in GetVolumeLimits, plugin.host:

**Comment by reiroldan** [comment]
+1 same case here

**Comment by wufsmail** [comment]
how to resole?

**Comment by wufsmail** [comment]
how to resolve?

**Comment by Tabrizian** [comment]
Will this be disabled by default in the next release?

**Comment by andyzhangx** [comment]
It's already fixed in v1.12.2 and v1.13.0.
@gnufied do you know how to disable `AttachVolumeLimit` in kubelet in v1.12? Would add `--feature-gates=AttachVolumeLimit=false` in kubelet command arguments work?

**Comment by cedricroijakkers** [comment]
I haven't updated to 1.12.2 yet (still on 1.12.1) but just to confirm, disabling that feature works.

For those that are also running on CentOS and/or RHEL, just to the following:

Edit file `/etc/sysconfig/kubelet` on your master server (control plane), and add the following:

`KUBELET_EXTRA_ARGS=--feature-gates=AttachVolumeLimit=false`

If you already have extra arguments in there, just add this one at the end of the line. Then restart kubelet on your master server:

`sudo systemctl restart kubelet`

**Comment by gnufied** [comment]
@andyzhangx  Yes that will work.

**Comment by rlljorge** [comment]
Update tho 1.12.2 resolve for me

Em qui, 1 de nov de 2018 9:22 PM, Abhilash Pallerlamudi <
notifications@github.com escreveu:

**Comment by donxan** [comment]
add follow line in your kubelet.servic,like this:
`[root@master2 ~]# vim /etc/systemd/system/kubelet.service`
```

[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
#--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest
ExecStart=/opt/kube/bin/kubelet \
  --address=192.168.2.10 \
  --allow-privileged=true \
  --anonymous-auth=false \
  --authentication-token-webhook \
  --authorization-mode=Webhook \
  --client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --cluster-dns=10.68.0.2 \
  --cluster-domain=cluster.local. \
  --cni-bin-dir=/opt/kube/bin \
  --cni-conf-dir=/etc/cni/net.d \
  --fail-swap-on=false \
  --feature-gates=AttachVolumeLimit=false \
  --hairpin-mode hairpin-veth \
  --hostname-override=192.168.2.10 \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --max-pods=110 \
  --network-plugin=cni \
  --pod-infra-container-image=mirrorgooglecontainers/pause-amd64:3.1 \
  --register-node=true \
  --root-dir=/var/lib/kubelet \
  --tls-cert-file=/etc/kubernetes/ssl/kubelet.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kubelet-key.pem \
  --v=2
...
```
[root@master2 ~]# systemctl daemon-reload
[root@master2 ~]# sudo systemctl restart kubelet
then it's ok

**Comment by sharkymcdongles** [comment]
So to get rid of a bug we should disable an entire feature?

https://kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits

Says it is supported by Azure-Disk. Why isn't node reporting the limit? It is getting instance metadata okay as all my nodes are tagged with SKU. Being that SKU determines attach limit as well, I do not understand why this cannot be made working?

I am on 1.14 in Azure on Ubuntu.

**Comment by andyzhangx** [comment]
@sharkymcdongles how do you deploy k8s on Azure? To get volume limit, kubelet on agent node needs azure identity, e.g. service principal, usually it's under `/etc/kubernetes/azure.json` file

**Comment by sharkymcdongles** [comment]
I deployed with kubespray. I have cloud_config set as such:

KUBELET_CLOUDPROVIDER="--cloud-provider=azure --cloud-config=/etc/kubernetes/cloud_config"

Service principle is set in cloud_config file.

**Comment by sharkymcdongles** [comment]
I triple checked and location was misspelled on some of the nodes for the cloud provider. Thanks!

**Comment by andyzhangx** [comment]
@sharkymcdongles the get vm size list call depends on location, so now it works?

**Comment by sharkymcdongles** [comment]
Yes it does. Thanks!
