### ISSUE TITLE
When the NAME of nodes is hostname, metrics-server cannot obtain node data.

### ISSUE THREAD

**Issue by D-PENG** [kubernetes/kubernetes#69510]
The name of the nodes of k8s is the same as the Linux hostname,Because DNS cannot resolve the hostname, metrics-server cannot get the data. I think so.
> ```
> E1008 06:51:25.170819 1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:kube-master: unable to fetch metrics from Kubelet kube-master (kube-master): Get http://kube-master:10255/stats/summary/: dial tcp: lookup kube-master on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-backup: unable to fetch metrics from Kubelet kube-backup (kube-backup): Get http://kube-backup:10255/stats/summary/: dial tcp: lookup kube-backup on 10.254.0.2:53: no such host, unable to fully scrape metrics from source kubelet_summary:kube-worker: unable to fetch metrics from Kubelet kube-worker (kube-worker): Get http://kube-worker:10255/stats/summary/: dial tcp: lookup kube-worker on 10.254.0.2:53: no such host]
> ```

**Comment by D-PENG** [comment]
When the name of the node is changed to IP, it is normal.
> [root@kube-master metrics-server]# kubectl top nodes
> NAME             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
> 192.168.72.111   135m         13%    801Mi           42%       
> 192.168.72.112   113m         11%    697Mi           37%       
> 192.168.72.113   100m         10%    286Mi           15%       
> [root@kube-master metrics-server]#

**Comment by liggitt** [comment]
@kubernetes/sig-autoscaling-bugs is the metrics server using the node name directly as a network host or is it looking up the reported addresses on the Node object?

**Comment by bskiba** [comment]
@kubernetes/sig-instrumentation-bugs

**Comment by D-PENG** [comment]
@liggitt The name of the nodes of k8s is the same as the Linux hostname,Because DNS cannot resolve the hostname, metrics-server cannot get the data. I think so.

**Comment by liggitt** [comment]
> @liggitt The name of the nodes of k8s is the same as the Linux hostname

that is not always the case. the addresses recorded on the node (node.status.addresses) are what should be used for network connections.

**Comment by brancz** [comment]
Which version of the metrics-server is this? Looking at [default address priority](https://github.com/kubernetes-incubator/metrics-server/blob/6cd52610db69d662b3b7890b73df82b3b3601ab3/pkg/sources/summary/addrs.go#L28:2) and the [address resolver](https://github.com/kubernetes-incubator/metrics-server/blob/6cd52610db69d662b3b7890b73df82b3b3601ab3/pkg/sources/summary/addrs.go#L56) which is used to [gather all metrics sources](https://github.com/kubernetes-incubator/metrics-server/blob/6cd52610db69d662b3b7890b73df82b3b3601ab3/pkg/sources/summary/summary.go#L257)  when [collecting](https://github.com/kubernetes-incubator/metrics-server/blob/6cd52610db69d662b3b7890b73df82b3b3601ab3/pkg/sources/manager.go#L89), this all looks correct to me and should be choosing the node hostname first.

Could you share the entire node object of the node that is failing to be scraped?

cc @DirectXMan12

**Comment by aleksandra-malinowska** [comment]
cc @x13n

**Comment by D-PENG** [comment]
@brancz 
k8s v1.12.0/v1.12.1
coredns v1.2.2
metrics-server v0.3.1
addon-resizer v1.8.3

[root@kube-master]# kubectl get --raw "/apis/metrics.k8s.io/v1beta1" | jq .
> {
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nodes",
      "singularName": "",
      "namespaced": false,
      "kind": "NodeMetrics",
      "verbs": [
        "get",
        "list"
      ]
    },
    {
      "name": "pods",
      "singularName": "",
      "namespaced": true,
      "kind": "PodMetrics",
      "verbs": [
        "get",
        "list"
      ]
    }
  ]
}

[root@kube-master ~]# kubectl top pods -n kube-system
> W1017 10:40:36.189212   28195 top_pod.go:263] Metrics not available for pod kube-system/coredns-779ffd89bd-k4jzp, age: 31m40.18920062s
error: Metrics not available for pod kube-system/coredns-779ffd89bd-k4jzp, age: 31m40.18920062s

**Comment by DirectXMan12** [comment]
@D-PENG I'd expect to see more errors if metrics-server couldn't resolve addresses.  Is there anything else in the logs?

**Comment by D-PENG** [comment]
> @D-PENG I'd expect to see more errors if metrics-server couldn't resolve addresses. Is there anything else in the logs?

Kubernetes has been upgraded to version 1.12.2 and the problem has not been relapse. 1.12.2 is normal   
>```
>[root@kube-master ~]# kubectl get nodes -o wide
>NAME          STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
>kube-master   Ready    master   5m26s   v1.12.2   172.16.16.13   <none>        CentOS Linux 7 (Core)   4.4.162-1.el7.elrepo.x86_64   docker://18.6.1
>[root@kube-master ~]# 
>[root@kube-master ~]# kubectl top nodes
>NAME          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
>kube-master   99m          9%     1465Mi          77%       
>[root@kube-master ~]# 
>[root@kube-master ~]# kubectl logs -f metrics-server-v0.3.1-75d9447679-lhkrk  -n kube-system -c metrics-server 
>I1108 01:46:27.121617       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
>[restful] 2018/11/08 01:46:32 log.go:33: [restful/swagger] listing is available at https://:443/swaggerapi
>[restful] 2018/11/08 01:46:32 log.go:33: [restful/swagger] https://:443/swaggerui/ is mapped to folder /swagger-ui/
>I1108 01:46:32.829288       1 serve.go:96] Serving securely on [::]:443
>```

**Comment by DirectXMan12** [comment]
ok, I thank we can close this, then

/close
