### ISSUE TITLE
i am unable to join my nodes to the master node

### ISSUE THREAD

**Issue by MohanNagendraKumar** [kubernetes/kubernetes#69514]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MohanNagendraKumar** [comment]
Run 'modprobe -- ' to load missing kernel modules;
2. Provide the missing builtin kernel ipvs support

[discovery] Trying to connect to API Server "192.168.68.32:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.68.32:6443"
[discovery] Failed to request cluster info, will try again: [Get https://192.168.68.32:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.68.32:6443: connect: no route to host]   . 

this is the error i am getting when i run a join command

**Comment by shubheksha** [comment]
@MohanNagendraKumar, GitHub is not the right place for support requests unfortunately. Please try asking in one of the support channels.
/triage support

**Comment by MohanNagendraKumar** [comment]
thanq @shubheksha for ur suggestion
