### ISSUE TITLE
i am unable to join the nodes to the master

### ISSUE THREAD

**Issue by MohanNagendraKumar** [kubernetes/kubernetes#69513]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
/close
please add only a single sentence in the title and fill the issue template correctly.
then re-open the issue..

thanks.
