### ISSUE TITLE
Pod stops processing the PVC's "watch of *v1.PersistentVolumeClaim ended with: The resourceVersion for the provided watch is too old."

### ISSUE THREAD

**Issue by Nilesh20** [kubernetes/kubernetes#69521]
I am using dynamic volume provisioning concept of Kubernetes and I am running one pod which is processing the PVC's but sometimes it suddenly stop to process PVC's and i checked the log i found following statements.

What is the meaning of this statements and why it is stopping the working of pod , if i restarts the pod then issue gets resolved , but i dont want to restart the pod everytime.

error creating filesystem: FILESYSTEM_MIN_CAPACITY The requested filesystem size is less than the minimum filesystem size: ".

Failed to watch *v1.Node: Get https://<ip>:443/api/v1/nodes?resourceVersion=98676317&timeoutSeconds=354&watch=true: dial tcp <ip>:443: getsockopt: connection refused

Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:default:" cannot list persistentvolumeclaims at the cluster scope: User "system:serviceaccount:default" cannot list all persistentvolumeclaims in the cluster

watch of *v1.PersistentVolume ended with: The resourceVersion for the provided watch is too old.
watch of *v1.StorageClass ended with: The resourceVersion for the provided watch is too old.
watch of *v1.PersistentVolumeClaim ended with: The resourceVersion for the provided watch is too old.
watch of *v1.ConfigMap ended with: The resourceVersion for the provided watch is too old.

**Comment by liggitt** [comment]
if re-establishing a watch returns the "version is too old" error, the caller must re-list and obtain a current resourceVersion to start a watch from.

what method are you using to list/watch? the client-go examples that use a client to build a listwatcher, then use the listwatcher to build an informer (which handles re-list/re-watch for you if needed) are a good starting point: https://github.com/kubernetes/client-go/blob/master/examples/workqueue/main.go#L164-L195

**Comment by Nilesh20** [comment]
I am using the external provisioner and in that there is controller which list and watch the PVC's 
function = NewProvisionController()

controller.claimSource = &cache.ListWatch{
		ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
			return client.CoreV1().PersistentVolumeClaims(v1.NamespaceAll).List(options)
		},
		WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
			return client.CoreV1().PersistentVolumeClaims(v1.NamespaceAll).Watch(options)
		},
	}
In my case provisioner is running and processing the PVC's but after some times it stop processing the PVC's and keep them into pending state.

**Comment by shraderdm** [comment]
I'm running into this issue as well. Has this already been resolved?

**Comment by mbach04** [comment]
+1 Seeing this in 5 fresh OCP 3.11 deployments. The `glusterfs-registry` storage class is failing as a result of this.
