### ISSUE TITLE
Makefile.generated_files:322: recipe for target '_output/bin/deepcopy-gen' failed

### ISSUE THREAD

**Issue by liukaii** [kubernetes/kubernetes#69523]
`root@ubuntu:/home/lk/GO/src/k8s.io/kubernetes# make
+++ [1008 20:13:44] Building the toolchain targets:
   k8s.io/kubernetes/hack/cmd/teststale
   k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
   k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF
  -D address
    	set data segment address (default -1)
  -E entry
    	set entry symbol name
  -H type
       set header type
  -I linker
    	use linker as ELF dynamic linker
  -L directory
    	add specified directory to library path
  -R quantum
    	set address rounding quantum (default -1)
  -T address
    	set text segment address (default -1)
  -V	print version and exit
  -X definition
    	add string value definition of the form importpath.name=value
  -a	disassemble output
  -buildid id
    	record id as Go toolchain build id
  -buildmode mode
    	set build mode
  -c	dump call graph
  -cpuprofile file
    	write cpu profile to file
  -d	disable dynamic executable
  -debugtramp int
    	debug trampolines
  -dumpdep
    	dump symbol dependency graph
  -extar string
    	archive program for buildmode=c-archive
  -extld linker
    	use linker when linking in external mode
  -extldflags flags
    	pass flags to external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -h	halt on error
  -installsuffix suffix
    	set package directory suffix
  -k symbol
    	set field tracking symbol
  -libgcc string
    	compiler support lib for internal linking; use "none" to disable
  -linkmode mode
    	set link mode
  -linkshared
    	link against installed Go shared libraries
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	enable MSan interface
  -n	dump symbol table
  -o file
    	write output to file
  -pluginpath string
    	full path name for plugin
  -r path
    	set the ELF dynamic linker search path to dir1:dir2:...
  -race
    	enable race detector
  -s	disable symbol table
  -tmpdir directory
    	use directory for temporary files
  -u	reject unsafe packages
  -v	print link trace
  -w	disable DWARF generation
k8s.io/kubernetes/hack/cmd/teststale
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF
  -D address
    	set data segment address (default -1)
  -E entry
    	set entry symbol name
  -H type
    	set header type
  -I linker
    	use linker as ELF dynamic linker
  -L directory
    	add specified directory to library path
  -R quantum
    	set address rounding quantum (default -1)
  -T address
    	set text segment address (default -1)
  -V	print version and exit
  -X definition
    	add string value definition of the form importpath.name=value
  -a	disassemble output
  -buildid id
    	record id as Go toolchain build id
  -buildmode mode
    	set build mode
  -c	dump call graph
  -cpuprofile file
    	write cpu profile to file
  -d	disable dynamic executable
  -debugtramp int
    	debug trampolines
  -dumpdep
    	dump symbol dependency graph
  -extar string
    	archive program for buildmode=c-archive
  -extld linker
    	use linker when linking in external mode
  -extldflags flags
    	pass flags to external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -h	halt on error
  -installsuffix suffix
    	set package directory suffix
  -k symbol
    	set field tracking symbol
  -libgcc string
    	compiler support lib for internal linking; use "none" to disable
  -linkmode mode
    	set link mode
  -linkshared
    	link against installed Go shared libraries
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	enable MSan interface
  -n	dump symbol table
  -o file
    	write output to file
  -pluginpath string
    	full path name for plugin
  -r path
    	set the ELF dynamic linker search path to dir1:dir2:...
  -race
    	enable race detector
  -s	disable symbol table
  -tmpdir directory
    	use directory for temporary files
  -u	reject unsafe packages
  -v	print link trace
  -w	disable DWARF generation

!!! [1008 20:13:44] Call tree:

!!! [1008 20:13:44]  1: /home/lk/GO/src/k8s.io/kubernetes/hack/lib/golang.sh:683 

kube::golang::build_kube_toolchain(...)

!!! [1008 20:13:44]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)

!!! [1008 20:13:44] Call tree:

!!! [1008 20:13:44]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)

Makefile.generated_files:322: recipe for target '_output/bin/deepcopy-gen' failed

make[1]: *** [_output/bin/deepcopy-gen] Error 1

Makefile:512: recipe for target 'generated_files' failed

make: *** [generated_files] Error 2
`
# kubernetes source code version 1.8.4 
# go version 1.11
How to solve this?

**Comment by neolit123** [comment]
cc @ixdy 
hm, seems like the old release is not buildable with the latest golang.
unless this is a user error of sorts.

/sig release
/kind bug

**Comment by liukaii** [comment]
@neolit123 
when I make with kubernetes1.9.4, it seems successful but still has some wrong message. 
`root@ubuntu:/home/lk/GO/src/k8s.io/kubernetes# make quick-release
+++ [1008 22:22:57] Verifying Prerequisites....
+++ [1008 22:22:57] Building Docker image kube-build:build-95d3909905-5-v1.9.3-1
+++ [1008 22:23:08] Creating data container kube-build-data-95d3909905-5-v1.9.3-1
+++ [1008 22:24:27] Syncing sources to container
+++ [1008 22:24:34] Running build command...
+++ [1008 22:25:02] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:25:02] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:25:03] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1008 22:25:09] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:25:09] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:25:09] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1008 22:25:13] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:25:13] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:25:13] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [1008 22:25:17] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:25:17] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:25:18] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/openapi-gen
+++ [1008 22:25:22] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:25:22] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:25:22] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    vendor/k8s.io/kube-aggregator
    vendor/k8s.io/apiextensions-apiserver
    plugin/cmd/kube-scheduler
    cluster/gce/gci/mounter
+++ [1008 22:28:54] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:28:55] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:28:55] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kubeadm
    cmd/kubelet
+++ [1008 22:29:05] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:29:05] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:29:05] Building go targets for linux/amd64:
    cmd/kubectl
+++ [1008 22:29:20] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:29:20] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:29:20] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [1008 22:30:31] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [1008 22:30:31] Generating bindata:
    test/e2e/generated/gobindata_util.go
~ ~/test/e2e/generated
~/test/e2e/generated
+++ [1008 22:30:32] Building go targets for linux/amd64:
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
+++ [1008 22:31:13] Syncing out of container
+++ [1008 22:31:45] Building tarball: src
+++ [1008 22:31:45] Building tarball: manifests
+++ [1008 22:31:45] Building tarball: salt
+++ [1008 22:31:45] Starting tarball: client linux-amd64
+++ [1008 22:31:45] Waiting on tarballs
+++ [1008 22:31:53] Building tarball: node linux-amd64
+++ [1008 22:31:53] Building tarball: server linux-amd64
+++ [1008 22:31:54] Starting docker build for image: cloud-controller-manager-amd64
+++ [1008 22:31:54] Starting docker build for image: kube-apiserver-amd64
+++ [1008 22:31:54] Starting docker build for image: kube-controller-manager-amd64
+++ [1008 22:31:54] Starting docker build for image: kube-scheduler-amd64
+++ [1008 22:31:54] Starting docker build for image: kube-aggregator-amd64
+++ [1008 22:31:54] Starting docker build for image: kube-proxy-amd64
invalid argument "gcr.io/google_containers/cloud-controller-manager:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
invalid argument "gcr.io/google_containers/kube-apiserver:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54] Call tree:
invalid argument "gcr.io/google_containers/kube-controller-manager:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
invalid argument "gcr.io/google_containers/kube-aggregator:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
invalid argument "gcr.io/google_containers/kube-proxy:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
invalid argument "gcr.io/google_containers/kube-scheduler:v1.9.4," for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [1008 22:31:54] previous Docker build failed
!!! [1008 22:31:54] Call tree:
!!! [1008 22:31:54]  1: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:220 kube::release::create_docker_images_for_server(...)
!!! [1008 22:31:54]  2: /home/lk/GO/src/k8s.io/kubernetes/build/lib/release.sh:91 kube::release::package_server_tarballs(...)
!!! [1008 22:31:54]  3: build/release.sh:45 kube::release::package_tarballs(...)
!!! [1008 22:32:06] previous tarball phase failed
Makefile:406: recipe for target 'quick-release' failed
make: *** [quick-release] Error 1
root@ubuntu:/home/lk/GO/src/k8s.io/kubernetes# go version
go version go1.11 linux/amd64
`
I am new to this and don't know how to solve this.

**Comment by ixdy** [comment]
Right, we pin go versions to kubernetes releases, so kubernetes 1.8 has only been validated with go1.8, and kubernetes 1.9 has only been validated with go1.9.

`make quick-release` should resolve this issue for you, though, since it uses the build container, which has a pinned version of go. It looks like you were getting an error message when building the containers at the end; what version of docker are you using?

As a side note, with the release of kubernetes 1.12, both kubernetes 1.8 and 1.9 have fallen out of the support window and will receive no additional patches or fixes.

**Comment by liukaii** [comment]
@ixdy Thank you for answering my question.Here is something about docker that  I am using.
`root@ubuntu:/home/lk/Downloads# docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false
`
Am I supposed to do something with docker?

**Comment by ixdy** [comment]
that seems like a pretty new version of docker, so that should work... have you tried building a more recently release of kubernetes (1.10 or later)?

**Comment by liukaii** [comment]
@ixdy        I used to build kubernetes1.12 and it works well. The version of kubeadm in master node is 1.9.4, so I try to build kubernetes1.9.4 when I want to change "kubelet" in slave node. Though it still has some error message, it can work well after changing "kubelet". Thank you very much!

**Comment by ixdy** [comment]
Kubernetes 1.9.4 is rather old (March 2018). I'm not sure what you mean by "version of kubeadm in master node" but it'd be good to update that.

**Comment by liukaii** [comment]
@ixdy Sorry, my English is poor. I will update it later.Thank you very much!

**Comment by dims** [comment]
/close

@liukaii please reopen when you are ready

**Comment by wwj-2017-1117** [comment]
Incompatible between golang-1.12 and golang-1.13 versions.
