### ISSUE TITLE
Is it OK to use single Cluster Name for multiple entries in admin.conf to access multiple masters without having master LB

### ISSUE THREAD

**Issue by ckurdekar** [kubernetes/kubernetes#69530]
@kubernetes/sig-multicluster
@kubernetes/sig-cluster-lifecycle

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
kind feature

**What happened**:
Usage of admin.conf for multi masters using multiple master entries with same cluster name.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Trying to access multi master (without load balancer) using admin.conf for POD deployment.
We are able to access masters(s) by placing all master IPs with having single cluster name. Somehow this works when one of master goes down, kubectl is able to switch to another master IP.
As we want to have only 1 logical logical cluster and without master LB, kubectl client should able to connect to masters (any one of master)

**Anything else we need to know?**:
Is it OK to use same Cluster Name for multiple entries in admin.conf to access multiple masters (Within single k8s cluster) without having master LB

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.0
- Cloud provider or hardware configuration:vmware
- OS (e.g. from /etc/os-release): RHEL 7.5
- Kernel (e.g. `uname -a`):3.10.0-862.2.3.el7.x86_64
- Install tools:
- Others:

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle 
/kind feature
/priority awaiting-more-evidence

any particular reason to not use a load balancer in front of the masters?

**Comment by neolit123** [comment]
closing the issue.
/close
