### ISSUE TITLE
Cardinality of admission web hook metrics is too high on clusters with lots of CRDs or admission controllers

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#69540]
Spun off from https://github.com/kubernetes/kubernetes/pull/55183

Webhook latency metrics grow O(M*N) with resources and admission controllers. On a large cluster with lots of CRDs this causes a significant amount of memory use and churn. On a smaller cluster with lots of admission controllers and CRDs, 75% of all apiserver prometheus metrics (38k series out of 46k series) were this metric.

The primary dimension that is arguably not useful is by resource type and sub resource, since the vast majority of these are not matched.  I think we should drop the resource and subresource latency tracking.  The extra fidelity is not worth the increased cost of tracking these metrics.

**Comment by smarterclayton** [comment]
/kind bug
@kubernetes/sig-api-machinery-bugs

**Comment by smarterclayton** [comment]
Most admission plugins track only one or two resource types, so tracking all of them is overkill.  Also, we're tracking all verbs and the vast majority of verbs get no calls.

**Comment by smarterclayton** [comment]
`apiserver_admission_controller_admission_latencies_seconds` is the impacted one.  I'm not even seeing step get called (but this is 1.11)

**Comment by lavalamp** [comment]
It should be O(N) with number of webhooks, I don't think it's necessary to break out by webhook *and* resource.

**Comment by jpbetz** [comment]
Okay, so we'll drop `group, version, resource, subresource` and `operation` labels from these metrics ([original design](https://docs.google.com/document/d/1rDRrC5MNI2An_FeYx8HAsmlQv1WThh9IBb3_shCTbJA/edit#))? I'll send out a PR if there are no objections.

**Comment by smarterclayton** [comment]
We could probably leave operation for now.  Operation is bounded.

**Comment by MHBauer** [comment]
/close
resolved by #69895
