### ISSUE TITLE
start kube-controller-manager err: unable to monitor quota for resource "extensions/v1beta1, Resource=networkpolicies"

### ISSUE THREAD

**Issue by Pingan2017** [kubernetes/kubernetes#69562]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
when starting kube-controller-manager, print err log:
`E1010 01:26:07.612718   20946 resource_quota_controller.go:170] initial monitor sync has error: couldn't start monitor for resource {"extensions" "v1beta1" "networkpolicies"}: unable to monitor quota for resource "extensions/v1beta1, Resource=networkpolicies"`

in code , no informers found for networkpolicies with extensions_v1beta1
https://github.com/kubernetes/kubernetes/blob/4ba5db087a2d7af5c04c99cb99e14ae74000fcbf/staging/src/k8s.io/client-go/informers/generic.go#L193-L203

should we need generic informer for this??
**What you expected to happen**:
no err 
**How to reproduce it (as minimally and precisely as possible)**:
start kube-controller-manager

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yuripastushenko** [comment]
We have same issue but with resource: prometheusrules
```
resource_quota_controller.go:173] initial monitor sync has error: [couldn't start monitor for resource {"monitoring.coreos.com" "v1" "prometheusrules"}: unable to monitor quota for resource "monitoring.coreos.com/v1, Resource=prometheusrules", couldn't start monitor for resource {"monitoring.coreos.com" "v1" "servicemonitors"}: unable to monitor quota for resource "monitoring.coreos.com/v1, Resource=servicemonitors", couldn't start monitor for resource {"monitoring.coreos.com" "v1" "prometheuses"}: unable to monitor quota for resource "monitoring.coreos.com/v1, Resource=prometheuses", couldn't start monitor for resource {"extensions" "v1beta1" "networkpolicies"}: unable to monitor quota for resource "extensions/v1beta1, Resource=networkpolicies", couldn't start monitor for resource {"monitoring.coreos.com" "v1" "alertmanagers"}: unable to monitor quota for resource "monitoring.coreos.com/v1, Resource=alertmanagers"]
```

**Comment by lovejoy** [comment]
same issue with tfjobs 
```E0321 12:02:44.346445  324154 resource_quota_controller.go:448] failed to sync resource monitors: couldn't start monitor for resource {"kubeflow.org" "v1alpha2" "tfjobs"}: unable to monitor quota for resource "kubeflow.org/v1alpha2, Resource=tfjobs"```
