### ISSUE TITLE
@kubernetes#How to launch aws loadbalancer for kubernetes cluster manually, is it possible to configure manually?

### ISSUE THREAD

**Issue by psultane-glisten** [kubernetes/kubernetes#69564]

**Comment by HagaiBarel** [comment]
Yep, it's possible, but you might want to rethink it as kubernetes isn't aware of it nor will it manage any of the settings regarding it. I wrote a blog post on the matter if you're interested, see here - https://medium.com/@hagaibarel/kubernetes-and-elbs-the-hard-way-c59a15779caf

**Comment by neolit123** [comment]
/sig aws
/triage support

probably best to ask at our support channels:
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

please close once resolved.
