### ISSUE TITLE
kubelet error getting node status: unauthorized

### ISSUE THREAD

**Issue by ricktbaker** [kubernetes/kubernetes#69576]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Setup new cluster in AWS EKS, with RBAC, checking all logs to verify all is good.  Nodes appear to be coming online and Ready, but I'm seeing the following errors for the kubelet service on the nodes.

```
service kubelet status

Oct 09 12:52:21 ip-172-26-0-213.ec2.internal kubelet[4226]: E1009 12:52:21.590612    4226 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "ip-172-26-0-213.ec2.internal": Unauthorized
Oct 09 13:13:24 ip-172-26-0-213.ec2.internal kubelet[4226]: E1009 13:13:24.141500    4226 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "ip-172-26-0-213.ec2.internal": Unauthorized
```

Have 3 nodes and seeing the same errors on all 3.

Appears it is coming from this line in kubelet_node_status.go

```
	node, err := kl.heartbeatClient.CoreV1().Nodes().Get(string(kl.nodeName), opts)
	if err != nil {
		return fmt.Errorf("error getting node %q: %v", kl.nodeName, err)
	}
```

From the workers I can execute get nodes using kubectl just fine:

```
    kubectl get --kubeconfig=/var/lib/kubelet/kubeconfig nodes
    NAME                           STATUS    ROLES     AGE       VERSION
    ip-172-26-0-58.ec2.internal    Ready     <none>    1h        v1.10.3
    ip-172-26-1-193.ec2.internal   Ready     <none>    1h        v1.10.3
```

**What you expected to happen**:

I'd expect the kubelet logs to not have this error.  Since the worker node can join the cluster it would appear that  I have the ClusterRoleBindings setup properly.

** Kubelet Version ***
```
kubelet --version
Kubernetes v1.10.3
```

/sig node

**Comment by liggitt** [comment]
unauthorized errors mean the credentials the kubelet is using are invalid. are there stale/expired client certificates in the kubelet certificate directory, and was the client-ca for the cluster rotated?

**Comment by ricktbaker** [comment]
@liggitt This is a brand new cluster in EKS.  I completely recreated last night just to double check everything.  Nodes come up as Ready in the cluster, I then tail the logs for the kubelet service and I can see logs of pods being scheduled but like clockwork, every 21 minutes I get the unauthorized error about "error getting node"

**Comment by liggitt** [comment]
That's an odd internal, especially to be a non-persistent error. Does it resolve itself after one occurrance without a kubelet restart? Do you know the duration of the client certificates issued to the kubelet?

 @awly, do you remember if there were improvements to client cert rotation in 1.11 or 1.12 that would explain a stale client cert used for kubelet heartbeat, which would resolve itself after a connection?

**Comment by ricktbaker** [comment]
Unsure on length of certificate.   I'd have to research a bit into EKS to find that out.

Doesn't resolve itself.  I've restarted the kubelet service several times, and the error persists.    It doesn't seem to be impacting anything from what I can tell.  The node stays in service, and pods continue to be scheduled as I add new services.  It's just a little concerning that this could lead to some issues that I'm not aware of.

**Comment by liggitt** [comment]
> the error persists

I meant does it persist at a 10-second interval (encountered at every heartbeat attempt) or at a 21-minute interval?

**Comment by ricktbaker** [comment]
Only at 21 minutes.  That's pretty much all I see in the logs except for when I add a new service and it gets scheduled to the node.

**Comment by awly** [comment]
@liggitt AFAIK EKS uses IAM authenticator for node auth. I'm not sure if it's only used to provision certs or always.
/sig aws

**Comment by taylan-insider** [comment]
Any updates here?

**Comment by szymonpk** [comment]
Looks like [it is 'normal' in EKS.](https://forums.aws.amazon.com/thread.jspa?threadID=291297)

**Comment by ricktbaker** [comment]
Was just going to come here and post that @szymonpk   Going to go ahead and close this out.
