### ISSUE TITLE
/proc/net/nf_conntrack doesn't exist on Ubuntu 16.04

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#69588]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

e2e test "[sig-network] Network [It] should set TCP CLOSE_WAIT timeout" requires the test target OS supports /proc/net/nf_conntrack, but Ubuntu 16.04 doesn't support it.
Then the test fails today like the following:
```
STEP: Checking /proc/net/nf_conntrack for the timeout
Sep 17 23:29:38.946: INFO: Getting external IP address for k8s-master
Sep 17 23:29:38.946: INFO: SSH "sudo cat /proc/net/nf_conntrack | grep 'dport=11302'" on k8s-master(192.168.1.108:22)
Sep 17 23:29:39.258: INFO: ssh ubuntu@192.168.1.108:22: command:   sudo cat /proc/net/nf_conntrack | grep 'dport=11302'
Sep 17 23:29:39.259: INFO: ssh ubuntu@192.168.1.108:22: stdout:    ""
Sep 17 23:29:39.259: INFO: ssh ubuntu@192.168.1.108:22: stderr:    "cat: /proc/net/nf_conntrack: No such file or directory\n"
Sep 17 23:29:39.260: INFO: ssh ubuntu@192.168.1.108:22: exit code: 1
Sep 17 23:29:39.260: INFO: Unexpected error occurred: failed running "sudo cat /proc/net/nf_conntrack | grep 'dport=11302'": <nil> (exit code 1)
[AfterEach] [sig-network] Network
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:142
...
~ Failure [18.318 seconds]
[sig-network] Network
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:22
  should set TCP CLOSE_WAIT timeout [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/kube_proxy.go:50

  Expected error:
      <*errors.errorString | 0xc420b0e430>: {
          s: "failed running \"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\": <nil> (exit code 1)",
      }
      failed running "sudo cat /proc/net/nf_conntrack | grep 'dport=11302'": <nil> (exit code 1)
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/kube_proxy.go:178
------------------------------
```

**What you expected to happen**:

The test succeeded or was skipped.

**How to reproduce it (as minimally and precisely as possible)**:

Just kick
```
$ go run hack/e2e.go --provider=skeleton -- test --test_args="--ginkgo.focus=should\sset\sTCP\sCLOSE_WAIT\stimeout"
```
**Anything else we need to know?**:

The existence of /proc/net/nf_conntrack depends on the Linux kernel config CONFIG_NF_CONNTRACK_PROCFS, but that is disabled on Ubuntu 16.04.
In addition, the test is skipped if the node number is less than 2.
So I guess that is one of reasons this issue was not present until today.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.4.0-134-generic
- Install tools: kubeadm
- Others:

**Comment by aojea** [comment]
Some kube-proxy functionalities depends on conntrack, is it possible to run a conformance cluster without having conntrack enable?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/69589/files#r418929810
