### ISSUE TITLE
CABundle should not be required in Webhook ClientConfig

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#69590]
Rancher users seem to use Let's Encrypt to expose their kube-apiserver. This means that their kubeconfig file has no client-ca. Any custom controller that uses self-hosted EAS to implement admission webhooks has no place to look for CABundle.

But CABundle is a required field for Webhook ClientConfig . https://github.com/kubernetes/api/blob/e3c5c37695fbce2b0b46845e3bb4806c4b8faf47/admissionregistration/v1beta1/types.go#L290

We use the self-hosted webhook pattern shown in https://github.com/openshift/kubernetes-namespace-reservation with our tools . This makes installing such tools in Rancher cluster very cumbersome.

`CABundle` should be an optional field to indicate that webhook server might be using a trusted certificate.

xref: https://github.com/kubedb/project/issues/309

**Comment by tamalsaha** [comment]
/kind enhancement
/sig api-machinery

cc: @deads2k

**Comment by deads2k** [comment]
Using system certs when the CA is empty seems fine.  Semi-related, I do not want to support an insecure option.  No CA cannot mean insecure, it must mean system certs.

**Comment by liggitt** [comment]
> Using system certs when the CA is empty seems fine. Semi-related, I do not want to support an insecure option. No CA cannot mean insecure, it must mean system certs.

Agree on both counts. If you leave it empty today (which is allowable), I think that is the current behavior (use system certs)

**Comment by tamalsaha** [comment]
So, is the fix just to relax the constraint in the types.go?

**Comment by mattmoor** [comment]
Any chance this would land in 1.13?

**Comment by liggitt** [comment]
> Any chance this would land in 1.13?

I don't see why not. The change is trivial, just needs a testcase added.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/70138 to fix the optional indicator and added a test to make sure the transport created from that config uses default rootca bundle and is not made insecure

**Comment by bgarcial** [comment]
I had the same error, but it was related with the management of the helm dependencies 

My cluster version is 1.12.7, but the error in my case was by the following:

I was trying attach cert-manager as a helm dependency in my requirements.yaml helm chart file and when I do that, I execute `helm dep update` to tell to helm that attach to cert-manager.

Then a `*.tgz` cert-manager package is downloaded to my `chart/` directory.
My idea was to remove cert-manager like dependency and so I had to remove the `*.tgz` cert-manager package from `chart/` directory and also update the helm dependencies executing again executing `helm dep update` in order to don't have any dependency attached.

```⟩ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 0 charts
Deleting outdated charts```

And my problem with the `"caBundle"`has disappear.

**Comment by ramnes** [comment]
Do I understand correctly that an empty `caBundle` value should be equivalent to a `caBundle` that contains `$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}')` (as used [here](https://github.com/morvencao/kube-mutating-webhook-tutorial/blob/master/deployment/webhook-patch-ca-bundle.sh))?

If so, how to explain that I end up with errors like `x509: certificate signed by unknown authority` without `caBundle`, whereas it works correctly when specified?

**Comment by elithrar** [comment]
An empty caBundle will use the root CA on the Node - which (as you see!)
will fail to validate cluster issued certs.

You need to provide the base64 cluster CA cert as the value to caBundle.
