### ISSUE TITLE
StatefulSet without Service

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#69608]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Developers have started to use `StatefulSet` without a `Service` definition as a way to deploy a pod on a cluster exactly once, for example here: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/stable/controller.yaml

Conceptually that makes sense when the app running in the pod doesn't accept any connections from outside. In this example, it's the CSI sidecar containers which react to changes in the apiserver.

But is this a supported mode of operation for a `StatefulSet`? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#statefulset-v1-apps says that
> serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set. Pods get DNS/hostnames that follow the pattern: pod-specific-string.serviceName.default.svc.cluster.local where "pod-specific-string" is managed by the StatefulSet controller.

`serviceName` is mandatory. The example above gets around this by setting `serviceName` without defining a corresponding `Service`.

The concern (raised by @rootfs in https://github.com/ceph/ceph-csi/issues/81) is that while it currently works, future revisions of the `StatefulSet` controller might not support this anymore.

**What you expected to happen**:

Clarify in the docs that the `Service` definition is not needed or (better?) make `serviceName` optional.

**Environment**:
- Kubernetes version (use `kubectl version`): tested on 1.11 and 1.12

**Comment by pohly** [comment]
/remove-lifecycle stale

Still a valid question...

**Comment by kfox1111** [comment]
+1. I'd like to know this too. Having statefulsets without a service makes sense to me if they don't care about a stable identity, just that there is no more then 1.

**Comment by Noah-Huppert** [comment]
Would a headless service be the solution to this problem?

[Kubernetes Docs](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services):

> Sometimes you don’t need load-balancing and a single Service IP. In this case, you can create what are termed “headless” Services, by explicitly specifying `"None"` for the cluster IP (`.spec.clusterIP`).

**Comment by pohly** [comment]
Noah Huppert <notifications@github.com> writes:
> Would a headless service be the solution to this problem?

It's better, but still a useless object that could be avoided if we
could get clarified that a StatefulSet is okay to use without a Service.

**Comment by kfox1111** [comment]
What is the status of this?

**Comment by kfox1111** [comment]
I've launched statefulsets without services and it seems to work ok. We're just looking for a guarantee that this will continue to be safe going forward. The docs say its required, but the implementation does not enforce it last I looked.

**Comment by yashbhutwala** [comment]
So, we had fun facing the issue today, learned a bunch of networking, passing it on, hopefully someone else will find this useful.  

If you create a StatefulSet with a headless service, the ports exposed in the headless service don't matter.  The communication in this case happens via DNA directly to the pod.  kube-proxy is not involved at all.  😄

**Comment by kfox1111** [comment]
/remove-lifecycle stale

It looks like when going to apps/v1, this actually did become a required feature:
error: error validating "test.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

This should be made less restrictive if possible.

**Comment by Nhat002** [comment]
@kfox1111 if you turn validation on in apps/v1beta2, you will still face this issue
```
Deploy failed: error: error validating "STDIN": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1beta2.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by kfox1111** [comment]
I was told that it was marked as required in the docs but it actually wasn't required. But looking at it now, it is actually required to pass validation. I would request that this be made optional in validation so that it is actually optional in practice. Turning off all validation on the statefulset to make it the service optional is not a good way of doing this. For things not needing DNS, the service should be optional. There are a lot of things that could benefit from being statefulsets but don't need DNS.

**Comment by pohly** [comment]
@kfox1111 should be a collaborator, right?

/reopen

**Comment by TBBle** [comment]
/remove-lifecycle rotten

https://github.com/kubernetes/kubernetes/issues/69608#issuecomment-594677833 still seems to be the state of this issue.

**Comment by TBBle** [comment]
At this point the two CSI examples from the original ticket have gone away (see https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/521 and https://github.com/ceph/ceph-csi/pull/414 which replaced the StatefulSet singletons with Deployments using leader-election).

Are there any practical/current use-cases for StatefulSet without a backing Service? The ticket's approaching three years old, and has not yet been triaged, suggesting there's not much appetite/motivation to advanced the proposed change in https://github.com/kubernetes/kubernetes/issues/69608#issuecomment-594677833.

**Comment by TBBle** [comment]
/reopen

https://github.com/kubernetes/kubernetes/issues/69608#issuecomment-1002681415 intended to keep this ticket active, but named the wrong lifecycle, I assume by accident.
