### ISSUE TITLE
fluentd-elasticsearch does not send events after they are filtered and processed

### ISSUE THREAD

**Issue by sagarkal** [kubernetes/kubernetes#69603]
**Is this a BUG REPORT or FEATURE REQUEST?**:

@kubernetes/sig-AWS-bugs
> Uncomment only one, leave it on its own line:
bug

**What happened**:

I am using fluentd-elasticsearch v2.3.1 in order to filter and process JSON events generated by kubernetes pods and then send them to AWS managed Elastic search.

**What you expected to happen**:
I expect to see filtered JSON events on Kibana. I am basically decoding a JSON object from a stringified bigger JSON object, doing some processing on it and then sending it to Elastic.  But I am seeing that the events are not being sent to Elastic by fluentd after they are filtered and processed. For example, I am deleting a couple of attributes before I send an event to Elastic. I verify from the logs of fluentd that the JSON was decoded and the said attributes were deleted. But I do not see the events on Kibana

**How to reproduce it (as minimally and precisely as possible)**:
Use the image gcr.io/google-containers/fluentd-elasticsearch (v2.3.1) to send an event like below to AWS Managed Elastic 6.2.3. Below is a part of the configuration I'm using for fluentd:

```
<filter kube.**>
    @type docker
</filter>
<filter kube.**>
    @type record_transformer
    remove_keys $['log']['requestHeaders']
</filter>
```
Note that `@type docker` is used to decode the intended JSON object that is stringified.

And below is the part of the message that I am decoding into JSON and deleting the attributes _requestHeaders_  and _responseHeaders_ before sending the event to Elastic
`
{"log": "{\"requestHeaders\":\"{\\\"Host\\\":\\\"www.dummy.com\\\",\\\"User-Agent\\\":\\\"Go-http-client/1.1\\\",\\\"Accept\\\":\\\"application/json\\\",\\\"X-Custom-Header\\\":\\\"234\\\",\\\"Accept-Encoding\\\":\\\"gzip\\\"}\",\"method\":\"GET\",\"responseHeaders\":\"{\\\"vary\\\":\\\"Accept-Encoding\\\",\\\"set-cookie\\\":\\\"rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 09-Oct-2018 00:43:41 GMT\\\",\\\"Accept-Ranges\\\":\\\"bytes\\\",\\\"Server\\\":\\\"dummy\\\",\\\"Content-Length\\\":\\\"3\\\",\\\"Content-Type\\\":\\\"application/json; charset=utf-8\\\",\\\"Connection\\\":\\\"close\\\",\\\"AcceptRanges\\\":\\\"bytes\\\"}\",\"uri\":\"/dummyPath\",\"sslServerName\":\"localhost\",\"statusText\":\"OK\",\"type\":\"http\",\"userAgent\":\"Go-http-client/1.1\",\"version\":\"HTTP/1.1\",\"sslProtocol\":\"TLSv1.2\"},\"status\":\"Pass\"}}\n"}
`
**Anything else we need to know?**: Nothing that I can think of right now.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu

**Comment by monotek** [comment]
Will be fixed with image 2.4.0. See: https://github.com/kubernetes/kubernetes/pull/71180
