### ISSUE TITLE
Not able to initialize kubernetes cluster with assigned IP : Vagrant provisioned infra

### ISSUE THREAD

**Issue by irfanjs** [kubernetes/kubernetes#69610]
Hello,

**what is expected:** 
Kubernetes cluster should be initialized with custom network interface provisioned by vagrant. 

**How to reproduce :**
Vagrant version :  2.1.4
oracle virtualbox version : Version 5.2.18 r124319 (Qt5.6.2)
Host OS : win 8.1 (64 bit), 8 GB RAM

two centos 7 boxes are provisioned. one is master and another is worker.
Using [vagraantfile  ](https://pastebin.com/zWHmnLzd), able to create VM and was able to execute all commands successfully. 

however, `kubeadm init` command always takes **10.x.x.x** range IP address rather than the one which i provided in the script. (172.x.x.x)

i am not sure why this is happening and how kubernetes decides which network interface to pick up at the time of initialization. 
i have gone to most k8s docs but never find the way to get it 

here is the doc i referred for vagrant networking: 
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
https://www.vagrantup.com/docs/virtualbox/networking.html

please suggest
Regards,

**Comment by irfanjs** [comment]
please suggest.
not getting , how kubernetes selects the network interfaces while initializing .....
as of now, it is selecting 10.x.x.x IP address ranges, but i need kubernetes to pick up 172.x.x.x ip address range. 172 ip address range is already available in enpS08 interface.

**Comment by irfanjs** [comment]
because of me in different timezone, most of the folks i see is offline ... so seeking suggestion here 
please help

**Comment by irfanjs** [comment]
this is resolved by using option : `--apiserver-advertise-address` along with `--pod-network-cidr` option

**Comment by neolit123** [comment]
thanks for the update
/close
