### ISSUE TITLE
ApiServer was not able to recover from network disconnection with etcd

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#69621]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
When apiserver was disconnected from etcd cluster for some reason, it's not able to recover even if  the network issue was solved. 

**What you expected to happen**:
Apiserver should always find the available etcd to work on.

**How to reproduce it (as minimally and precisely as possible)**:
Suppose there was an etcd cluster with 3 nodes and one apiserver connecting to it.
1. cut off the network connection between etcd and apiserver.
```
iptables -A INPUT -p tcp --dport 2379 -j DROP
iptables -A OUTPUT -p tcp --dport 2379 -j DROP
```
2. after 1 min, apiserver will respond with **504 Gateway Timeout** from the [timeout filter](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L37)
log shows as follows
```
logging error output: "{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within 1m0s\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}\n"
 [[kubelet/v1.9.6 (linux/amd64) kubernetes/73b157c] 172.16.1.43:48934]
I1010 19:31:18.290539   29187 wrap.go:42] GET /api/v1/nodes/172.16.1.42: (1m0.000346629s) 504
```
3. recover the network on **one node**
```
iptables -D INPUT -p tcp --dport 2379 -j DROP
iptables -D OUTPUT -p tcp --dport 2379 -j DROP
```

4. there was a chance(2/3) apiserver still not able to server **unless restart apiserver.**

**Anything else we need to know?**:
etcd cluster's client port is 2379 and peer port is 2380, so the iptable rules will not affect the internal health of etcd cluster.

**Environment**:
- Kubernetes version (use `kubectl version`):
   v 1.9.6 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
   **Etcd Version: 3.1.18**

**Comment by DylanBLE** [comment]
It seems that adding a timeout context fixes the issue. I wonder if there is more elegant solution.

**Comment by jingyih** [comment]
There is a timeout added to the incoming request to apiserver, which we believe is not wired correctly in the call stack.  I am investigating this issue.

**Comment by liggitt** [comment]
can you verify this is still needed after https://github.com/kubernetes/kubernetes/commit/31ff8c6b9a08d1168502e423bdd3fdbe4f2f729b (added in 1.10)

**Comment by DylanBLE** [comment]
@liggitt  31ff8c6 fixed the issue! Thanks.
