### ISSUE TITLE
allow to specify wheter to use rbd-nbd or krbd

### ISSUE THREAD

**Issue by gucki** [kubernetes/kubernetes#69625]
The current implemenation always tried first to use the kernel rbd and only if that fails it falls back to rbd-nbd. 

See https://github.com/kubernetes/kubernetes/blob/243557ba3da96995db4f8efbc756fc935d074739/pkg/volume/rbd/rbd_util.go#L362 

See https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/volume/rbd/rbd_util.go#L426

A configuration option to specify/ force which driver to use should be added. 

/sig storage

**Comment by wenjun93** [comment]
@rootfs @rzarzynski @kubernetes/sig-storage is there a preference of which way to use, krbd or rbd-nbd, which should be the suggested way from the reliability aspect?

**Comment by klzsysy** [comment]
i try remove rbd module

```sh
rbd_path=$(modinfo rbd | grep -Poe "/lib/modules/.*")

modprobe -r rbd

mv ${rbd_path} ${rbd_path}.bak

yum install -y rbd-nbd
```

![image](https://user-images.githubusercontent.com/3226923/53283253-77fd3280-377e-11e9-91dd-6f0bcdbc9995.png)


But who can tell me to wait 10 seconds after the completion of the mount to start the next step? （rbd same）

![image](https://user-images.githubusercontent.com/3226923/53283270-b266cf80-377e-11e9-8437-6480ae0d6038.png)



@k4k
