### ISSUE TITLE
EBS volume attaches but does not mount on AWS c5 instance types

### ISSUE THREAD

**Issue by cohadar** [kubernetes/kubernetes#69620]
/kind bug

**What happened**:
volume attaches but does not mount on AWS c5 instance types

**What you expected to happen**:
volume to mount on pod

**How to reproduce it (as minimally and precisely as possible)**:
k8s 1.10 on aws, c5 instance type node, try to mount EBS volume to pod

**Anything else we need to know?**:
This is probably because this instance types use different devices: /dev/nvme1n1 instead of /dev/xvdb

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`):
Linux ip-10-80-0-103 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
- Install tools:
kops
- Others:

**Comment by cohadar** [comment]
Max 3-4.

**Comment by leakingtapan** [comment]
5th gen of EC2 instance doesn't work with jessie. See https://github.com/kubernetes/kops/issues/5520 and https://github.com/kubernetes/kops/issues/3901#issuecomment-348799919

Have you tried stretch?

**Comment by leakingtapan** [comment]
/remove-lifecycle stale

You might be hitting the nvme issue: https://github.com/coreos/bugs/issues/2371

1.10 is pretty old now. @cohadar Do you still experience the issue with latest k8s version?
