### ISSUE TITLE
fake_event_expansion / fake_node_expansion do not expose PatchType.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes/kubernetes#69632]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/fake/fake_event_expansion.go
kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/fake/fake_node_expansion.go

do not support PatchType. They probably should.

**What you expected to happen**:
These files are not auto-generated, nor do they support PatchType.

**How to reproduce it (as minimally and precisely as possible)**:
delete these two files, run autogen, see they do not come back. Also, their API does not include patch type.

**Comment by caesarxuchao** [comment]
/kind cleanup
/sig api-machinery
See https://github.com/kubernetes/kubernetes/pull/69330#discussion_r224160179.
