### ISSUE TITLE
Add test coverage of protobuf compatibility between versions

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#69638]
During review of a [etcd client version upgrade](https://github.com/kubernetes/kubernetes/pull/69322) that also required a gogo/protobuf upgrade, we noticed that we lack of test coverage to ensure that previously serialized protobuf data decodes correctly and changes like this stay wire-compatible. We should aim for our wire protocol compatibility testing should be exhaustive.

**Comment by jonathangold** [comment]
I'd like to take this.
/assign

**Comment by jonathangold** [comment]
I would like to take this issue. Just signed the CLA.

**Comment by jonathangold** [comment]
@jpbetz Planning to writing a few (table-driven) tests in kubernetes/staging/src/k8s.io/apimachinery/pkg/api/resource/ to check if protobuf encodes and decodes as expected. Sound good?
