### ISSUE TITLE
Add support for imagePullSecrets in PodPreset

### ISSUE THREAD

**Issue by mitar** [kubernetes/kubernetes#69640]
/kind feature

**What happened**:

In `PodPreset` documentation it says that you can use it for secrets as well. But when I try to use `imagePullSecrets` in the preset, I get:

```
error validating data: ValidationError(PodPreset.spec): unknown field "imagePullSecrets" in io.k8s.api.settings.v1alpha1.PodPresetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:

`imagePullSecrets` would be used an applied to pods.

**How to reproduce it (as minimally and precisely as possible)**:

Create a preset with `imagePullSecrets` value. Try to create it using `kubectl create -f`.
**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration: custom server
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mitar** [comment]
@kubernetes/sig-architecture-feature-requests @kubernetes/sig-node-feature-requests

**Comment by bgrant0607** [comment]
/remove-sig architecture node

AFAIK, there is no plan to move the built-in PodPreset beyond alpha. If it is still needed, it would probably be implemented using CRD and admission webhooks.

**Comment by liggitt** [comment]
PodPresets are not being actively developed and are planned for removal (xref #94090 and #93900).

As an alternative, you could create a [mutating admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) (which was not a thing that existed when podpresets were introduced) to inject image pull secrets in a way that matches your use case.

/close
