### ISSUE TITLE
kubelet /stats/summary returns empty pods list - disabling HPA

### ISSUE THREAD

**Issue by aalubin** [kubernetes/kubernetes#69658]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig node
/area kubelet
/area kubelet-api

**What happened**:
We are trying to migrate from docker to cri-o for container runtime

When querying the kubelet for /stats/summary (curl localhost:10255/stats/summary)
the pods information is an empty list although pods are running on the node, the general server information is available.
This is an example of the end of the output:
.
.
.
   },
   "rlimit": {
    "time": "2018-10-11T06:38:33Z",
    "maxpid": 40960,
    "curproc": 1972
   }
  },
  "pods": []
 }

**What you expected to happen**:
statics information on pod

**How to reproduce it (as minimally and precisely as possible)**:
not sure, here is our kubelet configuration: 
xecStart=/usr/bin/kubelet --allow-privileged=true \
--cadvisor-port=4194 \
--cgroup-driver=cgroupfs \
--client-ca-file=/etc/pki/kubernetes_certs/ca.pem \
--cluster-dns=10.10.10.2 \
--cluster-domain=customdomain.com \
--cni-bin-dir=/opt/cni/bin \
--cni-conf-dir=/etc/cni/net.d \
--container-runtime-endpoint=unix:///var/run/crio/crio.sock \
--container-runtime=remote \
--cpu-manager-policy=none \
--feature-gates=TaintBasedEvictions=true \
--image-gc-high-threshold=70 \
--image-gc-low-threshold=50 \
--kube-reserved-cgroup=podruntime.slice \
--kube-reserved=cpu=1,memory=3Gi \
--kubeconfig=/etc/kubernetes/kubelet_kubeconfig \
--kubelet-cgroups=/podruntime.slice \
--network-plugin=cni \
--node-labels=configure_bgp_peers=true \
--pod-manifest-path=/etc/kubernetes/manifests \
--register-node=true \
--register-with-taints=new_node=true:NoSchedule \
--runtime-cgroups=/podruntime.slice \
--runtime-request-timeout=10m \
--system-reserved-cgroup=system.slice \
--system-reserved=cpu=1,memory=768Mi \
--tls-cert-file=/etc/pki/kubernetes_certs/k24.customdomain.com_cert.pem \
--tls-private-key-file=/etc/pki/kubernetes_certs/k24.customdomain.com_key.pem

**Anything else we need to know?**:
We've got the same results with mix of the following configuration:

- kubelet 1.10.7 and 1.11.3
- cri-o 1.10.5 and 1.11.6 

Another issue that we have that I think is the result of this is that crictl stats does not return any information

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: on premise Dell 630/640 servers
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): Linux k24.customdomain.com 4.14.35-1818.2.1.el7uek.x86_64 #2 SMP Mon Aug 27 21:16:31 PDT 2018 x86_64 x86_64 x8 6_64 GNU/Linux
- Install tools: puppet automation 
- Others:

**Comment by linericyang** [comment]
Both k8s and cri-o version 1.11 and 1.12 works as expected in my local environment, with the exactly same kubelet configurations. Cannot reproduce this issue.

**Comment by aalubin** [comment]
@linericyang thanks for checking.
Can it be related to cgroups? what can prevent from the kubelet to report pods stats?

**Comment by aalubin** [comment]
OK, issue resolved - sort of.
We are using cri-o from the following distribution: https://cbs.centos.org/koji/packageinfo?packageID=5695

This distribution write container information to /run/runc-ctrs
While cri-o forces runtime folder to be /run/runc

https://github.com/kubernetes-sigs/cri-o/blob/c778110424086ea17372539c2ccbd01596b83cb3/lib/container_server_linux.go#L17-L25

So I created a soft link to solve the issue

**Comment by linericyang** [comment]
@aalubin Good to know you root caused this issue. Fixing the hardcode path in cri-o might be the proper solution to resolve this issue. They already put a TODO item there.

**Comment by shahaf600** [comment]
related to this issue, I work with @aalubin on the same team.
after fixing this issue, I found the metrics-server can't get any data from any node with crio although i see in the hpa description the data:

$ kubectl describe hpa
Name:                                                  ****************
Namespace:                                             algo-prod
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 28 Aug 2018 11:29:19 +0300
Reference:                                             Deployment/************
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (36m) / 75%
Min replicas:                                          1
Max replicas:                                          32
Deployment pods:                                       1 current / 2 desired
Conditions:
  Type            Status  Reason                   Message
  ----            ------  ------                   -------
  AbleToScale     True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive   False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  ScalingLimited  True    TooFewReplicas           the desired replica count is increasing faster than the maximum scale rate
Events:
  Type     Reason                   Age                      From                       Message
  ----     ------                   ----                     ----                       -------
  Warning  FailedGetResourceMetric  3m55s (x6688 over 2d8h)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
