### ISSUE TITLE
kubeadm(v1.12.1) init failed(kubelet error with unknown flag --cadvisor-port)

### ISSUE THREAD

**Issue by lixianyang** [kubernetes/kubernetes#69656]
**BUG REPORT**:

>
> /kind bug

**What happened**:

when I use kubeadm init a cluster, it failed:
```
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
```
Then, I check kubelet.service (systemctl status kubelet -l) :
```
10月 11 14:00:17 u kubelet[5326]: F1011 14:00:17.004595    5326 server.go:148] unknown flag: --cadvisor-port
```

**What you expected to happen**:

Use kubeadm init cluster success

**How to reproduce it (as minimally and precisely as possible)**:

Download v1.12.1 server bin, copy bin files to /usr/bin/, then:
```
kubeadm init --ignore-preflight-errors Swap
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.12.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):18.04.1 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):Linux u 4.15.0-36-generic
- Install tools:kubeadm
- Others:

**Comment by lixianyang** [comment]
My environment error

**Comment by cybervedaa** [comment]
@lixianyang  - Can you tell me what was the environment error you found and fixed in your case?
I am experiencing the same problem.

**Comment by danopia** [comment]
I'm running Ubuntu Bionic like the original poster, but I'm not sure what the environment error was. Commenting the line fixes the problem for me as well.
