### ISSUE TITLE
Azure cluster setup script fails

### ISSUE THREAD

**Issue by ahmetalpbalkan** [kubernetes/kubernetes#6966]
(more progress at #7826)

I tried out Kubernetes install script for Azure (code from #6691) and having problems with it. My attempt at diagnosing it:

`kube-up.sh` gets stuck while trying to connect to the master (dots keep going on and on forever):

```
[...]
==> KUBE_MASTER_IP: kube-9a36ffc.cloudapp.net
Waiting for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start
  up.

....................................................................................................
....................................................................................................
....................................................................................................
................
```

I tried that `until curl ...` request myself and it returns `HTTP 502 Bad Gateway` from outside, when I looked at script I can see that it does `proxy_pass` to `localhost:8080`. But I can't curl to 8080 when I ssh to the master either (I don't know which process that was supposed to be).

However when I looked at /var/log/monit.log, every 2 minutes it keeps saying:

```
[UTC Apr 17 06:10:53] info     : 'docker' trying to restart
[UTC Apr 17 06:10:53] info     : 'docker' start: /etc/init.d/docker
[UTC Apr 17 06:10:53] error    : Error: Could not execute /etc/init.d/docker
```

and when I run `docker` command on the kubernetes-master instance, I can see indeed it's not installed. (not in dpkg.log either.) I have no idea who is supposed to install Docker. But I can give access to the instance to diagnose if you ping me on IRC.

**Comment by bgrant0607** [comment]
cc @jeffmendoza @colemickens

**Comment by bgrant0607** [comment]
See also #6576

**Comment by bgrant0607** [comment]
This sounds like a Salt problem. (See also #2678.) Could you check the Salt logs? https://github.com/GoogleCloudPlatform/kubernetes/wiki/Debugging-FAQ documents the locations of the logs.

What version of Kubernetes are you using?

**Comment by derekwaynecarr** [comment]
I wonder if it does the same thing that vagrant does which is verify each binary is on the machine when validating there cluster and the move to run more master components in pods makes that check never complete.

**Comment by colemickens** [comment]
The util script used to do that, it would access each minion and ensure `which docker` succeeds and that the kubelet is running, but it looks like now it just checks to see if the Kube endpoint is up.

**Comment by Snesha** [comment]
I have a fix for this issue. Do you need the CLA signed for PR's with <20 lines of change?

**Comment by cmdrkeene** [comment]
A fix would be great here. I'm seeing the same behavior on the latest release (and azure-cli@0.9.4 if that matters)

**Comment by dchen1107** [comment]
@Snesha Google lawyer requires CLA for every PR, and sign it through https://cla.developers.google.com/clas should be very easy.

**Comment by seanfreiburg** [comment]
Same issue here too.

**Comment by gabrielweyer** [comment]
I'm having the same issue here. Running `0.21.1` and trying to deploy on Azure following the [Azure](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md) tutorial.

I had a look at the salt logs and could only see DEBUG or INFO messages and nothing seemed out of the ordinary.

Regarding the Kubernetes log, only `kubernetes-addons.log` had some content and it was always the same things:

`error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused`

I noticed that scripts for other platforms (AWS, CoreOS...) are opening the port 8080, is it something we should do on Azure too?

My Master VM has 2 endpoints:
 - public port 443 mapped to private port 443
 - public port 22000 mapped to private port 22

My first minion has 1 endpoint
 - public port 22001 mapped to private port 22

My second minion has 1 endpoint
 - public port 22002 mapped to private port 22

When typing `netstat -t -l -p` I don't see anything listening on the port 8080 on the master.
