### ISSUE TITLE
Add Support for EFS TLS encryption via the AWS EFS Mount Helper

### ISSUE THREAD

**Issue by gregsidelinger** [kubernetes/kubernetes#69678]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Kube can not mount EFS(NFS) volumes using AWS's TLS options. The NFS volume in kube has mount.nfs hard coded in pkg/volume/nfs/nfs.go.  It needs a way to support mount.efs so that that the AWS EFS mount helper can setup the stunnels when tls is passed in via mountOptions.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/kubernetes-incubator/external-storage/issues/725 has a dependency on this.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CentOS 7.5
- Kernel (e.g. `uname -a`): Linux ip-10-166-56-121.ec2.internal 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by khacminh** [comment]
Hi @gregsidelinger,

I'm having the same issue with mounting EFS as `PersistentVolume` with **TLS** connection. Is there any workaround for EKS?

Thanks.

**Comment by gregsidelinger** [comment]
I have not had time to finish a EFS CSI driver.  One would hope AWS would provide one so I did not need to.

**Comment by khacminh** [comment]
Hi @gregsidelinger ,

I opened an issue, and I'm happy to hear that AWS is planning on it. They're collecting more use cases. I hope it will be released soon.

https://github.com/awslabs/amazon-eks-ami/issues/105#issuecomment-440843395

**Comment by mwilbz** [comment]
@khacminh my team just ran into the same issue when trying to use EKS. The AWS CSI driver that is being developed currently supports Kubernetes >=1.12, while EKS only supports up to Kubernetes 1.11. It seems [possible to fork the driver](https://github.com/aws/aws-efs-csi-driver/issues/10) to support 1.11, but we found a better workaround for now.

We were able to set up our nodes to [automatically mount EFS](https://docs.aws.amazon.com/efs/latest/ug/mount-fs-auto-mount-onreboot.html) using TLS, and then forward the mount with the [Kubernetes `local` volume type](https://kubernetes.io/docs/concepts/storage/volumes/#local).

Hope this helps.

**Comment by liggitt** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by leakingtapan** [comment]
If you are using v1.13+ cluster, you can start using aws-efs-csi-driver for tls encryption. Here is an example: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/encryption_in_transit/README.md

**Comment by ReillyProcentive** [comment]
/remove-lifecycle stale

I think we should leave this open until the EFS driver is at least beta quality.

**Comment by msau42** [comment]
The nfs driver in core Kubernetes is meant to be a generic nfs client that works across all platforms and environments.  Adding specific EFS binaries and options is not possible at this time, and CSI Is the way to go for all new provider-specific functionality.

**Comment by liggitt** [comment]
Based on https://github.com/kubernetes/kubernetes/issues/69678#issuecomment-508218044, this doesn't sound like something that will involve any changes in kubernetes or in this repo, is that correct? If so, I'd recommend closing this issue.

**Comment by msau42** [comment]
I recommend opening an issue in https://github.com/kubernetes-sigs/aws-efs-csi-driver for this functionality.
/close
