### ISSUE TITLE
i am unable to make run all my pods while installation

### ISSUE THREAD

**Issue by MohanNagendraKumar** [kubernetes/kubernetes#69672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MohanNagendraKumar** [comment]
NAMESPACE     NAME                                           READY   STATUS              RESTARTS   AGE
kube-system   coredns-576cbf47c7-7r2rm                       0/1     ContainerCreating   0          45m
kube-system   coredns-576cbf47c7-h9qf7                       0/1     ContainerCreating   0          45m
kube-system   etcd-cssosbe03-b02-master                      1/1     Running             0          12m
kube-system   kube-apiserver-cssosbe03-b02-master            1/1     Running             0          16m
kube-system   kube-controller-manager-cssosbe03-b02-master   1/1     Running             0          16m
kube-system   kube-flannel-ds-amd64-9fbxx                    0/1     CrashLoopBackOff    8          16m
kube-system   kube-proxy-2gg4t                               1/1     Running             0          45m
kube-system   kube-scheduler-cssosbe03-b02-master            1/1     Running             0          16m

**Comment by chrisohaver** [comment]
`kube-system kube-flannel-ds-amd64-9fbxx 0/1 CrashLoopBackOff 8 16m`

What do the logs say there?  `kubectl -n kube-system logs kube-flannel-ds-amd64-9fbxx `

**Comment by dims** [comment]
/close

please reopen with info requested above
