### ISSUE TITLE
Unable to have rolebinding for gsuite account

### ISSUE THREAD

**Issue by gogovan-vincentngai** [kubernetes/kubernetes#69689]
**What happened/How to reproduce it (as minimally and precisely as possible)**:
What i want is different team from gsuite(or by email group) 
access different namespace (and limit to namespace only)

In gsuite
1. I am using company domain and email from **gsuite**
2. I created group named "demogroup" and its address"demogroup@example.com"  and assign user "demo@example.com" into "demogroup@example.com"
3. Checked user can success login , and check groups is correctly show up in https://groups.google.com/a/example.com

In GCP - IAM 
1. Create Role named **Minimum role for kubernetes**
assign following permission 
- container.apiServices.get
- container.apiServices.list
- container.clusters.get
- container.clusters.getCredentials 

2. Add Group "demogroup@example.com" to IAM in GCP

3. Check IAM correct shows up "demogroup@example.com" and recognize it is a group(Group icon show up) 

In GKE
1. I create namespace "dev"
2. I create RoleBinding with follow cmd
> kubectl create rolebinding test-group \
> --clusterrole=edit \
> --group=demogroup@example.com \
> --namespace=dev

Result : 

> Error from server (Forbidden): pods is forbidden: User "demo@example.com" cannot list pods in the namespace "dev": Required "container.pods.list" permission.

3. However when i change directly to user rather group
> kubectl create rolebinding test-group\
> --clusterrole=edit \
> --user=demo@example.com \
> --namespace=dev

Result : 
demo@example.com can have right from clusterrole edit

**What you expected to happen**:
Allow to access **dev** namespace , at least can get pod 

**Environment**:
- Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.1", GitCommit:"7221ffe8776f399448d61b4dc9edb5c69232aece", GitTreeState:"clean", BuildDate:"2018-08-29T23:11:12Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GKE 1.10.7-gke.1

Anything i am missing ?

/sig gcp
/sig auth

**Comment by gogovan-vincentngai** [comment]
am i missing something not yet provide ?

**Comment by cjcullen** [comment]
Right now, Google group membership is not included in the authentication information that Kubernetes sees, so using those groups in RBAC bindings will not have any effect. We are thinking through how to make that work in a sane and scalable way.

If you want a "minimum role for Kubernetes, check out the [container.ClusterViewer](https://cloud.google.com/kubernetes-engine/docs/how-to/iam#predefined). It only has the `container.clusters.list` and `container.clusters.get` IAM permissions, which is enough to run `gcloud container clusters get-credentials` and start talking to your cluster.

`apiServices.get` and `apiServices.list` are permissions regarding the "APIService" API, which is used to [set up extension API Servers](https://kubernetes.io/docs/tasks/access-kubernetes-api/setup-extension-api-server/). I'm guessing that isn't what you wanted here.

`clusters.getCredentials` grants the ability to retrieve the basic auth username/password, or the pre-generated client-certificate (if those were enabled for your cluster). It looks like you want to authenticate to the cluster with your Google identity (e.g. "demo@example.com"), so you likely don't want getCredentials permission either.

**Comment by cjcullen** [comment]
GKE now supports expansion of Google Group membership for RBAC {Cluster}RoleBindings. There is a config you need to set on your GKE cluster; more info here: https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#google-groups-for-gke

**Comment by liggitt** [comment]
thanks for the update

/close
