### ISSUE TITLE
Containers injected via MutatingAdmissionWebhook do not get default SA volumeMount

### ISSUE THREAD

**Issue by jwendell** [kubernetes/kubernetes#69733]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
If a container is appended into a pod through a MutatingAdmissionWebhook, the volume mount for the service account (containing `mountPath: /var/run/secrets/kubernetes.io/serviceaccount`) does not get injected into this new container.

**What you expected to happen**:
All containers (despite being injected automatically by the MutatingAdmissionWebhook or not) should get this volume mount.

**Comment by liggitt** [comment]
the volume mount is added by the service account admission plugin, which runs prior to webhook admission plugins. see https://github.com/kubernetes/kubernetes/issues/64333 for a discussion of ordering dependencies in admission webhooks

/close

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/pull/78080/
