### ISSUE TITLE
Leader election spamming scheduling logs

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#69743]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-scheduling-bugs 

**What happened**:
Here's an example from an e2e test:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4196/artifacts/bootstrap-e2e-master/kube-scheduler.log

```
I1011 00:01:23.747194       1 wrap.go:42] GET /healthz: (21.155µs) 200 [kube-probe/1.13+ 127.0.0.1:35748]
I1011 00:01:25.678930       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:27.721975       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:29.778759       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:31.825248       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:33.748955       1 wrap.go:42] GET /healthz: (23.09µs) 200 [kube-probe/1.13+ 127.0.0.1:35770]
I1011 00:01:33.890292       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:35.935005       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:37.984695       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:40.027758       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:42.084951       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
```

**What you expected to happen**:
leader election success logs to be at a higher log level.

**Comment by bsalamat** [comment]
Leader election library is not a part of the scheduler. The scheduler is only a user of the library. It is located in client-go. It is currently [logged at V(4)](https://github.com/kubernetes/kubernetes/blob/38a9fc6aa240c99b17a93764fb5473bf6342ff9d/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L227). I am not sure if it is a good idea to reduce verbosity further.
The log messages seem to be excessive in the scheduler logs when the scheduler is idle in our tests.

**Comment by mlmhl** [comment]
> The log messages seem to be excessive in the scheduler logs when the scheduler is idle in our tests.

I think this is a common problem for all components, not just for scheduler.

**Comment by bsalamat** [comment]
In that case, we should consider reducing its verbosity to 5 or 6.

**Comment by msau42** [comment]
For some reason I thought that this was something new but I went back to 1.9 tests and checked the logs and I also see it printed every 2 seconds.

So maybe this is fine for test environments.

**Comment by bsalamat** [comment]
This is certainly not new, but I am still in favor of lowering it verbosity unless there is a good reason for having it in tests by default.

**Comment by timothysc** [comment]
I'm ok with changing the verbosity but the code now lives in the api-machinery land.

**Comment by seunghunee** [comment]
Can I take this?

**Comment by mikedanese** [comment]
The log level seems correct following these guidelines:

https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md

I am not sold on the value of glog's infinite log levels feature, however I could be convinced that our logging guidelines need a TRACE level.
