### ISSUE TITLE
API OWNERS should not inherit from parent?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#69741]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/OWNERS

I believe this owners file should not inherit permissions from parent OWNERS files; only api approvers should be able to approve api changes.

**Comment by neolit123** [comment]
@kubernetes/sig-architecture-misc-use-only-as-a-last-resort 
@kubernetes/sig-testing 
/kind feature
/sig architecture

**Comment by cblecker** [comment]
@lavalamp opened https://github.com/kubernetes/kubernetes/pull/69772 to do this
