### ISSUE TITLE
[Scheduler User Guide Documentation] Learning kube-scheduler's design and implementation from source code

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#69771]
PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE. We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: #69767

When we want to learn more about a system, starting with source code is always the right choice. So we need an document(feel free to create in https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/scheduling) to do this - from analyzing the source code of kube-scheduler to describe how the scheduler is designed and how it is implemented in engineering. This will be a valuable guide for new learners or developers who want to participate in kube-scheduler.

/sig scheduling
/kind documentation
/help
/good-first-issue

**Comment by yaseenhamdulay** [comment]
Hi, I'd like to pick this up. Could I do that?

**Comment by wgliang** [comment]
Of course, thank you very much! Any questions, please comment here, we will help you.

**Comment by wgliang** [comment]
@yaseenhamdulay 
NOTE: This may be a long-term job, you can write a part and submit it, so we can help you modify it at the same time. In other words, you do not need to complete before submitting your PR.

**Comment by wgliang** [comment]
@yaseenhamdulay  Will the PR be ready for review soon? Or what progress has you made recently? 
Hope to get your feedback. :)

**Comment by wgliang** [comment]
@yaseenhamdulay What progress has been made recently?

**Comment by huynq0911** [comment]
Hi @wgliang, I'm investigating about Scheduler and want to understand it better. Can I take it?

**Comment by wgliang** [comment]
@huynq0911 Sure, Thanks
/assign @huynq0911
