### ISSUE TITLE
Updating vendored dependencies for Kubernetes 1.13

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#69776]
What we need to do? The task here is to pick one or a few of related dependencies for the main kubernetes repository and update them in time for 1.13 release.

- Review the [documentation for managing vendor dependencies](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md)
- Click on each url below to see if there are any changes to dependencies. Note that the SHA in each url was picked up from Godeps.json. So cross check with the latest [Godeps.json](https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json)
- If there are recent changes to the vendored library, then follow steps from url above and update the dependency.
- Leave a note in this issue about which libraries you are picking up so others do not do the same work that you are doing.

**List of dependencies:**
- [ ] [github.com/Azure/azure-sdk-for-go](http://github.com/Azure/azure-sdk-for-go/compare/520918e6c8e8e1064154f51d13e02fad92b287b8...HEAD)
- [ ] [github.com/Azure/go-autorest](http://github.com/Azure/go-autorest/compare/bca49d5b51a50dc5bb17bbf6204c711c6dbded06...HEAD)
- [x] [github.com/JeffAshton/win_pdh](http://github.com/JeffAshton/win_pdh/compare/76bb4ee9f0ab50f77826f2a2ee7fb9d3880d6ec2...HEAD)
- [ ] [github.com/MakeNowJust/heredoc](http://github.com/MakeNowJust/heredoc/compare/bb23615498cded5e105af4ce27de75b089cbe851...HEAD)
- [ ] [github.com/Microsoft/hcsshim](http://github.com/Microsoft/hcsshim/compare/800683ae704ac360b2f3f47fa88f3a6c8c9091b5...HEAD)
- [ ] [github.com/PuerkitoBio/purell](http://github.com/PuerkitoBio/purell/compare/8a290539e2e8629dbc4e6bad948158f790ec31f4...HEAD)
- [x] [github.com/armon/circbuf](http://github.com/armon/circbuf/compare/bbbad097214e2918d8543d5201d12bfd7bca254d...HEAD)
- [ ] [github.com/aws/aws-sdk-go](http://github.com/aws/aws-sdk-go/compare/fde4ded7becdeae4d26bf1212916aabba79349b4...HEAD)
- [ ] [github.com/blang/semver](http://github.com/blang/semver/compare/b38d23b8782a487059e8fc8773e9a5b228a77cb6...HEAD)
- [ ] [github.com/chai2010/gettext-go](http://github.com/chai2010/gettext-go/compare/c6fed771bfd517099caf0f7a961671fa8ed08723...HEAD)
- [ ] [github.com/cloudflare/cfssl](http://github.com/cloudflare/cfssl/compare/56268a613adfed278936377c18b1152d2c4ad5da...HEAD)
- [x] [github.com/clusterhq/flocker-go](http://github.com/clusterhq/flocker-go/compare/2b8b7259d3139c96c4a6871031355808ab3fd3b3...HEAD)
- [ ] [github.com/codedellemc/goscaleio](http://github.com/codedellemc/goscaleio/compare/20e2ce2cf8852dc78bd42b76698dcd8dcd77b7b1...HEAD)
- [ ] [github.com/container-storage-interface/spec](http://github.com/container-storage-interface/spec/compare/2178fdeea87f1150a17a63252eee28d4d8141f72...HEAD)
- [ ] [github.com/containernetworking/cni](http://github.com/containernetworking/cni/compare/a7885cb6f8ab03fba07852ded351e4f5e7a112bf...HEAD)
- [ ] [github.com/coreos/etcd](http://github.com/coreos/etcd/compare/fca8add78a9d926166eb739b8e4a124434025ba3...HEAD)
- [ ] [github.com/coreos/go-semver](http://github.com/coreos/go-semver/compare/568e959cd89871e61434c1143528d9162da89ef2...HEAD)
- [ ] [github.com/coreos/go-systemd](http://github.com/coreos/go-systemd/compare/48702e0da86bd25e76cfef347e2adeb434a0d0a6...HEAD)
- [ ] [github.com/coreos/pkg](http://github.com/coreos/pkg/compare/fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8...HEAD)
- [ ] [github.com/cpuguy83/go-md2man](http://github.com/cpuguy83/go-md2man/compare/71acacd42f85e5e82f70a55327789582a5200a90...HEAD)
- [x] [github.com/d2g/dhcp4](http://github.com/d2g/dhcp4/compare/a1d1b6c41b1ce8a71a5121a9cee31809c4707d9c...HEAD)
- [ ] [github.com/d2g/dhcp4client](http://github.com/d2g/dhcp4client/compare/6e570ed0a266b730a860ba1068090f683b2c213a...HEAD)
- [ ] [github.com/davecgh/go-spew](http://github.com/davecgh/go-spew/compare/782f4967f2dc4564575ca782fe2d04090b5faca8...HEAD)
- [ ] [github.com/daviddengcn/go-colortext](http://github.com/daviddengcn/go-colortext/compare/511bcaf42ccd42c38aba7427b6673277bf19e2a1...HEAD)
- [ ] [github.com/dgrijalva/jwt-go](http://github.com/dgrijalva/jwt-go/compare/01aeca54ebda6e0fbfafd0a524d234159c05ec20...HEAD)
- [ ] [github.com/docker/distribution](http://github.com/docker/distribution/compare/edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c...HEAD)
- [ ] [github.com/docker/docker](http://github.com/docker/docker/compare/a9fbbdc8dd8794b20af358382ab780559bca589d...HEAD)
- [ ] [github.com/docker/go-connections](http://github.com/docker/go-connections/compare/3ede32e2033de7505e6500d6c868c2b9ed9f169d...HEAD)
- [ ] [github.com/docker/go-units](http://github.com/docker/go-units/compare/9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1...HEAD)
- [ ] [github.com/docker/libnetwork](http://github.com/docker/libnetwork/compare/a9cd636e37898226332c439363e2ed0ea185ae92...HEAD)
- [ ] [github.com/elazarl/goproxy](http://github.com/elazarl/goproxy/compare/c4fc26588b6ef8af07a191fcb6476387bdd46711...HEAD)
- [ ] [github.com/emicklei/go-restful](http://github.com/emicklei/go-restful/compare/ff4f55a206334ef123e4f79bbf348980da81ca46...HEAD)
- [ ] [github.com/evanphx/json-patch](http://github.com/evanphx/json-patch/compare/36442dbdb585210f8d5a1b45e67aa323c197d5c4...HEAD)
- [x] [github.com/exponent-io/jsonpath](http://github.com/exponent-io/jsonpath/compare/d6023ce2651d8eafb5c75bb0c7167536102ec9f5...HEAD)
- [ ] [github.com/fatih/camelcase](http://github.com/fatih/camelcase/compare/f6a740d52f961c60348ebb109adde9f4635d7540...HEAD)
- [ ] [github.com/fsnotify/fsnotify](http://github.com/fsnotify/fsnotify/compare/f12c6236fe7b5cf6bcf30e5935d08cb079d78334...HEAD)
- [x] [github.com/ghodss/yaml](http://github.com/ghodss/yaml/compare/c7ce16629ff4cd059ed96ed06419dd3856fd3577...HEAD)
- [ ] [github.com/go-openapi/loads](http://github.com/go-openapi/loads/compare/a80dea3052f00e5f032e860dd7355cd0cc67e24d...HEAD)
- [ ] [github.com/go-openapi/spec](http://github.com/go-openapi/spec/compare/1de3e0542de65ad8d75452a595886fdd0befb363...HEAD)
- [ ] [github.com/go-openapi/strfmt](http://github.com/go-openapi/strfmt/compare/d65c7fdb29eca313476e529628176fe17e58c488...HEAD)
- [ ] [github.com/go-openapi/validate](http://github.com/go-openapi/validate/compare/d509235108fcf6ab4913d2dcb3a2260c0db2108e...HEAD)
- [ ] [github.com/godbus/dbus](http://github.com/godbus/dbus/compare/c7fdd8b5cd55e87b4e1f4e372cdb1db61dd6c66f...HEAD)
- [ ] [github.com/gogo/protobuf](http://github.com/gogo/protobuf/compare/342cbe0a04158f6dcb03ca0079991a51a4248c02...HEAD)
- [ ] ~~[github.com/golang/glog](http://github.com/golang/glog/compare/44145f04b68cf362d9c4df2182967c2275eaefed...HEAD)~~
- [ ] [github.com/golang/groupcache](http://github.com/golang/groupcache/compare/02826c3e79038b59d737d3b1c0a1d937f71a4433...HEAD)
- [ ] [github.com/golang/mock](http://github.com/golang/mock/compare/bd3c8e81be01eef76d4b503f5e687d2d1354d2d9...HEAD)
- [ ] [github.com/golang/protobuf](http://github.com/golang/protobuf/compare/b4deda0973fb4c70b50d226b1af49f3da59f5265...HEAD)
- [ ] [github.com/google/cadvisor](http://github.com/google/cadvisor/compare/fc17731afdcf184832482e324913c8f1a91b54ee...HEAD)
- [ ] [github.com/google/gofuzz](http://github.com/google/gofuzz/compare/44d81051d367757e1c7c6a5a86423ece9afcf63c...HEAD)
- [ ] [github.com/googleapis/gnostic](http://github.com/googleapis/gnostic/compare/0c5108395e2debce0d731cf0287ddf7242066aba...HEAD)
- [ ] [github.com/gophercloud/gophercloud](http://github.com/gophercloud/gophercloud/compare/781450b3c4fcb4f5182bcc5133adb4b2e4a09d1d...HEAD)
- [ ] [github.com/hashicorp/golang-lru](http://github.com/hashicorp/golang-lru/compare/a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4...HEAD)
- [ ] [github.com/heketi/heketi](http://github.com/heketi/heketi/compare/aaf40619d85fda757e7a1c1ea1b5118cea65594b...HEAD)
- [ ] [github.com/jonboulle/clockwork](http://github.com/jonboulle/clockwork/compare/72f9bd7c4e0c2a40055ab3d0f09654f730cce982...HEAD)
- [ ] [github.com/json-iterator/go](http://github.com/json-iterator/go/compare/f2b4162afba35581b6d4a50d3b8f34e33c144682...HEAD)
- [ ] [github.com/kardianos/osext](http://github.com/kardianos/osext/compare/8fef92e41e22a70e700a96b29f066cda30ea24ef...HEAD)
- [ ] [github.com/libopenstorage/openstorage](http://github.com/libopenstorage/openstorage/compare/093a0c3888753c2056e7373183693d670c6bba01...HEAD)
- [ ] [github.com/mholt/caddy](http://github.com/mholt/caddy/compare/2de495001514ed50eac2e09f474c32d417100c5c...HEAD)
- [ ] [github.com/miekg/dns](http://github.com/miekg/dns/compare/5d001d020961ae1c184f9f8152fdc73810481677...HEAD)
- [ ] [github.com/mitchellh/go-wordwrap](http://github.com/mitchellh/go-wordwrap/compare/ad45545899c7b13c020ea92b2072220eefad42b8...HEAD)
- [ ] [github.com/mitchellh/mapstructure](http://github.com/mitchellh/mapstructure/compare/53818660ed4955e899c0bcafa97299a388bd7c8e...HEAD)
- [ ] [github.com/mvdan/xurls](http://github.com/mvdan/xurls/compare/1b768d7c393abd8e8dda1458385a57becd4b2d4e...HEAD)
- [ ] [github.com/onsi/ginkgo](http://github.com/onsi/ginkgo/compare/67b9df7f55fe1165fd9ad49aca7754cce01a42b8...HEAD)
- [ ] [github.com/onsi/gomega](http://github.com/onsi/gomega/compare/d59fa0ac68bb5dd932ee8d24eed631cdd519efc3...HEAD)
- [ ] [github.com/opencontainers/go-digest](http://github.com/opencontainers/go-digest/compare/a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb...HEAD)
- [ ] [github.com/opencontainers/runc](http://github.com/opencontainers/runc/compare/871ba2e58e24314d1fab4517a80410191ba5ad01...HEAD)
- [ ] [github.com/opencontainers/selinux](http://github.com/opencontainers/selinux/compare/4a2974bf1ee960774ffd517717f1f45325af0206...HEAD)
- [ ] [github.com/pborman/uuid](http://github.com/pborman/uuid/compare/ca53cad383cad2479bbba7f7a1a05797ec1386e4...HEAD)
- [ ] [github.com/pkg/errors](http://github.com/pkg/errors/compare/645ef00459ed84a119197bfb8d8205042c6df63d...HEAD)
- [ ] [github.com/pmezard/go-difflib](http://github.com/pmezard/go-difflib/compare/d8ed2627bdf02c080bf22230dbb337003b7aba2d...HEAD)
- [ ] [github.com/prometheus/client_golang](http://github.com/prometheus/client_golang/compare/e7e903064f5e9eb5da98208bae10b475d4db0f8c...HEAD)
- [ ] [github.com/prometheus/client_model](http://github.com/prometheus/client_model/compare/fa8ad6fec33561be4280a8f0514318c79d7f6cb6...HEAD)
- [ ] [github.com/prometheus/common](http://github.com/prometheus/common/compare/13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207...HEAD)
- [ ] [github.com/quobyte/api](http://github.com/quobyte/api/compare/206ef832283c1a0144bbc762be2634d49987b5ff...HEAD)
- [ ] [github.com/rancher/go-rancher](http://github.com/rancher/go-rancher/compare/09693a8743ba5ee58c58c1b1e8a4abd17af00d45...HEAD)
- [ ] [github.com/renstrom/dedent](http://github.com/renstrom/dedent/compare/020d11c3b9c0c7a3c2efcc8e5cf5b9ef7bcea21f...HEAD)
- [ ] [github.com/robfig/cron](http://github.com/robfig/cron/compare/df38d32658d8788cd446ba74db4bb5375c4b0cb3...HEAD)
- [x] [github.com/rubiojr/go-vhd](http://github.com/rubiojr/go-vhd/compare/0bfd3b39853cdde5762efda92289f14b0ac0491b...HEAD)
- [ ] [github.com/russross/blackfriday](http://github.com/russross/blackfriday/compare/300106c228d52c8941d4b3de6054a6062a86dda3...HEAD)
- [ ] [github.com/spf13/afero](http://github.com/spf13/afero/compare/b28a7effac979219c2a2ed6205a4d70e4b1bcd02...HEAD)
- [ ] [github.com/spf13/cobra](http://github.com/spf13/cobra/compare/c439c4fa093711d42e1b01acb1235b52004753c1...HEAD)
- [ ] [github.com/spf13/pflag](http://github.com/spf13/pflag/compare/583c0c0531f06d5278b7d917446061adc344b5cd...HEAD)
- [ ] [github.com/spf13/viper](http://github.com/spf13/viper/compare/7fb2782df3d83e0036cc89f461ed0422628776f4...HEAD)
- [ ] [github.com/storageos/go-api](http://github.com/storageos/go-api/compare/3a4032328d99c1b43fbda3d85bd3c80fa06e1707...HEAD)
- [ ] [github.com/stretchr/testify](http://github.com/stretchr/testify/compare/c679ae2cc0cb27ec3293fea7e254e47386f05d69...HEAD)
- [ ] [github.com/vishvananda/netlink](http://github.com/vishvananda/netlink/compare/b2de5d10e38ecce8607e6b438b6d174f389a004e...HEAD)
- [ ] [github.com/vmware/govmomi](http://github.com/vmware/govmomi/compare/22f74650cf39ba4649fba45e770df0f44df6f758...HEAD)
- [ ] [github.com/vmware/photon-controller-go-sdk](http://github.com/vmware/photon-controller-go-sdk/compare/4a435daef6ccd3d0edaac1161e76f51a70c2589a...HEAD)
- [ ] [github.com/xanzy/go-cloudstack](http://github.com/xanzy/go-cloudstack/compare/1e2cbf647e57fa90353612074fdfc42faf5073bf...HEAD)

Generated this list of dependencies (on oct 13 using script https://gist.github.com/dims/dcd1880aef24db6e85d733f3708af890)

**Comment by dims** [comment]
@justinsb some context is here : https://github.com/kubernetes/kubernetes/issues/27543#issuecomment-402144607

Another aspect here is to help folks who are new to the project to give something specific that they can help with as well. 

Another data point was how far behind we were in picking up some changes to ghodss/yaml and gopkg.in/yaml.v2:
https://github.com/kubernetes/kubernetes/pull/69627

It would be good to review what went in to dependencies and try to update them periodically. If we don't and we see a problem we need fixed in something upstream, it will get harder over time IMHO.

Yes, +1 for sig leads to review the above and prioritize them (and leave comments here for new contributors to help with the effort OR create a new issue and link here)

**Comment by dims** [comment]
The following are covered in #69976 
```
ithub.com/go-openapi/loads
github.com/go-openapi/spec
github.com/go-openapi/strfmt
github.com/go-openapi/validate
```

**Comment by bmcstdio** [comment]
The following are covered in #70136:

```
github.com/prometheus/client_golang
github.com/prometheus/client_model
github.com/prometheus/common
```

**Comment by wgliang** [comment]
The following are covered in #70136:

```
github.com/coreos/etcd
```

**Comment by jennybuckley** [comment]
cc @mbohlool

**Comment by sjgllghr** [comment]
The following are covered in #70292:
```
github.com/golang/glog
github.com/golang/groupcache
github.com/golang/mock
github.com/golang/protobuf
```

**Comment by TinySong** [comment]
The following are covered in #70332:

`github.com/container-storage-interface/spec`

**Comment by fdawg4l** [comment]
The following are covered in #70510

`github.com/vmware/govmomi`

**Comment by ameukam** [comment]
The following are covered in #70688: 
```
github.com/docker/distribution
github.com/docker/distribution/digestset
```

**Comment by hoangcao** [comment]
The following are covered in #70706 

github.com/godbus/dbus

**Comment by stafot** [comment]
The following is covered in https://github.com/kubernetes/kubernetes/pull/70744

`github.com/hashicorp/golang-lru`

**Comment by fdawg4l** [comment]
@thockin I don't know who the question is directed at, but I'll give my $.02.

> The devil you know is less dangerous than the devil you don't.

Depends on how much you trust your tests.

Until you need a new feature in a vendor dep, there really is no reason to upgrade it.  But, moving along with upstream has the added benefit of not needing to put in lots of time triaging integration issues later on when you really *do* need something new.  

You can keep up to date with your dependencies now, or put in the same amount of work later.  Or the other extreme is never updating your vendor dependencies because they're stable and you're afraid of regressions.

**Comment by hoangcao** [comment]
> This also gives a chance to get newer folks to try things out that is of value and help get their feet wet in our development processes, CI system etc.

+1 from new folk here. It provides us a valuable hand on task to understand more deeply about development processes, CI system ...

**Comment by thockin** [comment]
I don't buy those arguments.  

#27543 was a hostile thread which didn't actually make any arguments other than "you should update because there are updates".

The specific cases of needing to update seem to be working-as-intended to me.  We didn't update for a long time because we had no real need to.

 #69976 actually presented a reason to update.

I don't accept that giving new folks busywork is a goal of it's own, and especially when the risk incurred is so disproportionately high.  I'd prefer that we start culling dependencies entirely.  

I don't trust our tests to catch enough problems in our deps to justify willy-nilly updates.  If new people want to update deps, let's start by writing tests that cover the parts of those deps that we use, and let's write better import warnings.

Every time one of these PRs comes through some set of very busy people have to look at the code.  I don't have time for deep reviews of every dep, but  I do have to scan for obvious things.

I am putting this on sig-arch agenda for today with your name and mine, @dims.

**Comment by dims** [comment]
/close

let's wrap this up since we are so close to 1.13 code freeze. for 1.14, we will have more guidance on what criteria folks should use to update the dependencies too ( cc @deads2k )

**Comment by warmchang** [comment]
Consider this in the later release. 😃

**Comment by dims** [comment]
Justifications for updating a vendored dependency:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/godep.md#justifications-for-an-update

For future updates, each proposed PR should fall under one of those categories
