### ISSUE TITLE
Official coredns should be bound to nodeSelector: beta.kubernetes.io/os=linux

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#69773]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**:

In a windows cluster, containers can get scheduled on Windows nodes where they will never work.

Warning Failed 54m (x3 over 54m) kubelet, 35934k8s9000 Failed to pull image "coredns/coredns:1.2.2": rpc error: code = Unknown desc = no matching manifest for windows/amd64 in the manifest list entries

**What you expected to happen**:

CoreDNS starts and runs on Linux master nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Build a Windows Cluster.

Note:  I first encountered this issue when deploying with ACS-Engine:

https://github.com/Azure/acs-engine/issues/4011

but it occurs to me that it should be mirrored here, so that the relevant node selectors can be included in the canonical add-on directory.

/sig Windows

**Comment by johnbelamaric** [comment]
I suppose this is fine if there are always linux nodes in the cluster.

I don't know how Kubernetes or docker manifests work for windows, but CoreDNS does build and run on windows:

https://github.com/coredns/coredns/blob/master/Makefile.release#L114

That is not included in the manifest, is it possible to get that working? I guess you would probably also have to change the way the mounted config file is referred to in windows? Or is it this change good enough?

**Comment by chrisohaver** [comment]
> That is not included in the manifest, is it possible to get that working? I guess you would probably also have to change the way the mounted config file is referred to in windows?

Have not looked into it in detail yet, but one complication would be configuration. AFAIK Windows systems don't have an `/etc/resolv.conf`... and the default CoreDNS configuration makes specific reference to the file (to get upstream servers).

**Comment by johnbelamaric** [comment]
Yeah, good point. I was thinking about the -conf /etc/coredns/Corefile
which I think we pass to coredns IIRC. But resolv.conf is a bigger issue.
