### ISSUE TITLE
[Scheduler User Guide Documentation] How to configure your kubernetes scheduler?

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#69770]
PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE. We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: #69767

When we haven't used kube-scheduler or we haven't adjusted the kube-scheduler option, we'll be overwhelmed when we encounter some problems.

In fact, we adjust the weight ratio of different resources through some configuration to adjust the resource distribution of the cluster; even we can greatly improve the performance of the scheduling system just by modifying one option, such as the alwaysCheckAllPredicates option; etc. . .

So, we need a document(feel free to create in https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/scheduling) to explain the purpose of these options and how to adjust the kubernetes options to make kube-scheduler and kubernetes work better.

/sig scheduling
/kind documentation
/help
/good-first-issue

**Comment by wgliang** [comment]
@agladboy   Will the PR be ready for review soon? Or what progress has you made recently? 
Hope to get your feedback. :)

**Comment by agladboy** [comment]
@wgliang I'm beginning to work on it and I found that two documents are related to this topic,
a) https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
b)https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
I'm not sure which portion left I should be focusing to, more general, or update the article b. would you please give some input. Thanks!

**Comment by wgliang** [comment]
@agladboy Cool. You can send you PR just like https://github.com/kubernetes/website/pull/10702 or https://github.com/kubernetes/website/pull/10739.

**Comment by wgliang** [comment]
/ping @agladboy Will the PR be ready for review soon? Or what progress has you made recently?
Hope to get your feedback. :)

**Comment by agladboy** [comment]
@wgliang Thanks for asking! I will post the PR for the review by this week. :-)

**Comment by wgliang** [comment]
@agladboy Cool, thanks.

**Comment by agladboy** [comment]
@wgliang Will this document target to 1.13 release, if so I will rebase it to 1.13-dev. Thanks!

**Comment by wgliang** [comment]
@agladboy Good job. 
No, we may be planning on the next version. And we should have a lot of things to improve, we should not be able to catch up with this train of 1.13.

 :)
Thanks.
