### ISSUE TITLE
Containers periodically killed due to kubelet "No such container" error

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#69787]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig Windows

**What happened**:

  Normal   Created                 8m    kubelet, 29891k8s9000  Created container
  Normal   Pulled                  8m    kubelet, 29891k8s9000  Successfully pulled image "<repository>/powerflowclient:97"
  Normal   Started                 8m    kubelet, 29891k8s9000  Started container
  Warning  FailedSync              5m    kubelet, 29891k8s9000  error determining status: rpc error: code = Unknown desc = Error: No such container: fe3fe61341dd6267a5cfa6d8334d27731ee76db7f76b8d011b79da03a63ce037
  Normal   SandboxChanged          5m    kubelet, 29891k8s9000  Pod sandbox changed, it will be killed and re-created.

**What you expected to happen**:

No periodic container loss.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a cluster with ACS Engine 0.23.1 on Azure with Windows agents

**Anything else we need to know?**:

Docker Version 1.13.1

My apologies for filing this with so few logs.  If folks can advise me on how to acquire more information, I'll happily grab it.

**Environment**: 
Azure
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure 
- OS (e.g. from /etc/os-release): Windows 1803 on agents
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MarcPow** [comment]
Closing as non-actionable.

I suspect this is likely a bug in Docker EE 17.06 that I was using under Windows 1803.   But - in the absence of more data, it can't be fixed.  Closing it out so as not to clutter the queue.

**Comment by Suozz** [comment]
> Closing as non-actionable.
> 
> I suspect this is likely a bug in Docker EE 17.06 that I was using under Windows 1803. But - in the absence of more data, it can't be fixed. Closing it out so as not to clutter the queue.

hi, I meet the same problem and my docker's version, same with you, is 17.06. So do you know how to fix this bug
