### ISSUE TITLE
Profiling flag default value changed from true to false

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#69792]
For both kube-scheduler and kube-controller-manager, the `profiling` flag default changed, I believe accidentally.

kube-scheduler changed in #52562, cc @ironcladlou  (I think this is k8s 1.9)
kube-controller-manager changed in #60270 cc @stewart-yu  (I think this is k8s 1.11)

There was a similar issue with leader-election default changed, where we changed the default: #60524  Not sure of the timings here (was it in the same release)

I believe this is the root cause of #68606 and #67124

But cc @mikedanese because you mentioned that pprof was not turned on by default in #68366, yet this appears to only be true accidentally.  Also I think it is enabled by default for apiserver :-)

Two issues to unravel here I think:

* Should we keep the default as false for scheduler & k-c-m?  If we keep it we have to fix e.g. kubemark to set the profiling flag, otherwise it can't collect scheduler profiles.
* Assuming the default for apiserver is true, should we set the default to false, if we believe it to be unsafe?  (With a release note this time :-) )

**Comment by stewart-yu** [comment]
seems we have not setting default value for the `profiling` flag in `kube-controller-manager`

**Comment by mikedanese** [comment]
> Assuming the default for apiserver is true, should we set the default to false, if we believe it to be unsafe?

I'd recommend the we turn debugging handlers off by default on all binaries. Thanks for catching this.
