### ISSUE TITLE
miss oomkilled event

### ISSUE THREAD

**Issue by luzhzhsoft** [kubernetes/kubernetes#69798]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
when oom happend ,there no event appeared
**What you expected to happen**:
when oom happend,some event to desribe this phenomenon
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
please provide better description for your issue or try getting help on slack or the support channels:
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

/close
