### ISSUE TITLE
How to access environment variables inside container at runtime ? 

### ISSUE THREAD

**Issue by splnanthakumar** [kubernetes/kubernetes#69794]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by krmayankk** [comment]
Your question is not clear ? Do you mean from the code running inside the container ? In golang you can use https://golang.org/pkg/os/#Getenv

Providing more concrete examples will help otherwise this is an incomplete bug/issue
