### ISSUE TITLE
SELinux chcon relabelling considered harmful (for PVs)

### ISSUE THREAD

**Issue by anguslees** [kubernetes/kubernetes#69799]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT (sort of?)
/kind bug

**What happened**:

I had a large cephfs (rook) volume, and tried to mount it via the rook flexvolume on a coreOS node.  Dockerd on the node stopped responding, making the node go NotReady, and the huge number of setxattr calls DoSed my ceph metadata nodes, affecting other cephfs users in the cluster.

Consequently I've been learning about docker's SELinux relabelling, and afaics(*), it's only a good idea when it is absolutely required (local-subdirectory-based volumes: emptyDir, configMap, etc).   With this bug report, I propose we disable it almost everywhere, and replace it with the O(1) `context` mount option.

(*) This bug report is an attempt to flush out more knowledgeable opinions here.  The bug reports and discussions I've seen seem to explain or workaround the status-quo without actually asking **if it is the right approach for K8s**.

I figure we have roughly 3 categories of storage types:
- local subdirectories (emptyDir, configMap, downwardAPI, etc)
- ReadWriteOnce whole-filesystems (block devices)
- ReadWriteMany whole-filesystems (nfs, cephfs, glusterfs, etc)

The first category is trivially small, and walking the filesystem is fine.  We should use the existing docker recursive setxattr behaviour for those.  (Note for-real host-path k8s volumes already [disable](https://github.com/kubernetes/kubernetes/blob/8288d32a393394d716e04046a47e77fb1ac50ba0/pkg/volume/host_path/host_path.go#L209) relabelling because we don't want to mess with the host's filesystem).

Non-k8s docker usage doesn't really have those latter 2 categories.  This is where the docker relabelling falls down, and why I propose we should not use it for k8s.  For these latter 2 categories a far better option (afaics) is `mount -o context=...`, which is an **O(1) mount-time option that sets the label for the entire filesystem**.  This is _way_ better than walking the filesystem just to set every file to the same label.

Note also for the last category (ReadWriteMany), that the label needs to be consistent across all consumers, if using the chcon/setxattr approach (the existing docker behaviour, unless disabled).  I imagine this is the underlying reason that all the ReadWriteMany in-tree volume types [disable SELinux relabelling](https://github.com/search?q=%22SupportsSELinux%3A+false%22+repo%3Akubernetes%2Fkubernetes+path%3Apkg%2Fvolume+language%3AGo&type=Code), although this doesn't seem to be explicitly mentioned anywhere.  If the label was instead applied as a *mount option*, then the mapping only exists on the local client and the volume can be mounted on multiple nodes more easily.

**What you expected to happen**:

A PV to be mounted with something similar to the cost of just calling mount().  In general, I expect PVs to continue to be mountable, even when they contain large filesystems.

**How to reproduce it (as minimally and precisely as possible)**:

On a node OS that enables SELinux in either permissive or enforcing mode (eg: CoreOS, Atomic):

Fill a large cephfs volume (mine was ~60k files).  Attempt to start a pod that uses it via a rook flexvolume (not the in-tree ceph volume type, which disables SELinux relabelling).

Alternatively, attempt to use any other PV with a large filesystem.  Block-based PVs will be a lot faster, so the filesystem will need to be larger to clearly demonstrate the issue (I guess something around 10^5 - 10^6 files).

**Anything else we need to know?**:

The relabelling seems to occur for each container.  So the issue can further be exacerbated by starting a Pod with multiple containers, each of which use the same PV.

See also #27282

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}

- Cloud provider or hardware configuration: bare-metal / kubeadm
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.1.1
VERSION_ID=1911.1.1
BUILD_ID=2018-10-10-2057
PRETTY_NAME="Container Linux by CoreOS 1911.1.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux localhost 4.14.74-coreos #1 SMP Wed Oct 10 20:22:34 UTC 2018 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux
```

- Install tools: kubeadm
- Others:

**Comment by anguslees** [comment]
cc @gnufied.  I know it's a clickbait issue title, but what are your thoughts on moving SELinux relabelling to a mount-time `context` option instead?

**Comment by gnufied** [comment]
@anguslees It would be good to write some POCs around this area if you really want to pursue this. I see couple of problems which needs technical solution:

1. Typically if User does not specify a SELinux label then container runtime(docker et.el) will assign a unique MCS label to it and when mounting a volume with ":z" option, the volume also gets same MCS label. Have you considered how will this work when using `mount -o context` option? Will kubelet manage MCS labels? We will need to run some tests and write POCs. 
2. I was running some tests that use `chcon` and some that use `-o context` and I do not think they are equivalent. Have you tried mounting a volume with `svirt_sandbox_file_t` type which is typically required for accessing volumes within container. Does it work?

**Comment by anguslees** [comment]
> then container runtime(docker et.el) will assign a unique MCS label to it

Right.  I don't understand how this works currently given that a volume may be shared between multiple containers within a pod.  Afaics, we _need_ to allocate the label in the default case at *pod-level* (ie: somewhere in kubernetes/kubelet, not CRI/docker) in order to match expected k8s pod semantics.

This is based on a theoretical understanding though, since I've never actually used a system that _enforced_ SELinux policy :stuck_out_tongue: 

> tests that use chcon and some that use -o context and I do not think they are equivalent

Oh :(  that might mean we need to come up with another proposal then..  I hope we can make it work, because I don't have many other ideas that end with keeping SELinux support...

I don't have a lot of free time (of course), but the underlying issue impacts me directly so I'm motivated to get this fixed (or turn off SELinux on my systems entirely).  I'll try to set up an 'enforcing' test environment and gain some experience with typical usecases.

**Comment by dimm0** [comment]
This is still a huge issue for us. Jupyter notebooks spawn containers as a non-root user, and this relabelling prevents scientists from storing large datasets in their volumes (we use rook to manage ceph in our k8s cluster)
Rook guys already made fsgroup and selinux relabelling configurable (https://github.com/rook/rook/pull/2540#issuecomment-458668486), but I still see a slowdown when mounting volumes with large number of files, only if I set fsGroup in the pod spec.
Is there anything else happening on volume mount that should be disabled?

**Comment by dimm0** [comment]
We've accidentally got one node in the cluster with SELinux in permissive mode, and it was giving the error:

```
22s         Normal    Scheduled           Pod          Successfully assigned osg/stashcache-origin-merra2-7597cd494d-kdr62 to xcache-11.t2.ucsd.edu
2s          Normal    Pulling             Pod          pulling image "opensciencegrid/stash-origin:development"
1s          Normal    Pulled              Pod          Successfully pulled image "opensciencegrid/stash-origin:development"
1s          Normal    Created             Pod          Created container
1s          Warning   Failed              Pod          Error: failed to start container "stashcache-origin-merra2": Error response from daemon: error setting label on mount source '/var/lib/kubelet/pods/b17d64ec-3a2f-11e9-86c5-0cc47a6be994/volumes/ceph.rook.io~rook/fs-store': SELinux relabeling of /var/lib/kubelet/pods/b17d64ec-3a2f-11e9-86c5-0cc47a6be994/volumes/ceph.rook.io~rook/fs-store is not allowed: "operation not supported"
17s         Warning   BackOff             Pod          Back-off restarting failed container
```

Which tells me SELinux relabelling is still not off. Latest rook, recommended settings are set.

**Comment by mrballcb** [comment]
We have a Jenkins stack with a large jenkins home directory for the master on an EBS volume (not large in size, but large in number of files).  When the jenkins master restarts, it takes about 8 minutes for the pod to go from ContainerCreating to Running 0/1.  During that time we get several "Error: context deadline exceeded" messages.  We think it's selinux relabeling on this volume that's causing this long delay.  We're running Kube 1.10.12, so it's a bit older version.  It would be nice if there was a way to tell kube to mount this volume without selinux.

**Comment by andor44** [comment]
A temporary fix if you're okay with compiling your own kubelet is to change `SupportsSELinux` to `false` [here](https://github.com/kubernetes/kubernetes/blob/997d5182d0508d29612223fad9e2d10d3de73877/pkg/volume/rbd/rbd.go#L817).

**Comment by jingxu97** [comment]
cc @saad-ali @msau42

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
@anguslees not sure if you had a chance but we are trying to fix the issue in https://github.com/kubernetes/enhancements/pull/1621 

/remove-lifecycle-stale
