### ISSUE TITLE
"kubectl cp mypod:/ ..." truncates folder and file names

### ISSUE THREAD

**Issue by mmariani** [kubernetes/kubernetes#69804]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I asked kubectl to extract all the files in a container.

```
$ kubectl cp nginx:/ /tmp/nginx 
[...]
$ ls /tmp/nginx/
ar  bin  dockerenv  elinux  ev  ib  ib64  in  mp  nt  oot  pt  roc  rv  sr  tc  un  ys
```

Only the names of the top level entries are concerned.

**How to reproduce it (as minimally and precisely as possible)**:

Just cp the root folder somewhere.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: MaaS + juju
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5
- Kernel (e.g. `uname -a`): 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: juju bundle from canonical

**Comment by clickyotomy** [comment]
Hi, @WanLinghao - sorry, I didn't notice that this was assigned to you. Would you like me to close my PR?

**Comment by WanLinghao** [comment]
@clickyotomy never mind
