### ISSUE TITLE
Multimaster issue with etcd

### ISSUE THREAD

**Issue by vovkanaz** [kubernetes/kubernetes#69805]
Trying to do multi-master cluster,
First of all, we try to make a etcd cluster  based on this lhttps://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/
but we've got a result:
member 45bb04c0f4ab315b is healthy: got healthy result from https://XXX.XXX.XXX.XXX:2379
member ad96f29c89b43070 is healthy: got healthy result from https://XXX.XXX.XXX.XXX:2379
member ee4fa581d5988965 is unreachable: no available published client urls
cluster is healthy

docker run --rm -it --net host -v /etc/kubernetes:/etc/kubernetes quay.io/coreos/etcd:v3.2.18 etcdctl --cert-file /etc/kubernetes/pki/etcd/peer.crt --key-file /etc/kubernetes/pki/etcd/peer.key --ca-file /etc/kubernetes/pki/etcd/ca.crt --endpoints https://XXX.XXX.XXX.XXX:2379 cluster-health

member 45bb04c0f4ab315b is healthy: got healthy result from https:/XXX.XXX.XXX.XXX:2379
member ad96f29c89b43070 is healthy: got healthy result from https://XXX.XXX.XXX.XXX2:2379
member ee4fa581d5988965 is unreachable: no available published client urls
cluster is healthy

The first node where we are doing all configs, not working. ETCD Cluster is not available.
member ee4fa581d5988965 is unreachable: no available published client urls

Syslog:
Oct 15 13:27:20 ip-XXX.XXX.XXX.XX kubelet[2417]: F1015 13:27:20.798672    2417 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Oct 15 13:27:20 ip-XXX.XXX.XXX.XXX systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Oct 15 13:27:20 ip-XXX.XXX.XXX.XXX systemd[1]: kubelet.service: Failed with result 'exit-code'

Kubernetes 1.11, 1.12 Thanks a lot, and waiting for your response. Ubuntu 18.04

**Comment by vovkanaz** [comment]
https://github.com/kubernetes/kubernetes/issues/66108 
As we saw, we'll need to execute sudo kubeadm token create --print-join-command before setup... but in official docs no any word about this https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/#before-you-begin

**Comment by neolit123** [comment]
this seems to be an user issue on your side.

tokens expire after 24 hours. call again `kubeadm init` and the command at the end should be used for `kubeadm join` for other nodes.
this works perfectly fine for other users.

for questions you can also try our support channels:
e.g. stackoverflow or #kubeadm on slack:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close
