### ISSUE TITLE
CSI plugin e2e testing discussion

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#69819]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-feature-requests 

**What happened**:
I want to summarize my thoughts on how I think we should support running e2e tests against CSI plugins, and open it up for discussion.

Instead of running plugin e2e tests in kubernetes core, I think each CSI plugin should be responsible for setting up and running Kubernetes e2e tests from their own plugin repo.  My reasoning:

* CSI's goal is to move driver implementations out of tree.  That should apply to tests using those drivers too.
* Along the same lines, we can't feasibly maintain and include every single CSI plugin into the core kubernetes e2e tests.
* Each plugin may need special environment setup, which can be complex to add to the core kubernetes framework.

Some exceptions may include vendor-neutral CSI plugins like hostpath and nfs which can run on any environment.

To accomplish this, I want to move to a model where we:

* Provide a set of generic test suites as a library that can be imported into vendor's driver repos.  The test suites should have enough callouts for environment-specific setup/teardown.
* We could have some sort of common test dashboard in kubernetes-csi where vendors could report their test results.
* As a bonus, this generic test suite should also run the same tests that in-tree drivers run so we don't have to make separate test cases for CSI vs in-tree.

Advantages include:

* Vendors are free to setup whatever permutations of Kubernetes, kubernetes-csi sidecar, and CSI plugin versions they want to test.
* Vendors don't have to checkin to kubernetes/kubernetes every time they want to update their driver deployments or change some version
* All vendor plugin updates and e2e test changes can be checked into the same repo at the same time
* Vendors immediately get a set of Kubernetes test cases to run without having to explicitly write test cases for them (reduce duplication).

Downsides include:

* Vendors need to setup and maintain their own CI infra.  I think this is already a challenge for vendors that have their own CI not in kubernetes/kubernetes.
* Any updates to the CSI e2e test suites in kubernetes/kubernetes cannot be immediately validated against a vendor's CSI plugin.  Only CSI plugins that we decide to keep testing in-tree can be validated.  Some features not supported by the in-tree drivers may not be testable by default without some mock driver implementation.
* We lose pull job signal if a change in Kubernetes core breaks CSI in ways that the hostpath plugin cannot detect.  Once migration is done though, we should regain signal for at least in-tree drivers.

**Comment by msau42** [comment]
https://github.com/kubernetes/kubernetes/pull/68025 is helping to move in this direction

**Comment by pohly** [comment]
> Provide a set of generic test suites as a library that can be imported into vendor's driver repos.

This is currently very hard to do due to the monolithic nature of the Kubernetes E2E framework and its huge dependency tree. PR #68483 addresses that, but there has been some opposition against it. People interested in the topic should join the SIG-storage meeting tomorrow (2018-10-15) where this will be discussed.

> The test suites should have enough callouts for environment-specific setup/teardown.

If we add enough configuration options to the e2e.test binary published as part of a Kubernetes release, then that might be enough for testing vendor CSI drivers. But then vendors still can't write custom tests *and* have to run their own CI, so I see this only as the second best solution.

**Comment by msau42** [comment]
You mean sig-testing meeting?

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:

> You mean sig-testing meeting?

Yes, sorry for the typo. Here's the meeting document:
https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit#heading=h.ordpxvv8yiv3

**Comment by jsafrane** [comment]
While I agree that it should be possible for storage vendors to run any e2e tests with Kubernetes and their driver easily, at the same time we need to ensure Kubernetes API compatibility. When we move volume plugins from in-tree to CSI, we must test that existing API works and is translated to CSI in a seamless way.

Whether it is in kubernetes/kubernetes or e.g. kubernetes-sigs/gcp-compute-persistent-disk-csi-driver is another question. But it should be under Kubernetes control and we should even block a release if compatibility gets broken.

**Comment by msau42** [comment]
To clarify, existing in-tree tests still remain.  The ultimate test for migration is if those tests still pass without any changes needed.

**Comment by msau42** [comment]
Work to make in-tree and CSI drivers run the same tests: https://github.com/kubernetes/kubernetes/issues/68024

**Comment by pohly** [comment]
/reopen

While using the E2E framework and the storage testsuite out-of-tree should be possible already, work on making this easier continues. For example, the storage testsuites API and implementation is going to change (https://github.com/kubernetes/kubernetes/pull/72434).

**Comment by davidz627** [comment]
From the original post:
- [x] Provide a set of generic test suites as a library that can be imported into vendor's driver repos. The test suites should have enough callouts for environment-specific setup/teardown.
- [ ] We could have some sort of common test dashboard in kubernetes-csi where vendors could report their test results.
- [x] As a bonus, this generic test suite should also run the same tests that in-tree drivers run so we don't have to make separate test cases for CSI vs in-tree.

Looks like the last thing remaining is to have a common dashbaord

**Comment by msau42** [comment]
I'm not sure if we really need a common dashboard.  We at least have in-tree + hostpath csi driver results on the same dashboard: https://k8s-testgrid.appspot.com/sig-storage-kubernetes

I'm going to consider this done :-)
/close
