### ISSUE TITLE
[sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#69815]
This test has been failing since 10/13.

Dashboard: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-master-scale-correctness

Sample Failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/167

This test failure will block 1.13 beta (being in the [sig-release-master-blocking group](https://k8s-testgrid.appspot.com/sig-release-master-blocking)) so please let's fix it before then. Thanks!

/sig api-machinery
/kind failing-test
/priority important-soon

**Comment by fedebongio** [comment]
Hi @mariantalla! 

Please see #63622. This seems to be a duplicate of this one? Or this one is only for 1.13? 

Anyways, there's a PR #68300 that hopefully will fix it, by upgrading the sample APIserver to 1.10.

**Comment by fedebongio** [comment]
PR is merged, test looks good.

**Comment by mortent** [comment]
This seems to be a duplicate of #63622 and the test is passing in the api-machinery dashboard now. Closing this one.

/close
