### ISSUE TITLE
kube-dns 2/3 Running : Error getting metrics from dnsmasq

### ISSUE THREAD

**Issue by shawnhankim** [kubernetes/kubernetes#69833]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network
/sig aws
@kubernetes/sig-network-bugs

**What happened**:
* Occasionally, one of three kube-dns pods are not running as follows. 

| NAMESPACE   | NAME                                                    | READY | STATUS  |
|---------------|--------------------------------------|--------|----------|
| kube-system   | pod/kube-dns-7566b4f88b-4vqw5  | 2/3       |  Running |

**What you expected to happen**:
* I wanted to expect that all of three kube-dns pods are successfully running as follows.

| NAMESPACE   | NAME                                                    | READY | STATUS  |
|---------------|--------------------------------------|--------|----------|
| kube-system   | pod/kube-dns-7566b4f88b-4vqw5  | 3/3       |  Running |

**How to reproduce it (as minimally and precisely as possible)**:
* This is an occasional issue.
* Therefore, it is hard to be reproduced.

**Anything else we need to know?**:
* I am using Kubernetes 1.10.5
* Among three containers (kubedns, dnsmasq, sidecar), you could find the following error message.
```bash
$ kubectl -n kube-system logs kube-dns-7566b4f88b-4vqw5 -c kubedns

$ kubectl -n kube-system logs kube-dns-7566b4f88b-4vqw5 -c dnsmasq

$ kubectl -n kube-system logs kube-dns-7566b4f88b-4vqw5 -c sidecar
I0925 23:30:29.158874       1 main.go:51] Version v1.14.8.3
I0925 23:30:29.159297       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0925 23:30:29.159329       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
I0925 23:30:29.159375       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:1}
W0925 23:30:29.159729       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:38489->127.0.0.1:53: read: connection refused

Sometimes, you could find the following message.
W0925 12:38:52.621962       1 server.go:64] Error getting metrics from dnsmasq: dial udp 127.0.0.1:53: i/o timeout


```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.5+coreos.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CentOS Linux 7.1706 (Core)
- Kernel (e.g. `uname -a`): Linux 3.10.0-514.26.2.el7.x86_64
- Install tools: go1.9.3, gc
- Others: linux/amd64

**Comment by shawnhankim** [comment]
@kubernetes/sig-Network

**Comment by hofmeister** [comment]
We're seeing the same behaviour on GCP - resulting in internal service calls getting back a "host not found" error because the DNS system is down momentarily.
