### ISSUE TITLE
[Scheduler User Guide Documentation] Choose scheduling algorithms and strategies for your cluster

### ISSUE THREAD

**Issue by wgliang** [kubernetes/kubernetes#69840]
PLEASE COORDINATE WITH SIG-SCHEDULING BEFORE WORKING ON THIS ISSUE. We want to avoid the situation where two people accidentally start work on the same fix.
Main tracking issue: #69767

We all know that the kube-scheduler algorithm contains many predicates and priorities, all of which are derived from some common scheduling scenarios. But many users don't understand their role, and they don't know how to choose. 

So, we need to explain in detail the scheduling algorithm and how it works. How should we debug when something goes wrong? 
You can submit the document to the https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/scheduling directory in PR.

/sig scheduling
/kind documentation
/help
/good-first-issue

**Comment by wgliang** [comment]
_Then it can be changed dynamically._
@wenlxie It may not be a good idea to dynamically change the scheduling policy directly through the default scheduler, which is highly complex. I would recommend using the extended scheduler to do it.

**Comment by saurav-malani** [comment]
@wgliang @wenlxie I would like to work on this issue.

**Comment by wgliang** [comment]
@saurav-malani Thank you very much for your help, you can feel free to leave comments here if you have any questions.

**Comment by saurav-malani** [comment]
Hello @wgliang, can you help me by pointing any relevant doc related to the scheduling algorithm, where I can get to know what scheduling algo's exist and how they work?

**Comment by wgliang** [comment]
@saurav-malani 
In addition to the source code, we currently lack detailed official documentation, which is where we need to work hard. 

In fact, some of the best kube-scheduler documentation was not written by us!

e.g.
https://jvns.ca/blog/2017/07/27/how-does-the-kubernetes-scheduler-work/
http://alexandrutopliceanu.ro/post/scheduling-in-kubernetes/
https://searchitoperations.techtarget.com/definition/Kubernetes-scheduler
https://thenewstack.io/implementing-advanced-scheduling-techniques-with-kubernetes/

So, you need to study kube-scheduler in detail and record it.

**Comment by wgliang** [comment]
/ping @saurav-malani Will the PR be ready for review soon? Or what progress has you made recently?
Hope to get your feedback. :)

**Comment by wgliang** [comment]
@saurav-malani What progress has been made recently?

**Comment by SurenNihalani** [comment]
I'd like to work on this. Could anyone from the sig group assign it to me?
