### ISSUE TITLE
Override bootstrap policy

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#69864]
We want to disallow regular users from creating PDBs but unfortunately the bootstrap policy is hardcoded in the API server and we cannot really override it. Is there a way to achieve this currently? If not, we probably want the ability to be able to configure it.

@deads2k @sttts @smarterclayton @mfojtik @jim-minter @pweil-

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by liggitt** [comment]
/sig auth
/remove-sig api-machinery

You can modify default roles and disable reconciliation by setting the `rbac.authorization.kubernetes.io/autoupdate` annotation to `false`

**Comment by kargakis** [comment]
Awesome, thanks @liggitt !
