### ISSUE TITLE
Inconsistent default ports for `kubectl` and `kubectl --server 127.0.0.1`

### ISSUE THREAD

**Issue by kkimdev** [kubernetes/kubernetes#69894]
When there is no configuration, kubectl's default port changes depending on --server argument

```bash
# Tries to connect 127.0.0.1:8080
kubectl cluster-info
```

```bash
# Tries to connect 127.0.0.1:80
kubectl cluster-info --server 127.0.0.1
```

I think just specifying ip with --server shouldn't change the default port.  Or make the port required for --server option

**Comment by liggitt** [comment]
--server is parsed as a url, with default port semantics per protocol (http defaults to port 80, https to port 443). We don't merge in parts of the default address (protocol, host, or port)

/close
