### ISSUE TITLE
Can't start pods in Windows Server 2019

### ISSUE THREAD

**Issue by benmoss** [kubernetes/kubernetes#69901]
/kind bug

**What happened**:
Scheduling a container on Windows 2019 results in "Error: failed to start container".

**What you expected to happen**:
Pod should start, ping localhost

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy [this](https://gist.github.com/benmoss/abd68923acaccb2ca10388ff69f9908b) deployment
- Pod should report as failing

**Anything else we need to know?**:
We tried this deployment with both nanoserver:1809 and servercore:1809 and both exhibit the same problem. We can run both of those images via `docker run` and they start fine.

We're using Docker 18.03.1-ee-3, and Flannel with the overlay backend.

Full error message from `kubectl describe pod`:

```
Error response from daemon: container windowswebserver encountered an error during CreateContainer: failure in a Windows system call: The parameter is incorrect. (0x57) extra info: {"SystemType":"Container","Name":"windowswebserver","Owner":"docker","VolumePath":"\\\\?\\Volume{79402dc3-d182-11e8-a2cb-cec92004004a}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\windowswebserver","Layers":[{"ID":"4d1d619f-e731-5d80-9609-c7e0c25ccade","Path":"C:\\ProgramData\\docker\\windowsfilter\\cc6cf29dec8f97281c8fc72d9ec5db437d34b6aad0c3344ff94fe346b36c023e"}],"ProcessorWeight":5000,"HostName":"win-webserver-6545d59c4d-n9c45","MappedDirectories":[{"HostPath":"c:\\var\\lib\\kubelet\\pods\\fb9f05e8-d18c-11e8-a1af-005056bad04d\\volumes\\kubernetes.io~secret\\default-token-rfxk2","ContainerPath":"c:\\var\\run\\secrets\\kubernetes.io\\serviceaccount","ReadOnly":true,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"NetworkSharedContainerName":"f5e8564b0077b391b9cb3742544ad1ee6ad87d37d50d4621b0d35026e792b325","EndpointList":["6D5A40BA-9E84-4607-ABD0-6A36843C692E"]}
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release): Windows 2019
- Kernel (e.g. `uname -a`): 10.0.17763.1
- Install tools: BOSH

@PatrickLang 
/sig windows

**Comment by ddebroy** [comment]
Since you are trying to run on Windows Server 2019, your base images should point to 2019 as well. In the linked yaml, it shows:

```
containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/nanoserver:1809
        imagePullPolicy: IfNotPresent
        command:
        - ping
        - -t
        - localhost
```

To get above to run on Windows Server 2019, I think you either need to point the base image to `mcr.microsoft.com/windows/nanoserver:ltsc2019` or specify hyper-v isolation annotation as mentioned in https://kubernetes.io/docs/getting-started-guides/windows/#hyper-v-containers

**Comment by feiskyer** [comment]
> Since you are trying to run on Windows Server 2019, your base images should point to 2019 as well. 

1809 is actually the same with ltsc2019, but both of them are not available temporarily. They will be pushed again when Windows Server 2019 starts its new rollout.

**Comment by ddebroy** [comment]
My bad .. I misread 1809 as 1803. Please ignore the suggestion for hyper-v isolation above.

**Comment by benmoss** [comment]
related to https://github.com/moby/moby/issues/37832

**Comment by PatrickLang** [comment]
This will be fixed in a Windows patch, ETA late January. Windows OS bug number is 19831298

**Comment by daschott** [comment]
Can you validate that this is fixed in KB4476976. ETA for release is tomorrow.

**Comment by sumantfordev** [comment]
All of a suddent, i also started facing this issue in GKE, what are the possible cases for this issue to occur?

**Comment by jayunit100** [comment]
in general , i think if you are running the most up to date windows patches, this gets fixed automagically for you
