### ISSUE TITLE
LDAP User Accounts, UID Mappings and automatically run certain deployments as the uid of user who created the deployment 

### ISSUE THREAD

**Issue by slecrenski** [kubernetes/kubernetes#69909]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

There does not seem to be a mechanism besides maybe using OIDC to do User Authentication.  Which honestly I have yet to try out.  Service Accounts seem to be the main way to do security.

**What you expected to happen**:

I would like to allow users to login to the kubectl with say "kubectl login userid" and run kubectl create -f deployment.yaml and all associated pods run as the LDAP UID of the associated LDAP User who logged in.  People who are members of specific LDAP groups can deploy components into specific namespaces.  This would allow for a running pod to access NFS shares which are exported to the K8s hosts.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

If no one else wants to work it I would be interested in contributing.  Could be interested to use Kerberos with SSSD to LDAP and/or AD.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.9.6
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.xx
- Install tools: yum
- Others:

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/31517 for previous LDAP discussion

xref https://github.com/kubernetes/kubernetes/issues/13306 for recording/propagating creating user
