### ISSUE TITLE
Etcd-server-events memory leak?

### ISSUE THREAD

**Issue by Jarch09** [kubernetes/kubernetes#69915]
**Is this a BUG REPORT or FEATURE REQUEST?**:
**BUG REPORT**

/kind bug
/sig area/etcd

**What happened**:
I recently built a HA kube cluster using KOPS on AWS and seem to be having a memory leak. The working set & memory usage for the `etcd-server-events` pods have been increasing linearly since the cluster was created.

**What you expected to happen**:
Not to have a memory leak.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes/kops/issues/5941

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-10-05T03:09:14Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider or hardware configuration: `AWS`
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
```

- Install tools: `kops`
- Others:

I'm relatively new to kube so may be missing something obvious. Thank you for your help.

**Comment by jpbetz** [comment]
Doesn't appear to be an api-machinery issue, and the issue already opened against kops should be sufficient, any reason why there should be a kubernetes issue at all?

/remove-sig api-machinery

**Comment by Jarch09** [comment]
I made issues on both, because I didn't know the best location... would this be an issue with kops? Seems like kind of a fundamental kube thing if `etcd-server-events` is leaking - but maybe misunderstanding

**Comment by jpbetz** [comment]
Humm. `etcd-server-events` is not a pod I'm familiar with, which is what made me think it must be some kops thing.  But after searching around a bit, the only pod manifest I can find for it is this one for kubemark testing:

https://github.com/kubernetes/kubernetes/blob/8b36038b413dbb17cfef750d1b02e371903846cd/test/kubemark/resources/manifests/etcd-events.yaml#L1-L4

Do you know where the pod manifest your using came from and if it's the same one as the kubemark one?

As for the leak. I suspect it's not actually a leak, but a steady increase in total events stored in etcd. I see from the other issue that the memory increase was from ~370MiB to ~760MiB.  This is well within the healthy operating range of etcd under moderate to high event load.  I suspect that this is 'working as intended", but your'e welcome to review your etcd db keyspace size to see if it's out of line with the memory utilization. Also double check if your counting resident memory or virtual memory as etcd allocates a considerable amount of virtual memory for mmapped files and such that doesn't not acount against the processes resident memory budget.

**Comment by Jarch09** [comment]
Thanks for the reply - appreciate the help.

Here's the container:
```
 etcd-container:
    Container ID:  docker://5698a7c470c62b6b1a670b6d8f0603367230cc477292c557e84c1615f0862e21
    Image:         k8s.gcr.io/etcd:2.2.1
    Image ID:      docker-pullable://k8s.gcr.io/etcd@sha256:19544a655157fb089b62d4dac02bbd095f82ca245dd5e31dd1684d175b109947
    Ports:         2381/TCP, 4002/TCP
    Host Ports:    2381/TCP, 4002/TCP
    Command:
      /bin/sh
      -c
      mkfifo /tmp/pipe; (tee -a /var/log/etcd.log < /tmp/pipe & ) ; exec /usr/local/bin/etcd  > /tmp/pipe 2>&1
```

The manifest is from `KOPS`

The memory for the offending pods is now ~1.4GiB (still linear increase). Your suggestion that maybe it's just a steady increase in events sounds plausible, and I'll look into this. Does etcd purge stored events at any point, or is this just going to continue building up forever?
