### ISSUE TITLE
Add more projected volume e2e test cases

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#69911]
**Is this a BUG REPORT or FEATURE REQUEST?**:

@kubernetes/sig-storage-feature-requests 

**What happened**:
While refactoring the e2e tests as part of https://github.com/kubernetes/kubernetes/pull/68910#discussion_r223863346 , there were a few more test cases identified that can be added for projected volumes:
* non-optional for secrets
* non-optional should fail for secrets when key doesn't exist
* non-optional should fail for configmaps when key doesn't exist

**Comment by msau42** [comment]
@spiffxp would you be able to help find someone to work on this?

**Comment by spiffxp** [comment]
Sure, these look like they can flesh out conformance coverage for us

/area conformance
/assign @mgdevstack

FYI @pontiyaraja
