### ISSUE TITLE
sign in pod automatically quit

### ISSUE THREAD

**Issue by 185866519** [kubernetes/kubernetes#69923]
kubectl --request-timeout=10m  exec -it XXX    bash --namespace=dev-name

Sign in pod,it happen tomatically quit.

**Comment by liggitt** [comment]
make sure your --namespace arg comes before the command passed to exec or it will get sent to the pod as part of the command

beyond that, there's not a lot of information provided here. can you provide pod logs, or info about the pod, or trace output of the exec command (add --v=9, remove any credentials from trace output)?
