### ISSUE TITLE
cpumanager: Mixing workloads with pinned and non-pinned CPUs lead to unexpected results.

### ISSUE THREAD

**Issue by vladikr** [kubernetes/kubernetes#69932]
/kind bug

**What happened**:

I wanted to point out some issues that I've encountered with the cpu-manager.

When starting a pod with pinned CPUs, makes the cpu-manager to pin it's container to specific CPUs.

`/sys/fs/cgroup/cpuset/cpuset.cpus: 1,2`

However, if one starts another pod with a non-pinned CPUs, the cpu-manager doesn't exclude the already assigned CPU and lets the pod run on __all__ available CPUs.

`/sys/fs/cgroup/cpuset/cpuset.cpus: 0-3`

Similar behavior takes place when a non-pinned workload is already running on a node. cpu-manager will allow this workload to run on a pod with pinned CPUs as well.

**What you expected to happen**:
My expectation was that workloads with "guaranteed" CPUs will be pinned and get "dedicated" CPUs.
I'd like to get a clarification about whether this is expected behavior or is it an issue that should be resolved?

/sig node
/sig scheduling

**Comment by jeremyeder** [comment]
@balajismaniam have you seen something like this?  I cannot repro

**Comment by balajismaniam** [comment]
@jeremyeder I haven't seen this before. @vladikr which version of Kubernetes is being used?

**Comment by vladikr** [comment]
@balajismaniam I tried to reproduce the same with 1.11.0

```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}```

 I can't reproduce it now...

```
pod with pinned cpus:
[root@vmi-pinned /]# cat /sys/fs/cgroup/cpuset/cpuset.cpus 
1-2

Non-pinned cpus:
[root@vmi-ephemeral /]# cat /sys/fs/cgroup/cpuset/cpuset.cpus
0,3```

Previously I was on v1.10.4

**Comment by linericyang** [comment]
I also cannot produce this issue on v1.10.4.

**Comment by balajismaniam** [comment]
@fabiand Is this still an issue? I've not seen this kind of issue before. We have run mixed workloads with no issues. See https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/ for example.

**Comment by fabiand** [comment]
I had to check. Actually: No. Not an issue anymore, we could not reproduce it.

/close
