### ISSUE TITLE
the unit of rate which passed to bandwidth cni plugin are not bps

### ISSUE THREAD

**Issue by 420691301** [kubernetes/kubernetes#69957]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

According to the [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L379)，the units of rate parameter which passed to bandwidth cni are Kbps，not bps , but bandwidth cni plugin need rate parameter in [bps](https://github.com/containernetworking/plugins/blob/master/plugins/meta/bandwidth/main.go#L35)

**What you expected to happen**:
If I'm not mistaken，I will make PR to fix it .

**Comment by m1093782566** [comment]
cc @squeed
