### ISSUE TITLE
I can't get a shell using ssh from localhost to Pod

### ISSUE THREAD

**Issue by kwkimg3100** [kubernetes/kubernetes#69962]
**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.1
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: yum

I made hadoop image based on centos7 using dockerfile. And I need to configure cluster now using `ssh-copy-id`.
But an error has occured. 

`[root@master object]# kubectl get pods -o wide`
<pre>NAME                   READY   STATUS    RESTARTS   AGE   IP            NODE      NOMINATED NODE
hadoop-master-pod      1/1     Running   0          56m   10.244.10.8   slave07   <none>
hadoop-secondary-pod   1/1     Running   0          56m   10.244.4.3    slave05   <none>
hadoop-ssh-pod         1/1     Running   0          37m   10.244.8.7    slave11   <none></pre>
`[root@hadoop-master-pod hadoop]# ssh-copy-id 10.244.4.3`
<pre>/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: connect to host 10.244.4.3 port 22: Connection refused</pre>

From Pod to localhost, ssh works well. And ping also works well with each other. Also, openssh-server is installed in Pod. However, the status of sshd cannot be checked. Because `systemctl` cannot be used in Pod.
<pre>[root@hadoop-master-pod hadoop]# systemctl status sshd
Failed to get D-Bus connection: Operation not permitted</pre>

This is my Dockerfile
<pre>FROM docker.io/centos:latest
MAINTAINER "User"

USER root

# install base tools and download hadoop
RUN yum clean all
RUN rpm --rebuilddb
RUN yum update -y
RUN yum install -y curl tar openssh-server openssh-clients net-tools
RUN curl -LO 'http://mirror.navercorp.com/apache/hadoop/common/hadoop-3.1.1/hadoop-3.1.1.tar.gz'

# install java
RUN yum install -y java-1.8.0-openjdk-devel.x86_64

# set hadoop
RUN tar xzvf hadoop-3.1.1.tar.gz
RUN mkdir -p /root/opt/hadoop
RUN mv hadoop-3.1.1 /root/opt/hadoop
RUN rm -f hadoop-3.1.1.tar.gz

# set enviroment
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64
ENV HADOOP_HOME /root/opt/hadoop/hadoop-3.1.1
ENV PATH=$PATH:$HADOOP_HOME/sbin/:$HADOOP_HOME/bin:$JAVA_HOME/bin
ENV HDFS_NAMENODE_USER="root"
ENV HDFS_DATANODE_USER="root"
ENV HDFS_SECONDARYNAMENODE_USER="root"
ENV YARN_RESOURCEMANAGER_USER="root"
ENV YARN_NODEMANAGER_USER="root"
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64' >> hadoop-env.sh

# set xml
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN sed -i 's/<configuration>/<configuration>\n<property>\n<name>fs.defaultFS<\/name>\n<value>hdfs:\/\/master:9000<\/value>\n<\/property>/g' core-site.xml
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN sed -i 's/<configuration>/<configuration>\n<property>\n<name>dfs.replication<\/name>\n<value>1<\/value>\n<\/property>\n<property>\n<name>dfs.namenode.name.dir<\/name>\n<value>\/root\/opt\/hadoop\/hadoop-3.1.1\/data\/dfs\/namenode<\/value>\n<\/property>\n<property>\n<name>dfs.namenode.checkpoint.dir<\/name>\n<value>\/root\/opt\/hadoop\/hadoop-3.1.1\/data\/dfs\/namesecondary<\/value>\n<\/property>\n<property>\n<name>dfs.datanode.data.dir<\/name>\n<value>\/root\/opt\/hadoop\/hadoop-3.1.1\/data\/dfs\/datanode<\/value>\n<\/property>\n<property>\n<name>dfs.namenode.http-address<\/name>\n<value>master:9870<\/value>\n<\/property>\n<property>\n<name>dfs.namenode.secondary.http-address<\/name>\n<value>secondary:9868<\/value>\n<\/property>/g' hdfs-site.xml
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN sed -i 's/<configuration>/<configuration>\n<property>\n<name>yarn.nodemanager.aux-services<\/name>\n<value>mapreduce_shuffle<\/value>\n<\/property>/g' yarn-site.xml
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN sed -i 's/<configuration>/<configuration>\n<property>\n<name>mapreduce.framework.name<\/name>\n<value>yarn<\/value>\n<\/property>/g' mapred-site.xml

# make files
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN echo 'master' > masters
WORKDIR /root/opt/hadoop/hadoop-3.1.1/etc/hadoop
RUN sed -i 's/localhost/slave01\nslave02/g' workers

# listening port
EXPOSE 22

# CMD
CMD ["/usr/sbin/sshd", "--foreground"]</pre>

This is my master-pod yaml file.
<pre>apiVersion: v1
kind: Pod
metadata:
 name: hadoop-master-pod
 labels:
  app: hadoop-master-label
spec:
 volumes:
 - name: master-volume
#   hostPath:
#    path: /volume/master
 containers:
 - name: hadoop-master-con
   image: 192.168.50.130:5000/hadoop_test19:latest
   ports:
   - containerPort: 22
   command: [ "/bin/bash", "-c", "--" ]
   args: ["while true; do sleep 30; done;" ]</pre>
secondary-pod yaml is shown above.

How can I solve this problem?

**Comment by neolit123** [comment]
this is a tracker for bug and feature requests.
please try on stackoverflow, slack or our support channels.
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/#help-my-question-isn-t-covered-i-need-help-now

thanks.
/triage support
/close
