### ISSUE TITLE
Kuberneter v1.12.1 can't mount glusterfs volume with older gluster client

### ISSUE THREAD

**Issue by aga20** [kubernetes/kubernetes#69963]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We try to integrate v1.12.1. When we try to use glusterfs volume the kubelet can't able to mount it. 
Gluster client version:  glusterfs 3.10.12

I tried to investigate the problem and I think the problem is next: 
[Here](https://github.com/kubernetes/kubernetes/blob/release-1.12/pkg/volume/glusterfs/glusterfs.go#L365) you try to check the error message if the mount failed with auto_mount option:

But in my case the response is next (I manually added a log line to the code): 
{"msg":"I1018 05:47:40.593370    9295 glusterfs.go:365] exit status 1"}

So the check is wrong in my case. Of course when I give out manually the nsenter command I saw `Invalid argument` error message but somehow this message converted to `exit status 1` in the glusterfs.go.

**What you expected to happen**:
Mount the gluster volume.

**How to reproduce it (as minimally and precisely as possible)**:
Use 3.10.12 with kubernetes v1.12.1 and try out glusterfs volume type. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"archive", BuildDate:"2018-10-08T12:08:58Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release): RedHat 7.5 with newer kernel
- Kernel (e.g. `uname -a`): 
Linux multi-zadory-2731-2018-10-13--12-infra-node-1 4.4.159-1.el7.elrepo.x86_64 #1 SMP Sat Sep 29 08:16:29 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others: Kubelet run in container

@humblec please chekc it. Thanks!

**Comment by humblec** [comment]
@aga20 Can you update your client, I mean can you update glusterfs-fuse and client packages to available latest version ?

**Comment by aga20** [comment]
@humblec thank you! I tried out with 3.12.15 and as I see it can work in our system. I close the issue but just note: I can upgrade but if someone can't maybe this issue will be important. 
Thank you!
