### ISSUE TITLE
internal elb created under EKS is being launched under random AZ

### ISSUE THREAD

**Issue by ping2kalesh** [kubernetes/kubernetes#69971]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**: While exposing a deployment with service type load balancer (internal), the load balancer is not considering one of the AZs.

**What you expected to happen**: The internal load balancer should be launched into all the availability zones. But it randomly selecting only one AZ.

**How to reproduce it (as minimally and precisely as possible)**: 
step1: Launch worker nodes in private subnets and register them with EKS service. 
step2: tag the private subnets with:
key: kubernetes.io/role/internal-elb 
value: 1

step3: create a deployment
step4: expose the deployment using service type load balancer and use the following annotation in the service manifest to create an internal load balancer: 
[...]
metadata:
    name: my-service
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
[...]

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.12.1
- Cloud provider or hardware configuration: EKS (AWS) 1.10.3
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ping2kalesh** [comment]
@kubernetes/sig-cloud-provider

**Comment by ping2kalesh** [comment]
@adubkov All the subnets are private subnets.

**Comment by mattmessinger** [comment]
We have this same issue w/ a non-internal ELB/NLB.  

We installed EKS into an existing VPC and 3 private subnets, each in a different AZ.  We tagged the public subnets and igw with the correct cluster key/value (kubernetes.io/cluster/<cluster> | shared). The ELB/NLB is always created in a single public subnet in AZ us-west-2a. 

We created a second EKS cluster in the same VPC, followed the same procedure above, and it always creates the ELB/NLB in us-west-2a and us-west-2b (2 AZ's) but never the third, us-west-2c.

All 3 public subnets have the same igw in their routing tables.

**Comment by aimanparvaiz** [comment]
I am facing a similar issue, I created EKS in an existing VPC and all worker nodes are in private subnets. All private subnets are tagged with     `kubernetes.io/role/internal-elb` and `kubernetes.io/cluster/<cluster-name>`     
when I deploy a service and expose it behind an internal load balancer 
```  
annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
 I noticed that internal LB always skip one AZ, when I add it manually using the AWS console it works just fine and all 3 instances are marked in service.
