### ISSUE TITLE
undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions

### ISSUE THREAD

**Issue by myvker** [kubernetes/kubernetes#69972]
root@user:~/go/src/k8s.io/kubernetes/cmd/kube-apiserver # go build -v
k8s.io/kubernetes/cmd/kube-apiserver/app
# k8s.io/kubernetes/cmd/kube-apiserver/app
app/server.go:461:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/69974

/close
