### ISSUE TITLE
Kubelet can’t access apisever

### ISSUE THREAD

**Issue by wooyanger** [kubernetes/kubernetes#69973]
When add the “rotateCertificates” in kubelet config file,the kubelet can’t access apiserver.

**Comment by liggitt** [comment]
please include the versions of the apiserver and kubelet you are running, the full invocations of the apiserver, controller manager, and kubelet, and the relevant kubelet logs

**Comment by wooyanger** [comment]
**This is my version of apiserver and kubelet**

*  the apiserver version is v1.11.3
*  the kubelet version is v1.11.3

**static pod file of kube-apiserver is below**

	apiVersion: v1
	kind: Pod
	metadata:
	  annotations:
	    scheduler.alpha.kubernetes.io/critical-pod: ""
	  creationTimestamp: null
	  labels:
	    component: kube-apiserver
	    tier: control-plane
	  name: kube-apiserver
	  namespace: kube-system
	spec:
	  containers:
	  - command:
	    - kube-apiserver
	    - --authorization-mode=Node,RBAC
	    - --advertise-address=192.168.66.11
	    - --allow-privileged=true
	    - --client-ca-file=/etc/kubernetes/pki/ca.crt
	    - --disable-admission-plugins=PersistentVolumeLabel
	    - --enable-admission-plugins=NodeRestriction
	    - --enable-bootstrap-token-auth=true
	    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
	    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
	    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
	    - --etcd-servers=https://127.0.0.1:2379
	    - --insecure-port=0
	    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
	    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
	    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
	    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
	    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
	    - --requestheader-allowed-names=front-proxy-client
	    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
	    - --requestheader-extra-headers-prefix=X-Remote-Extra-
	    - --requestheader-group-headers=X-Remote-Group
	    - --requestheader-username-headers=X-Remote-User
	    - --secure-port=6443
	    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
	    - --service-cluster-ip-range=10.96.0.0/12
	    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
	    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
	    image: k8s.gcr.io/kube-apiserver-amd64:v1.11.3
	    imagePullPolicy: IfNotPresent
	    livenessProbe:
	      failureThreshold: 8
	      httpGet:
	        host: 192.168.66.11
	        path: /healthz
	        port: 6443
	        scheme: HTTPS
	      initialDelaySeconds: 15
	      timeoutSeconds: 15
	    name: kube-apiserver
	    resources:
	      requests:
	        cpu: 250m
	    volumeMounts:
	    - mountPath: /etc/pki
	      name: etc-pki
	      readOnly: true
	    - mountPath: /etc/kubernetes/pki
	      name: k8s-certs
	      readOnly: true
	    - mountPath: /etc/ssl/certs
	      name: ca-certs
	      readOnly: true
	  hostNetwork: true
	  priorityClassName: system-cluster-critical
	  volumes:
	  - hostPath:
	      path: /etc/ssl/certs
	      type: DirectoryOrCreate
	    name: ca-certs
	  - hostPath:
	      path: /etc/pki
	      type: DirectoryOrCreate
	    name: etc-pki
	  - hostPath:
	      path: /etc/kubernetes/pki
	      type: DirectoryOrCreate
	    name: k8s-certs
	status: {}


**kubelet config is below**

	address: 0.0.0.0
	apiVersion: kubelet.config.k8s.io/v1beta1
	authentication:
	  anonymous:
	    enabled: false
	  webhook:
	    cacheTTL: 2m0s
	    enabled: true
	  x509:
	    clientCAFile: /etc/kubernetes/pki/ca.crt
	authorization:
	  mode: Webhook
	  webhook:
	    cacheAuthorizedTTL: 5m0s
	    cacheUnauthorizedTTL: 30s
	cgroupDriver: cgroupfs
	cgroupsPerQOS: true
	clusterDNS:
	- 10.96.0.10
	clusterDomain: cluster.local
	containerLogMaxFiles: 5
	containerLogMaxSize: 10Mi
	contentType: application/vnd.kubernetes.protobuf
	cpuCFSQuota: true
	cpuManagerPolicy: none
	cpuManagerReconcilePeriod: 10s
	enableControllerAttachDetach: true
	enableDebuggingHandlers: true
	enforceNodeAllocatable:
	- pods
	eventBurst: 10
	eventRecordQPS: 5
	evictionHard:
	  imagefs.available: 15%
	  memory.available: 100Mi
	  nodefs.available: 10%
	  nodefs.inodesFree: 5%
	evictionPressureTransitionPeriod: 5m0s
	failSwapOn: true
	fileCheckFrequency: 20s
	hairpinMode: promiscuous-bridge
	healthzBindAddress: 127.0.0.1
	healthzPort: 10248
	httpCheckFrequency: 20s
	imageGCHighThresholdPercent: 85
	imageGCLowThresholdPercent: 80
	imageMinimumGCAge: 2m0s
	iptablesDropBit: 15
	iptablesMasqueradeBit: 14
	kind: KubeletConfiguration
	kubeAPIBurst: 10
	kubeAPIQPS: 5
	makeIPTablesUtilChains: true
	maxOpenFiles: 1000000
	maxPods: 110
	nodeStatusUpdateFrequency: 10s
	oomScoreAdj: -999
	podPidsLimit: -1
	port: 10250
	registryBurst: 10
	registryPullQPS: 5
	resolvConf: /etc/resolv.conf
	rotateCertificates: true
	runtimeRequestTimeout: 2m0s
	serializeImagePulls: true
	staticPodPath: /etc/kubernetes/manifests
	streamingConnectionIdleTimeout: 4h0m0s
	syncFrequency: 1m0s
	volumeStatsAggPeriod: 1m0s

**kebulet logs is below**

	Oct 19 09:28:56 k8s-master kubelet: E1019 09:28:56.585450   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
	Oct 19 09:28:56 k8s-master kubelet: E1019 09:28:56.586490   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
	Oct 19 09:28:56 k8s-master kubelet: E1019 09:28:56.587311   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
	Oct 19 09:28:57 k8s-master kubelet: E1019 09:28:57.592036   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
	Oct 19 09:28:57 k8s-master kubelet: E1019 09:28:57.592074   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
	Oct 19 09:28:57 k8s-master kubelet: E1019 09:28:57.592129   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
	Oct 19 09:28:58 k8s-master kubelet: E1019 09:28:58.001147   25958 eviction_manager.go:243] eviction manager: failed to get get summary stats: failed to get node info: node "k8s-master" not found
	Oct 19 09:28:58 k8s-master kubelet: E1019 09:28:58.594528   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
	Oct 19 09:28:58 k8s-master kubelet: E1019 09:28:58.594528   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
	Oct 19 09:28:58 k8s-master kubelet: E1019 09:28:58.596523   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
	Oct 19 09:28:59 k8s-master kubelet: E1019 09:28:59.597621   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
	Oct 19 09:28:59 k8s-master kubelet: E1019 09:28:59.597633   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
	Oct 19 09:28:59 k8s-master kubelet: E1019 09:28:59.601261   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
	Oct 19 09:29:00 k8s-master kubelet: E1019 09:29:00.605566   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
	Oct 19 09:29:00 k8s-master kubelet: E1019 09:29:00.605651   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
	Oct 19 09:29:00 k8s-master kubelet: E1019 09:29:00.607346   25958 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
	Oct 19 09:29:01 k8s-master kubelet: W1019 09:29:01.212514   25958 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
	Oct 19 09:29:01 k8s-master kubelet: E1019 09:29:01.212911   25958 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**Comment by DevilMayCrySamsara** [comment]
How was the problem solved?

**Comment by Demon-DK** [comment]
Have the same issue !
Have you had any solution ?

**Comment by wooyanger** [comment]
You need to delete the certificate directory.

**Comment by hjydxy** [comment]
@wooyanger Could you be specific please, which directory, which files, Thanks a lot!

**Comment by jzhoucliqr** [comment]
same issue for me. Thanks a lot for @wooyanger.  I tried to delete /var/lib/kubelet/pki/kubelet-client*, then it start working.

**Comment by yangruiray** [comment]
> same issue for me. Thanks a lot for @wooyanger. I tried to delete /var/lib/kubelet/pki/kubelet-client*, then it start working.

this helps me a lot, thx. I just mv the file out of the folder, then the link generate a new one. It solves unauthorized problem, node back to Ready again

**Comment by dougsland** [comment]
> same issue for me. Thanks a lot for @wooyanger.
> I tried to delete /var/lib/kubelet/pki/kubelet-client*, then it start working.

still valid in the 1.16.x

**Comment by mkt-mohit** [comment]
unable to read client-cert /var/lib/kubelet/pki/kubelet-client-current.pem

after above solution. Kubelet is not starting only

**Comment by avarf** [comment]
> same issue for me. Thanks a lot for @wooyanger. I tried to delete /var/lib/kubelet/pki/kubelet-client*, then it start working.

Now kubelet won't start at all:
```bash
/var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory
```

**Comment by eduardoriveror** [comment]
```
same issue for me. Thanks a lot for @wooyanger. I tried to delete /var/lib/kubelet/pki/kubelet-client*, then it start working.
```

This actually worked. After moving the certs and restarting kubelet, a new *kubelet-client-current.pem* was created and the node became ready
