### ISSUE TITLE
openapi GetOpenAPIDefinitions

### ISSUE THREAD

**Issue by myvker** [kubernetes/kubernetes#69974]
root@user:~/go/src/k8s.io/kubernetes/cmd/hyperkube # go build -v
k8s.io/kubernetes/cmd/kube-apiserver/app
k8s.io/kubernetes/vendor/github.com/godbus/dbus
# k8s.io/kubernetes/cmd/kube-apiserver/app
../kube-apiserver/app/server.go:461:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.1
- Cloud provider or hardware configuration: vm
- OS (e.g. from /etc/os-release):freebsd 11.2
- Kernel (e.g. `uname -a`):freebsd 11.2
- Install tools:go build -v
- Others:

**Comment by liggitt** [comment]
the openapi definitions are generated by the makefile. you can find the instructions to build the project at https://github.com/kubernetes/kubernetes/#to-start-developing-kubernetes

/close

**Comment by myvker** [comment]
this is freebsd platform,i can not gen pkg/generated/openapi code
