### ISSUE TITLE
generatedopenapi.GetOpenAPIDefinitions

### ISSUE THREAD

**Issue by myvker** [kubernetes/kubernetes#69982]
genericConfig.OpenAPIConfig = genericapiserver.DefaultOpenAPIConfig(generatedopenapi.GetOpenAPIDefinitions, openapinamer.NewDefinitionNamer(legacyscheme.Scheme, extensionsapiserver.Scheme, aggregatorscheme.Scheme))

what about this?

**Comment by neolit123** [comment]
/close
please re-open once you provide a better description for the issue.
for questions also try the support channels: https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/
