### ISSUE TITLE
Undelete/lazy delete resources

### ISSUE THREAD

**Issue by calind** [kubernetes/kubernetes#69980]
Is is possible to undelete a resource?

We have an use case, where we scale down a database statefulset, but we want to keep around PVC for some grace period so that if you need to scale it back up old/stable data to be available. We need this because it's very expensive to create a new replica from scratch.

I've tried but seams I cannot just set the meta.deletionTimestamp to nil.

/kind feature

**Comment by liggitt** [comment]
deletion is not reversible. once deletionTimestamp is set, the object will be deleted eventually (the presence of a finalizer can delay that deletion indefinitely, but not "undo" the deletion)

/close

**Comment by zhucan** [comment]
@liggitt Is it possible to add a cli "kubectl  reset" to reset the status of pvc when we accidentally delete pvc ?

**Comment by astraw99** [comment]
> @liggitt Is it possible to add a cli "kubectl reset" to reset the status of pvc when we accidentally delete pvc ?

Yes, sometimes we may delete the PVC accidentally, need tool to reset 'Terminating' to 'Bound'.
