### ISSUE TITLE
 When kubelet started, can't get valid node  ephemeral-storage  in update node status

### ISSUE THREAD

**Issue by changyaowei** [kubernetes/kubernetes#69999]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When kubelet started, kubelet update node status to apiserver through  func syncNodeStatus(). In func  setNodeStatusMachineInfo() which is included by func syncNodeStatus() , we update  node.Capacity, node.Capacity contains ephemeral-storage, but we update ephemeral-storage value in func updateRuntimeUp which is started after syncNodeStatus, So when kubelet started, can't get valid node  ephemeral-storage  in update node status

![image](https://user-images.githubusercontent.com/12136478/47194753-26d1d200-d38b-11e8-9d25-dcf8eb9a7dea.png)
![image](https://user-images.githubusercontent.com/12136478/47195022-7cf34500-d38c-11e8-92b3-d4064cf94b80.png)

![image](https://user-images.githubusercontent.com/12136478/47195011-63ea9400-d38c-11e8-8393-39e3a40ccb32.png)

**What you expected to happen**:
 When kubelet started, get valid node  ephemeral-storage  in update node status

**How to reproduce it (as minimally and precisely as possible)**:
Normal start

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.

**Comment by mlmhl** [comment]
This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

**Comment by changyaowei** [comment]
> This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

Kubelet get node status from apiserver and use it in  predicateAdmitHandler, once ephemeral-storage is zero , we will evict all pods.

![image](https://user-images.githubusercontent.com/12136478/47277048-9b587b00-d5ee-11e8-875a-279aa547c515.png)

**Comment by changyaowei** [comment]
> This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

Kubelet get node status from apiserver and use it in  predicateAdmitHandler, once ephemeral-storage is zero , we will evict all pods.

![image](https://user-images.githubusercontent.com/12136478/47277048-9b587b00-d5ee-11e8-875a-279aa547c515.png)

**Comment by changyaowei** [comment]
> This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

Kubelet get node status from apiserver and use it in  predicateAdmitHandler, once ephemeral-storage is zero , kubelet will evict all pods，so ephemeral-storage  can't be zero at any time

![image](https://user-images.githubusercontent.com/12136478/47277110-67318a00-d5ef-11e8-90d9-f91d641b1562.png)

**Comment by changyaowei** [comment]
> This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

Kubelet get node status from apiserver and use it in  predicateAdmitHandler, once ephemeral-storage is zero , kubelet will evict all pods, so ephemeral-storage can't be zero at any time

**Comment by changyaowei** [comment]
> This does not seem like a big problem as all these methods(`syncNodeStatus` and `updateRuntimeUp`) are invoked periodically. Actually, we can't be sure that `updateRuntimeUp` is exactly started after `syncNodeStatus` as they are both running in an independent goroutine.

Kubelet get node status from apiserver and use it in  predicateAdmitHandler, once ephemeral-storage is zero , kubelet will evict all pods, so ephemeral-storage can't be zero at any time

**Comment by sudomakeinstall2** [comment]
We have encountered this issue and I can confirm that whenever we restart the kubelet all the pods in the respective node gets evicted due to ephemeral storage.

Is there a temporary way to disable evicting pods with respect to ephemeral storage until this issue gets fixed? Since kubelet thinks capacity of the node is 0, setting `--eviction-hard` flag doesn't help because it demands a positive number.

**Comment by changyaowei** [comment]
> We have encountered this issue and I can confirm that whenever we restart the kubelet all the pods in the respective node gets evicted due to ephemeral storage.
> 
> Is there a temporary way to disable evicting pods with respect to ephemeral storage until this issue gets fixed? Since kubelet thinks capacity of the node is 0, setting `--eviction-hard` flag doesn't help because it demands a positive number.

We have fixed it in our scenario, i will push it later.

**Comment by dashpole** [comment]
cc @jingxu97 for an ephemeral-storage related issue
This looks similar to something we have seen before, but I can't find the bug.
