### ISSUE TITLE
Kubelet failing to start with error `client version 1.38 is too new` with Docker EE-basic 18.03

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#69996]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

After upgrading to Docker EE-basic 18.03, the kubelet won't start :

```
Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
...
Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I1018 04:06:42.719101    2912 server.go:408] Version: v1.12.1
E1018 04:06:44.012550    2912 server.go:731] Kubelet needs to run as uid `0`. It is being run as -1
W1018 04:06:44.012550    2912 server.go:741] setting OOM scores is unsupported in this build
I1018 04:06:44.013511    2912 kubelet.go:304] Watching apiserver
W1018 04:06:44.021533    2912 iptables.go:155] Error checking iptables version, assuming version at least 1.4.11: executable file not found in %PATH%
I1018 04:06:44.025520    2912 client.go:104] Start docker client with request timeout=2m0s
E1018 04:06:44.026503    2912 kube_docker_client.go:91] failed to retrieve docker version: Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.37
W1018 04:06:44.027498    2912 kube_docker_client.go:92] Using empty version for docker client, this may sometimes cause compatibility issue.
F1018 04:06:44.027498    2912 server.go:262] failed to run Kubelet: failed to create kubelet: failed to get docker version: Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.37
```

**What you expected to happen**:

No crashes, and kubelet should restart normally.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Docker EE-basic 17.06
2. Start kubelet
3. `Install-Package -Name Docker -ProviderName DockerMsftProvider -Update -Force -RequiredVersion 18.03`
4. `Restart-Service kubelet -Force`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Windows Server version 1803
- Install tools: acs-engine

```
>docker version
Client:
 Version:           18.03.1-ee-3
 API version:       1.37
 Go version:        go1.10.2
 Git commit:        b9a5c95
 Built:             Thu Aug 30 18:42:35 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ee-3
  API version:      1.37 (minimum version 1.24)
  Go version:       go1.10.2
  Git commit:       b9a5c95
  Built:            Thu Aug 30 18:56:49 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```

/sig windows

**Comment by PatrickLang** [comment]
Here's the tests that failed for reference. I cancelled the test pass.

[cancelled pass of windows conformance on docker 1803.txt](https://github.com/kubernetes/kubernetes/files/2493894/cancelled.pass.of.windows.conformance.on.docker.1803.txt)

**Comment by PatrickLang** [comment]
I reverted back to Docker EE-basic 17.06.02-ee-16 and now it starts up

```
I1019 19:01:01.794294  552220 kuberuntime_manager.go:197] Container runtime docker initialized, version: 17.06.2-ee-16,apiVersion: 1.30.0
```

**Comment by PatrickLang** [comment]
@ddebroy can you help direct this? We need 18.03 working to fix the file mount parsing issues.

**Comment by PatrickLang** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/64283 bumped the default client version to 1.38

**Comment by feiskyer** [comment]
It's weird that docker doesn't report such error for 17.06 (whose API version is even older). I think the issue is because of version validation inside docker EE: older docker versions only validate minimum version, but 18.03 also validates maximum version.

**Comment by PatrickLang** [comment]
@madhanrm @daschott @dineshgovindasamy  - what do you think about setting the requested Docker API to v1.30 (used in Docker EE-basic 17.06)? Do any of the networking changes require a higher Docker API version?

**Comment by ddebroy** [comment]
As discussed on Slack, best way forward would be to move to Docker 18.09 beta: https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0-beta3.zip . 18.09 version of Docker EE will be out shortly in November and aligns well with the Kube 1.13 release in December.

**Comment by PatrickLang** [comment]
Docker EE 18.09.0 is out for Windows. https://docs.docker.com/engine/release-notes/

Once I get a test done, I'll probably close this out

**Comment by PatrickLang** [comment]
This is working fine with Docker EE 18.09.0
For older versions set DOCKER_API_VERSION
