### ISSUE TITLE
Pod/Container can steal cpu/memory resources if cluster admin did not set "minimum" (not maximum) limitrange

### ISSUE THREAD

**Issue by nak3** [kubernetes/kubernetes#70017]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Even though we set follwing limitrange, users can use cpu/memory larther than 1 cpu or 1Gi memory by setting `0` for the pod limits.

~~~
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1"
        memory: "1Gi"
    - type: "Container"
      max:
        cpu: "1"
        memory: "1Gi"
~~~

**What you expected to happen**:

- kubernetes should not allow users to create pods with cpu/memory of `0` limit.

**How to reproduce it (as minimally and precisely as possible)**:

#### 1. Set LimitRange as following (We expect that pods/container has the max limit.)

~~~
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1"
        memory: "1Gi"
    - type: "Container"
      max:
        cpu: "1"
        memory: "1Gi"
~~~

#### 2. Create Pod with `0` limits

~~~
$ kubectl create -f pod.yaml
~~~

pod.yaml
~~~
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "0"
        memory: "0"
~~~

#### 3. Consume CPU (it will exceed limitrange as `0` means unlimited.)

~~~
$ kubectl exec -it nginx
# yes
~~~

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

~~~
$ ~/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.1.147+12f726c33a0e75", GitCommit:"12f726c33a0e759c8795892e9d27ecbf8e3c5f4d", GitTreeState:"clean", BuildDate:"2018-10-19T08:43:11Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.1.147+12f726c33a0e75-dirty", GitCommit:"12f726c33a0e759c8795892e9d27ecbf8e3c5f4d", GitTreeState:"dirty", BuildDate:"2018-10-19T10:48:33Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
~~~

- Cloud provider or hardware configuration:

bare metal 

- OS (e.g. from /etc/os-release):

~~~
$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
~~~

- Kernel (e.g. `uname -a`):

~~~
$ uname -a
Linux p50 4.16.14-300.fc28.x86_64 #1 SMP Tue Jun 5 16:23:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by munnerz** [comment]
I think this is by design - you should use a ResourceQuota in combination with your LimitRange in order to enforce requests/limits are set: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/#create-a-resourcequota

**Comment by yliaog** [comment]
i think @munnerz is right

**Comment by nak3** [comment]
No, ResourceQuota forces users to set limit, but setting `limits.{memory,cpu} 0` is kind of loophole for it. Any ResourceQuota does not effect `limits.{memory,cpu} 0`.

Only default or minimum of _limitrange_ settings can forbid users from setting `limits.{memory,cpu} 0` for now.

**Comment by derekwaynecarr** [comment]
re: resource quota, you can create a quota that restricts the number of allowed best effort pods in the namespace using quota scopes.

https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-scopes

so you would create a quota that matches BestEffort scope and set count/pods to 0.

independent of the quota capability, i want to look at the limit range change closer.
