### ISSUE TITLE
No easy way how to update CSI driver that uses fuse

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#70013]
We recommend to use DaemonSet to run CSI drivers on node. If a driver runs fuse daemon, it's almost impossible to update it, as killing a pod with the driver kills the fuse daemons too and it will kill all mounts, possibly corrupting application data.

We need a documented and supported way how to update such CSI drivers. Note that the update process can be manual or the code can live somewhere else, we just need it to to be documented and supported so people don't loose data.

/sig storage
@msau42 @davidz627 @saad-ali @pohly @vladimirvivien @verult @lpabon @jingxu97 @gnufied

**Comment by lpabon** [comment]
@jsafrane I think that is the responsibility of the driver, in my opinion. Although we could definitely provide guidelines, we shouldn't provide a solution, since we cannot control their release or update processes.

**Comment by fredkan** [comment]
Expect there is a common solution for this issue.

One workaround: https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md

**Comment by jim3ma** [comment]
Available solution from Alibaba Cloud OSS plugin:
https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md

Another solution: Buddy daemonset pods(two daemonset pod work as buddy)
when need upgrade, the buddy pod will take all fd from original pod and then serve fuse service.

**Comment by andyzhangx** [comment]
I hit similar issue, make fuse driver standalone is one solution; 
another problem is that how to recover when those mounting paths are already broken when fuse csi driver is restarted:
so when fuse driver is broken(sometimes driver pod restarted), the stage volume path is broken, following code will return error directly:
https://github.com/kubernetes/kubernetes/blob/e4a5012de6b49ca7c3b10c4647205fdca66014ee/pkg/volume/csi/csi_attacher.go#L231-L234

is it possible only return error when it's not `IsCorruptedMnt`, like what flexvolume did:
https://github.com/kubernetes/kubernetes/blob/e4a5012de6b49ca7c3b10c4647205fdca66014ee/pkg/volume/flexvolume/detacher.go#L60-L61

So in that case, so even fuse driver is broken, we could make sure if fuse csi driver has remount logic, it could recover after fuse driver is back.
WDYT? I could make code change if that's an acceptable workaround.

**Comment by andyzhangx** [comment]
I worked out a PR(https://github.com/kubernetes/kubernetes/pull/88569) to mitigate this issue when fuse driver on the node is restarted(mount point is corrupted), could someone take a look? Thanks.

**Comment by andyzhangx** [comment]
/open
keep the issue open since PR(#88569) is only a mitigation

**Comment by jim3ma** [comment]
> Available solution from Alibaba Cloud OSS plugin:
> https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md
> This solution is making fuse processes running in node's root namespaces and cgroup, so when daemonset pod upgrade, fuse processes will not be killed.
> 
> Another solution: Buddy daemonset pods(two daemonset pods work as buddy)
> When need upgrade, the buddy pod will take all fd(s) from original pod and then serve csi service.
> This solution needs some code changes for fuse drivers.

We implement a solution  - transferring fd in csi pod with surging rolling update.

**Comment by andyzhangx** [comment]
> > Available solution from Alibaba Cloud OSS plugin:
> > https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md
> > This solution is making fuse processes running in node's root namespaces and cgroup, so when daemonset pod upgrade, fuse processes will not be killed.
> > Another solution: Buddy daemonset pods(two daemonset pods work as buddy)
> > When need upgrade, the buddy pod will take all fd(s) from original pod and then serve csi service.
> > This solution needs some code changes for fuse drivers.
> 
> We implement a solution - transferring fd in csi pod with surging rolling update.

@jim3ma do you have the details of the solution? thanks.

**Comment by jim3ma** [comment]
> > > Available solution from Alibaba Cloud OSS plugin:
> > > https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md
> > > This solution is making fuse processes running in node's root namespaces and cgroup, so when daemonset pod upgrade, fuse processes will not be killed.
> > > Another solution: Buddy daemonset pods(two daemonset pods work as buddy)
> > > When need upgrade, the buddy pod will take all fd(s) from original pod and then serve csi service.
> > > This solution needs some code changes for fuse drivers.
> > 
> > 
> > We implement a solution - transferring fd in csi pod with surging rolling update.
> 
> @jim3ma do you have the details of the solution? thanks.

Currently, this solution is using in Ant Group, we will open source in [Dragonfly Image Service](https://github.com/dragonflyoss/image-service) some times later.

Another solution: csi container starts a fuse session in another container in host not in pod, then we can update csi pod with keeping a fuse session containers.

**Comment by xhejtman** [comment]
> > > > Available solution from Alibaba Cloud OSS plugin:
> > > > https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md
> > > > This solution is making fuse processes running in node's root namespaces and cgroup, so when daemonset pod upgrade, fuse processes will not be killed.
> > > > Another solution: Buddy daemonset pods(two daemonset pods work as buddy)
> > > > When need upgrade, the buddy pod will take all fd(s) from original pod and then serve csi service.
> > > > This solution needs some code changes for fuse drivers.
> > > 
> > > 
> > > We implement a solution - transferring fd in csi pod with surging rolling update.
> > 
> > 
> > @jim3ma do you have the details of the solution? thanks.
> 
> Currently, this solution is using in Ant Group, we will open source in [Dragonfly Image Service](https://github.com/dragonflyoss/image-service) some times later.
> 
> Another solution: csi container starts a fuse session in another container in host not in pod, then we can update csi pod with keeping a fuse session containers. this likes the solution from Alibaba Cloud OSS plugin but within our control.

did you open source already?

**Comment by andyzhangx** [comment]
@xhejtman Azure Blob CSI driver uses similar fuse proxy solution, and it's open source, check details here: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy

**Comment by xhejtman** [comment]
Thank. I was also interested in truly restartable fuse driver, at least I understand what @jim3ma talk about - track everything fuse needs for restart.

**Comment by ofek** [comment]
@jim3ma Is it open source now?
