### ISSUE TITLE
Suggest to make kubelet retry UnexpectedAdmissionError with an exponential delay

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#70010]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
/kind question

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Kuberentes: v1.11.2

When I'm testing  nvidia-device-plugin, and trigger it return error:  invalid allocation request: unknown device

https://github.com/NVIDIA/k8s-device-plugin/blob/v1.11/server.go#L165

It retries continuously because it's `UnexpectedAdmissionError`.

```
kubectl get po | grep UnexpectedAdmissionError | wc -l
1181
```

I suggest to make it retry with an with an exponential delay(10s, 20s, 40s ...).

**Comment by redbaron** [comment]
/remove-lifecycle rotten

-------- Original Message --------

**Comment by paol** [comment]
I'd like to second this bug report. Currently we are developing a device plugin, and the behavior surrounding UnexpectedAdmissionError is very undesirable.

We have worked around it by never returning errors from DevicePluginServer.Allocate(). Instead we return a "poison" value in ContainerAllocateResponse.Envs that causes the container creation to fail, which K8S handles in a much more amenable way. This is an ugly hack though.

**Comment by mozhata** [comment]
some bugs report with version v1.14.3

**Comment by Prasanna-sr** [comment]
same bugs report with version v1.11.7

**Comment by pryan-branch** [comment]
also on 1.15.7

**Comment by soulseen** [comment]
same bugs report with version v1.16.8

**Comment by salanki** [comment]
Having issues in 1.18.6 with this as well.
