### ISSUE TITLE
Can hostport be dynamically assigned?

### ISSUE THREAD

**Issue by smartdu** [kubernetes/kubernetes#70043]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
I want k8s to dynamically allocate a hostport and tell the container through the environment variable.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by neolit123** [comment]
hi, for questions you might get a better response in stackoverflow or slack:
https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

/close
