### ISSUE TITLE
Failing Kubeadm Test: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/524

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70058]
Testgrid; https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-master

Sample Failure: 

The problem seems to be that Kube-anywhere isn't working since commit  aae438e82

```
I1019 21:39:06.234] Oct 19 21:39:06.234: INFO: Failed to setup provide r config: The provider kubernetes-anywhere is unknown.
```

/sig cluster-lifecycle
/kind failing-test
/priority important-soon

cc: @timothysc 
@kubernetes/sig-cluster-lifecycle

**Comment by neolit123** [comment]
sent possible fix PR:
https://github.com/kubernetes/kubernetes/pull/70059

**Comment by neolit123** [comment]
sent new PR https://github.com/kubernetes/test-infra/pull/9884
might get merged once github is back on track.

**Comment by jberkus** [comment]
Reopening, because the test isn't passing *yet*.

/reopen

**Comment by neolit123** [comment]
true, i was almost sure that the solution in that last PR won't be sufficient...

**Comment by AishSundar** [comment]
@neolit123 I see https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-stable-on-master job failing as well. Will the 2 open PRs address this failure as well?

**Comment by neolit123** [comment]
@AishSundar all the kubeadm-gce-x tests are broken at the moment due to the e2e refactor.
we will hopefully decide on how to approach the issue today.

**Comment by neolit123** [comment]
latest efforts:
https://github.com/kubernetes/test-infra/pull/9915

**Comment by neolit123** [comment]
the tests are working on the cluster up/down side, except that they fail when dumping the node logs. looking into it.

**Comment by mariantalla** [comment]
Looks good, thanks! One flake in the last run - let's keep an eye on it but it should be fine.

/cc @jberkus @AishSundar @mortent 

/close
