### ISSUE TITLE
kubectl port-forward fails with incompatible key usage

### ISSUE THREAD

**Issue by vishal49naik49** [kubernetes/kubernetes#70063]
kubectl port-forward fails with below error:

error: error upgrading connection: error dialing backend: x509: certificate specifies an incompatible key usage

The kubelet client cert supplied to api service has below auth:

            X509v3 Extended Key Usage:
                TLS Web Client Authentication

User cert has below auth:

            X509v3 Extended Key Usage:
                TLS Web Client Authentication

Please advise!

**Comment by neolit123** [comment]
you might not get a response here, because this is the bug and feature tracker.

please try the support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

thanks
/close
