### ISSUE TITLE
unable to sync kubernetes service: Endpoints "kubernetes" is invalid

### ISSUE THREAD

**Issue by Suozz** [kubernetes/kubernetes#70065]
I deployment k8s on local VMs, but when I start apiserver, the log show this item
 ` unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "169.254.6.1": may not be in the link-local range (169.254.0.0/16)`

**Comment by neolit123** [comment]
169.254.6.1 is in the link-local range and it's not allowed as en endpoint.
```
	// We disallow some IPs as endpoints or external-ips.  Specifically,
	// unspecified and loopback addresses are nonsensical and link-local
	// addresses tend to be used for node-centric purposes (e.g. metadata
	// service).
```
https://en.wikipedia.org/wiki/Link-local_address

for further questions please try the support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close
