### ISSUE TITLE
Is it possible to pass the route of a pod in a yaml file?

### ISSUE THREAD

**Issue by chortels** [kubernetes/kubernetes#70078]
Hi, 

Is it possible to insert the route of a pod in a yaml file, so another service knows and could make use of it? I've been looking for examples where this is done but I haven't been able to find them.

Regards.

**Comment by ticpu** [comment]
What kind of route?  If it is an IP route, it feels like that should go into your router or network plugin.

**Comment by neolit123** [comment]
hi, please try our support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close
