### ISSUE TITLE
SharedInformer: When a Watch breaks, it should automatically resume

### ISSUE THREAD

**Issue by simonferquel** [kubernetes/kubernetes#70089]
/kind bug
**What happened**:
Whenever a listener receives an error from its unerlying Watch interface, it stops receiving events, even if the root cause is an intermitent network issue

**What you expected to happen**:
When a watcher reports an error and stops, just recreate one (reusing the latest received resourceRevision). This is doable as to build a shared informer, you don't give an existing Watch interface, but a ListerWatcher interface that can be used to recreate the Watcher.

**How to reproduce it (as minimally and precisely as possible)**:
Azure AKS has currently an annoying networking bug useful to reproduce the issue: idle TCP connections through their implementation of Kube-Proxy are dropped after ~10 minutes. So just setup any informer from a POD running in AKS, and you'll experience the problem

**Anything else we need to know?**:
Our current workaround is to wrap the ListerWatchers we use inside one that implements a kind of "ResilientWatch" (which implements watch.Interface, and automatically re-issue a Watch request on error)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2 (client and server, and client-go)
- Cloud provider or hardware configuration: Any
- OS (e.g. from /etc/os-release): Any Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
> Whenever a listener receives an error from its unerlying Watch interface, it stops receiving events, even if the root cause is an intermitent network issue

it is designed. but once the listerwatcher exits (with an error or rv confliction or whatever..), the reflector will try another list-watch within 1 sec. and we only recreate a watch on `connection refused` return code.

[https://github.com/kubernetes/kubernetes/blob/dbdcb7e053e13b59538a5317b3ccddbfe06ba5e3/staging/src/k8s.io/client-go/tools/cache/reflector.go#L132-L136](https://github.com/kubernetes/kubernetes/blob/dbdcb7e053e13b59538a5317b3ccddbfe06ba5e3/staging/src/k8s.io/client-go/tools/cache/reflector.go#L132-L136)

**Comment by simonferquel** [comment]
After careful analysis of logs against known workloads, it seems we are seing this particular AKS bug: https://github.com/kubernetes/kubernetes/issues/66153

The "funny" part is that their proxy bug seems very tricky: it seems to break the connection from the proxy to the API server, but not from the client to the proxy. So when the timeout happens, from the client side, you have a time window of a few minutes where the watch appears to be perfectly working, with no event to decode. At some point, the client seems to detect that or hit a timeout (you get the `streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 141; INTERNAL_ERROR` trace in logs), and the reflector resumes correctly.
It seems to correlate your comment about default watch timeout.

**Comment by yue9944882** [comment]
> it seems to break the connection from the proxy to the API server, but not from the client to the proxy. 

that shouldn't happen. the disconnection between server/proxy should propagate to client/proxy. what proxy are you using exactly?

**Comment by liggitt** [comment]
I don't see an issue here for the informer to resolve. on connection close, it re-establishes as expected.

/close
