### ISSUE TITLE
Ubuntu kubeadm package has broken dependency on kubernetes-cni (>= 0.6.0), can't be installed

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#70088]
/kind bug

```
 kubeadm : Depends: kubernetes-cni (>= 0.6.0) but 0.5.1-00 is to be installed
```

It seems to be related with: https://github.com/kubernetes/kubernetes/issues/69489

**Comment by AishSundar** [comment]
it seems the deb repo is broken for kubernetes 1.8. Kubernetes `1.8.14` depends on `cni-0.5.1` but `1.8.15` looks like it depends on cni-0.6.0. As per @neolit123 this is a known problem and the solution is to pin the CNI deb version.

@calebamiles is 1.8 too old for a backport fix?

**Comment by neolit123** [comment]
pinning the version of kubernetes-cni during install can fix this.
@aanm does that work for you?
https://github.com/kubernetes/kubernetes/issues/69489#issuecomment-427585842

questioning if we should address a patch release due to this bug - i.e. definitely messy, but not a security  issue.

**Comment by neolit123** [comment]
@aanm 
yes, the experiment is to try pinning the required version.
