### ISSUE TITLE
how to label the custom labels to container of kubernetes pods

### ISSUE THREAD

**Issue by mojo-zd** [kubernetes/kubernetes#70108]
> /kind feature

**kubernete version**
`
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
`

**What happened**:
kubernets pod will generate two containers, but not all containers with the custom labels of pod. 
example pod: artifactory-5988dc74dd-rxnjh

setp 1: check the pod labels
`
artifactory-5988dc74dd-rxnjh   1/1       Running   1          17h       com.wise2c.service=artifactory,com.wise2c.stack=wisecloud-controller,pod-template-hash=1544873088
`
the labels of `com.wise2c.service、com.wise2c.stack` is custom label

setp 2: check the containers of pod artifactory-5988dc74dd-rxnjh
container 1:
`
79eb0d1cb401        registry.cn-hangzhou.aliyuncs.com/wise2c-test/artifactory-oss@sha256:c4248a56321d2112513f07d575976ca8f36503acfc6f5a6bc85b750c9bff2d11       "/bin/sh -c /start..."   17 hours ago        Up 17 hours                                                                                                                                              k8s_artifactory_artifactory-5988dc74dd-rxnjh_wisecloud-controller_1a658416-d5d0-11e8-82d5-00163e0f7d95_1
`

container 2:
`
06e8791fe75d        192.168.1.189/library/pause-amd64:3.0                                                                                                       "/pause"                 17 hours ago        Up 17 hours                                                                                                                                              k8s_POD_artifactory-5988dc74dd-rxnjh_wisecloud-controller_1a658416-d5d0-11e8-82d5-00163e0f7d95_2
`

setp 3: check the lables of container
container1's label is:
`
"Labels": {
                "annotation.io.kubernetes.container.hash": "c9409f6",
                "annotation.io.kubernetes.container.ports": "[{\"hostPort\":8081,\"containerPort\":8081,\"protocol\":\"TCP\"}]",
                "annotation.io.kubernetes.container.restartCount": "1",
                "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
                "annotation.io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.container.logpath": "/var/log/pods/1a658416-d5d0-11e8-82d5-00163e0f7d95/artifactory_1.log",
                "io.kubernetes.container.name": "artifactory",
                "io.kubernetes.docker.type": "container",
                "io.kubernetes.pod.name": "artifactory-5988dc74dd-rxnjh",
                "io.kubernetes.pod.namespace": "wisecloud-controller",
                "io.kubernetes.pod.uid": "1a658416-d5d0-11e8-82d5-00163e0f7d95",
                "io.kubernetes.sandbox.id": "06e8791fe75d6b1ccf313b1a9954d9012e19f34ef875ab0b69a73191ba9fb21e"
            }
`

container2's label:
`
"Labels": {
                "annotation.kubernetes.io/config.seen": "2018-10-22T15:57:20.791042355+08:00",
                "annotation.kubernetes.io/config.source": "api",
                "annotation.kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"wisecloud-controller\",\"name\":\"artifactory-5988dc74dd\",\"uid\":\"17026245-bd66-11e8-a505-00163e0f7d95\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"19353801\"}}\n",
                "com.wise2c.service": "artifactory",
                "com.wise2c.stack": "wisecloud-controller",
                "io.kubernetes.container.name": "POD",
                "io.kubernetes.docker.type": "podsandbox",
                "io.kubernetes.pod.name": "artifactory-5988dc74dd-rxnjh",
                "io.kubernetes.pod.namespace": "wisecloud-controller",
                "io.kubernetes.pod.uid": "1a658416-d5d0-11e8-82d5-00163e0f7d95",
                "pod-template-hash": "1544873088"
            }
`
from the example, only pause container with the label of `com.wise2c.service、com.wise2c.stack`。
**What you expected to happen**:
i wish all of the containers with the labels `com.wise2c.service、com.wise2c.stack`

**@milestone/incomplete-labels**
`/sig scalability`

**Comment by neolit123** [comment]
hi, please try our support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

/close
