### ISSUE TITLE
k8s.gcr.io/fluentd-elasticsearch:v2.2.1 does not exist.

### ISSUE THREAD

**Issue by xnike** [kubernetes/kubernetes#70118]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig scheduling
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
Latest is 2.3.1
- https://console.cloud.google.com/gcr/images/google_containers/GLOBAL/fluentd-elasticsearch?gcrImageListsize=50
- https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Makefile#L19

Thanks,
Dims

/close
