### ISSUE TITLE
kube-proxy IPVS spurious logs removing IPv6 address

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kubernetes#70113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network
/area ipvs
/area ipv6

**What happened**:

`kube-proxy` with IPVS mode creates a `kube-ipvs0` interface for binding service IPs.

```
ip addr show kube-ipvs0
5: kube-ipvs0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 1a:ab:99:c0:a2:0d brd ff:ff:ff:ff:ff:ff
    inet 10.3.0.10/32 brd 10.3.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.3.0.1/32 brd 10.3.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet6 fe80::18ab:99ff:fec0:a20d/64 scope link 
       valid_lft forever preferred_lft forever
```

kube-proxy periodically [tries to unbind](https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/proxy/ipvs/proxier.go#L1583) addresses it doesn't know about from the interface. It tries to unbind the IPv6 address over and over.

```
Failed to unbind service addr fe80::18ab:99ff:fec0:a20d from dummy interface kube-ipvs0: error unbind address: fe80::18ab:99ff:fec0:a20d from interface: kube-ipvs0, err: cannot assign requested address
```

The error is a little vague, but see below. The IP parsing or address deletion code [here](https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/proxy/ipvs/netlink_linux.go#L61) may be a suspect.

**What you expected to happen**:

Either ignore the IPv6 address on the interface (its not hurting anything) or remove it correctly. 

**How to reproduce it (as minimally and precisely as possible)**:

Its perfectly natural for a new interface to have an inet6 address by default.

```
sudo ip link add name eth99 type dummy
```

If for some reason your `kube-ipvs0` interface doesn't have a similar address, you can add one to repro.

```
sudo ip addr add fe80::4482:f7ff:fe36:3e6d/64 dev kube-ipvs0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.1
- Cloud provider or hardware configuration: AWS, GCP, DigitalOcean, bare-metal, Azure
- OS (e.g. from /etc/os-release): Container Linux 1855.4.0
- Kernel (e.g. `uname -a`): 4.14.67-coreos
- Install tools: Typhoon

**Comment by dghubble** [comment]
The error message from `ip` is a little vague. Hop on a node to help out `kube-proxy` with its deletion. 

```
$ sudo ip addr del fe80::18ab:99ff:fec0:a20d dev kube-ipvs0
RTNETLINK answers: Cannot assign requested address
$ sudo ip addr del fe80::18ab:99ff:fec0:a20d/64 dev kube-ipvs0
// success!
```

This gives a clue about where `kube-proxy` goes wrong. With IPv4 addresses, leaving off the `/N` is permitted (though with a scary warning).

```
sudo ip addr del 10.3.0.10 dev kube-ipvs0
Warning: Executing wildcard deletion to stay compatible with old scripts.
         Explicitly specify the prefix length (10.3.0.10/32) to avoid this warning.
         This special behaviour is likely to disappear in further releases,
         fix your scripts!
```

With more verbose logging, we see the mask was stripped before calling  [netlink](github.com/vishvananda/netlink)'s [AddrDel](https://godoc.org/github.com/vishvananda/netlink#AddrDel
), so the bug lies in kube-proxy's construction of `currentBindAddres`.

```
Unbind addr fe80::18ab:99ff:fec0:a20d
Failed to unbind service addr fe80::18ab:99ff:fec0:a20d from dummy interface kube-ipvs0: error unbind address: fe80::18ab:99ff:fec0:a20d from interface: kube-ipvs0, err: cannot assign requested address
```

The mask is dropped [here](https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/proxy/ipvs/netlink_linux.go#L120). `addr.IP.String()` should be `addr.IPNet.String()`. However, it looks like much of kube-proxy ipvs deals in string IPs (e.g. 1.2.3.4, 1002:ab8::2:1) so propagating a `[]netlink.Addr` could be a large change.
   * https://godoc.org/github.com/vishvananda/netlink#Addr
   * https://godoc.org/net#IPNet

One might also point to [NewIPNet](https://godoc.org/github.com/vishvananda/netlink#NewIPNet) called [here](https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/proxy/ipvs/netlink_linux.go#L70) as the source - it assumes a `/32` mask for IPv4 and a `/128` mask for IPv6. Neither is neccessarily right for addresses that might end up on a `kube-ipvs0` interface, but `/32` happens to work for Kubernetes IPv4 service IPs. The trouble is, by the time we reach [UnbindAddress](https://github.com/kubernetes/kubernetes/blob/v1.12.1/pkg/proxy/ipvs/netlink_linux.go#L61), kube-proxy has already thrown away the mask information.

**Comment by uablrek** [comment]
Any relation with this you think? #65006 
Doesn't seem so since this is in `kube-ipvs0` and the other is ipvs targets...

**Comment by dghubble** [comment]
Hm, I think adapting the sync'er for IPv6 might be a different fix. I was working on a fix for the IPv6 cleanup on the `kube-ipvs` interface, lemme see if I can get that to a state it can be posted.

**Comment by uablrek** [comment]
I can only reproduce this fault if I do;
```
ip link set up dev kube-ipvs0
```
This will automatically assign a link-local generated address to the interface and the problem occurs. But the `kube-ipvs0` should **not** be up. By default if I start v1.12.0 it is down.

Is some program, e.g network-manager, brings the interface up?

Anyway I think it is possible to suspress auto-generated link-local ipv6 addresses. I will try to find the setting.

**Comment by uablrek** [comment]
After creation;
```
ip link set dev kube-ipvs0 addrgenmode none
```
should fix this problem. I will try to get time to do a PR.
