### ISSUE TITLE
Decide what to do with conformance tests that need privileged mode

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#70137]
Based on findings in:
- https://github.com/kubernetes/kubernetes/issues/59978
- https://github.com/kubernetes/kubernetes/pull/69935#issuecomment-432340200

We have SIG-Storage tests that have been coded to use `privileged` mode when they do not really need the `privileged` mode. These tests only fail under SELinux *if* `privileged` mode is set to false. So what can we do now?

- Option 1 : Nudge SIG-Storage to see if there is a way to get the feature working under SELinux without needing `privileged` mode
- Option 2 : Change the tests to detect if SELinux is on and set `privileged` mode is set to true if so
- Option 3 : Mark these tests with `[privileged]` and say that it is ok to skip these tests when vendors are testing conformance where/when they lock down kubelet to disallow privileged mode
- Option 4 : Drop these tests from conformance

/area conformance
/sig storage
/sig architecture

cc @kubernetes/cncf-conformance-wg

**Comment by mgdevstack** [comment]
@dims No existing Conformance tests from the suite are running in Privileged mode. Though there are few e2e tests which verify privileged behavior viz -
> should support r/w [NodeConformance]
> PrivilegedPod [NodeConformance] should enable privileged commands
>etc....

Can we close this issue?

**Comment by spiffxp** [comment]
I'm willing to take your word for it, but still feel compelled to do a sanity check (which is going to take me some time)

I'm wondering if there's a way we could lint this somehow

**Comment by mgdevstack** [comment]
For a documented purpose maintaining list of existing e2e dealing with `Privileged: true`. (Please keep adding test in comment incase any e2e is missed to mention here)

1. [sig-auth] PodSecurityPolicy should allow pods under the privileged policy.PodSecurityPolicy
2. [k8s.io] [sig-node] AppArmor load AppArmor profiles should enforce an AppArmor profile
3. [k8s.io] [sig-node] AppArmor load AppArmor profiles can disable an AppArmor profile, using unconfined
4. [sig-storage] HostPath should support r/w [NodeConformance]
5. [k8s.io] PrivilegedPod [NodeConformance] should enable privileged commands [LinuxOnly]
6. [k8s.io] [sig-node] kubelet [k8s.io] [sig-node] host cleanup with volume mounts [sig-storage] [HostCleanup][Flaky] Host cleanup after disrupting NFS volume [NFS] after stopping the nfs-server and deleting the (sleeping) client pod, the NFS mount and the pod's UID directory should be removed.
7. [k8s.io] [sig-node] kubelet [k8s.io] [sig-node] host cleanup with volume mounts [sig-storage][HostCleanup][Flaky] Host cleanup after disrupting NFS volume [NFS] after stopping the nfs-server and deleting the (active) client pod, the NFS mount and the pod's UID directory should be removed.
should propagate mounts to the host
8. Security Context When creating a pod with privileged should run the container as privileged when true [NodeFeature:HostAccess]
9. [sig-storage] PersistentVolumes NFS with Single PV - PVC pairs should create a non-pre-bound PV and PVC: test write access
`Uses NewNFSServer() function which is an wrapper for CreateStorageServer ( uses Privileged mode)`
10. [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kube-controller-manager restarts should delete a bound PVC from a clientPod, restart the kube-control-manager, and ensure the kube-controller-manager does not crash
11. [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kubelet restarts Should test that a file written to the mount before kubelet restart is readable after restart.
12. [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kubelet restarts Should test that a volume mounted to a pod that is deleted while the kubelet is down unmounts when the kubelet returns.
13. [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kubelet restarts Should test that a volume mounted to a pod that is force deleted while the kubelet is down unmounts when the kubelet returns.
14. [k8s.io] [sig-node] Mount propagation should propagate mounts to the host
15. --ginkgo.focus="should\sbe\smountable" --ginkgo.dryRun true
`178 E2Es, testing mount behavior of various Volume types(CSI, In-tree, GCP ...) with respect to various drivers(nfs, hostpath, aws ...) ..`

**Comment by dims** [comment]
Hmm, we do need @spiffxp 's input. Looks like Aaron asked for a sanity check and Mayank came up with the list of tests currently that use this flag.

/assign @spiffxp

**Comment by dims** [comment]
If @spiffxp is ok with the list, we can close this out.

**Comment by dims** [comment]
Do we have any volunteers to find a better spot for storing the list in the comments above?

**Comment by brahmaroutu** [comment]
If we can automate this, we should generate sections with list of tests for privileged, Windows only, linux only into the conformance document itself so that we can track for each of the release. WDYT?

**Comment by dims** [comment]
This has not come up in a while, so let's keep it at status quo

/close
