### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#70131]
_From @dims on September 21, 2018 21:4_

Please see https://reproducible-builds.org/ specifically https://reproducible-builds.org/docs/ on ideas about how to do deterministic builds. When we get a chance, we should try to examine how far away we are from this goal and what our blockers are.

Thanks,
Dims

_Copied from original issue: kubernetes/release#637_

**Comment by dims** [comment]
_From @bmwiedemann on September 22, 2018 5:44_

Latest state can be seen in
http://rb.zq1.de/compare.factory/kubernetes-compare.out for openSUSE
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/kubernetes.html

**Comment by dims** [comment]
@bmwiedemann i can't seem to tell if the results are from the latest k8s releases. if not is there a way to trigger these for say the v1.12-rc1 please?

**Comment by dims** [comment]
_From @bmwiedemann on September 22, 2018 20:2_

openSUSE's diff is from 1.11.1 (and we do have SOURCE_DATE_EPOCH set)

Going to 1.12 is not that easy, because my reproducibility-test tools are designed around building of packages and there are usually so many changes and build is so slow (~20 minutes per try) that it can take hours to get right.

However, IMHO it would be a good start to find out if and how the two known issues in 1.11.1 have been addressed. If there are patches, I could apply them to 1.11.1 and see if anything remains there.

I'd prefer to not have to chase the master branch.

**Comment by dims** [comment]
gotcha thanks @bmwiedemann

**Comment by dims** [comment]
@bmwiedemann please see https://github.com/kubernetes/kubernetes/pull/68983 to see if it fixes the man page issue

**Comment by dims** [comment]
On the buildid problem, looks like we may have to wait for next versions of golang:
https://github.com/golang/go/issues/16860

See for example how others are trying to think about the same problem:
- https://github.com/status-im/status-go/issues/1185
- https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/

**Comment by dims** [comment]
We need to update k/release anago scripts to set `SOURCE_DATE_EPOCH` and save the information somewhere (in generated tarballs? release notes?)

**Comment by dims** [comment]
_From @bmwiedemann on September 26, 2018 4:30_

regarding random build-ids:
https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/ seems to imply that it is already possible to generate reproducible go binaries and indeed our openSUSE "docker" package is already reproducible (we always build in the same path)

strace showed me

execve("/usr/lib64/go/1.10/pkg/tool/linux_amd64/compile", ["/usr/lib64/go/1.10/pkg/tool/linux_amd64/compile", "-o", "/tmp/go-build336594203/b073/_pkg_.a", **"-trimpath", "/tmp/go-build336594203/b073",** "-p", "k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets", "-complete", **"-buildid", "SUvgWqVQmIZMGMbPSYtX/SUvgWqVQmIZMGMbPSYtX"**, "-goversion", "go1.10.3", "-D", "", "-importcfg", "/tmp/go-build336594203/b073/importcfg", "-pack", "-c=4", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/byte.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/doc.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/empty.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/int.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/int64.go", "/home/abuild/rpmbuild/BUILD/kubernetes-1.11.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/gengo/examples/set-gen/sets/string.go"],

so my guess is that a part of the build system generates explicit random buildids instead of using something reproducible (e.g. a constant or the shasum of the source(s))
Maybe `go` would even do the right thing (like gcc) when no buildid is given?

**Comment by dims** [comment]
@bmwiedemann i could get reproducible builds with latest master. PR is here. here's what i had to do.
- `make quick-release` builds stuff inside a docker container, so we control a lot of the things including go version, paths etc.

But that was not enough. then i had to add `trimpath`
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-dac3f0d616ae45f98d45d6420ed1be65R671

And then added `-s -w` to remove the symbol table
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-dac3f0d616ae45f98d45d6420ed1be65R670

and finally pass the SOURCE_DATE_EPOCH into the container where the builds happen.
- https://github.com/kubernetes/kubernetes/pull/69003/commits/1f74a33790ce5112e4eac622e10be56819058dff#diff-0ee501c7b4b1ab61678579826c6d6534R603

Finally tested the build process under my laptop (MacOS) and ubuntu and verified the build id of the kubeadm binary.

**Comment by bmwiedemann** [comment]
/remove-lifecycle rotten

We currently have 1.13.3 in openSUSE and I can see new variations of order:
```diff
--- old//usr/share/man/man1/kubeadm-init.1      2019-02-20 01:47:34.848765358 +0000
+++ new//usr/share/man/man1/kubeadm-init.1      2019-02-20 01:47:34.856765406 +0000
@@ -26,10 +26,10 @@
 kubelet\-start              Writes kubelet settings and (re)starts the kubelet
 certs                      Certificate generation
   /etcd\-ca                   Generates the self\-signed CA to provision identities for etcd
+  /etcd\-server               Generates the certificate for serving etcd
   /etcd\-peer                 Generates the credentials for etcd nodes to communicate with each other
   /etcd\-healthcheck\-client   Generates the client certificate for liveness probes to healtcheck etcd
   /apiserver\-etcd\-client     Generates the client apiserver uses to access etcd
-  /etcd\-server               Generates the certificate for serving etcd
   /ca                        Generates the self\-signed Kubernetes CA to provision identities for other Kubernetes components
```

Plus the issue with varying build-ids - is 1.13.3 too old to have fixes from @dims or do we need to change something in our .spec file?

**Comment by bmwiedemann** [comment]
kubernetes-1.14.1 still has these order variations in `/usr/share/man/man1/kubeadm-init.1`

And there are also some binaries with variations
```diff
/usr/src/kubernetes/platforms/linux/amd64/e2e.test differs in ELF section .gopclntab
@@ -3121947,8 +3121947,8 @@
  85ddce0 3b35fa02 c234fa02 4a34fa02 d833fa02  ;5...4..J4...3..
  85ddcf0 6333fa02 f132fa02 b932fa02 7c32fa02  c3...2...2..|2..
  85ddd00 3a32fa02 f731fa02 ba31fa02 9031fa02  :2...1...1...1..
- 85ddd10 2f746d70 2f676f2d 6275696c 64323635  /tmp/go-build265
- 85ddd20 30303637 30342f62 3030312f 5f746573  006704/b001/_tes
+ 85ddd10 2f746d70 2f676f2d 6275696c 64383933  /tmp/go-build893
+ 85ddd20 34353433 34362f62 3030312f 5f746573  454346/b001/_tes
  85ddd30 746d6169 6e2e676f 00005f6f 75747075  tmain.go.._outpu
  85ddd40 742f6c6f 63616c2f 676f2f73 72632f6b  t/local/go/src/k
  85ddd50 38732e69 6f2f6b75 6265726e 65746573  8s.io/kubernetes

/usr/bin/kubeadm differs in ELF section .typelink
@@ -66,7 +66,7 @@
  1b41fd0 00eb0800 40eb0800 80eb0800 c0eb0800  ....@...........
  1b41fe0 00ec0800 80f00800 40ec0800 c0f00800  ........@.......
  1b41ff0 00ee0800 40ee0800 40c10800 80c10800  ....@...@.......
- 1b42000 c0ed0800 80ec0800 c0ec0800 80e50800  ................
+ 1b42000 80ec0800 c0ed0800 c0ec0800 80e50800  ................
  1b42010 00f10800 c0e50800 00ed0800 40ed0800  ............@...
  1b42020 c0e30800 00e40800 80ee0800 40e40800  ............@...
  1b42030 80e40800 c0e40800 40f20800 c0c10800  ........@.......
...
```

**Comment by dims** [comment]
@bmwiedemann see #78544 for the /usr/share/man/man1/kubeadm-init.1 fix. 

I haven't looked into the other two issues e2e.test with /tmp path and the kubeadm's .typelink section.

**Comment by dims** [comment]
For the e2e.test, looks like we need to set [`GOTMPDIR`](https://github.com/golang/go/issues/8451 ) to make sure a specific directory is used instead of the random `/tmp/go-buildXXXXXXXXX`

**Comment by bmwiedemann** [comment]
@dims, on 1.14.1 I applied 78544 and got another diff in man pages:

```diff
--- old//usr/share/man/man1/kubeadm-config-print-join-defaults.1        2019-06-
04 09:12:20.709964411 +0000
+++ new//usr/share/man/man1/kubeadm-config-print-join-defaults.1        2019-06-
04 09:12:20.729964549 +0000
@@ -23,7 +23,7 @@
 .SH OPTIONS
 .PP
 \fB\-\-component\-configs\fP=[]
-    A comma\-separated list for component config API objects to print the default values for. Available values: [KubeProxyConfiguration KubeletConfiguration]. If this flag is not set, no component configs will be printed.
+    A comma\-separated list for component config API objects to print the default values for. Available values: [KubeletConfiguration KubeProxyConfiguration]. If this flag is not set, no component configs will be printed.


 .SH OPTIONS INHERITED FROM PARENT COMMANDS
```

I also exported `GOTMPDIR` to a constant path, but something random (`go-build$NUM`) is appended to it during build.
```diff
/usr/src/kubernetes/hack/../platforms/linux/amd64/e2e.test differs in ELF section .gopclntab
@@ -3121947,8 +3121947,8 @@
  85ddce0 6433fa02 f232fa02 ba32fa02 7d32fa02  d3...2...2..}2..
  85ddcf0 3b32fa02 f831fa02 bb31fa02 8031fa02  ;2...1...1...1..
  85ddd00 2f686f6d 652f6162 75696c64 2f72706d  /home/abuild/rpm
- 85ddd10 6275696c 642f676f 2d627569 6c643337  build/go-build37
- 85ddd20 35373334 3432382f 62303031 2f5f7465  5734428/b001/_te
+ 85ddd10 6275696c 642f676f 2d627569 6c643837  build/go-build87
+ 85ddd20 36383531 3534332f 62303031 2f5f7465  6851543/b001/_te
  85ddd30 73746d61 696e2e67 6f00005f 6f757470  stmain.go.._outp
```

**Comment by dims** [comment]
@bmwiedemann can you please try #78695 for the kubeadm config print problem?

**Comment by dims** [comment]
@bmwiedemann how exactly do you build the e2e.test?

**Comment by dims** [comment]
Looks like we are hitting this https://github.com/golang/go/issues/16860 @bmwiedemann (for the .gopclntab problem)

**Comment by bmwiedemann** [comment]
yes. In openSUSE we usually build everything in constant paths, but it still is troublesome when some random component gets appended, as is the case here.

**Comment by dims** [comment]
@bmwiedemann  Could you please check 1.17 rc1 to see how we are doing?

**Comment by bmwiedemann** [comment]
I'm actually using our 1.16.2 package with a patch to rc1 added to have all the required build deps included.

In the binary diff of two rc1 builds are the usual go-parallelism-related diffs in the .note.go.buildid ELF section of all binaries, but also others in .typelink - already seen in May.
`e2e.test` also gets randomness in a string `/tmp/go-buildXXXXXXXX/b001/_testmain.go` .

Should e2e.test even be in the package?

https://rb.zq1.de/compare.factory-20191028/kubernetes-1.17.0-rc1-compare.out has the package diff.

So overall, pretty similar to the previous state. Could be better, could be worse.

**Comment by dims** [comment]
@bmwiedemann did you already try to add `-trimpath` and `-ldflags=-buildid=` as mentioned in https://github.com/golang/go/issues/34186#issuecomment-529390306 ? (using golang 1.13 of course)

**Comment by bmwiedemann** [comment]
Our main go version is still 1.12, so I did not test those. 
So I guess, to use these, I would append `GOFLAGS='-trimpath -ldflags=buildid='` in
https://github.com/bmwiedemann/openSUSE/blob/master/packages/k/kubernetes/kubernetes.spec#L265 

Is there some way to make these default in our build env? Asking, because there are many go packages that would need them and I'd prefer to not patch all of them individually. Seems `export GOFLAGS=` into env works.

And then I found that I patched the wrong spec file, so did not actually test 1.17 :-(
and getting it to build is not that trivial.
Even building 1.16.2 with go-1.13 needs some work, because it is looking for build deps in a different place and then tries to download them in our offline build env.
But even with internet access, it complains 

```
go: finding k8s.io/kubernetes/vendor/k8s.io/api latest
can't load package: package k8s.io/kubernetes/vendor/k8s.io/api/admission/v1: no matching versions for query "latest"
```
Strange.

**Comment by justaugustus** [comment]
Dims, you've got a fair amount more context on this than me, so reassigning you.
/unassign
/assign @dims

@kubernetes/release-engineering -- This is one to potentially help out with.
/help
/milestone v1.18
/priority important-longterm

**Comment by saschagrunert** [comment]
> _From @dims on September 21, 2018 21:4_
> 
> Please see https://reproducible-builds.org/ specifically https://reproducible-builds.org/docs/ on ideas about how to do deterministic builds. When we get a chance, we should try to examine how far away we are from this goal and what our blockers are.
> 
> Thanks,
> Dims
> 
> _Copied from original issue: [kubernetes/release#637](https://github.com/kubernetes/release/issues/637)_

We could utilize [nix](https://nixos.org/nix/) to easily achieve this by pinning the dependencies to a dedicated git commit. I'm maintaining the kubernetes nix package as well and we're fairly up-to-date with the k8s packages.

**Comment by smourapina** [comment]
Hello @dims and @saschagrunert! 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March, which is about 3 weeks from now. Is this issue still intended for milestone 1.18? Thanks in advance!

**Comment by dims** [comment]
/milestone clear

@smourapina clearing the milestone. thanks!

**Comment by bmwiedemann** [comment]
I recently had a look at 1.17 results and there were still issues left, even when building with go-1.13.

`/usr/bin/kube-apiserver differs in ELF section .typelink`

`/usr/bin/kube-scheduler differs in ELF section .note.go.buildid`

**Comment by dims** [comment]
@bmwiedemann I don't see a run for kubernetes here https://rb.zq1.de/compare.factory-20200430/

**Comment by bmwiedemann** [comment]
The .out files there are only created for differing builds.
https://rb.zq1.de/compare.factory-20200430/reproducible.json lists kubernetes1.17 and 1.18 as reproducible.
However, for kubernetes I had to do both builds with -j1 because build failed otherwise. And usually, various go programs suffered from some race in generation of the .note.go.buildid ELF header [like this](https://rb.zq1.de/compare.factory-20200430/ovnkube-compare.out) . That is a -j1 and a -j4 build differed there.

**Comment by dims** [comment]
Well, we have to celebrate that milestone, right? 🎈 🍰 !!! :)

ack on the -j1/-j4 will poke at it when i get a chance

**Comment by dims** [comment]
@bmwiedemann please do throw me a link with output showing binaries that had trouble with -j1/-j4 (from the kubernetes release artifacts). I'd have to track the build apparatus for each one to do something similar to https://github.com/kubernetes/kubernetes/pull/89136/files

**Comment by bmwiedemann** [comment]
It seems, #89136 fixed it for the kubernetes packages.
However, I have the feeling that go's build IDs were meant to be deterministic - because I never saw more than 2 different results when I varied levels of parallelism.
And instead of patching it out in every software, it would be good to understand and fix where that 1 bit of non-determinism comes from.

other packages I saw with this issue:
* [amazon-ecs-init](https://rb.zq1.de/compare.factory-20200430/amazon-ecs-init-compare.out)
* [brise](https://rb.zq1.de/compare.factory-20200430/brise-compare.out)
* [chartmuseum](https://rb.zq1.de/compare.factory-20200430/chartmuseum-compare.out)
* ~~cilium~~
* [cri-o](https://rb.zq1.de/compare.factory-20200430/cri-o-compare.out) - also had another issue solved with https://github.com/cri-o/cri-o/pull/3708
* [containerd](https://rb.zq1.de/compare.factory-20200430/containerd-compare.out) 
* [heapster](https://rb.zq1.de/compare.factory-20200430/heapster-compare.out)
* [ovnkube](https://rb.zq1.de/compare.factory-20200430/ovnkube-compare.out)
* [prometheus-ha_cluster_exporter](https://rb.zq1.de/compare.factory-20200430/prometheus-ha_cluster_exporter-compare.out)
* [prometheus-sap_host_exporter](https://rb.zq1.de/compare.factory-20200430/prometheus-sap_host_exporter-compare.out)
* [sonobuoy](https://rb.zq1.de/compare.factory-20200430/sonobuoy-compare.out)
* [syncthing](https://rb.zq1.de/compare.factory-20200430/syncthing-compare.out)
* [telegraf](https://rb.zq1.de/compare.factory-20200430/telegraf-compare.out)

and a few more like [minikube](https://rb.zq1.de/compare.factory-20200430/minikube-compare.out) and katacontainers where it might be hidden behind other sources of non-determinism.

**Comment by dims** [comment]
Ack. going to close this out. we can open some new issues when something else pops up.

/close

**Comment by BenTheElder** [comment]
@dims should we stop zero-ing out the buildid now?

**Comment by dims** [comment]
possibly @BenTheElder but we have to verify :(

**Comment by saschagrunert** [comment]
> @dims should we stop zero-ing out the buildid now?

May I ask why?

**Comment by dims** [comment]
@saschagrunert apparently there are fixes in golang compiler itself to better compute the buildid, so we should check it out when we have time.

**Comment by BenTheElder** [comment]
the buildid is a cache key, and the buildid should be reproducible now I think. but we need to confirm. I thought we'd checked that in KIND but it seems we're still zero-ing it.

**Comment by saschagrunert** [comment]
Got it, did some research and proposed the change: https://github.com/kubernetes/kubernetes/pull/101411

**Comment by dims** [comment]
/close

please reopen if needed @bmwiedemann
