### ISSUE TITLE
All GKE tests failing staring with 4d182cec0

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70133]
Starting with merge 4d182cec0, all GKE-releated blocking tests started failing.

Example failures: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-reboot/18413
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/33151

Changes here: https://github.com/kubernetes/kubernetes/compare/46ec13cf7...4d182cec0

Given that the failure message is:

```
W1023 08:02:31.946]  zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that: component "kube-apiserver" from endpoint "gke-c046389281d583ecc15d-9dcb" is unhealthy.
```

... this is almost certain due to this commit:

https://github.com/kubernetes/kubernetes/commit/371b1e7fed2fd7806640ac202b253f90aebfd61e
https://github.com/kubernetes/kubernetes/pull/70105

So, @mikedanese this one appears to be yours.

/sig api-machinery
/sig auth
/priority critical-urgent
/kind failing-test

**Comment by mikedanese** [comment]
I just brought up master in a few days old version of GKE so I suspect it wasn't anything in opensource that broke GKE. I'll continue to investigate and maybe hand off.

**Comment by wangzhen127** [comment]
The tests are still having some failure. But I think that's not related to my change now?

**Comment by jberkus** [comment]
@wangzhen127 I think that's correct.  However, the other failure is blocking getting a green run, so I'd like to hold this open for a day or so in hopes of getting one.

**Comment by jberkus** [comment]
On second thought, we have enough passing GKE tests to call this one closed.  Thanks.

/close
