### ISSUE TITLE
Release-1.11 kubeadm tests failing

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#70139]
This is blocking 1.11.4 from being released.

http://k8s-testgrid.appspot.com/sig-release-1.11-blocking#kubeadm-gce-1.11
http://k8s-testgrid.appspot.com/sig-release-1.11-blocking#kubeadm-gce-1.10-on-1.11

cc @kubernetes/sig-cluster-lifecycle @kubernetes/sig-release-bugs

**Comment by neolit123** [comment]
related PRs:
https://github.com/kubernetes/kubernetes/pull/70141
https://github.com/kubernetes/test-infra/pull/9897

**Comment by neolit123** [comment]
latest efforts
https://github.com/kubernetes/test-infra/pull/9915

**Comment by neolit123** [comment]
the tests are working on the cluster up/down side, except that they fail when dumping the node logs. looking into it.

**Comment by foxish** [comment]
@neolit123 @feiskyer, this is still blocking the release.
cc @krzyzacy @BenTheElder, can you help investigate this further?

**Comment by neolit123** [comment]
@foxish 
still waiting on some test jobs to finish.

**Comment by neolit123** [comment]
1.11 should be unblocked now.

**Comment by foxish** [comment]
This appears to be fixed now. Thanks all!
/close
