### ISSUE TITLE
Flaky test: [sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#70151]
Testgrid: https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster

Examples: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2570
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2560

The error message differs, but all seems to be around problems with connecting to the master. This has failed three times in the last week.

/sig cluster-lifecycle
/kind flake
/priority important-soon

**Comment by AishSundar** [comment]
@jberkus do we want to route this to anyone specific in cluster-lifecycle for deflaking?

**Comment by jberkus** [comment]
@timothysc, can you get someone to look into this?

**Comment by neolit123** [comment]
cc @roberthbailey @justinsb

**Comment by justinsb** [comment]
Aha - I looked at 2572, and tracked it down.  That is #70305

It's a bug where apiserver does not start in time to meet its healthcheck.

I'll pull down some of the others and check they look like the same root cause

**Comment by justinsb** [comment]
Good news - it is rare that apiserver _does_ start on time (looks like 72 / 92 restarted).  The failures happen when we get unlucky and query it during a restart.

**Comment by mariantalla** [comment]
Hey @justinsb @roberthbailey - this is now failing again on [sig-release-master-upgrade/gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master). Any updates/blockers?

cc @jberkus  @AishSundar

**Comment by AishSundar** [comment]
FWIW the failures we are seeing in the last couple of runs are slightly different from before 

```Get https://104.198.171.150/apis/apps/v1/namespaces/e2e-tests-sig-apps-replicaset-upgrade-5m25x/replicasets/rs: dial tcp 104.198.171.150:443: connect: connection refused
not to have occurred```

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1865
