### ISSUE TITLE
how to enable cAdvisor in kubernetes

### ISSUE THREAD

**Issue by damozhiying** [kubernetes/kubernetes#70153]
/kind bug
/sig area/cadvisor

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

1:the port 10255 not listening?but the 10250 is listening , what's the difference about two ports

**Comment by dims** [comment]
```
kubeadm: kubelets in kubeadm clusters now disable the readonly port (10255). If you're relying on unauthenticated access to the readonly port, please switch to using the secure port (10250). Instead, you can now use ServiceAccount tokens when talking to the secure port, which will make it easier to get access to, for example, the /metrics endpoint of the kubelet, securely. (#64187, @luxas)
```
from https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md

**Comment by Marusyk** [comment]
so, how to enable cAdvisor in kubernetes ?
