### ISSUE TITLE
Kubernetes pod resource utilization metrics need better documentation

### ISSUE THREAD

**Issue by bholagabbar** [kubernetes/kubernetes#70179]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I have a Kubernetes Pod that has 

* Requested Memory of 1500Mb
* Memory Limit of 2048Mb

I have 2 containers running inside this pod, one is the actual application (heavy Java app) and a lightweight log shipper.

The pod consistently reports a usage of 1.9-2Gb of memory usage. Because of this, the deployment is scaled (an autoscaling configuration is set which scales pods if memory consumption > 80%), naturally resulting in more pods and more costs

**Yellow Line represents application memory usage**

[![enter image description here][1]][1]

However, on deeper investigation, this is what I found.

On `exec`ing inside the application container, I ran the `top` command, and it reports a total of `16431508 KiB` or roughly 16Gb of memory available, which is the memory available on the Machine.

There are 3 processes running inside the application container, out of which the root process (application) takes *5.9%* of memory, which roughly comes out to 0.92Gb.

The log-shipper simply takes 6Mb of memory.

Now, what I don't understand is *WHY* my pod consistently reports such high usage metrics. Am I missing something ? We're incurring significant costs due to the unintended auto-scaling and would like to fix the same.

  [1]: https://i.stack.imgur.com/K3vpL.png

**What you expected to happen**:
I expect the process memory consumption observed via `top` to be the same as the memory occupied by the pod. That's not happening by a long shot

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure. Is this a fundamental linux/docker issue..?

**Anything else we need to know?**:

Also put up on stackoverflow - https://stackoverflow.com/questions/52963152/kubernetes-pod-reporting-more-memory-usage-than-actual-process-consumption

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nsidhaye** [comment]
Which java version you are using? Are you using `-XX:+UseCGroupMemoryLimitForHeap` parameter so JVM is aware of your request & limits parameters ? 

Possibly you need to use UnlockExperimentalVMOptions depend on which JDK version you are using.   `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`

**Comment by recampbell** [comment]
We saw similar behavior and believe it is due to this known issue: https://success.docker.com/article/the-docker-stats-command-reports-incorrect-memory-utilization

**Comment by onigirisan** [comment]
@bholagabbar I have encountered the same problem. Have you solved it now?

**Comment by bholagabbar** [comment]
@onigirisan What we did was run a bot that restarted our apps every 4 hours. Using this command https://github.com/kubernetes/kubernetes/issues/13488#issuecomment-446101458

This sort of resets the state, number of pods and memory consumption. This was the only temporary workaround we could find.

**Comment by mluscon** [comment]
`/remove-lifecycle rotten`

**Comment by luigi-riefolo** [comment]
any update on this?
 /remove-lifecycle stale

**Comment by woody2011** [comment]
same problem

**Comment by randreev1321** [comment]
I have the same problem.
`kubectl version 
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`

`kubectl top pod minio-prod-0
NAME           CPU(cores)   MEMORY(bytes)   
minio-prod-0   1m           922Mi   `

`docker stats



















































CONTAINER ID        NAME                                                                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e6f1db847082        k8s_minio_minio-prod-0_default_1057898a-0a81-11ea-ab3b-42010a800124_0   0.00%               330.4MiB / 14.69GiB   2.20%               0B / 0B             2.11GB / 2.93GB     29


















































CONTAINER ID        NAME                                                                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e6f1db847082        k8s_minio_minio-prod-0_default_1057898a-0a81-11ea-ab3b-42010a800124_0   0.00%               330.4MiB / 14.69GiB   2.20%               0B / 0B             2.11GB / 2.93GB     29


















































CONTAINER ID        NAME                                                                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e6f1db847082        k8s_minio_minio-prod-0_default_1057898a-0a81-11ea-ab3b-42010a800124_0   0.00%               330.4MiB / 14.69GiB   2.20%               0B / 0B             2.11GB / 2.93GB     29


















































CONTAINER ID        NAME                                                                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
e6f1db847082        k8s_minio_minio-prod-0_default_1057898a-0a81-11ea-ab3b-42010a800124_0   0.00%               330.4MiB / 14.69GiB   2.20%               0B / 0B             2.11GB / 2.93GB     29
`

**Comment by randreev1321** [comment]
> I have the same problem.
> 
> **kubectl version:**
> `Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`
> 
> **kubectl top pod minio-prod-0:**
> `NAME CPU(cores) MEMORY(bytes) minio-prod-0 1m 922Mi `
> 
> **docker stats:**
> `CONTAINER ID NAME CPU % MEM USAGE / LIMIT MEM % NET I/O BLOCK I/O PIDS e6f1db847082 k8s_minio_minio-prod-0_default_1057898a-0a81-11ea-ab3b-42010a800124_0 0.00% 330.4MiB / 14.69GiB 2.20% 0B / 0B 2.11GB / 2.93GB 29 `
> 
> **docker version**
> `Client: Version: 18.09.7 API version: 1.39 Go version: go1.11.2 Git commit: 2d0083d Built: Tue Sep 3 10:03:35 2019 OS/Arch: linux/amd64 Experimental: false Server: Engine: Version: 18.09.7 API version: 1.39 (minimum version 1.12) Go version: go1.11.2 Git commit: 2d0083d Built: Tue Sep 3 10:02:48 2019 OS/Arch: linux/amd64 Experimental: false`

Looks like the problem in the docker.
On version `docker-19.03.4` those problem doesn't show.

**Comment by bitva77** [comment]
Is there a related Docker bug/issue that this was tracked in or did it just magically fix itself?  :)

**Comment by danielsikorskiy** [comment]
Any updates on this issue? Same problem ....
Kubectl top shows way more than top / docker stats / any other memory usage checker.

Is there any documentation on how kubectl top actually calculates the memory usage for each pod?

**Comment by dongwangdw** [comment]
In kubernetes cluster, the cadvisor is used for mem metrics, `container_memory_usage_bytes`, and this one includes more than expected. I think this is the cause. 
I have a pod which has 1.05 GB from grafana, but with `kubectl top` only 435MB.

**Comment by SaschaHeyer** [comment]
Same issue

**Comment by arvin6msd** [comment]
same here as well. Shows 2.5 GiB in kubectl top while docker stats shows only 966Mib

**Comment by yangshuhao** [comment]
I have the same problem; i want to known, how to solved?

**Comment by gacalheiros** [comment]
I am also facing this issue.
Kubernetes: 1.15.6
docker: 18.09.4

**Comment by picaso** [comment]
Wow this has been an issue for almost 2 years?

**Comment by demon999** [comment]
Same issue
pod.memory.cache increase.

**Comment by HeikoScholtes** [comment]
Any news here?

**Comment by yuraxdrumz** [comment]
Same issue

**Comment by debu99** [comment]
same issue on ruby application

**Comment by larytet** [comment]
Python 3 same story

**Comment by larytet** [comment]
My Python  process has 600MB footprint. My process UNIX forks 3 processes. Should I expect to see in k8s 1.8GB occupied ?

**Comment by pabrahamusa** [comment]
I have similar issue where docker stats reports 
`  1.1GiB / 26GiB`
if i do a top in the node the app is only taking 26% of memory 

However kubectl top shows 26 GB of memory usage

I am assuming there are some issues how kubernetes find memory details with Java apps.

**Comment by graememross** [comment]
We have a similar problem but it is with a golang program (An operator)

I have profiled the program and we have no memory leaks - profiler reports a fairly stable memory usage of around 30MB of heap space occupied. However as time goes on kubectl top reports that the memory used by the pod increases hour on hour until it hits the resource limits of the deployment and it gets restarted.

This is happening about once every 24 hours.

What I have observed seems to be that the program allocates memory uses it then frees it back to the operating system. However the operating system does not reclaim this memory immediately unless the k8s node is under memory pressure. Interestingly if the k8s node is busy (lots of pods running and high memory usage) then the pod keeps its memory usage to around 50Mb and never varies. The only problem is when the k8s node is not under stress.

It appears the k8s OOM killer does not take into account memory that has been freed to the operating system before reaping a process .

I have tried setting GODEBUG=madvdontneed=1 and this improves the situation substantially but it still eventually fails

Is anyone aware of any settings I could add to the pod to ensure that the memory image is kept to a minimum and never triggers the OOM killer?

**Comment by lokiwins** [comment]
I was running into issues with `kubectl top` reporting one value for memory but in grafana using `container_memory_usage_bytes`

Swapped to using `container_memory_working_set_bytes` and `kubectl top` matched what was shown in grafana

**Comment by ehashman** [comment]
This is really a documentation gap.

Most of the comments here don't report _which_ memory metric from cadvisor you are looking at, but I suspect it is `container_memory_usage_bytes`.

`container_memory_working_set_bytes` will likely correspond to what you have in top. But your containers may preemptively reserve more memory than that, even if it is not in active use, which is why it shows up in the stats. This is a normal kernel behaviour. See https://github.com/kubernetes/website/issues/25388#issuecomment-816952936 for more details.

/retitle Kubernetes pod resource utilization metrics need better documentation
/kind documentation

/close

duplicate of https://github.com/kubernetes/website/issues/25388
