### ISSUE TITLE
Pod of DaemonSet was no evicted when node was down

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#70184]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Pod of DaemonSet was not evicted when node was down.

**What you expected to happen**:

Pod should be evicted when node was down.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create DaemonSet to run on some of cluster nodes.

2. Create Service and set pod selector to point to pods of the DaemonSet.

3. Shut down one of cluster node. Still see pod was running since DaemonSet by default tolerate taint `node.kubernetes.io/not-ready:NoExcute` and `node.kubernetes.io/unreachable:NoExcute`.

4. Access service. It will fail randomly as the service endpoints were not updated.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-34-generic
- Install tools:
- Others:

**Comment by liqlin2015** [comment]
sig/node

**Comment by liqlin2015** [comment]
Should the user decide whether tolerate taint `node.kubernetes.io/not-ready:NoExcute` and `node.kubernetes.io/unreachable:NoExcute`?

**Comment by mysunshine92** [comment]
as for Pod of DaemonSet，  if we evict the pod when node is down，daemonset will create one. so in the function of doEvictionPass, if the pod is managed by a daemonset, ignore it.
