### ISSUE TITLE
Windows containers do not have entries in the hosts file

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#70189]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig windows

**What happened**:

When deploying Kubernetes pods, the Linux containers will contain the following entries in the ``/etc/hosts`` file:

    # Kubernetes-managed hosts file.
    127.0.0.1       localhost
    ::1     localhost ip6-localhost ip6-loopback
    fe00::0 ip6-localnet
    fe00::0 ip6-mcastprefix
    fe00::1 ip6-allnodes
    fe00::2 ip6-allrouters
    10.240.0.67     dns-querier-1.dns-test-service.e2e-tests-dns-x649p.svc.cluster.local    dns-querier-1

However, these are not set on Windows containers; the container's ``C:\Windows\System32\drivers\etc\hosts`` file does not contain any entry. This can be attributed to the fact that individual files cannot be mounted on Windows containers the same way they are on Linux containers.

It can be fixed with a change to the kubelet once Windows Server 2019 has shipped, and once CRI-ContainerD is enabled on Windows. We cannot fix it for Windows Server 1803 or earlier with dockershim.

**What you expected to happen**:

The ``:\Windows\System32\drivers\etc\hosts`` file should be managed and populated by Kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

Spawn a Windows pod, and check its container's ``:\Windows\System32\drivers\etc\hosts`` file.

    kubectl create namespace e2e-tests-dns-x649p
    kubectl create -f windows_pod.yaml  # https://paste.ubuntu.com/p/ZgfQS9Wgcf/
    kubectl exec -n e2e-tests-dns-x649p dns-test-2ed58282-6d85-11e8-89cc-000c29738e2c -c querier -- cmd /S /C type C:\\Windows\\System32\\drivers\\etc\\hosts

Compare the result with a Linux pod's container's ``/etc/hosts`` file.

    kubectl create namespace e2e-tests-dns-x649p
    kubectl create -f linux_pod.yaml  # https://paste.ubuntu.com/p/kcFcfxYjm3/

    kubectl exec -n e2e-tests-dns-x649p dns-test-2ed58282-6d85-11e8-89cc-000c29738e2c -c querier -- cat /etc/hosts

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Windows Server 1803 (10.0.17134.48)
- Install tools: acs-engine v0.24.0
- Others:

**Comment by PatrickLang** [comment]
This requires single-file mapping, which won't work in Windows Server version 1803. It should be possible with Windows Server 2019 along with ContainerD

**Comment by feiskyer** [comment]
Will it work with Docker on Windows Server 2019?

**Comment by PatrickLang** [comment]
Not in 18.09 or earlier. I'm not sure what release it will be in because it will require migrating to containerd.

**Comment by AishSundar** [comment]
@PatrickLang should this issue be tracked for 1.13 in addition to https://github.com/kubernetes/kubernetes/issues/65016? If so please apply the appropriate priority and milestone labels please.

@nikopen

**Comment by PatrickLang** [comment]
This one needs to be in v1.14. We need to get cri-containerd working first to fix this.

**Comment by AishSundar** [comment]
Thanks
/milestone v1.14

**Comment by daschott** [comment]
By default, hosts file are not being used in Windows, it is all registry based. What features is this blocking?

CC @madhanrm

**Comment by bclau** [comment]
The hosts file entries are still taken into account on Windows when it has to resolve a DNS name. This is blocking DNS conformance tests, like ``[sig-network] DNS  should provide DNS for the cluster  [Conformance]``.

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, is this intended to be implemented in the following week?

**Comment by bclau** [comment]
No. It is meant to be fixed in the next release, when the Containerd support will be introduced.

**Comment by xmudrii** [comment]
Hello! We have started the code freeze for 1.15. Is this issue still planned for the 1.15 cycle?

**Comment by xmudrii** [comment]
Is there any update is the containerd implementation finished? Are there any relevant issues or PRs that we can use for tracking?

**Comment by dims** [comment]
@bclau sounds like a no-go for 1.15, let's just move it out as no one is working on it as well.

/milestone v1.16

**Comment by Pothulapati** [comment]
Hello! I'm part of the bug triage team for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16? If not please re-tag the issue to the planned milestone.

**Comment by PatrickLang** [comment]
/milestone v1.17
We won't be able to do this until containerd is ready. It might work in 1.17

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by bclau** [comment]
We have a PR for it, as you can see above: https://github.com/kubernetes/kubernetes/pull/83730
It;s a pretty small PR too.

**Comment by josiahbjorgaard** [comment]
@bclau @PatrickLang The v1.17 code freeze is this Thursday, end of day Pacific time. Will this issue be closed by then?

**Comment by josiahbjorgaard** [comment]
/milestone v1.18

(code freeze v1.17)

**Comment by PatrickLang** [comment]
This is going to need a Windows fix, not a ContainerD fix. We won't have that before code freeze on 5 March, so I'm pushing this out to 1.19.

/milestone v1.19

**Comment by marosset** [comment]
This is being tracked with MS internal work item 25807692
The Windows team thinks an OS fix for Windows Server 2019 will be released with the June patches.
I will post updates here as I get them.

**Comment by kbruner** [comment]
Hello from the bug triage team! This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting June 25th (about 4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.19, is it still planned for this release?

**Comment by marosset** [comment]
@immuzz can you comment on when we can expect a Windows fix for Windows Server 2019 that addresses the single file mount issues in containers when a target file already exists in the container?

**Comment by marosset** [comment]
@kbruner we are waiting on a Windows OS fix from Microsoft to proceed here. If that fix comes in time for us to validate this functionality in 1.19 we would like it to be included in 1.19.

**Comment by kbruner** [comment]
Hello! As this issue seems to depend on PR https://github.com/kubernetes/kubernetes/pull/83730 which has been pushed to v1.20, should this issue also be pushed to that milestone?

**Comment by marosset** [comment]
/milestone 1.20

The OS fix is now expect to be available as part of August Windows patches and then changes to the kubelet will need to follow.

/cc @immuzz

**Comment by immuzz** [comment]
@marosset yes it is expected be part of August Windows release

**Comment by bai** [comment]
Hey 👋 Bug Triage here. Wanted to follow up on the status of this issue as we're approaching code freeze on 12.11.2020. This issue is tagged for 1.20, is it still planned for this release?

**Comment by marosset** [comment]
@bai - Yes, we'd like to make it into 1.20.
We were waiting on some bugfixes in the Windows OS and those bugfixes are now available (as of Oct 20 2020).

**Comment by marosset** [comment]
I believe the work involved here is to 
- update 
https://github.com/kubernetes/kubernetes/blob/ec453ffb1a8c829ae5d62400a845836f708f80d0/pkg/kubelet/kubelet_pods.go#L137-L145 to enable this fucntionality for WIndows if container-runtime == remote (still disable this for DockerShim)
- Update/Add test coverage
- Update documentation - possible this section https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#feature-restrictions ?

**Comment by marosset** [comment]
/milestone v1.21

Moving to 1.21 since the required OS fixes were not available in time to implement this functionality in v1.20

**Comment by kcmartin** [comment]
Hello! I am from the Bug Triage team! This issue has not been updated for a long time, so I'd like to check on the status. The code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.

As the Issue is tagged for 1.21, is it still planned for this release?

**Comment by claudiubelu** [comment]
> Can this be reopened? From a related problem I have experienced using HostAlias for Windows pod deployments, this issue does not seem to be resolved. Instead, it looks as if it was closed by accident because the conversation went cold.

Hello. What Kubernetes version are you running? Also, on the Windows nodes, do you use docker, or containerd? This is only supported on Windows nodes with containerd, since it supports single file mapping, which is required in order to mount single files into Windows containers.

**Comment by brandongarcia-ms** [comment]
> Hello. What Kubernetes version are you running? Also, on the Windows nodes, do you use docker, or containerd? This is only supported on Windows nodes with containerd, since it supports single file mapping, which is required in order to mount single files into Windows containers.

We have experimented with both 1.22.11 and a 1.23 release and yea, the container runtime is containerd. Any other ideas to check up on?
