### ISSUE TITLE
Unexpectedly broken test in OwnerReferencesPermissionEnforcement admission controller

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#70192]
/kind flake
/sig testing
/sig auth

we are injecting a restMapper into this admisson controller while in its test, the restMapper somehow become empty when we remove internal clientset/informer dependency from it (#70167). now we come up with a walkaround in which we manually init the legacy schema via a dry import so that the built-in resources can be installed. this failing test suggests that the test is not quite correct logically.

**Comment by deads2k** [comment]
/assign @yue9944882 

Are you up for trying to figure out how to avoid requiring the internal types?

**Comment by jberkus** [comment]
What test does this break?  Links?

**Comment by jberkus** [comment]
OK, setting priority so that I know this isn't a 1.13 blocker.

/priority important-longterm
