### ISSUE TITLE
e2e: strict --provider checking

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#70200]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**What happened**:

In PR #68483 we tightened the --provider parameter checking of the e2e.test binary such that it only accepted known providers. This turned out to be problematic (https://github.com/kubernetes/kubernetes/issues/70058) because people had started to depend on the previous behavior, which was to accept anything and merely warn about it.

For the sake of giving people time to adapt, PR #70141 reverted to the older behavior.

**What you expected to happen**:

In 1.14 we want to allow only known providers. While at it, the error handling for unknown providers should be enhanced (print proper error message instead of calling Failf, which panics).

/assign
/sig testing

**Comment by pohly** [comment]
@neolit123 kubeadm was one of the tools which got broken by the tightening of the `--provider` parameter checking. Does kubeadm still rely on the acceptance of unknown provider parameters or can the current warning be turned into an error now?

/remove-lifecycle stale

**Comment by neolit123** [comment]
@pohly yes the kubernetes-anywhere deployer is still bound to provider=kubernetes-anywhere (unknown) in test infra jobs.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-x-on-y.yaml#L25

we went back and forth on this topic, but if you wish to replace this support for unknown deployers i can switch those jobs to `skeleton`.
LMK.

**Comment by neolit123** [comment]
given one release has passed with the deprecated message on the CLI, it's probably safe to remove this functionality now. :)

**Comment by pohly** [comment]
"Lubomir I. Ivanov" <notifications@github.com> writes:
> we went back and forth on this topic, but if you wish to replace this
> support for unknown deployers i can switch those jobs to `skeleton`.

Yes, please do. Once that is complete, I'll turn the warning into an error.

**Comment by neolit123** [comment]
done:
https://github.com/kubernetes/test-infra/pull/10913
