### ISSUE TITLE
Master should schedule Pod on a different node after N failed runs

### ISSUE THREAD

**Issue by dilyevsky** [kubernetes/kubernetes#70201]
/kind feature

**What happened**:

Some of our nodes got into inconsistent state which prevented them from running any new workload (docker login got broken) and master attempted to re-launch Pods on the same node over and over.

**What you expected to happen**:

Master (scheduler?) should give up on node after numerous failed attempts to launch a Pod and try a different node. Wouldn't really do anything if Pod itself is broken (e.g docker image doesn't exist, etc) but would prevent workload from stubbornly trying to launch on the broken node.

**How to reproduce it (as minimally and precisely as possible)**: break the node in a way that it can't launch any workload (e.g prevent docker from authenticating)

**Anything else we need to know?**: n/a

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by wanghaoran1988** [comment]
Is this something the [node-problem-detector](https://github.com/kubernetes/node-problem-detector) designed for ?

**Comment by dilyevsky** [comment]
@wanghaoran1988 not everything can be detected with that approach (and it's always an uphill battle) and some problems could be very workload-specific.

**Comment by Krueladin** [comment]
Would like to see this issue revisited. Some of our deployments are hanging up and expiring because Kubernetes is not smart enough to try scheduling the service on a different node. Would like to avoid the manual delete operations.
