### ISSUE TITLE
kube-dns.yaml ,  why i/o timeout

### ISSUE THREAD

**Issue by wfwf1990** [kubernetes/kubernetes#70218]
I1025 04:07:14.182379       1 dns.go:48] version: 1.14.6-3-gc36cb11
I1025 04:07:14.182824       1 server.go:73] ConfigMap and ConfigDir not configured, using values from command line flags
I1025 04:07:14.182862       1 server.go:112] FLAG: --alsologtostderr="false"
I1025 04:07:14.182882       1 server.go:112] FLAG: --config-dir=""
I1025 04:07:14.182885       1 server.go:112] FLAG: --config-map=""
I1025 04:07:14.182887       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I1025 04:07:14.182888       1 server.go:112] FLAG: --config-period="10s"
I1025 04:07:14.182891       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I1025 04:07:14.182893       1 server.go:112] FLAG: --dns-port="10053"
I1025 04:07:14.182896       1 server.go:112] FLAG: --domain="cluster.local."
I1025 04:07:14.182899       1 server.go:112] FLAG: --federations=""
I1025 04:07:14.182902       1 server.go:112] FLAG: --healthz-port="8081"
I1025 04:07:14.182904       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I1025 04:07:14.182939       1 server.go:112] FLAG: --kube-master-url="http://192.168.2.202:8080"
I1025 04:07:14.182943       1 server.go:112] FLAG: --kubecfg-file=""
I1025 04:07:14.182944       1 server.go:112] FLAG: --log-backtrace-at=":0"
I1025 04:07:14.182948       1 server.go:112] FLAG: --log-dir=""
I1025 04:07:14.182950       1 server.go:112] FLAG: --log-flush-frequency="5s"
I1025 04:07:14.182951       1 server.go:112] FLAG: --logtostderr="true"
I1025 04:07:14.182953       1 server.go:112] FLAG: --nameservers=""
I1025 04:07:14.182955       1 server.go:112] FLAG: --stderrthreshold="2"
I1025 04:07:14.182956       1 server.go:112] FLAG: --v="2"
I1025 04:07:14.182958       1 server.go:112] FLAG: --version="false"
I1025 04:07:14.182970       1 server.go:112] FLAG: --vmodule=""
I1025 04:07:14.183008       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
I1025 04:07:14.183147       1 server.go:213] Skydns metrics enabled (/metrics:10055)
I1025 04:07:14.183164       1 dns.go:146] Starting endpointsController
I1025 04:07:14.183166       1 dns.go:149] Starting serviceController
I1025 04:07:14.183475       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1025 04:07:14.183481       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I1025 04:07:14.683292       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:15.183493       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:15.683587       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:16.183636       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:16.683568       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:17.183637       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:17.683648       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:18.183622       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:18.683250       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:19.183282       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:19.683647       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:20.183430       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:20.684138       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:21.183507       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:21.683648       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:22.183214       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:22.683278       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:23.183335       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:23.683642       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:24.183485       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:24.683556       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:25.183573       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:25.683646       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:26.183654       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:26.683357       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:27.183417       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:27.683954       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:28.183493       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:28.683426       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:29.183398       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:29.683787       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:30.183908       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:30.683751       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:31.183342       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:31.683363       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:32.183252       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:32.683656       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:33.183540       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:33.683507       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:34.183696       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:34.683720       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:35.183801       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:35.683625       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:36.184111       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:36.683829       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:37.183414       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:37.683267       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:38.183292       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:38.683478       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:39.183418       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:39.683857       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:40.184341       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:40.684010       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:41.184049       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:41.683949       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:42.183838       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:42.683230       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:43.183856       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:43.683766       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I1025 04:07:44.183871       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E1025 04:07:44.184178       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get http://192.168.2.202:8080/api/v1/endpoints?resourceVersion=0: dial tcp 192.168.2.202:8080: i/o timeout
E1025 04:07:44.184725       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get http://192.168.2.202:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.2.202:8080: i/o timeout

**Comment by wfwf1990** [comment]
I am already stop firewalld and selinux!

**Comment by wfwf1990** [comment]
[root@master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:47:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by anfernee** [comment]
E1025 04:07:44.184178 1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get http://192.168.2.202:8080/api/v1/endpoints?resourceVersion=0: dial tcp 192.168.2.202:8080: i/o timeout
E1025 04:07:44.184725 1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get http://192.168.2.202:8080/api/v1/services?resourceVersion=0: dial tcp 192.168.2.202:8080: i/o timeout

These 2 lines of log basically say for some reason, it cannot connect to the master.

**Comment by wfwf1990** [comment]
> /sig network



> /sig network

Can you give me more details?

**Comment by anfernee** [comment]
With those logs, this is the only thing anybody can tell. Probably what you can do is to provide more details, like reproduce-able steps (how you bring up the cluster, the network topology, etc), so that people could help. Even if they don't have the exact lab environment, they might have an idea.
