### ISSUE TITLE
Unable to enter into kubernetes pod

### ISSUE THREAD

**Issue by CMADHANKUMAR** [kubernetes/kubernetes#70235]
The below one is the pod that i need to login and check out the mount points.

[root@kube-master-0-prodes-1539172764 centos]# kubectl get pod
sNAME                                                      READY   STATUS    RESTARTS   AGE
good-deer-minio-795c9b457d-sbnjg                          1/1     Running   0          31m

But,when i try to login i got the error like below.

[root@kube-master-0-prodes-1539172764 madhan]# kubectl exec -it good-deer-minio-795c9b457d-sbnjg -- /bin/bash
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

command terminated with exit code 126
-------------------------------------------------------------------------------------------------------
I am unable to open my pod's bash

**Comment by mysunshine92** [comment]
you can try this command 
kubectl exec -it good-deer-minio-795c9b457d-sbnjg -- /bin/sh

**Comment by CMADHANKUMAR** [comment]
> you can try this command
> kubectl exec -it good-deer-minio-795c9b457d-sbnjg -- /bin/sh

It works well,thank you !
