### ISSUE TITLE
Node gc can't prune multi-repo images

### ISSUE THREAD

**Issue by dbazhal** [kubernetes/kubernetes#70238]
**What happened**:
Image cleanup saves orphaned layers referenced in multiple repositories, which leads to node disk pressure.

**What you expected to happen**:
I expect that cleanup removes all untagged, unused images/layers making nodes healthy.

**How to reproduce it (as minimally and precisely as possible)**:
Tag image twice in two different repositories in docker resigtry, use both images on the same kube node, drop it, watch logs(gc kubelet log).

**Anything else we need to know?**:
```logs
# kubelet gc log
unable to delete 176fc649a386 (must be forced) - image is referenced in multiple repositories

# docker images
docker images | grep -i 176fc649a386
docker-registry.default.svc:5000/demo-infra/showcase                           <none>              176fc649a386        38 hours ago        1.13 GB
docker-registry.default.svc:5000/demo-testing/showcase                         <none>              176fc649a386        38 hours ago        1.13 GB
```

**Environment**:
- Kubernetes version - v1.11.0+d4cacc0
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: openshift ansible installer
- Others: docker version -  1.13.1, build 8633870/1.13.1

/king bug

**Comment by flyingcougar** [comment]
:+1: I am facing the same issue.

**Comment by myniva** [comment]
Is this maybe fixed by https://github.com/kubernetes/kubernetes/pull/70647?

**Comment by dbazhal** [comment]
Don't know - too few details i know about both cases. Will test after release, and close if issue is outdated or collect more info.
