### ISSUE TITLE
Emit event when live/readiness probe transitions to success

### ISSUE THREAD

**Issue by tomasaschan** [kubernetes/kubernetes#70231]
When a container in a pod has a readiness probe defined, and that probe has a too short `initialDelaySeconds` value, the events list (from `kubectl describe pod`) can look like this:

```
Events:
  Type     Reason                 Age   From                         Message
  ----     ------                 ----  ----                         -------
  Normal   Scheduled              84s   default-scheduler            Successfully assigned myapp-5798dd798c-t7dqs to docker-for-desktop
  Normal   SuccessfulMountVolume  84s   kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-gvnc2"
  Normal   Pulled                 75s   kubelet, docker-for-desktop  Container image "myapp:latest" already present on machine
  Normal   Created                74s   kubelet, docker-for-desktop  Created container
  Normal   Started                72s   kubelet, docker-for-desktop  Started container
  Warning  Unhealthy              65s   kubelet, docker-for-desktop  Readiness probe failed: Get http://10.1.0.103:80/healthz/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
However, as no new event is emitted when the probe state transitions to success, the last event in the list is of type/reason `Warning`/`Unhealthy`, even though the pod is no longer unhealthy.

It would be nice if the probe transition to success could emit an event here as well, so that when the pod becomes healthy the events list looks something like

```
Events:
  Type     Reason                 Age   From                         Message
  ----     ------                 ----  ----                         -------
  Normal   Scheduled              84s   default-scheduler            Successfully assigned myapp-5798dd798c-t7dqs to docker-for-desktop
  Normal   SuccessfulMountVolume  84s   kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-gvnc2"
  Normal   Pulled                 75s   kubelet, docker-for-desktop  Container image "myapp:latest" already present on machine
  Normal   Created                74s   kubelet, docker-for-desktop  Created container
  Normal   Started                72s   kubelet, docker-for-desktop  Started container
  Warning  Unhealthy              65s   kubelet, docker-for-desktop  Readiness probe failed: Get http://10.1.0.103:80/healthz/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   Healthy                11s   kubelet, docker-for-desktop  Readiness probe succeeded.
```
This would maybe alleviate [some confusion][so] on the part of Kubernetes newbies like myself.

[so]: https://stackoverflow.com/questions/52967947/

/kind feature

**Comment by tomasaschan** [comment]
/remove-lifecycle rotten

I understand this might not be high priority, but I still think it would be valuable.

**Comment by tomasaschan** [comment]
/remove-lifecycle rotten

@hzxuzhonghu is there any chance this will ever be looked at? If not, you might as well close this issue without waiting for @k8s-ci-robot...

**Comment by hzxuzhonghu** [comment]
Seems people in node sig have no bandwidth , let's close now

/close

**Comment by neerajgrg** [comment]
Is there any update on this ? it seems like an necessary improvement to be added to kubernetes. Currently when we describe the pod , it just shows the failure events and does not show up the success event , although the pod is in ready state.

**Comment by aaalex474** [comment]
There is one more reason to add this event.
Now I find no way to check when the pod gets ready. (It gets ready when the readiness probe passes for the first time)
