### ISSUE TITLE
Azure: Instance metadata fixes and improvement

### ISSUE THREAD

**Issue by khenidak** [kubernetes/kubernetes#70246]
- Azure cloud provider does not correctly handle failed calls to instance metadata endpoint. We currently handle transport errors but we don't handle response errors. Ref: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_instance_metadata.go#L113

we should handle `resp.statusCode != 200`-- This currently yields into empty ip address assigned to node objects.

- Remove the fall back to ARM once the above has been fixed. This removes the need for having identities in `azure.json` in case of `useInstanceMetadata = true`

- Add `user-agent: golang/kubernetes` request header for all calls to instance metadata   

- Cache the instance metadadata response and reuse for responding to `NodeAddress` and the rest of the calls. We can limit the call to `once per min` or even less.

@kubernetes/sig-azure 
@feiskyer 

**Environment**:
- Kubernetes version (use `kubectl version`): `all`
- Cloud provider or hardware configuration: `Azure`
- OS (e.g. from /etc/os-release): `Ubuntu xenial`
- Kernel (e.g. `uname -a`): `all`
- Install tools: `all`
- Others:

/king bug

**Comment by khenidak** [comment]
@kubernetes/sig-azure

**Comment by feiskyer** [comment]
Let me start adding the cache next week.

**Comment by feiskyer** [comment]
Filed #70353 to fix this.
