### ISSUE TITLE
ConfigError error=Unknown filter plugin 'concat'

### ISSUE THREAD

**Issue by hulu1522** [kubernetes/kubernetes#70257]
**What happened**:
fluentd-es-v2.2.1 seems to be missing a gem when starting up.

**What you expected to happen**:
The pod starts up

**How to reproduce it (as minimally and precisely as possible)**:
Deploy `fluentd-es-ds.yaml` with corresponding configmap

**Anything else we need to know?**:
```
2018-10-25 22:14:56 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unknown filter plugin 'concat'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
`Ubuntu Xenial 16.04 LTS`
- Kernel (e.g. `uname -a`):
```
Linux kube-minion-02 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

/king bug

**Comment by ermajn** [comment]
+1

**Comment by damozhiying** [comment]
+1

**Comment by ltupin** [comment]
+1

**Comment by chandaku** [comment]
I am also seeing this problem is there any workaround. @ltupin did you care anything special while build another docker container.

**Comment by ermajn** [comment]
@chandaku I've builded image also. Pushed it to my docker registry and changed configuration so it uses my image instead of pre-builded one.

**Comment by ltupin** [comment]
same as @ermajn said @chandaku ;-)

**Comment by chandaku** [comment]
Worked for me as well, created my own image and pushed to docker registry and arrived to my goal. Thanks

**Comment by ltupin** [comment]
@leosunmo I've just rebuild the fluentd container from source here:
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
So it seems that the container available in the registry is sort of "old" one... No sure about the relation with concat really.

**Comment by JoaAlteos** [comment]
Thank you @ltupin, I can confirm that rebuilding the image from source and posting it to my private container registry fixes this issue.
It seems like the concat plugin was added, versions were bumped but a new image was not created.
Concat added: https://github.com/kubernetes/kubernetes/commit/079136fd5964502e6d3b43a6bdbabe24d078767d
Versions bumped without a new image: https://github.com/kubernetes/kubernetes/commit/def00298c3c47b514895d3978f47f2fdc2733a73

**Comment by narg95** [comment]
@ltupin worked :)

@kubernetes-team just push the new version to the registry please

**Comment by ld-singh** [comment]
Not able to build new image as well now. Getting below error:
/bin/sh: 1: ulimit: error setting limit (Operation not permitted)

Newer version on fluentd-es image i.e. 2.3.1 giving same error as older versions:

config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unknown filter plugin 'concat'. Run 'gem search -rd fluent-plugin' to find plugins"

**Comment by zhwill** [comment]
i have the same problem，20181226
k8s 1.13.0
elasticsearch:v6.3.0
kibana-oss:6.3.2
fluentd-elasticsearch:v2.2.0

`[centos@k8s-master elk]$ kubectl get pod -n kube-system 
NAME                                    READY   STATUS    RESTARTS   AGE
......
fluentd-es-v2.2.1-dkmnp                 0/1     Error     1          6s
fluentd-es-v2.2.1-xgvql                 0/1     Error     1          6s
......
[centos@k8s-master elk]$ kubectl logs -f fluentd-es-v2.2.1-dkmnp -n kube-system 
2018-12-26 10:41:59 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unknown filter plugin 'concat'. Run 'gem search -rd fluent-plugin' to find plugins"
[centos@k8s-master elk]$ `

**Comment by vinhnglx** [comment]
Thanks, @ltupin . I built the image from source and it works perfectly. 

@zhwill you can try to use my image https://cloud.docker.com/u/siliconavengers/repository/docker/siliconavengers/fluentd-elasticsearch

**Comment by q1054261752** [comment]
[root@kube-node1 fluentd-elasticsearch]# kubectl logs fluentd-es-v2.2.1-8sbc5 -n kube-system -f
2019-01-30 08:40:21 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unknown filter plugin 'd plugins"

what do I will do?
