### ISSUE TITLE
Windows GotPodNetworkStatus assumes addToNetwork is idempotent, it's not 

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#70279]
**What happened**:

On Windows, CNI plugins always get called twice (or more) with command ADD when a pod is created.

The issue is that `cni_windows.go:GetPodNetworkStatus()` calls `plugin.addToNetwork` to check the status, but this triggers a new add.

**What you expected to happen**:

Only a single ADD since ADD is not idempotent.

As per the (current, at least) CNI spec: 

> A runtime must not call ADD twice (without a corresponding DEL) for the same (network name, container id, name of the interface inside the container). This implies that a given container ID may be added to a specific network more than once only if each addition is done with a different interface name.

**How to reproduce it (as minimally and precisely as possible)**:

Network a pod on windows, will see two copies of this log:
```
I1023 16:05:18.098116    7176 cni.go:275] About to del CNI network k8s-pod-network ...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by fasaxc** [comment]
@kubernetes/sig-windows-bugs

**Comment by feiskyer** [comment]
The ADD call is workaround for fetching pod network status. 

@dineshgovindasamy @madhanrm @PatrickLang Do we have any ETA to remove this workaround?

**Comment by fasaxc** [comment]
I put up a PR that has an alternative approach but it relies on the name of the interface being consistent with those used by the existing CNI plugins (i.e. it has to contain the container ID).  Might be a step int he right direction, at least.  I can respin if there's an alternative approach but I couldn't see an API to determine the HNS endpoints attached to a container.

**Comment by dineshgovindasamy** [comment]
With the CRI ContainerD implementation we are removing the multiple ADD calls. 2019 as a platform supports namespace as a top level object. We are making the ContainerD changes to expose and use namespace. Once the code stabilizes in ContainerD we will bring it to Dockershim.

**Comment by PatrickLang** [comment]
Cc @jsturtevant

**Comment by craiglpeters** [comment]
@fasaxc can you confirm if you're still facing this issue with the latest CNI?

**Comment by fasaxc** [comment]
We ran into this very recently and had to put in a new workaround in our CNI plugin.  We ended up creating a registry key for each container with a timestamp so we could tell if an ADD was for a "recently seen" container.  Would be great to have a fix in Kubernetes.

**Comment by craiglpeters** [comment]
@fasaxc can you point to the CNI binaries (including version) you are using?

@dineshgovindasamy are you clear what is going on here?

**Comment by fasaxc** [comment]
@craiglpeters That's Calico for Windows, which is part of Tigera's commercial offering.  We believe the standard open source CNI plugins can hit the same race though.  The customer who found the issue was doing a long-running churn test and they found that we were leaking IP addresses.

It turned out to be the case where kubelet sends a DEL to tear down the pod but the status timer pops and sends an ADD to collect status before the DEL has finished.

**Comment by daschott** [comment]
the issue with consecutive ADD calls is resolved in the v2 plugins to my understanding that use an updated workflow: https://github.com/microsoft/windows-container-networking/

 @nagiesek can confirm.

**Comment by dineshgovindasamy** [comment]
@fasaxc @craiglpeters @daschott 

Network Namespaces were not a first-class citizen on any Windows version prior to Windows Server 2019. We operate on an endpoint basis, and we needed an additional CNI call to replicate DNS registry keys. If you remove this call, then it becomes an issue as the new container inside the POD won't have any DNS registry keys set.

We added the network namespace support in Windows Server 2019 and We did the work to enable network namespace in containerD, which allowed us to remove the multiple "add" calls. ContainerD work is complete. 

Now for Dockershim, i am hoping we will deprecate it once ContainerD support comes in. but you can also do the same changes that we have done in ContainerD to support network namespace and remove the extra add call to the CNI. 

Adding namespace and removing the extra "ADD" call will work only for Windows server2019 and above.
