### ISSUE TITLE
make default container network interface name configurable

### ISSUE THREAD

**Issue by curu** [kubernetes/kubernetes#70284]
**What would you like to be added**:
make the default container network interface name configurable, so that one can change it to sth. like 'eth1'

**Why is this needed**:
we have many legacy services which get their listen ip from "eth1"  interface,  it's boring and time consuming to change all the code and recompile. 
our quick and dirty solution was to change the value of DefaultInterfaceName in kubelet/dockershim/network/network.go to 'eth1'.  it would be better if DefaultInterfaceName is configurable so that we don't need to touch any line of core kubelet code.

@kubernetes/sig-node-feature-requests

/sig node

/kind feature

**Comment by Pingan2017** [comment]
@derekwaynecarr @yujuhong take a look? if it is needed, I can work on it.

**Comment by Pingan2017** [comment]
Also /cc @tallclair

**Comment by D-PENG** [comment]
I usually configure the value of IP to 0.0.0.0 ：~

**Comment by curu** [comment]
@D-PENG.  Our bare-metal servers usually configured with too nic: eth0 as public and eth1 as private, service should normally listen only private ip for safe. It would be dangerous to listen on 0.0.0.0 if firewall was not properly configured.
