### ISSUE TITLE
RFC: all controllers are separate web services.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#703]
This is building on #635, which I agree with, but think does not go far enough.

###### Premise: There are going to be a lot of third-party controllers

We've talked about several types of controllers.  We all know about the replicationController.  A run-once controller has been suggested in #662.  A cron controller is mentioned in #170.  I can't find the issue, but I think there was a suggestion of a run-after feature.  My experience at my company is that people like to write their own workflow controllers, and no single one makes everyone happy. 

By way of analogy, Mesos lists 19 frameworks:
http://mesos.apache.org/documentation/latest/mesos-frameworks/

Kubernetes core developers won't be able to keep up with all of them and should not.

###### Premise: Controllers should be separate from the core of Kubernetes 

In  #635 Clayton explains some reasons for keeping parts of the API separate from each other:

"_to enforce boundaries, prevent coupling, allow higher security, allow api versioning at different rates, and allow experimentation for competing implementations_"

Given that there will be untrusted controllers, I propose that all controllers, including replication controller, should be treated as untrusted, to keep the playing field level.

I'm thinking of the division betwee kubernetes proper and controllers as based on the following principle:
_Kubernetes-proper supports objects whose creation require direct interaction with machines or network infrastructure, (and objects which are needed to support authentication, auditing and accounting)._  So, it would have:
       *  pods and volumes because these interact with machines.
       * services, because these interact with the network infrastructure.
       * podTemplates, because these are needed to narrow the scope of delegated authority. 

###### Proposal: all controllers run as separate web services from the core of kubernetes.

Given that controllers are not trusted by the core, they can't be part of the same process,.  So, they might as well be their own web services.

Sketch of how this might work:

Kubernetes core, and each controller runs as its own process, with its own deployment cycle and own ip+port.  For example:
   * Kubernetes proper runs at a known location, say `https://kubernetes.example.com/...`
   * The replicationController might run at say `https://kube-repl.example.com/...`.  
   * A user written controller might run at `https://my-kron.example.com/...`

All use of controllers requires delegation.  A user who wants to create a cron job that is managed by the aforementioned cron controller would do:
   1. Create a pod template using `PUT https://kubernetes.example.com/podTemplate`
   1. Create a cron-spec using `PUT https://my-kron.example.com/cronSpec`
   1. Creation of the cron-spec would trigger an Oauth flow where the user authorized `https://my-kron.example.com` to create pods using that podTemplate at  `https://kubernetes.example.com/...`.
   1. Periodically, `https://my-kron.example.com` runs a cron job using a token it got from the Oauth flow to start and monitor completion of a pod.

If a particular installation wants to provide a single endpoint then they can run a reverse proxy that maps each controller to a controller pseudo-resource path.  Extending the above example, the proxy might map:
      *  `https://kube-api.example.com/` to `https://kubernetes.example.com/...`
      *  `GET https://kube-api.example.com/controllers` would return static content with a list of supported controllers.
      *  `https://kube-api.example.com/controllers/replication/...` to `https://kube-repl.example.com/`
      *  `https://kube-api.example.com/controllers/cron/...` to  `https://my-kron.example.com/...`

The kubernetes project would control allocation of names under the `controllers/` path.

I haven't show this above, but each web service can have its own version identifier in its url.  The reverse proxy may provide its own version identifier which identifies the version of the collection of APIs as a whole, and needs not bear any relation to the versions of the individual web services.  It is distinguished by not having the same hostname as any individual service. 

The kubernetes core and various replication controllers could share the same APIserver via use of an APIserver library, as suggested in #700.

Certain controllers, such as replicationController would be made a standard part of the kubernetes-in-the-large API by virtue of being started by kube-up.sh and being distributed as part of the kubernetes source.  But all controllers would, by principle of least privilege, run separately from the core apiserver.

**Comment by smarterclayton** [comment]
Do we need this issue still?  Most things are controller loops, and almost all run in pods.  We still need to make it easy to script a custom controller

**Comment by thockin** [comment]
I took this to mean that we further break down the monolithic controller
manager.  Did I misinterpret?

**Comment by smarterclayton** [comment]
Is the monolithic one a problem?  There's a reductionist quality to that
that I don't think is practical.  My read was originally controllers meant
"distinct components", and it doesn't seem that we need one process for
each API resource or one process for each controller.  We should be *able*
to split them, but we don't *have* to.

On Sep 12, 2015, at 3:09 AM, Tim Hockin <notifications@github.com> wrote:

I took this to mean that we further break down the monolithic controller
manager. Did I misinterpret?

On Fri, Sep 11, 2015 at 5:09 PM, Clayton Coleman <notifications@github.com>
wrote:

> Do we need this issue still? Most things are controller loops, and almost
> all run in pods. We still need to make it easy to script a custom
controller
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/703#issuecomment-139690682>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/703#issuecomment-139737696>
.

**Comment by thockin** [comment]
I'm fine to close this

**Comment by erictune** [comment]
I don't think we need to go this far anymore.  Closing
