### ISSUE TITLE
CSI fsgroup does not work

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#70303]
**What happened**:
When trying to add fsgroup tests to the CSI drivers, the [test is failing](https://github.com/kubernetes/kubernetes/pull/68025#issuecomment-433536769)

**What you expected to happen**:
fsgroup should be set for supported drivers

@kubernetes/sig-storage-bugs 

/kind bug

**Comment by gnufied** [comment]
I do not think this is a valid bug. I ran same e2e test in linked PR on GCE and it works:

```
t 30 16:08:50.970: INFO: stdout: "Hello from com.google.csi.gcepd from namespace e2e-tests-csi-volumes-vbtkk\n"
STEP: Checking fsGroup is correct.
Oct 30 16:08:50.970: INFO: Running '/home/shared/go_projects/bin/kubectl --server=https://104.197.9.250 --kubeconfig=/home/hemant/.kube/config exec csi-client --namespace=e2e-tests-csi-volumes-vbtkk -- ls -ld /opt/0'
Oct 30 16:08:51.522: INFO: stderr: ""
Oct 30 16:08:51.522: INFO: stdout: "drwxrwsr-x    3 root     1234          4096 Oct 30 20:08 /opt/0\n"
STEP: cleaning the environment after csi
```

As you can see the fsGroup is correctly setup. So fsGroup at least works for CSI. May be something else happened in e2e.

**Comment by msau42** [comment]
Looks like a false alarm. Thanks for verifying!
/close
