### ISSUE TITLE
Kubelet service unable to start

### ISSUE THREAD

**Issue by codeasashu** [kubernetes/kubernetes#70300]
I am trying to get kubernetes up and running. I've installed kubernetes and its ran command `kubeadm init` which failed due to `kubelet` not being able to start up.

Used `journalctl -u kubelet.service` which output a massive log, ending up with

```
Oct 27 01:10:25 server kubelet[7435]:       --volume-stats-agg-period duration                                                                          Specifies interval for kubelet to calculate and cache the>
Oct 27 01:10:25 server kubelet[7435]: F1027 01:10:25.247033    7435 server.go:155] unknown command: /etc/kubernetes/kubelet.kubeconfig
Oct 27 01:10:25 server systemd[1]: kubelet.service: Service RestartSec=100ms expired, scheduling restart.
Oct 27 01:10:25 server systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 5.
Oct 27 01:10:25 server systemd[1]: Stopped Kubernetes Kubelet Server.
Oct 27 01:10:25 server systemd[1]: kubelet.service: Start request repeated too quickly.
Oct 27 01:10:25 server systemd[1]: kubelet.service: Failed with result 'exit-code'.
Oct 27 01:10:25 server systemd[1]: Failed to start Kubernetes Kubelet Server.
```

here is contents of `/etc/kubernetes` dir:
```
drwx------  2 root root 4.0K Oct 27 01:11 manifests
drwxr-xr-x  3 root root 4.0K Oct 27 01:11 pki
-rw-------  1 root root 5.4K Oct 27 01:11 admin.conf
-rw-r--r--  1 root root  773 Oct 27 00:33 apiserver
-rw-r--r--  1 root root  655 Oct 27 00:33 config
-rw-r--r--  1 root root  189 Oct 27 00:33 controller-manager
-rw-------  1 root root 5.4K Oct 27 01:11 controller-manager.conf
-rw-r--r--  1 root root  547 Oct 27 00:33 kubelet
-rw-------  1 root root 5.4K Oct 27 01:11 kubelet.conf
-rw-r--r--  1 root root  188 Oct 27 00:33 kubelet.kubeconfig
-rw-r--r--  1 root root  103 Oct 27 00:33 proxy
-rw-r--r--  1 root root  111 Oct 27 00:33 scheduler
-rw-------  1 root root 5.4K Oct 27 01:11 scheduler.conf
```

so `kubelet.kubeconfig` exists

I've installed kubernetes via https://aur.archlinux.org/kubernetes.git
and used makepkg -si to build.

**What you expected to happen**:
`kubelet` to run

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Arch Linux
- Kernel (e.g. `uname -a`): `Linux server 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux`
- Install tools: makepkg 5.1.1
- Others: Go version: go version go1.10.3 linux/amd64

/sig cli

/kind bug

**Comment by D-PENG** [comment]
Can you post the contents of kubelet.service.

**Comment by D-PENG** [comment]
Swap closed no

**Comment by codeasashu** [comment]
yes swap is off. Unfortunately, I can not post the contents as I have uninstalled and reinstalled using http://blog.programmableproduction.com/2018/03/08/Archlinux-Setup-Minikube-using-KVM/  and it worked.

The only difference I feel that worked for me is the installation of `docker-machine` and `docker-machine-driver-kvm` and the use of `kvm2` as the driver instead of virtualbox, which I was using before. 

Using `kvm2` as driver and reinstalling minikube solve the issue for me
