### ISSUE TITLE
kube-proxy cannot use ipvs mode on Linux 4.19

### ISSUE THREAD

**Issue by ijl** [kubernetes/kubernetes#70304]
kube-proxy cannot use ipvs mode on Linux 4.19 due to a check for the `nf_conntrack_ipv4` module, which was changed to `nf_conntrack` (https://github.com/torvalds/linux/commit/a0ae2562c6c4b2721d9fddba63b7286c13517d9f).

`RequiredIPVSKernelModulesAvailableCheck.Check()` uses `ipvsModules` to check for `nf_conntrack_ipv4`:

https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/util/ipvs/kernelcheck_linux.go#L78-L91

https://github.com/kubernetes/kubernetes/blob/6a8a8597f5bf4de29b7b88384529188df0b71337/pkg/util/ipvs/ipvs.go#L70-L77

It should instead accept `nf_conntrack` on Linux 4.19 or above.

**What happened**:
kube-proxy fell back from ipvs mode to iptables mode.
```
I1026 20:50:47.185405       1 feature_gate.go:226] feature gates: &{{} map[]}
W1026 20:50:47.323161       1 proxier.go:397] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
E1026 20:50:47.326512       1 server_others.go:304] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [nf_conntrack_ipv4]
I1026 20:50:47.328336       1 server_others.go:140] Using iptables Proxier.
```

**What you expected to happen**:
kube-proxy using ipvs.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a cluster on an image using Linux 4.19 or above with kube-proxy using ipvs mode (see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#run-kube-proxy-in-ipvs-mode).

**Environment**:
- Kubernetes version (use `kubectl version`): All
- Kernel (e.g. `uname -a`): 4.19

/kind bug

**Comment by m1093782566** [comment]
Okay, so should check {nf_conntrack_ipv4 | nf_conntrack} and expect load at least one module?

**Comment by islinwb** [comment]
@m1093782566 I think so

**Comment by m1093782566** [comment]
Please just go ahead :)
