### ISSUE TITLE
 --cluster-dns do check invalid network

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubernetes#70321]
I use Kubernetes v1.10.5, when i do below config:
```
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.53.0.10 --cluster-domain=cluster.local"
```
The kube-dns auto change to
```
kube-system    kube-dns                          ClusterIP   10.48.0.10
```
While i still use 10.53.0.* to config the clusterIP for my service.

Obviously, it can not intercommunicate.

The kube-dns can auto change to valid network is a great feature, but it do not make any warning which make me spend too much time debug why my service do not work.

Maybe check and add a waning here is better.

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
/kind feature

This is not a feature really. It is install optimization, but in the absence of such a label, I need to use "feature" here.

/sig scheduling

**Comment by D-PENG** [comment]
To modify the DNS address, you must delete the service of the default NAMESPACE kubernetes.

Component
> ```
> kube-apiserver、kube-controller-manager [flags]
> --service-cluster-ip-range=x.x.x.x/16
> 
> kubelet [flags]
> --cluster-dns=x.x.x.x
> 
> kube-proxy [flags]
> --cluster-cidr=x.x.x.x/16
> ```

**Comment by thockin** [comment]
Both of those are "valid" - are you saying that something is automatically changing the number that you put in, or that you didn't put it into the right place?

**Comment by daixiang0** [comment]
If praise a error when/before init, i think it is wonderful since invalid network address is hard to debug.

**Comment by daixiang0** [comment]
@thockin there is some misunderstand among us about valid CIDR address, refer to https://stackoverflow.com/questions/50084229/bash-check-if-cidr-address-is-valid

**Comment by daixiang0** [comment]
> Both of those are "valid" - are you saying that something is automatically changing the number that you put in, or that you didn't put it into the right place?

yes, i specify dns address and then specify other settings based on it, but i do not know the auto change about it before debug.

**Comment by daixiang0** [comment]
@thockin another question, which rule does it based on to do auto change?
