### ISSUE TITLE
Kubernetes automated rollbacks

### ISSUE THREAD

**Issue by prudhvigodithi** [kubernetes/kubernetes#70330]
Hey so automated rollbacks through kubernetes is done currently with only "undo" command with kubectl.

Is there is way kubernetes identifies the failed deployment and rollbacks automatically to previous running deployment by itself rather than passing the command kubectl rollout undo deploy/

Also with the command "kubectl patch deployment/nginx-deployment -p '{"spec":{"progressDeadlineSeconds":100}}" kubernetes does not by default rolls back to previous success deployment after the new deployment fails and completes the progressDeadlineSeconds to 100s

can we make make kubernetes know to rollback by itself depending upon progressDeadlineSeconds ?

I have tried " kubectl patch deployment/nginx-deployment -p '{"spec":{"spec.autoRollback":true}}'" which dint seem to work

Please provide me with solution if there is a way kubernetes can automatically rollback to previous successful deployment by itself.
Thank you

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6

- Cloud provider or hardware configuration: om prem
- OS (e.g. from /etc/os-release):

NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
- Kernel (e.g. `uname -a`): x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by prudhvigodithi** [comment]
Hey, is this you are mentioning https://github.com/kubernetes/community/tree/master/sig-apps?

**Comment by tossmilestone** [comment]
@prudhvigodithi I just labeled your issue with a correct sig, to make it clearer to be noticed.

**Comment by prudhvigodithi** [comment]
cool thanks, was juts wondering, if kubernetes could identify the failed deployments and automatically rollback to previous running deployments without undo api.

**Comment by tossmilestone** [comment]
@prudhvigodithi So it's a bug or feature request?

**Comment by prudhvigodithi** [comment]
Hey I have seen few articles related to k8s in regards to automated rollbacks, but the rollback is only possible with api using "kubectl rollout undo deploy/<name>", just want to know if kubernetes have any heath check or any other related checks to identify the failed deployment and rollback by itself.
its somewhat closely related to feature request.

**Comment by tossmilestone** [comment]
@prudhvigodithi Emm... I think it should be a feature request.
/kind feature
