### ISSUE TITLE
Kubeadm fails to add all volume mounts intermittently

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/kubernetes#70335]
**What happened**:
We have an autoscaling group of K8S masters which when coming up use kubeadm init to initialize.  The kube-apiserver.yaml manifest intermittently (but quite often) comes up with all the correct volumes defined, but some mounts missing.  Hand editing the mounts back in fixes the issue.

**What you expected to happen**:

All volumes defined _and_ mounted.

**Environment**:

K8S 1.11.3 on AWS, running Ubuntu 18.04 LTS, kernel 4.15.3.

/kind bug

**Comment by neolit123** [comment]
/close

@sgmiller 
please file the same issue in the kubernetes/kubeadm repo, so that we can keep track.
thanks.
