### ISSUE TITLE
PersistentVolume uses Docker volumes instead of mounted local host path

### ISSUE THREAD

**Issue by crunchtime-ali** [kubernetes/kubernetes#70339]
I want to (temporarily) use local host bound directories to persist application state of SonarQube. Below I describe how I achieved this in a self-hosted Kubernetes (1.11.3) cluster.

The problem I encounter is that despite everything working Kubernetes does not use the host path to persist the data (`/opt/sonarqube/postgresql`). Upon `docker inspect` of the SonarQube containers it uses the binds below.

**How can I use the host mounted path for the mounts?**

            "Binds": [
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/volume-subpaths/sonarqube-pv-postgresql/sonarqube/0:/opt/sonarqube/conf",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/volumes/kubernetes.io~configmap/startup:/tmp-script/:ro",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/volume-subpaths/sonarqube-pv-postgresql/sonarqube/2:/opt/sonarqube/data",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/volume-subpaths/sonarqube-pv-postgresql/sonarqube/3:/opt/sonarqube/extensions",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/volumes/kubernetes.io~secret/default-token-zrjdj:/var/run/secrets/kubernetes.io/serviceaccount:ro",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/etc-hosts:/etc/hosts",
                "/var/lib/kubelet/pods/49666f05-dad0-11e8-95cd-666c474c0e54/containers/sonarqube/95053a5c:/dev/termination-log"
            ]

**Here is what I did to setup the application**

I created a `StorageClass` to create PVs that mount local paths:

    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: local-storage-nowait
    provisioner: kubernetes.io/no-provisioner

Then I created two PVs to be used with the [SonarQube helm chart][1] like this:

    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: sonarqube-pv-postgresql
      labels:
        type: local
    spec:
      capacity:
        storage: 20Gi
      accessModes:
      - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: local-storage
      hostPath:
        path: /opt/sonarqube/postgresql
        type: DirectoryOrCreate
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - myhost

I launched the SonarQube helm chart with this additional config to use the PVs I just created

    image:
      tag: 7.1
    
    persistence:
      enabled: true
      storageClass: local-storage
      accessMode: ReadWriteOnce
      size: 10Gi
    
    postgresql:
      persistence:
        enabled: true
        storageClass: local-storage
        accessMode: ReadWriteOnce
        size: 10Gi

  [1]: https://github.com/helm/charts/tree/master/stable/sonarqube

**Comment by abretaud** [comment]
Hi, same problem for me, any news?

**Comment by mboudet** [comment]
/remove-lifecycle stale

Same issue for me, the data is not persisted on the host.
