### ISSUE TITLE
[API-Server] HTTP Compression - Brottli + ZSTD

### ISSUE THREAD

**Issue by nrshrivatsan** [kubernetes/kubernetes#70338]
**HTTP : Request + Response : Enable Brottli/ZSTD**:

- `kubectl` list Pods/Secrets seem to take a little time
- [`Brottli`](https://github.com/google/brotli/tree/master/go) & [`ZSTD`](https://godoc.org/github.com/DataDog/zstd) for Golang is available
- Impact of enabling compression would be magnificent for Site-Operations / Bot-Operations

**Control-Plane Latencies**:
- When performing routine health-checks on K8s workloads; API server is my source of truth
- In developing economies - Data is expensive; This feature would drastically enhance their experience of automation/manual API-server interactions

/kind feature

**Comment by nrshrivatsan** [comment]
@freeformz @brosner

**Comment by liggitt** [comment]
closing this, as there's actually a long-lived option to enable gzip compresson on get/list requests

https://github.com/kubernetes/kubernetes/pull/51508 was opened to promote it, but got hung up on [some issues around compression interacting with streaming subresources](https://github.com/kubernetes/kubernetes/pull/51508#issuecomment-388946179)

if you wanted to help move that forward, that would be great

/close
