### ISSUE TITLE
Link to docs from website

### ISSUE THREAD

**Issue by benmccann** [kubernetes/kubernetes#7034]
I don't see a link to [the documentation](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs) anywhere on [kubernetes.io](http://kubernetes.io)

**Comment by brendandburns** [comment]
Accepting this to me, I'll work w/ the docs folks to get it added.

Thanks for the suggestion!
--brendan

**Comment by bgrant0607** [comment]
Done
