### ISSUE TITLE
 Unauthorized issues in building kubernetes clusters using kubeadm

### ISSUE THREAD

**Issue by EricBatty** [kubernetes/kubernetes#70356]
Please see the following console output
[root@node2 ~]# kubeadm join 192.168.0.112:6443 --token oq9l8k.dxw47f2f1w2lrkix  --discovery-token-ca-cert-hash sha256:b33963fc744e484df6198a88fa5c4a0ecc370ecb3aa07acc31aa43030a5b2465 --ignore-preflight-errors=Swap
[preflight] running pre-flight checks
	[WARNING RequiredIPVSKernelModulesAvailable]: the IPVS proxier will not be used, because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh] or no builtin kernel ipvs support: map[ip_vs_rr:{} ip_vs_wrr:{} ip_vs_sh:{} nf_conntrack_ipv4:{} ip_vs:{}]
you can solve this problem with following methods:
 1. Run 'modprobe -- ' to load missing kernel modules;
2. Provide the missing builtin kernel ipvs support

	[WARNING Swap]: running with swap on is not supported. Please disable swap
[discovery] Trying to connect to API Server "192.168.0.112:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.0.112:6443"
[discovery] Requesting info from "https://192.168.0.112:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.0.112:6443"
[discovery] Successfully established connection with API Server "192.168.0.112:6443"
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.12" ConfigMap in the kube-system namespace
Unauthorized

**Comment by neolit123** [comment]
closing as duplicate of:
https://github.com/kubernetes/kubeadm/issues/1192
