### ISSUE TITLE
How can I re-schedule a running pod to another worker node

### ISSUE THREAD

**Issue by daemon027** [kubernetes/kubernetes#70363]
Hi, is there a way I can re-schedule a running pod to another worker node?
Currently I get "Conflict" when I try to binding a running pod to another node:

```
$ curl -k -H "Content-Type:application/json" -X POST -d '{"apiVersion":"v1", "kind": "Binding", "metadata": {"name": "hello-test"}, "target": {"apiVersion": "v1", "kind": "Node", "name": "k8s-node-02"}}'  --cert apiserver-kubelet-client.crt --key apiserver-kubelet-client.key https://k8s-101:6443/api/v1/namespaces/test-branch/pods/hello-test/binding

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Operation cannot be fulfilled on pods/binding \"hello-test\": pod hello-test is already assigned to node \"k8s-node-01\"",
  "reason": "Conflict",
  "details": {
    "name": "hello-test",
    "kind": "pods/binding"
  },
  "code": 409
} 
```
re-create the pod during the re-schedule process is accepted, how can I work around it? Thanks.

/triage support

**Comment by daemon027** [comment]
@kubernetes/sig-scheduling-bugs
/sig scheduling
/sig scalability

**Comment by bsalamat** [comment]
There is no way you can move a running pod from one node to another on the fly. Kubernetes does not support live migration of pods from one host to another.

**Comment by daemon027** [comment]
It's reasonable that "we can't move a running pod from one node to another on the fly".
The "re-schedule" I mean is some situation likes when a node is down, we need to migrate the pods on the "dead node" to another "live node". 
When I need to re-schedule a pod from node A to node B, I call a API, then the pod on node A is terminated and a new pod is created on node B, is there a way to do that?

**Comment by ravisantoshgudimetla** [comment]
@daemon027 - Can you please elaborate on what you mean by "dead node" here? Usually, the pods on node which is `NotReady` are evicted after `--pod-eviction-timeout` on node. Also, look at the issue https://github.com/kubernetes/kubernetes/issues/55713, if you have volumes attached to pods.

On a high-level, if you are interesting in writing code to evict the pod, you can always use kube eviction api(https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/)

**Comment by tossmilestone** [comment]
@daemon027 I think you could first `cordon` the node A, then delete the pod to trigger `re-schedule` of the pod. Hope this can help you.

**Comment by gacopl** [comment]
why not use labels and node selectors or affinity ?

**Comment by amelbakry** [comment]
The same question came to my mind. I have deployments with sometimes more than 200 pods, and there is no way to equally distribute the pods to the nodes. but sometimes I see pod with 60 pods and pod with 2 pods, so I need to distribute pods manually

**Comment by gacopl** [comment]
my experience is that when limits and requests are set properly the scheduler schedules evenly thing is it does that only during scheduling so sometimes manual action needs to be done to delete podsc so they get rescheduled on new nodes etc

**Comment by amelbakry** [comment]
I reached a situation where 62% of the pods where running only in 2 nodes, and all remaining pods were running on 9 nodes

**Comment by aveshagarwal** [comment]
> The same question came to my mind. I have deployments with sometimes more than 200 pods, and there is no way to equally distribute the pods to the nodes. but sometimes I see node with 60 pods and node with 2 pods, so I need to distribute pods manually

You could try https://github.com/kubernetes-incubator/descheduler in your scenario.

**Comment by aveshagarwal** [comment]
> my experience is that when limits and requests are set properly the scheduler schedules evenly thing is it does that only during scheduling

Right.

> so sometimes manual action needs to be done to delete podsc so they get rescheduled on new nodes etc

Instead of manual, you could try https://github.com/kubernetes-incubator/descheduler too.

**Comment by amelbakry** [comment]
Thanks a lot, I will try it
