### ISSUE TITLE
Failing kubeadm test: kubeadm-gce-stable-on-master/4929

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70375]
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-stable-on-master

**Which test(s) are failing**:
[`Up`](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-stable-on-master/4929)

**Since when has it been failing**:
October 27th, 2018

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-stable-on-master

**Reason for failure**:
It seems that #69486 has caused the failure: https://github.com/kubernetes/kubernetes/compare/b7b0aae43...481fa1977?

**Anything else we need to know**:

/kind failing-test

**Comment by neolit123** [comment]
possible fix: https://github.com/kubernetes/kubernetes-anywhere/pull/572

**Comment by jberkus** [comment]
Adding sig:

/sig cluster-lifecycle

**Comment by jberkus** [comment]
First test since the merge passed.  If we get a few more greens, we can close.  Thanks for fast work!

**Comment by mariantalla** [comment]
Thanks @neolit123 !

/close
