### ISSUE TITLE
Incorrect error reported when VM.Reconfigure fails in vSphere cloud provider

### ISSUE THREAD

**Issue by mansi-a** [kubernetes/kubernetes#70391]
**What happened**:
VM.Reconfigure failed when the VC user has insufficient privileges. Instead of an error related to authorization, a null pointer exception is thrown.

` 1 goroutinemap.go:150] Operation for \"provision-us1-dev-web-1/pvc[6271aab0-bd22-11e8-b4b3-005056bb78a9]\" failed. No retries permitted until 2018-09-20 23:05:45.833842201 +0000 UTC m=+1187.474157154 (durationBeforeRetry 2m2s). Error: \"recovered from panic \\\"runtime error: invalid memory address or nil pointer dereference\\\". (err=\u003cnil\u003e) Call stack:\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:154\\n/usr/local/go/src/runtime/asm_amd64.s:573\\n/usr/local/go/src/runtime/panic.go:502\\n/usr/local/go/src/runtime/panic.go:63\\n/usr/local/go/src/runtime/signal_unix.go:388\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/vmware/govmomi/object/task.go:52\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/vmware/govmomi/object/task.go:47\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/diskmanagers/vmdm.go:130\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/diskmanagers/virtualdisk.go:74\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:1192\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:1192\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:1210\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go:143\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go:359\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1455\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1343\\n/workspace/anago-v1.11.1-beta.0.115+b1b29978270dc2/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:115\\n/usr/local/go/src/runtime/asm_amd64.s:2361\\n\"\n","stream":"stderr","time":"2018-09-20T23:03:43.833989061Z"}`

**What you expected to happen**:
Expected to see an authorization related error.

**How to reproduce it (as minimally and precisely as possible)**:
Use a VC user which does insufficient privileges to create a persistent volume claim and see the error from controller-manager logs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release):
NAME="VMware Photon OS"
VERSION="2.0"
ID=photon
VERSION_ID=2.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
- Kernel (e.g. `uname -a`):
Linux 9153a58ea99d42d1b2ab41d62af932ca 4.9.124-1.ph2-esx #1-photon SMP Mon Aug 27 19:00:16 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz GenuineIntel GNU/Linux
- Install tools:
- Others:

/kind bug

**Comment by mansi-a** [comment]
@kubernetes/sig-cloud-provider-bugs

**Comment by mansi-a** [comment]
After the call to VM.Reconfigure, returned task is used without making a null check and that is where is NPE is coming from.
https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/cloudprovider/providers/vsphere/vclib/diskmanagers/vmdm.go#L130

https://github.com/kubernetes/kubernetes/blob/release-1.11/vendor/github.com/vmware/govmomi/object/virtual_machine.go#L195
This returns nil here when rpc fails.

**Comment by wgliang** [comment]
ref:https://github.com/kubernetes/kubernetes/pull/66304
This issue had been fixed.

**Comment by frapposelli** [comment]
@mansi-a looks like this has been fixed, please reopen if issue is still happening on latest version.

/close
