### ISSUE TITLE
[Kubernetes 1.9.2] Node becomes NotReady because docker ps hangs

### ISSUE THREAD

**Issue by xfye** [kubernetes/kubernetes#70417]
**What happened**:

It causes `docker ps` hangs and k8s node becomes NotReady.

I have logged an issue here as well:
https://github.com/containerd/containerd/issues/2750

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

It sometimes happens. Can not find the step to reproduce it.

**Anything else we need to know?**:

From `docker-containerd`'s dump, it shows that the goroutine hangs in reading oom eventfd.

```
goroutine 12 [syscall, 4392 minutes]:
syscall.Syscall(0x0, 0x49, 0xc420048818, 0x8, 0x410aff, 0xcafc08, 0xc95140)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x49, 0xc420048818, 0x8, 0x8, 0xc420198b14, 0xc95140, 0xc420198b10)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x49, 0xc420048818, 0x8, 0x8, 0x821960, 0x82cea0, 0x49d8e201)
        /usr/local/go/src/syscall/syscall_unix.go:161 +0x49
github.com/docker/containerd/runtime.(*oom).Flush(0xc420389cb0)
        /tmp/tmp.KIaRYYvBPV/src/github.com/docker/containerd/runtime/container.go:702 +0x54
github.com/docker/containerd/supervisor.(*Monitor).processEvent(0xc420198b10, 0x49, 0x1)
        /tmp/tmp.KIaRYYvBPV/src/github.com/docker/containerd/supervisor/monitor_linux.go:114 +0x493
github.com/docker/containerd/supervisor.(*Monitor).start(0xc420198b10)
        /tmp/tmp.KIaRYYvBPV/src/github.com/docker/containerd/supervisor/monitor_linux.go:144 +0xf4
created by github.com/docker/containerd/supervisor.NewMonitor
        /tmp/tmp.KIaRYYvBPV/src/github.com/docker/containerd/supervisor/monitor_linux.go:24 +0x175
```

**Environment**:

- OS: Ubuntu 16.04.3 LTS
- Linux Kernel: 4.4.0-104-generic
- Kubernetes: 1.9.2
- docker: 17.03.2-ce
- containerd: 0.2.3 commit 4ab9917febca54791c5f071a9d1f404867857fcc

/kind bug

**Comment by Nebulazhang** [comment]
I met this problem sometimes. And only to `restart dcokerd` can solve it.

**Comment by Pingan2017** [comment]
if `docker ps ` hang, the healthcheck of PLEG will fail. the fail of hc will cause the node NotReady, it is normal

**Comment by xfye** [comment]
> I met this problem sometimes. And only to `restart dcokerd` can solve it.

Yes, neet to restart dockerd.

**Comment by xfye** [comment]
From Kuberntes's release notes, thre latest verified docker version is 17.03.x. But we dot not want to upgrade our Kubernetes components so far.
Can someone resolved this issue before ?

**Comment by WxFang** [comment]
> I met this problem sometimes. And only to `restart dcokerd` can solve it.
@Nebulazhang 
But if we don't do anything, the node will stay NotReady forever right?
Do you have any idea about monitoring this from outside the cluster?
