### ISSUE TITLE
fixed path for safe_format_and_mount in kubelet break coreos on gce

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#7042]
Hi,

Kubelet on gce is looking for safe_format_and_mount in /usr/share/google but in coreos the path is /usr/share/oem/google-startup-scripts/ on RO partition.
I must compile kubelet to reflect the new path, instead of setting a simple parameter.

Best regards

**Comment by brosner** [comment]
I would love to see this get fixed and willing to help. Given that #8530 was pushed to after 1.0, I would like to avoid the custom kubelet binary for all my deployments.

I could use some suggestions on how to best fix this? Would looking for `safe_format_and_mount` in `/usr/share/oem/google-startup-scripts` before `/usr/share/google` be a reasonable fix?

**Comment by erimatnor** [comment]
I am also seeing this problem on CoreOS/AWS. A kubelet command-line parameter for setting script path  would be nice.

**Comment by jcderr** [comment]
+1

After a lengthy eval period, I think this is really the last impediment to us rolling out kubernetes across the board in our shop.

**Comment by berset** [comment]
Yes, this is really a blocker for a lot of use cases with CoreOS on AWS :(

**Comment by thesamet** [comment]
+1, ended up writing a CloudFormation setup that users my own custom build that cherry-picks #8530.

**Comment by dhawal55** [comment]
+1

**Comment by liquid-sky** [comment]
+1

**Comment by justinsb** [comment]
I believe we have now embedded equivalent code to safe_format_and_mount, so the script is no longer required (by kubelet, though e.g. kube-up uses it).  Closing.
