### ISSUE TITLE
kernel: unregister_netdevice: waiting for eth0 to become free. Usage count = 1

### ISSUE THREAD

**Issue by sumanmanuel** [kubernetes/kubernetes#70427]
A query related to similar errors.

I understand that there are multiple discussions related to the same error like:
https://github.com/kubernetes/kubernetes/issues/64743#issuecomment-404160205
referring to https://github.com/torvalds/linux/commit/4ee806d51176ba7b8ff1efd81f271d7252e03a1d

But my doubt is couldnt this trigger a similar flow making kernel to report it:
https://github.com/kubernetes/kubernetes/blob/650357ae53d299ef007a0483349e51c5327abc04/pkg/kubelet/dockershim/docker_sandbox.go#L374

especially if for example it follows the log flow
`Calico CNI deleting device in netns /proc/3025/ns/net
...
docker_sandbox.go:340] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "p1-6558811f44-kll87_n01": Unexpected command output nsenter: cannot open /proc/43796/ns/net: No such file or directory
`

Please correct me if I am wrong

/kind bug

**Comment by anfernee** [comment]
@sumanmanuel thanks for reporting issue. My advice is: can you post this into #64743 and close this one? Especially both issues have exactly the same title. #64743 draws a lot of attentions already from many people experienced similar issue, so I think you question has higher chance to be answered there.

**Comment by sumanmanuel** [comment]
was just curious if anyone thinks this could trigger this scenario or is completely impossible?
I think this situation can happen and can be avoided if this case is handled or am i wrong?

**Comment by kousiknandy** [comment]
/remove-lifecycle stale

Seen with `Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` and K8s `v1.11.5`.

**Comment by freehan** [comment]
ping?

**Comment by abh** [comment]
RedHat thinks they figured out either this or a related issue: https://access.redhat.com/solutions/3659011
https://www.spinics.net/lists/netdev/msg556882.html
