### ISSUE TITLE
change service port with aws nlb ，old security group rules not deleted

### ISSUE THREAD

**Issue by April-Q** [kubernetes/kubernetes#70421]
**What happened**:
I deployed a cluster on aws and created a loadbalance type service. When I modify the port of this service, the value of nodeport, loadbalance on aws will only add a new port in the security group, and will not delete the port that was originally opened.

**What you expected to happen**:
Delete the original opened port, only keep the new port

**How to reproduce it (as minimally and precisely as possible)**:
create a service like this：
svc.yaml
kind: Service
apiVersion: v1
metadata:
  name: my-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: nginx
  ports:
  - name: internet-nlb
    nodePort: 30080
    port: 30080
    protocol: TCP
    targetPort: 80
  type: LoadBalancer

then securiy group will add two rules:

Custom TCP Rule | TCP | 30080 | 0.0.0.0/0 | kubernetes.io/rule...

Custom TCP Rule | TCP | 30080 | 172.31.0.0/16 | kubernetes.io/rule...

then I modify the service port,change nodeport to 30081,port to 30081

then securiy group will be
Custom TCP Rule | TCP | 30080 | 0.0.0.0/0 | kubernetes.io/rule...

Custom TCP Rule | TCP | 30080 | 172.31.0.0/16 | kubernetes.io/rule...

Custom TCP Rule | TCP | 30081 | 0.0.0.0/0 | kubernetes.io/rule...

Custom TCP Rule | TCP | 30081 | 172.31.0.0/16 | kubernetes.io/rule...

I think the rules contain 30080 should be removed,no server is open to 30080 now

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.11.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):
Linux enn-2-129 3.10.0-693.el7.x86_64
- Install tools:
install k8s cluster with binary and Configuration file 
- Others:

/kind bug

**Comment by April-Q** [comment]
I reviewed k8s code,in kubernetes/pkg/cloudprovider/providers/aws/aws_loadbalancer.go file, func (c *Cloud) updateInstanceSecurityGroupsForNLBTraffic,after I remove the code below 
// remove from portChanges ports that are already allowed
			if intersection := desiredSet.Intersection(existingSet); intersection.Len() > 0 {
				glog.Infof("sj debug intersection", intersection)
				for p := range intersection {
					delete(portChanges[actualGroupID], p)
				}
			}
the problem solved,maybe I misunderstand something?

**Comment by April-Q** [comment]
I reviewed k8s code,in kubernetes/pkg/cloudprovider/providers/aws/aws_loadbalancer.go file, func (c *Cloud) updateInstanceSecurityGroupsForNLBTraffic,after I remove the code below

`// remove from portChanges ports that are already allowed
if intersection := desiredSet.Intersection(existingSet); intersection.Len() > 0 {
for p := range intersection {
delete(portChanges[actualGroupID], p)
}
}`
the problem solved,maybe I misunderstand something?

**Comment by April-Q** [comment]
I reviewed k8s code,in kubernetes/pkg/cloudprovider/providers/aws/aws_loadbalancer.go file, func (c *Cloud) updateInstanceSecurityGroupsForNLBTraffic,after I remove the code below
`// remove from portChanges ports that are already allowed
			if intersection := desiredSet.Intersection(existingSet); intersection.Len() > 0 {
				for p := range intersection {
					delete(portChanges[actualGroupID], p)
				}
			}`
the problem solved ,maybe I misunderstand something?

**Comment by krish7919** [comment]
I recently moved to NLB (from ALB) and am running into this issue too.

**Comment by krish7919** [comment]
/sig aws

Would an MR help here?

**Comment by b1zzu** [comment]
Hi, can I take it?

**Comment by b1zzu** [comment]
Hi, it is possible to have free resources (ec2 instances) from amazon in order to reproduce, debug and testing this bug?

**Comment by vaibhavk** [comment]
Hi, can I work on it if it's not resolved yet?

**Comment by krish7919** [comment]
I think this is fixed in v1.14 and is cherry-picked in v1.11 onwards.
