### ISSUE TITLE
go get -u github.com/kubernetes/kubernetes/cmd/kubectl

### ISSUE THREAD

**Issue by gertcuykens** [kubernetes/kubernetes#70447]
Now that we are in the age of go modules I think it is't fair to make this work
```
go get -u github.com/kubernetes/kubernetes/cmd/kubectl
```
It does install but as soon as you run it you get
```
kubectl

kubectl flag redefined: log_dir
panic: kubectl flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000080180, 0x1c15080, 0xc00003a8b0, 0x1a0cad8, 0x7, 0x1a45267, 0x2f)
        /usr/local/go/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc000080180, 0xc00003a8b0, 0x1a0cad8, 0x7, 0x0, 0x0, 0x1a45267, 0x2f)
        /usr/local/go/src/flag/flag.go:708 +0x8a
flag.(*FlagSet).String(0xc000080180, 0x1a0cad8, 0x7, 0x0, 0x0, 0x1a45267, 0x2f, 0xc00003a8a0)
        /usr/local/go/src/flag/flag.go:721 +0x8b
flag.String(0x1a0cad8, 0x7, 0x0, 0x0, 0x1a45267, 0x2f, 0x17c7460)
        /usr/local/go/src/flag/flag.go:728 +0x69
```

/kind bug
/sig cli

**Comment by tanweernoor** [comment]
any fix for this error ?

**Comment by dims** [comment]
Please try now. with the move from glog to klog this problem got fixed

/close

**Comment by tanweernoor** [comment]
Hi there.. i am getting this error now
kubelet version
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x757bb80, 0x493c4f4, 0xf, 0x4d01320, 0x4abd600)
	/usr/lib64/go/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x757bb80, 0x493c4f4, 0xf, 0x4abd600)
	/usr/lib64/go/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0x493c4f4, 0xf, 0x4abd600)
	/usr/lib64/go/src/net/http/server.go:2380 +0x4b
k8s.io/kubernetes/vendor/golang.org/x/net/trace.init.0()
	/code/BUILD/el7/kubelet-1.11.3/src/k8s.io/kubernetes/vendor/golang.org/x/net/trace/trace.go:115 +0x42

**Comment by WanLinghao** [comment]
@tanweernoor  kubelet? or just a typo
