### ISSUE TITLE
Failing tests: vsphere cloud provider conformance tests

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70446]
**Which jobs are failing**:
[master-blocking/Conformance vSphere-cloud-provider](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20vSphere-cloud-provider)

**Which test(s) are failing**:
[On gubernator](https://gubernator.k8s.io/build/k8s-conformance-cloud-provider-vsphere/head/ci/latest/1540913495)

Test-specific links:
[[sig-api-machinery] ConfigMap should be consumable via environment variable [NodeConformance] [Conformance]](https://gubernator.k8s.io/build/k8s-conformance-cloud-provider-vsphere/head/ci/latest/1540913495#sig-api-machinery-configmap-should-be-consumable-via-environment-variable-nodeconformance-conformance)

[[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]](https://gubernator.k8s.io/build/k8s-conformance-cloud-provider-vsphere/head/ci/latest/1540913495#sig-apps-statefulset-k8sio-basic-statefulset-functionality-statefulsetbasic-should-perform-rolling-updates-and-roll-backs-of-template-modifications-conformance)

**Since when has it been failing**:
October 30th, 2018

**Anything else we need to know**:
This _may_ be related to [Issue #70445](https://github.com/kubernetes/kubernetes/issues/70445)

/kind failing-test

**Comment by mariantalla** [comment]
This test is now passing, will keep an eye on it for a couple more runs and then close out if it's consistently passing.

**Comment by mbohlool** [comment]
cc @roycaihw
