### ISSUE TITLE
All GKE upgrade tests failing since 10/29

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70445]
Starting last night (Pacific time), all GKE upgrade tests started failing.  Many of them were very flaky before that, but even the non-flaky ones have been consistently failing since 13:00 on Oct. 29th.  Since this does not line up with any particular commit (or infra commit), I strongly suspect that it's due to a change in GKE.

**Which jobs are failing**:

* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-master
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-parallel
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-new-downgrade-cluster
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-new-downgrade-cluster-parallel
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new-parallel

**Which test(s) are failing**:

Inconsistent, does not appear to be a particular test issue.  For gke-gci-master-gci-new-downgrade-cluster, for example, *all* of the tests are failing.

**Since when has it been failing**:

Oct. 29th, sometime after 13:00

/kind failing-test
/priority critical-urgent
/sig gcp

**Comment by AishSundar** [comment]
Here's are all the chnages in this timeframe https://github.com/kubernetes/kubernetes/compare/1f3ef2909...3293f02d0?

**Comment by aleksandra-malinowska** [comment]
We have a root cause and fix on GKE side. It may take a day for the dashboards to clear up though.

**Comment by seans3** [comment]
Any progress on this? I'm still seeing the following failure in the SIG CLI `skew-cluster-stable1-kubectl-latest-gke` test: 
```
W1101 23:52:36.444]  zone: u'us-central1-c'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that: component "kube-apiserver" from endpoint "gke-935eb573abb7cb6333da-408c" is unhealthy.
```
The first failure happened on 10/29 @13:24.

The SIG CLI testgrid is at: https://k8s-testgrid.appspot.com/sig-cli-master#skew-cluster-stable1-kubectl-latest-gke

**Comment by aleksandra-malinowska** [comment]
> The SIG CLI testgrid is at: https://k8s-testgrid.appspot.com/sig-cli-master#skew-cluster-stable1-kubectl-latest-gke

A day was probably too optimistic:( Started to get greener around 6:30 PM PDT yesterday.

**Comment by aleksandra-malinowska** [comment]
Testgrids were rearranged in the meantime, new link to one of the previously-failing jobs: https://k8s-testgrid.appspot.com/sig-release-1.11-all#gke-gci-1.10-gci-1.11-upgrade-master

Not exactly green, but running again. The original issue seems fixed. 

/assign @jberkus

**Comment by mariantalla** [comment]
"Master upgrade should maintain a functioning cluster" has had a successful run, will keep an eye on it and will look to close this issue when it consistently passes...

@aleksandra-malinowska - what do you look for to ensure that the original issue is fixed in test runs? (asking as some tests are failing, but very possibly due to other reasons).

**Comment by aleksandra-malinowska** [comment]
@mariantalla all tests were failing before because cluster failed to be created at 1.11 (in which case the scenarios wouldn't even run, i.e. it failed at setup), or upgraded/downgraded to this version. This is no longer the case for most jobs, and errors in the few remaining ones are different. But we can of course keep this open for fixing/deflaking remaining tests.

**Comment by jberkus** [comment]
I'd rather close it and open an new issue for deflaking, since this is not a blocking issue anymore.

/close
