### ISSUE TITLE
Plugin watcher panics when ophaned plugin socket exists in plugin discovery directory

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#70460]
The Kubelet panics in a loop when it tries to send a request on that channel. It should not panic.
```
panic: send on closed channel
Oct 30 22:54:13 e2e-test-dyzz-minion-group-6h4b kubelet[23947]: goroutine 1235 [running]:
Oct 30 22:54:13 e2e-test-dyzz-minion-group-6h4b kubelet[23947]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).traversePluginDir.func1.1(0xc00051d380, 0xc001ce1200, 0x36)
Oct 30 22:54:13 e2e-test-dyzz-minion-group-6h4b kubelet[23947]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:191 +0x68
Oct 30 22:54:13 e2e-test-dyzz-minion-group-6h4b kubelet[23947]: created by k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).traversePluginDir.func1
Oct 30 22:54:13 e2e-test-dyzz-minion-group-6h4b kubelet[23947]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:190 +0x1ad
```

**How to reproduce it (as minimally and precisely as possible)**:
- create socket that is closed: `sudo mkfifo /var/lib/kubelet/plugins/fake-reg.sock` (fifo is not exactly the same as a standard registration socket but for purpose of repro I think it hits the same codepath)
- Observe panic

**Anything else we need to know?**:
This happens during usage of Kubernetes when some device tries to do registration but crashes and fails to clean up its sockets.

/kind bug
/sig node
/cc @yujuhong

**Comment by vikaschoudhary16** [comment]
taking a look, thanks!

**Comment by RenaudWasTaken** [comment]
Hmm can you share more details on reproducing @davidz627 ? Is this in the 1.12 release?

I'm not able to reproduce this bug. Looking at the error message I'm also a bit surprised because that channel is stopped at only two moments:
- At Startup if we're not able to watch the plugin dir, in which case the Kubelet will fail to start
- At Stop time which doesn't seem to be your case

**Comment by figo** [comment]
@davidz627 i have the same question as Renaud, i try to reproduce this with the latest build (v1.13), 
with the same step as you listed, i got the log saying:
```
plugin_watcher.go:197] Ignoring file /var/lib/kubelet/plugins/fake-reg.sock with mode prw-r--r--
```
which is consistent with latest version of code.

could you share more detail about the build you are using, or other relevant configuration information.

**Comment by davidz627** [comment]
sorry I left some steps out of repro
```
sudo systemctl kubelet stop
sudo mkfifo /var/lib/kubelet/plugins/fake-reg.sock
sudo systemctl kubelet start
```

I did notice that I was running this in my e2e cluster which may have been old. I will try to repro again on a newer cluster.

**Comment by davidz627** [comment]
> @davidz627 i have the same question as Renaud, i try to reproduce this with the latest build (v1.13),
> with the same step as you listed, i got the log saying:
> 
> ```
> plugin_watcher.go:197] Ignoring file /var/lib/kubelet/plugins/fake-reg.sock with mode prw-r--r--
> ```
> which is consistent with latest version of code.
> 
> could you share more detail about the build you are using, or other relevant configuration information.

this message only shows up if the file is not a socket. Did you use `mkfifo`? Maybe we need some other method of creating a fake socket for repro if that does not work

**Comment by davidz627** [comment]
eh. Can't reproduce. Closing issue

**Comment by figo** [comment]
> > @davidz627 i have the same question as Renaud, i try to reproduce this with the latest build (v1.13),
> > with the same step as you listed, i got the log saying:
> > ```
> > plugin_watcher.go:197] Ignoring file /var/lib/kubelet/plugins/fake-reg.sock with mode prw-r--r--
> > ```
> > which is consistent with latest version of code.
> > could you share more detail about the build you are using, or other relevant configuration information.
> 
> this message only shows up if the file is not a socket. Did you use `mkfifo`? Maybe we need some other method of creating a fake socket for repro if that does not work

@davidz627 i understand the issue been closed, just reply to your question for completeness, i did run `mkfifo`,  the fact that a fifo file can trigger registration indicates it is running on older version of code.

with latest version of code (it checking `case mode&os.ModeSocket != 0`), the fifo file should be ignored as they are having different modes.
```
fifo file mode:  prw-r--r-- 
socket file mode: srwxr-xr-x
```
