### ISSUE TITLE
AGE invalid

### ISSUE THREAD

**Issue by NOWYOU** [kubernetes/kubernetes#70473]
when I create a new yaml  ,I check it  but found a error 

[k8s@k8s-master dns]$ kubectl get all -n kube-system
NAME                                        READY     STATUS    RESTARTS            AGE
pod/coredns-77c989547b-944tv                1/1       Running   0          <invalid>
pod/coredns-77c989547b-s9vxl                1/1       Running   0          <invalid>

Under AGE, the timestamp is not displayed correctly, but the invalid is displayed.

Does anyone know what is going on?

**Comment by neolit123** [comment]
please use stackoverflow or slack for user facing issues:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

the tracker here is for bugs and feature requests, thanks.
/close
