### ISSUE TITLE
Move Kubelet Plugin Registration Watcher to GA 

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#70484]
**What would you like to be added**:
This issue is to migrate the Kubelet Plugin Registration/Watcher from Beta -> GA.

**Why is this needed**:
This feature (PluginsRegistrationWatcher) has been a core functionality of other systems such as CSI for a couple of releases now.  Moving from Beta to GA will signal to adopters (such as CSI) that this feature is ready stable and ready for continuing adoption.

**Feature tracking:** https://github.com/kubernetes/enhancements/issues/595 

**Items needed**
- [x] Update feature gate comment to reflect GA 
    - https://github.com/kubernetes/kubernetes/blob/dc1307b82639780334af99936b2e0dbe24c9a552/pkg/features/kube_features.go#L330:2
- [x] Create `v1` package in `pkg/kubelet/apis/pluginregistration`
- [x] Update  imports to point to `v1`
- [x] Create PR - https://github.com/kubernetes/kubernetes/pull/70559
- [ ] Resolve pending issue - https://github.com/kubernetes/kubernetes/issues/69015
- [ ] Present PR to section owners (SIG Node) for review

Related [umbrella] issue - https://github.com/kubernetes/kubernetes/issues/65773

/kind feature

**Comment by nikopen** [comment]
/milestone v1.13 

@kacole2
