### ISSUE TITLE
Kubelet RPM upgrade overwrites /etc/sysconfig/kubelet 

### ISSUE THREAD

**Issue by mxey** [kubernetes/kubernetes#70489]
**What happened**:

When updating the kubelet RPM from 1.11.3-0.x86_64 to 1.11.4-0.x86_64, `/etc/sysconfig/kubelet` is overwritten with the package contents again. 

**What you expected to happen**:

`/etc/sysconfig/kubelet` should be left as-is because it is meant for the operator to override

**How to reproduce it (as minimally and precisely as possible)**:

Install Kubelet on CentOS:

```
$ docker run -it centos:7

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

yum install -y kubelet-1.11.3 

```

Modify `/etc/sysconfig/kubelet`:

```
echo "FOO=bar" >>  /etc/sysconfig/kubelet 

[root@7d83157dac5a /]# cat /etc/sysconfig/kubelet 
KUBELET_EXTRA_ARGS=
FOO=bar
```

Upgrade kubelet:

```
yum upgrade -y  kubelet-1.11.4 
```

Check `/etc/sysconfig/kubelet`:
```
[root@7d83157dac5a /]# cat /etc/sysconfig/kubelet 
KUBELET_EXTRA_ARGS=
```

**Anything else we need to know?**:

[Configuration files in RPM packages should be marked as %config(noreplace)](http://people.ds.cam.ac.uk/jw35/docs/rpm_config.html)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.4
- Cloud provider or hardware configuration: Docker
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux 7d83157dac5a 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: —
- Others:

/kind bug

**Comment by steven-sheehy** [comment]
I was about to open a ticket, but I think I'll pile onto this one. I have the exact same issue, but for /etc/default/kubelet on Debian based systems. According to the systemd drop-in:

> This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.

But I can't use it for overrides if it can get overwritten anytime the kubelet package is updated.

```shell
$ dpkg -L kubelet
/.
/etc
/etc/default
/etc/default/kubelet
/usr
/usr/bin
/usr/bin/kubelet
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/kubelet.service
```

**Comment by steven-sheehy** [comment]
Looks like this is due to this file in [kubernetes/release](https://github.com/kubernetes/release/tree/master/debian/xenial/kubelet/lib/default) repo. @chuckha Can this file can be removed?

In systemd Environment can't override the same variable in an EnvironmentFile, the workaround is to create a systemd drop-in with another EnvironmentFile:

```shell
$ cat /usr/lib/systemd/system/kubelet.service.d/20-containerd.conf
[Service]
EnvironmentFile=-/usr/etc/kubelet

$ cat /usr/etc/kubelet
KUBELET_EXTRA_ARGS=--container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --runtime-request-timeout=15m
```

**Comment by chuckha** [comment]
I find it odd that the kubelet package is doing this https://github.com/kubernetes/release/blob/master/debian/xenial/kubelet/debian/kubelet.install#L3.

I think it makes more sense for that to happen in the kubeadm package, and then, only if the file doesn't exist I think. I have to think about the various scenarios, but I think it's sensible to not have the kubelet writing the /etc/default/kubelet file.

**Comment by steven-sheehy** [comment]
I don't think it should be in the kubeadm package either. Systemd doesn't require it to be there and its supposed to be a user supplied file. Having kubernetes create/supply it would cause difficulties/conflicts with users including it in their own deb file or when creating it dynamically via their provisioning scripts.

**Comment by chuckha** [comment]
Thanks for the explanation, I agree and have opened a ticket in kubernetes/release.

**Comment by neolit123** [comment]
/close
RPMs were fixed here:
https://github.com/kubernetes/release/pull/658
