### ISSUE TITLE
Add De-Init Containers for POD Termination Lifecycle

### ISSUE THREAD

**Issue by rorysavage77** [kubernetes/kubernetes#70496]
**What would you like to be added**:
Rationale:  Currently, during POD instantiation Kubernetes offers initContainers and PostStart hooks.  However, for POD termination, the only offering is PreStop hooks.  This enhancement/feature request is to allow the same duality during POD instantiation also during POD termination.  Having the ability to have controlled sequential containerized jobs for POD termination allows for dealing with application management such as clearing out configurations, a de registration/or series of de registration processes, or a whole slew of opportunities which are limited by a single PreStop hook. 

**Why is this needed**:
It is needed because it is missing from the Kubernetes ecosystem.   Offering initContainers and PostStart hooks for startup but only offering PreStop hooks for termination is extremely limiting.   Having a De-Init container (or whatever you would like to call it), is imperative for closing the gap on complete container orchestration. 

Example:

I have a vast multi-pod microservices based ecosystem.  For example: when certain worker services come online, they can 1-Register with a registration API, 2-Share their configuration with other services, 3-Dynamically build their own configuration based on the current state of the ecosystem, 4-Perform SQL updates, and 5-Obtain a software license via API call - then they can start and run.  However during Termination, having this ability to perform the reverse with just a PreStop hook is impossible.

/kind feature

**Comment by rcsavage** [comment]
@kubernetes/sig-architecture-<group-suffix>
@kubernetes/sig-cluster-lifecycle-<group-suffix>
@kubernetes/sig-cluster-ops-<group-suffix>
@kubernetes/sig-scheduling-<group-suffix>

**Comment by goblain** [comment]
Is it not an issue though that while for `initContainers` it is a hard requirement for them to succeed for the actual workload to start, while potential `shutdownContainers` could only act on best effort with no solid guarantee that they will get executed as expected, introducing volatility to the design of deployed solution? Is it even worth having if it can not be guaranteed to execute?

**Comment by neolit123** [comment]
i tend to agree with the above statement.

if you want to get more attention from maintainers try asking in these slack channels #sig-node or #sig-scheduling.

this is not related to code that these sigs maintain:
/remove-sig cluster-lifecycle cluster-ops
/sig node

**Comment by rcsavage** [comment]
> Is it not an issue though that while for `initContainers` it is a hard requirement for them to succeed for the actual workload to start, while potential `shutdownContainers` could only act on best effort with no solid guarantee that they will get executed as expected, introducing volatility to the design of deployed solution? Is it even worth having if it can not be guaranteed to execute?

@goblain - perhaps I was not detailed enough in my feature request resulting in the above assumptions.   I am not necessarily requesting that shutdownContainers succeed prior to POD termination.   What I am requesting is, "upon POD termination", shutdownContainer(s) can be triggered.  

[POD-workers] - State: Terminating 
[shutdownContainer-1]: Starts as soon as the above POD is being "Terminated"
[shutdownContainer-2]: waiting on #1 to succeed 

In this model, since the termination signal is sent to the POD (and since there is really no way to revert a termination signal), that's all we need to know to trigger a shutdownContainer sequence of jobs.   They can trigger asynchronously with the termination signal or wait for the POD to be completely destroyed prior to kicking off -- it really doesn't matter as long as they are executed with or after the termination signal.

**Comment by keppi2** [comment]
:+1:

**Comment by bibryam** [comment]
Is this different that defer-containers proposal? 
https://github.com/dhilipkumars/community/blob/9e81de385df8355af78b32ec0dd596cecda86a8a/contributors/design-proposals/defer-containers.md

**Comment by rcsavage** [comment]
The defer-container proposal would suffice and provide additional benefits.   Seems like that proposal was started in 2017.   How can we raise the priority?

**Comment by bgrant0607** [comment]
Defer containers proposal: https://github.com/kubernetes/community/pull/483
Note there are a number of cases where defer containers could not be guaranteed to execute (e.g., preemption, OOM, disk full, other resource contention).

Comment on our current hooks generally: https://github.com/kubernetes/community/pull/1171#issuecomment-415503318

cc @kow3ns

**Comment by lukasheinrich** [comment]
when reviewing kubecon eu talks, I noticed tekton seems to have a similar issue, which they also solved via a "hack" (injecting a smart binary that handles the order). So it seems there are a bunch of use-cases for "run a linear sequence of pods on the same node")

@jdrawlings @mrbobbytables @rochaporto @afortiorama @clelange

**Comment by kfox1111** [comment]
One of the things I've suffered through is that preStop hooks all happen at once and the container they are associated with gets killed when that preStop is done. There may be some support containers that need to stay up while the main preStop hook happens. So maybe this needs to work with that. Maybe all de-init containers happen first, then prestop hooks, then actual pod death?

**Comment by kfox1111** [comment]
This may be covered by the Sidecar container use case?

**Comment by filipedeo** [comment]
@kfox1111 A sidecar container runs in parallel with the main application. Any sidecars would be stopped in conjunction with the main container. Check this old conversation of defer-containers (de-init containers) here: https://github.com/kubernetes/community/pull/483

**Comment by Warxcell** [comment]
+1 - would be useful for example main container is generating some files - and deinit container - can upload these files somewhere. That way we can split responsibilities and remove some binaries from main container - responsible only for uploading the generated files.
