### ISSUE TITLE
Readonly volumes in Kubernetes are a mess

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#70503]
**What happened**:

Kubernetes currently has 5 places where you can specify if a volume is readonly:

1. PVC/PV access modes may be `ReadOnlyMany`.
2. `Pod.spec.volumes.persistentVolumeClaim.readOnly` boolean
3. `PersistentVolume.spec.[volumeSource].readOnly` boolean where [volumeSource] could be `CSIPersistentVolumeSource`, `GCEPersistentDiskVolumeSource`, etc.
4. `Pod.spec.containers.volumeMounts[x].readOnly` boolean.

The current state appears to be:

1. Is used for binding PV/PVC only.
2. Some plugins use this for controlling if a volume is **attached** as readonly.
3. Some plugins use this for controlling if a volume is **attached** as readonly.
4. Some plugins use this for controlling if a volume is **mounted** as readonly.

**What you expected to happen**:

Because of Kubernetes API deprecation policy, we can't remove any of these from the API. But we should at least define (for consistency) or at least document what the various combinations of these parameters do for different volume plugins.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by saad-ali** [comment]
Number 2 in the list above ("`Pod.spec.volumes.persistentVolumeClaim.readOnly` boolean") is especially problematic because if you have multiple pods referencing the same PVC, each pod can effectively specify a different readonly value for attach.

**Comment by saad-ali** [comment]
@cduchense pointed out that number 3 is problematic because: a) it is unclear how it is set, and 2) it is unclear how it is changed -- PV.spec is immutable and even if it wasn't requires cluster admin privileges to change (since it is a non namespaced object).

**Comment by saad-ali** [comment]
We will try and be more clear with CSI before it goes GA: https://github.com/kubernetes/kubernetes/issues/70505

For the existing volume plugins, we should document what the current behavior is.

If we ever redo the k8s API we should fix the API.

**Comment by AishSundar** [comment]
@saad-ali should this issue be tracked for 1.13?

/cc @nikopen

**Comment by humblec** [comment]
>2.Some plugins use this for controlling if a volume is attached as readonly.
3.Some plugins use this for controlling if a volume is attached as readonly.>

@saad-ali state `2 and 3` are same.

**Comment by venkatsc** [comment]
@saad-ali ReadOnly can also be specified as mount flag through PV.spec.mountOptions or StorageClass.mountOptions
