### ISSUE TITLE
Fully disrupted zone still gets evicted by node controller?

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes#70501]
Somebody on Stackoverflow was puzzled about the eviction behavior of the node controller when a zone is fully disrupted: https://stackoverflow.com/questions/52871164/when-one-of-zones-enter-full-disruption-we-update-eviction-qps-to-which-value-f

According to [node_lifecycle_controller.go#316](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L316), the eviction behavior of a healthy and a fully disrupted zone is equal:

    nc.enterFullDisruptionFunc = nc.HealthyQPSFunc

I see that this logic was introduced in the context of https://github.com/kubernetes/kubernetes/issues/28832 and is documented at https://kubernetes.io/docs/concepts/architecture/nodes/#node-controller. Still it is not clear to me whether it is intended to still evict nodes from a fully disrupted zone with the same rate as from a healthy zone.

Of course we also need to consider the case that a zone might not come back at all.

Is there any additional information to find about this? @gmarek, could you help us?

**Comment by k82cn** [comment]
ack, let me check it :)
