### ISSUE TITLE
Validating admission webhook failures are treated as internal server errors

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#70506]
**What happened**:

Mutating and Validating webhooks that respond with an AdmissionResult with `allowed` set to `false` cause the apiserver to respond to the initiating request with a 500. This behavior is easily verifiable looking at the code, [error source](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go#L133), [flagged as internal error 500](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go#L73)

**What you expected to happen**:

The apiserver would respond to the request with a 4xx error code. Supporting reasoning for expecting this:
An excerpt from the [docs](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)
> This admission controller calls any validating webhooks which match the request. Matching webhooks are called in parallel; if any of them rejects the request, the request fails

My expectation is that if a webhook (particularly a validating webhook) says a request is not allowed, the apiserver should respond with a 4xx error (it's the client's fault, they're trying to do something that is not supported), not a 5xx error (there isn't something wrong with the apiserver). 
Prior art for the apiserver responding with a 4xx error when an admission plugin decides the request is not allowed [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go#L79)

**How to reproduce it (as minimally and precisely as possible)**:

Create a validating webhook with failure policy set to `fail` that will under some circumstance respond with an AdmissionResult of `allowed` set to false. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): ubuntu

/kind bug

**Comment by ryanmcnamara** [comment]
Hey @caesarxuchao mind taking a look at this?

**Comment by Sanjary** [comment]
Hey @ryanmcnamara, if you are using your own webhook, then you can set the status code yourself. We do this and it works as expected. Check this:

https://github.com/kubernetes/api/blob/01ff9a9183351161976ac234ac88da924d1df1ef/admission/v1beta1/types.go#L92

However, if you don't set this status code in the result, IIRC the default gets set to 500.

**Comment by ryanmcnamara** [comment]
@Sanjary I repro'd as I described with the following admission result returned from the webhook
```
{"allowed":false,"status":{"status":"Failure","message":"rmcnamara-test","reason":"Unauthorized","code":401}}
```
We were already setting the Result field, it doesn't seem to have an effect on the http code returned by the api server.

Curling the apiserver to create a pod with a webhook always returning the above admission response: https://gist.github.com/ryanmcnamara/5a7914e22567b0c29008f2a70dbdf37f

**Comment by ryanmcnamara** [comment]
Actually the above was for a *mutating webhook*

I just tested this on a *validating webhook* and *only if* you set code in the Response.Result.Code will the response from the apiserver not be 500. So I think this is fine to close out.

**Comment by khogeland** [comment]
Hey @caesarxuchao, wondering if this might actually be a bug, since a mutating webhook has no way to respond that the client input was incorrect. Maybe the response code from the webhook server should just be relayed to the originating request?

Here's an example:

I have a webhook that sets an annotation on certain pods. If that annotation is already set, I would like to return a 400 error to the user, as their input was invalid. There is no way for my mutating webhook to do this, so either my users need to tolerate 500 errors, or I need to create a second (validating) webhook that causes an additional HTTP request to my process. Both solutions are bad: I either need to violate HTTP standards, or double the amount of traffic to my process.

**Comment by Sanjary** [comment]
Hey @khogeland, if user input is wrong, that should be challenged in validating admission webhook, but if you want to mutate based on user input in your mutating admission webhook, then you can still send response from back there. Check this bit, you can send response and a custom message back to the client:

https://github.com/kubernetes/api/blob/01ff9a9183351161976ac234ac88da924d1df1ef/admission/v1beta1/types.go#L92

Please correct me if this is not the concern you are dealing with.

**Comment by khogeland** [comment]
@Sanjary The issue is that the user sees a 500 status code instead of the status code specified in the Result. There is no way for a mutating webhook to reject a request with a proper 400-something status code.

**Comment by uruddarraju** [comment]
yeah. I think it is a valid requirement to have the capability to return 400s with a Mutating Webhook. In most cases, developers would not want to build 2 different admission plugins, one for mutating and one for validation for the same `Kind`. It is convenient to have both mutating and validating logic in one webhook. This also decreases the number of roundtrips from the apiserver for the webhooks.

**Comment by khogeland** [comment]
looks like this was fixed by https://github.com/kubernetes/kubernetes/commit/c2fcdc818be1441dd788cae22648c04b1650d3af#diff-e057ec5b2ec27b4ba1e1a3915f715262
