### ISSUE TITLE
Support NetworkUnavailable condition for all cloud providers.

### ISSUE THREAD

**Issue by aoxn** [kubernetes/kubernetes#70526]
**What happened**:
 If cluster is configured with cloudprovider and --configure-cloud-routes enabled , there are chances that Node become ready before Route is created(ccm failed to create route due to throttle etc.). This would result in pod scheduled unexpectedly.
A workaround is to write RouteCreated=False Conditions to Node before we remove the node.cloudprovider.kubernetes.io/uninitialized taints. Like what we did for gce .
cloud/node_controller.go
```
		// TODO(wlan0): Move this logic to the route controller using the node taint instead of condition
		// Since there are node taints, do we still need this?
		// This condition marks the node as unusable until routes are initialized in the cloud provider
		if cnc.cloud.ProviderName() == "gce" {
			curNode.Status.Conditions = append(node.Status.Conditions, v1.NodeCondition{
				Type:               v1.NodeNetworkUnavailable,
				Status:             v1.ConditionTrue,
				Reason:             "NoRouteCreated",
				Message:            "Node created without a route",
				LastTransitionTime: metav1.Now(),
			})
		}
```

**Similar issue cause by RouteCreated Condition failure.**
There are some cases that KCM failed to allocate PodCIDR(address pool exhausted etc.) to node object which means `spec.PodCIDR: ""`.  
route_controller use spec.PodCIDR to decide whether `RouteCreated` condition should be set in Node Object , [Code](https://github.com/kubernetes/kubernetes/blob/6f897af2daffd8cd3539f1ef279b9f9bc280d98f/pkg/controller/route/route_controller.go#L155) 
```
	for _, node := range nodes {
		// Skip if the node hasn't been assigned a CIDR yet.
		if node.Spec.PodCIDR == "" {
			continue
		}
		nodeName := types.NodeName(node.Name)
		// Check if we have a route for this node w/ the correct CIDR.
		r := routeMap[nodeName]
```
route_controller simply ignore this case , and no RouteCreate=False condition was write back to NodeObject, This result in kubelet post ready status which is not expected.

### Some Attachment might help https://github.com/kubernetes/kubernetes/blob/6f897af2daffd8cd3539f1ef279b9f9bc280d98f/pkg/controller/cloud/node_controller.go#L407

**What you expected to happen**:

Kubelet should post NotReady status when PodCIDR is not allocated when `--configure-cloud-routes` is set on cloudprovider.

**What `s Next**
If this make sense to you, I would like to submit a PR to fix this.

/kind bug

**Comment by aoxn** [comment]
/sig cloud-provider
@andrewsykim @cjcullen

**Comment by andrewsykim** [comment]
It might make more sense to add this logic into the [node ipam controller](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/nodeipam), though be warned that the node ipam controller is currently in a weird state and runs in two different modes (normal and cloud). The "cloud" version only works on GCE but it does handle this case exactly, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodeipam/ipam/sync/sync.go#L213-L222). I think it might be good to refactor this in some way to make this logic available to any provider. I'm not sure what that looks like but starting there seems like a good place to start instead of adding that logic in routes controller. What do you think? I think @cheftako might have some opinions here as well.

**Comment by aoxn** [comment]
Sorry for the miss leading.  PodCIDR is just an example for how and why does it not work. 
Basically , This is caused by an uninitialized Node Condition of `RouteCreated`. If cluster is configured with cloudprovider and `--configure-cloud-routes` enabled , there are chances that Node become ready before Route is created(ccm failed to create route due to throttle etc.).  This would result in pod scheduled unexpectedly. 
A workaround is to write RouteCreated=False Conditions  to Node before we remove the `node.cloudprovider.kubernetes.io/uninitialized` taints. Like what we did for gce as below:
`
		// TODO(wlan0): Move this logic to the route controller using the node taint instead of condition
		// Since there are node taints, do we still need this?
		// This condition marks the node as unusable until routes are initialized in the cloud provider
		if cnc.cloud.ProviderName() == "gce" {
			curNode.Status.Conditions = append(node.Status.Conditions, v1.NodeCondition{
				Type:               v1.NodeNetworkUnavailable,
				Status:             v1.ConditionTrue,
				Reason:             "NoRouteCreated",
				Message:            "Node created without a route",
				LastTransitionTime: metav1.Now(),
			})
		}
`

**Comment by andrewsykim** [comment]
@aoxn maybe I'm missing something, I still see that code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L340-L351) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L262-L271). It's only for GCE still though

**Comment by andrewsykim** [comment]
I agree though that this should be addressed in a more generic way, I'm not sure what that would look like yet.

**Comment by andrewsykim** [comment]
Maybe the condition should always be applied when `--configure-cloud-routes` is enabled 🤔. Alternatively we can add "Node Readiness Gate" similar to Pod Readiness Gates, see [this commet by Tim Hocken](https://github.com/kubernetes/kubernetes/pull/33573#issuecomment-415524319).

**Comment by aoxn** [comment]
@andrewsykim  Thanks for point it out. My mistake to miss that part.

Apply condition when `--configure-cloud-routes` is enabled LGTM.  Also, `Node Readiness Gate ` is reasonable for long term, but it is a plenty of work thing, we might need a way to workaround it for now. 

@thockin Do you have any comments?

**Comment by andrewsykim** [comment]
Will be fixed as part of https://github.com/kubernetes/enhancements/pull/1003
