### ISSUE TITLE
Add mirror site support in command parameters

### ISSUE THREAD

**Issue by yangsongx** [kubernetes/kubernetes#70523]
**Add command parameter such as '--mirror-site=foo.com' in kubeadm tool**:

**As the F*CK GFW, we can't use k8s smoothly as it is banned in China, is it possible to add --mirror-site=xxx -like command parameters? or config file. Always using the xx.google.com would be a frustrating result here.**:

/kind feature

**Comment by dims** [comment]
@yangsongx we understand the frustration. please see the tips being accumulated in:
https://github.com/kubernetes/kubernetes/issues/56038

/close

**Comment by dims** [comment]
we have `cn-dev` slack channel for developers in china. please ask folks there as well.

**Comment by yangsongx** [comment]
Thank you very much!
