### ISSUE TITLE
CRI: Document CRI log format better

### ISSUE THREAD

**Issue by StevenACoffman** [kubernetes/kubernetes#70539]
Is this format documented anywhere outside the code?
We are struggling with how to support it in fluent-bit.

Follow-up to #44976

The current fluent-bit `crio` parser uses this regex predating the partial/full and logtag:
```
/^(?<time>.+)\b(?<stream>stdout|stderr)\b(?<log>.*)$/
```
@chlunde Has proposed in fluent/fluent-bit#876 this regex proposal:
```
/^(?<time>.+)\b(?<stream>stdout|stderr)( (?<logtag>[A-Z]))?\b(?<log>.*)$/
```
@kskewes Has this proposed this regex in fluent/fluent-bit#873 :
```
^(?<time>.+) (?<stream>stdout|stderr) (?<partialflag>F|P) (?<message>.*)$
```

If you look at the regex fluentd uses here [Line 128](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L128) it is currently:
```
/^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
```
Can you speak to which would best meet your understanding and experience?
Is there official CRI-O log format documentation we should be consulting?

This example: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L112

```
2016-02-17T00:04:05.931087621Z stdout F [info:2016-02-16T16:04:05.930-08:00] Some log text here
```
Does not demonstrate partials and tags the way this https://github.com/kubernetes/kubernetes/issues/44976#issuecomment-345373795 comment does:
```
TIMESTAMP STREAM TAG CONTENT
2016-10-06T00:17:09.669794202Z stdout P:TAG1:TAG2 log content 1
2016-10-06T00:17:09.669794203Z stdout P:TAG1:TAG2 log content 2
```

**Comment by StevenACoffman** [comment]
@kubernetes/sig-instrumentation-proposals
@kubernetes/sig-node-proposals

**Comment by StevenACoffman** [comment]
Not sure if proposal for documentation is correct? Apologies if I chose poorly.

**Comment by brancz** [comment]
Sounds like this is specific to cri-o? Have you tried consulting them? As far as I know there are sig-node members among the cri-o maintainers :slightly_smiling_face: .

**Comment by StevenACoffman** [comment]
@kubernetes/sig-cri-o-proposals

**Comment by StevenACoffman** [comment]
Good suggestion, as CRI-O is the most active CRI implementation. I reached out on slack to sig-cri-o (although that sig doesn't appear to be a label/team).

**Comment by runcom** [comment]
> Sounds like this is specific to cri-o? Have you tried consulting them? As far as I know there are sig-node members among the cri-o maintainers  .

The CRI log format is **not** specific to CRI-O. It's specific to the CRI itself and code to parse logs can be found here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L125-L169

There's no however _documented_ log format and that's something we (and kubernetes) need to take care of (/cc @mrunalp @Random-Liu @feiskyer )

**Comment by StevenACoffman** [comment]
That bit of code matches:
https://github.com/kubernetes-sigs/cri-o/blob/f58419d6cf462070a0c3727ad2dc554ef151e832/conmon/conmon.c#L499-L509

I also see this other code mention a `:` log tag delimiter:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/constants.go#L39-L55

However, I don't see any examples actively using the `:` log tag delimiter, but I have seen in #44976 discussion around:
```
2016-10-06T00:17:09.669794202Z stdout P:TAG1:TAG2 log content 1
```
Is that just for the future?

**Comment by StevenACoffman** [comment]
I will just make up whatever seems to work. There's no documentation more than what I found.
