### ISSUE TITLE
Kubelet won't start on Azure VMSS after upgrading to k8s v.1.11.X

### ISSUE THREAD

**Issue by s0komma** [kubernetes/kubernetes#70562]
**What happened**:
Updated Kubernetes to v1.11.X on my k8s cluster running on Azure VMSS and now, kubelet won't start reporting error:
failed to run Kubelet: could not init cloud provider "azure": No credentials provided for AAD application.
I have the /etc/kubernetes/cloud_config  where it was working fine in k8s v1.10.8 and it is in this format:

> {
    "tenantId": "XXXX-XXX-XXX-XXX-XXX",
    "aadClientId": "XXXX-XXX-XXX-XXX-XXX",
    "aadClientSecret": "XXXX-XXX-XXX-XXX-XXX",
    "subscriptionId": "XXXX-XXX-XXX-XXX-XXX",
    "resourceGroup": "rg-XXX-lab-XXX-c1",
    "location": "eastus",
    "subnetName": "/subscriptions/XXXXX/resourceGroups/sp-XXXX-001eastusXXX/providers/Microsoft.Network/virtualNetworks/sp-XXXX-001eastusXXXX/subnets/sn_XX.XX.XX.0_24",
    "securityGroupName": false,
    "vnetName": "sp-XXXXX-001eastusXXXX",
    "vnetResourceGroup": "sp-XXXXXXeastusXXXX",
    "routeTableName": false,
    "cloudProviderBackoff": false,
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": true
    "vmType": "vmss"
 }

**What you expected to happen**:
Kubelet should start without a problem.
**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Kubernetes to v1.11.X on a k8s cluster running on Azure VMSS and restart kubelet.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.4
- Cloud provider or hardware configuration: Azure VMSS
- OS (e.g. from /etc/os-release): Ubuntu- 16.04.5 LTS
- Kernel (e.g. `uname -a`):Linux cpeasb49c000000 4.15.0-1028-azure #29~16.04.1-Ubuntu SMP Thu Oct 18 21:21:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

/kind bug
/sig azure
/area kubelet

**Comment by s0komma** [comment]
my kubelet.service files
```root@XXXXX:/etc/systemd/system/kubelet.service.d# ls -l
total 8
-rw-r--r-- 1 root root 898 Nov  2 03:06 10-kubeadm.conf
-rw-r--r-- 1 root root 501 Nov  2 03:13 20-kubelet-defaults.conf
root@XXXXXX:/etc/systemd/system/kubelet.service.d# cat 10-kubeadm.conf
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
root@XXXXXXXX:/etc/systemd/system/kubelet.service.d# cat 20-kubelet-defaults.conf
[Service]
Environment="KUBELET_EXTRA_ARGS=--address=0.0.0.0 --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --pod-infra-container-image=gcr.docker.prod.walmart.com/google_containers/pause-amd64:3.0 --fail-swap-on=true --cgroup-driver=cgroupfs --cloud-provider=azure --cloud-config=/etc/kubernetes/cloud_config --cluster-dns=XXXXXXX --authentication-token-webhook --authorization-mode=Webhook --node-labels=node-role.kubernetes.io/master=true "
Restart=always
RestartSec=10s

**Comment by feiskyer** [comment]
Glad to see issues solved.

For others using kubeadm, remember to set `KUBELET_EXTRA_ARGS` in `/etc/default/kubelet`. It will override values specified in `/etc/systemd/system/kubelet.service.d/20-kubelet-defaults.conf`. 

/close
