### ISSUE TITLE
Create pod failed, resource quota's counts is wrong.

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#70563]
**What happened**:
When I have  resource quota, and I create some pods from file. All is OK.
When I fail to create a pod and  quota's status 's used  will add 1.

If we delete or update pod this wrong count will be updated  to be a right count.
Or 5 min after the quota controller will update quota to be a right status.

In api-server code. I find the quota will  update at first. And then try to create a pod. and if create pod failed but the quota doesn't roll back
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
This is easy to reproduce
1. Create a  resource quota name "quota".
2. Create a pod named "test-pod"
3. Create another pod named "test-pod" too.
4. Create pod failed .And `kubectl get quota quota -o yaml` can see wrong counts.

`
[root@VM_128_15_centos ~]# kubectl create -f pod.yaml
pod "myapp-pod" created`
`[root@VM_128_15_centos ~]# kubectl get quota quota -o yaml
`
`
[root@VM_128_15_centos ~]# kubectl create -f pod.yaml
Error from server (AlreadyExists): error when creating "pod.yaml": pods "myapp-pod" already exists
`
`[root@VM_128_15_centos ~]# kubectl get quota quota -o yaml`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by Nebulazhang** [comment]
If we delete or update any pod this wrong count will be updated to be a right count.
Because quota controller watch "delete" and "update" event.
</br>

**Comment by Nebulazhang** [comment]
@xiaoxubeii Sorry I don't read recent release code. But it can be easy to reproduce, if you have some time, you can  have a little test. In resource quota admission, resource quota would be validated and updated and then the pod creating will failed because of "same name". I think these two steps are serial.
I agree that "update or delete, and quota controller are enough for quota update, despite some delay". Update and delete can help  quota to be correct. And I think the little dirty result cannot cause serious results, so we can tolerate this mistake.

**Comment by xiaoxubeii** [comment]
I don't think resource admission and pod creating are serial. That is why I mean "it is hard to track the consequence".

**Comment by zjj2wry** [comment]
when quota has 1 Gi left, two pods are created at the same time. Only one pod should be created successfully. resources quota admission will update the state of quota when creating pods. Other pods will fail to update because resource version occurs change. Or because the remaining resources of quota are not enough, the pod can not be created successfully. But if the first pod fails for other reasons, you need to wait for the resource quota controller to trigger resync after 5 minutes to restore the original status.

/assign i will create a pr attempt fix this

**Comment by liggitt** [comment]
quota increase occurs prior to the pod being persisted in etcd. if that persistence fails, the quota will be over-reserved until the reconciling controller releases it in the background.

prior to 1.9, a validation error in a pod would reserve quota for every attempt made to create the pod

in 1.9 and after, only validated pods that are about to be persisted reserve quota

/close
