### ISSUE TITLE
Can kubernetes support to recreate container_B when container_A in the same pod is recreated?

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/kubernetes#70569]
**What would you like to be added**:
When container_A is crashed by some reason, kubernetes will recreate this container to recover. Is it possible to add a feature to define some rules in manifest to make container_B in the same pod  be recreated at same time?
**Why is this needed**:
Our case is: there is a sidecar container and core container in the same pod. we want the sidecar container and core container to be recreated at same time:
if the sidecar container is crashed and recreated, the core container should be recreated, verse visa.
The reason for that is the utility process inside  sidecar container and the application process inside  core container was in a same container, they were live together via supervisored. Now, we want to split the utility process to an independent container as a sidecar container, so we need the similar feature via kubernetes.
Thanks for your support in advance! :-) 

/kind feature

**Comment by neolit123** [comment]
/sig node

if you don't get a response please try stackoverflow or slack.
