### ISSUE TITLE
[RFE] Allow to override default AWS endpoint

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#70588]
When deploying kubernetes in AWS cloud provider it is assumed the AWS cloud is not disconnected [1]. In case the assumption is violated, the deployment fails as the default configuration sets the default endpoint DNS suffix to `amazonaws.com` [2].

**What would you like to be added**:

Extend the aws cloud provider initialization with configurable aws DNS suffix endpoint. Currently, the code creates a session (by invoking `session.NewSession(&aws.Config{})`, see [3]) that could be extended into:

```go
sess, err := session.NewSession(&aws.Config{
	EndpointResolver: endpoints.ResolverFunc(myCustomResolver),
})
```

as described in [4]. There are other places where the change needs to be applied:
- for `LoadBalancing`: https://github.com/kubernetes/kubernetes/blob/f2c9eb860fd89acab5d587122ff77d8bf013b9b7/pkg/cloudprovider/providers/aws/aws.go#L673
- for `Autoscaling`: https://github.com/kubernetes/kubernetes/blob/f2c9eb860fd89acab5d587122ff77d8bf013b9b7/pkg/cloudprovider/providers/aws/aws.go#L708
- others

**Why is this needed**:

So the Kubernetes can be deployed in air-gapped AWS regions.

**Links**

[1] https://digitalageexperts.com/how-are-aws-private-air-gapped-regions-different/
[2] https://github.com/aws/aws-sdk-go/blob/475409399d0f8a680b6c68fcd49be984e36d5d66/aws/endpoints/defaults.go#L212
[3] https://github.com/kubernetes/kubernetes/blob/f2c9eb860fd89acab5d587122ff77d8bf013b9b7/pkg/cloudprovider/providers/aws/aws.go#L959
[4] https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/

/kind feature

**Comment by ingvagabund** [comment]
In theory, it should be enough to extend `CloudConfig` data type with `Endpoint` or similar field that is set to `amazonaws.com` by default.

[1] https://github.com/kubernetes/kubernetes/blob/f2c9eb860fd89acab5d587122ff77d8bf013b9b7/pkg/cloudprovider/providers/aws/aws.go#L521-L569

**Comment by ingvagabund** [comment]
Though, every endpoint resolver needs to be re-implemented since all the endpoint partitions are private [1] (in case we just want to replace the DNSsuffix with a different one).

[1] https://github.com/aws/aws-sdk-go/blob/475409399d0f8a680b6c68fcd49be984e36d5d66/aws/endpoints/defaults.go#L199-L201

**Comment by mbach04** [comment]
+1 These hard-coded endpoints are affecting a lot of folks. It would be great to see awslabs patch the sdk too.

**Comment by cuppett** [comment]
From the [AWS SDK for Go](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/):

> If the CA bundle file contains multiple certificates all of them will be loaded. The Session option CustomCABundle is also available when creating sessions to also enable this feature. CustomCABundle session option field has priority over the AWS_CA_BUNDLE environment variable, and will be used if both are set.

We could add a config option, but just relying on an environment variable to the kubelet may suffice and be simpler?

**Comment by VanWolf29** [comment]
I'd like to take this one. But I think I need some extra information about what it needs to be done.

**Comment by mbach04** [comment]
For tracking purposes:
[Kube auto-scaler](https://github.com/kubernetes/autoscaler/issues/1707)
