### ISSUE TITLE
Add the ability to kube-apiserver's healthz endpoint to disable health checks via query params

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#70591]
**What would you like to be added**:

Add support to the kube-apiserver so that we can disable health-checks via query params. 

**Why is this needed**:

Currently, the healthz endpoint is inflexible in that any and all health checks are currently executed when the endpoint is hit. Since the kube-apiserver only currently supports a liveness check, this means all persistent health check failures will eventually result in a kubelet driven restart. However, this may not be desirable behavior if you have additional monitoring services layered on top of your control plane. 

For instance, take the etcd failure from the perspective of the kube-apiserver. Currently, persistent failures during the etcd health check from the api-server healthz endpoint will cause the kube-apiserver to be restarted. This sometimes helps (in the case of a faulty etcd-client connection) but also can be detrimental (the kube-apiserver restarts until the etcd cluster is functioning, then the kube-apiserver bombards the etcd cluster with requests to update local caches, saturating the etcd cluster with requests, causing it to timeout on its own liveness probes and trigger a kubelet-driven restart). 

Let's say that we could now disable etcd from our liveness health check. Then if we had an external monitoring service, we could ask independently ask etcd if it was healthy and we could also ask the kube-apiserver if it thought etcd was unhealthy. Based on the combination of those answers, we could enable more intelligent responses to certain situation, like restarting the kube-apiserver when it thought etcd was unhealthy but etcd was actually reporting as healthy but not doing so when etcd was actually unhealthy. 

This feature is backwards-compatible and opt-in. There would be no impact to existing behavior unless these query params are actually used. 

/sig api-machinery
/kind feature

**Comment by lavalamp** [comment]
SGTM
