### ISSUE TITLE
Reference Docs: Windows Supported APIs

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#70604]
This is a tracking issue for the API reference documentation that needs to be updated related to Windows. This will replace the earlier list [here](https://github.com/kubernetes/community/blob/master/sig-windows/api-tracking.md). Initially I'm putting in a GitHub task list but will replace them with PR links as they're submitted

Many of these issues will probably also be gathered into https://github.com/kubernetes/kubernetes/issues/8190 to make the 'v2' api more OS-agnostic

Also for reference - the non-autogenerated website docs are tracked here https://github.com/kubernetes/website/pull/10875

- [ ] V1.Pod.Volumes - need to clarify mount options, permissions handling (no uid/gid), no subPath mounts
- [ ] V1.Pod.Resources.ResourceRequirements - clarify what properties work / don't work on Windows
- [ ] V1.Pod.hostNetwork - not supported
- [ ] V1.Pod.hostIPC, v1.Pod.hostpid, v1.Pod.
- [ ] V1.Pod.hostAliases - not supported, Windows doesn't support single file mounts
- [ ] V1.Pod.SecurityContext - some Windows unique additions, but most existing fields are Linux specific. `privileged` is not supported
- [ ] V1.Container.terminationMessagePath - Windows doesn't support single file mounts

/kind bug
/milestone v1.13
/sig windows
/sig architecture
/sig node

**Comment by AishSundar** [comment]
@tfogo the 1.13 Docs lead for tracking

**Comment by daschott** [comment]
Need to possibly add workaround on Windows Server, version 1803 to set DNS SearchList RegKey (instead of Domain). To achieve this, one can copy the registry key over using the following script:
[SearchListRegKeyEdit.zip](https://github.com/kubernetes/kubernetes/files/2581791/SearchListRegKeyEdit.zip)

you can then query if SearchList is set using:
`reg query HKLM\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces /s`

**Comment by bgrant0607** [comment]
Note that we're trying to make the KEP the authoritative list

https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md#what-will-never-work-without-underlying-os-changes

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will this be implemented in the following week?

**Comment by PatrickLang** [comment]
The KEP has full details, so I don't think this is needed and can be closed. @bgrant0607 - do you agree?

**Comment by bgrant0607** [comment]
Yes
/close
