### ISSUE TITLE
oidc via ldap+dex - invalid bearer token, invalid bearer token

### ISSUE THREAD

**Issue by rlagutinhub** [kubernetes/kubernetes#70601]
**What happened:**
I can not configure oidc via ldap+dex authentication.
Authentication fails 401 and the following messages write to the kube-api log:
authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]

Tell me how to solve this error.

**How to reproduce it (as minimally and precisely as possible):**
added following lines to kube-apiserver.yaml and then copy the file to /etc/kubernetes/manifests
    - --oidc-issuer-url=https://dex.k8s.dev.mta4.ru:32000/dex
    - --oidc-client-id=loginapp
    - --oidc-username-claim=name
    - --oidc-groups-claim=groups
    - --oidc-ca-file=/etc/kubernetes/pki/ca.pem

**Anything else we need to know?:**

**logs:**

less /var/log/containers/kube-apiserver-k8s-m1_kube-system_kube-apiserver-* or kubectl -n kube-system logs kube-apiserver-k8s-master01

 E1104 17:33:49.261285       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:33:49.286740       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:33:49.289633       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:33:49.291983       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:33:49.294518       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:34:29.652333       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:34:29.656383       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:34:29.659672       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:34:29.662339       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
E1104 17:34:29.665262       1 authentication.go:62] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]

**Environment:**

**Kubernetes version (use kubectl version):**
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:17:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Cloud provider or hardware configuration:**

**OS (e.g. from /etc/os-release):**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Kernel (e.g. uname -a):**
Linux k8s-master01 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Install tools:**
kubeadm

**Others:**
/sig oidc

/triage support

**Comment by rlagutinhub** [comment]
my log
![1](https://user-images.githubusercontent.com/30324030/47967113-1a2bca00-e06b-11e8-95d2-607d7c3bf2cc.png)
![2](https://user-images.githubusercontent.com/30324030/47967130-40ea0080-e06b-11e8-8ff1-3ab1b0c3972b.png)
![3](https://user-images.githubusercontent.com/30324030/47967151-6b3bbe00-e06b-11e8-8537-8ac067d38ad7.png)
![4](https://user-images.githubusercontent.com/30324030/47967181-b950c180-e06b-11e8-9923-72de74e2dcc3.png)

**Comment by liggitt** [comment]
/sig auth

That error message typically means the bearer token is not a valid signed JWT for the issuer

**Comment by rlagutinhub** [comment]
when using certificate letsencrypt this error is repeated [invalid bearer token, [invalid bearer token, invalid bearer token]]

**Comment by rlagutinhub** [comment]
Example my oidc token

- name: user1@dev.mta4.ru
  user:
    auth-provider:
      config:
        client-id: loginapp
        client-secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmYmMyMTU4NmU2MDQ3MmUyNmM1NGJmNTk2NmVkZDUxMjEwYWJlODgifQ.eyJpc3MiOiJodHRwczovL2RleC5kZXYubXRhNC5ydTozMjAwMC9kZXgiLCJzdWIiOiJDZ1YxYzJWeU1SSUViR1JoY0EiLCJhdWQiOiJsb2dpbmFwcCIsImV4cCI6MTU0MTQ4OTYyNiwiaWF0IjoxNTQxNDAzMjI2LCJhdF9oYXNoIjoiMEs5OGFhR3I3UEY3elVwWDR4Z3RVQSIsImVtYWlsIjoidXNlcjFAZGV2Lm10YTQucnUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ3JvdXBzIjpbImFkbWlucyJdLCJuYW1lIjoidXNlcjFAZGV2Lm10YTQucnUifQ.FY_p4P8_6tahXXsNfR65UMCQtBcuapBwIMw3xE_4ERSr47N6VKJDJ4rltjUOLJrTkxtXdMq_RXeWgIqj_QEqsHcNKqaWKZPb-ya9X3aE8AuC5AkeQPIq_NjPH9MIGDqUmnHevHlzyQZQotjtpgSKFsj_HXQ2Wem18mUccCvgq6sFSVv9c0dGhMwX2stJ8kPx0XsAjOqaG5OJodQ7Nob60RgxEzFM2a7QH3-n7zUGcc1TuLamqgJQu7lmzpgJu6W_Qtq8DF4EKPTDxccLnt0K4fJ6bT1SPikiCwXnjpAxNrk9NdZAXlyxakG5Qd7OPRkbRH5p2WLfzyRyj2AcEgot1w
        idp-issuer-url: https://dex.dev.mta4.ru:32000/dex
        refresh-token: Chl6M28zZXAycHBmbDR0b2dqYnh6ZjR6b2VzEhlrbWRlcXBiZWxicGN1YzRweGgyZDJybnNx
      name: oidc

**Comment by rlagutinhub** [comment]
I tested loginapp, dex-k8s-authenticator, gangway, with self-signed or letsencrypt certs.
 For all my solutions have an error [invalid bearer token, [invalid bearer token, invalid bearer token]]

**Comment by rlagutinhub** [comment]
> /sig auth
> 
> That error message typically means the bearer token is not a valid signed JWT for the issuer

In this case, it should be possible example - crypto/rsa: verification error?

**Comment by rlagutinhub** [comment]
> when using certificate letsencrypt this error is repeated [invalid bearer token, [invalid bearer token, invalid bearer token]]

signature verified successfully

https://dex.dev.mta4.ru/.well-known/openid-configuration
![1](https://user-images.githubusercontent.com/30324030/48132771-b6411580-e2a5-11e8-8187-f68e7c261709.png)

https://dex.dev.mta4.ru/keys
![2](https://user-images.githubusercontent.com/30324030/48132786-be995080-e2a5-11e8-843a-6f0fa7324bc7.png)

https://npm.runkit.com/jwk-to-pem
![3](https://user-images.githubusercontent.com/30324030/48132805-c78a2200-e2a5-11e8-82ef-c402e7b3a243.png)

https://jwt.io/
![4](https://user-images.githubusercontent.com/30324030/48132811-d07af380-e2a5-11e8-91b4-099e1e85cda3.png)

**And successfully result check ssl aceess from kube-api pod to dex pod**

 curl https://dex.dev.mta4.ru/keys -vvv
*   Trying 192.168.1.205...
* TCP_NODELAY set
* connect to 192.168.1.205 port 443 failed: Connection refused
*   Trying 192.168.1.204...
* TCP_NODELAY set
* Connected to dex.dev.mta4.ru (192.168.1.204) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=login.dev.mta4.ru
*  start date: Nov  4 20:15:28 2018 GMT
*  expire date: Feb  2 20:15:28 2019 GMT
*  subjectAltName: host "dex.dev.mta4.ru" matched cert's "dex.dev.mta4.ru"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  **SSL certificate verify ok.**
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5625cd6e3dc0)
> GET /keys HTTP/1.1
> Host: dex.dev.mta4.ru
> User-Agent: curl/7.52.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx/1.15.5
< date: Wed, 07 Nov 2018 12:25:47 GMT
< content-type: application/json
< content-length: 1032
< vary: Accept-Encoding
< cache-control: max-age=12802, must-revalidate
< strict-transport-security: max-age=15724800; includeSubDomains
<
{
  "keys": [
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "59cc1c0ff3e725d7e72fbf5ebc27f4ef56040f95",
      "alg": "RS256",
      "n": "vBcGt1SQEiGAwkKTLh8QPrW-GTHJnPso68En-lhUc9ADvsujDrzXg5Jz0FqbCeeC1TuEJ2NbWMOZc629tnUAmyWtde4tgtRwHl4_J9_5IVeiCUHYRZMRTrsB-mgPjLOG6hAHEDxC7kYxRKWDVIi0ekhFtwW8kh1XQ5AsxsSi7ysYq8m1--S3pi_Iu4cUk6wWi61WSh3Na3NV46Xdytb6zIOyZLYCfb3X4-QLHWdFejH_NIHihFFdwbdtcFBMk9_7i44QH3PJlOKVD2MgO0_kKntK67qKmAcbFzqXH92vLgfsb3EoX324OF-g6u3ID3mzEP2mwgqBlR6pSvSL-N8tkw",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "056c032ee83e55e917d7ab9fbec7661ac2427b24",
      "alg": "RS256",
      "n": "ynVrBEzEzHw8mxUh3JCKVgqKoRs3Jo2Ux_DPT1qR2SrxxBEYopgFOyTL3mJI2C4Lp1UGYvi3PA2w9mLTbwp6caoLDeHKcA_WCdqA-AA8seqg43u0MhMNT4cyoQMptU72BFkEKFKP0zovOtSNJQ0F0Rl7aQep23TBBWGcJM9HULIL6RQJUSUkZSIiXQJhOO5WPsybP97O0rWXzLzCVSdj_HbnNyMEBPir6CBhfXUm5oqXnRFaZA3-aEvm4XYA9-02q7ksYJpFdBzQ9vTt7Y1x9hgNmGIQ5gwS0QSAJ3Sr_dlbXi8rstEwCYwWoK0Amlc1E3scfS49MEGyk2lmQrXOqw",
      "e": "AQAB"
    }
  ]
* Curl_http_done: called premature == 0
* Connection #0 to host dex.dev.mta4.ru left intact

**Comment by ericchiang** [comment]
I don't think this is an issue with Kubernetes https://github.com/dexidp/dex/issues/1336#issuecomment-437465175

**Comment by yudiandreanp** [comment]
Got the same problem, this time with Google's OAuth2 as Identity Provider

**Comment by yudiandreanp** [comment]
> Example my oidc token
> 
> * name: [user1@dev.mta4.ru](mailto:user1@dev.mta4.ru)
>   user:
>   auth-provider:
>   config:
>   client-id: loginapp
>   client-secret: 4TORGiNV9M54BTk1v7dNuFSaI6hUjfjr
>   id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmYmMyMTU4NmU2MDQ3MmUyNmM1NGJmNTk2NmVkZDUxMjEwYWJlODgifQ.eyJpc3MiOiJodHRwczovL2RleC5kZXYubXRhNC5ydTozMjAwMC9kZXgiLCJzdWIiOiJDZ1YxYzJWeU1SSUViR1JoY0EiLCJhdWQiOiJsb2dpbmFwcCIsImV4cCI6MTU0MTQ4OTYyNiwiaWF0IjoxNTQxNDAzMjI2LCJhdF9oYXNoIjoiMEs5OGFhR3I3UEY3elVwWDR4Z3RVQSIsImVtYWlsIjoidXNlcjFAZGV2Lm10YTQucnUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ3JvdXBzIjpbImFkbWlucyJdLCJuYW1lIjoidXNlcjFAZGV2Lm10YTQucnUifQ.FY_p4P8_6tahXXsNfR65UMCQtBcuapBwIMw3xE_4ERSr47N6VKJDJ4rltjUOLJrTkxtXdMq_RXeWgIqj_QEqsHcNKqaWKZPb-ya9X3aE8AuC5AkeQPIq_NjPH9MIGDqUmnHevHlzyQZQotjtpgSKFsj_HXQ2Wem18mUccCvgq6sFSVv9c0dGhMwX2stJ8kPx0XsAjOqaG5OJodQ7Nob60RgxEzFM2a7QH3-n7zUGcc1TuLamqgJQu7lmzpgJu6W_Qtq8DF4EKPTDxccLnt0K4fJ6bT1SPikiCwXnjpAxNrk9NdZAXlyxakG5Qd7OPRkbRH5p2WLfzyRyj2AcEgot1w
>   idp-issuer-url: https://dex.dev.mta4.ru:32000/dex
>   refresh-token: Chl6M28zZXAycHBmbDR0b2dqYnh6ZjR6b2VzEhlrbWRlcXBiZWxicGN1YzRweGgyZDJybnNx
>   name: oidc

In my case, it turned out that I have to change "id-token" into "id_token".
Got the clues from here:
https://groups.google.com/forum/#!topic/kubernetes-sig-auth/6JjBeliY4-I

**Comment by rlagutinhub** [comment]
> In my case, it turned out that I have to change "id-token" into "id_token".

i changed "id-token" into "id_token" in kubeconfig file , but it doesn't work for me

**Comment by rlagutinhub** [comment]
> It is very possible that reason for error **[invalid bearer token, [invalid bearer token, invalid bearer token]]** ,
> 
> what I do backup manifest kube-api config file before changing it
> **cp -p /etc/kubernetes/manifests/kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml.orig**

really), after deleting this backup file /etc/kubernetes/manifests/kube-apiserver.yaml.orig
it works

for information https://github.com/dexidp/dex/issues/1336

**Comment by styk-tv** [comment]
I spent last 2 days with Keycloak (+Ldap) and K8s setup. Same exact configuration in k8s 1.9 worked flawlessly. Version below is producing 
```
authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
```
version:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mcasperson** [comment]
I've experienced this same error using Google OIDC and the k8s-oidc-helper. But the issues eventually rectifies itself. So my process is:

1. Build the local ~/.kube/config file using `k8s-oidc-helper`.
2. Add the appropriate RBAC cluster role bindings
3. Run `kubetctl get nodes`. This fails with `error: You must be logged in to the server (Unauthorized)`, and my log files have `Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]`
4. Wait a while
5. Try again, everything is good

What I have noticed is that the JWT token added to the `id-token` field by `k8s-oidc-helper` has an invalid signature when inspected in https://jwt.io/. My suspicion is that once this initial token expires, a refreshed one is retrieved, and the the starts auth working as expected.

**Comment by unbreakabl3** [comment]
> > It is very possible that reason for error **[invalid bearer token, [invalid bearer token, invalid bearer token]]** ,
> > what I do backup manifest kube-api config file before changing it
> > **cp -p /etc/kubernetes/manifests/kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml.orig**
> 
> really), after deleting this backup file /etc/kubernetes/manifests/kube-apiserver.yaml.orig
> it works
> 
> for information [dexidp/dex#1336](https://github.com/dexidp/dex/issues/1336)

Helped me as well.

**Comment by jackchuong** [comment]
Hi all,
I get same error with gangway+dex+AD+letsencrypt , my environment :
Kubernetes version: 1.26
Cloud being used: bare-metal
Installation method: kubeadm
Host OS: Ubuntu 22.04
CNI and version: Flannel latest
CRI and version: docker with Mirantis cri-dockerd as Docker Engine shim
1 control plane node and 3 worker nodes
/etc/kubernetes/manifests/kube-apiserver.yaml
```
    - --oidc-issuer-url=https://auth.k8s.mydomain.com/
    - --oidc-client-id=oidc-auth-client
    - --oidc-ca-file=/etc/kubernetes/pki/letsencrypt.pem
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
```

It used to work before , until last week, when I have to restarted my control plane node cause of some memory leak error. After that, when I try to access to k8s cluster from my computer with kubectl I get error
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
kubectl get nodes
E0728 12:13:04.100729   23052 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E0728 12:13:04.113234   23052 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E0728 12:13:04.125072   23052 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E0728 12:13:04.134795   23052 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E0728 12:13:04.142634   23052 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
This is log from api pod in kube-system namespace
```
E0804 07:23:25.791415       1 authentication.go:70] "Unable to authenticate the request" err="invalid bearer token"
E0804 07:23:25.806786       1 authentication.go:70] "Unable to authenticate the request" err="invalid bearer token"
E0804 07:23:25.816405       1 authentication.go:70] "Unable to authenticate the request" err="invalid bearer token"
E0804 07:23:25.825794       1 authentication.go:70] "Unable to authenticate the request" err="invalid bearer token"
E0804 07:23:25.833763       1 authentication.go:70] "Unable to authenticate the request" err="invalid bearer token"
```
Please give me some advice , thank you very much.
