### ISSUE TITLE
kubeadm join node successfully but list not found

### ISSUE THREAD

**Issue by bigbang009** [kubernetes/kubernetes#70614]
while I join a node by useing kubeadm join, it prompt successfully, but not found by listing nodes.
I found the token has been expired. So, I create token again, finally, it works. So, is it a bug that token has been expired but prompting successfully?

**Comment by neolit123** [comment]
could you please log the issue in the https://github.com/kubernetes/kubeadm tracker.
also provide more details like steps to reproduce, OS, and kubeadm version.
thanks.

/close

**Comment by bigbang009** [comment]
> could you please log the issue in the https://github.com/kubernetes/kubeadm tracker.
> also provide more details like steps to reproduce, OS, and kubeadm version.
> thanks.
> 
> /close
CentOS and the kernel version is kernel-4.14.47, the kubeadm version as follows:
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
