### ISSUE TITLE
Update to golang 1.11.2

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#70631]
go 1.11.2 is out 11/2 and this bug tracks upgrade to the latest version.

* Is it something we should absolutely needed in the 1.13 timeframe? 
* are there any [critical fixes in 1.11.2](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=milestone%3AGo1.11.2+) that should absolutely take?
* how long does the associated image updates and push take?
* If we chose to upgrade in 1.13,  we should do it before code slush targeted for Friday 11/6.

/assign @ixdy 

@ixdy can you please clarify the above ques and and help evaluate timing of the upgrade.

/cc @cjwagner @jberkus 
/sig release
/sig testing
/priority important-soon
/kind cleanup

**Comment by cblecker** [comment]
/cc
I’ve already got a branch cooking for this, but waiting for rules_go support first. I think @jayconrad said in Slack that this will happen this week.

**Comment by AishSundar** [comment]
Ahh so is the earliest expected timeframe when we can upgrade falls into Code slush period for 1.13 (post 11/9?) Depending on when this lands we might want to see if its safe to wait for 1.13.1. @cblecker are you aware of any critical fixes that make this compelling for 1.13 timeframe?

**Comment by cblecker** [comment]
The risk for patch golang point releases is typically low (the minor releases, like 1.10 -> 1.11, are higher risk). I don't see anything that's critical or of known impact, but at the same time, I see compiler fixes and go/types package fixes. They are more subtle and could present issues later.

I'd suggest that if we can tolerate getting it in, even if we're in slush, we should.

**Comment by AishSundar** [comment]
Ack that @cblecker :) Plz ping this bug as soon as we are ready to build and push the upgraded images. we'll will make a final call depending on the timeframe and CI signal going in. thanks!
