### ISSUE TITLE
Failing test: [sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stabilityChanges

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubernetes#70655]
**Which jobs are failing**:
[sig-release-master-upgrade/gce-new-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master)

**Which test(s) are failing**:
[[HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5 and verify decision stability](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1862#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicationcontroller-should-scale-from-1-pod-to-3-pods-and-from-3-to-5-and-verify-decision-stability)

**Since when has it been failing**:
November 3rd, 2018

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1862#sig-autoscaling-hpa-horizontal-pod-autoscaling-scale-resource-cpu-sig-autoscaling-serial-slow-replicationcontroller-should-scale-from-1-pod-to-3-pods-and-from-3-to-5-and-verify-decision-stability

**Anything else we need to know**:
[diff towards last passing commit](https://github.com/kubernetes/kubernetes/compare/3293f02d0...46d173232?) hints at #69698 .

/kind failing-test

**Comment by AishSundar** [comment]
@jbartosik this failure is currently blocking Beta for 1..13. Can you please investigate these and let us know the path forward.

**Comment by jbartosik** [comment]
It looks like it's the same problem (too strict expectations of the test) I'm solving in issue #69444 manifesting in test going in other direction so those PRs should solve it (both tests use the same helper to set expectations so relaxing expectations of the helper should help both tests).

This is an issue with tests having too strict expectations, I wouldn't block a release on it.

**Comment by AishSundar** [comment]
@jbartosik just to be clear the CPs above should fix this too or is there a new PR to relax the strict expectation?

**Comment by jbartosik** [comment]
The PRs above are relaxing tests. They should fix this issue.

**Comment by jberkus** [comment]
Unable to verify that the fix worked, because the test is failing for unrelated reasons.

**Comment by AishSundar** [comment]
I see these 2 pass in the latest run of https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-master (after we split out the parallel and non-parallel runs). 

Over to @jberkus to close when he sees fit

**Comment by jberkus** [comment]
/close

Thanks @jbartosik for the long slog!
