### ISSUE TITLE
Support to pause and resume the ability of scaling just like rollout

### ISSUE THREAD

**Issue by lvjing2** [kubernetes/kubernetes#70656]
**What would you like to be added**:
- kubectl scale pause deployment/xxx
- kubectl scale resume deployment/xxx
**Why is this needed**:
I maintained a preheat shared pod pool, and I need to add the pod to some user's deployment(replica=0) when it's need to scale up.
And what's the problem is that:
### if the init replica of user deployment is zero, then when i try to add the shared pod to the deployment and then set the replica to 1.
 - the rs will terminate the shared pool, cause the rs check the replica is 0 before i set it to 1.
### if the init replica of user deployment is zero, then when i try to set the replica to 1 and then add the shared pod to the deployment.
 - the rs will start a user pod, and after i added the shared pool to the user deployment, then the rs will check that there are 2 pod, so it will start to terminate a random one of them.
So no matter how did i try, I just can't achieve what I want. 

/kind feature

**Comment by tammersaleh** [comment]
I'd also like to see this.  

If a user specifies `replicas: 100` in their deploy manifest, runs `kubectl apply`, and then wants to migrate to HPA, then they've painted themselves into a corner.  

If they remove `replicas:` from the manifest and `apply` it, the app will immediately scale down to the default of 1 replica.  HPA will kick in, but customer experience will suffer in the meantime.  

We could avoid this if we could pause the scaling, apply the new manifest, manually `kubectl scale` to 100, and then unpause.
