### ISSUE TITLE
Failing Test: [sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#70661]
**Which jobs are failing**: gce-cos-master-reboot

**Which test(s) are failing**:
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards
[sig-cluster-lifecycle] Reboot [Disruptive] [Feature:Reboot] each node by triggering kernel panic and ensure they function upon restart

**Since when has it been failing**: Nov 5

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-reboot

**Reason for failure**:
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:116
Nov  5 17:17:13.789: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/lifecycle/reboot.go:168

**Anything else we need to know**:
This seems very similar to the issue reported and fixed in #69786

/sig cluster-lifecycle
/kind failing-test
/priority important-soon
/cc @msau42

**Comment by mortent** [comment]
Looks like the last 11 runs of this job has succeeded. If it still looks green tomorrow, we can probably close this.

**Comment by mortent** [comment]
So the job failed three times overnight, so it is definitely flaky. It seems to have been flaking 
for at least the last two weeks. Keeping the issue open, but changing it from failing test to flake.

/kind flake

**Comment by mariantalla** [comment]
Hey just a heads up that these are failing/flaking again. The diff is [here](https://github.com/kubernetes/kubernetes/compare/468c99ea2...bcef72bf0?); it seems the reason is that the reboot is not completed in time.

@yagonobre  tagging you as a commit you added shows up in the diff so you may have helpful context.

cc @AishSundar @jberkus

**Comment by jberkus** [comment]
Flake again today: https://k8s-testgrid.appspot.com/sig-release-1.13-blocking#gce-cos-1.13-reboot

This is the timeout again:

```
Nov 19 23:44:41.185: Test failed; at least one node failed to reboot in the time given.
```

Maybe we're just setting the timeout parameters a little too tight?  According to triage, this is a frequent flake, going back as long as we have history.  Can we maybe test increasing the timeouts by 10% and see if it fixes the flaking?
