### ISSUE TITLE
kube-apiserver audit log rotation throwing permission denied

### ISSUE THREAD

**Issue by LykinsN** [kubernetes/kubernetes#70664]
**What happened**:
I'm setting up integration with the Splunk logforwarder agent to stream our Kubernetes audit logs from our master nodes to Splunk Enterprise but I'm seeing an odd issue in our logs, where the kube-apiserver process says permission denied when trying to rotate the logs once they've reached maximum capacity.

`kube-apiserver[1574]: E1105 18:43:54.090393    1574 metrics.go:86] Error in audit plugin 'log' affecting 1 audit events: can't open new logfile: open /var/lib/audit.log: permission denied`

**What you expected to happen**:
I expect the logs to be rotated without issue, though there seems to be a failure in our situation.

**How to reproduce it (as minimally and precisely as possible)**:
I've only observed the problem once enabling the Splunk logforwarder and pointing it to the audit log file. I've confirmed on the Splunk side, that the forwarder agent shouldn't be locking the file in any way and should be doing a read only operation.

I've confirmed I can use root privileges to rename the file myself, but then I get a subsequent permission denied error with creating the new file (`can't open new logfile: open /var/lib/audit.log: permission denied`). From there, if I do `touch audit.log` then it begins to write to the file again as expected.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS/EC2
- OS (e.g. from /etc/os-release):
```NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux *** 4.4.0-1070-aws #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

/kind bug

**Comment by LykinsN** [comment]
@kubernetes/sig-AWS-bugs

**Comment by mihailgmihaylov** [comment]
I am not sure if this is related, I had a similar issue recently with the rotation of kube-apiserver audit logs. The error I received, however was:
```
E0129 13:15:01.951796       1 metrics.go:96] Error in audit plugin 'log' affecting 1 audit events: can't rename log file: rename /var/log/kube-apiserver-audit.log /var/log/kube-apiserver-audit-2019-01-29T13-15-01.951.log: device or resource busy
```

It turned out that I was mounting only the file to the kube-apiserver pod and therefore the container was unable to rename it. You can check if this is your case also.

This fixed my issue:
```
   - hostPath:
-      path: /var/log/kube-apiserver-audit.log
+      path: /var/log/kube-apiserver-audit
-       type: FileOrCreate
     name: audit
```

**Comment by arpitaashu** [comment]
> I am not sure if this is related, I had a similar issue recently with the rotation of kube-apiserver audit logs. The error I received, however was:
> 
> ```
> E0129 13:15:01.951796       1 metrics.go:96] Error in audit plugin 'log' affecting 1 audit events: can't rename log file: rename /var/log/kube-apiserver-audit.log /var/log/kube-apiserver-audit-2019-01-29T13-15-01.951.log: device or resource busy
> ```
> 
> It turned out that I was mounting only the file to the kube-apiserver pod and therefore the container was unable to rename it. You can check if this is your case also.
> 
> This fixed my issue:
> 
> ```
>    - hostPath:
> -      path: /var/log/kube-apiserver-audit.log
> +      path: /var/log/kube-apiserver-audit
> -       type: FileOrCreate
>      name: audit
> ```

Hey Mihail, I satrt getting the similar alert (after 1 day). You mentioned change only in hostpath. what changes are required in --audit-log-path and -mountpath??

My current config:

> --audit-log-path=/var/log/apiserver/audit.log
> - mountPath: /var/log/apiserver/audit.log
      name: audit-log
      readOnly: false
> - name: audit-log
     hostPath:
      path: /var/log/apiserver/audit.log
      type: FileOrCreate

**Comment by arun2arunraj** [comment]
@arpitaashu : Have you got any fix for this ?

**Comment by arun2arunraj** [comment]
@mihailgmihaylov : We are also facing the same issue. once i have changed my configuration as per your recommendation, API Server pod is not coming online.

**Comment by rangsan** [comment]
I stuck at this so long. Can someone please provide the entire api-server static pod manifest file?  I cannot find the right configuration for hostPath and mountPath just like above comment from @arpitaashu . :(

**Comment by rangsan** [comment]
Ok guys @arun2arunraj @arpitaashu  .I've sorted it out. Here's my manifest.
```spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.118.181.166
    - --allow-privileged=true
    - --audit-log-maxage=1
    - --audit-log-maxbackup=1
    - --audit-log-maxsize=2
    - --audit-log-path=/var/log/kube-apiserver-audit/audit.log
    - --audit-policy-file=/etc/kubernetes/audit-policy.yaml
...
...
    volumeMounts:
    - mountPath: /var/log/kube-apiserver-audit
      name: audit-log
    - mountPath: /etc/kubernetes/audit-policy.yaml
      name: audit-policy
      readOnly: true
...
...
  volumes:
  - hostPath:
      path: /var/log/kube-apiserver-audit
      type: DirectoryOrCreate
    name: audit-log
```
```
-rw-r--r-- 1 root root 2095198 Jul 20 09:50 audit-2021-07-20T02-50-39.054.log
-rw-r--r-- 1 root root 1051370 Jul 20 09:50 audit.log

**Comment by qmloong** [comment]
> I am not sure if this is related, I had a similar issue recently with the rotation of kube-apiserver audit logs. The error I received, however was:
> 
> ```
> E0129 13:15:01.951796       1 metrics.go:96] Error in audit plugin 'log' affecting 1 audit events: can't rename log file: rename /var/log/kube-apiserver-audit.log /var/log/kube-apiserver-audit-2019-01-29T13-15-01.951.log: device or resource busy
> ```
> 
> It turned out that I was mounting only the file to the kube-apiserver pod and therefore the container was unable to rename it. You can check if this is your case also.
> 
> This fixed my issue:
> 
> ```
>    - hostPath:
> -      path: /var/log/kube-apiserver-audit.log
> +      path: /var/log/kube-apiserver-audit
> -       type: FileOrCreate
>      name: audit
> ```
   - hostPath:
-      path: /var/log/kube-apiserver-audit.log
+      path: /var/log/kube-apiserver-audit
-       type: FileOrCreate
     name: audit

try DirectoryOrCreate rather than FileOrCreate

**Comment by eduardoriveror** [comment]
Just had this issue, and the last comment solves it. But in my case, I originally set the volumeMount section that mounted the logfile in the container with the argument *readOnly: true*, so the container fail to rewrite the log file. Setting it with the ability to rewrite the file *readOnly: false* makes also the trick. It is also suggested [here](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)

```
volumeMounts:
  - mountPath: /etc/kubernetes/audit-policy.yaml
    name: audit
    readOnly: true
  - mountPath: /var/log/audit.log
    name: audit-log
    readOnly: false
```

**Comment by bimax** [comment]
Hi all,

I am having initial issue with the `permission denied` issue for the log collecting tool. I am using promtail instead of Splank but it does not change a lot. 
As I can see on the kubernetes node (where I have promtail and kubernetes master configured) this file is present and has permissions:
```
# ls -la
celkem 1155012
drwxr-xr-x. 2 root root      4096  9. dub 06.11 .
drwxr-xr-x+ 3 root root        19 13. bře  2024 ..
-rw-------. 1 root root  89139342  9. dub 06.32 kube-apiserver-log.json
-rw-------. 1 root root 104856070  9. dub 02.27 kube-apiserver-log-2025-04-09T06-27-19.033.json
-rw-------. 1 root root 104857580  9. dub 02.52 kube-apiserver-log-2025-04-09T06-52-10.536.json
-rw-------. 1 root root 104857365  9. dub 03.17 kube-apiserver-log-2025-04-09T07-17-06.933.json
-rw-------. 1 root root 104856381  9. dub 03.42 kube-apiserver-log-2025-04-09T07-42-11.503.json
-rw-------. 1 root root 104856682  9. dub 04.07 kube-apiserver-log-2025-04-09T08-07-06.048.json
-rw-------. 1 root root 104857407  9. dub 04.32 kube-apiserver-log-2025-04-09T08-32-01.528.json
-rw-------. 1 root root 104857029  9. dub 04.57 kube-apiserver-log-2025-04-09T08-57-02.762.json
-rw-------. 1 root root 104856598  9. dub 05.21 kube-apiserver-log-2025-04-09T09-21-40.289.json
-rw-------. 1 root root 104857556  9. dub 05.46 kube-apiserver-log-2025-04-09T09-46-28.989.json
-rw-------. 1 root root 104855708  9. dub 06.11 kube-apiserver-log-2025-04-09T10-11-19.558.json
```
kube-apiserver manifest looks like this:
```
    - --apiserver-count=3
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kube-apiserver-log.json
    - --audit-policy-file=/etc/kubernetes/audit-policy/apiserver-audit-policy.yaml
 ```
and I do not see any options here: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#log-backend or here https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ how I can set permissions mode for files being rotated.

I see [above](https://github.com/kubernetes/kubernetes/issues/70664#issuecomment-883010956) @rangsan has permissions 744 but I have no idea how this can be set.

Any advices here would be nice.
