### ISSUE TITLE
Cannot get TTLAfterFinished to work in 1.12.1

### ISSUE THREAD

**Issue by cliffburdick** [kubernetes/kubernetes#70685]
**What happened**:
Trying to enable the TTLAfterFinished feature gate to use the Job cleanup feature, and the feature does not work after enabling.
**What you expected to happen**:
The Job to be deleted 100s after hitting the Completed state.
**How to reproduce it (as minimally and precisely as possible)**:
I added the following to the api-server and controller manifests:
--feature-gates="TTLAfterFinished=true"
After a restart, both show the item present. Then launched a Job with "ttlSecondsAfterFinished: 100" set under .spec.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-34-generic
- Install tools: kubespray
- Others:

/kind bug

**Comment by ferrandinand** [comment]
Same behavior in 1.13.1 also in bare metal.
OS: Container Linux by CoreOS stable (1855.4.0)

**Comment by cliffburdick** [comment]
I believe this works. I read somewhere only the api server and controller needed the feature gate, but kubelet needs it as well. Once that was added, it worked.

**Comment by ferrandinand** [comment]
No, It is not working for bare metal in the specs I mention before.
The feature is ignored and failed jobs are not removed.

kubernetes 1.13.1 (bare metal)
OS: Container Linux by CoreOS stable (1855.4.0)
uname -a
`
Linux master-10-0-4-103 4.14.96-coreos #1 SMP Mon Jan 28 05:16:10 -00 2019 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux`

**Comment by iczman** [comment]
+1, also not working in minikube 0.34.1

`minikube start --vm-driver hyperkit --feature-gates=TTLAfterFinished=true`

**Comment by Doqnach** [comment]
It does seem to work for me:

```bash
$ minikube start --feature-gates="TTLAfterFinished=true"
$ kubectl apply -f my-cron.yml
cronjob.batch/my-cron-1 created
```
(where `my-cron.yml` contains `ttlSecondsAfterFinished`)

**Comment by janetkuo** [comment]
Thanks all for reporting this. Would you mind providing more details? For example, the output of `kubectl get job <name of the job you expect to be GC'd> -o yaml -n <namespace name>`.

**Comment by Doqnach** [comment]
Could it be that I have quotes around the feature-gate?

Also: https://github.com/kubernetes/minikube/issues/3805

**Comment by janetkuo** [comment]
Feature `TTLAfterFinished ` needs to be enabled for both API server and controller manager. To verify whether it's enabled, check the beginning of both apiserver log and controller-manager log and look for `TTLAfterFinished` to see if the feature gate is enabled.

**Comment by realpkya** [comment]
> I believe this works. I read somewhere only the api server and controller needed the feature gate, but kubelet needs it as well. Once that was added, it worked.

How did you specify `feature gate` for kubelet?

**Comment by realpkya** [comment]
> Could it be that I have quotes around the feature-gate?
> 
> Also: [kubernetes/minikube#3805](https://github.com/kubernetes/minikube/issues/3805)

I was facing the problem and can confirm now it's working fine in `v1.12.7`

**Comment by MrD2** [comment]
I found same problem 
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal runc[4455]: error: invalid argument "TTLAfterFinished=true" for "--feature-gates" flag: unrecognized key: TT
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: kube-apiserver.service: Service hold-off time over, scheduling restart.
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: Stopped kubernetes-apiserver.
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: kube-apiserver.service: Start request repeated too quickly.
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: Failed to start kubernetes-apiserver.
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: kube-apiserver.service: Unit entered failed state.
Apr 24 09:26:06 kube-qrhfws6uojdg-master-0.novalocal systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.

**Comment by liggitt** [comment]
Please see the instructions for enabling the feature in both the API server and controller manager, and for specifying the options in your API objects to make use of the feature.

/close

**Comment by SalmaSattar** [comment]
Hi, I am trying to enable --feature-gates="TTLAfterFinished=true" in kubernetes version 1.13. 
I tried with kubeadm. Got error saying --feature-gates unrecognized. 
I installed kube-apiserver. Tried enabling --feature-gates="TTLAfterFinished=true" . I get some certificate error. 

Can you some one please help with the steps to enable  --feature-gates="TTLAfterFinished=true. It would be great help. Thank you

**Comment by 3ch01c** [comment]
`TTLAfterFinished` not working for me either. Am I doing it right?

``` sh
$ sudo kubeadm init --pod-network-cidr=10.0.1.0/16 --feature-gates="TTLAfterFinished=true" --v=5
unrecognized feature-gate key: TTLAfterFinished
k8s.io/kubernetes/cmd/kubeadm/app/features.NewFeatureGate
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/features/features.go:144
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:316
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func3
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:191
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:183
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:139
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

``` sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by allenjol** [comment]
@dioguerra did your resolved this problem ,i have the same problem
