### ISSUE TITLE
Prevent `Comment` field conflicts in Godeps/Godeps.json

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#70686]
**What would you like to be added**:

Prevent `Comment` field conflicts in Godeps/Godeps.json

**Why is this needed**:

`godep` may generate different comments on same commit in same repo. It's annoying when updating dependencies. More discussion: https://github.com/kubernetes/kubernetes/pull/69976#pullrequestreview-167565874

`godep` uses `git describe --tags <commit>` to generate comment, different git versions or local configs will generate different results (latest git use dynamic abbreviation size by default which depends on repo state). And some repo may tag one commit with multiple names which results in multiple comments (depends on your repo state), e.g. 

- https://github.com/go-openapi/analysis/tree/v0.17.1
- https://github.com/go-openapi/analysis/tree/v0.17.2

/kind feature

**Comment by dims** [comment]
@cofyc have you thought about `core.abbrev` in the git config. we could use `git config --global core.abbrev` to check if this is set to say `12` and then bail out if it is not with a prompt to the user to set it using `git config --global core.abbrev 12`. (or ever save the older value at the beginning of the script and reset it at the end). Will this work for us and give us consistent comments?

**Comment by thockin** [comment]
Demanding I change my local git config seems hostile. Can't we embed git configs in the repo that override user-prefs?

**Comment by dims** [comment]
@thockin would the 2nd part be ok? ( save the older value at the beginning of the script and reset it at the end )

**Comment by neolit123** [comment]
@thockin @dims 

we can include a `.gitconfig` file in the repo that has the local setting of `12`:
```
[core]
	abbrev = 12
```

and then include it as part of the build process using this command:
```
git config --local include.path '../.gitconfig'
```

this generates these lines in the `.git/config` file:
```
[include]
	path = ../.gitconfig
```

the `abbrev = 12` setting from the custom config file will override the user repo settings stored in global or the local `.git/config` file.

**Comment by dims** [comment]
@neolit123 👍

**Comment by thockin** [comment]
Can we just put it in the .git/config of the repo?  Or I guess that won't work because godep will run `describe` in every repo we are vendoring...

Save and restore is awkward for this, too.  I guess I'd rather just tell users to set their config

**Comment by thockin** [comment]
OR ... we could vendor godep and fix it?

**Comment by neolit123** [comment]
> OR ... we could vendor godep and fix it?

ideally godep should be fixed.
using raw `git describe --tags` with the local repo abbreviation settings is quite bad.

**Comment by thockin** [comment]
realistically, fixing godeop is not impossible - it's effectively frozen upstream and we wrap it in scripts anyway.  I don't know if other repos besides k/k still use it

**Comment by thockin** [comment]
Oh, how about that.  We already vendor it, so forking it would be relatively minor.

**Comment by thockin** [comment]
Or we could send an upstream patch to add --abbrev=12 to the `git describe` cmd/

**Comment by neolit123** [comment]
looks like the PR for this was already up but unmerged:
https://github.com/tools/godep/pull/560/files
cc @filbranden 

i think the correct course is to just fork.

**Comment by neolit123** [comment]
i think it should be the same procedure as the klog repo:
https://github.com/kubernetes/org/issues/195

i.e. sig-arch as owner, possibly slightly different write-access and owners.
@dims WDYT?

**Comment by dims** [comment]
@neolit123 i would lean towards doing something in the shell scripts and not a full vendoring. but would support if someone wants to go the whole way

**Comment by thockin** [comment]
I don't think there's a script based solution - godep hard-codes the command to run with no extension-point.

We either:

a) demand users set abbrev=12 in their gitconfig
b) remove the hash portion (normalize)
c) fork godep and change this

If we want to fork godep, we should think hard about whether making it a new repo is appropriate.  We want to support a fork of godep EVEN LESS than we want to support a fork of glog.

**Comment by cblecker** [comment]
>OR ... we could vendor godep and fix it?

*pokes head up*

I may or may not have a branch burning a hole on my compy to do just that. The problem with messing with git configs is you don't just have to do it for k/k, but you have to do it for every repo that godep restores and clones down (**yuck**)

Let me clean up my branch and see how far that gets us.

**Comment by thockin** [comment]
There's a small group of individuals in our community who sign up for the dirtiest jobs, over and over.  I love you guys.

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/pull/70718
/shrug
