### ISSUE TITLE
Update docs to reflect StatefulSets can Autoscale

### ISSUE THREAD

**Issue by ObviousDWest** [kubernetes/kubernetes#70709]
According to the following issue/comment, and early testing, it appears that StatefulSets *are* able to participate in pod autoscaling. Presumably, this can also lead to cluster or instance group autoscaling if StatefulSet pods cannot be scheduled. https://github.com/kubernetes/kubernetes/issues/44033#issuecomment-386753262_

However, there are several misleading bits of documentation that indicate otherwise that should be updated, so folks are more aware of this feature:
* "kubectl help autoscale", does not list StatefulSet as a legal target.
* https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
* https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
* https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/

**Comment by ObviousDWest** [comment]
This doc may also be out of date:
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/horizontal-pod-autoscaler.md#scale-subresource

/sig doc

**Comment by soltysh** [comment]
> Do we need to support autoscale sts in kubectl?

Yes, you need to update https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/polymorphichelpers/canbeautoscaled.go to handle STS

**Comment by surajnarwade** [comment]
since https://github.com/kubernetes/kubernetes/pull/71103 is merged, we can close this :smile_cat: 
cc @juanvallejo

**Comment by juanvallejo** [comment]
@surajnarwade thanks

/close
