### ISSUE TITLE
Scheduler CPU usage hurting scalability?

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70708]
CI testing upgraded to golang 1.12.2 around 4am last night.

After that, the two gce-100 test runs failed: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19422

This was followed by two runs whose runtime was slightly (2 min) above average for the test: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19424

We need to verify whether the golang upgrade had a measureable effect on performance, or whether this is just a continuation of issue #69600  Unfortunately, the Perf dashboard is no help here (issue on that to come)

/kind flake
/priority important-soon
/sig scalability

attn:
@wojtek-t 
@shyamjvs 
@cblecker 
@AishSundar

**Comment by AishSundar** [comment]
FWIW, there were runs before the Go lang upgrade that ventured into the 43m mark as well, but it was an aberration vs the norm 

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19395

We are watching the job closely to see if the timing comes down at all or not.

**Comment by jberkus** [comment]
So times are continuing to average higher -- almost 10% longer runs than prior to the golang change.

Sadly, we can't get better granularity from the perf dashboard, so at this point we don't know and it looks like a blocker.

Escalting priority

/priority critical-urgent

**Comment by AishSundar** [comment]
@wojtek-t This is currently blocking Beta cut for 1.13. Please investigate this as priority. thanks

**Comment by BenTheElder** [comment]
> CI testing upgraded to golang 1.12.2 around 4am last night.

1.11.2* ?

**Comment by wojtek-t** [comment]
@jberkus @AishSundar - I looked into tests and i don't see correlation with golang upgrade.
The metrics look fine to me.

The problem that we observe is that scheduler is using more cpu now.
It started happening more than a week ago, so it's not related to the 1.11.2 golang upgrade (I don't know when we upgraded to 1.11.1 though).

I looked a bit into scheduler changes from last 2 weeks or so, and the only PRs that looked potentially a little bit suspcious are:
https://github.com/kubernetes/kubernetes/pull/70605
https://github.com/kubernetes/kubernetes/pull/70366

@bsalamat : 
1. does scheduler benchmark gather cpu-usage so that we can verify that? [I'm afraid it's not, just wanted to be sure]
2. are you aware of any change in the last couple weeks that may result in higher cpu-usage?

@jberkus @AishSundar - I don't consider this to be serious enough to be beta release blocker.

**Comment by wojtek-t** [comment]
I'm not lowering the priority, as I would like to see the results of today gce-scale-performance suite run.

**Comment by AishSundar** [comment]
Thanks @wojtek-t for the investigation. Go  was updated to [1.11.1 on Oct 3rd](https://github.com/kubernetes/kubernetes/commit/962fdbcbcafdeaa223fddefa7113d90e39371a16#diff-8188c017a3a4a9343bc9920417e2376b). the last Go 1.10.4 update was on Sep 18th.

One ques towards Beta cut is, should hold Beta until today's  gce-scale-performance suite runs, or do you think we can proceed with Beta before that with the signal we got from gce-100 job?

**Comment by bsalamat** [comment]
It is likely caused by #70366. I was afraid that it could potentially cause higher CPU usage in our benchmarks where there are not many unschedulable pods. We should revert it.

**Comment by AishSundar** [comment]
Thanks for the revert PR @bsalamat 

@wojtek-t meanwhile we [didnt get a run of the large scale-performance job today](https://testgrid.k8s.io/sig-release-master-blocking#gce-master-scale-performance). Can you please look into whats going on? Thanks

**Comment by AishSundar** [comment]
Thanks @BenTheElder thats mighty helpful. How do we get the job back in a good state? can we assume the rescheduled pod is good and that run will complete?

**Comment by BenTheElder** [comment]
Not sure, it might be OK, in the past we had issues with the previous pod's resources breaking the rescheduled pod. It should either be in an OK state now or the next run will be. 

Metadata for [252](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/252/) (`2018-11-07 14:22 PST`) and  [251](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/251/) (`2018-11-07 00:01 PST`) are both pod / ProwJob ID `4bb6bf52-e263-11e8-bcaa-0a580a6c0209` so it rescheduled about 2 hours in.

**Comment by krzyzacy** [comment]
we can make a GIANT dedicated node for scalability jobs...

**Comment by AishSundar** [comment]
@wojtek-t #70776 reverting the problematic feature merged yesterday and we have some new runs https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

We also got a new large scale run for 11/7 - https://testgrid.k8s.io/sig-release-master-blocking#gce-master-scale-performance

 can you look it is ok from performance and CPU consumption and then close this issue? Thanks

**Comment by jberkus** [comment]
Not solved, we're getting some GCE-100 failures because of this now, for example this one:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19500

**Comment by jberkus** [comment]
It looks like this flake started getting a lot more frequent on either 10/4 or 10/5: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-10&text=kube-scheduler%20is%20using

**Comment by bsalamat** [comment]
I am reverting the other suspicious PR as well.

**Comment by AishSundar** [comment]
Looks like the latest revert  #70837 worked ! The [gce-cos-master-scalability-100](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100) job has been stable that last day.

@wojtek-t can you chk and close this issue if you deem it fixed.

**Comment by AishSundar** [comment]
@wojtek-t are we ok to close this issue for 1.13? We had newer runs of scale-correctness, scale-performance and scalability-100 in the past few days. From looking at the overall timing, there seems to be no regression. But can you look at the perf dashboards and advise accordingly?

**Comment by mariantalla** [comment]
Hey @wojtek-t and @bsalamat , just a heads up that this recently failed. Here's [testgrid](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100) and [kubernator](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/19687).

It's probably a flake (I think that because [the diff](https://github.com/kubernetes/kubernetes/compare/5ac8be279...ce01e8377?) shows only a changelog change) but it may be worth a look as the error message is interesting.

Thoughts?

**Comment by bsalamat** [comment]
There has not been any notable changes recently and the test has passed after the failure. I looked at error message, it was about longer startup time than expected. Given that the tests have passed after, I guess it was a flake.

**Comment by jberkus** [comment]
We are still seeing this flake in gce-cos-scalability-100, but at this point I'm going to close this issue in favor of a new issue focused only on the current flake: #71760

/close
