### ISSUE TITLE
Godep update script deletes vendor file

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes/kubernetes#70711]
**What happened**:
I was following the instruction in https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md#updating-a-dep to update a dependency (golang.org/x/net dependency, #70663) and it deleted a vendor file, vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-04-01/compute/BUILD, which is completely unrelated to golang.org/x/net. I think it might be related to a recently merged PR #66648 that "Update Azure Go SDK".

Here is the observation I got, as reference:

> $ git status
> On branch gonet110
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   Godeps/Godeps.json
> 	modified:   vendor/BUILD
> 	deleted:    vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-04-01/compute/BUILD
> 	modified:   vendor/golang.org/x/net/context/context.go
> 	modified:   vendor/golang.org/x/net/html/atom/gen.go
> 	modified:   vendor/golang.org/x/net/html/atom/table.go
> 	modified:   vendor/golang.org/x/net/html/const.go
> 	modified:   vendor/golang.org/x/net/html/doc.go
> 	modified:   vendor/golang.org/x/net/html/token.go
> 	modified:   vendor/golang.org/x/net/http2/ciphers.go
> 	modified:   vendor/golang.org/x/net/http2/configure_transport.go
> 	modified:   vendor/golang.org/x/net/http2/server.go
> 	modified:   vendor/golang.org/x/net/http2/transport.go
> 	modified:   vendor/golang.org/x/net/http2/write.go
> 	modified:   vendor/golang.org/x/net/idna/BUILD
> 	modified:   vendor/golang.org/x/net/idna/idna.go
> 	modified:   vendor/golang.org/x/net/idna/tables.go
> 	modified:   vendor/golang.org/x/net/idna/trieval.go
> 	modified:   vendor/golang.org/x/net/proxy/per_host.go
> 	modified:   vendor/golang.org/x/net/proxy/socks5.go
> 
Among the change, this one in particular is not expected:
> 	modified:   vendor/BUILD
> 	deleted:    vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-04-01/compute/BUILD

In vendor/BUILD:
> $ git diff vendor/BUILD
> diff --git a/vendor/BUILD b/vendor/BUILD
> index 5d89686d80..0c853bc8a8 100644
> --- a/vendor/BUILD
> +++ b/vendor/BUILD
> @@ -15,7 +15,6 @@ filegroup(
>          "//vendor/bitbucket.org/ww/goautoneg:all-srcs",
>          "//vendor/cloud.google.com/go/compute/metadata:all-srcs",
>          "//vendor/cloud.google.com/go/internal:all-srcs",
> -        "//vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-04-01/compute:all-srcs",
>          "//vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute:all-srcs",
>          "//vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2017-10-01/containerregistry:all-srcs",
>          "//vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2017-09-01/network:all-srcs",
> 

**What you expected to happen**:
Is this the expected behavior that I am supposed to manually remove the unexpected change? 

**How to reproduce it (as minimally and precisely as possible)**:
On master head,
```
hack/run-in-gopath.sh hack/godep-restore.sh -v

hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/golang.org/x/net'
hack/run-in-gopath.sh go get -d golang.org/x/net/http2
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/golang.org/x/net/http2 checkout release-branch.go1.10'

hack/run-in-gopath.sh hack/godep-save.sh

./hack/update-staging-godeps.sh

Commit
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.2.110+5e45a103519dd0-dirty", GitCommit:"5e45a103519dd06897d7171eb09ec534d419fb38", GitTreeState:"dirty", BuildDate:"2018-10-26T22:32:07Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Debian GNU/Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by neolit123** [comment]
/sig azure
@kubernetes/sig-azure  please delegate to other sigs if applicable.

**Comment by krzyzacy** [comment]
cc @fejta @cblecker (assume k8s dep works the same way as test-infra, then how it passed presubmit?)

**Comment by feiskyer** [comment]
The PR  #70663 has been merged now. No issues any more?

**Comment by cblecker** [comment]
Things are running fine in CI. If you're still experiencing issues, please let us know.

/close
