### ISSUE TITLE
k8s 健康监测bug

### ISSUE THREAD

**Issue by gitplyx** [kubernetes/kubernetes#70721]
k8s 集群中健康监测开启，总是自动重启pod
无法看到详细日志是什么原因引起的，寻求帮助，谢谢
健康监测是否有详细日志说明

**Comment by Pingan2017** [comment]
可以看下pod的事件

**Comment by D-PENG** [comment]
看下describe的日志

**Comment by zjj2wry** [comment]
@gitplyx it would be better provide more information use kubectl get -o yaml and describe command

**Comment by WanLinghao** [comment]
@gitplyx, please check if your host has any proxy set. try this:https://github.com/kubernetes/kubernetes/pull/68663

**Comment by neolit123** [comment]
@gitplyx 

please translate the issue description in english if possible.

**Comment by gitplyx** [comment]
查看describe 日志都很少，基本上看不出问题出现在那

**Comment by WanLinghao** [comment]
你至少把pod的配置信息以及describe的信息贴出来吧，你这就两句话怎么debug啊．
