### ISSUE TITLE
Add debug info: scheduler extenders's score and its name for each pod

### ISSUE THREAD

**Issue by hex108** [kubernetes/kubernetes#70723]
**What would you like to be added**:
In pkg/scheduler/core/generic_scheduler#`PrioritizeNodes` , add some debug info: each scheduler extender's score and its name for each pod, e.g.
```
--- a/pkg/scheduler/core/generic_scheduler.go
+++ b/pkg/scheduler/core/generic_scheduler.go
@@ -730,6 +730,9 @@ func PrioritizeNodes(
                                mu.Lock()
                                for i := range *prioritizedList {
                                        host, score := (*prioritizedList)[i].Host, (*prioritizedList)[i].Score
+                                       if glog.V(10) {
+                                               glog.Infof("%v -> %v: %v, Score: (%d)", pod.Name, host, ext.Name(), score)
+                                       }
                                        combinedScores[host] += score * weight
                                }
                                mu.Unlock()

```

And we need add a function(e.g. `Name()`) in interface `SchedulerExtender` to get extender's name or similar identity. For `HTTPExtender`, it might be enough to return its url `extenderURL`.

**Why is this needed**:
If there are two or more scheduler extenders configured for scheduler(and we have now), it will be very useful to debug why kubelet nodes get so high/low score.

/kind feature

**Comment by bsalamat** [comment]
@hex108 Why don't you send a PR instead?

**Comment by hex108** [comment]
@bsalamat Thanks. PR #70783 is sent. PTAL.
