### ISSUE TITLE
initContainers does not accept imagePullSecrets

### ISSUE THREAD

**Issue by opme** [kubernetes/kubernetes#70732]
**What happened**:
initContainers does not accept imagePullSecrets.   No way to configure a secret so initContainers can connect to a private repository.

**What you expected to happen**:
Adding an imagePullSecrets under spec should work for both container and initContainers

**How to reproduce it (as minimally and precisely as possible)**:
Have a template with both container and initContainer.  Define a imagePullSecret under spec.  Use a private repository where you authenticate with secret.

You will get imagePullBackoff and cannot connect to repository for your images that need to be pulled from your init containers.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.11
- Cloud provider or hardware configuration: Docker EE with Kubernetes, DTR (Docker Trusted Registry)
- OS (e.g. from /etc/os-release): alpine
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by Twister915** [comment]
Attempted to investigate this, and in case it's helpful to anyone else who wants to work on this:

https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L686

It appears init containers are created with the exact same call that other containers are, in release 1.8.x (checked 1.8.15 on that branch and 1.8.11 as specified by user).

**Comment by opme** [comment]
Let me know if you need any information to reproduce.   We can upgrade to 1.8.15.  I have heard it is working ok in v1.10.3.

**Comment by zjj2wry** [comment]
I saw the code of 1.8 and didn't see any difference in processing imagePullSecret

**Comment by aseempatni** [comment]
I'm on v1.12.6-3+602d21b1679fa5. init containers still don't seem to use imagePullSecrets from the spec.

**Comment by g9rga** [comment]
Have the same issue(

**Comment by Constantin07** [comment]
I'm experiencing the same issue on v1.11.8 (EKS).

**Comment by Dysproz** [comment]
It still does not work. :<
initContainers can't pull images from private repo. 
`unauthorized: authentication required`
/reopen

**Comment by jeanluclariviere** [comment]
/reopen 
this still isn't working: `manifests/latest: no basic auth credentials`

**Comment by michalpiasecki1** [comment]
`      initContainers:
        - name: wait-for-database
          image: image-name
          command: ["/usr/local/bin/wait-for-main-controller-database.sh", "postgresql"]
          imagePullPolicy: Always
          imagePullSecrets:
            - name: regcred`

ends with 

error validating data: ValidationError(Deployment.spec.template.spec.initContainers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by armab** [comment]
I can't confirm this issue is still present. At least in K8s `v1.15.2`.

I uploaded an image to private Docker registry and tried to re-use that privately hosted image in initContainers. The engine was able to pull it.

After checking, `spec.imagePullSecrets` secrets were used for both `spec.containers` and `spec.initContainers`.

**Comment by ah584d** [comment]
i have exactly the same issue, will it be fixed?

**Comment by dims** [comment]
cc @tedyu

**Comment by jeanluclariviere** [comment]
I just want to mention that I was able to resolve this in the end and am not encountering the no auth problem anymore as I previously stated. Sorry I forgot to come back in September and clarify - I don't remember what I was working on at the time unfortunately, I was just doing some basic testing at the time, so I would urge folks who are encountering this issue to post their configurations as I believe this can be solved.

**Comment by seanmetrix** [comment]
seems like it is working now - I've got all private repos for both containers and initContainers and it works with imagePullSecrets defined in the spec block.

**Comment by ah584d** [comment]
Yes guys , it works well now, i forgot to configure "Collaborators" in dockerhub, so the initContainer was not able to pull the image.
thanks

**Comment by qinmaye** [comment]
any progress about this?

**Comment by dpoetzsch** [comment]
> ```
>       initContainers:
>         - name: wait-for-database
>           image: image-name
>           command: ["/usr/local/bin/wait-for-main-controller-database.sh", "postgresql"]
>           imagePullPolicy: Always
>           imagePullSecrets:
>             - name: regcred
> ```
> 
> ends with
> 
> ```
> error validating data: ValidationError(Deployment.spec.template.spec.initContainers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
> ```

The fix is: `imagePullSecrets` must be specified on top level under `spec.template.spec`. It then is used for both the initContainers and normal containers.

**Comment by flyte** [comment]
> The fix is: `imagePullSecrets` must be specified on top level under `spec.template.spec`. It then is used for both the initContainers and normal containers.

What if you need different `imagePullSecrets` for your initContainers and normal containers?

**Comment by dpoetzsch** [comment]
> What if you need different imagePullSecrets for your initContainers and normal containers?

I don't see a problem with specifying both secrets together at top level. Am I missing something?

**Comment by flyte** [comment]
Does it keep trying each individual secret until one works? When using, for
example, GitLab deployment keys, each image has its own credentials, but
the registry address is always registry.gitlab.com.

**Comment by ivorscott** [comment]
This is still an issue. I have an initContainers container making use of a private image migration. With in containers I have a public image. Even with imagePullSecrets specified it doesn't work. I have a hunch that if the images are public in the pod template than the imagePullSecrets won't even be used.

**Comment by abdennour** [comment]
still issue persistent.
i have k8s 1.17 and i can confirm that.

**Comment by sniranjan** [comment]
Have the same issue in v1.20

**Comment by m-stojanovic** [comment]
Issue still present with 1.22.0 version, not able to pull the image for the init containers even if
```
      imagePullSecrets:
      - name: ecr-registry-secret
```
is specified under spec.template.spec @zouyee

**Comment by Jyny** [comment]
Having same issue, can we reopen this?
/reopen

**Comment by GeorgeTsilias** [comment]
This issue is still apparent on K8s v1.21+.


 
    spec:

      imagePullSecrets:
      
      - name: {{ imagePullSecrets }}
      
      containers:
      
        image: "{{ repository }}:{{ image.tag }}"
        
        imagePullPolicy: Always
        
        name: foo 
        
      initContainers:
      
      - name: init-wait
      
        image: "{{ repository }}:{{ image.tag}}"
        
        command: ["/wait.sh"]
        



Specifying the imagePullSecrets under  `spec.template.spec.initContainers`  produces an 

`error validating data: ValidationError(Deployment.spec.template.spec.initContainers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false`  error.

**Comment by Martin-Hogge** [comment]
Same issue on kubernetes version `1.19.14-gke.1900`.

**Comment by DIOLLIA** [comment]
So what's news? where is official comment..&

**Comment by DIOLLIA** [comment]
> 

No, it didn't work, not on` spec.imagePullSecrets`
and not on
`spec.initContainers.imagePullSecrets`

**Comment by nodesocket** [comment]
I think the reason why this issue breaks and then seems to magically work is if the Kubernetes worker nodes download the Docker image from the root `containers` then the next time `initContainers` runs it has the Docker image cached _(no auth needed)_. I was able to replicate this error if the Docker image is brand new _(not on any workers)_ and failing to auth using `imagePullSecrets`.

```
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
```

Running:

```
Kubernetes v1.20.7
```

**Comment by doctorpangloss** [comment]
This should be reopened. `initContainers` are ignoring `imagePullSecrets` on 1.6.8 `containerd`, Kubernetes 1.26.1

**Comment by doctorpangloss** [comment]
Issue can be closed again. Cannot reproduce, resolved other ways.
