### ISSUE TITLE
Flag --pod-manifest-path has been deprecated, but alternative going forward is not clear?

### ISSUE THREAD

**Issue by joshuacox** [kubernetes/kubernetes#70745]
**What happened**:

While following [this page](https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/) you set `/etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf` using this:

```
cat << EOF > /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
[Service]
ExecStart=
ExecStart=/usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true
Restart=always
EOF

systemctl daemon-reload
systemctl restart kubelet
```
but kubelet complains about this:

from `journalctl -xeu kubelet`:

```
Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

so looking at [this page](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) it points to this [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go) which does not have a `PodManifestPath`  but it does have a `StaticPodPath` which kind of sounds the same but certainly not exact.

and setting the config file to:

```
[Service]
ExecStart=
ExecStart=/usr/bin/kubelet  --config=/var/lib/kubelet/config.yaml
Restart=always
```

and `/var/lib/kubelet/config.yaml`:

```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 127.0.0.1
staticPodPath: /etc/kubernetes/manifests
```

ends up with:

```
Nov 07 13:15:09 testymaster1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Nov 07 13:15:09 testymaster1 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
Nov 07 13:15:09 testymaster1 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Nov 07 13:15:09 testymaster1 kubelet[3038]: I1107 13:15:09.286320    3038 server.go:408] Version: v1.12.2
Nov 07 13:15:09 testymaster1 kubelet[3038]: I1107 13:15:09.286902    3038 plugins.go:99] No cloud provider specified.
Nov 07 13:15:09 testymaster1 kubelet[3038]: W1107 13:15:09.287303    3038 server.go:553] standalone mode, no API client
Nov 07 13:15:09 testymaster1 kubelet[3038]: F1107 13:15:09.289992    3038 server.go:262] failed to run Kubelet: no client provided, cannot use webhook authentication
Nov 07 13:15:09 testymaster1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Nov 07 13:15:09 testymaster1 systemd[1]: kubelet.service: Unit entered failed state.
Nov 07 13:15:09 testymaster1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**What you expected to happen**:

kubelet to run

**How to reproduce it (as minimally and precisely as possible)**:

run [this script](https://gist.github.com/joshuacox/fc629fe4001cd7fd2bb1dcf2db40e2a8) on a freshly provisioned xenial host:

```
bash test-kubeletconfig.sh  10.0.0.6
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

packer built xenial KVM images using [kubash](https://kubash.org/)

```
kubash yaml2cluster -n testy ~/testy-cluster.yaml
kubash -n testy -y provision
```

From [this yaml](https://gist.github.com/joshuacox/aaebb3d1327cfdaef5a166e49959405e) file defining the cluster. Or [this one](https://gist.github.com/joshuacox/0e69650b0b2cdbeb79ab73e67f28d8ff) with fully separate etcd VMs.

- OS (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):

```
Linux testymaster1 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:

[kubash](https://kubash.org/) of which I am the author, and this is only in regards to kubelet at the moment as I am trying to debug my external etcd provisioning which I have another issue [here](https://github.com/kubernetes/website/issues/10808)

- Others:

/kind bug

**Comment by joshuacox** [comment]
/sig cluster-lifecycle  @luxas @neolit123 sorry if I mislabeled, I am just using the same label from my other [issue](https://github.com/kubernetes/website/issues/10808), feel free to correct.

**Comment by neolit123** [comment]
using the kubelet deprecated flags is what we do in kubeadm ATM.
you should ignore the warning for now.
we have tracking issues to address these eventually.
https://github.com/kubernetes/kubeadm/issues/949

/close

**Comment by lethargosapatheia** [comment]
Sorry to re-open this issue, but I don't understand what was actually changed. I also have this issue using the official documentation referenced by the op, and there are also two other warnings related to `--address` and `--cgroup-driver` (for which I've found the configuration parameters, although for `--pod-manifest-path` not):
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

Should I ignore the warning for `--pod-manifest-path`? And if yes, does that mean that it works nonetheless?

**Comment by lethargosapatheia** [comment]
Any news on this? I actually found this thread again after forgetting about this and then coming across it again because of the upgrade to 1.27 which removed some flags (such as `--container-runtime`).

**Comment by jayunit100** [comment]
im also wondering this.... we do have the kubeletconfig ? but i think some docs still say to use https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/ the `--pod-manifest-path` ?

**Comment by jayunit100** [comment]
i filed https://github.com/kubernetes/kubernetes/issues/120292 so that the kubelet logs this explicitly esp in cases that its not listening on /etc/kubernetes/manifests which ... is a possibility.
