### ISSUE TITLE
Kubelet should not consume Environment Variables

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#70767]
The kubelet uses a [versioned, kubernetes-style configuration](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L62).  As part of this migration, folks in sig-node [removed using the global flag set](https://github.com/kubernetes/kubernetes/pull/57613) in favor of explicitly defining the flags the kubelet accepts.  Environment variables similarly share a global, unversioned namespace.

The kubelet should call `os.Clearenv` when it starts up to maintain control of its api surface and thereby ensure we follow api compatibility guarantees.  If there are environment variables we need, we should parse them before `os.Clearenv`, and pass them as explicit configuration to the consumer.

cc @mtaufen @liggitt @kubernetes/sig-node-bugs 
/priority important-longterm
/area kubelet

**Comment by mtaufen** [comment]
Good idea. Run the cluster and node e2e suites with this modification and see what breaks?

**Comment by BenTheElder** [comment]
Is there support in kubelet config for $HTTP_PROXY and friends?

**Comment by tedyu** [comment]
@dashpole @mtaufen @BenTheElder 
Please comment whether the clearing of environment variables at the start of kubelet should be pursued.

Thanks
