### ISSUE TITLE
NodeInfoManager should use informers to cache CSINodeInfo objects

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#70773]
**What would you like to be added**:
NodeInfoManager should use informers to cache CSINodeInfo objects to reduce load on API Server

/sig storage
/cc @verult @saad-ali

/kind feature

**Comment by davidz627** [comment]
/remove-lifecycle rotten
/cc @msau42 @xing-yang 
not sure if related to current work for `CSIDriver` but just flagging this in case

**Comment by msau42** [comment]
@xing-yang 's PR is not addressing this but will help.

**Comment by davidz627** [comment]
related PR referenced above: https://github.com/kubernetes/kubernetes/pull/75129

**Comment by davidz627** [comment]
/remove-lifecycle stale
still required

**Comment by davidz627** [comment]
/remove-lifecycle stale
still required

**Comment by msau42** [comment]
We're tracking this as a nice to have for CSI topology GA

**Comment by davidz627** [comment]
/cc @tedyu 
expressed interest in this

**Comment by msau42** [comment]
cc @mucahitkurt, who's been helping me on a lot of the topology tasks, to coordinate efforts

**Comment by tedyu** [comment]
It seems ControllerContext is needed in order to get hold of storageinformers.CSINodeInformer .

After initial check of pkg/volume/csi/nodeinfomanager/nodeinfomanager.go , it doesn't reference ControllerContext now.

**Comment by msau42** [comment]
kubelet uses a different way of initializing kubeclient/informers and will be different than kube-controller-manager. You will probably want to follow what we did to add informers for CSIDriver in kubelet: https://github.com/kubernetes/kubernetes/blob/7d40536c8184d7b70e4dc3c27d9acc42b5b32d8e/pkg/kubelet/volume_host.go#L73

**Comment by tedyu** [comment]
See if the following is on track:
```
@@ -378,8 +379,12 @@ func (nim *nodeInfoManager) tryUpdateCSINode(
        driverNodeID string,
        maxAttachLimit int64,
        topology map[string]string) error {
+       const resyncPeriod = 0
+       informerFactory := informers.NewSharedInformerFactory(csiKubeClient, resyncPeriod)
+       csiNodeInformer := informerFactory.Storage().V1beta1().CSINodes()
+       csiNodeLister := csiNodeInformer.Lister()
+       nodeInfo, err := csiNodeLister.Get(string(nim.nodeName))

-       nodeInfo, err := csiKubeClient.StorageV1beta1().CSINodes().Get(string(nim.nodeName), metav1.GetOptions{})
        if nodeInfo == nil || errors.IsNotFound(err) {
                nodeInfo, err = nim.CreateCSINode()
        }
```
There are a bunch of tests in nodeinfomanager_test.go failing which I will investigate.

**Comment by msau42** [comment]
I think it is better to initialize and pass through the informer during kubelet initialization rather than at runtime on every call.  See above comment on where to start.

**Comment by tedyu** [comment]
I was thinking about obtaining the informer in nodeInfoManager#InstallCSIDriver.
But it seems updateCSINode is only called by nodeInfoManager#InstallCSIDriver.

**Comment by tedyu** [comment]
```
@@ -123,7 +125,12 @@ func (nim *nodeInfoManager) InstallCSIDriver(driverName string, driverNodeID str
        }

        if utilfeature.DefaultFeatureGate.Enabled(features.CSINodeInfo) {
-               err = nim.updateCSINode(driverName, driverNodeID, maxAttachLimit, topology)
+               const resyncPeriod = 0
+               csiKubeClient := nim.volumeHost.GetKubeClient()
+               informerFactory := informers.NewSharedInformerFactory(csiKubeClient, resyncPeriod)
+               csiNodeInformer := informerFactory.Storage().V1beta1().CSINodes()
+               csiNodeLister := csiNodeInformer.Lister()
+               err = nim.updateCSINode(driverName, driverNodeID, maxAttachLimit, topology, csiNodeLister)
                if err != nil {
                        return fmt.Errorf("error updating CSINode object with CSI driver node info: %v", err)
                }
@@ -351,7 +358,8 @@ func (nim *nodeInfoManager) updateCSINode(
        driverName string,
        driverNodeID string,
        maxAttachLimit int64,
-       topology map[string]string) error {
+       topology map[string]string,
+       lister v1beta1.CSINodeLister) error {

        csiKubeClient := nim.volumeHost.GetKubeClient()
        if csiKubeClient == nil {
@@ -360,7 +368,7 @@ func (nim *nodeInfoManager) updateCSINode(

        var updateErrs []error
        err := wait.ExponentialBackoff(updateBackoff, func() (bool, error) {
-               if err := nim.tryUpdateCSINode(csiKubeClient, driverName, driverNodeID, maxAttachLimit, topology); err != nil {
+               if err := nim.tryUpdateCSINode(csiKubeClient, driverName, driverNodeID, maxAttachLimit, topology, lister); err != nil {
                        updateErrs = append(updateErrs, err)
                        return false, nil
                }
@@ -377,9 +385,10 @@ func (nim *nodeInfoManager) tryUpdateCSINode(
        driverName string,
        driverNodeID string,
        maxAttachLimit int64,
-       topology map[string]string) error {
+       topology map[string]string,
+       lister v1beta1.CSINodeLister) error {
+       nodeInfo, err := lister.Get(string(nim.nodeName))

-       nodeInfo, err := csiKubeClient.StorageV1beta1().CSINodes().Get(string(nim.nodeName), metav1.GetOptions{})
        if nodeInfo == nil || errors.IsNotFound(err) {
                nodeInfo, err = nim.CreateCSINode()
        }
```
nodeinfomanager_test needs some refactoring to accommodate the above change.

**Comment by msau42** [comment]
nodeInfoManager#InstallCSIDriver is not the right place to initialize the informer. It is called every single time a CSI driver is installed.  Instead, we want to initialize the informer during kubelet initialization.

**Comment by tedyu** [comment]
Looking up the call chain, operation_executor.go :
```
		oe.operationGenerator.GenerateRegisterPluginFunc(socketPath, foundInDeprecatedDir, timestamp, pluginHandlers, actualStateOfWorld)
```
which is called by reconciler#reconcile

It seems reconciler#Run is called by a few classes.

**Comment by msau42** [comment]
I spoke to liggitt and he explained that it's not always good to use informers.

In this case, we have multiple factors that would argue in favor of *not* using informers:
* There's a CSINode object per Node in the cluster, but kubelet only needs 1 of them. In large clusters with 1000s of nodes, that means every node opens a watch and is filtering 1000s of unneeded objects. Informers would actually significantly increase load on the apiserver, not reduce.
* CSINode objects are only updated when drivers are installed or uninstalled, which doesn't happen often in a normal cluster (drivers are usually installed during cluster bootstrap)
* We do not actively reconcile updates to CSINode objects in kubelet. We only Get() them when we're trying to register/unregister a driver.

So for these reasons, we should not switch to using CSINode informers in kubelet. Sorry for the inconvenience. This was not immediately obvious to me, but makes a lot of sense now.

**Comment by davidz627** [comment]
Lets remove the TODO from the codebase (if there exists one) then and we can consider this issue closed

**Comment by msau42** [comment]
Didn't find any TODOs related to this.
/close
