### ISSUE TITLE
Failing Test: [sig-storage] Mounted flexvolume expand[Slow] Should verify mounted flex volumes can be resized

### ISSUE THREAD

**Issue by mortent** [kubernetes/kubernetes#70774]
**Which jobs are failing**: gce-cos-master-slow

**Which test(s) are failing**: [sig-storage] Mounted flexvolume expand[Slow] Should verify mounted flex volumes can be resized

**Since when has it been failing**: 11/07/2018

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-slow

**Reason for failure**:
Long error message, but seems like it failed to create a deployment:
_Failed creating deployment deployment "deployment-cc8adc2b-e2de-11e8-bc1f-0a580a3c13e1" failed to complete_

**Anything else we need to know**:
Seems like this is the offending PR: https://github.com/kubernetes/kubernetes/pull/70667
This is a priority as it is release-blocking: https://github.com/kubernetes/kubernetes/pull/70667#issuecomment-436821032

/kind failing-test
/sig storage
/priority important-soon
/cc @aniket-s-kulkarni

**Comment by aniket-s-kulkarni** [comment]
@mortent Could you include the output leading up to the error message please? It seems to work in my testing and dev env, and I'm wondering it there is something that was overlooked in the test case thats causing it to fail. The output and complete error message would help to figure that out.

**Comment by mortent** [comment]
@aniket-s-kulkarni You can get the logs for all run through the testgrid here: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-slow. Just click on any of the boxes in the column for the test run you want to look at.
The logs for the latest run is here: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/21549

**Comment by aniket-s-kulkarni** [comment]
@mortent thanks I'm looking at the logs to see what is going wrong.

**Comment by aniket-s-kulkarni** [comment]
It looks like, the the problem is the e2e test wasn't installing the dummy flex driver on the master when the flex driver was _attachable_. I will submit a fix for it.

**Comment by msau42** [comment]
In your fix, make sure to skip environments where master install is not possible, like gke

**Comment by AishSundar** [comment]
@aniket-s-kulkarni @gnufied is there an ETA for this to be fixed?

**Comment by gnufied** [comment]
@aniket-s-kulkarni is working on a fix. I was hoping if it gets done today but it doesn't tomorrow,  we will revert PR that introduced e2e for now.

**Comment by aniket-s-kulkarni** [comment]
@msau42 yes. The test skips everything except `aws`, `gce` and `local`. I've made the change and I am trying out one run after which I will raise the PR.

**Comment by aniket-s-kulkarni** [comment]
@AishSundar @gnufied I have raised the PR for this. https://github.com/kubernetes/kubernetes/pull/70869

**Comment by AishSundar** [comment]
/reopen
Keeping this open until we see the test pass in the dashboards

**Comment by aniket-s-kulkarni** [comment]
OK sounds good.
