### ISSUE TITLE
local-up-cluster.sh: install CSI CRDs

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#70791]
**What would you like to be added**:

https://github.com/kubernetes/kubernetes/pull/70193/ added a new addon to addon manager "that automatically installs CSI CRDs if CSIDriverRegistry or CSINodeInfo feature gates are true". But this is either broken or this addon manager isn't active in a cluster brough up with:
```
ALLOW_PRIVILEGED=1 FEATURE_GATES="CSIPersistentVolume=true,MountPropagation=true,VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true"  hack/local-up-cluster.sh -O
```

This should work automatically also for such local clusters.

**Why is this needed**:

The CSI E2E tests are now expecting that the cluster has the CRDs and fail when that isn't the case.

/kind feature
(or perhaps a bug, not sure)

/cc @saad-ali

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
/assign @saad-ali
