### ISSUE TITLE
Update heketi dependency after licensing issues are fixed

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#70802]
Please see discussion in:
- https://github.com/heketi/heketi/issues/1279
- https://github.com/kubernetes/kubernetes/issues/35557#issuecomment-436973405

Once things are fixed we need to update k/k with latest from heketi repo

Alternative : Drop GlusterFS in-tree plugin

**Comment by dims** [comment]
cc @AishSundar

**Comment by AishSundar** [comment]
/cc @nikopen 

@nikopen this is a critical issue we are tracking for 1.13.

**Comment by nikopen** [comment]
ack, I've read the background. 

Should expect the new version to go in by early next week so there's some days between it and code freeze for CI.

**Comment by AishSundar** [comment]
https://github.com/heketi/heketi/issues/1279 is now closed. @childsb we should be good to pull the changes into k/k right?

**Comment by AishSundar** [comment]
ah I see https://github.com/kubernetes/kubernetes/pull/70811 in progress. Thanks @humblec

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/pull/70811 has merged.

/close
