### ISSUE TITLE
[sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: gcePD [Serial] should provision storage

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#70832]
**Which jobs are failing**: gce-new-master-upgrade-cluster

**Which test(s) are failing**: [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: gcePD [Serial] should provision storage

**Since when has it been failing**: Today (Nov. 8)

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster

**Reason for failure**:

Test is timing out

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:112
Expected error:
    <*errors.errorString | 0xc422dae9f0>: {
        s: "Gave up after waiting 15m0s for pod \"pvc-volume-tester-nbl9f\" to be \"success or failure\"",
    }
    Gave up after waiting 15m0s for pod "pvc-volume-tester-nbl9f" to be "success or failure"
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:1256
```

Alerting here because this appears to be a new test.

**Anything else we need to know**:

May be related to #70549, or #70760 

/kind failing-test
/sig storage
/assign @davidz627 
/priority critical-urgent
/milestone v1.13

**Comment by davidz627** [comment]
/cc @msau42 

seem to recall you mentioning this in a separate issue as due to a test-infra failure. Not sure if this is the same thing

**Comment by msau42** [comment]
No that was in the serial suite where the test-log showed some boskos error.  I don't see the same kubelet restart test being run in the upgrade suite, so I suspect it's a different issue.

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2612?log#log

**Comment by AishSundar** [comment]
this test super flaky i.e., passes just 50% of the time. @davidz627 any update?

**Comment by AishSundar** [comment]
This test passed for a 3 runs now. will watch a bit more before we close this out.

**Comment by davidz627** [comment]
looked into the test flake a bit more, the error message i'm seeing:
```
FailedMount: MountVolume.WaitForAttach failed for volume "pvc-0a928b69-e52c-11e8-abde-42010a800002" : volume projects/k8s-gce-gci-1-6-mstr-ctl-skew/zones/us-central1-f/disks/pvc-0a928b69-e52c-11e8-abde-42010a800002 has GET error for volume attachment : resource name may not be empty
```
This looks like the same issue described here: https://github.com/kubernetes/kubernetes/issues/65246
that @pohly is looking into

**Comment by jberkus** [comment]
@davidz627 should I close this in favor of the other issue, then?

**Comment by davidz627** [comment]
yes, lets keep the context in one issue. I believe this is the same

**Comment by AishSundar** [comment]
/close

We are tracking progress of this in #65246
