### ISSUE TITLE
Pods stay in Pending for a long time

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#70835]
**What happened**:

Pods stay in Pending status for a long time.

Here is my pod

```
# kubectl -n services get pods -o wide
NAME                                        READY     STATUS    RESTARTS   AGE       IP        NODE
redis-65dcfbfccc-dtk8x                      0/1       Pending   0          19h       <none>    9.193.199.43
```

And from kubelet log
```
Nov  8 11:20:11 inmbzicpsanw08 hyperkube[1599]: I1108 11:20:11.726517    1599 config.go:405] Receiving a new pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:32 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:32.408191    1599 kubelet.go:1861] SyncLoop (ADD, "api"): "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:32 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:32.493868    1599 kubelet_pods.go:1375] Generating status for "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:32 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:32.504139    1599 volume_manager.go:347] Waiting for volumes to attach and mount for pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:34 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:34.306831    1599 volume_manager.go:380] All volumes are attached and mounted for pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:35 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:35.476785    1599 kuberuntime_manager.go:385] No sandbox for pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)" can be found. Need to start a new one
Nov  9 06:25:35 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:35.476823    1599 kuberuntime_manager.go:570] computePodActions got {KillPod:true CreateSandbox:true SandboxID: Attempt:0 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[]} for pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)"
Nov  9 06:25:35 inmbzicpsanw08 hyperkube[1599]: I1109 06:25:35.476890    1599 kuberuntime_manager.go:579] SyncPod received new pod "redis-65dcfbfccc-dtk8x_services(2826d997-e31a-11e8-b5cb-005056bf37ac)", will create a sandbox for it
```

As you seen from kubelet log, kubelet get the pods at `Nov  8 11:20:11`, but start the sync loop at `Nov  9 06:25:32`. Why takes so long for kubelet to take action? Sounds like the `configCh` https://github.com/kubernetes/kubernetes/blob/v1.10.0/pkg/kubelet/kubelet.go#L1846 is hanging at that time, kubelet main sync up thread did not detect events from that channel.

**What you expected to happen**:

After scheduled Pods should be created by kubelet immediately.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.0
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release):  Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by dchen1107** [comment]
@liqlin2015 between Nov  8 11:20:11 and Nov  9 06:25:32, are there anything happened to your node? Any logs between two times in Kubelet? Did Kubelet process any other events between them?

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-node-bugs

**Comment by liqlin2015** [comment]
@dchen1107 Kubelet did not process any other sync event at that time. The last sync event is housekeeping. So I suspect something was hanging when we do clean up in housekeeping. Well it's difficult to find out where it was hanging from code and log (I have set log level to `--v=4`).

In the time window, it did print some log like attaching volume failed, etc.
