### ISSUE TITLE
CoreDNS configured to run on masters

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#70851]
For some reason the coredns configuration has a master toleration, where kube-dns did not.  Is there some reason for the discrepancy?

kube-dns: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube-dns/kube-dns.yaml.base#L90
coredns: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in#L111

Spotted by @bhegazy in https://github.com/kubernetes/kops/pull/5917

**Comment by chrisohaver** [comment]
I believe this was replicated from kubeadm's default kube-dns configuration.

https://github.com/kubernetes/kubernetes/blob/52de5c55e37c6b50cf640470752d9c9a56441705/cmd/kubeadm/app/phases/addons/dns/manifests.go#L175

**Comment by MarcPow** [comment]
@chrisohaver If CoreDns doesn't tolerate master taints, but can only run on (Linux) masters in the typical Windows/Linux hybrid cluster configuration - how will clusters using CoreDns function with a bunch of special configuration?

**Comment by chrisohaver** [comment]
@marcpow, if someone has a special configuration like that they will need to adjust the coredns deployment config. We can’t make a single default setting work for all possible edge cases. IMO, we should aim to make the coredns default config work for the most common case. I wouldn’t call windows/Linux hybrid clusters “typical” quite yet.

**Comment by MarcPow** [comment]
> @MarcPow, if someone has a special configuration like that they will need to adjust the coredns deployment config. We can’t make a single default setting work for all possible edge cases. IMO, we should aim to make the coredns default config work for the most common case. I wouldn’t call windows/Linux hybrid clusters “typical” quite yet.

Makes sense.

I was trying to think ahead to the hybrid conformance tests for 1.13/1.14 but in practice -
(a) If I'm understanding it correctly, the change is scoped enough that I don't *think* it will affect them materially and
(b) I understand that you need to optimize for the typical case at the moment.

**Comment by MarcPow** [comment]
/close.

This change has already been merged.
