### ISSUE TITLE
VisitPodSecretNames has cloud provider specific code

### ISSUE THREAD

**Issue by vboctor** [kubernetes/kubernetes#70855]
**What would you like to be added**:

The visitor function in the pod API highlights that there is no way to get the collection of secrets in a cloud provider agnostic way.

See the switch statement at:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/util.go#L52

**Why is this needed**:

Cloud provider specific code should be abstracted via the cloud provider implementations and not in core project code.  This is likely to avoid bugs in the future.

I'm new to the project, so apologies in advance if there is a good reason for the code being written this way (e.g. backward compatibility).

/sig api-machinery

/kind feature

**Comment by liggitt** [comment]
> get the collection of secrets in a cloud provider agnostic way

That method is returning all the secrets referenced from a pod spec. The ability to specify CSI volume sources in a pod spec is being implemented (
https://github.com/kubernetes/kubernetes/pull/68232). When that is added, secrets referenced from CSI volume sources will be added to that method, and allow arbitrary volume extensions. 

/close
